### ISSUE TITLE
BUG: runtest.py always fails tests_scripts.text_f2py on windows

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10016]
This is because `numpy.tests.test_scripts.test_f2py` tries to call `$python_dir/Scripts/f2py.py`, when in fact we're running in a (pseudo?) virtual env with its scripts at `$repo_dir/build/testenv/Scripts/f2py.py`.

There's a test there to disable this for `inplace` testing, but it's not clear what that means, and for whatever reason `runtests.py` is not considered "inplace".

Things have been like this for me since at least 1.12, but I figured I should create an issue for other people with the same problem

**Comment by kchomski-reef** [comment]
@eric-wieser what is your setup?

I've just tested this on `Win7_x86` and both `python2.7.14` and `python3.6.2` and it seems to be working:

```windows
(C:\Users\IEUser\Miniconda2) C:\Users\IEUser\projects\numpy-master>python runtests.py -v -t numpy\tests\test_scripts.py
Building, see build.log...
    ... build in progress
    ... build in progress
Build OK
Running unit tests for numpy.tests.test_scripts.py
NumPy version 1.14.0.dev0+Unknown
NumPy relaxed strides checking option: True
NumPy is installed in C:\Users\IEUser\projects\numpy-master\build\testenv\Lib\si
te-packages\numpy
Python version 2.7.14 |Anaconda, Inc.| (default, Oct 15 2017, 06:26:11) [MSC v.1
500 32 bit (Intel)]
nose version 1.3.7
numpy.tests.test_scripts.test_f2py ... ok

----------------------------------------------------------------------
Ran 1 test in 0.320s

OK

(C:\Users\IEUser\Miniconda2) C:\Users\IEUser\projects\numpy-master>
```

**Comment by eric-wieser** [comment]
At a glance - I'm using a pip-installed python environment, not Miniconda like you are.

**Comment by charris** [comment]
That test is very sensitive to the installation. I wonder a bit if we shouldn't just issue a warning and not fail.

**Comment by mhvk** [comment]
Ah, that explains an issue I suddenly had (on a Debian system); I had finally decided that I might need to replace `python setup.py install` with `pip install .`, and have been having these annoying error messages since.

**Comment by tynn** [comment]
Would it make sense to add the install `bin` or `Scripts` directory to `PATH`. I did this already to make my build work. But I'm not sure how to implement it platform independent. For the `site-package` the `distutils.sysconfig.get_python_lib` function provides the necessary information. Is there something for the scripts as well?
