### ISSUE TITLE
Bump NPY_API_VERSION for 1.14

### ISSUE THREAD

**Issue by xoviat** [numpy/numpy#10014]
I attempted this in my own PR but failed. The version needs to be increased to use WRITEBACKIFCOPY.

**Comment by xoviat** [comment]
@seberg Any way that you take care of this now? SciPy has test failures because of this issue.

**Comment by charris** [comment]
Take a look at `doc/HOWTO_RELEASE.rst.txt` around line 218 to see how to update it.

**Comment by charris** [comment]
See #10022.
