### ISSUE TITLE
PyArray_ResolveWritebackIfCopy should allow null values

### ISSUE THREAD

**Issue by xoviat** [numpy/numpy#10012]
Looking at the actual uses of the function, there are places where it needs to go after `PY_XDECREF`, where null values can be accepted. The function should do nothing if a null value is passed.

/cc @mattip

**Comment by eric-wieser** [comment]
Not a fan of this. Either require the user to write `if (arr) ...`, or provide a macro `PyArray_XResolveWritebackIfCopy`

**Comment by eric-wieser** [comment]
It's not pointless if it encourages them to think more carefully about their resource management.

**Comment by xoviat** [comment]
Look at how this will be actually implemented in SciPy. I'll just need to check for null values and then call updateifcopy before xdecref:

https://github.com/scipy/scipy/blob/74e4586fe99cb587b3c6d05ae81aaf2bc8b3a3a8/scipy/ndimage/src/nd_image.c#L197

I don't see the reason for putting this in scipy code as it will result in more code over all in the ecosystem.

**Comment by xoviat** [comment]
IIUC, we coerce the array here:

https://github.com/scipy/scipy/blob/74e4586fe99cb587b3c6d05ae81aaf2bc8b3a3a8/scipy/ndimage/src/nd_image.c#L127

into a format that we can operate on (specifically a behaved array).

After we're done working with the array, we need to write the results back.

**Comment by xoviat** [comment]
Specifically, if the given array meets the requirements (it's "behaved"), we operate directly on the given array. If not, we use numpy to create a copy that we can work with. Then after we're done with working on the copy, we delete the object to update the original array.

**Comment by eric-wieser** [comment]
In this case though, the right thing to do is `PyArray_DiscardWritebackIfCopy` rather than just `goto done`, right?

> I don't see the reason for putting this in scipy code

If scipy provides `NI_ObjectToOutputArray`, then they should provide a matching `NI_DiscardOutputArray` else their abstraction is leaky.

**Comment by mattip** [comment]
in any case, the ``PyArray_ResolveWritebackIfCopy`` should be *before* any of the ``PY_XDECREF``, so if it can go before the ``exit`` label all should be OK, no?

**Comment by xoviat** [comment]
That's what I said. 

> NI_ObjectToOutputArray

IIUC that's private.

**Comment by xoviat** [comment]
> In this case though, the right thing to do is PyArray_DiscardWritebackIfCopy rather than just goto done, right?

Does this function update the original array?

**Comment by eric-wieser** [comment]
> Does this function update the original array?

No - which is the correct behaviour if the `ParseTuple` call fails.

**Comment by xoviat** [comment]
First, SciPy doesn't currently have that behavior (although maybe it should). Second, we still need to write the results back after NI_Correlate1D. But maybe `PyArray_ResolveWritebackIfCopy` should be called?

**Comment by mattip** [comment]
I am confused. In the link [you provided](https://github.com/scipy/scipy/blob/74e4586fe99cb587b3c6d05ae81aaf2bc8b3a3a8/scipy/ndimage/src/nd_image.c#L197) it should be sufficient to put a call to ``PyArray_ResolveWritebackIfCopy(output)`` on line 193, before the ``exit`` label. In this case ``output`` cannot be ``NULL``, correct?

**Comment by xoviat** [comment]
> I am confused. In the link you provided it should be sufficient to put a call to PyArray_ResolveWritebackIfCopy(output)

Yes, except it's going to go for all of the XDECERF(output)

> In this case output cannot be NULL, correct?

It *can* be null, hence the XDECREF.

**Comment by xoviat** [comment]
Thanks. I think I understand the way forward now.

**Comment by eric-wieser** [comment]
> It can be null, hence the XDECREF.

Not _before_ the `exit` label, it can't. To resolve ambiguity here:

```
static PyObject *Py_Correlate1D(PyObject *obj, PyObject *args)
{
    PyArrayObject *input = NULL, *output = NULL, *weights = NULL;
    int axis, mode;
    double cval;
    npy_intp origin;

    if (!PyArg_ParseTuple(args, "O&O&iO&idn" ,
                          NI_ObjectToInputArray, &input,
                          NI_ObjectToInputArray, &weights, &axis,
                          NI_ObjectToOutputArray, &output, &mode, &cval,
                          &origin))
        goto exit;

    NI_Correlate1D(input, weights, axis, output, (NI_ExtendMode)mode, cval,
                   origin);

    PyArray_ResolveWritebackIfCopy(output);
exit:
    Py_XDECREF(input);
    Py_XDECREF(weights);
    Py_XDECREF(output);
    return PyErr_Occurred() ? NULL : Py_BuildValue("");
}

**Comment by mattip** [comment]
sorry. If there is a way to prevent others from having the same issue, please let me know. Perhaps the docs are not clear enough

**Comment by eric-wieser** [comment]
So it seems to me that  `PyArray_XDiscardWritebackIfCopy` would be useful when paired with converter functions, but the cost of the `if` is not that big.

**Comment by xoviat** [comment]
IHMO don't spend more time on this.
