### ISSUE TITLE
repr change for arrays of size 1 even with np.set_printoptions(legacy=True) in numpy master

### ISSUE THREAD

**Issue by lesteve** [numpy/numpy#10026]
In scikit-learn we have seen failures in doctests for a few days on our build using numpy-dev. This is one of them:

```py
import numpy as np

try:
    np.set_printoptions(legacy=True)
except Exception:
    pass

print(repr(np.array([0.])))
print(repr(np.array([[0.]])))
print(repr(np.array([1., 2., 3.])))

```

With numpy master:
```
array([0.])
array([[0.]])
array([ 1.,  2.,  3.])
```

With numpy 1.13 (note the space before the 0):
```
array([ 0.])
array([[ 0.]])
array([ 1.,  2.,  3.])
```

**Comment by charris** [comment]
It's a feature, not a bug ;) The default print formatting will change in 1.14. We are aware that this will break doctests. From the release notes
```
Changes to array printing, and the new "legacy" printing mode.
--------------------------------------------------------------
The new ``sign='-'`` option (see new features below) causes the ``repr`` of
float arrays to often omit a whitespace previously printed in the sign
position, and 0d arrays also now print with small whitespace and precision
differences (see changes below). These changes are likely to break downstream
user's doctests.

These new behaviors can be disabled to mostly reproduce numpy 1.13 behavior by
enabling the new "legacy" printing mode. This is enabled by calling
``np.set_printoptions(legacy=True)``, or using the new ``legacy`` argument
to ``np.array2string``.
```
Note that there are various ways to relax whitespace sensitivity of doctests which are probably worth looking into if you want to continue to rely on doctests. @ahaldane Further suggestions?

**Comment by charris** [comment]
Note that there are more changes than you show, for instance
```
In [1]: print(repr(np.array([1., 2., 3.])))
array([1., 2., 3.])
```
Note missing spaces.

**Comment by charris** [comment]
Oops, I see that you did use the legacy mode, so we can maybe fix that.

**Comment by lesteve** [comment]
> Oops, I see that you did use the legacy mode, so we can maybe fix that.

That would be great!

For now our strategy is to use the legacy mode to have compatibility of our doctest with numpy 1.14dev and 1.13. When numpy 1.14 is released we will revisit our strategy. One possible solution is to update all of our doctests to work with 1.14 and just skip them for numpy <= 1.13.

**Comment by amueller** [comment]
I'm confused. So did numpy decide to definitely break, regardless of the sign/legacy setting?

**Comment by amueller** [comment]
Something that was printed as 1.0 is now printed as 0.99999999(...?) is that also a feature?

**Comment by ahaldane** [comment]
What code exactly printed `0.99999999`? There is a new float printing algorithm in 1.14 which, barring a bug, should print just like a python3 float.

**Comment by ahaldane** [comment]
I'll take a look at the space in the legacy option, I'm pretty sure that is a fixable bug.

**Comment by lesteve** [comment]
> What code exactly printed 0.99999999? There is a new float printing algorithm in 1.14 which, barring a bug, should print just like a python3 float.

There is a case for `np.set_printoptions(legacy=True)` to implement the pre-dragon4 printing. I am not sure it is worth the cost, I'll open a separate issue to discuss this. FWIW in scikit-learn we have managed to work around these issues by using doctest ellipsis.

**Comment by charris** [comment]
Just a quick update, it is now `legacy='1,13'` to get the old printing.
