### ISSUE TITLE
numpy scalars: should np.set_printoptions(legacy=True) in 0.14.dev reverts to 0.13 printing?

### ISSUE THREAD

**Issue by lesteve** [numpy/numpy#10029]
This is another thing we bumped into our scikit-learn doctests using numpy dev. If this is easy for `np.set_printoptions(legacy=True)` to use pre-dragon4 printing it would make our life (and the life of other downstream projects bumping into the same problems with doctests) a bit easier when numpy 1.14 is released.

I think the expected behaviour is that `np.set_printoptions(legacy=True)` does revert to pre-dragon4 format even with all its flaws. If this is not too costly in terms of maintenance, maybe it could be considered? Note we can work-around this issue with doctests ellipsis in scikit-learn.

A snippet to illustrate what I mean in more details:
```py
import numpy as np

try:
    np.set_printoptions(legacy=True)
except TypeError:
    pass

i = 6
numpy_number = np.float64(1.) - i * 1e-17
print('str  : ', numpy_number)
print('repr : ', repr(numpy_number))
```

Output on numpy master:
```
str  :  0.9999999999999999
repr :  0.9999999999999999
```

Output on numpy 1.13:
```
str  :  1.0
repr :  0.99999999999999989
```

When using `np.set_printoptions(legacy=True)` I would expect both output to match.

**Comment by ahaldane** [comment]
OK, this is due to our choice to make floating scalars always print like in python3, we discussed this here: https://github.com/numpy/numpy/pull/9966#issuecomment-342016883. In python2 the str of floating scalars gets truncated.

I'll see if we can get it to truncate in python2 in legacy mode.

**Comment by lesteve** [comment]
OK so this is not related to dragon4 but to discrepancies between numpy scalars and Python floats , sorry for the confusion.

I think the more generic questions are: 
1. should numpy 1.14 + `np.set_printoptions(legacy=True)` print/repr exactly the same as numpy 1.13?
1. How hard is it to do?
1. Is it worth the maintenance cost?

As a numpy user, I think the answer for 1. is "ideally yes". There are a bunch of print/repr change from numpy 1.13 to 1.14 and I would expect `np.set_printoptions(legacy=True)` to revert all of them.

numpy developers are better placed to comment on 2.

I guess for 3. a combination of numpy users and developers is needed. The perspective I can give from scikit-learn maintenance point of view: we can work around it for doctests and I am more than fine with working around it.

Just to be explicit, as a scikit-learn maintainer I am of course well-aware of the cost and pain of not being able to get rid of less than optimal code for backward-compatibility reasons.
