### ISSUE TITLE
Substract Performance Issue

### ISSUE THREAD

**Issue by davinci26** [numpy/numpy#10037]
I encounter the following strange behaviour. This code is unstainably slow to run. 
`
import numpy as np
b = np.random.rand(1332200,1)
a = np.random.rand(1332200,)
b-a
`
Whereas this code, runs almost instantly.
`
import numpy as np
b = np.random.rand(1332200,1)
a = np.random.rand(1332200,1)
b-a
`
Another weird observation is that the following code runn
`
import numpy as np
b = np.random.rand(1332200,1)
a = np.random.rand(1332200,)
a - b
`

I am on: Python 3.6.3 and Numpy 1.13.3 and Operating System: MacOS  Sierra 10.12.6.
Is this expected behavior? If so can I get an explanation on why it happens?

Thanks alot!!!!

**Comment by bashtage** [comment]
These don't produce the same results.  The first uses broadcasting is shoudl produce a 1332200 by 1332200 array
```
b = np.random.rand(3,1) 

a = np.random.rand(3,)

b-a
Out[326]: 
array([[-0.35415731, -0.28276946,  0.08650954],
       [-0.59886639, -0.52747853, -0.15819953],
       [-0.28698925, -0.2156014 ,  0.15367761]])
```

The second doesn't use broadcasting and so produces a single 1332200  by 1 array.
