### ISSUE TITLE
numpy/core/code_generators/generate_numpy_api.py: error: returning a value from a constructor

### ISSUE THREAD

**Issue by looooo** [numpy/numpy#10035]
Can someone have a look at this. I am trying to port a library (which uses numpy from c++) to python3.6 but get this error:

```
<_b_env>/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:35: error: returning a value from a constructor
 #define NUMPY_IMPORT_ARRAY_RETVAL NULL
```

https://github.com/numpy/numpy/blob/master/numpy/core/code_generators/generate_numpy_api.py#L124L130

---------------------------------------------------------
system info:
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
ubuntu 17.10 / linux 64
the bindings I try to port to py3 can be found here:
https://github.com/looooo/dakota/blob/6.7-clone/src/PythonInterface.cpp

**Comment by looooo** [comment]
Does anybody know why those conditional (mentioned lines, py2 vs py3) are needed. Maybe something related to windows?

**Comment by eric-wieser** [comment]
It's because on python 3, the `PyMODINIT_FUNC` type has a return value, but on python 2 it does not - the macro is designed to be used inside one of these functions.

**Comment by looooo** [comment]
thanks. I don't know how exactly this function works, but wrapping an additional function around it works for me with py2 and py3.
https://github.com/looooo/dakota/blob/6.7-clone/src/PythonInterface.cpp#L43L50

**Comment by looooo** [comment]
@eric-wieser  does I have to store the returned pointer somewhere (for py3)? I get a segfault in release-mode and the program seems to run in debug-mode...
