### ISSUE TITLE
datetime64 not present in intersphinx inventory

### ISSUE THREAD

**Issue by dstansby** [numpy/numpy#10039]
Hello, over at Matplotlib we're trying to reference your docs on `datetime64` objects, but it doesn't look like there is an entry in the numpy intersphinx inventory. Running the following doesn't produce any output:

```bash
python -m sphinx.ext.intersphinx 'https://docs.scipy.org/doc/numpy/objects.inv' | grep 'datetime64'
```

The grep can be removed to see the whole numpy intersphinx inventory. xref https://github.com/matplotlib/matplotlib/issues/9802

**Comment by shoyer** [comment]
Hmm... I'm not an expert in how our docs pick up these references but this seems like something that should be easy to fix.

In the meantime, this is probably the best page to reference on datetime64: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.datetime.html

**Comment by dstansby** [comment]
Maybe needs an autoclass entry? We fixed something similar in Matplotlib here: https://github.com/matplotlib/matplotlib/pull/8175

I'll try and have a go later today.

**Comment by melissawm** [comment]
Now,

```
$ python -m sphinx.ext.intersphinx 'https://numpy.org/doc/stable/objects.inv' | grep 'datetime64'
        numpy.datetime64                         reference/arrays.scalars.html#numpy.datetime64
```

so I think this issue can be closed. Please reopen if this is not the case.
