### ISSUE TITLE
ENH: Equivalent to pandas quantile in numpy

### ISSUE THREAD

**Issue by rdturnermtl** [numpy/numpy#10033]
Numpy uses the np.percentile function to find the empirical percentiles taking the inputs in [0, 100], while pandas' quantile does the same thing except on a [0,1] scale.

It seems the pandas' [0,1] scale is much cleaner since most people in prob/stat pass probabilities around in their code and np.percentile results in a lot of multiplications and divisions by 100 in the code.

This code be done by another optional argument to percentile or by implementing a np.quantile, which would provide complete consistency with pandas.

**Comment by eric-wieser** [comment]
See #9213
