### ISSUE TITLE
numpy.ma.dump and np.ma.load fail to close the files that they open

### ISSUE THREAD

**Issue by r-owen** [numpy/numpy#10045]
numpy 1.13.1 dump fails to close the file that it opens (as a unit test in our code reported). The code appears to be as follows, which is clearly not closing the file it might open:
```
def dump(a, F):
    if not hasattr(F, 'readline'):
        F = open(F, 'w')
    return pickle.dump(a, F)
```

**Comment by orbit-stabilizer** [comment]
Which file is this code located in?

**Comment by charris** [comment]
`numpy/lib/format.py`.

**Comment by orbit-stabilizer** [comment]
Sorry for my ignorance, I've just started contributing, but I'm confused as to whether we can just add F.close() after we have opened the file. It seems like we cannot since we return F after, so we don't want to close it. Am I thinking about this correctly?

**Comment by rkern** [comment]
You are thinking about it correctly, but it's easy enough to put in an `if` test to guard that case. I'd write it like so:

```
def dump(a, F):
    close_the_file = False
    if not hasattr(F, 'readline'):
        # Assume this is a filename, so open a new file object.
        close_the_file = True
        F = open(F, 'w')
    try:
        pickle.dump(a, F)
    finally:
        if close_the_file:
            # We own the file object, so clean it up explicitly.
            F.close()
```

All told, it's probably not a big deal as in all Python implementations under which numpy runs (that I am aware of), when the function returns, `F` goes out of scope, the opened file object will be cleaned up, and the file handle will be closed at that time.

**Comment by eric-wieser** [comment]
Why on earth is `np.ma.dump` a thing at all?

**Comment by njsmith** [comment]
> All told, it's probably not a big deal as in all Python implementations under which numpy runs (that I am aware of), when the function returns, F goes out of scope, the opened file object will be cleaned up, and the file handle will be closed at that time.

On CPython the opened file object is cleaned up immediately, but other implementations like PyPy generally only guarantee that the file object is cleaned up "eventually". (They don't do refcounting, so all deallocations wait until a GC pass happens.) On such implementations, you can have problems if you e.g. call `np.dump` in a loop, and run out of file descriptors before the GC runs.

It's not exactly a showstopper urgent bug, but it would be better to explicitly close the file here.

**Comment by njsmith** [comment]
Oh, it's actually `np.ma.dump` and it's useless? That makes this feel even less urgent :-)

**Comment by eric-wieser** [comment]
Yep, `np.dump is pickle.dump` with no wrapping whatsoever, which is also a little questionable.

**Comment by njsmith** [comment]
Where do you see that? I get:

```
In [1]: np.dump
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-c704d89a0831> in <module>()
----> 1 np.dump

AttributeError: module 'numpy' has no attribute 'dump'

In [2]: np.__version__
Out[2]: '1.13.3'
```

**Comment by timj** [comment]
```
$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 18:10:31) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> f = np.array([1,2,3])
>>> f.dump()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: dump() takes exactly 1 argument (0 given)
>>> np.__version__
'1.13.1'
>>> 
```

The method is in the public API and has not been marked deprecated. On CPython if you use it with warnings enabled you get a ResourceWarning:

```
ResourceWarning: unclosed file <_io.BufferedWriter name=‘bf_kernel.pkl’>
```

The fix is trivial (close the file if you opened it) so it would be great if we could add the fix for the next patch release. Shall I make a pull request for this? The example above from @rkern seems fine to me (I don't think `pickle.dump()` is documented to return anything so the `return` in the current version of the code doesn't give us anything.

Regarding the comment above about it wrapping pickle with no extra wrapping, it does let you dump to a filename rather than a file handle, which can be handy when you are debugging.

I have no objection to these functions being given a DeprecationWarning for v1.14 if that's where people want to go,although  I am guessing there should be a wider discussion than on this issue?

**Comment by eric-wieser** [comment]
> Where do you see that?

Apologies, I was testing `np.loads is pickle.loads`, which does return `True`. You're right, there is no `np.dump`

**Comment by eric-wieser** [comment]
> it does let you dump to a filename rather than a file handle, which can be handy when you are debugging.

Not in python 3, it doesn't, thanks to #5491. So on that basis, no one is using that feature except on python 2.7, which is approaching EOL.

`np.save` can be used to write directly to a filename too, but is specific to numpy arrays.

**Comment by orbit-stabilizer** [comment]
Ah, I see. Why was `pickle.dump(a, F)` being returned in the previous case?

**Comment by timj** [comment]
I'm a bit shocked that it's taken 3 years to not add the `b` in the `open` call. @orbit-stabilizer your code does work (with the right `wb`) but it's a question of whether you duplicate the call to `pickle.dump` or not. I'm fine with that approach as well.

PS We are using python3.

**Comment by eric-wieser** [comment]
@timj: I've of the opinion that if it's been broken since the beginning of time for python 3, and the existance of the function is unjustifiable, we should leave it broken, but with a clearer error message - this is a great time to remove it from the API in anticipation of the Py3 only version of numpy.

**Comment by njsmith** [comment]
I guess there could be people using it on py3 and explicitly passing in a
pre-opened binary file? I do like the idea of getting rid of it though if
we can – every extra method on ndarray makes more work for everyone
implementing a new duck-array type.
