### ISSUE TITLE
"None" on Numpy Documentation Page

### ISSUE THREAD

**Issue by clintonyeb** [numpy/numpy#10048]
There appears to be a bug in the reference documentation. Please check and rectify.

There is a None on top of the page.

[Numpy Documentation](https://docs.scipy.org/doc/numpy/)

![numpy-none](https://user-images.githubusercontent.com/13755676/32979294-88b950e4-cc78-11e7-8b96-f0519dac69cb.png)

**Comment by charris** [comment]
Pretty sure this is a duplicate and has been solved.

**Comment by charris** [comment]
Ah, here it is: https://github.com/numpy/numpydoc/issues/109.

**Comment by charris** [comment]
And here: #9676.

**Comment by clintonyeb** [comment]
But it definitely hasn't been solved. It's still there..

**Comment by charris** [comment]
It won't go away until the docs are regenerated, probably for 1.14.
