### ISSUE TITLE
Responsible of this repository

### ISSUE THREAD

**Issue by TelecomAnin** [numpy/numpy#10050]
Hi !!
when i read your Readme and some files i have a pain know to find exactely the responsible of this project.

Thk

**Comment by charris** [comment]
Lots of people are responsible for the project, what is it that you want to know?

**Comment by seberg** [comment]
Maybe we should make the governance stuff more discoverable? I am not sure how you actually reach it right now. But overall, I think it is a community project, so that for most things the mailinst list is basically correct?

**Comment by TelecomAnin** [comment]
Yes of course , thank you .
But for one class's subject i need some informations (numpy repository's history, Is it NumFocus the organisation who supervise the project? ...)
If it is possible i would have an email of one contributor in order to avoid sending issue on your repo.
Best regards !

**Comment by xoviat** [comment]
See 

- https://docs.scipy.org/doc/numpy-dev/dev/governance/governance.html
- https://docs.scipy.org/doc/numpy-dev/dev/governance/people.html#governance-people

**Comment by TelecomAnin** [comment]
Thank you very much for your help .


The information I gathered from this repository is clearer about the
governance and concepts around this project thanks to the 2 links I
received. For this purpose add more description in the readme would not be
bad. And I am willing to do it.

Best regards !!!

2017-11-20 23:31 GMT+01:00 xoviat <notifications@github.com>:
