### ISSUE TITLE
legacy 1.13 printing edge case: missing superfluous comma after ellipsis

### ISSUE THREAD

**Issue by lesteve** [numpy/numpy#10059]
I think this is the last quirk that we found when running the scikit-learn doctests. After this one you will hopefully not hear from me for a while ;-). We have only one doctest affected by this and we can work around this easily by using `repr` instead of `print` or using doctest ellipsis.

This edge case does break the `legacy='1.13'` promise so I thought I would let you know and then you can decide whether you want to fix it (i.e. match the buggy behaviour with `legacy='1.13'`)  or not. I would completely understand if you just decided to close this issue

```py
import numpy as np

try:
    np.set_printoptions(legacy='1.13')
except TypeError:
    pass

print(np.arange(10000))
```

Output numpy dev:
```
[   0    1    2 ... 9997 9998 9999]
```

Ouput on 1.13.3 (note the additional comma after the ellipsis):
```
[   0    1    2 ..., 9997 9998 9999]
```

**Comment by eric-wieser** [comment]
Yep, this was #9777/#9815, which was before we settled on the `legacy` API, I think.

It's pretty straightforward to fix this, so I'm inclined to say we should, even if it was a bugfix.

**Comment by charris** [comment]
@ahaldane @eric-wieser Has this been fixed?

**Comment by eric-wieser** [comment]
No, this is still outstanding
