### ISSUE TITLE
test_path_type_input hangs when running the test suite

### ISSUE THREAD

**Issue by jmwoloso** [numpy/numpy#10060]
Hello!

Linux Mint: 18.3 (Sylvia)
Python: 3.6.3
NumPy: 1.13.3
Cython 0.27.3

I am trying to build numpy and scipy wheels from source using the intel mkl compilers. Numpy compiles just fine, however when I run the test suite, the suite hangs on `test_path_type_input` within `test_einsum.TestEinSumPath` (or maybe the test after it? not sure because the last test name visible is this one; see screen cap)

Running the test suite for scipy results in the suite hanging on `test_lapack` within `test_build.TestF77Mismatch`

In both cases (numpy and scipy) the tests run and pass fine when run individually, so I'm not sure what else might be the cause.

Any help is greatly appreciated. See screen shot for images of the test suites when they're stuck is included.
![numpy](https://user-images.githubusercontent.com/7530947/33036734-90a4cba6-cdec-11e7-8014-025c4f0904f1.png)
![scipy](https://user-images.githubusercontent.com/7530947/33036738-92df0c24-cdec-11e7-93f7-0b0417779e7c.png)

**Comment by mattip** [comment]
A couple of things to try, since this might be specific to your setup:
- what happens when you use a different compiler?
- what is your memory use/cpu use when it is hung? Perhaps you are running out of memory and hitting a swap file?

**Comment by jmwoloso** [comment]
@mattip Thank you for the suggestions. I tried compiling with gcc instead of mkl and the tests run fine now and pass, so it's obviously an intel mkl issue (once again, go figure). Closing. Thank you again!

**Comment by oleksandr-pavlyk** [comment]
It is an Intel OpenMP issue. A work-around is to either set `KMP_INIT_AT_FORK=FALSE` prior to launching the NumPy’s test suite, or use TBB threading layer, but setting `MKL_THREADING_LAYER=TBB` prior to launching python. 

Yet another work-around is to use an older version of `libiomp5` (get the shared object library from Anaconda's cloud and overwrite what is installed with MKL).

**Comment by mattip** [comment]
Does this issue also come up in production environments?
We should at least document this somewhere, perhaps in doc/source/dev/development_environment.rst

@oleksandr-pavlyk can you suggest some wording that would maximize the likeleyhood that google will point people in the right direction?

**Comment by oleksandr-pavlyk** [comment]
@mattip Yes, hangs can occur in a production environment as well, and afflict problems that do not use MKL, but use Intel OpenMP.  It's just that MKL uses Open MP as its default threading layer.

The new title of this issue is a little misleading, I'd say. The hang occurs in the compiler's run-time library, not in the compiler itself.

**Comment by mattip** [comment]
@oleksandr-pavlyk now is the titile closer to correct?

**Comment by oleksandr-pavlyk** [comment]
@mattip Please change it to "NumPy with Intel MKL as BLAS/LAPACK hangs in Intel OpenMP runtime".

It is important to state that this problem is specific to Intel OpenMP 2018.0.2, and is already fixed in sources, therefore the fix will be available at the next release cadence.

**Comment by mattip** [comment]
thanks for the clarification
