### ISSUE TITLE
Cannot Import scipy.special

### ISSUE THREAD

**Issue by bdenergy** [numpy/numpy#10064]
I updated scipy to 1.0.0 on the 25th of november. since then i haven't been able to import the module. it displays the following error: ImportError: DLL load failed: cannot find the specified module. i'm using Anaconda (64bit) Python interpreter, IDE Pycharm win 10

**Comment by eric-wieser** [comment]
Looks like you meant to direct this to [scipy/scipy](https://github.com/scipy/scipy)?

I can tell you in advance that they're going to want the full error message.
