### ISSUE TITLE
Thank you for pushing python 3!

### ISSUE THREAD

**Issue by LinxiFan** [numpy/numpy#10076]
This is probably inappropriate as a Github issue (feel free to close), but I just want to say thank you for the [proposal](https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst) to drop support for python 2. 

I've been advocating python 3 for a long time, and am repeatedly frustrated to see libraries that are under active development AND support python 2 only. Python 3 has been out for ~10 years. A decade in modern computing is forever!! Legacy codebase is not a good enough excuse: people moved away from Fortran to C eventually. Python 3 has very nice new language features, standard libraries, and much better semantic consistency. I'd have way less cognitive burden as a programmer if I don't need to allocate extra neurons to reconcile between 2 and 3. 

I'm so glad a community as powerful as Numpy is making such a gesture. It's an extremely strong signal to the Python world. I expect to see more schools teaching python 3 as a starter language instead of 2.7 _because of_ numpy team's decision! 

Thank you for moving us forward! Cheers!

**Comment by rth** [comment]
Also, someone from the core team might want to add approximate future numpy release timelines to the "Projects Timeline" at https://www.python3statement.org/ (cf [docs here](https://github.com/python3statement/python3statement.github.io#add-timeline-information)).

**Comment by eric-wieser** [comment]
Timeline was added in python3statement/python3statement.github.io#94.

I'm going to close this in the interest of reducing the number of open issues by one.
