### ISSUE TITLE
BUG: numpy.testing.assert_equal does not test values of datetime64/timedelta64 scalars

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#10081]
As reported by @matveich in #10004

Test cases:
```
>>> np.testing.assert_equal(np.datetime64('2000-01-01'), np.datetime64('2000-01-10'))
>>> np.testing.assert_equal(np.timedelta64(10, 'ns'), np.timedelta64(20, 'ns'))
```

Equality checks (`!=` and `==`) seem to work correctly, as does `np.testing.assert_array_equal`.

**Comment by matveich** [comment]
I discovered that in numpy 1.12.1 it works correctly

**Comment by eric-wieser** [comment]
Seems to have been introduced in #8421
