### ISSUE TITLE
numpy 1.13.3: `test_multiarray.TestClip` fail on architecture x32

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#10093]
Hello,
when building numpy 1.13.3 on x32, `test_multiarray.TestClip` fails an a way that makes the whole test suite to abort:

```
test_broadcast1 (test_multiarray.TestChoose) ... ok
test_broadcast2 (test_multiarray.TestChoose) ... ok
test_basic (test_multiarray.TestClip) ... python2.7-dbg: numpy/core/src/multiarray/lowlevel_strided_loops.c.src:832: _aligned_contig_cast_double_to_longdouble: Assertion `npy_is_aligned(dst, _ALIGN(_TYPE2))' failed.
Running unit tests for numpy
NumPy version 1.13.3
NumPy relaxed strides checking option: True
NumPy is installed in /<<PKGBUILDDIR>>/debian/tmp/usr/lib/python2.7/dist-packages/numpy
Python version 2.7.14 (default, Sep 17 2017, 18:50:44) [GCC 7.2.0]
nose version 1.3.7
Aborted
debian/rules:150: recipe for target 'override_dh_auto_install' failed
make[1]: *** [override_dh_auto_install] Error 134
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
debian/rules:18: recipe for target 'binary-arch' failed
make: *** [binary-arch] Error 2
```

(full log at https://buildd.debian.org/status/fetch.php?pkg=python-numpy&arch=x32&ver=1%3A1.13.3-1&stamp=1511734620&raw=0)

can you have a look?

thanks!

PS: this was originally reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874147

**Comment by charris** [comment]
Could you do a bisection to see if this is new?

**Comment by sandrotosi** [comment]
this has been around since at least 1.12.1

**Comment by njsmith** [comment]
Notice that x32 here is the weird ABI that's x86-64 except that it uses 32-bit pointers. It's not terribly surprising if our alignment handling code is somehow getting confused...

**Comment by eric-wieser** [comment]
Can you run it again with `PYTHONFAULTHANDLER=1` in your environment, and give the output?

**Comment by charris** [comment]
Hmm, so `Py_ssize_t` is not the same as `Py_intptr_t == npy_intp`. That's not so bad, but the other way round could *really* mess things up ...

**Comment by eric-wieser** [comment]
@charris: Can you elaborate on that remark? which is larger of `sizeof(Py_ssize_t)` and `sizeof(Py_intptr_t)`?

It does worry me somewhat that numpy uses `intptr` interally when it nearly always means `ssize_t`.

**Comment by charris** [comment]
Yeah, it worries me a bit too. Changing it by adding an index type or some such would be good, I don't think we actually use `npy_intp` or `npy_uintp` for pointers except for simd and possible few other places checking alignment. For most architectures they are both the same size. My guess it that usage for addresses is confined to `npy_uintp`. What we have is one of those inherited thingies probably going back to numeric and paleolithic C. `ptrdiff_t` and `size_t` didn't come in until C89, which took surprisingly long to become standard. Note the `ssize_t` is not in a C standard (it's POSIX), `intptr_t` and `uintptr_t` didn't come in until C99.

**Comment by charris** [comment]
Researching a bit more, `npy_intp` is a synonym for `Py_intptr_t`, which looks to be a synonym for C99 `intptr_t`, when it exists, and which is in turn a synonym for C89 `ptrdiff_t`. In other words, it is the (a?) correct type for indexing and pointer arithmetic, which is how we use it.

@sandrotosi Could you tell us what size `iinfo("intp")` and `iinfo("uintp")` show on that machine?

**Comment by seberg** [comment]
So it is the right type, but I would not be certain that Py_SSize_t/ssize_t isn't used synonymous at some points :/, and that would be incorrect then?

**Comment by GreenReaper** [comment]
For what it's worth, this is still happening. [Here's a recent build log from 1.16.2](https://buildd.debian.org/status/fetch.php?pkg=python-numpy&arch=x32&ver=1%3A1.16.2-1&stamp=1551554744&raw=0) - there's some errors related to tests involving f2py earlier that don't seem to occur on x86 32-bit, but I don't know enough to know if they're relevant.

**Comment by eric-wieser** [comment]
Since clip was rewritten in 1.17, I doubt the original issue still applies there, although I suppose we're still supporting 1.16.

It might be worth opening a new issue about einsum on longdouble and x32.

**Comment by sandrotosi** [comment]
closing outdated issues i reported long ago
