### ISSUE TITLE
numpy.linalg.svd doucmentation

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#10099]
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.svd.html#numpy.linalg.svd

says

> full_matrices : bool, optional
> compute_uv : bool, optional

but the defaults displayed are int, not bool.

**Comment by seberg** [comment]
Sure, probably some historic reason, want to open a pull request?

**Comment by eric-wieser** [comment]
This was fixed in 2d66d07330486ebfec287c01f6b57f0d37433c2d
