### ISSUE TITLE
loadtxt documentation

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#10098]
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.loadtxt.html

says

"converters : dict, optional A dictionary mapping column number to a function that will convert that column to a float. "

Should it not be a function converting to whatever the target dtype is (e.g. it might be complex)?

**Comment by seberg** [comment]
Sounds right, can you open a pull request with the suggested changes?
