### ISSUE TITLE
variance/covariance of high dimensional variable

### ISSUE THREAD

**Issue by Erichliu00** [numpy/numpy#10126]
I believe that it is necessary to compute variance/covariance of matrix-variable. 
For example, suppose we have a variable `x` with shape `[2,4]`, then given four different batches of input, we can have four values of `x`, say `xi= np.random.normal(0,1, [2,4])` for i = 0,1,2,3,  how can we compute the variance of `x` given four observations?
Neither `np.cov([x0, x1, x2, x3])` nor `np.cov(np.array([x0, x1, x2, x3]))`  works without error.

**Comment by bashtage** [comment]
You need to compute the covariance of the 1vec` of your data.  Something like 

```
np.cov(np.array(list(map(lambda a:a.ravel(),[x1,x2,x3,x4]))).T)
```
