### ISSUE TITLE
cumsum result has different dtype than input

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#10134]
When computing a `cumsum` on an array of an integer type other than int64, the result always has int64 type:
```python
import numpy

a = numpy.array([1, 2, 3], dtype=numpy.int8)
print(a.dtype)

b = numpy.cumsum(a)
print(b.dtype)
```
```
int8
int64
```
Is this intentional?

**Comment by pv** [comment]
Yes.

**Comment by mhvk** [comment]
Overflow is just too likely without it.

**Comment by mhvk** [comment]
This is documented for `np.cumsum`, and also in the documentation of the underlying ufunc methods: https://docs.scipy.org/doc/numpy/reference/ufuncs.html#methods

If this answers it, please close the issue.

**Comment by seberg** [comment]
The only tricky thing is, that the result has the C long type, so if you are a software package, could think about manually setting the dtype.
