### ISSUE TITLE
DOC: Function byte_bounds

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#10140]
There does not appear to be documentation for `byte_bounds` on the webpage despite it being available from the toplevel module and having a docstring. Not sure if this is an oversight or if this function should be private and has leaked out into the public API.

**Comment by eric-wieser** [comment]
Seems to me that need some kind of test suite to check that every function under `np.*` has a corresponding documentation page generated by sphinx

**Comment by jakirkham** [comment]
Thoughts on this one, @njsmith?

**Comment by njsmith** [comment]
Are you asking whether I think `byte_bounds` should be deprecated? I dunno, it seems like a pretty pointless function to me, but also harmless, so meh, I can't get too worked up about it. It's just a little Python wrapper around `__array_interface__`, which is a documented and stable API, so it's not a big maintenance problem.

**Comment by mattip** [comment]
Closing, it is now [documented](https://numpy.org/devdocs/reference/generated/numpy.byte_bounds.html)

**Comment by mattip** [comment]
1.
