### ISSUE TITLE
Feature request: adding phantom dimensions to an array

### ISSUE THREAD

**Issue by alexeymuranov** [numpy/numpy#10149]
I know that to obtain a multidimensional array where only certain dimensions count, i can use `meshgrid` or `tile`, at least if the array is not going to be modified.  These solutions however look inefficient and unnatural (using extra memory while no extra memory is really needed).

Wouldn't it be nice to have a method that creates a read-only (n + m)-dimensional view from an n-dimensional array by adding m "phantom" dimensions?

**Comment by seberg** [comment]
Normally, you do not need it, since broadcasting means (n, 1) can interact like (n, m) in most cases. Other then that there is `broadcast_to` (and friends) which does exactly that.
