### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by melvyniandrag** [numpy/numpy#10153]
Small documentation bug here
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html

>>> y = x['foo']
>>> y
array([ 2.,  3.], dtype=float32)

'foo' is [1,2], the integer column.

**Comment by eric-wieser** [comment]
Already fixed in the latest docs: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.rec.html
