### ISSUE TITLE
Add numpy.chop

### ISSUE THREAD

**Issue by AndrewBelt** [numpy/numpy#10173]
The name proposal is based on Mathematica's [Chop](http://reference.wolfram.com/language/ref/Chop.html), and a reference implementation (e.g. for float types) could be

```py
def chop(A, eps = 1e-10):
	B = np.copy(A)
	B[np.abs(A) < eps] = 0
	return B
```

With obvious implementations for np.complex* types.
Is there interest for this function?

**Comment by njsmith** [comment]
There's some resistance to adding simple helper functions to numpy at this point, so you might have trouble convincing folks. But if you want to pursue this, you should send an email to the numpy-discussion mailing list, and see what kind of response you get there – that's a general requirement for new APIs.

**Comment by eric-wieser** [comment]
> With obvious implementations for np.complex* types.

Not obvious to me. Are you trying to impose a `+`-shaped dead zone in the complex plane, or a circle around the origin?

Absolute epsilons strike me as dangerous too.

**Comment by AndrewBelt** [comment]
A circle around the origin. Anything else would be surprising behavior.

**Comment by eric-wieser** [comment]
> Anything else would be surprising behavior.

I agree - but now take a look at the mathematica `Chop` page, and you'll see it uses the cross region.

**Comment by AndrewBelt** [comment]
You are correct. Mathematica's `Chop` threads (as they call it) the function through each complex part.
For this reason, `chop` might not be an ideal name for those expecting Mathematica behavior to transfer perfectly to Numpy, but I doubt this is remotely a goal for Numpy. `trim` is too close to `trim_zeros` which has a different purpose, and `cut` sounds like slicing.

**Comment by shoyer** [comment]
I'm going to echo @njsmith's concern about adding simple helper functions to NumPy. I'm sure a need for this function comes up commonly with some workflows, but we already have primitives that make this easy to write yourself. There's nothing wrong with writing your own domain specific helper functions.

**Comment by AndrewBelt** [comment]
@shoyer If helpers are discouraged, is there a project (called something like `numpy.contrib`) that gathers these tools into a standardized package, or maybe a nonstandard but de-facto standard third-party library? I could think of hundreds of helpers like this which aren't implemented in Numpy, e.g. advanced functional programming on ndarrays, that would reduce total line length of most scripts in physics and data science by 2-3x.

**Comment by shoyer** [comment]
There are lots of domain specific packages, e.g., scikit-image, scikit-learn, AstroPy. I don't know of a generic package like NumPy-contrib.

**Comment by njsmith** [comment]
@AndrewBelt 
> I could think of hundreds of helpers like this which aren't implemented in Numpy, e.g. advanced functional programming on ndarrays, that would reduce total line length of most scripts in physics and data science by 2-3x.

I think if put up such a package with some good examples demonstrating 2-3x simplifications, then you'll get lots of interest!

**Comment by rgommers** [comment]
It's time to close this, we have broad consensus that we don't want too add simple helper functions like this. Thanks everyone.
