### ISSUE TITLE
Expose histogram bin estimators?

### ISSUE THREAD

**Issue by dstansby** [numpy/numpy#10183]
Would it be possible to expose the histogram bin estimators available in numpy? e.g. https://github.com/numpy/numpy/blob/e94ed84010c60961f82860d146681d3fd607de4e/numpy/lib/function_base.py#L393 and others.

We would find it useful in Matplotlib for computing bins without having to spend time computing the full histogram (xref https://github.com/matplotlib/matplotlib/issues/8636)

**Comment by eric-wieser** [comment]
Is the application here:

* Compute the bins for `np.concatenate([a, b, c])`
* Compute the histogram for each of a, b, c, using those bins?

That seems like a pretty reasonable application to me. I'm not sure if we should directly expose those functions, or just expose a `bins_only=True` argument to `np.histogram`.

**Comment by eric-wieser** [comment]
I'm not sure how we can expose the uniform range optimization in that use case, but I suppose optimality is not the primary concern.

**Comment by eric-wieser** [comment]
It's waiting on #10186, but I have a local patch that exposes `bin_edges = histogram_bins(a, bins=10, range=None, weights)`.

Does that sound like a reasonable API?

**Comment by dstansby** [comment]
I think the application is computing bins for `np.concatenate([a,b,c])`. All of your suggestions above sound good!

**Comment by shoyer** [comment]
I like the separate `histogram_bins` function.

**Comment by eric-wieser** [comment]
Alright, this is now trivial to patch on master in `np.lib.histograms` as

```python
def histogram_bin_edges(a, bins, range, weights):
    a, weights = _ravel_and_check_weights(a, weights)
    bin_edges, _ = _histogram_bins(a, bins, range, weights)
    return bin_edges
```
Most of the work here is to add a docstring, and some simple tests - so tagging as an easy fix

I suppose emailing the mailing list to confirm the function name could be valuable too.

**Comment by kirit93** [comment]
Does this issue still need to be worked on? If so, I'd like to work on this!

**Comment by eric-wieser** [comment]
@kirit93: Go for it!

**Comment by kirit93** [comment]
@eric-wieser Have you added this function to master? 
```def histogram_bin_edges(a, bins=10, range=None, weights=None):
    a, weights = _ravel_and_check_weights(a, weights)
    bin_edges, _ = _histogram_bins(a, bins, range, weights)
    return bin_edges
```
There's no function ```_histogram_bins``` in ```np.lib.histograms```. 

Shouldn't the function be 
```
def histogram_bin_edges(a, bins=10, range=None, weights=None):
    a, weights = _ravel_and_check_weights(a, weights)
    bin_edges, _ = _get_bin_edges(a, bins, range, weights)
    return bin_edges
```

I just need to add this function to ```np.lib.histogram``` with a docstring and add a test for this in ```np.lib.tests.test_histograms``` right?

Thanks!

**Comment by eric-wieser** [comment]
@dstansby: This will be in 1.15 - although matplotlib is currently 8 minor versions behind, so you could be waiting a long time!

I suppose you could backport the `np.lib.histograms` module in its entirety?
