### ISSUE TITLE
Reference loss with OutputConverter?

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#10197]
While discussing a secure risk of reference leaks, @eric-wieser worried that any time `PyArray_OutputConverter` is used in `PyArg_ParseTupleAndKeywords`, there might be reference leak with a well-placed failure. This issue is just to remind us we should investigate this.

**Comment by eric-wieser** [comment]
To clarify, the assumption is with calls of the form:
```c
if (PyArg_ParseTupleAndKeywords(args, kwds, "O&O&O&", kwlist, ConvertA, &a, ConvertB, &b, ConvertC, &c) < 0) {
    Py_XDECREF(a);
    Py_XDECREF(b);
    // assume that C is fine, because it was converted last - but there might be extra checks in ParseTupleAndKeywoards, so this is wrong
    return NULL;
}
```

**Comment by eric-wieser** [comment]
Closing as a non-issue - `PyArray_OutputConverter` creates no new references, so needs no associated cleanup

**Comment by mhvk** [comment]
OK, thanks for checking in detail.
