### ISSUE TITLE
Broken link in a doc (numpy.histogram)

### ISSUE THREAD

**Issue by olegserov** [numpy/numpy#10204]
The link from this page:
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.histogram.html
"Source code" leads to this page:
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy-histogram-1.py
that is 404

**Comment by eric-wieser** [comment]
Think there's a duplicate issue floating about somewhere for this...

I'm pretty surprised that a graph renders there at all - I was expecting some kind of sphinx directive to render it, but it just ... happens.

**Comment by eric-wieser** [comment]
Ah, duplicate of #9500.
