### ISSUE TITLE
extra-dll location in __config__.py incorrect if distribution name != package name

### ISSUE THREAD

**Issue by letmaik** [numpy/numpy#10219]
The `extra-dll` folder created in numpy's `build_ext` when building on Windows is based on the distribution name:
https://github.com/numpy/numpy/blob/447e7e4b1c7c8257fba45da00f62f4bc14c693d3/numpy/distutils/command/build_ext.py#L265-L266
However, the accompanying `__config__.py` file generated to locate this folder is based on the package directory in which `__config__.py` resides:
https://github.com/numpy/numpy/blob/cb4d8026f0cf5e25a61ecb1deb644656ed3bc3be/numpy/distutils/misc_util.py#L2286-L2291
This means that distributions whose name is not identical to their package name will not be able to use this auto-generated `__config__.py` file. I'm not sure what the proper solution looks like, but I have a feeling it will be something along the lines of:
```
req = pkg_resources.Requirement.parse(DISTRIBUTION_NAME)
extra_dll_dir = pkg_resources.resource_filename(req, DISTRIBUTION_NAME + '/extra-dll')
```
I used this successfully but I'm not sure if it's the best solution.

**Comment by pv** [comment]
pkg_resources probably cannot be used as the package/distribution is not 
installed when build_ext runs. However, distutils knows where it writes 
the __config__.py, so the `runtime_lib_dir` should be changed to match 
that in case the two are not the same.

**Comment by xoviat** [comment]
I tried to fix this with gh-10226, but there's not really a clean fix; the configuration object isn't passed through to `build_ext`.

**Comment by xoviat** [comment]
Update: I think I found a somewhat-reasonable solution.
