### ISSUE TITLE
ma.masked_values masking error

### ISSUE THREAD

**Issue by jblarsen** [numpy/numpy#10227]
```
>>> import numpy as np
>>> np.ma.masked_values(np.array([-32768.0]), np.int16(-32768))
masked_array(data = [-32768.],
             mask = False,
       fill_value = -32768.0)
```

So the resulting masked array is not masked. On the other hand it is masked
in the three cases below:

```
>>> np.ma.masked_values(np.array([-32767.0]), np.int16(-32767))
masked_array(data = [--],
             mask = [ True],
       fill_value = -32767.0)

>>> np.ma.masked_values(np.array([-32768.0]), -32768.0)
masked_array(data = [--],
             mask = [ True],
       fill_value = -32768.0)

>>> np.ma.masked_values(np.array([-32768.0]), -32768)
masked_array(data = [--],
             mask = [ True],
       fill_value = -32768.0)
```

It seems like it happens in masked_values due to:

```
>>> np.abs(np.int16(-32768))
-32768
```

since the range of np.int16 is [-32768; 32767].

See also mailing list discussion:

https://mail.python.org/pipermail/numpy-discussion/2017-December/077532.html

**Comment by eric-wieser** [comment]
Man, these function names are awful. Did you know, we have

* `masked_equal`
* `masked_values`
* `masked_object`

Where `values` is just `object` but without `isclose` semantics, and `_equal` is completely different to `_object`, in that it it supports subclasses but not broadcasting.
