### ISSUE TITLE
Tons of new nitpicky warning failures in daily build test.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#10222]
See https://travis-ci.org/MacPython/numpy-wheels/jobs/316861440#L2903. I expect there has been a change of compiler version or in warnings flags (`-Wextra` ?) .  Some of the new errors are due to such things as enums becoming unsigned ints by default, which is unusual, but many others come from signed/unsigned integer comparisons and look valid.

**Comment by charris** [comment]
Cause seems to be `-Wno-unused-result -Wsign-compare`.

**Comment by charris** [comment]
I'll guess that the new flags came in with the Python configuration flags.

**Comment by charris** [comment]
The `sign-compare` warnings are mostly due to a mix of `npy_uintp` and `npy_intp`. It isn't difficult to hack together a fix, but it is a bit trickier to decide on the *correct* fix. Note that `SIZEOF` returns unsigned values. Note also that `signed * unsigned` is `unsigned`, which makes indexing tricky when one of the operands is unsigned and the other possible negative.

I think we might want to stick with `npy_intp`, which is our effective array size, and change the functions `npy_blocked_end numpy` and `npy_aligned_block_offset` to work with that instead of the unsigned versions.

**Comment by eric-wieser** [comment]
Presumably #9705 hits a bunch of these

**Comment by charris** [comment]
Most of them are in the simd generated code and result from a mix of `npy_intp` and `npy_uintp` in the address manipulations. Most of the remainder are due to the fact that `sizeof` returns `size_t`, which is unsigned.

For the simd, I'm thinking that address offsets need to be signed (numpy standard), while addresses converted to numbers to check for alignment need to be unsigned. It's straight forward except there are a lot of size assumptions built in, all valid, but a bit tricky how to make the validity clear.

**Comment by mattip** [comment]
Builds now are clean, closing. Please reopen if needed
