### ISSUE TITLE
Misleading error message in numpy.ndarray.reshape

### ISSUE THREAD

**Issue by secsilm** [numpy/numpy#10221]
I found two weird errors with `numpy.ndarray.reshape()`.

**First**

```python
import numpy as np
np.__version__   # 1.13.3

arr = np.arange(10)
arr.reshape(shape=(5, 2), order='F')
```

Output:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-13-47391b175807> in <module>()
----> 1 arr.reshape(shape=(5, 2), order='F')

TypeError: function takes at most 1 argument (2 given)
```

**Second**

```python
import numpy as np
np.__version__   # 1.13.3

arr = np.arange(10)
arr.reshape((5, 2), 'F')
```

Output:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-7-61a92e6d5e91> in <module>()
----> 1 arr.reshape((5, 2), 'F')

TypeError: 'tuple' object cannot be interpreted as an integer
```

So, any idea on these two errors?

**Comment by eric-wieser** [comment]
These work fine:
* `arr.reshape((5, 2), order='F')`
* `arr.reshape(5, 2, order='F')`

**Comment by mhvk** [comment]
See https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/methods.c#L183
This might be quite an easy thing to fix, just use `PyArg_ParseTupleAndKeywords` -- the only odd thing is that at the top of that file a specific utility function is introduced to just parse keywords.

**Comment by seberg** [comment]
Error is better now (for whatevr reason), closing.
