### ISSUE TITLE
Travis is failing for Python 3.5 with no error message

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10239]
See [build #16778.8](https://travis-ci.org/numpy/numpy/jobs/318453194) for an example. [The logs](https://api.travis-ci.org/v3/job/318453194/log.txt) don't seem to help at all

**Comment by matthew-brett** [comment]
Maybe an example of https://github.com/travis-ci/travis-ci/issues/8920 ?

**Comment by charris** [comment]
Some sort of cache/file failure I think. It started about 3 days ago for merge tests, but not for PR tests. I didn't find any mentions of likely Travis environment changes when I looked, but I think that is where the problem is.

**Comment by matthew-brett** [comment]
Specifically, this fix works for a few projects that started failing a few days ago:

https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024

**Comment by charris** [comment]
Fix applied in #10252 and seems to be working: https://travis-ci.org/numpy/numpy/builds/319529106

**Comment by eric-wieser** [comment]
Think this can be closed, seems it was transient
