### ISSUE TITLE
Include SKIP in numpy.fromfile

### ISSUE THREAD

**Issue by rspadim** [numpy/numpy#10238]
Hi guys! could be possible include a SKIP parameter at numpy.fromfile (https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.fromfile.html), to skip first "rows" from file?

thanks!

**Comment by eric-wieser** [comment]
I think you can already do:

```
def skip(f, num_lines):
    for i in range(skip):
        f.readline()

with open(fname, 'w') as f:
    skip(f, num_rows)
    res = np.from_file(f)
```

**Comment by mhvk** [comment]
Any reason not just to use `loadtxt` for text files? This allows skipping rows already. I see `fromfile` as targeted more at binary files.

**Comment by mattip** [comment]
Closing as the original reporter did not respond to the suggestions. Please reopen if you are willing to engage in why the suggested solutions do not solve the issue
