### ISSUE TITLE
Structured array comparison fails for different subtypes

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#10235]
The below comparison seems like it should pass, but it does not. This may well be documented somewhere, but it still seems strange - if `astype` works, surely comparison should work too! Indeed, might it be a suggestion to try going via `astype` if the dtype do not match exactly?
```
dtype1 = [('a', int), ('b', float)]
dtype2 = [('a', np.int16), ('b', np.float16)]
x1 = np.array((1, 2.), dtype=dtype1)
x2 = x1.astype(dtype2)
x1 == x2
# /usr/bin/ipython3:1: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
# False
```

**Comment by ahaldane** [comment]
I recently updated the docs about this, see [the doc](https://github.com/numpy/numpy/blob/master/numpy/doc/structured_arrays.py#L470), also rendered [here](https://ahaldane.github.io/user/basics.rec.html#structure-comparison)

That's descriptive, not prescriptive, though. I just documented what the current state of things is.

**Comment by mhvk** [comment]
Thanks.  But note that the docs are not quite correct: `<` and `>` return `NotImplemented`, thus leading to a `TypeError` (correctly, I think)

**Comment by mhvk** [comment]
I guess my ideal behaviour would be that comparison simply proceeds element-wise, from left to right.

**Comment by ahaldane** [comment]
> `<` and `>` return `NotImplemented`

Hmm.. only in python3. The doc is correct in python2, and it looks my assumption that python3 would be the same was wrong!

**Comment by eric-wieser** [comment]
> I guess my ideal behaviour would be that comparison simply proceeds element-wise, from left to right.

Doesn't `ndarray.sort` already do this>

**Comment by mhvk** [comment]
>> I guess my ideal behaviour would be that comparison simply proceeds element-wise, from left to right.

> Doesn't `ndarray.sort` already do this?

That suggests the comparison operators could borrow from that -- though I was really thinking only about `==` and `!=`, which *have* to return something (ideally with the right broadcast shape...)

**Comment by mhvk** [comment]
Just to have links to the current implementation: things first go through [`array_richcompare`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arrayobject.c#L1266), and the example above breaks on its check whether `other.dtype` is equivalent in casting to `self.dtype`; after that, things pass on to [`_void_compare`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arrayobject.c#L1113).

Just changing the casting check to `NPY_UNSAFE_CASTING` makes the above case pass.

**Comment by seberg** [comment]
This works now (so long fields have the same names), closing.  (There is an other issue about potentiall allowing different field names.)
