### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by dchatterjee172** [numpy/numpy#10233]
`a=[[[0],[1]],[[1],[2],[3]]]`
`np.array(a) #works fine`
`np.array(a,np.int32) #throws ValueError`
`ValueError: setting an array element with a sequence.`
This looks weird!
numpy=1.13.3   
Linux

**Comment by seberg** [comment]
It is not, the first is weird (object array), numpy arrays need to have a regular shape. There are issues open to make the first fail unless object dtype is given explicitly, so closing.
