### ISSUE TITLE
Compound structured dtype question

### ISSUE THREAD

**Issue by rspadim** [numpy/numpy#10246]
Hi guys, i'm reading a complex array dtype from binary file, could any one help? 

the structure is:
       8 bytes     = Long    Current Time (unixtime stamp)
       8 bytes     = Long    Current Time (unixtime stamp in MiliSeconds)
       8 bytes     = Long    Server Time (unixtime stamp)
       8 bytes     = Long    Ticks from windows startup
       8 bytes     = Long    Microseconds from windows startup
       X[
          1 byte   = UChar (sensor on/off)
          8 bytes  = Double (sensor converted value)
          8 bytes  = Long (sensor raw value)
          ]

X is an array that can be 32 or 16, i'm setting 32 in this example:
```
dt = np.dtype([('a'         ,np.datetime64),
               ('b'      ,np.datetime64),
               ('c'           ,np.datetime64),
               ('d'        ,'u8'),
               ('e' ,'u8'),
               {'name':   ['f', 'g', 'h'] ,
                'formats':['u1','f8', 'u8']}    <- HERE IS MY PROBLEM, HOW CAN I MAKE THIS VARIABLE (16 OR 32?)
              ])
```
Thanks!

**Comment by shoyer** [comment]
NumPy does not support variable size dtypes. So I'm afraid you will not be able to directly read this binary file into a single NumPy array.

**Comment by eric-wieser** [comment]
Are you looking for
```
dt = np.dtype([('a' ,np.datetime64),
	('b' ,np.datetime64),
	('c' ,np.datetime64),
	('d' ,'u8'),
	('e' ,'u8'),
	('X', [
		('f', 'u1'),
		('g', 'f8'),
		('h', 'f8'),
	], 16),
])
```

**Comment by rspadim** [comment]
thanks @eric-wieser!  i did this:

        names  =["a","b","c","d","e"]
        formats=["<u8", "<u8", "<u8", "<u8", "<u8"]
        for i in range(0,X):
            names.append("a"+str(i))
            names.append("b"+str(i))
            names.append("c"+str(i))
            formats.append("<u1")
            formats.append("<f8")
            formats.append("<u8")
        np.dtype({'names':names,'formats':formats})

now my doubt is, how to do this with pandas, but it's another package not in this github, anyway, thanks a lot guys!

**Comment by eric-wieser** [comment]
@rspadim: Any reason for generating the field names as you do above, rather than using the subarray type I show?

**Comment by rspadim** [comment]
it was easier to handle variables later
