### ISSUE TITLE
ImportError: cannot import name 'multiarray' in Ubuntu

### ISSUE THREAD

**Issue by suparek** [numpy/numpy#10242]
my environment:
ubuntu server 16.04
apache2
django 1.11
python 3.6 (use conda env)

when i use shell，i write:
`import numpy`
`import numpy.core.multiarray`

it is all right

but when i use it in my django code。come error like this:
`Traceback (most recent call last):`
`[ 2017] [wsgi:error] [pid 24663:tid 139804098279168] [remote 192.168.10.3:53941]   File "/home/yangtao/miniconda3/envs/compoengine/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <modu$`
`[ 2017] [wsgi:error] [pid 24663:tid 139804098279168] [remote 192.168.10.3:53941]     from . import multiarray`
`[ 2017] [wsgi:error] [pid 24663:tid 139804098279168] [remote 192.168.10.3:53941] ImportError: cannot import name 'multiarray'`

why ? i use it in my conda env,

**Comment by charris** [comment]
Probably different installed Pythons in the different environments.

**Comment by seberg** [comment]
Yeah, check which python you are even using (maybe with `which python`) compared to the numpy that gets picked up, etc. Or something went wrong during install. Certainly it is not a numpy bug, though you can try asking here if you have more details. Also if you got stuff in your `PYTHONPATH` or such it might pick up the wrong thing, etc.
