### ISSUE TITLE
Memory leak when using slice notation

### ISSUE THREAD

**Issue by tomerv** [numpy/numpy#10273]
Running this snippet causes the memory usage to increase with every iteration:

```
lst = []
for i in range(1000):
    print(i)
    a = np.random.rand(10000000)
    lst.append(a[:10])
```

It seems that the list holds references to the original array, which takes a lot of memory. When wrapping with np.array(), the memory does not increase significantly, i.e. the original large array is deallocated on after iteration:

```
lst = []
for i in range(1000):
    print(i)
    a = np.random.rand(10000000)
    lst.append(np.array(a[:10]))
```

I would expect `a[:10]` to have the save behavior as `np.array(a[:10])`.

Numpy 1.12.1
Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
[GCC 4.8.4] on linux

**Comment by eric-wieser** [comment]
This is not a leak, because the memory is freed correctly when the list is freed.

You're correct that taking a small slice of a large array causes the large array to stick around, but that's pretty much by design.

**Comment by tomerv** [comment]
Yes, technically this is not a memory leak. Sorry for the inexact wording.

Regarding the design, the main issue is that this is unexpected behavior.
Compare with Python's native lists and their slices:
```
lst = []
for i in range(1000):
    print(i)
    a = np.random.rand(10000000)
    b = list(a)
    lst.append(b[:10]))
```
Here the memory usage doesn't increase, i.e. `b` is freed on every iteration.

**Comment by eric-wieser** [comment]
So to elaborate, this was a deliberate choice to make slices return views. That means the following happens
```
>>> a = np.zeros(4, int)
>>> b = a[2:]
>>> b[0] = 1
>>> a
array([0, 0, 1, 0])
```

`np.array(...)` causes a copy to be made, which explains why you don't see the behavior there

**Comment by tomerv** [comment]
Ok, I can't say I like this behavior, but I guess that's not going to change. Thanks for the explanation and providing a link to the docs.

**Comment by eric-wieser** [comment]
For completeness, the underlying large array can be accessed with `b.base`.

In principle we could shrink large arrays whose only only reference is via a smaller view, but that would be a little fragile to detect, and would break any code that relied on the `base` attribute.

The view behavior is incredibly useful, but that doesn't mean its not confusing. We (or a third-party package) could also possibly provide a `ndlist` type that does _not_ use view semantics for slicing, for people who have expectations similar to yours.

**Comment by tomerv** [comment]
I ran into this behavior when I did something like this:

`top_items = np.argsort(long_array)[:k]`

Perhaps this specific use-case could be improved? Note that the array that's returned from `np.argsort` is not binded to any name. In C++ that would allow the compiler to treat it as a temporary, and destroy it in the next statement. I don't know whether this is applicable to Python/Numpy.

(I know that argsort can be replaced by argpartition and argsort, and that's what I eventually did).

**Comment by eric-wieser** [comment]
There's now a precedent for treating temporaries specially (on some platforms) so that's a reasonable suggestion

**Comment by liwt31** [comment]
I've run into the same problem and it took me a lot of time to figure out why memory usage is way beyond expectation. I think it might be a good idea to add this kind of behavior to the indexing document as a kindly reminder (I'd be happy to help on this). 
FYI, I'm using the following code. Although I totally understand what's happening under the hood and I value the view mechanism, the overall result feels pretty weird:
```
def foo():
    a = np.random.rand(int(2e8))
    b = a[:100]
    return b
b = foo()
```

**Comment by mattip** [comment]
Documentation additions for clarity are always welcome. Perhaps we should have an example with `b = a[:100].copy()` with an explanation why anyone would want to do that.

**Comment by tomerv** [comment]
I support the suggestion to give b = a[:100].copy() as an example.
