### ISSUE TITLE
Cannot use inplace assignment when dtype would change

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10277]
For instance, the following fails:
```
dt = np.arange(10).astype('m8[D]')
dt += np.datetime64('now', 'D')
# TypeError: Cannot cast ufunc add output from dtype('<M8[s]') to dtype('<M8[D]') with casting rule 'same_kind'
```
while this works as intended:
```
dt = np.arange(10).astype('m8[D]')
dt = dt + np.datetime64('now', 'D')
```

We could give the former the semantics of the latter by returning `NotImplemented` from `ndarray.__iadd__` if the dtypes aren't compatible.

Is making this change desirable?

Arguments for:
* In place assignment can be used as an optimization, without breaking behavior for non-homogenous dtypes
* Consistency with python, where `+=` has semantics that vary by variable type.

Arguments against:
* `+=` no longer has "always mutates in place" semantics (that is now spelt `x[...] += y`)

**Comment by seberg** [comment]
I am -1 without thinking much about it. View/mutable vs. non-mutable is already complicated enough, this would make it completly intransparent.

**Comment by njsmith** [comment]
I agree with @seberg on this one.

**Comment by mattip** [comment]
would it be acceptable to special-case teach `timedelta` `__iadd__` about `dateteime` ?

**Comment by mattip** [comment]
ahh, I see the rule is that `timedelta` + `datetime` -> `datetime`, where in-place `timedelta` + `datetime` would have to change that.

**Comment by mattip** [comment]
Please reopen if there is a different direction that could make this work.
