### ISSUE TITLE
Check whether a binary ufunc is left-sparse or right-sparse.

### ISSUE THREAD

**Issue by hameerabbasi** [numpy/numpy#10274]
Hello! Is there a some way to check whether a binary ufunc is left-sparse or right-sparse? Let me show you what I mean:

```
z = x op y
```
Now, if `op` has the property that it is zero whenever `x` is zero, then it is left-sparse. If it is zero whenever `y` is zero, then it is right-sparse. For example, `numpy.multiply` is both left- and right-sparse. The operation `z = x * (1 + y)` is left-sparse but not right-sparse.

I could, of course, generate an array of random numbers just to check, but that would always have a chance of failing for specific cases.

**Comment by eric-wieser** [comment]
Your second example is no longer just a simple binary ufunc, but is really asking about compound expressions.

The simple answer is that there are not that many binary ufuncs, and almost all of them are symmetric (except power, division-related, copysign...) so you can just make a list yourself.

**Comment by hameerabbasi** [comment]
I guess even for compound expressions, if we had a tree somehow, we could derive the density relations. Thanks @eric-wieser! Okay to close on my side.

**Comment by eric-wieser** [comment]
Assuming `x` and `y` are custom subclasses of `ndarray`, you can build the tree as you go with `__array_ufunc__`, which will tell you the ufunc being called.
