### ISSUE TITLE
"Interesting" error message in np.ravel_multi_index

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#10285]
numpy 1.13.3, py 3.6, arch linux
```
In [8]: np.ravel_multi_index([None], (3))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-1d6691d53114> in <module>()
----> 1 np.ravel_multi_index([None], (3))

TypeError: Iterator operand or requested dtype holds references, but the REFS_OK flag was not enabled
```

I feel like this is leaking some internal details about ravel_multi_index and a simpler error message would be better.
Obviously not a huge deal, feel free to close if no action will be taken.

**Comment by seberg** [comment]
Well, it gives the npyiter/nditer error message for object dtype flag missing. Possibly one can even allow objects there (if it gets cast by the iterator or so), or a check earlier would be a bit nicer.

**Comment by eric-wieser** [comment]
Passing REFS_OK should be fine, because it will be rejected by the casting rule anyway.

Alternatively, perhaps the casting should just be checked first.

**Comment by WarrenWeckesser** [comment]
In the main development branch, and at least as far back as 1.20.1, we now get this:
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.22.0.dev0+1267.g1cadccc60'

In [3]: np.ravel_multi_index([None], (3,))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-742229366104> in <module>
----> 1 np.ravel_multi_index([None], (3,))

~/mc39numpy/lib/python3.9/site-packages/numpy-1.22.0.dev0+1267.g1cadccc60-py3.9-linux-x86_64.egg/numpy/core/overrides.py in ravel_multi_index(*args, **kwargs)

TypeError: only int indices permitted

```
Can we close the issue?

**Comment by seberg** [comment]
Agreed, that sounds good enough as an error message and a big improvement, lets close this (if someone is still unhappy, please just open a new issue/PR).
