### ISSUE TITLE
bug? over the "+=" command

### ISSUE THREAD

**Issue by Tiz97** [numpy/numpy#10280]
Dear guys, 
I have founded out that the "+=" command is dangerouse in python 3.x when used into the increasing of a work-variable and not a time-variable. Let me show: in the next sketch, which is the simplyfied essenctial part of a bigger program, I am trying to use it in order to create an array of increased arrays.
-------------------------------------------------------------------------------------------
import numpy as np
k=0
a=np.zeros(3)
b=[]

for k in range(0,10):
a  +=  np.array([1,1,1]) 
b.append(a)
------------------------------------------------------------------------

Now, the expected value for b was something like: 
b = [array([ 1.,  2.,  3.]), array([ 2.,  4.,  6.]), array([ 3.,  6.,  9.]), array([  4.,   8.,  12.]), array([  5.,  10.,  15.]), array([  6.,  12.,  18.]), array([  7.,  14.,  21.]), array([  8.,  16.,  24.]), array([  9.,  18.,  27.]), array([ 10.,  20.,  30.])]

while it went out to be:
b = [array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.]), array([ 10.,  20.,  30.])]

Now, I solved the matter by substituting line 7 with:
a  = a + np.array([1,1,1]) 
but I thought it was responsable to report it. Maybe just an old version of numpy? 

Thank for all your work, guys, this project is great and useful!

**Comment by seberg** [comment]
Arrays are views and in place is truly in place. This is expected and not even very special to numpy, the same happens e.g. if `a` is a list you append to.
