### ISSUE TITLE
GCC 8: Undefined _ZGVbN2v___log_finite when using -Ofast, missing -lm

### ISSUE THREAD

**Issue by archboy87** [numpy/numpy#10307]
I'm getting a failure when importing numpy 1.13.3 compiled with GCC 8:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 166, in <module>
>     from . import random
>   File "/usr/lib/python3.6/site-packages/numpy/random/__init__.py", line 99, in <module>
>     from .mtrand import *
> ImportError: /usr/lib/python3.6/site-packages/numpy/random/mtrand.cpython-36m-x86_64-linux-gnu.so: **undefined symbol: _ZGVbN2v___log_finite**

I've tried with both openblas 0.2.20 and lapack / cblas 3.8.0. I've recompiled cython, cblas & lapack with GCC 8, but this didn't change the result.

I've compiled my whole system (Arch) with gcc-libs 8.0.0 so I can't just use the working GCC 7 version:

> ImportError: /usr/lib/libgfortran.so.5: version `GFORTRAN_7' not found (required by /usr/lib/python3.6/site-packages/scipy/special/_ufuncs.cpython-36m-x86_64-linux-gnu.so)

I don't demand to support GCC 8 from you, but rather asking for the root causing this mutual incompatibility. Any ideas?

**Comment by xoviat** [comment]
No, we need to support GCC 8. It looks like `-lm` need to be passed to the linker command for mtrand (add `m` to the libraries). Would you mind submitting a PR with this fix?

**Comment by xoviat** [comment]
Try adding it here:

https://github.com/numpy/numpy/blob/f1d81d84a2c8e3f44c434d580ab988912f9a4c83/numpy/random/setup.py#L43

**Comment by juliantaylor** [comment]
`_ZGVbN2v___log_finite` is a a function from the glibc vectorized math library, numpy isn't using this.
With which flags are you compiling numpy? that function should only be used with `-ffast-math`

**Comment by eigenwillig** [comment]
Yes, I'm using `-march=native -Ofast`. I know, that ffast-math leads to some round, but I never had a single problem with this.

**Comment by rgommers** [comment]
This should be fixed, `numpy/random/setup.py` contains:
```
mtrand_libs = ['m', 'npymath'] if os.name != 'nt' else ['npymath']
```
Closing, thanks everyone.
