### ISSUE TITLE
np.random.shuffle(arr) vs np.random.shuffle(np.array(arr))

### ISSUE THREAD

**Issue by dragen1860** [numpy/numpy#10304]
```
arr = np.arange(10)
np.random.shuffle(arr) 
```
works normal as usual.
However, when you use `np.random.shuffle(np.array(arr))` to run the shuffle, the content of `arr` remains unchanged!
Why? Is it a bug?

**Comment by eric-wieser** [comment]
`np.array` has a default argument `copy=True`, meaning you're shuffling a temporary copy, not `arr`
