### ISSUE TITLE
Unnecessary flop in exponential simulation?

### ISSUE THREAD

**Issue by dlsun** [numpy/numpy#10306]
https://github.com/numpy/numpy/blob/7255987a11c8b90ff525ad178419b22508164e23/numpy/random/mtrand/distributions.c#L112

-log(U) has the same distribution as -log(1 - U), so is Numpy doing one extra unnecessary flop?

**Comment by charris** [comment]
As the comment says, ` 1 - U` is never zero, while `U` may be. The ideal would probably be to have a uniform distribution in `(0, 1]`, which could be obtained with integer arithmetic before conversion to a float.

**Comment by bashtage** [comment]
If you care about flops you should use a Ziggurat implementation of the exponential.  There is one  [here](https://github.com/bashtage/ng-numpy-randomstate) and it is about 10x faster than using the log.

**Comment by charris** [comment]
@bashtage That reminds me that I have a cleaner implementation of the gaussian ziggurat that I should send you. I've had it sitting around for 10 years or so. It got tested way back when. The simplification was to include the majorizing exponential function as part of the base of the ziggurat, which got rid of the extra loop for that case. Here were some of the results that Bruce Carneal got at that time.

>I've completed timing and robustness tests that should
allow apples to apples comparisons of the mtrand normal distribution
possibilities.  The short story goes like this:
>
> 0) One of the 'Harris' ziggurats, zig7, passes all TestU01 crush tests
    when running atop each of five PRNGS.
>
 >1) Depending on how fast the underlying PRNG is, zig7
    outperforms Box_Muller by ~1.3X to ~8.5X.
>
 >2) using gcc, mwc8222+zig7 outperforms mt19937+Box_Muller by 7X.

**Comment by charris** [comment]
Timings here for 32 bit mt19927:
```
mt19937 trng: 6.52459e+06 ops per second
mt19937 boxm: 1.28223e+07 ops per second
mt19937 zig7: 5.00116e+07 ops per second
mt19937 zig8: 5.41123e+07 ops per second
mt19937 zig9: 5.47083e+07 ops per second
```
The cleaned up ziggurat is about 10% faster than the original Doornik ziggurat.

**Comment by bashtage** [comment]
I'm currently using Julia's implementation, so I'm not sure how this compares to those.

**Comment by bashtage** [comment]
xref #13163 . This is fixed in the randomgen branch.
