### ISSUE TITLE
np.round questions

### ISSUE THREAD

**Issue by xoviat** [numpy/numpy#10305]
While digging into test failures when compiling with flang, I found that `np.rint(4.5) = 4`, which is surprising considering that math class always taught that you are supposed to round up. The root cause of this behavior is the `ieee_rint(4.5) = 4` on gfortran and `ieee_rint(4.5) = 5` on flang, because we simply use MSVC's round function.

I can resolve these issues, but does anyone know why the gfortran result is correct?

**Comment by charris** [comment]
Round to even is the preferred method as the error distribution is more symmetric. Rounding up biases the errors.
