### ISSUE TITLE
Adding keywords to ufunc calls seems slow

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#10301]
Mostly just as a note that says more about python not being so efficient as used from C than about our implementation, but adding a keyword argument to a ufunc takes at least double the time as a simple python function would suggest is needed (note that `where=True` and `subok=True` should just be no-ops; found this as I was hoping to speed up routines by passing `subok=False`...).
```
In [53]: a = np.arange(2.)

In [54]: %timeit np.add(a, a)
The slowest run took 55.55 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 509 ns per loop

In [55]: %timeit np.add(a, a, subok=True)
The slowest run took 22.16 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 786 ns per loop

In [56]: %timeit np.add(a, a, subok=False)
The slowest run took 22.60 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 758 ns per loop

In [57]: %timeit np.add(a, a, where=True)
The slowest run took 39.37 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 818 ns per loop
```

Simple python class on the same machine
```
In [90]: class B:
    ...:     def __call__(self, subok=True):
    ...:         pass
    ...:     
    ...:     

In [91]: b = B()

In [92]: %timeit b()
The slowest run took 34.52 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 126 ns per loop

In [93]: %timeit b(subok=True)
The slowest run took 25.05 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 216 ns per loop
```

**Comment by bashtage** [comment]
If you use positional arguments you are back to the original case:

```
%timeit b()
161 ns ± 2.91 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

%timeit b(subok=True)
240 ns ± 4.86 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%timeit b(True)
158 ns ± 0.581 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

**Comment by eric-wieser** [comment]
Is this going through our optimized kwarg parser that does a lookup on the first letter of the kwarg?

**Comment by mhvk** [comment]
Yes, the plain `ufunc` do use the special loop. Below, I also check `np.add.reduce`, which goes through `PyArg...`. Turns out that is even slower. Note also that the various no-ops all take different amounts of time (consistently so), with what seems a clear dependence on where in the reduce keyword argument list they are. Since python functions are so much faster, it may be that we can "pre-compile" some things (like constructing hashes out of key names to make dict look up faster?) to make these calls faster. 
```
%timeit np.add(a, a)
# 1000000 loops, best of 3: 433 ns per loop
%timeit np.add(a, a, subok=True)
# 1000000 loops, best of 3: 711 ns per loop
%timeit np.add.reduce(a)
# 1000000 loops, best of 3: 1.05 µs per loop
%timeit np.add.reduce(array=a)
1000000 loops, best of 3: 1.31 µs per loop
%timeit np.add.reduce(a, out=None)
# 100000 loops, best of 3: 1.67 µs per loop
%timeit np.add.reduce(a, axis=None)
# 100000 loops, best of 3: 1.5 µs per loop
 %timeit np.add.reduce(a, keepdims=False)
# 100000 loops, best of 3: 1.75 µs per loop
```

**Comment by mhvk** [comment]
The slowness of `PyArg_TupleAndKeywords` seems well-known, though not with obvious current solutions: see https://mail.python.org/pipermail/python-ideas/2014-May/028010.html

**Comment by mhvk** [comment]
Partially as note-to-self: we avoid the slowness of C-based keyword parsing in part by passing through `_methods.py`, which passes only positional arguments to the reductions.

**Comment by mhvk** [comment]
See #11333 for a partial fix.

**Comment by seberg** [comment]
Closing, keyword arguments will barely add any additional overhead in NumPy 1.21/main.

**Comment by mhvk** [comment]
> Closing, keyword arguments will barely add any additional overhead in NumPy 1.21/main.

:fireworks:
