### ISSUE TITLE
The size of 0-d arrays is 1.

### ISSUE THREAD

**Issue by local-minimum** [numpy/numpy#10329]
I understand why this would happens, but nevertheless, it is contrary to any reasonable expectation:

```
In [9]: np.array(None).ndim
Out[9]: 0

In [10]: np.array(None).size
Out[10]: 1
```

If an array lacks dimensions, it can't have any data and therefore its size must be `0`.

**Comment by pv** [comment]
0-dimensional arrays are scalars. Indeed, `\Prod_{k=1}^n s_k == 1` for `n = 0`.

**Comment by eric-wieser** [comment]
Or phrased another way, `x.size == np.prod(x.shape)`, and in your case, `x.shape == ()`.

Perhaps you're getting confused by the use of `None`? You can put anything you like in an 0d array:

```
x = np.array(42)
assert x[()] == 42
```
