### ISSUE TITLE
do NumPy has a c-api to migrate to another language?

### ISSUE THREAD

**Issue by guenchi** [numpy/numpy#10335]
do NumPy has a c-api to migrate to another language?

**Comment by seberg** [comment]
Not sure what you mean, numpy needs a running Python instance to work. In the end you can use numpy's and pythons C-API to do anything of course, but you need the python. Python is used everywhere within numpy, there is no python agnostic layer or such.

Anyway, will close this for now, feel free to discuss (though it might fit better on the mailing list).
