### ISSUE TITLE
Plus signs are missing for complex arrays in legacy printing mode

### ISSUE THREAD

**Issue by krischer** [numpy/numpy#10356]
Apologies if this is a duplicate as it seems such an obvious bug but I could not find another issue about it. Legacy printing mode omits the plus signs for complex arrays.

```python
>>> import numpy as np
>>> np.ones(5, dtype=np.complex128)
array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])
>>> np.set_printoptions(legacy="1.13")
>>> np.ones(5, dtype=np.complex128)
array([ 1. 0.j,  1. 0.j,  1. 0.j,  1. 0.j,  1. 0.j])
```

The output on numpy 1.13.3 is

```python
>>> np.ones(5, dtype=np.complex128)
array([ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j])
```

**Comment by ahaldane** [comment]
Whoops! Confirmed. Should be easy to fix.

**Comment by jakirkham** [comment]
Just ran into this, glad to see you are already on top of it. Any suggested workarounds in the interim?

**Comment by krischer** [comment]
> Just ran into this, glad to see you are already on top of it. Any suggested workarounds in the interim?

I converted most of these occurrences in our codes to unit tests and in a few cases we just print the real and imaginary parts separately for now...
