### ISSUE TITLE
Printing of complex arrays is different on macOS and Linux

### ISSUE THREAD

**Issue by andyfaff** [numpy/numpy#10355]
Printing of complex arrays is different on macOS and Linux.
On macOS (3.6.3):

```
>>> import numpy as np
>>> from scipy import linalg
>>> A = np.mat('[1 3 2; 1 4 5; 2 3 6]')
>>> T, Z = linalg.schur(A)
>>> T2, Z2 = linalg.rsf2csf(T, Z)
>>> T2
array([[ 9.90012467+0.        j, -0.32436598+1.55463542j,
        -0.88619748+0.56902762j],
       [ 0.        +0.        j,  0.54993766+0.89925841j,
         1.06493862+0.        j],
       [ 0.        +0.        j,  0.        +0.        j,
         0.54993766-0.89925841j]])
>>> np.version.version
'1.14.0'
```

on the travis Linux image (Python 3.5.4):
```
array([[ 9.90012467+0.00000000e+00j, -0.32436598+1.55463542e+00j,
        -0.88619748+5.69027615e-01j],
       [ 0.        +0.00000000e+00j,  0.54993766+8.99258408e-01j,
         1.06493862+3.05311332e-16j],
       [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.54993766-8.99258408e-01j]])
```

**Comment by ahaldane** [comment]
Hmm. I'm not yet sure why there's a difference, but in both cases there should not be any spaces inside the number. I think we need to override the `floatmode` option for complex values.

**Comment by pv** [comment]
So the spaces before `j` is a bug? I was indeed going to complain about 
it as I think whatever numbers get printed should still be valid Python 
literals...

**Comment by ahaldane** [comment]
Yes, it's definitely a bug. I was careful to make complex-scalars not have any spaces, but somehow missed making complex-arrays be the same.

I think I alreadt have the fix, I just needed to treat the `floatmode` option more carefully for complex arrays.

**Comment by pv** [comment]
It seems the numpy printing still has some bugs that will be corrected. 
We probably should hold this PR off until those have been fixed...
