### ISSUE TITLE
1D ``np.linalg.norm`` not preserving input dtype?

### ISSUE THREAD

**Issue by kmaehashi** [numpy/numpy#10364]
I saw the [v1.14.0 release note](https://github.com/numpy/numpy/blob/master/doc/release/1.14.0-notes.rst#1d-nplinalgnorm-preserves-float-input-types-even-for-arbitrary-orders) saying:

> 1D np.linalg.norm preserves float input types, even for arbitrary orders

However, when I try the code on the release note, it does not behave as it says.

```py
>>> import numpy as np
>>> np.__version__
'1.14.0'
>>> f32 = np.float32([1, 2])
>>> np.linalg.norm(f32, 2.0).dtype
dtype('float32')
>>> np.linalg.norm(f32, 2.0001).dtype
dtype('float64')  # it should be float32 on numpy 1.14?
```

**Comment by eric-wieser** [comment]
My fault in #9522. I think it does preserve `longdouble` types now, but I wasn't able to test that.

Maybe simplest to revert that part of the release note?

**Comment by eric-wieser** [comment]
Culprit is the `1.0` on this line upcasting: https://github.com/numpy/numpy/commit/351fe979580ab842cc5c04e1b616d3a64936a695#diff-6858bbac5c5c59bdddf245c69d6a547cR2206

Replacing it with `1` should solve the problem.
