### ISSUE TITLE
byteswap() doesn't change byteorder attribute

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#10372]
```python
import numpy

a = numpy.array([3.14], dtype=numpy.dtype('>f4'))
print(map(hex, a))  # ['0x3']
print(a.dtype.byteorder)  # >

a.byteswap(inplace=True)
print(map(hex, a))  # ['-0x1ea']
print(a.dtype.byteorder)  # >
```

**Comment by matthew-brett** [comment]
I'm afraid that's by design.  Byteswap just swaps the bytes, you have to do a separate `a.dtype.byteorder = '<'` to tell the array that the data are swapped.

**Comment by nschloe** [comment]
Alright, thanks for explanation.

**Comment by eric-wieser** [comment]
Use `.newbyteorder()` to tell numpy the data is swapped. `.newbyteorder().byteswap()` preserves the value, but swaps the underlying representation
