### ISSUE TITLE
Difference in matrix multiplication result between Xeon E5-1650 v2 and v3

### ISSUE THREAD

**Issue by Strilanc** [numpy/numpy#10377]
If you run the following python code:

```
import numpy as np
s = np.sqrt(0.5)
np.dot([[s, s], [0, 0]], [[s, 0], [-s, 0]])
```

The result on a Xeon E5-1650 v2 is the zero matrix:

```
array([[ 0.,  0.],
       [ 0.,  0.]])
```

But on a Xeon E5-1650 v3 the result has some error:

```
array([[  4.26642159e-17,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00]])
```

Even more strangely, the error goes away when removing the second row of the first matrix (the zero row) or the second column of the second matrix (the zero column).

I realize that floating point calculations intrinsically involve approximations, so small errors like this are not particularly surprising. What is surprising is that the presence of error depends on the processor version. The dependence on the presence of additional irrelevant zeros is less surprising, but for such a small matrix there is unlikely to be any fancy algorithms mixing those zeros into the other values so maybe it's a bit surprising after all.

**Comment by njsmith** [comment]
It's very common for linear algebra routines like `dot` to perform their computations in different ways depending on the exact version of the processor, the cache size, the compiler settings, and other factors like that. The results should be generally equivalent, but you should expect the exact amount and location of small floating point rounding errors to vary like this, yeah.
