### ISSUE TITLE
bug in percentile Linear

### ISSUE THREAD

**Issue by jhelie** [numpy/numpy#10373]
```
>>>  np.__version__
'1.13.3'
```
A rounding error occurs for certain value/percentile combinations.  
```
>>> a = np.ones(279) * 0.56758051638767337
>>> np.unique(a)
array([ 0.56758052])
```
The array containing only identical values all percentiles should be equal to that value but that is not the case for the 45th percentile:
```
>>> for p in range(0,100,5):
        if np.percentile(a, p) != a[0]:
            print(p)
45
```
And indeed:
```
>>> np.percentile(a, 45)
0.56758051638767348
>>> np.percentile(a, 45) - a[0]
1.1102230246251565e-16
```
The problematic percentile(s) depend on the length and the value of the array:
```
>>> b = np.ones(279) * 60287681548494698
>>> np.unique(b)
array([ 60287682])
>>> for p in range(0,100,5):
        if np.percentile(b, p) != b[0]:
            print(p)
95
>>> np.percentile(b, 95)
0.60287681548494709
```

**Comment by seberg** [comment]
On the one end, a single ULP error has to be expected, on the other hand, it would be nice if `lower <= percenetile <= higher` would always hold. Is there a way to rearrange the calculation so that this is ensured without much trouble?

**Comment by seberg** [comment]
I suppose something like `(a + (b-a) * (weight))` instead of `(1-weight)*a + weight * b` could work and not be slower? Since weight is smaller then one, and a smaller b it could guarantee this while giving a similar overall error?

**Comment by seberg** [comment]
Hehe, Iguess it might work if for weight being 1 (or close enough), `a * (b-a) <=b` fo any `b>=a` is true, and I am not wuite sure it is right now :).

**Comment by seberg** [comment]
Ah, of course, if a is large and negative and b small (negative) you will get catastrophic annihilation. Pretty certainly not that simple, need some trick like kahan probably, not sure if its worth here....

**Comment by njsmith** [comment]
Here's a bug that seems to come down to `percentile` returning values outside the array bounds: https://github.com/pydata/patsy/pull/116

**Comment by seberg** [comment]
I am 98% sure that the (rather long ago) fix to use a `lerp` in `percentile` that ensures strict monotonicity fixes this issue, and none of the examples above still error, so closing.
