### ISSUE TITLE
loadtxt returns IOError with empty errno for non-existing files

### ISSUE THREAD

**Issue by christian-rauch** [numpy/numpy#10376]
Before version 1.14, loading a non-existing file via `np.loadtxt("some_file.csv")`
would have raised: `[Errno 2] No such file or directory: 'some_file.csv'`, i.e. a `IOError` with `errno=2` (exception of `open`).

Since 1.14, a `IOError` with unset `errno` is raised via: `raise IOError("%s not found." % path)`: `IOError: some_file.csv not found.`.

This is not documented in the release notes.
Is there a specific reason why this behaviour is changed?

**Comment by seberg** [comment]
Getting a `FileNotFoundError` now, which seems OK to me.  But please open a new issue if I am misunderstanding things.
