### ISSUE TITLE
BUG: show_config is broken on Windows and 1.14

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#10386]
With the release of 1.14 (using Anaconda with MKL) I now get NOT AVAILABLE for all entries:
```
>>> import numpy
>>> numpy.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
  NOT AVAILABLE
blas_src_info:
  NOT AVAILABLE
blas_opt_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
  NOT AVAILABLE
lapack_src_info:
  NOT AVAILABLE
lapack_opt_info:
  NOT AVAILABLE
```
Using dependency walker I can confirm that there is a link from `numpy\core\MULTIARRAY.CP36-WIN_AMD64.PYD` to `MKL_RT.DLL`.

**Comment by xoviat** [comment]
Anaconda doesn't publicly build their windows NumPy, so we'd need more information to be able to act on this. 

cc @mingwandroid

**Comment by larsoner** [comment]
For what it's worth with 1.13.3 on Windows I checked and the entries make sense:
```
blas_mkl_info:
    libraries = ['mkl_rt']
...
```

**Comment by mingwandroid** [comment]
> Anaconda doesn't publicly build their windows NumPy, so we'd need more information to be able to act on this.

How do you mean? We do not build on Appveyor and other public CI systems for security reasons but our recipes are all available and completely reproducible.

https://github.com/AnacondaRecipes/numpy-feedstock/tree/master/recipe

@jjhelmus any ideas about this one?

**Comment by jjhelmus** [comment]
I'm seeing this as well on Windows.  For some reason the `__config__.py` file is not getting written correctly for our builds. I'll investigate further.

**Comment by msarahan** [comment]
I think we've fixed it - is this the expected output?

```
>>> import numpy
>>> numpy.show_config()
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/MC2/envs/np114test\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/MC2/envs/np114test\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/MC2/envs/np114test\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/MC2/envs/np114test\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/MC2/envs/np114test\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/MC2/envs/np114test\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/MC2/envs/np114test\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/MC2/envs/np114test\\Library\\include']
```

The root cause was a faulty mkl-devel package, which is where we have our site.cfg file that numpy uses.  This file was being build with a shell script on both unix and windows, and the uname-based detection of being on windows was not matching names correctly (windows has way too many possible outcomes for uname).

Regardless, I recommend closing this issue here, because it was definitely an Anaconda/packaging bug, not a numpy bug.

**Comment by larsoner** [comment]
Yes that's more like it. Thanks @msarahan

**Comment by msarahan** [comment]
Thanks @larsoner - we'll have new packages up in a little while.  There was an annoying test failure due to CI systems - maybe an hour or so for me to patch and rebuild.

**Comment by msarahan** [comment]
@larsoner done.  Please ping me if you see any further issues along these lines.
