### ISSUE TITLE
numpy/sympy: scalar multiplication of arrays depends on order of factors

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#10384]
When forming the product `alpha * X` with `alpha` being a sympy scalar and `X` being an array of sympy dtype _with only one element_, the resulting object will be a `float`, not a numpy array with sympy dtype. It's all working as expected 

 * if forming `X * alpha` or
 * if `X` has more than one element or
 * if the data type is `int` or `float`.

MWE:
```python
import numpy
import sympy

a = numpy.array([sympy.S(1)])
b = sympy.S(1)
print(a*b)  # [1]
print(b*a)  # 1.00000000000000

a = numpy.array([sympy.S(1), sympy.S(1)])
print(a*b)  # [1, 1]
print(b*a)  # [1, 1]

a = numpy.array([1])
b = 1
print(a*b)  # [1]
print(b*a)  # [1]
```
Perhaps this can be reproduced with other data types as well.

**Comment by pv** [comment]
Sympy scalars need to define `__array_ufunc__ = None` or `__array_priority__ > np.ndarray.__array_priority__` if they want to avoid numpy's greedy array casts in binary operations.
