### ISSUE TITLE
Invalid result from Reduction Iteration in given example

### ISSUE THREAD

**Issue by oksidans** [numpy/numpy#10410]
The example for [Reduction Iteration](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.nditer.html#reduction-iteration) is producing the wrong result.

```python
a = np.arange(24).reshape(2,3,4)
it = np.nditer([a, None], flags=['reduce_ok', 'external_loop'], op_flags=[['readonly'], ['readwrite', 'allocate']], op_axes=[None, [0,1,-1]])

it.operands[1][...] = 0
for x, y in it:
    y[...] += x
```
produces result:
```
>>> it.operands[1]
array([[ 3,  7, 11],
       [15, 19, 23]])
```
which is not accurate
```
>>> np.sum(a, axis=2)
array([[ 6, 22, 38],
       [54, 70, 86]])
```
I am using latest anaconda, Windows 7, 64bit, python 2.7, numpy 1.13.1, jupyter 1.0.0

**Comment by eric-wieser** [comment]
Can you link to where the example comes from?

**Comment by oksidans** [comment]
It is in the documentation, under the Iterating Over Arrays section - Reduction Iteration example for summation of all elements in an array
Here is the link  [https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.nditer.html](url)

**Comment by eric-wieser** [comment]
Looks like it fails for the same reason that the following does:
```python
x = np.lib.stride_tricks.as_strided(0, shape=(4,), strides=(0,))
x += np.arange(4)
x
# array([3, 3, 3, 3])
```

**Comment by eric-wieser** [comment]
Strangely, using `np.add(y, x, out=y)` works correctly

**Comment by eric-wieser** [comment]
Looks like a regression in 1.12 or 1.13 - 1.11 works correctly.

I suspect this is due to the overlap-detection added in 1.13

**Comment by eric-wieser** [comment]
Although it [seems it was deliberate](https://github.com/numpy/numpy/pull/8043#issuecomment-274281137)

**Comment by pv** [comment]
`np.add(x, y, out=z)` should be  the same as `np.add(x.copy(), y.copy(), 
out=z)`, otherwise it's a bug.

**Comment by pv** [comment]
I don't think there are exceptions from the above rule, at least I don't 
recall adding special cases for 0-stride arrays.

**Comment by eric-wieser** [comment]
Looking at [these lines](https://github.com/numpy/numpy/pull/8043/files#diff-84bb1212a068e5b2baddc15d9ad0200eL2323) from @pv's PR, it seems that this change was deliberate, and the `out` argument behavior is a lingering bug (and the documentation is out of date)

**Comment by seberg** [comment]
Yeah, I somewhat guess it is a change in behaviour that was in some sense anticipated. Is this actually creating problems for you? The nditer API, is a bit too close to the C-API for its own good/nice usage sometimes....
