### ISSUE TITLE
Float128 repr is wrong on ppc64

### ISSUE THREAD

**Issue by ahaldane** [numpy/numpy#10429]
Reminder/issue to keep track of the fact that we need to fix the float128 dragon4 code for IBM's "double-double" float format on ppc.

I'm working on it, should be done soon.

**Comment by jjhelmus** [comment]
I'm seeing a number of unit test errors and failures in NumPy 1.14.0 as well as the current master when building from source on a ppc64le system running CentOS 7.  I bisected these back to PR #9941. I'm assuming this issue is for tracking these.

Would a log of the failures be helpful?

Let me know if there is anything I can do to help get these resolved.

**Comment by ahaldane** [comment]
Let me finish up with my changes. I'm working on the ppc64(be) system, so since you have a le system it would be nice if you can run tests before we release too.

**Comment by ahaldane** [comment]
Sidenote that isn't exaclty this issue, but related:

There appears to be a glibc bug in `strtodl` on ppc64 which means that it is not possible to read in small float128 values from strings, eg 5e-296 which is not even a subnormal double. This means it is not possible to consistently round-trip float128 values through load/savetxt.

Here is an example running numpy 1.13:
```python
>>> np.array([np.float128('5.0e-292')/100])   # we can create small values with algebra
array([ 5e-294], dtype=float128)
>>> np.float128('5e-294')  # but can't create them from a string
ValueError: invalid literal for long double: 5e-294
```

Here's a little C program which does the same:
<details>
<summary>C program</summary>

```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

int main(){
    double d;
    long double x;
    char str[1024], *end;

    d = strtod("5.0e-294", &end); /* doubles are no problem */
    if(errno != 0) {
        printf("error: %s\n", strerror(errno));
    }
    printf("double:      %.40g\n", d);

    x = strtold("5.0e-292", &end);
    if(errno != 0) {
        printf("error: %s\n", strerror(errno));
    }
    printf("long double: %.40Lg\n", x);
    x = x/100;
    printf("/100:        %.40Lg\n", x);

    snprintf(str, 1024, "%.40Lg", x);
    x = 0;  /* reset to 0 to see if it gets overwritten */
    errno = 0;
    x = strtold(str, &end); /* long doubles fail */
    if(errno != 0) {
        printf("error: %s\n", strerror(errno));
    }
    printf("save/load:   %.40Lg\n", x);
}
```

</details>

output on ppc64 (be):
```
double:      5.0000000000000002566363886578393283723e-294
long double: 4.999999999999999999999999999999967711586e-292
/100:        5.000000000000000000000000000002042787298e-294
error: Numerical result out of range
save/load:   5.000000000000000000000000000002042787298e-294
```
So it seems to succesfully read in the final value, but mistakenly sets errno.

**Comment by charris** [comment]
Looks like LLVM has a compatible MIT license, supports power pc big and little endian, and has its own library. There might be some code there we could steal.

**Comment by ahaldane** [comment]
Good idea, I didn't know that.

I just spent a while trying to get llvm's libc installed on ppc, to see if its `strtold` works properly. But despite some effort I couldn't get things to compile. Googling my compilation errors shows others are struggling to compile on ppc too with similar errors, eg. https://trac.macports.org/ticket/53184?cversion=0&cnum_hist=6, https://bugs.llvm.org/show_bug.cgi?id=33516. I'm giving up on it for now.

**Comment by charris** [comment]
Ah, too bad. LLNL also had some code for double double and quad double, but the license looked ridiculous, as in, you needed to fill out a form.

**Comment by ahaldane** [comment]
@jjhelmus  If you get a chance, could you confirm the following for me on your le system, with numpy 1.13 or before?

```python
>>> from numpy.core.multiarray import format_longfloat
>>> a = np.float128('2')/np.float128('3')
>>> b = np.float128(format_longfloat(a, 40))
>>> format_longfloat(a, precision=40)
'0.6666666666666666666666666666666584493656'
>>> format_longfloat(b, precision=40)
'0.6666666666666666666666666666666584493656'
>>> a == b
False
```

I think this is some slight weirdness in glibc, or perhaps of the arch itself, having to do with treatment of the 107th bit.

Also what is your glibc version, reported by `ldd --version`?

**Comment by jjhelmus** [comment]
@ahaldane I'm seeing the same results on a le system with numpy 1.13.3:

```
>>> import numpy as np
>>> from numpy.core.multiarray import format_longfloat
>>> a = np.float128('2')/np.float128('3')
>>> b = np.float128(format_longfloat(a, 40))
>>> format_longfloat(a, precision=40)
'0.6666666666666666666666666666666584493656'
>>> format_longfloat(b, precision=40)
'0.6666666666666666666666666666666584493656'
>>> a == b
False
>>> np.__version__
'1.13.3'
```

glibc reports itself as `ldd (GNU libc) 2.17`

**Comment by ahaldane** [comment]
Thanks. I think I'll submit a glibc bug, and I'll just follow their behavior for now in numpy.

**Comment by charris** [comment]
@ahaldane Looks like this won't ready anytime soon, so pushing off to 1.15 also.

**Comment by ahaldane** [comment]
Actually, I think this one is fixed by #10444, which as far as I am concerned is "good to go".

The last few comments here are about whether the glibc behavior is right or not. In #10444 I just copy the glibc behavior, which is what we got in 1.13 anyway.

**Comment by charris** [comment]
OK, I marked #10444 for backport.

**Comment by charris** [comment]
@ahaldane This is fixed now, right?

**Comment by ahaldane** [comment]
This one is fixed. Closing.
