### ISSUE TITLE
ma.average ignores masked weights

### ISSUE THREAD

**Issue by cmchugh11** [numpy/numpy#10438]
The np.ma.average function ignores masked weights. Averaging a masked array with unmasked and masked weights incorrectly gives the same result. I am using numpy version 1.13.3, python 2.7.12. In previous versions of numpy (e.g. 1.11.0b3) ma.average did not exhibit this behavior.   

```
import numpy as np
import numpy.ma as ma
x = np.ma.array(np.arange(9).reshape(3, 3), mask=[[1, 0, 0], [1, 0, 0], [0, 0, 0]])
w=ma.masked_array([31,28,31],mask=False)
w2 = ma.masked_array([31,28,31],mask=[1,0,0])
```
```

np.ma.average(x, axis=0, weights=w, returned=True)
(masked_array(data = [6.0 4.0 5.0],
             mask = [False False False],
       fill_value = 1e+20)
, array([ 31.,  90.,  90.]))

np.ma.average(x, axis=0, weights=w2, returned=True)
(masked_array(data = [6.0 4.0 5.0],
             mask = [False False False],
       fill_value = 1e+20)
, array([ 31.,  90.,  90.]))
```

**Comment by rgommers** [comment]
This is still the case, and indeed looks like a bug. If `weights` also has a mask, and has masked elements that are unmasked in `x`, then that should either raise an exception or the output element should be calculated using the union of the two masks. I think the latter is probably better.

**Comment by lauradmartens** [comment]
@mecopur and I will be working on this bug
