### ISSUE TITLE
random.choice adjust name of the "replace" parameter

### ISSUE THREAD

**Issue by shitian-ni** [numpy/numpy#10437]
I think the name "replace" is confusing. 
Maybe it is better to name the parameter as "repeat"?

**Comment by eric-wieser** [comment]
`replace` is the usual terminology. [From wikipedia](https://en.wikipedia.org/wiki/Simple_random_sample):

> such sampling is typically done "without replacement", i.e., one deliberately avoids choosing any member of the population more than once.

I'm sure there exists a better reference, but I've always heard it referred to as sampling with replacement.
