### ISSUE TITLE
Bug: Comparison operator for subarrays is wrong/unimplemented

### ISSUE THREAD

**Issue by ahaldane** [numpy/numpy#10442]
Currently, sorting and comparison of subarrays is wrong in many cases.

This was discovered because trying to sort arrays with subarrays leads to different results on little-endian systems vs big-endian:
```python2
>>> z = np.array([([3,3],), ([-1,0],)], dtype=[('v', '>i4', (2,))])
>>> z[0] < z[1]
```
On little endian, the last line returns `True`. On big-endian, it returns `False`.

Here's what's happening:  In `VOID_compare`, [this line](https://github.com/numpy/numpy/blob/9749eec481b97f63520915b044dc5fdd14c71ebd/numpy/core/src/multiarray/arraytypes.c.src#L2977), see that non-structured voids are compared by doing `cmp(val1.tobytes(), val2.tobytes()`. In other words, it looks like we treat subarrays as if they were plain 'np.void' types and use a simple string compare. That's why endianness mattered, but it also means that a lot of other cases are wrong since we are comparing the byte values rather than the numerical values.

I think we need to add an extra block there to take care of subarrays.

**Comment by ahaldane** [comment]
The failing test can be seen at https://github.com/numpy/numpy/pull/9302#discussion_r162775288.

But actually, I need to remind myself: Why are we testing sorting of structured arrays there? Is that deprecated or supported? The comparison in my example above warns with `DeprecationWarning: unorderable dtypes; returning scalar but in the future this will be an error`.

**Comment by ahaldane** [comment]
See also #10235. I think `VOID_compare` needs a good doing-over.

**Comment by seberg** [comment]
Stumbled on this. On NumPy 1.19 and 1.20+ this now errors. Although, with the slightly weird error:
```
TypeError: '<' not supported between instances of 'numpy.ndarray' and 'numpy.ndarray'
```
indicating that after some maze of calls it ended up returning `NotImplemented` (for both directions).  Which is probably an improvement, but still a bug.
