### ISSUE TITLE
BUG: segfault on malformed dtype string

### ISSUE THREAD

**Issue by DrRibosome** [numpy/numpy#10440]
I was trying different combinations for numpy dtype parsing from strings and hit this. Instead of returning a parse error, or something similar, it looks like malformed dtype strings simply cause a segfault.

For example:
```python
>>> import numpy as np
>>> np.dtype('f8,i8,[f8,i8]')
Segmentation fault (core dumped)
```

**Comment by charris** [comment]
Confirmed. This sounds like the sort of thing fuzz testing would be good for.
