### ISSUE TITLE
Why does importing numpy add 1 GB of virtual memory on Linux?

### ISSUE THREAD

**Issue by skullgoblet1089** [numpy/numpy#10455]
... and can I change this behavior?

I have to run python in a resource constrained environment with only a few GB of virtual memory. 

Red Hat Enterprise Linux Server release 6.9 (Santiago)
Python 3.6.2
numpy>=1.13.3

import os
os.system('cat "/proc/{}/status"'.format(os.getpid()))

... VmRSS: 7300 kB 
... VmData: 4348 kB
... VmSize: 129160 kB

import numpy
os.system('cat "/proc/{}/status"'.format(os.getpid()))

... VmRSS: 21020 kB
... VmData: 1003220 kB
... VmSize: 1247088 kB  

Any advice on how I can bring this initial memory allocation to VmData down?

e.g.

- Change the default amount allocated to numpy on import?
- Disable the feature and force python / numpy to allocate more dynamically?

This hits me especially hard because I have to fork children from my main process as part of application design, all of which receive a copy-on-write allocation of this same amount of virtual memory on fork. The result is that after forking only 1 - 2 children, the process group hits the ceiling and shuts everything down. Having some control over the initial allocation would be very useful.

**Comment by eric-wieser** [comment]
How does `python -OO` behave for you?

**Comment by charris** [comment]
Hmm, I don't see that here with Python 2.7 or 3.6.2.
```
VmSize:	  237200 kB
...
VmRSS:	   26812 kB
...
VmData:	   14252 kB
```
The `VmSize` about doubles after import.

**Comment by charris** [comment]
I wonder if it could be debugging data, or possibly something special to Python 3.6.2. How did you install NumPy? I'm using current master, but I can't think of anything special we have done about memory.

**Comment by charris** [comment]
I don't see it with NumPy 1.13.3 either.

**Comment by skullgoblet1089** [comment]
-OO:

- Using -OO didn't seem to impact much (see below)
- I notice that the number of threads is increasing from 1 - 24 after NumPy import also

Other:

- I've tried this with Python 2.6.6 (NumPy==1.10.0) and 3.4.3 (NumPy==1.14.0) on my machine and see the same behavior
- I've installed NumPy from pip in each test using a virtualenv to isolate
- Out of curiosity what os are you using to test?
- This may be specific to my installation(s) of Python
- I am using an older host that might have an outdated compiler
- I can look into that more tomorrow morning and update

-OO (before import numpy):

VmPeak:   125360 kB
VmSize:   125360 kB
VmLck:         0 kB
VmHWM:      5336 kB
VmRSS:      5336 kB
VmData:     2612 kB
VmStk:       108 kB
VmExe:      2028 kB
VmLib:      2736 kB
VmPTE:       112 kB
VmSwap:        0 kB
Threads:        1

-OO (after import numpy):

VmPeak:  1246448 kB
VmSize:  1246448 kB
VmLck:         0 kB
VmHWM:     18032 kB
VmRSS:     18032 kB
VmData:  1000152 kB
VmStk:       108 kB
VmExe:      2028 kB
VmLib:     48988 kB
VmPTE:       452 kB
VmSwap:        0 kB
Threads:        24

**Comment by charris** [comment]
Hmm, I think the numpy wheels on pip have OpenBLAS compiled in. Are you installing from source? I'm running Fedora 27 and my NumPy is linked against the ATLAS shared library.

**Comment by njsmith** [comment]
I don't know for sure, but yeah, the wheels include OpenBLAS and this very much sounds like the kind of shenanigans that OpenBLAS might be getting up to.

BTW, I am confused by the idea that you have limited "virtual memory". Virtual memory is... virtual; it's locations that you can talk about by number, but that don't necessarily actually use any memory. Does your environment have a shortage of numbers?

Anyway, I get that you may not have a choice here – you might try building your own numpy with a different version of BLAS, or examining the OpenBLAS build configuration guide to see if there are any knobs that might be tweakable. (They have a lot of knobs, and their defaults are often tuned for supercomputer setups that are not so appropriate for general use.)

**Comment by njsmith** [comment]
also fyi, `open("/proc/self/status")` is a shorter way to write `open("/proc/{}/status".format(os.getpid())`.

**Comment by ahaldane** [comment]
>  I notice that the number of threads is increasing from 1 - 24 after NumPy import also

That's odd, I'm not aware of numpy using threads. Are you running in a plain python shell or in ipython? (recent ipython uses lots of threads)

**Comment by njsmith** [comment]
@ahaldane OpenBLAS definitely uses threads though.

**Comment by xoviat** [comment]
The OpenBLAS distributed with the manylinux wheels is a [few years old](https://travis-ci.org/MacPython/openblas-libs/builds/140986655) and perhaps could be updated.

**Comment by charris** [comment]
> OpenBLAS definitely uses threads though.

Might even maintain a thread pool.

**Comment by skullgoblet1089** [comment]
Thanks for your help on this thread, everyone.

- After poking around I found that the easiest way for me to control the number of threads was by setting the environment variable OMP_NUM_THREADS.  
- Setting this variable to a smaller value (4), dramatically reduced the amount of VmData consumed by python with no performance impact vs alternative for the following simple benchmark credit to [this blog](https://hunseblog.wordpress.com/2014/09/15/installing-numpy-and-openblas/).

#### Test

```python
def _proc_status():
    print(open('/proc/self/status').read())

_proc_status()

import numpy as np
import numpy.random as npr
import time

print("import numpy")
_proc_status()

# --- Test 1
N = 1
n = 1000
 
A = npr.randn(n,n)
B = npr.randn(n,n)
 
t = time.time()
for i in range(N):
    C = np.dot(A, B)
td = time.time() - t
print("dotted two (%d,%d) matrices in %0.1f ms" % (n, n, 1e3*td/N))

_proc_status()

# --- Test 2
N = 100
n = 4000
 
A = npr.randn(n)
B = npr.randn(n)
 
t = time.time()
for i in range(N):
    C = np.dot(A, B)
td = time.time() - t
print("dotted two (%d) vectors in %0.2f us" % (n, 1e6*td/N))

_proc_status()

# --- Test 3
m,n = (2000,1000)
 
A = npr.randn(m,n)
 
t = time.time()
[U,s,V] = np.linalg.svd(A, full_matrices=False)
td = time.time() - t
print("SVD of (%d,%d) matrix in %0.3f s" % (m, n, td))

_proc_status()

# --- Test 4
n = 1500
A = npr.randn(n,n)
 
t = time.time()
w, v = np.linalg.eig(A)
td = time.time() - t
print("Eigendecomp of (%d,%d) matrix in %0.3f s" % (n, n, td))

_proc_status()

```

#### Results

``` bash
...
VmPeak:	  119096 kB
VmSize:	  118776 kB
VmLck:	       0 kB
VmHWM:	    5028 kB
VmRSS:	    5028 kB
VmData:	    2588 kB
VmStk:	     112 kB
VmExe:	    2028 kB
VmLib:	    2368 kB
VmPTE:	      96 kB
VmSwap:	       0 kB
Threads:	1
...

import numpy

...
VmPeak:	  382092 kB
VmSize:	  382092 kB
VmLck:	       0 kB
VmHWM:	   19964 kB
VmRSS:	   19964 kB
VmData:	  142356 kB
VmStk:	     112 kB
VmExe:	    2028 kB
VmLib:	   48620 kB
VmPTE:	     356 kB
VmSwap:	       0 kB
Threads:	4
...

dotted two (1000,1000) matrices in 19.9 ms
...
VmPeak:	  438772 kB
VmSize:	  438772 kB
VmLck:	       0 kB
VmHWM:	   51120 kB
VmRSS:	   51120 kB
VmData:	  198572 kB
VmStk:	     576 kB
VmExe:	    2028 kB
VmLib:	   48620 kB
VmPTE:	     424 kB
VmSwap:	       0 kB
Threads:	4
...

dotted two (4000) vectors in 3.53 us
...
VmPeak:	  438772 kB
VmSize:	  415324 kB
VmLck:	       0 kB
VmHWM:	   51124 kB
VmRSS:	   27688 kB
VmData:	  175124 kB
VmStk:	     576 kB
VmExe:	    2028 kB
VmLib:	   48620 kB
VmPTE:	     380 kB
VmSwap:	       0 kB
Threads:	4
...

SVD of (2000,1000) matrix in 0.741 s
... 
VmPeak:	  524932 kB
VmSize:	  454520 kB
VmLck:	       0 kB
VmHWM:	  137900 kB
VmRSS:	   67760 kB
VmData:	  214312 kB
VmStk:	     584 kB
VmExe:	    2028 kB
VmLib:	   48620 kB
VmPTE:	     464 kB
VmSwap:	       0 kB
Threads:	4
...

Eigendecomp of (1500,1500) matrix in 7.279 s
...
VmPeak:	  564208 kB
VmSize:	  493848 kB
VmLck:	       0 kB
VmHWM:	  177732 kB
VmRSS:	  107376 kB
VmData:	  253620 kB
VmStk:	     604 kB
VmExe:	    2028 kB
VmLib:	   48620 kB
VmPTE:	     540 kB
VmSwap:	       0 kB
Threads:	4
...
```
