### ISSUE TITLE
Version constant in numpy.core.umath is bytes

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#10461]
```python
>>> import numpy.core.umath
>>> numpy.core.umath.__version__
b'0.4.0'
```

I am not sure this constant is even maintained, but if it remains, it should be `str`, not `bytes`.

```python
>>> numpy.__version__
'1.15.0.dev0+81e15e8'
```

**Comment by charris** [comment]
I don't think it is maintained, at least I haven't. My thought is that we should remove it.
