### ISSUE TITLE
Inaccurate docstring for asarray

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#10466]
Inaccurate docstring for asarray

The asarray docstring contains the following snippets:

    order : {'C', 'F'}, optional
        Whether to use row-major (C-style) or
        column-major (Fortran-style) memory representation.
        Defaults to 'C'.
    
    Returns
    -------
    out : ndarray
        Array interpretation of `a`.  No copy is performed if the input
        is already an ndarray with matching dtype and order.  If `a` is a
        subclass of ndarray, a base class ndarray is returned.

1) Note that the signature reports that the default for `order` is None, not 'C'.

2) Consider the following (numpy 1.14, Arch Linux):

```
    In [1]: a = np.arange(4).reshape((2, 2))

    In [2]: aT = a.T

    In [3]: np.asarray(a) is a
    Out[3]: True

    In [4]: np.asarray(aT) is aT
    Out[4]: True

    In [5]: np.asarray(aT).flags
    Out[5]: 
      C_CONTIGUOUS : False
      F_CONTIGUOUS : True
      OWNDATA : False
      WRITEABLE : True
      ALIGNED : True
      WRITEBACKIFCOPY : False
      UPDATEIFCOPY : False
```

A strict reading of the docstring would say that `np.asarray(aT)` should make a copy of aT to return a C-contiguous array (well, I guess it does not say explicitly that a copy will be made if the dtype or order do not match, but only the converse...).  My guess is that the docstring is simply being inaccurate here.

**Comment by seberg** [comment]
I think the correct thing is to add: "if a copy is made"

**Comment by seberg** [comment]
This now has the same blurb as `np.array` and says it default to "K", so closing, as I think it should be correct now.
