### ISSUE TITLE
Memory leak when casting np.float32 to int with Numpy 1.14.0

### ISSUE THREAD

**Issue by duag** [numpy/numpy#10474]
Hello,
running the code below with Numpy 1.14.0 will result in fast growing memory usage until the OS kills the process.
```python
import numpy as np
test = np.float32(3.14)
while True:
    x = int(test)
```
Tested with Python 2.7.12 on Win10 x64 and on Linux Mint 17.4 x64.

-----
The bug is not reproducible with Python 3.6.3.

**Comment by Farbdose** [comment]
I can reproduce this with Python 2.7.13 on Ubuntu 17.04.
Python 3.5.3 seems to be fine...

**Comment by seberg** [comment]
If you have a working commit and a non-working commit, the best thing is to do a `git bisect` to quickly narrow down what actually broke it.

**Comment by Farbdose** [comment]
@seberg Unfortunately I don't, atm the only thing I know is that it broke somewhere in the 1037 commits from 1.13.0 to 1.14.0.

**Comment by seberg** [comment]
That is a working and a non-working commit, the 1037 can be quickly spanned by a bisect if you have some time for it. (though I admit, in this case, one can likely just look at the offending function directly)

**Comment by Farbdose** [comment]
Ah sorry my mistake, for a second I thought you were asking If I already know which commit broke it...
Regarding bisect: I just hoped to get around it by getting someone who can actually read c++ to look at the right part of the repo^^
I have some free time in about 3 weeks so if nothing has come up until then I can try to work through http://scipy.github.io/devdocs/building/index.html and sift through it with bisect.

**Comment by jbarthelmes** [comment]
Bisecting with [some automated test](https://gist.github.com/jbarthelmes/f92bfef790ae049c2022abb315bd0de2) I found e0fb73953a4ed36503e72ec5764be5443688ab24 to be the bad commit.

**Comment by seberg** [comment]
Thanks @jbarthelmes! That makes it pretty obvious, want to do a PR also? ;)

**Comment by jbarthelmes** [comment]
@seberg I'm not a Python dev, so no.

**Comment by seberg** [comment]
Hehe, OK, I already did it anyway, just two lines of code :), there is a second conversion step in Py2, and there was a DECREF missing.
