### ISSUE TITLE
`while True: int(numpy.int64(0))` leaks memory

### ISSUE THREAD

**Issue by rshin** [numpy/numpy#10485]
Also happens for other types, like `int32` and `uint16`, and `float32`.

Reproducible on 1.14.0 with Linux (`numpy-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl` from PyPI), but not on 1.13.0.

**Comment by eric-wieser** [comment]
Related to #10474

**Comment by pv** [comment]
Does gh-10482 fix this?

**Comment by seberg** [comment]
I believe it does, but we need to backport it in any case.

**Comment by seberg** [comment]
The PR is labelled, so keeping this open unnecessary.
