### ISSUE TITLE
Documentation for extending NumPy leads to clang compiler failure

### ISSUE THREAD

**Issue by xoviat** [numpy/numpy#10486]
Consider the following example:

https://docs.scipy.org/doc/numpy-1.14.0/user/c-info.how-to-extend.html#required-subroutine
```
PyMODINIT_FUNC
init{name}(void)
{
   (void)Py_InitModule({name}, mymethods);
   import_array();
}
```

In Python 3, the initialization function returns a pointer to the module object, which means the return type of the initialization object is a pointer. The problem comes when clang expands the `import_array()` macro and finds that it attempts to return a type that is an integer (I assume) rather than a pointer:

```
  error: non-void function 'PyInit__module' should return a value [-Wreturn-type]
    import_array();
    ^
  /site-packages/numpy/core/include/numpy/__multiarray_api.h:1713:144: note: expanded from macro 'import_array'
  #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
```

**Comment by eric-wieser** [comment]
I've seen this issue before somewhere, in a question about how to call `import_array()` in a C++ constructor.

Having the `return` in the macro seems like a design mistake.

**Comment by xoviat** [comment]
I closed this because I need to investigate more before pinning this on NumPy.

**Comment by eric-wieser** [comment]
Numpy is already handling this, I think:
```
#if PY_VERSION_HEX >= 0x03000000
#define NUMPY_IMPORT_ARRAY_RETVAL NULL
#else
#define NUMPY_IMPORT_ARRAY_RETVAL
#endif
```

**Comment by xoviat** [comment]
Okay, so the issue occurs only on py2 + py3c (the initialization function is nonstandard, and has py3 semantics). Solution appears to be to use import_array1

**Comment by eric-wieser** [comment]
Or call `_import_array()`, which allows you more control than just `return`ing
