### ISSUE TITLE
fail to install smbus-cffi

### ISSUE THREAD

**Issue by puspa57** [numpy/numpy#10480]
Hello, 
I'm try to install smbus-cffi on my Omega2+ using PuTTY. This is what I got: 

root@Omega-98E4:~# pip install smbus-cffi
Collecting smbus-cffi
  Downloading smbus-cffi-0.5.1.tar.gz
Command "python setup.py egg_info" failed with error code 1 in
 /tmp/pip-build-OXoJFk/smbus-cffi/

**Comment by eric-wieser** [comment]
Wrong issue tracker? Your output doesn't contain the word `numpy`...

**Comment by seberg** [comment]
Yeah, lets, assume this is a mis-post for the moment.
