### ISSUE TITLE
MicroSD card Omega2+ 

### ISSUE THREAD

**Issue by puspa57** [numpy/numpy#10487]
I'm having unsuccessful with  MicroSD card for Omega2+. I followed this instruction very carefully and numerous time: to get external storage MicroSD card for my Omega2+. After done when I check storage there is no changed. 

https://docs.onion.io/omega2-docs/boot-from-external-storage.html#boot-from-external-storage-mounting-the-external-storage-device 
<img width="183" alt="capture2" src="https://user-images.githubusercontent.com/34567119/35469657-a153a986-0307-11e8-9109-7d64af7a52cb.PNG">

root@Omega-98E4:~# df -h                                                      
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 5.5M      5.5M         0 100% /rom
tmpfs                    61.4M    216.0K     61.2M   0% /tmp                  
/dev/mtdblock6           25.1M      9.9M     15.2M  39% /overlay              
overlayfs:/overlay       25.1M      9.9M     15.2M  39% /                     
tmpfs                   512.0K         0    512.0K   0% /dev                  
/dev/mmcblk0p1           14.2G     57.6M     13.4G   0% /tmp/run/mountd/mmcblk
root@Omega-98E4:~#            

expecting to get like image below   
<img width="430" alt="capture1" src="https://user-images.githubusercontent.com/34567119/35469648-423c0876-0307-11e8-8c9a-0ad5ea51f7aa.PNG">

**Comment by eric-wieser** [comment]
@puspa57, you are aware that this is the issue tracker for `numpy`, the numeric python library? This is the second time you opened an issue for another project here (gh-10480)
