### ISSUE TITLE
any() for object-dtype arrays returns non-booleans

### ISSUE THREAD

**Issue by acdr000** [numpy/numpy#10489]
The `any` function seems to not deal well for arrays of dtype `object`. According to the [documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.any.html) it should return a boolean. However, consider the following code:

`print(numpy.array([5, None]).any())`

To my surprise, this prints `5`, rather than `True`. It seems to always return the first element of which the boolean value is `True`, or, if no such elements exist, the last element. (This means that `numpy.array([False, None]).any()` evaluates to `None`.)

Appears to happen in Python 3.6.1, Numpy 1.12.1, on Linux, as well as Python 2.7.10, numpy 1.9.2. on Windows (10).

**Comment by charris** [comment]
That is how Python `or` works.
```
In [3]: None or 0
Out[3]: 0

In [4]: None or 5
Out[4]: 5
```
I suppose we could look at the result and convert it to a boolean.

**Comment by rkern** [comment]
I think we should just document the current behavior. `.all()` is essentially defined as `logical_or.reduce()`, and `logical_or`'s `object` implementation chose by design to replicate Python's `__or__` shortcut semantics.

**Comment by eric-wieser** [comment]
On the other hand, we're deviating from the builtin `all` and `any`, so we should at least have a warning in the docs about that.

Another fix would be to add a `OO->?` loop to `logical_or`, so that `dtype=bool` can be passed if desired.

I'm pretty sure this is a duplicate issue, but I can't find the original.

**Comment by ahaldane** [comment]
#6320 would "fix" this problem:
```python
>>> print(numpy.array([5, None]).any())
True
```
I'm not sure we're ever going forward with that PR, it's just food for thought.

**Comment by acdr000** [comment]
Editing the documentation is fine as well, of course. But I'd still find it a little bit funky that `array([5,2]).any()` would evaluate to something other than `array([5,2], dtype=object).any()`.

**Comment by aerobio** [comment]
I recently posted [this](https://stackoverflow.com/q/77954586/2148416) on stackOverflow and was directed to this thread.

Basically, this is odd:
```
>>> np.array([0, 111, 222]).any()
True
>>> np.array([0, 111, 222], dtype=object).any()
111
```
But at least the result is truthy, as expected.

However, this difference of behavior is a problem:
```
>>> np.invert(np.array([0, 111, 222]).any())
False
>>> np.invert(np.array([0, 111, 222], dtype=object).any())
-112
```

**Comment by seberg** [comment]
I changed this for NumPy 2.0.
