### ISSUE TITLE
Different results of numpy.linalg.inv depending on input dtype

### ISSUE THREAD

**Issue by marvinvanaalst** [numpy/numpy#10499]
While manually trying to solve a linear regression problem of the form 

> b = (X^T X)^{-1} X^T t

I noticed that it is necessary to convert the design matrix X to float values, in order to achieve the results of np.polyfit. For example, given an input array of  

``` python
x = [1,2,3,4,5,6,7,8,9,10] #or x = np.array([1,2,3,4,5,6,7,8,9,10])
```
and the design matrix functions

``` python
def design_matrix(x,N):
    x = np.array(x)
    power = np.array(list(range(0,N+1))).reshape(1,N+1)
    return np.power(x.reshape(-1,1),power)

def design_matrix_float(x,N):
    x = np.array(x).astype("float")
    power = np.array(list(range(0,N+1))).reshape(1,N+1)
    return np.power(x.reshape(-1,1),power)
```
The difference between the two matrix inversions
``` python
deg = 5
X = design_matrix(x,deg)
Xfloat = design_matrix_float(x,deg)
print(np.linalg.inv(np.matmul(X.T,X)) - np.linalg.inv(np.matmul(Xfloat.T,Xfloat)))
```
is non-zero

``` python
array([[ -2.62168254e+01,   4.32180394e+01,  -2.26876373e+01,
          5.07225293e+00,  -5.04169719e-01,   1.83334443e-02],
       [  4.32180394e+01,  -7.12442831e+01,   3.74002264e+01,
         -8.36153210e+00,   8.31116142e-01,  -3.02224052e-02],
       [ -2.26876373e+01,   3.74002264e+01,  -1.96335323e+01,
          4.38944965e+00,  -4.36300718e-01,   1.58654807e-02],
       [  5.07225293e+00,  -8.36153210e+00,   4.38944965e+00,
         -9.81344972e-01,   9.75433255e-02,  -3.54703002e-03],
       [ -5.04169719e-01,   8.31116142e-01,  -4.36300718e-01,
          9.75433255e-02,  -9.69557151e-03,   3.52566237e-04],
       [  1.83334443e-02,  -3.02224052e-02,   1.58654807e-02,
         -3.54703002e-03,   3.52566237e-04,  -1.28205904e-05]])
```
while for degree < 4

``` python
deg = 4
X = design_matrix_int(x,deg)
Xf = design_matrix_float(x,deg)
np.linalg.inv(np.matmul(X.T,X)) - np.linalg.inv(np.matmul(Xf.T,Xf))
```
it is exactly zero:

```python
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])
```

**Comment by ahaldane** [comment]
First,  `np.dtype('float')` is 32-bit on your machine, presubably, because I get all-0s up to `deg = 10`.

Second, I think that the integer one is "wrong" because you are hitting an integer overflow. Can you check if `np.matmul(X.T,X)` has any negative values?

**Comment by ahaldane** [comment]
If you are on 32 bit, it could also be that you lost too much precision on the floats.

Actually, I take back my last comment about the integer one being likely wrong. For `deg = 5` I don't think you hit overflow even with int32 with your values. But I do think you are getting limited float precision if using 32-bit floats. Try with 64 bit.

**Comment by marvinvanaalst** [comment]
I checked and the machine is running on 64 bit, the integer dtype is 32 bit and the float dtype is 64 bit.

Using int64 solved the problem for me.
I think you were right the first time, as I compared float32 and float64 outputs and they were identical. So most probably the integer one is wrong.

**Comment by mattip** [comment]
Please reopen if you wish to revisit the topic of int32 matrix inversion
