### ISSUE TITLE
Shared libraries are not stripped in the manylinux1 wheels

### ISSUE THREAD

**Issue by xhochy** [numpy/numpy#10519]
In all yet uploaded NumPy versions for manylinux1, the shared libraries are not stripped and thus ship a lot of bytes overhead.

```
# ll -h /opt/_internal/cpython-3.5.4/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 9.9M Feb  4 11:35 /opt/_internal/cpython-3.5.4/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
```

Calling strip on `multiarray` alone already saves 7.9MiB.

```
# strip /opt/_internal/cpython-3.5.4/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
# ll -h /opt/_internal/cpython-3.5.4/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 2.0M Feb  4 11:41 /opt/_internal/cpython-3.5.4/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
```

If someone could point me to the official scripts that generate these wheels, I would volunteer to change the build process that we only include stripped binaries.

**Comment by njsmith** [comment]
It would be nice if auditwheel were modified so that it stripped all the binaries it repackaged by default. That would automatically fix all manylinux wheels.

Maybe it would also be good to fix the numpy wheel build process to strip things explicitly – I guess Mac and Windows have the same issue. That's over here: https://github.com/MacPython/numpy-wheels

If you do it that way though then you'll probably want to also fix scipy, etc.

**Comment by charris** [comment]
I think the actual builder may be at https://github.com/numpy/windows-wheel-builder.

**Comment by xoviat** [comment]
Umm...the windows wheel builder is not used anymore.

> If someone could point me to the official scripts that generate these wheels, I would volunteer to change the build process that we only include stripped binaries.

Submit a PR to `pypa/auditwheel`. Changes there will have the broadest impact.

**Comment by charris** [comment]
> Umm...the windows wheel builder is not used anymore.

Ah yes, it was last used for 1.13. It is still included in `numpy-wheels` as a submodule, so we should probably get rid of that.

**Comment by xhochy** [comment]
Opened https://github.com/MacPython/numpy-wheels/issues/19 to resolve this on the next release.

**Comment by seberg** [comment]
We should be doing this for a long time, the linked issues have all been closed.
