### ISSUE TITLE
from ._globals import ModuleDeprecationWarning, VisibleDeprecationWarning ImportError: No module named _globa

### ISSUE THREAD

**Issue by neuronphysics** [numpy/numpy#10512]
Hello,

I have anaconda in my machine and using python 2.7. I uninstalled/installed  the numpy library using `conda install -n base  numpy`. After new installation when I import numpy I get this error:
```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 112, in <module>
    from ._globals import ModuleDeprecationWarning, VisibleDeprecationWarning
ImportError: No module named _globals
>>> quit()
```
I read different answers for similar problem, namely a conflict between version of numpy and python but I did not figure out how it should be resolved. Any suggestion how to deal with this issue will be appreciated.

**Comment by njsmith** [comment]
It sounds like some kind of problem with the installation, and since you used anaconda for the install you might have better luck asking in the anaconda bug tracker.

**Comment by mattip** [comment]
@neuronphysics did you work this out? Can we close it?

**Comment by mattip** [comment]
Closing from lack of response by the issue author. If the problem still exists, please reopen with more information
