### ISSUE TITLE
"too many indices" in single element array

### ISSUE THREAD

**Issue by asmasca** [numpy/numpy#10510]
I'm writing a code that starts by reading an input catalog given by the user. The catalog has a number of elements that goes anywhere from 1 o whatever. Then the code loops over all elements to do its thing.

Let's assume the names of the elements are stored in an array called "names"

When the catalog includes 2 or more elements, everything is fine. But when it includes just 1 element, I get the following errors:

len(names) --> len of unsized object
names[0] --> Too many indices for array

The code to read the catalog would be just
names=np.loadtxt(cat,unpack=True,skiprows=0,dtype=("U25"))

Does anyone know what would be the right way of doing this? I'm right now transitioning from IDL to Python, and this seemed a very straightforward way of writing it. 

Thanks in advance

**Comment by pv** [comment]
For usage advice, stackoverflow.com is a better place to ask questions 
of this type.

**Comment by seberg** [comment]
Heh, it is a bit annoying (genfromtext is a bit more verbose here even maybe), but the documentation *does* say how to get around this, with the correct arguments, so will close this.
