### ISSUE TITLE
Remaining genfromtxt vs StringIO woes

### ISSUE THREAD

**Issue by adeak** [numpy/numpy#10511]
I know that `genfromtxt` has some issues, see https://github.com/numpy/numpy/issues/3184. As I see it this was related to why calling `genfromtxt` on a `StringIO` as per [the examples](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html) was broken for a while. I tested the following two examples:

```python
import numpy as np
from io import StringIO, BytesIO

def with_stringio():
    s = StringIO("1,1.3,abcde")
    return np.genfromtxt(s, dtype=[('myint','i8'),('myfloat','f8'),
                                   ('mystring','S5')], delimiter=",")

def with_bytesio():
    s = BytesIO(b"1,1.3,abcde")
    return np.genfromtxt(s, dtype=[('myint','i8'),('myfloat','f8'),
                                   ('mystring','S5')], delimiter=",")
```

The `BytesIO` case worked fine on every test I ran.

For numpy 1.13.3 the `StringIO` case was broken across python 2.7, 3.5, 3.6 with the following TypeErrors:
 * 2.7: "initial_value must be unicode or None, not str"
 * 3.5: "Can't convert 'bytes' object to str implicitly"
 * 3.6: "must be str or None, not bytes"

Upgrading numpy to 1.14.0 fixed the example for both python 3 versions I tested, however 2.7 is still broken. On the other hand, the `BytesIO` example works across all three versions I tested.

Should the docs not be changed to use `BytesIO` at least until the `StringIO` case is cleaned up for 2.7? That would be an acceptable workaround on python 2.7 for the time being, but then again for python 3 using `StingIO` is probably better.

Also note that it seems that the upgrade to 1.14.0 fixes https://github.com/numpy/numpy/issues/9653.

**Comment by eric-wieser** [comment]
The 2.7 failure you observe is not coming from numpy:

```
>>> StringIO("1,1.3,abcde")
TypeError: initial_value must be unicode or None, not str
```

The fix would be to write that as `StringIO(u"1,1.3,abcde")`.

**Comment by adeak** [comment]
Thanks, @eric-wieser, I missed that. Is that an acceptable fix? From a quick grep it seems to me that there are no existing examples containing unicode literals, only separate tests. If this is not an issue I'll gladly submit the (admittedly trivial) fix.

**Comment by eric-wieser** [comment]
Yeah, I think that would be a sensible doc change. Go ahead and make the patch!

**Comment by eric-wieser** [comment]
See also: #10991

**Comment by adeak** [comment]
Thanks for the link, submitted the PR. I also wanted to update the example outputs to the actual ones, but I ran into the deprecation you raised in https://github.com/numpy/numpy/issues/10990. So that can be a separate PR once the encoding issue is settled.

**Comment by FilipDominec** [comment]
With ```np.version.version == '1.13.3'``` still in Ubuntu 18.04, I think many people would appreciate a fix of the example code that works. I may be missing something, but I get following errors in Python3 trying a bytes object: 

```
In [11]: data = b"1, 2, 3\n4, 5, 6"

In [12]: np.genfromtxt(StringIO(data), delimiter=",")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-5e7122461d27> in <module>()
----> 1 np.genfromtxt(StringIO(data), delimiter=",")

TypeError: initial_value must be str or None, not bytes
```

Trying forced unicode string:

```

In [13]: data = u"1, 2, 3\n4, 5, 6"

In [14]: np.genfromtxt(StringIO(data), delimiter=",")

...
TypeError: must be str or None, not bytes
```

**Comment by eric-wieser** [comment]
@FilipDominec: Numpy 1.13.3 is well beyond its support lifetime, and will not be receiving any further updates. Can you try upgrading to 1.15.x, and see if the problem persists?

**Comment by FilipDominec** [comment]
I am sorry, being on my production machine I will probably have to wait for new Ubuntu LTS version with numpy updates; then I would certainly report such a problem if it persists.

**Comment by adeak** [comment]
@FilipDominec any chance you can leave the archaic ubuntu repository behind and install a newer local numpy version (possibly in a virtualenv)?
