### ISSUE TITLE
BUG: np.dtype(ctypes.Structure) does not respect _pack_ field

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10532]
```python
class Foo(ctypes.Structure):
    _fields_ = [('one', ctypes.c_uint8), ('two', ctypes.c_uint32)]
    _pack_ = 2
```
```python
>>> ctypes.sizeof(Foo())  # packed to alignment 2
6
>>> np.dtype(Foo).itemsize  # default alignment incorrectly used
8
```

Fix should be fairly straightforward by changing:

https://github.com/numpy/numpy/blob/44810f07ec6a281d96d6a69c105ce6ae59aec718/numpy/core/_dtype_ctypes.py#L35-L46

**Comment by tylerjereddy** [comment]
Incidentally, I've been thinking a lot about using `ctypes` to define custom dtypes lately, since Python-based custom dtype definition is currently on our roadmap. I wonder how many other issues there are with trying to reconstitute the NumPy version of `PyTypeObject` `struct` from a Python object subclassed from a `ctypes.Structure`.

**Comment by eric-wieser** [comment]
I don't fully understand what you're suggesting - but right now using ctypes as an exchange format is a pretty poor path for anything, because the objects are hard to inspect:

* `_fields_` does not contain endianness information (#10533), so is not reliable
* The only way to inspect the post-construction type is via PEP3118
* Old versions of python provide incorrect PEP3118 format strings for integer ctypes
* Bleeding-edge versions of python still give incorrect PEP3118 format strings for almost all structs (python/cpython#5561,)
* leeding-edge versions of python still give incorrect PEP3118 format strings for empty arrays (python/cpython#5576)

**Comment by tylerjereddy** [comment]
I basically mean doing what you just did above, but extending it to comprehensively define a useful custom dtype that inherits from `ctypes.Structure`. Looks like you're way ahead of me and already have CPython PRs open!

**Comment by eric-wieser** [comment]
To be clear - by custom dtype, do you mean _structured_ dtype, or are you envisaging applying it to things like fixed-pointer numbers / auto-differentiating scalars / etc?

**Comment by tylerjereddy** [comment]
More the auto-differentiating scalars and other custom dtypes of that nature, like those supporting units or missing integer support.

So:

```Python
class AmazingDtype(ctypes.Structure):
    # this is an amazing third-party NumPy dtype
    # that implements automatic forward differentiation
    # without touching a single C file by using the
    # Python standard library ctypes.Structure to fill
    # in all the requisite structure members of the type class
    # needed to do useful things as a NumPy dtype
    pass
```

**Comment by mattip** [comment]
I would not like to encourage deeper use of ctypes. The code behind them has many open issues. The package defines yet-another-dsl for describing c-like interfaces. It has so many layers it will always be slow and buggy.  Why not directly inherit from a new `dtypes.baseclass` that returns `NotImplemented` where needed instead?

**Comment by eric-wieser** [comment]
I'm with @mattip here. We don't want to built on top of ctypes - only provide compatibility with it.

**Comment by eric-wieser** [comment]
As of #12254, this should be fairly straightforward to fix.
