### ISSUE TITLE
3D array F-contiguous and C-contiguous at the same time

### ISSUE THREAD

**Issue by andreanicastro** [numpy/numpy#10530]
Trying to solve another issue I stumble across a wierd (to me) effect that I can't understand.
The following code:

 ```
im_np = np.ones((2880,1800,3), dtype=np.uint8)                                              
 print("Before transpose:\n{}".format(im_np.flags))                                          
 im_np = np.transpose(im_np, (1,0,2))                                                        
 print("After transpose:\n{}".format(im_np.flags))                                                                                                                       
 im_tmp = np.copy(im_np.flags, order='K')                                                    
 print("With K copy:\n{}".format(im_tmp.flags))                                              
 im_np_cpy = np.copy(im_np, order='C')                                                       
 print("With C copy:\n{}".format(im_np_cpy.flags))     
```

outputs:

> Before transpose:
>   C_CONTIGUOUS : True
>   F_CONTIGUOUS : False
>   OWNDATA : True
>   WRITEABLE : True
>   ALIGNED : True
>   WRITEBACKIFCOPY : False
>   UPDATEIFCOPY : False
> After transpose:
>   C_CONTIGUOUS : False
>   F_CONTIGUOUS : False
>   OWNDATA : False
>   WRITEABLE : True
>   ALIGNED : True
>   WRITEBACKIFCOPY : False
>   UPDATEIFCOPY : False
> With K copy:
>   C_CONTIGUOUS : True
>   F_CONTIGUOUS : True
>   OWNDATA : True
>   WRITEABLE : True
>   ALIGNED : True
>   WRITEBACKIFCOPY : False
>   UPDATEIFCOPY : False
> With C copy:
>   C_CONTIGUOUS : True
>   F_CONTIGUOUS : False
>   OWNDATA : True
>   WRITEABLE : True
>   ALIGNED : True
>   WRITEBACKIFCOPY : False
>   UPDATEIFCOPY : False
> 

Focusing on:

> With K copy:
>   **C_CONTIGUOUS : True**
>   **F_CONTIGUOUS : True**
>   OWNDATA : True
>   WRITEABLE : True
>   ALIGNED : True
>   WRITEBACKIFCOPY : False
>   UPDATEIFCOPY : False

I don't understand how a 3D vector can be both F-contiguous and C-contiguous. 
Am I missing something? Is it a behaviour to be expected? The documentation is not really clear on this.

**Comment by ahaldane** [comment]
You've got a typo! `im_tmp = np.copy(im_np.flags, order='K')` should be `im_tmp = np.copy(im_np, order='K')`.  You actually ended up with a 1d object array.

(The fact that it is so easy to mistakenly get object arrays is something we want to fix one day)

**Comment by andreanicastro** [comment]
Oh god... that **is**  embarrassing. Thanks!
