### ISSUE TITLE
'ERRORS ARE TO BE EXPECTED-PLEASE REPORT THEM TO THE NUMPY DEVELOPERS'

### ISSUE THREAD

**Issue by BenjiEzivon** [numpy/numpy#10556]
![beweis](https://user-images.githubusercontent.com/26362862/36021942-a45a06d6-0d87-11e8-907f-f02423d8b39a.png)

Sorry for the bad quality but the program instantly closed after opening it.

I've written a code for AStar Pathfinding with Numpy but it crashes Python. Sometimes I got this error screen. There is a bit of German as I am german. It says: 'The given module wasn't found' after DIL load failed. Here is my code:

`from PIL import Image
import sys
import AAStar
import heapq
sys.setrecursionlimit(sys.maxint)
weiss = (255,255,255)
schwarz = (0,0,0)
grun = (0,99,0)
rot = (99,0,0)
grau1 = (207,207,207)
grau2 = (43,43,43)
grau3 = (27,27,27)
grau4 = (23,23,23)
liste = []
walls = []
c1 = 0
c2 = 0
rechlist = []
rotlist = []
start = []
reachable = False
s = 0
r=0
nmap = []

Bild = Image.open('quax.png')
quaxerg = Bild.copy
w, h = Bild.size
Bildk = Bild.resize((int(w*0.5), int(h*0.5)),Image.BICUBIC)
Bildk.save('b.png')
w = w * 0.5
h = h * 0.5

for y in range(h):
    for x in range(w):
        if Bildk.getpixel((x,y)) == (grau1 or grau2 or grau3 or grau4):
            wall.append(1)
        if Bildk.getpixel((x,y)) == rot:
            c1 = x
            c2 = y
            rechlist.append(c1)
            rechlist.append(c2)
            rotlist.append(rechlist)
            rechlist=[]
        if Bildk.getpixel((x,y)) == grun:
            start.append(x)
            start.append(y)
        if Bildk.getpixel((x,y)) == weiss:
            walls.append(1)
        if Bildk.getpixel((x,y)) == schwarz:
            walls.append(0)
    nmap.append(walls)
    walls = []
        
    nmap = np.array(nmap)

    class AStar():

        def __init__(self, grid, x, y, goal_x, goal_y)    :
            self.grid = grid
            self.initial_x = x 
            self.initial_y = y 
            self.x = self.initial_x  
            self.y = self.initial_y  
            self.goal_x = goal_x  
            self.goal_y = goal_y 
            self.neighbors = []
            self.neighbor()

        def neighbor(self):
            if self.x == self.goal_x and self.y == self.goal_y:
                print('your done')
                return 'your done'

            self.grid[self.x][self.y] = 1
            
            if self.x > 0: 
                if self.grid[self.x-1] [self.y] == 0:
                    self.neighbors.append([self.x - 1, self.y])  

            if self.x < self.grid.shape[0] - 1:
                if self.grid[self.x+1][self.y] == 0: 
                    self.neighbors.append([self.x+1,self.y]) 

            if self.y > 0:
                if self.grid[self.x][self.y - 1] == 0:
                    self.neighbors.append([self.x, self.y - 1])

            if self.y < self.grid.shape[1] - 1: 
                if self.grid[self.x][self.y + 1] == 0:
                    self.neighbors.append([self.x, self.y + 1]) 

            self.f_value()

   
        def f_value(self):
            h_values = []
            g_values = []  

            for i in self.neighbors:     
                x_distance = abs(i[0] - self.goal_x)  
                y_distance = abs(i[1] - self.goal_y)  
                h_value = (x_distance + y_distance)
                h_values.append(h_value)
 
            for i in self.neighbors:
                x_distance = abs(i[0] - self.initial_x)  
                y_distance = abs(i[1] - self.initial_y)
                g_value = (x_distance + y_distance)
                g_values.append(g_value)

            self.f_values = [h + g for h, g in zip(h_values, g_values)]
            self.path()

        def path(self):

            for coordinate, i in enumerate(self.f_values):
                if i <= min(self.f_values):
                    value = i
                    index = coordinate 

            self.x = self.neighbors[index][0]        
            self.y = self.neighbors[index][1]

            print('f_values:', self.f_values)
            print('neighbors:', self.neighbors)  
            print('x:', self.x)
            print('y:', self.y)

            self.neighbors.pop(index)
            self.f_values.pop(index)

            self.neighbor()

c1 = start.pop(0)
c2 = start.pop(0)
while (len (rotlist)) != 0 :
    liste = rotlist.pop(0)
    s = liste.pop(0)
    r = liste.pop(0)
    print AStar.__innit__(nmap, c1,c2,s,r)`

![quax](https://user-images.githubusercontent.com/26362862/36022220-8c87105c-0d88-11e8-846b-87c635b5624f.png)
This is the picture it opens

The Code is written in python 2.3 (as I need PIL and that's the newest version I got PIL to work)
I use Windows 10.

That's my Problem. I hope you can help me as this is made for a contest.

**Comment by rgommers** [comment]
Please don't spend time on Python 2.3. PIL is abandonware, its modern maintained fork is Pillow - you can install that with Python 2.7 or 3.x

**Comment by rgommers** [comment]
If this is a numpy install issue, you should be able to reproduce it by executing `import numpy` in the Python interpreter. Can you?

Otherwise, make sure you run your program from the command line instead of the GUI, so you get a sensible traceback.

**Comment by BenjiEzivon** [comment]
A reinstallation of Python, Pillow, and Numpy helped me. Thank you
