### ISSUE TITLE
Numerical computation problem

### ISSUE THREAD

**Issue by MasKong** [numpy/numpy#10577]
Below is my program. The output is different when I return a*b and the whole result  return (np.sum(l,axis=0) * np.log(l.shape[0]/np.sum(l>0,axis=0))). Why? Below is the code.

import numpy as np

def dot_product(l1, l2):
    sum_dp = 0
    for i in range(len(l1)):
        sum_dp += l1[i] * l2[i]
    return sum_dp

def tf_idf(l):
    #print (np.sum(l,axis=0))
    a = np.sum(l,axis=0)
    #print (float(l.shape[0])/np.sum(l>0,axis=0))
    #print (np.log(float(l.shape[0])/np.sum(l>0,axis=0)))
    b = np.log(float(l.shape[0])/np.sum(l>0,axis=0))
    print (a*b)
    #return a*b
    return (np.sum(l,axis=0) * np.log(l.shape[0]/np.sum(l>0,axis=0)))

l1 = np.array([3,0,5,0,2,6,0,2,0,2]).reshape(10,1).T
l2 = np.array([0,7,0,2,1,0,0,3,0,0]).reshape(10,1).T
l3 = np.array([0,1,0,0,1,2,2,0,3,0]).reshape(10,1).T
l4 = np.concatenate((l1,l2, l3),axis = 0)
print (l4)
res = tf_idf(l4)
print (res)
<img width="910" alt="screenshot 2018-02-13 12 15 38" src="https://user-images.githubusercontent.com/23203109/36133272-ac8955f4-10b7-11e8-9ce1-dc135bbf8a00.png">

**Comment by seberg** [comment]
This seems like a usage problem and does not really belong here. The two things might differ in your code in any case if you use python 2, which I assume, with the second version not being what you want.
