### ISSUE TITLE
Link to Oliphants Guide to Numpy is broken

### ISSUE THREAD

**Issue by andyfaff** [numpy/numpy#10572]
```https://github.com/numpy/numpy/search?utf8=%E2%9C%93&q=tramy.us&type=```
directs to `http://ww12.tramy.us/`, which definitely isn't the `Guide to Numpy`, and looks somewhat dodgy.

**Comment by pv** [comment]
I guess either docs.scipy.org should host a copy of the PDF, or just 
remove the hyperlink.

The link to the sources is:
https://github.com/numpy/numpy/tree/pre-removal-numpybook/doc/numpybook

**Comment by rgommers** [comment]
+1 for hosting a pdf, the book is still in demand.

**Comment by derrickaw** [comment]
This issue keeps lingering around from #9088 and #8520.  How about pointing users to https://archive.org/details/NumPyBook which was suggested by @nicoguaro in #8520?

**Comment by rgommers** [comment]
Fixed by gh-10592, closing. Thanks all!
