### ISSUE TITLE
Miniseed to SEG-Y

### ISSUE THREAD

**Issue by shicks-seismo** [numpy/numpy#10580]
Hi all,

I'm trying to write seg-y files from miniSEED (STEIM-2 compressed) data.

The stream is at 20 sps, I have trimmed the data to a 60 second long segment (1201 samples) and converted the data type to float32, as follows: 

```
st = read("WI.DSD.00.BHZ.D.2017.032")
st.trim(st[0].stats.starttime+60, st[0].stats.starttime+120)
st[0].data = np.require(st[0].data, dtype=np.float32)
st.write('/Users/sph1r17/test.segy', format="SEGY", encoding=1)
```

Yet, I still get the following error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/core/stream.py", line 1443, in write
>     write_format(self, filename, **kwargs)
>   File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/core.py", line 394, in _write_segy
>     segy_file.write(filename, data_encoding=data_encoding, endian=byteorder)
>   File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/segy.py", line 256, in write
>     self._write(file, data_encoding=data_encoding, endian=endian)
>   File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/segy.py", line 296, in _write
>     self.binary_file_header.write(file, endian=endian)
>   File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/segy.py", line 502, in write
>     file.write(pack(format, getattr(self, name)))
> struct.error: 'h' format requires -32768 <= number <= 32767

Here are the header details are trimming and converting the dtype:

> network: WI
> station: DSD
> location: 00
> channel: BHZ
> starttime: 2017-02-01T00:01:00.025000Z
> endtime: 2017-02-01T00:02:00.025000Z
> sampling_rate: 20.0
> delta: 0.05
> npts: 1201
> calib: 1.0
> _format: MSEED
> mseed: AttribDict({'encoding': 'STEIM2', 'record_length': 512, 'byteorder': '>', 'number_of_records': 4145, 'dataquality': 'M', 'filesize': 2122240})
> processing: ['ObsPy 1.1.0: trim(endtime=UTCDateTime(2017, 2, 1, 0, 2, 0, 25000)::fill_value=None::nearest_sample=True::pad=False::starttime=UTCDateTime(2017, 2, 1, 0, 1, 0, 25000))']

I understand from https://github.com/obspy/obspy/issues/1393 that this is to do with the number of samples, but the number of samples in my trace is far below the maximum of 32767. 

The raw miniSEED file can be found on my Dropbox here: https://www.dropbox.com/s/b8dh36c0h5ig0yk/WI.DSD.00.BHZ.D.2017.032?dl=0

**Comment by eric-wieser** [comment]
I don't see numpy anywhere in that stack trace or code, so I'm not sure this is the right place to report this.

**Comment by shicks-seismo** [comment]
Whooops I posted this on completely the wrong repository. Many apologies! Feel free to delete.
