### ISSUE TITLE
np.histogram gives confusing error message when NaN is encountered

### ISSUE THREAD

**Issue by jsh9** [numpy/numpy#10601]
If one tries to do `np.histogram([1,2,3,4,np.nan])`, then an error message is thrown:
`ValueError: range parameter must be finite.`

This message is somewhat confusing, because I had to open up the source code of `histogram` to see that `mn` and `mx`, which were determined from `a.min()` and `a.max()`, were NaN because of NaN's in the input data.

Is it possible to change it to something like "input data contains NaN, which is not supported"?

Python version: 3.6
numpy version: 1.13.3

**Comment by eric-wieser** [comment]
Same message in 1.14

Note that input containing NaN _is_ supported, but only if a range parameter is specified. The same behavior can be seen for infinities too - so perhaps `"autodetected range of [{min}, {max}] is not finite"`

A patch should be fairly straightforward

**Comment by kirit93** [comment]
I'd like to make this patch. Can I go ahead and submit a PR?

**Comment by stefanv** [comment]
Is this ticket resolved?

**Comment by eric-wieser** [comment]
Good catch

**Comment by whtowbin** [comment]
Could this be improved by giving the option to use np.nanmin and np.nanmax? Or make this the default?

**Comment by jmoraispk** [comment]
@eric-wieser, I'm still getting the same error for histogram. Has this been merged?

The change @whtowbin proposed works quite well.

In the file, `numpy/lib/histograms.py`, change the line 
`first_edge, last_edge = a.nanmin(), a.nanmax()`
to 
`first_edge, last_edge = a.min(), a.max()`
