### ISSUE TITLE
Why eigenvectors seem incorrect in python?

### ISSUE THREAD

**Issue by nipnipj** [numpy/numpy#10616]
I'm trying to get the eigenvalues and eigenvectors from a square matrix with the following commands:
```
import numpy as np
A = matrix([[5,2,0],[3,1,-5],[11,4,-4]])
λ, U = np.linalg.eig(A)
print ('Starting matrix:\n', A)
print('\nEigenvalues:\n', λ)
print('\nEigenvectors:\n', U)
```
The eigenvalues coincide with other softwares, but the eigenvector not. It makes me wonder what I'm doing wrong?

**Comment by shoyer** [comment]
Even if the eigenvalues are unique, eigenvectors are only only unambiguously defined up to a multpilicative phase `exp(1j*phi)`

**Comment by nipnipj** [comment]
I missed that detail. I really appreciate your help!
If there any way to get eigenvectors similar to other software?

**Comment by shoyer** [comment]
Well, first you would have to show me what the other software is....

But if you need to reproduce eigenvectors from other software, the simple answer is that you are probably making the wrong sort of comparison.

**Comment by nipnipj** [comment]
Python report normalized eigenvectors (Euclidean normalization).
Thanks for your time!
This issue can be closed.

**Comment by charris** [comment]
NumPy returns normalized eigenvectors.
```
In [6]: A = array([[5,2,0],[3,1,-5],[11,4,-4]])

In [7]: e, v = np.linalg.eig(A)

In [8]: sqrt(sum(v*v, axis=0))
Out[8]: array([1., 1., 1.])
```
Note that the eigen vectors are stored in the columns, not rows. The usual differences in reported eigen vectors is the sign, i.e., vectors from one algorithm may differ from another algorithm by being multiplied by -1. Somewhat apart from that, use of matrices is discouraged, plain old arrays are much preferred.
