### ISSUE TITLE
PyArray_GetField() steals ref to descr

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#10627]
The doc currently doesn't mention that `PyArray_GetField` steals a reference to its `descr` argument.

**Comment by SahanaJavgal** [comment]
Hello, I am new to Open Source and I am Applying for Outreachy. I would like to work on this Issue. Could you please assign it to me @pitrou

**Comment by mattip** [comment]
@SahanaJavgal better than "assign" ing an issue to you is to issue a pull request, put in the comment the text `fixes #10627`. Then a cross-ling to the opened pull request will appear here and others will know you are working on it.

**Comment by SahanaJavgal** [comment]
Okay thanks

**Comment by SahanaJavgal** [comment]
#13235 fixes the above issue #10627
