### ISSUE TITLE
Strange behavior with slicing

### ISSUE THREAD

**Issue by Aelphy** [numpy/numpy#10638]
`import numpy as np`

`template = np.random.random(size=12).reshape(3, 4)`

Results of:

`template[:, np.random.choice(template.shape[1], size=template.shape[0])]`
and
`template[np.arange(template.shape[0]), np.random.choice(template.shape[1], size=template.shape[0])]`
are different.

Shouldn't they be the same ?

**Comment by pv** [comment]
No: 
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#indexing-with-arrays-of-indices

**Comment by Aelphy** [comment]
Got it, thnx
