### ISSUE TITLE
about asmatrix API

### ISSUE THREAD

**Issue by woaij100** [numpy/numpy#10632]
x = np.array([[1,2],[3,4]])
m = np.asmatrix(x)
x[0,0]
1
https://docs.scipy.org/doc/numpy/reference/generated/numpy.mat.html

**Comment by hameerabbasi** [comment]
So, what is your question?

I would highly recommend you use `ndarray` instead of `matrix`. It's dated. If you want to use linear algebra, use `ndarray`, and use `np.dot(a, b)` for matrix multiplication, or `a @ b` assuming you're using Python 3.5 or newer.

**Comment by woaij100** [comment]
Sorry,I mean your example maybe wrong,you can see this url in my first email.

(return 5)

**Comment by njsmith** [comment]
The example sets `x[0, 0]` to 5.

I don't know why. Just to confuse people I guess? It seems like it would be clearer to just do `m = np.asmatrix(x)`, and then show `m`.

**Comment by hameerabbasi** [comment]
```python
>>> x[0,0] = 5
```

The triple arrow indicates that this is an input. `...` indicates that the input is continued on the next line; and any line without these two indicates that this is an output.

**Comment by woaij100** [comment]
ohhhh...sorry Thanks

**Comment by hameerabbasi** [comment]
Close?
