### ISSUE TITLE
Large Files Crash np.loadtxt

### ISSUE THREAD

**Issue by heaton56** [numpy/numpy#10644]
using:

`V, I = np.loadtxt('test2.txt', usecols=(1,2), unpack=True)`

I get:

ValueError: could not convert string to float: 'âˆž'

whenever the file is longer than about 400K lines.

**Comment by heaton56** [comment]
To be more precise, it fails at 1 million lines and works at 300K lines. 
In my case the work around is to do line by line decimation to reduce the amount of data. However, there are many applications where big data can't be decimated.

**Comment by charris** [comment]
A million lines isn't big. What OS and what NumPy version?

**Comment by heaton56** [comment]
Windows10 latest update, np version 1.14.1.
[data1MLines.zip](https://github.com/numpy/numpy/files/1746038/data1MLines.zip)
