### ISSUE TITLE
Please add Sphinx search field to numpy html docs

### ISSUE THREAD

**Issue by JakobJakobson** [numpy/numpy#10643]
Dear developers

the official Python documentation has the very handy feature of a search field in its top navigation bar that allows you to perform a search directly within its documentation.
Could you implement something like that as well for your documentation as it is a very convenient feature?

Regards,

Jakob

**Comment by sujaypat** [comment]
@JakobJakobson Can this be closed since the related PR has been merged?

**Comment by mattip** [comment]
yes, thanks
