### ISSUE TITLE
BUG: setup.py does not build if egg-info is specified

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10646]
This command fails to make numpy build

```
python setup.py egg-info build install
```

But this works fine:

```
python setup.py egg-info
python setup.py build
python setup.py install
```

As the presence of `egg-info` causes builds to be skipped

**Comment by rgommers** [comment]
That looks like a wontfix to me, there's no good reason to do that that I'm aware of. `egg_info` is a bit of an implementation detail, this build command isn't normal usage.
