### ISSUE TITLE
cumsum performance hit when same array is passed in as 'out' argument

### ISSUE THREAD

**Issue by jonathanlintott** [numpy/numpy#10640]
If `np.cumsum` is called where the `out` argument is the same array as `a`, then the call can take over twice as long depending on the shape of `a` and the axis chosen.

Example:
```
arr = np.random.random((100, 500))

out1 = np.cumsum(arr, axis=0)  # First call

out2 = np.zeros((100, 500))
np.cumsum(arr, axis=0, out=out2)  # Second call, no noticeable performance difference

np.cumsum(arr, axis=0, out=arr)  # Third call, takes over twice as long
```
The performance hit can be seen on arrays with different number of dimensions, although it is smaller on `1D` arrays.

This is when using numpy 1.13.1 and python 2.7.11 on a windows 64 machine.

**Comment by pv** [comment]
The data dependence is too complex for the generic heuristics (which do 
not know they are doing cumsum along an axis) to decide on the fly that 
no temporary copy is needed.

**Comment by rekcahpassyla** [comment]
Is there any other equivalent way of getting the same performance as in numpy 1.10? Basically we have code that uses quite a lot of calls to `cumsum` and those now take 3x as long. We are seeing a rather large performance hit. I tried `np.add.accumulate` but it had the same behaviour as `np.cumsum` (which I kind of expected)

**Comment by rekcahpassyla** [comment]
Here are some more concrete numbers
numpy 1.10.4:
```python
In [1]: import numpy as np

In [2]: tmp = np.random.random((13, 31, 5000))

In [3]: tmp.flags
Out[3]:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [4]: %timeit np.cumsum(tmp, axis=0)
10 loops, best of 3: 23.3 ms per loop

In [5]: %timeit np.cumsum(tmp, axis=0, out=tmp)
100 loops, best of 3: 9.03 ms per loop

In [6]: np.__version__
Out[6]: '1.10.4'

```

numpy 1.13:

```python
In [1]: import numpy as np

In [2]: tmp = np.random.random((13, 31, 5000))

In [3]: tmp.flags
Out[3]:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [4]: %timeit np.cumsum(tmp, axis=0)
10 loops, best of 3: 22.9 ms per loop

In [5]: %timeit np.cumsum(tmp, axis=0, out=tmp)
10 loops, best of 3: 31.1 ms per loop

In [6]: np.__version__
Out[6]: '1.13.1'

```

**Comment by pv** [comment]
There's no workaround I know, apart from writing your own 
`fast_cumsum_axis` in a few lines of C or Cython.

The accumulate-into-same-array common special case can however probably 
be detected relatively easily in PyUFunc_Accumulate. This may be as 
simple as turning on the *ASSUME_ELEMENTWISE iterator flag but that may 
need some more thinking.

**Comment by rekcahpassyla** [comment]
tHanks- I guess in the short term we'll have to roll our own. I'm slightly surprised that nobody else ran into this

**Comment by seberg** [comment]
Well, as Pauli said, removing the safety check for identical arrays should not be hard at all (and is probably even trivial as he pointed out). If you do not have identical arrays, it gets tricky whether or not an operation is safe, but I doubt you need that.

**Comment by rekcahpassyla** [comment]
I wasn't able to get numpy to build on Windows the last time I tried, unfortunately

**Comment by jonathanlintott** [comment]
It's important to note that the pattern `func.accumulate(a, out=a)` occurs in the numpy library an at least one other location, under `np.vander`.

Due to this line [here](https://github.com/numpy/numpy/blob/a4e47e0205b78eb96248e71918c2558e25a9d3c7/numpy/lib/twodim_base.py#L528) (`multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)`) the vander function is twice as slow in 1.13 than in 1.10.

The tests on my machine for 1.10.4
```
In [3]: arr = np.random.random((1000))
In [4]: %timeit np.vander(arr)
10 loops, best of 3: 14.2 ms per loop
```
And for 1.13.1
```
In [3]: arr = np.random.random((1000))
In [4]: %timeit np.vander(arr)
10 loops, best of 3: 28.9 ms per loop
```

**Comment by pv** [comment]
It's actually not fully true that `np.cumsum(a, out=a) == np.cumsum(a)` --- integer overflow appears to be problematic (assert fails both on 1.12.1 and on 1.14.1):
```
import numpy as np
np.random.seed(1234)
x0 = np.random.randint(0, 2**16, size=(7, 13, 8, 21)).astype(np.int16)
x = x0.copy()
y0 = np.add.accumulate(x0, axis=3)
y = np.add.accumulate(x, out=x, axis=3)
assert np.all(y == y0)
```

**Comment by seberg** [comment]
Hehe, tricky stuff, but this should just be because setting out makes the accumulate loop not do the automatic upcast to "at least long when we are summing" that probably kicks in here, so I am not sure it changes a lot here. But shows that things are always trickier then you expect :).
