### ISSUE TITLE
DOC/BUG: np.sum supports generators, unlike the other reduction helpers

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10652]
```python
>>> np.sum(a for a in range(10))
45
>>> np.prod(a for a in range(10))
<generator object <genexpr> at 0x0000023BAF7ED1A8>
```

Generators are not considered `array_like`, so the result for `sum` does not match the documentation.

Introduced in a13aad3ac33b629f3e696b4d4d5dbf4b5605d567

**Comment by hameerabbasi** [comment]
This also happens for `np.[any|all|min|max]`. I fixed it in #10661. Take a look.
