### ISSUE TITLE
Last 3 digits are lost after converting pd.Timestamp to np.datetime64

### ISSUE THREAD

**Issue by fujiisoup** [numpy/numpy#10668]
Last 3 digits are lost after converting pd.Timestamp to np.datetime64

```python
In [12]: ts = pd.Timestamp(np.datetime64('2018-02-12 06:59:59.999986560'))
    ...: ts
    ...: 
Out[12]: Timestamp('2018-02-12 06:59:59.999986560')

In [13]: np.datetime64(ts, 'ns')
Out[13]: numpy.datetime64('2018-02-12T06:59:59.999986000')  # last three digits **560 are lost
```
It looks following `pd.Timestamp` -> `np.datetime64[us]` ->`np.datetime64[ns]`

Is this a something expected?
I think the recommended way to convert a `pandas.Timestamp` to `np.datetime64` is to use `pandas.Timestamp.to_datetime64`, but it would be nice for us to use numpy's typecasting to keep consistency.

From pydata/xarray#1932, pydata/xarray#1942

**Comment by shoyer** [comment]
This makes sense because `pandas.Timestamp()` is a `datetime.datetime` subclass. I think making `Timestamp` a datetime subclass was probably a mistake, but it's hard to see that changing in pandas and in any case there's not much numpy can do about it.

**Comment by fujiisoup** [comment]
Thanks for the infomation. Closing.

**Comment by eric-wieser** [comment]
@shoyer: Can you elaborate on that? Is pandas storing the last three digits in an extra field?
