### ISSUE TITLE
Before release, warn that it is due

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#10662]
As requested in https://github.com/numpy/numpy/pull/10544#issuecomment-368281014, a reminder to send a warning to the numpy list when a release is about to made, so projects such as scipy and astropy, which do CI against numpy-dev, can check that whatever is about to be released does not break things.

**Comment by rgommers** [comment]
This is always done AFAIK, and https://github.com/numpy/numpy/blob/master/doc/HOWTO_RELEASE.rst.txt says:
*During the beta/RC phase an explicit request for testing the binaries with several other libraries (SciPy/Matplotlib/Pygame) should be posted on the mailing list.* - that should cover this too

**Comment by mhvk** [comment]
I think this is specifically for the point release; for 1.14.0 it definitely was done, but 1.14.1 introduced some new bugs that could have been caught if there had been a bit more time.

**Comment by charris** [comment]
@mhvk What I meant was an issue for the bug, not the procedure :)

**Comment by mhvk** [comment]
OK, I'll make an issue for that. Feel free to close this issue!
