### ISSUE TITLE
Crash in np.ones on centos

### ISSUE THREAD

**Issue by varun-intel** [numpy/numpy#10681]
I am encountering a error in the np.ones function when I run a script on centos 7.4. The crash occurs in the following lines:
a = empty(shape, dtype, order)
multiarray.copyto(a, 1, casting='unsafe')
The error is: KeyError: 'dict'

This is the line I am executing:
self.x = np.ascontiguousarray(np.ones((1, 1), dtype=np.float32))

I do not observe the problem on other operating systems (ubuntu, mac). Is this a known issue?

**Comment by seberg** [comment]
What python and numpy version? Also can you try the `np.copyto` without anything else, as well as without the `casting` keyword. Frankly, it looks pretty strange, might there anything else be strange not directly related to NumPy?

What would make sense to me is if `dtype` is a bit special. What is `dtype` here?

**Comment by varun-intel** [comment]
I can't change any of those lines because they are inside the np.ones function. The dtype is np.float32, nothing unusual. The only line I am executing is this:

self.x = np.ascontiguousarray(np.ones((1, 1), dtype=np.float32))

**Comment by pv** [comment]
Can you answer the questions by @seberg: python version? numpy version?

**Comment by varun-intel** [comment]
Yes, python 3.4.5, numpy 1.13.1

**Comment by eric-wieser** [comment]
> I can't change any of those lines because they are inside the np.ones function

You can copy out the contents of the function, and run those by themselves :)

**Comment by mattip** [comment]
@varun-intel is this still an issue? Where did you get numpy/python?

**Comment by mattip** [comment]
Closing since we cannot reproduce. Please reopen with more information if still relevant
