### ISSUE TITLE
weights argument seems to be ignored in np.histogram

### ISSUE THREAD

**Issue by geogria** [numpy/numpy#10682]
```
>>> import numpy as np
>>> a=np.array([1,2,3,4,5,6,7,8,9,10])
>>> weights=np.array([0.8,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1])
>>> hist, bin_edges = np.histogram(a,bins=10, weights=weights)
>>> print(bin_edges)
[  1.    1.9   2.8   3.7   4.6   5.5   6.4   7.3   8.2   9.1  10. ]
>>> hist, bin_edges = np.histogram(a,bins=10)
>>> print(bin_edges)
[  1.    1.9   2.8   3.7   4.6   5.5   6.4   7.3   8.2   9.1  10. ]
```

The bin_edges calculated with and without weights are the same. It seems the weights are ignored in the bin_edges calculation.

**Comment by eric-wieser** [comment]
From the docs

> Weighted data is not supported for automated bin size selection.

**Comment by NelleV** [comment]
numpy could raise a warning when automated bin size are used with weights to inform the user that weighted data is not supported for automated bin size selection.

**Comment by domagalski** [comment]
The weights argument is not used at all for calculating bin edges. I've created a pull request #10759 to add this in.

**Comment by nayyarv** [comment]
Hmm, when you pass in 10 bins, the bin edges are literally calculated by `np.linspace(min(x), max(x), n_bins+1)`. This will never change depending on weights, since this does not change the range nor the number of bins.

What does change is the value (i.e. height) of each bin. That is affected by weights.

```python
In [4]: >>> import numpy as np
   ...: >>> a=np.array([1,2,3,4,5,6,7,8,9,10])
   ...: >>> weights=np.array([0.8,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1])
   ...: >>> hist, bin_edges = np.histogram(a,bins=10, weights=weights)
   ...: >>> print(hist)
[0.8 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
   ...: >>> hist, bin_edges = np.histogram(a,bins=10)
   ...: >>> print(hist)
[1 1 1 1 1 1 1 1 1 1]
```

And if you were to try the same with an automated method, you get a ValueError since the weights would change the estimate.
```
In [5]:  >>> hist, bin_edges = np.histogram(a,bins='auto', weights=weights)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-207ca380ce4e> in <module>()
----> 1 hist, bin_edges = np.histogram(a,bins='auto', weights=weights)

/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.pyc in histogram(a, bins, range, normed, weights, density)
    689                 "{!r} is not a valid estimator for `bins`".format(bin_name))
    690         if weights is not None:
--> 691             raise TypeError("Automated estimation of the number of "
    692                             "bins is not supported for weighted data")
    693         # Make a reference to `a`

TypeError: Automated estimation of the number of bins is not supported for weighted data
```

This is not a bug, this is a misunderstanding of how weights and bin edges interact.

**Comment by eric-wieser** [comment]
I think this can be closed, unless you think the docs can be improved, @domagalski?

**Comment by domagalski** [comment]
I agree. It can be closed.
