### ISSUE TITLE
Creating array of arrays in numpy with different dimentions

### ISSUE THREAD

**Issue by ale152** [numpy/numpy#10695]
I'm trying to create an array of numpy arrays, each one with a different dimension. So far, it seems to be fine. For example, if I run:

`np.array([np.zeros((10,3)), np.zeros((11,8))])`

the result is:

```
array([ array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]]),
       array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])], dtype=object)

```

The dimension of the two matrices are completely different and the array is generated without any problem. However, if the first dimension of the two matrices is the same, it doesn't work anymore:

```
np.array([np.zeros((10,3)), np.zeros((10,8))])

Traceback (most recent call last):

  File "<ipython-input-123-97301e1424ae>", line 1, in <module>
    a=np.array([np.zeros((10,3)), np.zeros((10,8))])

ValueError: could not broadcast input array from shape (10,3) into shape (10)
What is going on?
```

Thank you!

**Comment by seberg** [comment]
Create it with `dtype=object`, and to be even safer. Create an empty array with `dtype=object` and the correct shape and then assign the arrays you want to have inside to individual elements.

**Comment by seberg** [comment]
There are discussions about making this a bit cleaner, but they are open elsewhere already.

**Comment by google-maps-reactmartial** [comment]
https://linear-regressioninordin.github.io/kip/



I unraveled the mystery
