### ISSUE TITLE
default value for np.take(<oob>)

### ISSUE THREAD

**Issue by kodonnell** [numpy/numpy#10696]
My use case involves padding and im2col sorts of operations, and basically I'd like a way of doing `take from these indices, except when the value is -1, and then just take 0`. I.e. I'd like:

```
arr.take(-1)
```

to return `0` (or some other default value) regardless of `arr`. I understand I can do this with masks, but for me it'd be a little easier (and more efficient) as above and I imagine it'd be easy to implement as a new 'mode' to `take`. See if others think it's worthwhile.

Aside - it took me quite a while to debug some code as I thought the above was the expected behaviour for `mode='clip'`. When I tested it, my arrays happened to have `0` in the right location for it to appear to work as I expected. The docs don't seem to mention what happens with negative indices in this mode.

**Comment by jaimefrio** [comment]
Thanks for taking the time for opening this issue!

Could you be a little more specific on how do you think this should work?

`-1` is a valid index for take, so expecting it to return anything other than the last item of the indexed array is going to be a tough sell, and I personally think it would be a very bad idea. The closest to what you seem to be asking that I think could make sense is to have a `mode='default'` that would use an extra `default_value` kwarg to place it in all out of bounds indices. I'm uncertain whether something like this would see much use, but I may be wrong.

In any case, if you want to move this forward, I'd suggest that you make a more concrete proposal of the API and behavior you'd like to see, if possible with concrete examples. This may be a good place to have that discussion, but eventually, as with all API changes, it's going to have to be discussed on the wider mailing list, so feel free to write that e-mail and start that discussion when ever you think your proposal is ready.

**Comment by kodonnell** [comment]
Thanks @jaimefrio - and fair point about `-1` ... though it seems odd that behaviour changes in `mode='clip'` if it's a valid index. As below, I'd expect `a.take(-1)` to be equivalent to `a[-1]`.

```python
>>> import numpy as np
>>> a = np.arange(10)
>>> a.take(-1)
9
>>> a.take(-1, mode='clip')
0
```

This is stated in the documentation: *‘clip’ mode means that all indices that are too large are replaced by the index that addresses the last element along that axis. Note that this disables indexing with negative numbers.* However I'm not sure what's going on with `-1` then - I assume it's being treated as OOB. Anyway, somewhat a side issue, though relevant-ish to this issue.

Possibly `np.nan` could be a better solution for 'give me the default back' - but that means the index has to be a float etc., which might be fun. As a rough proposal, following your suggestion, something like when `mode='default'`, then a default value (specified as e.g. `default=0`) would be returned when the index is OOB. That's pretty simple, I think, and easy to implement. Personally, I think both `mode='clip'` and `mode='default'` could do with a separate argument specifying what to do with negative indices - as above, what does `take(-1)` do, and what if I want it to do the opposite?

I'll close this issue and leave it here for posterity - for now I'm not worried enough to start an email list etc., and as you say, it might not be worth it, given there's such a simple solution with masks.
