### ISSUE TITLE
np.loadtxt data type mismatch when used with cython ndarrays of the same np data type

### ISSUE THREAD

**Issue by firstkingofrome** [numpy/numpy#10717]
The following causes an data type mismatch, when declaring a numpy array and then populating it with 
np.loadtxt a data type mismatch occurs even if the same numpy data type deceleration is used for each (np.loadtxt tries return higher precision).

cdef np.ndarray[np.float,ndim=1] test
test = np.loadtxt(FILENAME, dtype ={'names':('lon'), 'formats': (np.float)}, unpack=True,skiprows=5)           

WorkAround:
Declaring the numpy array using the C double works but it feels super hacky, it would be nice if you could use numpy data type decelerations everywhere.

cdef np.ndarray[double,ndim=1] test
test = np.loadtxt(FILENAME, dtype ={'names':('lon'), 'formats': (float)}, unpack=True,skiprows=5)  

Thank You,

**Comment by seberg** [comment]
1. you have to cimport numpy, best with a different name, and use that
2. `np.float is float` (pythons float) not even numpy's float, while you have to use the C side of cython.

**Comment by firstkingofrome** [comment]
Thank You for the explanation, it was very helpful.
