### ISSUE TITLE
Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by rf-andrade** [numpy/numpy#10714]
I'm quite new to Python/Anaconda, and I'm facing an issue that I couldn't solve on my own or googling. 
When I'm running Python on cmd I can import and use numpy. Working fine. 

When I'm running scripts on Spyder, or just trying to import numpy on Anaconda Prompt this error message appears:
"ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray'"

I don't know if there are relations to it, but I cannot update conda, as well. When I try to update I receive Permission Errors. 

Any ideas??

**Comment by phung025** [comment]
Try reinstall numpy using this command line: `pip install --upgrade --force-reinstall numpy`

**Comment by rgommers** [comment]
@rf-andrade you're likely using 2 different Python versions, one from the command line and another one in Spyder. 

Do not mix `pip` and `conda` for installing `numpy`.

This issue is probably not relevant anymore, and certainly not a numpy bug, so I'm closing it.

**Comment by daltonwang** [comment]
> Try reinstall numpy using this command line: `pip install --upgrade --force-reinstall numpy`
It works. Thank you

**Comment by lel4866** [comment]
This worked for me as well (pip install --upgrade --force-reinstall numpy). Made both PyCharm and Visual Studio able to import and use numpy

**Comment by r002** [comment]
I just finished installing Anaconda for Python 3.7 on Windows and had received this numpy error too!  I had to run **"pip install --upgrade --force-reinstall numpy"** from the Anaconda prompt which fixed my issue as well.  Thank you for sharing this tip!  Anaconda took up something like 3GB!  It's insane to me to go through so much hassle only to have "import numpy as np" fail in my test hello.py file.  Someone from the Anaconda team (or numpy team?) should please fix this!

![image](https://user-images.githubusercontent.com/45280066/50541093-3bd99700-0b6c-11e9-9024-02ea89480478.png)

**Comment by rgommers** [comment]
Not sure what the issue was here for the last few commenters, but for anyone who ends up here: **please never install numpy with pip into a conda/anaconda install!** this will result in all sorts of pain down the line. NumPy is treated in a special way by conda, it is basically the only conda-installable package that you absolutely never should touch with pip. Reinstall with conda instead.

**Comment by amapic** [comment]
> I just finished installing Anaconda for Python 3.7 on Windows and had received this numpy error too! I had to run **"pip install --upgrade --force-reinstall numpy"** from the Anaconda prompt which fixed my issue as well. Thank you for sharing this tip! Anaconda took up something like 3GB! It's insane to me to go through so much hassle only to have "import numpy as np" fail in my test hello.py file. Someone from the Anaconda team (or numpy team?) should please fix this!
> 
> ![image](https://user-images.githubusercontent.com/45280066/50541093-3bd99700-0b6c-11e9-9024-02ea89480478.png)



> I just finished installing Anaconda for Python 3.7 on Windows and had received this numpy error too! I had to run **"pip install --upgrade --force-reinstall numpy"** from the Anaconda prompt which fixed my issue as well. Thank you for sharing this tip! Anaconda took up something like 3GB! It's insane to me to go through so much hassle only to have "import numpy as np" fail in my test hello.py file. Someone from the Anaconda team (or numpy team?) should please fix this!
> 
> ![image](https://user-images.githubusercontent.com/45280066/50541093-3bd99700-0b6c-11e9-9024-02ea89480478.png)

Hi, can you give me your version of python, opencv-python and numpy ? I don't manage to have opencv-python working.... I'm just stuck.

**Comment by amapic** [comment]
Hi aelillie,
I created a new env in python 3.7 and install numpy 1.15.4 and no problem for me. How do you know that it's not working for you ?

**Comment by amapic** [comment]
> @amapic
> 
> Apologies for my belated reply. Here are the versions I have on my system atm:
> python: 3.7.1
> opencv-python: Not installed; I don't currently use this library.
> numpy: 1.15.4
> 
> I hope this helps!

Hi,
No problem. I succeeded to do it actually. It was just a mistake in the selected env.

**Comment by aelillie** [comment]
> Hi aelillie,
> I created a new env in python 3.7 and install numpy 1.15.4 and no problem for me. How do you know that it's not working for you ?

I get this error:
![image](https://user-images.githubusercontent.com/9073236/51552871-dbd7c700-1e71-11e9-8e91-069722f7e8e9.png)

**Comment by mattip** [comment]
@aelillie Please do not continue this issue here. It is closed. Please open a new one, and specify your anaconda version, OS version, and how exactly you are starting python. Even better, file an issue with [anaconda](https://github.com/ContinuumIO/anaconda-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+multiarray+), perhaps they can help you. I will mention we have had reports of issues around the PATH environment variable, perhaps the anaconda-specific directories are not being added properly before you try to load numpy.

**Comment by amapic** [comment]
@aelillie Im ok to help you somewhere else. I lost a lot of time on this.

**Comment by bigonez** [comment]
Even with a brand new installation of Anaconda3-2018.12, I got the same issue when I start to use Python and import numpy immediately.
After append the path, C:\...\anaconda3\Library\bin, into the PATH environment variable, it works without any issues.

**Comment by shivasaxena23** [comment]
I would recommend performing **conda install -c anaconda numpy** which upgraded the previously buggy numpy.

**Comment by catrueeb** [comment]
@bigonez Is this a permanent fix? Or is it only working for the base environment. I feel like adding the environment variable path to the base environment might confuse pycharm etc. when working with other environments, no?

**Comment by muddy53** [comment]
> Try reinstall numpy using this command line: `pip install --upgrade --force-reinstall numpy`

Thank you so much!!! IT WORKED LIKE A CHARM!!

**Comment by Pacman1984** [comment]
> Try reinstall numpy using this command line: `pip install --upgrade --force-reinstall numpy`

This command helps. reinstalling numpy with pip in an conda environment makes numpy work again in vs code for me. Before i had the 1.15 conda forge version installed and it was broken (ImportError: 
Importing the multiarray numpy extension module failed.) After forced pip reinstall version 1.17 was installed and it works fine now.

**Comment by asifm** [comment]
Anyone coming here after facing the problem via R's reticulate, try @Pacman1984 solution above. It worked for my conda environment.

**Comment by peeterm007** [comment]
For what it's worth, I ran into the same issue with pip and venv. Unfortunately the above 'pip install --upgrade --force-reinstall numpy' did not help. It also did not help that I removed the whole venv and installed everything from scratch: as soon as I tried to install numpy, same error again. 

This helped: 

`/path/to/my/venv/bin/python -m pip cache purge`
