### ISSUE TITLE
format_float_positional not working as described?

### ISSUE THREAD

**Issue by uwezi** [numpy/numpy#10713]
numpy-1.14.1-cp34-none-win_amd64.whl

This was just the function I needed today, but I find that _format_float_positional_ does not appear to work as described - at least not as I understand it:

None of the following cases gives me 5 significant digits without trimming trailing zeroes, even though I would expect _trim="k"_ to treat trailing zeroes as significant digits. Also _fractional=False_ for the first line should not give me 5 decimal places after the decimal separator - should it?
 
```
print(np.format_float_positional(-324.5, precision=5, trim="k", unique=False, fractional=False))
print(np.format_float_positional(-324.5, precision=5, trim="k", unique=True, fractional=False))
print(np.format_float_positional(-324.5, precision=5, trim="k", unique=False, fractional=True))
print(np.format_float_positional(-324.5, precision=5, trim="k", unique=True, fractional=True))
```

-324.50000
-324.5
-324.50000
-324.5

**Comment by uwezi** [comment]
doing one more bit of analysis I seem to understand what is happening here:

_trim="k"_ AND _precision=n_ 

- correctly rounds of the number to _n_ significant digits in total (before plus after separator)
- always displays _n_ decimals after the separator, even if there are already _m_ digits before the decimal separator
- thus the remaining decimals after the separator are filled with zeroes, even though only _n-m_ decimals  should be displayed

**Comment by ahaldane** [comment]
Thanks for the catch, confirmed. 

I think the fix is simple, I'll put up a PR shortly, and hopefully it can get into 1.14.2

**Comment by uwezi** [comment]
happy to be helpful!
