### ISSUE TITLE
[feature request] Convert complex diagonal form to real block diagonal form

### ISSUE THREAD

**Issue by NKrvavica** [numpy/numpy#10724]
In Matlab there is a function cdf2rdf (https://www.mathworks.com/help/matlab/ref/cdf2rdf.html) which converts a complex diagonal form of eigenvalues and eigenvectors to a real diagonal form.
I didn't find the similar one in numpy, and it would be quite useful for developing numerical models that are used to solve hyperbolic systems.
Any chance this could be added in the future versions?
If not, can you recommend some alternatives and/or how to implement it myself?

**Comment by WarrenWeckesser** [comment]
FYI: @NKrvavica also [asked this on the scipy github site,](https://github.com/scipy/scipy/issues/8544) and based on the comments there, the function might end up in `scipy.linalg`.

**Comment by ilayn** [comment]
This is now in SciPy which would be available with v1.1.0 via https://github.com/scipy/scipy/pull/8550

**Comment by rgommers** [comment]
👍 closing this issue then
