### ISSUE TITLE
Multiarray numpy extension broken with GCC7 on x86/i386

### ISSUE THREAD

**Issue by AsavarTzeth** [numpy/numpy#10733]
GCC version: 7.3.0
Fortran compiler: gnu95
Python: 3.5.2
Lapack (external): 8.3.0
Numpy: 1.14.1
Architecture: x86 (32-bit / i386)

I am building my own lapack, numpy and scipy from source. However when I recently started using gcc7 there was a regression that broke my i386 builds.

Whenever numpy is imported, or in my case I try to build scipy I get these errors:

```
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: /app/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-i386-linux-gnu.so: undefined symbol: __divmoddi4
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 418, in <module>
    setup_package()
  File "setup.py", line 398, in setup_package
    from numpy.distutils.core import setup
  File "/app/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/app/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/app/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/app/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/app/lib/python3.5/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
Original error was: /app/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-i386-linux-gnu.so: undefined symbol: __divmoddi4
```

This is not reproducible if numpy is built for aarch64, arm (32-bit), or x86_64.

Based on some quick research it would appear that `__dibmoddi4()` is a new function of libgcc that is only used with 32-bit x86.

Other references:
- https://gcc.gnu.org/ml/gcc-help/2017-05/msg00108.html
- https://sourceforge.net/p/mingw-w64/mailman/message/35827726/
- https://www.illumos.org/issues/8500

**Comment by charris** [comment]
Sounds like it is linking to the wrong/bad library.  What does `nm -D <path_to_library>` show?

**Comment by njsmith** [comment]
This would happen if you're building with gcc 7, but aren't making sure that runtime, you're using gcc 7's libgcc. Maybe you need to do something with `LD_LIBRARY_PATH`? Or consider finding some way to link libgcc statically?

**Comment by AsavarTzeth** [comment]
Thank you both, those were all the clues I required. I did indeed use gcc7 but linked against libgcc6. Therefore the symbol was not available.
