### ISSUE TITLE
numpy random.seed not working

### ISSUE THREAD

**Issue by AndreiKeino** [numpy/numpy#10738]
The code:

``
import numpy as np
import random
random.seed(14)
print(np.random.rand())

``

should print the same number every time it run, isnt't it? 

But it prints:

0.5371892444512011

0.9847269979401458

0.6225177674856823

0.38136659300204057

**Comment by rkern** [comment]
No, `random` is a different module from `numpy.random`.

**Comment by AndreiKeino** [comment]
Thank you.
