### ISSUE TITLE
a.size and np.prod(a.shape) are not equivalent

### ISSUE THREAD

**Issue by jonasrauber** [numpy/numpy#10747]
The documentation of `ndarray.size` claims that `a.size` is equivalent to `np.prod(a.shape)`. While they do return the same value, they return different types and therefore are not equivalent.

```python
a = np.zeros((2, 2))

type(a.size)
# returns <class 'int'>

type(np.prod(a.shape))
# returns <class 'numpy.int64'>
```

Continuing the calculations using `np.prod(a.shape)` can therefore lead to integer overflows.

I guess `np.prod(a.shape)` cannot be changed to return a `<class 'int'>` instance, and `a.size` should certainly not be changed to return a `<class 'numpy.int64'>` instance, so probably the only solution is to update the documentation to reflect that these two are not fully equivalent.

I'd be happy to make pull-request to update the documentation accordingly.

**Comment by seberg** [comment]
I somewhat doubt that replacing "equivalent" with "equal" will actually help much, but seems like a small documentation improvement, so sounds good. Can you create a quick PR for it?

**Comment by seberg** [comment]
Maybe to be clear, the only difference between the two is that `np.prod` effectively calls `np.asarray` on the tuple and that converts the integer to non-python type.

**Comment by jonasrauber** [comment]
@seberg I don't think replacing _equivalent_ with _equal_ is sufficient. Instead, the documentation should explicitly state the difference explicitly.

**Comment by seberg** [comment]
Fair point, just suggest a change in the docs!
