### ISSUE TITLE
Doc error: Author name wrong in reference to book

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#10751]
At https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html#numpy.outer (and probably other places),

> G. H. Golub and C. F. van Loan, Matrix Computations, 3rd ed., Baltimore, MD, Johns Hopkins University Press, 1996

should be

G. H. Golub and C. F. Van Loan, Matrix Computations, 3rd ed., Baltimore, MD, Johns Hopkins University Press, 1996

**Comment by eric-wieser** [comment]
I'm surprised that a reference is needed at all for an outer product, but I guess it does no harm. Introduced in 094a81e1352fb6b3a7a614fc8df23d0080cf7cb5, FWIW.

**Comment by ChloeColeongco** [comment]
Hi, I'm very very very new to contributing to open source, so I might be missing the issue entirely. But I made a pull request for this fixing the author name in the document linked by @eric-wieser so now it should look like this:
![image](https://user-images.githubusercontent.com/30606327/37790573-8f6bb5a2-2dcc-11e8-814e-f9a495dc0fa5.png)
Is that what is needed for this? Thank you.

**Comment by eric-wieser** [comment]
At risk of falling into [one of these traps](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) and telling people how to spell their own name - apparently [van should be lowercase in dutch](https://www.dutchgenealogy.nl/how-to-capitalize-dutch-names-with-prefixes/)

**Comment by ChloeColeongco** [comment]
Wait, so it was already correct? @eric-wieser

**Comment by keithbriggs** [comment]
Yes, and if Van Loan were Dutch, this would be relevant.

K

________________________________________

**Comment by keithbriggs** [comment]
No.

http://www.cs.cornell.edu/cv/


________________________________________

**Comment by charris** [comment]
Closed by #10785.
