### ISSUE TITLE
promote_types doesn't respect endianness

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#10767]
Appears that `promote_types` does not respect endianness and will convert two matching types of the same endian to little endian. Example included below along with the `conda` environment used to reproduce this issue.

<details>
<summary>Example:</summary>

```python
In [1]: import numpy as np

In [2]: np.promote_types('>f8', '>f8').str
Out[2]: '<f8'
```

</details>

<br>

<details>
<summary>Environment:</summary>

```yaml
name: test
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36_0
- blas=1.1=openblas
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- decorator=4.2.1=py36_0
- ipython=6.2.1=py36_1
- ipython_genutils=0.2.0=py36_0
- jedi=0.11.1=py36_0
- libgfortran=3.0.0=0
- ncurses=5.9=10
- numpy=1.14.2=py36_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- parso=0.1.1=py_0
- pexpect=4.4.0=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.2=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- python=3.6.4=0
- readline=7.0=0
- setuptools=39.0.1=py36_0
- simplegeneric=0.8.1=py36_0
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- tk=8.6.7=0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.30.0=py36_2
- xz=5.2.3=0
- zlib=1.2.11=0
```

</details>

**Comment by jakirkham** [comment]
Copied from [the docs]( https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.promote_types.html#numpy.promote_types ).

> The returned data type is always in native byte order.

That said, it seems [native byte order is determined at compile time]( https://github.com/numpy/numpy/blob/v1.14.2/numpy/core/include/numpy/ndarraytypes.h#L1719-L1725 ). In the era of binary packages `wheel`, `conda`, etc. this seems like a less reliable indicator of what the user would expect. Perhaps a run time check would improve the situation. Thoughts?

**Comment by seberg** [comment]
At this point, I think dtype promotion returning canonical/native byte order is intended (and better for most users, as non-native byteorder is tricky).

Packaging shouldn't be a problem.  AFAIK, you will need different wheels for platforms with different byte-order anyway.

**Comment by jakirkham** [comment]
To clarify the packaging point, cross compilation is often used for more exotic platforms that may not be present on CI. So checking the build time systems endianness would be incorrect in this case

**Comment by seberg** [comment]
Ah OK, we use:
```
    #if defined(NPY_HAVE_ENDIAN_H)
    #include <endian.h>
    #elif defined(NPY_HAVE_SYS_ENDIAN_H)
    #include <sys/endian.h>
    #endif
```
or via target CPU macros like `__x86_64__`.  If those don't work with cross compilation, I can reopen and rephrase the title a bit.
