### ISSUE TITLE
taking derivative of a polynomial using poly1d polyder without reversing the coefficients

### ISSUE THREAD

**Issue by GileadMoshe** [numpy/numpy#10762]
I'm using poly1d and polyder to return the derivative of a simple polynomial.

       3     2
    1 x + 1 x + 1 x + 1
    

I'm seeing the simple combination of the two commands doesn't doesn't use the coefficients in the correct order.

    print(np.poly1d(P.polyder(c)))

Is there a one liner that I can use like this

    print(np.poly1d(P.polyder(c)))

so that the coefficients like above are in the correct order?

Below is my code and output:
    
    import numpy as np
    from numpy.polynomial import polynomial as P
    
    print("")
    
    c = (1, 1, 1, 1)
    
    print("the array of coefficients for the polynomial")
    print(c)
    
    print("")
    
    print("polynomial with coefficients and exponents")
    print(np.poly1d(c))
    
    print("")
    
    print("array of coefficients of derivative of polynomial: lowest order coming first in the array")
    d_c = P.polyder(c)
    print(d_c)
    
    print("")
    
    print("reversing the array of coefficients for the derivative of the polynomial")
    d_c = d_c[::-1]
    print(d_c)
    
    print("")
    
    print("printing the derivative of the polynomial with exponents and coefficients")
    print(np.poly1d(d_c))
    
    print("")
    
    print("printing the derivative of the polynomial without reversing the coefficient array after derivation")
    print(np.poly1d(P.polyder(c)))
    
    print("")

Output:

    the array of coefficients for the polynomial
    (1, 1, 1, 1)
    
    polynomial with coefficients and exponents
       3     2
    1 x + 1 x + 1 x + 1
    
    array of coefficients of derivative of polynomial: lowest order coming first in the array
    [ 1.  2.  3.]
    
    reversing the array of coefficients for the derivative of the polynomial
    [ 3.  2.  1.]
    
    printing the derivative of the polynomial with exponents and coefficients
       2
    3 x + 2 x + 1
    
    printing the derivative of the polynomial without reversing the coefficient array after derivation
       2
    1 x + 2 x + 3

**Comment by eric-wieser** [comment]
`np.poly1d` (semi-deprecated) and `np.polynomial` are incompatible. You should use `np.polynomial` for everything

**Comment by eric-wieser** [comment]
You want either:
```python
>>> c = [1, 1, 1, 1]
>>> p = np.poly1d(c)
>>> p
poly1d([1, 1, 1, 1])
>>> p.deriv()
poly1d([3, 2, 1])
>>> np.polyder(p)   # NOT np.polynomial.polynomial.polyder
poly1d([3, 2, 1])
```
or using the new API:
```
>>> from numpy.polynomial import Polynomial
>>> c = [1, 1, 1, 1]
>>> p = Polynomial(c)
>>> p
Polynomial([1., 1., 1., 1.], [-1, 1], [-1, 1])
>>> p.deriv()
Polynomial([1., 2., 3], [-1, 1], [-1, 1])
```
