### ISSUE TITLE
BUG: np.matmul fails on np.matrix of integers

### ISSUE THREAD

**Issue by Han-He** [numpy/numpy#10764]
```python
>>> a = np.matrix([[1,1],[1,2]])
>>> a
matrix([[1, 1],
        [1, 2]])
>>> b = np.array([1,2])
>>> b
array([1, 2])
>>> np.matmul(a,b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Iterator automatic output has an array subtype which changed the dimensions of the output
>>> a = a.astype(np.float64)
>>> a
matrix([[ 1.,  1.],
        [ 1.,  2.]])
>>> np.matmul(a,b)
matrix([[ 3.,  5.]])
```
When a.dtype is np.int32, we cannot do np.matmul on a and b. But after changing the data type to np.float64, it works.
Anyone know why is that?

**Comment by eric-wieser** [comment]
That's a bizarre error. It might be due to you using `np.matrix`, which you should really avoid. `np.array` works just fine for 2d arrays, especially if you're using `matmul`

**Comment by charris** [comment]
Yeah, matrix reshapes arrays to always have 2 dimensions. The point of the new `@` (matmul) operator in Python 3.5 is to avoid using matrices, which we are going to get rid when we can.

**Comment by eric-wieser** [comment]
Still very strange that this only happens for integers

**Comment by charris** [comment]
The implementation uses einsum whenever CBLAS cannot be used, i.e., stacks and non-inexact types. We should probably fix that for at least stacks of inexact types.

**Comment by mattip** [comment]
now that matmul is a ufunc, this works
```
>>> a = np.matrix([[1,1],[1,2]])
>>> b = np.array([1,2])
>>> np.matmul(a,b)
matrix([[3, 5]])
```
