### ISSUE TITLE
Add an alias 'stable' for 'mergesort' in sort

### ISSUE THREAD

**Issue by lakshayg** [numpy/numpy#10784]
Currently, numpy supports only one way of performing a stable sort i.e. mergesort. Therefore, it makes sense to add an alias for mergesort which will help in making the code more readable.

When I see 'mergesort' written in the code, it is not explicit that this was done to make the sort stable. Therefore having a 'stable' option will fit well with the idea "explicit is better than implicit".

I would like to give this a try if this issue makes sense and the devs decide to accept this proposal.

**Comment by charris** [comment]
Seems reasonable to me.

**Comment by jaimefrio** [comment]
I think this is a great idea, as long as we don't document it as specifically being an alias for mergesort, but as providing a default stable sorting algorithm: that way if we one day implement, say count sort for `uint8`, we can make stable point to that algorithm for that dtype.

I also think it may be a good idea to have a 'default' or 'fastest' label that points to 'quicksort' but that could be replaced by something else if we ever implement it.

**Comment by eric-wieser** [comment]
I'd say you should go ahead and implement it.

Doing the same for `partition` might be nice too

**Comment by lakshayg** [comment]
I have sent a PR but I am getting a segfault on running the tests and not sure where the issue is. Any help will be appreciated.
