### ISSUE TITLE
np.einsum unexpected behavior for double trace on tensors

### ISSUE THREAD

**Issue by mfdgroot** [numpy/numpy#10792]
I run into this error being thrown when doing double summation on tensors with legs with different dimensions.
It looks a lot like #5147 which was solved previously.
This is a minimal example (dimensions and array values are unimportant to the problem):
```
a=np.arange(4).reshape(1,1,2,1,2)
np.einsum('bbcdc->d,a)
```
returns
```ValueError: dimensions in operand 0 for collapsing index 'd' don't match (1 != 2)```.

Summing `b` and `c` separately works as do the following examples:
```
a=np.arange(4).reshape(1,1,2,2,1)
np.einsum('bbccd->d,a)

a=np.arange(8).reshape(1,1,2,2,2)
np.eisum('bbcdc->d,a)
```

**Comment by eric-wieser** [comment]
Yet succeeds if the order is reversed:
```
np.einsum('cdcbb->d', a.T)
```

**Comment by mfdgroot** [comment]
The triple trace
```
a=np.arange(4).reshape(1,1,1,1,2,1,2)
np.einsum('eebbcdc->d',a)
```
works as well.
