### ISSUE TITLE
Surprising np.random.choice semantics due to unexpected casting to ndarray

### ISSUE THREAD

**Issue by estansifer** [numpy/numpy#10791]
I am opening this issue to discuss the desired semantics of np.random.choice, with reference to some previous issues that have brought up portions of the below. (I'm not sure if this is the most appropriate place for this type of discussion, so feel free to direct me elsewhere.)

When "xs" is a python list, the semantics of "np.random.choice(xs)" depends on the types and values of the elements of xs, which is surprising because python's analogous "random.choice(xs)" does not, and because one would not expect choosing a random element from a list to depend on what the elements are. (This was mentioned in a comment on issue #8305.)

One specific case of this was mentioned in issue #7810; namely, when xs is multidimensional and each of its elements can be broadcast to the same shape, e.g. xs = [[1, 2], [3, 4]].

The proposal in that issue is to add an optional "axis" argument, with "axis=0" giving the desired behavior. However, this would not resolve the surprises I ran into below even when xs is one-dimensional.

With "xs = [1, 2]", the 1 is cast to a numpy.int64 (this led to a bug in my code).
With "xs = [1, 2.5]", the 1 is cast to a numpy.float64.
With "xs = [10 ** 100 + 1, 2.5]", the large integer remains a python int, despite what I expected from the previous example.
With "xs = [1, [2, 3]]", the 1 remains a python int.

These casts (or lack thereof) occur because np.random.choice starts by creating an ndarray out of its argument, which I did not expect to happen as the function shouldn't need to inspect the elements of xs.

My first suggested solution would be to, instead of the cast "a = np.array(a, copy = True)" at the beginning of np.random.choice, convert "a" to a 1D array with dtype='O'. I believe this would fix #7810, without the need for an axis argument, as well as the surprises I ran into above. Unfortunately "a = np.fromiter(a, dtype = 'O')" does not accomplish this as np.fromiter cannot be used with the 'O' dtype (??), so an explicit python loop would probably be necessary for this approach (or the use of some function I am unaware of).

Alternatively, and preferably, it is possible to delay the numpy array creation until the end (where it is only needed if "size" is given), but this would require modifying some of the error-checking which I didn't understand.

Either of the above solutions with fix the problem that led to #7810 but would be incompatible with the axis keyword being added (which only matters if axis > 0 is actually useful for anything).

It is not clear to me what the most obvious behavior of np.random.choice should be when the "size" argument is given. If size is a tuple it is clear the user is expecting an ndarray in response, but the dtype is not clear, e.g., if np.random.choice([1, 2.5], size = (2, 2)) returns [[1, 1], [1, 1]].

Finally, it is possible that the best solution is that np.random.choice should only work predictably on inputs of consistent types and shapes. If this is the intended solution, then the above behavior I described as "surprising" should instead be more clearly documented, with the documentation pointing the user towards the use of python's random.choice for cases where the input has an unusual shape or mixed types.

**Comment by hameerabbasi** [comment]
This can (maybe?) be fixed with something like:

```
idx = np.random.choice(len(xs))
item = xs[idx]
```

I'm not sure whether putting this into the code for `np.random.choice` is desirable, though.

**Comment by estansifer** [comment]
That's a clean work-around and I think comes out to be similar to my second suggestion in the post once you make suitable changes so that it works with the size parameter.

Looking at the source again, I think I could make the necessary changes. It amounts more-or-less to retaining the existing semantics when the "size" argument is given (except with #7810 fixed), and doing the obviously right thing when "size" is not specified. There will still be weird behavior when mixed-type python lists are used with the "size" argument but that is unavoidable.

**Comment by mattip** [comment]
Closing, `np.random.Generator().choice` now has an `axis=0` kwarg
