### ISSUE TITLE
DOC: link to tox in development_environment.rst

### ISSUE THREAD

**Issue by pvanmulbregt** [numpy/numpy#10806]
numpy/doc/source/dev/development_environment.rst contains a reference to tox

    Running tests with `tox`_ is also supported.

    .. _tox: http://tox.testrun.org:

Is this still a valid destination URL?  It appears to resolve to https://tox.testrun.org/ at 94.130.231.157 which Chrome claims is insecure, and shows a page offering professional commercial services for tox and pytest.
I wonder if perhaps the name `tox.testrun.org` expired in the 3 years since the URL was inserted in the document, or the tox project moved its location.
Documentation for tox is available at https://tox.readthedocs.io/en/latest/.  Perhaps this would be a more useful destination?

**Comment by rgommers** [comment]
Fixed in gh-10807, closing.

@pvanmulbregt for next time: if you put in your commit message "Closes gh-xxxxx" then the issue will be closed automatically when the PR is merged.
