### ISSUE TITLE
Possible silent overflow in PyArray_PyIntAsIntp_ErrMsg

### ISSUE THREAD

**Issue by zhangyangyu** [numpy/numpy#10804]
It seems https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/conversion_utils.c#L830 could lead to silent overflow when `NPY_SIZEOF_LONG > NPY_SIZEOF_INTP` or `NPY_SIZEOF_LONGLONG > NPY_SIZEOF_INTP`. Otherwise, maybe https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/conversion_utils.c#L830 doesn't have to go through `overflow_check`.

**Comment by seberg** [comment]
Closing, the condition mentioned seems impossible to occur, I am sure if such a system ever exists (if even plausible), more things would break loudly.
