### ISSUE TITLE
Using the += <negatve integer> with arrays of dtype uint8 errors, even when the subtraction will not produce a negative value in the array

### ISSUE THREAD

**Issue by gmonkman** [numpy/numpy#10808]
Title self explanatory.

Code to reproduce.
```
>>> a = _np.array([10], dtype='uint8')
>>> a += -1
```

Traceback (most recent call last):
  File "<debug input>", line 1, in <module>
TypeError: Cannot cast ufunc add output from dtype('int16') to dtype('uint8') with casting rule 'same_kind'

**Comment by charris** [comment]
It's a feature, you cannot add two different types in place unless you force it. There are two ways around it:
```
In [1]: a = np.array([10], dtype='uint8')

In [2]: a += uint8(-1); a
Out[2]: array([9], dtype=uint8)

In [3]: np.add(a, -1, out=a, casting='unsafe'); a
Out[3]: array([8], dtype=uint8)
```
or just do `a -= `.
