### ISSUE TITLE
Inconsistent behaviour of squeeze when array has 1 and more than 1 items

### ISSUE THREAD

**Issue by lnshi** [numpy/numpy#10819]
Refer to the below test cases I did:

    [leonard@Leonard's MacBook Pro ~/projects/staging]$ python
    Python 3.5.4 (default, Feb 14 2018, 17:54:42)
    [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import numpy as np
    >>> t = np.squeeze([1])
    >>> t
    array(1)
    >>> t[0]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IndexError: too many indices for array
    >>> r = np.squeeze([[1]])
    >>> r
    array(1)
    >>> r[0]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IndexError: too many indices for array
    >>> m = np.squeeze([1,2])
    >>> m
    array([1, 2])
    >>> m[0]
    1
    >>> n = np.squeeze([[1,2]])
    >>> n
    array([1, 2])
    >>> n[0]
    1
    >>>

**Comment by eric-wieser** [comment]
This is by design. `squeeze` removes all axes of length 1.

If you want to squeeze along only the first axis, use `.squeeze(axis=0)`

**Comment by lnshi** [comment]
@eric-wieser  May i ask what is the considerations behind this design? Just fell this a bad design...

**Comment by eric-wieser** [comment]
I don't think `squeeze()` existing at all is a particularly good design - if we designed it again, either it would have to:
* pick an axis by default (like `stack`) - the choice is not obvious
* pick all the axes by default (like `sum`) - this is not at all useful, and just becomes `.item()`
* be what it currently is
* not exist

In constrast, I think `.squeeze(axis=...)` is a good design, as it resolves all ambiguity
