### ISSUE TITLE
No exception set while conversion failure in PyArray_IntpConverter

### ISSUE THREAD

**Issue by zhangyangyu** [numpy/numpy#10813]
In https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/conversion_utils.c#L131, under the condition `nd != len`, there is no exception set. Python requires the converter to set an exception when failure.

**Comment by seberg** [comment]
Unless the previous function (`PyArray_IntpFromIndexSequence `) already set an exception, which should be the case here, no?

**Comment by zhangyangyu** [comment]
Yeah, the problem is when `PyArray_IntpFromIndexSequence` returns not `-1`, it does not set an exception. Please check the code, it only sets an exception when returning `-1`.

**Comment by eric-wieser** [comment]
What happens if I make an object that returns a different length each time?

**Comment by seberg** [comment]
I doubt this was ever an issue, but even if, the code changed in the meantime and it should be fixed.
