### ISSUE TITLE
Replacement for numpy.core.umath_tests.inner1d?

### ISSUE THREAD

**Issue by lesteve** [numpy/numpy#10815]
The scikit-learn Travis build using the numpy dev wheel started failing two days ago with the error (see for example this [one](https://travis-ci.org/scikit-learn/scikit-learn/builds/358788542#L2020)):

```
from numpy.core.umath_tests import inner1d
ModuleNotFoundError: No module named 'numpy.core.umath_tests'
```

This is due to https://github.com/numpy/numpy/commit/fbb29df68bd7f330d5a5ced2c20e9244f12f9648#diff-33315af1a22893e97676ee134db5ce1c which renamed compiled modules in numpy.core. 

IIUC inner1d was kind of private and we were not meant to use it. What would you suggest is a good replacement for `inner1d(arr1, arr2)`? I found that `np.einsum(...i, ..i, arr1, arr2)` seemed to be doing something close in our uses cases (arr1 is of shape (p,) and arr2 of shape (n, p) in all our tests) but maybe there is a better replacement?

**Comment by jaimefrio** [comment]
If that's all the broadcasting you need, I think `np.dot(arr2, arr1)` would be the better alternative, as you may get parallelization from the BLAS library. `np.einsum` may use SIMD if possible, so it is likely also faster than `inner1d`, and may come  up on top of `np.dot` if it can avoid making copies of the arrays.

**Comment by lesteve** [comment]
> I think np.dot(arr2, arr1) would be the better alternative

Good point, I did not think of that! Thanks a lot for the details!

**Comment by lesteve** [comment]
Actually, sometimes we have both `arr1` and `arr2` of the same shape i.e. `(n, p)` so I guess np.einsum is the only solution.
