### ISSUE TITLE
np.clip fails to clip to upper bound

### ISSUE THREAD

**Issue by cmollen** [numpy/numpy#10816]
When setting `a_max` to `1 - 1e-15`, the value is clipped to `1.0` and not `0.999999999999999`.

I'm not sure if this is a floating point representation issue or a NumPy bug, but simply printing the `a_max`  argument does not yield the same result as the clipped value.

```python
a_max = 1 - 1e-15
print(a_max)
>>> 0.999999999999999

print(np.clip([0, 1, 2], a_min=1e-15, a_max=a_max))
>>> [  1.00000000e-15   1.00000000e+00   1.00000000e+00]

print(min(a_max, 1))
>>> 0.999999999999999
```

I stumbled upon this as sklearn's `log_loss` metric function clips the probabilities between [eps, 1-eps], with the default epsilon set to 1e-15. 

I'm using Python 3.6 with NumPy 1.13.1+mkl on Windows 10 64bit.

**Comment by matthew-brett** [comment]
Could it be a floating point printing issue?

```
In [1]: import numpy as np 

In [2]: a_max = 1 - 1e-15

In [3]: print(a_max)
0.999999999999999

In [4]: clipped = np.clip([0, 1, 2], a_min=1e-15, a_max=a_max)

In [5]: print(clipped)
[1.e-15 1.e+00 1.e+00]

In [6]: print(clipped.max())
0.999999999999999
```

**Comment by cmollen** [comment]
It looks like it @matthew-brett, even though I'm not able to reproduce your output. But represented as an integer ratio it is clearly not 1.0.

```python
import numpy as np 
a_max = 1 - 1e-15
print(a_max)
>>> 0.999999999999999

clipped = np.clip([0, 1, 2], a_min=1e-15, a_max=a_max)
print(clipped)
>>> [  1.00000000e-15   1.00000000e+00   1.00000000e+00]

print(clipped.max())
>>> 1.0

print(float(clipped.max()).as_integer_ratio())
>>> (9007199254740983, 9007199254740992)

```

**Comment by ahaldane** [comment]
Your issue boils down  the fact that when printing an array, numpy only prints 8 digits of precision, so 0.999999999999999 prints as 1.000000. If you print the value on its own numpy prints more digits.
```
>>> np.__version__
'1.13.3'
>>> np.clip([0, 1, 2], a_min=1e-15, a_max=a_max)
[  1.00000000e-15   1.00000000e+00   1.00000000e+00]
>>> np.clip([0, 1, 2], a_min=1e-15, a_max=a_max)[-1]
0.999999999999999
>>> np.set_printoptions(precision=16)
>>> print(np.clip([0, 1, 2], a_min=1e-15, a_max=a_max))
[  1.0000000000000001e-15   9.9999999999999900e-01   9.9999999999999900e-01]
```

You get different output from @matthew-brett because you are using an older numpy. Printing was improved in 1.14.

If you upgrade to numpy 1.14, there are some nice new features, such as "unique" printing, which will print just the right number of digits to get a uniquely specified value:
```python
>>> np.__version__
'1.14.2'
>>> np.set_printoptions(floatmode='unique')
>>> print(np.clip([0, 1, 2], a_min=1e-15, a_max=a_max))
[1.00000000000000e-15 9.99999999999999e-01 9.99999999999999e-01]
```

Note also that there are some minor related bugs that will be fixed in numpy 1.14.3, see #10763.

**Comment by GalAvineri** [comment]
I encountered this issue as well in version 1.16 and I believe I found a minimal example that shows it.

```python
>>> import numpy as np
>>> np.__version__
'1.16.3'

>>> eps = 1e-15
>>> a = np.array(1)
>>> a_clipped = np.clip(a, eps, 1 - eps)
>>> print(a_clipped) 
0.999999999999999

>>> b = np.array(1, dtype=np.float32)  # Note the dtype specification 
>>> b_clipped = np.clip(b , eps, 1 - eps)
>>> print(b_clipped)
1.0
```

The dtype of a is set as int64, and the clipping is successful.
If I set the dtype to be float32 the clipping fails

**Comment by seberg** [comment]
@GalAvineri as noted in the previous comment, the datatype you are using is `np.float32`, so the input the function is implicitly cast to:
```
b_clipped = np.clip(b , np.float32(eps), np.float32(1 - eps))
```
which is the same as:
```
b_clipped = np.clip(b , 0, 1)
```
So this should be expected, and while I cannot fully rule out it may change at some point, you should expect such things. There are some issues with deciding what the correct data type is here, but as long as the results datatype `b_clipped.dtype` is a float32, this is expected.

**Comment by GalAvineri** [comment]
I see. So using higher precision should solve the issue than :)
Thank you!
