### ISSUE TITLE
[Feature Request] Add support for duplication matrix, elimination matrix and 

### ISSUE THREAD

**Issue by TheShadow29** [numpy/numpy#10817]
Here is the wiki article for them [Duplication and Elimination Matrices](https://en.wikipedia.org/wiki/Duplication_and_elimination_matrices). It would be nice to have direct functions for them. 

Given a square matrix A of size n x n, duplication matrix D and elimination matrix E will satisfy:
`D vech(A) = vec(A)` and `E vec(A)  = vech(A)`.

The original paper which introduces [duplication matrix](https://epubs.siam.org/doi/pdf/10.1137/0601049)

**Comment by shoyer** [comment]
These matrices are sparse, so they would probably be a more appropriate fit for `scipy.sparse` than NumPy.

**Comment by TheShadow29** [comment]
@shoyer you are correct. Sorry I didn't think of that. Should I open a new issue at scipy?

**Comment by shoyer** [comment]
Yes, that would be a better place to discuss this.
