### ISSUE TITLE
ImportError: Missing required dependencies ['numpy']

### ISSUE THREAD

**Issue by JP-Noble** [numpy/numpy#10811]
I have been searching all over the place but I don't seem to be able to find the answer.

I  am very new to python (Assume that I know absolutely nothing) and someone has created a module for us to extract data for a project. However when I attempt to run it I get the error in the title:
***********************************************************************************************
C:\Anaconda3\python.exe I:/Python/Modules/OVSurvey/ExtractRunner.py
Traceback (most recent call last):
  File "I:/Python/Modules/OVSurvey/ExtractRunner.py", line 18, in <module>
    import pandas as pd
  File "C:\Anaconda3\lib\site-packages\pandas\__init__.py", line 18, in <module>
    raise ImportError("Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

Process finished with exit code 1
***********************************************************************************************
I have tried doing the below steps in the command prompt:

conda update conda
conda update -y --all
conda install numpy
conda uninstall pandas
conda uninstall numpy
conda install pandas
conda install numpy

It seems to have left me with these versions:
Python 3.4.1
Pandas: 0.19.2-np111py34_1
numpy: 1.11.3-py34_0

Any help will be greatly appreciated

**Comment by pv** [comment]
This is not a bug report to numpy. You can ask general questions of
this type e.g. on stackoverflow.com or on mailing lists.

**Comment by JP-Noble** [comment]
OK thanks
