### ISSUE TITLE
datetime64 cannot parse dates starting with a positive sign

### ISSUE THREAD

**Issue by javidcf** [numpy/numpy#10810]
[ISO 8601 allows you to put a sign before the year](https://en.wikipedia.org/wiki/ISO_8601#Years) in order to be able to represent BC dates. NumPy handles BC dates nicely:

    import numpy as np
    np.datetime64('-1000-01-01T00:00:00Z')  # No error

However, when giving an AC date starting with a `+` sign it fails:

    import numpy as np
    np.datetime64('+1000-01-01T00:00:00Z')  # ValueError

Python 3.6.3 | Anaconda
NumPy 1.13.3
Windows 10 x64

**Comment by shoyer** [comment]
Yes, this would be nice to support. I think this would be a pretty easy fix, around these lines in `datetime_strings.c`:
https://github.com/numpy/numpy/blob/bea761424753c0612a65a6a91d44f9a81bdc4c12/numpy/core/src/multiarray/datetime_strings.c#L376=L397

(It would also need a unit test, somewhere in `numpy/core/tests/test_datetime.py`)
