### ISSUE TITLE
Testing guideline page is obsolete and not built in main docs

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#10821]
As per @rgommers's advice, I am moving scipy/scipy#8606 to here.

The numpy testing guideline does not appear to be built with the other docs. It renders adequately on GitHub (https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt), but seems out of place.

This is noticeable in particular because the scipy docs link to the GitHub page. The section on unit tests under the "Contributing New Code" section of the "Contributing to SciPy" page (http://scipy.github.io/devdocs/hacking.html#contributing-new-code) has a link to the "testing guidelines", which points here.

Given that this page (probably among others) is important enough to link across projects, it would probably be a good idea to include it in the generated docs.

On top of the fact that the page is missing, it still refers to the old `nose` testing setup, and should probably be updated to include the switchover to `py.test`.

**Comment by mattip** [comment]
It would seem that document should be rewritten as part of the pytest refactor #10856 ?

**Comment by madphysicist** [comment]
@mattip Good call. I've added that to the title and description.

**Comment by charris** [comment]
@mattip I made a start on that a couple of weeks ago and ended up pretty much deleting the whole file. What it needs is a good link to a pytest tutorial. My impression is that there is a *lot* of pytest documentation, but it tends to be a big collection of examples rather than an organized tutorial and isn't that good for teaching. Does anyone know of a good pytest tutorial?

**Comment by madphysicist** [comment]
@charris Not sure if this is what you are looking for, but I particularly like http://pythontesting.net/framework/pytest/pytest-introduction/. I got it from https://docs.pytest.org/en/latest/talks.html. If you do decide to rewrite this page, could you add in a section for running the tests using `runtests.py` in the root `numpy` directory? Assuming of course that that is still the recommended way of doing it.

**Comment by mattip** [comment]
There is the [official documentation](https://docs.pytest.org/en/latest/contents.html), [how to run it](https://docs.pytest.org/en/latest/usage.html) and a [list of resources](https://docs.pytest.org/en/latest/talks.html) but most of those are videos which personally I find difficult to learn from.

It kind of depends what level user you are looking to teach.

I have used [this tutorial](https://semaphoreci.com/community/tutorials/testing-python-applications-with-pytest) for teaching absolute beginners about testing.

If you want to summarize the pytest documentation, I would proceed by describing [building NumPy](https://docs.pytest.org/en/latest/existingtestsuite.html) for testing, running pytest from [command line](https://docs.pytest.org/en/latest/usage.html), and then [writing asserts](https://docs.pytest.org/en/latest/assert.html) in tests, although the pytest best parctices are much different than the testing utililites that have grown up around NumPy.

**Comment by charris** [comment]
@mattip  I think there are three main methods of testing:

* `runtests.py` (preferred for development)
* `import numpy; numpy.test()` for distributions, wheels
* `pytest` cli(python setup.py develop ?)

I don't use the last myself, but I think it is the main mode for some. Note that we cannot use a simple `pytest numpy` because of the way the test directories are laid out. Apart from that, I think there are just a few markers that we should mention

* `skip`
* `skipif`
* `slow`
* `xfail`

But rather than go into details about those, I'd rather link to pytest documentation. The current documentation is almost an introduction to unit testing with nose and covers the previous NumPy framework built on that. I don't think we need the equivalent with pytest, which looks to have much more documentation and a wider community for help than nose ever did. My first impulse was to just cover `runtests.py` and link to some pytest documentation, but that may be a bit too short.

**Comment by charris** [comment]
BTW, If someone more familiar with pytest than me would like to revise that documentation, please speak up ;)

**Comment by stefanv** [comment]
I imagine calling `pytest` directly will be very common, and is what newcomers
to the project will try first.

**Comment by madphysicist** [comment]
@charris, even just a detailed set of instructions for `runtests.py` would be highly appreciated. It would give beginners at least some place to start. Ignoring `np.test()` for the time being, it's the method that needs to be documented the most.

I'm not too familiar with `pytest`, so even coming back after not doing any  development for a year or so was confusing. What confused me the most is that I could no longer run with `runtests.py -t filename:testname`. Some instructions and documentation on the options would be great.

**Comment by charris** [comment]
@stephan Unfortunately, it doesn't work. If we had a separate top level package that contained all the tests -- which pytest recommends -- we could do it. As is, you need to do `pytest numpy`, which tries to import numpy from the numpy repository, giving an error unless numpy has been installed in develop mode. If you cd to somewhere else, it will run on installed numpy and the `pytest.ini` file will be missing so it won't run in develop mode. In the final analysis, the only recommended way to test for development is with runtests, which is really not a bad option. In any case, that needs to be emphasized.

**Comment by stefanv** [comment]
Good to know; thanks for the clarification.

**Comment by madphysicist** [comment]
@charris. While not disagreeing with your analysis in any way, isn't it possible to specify a custom ini file when running from an outside directory?

**Comment by mattip** [comment]
Just to be clear, I am an advocate of `git clean -xfd; pip install -e . --upgrade ; pytest -m "not slow"` for running tests in place, which works today. We should tweak our `conftests.py` so the slow tests are not run by default. IMO maintaining a `runtests.py` is a burden and can get in the way of the testing tool's progress over time.

Pandas made the move to pytest recently, but their [documentation](https://github.com/pandas-dev/pandas/wiki/Testing) still mentions nose testing. Maybe we could learn from their [conftest.py](https://github.com/pandas-dev/pandas/blob/master/pandas/conftest.py) and some of the pull requests [marked with `Testing` and pytest](https://github.com/pandas-dev/pandas/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3ATesting+pytest+)

**Comment by madphysicist** [comment]
@mattip I was not aware that `pip install -e . --upgrade` did the install in-place. Thanks for pointing that out. Definitely something to put in the docs.

**Comment by pv** [comment]
pip install -e pretty much requires virtualenv, otherwise it you'll
mess up your production environment.
