### ISSUE TITLE
numpy.repeat and numpy.tile don't work at all

### ISSUE THREAD

**Issue by bigdeeer** [numpy/numpy#10837]
Hello guys!
  I am using windows 10 home edition, python 3.6, Anaconda, and PyCharm as IDE.
After I entered the code below:

import numpy as np
a = np.array([1])
np.tile(a, 5)
print(a)
b = np.array([2])
np.repeat(a, 5)
print(b)

It showed me the result as:
[1]
[2]

I think my numpy.repeat and numpy.tile did not work at all.
Does anyone know what happened to this code? Did I do something wrong?

Thank you very much!

**Comment by bigdeeer** [comment]
![snipaste_2018-04-03_00-11-15](https://user-images.githubusercontent.com/25148612/38203959-98f307fa-36d3-11e8-98b6-4fd32d067624.png)
![snipaste_2018-04-03_00-11-21](https://user-images.githubusercontent.com/25148612/38203964-9b861660-36d3-11e8-860a-a21a3f195588.png)

**Comment by pv** [comment]
They return the new result, not operate inplace.
