### ISSUE TITLE
np.random.choice unusable for array dimensions > 1

### ISSUE THREAD

**Issue by pyformulas** [numpy/numpy#10835]
NumPy version 1.14.2

It's not possible to grab a random row from a 2d array using np.random.choice. Consider this array:

`points = np.random.random((10,2))`

Trying to get a random row this way fails
```python
np.random.choice(points)

ValueError: a must be 1-dimensional
```
which might be reasonable. (A more reasonable behavior is perhaps for np.random.choice to take an optional axis= argument so that it can return a random slice along the axis, defaulting to a random element in the entire array.)

However, there is *no* way to directly grab a random row:
```python
np.random.choice(list(points))

ValueError: a must be 1-dimensional
```
```python
np.random.choice(tuple(points))

ValueError: a must be 1-dimensional
```
```python
np.random.choice([row for row in points])

ValueError: a must be 1-dimensional
```

Whereas this can be done with random.sample:
```python
import random
random.sample(list(points), 1)

[array([0.77376144, 0.64678796])]
```

**Comment by njsmith** [comment]
You can sample a random set of row indices:

```python
row_i = np.random.choice(points.shape[0], ...)
points[row_i, :]
```

This also allows for sampling a random set of columns.

**Comment by mattip** [comment]
Maybe needs a line in the documentation of ``random.choice``?

**Comment by pyformulas** [comment]
The problem with @njsmith's solution is that, say you have a list of arrays. The expected behavior for numpy.random.choice is for it to return a random array from the list. But attempting to do this can result in `ValueError: a must be 1-dimensional`. I think this is because numpy internally converts the list to an array, making it appear 2-dimensional.

**Comment by stmax82** [comment]
I think I just ran into this problem with a list of arrays. I want to pick a random array from a list of arrays:

x = np.zeros((10,10))
y = np.ones((10,10))
z = np.random.choice([x,y])

This results in the unexpected error "ValueError: a must be 1-dimensional".
Well "a" clearly is 1-dimensional...

Note that if x and y have different shapes, random.choice works as expected.
Took me a while to figure that out because my arrays only occasionally end up with the same shapes... in which case the error occures. :/

**Comment by WarrenWeckesser** [comment]
The recommended method for making a random choice is now to use the `choice` method of the `Generator` class.  You can get an instance of this class with, for example, `np.random.default_rng()`.

For example, here's the example from top of this issue:

```
In [63]: rng = np.random.default_rng()

In [64]: points = rng.random((10,2))

In [65]: points
Out[65]: 
array([[0.37279228, 0.21731135],
       [0.46409222, 0.8051227 ],
       [0.86021344, 0.13008027],
       [0.5291926 , 0.46637031],
       [0.57839398, 0.13400253],
       [0.61457234, 0.83176585],
       [0.02210913, 0.67098608],
       [0.79260095, 0.94899478],
       [0.44924031, 0.8708212 ],
       [0.36823098, 0.51461417]])

In [66]: rng.choice(points)
Out[66]: array([0.37279228, 0.21731135])
```
Here's the most recent example:
```

In [67]: x = np.zeros((10,10))

In [68]: y = np.ones((10,10))

In [69]: z = rng.choice([x,y])

In [70]: z
Out[70]: 
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
```
I don't think there are any plans to make improvements to the legacy random code, so I'm closing the issue, but we can reopen it if the demand is high.

**Comment by LostInBayes** [comment]
I too would like to sample from a 2d numpy array but I'm restricted to 1d arrays . :(

**Comment by jtrakk** [comment]
>  I'm closing the issue, but we can reopen it if the demand is high.

FWIW the issue currently has 10 👍, which would rank it 12th of 1,864 among open issues on that metric. Perhaps it's time to consider reopening?

**Comment by rgommers** [comment]
> FWIW the issue currently has 10 +1, which would rank it 12th of 1,864 among open issues on that metric. Perhaps it's time to consider reopening?

Those are from before adding `Generator.choice`, which solves the problem. We'd like to avoid changing the legacy functions at this point.

> At least it would be nice to improve discovery for the new recommended method (which does solve the problem AFAICT).

That is a good point. I opened PR gh-16075 to do that.

**Comment by ak2911** [comment]
think alternatively,
use random to generate indices; then slice fromthe array. works on any dimention
n_sample = 10 #sample count
points[np.random.randint(0,points.shape[0], n_sample )]
