### ISSUE TITLE
Memory leak numpy.random.randint in 1.14.0

### ISSUE THREAD

**Issue by jan-adx** [numpy/numpy#10841]
This code leaks:
while True:
   a = numpy.random.randint(10)

replacement by following works fine:
   a = int(numpy.random.rand() * 10)

**Comment by charris** [comment]
I don't see this problem.

**Comment by bashtage** [comment]
Also don't see it on Windows.

**Comment by jan-adx** [comment]
I think I installed it with pip install.

**Comment by bashtage** [comment]
I ran it on Ubuntu using the wheel and can't repro.

**Comment by bashtage** [comment]
@charris This looks like a false positive, probably closeable.

**Comment by jan-adx** [comment]
Well, it still happens to me on one machine... if there is some way how to debug it, let me know, I can try it.

**Comment by mattip** [comment]
It seems you have installed kernel 4.13 into ubuntu 16.04, my Ubuntu 16.04 has 4.4. Do you still have the old one installed, can you reboot with grub and choose the older one?

**Comment by mattip** [comment]
Closing, please reopen if you see it on another machine or wish engage in debugging it.

**Comment by jacquesqiao** [comment]
I also find the same problem. 
```python
a = int(numpy.random.randint() * 10)
```
does not work for me. Use random.randint() has no problem.
