### ISSUE TITLE
[Enhancement] Add axis-less flip for 1d arrays

### ISSUE THREAD

**Issue by homocomputeris** [numpy/numpy#10847]
I suggest autoflipping 1d arrays without specifying axis:

``` python
a = np.array([1, 2, 3])
b = np.flip(a)
```
instead of
`b = np.flip(a, 0)`

`fliplr` doesn't work in this case, and `flip` can easily check input's `ndim`.

**Comment by mhvk** [comment]
It would seem to make sense to make this work. I think the easiest would be to create some default for `axis`. Sensible options are first (`axis=0`), last (`axis=-1`) or, perhaps most similar to other numpy functions, all axes (`axis=None`). The latter would require a bit more of a rewrite, but could include giving the ability to give multiple axes. Something along these lines:
```
if axis is None:
    indexer = (slice(None, None, -1),) * m.ndim
else:
    if not isinstance(axis, tuple):
        axis = (axis,)
    indexer = [slice(None)] * m.ndim
    try:
        for ax in axis:
            indexer[ax] = slice(None, None, -1)
    except IndexError:
        raise ValueError(...)
    indexer = tuple(indexer)
return m[indexer]
```
Would you be interested in making a PR for this? I think the above code would suffice, but it would need also some additional tests that check that things work, an update to the docstring, and an entry in the release notes.

**Comment by eric-wieser** [comment]
@mhvk: Should use a `normalize_axis_tuple` call in there somewhere

**Comment by sitelight** [comment]
That's a great idea!
I think that adding this tiny portion of code might do the trick (with default axis =0)
`def axis(a):
    return flip(a,0)`

**Comment by mhvk** [comment]
@sitelight - discussion moved over to the actual implementation in #10872
