### ISSUE TITLE
Possible issue with np.moveaxis

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#10846]
Based on the documentation for [moveaxis](https://docs.scipy.org/doc/numpy/reference/generated/numpy.moveaxis.html), I am having issues interpreting the following behavior:

```python
In [19]: a = np.arange(24).reshape((2,3,4))

In [20]: b = np.moveaxis(a, (0, 1, 2), (2, 0, 1))

In [21]: a.shape
Out[21]: (2, 3, 4)

In [22]: b.shape
Out[22]: (3, 4, 2)
```

My interpretation of the moveaxis call is that the axis in first position should now be in second position, the axis in second position should be in third position, and the axis in third position should come first, so that the shape of ``b`` should be ``(4, 2, 3)``, not ``(3, 4, 2)``.

Is the behavior above expected? If so, I think it might make sense to include an example like this and explain why it behaves this way (at the moment there is only really one example since they are all equivalent).

**Comment by matthew-brett** [comment]
Sorry if I'm not understanding, but I was expecting the result you got.  Axis 0 length 2 goes to index 2, axis 1 length 3 goes to index 0, axis 2 length 4 goes to position 1 - `(3, 4, 2)`.

**Comment by astrofrog** [comment]
I have no idea what I was thinking a few hours ago, but clearly I was in need of ☕️ 

Sorry for the noise!
