### ISSUE TITLE
Outdated https://docs.scipy.org/doc/numpy-dev/

### ISSUE THREAD

**Issue by cdeil** [numpy/numpy#10844]
At https://docs.scipy.org/doc/numpy-dev/ I see this:

> NumPy v1.13.dev0 Manual
> Welcome! This is the documentation for NumPy 1.13.0.dev0+a5d71d6, last updated Jan 16, 2017.

That's over a year old.

Can you please update it to the show the latest dev docs, or redirect to the proper place if they exist somewhere else?

**Comment by mattip** [comment]
The repo for this is https://github.com/scipy/docs.scipy.org, but it is not clear to me how they generate the content for the doc/numpy-dev site. In any case, IMO it should link to http://www.numpy.org/devdocs/index.html

**Comment by rgommers** [comment]
> The repo for this is https://github.com/scipy/docs.scipy.org, but it is not clear to me how they generate the content for the doc/numpy-dev site. 

Currently it's ``make dist && make upload USERNAME=... RELEASE=dev`` (see https://github.com/numpy/numpy/blob/master/doc/Makefile#L89). Manual, that's why it's outdated. The `docs.scipy.org` repo should be pointed to http://www.numpy.org/devdocs/index.html indeed, which is a simple change in the `index.html` in that repo.

**Comment by cdeil** [comment]
If someone has the bandwidth to take on the task of improving the Numpy docs setup / build / deploy, another major improvement would be to have a version chooser (as e.g. selector on  https://docs.python.org/3/ in the top left or many ReadTheDocs sites).

@rgommers - Is there a proposal how to automate the docs build / deploy so that this becomes maintainable to keep it up to date?

**Comment by rgommers** [comment]
> @rgommers - Is there a proposal how to automate the docs build / deploy so that this becomes maintainable to keep it up to date?

No, there's no good way to fully automate this AFAIK, and looking into how to do this securely with ssh access to a server via a public repo is (at least for me) much more work than running a few commands at release time. It's a matter of a few commands; normally it's done within a few days, but for 1.14.1/2 I didn't get the request to do this (is part of the release procedure).

**Comment by eric-wieser** [comment]
Could you do this with a github webhook, and have it notify the server when a new release is available?

**Comment by rgommers** [comment]
Here are the instructions, it's really not too much of a burden: https://github.com/numpy/numpy/blob/master/doc/HOWTO_RELEASE.rst.txt#update-docsscipyorg

If the devdocs are automatically updated, I'm happy with the status of this stuff.

**Comment by eric-wieser** [comment]
Presumably building on the server is not an option?

Perhaps the server could pull the built docs from CircleCI when notified?

**Comment by pv** [comment]
As long as this involves servers maintained by us, I don't like the
idea of anything more complex than rsync. Babysitting stuff takes time
that nobody really has.

**Comment by charris** [comment]
@rgommers My understanding is the the docs get updated for minor, but not micro, version changes.

**Comment by rgommers** [comment]
> No, we've always done minor versions as well

to be fair, there's a bunch more missing. besides the release notes, nothing much changes.....

I'd be in favor to add them consistently, because it's not much work and it avoids the types of questions in this issue

**Comment by mattip** [comment]
The specific problem in this issue has been solved. It seems there is consensus not to automate this during the release process. Can we close?

**Comment by rgommers** [comment]
Yep, the original issue is fixed by https://github.com/scipy/docs.scipy.org/pull/14. Thanks @mattip, all

**Comment by cdeil** [comment]
Well, the original issue report was that https://docs.scipy.org/doc/numpy-dev/ is outdated, and it still is and Google will redirect people there. So this is not supposed to be the place for the devdocs? Then maybe remove that outdated copy of the devdocs?

**Comment by rgommers** [comment]
Yes I know, the PR is merged and it will go live later today

**Comment by cdeil** [comment]
OK, thanks!

**Comment by rgommers** [comment]
All up to date now, and removed the `numpy-dev` content. 

The old `scipy-dev` was turned into all symbolic links, which is even better - I just don't know how that was done. @pv I suspect that was you? If it's easy and you can do the same for `numpy-dev`, that would be nice. If not easy, current status is fine too.

**Comment by cdeil** [comment]
Thank you very much!
