### ISSUE TITLE
numpy 1.14.2 fails on pip install - darwin, fish shell, pyenv, virtualenv

### ISSUE THREAD

**Issue by wizofe** [numpy/numpy#10853]
Trying to install `numpy-1.14.2` on darwin high sierra 10.13.4, `fish` shell and `virtualenv` with `python` 3.7.0b2 (same with 3.8-dev):

```python
File "/private/var/folders/v3/7ns32f8n17n9szkdd738rfhw0000gn/T/pip-build-98whq2fs/numpy/numpy/distutils/fcompiler/gnu.py", line 83, in gnu_version_match
raise ValueError(err + version_string)
ValueError: A valid Fortran version was not found in this string:
/usr/local/opt/python/bin/python3.6: No module named virtualfish
7.3.0
```

If I do the same with python 2.7 it works perfectly fine. Any ideas? I would love to help to fix the issue if you point me to the right direction.

**Comment by charris** [comment]
Are you installing from source? Numpy 1.14.x source on PyPI is not python 3.7 compatible.

**Comment by charris** [comment]
See also #10500.

**Comment by mattip** [comment]
Could you try again? In #10500 they are now reporting success

**Comment by mattip** [comment]
I wonder if the `fish` shell is `bash`-compliant enough for our distutils. See for instance #9970.

**Comment by charris** [comment]
See #11824, which has more discussion. I don't know if the fish shell is the problem, but it is likely.

**Comment by mattip** [comment]
Closing since we didn't get an update. If needed, please reopen with more information on what exactly is failing.
