### ISSUE TITLE
numpy multiarray fail pkgsrc

### ISSUE THREAD

**Issue by djadk84** [numpy/numpy#10854]
When I tryied to install scipy using [pkgsrc](https://www.netbsd.org/docs/pkgsrc/) I got this error, I reported the error on [pkgsrc](https://www.netbsd.org/docs/pkgsrc/) upstrean and they apply this [fix](https://github.com/NetBSD/pkgsrc/blob/trunk/math/py-numpy/patches/patch-numpy_distutils_system__info.py). Basicly it makes numpy using blaslib from [lapack](http://www.netlib.org/lapack/) instead of openblas libs

> (pkgenv)
 [devops@brownie mlearning]$ pip install scipy
Collecting scipy
  Using cached scipy-1.0.1.tar.gz
Requirement already satisfied: numpy>=1.8.2 in ./pkgenv/lib/python3.6/site-packages (from scipy)
Installing collected packages: scipy
  Running setup.py install for scipy ... error
    Complete output from command /home/devops/mlearning/pkgenv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yvrzqwmu/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3v8rk3g3-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/devops/mlearning/pkgenv/include/site/python3.6/scipy:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    Traceback (most recent call last):
      File "/home/devops/mlearning/pkgenv/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
        from . import multiarray
    ImportError: /home/devops/mlearning/pkgenv/lib/python3.6/site-packages/numpy/core/multiarray.so: undefined symbol: cblas_cdotc_sub
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yvrzqwmu/scipy/setup.py", line 418, in <module>
        setup_package()
      File "/tmp/pip-build-yvrzqwmu/scipy/setup.py", line 398, in setup_package
        from numpy.distutils.core import setup
      File "/home/devops/mlearning/pkgenv/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
        from . import add_newdocs
      File "/home/devops/mlearning/pkgenv/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "/home/devops/mlearning/pkgenv/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
        from .type_check import *
      File "/home/devops/mlearning/pkgenv/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
        import numpy.core.numeric as _nx
      File "/home/devops/mlearning/pkgenv/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
        raise ImportError(msg)
    ImportError:
    Importing the multiarray numpy extension module failed.  Most
    likely you are trying to import a failed build of numpy.
    If you're working with a numpy git repo, try `git clean -xdf` (removes all
    files not under version control).  Otherwise reinstall numpy.
    
    Original error was: /home/devops/mlearning/pkgenv/lib/python3.6/site-packages/numpy/core/multiarray.so: undefined symbol: cblas_cdotc_sub
    
    
    ----------------------------------------
>Command "/home/devops/mlearning/pkgenv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yvrzqwmu/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3v8rk3g3-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/devops/mlearning/pkgenv/include/site/python3.6/scipy" failed with error code 1 in /tmp/pip-build-yvrzqwmu/scipy/

**Comment by njsmith** [comment]
That will make their numpy rather slow, but I guess it's up to them how they configure their distribution.

Is there something you think we should do?

**Comment by djadk84** [comment]
Also I have to let you know that I only have issue with numpy when Im using python 3.6. thia error is not present when using python 2.7 so there is no need for this patch.

**Comment by rgommers** [comment]
This looks like a `pkgsrc` issue then if it works with 2.7. @djadk84 it makes sense to ping that dev, there's likely a better solution that `pkgsrc` could use - would be good to check at least that they are aware that their current fix has significant impact on performance.

It doesn't look like there's anything to do for numpy here, so closing this issue. Feel free to post more comments here though, or ping me on a pkgsrc issue.
