### ISSUE TITLE
np.unique is producing invalid output for constant big arrays

### ISSUE THREAD

**Issue by thoth291** [numpy/numpy#10857]
Hi,
Stumbled upon this error:
```python
In [1]: np.unique(np.ones(8*10**9,dtype=np.float32))
Out[1]: array([ 0.], dtype=float32)
```
But reducing size - 8*10**8 - helps to fix it.
```python
In [2]: np.unique(np.ones(8*10**8,dtype=np.float32))
Out[2]: array([ 1.], dtype=float32)
```
I wonder if it's issue with `sort` or any other routines...

Makes me wonder if any of my Numpy codes are correct... since I deal with very big arrays normally.

Please help!

**Comment by charris** [comment]
How much memory do you have? The array itself consumes 32*10**9, and the algorithm somewhat more. Also, what numpy version? There have been some recent changes. The fact that it works for `8*10**8` is a little bit suspicious.

**Comment by charris** [comment]
Also, what platform?

**Comment by charris** [comment]
That is a pretty old version. Just to for the information, is there a way you can test a more recent version? Also, are you running bare numpy or is anything else involved.

**Comment by charris** [comment]
Hmm, most of the changes haven't been released yet. I don't see how sort would matter here, as the array is already sorted. Things would really need to go wrong for that to mess up. However, it is possible that the indexing is failing somewhere.

**Comment by charris** [comment]
Might also help if you could pin down where it goes wrong. I would expect a power of two :)  Is the big array actually ones?

**Comment by charris** [comment]
I don't have enough memory to check on this myself.

**Comment by thoth291** [comment]
Couldn't reproduce the error with any other version of numpy. It must be something happened with this particular installation.
You may close the issue now.
Thanks!

**Comment by charris** [comment]
OK. Let us know if it turns up again.
