### ISSUE TITLE
histogramdd fuzzes the rightmost bin edge

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10864]
This was clearly deliberate, as there's an explicit test:

https://github.com/numpy/numpy/blob/c8a5f560f1eedd510ca5656b06dd1ca2ba9322bd/numpy/lib/tests/test_histograms.py#L628-L632

It's implemented here:

https://github.com/numpy/numpy/blob/c8a5f560f1eedd510ca5656b06dd1ca2ba9322bd/numpy/lib/histograms.py#L915-L921

Why do we do this? It's:
* Not documented
* Inconsistent with `histogram`
* Arbitrarily tied to base 10 in a bizarre way
* Causing zero-width bins to fail
* Possibly a workaround for loss of precision from us casting integer edges to float

Is there any reason not to switch to:
```python
on_edge = sample[:, i] == edges[i][-1]
# Shift these points one bin to the left. 
Ncount[i][on_edge] -= 1
```

Raised in https://github.com/numpy/numpy/pull/4284#issuecomment-36425095 and #9435

**Comment by eric-wieser** [comment]
Patch at #11023 for the sake of discussion

**Comment by eric-wieser** [comment]
I've put a patch at #11023, for the sake of discussion - it should make it clearer what the behavior changes are.

**Comment by HagaiHargil** [comment]
@eric-wieser What do you think of my [earlier comment](https://github.com/numpy/numpy/issues/10864#issuecomment-385601711)? As I previously said, this bug kinda hurts me, and I'd be happy to help to resolve this issue.
