### ISSUE TITLE
ma/bench.py is broken on Python 2.7 - encoding error

### ISSUE THREAD

**Issue by jdmarch** [numpy/numpy#10868]
`ma/bench.py` contains a UTF-8 character `µ` on line 40.

Originally, the module included a standard default encoding line:
`# -*- coding: utf-8 -*-`

but this was removed in numpy 1.10.0 in https://github.com/numpy/numpy/commit/7c8c9adda27efe7f84fc98240ee1b7fa15714f06#diff-047b693f5b55e9ee72fcc8ad74f10d92 @charris

**Comment by charris** [comment]
Closed by #10869.
