### ISSUE TITLE
center_of_mass() overflow

### ISSUE THREAD

**Issue by ErikBsly** [numpy/numpy#10865]
When using [center_of_mass()](https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.ndimage.measurements.center_of_mass.html) it calculates the intermediate sum with the element type of the array, e.g. int32. However, when the input is a large array or is filled with large values, it _silently_ overflows quite fast and returns invalid (e.g. negative) center of mass values.

Since it uses np.sum() internally, one should be able to set the accumulator dtype in center_of_mass() which then forwards it to sum() to prevent possible overflows.

**Comment by seberg** [comment]
Does not sound like a numpy, but like a possible scipy issue. Please move it there.

**Comment by seberg** [comment]
There might be a numpy issue below here, but I am sure we have open issues for that anyway.
