### ISSUE TITLE
DOC: State in docstring that lexsort is stable.

### ISSUE THREAD

**Issue by pchanial** [numpy/numpy#10873]
Summary says it all. I had to dig into the item_selection.c file to find out that mergesort is used internally.
sort and argsort docstrings state that lexsort is stable but lexsort's one does not. Btw, the issue has been reported in 2011 http://numpy-discussion.10968.n7.nabble.com/stable-sort-on-a-recarray-td27985.html.

**Comment by mattip** [comment]
Fixed via merged PR #10874
