### ISSUE TITLE
DOC: Bad link to `np.random.randint

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#10886]
Under  numpy.random.random_integers(low, high=None, size=None), it says:

> See also random.randint

but the link goes to https://docs.python.org/dev/library/random.html#random.randint, when it should go to https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html .

**Comment by mattip** [comment]
The source for the link is mtrand.pyx, under random_integers, ``random.randint`` links to the python function of the same name not the ``np.random.randint``
