### ISSUE TITLE
Not working `rundocs()` in `numpy\lib\tests\test_polynomial.py`

### ISSUE THREAD

**Issue by andrzejQ** [numpy/numpy#10881]
I suppose `rundocs ()` does not work because of a line which precedes main docstring:
    `from __future__ import division, absolute_import, print_function`

env: `numpy                     1.14.2           py36h5c71026_1
conda/4.5.0 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.16299`

**Comment by andrzejQ** [comment]
"from __future__ imports must occur at the beginning of the file", but main docstring of module can exists before "from __future__ import division"

**Comment by mattip** [comment]
This is from 6aa264c, and looking at the diff seems to be the only one that introduced this regression. To be precise, `rundocs()` runs but the docstring is empty.

In the mean time formatting has changed, so moving the `from __future__` import to after the docstring results in many failing tests

**Comment by mattip** [comment]
The formatting tests started failing in 8943851, which changed float number formatting. It seems the doctests need to be reformatted
