### ISSUE TITLE
NumPy comparison to SymPy Rationals is "broken"

### ISSUE THREAD

**Issue by dhermes** [numpy/numpy#10894]
This is because the `sympy.Rational` instances get converted to a `float` / `np.float64` before being compared, hence they are rounded. ISTM that returning `NotImplemented` in `__cmp__`  / `__eq__` / etc. may be possible (but may also be a breaking change that the maintainers aren't interested in).

----

For example both `float` and `np.float64` think they are equal to the fraction `1 + 2^{-53}` (which can't be represented in an IEEE-754 64-bit float):

```python
>>> import numpy as np
>>> import sympy
>>> v = 1.0
>>> v_np = np.float64(v)
>>> v_rat = sympy.Rational(v)
>>> frac = sympy.Rational(2**53 + 1, 2**53)
>>> float(frac)
1.0
>>> v < frac, frac > v, v == frac, frac == v
(False, False, True, True)
>>> v_np < frac, frac > v_np, v_np == frac, frac == v_np
(False, False, True, True)
>>> v_rat < frac, frac > v_rat, v_rat == frac, frac == v_rat
(True, True, False, False)
```

and similar behavior occurs when comparing `1 - 2^{-53}` (which can be represented) to `1 - 2^{-54}` (which cannot):

```python
>>> v = 1.0 - np.spacing(0.5)
>>> v.hex()
'0x1.fffffffffffffp-1'
>>> v_np = np.float64(v)
>>> v_rat = sympy.Rational(v)
>>> frac = (v_rat + 1) / 2  # Midpoint
>>> float(frac)
1.0
>>> v < frac < 1, 1 > frac > v
(True, False)
>>> v_np < frac < 1, 1 > frac > v_np
(True, False)
>>> v_rat < frac < 1, 1 > frac > v_rat
(True, True)
>>> v == frac, frac == v
(False, True)
>>> v_np == frac, frac == v_np
(False, True)
```

However, `float` and `np.float64` disagree when comparing `17/8 - 2^{-51}` (which can be represented) to `17/8 - 2^{-52}` (which cannot):

```python
>>> v = 2.125 - np.spacing(2.125)
>>> v.hex()
'0x1.0ffffffffffffp+1'
>>> v_np = np.float64(v)
>>> v_rat = sympy.Rational(v)
>>> frac = (v_rat + sympy.Rational(2.125)) / 2  # midpoint
>>> frac <= v
False
>>> frac <= v_np
True
>>> frac <= v_rat
False
>>> v == frac, frac == v
(False, False)
>>> v_np == frac, frac == v_np
(False, True)
```

**Comment by asmeurer** [comment]
It's worth noting that SymPy has its own issues here, which may or may not come up when testing this https://github.com/sympy/sympy/issues/11707
