### ISSUE TITLE
`irfftn` corrupts input when dimensions >=3

### ISSUE THREAD

**Issue by rainwoodman** [numpy/numpy#10895]
Seems to be introduced recently. It doesn't affect `fftn`, `ifftn` or `rfft`, `irfft`.

Here is the reproducer.
```
import numpy
from numpy.testing import assert_allclose

def showbug(nd):
    size = [4] * nd
    x = numpy.random.uniform(size=size)
    y = numpy.fft.rfftn(x)
    y1 = y.copy()

    numpy.fft.irfftn(y1)

    assert_allclose(y1, y)

showbug(3)
```

```
Traceback (most recent call last):
  File "fftbug.py", line 14, in <module>
    showbug(3)
  File "fftbug.py", line 12, in showbug
    assert_allclose(y1, y)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([[[ 1.612765+0.j      , -0.069468+0.278309j, -1.196650+0.j      ],
        [ 1.794408+0.j      ,  0.084526+0.187052j,  0.642339+0.j      ],
        [ 1.536380+0.j      , -0.811544-0.006539j,  0.736002+0.j      ],...
 y: array([[[  3.227387e+01+0.j      ,  -6.852522e-01-0.432786j,
          -2.638166e+00+0.j      ],
        [ -9.017300e-01+2.401103j,   1.732144e+00+0.885346j,...
```

**Comment by eric-wieser** [comment]
Thanks for the complete repro!

Works on my machine:
```python
In [47]: import numpy
    ...: from numpy.testing import assert_allclose
    ...: 
    ...: def showbug(nd):
    ...:     size = [4] * nd
    ...:     x = numpy.random.uniform(size=size)
    ...:     y = numpy.fft.rfftn(x)
    ...:     y1 = y.copy()
    ...: 
    ...:     numpy.fft.irfftn(y1)
    ...: 
    ...:     assert_allclose(y1, y)
    ...: 
    ...: showbug(3)
    ...: 

In [48]: numpy.__version__
Out[48]: '1.14.2'
```

**Comment by rainwoodman** [comment]
1.13.3 has this problem. So presumably fixed some where?

**Comment by pv** [comment]
I don't think there are code differences in numpy.fft between these versions...

Just a check: do you have some package installed that monkeypatches numpy.fft (e.g. to use MKL)?

**Comment by rainwoodman** [comment]
I installed numpy from conda. It has the problem on 1.14.2 as well.

python fftbug.py 
1.14.2
Traceback (most recent call last):
  File "fftbug.py", line 15, in <module>
    showbug(4)
  File "fftbug.py", line 13, in showbug
    assert_allclose(y1, y)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([[[[ 1.637694+0.j      , -0.798041-0.148766j,
           0.133596+0.j      ],
         [ 2.596948+0.j      ,  0.730632+0.308955j,...
 y: array([[[[ 1.208828e+02+0.j      ,  2.842134e-01+0.363692j,
          -5.359733e+00+0.j      ],
         [-1.741360e+00+5.362906j,  2.010823e+00+0.860568j,...
(base) [yfeng1@waterfall tmp]$ !cat
cat .travis.yml 
cat: .travis.yml: No such file or directory
(base) [yfeng1@waterfall tmp]$ cat fftbug.py 
import numpy
from numpy.testing import assert_allclose

print(numpy.__version__)
def showbug(nd):
    size = [4] * nd
    x = numpy.random.uniform(size=size)
    y = numpy.fft.rfftn(x)
    y1 = y.copy()

    numpy.fft.irfftn(y1)

    assert_allclose(y1, y)

showbug(4)

**Comment by pv** [comment]
And `numpy.fft.rfftn is numpy.fft.fftpack.rfftn`?

**Comment by rainwoodman** [comment]
No.

In [1]: import numpy

In [2]: rfftn
Out[2]: <function mkl_fft._numpy_fft.rfftn>

**Comment by pv** [comment]
If `(numpy.fft.rfftn is numpy.fft.fftpack.rfftn) == False`, then something has monkeypatched it, I think.

**Comment by pv** [comment]
Ok, looks like something that needs to be fixed in continuum's mkl_fft then.
