### ISSUE TITLE
BUG: result of numpy.einsum is sometimes wrong with float16

### ISSUE THREAD

**Issue by toslunar** [numpy/numpy#10899]
To reproduce:
```
>>> np.einsum('i,ji->', np.ones(2, dtype=np.float16), np.eye(2, dtype=np.float16))
32770.0
```

Why:
`*(@type@ *)dataptr[2] += @to@(accum);` in https://github.com/numpy/numpy/blob/3ec8875/numpy/core/src/multiarray/einsum.c.src#L594 is preprocessed to `*(npy_half *)dataptr[2] += npy_float_to_half(accum);`.  The example above works fine if the line is replaced with
```
*(@type@ *)dataptr[2] = @to@(@from@(*(@type@ *)dataptr[2]) + accum);
```

**Comment by eric-wieser** [comment]
That fix looks correct to me.

It sucks that we're not using a language that can overload operators for float16...

**Comment by toslunar** [comment]
Sure. I'll soon send a PR on this issue.
