### ISSUE TITLE
Documentation : No link to `standard_normal` in 'See Also' section of 'numpy.random.randn'

### ISSUE THREAD

**Issue by subhrm** [numpy/numpy#10902]
In the documentation [page ](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html) of `numpy.random.randn` , the **See Also** section mentions `random.standard_normal` , but there there is no link to the documnetaion page of `random.standard_normal`.  This should link to [https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.standard_normal.html](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.standard_normal.html)

**Comment by stefanv** [comment]
@charris What is the convention of linking to functions in submodules?  `random.standard_normal` and `standard_normal` both seem valid, so comes down to convention.  And then we can fix the tools to understand whichever option we prefer.
