### ISSUE TITLE
Error in calculation of .prod() function in numpy

### ISSUE THREAD

**Issue by yuexiaxiaoyin** [numpy/numpy#10913]
本人在练习欧拉计划的第八题时，选择使用numpy的prod函数来计算列表的累乘。选择将13个数的列表转化为array对象，结果在计算[5 5 7 6 6 8 9 6 6 4 8 9 5]时，prod计算的结果是2039787520，与科学计算器计算的结果23514624000不一致

**Comment by eric-wieser** [comment]
Translated with google translate and some common sense applied after:

> When I practise the eighth question of Project Euler, I chose to use numpy's prod function to calculate the list's product. We chose to convert the list of 13 numbers into an array object. When calculating [5 5 7 6 6 8 9 6 6 4 8 9 5], the result of prod calculation is 2039787520, which is inconsistent with the result calculated by scientific calculator 23514624000

**Comment by eric-wieser** [comment]
You're using windows, and numpy is defaulting to using a `np.int32` array. As a result, you're getting integer overflow:
```python
>>> x = np.array([5, 5, 7, 6, 6, 8, 9, 6, 6, 4, 8, 9, 5])
>>> x.dtype
dtype('int32')  # On windows, anyway
>>> np.prod(x)
2039787520
>>> np.prod(x, dtype=np.int64)
23514624000
```
It would be nice if we could warn about this...

**Comment by yuexiaxiaoyin** [comment]
thank you a lot @eric-wieser
