### ISSUE TITLE
Manylinux wheel size could be reduced by 66%

### ISSUE THREAD

**Issue by LouisAmon** [numpy/numpy#10920]
When building `numpy` from source and running the command `strip`, the resulting folder is 66% lighter than when using the manylinux wheel (via `pip`).

> [...] the strip program removes inessential information from executable binary programs and object files, thus potentially resulting in better performance and sometimes significantly less disk space usage
https://en.wikipedia.org/wiki/Strip_(Unix)

This is probably harmless on most systems, yet it is quite important in size-constrained systems (such as [AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/limits.html)).

Some developers have resorted to distributing their own stripped binaries (e.g. [lambda packages](https://github.com/Miserlou/lambda-packages/) for the serverless framework [zappa](https://github.com/Miserlou/Zappa)), but it seems like a makeshift solution.

I think the problem should be solved upstream, as each library should be responsible for packaging their own optimized binaries.

# System specifications

Every command below has been executed using the `amazonlinux` docker image.
https://hub.docker.com/_/amazonlinux/

Numpy version: `1.14.2`
Python version: `3.6.2`

# How to replicate 

## Prepare docker image

```
docker run -it amazonlinux bash
yum update -y
yum install -y findutils binutils python36-devel gcc
```

## Install wheel & measure package size

```bash
python3 -m pip install -t wheel numpy==1.14.2
du -sh wheel
```
--> **57 MB**

Try [strip](https://en.wikipedia.org/wiki/Strip_(Unix)):

```bash
find wheel/ -name "*.so"|xargs strip
du -sh wheel
```
--> 56 MB

No real progress here. The binary wheel seems already stripped.

## Build from source & measure package size

```bash
python3 -m pip install -t build --no-binary numpy numpy==1.14.2
du -sh build
```
--> 42 MB

Try [strip](https://en.wikipedia.org/wiki/Strip_(Unix)):

```bash
find build/ -name "*.so"|xargs strip
du -sh build
```
--> **19 MB**

**Comment by pv** [comment]
The reason is clear: the wheel on PyPi bundles a copy of openblas, the
one built from sources does not.

**Comment by pv** [comment]
... and just to be clear: openblas has to be bundled because generally
there is no LAPACK library installed on target machines.

So "building from sources" is not a solution to reduce the manylinux
wheel size.

**Comment by LouisAmon** [comment]
Hello @pv, thanks for looking into this.

As per the [documentation](https://docs.scipy.org/doc/numpy-1.14.2/user/building.html):
> NumPy does not require any external linear algebra libraries to be installed. However, if these are available, NumPy’s setup script can detect them and use them for building.

There problem here is that, considering `numpy` is often installed along other Python packages from the Python scientific community (e.g. `pandas`, `scipy`, etc.), they all add up to an impressive size.

Now I know each library should address their own build problem separately, but since `numpy` is usually the main building block... maybe including `openblas` isn't what everyone needs.

Isn't there a way to offer an alternate "lightweight" installation ?
Maybe something along the lines: `pip install numpy-light`

**Comment by bashtage** [comment]
On conda numpy + openblas are only ~ 13MiB.  Curious what isn't in conda's 2 libs or is in the wheels. Extra static linked deps?

**Comment by charris** [comment]
@bashtage compressed or expanded? The numpy wheels on PyPI are also around 12 MiB.

**Comment by bashtage** [comment]
Compressed, so similar.

**Comment by LouisAmon** [comment]
@bashtage 

This is the list of binaries currently included in the wheel:
```
bash-4.2# find numpy -name "*.so"|xargs du -sh
8.0K	numpy/core/struct_ufunc_test.cpython-36m-x86_64-linux-gnu.so
2.0M	numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so
16K	numpy/core/umath_tests.cpython-36m-x86_64-linux-gnu.so
52K	numpy/core/test_rational.cpython-36m-x86_64-linux-gnu.so
116K	numpy/core/multiarray_tests.cpython-36m-x86_64-linux-gnu.so
8.0K	numpy/core/operand_flag_tests.cpython-36m-x86_64-linux-gnu.so
8.0K	numpy/core/_dummy.cpython-36m-x86_64-linux-gnu.so
1.6M	numpy/core/umath.cpython-36m-x86_64-linux-gnu.so
936K	numpy/random/mtrand.cpython-36m-x86_64-linux-gnu.so
37M	numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
180K	numpy/linalg/_umath_linalg.cpython-36m-x86_64-linux-gnu.so
28K	numpy/linalg/lapack_lite.cpython-36m-x86_64-linux-gnu.so
40K	numpy/fft/fftpack_lite.cpython-36m-x86_64-linux-gnu.so
```

Most likely, conda has some kind of optimization allowing it to avoid including the `libopenblas` dependency (?). 

The wheel itself is build here:
https://github.com/MacPython/numpy-wheels

**Comment by LouisAmon** [comment]
Still, I believe there is an architectural issue in the way the PyData suite is built and synergizes with one another.

If you install e.g. `numpy + scipy + pandas`, you end up with 358MB's worth of code & depdendencies, most of which you don't really need.
```
bash-4.2# python3 -m pip install -t . scipy pandas numpy
bash-4.2# du -sh scipy pandas numpy
190M	scipy
111M	pandas
57M	numpy 
```

The only way around this right now is to fiddle with builds, hoping not to mess up the linkage with C libraries along the way (`scipy` is especially tricky in this)

This is a major issue in the industry (from a DevOps perspective), as systems are converging more and more towards the microservice idiom and bundling/compression is key.

Bumping the `multibuild` dependency here and there is definitely going in the right direction (with the auto-strip that had been added).

As for `numpy`: the choice of including `openblas` as a sensible default seems reasonable. The only thing that could be done about this is perhaps updating the docs to reflect this.

I don't think there's much more to do on this issue for the time being.

Again, thanks @pv for your patience :)

**Comment by charris** [comment]
@LouisAmon I think you are comparing compressed to uncompressed. The 64 bit manylinux pip wheels (compressed) are about 12 MiB, approximately the same as the conda wheels. The 64 bit mac wheels, that do not include openblas, are about 4 MiB.

**Comment by LouisAmon** [comment]
@charris all the figures above refer to uncompressed data.

I didn't study the compressed size because my problem was to fit a bunch of *uncompressed* Python libraries into AWS Lambda (262MB maximum uncompressed size).
Besides, wheel compression doesn't always affect packages in the same way depending on the underlying `.so` files.

You are correct about compressed sizes though:
- `numpy-1.14.2-cp36-cp36m--macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl` --> 4.7MB
- `numpy-1.14.2-cp36-cp36m-manylinux1_x86_64.whl` --> 12.8MB

That's still a 63% difference, mostly due to `openblas`...

**Comment by rgommers** [comment]
> even in the aws-provided lambda layer for numpy & scipy, the libopenblasp*.so binaries are there

do you have a link for that? I haven't heard before about AWS providing that
