### ISSUE TITLE
Legacy 1.13 printing broken for 0d arrays

### ISSUE THREAD

**Issue by kohr-h** [numpy/numpy#10934]
Code to trigger the error:
```python
>>> import numpy as np
>>> np.__version__
'1.14.2'
>>> np.array2string(np.array(1.0))
'1.'
>>> np.set_printoptions(legacy='1.13')
>>> np.array2string(np.array(1.0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/numpy/core/arrayprint.py", line 616, in array2string
    return style(a.item())
TypeError: object() takes no parameters
```
Same error with 1.14.1 and 1.14.0.

Since `style` is just an alias for `np._NoValue` the code effectively calls (or instantiates, depending on the code version) `_NoValue(1.0)`, which is not valid.
I saw that there was a recent change in `_globals.py` that makes `_NoValue` an instance instead of a class, but it has no `__call__`, so unless I'm missing something, it won't work either.

**Comment by eric-wieser** [comment]
Yep, this is a bug. Thoughts @ahaldane? Can we really afford a fourth 1.14.x release?

**Comment by ahaldane** [comment]
There are a few other nits that could go in to a 1.14.3. Maybe I can try making a release as @charris suggested...

**Comment by kohr-h** [comment]
Thanks for the quick fix!
