### ISSUE TITLE
Documentation for numpy version is incorrect

### ISSUE THREAD

**Issue by SteveDoyle2** [numpy/numpy#10935]
In all the locations I checked:
 - http://www.numpy.org/devdocs/reference/generated/numpy.lib.NumpyVersion.html
 - https://docs.scipy.org/doc/numpy-1.14.2/release.html
 - https://docs.scipy.org/doc/numpy-1.14.0/release.html
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.lib.NumpyVersion.html

The documentation for how to use NumpyVersion is incorrect:

    >>> from numpy.lib import NumpyVersion
    >>> if NumpyVersion(np.__version__) < '1.7.0'):
    ...     print('skip')

and should be:

    >>> from numpy.lib import NumpyVersion
    >>> if NumpyVersion(np.__version__) < '1.7.0':
    ...     print('skip')

**Comment by eric-wieser** [comment]
For anyone else struggling
```diff
 >>> from numpy.lib import NumpyVersion
->>> if NumpyVersion(np.__version__) < '1.7.0'):
+>>> if NumpyVersion(np.__version__) < '1.7.0':
 ...     print('skip')
```
