### ISSUE TITLE
make `binary_repr` more usefull

### ISSUE THREAD

**Issue by oscardssmith** [numpy/numpy#10932]
Currently, `binary_repr` takes in a number, and outputs a string. This is not very useful, given that `bin` (from python) does the same thing, only faster. It seems to me that it should instead take in an `array_like` and output a `bool` array. This would make it fit in much better with other  functions. Is there a reason it behaves the way it does?

**Comment by eric-wieser** [comment]
Are you looking for `np.unpack_bits`?

**Comment by eric-wieser** [comment]
[`binary_repr`](https://github.com/numpy/numpy/blob/v1.14.2/numpy/core/numeric.py#L1957-L2064) does more than `bin` does - it allows for fixed-width binary numbers, and printing sign bits.

**Comment by oscardssmith** [comment]
From what I can see `unpack_bits`" Unpacks elements of a uint8 array into a binary-valued output array."
What if I want an array of `unint64`?s
