### ISSUE TITLE
Link from numpy.org to tutorial is broken (404)

### ISSUE THREAD

**Issue by jruere** [numpy/numpy#10942]
The URL referenced is: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

**Comment by charris** [comment]
Yeah, I cannot figure out where the source for that is located. @rgommers @pv Do you know?

**Comment by pv** [comment]
Source of which page?
Do you mean this: https://github.com/numpy/numpy.org

**Comment by charris** [comment]
The source for this page https://docs.scipy.org/doc/.

**Comment by pv** [comment]
https://github.com/scipy/docs.scipy.org  (There is a pattern :)

**Comment by mattip** [comment]
also https://github.com/scipy/docs.scipy.org/pull/17
