### ISSUE TITLE
Is numpy GCC 8 ready

### ISSUE THREAD

**Issue by eigenwillig** [numpy/numpy#10952]
As [GCC 8 is coming](https://gcc.gnu.org/gcc-8/changes.html) numpy should verify whether is it supports the gcc 8 libs.

**Comment by juliantaylor** [comment]
its working fine on my system, no test issues, no new warnings

**Comment by eigenwillig** [comment]
According to ldd /usr/lib/python3.6/site-packages/numpy/random/mtrand.cpython-36m-x86_64-linux-gnu.so is not linking to gcc?

```
	linux-vdso.so.1 (0x00007ffd431a0000)
	libpython3.6m.so.1.0 => /usr/lib/libpython3.6m.so.1.0 (0x00007f5df4eb1000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f5df4c93000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f5df48d8000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f5df46d4000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f5df44d1000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f5df413d000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f5df56ef000)
```

I'm getting issue https://github.com/numpy/numpy/issues/10307

**Comment by juliantaylor** [comment]
lets close this then, the other issue is more specific
