### ISSUE TITLE
Numpy's argsort instability

### ISSUE THREAD

**Issue by arnaldog12** [numpy/numpy#10955]
Lately,  I have been experimenting **np.argsort** (version 1.14.2, python 3.5.5) and I have realized something weird.

If you run the following code, you will get the result:

```py
In [0]: np.argsort([3]*16)
Out[0]:
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15], dtype=int64)
```

But if you make just a little change:

```py
In [1]: np.argsort([3]*17)
Out[1]:
array([ 0, 14, 13, 12, 11, 10,  9, 15,  8,  6,  5,  4,  3,  2,  1,  7, 16], dtype=int64)
```

I know the default method for *numpy argsort* is *quicksort*, which is an unstable sorting algorithm. But, **there is an reasonably explanation about the differents behavior above? Is this related to quicksort's choice of pivot? If so, why?**

**Comment by hameerabbasi** [comment]
Numpy doesn't use quicksort by default, it uses introsort, which starts with quicksort and switches to mergesort when that becomes too slow, for a worst-case runtime of `O(n log n)`. This is mentioned a bit further down in the docs. I can't tell without extensive debugging, but I'm pretty sure what you're seeing is that for `[3] * 16`, mergesort is being used, but for `[3] * 17`, quicksort is triggered.

**Comment by jaimefrio** [comment]
It's actually even simpler: if the subarray being sorted has more than 16 items (https://github.com/numpy/numpy/blob/master/numpy/core/src/npysort/quicksort.c.src#L62), a pivot is chosen and the array gets partitioned. If not, selection sort is used, as for small arrays it's faster than the partitioning overhead.
