### ISSUE TITLE
Numpy.power overflows with int32

### ISSUE THREAD

**Issue by ZZcat** [numpy/numpy#10964]
Numpy.power(a,b) doesn't seem to be handling large numbers properly.  
![screen shot 2018-04-23 at 7 18 48 pm](https://user-images.githubusercontent.com/9269983/39159452-30168168-472b-11e8-9660-59ac9532a3bd.png)
Maybe a bug in multiplying matrixes? 
![screen shot 2018-04-23 at 7 19 29 pm](https://user-images.githubusercontent.com/9269983/39159470-517e1eb0-472b-11e8-84ec-a5e9447bb6dd.png)
Numpy info: numpy in /Users/usernameHere/miniconda3/envs/nnseries/lib/python3.6/site-packages (1.12.1)
Update:
This seems similar to my c++ program that couldn't handle numbers larger than 2^31.  If numpy uses a c or c++, an arbitrary-length integer library may be need to handle large numbers.

**Comment by Dan-Patterson** [comment]
try t = np.arange(50., 100., 1) to cast float, your originals are int32
np.iinfo('int32')
iinfo(min=-2147483648, max=2147483647, dtype=int32)

**Comment by mattip** [comment]
duplicate of #8987, although I would expect the scalar np.power(2,100) to warn like it used to, my system numpy is 1.11.0 and I get a `RuntimeWarning('invalid value encountered in power')`. `HEAD` no longer arns

**Comment by mattip** [comment]
responding to where the warning went - the `@TYPE@_power` function used to cast to float and call `power`, now we evaluate without casting. Perhaps we could try to detect overflow in these functions, for a start we know that power(2, 100) will overflow

**Comment by ZZcat** [comment]
Update:
This seems similar to my c++ program that couldn't handle numbers larger than 2^31. If numpy uses a c or c++ they may need to get a arbitrary-length integer library to handle larger numbers.

**Comment by eric-wieser** [comment]
Numpy uses `dtype=np.int_` by default for integer arrays, which is `dtype=np.int32` or `dtype=np.int64` depending on your platform.

If you want larger integers, you should just use `dtype=np.object_`, which will use python's builtin arbitrary-length integer support.

**Comment by ZZcat** [comment]
How do we use np.object_?
`----> 1 np.power(2,100, dtype = np.object_)
TypeError: No loop matching the specified signature and casting
was found for ufunc power`

Defining dtype seems to work ...
![screen shot 2018-04-30 at 3 13 27 pm](https://user-images.githubusercontent.com/9269983/39448076-6ccda452-4c89-11e8-84ff-af7e2adaff5a.png)

**Comment by gvoysey** [comment]
@mattip +1 on detection and warning about overflows.   Especially because non-numpy `2**100` works just fine, this introduces unnecessary confusion for users.

**Comment by macbuse** [comment]
This is a related issue with np.array and powers in 3.6.6 :
K =  np.array(range(35),dtype=np.int64)
K**13 % 35 - K
should give an array of zeros but gives:

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, -16, -16, -16, -32, -13, -29])

whereas the list comprehension works fine : 
[ x**13  % 35 - x for x in range(35)]

**Comment by macbuse** [comment]
@macbuse <https://github.com/macbuse>: Your problem there is that 35**13 >
> 2**64, and your result doesn't fit in an uint64
>
> —
>

Thanks for the reply.

Sure I put the dtype in to force int64 after I got the error without
specifying the dtype.
My issue is that I expected this snippet to fail  with an overflow  warning.

**Comment by seberg** [comment]
As noted, overflows are expected, so that part of the issue is simply a problem of knowing about integer precision.  The `object` case may have been a but at some point, but it works now.

Detecting integer overflows may be nice, but there are other (more general) issues about that, so closing.
