### ISSUE TITLE
Document PyArray_GETITEM / PySequence_GetItem discrepancy

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#10966]
Even for 1-D Arrays, `PyArray_GETITEM` returns something different from `PySequence_GetItem`: `PyArray_GETITEM` returns standard Python types while `PySequence_GetItem` returns the corresponding Numpy scalar types. This should be documented to avoid confusion.

**Comment by yugkhanna** [comment]
I would like to take this issue up.

**Comment by mattip** [comment]
Great, welcome. Please follow the [developer worklow](http://www.numpy.org/devdocs/dev/gitwash/development_workflow.html). You can see the rendered c-api documentation [here](http://www.numpy.org/devdocs/reference/c-api.array.html), this is created from the text file doc/source/reference/c-api.array.rst.

**Comment by yugkhanna** [comment]
I am absolutely new to this. So I should just modify the PyArray_GETITEM in the text file? @mattip

**Comment by yugkhanna** [comment]
https://github.com/numpy/numpy/pull/11914

This is the PR. Please review :)

**Comment by eric-wieser** [comment]
@pitrou: Is the change in https://github.com/numpy/numpy/pull/11914/files enough for you to consider this done, or are you after more?

**Comment by pitrou** [comment]
@eric-wieser Looks good to me, thank you.
