### ISSUE TITLE
Is numpy+mkl faster than numpy?

### ISSUE THREAD

**Issue by reaCodes** [numpy/numpy#10965]
If numpy+mkl is faster, how much faster is it than numpy?
I can't feel the difference in their speed.
Because I need to install Scipy, I must install numpy+mkl version. I found that numpy+mkl's installation package is much larger than numpy's.

Note: I am using Windows 10 on Intel's CPU.

**Comment by matthew-brett** [comment]
I guess you are using Christoph Gohlke's wheels?

I think you will find that you can use standard pip packages now for numpy and scipy.

These standard pip packages are linked to OpenBLAS.  My general impression is that OpenBLAS is in the same ballpark for speed as MKL, but I'm happy to be corrected.

**Comment by reaCodes** [comment]
@matthew-brett 
Yes, I am using Christoph Gohlke's wheels. 

But if I install numpy's "standard pip packages", scipy does not work on my computer. 

I can successfully install scipy using pip, but most of its functions are not working properly. For example I can't use `from scipy import fftpack`

I must install numpy+mk to make scipy work. I did not find any other solution.

**Comment by matthew-brett** [comment]
Maybe that's a clash with your previously-installed numpy-mkl?  The normal pip install works for me:

```
(py27) c:\repos>pip install numpy scipy
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/2e/91/504e434d3b95d943caab926f33dee5691768fbb622bc290a0fa6df77e
/numpy-1.14.2-cp27-none-win32.whl (9.8MB)
    100% |################################| 9.8MB 2.2MB/s
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/8b/cc/5644cc13ce917198d3a7a1e7ce921cd485e36a6c9f8022c79ea6930f0
/scipy-1.0.1-cp27-none-win32.whl (26.4MB)
    100% |################################| 26.4MB 906kB/s
Installing collected packages: numpy, scipy
Successfully installed numpy-1.14.2 scipy-1.0.1

(py27) c:\repos>python -c "from scipy import fftpack"

```

**Comment by reaCodes** [comment]
I don't know why, but now it does work!

![image](https://user-images.githubusercontent.com/13817254/39184290-754e34cc-47f5-11e8-968e-ec31d32355b3.png)

**Comment by reaCodes** [comment]
@matthew-brett When does numpy start to be linked to OpenBLAS? I can't search for any relevant information.

**Comment by seberg** [comment]
Just to note, the differences are only really relevant for linear algebra in any case. In any case, Matti is right it is not an issue, so closing.
