### ISSUE TITLE
Rounding digits

### ISSUE THREAD

**Issue by smoneck** [numpy/numpy#10963]
```
>>> np.round([1.0, 1.718281828459045],12)
array([1.        , 1.71828183])
```
numpy '1.14.2'

**Comment by smoneck** [comment]
Ah! Hm ... Then the intricate part lies somewhere else.

```python
  for i in range( 1, Nx ):
    for j in range( Nx-1, i - 1 , -1 ):
      a[j] = np.round( ( a[j] - a[j-1] ) / ( x[j] - x[j-i] ), precision )
  
  for i in range( 1, Nx ):
    for j in range( Nx-1, i - 1 , -1 ):
      b[j] = ( b[j] - b[j-1] ) / ( x[j] - x[j-i] )

  b = np.round(b, precision)
  
  print(a)
  print(b)
  print(a==b)
```

gives 

```
[1.0, 1.107013790801, 0.612739766513, 0.226103790562, 0.062575003589, 0.013854278366]
[1.         1.10701379 0.61273977 0.22610379 0.062575   0.01385428]
[ True  True False False False False]
```
The upper version works as expected. The lower one is causing the worries.

**Comment by ahaldane** [comment]
Aren't they expected to be different? In the top loop you are rounding on each iteration, so the rounding error propagates as you go. In the bottom loop there is no rounding, so no error accumulation, and then you round at the end.

**Comment by smoneck** [comment]
Certainly! *headtotable*

Thank you! It was too late ...
