### ISSUE TITLE
GCC_4.3.0 version required for libgfortran.so.3

### ISSUE THREAD

**Issue by petronemilio** [numpy/numpy#10972]
I've been struggling to correctly load numpy in python. I need it to run Trinity RNA-seq assembler (https://github.com/trinityrnaseq/trinityrnaseq/wiki). When I open python2.7 in the terminal to import numpy I get the following error:   
   ``python -c 'import numpy; numpy.test()``
   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
       from . import add_newdocs
      File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
       from numpy.lib import add_newdoc
      File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 19, in <module>
       from .polynomial import *
      File "/usr/local/lib/python2.7/dist-packages/numpy/lib/polynomial.py", line 20, in <module>
       from numpy.linalg import eigvals, lstsq, inv
      File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/__init__.py", line 51, in <module>
       from .linalg import *
      File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 31, in <module>
       from numpy.linalg import lapack_lite, _umath_linalg
    ImportError: /usr/local/lib/libgcc_s.so.1: version `GCC_4.3.0' not found (required by > /usr/lib/x86_64-linux-gnu/libgfortran.so.3)``

I have a GCC 4.8.4 version.  Gfortran is configured in this way:
    Using built-in specs.
    COLLECT_GCC=gfortran
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.4' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu

**Comment by eigenwillig** [comment]
Just recompile with fresh GCC including _your BLAS library_!

**Comment by petronemilio** [comment]
That solve my problem. I leave GCC only in one folder an made a new compilation.

Thanks!
