### ISSUE TITLE
Mean Precision

### ISSUE THREAD

**Issue by Alexander-Shukaev** [numpy/numpy#10979]
```
>>> (238.00003776 + 238.00003776 + 238.00003776) / 3
238.00003776000003
>>> (238.00003776 + 238.00003776 + 238.00003776) * (1.0 / 3.0)
238.00003776
```

The `numpy.mean` function most probably does something similar to the first case (i.e. division).  Don't you think it's a potential problem?

**Comment by seberg** [comment]
The first case is more precise, so obviously no. Just because you happen to find a reason where it is off more, does not make it so in general.
