### ISSUE TITLE
unexpected result when subtracting an array from a set

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#10976]
Py3.6.5, np1.14.2
```
In [1]: {1} - np.array([])
Out[1]: array([], dtype=object)
```
I was hoping to compute a set difference, but accidentally passed an array (yes, I know, `{1} - [2]` doesn't work either.  So this should either fail with TypeError (as subtracting a list does, or trigger broadcasting (treating the set as an iterable).  Looks like it's the second one, which is a bit nonobvious, but I understand the preference to avoid special casing some iterables (sets) from numpy's PoV.
But
```
In [2]: {1} - np.array([2])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-39c5c8a06b33> in <module>()
----> 1 {1} - np.array([2])

TypeError: unsupported operand type(s) for -: 'set' and 'int'
```
so it's not broadcasting either.

**Comment by eric-wieser** [comment]
It looks like `{1}` is being promoted to a 0d array, `array({1}, dtype=object)`, which seems pretty reasonable to me.

In your first case, broadcasting happens between this shape `()` array and the shape `(0,)` empty array, which results in calling `-` 0 times

In the second case, broadcasting happens between this shape `()` array and the shape `(1,)` array, which results in calling `-` 1 times (which fails.

The only part of this that seems non-obvious to me is the automatic conversion of `{1}` to `np.array({1}, object)`.

**Comment by anntzer** [comment]
Ah, sounds "fair" (at least it matches the rules, even though they have some nonobvious consequences here).
Feel free to close.

**Comment by seberg** [comment]
Going to close this, it does seem somewhat fair.  I guess this is another data point for rejecting all `iterables` in automatic `dtype=object` coercion.  So that this would give an error.
