### ISSUE TITLE
SVG logo doesn't appear in README on GitHub

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#11000]
<img width="1552" alt="screen shot 2018-04-28 at 15 39 42" src="https://user-images.githubusercontent.com/3019665/39400224-69c98d56-4afa-11e8-96e7-c0b08838742d.png">

**Comment by eric-wieser** [comment]
Looks like it's being sanitized by github somehow:

https://raw.githubusercontent.com/numpy/numpy/master/branding/icons/numpylogo.svg?sanitize=true

vs

https://raw.githubusercontent.com/numpy/numpy/master/branding/icons/numpylogo.svg
