### ISSUE TITLE
`np.random.permutation` & `np.random.shuffle` are slow.

### ISSUE THREAD

**Issue by colinfang** [numpy/numpy#11013]
`np.random.permutation(x)` is the same as `x[np.random.permutation(x.shape[0])]` semantically if `x` is an array. Why the latter is so much faster than the former?

```python
    x = np.random.rand(50000, 2)
    %timeit x.take(np.random.permutation(x.shape[0]), axis=0)
    # 1.02 ms
    %timeit x[np.random.permutation(x.shape[0])]
    # 1.75 ms
    %timeit np.random.permutation(x)
    # 34.1 ms
    %timeit np.random.shuffle(x)
    # 34.2 ms
```

**Comment by bashtage** [comment]
`shuffle` has a general path for any like-like object and a fat path for 1-d NumPy Arrays.

From shuffle:
```
        if type(x) is np.ndarray and x.ndim == 1 and x.size:
            # Fast, statically typed path: shuffle the underlying buffer.
            # Only for non-empty, 1d objects of class ndarray (subclasses such
            # as MaskedArrays may not support this approach).
```

**Comment by eric-wieser** [comment]
It surprises me that semantically these cases are even the same - I assumed that `np.shuffle(x)` would shuffle along the first axis in the same way that `sort()` does - by treating each 1D slice separately. It seems that this is not how it works.
