### ISSUE TITLE
UnpicklingError: invalid load key, 'n'.

### ISSUE THREAD

**Issue by ikrambennasrbennasr** [numpy/numpy#11017]
hello, i run this code : 

from keras.models import model_from_json
exp_number = 13
output_architecture = '/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/convnet_architecture_exp' + str(exp_number) + '.json'
best_weights_during_run = '/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/weights_exp' + str(exp_number) + '.h5'
final_weights = '/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/weights_exp' + str(exp_number) + '_final.h5'
model = model_from_json(open(output_architecture).read())
model.load_weights(best_weights_during_run)
model.compile(loss='mean_squared_error', optimizer='sgd')
model.summary()
from keras.models import model_from_json
exp_number = 13
from scipy import *
from numpy import *
import theano
import cPickle as pickle 
from numpy.core import multiarray
losses = pickle.load( open('/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/history_exp' + str(exp_number) + '.pickle'   , 'rb'))
test_set = pickle.load(open('/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/TestSet.pickle', 'rb'))
X_test = test_set['X_test']
Y_test = test_set["Y_test"]  

and i get the followinf error : 
UnpicklingError                           Traceback (most recent call last)
<ipython-input-7-46cb7977ad4c> in <module>()
     26 losses = pickle.load( open('/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/history_exp' + str(exp_number) + '.pickle'   , 'rb'))
     27 # load the test set
---> 28 test_set = pickle.load(open('/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/TestSet.pickle', 'rb'))
     29 
     30 X_test = test_set['X_test']

UnpicklingError: invalid load key, 'n'.

Can someone help me please

**Comment by ikrambennasrbennasr** [comment]
@mattip thanks for the response. In fact I did not create the test set file but I'm trying to implement the CNN algorithm and this file is already created : https://github.com/tperol/neuralnilm/tree/master/tmpdata

**Comment by ikrambennasrbennasr** [comment]
also I wonder why the command that precedes it directly runs and that one, no

**Comment by mattip** [comment]
Your best bet would be to directly contact the author, hopefully they will respond

**Comment by ikrambennasrbennasr** [comment]
@mattip  thanks for you and for the time that you have put to answer me

**Comment by mattip** [comment]
Closing, I hope you were able to solve the problem. Please reopen if there is more NumPy can do here.
