### ISSUE TITLE
What are np.int0 and np.uint0 supposed to be?

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#11025]
Some archaelogy shows that 618a8d472a36506eb5848009f10585f7c63da799 seems to have taken it from Numeric, which provided `Int0`.

Numeric's `IntN` seemed to mean meaning C99s `int_leastN_t`, suggesting that `Int0` should be `signed char`.

So why is `np.int0` an alias of `np.intp`?

**Comment by rkern** [comment]
In Numeric, `Int0` is indeed equivalent to `Int8`. There's no real reason for it to exist at all, though, fixed or unfixed. I don't recommend using it. Or letting its anomalous existence bother you much. :-)

**Comment by seberg** [comment]
I will close this in favor of the new gh-15334 (renaming it as a documentation and/or deprecation) not that it matters which one is open. Included the info about `int8` there.

**Comment by ramenspazz** [comment]
But if there is no reason for it to exist, can I delete it safely? I don't want things with no purpose even if you want me to keep them if they have no purpose...
