### ISSUE TITLE
RuntimeWarning for np.array with NaN

### ISSUE THREAD

**Issue by chapochn** [numpy/numpy#11029]
When i run the code
`A = np.full(7, np.nan)`
there is no issue.

When i run
`A = np.full(8, np.nan)`
and for any array larger than that, i get the warnings:

> /mnt/home/[...]/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
>   return umr_minimum(a, axis, None, out, keepdims)
> /mnt/home/[...]/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
>   return umr_maximum(a, axis, None, out, keepdims)

i use spyder 3.2.6, python 3.6.4, numpy 1.14.0
I have this warning on one of my computers (running CentOS Linux 7), but not on the other (running Ubuntu 16.04)
Cannot figure out where the different comes from. Any ideas?

**Comment by tzickel** [comment]
Did you install numpy from pip install or using the package manager of your distribution (in both cases)

**Comment by mattip** [comment]
This seems strange to me, can anyone reproduce? `np.full()` should not be calling `umr_minimum`, `umr_maximum`. Perhaps there is something else going on with the way Spyder is displaying `A` in its workspace browser, which is calling `np.min(A), np.max(A)`, which indeed would connect it to #10370 and pr #11043 ?

**Comment by mattip** [comment]
How do we label third-party issues reported here?

**Comment by chapochn** [comment]
@tzickel i installed in both cases using anaconda.
It seems it is indeed a spyder related issue, as when i run the same commands in an ipython terminal, no warning appears

**Comment by NotSqrt** [comment]
I reported the same behaviour in https://github.com/numpy/numpy/issues/10370#issuecomment-361579169

**Comment by NotSqrt** [comment]
Until numpy==1.14.3, there was no RuntimeWarning for `numpy.min(numpy.full((7,), numpy.nan, dtype=numpy.float64))`.

With numpy==1.14.4, there's a RuntimeWarning for that case.

**Comment by mattip** [comment]
There was a bug that not only didn't warn, it sometimes and on some platforms ignored the `nan`. The warning is needed whenever we propagate an invalid value, no?  It is up to the user to ignore those (or not) using any of the warning handling mechanisms in python or `numpy.seterr`

**Comment by mattip** [comment]
The issue was in spyder, and was fixed there.
