### ISSUE TITLE
Polynome integer error

### ISSUE THREAD

**Issue by scootty1** [numpy/numpy#11035]
## Description
While making a 10th-degree polyfit for some thermodynamic data, I stumbled upon an error while feeding an int32 array to the polynome function. For most integer input arrays the polynome returns incorrect values while float arrays seem to return good results.
## code to reproduce the error
This polynome is fitted for `-30 <= t <= 100`. Integer arrays as input only return correct results in the range of `-10 <= t <= 10`.
```
def poly10(t):
    return (- 1.30339138e-16*t**10 + 7.49527386e-14*t**9 - 1.59881730e-11*t**8
            + 1.54764869e-09*t**7 - 5.56609536e-08*t**6 + 1.46597641e-06*t**5
            + 4.21883898e-04*t**4 + 2.43290034e-02*t**3 + 1.38204573e+00*t**2
            + 4.58581434e+01*t + 6.02909924e+02)
```
```
t_int = np.arange(73, 75) 
poly10(t_int)
Out[3]: array([35744.64386573, 30976.45981835])
```
## expected output
Using an float64 array, the output is as expected:
```
t_float = np.arange(73, 75).astype(float)
poly10(t_float)
Out[5]: array([35432.40549908, 36962.19541186])
```

Python 3.6.5, Numpy 1.14.2

**Comment by charris** [comment]
The `**` operators has precedence, so you are raising integers to high powers and undoubtedly encountering overflow. Don't use integers for these things. For that range and powere, you would also be better using the Polynomial class for the fitting.

**Comment by scootty1** [comment]
Ok, thanks for that advice. Interestingly numpy doesn't raise an overflow warning, which I usually get when I encounter overflows.
I'll take a look into the Polynomial class, thanks!
