### ISSUE TITLE
numpy.genfromtxt : cannot read indices when dtype=None or specified explicitly

### ISSUE THREAD

**Issue by srdg** [numpy/numpy#11039]
Sorry in advance if this is a duplicate. I'm trying to read the [Iris dataset](https://www.kaggle.com//uciml/iris) using the following code: 
`data = numpy.genfromtxt('../input/Iris.csv',delimiter=',',usecols= range(1,6),skip_header=1, dtype = None)`.
However, when I try to separate the features and labels using this - 
`features = data[:,:-1]`
`labels = data[:,-1:]`
the following error occurs : 
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-48-a596c22da600> in <module>()
----> 1 features = data[:,:-1]
      2 features.shape

IndexError: too many indices for array

```
This error also persists when I use the following :
```
data = np.genfromtxt('../input/Iris.csv',delimiter=',',usecols= range(1,6),skip_header=1,dtype={'names': ('sepal length', 'sepal width', 'petal length', 'petal width', 'label'),
          'formats': (np.float, np.float, np.float, np.float, '|S15')})
```
However, this kind of indexing works fine when I do not pass `dtype` as argument at all, but the only problem with that is the labels are read as `NaN` , which cannot be processed further to numerically encode separately.

**Comment by ahaldane** [comment]
That appears to be the expected behavior, according to the docstring and the [user guide (link)](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.io.genfromtxt.html#choosing-the-data-type).

By default it will try to make a 2d float array. If you specify `dtype=None` it more carefully chooses the dtype, which in this case leads to a 1d strctured array.

By the way, it may be easier/better to use pandas rather than numpy itself if you want to do tabular data analysis - pandas is specifically designed for that purpose.

**Comment by srdg** [comment]
@ahaldane Is there a way where I could change the 1D to 2D while calling the function, or perhaps,  using `numpy.reshape()` later?

**Comment by ahaldane** [comment]
Hard to answer - it depends on your goals and requirements. Why is setting `dtype=float` (ie, the default) not good enough? Why are you setting `dtype=None`?

It's hard to make out what you are thinking from over here, but I would like to emphasize again that numpy is not really designed for tabular data analysis. If your columns are of different types, as you seem to suggest they are, then numpy fundamentally cannot represent it as a 2d array. In that case I highly suggest using pandas.

**Comment by srdg** [comment]
@ahaldane Please refer to the last part of my original issue : I wanted to load the data and labels together, shuffle them, and index the strings in some numeric format. Since it's a bit of a pain to do in `numpy`, I'll use `pandas` rather, thanks for the suggestion. Closing this issue since it's really not one.
