### ISSUE TITLE
1.14.3 - "Importing the multiarray numpy extension module failed" when building doc

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#11049]
Hello,
i'm working to package numpy 1.14.3 for debian, and during our building process numpy fails when building the documentation. the doc build command and error are as follow:

```
make -C doc html PYTHON=python3 PYTHONPATH=../build/lib.linux-x86_64-3.6
make[1]: Entering directory '/home/morph/deb/build-area/python-numpy-1.14.3/doc'
mkdir -p build
touch build/generate-stamp
mkdir -p build/html build/doctrees
LANG=C sphinx-build -b html -d build/doctrees   source build/html 
Running Sphinx v1.7.4

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 47, in <module>
    import numpy
  File "/home/morph/deb/build-area/python-numpy-1.14.3/build/lib.linux-x86_64-3.6/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/morph/deb/build-area/python-numpy-1.14.3/build/lib.linux-x86_64-3.6/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/morph/deb/build-area/python-numpy-1.14.3/build/lib.linux-x86_64-3.6/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/morph/deb/build-area/python-numpy-1.14.3/build/lib.linux-x86_64-3.6/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/morph/deb/build-area/python-numpy-1.14.3/build/lib.linux-x86_64-3.6/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray
```

(we need to use PYTHONPATH to point at the just built version of numpy)

which is weird, because i can import multiarray just fine:

```
morph@zion:~/deb/build-area/python-numpy-1.14.3/doc$ PYTHONPATH=../build/lib.linux-x86_64-3.6 python3
Python 3.6.4 (default, Jan  5 2018, 02:13:53) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy.core.multiarray
>>> numpy.core.multiarray.__file__
'/home/morph/deb/build-area/python-numpy-1.14.3/build/lib.linux-x86_64-3.6/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so'
>>> 
```

any idea what's going on here?

thanks!

**Comment by charris** [comment]
Did 1.14.2 work? I don't see anything in 1.14.3 that should affect documentation. Usually that error is caused be an installation problem. Did you start with a clean repo?

**Comment by sandrotosi** [comment]
i didnt try 1.14.2 (i was a bit behind with tracking releases for debian so we're bumping from 1.13.3 to 1.14.3); our packaging process unpacks the tarball we fetched from PyPI, add the debian customizations and then build hte package, so we do start from a clean env yes.

the fact that's importable by hand maybe signifies it's an import order issue (wild guess)? anything i can do to understand what's going on?

**Comment by pv** [comment]
Note that the sphinx-build is running on Python 2.7 and it's trying to import numpy from python 3.6 pythonpath. Maybe set `make PYVER=3.6` (check the makefile for details on what it does).

**Comment by sandrotosi** [comment]
OMG i feel so stupid to have missed that! :( lemme test some stuff

**Comment by sandrotosi** [comment]
ok, this is fixed: it turns out it was a configuration hiccup in Debian where if you have both py2 and py3 sphinx packages installed, the py2 scripts (like sphinx-build) are preferred over py3; but since there's a push in Debian to build doc via py3 sphinx, it should be the other way around.

sorry for the noise and thanks for the buick help!
