### ISSUE TITLE
numpy 1.14.3: f2py.1 no longer available

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#11052]
hello,
it looks like f2py documentation has been reorganized between 1.13.3 and 1.14.3, and now the manpage `f2py.1` is no longer available in the git repo (and thus also in the PyPI tarball) - any reason for this change or was it simply lost in the reorg?

thanks!

**Comment by charris** [comment]
@sandrotosi To be clear, you are looking for a manpage? Most to of the content looks to be available in `doc/f2py/source/usage.rst`

**Comment by sandrotosi** [comment]
not necessarily, it's more like: it used to be there, there was no apparent reason to remove it (unless it was out-of-date and there is no easy way to keep it up-to-date instead), in Debian we like to ship manpages for command-line tools as people often prefer `man <cmd>` than opening a browser and find the doc, and so on.

if it's gone for good, i will simply remove the code to install it and configure it for debian

**Comment by charris** [comment]
@sandrotosi  The file was removed in #9264. If you have a good workaround, that is the way to go. If you need a man page, we can probably do something about that, although I cannot think of anything else for which we have a manpage. I note that Fedora 27, which comes with 1.13 also has the f2py man page. We should probably do something about restoring it.

**Comment by sandrotosi** [comment]
no problem for now, i commented out the steps to install that manpage: if you end up restoring it, i'll uncomment them again, if you decide not to ship a manpage, i'll remove them.

this ticket is more to understand what happened to the manpage and if its removal was intentional

**Comment by charris** [comment]
We could just drop it into `doc/source/f2py`, or even make a `doc/manpage` directory. Might be worth raising the issue on the list to see what people think.

**Comment by pv** [comment]
I guess sphinx in principle can produce manpages (in case someone wants
to make it work):
http://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-manual-page-output
http://www.sphinx-doc.org/en/master/man/

**Comment by melissawm** [comment]
Is this something we still want to do? I'm guessing since this hasn't been brought up in a while that we don't need the man page, and this issue can be closed.

**Comment by sandrotosi** [comment]
i would still like to have a manpage associated with the tool, at least that's what we prefer in Debian to have (but it's definitely not a strong requirement)

**Comment by HaoZeke** [comment]
Since we ended up dropping `pdf` generation, I would assume the `man` page generation is very low prio, especially since either:
- We use a library which does the `man` page generation more or less automatically (e.g. `click` has [click-man](https://github.com/click-contrib/click-man)
- We maintain it by hand (very unlikely)

For (1) I think it is essentially covered by #24552, so I'm closing this for now.
