### ISSUE TITLE
Building a wheel with fails to include extension modules in the wheel

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#11062]
`pip wheel .`, or `python setup.py bdist_wheel`, from a source checkout of numpy==1.14.3, or `pip wheel numpy-1.14.3.zip` after manually downloading the sdist, both produce a numpy-1.14.3-....whl that does not include the extension modules (e.g. multiarray) in the wheel.

versions:
python 3.6.5 on Arch Linux (system python)
setuptools 39.1.0
wheel 0.31.0
pip 9.0.3

**Comment by eric-wieser** [comment]
Does `python setup.py build bdist_wheel` work?

**Comment by anntzer** [comment]
It fails likewise on the 1.14.3 checkout (after running git clean -xdf first, just to be sure).

**Comment by anntzer** [comment]
Right now I think it's an issue with `wheel`, see https://github.com/pypa/wheel/issues/241.
