### ISSUE TITLE
Numby pip installation problem

### ISSUE THREAD

**Issue by hawk20002000** [numpy/numpy#11070]
Hi all

I am new to Linux and Python and having problems installing numpy (actually I want to install picamera which needs numpy).

Im am Running:

Raspberry pi 3B
Raspbian Stretch 9.4

There already is a version of numpy installed when I check with python:

>>> import numpy
>>> numpy.version.version
'1.12.1'
>>> 

This is the output of the installation.

pip install "picamera[array]"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting picamera[array]
  Downloading https://files.pythonhosted.org/packages/79/c4/80afe871d82ab1d5c9d8f0c0258228a8a0ed96db07a78ef17e7fba12fda8/picamera-1.13.tar.gz (143kB)
    100% |################################| 153kB 4.1MB/s 
Collecting numpy (from picamera[array])
  Using cached https://files.pythonhosted.org/packages/b0/2b/497c2bb7c660b2606d4a96e2035e92554429e139c6c71cdff67af66b58d2/numpy-1.14.3.zip
Building wheels for collected packages: picamera, numpy
  Running setup.py bdist_wheel for picamera ... done
  Stored in directory: /home/pi/.cache/pip/wheels/61/e2/56/0bc656389730dea8038d226fe0fd6d724e9feedd4817ef8311
  Running setup.py bdist_wheel for numpy ... error
  Complete output from command /home/pi/.virtualenvs/cv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-QuQdfD/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-cpufJW --python-tag cp27:
  Running from numpy source directory.
  blas_opt_info:
  blas_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  blis_info:
  customize UnixCCompiler
    libraries blis not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  openblas_info:
  customize UnixCCompiler
  customize UnixCCompiler
    libraries openblas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
  customize UnixCCompiler
    libraries tatlas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib/atlas-base', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  atlas_3_10_blas_info:
  customize UnixCCompiler
    libraries satlas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib/atlas-base', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib/atlas-base', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  atlas_blas_info:
  customize UnixCCompiler
  get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
  customize Gnu95FCompiler
  Found executable /usr/bin/gfortran
  customize UnixCCompiler
  customize UnixCCompiler
    FOUND:
      libraries = ['f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
      library_dirs = ['/usr/lib/atlas-base']
      language = c
      define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
      include_dirs = ['/usr/include/atlas']
  
    FOUND:
      libraries = ['f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
      library_dirs = ['/usr/lib/atlas-base']
      language = c
      define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
      include_dirs = ['/usr/include/atlas']
  
  svnversion: warning: cannot set LC_CTYPE locale
  svnversion: warning: environment variable LC_ALL is en_US.UTF-8
  svnversion: warning: please check that your locale name is correct
  non-existing path in 'numpy/distutils': 'site.cfg'
  svnversion: warning: cannot set LC_CTYPE locale
  svnversion: warning: environment variable LC_ALL is en_US.UTF-8
  svnversion: warning: please check that your locale name is correct
  F2PY Version 2
  lapack_opt_info:
  lapack_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  openblas_lapack_info:
  customize UnixCCompiler
  customize UnixCCompiler
    libraries openblas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  openblas_clapack_info:
  customize UnixCCompiler
  customize UnixCCompiler
    libraries openblas,lapack not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
    NOT AVAILABLE
  
  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /home/pi/.virtualenvs/cv/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /home/pi/.virtualenvs/cv/lib
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/lib/atlas-base
  customize UnixCCompiler
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/lib
  customize UnixCCompiler
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
  customize UnixCCompiler
    libraries satlas,satlas not found in /home/pi/.virtualenvs/cv/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /home/pi/.virtualenvs/cv/lib
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/lib/atlas-base
  customize UnixCCompiler
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/lib
  customize UnixCCompiler
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE
  
  atlas_threads_info:
  Setting PTATLAS=ATLAS
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /home/pi/.virtualenvs/cv/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /home/pi/.virtualenvs/cv/lib
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/atlas-base
  customize UnixCCompiler
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  customize UnixCCompiler
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE
  
  atlas_info:
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /home/pi/.virtualenvs/cv/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /home/pi/.virtualenvs/cv/lib
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
  customize UnixCCompiler
  customize UnixCCompiler
  <class 'numpy.distutils.system_info.atlas_info'>
  customize UnixCCompiler
  get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
  customize Gnu95FCompiler
  customize UnixCCompiler
  customize UnixCCompiler
    FOUND:
      libraries = ['lapack', 'f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
      library_dirs = ['/usr/lib/atlas-base/atlas', '/usr/lib/atlas-base']
      language = f77
      define_macros = [('NO_ATLAS_INFO', -1)]
      include_dirs = ['/usr/include/atlas']
  
    FOUND:
      libraries = ['lapack', 'f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
      library_dirs = ['/usr/lib/atlas-base/atlas', '/usr/lib/atlas-base']
      language = f77
      define_macros = [('NO_ATLAS_INFO', -1)]
      include_dirs = ['/usr/include/atlas']
  
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build/src.linux-armv7l-2.7
  creating build/src.linux-armv7l-2.7/numpy
  creating build/src.linux-armv7l-2.7/numpy/distutils
  building library "npymath" sources
  get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
  customize Gnu95FCompiler
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-QuQdfD/numpy/setup.py", line 394, in <module>
      setup_package()
    File "/tmp/pip-install-QuQdfD/numpy/setup.py", line 386, in setup_package
      setup(**metadata)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build.py", line 47, in run
      old_build.run(self)
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build_src.py", line 148, in run
      self.build_sources()
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build_src.py", line 159, in build_sources
      self.build_library_sources(*libname_info)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build_src.py", line 294, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
      source = func(extension, build_dir)
    File "numpy/core/setup.py", line 673, in get_mathlib_info
      st = config_cmd.try_link('int main(void) { return 0;}')
    File "/usr/lib/python2.7/distutils/command/config.py", line 248, in try_link
      self._check_compiler()
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/config.py", line 81, in _check_compiler
      c_compiler=self.compiler)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 873, in new_fcompiler
      c_compiler=c_compiler)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 847, in get_default_fcompiler
      c_compiler=c_compiler)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 794, in _find_existing_fcompiler
      c.customize(dist)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 499, in customize
      get_flags('opt', oflags)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 490, in get_flags
      flags.extend(getattr(self.flag_vars, tag))
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/environment.py", line 39, in __getattr__
      return self._get_var(name, conf_desc)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/environment.py", line 53, in _get_var
      var = self._hook_handler(name, hook)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 697, in _environment_hook
      return hook()
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/gnu.py", line 233, in get_flags_opt
      v = self.get_version()
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 428, in get_version
      version = CCompiler.get_version(self, force=force, ok_status=ok_status)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/ccompiler.py", line 627, in CCompiler_get_version
      version = matcher(output)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/gnu.py", line 270, in version_match
      v = self.gnu_version_match(version_string)
    File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/gnu.py", line 83, in gnu_version_match
      raise ValueError(err + version_string)
  ValueError: A valid Fortran version was not found in this string:
  /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
  6.3.0
  
  ----------------------------------------
  Failed building wheel for numpy
  Running setup.py clean for numpy
  Complete output from command /home/pi/.virtualenvs/cv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-QuQdfD/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Running from numpy source directory.
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  
  ----------------------------------------
  Failed cleaning build dir for numpy
Successfully built picamera
Failed to build numpy
Installing collected packages: numpy, picamera
  Running setup.py install for numpy ... error
    Complete output from command /home/pi/.virtualenvs/cv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-QuQdfD/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kDCOeV/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.virtualenvs/cv/include/site/python2.7/numpy:
    Running from numpy source directory.
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)
    
    
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    blis_info:
    customize UnixCCompiler
      libraries blis not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries tatlas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib/atlas-base', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_3_10_blas_info:
    customize UnixCCompiler
      libraries satlas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib/atlas-base', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib/atlas-base', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_blas_info:
    customize UnixCCompiler
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    Found executable /usr/bin/gfortran
    customize UnixCCompiler
    customize UnixCCompiler
      FOUND:
        libraries = ['f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
        library_dirs = ['/usr/lib/atlas-base']
        language = c
        define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
        include_dirs = ['/usr/include/atlas']
    
      FOUND:
        libraries = ['f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
        library_dirs = ['/usr/lib/atlas-base']
        language = c
        define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
        include_dirs = ['/usr/include/atlas']
    
    svnversion: warning: cannot set LC_CTYPE locale
    svnversion: warning: environment variable LC_ALL is en_US.UTF-8
    svnversion: warning: please check that your locale name is correct
    non-existing path in 'numpy/distutils': 'site.cfg'
    svnversion: warning: cannot set LC_CTYPE locale
    svnversion: warning: environment variable LC_ALL is en_US.UTF-8
    svnversion: warning: please check that your locale name is correct
    F2PY Version 2
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/home/pi/.virtualenvs/cv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /home/pi/.virtualenvs/cv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/.virtualenvs/cv/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/atlas-base
    customize UnixCCompiler
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    customize UnixCCompiler
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries satlas,satlas not found in /home/pi/.virtualenvs/cv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/.virtualenvs/cv/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/atlas-base
    customize UnixCCompiler
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    customize UnixCCompiler
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /home/pi/.virtualenvs/cv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/.virtualenvs/cv/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/atlas-base
    customize UnixCCompiler
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    customize UnixCCompiler
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /home/pi/.virtualenvs/cv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /home/pi/.virtualenvs/cv/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
    customize UnixCCompiler
    customize UnixCCompiler
    <class 'numpy.distutils.system_info.atlas_info'>
    customize UnixCCompiler
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    customize UnixCCompiler
    customize UnixCCompiler
      FOUND:
        libraries = ['lapack', 'f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
        library_dirs = ['/usr/lib/atlas-base/atlas', '/usr/lib/atlas-base']
        language = f77
        define_macros = [('NO_ATLAS_INFO', -1)]
        include_dirs = ['/usr/include/atlas']
    
      FOUND:
        libraries = ['lapack', 'f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
        library_dirs = ['/usr/lib/atlas-base/atlas', '/usr/lib/atlas-base']
        language = f77
        define_macros = [('NO_ATLAS_INFO', -1)]
        include_dirs = ['/usr/include/atlas']
    
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-QuQdfD/numpy/setup.py", line 394, in <module>
        setup_package()
      File "/tmp/pip-install-QuQdfD/numpy/setup.py", line 386, in setup_package
        setup(**metadata)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/install.py", line 62, in run
        r = self.setuptools_run()
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build.py", line 47, in run
        old_build.run(self)
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build_src.py", line 148, in run
        self.build_sources()
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build_src.py", line 159, in build_sources
        self.build_library_sources(*libname_info)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build_src.py", line 294, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 673, in get_mathlib_info
        st = config_cmd.try_link('int main(void) { return 0;}')
      File "/usr/lib/python2.7/distutils/command/config.py", line 248, in try_link
        self._check_compiler()
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/command/config.py", line 81, in _check_compiler
        c_compiler=self.compiler)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 873, in new_fcompiler
        c_compiler=c_compiler)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 847, in get_default_fcompiler
        c_compiler=c_compiler)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 794, in _find_existing_fcompiler
        c.customize(dist)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 499, in customize
        get_flags('opt', oflags)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 490, in get_flags
        flags.extend(getattr(self.flag_vars, tag))
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/environment.py", line 39, in __getattr__
        return self._get_var(name, conf_desc)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/environment.py", line 53, in _get_var
        var = self._hook_handler(name, hook)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 697, in _environment_hook
        return hook()
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/gnu.py", line 233, in get_flags_opt
        v = self.get_version()
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/__init__.py", line 428, in get_version
        version = CCompiler.get_version(self, force=force, ok_status=ok_status)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/ccompiler.py", line 627, in CCompiler_get_version
        version = matcher(output)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/gnu.py", line 270, in version_match
        v = self.gnu_version_match(version_string)
      File "/tmp/pip-install-QuQdfD/numpy/numpy/distutils/fcompiler/gnu.py", line 83, in gnu_version_match
        raise ValueError(err + version_string)
    ValueError: A valid Fortran version was not found in this string:
    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
    6.3.0
    
    ----------------------------------------
Command "/home/pi/.virtualenvs/cv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-QuQdfD/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kDCOeV/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.virtualenvs/cv/include/site/python2.7/numpy" failed with error code 1 in /tmp/pip-install-QuQdfD/numpy/

I tried lots of different solutions I found on google nothing did help in my case:

It seems my fortran version 6.3.0 is not compatible but I tried updating/reinstalling the build essential package. Can someone please help me ? I m a little lost 😁Thanks!

**Comment by mattip** [comment]
Did you try `sudo apt-get install python-picamera python3-picamera`? Compiling numpy is probably not the best advice on that platform. In any case, you will want to [set up your locale properly](https://askubuntu.com/questions/114759/warning-setlocale-lc-all-cannot-change-locale), that warning is confusing the fortran version parser.

**Comment by hawk20002000** [comment]
Thanks this has worked so far! I did the locale setup and Picamera seems to be working with numpy, thanks!
