### ISSUE TITLE
1.14.3 on sparc64: numpy.core.tests.test_multiarray.TestMethods.test__complex__should_not_work ... Bus error

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#11088]
Hello,
when building numpy 1.14.3 on debian for sparc64 architecture, the test suite fails with:

```
numpy.core.tests.test_multiarray.TestMatmul.test_shapes ... ok
numpy.core.tests.test_multiarray.TestMatmul.test_vector_matrix_values ... ok
numpy.core.tests.test_multiarray.TestMatmul.test_vector_vector_values ... ok
numpy.core.tests.test_multiarray.TestMemEventHook.test_mem_seteventhook ... ok
numpy.core.tests.test_multiarray.TestMethods.test__complex__ ... ok
numpy.core.tests.test_multiarray.TestMethods.test__complex__should_not_work ... Bus error
```

(this is for python 2.7.15~rc1)

full log at: https://buildd.debian.org/status/fetch.php?pkg=python-numpy&arch=sparc64&ver=1%3A1.14.3-2&stamp=1525577504&raw=0

can you have a look? thanks!

**Comment by rikmills** [comment]
This also fails on Ubuntu for armhf

https://launchpad.net/ubuntu/+source/python-numpy/1:1.14.3-2ubuntu1

full log https://launchpadlibrarian.net/371898878/buildlog_ubuntu-cosmic-armhf.python-numpy_1%3A1.14.3-2ubuntu1_BUILDING.txt.gz

**Comment by ginggs** [comment]
I was able to reproduce this in 1.14.1, but not in 1.13.3.

Replacing
`        *((@type@ *)ov)=temp;`
with
`        memcpy(ov, &temp, sizeof(@type@));`
at https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arraytypes.c.src#L250
works around the problem for me, but I can't see what changed from 1.13.3 to 1.14.1; the code in **arraytypes.c.src** hasn't changed in 9 years, and **test__complex__should_not_work** hasn't changed in 2.

**Comment by charris** [comment]
The problem is probably in the `PyArray_ISBEHAVED` check, i.e., in the passed argument. It would be most helpful if you could do a bisection for this problem.

**Comment by charris** [comment]
Although it would seem that `ov` should also be checked. Is the same compiler being used for both 1.13 and 1.14?

**Comment by charris** [comment]
@seberg Thoughts?

**Comment by ginggs** [comment]
> Is the same compiler being used for both 1.13 and 1.14?
Yes, I tried 1.13 in the exact same setup as 1.14  to make sure the problem wasn't elsewhere.

I am trying 1.14.0rc1 now.

**Comment by charris** [comment]
The test itself was added in 1.12, so that wasn't the change.

**Comment by seberg** [comment]
I am not very familiar with alignment issues. I agree that the `PyArray_ISBEHAVED` should be the problem (unless that `ap == NULL` check kicks and the BEHAVED check is simply missing somewhere earlier).
We had changes to the alignment stuff before, but why it should suddenly pop up. Julian addes some asserts with the `npy_is_aligned(dst, _ALIGN(_TYPE2))` to the item setting code in lowlevel strided loops stuff, not sure if it might help with debugging?

**Comment by seberg** [comment]
OK, inserting:
```
        assert(npy_is_aligned(ov, sizeof(@type@)));
```
allows one to reproduce it on a normal computer. Please do not ask me why I need `sizeof` and `_ALGIN` does not work, I am too stupid to understand it. I am not even sure if it is correct, or just happens to crash at the right spot ;)

**Comment by ginggs** [comment]
1.14.0rc1 fails in the same way, so the problem seems to have been introduced somewhere between 1.13.3 and 1.14.0rc1.

I'll try to figure out how to bisect further, as so far I've just been building the Debian package using the different tarballs which are available.

**Comment by seberg** [comment]
@charris I think adding this assert there seems good in any case, but do you have any clue why it is not working with `_ALIGN(@type@)`? That would seem right to me, no idea if there are any differences here to be honest.

My bisect is running now (I hope), but since it has to recompile and that takes a while, might be a bit for the result (or noticing that something is wrong)

**Comment by charris** [comment]
@seberg Hey, that's a neat way to do it. The assert sounds like a good idea as the argument isn't getting checked otherwise. Not sure why the  `_ALIGN(@type@)` doesn't work, need to look over the macro implementations.

**Comment by seberg** [comment]
My bisect run said this: a3afc25089b5343b2dc7ea21add26d03fc232539 let me see if it has a point or not ;)

**Comment by seberg** [comment]
Sorry about the false alarm, fixed my script and then had a syntax error in it. Yeah, Julian came up with it, so it must be smart ;)

**Comment by charris** [comment]
I cannot see any problem with the `_ALIGN(@type@)`  macro, should work.

**Comment by seberg** [comment]
Yeah, missing git cleans in there... I hope just a matter of time now.

**Comment by seberg** [comment]
OK, my bisect finished at:
7412b85a1b4920e5b72ab694e51b11e4cb615866

**Comment by seberg** [comment]
It definitely looks like it is that commit (double checked, and the previous one -- 2afa142ae -- is good), and that commit looks like it may have something to do with it, but frankly it is also absolutely not obvious why...

**Comment by charris** [comment]
Oh, that does look suspicious just on general principles. Let's bring in @ahaldane too.

**Comment by seberg** [comment]
I think I will call it a day, already spend too much time on it :(, but here is the valgrind output, to give a bit more starters:
```
==8695== Process terminating with default action of signal 6 (SIGABRT): dumping core
==8695==    at 0x508D86B: raise (in /usr/lib/libc-2.27.so)
==8695==    by 0x507840D: abort (in /usr/lib/libc-2.27.so)
==8695==    by 0x50782DF: __assert_fail_base.cold.0 (in /usr/lib/libc-2.27.so)
==8695==    by 0x5086111: __assert_fail (in /usr/lib/libc-2.27.so)
==8695==    by 0x95D7D42: DOUBLE_setitem (arraytypes.c.src:240)
==8695==    by 0x95DDF90: VOID_setitem (arraytypes.c.src:912)
==8695==    by 0x95FCBFB: setArrayFromSequence (ctors.c:548)
==8695==    by 0x95FC78A: PyArray_FromAny (ctors.c:1769)
==8695==    by 0x95FC84A: PyArray_CheckFromAny (ctors.c:1868)
==8695==    by 0x968AEBA: _array_fromobject (multiarraymodule.c:1756)
==8695==    by 0x55954D3: _PyCFunction_FastCallDict (in /usr/lib/libpython3.6m.so.1.0)
==8695==    by 0x559559F: _PyCFunction_FastCallKeywords (in /usr/lib/libpython3.6m.so.1.0)
```

**Comment by charris** [comment]
@seberg Hey, thanks a lot. Finding the commit gets us a long way down the road.

**Comment by seberg** [comment]
OK, can't give up so close to it ;), its a pretty silly bug really... Still seeing why some other stuff seems to fail, but will just open a PR in a bit, though probably needs a bit of fixing up later.

**Comment by seberg** [comment]
@ginggs may want to test the fix, not too unlikely something similar crops up now later in the test suit...

**Comment by ginggs** [comment]
Testing now.

**Comment by ginggs** [comment]
Test suite passes with python 2.7.15~rc1 and 3.6.5.
Thanks @charris and @seberg !

**Comment by charris** [comment]
@rikmills Can you check it this also fixes your problem?

**Comment by ginggs** [comment]
Ubuntu build for armhf also successful:

https://launchpad.net/ubuntu/+source/python-numpy/1:1.14.3-2ubuntu2

@rikmills ^

**Comment by charris** [comment]
Great, thanks for the quick response.
