### ISSUE TITLE
1.14.3 on powerpcspe: TypeError: unsupported operand type(s) for ** or pow(): 'numpy.float128' and 'int'

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#11087]
Hello,
powerpcspe is another special architecture Debian is trying to support. right after building numpy (via `setup.py build`) we also build the documentation pointing at the built code, but on powerpcspe this fails with this error:

```
(export MPLCONFIGDIR=. ; make -C doc html PYTHON=python3 PYTHONPATH=../build/lib.linux-ppc-3.6)
make[2]: Entering directory '/<<PKGBUILDDIR>>/doc'
mkdir -p build
touch build/generate-stamp
mkdir -p build/html build/doctrees
LANG=C sphinx-build -b html -d build/doctrees   source build/html 
Running Sphinx v1.7.4
/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/core/getlimits.py:82: RuntimeWarning: overflow encountered in power
  self.resolution = float_to_float(float_conv(10) ** (-self.precision))
/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/core/getlimits.py:82: RuntimeWarning: invalid value encountered in power
  self.resolution = float_to_float(float_conv(10) ** (-self.precision))

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 47, in <module>
    import numpy
  File "/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/core/__init__.py", line 51, in <module>
    from . import getlimits
  File "/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/core/getlimits.py", line 226, in <module>
    tiny=exp2(_ld(-1022)))
  File "/<<PKGBUILDDIR>>/build/lib.linux-ppc-3.6/numpy/core/getlimits.py", line 82, in __init__
    self.resolution = float_to_float(float_conv(10) ** (-self.precision))
TypeError: unsupported operand type(s) for ** or pow(): 'numpy.float128' and 'int'
```

full log at: https://buildd.debian.org/status/fetch.php?pkg=python-numpy&arch=powerpcspe&ver=1%3A1.14.3-2&stamp=1525636637&raw=0

(we build module and documentation before running tests, so we dont have their results here)

can you have a look?

**Comment by ahaldane** [comment]
This seems to involve float128 values, but as far as I can tell from a quick look at docs, this platform shouldn't support float128: There's no extended precision type nor quad type. Does that sound right to you? Do you know a good place to read more about the float implementation?

Also, do you know a place we could get access to a powerpcspe?

**Comment by sandrotosi** [comment]
I'm not really familiar with the architecture, but there are quite some info at https://wiki.debian.org/PowerPCSPEPort , with also the instruction on using QEMU to setup a local system for that architecture. there is also a list of porters you may want to contact for additional support

thanks!

**Comment by charris** [comment]
@sandrotosi What is the current status of this with NumPy master?

**Comment by sandrotosi** [comment]
numpy is currently not built on powerpcspe due to some missing dependencies on that architecture (which is not a release arch for Debian anyway). I'd say, let's close this issue and i'll re-open it if it appears again, what do you think?

**Comment by charris** [comment]
Done, thanks for the heads up.
