### ISSUE TITLE
np.random.normal returns only integer values when mean, variance are integers

### ISSUE THREAD

**Issue by garyzhubc** [numpy/numpy#11093]
I'm writing a Gibbs sampler, and here is the issue. It returns integer points when `x0` being initialized to `array[0,0]` instead of sampling from real values. 

```
    N = 9999
    x0 = array([1,1])
    X = gibbs(N,x0,array([[2,1],[1,1]]),array([1,1]))
    print(X)
    plt.scatter(X[:,0],X[:,1])
    plt.show()

```

The problem is resolved if initialize `x0` as `array[0,5,0.5]`. 

```
    N = 9999
    x0 = array([0.5,0.5])
    X = gibbs(N,x0,array([[2,1],[1,1]]),array([1,1]))
    print(X)
    plt.scatter(X[:,0],X[:,1])
    plt.show()

```

**Comment by bashtage** [comment]
This is a bug in your code.  You are setting an element in an array with `dtype=int` and so you are forcing doubles to be ints.

change `x0 = array([1,1])` to `x0 = array([1,1.])`
