### ISSUE TITLE
1.14.3: numpy.arange(dtype=numpy.float128) does not work on some platforms

### ISSUE THREAD

**Issue by olebole** [numpy/numpy#11103]
On some Debian platforms, numpy.arange does not work properly. For example, on arm64 I get:

```
Python 3.6.5 (default, May 11 2018, 13:30:17) 
[GCC 7.3.0] on linux
>>> import numpy
>>> numpy.arange(3)
array([0, 1, 2])
>>> numpy.arange(3, dtype=numpy.float128)
array([0., 0., 0.], dtype=float128)
```

This causes a failure of the astropy tests, reported in astropy/astropy#7467. It is a regression; for 1.13 it worked fine.

Affected platforms include arm64, ppc64 (big and little endian), s390x, risc64v.
This is also reported as Debian bug [#898776](https://bugs.debian.org/898776).

**Comment by ahaldane** [comment]
I'll see if I can find a quick fix, to fall back on the system printf.

**Comment by ahaldane** [comment]
Yes, I confirm the example works now on ppc64be:
```python
>>> np.arange(3, dtype=np.float128)
array([0., 1., 2.], dtype=float128)
```
