### ISSUE TITLE
DOC: document that scale parameter can be 0 from numpy 1.12 on

### ISSUE THREAD

**Issue by awakenting** [numpy/numpy#11125]
Hey,
I think it would be worth to update the documentation with the changes of this pull request : https://github.com/numpy/numpy/pull/5822 where many distributions were allowed to have a scale parameter of 0 (see also this issue: https://github.com/numpy/numpy/issues/5818). One big reason is that if you rely on this behaviour your code is incompatible with numpy versions below 1.12.

**Comment by mattip** [comment]
Would you like to create a pull request? You should follow the [dev guide](http://www.numpy.org/devdocs/dev/index.html). The documentation is generated from the docstrings in `numpy/random/mtrand/mtrand.pyx`, it seems a few well-placed "non-negative" qualifiers for `scale` might help.

**Comment by awakenting** [comment]
Yes, but I will only have time after a deadline in 2 weeks.
One question I already have: Should I include versionadded directives from sphinx as well?

**Comment by mattip** [comment]
I think not, we usually only add `versionadded` directives for new features or options. This was considered a bug fix.

**Comment by eric-wieser** [comment]
I'd use versionchanged
