### ISSUE TITLE
A protocol for tensordot

### ISSUE THREAD

**Issue by mrocklin** [numpy/numpy#11128]
Following on #11074 I would like to see operations like `np.tensordot` develop a protocol that could be implemented by duck-array libraries like dask, cupy, or sparse

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: x = da.ones((5, 5), chunks=(2, 2))

In [4]: np.tensordot(x, x)  # I would like for this to be a dask.array
Out[4]: array(25.)
```

**Comment by seberg** [comment]
I guess `__array_function__` is that protocol, closing.
