### ISSUE TITLE
ctypes code fragment link on dll notes page does not work

### ISSUE THREAD

**Issue by jontwo** [numpy/numpy#11127]
The link to the [ctypes code fragment](https://pytools.codeplex.com/workitem/1627) on the [windows dll page](https://github.com/numpy/numpy/wiki/windows-dll-notes) does not work, as pytools has moved to [github](https://github.com/Microsoft/PTVS).

**Comment by mattip** [comment]
Do you know the exact link that should replace the broken one?

**Comment by jontwo** [comment]
No, that's why I raised the issue. I'm trying to find out about windows dll search order and thought that fragment might help me. I did a quick search of the repo, but couldn't find it.

**Comment by eric-wieser** [comment]
Possibly https://gist.github.com/matham/f6a07f8fb5e403feb440?

**Comment by jontwo** [comment]
@eric-wieser Thanks - looks like that is it. Anyone know if it works? The `sdl2\bin` in the last line should be a string, shouldn't it?

**Comment by mattip** [comment]
Modified to show commit 1fcb19492c5a262baed79669c21410257bd34295 which was active for a while until we found it caused problems for subsequent dll searches when loading other packages
