### ISSUE TITLE
dtype=uint64 generates wrong Py_buffer format code

### ISSUE THREAD

**Issue by matthiaskramm** [numpy/numpy#11130]
Creating a numpy array like this:

```
x = numpy.array([0, 1, 2], dtype=numpy.uint64)
```

and then passing it to a C extension that reads out the array's buffer info:

```
Py_buffer view;
PyObject_GetBuffer(x, &view, PyBUF_FORMAT | PyBUF_STRIDED_RO | PyBUF_C_CONTIGUOUS);
```

results in (on my system)

```
view.format: 'L'
view.itemsize: 8
```

Now, `itemsize` is correct, but `format` is wrong, according to https://docs.python.org/2/library/struct.html. It should be `'Q'`, since `'L'` is always 32 bits.

**Comment by eric-wieser** [comment]
Your assertion is wrong - you're thinking of `'=L'`, which is always 32. In the case above, it's the system `long` type

**Comment by matthiaskramm** [comment]
Ah. Thanks. I missed that part.
