### ISSUE TITLE
doc unclear on slicing

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#11143]
At https://docs.scipy.org/doc/numpy/user/basics.indexing.html, this sentence:

> Note that slices of arrays do not copy the internal array data but also produce new views of the original data.

does not make sense.  I think the word "also" should be deleted, then it becomes grammatical and technically correct.

**Comment by charris** [comment]
Agree. Could also omit "internal" and put a comma before "but". Want to make a PR?

**Comment by keithbriggs** [comment]
Or perhaps replace "but" by "only"?  I can make a PR when I remember how to...

**Comment by mattip** [comment]
http://www.numpy.org/devdocs/dev/gitwash/development_workflow.html

Let us know if the instructions are not clear
