### ISSUE TITLE
Let `array2string` print prefix/suffix

### ISSUE THREAD

**Issue by astromancer** [numpy/numpy#11142]
In `array2string` the prefix and suffix are **only** used to align/indent the lines following a newline in the string representation of the array, and are **not** included in the returned string as one would expect.

Eg:
```
a = np.array([0, 1])
np.array2string(a, prefix='Array(', suffix=')') 
# Produces '[0 1]' not 'Array([0 1])' as expected
```

It would be useful to support prefix/suffix here for customized array printing without needing to subclass `np.ndarray`.  If, however, this is the intended/needed behaviour, it should be made clear in the documentation that the prefix and suffix are not printed.

**Comment by eric-wieser** [comment]
This is intended behavior, although perhaps the docs could be clearer
