### ISSUE TITLE
`astype` after `np.random.uniform` make the array weird

### ISSUE THREAD

**Issue by jyori112** [numpy/numpy#11144]
Hello,

Recently I have been struggling with weird and unexpected behavior of numpy, and would like to have some help.

Here is my code:

```
import numpy as np
vec = np.random.uniform(-0.5, 0.5, size=(100)).astype(np.float32)
print(np.linalg.norm(vec))
```

This code returns very differently every run including

1. `0.0`
2. `nan` along with `RuntimeWarning: invalid value encountered in sqrt`
3. Very large value, i.e. `6074001000.0`
4. Good value, i.e. `1.4142135`

Further I confirmed that it works fine if I don't have `.astype`, but I need `vec` to be float32 for following process.

My environment is

```
OS: macOS High Sierra
numpy version: 1.14.0
python version: anaconda3-5.1.0 (install with pyenv)
```

Thank you

**Comment by mattip** [comment]
Does not reproduce on Ubuntu x64 using gcc and NumPy 1.14.0

**Comment by seberg** [comment]
Sounds like another one of those "something is wrong with BLAS" issues, i.e. probably an anaconda bug (or some bug in the setup). If it is not up to date, maybe try updating it, I seem to remember there were some fixes in it?

**Comment by seberg** [comment]
Or, if it is linking again Accelerate (I somewhat think anaconda stopped that), I would not be surprised. Accelerate had some funny issues like this I think.

**Comment by mattip** [comment]
searching issues for [float32 and blas](https://github.com/numpy/numpy/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+float32+blas) does bring up a few of them. #10584 look very much like this one.

**Comment by jyori112** [comment]
I updated anaconda to the latest version, but it did not fix the problem.

```
% conda --version
conda 4.5.4
```

Also, here is the result of `numpy.__config__.show()`, hope it may help
```
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/[username]/.pyenv/versions/anaconda3-5.1.0/include']
```

**Comment by seberg** [comment]
@jyori112 please check the issue Matti linked above. It quite certainly identical and in any case in the right direction, so closing this one as duplicate.
The thing is that this is certainly an MKL or linking issue in anaconda and numpy can't do anything about it in any case actually...
