### ISSUE TITLE
Numpy cannot convert pandas.NaT to a datetime64

### ISSUE THREAD

**Issue by ericksc** [numpy/numpy#11147]
#### Code Sample, Creating a MaskedArray with missing data

When the code showed below an exception is captured:
**{ValueError}cannot convert float NaN to integer**

```python
# My current numpy version is
np.__version__
#1.13.3

MaskedArray(['2018-12-12', pd.NaT],mask=[False, True] ,dtype='datetime64[ns]', fill_value=None)
```
#### Problem description

A MaskedArray needs to be created to insert to Database by using turbodbc module. That array contains missing values.

**Note**: The same behavior also applies to numpy arrays and when the fill_value is removed

```python
MaskedArray(['2018-12-12', pd.NaT],mask=[False, True] ,dtype='datetime64[ns]')
```  

**Note**: The error disappear when missed value is a None
```python
MaskedArray(['2018-12-12', None],mask=[False, True] ,dtype='datetime64[ns]')
```

**Comment by eric-wieser** [comment]
Note that this works fine:
```
MaskedArray(['2018-12-12', 'NaT'],mask=[False, True] ,dtype='datetime64[ns]')
```

Numpy doesn't know about `pd.NaT` - it's from pandas

**Comment by mattip** [comment]
Closing.
