### ISSUE TITLE
 import multiarray ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by lakshmisivareddy** [numpy/numpy#11164]
Hi i am getting below error i am tried changing python & numpy  versions but nothing worked out 
 
\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

i am using numpy : 1.14.3
python : 3.6.5

**Comment by matthew-brett** [comment]
Is it possible you are trying to import numpy from a directory that has `numpy` as a subdirectory?  If so, try changing to another directory, outside the numpy directory tree.  Does that work?

**Comment by lakshmisivareddy** [comment]
Hi @matthew-brett 
i am using Anaconda 
this is my env path 
/Anaconda3\envs\MYML\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found

**Comment by matthew-brett** [comment]
I'm not sure what's going on, but it does seem that your Numpy installation is broken.   I see you're using Anaconda - why not try asking their advice over at https://github.com/ContinuumIO/anaconda-issues/issues ?

**Comment by lakshmisivareddy** [comment]
Hi @matthew-brett  thanks for the response i will try in /anaconda-issues/issues

**Comment by matthew-brett** [comment]
@lakshmisivareddy - OK to close this one?

**Comment by lakshmisivareddy** [comment]
Hi sorry for late response  you can close
