### ISSUE TITLE
DOC: Bit numbering for 8 bit types

### ISSUE THREAD

**Issue by sbrodehl** [numpy/numpy#11172]
Hi there,

I am working with 8 bit data with varying bit numbering and was wondering how numpy supports bit numbering for those types (`int8`, `uint8`, `byte`, `ubyte`).

According to the [numpy.dtype.byteorder docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.byteorder.html) "*endian is not relevant for 8 bit numbers*", but how is a single byte endcoded?

Creating e.g. `uint8` data seems always to be encoded with the *most significant bit first*.
Where is that documented?

See the [example on numpy.unpackbits](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unpackbits.html):
```python
>>> a = np.array([[2], [7], [23]], dtype=np.uint8)
>>> a
array([[2],
       [7],
       [23]], dtype=uint8)
>>> b = np.unpackbits(a, axis=1)
>>> b
array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=uint8)
```

Edit: Updated text regarding bit numbering.

**Comment by charris** [comment]
Big/little endian refers to byte order in types that are more than one byte in size, it doesn't refer to bit order within bytes.

**Comment by sbrodehl** [comment]
Yes, that's true. But how is the bit order set?
Does numpy rely on the system to do that?

**Comment by rkern** [comment]
No, it's a design choice of `np.unpackbits()`. It should be consistent on all platforms.

**Comment by charris** [comment]
The bit order internally is transparent, i.e., left and right shift will produce values like `*2` or `/2` regardless. Specifications of serial protocols is a separate issue and is handled at the network interface level. There is a network specification for representing (printing) the bits of bytes, which like the protocol itself is big endian, i.e., the high order bit is on the left, and this is pretty much a universal standard for arabic numerals, which are little endian when writing goes right to left, as arabic does :) I suppose you could call the big endian convention a translation error.

**Comment by sbrodehl** [comment]
Thanks @rkern, that's nice to know! Is that somewhere documented?

**Comment by eric-wieser** [comment]
I would be in favor of adding an `order='big'` parameter to this function - I find it weird that
```
x = np.uiunt8(0xA5)
for i in range(8):
    assert np.unpackbits(x)[i] == (x >> (7-i)) & 0x1
```
And would prefer the simpler relationship
```
x = np.uiunt8(0xA5)
for i in range(8):
    assert np.unpackbits(x, order='little')[i] == (x >> i) & 0x1
```

**Comment by mattip** [comment]
So the current representation where `3 => [0, 0, 0, 0, 0, 0, 1, 1]` would be `order='big'`?

**Comment by sbrodehl** [comment]
I'm not sure whether `little` and `big` are the right words to describe the bit ordering in this case. They typically refer to byte ordering (endianness).

In our case, we describe the bit order. Not sure how much the term bit endianness is used in this case...
However, the _order_ keyword describes whether the _Most Significant Bit_ (MSB) or the _Least Significant Bit_ (LSB) will be processed first.

FWIW MSB 'corresponds' to big-endian, and LSB to little-endian.
So, in this case you are right, `3 => [0, 0, 0, 0, 0, 0, 1, 1]` would be `order='big'`.

I personally would prefer keyword options alike `MSB`, `LSB` (to differentiate from byte ordering), but I guess someone higher up the food chain needs to decide that.

**Comment by charris** [comment]
> I personally would prefer keyword options alike MSB, LSB (to differentiate from byte ordering)

Agree, byte ordering is memory layout of the bytes and addressing, bits depend on the chip pin out and internal register implementations and not something we need be concerned about. The  MSB, LSB choice would be a display option necessary to interpret the output.
