### ISSUE TITLE
Two different Appveyor accounts?

### ISSUE THREAD

**Issue by pv** [numpy/numpy#11171]
Currently, numpy seems to be set up to run Appveyor via
https://ci.appveyor.com/project/charris/numpy

However, there's also a separate "project" appveyor account 
https://ci.appveyor.com/project/numpy/numpy
I don't know the history of this, but it seems I'm able to log into this "project" account, and occasionally get redirected to it. For some reason, it's not correctly running the numpy tests however, but has a very long queue.

I don't have bandwidth to sort this out, but just as a notice...

**Comment by charris** [comment]
Yep, this issue is still hanging out there. The history is that I set up the original because appveyor didn't support projects at the time, at least without intervention by the appveyor developers. I have seen the other account run tests now an then and if it was consistent I could shut my account down.

Another possibility we will be taking a look at in the future moving to and upcoming Microsoft project which is going to offer windows, linux, and osx testing support.

**Comment by njsmith** [comment]
I'm not sure where the "project" account comes from – I think it's existed for a long time. At the sprint on Thursday, we were being confused/annoyed about appveyor's permissions when trying to re-run an old build, and in the course of that I ended up clicking around in the project account and I *think* I may have enabled it to start doing builds. In theory. In practice, like you say, it doesn't seem to actually do builds, but rather just queue them and never run the queue.

I guess ideally we would switch to the project account and disable the "charris" account. Of course this would require figuring out why the project account doesn't work and fixing it, and I don't know how to do that. (I guess one unlikely possibility is that the two accounts are somehow interfering with each other?) Given this issue, it might be more practical in the short term to disable the project account, if no one has time to figure out how to make it work correctly.

Microsoft's VSTS project has recently started offering CI for Windows/MacOS/Linux, and are giving away at least some free to open source projects. So far they're handling this in a case-by-case basis; I think CPython is the only project enabled so far. I've asked Steve Dower about the possibility of getting a similar setup for numpy, and he's looking into it. In principle it could be pretty sweet (CPython currently has 20-way parallelism across all three platforms on pretty beefy machines), but we don't really know what will happen yet.

**Comment by charris** [comment]
Hmm, I can log into that account and may have set it up. I can also delete it. @njsmith Can you log into that account also? I'm wondering if I set it up, or if my access is an artifact of my adding the numpy account. I note that there is also a windows-wheels-builder account.

**Comment by njsmith** [comment]
I can log into the project account yes. I think anyone who has permissions on the GitHub repository can.

**Comment by charris** [comment]
Maybe we should see if we can get it working and then drop my account.

**Comment by charris** [comment]
From the numpy account settings:

`AppVeyor was authorized 2 years ago for admin:repo_hook,read:org,repo:status access to GitHub repositories as njsmith account.`

**Comment by charris** [comment]
I'm inclined to delete the numpy account and create a new one following the prescription at https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization, However, we need to decide on an email address to do so.

**Comment by charris** [comment]
Seems to be set up as: `numpy-steering-council@googlegroups.com`, Nathaniel, I'm pretty sure I recall you doing this.

**Comment by charris** [comment]
Numpy also has an active github email service with address `numpy-svn@scipy.org`. Maybe we should turn that off as Github has moved away from the services.

**Comment by charris** [comment]
Just for testing, I'm going to remove the NumPy project on my account and see if it makes a difference. IIRC, last time Nathaniel added NumPy on his personal appveyor account, we had the test running twice, once for each of us, so I suspect that is not the problem.

**Comment by charris** [comment]
Well, maybe not. I'd rather get something else working first because if my account loses the history I don't know what will happen to all the current test results.. Maybe I can just turn off the NumPy access.

**Comment by charris** [comment]
Well, I've deactivated the numpy project appveyor webhook since it doesn't seem to be working, but sometimes makes the appveyor link confusing. I wonder if appveyor knows that the numpy project is open source? At this point I think we need to contact appveyor support to find out what is going on.

**Comment by charris** [comment]
Hmm. Most places these days require email verification, I wonder if appveyor was able to do that with the google-group mail address?

**Comment by mattip** [comment]
Can we close this since we stopped using appveyor CI for numpy? We still use it for the wheels.

**Comment by rgommers** [comment]
Thanks @mattip. Yes, the wheels are built on a different account (https://ci.appveyor.com/project/matthew-brett/numpy-wheels/history) so let's close this.
