### ISSUE TITLE
numpy hstack changes byte endianness of the arrays

### ISSUE THREAD

**Issue by pxcandeias** [numpy/numpy#11188]
Working with numpy version 1.14.0 on a Windows7 64 bits machine with Python 3.6.4 (Anaconda distribution) I notice that hstack changes the byte endianness of the the arrays.

A minimal example of this behaviour taken from an IPython console:

Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

In[1]: import numpy as np
In[2]: np.__version__
Out[2]: '1.14.0'

In[3]: a = np.array([1.], dtype='>f8')
In[4]: a
Out[4]: array([1.])

In[5]: a.dtype
Out[5]: dtype('>f8')

In[6]: b = np.hstack((a, a))
In[7]: b
Out[7]: array([1., 1.])

In[8]: b.dtype
Out[8]: dtype('float64')

In[9]: a.dtype == b.dtype
Out[9]: False

I would expect that this operation would keep the byte endianness of the original array (or possibly the leftmost array in the tuple argument to the hstack function) but this is not the case. The result is promoted to numpy.float64 (equivalent to numpy.dtype('<f8') in this machine) instead of keeping the original numpy.dtype('>f8'). Is the default behaviour of hstack considered to be 'return an array with the machine default endianness'?

**Comment by seberg** [comment]
Very old issue which inherits its behavior from `concatenate`.  I think the choice that we return native byte order here is pretty settled, there is now a `dtype=` parameter to avoid getting the "canonical"/native result.  See also gh-20767
