### ISSUE TITLE
BUG: Non-standard scaling factor for the covariance matrix in `numpy.polyfit`

### ISSUE THREAD

**Issue by jotasi** [numpy/numpy#11196]
As discussed on the [mailing list](http://numpy-discussion.10968.n7.nabble.com/Inconsistent-results-for-the-covariance-matrix-between-scipy-optimize-curve-fit-and-numpy-polyfit-td45582.html) recently, and (as @josef-pkt pointed out to me) also already [in a discussion in 2013](https://mail.scipy.org/pipermail/numpy-discussion/2013-February/065664.html), `numpy.polyfit` uses a non-standard factor in the estimated scale of the covariance matrix. Namely, rather than using the standard `chisq/(M-N)`, it scales it with `chisq/(M-N-2)` where `M` is the number of data points and `N` is the number of parameters. Neither my colleague @wummo and I, while researching this, nor @josef-pkt as stated in the subsequent E-Mail conversation has found any reference for this in the literature. There is a comment in the corresponding code here explaining the choice:
https://github.com/numpy/numpy/blob/79ec65de3064cbdc687820ab09f20b989028509d/numpy/lib/polynomial.py#L593-L604
But there is no reference given there. As this is non-standard and is inconsistent with other fitting programs (such as e.g. `scipy.optimize.curve_fit`), we feel that this should be changed to avoid surprises when using this library.

As a side note, one could use the occasion to add an additional parameter which enables the return of an unscaled covariance matrix (@josef-pkt suggested the name `absolute_weights`, analogous to `curve_fit`'s `absolute_sigma`). This was already suggested in both mailing list discussions. It would be useful in occasions, where the weights are given by `1/sigma` with sigma being the (known) standard errors of (gaussian distributed) data points, in which case  the unscaled matrix is already a correct estimate for the covariance matrix.

**Comment by daschaich** [comment]
Yes, it would be nice to bring the polyfit routine into line with the behavior I (and apparently others) would expect.  I was [bitten](https://mail.scipy.org/pipermail/numpy-discussion/2013-July/067076.html) by this issue back in 2013 (leading eventually to pull request #7672) and am back now because it just bit a student last night.  I think unless/until this is dealt with I need to switch all my code to use scipy.optimize.curve_fit instead.
