### ISSUE TITLE
What CI/CD tool(CircleCI or Travis CI) is currently used in NumPy?

### ISSUE THREAD

**Issue by Mikerr1111** [numpy/numpy#11207]
Looking in the NumPy repository I see a CircleCI folder suggesting that CircleCI is your CI tool, but if I look in the Readme file I see the Travis CI build passing badge. Are both being used or is there a transition
 phase going on from Travis CI to CircleCI?

![numpy](https://user-images.githubusercontent.com/18353476/40772464-e2438596-6474-11e8-82a9-a0364c1d4bfe.PNG)
![numpy2](https://user-images.githubusercontent.com/18353476/40772474-e8ebb508-6474-11e8-995b-350dbdf227fa.PNG)

**Comment by pv** [comment]
Multiple CIs are used, as a quick look at the pull request page or
config files would reveal.

**Comment by njsmith** [comment]
There's no transition happening currently; multiple tools are used for different purposes.
