### ISSUE TITLE
merging structured arrays with subarrays fails

### ISSUE THREAD

**Issue by GerhardR** [numpy/numpy#11212]
Hi,

I am trying to merge to structured arrays where columns contain subarrays. The following is a simple example. both arrays (a and b) contain a single column that contains a 2 element array (representing a 2D vector). 

I try to merge the two arrays into a single one with numpy.lib.recfunctions.merge_arrays but I get the error below.

this is using numpy 1.13.3 with Python 3.6 on Windows (Anaconda install)

```python
import numpy as np
import numpy.lib.recfunctions as rfn

data = [((1, 2),), ((3,4),)]

a = np.array(data, dtype=[('vectors', 'f4', (2,))])
b = np.array(data, dtype=[('points', 'f4', (2,))])

m = rfn.merge_arrays([a,b])
```
Results in:
```python
Traceback (most recent call last):

  File "<ipython-input-325-1bf6c0257828>", line 10, in <module>
    m = rfn.merge_arrays([a,b])

  File "C:\Users\gerhardr\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\recfunctions.py", line 455, in merge_arrays
    dtype=newdtype, count=maxlength)

ValueError: size of tuple must match number of fields.
```

**Comment by GerhardR** [comment]
Similar error on numpy 1.14.3 (Python 3.6, Windows 10, Anaconda)

```python
Traceback (most recent call last):

  File "<ipython-input-11-d8059f1b607f>", line 9, in <module>
    m = rfn.merge_arrays([a,b])

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\numpy\lib\recfunctions.py", line 489, in merge_arrays
    dtype=newdtype, count=maxlength)

ValueError: could not assign tuple of length 4 to structure with 2 fields.
```

**Comment by GerhardR** [comment]
That is precisely what I was looking for ! thank you. 

I am not sure I understand what the flattening does here? Each of the dtypes has a single column, how else would they be combined without flatten=True ?

**Comment by mattip** [comment]
At the least this issue pointed out that our on-line documentation is missing for `recfunctions`, added in PR #11225

Since each values is two floats, `flatten` is needed.
