### ISSUE TITLE
Importing the multiarray numpy extension module failed.

### ISSUE THREAD

**Issue by wgaylord** [numpy/numpy#11215]
When installing numpy thru apt-get on Raspberrian Linux I am getting this error.

Numpy version

> python-numpy is already the newest version (1:1.12.1-3).

Python version 

> Python 2.7.13 (default, Nov 24 2017, 17:33:09)
> [GCC 6.3.0 20170516] on linux2
> 

Full error is.

> ImportError:
> Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy. If you're working with a numpy git repo, try `git clean -xdf` (removes all files not under version control).  Otherwise reinstall numpy.

**Comment by pv** [comment]
Report it to the linux distribution you are using.

**Comment by matthew-brett** [comment]
For what it's worth, on my Raspberry Pi, with the same versions, I do not get an import error from `python -c "import numpy"`.   Do you?  Is it possible you're trying this in a directory with a `numpy` subdirectory?

**Comment by wgaylord** [comment]
That also throws an error.

**Comment by wgaylord** [comment]
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
>     from . import add_newdocs
>   File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
>     from numpy.lib import add_newdoc
>   File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
>     from .type_check import *
>   File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
>     import numpy.core.numeric as _nx
>   File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 24, in <module>
>     raise ImportError(msg)
> ImportError:
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> If you're working with a numpy git repo, try `git clean -xdf` (removes all
> files not under version control).  Otherwise reinstall numpy.

**Comment by matthew-brett** [comment]
What directory are you in?

Try:

```
sudo apt-get install --reinstall python-numpy
```

**Comment by wgaylord** [comment]
I am sitting in the home directory of my user.

And running that had no effect same error.

**Comment by charris** [comment]
Do a `locate` for numpy.

**Comment by wgaylord** [comment]
What do you mean? locate is not a command on my system.

**Comment by wgaylord** [comment]
whereis returns

> pi@raspberrypi:~ $ whereis numpy
> numpy: /usr/include/numpy /usr/share/numpy

**Comment by charris** [comment]
Try `find`. On Fedora the files are indexed and can be searched for using `locate`. Looks like you need to install for Debian, it isn't there by default but is available.

**Comment by wgaylord** [comment]
If I run find / numpy I get every file that uses numpy.

**Comment by mattip** [comment]
`find / -name '*numpy*'`or even `find / -name multiarray.so`, then you can do things like `ldd <path/to>/multiarray.so` to find out what other libraries `multiarray.so` needs to load. If any of those are `not found`, that is a problem.

**Comment by wgaylord** [comment]
I am attempting just to reflash my Pi 

Probably was some weird error.
