### ISSUE TITLE
linalg.solve gives incorrect answers for large matrices containing large numbers

### ISSUE THREAD

**Issue by usheth** [numpy/numpy#11213]
I am trying to solve matrix equations of the form Ax=B where both A and B are multi-dimensional. numpy.linalg.solve gives the correct answer when A and B have smaller dimension (eg. A is 3x3 and B is 3x10 or A is 7x7 and B is 7x10). However, when A and B are large and contain large values (A is 15x15 and B is 15x10 containing values of the order 10^18), the solution is incorrect. I am using numpy version 1.11.0 and Python version 3.5. I am running 64 bit Ubuntu 16.04. 
Could this be a precision issue? If yes, what can I do to increase the precision of the method? I have already set the 'dtype' of the matrices to float64.

Thank you!

**Comment by njsmith** [comment]
It could be a precision issue, but it's hard to say without more information. Can you give an example (ideally as cut-and-pasteable code) of what you're doing, and how you're checking for errors?

**Comment by usheth** [comment]
Hi!

I'm trying to solve `Ax=B` for `x`. Also, `A` is a Vandermonde matrix. Here's a code snippet:

```
def matdotcode_mult(query_split,point_matrix_split,const,splits):
	query_term = evaluate_matrix_polynomial(query_split,const,splits,reverse=True)
	point_matrix_term = evaluate_matrix_polynomial(point_matrix_split,const,splits)
	mul = np.matmul(point_matrix_term,query_term)
	return mul

def evaluate_matrix_polynomial(mats,const,splits,reverse=False):
	result = np.zeros(mats[0].shape, dtype=np.float64, order="FORTRAN")
	for exp in range(splits):
		index = exp
		if reverse:
			index = splits-exp-1
		term = math.pow(const,exp)*mats[index].astype(dtype=np.float64)
		result = np.add(result, term)
	return result

const = 1
powers_of_const = []
polynomial_values = []
for i in range(degree+1):
	powers_of_const.append(get_pow_list(const,degree))
	polynomial_values.append(matdotcode_mult(query_split,point_matrix_split,const,splits))
	const += 1

A = np.array(powers_of_const,dtype=np.float64)
B = np.hstack(polynomial_values)

x = np.linalg.solve(A,B.T)
```

Here, `degree` is the degree of the Vandermonde matrix, `query_split` is an array containing 8 16x1 vectors and `point_matrix_split` is an array containing 8 10x16 vectors.

I am interested only in the array at index `x[degree/2]` and have a reference answer for this array which I am comparing to the answer.

Thanks!

**Comment by usheth** [comment]
If it helps, here's an example of the scale of values `B` will contain when solving for `x`:

```
[  8.66257000e+05   1.00170581e+09   1.65513052e+11   7.24416681e+12
    1.42624769e+14   1.66461495e+15   1.34552560e+16   8.28664412e+16
    4.13964490e+17   1.75155499e+18   6.47541839e+18   2.14058880e+19
    6.43995162e+19   1.78771217e+20   4.62953230e+20]
```

(This is one row in `B` when the degree of the Vandermonde matrix `A` is 15)

**Comment by pv** [comment]
Check `numpy.linalg.cond(A)`. If it is larger than ~1e15, the matrix is essentially singular insofar as floating-point numerical linear algebra is concerned, and LU decomposition (np.linalg.solve) cannot be used to invert it.

**Comment by usheth** [comment]
```
np.linalg.cond(A)
/usr/lib/python3/dist-packages/numpy/linalg/linalg.py:1457: RuntimeWarning: divide by zero encountered in true_divide
  return s[..., 0]/s[..., -1]
inf
```

That was the issue. Thank you so much!
