### ISSUE TITLE
rk_random_uint32 optimized for 16-bits rng

### ISSUE THREAD

**Issue by achan001** [numpy/numpy#11227]
Function [rk_random_uint32](https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/randomkit.c)  always does redraw for biased val
```
for (i = 0; i < cnt; i++) {
    while ((val = (rk_uint32(state) & mask)) > rng);
    out[i] =  off + val;
}
```
Proposal to allow small 16-bits rng a *second chance* before redraw
```
for (i = 0; i < cnt; i++) {
    for(;;) {
        val = rk_uint32(state);
        if ((val & mask) <= rng) {val &= mask; break;}
        if (mask <= 0xffff && (val = (val>>16) & mask) <= rng) break;
    }
    out[i] =  off + val;
}
```

**Comment by bashtage** [comment]
The compatibility guarantee makes this impossible to implement.  Additionally, randint efficiently uses bytes from unsigned integers when producing 8 or 16 bit uints or ints.

**Comment by achan001** [comment]
Thanks.  
I don't know there is a compatibility guarantee.
