### ISSUE TITLE
numpy.memmap can overflow with large int32 shape components

### ISSUE THREAD

**Issue by pgunn** [numpy/numpy#11224]
The memmap constructor for the numpy memmap binding can fail if the shape components are large int32-type variables that if multiplied together will overflow. 

We maintain a crossplatform project that exhibits this behaviour (we have seen it on Windows) with user-supplied data that meets this criterion.

PR #11223 is a possible solution to this issue; it promotes the shape components to np.uint64 inside that constructor before doing the problematic maths operations on them.

**Comment by lesteve** [comment]
Should this one be closed since #11223 has been merged?
