### ISSUE TITLE
BUG: np.savez can not be loaded by np.load

### ISSUE THREAD

**Issue by anypurpose** [numpy/numpy#11220]
my first time to report a bug here.
But it is so annoying, I have to report it.
Here is the demonstration of the errors I encounter:
python version 2.7.13
>>> import numpy as np
>>> import pandas as pd
>>> np.__version__
'1.14.3'
>>> pd.__version__
u'0.23.0'

>>> df=pd.DataFrame({'a':range(10)})
>>> df['b']='abc'
>>> df
   a    b
0  0  abc
1  1  abc
2  2  abc
3  3  abc
4  4  abc
5  5  abc
6  6  abc
7  7  abc
8  8  abc
9  9  abc

>>> np.savez_compressed('abc',data=df.to_records(index=False))
>>> a=np.load('abc.npz')
>>> a.keys()
['data']
>>> a['data']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 235, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 635, in read_array
    shape, fortran_order, dtype = _read_array_header(fp, version)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 523, in _read_array_header
    raise ValueError(msg % (d['descr'],))
ValueError: descr is not a valid dtype descriptor: [(u'a', '<i8'), (u'b', '|O')]

But the 'abc.npz' created here, can be loaded by np.load in python3!!!

**Comment by pv** [comment]
Read the np.load documentation and set "encoding" appropriately.

**Comment by seberg** [comment]
Yeah, other then that, you have objects, objects are pickled, pickle issues are outside of numpy for the most part. The encoding is one thing we provide to make it a bit more robust.
