### ISSUE TITLE
BUG: Wrong error reporting in einsum

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#11221]
See this example:

```
>>> a = np.ones((3, 3, 4, 5, 6))
>>> b = np.ones((3, 4, 5))
>>> np.einsum('aabcb,abc', a, b)
ValueError: dimensions in operand 0 for collapsing index 'c' don't match (4 != 6)
```

The `4 != 6` mismatch is for collapsing index `'b'`, not `'c'`.

This is due to `get_combined_dims_view` in `einsum.c.src` overwriting the labels array as it parses it to remove duplicates, see [here](https://github.com/numpy/numpy/blob/maintenance/1.14.x/numpy/core/src/multiarray/einsum.c.src#L2212)

So by the time the mismatch in the 5th dimension is detected, the `'b'` in position 3 has been overwritten by the `'c'` in position 4, leading to the wrong reporting.

**Comment by eric-wieser** [comment]
This doesn't seem fixed - it now raises a `ValueError` with no message at all
