### ISSUE TITLE
Implement np.memmap.__array_ufunc__

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#11235]
This should be a relatively easy place that we can start implementing `__array_ufunc__` internally.

Right now this implements `__array_wrap__`.

**Comment by cldssty** [comment]
Hi, can I work on this?

**Comment by mattip** [comment]
@cldssty we don't really assign issues. Once you have a prototype or some code we can look at, issue a pull request with the WIP (work in progress) label. If you need help getting started, look at the [development process](http://www.numpy.org/devdocs/dev/index.html) pages. Feedback on the onboarding documentation is welcome as well.

The idea would be to update the class to use `__array_ufunc__` as an alternative to the `__array_finalize__`, `__array_wrap__` protocols. It would be interesting to benchmark the difference.

**Comment by cldssty** [comment]
Ah understood. I'll have a look at the page you linked! Thanks.

**Comment by seberg** [comment]
I'll close this one, I don't really see it as having any advantage.  And I doubt array-wrap is going anywhere.  (Happy if you disagree and reopen, though.)
