### ISSUE TITLE
import numpy gives error

### ISSUE THREAD

**Issue by gdu2003** [numpy/numpy#11243]
i get following error while importing numpy:
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "C:\Apps\Python35\lib\site-packages\numpy\core\__init__.py", line 16, in
<module>
    from . import multiarray
ImportError: DLL load failed: The network path was not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Apps\Python35\lib\site-packages\numpy\__init__.py", line 142, in <mod
ule>
    from . import add_newdocs
  File "C:\Apps\Python35\lib\site-packages\numpy\add_newdocs.py", line 13, in <m
odule>
    from numpy.lib import add_newdoc
  File "C:\Apps\Python35\lib\site-packages\numpy\lib\__init__.py", line 8, in <m
odule>
    from .type_check import *
  File "C:\Apps\Python35\lib\site-packages\numpy\lib\type_check.py", line 11, in
 <module>
    import numpy.core.numeric as _nx
  File "C:\Apps\Python35\lib\site-packages\numpy\core\__init__.py", line 26, in
<module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The network path was not found.

Python version: Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
 on win32
numpy version: 1.14.3

**Comment by mattip** [comment]
The error "The network path was not found" is a bit suspect, since you seem to be loading from a local directory `C:\Apps\Python35\lib\site-packages`. You should have a file `multiarray.pyd` located in `C:\Apps\Python35\lib\site-packages\numpy\core`. How did you install numpy?

**Comment by gdu2003** [comment]
I did not install numpy directly , it installed as a dependency to some other package (may b mdfreader or asammdf or tensorflow).Only thing which i noticed when i installed it inwas behind corporate proxy and installed using proxy.Now if i use these packages without proxy it is not working. If i go back in corporate network, everything works fine. I have tried removing environment variables of http proxy and all internet setting to automatically detect but it does not work untill i am behind proxy.

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 5, 2018 at 0:27, Matti Picus<notifications@github.com> wrote:   
The error "The network path was not found" is a bit suspect, since you seem to be loading from a local directory C:\Apps\Python35\lib\site-packages. You should have a file multiarray.pyd located in C:\Apps\Python35\lib\site-packages\numpy\core. How did you install numpy?

**Comment by gdu2003** [comment]
There is are two file with name: multiarray.cp35-win_amd64.pyd & multiarray_tests.cp35-win_amd64.pyd
    On Tuesday, June 5, 2018, 12:27:13 AM GMT+5:30, Matti Picus <notifications@github.com> wrote:  
 
 
The error "The network path was not found" is a bit suspect, since you seem to be loading from a local directory C:\Apps\Python35\lib\site-packages. You should have a file multiarray.pyd located in C:\Apps\Python35\lib\site-packages\numpy\core. How did you install numpy?

**Comment by gdu2003** [comment]
Got it resolved. It was mdfreader 2.7.5 which installs numpy> 1.14. i just re installed mdfreader 2.7.5 with --ignore-installed flag without using proxy. Everything is working fine now. Thanks alot for support.

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 6, 2018 at 22:55, Matti Picus<notifications@github.com> wrote:   
If you check your PATH environment variable, do you have network paths in it? Also - does the command import numpy as np take quite a while to raise the exception, versus how long it takes to run when you are using the proxy? Those would be indications that something else is going on. Try cleaning up your PATH variable before running python when you are not connected to the proxy.

**Comment by mattip** [comment]
Glad it worked out
