### ISSUE TITLE
f2py: "TypeError: a bytes-like object is required, not 'str'"

### ISSUE THREAD

**Issue by byoung4** [numpy/numpy#11253]
I found a bug in `f2py.compile()`.  I also have a fix.

**Input:**
```python
import numpy.f2py
source = '''
      subroutine foo
      print*, "Hello world!"
      end 
'''
numpy.f2py.compile(source, modulename='hello')

import hello
hello.foo()
```

**Output**:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-875a80871522> in <module>()
----> 1 numpy.f2py.compile(source, modulename='hello')

~/miniconda3/lib/python3.6/site-packages/numpy/f2py/__init__.py in compile(source, modulename, extra_args, verbose, source_fn, extension)
     57
     58     try:
---> 59         f.write(source)
     60         f.flush()
     61

~/miniconda3/lib/python3.6/tempfile.py in func_wrapper(*args, **kwargs)
    481             @_functools.wraps(func)
    482             def func_wrapper(*args, **kwargs):
--> 483                 return func(*args, **kwargs)
    484             # Avoid closing the file as long as the wrapper is alive,
    485             # see issue #18879.

TypeError: a bytes-like object is required, not 'str'
```

**The problem:**

In [`numpy/numpy/f2py/__init__py`](https://github.com/numpy/numpy/blob/master/numpy/f2py/__init__.py) on line `54`, this command

`        f = tempfile.NamedTemporaryFile(suffix=extension)`

Calls [`tempfile.NamedTemporaryFile`](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) with the default write mode, which is `w+b`.

Subsequently, on line `59`,

`        f.write(source)`

Attempts to write a `str` to the `NamedTemporaryFile`, which is open in *binary* write mode, which results in the error above.

**The fix**

Change line `54` from

`        f = tempfile.NamedTemporaryFile(suffix=extension)`

to

`        f = tempfile.NamedTemporaryFile(suffix=extension, mode='w')`

**Re-do the input**

```python
import numpy.f2py
source = '''
      subroutine foo
      print*, "Hello world!"
      end 
'''
numpy.f2py.compile(source, modulename='hello')

import hello
hello.foo()
```

**Output**

`Hello world!`

**Comment by eric-wieser** [comment]
Fix looks good to me - can you make a pull request?

**Comment by byoung4** [comment]
Submitted a pull request
https://github.com/numpy/numpy/pull/11258

**Comment by Samson-Valentin** [comment]
Hi, thank you for the solution. I was just wondering how can I do this fix (I'm working on Jupyter). I don't understand how to access to the Python library to make the change.

**Comment by sparkingdark** [comment]
Is this still open?

**Comment by mattip** [comment]
Maybe. The PR was closed, but it is not clear to me if the problem was fixed or if it could not be reproduced. The first step would be to try to reproduce this failure locally.

**Comment by sparkingdark** [comment]
Yeah It's a confusing issue I don't understand how to approach it.
hey @mattip hwo can I join the numpy slack community?Can you help me with that?

**Comment by byoung4** [comment]
I just re-ran the original test on the latest version of numpy and it worked.

```python
In [1]: import numpy.f2py

In [2]: source = '''
   ...:       subroutine foo
   ...:       print*, "Hello world!"
   ...:       end
   ...: '''

In [3]: numpy.f2py.compile(source, modulename='hello')

Out[3]: 0

In [4]: import hello

In [5]: hello.foo()
 Hello world!
```
Seems like it works to me. This issue should be closed.

**Comment by mattip** [comment]
@sparkingdark DM me (my mail is on my profile) I'll send you a link

**Comment by sparkingdark** [comment]
I got it and joined slack.
