### ISSUE TITLE
Building v1.14.4 fails in Docker with Alpine 3.7 and Python 3.6

### ISSUE THREAD

**Issue by albertaparicio** [numpy/numpy#11267]
I am trying to install numpy in a Docker image using `python:3.6-alpine3.7` as the base image. 

When trying to install NumPy with pip (`pip install numpy==1.14.4`), the build fails ([error log](https://github.com/numpy/numpy/files/2080043/error_1.14.4.log)). I have tried installing version 1.14.3 and there are no errors in this case ([install log](https://github.com/numpy/numpy/files/2080042/error_1.14.3.log)).

Minimal Dockerfile:
```Dockerfile
FROM python:3.6-alpine3.7
RUN apk add --no-cache build-base
RUN pip3 install numpy==1.14.4
```

**Comment by albertaparicio** [comment]
I have been able to test your suggestion and it compiles and installs with no issues. 

I applied it on `master` inside the same image in the Dockerfile above.

Thank you for your help

**Comment by charris** [comment]
@albertaparicio Thanks for testing.
