### ISSUE TITLE
Valgrind shows invalid access on searchsorted with empty input

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#11261]
A quick valgrind run showed a small read into an empty array here:

https://github.com/numpy/numpy/blob/9a4d75dce2442b81859152048c299c57e6610667/numpy/core/src/npysort/binsearch.c.src#L46

Should be mostly harmless, but probably wouldn't hurt to fix. That seemed like the only (numpy related) thing to show up.

**Comment by jaimefrio** [comment]
We could either fix it right here, as e.g.:

```
@type@ last_key_val = (key_len > 0) ? *(const @type@ *)key : 0;
```

Or add shortcut paths in ```PyArray_SearchSorted``` to return empty arrays for those cases. Any preference?

**Comment by eric-wieser** [comment]
I think there's a second place in there that needs fixing too - argbinsearch

**Comment by seberg** [comment]
Only reason I did not fix it yet, was that I was not immediately sure
where to fix it ;).

The third and fourth also, only histogramdd test found it, so specific
(arg)sort/searchsorted empty tests would be good probably.

**Comment by jaimefrio** [comment]
It's probably best to fix it closest to the error, i.e. right in this file. Someone may optimize out a quick path, and we'd be back to having the same problem.

**Comment by eric-wieser** [comment]
> argsort empty tests

The way to test `argbinsearch` is `searchsorted(..., sorter=[])`

**Comment by seberg** [comment]
Yeah, quick fix anyway. Realized that it might (normally) be just an invalid read, and maybe it was only an invalid read in the tests, but no matter. It is also nice that there was nothing in the f2py tests apparently, didn't remember that there was a fix there.
