### ISSUE TITLE
NEP: update nep-0018 after email discussion

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#11276]
The mailing list discussion seems to have reached a natural lull. The [NEP](http://www.numpy.org/neps/nep-0018-array-function-protocol.html) should be updated reflecting the discussion, a `Discussion` section could reflect some of the alternatives raised on the mailing list [thread](https://mail.python.org/pipermail/numpy-discussion/2018-June/078127.html). I think we can move the NEP to `Accepted`, and add the `Resolution` tag to the header, according to the [NEP workflow](http://www.numpy.org/neps/nep-0000.html#review-and-resolution).

@shoyer, @mrocklin

**Comment by shoyer** [comment]
I'm not sure it's safe to call it "Accepted" yet :). But certainly it should get another revision and update to the list :).

**Comment by njsmith** [comment]
The mechanism for marking a NEP as accepted is for someone to propose that there's consensus and wait a week... did this happen and I missed it?

FWIW I still think the NEP is probably a bad idea, but I haven't had energy to read it and the discussion yet carefully, so perhaps that will change.

**Comment by shoyer** [comment]
> The mechanism for marking a NEP as accepted is for someone to propose that there's consensus and wait a week... did this happen and I missed it?

No, that hasn't happened yet.

**Comment by seberg** [comment]
Well, wether a bad idea or not, NEP 18 has long been final, and even gotten a bit of revision since then.  I don't know what alternatives were discussed back in that thread, but I doubt that there is much point in going back and trying to update the document now (unless something specific comes up).
