### ISSUE TITLE
Numpy 1.14.4 does not install on Alpine

### ISSUE THREAD

**Issue by mrfuxi** [numpy/numpy#11279]
I tried to install recent NumPy (1.14.4), forced by SciPy :(
It works in local env but not in Docker running Alpine.

Minimal Docker file that reproduces the problem:

```
FROM python:3.6.5-alpine
RUN apk add --no-cache build-base
RUN pip install numpy==1.14.4
```

By using 1.14.3 it all works.

**Comment by shoyer** [comment]
What error message do you see?

**Comment by mrfuxi** [comment]
Log from the installation: [alpine.1.14.4.log](https://github.com/numpy/numpy/files/2083442/alpine.1.14.4.log)

**Comment by mattip** [comment]
Duplicate of #11274, fixed on HEAD

**Comment by mrfuxi** [comment]
awesome, thank you. Can't wait for the release
