### ISSUE TITLE
Testing.assert_equals bug with nan and sets

### ISSUE THREAD

**Issue by peterdolan** [numpy/numpy#11272]
Hello, I've run into a small bug that causes an error in Testing.assert_equals.

Version numbers: 
* numpy -- 1.14.1
* Python -- 3.6.4
* OS -- OSX 10.13.4 (17E199)

The problem is laid out in code below:

```
import numpy as np

float64_nan = np.float64(np.nan)
np.testing.assert_equal(float64_nan, np.nan) #succeeds
np.testing.assert_equal({float64_nan}, {np.nan}) #fails
```
It seems like either both of these should fail or both should succeed, seeing as the only thing changed is how the data is structured, but maybe there's something I'm missing?

This is a relatively contrived example, but it came up organically when dealing with pandas series/dataframes (which output float64 nans). It looks like maybe without a set both are checked as isNaN, but in the set things are done differently?

**Comment by seberg** [comment]
That function assumes the input is either an ndarray (in which case it calls `assert_array_equal` or a scalar. A set is neither, so the NaNs are considered equal code cannot work for it.

**Comment by peterdolan** [comment]
Ahh, interesting @seberg. Is there any way to test comparisons on sets beyond creating my own function?

**Comment by eric-wieser** [comment]
@peterdolan: Not really. Note that your problem is not a numpy one:

```python
>>> nan1 = float('nan')
>>> nan2 = float('nan')
>>> {nan1} == {nan1}
True
>>> {nan1} == {nan2}
False
```

**Comment by peterdolan** [comment]
@eric-wieser fascinating... Thanks for the help! I'll go ahead and close this :)
