### ISSUE TITLE
Numpy's zeros method code changed after version up but can not find the changed logs

### ISSUE THREAD

**Issue by MrNinja** [numpy/numpy#11278]
Hi, Numpy developing team.
Thank you for your community supported.

Today, I check a new issue from my project and found a behavior changed on `numpy.zeros` method. However, I can not find any changed log wrote about it. So I wonder that which version this method changed it API?

Project with new API anaconda updated:
```
(anaconda2-5.2.0) app@u-01_v5:~/project$ conda list | grep numpy
numpy                     1.14.3           py27hcd700cb_1  
numpy-base                1.14.3           py27h9be14a7_1  
numpydoc                  0.8.0                    py27_0 
```

Error message
```
>>> trend_degree == 1.0
======================================================================
ERROR: Project method comment
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/src/project/test/module/feature.py", line 279, in test_method
    self.target.test_method(matrix)
  File "/mnt/src/project/app/module/test_method.py", line 90, in generate_method_matrices
    self.get_kalman_matrices(matrix, learn)
  File "/mnt/src/project/app/module/kalman_matrix.py", line 117, in get_kalman_matrices
    matrix_param["trend_degree"], matrix_param["tau_trend"]
  File "/mnt/src/project/app/module/kalman_matrix.py", line 213, in _generate_matrices_trend
    g_mat = np.zeros([trend_degree, 1])
TypeError: 'float' object cannot be interpreted as an index
```

Project with previous API anaconda:
```
(anaconda2-4.1.1) app@u-01:~/project$ conda list | grep numpy
numpy                     1.11.1                   py27_0
```

Warning message:
```
>>> trend_degree == 1.0
Project method comment ... /mnt/src/project/app/module/kalman_matrix.py:213: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  g_mat = np.zeros([trend_degree, 1])
/mnt/src/project/app/module/kalman_matrix.py:214: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  h_mat = np.zeros([1, trend_degree])
ok

----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
```

My Dockerfile:

```
###### BEGINNING | 初めて ######
# Define the default image template
FROM ubuntu:16.04

# Run the update and needed tools for this image (ssh, vsftpd, basic utils and libraries)
RUN apt-get update
RUN apt-get install -y sudo ssh vsftpd vim git curl wget build-essential gcc tig byobu nkf libffi-dev libgdal-dev libspatialindex-dev graphviz language-pack-ja supervisor tzdata

###### ANACONDA PREPARE | anaconda環境の準備 ######
RUN curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
RUN ~/.pyenv/bin/pyenv install anaconda2-4.1.1
RUN ln -s ~/.pyenv/versions/anaconda2-4.1.1 ~/anaconda

# PyEnv
RUN echo 'export PATH="/home/'${CONTAINER_USER_NAME}'/.pyenv/bin:$PATH"' >> /home/${CONTAINER_USER_NAME}/.bashrc
RUN echo 'eval "$(pyenv init -)"' >> /home/${CONTAINER_USER_NAME}/.bashrc
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> /home/${CONTAINER_USER_NAME}/.bashrc

###### PYTHON PACKAGE PREPARE | pythonパッケージの準備 ######
RUN mkdir -p /home/${CONTAINER_USER_NAME}/si1_data
COPY requirements.txt /home/${CONTAINER_USER_NAME}/
RUN ~/anaconda/bin/pip install --upgrade pip
RUN ~/anaconda/bin/pip install --upgrade cffi
RUN ~/anaconda/bin/pip install -r /home/${CONTAINER_USER_NAME}/requirements.txt
RUN ~/.pyenv/bin/pyenv global anaconda2-4.1.1
RUN ~/.pyenv/shims/conda install ipyparallel traitlets==4.3.2
RUN ~/.pyenv/shims/conda install twisted
RUN ~/.pyenv/shims/conda install psycopg2
RUN ~/.pyenv/shims/conda install PyYAML==3.12
RUN ~/anaconda/bin/pip install python-keystoneclient
RUN ~/anaconda/bin/pip install PyJWT
RUN rm /home/${CONTAINER_USER_NAME}/requirements.txt
RUN ~/anaconda/bin/pip list
...
```

**_Please teach me which version did you have this change_**.

I checked on [Github release notes](https://github.com/numpy/numpy/tree/master/doc/release) and [Numpy home page release notes](https://docs.scipy.org/doc/numpy-1.14.0/release.html). However, maybe I didn't work hard, I can not find this.

Apologise for my disturbed!

**Comment by eric-wieser** [comment]
My guess is that what actually changed is that `trend_degree` used to be an integer, but is now a float. How is `trend_degree` calculated?

**Comment by MrNinja** [comment]
Mr. @eric-wieser!

This code still here from 2012 and always be `float`. You could see that `numpy version 1.11.1` still supported float number with a warning I mention bellow. I knew that I should update this code and change the data type of `trend_degree` to `integer`. For this fix, unless my customer know which version did numpy library changed, I can't do any more.

Please understand me. Thank you for your support.

> VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

**Comment by njsmith** [comment]
There used to be a lot of places where floats were implicitly cast to integers, which often caused bugs. (E.g., `0.99999999` becoming `0`.). We tightened this up a while ago, after a long deprecation period. You're not not seeing it in the changelog because it wasn't specific to `zeros` – it affected lots of things.

**Comment by eric-wieser** [comment]
Apologies, I missed your output from the previous version of numpy. Thanks for the thorough background, even if I failed to read it!

**Comment by seberg** [comment]
If 1.11 gives a VisibleDeprecation warning (the depcreation warning itself was around at least since 1.9), then most likely 1.12 got rid of it, and fair enough, looks like it:

https://github.com/numpy/numpy/blob/master/doc/release/1.12.0-notes.rst#deprecationwarning-to-error

**Comment by MrNinja** [comment]
Hi, Mr. @njsmith, Mr. @seberg.
Thank you a lot for your supported.
