### ISSUE TITLE
Environment variable MKL_THREADING_LAYER is ignored since 1.13.3

### ISSUE THREAD

**Issue by mlamarre** [numpy/numpy#11271]
Not sure this is the right project for this issue. Might be a ContinuumIO build issue.

Using the conda default numpy, i.e. installed with `conda install numpy=1.13.3`

Since version 1.13.3 the env. variable MKL_THREADING_LAYER is ignored and OpenMP is always used. 

bash example:
```
export MKL_VERBOSE=1
export MKL_THREADING_LAYER=sequential
python -c "import numpy as np; A=np.random.rand(1000,2000); B=np.random.rand(2000,1000); C=np.dot(A,B)"
```
### Expected output (because of MKL being verbose) with version 1.13.1

Pay attention to end of first line and the NThr value (it should be 1)

```
MKL_VERBOSE Intel(R) MKL 2018.0 Update 3 Product build 20180406 for Intel(R) 64 architecture Intel(R) Advanced Vector Extensions 2 (Intel(R) AVX2) enabled processors, Lnx 3.00GHz lp64 sequential
MKL_VERBOSE DGEMM(N,N,1000,1000,2000,0x7fffe1784e30,0x7fe6d9302010,1000,0x7fe6da245010,2000,0x7fffe1784e38,0x7fe6d8b60010,1000) 97.41ms CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:1
```

### Version 1.13.3 output
There's a new message displaying the value of the environment variable but it's misleading.
Scroll right and notice `sequential` became `intel_thread` and NThr != 1
```
Numpy + Intel(R) MKL: THREADING LAYER: sequential
MKL_VERBOSE Intel(R) MKL 2018.0 Update 3 Product build 20180406 for Intel(R) 64 architecture Intel(R) Advanced Vector Extensions 2 (Intel(R) AVX2) enabled processors, Lnx 3.00GHz lp64 intel_thread
MKL_VERBOSE DGEMM(N,N,1000,1000,2000,0x7ffdb4cc1c30,0x7f63a7724040,1000,0x7f63a8667040,2000,0x7ffdb4cc1c38,0x7f63a6f82040,1000) 55.40ms CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:24
```
Main concern for me is that this also affects other package loaded after numpy, creating oversubscription issues. Once mkl_rt.dll loads an implementation, it will not reload another later.

**Comment by charris** [comment]
I don't see that macro anywhere in NumPy, so suspect it is part of the Intel/Anaconda build.

**Comment by mlamarre** [comment]
Ok thanks, you can close this, I will bring my markdown message to their project.
