### ISSUE TITLE
ieee754.c.src build error

### ISSUE THREAD

**Issue by wenheping** [numpy/numpy#11288]
The line 587 in file numpy/core/src/npymath/ieee754.c.src : 
int npy_get_floatstatus_barrier(char * param))

shall I remove a ")" ?

**Comment by seberg** [comment]
I do not understand what you mean, but there was a fix along the lines of this which was just put in, see gh-11269. So my guess is you ran into that issue and simply should update.

**Comment by seberg** [comment]
Wait, what, yeah I guess so, please do. But why isn't this killing all our builds?

**Comment by wenheping** [comment]
I failed building it on NetBSD.

**Comment by seberg** [comment]
do you want to make a PR to fix this?

**Comment by wenheping** [comment]
You mean a PR in NetBSD or a PR in Github ?

**Comment by wenheping** [comment]
Anyway, I hope it could be fixed by upstream.

**Comment by seberg** [comment]
Here on github a pull request to numpy to get this fixed.

**Comment by charris** [comment]
@wenheping If you don't want to do it, I'll make the PR, I want to put out 1.14.5 fixing this (and another glitch) soon. I've looked through that set of changes again and don't see anymore fixes needed, at least until we hear from some of the platforms where source builds are less common.

**Comment by wenheping** [comment]
Thank you !

**Comment by charris** [comment]
@wenheping Have you tested that the build succeeds with this fix?

**Comment by wenheping** [comment]
Yes, succeeds with this fix. Thanks !
