### ISSUE TITLE
DOC : Some Properties is different from sample code(quickstart.html)@Windows 10 64bit.

### ISSUE THREAD

**Issue by mau34** [numpy/numpy#11289]
I got a different results in tutorial(https://docs.scipy.org/doc/numpy/user/quickstart.html).

I installed Python using the Anaconda distribution on Windows 10 64bit
and executed the sample code.

----------------Sample------------------
```
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
>>> a.shape
(3, 5)
>>> a.ndim
2
>>> a.dtype.name
'int64'
>>> a.itemsize
8
```

----------------My Environment----------
Windows10 Home 64bit
Python 3.6.5
numpy1.14.3
```
$pip freeze
numpy==1.14.3
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
>>> a.shape
(3, 5)
>>> a.dtype.name
'int32'
>>> a.itemsize
4
```

The following properties is different from the sample code and my environment.
    a.dtype.name
    a.itemsize

Is this due to the diffence in runtime environment(win10/linux/mac....)? # #

**Comment by seberg** [comment]
Yes, the default integer type is `long`, which is due to pythons integer being long (normally) in python 2.7. It is really annoying especially in python 3.x code, but just changing to 64bits is nontrivial anyway.
(In other words, the default integer is 32bits on all windows and 32bit linux -- probably also 32bit mac, but not sure).

That document could probably point out this shortly.

**Comment by alfredaita** [comment]
a = np.arange(15,dtype = 'int64').reshape( 3,5) will give 64 bit

**Comment by mau34** [comment]
I got the same result in tutorial.
It is important to specify dtype='int64'.
```
>>>import numpy as np
>>> a=np.arange(15,dtype='int64').reshape(3,5)
>>> a.dtype
dtype('int64')
```
Thanks!
