### ISSUE TITLE
np.datetime64 scalar constructor silently ignores dtype keyword argument

### ISSUE THREAD

**Issue by pumelo** [numpy/numpy#11302]
See the following example which returns True.
```
bytes(np.datetime64('2017-12-28T12:00:00.000000', dtype='M8[ns]').data) == bytes(np.datetime64('1970-01-18T12:41:02.400000000', dtype='M8[ns]').data)
```

The bottom line is, that the dtype keyword argument is silently ignored and the type of the datetime object is infered from how many zeros you append to the time string.

**Comment by eric-wieser** [comment]
I think here's the real cause
```
>>> np.datetime64('2017-12-28T12:00:00.000000', kwargs_are_completely_ignored=True)
numpy.datetime64('2017-12-28T12:00:00.000000')
```

**Comment by eric-wieser** [comment]
Great, turns out this is true of every numpy scalar type. Closing in favor of #11304 which is the root problem

**Comment by eric-wieser** [comment]
The correct way to spell what you're after is `np.datetime64('2017-12-28T12:00:00.000000', 'ns')`, by the way
