### ISSUE TITLE
BUG: Scalar type constructors take arbitrary kwargs then ignore them

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#11304]
`@name@_arrtype_new` has `kwds`, but uses `PyArg_ParseTuple` instead of `PyArg_ParseTupleAndKeywords`, which means that arbitrary keywords are accepted then ignored

Cause of #11302

**Comment by Bo887** [comment]
@eric-wieser Is this still up for grabs?

**Comment by eric-wieser** [comment]
Open issues should always be assumed up for grabs :)

**Comment by Bo887** [comment]
@eric-wieser Is this simply changing the call [here](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/scalartypes.c.src#L2808)?

Also, do you have a list of the keywords?
