### ISSUE TITLE
BLD: warning "document not included in any toctree" while building documentation

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#11316]
When building documentation, there are many tens of warnings `WARNING: document isn't included in any toctree`. It seems to be from class attribute `autoattribute` generated documentation. This might be a numpydoc issue, but it does not occur when building scipy documentation. Any hints where to debug this?

**Comment by rgommers** [comment]
There are warnings for SciPy, e.g.:
```
/home/rgommers/code/scipy/doc/source/generated/scipy.spatial.cKDTree.tree.rst: WARNING: document isn't included in any toctree
```

It's a numpydoc issue: https://github.com/numpy/numpydoc/issues/69
