### ISSUE TITLE
Import multiarray libgfortran.so.4 error

### ISSUE THREAD

**Issue by SietsmaRJ** [numpy/numpy#11322]
I'm having this issue for a while now, ever since i upgraded python, numpy and Manjaro to their latest versions. Since then i am unable to import multiarray.

Current Manjaro version: 17.1.10
Current python version: 3.6.5-3
Current numpy version: 1.14.3-1

This is what i get:
`python -c 'import numpy'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libgfortran.so.4: cannot open shared object file: No such file or directory`

But this is inside my /usr/lib/python3.6/site-packages/numpy/core folder:
/usr/lib/python3.6/site-packages/numpy/core sietsmarj% ls
arrayprint.py
cversions.py
defchararray.py
_dummy.cpython-36m-x86_64-linux-gnu.so
einsumfunc.py
fromnumeric.py
function_base.py
generate_numpy_api.py
getlimits.py
include
info.py
__init__.py
_internal.py
lib
machar.py
memmap.py
_methods.py
multiarray.cpython-36m-x86_64-linux-gnu.so
multiarray.so
multiarray_tests.cpython-36m-x86_64-linux-gnu.so
multiarray_tests.so
numeric.py
numerictypes.py
operand_flag_tests.cpython-36m-x86_64-linux-gnu.so
__pycache__
records.py
setup_common.py
setup.py
shape_base.py
struct_ufunc_test.cpython-36m-x86_64-linux-gnu.so
test_rational.cpython-36m-x86_64-linux-gnu.so
tests
umath.cpython-36m-x86_64-linux-gnu.so
umath_tests.cpython-36m-x86_64-linux-gnu.so

I'm really bummed, because now i can't use pulseeffects anymore :(

P.S.:
I have cython installed under version 0.28.3-2, when i try to install gcc-python-plugin it gives me a vertification error.

**Comment by SietsmaRJ** [comment]
Also, i have tried downgrading numpy and python, it didn't help (and yes, reinstalling was pretty much the first thing i did)

**Comment by mattip** [comment]
How did you get numpy? from the combination of `/usr/lib/python3.6/site-packages/numpy/core/init.py` and version 1.14.3, I am guessing you did `sudo pip ...`? That is not recommended, you would be better off letting apt manage your system and pip for local installs. 

With that, there are some hints around about needing gcc 7 to get libgfortran.so.4

**Comment by SietsmaRJ** [comment]
I have installed numpy through yaourt, but i think that still uses package manager "pacman" (sudo pacman -S python-numpy). GCC 7 libraries are installed, but this doesn't seem to really help.

{18-06-14 8:31}RASPUTIN:~ sietsmarj% yaourt gcc7
1 community/gcc7 7.3.1+20180406-2 [installed]
    The GNU Compiler Collection - C and C++ frontends (7.x.x)
2 community/gcc7-libs 7.3.1+20180406-2 [installed]
    Runtime libraries shipped by GCC (7.x.x)
==> Enter n° of packages to be installed (e.g., 1 2 3 or 1-3)
==> ---------------------------------------------------------
==> q
{18-06-14 8:31}RASPUTIN:~ sietsmarj% yaourt python-numpy
1 extra/python-numpy 1.14.3-1 [installed]
    Scientific tools for Python
2 aur/dynd 0.7.2-1 (1) (0.00)
    A dynamic array library (similar to python-numpy but written in C++).
3 aur/python-numpy-doc 1.13.0-1 (11) (0.00)
    Documentation for NumPy
4 aur/python-numpy-docs-devhelp 1.14.2-1 (0) (0.00)
    HTML documentation for Python NumPy with GNOME Devhelp support
5 aur/python-numpy-mkl 1.14.2-1 (28) (1.44)
    Scientific tools for Python compiled with intel mkl
6 aur/python-numpy-openblas 1.14.3-1 (Out of Date) (17) (0.28)
    Scientific tools for Python - built with openblas
7 aur/python-numpy-stl 2.5.0-1 (1) (0.00)
    Simple library to make working with STL files (and 3D objects in general) fast and easy.
8 aur/python-numpydoc 0.7.0-1 (Out of Date) (12) (0.22)
    Sphinx extension to support docstrings in Numpy format
==> Enter n° of packages to be installed (e.g., 1 2 3 or 1-3)
==> ---------------------------------------------------------
==> q

How would you suggest i install it?

**Comment by SietsmaRJ** [comment]
UPDATE:
It was a problem with pacman.
I installed numpy and scipy though `sudo pip...` .. now pulseeffects works again :smile: 
PIP actually has 1.14.5 available already, pacman not yet. This might be the source (from what i've seen around here)

Case closed!
