### ISSUE TITLE
Python 3.5 build on Travis-CI is failing on master

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#11343]
See https://travis-ci.org/numpy/numpy/jobs/392780581

```
Network availability confirmed.

3.5 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.5.tar.bz2
$ curl -sSf -o python-3.5.tar.bz2 ${archive_url}
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
```

My guess is that this is a Travis-CI issue which will resolve itself eventually. I don't think we've even gone to any NumPy specific configuration by the time the build fails.

**Comment by eric-wieser** [comment]
I restarted the job and all seems fine again

**Comment by charris** [comment]
It goes on and off. Travis is having problems, I don't know why.
