### ISSUE TITLE
np.bool_ has wrong-looking comparisons (different from the np.bool_ != bool issue)

### ISSUE THREAD

**Issue by bobby-edo** [numpy/numpy#11346]
Environments: locally on numpy 1.13.3 / python 2.7.10 and python.org/shell, numpy 1.12.0, python 3.6.0

import numpy as np
a = np.bool_(False)
print(type(a), type(not(a)))
print([a, not(a), not(a) is False, not(a) is True, True is False])

First line is (<type 'numpy.bool_'>, <type 'bool'>)  (expected)
Second line is [False, True, True, True, False]
In particular, "not(a)" claims to be a builtin 'bool' that has True "is" comparisons to both the literal "True" and "False".

**Comment by seberg** [comment]
This is correct, `is`is an identity operator, and the numpy scalars are a different type behaving much the same as pythons type.

As per python rule `bool(numpy_bool)` will return python True/False. And `not object` is the same as `not bool(object)`.

**Comment by eric-wieser** [comment]
There is nothing we can do about this. `type(not x) is bool` is true no matter how `x` is defined.

The workaround is to use `~x` instead of `not x` - which is already necessary for arrays anyway

**Comment by bobby-edo** [comment]
Thank you. Also, my coleague informed me that 
Edit: my colleague informed me that 
(not(x) is False, not(x) is True)
evaluates to 
(True, True)
for most python arguments x, such as (None, 0, 1, "hi")

**Comment by charris** [comment]
Careful of operator precedence
```
In [1]: (not np.bool_(False)) is False
Out[1]: False

In [2]: not np.bool_(False) is False
Out[2]: True
```
