### ISSUE TITLE
BUG: np.sctypeNA['i8'] and np.sctypeNA['f8'] have different semantics

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#11341]
Part of cleaning up `numerictypes.py`. The following looks wrong to me:

```python
>>> np.sctypeNA['i8']  # any integer type
<type 'numpy.int64'>
>>> np.sctypeNA['f8']  # any non-integer type
'Float64'
```

Surely these should both return `type` objects, rather than sometimes returning strings?

**Comment by eric-wieser** [comment]
According to #997, looks like these should actually both return strings

**Comment by eric-wieser** [comment]
Looks like these have been wrong for all of time (03d6cb12fa1137055d33197d1953752d2dbcdc10)

**Comment by mattip** [comment]
We could just deprecate `sctypeNA`, it seems undocumented and unused. A quick grep shows no use of it in scipy. The same for `typeNA`.

**Comment by eric-wieser** [comment]
I'd be completely on board with that. Also:
```python
>>> np.typeNA is np.sctypeNA
```
