### ISSUE TITLE
ENH: tests should cover all code paths

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#11369]
A catch-all issue about lack of testing

We do not run tests with a tool like coverage. It seems we don't even test all the `kwargs` for user-facing functions. Often the `out` argument is not tested at all.

**Comment by pv** [comment]
scipy has a working gcov+codecov setup on case that's of interest. Of the
3rd party coverage CIs, in my experience codecov was better than coveralls
at least some years ago.

ma 18. kesäkuuta 2018 klo 5.10 Matti Picus <notifications@github.com>
kirjoitti:

**Comment by eric-wieser** [comment]
We now have a coverage tool running. Should we leave this open, representing "coverage is not 100%", or can this be closed?

**Comment by tylerjereddy** [comment]
Could maybe close -- if 100 % is a target does that mean we want to thoroughly test "vendored" (fft stuff?) code as well.

I wish there were more options for CI coverage in the ecosystem. codecov doesn't even work for SciPy anymore, apparently because of the size of the reports, which worries me if we ever try to expand our coverage to include an aggregation of reports from platforms / Python versions, etc.

**Comment by seberg** [comment]
We should aim for 100%, but since I doubt we will make a coordinated effort for that any time soon, I will close it.

It may make sense to open an issue about specific bad files, or a tracking issue listing them, though.

**Comment by seberg** [comment]
Or, we reopen this/create a new one that gives some information on how to approach getting there, so newcomers can try to dive into the code by writing tests.

**Comment by tylerjereddy** [comment]
I think closing in favor of discrete engineering tasks / issues is the right choice -- clicking on the codecov badge on our readme provides a portal to assessing the situation, albeit not with the best interface. I think we may also have options with Azure reports for coverage, but hard to gauge priority on that kind of stuff.

Hopefully there isn't too much contention around the suggestion that we've certainly improved in testing / coverage thoroughness recently.

There seems to be a new set of concerns about the environmental footprint of our testing infrastructure, but that's another discussion, and certainly I'm not in favor of short-term test compromises to save electricity, but longer-term structured plans should obviously be considered to avoid waste.
