### ISSUE TITLE
Fail to import Numpy in Hydrogen/Atom although it works fine in the terminal

### ISSUE THREAD

**Issue by bjce** [numpy/numpy#11360]
I'm trying to import numpy with command `import numpy` but i get this strange error which seems to be related to another of my file.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-d4cdadb62aa7> in <module>()
----> 1 import numpy

~/Downloads/numpy.py in <module>()
----> 1 from numpy import genfromtxt
      2 my_data = genfromtxt('/Users/mymac/Documents/PyQt/image_viewer/csv_file_generator/eggs.csv',
      3     delimiter=',',
      4     dtype=None,
      5     encoding=None)

ImportError: cannot import name 'genfromtxt'
```

when running the following command line from the terminal it works fine: 
`$ python3`
`>>> import numpy`

**Comment by rgommers** [comment]
probably an issue with your PYTHONPATH within Hydrogen. Try `import numpy` there, probably you'll get the same, it'll be unrelated to `genfromtxt`.

**Comment by bjce** [comment]
Many thanks @rgommers, do you have an idea of how to change my PYTHONPATH within Hydrogen?

**Comment by rgommers** [comment]
not  in the IDE, never used it. But you can first check that that's the issue by inspecting `sys.path` within Hydrogen (the `site-packages` dir in which you have numpy installed should be there, but it's likely missing). Then if you can't find an IDE setting, you can work around it by doing `sys.path.insert(0, 'the-right-path')`.

**Comment by bjce** [comment]
@rgommers thank you for answer. It worked. Is there a way to insert those different path in a permanent manner so that I don't have to insert those lines at the beginning of each script: 

```
import sys
sys.path.insert(0, '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip')
sys.path.insert(0, '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6')
sys.path.insert(0, '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload')
sys.path.insert(0, '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages')
```

**Comment by rgommers** [comment]
> Is there a way to insert those different path in a permanent manner 

Normally the IDE should get those settings from your `.bash_profile` or similar. If it's different, then it will be an IDE-specific setting. So I think that's a matter of hunting around in the Hydrogen settings, or asking on a Hydrogen mailing list / issue.

**Comment by bjce** [comment]
many thanks @rgommers!

**Comment by njsmith** [comment]
There might be something messed up with your path, I don't know, but the first thing I would fix is:

> ~/Downloads/numpy.py

When you import a module in python, then by default the first place Python looks (the first thing on `sys.path`) is the directory where your script lives. In this case, you have a file called `numpy.py`, so if you have a script in the same directory that does `import numpy`, then it will find *your* `numpy.py` and try to import it, instead of the real numpy package.

So before you go down the rabbit hole with `.bash_profile` and Hydrogen settings and stuff, try renaming `numpy.py` to something else.

**Comment by njsmith** [comment]
```
~$ python3
>>> import sys
>>> sys.path
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/njs/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
```

Notice that weird empty string `''` at the beginning of the default `sys.path`? That's a quirk of Python's import system: it's a magic value that when you're running a script means "whatever directory the script is in", and when you're running interactively means "whatever directory you're running this in".

**Comment by bjce** [comment]
many thanks again @njsmith 

I indeed see that empt string `''` at the beginning of the defaulf `sys.path`

however I'm still running into trouble : I'm trying to run a script from Atom/Hydrogen and get an error `ModuleNotFoundError: No module named 'PySide'`. When running the exact same script in Spyder, it works fine.

When looking at the `sys.path` in Atom/Hydrogen and Spyder, they turn out to be exactly the same

- from Atom/Hydrogen:

```
import sys
sys.path

['',
 '/anaconda3/lib/python36.zip',
 '/anaconda3/lib/python3.6',
 '/anaconda3/lib/python3.6/lib-dynload',
 '/anaconda3/lib/python3.6/site-packages',
 '/anaconda3/lib/python3.6/site-packages/aeosa',
 '/anaconda3/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg',
 '/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/Users/mymac/.ipython']
```

- In Sypder: 

```
import sys

sys.path
Out[5]: 
['',
 '/anaconda3/lib/python36.zip',
 '/anaconda3/lib/python3.6',
 '/anaconda3/lib/python3.6/lib-dynload',
 '/anaconda3/lib/python3.6/site-packages',
 '/anaconda3/lib/python3.6/site-packages/aeosa',
 '/anaconda3/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg',
 '/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/Users/mymac/.ipython']
```

I have to say that I unfortunately still don't understand the problem
