### ISSUE TITLE
Need mailmap entry for 1.15

### ISSUE THREAD

**Issue by charris** [numpy/numpy#11361]
Hi Many,

I'm looking for full names (and maybe mailing addresses) for the following NumPy contributors

* [x] @zuko3d
* [x] @tynn 
* [x] @siavashserver
* [ ] @mamrehn
* [x] @luzpaz 
* [x] @lumbric 
* [x] @guoci
* [x] @fo40225
* [x] @fivemok

If you are one of the preceding, please add to this issue if you want your name to appear correctly as a contributor to the NumPy 1.15.0 release.

**Comment by zuko3d** [comment]
Hi, zuko3d -> Dmitriy Shalyga.

**Comment by guoci** [comment]
Guo Ci
zguoci@gmail.com

**Comment by fo40225** [comment]
fo40225 -> Ching Hsu

**Comment by siavashserver** [comment]
Siavash Eliasi
siavashserver@gmail.com

**Comment by luzpaz** [comment]
Please keep @luzpaz as the contributors name, thanks!

**Comment by fivemok** [comment]
Nick Minkyu Lee
mknicklee@protonmail.com

**Comment by tynn** [comment]
@tynn is fine

**Comment by lumbric** [comment]
Please use "@lumbric".
