### ISSUE TITLE
BUG: Wrong axis number in error message

### ISSUE THREAD

**Issue by mdickinson** [numpy/numpy#11378]
I'm seeing a confusing error message when doing fancy indexing on a 1d NumPy array. The error message is "index 10 is out of bounds for axis 1 with size 5", but the array in question is 1d, so only has a single axis. I would have expected "index 10 is out of bounds for axis 0 with size 5". See the interpreter session below (NumPy master branch at 717840c91029ac0680110838eec0103d23ccb32c; Python 3.6.5; macOS 10.13.5). I can also reproduce on NumPy 1.14.5/Python 3.6.5 and NumPy 1.13.3/Python 2.7.13.

```python
taniyama:numpy mdickinson$ python
Python 3.6.5 (default, Mar 29 2018, 15:37:32) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np
<module 'numpy' from '/Users/mdickinson/Desktop/numpy/numpy/__init__.py'>
>>> np.arange(5)
array([0, 1, 2, 3, 4])
>>> np.arange(5)[[0, 1, 10]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 10 is out of bounds for axis 1 with size 5
```

**Comment by eric-wieser** [comment]
Can't reproduce:
```
In [18]: np.arange(5)[[0, 1, 10]]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-18-f75ad3520681> in <module>()
----> 1 np.arange(5)[[0, 1, 10]]

IndexError: index 10 is out of bounds for axis 0 with size 5
```

**Comment by mdickinson** [comment]
Interesting; just tested on Windows (Windows 10, Python 2.7.13, NumPy 1.13.3), and can't reproduce there. This seems to be either macOS-specific, or specific to my machine. I'll check with colleagues to see if I can eliminate the second possibility.

**Comment by seberg** [comment]
Jupp: https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/lowlevel_strided_loops.c.src#L1440
That says 1, not 0.

**Comment by mdickinson** [comment]
Thanks for the speedy resolution! (FTR, I did check with colleagues; needless to say, they could reproduce.)
