### ISSUE TITLE
numpy.sqrt doesn't output array if input has shape ()

### ISSUE THREAD

**Issue by tobiasfeil** [numpy/numpy#11386]
I just came across this behavior:

![image](https://user-images.githubusercontent.com/17533713/41655993-e32e6370-748e-11e8-99ad-944d97c32acd.png)

I expected that the ouptut of `np.sqrt(4)` would be `array(2.)` and not `2.`. Since the documentation says this method outputs an array, I propose to change the output to `np.array(2.)`.

**Comment by seberg** [comment]
I agree, but it would require at least a major version bump, and we have already issues open for this, for example gh-6051 (and probably more)

**Comment by seberg** [comment]
Also note that this is true for almost all functions, not just sqrt.

**Comment by seberg** [comment]
Sorry, actually I disagree ;). `np.sqrt(np.array(4))` should be an array 2, the scalar case is probably good with just staying a scalar though. But the fact is, it always returns scalars for the time being.
