### ISSUE TITLE
BUG: pad with edge mode fails for object types

### ISSUE THREAD

**Issue by pimdh** [numpy/numpy#11395]
The following works as expected:
```
np.pad(np.array([1]), [(1, 0)], 'edge')
# => array([1, 1])
```
But the following fails:
```
np.pad(np.array([None]), [(1, 0)], 'edge')
# => {AttributeError}'NoneType' object has no attribute 'reshape'
```
This is because in [`_prepend_edge`](https://github.com/numpy/numpy/blob/a5d8ab86bfb29bd41ae56e81914b885143a2ff78/numpy/lib/arraypad.py#L189) and [`_append_edge`](https://github.com/numpy/numpy/blob/a5d8ab86bfb29bd41ae56e81914b885143a2ff78/numpy/lib/arraypad.py#L217) it is assumed that the indexing returns a numpy scalar or array. This is the case for most types, but apparently not for `np.object_` if a single value is retured. I suppose this can be fixed by wrapping `edge_arr` in `np.asarray()`.

Shall I submit a PR?

**Comment by eric-wieser** [comment]
I think this might already be fixed in master?

**Comment by eric-wieser** [comment]
A PR to contribute a test would certainly be welcome though

**Comment by lagru** [comment]
Small reminder: I think this is fine to close with the addition of the regression test in #11395... :)

**Comment by seberg** [comment]
Thanks for the heads up @lagru, will close this then if there is a test merged. I agree, your new code at least seemed safe in this way.
