### ISSUE TITLE
random tag appeared on https://github.com/numpy/numpy/tags

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#11404]
https://github.com/numpy/numpy/releases/tag/untagged-65f99747b229ae7de4cc

@mhvk I assume that's an accident. any idea how you did that?

**Comment by eric-wieser** [comment]
The accidental branches are a result of contributors using the edit on github interface. Unfortunately, once you become a contributor, those buttons no longer operates on your fork

**Comment by charris** [comment]
No idea where they came from, but my guess is that they happened when pushing to directly to the branch. I think the random branches came from online edits. I delete some now and then. Not that the tags aren't "real" tags, they are something generated by github. Also, even when there was a real 1.15.0rc1 tag, I had to edit the name.

**Comment by mhvk** [comment]
Did I actually do this? I did not edit on github, nor pushed to master directly.

**Comment by rgommers** [comment]
> The accidental branches are a result of contributors using the edit on github interface. Unfortunately, once you become a contributor, those buttons no longer operates on your fork.

Hmm, annoying. There doesn't seem to be any way to change that behavior or disable the editor.

**Comment by rgommers** [comment]
> Did I actually do this? I did not edit on github, nor pushed to master directly.

GitHub usually isn't wrong about that. Maybe you pushed to a branch?

**Comment by charris** [comment]
@mhvk I wonder if you were logged into numpy rather than your own account? Although how you pushed to a branch is strange. Then again, the tag was a bit strange ...

**Comment by mhvk** [comment]
I never even tried logging in under numpy (and assumed that was not possible!)

**Comment by mattip** [comment]
all is cleaned up, closing
