### ISSUE TITLE
Document tracemalloc support and usage for debugging

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#11408]
The only info I could find was [this note in the release]( https://docs.scipy.org/doc/numpy/release.html#support-for-tracemalloc-in-python-3-6 ). Would be nice to have some docs explaining what this is and showing how to use it.

**Comment by juliantaylor** [comment]
I'd rather deprecate the tolols (so remove them from the  sdist again). They are obsolete with the tracemalloc support we added a  while back.

**Comment by jakirkham** [comment]
That’s unrelated.

**Comment by seberg** [comment]
This exists [here](https://numpy.org/doc/stable/reference/c-api/data_memory.html#example-of-memory-tracing-with-np-lib-tracemalloc-domain) now.

**Comment by jakirkham** [comment]
> This exists [here]( https://numpy.org/doc/stable/reference/c-api/data_memory.html#example-of-memory-tracing-with-np-lib-tracemalloc-domain ) now.

Thanks Sebastian! 🙏

cc @stuarteberg (in case this is of interest)
