### ISSUE TITLE
tuple or list in numpy.empty

### ISSUE THREAD

**Issue by wesszabo** [numpy/numpy#11410]
In the documentation of  `numpy.empty(shape, dtype=float, order='C')`  
the  `shape : int or tuple of int`.  ([https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.empty.html](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.empty.html))
However in example `shape` is a list of int,
`np.empty([2, 2])`.

In the page [https://docs.scipy.org/doc/numpy-1.14.0/index.html](https://docs.scipy.org/doc/numpy-1.14.0/index.html)
"The preferred way to update the documentation is by submitting a pull request on Github (see the  [Developer Guide](http://docs.scipy.org/doc/numpy-dev/dev/))."
Unfortunately the above link is dead.

**Comment by mattip** [comment]
So that's two issues, although the broken link has been fixed for the upcoming 1.15 release. The proper link is https://docs.scipy.org/doc/numpy/dev/, the `numpy-dev` has turned into `numpy`

The example still shows list-of-ints in the latest documentation. PR welcome

**Comment by pulkitmaloo** [comment]
This is already fixed.
