### ISSUE TITLE
Suggestion in warning message about non-tuple indexing could be clearer

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#11411]
Right now non-tuple indexing raises a new FutureWarning:

```
/Users/goldbaum/Documents/yt-git-fixes/yt/fields/fluid_fields.py:217: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_field[slice_3d] = f
```

The problem is the suggestion to use `arr[tuple(seq)]` isn't always correct. In particular, if the elements of `seq` are all integers, `arr[tuple(seq)]` won't be the same thing as `arr[seq]`. I'd suggest editing the text of the warning to make a more qualified suggestion based on the types of the input.

**Comment by ngoldbaum** [comment]
Ah, I confused myself and thought I was getting the warning in all cases but it turns out that's wrong. Apologies for the noise.

**Comment by eric-wieser** [comment]
Do you think the message could be made clearer to make that confusion harder to fall into?

**Comment by ngoldbaum** [comment]
No I think it's fine as-is. I was debugging by putting a breakpoint that looked like this in the `__getitem__` implementation of my `ndarray` subclass:

```
def __getitem__(self, item):
    if isinstance(item, list):
        import pdb; pdb.set_trace()
    # do the rest of __getitem__
```

So I saw that my breakpoint was triggered by the case that isn't deprecated and doesn't generate a warning, but mistakenly thought that it was still a problem. I don't think you can make the warning message prevent people from making boneheaded assumptions like I did earlier.

I guess perhaps you could include a link to #9686 in the warning message itself (if linking to things on github in a warning is kosher) that would make it clearer why the deprecation happened when someone initially sees the warning.

**Comment by Katrina-Johnson** [comment]
I am new to using python, and got the following warning when using seaborn with matplotlib on a .csv dataframe.

FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`.  

I would welcome any suggestions regarding how to address this.

**Comment by eric-wieser** [comment]
@Katrina-Johnson: That is probably a matplotlib or seaborn problem, not one in your code. Have you tried updating to the latest versions of those packages?

**Comment by Katrina-Johnson** [comment]
I believe I should be using the latest version of both. n
I downloaded them within the past two months.

**Comment by eric-wieser** [comment]
Run `warnings.simplefilter('error')`, and paste the stack trace here. It will show the line of code in matplotlib / seaborn that is causing the issue, and then you can report the problem to them.

**Comment by itar-kh** [comment]
I am using python and got the following warning when using " scipy.stats"

error=(FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
)

**Comment by seberg** [comment]
@itar-kh such warnings should be expected if you use a newer numpy version with an older scipy one. If it comes from scipy.stats, you may want to simply ignore it, it is a warning so normally should just print out and that is it. I would be surprised if scipy is not long fixed, but if your scipy version is very recent it could be a scipy issue.

If this creates an error/exception, that means that the warnings were set up like this by you with the `warnings.simplefilter("error")` command above, I assume. Now that you know it originates in scipy, just set it back. Or update your scipy version to get rid of it.

Of course at some point numpy will go through with the change, and forward compatibility will break (you cannot use an arbitrarily new numpy with an old scipy at some point).

**Comment by durack1** [comment]
Hi folks, I've been routinely using calls like `b = a[0, ...]` or `b = a[0,]` etc, however it seems like this call now triggers this warning - how do I update myself to ensure that I work as numpy updates? I tried `b = a[(0,)]` but this doesn't seem to solve my problem?

**Comment by eric-wieser** [comment]
@durack1: What is `type(a)`?

**Comment by durack1** [comment]
@eric-wieser here you go:
```
type(s): <class 'cdms2.tvariable.TransientVariable'>
```
And this is the `cdms2` library: https://anaconda.org/conda-forge/cdms2/

**Comment by durack1** [comment]
@eric-wieser and following your `warnings.simplefilter('error') recommendation [above](https://github.com/numpy/numpy/issues/11411#issuecomment-445507078) here's the output:
```
type(s): <class 'cdms2.tvariable.TransientVariable'>
Traceback (most recent call last):
  File "make_CMxWOAClims.py", line 102, in <module>
    s           = s[(0,)]
  File "/export/durack1/anaconda2/envs/cdat81py2/lib/python2.7/site-packages/cdms2/avariable.py", line 1751, in __getitem__
    return self.getSlice(numericSqueeze=1, raw=0, isitem=1, *speclist)
  File "/export/durack1/anaconda2/envs/cdat81py2/lib/python2.7/site-packages/cdms2/avariable.py", line 881, in getSlice
    result = self.subSlice(*specs, **keys)
  File "/export/durack1/anaconda2/envs/cdat81py2/lib/python2.7/site-packages/cdms2/avariable.py", line 751, in subSlice
    d = self.expertSlice(slicelist)
  File "/export/durack1/anaconda2/envs/cdat81py2/lib/python2.7/site-packages/cdms2/tvariable.py", line 340, in expertSlice
    return numpy.ma.MaskedArray.__getitem__(self, slicelist)
  File "/export/durack1/anaconda2/envs/cdat81py2/lib/python2.7/site-packages/numpy/ma/core.py", line 3174, in __getitem__
    dout = self.data[indx]
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
```

**Comment by eric-wieser** [comment]
The warning is due to incorrect use within the `cdms2` package itself. You should file a bug report against that package.

**Comment by eric-wieser** [comment]
Already fixed upstream in this completely unintelligible PR: CDAT/cdms#296

**Comment by durack1** [comment]
@eric-wieser thanks for this, can you point out the issue resolution in the PR CDAT/cdms#296 - I assume this is in `avariable.py`?

**Comment by eric-wieser** [comment]
tvariabke.py

**Comment by durack1** [comment]
@eric-wieser ok got you and https://github.com/CDAT/cdms/pull/296/files#diff-c02b6d92e7f86eadf6ebfab79653266aR398 - correct?

**Comment by Xunius** [comment]
It might have something to do with that I'm not a native English speaker, I also found this warning message confusing. Is it mentioned anywhere in the numpy documentation about this, some recommended ways of doing indexing and the discouraged ways? I just re-read the [v1.17 manual](https://docs.scipy.org/doc/numpy/user/basics.indexing.html#index-arrays) and I didn't find any, or maybe I just missed something obvious?

Could you give some examples on when the results will be different? Because it is said that "which will result either in an error or a different result." I'm a bit worried about the "different result" part because there might be such things somewhere in my rather non-professional code that will silently break the program.

**Comment by seberg** [comment]
I doubt the rules are spelled out there, I have spelled them out before in issues probably, but they are pretty weird (which is the whole point of the deprecation). The **new** rules however are simple:

1. Are you (normally) indexing into more then one dimension?
    * You want to use `arr[tuple(index)]`.
2. Is `arr[np.array(index)]` a sensible thing? (i.e. you have an array index into *one* dimension):
    * You want to use `arr[np.array(index)]` *or* `arr[index,]` (note the extra comma!)

And yes, those two points are definitely mentioned in the docs, but there is a bit of annoying thing where we have two distinct documentions. The *reference* documentation somewhat covers this here:
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing

**Comment by eric-wieser** [comment]
> note the extra comma!

Also worth noting that the purpose of this deprecation is to eventually make that extra comma unnecessary.

**Comment by jjacobson95** [comment]
I'm also a bit confused about this wording / how to fix my code to avoid this.   It would be some work on your end, but a really useful feature for the error message could be to provide the updated code. 

For example, if warning was caused to to this line:
`predictions = pd.DataFrame(Kmer_Count_Totals.columns[Sorted_vals][:, :1])`

The warning could read: 

> /Users/jaco059/miniconda3/envs/snekmer_kmer_association/lib/python3.10/site-packages/pandas/core/indexes/base.py:5055: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = getitem(key)
/var/folders/wt/_yr7rg_13t76sq_q5cw57hxw0000gn/T/ipykernel_33055/3189755255.py:135: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
Previous Usage: predictions = pd.DataFrame(kmer_count_totals.columns[sorted_vals][:, :1])
Updated Usage: predictions = pd.DataFrame(kmer_count_totals.columns[sorted_vals][tuple(slice(None),:1)]) 
^ Or however it should look - I am unsure...
