### ISSUE TITLE
Please provide Python 3.7 wheels

### ISSUE THREAD

**Issue by hroncok** [numpy/numpy#11418]
Please, provide wheels for Python 3.70rc1 on PyPI. This would allow consumers of NumPy to test their code faster with 3.7. Thank you.

**Comment by matthew-brett** [comment]
It wasn't all that straightforward, but Python 3.7 wheels should now be available on PyPI.

**Comment by hroncok** [comment]
Thank you!

**Comment by hugovk** [comment]
Thanks! Confirmed wheel available for macOS High Sierra.
```console
[hugo:~/github] 5s % pip install -U numpy
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/a0/31/f01ac16f0e8adbb94cd4e3de4920b49a470cf4ca7d452eefd960d4b0248f/numpy-1.14.5-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.7MB)
    100% |████████████████████████████████| 4.7MB 1.1MB/s
Installing collected packages: numpy
Successfully installed numpy-1.14.5
[hugo:~/github] 14s %
```
Can this issue be closed?

**Comment by seibert** [comment]
@matthew-brett: We're trying to build Python 3.7 wheels for Numba, and curious how you got a working manylinux1 Python 3.7 environment.

**Comment by matthew-brett** [comment]
I didn't do anything special for manylinux1 - the container took care of it for me - what problems are you having?
