### ISSUE TITLE
np.linalg.qr: handle empty matrices

### ISSUE THREAD

**Issue by convexset** [numpy/numpy#11412]
This may seem silly, but raising exceptions for mathematically legitimate request causes problems downstream.

See: https://github.com/dask/dask/issues/3659 (weird case of distributed computation where there is an empty 0×n matrix that needs to be handled by `np.linalg.qr`; this happens when a distributed array of blocks blocks, called chunks in dask, are filtered, and it is unknown a priori which blocks, if any, are empty)

There are two cases, both of which are "mathematically legitimate":
 - 0×n  ->  `q` is 0×0 and `r` is 0×n
 - m×0  ->  `q` is m×0 and `r` is 0×0

If this suggestion is found to be reasonable, I'll create a PR.

**Comment by convexset** [comment]
Same issue applies to `np.linalg.svd`:

 - 0×n -> u is 0×0, s is (0,) and vh is 0×n
 - m×0 -> u is m×0, s is (0,)  and vh is 0×0

**Comment by convexset** [comment]
Notably, the correct thing happens with `np.linalg.eig` and `np.linalg.eigh`.
```
>>> np.linalg.eig(np.zeros((0, 0)))
(array([], dtype=float64), array([], shape=(0, 0), dtype=float64))
```
and
```
>>> np.linalg.eigh(np.zeros((0, 0)))
(array([], dtype=float64), array([], shape=(0, 0), dtype=float64))
```

**Comment by njsmith** [comment]
I haven't thought through the correct semantics for these particular operations. But the general trend is that all the linalg operations used to error out on zero-sized inputs, usually for no particularly good reason, and we've been gradually fixing them to handle these edge cases better. So your general proposal here is totally uncontroversial; please go ahead with that PR.

**Comment by eric-wieser** [comment]
There's an open issue about at least one of svd and qr - if you can find it, I think some semantics were discussed there.

**Comment by eric-wieser** [comment]
Duplicates #8654, although it looks like there's no discussion there after all

**Comment by convexset** [comment]
Ah yes. Noticed that least squares had the same issue because of the same assertion being called.

In the 0×n case, the output should be `np.zeros(n)`, and for the n×0 case, `np.zeros(0)`... Funny how there generally will be a non-zero residual in the latter case.

**Comment by eric-wieser** [comment]
@convexset: `svd` is a problem when `full=true`. It has signature:

    (m,n)->(m,m),(k),(n,n)

where `k = min(m, n)`, and the variables are `a = u, s, vh`

So what should the value of the non-empty `vh` be when `a = np.empty((0, 4))`?

**Comment by convexset** [comment]
Hmmm... for the "full"/"complete" cases...
 - svd(m, 0) -> eye(m), np.zeros(0), np.zeros((0, 0))
 - svd(0, n) -> np.zeros((0, 0)), np.zeros(0), eye(n)
 - qr(m, 0) -> eye(m), np.zeros((m, 0))
 - qr(0, n) -> np.zeros((0, 0)), np.zeros((0, n))

**Comment by eric-wieser** [comment]
That `svd` behaviour matches Julia:

https://tio.run/##yyrNyUw0@/@/UsFWwSmxOFXPJzPPMSddr7gsJS0xuUSjKrUov1jDREfBQFNHoSQjM882LTGnOFWTq6AoM68kJ0@jUvP/fwA

**Comment by eric-wieser** [comment]
The first step for fixing this for `qr` would probably be to vectorize qr via a gufunc

**Comment by convexset** [comment]
PR for `qr`: https://github.com/numpy/numpy/pull/11593 (Sorry, got busy.)

**Comment by convexset** [comment]
PR for `lstsq`: https://github.com/numpy/numpy/pull/11594

**Comment by convexset** [comment]
I'll close this and continue the discussion in pre-existing issue https://github.com/numpy/numpy/issues/8654
