### ISSUE TITLE
numpy.array(10).tolist() will return a number

### ISSUE THREAD

**Issue by marcelotrevisani** [numpy/numpy#11413]
I was wondering if it's a bug.

if the user execute:
```python
array_one = numpy.array(10)
array_one.tolist()
10
```
I know that the right way to use the method ``array`` is to pass a list or a tuple to ``numpy.array``. However, it's a bit strange to allow the user to use in that way and even to execute the method ``tolist()`` which will return just a number instead of a list as expected.

**Comment by seberg** [comment]
Well, that function uses a nested list of the correct shape (except I guess for empty arrays where this is not possible) of pure python datatypes (when possible). So yeah, the name is a bit confusing in that sense, it is more like `to_python_nested_lists_of_scalar_or_scalar` if you want ;).

Or one could say, it returns the best python type approximating the array, and this is very unlikely to change, so I am closing the issue.

**Comment by seberg** [comment]
I did not check/understand quickly what this `pytest.approx` does though, that it wants to iterate the array, it seems likely that there may be some other way to achieve what you need to achieve? Unless this is a problem of arrays kind of looking like they can be iterated, but sometimes it is not possible?
