### ISSUE TITLE
Why auto-casting 1-d array to vector?

### ISSUE THREAD

**Issue by DDOwzw** [numpy/numpy#11421]
Suppose:
a = numpy.random.rand(3073, 10)
b = a[1]
why is b in the shape (10,) instead of (1, 10)?
I don't see any benefits for auto casting b into vector shape so far.
Instead, the b.shape[1] will be an index out of range error now.

**Comment by eric-wieser** [comment]
Broadly speaking, this is so that `a[1][2]` is the same as `a[1, 2]`.

You can get what you want here with `b = a[1:2]`
