### ISSUE TITLE
np.histogram erroneously emit warning when density=False

### ISSUE THREAD

**Issue by pllim** [numpy/numpy#11426]
As seen in https://travis-ci.org/ejeschke/ginga/jobs/395720074 . The actual code in Ginga calling histogram is:
```python
# get image histogram
hist, bins = numpy.histogram(some_array, hashsize, density=False)
```
Note that `normed` was not used. However, it caused this warning in Numpy ~~dev~~ prerelease:
```python
        else:
            if normed is not None:
                # 2018-06-13, numpy 1.15.0 (this was not noisily deprecated in 1.6)
                warnings.warn(
                        "Passing normed=False is deprecated, and has no effect. "
                        "Consider passing the density argument instead.",
>                       DeprecationWarning, stacklevel=2)
E               DeprecationWarning: Passing normed=False is deprecated, and has no effect. Consider passing the density argument instead.
```

I think this is caused by #11352 . When `density=False`, it goes into the logic block that forces `normed=False`, which resulted in it going into this logic block in `np.histogram()`:
```python
else:
    if normed is not None:
        ...
```

cc @ejeschke

**Comment by eric-wieser** [comment]
Introduced in #11323 / #11352

**Comment by eric-wieser** [comment]
Fixed in the above two PRs. Thanks for the report!
