### ISSUE TITLE
Error! numpy python library not detected!!

### ISSUE THREAD

**Issue by charlottecc** [numpy/numpy#11430]
Hi All,
I'm wondering if anyone can help me... I'm very new to programming. 

I have downloaded Metaphlan2 and all of its dependencies via Conda, in a conda environment. 

But I keep getting the Error message: Error! numpy python library not detected!!

When I check to see if numpy is installed and updated, it is. I tried python -c "import numpy; print numpy.__version__" but this gave the error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pub*/*/miniconda2/envs/metaphlan/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/pub*/*/miniconda2/envs/metaphlan/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/pub*/*/miniconda2/envs/metaphlan/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/pub*/*/miniconda2/envs/metaphlan/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/pub*/*/miniconda2/envs/metaphlan/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /lib/libc.so.6: version `GLIBC_2.10' not found (required by /pub*/*/miniconda2/envs/metaphlan/lib/python2.7/site-packages/numpy/core/multiarray.so)

I have tried to uninstall numpy from the python in your system, using pip uninstall and also removed the conda env containing metaphlan and redownloaded this. But I am still getting the same error? 

I'm unsure of how to fix this, does anyone have any ideas?

Thank you in advance!

**Comment by mattip** [comment]
What distribution of Linux are you running? In general, software you download, like anaconda, depends on your operating system to supply basic functionality, so assumptions are made as to the availability of general routines. Theses are tied into a library called glibc, supplied by the distribution running over the Linux kernel. Apparently your distribution is too old for anaconda. 

This is not a NumPy issue, rather one somewhere between anaconda and whatever distribution you are running.

Try searching "version `GLIBC_2.10' not found" (without the ") and add your distribution and version.

**Comment by charlottecc** [comment]
You were right, I changed the operating system I was using and it ran fine. 
Thank you very much for your help!

**Comment by Ariesissinging** [comment]
Hi Charlottecc, I got the same error message when I ran Metaphlan2. How did you change the operating system?

**Comment by charlottecc** [comment]
Hi, 

I am using a machine cluster at my university and was advised to use the chos command to change between the different operating systems which are available to me via our machines. 

I’m not sure whether that command is one you can use if you’re running Metaphlan2 by other means. I know that each of our operating systems have different versions of underlying programs and libraries, maybe if you update these it will work. 

Sorry for not being of much help!

Charlotte
