### ISSUE TITLE
numpy.sqrt() raises RuntimeWarning

### ISSUE THREAD

**Issue by orihime-tetsuro** [numpy/numpy#11448]
I have 1000*1000 numpy array, and it raises RuntimeWarning by numpy.sqrt().

I uploaded it (serialized as vhat.npy) here:
https://1drv.ms/u/s!ApqCp4zCguoNmp1PtS17b0AODskEJQ

vhat.npy has no negative numbers, no nan.

```
import numpy
data = numpy.load("vhat.npy")
numpy.sqrt(data) # RuntimeWarning: invalid value encountered in sqrt

numpy.sqrt(data[:, 0:900]) # no Warning
numpy.sqrt(data[:, 100:2000]) # no Warning
numpy.sqrt(data[:, ::-1]) # no Warning発

numpy.sqrt(data[:,:]) # RuntimeWarning: invalid value encountered in sqrt 
```

Environment: 
(1) Ubuntu 16.04, miniconda, numpy=1.14.2=py36hdbf6ddf_1, mkl=2018.0.2=1
(2) MacOS, anaconda, numpy=1.14.5=py36h9bb19eb_0, numpy-base=1.14.5=py36ha9ae307_0, mkl=2018.0.3=1

**Comment by eric-wieser** [comment]
```
np.signbit(data).any()
Out[4]: False
```

**Comment by orihime-akami** [comment]
@ewmoore 

```
In [9]: numpy.signbit(data)
Out[9]:
array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)

In [10]: numpy.signbit(-1)
Out[10]: True

In [11]: numpy.signbit(-0.0)
Out[11]: True
```

sadly, not negative zero...

**Comment by WarrenWeckesser** [comment]
FWIW, I can reproduce the warning reliably with `x = (np.random.rand(1000000)**8).astype(np.float32)`:

```
In [1]: np.__version__
Out[1]: '1.14.5'

In [2]: x = (np.random.rand(1000000)**8).astype(np.float32)

In [3]: r = np.sqrt(x)
/Users/warren/miniconda36b/bin/ipython:1: RuntimeWarning: invalid value encountered in sqrt
  #!/Users/warren/miniconda36b/bin/python

In [4]: x = (np.random.rand(1000000)**8).astype(np.float32)

In [5]: r = np.sqrt(x)
/Users/warren/miniconda36b/bin/ipython:1: RuntimeWarning: invalid value encountered in sqrt
  #!/Users/warren/miniconda36b/bin/python
```

If the warning is changed to an error, it becomes `FloatingPointError: underflow encountered in sqrt`:

```
In [6]: sv = np.seterr(all='raise')

In [7]: r = np.sqrt(x)
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
<ipython-input-7-39e7f2aabdd5> in <module>()
----> 1 r = np.sqrt(x)

FloatingPointError: underflow encountered in sqrt
```

**Comment by njsmith** [comment]
IIUC, "underflow" means that you're hitting [denormals](https://en.wikipedia.org/wiki/Denormal_number), i.e. numbers that are positive, but so close to zero that floating point is having trouble handling them. In *theory* this is a different thing than an "invalid" value, which is supposed to indicate a domain error. It's weird though that messing with `seterr` changes which one you get...

**Comment by WarrenWeckesser** [comment]
That's one of the first things I checked.  None of the values in the file linked to above are denormal:

```
In [10]: data = np.load("vhat.npy")

In [11]: x = data.ravel()

In [12]: x[x > 0].min()
Out[12]: 5.018529e-28
```

**Comment by mhvk** [comment]
Given your tests on top, order apparently is important, which makes this even weirder. Did it ever happen on smaller arrays (ie., a given row in your `data`)?

**Comment by WarrenWeckesser** [comment]
I suspect it involves SIMD and/or MKL.

**Comment by roebel** [comment]
I have the same problem on Linux debian 9 with numpy 1.13.3 under anaconda, here a few tests  on the ipython command line with mkl enabled  

In [33]: np.sqrt(np.finfo(np.float32).eps**6*np.ones(8192, dtype=np.float32));
In [34]: np.sqrt(np.finfo(np.float32).eps**6*np.ones(8192*2, dtype=np.float32));
/u/formes/share/packages/Anaconda3/bin/ipython:1: RuntimeWarning: invalid value encountered in sqrt
  #!/u/formes/share/packages/Anaconda3/bin/python

Using an install with mkl disabled, or using dtype=np.float64, or increasing the magnitude to eps**4 removes the warning.

Best
Axel

**Comment by orihime-tetsuro** [comment]
thank you for reproduction code.

**Comment by orihime-tetsuro** [comment]
This problem occured in 
> (2) MacOS, anaconda, numpy=1.14.5=py36h9bb19eb_0, numpy-base=1.14.5=py36ha9ae307_0, mkl=2018.0.3=1

environment. (MKL 2018 update 3)

**Comment by slinnarsson** [comment]
This is a very annoying bug. As far as I can tell, it affects `np.sqrt(a)` when

* Type is 32-bit float: `a.dtype == "float32"` 
* Length exceeds 8192 elements: `len(a) > 8192`
* There is at least one zero: `np.sum(a == 0) > 0`

Minimal code to reproduce the error is simply:

```python
import numpy as np
N = 8193
a = np.arange(N).astype('float32')
b = np.sqrt(a)
```

The warning occurs only for N > 8192 (which is suspiciously 2^13). `np.arange` can be replaced with `np.zeros` or `np.empty` and still get the warning. Replacing `float32` with any of `int32`, `int64` or `float64` suppresses the warning (at least around 8192). Replacing `sqrt` with `abs` or `mean` also suppresses the warning (though obviously the result is different).

Despite the warning, all the resulting values are exactly correct, compared to the builtin `sqrt`:

```python
>>> import math
>>> np.all(np.array([math.sqrt(a) for a in range(8193)]).astype('float32') == b)
True
```

Having a single zero in the array is sufficient to cause the warning:

```python
a = np.random.uniform(size=8193).astype('float32')
a[0] = 0.  # Remove this line to suppress the warning
np.sqrt(a)
```

On my machine,  `print(np.__version__,np.__mkl_version__)` returns `1.14.5 2018`.

**Comment by njsmith** [comment]
So according to https://github.com/ContinuumIO/anaconda-issues/issues/9129#issuecomment-380284038, not only is this a bug in a package we don't distribute (MKL), but triggering the bug requires that you be using a non-standard version of numpy that includes some patch that the anaconda team came up with. So... I think you need to talk to them; there's not a lot we can do about code we didn't write, don't distribute, and have never seen :-).

**Comment by juliantaylor** [comment]
anaconda overrides our sqrt function? why that? are they using multithreading there? Else I do not see the benefit, our code is pretty much as good as it gets (sqrt in avx is still serialized on 128 bit blocks)

I find it very worrying that a major numpy re-distribution patches this stuff by default. The reason we don't use vector math libraries ourselves is exactly because we know it breaks stuff.
