### ISSUE TITLE
How to install Numpy on OS 10.13.15 with Homebrew…

### ISSUE THREAD

**Issue by Kabel77** [numpy/numpy#11454]
I  hope this is the right channel for my question and hope you could help. I tried to install Numpy via Homebrew with this line:

> brew tap homebrew/science && brew install python numpy scipy matplotlib

And get the following error:

> Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.

What went wrong here and how could I solve it? Thanks…

**Comment by rgommers** [comment]
Homebrew is not the right way to install scientific python packages. Hence that deprecation message. If you're starting from scratch, use a distribution - see https://scipy.org/install.html

**Comment by matthew-brett** [comment]
If you're already using Homebrew, my personal recommendation is to install Python with Homebrew, and then install numpy, scipy, matplotlib with pip.  That's what I do, and I suspect that's what the Homebrew folks would recommend.

**Comment by Kabel77** [comment]
Thank you!

I have Python already installed. The line I have mentioned, I found it on the site you sent me:

> Homebrew
>
> You can install NumPy, SciPy, and Matplotlib, with:
>
> brew tap homebrew/science && brew install python numpy scipy matplotlib

I have Python 3.4 installed, and Pip must be installed with it normally, right? Sorry to ask again, but I do not find it – in terminal I get the message, that there is no module like this. I also do not find a way to do that. Please tell me, if there is an appropriate way to get help, I dont want to bother you.

Thanks, all best!


Am 29. Juni 2018, 19:44 +0200 schrieb Matthew Brett <notifications@github.com>:

**Comment by pv** [comment]
I note the page  https://scipy.org/install.html does have exactly that homebrew instructions --- if it's not valid any more, should be removed

**Comment by rgommers** [comment]
@Kabel77 Python 3.4 support is about to disappear from numpy and other packages, it's pretty much obsolete by now. You're better off install 3.6 at this point. Either with Homebrew, and then doing what @matthew-brett recommended, or just grab Anaconda py36.

**Comment by rgommers** [comment]
Hmm, outdated install instructions, it seems like an ever-returning issue:(

**Comment by rgommers** [comment]
No time to figure it out now; `brew install python` install Python 3.x, but does not alias `python` to `python3`? So just reopening.

I suspect the right thing to do is:
```
brew install python
# alias python to python3
python -m pip install numpy scipy ...
```

**Comment by mattip** [comment]
Closed by the PR to scipy.
