### ISSUE TITLE
Use python 3 for benchmarks?

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#11458]
Currently, benchmarks are only done on python2 [1]. Shouldn't this be python3? Or at least not only python2?

[1] `asv.conf.json` has `"pythons": ["2.7"],`; see
https://github.com/numpy/numpy/blob/master/benchmarks/asv.conf.json#L38

**Comment by rgommers** [comment]
Benchmarks are expensive, best to keep it to one Python version. Maybe bump from 2.7 to 3.7 soonish?

**Comment by pv** [comment]
FWIW, this won't affect what's on https://pv.github.io/numpy-bench/ so it's mainly a question of convenience for people running them themselves.

**Comment by shoyer** [comment]
It sounds like there's consensus on switching to 3.7 by default -- see https://github.com/numpy/numpy/pull/12331
