### ISSUE TITLE
BUG: fancy indexing assignment with strided np.intp writes into wrong positions

### ISSUE THREAD

**Issue by reineking** [numpy/numpy#11467]
Reading via fancy indexing works fine in this example:
```python
a = np.arange(6)
idx = np.arange(6).reshape(2, 1, 3)[:, :, 0]
print(a[idx])
[[0]
 [3]]
```

However, writing with the same index modifies the wrong elements:
```python
a[idx] = -1
print(a)
[-1 -1  2  3  4  5]
```

What is even stranger is that the issue disappears if you first copy the index:
```python
a = np.arange(6)
a[idx.copy()] = -1
print(a)
[-1  1  2 -1  4  5]
```

This also seems to be related to the index shape because the following works as expected:
```python
a = np.arange(6)
a[np.arange(6).reshape(2, 3)[:, 0]] = -1
print(a)
[-1  1  2 -1  4  5]
```

**Comment by seberg** [comment]
Fancy indexing does not know about memory overlap of index and array (or array and assigner), there is an issue open about it. And yeah, never thought about it so much, but you can horribly break things doing things like that (i.e. no copy of idx).
OTOH, it seems pretty theoretical that the index points to the same memory as the array itself in practice. We still should fix it, there is an issue about adding the memory overlap detection to indexing, though I think the overlap of assigned and data array is probably more important then assigned array and index, that will give you wrong results as well.
Also this is less likely and will easily crash the seesion, just set the RHS to something large in your examples.

**Comment by eric-wieser** [comment]
@seberg: I see no memory overlap between `a` and `idx` here

**Comment by seberg** [comment]
Ooooops :)

**Comment by eric-wieser** [comment]
@reineking: I can't reproduce this on master:
```python
>>> a = np.arange(6)
>>> idx = np.arange(6).reshape(2, 1, 3)[:, :, 0]
>>> a[idx] = -1
>>> a
array([-1,  1,  2, -1,  4,  5])
```

What version of numpy are you using?

**Comment by reineking** [comment]
1.14.5. I did not test on master.

**Comment by seberg** [comment]
@eric-wieser I can reproduce it, can you verify that your idx is of `np.intp` type? At least then I can guess what is going on, it must be going into the 1D fastpath and then use the incorrect stride for the indexing array. At least I hope that it is, strange that the tests never found it :(

**Comment by eric-wieser** [comment]
@seberg: Bingo, I'm on windows and the default integer type is int32, but intp is int64.

**Comment by seberg** [comment]
Yeah, I really did not expect a bug like that in indexing anymore :(. It may be a rare bug, this one is a real high priority one. @charris added a 1.15.0 release milestone, feel free to move it if it is holding things up,this has been there since 1.9. at least after all, but shouldn't lose track of it...

**Comment by seberg** [comment]
OK, the bug is practically a typo :( :

```diff
diff --git a/numpy/core/src/multiarray/mapping.c b/numpy/core/src/multiarray/mapping.c
index 46ff78b9c..cdca1d606 100644
--- a/numpy/core/src/multiarray/mapping.c
+++ b/numpy/core/src/multiarray/mapping.c
@@ -2084,7 +2084,7 @@ array_assign_subscript(PyArrayObject *self, PyObject *ind, PyObject *op)
                                                PyArray_TRIVIALLY_ITERABLE_OP_READ,
                                                PyArray_TRIVIALLY_ITERABLE_OP_READ) ||
                  (PyArray_NDIM(tmp_arr) == 0 &&
-                        PyArray_TRIVIALLY_ITERABLE(tmp_arr))) &&
+                        PyArray_TRIVIALLY_ITERABLE(ind))) &&
                 /* Check if the type is equivalent to INTP */
                 PyArray_ITEMSIZE(ind) == sizeof(npy_intp) &&
                 PyArray_DESCR(ind)->kind == 'i' &&
```
The fast path only work with 1D indices (the trivial iteration does), I am wondering a bit if we can sprinkle a few asserts into the TRIVIAL loop setup functions.

**Comment by seberg** [comment]
I also suggest trying to add:
```diff
--- a/numpy/core/src/private/lowlevel_strided_loops.h
+++ b/numpy/core/src/private/lowlevel_strided_loops.h
@@ -701,6 +701,7 @@ npy_bswap8_unaligned(char * x)
                         )
 
 #define PyArray_TRIVIAL_PAIR_ITERATION_STRIDE(size, arr) ( \
+                        assert(PyArray_ISONESEGMENT(arr)); \
                         size == 1 ? 0 : ((PyArray_NDIM(arr) == 1) ? \
                                           PyArray_STRIDE(arr, 0) : \
                                           PyArray_ITEMSIZE(arr)))
```
I am not sure I will write tests and stuff timely, so pleaes feel free to pick it up.

**Comment by seberg** [comment]
Couldn't really think of more tests, but gh-11468 fixes the bug with the example from here as a test.
