### ISSUE TITLE
numpy.random.choice is super slow for choosing a single element (~100x slower)

### ISSUE THREAD

**Issue by karttikeya** [numpy/numpy#11476]
I have a loop for reading a file line by line and processing it which among other things picks a random sample from all the lines seen till the point, say stored in `seen[]` , where each element of `seen[]` is itself a list with varying sizes.

Now, before I was using `chosen = numpy.random.choice(seen)` with which the loop processing started with ~`5000` it/sec and smoothly decreased to ~`150`it/sec . Replacing that by `chosen = seen[random.randint(0,len(seen)-1)]` gives me a consistent ~`16500`it/sec as found out by the `tqdm()` package.

While this is such a simple tweak, I am bewildered by this annoying glitch and wasted a lot of time profiling my code trying to find the bottleneck. I wished to check with the devs why is this happening and if this can be corrected in the future versions.

**Comment by karttikeya** [comment]
I see. Thanks a lot for the insightful answer. I guess it would be helpful if numpy throws a warning or something similar in such cases. But I now clearly understand the reason.

**Comment by anthonyshibitov** [comment]
@karttikeya when would this give a warning? i.e. what size array?

**Comment by eric-wieser** [comment]
There's talk of warning whenever numpy tries to convert a jagged array like that, and ends up chosing `dtype=object`

**Comment by anthonyshibitov** [comment]
@eric-wieser what do you mean by 'jagged'?

**Comment by mattip** [comment]
`seen` is a list of lists, each internal list can have a different length, so if you would draw them you could get this which looks "jagged"
```
[ [1, 2, 3],
  [1, 2, 3, 1, 2, 3],
  [1, 2, 3],
  [1, 2, 3, 1, 2, 3],
  [1, 2, 3],
  [1, 2, 3],
]
```

**Comment by tylerjereddy** [comment]
Incidentally, those "jagged" arrays are extremely common in computational geometry since collections of polygons invariably tend to have different sizes (edge counts, etc.).

**Comment by jonashaag** [comment]
Just hit this too. I think NumPy should be either failing to work on non-arrays, or have acceptable performance. I volunteer to come up with a PR if you agree.

**Comment by eric-wieser** [comment]
@jonashaag, I'm pretty sure in newer versions of numpy my example above would emit a deprecationwarning.

**Comment by jonashaag** [comment]
Sorry, I'm talking about flat lists:

```pycon
>>> import time
>>> import numpy as np
>>> import random
>>> stuff = range(100_000)
>>> s = time.time(); np.random.choice(stuff); time.time() - s
0.06497526168823242
>>> s = time.time(); random.choice(stuff); time.time() - s
0.0004982948303222656
```

I think it's reasonable to try to use NumPy for selecting samples from Python lists, for example if you are using a NumPy RNG everywhere in the code and want to be able to work with non-arrays using the same RNG. And I'd expect NumPy to not perform unnecessarily bad.
