### ISSUE TITLE
searchsorted weird behaviour when called with non sorted array (should it raise error?)

### ISSUE THREAD

**Issue by pietropeter** [numpy/numpy#11477]
Debugging a scikit-learn LabelEncoder recipe found online [(stackoverflow)](https://stackoverflow.com/questions/21057621/sklearn-labelencoder-with-never-seen-before-values) I ran into a weird behaviour of `numpy.searchsorted(a, v)` when called with a non sorted array (which is not a correct use case of the function):

```
Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.14.2'
>>> np.searchsorted([1, 2, 3, 4, -1], [4])
array([5], dtype=int64)
>>> np.searchsorted([1, 2, 3, 4, -1], [3, 4])
array([2, 3], dtype=int64)
```

In particular I would expect that the algorithm would respond with the same value for input 4 in array `a` independent of the other values (while from the above we see the answer is first 5, then 3).
I guess this is due to the fact that this is due to `v` being non sorted, but I am wondering: **should numpy.searchsorted raise an error when `v` is not sorted?**

**Comment by pv** [comment]
It is not possible to check if an array is sorted in O(log n) time.

**Comment by pietropeter** [comment]
ok, it makes sense. Thanks for the answer.

**Comment by eric-wieser** [comment]
Note that `np.digitize` does check for this condition, but as a result is slower.
