### ISSUE TITLE
Calculation Error

### ISSUE THREAD

**Issue by MrQazi** [numpy/numpy#11499]
Suspected bug in NumPy for Python3.7

There is some problem in calculation (I don't know exactly where)

I used array,transpose,dot and multiply in my program.

My code works 100% fine with Python3.6-numpy

![screenshot from 2018-07-04 17-59-14](https://user-images.githubusercontent.com/39848443/42281121-0f016dfc-7fbc-11e8-9aca-37699366726f.png)

**Comment by charris** [comment]
Where did you get NumPy, what is `test.py`, what platform?

**Comment by eric-wieser** [comment]
Closing this, since it doesn't contain nearly enough information for us to fix anything.
