### ISSUE TITLE
Use gufuncs for partition, sort, etc., so they can be overridden with `__array_ufunc__`

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#11492]
Now that gufuncs gained `axis` and `keepdims` arguments, they could in principle be used to implement `sort`, `partition`, and their `arg*` equivalents, so that those functions could be overriden. This would go some towards also overriding functions like `median`.

**Comment by rgommers** [comment]
Would you also expect a performance improvement?

Functions are overridable now via `__array_function__`.

**Comment by mhvk** [comment]
Indeed, one can now override, so compared to 2 years ago, this is less relevant. I think it might mostly allow focusing on the implementation, as having it as a gufunc would remove the need to set up the iterator, etc. (this has been quite nice for @eric-wieser's work in `linalg`). Perhaps more importantly, with the new dtypes, it might provide a cleaner way to define sorting functions (which seem very odd on the `dtype`).

**Comment by mhvk** [comment]
Closing this since at the very least the title is misleading. There might well be an advantage to making `sort` a gufunc, but that should then be its own issue.
