### ISSUE TITLE
DOC ENH: concatenate arrays with numbers

### ISSUE THREAD

**Issue by homocomputeris** [numpy/numpy#11509]
Example: say, we have an array `g`. Some its recombination in Matlab is a one-liner:
```matlab
g = [something]
[g(1); g(2:n)+g(2*n:-1:n+2); g(n+1)]
```
I suggest adding this possibility to `np.concatenate()`:
```python
g = np.array(something)
np.concatenate((g[0], g[1:n] + g[2 * n:n:-1], g[n + 1]))
```
It's not really clear why NumPy cannot convert a number to, e.g., a list, if it can detect its type and shape, because adding even more brackets works, but doesn't make a lot of sense:
`np.concatenate(([g[0]], g[1:n] + g[2 * n:n:-1], [g[n + 1]])) `

**Comment by eric-wieser** [comment]
`np.block` already does this

**Comment by homocomputeris** [comment]
OK, my bad, I didn't think about `block`. Maybe because I had an idea of it to make _block_ matrices, not gluing something to an array.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html - here there is nothing with Ctrl+F -> "block".

BTW, `insert` and `append` could be the solution, if insert for some reason didn't `flatten` the whole array (why?!)

**Comment by eric-wieser** [comment]
An aside: those docs are pretty ugly:

![image](https://user-images.githubusercontent.com/425260/42352847-dabcabae-8071-11e8-8b3a-8f7fe84d4458.png)

**Comment by eric-wieser** [comment]
> Maybe because I had an idea of it as of a constructor of block matrices, not gluing something to an array.

`block` is the N-dimensional generalization of block matrices. In 1d, that's gluing something to the front and back of an array.

**Comment by homocomputeris** [comment]
> block is the N-dimensional generalization of building block matrices. In 1d, that's gluing something to the front and back of an array.

Yeah, I know it. But, actually, it's not clear why `concatenate` cannot accept 0d arrays, but `block` can.
Or, in other words, if `block` can accept whatever, why is it called only `block`, not `unify_everything`? I'm obviously exaggerating, but if we remember 

> There should be one-- and preferably only one --obvious way to do it.

then I'd say that `concatenate` should be able append numbers to a 1d list, and `block` should return `block` matrices.

**Comment by homocomputeris** [comment]
In given circumstances, I think the best solution is to improve the docs on the joining of arrays.

**Comment by eric-wieser** [comment]
As of #11534, block is referenced in the concatenate docstring

**Comment by mattip** [comment]
Closing, documentation was added
