### ISSUE TITLE
__lt__ and arange for complex numbers

### ISSUE THREAD

**Issue by crusaderky** [numpy/numpy#11505]
I tried to find any kind of documentation on how numpy implements inequality comparison between complex numbers, but I found none.

It seems like ``__lt__`` is implemented as ``(lhs.real, lhs.imag) < (rhs.real, rhs.imag)``, or in other words
```
if lhs.real < rhs.real:
    return True
if lhs.real > rhs.real:
    return False
return lhs.imag < rhs.imag
```
Tests that brought me to this conclusion:
```
>>> numpy.array(9+999j) < numpy.array(10+10j)
True
>>> numpy.array(11+1j) < numpy.array(10+10j)
False
>>> numpy.array(10+1j) < numpy.array(10+10j)
True
>>> numpy.array(10+11j) < numpy.array(10+10j)
False
```
Is this correct? If so it would at the bare minimum require some formal documentation, as another perfectly valid implementation could have been ``abs(lhs) < abs(rhs)``.

Also, ``arange`` behaves weirdly and I can't put any sense in it. I would have expected it to be coherent with ``__lt__``, that is
```
i = start
while (i < stop if step > 0 else i > stop):
    yield i
    i += step
```
but it isn't:
```
>>> numpy.arange(0+1j, 4+1j, 1)
array([], dtype=complex128)
>>> numpy.arange(0+1j, 4+4j, 1)
array([0.+1.j, 1.+1.j, 2.+1.j])
>>> numpy.arange(0, 4j, 1j)
array([], dtype=complex128)
>>> numpy.arange(0, 8+4j, 1)
array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j])
```

**Comment by charris** [comment]
The NumPy complex ordering is documented in the notes to `sort` and is lexicographic.
```
The sort order for complex numbers is lexicographic. If both the real
and imaginary parts are non-nan then the order is determined by the
real parts except when they are equal, in which case the order is
determined by the imaginary parts.
```
`linspace` will do a linear interpolation between the end points.

**Comment by crusaderky** [comment]
@charris ok, but what about arange?

**Comment by seberg** [comment]
There is already a bug open (and i think a bit of discussion) in issue gh-10332 about the arange. Probably current behaviour is so strange that it is very much plausible that you can change it relatively quickly.

**Comment by seberg** [comment]
Its not a bad point though that arange is a bad function anyway for all complex types, since they are all not exact types....

**Comment by crusaderky** [comment]
Closing as duplicate of #10332
