### ISSUE TITLE
Python crash after several iterations of np.require

### ISSUE THREAD

**Issue by ihormelnyk** [numpy/numpy#11507]
Sample script with all the conditions:

```
import numpy as np

t = np.dtype([(('Some field description', 'f1'), np.float64)])
data = np.zeros(100, t)
for i in xrange(10):
    print(i)
    np.require(data[['f1']], t)
```

Output:
```
0
1
2
3
4
5
6

Process finished with exit code -1073741819 (0xC0000005)
```

**Comment by mattip** [comment]
Cannot reproduce on ubuntu 18.04 with NumPy 1.16-dev and python3.6. Please tell us:

- python version (`python -c "import sys; print(sys.version)`)
- platform 
- numpy version (`python -c"import numpy; print(numpy.__version__)`)

**Comment by cgohlke** [comment]
I can reproduce this on Windows with numpy‑1.14.5+mkl‑cp37‑cp37m‑win_amd64 and numpy‑1.15.0rc1+mkl‑cp37‑cp37m‑win_amd64. Probably it is also reproducible on other platform. The script does not always crash. The output of the script is:

```
0
array([(0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,)], dtype=[(('Some field description', 'f1'), '<f8')])
1
array([(0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,)], dtype=[(('Some field description', 'f1'), '<f8')])
2
array([(0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,)], dtype=[((''nvalid index (1)', 'f1'), '<f8')])
3
```

Note the ` dtype=[((''nvalid index (1)', 'f1'), '<f8')])` before the crash.

The crash is at https://github.com/numpy/numpy/blob/maintenance/1.15.x/numpy/core/src/multiarray/strfuncs.c#L178

**Comment by pv** [comment]
Do numpy versions < 1.14.4 crash?

**Comment by cgohlke** [comment]
numpy-1.13.3 does not crash.

**Comment by ihormelnyk** [comment]
python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
numpy 1.14.2

**Comment by ihormelnyk** [comment]
Same crash on:
python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
numpy 1.15.0rc1

**Comment by ihormelnyk** [comment]
numpy-1.13.3 does not crash
platform Windows 10 64bit

**Comment by mattip** [comment]
The crash is in `array_str` where it calls `s = PyEval_CallObject(PyArray_StrFunction, arglist)`, which calls into a python function, which eventually crashes inside `PyObject_Size(o)` since `o` is rubbish. Still looking into what the python function is doing

**Comment by pv** [comment]
"git bisect start master v1.13.3; git bisect run ..." says e08eced7990fbdcecb2bd81d3fc736f69bad6dfd is the first bad commit.

**Comment by mattip** [comment]
I get a crash on HEAD with python 3.6 reliably when compiled with '-g -O0', here is a simpler reproducer
```
import numpy as np

for j in range(10):
    t = np.dtype([(('Some long field name', 'f1'), np.float64)])
    data = np.zeros(10, t)
    for i in range(10):
        print(j, i, data[['f1']])
```
The last output is
```
0 4 [(0.,) (0.,) (0.,) (0.,) (0.,) (0.,) (0.,) (0.,) (0.,) (0.,)]
0 5 [[valid index (1)(0.,]
```

The print function iterates over the view, and hits the `IndexError` in `voidtype_item` which is one of the few places that prints `...valid index (%d...`. When the field title shorter, I get a different crash, after a different number of iterations through the tester loop: 

```
Fatal Python error: deletion of interned string failed
KeyError: 'stderr'
```

**Comment by mattip** [comment]
it seems to be a refcnt problem, randomly `Py_INCREF` ing `view` for string field access "solves" the segfault. Now why is that needed, `view->ob_refcnt` is 1 at this point which seems correct?
```
--- a/numpy/core/src/multiarray/mapping.c
+++ b/numpy/core/src/multiarray/mapping.c
@@ -1635,6 +1635,7 @@ array_subscript(PyArrayObject *self, PyObject *op)
             if (view == NULL) {
                 return NULL;
             }
+            Py_INCREF(view);
             return (PyObject*)view;
         }
     }
```

**Comment by charris** [comment]
Let's bring in @ahaldane also.

**Comment by charris** [comment]
Crash only on Python 2 is suspicious. Has that been confirmed?

**Comment by mattip** [comment]
Moving one level down, `view` holds references to its `dtype` and its `base`. It is enough to INCREF the newly-created void dtype of `data[['f1']])` in `_get_field_view` 
```
--- a/numpy/core/src/multiarray/mapping.c
+++ b/numpy/core/src/multiarray/mapping.c
@@ -1597,6 +1597,7 @@ _get_field_view(PyArrayObject *arr, PyObject *ind, PyArrayObject **view,
         if (*view == NULL) {
             return 0;
         }
+        Py_INCREF(view_dtype);
 
         /* the code below can be replaced by "return 0" in 1.16 */
         if (force_view) {
```
The `view_dtype` has `fields` (a dict) and `names` (a tuple), I suspect the code that handles titles around line 1542, I don't think it is as well tested as the rest

**Comment by mattip** [comment]
And bingo. There is a DECREF of the `title` text key used in the `fields` dict. Setting a watchpoint on its refcnt around the rest of the code, it starts off at 5 in the first call to print, and each iteration of the loop it drops by one until at the fifth round it is deallocated.

**Comment by cgohlke** [comment]
Just did a debug build of numpy and found the same line of `Py_DECREF(title)`.

**Comment by njsmith** [comment]
I feel like you've probably heard Armin rant about this before, but I find `rr` *super* useful for debugging refcount issues. You can wait for the crash, then put a watch point on the refcount value and run the program backwards to see all the places where it was incremented/decremented.

**Comment by cgohlke** [comment]
>  how does a debug build help with this

The debug build crashed at https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/descriptor.c#L3203 and it was obvious in the debugger that the refcount of `title` was invalid.

**Comment by mattip** [comment]
I usually get a "helpful" crash, and can step up in the backtrace to some reasonable place, but in this case my cpython3.6 was just segfaulting randomly. Or were you using a debug python as well as a debug numpy?

**Comment by cgohlke** [comment]
>  Or were you using a debug python as well as a debug numpy

Yes, sorry. I used `python_d.exe` to build numpy and run the script.
