### ISSUE TITLE
Example code for polynomial.chebyshev.cheb2poly doesn't work.

### ISSUE THREAD

**Issue by aifer4** [numpy/numpy#11519]
The example code imports the polynomial package as P:
  >>> from numpy import polynomial as P

and then  calls cheb2poly like this:
  >>> P.cheb2poly(range(4))
  array([ -2.,  -8.,   4.,  12.])

The code above doesn't work though, because it actually should be this:
  >>> P.chebyshev.cheb2poly(range(4))

**Comment by mattip** [comment]
You are referring to [this line](https://github.com/numpy/numpy/blob/master/numpy/polynomial/chebyshev.py#L420)? A PR would be welcome, try to follow the git workflow [here](http://www.numpy.org/devdocs/dev/gitwash/development_workflow.html).

**Comment by mattip** [comment]
Do all the other docstring tests run?

**Comment by charris** [comment]
> converting chebyshev and legendre polynomials above order 20 to ordinary polynomials.

Not surprising, normal precision polynomials die around order 20. I'll still be interested in the example, however. I'd also be interested in the accuracy of the approximation, as opposed to the accuracy of the coefficents. If high precision is really needed, using a rational, Decimal, or some other high precision type is recommended.
