### ISSUE TITLE
No module named 'numpy' 

### ISSUE THREAD

**Issue by kaedyn** [numpy/numpy#11516]
I've tried several ways to installed numpy from conda on Linux using command:

conda install -c anaconda numpy
conda install numpy 

I've also tried pip install numpy

But none of them work for me and keep showing the error: no module named numpy

I've noticed there might be some error for numpy 1.14.3 so I removed it and install 1.14.5. But it still doesn't work... (I am using python 3.6)

Any suggestions?

**Comment by eric-wieser** [comment]
The python you're running is not the same as the one you're installing into. If you're unsure, `python -m pip install numpy` will install it into the same python that `python` starts.

**Comment by tylerjereddy** [comment]
Standard install trouble-shooting / question issue with a clear response & without activity for more than a month, so closing.
