### ISSUE TITLE
Large error in converted polynomials

### ISSUE THREAD

**Issue by aifer4** [numpy/numpy#11520]
When polynomial.Chebyshev and polynomial.Legendre objects are converted to polynomial.Polynomial objects and evaluated, large errors can be introduced. For asymmetrical domains about zero (e.g. [0,1]), the error becomes catastrophic for polynomials of order greater than 20. For symmetrical domains about zero (e.g. [-1, 1]), the error becomes catastrophic for polynomials of order above 40.

The following code gives an example of the first case (asymmetric domain, order 23):

>>> import numpy as np
>>> import numpy.polynomial as P
>>> import matplotlib.pyplot as plt
>>> dom = [0, 1]
>>> x = np.linspace(dom[0], dom[1], 1000)
>>> I = np.eye(100)
>>> c23 = P.Chebyshev(I[23],domain=dom)
>>> c23_poly = c23.convert(kind=P.Polynomial)
>>> plt.plot(x, c23_poly(x))
>>> plt.plot(x, c23(x))
>>> plt.show()

The code above produces the attached plot
![poly_conversion_error](https://user-images.githubusercontent.com/11010066/42399655-be4400aa-813c-11e8-94d2-c5ff7002e24c.PNG)

**Comment by charris** [comment]
Yep, that is the problem with ordinary polynomials, the difference in order for the two domains is a giveaway, as the ordinary polynomials become even worse conditioned outside of the domain [-1, 1]. That is why we have Chebyshev series :) You can get slightly better results by keeping the domain
```
c23_poly = c23.convert(kind=P.Polynomial, domain=[0, 1])
```
or by using Decimal with high precision, but everything needs to be done in high precision until after the evaluation. Polynomials are notorious for being ill conditioned. The order at which they go bad depends a lot on the domain of the data and the shape of the function being approximated.

**Comment by charris** [comment]
If you look at the coefficients of the polynomial, you will see that evaluation depends on the cancellation of very large terms, on the  order of 1e16. Given that double precision has about 16 digits of accuracy, you can see why things go bad.

**Comment by charris** [comment]
The conversion function has the note
```
Notes
-----
Conversion between domains and class types can result in
numerically ill defined series.
```

**Comment by aifer4** [comment]
Oh, got it. Perhaps convert() should give a warning in these cases? Using decimal does help, and makes the polynomial appear accurate to around order of 70, but also slows things down quite a bit.

**Comment by charris** [comment]
I suppose we could make the note more alarming ;) However, sometimes things work surprisingly well, so it is hard to determine beforehand when the polynomial is ill conditioned. Hmm, given the cancellation of high order terms, perhaps something can be done, there might also be work in the literature on the condition number of the conversion. I expect there is a fair amount of literature that could be found with a thorough search or asking an expert (which I am not), and there might even be a way to determine the numerical suitability of a given polynomial over a given interval. I can think of several inefficient possibilities.

My rough rule of thumb is, degree 5 or less, no problem, degree 5-12, feel nervous and check results, degree > 12, playing with fire. Oddly enough, fitting 50 equally spaced zeros on [-1, 1] doesn't look all that bad ...

BTW, you can tell that the problem with the example you illustrated is numerical, there are too many wiggles for a polynomial of degree 23.

**Comment by charris** [comment]
Closing. Thanks for the report, I expect others will notice the same problem in the future.
