### ISSUE TITLE
Mailing list does not accept subscription

### ISSUE THREAD

**Issue by manuels** [numpy/numpy#11523]
I tried to subscribe to the [mailing list](https://mail.python.org/mailman/listinfo/numpy-discussion) for a [suggested enhancement of numpy](https://github.com/numpy/numpy/pull/11504) several times now (today and yesterday) and I never got a subscription notification email or any other email from the mailing list (I did check my spam folder).

Sending an email to numpy-discussion@python.org anyway is blocked:

> This is a members-only list.  Your message has been automatically
rejected, since it came from a non-member's email address.  Please
make sure to use the email account that you used to join this list.

Is there a problem with the mailing list currently?

**Comment by njsmith** [comment]
Huh, that sounds frustrating! I haven't heard anyone else reporting anything like this recently. We don't maintain the list itself – the python.org folks do that – so I think you'll want to email `mailman@python.org` and they can hopefully help you out.

**Comment by manuels** [comment]
Ok, I'll let you know as soon as I have heard back from them.

**Comment by manuels** [comment]
Now that's embarassing: My browser had a typo in the autocomplete of my email address.
