### ISSUE TITLE
numpy.polyfit would benefit from an option to use only monotonic functions

### ISSUE THREAD

**Issue by Tarskin** [numpy/numpy#11539]
I would like to know if it is possible to get an option added to polyfit that forces it to stick to monotonic functions (i.e. I am trying to get the best fitting monotonic polynomial for a given set of data).

**Comment by seberg** [comment]
Unfortunately I do not think that is a plausible addition. Such a constraint would result in it not being a linear fitting problem anymore, so the tools to solve it are much more general/different strategies the likes of which you will find in `scipy.optimize` or further.
I might suggest to use the polyfit results to initialize a `scipy.optimize` least squares optimizer which supports constraints that ensure monotonic behaviour.

I believe there are also some curvefitting tools outside of scipy which might make your task simpler (scipy users mailing list might be an option if you have deeper questions).
