### ISSUE TITLE
Update the documentation on installation, pip install and wheel included openblas

### ISSUE THREAD

**Issue by paugier** [numpy/numpy#11537]
Hi,
I finally figured out that numpy wheels included the openblas library (https://github.com/numpy/numpy/issues/10920)! It is not mentioned in the documentation.

It would be good to add short remarks on that in the install pages of the documentation (https://scipy.org/install.html#installing-via-pip, https://docs.scipy.org/doc/numpy-1.10.1/user/install.html).

Actually there is nearly no mention of the wheels in the installation pages.

By the way, now that we have the wheels, the installation with pip is actually better than using apt-get, especially better than installing the package python-numpy (as written in the doc) which uses python 2.7!

- The remark on `--user` is valid only if one uses the Python of the system. With pyenv or in a virtualenv, `pip install numpy` is fine.
- "Note that you need to have Python and pip already installed on your system." Could it be a good idea to point to https://github.com/pyenv/pyenv ? It is now a very nice and simple (even for beginners) way to get an up-to-date scientific environment.

**Comment by denis-bz** [comment]
There's a further problem with wheels:
after `pip install numpy==1.15.0`, `import seaborn -> from scipy import stats` gives

    /Library/Python/2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
    ... ~ 20 similar.

https://stackoverflow.com/questions/40845304/   
runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility
explains the problem, and suggests compiling from source:
`pip install --no-binary numpy`. Hmmm.

While this is not really a numpy problem, a mention in the 1.15 release notes would be helpful.

My versions: python 2.7.15, pip 18.0, scipy 1.1.0, macosx 10.10.5  
numpy-1.15.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

**Comment by rgommers** [comment]
Grr. @denis-bz could you please open a separate issue for this? It needs a filter, and an explanation for why the size decreased (normally should only increase).

**Comment by charris** [comment]
The dtype hasn't changed since 2014, so I am not sure where this comes from, might be differences due to Python 2.7, or perhaps a cython problem.

**Comment by rgommers** [comment]
If someone could do some systematic testing (checking for which Python/Cython versions this happens), that would already be helpful.

I have the feeling this is going to be annoying again. We may want to take some more rigorous step here, like filtering out all these warnings permanently in `numpy/__init__.py`.

**Comment by charris** [comment]
I'm going to guess that the size present in the wheel has been statically determined by the compiler, so may depend on the compiler and the environment when the wheel is made, although it is hard to see what might have changed there that would make a difference.

**Comment by charris** [comment]
On my machine, NumPy 1.15.0, Python 3.6
```
In [2]: dtype.__basicsize__
Out[2]: 96
```
Same for Python 2.7. Both locally compiled. Because the error is new, it would be interesting to see what that was for whatever SciPy was compiled against. Would also be interesting for some of the earlier NumPy wheels.

**Comment by charris** [comment]
So NumPy and SciPy were compiled differently. Where did you get SciPy?

**Comment by earwig** [comment]
As far as I can tell, the warnings are new because we removed the code that suppressed them in 1.15.0. I don't believe anything to do with dtype has actually changed, but I may be incorrect. (See #11628.)

**Comment by charris** [comment]
The warning may be new,  but I'm not convinced they are harmless, the sizes should be the same and I want to know why not.

**Comment by charris** [comment]
The install instructions have changed in 1.15 and now link to https://scipy.org/install.html, where pip install is more current. Is a link sufficient? Is there anyway we can make documentation searches default to something more recent than 1.10?

I think we can close this unless we want for make the install instructions more local.

**Comment by charris** [comment]
Although  https://scipy.org/install.html should be updated to mention the presence of binary wheels, and maybe pip compatibility problems with some of the scientific distributions. Those things seem to change, so it is difficult to keep them current.

**Comment by mattip** [comment]
I think a link is sufficient and we can close this. 

There was talk about changing the style of the on-line documentation to add a version selector like [scikit image](http://scikit-image.org/docs/stable/api/skimage.external.tifffile.html) and maybe even add a "not latest version" warning

**Comment by rgommers** [comment]
Agree with just linked to https://scipy.org/install

**Comment by charris** [comment]
OK, closing this.
