### ISSUE TITLE
Boolean & operator not working as expected

### ISSUE THREAD

**Issue by karn1986** [numpy/numpy#11546]
I have this simple piece of code where I  try to compare the numpy function **logical_and** vs the "&" operator. 

I encounter a very strange behavior in which the order in the which the statements are executed seem to have an effect on the final result when in fact they shouldn't. 
In the below code , if I interchange the order of the bold statements, it leads to a different value of the variable "test" as well as a different image at the end.

import numpy as np
from scipy import misc
import matplotlib.pyplot as plt
photo_data = misc.imread('./sd-3layers.jpg')
red_mask   = photo_data[:, : ,0] < 150
green_mask = photo_data[:, : ,1] > 100
blue_mask  = photo_data[:, : ,2] < 100

_**final_mask1 = np.logical_and(red_mask, green_mask, blue_mask)
final_mask = red_mask & green_mask & blue_mask**_

test = (final_mask1 == final_mask)
print(np.all(test))
photo_data[final_mask] = 0
plt.figure(figsize=(15,15))
plt.imshow(photo_data)

![sd-3layers](https://user-images.githubusercontent.com/41074929/42523314-a4575e4e-842a-11e8-9236-be28d51c58f0.jpg)

**Comment by rkern** [comment]
`logical_and()` does not take 3 input arguments. Like all ufuncs, it can take an `out=` argument which is not an input, but an existing array which the output will be written into. That's what is happening here. The result of `np.logical_and(red_mask, green_mask)` is being written into `blue_mask`.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_and.html

**Comment by karn1986** [comment]
Thanks!!!!
