### ISSUE TITLE
Bug in einsum's docstring: 'optimize'

### ISSUE THREAD

**Issue by alvarorga** [numpy/numpy#11543]
In the description of the `optimize` parameter in the `einsum` function it says that default is `True`, while the default argument is actually `False`.

**Comment by attack68** [comment]
The default was changed in a previous release, but caused problems so was reverted back to False. The docs have been updated in this PR #11234

**Comment by tylerjereddy** [comment]
Confirmed [fixed in devdocs](https://www.numpy.org/devdocs/reference/generated/numpy.einsum.html?highlight=einsum#numpy.einsum), closing.
