### ISSUE TITLE
Strange behaviour of numpy.concatenate

### ISSUE THREAD

**Issue by AljoSt** [numpy/numpy#11542]
Hi,
I came across this behaviour which caused quite some confusion and which seems strange to me:
If you use numpy.concatenate on lists of lists, it works if either all of the sub-lists have the same length or if all of them have different lengths ( see this discussion: https://stackoverflow.com/questions/51246704/how-does-numpy-concatenate-work-on-lists/51247760#51247760 ).
Apparently, that is because if none of the sub-lists have the same dimension, they are treated as lists, but if at least one has, they are converted to numpy arrays (?). So in the example on SO, the `failList` has two sub-lists which have the same dimensions (no.0 and no.2 have both lists of size 1), but 3 sub-lists of different dimensions.
In my opinion, numpy should treat the lists as lists if at least one element does not have the correct dimensions, or it should provide a better error message. Currently, it states that "all elements must have the same dimension", which is not true. Either all of them must be the same or, in case they are lists, all of them must be different.

**Comment by eric-wieser** [comment]
This is unrelated to `concatenate` - what you're seeing is the behavior of automatic conversion from a list to an array.

**Comment by AljoSt** [comment]
Hm okay, but still I think that this seems to be an odd behaviour. Either it should change or the error message should be more informative (?). 

Btw: In this case it is not the same (?)
```
import numpy as np

failList = [[[1], [2]],
           [[3, 4, 5, 6], [7]],
           [[8], [9]]]
try:
    np.concatenate(np.array(failList))
    print("worked")
except:
    print("failed")

try:
    np.concatenate(failList)
    print("worked")
except:
    print("failed")
```


The first one works, the second one throws an exception (```ValueError: all the input arrays must have same number of dimensions```)

**Comment by eric-wieser** [comment]
So in the case of `concatenate`, the signature is really `concatenate(Sequence[ndarray])`. So when you call it as `concatenate(List[List[Any]])`, the `List[Any]` is coerced to `ndarray`.

So `np.concatenate((a, b, c))` is always the same as `np.concatenate((np.asarray(a), np.asarray(b), np.asarray(c)))`

**Comment by AljoSt** [comment]
Fair enough, but nonetheless I find this behaviour strange. If you look at this example:

```
failList = [[[1], [2]],
               [[4, 5, 6], [7]]]

goodList = [[[1], [2, 3]],
                  [[4, 5, 6], [7]]]

```
For me it is not intuitive that ```np.concatenate(faillList)``` would fail and ```np.concatenate(goodList)``` would work. Especially since the error states that the error says ```ValueError: all the input arrays must have same number of dimensions```. The "input arrays" of the second list do not have the same dimensions either and it does work.

**Comment by eric-wieser** [comment]
> do not have the same dimensions

Sure they do:
```python
>>> [np.ndim(a) for a in goodList]
[1, 1]
>>> [np.ndim(a) for a in failList]
[2, 1]
```

**Comment by ahaldane** [comment]
I'm going to close - I think it is the documented behavior.
