### ISSUE TITLE
I am getting a TypeError on running an example from the docs.

### ISSUE THREAD

**Issue by abhi-jha** [numpy/numpy#11555]
DOCS : https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.byteswap.html#numpy.ndarray.byteswap

```
A = np.array([1, 256, 8755], dtype=np.int16)
map(hex, A)

TypeError                                 Traceback (most recent call last)
<ipython-input-114-c1e70c32fbaf> in <module>()
----> 1 max(hex, A)

TypeError: '>' not supported between instances of 'int' and 'builtin_function_or_method'
```

What is the fix for this?

**Comment by eric-wieser** [comment]
You typed `max(hex, A)`, not `map(hex, A)`

**Comment by abhi-jha** [comment]
Silly me. Thanks.

**Comment by abhi-jha** [comment]
There's another issue.

Link : https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.byteswap.html

```
map(hex, A)
['0x1', '0x100', '0x2233']
```

Just doing map won't print out the results on the console. It needs to be passed to a list for the output to be seen.
