### ISSUE TITLE
Numpy Ndarray has no convenience method to set encoding (expect some thing like this np.astype(str, encoding))

### ISSUE THREAD

**Issue by venkatsgit** [numpy/numpy#11554]
we need to set the encoding during type conversion 
np dtype ```object```  to np dtype ```string``` with a encoding "utf-8" ,
but what i see is only ascii or unicode np.astype(np.unicode_)

```
unicode_np_array = np.ndarray(shape=(1,1,1), dtype=object)
for index, x in np.ndenumerate(unicode_np_array):
   unicode_np_array.itemset(index,b'search_key_\xc3\x84')
np.astype(np.unicode_)
yields this error 
UnicodeDecodeError: 'ascii' codec can't decode
byte 0xc3 in position 12: ordinal not in range(128)
```

because of that we do ndenumerate and apply decoding for each element which has a performance impact . It would be nice if there is any convenience method to do this which internally parallelize the encoding.

```
import numpy as np
import time

unicode_np_array = np.ndarray(shape=(1,1,1), dtype=object)
for index, x in np.ndenumerate(unicode_np_array):
   unicode_np_array.itemset(index,b'search_key_\xc3\x84')

print ("The unicode numpy array :"+ str(unicode_np_array))

ascii_np_array = np.ndarray(shape=(1,1,1), dtype=object)
for index, x in np.ndenumerate(ascii_np_array):
   ascii_np_array.itemset(index,b'search_key')
print ("The ascii numpy array :"+ str(ascii_np_array))

unicode_conversion_start_time = time.time()
for index, x in np.ndenumerate(unicode_np_array):
   unicode_np_array.itemset(index,x.decode('utf-8'))
unicode_conversion_end_time = time.time()

unicode_conversion_time = (unicode_conversion_end_time - unicode_conversion_start_time)*1000
print ("The unicode numpy array after conversion :"+ str(unicode_np_array))
print ("The unicode numpy conversion time :"+ str(unicode_conversion_time))

ascii_conversion_start_time = time.time()
ascii_np_array = ascii_np_array.astype(str)
ascii_conversion_end_time = time.time()

ascii_conversion_time = (ascii_conversion_end_time - ascii_conversion_start_time)*1000
print ("The ascii numpy array after conversion :"+ str(ascii_np_array))
print ("The ascii numpy conversion time :"+ str(ascii_conversion_time))
```

**Comment by MartinNowak** [comment]
`np.char.decode(unicode_np_array.astype(np.bytes_), 'UTF-8')`

**Comment by mattip** [comment]
np.chararray.decode is documented and the top result when [searching our docs](http://www.numpy.org/devdocs/search.html?q=decode&check_keywords=yes&area=default). Closing, please reopen if you think we should somehow make this more discoverably.

**Comment by ScriptPup** [comment]
Sorry to resurrect this, I can open a new issue if necessary.
However, using the syntax documented, I'm receiving the error
```
'ascii' codec can't encode characters in position 6-25: ordinal not in range(128)
```

My exact code, trying to use decode on pandas df.
```
np.char.decode(df.where(pd.notnull(df), '').values.astype(np.bytes_), 'UTF-8')
```

I tried searching your docs, but didn't find anything that helps with this. Maybe my search terminology wasn't tight enough for the engine.

**Comment by eric-wieser** [comment]
The error is coming from `.astype(bytes)` I think.

**Comment by ScriptPup** [comment]
Yes, that's where I'm seeing the error as well. Shouldn't bytes be encoding agnostic though? Perhaps that's a pandas issue, but I thought they just used numpy under the hood for these kinds of data manipulations?

**Comment by mattip** [comment]
No, encode by default can sometimes use the `locale`. If your `locale` is not set, it uses `ascii` (depending on python version and platform too, and windows is really weird).
If you want bytes, can you do `np.char.encode(df.where(pd.notnull(df), '').values, 'utf-8')` ?
If you want unicode dtype, why do you need to encode/decode at all?

**Comment by ScriptPup** [comment]
After hours of banging by head against this, turns out to be incredibly simple. Thanks @mattip, that does it.
