### ISSUE TITLE
shape too large to be a matrix.

### ISSUE THREAD

**Issue by Vedavivek** [numpy/numpy#11563]
I started working on Numpy and new to python. So, I've got this error while running this code and can anyone specify what's going under the hood and how to properly code to overcome this error.

    import numpy as np 
    a = np.matrix(np.arange(0,12)).reshape(2,2,3)

When I tried to run this, I got the following error. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/numpy/matrixlib/defmatrix.py", line 271, in __array_finalize__
    raise ValueError("shape too large to be a matrix.")
ValueError: shape too large to be a matrix.

**Comment by mattip** [comment]
The `matrix` class is not recommended for new use. It can only be two-dimensionsal, so you cannot reshape it to three dimensions. Use this instead
```
a = np.arange(0,12).reshape(2,2,3)
```

**Comment by Vedavivek** [comment]
@mattip thank you. I just framed a wrong question without knowing much about it.
