### ISSUE TITLE
Try numpy with OpenBlas

### ISSUE THREAD

**Issue by yaoye7758521** [numpy/numpy#11579]
I recentely buy a computer with AMD ZEN CPU,but I found numpy worked on this CPU very slowly.

**Comment by njsmith** [comment]
How are you installing numpy? pip, conda, ...?

**Comment by yaoye7758521** [comment]
I installed Pytorch with conda.may be numpy is build-in

**Comment by njsmith** [comment]
If you're using conda (and specifically the anaconda distribution), then by default they'll give you a version of numpy that uses MKL.

MKL is Intel's math library, which is designed to run more slowly when it detects that you're using an AMD CPU.

[According to this page](https://docs.anaconda.com/mkl-optimizations/), it looks like you can remove MKL and switch to OpenBLAS by running:

```
conda install nomkl numpy scipy scikit-learn numexpr
conda remove mkl mkl-service
```

I haven't tried this myself – I don't use anaconda, and the numpy project has no control over how anaconda chooses to build/distribute numpy. So hopefully that works, but if not, then you should contact the anaconda developers for further assistance. Good luck!

**Comment by yaoye7758521** [comment]
Thanks a lot , I will try it this night.

**Comment by yaoye7758521** [comment]
Thanks a lot , I will try this way tonight
