### ISSUE TITLE
Using Python security alerts

### ISSUE THREAD

**Issue by JakobJakobson** [numpy/numpy#11576]
Dear developers,

as I read the following news on the GitHub blog [Security vulnerability for Python](https://blog.github.com/2018-07-12-security-vulnerability-alerts-for-python/) I got curious if you want to use it for numpy?

Regards,
Jakob

**Comment by seberg** [comment]
Glancing over it, it looks more a tool for packages that have a massive and hard to grasp dependency tree such as npm? While numpy has almost no dependencies at all, and those that it does like BLAS have various implementations and live outside the ecosystem.
I am probably a bit too skeptical, but in practice what would we expect this of notifying us? Or does this help downstream/users in case someone find a serious vulnerability (e.g. triggered by bad data) in numpy?

**Comment by njsmith** [comment]
From the blog post, it sounds like they're pulling information about vulnerabilities from existing non-github databases. I'm the rare case where numpy itself contains a vulnerability, then I think that should already get picked up.

The new thing seems to be that you can include a `requirements.txt` or `Pipfile.lock` file in your repository to start getting notifications about the listed packages. Numpy doesn't have any dependencies, and if it did then they wouldn't be listed in those files anyway (those files are designed for standalone applications, not libraries), so this seems pretty irrelevant to us. The target audience here is more like, folks maintaining complicated web apps, that have lots of dependencies and which are exposed to the internet.

**Comment by seberg** [comment]
Sounds like we probably all agree and this can be closed.
