### ISSUE TITLE
Add axis option to numpy.random.shuffle

### ISSUE THREAD

**Issue by CyanoKobalamyne** [numpy/numpy#11583]
Currently, `numpy.random.shuffle` only supports shuffling along the first axis only. Many other Numpy functions support the `axis` keyword argument to specify the axis along which the respective operation should be applied, it would be great to have such an argument for this function as well.

**Comment by subhrm** [comment]
I would suggest  [`apply_along_axis`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.apply_along_axis.html) . PFB an example : 

```
import numpy as np
a = np.arange(40).reshape((5,8))                   
_ = np.apply_along_axis(np.random.shuffle,1,a) 
np.random.shuffle(a)
print(a)
```
Example output:
```
[[28 24 30 27 31 25 26 29]
 [39 36 37 33 38 35 34 32]
 [ 9 15 12  8 14 13 11 10]
 [22 17 23 19 20 16 18 21]
 [ 2  1  5  4  6  0  7  3]]
```

**Comment by WarrenWeckesser** [comment]
FYI: https://github.com/numpy/numpy/issues/5173

**Comment by wkschwartz** [comment]
Can this be closed now because of #13829?

**Comment by CyanoKobalamyne** [comment]
I believe so. Thank you!

**Comment by dasiff** [comment]
Actually the proposed code does not do what a single-dimensional shuffle should do:
a = np.arange(40).reshape((5,8))       
print(str(a))
# shuffle along axis 1     
np.apply_along_axis(np.random.shuffle,1,a)
print(str(a)) 

[[ 0  5  3  7  6  1  2  4]
 [11  9  8 15 13 12 14 10]
 [18 23 19 20 21 16 22 17]
 [28 29 24 25 26 31 27 30]
 [39 38 34 33 37 32 36 35]]

It shuffles each row separately--it should preserve the column order and shuffle columns
