### ISSUE TITLE
ENH: Implement NEP 19 Random Number Generator Policy (tracker issue)

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#11587]
Now that NEP 19 has been accepted, what is the path forward to extending the `numpy.random` module? Do we point people to [randomgen](https://github.com/bashtage/randomgen) or do we somehow incorporate it into NumPy itself?

**Comment by rkern** [comment]
We will be incorporating it into numpy.

**Comment by mattip** [comment]
Help needed?
