### ISSUE TITLE
core/function_base.py contains obsolete call for astype in def linspaces

### ISSUE THREAD

**Issue by vdoublie** [numpy/numpy#11585]
in numpy/core/function_base.py

def linspaces ...

return y.astype(dtype,copy=False) is obsolete
-> astype does not contain the "copy' parameter anymore

please remove the copy=False in both return options

**Comment by eric-wieser** [comment]
> astype does not contain the "copy' parameter anymore

[Citation needed](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html)

**Comment by vdoublie** [comment]
Yes I know, The PB is in the call from numpy/core/function_base.py
in the linspaces definition

**Comment by eric-wieser** [comment]
Can you elaborate on why you think it is obsolete?

**Comment by vdoublie** [comment]
here is the snipet from the numpy/core/function_base.py defining linspaces
that comes getting numpy 

def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None):
    """
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

[…]
    if retstep:
            return y.astype(dtype, copy=False), step
    else:
            return y.astype(dtype, copy=False)


——>
This causes problem in Python 3.6.6
evidently as astype does not contain “copy’
It is probably the last instance having this “copy” as parameter
That’s what I mean when I write obsolete.. there is an obsolete call syntax

Cheers
V.

**Comment by eric-wieser** [comment]
> This causes problem in Python 3.6.6

Can you show the exact problem you're seeing, in the form of the code you're running, and the error it produces, along with your numpy version?

**Comment by vdoublie** [comment]
def get_orbital_phase(self, t14, period, N=1000):
    f = t14/period
    self.phi = np.linspace(-f, f, N)
    return self.phi


  File "/Users/vdoublie/astro/ExoSim_Ariel/ExoSim_Py36/ExoSim_Ariel_20160516/exosim/classes/planet.py", line 112, in get_orbital_phase
    self.phi = np.linspace(-f, f, N)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/function_base.py", line 150, in linspace
    return y.astype(dtype, copy=False)
TypeError: astype() got an unexpected keyword argument 'copy’

it is a rather long code prior to this

Funnily enough in a python prompt.. seems not to matter

Python 3.6.6 (default, Jun 28 2018, 05:43:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> f = 0.0000002
>>> phi = np.linspace(-f,f,N=1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: linspace() got an unexpected keyword argument 'N'
>>> phi = np.linspace(-f,f,num=1000)
>>> N = 1000
>>> phi = np.linspace(-f,f,N)
>>> t14=10e-5
>>> period=0.002
>>> f=t14/period
>>> phi = np.linspace(-f,f,N)
>>> np
<module 'numpy' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/__init__.py'>

  py36-numpy @1.14.5_0+atlas+gcc7 

The error disappear when I correct to:
    if retstep:
        try:
            return y.astype(dtype, copy=False), step
        except:
            return y.astype(dtype), step
    else:
        try:
            return y.astype(dtype, copy=False)
        except:
            return y.astype(dtype)


Cheers
Vanessa

**Comment by eric-wieser** [comment]
Can you add a `print(repr(f), type(f), repr(N), type(N))` to `get_orbital_phase`?

**Comment by vdoublie** [comment]
> On 23 Jul 2018, at 15:47, Eric Wieser <notifications@github.com> wrote:
> 
> Can you add a print(repr(f), type(f), repr(N), type(N)) to get_orbital_phase?
> 

('array(0.02314894) * dimensionless', <class 'quantities.quantity.Quantity'>, '1000', <type 'int'>)

**Comment by eric-wieser** [comment]
Now we're getting somewhere! What you're seeing is fixed in python-quantities/python-quantities#144, I think
