### ISSUE TITLE
How to plot numpy.histogram

### ISSUE THREAD

**Issue by Starfruit007** [numpy/numpy#11603]
does anyone know how to display numpy.histogram as picture.
I know plt.hist can display hist-pictures, but it cannot use the return value from numpy.histogram.

can anyone help me with that? thanks a lot.

**Comment by eric-wieser** [comment]
This question would be better aimed at https://github.com/matplotlib/matplotlib

**Comment by Starfruit007** [comment]
thanks a lot, but ich have already tried this one, but it works not good for numpy.histogram.

**Comment by mattip** [comment]
https://stackoverflow.com/questions/5328556/histogram-matplotlib

**Comment by eric-wieser** [comment]
@Starfruit007: Tried what? I'm just telling you to ask someone working on matplotlib how to do it, and maybe ask them to add an example to their documentation.

@mattip: Good find!
