### ISSUE TITLE
BUG: clip(out=foo) assumes foo is C-contiguous

### ISSUE THREAD

**Issue by adbull** [numpy/numpy#11605]
### Issue
If `clip` is called with an `out` argument that is not C-contiguous, the data will be stored to `foo` in the wrong order. This issue appears to be specific to `clip`, and does not occur e.g. with `abs`.

### Versions
This issue was observed with Python 3.6.6 and Numpy 1.14.5 on Linux, installed using Conda.

### Sample code

Input:
```python
import numpy as np

x = np.arange(4).reshape(2, 2)
print(x)

y = np.zeros_like(x).T
np.abs(x, out=y)
print(y)

y = np.zeros_like(x).T
np.clip(x, 0, None, out=y)
print(y)
```

Output:
```python
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
```

**Comment by seberg** [comment]
Yeah, you are right, the check in https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/calculation.c#L1105 is off, can probably be simplified using something like the `TRIVIALLY_ITERABLE_PAIR` macro (not sure of the exact name).
