### ISSUE TITLE
systematic bias in linspace

### ISSUE THREAD

**Issue by aifer4** [numpy/numpy#11608]
np.linspace(a, b, N) creates N evenly spaced values in the interval [a,b] including the endpoints. I understand that it is not possible in general to create N evenly spaced values in an interval [a, b] when representing numbers in float precision. Let's say we define the random variables x[i] as the step sizes between adjacent points:
x[i] =  np.linspace(a, b, N)[i] - np.linspace(a, b, N)[i-1]
It would be nice if x[i] were i.i.d. random variables (that is, all having the same mean and variance). However, this is not the case in reality. Here is a plot of the step sizes for linspace(0, 1, 100000) and the code which generated it:
```
x = np.linspace(0, 1, 100000)
plt.plot((x - np.roll(x,1))[1:])
plt.title('linspace step sizes')
plt.xlabel('step index')
plt.ylabel('step size')
plt.show()
```

![image](https://user-images.githubusercontent.com/11010066/43104994-51f0e572-8ea1-11e8-84b0-9990ffa2f219.png)

and on a log scale in x:

![image](https://user-images.githubusercontent.com/11010066/43105156-e5b9cada-8ea1-11e8-9a74-c473ad8ef3f3.png)

The step sizes seem to be the same within bins on a log scale, but in general the deviation from the average step size increases towards the higher end of the bin. This probably has to do with algorithmic efficiency, and is definitely fine for everyday needs, but maybe there should be a (possibly slower) alternative which has i.i.d. step sizes?

**Comment by rkern** [comment]
Yes, this has everything to do with floating point representation. I don't think there is a way to do better, for the OP's definition of "better". These aren't random variables, so it doesn't make sense to talk about i.i.d. results.

The differences vary about 1 ULP, peak-to-peak, for the ULP at each breakpoint. The bias just comes from where the mean value happens to be between those peaks. For an even power-of-two value, I think it might split it down the middle, but 1/99999 is not.

I think this goes beyond being good for "everyday use". If you have calculations that care about "biases" this small, I think you need to find something other than floating point arithmetic to calculate it.

**Comment by aifer4** [comment]
Oh I understand, it seems obvious now that that would happen. Still, for certain applications the statistically random behavior is useful, at the expense of having less precision for the lower numbers. For example, in signal processing applications where sampling rate is important, sampling rates which are consistently more regular for smaller values of x will give you biased results. You can get unbiased values by reducing the accuracy of all the numbers (i.e. by adding small random numbers to all the values), which is what I'll be doing for my work now. I wonder if this kind of behavior could be useful enough to warrant an option in the function call (or a separate function)?
