### ISSUE TITLE
np.argsort() has something wrong

### ISSUE THREAD

**Issue by starbaby01** [numpy/numpy#11618]
i.e:
 a=[2,0,-1,3]
 np.argsort(a)
 output is right:
array([2, 1, 0, 3], dtype=int64)

but:
 a=[2,-1,0,3]
 np.argsort(a)
output has soemthing wrong:
 array([1, 2, 0, 3], dtype=int64)
The correct outpus should be:
 array([2, 0, 1, 3], dtype=int64)

**Comment by eric-wieser** [comment]
Duplicate of #8757
