### ISSUE TITLE
Release numpy-1.15.0 incompatible with sklearn

### ISSUE THREAD

**Issue by ededdneddyfan** [numpy/numpy#11614]
On a ubuntu 16.04 image in a Docker Container - 

root@1aae1bb24eec:/usr/bin# python3.6
Python 3.6.6 (default, Jun 28 2018, 04:42:43) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/sklearn/__init__.py", line 134, in <module>
    from .base import clone
  File "/usr/local/lib/python3.6/dist-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .validation import (as_float_array,
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/__init__.py", line 114, in <module>
    from .isolve import *
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/isolve/iterative.py", line 10, in <module>
    from . import _iterative
ImportError: libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory

Tested w/ numpy-1.14.3 and I had no issues.

**Comment by rgommers** [comment]
You'll need to tell us how exactly you installed numpy, scipy and scikit-learn here.

**Comment by ededdneddyfan** [comment]
Previous command in dockerfile which failed -

RUN     pip3.6 install awscli numpy scipy scikit-learn pandas flask gevent gunicorn boto3 joblib newrelic nltk sacred && \
        (cd /usr/local/lib/python3.6/dist-packages/scipy/.libs; rm *; ln ../../numpy/.libs/* .) && \
        rm -rf /root/.cache

Successful Run

RUN     pip3.6 install awscli numpy==1.14.3 scipy scikit-learn pandas flask gevent gunicorn boto3 joblib newrelic nltk sacred && \
        (cd /usr/local/lib/python3.6/dist-packages/scipy/.libs; rm *; ln ../../numpy/.libs/* .) && \
        rm -rf /root/.cache

**Comment by ededdneddyfan** [comment]
Was able to do the above successfully which led me to test further and try to look into why we ran into this.

Seems like this advice from [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/container/Dockerfile) may no longer be advisable - including `(cd /usr/local/lib/python3.6/dist-packages/scipy/.libs; rm *; ln ../../numpy/.libs/* .)` causes errors. I've updated the dockerfile to instead just run
`RUN     pip3.6 install awscli numpy scipy scikit-learn pandas flask gevent gunicorn boto3 joblib newrelic nltk sacred && \
        rm -rf /root/.cache` which works fine.

**Comment by charris** [comment]
> libopenblasp-r0-39a31c03.2.18.so

Just to be clear, NumPy 1.15 comes with `libopenblasp-r0-8dca6697.3.0.dev.so`, which it looks like SciPy cannot use. Why are you linking the SciPy lib to NumPy.

**Comment by ededdneddyfan** [comment]
See above comment @charris - you're absolutely right!

**Comment by rgommers** [comment]
@ededdneddyfan yes that's poor advice. Maybe open an issue on that repo?

**Comment by ededdneddyfan** [comment]
Will do, and closing this issue now. Sorry for the confusion!

**Comment by njsmith** [comment]
That rm/ln thing is kind of a gross hack, but I do see the purpose: people are sensitive to the size of their docker images, and it is common for numpy and scipy to ship the same large files, which is inefficient. In the long run there might be some more elegant solution, but for now this hack isn't unreasonable.

My suggestion would be: if you want to do the hack, go ahead, *but* update the script so it only replaces identical files with links. That should be safe, and will save space most of the time (e.g. right now scipy and numpy have different libraries here, but they'll probably sync up again when scipy makes another release).
