### ISSUE TITLE
DOC: expand_dims returns a view

### ISSUE THREAD

**Issue by dpogosov** [numpy/numpy#11632]
Hi,

if we apply expand_dims to a numpy array 'a' :
b = numpy.expand_dims(a, axis=0)
the 'b' is not a new array, it will be a link to the objects 'a'

is it correct behavior?
if so, it should be noted in the manual

thanks!

**Comment by seberg** [comment]
Certainly intended. But the documentation could indeed mention that it returns a view (both in the summery and for the return array probably). Want to create a pull request?
