### ISSUE TITLE
TST: DataSource test require to be online

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#11631]
Probably just an oddity and me being a bit annoyed/surprised by it, please go ahead and simply close again, but I was confused that when trying to test a bit on the plane I got failures because I was offline. Those come from DataSource, which possibly should just be deprecated anyway (but I have no idea who might be using it).

**Comment by charris** [comment]
Hmm. Was there an error or did the test just hang?

**Comment by eric-wieser** [comment]
Test gives an error - I too found this on the plane last week. At the very least, we should ignore failures due to network errors

**Comment by mhvk** [comment]
Over at astropy, our main source of false failures on travis is from the tests that need network access - even though we split off ones that need more flaky servers. I agree the standard test suite should, by default, not run any tests needing network access. Possibly some such tests should be done in a cron job on travis just to be sure we catch it is things start to fail. But ideally numpy is just free of any parts that require network access.

**Comment by seberg** [comment]
The test can also hang at least a while if the connection is bad.

**Comment by seberg** [comment]
Ah, due to that other issue, realized that we use DataSource for the "use string as a file" logic in `loadtxt`, `savetxt`, and `genfromtxt` (not `load).
Makes me also wonder whether such behaviour is really a good idea in numpy and should not be deprecated? It is pretty obvious that something starting with `http://`, etc. is not a file. But I guess for tutorials it might be nice also and the code looks pretty sane.

These are only 3 tests in numpy, it could be nice to really make them not show up when offline, but maybe we can also just mark them (similar to slow) and then only run them in the "full" testsuit, which I believe we run on travis. I do not remember seeing these tests before, which makes me think that for some reason we did not really run them with `nose`.

**Comment by rgommers** [comment]
Weird, I cannot remember ever seeing this before and certainly have run tests while being offline. I suspect that we weren't running these tests until the pytest switch.

Agree that this is a valid bug report and should be fixed.

**Comment by tylerjereddy** [comment]
I think that can be closed because https://github.com/numpy/numpy/pull/11715 was merged, right?

**Comment by rgommers** [comment]
yep, no failures anymore, closing
