### ISSUE TITLE
Source link in doc of `printoptions` goes to contextlib

### ISSUE THREAD

**Issue by kohr-h** [numpy/numpy#11639]
The source link in [the documentation of the new `printoptions` context manager](https://docs.scipy.org/doc/numpy/reference/generated/numpy.printoptions.html?highlight=printoption) has the wrong link target: it goes to the invalid
```
http://github.com/anaconda3/lib/python3.6/contextlib.py#L281-L311
```
Seems like an issue with the link auto-generation machinery, maybe even with other decorated functions?

**Comment by eric-wieser** [comment]
I think this might be a sphinx bug

**Comment by eric-wieser** [comment]
Nope, this is a bug in our own code - good find!

https://github.com/numpy/numpy/blob/83828f52b287fefb3d8753a21bd3441997a4d687/doc/source/conf.py#L303-L348

**Comment by eric-wieser** [comment]
This relates to https://bugs.python.org/issue1764286

**Comment by kohr-h** [comment]
Wow, that was quick! Interesting that it turned up an inconsistency in the Python standard library.

**Comment by eric-wieser** [comment]
Upstream fix at https://github.com/python/cpython/pull/8602

**Comment by eric-wieser** [comment]
Upstream fix still waiting for review - I think a review from a non core developer would move the process forwards
