### ISSUE TITLE
Can no longer take powers of matrices with dtype object

### ISSUE THREAD

**Issue by MarkCBell** [numpy/numpy#11635]
I am using numpy in python 3.6.5 where the code
```
>>> import numpy as np
>>> M = np.matrix([[2,1],[1,1]], dtype=object)
>>> M**3
```
Runs fine in numpy 1.14.x but raises a 
`TypeError: Object arrays are not currently supported`
in numpy 1.15.0. I looked in the 1.15.0 release notes but couldn't see anything about matrix multiplication / powers being depreciated for objects. Is there a way around this? Currently I need to make matrices of python integers in order to be able to support doing large powers without overflow.

**Comment by MarkCBell** [comment]
So the problem seems to stem from https://github.com/numpy/numpy/commit/a786915c4e9f6f2a4b4e8f95b9db6f3538343509 which rewrote and tidied up the matrix_power function. However in doing so it replaced calls to `dot` with calls to `matmul` which does not support object types https://github.com/numpy/numpy/blob/7cd94f262b1b12d29f7903195098903cd0e9db22/numpy/core/src/multiarray/multiarraymodule.c#L2347

I think I could write a patch that would keep the same cleaner, rewritten structure to matrix_power but goes back to using `dot` instead. However are there any advantages of `matmul` over `dot`?

**Comment by eric-wieser** [comment]
> However are there any advantages of matmul over dot?

Yes, it makes linalg work for stacks of matrices. So the logic should maybe look something like:

```
if dtype != object:
    f = np.matmul
elif arr.ndim == 2:
    f = np.dot
else:
    raise NotImplementedError("matrix_power is not implemented for stacks of object arrays")
```

**Comment by mattip** [comment]
`matmul` should turn into a ufunc for 1.16, so fixing `einsum` would not fix `matmul`.

**Comment by dgasmith** [comment]
`einsum` for objects would be pretty complex. Perhaps a Python version would be doable.
