### ISSUE TITLE
numpy API deprecated on scikit-learn installation

### ISSUE THREAD

**Issue by czhao028** [numpy/numpy#11646]
When I try to install scikit-learn from source (I've opened an issue there w/ this problem; they told me it had nothing to do with scikit), I get a mix of error messages, including this:

### Reproducing code example:
- cloned scikit-learn [https://github.com/scikit-learn/scikit-learn.git](https://github.com/scikit-learn/scikit-learn.git)
- cd scikit-learn-master 
- make clean
- python setup.py install`

error messages --

```
compile options: '-I/Users/[USER_NAME]/anaconda3/envs/installgithub/lib/python3.6/site-packages/numpy/core/include -I/Users/[USER_NAME]/anaconda3/envs/installgithub/lib/python3.6/site-packages/numpy/core/include -I/Users/[USER_NAME]/anaconda3/envs/installgithub/include/python3.6m -c'
gcc: sklearn/utils/_logistic_sigmoid.c
In file included from sklearn/utils/_logistic_sigmoid.c:589:
In file included from /Users/[USER_NAME]/anaconda3/envs/installgithub/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/[USER_NAME]/anaconda3/envs/installgithub/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /Users/[USER_NAME]/anaconda3/envs/installgithub/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1818:
/Users/[USER_NAME]/anaconda3/envs/installgithub/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
```

### Numpy/Python version information:
1.14.5 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by eric-wieser** [comment]
Can you link to the issue you opened there?

**Comment by rkern** [comment]
These aren't error messages, just warnings. scikit-learn needs to modify their code to avoid the warnings and possibly avoid the deprecated APIs. It's not necessarily the case that they are using the deprecated APIs; C does not give us the tools to issue warnings only when specific APIs are used. The method that we use displays these warnings if the numpy-using code just `#include`s the numpy headers, no matter what parts of the API they actually use. They have to take an active step to `#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION` to disable the warnings and prevent the numpy headers from exposing the deprecated API. It's churn for the downstream projects every time we deprecate more APIs, but it's the best we can do with the limited tools that C gives us.

**Comment by rkern** [comment]
The only issue I see is https://github.com/scikit-learn/scikit-learn/issues/11636, which doesn't discuss these warning messages. These warning messages are not related to the build problems that you are experiencing, @czhao028; you can safely ignore them. If your installation is still not working, it's due to other issues.

Unfortunately, Github issues aren't the best place to get or give installation help. I'm not sure what problems you are currently experiencing, but if you still have questions about how to install scikit-learn from source into your Anaconda installation, there is an Anaconda Google group for providing support: https://conda.io/docs/help-support.html

**Comment by InessaPawson** [comment]
I’m going to close this issue as it has to be addressed outside of the NumPy project. 
@czhao028, I hope you found a workaround for it.
