### ISSUE TITLE
Strange problem when creating a pandas.Series from void ndarray since 1.15.0

### ISSUE THREAD

**Issue by konlai** [numpy/numpy#11668]
I don't know whether this is Numpy bug or Pandas bug. Since upgrading to 1.15.0, I'm getting garbage in my pandas.Series when I construct it using an ndarray. This worked fine in Numpy 1.14.5.

### Reproducing code example:

```python
import numpy
import pandas

a = numpy.array(['abcd'], "V4")
#print a
s = pandas.Series(a).apply(lambda x: str(x))
print s
```

### Error message:

With Numpy 1.14.5, it prints:
```
0    abcd
dtype: object
```

With Numpy 1.15.0, it prints:
```
0    �7�5
dtype: object
```

However, if you uncomment the ```print a```, then it will print:
```
[b'\x61\x62\x63\x64']
0    abcd
dtype: object
```

Note that the original "V4" ndarray is produced by another library. Ideally, they should probably be producing an "a4" ndarray. But that's another matter.

### Numpy/Python version information:

Python 2.7.5
Numpy 1.15.0
Pandas 0.23.3

**Comment by charris** [comment]
Out of curiosity, can you try with Python 3 or a recent version of 2.7?  Python 2.7.5 is known to have some issues, see #10524.  @jreback Any idea, that does seem strange.

**Comment by charris** [comment]
I think that there is something uninitialized in the printing function for that dtype.

Python 3.3.6, Pandas 0.22.0
```
In [1]: import pandas

In [2]: a = numpy.array([b'abcd'], "V4")

In [3]: s = pandas.Series(a).apply(lambda x: str(x)); s
Out[3]: 
0    b'`\xc9M/'
dtype: object

In [4]: s = str(a)

In [5]: s = pandas.Series(a).apply(lambda x: str(x)); s
Out[5]: 
0    b'abcd'
dtype: object

In [6]: a = numpy.array([b'abcd'], "V4")

In [7]: s = pandas.Series(a).apply(lambda x: str(x)); s
Out[7]: 
0    b'abcd'
dtype: object
```
@ahaldane Can you think of anything?

**Comment by eric-wieser** [comment]
So to be clear, the act of printing the array changes the behavior?

**Comment by konlai** [comment]
> So to be clear, the act of printing the array changes the behavior?

Yes.

> I think that there is something uninitialized in the printing function for that dtype.

I don't know how the printing function is involved in the construction of the pandas.Series, but the object inside the Series is different depending on whether you've printed the ndarray first. e.g. (with with Python 3.4.8, Pandas 0.22.0, Numpy 1.15.0):
```python
a = numpy.array([b'abcd'], "V4")
#print(a)
s = pandas.Series(a).apply(lambda x: x.decode('latin-1'))
print(s[0] == 'abcd')
```
Prints ```False```. But prints ```True``` if ```print(a)``` is uncommented.

**Comment by eric-wieser** [comment]
Is accessing the element sufficient? So replacing `print(a)` with `tmp = a[0]`?

**Comment by konlai** [comment]
> Is accessing the element sufficient? So replacing print(a) with tmp = a[0]?

No. The pandas.Series still contains garbage if I do that.

**Comment by eric-wieser** [comment]
How about `tmp = str(a[0])`?

**Comment by konlai** [comment]
> How about tmp = str(a[0])?

Yes. That fixes the problem.

**Comment by eric-wieser** [comment]
Something very strange is going on. After some poking around, I got this behavior:

```
>>> b = numpy.array([b'abce'], "V4")  # note the 3
>>> pandas.Series(b).apply(lambda x: x.decode('latin-1'))
0    abcd
dtype: object
```

Seems we're using unitialized memory from somewhere

**Comment by eric-wieser** [comment]
Well, I've found one bug
```
return PyBytes_FromStringAndSize(PyArray_DATA(ap), descr->elsize);
```

should be

```
return PyBytes_FromStringAndSize(ip, descr->elsize);
```

For length 1 arrays though, I can't see why that would matter

**Comment by charris** [comment]
The bad commit is a83af93ab4894b5838b598daacbc24da1f729484 in #8157.

**Comment by charris** [comment]
Fixing the bug found by @eric-wieser fixes the immediate problem. The `pandas.Series(a)` printing problem is also in  NumPy v1.10.0 and I suspect a Pandas bug.

**Comment by charris** [comment]
@eric-wieser Any idea how to test the fix without using pandas? I'm coming up dry.

**Comment by eric-wieser** [comment]
I gave a failing test case in my comment above
