### ISSUE TITLE
numpy > 0.14.2 broke on OpenBSD/macppc due to use of Cython > 0.27.3

### ISSUE THREAD

**Issue by didickman** [numpy/numpy#11664]
Downloading numpy 0.14.3 or greater from pypi was broken on OpenBSD/macppc.

We traced the breakage to the upgrade from Cython 0.26 used in numpy 0.14.2 to Cython 0.28 used in the numpy 0.14.3 package.

The reason was traced to use of _attribute__((optimize("Os"))) in recent versions of Cython. On OpenBSD we’ve disabled use of this gcc atttibute as the gcc folks have documented that this attribute is “not suitable in production code”.

Reporting this issue here in case numpy developers want to review.

Here’s a link to the OpenBSD patch we applied to numpy to disable this Cython feature. Our diff includes links to a few relevant Cython bug reports that may be interesting to review as well:

https://github.com/openbsd/ports/commit/4bcdc694962990039740a88abbf6ec7d18fb4027

**Comment by charris** [comment]
Thanks for the report. This sounds like a Cython problem, I'm not sure there is anything NumPy can do, as we need Cython >= 0.28 to generate code that will compile and run under Python 3.7. Do you have a suggestion in that regard?

**Comment by charris** [comment]
Note that I am talking about the source, we could certainly change the flags used to compile the wheels on PyPI.

**Comment by mattip** [comment]
cython/cython#2494 explains that the use of `__attribute__((optimize("Os")))` seems to be the cause of the `warning: dereferencing type-punned pointer will break strict-aliasing rules` warnings I have been seeing.

Looking at the linked patch and at the `mtrand.c` generated code, we could disable this by adding 
```
CFLAGS +=  -D CYTHON_SMALL_CODE=
```
to the setup.py

**Comment by charris** [comment]
@mattip Sounds like a good idea. I'm curious if the `cold` attribute mentioned has the same problem, as disabling small code might be a problem. Although NumPy's use of Cython is so limited that it probably doesn't make much difference.

**Comment by charris** [comment]
@didickman Noting the title change, is it the case that Cython 0.28.3 is OK?

**Comment by mattip** [comment]
Should we at least fix 1.15 since it uses a problematic cython?

**Comment by charris** [comment]
Let's go ahead and define the macro with a note just to make sure 1.15.1 doesn't have a problem, we can update later when we are sure the problem is fixed. Sounded like the options were a Cython 0.28.5 (soonish) or 0.29.0 (weeks).

**Comment by mattip** [comment]
Cython 0.29 has been released. We should revisit this once we update our build system to use it.

**Comment by charris** [comment]
@didickman Is this fixed for you?

**Comment by didickman** [comment]
yep. we have a workaround on openbsd where we’re on version 1.14.6 now. if i find any issues when we go to 1.15.x i’ll open a new ticket as needed. feel free to close this one...

**Comment by charris** [comment]
@didickman Thanks for the update.
