### ISSUE TITLE
Subclassing support for non-universal functions

### ISSUE THREAD

**Issue by suquark** [numpy/numpy#11671]
I have a subclass of `ndarray` that supports ufunc-based subclassing by using `__array_finalize__`. But functions like `numpy.concatenate` will not preserve the type. Is/Will there be some ways for subclassing with non-universal functions.

### Reproducing code example:

```python
import numpy as np
class NDarray(numpy.ndarray):
    def __new__(cls):
        # ...
    def __array_finalize__(self, obj: typing.Any) -> None:
        # ...

arr = NDarray([1,2,3])
arr = np.add(arr, arr)
type(arr)  # -> NDarray
arr = np.concatenate([arr, arr])
type(arr)  # -> np.ndarray
```

### Numpy/Python version information:

1.14.3 3.6.5 (default, Jul 16 2018, 23:21:05)

**Comment by shoyer** [comment]
NEP 18 has been provisionally accepted -- see https://github.com/numpy/numpy/issues/12028 for current work
