### ISSUE TITLE
Extremely different solutions to least squares depending on casting (complex64 vs 128)

### ISSUE THREAD

**Issue by abaxi** [numpy/numpy#11672]
Given matrix Y and matrix X I want to find a vector 'a' such that Y = Xa

X is a matrix with complex128 values in it
I make "the same" Y twice, once using complex64 and once using complex128 and use lstsq to solve both. The abs difference between these Ys is ~e-8.

The solutions to Y=Xa in either case are extremely different (orders of magnitude). It is not just a scaling issue. The solutions are completely different. I expected them to be the same since the difference in values in Y across both cases is minuscule. 

The resulting 'a' I get when Y is c128 is the one I expect/want. I see that np.exp() returns a np.complex128 type object, so making a Y that is also c128 may make more sense. But the error from making Y a c64 object is more than what I'd expect.

Lastly, I know that the rank of X isn't full, but I think that that is besides the issue. 

Whats going on there? Is what I'm doing just poor programming practice? Is this a bug?

I'm using python 2.7.6.

Thank you

### Reproducing code example:

```
import numpy as np
from numpy.linalg import lstsq

def get_Y(divs, ds, mode):
    Y = np.zeros(len(divs))
    if mode == 64:
        Y = Y.astype(np.complex64)
    elif mode == 128:
        Y = Y.astype(np.complex128)
    else:
        print "mode must be 64 or 128"
        exit()
    
    for d in ds:
        Y += np.exp(1j*d/divs)
    return Y

def get_X(pds, divs):
    mat = []
    for d in pds:
        s = np.exp(1j*d/divs)
        mat.append(s)
    mat = np.array(mat).transpose()
    return mat

if __name__ == '__main__':
    ds = [0.4]
    c64 = 64
    c128 = 128
    possible_ds = np.arange(0, 1, 0.1)
    divs = np.arange(1,2,0.1)
    X = get_X(possible_ds, divs)
    
    Y1 = get_Y(divs, ds, c64)
    a1, _, r1, _ = lstsq(X, Y1)
    
    Y2 = get_Y(divs, ds, c128)
    a2, _, r2, _ = lstsq(X, Y2)
    
    print "'a' when Y is complex64:\n", np.round(a1,3)
    print "'a' when Y is commplex128:\n", np.round(a2,3)
    print "Diff. in Y_c128 and Y_c64:\n", np.sum(np.abs(Y2-Y1))


```

### Numpy/Python version information:

```
'a' when Y is complex64:
[ -49581.541 +10206.582j  254035.414 -72135.028j -453206.422+165424.87j
  213771.156 -95484.351j  277139.974-152791.682j -264373.010+172255.911j
 -188403.305+140993.125j  362766.036-317918.434j -184756.245+187945.166j
   32608.943 -38496.158j]
'a' when Y is commplex128:
[-0.007-0.002j  0.056+0.013j -0.190-0.029j  0.354+0.027j  0.606-0.j
  0.256-0.019j -0.080+0.011j -0.004+0.002j  0.010-0.003j -0.002+0.001j]
Diff. in Y_c128 and Y_c64:
1.70216993313e-07

```

**Comment by charris** [comment]
> Lastly, I know that the rank of X isn't full, but I think that that is besides the issue.

I suspect that is most of the issue, as the higher precision will probably differ in the smaller singular values. Try explicitly setting the `rcond` to the same value for both. Looking at the singular values of both the low and high precision design matrices might also be informative. Generally speaking, rank deficient matrices spell trouble.

**Comment by abaxi** [comment]
Thank you. I didn't know the thing about rcond. The singular values are the same even when rcond is not set. 

Explicitly setting rcond to say 1e-8 makes both the result vectors more similar. However, lowering rcond below some threshold makes the c64 result poor again, while still "improving" the c128 result. Figures attached.

![figure_e-8](https://user-images.githubusercontent.com/26046328/43681886-8ac4a540-982f-11e8-96b4-e33cfcb90b6f.png)

![figure_e-10](https://user-images.githubusercontent.com/26046328/43681885-8aa86aa6-982f-11e8-90ea-b5298382eeb5.png)

![figure_e-80](https://user-images.githubusercontent.com/26046328/43681887-8ad8ba26-982f-11e8-89f9-899ef9bd83db.png)


Will the issue be avoided if the X matrix has linearly independent columns?

Thank you.

**Comment by charris** [comment]
> Will the issue be avoided if the X matrix has linearly independent columns?

I would expect that to be the case. What you are experiencing is typical of ill conditioned design matrices.

**Comment by abaxi** [comment]
OK. Hopefully I will be able to do that. Thank you for clearing things up. Closing this issue.
