### ISSUE TITLE
BUG : About Data type objects

### ISSUE THREAD

**Issue by xushengun** [numpy/numpy#11681]
When creat a array with set the dtype , the array just lost the columns which the dtype is numpy.string_,numpy.str,numpy.str_,numpy.str0 .
And when i change 'string_' to '<U1' ,that will work .
### Reproducing code example:

```python
import numpy as np
<< your code here >>
b = np.array([('a',1,2),(3,4,5),(6,7,8)], dtype=([('name','string_'),('age','int8'),('salary','float32')]))
a = np.array([('a',1,2),(3,4,5),(6,7,8)], dtype=([('name','<U1'),('age','int8'),('salary','float32')]))
```

### Numpy/Python version information:

1.15.0 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
Duplicate of #8969
