### ISSUE TITLE
numpy.take fails with int64 dtype on i386 architecture

### ISSUE THREAD

**Issue by rth** [numpy/numpy#11696]
numpy.take fails with int64 dtype on i386 architecture

### Reproducing code example:

```python
import numpy as np
x = np.arange(10, dtype='int64')
index = np.arange(3, dtype='int64')
x.take(index)
```
### Expected output:
```
array([0, 1, 2])
```
is obtained on 64 bit architecture

### Error message:

On 32 bit Debian Linux, I get,
```
>>> x.take(index)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```
On 32 bit windows, the same result was indirectly illustrated in https://github.com/scikit-learn/scikit-learn/pull/11295#issuecomment-411638342

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.14.5 3.6.6 (default, Jun 27 2018, 14:44:17) 
[GCC 8.1.0]
```
Generally this was run in the debian unstable [i386 Docker image](https://hub.docker.com/r/i386/debian/), with the following setup,
<details>

<summary>Dockerfile</summary>

```
FROM i386/debian:unstable

RUN apt-get update && apt-get install -y build-essential git make

RUN apt-get install -y python3 python3-scipy python3-numpy python3-setuptools python3-pkg-resources python3-pip
```

</details>

**Comment by eric-wieser** [comment]
Arguably this is by design. If you're indexing with a type bigger than `np.intp`, you're likely to overflow, and you don't want that.

**Comment by rth** [comment]
OK, makes sense. Thanks @eric-wieser !
