### ISSUE TITLE
MAINT: Numpy uses `PyUnicode_AS_DATA` which will be deprecated eventually

### ISSUE THREAD

**Issue by danieljacobs1** [numpy/numpy#11699]
I originally raised this as https://github.com/pandas-dev/pandas/issues/21758 thinking it was a `pandas` issue, but when I delved more deeply I found that it was `numpy`.

Using `np.array` changes the return value of `sys.getsizeof` on the first single character string that is passed to it.

### Reproducing code example:
Pasting this into a Python REPL:
```
import sys
sys.getsizeof('a')
sys.getsizeof('b')
import numpy as np
sys.getsizeof('a')
sys.getsizeof('b')
np.array(['b'], dtype=(np.str_, 1))
sys.getsizeof('a')
sys.getsizeof('b')
sys.getsizeof('c')
```
I get output like this:
``` $ python
$ python
Python 3.7.0 (default, Jun 28 2018, 13:15:42)
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getsizeof('a')
50
>>> sys.getsizeof('b')
50
>>> import numpy as np
>>> sys.getsizeof('a')
50
>>> sys.getsizeof('b')
50
>>> np.array(['b'], dtype=(np.str_, 1))
array(['b'], dtype='<U1')
>>> sys.getsizeof('a')
50
>>> sys.getsizeof('b')
58
>>> sys.getsizeof('c')
50
>>>
>>>
```
Notice how `sys.getsizeof('b')` has _increased_ from 50 to 58 following the call to `np.array`. This is very much unexpected behaviour.

### Numpy/Python version information:

Output from `import sys, numpy; print(numpy.__version__, sys.version)`:
```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.15.0 3.7.0 (default, Jun 28 2018, 13:15:42)
[GCC 7.2.0]
```
I've seen this with a mixture of `Python` versions and `numpy` versions. I'm using Ubuntu 18.04LTS 64-bit, but I've also seen this on Ubuntu 16.04LTS 64-bit.

**Comment by seberg** [comment]
Honestly, I doubt this has anything to do with numpy, see for example:
```
import sys
import array
sys.getsizeof('a') == 50
array.array('u', ['a'])
sys.getsizeof('a') == 58
```
My guess is, some C-level API level function in python causes this, for example `PyUnicode_AS_DATA` or so (which numpy uses in a few places).

**Comment by seberg** [comment]
So, lets see:

 1. Python (in `PyUnicode_AsUnicode` (or children of it) will allocate some `wstr` representation:
   ```
   _PyUnicode_WSTR(unicode) = (wchar_t *) PyObject_MALLOC(
                       sizeof(wchar_t) * (_PyUnicode_LENGTH(unicode) + 1 + num_surrogates));
   ```
 2. That stuff is deprecated now, but the other function mentions you need to make sure `PyUnicode_READY` was called (but I guess that is only true from the C-api not sure).

So, I guess it might be that we could switch to using `PyUnicode_4BYTE_DATA` (or the 2 byte on narrow builds?), and the increase may go away. But overall, the increase seems to  me like an intended side effect.

**Comment by seberg** [comment]
So, changing over to the other API sooner rather then later might save this extra string copy/representation maybe. I am not sure. Maybe someone who knows it better or wants to dig deeper comes along though.

I guess if you say that this is a serious memory footprint issue, it might be worth looking more closely though.

**Comment by danieljacobs1** [comment]
Thank you for digging into this further @seberg - I don't know the CPython extension API so wouldn't know where to begin.

It does seem, then, to be a CPython issue rather than `numpy`; stopping usage of deprecated API's is always good to do, of course :smile:.

It's not causing a serious memory footprint issue that we're aware of. I consider this a slightly alarming oddity.

I'll ask about the `array.array` example on the CPython issue tracker too. They should be able to confirm whether or not it's a bug or unintended side-effect.

Thanks again.

**Comment by seberg** [comment]
Random search, maybe you already saw it, but: https://bugs.python.org/issue30863 reads like using the new API (`PyUnicode_AsWideChar`) should remove the effect of caching. Am not quite sure if platforms with `wchar_t` support changes anything.

**Comment by mattip** [comment]
We no longer use `PyUnicode_AS_DATA`, but there were some other concerns in this issue. Should we close it or change the title?

**Comment by seberg** [comment]
I think in most cases, we still use API which causes the unicode object to cache the result. (E.g. as utf8 string) but I am not convinced this is a bad thing in most cases, as opposed to just surprising.
Also, I expect we have to use utf8 in most of those cases, since we probably need ascii compatibility.

So, I will close it. I am not quite sure, but it would seem more helpful to open a new issue that is more to the point, and personally, I am not sure there is an issue at all.

**Comment by eric-wieser** [comment]
The original behavior also no longer occurs:
```
In [2]: import sys
   ...: print(sys.getsizeof('a'))
   ...: print(sys.getsizeof('b'))
   ...: import numpy as np
   ...: print(sys.getsizeof('a'))
   ...: print(sys.getsizeof('b'))
   ...: np.array(['b'], dtype=(np.str_, 1))
   ...: print(sys.getsizeof('a'))
   ...: print(sys.getsizeof('b'))
   ...: print(sys.getsizeof('c'))
50
50
50
50
50
50
50
```
