### ISSUE TITLE
numpy installation in cygwin issue 

### ISSUE THREAD

**Issue by pumpkinband** [numpy/numpy#11704]
i tried

`pip install numpy==1.14.5`

 but every time this error keeps going

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-i nstall-LkomBi/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f .read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" i nstall --record /tmp/pip-record-bAHGSs/install-record.txt --single-version-exter nally-managed --compile" failed with error code 1 in /tmp/pip-install-LkomBi/num py/`

**Comment by mosrosem** [comment]
Have you tried using python3-devel module in Cygwin?

**Comment by mattip** [comment]
@mosrosem are you interested in pursuing this or can we close? What are the contents of the log file?

**Comment by mattip** [comment]
Closing, please reopen with more information if needed
