### ISSUE TITLE
TST: ARMv8 sample CI build

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#11702]
CI for more "exotic" platforms like ARM is [on our roadmap](http://www.numpy.org/neps/roadmap.html#continuous-integration). Since there's a [free ARMv8-a machine pool available from shippable](http://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture) I went ahead and drafted a feature branch in my NumPy fork that contains a [`shippable.yml`](https://github.com/tylerjereddy/numpy/blob/shippable_arm_ci/shippable.yml) with a few basic commands to build & test NumPy.

The console results are [available here](https://app.shippable.com/github/tylerjereddy/numpy/runs/5/1/console), and hopefully you can see those. In short, `python runtests.py` seems to build without problems and produce this test output:
`1 failed, 4627 passed, 406 skipped, 87 deselected, 10 xfailed in 226.59 seconds`

There are probably various discussion points, including whether we really want to do this, but a few initial observations:

- the above is with Python 2.7 because there seem to be some challenges getting pre-installed 3.6 to work by default with their ARM shared pool image
- seems like a lot of skipped tests above & we'd have to make sure that the default virtual env isolation is appropriate and there's no other NumPy system installation causing issues, etc. (I think we are very cautious about this stuff on Travis)
  - cython is (so far) the only dependency that I pip installed so would indeed have to check the environment stuff quite carefully to see what is preloaded or prevent interaction with it
- I did have to email them to get permission to access the free pool, but they were very fast / responsive (minutes usually so far)

Other Note: I didn't initiate this as a PR directly to NumPy so that I could avoid trying to register the actual NumPy organization with the service until i.e. core devs / steering committee have weighed in, etc.

**Comment by rgommers** [comment]
Nice. @jjhelmus wanted to work on this during the sprint at SciPy. He may want to review/collaborate.

**Comment by tylerjereddy** [comment]
For Python 2.7 on ARM [the current result](https://app.shippable.com/github/tylerjereddy/numpy/runs/10/1/console) is pretty close to Travis now:

ARM / shippable: "1 failed, 5004 passed, 29 skipped, 87 deselected, 10 xfailed"
Linux / Travis: "5006 passed, 28 skipped, 87 deselected, 10 xfailed"

**Comment by tylerjereddy** [comment]
I've added Python 3.7 to the ARMv8 matrix now too -- that works with a [similar result](https://app.shippable.com/github/tylerjereddy/numpy/runs/34/summary/console):
`1 failed, 5017 passed, 25 skipped, 88 deselected, 10 xfailed`

Other potentially useful things we could do if there is interest:

- add coverage reporting with codecov
- integrate with the Shippable test / coverage result reporting as well -- they have their own visualization infrastructure that can be used if you copy the data to an appropriate image path
- `pypy3-v6.0.0` is available in the aarch64 image we have access so we could test with `pypy` as well
- Python 3.6 isn't available by default with the image we currently have access to; we could probably build it into the matrix with some effort / slower job (final strategy may be to use our own custom docker container I suppose, so there's better control -- not sure if that's a lot slower though)

**Comment by charris** [comment]
Nice. I'd like to keep it simple to start with, pass all the tests. Is there a Fortran compiler available?

**Comment by jjhelmus** [comment]
@tylerjereddy This is great work, I'm excited about the possibility of regular testing of NumPy on ARMv8.  

I put together a similar setup after SciPy that might be helpful, the [shippable.yml file](https://github.com/jjhelmus/numpy/blob/arm_ci/shippable.yml) and [results](https://app.shippable.com/github/jjhelmus/numpy/runs/21/summary/console).

A few of the highlights that you might consider incorporating:

  * Building Cython takes nearly as long as building NumPy.  Using pre-build wheels drops this to a few seconds.  I'd be happy to help build these and find a place to host them.  Another speedup is skip to compiling Cython by passing `--install-option="--no-cython-compile"`.
  * The [`-junit-xml` portion](https://github.com/jjhelmus/numpy/blob/arm_ci/shippable.yml#L19) adds the test stats to the Shippable summary page.

I was not able to get older version of Python 3.x working (at the time 3.7 was not yet out).  I think the docker image is missing the necessary python-devel system packages which will make testing against these difficult.

**Comment by tylerjereddy** [comment]
> I'd be happy to help build these and find a place to host them

That sounds useful -- I've indeed noticed the time consumed by the Cython build

**Comment by tylerjereddy** [comment]
> Is there a Fortran compiler available?

Yup! The failure [is for a previously-documented problematic test](https://github.com/numpy/numpy/issues/6718). Perhaps `f2py` isn't on the install path for some reason--as many core devs in that linked issue note--this can be tricky to do automatically, but hopefully can just adjust `PATH` appropriately.

Looks like @jjhelmus doesn't have that particular issue, though we used slightly different workflows--I went through `runtests.py` directly.

**Comment by mattip** [comment]
I reached out to cython directly to get arm8 wheels on PyPI, see cython/cython#2561

**Comment by charris** [comment]
Note that the comments on the problematic test are not completely correct, f2py is usually the latest version installed, but there are -- or should be -- Python version specific entries also, f2py2, f2py2.7, etc. We should revisit this if we take another look at entry_points.

**Comment by tylerjereddy** [comment]
All tests are passing now and [the summary page](https://app.shippable.com/github/tylerjereddy/numpy/runs/38/summary/console) nicely displays the testing / timing stats for Python 2.7 & 3.7.

CI time has been cut in half thanks to suggestions from @jjhelmus -- we're down to 12 minutes now; for both Python versions:

- 90 seconds for Cython build
- 5 minutes for NumPy build
- 4.5 minutes for NumPy test suite

I'll wait for feedback before expanding / adjusting beyond that; Cython ARM binary / wheel would be helpful as noted above. Could add coverage and use `--full` for testing, but again I'll wait for a request to do that and keep it simple for now as suggested.

**Comment by tylerjereddy** [comment]
Down to [9 minutes](https://app.shippable.com/github/tylerjereddy/numpy/runs/44/summary/console) for the ARM CI now; using two cores helps for the unit tests, but is not reliably faster for the build on that infrastructure allotment.

**Comment by tylerjereddy** [comment]
The 5 slowest NumPy tests on ARMv8 CI / Python 3.7 are pasted below if we want to try to squeeze the times down even more. I wonder if almost 30 seconds for a single unit test can be reduced.

```
========================== slowest 5 test durations ===========================
25.53s call     build/testenv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py::TestAssertNoGcCycles::test_fails
5.29s call     build/testenv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py::TestAssertNoGcCycles::test_passes
5.29s call     build/testenv/lib/python3.7/site-packages/numpy/core/tests/test_mem_overlap.py::TestUFunc::test_unary_gufunc_fuzz
5.09s call     build/testenv/lib/python3.7/site-packages/numpy/lib/tests/test_utils.py::test_lookfor
5.03s call     build/testenv/lib/python3.7/site-packages/numpy/core/tests/test_mem_overlap.py::test_internal_overlap_fuzz
```

**Comment by tylerjereddy** [comment]
The [discussion](https://github.com/cython/cython/issues/2561) surrounding "official" PyPI ARMv8 Cython builds is not looking positive, in short because of ecosystem / standards issues.

As a result, I've figured out how to cache Cython wheels using shippable Amazon S3 cache uploads in a way that allows both the 2.7 and 3.7 builds to run in [9 minutes](https://app.shippable.com/github/tylerjereddy/numpy/runs/56/summary/console) -- the same as the best previous results with a wheel-specific URL.

Does this seem like a suitable approach for now? If we ever change Cython versions we pay a 1-time 13 minute build penalty for each job in the matrix, but then subsequent builds continue using the cached wheel once refreshed.

**Comment by tylerjereddy** [comment]
> Shippable will run in parallel with appveyor and travis, no?

Yes. I'm not sure how well the interface integrates into the "CI list" at the bottom of PRs and so on though (I've not even seen a screenshot / example of that yet); hopefully just another row entry there.

**Comment by rgommers** [comment]
> I would like to see some funds go into upgrading appveyor and travis accounts,

we have enough funds for that. maybe figure out what it costs and propose it on the steering council list?

**Comment by tylerjereddy** [comment]
[Here](http://docs.shippable.com/ci/pull-request-builds/) is the PR behavior explanation / screenshot for shippable / github -- basically the same as the others with another row in the CI part at the bottom of PRs.

**Comment by eric-wieser** [comment]
I'm responsible for that 25s test - I'll see if I can work out why

**Comment by QuLogic** [comment]
This has been enabled, no?
