### ISSUE TITLE
could np.save save to spare array ?

### ISSUE THREAD

**Issue by JackieQiang** [numpy/numpy#11707]
I save array(much location is zero)  to disk. it takes too much hard disk space. why numpy no method like spare array to save array?

**Comment by ksunden** [comment]
Numpy is designed with Dense/strided arrays in minde. For sparse matrices take a look at:

https://docs.scipy.org/doc/scipy/reference/sparse.html (which behaves much like `numpy.matrix`)

and:

https://sparse.pydata.org/en/latest/ (which has in interface more similar to `ndarray`)

**Comment by seberg** [comment]
Another thing would be to use `np.savez_compressed` which will zip the result, for simple stuff that might be good enough, but is not really a sparse format of course.

**Comment by JackieQiang** [comment]
very thankful!

**Comment by JackieQiang** [comment]
I just think how to save disk space.if numpy save array(more than 2 dimension) as spare array style that can save much disk space.

**Comment by eric-wieser** [comment]
IF you just want to save disk space, use `np.savez_compressed` as mentioned above
