### ISSUE TITLE
np.insert using index of -1, inserts value not at end of array

### ISSUE THREAD

**Issue by millen1m** [numpy/numpy#11705]
From the docs the `obj`: "Object that defines the index or indices before which values is inserted."
Therefore passing `obj=-1` should and the value to the end of the array but it inserts it as the second-to-last value. This occurs in version 1.15.0 and 0.14.3, not sure if this is true for all versions.

### Reproducing code example:

```python
import numpy as np
a = np.arange(4)
b = np.insert(a, obj=-1, values=9)
print(b)
assert b[-1] == 9
```

### Error message:

`assert b[-1] == 9` rasies `AssertionError`

### Numpy/Python version information:

```
1.15.0 3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by mhvk** [comment]
The behaviour seems correct: insert *before* the relevant item, which in the case of `-1` is the last one. To add an entry at the end, you'd need to use `len(array)`:
```
In [5]: a = np.arange(4)

In [6]: np.insert(a, len(a), 9)
Out[6]: array([0, 1, 2, 3, 9])
```

Since this was confusing, do you think there would be a good way to indicate in the docstring how to do this? Perhaps an example? (E.g., `np.rollaxis` does have an example like this, though not very explicit).

**Comment by millen1m** [comment]
Thanks, I completely misinterpreted the "before" to mean the index before you perform the insert. Maybe it doesn't need an example - I just need more coffee.

Or could change the word "which" to be "where", to be explicit that "before" is referring to a position, not a time.

Or could put the explicit example above using the negative index to show behaviour.

Probably coffee is the answer though :)

**Comment by mhvk** [comment]
@millen1m - no worries. Since it is clarified, I'll close this issue.

If you have the energy (after some coffee?), do put in a PR with a possible docstring improvement...
