### ISSUE TITLE
einsum in numpy 1.15 is almost 30 times slower than numpy 1.14!

### ISSUE THREAD

**Issue by sajaysurya** [numpy/numpy#11714]
einsum is significantly slower in numpy 1.15 (when compared to numpy 1.14). Could be related to [#11686](https://github.com/numpy/numpy/issues/11686). I am not sure... I am using python 3.7.0 in Arch Linux.

I realize that 1.15 does bring some improvements to einsum in general; but, for this specific code, it is very slow!

### Reproducing code example:

```python
import numpy as np
import time

print(np.version.version)

b = np.random.random((5, 2))
t = np.random.random((5, 5, 2))
p = np.random.random((2, 5))

t1 = time.time()
for _ in range(int(1e6)):
    out = np.einsum('ij,ixy,ji->xy', b, t, p)
t2 = time.time()
print(t2-t1)
```

### Output 1:
1.15.0
129.36364936828613

### Output 2:
1.14.5
4.071631908416748

**Comment by charris** [comment]
Verified. @dgasmith Thoughts?

**Comment by mhvk** [comment]
With `optimize=False`, one regains the factor 30 in speed. 

For two matrices, things are still OK, so it just seems we need to be more conservative with using `optimize` (or, better, optimize the optimization!).

**Comment by seberg** [comment]
`optimize_arg = kwargs.pop('optimize', len(operands) > 3)` reads like the optimization is reenabled in 1.15, was that actually intentional? I don't recall what the problems where with the differences. One could try to estimate the problem size and skip optimization for small ones, but at least doing it in python, I wouldn't be so sure it can manage, the factor is so large because the problem is so small of course.

**Comment by charris** [comment]
Hmm, that was #10359. The default was made `optimize=False` in #10403, but only for 1.14.x, might want to revisit that and disable it by default in master.  @mhvk any reason not to leave optimization disabled by default? Anyone currently using 1.14 has to set optimize if they want it, so nothing is lost by continuing that.

**Comment by mhvk** [comment]
#10359 was just a quick fix for the two-argument case (and thus for `matmul`) - I have no objection to leaving the default `False`, but I think we had quite a lot more discussion elsewhere. I guess the problem is that that never led to a conclusion and hence the quick fix was all that remained!

**Comment by seberg** [comment]
Well, I am not sure I am worried about the slowdown itself here, one can possibly argue or optimize it away. OTOH, I am not sure how many other inconsistencies might still be around, so not enabling `optimize` as default yet is maybe simply the safe bet.

As such, I like changing the default, just wonder if there needs to be another iteration to smooth out things/optimize these small array cases.

**Comment by dgasmith** [comment]
Another example where the execution of the pure C `einsum` function execution is on the order of a couple of Python operations and even caching the path would not help:

```
%timeit np.einsum('ij,ixy,ji->xy', b, t, p, optimize=False)
100000 loops, best of 3: 4.5 µs per loop

%timeit np.einsum('ij,ixy,ji->xy', b, t, p, optimize=['einsum_path', (0, 2), (0, 1)])
10000 loops, best of 3: 49.6 µs per loop
```

Parsing the kwargs takes on the order of 4us in Python. If we look at #11686 and this issue, they are on opposite ends of the spectrum where one looks for low latency computations while the other wants simple GEMM calls to work in `einsum`. Unless we do it all in C, figuring out enough information to run a heuristic is going to cost more than the total cost of these small calls.

At the moment we keep trying to make `einsum` "smart", but we hit this spectrum of cases where the expectations of `einsum` are quite different leading to ambiguity. Two possible way forward:
1) Announce in the description that we optimize for large expressions and small expressions should consider `optimize=False` or vice versa.
2) Push all path parsing tech and heuristic logic into the C layer.

**Comment by charris** [comment]
Yep, let's revisit this if/when more has been pushed into the C layer. I think folks who really need the optimization are capable of making that determination and explicitly setting the argument.

**Comment by dgasmith** [comment]
I am pretty happy to have this just be `optimize=False`. Much of the original discussion about this topic centered around the fact that a user should just be able to write an expression and have it execute at peak performance; however, there have been enough problems with the heuristics that the inconsistencies probably outweighs user ease of use.

**Comment by mwiebe** [comment]
It's nice to see C-Einsum is doing ok for small operations, I put some good effort into keeping its overhead low. For example, that's why the C-level API accepts strings instead of lists of integers. In my benchmarks I found that constructing a single string and interpreting it from C is much faster than constructing the equivalent lists of integers and interpreting those.

**Comment by mwiebe** [comment]
I've certainly noticed, it's great work. It's been nice seeing einsum end up in places like tensorflow and pytorch too.
