### ISSUE TITLE
MAINT: add a test_wheel.py script

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#11713]
We do not have a good way to test that wheels are usable. `runtests.py` is designed to test in-place. It would be nice to have a `test_wheel.py` script that would build a virtualenv (optionally, not needed on Travis) , install numpy from a wheel, and test that all the scripts like f2py minimally work. Then we could run that script both offline and as part of the release build.

Related to issue #11649

**Comment by rgommers** [comment]
We do test wheels on TravisCI, see `USE_SDIST` (sdist --> wheel) and `USE_WHEEL` (direct wheel creation) builds.

gh-11649 depends on OS, compilers, and other user environment things. You won't catch that for a release build; you probably won't even catch it if all devs ran your `test_wheel.py` on their own machines.

**Comment by tylerjereddy** [comment]
`USE_WHEEL` Travis job clearly does this as Ralf indicates; we also use that job for coverage now too, after installing from a newly-built wheel. So closing here.
