### ISSUE TITLE
test_core.TestMaskedArrayMethods.test_sort_flexible fails on ppc64 & s390x

### ISSUE THREAD

**Issue by QuLogic** [numpy/numpy#11716]
### Reproducing code example:
Build NumPy and run the test suite in the Fedora build root. See full logs for [ppc64](https://koji.fedoraproject.org/koji/taskinfo?taskID=29010141) and [s390x](https://koji.fedoraproject.org/koji/taskinfo?taskID=29010143).

### Error message:

The result is the same for both arches:
```
E       AssertionError: 
E       Arrays are not equal
E       
E       (mismatch 85.7142857143%)
E        x: array([([1, 1],), ([1, 2],), ([2, 1],), ([2, 2],), ([3, 3],), ([3, 1],),
E              ([1, 0],)], dtype=[('v', '>i8', (2,))])
E        y: array([([1, 0],), ([1, 1],), ([1, 2],), ([2, 1],), ([2, 2],), ([3, 1],),
E              ([1, 3],)], dtype=[('v', '>i8', (2,))])
```

### Numpy/Python version information:
NumPy 1.15.0, Python 2.7

I believe both of these arches are big-endian, so this might be something relevant.

**Comment by charris** [comment]
Is this a new failure or was it already in 1.14? The only thing I can think of that might have changed is endian detection. Where did you get NumPy?

**Comment by QuLogic** [comment]
It failed in [1.14.0rc1](https://koji.fedoraproject.org/koji/buildinfo?buildID=1009281), but not [1.13.3](https://koji.fedoraproject.org/koji/buildinfo?buildID=1000045). It is built from [the GitHub release tarball](https://src.fedoraproject.org/rpms/numpy/blob/master/f/numpy.spec#_21). (Note: Fedora builds have been accidentally ignoring test failures, so several arch-specific bugs may have existed for a while.)

**Comment by charris** [comment]
The test was added in #9302 and was new in 1.14.  There was a comment that that test failed on big endian. @ahaldane @eric-wieser Thoughts?

**Comment by charris** [comment]
@eric-wieser 
> I think the test is just bad - from what I remember, sorting on subarray types does a byte-wise, not index-wise, comparison. This isn't a maskedarray bug, it comes from ndarray itself.

So it would be an accident that the first failure is when `endwith=False`? I can see where flipping the byte order could cause problems when the fill value changes, same if some of the tested values were negative.

**Comment by charris** [comment]
So sorting works, but I suspect that the result might not be quite what #8069 expected :)

**Comment by charris** [comment]
OK, I put up the quick and dirty fix, not completely happy with it.
