### ISSUE TITLE
valueError : shapes ... not aligned ...

### ISSUE THREAD

**Issue by bassamElabid** [numpy/numpy#11737]
I'm new to python and numpy and i'm starting with machine learning and it's a little bit complicated but i'm trying my best i've tried understanding what others have posted in here and other websites and everything was like chinese so i thought i should post my problem here and please i need a specific answer on how to solve this not some words about numpy and python that i don't understand yet

```python
import numpy as np
def nonlin(x, deriv = False):
    if(deriv == True):
        return (x*(1-x))
    return 1/(1+np.exp(-x))
    



#input data
x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
    
    
y = np.array([0,1,1,0]) 

#seed

np.random.seed(1)



#synapses

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1



#training

for j in range(60000):
    
    #layers
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    #backpropagation
    
    l2_error = y - l2
    if (j % 10000) == 0:
        print ("ERROR" + str(np.mean(np.abs(l2_error))))
        
        
        #calculate deltas
        l2_delta = l2_error*(nonlin(12, deriv = True))
        
        l1_error = l2_delta.dot(syn1.T) #this is the line 48
        
        l1_delta = l1_error * (nonlin(11, deriv = True))
        
        
        #update our synapses
        
        syn1 += l1.T.dot(l2_delta)
        syn0 += l0.T.dot(l1_delta)
        
        
        print ('output after traning')
        print (l2)
```

### Error message:

this is the error 

  File "C:/Users/admin/.spyder-py3/temp.py", line 48, in <module>
    l1_error = l2_delta.dot(syn1.T)

ValueError: shapes (4,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

### python version :
i'm using python 3.6

# and thanks 👍

**Comment by seberg** [comment]
Sorry, but this is not really the forum to ask such a question, you can try stackoverflow or whatever that other stack* place was for debugging questions.  Or many other places.

The error might sound odd, but if you filter it it tells you: In that one line (which only includes a dot product) there is something wrong with the array shapes.

You seem to be aware of shapes and stuff (such as `arr.T`), so I think that should be able to figure it out yourself.

If you want to improve the error message, then that would be something to post here!
