### ISSUE TITLE
Handling of dtype bool is not straight-forward

### ISSUE THREAD

**Issue by Mereep** [numpy/numpy#11744]
I would expect a numpy array containing boolean values to react meaningful to "is True"
### Reproducing code example:

```python
import numpy as np
np.array([True])[0] is True
Out[3]: False
np.array([True])[0] == True
Out[4]: True
```
dtype evaluates to dtype('bool').

I know that the dtype is not build-in anymore, and technically it does not "point to the same object" but I see no reason why numpy should not gracefully handle that situation and do what the user obviously wants to do there.

**Comment by pv** [comment]
```
>>> type(np.array([True])[0])
<class 'numpy.bool_'>
```
The behavior is intentional and will not be changed.
If you want to cast to Python object, do
```
>>> np.array([True])[0].item() is True
True
```

**Comment by Mereep** [comment]
@pv Thanks for the fast response. Just for my personal interest: Was there a discussion about that matter? 
And is there a reason why:

`np.array([True])[0] is np.array([True])[0]
Out[53]: True
np.array([1])[0] is np.array([1])[0]
Out[54]: False`

while
`id(np.array([1])[0]) ==  id(np.array([1])[0])
Out[55]: True`

**Comment by pv** [comment]
The general design of numpy is 10+ years old. That's before my time, so I don't know the details how it was arrived at.

**Comment by eric-wieser** [comment]
The result is a singleton, but it's `np.True_` not `True`.

Your id weirdness with integers is because the first integer is destroyed before you allocate the second, so the second ends up being allocated in the same place.

**Comment by eric-wieser** [comment]
More information on [integer caching in python](https://stackoverflow.com/a/15172182/102441), which is obviously by design.

The `is` operator in python simply means "these are the same instances of the object" - the language makes no guarantees about whether two integers are identical or different instances.

**Comment by Mereep** [comment]
Well... I see the point but don't get my wrong: This looks for me like broken by design. Since this fact is absolutely invisible to me and just a optimization I don't want to see the arbitary side effect of it (And I am sure 99.9% of Python-Users are not aware of that). I see 2x same data type and 2 times the same operations but get 2x a different result. type(10) should evaluate to "const short_10" or something like that.

Anywas thanks for the link and the time 👍
