### ISSUE TITLE
Vectorize np.linalg.qr

### ISSUE THREAD

**Issue by oleg-kachan** [numpy/numpy#11741]
QR decomposition is not vectorized, i.e. expects only 2-dimensional arrays as input, while you can pass 3-dimensional arrays (a number of matrices along 0-axis) to SVD:

### Reproducing code example:

This gives error:

```python
import numpy as np

A = np.random.normal(size=(3,2,2))
[Q, R] = np.linalg.qr(A)
```

while SVD returns proper arrays U, S and V
```
[U, S, V] = np.linalg.svd(A)
```

### Error message:

```
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-237-7b6d808ca118> in <module>()
----> 1 np.linalg.qr(A)

~/lib/python3.6/site-packages/numpy/linalg/linalg.py in qr(a, mode)
    858 
    859     a, wrap = _makearray(a)
--> 860     _assertRank2(a)
    861     _assertNoEmpty2d(a)
    862     m, n = a.shape

~/lib/python3.6/site-packages/numpy/linalg/linalg.py in _assertRank2(*arrays)
    196         if a.ndim != 2:
    197             raise LinAlgError('%d-dimensional array given. Array must be '
--> 198                     'two-dimensional' % a.ndim)
    199 
    200 def _assertRankAtLeast2(*arrays):

LinAlgError: 3-dimensional array given. Array must be two-dimensional
```
### Numpy/Python version information:

1.15.0 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 17:02:57)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by czgdp1807** [comment]
The issue still persists in the master branch. I would like to investigate it.

Following is the stacktrace,

```python
1.22.0.dev0+77.g679087333
Traceback (most recent call last):
  File "code.py", line 6, in <module>
    [Q, R] = np.linalg.qr(A)
  File "<__array_function__ internals>", line 6, in qr
  File "/home/czgdp1807ssd/numpy_project/numpy/numpy/linalg/linalg.py", line 907, in qr
    _assert_2d(a)
  File "/home/czgdp1807ssd/numpy_project/numpy/numpy/linalg/linalg.py", line 191, in _assert_2d
    'two-dimensional' % a.ndim)
numpy.linalg.LinAlgError: 3-dimensional array given. Array must be two-dimensional
```

**Comment by eric-wieser** [comment]
Implementing this would amount to moving the python implemention into C, where it can be placed into a gufunc inner loop. This is fairly involved, but it should be possible to largely follow the pattern used by existing functions like `lstsq`

**Comment by czgdp1807** [comment]
Hi @eric-wieser Thanks for the direction. I just started today with `numpy` and made some changes (at Python level) for allowing computation of results for matrices with higher than two dimensions. I will undo those changes and follow the pattern similar to `lstsq`. Could you please confirm if I should add `qr` in `numpy/linalg/umath_linalg.c.src` (see below for the location in the file I am referring too) as is the case with other `linalg` functions? Thanks.

https://github.com/numpy/numpy/blob/6790873334b143117f4e8d1f515def8c7fdeb9fb/numpy/linalg/umath_linalg.c.src#L3166

and other places where `lstsq`, `svd` are referred in the same file?

**Comment by eric-wieser** [comment]
Yes, that's the right approach I think.

**Comment by czgdp1807** [comment]
I think only `lstsq` and `qr` are required to be vectorised. Rest of the functions are already working fine with stacks of matrices. Please let me know if I missed out anything here. Thanks.
