### ISSUE TITLE
garbled formulae in NumPy documentation

### ISSUE THREAD

**Issue by kfjahnke** [numpy/numpy#11753]
I'm having difficulties displaying the NumPy reference in HTML format. There seems to be some formatting shining through which isn't correctly translated to HTML, or the rendering engine can't display the content properly.

The problem shows, for example, when looking at [the ndarray reference](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html), subsection "Internal memory layout of an ndarray". Here I get garbled formulae like this:

n_{\mathrm{offset}} = \sum_{k=0}^{N-1} s_k n_k

The problem occurs both with firefox and chromium on kubuntu 18.04, the docu is version 1.15.

**Comment by matthew-brett** [comment]
The markup looks correct in the source, maybe there's a problem with `sphinx.ext.imgmath` ?

**Comment by mattip** [comment]
This seems to be a problem with scipy.org the [page at numpy.org](http://www.numpy.org/devdocs/reference/arrays.ndarray.html?highlight=internal#internal-memory-layout-of-an-ndarray) look OK

**Comment by pv** [comment]
Probably some problem in the local configuration (missing latex or some other reason for imgmath to not work?) of the person who built the docs.

**Comment by matthew-brett** [comment]
Is there a way of crashing out if the local configuration is not up to spec?

I'm sure it was a concious decision not to use MathJax - but is worth revisiting that question?

**Comment by pv** [comment]
For Scipy docs, we use bundled Mathjax https://github.com/scipy/scipy/pull/7376/commits/752e31f7338653cd49e8b9daf370515402446111 --- it's better to bundle mathjax than get it from CDNs as the docs are then readable also offline, and you don't need to update things if CDNs change (as happened already with mathjax https://www.mathjax.org/cdn-shutting-down/).

**Comment by rgommers** [comment]
- that page looks fine now, do you still have a problem @kfjahnke ?
- bundling MathJax in the same way as for the SciPy docs seems like a good idea.
- for the record: I usually build the NumPy docs for a new release. we cannot auto-build them with CI and deploy them as long as we're hosting everything on the current docs.scipy.org server (this has been discussed before)

**Comment by eric-wieser** [comment]
I think #12194 duplicates this

**Comment by pdebuyl** [comment]
The doc seems to render fine.

The issue was in the formula for n_offset at https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray

I propose to close.

**Comment by mattip** [comment]
Closing. Please open a new issue if output is still garbled.
