### ISSUE TITLE
Exporting mtrand.RandomState to public Cython API

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#11764]
Was wondering if it would be possible to include a Cython header file that exports `mtrand.RandomState` for use in other Cython code.

**Comment by bashtage** [comment]
I don't think this will happen for RandomState, but may happen for its successor that comes from the NEP 19 process. 

[randomgen](https://github.com/bashtage/randomgen) exposes some Cython API. See [these examples](https://github.com/bashtage/randomgen/tree/master/randomgen/examples).

**Comment by bashtage** [comment]
@mattip I think this wishlist item can be close since there is an API for Generator now.

**Comment by mattip** [comment]
Closing, thanks.
