### ISSUE TITLE
a['f0'].dtype != a.dtype['f0']

### ISSUE THREAD

**Issue by mamikonyan** [numpy/numpy#11769]
When a structure has a sub-array field, its dtype is reported differently in the following cases:
```
import numpy as np
>>> a = np.zeros(1, dtype=[('f0', 'i4', 3)])
>>> a.dtype['f0']
dtype(('<i4', (3,)))
>>> a['f0'].dtype
dtype('int32')
```
I am not sure if this is intended or if there is a good reason for this behavior, but it's rather unhelpful in my situation.

**Comment by charris** [comment]
I think the two are different things, the first refers to the dtype for the structured array subarray, the second for the subarray.

**Comment by mamikonyan** [comment]
I see. I suppose it's consistent with
```
>>> np.zeros(1, np.dtype('2i')).dtype
dtype('int32')
```
But on the other hand, something seems muddled because subarray dtypes conflate type and shape information, and later lose the shape. Even though the memory layout is the same and from the point of view of C arrays there is no distinction, both NumPy and HDF5, where I'm currently seeing this issue, can represent the difference in their type systems:
```
>>> scalar, array = np.dtype('i'), np.dtype('2i')
>>> scalar == array
False
>>> np.zeros(1, scalar).dtype == np.zeros(1, array).dtype
True
```
However, NumPy freely converts 1-D arrays of nested arrays to 2-D arrays, but HDF5 doesn't, i.e., the type of a 1-D dataset of H5T_ARRAY is distinct from that of a 2-D dataset of the same underlying type.

Just a comment on how the two type systems interact...

**Comment by eric-wieser** [comment]
What you're identifying here is that subarrays decay to an extra dimensions:
```
>>> a = np.zeros(10, (np.int32, 5))
>>> a.shape
(10, 5)
>>> a.dtype
int32
```

This is far too old a design decision to change. If you want the subarray not to decay, the workaround is:
```
>>> a = np.zeros(10, [('value', (np.int32, 5))])
>>> a.shape
(10,)
```

**Comment by seberg** [comment]
I will close this. As noted by Eric and Chuck there seems no actionable issue here. Subarrays are absorbed into arrays on indexing, it is not likely to change. If someone disagrees, just reopen or create a new issue.
