### ISSUE TITLE
ascontiguousarray/asfortranarray take longer than flag check on matching order arrays

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#11804]
It appears to take ~1µs to call `ascontiguousarray` or `asfortranarray` on an array that already matches the expected order. Simply checking the order of the array and skipping if satisfied takes ~90ns. It's a little surprising that `ascontiguousarray` or `asfortranarray` take a little over an order of magnitude longer. Any thoughts why?

### Reproducing code example:

```python
In [1]: import numpy as np

In [2]: a = np.random.random((200, 300)).copy(order='C')

In [3]: %%timeit
   ...: np.ascontiguousarray(a)
   ...: 
1.48 µs ± 93.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [4]: %%timeit
   ...: if not a.flags.c_contiguous:
   ...:     np.ascontiguousarray(a)
   ...: 
86.8 ns ± 1.72 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [5]: b = np.random.random((200, 300)).copy(order='F')

In [6]: %%timeit
   ...: np.asfortranarray(b)
   ...: 
1.38 µs ± 15.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [7]: %%timeit
   ...: if not b.flags.f_contiguous:
   ...:     np.asfortranarray(b)
   ...: 
87.8 ns ± 1.89 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

### Numpy/Python version information:

```
1.15.1 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

**Comment by mattip** [comment]
The call to b.flags is much simpler. It does this where the code is in (python) or (c)
```
b.flags.c_contiguous (python) ->
    PyGetAttrString(b, "flags") (c) ->
        array_flags_get (c) -> 
            PyArray_NewFlagsObject(b)->
                array_flags_contiguous_get
```
where np.asarraycontiguous does
```
np.ascontiguousarray(a) (python) ->
    np.array(a, dtype=None, copy=False, order='C', ndmin=1) (python) ->
        _array_from_object(...) (c) ->
            various arg parsing and condition checking to
            determine no copy is necessary
```
kwarg parsing is known to be slower than a direct function call.

**Comment by eric-wieser** [comment]
`ascontiguousarray` does extra work of converting non-arrays to arrays too

**Comment by jakirkham** [comment]
Interesting. Thanks for the info.

Is there a point in the code where we could inject a flag check like this to avoid extra work?

**Comment by seberg** [comment]
If we really want to micro-optimize these things, we would have to move them to C, no? Even a call to `isinstance(arr, ndarray)` takes about as much time as the flags check.

**Comment by jakirkham** [comment]
Agreed. Where on the C side would this best fit?

**Comment by hmaarrfk** [comment]
is there a way to do the instance check without calling the python engine? 

On my computer ascontiguous take 300ns. You can shave some 50ns by using functools.partial
```python
import functools
ascontiguousarray = functools.partial(array, copy=False, order='C', ndmin=1)
```
seems to pass tests. I don't know how to get the docs to appear right. 

You can also shave those ns on np.asarray and np.asanyarray (just other convenience functions that come to mind).

You'll probably run into other issues like somebody wanting to specify positional arguments in a strange order

At that point, the largest contributor to the slowdown is `asarray(copy=False)` which seems to be implemented in C. That alone takes 170 us.

**Comment by seberg** [comment]
This has been fixed by my new argparsing code and moving these `array` "aliases" to C.

**Comment by jakirkham** [comment]
Looking forward to taking it for a spin 😁

**Comment by seberg** [comment]
@jakirkham this has been around for a while, you are certainly already using it.

**Comment by jakirkham** [comment]
Oh sorry 🤦‍♂️

Yep looks great! 🎉

```python
In [1]: import numpy as np

In [2]: a = np.random.random((200, 300)).copy(order='C')

In [3]: %%timeit
   ...: np.ascontiguousarray(a)
   ...: 
   ...: 
70.3 ns ± 0.192 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: b = np.random.random((200, 300)).copy(order='F')

In [5]: %%timeit
   ...: np.asfortranarray(b)
   ...: 
   ...: 
68.4 ns ± 0.427 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
