### ISSUE TITLE
Export convertors of distributions

### ISSUE THREAD

**Issue by KOLANICH** [numpy/numpy#11807]
I guess, that algos generating samples from distributions work the following way - initially they take samples of uniform distribution and then convert it to the needed one using some algo.

It would be nice to expose these algos as convertor functions getting samples from uniform distribution and returning the corresponding samples from the desired one. I certainly can use inverse cdf for that, but I guess that more efficient methods are used in the libs of this kind.

**Comment by eric-wieser** [comment]
Not all algorithms work in that way - some need multiple samples from a uniform distribution, varying from exactly 2 samples to an unbounded number of samples (rejection sampling).

**Comment by KOLANICH** [comment]
OK. Do numpy/scipy contain any fast approximations for inverse CDFs?

**Comment by mattip** [comment]
This is the domain of `scipy.stats`, specifically `ppf`. Closing.
