### ISSUE TITLE
MemoryError for large numpy arrays

### ISSUE THREAD

**Issue by akshaykri** [numpy/numpy#11808]
I am trying to manipulate large N x N numpy arrays, but running into a MemoryError, for N >= 45022. It works fine for N <=45021. As per the advice on [this](https://software.intel.com/en-us/articles/large-matrix-operations-with-scipy-and-numpy-tips-and-best-practices) Intel webpage, I am using the [Miniconda](https://conda.io/miniconda.html) distribution of python. I am running this code on a single node of a cluster with 32 cores and 512 GB RAM. Further a `cat /proc/cpuinfo | grep address` tells me that all processors have address sizes that are 46 bits physical, 48 bits virtual.

A 45000 x 45000 array of 64 bit floats is an object with 2.025 billion 8-byte numbers, and should take only 16 GB of RAM, so I am not quite sure why this problem occurs. Also 2.025 billion is much smaller than 2^46 (~ 70 trillion).

### Reproducing code example:

```
import numpy as np

N = 45022
M = np.ones((N,N), dtype='float64')
print(np.sum(M))
```

Identical problems occur with `np.zeros()` and `np.random.rand()`, but with slightly different error messages.

### Error message:
```
Traceback (most recent call last):
  File "prog1.py", line 5, in <module>
    M = np.ones((N,N), dtype='float64')
  File "/group/user13/miniconda/miniconda3/envs/idp/lib/python3.6/site-packages/numpy/core/numeric.py", line 188, in ones
    a = empty(shape, dtype, order)
MemoryError
```
### Numpy/Python version information:

output from `sys.version`
3.6.3 |Intel Corporation| (default, May  4 2018, 04:22:28) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

output from `numpy.__version__`
1.14.3

Any help or suggestions would be greatly appreciated. I aim to handle 85000 x 85000 matrices.

**Comment by eric-wieser** [comment]
My understanding was that on 32-bit systems the maximum array size would be < 4GB, so it looks like something else is happening here

**Comment by seberg** [comment]
No, we force `np.intp` size in bytes, so that should be <2GB, since that is signed. And since we do all offset calculations in `np.intp`/`ssize_t`, it probably needs a lot of refactor to allow more.

**Comment by akshaykri** [comment]
I believe it is not a 32-bit issue as `print(np.iinfo(np.intp))` gives me the following output.

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

**Comment by seberg** [comment]
Then... frankly my guess is your cluster probably setting some limits on your processes, which makes a lot of sense for example if you have a queuing system running (although 2 or 4Gb seems little for a 512Gb node).
Might try with some non-python allocations to see if that is really the case, numpy, on 64bits, certainly has no issue with gigantic arrays, normally.

Maybe check what `ulimit -v` says, but I am just guessing.

**Comment by seberg** [comment]
Ah wait, you have 16Gb, so... it might be expecting 32 independend processes so limiting each to 16GB to be sure.

**Comment by seberg** [comment]
Ah @eric-wieser sorry, now I get your point :), the array is too cause a numpy error due to 32bits, opst.

**Comment by akshaykri** [comment]
Thank you! I added a `ulimit -v unlimited` before calling my python script and it worked as expected without a MemoryError.
Sorry I thought this was a numpy issue and didn't realize it had to do with the defaults on my cluster. I appreciate the help!

**Comment by seberg** [comment]
Might want to set a large limit to be sure to not clog up the machine, someone set the limit for a reason probably. Also I assume you know that you can use those resources and are not sharing them a lot....
