### ISSUE TITLE
array_split incorrect behavior with array size bigger MAX_INT32

### ISSUE THREAD

**Issue by StrikerRUS** [numpy/numpy#11809]
`numpy.array_split()` produces empty last chunk in case of original array size is bigger than MAX_INT32.

### Reproducing code example:

**NOT OK**:
```
import numpy as np
test = np.random.rand(1 << 31, 1)
for chunk in np.array_split(test, 2):
    print(chunk.shape)

>>>(1073741824, 1)
>>>(0, 1)
```

**NOT OK**:
```
import numpy as np
test = np.random.rand(1 << 31, 1)
for chunk in np.array_split(test, 3):
    print(chunk.shape)

>>>(715827883, 1)
>>>(715827883, 1)
>>>(0, 1)
```

**OK**:
```
import numpy as np
test = np.random.rand(1 << 30, 1)
for chunk in np.array_split(test, 2):
    print(chunk.shape)

>>>(536870912, 1)
>>>(536870912, 1)
```

**OK**:
```
import numpy as np
test = np.random.rand((1 << 31) - 1, 1)
for chunk in np.array_split(test, 2):
    print(chunk.shape)

>>>(1073741824, 1)
>>>(1073741823, 1)
```

### Numpy/Python version information:

```
numpy.__version__
>>> 1.14.4

sys.version
>>> 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
```

112 GB of RAM to exclude the problem with the memory lack.

**Comment by StrikerRUS** [comment]
In addition, there is a misleading comment in the source code of `array_split`:

https://github.com/numpy/numpy/blob/5adb81051086a45fe3b59ba506b567340ec9bd5e/numpy/lib/shape_base.py#L686-L692

Should be:

```
# handle array case.
```

**Comment by seberg** [comment]
Want to create a PR about it? I am pretty sure the bug is just below those lines of code. There is an array being created and then `cumsum`ed, that array has to be of `dtype=np.intp` (or a similar solution).

Tests should be possible using broadcasted arrays (on 64bit)

**Comment by StrikerRUS** [comment]
@seberg 
Thank you very much for the solution!
I applied your fix locally and it solved the problem of the last empty chunk.
I'll create a PR.

**Comment by seberg** [comment]
Thanks all!
