### ISSUE TITLE
Invalid integer comparison

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#11801]
With Python 3.7.0 and Numpy 1.15.0 (Anaconda version):

```python
>>> v = np.int64(np.iinfo(np.int64).max)
>>> v
9223372036854775807
>>> type(v)
numpy.int64
>>> v < 2**63
False
>>> int(v) < 2**63
True
```

**Comment by eric-wieser** [comment]
`2**63` is converted to a numpy `uint64`. The comparison `int64 < uint64` is undefined, so it promotes to `float64 < float64`, and the precision is reduced, making them equal.

**Comment by eric-wieser** [comment]
Perhaps we ought to deprecate the promotion from integers to floats, and just switch to object arrays instead.

**Comment by pitrou** [comment]
Comparison `int64` with `uint64` sounds at least semantically well-defined to me.

**Comment by eric-wieser** [comment]
Sure, in this case I simply meant "we don't define it". `uint64 + int64` is a similar case that is actually ill-defined

**Comment by pitrou** [comment]
Well, addition *is* ambiguous in case of overflow, but comparison is not ;-)

**Comment by eric-wieser** [comment]
> addition is ambiguous in case of overflow

Worse than that, the type of `uint + int` is ambiguous in all cases.

You're correct that comparison can be perfectly well-defined, but the C compiler won't define it for us sadly.

**Comment by seberg** [comment]
Closing this one in favor of the related gh-12525.  Keeping that open since comparisons are maybe a special case compared to the general promotion problem in gh-20905.
