### ISSUE TITLE
Matrix multiplication does not release the GIL

### ISSUE THREAD

**Issue by lsorber** [numpy/numpy#11821]
Many people seem to be under the impression that numpy operations will generally release the GIL when it can. However, I tried a few matrix-vector multiplication variants (see minimal reproducing example below), and it looks like only the `np.einsum` variant will actually release the GIL.

Matrix multiplication seems like a pretty good candidate to release the GIL. Is this a bug, or intentional?

### Reproducing code example:

```python
import numpy as np
from concurrent.futures import ThreadPoolExecutor, wait

A = np.random.randn(200_000, 300)
b = np.random.randn(300)

def matvec(variant):
    if variant == 0:
        return A @ b
    if variant == 1:
        return A.dot(b)
    if variant == 2:
        return np.dot(A, b)
    if variant == 3:
        return np.tensordot(A, b, axes=1)
    if variant == 4:
        return np.einsum('ij,j', A, b)

for variant in range(5):
    with ThreadPoolExecutor(max_workers=2) as e:
        print(f'\nMatvec variant={variant}:')
        %timeit f1 = e.submit(matvec, variant); wait([f1])
        %timeit f1 = e.submit(matvec, variant); f2 = e.submit(matvec, variant); wait([f1, f2])
```

Notice that running two matvecs roughly doubles the timings, except for the `np.einsum` variant:
```
Matvec variant=0:
34.3 ms ± 2.58 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
62.2 ms ± 3.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=1:
33.3 ms ± 1.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
61.7 ms ± 3.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=2:
33.7 ms ± 2.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
60.2 ms ± 1.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=3:
33.8 ms ± 1.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
61.6 ms ± 1.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=4:
54.3 ms ± 3.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
52.9 ms ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

### Numpy/Python version information:

Results are similar for both OpenBLAS and MKL.
```
1.15.0 3.7.0 (default, Jun 28 2018, 07:39:16) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by njsmith** [comment]
The OpenBLAS and MKL versions aren't just releasing the GIL; they're also also using multithreading internally, so one call can already saturate all your cores by itself. Einsum isn't multithreaded, so you need two of them to use two CPUs.

If you set the envvar `OMP_NUM_THREADS=1` to force OpenBLAS and MKL to be single threaded internally, you should see results more like you were expecting.

**Comment by lsorber** [comment]
@njsmith Indeed, the cores being saturated by a single matvec seems to be the main issue. Thanks!

Playing around with `OMP_NUM_THREADS` it's clear that estimating the performance of parallel matvecs is not trivial. I've included some timings for `BLAS=[OpenBLAS, MKL] x OMP_NUM_THREADS=['', '1', '2']` below on my machine with 4 physical cores. Some observations:
1. Even though my machine has 4 physical cores, computing 2 matvecs OpenBLAS simultaneously with `OMP_NUM_THREADS=2` is as slow as computing them sequentially.
2. For MKL, setting `OMP_NUM_THREADS=2` is actually faster than letting it choose the number of threads for a single matvec _and_ it allows two matvecs to finish in the same time.

<details>
<summary>OpenBlas with `OMP_NUM_THREADS` not set</summary>

```
Matvec variant=0:
35.9 ms ± 2.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
63.9 ms ± 5.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=4:
36.2 ms ± 3.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
35.6 ms ± 3.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
</details>

<details>
<summary>OpenBlas with `OMP_NUM_THREADS=1`</summary>

```
Matvec variant=0:
39.4 ms ± 9.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
41 ms ± 5.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=4:
31.7 ms ± 964 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
35.6 ms ± 3.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
</details>

<details>
<summary>OpenBlas with `OMP_NUM_THREADS=2`</summary>

```
Matvec variant=0:
36.7 ms ± 1.88 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
57.8 ms ± 2.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=4:
33.1 ms ± 3.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
33 ms ± 1.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
</details>

<details>
<summary>MKL with `OMP_NUM_THREADS` not set</summary>

```
Matvec variant=0:
27.4 ms ± 2.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
63.7 ms ± 2.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=4:
33.1 ms ± 1.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
32.9 ms ± 380 µs per loop (mean ± std. dev. of 7 runs, 10 loops each
```
</details>

<details>
<summary>MKL with `OMP_NUM_THREADS=1`</summary>

```
Matvec variant=0:
46.5 ms ± 1.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
38.4 ms ± 2.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=4:
34.9 ms ± 3.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
33.8 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
</details>

<details>
<summary>MKL with `OMP_NUM_THREADS=2`</summary>

```
Matvec variant=0:
20.6 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
24.1 ms ± 5.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Matvec variant=4:
38.9 ms ± 7.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
45.5 ms ± 2.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
</details>

I'll go ahead and close this issue since the GIL is in fact released. That being said, based on the above experiments getting the benefits of the released GIL is not that straightforward.
