### ISSUE TITLE
tcsh/csh resource file infecting f2py/distutils?

### ISSUE THREAD

**Issue by mathomp4** [numpy/numpy#11824]
This is a weird bug that is hard to reproduce because, honestly, we don't know what's causing it. A code I work on at NASA uses f2py in a couple of places. And, say, for me, there is never any problem. But for a growing number of our users, they have an issue where f2py just does not work for them. The symptom seems to be that something in their environment causes the f2py compiler detection (done through distutils, I think) to go a bit nuts. For example, for some users if they have:

`echo`

in their .cshrc/.tcshrc file, f2py stops working.

Now, in some cases, I can get them working by instead of just pointing to the name of the compiler:

`f2py    --f77exec=mpiifort --f90exec=mpiifort --fcompiler=intelem`

I pass in the full path:

`f2py    --f77exec=/full/path/to/mpiifort --f90exec=/full/path/to/mpiifort --fcompiler=intelem`

But, again, this doesn't always work. For some users it doesn't help, the issue seems to be that even though we've told f2py that we are using Intel/intelem, it finds gfortran in the environment, tells ifort to use the flags for that, and ifort -fopenmp crashes. 

Eventually, a user was able to "fix" this by adding a line to `exec_command.py` after:

https://github.com/numpy/numpy/blob/d210300bc1b1a849a5df618b47b00cba501f51b4/numpy/distutils/exec_command.py#L233-L240

of `command.insert(1, '-f')`. By doing this, the shell command does not load the rc file in tcsh/csh. 

By default, `tcsh -c command` will source the resource file, which can lead to issues. (For other shells, `-f` seems to be pretty neutral in, say, bash and zsh. I haven't tested in fish, but I'm guessing fish is weird enough it doesn't work.) We can't envision scenarios where f2py needs environment variables from sourcing the resource/startup files when this command is run.

Our shop mainly uses tcsh as the interactive shell due to historical and practical reasons, so this is important to us, so much so that we are planning on editing any `numpy` we get from Anaconda, Intel, wherever.

### Reproducing code example:

I was able to reproduce this with and without the `echo` in the rc file using the `fib1.f` example here: https://docs.scipy.org/doc/numpy/f2py/getting-started.html but another user couldn't replicate it.

### Error message:

I'm attaching three files for this so you can see what's happening. In one case I pass in the full FC path and things work. In the next, I don't use the full path and it fails. In the last, I patch our distutils and don't pass in the full path and things work.

[fullfc.log](https://github.com/numpy/numpy/files/2325168/fullfc.log)
[nofullfc.log](https://github.com/numpy/numpy/files/2325169/nofullfc.log)
[nofullfc.patch.log](https://github.com/numpy/numpy/files/2325170/nofullfc.patch.log)

I'll also attach two files from a colleague who got hurt with this and he inserted prints into the f2py process:

[outY.log](https://github.com/numpy/numpy/files/2325189/outY.log)
[outX.log](https://github.com/numpy/numpy/files/2325190/outX.log)

This seems to show it's during the `exec_command` for the compiler version.

### Numpy/Python version information:

`('1.14.2', '2.7.14 |Anaconda, Inc.| (default, Mar 27 2018, 17:29:31) \n[GCC 7.2.0]')`

**Comment by charris** [comment]
Did f2py used to work with those shells? Also, I note that you are using Anaconda, which may be a complication in determining cause. Does everyone define `SHELL` in their environment?

**Comment by charris** [comment]
What OS?

**Comment by charris** [comment]
Also, looks like you are using the Intel compiler, correct?

**Comment by charris** [comment]
>  tells ifort to use the flags for that, and ifort -fopenmp crashes.

OK, I think we have had similar problems with clang.

**Comment by mathomp4** [comment]
There are a couple of OSs. The fullfc/nofullfc were run on a CentOS 7 box. The other outfiles are from a SLES11SP3 cluster.

And, yes, we are using Intel 18 with Open MPI (on the desktop) and Intel MPI or HPE MPT on the cluster. In both cases, a recent-ish version of GCC (6.3-ish) is loaded as the base libraries for the model require a newer GCC than on the system. But, in each case, the Fortran compiler is Intel and we enforce it with the --fcompiler (though, as I said, sometimes distutils or f2py seems to not believe me).

**Comment by mathomp4** [comment]
Also, I am using Anaconda on the desktop. On the cluster, it's a custom Python distribution mainly built by hand, I believe.

f2py in olden days did used to work on the cluster. I want to think the trouble started around the time I reported #8941 and #8973 was merged. It's like things got better and worse all at once.

**Comment by pv** [comment]
A previous maybe similar failure case was due to F77/F90 environment variables being set to point to gfortran while --fcompiler pointed to Intel.

In principle there should be no need for numpy.distutils to invoke shell. Basically, any use of `exec_command` is "wrong", now that Python stdlib has the `subprocess` module. I count ~10 calls to exec_command in numpy.distutils, so it should not be very hard to revise them, which even could be done one by one. (Not volunteering to do it myself though.)

**Comment by mathomp4** [comment]
I did a few tests outside of numpy and, I think, the only shells (if `exec_command` stays) that care about this are tcsh and csh. It seems that both bash and zsh don't have the same need for -f. And, as expected, fish just crashes with a -f.

**Comment by tylerjereddy** [comment]
So, is there consensus that gradually removing `exec_command` usage in `distutils` is the way to go here? Is it likely that only the Fortran-related distutils components could be edited first in this manner to fix it, or is it pretty likely that there are indirect effects from `exec_command` shell invocations elsewhere in distutils?

**Comment by charris** [comment]
@tylerjereddy it sounds like we should dispense with exec_command in general. The reason that f2py is special here is that they aren't trying to build numpy, just fortran files.

**Comment by charris** [comment]
If you are thinking of taking on the job, go for it. I was going to do it myself...

**Comment by tylerjereddy** [comment]
Yeah, I should start on this & @stefanv thinks it is a good idea for me to.

**Comment by charris** [comment]
See also #9970 for a duplicate.

**Comment by tylerjereddy** [comment]
@mathomp4 Could you possibly see if #11898 addresses this issue? That is the last PR that should need to be merged to solve it, but would be nice to get confirmation as adjusted C compiler detection is a little scary.

**Comment by mathomp4** [comment]
@tylerjereddy 

I think recent changes to numpy/f2py might have broken our f2py use again. We recently installed Anaconda 2019.03 and did a `conda install numpy` with that and all of the sudden, issues have returned. I'm working with our Python experts here to see if we can figure out what's happening.

**Comment by mathomp4** [comment]
@tylerjereddy Okay. I have some more information.

This is fun. It turns out that Conda currently has numpy 1.16.3 (we have 1.16.2, but it's wrong in both). The problem is that that version does not have the bug fix from 73de62ffe8aada29666c809d08825a362d9fb408 for Intel compilers. Guess what compiler we use?

I was doing all this nice Python debugging and was going to post a nice long investigation and then I looked at the history for `ccompiler.py` and found you already found this. I'll work with my people here to do a code injection for now to fix this. 

Will you be releasing a 1.16.4 with this fix (so that Conda picks it up)? I know 1.16 is the last 2.7 numpy, and we are (unfortunately) still a mainly 2.7 shop (though we are soon to issue an edict to update scripts as we will stop *installing* 2.7). For now, I'll add the code injection to our Anaconda installation script as a post-processing step.

**Comment by charris** [comment]
@mathomp4 Thanks for the heads up. I've marked the fix for backport.

**Comment by mathomp4** [comment]
@charris Thanks. A morning filled with adding print statements through numpy...when I should just check the git log first. :)

**Comment by seberg** [comment]
Was this resolved? In which case we can probably also close gh-10853?

**Comment by seberg** [comment]
@mathomp4 this issue is pretty old, and it seems like it should have been fixed probably? We decided to close this issue, but please ping us if you are still experiencing anything so we can reopen!
