### ISSUE TITLE
Inaccurate results from numpy.linalg.svd

### ISSUE THREAD

**Issue by SaTjemkes** [numpy/numpy#11828]
### Reproducing code example:

```python
import numpy as np
def do_the_svd(n):
    a = np.random.randn(n, n)
    U, s, V = np.linalg.svd(a)
    return np.allclose(a, np.dot(U, np.dot(np.diag(s), V)))
if __name__== "__main__":
    for n in [9,90,900]:
        print ("size {}, svd check {}".format(n, do_the_svd(n)))

```

### Error message:

upon execution of the above code, the first value for n (9) will return a True response, but for 90 or 900 the outcome is False.
i did not encounter this with older versions of numpy 1.14.0dev0+88f8310 
Note that  new numpy is implemented on Ubuntu 18.04, while the older version is running under ubuntu 14.04
using the fortran 90 equivalent (under the ubuntu 18.04 system), linking to same blas library generates good results.

### Numpy/Python version information:

1.16.0.dev0+ac4d480 python 3.6 using openblas'

**Comment by SaTjemkes** [comment]
python 3.6.1 and numpy 1.16.0.dev0+ac4d480

**Comment by charris** [comment]
> linking to same blas library generates good results.

Are you saying that this looks like a BLAS problem?

**Comment by SaTjemkes** [comment]
Not sure where exactly the problem is. I can do a svd using fortran90 using the openblas library without any problems. Same matrix as in python code. So it could be the link of numpy to openblas. but that is a wild guess and way beyond my knowledge. (openblas 0.2.20)

**Comment by seberg** [comment]
@SaTjemkes did you remember when comparing with fortran that numpy uses C-order arrays as default, so the parameters would be different probably? (also a bit wonderig how big the error is)

**Comment by SaTjemkes** [comment]
@seberg: The errors can be pretty big, and I consider this as a very serious bug. Some background: I am using the standard svd in a complex processing package for many years. And it generated good results. It was only recently that I upgraded to ubunut 18.04, and the current versions of numpy/scipy/openblas that my processor failed on all cases. It turned out that some matrix manipulations involving square root of a matrix, generated garbage. (matrices of 500 x 3000 elements). I do not know the exact details of the implementation but there are several ways to do an svd. And I suspect that some machine dependent settings are corrupting the svd for larger matrices.  To come back to your question: the np.allclose tests if two matrices are close. Normally you expect differences 1e-5 or smaller. I have found differences O(100) or more  meaning two completely different matrices. It is relatively easy to generate an python module out of the f90 code,  using f2py. When creating the fortran interface indeed you have to indicate that order of your matrices are conforming Fortran90 convention. Otherwise you run into trouble. So this is not an issue. My F90 program (called from the python module on exactly same matrix used by the numpy.linalg.svd, generate differences between the original  and reconstructed matrix using the U, s, VT generated by the F90 program of the order 1e-14 as it should.

**Comment by eric-wieser** [comment]
I get True in all cases running this on windows with `lapack_lite`

**Comment by mattip** [comment]
@SaTjemkes it is not clear which change actually caused the problem. It might be something specific to your system: your compiler, your version of OpenBLAS or alternative library. It seems you are compiling NumPy yourself. You should be able to reproduce our tests, from the git checkout run
```
python runtests.py -t numpy/linalg/tests/test_linalg.py
```
or from python (after installing NumPy, and outside the git checkout)
```
python -c"import numpy; numpy.linalg.test()"
```
If these tests fail there is something wrong with your installation, since our CI passes the tests. We may be able to help you work out what is wrong, but you need to tell us exactly how you installed NumPy and what OpenBLAS (or alternative) you are using, and what compiler.

**Comment by SaTjemkes** [comment]
@mattip 
numpy was installed using guidance from  website by cloning the latest version from repository: (from my history file)
  173  git clone https://github.com/numpy/numpy.git numpy
  174  ls
  175  cd numpy/
  176  ls
  177  python3 setup.py build
  178  python3 setup.py install
  179  cd ..
  180  git clone https://github.com/scipy/scipy.git scipy
  181  cd scipy/
  182  python3 setup.py build
  183  python3 setup.py install
 
All done as normal user. 
the openblas library was compiled in similar manner (from script)
    mkdir build && cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=${PREFIX}
    make install PREFIX=${PREFIX}

after installing numpy/scipy openblas was found. I have 
export OMP_NUM_THREADS=1

regarding your numpy.linalg.test() (running python3.6)

python3 -c"import numpy; numpy.linalg.test()"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/stephen/.local/lib/python3.6/site-packages/numpy-1.16.0.dev0+ac4d480-py3.6-linux-x86_64.egg/numpy/_pytesttester.py", line 128, in __call__
    import pytest
ModuleNotFoundError: No module named 'pytest'


hope this helps 
thanks

**Comment by SaTjemkes** [comment]
python 3.6.3
gcc 7.3.0 on linux
lubuntu 18.04 
numpy 1.16.0.dev

on the system all works fine: ubuntu 14.04, python 3.6.3, gcc 4.8.4; but an older version of numpy/scipy (1.14.0.dev0)

**Comment by SaTjemkes** [comment]
now after pytest installed
python3 -c"import numpy; numpy.linalg.test()"
NumPy version 1.16.0.dev0+ac4d480
NumPy relaxed strides checking option: True
.................................................................................................................................................................... [ 62%]
.................................................................................................                                                                    [100%]
261 passed, 22 deselected in 6.57 seconds

**Comment by SaTjemkes** [comment]
some further info
If i run for n=9 my test, then both U,s,Vt are same for numpy.linalg.svd and the f90 vers
if i run for n=39, then it starts getting corrupted. Meaning eigenvalues are identical, but the U starts to deviate. plotting numpyU - f90U as function of i shows that there are deviations between the two base functions which changes with U number. 
![figure_n39](https://user-images.githubusercontent.com/42771967/44777376-c6889600-ab7a-11e8-98f3-e3834ff6d579.png)
.

**Comment by seberg** [comment]
@SaTjemkes yeah, well was just wondering, because I guess it seems not unlikely to be an issue in the OpenBLAS rather then numpy, so if you are sure it tests the exact same OpenBLAS call, we know it is has something to with linking, or the OpenBLAS shipped by numpy or so.

If it is in OpenBLAS, I guess it could even be hardware dependend because of kernel specializations? Not an easy thing to figure out :(.

**Comment by SaTjemkes** [comment]
The only thing i can do is go back to a previous version of ubuntu and check again. keep you posted.

**Comment by SaTjemkes** [comment]
Went back to lubuntu 16.04 and installed openblas-dev and openblas-base from repository (sudo apt-get install etc ect), ditto for python3 and the setuptools, dev etc to get the headers.
Then I installed the latest numpy after i pulled it from git repository (git clone etc), which is using gnu c 5.4.0 for compilation. and have no problems what so ever. 
Meaning with the material from repository there should be no issue

now i am running my own installation script (building all tools from src) which will take some time (i need this for building my docker system)

will keep you posted

**Comment by bashtage** [comment]
Test passes using the OpenBlas/PyPI wheels on Ubuntu 18.04.  Also conda/MKL on same system.

**Comment by SaTjemkes** [comment]
Solved.
To make a long story short: problems were initiated because the openblas 0.2.20 was complied using the experimental cmake utility shipped with the distribution. If instead it is compiled using the shipped makefiles it is all fine. 
Using OpenBlas 0.2.20 on haswell architecture, numpy 1.16, (l)ubuntu 18.04, gcc 7.3.0. 
It is also working if the openblas is installed from the repository
for an unknown reason if the OpenBlas makefiles are generated using the cmake utility it causes problems with numpy/scipy on my system. Maybe an environment setting is not correct or ??.

**Comment by SaTjemkes** [comment]
Many thanks for the suggestions pointing to the problem and the efforst

**Comment by charris** [comment]
@SaTjemkes Thanks for following through. You should report this to the OpenBLAS folks: https://github.com/xianyi/OpenBLAS.
