### ISSUE TITLE
einsum freezes for unknown reason

### ISSUE THREAD

**Issue by lmtsui** [numpy/numpy#11820]
when using einsum to contract tensors of some dimensions, it randomly got stuck and will return an answer after a long pause. For example,

### Reproducing code example:
```python
import numpy as np
a=np.random.rand(6,6,4)
b=np.random.rand(4,4,4)
Atemp = np.einsum(a,[6,5,11],a,[4,5,9],a,[4,6,7],b,[12,9,10],
                  a,[2,3,13],a,[1,2,10],a,[1,3,8],b,[14,8,7])
```

### Error message:

None

### Numpy/Python version information:

1.15.0 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

**Comment by seberg** [comment]
I do not think there is no reason here, the einsum problem is just gigantic, try:
```
import numpy as np
a=np.random.rand(6,6,4)
b=np.random.rand(4,4,4)
print(np.einsum_path(a,[6,5,11],a,[4,5,9],a,[4,6,7],b,[12,9,10],
                     a,[2,3,13],a,[1,2,10],a,[1,3,8],b,[14,8,7])[1])
#############
  Complete contraction:  gfl,efj,egh,mjk,cdn,bck,bdi,oih->lmno
         Naive scaling:  14
     Optimized scaling:  14
      Naive FLOP count:  2.446e+10
  Optimized FLOP count:  2.446e+10
   Theoretical speedup:  1.000
  Largest intermediate:  2.560e+02 elements
--------------------------------------------------------------------------
scaling                  current                                remaining
--------------------------------------------------------------------------
  14    oih,bdi,bck,cdn,mjk,egh,efj,gfl->lmno                               lmno->lmno
```
It doesn't optimize here (not sure if it can be), but it says pretty clearly that it needs 25 gigaflops to calculate it, so hanging for a minute sounds very much expected to me on first glance.

**Comment by lmtsui** [comment]
I am sure it can be much optimized, eg.
--------------------------------------------------------------------------
scaling                  current                                remaining
--------------------------------------------------------------------------
  5    gfl,efj -> egjl                                 oih,bdi,bck,cdn,mjk,egh,egjl->lmno
  5    egjl,egh -> hjl                               oih,bdi,bck,cdn,mjk,hjl->lmno
  5    cdn,bck -> bdkn                           oih,bdi,bdkn,mjk,hjl->lmno
  5    bdkn,bdi -> ikn                             oih,ikn,mjk,hjl->lmno
  5    mjk,hjl -> hklm                             oih,ikn,hklm->lmno
  5    oih,ikn -> hkno                             hkno,hklm->lmno
  6    hkno,hklm->lmno                         lmno->lmno

Why is einsum unable to find any optimization, even if I set optimize='greedy' or 'optimal'? Even doing a single contraction will reduce the scaling cost from 14.
