### ISSUE TITLE
Installation issue for version 1.15.1 on Python 3.6 (Windows 64-bit)

### ISSUE THREAD

**Issue by lustat** [numpy/numpy#11838]
I have problems to install numpy version 1.15.1 for Python 3.6 on 64-bit Windows. 

I tried first with "pip install" which was aborted due to mismatch of hashes. I also tried to manually download the wheel [numpy-1.15.1-cp36-none-win_amd64.whl](url) from[https://pypi.org/project/numpy/1.15.1/#files](url) but that was also automatically aborted.

Could there be something wrong with the wheel itself?
 
### Reproducing code example:
pip install numpy

### Error message:
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/fb/7d/f8b97d97809f184d90faf320fa8e2e7eac994844c5e6c57adbed1283e9e9/numpy-1.15.1-cp36-none-win_amd64.whl
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    numpy from https://files.pythonhosted.org/packages/fb/7d/f8b97d97809f184d90faf320fa8e2e7eac994844c5e6c57adbed1283e9e9/numpy-1.15.1-cp36-none-win_amd64.whl#sha256=c81a6afc1d2531a9ada50b58f8c36197f8418ef3d0611d4c1d7af93fdcda764f:
        Expected sha256 c81a6afc1d2531a9ada50b58f8c36197f8418ef3d0611d4c1d7af93fdcda764f
             Got        3585efe41f5053dc28dd4c60fa5aaddcb7c2aeab5bf934c8f595152533c1c79e

### Numpy/Python version information:
Numpy version:
1.15.1

Python version:
3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]

**Comment by charris** [comment]
Hmm, the expected hash looks correct, both generated locally and on PyPI. I would also have expected other reports if it was an upstream problem, but it may still be early. Anyway, the question is why you are getting the wrong numbers after download. It may be possible that PIP is downloading the wrong file, or maybe something local is going on, bad connection or download.

**Comment by charris** [comment]
Have you had success in the past?

**Comment by lustat** [comment]
Thanks for the reponse. OK, I see then the problem seems to be on my side.

I just got a new computer at work and the problem occurred while trying to install all the packages we use in the current project. On my previous computer I had no problems with pip install numpy.

I am a bit lost. I think I will try download python + numpy on my home laptop. And verify that it works fine then. Perhaps it could be a firewall issue.

**Comment by tylerjereddy** [comment]
Sounds like a user-level issue that we may be able to close then?

**Comment by lustat** [comment]
Closing issue, since it is of no general interest.
