### ISSUE TITLE
TestScalarPEP3118.test_scalar_match_array fails on armv7hl

### ISSUE THREAD

**Issue by QuLogic** [numpy/numpy#11832]
### Reproducing code example:

The build on [Fedora armv7hl](https://koji.fedoraproject.org/koji/taskinfo?taskID=29364138) fails in `TestScalarPEP3118.test_scalar_match_array`.

### Error message:

```
__________________ TestScalarPEP3118.test_scalar_match_array ___________________
self = <numpy.core.tests.test_scalarbuffer.TestScalarPEP3118 object at 0xac6244d0>
    def test_scalar_match_array(self):
        for scalar, _ in scalars_and_codes:
            x = scalar()
            a = np.array([], dtype=np.dtype(scalar))
            mv_x = memoryview(x)
            mv_a = memoryview(a)
>           assert_equal(mv_x.format, mv_a.format)
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: 'Zg'
E            DESIRED: '^Zg'
_          = 'Zg'
a          = array([], dtype=complex128)
mv_a       = <memory at 0xada02b28>
mv_x       = <memory at 0xadb85b70>
scalar     = <class 'numpy.complex128'>
self       = <numpy.core.tests.test_scalarbuffer.TestScalarPEP3118 object at 0xac6244d0>
x          = 0j
```

### Numpy/Python version information:

NumPy 1.15.1, Python 3.7

**Comment by eric-wieser** [comment]
I don't know how to read pytest output - is it the array or the scalar that has `.format == '^Zg'`?

**Comment by QuLogic** [comment]
The `AssertionError` output is from `assert_equal` from NumPy, not pytest... So the scalar is `'Zg'` and the array is `'^Zg'`.

**Comment by QuLogic** [comment]
So I parametrized this test by changing:
```python
    def test_scalar_match_array(self):
        for scalar, _ in scalars_and_codes:
```
into:
```python
    @pytest.mark.parametrize('scalar, code', scalars_and_codes)
    def test_scalar_match_array(self, scalar, code):
```

and all the _other_ types pass except for:
```
self = <numpy.core.tests.test_scalarbuffer.TestScalarPEP3118 object at 0xef553890>
scalar = <class 'numpy.complex128'>, code = 'Zd'

    @pytest.mark.parametrize('scalar, code', scalars_and_codes)
    def test_scalar_match_array(self, scalar, code):
        x = scalar()
        a = np.array([], dtype=np.dtype(scalar))
        mv_x = memoryview(x)
        mv_a = memoryview(a)
>       assert_equal(mv_x.format, mv_a.format)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: 'Zd'
E        DESIRED: '=Zd'

a          = array([], dtype=complex128)
code       = 'Zd'
mv_a       = <memory at 0xfe1f7850>
mv_x       = <memory at 0xfe1f69f0>
scalar     = <class 'numpy.complex128'>
self       = <numpy.core.tests.test_scalarbuffer.TestScalarPEP3118 object at 0xef553890>
x          = 0j
```

I'm not sure why it's a different one failing from above, but I did run this test in an emulator, so that could be an issue.

**Comment by eric-wieser** [comment]
It looks like our code intends `^Zg` to be the correct type of `np.clongdouble`. Unfortunately, PEP3118 is super-vague, and doesn't really clarify whether `long double` has a standard size of alignment. By my reading of the `struct` documentation, the correct marker would be `@` since everything about longdouble is native.

**Comment by eric-wieser** [comment]
If you inspect `mv_a.dtype.byteorder` and `mv_x.dtype.byteorder`, what you do you get?

**Comment by QuLogic** [comment]
This seems a bit flaky as the first time I ran it (in emulation), nothing failed, but the second time `Zg` failed. However, neither `mv_a` nor `mv_x` appear to have a `dtype` attribute?

**Comment by eric-wieser** [comment]
That was because I gave you false instructions. I meant `x.dtype.byteorder` and `a.dtype.byteorder`

**Comment by QuLogic** [comment]
Ah, they are both `'='`.

**Comment by eric-wieser** [comment]
And what about `np.array(x).dtype.byteorder`?

**Comment by QuLogic** [comment]
Also `'='`.

**Comment by eric-wieser** [comment]
`.dtype.alignment` for all three cases?

**Comment by QuLogic** [comment]
All 16.
```
(Pdb) x.dtype.byteorder, a.dtype.byteorder, np.array(x).dtype.byteorder
('=', '=', '=')
(Pdb) x.dtype.alignment, a.dtype.alignment, np.array(x).dtype.alignment
(16, 16, 16)
```

**Comment by eric-wieser** [comment]
Is this the `Zd` case or the `Zg` case?

**Comment by mattip** [comment]
On ARM floating point must be aligned, X86 deals with non-aligned floats. Perhaps there is some reallocation going on where memory is `malloc`ed non-aligned and then moved, but this only happens rarely, and somehow that (again, rarely) changes the flags? Just a guess.

**Comment by QuLogic** [comment]
That might possibly be related?
```
(Pdb) p a.ctypes.data
4156350568
(Pdb) p a.ctypes.data % a.dtype.alignment
8
```
I don't know how to check `x`, but tried with `id`?
```
(Pdb) id(x)
4153570896
(Pdb) id(x) % 16
0
```

**Comment by charris** [comment]
Does this processor have the quad precision long doubles? I don't know what the "hl" suffix in the name means.

**Comment by mattip** [comment]
The call it armv7hl, but the actual buildbot is running [`armhfp`](https://koji.fedoraproject.org/koji/taskinfo?taskID=29364138) architecture, which I assume means `arm7hf`. The difference is in the floating point simulation, [this](https://blogs.oracle.com/jtc/is-it-armhf-or-armel) is the most concise explanation I could find, there may be a better one somewhere. The `armel` alternative is no longer popular, debian dropped support a while ago so now pretty much all armv7 (which is the vast majority of the Raspberry PI-type machines out there) are `armhf`. arm8 is the new standard, but it will be a long time till arm7 goes away.

**Comment by nullr0ute** [comment]
The L in hl means little endian, the H means "hard float" which basically equates to the compiler flag -mfloat-abi=hard which means for the code to run it must have a FPU, which is a hard requirement for ARMv7, it was optional on prior versions.

**Comment by nullr0ute** [comment]
ARMv8 is also primarily 64 bit (not exclusively thought) and in the 64 bit context is referred to as aarch64

**Comment by QuLogic** [comment]
Wait, isn't `np.complex128` two 64-bit floats? Why do we need quad precision long doubles?

**Comment by eric-wieser** [comment]
That's an artefact of a bad `__name__`. On your platform, `np.clongdouble.__name__ == "complex128"`, but is not actually an alias for `np.complex128`

**Comment by eric-wieser** [comment]
There's an open pr to fix that

**Comment by QuLogic** [comment]
OK, so `numpy/config.h` has `#define HAVE_LDOUBLE_IEEE_DOUBLE_LE 1`, so I guess the answer is no?

**Comment by QuLogic** [comment]
Could #6377 have an effect here?

**Comment by mattip** [comment]
@QuLogic is this build still failing?

**Comment by QuLogic** [comment]
Fedora dropped armv7hl as a primary architecture in 37, so I can't really confirm one way or the other. Maybe the Debian packagers could confirm, but they don't seem to have commented here, so maybe they never saw it. I'll close this then.
