### ISSUE TITLE
Pure numpy scipy's generic_filter alternative

### ISSUE THREAD

**Issue by t20100** [numpy/numpy#11848]
This is a proposition to have a function in numpy that provides a faster alternative to scipy's generic_filter.

Something like `def filtergrid(data, window_size, mode='reflect', cval=0)`
 which takes an array and a window size as input and returns an array containing all windows that can then be processed with numpy functions (e.g., numpy.nanmedian, numpy.max, ....)

From what I have tested, it is faster than scipy's generic_filter: e.g., 5x5 median filter ignoring NaNs (with numpy.nanmedian) on 500x500 float image: with filtergrid it takes about 600ms while generic_filter takes about 16s.
The only drawback is potentially a higher memory consumption (especially if window_size is large).

### Reproducing code example:

Here is a minimalistic working implementation for 2d arrays:
```
import numpy
from numpy.lib import stride_tricks
def filtergrid2d(data, window_size):
    data = numpy.ascontiguousarray(data)    
    itemsize = data.itemsize
    dim0, dim1 = data.shape
    window_dim0 = min(window_size[0], dim0)
    window_dim1 = min(window_size[1], dim1)
    # Create a 4D view of the data that is convenient to apply the filter at once
    # view uses memory overrides and overflows allocated memory...
    view = stride_tricks.as_strided(
        data,
        shape=(dim0 + 1 - window_dim0, dim1, window_dim0, dim1),
        strides=(itemsize * dim1, itemsize, itemsize * dim1, itemsize),
        writeable=False)
    # Remove access to data that is not needed to apply filter
    grid = view[:, :(dim1 + 1 - window_dim1), :, :window_dim1]
    # Reshape array
    grid = grid.reshape(dim0 + 1 - window_dim0,
                        dim1 + 1 - window_dim1,
                        window_dim0 * window_dim1)
    return grid
```

And how to use it to apply a median filter while ignoring NaNs:
```
image = numpy.random.random(512**2).reshape(512, 512)
nanmedian_filtered_data = numpy.nanmedian(filtergrid2d(image, (3, 3)), axis=-1)
```

A more complete prototype (including some border padding modes) and a benchmark is available at:
https://gist.github.com/t20100/8dcb130e4f5a680c01b29d383a0ba108

Do you believe this feature is of general interest and deserves working on it further and include it into numpy?

**Comment by bashtage** [comment]
Why wouldn't scipy be the right place for a faster version of a scipy function?

**Comment by rgommers** [comment]
Performance improvements of `generic_filter` are of interest. It doesn't fit in numpy however; scipy improvements should go into scipy. Note that here is an alternative that speeds up `generic_filter` a lot via numba:
https://ilovesymposia.com/2017/03/12/scipys-new-lowlevelcallable-is-a-game-changer/
https://ilovesymposia.com/2017/03/15/prettier-lowlevelcallables-with-numba-jit-and-decorators/
You should probably benchmark against that.

**Comment by t20100** [comment]
Because it provides a similar feature but a different API and a different way to use it:
It creates an array of all windows of the input array.
It also only relies on numpy.

**Comment by bashtage** [comment]
If it provides a meaningful improvement that the SciPy community appreciates, then I think they should be willing to accept expanding the API.

SciPy relies on (in fact, requires) NumPy.

**Comment by t20100** [comment]
Thanks, I'll check if they are interested.
BTW, it's twice slower than the generic_filter + numba solution.

**Comment by rgommers** [comment]
> Thanks, I'll check if they are interested.

Yep we'll be interested for SciPy - the main discussion will be how to introduce that in a backwards-compatible way.

> BTW, it's twice slower than the generic_filter + numba solution.

That's quite good I'd say.

**Comment by eric-wieser** [comment]
I think this overlaps heavily with #10771

**Comment by t20100** [comment]
Yes it is the very same idea, good to know it's going to be available.
