### ISSUE TITLE
MAINT: _polybase __div__ method

### ISSUE THREAD

**Issue by jeffyancey** [numpy/numpy#11845]
Line 420 - 422 of `numpy/polynomial/_polybase.py` has the following method:

```
    def __div__(self, other):
        # set to __floordiv__,  /, for now.
        return self.__floordiv__(other)
```

This  implies the original author may have intended to come back and implement some other `__div__` method here. Is there a consensus on whether we would want to do that, remove the comment, or kick the can down the road?

**Comment by eric-wieser** [comment]
> this operator could be deprecated at some future time after Python 2 is dropped

It can be removed entirely - `__div__` is never called in python 3
