### ISSUE TITLE
BLD: unable to build from source over existing installation in non-standard path

### ISSUE THREAD

**Issue by francesco-ballarin** [numpy/numpy#11853]
Dear numpy developers,

I have a CentOS 7 machine with python3.6 installed from https://www.softwarecollections.org/en/scls/rhscl/rh-python36/

This installs python3 into the non-standard path
```
/opt/rh/rh-python36/root/usr
```

The collection also comes with a numpy 1.13, installed in the same path.
As I do not have root access to the machine, I would like to upgrade to the current development version building the master version of numpy from source and installing it in a user folder.

The system folder
```
/opt/rh/rh-python36/root/usr/include
```
contains python3.6m includes, but also a symbolic link
```
numpy -> /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/numpy/core/include/numpy/
```
This causes the compilation of the multiarray package (see [1] for the full command)
```
gcc .... -I/opt/rh/rh-python36/root/usr/include .... -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Inumpy/core/include ...
```
to include non-standard system-wide headers (from /opt/rh/rh-python36/root/usr/include/numpy, v 1.13) before the master ones, resulting in several occurences of
```
error: ‘NPY_ARRAY_WRITEBACKIFCOPY’ undeclared (first use in this function)
```
because NPY_ARRAY_WRITEBACKIFCOPY was defined in numpy >= 1.14.

Is there a way to configure the setup script to move the
```
-I/opt/rh/rh-python36/root/usr/include
```
after all others include flags? 

On an unrelated note, is the
```
/opt/rh/rh-python36/root/usr/include/numpy
```
symbolic link really needed for numpy to work properly?

Thanks,
best regards,
Francesco Ballarin

[1] The full command is 
```
gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv  -I/opt/rh/rh-python36/root/usr/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DSCIPY_MKL_H -DHAVE_CBLAS -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-3.6/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/rh/rh-python36/root/usr/include/python3.6m -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath  -c numpy/core/src/multiarray/compiled_base.c -o build/temp.linux-x86_64-3.6/numpy/core/src/multiarray/compiled_base.o -MMD -MF build/temp.linux-x86_64-3.6/numpy/core/src/multiarray/compiled_base.o.d
```

**Comment by rainwoodman** [comment]
Yes. Please fix this!

**Comment by rainwoodman** [comment]
One way to identify which module has pulled in the paths is to run `setup.py **config`
**
On my system, if I supply a site.cfg with a MKL section that contains junk, then it will not add /usr/lib and /usr/include to the include paths.

**Comment by pv** [comment]
The symbolic link is not needed, but for some reason linux distributions added it even though it breaks things...

**Comment by yoonghm** [comment]
Setting from `site.cfg` file (such as `include_dirs = ...`) are not used by `setup.py`.  

The rst document (https://github.com/numpy/numpy/blob/3a2ab2d39f82171c99e78634cfb1014fda06245d/doc/source/user/building.rst) mentioned that user could modify `CC` environment variables to introduce flags to C compilers.  I did that but the it replaces the existing command instead of appending the commands. 

In order to add in an include directory `/home/s/src/include/python3.8", I need to run `setup.py` as follow:

```bash
CC="gcc -pthread -I/home/s/src/include/python3.8" python3 setup.py
```

**Comment by seberg** [comment]
Not sure if that can really work. The way the python include directory is found is by asking python for it. So you should run the installer with the python you want it to link to.

**Comment by rgommers** [comment]
>  I did that but the it replaces the existing command instead of appending the commands.

Set `export NPY_DISTUTILS_APPEND_FLAGS=1` to get the append behavior. This will become the default in NumPy 1.18.0

**Comment by francesco-ballarin** [comment]
Not using that OS anymore.
