### ISSUE TITLE
Numpy bincount way too slow for very few large integers.

### ISSUE THREAD

**Issue by jmrk84** [numpy/numpy#11863]
### Reproducing code example:

```python
import numpy as np
import time
import collections
start = time.time()
np.bincount([1,1,1,1,12,30000000,30000000,30000000,300000000,300000000]).argmax()
print('numpy took {0}'.format(time.time()-start))

start = time.time()
collections.Counter([1,1,1,1,12,30000000,30000000,30000000,300000000,300000000]).most_common(1)
print('Counter took {0}'.format(time.time()-start))

```
=>numpy took 0.714s
=>Counter took 9.71 µs

bincount with argmax is several orders of magnitude slower than collections.Counter to find the most common element in a tiny array with "very large" numbers. 

### Numpy/Python version information:
1.13.3 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]

**Comment by pv** [comment]
It's probably as fast as it can be:
```
>>> z = np.bincount([1,1,1,1,12,30000000,30000000,30000000,300000000,300000000]) 
>>> z.shape
(300000001,)
```
