### ISSUE TITLE
`dtype` does not support unicode

### ISSUE THREAD

**Issue by Nikoleta-v3** [numpy/numpy#11860]
Currently the method `dtype` does not support unicode.

Using the following example I am getting an `UnicodeEncodeError `
```python
>>> import numpy as np
>>> np.dtype('ѐ')
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-2-4cd43c9a625d> in <module>()
----> 1 np.dtype('ѐ')

UnicodeEncodeError: 'ascii' codec can't encode character '\u0450' in position 0: ordinal not in range(128)
```

OS: Linux 18.04
Python: 3.6.6
numpy: '1.15.1'

**Comment by seberg** [comment]
Note that it works for fields:
```
np.dtype([('äöüѐ', 'f')])
```
and that is the only place where unicode might be useful. The error message would be better as `TypeError: data type "..." not understood` though.

**Comment by Nikoleta-v3** [comment]
I see. Thank you for your reply and for the fix :+1:

**Comment by seberg** [comment]
No fix, just a pointer for someone who wants to fix it. If you have a
bit of time, that would be awesome ;).
