### ISSUE TITLE
Unexpected behaviour numpy.fromstring

### ISSUE THREAD

**Issue by printsg** [numpy/numpy#11878]
I encounter some unexpected behaviour when using function np.fromstring and string contains whitespaces. In the following examples, I would expect to see the same output.

**Example 1:**
```python
In [1]: np.fromstring(' a', dtype=float, sep=',')
Out[1]: array([-1.])

In [2]: np.fromstring('a', dtype=float, sep=',')
Out[2]: array([], dtype=float64)
```
**Example 2:** _(Correction: strip() wasn't relevant, I just removed it)_
```python
In [3]: np.fromstring('1, a, 2',dtype=float,sep=',')
Out[3]: array([ 1., -1.])

In [4]: np.fromstring('1,a,2',dtype=float,sep=',')
Out[4]: array([ 1.])
```
Could you please clarify if this is expected behaviour or not and why if it is?

Thanks in advance.

**Comment by printsg** [comment]
> the difference is since the whitespace itself is translated to -1 for dtype=float (I don't know it this is the expected behavior).

Thanks for the reply!

> the strip() in the second example doesn't have influence since it only remove whitespaces from the beginning and the end of the string. so '1, a, 2'.strip() == '1, a, 2'.

Indeed, strip() is irrelevant in this example (it was left from copy-pasting), I corrected it in the post.

**Comment by zjpoh** [comment]
I found another example
```python
np.fromstring("1, + 1,", sep=",")  # array([ 1., -1.])
```
As explained by @aalon2, I think this is because whitespace is translated to -1 and `FLOAT_fromstring` did not finish reading the entire string. It reads until "1, + ".

One way that I can think of to handle ill-formatted string is to raise an error if the `fromstring` did not finish reading the entire string.

Probably related to #14227.

**Comment by eric-wieser** [comment]
To some extent, I wonder whether fromstring is worth deprecating - we have a few too many methods for reading text files, and by virtue of being written in C,  this one seems to be the most fragile.

**Comment by seberg** [comment]
These should be deprecated by gh-13605 @zjpoh, that still needs merging, IIRC it was ready.

**Comment by seberg** [comment]
(on the general note, I would be OK with deprecating it entirely, although it is the only place that allows hooks for new dtypes, but than, nobody has these anyway.)

**Comment by zjpoh** [comment]
@seberg Got it. Thanks~

**Comment by mattip** [comment]
Closing, these now raise a `DeprecationWarning`
