### ISSUE TITLE
BENCH: split out slow setups from benchmarks

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#11875]
PR #11874 showed a path to improving benchmark running time by avoiding running slow class setup when not needed. It is suggested there that there may be more candidates for this kind of refactoring. This might be an easy issue for beginners. Benchmarks can be run with `python runtests.py --bench`

**Comment by pv** [comment]
One can also do:
.
cd benchmarks
ipython
In [1]: import benchmarks.bench_core as b
In [2]: %timeit b.Core().setup()
.
and so on for all benchmarks (note: easy to write a script that does this for all of them). If a setup method is slower than, say, 100ms, and used by multiple benchmarks, splitting it up may speed up runtests.py --bench. Be sure to measure that changes made actually speed this up.

**Comment by pv** [comment]
Script: https://gist.github.com/pv/9f51381ec8a488c34920749d0f00c43e
```
Slow setup routines
benchmarks.bench_core.CountNonzero:CountNonzero.setup(1,1000000,<class 'object'>): 0.03455194600064715 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(1,1000000,<class 'str'>): 0.6196904629996425 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(2,1000000,<class 'bool'>): 0.04192689400042582 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(2,1000000,<class 'int'>): 0.04525058800027182 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(2,1000000,<class 'object'>): 0.06719392699960736 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(2,1000000,<class 'str'>): 1.1944845250000071 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(3,1000000,<class 'bool'>): 0.05948299999909068 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(3,1000000,<class 'int'>): 0.06613554099931207 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(3,1000000,<class 'object'>): 0.09786297800019383 * 3
benchmarks.bench_core.CountNonzero:CountNonzero.setup(3,1000000,<class 'str'>): 1.836624182000378 * 3
benchmarks.bench_function_base.Sort:Sort.setup: 0.4403215519996593 * 8
benchmarks.bench_indexing.Indexing:Indexing.setup('indexes_','I',''): 0.12477519099957135 * 1
benchmarks.bench_io.LoadtxtCSVSkipRows:LoadtxtCSVSkipRows.setup(0): 0.4922110050010815 * 1
benchmarks.bench_io.LoadtxtCSVSkipRows:LoadtxtCSVSkipRows.setup(10000): 0.4833040470002743 * 1
benchmarks.bench_io.LoadtxtCSVSkipRows:LoadtxtCSVSkipRows.setup(500): 0.47398070500094036 * 1
benchmarks.bench_shape_base.Block3D:Block3D.setup(100): 0.7387005040000076 * 1
```

**Comment by MichaelSaah** [comment]
Thanks for the script, I tried to time these today and I ran into the problem of setup()'s taking additional arguments. Out of the setup()'s that didn't take additional arguments, Sort was the only "slow" method I identified. Clearly missed a few.

I'd be open to refactoring these, but first I need to look more into ASV to see how they interface.

**Comment by MichaelSaah** [comment]
Went through the slow setups, here are my findings:

- Brought Sort setups down from 8*0.430 = 3.44 sec to 7*0.001+0.430 = 0.437 sec by splitting into Sort and WorstSort
- Don't see a way to speed up CountNonzero without caching
- Indexing is slow for just one param set, don't see a way to speed up via reorganizing
- LoadtxtCSVSkipRows is slow for all param sets, don't see a way to speed up via reorganizing

**Comment by rgommers** [comment]
This seems to have been addressed, closing. Thanks @MichaelSaah, all
