### ISSUE TITLE
f2py and OpenMP linking

### ISSUE THREAD

**Issue by wtjones1** [numpy/numpy#11908]
When building an extension module with f2py from numpy as late as 1.15.1, the link command fails to include the OpenMP compiler flag (gfortran: -fopenmp, ifort: -qopenmp, etc.).  Therefore, the extension module is not linked against the required Offloading and Multi Processing Runtime Library and possibly other dependent libraries which vary by compiler.

While there may be another method of specifying the appropriate linker option (which I would be interested in knowing), it would appear that this option should be passed to the linker as part of the linker_so options or equivalent.

Note that, at least with gfortran and ifort, a compiler command line option instructs the linker to include the Offloading and Multi Processing Runtime Library (which is dependent on the compiler used).  Therefore, adding the library(s) in a generic way that supports multiple Fortran compilers in a build environment prevents the explicit listing of these libraries when invoking f2py.

**Comment by charris** [comment]
We don't currently have any maintainers dedicated to f2py. If you or someone else would like to work on this we would welcome a PR.

**Comment by Koushikphy** [comment]
I usually do this for gfortran

**Comment by carlkl** [comment]
Isn't this solved since numpy-1.16.0 and defining: `export NPY_DISTUTILS_APPEND_FLAGS=1`?

See also: https://stackoverflow.com/questions/54201961/how-to-tell-f2py-module-to-look-in-current-directory-for-shared-object-dependenc

**Comment by HaoZeke** [comment]
> Isn't this solved since numpy-1.16.0 and defining: `export NPY_DISTUTILS_APPEND_FLAGS=1`?
> 
> See also: https://stackoverflow.com/questions/54201961/how-to-tell-f2py-module-to-look-in-current-directory-for-shared-object-dependenc

Yup it does look like it, would be fantastic to have a docs PR close this :)

**Comment by HaoZeke** [comment]
Should be fixed (replaced / deprecated) by https://github.com/numpy/numpy/pull/24532.
