### ISSUE TITLE
License files missing in Releases

### ISSUE THREAD

**Issue by giuliobenetti** [numpy/numpy#11927]
In Release https://github.com/numpy/numpy/releases/download/v1.15.1/numpy-1.15.1.tar.gz
license for sub libraries are not present, they are only listed on the base LICENSE.txt file.
Is it possible to add them in the next release?
Thanks

**Comment by charris** [comment]
What exactly would you like to see?

**Comment by giuliobenetti** [comment]
Hello,

these files are missing:
numpy/linalg/lapack_lite/LICENSE.txt
tools/npy_tempita/license.txt

**Comment by rgommers** [comment]
Thanks for the report @giuliobenetti, and sorry it took a while to fix. Should be addressed by gh-13086
