### ISSUE TITLE
Finish deprecation cycle for comparison to NaT

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#11945]
xref https://github.com/numpy/numpy/issues/7019

We started this deprecation cycle with NumPy 1.11 back in March, 2016. At the time, it was suggested we would change the behavior for NumPy 1.13, but that's passed by now.

Let's try not to forget it for the 1.16 release? :)

**Comment by charris** [comment]
Want to make a PR?

**Comment by shoyer** [comment]
OK, see https://github.com/numpy/numpy/pull/11948
