### ISSUE TITLE
Inconsistent behaviour when casting "ndarray" to int and float between Python 2.7 and Python 3.6.

### ISSUE THREAD

**Issue by KelSolaar** [numpy/numpy#11956]
### Reproducing code example:

Hi,

I'm running into some inconsistencies when casting a `ndarray` to int and float between Python 2.7 and Python 3.6. Basically, a single element 1D array upon being casted to int or float ends up as either a `np.float64` or `np.int64` which is expected except when casting the array to int in Python 3.6 where it stays as a `ndarray`. I tried with Numpy 1.14.3 and 1.15.1 and both versions exhibit the same behaviour:

*Python 3.6.4*

```python
# Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01)
# [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
# Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.15.1'
>>> np.float_(np.array([1]))
1.0
>>> type(np.float_(np.array([1])))
<class 'numpy.float64'>
>>> np.int_(np.array([1]))
array([1])
>>> type(np.int_(np.array([1])))
<class 'numpy.ndarray'>
```

*Python 2.7.14*

```python
# Python 2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:18:54)
# [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
# Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.15.1'
>>> np.float_(np.array([1]))
1.0
>>> type(np.float_(np.array([1])))
<type 'numpy.float64'>
>>> np.int_(np.array([1]))
1
>>> type(np.int_(np.array([1])))
<type 'numpy.int64'>
```

Using Python `int` built-in works as expected:

```python
>>> int(np.array([1]))
1
>>> type(int(np.array([1])))
<class 'int'>
```

### Numpy/Python version information:

```
1.15.1 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

```
('1.15.1', '2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:18:54) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]')
```

**Comment by eric-wieser** [comment]
`np.float_` and `np.complex_` (and `np.int_` on python 2) are special, because they (attempt to) subclass the builtin types of the same names.

I don't view this as a particularly good thing, not least because the CPython C api does not support multiple inheritance, yet we hack it in anyway

**Comment by charris** [comment]
> I don't view this subclassing as a particularly good thing

@eric-wieser It has always been troublesome, it was great that the int problem went away with Python 3. If a good case could be made that changing that didn't break things downstream we should probably do so.

**Comment by seberg** [comment]
This is fixed, it now returns arrays when it should.
