### ISSUE TITLE
TST: Valgrind testing difficult/broken due to float128 test gathering failing

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#11963]
Once in a while, I run the numpy test suit with valgrind, right now that does not quite work. This seems to be due to warnings that are turned to errors in the test (skipping) decorators that test `np.finfo(np.float128)` or similar.
Would be nice to fix in the longer run, I might just end up looking at it at some point. There are probably a few possibilities:
 1. Make sure the decorator does not raise the warning.
 2. Make sure the warnings are not turned to error during the test gathering part.
 3. See if it is not possible to tell pytest to report an error during test-gathering as a failed test or so instead of not running the whole test suit.

These tests (just like xerrbla or so) always failed on valgrind. Maybe there already is a simple option to achieve any of these, but I did not find it yet.

Output:
```
______________ ERROR collecting build/testenv/lib/python3.7/site-packages/numpy/core/tests/test_umath.py _______________
numpy/core/tests/test_umath.py:2455: in <module>
    class TestComplexFunctions(object):
numpy/core/tests/test_umath.py:2639: in TestComplexFunctions
    @pytest.mark.skipif(is_longdouble_finfo_bogus(),
numpy/core/tests/test_umath.py:2451: in is_longdouble_finfo_bogus
    info = np.finfo(np.longcomplex)
numpy/core/getlimits.py:404: in __new__
    obj = object.__new__(cls)._init(dtype)
numpy/core/getlimits.py:411: in _init
    machar = _get_machar(dtype)
numpy/core/getlimits.py:290: in _get_machar
    UserWarning, stacklevel=2)
E   UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbfY\x0e\x00\x00\x00\x00' for <class 'numpy.float128'> does not match any known type: falling back to type probe function
```

**Comment by pv** [comment]
`... -- -W ignore` ?

**Comment by pv** [comment]
The regexp probably needs to match the whole message?
Anyway, you can also add pytest flags on command line, also with runtests.py...

**Comment by seberg** [comment]
Thanks, that pytest.ini thing was the thing I was missing/messing up. I can add the line to pytest.ini and it runs fine.

**Comment by charris** [comment]
Yeah, that behavior was noted when the pytest 3.8 problem was being tracked down. See https://github.com/pytest-dev/pytest/pull/3947.

**Comment by seberg** [comment]
Thanks, could be nice if it was not necessary to edit the file/mess with it, but will close this for now until it annoys me again :). Tests ran well with valgrind (one warning, but probably just something to do with pythons string handling).

**Comment by charris** [comment]
I think the fix is scheduled for pytest 3.9.

**Comment by mattip** [comment]
@seberg, if you have a valgrind running, could you look at issue #11951 "Memory leak when using astype('unicode')"?

**Comment by seberg** [comment]
Will have a quick look, but nowadays there really is almost nothing to it, since using `PYTHONMALLOC=malloc` is basically all magic you need (except maybe a debug python/numpy to get better output, unless I am missing some more awesome stuff).
