### ISSUE TITLE
BUG: errors and PyArray_AdaptFlexibleDType

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#11969]
`PyArray_AdaptFlexibleDType` does not return an error status. It seems the third argument, `flex_type` is set to `NULL` if an error occurs, but the value is not checked after a call to the function. Apparently our test suite does not trigger errors in the function. We should
- return a value from the function to indicate an error occurred
- check the value at all calls to the function
- devise tests that make the function fail, preferably in a way that requires the checks in order to prevent incorrect results or crashes
- make sure we exit the function on errors, for instance from the call to `PyArray_GetArrayParamsFromObject`.

**Comment by eric-wieser** [comment]
Seems like `PyArray_AdaptFlexibleDType` should just return the adapted dtype, rather than using an out argument
