### ISSUE TITLE
numpy.ndarray cause segfault after unpickling on OSX

### ISSUE THREAD

**Issue by Sytten** [numpy/numpy#11972]
It seems like `numpy.ndarray` unpickled causes a segmentation fault when using a `.dot` or similar functions on it, but does work when copying the data to a new `numpy.ndarray` using `new = numpy.asarray(old.tolist())`.  I saw this had been an issue a long time ago: https://github.com/numpy/numpy/issues/1149 and I wonder if it might be the same problem.

### Reproducing code example:

I will post it shortly.

### Error message:

I have to check how to do this.

### Numpy/Python version information:

1.14.1 3.6.5 (default, Jun 17 2018, 12:13:06)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

**Comment by seberg** [comment]
You don't need to worry about the "Error message" (although if you can run things through a debugger/valgrind that would be cool). If we have a reproducing example that would be good, although if it really has to do with `np.dot` and is limited to OSX it might be a bit trickier.

**Comment by Sytten** [comment]
It will be tricky, it runs fine on our prod server on linux so my best bet is that its a OSX thing. The code spawns on multiple services, so I have to write another test. I will keep you posted as fast as possible.

**Comment by sturlamolden** [comment]
No segfaults here... NumPy 1.15.1 on High Sierra:

```
sturla$ python
Python 3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import pickle
>>> a = np.array([1,2,3,4])
>>> b = pickle.loads(pickle.dumps(a))
>>> a
array([1, 2, 3, 4])
>>> b
array([1, 2, 3, 4])
>>> b.dot(b)
30
>>> a.dot(a)
30
```

**Comment by Sytten** [comment]
I was passing around the objects in a mongo database using GridFS. I dont expect a straight dump + load to be problematic. Still you should be able to dump the data to file, restart the interpreter, load the data and see if it works...

**Comment by seberg** [comment]
Closing, as a years old issue where we would need more information from the original report.  Plus, chances are that there was a bug that was fixed in the meantime.
A new issue is of course nice if there is still an issue.
