### ISSUE TITLE
gfortran 4.7 does not support '-mlong-double-64' on Win32

### ISSUE THREAD

**Issue by thoduv** [numpy/numpy#11988]
Hello,

I ran into a problem when using the numpy 1.15.1 distutils to build an extension that includes FORTRAN code.

I run Windows 64 bits, and while I had no problem compiling with MSVC+gfortran 5.3 for Python 3.5 64 bits, I got the following error when compiling with gfortran 4.7 for Python 2.7 32bits (installed through Anaconda 2.7, 32 bits):

`gfortran.exe: error: unrecognized command line option '-mlong-double-64'`

Removing the option "-mlong-double-64" in the _link_wrapper_lib method of distutils/fcompiler/gnu.py effectively solved the problem.

I could not check whether it is related to the gfortran version, or the different architecture. Anyway, maybe the option should be only added conditionnally.

**Comment by carlkl** [comment]
As this issue isn't relevant for: 
- msys2-python-numpy: `-mlong-double-64` isn't used for this use case
- Windows CPython: numpy won't be built with the GCC toolchain (in contrast to scipy) even for change to meson in future 
I propose to close this issue.

**Comment by seberg** [comment]
Thanks for the note! It is also very old so closing.

Please open a new issue if you run into the same (or similar) problem.
