### ISSUE TITLE
Codecov is comment-spamming PRs

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#11984]

**Comment by tylerjereddy** [comment]
I've noticed. There are a few recent issues on their [status page](https://status.codecov.io/), but nothing that is an exact match. I tried emailing their support address because codecov has [completely stopped working](https://github.com/scipy/scipy/pull/9186#issuecomment-419225782)  over at SciPy, but it has been 12 days without a response so I'm not optimistic about hearing back from them in general.

**Comment by rgommers** [comment]
I'd be fine with removing it. Codecov is terrible, both in its intermittent spamming (this is definitely not the first time) and in its actual stats/diffs.

**Comment by tylerjereddy** [comment]
> I'd be fine with removing it. 

Any suggestions for viable alternatives? I do find it helpful to use some of the stats, esp. to see if I need to explore patch codepaths with new unit tests, but I agree there are lots of bugs-- signal : noise is bad on the service even when not spamming.

**Comment by tylerjereddy** [comment]
In the NumPy codecov account I do see [a link to their github app](https://github.com/integration/codecov), which we aren't currently using:

> Integrate with Codecov through the GitHub Integration to strengthen Codecov's integration with your team. This will replace the the bot account and post pull request comments on-behalf-of Codecov.

Switching to that approach before a hard removal might be worth a shot, to verify if it is more responsive to config specification to avoid comments.

Other thought -- block the codecov bot from posting to the repo as if it were an annoying user as a sort of band-aid. Not sure if that modularity of control exists though.

**Comment by rgommers** [comment]
That's possible. Anyone opposed to blocking the `codecov-io` user?

Also, the Settings page shows that a red exclamation mark for the `homu` bot. It seems disfunctional and I never liked it in the first place. Okay to delete it?

**Comment by charris** [comment]
> Okay to delete it?

Fine with me.

**Comment by rgommers** [comment]
Okay Homu is dead apparently and homu.io domain was expired/expiring: https://bors.tech/homu-io/. Deleted.

**Comment by eric-wieser** [comment]
I thought homu was quite handy for pinging crs when they had new conflicts, but the point is moot now the bot is dead.

Blocking codecov bot sounds like a nice solution - all we wanted was the ci anyway.

**Comment by eric-wieser** [comment]
Looks like I don't have access to that page, not that I really need it

**Comment by njsmith** [comment]
[Supposedly](https://docs.codecov.io/docs/pull-request-comments#section-disable-comment) you can also add `comment: off` to `.codecov.yml`, though who knows if that works right now when they have this bug in their commenting system.

**Comment by tylerjereddy** [comment]
> Supposedly you can also add `comment: off` to `.codecov.yml`

We already have that setting -- @pv requested that pretty early on when we decided to add coverage; for some reason it apparently stopped working.

**Comment by rgommers** [comment]
> Looks like I don't have access to that page, not that I really need it

Had a look at this - it's repo owner only apparently (which makes sense). There's only 5 at the moment: Travis, Chuck, Nathaniel, Pauli and me. We could change add/remove as needed, goal is to keep that group small though since it also allows things like deleting the whole repo.

**Comment by mattip** [comment]
Has the spam decreased sufficiently to close this?
