### ISSUE TITLE
MAINT: exec_command() cleanup

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#11980]
With the impending demise of `exec_command()` related to #11824, there will soon only be unit tests that call this function in our code base even though it will no longer be used.

The unit tests are in `numpy/distutils/tests/test_exec_command.py` -- will we want to remove the tests that specifically call `exec_command()`?  I assume we won't want to unit test the standard library stuff we've replaced `exec_command()` with.

Also, do we need a deprecation marker of some sort on `exec_command()` before removing it? I'm not sure how public-facing / used it is; maybe I need to check that deprecation policy NEP again!

**Comment by charris** [comment]
Hmm, I don't see it in scipy or the `__all__` lists. It might make sense to deprecate it just to be safe, but it is probably not needed. @rgommers Thoughts?

**Comment by tylerjereddy** [comment]
ping

This came up again in https://github.com/numpy/numpy/pull/12849

The associated unit tests may be a bit more fragile now--we could remove the unit tests separately from the hard removal of the function itself I suppose.

**Comment by charris** [comment]
I think the best way to go is deprecate `exec_command` while keeping the tests, and then remove both at the same time. The tests will need fixing to ignore the deprecation warning.
