### ISSUE TITLE
int64 to float32 casting issues

### ISSUE THREAD

**Issue by miclegr** [numpy/numpy#12010]
Casting int64s to float32s produces strange results for certain ints.

### Reproducing code example:

```python
import numpy as np
np.array([89461577,89461578,89461579,89461580],dtype=np.int64).astype(np.float32)
```

### Result:
```python
array([89461576., 89461576., 89461576., 89461580.], dtype=float32)
```

### Numpy/Python version information:

Numpy 1.14.5 
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:55) [MSC v.1900 64 bit (AMD64)]

**Comment by seberg** [comment]
This is correct (although it could warn about an unsafe cast, but astype specifically allows unsafe casts, and numpy is a bit lazy about acting as if int32 -> float32 is safe).

Anyway, please have a look for example at: https://en.wikipedia.org/wiki/Single-precision_floating-point_format#Precision_limits_on_integer_values
and most importantly, avoid float32 unless you are pretty sure that they are sufficient for what you are doing. For many things they are great, but for a lot of things they just lack the precision.

**Comment by mattip** [comment]
```
>>> a =  np.array([89461577,89461578,89461579,89461580],dtype=np.int64)
>>> a.astype(np.float32, casting='safe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array from dtype('int64') to dtype('float32') \
according to the rule 'safe'
```
