### ISSUE TITLE
cannot install numpy==1.14 specifically

### ISSUE THREAD

**Issue by Karrenbelt** [numpy/numpy#12026]
### Reproducing code example:

```bash
pip3.7 install numpy==1.14
```
on the contrary, installing the current latest version, 1.15.2 works fine

```bash
pip3.7 install numpy==1.15.2 
```

I need numpy==1.14 as a dependency to pip install abcpy 

### Error message:

15 errors generated.
    error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.macosx-10.13-x86_64-3.7/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.macosx-10.13-x86_64-3.7/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/tq/yhb6dsx952l1wcmx5qnxp0940000gn/T/pip-install-z318x9au/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/tq/yhb6dsx952l1wcmx5qnxp0940000gn/T/pip-record-zpcqluaj/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/tq/yhb6dsx952l1wcmx5qnxp0940000gn/T/pip-install-z318x9au/numpy/

### Numpy/Python version information:
python: 3.7.0
issue with numpy version: 1.14

**Comment by charris** [comment]
Why is it compiling?

**Comment by charris** [comment]
pip should be installing a wheel, not compiling, but apparently that is what happens if you do not supply the micro version. Try `pip3.7 install numpy==1.14.6`

**Comment by rgommers** [comment]
1.14 means 1.14.0 to pip. Always use a full 3-digit version number. 1.14.0 doesn't have Python 3.7 wheels, 1.14.6 does. Closing, you'll get a wheel with `pip3.7 install numpy==1.14.6`
