### ISSUE TITLE
numpy.maximum since 1.15 raises RuntimeWarning when encountering a NaN even though the docs say it should propagate NaNs

### ISSUE THREAD

**Issue by tudorprodan** [numpy/numpy#12038]
`numpy.maximum` now raises a RuntimeWarning when encountering a NaN, but the documentation says it propagates NaNs and even goes to the trouble of saying exactly how they are propagated, which makes it seem like it shouldn't give a warning.

### Reproducing code example:
```python
In [1]: import numpy as np

In [2]: x = np.array([1, 2, np.nan], dtype=float)

In [3]: np.maximum(x, x)
/home/tudor/anaconda3/bin/ipython:1: RuntimeWarning: invalid value encountered in maximum
  #!/home/tudor/anaconda3/bin/python
Out[3]: array([ 1.,  2., nan])

```

### Numpy/Python version information:

```python
In [6]: import sys, numpy; print(numpy.__version__, sys.version)
1.15.1 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51)
[GCC 7.2.0]
```

**Comment by charris** [comment]
Note that we may still want to raise a warning.

**Comment by charris** [comment]
Might open for discussion on the mailing list.

**Comment by charris** [comment]
If we do decide the raising a warning is the right thing, we should document that. I'm tending in that direction as the appearance of NaNs could indicate an error or that nanmax should be used.

**Comment by WarrenWeckesser** [comment]
I added a "thumbs up" emoji to the bug report, but it occurs to me that the meaning of doing that is a bit vague, so here's the explicit comment:  I agree that `maximum` should not generate a warning when given a `nan`. If the code is designed and documented to handle `nan`, then `nan` is not an "invalid value".  The warning is wrong in that sense.

> [...] nanmax should be used.

I don't think there is `nan`-function for `maximum`.

**Comment by WarrenWeckesser** [comment]
Raising a warning is also inconsistent.  Functions such as `numpy.add` and `numpy.arctan2` do not raise a warning:

```
In [21]: np.__version__
Out[21]: '1.15.1'

In [22]: np.add(1.0, np.nan)
Out[22]: nan

In [23]: np.arctan2(1.0, np.nan)
Out[23]: nan
```

**Comment by tudorprodan** [comment]
> If we do decide the raising a warning is the right thing, we should document that. I'm tending in that direction as the appearance of NaNs could indicate an error or that nanmax should be used.

nanmax does something different, it ignores nans, whereas maximum propagates nans.

```python
In [1]: import numpy as np

In [2]: x = np.arange(3, dtype=float)

In [3]: x[2] = np.nan

In [4]: x
Out[4]: array([ 0.,  1., nan])

In [5]: np.nanmax(np.vstack([x, x[::-1]]), axis=0)
Out[5]: array([0., 1., 0.])

In [6]: np.maximum(x, x[::-1])
/home/tudor/anaconda3/bin/ipython:1: RuntimeWarning: invalid value encountered in maximum
  #!/home/tudor/anaconda3/bin/python
Out[6]: array([nan,  1., nan])
```

**Comment by eric-wieser** [comment]
> I don't think there is nan-function for maximum.

`fmax` is the function you're after

**Comment by eric-wieser** [comment]
Some discussion about whether `maximum` should warn here: https://github.com/numpy/numpy/pull/9020#issuecomment-298135555

**Comment by WarrenWeckesser** [comment]
> Some discussion about whether maximum should warn here: #9020 (comment)

In that discussion, @juliantaylor said

> maximum/minimum should warn, nan's may lead to unexpected results.

The `maximum` and `minimum` docstrings explain how `nan` is handled, so I don't know what "unexpected results" refers to.  If the idea is that typically, a `nan` indicates that a calculation went wrong somewhere,  and the user should be warned that they passed a `nan` to `maximum`, then the same argument applies to *all* numpy functions (e.g. `add`, `arctan2`, `sin`, etc.).  But most functions don't warn with `nan`.  What is special about `maximum` and `minimum` that they should raise a warning where most other numpy functions do not?

**Comment by tudorprodan** [comment]
What needs to happen for this to be classified as either a) feature that works as expected or b) regression? What's the process?

I'm asking because I am using code that's throwing a lot of warnings because of this behaviour change. If it's a feature, than I need to work around it, if it's a regression then I just need to temporarily silence that one warning.

**Comment by charris** [comment]
My own feeling on this as that we should do what is most useful to the users, but I don't know what that is :) I find the arguments for not warning a bit stronger than those in favor, although I'd like to know more about the use case in which the warning is a problem. It would be good to have more opinions, maybe a posting on the mailing list would help. Also @pv, @rgommers Thoughts?

**Comment by tudorprodan** [comment]
> although I'd like to know more about the use case in which the warning is a problem

The warning is a problem for me because I try to keep my stuff tidy with no warnings.
Also, if you share code with someone else, it's preferable for the other person if the code doesn't raise warnings.

The function has NaN handling very well documented: it explicitly says what happens when NaNs are found and the behaviour is well defined: NaNs are propagated using a well defined rule.
So it's my personal opinion that this is a regression and should be fixed unless the intent is to change the function behaviour. I think if it were the intent to change it in that way, someone would have said so. 

But I'm not sure at what point and who decides on that.

**Comment by WarrenWeckesser** [comment]
Is anyone currently arguing for keeping the warnings?

**Comment by charris** [comment]
NumPy 1.15.3 is coming up, it would be good to settle this...

**Comment by mattip** [comment]
Also maybe related to #8945 where warnings are possibly emitted when comparing (sign, abs, gt, lt ...)

**Comment by wholmgren** [comment]
I will chime in as a strong proponent of *not* emitting these warnings. The reasoning is carefully explained by @WarrenWeckesser and @tudorprodan.

I arrived here because the pvlib python library uses `maximum` in a way that expects valid `nan` inputs and desires that they be passed along in the output. We'd like to avoid writing work around functions like this one https://github.com/pvlib/pvlib-python/pull/610

**Comment by charris** [comment]
I think this is trending strongly in the direction of no warnings.

**Comment by eric-wieser** [comment]
Taking a step back here - as far as I'm aware _all_ of the floating point ufuncs have well-defined behavior on nans, as specified by ieee754.

So should we just change the default to ignore this class of fperr, rather than choosing not to emit it?
