### ISSUE TITLE
Memory leak when slicing derived classes from Numpy

### ISSUE THREAD

**Issue by ehpor** [numpy/numpy#12037]
Memory leak when slicing derived classes from Numpy. Slicing without using the derived classes produces no memory leak. The size of the memory leak is dependent on the size of the sliced array (post-slicing). The memory leak is not visible in the objects managed by Python: that is, the number of objects managed by Python doesn't increase with more iterations in the for loop below.

The code example follows closely the current documentation on derived classes, more specifically [here](https://docs.scipy.org/doc/numpy/user/basics.subclassing.html#slightly-more-realistic-example-attribute-added-to-existing-array).

### Reproducing code example:

```python
import numpy as np
import time

class Field(np.ndarray):
    def __new__(cls, arr):
        obj = np.asarray(arr).view(cls)
        return obj
	
    def __array_finalize__(self, obj):
        if obj is None:
            return

N = 256*256

B = np.zeros(N)
B[:N/2] = 1

# Memory leak depending on which of the following lines is executed
A = Field(np.random.rand(N))
#A = np.random.rand(N)

for i in np.arange(10000):
    if i % 100 == 0:
        print(i)
        time.sleep(0.01)
	
    # Memory leak in following line
    res = A[B>0]
```

### Error message:

No error message is produced.

### Numpy/Python version information:

Problem occurs for both Python 3.6.6 and Python 2.7.15. I didn't check other version.
Problem is not present in Numpy 1.14.5 but is present in both Numpy 1.15.1 and 1.15.2.

**Comment by seberg** [comment]
Bug is probably there since forever (even my messing with indexing). I think the DECREF: https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/mapping.c#L1131 just has to be done unconditionally (i.e. the function does not actually steal a reference to base).

**Comment by seberg** [comment]
Hmmm, or not, seems the code varied a little, so could be a more recent regression. Not that it matters much when or who put it there :).

**Comment by yymao** [comment]
I can confirm this bug in 1.15.2. Here's some potentially related info:
- This is related to https://github.com/numpy/numpy/issues/11983, which affected numpy 1.15.0 and 1.15.1. 
- A fix was made in 1.15.2 and master (https://github.com/numpy/numpy/pull/11989 https://github.com/numpy/numpy/pull/11992), but the fix does not fully resolve the memory leak issue. 

(cc @mhvk @eric-wieser)

**Comment by eric-wieser** [comment]
@seberg: "easy" is perhaps optimistic for a refcount leak ;)

**Comment by eric-wieser** [comment]
Well-placed optimism: https://github.com/numpy/numpy/pull/11989/files#r220800032

**Comment by seberg** [comment]
Hehehe, easy... For those that understand immediately what I meant with "doesn't steal the reference" ;).

**Comment by seberg** [comment]
@charris, added the backport label just to be sure. I would be happy if someone fixes it. Won't do it now because I am swamped (even if it should be fast), but if no one beats me, just ping me again a bit before branching, should be free by then.

**Comment by charris** [comment]
See #12127.
