### ISSUE TITLE
TST: Azure testing with NumPy

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#12036]
This was discussed a bit on the mailing list--I've done a little testing on my fork of NumPy.

A [sample PR](https://github.com/tylerjereddy/numpy/pull/1) shows the github integration in action for a MacOS job. The `numpy_azure` branch contains the `.yml` file, and the PR is opened against that.

MacOS tests don't all pass there yet. Looks like it took 3 minutes, 17 seconds for the full run.

**Comment by rgommers** [comment]
+10 for Azure Pipelines. Discussed it with quite a few people, and Steve Dower gave an overview of features, MS's motivations, and what's coming next. Everyone was very positive and enthusiastic about it.

**Comment by tylerjereddy** [comment]
> I'd really like to see windows testing

I added Windows / Python 3.6 full tests to matrix; 1 error and a few failures; worse if I try more than 1 core for testing; tempfile stuff and a few other things. I'll try to sort them out.

**Comment by tylerjereddy** [comment]
`init_dgelsd failed init` issue on the macOS builds is similar to a [recent bug report](https://github.com/Homebrew/homebrew-core/issues/31404) for clang builds with homebrew and recent NumPy, which seems to be circumvented by using a recent version of gcc

**Comment by tylerjereddy** [comment]
I've been able to reduce test skips on the azure mac os image now:
`26 failed, 5552 passed, 25 skipped, 12 xfailed, 1 xpassed`

But the failures look real and are also [reported for macos 10.13 recently for macports](https://trac.macports.org/ticket/56954).

**Comment by tylerjereddy** [comment]
One user [tracked down the source line in Numpy](https://github.com/numpy/numpy/blob/master/numpy/linalg/umath_linalg.c.src#L2561) -- I'll see if I can debug that if nobody beats me to it; there's a comment mentioning `Fix a bug in lapack 3.0.0` just above the low-level error block -- I bet it is because of something there -- we custom modify something that is fed to `malloc` because of an alleged lapack bug, but maybe that bug is no longer in play with some recent mac os images / LAPACK library settings, etc.

**Comment by eric-wieser** [comment]
What version of Lapack is being tested there?

That comment was introduced by me in 92f1d1221c7d41609d853f7ce0ca666f341ff607. I think there are all sorts of bugs in the lapack workspace calculations, which is what motivated my upgrade of lapack_lite a while back.

I think the situation now is that OSX ships with a more broken lapack than the one bundled with numpy.

**Comment by charris** [comment]
Can we make the Mac build with the NumPy fallback code? I know we can on Linux, but have never tried on Mac.

**Comment by tylerjereddy** [comment]
I'll have to check re: lapack version -- the show_config style commands don't always make this stuff obvious to me. What is meant by "fallback code?"

 Are there any low-level hooks that can be used in C source files to probe LAPACK version during pre-processing / guard the logic for handling the bugs?

I see online that `ilaver()`(http://www.netlib.org/lapack/explore-html/d5/d42/ilaver_8f_ace0eea943fa875e927d0b8b6614c9763.html) function will return lapack version, but it is apparently never used in our source. Looks like `scipy` exposes it in `scipy.linalg.lapack.ilaver`

**Comment by charris** [comment]
IIRC, on the Mac use of accelerate/veclib is hardwired in, see `numpy/distutils/system_info.py`. On other platforms one can do
```
BLAS=None LAPACK=None python setup.py build
```
which disables linking to the external libraries and uses unoptimized numpy code instead.

**Comment by pv** [comment]
Support for also ACCELERATE=None was iirc added recently.

**Comment by tylerjereddy** [comment]
Yeah, the broader setup effort has been completed; some more challenging refinements may remain for i.e., MacOS `f2py` and test thread safety, etc.
