### ISSUE TITLE
DOC: search does not work on online docs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#12044]
The docs have a quick search window. It seems the search feature is broken on www.numpy.org/devdocs/search.html but works on https://docs.scipy.org/doc/numpy/search.html. It was suggested on the mailing list this may be due to sphinx 1.8.0, as matplotlib pinned sphinx matplotlib/matplotlib#12183 to `!=1.8.0` and sphinx is aware of the issue sphinx-doc/sphinx#5460 a fix is scheduled for sphinx 1.8.1

**Comment by mattip** [comment]
Hmm. Circle CI doc builds are using sphinx 1.8.1, but the search still does not work. It seems there was a change in the javascript used by our theme(?) and we need to do something like the fix for rtfd/sphinx_rtd_theme#672?

**Comment by timhoffm** [comment]
Fixed by #12216.
