### ISSUE TITLE
Improve printing of multidimensional arrays

### ISSUE THREAD

**Issue by JackCaster** [numpy/numpy#12059]
I think the current printing of multidimensional arrays is not human friendly and misleading.
For example a 4x3x2 array 
```python
import numpy as np
np.random.rand(4, 3, 2)
``` 
is printed as:
```python
[[[0.4754527  0.93054666]
  [0.72447069 0.29154046]
  [0.83630351 0.80910477]]

 [[0.81053942 0.44297571]
  [0.77322926 0.66898573]
  [0.61047337 0.32897926]]

 [[0.75482612 0.97126855]
  [0.14926725 0.60235927]
  [0.42149006 0.94177078]]

 [[0.30307318 0.46313982]
  [0.66408541 0.3904654 ]
  [0.3638378  0.17299474]]]
```
which I think is counter intuitive, and _misleading_. In fact, if I were to guess the shape of the array based only on the printed output I would say that the array is 3x2x4. What is the benefit of such representation? When would that be helpful?

I think the way R/Julia/Matlab (i.e., basically all the other workhorses of numerical computing and datascience) would print it is much better and more intuitive:

R: `array(runif(4*3*2), dim=c(4, 3, 2))`
```r
, , 1

          [,1]      [,2]       [,3]
[1,] 0.2825591 0.5522334 0.52391832
[2,] 0.1767849 0.6971883 0.71043175
[3,] 0.8761354 0.4497122 0.52815858
[4,] 0.1089502 0.5988136 0.02213838

, , 2

           [,1]      [,2]      [,3]
[1,] 0.09317015 0.3284360 0.8860116
[2,] 0.69452404 0.1435934 0.2693101
[3,] 0.66731886 0.4968847 0.9382747
[4,] 0.43573113 0.6021183 0.2983161
```
----
Julia: `rand(4, 3, 2)`

```
4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.687108  0.137954   0.171866
 0.635288  0.0111684  0.314236
 0.297158  0.711548   0.210333
 0.157791  0.216369   0.922683

[:, :, 2] =
 0.209024  0.253238   0.856131
 0.646831  0.241493   0.436598
 0.460633  0.0475346  0.318768
 0.231589  0.452068   0.83759
```
----
Matlab: `rand(4, 3, 2)` 

```matlab
ans(:,:,1) =

    0.8147    0.6324    0.9575
    0.9058    0.0975    0.9649
    0.1270    0.2785    0.1576
    0.9134    0.5469    0.9706


ans(:,:,2) =

    0.9572    0.4218    0.6557
    0.4854    0.9157    0.0357
    0.8003    0.7922    0.8491
    0.1419    0.9595    0.9340
```
I particularly like the way Julia displays the shape of the array and the datatype (`4×3×2 Array{Float64,3}`) and the way R labels the x- and y- axis (`[,1]`)--which is very useful to subset the array.  
I understand that there is a difference on how Python stores the element of the array (i.e., row-major) compared to R/Julia/Matlab (column major), but this shouldn't affect the way the array is printed. Or at least, there should be an option to decide which representation is better. Would that be possible to improve the printing of Numpy arrays? 
If this feature cannot be implemented, would it be possible to at least label the axes to be more explicit on what order the axes are printed?

**Comment by ahaldane** [comment]
I think the motivation is that with our notation you can (often) do:
```python
>>> a = np.random.rand(4, 3, 2)
>>> eval(repr(a))
``
and you get back a copy of the array. In other words the array representation matches the array construction code.

However, I would make two other comments:

First, it is possible for anyone to use their own array printing routines by calling `np.set_string_function`  to reset which functions get called to print arrays. In fact, if you look at our printing implementation in `numpy/core/arrayprint.py`, you will see that we set up a lot of printing code, and then at the very end of the file call that function to "patch in" our implementation - but any user can just as well patch in their own alternate printing methods, ours does not have a privileged status.

Second, we recently sort-of-promised that we would not change array printing much in the near future, since in numpy 1.14 we made a number of printing changes which caused a lot of headache for downstream projects, particularly those using doctests. However, currently numpy is working on a new direction, of allowing users to create ducktypes of ndarrays. It has occurred to me that it would be nice to rework our current printing code to make it easy for ducktype implementors to re-use our printing code (currently there are issues doing that). That could be an opportunity to reconsider array printing styles - although I have to admit I like our style right now.

**Comment by io99** [comment]
> I think the current printing of multidimensional arrays is not human friendly and misleading.
While I agree with your opinion, changing something on the ground level will leave room for error as lot of documentation has this implementation as default

**Comment by ahaldane** [comment]
Reviewing this as part of my 10 random issues, as requested [prpp report](https://mail.python.org/pipermail/numpy-discussion/2019-March/079250.html).

I'm going to close this issue: We are not going to dramatically change how numpy prints arrays now, for the reasons I mentioned above.
