### ISSUE TITLE
Mac accelerate np.linalg.svd() returns negative singular values

### ISSUE THREAD

**Issue by seehuhn** [numpy/numpy#12055]
For some matrices, the function `np.linalg.svd()` wrongly reports singular values to be negative.   The problem seems to disappear when the option `compute_uv=False` is used.

### Reproducing code example:

The following code reproduces the problem (required data file attached).

```python
import numpy as np

data = np.load('bug.npz')
X = data['X']

# compute Matern 5/2 covariance
dx = np.expand_dims(X, -2) - np.expand_dims(X, -3)
d2 = np.sum(np.square(dx), axis=-1)
tmp = np.sqrt(5 * d2)
C0 = (1 + tmp + np.square(tmp)/3)*np.exp(-tmp)
C1 = 0.007534975082954493 * C0 + 0.00027734601411494704 * np.identity(C0.shape[0])

# attempt to compute the condition number in two different ways:
D = np.linalg.svd(C1, compute_uv=False)
print(D[0] / D[-1])
assert D[-1] >= 0
U, D, Vt = np.linalg.svd(C1, full_matrices=False)
print(D[0] / D[-1])
assert D[-1] >= 0
```

### Error message:

The output of the script is as follows.  I would have expected the first two numbers to be identical (and positive) and for the `assert` statement to not trigger.  If the matrix is "bad" (I don't know whether 55.33 is the true condition number), I would expect an `LinAlgError` to be raised instead of a wrong result to be returned silently.

```
55.336278146990466
-1.9643903247889207
Traceback (most recent call last):
  File "./bug.py", line 21, in <module>
    assert D[-1] >= 0
AssertionError
```

### Numpy/Python version information:

1.14.5 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)]

[bug.npz.gz](https://github.com/numpy/numpy/files/2430973/bug.npz.gz)

**Comment by charris** [comment]
Is this OS X with accelerate?

**Comment by charris** [comment]
Works for me.

**Comment by seehuhn** [comment]
It's OS X 10.13.6.  I don't know about "with accelerate".  How do I find out?

**Comment by seehuhn** [comment]
Thanks.  I installed numpy using pip (`pip3 install numpy`).  Once complication was that I upgraded to numpy 1.15, but then had to downgrade again (`pip3 install numpy==1.14.5`) because tensorflow was complaining about the newer numpy version.

It seems that my install is using accelerate:
```
>>> numpy.__config__.show()
[...]
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
[...]
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
```

**Comment by charris** [comment]
Thanks for the info. We have had other problems with accelerate, which might seem surprising given Apple's resources, but there you are. We want to switch to another library at some point, but it is tricky. If you use the anaconda distribution it will come with MKL instead of accelerate.

**Comment by seehuhn** [comment]
I downloaded the mkl libraries from the Intel web page and then installed numpy 1.14.6 from source.  My script now prints
```
55.33627814699067
55.33627814699072
```
Thus, the problem is solved for me.

Not sure whether the issue should be closed, or stay open as a reminder that some Accelerate framework issue needs working around.

**Comment by charris** [comment]
Thanks for the update.  I think I'll close this as a search should still find it.
