### ISSUE TITLE
unexpected behavior during slicing

### ISSUE THREAD

**Issue by rschmaelzle** [numpy/numpy#12053]
Hi, I ran into a behavior I found surprising. It may be my mistake not understanding/knowing this, but I wanted to make sure it is noticed - I couldn't find info online (surprising as well, because if it is mymistake, I''d assume others ran into it as well). Basically, it seems that when I slice a 3 dimensional array of size 268 * 193 * 498 along the third dimension based on a logical vector ((gender_data ==2), the result is not what I expected, but the dimensions are swapped. ... Of note, this doesn't happen if i slice differently such as via ts_data[0,:,0:20] 
Best, Ralf.

### Reproducing code example:
```python
import numpy as np
ts_data[0,:,(gender_data == 2)].shape
OUTPUT (256, 193)

r = ts_data[:,:,(gender_data == 2)]
r[0,:,:].shape
OUTPUT (193, 256)
```

### Numpy/Python version information:
1.14.3 3.6.5 |Anaconda custom (64-bit)| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by seberg** [comment]
This is expected, see also the second bullet point close to the end of the section (it is true also for boolean arrays): https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#integer-array-indexing

Basically the `0` has to be considered an array, so it is iterated together with the boolean index. Thus there is a new dimension coming from both and numpy cannot guess where to put it, but numpy does guess it in the other case.

If you are still confused or just curious, a full explanation – and proposed solution – can be found in the NEP: http://www.numpy.org/neps/nep-0021-advanced-indexing.html

**Comment by seberg** [comment]
Obviously, documentation improvements are always welcome! Just the behaviour is set here….
