### ISSUE TITLE
Deprecated mktemp function used in tests

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12071]
The deprecated mktemp function is used in the following test files:

- numpy/core/tests/test_memmap.py
- numpy/core/tests/test_multiarray.py
- numpy/lib/tests/test_format.py

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by rgommers** [comment]
This is still the case, it should be replaced with non-deprecated functionality from https://docs.python.org/3/library/tempfile.html

**Comment by alize-papp** [comment]
@lyzlisa and I are working on this issue (WiMLDS Berlin hackathon)
