### ISSUE TITLE
SWIG C_CONTIGUOUS / F_CONTIGUOUS 

### ISSUE THREAD

**Issue by Dekken** [numpy/numpy#12077]
Hi there,

We use swig/cereal with numpy and have found a possible discrepancy.

What we have works with numpy 1.14.3, but does not with 1.15.2

It's entirely probable that we are misusing SWIG and numpy

The code can be found here: https://github.com/Dekken/tick/blob/col_maj/tick/array/tests/serialize_test.py#L63

Travis build showing errors for python 3.7 - I've tested python 3.7 with numpy 1.14.3 and it works.
https://travis-ci.org/X-DataInitiative/tick/builds/436711891

### Reproducing code example:

```python
import numpy as np
row_array = np.array([[1, 2.1, 5], [0, 4, 1]])
col_array = np.asfortranarray(row_array)

serialize_array(col_array, self.array_file)
# our serializing swig/cereal function
serialized_col_array = load_array(self.array_file, array_dim=2,
                                      dtype=self.dtype,
                                      major="col")
np.testing.assert_array_almost_equal(col_array, np.asfortranarray(row_array))
np.testing.assert_array_almost_equal(col_array, row_array)
np.testing.assert_array_almost_equal(col_array, serialized_col_array)       
```

### Error message:

Failing test: https://travis-ci.org/X-DataInitiative/tick/jobs/436711893#L3550

**Comment by mattip** [comment]
The test creates `row_array` differently:
```
row_array = np.arange(80).reshape(10, 8).astype(self.dtype)
```
Is the problem in writing the file or reading it? You can create a file with the old/new version and load it with the new/old version to test which direction is problematic.

**Comment by Dekken** [comment]
will do

**Comment by Dekken** [comment]
loading both versions of the written file fails with numpy 1.15 - I think I had been through something similar and had to set ```PyArray_ENABLEFLAGS(array, NPY_ARRAY_F_CONTIGUOUS);``` in swig on reading/loading

**Comment by Dekken** [comment]
Assuming I didn't mess it up - both saved files are identical regardless of numpy version

saving 1.14/1.15 file loading succeeds with 1.14
saving 1.14/1.15 file loading fails with 1.15

I had some similar problem with python/swig generally and had to add 

```
      PyArray_ENABLEFLAGS(array, NPY_ARRAY_F_CONTIGUOUS);
      PyArray_CLEARFLAGS(array, NPY_ARRAY_C_CONTIGUOUS);
```

for reading to work correctly at least in 3.6

**Comment by Dekken** [comment]
The de/serialized arrays are equal if flattened it appears

https://github.com/Dekken/tick/blob/col_maj/tick/array/tests/serialize_test.py#L75

**Comment by mattip** [comment]
So we have narrowed the problem down to one of the code paths in `load_array`. Which code path in `load_array` is it?

**Comment by Dekken** [comment]
it would be either 

```tick_float_colmaj_array2d_from_file```
or
```tick_double_colmaj_array2d_from_file```

I've verified that the contents of the C array are identical on loading/saving from cereal with both versions

[gist](https://gist.github.com/Dekken/18351fa610800f7f3f91db7a3b6987d8)

**Comment by Dekken** [comment]
Close if you like

**Comment by mattip** [comment]
It turns out the downstream project was (ab)using the ability to set flags directly via C, and was setting f_contiguous without changing the strides appropriately. We are still working out why older NumPy versions passed the testing.  While this issue may result in enhancing the checks done in `PyArray_ENABLEFLAGS(array, NPY_ARRAY_F_CONTIGUOUS);` and `PyArray_CLEARFLAGS(array, NPY_ARRAY_C_CONTIGUOUS);` for multi-dimensional arrays, I do not think is it a regression.

**Comment by mattip** [comment]
Here is a link to the [problematic code](https://github.com/Dekken/tick/blob/col_maj/lib/swig/array/sarray_typemap_out.i#L67)

**Comment by Dekken** [comment]
This link won't survive ;)

**Comment by Dekken** [comment]
Thanks for your time @mattip I got it working with "PyArray_New + flags"
