### ISSUE TITLE
Numpy should throw a KeyError when slicing with out-of-bounds indexes

### ISSUE THREAD

**Issue by nedclimaterisk** [numpy/numpy#12086]
### Reproducing code example:

```python
import numpy as np

In [20]: a = np.array([[1,2,3],[5,4,3]])

In [21]: a[5]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/nedcr/ClimateRisk/downscaling-tool/scripts/nanaimo_test.py in <module>()
----> 1 a[5]

IndexError: index 5 is out of bounds for axis 0 with size 2

In [22]: a[5:]
Out[22]: array([], shape=(0, 3), dtype=int64)

In [23]: a[5:7]
Out[23]: array([], shape=(0, 3), dtype=int64)

```

These results are potentially problematic, because poor indexing could lead to incorrect results in some calculations. Is there a reason why a KeyError isn't thrown here?

### Numpy/Python version information:

```
1.13.3 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

**Comment by mattip** [comment]
NumPy ndarrays are like sequences not dictionaries. The behaviour you see is appropriate for Python sequences.
```
a = range(3)
a[5]  # Raises IndexError
list(a[5:])  # Returns []
```

**Comment by nedclimaterisk** [comment]
Mmm.. I guess that last example should be `list(a)[5:]`, but yeah, it works the same. Strange bahviour in python. There is more discussion here: https://stackoverflow.com/questions/9490058/why-substring-slicing-index-out-of-range-works-in-python - I guess there is nothing to do in numpy. Thanks for the reply :)
