### ISSUE TITLE
remainder is not implemented for timedelta64

### ISSUE THREAD

**Issue by miccoli** [numpy/numpy#12092]
`timedelta64` allows for multiplication and division, but not for `remainder`

### Reproducing code example:

```python
>>> a = np.timedelta64(7, 's')
>>> b = np.timedelta64(3, 's')
>>> c = np.timedelta64(1, 's')
>>> a == b*2 + c
True
>>> a / 2
numpy.timedelta64(3,'s')
>>> a / b
2.3333333333333335
```
I would expect that ` a  %  b  ==  c` and ` a % 2 == c`
but
```
>>> a % b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'remainder' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
>>> a % 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'remainder' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.15.2 3.6.5 (default, Apr  6 2018, 12:22:55) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

**Comment by tylerjereddy** [comment]
There hasn't been much movement on `datetime64` issues lately; I tried to fix a few things here and there.

If this is something that should be fixed, people may need some convincing!

**Comment by miccoli** [comment]
@tylerjereddy  
`timedelta64` is the base for pandas [Time Deltas](http://pandas.pydata.org/pandas-docs/stable/timedeltas.html#time-deltas).

Lately I'm fighting with timestamped data, read via pandas [IO](http://pandas.pydata.org/pandas-docs/stable/io.html). It was not a smooth journey: a lot of bumps on the road, some of which I contributed (at leas so I hope) to mitigate (see pandas-dev/pandas#22802).

My point is that if `timedelta64` is not deprecated it should be implemented in a consistent way. Continuously juggling between different representation of the same quantity depending of the operation you are trying to perform is unnerving.


Just if you are interest in the problem that prompted this issue / request for enhancement. I have a signal sampled at 102.4 Hz with a jitter that causes deviations of about ±0.05 Hz. I have timestamps (stored as `timedelta64`) at 𝘪⋅𝛥𝘵 + 𝜀ᵢ ; the modulo arithmetic here is handy to compute the deviation 𝜀ᵢ of the sampling interval with respect to the nominal one. This is not possible directly: I have to convert first the `timedelta64` to long integers and then back to `timedelta64`. Of course I can circumvent the problem in a lot of ways but it would be nice to this in the natural way:  
(𝘪⋅𝛥𝘵 + 𝜀ᵢ) mod 𝛥𝘵

**Comment by tylerjereddy** [comment]
Ok, I tried to help with #11890, #11873, #11852, #11851, and #11841, which have maybe lingered a bit.

I'll take a look here then

**Comment by shoyer** [comment]
@tylerereddy feel free to ping me on review for datetime64 issues

**Comment by miccoli** [comment]
I think that #12120 completely addresses the present. Can I close the present issue, or there is a reason for keeping it open?

**Comment by tylerjereddy** [comment]
Yeah, I'll close this then. I think I may still try to follow up with remainder support for one or two other operand types mixed with timedelta64 and I think Eric suggested divmod would be a reasonable follow-up as well, but that can be pursued elsewhere.

**Comment by miccoli** [comment]
as what regard `mm` operands, `divmod` and `//` should follow, so that
```
divmod(a, b) == (a//b, a%b)
```
is an invariant.

thnx again.
