### ISSUE TITLE
Rendering of Math formula is broken in the documentation of numpy gradient

### ISSUE THREAD

**Issue by YuanjieZhao** [numpy/numpy#12100]
The rendering of Math formula is broken on the web page of numpy gradient. This problem occurs on all browsers I've tried.

## Link to the documentation page

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.gradient.html 

## Screenshot of the broken Math rendering

![image](https://user-images.githubusercontent.com/26195281/46574379-efa8fd00-c956-11e8-88cc-441d08511ddb.png)

**Comment by mattip** [comment]
This was fixed in pr #11006 for the numpy docs, the [page](http://www.numpy.org/devdocs/reference/generated/numpy.gradient.html) renders correctly in our current HEAD version. @rgommers any ideas?

**Comment by melissawm** [comment]
Closing this as it does seem to be fixed in the [current documentation](https://numpy.org/doc/stable/reference/generated/numpy.gradient.html).
