### ISSUE TITLE
BUG memory leak using ProcessPoolExecutor

### ISSUE THREAD

**Issue by pierreglaser** [numpy/numpy#12122]
Hello,
A recent [bug report](https://github.com/joblib/joblib/issues/781) was filed in [joblib](https://github.com/joblib/joblib), alerting us about a memory leak when calling several times a `Parallel` instance on a numpy.ndarray iterator.

While trying to recreate a minimal example, it turns out that the bug still exists without `joblib`,  when using only numpy and a `concurent.futures.ProcessPoolExecutor`.

Running the following bit of code on a fresh python 3.6 virtual environment with
```
numpy==1.15.2
psutil==5.4.7
``` 
```python
import numpy as np
import psutil
import gc

from concurrent.futures import ProcessPoolExecutor


def func(*args, **kw):
    pass


if __name__ == "__main__":
    n = 100000
    x = np.arange(n)
    print("x size: %0.3f MB" % (x.nbytes / 1e6))

    executor = ProcessPoolExecutor(2)

    for i in range(10):
        gc.collect()
        print("Iteration %d: %0.3f MB" %
              (i, psutil.Process().memory_info().rss / 1e6))

        for r in executor.map(func, [x[i] for i in range(n)], chunksize=100):
            pass

        # The following for-loop does not cause the memory leak
        # for r in executor.map(
        #         func, [x[i:i + 1] for i in range(n)], chunksize=100):
        #     pass
```

gives out:

```
x size: 0.800 MB
Iteration 0: 30.200 MB
Iteration 1: 61.817 MB
Iteration 2: 92.025 MB
Iteration 3: 116.171 MB
Iteration 4: 151.134 MB
Iteration 5: 174.965 MB
Iteration 6: 199.463 MB
Iteration 7: 223.617 MB
Iteration 8: 268.849 MB
Iteration 9: 293.966 MB
```

The problem pretty much  disappears in *all* of these cases:
* Running the commented for-loop instead 
* Using `concurent.futures.ThreadPoolExecutor` instead of `concurrent.futures.ProcessPoolExecutor`
* Calling `[pickle.dumps(xi) for xi in x]`
* Iterating on a `range` or a `list` instead of x by calling for example `x = x.tolist()`
* using `x = np.arange(n).reshape(-1, 1)` instead of `x = np.arange(n)`
* Populating and emptying a `multiprocessing.Queue` with the elements of `x` (by running this chunk of code instead of the `for r in executor.map(...)` loop):

```python
        from multiprocessing import Queue
        q = Queue()
        [q.put(xi) for xi in x]
        [q.get() for _ in range(n)]
        q.close()
```

Let me know if you want more detailed output about any of these cases.

We are kind of out of ideas with @ogrisel, so we are hoping to have some insight from more experienced numpy developers :)
Pierre

**Comment by dhimmel** [comment]
Not sure if there is any relation to this issue, but we've found a memory leak affecting pandas that was introduced by numpy 0.15.0 and not fixed as of 0.15.2: https://github.com/pandas-dev/pandas/issues/23035.

**Comment by charris** [comment]
Maybe #12127, #12037.

**Comment by pierreglaser** [comment]
With the last numpy master installed, I still have the leak. Will continue to look for a more minimal reproducing example.

**Comment by pierreglaser** [comment]
Update on this. Such a leak can be reproduced simply by calling `pickle.dumps` iteratively on chunks of the original array.
This:
```python
import gc
import pickle
import psutil

import numpy as np


def _get_chunks(chunksize, iterable):
    beg = 0
    end = chunksize
    while end <= len(iterable):
        yield iterable[beg:end]
        beg += chunksize
        end += chunksize


def dump_chunks(iterable):
    res = []
    for chunk in _get_chunks(chunksize, iterable):
        res += pickle.dumps(chunk)
    return


if __name__ == "__main__":
    n = 100000
    chunksize = 1000
    n_iter = 20
    x = np.arange(n)
    for i in range(n_iter):
        rss = psutil.Process().memory_info().rss / 1e6
        print("Iteration %d: %0.3f MB" % (i, rss))

        list_of_int64 = [x[i] for i in range(n)]
        r = dump_chunks(list_of_int64)
        gc.collect()
        del r
```

Leads to this memory usage:
```Iteration 0: 32.399 MB
Iteration 1: 88.596 MB
Iteration 2: 187.548 MB
Iteration 3: 221.774 MB
Iteration 4: 290.341 MB
Iteration 5: 324.612 MB
Iteration 6: 358.830 MB
Iteration 7: 388.477 MB
Iteration 8: 448.078 MB
Iteration 9: 510.816 MB
Iteration 10: 545.214 MB
Iteration 11: 579.129 MB
Iteration 12: 633.836 MB
Iteration 13: 667.816 MB
Iteration 14: 701.940 MB
Iteration 15: 787.571 MB
Iteration 16: 835.617 MB
Iteration 17: 869.581 MB
Iteration 18: 910.975 MB
Iteration 19: 970.416 MB
```

as soon as the number of chunks exceeds 1, there is a leak we cannot control. if `chunksize == n`, the memory usage remains stable.

**Comment by dhimmel** [comment]
> Update on this. Such a leak can be reproduced simply by calling pickle.dumps iteratively on chunks of the original array.

Great detective work. Have you investigated in which versions of numpy the leak occurs?

I am wondering if this could cause the issue we report at https://github.com/pandas-dev/pandas/issues/23047. The bug @charris referenced could also be the culprit. Or both could affect us because we use pandas.MultiIndexes as well as pickling.

**Comment by pierreglaser** [comment]
@mattip @dhimmel using git bisect, the leak appears to be introduced following #10564.

**Comment by pierreglaser** [comment]
@mattip  A specific entry of the cache is cleared only following a call to  `array_dealloc` (that calls `_array_dealloc_buffer_info`).  In my specific example, the cache does not contain numpy arrays, but scalar types, so I think the entries of the dict are never cleared.
A quick hack into `_buffer_get_info`, adding one entry into the cache only if it is a numpy array reduced the effect of the leak in a smaller example. This still needs a little bit more investigation but I think we are getting closer.

**Comment by mattip** [comment]
No, the `_buffer_info_cache` is a symptom, not the illness. Putting `ndarray`s or `scalars` into a list, then `dumps`-ing that list somehow causes a leak that `del`eting the list does not clear.

**Comment by pierreglaser** [comment]
@mattip, in the example above, what is pickled is not a list of numpy arrays, but a list of  `np.int64`s. There is no leak if we pickle a list of `np.ndarray`s instead. This can be verified by creating `x` like this:
`x = np.arange(n).reshape(-1 ,1)`

Following the commit that introduced the leak,  `_buffer_get_info` now creates entries in the `buffer_info_cache`, even when the pickled object is a numpy scalar type. Previously, it would do so only when the pickled object was a `np.ndarray`.

However, because in the previous behavior, only `np.ndarray`s were cached, entries of the cache were cleared only during a call of `array_dealloc`, through `array_dealloc_buffer_info`. This has not been changed in this commit.  Therefore, in my example, `np.int64` values are added into the cache, but are never cleared afterwards.

There may be other issues, this seems like one of them. The leak seriously slows down when adding only `np.array` entries into the cache.  Another solution would be clearing cache entries during scalar types deallocation I guess.

**Comment by mattip** [comment]
@pierreglaser  I created a PR to release the memory on scalar deallocation, could you test it and comment there if it lessens the problem in the original `ProcessPoolExecutor` code?

**Comment by pierreglaser** [comment]
@mattip update on this:

I ran the memory usage benchmarks from `ProcessPoolExecutor` with the following branches:
- the branch from the #12249 the you just opened
- master
- the commit where the regression was introduced
- the last commit before the regression was introduced
- a branch where I introduce a fix proposal by not caching if `obj` has a scalar type.

Here is the plotted peak memory usage:

![memory_usage_fig](https://user-images.githubusercontent.com/18555600/47371353-ec986580-d6e7-11e8-9435-d194f2100ee8.png)

From the graph, it seems like your PR is fixing something else (maybe another use case that has not been reported yet). With the fix I introduced, it seems the memory gets back to its behavior prior to the regression.

For the record, here are the scripts I used. Python3.7 on Ubuntu 18.04.
getting memory usage data:

```python
from concurrent.futures import ProcessPoolExecutor
import csv
import gc
import os
import psutil
import subprocess

import numpy as np


def func(v):
    return v


if __name__ == "__main__":
    n = 10000
    chunksize = 100
    n_iter = 100
    x = np.arange(n)
    memory_usage = []
    executor = ProcessPoolExecutor(max_workers=2)

    NUMPY_DIR = os.path.dirname(np.__file__)

    # get current, and remote tracked git branch for numpy
    git_command = ['git', '-C', NUMPY_DIR, 'rev-parse', '--abbrev-ref', 'HEAD',
                   '@{u}']
    p = subprocess.Popen(git_command, stdout=subprocess.PIPE)
    branches, _ = p.communicate()
    current_branch, tracked_branch = branches.decode().split()

    # record memory usage over many passes on the data
    for i in range(n_iter):
        rss = psutil.Process().memory_info().rss / 1e6
        memory_usage.append(rss)
        print("Iteration %d: %0.3f MB" % (i, rss))
        for r in executor.map(
                func, [x[i] for i in range(n)], chunksize=chunksize):
            pass
        del r
        gc.collect()

    # write the metadata an the memory usage to a csv
    with open('memory_usage.csv', 'a') as f:
        writer = csv.writer(f)
        writer.writerow([tracked_branch, current_branch, *memory_usage])
```

plotting the data (using `pandas` and `matplotlib`)
```python
import pandas as pd
import matplotlib.pyplot as plt

mem_usage = pd.read_csv('memory_usage.csv', index_col=[0, 1], header=None)
mem_usage.index.names = ['tracked_branch', 'local_barnch']
f, axs = plt.subplots(nrows=2, ncols=3, figsize=(14, 8), sharex=True,
                      sharey=True)
axs = axs.flatten()
ax_no = 0

for branches, usage in mem_usage.iterrows():
    ax = axs[ax_no]

    # plot the memory usage
    ax.plot(usage.values)
    ax.set_xlabel('iteration')
    ax.set_ylabel('memory usage (MB)')

    # plot the branch information
    branch_info = """
    tracked branch: {},
    local branch: {}
    """.format(*branches)

    ax.text(x=0, y=0.95, s=branch_info, verticalalignment='top',
            transform=ax.transAxes, fontsize=10)
    ax_no += 1

f.suptitle('memory usage when calling ProcessPoolExecutor.map on many'
           'np.int64')
f.savefig('memory_usage_fig.png')
```  

Note: the results are the same using the `pickle.dumps` minimal example written above.
