### ISSUE TITLE
tensordot without copy

### ISSUE THREAD

**Issue by fujiisoup** [numpy/numpy#12132]
`np.tensordot` reshapes arrays to 2-dimensional arrays.
Reshaping sometimes induces a copy of the original array, and it is problematic if the array is a memory efficient view that is created by `as_strided`.

Is it reasonable to have a `tensordot` c-implementation without reshaping?

### Reproducing code example:
```python
import numpy as np

def rolling(a, window, axis):
    """ rolling window operation taken from #31"""
    a = np.swapaxes(a, axis, -1)
    shape = a.shape[:-1] + (a.shape[-1] - window + 1, window)
    strides = a.strides + (a.strides[-1],)
    rolling = np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides,
                                              writeable=False)
    return np.swapaxes(rolling, -2, axis)


arr = np.random.randn(1000, 2000)
y = rolling(rolling(arr, 30, 0), 40, 1)
x = np.random.randn(30, 40)

np.tensordot(y, x, axes=2)  # -> MemoryError
```

### Error message:

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-1-604fcd21e3bd> in <module>()
     15 x = np.random.randn(30, 40)
     16 
---> 17 np.tensordot(y, x, axes=2)

~/anaconda3/envs/xarray/lib/python3.6/site-packages/numpy/core/numeric.py in tensordot(a, b, axes)
   1310     oldb = [bs[axis] for axis in notin]
   1311 
-> 1312     at = a.transpose(newaxes_a).reshape(newshape_a)
   1313     bt = b.transpose(newaxes_b).reshape(newshape_b)
   1314     res = dot(at, bt)

MemoryError: 

### Numpy/Python version information:

```python
In [2]: import sys

In [3]: sys.version
Out[3]: '3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) \n[GCC 7.3.0]'

In [4]: np.__version__
Out[4]: '1.15.0'
```

**Comment by shoyer** [comment]
It looks like `np.einsum()` works much better here, e.g., `np.einsum('...ij,ij', y, x)` completes very quickly.

I'm pretty sure that `np.dot()` itself copies data in some/many cases when you have strange strides. For matrix-matrix multiplication, copying inputs does not matter, because copying takes time O(n^2) but the computation takes (roughly) time O(n^3). Here you're doing matrix-vector multiplication (effectively), so the cost of the computation and copying is roughly equivalent.

**Comment by fujiisoup** [comment]
Thanks, @shoyer for the nice suggestion.
I just noticed `np.einsum('...ij,ij', y, x, optimize=False)` works 10 times faster than my `numba` interpretation.

It looks the best path.
Closing.
