### ISSUE TITLE
Reviving "plans" from the TRAC wiki into NEPs

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12164]
Thanks to #12161, I discovered that the old wiki is still archived somewhere.

On this page, there are a bunch of links that might make sense to turn back into NEPs

https://web.archive.org/web/20130402020606/http://projects.scipy.org/numpy/wiki

- [x] PR #12166 Zero Rank Arrays
- [ ] [NumPy Refactoring](https://web.archive.org/web/20130402150231/http://projects.scipy.org/numpy/wiki/NumPyRefactoring) - maybe merge this with notes from the [compiler workshop in 2016](https://python-compilers-workshop.github.io/)

Edit: add checklist

**Comment by rgommers** [comment]
Which ones in particular were you thinking about?

**Comment by eric-wieser** [comment]
I'm thinking that we should write up all of them, even if we mark them as abandoned / informational / implemented. For instance, there's a write-up on the rationale for 0d arrays existing, and it would be a shame for that to be lost to time.

**Comment by rgommers** [comment]
Hmm, many of those pages are one or two paragraphs of random notes that weren't meant as a well thought out NEP. So I'd rather make a list of the things that are actually valuable, otherwise we're just inserting irrelevant things into the NEPs page. The 0-D one is definitely useful. Something like https://web.archive.org/web/20130402150231/http://projects.scipy.org/numpy/wiki/NumPyRefactoring also. Pages like `NumScons` or `ImprovingIssueHandling`, not really.

**Comment by seberg** [comment]
Hehe, nice that mail about 0-D arrays/array-scalars https://web.archive.org/web/20100501162447/http://aspn.activestate.com:80/ASPN/Mail/Message/numpy-discussion/3028210 is pretty much spot on to what I believe, too bad it wasn't implemented back then.

**Comment by eric-wieser** [comment]
@seberg: As far as I can tell, all of that mail is implemented, with the possible exception of the return type of `ufunc.reduce`

**Comment by seberg** [comment]
Hehe, Eric, yeah. I guess I noticed that mostly because that is what I wish we had :). If we had the ufunc reduce thing, I believe you could switch to not converting 0D to scalars magically, heck I bet most users wouldn't notice, but unfortunately it could be very tricky.

**Comment by bsipocz** [comment]
Would the unchecked box of "Numpy Refactoring" covered by the new 2.0 release? If yes, could we close this issue?

**Comment by charris** [comment]
Looks like that was a different proposal aimed at making a core NumPy that would be independent of Python. These days it looks like we are headed towards a standard interface rather than a standard implementation.

Thanks for the heads up, Brigitta.
