### ISSUE TITLE
recarray from record has no shape, cannot be sliced.

### ISSUE THREAD

**Issue by cboulay** [numpy/numpy#12161]
Creating new recarrays from a single record results in a recarray with shape = (). It cannot be indexed into and it has no length. For now I'm working around this by reshaping the new recarray to (1,).

### Reproducing code example:

```python
import numpy as np
ra = np.rec.array(np.ones(4, dtype='f4,f4'))
r = ra[0]
ra2 = np.core.records.array(r)
ra2.shape  # returns ()
ra2[0]
# np.array_equal(ra2.reshape(1,)[0], ra[0])  # True
```

### Error message:

```
Traceback (most recent call last):
  File "/home/chad/miniconda3/envs/np/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-18a4fa8bb93d>", line 6, in <module>
    ra2[0]
  File "/home/chad/miniconda3/envs/np/lib/python3.6/site-packages/numpy/core/records.py", line 505, in __getitem__
    obj = super(recarray, self).__getitem__(indx)
IndexError: too many indices for array
```

### Numpy/Python version information:

1.14.3 3.6.3 |Intel Corporation| (default, May  4 2018, 04:22:28) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

**Comment by eric-wieser** [comment]
This is by design - you have a 0d array, so need to pass 0 indices:
```
>>> r = np.rec.array(np.ones(4, dtype='f4,f4'))[0]
>>> ra2 = np.core.records.array(r)
>>> ra2.shape
()
>>> ra2[0]
IndexError: too many indices for array
>>> ra[()]
(1., 1.)
```

**Comment by cboulay** [comment]
What does a 0d even mean? How can something be zero-dimensional but yet be nonempty? Can you point me to any numpy documentation?

**Comment by eric-wieser** [comment]
> How can something be zero-dimensional but yet be nonempty?

I'd hope you agree that an array is empty if `product(arr.shape) == 0`. The product of `()` is 1 (the multiplicative identity, so a 0d array has exactly one value.

I'm not sure if there is any documentation specifically on this, as it's just a natural base case for n-dimensional arrays

**Comment by cboulay** [comment]
OK thanks.
I've been using numpy for biological signal processing for the past 8 years, and Matlab for 6 years before that, and I've never encountered a zero-rank array and I've never had to use an empty tuple for indexing.

From a programmer's perspective, having a container that can't be indexed is kind of frustrating. If I wanted a scalar (my reading suggests that the zero-rank array is equivalent to a scalar), then I would have kept the `record` and not tried to create a `recarray` with it.

There is some theory here I'm lacking. I'd love to read up on it but the docs are lacking. After searching around I found a couple references to a now missing page, but luckily it's still available on [the web archive](https://web.archive.org/web/20130401215434/http://projects.scipy.org/numpy/wiki/ZeroRankArray).

Thanks for your time.

**Comment by charris** [comment]
There was also a pretty long discussion on the mailing list back around the time of the first NumPy release, I forget who pushed the idea, it was one of the early contributors.
