### ISSUE TITLE
Strides of array with dimension of `1` are bogus when NPY_RELAXED_STRIDES_DEBUG is set

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpy#12172]
See https://github.com/numpy/numpy/pull/12171 if you don't want to recompile numpy on your system:

```
export NPY_RELAXED_STRIDES_DEBUG=1
git clean -xdf
python setup develop --no-deps
# This fails
python -c "import numpy as np; assert np.ones((3, 1, 3), dtype='double').strides == (24, 24, 8)"
# This passes
python -c "import sys; import numpy as np; assert np.ones((3, 1, 3), dtype='double').strides == (24, sys.maxsize, 8)"
```
### Numpy/Python version information:

```
import sys, numpy; print(numpy.__version__, sys.version)              
1.16.0.dev0+2c4c93a 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
```

**Comment by hmaarrfk** [comment]
Seems to be all strides:

```
>>> import numpy as np
>>> np.zeros((3, 1, 3), 'float32').strides
>>> np.zeros((3, 1, 3), 'int8').strides 
>>> np.zeros((3, 1, 1, 3), 'int8').strides
>>> np.zeros((3, 1, 1, 1), 'int8').strides
>>> np.zeros((1, 1, 1, 1), 'int8').strides 
(12, 9223372036854775807, 4)
(3, 9223372036854775807, 1)
(3, 9223372036854775807, 9223372036854775807, 1)
(1, 9223372036854775807, 9223372036854775807, 9223372036854775807)
(9223372036854775807, 9223372036854775807, 9223372036854775807, 9223372036854775807)
```

Maybe I'm not supposed to use strides when the axis has a dimension of 1?

**Comment by pv** [comment]
It's intentional afaik: for dimension with size-1 the stride should not matter (and so it is filled with value that triggers segfault in incorrect code).

**Comment by hmaarrfk** [comment]
Yeah, I think you are right. Sorry :/

**Comment by seberg** [comment]
Basically, when we enabled relaxed strides, in the first few releases we would set this flag during prerelease, because it was the pretty much the only way to flush downstream incompatibility. So, now it is still there but you have to enable it manually. Sounds like it worked ;).

**Comment by hmaarrfk** [comment]
I guess I wanted to write some code that dependend on items with an axis of 1 to have the new default values.

I'll think of a different algorithm for it. Thanks!

**Comment by seberg** [comment]
@hmaarrfk if you run into an issue because of that, your code probably already checks that the array is contiguous. In that case you should not use strides at all IMO, you can just use ITEMSIZE and the shape. If you use strides you will normally always multiply them with (dim-1) at some point, and the value will not matter.
