### ISSUE TITLE
Document page for Numpy Indexing is truely aweful!, simply uncomprehensable! 

### ISSUE THREAD

**Issue by arjangcore** [numpy/numpy#12193]
The page is 
https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html#
Just give it to someone who is an experienced programmer and ask  him to make sense of it please!

**Comment by eric-wieser** [comment]
> Just give it to someone who is an experienced programmer and ask him to make sense of it please!

Give it to a numpy developer and I'm sure they'll be able to make sense of if :). Our metric for successful documentation should not be just whether an experienced programmer can make sense of it, but also whether more of a novice can.

Feel free to suggest improvements / make them as PRs - as filed, this issue doesn't really suggest a path forwards.

**Comment by eric-wieser** [comment]
Note also that those docs are the 1.13 version, and the 1.15 ones may be marginally better (although you made me discover #12194, so thanks!)

**Comment by hmaarrfk** [comment]
@arjangcore can you please explain to use your computing background?

Reading over it again, the documentation seems to assume that the reader knows about python indexing. This might not be the case. Python has many peculiarities that make transitionning from other languages difficult at times.

For example, it isn't really obvious that `x[1]` returns something that has 1 fewer dimensions than `x`.

Maybe the basics can be expanded upon.

**Comment by melissawm** [comment]
Unless we have concrete suggestions for improvements to the current documentation, I'm assuming this issue is no longer relevant. Feel free to re-open.
