### ISSUE TITLE
Inconsistent attribute naming of infinity and negative infinity

### ISSUE THREAD

**Issue by ChaiBapchya** [numpy/numpy#12202]
Why does numpy have inconsistent naming convention followed for infinity and negative infinity?
For infinity, it is `np.inf` (all small `inf`)
For negative infinity, it is `np.NINF` (all capital `NINF`)

Why not a standard same convention of all small / all cap?

### Reproducing code example:

```python
import numpy as np
>>> import numpy as np; a=mx.nd.array([np.inf,np.NINF,-1,np.INF,np.ninf])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'numpy' has no attribute 'INF'
>>> import numpy as np; a=mx.nd.array([np.inf,np.NINF,-1,np.ninf])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'numpy' has no attribute 'ninf'
```

### Error message:
```
AttributeError: module 'numpy' has no attribute 'INF'
AttributeError: module 'numpy' has no attribute 'ninf'
```

### Numpy/Python version information:

1.14.3 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by eric-wieser** [comment]
A better question - why does `np.NINF` exist at all? Why not just `-np.inf`?

**Comment by ChaiBapchya** [comment]
Exactly. I have been using `np.inf` and `-np.inf` all this while confused whether it's right or should I stick to the `np.NINF` and `np.PINF`

**Comment by seberg** [comment]
Closing, the discussion of removing names like `np.NINF` has other issues open.
