### ISSUE TITLE
Misleading assert_almost_equal error message in presence of infs.

### ISSUE THREAD

**Issue by antomaly** [numpy/numpy#12200]
When using np.testing.assert_almost_equal (and related functions like assert_allclose) to compare arrays which include infs, the error message can be misleading. It describes a comparison between arrays with the infs stripped out, which makes debugging more difficult.

### Reproducing code example:

```python
import numpy as np
np.testing.assert_almost_equal([np.inf, 0], [np.inf, 1])
```

In numpy version 1.12.1, this produces the error message 
```
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 100.0%)
 x: array([ inf,   0.])
 y: array([ inf,   1.])
```

In numpy version 1.13.3, we instead get the error message
```
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 100.0%)
 x: array([ 0.])
 y: array([ 1.])
```

This second error message doesn't reflect what arrays are actually being compared. (The mismatch percentage is also wrong, in both versions.)

**Comment by liwt31** [comment]
Can I take on this? It could be fixed by some tweaks in `np.testing.utils.assert_array_almost_equal.compare` and `np.testing.utils.assert_array_compare`, in which NaN's are excluded from the original input matrix. We can make a copy of the original matrix and format output based on it.
