### ISSUE TITLE
np.dot(A, <n>*A.T) returns a non-symmetric matrix 

### ISSUE THREAD

**Issue by ligc** [numpy/numpy#12218]
### Reproducing code example:

```
#!/usr/bin/env python
import numpy as np

y1 = np.asarray([
[2.91449144e-01, 4.59977736e+00, 2.83297743e+01, 9.53724273e+00,
  5.25221643e+00, 1.02158386e+01, 0.00000000e+00, 2.24806400e+00,
  4.01949243e-01, 0.00000000e+00, 1.32968418e+00],
 [1.66920873e+00, 2.31749208e+00, 3.10276239e+00, 6.89104278e+00,
  1.07913083e+00, 9.11750228e+00, 6.86470141e+00, 2.24806400e+00,
  1.96508519e+00, 0.00000000e+00, 0.00000000e+00],
 [1.85467637e-01, 5.49072090e+00, 6.86880498e+01, 7.88398527e+00,
  4.41940736e+00, 1.02032004e+01, 0.00000000e+00, 2.24806400e+00,
  2.14372930e+00, 0.00000000e+00, 1.32968418e+00],
 [2.91050681e-01, 4.59902850e+00, 2.82231912e+01, 9.53109983e+00,
  5.26196419e+00, 1.02111336e+01, 0.00000000e+00, 2.24806400e+00,
  4.02729258e-01, 4.76069790e-05, 1.32968418e+00],
 [1.86186825e-01, 5.48743082e+00, 6.86648941e+01, 7.86822089e+00,
  4.40019891e+00, 1.01876005e+01, 1.29820826e-03, 2.24806400e+00,
  2.14295826e+00, 1.98928485e-03, 1.32968418e+00]
])

ydot1 = 2 * np.dot(y1,  y1.T)
ydot2 = np.dot(y1,  2 * y1.T)
if (ydot1 == ydot1.T).all():
    print("ydot1 is symmetric")
else:
    print ("ydot1 is not symmetric")

if (ydot2 == ydot2.T).all():
    print("ydot2 is symmetric")
else:
    print ("ydot2 is not symmetric")
```

Run the code listed above, get the following result:

```
[ligc@macbook: ~]$ python test.py
ydot1 is symmetric
ydot2 is not symmetric
[ligc@macbook: ~]$
```

The problem is that the ```np.dot(y1,  2 * y1.T)``` returns a non-symmetric matrix, we have a lot of machines with the same numpy and scipy version to run this code, **the problem only occurs on a few nodes**. The non-symmetric matrix causes problems for our product, we COULD change the ydot1 = \<n\> * np.dot(y1,  y1.T) to ydot2 = np.dot(y1,  \<n\> * y1.T),  it will involve a lot of code changes and we would like to understand why it happens.

This might be related to https://github.com/numpy/numpy/issues/6794 and https://github.com/numpy/numpy/issues/6793

### Numpy/Python version information:

```
[ligc@macbook: ~]$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__, sys.version)
('1.15.2', '2.7.10 (default, Oct  6 2017, 22:29:07) \n[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]')
>>>
```

**Comment by shoyer** [comment]
I think the problem here is that the order of operations for floating point arithmetic matters, so small differences for mathematically equivalent operations are basically inevitable. You probably shouldn't be relying on exact symmetry at all or any sort of floating point equality. If you really need exactly symmetric matrices I would consider writing something like `ydot2 = 0.5 * (ydot2 + ydot2.T)`.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed our problem, and we changed the ```if (ydot == ydot.T).all()``` to ```if np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15):``` to avoid the float comparision issue.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed our problem, and we changed the ```if (ydot == ydot.T).all()``` to ```if np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15):``` to avoid the float comparision issue.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed our problem, and we changed the ```if (ydot == ydot.T).all()``` to ```if np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15):``` to avoid the float comparision issue.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed our problem, and we changed the ```if (ydot == ydot.T).all()``` to ```if np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15):``` to avoid the float comparision issue.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed our problem, and we changed the ```if (ydot == ydot.T).all()``` to ```if np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15):``` to avoid the float comparision issue.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed our problem, and we changed the ```if (ydot == ydot.T).all()``` to ```if np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15):``` to avoid the float comparision issue.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed our problem, and we changed the ```if (ydot == ydot.T).all()``` to ```if np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15):``` to avoid the float comparision issue.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed the symmetric matrix issue, and we have changed the ```(ydot == ydot.T).all()``` to ```np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15)``` to avoid the float numbers comparision issue.

**Comment by ligc** [comment]
Thanks @shoyer, the suggested ```ydot2 = 0.5 * (ydot2 + ydot2.T)``` fixed the symmetric matrix issue, and we have changed the ```(ydot == ydot.T).all()``` to ```np.allclose(ydot, ydot.T, atol=1e-12, rtol=1e-15)``` to avoid the float numbers comparision issue.
