### ISSUE TITLE
array_function_dispatch() breaks inspect.getargspec/getfullargspec

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#12225]
xref https://github.com/numpy/numpy/issues/12028

Even though assuredly this isn't really guaranteed by our API, introspection into NumPy function arguments appears to be used by a number of our dependencies. Unfortunately, although `inspect.signature` has a `follow_wrapped` argument this isn't the case for `inspect.getfullargspec` or the old `inspect.getargspec` (still used for Python 2.7 compatibility in many cases).

Behavior on master:
```
>>> inspect.getfullargspec(np.sum)
FullArgSpec(args=[], varargs='args', varkw='kwargs', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
```

Behavior with the released version of NumPy:
```
>>> inspect.getfullargspec(np.sum)
FullArgSpec(args=['a', 'axis', 'dtype', 'out', 'keepdims'], varargs=None, varkw=None, defaults=(None, None, None, <class 'numpy._globals._NoValue'>), kwonlyargs=[], kwonlydefaults=None, annotations={})
```

This results in test failures in dask (https://github.com/dask/dask/issues/4111) and is my best guess for pandas test failures (https://github.com/pandas-dev/pandas/issues/23172).

We have a few options for fixing this:
1. Don't. Tell dependencies to figure out a more robust way of handling this.
2. Use some sort of `eval`/`exec` based magic to build real function objects with the right signature  https://github.com/numpy/numpy/issues/12028#issuecomment-429379252
3. Stop using a decorator in favor of writing functions with explicit signatures.

(1) seems quite unfriendly to users. (3) would result in a lot of more boilerplate code in NumPy and would [break extensibility](http://www.numpy.org/neps/nep-0018-array-function-protocol.html#extensibility).

(2) might have a negative impact on import performance, but may be our best bet.

**Comment by eric-wieser** [comment]
Option 4: Roll back `__array_function__` changes and postpone them till after we drop python 2, where `inspect.signature` is guaranteed to exist

**Comment by shoyer** [comment]
Testing suggests that this would fix the Dask issue, but something else appears to be causing the pandas issue -- #12226 didn't fix it.

@eric-wieser Unfortunately, the mere availability of `inspect.signature` would not be enough -- it actually has to always be used instead of `inspect.getfullargspec`. This seems unlikely to be the case for at least some time.

**Comment by mhvk** [comment]
I guess the point of waiting for python3 only is that option (1) becomes more palatable - we can tell users how to solve the introspection problem.

p.s. There may be some independent value in not rolling out something major for our last python2 version, which perhaps argues for waiting.  Or, maybe more crazily, one could proceed with the wrapper not doing anything by default, i.e., have one release in which even having `__array_function__` is strictly opt-in (there was some discussion about this on the mailing list).

**Comment by rgommers** [comment]
@shoyer did you delete your own comment from 5 hours ago? I was going to respond to it, but it's not here anymore.

>  Or, maybe more crazily, one could proceed with the wrapper not doing anything by default, i.e., have one release in which even having __array_function__ is strictly opt-in (there was some discussion about this on the mailing list).

Not crazy - that seems much better than removing everything and putting it back after the 1.16.x branch

**Comment by shoyer** [comment]
@rgommers It looks like my comment is still there? Maybe some temporary glitch related to the GitHub data outage last night?

**Comment by shoyer** [comment]
>> Or, maybe more crazily, one could proceed with the wrapper not doing anything by default, i.e., have one release in which even having array_function is strictly opt-in (there was some discussion about this on the mailing list).
> Not crazy - that seems much better than removing everything and putting it back after the 1.16.x branch

Yes, if there is no way avoid breaking some edge cases it is certainly better to roll this out slowly. It would be a reasonable use-case for @njsmith's `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION` environment variable.

**Comment by seberg** [comment]
I think we can close this, as we have the `signature` works and the discussion was: On python 3 that will fix it, Python 2 is a problem... But Python 2 isn't a problem anymore.
