### ISSUE TITLE
Manylinux wheels: openblas not faster with multiple threads

### ISSUE THREAD

**Issue by NotSqrt** [numpy/numpy#12220]
Hi,

Among other methods, `np.linalg.eig` takes the same **wall clock time** either with `OPENBLAS_NUM_THREADS=1` or letting it use multiple threads, **despite using multiple or all CPUs**.

### Reproducing code example:

The behaviour is the same for python3.6 or python2.7.

I ran this on 2 computers with different Intel CPUs, Ubuntu 16.04, clean virtualenvs.

```bash
pip install numpy==1.15.2  # should pull numpy-1.15.2-cp27-cp27mu-manylinux1_x86_64.whl or similar

/usr/bin/time -v python -c "import numpy as np; G = np.random.random((2048, 2048)); [np.linalg.eig(G) for __ in range(2)]"
#	Command being timed: "python -c import numpy as np; G = np.random.random((2048, 2048)); [np.linalg.eig(G) for __ in range(2)]"
#	User time (seconds): 57.16
#	System time (seconds): 49.60
#	Percent of CPU this job got: 757%
#	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:14.08

OPENBLAS_NUM_THREADS=1 /usr/bin/time -v python -c "import numpy as np; np.random.seed(0); G = np.random.random((2048, 2048)); [np.linalg.eig(G) for __ in range(2)]"
#	Command being timed: "python -c import numpy as np; np.random.seed(0); G = np.random.random((2048, 2048)); [np.linalg.eig(G) for __ in range(2)]"
#	User time (seconds): 14.06
#	System time (seconds): 0.09
#	Percent of CPU this job got: 99%
#	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:14.16
```

As can be seen, similar `wall clock time`, but `User time` and `Percent of CPU` multiplied by ~8 (I used a 8-core CPU) when leaving `OPENBLAS_NUM_THREADS` at its default value.

So you're like:
>  :smile: Openblas used all my cores, it is faster !

but in fact, it just used multiple cores for nothing.

Currently, the wheels use a pre-built openblas version from wheels.scipy.org.
Before December 2017, the code to compile openblas and include it in the manylinux wheel was:
https://github.com/matthew-brett/multibuild/commit/8350b93be1e8f622c8ca49d8b17e7bad070df647

```bash
make DYNAMIC_ARCH=1 USE_OPENMP=0 NUM_THREADS=64
```

This behaviour is certainly not new, and probably attributable to openblas, but I wanted to make Numpy contributors aware of this.

### Numpy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
('1.15.2', '2.7.12 (default, Dec  4 2017, 14:50:18) \n[GCC 5.4.0 20160609]')
```

Thanks !

**Comment by u55** [comment]
I can confirm that `np.linalg.eig` **does not** have a speedup when using multiple threads on Linux where I have compiled OpenBlas myself instead of using the wheels. However, `np.dot` **does** have a speedup when using multiple threads.

> Among other methods, `np.linalg.eig` takes the same wall clock time ...

@NotSqrt In which other methods did you see this behavior?

**Comment by njsmith** [comment]
Please report this to the OpenBLAS project, they're the ones who might be able to do something about it :-)

**Comment by u55** [comment]
@njsmith Agreed. I can replicate the same behavior in Julia, so it's clearly not a Numpy bug. 

```
$ OPENBLAS_NUM_THREADS=1 /usr/bin/time -v julia -e 'using LinearAlgebra; G = rand(2048, 2048); eigen(G);'
	Command being timed: "julia -e using LinearAlgebra; G = rand(2048, 2048); eigen(G);"
	User time (seconds): 19.26
	System time (seconds): 0.15
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:19.47

$ OPENBLAS_NUM_THREADS=64 /usr/bin/time -v julia -e 'using LinearAlgebra; G = rand(2048, 2048); eigen(G);'
	Command being timed: "julia -e using LinearAlgebra; G = rand(2048, 2048); eigen(G);"
	User time (seconds): 87.62
	System time (seconds): 47.03
	Percent of CPU this job got: 738%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:18.23
```

**Comment by seberg** [comment]
I will close this, but do encourage you to open an issue in OpenBLAS!

**Comment by NotSqrt** [comment]
Thanks for your input.

I've found this in OpenBLAS : https://github.com/xianyi/OpenBLAS/issues/1560#issuecomment-388893634

I'll add more info there.
