### ISSUE TITLE
integrate content/images on broadcasting in docs

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#12223]
https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc explains broadcasting well (including useful diagrams) and is linked to from https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html. It is the only link to https://scipy.github.io/old-wiki left.

This content should be integrated in the user guide. There's also useful code to draw such diagrams at https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

**Comment by mattip** [comment]
A different issue, but ...

The actual broadcasting doc lives in `numpy/doc/broadcasting.py`. Why is some of the documentation in `numpy/doc` and some in `doc/source/user`? Should we remove `numpy/doc` or do new users browse using our `help(numpy.doc)` system?

**Comment by mattip** [comment]
A different issue, but ...

The actual broadcasting doc lives in `numpy/doc/broadcasting.py`. Why is some of the documentation in `numpy/doc` and some in `doc/source/user`? Should we remove `numpy/doc` or do new users browse using our `help(numpy.doc)` system?

**Comment by rgommers** [comment]
> Should we remove `numpy/doc` or do new users browse using our `help(numpy.doc)` system?

Allowing ``help(numpy.doc.broadcasting)` for some topics is the only reason `numpy.doc` exists AFAIK. However `help()` is increasingly irrelevant and given that `numpy.doc` isn't really part of our API I'd be fine with removing the whole thing. Reduces contributors/maintainer confusion and puts all docs where they belong, under `doc/source/`.

**Comment by eric-wieser** [comment]
Are the rst docs distributed with the pypi package? There might be some argument about offline help  in favor of keeping something like `np.doc`, even if all it does is read in the rst files

**Comment by charris** [comment]
Discoverability is probably key, and those docs aren't all that discoverable, even for maintenance purposes. I usually hit `?` for the docstring or hit google for the docs. Moving those docs sounds like a good idea to me.

**Comment by eric-wieser** [comment]
> a lot via ? (or in some cases, help())

Don't forget `np.info`, which I think tries to work around some rules in `help`s `__doc__`-lookup that don't work for ufuncs
