### ISSUE TITLE
np.random.choice with multiprocessing returns identical values more often than single processing 

### ISSUE THREAD

**Issue by MJosefson** [numpy/numpy#12231]
I tried to use np.random.choice with the multiprocessing library applied to identical data but in parallel processes to speed up a simulation. Then I came across an unexpected side effect.
 
The random samplings appear to be less random when doing multiprocessing than when doing single processing. The pattern of mean values for the random sample are often identical for the few first samples, then there is a more regular pattern where identical values appear every second time or similar. Below is an example code with text output.

Output from the below code:
Running Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic on x86_64 computer

Single process
[136.99470804318773, 138.65168938261866, 133.59633227541497, 135.33624623443436, 135.3288614009962, 135.53831706018755, 134.80941789725605, 136.91831793195524, 136.46465072531421, 136.42414087330076, 135.62503639442536, 135.69894704276624, 136.61812340005451, 134.07609304581661, 134.61896782553274, 136.2073836821736]

4 cores 8 threads
7 threads used
[134.58343651532508, 134.58343651532508, 134.58343651532508, 134.58343651532508, 134.58343651532508, 134.58343651532508, 134.58343651532508, 137.78699779947749, 137.78699779947749, 137.78699779947749, 133.45879254382663, 137.78699779947749, 137.78699779947749, 133.45879254382663, 137.78699779947749, 137.39873418456261]

### Reproducing code example:

```python
import numpy as np
import multiprocessing, psutil, platform
import matplotlib.pyplot as plt

def get_sampling_mean(distr_portion):
    smps = []
    for i in range(20):       
        smp = np.random.choice(distr_portion, size=10)
        smps.append(smp)
    return np.mean(smps) 
 
if __name__ == '__main__':
    running_system_id_str = 'Running '+ platform.platform()
    hardware_id_str = 'on ' +platform.processor()+ ' computer' 
    print(running_system_id_str, hardware_id_str)
    print()
       
    """Make 16 identical distribution entries in a list"""
    distr_size = 5000
    distr = np.random.normal(loc=135, scale=20, size=distr_size)    
    tasks = []
    for task in range(16):
        tasks.append(distr)
        
    """Get the single processing results"""
    smp_means = list(map(get_sampling_mean, tasks))   
    print('Single process')
    print(smp_means)
            
    """Get the multiprocessing results"""  
    cores = psutil.cpu_count(logical=False)
    threads = psutil.cpu_count(logical=True)
    if cores == threads:
        threads_used = threads
    else:
        threads_used = threads-1        
    print()
    print(cores, 'cores', threads, 'threads')
    print(threads_used, 'threads used') 
    
    pool = multiprocessing.Pool(processes=threads_used)
    smp_means_MPC = list(pool.map(get_sampling_mean, tasks))
    print(smp_means_MPC)
    
        
    figure, ax = plt.subplots(1, 2)
    ax[0].plot(smp_means)
    ax[1].plot(smp_means_MPC)
    ax[0].set_xlabel('mean_smp_magnitude')
    ax[1].set_xlabel('mean_smp_magnitude from MPC')
    plt.show()
```

### Numpy/Python version information:

1.13.3 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Comment by bashtage** [comment]
You need to use a new instance of `RandomState` in each process.  When you use the singleton (module level) RandomState the additional copies may be identical to the initial RandomState that is created when the module is first initialized. 

Or you could use something like randomgen https://pypi.org/project/randomgen/ which supports generators with multiple streams or simple jump functions.

**Comment by MJosefson** [comment]
Thank you very much for the good answer. I have now tested with a local Random generator object for each process according to the code below and everything works as expected also with multiprocessing.

```python
def get_sampling_mean(distr_portion):
    LocalProcRandGen = np.random.RandomState()
    smps = []
    for i in range(20):       
        smp = LocalProcRandGen.choice(distr_portion, size=10)
        smps.append(smp)
    return np.mean(smps)
```
