### ISSUE TITLE
Wrapped functions have lost inspect.getfullargspec information

### ISSUE THREAD

**Issue by mrocklin** [numpy/numpy#12247]
In master calling `inspect.getfullargspec` on some function now returns only args/kwargs.  I suspect that this is due to the recent `__array_function__` wrapping, though I am not sure.

### Reproducing code example:

```python
import numpy as np       
import inspect       
print(inspect.getfullargspec(np.nansum))
```

```
FullArgSpec(args=[], varargs='args', varkw='kwargs', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})  # version 1.16.0.dev0+db5750f
FullArgSpec(args=['a', 'axis', 'dtype', 'out', 'keepdims'], varargs=None, varkw=None, defaults=(None, None, None, <no value>), kwonlyargs=[], kwonlydefaults=None, annotations={})  # version 1.15.1
```

The `inspect.signature` function seems to work fine.

**Comment by mrocklin** [comment]
cc @shoyer

**Comment by shoyer** [comment]
Yes, see https://github.com/dask/dask/issues/4111 and https://github.com/numpy/numpy/issues/12225

Closing this in favor of https://github.com/numpy/numpy/issues/12225.
