### ISSUE TITLE
Bug in masked array boolean comparison in Numpy 1.15.3

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#12248]
An issue was introduced in Numpy 1.15.3 compared to Numpy 1.15.2 which results in comparisons of masked arrays crashing (this has broken some functionality over at astropy - e.g. https://github.com/astropy/astropy/issues/7943)

This is likely due to https://github.com/numpy/numpy/pull/12237

### Reproducing code example:

**Expected (Numpy 1.15.2)**

```python
>>> (np.ma.array(['A', 'B', 'C'], fill_value='N') == 'A') | (np.ma.array(['A', 'B', 'C'], fill_value='N') == 'A')
masked_array(data=[ True, False, False],
             mask=False,
       fill_value='N')
```

(arguably this was wrong too since fill_value should have been a bool, but at least it didn't crash)

**Actual (Numpy 1.15.3)**:

```python
>>> (np.ma.array(['A', 'B', 'C'], fill_value='N') == 'A') | (np.ma.array(['A', 'B', 'C'], fill_value='N') == 'A')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom/miniconda3/envs/np1153/lib/python3.6/site-packages/numpy/ma/core.py", line 3016, in __array_finalize__
    self._fill_value = _check_fill_value(self._fill_value, self.dtype)
  File "/Users/tom/miniconda3/envs/np1153/lib/python3.6/site-packages/numpy/ma/core.py", line 476, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: invalid literal for int() with base 10: 'N'
```

### Numpy/Python version information:

Python 3.6, Numpy 1.15.3

**Comment by charris** [comment]
Hmm, I'd guess `_check_fill_value` is doing something wrong.

**Comment by charris** [comment]
Shorter test case
```
In [21]: np.ma.array(['A', 'B', 'C'], fill_value='N').astype('?')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
...
```

**Comment by charris** [comment]
I think the bug was already there, we have just exposed it.
```
In [1]: a = np.ma.array(['A', 'B', 'C'], fill_value='N')

In [2]: a == 'A'
Out[2]: 
masked_array(data=[ True, False, False],
             mask=False,
       fill_value='N')

In [3]: np.__version__
Out[3]: '1.15.0'
```

**Comment by charris** [comment]
Which brings up the question, what should the fill value be in that case? It doesn't seem well defined when going from strings to boolean. Maybe the boolean default value?

**Comment by astrofrog** [comment]
@charris - looking into this more I think that technically this is a bug for other types too, not just strings:

```python
>>> a = np.ma.array([1, 2, 3], fill_value=2)
>>> a == 1
masked_array(data=[ True, False, False],
             mask=False,
       fill_value=2)
```

Personally I would say that ``False`` would probably make more sense as a default fill value here, but I don't really have a strong preference.

**Comment by charris** [comment]
I think the problem is actually a bit deeper:
```
In [1]: array('N', dtype='?')
Out[1]: array(True)

In [2]: array('N').astype('?')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-40697cdee1fe> in <module>()
----> 1 array('N').astype('?')

ValueError: invalid literal for int() with base 10: 'N'
```
I think we should be able to assign a truth value to strings in general, Python does.

**Comment by eric-wieser** [comment]
I think we already do? #9875 shows how we do but we probably got it wrong

**Comment by pllim** [comment]
In digging over at Astropy, it seems like Numpy's `set_fill_value()` method for masked array was used, where the default fill value was `None`, which became "N/A" for string array but sometimes also became "N".

```python
>>> import numpy as np
>>> np.__version__
'1.15.3'
>>> x1 = np.ma.array(['A', 'B', 'C'], mask=[True, False, False])
>>> x1
masked_array(data=[--, 'B', 'C'],
             mask=[ True, False, False],
       fill_value='N/A',
            dtype='<U1')
>>> x1 = np.ma.array(['A', 'B', 'C'], mask=[True, False, False], fill_value=False)
masked_array(data=[--, 'B', 'C'],
             mask=[ True, False, False],
       fill_value='F',
            dtype='<U1')
>>> x1.set_fill_value(None)
masked_array(data=[--, 'B', 'C'],
             mask=[ True, False, False],
       fill_value='N',
            dtype='<U1')
```

As a result, using `==` propagates that fill value but now to boolean array.

```python
>>> x1 == 'A'
masked_array(data=[--, False, False],
             mask=[ True, False, False],
       fill_value='N')
```

Which leads to this error when operator is used on multiple comparisons.

```python
>>> (x1 == 'A') | (x1 == 'A')
ValueError: invalid literal for int() with base 10: 'N'
```

So, is the bug in `fill_value` propagation in Numpy? Or are we using it wrong?

**Comment by charris** [comment]
@pllim I have a fix, just need to write tests...

**Comment by astrofrog** [comment]
@charris - thanks!

**Comment by charris** [comment]
May be a while, I'm finding some bizarre behavior with the tests. I'm either confused, or there is a fungus like population of bugs under the forest surface and it has just rained.

**Comment by eric-wieser** [comment]
@charris: I think the latter. `fill_value` has some very weird semantics. Perhaps I didn't convey my skepticism that your seemingly correct fix would preserve the weirdness in that PR. Good luck!

**Comment by charris** [comment]
@eric-wieser It's a Python2 vs Python3 thing, the masked string arrays behave differently in the two cases when indexed. Python3 works as expected...

**Comment by pllim** [comment]
For the record, I was using Python 3.6.

**Comment by charris** [comment]
In particular, in python2 `test = (a[0] == b)` and `test = (b == a[0])` produce different result types for some mask values when `a` and `b` are masked unicode arrays.

**Comment by charris** [comment]
Example Python2 result.
```
In [2]: b = ma.array(['a', 'b'], dtype='U', mask=[1, 0], fill_value='A')

In [3]: u'a' == b
Out[3]: False

In [4]: b == u'a'
Out[4]: 
masked_array(data=[--, False],
             mask=[ True, False],
       fill_value=True)
```

**Comment by charris** [comment]
The (new) bug I am discussing turned up in the new tests and isn't directly relevant to the astropy example, which is fixed.

**Comment by charris** [comment]
However, in Python3, comparing a unicode array with a bytes scalar does not error, and I think it should.
```
In [3]: a = np.array(['a', 'b'], dtype='U')

In [4]: u'a' == a
Out[4]: array([ True, False])

In [5]: b'a' == a
Out[5]: False
```

**Comment by charris** [comment]
And this warning message seems incorrect
```
In [1]: a = np.array(['a', 'b'], dtype='U')

In [2]: 1 == a
/usr/bin/ipython3:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  #!/usr/bin/python3
Out[2]: False
```
Shouldn't it raise an error in the future?

**Comment by charris** [comment]
See #12257.
