### ISSUE TITLE
BUG: clip() does not respect the writeable flag

### ISSUE THREAD

**Issue by mreineck** [numpy/numpy#12242]
### Reproducing code example:

```python
import numpy as np

print (np.version.full_version)

a=np.arange(10)
a_orig=a

a.flags.writeable=False

#np.sin(a,out=a)      # this raises an exception as expected
np.clip(a,1,2,out=a)  # this doesn't
print(a)
print(a is a_orig)
```

### Error message:

There is no error message, but I would expect
`ValueError: output array is read-only`

### Numpy/Python version information:

('1.15.2', '2.7.15+ (default, Aug 31 2018, 11:56:52) \n[GCC 8.2.0]')

**Comment by samyak-jain** [comment]
Hey, I would like to work on this. Would that be ok?

**Comment by charris** [comment]
@samyak-jain You don't need permission, we will merge whoever has the first working fix.

**Comment by WarrenWeckesser** [comment]
`clip` now respects the `writeable` flag of the `out` parameter.  Presumably this was fixed by https://github.com/numpy/numpy/pull/12519.
