### ISSUE TITLE
Should be able to convert string arrays to bool_

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12252]
NumPy can create boolean arrays out of strings, but cannot convert string arrays to bool_. I think we should follow Python here and assign truth values to strings.

### Reproducing code example:

```python
>>> import numpy as np
>>> np.array('N', dtype='?')
array(True)
>>> np.array('N').astype('?')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'N'
```

**Comment by eric-wieser** [comment]
Duplicates #9875, I think

**Comment by mattip** [comment]
Closing as a duplicate of #9875. Please reopen if I misunderstood
