### ISSUE TITLE
ufuncs: warn about leaving values uninitialized

### ISSUE THREAD

**Issue by sk1p** [numpy/numpy#12255]
The [ufunc reference](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html) contains the following notes about `out` and `where` usage:

> If ‘out’ is None (the default), a uninitialized return array is created. The output array is then filled with the results of the ufunc in the places that the broadcast ‘where’ is True. If ‘where’ is the scalar True (the default), then this corresponds to the entire output being filled. **Note that outputs not explicitly filled are left with their uninitialized values.**

and

> Note that if an uninitialized return array is created, values of False will leave those values uninitialized.

I understand why the API is like this, and that there are legitimate use cases that prevent unnecessary initialization. But it would be nice to also have this warning on the specific functions, like [np.divide](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.divide.html) etc. - especially because this is a construct where an innocent looking statement may result in non-deterministic behavior.

Thanks!

**Comment by mattip** [comment]
Duplicate of #12022, fixed by PR #12025 which is waiting for final review

**Comment by sk1p** [comment]
Thanks for letting me know, missed that when looking for duplicates. Good to know it is being worked on!
