### ISSUE TITLE
BUG? hstack/vstack/column_stack no longer accept generators

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#12263]
As reported by @ilayn over in https://github.com/numpy/numpy/issues/12262:

> There are other backwards incompatible changes for hstack and column_stack which were explicitly accepting generator expressions but now they don't.
>
> Xref : scipy/scipy#9405

**Comment by shoyer** [comment]
This is definitely due to my `__array_function__` refactor to add dispatchers to these functions (specifically https://github.com/numpy/numpy/pull/12115). The new dispatcher functions now exhaust the generators before they reach functions.

This is certainly not supported behavior -- the docstrings for these functions describes these parameters as accepting a "sequence of ndarrays" and generators are not sequences.

That said, if scipy relied on this behavior it would be better to handle this change more gracefully. My proposal:
- For now, raise a FutureWarning when passed a generator, as determined by `isinstance(arg, types.GeneratorType)`
- In the future, raise TypeError.

This will result in a small performance penalty, but I don't see any good alternatives. In particular, I don't see any way we could correctly implement these functions with dispatching with support for generator arguments.

**Comment by amueller** [comment]
Scikit-learn relied on this also in many places. Even if it wasn't officially supported I would think a deprecation cycle / FutureWarning would be good. If scipy and scikit-learn rely on it, chances are lots of people were.

**Comment by charris** [comment]
@shoyer That sounds like a good solution to me.

**Comment by tylerjereddy** [comment]
Yeah, sounds sensible given the strong indication of downstream dependency from big projects.

**Comment by ilayn** [comment]
To be honest I don't see the benefit of generators in this context since at some point all elements have to be ... generated and be present in the memory. Thus I would be in favor of deprecating and eventually removing them if they make `__array_function__` perform better which is way more important than this detail.

**Comment by shoyer** [comment]
For scikit-learn, I think they used this just because it looked a little cleaner with two fewer characters, e.g.,
```python
self.rows_ = np.vstack(self.row_labels_ == c
                       for c in range(self.n_clusters))
```
vs
```python
self.rows_ = np.vstack([self.row_labels_ == c
                        for c in range(self.n_clusters)])
```

**Comment by amueller** [comment]
@shoyer that seems a likely explanation and I don't think we actually care.

**Comment by shoyer** [comment]
This is also the cause of test failures for pandas: https://github.com/pandas-dev/pandas/issues/23172
