### ISSUE TITLE
DOC: refactor information in user and reference sections of the docs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#12261]
Our documentation repeats information. The `PyArray_SimpleNew` family of functions is documented both in the [user section](https://docs.scipy.org/doc/numpy-1.15.1/user/c-info.how-to-extend.html#creating-a-brand-new-ndarray) and in the [reference section](https://docs.scipy.org/doc/numpy-1.15.1/reference/c-api.array.html#creating-arrays).

Also, the [distutils section](https://docs.scipy.org/doc/numpy-1.15.1/reference/distutils.html) should be moved to user, not reference, and cleaned up.

See also #12250

**Comment by rgommers** [comment]
> Also, the distutils section should be moved to user, not reference, and cleaned up.

No not that section, that is the reference guide content and is in the right place. I was talking about https://github.com/numpy/numpy/blob/master/doc/DISTUTILS.rst.txt, which is not the same - that's a standalone file now that looks more like user guide material.

**Comment by mattip** [comment]
Closing this, even though the PRs that relate to distutils are not done yet, since the information in the PRs is more extensive than in this issue.
