### ISSUE TITLE
DOC The docstring of numpy.equal is misleading

### ISSUE THREAD

**Issue by albertcthomas** [numpy/numpy#12267]
The [docstring of numpy.equal](https://www.numpy.org/devdocs/reference/generated/numpy.equal.html#numpy-equal) says that the input arrays should be of the same shape. I think this is wrong as broadcasting will be used and no error is returned if you use two input arrays with different shapes.

Besides the second example does not compare two arrays.
```python
>>> np.equal(1, np.ones(1))
array([ True])
```

**Comment by mattip** [comment]
PR welcome. The text comes from `numpy.core._add_newdoc('numpy.core.umath', 'equal'), around line 1068 in `numpy/core/_add_newdocs.py` 

To view the changes, you need to [build the documentation](https://www.numpy.org/devdocs/docs/howto_build_docs.html), I find the easiest way to do this is to create a virtualenv, activate it, then from the top level numpy directory
```
pip install .
(cd doc; make html)
```
The first time you do this, the documentation creation takes quite a while.
