### ISSUE TITLE
ENH: Add support for `np.dtype(ctypes.Union)`

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12273]
This ought to be as simple as constructing a dtype with all the fields overlapping.

This will go in `_dtype_ctypes.py`, and there's a test that needs activating in `test_dtype.py`.

**Comment by euler16** [comment]
Can I work on this @eric-wieser ? Though I would require some guidance on how to work on this since I am begining with Open Source.

**Comment by eric-wieser** [comment]
You'll want to change these lines:

https://github.com/numpy/numpy/blob/44810f07ec6a281d96d6a69c105ce6ae59aec718/numpy/core/_dtype_ctypes.py#L59-L63

Such that this test passes:

https://github.com/numpy/numpy/blob/44810f07ec6a281d96d6a69c105ce6ae59aec718/numpy/core/tests/test_dtype.py#L810-L825

**Comment by bmakos** [comment]
@euler16 - are you still working on this? If not I'd like to do it (I am also new to open source contributions).

**Comment by euler16** [comment]
yes I am, I will send a PR soon

**Comment by eric-wieser** [comment]
@bmakos: If you want to work on something very similar, #10532 is probably only a little more complex

**Comment by bmakos** [comment]
> @bmakos: If you want to work on something very similar, #10532 is probably only a little more complex

Ok, I will take a look, see what I can do. Thank you!

**Comment by eric-wieser** [comment]
@euler16: Are you close? It would be great if this could make it into 1.16 alongside @bmakos' work

**Comment by eric-wieser** [comment]
Milestoned as 1.16 since the release notes added in #12392 claim this is already done!

**Comment by bmakos** [comment]
So this indeed is simple, I wrote the code, but then decided to see how it behaves with a Union containing a packed structure. 

```
>>>class Foo(ctypes.Structure):
    _fields_ = [('one', ctypes.c_uint8.__ctype_be__),('two', ctypes.c_uint32.__ctype_le__)]
    _pack_ = 1
    
>>>class Union(ctypes.Union):
    _fields_ = [
        ('a', ctypes.c_uint8),
        ('b', ctypes.c_uint16),
        ('c', ctypes.c_uint32),
        ('d', Foo),
    ] 
    
>>>ctypes.sizeof(Foo)
5
>>>ctypes.sizeof(Union)
8
```

In my code I constructed the dtype from Union with `itemsize=ctypes.sizeof(Union)))`, which in this case gives size 8, while the correct size in my view would be 5. 

As we are doing this to support ctypes the sensible choice is to still go with `itemsize=ctypes.sizeof(Union)))`, but the ctypes Union constructor may need a fix (I will see how can I open a bug, never did this).

**Comment by eric-wieser** [comment]
> which in this case gives size 8, while the correct size in my view would be 5.

8 is correct - the struct has 3 bytes of padding inserted to meet the alignment requirements of uint32

**Comment by bmakos** [comment]
I see now that if I also make the Union packed to 1 the size is 5. I assumed the rule to calculate the size was to take `sizeof` of the largest member as it is (in this case a packed Structure). Thank you for the clarification.
