### ISSUE TITLE
Ravel method returning copied view of array if order is 'F'

### ISSUE THREAD

**Issue by ShivKJ** [numpy/numpy#12318]
### Reproducing code example:

```python
import numpy as np
x=np.arange(12).reshape((3,4))
y = x.ravel('F')
y[0] = 9999

"The array 'x' is not modified"
```

**Comment by eric-wieser** [comment]
It is not possible to ravel an array which is not-F-contiguous into one that is, without making a copy.

**Comment by ShivKJ** [comment]
Ok.
Please update this info into "ravel" documentation.
Thanks.

**Comment by eric-wieser** [comment]
Can you propose better wording than the existing:

> A copy is made only if needed.

**Comment by ShivKJ** [comment]
It seems a bit more complicated. After diving deep I observe the following considering orders are {'C','F','A','K'}:

There is a flag named "OWNDATA" in numpy array.
If a ravelled array has same memory location as the original array then only OWNDATA is True.

In totality,
there are two cases:
1) If the ravelled array is F-contiguous then it is always the copied view unless the original array is F-contiguous.
2) If the original array is F-contiguous then ravelled array is copied view if it is C-contiguous.
