### ISSUE TITLE
Suggestion to add a warning to a silent failure of dtype conversion using .astype(copy=False) 

### ISSUE THREAD

**Issue by cocoaaa** [numpy/numpy#12323]
Hi, the type conversion of an `ndarray` using `.astype(copy=False)` doesn't have an effect
if the array is not compatible for the type conversion inplace.  This is noted in the documentation, but 
I still think it will be helpful to output a warning when this happens. 

```python
temp = np.random.randint(1,10, size=(2,5),dtype=np.int32)
print(temp.dtype) # int32

temp.astype(np.float, copy=False)
print(temp.dtype) #int32: the requested type conversion is not possible inplace.

# silent fail
# would like to see a warning printed out here.
```
Thanks!

**Comment by seberg** [comment]
Casting is not an in-place operation and copy=False means that no copy is made (if possible). The code thus never makes sense, it always has to be `temp = temp.astype(np.float64, copy=False)`. So frankly, I don't see a warning making much sense. You are just creating a new array which is dereferenced immediately.

**Comment by seberg** [comment]
If you have an idea how it might be made more clear, please do say so. Or ask if you have another question.
