### ISSUE TITLE
Support "Single Index" for matrices or high dimension arrays

### ISSUE THREAD

**Issue by Freakwill** [numpy/numpy#12325]
Support "Single Index" for matrices or high dimension arrays

### Description
For instance, A[2] is the third element counted column-by-column. 
just use A[2, :] to get matrix([[7, 8, 9]]). handle with np.arrry similarly.
Alternatively, use A(2) to avoid of overriding the current method.

```python
import numpy as np
A = np.matrix('1,2,3;4,5,6;7,8,9')
A[2] # => 7 instead of matrix([[7, 8, 9]]), as in matlab
A[5] # => 8
...
```

### Motivation
Sometimes we get `matrix([[7, 8, 9]])` that is 1-dim essentially, but we have to refer to the elements with 2-dim index.

**Comment by seberg** [comment]
There already is `arr.flat` and `arr.index` (which is a bit different). Actually changing the behaviour is not sensible at all.
Also, general piece of advice: Avoid `np.matrix`.
