### ISSUE TITLE
BLD: site.cfg BLAS setup not reliable?

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#12329]
EDIT: OK, most of it was just due to cblas not being compiled in. However, at least for the system libs that should still work. The system has cblas and it should be OK that openblas is not compiled with the cblas interface? The second thing is that `_umath_linalg` and `_multiarray_umath` end up linking different libs if I try to use blis, which seems wrong?.

Old post:

Did not really try to dig into it yet, since I am not much familiar with the build system. Right now, numpy does not seem to build/link correctly on my system (openblas installed), in the sense that:
`/home/sebastian/forks/numpy/build/testenv/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so` does not actually link any BLAS. It used to work just before when we still had the single `multiarray` file.

It works completely fine when I add the openblas section in the site config. I tried also with BLIS, that does not work. The `rpath` is added, but BLIS is not loaded when running. Additionally `_linalg_umath` actually still picks up and links openblas which I guess it should not do?

Anyway, should investigate more/check what exact compilation args are being used that it ends up not linking the libraries. Maybe its also something with my system, but I suspect partially a regression due to the ufunc/multiarray merge, so opening an issue.

**Comment by seberg** [comment]
I guess the fact that `_linalg_umath` is linked like that could be due to LAPACK, but not quite clear about the details right now.

**Comment by seberg** [comment]
This short line, looks like it should be linking (skipped most `.o` files)?:
```gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=4 -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Werror=declaration-after-statement -Werror=vla -Werror=nonnull -Werror=pointer-arith -Wlogical-op -Werror=unused-function build/temp.linux-x86_64-3.7/numpy/core/src/multiarray/alloc.o <skip> -L/home/sebastian/blis/lib -L/usr/lib -Lbuild/temp.linux-x86_64-3.7 -Wl,--enable-new-dtags,-R/home/sebastian/blis/lib -lnpymath -lnpysort -lblis -lblis -lm -lpython3.7m -o build/lib.linux-x86_64-3.7/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so```

The result ldd is:
```bash
 % ldd build/lib.linux-x86_64-3.7/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd0e1fe000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fa120dfd000)
	libpython3.7m.so.1.0 => /usr/lib/libpython3.7m.so.1.0 (0x00007fa120a84000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fa120a63000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fa12089f000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007fa12134a000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fa12089a000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007fa120895000)
```

**Comment by seberg** [comment]
Oh, my blis was compiled without the cblas interface, same for the system openblas. But before numpy would link cblas for the system one at least.

**Comment by seberg** [comment]
Starting to semi understand the distutils stuff. What I find a bit strange is that things seemed to have changed when nothing changed in distutils. But maybe my system also just changed and `libopenblas` did not exist before under that name. Don't think I will try to dig much deeper here, at least for now. If this behaviour is expected, feel free to close, if its worth to investigate something, I will do that of course.

**Comment by seberg** [comment]
So maybe someone with knowledge about this has a bit of time to give me a hint on this. I still always need to use a `site.cfg` to compile on my computer.

I have openblas, but the system provided one is compiled without cblas, instead there is a dedicated `libcblas.so` which links with `libblas.so` (which is just `libopenblas.so`). I think this is a typical setup on many linux machines. Is there an easy way to make it notice that openblas is actually not the right target when it does not include the cblas symbols?

**Comment by rgommers** [comment]
> Is there an easy way to make it notice that openblas is actually not the right target when it does not include the cblas symbols?

This kind of thing will have clear configure stage output with Meson. 

Nothing else is going to change here anymore, so closing. Thanks @seberg
