### ISSUE TITLE
default behavior of array of infs divided by self [np.full((2,),np.inf)/np.full((2,),np.inf)] should be "Raise," not "warn"

### ISSUE THREAD

**Issue by neonb88** [numpy/numpy#12345]
In pure python, when I divide by zero, code execution immediately halts and gives me a line number.  In numpy, the default behavior (at least for me) is to give me this: `__divide_err__.py:8: RuntimeWarning: invalid value encountered in divide
`, and this warning got lost in the weeds of my debug statements.  I would prefer if numpy's default behavior was to "Raise" rather than "Warn."  This default value cost me hours of productivity, and I imagine future numpy noobs may also encounter frustration thanks to this confusion if it is not changed

### Reproducing code example:

import numpy as np

```python
import numpy as np
dir_vect  = np.zeros(3).astype('float64')
print dir_vect/dir_vect
print "this line would not execute if divide-by-zero behavior was consistent between pure python and numpy"
```

### Error message:

__divide_err__.py:8: RuntimeWarning: invalid value encountered in divide
  print dir_vect/dir_vect
[nan nan nan]
this line would not execute if divide-by-zero behavior was consistent between pure python and numpy

### Numpy/Python version information:

python version: 2.7.15
numpy version:  1.14.5

**Comment by seberg** [comment]
Closing, this is configurable with `np.errstate` and a deliberate choice.
