### ISSUE TITLE
Set Cython 'language_level` directive after 1.16 release.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12356]
FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2).

The directive needs to be in the `*.pyx` files.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by sethtroisi** [comment]
I suspect this was handled by adding "-3" to [cythonize.py](https://github.com/numpy/numpy/blame/master/tools/cythonize.py#L53) in #13163? or by using the new version of Cython.

**Comment by rgommers** [comment]
indeed, thanks @sethtroisi
