### ISSUE TITLE
REL: mailmap entries for 1.16

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12360]
The following folks need a name and email address for inclusion in the list of NumPy 1.16.0 contributers.

- [x] @attack68
- [x] @cclauss
- [ ] @lerbuke
- [x] @logeaux
- [x] @silenc3r
- [x] @tteichmann

Could you please comment on this issue with that information so that the numpy mailmap can be updated?

**Comment by cclauss** [comment]
Christian Clauss

**Comment by logeaux** [comment]
Alan Fontenot
logeaux@yahoo.com

**Comment by silenc3r** [comment]
Dawid Zych
dawid.zych@yandex.com

**Comment by tteichmann** [comment]
Tim Teichmann
t.teichmann@dashdos.com

**Comment by attack68** [comment]
john darbyshire

**Comment by charris** [comment]
Thanks all.
