### ISSUE TITLE
DOC: numpy.arcsin(x, /, out=None, *,  ...

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#12393]
What do the "/" and "*" mean in the documentation of numpy.arcsin and many similar functions?

> numpy.arcsin(x, /, out=None, *,  ...
> numpy.arctan(x, /, out=None, *,  ...

**Comment by charris** [comment]
See PEP 457

```
def name(positional_only_parameters, /, positional_or_keyword_parameters,
         *, keyword_only_parameters):
```
Keyword_only is new in Python 3. I don't know if the `/` syntax is supported yet, but it serves for documentation purposes.

**Comment by mattip** [comment]
Informational, no action needed. Closing.
