### ISSUE TITLE
gfortran needs "-maix64" flag for 64bit python in AIX

### ISSUE THREAD

**Issue by ayappanec** [numpy/numpy#12396]
We are building scipy in AIX OS with python3. 
We have both 32bit and 64bit version of python3 shipping with python3 rpm from IBM AIX Toolbox. And 64bit version is the default. 
In AIX, one has to always pass the gcc/g++/gfortran flag "-maix64" for 64bit build. If this option is not passed, the resulting object files will be 32bit. 
While building scipy, this flag "-maix64" is getting passed for c & c++ code compilation (through the sysconfigdata file) but not for fortran code. And because of this 64bit compilation is failing. 
To fix that , i have to manually export FFLAGS="-maix64" and edit the below file to pass the flag for shared library creation.
```
--- site-packages/numpy/distutils/fcompiler/gnu.py_orig 2018-11-13 04:24:10 +0000
+++ site-packages/numpy/distutils/fcompiler/gnu.py      2018-11-13 05:13:46 +0000
@@ -294,7 +294,7 @@
                           "-fno-second-underscore"] + _EXTRAFLAGS,
         'compiler_fix' : [None, "-Wall",  "-g","-ffixed-form",
                           "-fno-second-underscore"] + _EXTRAFLAGS,
-        'linker_so'    : ["<F90>", "-Wall", "-g"],
+        'linker_so'    : ["<F90>", "-Wall", "-g", "-maix64"],
         'archiver'     : ["ar", "-cr"],
         'ranlib'       : ["ranlib"],
         'linker_exe'   : [None, "-Wall"]
```
I think we can make numpy handle this situation by including this flag "-maix64" based whether it's 64bit or 32bit python in AIX (using something like  platform.architecture() which outputs ('64bit', 'COFF') in AIX)

**Comment by rgommers** [comment]
That sounds like a good idea. Could you either send this as a PR, or propose the exact line to check? E.g. is this correct?

    if sys.platform[:3] == 'aix' and platform.architecture()[0][:2] == '64':
        linker_so.append('maix64')

**Comment by ayappanec** [comment]
This is fine except that it should be "-maix64" rather than "maix64". 

And also there is an error while building the _quadpack.so library in scipy.

/opt/freeware/lib/python3.6/config/ld_so_aix /opt/freeware/bin/gfortran -Wall -g -maix64 -bI:/opt/freeware/lib/python3.6/config/python.exp -Wall -g -maix64 -shared build/temp.aix-7.2-3.6/scipy/integrate/_quadpackmodule.o -L/opt/freeware/lib -L/opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8.1.0/ppc64 -L/opt/freeware/lib64 -Lbuild/temp.aix-7.2-3.6 -lquadpack -lmach -llapack -llapack -lblas -lblas -lgfortran -o build/lib.aix-7.2-3.6/scipy/integrate/_quadpack.so
ld: 0711-317 ERROR: Undefined symbol: __tls_get_addr
collect2: error: ld returned 8 exit status

____tls_get_addr in AIX comes from libpthread unlike in linux where it comes from GLIBC. 
export LDFLAGS="-lpthread" and triggering the build again fixes this issue. 

I am not very familiar with the code here, just learning it now. So it's better you guys can make the relevant changes and that way we won't get any regression.

**Comment by ayappanec** [comment]
So there are 3 things to take care of.
1) Adding "-maix64" to the FFLAGS
2) Adding "-lpthread" to the LDFLAGS
3) Adding "-maix64" to the linker_so
