### ISSUE TITLE
The matrix multiplied by its own inverse is not equal to the identity matrix

### ISSUE THREAD

**Issue by youngseaz** [numpy/numpy#12397]
### Reproducing code example

```python
# coding:utf-8
import numpy as np


def rand_matrix(m, n):
    temp = np.random.randint(m, n, [3, 3])
    return np.mat(temp)


def inversion(m, n):
    temp = rand_matrix(m, n)
    print("random matrix is:\n ", temp)
    try:
        output = temp.I
        print("random matrix's inversion is:\n", output)
        print(np.dot(temp, output))
        return output
    except np.linalg.linalg.LinAlgError as err:
        print("the matrix is singular matrix which inversion doesn't exist")


inversion(1, 20)

```

### result:

![example](http://youngseaz.com/p.png)
I run the code several times. The result of running the code was similar to the screenshot. The code produces a random 3*3 matrix named temp, then calculates the inverse of the random matrix. Finally, I called numpy.dot() for examination. But the result exceeding my expectations, the result wasn't  identity matrix

### Numpy/Python version information: 
Python --version 3.6.3
numpy --version 1.13.3

**Comment by charris** [comment]
Close enough for numerical work. Floating point arithmetic is not exact and the error here is about 1/2 ULP relative to 1, which is pretty good.
