### ISSUE TITLE
Using `.astype('datetime64[7D]')` unexpectedly changes dates

### ISSUE THREAD

**Issue by jwdink** [numpy/numpy#12404]
I'm trying to use numpy's dtype meta-data for arrays of date-times to signal the frequency of the data. For weekly data, I'm getting unexpected behavior: for an array of dates (with zeros for time-data), converting to '7D' type changes the dates to the nearest Thursdays. This behavior seems fair enough for converting to 'W', but doesn't make sense for '7D'.

### Reproducing code example:

```python
import numpy as np
import pandas as pd # for weekday name

datetimes = np.array(['2012-04-30', '2012-08-06', '2012-04-30', '2012-04-30',  '2012-04-30'], dtype='datetime64[ns]')

print(pd.Series(datetimes).dt.day_name().unique())
# > ['Monday'] # all mondays

print(pd.Series(datetimes.astype('datetime64[W]')).dt.day_name().unique())
# > ['Thursday'] # that's fair enough, the 'W' format isn't specific enough

print(pd.Series(datetimes.astype('datetime64[7D]')).dt.day_name().unique())
# > ['Thursday'] # but why would the 7D format change the dates?
```

### Numpy/Python version information:

```
1.14.2 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by jwdink** [comment]
I see-- the assumption is that we always want to floor the datetime so that it's an even count from the unix epoch. So there's no way to specify the "start" datetime when using a number in front of the datetime-unit? E.g., if I wanted to count weeks starting on Monday.

**Comment by eric-wieser** [comment]
I'd recommend you store the start date in a `datetime64[D]`, and then store offsets in a `timedelta64[W]`
