### ISSUE TITLE
AssertionError: Some doctests failed: Expected: 3.0 Got: 3e+00 in numpy.test() on 1.15.4 on Python 3.7.1 

### ISSUE THREAD

**Issue by novosirj** [numpy/numpy#12406]
Recently build Python 3.7.1 and NumPy from source, NumPy with the Intel Composer XE 2018 update 4 (18.0.5) compiler to take advantage of Intel MKL and the compiler optimizations, with instructions from Intel. I say that for the sake of completeness -- I lean towards it not being relevant here. Seeing an error in the test phase.

### Reproducing code example:

```python3
import numpy
numpy.test()
```

### Error message:

This seems somewhat harmless, but errors out:

```E           AssertionError: Some doctests failed:
E           **********************************************************************
E           File "/opt/sw/packages/gcc-4_8/python/3.7.1/lib/python3.7/site-packages/numpy-1.15.4-py3.7-linux-x86_64.egg/numpy/lib/tests/test_polynomial.py", line 21, in test_polynomial
E           Failed example:
E               p(0)
E           Expected:
E               3.0
E           Got:
E               3e+00
```

This does not happen on my _previous_ installation, which is NumPy 1.11.3 with Python 3.5.2.

### Numpy/Python version information:

>>> print(numpy.__version__,sys.version)
1.15.4 3.7.1 (default, Nov 14 2018, 16:33:36) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

**Comment by pistack** [comment]
I got same bug too, with intel compiler xe 2019.1.144 and python 2.7, 3.6.6 and 3.6.7

**Comment by charris** [comment]
Don't worry, the doctests have been changed to standard testing in 1.16 so this test doesn't exist anymore.  One of the reasons for the change was the dependence of doctests on how numbers were printed. Haven't seen this particular problem before, might be Python related or might be on account to switching to pytest, but in any case it should be gone in the next release.

**Comment by charris** [comment]
I'm going to leave this open for a while as it might be Python 3.7.1 related and there may be more reports.

**Comment by bsipocz** [comment]
I propose to close this now, quite some time has passed and I suppose there won't be more reports coming. 
Please reopen if it pops up again.
