### ISSUE TITLE
Make CI fail if a MismatchCAPIWarning is emitted at build time

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12415]
Raised in #12412

**Comment by rgommers** [comment]
This was done quite a while ago I believe. 

In `numpy/core/meson.build`:
```meson
# Check whether we have a mismatch between the set C API VERSION and the
# actual C API VERSION. Will raise a MismatchCAPIError if so.
r = run_command(
  'code_generators/verify_c_api_version.py', '--api-version', C_API_VERSION,
  check: true
)
```
And `numpy/core/code_generators/verify_c_api_version.py` seems to always raise an exception if a mismatch is detected. Hence closing. Thanks Eric.
