### ISSUE TITLE
MismatchCAPIWarning during build

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12412]
Something we might want to deal with before 1.16:

> numpy\core\setup.py:400: MismatchCAPIWarning: API mismatch detected, the C API version numbers have to be updated. Current C api version is 13, with checksum 5b0e8bbded00b166125974fc71e80a33, but recorded checksum for C API version 13 in codegen_dir/cversions.txt is a1bc756c5782853ec2e3616cf66869d8. If functions were added in the C API, you have to update C_API_VERSION  in numpy\core\setup_common.py.

The build continues despite this warning, so it's possible we just didn't notice it. This is likely my fault as part of #8955

**Comment by charris** [comment]
Updated in #12414.
