### ISSUE TITLE
subtract operation makes the program hang

### ISSUE THREAD

**Issue by luyiming** [numpy/numpy#12423]
This is a really strange bug. When processing some **specific** image with **(224, 224)** size. The subtract operation `(img/128)-1` hangs the program. I cannot stop the program using Ctrl+c. The system monitor shows that the python interpreter using 100% CPU. 

`np.subtract(img/128, 1)` sometimes hang the program, sometimes not. I'm struggling in this problem for an hour and I can't say for sure in which circumstances `np.subtract(img/128, 1)` would not hang.

```python
from keras.preprocessing import image
import numpy as np

img = image.load_img('specific_image.png', target_size=(224, 224))
img = np.asarray(img)
x = img / 128 -  1   # <---- The program hangs here
```

### Error message:

![](https://i.snag.gy/ujYtfT.jpg)

### Numpy/Python version information:

keras version: 2.2.4
numpy version: 1.14.3
python version: 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

P.S. I'm using Anaconda 3.2.0 and install the packages using `conda install keras`.

**Comment by luyiming** [comment]
The image is here:
https://drive.google.com/file/d/1IyRJFdPWRgsMHli5Vs6o650nyYYMVmTB/view?usp=sharing

```
MD5 (image.png) = 3bef00894c615654d12e0d47eb7daf09
```

**Comment by seberg** [comment]
Never used keras really. I assume you know that `img` is really a `(224, 224)` or maybe `(224, 224, 3)` array and nothing weird?
It sounds a bit like gh-12350 which was also on a Mac I think and occasionally timed extremely slow (for the problem size).

Would be interesting if someone on a mac can run some profiling tool or so to see where it hangs. Is it related to specific array sizes?

@luyiming could you test it with a random array (or so) of similar parameters, the `keras` dependency is not nice. Also, probably not the case for you or best way to check but can you say if your numpy version has `np.random_intel` or `np.erf` defined? (it is just that there are patched numpy versions from Intel, and if yours is one we may have to push it to Intel)

**Comment by luyiming** [comment]
I think this problem is related to Keras. The image size and image content are not the key. I tried a few other images and image sizes, the program hangs anyway. But when I use `imageio.imread()` to load the image, everything is fine. 
Now I switched to `python=3.6.7, numpy=1.15.4` and the problem is solved.
Still curious why Keras could affect the numpy behavior.

**Comment by seberg** [comment]
@luyiming what does `img.flags`, `img.strides`, `img.dtype` give you after loading it with keras (and converting it to a numpy array)? Oh, and maybe also `img.__array_interface__` just to be sure we have everything.

**Comment by luyiming** [comment]
After I upgraded the python, I cannot reproduce that bug anymore...
