### ISSUE TITLE
format_float_positional with trim='-' leaves trailing decimal point

### ISSUE THREAD

**Issue by bmerry** [numpy/numpy#12441]
When using `format_float_positional` with `trim='-'`, the documentation says it will remove a trailing decimal point, but it does not always do so.

### Reproducing code example:

```python
import numpy as np
print(np.format_float_positional(1e-10, precision=5, trim='-'))
```

This outputs `0.` rather than `0`. Using `0` as input instead of `1e-10` produces the expected output.

### Numpy/Python version information:

1.15.4 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]

**Comment by corneliusroemer** [comment]
Wow, I'm surprised no one has commented on this bug yet. I was about to open the issue myself only to discover that it's been an open issue for 3 years!

I'll submit a PR to fix this, should be easy.
