### ISSUE TITLE
stack with an empty matrix

### ISSUE THREAD

**Issue by Freakwill** [numpy/numpy#12453]
Redefine stack functions, when stacked with an empty matrix, it equals to itself.

```python
import numpy as np
np.vstack(([], A)) == np.hstack(([], A)) == A  (== np.concatenate(([], A)))
```
```
# pseudo code
A = array([])
for-loop
    A1 = ...
    if A is empty
        A = A1
    else
        stack A on A1
```
Otherwise, I have to define a m*n empty matrix before stacking, or use if-statement to define A.

**Comment by eric-wieser** [comment]
`[]` is not really a matrix, it's a (0,)-array.

Can you be more clear what you're requesting here?

What shape is `A`?

Are you asking about `vstack` or `stack`, which are different in a lot of ways?

**Comment by eric-wieser** [comment]
The trick is to initialize A as `np.zeros((0, 3))` when concatenating on
axis 0 (vstack) and `np.zeros((2, 0))` when concatenating on axis 1.

Unlike the approach you're proposing, this also produces correct results if
the loop never runs.

On Tuesday, November 27, 2018, William Song <notifications@github.com>
wrote:
> [] is not really a matrix, it's a (0,)-array.
>
> Can you be more clear what you're requesting here?
>
> What shape is A?
>
> Are you asking about vstack or stack, which are different in a lot of
ways?
>
> # example code
> A = np.array([])
> for k in range(10):
> A1 = np.zeros((2,3))
> if k==0:
> A = A1
> else
> A = np.vstack((A, A1)) # or hstack
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/Z2vWb06OKEihlslY0TdTWwPEPifXJoTfn0-BAoCRdcE6-F52w0IkXAXs2xMcZOEZGAQIl51sEmsMka-kKAcqccM4SfVP1Tw7FX3UpDil3-ssSZtIrKeExFqNQ8tCtys6x7akKfl9KNXAhO9i8zfY9TAERQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAZ9LFfB2im1hqyBRXcGHyF43aBfwFVvks5uzhBVgaJpZM4YyXvV.gif
>

**Comment by Freakwill** [comment]
> The trick is to initialize A as `np.zeros((0, 3))` when concatenating on axis 0 (vstack) and `np.zeros((2, 0))` when concatenating on axis 1. Unlike the approach you're proposing, this also produces correct results if the loop never runs.
> On Tuesday, November 27, 2018, William Song ***@***.***> wrote: [] is not really a matrix, it's a (0,)-array. Can you be more clear what you're requesting here? What shape is A? Are you asking about vstack or stack, which are different in a lot of
> ways?
> # example code A = np.array([]) for k in range(10): A1 = np.zeros((2,3)) if k==0: A = A1 else A = np.vstack((A, A1)) # or hstack — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.<
> https://ci3.googleusercontent.com/proxy/Z2vWb06OKEihlslY0TdTWwPEPifXJoTfn0-BAoCRdcE6-F52w0IkXAXs2xMcZOEZGAQIl51sEmsMka-kKAcqccM4SfVP1Tw7FX3UpDil3-ssSZtIrKeExFqNQ8tCtys6x7akKfl9KNXAhO9i8zfY9TAERQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAZ9LFfB2im1hqyBRXcGHyF43aBfwFVvks5uzhBVgaJpZM4YyXvV.gif
> […](#)

It is a good but not perfect trick. Since the size of `A1` might be changed dynamically, for example it is read from any .xls file by pandas. In this case, it is troublesome. And my request is reasonable and pythonic. So dose Matlab.

**Comment by eric-wieser** [comment]
> And my request is reasonable and pythonic. So dose Matlab.

In my experience, the fact that matlab does something is more often than not an argument that it is _not_ pythonic...

Can you give a concrete example of where the trick above doesn't work?

I think your argument is similar to saying that for the following code, python should let you do `str + 0 == str`, so that you get `"cba"` in the second case.
```python
def reverse_sum(x):
    ret = 0
    for xi in x:
        ret = xi + ret

reverse_sum([1, 2, 3])  # 6
reverse_sum(["a", "b", "c"])  # error
```
Just like being sloppy with types is generally a bad idea, being sloppy with shapes in numpy is also a bad idea.

**Comment by Freakwill** [comment]
Your argument is persuasive. Thank you.
