### ISSUE TITLE
Possible disambiguity in documentation/ Suggestion

### ISSUE THREAD

**Issue by neyuru** [numpy/numpy#12452]
When running the tests the output is a little ambiguous. As stated in issue [#12450](https://github.com/numpy/numpy/issues/12450), running

```import numpy
numpy.test('full')
```

gives the impression (to a newcomer) of 9 tests failing:

````
4686 passed, 362 skipped, 9 xfailed, 5 warnings in 213.99 seconds
True
````

So a suggestion is to change the output to be less ambiguous, in particular for the "xfailed". Thanks!

**Comment by bmakos** [comment]
I am not sure I agree. Knowing how pytest uses xfail, this message is clear to me. See the documentation for [pytest](https://docs.pytest.org/en/latest/skipping.html). 

> A xfail means that you expect a test to fail for some reason. A common example is a test for a feature not yet implemented, or a bug not yet fixed. When a test passes despite being expected to fail (marked with pytest.mark.xfail), it’s an xpass and will be reported in the test summary.

Those 9 tests actually do fail, so the impression you have is correct. Should you worry - probably not, it also means that they are expected to fail.

**Comment by seberg** [comment]
I agree with the sentiment, but I do not think it is anything to do with numpy. Maybe pytest could print an additional line saying that htings were successfull, but I don't think we should patch it here.

However, if some user guide tells you to run the tests, it could show an example output line for a successful test or so.

**Comment by mattip** [comment]
closing,  #13216 added the suggested output line
