### ISSUE TITLE
Ragged array creation works on Windows, fails on Linux

### ISSUE THREAD

**Issue by eackermann** [numpy/numpy#12468]
I am trying to create a ragged array. I get a ValueError in Linux, using numpy versions 1.11.3 and 1.13.3. However, it works on Windows, with numpy version 1.11.3.

I have not been able to get it to work on Linux yet, but do have (and included below) a workaround.

### Reproducing code example:

```python
import numpy as np

# fails:
arr = np.array([np.zeros((2,3)), np.zeros((2,4))], dtype=np.object)

# works:
arr = np.array([np.zeros((5,3)), np.zeros((2,4))], dtype=np.object)
arr[0] = np.zeros((2,3))
```

### Error message:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-273-0dde62aac73b> in <module>()
----> 1 np.array([np.zeros((2,3)), np.zeros((2,4))], dtype=np.object)
```

### Numpy/Python version information:

Fails on Linux, with numpy 1.11.3 and 1.13.3
Works on Windows, with numpy 1.11.3

**Comment by sturlamolden** [comment]
I am not sure that code is even supposed to work. ```np.array``` is a smart routine, but it cannot read your mind. It gets confused when you nest lists and ndarrays, which are both iterables. 

Personally I find I have no or very little use for "ragged arrays". Cases for ragged arrays are nearly always better solved by keeping a list of ndarrays. 

However, if you really want to create a ragged array, then do it in multiple steps so NumPy understands what you want:

```Python
arr = np.array(10*[None])
for i in arr.shape[0]: arr[i] = np.zeros(30)
arr[0] = np.zeros(50)
```

**Comment by seberg** [comment]
Related to gh-19470 and others.  I am going to close this, 1.13 is pretty old and I expect this is consistent now, if it was inconsistent before.
