### ISSUE TITLE
FFT2 incorrect results for Fortran ordered 3D data

### ISSUE THREAD

**Issue by rth** [numpy/numpy#12460]
FFT2 produces incorrect results for Fortran ordered 3D data

### Example

```python
>>> import numpy as np
>>> rng = np.random.RandomState(42)
>>> X_c = rng.rand(1024, 1024, 1).astype(np.complex128)
>>> X_f = X_c.astype(X_c.dtype, order='F')

>>> np.abs(np.fft.fft2(X_c, axes=(0, 1))).max()
524563.6580112983  # expected (correct) value
>>> np.abs(np.fft.fft2(X_f, axes=(0, 1))).max()
8.430870870125293e+295 # incorrect value for Fortran ordered data
>>> np.abs(np.fft.fft2(X_f[:, :, 0], axes=(0, 1))).max()
524563.6580112983  # passing a 2D slice,  Fortran ordered works.
```

### Numpy/Python version information:

Python 3.6, Linux, numpy 1.15.4  (from the default conda channel).

This particular example works as expected with `fft2` from scipy 1.1.0.

I'm not sure if https://github.com/numpy/numpy/pull/11888 would help with this.

**Comment by rth** [comment]
Nevermind, this is a `mkl_fft` issue and it appears that on the default conda channel numpy is now patched to use `mkl_fft` (which used to happen only on the intel conda channel).

Steps to reproduce,
```py
$ conda create -n test-env numpy python=3.7
[..]
$ conda activate test-env
$ python -c 'import numpy as np; print(np.fft.__file__)'                                               
/home/rth/.miniconda3/envs/test-env/lib/python3.7/site-packages/numpy/fft/__init__.py
$ head -n 20 /home/rth/.miniconda3/envs/test-env/lib/python3.7/site-packages/numpy/fft/__init__.py
from __future__ import division, absolute_import, print_function

# To get sub-modules
from .info import __doc__

from .fftpack import *
from .helper import *

from numpy.testing._private.pytesttester import PytestTester
test = PytestTester(__name__)
del PytestTester


try:
    import mkl_fft._numpy_fft as _nfft
    patch_fft = True
    __patched_functions__ = _nfft.__all__
except ImportError:
    patch_fft = False
```

I find this worriesome.

**Comment by rth** [comment]
Opened https://github.com/IntelPython/mkl_fft/issues/29

Saw earlier discussion about this in https://github.com/numpy/numpy/issues/11241, https://github.com/numpy/numpy/issues/11456

Just curious was there some discussion with numpy developpers about the inclusion of mkl_fft in numpy on the default conda channel? or is this purely a decision at the distribution level?

Because patching the code in some undocumented ways and advertising it as "numpy" doesn't sound great.

**Comment by grlee77** [comment]
mkl_fft has caused some issues in running the numpy interface tests for pyFFTW in the past as well due to the differences in supported precisions. [Our workaround in the test suite](https://github.com/pyFFTW/pyFFTW/blob/5bf1dda837dcef722ee14b349834a701e4d53592/test/test_pyfftw_base.py#L42-L47) was to import fft routines directly from `numpy.fft.fftpack` instead of the base `numpy.fft` location to bypass `mkl_fft`.  This approach is not very future-proof however, as #11888 would change the FFT backend from fftpack to pocketfft.

**Comment by seberg** [comment]
Even if it is not a numpy bug, it would still be nice to add a test to the numpy test suit to close this.

**Comment by rgommers** [comment]
> This approach is not very future-proof however, as #11888 would change the FFT backend from fftpack to pocketfft.

Looks like there's nothing we can do there to avoid some work in pyfftw, because we want to remove all of fftpack. But after that, we'd like to implement a proper backend system to select implementations, to avoid this kind of problem.

**Comment by oleksandr-pavlyk** [comment]
The issue was resolved in mkl_fft 1.0.10 as per https://github.com/IntelPython/mkl_fft/issues/29 in https://github.com/IntelPython/mkl_fft/pull/30. 

Please close this issue.

**Comment by oleksandr-pavlyk** [comment]
Perhaps this test can be adapted:

```python

reps_64 = (2**11)*np.finfo(np.float64).eps
reps_32 = (2**11)*np.finfo(np.float32).eps
atol_64 = (2**8)*np.finfo(np.float64).eps
atol_32 = (2**8)*np.finfo(np.float32).eps

def _get_rtol_atol(x):
    dt = x.dtype
    if dt == np.double or dt == np.complex128:
        return reps_64, atol_64
    elif dt == np.single or dt == np.complex64:
        return reps_32, atol_32
    else:
        assert (dt == np.double or dt == np.complex128 or dt == np.single or dt == np.complex64), "Unexpected dtype {}".format(dt)
        return reps_64, atol_64

class Test_Regressions(TestCase):

    def setUp(self):
        rnd.seed(123456)
        self.ad = rnd.randn(32, 17, 23)
        self.af = self.ad.astype(np.float32)
        self.az = rnd.randn(32, 17, 23*2).view(np.complex128)
        self.ac = self.az.astype(np.complex64)

    def test_cf_contig(self):
        """fft of F-contiguous array is the same as of C-contiguous with same data"""
        for ar in [self.ad, self.af, self.az, self.ac]:
            r_tol, a_tol = _get_rtol_atol(ar)
            d_ccont = ar.copy()
            d_fcont = np.asfortranarray(d_ccont)
            for a in range(ar.ndim):
                f1 = mkl_fft.fft(d_ccont, axis=a)
                f2 = mkl_fft.fft(d_fcont, axis=a)
                assert_allclose(f1, f2, rtol=r_tol, atol=a_tol)
```

**Comment by rth** [comment]
Thanks @oleksandr-pavlyk ! Made a PR with a non regression test in #12702.
