### ISSUE TITLE
Build OpenBLAS 3.4.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12478]
OpenBLAS 3.4 has been released: https://github.com/xianyi/OpenBLAS/releases.

@matthew-brett, @tylerjereddy We need to try building the library for testing. What would be the best way to go about that? When that is done, and if the tests pass, then we can close #12394

**Comment by matthew-brett** [comment]
I just triggered a build : https://github.com/MacPython/openblas-libs/commit/592faed28c77f06baaf8427bb85007a5a5f5e885 - let's see what happens.  The Windows builds take 90 minutes or so to filter through, if they work.

**Comment by matthew-brett** [comment]
After a fix from the OpenBLAS team, I think all builds are working.

Uploaded at https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/

With build fix, but otherwise 0.3.4:

openblas-v0.3.3-186-g701ea883-macosx_10_9_i386-gf_1becaaa.tar.gz
openblas-v0.3.3-186-g701ea883-macosx_10_9_x86_64-gf_1becaaa.tar.gz
openblas-v0.3.3-186-g701ea883-manylinux1_i686.tar.gz
openblas-v0.3.3-186-g701ea883-manylinux1_x86_64.tar.gz

Windows didn't need the build fix, so these should be OK:

openblas-v0.3.4-win32-gcc_7_1_0.zip
openblas-v0.3.4-win_amd64-gcc_7_1_0.zip

New Windows builds with build fix commits currently running.

**Comment by charris** [comment]
Matthew, that was fast, thanks. I think we can go ahead with that, and if v0.3.5 comes out during the release cycle, we can go with that.

Running numpy-wheels test at the moment. I used
```
# Environment variables for build
OPENBLAS_VERSION="v0.3.3-186-g701ea883"
MACOSX_DEPLOYMENT_TARGET=10.9
```
I guess 10.9 is good for all later OS X?

**Comment by matthew-brett** [comment]
Yes, 10.9 is good for all later ...

**Comment by charris** [comment]
I'm getting a strange tar error on the Mac, see https://travis-ci.org/MacPython/numpy-wheels/jobs/462932584.

**Comment by charris** [comment]
I'm guessing that the wrong archive name is generated for the openblas library.

**Comment by tylerjereddy** [comment]
Yeah, I think we'll need to bump the version of the osx image we use soon. I mentioned that this weekend during the meeting.

I'm slightly concerned that we may have to just remove / override the `brew` commands using in multibuild because they may actually behave differently / no longer error when we bump the version, but I guess we'll see what happens in a few weeks.

**Comment by tylerjereddy** [comment]
If you check the output log carefully I think you'll find that there are actually some homebrew commands / issues in there, even though we're actually using a tarball / custom binary build to install openblas for wheel builds. I suspect there's not much point in calling those brew commands anymore, but I can take a closer look tomorrow.

**Comment by charris** [comment]
The Mac libraries download and unpack just fine here, so the archives are probably good. So maybe it is the name...

**Comment by matthew-brett** [comment]
Yes, sorry, I should refactor that - it's expecting a fused binary library,
for Mac, that I didn't get round to generating.

I'll do it now - see scripts/fuse_openblas.py in the openblas-libs
repository.

We should probably drop these fused builds soon.  Scipy already has dropped
them.

**Comment by charris** [comment]
We stopped supporting the i386 wheels a while ago, what do we need to do to finish the job?

**Comment by matthew-brett** [comment]
We should download only the 64-bit OpenBLAS archive, and link only against that.  That will require some changes to the `gfortran-install` submodule. Maybe we should modify the architecture compilation flags for Mac, these will be dual-architecture by default from the Python.org Python.  We need to turn off 32-bit tests.

Meanwhile - fusing the binaries failed, the 64-bit archive appears to be dual architecture.  I don't know why, maybe some change to the OpenBLAS build configuration (in OpenBLAS).   I suspect it's not fully dual arch, but we'll see, because I've just copied the 64-bit archive for now, to what I think is the correct name, and uploaded that:

<https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/openblas-v0.3.3-186-g701ea883-macosx_10_9_intel-gf_1becaaa.tar.gz>

Try triggering the build again?

**Comment by matthew-brett** [comment]
I don't understand the XCode complaint by Travis-CI, we aren't setting the xcode image in the `.travis.yml` file, as far as I can see.  I think that means we just get the default image.

**Comment by charris** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Xcode#Version_comparison_table ) says XCode 7.0 requires OS X 10.10.4 minimum. Not sure what that means, actually.

**Comment by matthew-brett** [comment]
That's only the operating system that the XCode version requires.  All we need is that the XCode version can compile for the 10.9 SDK.

**Comment by charris** [comment]
Reran the Mac builds, looks like the build did OK, but:
```
Successfully installed numpy-1.16.0.dev0+55bbfaf
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/travis/build/MacPython/numpy-wheels/venv/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/travis/build/MacPython/numpy-wheels/venv/lib/python2.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 
```

**Comment by charris** [comment]
Should I just retrigger the whole thing?

**Comment by matthew-brett** [comment]
Maybe just the 32-bit tests, as I suspected.  Try this diff:

```
diff --git a/config.sh b/config.sh
index de1f322..7a345da 100644
--- a/config.sh
+++ b/config.sh
@@ -33,13 +33,7 @@ function get_test_cmd {
 
 function run_tests {
     # Runs tests on installed distribution from an empty directory
-    if [ -n "$IS_OSX" ]; then  # Test both architectures on OSX
-        # Skip f2py tests for 32-bit
-        arch -i386 python -c "$(get_test_cmd "'--ignore=numpy/f2py', $EXTRA_ARGV")"
-        arch -x86_64 python -c "$(get_test_cmd)"
-    else
-        python -c "$(get_test_cmd)"
-    fi
+    python -c "$(get_test_cmd)"
     # Check bundled license file
     python ../check_license.py
     # Show BLAS / LAPACK used
```

**Comment by charris** [comment]
Trying with the test update.

**Comment by matthew-brett** [comment]
@tylerjereddy - oops - yes - sorry - it's very late here.   We don't need that old image, we only need 10.9 SDK, not 10.6 as we were previously using.

**Comment by matthew-brett** [comment]
Oh - whoops again - the xcode 6.4 is the last to have the 10.9 SDK.  Here was a recent query for Python-Pillow:

https://github.com/python-pillow/pillow-wheels/issues/96#issuecomment-421541416

I guess we should just switch to a later image when we're forced to.  At the moment, we could, if pushed, go to macOS 10.11 = xcode image 7.3.

**Comment by charris** [comment]
We should probably go up to 10.11, as otherwise we will be stuck soon after the next releases of NumPy and SciPy.

The Mac builds look to be passing now.

**Comment by matthew-brett** [comment]
We don't lose anything by keeping 10.9 compatibility a bit longer - I don't think.   All later macOS versions can use the 10.9 binary.

**Comment by charris** [comment]
I'd like to keep the same compatibility throughout the 1.16 micro releases. It would be nice if the 1.16.1 wheels ran on the same OS versions as 1.16.0. It is a question of making the switch up front or dealing with it later, but it probably isn't a big deal.

**Comment by charris** [comment]
Closing this as the primary task is done. We can continue discussing the pending loss of 10.9 support here, or open another issue.

**Comment by charris** [comment]
Matthew, thanks for getting this done.

**Comment by matthew-brett** [comment]
@isuruf - thanks - yes - I was just wondering about that - would you mind pointing us to the machinery for that?

**Comment by isuruf** [comment]
Here are the lines to download and setup the sdk, https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/branch2.0/recipe/run_conda_forge_build_setup_osx#L12-L23.

We also set, `export CFLAGS="${CFLAGS} -mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET} -isysroot ${CONDA_BUILD_SYSROOT}`

(CONDA_BUILD_SYSROOT variable is from link above. You can rename the variable to something not conda specific)

**Comment by matthew-brett** [comment]
Nice - thanks.  Do you need `-mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}` when `MACOSX_DEPLOYMENT_TARGET` is set and exported?

**Comment by isuruf** [comment]
Some packages add a different `-mmacosx-version-min` to their package flags which overrides `MACOSX_DEPLOYMENT_TARGET`. It was added to handle this case (It wouldn't always work. eg: if values from env variable `CFLAGS` if prepended)

**Comment by charris** [comment]
What is the current status of this? I'm concerned that wheel builds may break in the middle of the current release. Another thing we may want to fix for OS X is the names of the wheels, which currently imply that they will also work for 32 bit: numpy-1.16.0rc1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl. Or perhaps I am missing something.

**Comment by charris** [comment]
@matthew-brett @tylerjereddy Just ran into this again with the 1.16.4 release and the updated OpenBLAS libraries. Do we really need the fused versions? The master branch is building without problems and passing tests.

**Comment by tylerjereddy** [comment]
Pretty sure Matthew and I already discussed that it is okay not to produce dual-arch mac OpenBLAS builds anymore: https://github.com/MacPython/openblas-libs/pull/1#issuecomment-476312625

> The master branch is building without problems and passing tests.

You mean the master branch of numpy-wheels, where I [recently removed](https://github.com/MacPython/numpy-wheels/pull/44/files) the dual-arch builds for Mac OS?

I suppose it may be a little strange to drop 32-bit Mac architecture support in 1.16.4 relative to the the previous 1.16.x releases, but if the upstream MacPython / OpenBLAS decision has been made it seems like that's already decided for NumPy too. Perhaps there's an argument related to the LTS release series/ final 2.7 support...

**Comment by charris** [comment]
I removed it from v1.16.4 after doing a diff, and it is building fine. I note that earlier 1.16 builds were not running 32 bit tests in any case, so we dropped 32 bits already, which is why I was wondering why we were still using the fused library.

**Comment by charris** [comment]
The release notes say we dropped 32 bit support in 1.15.2 even though we were still including it, so I think we are good to go for 1.16
