### ISSUE TITLE
Behavior of np.array([a, b], dtype=object) with arrays a and b

### ISSUE THREAD

**Issue by kohr-h** [numpy/numpy#12479]
What exactly is the behavior of the `array` constructor with `dytpe=object`? I'm particularly interested in the policy for a sequence of `numpy.ndarray` as input.

Before mucking around with this, I thought that `dtype=object` basically did nothing but store references no matter what comes in. Apparently that's not the case:

Same `dtype`, same size:
```python
>>> a = np.zeros(int(1e8))
>>> b = np.zeros(int(1e8))
>>> x = np.array([a, b], dtype=object)  # Consumes all memory and crashes

```

Different `dtype`, same size:
```python
>>> a = np.zeros(int(1e8))
>>> b = np.zeros(int(1e8), dtype='float32')  # or int or complex
>>> x = np.array([a, b], dtype=object)  # Consumes all memory and crashes

```

Different sizes:
```python
>>> a = np.zeros(int(1e8))
>>> b = np.zeros(int(1e8) + 1)
>>> x = np.array([a, b], dtype=object)  # instantaneous
>>> x = np.array([a, b])  # equivalent
```

### Questions
- What happens in the crashing calls? Is the constructor looping over the arrays in Python?
- Why aren't just the two arrays stored as references as in the last case?

I tested 1.15.4 and 1.13.

**Comment by seberg** [comment]
The last now raises an error, so it is now consistent so to speak.  Closing, since I am sure we havce other issues open about making it easier to create this type of "ragged" object array (limiting the depth of the new array).
