### ISSUE TITLE
DOC, TST: Display of "prompts" in docs

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#12484]
As @shoyer [notes](https://github.com/numpy/numpy/pull/12253#issuecomment-444251087) in #12253 (the PR to add refguide checking), some people may prefer to have docstrings (or portions thereof) which have code blocks that do not have prompts like `>>>` and `...` all over the place.

As discussed on the weeked in-person, we may eventually want to "improve" our doc html renders to have the option to "hide" these prompts online like CPython does. There's also the `Manuel` package mentioned in the linked comment above.

That said, I simply reverted `numpy/lib/mixins` (for `NDArrayOperatorsMixin` restoration to status without prompts, as requested) to master branch status and refguide check still passed, even without the prompts, so that was probably more of an issue with doctest proper rather than refguide.

I don't feel strongly about this, but I'll leave this bookmark issue open for now so that the connected PR does not become burdened by debate of prompts vs. no-prompts vs. toggle-prompts.

**Comment by tylerjereddy** [comment]
My note above about the numpy/lib/mixins stuff passing may be premature -- I think the prompts were almost certainly added in using vanilla doctest, then when I switched to refguide numpy/lib/mixins was no longer exposed as a public module for testing so that specific case will probably have to be revisited if / when I add that in, and if the appropriate functions can be safely added to `__all__` in that module if they aren't already

**Comment by melissawm** [comment]
I believe this issue no longer applies to the current version of the docs. I propose this issue is closed, and if the discussion is still relevant we can open another issue for the current context.

**Comment by rossbar** [comment]
I agree, let's go ahead and close this. Please reopen to pick up the conversation as necessary!
