### ISSUE TITLE
DOC, TST: matmul docstring fails refguide

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#12483]
The matmul docstring in `numpy/core/code_generators/ufunc_docstrings.py` fails the refguide check in #12253 for a variety of reasons varying from behavior changes to not even closing brackets in `np.array()` declarations.

While I've cleaned up some of the trivial issues, I'm going to mark the rest of the issues in that docstring with the `SKIP` directive and I suggest that they be fixed **after** that PR is merged so that the fixes are properly verified in CI.

I'll probably continue with this approach moving forward until the doctest PR is merged -- adding SKIPs and opening bookmark issues--otherwise I end up as the "human refguide checker" for doc changes.

**Comment by mattip** [comment]
This diff will fix the issue. It builds on #12253, so it will be easier to make a PR once that lands.
<details>

```
--- a/numpy/core/code_generators/ufunc_docstrings.py
+++ b/numpy/core/code_generators/ufunc_docstrings.py
@@ -2603,13 +2603,13 @@ add_newdoc('numpy.core.umath', 'matmul',
     - Stacks of matrices are broadcast together as if the matrices
       were elements, respecting the signature ``(n,k),(k,m)->(n,m)``:
 
-      >>> a = a = np.full([9,5,7,3], True, dtype=bool)
-      >>> c = np.full([9, 5, 4,3], True, dtype=bool)
-      >>> np.dot(a, c).shape # doctest: +SKIP
-      (9, 5, 7, 9, 5, 4)
-      >>> np.matmul(a, c).shape # doctest: +SKIP
-      (9, 5, 7, 4)
-      >>> # n is 5, k is 3, m is 4
+      >>> a = np.ones([9, 5, 7, 4])
+      >>> c = np.ones([9, 5, 4, 3])
+      >>> np.dot(a, c).shape
+      (9, 5, 7, 9, 5, 3)
+      >>> np.matmul(a, c).shape
+      (9, 5, 7, 3)
+      >>> # n is 7, k is 4, m is 3
 
     The matmul function implements the semantics of the `@` operator introduced

```
