### ISSUE TITLE
BUG: skiprows in loadtxt counts comments

### ISSUE THREAD

**Issue by iljah** [numpy/numpy#12489]
Since comments in loadtxt can already be used to skip comments in data file, why would skiprows also count comments? That doesn't seem useful and in my case is less than useless since number of comments can vary but number of data lines I want to skip doesn't.

### Reproducing code example:

```
>>> from io import StringIO
>>> from numpy import loadtxt
>>> f=StringIO("# 1 2\n2 3\n4 5\n")
>>> loadtxt(f, skiprows=0)
array([[2., 3.],
       [4., 5.]])
>>> f=StringIO("# 1 2\n2 3\n4 5\n")
>>> loadtxt(f, skiprows=1)
array([[2., 3.],
       [4., 5.]])
>>> f=StringIO("# 1 2\n2 3\n4 5\n")
>>> loadtxt(f, skiprows=2)
array([4., 5.])
```

Result above is identical with skiprows=0 and skiprows=1 which seems inconsistent...

### Numpy/Python version information:

>>> import sys, numpy; print(numpy.__version__, sys.version)

1.14.5 3.6.7 (default, Nov 23 2018, 12:11:28) 
[GCC 8.2.1 20181105 (Red Hat 8.2.1-5)]

**Comment by seberg** [comment]
Because skip rows is designed to skip header information in files. So it cannot do what you want it to do, but it was never designed to do that. (Similar to genfromtxt where skiprows was renamed to `skip_header`, though)

Anyway, we cannot change such behavior. Clarifications of the documentation are always good. Otherwise, we would have to add a new argument.

**Comment by iljah** [comment]
> Because skip rows is designed to skip header information in files.

Comments are not defined so I guess technically it's working. Currently 
their definition is surprising though: "data to exclude, except header 
(first skiprows rows) which is always included" or similar.

**Comment by seberg** [comment]
Yes, it is technically right. I am not quite sure what you mean with the quote. Is it a suggestion to improve the documentation? Those are always welcome, and simple changes can already be made through the web interface, by clicking the "Edit" button on the correct code file.

**Comment by iljah** [comment]
Finally got around to it: https://github.com/numpy/numpy/pull/12584

**Comment by seberg** [comment]
Thanks
