### ISSUE TITLE
Inconsistent behavior argsort of nan's

### ISSUE THREAD

**Issue by JoostBerkhout** [numpy/numpy#12490]
When applying argsort to a n-sized NumPy array consisting of only nan's, np.arange(n) is returned for n <=16. When n > 16, this logic stops and I can not make sense of the output anymore.  This (apparent) inconsistent behavior of argsort may be undesirable.

### Reproducing code example:

```python
import numpy as np
for n in range(20):
   a = np.empty((n,))
   a[:] = np.nan
   print(np.argsort(a))
```

Output of the code:
```
[]
[0]
[0 1]
[0 1 2]
[0 1 2 3]
[0 1 2 3 4]
[0 1 2 3 4 5]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0 14 13 12 11 10  9 15  8  6  5  4  3  2  1  7 16]
[ 0 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1 16 17]
[ 0 16 15 14 13 12 11 10 17  9  7  6  5  4  3  2  1  8 18]
```
### Error message:

No error. 

### Numpy/Python version information:

`('1.15.4', '2.7.15 |Anaconda custom (64-bit)| (default, Nov 13 2018, 17:33:26) [MSC v.1500 64 bit (AMD64)]')
`

**Comment by seberg** [comment]
This is expected, if you read the documentation of argsort the default sorting algorithm is not stable. You should use the `kind` keyword argument to chose a stable one (on newer we have a "stable" one, which could change to a different but stable algorithm and is more easy to read).

So there is no bug here, but if you can suggest to make the documentation more clear in a way that would have helped you, please do!

**Comment by JoostBerkhout** [comment]
Thanks seberg for your quick response. I just missed the notes regarding this matter.
