### ISSUE TITLE
np.sin() inaccurate for large numbers

### ISSUE THREAD

**Issue by rdtharri** [numpy/numpy#12499]
numpy.sin() is inacurate for numbers larger than ~1E11 due to floating-point issues.

### Reproducing code example:

```python
import numpy as np

#mod(a,2pi) = mod(b,2pi)
a = 0.5
b = 0.5 + 2 * np.pi * 1e15

#these should evaluate to the same value
sina = np.sin(a)
sinb = np.sin(b)

#this should be close to 0
print np.abs(sina-sinb)
```

### Request:

It may be appropriate for a warning message to be printed when np.sin() is called on a number larger than 1e11. The deviation in the accuracy of np.sin() and other trig functions increases with parameter magnitude more quickly than the error of most other np functions.

**Comment by tlatorre-uchicago** [comment]
I don't think there's anything numpy can do about this. This is a fundamental issue with the limitations of floating point representation. For example:

```python
In [5]: 0.5 + 2*np.pi*1e15 - 2*np.pi*1e15
Out[5]: 0.0
```

**Comment by seberg** [comment]
Yeah,it is annoying, but it is similar to catastrophic annihilation when subtracting numbers. Note that `sin` itself is exact, it is the number passed into the sine that is just not exact enough to be useful with respect to `sin`.

It would be nice to educate users about such floating point issues. And I agree that this is more a trap then others, but while warnings for this might be feasible for scalars, on first thought I doubt it is nice or feasible for arrays.

**Comment by seberg** [comment]
I will close this for now, although others might disagree. I think we need some discussion if we might want to add such warnings. these are warnings that are not anticipated by floating point standards. Personally, I doubt it, although I do see a value from an educational point.

**Comment by charris** [comment]
> So Paul is walking past the lunch place and these guys are all excited. "Hey, Paul!" they call out. "Feynman's terrific! We give him a problem that can be stated in ten 
seconds, and in a minute he gets the answer to 10 percent. Why don't you give him one?" Without hardly stopping, he says, "The tangent of 10 to the 100th."
I was sunk: you have to divide by pi to 100 decimal places! It was hopeless.

Taken from "Surely You're Joking, Mr. Feynman".
