### ISSUE TITLE
DOC, TST: matplotlib backends in doctests

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#12492]
As [noted](https://github.com/numpy/numpy/pull/12253#discussion_r239262077) we probably shouldn't have things like `matplotlib.use('agg')` in our docs. I added several such cases in #12253 -- I think my main reason was related to issues of:

1) having matplotlib plots showing (popping) up on my screen locally during doctests because of backend settings / whatever defaults get used with our original docstrings
2) Actual doctest errors, at least locally, without using a fixed backend

I'm not sure if the issues are less severe after the doctest->refguide transition now.

**Comment by rgommers** [comment]
There shouldn't be any issues, `use('Agg')` is already done within `refguide_check`: https://github.com/scipy/scipy/blob/master/tools/refguide_check.py#L827

**Comment by tylerjereddy** [comment]
Ok, the superset of changes in the linked PR includes many left-overs from pure doctest revisions so I'll have to manually reverse quite a few of those.

**Comment by mattip** [comment]
Can we close this?

**Comment by rgommers** [comment]
> Can we close this?

No, there are 5 instances of `matplotlib.pyplot.switch_backend('agg')` currently in master, those simply need removing to close this issue.
