### ISSUE TITLE
Mixing scalar dtype objects with Python objects (casting) is very slow

### ISSUE THREAD

**Issue by zerothi** [numpy/numpy#12496]
Doing scalar operations with `numpy.dtype` integers compared to Python `int` has a very large overhead.

I don't know if some of #2899 will correct this.

This issue is discovered through the usage of a custom sparse matrix format which uses int32 (to conform with `scipy` matrices) and thus does lots of indexing operations. When one mixes `len(obj)` with indices in `int32` format there is a huge overhead which seems too high compared to regular conversions.

Indeed casting to intrinsic Python object is faster than doing it through `numpy`. I would suspect some overhead, but `int + int32` is 50 times slower than `int + int`, and 25 times slower than `int32 + int32`.

### Reproducing code example:

This is rather long to have all in one. The code is very simple.

```python
import time as t
import numpy as np

itt_N = int(1e6)

fmt = '{:20s}: {}'

# Define integers
iint = 20
i32 = np.int32(20)
i64 = np.int64(20)

def my_run(i1, i2):
    try:
        s_i1 = str(i1.dtype)
    except:
        s_i1 = 'int'
    try:
        s_i2 = str(i2.dtype)
    except:
        s_i2 = 'int'

    t0 = t.time()
    for _ in range(itt_N):
        n = i1 + i2
    print(fmt.format('{} + {}'.format(s_i1, s_i2), t.time() - t0))

    if s_i1 == s_i2:
        return

    t0 = t.time()
    for _ in range(itt_N):
        n = i2 + i1
    print(fmt.format('{} + {}'.format(s_i2, s_i1), t.time() - t0))

my_run(iint, iint)
my_run(iint, i32)
my_run(iint, i64)
my_run(i32, i32)
my_run(i32, i64)
my_run(i64, i64)

# Now conversions
t0 = t.time()
for _ in range(itt_N):
    n = iint + int(i32)
print(fmt.format('int + int(int32)', t.time() - t0))

t0 = t.time()
for _ in range(itt_N):
    n = iint + int(i64)
print(fmt.format('int + int(int64)', t.time() - t0))

t0 = t.time()
for _ in range(itt_N):
    n = i32 + int(i32)
print(fmt.format('int32 + int(int32)', t.time() - t0))

t0 = t.time()
for _ in range(itt_N):
    n = i32 + int(i64)
print(fmt.format('int32 + int(int64)', t.time() - t0))


t0 = t.time()
for _ in range(itt_N):
    n = i64 + int(i32)
print(fmt.format('int64 + int(int32)', t.time() - t0))

t0 = t.time()
for _ in range(itt_N):
    n = i64 + int(i64)
print(fmt.format('int64 + int(int64)', t.time() - t0))
```

### Numpy/Python version information:

- 1.15.4, 2.7.15 (default, Nov 30 2018, 10:13:10) [GCC 8.2.0], output:
```bash
int + int           : 0.0489568710327
int + int32         : 1.60342693329
int32 + int         : 1.83480596542
int + int64         : 0.149921894073
int64 + int         : 0.180678844452
int32 + int32       : 0.0887141227722
int32 + int64       : 1.75734806061
int64 + int32       : 0.146602869034
int64 + int64       : 0.0899341106415
int + int(int32)    : 0.217828035355
int + int(int64)    : 0.214859008789
int32 + int(int32)  : 2.11016106606
int32 + int(int64)  : 2.0769739151
int64 + int(int32)  : 0.369491815567
int64 + int(int64)  : 0.375802993774
```

- 1.15.4, 3.7.1 (default, Dec  2 2018, 22:21:13) [GCC 8.2.0], output:
```bash
int + int           : 0.038968801498413086
int + int32         : 2.2395167350769043
int32 + int         : 2.3282487392425537
int + int64         : 0.16041350364685059
int64 + int         : 0.18115663528442383
int32 + int32       : 0.07951927185058594
int32 + int64       : 2.3612844944000244
int64 + int32       : 0.1289522647857666
int64 + int64       : 0.08025431632995605
int + int(int32)    : 0.21024799346923828
int + int(int64)    : 0.2115180492401123
int32 + int(int32)  : 2.7235195636749268
int32 + int(int64)  : 2.7075741291046143
int64 + int(int32)  : 0.3746912479400635
int64 + int(int64)  : 0.3755314350128174
```

**Comment by charris** [comment]
It looks like casting is a major bottleneck. IIRC, that currently goes through the array machinery with a fast path when no casting is needed. It is a longstanding problem and the usual recommendation is "don't do that", which doesn't seem in option in your use case. We should take a look at that as we are considering changing the scalar handling in a future release.

**Comment by zerothi** [comment]
Yes, right now I am doing manual casting which still gives a factor ~10! ;)
And yes, in this case I can't really go about this...

Good if this is taking into consideration when changing scalar handling in a future rewrite.

**Comment by seberg** [comment]
It's fast now in NumPy 2, (partially my weak promotion implementation with NEP 50, partially just my earlier restructring of this code to make it faster), so not sure when it changed.
