### ISSUE TITLE
ndarray.fill crashes in master

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [numpy/numpy#12503]
### Reproducing code example:

A test `scipy._lib.tests.test__utils::test__aligned_zeros` from 1.2.0rc2, with NumPy built from sources sporadically crashes.

```
(tscp) [13:28:40 fxsatlin03 test_tmp]$ pytest -v --pyargs scipy._lib.tests.test__util::test__aligned_zeros
================================================= test session starts ==================================================
platform linux -- Python 3.6.5, pytest-3.8.1, py-1.6.0, pluggy-0.7.1 -- ~/miniconda3_cb3/envs/tscp/bin/python
cachedir: .pytest_cache
rootdir: ~/test_tmp, inifile:
collected 1 item

test__util.py::test__aligned_zeros <- ~/miniconda3_cb3/envs/tscp/lib/python3.6/site-packages/scipy/_lib/tests/test__util.py Aborted (core dumped)
```

The best reproducer I could build is

```python
import numpy as np

buf = np.empty(4, np.uint8)
buf = buf[2:3][:-1]
data = np.ndarray((0,), np.double, buf, order='C')
data.fill(0) # crash
```

### Error message:

```
(tscp) [13:26:20 vmlin03 test_tmp]$ python scipy_utils.py
python: numpy/core/src/multiarray/lowlevel_strided_loops.c.src:816: _aligned_cast_longlong_to_double: Assertion `npy_is_aligned(dst, __builtin_offsetof(struct {char c; npy_double v;}, v))' failed.
Aborted (core dumped)
```

### Numpy/Python version information:

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.16.0.dev0+22d6157'
```

**Comment by tylerjereddy** [comment]
I can't reproduce the NumPy-only test case crash above locally on Ubuntu at the same NumPy commit hash.

I haven't seen that SciPy test failure in dev CI or wheel builds either. Anything different about your configuration vs. what we use for i.e., CI?

**Comment by charris** [comment]
I can't reproduce either, using latest master and both Python2 and Python3 on Fedora.

What compiler/optimization are you using?

**Comment by charris** [comment]
How sporadic is "sporadic"?

**Comment by oleksandr-pavlyk** [comment]
Thank you all for checking. I am compiling using Intel compiler, and compiling with `-O3`.

pytest calls crashes 3 out of 4 times, but my stand alone example crashes every time I tried. 

I will report my findings here.

**Comment by tylerjereddy** [comment]
> Intel compiler

18.x series? If the compiler is the difference vs. our test infrastructure I'm not sure we have an easy way to CI test with Intel compilers because of the license stuff, if I'm not mistaken.

**Comment by oleksandr-pavlyk** [comment]
As I said, I am using Intel C Compiler 2016 update 3, but I can reproduce the problem when compiling the entire NumPy with `-g -O0`:

```
(gdb) f 4
#4  0x00002aaaaf6a9695 in _aligned_cast_longlong_to_double (dst=0x555555ac1142 "", dst_stride=8,
    src=0x7fffffffc5a0 "", src_stride=0, N=0, __NPY_UNUSED_TAGGEDsrc_itemsize=8, __NPY_UNUSED_TAGGEDdata=0x0)
    at numpy/core/src/multiarray/lowlevel_strided_loops.c.src:816
816         assert(npy_is_aligned(dst, _ALIGN(_TYPE2)));
```

when running the above snippet.  

I will run more experiments.

**Comment by oleksandr-pavlyk** [comment]
The SHA were this problem was reproduced is the root of maintenance/1.16.x branch. 

Unless it is a matter of the assert needing to be fixed, perhaps this issue should be fixed in 1.16

**Comment by tylerjereddy** [comment]
Does this mean we are missing / need a CI entry that runs tests with C-level assert macros active?

**Comment by mattip** [comment]
Can reproduce when `CFLAGS="-g -O0 -UNDEBUG -D_DEBUG" python runtests.py -i`

**Comment by charris** [comment]
The problem PR is #6377.

**Comment by charris** [comment]
@ahaldane  Want to take a look?

**Comment by ahaldane** [comment]
OK, I see the problem.

It is actually related to the `NPY_RELAXED_STRIDES_CHECKING` bugfix from [this commit](https://github.com/numpy/numpy/pull/6377/commits/b76c0dfbf9eec3bd3ac6ec2fc7b507bee8f3c0e1), and is not due to the `complex` alignment change that PR was focused on.

In that commit I tried to add `RELAXED_STRIDE` checking which was missing from `raw_array_is_aligned`. That code says that 0d arrays are "always aligned" (see comment there), which means that the copy code goes down the "aligned" copy-code path. But that code-path has an assertion which does not account for relaxed_stride definition of alignment.

This didn't happen in 1.15 because `raw_array_is_aligned` didn't do relaxed_stride checking then (which I think was a bug).
