### ISSUE TITLE
Problem building docs

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12504]
Unable to make documentation with
```
make dist
```
fails with
```
Traceback (most recent call last):
  File "/home/charris/.local/bin/sphinx-build", line 7, in <module>
    from sphinx.cmd.build import main
ModuleNotFoundError: No module named 'sphinx'
```

I can do the import without problems from a console, so suspect some sort of path problem has crept into my environment.  There haven't been any recent updates to the Makefile.

@rgommers Could you check if you can still make the documentation? That's why the new issue :)

**Comment by rgommers** [comment]
works fine for me, doesn't look like a regression

**Comment by rgommers** [comment]
`make html` fails for you as well then I assume? That's a much faster way to check, avoids the rebuild

**Comment by charris** [comment]
Figured it out, my default python3 is now 3.7 (surprise), whereas the Makefile has `PYVER = 3.6`. Should probably just make it `PYVER = 3`.

**Comment by rgommers** [comment]
ah yes, that will give that error - the `PYVER` thing is a bit useless.
