### ISSUE TITLE
AVX2 related failures.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12507]
See #12398 for details of test failures when compiled with defined `__AVX2__`.

**Comment by juliantaylor** [comment]
posted a fix to master and 1.16.x

**Comment by charris** [comment]
The real problem here was our CI testing, we need some tests running with AVX support. Our wheels are too generic for that, so problems won't manifest there. @tylerjereddy Do you know if it is possible to specify the hardware/flags on any of our testing platforms so that in the future problems like this will be caught early?

**Comment by juliantaylor** [comment]
most testing platforms should have at least avx by now, I'd convert the code to runtime detection and add environment variables to select what you want for tests during the initial dispatching.
If we extend the code to the boolean code we might see some benefit and adding some more selection features would be a worthwhile investment.

(note we already have compiler optimized runtime dispatched vector code in all our the integer ufuncs, there we simply rely on the correctness of the compiler compiling both the vectorized and normal code correctly but explicitly testing both code paths might still be worthwhile)

**Comment by tylerjereddy** [comment]
I can reproduce what Chuck sees at the offending commit with this compilation: 
`CFLAGS=-mavx2 NPY_DISTUTILS_APPEND_FLAGS=1 python runtests.py --mode=full -- -n 7 -rsx`

However, even on master branch, my Mac has a few new failures when compiling NumPy with `-mavx2`. On Azure, "illegal instruction" shows up right away when doc testing starts after a successful build for the Mac image with the above compile flags.

What's the "recommended" / conservative way to activate AVX support for NumPy compile with clang and / or gcc? If this is an avx2 specific issue, I suppose we may need to probe a few different CI configs to see which has a sufficiently-recent CPU arch.

I don't think we have much control over specific hardware details, but we can certainly control compilation flags.
