### ISSUE TITLE
int(np.int32(random.getrandbits(32))) trows an OverflowError on win_amd64 but not on linux

### ISSUE THREAD

**Issue by tcdude** [numpy/numpy#12510]
When on Windows 10 64bit, an OverflowError is raised about 50% of the time by the code example below, while on Linux it executes without a problem.
Could be related to: https://github.com/numpy/numpy/issues/6637

### Reproducing code example:

```python
import numpy as np
import random

for _ in range(10000):
    int(np.int32(random.getrandbits(32)))
```

### Error message:

Traceback (most recent call last):
  File "randtest.py", line 24, in <module>
    int(np.int32(random.getrandbits(32)))
OverflowError: Python int too large to convert to C long 

### Numpy/Python version information:

Numpy: 1.15.4  
Python: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
`int32` is signed, `getrandbits` is unsigned.

**Comment by tcdude** [comment]
Thank you. It still puzzles me thou, that it doesn't throw the same exception on Linux!

**Comment by eric-wieser** [comment]
Looking deeper, the behavior is pretty inconsistent:
```
import numpy as np
import itertools

types = [
    'byte', 'short', 'intc', 'int_', 'longlong',
    'ubyte', 'ushort', 'uintc', 'uint', 'ulonglong'
]
sizes = sorted(set(
    bits
    for t in types
    for bits in [np.dtype(t).itemsize * 8, np.dtype(t).itemsize * 8-1]
))

result = {}
for t_name, size in itertools.product(types, sizes):
    t = getattr(np, t_name)
    try:
        x = t(2**size)
    except Exception as e:
        result[t_name, size] = e
    else:
        result[t_name, size] = x

# markdown table
print('| expr | result |')
print('|------|--------|')
for t, size in itertools.product(types, sizes):
    res = result[t, size]
    if isinstance(res, Exception):
        res = "`{}`: {}".format(type(res).__name__, res)

    print('| `np.{}(2**{})` | {} |'.format(t, size, res))
```
Giving

| expr | result |
|------|--------|
| `np.byte(2**7)` | -128 |
| `np.byte(2**8)` | 0 |
| `np.byte(2**15)` | 0 |
| `np.byte(2**16)` | 0 |
| `np.byte(2**31)` | `OverflowError`: Python int too large to convert to C long |
| `np.byte(2**32)` | `OverflowError`: Python int too large to convert to C long |
| `np.byte(2**63)` | `OverflowError`: Python int too large to convert to C long |
| `np.byte(2**64)` | `OverflowError`: Python int too large to convert to C long |
| `np.short(2**7)` | 128 |
| `np.short(2**8)` | 256 |
| `np.short(2**15)` | -32768 |
| `np.short(2**16)` | 0 |
| `np.short(2**31)` | `OverflowError`: Python int too large to convert to C long |
| `np.short(2**32)` | `OverflowError`: Python int too large to convert to C long |
| `np.short(2**63)` | `OverflowError`: Python int too large to convert to C long |
| `np.short(2**64)` | `OverflowError`: Python int too large to convert to C long |
| `np.intc(2**7)` | 128 |
| `np.intc(2**8)` | 256 |
| `np.intc(2**15)` | 32768 |
| `np.intc(2**16)` | 65536 |
| `np.intc(2**31)` | `OverflowError`: Python int too large to convert to C long |
| `np.intc(2**32)` | `OverflowError`: Python int too large to convert to C long |
| `np.intc(2**63)` | `OverflowError`: Python int too large to convert to C long |
| `np.intc(2**64)` | `OverflowError`: Python int too large to convert to C long |
| `np.int_(2**7)` | 128 |
| `np.int_(2**8)` | 256 |
| `np.int_(2**15)` | 32768 |
| `np.int_(2**16)` | 65536 |
| `np.int_(2**31)` | `OverflowError`: Python int too large to convert to C long |
| `np.int_(2**32)` | `OverflowError`: Python int too large to convert to C long |
| `np.int_(2**63)` | `OverflowError`: Python int too large to convert to C long |
| `np.int_(2**64)` | `OverflowError`: Python int too large to convert to C long |
| `np.longlong(2**7)` | 128 |
| `np.longlong(2**8)` | 256 |
| `np.longlong(2**15)` | 32768 |
| `np.longlong(2**16)` | 65536 |
| `np.longlong(2**31)` | 2147483648 |
| `np.longlong(2**32)` | 4294967296 |
| `np.longlong(2**63)` | `OverflowError`: int too big to convert |
| `np.longlong(2**64)` | `OverflowError`: int too big to convert |
| `np.ubyte(2**7)` | 128 |
| `np.ubyte(2**8)` | 0 |
| `np.ubyte(2**15)` | 0 |
| `np.ubyte(2**16)` | 0 |
| `np.ubyte(2**31)` | `OverflowError`: Python int too large to convert to C long |
| `np.ubyte(2**32)` | `OverflowError`: Python int too large to convert to C long |
| `np.ubyte(2**63)` | `OverflowError`: Python int too large to convert to C long |
| `np.ubyte(2**64)` | `OverflowError`: Python int too large to convert to C long |
| `np.ushort(2**7)` | 128 |
| `np.ushort(2**8)` | 256 |
| `np.ushort(2**15)` | 32768 |
| `np.ushort(2**16)` | 0 |
| `np.ushort(2**31)` | `OverflowError`: Python int too large to convert to C long |
| `np.ushort(2**32)` | `OverflowError`: Python int too large to convert to C long |
| `np.ushort(2**63)` | `OverflowError`: Python int too large to convert to C long |
| `np.ushort(2**64)` | `OverflowError`: Python int too large to convert to C long |
| `np.uintc(2**7)` | 128 |
| `np.uintc(2**8)` | 256 |
| `np.uintc(2**15)` | 32768 |
| `np.uintc(2**16)` | 65536 |
| `np.uintc(2**31)` | 2147483648 |
| `np.uintc(2**32)` | `OverflowError`: Python int too large to convert to C long |
| `np.uintc(2**63)` | `OverflowError`: Python int too large to convert to C long |
| `np.uintc(2**64)` | `OverflowError`: Python int too large to convert to C long |
| `np.uint(2**7)` | 128 |
| `np.uint(2**8)` | 256 |
| `np.uint(2**15)` | 32768 |
| `np.uint(2**16)` | 65536 |
| `np.uint(2**31)` | 2147483648 |
| `np.uint(2**32)` | `OverflowError`: Python int too large to convert to C long |
| `np.uint(2**63)` | `OverflowError`: Python int too large to convert to C long |
| `np.uint(2**64)` | `OverflowError`: Python int too large to convert to C long |
| `np.ulonglong(2**7)` | 128 |
| `np.ulonglong(2**8)` | 256 |
| `np.ulonglong(2**15)` | 32768 |
| `np.ulonglong(2**16)` | 65536 |
| `np.ulonglong(2**31)` | 2147483648 |
| `np.ulonglong(2**32)` | 4294967296 |
| `np.ulonglong(2**63)` | 9223372036854775808 |
| `np.ulonglong(2**64)` | `OverflowError`: int too big to convert |

**Comment by eric-wieser** [comment]
Comment above updated with a more concise table.

**Comment by eric-wieser** [comment]
Deleted my comment, and closing this issue in favor of the more useful #12513. Thanks for the report!
