### ISSUE TITLE
Truncation behavior of scalar integer type constructors is inconsistent

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12513]
Raised in #12510 by @tcdude

Invoking the scalar integer constructors on various edge-case values leads to wildly inconsistent behavior between truncating bits, raising an error referring to longs, or raising one that does not.

There are two possible directions we could take to resolve this:

* Scalar constructors should always truncate the MSBs, so that `np.bytes(2**64 + 1)` is 1
* Scalar constructors should always fail if the integer is unrepresentable within their range

The below output is from windows 10 x64, with bold cells showing where the operation is not a no-op:

| | `2**7` | `2**8` | `2**15` | `2**16` | `2**31` | `2**32` | `2**63` | `2**64` |
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
| `np.byte(...)` | <b>-2<sup>7</sup></b> | <b>0</b> | <b>0</b> | <b>0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> |
| `np.ubyte(...)` | 2<sup>7</sup> | <b>0</b> | <b>0</b> | <b>0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> |
| `np.short(...)` | 2<sup>7</sup> | 2<sup>8</sup> | <b>-2<sup>15</sup></b> | <b>0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> |
| `np.ushort(...)` | 2<sup>7</sup> | 2<sup>8</sup> | 2<sup>15</sup> | <b>0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> |
| `np.intc(...)` | 2<sup>7</sup> | 2<sup>8</sup> | 2<sup>15</sup> | 2<sup>16</sup> | <b>E0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> |
| `np.uintc(...)` | 2<sup>7</sup> | 2<sup>8</sup> | 2<sup>15</sup> | 2<sup>16</sup> | 2<sup>31</sup> | <b>E0</b> | <b>E0</b> | <b>E0</b> |
| `np.int_(...)` | 2<sup>7</sup> | 2<sup>8</sup> | 2<sup>15</sup> | 2<sup>16</sup> | <b>E0</b> | <b>E0</b> | <b>E0</b> | <b>E0</b> |
| `np.uint(...)` | 2<sup>7</sup> | 2<sup>8</sup> | 2<sup>15</sup> | 2<sup>16</sup> | 2<sup>31</sup> | <b>E0</b> | <b>E0</b> | <b>E0</b> |
| `np.longlong(...)` | 2<sup>7</sup> | 2<sup>8</sup> | 2<sup>15</sup> | 2<sup>16</sup> | 2<sup>31</sup> | 2<sup>32</sup> | <b>E1</b> | <b>E1</b> |
| `np.ulonglong(...)` | 2<sup>7</sup> | 2<sup>8</sup> | 2<sup>15</sup> | 2<sup>16</sup> | 2<sup>31</sup> | 2<sup>32</sup> | 2<sup>63</sup> | <b>E1</b> |

Where:
* E0 is `OverflowError('Python int too large to convert to C long',)`
* E1 is `OverflowError('int too big to convert',)`</sup>
<details>

<summary>Script to generate that table</summary>

```python
import numpy as np
import itertools

def compute():
    types = [
        'byte', 'ubyte',
        'short', 'ushort',
        'intc', 'uintc',
        'int_', 'uint',
        'longlong', 'ulonglong',
    ]
    sizes = sorted(set(
        bits
        for t in types
        for bits in [np.dtype(t).itemsize * 8, np.dtype(t).itemsize * 8-1]
    ))

    result = {}
    for t_name, size in itertools.product(types, sizes):
        t = getattr(np, t_name)
        try:
            x = t(2**size)
        except Exception as e:
            result[t_name, size] = e
        else:
            result[t_name, size] = x

    return types, sizes, result

def show_grid(types, sizes, result):
    errs = sorted(set((type(val), val.args) for val in result.values() if isinstance(val, Exception)))

    # header
    print('| ', end='')
    for size in sizes:
        print('| `2**{}` '.format(size), end='')
    print('|')
    print('| -- ', end='')
    for size in sizes:
        print('| -- '.format(size), end='')
    print('|')

    # rows
    for t_name in types:
        print('| `np.{}(...)` '.format(t_name), end='')
        for size in sizes:
            ret = result[t_name, size]
            if isinstance(ret, Exception):
                ei = errs.index((type(ret), ret.args))
                ret = '<b>E{}</b>'.format(ei)
            elif int(ret) == 2**size:
                ret = '2<sup>{}</sup>'.format(size)
            elif int(ret) == -2**size:
                ret = '<b>-2<sup>{}</sup></b>'.format(size)
            else:
                ret = '<b>{}</b>'.format(ret)
            print('| {} '.format(ret), end='')

        print('|')

    print()
    print("Where:")
    for i, (t, args) in enumerate(errs):
        print('* E{} is `{}{}`'.format(i, t.__name__, args))


show_grid(*compute())
```
</details>

**Comment by eric-wieser** [comment]
FWIW, ctypes takes the former approach, allowing `ctypes.c_uint8(2**64)` without complaint.

**Comment by seberg** [comment]
NumPy always complains now since 1.25, I think.  I don't disagree that it is inconvenient in some places, but I think it generally makes sense to protect users who don't think about it.
