### ISSUE TITLE
Flip not working with axis as tuple

### ISSUE THREAD

**Issue by renan-cunha** [numpy/numpy#12542]
Flip not working with axis as tuple, like the Example in the [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.flip.html?highlight=flip#numpy.flip).
### Reproducing code example:

```python
import numpy as np

A = np.arange(8).reshape((2,2,2))
np.flip(A, (0,2))
```
  

### Error message:

Traceback (most recent call last):
  File "myproblem.py", line 4, in <module>
    np.flip(A, (0,2))
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 206, in flip
    indexer[axis] = slice(None, None, -1)
TypeError: list indices must be integers or slices, not tuple

### Numpy/Python version information:

1.14.5 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

**Comment by seberg** [comment]
Allowing to flip multiple dimension was unfortunately only added in 1.15, which I guess is probably the cause of the expectation that it should work. Updating numpy will make this code work successfully.
