### ISSUE TITLE
DEP: remove untested, non-numeric code

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#12541]
In trying to make sense of our header files, I noticed we have a `npy_interrupt.h` file that defines a way to allow C code to respond to interrupts. The code is not tested. The only place it is used internally is in `int_asbuffer`, which interprets a python int as a pointer to a block of memory, tries to determine the size of the block, and returns a buffer object. It also is not tested.

At some point we should remove these since they are not really part of NumPy.

**Comment by mattip** [comment]
This would require deprecating `_PyArray_SigIntHandler`, which is a public API function

**Comment by Kai-Striega** [comment]
@mattip I've got some time to contribute at the moment. I'd need some guidance on how to get started (I don't have problems building/testing NumPy, only context on this specific issue)

**Comment by mattip** [comment]
You can look at other API function deprecations, like in #21188 [here](https://github.com/numpy/numpy/pull/21188/files#diff-3ce0ae2ab2cdadf0138ac9d43ac1664174259404fe7a517240db8a81c2d72aa6R315). Note this needs a release note, see [the readme](https://github.com/numpy/numpy/tree/main/doc/release/upcoming_changes#readme)

**Comment by seberg** [comment]
This is gone.
