### ISSUE TITLE
keepdims should be set by default to True in sum

### ISSUE THREAD

**Issue by aamster** [numpy/numpy#12559]
I would expect sum to return a row vector or column vector depending on whether axis is set to 0 or 1 by default. Instead sum returns a rank 1 matrix. The programmer instead needs to know to set keepdims to True. If the programmer forgets this, then rank 1 matrices cause silent bugs since they don't function as expected. For example transpose of the rank 1 matrix does not return a transpose. Is there any benefit to having it return a rank 1 matrix instead of a vector?

**Comment by eric-wieser** [comment]
Changing behavior like this would break thousands of users.

I also don't think that would even be a better default. As designed, `np.sum([1, 2])` and the built-in `sum([1, 2])` match. Under your proposition, they would not.

I think you need to stop thinking in terms of "matrices" or "vectors". Numpy is all about n-dimensional arrays.

**Comment by seberg** [comment]
The `.T` operation is indeed a bit of a pain point. But I am sure there are issues about it open. I do not remember the last discussion, my guess is, it will either stay as is, or slowly turned into only working for 2D.
