### ISSUE TITLE
Remove rank 1 matrices

### ISSUE THREAD

**Issue by aamster** [numpy/numpy#12558]
Rank 1 matrices should be removed. They don't behave as expected. For example a rank 1 matrix transpose does not return an error and does not do a transpose as expected. This can cause silent bugs. I'm not sure what purpose these rank 1 matrices serve but they are confusing.

**Comment by mattip** [comment]
You have to give better justifications for things than "I am confused by it". There are good reasons the fundamental data structure in NumPy is called `ndarray` not `matrix`. You can perhaps claim transpose on 1d arrays should maybe warn, but we will not remove them.

**Comment by aamster** [comment]
I'm not sure what purpose they serve. But assuming they won't be removed, let's take transpose of rank 1 matrix as an example. Numpy should definitely return a warning in this case as the transpose is not returned. As an extreme example if I am calculating 1 + 1 and it sometimes returns 10, a warning should definitely be returned.

**Comment by mattip** [comment]
Duplicate of #9530
