### ISSUE TITLE
BUG: NumPy deprecation of `numpy.testing.decorators`

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#12599]
I am working on testing [some libraries](https://github.com/nipy/nibabel/pull/705) for proper 1.15 support, and ran into an issue with the docstring for the 1.15 deprecation of numpy.testing.decorators:
```
DeprecationWarning: Importing from numpy.testing.decorators is deprecated since numpy 1.15.0, import from numpy.testing instead.
```
This does not work for previously working code like `from numpy.testing.decorators import skipif` because the suggested `from numpy.testing import skipif` does not work.

Looking at the NumPy code, in `testing/__init__.py` there is `from ._private import decorators as dec`. This means that the next-simplest option, `from numpy.testing.dec import skipif`, won't work. Is this two-liner thus the preferred way to do it?
```
from numpy.testing import dec
skipif = dec.skipif
```
If so, perhaps the warning should be adjusted to say something like "import from numpy.testing or use the numpy.testing.dec namespace instead" (since you can't directly import from `numpy.testing.dec`, not sure the best way to phrase it)?

**Comment by charris** [comment]
> from numpy.testing import dec

That's how it should be done ;) Note that the decorators are also Nose specific and Nose doesn't work for latest Python. But if you don't typically use namespaces, just suppress the deprecation warning. PR's to improve the warning language are also welcome.
