### ISSUE TITLE
Reduce power consumption for testing

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#12598]
The number of CI tests we run on every PR has substantially increased recently. While there is no cost to us, all these tests do use power, which, at ~100 W times ~2 hr of processing time, is not negligible. We should try to minimize that, perhaps by doing first a single test before running the full suite (we use the travis scheme for this at astropy; not sure how it works for azure).

Relatedly, we should document best practices, e.g., only push when tests pass locally, and for WIP where tests are know to fail, having options to avoid testing altogether.

p.s. I must admit I have little idea what the tests other than circle ci, azure, and coverage are good for...

**Comment by shoyer** [comment]
> We should try to minimize that, perhaps by doing first a single test before running the full suite (we use the travis scheme for this at astropy; not sure how it works for azure).

To be honest, I value developer time more. At $0.10/kWh, this is $0.02 in power costs. I'm sure we all have much bigger opportunities to impact climate change in our everyday lives :).

**Comment by mhvk** [comment]
I think you may be underestimating how many tests are run. For electricity, for me personally, influencing the number of tests may well be the best I can do (of course, if I were a dictator, I would instantly shut down anybody mining bitcoins, which would be way more effective, but alas I am not...).

**Comment by eric-wieser** [comment]
Doing a single test before the full run sounds like an improvement even from a developer time standpoint

**Comment by rgommers** [comment]
I sympathize with both viewpoints here. If there's a reliable way to do one regular run on say TravisCI, and conditionally on that passing run everything else, that would be awesome. If it requires manual actions though, then that wouldn't be good. It doesn't sound completely straightforward to trigger other CI systems from a TravisCI run.

**Comment by mhvk** [comment]
Definitely agreed it should be automatic! Over at astropy, the suggestion in part is to collect runs with the same python version in single tests; this allows early failure and reduces setup costs.

On travis, one can use "stages" to do first one test, then more (we use this in [astropy](https://github.com/astropy/astropy/blob/master/.travis.yml#L65)); possibly, there are similar options in azure?

Even better would be to do this at the github level, so all CIs can be dealt with. It does seem that github is introducing a new "Check Suites" framework that might allow requesting a hook such as azure to run only after something else is finished [1], but I fear I don't understand the machinery well enough to be sure.

[1] https://developer.github.com/v3/activity/events/types/#checksuiteevent

**Comment by bsipocz** [comment]
Now azure is also divided up into stages, so I feel we did all what's possible: https://github.com/numpy/numpy/pull/14709

**Comment by mhvk** [comment]
@bsipocz, @hameerabbasi - thanks so much! Closing...
