### ISSUE TITLE
1.6.0rc1 3.7 debug: test failure: test_multiarray.py::TestAlignment::test_various_alignments Aborted

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#12607]
Hello,
when running the test suite on i386 wit python3.7 in the debug flavor we get this abort:

```
-- running tests for 3.7 debug --
NumPy version 1.16.0rc1
NumPy relaxed strides checking option: True
============================= test session starts ==============================
platform linux -- Python 3.7.2rc1, pytest-3.10.1, py-1.7.0, pluggy-0.8.0 -- /usr/bin/python3.7-dbg
cachedir: .pytest_cache
rootdir: /<<PKGBUILDDIR>>, inifile: pytest.ini
collecting ... collected 7336 items / 167 deselected
...
tmp/usr/lib/python3/dist-packages/numpy/core/tests/test_multiarray.py::TestAlignment::test_various_alignments Aborted
```

could you have a look?

thanks!

**Comment by charris** [comment]
@ahaldane I don't know if it is your problem, but it is your test :)

**Comment by sandrotosi** [comment]
the full log of the failure is at: https://buildd.debian.org/status/fetch.php?pkg=python-numpy&arch=i386&ver=1%3A1.16.0~rc1-1&stamp=1545690613&raw=0

the machine where it was built was: https://db.debian.org/machines.cgi?host=x86-ubc-01 (i dont have access to it to run commands, but i suspect it may be an actual amd64 hardware running i386 chroots for packages building purposes)

is there any switch/option you want me to pass to the tests? is the abort unreproducible on your end?

**Comment by charris** [comment]
Just printing out the parameters would help locate what is causing the problem. I assume abort is some sort of illegal access? The test is doing a fair amount fooling with locations and it is passing on our normal tests, so the difference is the debug option and I don't know exactly what it is failing on here. Is there a way to get more information on the cause of the abort?

**Comment by seberg** [comment]
It could even just be a failed assert? Although certainly in one to do with alignment.

**Comment by sandrotosi** [comment]
i'll have a look if i can setup an environment to replicate it on my hand, it may take some days.

`Aborted` means the interpreter was doing something so wrong that it got terminated, so likely not a simple failed assert.

**Comment by seberg** [comment]
Was suprising to me as well, but I just tried and if I add a random `assert(0)` in the code, I do get `Aborted (core dumped)`.

**Comment by mattip** [comment]
Reproduces on python3.5-dbg in the chroot, now trying to run gdb

**Comment by mattip** [comment]
I think there is a problem with the [alignment check](https://github.com/numpy/numpy/blob/v1.16.0rc1/numpy/core/src/multiarray/array_assign_scalar.c#L49) for longdouble dtypes (with `elsize=12`) which will always return 1, even when `dst_data` is not aligned:
```
raw_array_is_aligned(ndim, shape, dst_data, dst_strides,
npy_uint_alignment(dst_dtype->elsize))
```

looking at the [implementation](https://github.com/numpy/numpy/blob/v1.16.0rc1/numpy/core/src/multiarray/common.h#L210) of `npy_uint_alignment(12)`, it will return 0, which causes [`raw_array_is_aligned`](https://github.com/numpy/numpy/blob/v1.16.0rc1/numpy/core/src/common/array_assign.c#L87) to return 1.

Adding a `case 12: alignment = _ALIGN(npy_longdouble); break` to the `switch` in `npy_uint_alignment` results in all the test passing rather than failing the assert, but it is strange to add a float type to `npy_uint_alignment`, no?

@ahaldane do you have any ideas?

**Comment by mattip** [comment]
Feel free to push to #12611. The 32 bit chroot in CI now runs the tests with `-UNDEBUG` so the asserts are active.

**Comment by charris** [comment]
We should probably add an option to `runtests.py` for `-UNDEBUG`. There is already a `debug` option, I wonder if we should add it there?

**Comment by mattip** [comment]
For MSVC the `--debug` option in `runtests.py` does not work, but `-UNDEBUG` is in the C standard, so we would still need to define it externally for some platforms.

**Comment by charris** [comment]
Good point. Maybe a new option then `--ndebug`, on MSVC that would add the `/DNDEBUG` option to the command line.

**Comment by sandrotosi** [comment]
thanks for the quick turnaround! I'm uploading numpy with this patch, will let you know if this is not fixed.

**Comment by sandrotosi** [comment]
confirming it worked! outs i386 build just completed successfully -- thanks folks!
