### ISSUE TITLE
numpy.gradient is swapping the 0th and 1st gradient axes

### ISSUE THREAD

**Issue by rwolst** [numpy/numpy#12614]
When using `np.gradient` the 0th and 1st axis gradients are swapped.

### Reproducing code example:
The `n` value below can be modified yet it always shows the 0th and 1st axis gradients being swapped.

    import numpy as np

    n = 4  # Total dimension size.
    delta = 1e-5  # Step size in calculating the approximate gradient.
    points = 2  # Total points to calculate gradient at.

    # Create a grid of theta values to mesh together that we can find the gradient
    # values on.
    m_grid = np.meshgrid(*[np.arange(0, points*delta, delta) for i in range(n)])
    Theta = np.concatenate([i[None,:] for i in m_grid])

    # Define basic function who's gradient value is equal to its dimension value.
    def h(theta):
        temp = np.arange(theta.shape[0])
        return np.einsum('i...,i->...', theta, temp)

    # Calculate gradient using Numpy.
    grad = np.gradient(h(Theta), *[delta for i in range(n)])
    G = np.concatenate([i[None, :] for i in grad])

    # Get the slice at 0.
    print("Gradient value at 0 (should be [0:%s])." % (n-1))
    print(G[[slice(0,n,1)] + [slice(0,1,1) for i in range(n)]].squeeze())

### Expected Result:
For `n=4` I expect `[0, 1, 2, 3]`.

### Actual Result:
For `n=4` I get `[1, 0, 2, 3]`.

### Numpy/Python version information:

    1.13.0 3.6.7 (default, Oct 21 2018, 04:56:05) 
    [GCC 5.4.0 20160609]

**Comment by seberg** [comment]
I think you are confused with `meshgrid` and not `gradient`. This looks all very much correct.

**Comment by seberg** [comment]
Not that meshgrid is ideal in many cases, but... (also there are probably alternatives here)

**Comment by rwolst** [comment]
Ok, yes I agree this seems like an issue caused by `meshgrid`. Very strange that the `0th` component from `meshgrid` varies along the `1st` axis, the `1st` component varies along the `0th` and the `ith` component (for `i > 2`) varies along the `ith` axis!

I see this is documented in `meshgrid` but seems to be a strange default.
