### ISSUE TITLE
vstack-ing empty list

### ISSUE THREAD

**Issue by gykovacs** [numpy/numpy#12628]
vstack-ing empty lists fail.

It is clear that the empty list does not allow numpy to infer on the shape and check if it is compatible with the other arrays being stacked. However, as stacking the empty list doesn't change anything, I think some branching in vstack (or the prefiltering of empty arrays in vstack) could make this code work. And increase convenience.

Use case: depending on user input, one generates arrays of the same size and collects them in a list. Then, the list is transformed into an array of arrays (2D), and appended to another 2D array using vstack. In case of an empty list the code fails.

### Reproducing code example:

```python
import numpy as np
np.vstack([np.array([[1, 2], [2, 3]]), np.array([])])
```

### Error message:

Traceback (most recent call last):

  File "<ipython-input-4-ac0729f3f966>", line 1, in <module>
    np.vstack([np.array([[1, 2], [2, 3]]), np.array([])])

  File "/home/gykovacs/anaconda3/lib/python3.6/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

### Numpy/Python version information:

1.15.4 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]

**Comment by gykovacs** [comment]
If someone confirms that adding the proposed feature (prefiltering for empty arrays in vstack) would be beneficial, I would be happy to deep dive and give it a try.

**Comment by seberg** [comment]
This is not going to happen, since I expect everyone agrees that you can be expected to write this as the empty array as `np.empty((0, 2))`, or similar.

**Comment by seberg** [comment]
Of course you have to be a bit careful with the dtype, but then `np.empty_like` or similar and passing the shape will help out.

**Comment by gykovacs** [comment]
Thanks! Yeah... np.empty could be used. What I tried to articulate was that if the list is dynamic (empty or not, depending on user input or execution path), one cannot convert it to an array and vstack it. Clearly, further lines of codes are required to check if the list is empty, which increases clutter and decreases readability. For example, given a 2D array (```A```), and a list of compatible 1D arrays (```LLL```) of unknown. One wants to vstack them, and
```
B= np.vstack([A, np.array(L)])
```
will fail if ```L``` is empty. Is there some simple way to implement this operation without checking if ```L``` is empty?

**Comment by seberg** [comment]
Well, if you pass in the array, there is definitely nothing to do. Until now we have held back and being lenient with list in such cases.
