### ISSUE TITLE
C-API documentation of nditer lists items that do not exist

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#12632]
I was trying to understand `nditer` better (with the idea of trying to implement a `where` keyword for reductions), and was surprised to find reference to items that do not actually seem to exist, in particular the `NPY_ITER_USE_MASKNA` flag and `NpyIter_GetMaskNAIndexArray` function.

**Comment by charris** [comment]
The iterator was used to implement the missing values  (NA) work. When that work was removed bits and pieces apparently got left behind. The `where` argument also came out of that work.

**Comment by vrindaaa** [comment]
Heyy, can I work on this issue?

**Comment by pujaji** [comment]
Heyy Outreachy mentors,
Can I also work on this Issue? I can see Vrindaa comment.

**Comment by mattip** [comment]
Fixed in #13205
