### ISSUE TITLE
np.sum bug

### ISSUE THREAD

**Issue by alexxchen** [numpy/numpy#12643]
a= [0.05, 0.05, -0.45, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
np.sum(a) get -2.7755575615628914e-17

### Numpy/Python version information:

1.14.5 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]

**Comment by eric-wieser** [comment]
Works as intended. float(0.05) is not exactly 0.05. The built-in `sum` gives the same result
