### ISSUE TITLE
How can I install numpy for pypy3.5 on windows

### ISSUE THREAD

**Issue by sandy-shirt** [numpy/numpy#12648]
I tried to install numpy by  
pypy3 -m pip install numpy 
it didnt work , my os is windows 
is numpy supported on pypy3.5 windows yet?

**Comment by mattip** [comment]
It should be. You need a compiler, binary wheels are not available yet. Please open an issue on the [pypy issue tracker](https://bitbucket.org/pypy/pypy/issues) with the complete (text, not screenshot) output from the command

**Comment by mattip** [comment]
From the PyPy [issue tracker](https://bitbucket.org/pypy/pypy/issues/2935/unable-to-install-numpy-for-pypy35-on), this was [fixed](https://bitbucket.org/pypy/pypy/commits/d246497b019e) on PyPy `HEAD`.
