### ISSUE TITLE
np.memmap throws OSError when size is zero

### ISSUE THREAD

**Issue by kieran-lemayai** [numpy/numpy#12653]
...Which, in fairness, is an edge case I should have guarded against myself. On the other hand, perhaps we could do some checking and toss a descriptive `ValueError` instead? I'm willing to write up a PR if that's an acceptable change.

### Reproducing code example:

The following works with any shape, so long as any one of the axes is length 0:

```python
import numpy as np
mmap = np.memmap('test.npy', shape=(0,4), mode='w+')
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/memmap.py", line 250, in __new__
    fid.seek(bytes - 1, 0)
OSError: [Errno 22] Invalid argument
```

### Numpy/Python version information:

1.15.2 / 3.5.2

**Comment by eric-wieser** [comment]
Given that `mmap.mmap` supports this, we should too. Thanks for the report. Seems like simply not running the branch that writes a trailing zero would do the trick

**Comment by gabelstein** [comment]
The problem is in ndarray that doesn't let you use a shape with a 0.
Is that wanted, though?
If not, it should probably be fixed there.

**Comment by gabelstein** [comment]
Apparently this is an error of ndarray. They also don't like shapes with a 0. Not sure if that's wanted.
Should this be fixed for ndarray or just locally for memmap?

**Comment by kieran-lemayai** [comment]
The real issue that I was trying to present is that it's difficult to figure out the source of the error when it's a scary `OSError` instead of something straightforward. Doing a check and throwing `ValueError` with a descriptive message should be acceptable, right? Again, I can probably write the PR if that's OK.

**Comment by eric-wieser** [comment]
> [ndarray] also don't like shapes with a 0

Citation needed. Numpy is fine with this

**Comment by eric-wieser** [comment]
Now raises `ValueError: cannot mmap an empty file`. Perhaps we should allow this too, but that's a different task

**Comment by kieran-lemayai** [comment]
You're awesome.

**Comment by gabelstein** [comment]
> > [ndarray] also don't like shapes with a 0
> 
> Citation needed. Numpy is fine with this

calling it like this (as done in memmap.py) rejects shape with a 0:
ndarray.__new__(subtype, shape,...)
