### ISSUE TITLE
Element-wise operators 10x slower in 1.15 than in 1.11

### ISSUE THREAD

**Issue by iandreariley** [numpy/numpy#12669]
Element-wise addition, subtraction, multiplication, and division are almost 10x slower in 1.15 than in 1.11.3. This appears true only for the first execution of the below script. In subsequent executions, 1.15 seems faster - however in production we are seeing the slower performance of 1.15 all the time (i.e., it never "warms up"). Is this a caching issue or something of that nature?

### Reproducing code example:
1. create a conda environment with numpy 1.11.3 thus:
    ```sh
    conda create -n np1113py352 python=3.5.2 numpy=1.11.3
     ```
2. create a second environment with 1.15 thus
    ```sh
    conda create -n np115py352 python=3.5.2 numpy=1.15
    ```
3. Run operators with the following script in both environments and observe that first execution is much slower in the 1.15 environment

```python
import argparse
import sys
import time
import numpy as np

def time_op(op):
    a1 = np.random.rand(512, 512)
    a2 = np.random.rand(512, 512)
    start = time.perf_counter()
    exec('a1 {} a2'.format(args.op))
    end = time.perf_counter()
    return end - start

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("op")
    parser.add_argument("repeats", default=1, type=int, nargs='?')
    args = parser.parse_args()
    results = [time_op(args.op) for i in range(args.repeats)]
    print("Mean: {}".format(np.mean(results)))
    print("All Results:\n{}".format(results))
```

**Expected Output**

```sh
> source activate np1113py352
(np1113py352) > python time_numpy_op.py -
Mean: 0.0011733369901776314
All Results:
[0.0011733369901776314]
(np1113py352) > source deactivate
> source activate np115py352
(np115py352) > python time_numpy_op.py -
Mean: 0.019282180990558118
All Results:
[0.019282180990558118]
(np115py352) i> source deactivate
> source activate np1113py352
(np1113py352) > python time_numpy_op.py - 10
Mean: 0.0008086999965598807
All Results:
[0.0009474630060140043, 0.000974412017967552, 0.0009397219982929528, 0.0008637550054118037, 0.0009213250013999641, 0.0008586559852119535, 0.0007832369883544743, 0.0006015869730617851, 0.0006042780005373061, 0.0005925649893470109]
(np1113py352) > source deactivate
> source activate np115py352
(np115py352) > python time_numpy_op.py - 10
Mean: 0.0025311258970759807
All Results:
[0.02195357100572437, 0.0006182210054248571, 0.00038990401662886143, 0.0003395449894014746, 0.0003235509793739766, 0.0003280279925093055, 0.00033088400959968567, 0.00032537899096496403, 0.00035402498906478286, 0.00034815099206753075]

```

### Error message:

N/A

### Numpy/Python version information:
**Numpy:** 1.11.3 / 1.15.2 (both installed via conda)
**Python:** 3.5.2 (installed via conda)

**Other Info:**
**OS:** SLES 12.2

**Comment by mhvk** [comment]
That is very strange. I have no access to conda myself, but under Debian numpy 1.15.4 or current master do not produce anything remotely as slow for the first trial (though it is a bit slower than the others). It does seem like some caching issue... Is it possible to install numpy not via conda, but just `pip install`? E.g., conda turns on some intel mkl libraries and perhaps loading them takes long.  Also, just to reduce irrelevant things, perhaps use the following variant of your script:
```
import argparse
import time
import numpy as np


def time_op(op):
    a1 = np.random.rand(512, 512)
    a2 = np.random.rand(512, 512)
    start = time.perf_counter()
    op(a1, a2)
    end = time.perf_counter()
    return end - start


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("op")
    parser.add_argument("repeats", default=1, type=int, nargs='?')
    args = parser.parse_args()
    op = getattr(np, args.op)
    results = [time_op(op) for i in range(args.repeats)]
    print("Mean: {}".format(np.mean(results)))
    print("All Results:\n{}".format(results))
```
Here, `op` has to be `add`, `subtract`, etc.
On my machine:
```
python3 a.py add 4
Mean: 0.0008432719987467863
All Results:
[0.0009956739959307015, 0.0008107320027193055, 0.0007802440086379647, 0.0007864379876991734]
```

**Comment by mattip** [comment]
Cannot reproduce when building from source on Ubuntu 18.04:
```
NumPy v1.11.3 (needed to remove `xlocale.h` from `npy_os.c` to build it)
Mean: 0.0009849630296230316
All Results:
[0.0009849630296230316]

NumPy v1.15.4
Mean: 0.000997839029878378
All Results:
[0.000997839029878378]

```

SLES is Suse Linux Enterprise Server?
Conda is using binary packages. So it may be they changed some compiler flags between the builds.

**Comment by seberg** [comment]
Possibly it has something to do with MKL replacing the ufuncs? That would seem logical....

**Comment by seberg** [comment]
Sorry, to be more clear: There are anaconda versions of numpy that use patches by Intel. Those use MKL for some ufuncs and that might do strange things.

@iandreariley can you see if you have `np.erf` or `np.random_intel` defined. Then this is almost certainly the reason (check it for both versions).

**Comment by iandreariley** [comment]
@seberg Thanks for the prompt response. Yes `np.erf` is defined, and the mkl dependency does seem to be the issue. I installed numpy 1.15.2 _without_ mkl, and that fixes the slow first execution. Thanks again for your help.

For those using conda interested in installing numpy without mkl, the `nomkl` metapackage does the trick. I created my environment thus:

```sh
conda create -n np115nomklpy352 python=3.5.2 numpy=1.15.2 nomkl
```

**Comment by charris** [comment]
Might want to open a Anaconda issue.

**Comment by iandreariley** [comment]
@charris I don't think there's an issue with Anaconda. The `nomkl` package provides a supported avenue for opting out of mkl, and speaks to the fact that they're aware of the potential issues with it - It appears they choose to use mkl builds by default, and I don't have enough context to question that choice.

**Comment by mhvk** [comment]
@iandreariley - the fact that in production you saw the slow-down every step suggests there is a real bug, either in anaconda's packaging or in your code. Would still seem worth investigating.

**Comment by iandreariley** [comment]
@mhvk that's a fair point. Raised an issue with Anaconda: https://github.com/ContinuumIO/anaconda-issues/issues/10485 . And ftr, I'm sure there are several bugs in my code 😃 

Also, @seberg, `np.erf` was defined in _only_ the 1.15.2 numpy (`np.intel_random` was defined in neither). Was that feature added after 1.11.3, or does its presence/absence have to do with anaconda's build?

**Comment by mhvk** [comment]
@iandreariley - `np.erf` is something that is added by intel, so we use its presence as a hint problems may have nothing to do with us :smiley_cat:

**Comment by iandreariley** [comment]
@mhvk Thanks for the help. Can you point me to any documentation on how MKL and numpy interact? I've found the following docs from [Anaconda](https://docs.anaconda.com/mkl-optimizations/) and [Intel](https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl), but haven't found anything from the numpy side.

One curious thing: I noticed that my 1.11.3 evironment _does_ have the `mkl` package in it, but does not have `erf` or `intel_random` defined. However the 1.15 environment has the `mkl_fft` and `mkl_random` packages installed - I'd guess that one of these is responsible for the change in behavior.

Thanks again for the help. I'll stop blowing up this post now.

**Comment by mhvk** [comment]
@iandreariley - I actually know *nothing* about mkl inside numpy or about anaconda (I happily use Debian myself and so have things wonderfully packed up for me). I only know it regularly causes problems or confusion.

**Comment by seberg** [comment]
@iandreariley actually you should be aware that there are two parts to MKL + numpy:

1. To give speedy linear algebra (most things in `np.linalg` and `np.dot`, etc.). NumPy should be linked to a BLAS/LAPACK implementation. There are a few options for this and one of them is MK. When you compile numpy yourself you can pick easily which one you want:
   * A differing implementation is expected from numpy side
   * In principle anyone can chose what they use. Anaconda long ago started to package MKL, since it is a good choice.

2. MKL actually implements not only BLAS/LAPACK, but also some other operations, this is what "speeds up numexpr":
   * Using MKL versions, e.g. for this function here, is *not* supported by numpy itself at this time
   * Intel *patches* numpy to use MKL for functions such as here.
   * Intel *patches* numpy for some more things (`random_intel`, general speed patches such as using multithreading for a couple of things. I expect these are great if you have large datasets, but apparently can be disadvantage for small arrays as you have seen here)
   * Anaconda seems to have started using at least some of these patches recently.

The blog posts also mix the two things. Users should expect 1., but 2. is a bit trickier and harder to judge. So for Anaconda it can be interesting because what you see are issues caused by 2. And Anaconda could decide that some of these patches are not actually useful for a general audience.

**Comment by iandreariley** [comment]
@seberg Thanks for the information. I wasn't sure whether it was the MKL BLAS/LAPACK implementation, or these additional patches. We will try building numpy without these patches and see if that fixes the issue.
