### ISSUE TITLE
um.multiply.reduce() produces wrong result: int overflow?

### ISSUE THREAD

**Issue by swilson314** [numpy/numpy#12664]
um.multiply.reduce() produces wrong result for some args. I found this via a call to np.resize() which failed in call to reshape():

    ValueError: cannot reshape array of size....

This works fine for smaller values, which makes me think this is an int overflow.

### Reproducing code example:

```python
import numpy.core.umath as um
# result should be 6087276620, but result on my machine is 1792309324
um.multiply.reduce((2715110, 2242))
```

### Numpy/Python version information:

1.14.3 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

**Comment by charris** [comment]
Integer overflow is the correct result for NumPy, it does modular arithmetic, as does C.

**Comment by swilson314** [comment]
In C I would be able to cast the ints to 64 bit. Is there a way to do that here?

**Comment by swilson314** [comment]
Haha. Indeed it works here too:

um.multiply.reduce((numpy.int64(2715110), 2242))

**Comment by eric-wieser** [comment]
`um.multiply.reduce((2715110, 2242), dtype=np.float64)` would work too

**Comment by swilson314** [comment]
@eric-wieser Yes, though I'm not sure how to do that in a call to np.resize() which doesn't appear to take a dtype arg.
