### ISSUE TITLE
Use reductions with where for nanfunctions

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#12662]
Reductions have gained a `where` keyword, which means that things like `nansum` can now be implemented more trivially as `np.sum(a, where=~np.isnan(a))`. This is faster than the current `nansum` implementation, which has to make a copy of `a` and then set elements of it to 0. It is a fairly straightforward change, but I'm raising the issue here rather than doing it as I don't quite have time for it myself. Specifically, what I think should be done is

1. [X] Add nanfunction benchmarks to `numpy/benchmarks/benchmarks`, for a range of conditions (small & large array; no `nan`, few `nan`, many `nan`). (EDIT: done in #12666)
2. [X] Implement a new `_nan_mask` function which returns `True` for dtype that do not have `nan` (integer, etc.), and `~np.isnan(array)` (or perhaps better `m = np.isnan(array); m = np.invert(m, out=m)`).
3. [ ] Replace `nansum`, etc., with something like `np.sum(array, where=_nan_mask(array))`, checking that timings actually improve.

**Comment by Apurv98** [comment]
Hi! I am new to open source contribution. Is it okay for me to work on it?

**Comment by aditipansari** [comment]
Hello, I am interested in solving this issue. I am an Outreachy applicant.

**Comment by mattip** [comment]
anyone who wishes to work on an issue should create a pull request with an honest attempt to solve the issue, in the first **comment** (not in the title of the pull request nor the commit message) cross reference this issue (i.e. `relates to #12662` or `fixes #12662`). From there we can help you once you have demonstrated that you understand the [workflow](http://www.numpy.org/devdocs/dev/gitwash/development_workflow.html), the idea behind the issue, and the solution to it.

**Comment by mhvk** [comment]
@aditipansari - great that you're willing to help. Note that there is a first attempt in #12801 - you could elaborate on that for the other functions.

**Comment by mhvk** [comment]
After a long discussion at https://mail.python.org/pipermail/numpy-discussion/2019-June/079633.html, the conclusion would seem to be that the benefits of cleaning up `nanfunctions` are not worth the complications of dealing with deprecations. For large arrays and/or speed, I guess the best bet is to use `Bottleneck`, or just write the one-liners outside of `nanfunctions`.

**Comment by eric-wieser** [comment]
In that thread, you say:

> One could also avoid the `.sum()` override altogether by doing `np.add.reduce(..., where=...)`, but this would probably break just as much.

Are you sure about that? My feeling is that most `__array_ufunc__` implementations will attempt to pass on the keyword argument and things will just work. If they don't work, then implementing `__array_function__` to provide an implementation would always be an option.

Perhaps worth trying for 1.18, just to get some feedback on whether downstream projects break.

**Comment by mhvk** [comment]
@eric-wieser - that's a good point. I'll re-open this issue temporarily and will try replacing @tylerjereddy's PR with one that just does that. Of course, for `Matrix`, there is no `__array_ufunc__`, but its `__array_wrap__` or `__array_finalize__` may well just do the right for tests to pass.

**Comment by mhvk** [comment]
OK, [tried](https://github.com/numpy/numpy/compare/master...mhvk:nanfunctions-using-where?expand=1). Still fails one of the `matrix` tests, where one sums over the second axis (since `__array_finalize__` cannot know which axis was summed over and thus expands the first).

In principle, not difficult to solve within `matrix`, but not sure we really want to touch that at all, yet even less interested in inserting work-arounds for it...
