### ISSUE TITLE
Numpy.Empty - Array Not Exactly Empty

### ISSUE THREAD

**Issue by rudrathegreat** [numpy/numpy#12661]
Hi NumPy Development Team!

I love NumPy! it helps me a lot indeed! But today, I was experimenting with my code which uses NumPy and there seems to be a bug. This is not so much an issue but a minor bug which I am sure the team can solve.

If my perception is correct, `numpy.empty` creates an empty array with a given shape. Well, this is unfortunately not the case for me. See, while I was debugging my code, I noticed something (which is mentioned under the heading Error Message).

### Reproducing code example:

```python
import numpy as np

a = np.empty(shape=(1, 4))
print(a)  # A way of debugging code
```

### Error message:

Not so much an error message, this is the output of the the Reproducing code example - 

```Python

[[2.96613498e-267 6.27289313e-043 1.17767301e-268 8.91241522e-313]]

```
### Numpy/Python version information:

numpy==1.15.4
python==3.5.2 or 3.7.0

### Related Issue

The following issue is related but the Python Version is 2.7 -  #9882

**Comment by eric-wieser** [comment]
This is working as intended, but perhaps we need to improve the done.

What output would you expect?

**Comment by rudrathegreat** [comment]
Something Like -

```Python

[[0 0 0 0]]

```

**Comment by eric-wieser** [comment]
That's what `np.zeros` is for

**Comment by rudrathegreat** [comment]
Ok. 

I was just reading the other issue which I referenced, turns out my perception was slightly off course. Just to let you know that I am still relatively new to NumPy. So the original intention of `numpy.empty` is to return a completely knew array, not exactly filled with zeros.

**Comment by eric-wieser** [comment]
Correct - `np.empty` just means "create an array, I don't care what values it contains because I'm going to replace all of them"

**Comment by rudrathegreat** [comment]
Thanks for helping me out!

**Comment by Vicky105** [comment]
I have an issue with NumPy's np.empty. Instead of generating random values, it is influenced by the previous output, which matches the empty array's dimensions. Has anyone else faced this issue before?

**Comment by charris** [comment]
@Vicky105 The empty array contains what happens to be in memory at those locations, which  depends on how memory is managed. Python, for instance, uses a cache for small objects to speed up allocation.

**Comment by Vicky105** [comment]
Thank you @charris
