### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [numpy/numpy#12673]
I would like to point out that identifiers like “[`_MULTIARRAYMODULE`](https://github.com/numpy/numpy/blob/464f79eb1d05bf938d16b49da1c39a4e02506fa3/numpy/core/include/numpy/arrayscalars.h#L4 "Update candidate")” and “[`_NPY_COMMON_H_`](https://github.com/numpy/numpy/blob/c6566b7d3724fe59c5e72a0eb393676ee7b70cc1/numpy/core/include/numpy/npy_common.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by charris** [comment]
PRs welcome.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by charris** [comment]
It doesn't matter in practice.

**Comment by elfring** [comment]
Would you like to achieve anyhow that [this software will become standard compliant](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by njsmith** [comment]
This is a strange way of having a conversation.

What Chuck is saying is that this is a very minor issue that's never caused any problems in practice, so it's unlikely that anyone will prioritize it. But if you'd like to do the work to clean it up and submit it as PRs then we'll consider them.

**Comment by charris** [comment]
@elfring It only becomes a problem if the compiler defines macros with those names, which is very unlikely.  Not using leading underscores in the names is good practice, but it only adds a bit of protection in practice. If the compilers themselves were to enforce such rules a *lot* of software would break.

**Comment by elfring** [comment]
>Not using leading underscores in the names is good practice, …

How does [this view](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Description for reserved identifiers") fit to source code from current (Python) software?

**Comment by njsmith** [comment]
I'm sorry, but it's not possible to have a useful conversation if all you're going to do is post cryptic questions with vaguely related links. If you want to participate here you need to do your fair share of communicating.

**Comment by elfring** [comment]
* Which details do you find “cryptic” from known programming language rules?
* Will the software development attention increase for such issues?

**Comment by mattip** [comment]
This is not how open source projects work. The [license](https://github.com/numpy/numpy/blob/master/LICENSE.txt#L20) reads **'THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"'**. No one is forcing you to use it. If you want something changed you have to 
- convince us it is important
- and usually provide a pull request to fix the issue yourself, which can be accepted or rejected totally at the discretion of the maintainers for the good of the community, as laid out in our [governing documents](http://www.numpy.org/devdocs/dev/governance/governance.html#consensus-based-decision-making-by-the-community).

You are not providing a convincing argument that this is important. A standard that goes against current industry-wide practice is not going to convince the maintainers. In the document you link to it points out the accepted use of leading `_` in macro names. Why should we change this? Is there a particular compiler this confuses? A platform where our style is problematic?

Neither are you providing a pull request fixing what you call a problem.

**Comment by mattip** [comment]
Hmm, it turns out we may be dealing with a bot GenericMappingTools/gmt#287

**Comment by elfring** [comment]
* I am curious on how the software development attention will evolve around [another bug report](https://bugs.python.org/issue35671 "reserved identifier violation").
* Do find any information relevant from [secure programming guidelines](https://wiki.sei.cmu.edu/confluence/display/c/SEI+CERT+C+Coding+Standard "SEI CERT C Coding Standard") (also for this issue)?

**Comment by njsmith** [comment]
@mattip how bizarre. I agree though, if you browse @elfring's "contributor activity" it looks pretty damning – lots of these identically vague reports and follow-up comments with maintainers getting angry at having their time wasted. Guess we should click the "report" button to alert github.

**Comment by rgommers** [comment]
Weird indeed. Not 100% sure though, since there are emails to Clang-dev with a similar communication style from 2013-2014 by someone with the same name: http://clang-developers.42468.n3.nabble.com/template/NamlServlet.jtp?macro=user_nodes&user=496047

@elfring please stop opening these issues, on this repository and any other repositories. You *are* wasting everyone's time. If you're not a bot, please educate yourself about how to communicate effectively with open source developers before doing anything else.

**Comment by elfring** [comment]
The change acceptance is evolving for various questionable implementation details of several software components over time, isn't it?

**Comment by rgommers** [comment]
Okay, I'm wrong:)

**Comment by rgommers** [comment]
user blocked

**Comment by eric-wieser** [comment]
@rgommers: You're not the first to come to that conclusion

From [this discussion](https://lkml.org/lkml/2017/11/28/690):

> > That said, I'm considering Markus Elfring being a human.
>
> Thanks for this view.

**Comment by rgommers** [comment]
@eric-wieser interestingly, that email has the suggestion
```
> it would be better to just setup a "tip bot for Markus
> Elfring" and let it send patches automatically.
```
so it may be a real human that's also operating a bot:)
