### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [numpy/numpy#12674]
Would you like to [add more error handling](https://github.com/numpy/numpy/blob/464f79eb1d05bf938d16b49da1c39a4e02506fa3/numpy/core/src/multiarray/usertypes.c#L221 "Update candidate: PyArray_RegisterCanCast()") for return values from functions like “[malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation")”?

**Comment by eric-wieser** [comment]
Your link doesn't point to a malloc, so there's nothing we can do here.

Assuming we missed one - then yes, we should call PyErr_NoMemory() if it fails. Feel free to open a new issue with more details on where the offending malloc is - or better, create a PR and fix it for us!

**Comment by elfring** [comment]
* How do you think about to [reconsider the implementation of a function like “PyArray_RegisterCanCast”](https://github.com/numpy/numpy/blob/464f79eb1d05bf938d16b49da1c39a4e02506fa3/numpy/core/src/multiarray/usertypes.c#L259 "Update candidate: PyArray_RegisterCanCast()")?
* Would you like to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by njsmith** [comment]
https://github.com/numpy/numpy/issues/12673#issuecomment-451731448

**Comment by eric-wieser** [comment]
PR made to address this in #12680 - it turns out that there were a lot of poorly handled allocations in that file.

@elfring, if you're posting these comments with a bot, please consider indicating so in your messages. Detecting this issue was helpful, but your tone is bizarre, and the follow-up comments are not helpful.
