### ISSUE TITLE
ENH: `median` should not warn about invalid values

### ISSUE THREAD

**Issue by Alexander-Shukaev** [numpy/numpy#12676]
The problem is that `median` would produce `RuntimeWarning` with the `Invalid value encountered in median for 2 results` message, while `mean` is silent about it.  Why?

### Reproducing code example:

```python
import numpy as np
a = np.array([[1, 4, 3, np.nan], [2, 5, np.nan, 4]])
m = mean(a, axis=1)
```

### Numpy/Python version information:

```
1.15.4 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831]
```

**Comment by Alexander-Shukaev** [comment]
It might also be an indication of poor design and/or missing consolidation of reusable code written by different people/times.

**Comment by mattip** [comment]
Indeed in both cases `np.nan` is returned, while only `np.median` prints a warning. Following the logic of [removing the warnings](12038) from `np.maximum`, `np.minimum` perhaps we should deprecate the warning from `np.median`

**Comment by mattip** [comment]
Changed title to put the emphasis on `median`
