### ISSUE TITLE
Tracking Issue for ppc64 continuous integration

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#12688]
Progress / tracking issue following a conference call today with @ipoddar-ibm from IBM along with @stefanv & @mattip regarding dev access to POWER arch machines as well as adding `numpy/numpy` to Travis CI runs that use genuine POWER arch / hardware (presumably ppc64le Linux instead of i.e., emulation).

For reference, @mattip provided some [open AIX issues](https://github.com/numpy/numpy/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+aix) and [open powerpc issues](https://github.com/numpy/numpy/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+powerpc).

**Comment by edelsohn** [comment]
I work at IBM Research and assist with the AIX VMs at OSUOSL. I can provide access to a VM.  Note that this is a raw AIX VM and one needs to install all of the necessary build software and perform normal system administration on the system.

Also, there are AIX systems in the GNU Compile Farm.  Depending on the load, you may be able to utilize the existing system.

**Comment by edelsohn** [comment]
Using the existing Travis CI beta support for PPC64LE Linux is completely separate and distinct from requesting PPC64LE Linux hosting at OSUOSL, although Travis CI itself leverages systems at OSUOSL for PPC64LE Linux.

**Comment by tylerjereddy** [comment]
Seems to be working already but I did ping for a brief check in the linked issue.

**Comment by ghatwala** [comment]
@tylerjereddy @gerrith3  - The travis job in @akhileshbhople's forked repo - https://github.com/akhileshbhople/numpy/blob/master/.travis.yml is already passing - https://travis-ci.org/akhileshbhople/numpy/builds/477287496 for both Intel and ppc64le. He would be raising PR here shortly to add power support in travis.yml .

**Comment by tylerjereddy** [comment]
I already did that in #12709 as far as I can tell -- seems to work.

**Comment by edelsohn** [comment]
For the AIX track, ATLAS BLAS supports AIX, but OpenBLAS currently does not have any support for AIX.

**Comment by ipoddar-ibm** [comment]
@tylerjereddy have you received the Linux and AIX VMs that you requested from OSU OSL?

**Comment by tylerjereddy** [comment]
I think @mattip requested / received them -- we'll see what he says.

Perhaps I should apply for accounts too.

**Comment by mattip** [comment]
I requested PPC64LE access, and got as far as the comment [above](https://github.com/numpy/numpy/issues/12688#issuecomment-452822109) from @ipoddar-ibm. 

I did not request AIX access.

**Comment by edelsohn** [comment]
IBM and OSUOSL were waiting for feedback if Travis-CI access was sufficient or you needed direct access to VMs for development.

@mattip You already should have access to the GNU Compile Farm systems, which include PPC64 Linux, through the PyPy accounts.

I'll tell OSUOSL to proceed with the NumPy VM.

**Comment by mattip** [comment]
@edelsohn Hi. Good to know that I already have access, although I admit I have never tried `ssh`ing in. Are there directions somewhere?

**Comment by edelsohn** [comment]
Are you asking about the GNU Compile Farm in general or PyPy access?

The Compile Farm is described at

https://gcc.gnu.org/wiki/CompileFarm

I don't know exactly which keys Fijal and Armin have been using.  I can add you to shrager's account or you can request your own.

Also, hopefully Lance will create the dedicated VM for NumPy this week, but it may be delayed because of FOSDEM.

**Comment by edelsohn** [comment]
Matti's VM should be deployed shortly.

**Comment by mattip** [comment]
I now have ssh access to a ppc64le machine.

**Comment by tylerjereddy** [comment]
Initial debug effort on ppc64le for SciPy `test_white_tophat03()` failure: 

https://github.com/scipy/scipy/pull/9684#issuecomment-466251057

Something about `np.bool_` and the data pointer iterations in the preprocessor macro described there seems a little off on ppc64le for some reason.

**Comment by tylerjereddy** [comment]
One thing that would be useful for me is access to static gfortran libraries built with `-fPIC`. `gcc112`compile farm machine uses CentOS7 with `4.8.5` toolchain version for gcc / gfortran.

I can manually pull in `libgfortran.a` without root using:
`yumdownloader libgfortran-static.ppc64le`
`rpm2cpio libgfortran-static-4.8.5-36.el7_6.1.ppc64le.rpm | cpio -idmv`

But that `libgfortran.a` was not built with `-fPIC` so statically linking in the gcc / gfortran runtime dependencies to OpenBLAS doesn't work.

I think newer version of GCC may have versions of `libgfortran.a` that are more suitable for this purpose since I've had success doing the static link with the 8.x toolchain series.

There are various debates about statically linking in to shared libraries, but for us it is something we are thinking about for OpenBLAS. See working example for macOS: https://github.com/numpy/numpy/pull/13191

**Comment by edelsohn** [comment]
Please use the GCC Compile Farm mailing list and ticketing system to request packages or system configuration changes.

**Comment by edelsohn** [comment]
gcc112 is a Power8 system.
gcc135 is a Power9 system.

Both systems have IBM Advance Toolchain installed, which are based on newer GCC with some backported optimizations.

I would recommend that you try /opt/at12.0/bin/{gcc,g++,gfortran} .  Note that libgfortran shared objects are installed in /opt/at12.0/lib64.

Also libgfortran shared objects for the system compiler (GCC 4.8.5) are installed in /usr/lib64 .

**Comment by tylerjereddy** [comment]
Thanks David--I'll take a look

I noticed that I can't seem to get `ppc64le` Travis CI node access using newer `travis-ci.com` app integration on a repo. In particular, I'm working on my fork of NumPy to reduce noise, etc., and while the `linux-ppc64le` mouseover *does* show up in the Travis matrix list, the machine is clearly `x86_64`.

Indeed, I've added an extra `lscpu` to the [PR in question](https://github.com/tylerjereddy/numpy/pull/6).

I'm pretty sure NumPy is using the older travis-ci.org "dispatch" mechanism, and that's the only difference I can think of between main repo and my fork.

**Comment by edelsohn** [comment]
I don't know how Travis CI Beta-level support for PPC64LE is integrated with OSUOSL backends, i.e., which level of Travis API they are running and how API compatibility is handled. This seems like a travis-ci.com bug and needs to be raised in travis-ci.com issue tracking system.

**Comment by tylerjereddy** [comment]
ok, done: https://travis-ci.community/t/ppc64le-arch-support-on-travis-ci-com-vs-travis-ci-org/2898

**Comment by ghatwala** [comment]
Hi @tylerjereddy - 
> I noticed that I can't seem to get ppc64le Travis CI node access using newer travis-ci.com app integration on a repo. In particular, I'm working on my fork of NumPy to reduce noise, etc., and while the linux-ppc64le mouseover does show up in the Travis matrix list, the machine is clearly x86_64

This is a known issue as travis-ci.com officially doesn't support "ppc64le" builds as of now , power jobs work only on travis-ci.org. The mouseover depicting "linux-ppc64le" in the matrix is an issue at Travis-ci.com. I think your forked repo could de deployed on "travis-ci.org" too .

**Comment by tylerjereddy** [comment]
Swapping back works, thanks @ghatwala 

I'll keep the discussion of `libgfortran.a` built with PIC mostly confined to the GCC compile farm emails for now--the Julia language has had similar issues: https://github.com/JuliaLang/julia/issues/326

**Comment by mattip** [comment]
Closing, as we have had no problems with the ppc64le CI process that is running on travis. The linalg backend is a separate issue.
