### ISSUE TITLE
array_split and split not working as expected with indices_or_sections = 1 

### ISSUE THREAD

**Issue by NumesSanguis** [numpy/numpy#12691]
I have a batch generator function, which returns data as batches (for deep learning).
The user can specify how many samples there should be in a single batch.
In the case of different lengths of the data (e.g audio of 5.3 sec, 6.2s, 4.7s), the batch size has to be 1.

`numpy.array_split()` and `numpy.split()` work as intended for `indices_or_sections > 1`, but not if set to `1`.

### Reproducing code example:

```python
import numpy as np
arr_test = np.array([3, 6, 2, 1])
arr_parts = np.array_split(arr_test, 1)
print(arr_parts)
```

### Expected output
```[array([3]), array([6]), array([2]), array([1])]```

### Actual output
```[array([3, 6, 2, 1])]```

### Works as intended with `indices_or_sections > 1`
input: `np.array_split(arr_test, 2)`
output: `[array([3, 6]), array([2, 1])]`

### Numpy/Python version information:

1.15.4 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]

**Comment by eric-wieser** [comment]
You're reading [the docs](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.split.html) incorrectly:

> `np.split`
>
> the array will be divided into N equal arrays along axis

N pieces, not pieces of size `n`. Try it with a longer array, and you'll work out what's going on. 4 was an unfortunate length to choose.

**Comment by NumesSanguis** [comment]
Sorry, I understood it wrong indeed. What I wanted to achieve is done with: `np.array_split(arr_test, 4)`. 4 being the total length of the array.
