### ISSUE TITLE
Incorrect code example for recfunctions.merge_arrays

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#12717]
https://docs.scipy.org/doc/numpy/user/basics.rec.html#numpy.lib.recfunctions.merge_arrays currently has the following snippet:
```
>>> from numpy.lib import recfunctions as rfn
>>> rfn.merge_arrays((np.array([1, 2]), np.array([10., 20., 30.])))
masked_array(data = [(1, 10.0) (2, 20.0) (--, 30.0)],
             mask = [(False, False) (False, False) (True, False)],
       fill_value = (999999, 1e+20),
            dtype = [('f0', '<i4'), ('f1', '<f8')])
```
but `merge_arrays` defaults to `usemask=False`, and indeed, running the code gives
```
In [1]: rfn.merge_arrays((np.array([1, 2]), np.array([10., 20., 30.])))
Out[1]: 
array([( 1, 10.), ( 2, 20.), (-1, 30.)],
      dtype=[('f0', '<i8'), ('f1', '<f8')])
```

Haven't checked the other examples, but probably a good idea too.

### Reproducing code example:

See above.

### Numpy/Python version information:

1.15.4 3.7.2 (default, Dec 29 2018, 21:15:15) 
[GCC 8.2.1 20181127]

**Comment by Dan-Patterson** [comment]
```
a   # array([1, 2])
b   #  masked_array(data=[-, 20.0, 30.0],
                mask=[ True, False, False],
               fill_value=1e+20)
ab = rfn.merge_arrays((a, b), usemask=True)
ab
masked_array(data=[(1, -), (2, 20.0), (-, 30.0)],
             mask=[(False,  True), (False, False), ( True, False)],
       fill_value=(999999, 1.e+20),
            dtype=[('f0', '<i4'), ('f1', '<f8')])
```
You are correct, the declaration does need to be overt and the above help is misleading.

**Comment by anntzer** [comment]
Note, by the way, that `merge_arrays` appears to be the *only* function in recfunctions where usemask defaults to False (which is a saner default IMO, but YMMV).  Would be nice if this was more consistent...

**Comment by yashasvimisra2798** [comment]
Upon looking at the current documentation, it looks like this issue is not relevant anymore. Correct me if I am wrong.

**Comment by rgommers** [comment]
@yashasvimisra2798 yes, you are right. The documentation example now matches the actual behavior. The masked element is `-1` not `--` anymore. I'll close it. Thanks for looking into this!
