### ISSUE TITLE
utcfromtimestamp for numpy arrays

### ISSUE THREAD

**Issue by haimivan** [numpy/numpy#12726]
Hi,

I am missing a conversion from float to a datetime.datetime column as a numpy function. See also https://stackoverflow.com/questions/52781113/what-is-the-quickest-way-to-get-a-datetime-from-a-numpy-timestamp-array .

Example:

With the following snippet, I would like to convert a numpy array column of timestamps (formatted as floats) to a datetime.datetime column.

The function `datetime.datetime.utcfromtimestamp()` apparently only works for scalars. 

Which numpy function do I have to use to achieve this conversion?

    my_datetime = datetime.datetime.strptime("31.12.1999 23:59:12", "%d.%m.%Y %H:%M:%S")
    a = np.empty((0, 3))
    a = np.insert(a, a.shape[0], [[my_datetime.timestamp(), 1, 1]], axis=0)
    a = np.insert(a, a.shape[0], [[my_datetime.timestamp(), 1, 1]], axis=0)
    print(datetime.datetime.utcfromtimestamp(a[:,0:1]))
    
    >>TypeError: only size-1 arrays can be converted to Python scalars

Or is there another easy way to perform this?

**Comment by eric-wieser** [comment]
If you want a numpy datetime, you can use:
```python
>>> a[:,0:1].astype('datetime64[s]')
array([['2000-01-01T07:59:12'],
       ['2000-01-01T07:59:12']], dtype='datetime64[s]')
```

or if you want microsecond precision:
```python
>>> (a[:,0:1]* 1000000).astype('datetime64[us]')
array([['2000-01-01T07:59:12.000000'],
       ['2000-01-01T07:59:12.000000']], dtype='datetime64[us]')
```

If you want pure-python datetimes, you can use vectorize:
```python
>>> np.vectorize(datetime.datetime.utcfromtimestamp)(a[:,0:1])
array([[datetime.datetime(2000, 1, 1, 7, 59, 12)],
       [datetime.datetime(2000, 1, 1, 7, 59, 12)]], dtype=object)
```

For future reference, questions like this would be better directed to StackOverflow
