### ISSUE TITLE
np.array(..., dtype=np.float32).astype(np.float16) doesn't handle denorms properly

### ISSUE THREAD

**Issue by DickJC123** [numpy/numpy#12721]
The smallest denorm value that can be held in a np.float16 is 2**-24.  The value 2**-25 is halfway between 0 and 2**-24, but is rounded down to 0 when converted to a np.float16 because of the rule to round to the nearest even-lsb value in the case of ties.  However, any value that is slightly above 2**-25 should be rounded up to 2**-24.  The following interpreter sequence shows such a case that is properly handled by the float64->float16 conversion, but not by the float32->float16 conversion (see the last line below).
```
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.14.3'
>>> '%.40f' % np.array([2**-24]).astype(np.float64)[0]
'0.0000000596046447753906250000000000000000'
>>> '%.40f' % np.array([2**-24]).astype(np.float32)[0]
'0.0000000596046447753906250000000000000000'
>>> '%.40f' % np.array([2**-24]).astype(np.float16)[0]
'0.0000000596046447753906250000000000000000'
>>> '%.40f' % np.array([2**-25]).astype(np.float64)[0]
'0.0000000298023223876953125000000000000000'
>>> '%.40f' % np.array([2**-25]).astype(np.float32)[0]
'0.0000000298023223876953125000000000000000'
>>> '%.40f' % np.array([2**-25]).astype(np.float16)[0]    # OK: expected flush to 0
'0.0000000000000000000000000000000000000000'
>>> '%.40f' % np.array([2**-25 + 2**-38]).astype(np.float64)[0]
'0.0000000298059603665024042129516601562500'
>>> '%.40f' % np.array([2**-25 + 2**-38]).astype(np.float32)[0]
'0.0000000298059603665024042129516601562500'
>>> '%.40f' % np.array([2**-25 + 2**-38]).astype(np.float64).astype(np.float16)[0]    # OK: 2**-24
'0.0000000596046447753906250000000000000000'
>>> '%.40f' % np.array([2**-25 + 2**-38]).astype(np.float32).astype(np.float16)[0]    # not OK: should be 2**-24
'0.0000000000000000000000000000000000000000'
>>> 
```

**Comment by seberg** [comment]
I think the reason for this is that all float16 operations use float32 internally, so this probably goes via float32:
```python
'%.40f' % np.array([2**-25 + 2**-38]).astype(np.float64).astype(np.float16)[0]  
# '0.0000000596046447753906250000000000000000'
'%.40f' % np.array([2**-25 + 2**-38]).astype(np.float64).astype(np.float32).astype(np.float16)[0]
# '0.0000000000000000000000000000000000000000'
```

**Comment by seberg** [comment]
Sorry, that was nonsense...

**Comment by seberg** [comment]
So I think at the poin where it rounds up, some of the last bits are lost already. The same effect happens with float64 when you reach `np.array([2**-25 + 2**-65]).astype(np.float64)`, just much later of course. Not sure what should be expected here or not.

**Comment by seberg** [comment]
The bit foo is not that strong with me, but the below fix would fix it, on my computer with only about 2% speed penalty for the denormal casts above:

<details>

```diff
diff --git a/numpy/core/src/npymath/halffloat.c b/numpy/core/src/npymath/halffloat.c
index ac8b2adb6..c2bd28d60 100644
--- a/numpy/core/src/npymath/halffloat.c
+++ b/numpy/core/src/npymath/halffloat.c
@@ -279,7 +279,6 @@ npy_uint16 npy_floatbits_to_halfbits(npy_uint32 f)
 
     /* Exponent underflow converts to a subnormal half or signed zero */
     if (f_exp <= 0x38000000u) {
-        unsigned char shift;
         /*
          * Signed zeros, subnormal floats, and floats with small
          * exponents all convert to signed zero half-floats.
@@ -302,6 +301,7 @@ npy_uint16 npy_floatbits_to_halfbits(npy_uint32 f)
             npy_set_floatstatus_underflow();
         }
 #endif
+        f_sig >>= (113 - f_exp);
         /* Handle rounding by adding 1 to the bit beyond half precision */
 #if NPY_HALF_ROUND_TIES_TO_EVEN
         /*
@@ -309,17 +309,13 @@ npy_uint16 npy_floatbits_to_halfbits(npy_uint32 f)
          * the remaining bit pattern is 1000...0, then we do not add one
          * to the bit after the half significand.  In all other cases, we do.
          */
-        shift = 16 - (113 - f_exp);
-        if ((f_sig & (0x3fffffffu >> shift)) != (0x10000000u >> shift)) {
-            f_sig += 0x10000000u >> shift;
+        if ((f_sig&0x00003fffu) != 0x00001000u) {
+            f_sig += 0x00001000u;
         }
-        h_sig = (npy_uint16) (f_sig >> (126 - f_exp));
-
 #else
-        f_sig >>= (113 - f_exp);
         f_sig += 0x00001000u;
-        h_sig = (npy_uint16) (f_sig >> 13);
 #endif
+        h_sig = (npy_uint16) (f_sig >> 13);
         /*
          * If the rounding causes a bit to spill into h_exp, it will
          * increment h_exp from zero to one and h_sig will be zero.

```
</details>

Basically, the current code will make a preliminary denormal representation by shifting the significant by `113-exponent` (and setting the most significant bit), at that point it is still at a higher precision, but a few bits get lost at that. So the above diff moves the rounding logic into the original precision instead. But not sure I am happy with that (same thing needs to be done for float64 of course)...

**Comment by seberg** [comment]
I wonder if there isn't some nice more modern code out there we can steal, didn't find some quickly though. Maybe hdf5 has it or so, I had found [this at stackoverflow](https://stackoverflow.com/a/3542975/455221) but it does not get this right... There must be a few implementations out there?

**Comment by seberg** [comment]
Silly me, I think I found a minimal fix will probably create a PR soon. But if there is nice code to replace it all out there, that would also be good.

**Comment by seberg** [comment]
@DickJC123 since I guess you have some experience with half's. I put up a fix in gh-12722 if you have some time to take a look, that would be great!
