### ISSUE TITLE
linalg.eigh raises LinAlgError: Eigenvalues did not converge but scipy.linalg.eigh works

### ISSUE THREAD

**Issue by maxnus** [numpy/numpy#12738]
I have a problem diagonalizing a 4200 by 4200 symmetric real matrix, as `numpy.linalg.eigh` raises `numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge`. On the other hand `scipy.linalg.eigh` works with the same matrix.

### Reproducing code example:

I created a GitHub gist here: [link](https://gist.github.com/Majokux/d6a418f36595fad228b0d95c230906c9).

It creates the matrix using some of its internal symmetries. It requires the `npz` file from above gist, however.

```python3
import numpy as np
import scipy
import scipy.linalg

data = np.load("data.npz")
block00 = data["block00"]
block01 = data["block01"]
block11_diag = data["block11_diag"]

n0 = block00.shape[-1]
n1 = len(block11_diag)

def make_matrix(block00, block11_diag, block01):
    n = n0 * (n1+1)
    mat = np.zeros((n, n))
    p = range(n0)
    mat[np.ix_(p, p)] = block00
    for i in range(1, n0):
        a = range(n0+i*n1, n0+(i+1)*n1)
        b = range(i, i+1)
        mat[np.ix_(a, a)] = np.diag(block11_diag)
        mat[np.ix_(b, a)] = block01
        mat[np.ix_(a, b)] = block01.T
    return mat

mat = make_matrix(block00, block11_diag, block01)

print("mat.shape: {}".format(mat.shape))
print("np.all(mat - mat.T == 0.0): {}".format(np.all(mat.T - mat == 0.0)))
print("isfinite(mat): {}".format(np.all(np.isfinite(mat))))

# SciPy
scipy_eig, scipy_vec = scipy.linalg.eigh(mat)

# NumPy
numpy_eig, numpy_vec = np.linalg.eigh(mat)
```

### Error message:

```Traceback (most recent call last):
  File "run.py", line 43, in <module>
    numpy_eig, numpy_vec = np.linalg.eigh(mat)
  File "/apps/numpy/1.15.4/openblas/0.3.3-openmp/lib/python3.5/site-packages/numpy-1.15.4-py3.5-linux-x86_64.egg/numpy/linalg/linalg.py", line 1410, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
  File "/apps/numpy/1.15.4/openblas/0.3.3-openmp/lib/python3.5/site-packages/numpy-1.15.4-py3.5-linux-x86_64.egg/numpy/linalg/linalg.py", line 95, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge
```

### Numpy/Python version information:

1.15.4 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]

**Comment by helloworldexpert** [comment]
Hi Majokux,

It's been a while since you opened this issue, so I hope you solved the problem already. If not, did you ensure that you are using the latest versions of numpy and scipy? I ran the code with the given .npz file without issue. Both .eigh calculations converged to the same eigenvalues and eigenvectors.

Good luck!

**Comment by rgommers** [comment]
This is from >10 minor releases ago (and OpenBLAS is 21 releases further along. So this is almost certainly fixed - I'll close this issue. Thanks both.
