### ISSUE TITLE
BUG?: np.percentile `nan` invalid-value warning removed in 1.17dev

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#12737]
On 1.16.x:
```
>>> np.percentile([1, np.nan], 1)
/home/larsoner/python/numpy/numpy/lib/function_base.py:3821: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)
nan
```
On `master` no warning is emitted. This is breaking a [warning check in scipy](https://travis-ci.org/scipy/scipy/jobs/479387913#L1378-L1381). Is this change intended? If so, I can change the SciPy test in some suitable way, either by emitting our own warning or by asserting the number of warnings is zero if the numpy version is 1.17 or later.

**Comment by mattip** [comment]
yes that on purpose by #12679. The warning was redundant, the value returned is `np.nan`

**Comment by larsoner** [comment]
Okay, thanks for the quick clarification!

**Comment by madphysicist** [comment]
I'll work in a patch shortly.

**Comment by larsoner** [comment]
@madphysicist a fix has been merged in https://github.com/scipy/scipy/pull/9681 already
