### ISSUE TITLE
ndarray.__reduce_ex__ doesn't check return value of PickleBuffer.__new__

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#12745]
When taking a buffer out of an array fails, `__reduce_ex__` raises SystemError instead of propagating the error:
```python
>>> import numpy as np                                                                                                                                    
>>> d = np.datetime64('2015-07-04 12:59:59.50', 'ns')                                                                                                     
>>> a = np.array([d])                                                                                                                                     
>>> memoryview(a)                                                                                                                                         
Traceback (most recent call last):
  File "<ipython-input-4-dd900d27ccee>", line 1, in <module>
    memoryview(a)
ValueError: cannot include dtype 'M' in a buffer

>>> a.__reduce_ex__(5)                                                                                                                                    
Traceback (most recent call last):
  File "<ipython-input-5-b4bdda9e83c1>", line 1, in <module>
    a.__reduce_ex__(5)
SystemError: <built-in function __import__> returned a result with an error set
```

This is because in the C function `array_reduce_ex`, the result of calling the `PickleBuffer` constructor is not checked for NULL, so the original error is ignored and the interpreter ultimately complains.

(this is related to but distinct from https://github.com/numpy/numpy/issues/4983#issuecomment-441332940)

Note: you need `pickle5` installed to reproduce.

**Comment by pitrou** [comment]
@ogrisel @pierreglaser

**Comment by pitrou** [comment]
What `__reduce_ex__` should probably do instead is, when creating the `PickleBuffer` fails, fall back to the protocol 4 implementation.

**Comment by pierreglaser** [comment]
yes indeed. I'll add a `NULL` check and update the error indicator.

**Comment by pitrou** [comment]
@pierreglaser I'm working on this already :-)

**Comment by jakirkham** [comment]
@pitrou, somewhat orthogonal, but do you know if there is any plan to add support for datetime and timedelta to Python's buffer protocol?

**Comment by pitrou** [comment]
I don't think there is any. `datetime64` and `timedelta64` are somewhat Numpy-specific (also, I had the impression they were still more or less experimental, or perhaps considered to be ill-designed). @skrah might have more insight.

**Comment by skrah** [comment]
No, I haven't heard of any plan either.  Full support with `tolist()` etc. would take a huge amount of code for *interpreting* the `int64`.

`memoryview` should silently accept `M`; it also accepts some `ctypes` formats that it cannot interpret.

I only know that whenever time/date related issues come up on the Python mailing lists, there always seems to be a huge controversy.  Personally, I like Bernstein's `tai64n`, which is larger than `datetime` but IMHO easier to interpret.
