### ISSUE TITLE
pypy3: package import fails in 1.16.0 where it passed in 1.15

### ISSUE THREAD

**Issue by jnothman** [numpy/numpy#12740]
Scikit-learn was successfully testing on pypy3 with numpy 1.15 (https://circleci.com/gh/scikit-learn/scikit-learn/43203) but fails during installation when numpy is imported with version 1.16 (https://circleci.com/gh/scikit-learn/scikit-learn/43335).

```
Installing collected packages: scikit-learn
  Running setup.py develop for scikit-learn
    Running command /root/project/pypy-env/bin/pypy3 -c "import setuptools, tokenize;__file__='/root/project/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/project/setup.py", line 243, in <module>
        setup_package()
      File "/root/project/setup.py", line 216, in setup_package
        numpy_status = get_numpy_status()
      File "/root/project/setup.py", line 149, in get_numpy_status
        import numpy
      File "/root/project/pypy-env/site-packages/numpy/__init__.py", line 142, in <module>
        from . import core
      File "/root/project/pypy-env/site-packages/numpy/core/__init__.py", line 16, in <module>
        from . import multiarray
      File "/root/project/pypy-env/site-packages/numpy/core/multiarray.py", line 44, in <module>
        arange.__module__ = 'numpy'
    AttributeError: readonly attribute '__module__'
```

This issue was introduced in 4d24bbda32d133d51940b0691bd9b428d4198eaa

**Comment by mattip** [comment]
You need to either use a nightly build of PyPy from http://buildbot.pypy.org/nightly/py3.5/pypy-c-jit-latest-linux64.tar.bz2 or pin NumPy to 1.15.4. The last released pypy3 has a bug that makes `__module__` read-only. In [PR #12594](https://github.com/numpy/numpy/pull/12594/files#diff-8e7291644e10593b50dd6724286f5c44) there is a script to download, unpack, and setup that nightly

**Comment by larsoner** [comment]
FYI I adapted the code from the linked NumPy PR [for SciPy](https://github.com/scipy/scipy/pull/9700) and things look green again over there -- thanks for the info everyone.

**Comment by rgommers** [comment]
This seems to be addressed, closing.
