### ISSUE TITLE
Feature: possibility to ignore data in `np.frombuffer` etc.

### ISSUE THREAD

**Issue by MaxNoe** [numpy/numpy#12747]
Is it possible to ignore data, when using `np.from...`, e.g. `np.frombuffer`?

Simple example, I have binary data representing two columns, but I'm only interested in one.
The actual use case for me involves a much more complex dtype, so slicing is not an option.

```python
import numpy as np

data = np.random.normal(size=10).tobytes()

# read both columns:
a = np.frombuffer(data, dtype=[('x', 'f8'), ('y', 'f8')])

# Would be nice, only to read y: None, or some othe special value?
b = np.frombuffer(data, dtype=[(None, 'f8'), ('y', 'f8')])
```

The python standard library struct use `'x'` to denote padding bytes:
https://docs.python.org/3/library/struct.html#format-characters

**Comment by mhvk** [comment]
You can pass in offsets to a dtype. Following the example in the docstring of `np.dtype` (for when the dtype is given as a dict):
```
In [4]: np.frombuffer(data, dtype={'y': ('f8', 8)})
Out[4]: 
array([( 1.80441619,), (-0.69647703,), (-2.11883599,), ( 0.52758458,),
       (-1.75860011,)],
      dtype={'names':['y'], 'formats':['<f8'], 'offsets':[8], 'itemsize':16})
```

**Comment by mhvk** [comment]
p.s. The dict version where one passes in names, formats, and offsets is perhaps clearer. https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html#specifying-and-constructing-data-types

**Comment by MaxNoe** [comment]
Nice, thank you!

**Comment by mattip** [comment]
Closing, please reopen if there is more to say here
