### ISSUE TITLE
Change indices in numpy.diff docstring to not use variable 'n' which is a function parameter

### ISSUE THREAD

**Issue by ajschol** [numpy/numpy#12742]
https://github.com/numpy/numpy/blob/ccfbcc1cd9a4035a467f2e982a565ab27de25b6b/numpy/lib/function_base.py#L1079-L1176

The current docstring for numpy.diff states 
'The first order difference is given by out[n] = a[n+1] - a[n] along the given axis, higher order differences are calculated by using diff recursively.'
This phrasing is confusing because n is a function parameter with a fixed value, however, here the implied meaning is that n varies from 0 to len(a) - 1 (along the given axis).

Recommend the statement be changed to use a "typical" index variable not in the function signature, such as 'i':
'The first order difference is given by out[i] = a[i+1] - a[i] along the given axis, higher order differences are calculated by using diff recursively.'

**Comment by seberg** [comment]
Changed in the gh-12758.
