### ISSUE TITLE
Problem in the documentation of numpy.random.randint in python 2.7

### ISSUE THREAD

**Issue by jaypokarna067** [numpy/numpy#12746]
Official Documentation of python 2.7 mentions that numpy.random.randint(a,b) will return a random integer from N such that a<=N<=b. But I have run the code and I have found that it never returns equal to b. So, what I did was I ran numpy.random.randint(0,1) for 50 milion times and finally printed the sum. 

I don't know if this a documentation or an implementation issue, but this is an issue which needs to be looked at. Below is the code that I ran.

The output was 0.

### Reproducing code example:

import numpy as np
x = np.random

sum = 0
count = 0
sum += x.randint(0,1)

while(count<50000000):
    sum += x.randint(0,1)
    count += 1

print(sum)

**Comment by jaypokarna067** [comment]
I have checked it and the same issue exists for python 3.7 also. I am using a Mac.

**Comment by seberg** [comment]
@jaypokarna067 is it possible you are confusing the documentation of `randint` and `random_integers`? Or I guess pythons `random.randint` which is different from numpy's? Maybe `np.random.randint` could get a note about this difference, want to write one?
