### ISSUE TITLE
Updates to `nditer` docs?

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#12764]
I was looking through the instructions on how to use `flags=['multi_index']` at https://docs.scipy.org/doc/numpy/reference/arrays.nditer.html#tracking-an-index-or-multi-index. The recommended way of doing

```
it = np.nditer(a, flags=['multi_index'], op_flags=['writeonly'])
with it:
    while not it.finished:
        it[0] = it.multi_index[1] - it.multi_index[0]
        it.iternext()
```

seems a bit stilted and unpythonic, given that you can avoid iterating manually at all:

```
it = np.nditer(a, flags=['multi_index'], op_flags=['writeonly'])
with it:
    for x in it:
        x[...] = it.multi_index[1] - it.multi_index[0]
```

This description appears for all versions at least up to 1.16.0.

I agree that the alternative looping notation should be mentioned, perhaps in a section on "Fine Grained Loop Control" or "Alternative Iteration Method" or something similar, but it's not necessary to show the feature as the only way of iterating with an index.

If my suggestion meets with a favorable response, I'd be happy to submit a patch. Or I can do that if you just want to see whatI had in mind.

This issue is based on my answer to https://stackoverflow.com/q/54220875/2988730

Another item that came up in the same answer is that at least in version 1.12.0, `nditer` was not a context manager and did not have a close method. I propose adding some `since 1.1....` tags in a few places to document this explicitly.

**Comment by mhvk** [comment]
I think your version of the example is indeed clearer.

**Comment by seberg** [comment]
I agree, lets change it. The current version probably makes only sense for similarity with the C-API...
