### ISSUE TITLE
Issue with _type_aliases.py

### ISSUE THREAD

**Issue by nateGeorge** [numpy/numpy#12775]
There seems to be a bug in _type_aliases.py, where the values in `_concrete_items` (which is `typeinfo` from multiarray) seem to be tuples, and the code is trying to access the `type` property from these tuples.

I've seen another [person with the same error](https://stackoverflow.com/questions/54200850/attributeerror-tuple-object-has-no-attribute-type-upon-importing-tensorflow/54227655#54227655).  The fix seems to be downgrading to 1.15.4.  `pip install numpy==1.15.4`.

### Reproducing code example:

```python
import numpy
```

### Error message:

```python
Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy                                                            
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d4cdadb62aa7> in <module>
----> 1 import numpy

/usr/local/lib/python3.6/dist-packages/numpy/__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

/usr/local/lib/python3.6/dist-packages/numpy/core/__init__.py in <module>
     55 from . import umath
     56 from . import _internal  # for freeze programs
---> 57 from . import numerictypes as nt
     58 multiarray.set_typeDict(nt.sctypeDict)
     59 from . import numeric

/usr/local/lib/python3.6/dist-packages/numpy/core/numerictypes.py in <module>
    109 )
    110 
--> 111 from ._type_aliases import (
    112     sctypeDict,
    113     sctypeNA,

/usr/local/lib/python3.6/dist-packages/numpy/core/_type_aliases.py in <module>
     61         _concrete_typeinfo[k] = v
     62 
---> 63 _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
     64 
     65 

/usr/local/lib/python3.6/dist-packages/numpy/core/_type_aliases.py in <setcomp>(.0)
     61         _concrete_typeinfo[k] = v
     62 
---> 63 _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
     64 
     65 

AttributeError: 'tuple' object has no attribute 'type'
```

### Numpy/Python version information:

Python 3.6.8
Numpy 1.16.0

sys.version output: '3.6.8 (default, Dec 24 2018, 19:24:27) \n[GCC 5.4.0 20160609]'

**Comment by eric-wieser** [comment]
> where the values in _concrete_items (which is typeinfo from multiarray) seem to be tuples,

This is because you have the wrong version of multiarray. They are not tuples in 1.16.0. You have somehow ended up with multiple numpy versions installed over each other.

**Comment by nateGeorge** [comment]
I see, thanks.  I should've know there wouldn't be any bugs in a release.  It turns out even after uninstalling numpy with pip and apt-get on Ubuntu, there was still a numpy folder under /usr/local/lib/python3.6/dist-packages.  I had to go and manually delete that, then after reinstalling it was all good.

**Comment by eric-wieser** [comment]
Sounds like we need to take detecting conflicting installations more seriously

**Comment by mattip** [comment]
@nateGeorge what version of `pip` are you using?

**Comment by mattip** [comment]
xref issue #12736
I don't think the `multiarray` detection "fix" in #12763 would have caught this error.

**Comment by nateGeorge** [comment]
@mattip Using the latest, 18.1 on Ubuntu 16.04.

**Comment by charris** [comment]
> I should've know there wouldn't be any bugs in a release.

There are usually bugs in the `*.*.0` releases, there aren't enough people testing the pre-releases to find them earlier. Thanks for testing and for the feedback.

**Comment by bwanglzu** [comment]
my solution..
1. sudo pip3 uninstall numpy
2. sudo pip3 uninstall numpy
.... do this until you can not uninstall numpy anymore
3. sudo pip3 install -U numpy

ubuntu 18.04, python 3.5.

**Comment by eAi** [comment]
I just came across this issue, upgrading a pretty old version of numpy to latest. Uninstalling, deleting the site-packages folder and reinstalling as @bwanglzu suggested above worked.

macOS 10.13.6, python 2.7.14.
