### ISSUE TITLE
Dtype.base attribute not documented

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#12786]
dtype instances have a `base` attribute that, I think, is meant to be the "base dtype" for subarrays. It is, however, not documented, leading to hesitation with and confusion about its use.  See
https://stackoverflow.com/questions/52476601/purpose-status-of-the-attribute-numpy-dtype-base and https://github.com/astropy/astropy/pull/8353#issuecomment-454945823

My sense is that it is useful and should just be documented properly.

**Comment by eric-wieser** [comment]
I've found myself using `.subdtype` instead, which contains the same info

**Comment by eric-wieser** [comment]
I think base also means something different for structured types, especially weird ones like `dtype((int, [('a', int)]))`

**Comment by mhvk** [comment]
`base` has the advantage over `subdtype` that it is also defined for dtypes, so if one just cares about the type of data and not its shape (as in the astropy issue), then it is easier.

Of course, main point here is that any exposed attribute should be documented (even if we decide one better not use it!)
