### ISSUE TITLE
Errors passing file-like objects to numpy.save and numpy.load

### ISSUE THREAD

**Issue by tom-new** [numpy/numpy#12780]
## **numpy.save**

Using numpy.save (and numpy.savez) with an open file as the first argument throws an unexpected TypeError, given that the documentation states (emphasis mine):

Either the file name (string) **or an open file (file-like object)** where the data will be saved. If file is a string or a Path, the .npz extension will be appended to the file name if it is not already there.

### Reproducing code example:
```python
import numpy as np
test_path = "test.npy"
test_data = np.random.rand(100)
with open(test_path, "w") as test_file:
    np.save(test_file, test_data)
```

### Error message:
```
Traceback (most recent call last):
  File "save-test.py", line 5, in <module>
    np.save(test_file, test_data)
  File "/home/tom/anaconda3/envs/geopy/lib/python3.7/site-packages/numpy/lib/npyio.py", line 491, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/tom/anaconda3/envs/geopy/lib/python3.7/site-packages/numpy/lib/format.py", line 555, in write_array
    version)
  File "/home/tom/anaconda3/envs/geopy/lib/python3.7/site-packages/numpy/lib/format.py", line 328, in _write_array_header
    fp.write(header_prefix)
TypeError: write() argument must be str, not bytes
```

### Numpy/Python version information:
1.11.3 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:33:04) 
[GCC 7.3.0]

-----------------------
## **numpy.load**

When attempting to use numpy.load in the same way as above, the code in my project throws a UnicodeDecodeError. I have been unable to reproduce this exact error in an isolated snippet, but nevertheless an error is still thrown by code below. I suspect these issues are related, since using the path string instead of the open file object solves both errors.

### Reproducing code example:
```python
import numpy as np
test_path = "test.npy"
with open(test_path, "r") as test_file:
    test_data = np.load(test_file)
```

### Error message:
```
Traceback (most recent call last):
  File "load-test.py", line 4, in <module>
    test_data = np.load(test_file)
  File "/home/tom/anaconda3/envs/geopy/lib/python3.7/site-packages/numpy/lib/npyio.py", line 392, in load
    fid.seek(-N, 1)  # back-up
io.UnsupportedOperation: can't do nonzero cur-relative seeks
```

**Comment by seberg** [comment]
If you open the file yourself, you have to open it with `"wb"`, since you need to write binary data. If the documentation is not clear about it, I would appreciate it a lot if you can create a small PR to make it more clear (you can even do that by using the edit button on the github website).
