### ISSUE TITLE
numpy.fft.fft fails on odd-length arrays longer than 2^24 elements

### ISSUE THREAD

**Issue by thevorpalblade** [numpy/numpy#12795]
When performing a FFT on an array of odd length greater than 2^24, numpy raises a ValueError:
`ValueError: Internal error occurred, status=-1`
Notably, an array of length 2**24 - 1 or smaller is fine, as is an array of any even length. 

### Reproducing code example:

```python
import numpy as np
x = np.empty(2**24 + 1)                                                                                                                   
np.fft.fft(x)  
```

### Error message:

```                                                                                                                        
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-2ca28be828ef> in <module>
----> 1 np.fft.fft(x)

/opt/anaconda/lib/python3.6/site-packages/mkl_fft/_numpy_fft.py in fft(a, n, axis, norm)
    156 
    157     """
--> 158     output = mkl_fft.fft(a, n, axis)
    159     if _unitary(norm):
    160         output *= 1 / sqrt(output.shape[axis])

mkl_fft/_pydfti.pyx in mkl_fft._pydfti.fft()

mkl_fft/_pydfti.pyx in mkl_fft._pydfti._fft1d_impl()

ValueError: Internal error occurred, status=-1
```
### Numpy/Python version information:
Numpy  1.15.4
Python 3.6.8

**Comment by charris** [comment]
Looks like an MKL problem. Where did you get NumPy?

**Comment by thevorpalblade** [comment]
This is an Anacodna distributed numpy. I just checked wtih my system numpy library (distributed by Arch) and it works fine! So indeed, this seems to be upstream.

**Comment by charris** [comment]
Not sure of the best way to handle these bug reports. Anaconda sounds like the place to start. @stefanv  There seem to be several Intel related repositories on Github, maybe we should ask that they set one up for NumPy related issues. @thevorpalblade It would probably be a good idea to make sure your Anaconda install is up to date before following this up.

**Comment by grlee77** [comment]
Based on the traceback, it looks like the issue should probably just be raised at the mkl_fft repository:
https://github.com/IntelPython/mkl_fft

**Comment by thevorpalblade** [comment]
Looks related to:
https://github.com/IntelPython/mkl_fft/issues/24
So I'll probably assume it's covered by that bug report until I find out otherwise. Thanks!
