### ISSUE TITLE
Issue with importing numpy

### ISSUE THREAD

**Issue by VinhVu95** [numpy/numpy#12792]
Get this error message when try to import numpy (and other lib have dependency on numpy) - version 1.14.0:

"Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy...
Original error was: DLL load failed: The specified path is invalid."

I am using Python from <USERPATH>\Anaconda\python.exe (the only Python version in my machine - 3.6), install the package using pip, reinstall many times with forcing updated version, even reinstall Anaconda but does not work.

I am using company Pypi internal repo so not allow accesses to outside resource. My colleague who having the same installment but his numpy works normally.

**Comment by VinhVu95** [comment]
> Does your installation path contain spaces or unicode characters?

Sorry I am not sure what you meant by this

**Comment by mattip** [comment]
> The system path includes `<USER_DRIVE>\Continuum\Anaconda\Scripts`

I mean are there any spaces or non-ascii characters in <USER_DRIVE>?

**Comment by VinhVu95** [comment]
No there is not!

**Comment by mattip** [comment]
Closing.
