### ISSUE TITLE
Corner case in reduce()

### ISSUE THREAD

**Issue by skrah** [numpy/numpy#12798]
I wonder if the following is intentional; I would have expected that `add.reduce()` returns the identity element in both cases:

```
>>> x = np.array([[]])
>>> y = x[1:0]
>>> y
array([], shape=(0, 0), dtype=float64)
>>> np.add.reduce(y)
array([], dtype=float64)
>>> 
>>> y = np.array([])
>>> np.add.reduce(y)
0.0
```

**Comment by seberg** [comment]
Seems consistent to me, since `reduce` appears to default to `axis=1`, so the other axes must remain unchanged (and thus 0). The, I guess correct but funny other version is:
```
In [3]: np.add.reduce(np.ones((0, 0)), keepdims=True)                                                                   
Out[3]: array([], shape=(1, 0), dtype=float64)
```
"deleting" the "scalar".

This one looks a bit stranger to me:
```
In [4]: np.add.reduce(np.ones((0, 0)), keepdims=True, axis=(0, 1))                                                      
Out[4]: array([[0.]])
```
but I guess it is consistent.

**Comment by seberg** [comment]
Yeah, the dimension is 1 for any reduced dimension with `keepdims` or the dimension removed. In the case of all being removed a 0D comes out. This is the same for all axis lengths, including 0. So, it seems all very consistent and correct to me. The corner cases may be a bit surprising on their own, but I do think it is the right and consistent thing.

**Comment by eric-wieser** [comment]
@skrah, you'll get the behavior you expect if you pass `axis=None`, meaning reduce over all axes. Closing this, I agree with @seberg that it looks correct as is.

**Comment by skrah** [comment]
Thanks for the comments, the existing behavior makes sense.

I think in the following I was looking for `all(x == y) implies reduce(x) == reduce(y)`:

```
>>> x = np.array([]).reshape(0, 0)
>>> y = np.array([])
>>> np.all(x == y)
True
>>> np.array_equiv(x, y)
True
```

I expected that the logical array is what always matters in NumPy.  But indeed `array_equal()`considers the shape, even if no elements exist:

```
>>> np.array_equal(x, y)
False
```
