### ISSUE TITLE
MAINT: NaT (arg)min/max behavior

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#12797]
As discussed in #12658, we'll want to target `NaT` argmin, argmax, min, and max behavior adjustments to match the bug fix in sorting described there (to match `NaN` behavior) with 1.17 release target.

In particular, @seberg [notes (comment)](https://github.com/numpy/numpy/pull/12658#issuecomment-451647185)

> It seems currently NaT is completely ignored for min/max and argmin/argmax. I wonder if we should push to change that to be identical NaN (NaN is always returned). I guess if it that bites someone, on the up-side it probably will be loud since it points to NaT.

> There is also an independend bug for argmin when it starts with NaT and has only one not NaT item at the end

**Comment by zjpoh** [comment]
I can take a look at this if nobody is working on it.

**Comment by seberg** [comment]
Sure, sounds good, we could put this on the agenda for tomorrow.
