### ISSUE TITLE
f2py fails to generate Fortran modules on Numpy 1.16.0

### ISSUE THREAD

**Issue by dmey** [numpy/numpy#12796]
On Numpy 1.16.0, `f2py` fails to generate Fortran modules:
```
error: f2py target file '/tmp/tmpnke02j8i/src.linux-x86_64-3.6/test_f2py.c' not generated
```

Tested on Ubuntu 1.16 and macOS 1.14.2 both with Python 3.6.
This appears to be a new bug as there are no issue with Numpy 1.15.4 or lower.

### Reproducing code example:

Create `test_f2py.f90` and  `test_f2py.py` and add the following lines:
- `test_f2py.f90`
```
program test_f2py
end program test_f2py
```

- `test_f2py.py`
```
import numpy.f2py as f2py

with open('test_f2py.f90', 'rb') as fid:
    source = fid.read()
f2py.compile(source , modulename='test_f2py', extension='.f90')
```

Run `test_f2py.py`.

**Comment by tylerjereddy** [comment]
May or may not be related to #12756, but certainly seems reasonable to guess that this may be related to the `exec_command()` removal work that included some f2py source. But not sure.

**Comment by mattip** [comment]
Does not reproduce for me using the wheel on PyPI using Ubuntu 18.04 and using the bash shell. I get a successful production of `./test_f2py.cpython-36m-x86_64-linux-gnu.so`.  Where are you getting numpy from? What is your shell on Ubuntu/Mac OS?

**Comment by mattip** [comment]
Until someone can reproduce this in an environment that allows debugging the chances of fixing it are very slim.

**Comment by mattip** [comment]
My mistake, the `rb'` in `open(..., 'rb')` is the problem. Do we support compiling bytestrings?

**Comment by mattip** [comment]
[`np.f2py.compile`](https://github.com/numpy/numpy/blob/v1.16.0/numpy/f2py/__init__.py#L35) says `source` is a `str`, but admittedly the documentation is poorly indexed. The docstring does not appear in the [devdocs](http://www.numpy.org/devdocs/f2py/usage.html?highlight=compile) and even the link there is not very discoverable

**Comment by mattip** [comment]
On 1.15.4 passing in a `str` raises `TypeError: a bytes-like object is required, not 'str'`

**Comment by dmey** [comment]
That's good -- we get the same now. Thanks

I think that the doc string in 1.15.4 may be incorrect (see [this](https://github.com/numpy/numpy/blob/v1.15.4/numpy/f2py/__init__.py#L31)) but as the type for `source` has now been changed to `str` in 1.16.0 (see [this](https://github.com/numpy/numpy/blob/v1.16.0/numpy/f2py/__init__.py#L35)) it has lead to some confusion. Regardless, I think that the main issue here is that type has changed from 1.15.4 to 1.16.0, furthermore I agree with your comments you raised about the docs (i.e. "documentation is poorly indexed. The docstring does not appear in the devdocs and even the link there is not very discoverable")

**Comment by mattip** [comment]
@dmey Thanks for persisting. The [docs](http://www.numpy.org/devdocs/f2py/usage.html#python-module-numpy-f2py) now are taken from the docstrings and have been updated a bit, feel free to PR improvements :)

**Comment by dmey** [comment]
Great, thanks @mattip and will do if I find other issues.
