### ISSUE TITLE
np.__config__.show() is not consistent with ldd multiarray.so

### ISSUE THREAD

**Issue by phoenixbai** [numpy/numpy#12821]
I compiled the numpy-1.12.0 with openblas enabled. And when I build wheel package, the related openblas lib is included in numpy/.libs/. 

and when I ldd multiarray.so, get below:

> 	linux-vdso.so.1 =>  (0x00007fff25bff000)
	libopenblas-37aab398.so.0 => /archive/numpy-1.12.0-openblas.zip/files/numpy/core/./../.libs/libopenblas-37aab398.so.0 (0x00007f2272679000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f22723de000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f22721c3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2271e6b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f22739da000)
	libgfortran-ed201abd.so.3.0.0 => /archive/numpy-1.12.0-openblas.zip/files/numpy/core/./../.libs/libgfortran-ed201abd.so.3.0.0 (0x00007f2271b70000)

but while I print np.__config__.show(), openblas lib directory is not consistent with the above and it points to the directory configured in site.cfg :

```
import numpy as np
np.__version__
```

>'1.12.0'

`np.__config__.show()`

>lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
    runtime_library_dirs = ['/opt/OpenBLAS/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
    runtime_library_dirs = ['/opt/OpenBLAS/lib']
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
    runtime_library_dirs = ['/opt/OpenBLAS/lib']
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
    runtime_library_dirs = ['/opt/OpenBLAS/lib']
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE

when I deploy this wheel package local, where OpenBlas is installed /opt/OpenBLAS, it works fine. But when I copy the wheel package to some other machine with no OpenBLAS installation, the acceleration is not working.

I thought the the dependency lib is already included in whl file (numpy/.libs), so it should be working.
am I thinking wrong or what am I doing wrong?
please advise.

**Comment by rgommers** [comment]
> but while I print np.**config**.show(), openblas lib directory is not consistent with the above and it points to the directory configured in site.cfg :

It will indeed, by design, show the build-time value of the directory.

> I thought the the dependency lib is already included in whl file (numpy/.libs), so it should be working.
am I thinking wrong or what am I doing wrong?

The answer here is that you need a custom `_distributor_init.py` file, like we add in https://github.com/numpy/numpy/blob/main/tools/openblas_support.py#L197
