### ISSUE TITLE
DOC: autosummary is finding double documentation, emits many warnings

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#12827]
In looking at the [warnings while generating documentation](https://circleci.com/gh/numpy/numpy/5751?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), there are dozens of "/home/circleci/repo/venv/lib/python3.6/site-packages/numpy/core/_internal.py:docstring of numpy.core._internal._ctypes.shape:1: **WARNING: duplicate object description of** numpy.core._internal._ctypes.shape, other instance in /home/circleci/repo/doc/source/reference/generated/numpy.core.defchararray.chararray.ctypes.rst, **use :noindex: for one of them**

I think this is caused by `chararray` being a subclass of `ndarray`, as similar warnings are generated for `MaskedArray`. I tried:
- adding `autodoc_inherit_docstrings = False` to the `conf.py`
- messing with the `autosummary` [templates](https://github.com/numpy/numpy/tree/v1.16.0/doc/source/_templates/autosummary)

Any ideas how to turn those warnings off?

**Comment by tapaswenipathak** [comment]
Hi @mattip: Interested, can I work on the ticket?

**Comment by rgommers** [comment]
hi @tapaswenipathak, no one is working on this one I think, and would be great to have this fixed. a word of warning, it requires diving into some sphinx/numpydoc details which are not too pretty

**Comment by mattip** [comment]
The warnings are gone. I think numpydoc fixed something. Closing

**Comment by DerWeh** [comment]
Can someone share how this issue has been solved? I am trying for days to generate a documentation using `numpydoc` and `autosummary` but I cannot find any help how this can work.

**Comment by mattip** [comment]
I think you need to do the trick that we use in the  [templates](https://github.com/numpy/numpy/tree/v1.16.0/doc/source/_templates/autosummary). If you look at them via github, use the "raw" view to see the text. For instance, here is the `class.rst` raw text:

<details>

```
{% extends "!autosummary/class.rst" %}

{% block methods %}
{% if methods %}
   .. HACK -- the point here is that we don't want this to appear in the output, but the autosummary should still generate the pages.
      .. autosummary::
         :toctree:
      {% for item in all_methods %}
         {%- if not item.startswith('_') or item in ['__call__'] %}
         {{ name }}.{{ item }}
         {%- endif -%}
      {%- endfor %}
{% endif %}
{% endblock %}

{% block attributes %}
{% if attributes %}
   .. HACK -- the point here is that we don't want this to appear in the output, but the autosummary should still generate the pages.
      .. autosummary::
         :toctree:
      {% for item in all_attributes %}
         {%- if not item.startswith('_') %}
         {{ name }}.{{ item }}
         {%- endif -%}
      {%- endfor %}
{% endif %}
{% endblock %}

```
