### ISSUE TITLE
numpy.nditer returns ValueError

### ISSUE THREAD

**Issue by ViacheslavP** [numpy/numpy#12835]
Even the simplest iterator via nditer fails and returns ValueError

### Reproducing code example:

```python
import numpy as np

def foo(a):
    it = np.nditer([a, None])
    with it:
        for x,y in it:
            y[...] = x * x
    return it.operands[1]
b = np.arange(2)
print(foo(b))
```

### Error message:
Traceback (most recent call last):
  File "delete_me.py", line 10, in <module>
    print(foo(b))
  File "/delete_me.py", line 7, in foo
    return it.operands[1]
ValueError: Iterator is invalid

UPD:
I am an idiot

```python
import numpy as np

def foo(a):
    it = np.nditer([a, None])
    with it:
        for x,y in it:
            y[...] = x * x
        return it.operands[1]
b = np.arange(2)
print(foo(b))
```

### Numpy/Python version information:
1.15.4 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]

**Comment by seberg** [comment]
Hmmm, this should maybe be changed. When using the `with` statement, the return needs to be inside the with statement.

We can probably relax this for the `operands` specifically though.

**Comment by seberg** [comment]
Sorry, but I do think you are right and this specific use case should probably be allowed. But I can open another issue outside.
