### ISSUE TITLE
TypeError: `pad_width` must be of integral type.

### ISSUE THREAD

**Issue by MariosGr** [numpy/numpy#12852]
np.pad() raises an exception when trying to pad multiple axes with before and after padding.

### Reproducing code example:
```python
import numpy as np
a = np.arange(8).reshape((2, 2, 2))
np.pad(a, ((1,2), (0,), (0,)), 'maximum').shape
```
However, this works:
```python
import numpy as np
a = np.arange(8).reshape((2, 2, 2))
np.pad(a, ((1,), (0,), (0,)), 'maximum').shape
```

### Error message:
TypeError: `pad_width` must be of integral type.

### Numpy/Python version information:
1.16.0 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0]

**Comment by eric-wieser** [comment]
Did this work on 1.15?

**Comment by MariosGr** [comment]
Thanks for the response. 
Your spelling works fine. It just was not clear from the documentation how to spell it.
