### ISSUE TITLE
azure-pipelines broken for 32-bit compiles.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12856]
See https://dev.azure.com/numpy/numpy/_build/results?buildId=1943. Looks like an azure problem.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mattip** [comment]
xref #12842, #12857

pinging @chrisrpatterson who has been helpful debugging this kind of failure before

**Comment by mattip** [comment]
On a [successful build](https://dev.azure.com/numpy/numpy/_build/results?buildId=1942), the fortran compiler is found at `C:\tools\mingw32\bin\gfortran.exe` (line 1851 in the 32 bit build log for the "Build NumPy" step. Why can't I link directly to that?)
On an [unsucessful build](https://dev.azure.com/numpy/numpy/_build/results?buildId=1943) the compiler is started from `C:\ProgramData\Chocolatey\bin\gfortran.exe`. The `azure-pipelines.xml` did not change between the two builds.

**Comment by mattip** [comment]
The first time gfortran appears in the successful log file is on line 91
```
2019-01-25T19:59:39.1290829Z   Found executable C:\tools\mingw32\bin\gfortran.exe
2019-01-25T19:59:39.1689573Z   Using built-in specs.
2019-01-25T19:59:39.1689719Z   COLLECT_GCC=C:\tools\mingw32\bin\gfortran.exe
```

On the unsuccessful build the line is different, and the `COLLECT_GCC` result does not equal the found compiler:
```
2019-01-26T01:57:18.1558151Z   Found executable C:\ProgramData\Chocolatey\bin\gfortran.exe
2019-01-26T01:57:18.3329319Z   Using built-in specs.
2019-01-26T01:57:18.3332751Z   COLLECT_GCC=C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw32\bin\gfortran.exe
```

**Comment by mattip** [comment]
Compare the "Install 32-bit mingw for 32-bit builds" step from [successful](https://dev.azure.com/numpy/numpy/_build/results?buildId=1942) and [failing](https://dev.azure.com/numpy/numpy/_build/results?buildId=1943). The package used to be version 5.3.0, and is now 8.1.0

**Comment by charris** [comment]
Keeping this open to remind us that the tool chain needs work to update it.

**Comment by seberg** [comment]
While we are still pinning the mingw version (7.3.0) currently in azure-pipelines.  My guess is, keeping this 2 year old issue open doesn't serve much purpose anymore, so closing.
