### ISSUE TITLE
FFT2 DC value is not totally equal to the sum of the data.

### ISSUE THREAD

**Issue by ahmedshaaban1** [numpy/numpy#12861]
The DC value of the numpy.fft.fft2 for two dimension data is not equal to the sum of the data itself. 
The DC value that I got it ((333031523.05810547+0j)) and the sum of the data is  333031550.0
The difference is not large, yet considerable. 

### Reproducing code example:

Here is link for the file. [https://app.box.com/s/su5kqoxcydwf5qq183on0tyils0mvkvh](url)
```python
import numpy as np
file_data=np.load('/Users/ahmedlasheen/Desktop/Data2d.npz')
data=file_data['data']
fft_data=file_data['fft_data']

print(fft_data[0,0])
print(np.sum(data))
```

### Numpy/Python version information:
('1.14.2', '2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 11:07:58) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')

**Comment by cgohlke** [comment]
The data is 32-bit float, which is not precise enough to correctly sum all items. Use a 64-bit float accumulator instead: `np.sum(data, dtype=np.float64)`.

**Comment by ahmedshaaban1** [comment]
Thanks, I did not expect that precision could cause such inconsistency. 
Here is list of the output for different precisions.
('FFT DC values', (333031520+0j))
('Sun of the data float 23', 333031550.0)
('Sum of the data float 64', 333031523.05810547)
('Sum of the data float 128', 333031523.05810546875)
Float23 gave me much better results, yet they are not 100% similar, even with float 128.
Thanks

**Comment by charris** [comment]
What are the dimensions of the array?

**Comment by ahmedshaaban1** [comment]
(12784,  144)

**Comment by charris** [comment]
12784 has factors 17*47*16, could you try taking a subarray with dimension (12288, 144) and also try the transpose?

**Comment by charris** [comment]
Also, this being Anaconda, are you using the Intel fft?

**Comment by charris** [comment]
Note that Numpy itself only implements the FFT for doubles.

**Comment by mattip** [comment]
I am not sure there is anything we can do here. Closing. Please reopen if the NumPy you install from pip has this problem.
