### ISSUE TITLE
numpy-wheels 1.17.0-dev test failures.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12862]
For some time the numpy-wheels daily builds have suffered sporadic `pinv` test failures on linux i386, see https://travis-ci.org/MacPython/numpy-wheels/builds/484516943 for an example. After tedious, and possibly incorrect, bisection the troublesome commit seems to be 062dc8f831e695c2c179482da35affcc6045b4f3, the commit adding pocketfft.

I don't know more than that at the moment, but put this up to help point folks in the right direction if they want to help debug this.

**Comment by charris** [comment]
@mreineck Thoughts? Can you think of anything in your PR that could affect floating point or complex64 computation?

**Comment by mreineck** [comment]
No clue at the moment ... if these are intermittent failures, then I cannot imagine how pocketfft triggers them; this should be totally deterministic code, and I don't manipulate the CPU in any way, e.g. by changing the rounding mode or similar.

**Comment by charris** [comment]
My thoughts have been possible memory corruption, or possibly a compiler problem. How it manages to interact with OpenBLAS is a mystery.

**Comment by mreineck** [comment]
I'm running valgrind tests on the pure C library without any complaint. If you have a suggestion for more thorough testing, I'll try it.

It could of course be something in the Python glue code near the end of pocketfft.c (starting at line 2187). I'm not sure how to test this systematically.

**Comment by seberg** [comment]
Don't know this well enough. is there a chance that:
```
typedef struct { real r, i; } complex;
```
gets overshadowed by C99 `complex`? Not even sure why that should lead to weird things though, even if it happens.

**Comment by charris** [comment]
Heh, compiling with `-pedantic` yields somewhat less than a zillion warnings, but not much less. Mostly about casting object pointers to function pointers. And Cython code also does that a lot.

**Comment by mreineck** [comment]
An interesting experiment would be to set "-fno-strict-aliasing" as a global C compiler flag for scipy and check whether the problems go away. If so, then scipy most likely does some nasty type-punning in its C libraries that collides with the C99 rules.

**Comment by charris** [comment]
Tried with `-O2` instead of `-O3`, but didn't help. No compiler warnings.

**Comment by charris** [comment]
Note that there is no problem on Windows, which makes me think it is somehow compiler related.

**Comment by charris** [comment]
Our 32 bit azure test running Ubuntu Bionic, gcc 7.3.0, also passes. So one solution seems to be using a newer gcc. @matthew-brett @rgommers What are the tradeoffs with using a newer compiler for the wheel builds?

**Comment by mreineck** [comment]
Please give the "-fno-strict-aliasing" a try. If that helps, we at least know that some of the code ignores aliasing rules, and we can warn users. Also, older compilers might work again.

**Comment by charris** [comment]
Wheels are already built with `-fno-strict-aliasing`. Most of our pointer casts are `char *` to something else, so not treated as non aliased because char pointers were traditionally used like void pointers. I was actually surprised that the flag makes no difference these days, not having `-fno-strict-aliasing` used to cause bugs. But better safe than sorry.

OTOH, it is possible that the OpenBLAS libraries were compiled without that flag, but I don't know if that would matter. I'm thinking it is really a compiler problem, travis trusty uses gcc 4.8.4, but I'm not sure what version is in the docker image that is pulled down for the build.

**Comment by charris** [comment]
Here are the compiler flags being used.
```
C compiler: gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -O2 -fno-strict-aliasing -I/usr/local/include -fPIC
```

**Comment by charris** [comment]
This seems to have been fixed at the CI end, so closing.
