### ISSUE TITLE
NumPy User Guide broken link

### ISSUE THREAD

**Issue by joelcorey** [numpy/numpy#12860]
### Reproducing code example:

At present, if you visit https://www.scipy.org/getting-started.html and then click on the link for `NumPy User Guide`, it will tell you that the page was not found. The link is broken. The oldest working archive available for this page dates back to more than 2 years ago (as can be seen from http://web.archive.org/web/20160917150027/http://docs.scipy.org:80/doc/numpy-dev/user/ ).

### Error message:

404 Not Found

**Comment by mattip** [comment]
The repo for the site is https://github.com/scipy/scipy.org, not here. The source is `https://github.com/scipy/scipy.org/blob/master/www/getting-started.rst` and the link in question should be `https://docs.scipy.org/doc/numpy/user` (without the `-dev`). Perhaps you could make a PR against that repo?

**Comment by rgommers** [comment]
This is fixed now. Thanks for reporting @joelcorey
