### ISSUE TITLE
Downgrading python to install keras made numpy unusable

### ISSUE THREAD

**Issue by herminine** [numpy/numpy#12864]
I was using python 3.7 and the task at hand asked us to use keras. However I was not able to install Tensorflow or any other necessary package. As I saw that tensorflow is not compatible with python 3.7, but is with 3.6, I decided to downgrade python
I used
```conda install python=3.6```
Then I installed tensorflow and keras using pip.

Trying to import numpy afterwards resulted in this error message.

### Error message:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\numpy\core\__init__.py in <module>
     15 try:
---> 16     from . import multiarray
     17 except ImportError as exc:

~\Anaconda3\lib\site-packages\numpy\core\multiarray.py in <module>
     11 
---> 12 from . import overrides
     13 from . import _multiarray_umath

~\Anaconda3\lib\site-packages\numpy\core\overrides.py in <module>
      8 
----> 9 from numpy.core._multiarray_umath import add_docstring, ndarray
     10 from numpy.compat._inspect import getargspec

ImportError: DLL load failed: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-12-4e0db29569b3> in <module>
      1 
----> 2 import numpy as np
      3 import pandas as pd
      4 import matplotlib.pyplot as plt
      5 import seaborn as sns

~\Anaconda3\lib\site-packages\numpy\__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~\Anaconda3\lib\site-packages\numpy\core\__init__.py in <module>
     45 Original error was: %s
     46 """ % (sys.executable, exc)
---> 47     raise ImportError(msg)
     48 finally:
     49     for envkey in env_added:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\Paula\Anaconda3\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: Le module spécifié est introuvable.

### Numpy/Python version information:

I tried to use commands with pip to reinstall numpy, but numpy was already installed (I uninstalled and reinstalled to see if there as a compatibility problem). So I don't know why python does not find numpy and any other packages.

**Comment by mattip** [comment]
This seems to be a conda-related question and you might get a better answer on a conda-related issue tracker. But here are a few thing you could check:

- Do you have a file `~\Anaconda3\lib\site-packages\numpy\core\_multiarray_umath.pyd`?
- If so, and you print the PATH variable, does it have the ~\Anaconda3\Scripts directory in it? If not, does adding it to the PATH before running python solve the problem?
- If you needed to add the directory to the PATH, are you activating the conda environment before running python?

**Comment by herminine** [comment]
- I do have a file ```~\Anaconda3\lib\site-packages\numpy\core\_multiarray_umath.cp36-win_amd64.pyd```
- It does have both those directories.
- I tried to use the conda commands to install numpy, which allowed me to update it, which led to a correct import. However, it feels like I will have to do this for every package, and some still don't charge correctly.
- Would uninstalling/reinstalling conda sort this out?

**Comment by mattip** [comment]
`conda` and `pip` are two different methods for managing an environment. If you are using Anaconda, you should use `conda` for all your packaging needs. Please see their documentation for installing `keras`, `tensorflow` and other packages, and their issue tracker for any problems you encounter.
