### ISSUE TITLE
pypy2 6.0.0 numpy 1.13.3 import error

### ISSUE THREAD

**Issue by sylee0124** [numpy/numpy#12881]
```python
pypy
import numpy
```

### Error message:

It says undefined symbol: __intel_sse2_strrchr
Some posts refer that it's due to compiler problem but I have no clue...
<img width="502" alt="ldd_numpy" src="https://user-images.githubusercontent.com/47180088/51983083-2e049200-24db-11e9-901b-93e1d28de4ff.PNG">

<img width="957" alt="numpy_error" src="https://user-images.githubusercontent.com/47180088/51982617-d7e31f00-24d9-11e9-8d60-6eb2545874c3.PNG">

### Numpy/Python version information:
numpy 1.13.3, pypy2 6.0.0
Linux version 4.4.0-139-generic (buildd@lcy01-amd64-006) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by SteveDoyle2** [comment]
Have/can you try this on the latest version of numpy (1.16.2).  That version is no longer maintained.

**Comment by mattip** [comment]
Closing since the original reporter has not updated the issue. Please reopen if it is still relevant for a new version of NumPy / PyPy.
