### ISSUE TITLE
BLD: Regression: improper double quotes appear in rpath (linux)

### ISSUE THREAD

**Issue by LucHermitte** [numpy/numpy#12882]
### Steps to reproduce the problem:

I've observed a regression on RH7 when installing numpy (currently v1.16.0) with

```bash
pip install numpy --force-reinstall --ignore-installed --no-binary :all:
```

Until now I had no problem with python 3.6.5 (and previous) and with earlier versions of numpy (v1.14.3), now I observe the following issue (python 3.7.2, and even python 3.6.5) with numpy 1.16.0.

I fill `~/site.cfg` with information where to find lapack and blas libraries

```ini
[lapack]
lapack_libs  = lapack
language     = gfortran
library_dirs = /some/path/rh7/lapack/3.6.1/lib
runtime_library_dirs = /some/path/rh7/lapack/3.6.1/lib

[blas]
blas_libs    = blas,cblas
language     = gfortran
library_dirs = /some/path/rh7/lapack/3.6.1/lib
runtime_library_dirs = /some/path/rh7/lapack/3.6.1/lib
```

### Observed problem:

When I run `ldd` on the produced `numpy/linalg/lapack_lite.cpython-*m-x86_64-linux-gnu.so`, `liblapack.so`,  `libblas.so` and `libblas.so` aren't found.

When I ask `readelf  -d numpy/linalg/lapack_lite.cpython-*m-x86_64-linux-gnu.so | grep rpath`, I see

```
 0x000000000000000f (RPATH)              Library rpath: ["/some/path/rh7/lapack/3.6.1/lib"]
```

instead of 

```
 0x000000000000000f (RPATH)              Library rpath: [/some/path/rh7/lapack/3.6.1/lib]
```

that I had with previous versions of numpy. 

Removing the double-quotes with `chrpath`  fixes the issue. 

### Numpy/Python version information:

Numpy 1.16.0 (according to `pip -v`)
Python 1.6.5 and 1.7.2

No trouble with Numpy 1.14.3 (and earlier versions) and Python 1.6.5 (and earlier versions)

**Comment by eric-wieser** [comment]
Can you paste the full output of that command?
