### ISSUE TITLE
DOC: mention 0d corner case in ndarray.tolist 

### ISSUE THREAD

**Issue by mdickinson** [numpy/numpy#12913]
The [documentation](https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.ndarray.tolist.html) for `ndarray.tolist` says:

> Return the array as a (possibly nested) list.

But for zero-dimensional arrays, `tolist` returns a scalar:

```
>>> import numpy as np
>>> type(np.array(1.23).tolist())
<class 'float'>
```

This behaviour makes perfect sense: for an `n`-dimensional array, I expect `n` levels of nesting in the resulting list, but it's confusing that something called `tolist` isn't returning a list.

Would it be worth mentioning this zero-dimensional special case explicitly in the documentation, so that it's clear that it's intentional behaviour, and something that can be relied upon?

### Numpy/Python version information:

Python 3.7.2, NumPy 1.15.4.

**Comment by mdickinson** [comment]
Related: https://github.com/numpy/numpy/issues/11413

**Comment by eric-wieser** [comment]
This is already fixed in master
