### ISSUE TITLE
pytest thinks `_multiarray_module_test` is a test it should run, fails.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12916]
The other module names end with `tests` and are not detected as tests. Making that rename seems to fix things. The source code should also be moved out of the `multiarray` directory and into `src` so it is not lost in the multiarray code.

For reference on "new" files appearing during installation, `*.so` files are wrapped with a python file of the same name but `*.py` extension when installed.

**Comment by mattip** [comment]
Is the first sentence missing from the comment?

**Comment by charris** [comment]
We have several test modules ending in `tests` that don't seem to be a problem
```
numpy/core/_multiarray_tests.cpython-37m-x86_64-linux-gnu.so
numpy/core/_multiarray_tests.py
numpy/core/_operand_flag_tests.cpython-37m-x86_64-linux-gnu.so
numpy/core/_operand_flag_tests.py
numpy/core/_rational_tests.cpython-37m-x86_64-linux-gnu.so
numpy/core/_rational_tests.py
numpy/core/_struct_ufunc_tests.cpython-37m-x86_64-linux-gnu.so
numpy/core/_struct_ufunc_tests.py
numpy/core/_umath_tests.cpython-37m-x86_64-linux-gnu.so
numpy/core/_umath_tests.py
```
Note also the `*.py` wrapper files generated during install. I should have caught this as I ran into the same test problem when renaming some of those files.

**Comment by charris** [comment]
Not sure why this problem didn't turn up in runtests. IIRC, the names that pytest recognizes as tests can be specified, but we should probably work with the default.

**Comment by charris** [comment]
Closing, the troublesome test has been removed.
