### ISSUE TITLE
1/np.array(0) returns 0

### ISSUE THREAD

**Issue by bananaman23** [numpy/numpy#12918]
### Reproducing code example:

```python
In [1]: import numpy as np

In [2]: 1/np.array(0.), 1./np.array(0), 1/np.array(0)
RuntimeWarning: divide by zero encountered in divide
Out[2]: (inf, inf, 0)
```

### Numpy/Python version information:

('1.14.3', '2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) \n[GCC 7.2.0]')

**Comment by ksunden** [comment]
```
>>> import numpy as np
>>> 1/np.array(0.), 1./np.array(0), 1/np.array(0)
__main__:1: RuntimeWarning: divide by zero encountered in true_divide
(inf, inf, inf)
>>> np.__version__
'1.15.4'
```

Appears to be fixed

**Comment by eric-wieser** [comment]
In python 2, `/` is integer division which is why it gives 0. In python 3, it is float division, which is why it gives `inf`. There was never a bug here, this is a design choice by python itself.
