### ISSUE TITLE
np.array(17) ** 13 returns an incorrect even number

### ISSUE THREAD

**Issue by bananaman23** [numpy/numpy#12917]
### Reproducing code example:

```python
In [1]: import numpy as np

In [2]: np.array(17)**13, 17 ** 13
Out[2]: (9904578032905936, 9904578032905937)
```

### Numpy/Python version information:

('1.11.3', '2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) \n[GCC 7.2.0]')

**Comment by charris** [comment]
Seems to have been fixed.
```
In [1]: array(17)**13
Out[1]: 9904578032905937
```
It isn't that far from overflowing, though.

**Comment by eric-wieser** [comment]
Note that on windows, that does overflow - but that's by (unfortunate) design.

**Comment by eric-wieser** [comment]
Tested as far back as 1.12.1, still seems fine. Feel free to re-open if you can reproduce on a more recent release.
