### ISSUE TITLE
Add npy support to np.memmap

### ISSUE THREAD

**Issue by glenfletcher** [numpy/numpy#12926]
### Reproducing code example:

Here are to ways of creating a new empty array from a complex dtype object, if method 1 is used it creates a raw binary array on disk without the description header that np.save creates, were as method 2 first creates an empty array then saves it to disk and finally reloads it as a writable memmap'ed file, this is inefficient.

Under most circumstances this is fine as we would populate the array then save it to disk, however consider the example dtype this represents the results of a numerical simulation with two variables  hence each result is calculated in a loop over these variables, we could save the data in separate files but this messes up the file system.

The problem is when the simulation takes several hours to run if we wait to save we could lose all our results to a crash or force termination on a PBS system, were as with the memmap'ed method we can include a flag to indicate that a result has been calculated this way in the event of a crash of termination, we can resume without losing the results that had already been calculated. 

```python
import numpy as np
var1 = range(10)
var2 = range(20)
dtype= np.dtype([
('param1', float),
('param2', float),
('param3', float),
('param4', float, (2,)),
('var1', float, (len(var1),)),
('var2', float, (len(var2),)),
('result1', float, (len(var1),len(var2))),
('result2', float, (len(var1),len(var2),5,60))
])

#Method 1
data_memmap = np.memmap("memmap.npy", dtype, "w+", shape=())

#Method 2
data = np.empty((), dtype)
np.save("save.npy", data)
data_save = np.load("save.npy", "r+")
```

On my computer using method 1 has no header where as method 2 has the header 
```
{
  'descr': [('param1', '<f8'),
               ('param2', '<f8'),
               ('param3', '<f8'),
               ('param4', '<f8', (2,)),
               ('var1', '<f8', (10,)),
               ('var2', '<f8', (20,)),
               ('result1', '<f8', (10, 20)),
               ('result2', '<f8', (10, 20, 5, 60))],
 'fortran_order': False,
 'shape': (),
}
```

both allow me to access the array as a memmap'ed file which can be flushed using `data_x.flush()`

What I want is a combination method say

```python
data_memmap = np.memmap("memmap.npy", dtype, "w+", shape=(), npy=True)
```

or

```python
data_memmap = np.memmap("memmap.npy", dtype, "nw+", shape=())
```

which work like the normal memmap command but removes the offset option and creates a new npy file to map to, this avoids the inefficiency of method 2.

### Numpy/Python version information:

1.14.5 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
I don't think we should let memmap know about npy files, but it would be cool if np.load had an "open as mapped memory" argument. Your example would then look like:
```
arr = np.empty(shape)
np.save(arr, 'f.npy')
arr = np.load('f.npy', memmap=True)

```

**Comment by rkern** [comment]
It does: `np.load('f.npy', mmap_mode='r')`

https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html

**Comment by eric-wieser** [comment]
Sounds like @glenfletcher needs `r+`, but thanks for reminding me it already exists.

I think this can be closed then?

**Comment by rkern** [comment]
Let me attempt to rephrase the request: The desire is to initialize an NPY file with a given dtype and shape, and open it as memory-mapped for reading and writing.

I'm sympathetic, but I'm not convinced that method 2 (which accomplishes the same thing a bit more obliquely) is so inefficient that it warrants a new function. In fact, if I were tasked to implement this request, I'd probably have started with method 2 and called it a day.

**Comment by eric-wieser** [comment]
I've realized that I was not reading method 2 well enough, and all my comments have been just describing it. Sorry about that.

**Comment by lijunzh** [comment]
@mhvk Exactly what I wanted. I've been trying but failed to use `np.memmap` to create a large array on the file so that I can later load it in via `np.load(..., mmap_mode='r', ...)`. `np.lib.format.open_memmap` is the right solution. 

I didn't find any documentation on the https://docs.scipy.org/doc/numpy/ . Maybe we can add some docs for future reference?

**Comment by seberg** [comment]
@lijunzh at least starting in numpy 1.16 and later, there is a "See Also" in the `np.memmap` documentation. Is that enough for what you are looking for?

**Comment by lijunzh** [comment]
@seberg Yes, you are right. Sorry, I must have overlooked that line. It will be more helpful if there is a clickable link on the `lib.format.open_memmap` function, though.

**Comment by lijunzh** [comment]
@seberg  I mean something like #13414

**Comment by rossbar** [comment]
`lib.format.open_memmap` has been added to the documentation (thus fixing the See Also link) in #16664.
