### ISSUE TITLE
Cannot import numpy on MacOS 10.6 SnowLeopard

### ISSUE THREAD

**Issue by artcs** [numpy/numpy#12939]
On MacOS 10.6 importing latest numpy results in this error:

```
>>> import numpy
Traceback (most recent call last):
  File "/Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Symbol not found: __tlv_bootstrap
  Referenced from: /Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.5.dev.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.5.dev.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /Library/Frameworks/Python.framework/Versions/3.7/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Symbol not found: __tlv_bootstrap
  Referenced from: /Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.5.dev.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/artcs/Library/Python/3.7/lib/python/site-packages/numpy/core/../.dylibs/libopenblasp-r0.3.5.dev.dylib
```
This happens with Python 2.7.15 as well as 3.7.1.
A websearch for `__tlv_bootstrap` shows this seems to be an error related to libs compiled with llvm on MacOS 10.7 which causes them to no longer work on 10.6.
The wheel installed via `pip install --user numpy` implies compatibility with 10.6 however and installation works fine. Only it cannot be used. Can this be fixed or if not can someone point me to the latest working version for SL?

**Comment by rgommers** [comment]
> The wheel installed via `pip install --user numpy` implies compatibility with 10.6 however and installation works fine

The wheels on PyPI indeed have 10.6 in their name. I have a vague memory of us bumping the minimum version required to 10.9, but can't remember the details. @matthew-brett any idea?

> Can this be fixed or if not can someone point me to the latest working version for SL?

If these wheels don't work, there are no other ones. You may still be able to build from source though. 10.6 is so old that I suspect we don't want to spend time on that anymore, other than correcting our wheel naming.

**Comment by matthew-brett** [comment]
Yes, sorry, we are mis-speaking on the wheel compatibility - current numpy wheels are compatible with macOS 10.9 and higher.  I'm afraid you'll have to get an earlier version, to get real 10.6 compatibility.

**Comment by artcs** [comment]
Thank you for clarification. Closing this here.
Do you know, if there's a working version which can be installed via pip? (self-compiling is not an option because of the old compiler infrastructure on the affected machines)

**Comment by matthew-brett** [comment]
Yes, there surely are some. Try dropping back a few versions.   I think the 10.9 requirement appeared around the time we switched to OpenBLAS, so the wheels would be smaller for the older Accelerate builds, and I'm pretty sure they would work.

**Comment by artcs** [comment]
Thanks again. For reference, numpy 1.14.6 seems to be the last version with working SnowLeopard support.
```
pip uninstall numpy
pip install --user -Iv numpy==1.14.6
```

**Comment by rgommers** [comment]
Added an issue at https://github.com/MacPython/numpy-wheels/issues/43 for this.

I'm going to reopen it since it's not yet fixed, and assign this to the 1.16.2 milestone

**Comment by charris** [comment]
@rgommers What do you suggest as a fix, renaming? Sounds like the only other option is using Accelerate.

**Comment by rgommers** [comment]
Yes, renaming - the `10.6` tag should be removed from the filename. Definitely not going back to Accelerate.

**Comment by charris** [comment]
@matthew-brett Ping.

**Comment by dmitriz** [comment]
I have just ran into this issue on Mac OSX 10.8.5 and installing `numpy 1.15` still seems to work, which is a more recent version than the `1.14` recommended above:

```sh
sudo python3 -m pip uninstall numpy
python3 -m pip install numpy==1.15 --user
```

- I had to `sudo` the uninstall to avoid permission errors.
- For the install I could use the `--user` option instead.

Then it worked without errors:

```sh
python3
Python 3.7.3 (default, Jul  7 2019, 02:21:27) 
[Clang 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.array([1,3,4])
array([1, 3, 4])
>>> numpy.array([1,3,4]).ndim
1
```

**Comment by charris** [comment]
@matthew-brett Can this be closed?

**Comment by matthew-brett** [comment]
Yes, at least, if the current wheels are correctly named to macOS 10.9.

**Comment by charris** [comment]
Doesn't look like it, need to update multibuild I think. Should I go straight to the last commit?
```
numpy-1.16.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
```

**Comment by charris** [comment]
I think this has been fixed, although I haven't finished updating the submodule for all the versions.

@matthew-brett I do see this
```
61.00s$ before_install
Warning: The default Caskroom location has moved to /usr/local/Caskroom.
Please migrate your Casks to the new location and delete /opt/homebrew-cask/Caskroom,
or if you would like to keep your Caskroom at /opt/homebrew-cask/Caskroom, add the
following to your HOMEBREW_CASK_OPTS:
  --caskroom=/opt/homebrew-cask/Caskroom
For more details on each of those options, see https://github.com/caskroom/homebrew-cask/issues/21913.
Error: oclint is not installed
```
It doesn't seem to affect anything in the build, but I'm curious where it comes from.

**Comment by charris** [comment]
@matthew-brett Should I use latest multibuild for the next releases? Currently 7287f69. The nightly builds still have 10_6 in the name. I wonder if they are building from the daily branch instead of master. I'll see what the 1.17.1 builds produce, the expansive names were still used in 1.17.0 AFAICT. Not sure what the names *should* be.

**Comment by charris** [comment]
Also @tylerjereddy Thoughts?

**Comment by tylerjereddy** [comment]
`10_9` is the oldest version number I see "advertised" in the SciPy 1.3.1 mac binary / wheels assets listed on GitHub release page, if that helps. Those are the same assets we upload to PyPI. 

If SciPy is getting the right numbering in the name and NumPy isn't it is probably worth checking why. Looking at the two wheels repos I'm surprised to notice that the NumPy multibuild submodule looks like it has been synced to a far more recent commit than scipy wheels submodule equivalent.

**Comment by charris** [comment]
> multibuild submodule looks like it has been synced to a far more recent commit than scipy wheels submodule equivalent.

It was updated to (maybe) deal with the name problem, which in turn uncovered other more recent bugs, so it was updated further.

**Comment by charris** [comment]
I see this for scipy wheels at http://wheels.scipy.org/
```
scipy-1.3.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
```
So there is still a 10_6 in there.

**Comment by tylerjereddy** [comment]
oh right, I see that on the GitHub release page now too

**Comment by mattip** [comment]
The problem might be solved by MacPython/numpy-wheels#58, but that is [failing to build](https://travis-ci.org/MacPython/numpy-wheels/jobs/575245483) and I don't really understand the failure message

**Comment by charris** [comment]
@mattip , do you have permissions to cancel that build and all except the last in the queue? I can't release until appveyor is working again.

**Comment by charris** [comment]
@mattip the problem might be related to the Aug 22 github problems: https://status.appveyor.com.

**Comment by mattip** [comment]
Sorry, I can see the [queue](https://ci.appveyor.com/project/matthew-brett/numpy-wheels/history) but cannot find a "cancel" button anywhere. Maybe @matthew-brett can?

**Comment by charris** [comment]
Hmm,  latest names with latest multibuild look like
```
numpy-1.17.1-cp35-cp35m-macosx_10_6_intel.whl
```
So still not correct. I think that the version is being picked up from the enviroment and we are actually building with 10.6. Maybe this is due to
```
# Force xcode 6.4 image to work round
# https://github.com/python-pillow/pillow-wheels/issues/45
osx_image: xcode6.4
```
Which was suppose to be removed from travis last January.

**Comment by mattip** [comment]
> osx_image: xcode6.4

I issued a pull request to update that in MacPython/numpy-wheels#56 which did build successfully

**Comment by mattip** [comment]
The names are now correct in the [wheel](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/) prereleases. closing, please reopen if there is more action needed.

**Comment by charris** [comment]
I have a question concerning the upcoming 1.16.6 and 1.17.5 releases. Python 2.7 and 3.5 require xcode 9.4 for the build and I've also been labeling them as 10_6. If the llvm compiled OpenBLAS libraries are the determining factor, it seems they should be labeled 10_9. Is that correct?

**Comment by rgommers** [comment]
Yep, naming should be `10_9`

**Comment by charris** [comment]
Hmm, the Python 3.5 wheels cannot be built on 10.9, apparently the 3.5 package is not available for install. So building on 10.6 and will rename the wheel. I think that should be OK.
