### ISSUE TITLE
Numpy cannot be imported while running with Valgrind, in some cases

### ISSUE THREAD

**Issue by egaudry** [numpy/numpy#12930]
I am building an interpreter, based on the python C-API, that relies on ; This interpreter will load numpy at some point.

When launched under valgrind (--tool=memcheck), numpy will fail to load arguing that it cannot create a NaN from a longdouble. This can be observed with both numpy 1.15.4 and 1.16.1, not with 1.12.1, only when loading under valgrind.

### Reproducing code example:
```python
import numpy as np
```
### Error message:
cannot convert longdouble NaN to integer

**Comment by egaudry** [comment]
As a workaround, returns a value based on NaN:
`''
Index: numpy/numpy-1.16.1/numpy/core/src/common/npy_longdouble.c
===================================================================
--- numpy/numpy-1.16.1/numpy/core/src/common/npy_longdouble.c   (revision 118978)
+++ numpy/numpy-1.16.1/numpy/core/src/common/npy_longdouble.c   (working copy)
@@ -26,14 +26,20 @@
     neg = 0;
 
     if (npy_isinf(ldval)) {
-        PyErr_SetString(PyExc_OverflowError,
-                        "cannot convert longdouble infinity to integer");
-        return NULL;
+        //PyErr_SetString(PyExc_OverflowError,
+        //                "cannot convert longdouble infinity to integer");
+        v = PyLong_FromLong(NAN);
+        if (v == NULL)
+          return NULL;
+        goto done;
     }
     if (npy_isnan(ldval)) {
-        PyErr_SetString(PyExc_ValueError,
-                        "cannot convert longdouble NaN to integer");
-        return NULL;
+        //PyErr_SetString(PyExc_ValueError,
+        //                "cannot convert longdouble NaN to integer");
+        v = PyLong_FromLong(NAN);
+        if (v == NULL)
+          return NULL;
+        goto done;
     }
     if (ldval < 0.0) {
         neg = 1;
'''

**Comment by seberg** [comment]
Hmmm, strange. Long double never worked for me on valgrind (leading to all related tests to fail, similarly, all floating point error tests fail), I assumed it simply does not support it. But I never had issues with the actual import.

**Comment by eric-wieser** [comment]
Can you give either a c or Python stack trace?

**Comment by egaudry** [comment]
```
>>> import numpy
---- WARNING ----
Could not import numpy module:
cannot convert longdouble NaN to integer
--------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]lib/python2.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
```

**Comment by eric-wieser** [comment]
It's very weird that the first message has no exception type to show.

**Comment by eric-wieser** [comment]
Our source code contains neither `==== WARNING` nor `Could not import numpy module`. Do you have any idea what is printing those?

**Comment by seberg** [comment]
Hmmm, maybe there is some funny interplay with the `_distributor_init`, e.g. you are using an anaconda version, while I would be using a more bare version or even the development version.

**Comment by egaudry** [comment]
Sorry, I forgot to add that the === WARNING === message comes from our interpreted, when the ImportError exception is raised.  he import issue can only be seen when launching our interpreter with valgrind, without there is no issue.

Is there any longdouble creation while importing numpy ?
Would returning a NaN (respectively Inf) would make sense ?

**Comment by eric-wieser** [comment]
> Would returning a NaN (respectively Inf) would make sense ?

No, because you can't do that - `(long)NAN` is nonsensical and probably undefined behavior

**Comment by eric-wieser** [comment]
It looks like your interpreter is messing with our error message - you should be able to get a backtrace that ends with `SomeError: cannot convert longdouble NaN to integer`

**Comment by egaudry** [comment]
Then what about the longdouble NaN used during numpy initialization ?

**Comment by eric-wieser** [comment]
Please configure your interpreter to not swallow the traceback and exception type, so that we stand a chance of debugging this.

**Comment by egaudry** [comment]
```
==28165== Memcheck, a memory error detector
==28165== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==28165== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==28165== Command: actranpy
==28165== 
hwloc x86 backend cannot work under Valgrind, disabling.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "[...]/lib/python2.7/site-packages/pyfemtown/Main/__init__.py", line 2, in <module>
    import numpy
  File "[...]/lib/python2.7/site-packages/numpy/__init__.py", line 167, in <module>
    core.getlimits._register_known_types()
  File "[...]/lib/python2.7/site-packages/numpy/core/getlimits.py", line 177, in _register_known_types
    tiny=tiny_f128)
  File "[...]/lib/python2.7/site-packages/numpy/core/getlimits.py", line 53, in __init__
    self.precision = int(-log10(self.eps))
ValueError: cannot convert longdouble NaN to integer
```

**Comment by eric-wieser** [comment]
Great, thanks! Now we see the real problem - `log10(eps)` is returning `nan` on your system. To be clear - this only happens in conjunction with valgrind?

I'd be curious to know the value of eps when this fails.

**Comment by egaudry** [comment]
Yes, this only happens when running under valgrind (3.14 and 3.13 have been tested and show the same behavior).

**Comment by seberg** [comment]
Hmmm, on my system I get the double eps, which is `2.220446049250313e-16`, however, even for that value the `np.log10` should not return NaN. I am also using 3.14, out of curiosity, is your computer a Mac or so, that it uses double-double for float128?

I get a lot of undefined errors in valgrind for `np.finfo(np.float128)`, but no crashes.

**Comment by egaudry** [comment]
I can reproduce this behavior on 2 different linux 64-bit (x86) boxes, one centos-7.5 and one suse12sp3.

**Comment by egaudry** [comment]
under valgrind:
```
 Machine parameters for float128
  ---------------------------------------------------------------
  precision =  15   resolution = 9.999999999999998805e-16
  machep =    -52   eps =        2.2204460492503130808e-16
  negep =     -53   epsneg =     1.1102230246251565404e-16
  minexp =  -1022   tiny =       2.2250738585072013831e-308
  maxexp =   1024   max =        1.7976931348623157081e+308
  nexp =       11   min =        -max
  ---------------------------------------------------------------
```
without valgrind:
```
  Machine parameters for float128
  ---------------------------------------------------------------
  precision =  18   resolution = 1e-18
  machep =    -63   eps =        1.084202172485504434e-19
  negep =     -64   epsneg =     5.42101086242752217e-20
  minexp = -16382   tiny =       3.3621031431120935063e-4932
  maxexp =  16384   max =        1.189731495357231765e+4932
  nexp =       15   min =        -max
  ---------------------------------------------------------------
```

**Comment by egaudry** [comment]
http://www.valgrind.org/docs/manual/manual-core.html#manual-core.limits

**Comment by seberg** [comment]
Not that I think it will help, but I guess I confused eps and epsneg before, and the only difference in the params itself is that I got:
```
>>> print(np.finfo(np.float128))
Machine parameters for float128
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000004721e-15
machep =    -52   eps =        2.2204460492503130808e-16
negep =     -53   epsneg =     1.1102230246251565404e-16
minexp =  -1022   tiny =       2.2250738585072013831e-308
maxexp =  1024   max =        1.7976931348623157081e+308
nexp =       11   min =        -max
---------------------------------------------------------------
```
a slightly different value for the resolution (seems a bit strange to me, but maybe it is just random, this is a Kaby Lake mobile processor on arch linux).
Maybe there is a different (ftz) denormal handling for some reason, which then leads to other things? Just guessing here, since I find it curious our setups behave differently.

**Comment by egaudry** [comment]
I have tested both scenarii:
- without FTZ
- with FTZ (it is our default handling for subnormals)
and they all resulted in the same issue with exp2(ld(-112)).

**Comment by seberg** [comment]
Well, if I think about it, I do get a lot of invalid reads, so maybe we should look into those warnings before wondering about apparently random behaviour...

**Comment by egaudry** [comment]
I'm not sure the behavior is random, or I'm not sure that randomness is at the origin of the overflow issue when running under valgrind.

**Comment by seberg** [comment]
So, I think the (valgrind) warnings that I see are just because it prints out/checks the `bytes` information when it gives a warning because it uses the raw `bytes` information of `-0.1` to guess what format it is (and that matches none for me, but apparently is uninitialized anyway -- while it is close to the actual long double format, it is not an exact match).

And yeah, the overflow issues are by themselves weird, right, because it should not overflow for doubles.

**Comment by seberg** [comment]
Just stumbled on this. Did you ever resolved it?

It feels like there should be some simple fix, but I don't know what it is and this is unfortunately pretty niche :(.  Valgrind still works fine for me (modulo those longdouble issues). I have occasionally set GCC to compile longdouble as 64bit floats, although that comes with its own set of issues when calling functions from glibc (so it might shift the problem, but probably doesn't solve it).

I am going to close this since it has been a long while and I am not sure what to do, please comment or open a new issue if its still a problem.
