### ISSUE TITLE
numpy.distutils.fcompiler fails to work if the distributable uses only .pyc files

### ISSUE THREAD

**Issue by jakegt1** [numpy/numpy#12934]
If numpy is built with only .pyc files in the distributable, numpy.distutils.fcompiler will not work as there will be no available fcompiler classes due to a glob explicity looking for .py files.

## How to reproduce error

Build numpy with the following command:#
```bash
python setup.py build_ext bdist_egg --exclude-source-files
```

Attempt to get a fortran compiler: 

```python
from numpy.distutils import fcompiler
compiler = fcompiler.get_default_fcompiler()
```

This will show the message at [numpy.distutils.fcompiler.\_\_init\_\_:891](https://github.com/numpy/numpy/blob/master/numpy/distutils/fcompiler/__init__.py#L891) with no supported compilers - this is because the glob at line [775](https://github.com/numpy/numpy/blob/master/numpy/distutils/fcompiler/__init__.py#L775) specifically looks for only .py files.

Maybe it would be better to use some of the package management modules to list the available compilers instead of using a glob?

### Numpy/Python version information:

Numpy 1.15.4
Python 3.5.2

**Comment by rgommers** [comment]
> If numpy is built with only .pyc files in the distributable

don't do that, to start with:) seriously, do not rely on such obscure setuptools features if you want to distribute code robustly.

not opposed to making changes here if they're very easy, but this falls under unsupported usage.

**Comment by jakegt1** [comment]
I'm not surprised it does, but I have a requirement where the package needs to be as small as possible (and I can't have __pycache__ folders created on the fly, so I can't reduce the initial file size that way either.)

It's a simple change for what in fairness, is not a particularly robust way of calculating what is needed in the first place.

I do understand this is a very specific and odd use case though.
