### ISSUE TITLE
numpy.random.randint complaints about missing positional argument.

### ISSUE THREAD

**Issue by thakkardharmik** [numpy/numpy#12933]
When the dtype is specified in the call to numpy.random.randint, we should set the default value for low based on the datatype. Currently the call does not support creating random int just by specifying the datatype of the random value.

```
RAND_MAPPING = {
    'TINYINT': np.random.randint(dtype=np.int8),
    'SMALLINT': np.random.randint(dtype=np.int16)
}
for k in range(20):
    print(RAND_MAPPING['TINYINT'])
```
Error stack - 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-67fec5a70990> in <module>()
     12 
     13 RAND_MAPPING = {
---> 14     'TINYINT': np.random.randint(dtype=np.int8),
     15     'SMALLINT': np.random.randint(dtype=np.int16)
     16 }

mtrand.pyx in mtrand.RandomState.randint()

TypeError: randint() takes at least 1 positional argument (0 given)
```

We should be able to generate random number just specifying datatype.

**Comment by bashtage** [comment]
The default value for low is 0.  The one parameter configuration sets high.

If a 0 positional parameter version was possible, it would have to sample on [0,iinfo(dtype).max], not [iinfo(dtype).min, iinfo(dtype).max].

**Comment by ihnorton** [comment]
related to https://github.com/numpy/numpy/issues/9573

**Comment by mdhaber** [comment]
The first argument of `randint` is documented as being required, so this is an enhancement request. However, enhancements are no longer being made to [legacy random number generation](https://numpy.org/doc/stable/reference/random/legacy.html#legacy-random-generation), so I'll close.
