### ISSUE TITLE
Cannot uninstall 'numpy'. It is a distutils installed project...

### ISSUE THREAD

**Issue by AndrewYinLi** [numpy/numpy#12948]
I am currently attempting to uninstall numpy in a Python 2.7 ArcGIS environment, however I get the error cited in the error section of this issue.

### Reproducing code example:

```
pip uninstall numpy
```

### Error message:

```
Cannot uninstall 'numpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
<!-- Full error message, if any (starting from line Traceback: ...) -->
```
### Numpy/Python version information:

('1.9.3', '2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]')

**Comment by seberg** [comment]
@AndrewYinLi I guess you were able to get around it? Shouldn't be anything to do with numpy, just the general issue of mixing distutils and pip.

**Comment by mattip** [comment]
Closing, that error is expected.
