### ISSUE TITLE
HOWTO_BUILD_DOCS.rst.txt is missing from repo

### ISSUE THREAD

**Issue by pllim** [numpy/numpy#12954]
### Reproducing code example:

In the Astropy documentation, https://github.com/astropy/astropy/blame/master/docs/development/docrules.rst#L558-L562 links to your https://github.com/numpy/numpy/blob/master/doc/HOWTO_BUILD_DOCS.rst.txt

### Error message:

The file is no longer there. What should we link it to now? Please advise. Thank you!

### Numpy/Python version information:

Python version is irrelevant. Numpy is the code in `master`.

**Comment by mattip** [comment]
If you really want the old instructions, you can pin to the 1.14 branch https://github.com/numpy/numpy/blob/maintenance/1.14.x/doc/HOWTO_BUILD_DOCS.rst.txt, but I would recommend the generic last-version rendered (html not rst) link which is now http://www.numpy.org/devdocs/docs/howto_build_docs.html

**Comment by pv** [comment]
Or, copypaste the contents to astropy. There's no guarantee that the instructions won't be changed if things are changed in numpy.

**Comment by pllim** [comment]
Thanks for your swift replies! We'll think about the options you have presented.
