### ISSUE TITLE
numpy.interp inconsistent behavior for left and right when inf is present.

### ISSUE THREAD

**Issue by RLstat** [numpy/numpy#12951]
related to #11439, yet my issue exist in 1.15.4, which is released after that merge. 

When the array contains infinity values, if -np.inf is present at the left or the np.inf is present at the right, in either `xp` or `fp`, their behavior are inconsistent. 

### Reproducing code example:

case1: infinity in the `fp`.
```python
import numpy as np
xp = np.array([0, 1, 9, 10])
fp = np.array([-np.inf, 0.1, 0.9, np.inf])
x = np.array([0.2, 9.5])

np.interp(x, xp, fp) # returns array([nan, inf]), where array([-inf, inf]) is probably more appropriate. 
```
case2: infinity in the `xp`.
```python
import numpy as np
xp = np.array([-np.inf, 1, 9, np.inf])
fp = np.array([0, 0.1, 0.9, 1])
x = np.array([0.2, 9.5])

np.interp(x, xp, fp) # returns array([nan, 0.9])

```
the left side is giving nan, the right side is giving the value in `fp` that corresponds to non infinity value. I think it should be consistent for both sides, maybe like `array([0.1, 0.9])`, or `array([nan, nan])` (I am not sure which one is better). 

### Numpy/Python version information:
`1.15.4`

**Comment by eric-wieser** [comment]
Looks reasonable to me. When `x` does not match `xp[i]` exactly, I think the rules should be (expressed in priority order):

| fp[i] | fp[i+1] | result
|----|----|----|
| nan | Any | nan 
| Any | nan | nan 
| inf | -inf | nan 
| -inf | inf | nan 
| -inf | Any | -inf 
| Any | -inf | -inf 
| inf | Any | inf 
| Any | inf | inf 
| Any | Any | normal interpolation
