### ISSUE TITLE
Histogram with np.nan values: RuntimeWarning: invalid value encountered

### ISSUE THREAD

**Issue by roliveira** [numpy/numpy#12955]
A simple change of the automatic bounds calculation in:
https://github.com/numpy/numpy/blob/1c4ab89870e39be7c4a47258f6d92f532650e5cc/numpy/lib/histograms.py#L312

to 

```python
first_edge, last_edge = np.nanmin(a), np.nanmax(a) 
```

seems to fix this issue. Am I missing something or perhaps it could be this straight-forward?

**Comment by eric-wieser** [comment]
I think this is working as intended - arguably you want a warning if you ask histogram to auto-guess the bounds from data with missing values.

**Comment by roliveira** [comment]
@eric-wieser you are right, having `np.histogram` being built with a `np.nan` returns you `ValueError: autodetected range of [nan, nan] is not finite`. 

However having it built with `pyplot.hist` silently accepts it and only raises a `RuntimeWarning`
```python
/anaconda/lib/python3.6/site-packages/numpy/lib/histograms.py:754: RuntimeWarning: invalid value encountered in greater_equal
  keep = (tmp_a >= first_edge)
/anaconda/lib/python3.6/site-packages/numpy/lib/histograms.py:755: RuntimeWarning: invalid value encountered in less_equal
  keep &= (tmp_a <= last_edge)
```

Is this simply a version mismatch? This is what I've got for `matplotlib` and `numpy` right now:

```shell
~$ conda list | grep matplotlib
matplotlib                3.0.2            py36h5429711_0  
matplotlib2tikz           0.6.18                   pypi_0    pypi
~$ conda list | grep numpy
numpy                     1.15.2                   pypi_0    pypi
numpy-base                1.15.4           py36h81de0dd_0  
numpydoc                  0.8.0                    py36_0 
```

**Comment by eric-wieser** [comment]
Can you show me the exact code you're running in each case?

**Comment by fbertrand27** [comment]
Just ran into this, the behavior does not seem consistent based on if we pass in a single list of values or a list of lists. i.e. these warnings do NOT seem to happen if passing multiple data sets:

**Warning given:**
`axs.hist( (1, np.nan) )`

**NO warning given:**
`axs.hist( ((1, np.nan), (1, 2)) )`

**Comment by roliveira** [comment]
I'm closing this issue; I didn't follow the request closely and this is likely irrelevant now.
