### ISSUE TITLE
DOC: np.roll does not mention negative values for shift

### ISSUE THREAD

**Issue by solarjoe** [numpy/numpy#12959]
Title says it all.

The documentation should mention that it is also possible to shift towards the other direction using negative values. Sure. you can find out by trying, but then you are not sure if it is a bug or a feature :)

**Comment by Dan-Patterson** [comment]
The sign of the integer was not restricted, but I agree, maybe a followup example to the first in the help
np.roll(x, -2)
array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

**Comment by Dan-Patterson** [comment]
looks good!
