### ISSUE TITLE
Help for Pyinstaller pack *.exe

### ISSUE THREAD

**Issue by yangjiuchun** [numpy/numpy#12967]
Process:
C:\logparser>Pyinstaller -F main.py
182 INFO: PyInstaller: 3.5.dev0+73dfb3add
182 INFO: Python: 3.6.4
182 INFO: Platform: Windows-7-6.1.7601-SP1
184 INFO: wrote C:\logparser\main.spec
186 INFO: UPX is not available.
189 INFO: Extending PYTHONPATH with paths
['C:\\logparser', 'C:\\logparser']
189 INFO: checking Analysis
190 INFO: Building Analysis because Analysis-00.toc is non existent
190 INFO: Initializing module dependency graph...
194 INFO: Initializing module graph hooks...
197 INFO: Analyzing base_library.zip ...
4937 INFO: running Analysis Analysis-00.toc
4964 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by C:\python36\python.exe
5956 INFO: Caching module hooks...
5964 INFO: Analyzing C:\logparser\main.py
6082 INFO: Processing pre-find module path hook   distutils
9012 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
12881 INFO: Processing pre-find module path hook   site
12882 INFO: site: retargeting to fake-dir 'C:\\python36\\lib\\site-packages\\pyi
nstaller-3.5.dev0+73dfb3add-py3.6.egg\\PyInstaller\\fake-modules'
18772 INFO: Processing pre-safe import module hook   six.moves
52130 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
58754 INFO: Loading module hooks...
58755 INFO: Loading module hook "hook-certifi.py"...
58757 INFO: Loading module hook "hook-cryptography.py"...
59359 INFO: Loading module hook "hook-distutils.py"...
59361 INFO: Loading module hook "hook-encodings.py"...
59545 INFO: Loading module hook "hook-IPython.py"...
59564 INFO: Excluding import 'gtk'
59574 INFO: Excluding import 'PyQt4'
59583 INFO: Excluding import 'PyQt5'
59592 INFO: Excluding import 'matplotlib'
59600 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pyla
btools
59600 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
59601 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.c
ore.pylabtools
59601 INFO:   Removing import of matplotlib.figure from module IPython.core.pyla
btools
59604 INFO: Excluding import 'PySide'
59613 INFO: Excluding import 'tkinter'
59623 INFO:   Removing import of tkinter from module IPython.lib.clipboard
59626 INFO: Loading module hook "hook-jedi.py"...
59632 INFO: Loading module hook "hook-lib2to3.py"...
59641 INFO: Loading module hook "hook-lxml.etree.py"...
59642 INFO: Loading module hook "hook-matplotlib.backends.py"...
62633 INFO:   Matplotlib backend "GTK3Agg": ignored
    cairo backend requires that cairocffi or pycairo is installed
63254 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
64067 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
C:\python36\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `I
Python.kernel` package has been deprecated since IPython 4.0.You should import f
rom ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
65327 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'ipykernel'
66186 INFO:   Matplotlib backend "Qt4Agg": added
66792 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
67654 INFO:   Matplotlib backend "Qt5Agg": added
68307 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
69097 INFO:   Matplotlib backend "TkAgg": added
69918 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
71131 INFO:   Matplotlib backend "WebAgg": added
71994 INFO:   Matplotlib backend "WX": added
72791 INFO:   Matplotlib backend "WXAgg": added
73430 INFO:   Matplotlib backend "WXCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
74045 INFO:   Matplotlib backend "agg": added
74688 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
75499 INFO:   Matplotlib backend "pdf": added
76233 INFO:   Matplotlib backend "pgf": added
76840 INFO:   Matplotlib backend "ps": added
77430 INFO:   Matplotlib backend "svg": added
78207 INFO:   Matplotlib backend "template": added
79204 INFO: Loading module hook "hook-matplotlib.py"...
79750 INFO: Loading module hook "hook-numpy.core.py"...
79886 INFO: Loading module hook "hook-numpy.py"...
79890 INFO: Loading module hook "hook-openpyxl.py"...
79901 INFO: Loading module hook "hook-pandas.py"...
81907 INFO: Loading module hook "hook-PIL.Image.py"...
82503 INFO: Loading module hook "hook-PIL.py"...
82509 INFO: Import to be excluded not found: 'FixTk'
82509 INFO: Excluding import 'PyQt4'
82514 INFO:   Removing import of PyQt4 from module PIL.ImageQt
82516 INFO: Excluding import 'PyQt5'
82521 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
82521 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
82522 INFO: Excluding import 'PySide'
82526 INFO:   Removing import of PySide from module PIL.ImageQt
82528 INFO: Excluding import 'tkinter'
82534 INFO:   Removing import of tkinter from module PIL.ImageTk
82535 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
82541 INFO: Excluding import 'tkinter'
82546 INFO: Import to be excluded not found: 'FixTk'
82546 INFO: Loading module hook "hook-pkg_resources.py"...
83230 INFO: Processing pre-safe import module hook   win32com
83555 INFO: Loading module hook "hook-pycparser.py"...
83981 INFO: Loading module hook "hook-pydoc.py"...
83985 INFO: Loading module hook "hook-pygments.py"...
86701 INFO: Loading module hook "hook-PyQt5.py"...
86964 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
87158 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
87527 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
88177 INFO: Loading module hook "hook-pythoncom.py"...
88793 INFO: Loading module hook "hook-pytz.py"...
88891 INFO: Loading module hook "hook-pywintypes.py"...
89532 INFO: Loading module hook "hook-scipy.linalg.py"...
89534 INFO: Loading module hook "hook-scipy.py"...
89540 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
89550 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
89552 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
89554 INFO: Loading module hook "hook-setuptools.py"...
90589 INFO: Loading module hook "hook-skimage.transform.py"...
90627 INFO: Loading module hook "hook-sqlite3.py"...
90811 INFO: Loading module hook "hook-sysconfig.py"...
90813 INFO: Loading module hook "hook-win32com.py"...
91433 INFO: Loading module hook "hook-xml.dom.domreg.py"...
91434 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
91436 INFO: Loading module hook "hook-xml.py"...
91437 INFO: Loading module hook "hook-_tkinter.py"...
91774 INFO: checking Tree
91774 INFO: Building Tree because Tree-00.toc is non existent
91775 INFO: Building Tree Tree-00.toc
91843 INFO: checking Tree
91844 INFO: Building Tree because Tree-01.toc is non existent
91844 INFO: Building Tree Tree-01.toc
92049 INFO: checking Tree
92050 INFO: Building Tree because Tree-02.toc is non existent
92051 INFO: Building Tree Tree-02.toc
92074 INFO: Looking for ctypes DLLs
92168 INFO: Analyzing run-time hooks ...
92199 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
92204 INFO: Including run-time hook 'pyi_rth_pkgres.py'
92206 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
92210 INFO: Including run-time hook 'pyi_rth_traitlets.py'
92213 INFO: Including run-time hook 'pyi_rth__tkinter.py'
92216 INFO: Including run-time hook 'pyi_rth_qt5.py'
92220 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
92222 INFO: Including run-time hook 'pyi_rth_mpldata.py'
92293 INFO: Looking for dynamic libraries
147243 INFO: Looking for eggs
147243 INFO: Using Python library C:\python36\python36.dll
147244 INFO: Found binding redirects:
[]
147295 INFO: Warnings written to C:\logparser\build\main\warn-main.txt
148007 INFO: Graph cross-reference written to C:\logparser\build\main\xref-main.
html
148192 INFO: checking PYZ
148192 INFO: Building PYZ because PYZ-00.toc is non existent
148193 INFO: Building PYZ (ZlibArchive) C:\logparser\build\main\PYZ-00.pyz
156635 INFO: Building PYZ (ZlibArchive) C:\logparser\build\main\PYZ-00.pyz compl
eted successfully.
156731 INFO: checking PKG
156732 INFO: Building PKG because PKG-00.toc is non existent
156732 INFO: Building PKG (CArchive) PKG-00.pkg
311813 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
311903 INFO: Bootloader C:\python36\lib\site-packages\pyinstaller-3.5.dev0+73dfb
3add-py3.6.egg\PyInstaller\bootloader\Windows-64bit\run.exe
311904 INFO: checking EXE
311904 INFO: Building EXE because EXE-00.toc is non existent
311904 INFO: Building EXE from EXE-00.toc
311905 INFO: Appending archive to EXE C:\logparser\dist\main.exe
312346 INFO: Building EXE from EXE-00.toc completed successfully.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

### Error message:
C:\logparser>C:\logparser\dist\main.exe
Traceback (most recent call last):
  File "site-packages\numpy\core\__init__.py", line 16, in <module>
  File "C:\python36\lib\site-packages\pyinstaller-3.5.dev0+73dfb3add-py3.6.egg\P
yInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\numpy\core\multiarray.py", line 12, in <module>
  File "C:\python36\lib\site-packages\pyinstaller-3.5.dev0+73dfb3add-py3.6.egg\P
yInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\numpy\core\overrides.py", line 9, in <module>
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from msgflowprocessor import *
  File "C:\python36\lib\site-packages\pyinstaller-3.5.dev0+73dfb3add-py3.6.egg\P
yInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "msgflowprocessor.py", line 12, in <module>
    import matplotlib
  File "C:\python36\lib\site-packages\pyinstaller-3.5.dev0+73dfb3add-py3.6.egg\P
yInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\matplotlib\__init__.py", line 141, in <module>
  File "C:\python36\lib\site-packages\pyinstaller-3.5.dev0+73dfb3add-py3.6.egg\P
yInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\matplotlib\cbook\__init__.py", line 33, in <module>
  File "C:\python36\lib\site-packages\pyinstaller-3.5.dev0+73dfb3add-py3.6.egg\P
yInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\numpy\__init__.py", line 142, in <module>
  File "C:\python36\lib\site-packages\pyinstaller-3.5.dev0+73dfb3add-py3.6.egg\P
yInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\numpy\core\__init__.py", line 47, in <module>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\logparser\d
ist\main.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: 找不到指定的模块。

[14168] Failed to execute script main

### Numpy/Python version information:
python:  3.6.4
numpy: 1.16.0+mkl
matplotlib: 3.0.2
pyinstaller: 3.5.dev0+73dfb3add

**Comment by mattip** [comment]
Your pyinstaller build artifact is probably missing the mkl dlls. If you build with more verbose logging, you should see [this line](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-numpy.core.py#L44) printed. This is not a numpy problem, rather one with pyinstaller

**Comment by yangjiuchun** [comment]
@mattip: Maybe you are right. I compiled my project on win10, and the exe ran normally. 
How can I find  the missing mkl dlls name?

**Comment by mattip** [comment]
I don't know much about pyinstaller, maybe ask there. You could look for how to enable more verbose output and debug the pyinstaller build.

**Comment by yangjiuchun** [comment]
@mattip: Thank you very much.

**Comment by mattip** [comment]
Closing. Please open a new issue if there is something that needs changing from numpy.
