### ISSUE TITLE
Unable to use tensorflow because of error.

### ISSUE THREAD

**Issue by HuviX** [numpy/numpy#12969]
Hello. 
I have created a new environment for tensorflow in Anaconda.
And 
```python
pip install tensorflow
```
Installation said to be successful but in fact I have some problems in numpy which I have already tried to solve by numpy reinstallation/version downgrade.

```python
import numpy
```
as well as 
```python
import tensorflow
```
leads to: 

### Error message:
Traceback (most recent call last):
  File "C:\Users\Maest\AppData\Local\Continuum\anaconda3\envs\tflow\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Maest\AppData\Local\Continuum\anaconda3\envs\tflow\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\Maest\AppData\Local\Continuum\anaconda3\envs\tflow\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\Maest\AppData\Local\Continuum\anaconda3\envs\tflow\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\Maest\AppData\Local\Continuum\anaconda3\envs\tflow\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\Maest\AppData\Local\Continuum\anaconda3\envs\tflow\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.

### Numpy/Python version information:

Python version - '3.7.2 (default, Feb 11 2019, 14:11:50) [MSC v.1915 64 bit (AMD64)]'
Numpy version - I have already tried multiple versions: 1.5.3, 1.5.4, 1.6.1. And I get the same errors.

**Comment by mattip** [comment]
the information [here](https://github.com/numpy/numpy/issues/12957#issuecomment-462651814) about PATHs might be helpful. Please let us know if it is, so we can hone in on the real issue.

**Comment by HuviX** [comment]
``` PATH=path\to\site-packages\numpy\.libs;%PATH%python -c "import numpy"```
works well. And Lib\site-packages\numpy.libs exists and there is one file in it:
libopenblas.CSRRD7HKRKC3T3YXA7VY7TAZGLSWDKW6.gfortran-win_amd64.dll 
What should I do next? Add ...\Lib\site-packages\numpy.libs  to my PATH variable?

**Comment by HuviX** [comment]
I am a bit confused about conversation you linked to, sorry.

**Comment by mattip** [comment]
Could you try one more thing (this is what we do inside numpy)? We append, rather than prepend the library to the path inside numpy:
```
PATH=%PATH%;path\to\site-packages\numpy\.libs
python -c "import numpy"
```
So if prepending the path works, and appending does not, there is something strange about your path. If appending works, there is something strange in the way we set the PATH inside numpy.

**Comment by HuviX** [comment]
This also works well. Actually, it doesn't throw me any exceptions/errors :)

**Comment by mattip** [comment]
Strange. so something is wrong with setting os.environ['PATH'] from python. A work-around for you is to set that path before calling python. It is more worrying for us that the python (apparently from 3 days ago?) you are using changed its behaviour. Where is it from?

**Comment by mattip** [comment]
Ahh, this is anaconda-issues#10629 which is a copy of anaconda-issues#10628
