### ISSUE TITLE
BUG: Switch to shlex.split(args, posix=False) is backward-incompatible

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12979]
As part of @tylerjereddy's valiant crusade to eliminate `_exec_command`, we introduced some uses of `shlex.split` to maintain compatibility with old string arguments:

https://github.com/numpy/numpy/blob/568d0f7483f7b94029d49707ccd6371f9f5c554c/numpy/f2py/__init__.py#L94

https://github.com/numpy/numpy/blob/d1186c9d2fdc62fe1491d0820af12106d16a1fb6/numpy/distutils/fcompiler/__init__.py#L478

https://github.com/numpy/numpy/blob/d1186c9d2fdc62fe1491d0820af12106d16a1fb6/numpy/distutils/fcompiler/__init__.py#L481

Unfortunately, these changes made the false assumption that `shlex.split(args, posix=False)` meant "do it the windows way". This is demonstrably non-true.

I think we need to make a choice here:

* Just require posix-escaping everywhere. Most people using distutils are probably more familiar with it anyway. The biggest pain point is that windows file paths using backslashes will start failing.
* Implement our own version of shlex.split that works correctly on windows.

An inefficient but correct implementation would look like:

```python
import subprocess

def shell_split(cmd):
    """
    Like `shlex.split`, but uses the Windows splitting syntax when run on Windows
    """
    if os.name == 'posix':
        return shlex.split(cmd)
    else:
        import json

        if not cmd:
            return []
        # Just invoke python which has a builtin parser, rather than trying to roll our own.
        full_cmd = '{} {}'.format(
            subprocess.list2cmdline([
                sys.executable, '-c',
                'import sys, json; print(json.dumps(sys.argv[1:]))'
            ]), cmd
        )
        ret = subprocess.check_output(full_cmd)
        return json.loads(ret.decode())
```

And an example of how this differs from `shlex.split`:
```python
>>> flags = '-I/fake/directory "-I/path with/spaces" -Os'
>>> shlex.split(flags, posix=False)
['-I/fake/directory', '"-I/path with/spaces"', '-Os']
>>> shell_split(flags)
['-I\\fake\\directory', '-I/path with/spaces', '-Os']
```

**Comment by tylerjereddy** [comment]
I added the discussion surrounding this decision to "Community Suggested Topics" in the weekly meeting, scheduled for tomorrow. I've been a bit distracted by the ongoing SciPy manuscript and SciPy release process.

**Comment by tylerjereddy** [comment]
@eric-wieser Can you clarify exactly what case we are aiming to fix here? What is broken now?

The discussion in the meeting today was a bit divided re: the two choices you provide.

**Comment by eric-wieser** [comment]
Sure, let me try to enumerate the behavior on windows. The right columns of this table show alternative `argv` interpretations, with "•" used to make the argument separation obvious

| `environ["F90"]` | before<br />(windows) | current<br />(windows) | current<br />(posix) | proposed<br />(windows)
|--|--|--|--|--|
| `f90` | `f90` | `f90` | `f90` | `f90`
| `path/f90` | `path/f90` | `path/f90` | `path/f90` | `path/f90`
| `path\f90` | `path\f90` | `path\f90` | `pathf90` | `path\f90`
| `"path\f90"` | `path\f90` | `"path\f90"` | `path\f90` | `path\f90`
| `path\\f90` | `path\\f90` | `path\\f90` | `path\f90` | `path\\f90`
| `path to/f90` | `path to/f90` | `path` • `to/f90` | `path` • `to/f90` | `path` • `to/f90`
| `"path to\f90"` | `path to\f90` | `"path to\f90"` | `path to\f90` | `path to\f90`
| `f90 --coverage` | `f90 --coverage` | `f90` • `--coverage` | `f90` • `--coverage` | `f90` • `--coverage`
| `path/f90 --coverage` | `path/f90 --coverage` | `path/f90` • `--coverage` | `path/f90` • `--coverage` | `path/f90` • `--coverage`
| `"path/f90" --coverage` | `path/f90` • `--coverage` | `"path/f90"` • `--coverage` | `path/f90` • `--coverage` | `path/f90` • `--coverage`
| `"path to/f90" --coverage` | `path to/f90` • `--coverage` | `"path to/f90"` • `--coverage` | `path to/f90` • `--coverage` | `path to/f90` • `--coverage`


<details>

<summary>Generation script</summary>

```python
import json
import os
import shlex
import subprocess
import sys

from numpy.distutils.exec_command import _quote_arg, exec_command

def argv_proposed(cmd):
    """
    Like `shlex.split`, but uses the Windows splitting syntax when run on Windows
    """
    if os.name == 'posix':
        return shlex.split(cmd)
    else:
        import json

        if not cmd:
            return []
        # Just invoke python which has a builtin parser, rather than trying to roll our own.
        full_cmd = '{} {}'.format(
            subprocess.list2cmdline([
                sys.executable, '-c',
                'import sys, json; print(json.dumps(sys.argv[1:]))'
            ]), cmd
        )
        ret = subprocess.check_output(full_cmd)
        return json.loads(ret.decode())


def argv_before(cmd):
	s, val = exec_command([sys.executable, '-c', 'import sys, json; print(json.dumps(sys.argv[1:]))', cmd])
	return json.loads(val)

def argv_nonposix(cmd):
	return shlex.split(cmd, posix=False)

def argv_posix(cmd):
	return shlex.split(cmd, posix=True)

funcs = [
	argv_before, argv_nonposix, argv_posix, argv_true
]

cases = [
	r'f90',
	r'path/f90',
	r'path\f90',
	r'"path\f90"',
	r'path\\f90',
	r'path to/f90',
	r'"path to\f90"',
	r'f90 --coverage',
	r'path/f90 --coverage',
	r'"path/f90" --coverage',
	r'"path to/f90" --coverage',
]

def show_argv(argv):
	return ' • '.join('`{}`'.format(arg) for arg in argv)

for case in cases:
	print(' '.join([
		'| {}'.format(val) for val in (
			['`{}`'.format(case)] + [
				show_argv(func(case)) for func in funcs
			]
		)
	]))
```

</details>

**Comment by mattip** [comment]
The `current (posix)` column is with `posix=True`?  If so, what happens if you do `posix=False`?

**Comment by eric-wieser** [comment]
That's shown in the "current
(windows)" column

**Comment by mattip** [comment]
Cool. So I vote in favor of your `shell_split` function. If some of the rows are not currently being tested, it would be helpful to add them to tests as well, so we can eventually grow a set of "best practices".

**Comment by eric-wieser** [comment]
The one problem with my `shell_split` function is it requires `sys.executable` to be executable, which I don't think is always true for embedded interpreters. Admittedly those are unlikely to be running distutils.

**Comment by mattip** [comment]
couldn't you do it from 'import json' instead?

**Comment by eric-wieser** [comment]
Was that intended for the other PR? Not sure what your question is.

The approach above goes through subprocess because the best way to work out what the MS C runtime's rules for parsing out argv are is to run a program that uses the MS C runtime.

**Comment by mattip** [comment]
ahh, got it, thanks

**Comment by eric-wieser** [comment]
`json` is just used as a lightweight way of roundtripping the list of strings through stdout

**Comment by eric-wieser** [comment]
Looks like my diagnosis was incorrect. We can call the right function using ctypes:
```
def win_CommandLineToArgvW(cmd):
    import ctypes
    nargs = ctypes.c_int()
    ctypes.windll.shell32.CommandLineToArgvW.restype = ctypes.POINTER(ctypes.c_wchar_p)
    lpargs = ctypes.windll.shell32.CommandLineToArgvW(unicode(cmd), ctypes.byref(nargs))
    args = [lpargs[i] for i in range(nargs.value)]
    if ctypes.windll.kernel32.LocalFree(lpargs):
        raise AssertionError
    return args
```
Despite the claims in [this answer](https://stackoverflow.com/a/35900070/102441), this is actually exactly the same as my function above

**Comment by mattip** [comment]
The [cpython issue](https://bugs.python.org/issue1724822) requesting a fix in python is still open

**Comment by eric-wieser** [comment]
I think that issue is requesting an escaper for `cmd.exe`, which is a more unpleasant can of worms.

I don't think it's one we need to touch though -  we're not looking for `cmd.exe` escaping anyway - exec_command was calling `Popen(str)` not `Popen(str, shell=True)`.

**Comment by eric-wieser** [comment]
Proposed change to distutils would be a new `_commandline_parsers.py` containing:
```
"""
Helper functions to split and join shell strings.

`split(join(argv))` should always be a no-op.
"""
import shlex
import subprocess
try:
    from shlex import quote
except ImportError:
    from pipes import quote


class WindowsCRT:
    """
    The parsing behavior used by `subprocess.call("string")` on Windows.

    CRT short for C RunTime. This parser does _not_ match cmd.exe
    """
    @staticmethod
    def join(argv):
        return subprocess.list2cmdline(argv)

    @staticmethod
    def split(cmd):
        import ctypes  # guarded import for systems without ctypes

        CommandLineToArgvW = ctypes.windll.shell32.CommandLineToArgvW
        CommandLineToArgvW.restype = ctypes.POINTER(ctypes.c_wchar_p)
        CommandLineToArgvW.argtypes = (ctypes.c_wchar_p, ctypes.POINTER(ctypes.c_int))

        nargs = ctypes.c_int()
        lpargs = CommandLineToArgvW(cmd, ctypes.byref(nargs))
        args = [lpargs[i] for i in range(nargs.value)]
        assert not ctypes.windll.kernel32.LocalFree(lpargs)
        return args


class Posix:
    """
    The parsing behavior used by `subprocess.call("string")` on Posix.
    """
    @staticmethod
    def join(cmd):
        return ' '.join(quote(arg) for arg in argv)

    @staticmethod
    def split(cmd):
        return shlex.split(cmd, posix=True)


if os.name == 'nt':
    Native = WindowsCRT
else:
    Native = Posix
```

Then we'd replace `shlex.split` with `_commandline_parsers.Native.split`

**Comment by charris** [comment]
LGTM. Would the new classes go into  `numpy/distutils/misc_util.py` or do you want to keep them in their own file?

Note that we will probably make a stop the bleeding release soon to fix the DLL load problems and it would be good to have this fix in that.

**Comment by eric-wieser** [comment]
Erroneous auto-closure
