### ISSUE TITLE
errors installing numpy

### ISSUE THREAD

**Issue by nguyenmaihao** [numpy/numpy#12975]
I had a problem when installing numpy. My laptop has 64 bit window 7. After installing python 2.7.13, I need to install numpy package. I set the path in Advanced system setting. 
![image](https://user-images.githubusercontent.com/47300457/52881387-b5513700-3164-11e9-9698-5c5b7c07bc4f.png)

 Although numpy is successfully installed, my command "import numpy" in Python 2.7.13 Shell produces an error. 
### Reproducing code example:

import numpy 

### Error message:
```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import numpy
  File "C:\Python27\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Python27\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 
```
### Numpy/Python version information:
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32

**Comment by charris** [comment]
Hmm. We don't recommend users building numpy on Windows because of various problems. What is actually installed in the path where your Python comes from? Do you have more than one Python installed?

**Comment by nguyenmaihao** [comment]
At first, I installed Python 3 and Python 2 together. When I found some advice on the Internet about troubles coming from using both 2 versions, I uninstalled Python 3.  My current path is listed as follows:

C:\Python27\;C:\Python27\Scripts\;C:\Users\mai hao\Miniconda2;C:\Users\mai hao\Miniconda2\Library\mingw-w64\bin;C:\Users\mai hao\Miniconda2\Library\usr\bin;C:\Users\mai hao\Miniconda2\Library\bin;C:\Users\mai hao\Miniconda2\Scripts;C:\Users\mai hao\Miniconda3;C:\Users\mai hao\Miniconda3\Library\mingw-w64\bin;C:\Users\mai hao\Miniconda3\Library\usr\bin;C:\Users\mai hao\Miniconda3\Library\bin;C:\Users\mai hao\Miniconda3\Scripts;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\

Besides Windows, where can I build numpy? 

Thank you for your help!

**Comment by charris** [comment]
You are using Anaconda/Miniconda? To avoid problems you should use Miniconda{2, 3} to install Numpy, you don't need to build it. If you have problems, you should ask for help from the Anaconda folks.

**Comment by rgommers** [comment]
> Besides Windows, where can I build numpy?

There are distributions like Anaconda for all major platforms, best to use those. See https://scipy.org/install.html for details.

No further follow-up, so closing
