### ISSUE TITLE
On Mac OS X, import numpy complaining about "Library not loaded: @rpath/libgfortran.3.dylib"

### ISSUE THREAD

**Issue by mjbrodzik** [numpy/numpy#12970]
### Reproducing code example:
On Mac OS X Mojave,
conda create -n numpy python=3.6 numpy=1.16
source activate numpy
python
import numpy

Produces run-time error complaining about libgfortran3 (see error message below)

```python
import numpy
(see error message, below)
```

### Error message:

Original error was: dlopen(/Users/brodzik/miniconda3/envs/numpy/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /Users/brodzik/miniconda3/envs/numpy/lib/libopenblas.dylib
  Reason: image not found

### Numpy/Python version information:

I have installed gcc and gfortran with brew:

gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
(base) cu-vpn-nsidc-172:~ brodzik$ gfortran --version
GNU Fortran (Homebrew GCC 8.2.0) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

However, the above conda installation looks like it has installed libgfortran4, not 3:

(numpy) cu-vpn-nsidc-172:~ brodzik$ conda list
# packages in environment at /Users/brodzik/miniconda3/envs/numpy:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge/channel/main
ca-certificates           2018.11.29           ha4d7672_0    conda-forge/channel/main
certifi                   2018.11.29            py36_1000    conda-forge/channel/main
libcxx                    7.0.0                h2d50403_2    conda-forge/channel/main
libffi                    3.2.1             h0a44026_1005    conda-forge/channel/main
libgfortran               4.0.0                         0    conda-forge/channel/main
llvm-meta                 7.0.0                         0    conda-forge/channel/main
ncurses                   6.1               h0a44026_1002    conda-forge/channel/main
numpy                     1.16.1          py36_blas_openblash486cb9f_0  [blas_openblas]  conda-forge/channel/main
openblas                  0.3.3             hdc02c5d_1001    conda-forge/channel/main
openssl                   1.0.2p            h1de35cc_1002    conda-forge/channel/main
pip                       19.0.2                   py36_0    conda-forge/channel/main
python                    3.6.7             h4a56312_1001    conda-forge/channel/main
readline                  7.0               hcfe32e1_1001    conda-forge/channel/main
setuptools                40.8.0                   py36_0    conda-forge/channel/main
sqlite                    3.26.0            h1765d9f_1000    conda-forge/channel/main
tk                        8.6.9             ha441bb4_1000    conda-forge/channel/main
wheel                     0.33.0                   py36_0    conda-forge/channel/main
xz                        5.2.4             h1de35cc_1001    conda-forge/channel/main
zlib                      1.2.11            h1de35cc_1004    conda-forge/channel/main
(numpy) cu-vpn-nsidc-172:~ brodzik$ 

My conda version is 4.6.3.

I have tried to figure out how to install libgfortran3, but haven't had any luck. Please advise.

**Comment by mjbrodzik** [comment]
I have done a little more work on this.  A colleague of mine suggested I examine the recipe for numpy, which has libgfortran set to >3.0.1.  

He suggested upgrading my conda, which I did with 'conda update conda'.  This upgraded me to conda 4.5.11-py35_0. I also conda clean --all.  The numpy recipe is still requiring >=3.0.1.

I seem to have a workaround in specifying libgfortran on my conda create step, like this:

conda create -n numpy python=3 numpy libgfortran=3

but I don't think this a very good answer.

**Comment by rgommers** [comment]
Thanks for the report @mjbrodzik. This was a bug in conda-forge that got fixed: https://github.com/conda-forge/numpy-feedstock/issues/126. You should get a rebuilt version of numpy when you're creating new environments.

**Comment by mjbrodzik** [comment]
Hello, @rgommers 

I have tried updating my conda to v4.6.4, and doing conda clean --all, but all my numpy recipes still specify open-ended libgfortran >=3.0.1, which requires me to build new environments with "libgfortran=3" specifically.  Is there something else I need to do to access the corrected numpy packages?

**Comment by rgommers** [comment]
Hi @mjbrodzik. I have a very similar setup to you, I'll try to reproduce this problem. 

Could you give the output of `locate libgfortran.3.dylib`, `locate libgfortran.4.dylib` and `locate libopenblas.dylib`?

**Comment by rgommers** [comment]
Is it possible that you ran `conda create -n numpy python=3.6 numpy=1.16` but it did not create a clean env (maybe because the named env already existed?). 

Here is the full output of running that command for me,  it installs `libgfortran        pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2`:

```
$ conda create -n gfortran-issue python=3.6 numpy=1.16
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.6
  latest version: 4.6.7

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /Users/rgommers/anaconda3/envs/gfortran-issue

  added / updated specs:
    - numpy=1.16
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-19.0.3                 |           py36_0         1.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following NEW packages will be INSTALLED:

  blas               conda-forge/osx-64::blas-1.1-openblas
  ca-certificates    conda-forge/osx-64::ca-certificates-2018.11.29-ha4d7672_0
  certifi            conda-forge/osx-64::certifi-2018.11.29-py36_1000
  libcxx             conda-forge/osx-64::libcxx-7.0.0-h2d50403_2
  libffi             conda-forge/osx-64::libffi-3.2.1-h0a44026_1005
  libgfortran        pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  llvm-meta          conda-forge/noarch::llvm-meta-7.0.0-0
  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002
  numpy              conda-forge/osx-64::numpy-1.16.1-py36_blas_openblash486cb9f_0
  openblas           conda-forge/osx-64::openblas-0.3.3-hdc02c5d_1001
  openssl            conda-forge/osx-64::openssl-1.0.2p-h1de35cc_1002
  pip                conda-forge/osx-64::pip-19.0.3-py36_0
  python             conda-forge/osx-64::python-3.6.7-h4a56312_1002
  readline           conda-forge/osx-64::readline-7.0-hcfe32e1_1001
  setuptools         conda-forge/osx-64::setuptools-40.8.0-py36_0
  sqlite             conda-forge/osx-64::sqlite-3.26.0-h1765d9f_1000
  tk                 conda-forge/osx-64::tk-8.6.9-ha441bb4_1000
  wheel              conda-forge/osx-64::wheel-0.33.1-py36_0
  xz                 conda-forge/osx-64::xz-5.2.4-h1de35cc_1001
  zlib               conda-forge/osx-64::zlib-1.2.11-h1de35cc_1004


Proceed ([y]/n)? 


Downloading and Extracting Packages
pip-19.0.3           | 1.8 MB    | ################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate gfortran-issue
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

**Comment by mjbrodzik** [comment]
Yes, it is possible I was doing that, although I was careful to 'conda env remove -n numpy'.  

I just tried creating an env with a name I'd never used before, and still had the same problem.

I also am seeing an odd message from conda when I try to update conda iitself.  It tells me a newer version of conda is available, but then doesn't do the update:
nsidc-worsley:~ brodzik$ conda update -n base conda
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.6.7

Please update conda by running

    $ conda update -n base conda



# All requested packages already installed.

nsidc-worsley:~ brodzik$

I'm starting to wonder about about my conda installation, so I also tried just renaming my ~/miniconda3 directory and reinstalling miniconda3.  This installed conda v4.5.12.  I did a

conda update -n base conda

and it successfully updated me to  conda 4.6.4, but I see this is older by a couple of patches from the one you are working with.

I wonder if my issue is related to my channel settings.  These are:

(base) nsidc-worsley:~ brodzik$ conda config --get
--set always_yes True
--add channels 'defaults'   # lowest priority
--add channels 'https://conda.anaconda.org/conda-forge/channel/main'
--add channels 'https://conda.anaconda.org/nsidc/channel/dev'
--add channels 'https://conda.anaconda.org/nsidc/channel/main'   # highest priority
--set show_channel_urls True
(base) nsidc-worsley:~ brodzik$

The nsidc channels are ones that my organization uses.  I removed these from the config and left in conda-forge/channel/main and defaults (since these match the ones in your output).  I made a new env and still get libgfortran4 with the same error.

**Comment by rgommers** [comment]
Yes, we're using the same channels in the same order now: `conda-forge` higher prio than `defaults`.

@beckermr would you mind having a look at this? any suggestions on how to further debug?

**Comment by mjbrodzik** [comment]
Sorry I missed your question about locate.  I'm not familiar with it, but when I run it, it says my locate.database doesn't exist.  And when I run the command to create it, it starts the service but I still can't get an answer back to help answer your question:
(base) nsidc-worsley:~ brodzik$ locate libgfortran.3.dylib

WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.

(base) nsidc-worsley:~ brodzik$ sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
Password:
(base) nsidc-worsley:~ brodzik$
(base) nsidc-worsley:~ brodzik$ locate libgfortran.3.dylib

WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.

(base) nsidc-worsley:~ brodzik$ sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
/System/Library/LaunchDaemons/com.apple.locate.plist: service already loaded
(base) nsidc-worsley:~ brodzik$

**Comment by beckermr** [comment]
Try cleaning the repo index. `conda clean -i`.

Then clean all of the packages `conda clean --all`.

Then try again.

**Comment by rgommers** [comment]
yeah it will take more than a few minutes; it indexes all files. once it's done, you'll see something like:
```
$ locate libopenblas.dylib
/Users/rgommers/anaconda3/envs/hthf/lib/libopenblas.dylib
/Users/rgommers/anaconda3/envs/tmpfiona/lib/libopenblas.dylib
/Users/rgommers/anaconda3/lib/libopenblas.dylib
/Users/rgommers/anaconda3/pkgs/libopenblas-0.2.20-hdc02c5d_4/lib/libopenblas.dylib
/Users/rgommers/anaconda3/pkgs/libopenblas-0.3.3-hdc02c5d_3/lib/libopenblas.dylib
/Users/rgommers/anaconda3/pkgs/openblas-0.2.20-8/lib/libopenblas.dylib
/Users/rgommers/anaconda3/pkgs/openblas-0.3.3-ha44fe06_1/lib/libopenblas.dylib
```

**Comment by charris** [comment]
It may, or may not, update daily. Sometimes you need to go a bit faster and `sudo updatedb` should do it. Note that you don't need the complete file name, you will just get more matches with plain old `libopenblas`.

**Comment by mjbrodzik** [comment]
Sorry for the delayed response.  Recall that I moved my original miniconda installation to ~/miniconda3_orig/ and re-installed miniconda.  The new installation is in ~/miniconda3/ and I'm trying not to make systematic env names for each new test I run.

Here are my locate outputs:

(base) nsidc-worsley:~ brodzik$ locate libgfortran.3.dylib
/Applications/MATLAB_R2017b.app/sys/os/maci64/libgfortran.3.dylib
/Applications/MATLAB_R2018b.app/sys/os/maci64/libgfortran.3.dylib
/Users/brodzik/miniconda3/envs/gfortran-3/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3/pkgs/libgfortran-3.0.1-h93005f0_2/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/envs/cartopy/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/envs/cetb3/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/envs/charis/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/envs/kwb/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/envs/nco/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/envs/pandas3/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/envs/rasterio/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/pkgs/libgcc-4.8.5-1/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/pkgs/libgfortran-3.0.0-0/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/pkgs/libgfortran-3.0.0-1001/lib/libgfortran.3.dylib
/Users/brodzik/miniconda3_orig/pkgs/libgfortran-3.0.1-h93005f0_2/lib/libgfortran.3.dylib
(base) nsidc-worsley:~ brodzik$ 

***********************************

(base) nsidc-worsley:~ brodzik$ locate libgfortran.4.dylib
/Users/brodzik/miniconda3/envs/gfortran-test/lib/libgfortran.4.dylib
/Users/brodzik/miniconda3/envs/gfortran-test2/lib/libgfortran.4.dylib
/Users/brodzik/miniconda3/envs/gfortran-test3/lib/libgfortran.4.dylib
/Users/brodzik/miniconda3/envs/gfortran-test4/lib/libgfortran.4.dylib
/Users/brodzik/miniconda3/pkgs/libgfortran-4.0.0-0/lib/libgfortran.4.dylib
/Users/brodzik/miniconda3_orig/envs/gfortran-issue/lib/libgfortran.4.dylib
/Users/brodzik/miniconda3_orig/envs/test_cetb/lib/libgfortran.4.dylib
/Users/brodzik/miniconda3_orig/pkgs/libgfortran-4.0.0-0/lib/libgfortran.4.dylib
(base) nsidc-worsley:~ brodzik$


***********************************

(base) nsidc-worsley:~ brodzik$ locate libopenblas.dylib
/Users/brodzik/miniconda3/envs/gfortran-3/lib/libopenblas.dylib
/Users/brodzik/miniconda3/envs/gfortran-test/lib/libopenblas.dylib
/Users/brodzik/miniconda3/envs/gfortran-test2/lib/libopenblas.dylib
/Users/brodzik/miniconda3/envs/gfortran-test3/lib/libopenblas.dylib
/Users/brodzik/miniconda3/envs/gfortran-test4/lib/libopenblas.dylib
/Users/brodzik/miniconda3/pkgs/openblas-0.3.3-hdc02c5d_1001/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/envs/cartopy/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/envs/cetb3/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/envs/gfortran-issue/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/envs/kwb/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/envs/nco/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/envs/test_cetb/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/pkgs/openblas-0.2.19-2/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/pkgs/openblas-0.2.20-8/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/pkgs/openblas-0.3.3-ha44fe06_1/lib/libopenblas.dylib
/Users/brodzik/miniconda3_orig/pkgs/openblas-0.3.3-hdc02c5d_1001/lib/libopenblas.dylib
(base) nsidc-worsley:~ brodzik$

**Comment by mjbrodzik** [comment]
And now I have done the conda clean commands you recommended and tried a new env.  This time it worked and I have a working runtime version of numpy:

(base) nsidc-worsley:~ brodzik$ conda clean -i
(base) nsidc-worsley:~ brodzik$ conaa clean --all
-bash: conaa: command not found
(base) nsidc-worsley:~ brodzik$ conda clean --all
Cache location: /Users/brodzik/miniconda3/pkgs
Will remove the following tarballs:

/Users/brodzik/miniconda3/pkgs
------------------------------
blas-1.1-openblas.tar.bz2                      1 KB
llvm-meta-7.0.0-0.tar.bz2                      2 KB

---------------------------------------------------
Total:                                         4 KB

Removed blas-1.1-openblas.tar.bz2
Removed llvm-meta-7.0.0-0.tar.bz2
Cache location: /Users/brodzik/miniconda3/pkgs
Will remove the following packages:
/Users/brodzik/miniconda3/pkgs
------------------------------

blas-1.1-openblas                              3 KB
llvm-meta-7.0.0-0                              5 KB

---------------------------------------------------
Total:                                         8 KB

removing blas-1.1-openblas
removing llvm-meta-7.0.0-0
(base) nsidc-worsley:~ brodzik$

***********************************

(base) nsidc-worsley:~ brodzik$ conda create -n gfortran-test5 python=3.6 numpy=1.16
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/brodzik/miniconda3/envs/gfortran-test5

  added / updated specs:
    - numpy=1.16
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.1                   |         openblas           1 KB  conda-forge/channel/main
    libgfortran-3.0.1          |                0         495 KB  conda-forge/channel/main
    llvm-meta-7.0.0            |                0           2 KB  conda-forge/channel/main
    numpy-1.16.2               |py36_blas_openblash486cb9f_0         4.1 MB  conda-forge/channel/main
    python-3.6.7               |    h8dc6b48_1003        20.5 MB  conda-forge/channel/main
    ------------------------------------------------------------
                                           Total:        25.1 MB

The following NEW packages will be INSTALLED:

  blas               conda-forge/channel/main/osx-64::blas-1.1-openblas
  ca-certificates    conda-forge/channel/main/osx-64::ca-certificates-2018.11.29-ha4d7672_0
  certifi            conda-forge/channel/main/osx-64::certifi-2018.11.29-py36_1000
  libcxx             conda-forge/channel/main/osx-64::libcxx-7.0.0-h2d50403_2
  libffi             conda-forge/channel/main/osx-64::libffi-3.2.1-h0a44026_1005
  libgfortran        conda-forge/channel/main/osx-64::libgfortran-3.0.1-0
  llvm-meta          conda-forge/channel/main/noarch::llvm-meta-7.0.0-0
  ncurses            conda-forge/channel/main/osx-64::ncurses-6.1-h0a44026_1002
  numpy              conda-forge/channel/main/osx-64::numpy-1.16.2-py36_blas_openblash486cb9f_0
  openblas           conda-forge/channel/main/osx-64::openblas-0.3.3-hdc02c5d_1001
  openssl            conda-forge/channel/main/osx-64::openssl-1.1.1a-h1de35cc_1000
  pip                conda-forge/channel/main/osx-64::pip-19.0.3-py36_0
  python             conda-forge/channel/main/osx-64::python-3.6.7-h8dc6b48_1003
  readline           conda-forge/channel/main/osx-64::readline-7.0-hcfe32e1_1001
  setuptools         conda-forge/channel/main/osx-64::setuptools-40.8.0-py36_0
  sqlite             conda-forge/channel/main/osx-64::sqlite-3.26.0-h1765d9f_1000
  tk                 conda-forge/channel/main/osx-64::tk-8.6.9-ha441bb4_1000
  wheel              conda-forge/channel/main/osx-64::wheel-0.33.1-py36_0
  xz                 conda-forge/channel/main/osx-64::xz-5.2.4-h1de35cc_1001
  zlib               conda-forge/channel/main/osx-64::zlib-1.2.11-h1de35cc_1004



Downloading and Extracting Packages
llvm-meta-7.0.0      | 2 KB      | ##################################### | 100% 
numpy-1.16.2         | 4.1 MB    | ##################################### | 100% 
blas-1.1             | 1 KB      | ##################################### | 100% 
libgfortran-3.0.1    | 495 KB    | ##################################### | 100% 
python-3.6.7         | 20.5 MB   | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate gfortran-test5
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) nsidc-worsley:~ brodzik$ 

********************************************

Which is great!

So did I understand this correctly, that some combination of reinstalling miniconda3, updating conda itself and cleaning the repo index with `conda clean -i` actually did the trick?

**Comment by beckermr** [comment]
Something like that. Conda does not change local index data once it is downloaded. This is the data that determines which dependencies are allowed. So some combinations of the actions above got the freshly patched index data downloaded.

**Comment by mjbrodzik** [comment]
Thank you very much for the help.  Now back to work!

**Comment by rgommers** [comment]
awesome, thanks @mjbrodzik for confirming that things work now, and @beckermr for pointing out the right fix!

**Comment by glitterzhang** [comment]
Did:
**conda uninstall numpy**  and **conda install numpy**. Problem fixed for me.

**Comment by fedorpashin** [comment]
Solved this problem by installing **openblas** with conda.

**Comment by EZ4ZZW** [comment]
> Solved this problem by installing **openblas** with conda.

This solved my problem !  Thank u very much !

**Comment by tengjuilin** [comment]
For minimal reproducible example of

```
conda create -n numpytest numpy -c conda-forge
conda activate numpytest
```

the solution of

```
conda uninstall numpy
conda install numpy
```

works well. However, if the environment is created with `environment.yml`, the environment will not be well-configured upon creation, which may lead to reproducibility issues.

This may or may not be a conda problem: https://github.com/conda-forge/numpy-feedstock/issues/126

**Comment by mattip** [comment]
This issue was closed almost a year ago. Please open a new issue and be sure to describe which  version of [environment.yml](https://github.com/numpy/numpy/blob/main/environment.yml) you are using.

**Comment by rgommers** [comment]
Already done at https://github.com/conda-forge/numpy-feedstock/issues/279. This is not a numpy issue

**Comment by Alexandro1112** [comment]
I have same problem.
I using command 
```
 pip3 install --force-reinstall -U numpy==1.24.0rc2
```
and
```
import numpy
```
Output without problems.
```
Process finished with exit code 0
```
