### ISSUE TITLE
number is assignable to constant value e.g. np.nan

### ISSUE THREAD

**Issue by terasakisatoshi** [numpy/numpy#12981]
https://docs.scipy.org/doc/numpy/reference/constants.html says

> numpy.nan¶
IEEE 754 floating point representation of Not a Number (NaN)

Of course this is not a number literally and this is treated as constant.
On the other hand the constant `np.nan` happens to be changed.

### Reproducing code example:

```python
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:11) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.nan
nan
>>> np.isnan(np.nan)
True
>>> np.nan != 1
True
>>> np.nan == 1 # one tries to compare np.nan and 1
False
>>> np.nan = 1 # but makes a mistake
>>> np.isnan(np.nan)
False
>>> np.nan == 1 # got ridiculous result
True
>>> np.__version__
'1.15.2'
```

- I know Python programmers are kind/smart so that they don't do this such evil thing.
we should not change(or assign to) any kinds of constant numbers given by library.
- I also know since Python has a feature overriding almost anything, it may happens and induces some bugs.

```python
>>> import numpy as np
>>> 1/np.inf
0.0
>>> np.inf = 0 # I do not know who wants to do this but could be done.
>>> 1/np.inf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

- Does anyone have any ideas other than "we should be careful"?

Thank you.

### Numpy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.15.2 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:11) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

**Comment by rgommers** [comment]
>     * I also know since Python has a feature overriding almost anything, it may happens and induces some bugs.

Indeed, names can be assigned to. E.g.:

```
In [1]: np.linspace = 3

In [2]: np.linspace
Out[2]: 3
```

This kind of thing simply comes as a side effect with the flexibility of Python.

>     * Does anyone have any ideas other than "we should be careful"?

Write tests for your code

**Comment by eric-wieser** [comment]
To elaborate on this: Python does nothing to stop you changing `math.pi`, so it's consistent for us also not to do anything to protect our constants.

If you feel strongly about this, you could send something to `python-ideas`
