### ISSUE TITLE
Weird behaviour in indexing arrays with negative indices

### ISSUE THREAD

**Issue by PseudoFlame** [numpy/numpy#12985]
When indexing an array with negative indices, it does behave differently depending on the size of the array and the value of the entered indices. The behavior is not intuitive to the user and leads to unexpected results.
Expected behavior (from my point of view / desired behavior): ignore negative (starting) indices and treat them as zeros.

### Reproducing code example:

```python
import numpy as np

print np.arange(6)[-4:2]
# prints array([], dtype=int64)

print np.arange(3)[-4:2]
# prints array([0, 1])

# np.version.full_version = '1.11.3'
```

### Error message:
None (see comments in code example above or try yourself)

### Numpy/Python version information:

1.11.3
2.7.15 |Anaconda, Inc.| (default, Oct 10 2018, 21:32:13) 
[GCC 7.3.0]

**Comment by seberg** [comment]
We are inheriting the slicing behaviour from python (lists, strings, etc.), so I do not think there is anything strange here. I do not really agree anyway. The starting indices are not that special that they should be different from others, and e.g. `arr[-5:]` is very useful.

There is nothing that can be done here even if there was motivation, so closing.

**Comment by ksunden** [comment]
To elaborate a little on _why_ the behaviour is expected, negative indices just count from the end, so in the example:

```
print np.arange(6)[-4:2]
```
Since the array is of length 6, this is equavalent to taking the slice `[2:2]`, which of course is empty

but in 
```
print np.arange(3)[-4:2]
```
The negative index actually is larger than the array size, but the call is equavalent to `[0:2]`, hence why something is returned here, but not above

**Comment by seberg** [comment]
Yeah, so I guess the "weird" part meant here is maybe more the truncating behaviour for out-of-bound indices that python uses (and we inherit). Can't say I like that much even if it has uses occasionally, but just like said in the discussion on the mailing list there is nothing to do about it as well.
