### ISSUE TITLE
DOC: point users of np.outer to np.multiply.outer

### ISSUE THREAD

**Issue by 2sn** [numpy/numpy#12980]
(Was: np.outer with scalar)

(feature request)

When one of the operators to np.pout is a scalar, it would be great if the result could behave like a regular multiplication.

### Reproducing code example:

```python
import numpy as np

np.outer(1,[2,3,4])
# result: array([[2, 3, 4]])
# desired: array([2, 3, 4])

np.outer([2,3,4],1)
# result: array([[2], [3], [4]])
# desired: array([2, 3, 4])
```

The above results would be OK for 1D arrays, as in
```python
np.outer([1],[2,3,4])
np.outer([2,3,4],[1])
```
but scalars should behave differently.

**Comment by eric-wieser** [comment]
I'd recommend just using `np.multiply.outer`, which works as you request:
```python
>>> np.multiply.outer(1,[2,3,4])
array([2, 3, 4])
```

`np.outer` only exists at this point for compatibility with old code.

**Comment by 2sn** [comment]
Thanks!  

Could you please add note to the documentation, for others to find?  

[Closing is OK otherwise.]

**Comment by eric-wieser** [comment]
There's already a note in the see also section of [the docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html) that mentions `np.multiply.outer`:

![image](https://user-images.githubusercontent.com/425260/52909517-85766200-323e-11e9-8f0f-85163d93cab2.png)


If you don't think this is obvious enough, then feel free to submit a PR with improved docs. If you hadn't already found it, the docs have a [source] link that usually takes you to where the docstring comes from.

**Comment by 2sn** [comment]
My apologies, I overlooked that.

In fact, numpy.tensordot(..., axes=0) does the same.  It should be 
mentioned.  In contrast to what the documentation of tensordot seems to 
suggest, it also accepts scalars.

**Comment by eric-wieser** [comment]
`tensordot` behaves differently on 2d arrays.

**Comment by 2sn** [comment]
yes, but that can be easily overwritten by the `axes` parameter to make 
it behave the same.  I am also impressed with the `einsum` function.

**Comment by eric-wieser** [comment]
Looking a little closer: the following are the same for all dimensions of `a` and `b`:

* np.tensordot(a, b, axes=((), ()))`
* np.multiply.outer(a, b)`

**Comment by dhirensr** [comment]
@eric-wieser : could you mention what changes needs to be made? I mean do we mention in np.multiply.order that we could use either
    np.tensordot(a, b, axes=((), ()))
    np.multiply.outer(a, b)
and also mention that np.outer is used for compatibility with oldcode so one can use np.multiply.outer?

**Comment by gimseng** [comment]
Hi, has this issue been resolved? I am new to open-source and this project, so thought of taking this up. Let me know if that is ok.

**Comment by mattip** [comment]
Hi @gimseng. Anyone is welcome to submit a PR to any open issue. Please read the [developer guidelines](https://numpy.org/devdocs/dev/index.html) and the [guide to the documentation](https://numpy.org/devdocs/docs/index.html). When you do submit a PR, link back to this issue by putting `xref gh-12980` in your PR request (or use `fixes` or `closes` to automatically close it when merged) so others will know you are working on this.
