### ISSUE TITLE
Error importing numpy in AWS Lambda

### ISSUE THREAD

**Issue by jz34** [numpy/numpy#12992]
I was trying to deploy a python package in AWS Lambda following the instruction from https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html. I include numpy as my dependency in my deployment package. However, when I upload my deployment zip file onto lambda. There is always an import error like this:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'plotting_function': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /var/lang/bin/python3.7),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

My OS is Mac and my python version is 3.7. I installed numpy by using pip install lumpy --target . from https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html

Can someone help me? Thanks!

**Comment by rgommers** [comment]
> My OS is Mac and my python version is 3.7. I installed numpy by using pip install lumpy --target

That will not work. You cannot package anything except pure Python code on Mac, because Mac != Linux. Your zip file contents need to be compatible with Amazon Linux.

See the note at the top of https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html. It links to https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html for more details.

The AWS docs are pretty crap for learning about this stuff, I suggest you follow a tutorial blog post like https://serverless.com/blog/serverless-python-packaging/

**Comment by jamesshapiro** [comment]
I would also recommend https://serverless.com/blog/serverless-python-packaging/

Note that I had to add:

package:
  exclude:
    - venv/**

... to the end of my serverless.yml file in order to get the .zip file small enough to successfully load in Lambda.

**Comment by renanferr** [comment]
Specifying python version when installing numpy via pip worked for me. I was using Python 3.7 as my lambda runtime so I did this and it worked just fine:

`python3.7 -m pip install ...`

**Comment by jamesshapiro** [comment]
Current best practices are to import numpy as a lambda layer. See here: https://stackoverflow.com/questions/42534850/installing-numpy-on-mac-to-work-on-aws-lambda/58136903#58136903

**Comment by TMorville** [comment]
Related to #8498.
