### ISSUE TITLE
undefined symbol: cblas_sgemm

### ISSUE THREAD

**Issue by THLB2019** [numpy/numpy#12999]
This is on installing numpy on raspberry pi 3. I used the Noobs latest version and so using Raspbian stretch. Python was already installed, and I think numpy was already included. At the time, I think that import numpy was working well.
I installed openCV and it didn't work for a while as I had not put some necessary modules, but finally got it to work. So far so good.
Later I was trying to install matplotlib, and this didn't go very smoothly. I made a number of attempts where the message in the title was already flagged. I finally manage to get the import matplotlib to work, but then numpy stopped importing. Now I cannot import either matplotlib or numpy, despite having uninstalled numpy (pip3 uninstall numpy) and reinstalled:

  /home/pi/.local/lib/python3.5/site-packages/numpy/tests/test_warnings.py
  /home/pi/.local/lib/python3.5/site-packages/numpy/version.py
Proceed (y/n)? y
  Successfully uninstalled numpy-1.16.1
pi@raspberrypi:~ $ pip3 install numpy
Collecting numpy
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.16.1-cp35-cp35m-linux_armv7l.whl
Installing collected packages: numpy
Successfully installed numpy-1.16.1
pi@raspberrypi:~ $ 

Prior to uninstalling numpy, I did try to install without uninstalling, and downloaded the cached file mentioned.

Now, I cannot import numpy or matplotlib and for both get a similar error and the message telling me to raise this new issue which I am doing now.

>>> import numpy
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/pi/.local/lib/python3.5/site-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import numpy
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /home/pi/.local/lib/python3.5/site-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm

>>> import matplotlib
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/pi/.local/lib/python3.5/site-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import matplotlib
  File "/home/pi/.local/lib/python3.5/site-packages/matplotlib/__init__.py", line 141, in <module>
    from . import cbook, rcsetup
  File "/home/pi/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 33, in <module>
    import numpy as np
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /home/pi/.local/lib/python3.5/site-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm

I hope this helps and that it will eventually contribute to making the installation of these two packages easier in the future.

Thanks,

Thomas

**Comment by seberg** [comment]
@THLB2019 can you check what `ldd` on the shell tells you? I could imagine that it is linked to an openblas version and due to some update it is now picking up an incorrect OpenBLAS (or other BLAS implementation) version (one that was compiled without exporting the cblas symbols). It might be good to find out which blas implementation is normally used on this setup, I do not know.

**Comment by msinkec** [comment]
I'm having the same issue on a Rpi3.

@seberg 
pi@raspberrypi:~ $ ldd /usr/local/lib/python3.5/dist-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so
	linux-vdso.so.1 (0x7eaff000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76d12000)
	libf77blas.so.3 => /usr/lib/libf77blas.so.3 (0x76cd8000)
	libcblas.so.3 => /usr/lib/arm-linux-gnueabihf/libcblas.so.3 (0x76c7e000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x76a06000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76987000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x7695e000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x7681f000)
	/lib/ld-linux-armhf.so.3 (0x76f37000)
	libgfortran.so.3 => /usr/lib/arm-linux-gnueabihf/libgfortran.so.3 (0x7676a000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x7673d000)
	libf2c.so.2 => /usr/lib/arm-linux-gnueabihf/libf2c.so.2 (0x76714000)

**Comment by msinkec** [comment]
On my x64 machine it seems to be linked with a bundled .so:

miha@legion:~$ ldd /usr/local/lib/python3.6/dist-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffd571c1000)
	libopenblasp-r0-382c8f3a.3.5.dev.so => /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libopenblasp-r0-382c8f3a.3.5.dev.so (0x00007f69e3cea000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f69e394c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f69e372d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f69e333c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f69e604c000)
	libgfortran-ed201abd.so.3.0.0 => /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0 (0x00007f69e3042000)

This one works fine.

**Comment by msinkec** [comment]
I fixed the issue by deleting /usr/local/lib/python3.5/dist-packages/numpy and re-building it with:
    $ sudo pip3 install numpy

Now the ldd output is:
miha@legion:~$  ldd /usr/local/lib/python3.6/dist-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffc8b136000)
	libopenblasp-r0-382c8f3a.3.5.dev.so => /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libopenblasp-r0-382c8f3a.3.5.dev.so (0x00007f3f20b4d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3f207af000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3f20590000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3f2019f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3f22eaf000)
	libgfortran-ed201abd.so.3.0.0 => /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0 (0x00007f3f1fea5000)

**Comment by mattip** [comment]
Closing. Each instance of this problem is unique, please report all relevant information if you are struck by this. Sometimes installing other packages can clobber the OpenBLAS needed by NumPy.

**Comment by skyroam** [comment]
Maybe you can try the following commands:
```bash
#sudo apt-get remove python-numpy
sudo apt-get remove python3-numpy
pip3 uninstall numpy
sudo apt-get install python3-numpy
```
It fixes my issue.

**Comment by daixiangzi** [comment]
> ```shell
> sudo apt-get remove python3-numpy
> ```

ok,it sure to help me,but this is why??

**Comment by jachymb** [comment]
I am getting exactly the same error as in the first post today when trying to do

    from numpy.distutils.system_info import default_include_dirs, default_lib_dirs

**Comment by mattip** [comment]
This issue is closed. I am closing discussion here so that people will open a new issue instead of commenting here.
