### ISSUE TITLE
np.full much slower than np.empty + .fill

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#13001]
Am finding that `np.full` is notably slower than running `np.empty` and calling `.fill` on the array. This seems a bit surprising to me as I would think `full` would be roughly equivalent to the latter. Maybe I'm missing something?

### Reproducing code example:

```python
In [1]: import numpy as np                                                      

In [2]: %%timeit 
   ...:  
   ...: a = np.full((100, 110), 21.0, float) 
   ...:  
   ...:                                                                         
4.61 µs ± 84.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [3]: %%timeit 
   ...:  
   ...: a = np.empty((100, 110), float) 
   ...: a.fill(21.0) 
   ...:  
   ...:                                                                         
3.53 µs ± 81.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

### Numpy/Python version information:

```python
In [4]: import sys, numpy; print(numpy.__version__, sys.version)                
1.16.0 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 10:30:07) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by seberg** [comment]
I think there is just about 1us overhead because you have an additional function call with slightly added complexity. Much of it may be `copyto` vs. `fill`, but that probably has very good reasons.

Could probably be micro-optimized, somewhat doubt it is worth it though?

**Comment by jakirkham** [comment]
FWIW here is the time for `copyto`.

```python
In [1]: import numpy as np                                                      

In [2]: %%timeit 
   ...:  
   ...: a = np.empty((100, 110), float) 
   ...: np.copyto(a, 21.0) 
   ...:  
   ...:                                                                         
3.73 µs ± 55.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

**Comment by jakirkham** [comment]
If I write, my own custom `full` function, the timing is basically the same.

```python
In [1]: import numpy as np                                                      

In [2]: def full(shape, fill_value, dtype): 
   ...:     a = np.empty(shape, dtype) 
   ...:     np.copyto(a, fill_value) 
   ...:     return a 
   ...:                                                                         

In [3]: %%timeit 
   ...:  
   ...: a = full((100, 110), 21.0, float) 
   ...:  
   ...:                                                                         
3.78 µs ± 84.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Any ideas why it is still significantly slower to use `np.full`?

**Comment by seberg** [comment]
@jakirkham, ah right, than the big difference is going to be due to the new `__array_function__` dispatching mechanism. Since Stephan Hoyer is aware of that, I will close this issue.

**Comment by seberg** [comment]
@jakirkham actually, sorry, probably more likely this:
```
if dtype is None:
     dtype = array(fill_value).dtype
```
has to create an array. Maybe if we change that to:
```
if dtype is None:
    fill_value = array(fill_value)
    dtype = fill_value.dtype
```
the overhead would be gone. But might have to think about corner cases.

**Comment by seberg** [comment]
OK, grrr, should take it slower or have more coffee ;). The difference is due to the `"unsafe"` kwarg. And if I glance at the code, I think 100% of that difference is just the python argument parsing (unless our parsing of "unsafe" is slow). You are timing very fast things after all...

I guess you could get half-way just by positional passing instead of passing by kwarg if you feel like micro optimizing this.

**Comment by mattip** [comment]
Closing. If more discussion is needed please reopen.

**Comment by seberg** [comment]
Agreed, it is a nit. If anyone feels like to micro-optimize they can take it up directly.
