### ISSUE TITLE
Installing and setting up gprMax - numpy errors

### ISSUE THREAD

**Issue by lucyevers** [numpy/numpy#13000]
Hello, I am an inexperienced student trying and failing to install gprMax following the Getting Started doc. When entering (gprMax)$ python setup.py build I got an error of importing the multiarray numpy extension module failed. I have tried git clean -xdf and don't know how to reinstall numpy. I tried to add C:\Users\anima\Miniconda3\envs\gprmax\python.exe to my path but not sure if this did anything. 
My screenshots will probably best describe the troubles I am facing - this is my first time using the command promt window so don't really understand what's going on!

### Reproducing code example:

```
![2019-02-20](https://user-images.githubusercontent.com/47829397/53116398-7fcf9380-3540-11e9-8f8a-4d1ed6e4f49e.png)
![2019-02-20 1](https://user-images.githubusercontent.com/47829397/53116408-852cde00-3540-11e9-9c5b-6813a840a7a7.png)
![2019-02-20 2](https://user-images.githubusercontent.com/47829397/53116412-89f19200-3540-11e9-81c1-c9e87b0ee32e.png)
![2019-02-20 3](https://user-images.githubusercontent.com/47829397/53116420-8e1daf80-3540-11e9-8eab-7d5dde4b1f2f.png)
![2019-02-20 4](https://user-images.githubusercontent.com/47829397/53116429-937afa00-3540-11e9-9eaf-cc6d14f1c8e1.png)
![2019-02-20 5](https://user-images.githubusercontent.com/47829397/53116442-970e8100-3540-11e9-8ee2-c333e984a3ba.png)






<< (gprmax) C:\Users\anima\Miniconda3\gprMax>python setup.py build
Traceback (most recent call last):
  File "C:\Users\anima\Miniconda3\envs\gprmax\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "C:\Users\anima\Miniconda3\envs\gprmax\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\anima\Miniconda3\envs\gprmax\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found. >>
```

### Error message: Original error was: DLL load failed: The specified module could not be found. During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    import numpy as np
  File "C:\Users\anima\Miniconda3\envs\gprmax\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\anima\Miniconda3\envs\gprmax\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)

**Comment by mattip** [comment]
Could you link to the documentation you are following? If you are using Anaconda, you may need to use an older version since their newest version has a [bug](https://github.com/ContinuumIO/anaconda-issues/issues/10628) that prevents using a numpy other than the one provided by Anaconda.

**Comment by lucyevers** [comment]
http://docs.gprmax.com/en/latest/include_readme.html#installation
Followed all the steps on this. Okay I installed the 3.7 version so can try an earlier one.

**Comment by mattip** [comment]
It seems they [require updating numpy>1.15.4](https://github.com/gprMax/gprMax/blob/9d44724ce16842073dcbf0e9edb3bc63774cc1f5/conda_env.yml) which may be why it is updating numpy from the one provided by Anaconda while building and installing the package.
