### ISSUE TITLE
impossible to convert float, the exponent is cut

### ISSUE THREAD

**Issue by PalGiupo** [numpy/numpy#13018]
### Reproducing code example:

```python
import numpy as np
a = np.array(['6693.0', '8974.0', '5893.0', '5877.0', '9060.0', '6149.0', '7231.0', '5813.0', '7367.0', '6313.0', '399.0', '11904.0', '302.6666666666667', '7173.0', '2753.0', '176.0', '332.0', '4462.0', '1691.25', '21394746.0', '304.0', '1649.0', '77.0', '901.0', '222.67567567567568', '201.33333333333334', '73.5'])
dataset = np.column_stack((a, a))
dataset_scaled = dataset.copy()

from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
dataset_scaled[:, 1:] = min_max_scaler.fit_transform(dataset_scaled[:, 1:])
```
When I use Min Max I have a Warning, but i think it's irrilevant:

> sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype <U18 was converted to float64 by MinMaxScaler.
>   warnings.warn(msg, DataConversionWarning)

Thi is the Output of dataset_scaled:
```python
dataset_scaled
Out[159]: 
array([['6693.0', '0.0003093994544669'],
       ['8974.0', '0.0004160147812498'],
       ['5893.0', '0.0002720069680898'],
       ['5877.0', '0.0002712591183622'],
       ['9060.0', '0.0004200344735354'],
       ['6149.0', '0.0002839725637305'],
       ['7231.0', '0.0003345459015556'],
       ['5813.0', '0.0002682677194521'],
       ['7367.0', '0.0003409026242397'],
       ['6313.0', '0.0002916380234378'],
       ['399.0', '1.5214067894706029'],
       ['11904.0', '0.0005529647626062'],
       ['302.6666666666667', '1.071138932678996e'],
       ['7173.0', '0.0003318349462932'],
       ['2753.0', '0.0001252414590594'],
       ['176.0', '4.7909123170733275'],
       ['332.0', '1.2082447160619073'],
       ['4462.0', '0.0002051211580826'],
       ['1691.25', '7.561461854580854e'],
       ['21394746.0', '0.9999999999999999'],
       ['304.0', '1.0773710137418555'],
       ['1649.0', '7.363982785901489e'],
       ['77.0', '1.6359212790006476'],
       ['901.0', '3.867785309637248e'],
       ['222.67567567567568', '6.972561775632493e'],
       ['201.33333333333334', '5.975007719016654e'],
       ['73.5', '0.0']], dtype='<U18')
```

The error happens when i try to convert to float:
`dataset_scaled.astype(np.float)`
### Error message:
ValueError: could not convert string to float: **'1.071138932678996e'** (thirteenth row)

I don't know if it's a Scikit problem in the conversion or Numpy problem in the column selection...I try to bring it back to the skikit developers too
### Numpy/Python version information: Python 3.7.1, numpy 1.15.4

Workaround that works:
```python
dataset_scaled2 = dataset.copy()
dataset_scaled2 = min_max_scaler.fit_transform(dataset_scaled2)
```
The line that created problems is now correct:

> [1.07113893e-05, 1.07113893e-05],

**Comment by rgommers** [comment]
see the `e` at the end of `'1.071138932678996e'` - that's not a valid string representation of a float. hence a conversion issue. that said, `MinMaxScalar` is designed to work with floats, not float data in strings. so I'd say it's user error, please just convert your data to floats before passing it to any numpy or scikit-learn function
