### ISSUE TITLE
Original error was: DLL load failed【in the python of Maya2018】

### ISSUE THREAD

**Issue by Hei5enber9** [numpy/numpy#13010]
I have 2 versions of python.

*D:\Python2.7\python2*
*E:\maya2018\Maya2018\bin\mayapy*

I want to use Numpy in mayapy.
Therefore, I copy the Numpy file in 
*D:\Python2.7\Lib\site-packages\numpy*
 to 
*E:\maya2018\Maya2018\Python\Lib\site-packages*.

And then I open mayapy in cmd. 
```
C:\Users\shiganquan>mayapy
Python 2.7.11 (default, Jul  1 2016, 02:08:48) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\maya2018\Maya2018\Python\lib\site-packages\numpy\__init__.py", line 1
42, in <module>
    from . import core
  File "E:\maya2018\Maya2018\Python\lib\site-packages\numpy\core\__init__.py", l
ine 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using E:\maya2018\Ma
ya2018\bin\mayapy.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: 找不到指定的模块。
```

### Numpy/Python version information:
*D:\Python2.7\python2: *
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Numpy1.16.1

*E:\maya2018\Maya2018\bin\mayapy*
Python 2.7.11 (default, Jul  1 2016, 02:08:48) [MSC v.1900 64 bit (AMD64)] on win32
Numpy1.16.1

I have tried that put the ./lib into my PATH, but it doesn't work.
```
E:\maya2018\Maya2018\Python\Lib\site-packages\numpy\.libs
```

**Comment by mattip** [comment]
Is there a dll file in `E:\maya2018\Maya2018\Python\Lib\site-packages\numpy\.libs` ? If you stop in a debugger (you can add the line `import pdb;pdb.set_trace()` just before the line that raises the exception) and do `import os; print '\n'.join(os.environ['PATH'].split(';'))` at the command prompt to pretty-print the path, do you see that directory?

**Comment by Hei5enber9** [comment]
Yes, I can see the directory.
The output is shown in the following image.
![wechatimg222](https://user-images.githubusercontent.com/40930438/53227924-ac0f1f80-36ba-11e9-85ab-5f0a6f5f4baa.jpeg)

**Comment by mattip** [comment]
Is there a dll file in `E:\maya2018\Maya2018\Python\Lib\site-packages\numpy\.libs` ?

Could you try putting the added directory first in the path and make sure it is first when you stop in the debugger?

**Comment by rgommers** [comment]
Maya Python has no way to install packages like NumPy according to its docs. There is no `pip` shipped with it. It seems like their Python is incompatible with regular Windows Python versions, because it used a different compiler: https://forums.autodesk.com/t5/maya-programming/adding-python-modules-scipy-numpy/td-p/4304367

So I'm afraid the answer is, we can't help you - you will need to compile from scratch, and/or complain to Autodesk.

> Therefore, I copy the Numpy file in

this is never a valid way to install any Python package, and will result in lots of problems. please don't do that, especially for any package which contains compiled extensions (like numpy).

**Comment by Hei5enber9** [comment]
Thank you for your instruction!
