### ISSUE TITLE
DOC: array creation API is defined twice in docs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13013]
The information in [`doc/source/user/c-info.how-to-extend.rst`](http://www.numpy.org/devdocs/user/c-info.how-to-extend.html#dealing-with-array-objects) is repeated in [`doc/source/reference/c-api.array.rst](http://www.numpy.org/devdocs/reference/c-api.array.html?highlight=pyarray_simplenewfromdata#creating-arrays). The first should only reference the second, and the descriptive text should be merged.

This may be a good starter task. The cycle to fix this issue, based on the [doc building documentation](http://www.numpy.org/devdocs/docs/howto_build_docs.html) is to 

1. create the documentation with `make html`
2. Note the many warnings about `duplicate C object description` in the two files
3. Edit the files to unify the documentation, one should be using `.. c:function::` to define the functions and the other using `:c:func:` to reference it, perhaps with descriptive text.
4. Use `firefox build/html/reference/c-api.array.html` and `firefox build/html/user/c-info.how-to-extend.html` to view the changes

**Comment by barufa** [comment]
I will try to solve it!

**Comment by high-in-entropy** [comment]
@mattip I would like to contribute to this issue.

**Comment by mattip** [comment]
Welcome!
Information on how to contribute is in our [devdocs](www.numpy.org/devdocs/dev/gitwash/development_workflow.html). If it is not clear, please issue a PR to help with that too.

**Comment by high-in-entropy** [comment]
@mattip Although this was tagged easy, I am not able to solve the issue. [I am completely new to open source contributions].

**Comment by mattip** [comment]
Which one of 1-4 is giving you trouble?

**Comment by bmakos** [comment]
@high-in-entropy do you still want to work on this? If not I'd like to give it a shot, I also never updated the documentation - would be nice to learn.

**Comment by high-in-entropy** [comment]
@bmakos  Yes please go on.

**Comment by bmakos** [comment]
@mattip 

I am struggling with the link from [c-api.array.rst](http://www.numpy.org/devdocs/reference/c-api.array.html?highlight=pyarray_simplenewfromdata#creating-arrays) to [c-info.how-to-extend.rst](http://www.numpy.org/devdocs/user/c-info.how-to-extend.html#dealing-with-array-objects). 

I changed the code of [doc/source/user/c-info.how-to-extend.rst](http://www.numpy.org/devdocs/user/c-info.how-to-extend.html#dealing-with-array-objects) to `:c:cfunc:'PyArray_SimpleNew'` but there is no link between. 

Found some instructions on how to list the `objects.inv` content: `python -m sphinx.ext.intersphinx 'objects.inv' `. This listing does not contain `PyArray_SimpleNew`... 

Does this mean that we have to create in the `doc/sphinxext/doc/conf.py` file a link using `intersphinx_mapping`? Probably not, as I can see there is a link to `PyArray_NewFromDescr` that works. Is there some other step to be done besides the `build html` once I do the changes?

**Comment by mattip** [comment]
You need to use backticks around the function name
```
:c:cfunc:`PyArray_SimpleNew`
not
:c:cfunc:'PyArray_SimpleNew'
```

**Comment by bmakos** [comment]
Yes, I used the backticks in the source, I used normal ones here for comment because the code segment is between backticks...

**Comment by mattip** [comment]
Weird. Can you push your branch to your fork of the repo so I can take a look?

**Comment by bmakos** [comment]
I will push it when I get home in a few days. Thank you!

**Comment by karunagoyalk** [comment]
Hey!
I would like to work on this issue! Can I go ahead?

**Comment by bmakos** [comment]
I wanted to send a pr tomorrow for it. I am away from home for a few days without pc, returning today. Did you try to do the changes and the links worked for you?

**Comment by bmakos** [comment]
I re-did the changes and now linking seems to work. Should I try to merge the descriptions?

**Comment by mattip** [comment]
+1. The general idea in my opinion is that we need a concise and accurate technical description of the functions and their parameters, (those should be in `c-api.array.rst`), and a higher level, wordier first-user description (those should stay in `c-info.how-to-extend.rst`

**Comment by mattip** [comment]
While #13119 made a step in the right direction, the documentation content is still duplicated. Reopening.

**Comment by vanitaa** [comment]
I m trying to create the documentation with `make html` but i m getting the error during the build 

```mkdir -p build/html build/doctrees
LANG=C sphinx-build -b html -WT --keep-going -d build/doctrees   source build/html 
Running Sphinx v1.8.5
1.15 1.15.4

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/Users/panda/numpy/doc/source/conf.py", line 95, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init && git submodule update

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/Users/panda/numpy/doc/source/conf.py", line 95, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init && git submodule update


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/Users/panda/numpy/doc/source/conf.py", line 95, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init && git submodule update
```


how can I buld it on my system?

**Comment by mattip** [comment]
Did you run `git submodule init && git submodule update`?

**Comment by bmakos** [comment]
@vanitaa I think you did not issue the ‘git submodule init’ and ‘git submodule update’ commands. The start of this thread has a link to building the docs.

**Comment by vanitaa** [comment]
thanks, @mattip @bmakos my previous issue has been resolved. But now I m getting this error
```mkdir -p build/html build/doctrees
LANG=C sphinx-build -b html -WT --keep-going -d build/doctrees   source build/html 
Running Sphinx v1.8.5
1.15 1.15.4

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'matplotlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension matplotlib.sphinxext.plot_directive (exception: No module named 'matplotlib')

Extension error:
Could not import extension matplotlib.sphinxext.plot_directive (exception: No module named 'matplotlib')
make: *** [html] Error 2
```
though matplotlib is installed

**Comment by mattip** [comment]
It seems you are using a system python3.7 since sphinx is loading from `/usr/local/lib/python3.7/site-packages/sphinx`. How did you get sphinx installed into it? You should install matplotlib and scipy via the same mechanism, and verify that python3.7 -c "import matplotlib" works.

Using `sudo pipXX install` is not recommended practice, you should use a virtualenv or `pip3.7 install --user ...` instead.

**Comment by mattip** [comment]
Maybe you could use your experience to suggest improvements to the [doc building guide](http://www.numpy.org/devdocs/docs/howto_build_docs.html) which you should be following.

**Comment by vrindaaa** [comment]
While trying to create the documentation using make html I'm getting the following error 
mkdir -p build/html build/doctrees
LANG=C sphinx-build -b html -WT --keep-going -d build/doctrees   source build/html 
Sphinx v1.6.7
Usage: sphinx-build [options] sourcedir outdir [filenames...]

Filename arguments:
  without -a and without filenames, write new and changed files.
  with -a, write all files.
  with filenames, write these.

sphinx-build: error: no such option: --keep-going
Makefile:123: recipe for target 'html' failed
make: *** [html] Error 2
Could someone help me with the same?

**Comment by mattip** [comment]
Sphinx 1.6.7 is really old. We require sphinx 1.8.3 or later. Your choices are:
- set up a virtualenv `sudo apt install virtualenv; virtualenv -p python3 /path/to/some/directory; source /path/to/some/directory/bin/activate`. Then you can freely `pip install` anything you need into the virtualenv, set up multiple virtualenvs, and easily start over when that virtualenv gets messed up (including installing random versions of numpy into it for testing. To exit the virtualenv: `deactivate`
- `pip3 install --user sphinx` which will add another overlay of packages to ~/.pip but might be hard to manage and is not isolated, any python3 you run will pick up the extra packages
- use anaconda with an updated sphinx. I am not really sure what versions they ship

**Comment by vrindaaa** [comment]
I tried to run `make html` in the numpy/numpy/doc directory but I'm getting the following error
make: *** No rule to make target 'html'.  Stop.
What am I doing wrong?

**Comment by rgommers** [comment]
you're in the wrong directory, use `doc/` not `numpy/doc/`. to verify you're in the right place, there's a file `Makefile` there
