### ISSUE TITLE
Convert uses of `property` to `@property`

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13024]
A good starter issue - there are some places in numpy that use the pre-decorator property syntax:
```python
def set_mask(self, value):
    ...
def get_mask(self):
    ...
mask = property(fget=get_mask, fset=set_mask, doc="the docstring")
```

It would be some nice cleanup to go through these and replace them with
```python
@property
def mask(self):
    """
    the docstring
    """
    # the contents of get_mask

@mask.setter
def mask(self, value):
    # the contents of set_mask

# only needed if `set_mask` and `get_mask` do not start with `_`:
# for compatibility
get_mask = mask.fget
set_mask = mask.fset
```

An easy way to find these is to search the source for ` = property(`.

**Comment by eric-wieser** [comment]
79baef7a80769842f1c7f14e31056e4750a122e8 is an example of what a changeset here would look like.

**Comment by saubhik** [comment]
@eric-weiser I would like to work on this issue as my first one!

**Comment by Melevir** [comment]
Is the issue still in relevant status? Looks like @alexcwatt solved this.
