### ISSUE TITLE
MAINT: Remove Python 2 compatibility code

### ISSUE THREAD

**Issue by lgeiger** [numpy/numpy#13037]
[Numpy 1.17 will drop support for Python 2.7](http://www.numpy.org/neps/nep-0014-dropping-python2.7-proposal.html) and [will require Python at least 3.5](https://github.com/numpy/numpy/blob/master/setup.py#L30-L31).

Numpy currently uses quite a bit of code to behave well with Python 2.7-3.4 ([Python code](https://github.com/numpy/numpy/search?q=sys.version_info&unscoped_q=sys.version_info), [C code](https://github.com/numpy/numpy/search?q=NPY_PY3K)). This code is not needed anymore in Numpy 1.17 and introduces a lot of clutter in the code base.

Would you welcome PRs that remove the legacy code?

Possible drawbacks: It may make it a bit harder to backport fixes from Numpy 1.17 to 1.16. Large-scale refactoring always has the possibility to introduce bugs.

**Comment by mattip** [comment]
The [NEP](http://www.numpy.org/neps/nep-0014-dropping-python2.7-proposal.html) is silent on when to clean the code base, but I seem to remember discussion that "now is too early" from the perspective of backporting bug fixes. Maybe closer to Jan 2020 we could consider it.

**Comment by rgommers** [comment]
indeed, not yet please - from Jan 2020 would indeed be better. not actionable for now, so I'm closing this issue
