### ISSUE TITLE
Allow creation of *_like() arrays of arbitrary shapes

### ISSUE THREAD

**Issue by pentschev** [numpy/numpy#13043]
Following the discussion in https://github.com/dask/dask/issues/4462, in some cases it's necessary to create a new array of the same NumPy-like type (e.g., sparse or CuPy) as the input array. This can be achieved by using `{empty,full,ones,zeros}_like()` functions. However, this prevents a new array of arbitrary shape to be created.

@shoyer suggested the following change in https://github.com/dask/dask/issues/4462:

> What about adding a `shape` keyword argument to NumPy's `zeros_like`, `ones_like` and `full_like`? There's some precedence for overwriting attributes of the original array with the `dtype` argument already.

I think this is a good solution and I would like to see this implemented. I will be opening a PR for this soon.

@mrocklin @hameerabbasi FYI

**Comment by mrocklin** [comment]
This sounds like a good idea to me.  For context, @pentschev has been
trying to get dask.array and cupy working for a while and apparently has
run into this limitation several times.

**Comment by seberg** [comment]
The only possible downside would be if some of these get dispatched through ufuncs right now and that might make things tricky. Other then that, it seems a natural thing to just offer it.

**Comment by pentschev** [comment]
I've sent PR https://github.com/numpy/numpy/pull/13046 for evaluation/review, please also refer to that for suggested implementation.

**Comment by rgommers** [comment]
PR merged, closing.
