### ISSUE TITLE
can not import numpy. NameError: name 'env_added' is not defined

### ISSUE THREAD

**Issue by 365670123** [numpy/numpy#13052]
### Reproducing code example:

```python
import numpy as np
```

### Error message:

```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import numpy
  File "D:\Python\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "D:\Python\Python36\lib\site-packages\numpy\core\__init__.py", line 42, in <module>
    for envkey in env_added:
NameError: name 'env_added' is not defined
### Numpy/Python version information:
numpy-1.16.2+mkl-cp36-cp36m-win_amd64
python 3.6.7
```

**Comment by mattip** [comment]
We do not ship a 1.16.2 [`numpy/core/__init__.py`](https://github.com/numpy/numpy/blob/v1.16.2/numpy/core/__init__.py#L42) with `env_added` in it.

**Comment by eric-wieser** [comment]
[Don't we?](https://github.com/numpy/numpy/blob/v1.16.2/numpy/core/__init__.py#L72-L77)

**Comment by rgommers** [comment]
oops, I didn't double check the assertion. that said, I don't see any way that `env_added` can be undefined and this is not about 1.16.2 (line numbers don't match). so still looks like either a messed up env (2x numpy installed) or a distributor-modified `__init__.py`

**Comment by mattip** [comment]
Sorry. The line number change may be due to Anaconda patches. Maybe it would help to see the actual file?

**Comment by 365670123** [comment]
> oops, I didn't double check the assertion. that said, I don't see any way that env_added can be undefined and this is not about 1.16.2 (line numbers don't match). so still looks like either a messed up env (2x numpy installed) or a distributor-modified __init__.py

I found the reason, you are right. I download numpy1.16.2+mkl from other distributor from lfd.uci.edu. They made mistakes on __init__.py, and have fixed it before I realized it.
