### ISSUE TITLE
The performance about computing array (A+B) in place and copy

### ISSUE THREAD

**Issue by amou080515** [numpy/numpy#13066]
I want to know why the performance of the two(in place and copy) is so different.
Why copy has a better perforance than inplace.

Thanks.
### Reproducing code example:

```python
import numpy as np
from contextlib import contextmanager
import time
import numpy as np

@contextmanager
def timethis(label):
	start = time.process_time()
	try:
		yield
	finally:
		end = time.process_time()
		print(label,end-start)

A = np.ones(3)
B = np.ones(3)*2
with timethis('in place'):
    for i in range(10000):
        np.add(A,B,out=B)

A = np.ones(3)
B = np.ones(3)*2
with timethis("with copy"):
    for i in range(10000):
        B = np.add(A,B)

# output
# in place 0.010361745000000866
# with copy 0.005822838000000274
```

### Numpy/Python version information:

numpy version: 1.16.2
python version: 3.6.7

**Comment by grlee77** [comment]
I wouldn't expect there to be a benefit to in-place operation for tiny arrays that fit in the processor's cache. I don't know specifically why in-place is slower in this case, but if you use much larger arrays (at least 10s-100s of MB in size) so that they do not fit in the cache you should see a substantial gain for the in-place variant:

For example
```Python
A = np.ones(10000000)
B = np.ones(10000000)*2
with timethis('in place'):
    for i in range(100):
        np.add(A,B,out=B)

A = np.ones(10000000)
B = np.ones(10000000)*2
with timethis("with copy"):
    for i in range(100):
        B = np.add(A,B)
# in place 1.4728869300000724
# with copy 4.39137072799997
```

**Comment by seberg** [comment]
It is probably things like simply parsing the `out` kwarg (presence of kwargs at all possibly) that make the difference there.
