### ISSUE TITLE
numpy array values are change by if statement

### ISSUE THREAD

**Issue by paapu88** [numpy/numpy#13065]
Hei,
conda environment with;
python                    3.6.8                h0371630_0
numpy                     1.16.0                   pypi_0    pypi
numpy-base                1.15.4           py36hde5b4d6_0  

### Reproducing code example:

```
import numpy as np
data = np.empty([11, 5])
data[:] = np.nan
print("Before:")
print(data)
if not any(np.isnan(data[0, :], data[-1, :])):
    print("doing nothing")
print("After:")
print(data)

OUTPUT:
Before:
[[nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]
After:
[[nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [ 1.  1.  1.  1.  1.]]
```
---------------------------
(sometime I get zeros as last  row...)
Terveisin Markus

**Comment by seberg** [comment]
Of course this happens, you are using the array as an output array to `np.isnan`.

With `np.isnan(data[0, :], data[-1, :])` you explicitly ask numpy to write the result to `data[-1, :]`, so it does it.
