### ISSUE TITLE
ValueError: setting an array element with a sequence. python

### ISSUE THREAD

**Issue by sjadd** [numpy/numpy#13070]
I am trying to solve a differential equation contains complex numbers. These complex numbers are constants A and B.

### Reproducing code example:

```python
import numpy as np 
import matplotlib.pyplot as plt

# intinialize values
x0=0
y0=1
xf=2
h=0.1
n=200
y=np.zeros([n])
t=np.zeros([n])
t[0]=y0
t[0]=x0
t=np.linspace(x0,xf,n)

gamma=1.0

width=1.0

v_g=1.0

L=1.0

k=1

r=1.0

C=1j

A=((8*np.pi)**(1.0/4.0)/(np.sqrt(width*L)))*(-C/2*np.pi)*np.sqrt(gamma*v_g*L/2)

B=(k**2)+C*k*r-((width**2)*(r**2)/4)+r*v_g*t*(width**2/2)-v_g**2*t**2*(width**2/4)+k**2/width**2

for i in range(1,n):
    t[i]=t[i-1]+h
    slope=A*np.exp(B)-(1/2)*(y[i-1])
    y[i]=y[i-1]+h*slope
plt.plot(t,y,'-')

```

### Error message:
ValueError: setting an array element with a sequence.

Can anyone help me to explain the problem and give a suggestion to solve the problem?

**Comment by seberg** [comment]
Sorry, but I think it will be instructional for you to figure it out on your own:
  * Check the line that the ValueError points to and read the error message carefully
  * Inspect the code on the line and/or split it up into its components.
  * Inspect all the operands involved, you can use the debugger or simply print statements.

The numpy issue tracker is not a support platform, we do generally help out, but such debugging question should be asked elsewhere normally. You can even probably find similar questions by searching for the error message which probably gives enough hints on how what is wrong. (although again, inspecting what you are asking the code to do will tell you very quickly).
