### ISSUE TITLE
The `np.dot` resultant computation was automatically rounded

### ISSUE THREAD

**Issue by Rowing0914** [numpy/numpy#13081]
By the code below, in the highlighted part as `======= Weird Behaviour Part =======`, I was expecting a vector containing not rounded numbers. However, as I tried three different ways in the code followed by the output on my terminal. I was getting the rounded number as the outcome of `np.dot` API. 

### Reproducing code example:

```python
import numpy as np

def get_samples():
  """
  this prepares the dataset
  """
  M = np.array([[0.8, 0.2],[0.3,0.7]])
  B = np.array([[0.3,0.4,0.1,0.2],[0.2,0.2,0.3,0.3]])
  p = np.array([0.4,0.6])
  v = np.array([4,1,2])
  return M, B, p, v

def dummy(M,p,B,v):
  # ALPHA DYNAMIC calculate alpha
  result = []
  T = np.size(v)
  for t in range(T):
    if t == 0:
      result.append(B[:, int(v[t])-1]*p)
    else:

      """
      ======= Weird Behaviour Part =======
      """

      # manually compute dot product
      # output: 0.11800000000000002 0.14200000000000002
      print(M[:,0]@result[-1], M[:,1]@result[-1])

      # np.dot
      # output: [0.1  0.15]
      print(np.dot(M, result[-1]))

      # pythonic way of np.dot
      # output: [0.118 0.142]
      print(sum([i*j for (i, j) in zip(M, result[-1])]))

      result.append(sum([i*j for (i, j) in zip(M, result[-1])])*B[:, int(v[t])-1])
  return np.array(result).T

if __name__ == '__main__':
  M, B, p, v = get_samples()
  print(dummy(M,p,B,v))
```

### Error message:
No ERROR

### Numpy/Python version information:

Python: 3.6.6
Numpy: '1.14.2'

**Comment by charris** [comment]
Try
```
>>> np.set_printoptions(precision=30)
```

**Comment by charris** [comment]
You are computing the wrong things. `print(np.dot(M, result[-1]))` should be `print(np.dot(M.T, result[-1]))` in order to agree with the other computations. The "manual" computations are not matrix multiplication.


```

**Comment by Rowing0914** [comment]
> Try
> 
> ```
> >>> np.set_printoptions(precision=30)
> ```

this worked!! thank you!

**Comment by Rowing0914** [comment]
> You are computing the wrong things. `print(np.dot(M, result[-1]))` should be `print(np.dot(M.T, result[-1]))` in order to agree with the other computations. The "manual" computations are not matrix multiplication.

hmm,, I see. this worked as well..
I might have to check the implementation though, I had thought that inside `np.dot` it automatically transposed the given first argument's matrix.

**Comment by charris** [comment]
`np.dot` is plain old matrix multiplication for 2D matrices. You are probably thinking of the vector dot product, but NumPy only has one type of 1D vector, not Row and Column vectors, so even in that case there is no transpose.

**Comment by Rowing0914** [comment]
> `np.dot` is plain old matrix multiplication for 2D matrices. You are probably thinking of the vector dot product, but NumPy only has one type of 1D vector, not Row and Column vectors, so even in that case there is no transpose.

Oh, I got it. Because I was not sure by just reading the document,, but now I know! thank you so much for helping me out.
