### ISSUE TITLE
ndarray.T does not return self as doc says

### ISSUE THREAD

**Issue by toslunar** [numpy/numpy#13094]
`x.T` seems returning *a view of* `x` if `x.ndim < 2`, while the documentation (https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.T.html) says it returns "self".  To me it's not clear what is different between `x.T` and `x.transpose()` except for performance.

### Reproducing code example:

```python
import numpy as np
x = np.array([3, 4])
print(x.T is x)  # => False
print(x.T.base is x)  # => True
```

### Numpy/Python version information:
I checked two sets of versions:
```
>>> print(numpy.__version__, sys.version)
1.16.1 3.6.5 (default, Jun 21 2018, 17:25:32)
[GCC 5.4.0 20160609]
```
and
```
>>> print(numpy.__version__, sys.version)
('1.9.3', '2.7.15 (default, Nov  7 2018, 12:21:05) \n[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)]')
```

**Comment by seberg** [comment]
Yes, you are right, the doc is probably outdated and should be updated. There is no difference, it is simply a convenience shorthand.

Want to create a PR?
