### ISSUE TITLE
ediff1d with np.nan in to_begin/to_end, behaviour and error messages

### ISSUE THREAD

**Issue by stuartarchibald** [numpy/numpy#13103]
Making https://github.com/numpy/numpy/pull/12713#issuecomment-470079405 into an issue...

Patch #12713 will cause an exception to be raised in the case of a NaN in the `to_begin/to_end` arrays. Numba unit tests caught this change when updating to support 1.16 series https://github.com/numba/numba/pull/3826.

### Reproducing code example:

```python
import numpy as np
dt=np.float64
np.ediff1d(np.arange(10, dtype=dt), to_begin=np.array([1, np.nan], dtype=dt))
```
### Error message:
```
ValueError: cannot convert 'to_begin' to array with dtype 'dtype('float64')' as required for input ary
```
because of lines like this with an equality test of `array == array`: https://github.com/numpy/numpy/pull/12713/files#diff-9e06c7b7bcc8e8153f5c2df57283b4cbR109

#### Further...
The error message is perhaps  a bit strange in the context of e.g.:
```python
np.ediff1d(np.arange(10, dtype=np.float32), to_begin=np.array([np.finfo(np.float64).max], dtype=np.float64)) 
```
which produces

```
ValueError: cannot convert 'to_begin' to array with dtype 'dtype('float32')' as required for input ary
```
which is not actually the problem, because technically the array `np.array([np.finfo(np.float64).max], dtype=np.float64))` can  be converted to a `np.float32` dtype:
```
In [18]: np.array([np.finfo(np.float64).max], dtype=np.float64).astype(np.float32)                                              
Out[18]: array([inf], dtype=float32)
```
it's just that it's not "safe" under the given behavioural assumptions?

Happy to create a patch for either of these if considered a problem? Else Numba will be patched to match.

Thanks!

### Numpy/Python version information:

```
$ python -c 'import sys, numpy; print(numpy.__version__, sys.version)' 
1.16.2 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
Based on this bug report, I think #12713 was a mistake - I don't think we can meaningfully detect the different between poorly-casted input that the user wasn't expecting (as in #11490) and deliberately sloppy casting that the user wants to keep working (as in #12711).

I think the best approach here is to revert #12713, and either:
* tell our users to just fix their casting via the existing error, which is a little tough on them
* start emitting a `DeprecationWarning` place of the error. and tell them that the casting will fail in future.

**Comment by mattip** [comment]
So we have conflicting needs. In 1.14.0 the following all worked:
```
>>> import numpy as np
# From #11490, fixed in #11805 for 1.16.0
>>> a = np.array([1, 2, 3])
>>> np.ediff1d(a, np.nan)
array([1, 1, -9223372036854775808])
# From #12711, raises error in 1.16.0rc1, fixed in #12713  
>>> x = np.array([1, 2, 4, 7, 0], dtype=np.int32)
>>> np.ediff1d(x, to_begin=-99, to_end=np.array([88, 99]))
array([-99,   1,   2,   3,  -7,  88,  99], dtype=int32)
>>> dt=np.float64
# From this issue
>>> np.ediff1d(np.arange(10, dtype=dt), to_begin=np.array([1, np.nan], dtype=dt))
array([ 1., nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
```
If we revert #12713, do we revert #11805?

**Comment by charris** [comment]
Just a comment that  #12713 was backported, so if reverted, needs to be reverted in 1.16.

**Comment by AllenDowney** [comment]
Can I cast a vote in favor of reverting this type checking?  Putting NaN at the beginning or end of a diff array seems to be a common and useful option, and with this type checking it is very difficult, maybe impossible.  Even this fails:

```
a = np.array([1,2,3], dtype=np.float64)
to_end = np.array([np.nan], dtype=np.float64)
np.ediff1d(a, to_end=to_end)
```
Yields
```
ValueError: cannot convert 'to_end' to array with dtype 'dtype('float64')' as required for input ary
```

Is there any way to work around this?

**Comment by charris** [comment]
note to self, may want to backport to 1.16.

**Comment by seberg** [comment]
Hmmm, this is tricky. Should we just revert it completely (as matti noted)? The way I would see it, the cast check is somewhat correct (although it could use "same_kind" if we want to be relaxed about things), but we have to go via a `DeprecationWarning` to get there.  (I agree that the value checking is probably just a bad idea, we just have no way to spell that out nicely right now)

**Comment by eric-wieser** [comment]
Another failing case:
```
np.ediff1d(np.array([1], 'm8[s]'), to_begin=np.timedelta64('NaT', 's'))
```

**Comment by seberg** [comment]
On the zoom talk we just decided the best solution for the moment is probably to do use:

1. Same kind casting plus an additional check for integers that the casting actually was safe
2. Use safe casting for all other types.

Safe casting could be a bit stricter for float32 and float64, but since casting float64 to float32 typiclaly breaks the `==` check as well (since it loses precision), I think that is fine.

**Comment by eric-wieser** [comment]
A proposal:
```
def do_deprecated_begin_end_casting(arr, dtype_req):
    try:
        return arr.astype(dtype_req, casting='safe')
    except TypeError:
        if not np.issubdtype(dtype_req, np.integer) or dtype_req.type != np.timedelta64:
            raise
        try:
            arr_cast = arr.astype(casting='same_kind')
        except TypeError:
            pass
        else:
            if (arr_cast == arr).all():
                deprecate()
                return arr_cast
        raise
```

```
to_begin = do_deprecated_begin_end_casting(to_begin, dtype_req)
to_end = do_deprecated_begin_end_casting(to_end, dtype_req)
```

**Comment by eric-wieser** [comment]
Or simpler, as discussed with @seberg:
* Revert #12713, replace the test of integer overflow with a test of nan conversion
* Add `same_kind` to the `can_cast`
* Document that integer overflow protection was removed, and justify this as consistent with the rest of numpy

**Comment by mattip** [comment]
@seberg @eric-wieser would one of you like to implement the recommended fix?

**Comment by seberg** [comment]
I will open a PR.

**Comment by seberg** [comment]
Grrr, so `np.diff` also got these arguments now, but it uses concatenate which means that it does not give priority to the central array. They were added in 1.16. Should we undo it now just because?
