### ISSUE TITLE
Unexpected result for 32-bit right shift on uint32

### ISSUE THREAD

**Issue by javidcf** [numpy/numpy#13106]
Taken from this StackOverflow question: [Why is (2^31) >> 32 not 0?](https://stackoverflow.com/q/55097508)

A 32-bit right shift applied to a uint32 array with the value 2<sup>31</sup> in it produces an array with the value 2147483648 instead of 0. Interestingly, when the operation is applied to a scalar with the same value the result is 0.

As discussed in the linked question, this probably has to do with 32-bit shifts of 32-bit values not being well-defined in C. However, this shouldn't condition the behavior of NumPy. Most importantly, the behavior should be consistent between arrays and scalars.

### Reproducing code example:

```python
import numpy as np

print(np.array([2 ** 31], dtype=np.uint32) >> 32)
# [2147483648]
print(np.array(2 ** 31, dtype=np.uint32) >> 32)
# 0
```

### Error message:

NA

### Numpy/Python version information:

1.15.4 3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
The scalar behaves differently because the types are promoted to int64. You'll get consistent behavior if you change the this to `<< np.uint32(32)`

**Comment by javidcf** [comment]
@eric-wieser Thanks for the answer, I see, you are right. I thought type coercion would work the same for scalars and arrays, but I see it kind of inverts the priorities wrt Python values: with arrays, Python values are converted to NumPy type, and for primitives NumPy values are converted to the bigger Python type (more or less?). It is somewhat confusing/surprising but I can see the reasons for it. If this is the expected behavior I suppose this should be closed.

**Comment by bersbersbers** [comment]
Thanks for the explanation. Just to prevent early closing of this issue: regardless of the consistency issue, I feel that the behavior of `np.array([2 ** 31], dtype=np.uint32) >> 32` should be fixed or documented.

**Comment by l0calh05t** [comment]
While the promotion to `numpy.int64` is not an issue, I agree with @bersbersbers that the leaky abstraction of C shifts should at the very least be documented. But preferably, it should be checked, as allowing undefined behavior through from the Python side is not a good idea.

**Comment by charris** [comment]
There are two things involved here: C and promotion, and both have come up before. There is a languishing PR, #7473, for the C side, and it would be nice to avoid the promotion problem when defining the ufunc, giving priority to the value being shifted, but that is a trickier problem.

**Comment by florisje** [comment]
I think this is no longer an issue.

```python
import numpy as np
print(np.array([2 ** 31], dtype=np.uint32) >> 32)
# [0]
print(np.array(2 ** 31, dtype=np.uint32) >> 32)
# 0
```

Can we close this?
