### ISSUE TITLE
Document polynomial submodule

### ISSUE THREAD

**Issue by stefanv** [numpy/numpy#13113]
Currently, the `numpy.polynomial` docstring [does not provide a lot of guidance](https://www.numpy.org/devdocs/reference/routines.polynomials.html) on which functions to use.  As such, users sometimes end up using `numpy.polynomial.polynomial' and other deeper nested functionality.

We could model a docstring after, e.g., https://github.com/scipy/scipy/blob/master/scipy/interpolate/__init__.py, which categorizes functionality.

@charris I am happy to work on this, but would need some guidance from you on where users are *supposed* to go.

Current submodule docstring:

<details>

A sub-package for efficiently dealing with polynomials.

Within the documentation for this sub-package, a "finite power series,"
i.e., a polynomial (also referred to simply as a "series") is represented
by a 1-D numpy array of the polynomial's coefficients, ordered from lowest
order term to highest.  For example, array([1,2,3]) represents
``P_0 + 2*P_1 + 3*P_2``, where P_n is the n-th order basis polynomial
applicable to the specific module in question, e.g., `polynomial` (which
"wraps" the "standard" basis) or `chebyshev`.  For optimal performance,
all operations on polynomials, including evaluation at an argument, are
implemented as operations on the coefficients.  Additional (module-specific)
information can be found in the docstring for the module of interest.

</details>

**Comment by rossbar** [comment]
Closed by #16167
