### ISSUE TITLE
Wrong std for implicitly complex input

### ISSUE THREAD

**Issue by sedefe** [numpy/numpy#13110]
Standart deviation formula could give unexpected result (e.g. imaginary values) when input is implicitly complex.

### Reproducing code example:

```python
import numpy as np
a = np.array([None, 0])
a[0] = 1j
b = np.array([1j, 0])

print(f'res={np.std(a)}, dtype={a.dtype}') # gives imaginary std
print(f'res={np.std(b)}, dtype={b.dtype}')

```

### Numpy/Python version information:
numpy 1.16.2
python 3.7

res=0.5j, dtype=object
res=0.5, dtype=complex128

**Comment by eric-wieser** [comment]
I'd bet this is a somewhat pervasive issue...

**Comment by ewmoore** [comment]
I’m not sure that you could make object arrays still useful and prevent this kind of thing. 

Types can only help you if you actually use them. Making an object array is opting out of that help.

**Comment by eric-wieser** [comment]
@ewmoore: The only reason this is a problem is an incorrect optimization that avoids calling `conjugate` on non-complex arrays (which would make an unnecessary copy). If the optimization is reframed as avoiding calling conjugate on `floating` or `integer` arrays, then this problem would go away.

**Comment by seberg** [comment]
I think conjugate on object used to be broken, but it is not anymore, so we should fix this!

**Comment by ewmoore** [comment]
@eric-wieser, sorry for the noise then.  I didn't look, and assumed what the bug was.

**Comment by seberg** [comment]
Hmmm, of course fixing it could in principle break arrays with object types that do not support `.conjugate()`, although `decimal.Decimal` and the built-in numerical types all do (at least by now) I believe.

**Comment by bsipocz** [comment]
Please close. 

This has been fixed, but the github autoclosing didn't kick in. I think the reason is that the "closes" keyword was in a commit message, and the committer doesn't have write access to the repo. Had it been in the PR's description the auto closing would have worked.

**Comment by rgommers** [comment]
thanks!
