### ISSUE TITLE
DOC: Merge together DISTUTILS.rst.txt#template-files" and distutils.rst#conversion-of-src-files

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13129]
A follow-up to #11689.

These two sections describe the same distutils feature, but in different ways. It would be good to unify them.

**Comment by mattip** [comment]
The two sections are rendered [here](http://www.numpy.org/devdocs/reference/distutils_guide.html#template-files) and [here](http://www.numpy.org/devdocs/reference/distutils.html#other-files)

**Comment by aashuli** [comment]
@mattip Can I start working on this!

**Comment by mattip** [comment]
@aashuli go for it. Reference this issue in the PR so a link shows up here letting other people know it is underway.

**Comment by jyox007** [comment]
Hello @mattip I am an outreachy applicant . can i take this ticket.

**Comment by ojaswi12** [comment]
Is this issue still open? I'd like to work on this.

**Comment by mattip** [comment]
@ojaswi12 go for it. Reference this issue in the PR so a link shows up here letting other people know it is underway.

**Comment by jyox007** [comment]
Hello,@mattip I am an outreachy applicant. can I take this ticket?  
Is this issue still open?

**Comment by mattip** [comment]
We don't really "assign" issues, usually the first (and if there is more than one, best) PR is the one accepted. It is a bit unusual to have so many people interested in a single issue. 

We suggested a number of issues Outreachy applicants try. Both @aashuli and @ojaswi12 have expressed an interest, it would be a shame to invest work to have it discarded since someone else submitted first.

**Comment by ojaswi12** [comment]
For merging the two documents, do i have to concatenate one after the other, or do you want me to read both and create a new description for the both

**Comment by mattip** [comment]
@ojaswi12 merge the descriptions. It requires thinking about the content and the best way to unify the two descriptions, and also thinking about which one should be the primary source, the other should have a link rather than content. I think we do not want to delete either file at this stage.

**Comment by aashuli** [comment]
#13175
