### ISSUE TITLE
random.gamma incorrect results

### ISSUE THREAD

**Issue by franciscogarate** [numpy/numpy#13138]
In addition to parameterization (see: https://github.com/numpy/numpy/issues/3928), ``numpy.random.gamma`` has an incorrect result, not aligned with ``scipy.stats.gamma``. Please check example below:
Numpy version: 1.15.2
Scipy version: 1.1.0

### Code example:

```python
import numpy as np
import scipy.stats as st
from matplotlib import pyplot as plt

alpha = 7.
lamdba = 0.0025
theta = 1/lamdba

# Option 1:
mean = alpha / lamdba
var = alpha / (lamdba ** 2)
std = np.sqrt(var)
print(mean, std)

# Option 2 (scipy.stats):
print(st.gamma.mean(a=alpha, scale=1/lamdba), st.gamma.std(a=alpha, scale=1/lamdba))

# Option 3 & 4:
distribution = st.gamma(a=alpha, scale=1/lamdba)
print(distribution.mean(), distribution.std())
m, v = distribution.stats('mv')
print(m, np.sqrt(v))

print("percentile:")
print("-"*10)
for i in [0.5, 0.75, 0.95, 0.995]:
	print(round(st.gamma.ppf(i, a=alpha, scale=1/lamdba),2))

print("10.000 simulations:")
print("-"*10)
items = [1, lamdba, std, var, 1/lamdba, 1/std, 1/var, theta**0.5, theta**0.5/alpha]
for item in items:
	scale = item
	obs = []
	for i in range(10000):
		s = np.random.gamma(shape=mean, scale=scale)
		obs.append(s)
	print(np.mean(obs), np.percentile(obs,99.5)) # ~2800, ~6263.87

# Plot:
x = np.linspace (0, 9000, 200) 
y = st.gamma.pdf(x, a=alpha, scale=1/lamdba)
plt.plot(x, y)
plt.show()
```
<pre>
2800.0 1058.3005244258363
2800.0 1058.3005244258363
2800.0 1058.3005244258363
2800.0 1058.3005244258363
percentile:
----------
2667.85
3423.39
4736.96
6263.87
10.000 simulations:
----------
2799.897006963713 2939.4130691768314
6.999216070936152 7.354750837444137
2962502.3180644396 3107142.964045034
3135519955.3881283 3286186790.337828
1120179.56533464 1174490.7069547528
2.6462321958833925 2.7776389287956964
0.00249983363715886 0.002619975990984695
55999.8440596136 58808.98014137368
7999.3703145983245 8386.056327629416
</pre>

**Comment by Kiraeraser** [comment]
i want to solve this issue

**Comment by bashtage** [comment]
I don't think you understand the parameterization here:

```
shape = 7
scale = 400
mean = shape * scale
variance = shape * scale**2
std = np.sqrt(variance)
print(mean, std)
np.random.gamma(7,400)
x = np.random.gamma(7,400,size=(10000000,))
print(x.mean(0), x.std(0))
```

**Comment by bashtage** [comment]
In my opinion the scipy parameterization is not standard and is ultimately driven by their desire for a consistent API for distribtions.  The numpy parameterization is, for example, the first parameterization listed in Wiki.

**Comment by eric-wieser** [comment]
It might be worth documenting in the scipy version what the equivalent numpy parametrization is

**Comment by WarrenWeckesser** [comment]
NumPy and SciPy have the same parametrizations, but they use different names, and SciPy includes a location parameter this is not in NumPy.  Note that the parameters to the `gamma` function in NumPy are `shape` and `scale`.  In the formulas shown in the docstring, these parameters are referred to as `k` and `theta`, respectively.  This is explained in the first few sentences of the function's docstring.  As @bashtage, noted, those are the same `k` and `theta` as in the Wikipedia page on the gamma distribution.

The shape parameter in `scipy.stats.gamma` is called `a`, and the scale parameter (as in all the continuous distributions in SciPy) is called simply `scale`.

So there is nothing incorrect here.

Here's a simple script that compares theoretical and sampled results for `scipy.stats.gamma` and the `gamma` function from `numpy.random`. (I'm using the legacy version of the function.)

```python
import numpy as np
from scipy.stats import gamma

# Shape parameter ('k' in numpy, 'a' in scipy):
alpha = 7.0

# Scale ('theta' in numpy, 'scale' in scipy):
theta = 400.0

mean = alpha * theta
var = alpha * theta**2 
print(f'mean and var from formulas:          {mean:.3f}, {var:.3f}')
print(f'mean and var from scipy.stats.gamma: '
      f'{gamma.mean(a=alpha, scale=theta):.3f}, '
      f'{gamma.var(a=alpha, scale=theta):.3f}')

print()
print("simulations:")
print("-"*50)
print('                       Mean       50%       99.5%')
print("-"*50)
print(f'Expected (scipy): {gamma.mean(a=alpha, scale=theta):10.3f} '
      f'{gamma.ppf(0.5, a=alpha, scale=theta):10.3f} '
      f'{gamma.ppf(0.995, a=alpha, scale=theta):10.3f}')
print("-"*50)
for k in range(5):
    obs = np.random.gamma(shape=alpha, scale=theta, size=1000000)
    print(f'Sample (numpy):   {np.mean(obs):10.3f} '
          f'{np.percentile(obs, 50):10.3f} {np.percentile(obs, 99.5):10.3f}')
```
Output:

```
mean and var from formulas:          2800.000, 1120000.000
mean and var from scipy.stats.gamma: 2800.000, 1120000.000

simulations:
--------------------------------------------------
                       Mean       50%       99.5%
--------------------------------------------------
Expected (scipy):   2800.000   2667.855   6263.870
--------------------------------------------------
Sample (numpy):     2799.673   2667.168   6260.861
Sample (numpy):     2800.640   2669.183   6253.323
Sample (numpy):     2800.159   2668.041   6252.093
Sample (numpy):     2799.269   2667.252   6258.423
Sample (numpy):     2799.882   2667.112   6280.516
```
