### ISSUE TITLE
Trying to use Numpy package as zip instead of installing NUMPy

### ISSUE THREAD

**Issue by esansraja** [numpy/numpy#13135]
### Reproducing code example:

Hi All,
 We had to use 'numpy' in one of my program  and run the script on cloud server (IBM), where we can't install stuff.
IBM is supporting only the standard python libraries and for  non standard packages, advised  us to zip the required packages as zip file and copy it along with the script in the server location. This technique has worked for other packages but somehow is failing for numpy (couldn’t able to recognize 'numpy' through zip file) . so i installed numpy and copy the cnumpy folder from site-packages and zipped and kept it in the program folder  where i am executing my script. 

**this is my code to import numpy**

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)),"numpy.zip"))
import numpy

### Error message:

(tutorial-env) rajm-mbp:python rajm$ python3 ExcelSplit.py
Traceback (most recent call last):
  File "/Users/rajm/Python/numpy.zip/numpy/core/__init__.py", line 40, in <module>
  File "/Users/rajm/Python/numpy.zip/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/rajm/Python/numpy.zip/numpy/core/overrides.py", line 6, in <module>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ExcelSplit.py", line 17, in <module>
    import numpy
  File "/Users/rajm/Python/numpy.zip/numpy/__init__.py", line 142, in <module>
  File "/Users/rajm/Python/numpy.zip/numpy/core/__init__.py", line 71, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /Users/rajm/Python/tutorial-env/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

### Numpy/Python version information:

1.16.2 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)]

**Comment by rgommers** [comment]
> so i installed numpy and copy the cnumpy folder from site-packages and zipped and kept it in the program folder where i am executing my script

that could work, if you have a working install on the same type of OS/hardware. Since you are missing a key binary, you either didn't have it working on the system you copied from, or didn't make a complete copy.

**Comment by mattip** [comment]
You also need to copy the support `*.so` files from `site-packages/numpy/.libs` to somewhere outside the `zip` since the runtime loader does not support loading an `*.so` from a zip file. Perhaps ask whoever gave you the advice to use this technique what they recommend for binary `*.so`s needed by python modules

**Comment by rgommers** [comment]
> ou also need to copy the support *.so files from site-packages/numpy/.libs to somewhere outside the zip since the runtime loader does not support loading an *.so from a zip file. 

Ah, I missed the part about actually *running* from a zipfile. Rather than special-casing `*.so`, just unpack the whole zip file. I thought the zipping was just to get numpy onto the machine. Always just unzipping everything is more robust.

> Perhaps ask whoever gave you the advice to use this technique what they recommend for binary *.sos needed by python modules

Better to just tell them that the advice is wrong. You don't want users to have to even check whether a package has `.so`'s.
