### ISSUE TITLE
Problem with import numpy

### ISSUE THREAD

**Issue by hacousin** [numpy/numpy#13139]
### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

### Numpy/Python version information:

I tried to run" import numpy as np" but it shows me an error message. I uninstalled and reinstalled 2 times but the problem is still present. I installed anaconda via the site : "https://www.anaconda.com/distribution/" and I launched the launcher for the installed one.The message is :

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\harry\Anaconda3\pythonw.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by charris** [comment]
Duplicate, see #13017, #12977.

**Comment by hacousin** [comment]
Ok ty
