### ISSUE TITLE
isinistance(np.float32, float) is false

### ISSUE THREAD

**Issue by gasparka** [numpy/numpy#13133]
I am trying to test if an array contains floats, but ran info following behavior:
```python
import numpy as np
x = np.empty(1, dtype=float)
assert isinstance(x[0], float)  # OK

x = np.empty(1, dtype=np.float64)
assert isinstance(x[0], float) # OK

x = np.empty(1, dtype=np.float32)
assert isinstance(x[0], float)  # FAIL
```

Is this expected?
Workaround is to use ```np.floating``` instead of ```float```, but IMHO this is not intuitive.

### Numpy/Python version information:

1.16.2 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]

**Comment by eric-wieser** [comment]
I'd actually like to make the first two cases fail too...

**Comment by gasparka** [comment]
+1 for consistency.
 I had this snipped in a production code - worked fine with ```float64``` and then surprisingly failed with ```float32```.

Is there a better way to test for data-type? My application is quite common:
``` python
if array_is_floats:
   # do something
elif array_is_complex:
   # do something else
```

**Comment by mattip** [comment]
```
if isinstance(a.flat[0], np.floating):
   # float
elif isinstance(a.flat[0], np.complexfloating):
    # complex
```

**Comment by eric-wieser** [comment]
`issubclass(a.dtype.type, np.floating)` is probably a better call

**Comment by gasparka** [comment]
Thanks.
Ran a quick grep over Numy/Scipy codebase to see if 'my-style' was widely used - only found a few harmless usages.

Issue solved.

**Comment by TheStoneMX** [comment]
this worked for me 

x = y.asnumpy() 
assert isinstance(x, np.float32)
