### ISSUE TITLE
`not_equal` cannot compare string and specify out

### ISSUE THREAD

**Issue by ZisIsNotZis** [numpy/numpy#13151]
The function `np.not_equal` will raise an error if comparing string arrays and specifying `out=` with bool array.

Usually directly doing `a != b` would be fine, but it would be nice if can specify out because sometimes people want to output to a slice of some bigger bool array, while doing `mask[x:y] = a != b` evolves a explicit copying.

### Reproducing code example:

    import numpy as np
    mask = np.empty(2, '?')
    np.not_equal(['ab','cd'], ['ef','cd'], mask)

### Error message:

    TypeError                                 Traceback (most recent call last)
    <ipython-input-146-978e55c846c5> in <module>
          1 import numpy as np
          2 mask = np.empty(2, '?')
    ----> 3 np.not_equal(['ab','cd'], ['ef','cd'], mask)

    TypeError: ufunc 'not_equal' did not contain a loop with signature matching types dtype('<U2') dtype('<U2') dtype('bool')

### Numpy/Python version information:

1.16.2 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]

**Comment by DorotheaMueller** [comment]
The error message is not related to the output array, but to the comparison itself.
The comparison does not work for characters, but it works for certain dtypes like booleans, integers, objects (although not being explicitly mentioned in the documentation of [numpy.not_equal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.not_equal.html)).

If the comparison is made with characters, it will fail (irrespective of the output array):

```python
x = np.array(['ab', 'cd'])
y = np.array(['ef', 'cd']) 
np.not_equal(x, y)
```
```
TypeError: ufunc 'not_equal' did not contain a loop with signature matching types dtype [...]
```
But casting the characters as dtype object, it will work:

```python
x = np.array(['ab', 'cd'], dtype = object)
y = np.array(['ef', 'cd'], dtype = object) 
np.not_equal(x, y)
```
It will also work fine if an output array is used:

```python
mask = np.empty(2, '?')
x = np.array(['ab', 'cd'], dtype = object)
y = np.array(['ef', 'cd'], dtype = object) 
np.not_equal(x, y,  mask)
```
```
[True False]
```

**Comment by mhvk** [comment]
@DorotheaMueller is correct: the `ufunc` does not support strings (or any variable length types like structured arrays) - they are treated specially for the `!=` operator (i.e., in `np.ndarray.__ne__`)

**Comment by ZisIsNotZis** [comment]
Oh, I never tested that. Sorry for that. So basically there is no way to output to a specific location for string comparison?

**Comment by mhvk** [comment]
@ZisIsNotZis - no worries, this is a tricky one. And, no, apart from recasting to `object` (which will use far more memory than you'd safe with the output array), there is currently no way to specify an output location.

We do hope to eventually remove this limitation, but it will be a while...

For now, I'll close this. Don't hesitate to report if you find other problems - sometimes we can solve them!
