### ISSUE TITLE
Bus error: 10 when multiplying two matrices

### ISSUE THREAD

**Issue by PrimozGodec** [numpy/numpy#13155]
When performing the multiplication of two matrices the program quits with the error `Bus error: 10`. No other error messages are presented. Can large matrices size be the cause for an issue?

### Reproducing code example:

The error occurs when performing the multiplication of two matrices.
    out = w_col @ x_col

`w_col` is the matrix of shape `(64, 27)` and with type `float32`.
`x_col` is the matrix of shape `(27, 12996)` and with type `float32`.

Tried to reproduce it in the single script but not successfully. It seems that error occurs in the sequence of many Numpy operations, but it always crashes while multiplying.

### Error message:

Bus error: 10

### Numpy/Python version information:

Numpy 10.15.4, MacOS 10.14.3 
On same OS issue do not occur with Numpy 10.16.*

Also, tested on another MacOS machine where the same issue happens with Numpy 10.16.2

**Comment by charris** [comment]
How did you install numpy? What hardware?

**Comment by PrimozGodec** [comment]
Numpy is installed with `pip` in a virtual environment. 

Hardware: 
MacBook Pro (13-inch, 201), 3,1 GHz Intel Core i5, RAM: 8 GB 2133 MHz LPDDR3

**Comment by matthew-brett** [comment]
I get no crash from numpy 1.15.4 macoS 10.14.3, Homebrew Python 3.7 and

[ins] In [2]: import numpy as np
[ins] In [3]: w_col = np.ones((64, 27), dtype=np.float32)
[ins] In [4]: x_col = np.ones((27, 12996), dtype=np.float32)
[ins] In [5]: out = w_col @ x_col

Does this crash for you?

**Comment by seberg** [comment]
It is a bit silly stuff in there as well, but I think it should give some idea also on mac, @PrimozGodec can you run this code: https://gist.github.com/seberg/ce4563f3cb00e33997e4f80675b80953

**Comment by PrimozGodec** [comment]
@matthew-brett It does not crash? It seems that there must be some weird combination of Numpy commands that cause a program to crash. I am still trying to prepare a minimal example. In the worst case, I will prepare steps to reproduce the issue with the full application.

**Comment by PrimozGodec** [comment]
@seberg This is the output:

Probing Multiarray
------------------
OpenBLAS:
    num threads: 2
    version info: DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64

Probing Linalg
--------------
OpenBLAS:
    num threads: 2
    version info: DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64

**Comment by seberg** [comment]
@PrimozGodec not sure if this is plausible here, but we sometimes had funny interplay with other packages (such as gui packages). So if you application imports such things before numpy, maybe try importing numpy first or import all the same modules when trying to reproduce it with a simple matrix multiplication. Another thing could be threading maybe?

**Comment by PrimozGodec** [comment]
Hmm. There is PyQt imported in several places in the app. Possibly PqQt can be a reason.

**Comment by PrimozGodec** [comment]
The steps to reproduce the issue:

1. Clone this repository git@github.com:biolab/orange3-imageanalytics.git
2. `cd orange3-imageanalytics`
3. Check out this PR: https://github.com/biolab/orange3-imageanalytics/pull/124
4. Install the package: `pip install -e .`
5. (Issue appear with the latest Numpy version too, but in my case it is more likely with older version so:) `pip uninstall numpy`
`pip install numpy==1.15.*`
6. Run this code:

```
import logging

from AnyQt.QtWidgets import QApplication
from AnyQt.QtTest import QSignalSpy

from Orange.data import Table
from orangecontrib.imageanalytics.widgets.owimageembedding import OWImageEmbedding

def main(argv=None):
    logging.basicConfig(level=logging.DEBUG)
    app = QApplication(list(argv) if argv else [])
    argv = app.arguments()
    if len(argv) > 1:
        filename = argv[1]
    else:
        filename = "zoo-with-images"
    data = Table(filename)
    widget = OWImageEmbedding()
    widget.show()

    assert QSignalSpy(widget.blockingStateChanged).wait()
    widget.set_data(data)
    widget.handleNewSignals()
    app.exec()
    widget.set_data(None)
    widget.handleNewSignals()
    widget.saveSettings()
    widget.onDeleteWidget()
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
```

**Comment by seberg** [comment]
There were such issues with PyQt and some older anaconda versions, but I am not sure it should happen with pip installed numpy (the wheels). If you think it might be related to that, can you run Matthews example in a script that imports all the PyQt stuff before numpy. Just because such a long reproducer is annoying.

**Comment by PrimozGodec** [comment]
As @seberg pointed out, there is a problem with threading (QThread by Qt). The task, where the error appears, runs in a thread such that app does not freeze while computing. Threading cannot be avoided.

**Comment by matthew-brett** [comment]
We used to have a threading conflict between OpenBLAS and Qt : https://github.com/numpy/numpy/issues/11551 .  I believe we fixed this with our later builds, using later OpenBLAS.  Have you tried latest Numpy?

**Comment by PrimozGodec** [comment]
@matthew-brett it seems that those two issues are connected and I can confirm that the issue is solved. On my computer, the latest version works fine. On the other computer, there were some issues with reinstalling packages.
Thanks, everybody for your help. I am closing this issue.
