### ISSUE TITLE
(comparatively) long dispatch times with __array_function__ or __array_ufunc__

### ISSUE THREAD

**Issue by brandondube** [numpy/numpy#13150]
Numpy functions called on cupy arrays inflate runtime by (about) a factor of four.  I have a notebook benchmarking this on a windows 10 machine here,

https://gist.github.com/brandondube/eff40d7b372f596ebe629f4fa33da31c

The system has an i7-8700K and GTX 1080ti with 32GB of ram and 11GB of VRAM (though I think the latter two are irrelevant here).  The benchmark is very simple, comparing exp and sin called through numpy and through cupy.  The dtype is f64, which has performance degraded ~2x vs f32 in windows for numpy, but I think that is also unrelated here(?)

If I increase the array sizes so that numpy (cpu) enters the ms domain while gpu remains in us domain, it becomes clear that the timing is not because the array is copied from device to host, computed on CPU, and copied back to device.

It would be great to see the overhead of this reduced -- performance sensitive code really can't tolerate this kind of slowdown.  I do understand that the mechanisms behind this are in beta/still evolving.  Thank you!

**Comment by eric-wieser** [comment]
Only `__array_ufunc__` is relevant here

**Comment by mattip** [comment]
You want to use CuPy 6.0 not 5.3, as 6.0 supports the post-NumPy-1.16 `__array_function__` protocol. It would be interesting to see a comparison.

With that, I tried to organize the data you gave a little differently, where `np` is NumPy, `cp` is CuPy, and `anp` is `autograd.numpy`

function\array | np | cp 
------|--------|-------
`np.exp` | 814 ns ± 15.7 ns | 89.1 µs ± 1.33 µs
`cp.exp` | | 12.9 µs ± 161 ns
`anp.exp`| | 91.7 µs ± 1.28 µs
`np.sin` | | 118 µs ± 44.5 µs
`cp.sin` | | 12.8 µs ± 209 ns

How does the data support your conclusion in the first sentence? Where does the "factor of 4" come from? Something does seem to be slowing things down, but what exactly? Can you run [gprof or valgrind](http://gernotklingler.com/blog/gprof-valgrind-gperftools-evaluation-tools-application-level-cpu-profiling-linux/) to figure out what is going on (but take the results with a [grain of salt](https://yosefk.com/blog/how-profilers-lie-the-cases-of-gprof-and-kcachegrind.html).

**Comment by brandondube** [comment]
The factor of four is a factor of eight -- looks like I flubbed some basic division late at night.  I didn't realize __array_ufunc__ and __array_function__ were coming in cupy 6.0, which has been in various stages of prerelease for quite some time now.  Tomorrow night I'll see if I can get the latest 6.0 beta compiled and if this is improved -- my laptop has an AMD card, so I can't play with cupy on it.

**Comment by brandondube** [comment]
Cupy 6 makes np and cp have equal execution time -- the fix is already implemented!

https://gist.github.com/brandondube/880cf989c2dd33f4b5a2f88e89b6c31f
