### ISSUE TITLE
ndarray.flat causes reference count error with invalid inputs

### ISSUE THREAD

**Issue by adeak** [numpy/numpy#13165]
Passing invalid inputs to `ndarray.flat` will raise an error, but after the interpreter finishes there's a reference count error (python attempts to deallocate the integer 7):
```
>>> import numpy as np
>>> np.arange(3).flat[None]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: unsupported iterator index
>>> 
*** Reference count error detected: 
an attempt was made to deallocate 7 (l) ***
```
The issue is there in master.

~This is probably related to (or a duplicate of) https://github.com/numpy/numpy/issues/7982. The reason why I'm not sure this is a duplicate is because the other issue tries assigning to invalid memory, whereas here we're only attempting a read, and that could fail before breaking anything.~ Update: Since this is a different part of the code (subscription rather than subscripted assignment) and the input type triggering the error is different, I don't think it's related to that issue after all.

**Comment by mhvk** [comment]
Confirmed.  Though no time right now to look into it. On the relation to #7982: Would be good to see if the fix given in https://github.com/numpy/numpy/issues/7982#issuecomment-439114876 solves it - I am doubtful...

**Comment by adeak** [comment]
Thanks, @mhvk. I tried using the patch you linked but it didn't change anything in the above behaviour.

**Comment by mhvk** [comment]
@adeak - thanks for checking. So it is an independent bug, then.  I fear `.flat` is not the most looked-after part of the code...

**Comment by adeak** [comment]
OK, so the linked patch won't work for two reasons: it handles tuple input, and it's for subscripted _assignment_, whereas I have subscription ([`iter_subscript`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/iterators.c#L532)). I _think_ what's going on with `None` or string-typed input to `flat` (which is how I first found the issue), is that after a series of skipped `if` branches we reach [here](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/iterators.c#L629-L630):
```
    /* convert to INTP array if Integer array scalar or List */
    indtype = PyArray_DescrFromType(NPY_INTP);
```
There is no failure mode before this point for `None` or string input. So, suspiciously, `NPY_INTP == 7` (cf. the reference count error message referring to 7).
Then again after a few skipped `if` branches we end up [here](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/iterators.c#L669-L671):
```
    else {
        Py_DECREF(indtype);
    }
```
My suspicion is that this `DECREF` call messes with the reference count of `NPY_INTP`. Of course the 7 might be a coincidence. Anyway, I suspect there should be an early fail mode for "this input was completely unexpected", or the above `indtype` assignment must be put inside an `if` block of its own. I'm not familiar with the internals to try and fix this on my own.

**Comment by seberg** [comment]
@adeak if you are happy to iterate fix it up a bit with reviewer help, then I think we would love if you open a PR in any case. Also adding a test case would be good, and I think you are very much on the right track, so I suspect you will find the right fix :).

**Comment by adeak** [comment]
@seberg thanks, I'd love that :) It will take a while for me to wrap my head around the details of the C API, but if some hand-holding in review is not an issue, I'll have at it.
