### ISSUE TITLE
Save big matrix blob in Java and load as numpy in Python

### ISSUE THREAD

**Issue by hlbkin** [numpy/numpy#13178]
Hi team!

Do you how this could be achieved: 

1) Saving big blob via Java (big feature matrix for 1 day/hour at a time) to some database

2) Load as numpy array in Python

**Comment by seberg** [comment]
Numpy provides easy ways to read simple binary data or many other formats (e.g. through scipy). It is certainly not hard to do, but I am sorry, this is simply not the right place to ask such questions.
