### ISSUE TITLE
np.any() gives inconsistent result for 'is None'

### ISSUE THREAD

**Issue by vincenzooo** [numpy/numpy#13183]
I would expect [None] and [None,...] both to return True, as in code below, or at least return same result. 
Also if an element in the array is a string, comparison fails with an error.

### Reproducing code example:

```python
import numpy as np
tv=[None,[None],[None,2],'test']  #test values

for v in tv: print (np.any(v) is None) 
print('expected behavior:')
for v in tv: print (v is None if np.ndim(v)==0 else np.any([vv is None for vv in v]))
```

### Numpy/Python version information:

1.15.4 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
I think you're confused by meaning of a bunch of things here.

`np.any(x) is None` does not mean "any of the items in x are None". It means "check if all the values are falsy, and the last value in x is `None`.

Just like `np.any(x) == 1` is very different from `np.any(x == 1)`.

It's also worth realizing that you're constructing an object array containing lists:
```
>>> tv = np.array([None,[None],[None,2],'test']); tv
array([None, list([None]), list([None, 2]), 'test'], dtype=object)
```

**Comment by vincenzooo** [comment]
Thanks for the quick reply
and sorry, it was my intention to use any in the correct way, but I made a typo in my last editing, sorry, I appreciate you taking the time to explain.
Still, it seems inconsistent to me, let me try to point out what I mean:

```python
import numpy as np
In [21]: np.any(np.array([1]) == 1)
Out[21]: True

In [22]: np.any(np.array([None]) is None)
Out[22]: False
```

The intent of the list was to test each element separately, because I was looking for a function "True if at least one element of a variable (iterable or not) is None", I didn't manage with builtins, and was trying to use automatic conversion, but I see now why that is wrong. 
Maybe this is intended behavior, but if at least one element of the array is None, I would expect it to give True, consistently with any other comparison.

**Comment by eric-wieser** [comment]
Numpy is unable to overload the `is` operator, so `arr is None` has no special meaning

**Comment by Mohamed-S-Helal** [comment]
> Thanks for the quick reply
> it was my intention to use any in the correct way, but I made a typo in my last editing, sorry, I appreciate you taking the time to explain.
> Still, it seems inconsistent to me, let me try to point out what I mean:
> 
> ```python
> import numpy as np
> In [21]: np.any(np.array([1]) == 1)
> Out[21]: True
> 
> In [22]: np.any(np.array([None]) is None)
> Out[22]: False
> ```
> 
> The intent of the list was to test each element separately, because I was looking for a function "True if at least one element of a variable (iterable or not) is None", I didn't manage with builtins, and was trying to use automatic conversion, but I see now why that is wrong.
> Maybe this is intended behavior, but if at least one element of the array is None, I would expect it to give True, consistently with any other comparison.

Have you figured it out yet? I noticed the same issue
