### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by rutujar** [numpy/numpy#13180]
after installing numpy in ubuntu 16.04 i am not able to access it. 
ImportError: cannot import name 'multiarray'

**Comment by charris** [comment]
How did you install numpy.

**Comment by rutujar** [comment]
sudo apt install python3-numpy

**Comment by mattip** [comment]
what hardware are you using?

**Comment by rutujar** [comment]
laptop specification or what?

**Comment by mattip** [comment]
`uname -m`, which should give something like `x86_64`

**Comment by mattip** [comment]
and what is the complete traceback of the error? Maybe there is more than one numpy on the machine

**Comment by rutujar** [comment]
import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

**Comment by vneogi199** [comment]
Uninstall numpy using:
`sudo apt remove python3-numpy`

Then install it using pip:
`pip3 install numpy`

**Comment by mattip** [comment]
@vneogi199 that will result in a different version of numpy, perhaps @rutujar wants to use the os-provided version.

Please show the output of all four of these commands
1. `ls /usr/lib/python3/dist-packages/numpy/core/*.so`
2. `uname -m`
3.  `apt list python3-numpy`
4. `ldd /usr/lib/python3/dist-packages/numpy/core/multiarray*.so`

**Comment by rutujar** [comment]
@mattip
1. ls /usr/lib/python3/dist-packages/numpy/core/*.so

/usr/lib/python3/dist-packages/numpy/core/_dummy.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/numpy/core/multiarray_tests.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/numpy/core/operand_flag_tests.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/numpy/core/struct_ufunc_test.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/numpy/core/test_rational.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/numpy/core/umath.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/numpy/core/umath_tests.cpython-35m-x86_64-linux-gnu.so

2. uname -m
x86_64

3.apt list python3-numpy
Listing... Done
python3-numpy/xenial,now 1:1.11.0-1ubuntu1 amd64 [installed]

4.ldd /usr/lib/python3/dist-packages/numpy/core/multiarray*.so
/usr/lib/python3/dist-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so:
	linux-vdso.so.1 =>  (0x00007fff681ce000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fbec19a0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbec1697000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbec147a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbec10b0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbec1f6d000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007fbec0b12000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fbec07e7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbec05d1000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fbec0392000)
/usr/lib/python3/dist-packages/numpy/core/multiarray_tests.cpython-35m-x86_64-linux-gnu.so:
	linux-vdso.so.1 =>  (0x00007ffe0170d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd96a65b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd96a291000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd96aa84000)

**Comment by mattip** [comment]
Everything seems OK, that is exactly what my 16.04 gives me. Are you using the system python3 (`usr/bin/python3`)?
What does 
`python3 -c "import sys; print(sys.version); import numpy; print(numpy.__version__)"`
show? Mine reports
```
3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
1.11.0
```

**Comment by rutujar** [comment]
i think somewhere the permissions is denied.it is happening for every package in python 3.
when i try installing it again.
$ pip3 install numpy
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/numpy'
Consider using the `--user` option or check the permissions.

**Comment by vneogi199** [comment]
Since you are writing to the system to the system path, you have to use:
`sudo pip3 install numpy`
Or you can write to user path using:
`pip3 install numpy --user`

**Comment by mattip** [comment]
you reported that you did `sudo apt install python3-numpy` before. You should either use `sudo apt install python3-*` or `pip install numpy`, but not mix them.

**Comment by rutujar** [comment]
i uninstalled and installed it again.
error resolved for numpy.
it worked for pip3 install numpy --user
 thanks @vneogi199, @mattip
