### ISSUE TITLE
[Feature request] Add nanptp function

### ISSUE THREAD

**Issue by Gabriel-p** [numpy/numpy#13198]
There is a [ptp](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ptp.html) function but it will fail when there are `nan` values in the array.

**Comment by yliapis** [comment]
Hi Gabriel, I will take a go at this over the weekend

**Comment by rgommers** [comment]
Having this linked somewhere would be nice, but I think it's too niche to include in numpy. we only want `nan*` versions of the most commonly used functions, and `ptp` is not one of those.

**Comment by yliapis** [comment]
From looking at the existing `nan*` functions, it looks like most of the base functions have nan analogs. I agree that ptp is not the most commonly used function, but I use it quite a bit on signal processing problems, and it does feel like it is missing given the other functions in `nanfunctions.py`. I've finished implementing a basic version, I'll get it up on my account once it is cleaned up and tested.

**Comment by yliapis** [comment]
If we decide to move forward with this one, I just opened a PR with the function implementation and corresponding tests.
#13220

**Comment by rgommers** [comment]
We discussed this in the triage meeting. Most people were happy with rejecting this feature request. @charris abstained, @seberg said he could imagine a separate namespace.

The main rationale here is that we don't want more nan-functions in general; we have the most commonly used ones, and filling up the main namespace with more nan-functions isn't justified (there's a significant cost for adding anything to the namespace at this point.

In particular for this one: `ptp` is already niche, and was arguably a mistake to add to numpy. So `nanptp` isn't desired.

A separate package like `bottleneck` makes more sense for more nan-functions.

Thanks for suggesting this @Gabriel-p, and for the PR @yliapis

**Comment by Gabriel-p** [comment]
Thank you for the detailed explanation @rgommers
