### ISSUE TITLE
`numpy.genfromtxt` doesn't properly close input in the event of an error

### ISSUE THREAD

**Issue by jdswinbank** [numpy/numpy#13200]
If an error is thrown when processing input, `np.genfromtxt` doesn't cleanly close the file it has opened.

For example, in the below, a `UnicodeDecodeError` is thrown while attempting to interpret `£` as ASCII. That error is expected, but it results in a `ResourceWarning` about the file not being properly closed.

Replace ``ascii`` with ``utf-8``, and the `ResourceWarning` vanishes.

### Reproducing code example:

```python
import numpy as np
import warnings

warnings.simplefilter("always")

with open("test.csv", "w") as f:
    f.write("£")

try:
    np.genfromtxt("test.csv", encoding="ascii")
except UnicodeDecodeError:
    pass
```

### Error message:

```
$ python myproblem.py 
myproblem.py:12: ResourceWarning: unclosed file <_io.TextIOWrapper name='test.csv' mode='rt' encoding='ascii'>
  pass
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

### Numpy/Python version information:

```
1.16.2 3.7.2 (default, Dec 30 2018, 08:55:50) 
[Clang 10.0.0 (clang-1000.11.45.5)]
```

**Comment by eric-wieser** [comment]
Sounds like a with statement is needed
