### ISSUE TITLE
np.concatenate cast int to str when concatenating arrays of pairs

### ISSUE THREAD

**Issue by josegarciaclm95** [numpy/numpy#13204]
When using `np.concatenate` to concatenate arrays containing pairs `(integer, string)`, the `integer` value is cast to `string`.

### Reproducing code example:
```python
import numpy as np
#[(int, str)]
example = [
    [(625, 'eeg'), (625, 'bci'), (625, 'gsr')], 
    [(511, 'revision'), (511, 'theory'), (511, 'state-of-art')]
]
np.concatenate(example)
#[('625', 'eeg'), ('625', 'bci')...., ('511', 'state-of-art')]
```

### Numpy/Python version information:

1.15.4 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

**Comment by seberg** [comment]
note that if you wish to have a structured dtype, you have to give the dtype manually. Numpy will only automatically coerce to a single dtype:
```
l = [(625, 'eeg'), (625, 'bci'), (625, 'gsr')]
arr = np.array(l)
print(l, l.dtype)
```

Output:
```
[['625' 'eeg']
 ['625' 'bci']
 ['625' 'gsr']] <U21
```

**Comment by josegarciaclm95** [comment]
Hi @seberg. I understand that I have to set something like this
`dt = np.dtype([('cited_by', np.int), ('kw', np.unicode_)])`
to my array, since I want to have a pair with an int and a string value, but I cannot add it to the `concatenate` function.
How should I use it?

Thanks in advance.

**Comment by seberg** [comment]
The concatenate function is to concatenate arrays, if you provide lists, numpy will have to convert them to arrays first. So it implicitely calls `np.asarray` on them. So you will either need to:

 * coerce to array yourself
 * Simply work with list until you do one final `np.array` call.

anyway, it is not an issue with the concetenate function. If anything we could force explicitly using `np.asarray` with `dtype` more, but that is being talked about already (at least for object arrays, which are a bit different though).
