### ISSUE TITLE
Int to float type conversion of numpy.array when result is in uint64 range

### ISSUE THREAD

**Issue by cod3monk** [numpy/numpy#13212]
When a `numpy.array` of integers (i.e., `int64`) is operated on (e.g., with an addition or multiplication) and the resulting integer is beyond the range of `int64` but still within `uint64`, the resulting type becomes `float64`. When the range of `uint64` is exceeded it becomes–as expected–a python integer object.

I would expect the `float64` results to actually be `uint64`.

### Reproducing code example:

```python
>>> import numpy as np
>>> np.array([2**62])  # as expected -> int64
array([4611686018427387904])
>>> np.array([2**63])  # as expected -> uint64
array([9223372036854775808], dtype=uint64)
>>> np.array([2**64])  # as expected -> object
array([18446744073709551616], dtype=object)
>>> np.array([0]) + (2**63-1)  # as expected -> int64
array([9223372036854775807], dtype=int64)
>>> np.array([0]) + 2**63  # NOT as expected -> float64
array([9.22337204e+18])
>>> np.array([0]) + (2**64-1)  # NOT as expected -> float64
array([1.84467441e+19])
>>> np.array([0]) + 2**64  # as expected -> object
array([18446744073709551616], dtype=object)
```

### Numpy/Python version information:
numpy: 1.16.2
python: 3.5.6 (default, Oct  3 2018, 19:57:36) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]

**Comment by rgommers** [comment]
```
In [6]: array(2**63)
Out[6]: array(9223372036854775808, dtype=uint64)
In [7]: array(2**64)
Out[7]: array(18446744073709551616, dtype=object)
```
Notice the difference between those two.  Basically first 2**64 is converted to a numpy array and *then* the casting occurs:
```
int64 + uint64 -> float64
int64 + object -> object
```
So this is simply a consequence of the casting rules:
```
In [2]: (np.array([1], dtype=np.int64) + np.array([2], dtype=np.uint64)).dtype
Out[2]: dtype('float64')

In [3]: (np.array([1], dtype=np.int64) + np.array([2], dtype=np.object)).dtype
Out[3]: dtype('O')
```
