### ISSUE TITLE
Documentation mistake numpy.floor_divide

### ISSUE THREAD

**Issue by PDiracDelta** [numpy/numpy#13215]
The [floor_divide docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.floor_divide.html) claim that 

> Return the largest integer smaller or equal to the division of the inputs. It is equivalent to the Python // operator and pairs with the Python % (remainder), function so that b = a % b + b * (a // b) up to roundoff.

However, the mathematical expression is equal to a, not equal to b.

### Reproducing code example:

```
a=9; b=2; a % b + b * (a // b)  == a
True
```

### Numpy/Python version information:

Numpy docs V1.16.1

**Comment by mbengtanyi** [comment]
Hello, I'm new to open source and would like to work on this if no one is.

**Comment by seberg** [comment]
Please just go ahead, in case you are thinking about Outreachy. Especially also in that case, please look into building the documentation locally as well.

For some general notes about our workflow have a short look at: http://www.numpy.org/devdocs/dev/gitwash/development_workflow.html.

For instructions on building the documentation, see:
http://www.numpy.org/devdocs/docs/index.html?highlight=documentation

(One quick way to get into a shell to run `make html` which uses the development numpy version may be to use `python runtests.py --shell`)

**Comment by SahanaJavgal** [comment]
Hi Im Interested in solving the issue

**Comment by mbengtanyi** [comment]
On it. Thanks @seberg

**Comment by RuchikaChugh** [comment]
hey! I am an Outreachy Applicant. I am interested in solving this issue.

**Comment by mattip** [comment]
@RuchikaChugh, @SahanaJavgal please choose another issue.

**Comment by yesass** [comment]
@mattip Hi! If nobody opened a PR, can I work on this issue?

**Comment by mattip** [comment]
It seems the others gave up, so go ahead. Please xref the issue by adding `#13215` in the comments after you create the pull request, i.e. `Fixes #13215`

**Comment by mbengtanyi** [comment]
I am working on it. Having a bit of problems building sphinx though.

**Comment by aditipansari** [comment]
Hello, I am interested in solving this issue. I am an Outreachy applicant.

**Comment by mattip** [comment]
@aditipansari please choose another issue.

**Comment by mattip** [comment]
Fixed in #13242
