### ISSUE TITLE
Indicate attempted allocation size when constructing an array gives a MemoryError

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13225]
I've seen multiple questions now of the form "why does this give a MemoryError" when the reason is the user ended up allocating a bigger array than expected.

It would be helpful to include the shape and dtype in the error message.

**Comment by bmakos** [comment]
I will give this a try sometimes this week. If someone else is already working on it let me know.

**Comment by bmakos** [comment]
For some reason this does not reproduce as reported on my setup (OSx, python 3.7.3): 

```
>>> import numpy as np
>>> t = np.zeros((51,765,285),dtype=np.float64)
>>> z = np.zeros((51,765,285),dtype=np.float64)
>>> indices = np.apply_along_axis(lambda a: a.searchsorted(10), axis=0, arr=t)
indices.shape
np.take(z, indices, axis=0)
z[indices,:,:]
>>> indices.shape
(765, 285)
>>> np.take(z, indices, axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/BMA/numpy/numpy/core/overrides.py", line 150, in public_api
    implementation, public_api, relevant_args, args, kwargs)
  File "/Users/BMA/numpy/numpy/core/fromnumeric.py", line 192, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/Users/BMA/numpy/numpy/core/fromnumeric.py", line 60, in _wrapfunc
    return bound(*args, **kwds)
IndexError: index 51 is out of bounds for size 51
```

On the other hand, a fresh install of numpy from git on Elementary OS reproduced it (both setups run 1.17.0). 
I'll keep looking.

**Comment by eric-wieser** [comment]
@bmakos: You could try testing with `np.ones((2**40,), np.uint8)`, which should be easily greater than your available ram

**Comment by bmakos** [comment]
<img width="1050" alt="numpy extensive memory use" src="https://user-images.githubusercontent.com/5707813/55749327-f10bcd00-5a40-11e9-927c-1e3b21739404.png">

Ok, so it seems I will not be able to reproduce this on my machine, the process gets automatically killed at around 120gb by the os. I'll just use a vm with Elemenary for this issue. Sry for the confusion.

**Comment by bmakos** [comment]
I am a bit insecure about the solution I took. Is it acceptable to issue just this amount of information for this error?

**Comment by eric-wieser** [comment]
These lines are where the change would go:

https://github.com/numpy/numpy/blob/f4a24b1f4779d1b9966efe2ad79cba21241ce500/numpy/core/src/multiarray/ctors.c#L1054-L1080

**Comment by bmakos** [comment]
Yes, I was already working on adding it. I debugged it with gdb last night and I got to the same conclusion: 

```
Breakpoint 1, 0x0000555555602337 in PyErr_NoMemory ()
(gdb) up
#1  0x00007ffff5b3b131 in PyArray_NewFromDescr_int (subtype=0x7ffff60b9d00 <PyArray_Type>,
    descr=0x7ffff60ba660 <DOUBLE_Descr>, nd=4, dims=0x7fffffffcb30, strides=0x0, data=0x0, flags=0,
    obj=0x7ffff6163ad0, base=0x0, zeroed=0, allow_emptystring=0)
    at numpy/core/src/multiarray/ctors.c:1075
1075                PyErr_NoMemory();
(gdb)
```
I'll use `PyErr_SetObject` or `PyErr_SetString`, I just have to figure out how to build the message. 

@eric-wieser Thank you for confirming the location, it's good to know I am on track.

**Comment by eric-wieser** [comment]
One trick you could use is to dispatch the message formatting to python. One approach would be to add a helper function to `_internal.py`, the other would be to create a MemoryError subclass in _exceptions.py

**Comment by bmakos** [comment]
@eric-wieser In the end I went with not using python to format the message because I struggled with passing the dimensions array to python and all the data I needed was available in `fa`. Also, found some handy helper functions (like `PyUString_FromFormat`). 
If you still wish to go the route you suggested I can probably do it, let me know.

**Comment by eric-wieser** [comment]
> I struggled with passing the dimensions array to python

You can use `PyArray_IntTupleFromIntp` to get the tuple of dimensions

**Comment by rezapci** [comment]
`
in:
import matplotlib.pyplot as plt

import pandas as pd
%matplotlib inline
import numpy as np

view_dt = pd.read_csv('dataset.csv')

in:
view_dt.shape
out: (300000, 14)

in:
dtypes
out:
time    object
d1       int64
d2       int64
d3       int64
d4       int64
d5       int64
d6       int64
d7       int64
d8       int64
d9       int64
d10      int64
d11      int64
d12      int64
d13      int64
dtype: object
in:
data = view_dt.iloc[:, 3:5].values
in:
import scipy.cluster.hierarchy as shc

plt.figure(figsize=(10, 7))
plt.title("Lux Dendograms")
dend = shc.dendrogram(shc.linkage(data, method='ward'))`

out:
MemoryError: Unable to allocate array with shape (44999850000,) and data type float64

**Comment by bmakos** [comment]
> `in: import matplotlib.pyplot as plt`
> 
> `import pandas as pd %matplotlib inline import numpy as np`
> 
> `view_dt = pd.read_csv('dataset.csv')`
> 
> `in: view_dt.shape out: (300000, 14)`
> 
> `in: dtypes`
> `out: time object d1 int64 d2 int64 d3 int64 d4 int64 d5 int64 d6 int64 d7 int64 d8 int64 d9 int64 d10 int64 d11 int64 d12 int64 d13 int64 dtype: object`
> `in:`
> `data = view_dt.iloc[:, 3:5].values`
> `in:`
> `import scipy.cluster.hierarchy as shc`
> 
> `plt.figure(figsize=(10, 7))`
> `plt.title("Lux Dendograms")`
> `dend = shc.dendrogram(shc.linkage(data, method='ward'))`
> 
> `out: MemoryError: Unable to allocate array with shape (44999850000,) and data type float64`

Is there a question? An 11 digit number times the size of float64 on your system is likely a larger number than the memory available.

**Comment by eric-wieser** [comment]
Locking this because it's likely to draw more comments of the same style, and they'd be easier to handle as separate issues.

To people who have this error: you are allocating a very large array, larger than your available memory. This might be caused by:
* Large inputs
* Incorrect broadcasting - look at the shape in the error message, and check it's what you'd expect
* A problem is the function you're calling that creates unreasonable large arrays
