### ISSUE TITLE
MemoryError with fancy indexing / np.take

### ISSUE THREAD

**Issue by Plantain** [numpy/numpy#13223]
fancy indexing seems to throw MemoryErrors in circumstances where I do not expect it should.
For reference I have 16GB of RAM (+ swap), and the process uses ~170MB with t & z populated.

I am using 'real' data which is monotonically increasing - the intent is to find the indexes where a value (10) would fit into array t, then find the values at those indexes in another array z.
But the same occurs with np.zeros in the example b elow.

### Reproducing code example:
```
>>> t = np.zeros((51,765,285),dtype=np.float64)
>>> z = np.zeros((51,765,285),dtype=np.float64)
>>> t.shape
(51, 765, 285)
>>> indices = np.apply_along_axis(lambda a: a.searchsorted(10), axis=0, arr=t)
>>> indices.shape
(765, 285)
>>> np.take(z, indices, axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 189, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
  File "/usr/lib/python3.7/site-packages/numpy/ma/core.py", line 5810, in take
    out = _data.take(indices, axis=axis, mode=mode)[...].view(cls)
MemoryError
>>> z[indices,:,:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/numpy/ma/core.py", line 3174, in __getitem__
    dout = self.data[indx]
MemoryError
```

### Numpy/Python version information:
1.16.2 3.7.2 (default, Jan 10 2019, 23:51:51)

**Comment by eric-wieser** [comment]
Try it with smaller arrays, and you'll see that `z[indicies,:,:]` is not the shape you want.

**Comment by eric-wieser** [comment]
I opened #13225 about producing a better error message here.

**Comment by eric-wieser** [comment]
With @bmakos' changes in #13306, both examples raise
```python
MemoryError: Unable to allocate array with shape (765, 285, 765, 285) and data type float64
```

**Comment by seberg** [comment]
Great @eric-wieser and @bmakos, cool improvement. I think we can close this then. Much more information will be a bit tricky to generate, so if someone wants it, it can wait for a new issue.
