### ISSUE TITLE
Shouldn't the result be ordered the same way as the input array?

### ISSUE THREAD

**Issue by robsanpam** [numpy/numpy#13221]
https://github.com/numpy/numpy/blob/685b9ace06f1dc50e2698099d7a2b6a241379318/numpy/core/fromnumeric.py#L2231

**Comment by matthew-brett** [comment]
For those who need more background, this is from `np.all`, operating on axis=0 (across rows):

```
>>> np.all([[True,False],[True,True]], axis=0)                                                                         
array([ True, False])
```

This is in the correct order.  Is it possible you thought `axis=0` meant operating across columns (along rows)?

**Comment by robsanpam** [comment]
Thanks for your answer. I think I should be confusing something, but np.all() is the logical and right? How is it that the first row [True, False] returns a True?

**Comment by eric-wieser** [comment]
It doesn't, that is what `np.all(a, axis=1)` would mean

**Comment by robsanpam** [comment]
If I want to perform an AND reduction per row:
```
np.all([[True,False], # first row
           [True,True], # second row
           [False, False]], # third row
           axis=0)
```
I am expecting an output like: 
`array([False, True, False])`

However the result is:
`array([False, False])`

Shouldn't the result be an array of length 3 since I am reducing three rows?

**Comment by eric-wieser** [comment]
It shouldn't, that is what np.all(a, axis=1) would mean.

You are passing the wrong value for the `axis` arg

**Comment by matthew-brett** [comment]
@robsanpam  - it's a common error - and one I've made multiple times - but no - axis=0 means the first axis of the array.  When you say an array is shape (m, n), you mean it has m rows and n columns.   So the first axis is length m, and runs across the rows (and therefore along the columns).

**Comment by robsanpam** [comment]
Everything is clear now, thank you so much!
