### ISSUE TITLE
Change required Sphinx version to build docs

### ISSUE THREAD

**Issue by kritisingh1** [numpy/numpy#13230]
As of now, the guide to build the numpy docs [here](https://www.numpy.org/devdocs/docs/howto_build_docs.html) mentions the minimum Sphinx version required to be 1.0.1, however it throws an error which is due to 1.0.1 being an outdated version.
### Reproducing code example:
Run `make html` in `numpy/doc` directory
### Error message:
`sphinx-build: error: unrecognized arguments: --keep-going`

Hence we need to change the minimum required version in the docs.

**Comment by RuthAtem** [comment]
I would like to work on this project
