### ISSUE TITLE
Problem in using numpy.amax() and numpy.amin() on string arrays

### ISSUE THREAD

**Issue by ROZZ01** [numpy/numpy#13246]
I am getting error reports when I use numpy.amax() and numpy.amin() when working with numpy string arrays. I run my code in Jupyter Notebook running python 3.

import pandas as pd
import numpy as np
s = np.array(['one','two','three'])

np.amax(s)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-24c766403e22> in <module>
----> 1 np.amax(s)

/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims, initial)
   2332     """
   2333     return _wrapreduction(a, np.maximum, 'max', axis, None, out, keepdims=keepdims,
-> 2334                           initial=initial)
   2335 
   2336 

/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     81                 return reduction(axis=axis, out=out, **passkwargs)
     82 
---> 83     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     84 
     85 

TypeError: cannot perform reduce with flexible type

np.amin(s)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-90cb0ff81d13> in <module>
----> 1 np.amin(s)

/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in amin(a, axis, out, keepdims, initial)
   2440     """
   2441     return _wrapreduction(a, np.minimum, 'min', axis, None, out, keepdims=keepdims,
-> 2442                           initial=initial)
   2443 
   2444 

/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     81                 return reduction(axis=axis, out=out, **passkwargs)
     82 
---> 83     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     84 
     85 

TypeError: cannot perform reduce with flexible type

**Comment by TheDeclineOfTheAmericanMiddleClass** [comment]
it has to be numbers, no?

**Comment by mattip** [comment]
Closing. The error message seems clear enough, we cannot currently perform reduce operations on flexible types. Use `max(s)` instead.
