### ISSUE TITLE
Can we have something like numpy.stats?

### ISSUE THREAD

**Issue by aakash30jan** [numpy/numpy#13256]
Hello everyone, 

Would it be useful to have something like _numpy.stats_ on the grounds of _scipy.stats.describe_  ?
Though a simple implementation, I believe it would be very handy for Numpy users. More information on _scipy.stats.describe_ here : https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.describe.html .

Thanks

**Comment by rgommers** [comment]
That seems out of scope for NumPy. Also, we don't want to duplicate what is already in SciPy. So no. Thanks for the suggestion though @aakash30jan
