### ISSUE TITLE
np.quantile: inconsistent behaviour across platforms for certain edge cases

### ISSUE THREAD

**Issue by rjenc29** [numpy/numpy#13272]
Just flagging up a couple of behavioural inconsistencies across platforms (specifically Windows and Linux) for `np.quantile` and `np.nanquantile` which were discovered whilst testing their candidate implementations in [numba](https://github.com/numba/numba/pull/3899).

### Reproducing code example:

```python
import numpy as np

a = a = np.array(5)
q = np.array(1)
print(np.quantile(a, q))

a = True
q = False
print(np.quantile(a, q))

a = np.array([False, True, True])
q = a
print(np.quantile(a, q))
```

(This example uses `np.quantile` - you get the same result with `np.nanquantile`)

### Error message:
The outputs are inconsistent across platforms; the Windows 10 outputs are (I think) expected and in line with the documented behaviour.

Outputs:

| Windows 10 | Linux Ubuntu 18.4 |
| - | - |
| 5.0 | 5 |
| 1.0 | True |
| [0. 1. 1.] | [False True True] |

### Numpy/Python version information:

**Windows 10**
1.16.2 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]

**Ubuntu 18.4**
1.16.2 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)[GCC 7.3.0]

**Comment by seberg** [comment]
Yeah, quantile/percentile assumes that `q` cannot be `intp` depending on the method used (to start off with). So it basically incorrectly uses the wrong "method" on linux (because the int array is `intp` on 64bit linux). Likely we should replace the line `q = q * (Nx - 1)` with `q = q * (Nx - 1.)`...

**Comment by rjenc29** [comment]
Great, thanks for the reply.

`np.percentile` and `np.nanpercentile` seem to be OK to me (i.e. their outputs are consistent across platforms & per the docs); it seems to be limited to `np.quantile` and `np.nanquantile` but I could be wrong.

**Comment by seberg** [comment]
Yes, those probably have a division inside so that it will always be floating point. That is a good thing, so it is a rather new issue since it is limited to quantile.

Since the fix seems probably minimal, maybe you want to give it a shot? The most important thing is to write tests as well.

**Comment by rjenc29** [comment]
Sure thing, I will PR a patch when I get a mo.

**Comment by eric-wieser** [comment]
I'd argue the Linux behavior is correct here, and the fix is simply to replace the into comparison with an `issubdtype(indices.dtype, np.integer)`

**Comment by joshz123** [comment]
is this issue open?

**Comment by ericmariasis** [comment]
Created pull request #15487

**Comment by adeak** [comment]
It seems to me that this can be closed thanks to https://github.com/numpy/numpy/pull/15487.

**Comment by seberg** [comment]
Yes, thanks for the ping.
