### ISSUE TITLE
In-place numpy array concatenation?

### ISSUE THREAD

**Issue by Derek-Wds** [numpy/numpy#13279]
I was doing a machine learning project and need to use the concatenation function to make up data. However, when my data gets big, concatenation will eat up too much memory. I have checked the documentations, it seems that numpy just copy the entire data, do the concatenation and return it back to the original data. The situation is the same for both `np.concatenate()` and `np.add()`. I wonder if there has in place concatenation of numpy array that in numpy? Thanks!

### Reproducing code example:

```python
import numpy as np
data = np.concatenate([data1, data2], axis=0)
```

### Error message:
It shows memory error when the `data1` and `data2` array get too big (like several gigabytes).

### Numpy/Python version information:
`Python 3.6.7`
`numpy (1.15.1)`

**Comment by eric-wieser** [comment]
Concatenation is the act of taking arrays at different locations in memory and combining them into the same location in memory. If memory is laid out as follows, where `foo` and `bar` are someone else's data:
```
00    04    08    0C    10    14    18    1C
|     |     |     |     |     |     |     |
[data1     ][foo ][data1     ][bar ]
```

Then concatenate produces
```
00    04    08    0C    10    14    18    1C    20    24    28    2C
|     |     |     |     |     |     |     |     |     |     |     |
[data1     ][foo ][data1     ][bar ][concat(data1, data2)  ]
```
There is no way to concatenate "in-place" into `data1`, doing so would overwrite foo, and we don't own that.
