### ISSUE TITLE
numpy getH() function not working?

### ISSUE THREAD

**Issue by the-lotuseater** [numpy/numpy#13282]
### Reproducing code example:

```python
import numpy as np
<< a = np.random.randint(1,15,size = (10,10))
a = a -1j*a
a.H >>
```

### Error message:

Traceback (most recent call last):
  File "stdin", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'H'

**Comment by eric-wieser** [comment]
You're looking for `a.T.conj()`, [more info here](https://stackoverflow.com/q/26932461/102441).

**Comment by the-lotuseater** [comment]
Thanks @eric-wieser but I was hoping to get insight into why this method is not functioning.

**Comment by eric-wieser** [comment]
There is no attribute `np.ndarray.H` or `np.ndarray.getH`. It is not functioning because it does not exist.

Are you thinking of `np.matrix.H`, part of the deprecated `np.matrix`?

**Comment by the-lotuseater** [comment]
Yes! So you're saying it is obsolete? Hmm, I guess I was misled by the documentation then. Thank you!
