### ISSUE TITLE
Check for existing of `exp` attribute before falling back to iteration

### ISSUE THREAD

**Issue by Strilanc** [numpy/numpy#13288]
In the following code, a class attempts to implement a specialized exponential method but this method is not called by numpy:

```python
class C:
    def __len__(self):
        return len([1, 2, 3])

    def __getitem__(self, item):
        return [1, 2, 3][item]

    def exp(self):
        return 'special'

v = np.exp(C())
print(v)  # [ 2.71828183  7.3890561  20.08553692]
assert v == 'special'  # fails
```

The presence of the `exp` method clearly indicates a desire to override numpy's default behavior with respect to iterables, but it is ignored.

**Comment by charris** [comment]
The class looks like a sequence to NumPy and is converted to an array as such. You might want to look at `__array_ufunc__` in recent NumPy releases if you need that sort of functionality.

**Comment by seberg** [comment]
I agree with Chuck. We should not start to randomly test for attributes on sequence objects. Array ufunc is a likely candidate here, maybe there are others, but without some very good arguments I am -1 on doing the attribute lookup.
