### ISSUE TITLE
Processes do not exit after successful computation

### ISSUE THREAD

**Issue by gasabr** [numpy/numpy#13294]
**Problem**: after computing eigen values with numpy in internals of the `mordred` library  processes being created by `C` code are still there.

**Solution**: I was able to fix the issue by setting env OMP_NUM_THREADS=1. That's the dirty fix, but I would like to understand the cause of the problem and fix it if possible.

### Reproducing code example:
please, install mordred (`pip install mordred`, `conda install -c rdkit rdkit`) to reproduce, I was not able to reproduce with numpy only, will attach the code and files below.

```python
import time
from mordred import Calculator
from rdkit.Chem import MolFromSmiles
c = Calculator.from_json(
    [{"name": "BaryszMatrix", "args": {"prop": "Z", "type": "SpAbs"}}]
)
molecule = MolFromSmiles('O=C(NCc1ccnc(N2CCCCC2)c1)Nc1ccc2c(c1)CCC2')
c(molecule)
time.sleep(10)
# in htop one can see around 30 processes with sleep status
```

Also, I've tried to reproduce the error by doing the exact call that is made in the snippet above to calculate eigen values, but here I encountered error, which I'm not sure how to fix, sorry.

```python
from numpy.linalg import _umath_linalg
import pickle
with open('a.pkl', 'rb') as fp: a = pickle.load(fp);
with open('extobj.pkl', 'rb') as fp: extobj = pickle.load(fp);
signature = 'd->dd'
_umath_linalg.eigh_lo(a, signature, extobj)
```

### Numpy/Python version information:
```
(numpy_bug) gabroskin@xxx:~$ python -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.16.2 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
```
[archive](https://github.com/numpy/numpy/files/3059916/numpy_bug.tar.gz) with files to reproduce in pure numpy.

UPD: added installation of rdkit

**Comment by seberg** [comment]
I am going to close this. Setting `OMP_NUM_THREADS` to 1 is not all that bad. There is also joblib threadpoolctrl project which may be interesting to you. Unfortunately, numpy currently has no very direct control of these threads (in fact you can change the BLAS backend without recompiling numpy). there have been thoughts about adding some tries for it, but overall threadpoolctrl likely fills the gap sufficiently right now.
