### ISSUE TITLE
np.savetxt bug on structured array

### ISSUE THREAD

**Issue by mooyeolb** [numpy/numpy#13297]
Saving numpy array subsampled by multi-field indexing fails.

### Reproducing code example:

```python
import numpy as np
x = np.array([(1,2,3),(4,5,6)], dtype=[('foo', 'i8'), ('bar', 'f4'), ('yee', 'f4')])
np.savetxt('out.txt', x[['foo', 'yee']])
```

### Error message:
TypeError: Mismatch between array dtype ('{'names':['foo','yee'], 'formats':['<i8','<f4'], 'offsets':[0,12], 'itemsize':16}') and format specifier ('%.18e %.18e %.18e')

### Numpy/Python version information:
('1.16.2', '2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) \n[GCC 7.3.0]')

**Comment by Dan-Patterson** [comment]
Following along in this thread

https://github.com/numpy/numpy/issues/13299

y = rf.repack_fields(x[['foo', 'yee']])
np.savetxt('c:/temp/out.txt', y)

was the only thing that didn't raise the error you posted.
