### ISSUE TITLE
pyzo and numpy installation

### ISSUE THREAD

**Issue by emiliejehanno** [numpy/numpy#13290]
I can't open numpy 

I wrote "pip install numpy" in the shell
it seams ok but it is not

When I try to import numpy writing "import bumpy as np"
I see this :

<<<Traceback (most recent call last):
  File "<tmp 1>", line 1, in <module>
    import numpy as np
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-32),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dynamic module does not define module export function (PyInit__multiarray_umath) >>>>

As I am French I don't really understand everything.

Thank you

**Comment by charris** [comment]
Are you using Anaconda? Also take a look at #12977.

**Comment by rgommers** [comment]
install issue with no response after a month, closing
