### ISSUE TITLE
np.arange() unexpected behaviour: Same output when the output should be different

### ISSUE THREAD

**Issue by JackHenry281** [numpy/numpy#13304]
I have a found a bug with np.arange(). When specifying two different end values for the range the outputted matrix is the same when it should be different.

### Reproducing code example:

```python
import numpy as np
#this should be False
len(np.arange(0, 19.76, 0.08)) == len(np.arange(0, 19.84, 0.08))
This should cause an error but does not
np.arange(0, 19.76, 0.08) == np.arange(0, 19.84, 0.08)
```

### Error message:

There is no error message

### Numpy/Python version information:

1.16.2 3.7.2 (default, Feb 21 2019, 17:35:59) [MSC v.1915 64 bit (AMD64)]

**Comment by mattip** [comment]
Numpy's floating point numbers are a discrete representation of a continuous world. Try exploring with the stop value to see where the rounding errors will change the result
```
len(np.arange(0, 19.76, 0.08))
len(np.arange(0, 19.759999999999, 0.08))
len(np.arange(0, 19.84000000001, 0.08))
```

**Comment by JackHenry281** [comment]
> Numpy's floating point numbers are a discrete representation of a continuous world. Try exploring with the stop value to see where the rounding errors will change the result
> 
> ```
> len(np.arange(0, 19.76, 0.08))
> len(np.arange(0, 19.759999999999, 0.08))
> len(np.arange(0, 19.84000000001, 0.08))
> ```

I tried adding dozens, if not hundreds of zero's onto the end of 19.84 and 19.76 but still got the same issue. e.g: typing the following into the console still returns True. 
```
len(np.arange(0, 19.760000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0.08)) == len(np.arange(0, 19.840000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0.08))
```

**Comment by mattip** [comment]
Adding zeros does not change the conversion of that text into a [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) binary representation. There is limited precision to the representation that numpy uses, and sometimes rounding error creep in.

**Comment by rossbar** [comment]
The `arange` docs mention the potential hang ups with float steps due to floating point error (see the `Returns` section). Unless there is a proposal for how the docs could be improved I'd be inclined to close this.

**Comment by seberg** [comment]
Agreed, there are issues around arange (more than necessary due to floats), but there is a huge amount of code that relies on those issues probably. I would love a proposal to try and attack this, but I honestly do not know if we can/should. (Of course we could fix up some of the weirdness, but then we have to figure out how bad the impact will be, and this for one is a difference that I think is likely extremely common that people write `np.arange(0, 19.84000000001, 0.08)[:-1]`) or so.
