### ISSUE TITLE
Feature request: Adding flag to allow anti-diagonals

### ISSUE THREAD

**Issue by AnderUstarroz** [numpy/numpy#13302]
Wouldn't be great adding to **numpy.diagonal** and **numpy.fill_diagonal** the capability of using anti-diagonals?  Maybe adding  a flag to return the anti-diagonal instead?

I know currently it can be achieved doing some tricks like `np.fliplr(a).fill_diagonal(array, 1)` but doesn't feel right.

For example:
```python
import numpy as np

# NORMAL DIAGONAL
a = np.zeros((3, 3))
np.fill_diagonal(a, 1)
print(a)
#  array([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]])

# ANTI-DIAGONAL (Suggestion)
a = np.zeros((3, 3))
np.fill_diagonal(a, 1, flip=True)
print(a)
#  array([[0., 0., 1.],
#         [0., 1., 0.],
#         [1., 0., 0.]])

# Another example:
a = np.zeros((3, 3))
np.fill_diagonal(a[:,:2], 1, flip=True)
print(a)
#  array([[0., 1., 0.],
#         [1., 0., 0.],
#         [0., 0., 0.]])

```

**Comment by eric-wieser** [comment]
I think the name you're looking for is [anti-diagonal](https://en.wikipedia.org/wiki/Anti-diagonal_matrix) rather than `inverse` or `reverse`.

**Comment by AnderUstarroz** [comment]
Thanks @eric-wieser, I have updated the name to anti-diagonal to avoid confusions. 
About your examples using `np.fliplr()` that was exactly my point, having to implement 3 different steps to achieve anti-diagonal feels cumbersome. I think it would be way cleaner having a dedicated function for it or just a flag to reverse the result when using  diagonal/fill_diagonal.

**Comment by eric-wieser** [comment]
I only count two steps there, not three - and there are two options for the first (`flip`) step. How do we decide between them?

**Comment by AnderUstarroz** [comment]
I think you are right, it was just a mistake of my implementation, I was using these three steps 

```python
import numpy as np


a = np.zeros((3,3))
np.fill_diagonal(a, 1)
a = np.fliplr(a)            # Step 1 flip array
np.fill_diagonal(a, 2)  # Step 2 apply anti-diagonal
a = np.fliplr(a)            # Step 3 flip back the array
print(a)
# array([[1., 0., 2.],
#       [0., 2., 0.],
#       [2., 0., 1.]])
```

I didn't know this could be more easily achieved just like this:
```python
import numpy as np


a = np.zeros((3,3))
np.fill_diagonal(a, 1)
np.fill_diagonal(np.fliplr(a), 2)  
print(a)
# array([[1., 0., 2.],
#       [0., 2., 0.],
#       [2., 0., 1.]])

```
So please, forgive this poor ignorant :)

**Comment by eric-wieser** [comment]
Do you want to add an example to the `fliplr` documentation that shows how the fact the result is a view and not a copy can be useful? I think `fill_diagonal(fliplr(a), [1, 2, 3])` might be a good way to show that

**Comment by AnderUstarroz** [comment]
My personal vendetta is against the anti-diagonals. I bet more people like me was hoping to see some examples about how to create anti-diagonal within the [np.diagonal](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diagonal.html) and [np.fill_diagonal](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.fill_diagonal.html) pages.


- [Pull request 13316](https://github.com/numpy/numpy/pull/13316/commits)
