### ISSUE TITLE
Slow creation of object-dtype array when elements define __len__

### ISSUE THREAD

**Issue by TomAugspurger** [numpy/numpy#13308]
This is a bit of a strange one that pandas users are hitting. Creating a nested 1-d ndarray (each element of the array is itself an array-like object) is quite slow when the element class defines `__iter__`,  `__getitem__` and `__len__`. When only `__iter__` and `__getitem__` is defined, an alternate (faster) path seems to be taken.

Some setup:

```python
import time
import numpy as np


class Fast:
    def __init__(self, x):
        self.x = x

    def __iter__(self):
        return iter(self.x)

    def __getitem__(self, item):
        return self.x[item]


class Slow(Fast):
    # Defining `__len__` puts us on a slow path.
    def __len__(self):
        return len(self.x)
```

And demonstrating the problem, where our "element" class is itself an ndarray (so we're putting ndarrays inside ndarrays). Note that we use the pattern

```python
out = np.empty(length, dtype=object)
out[:] = ...
```

to avoid issues with shape inference in the `np.array` method (perhaps there's a better way to do this?)

```python
arr = np.arange(1_000_000)
out = np.empty(2, dtype=object)

f = Fast(arr)
obj = [[f], [f]]
t0 = time.time()
out[:] = obj
t1 = time.time()
print(f'Fast: {t1 - t0}')

out = np.empty(2, dtype=object)
f = Slow(arr)
obj = [[f], [f]]
t0 = time.time()
out[:] = obj
t1 = time.time()
print(f'Slow: {t1 - t0}')
```

For me, that prints

```
## -- End pasted text --
Fast: 0.00
Slow: 0.16
```

I haven't really done any profiling, as I'm not sure how to profile the C code inside NumPy.

**Comment by seberg** [comment]
Well, numpy coerces to arrays, and this coercion has to discover the correct dimensionality of the array. I am not sure is much we can do about it to be honest, but maybe worth a look. We may want something like an `ndim` argument to make object array coercion more robust in any case, and if that happens, `np.array` may need an `ndim` argument and then the dimension discovery could be skipped?

**Comment by seberg** [comment]
Since you have probably pretty special objects in the use case, maybe there is something to optimize in the specific logic here.

**Comment by TomAugspurger** [comment]
> Well, numpy coerces to arrays, and this coercion has to discover the correct dimensionality of the array.

Can you expand on this a bit? It's possible that `np.array` coerces, but in an example use case from https://github.com/pandas-dev/pandas/issues/25364 (an ndarray where each element is a PyArrow Table), the element array-likes aren't converted.

```python
In [1]: import pyarrow as pa

In [2]: import numpy as np

In [3]: x = np.arange(1000000)

In [4]: y = pa.array(x)

In [5]: out = np.empty(2, dtype=object)

In [6]: %time out[:] = [y, y]
CPU times: user 1.03 s, sys: 110 ms, total: 1.13 s
Wall time: 1.12 s

In [7]: out[0]
Out[7]:
<pyarrow.lib.Int64Array object at 0x114f6b368>
[
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  ...
  999990,
  999991,
  999992,
  999993,
  999994,
  999995,
  999996,
  999997,
  999998,
  999999
]
```

> We may want something like an ndim argument to make object array coercion more robust in any case

This sounds generally useful for creating an ndarray from nested data, but this may not be an important use case for NumPy.

> Since you have probably pretty special objects in the use case, maybe there is something to optimize in the specific logic here.

I may be mis-remembering, but when I looked at this last month it's possible that objects implementing the buffer protocol didn't hit the slow path. But, this is a general issue with pandas users trying to stuff strange things into an object-dtype arrays.

**Comment by seberg** [comment]
This is now fast in master, since for assignment to object we only discovery the number of necessary dimensions, and its now defined to go exactly into one level of array-likes, and never further (it almost never really did before as well).  So I think this is fixed at this time and we should open a new issue if there is more that seems oddly slow.
