### ISSUE TITLE
Warnings need different stacklevel after NEP 18 overrides

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#13329]
An example can be seen in recent doc builds:
```
/home/circleci/repo/venv/lib/python3.6/site-packages/numpy/core/overrides.py:150: RankWarning: Polyfit may be poorly conditioned
  implementation, public_api, relevant_args, args, kwargs)
/home/circleci/repo/venv/lib/python3.6/site-packages/numpy/core/overrides.py:150: RankWarning: Polyfit may be poorly conditioned
  implementation, public_api, relevant_args, args, kwargs)
```
In every function that got an override, the warnings `stacklevel` needs to be increased by 1. 

I looked for an existing issue for this but couldn't find it. @shoyer does this need to be added to the NEP 18 tracking issue?

**Comment by shoyer** [comment]
Yes, this would be good to add to the tracking issue.
