### ISSUE TITLE
Extension integer dtypes (such as pandas Int32Dtype) do not work with numpy

### ISSUE THREAD

**Issue by techvslife** [numpy/numpy#13330]
This is not strictly speaking a bug, but an issue caused by lack of support for the new nullable extended dtypes from pandas (such as the nullable integer Int32Dtype) when they get passed along to numexpr and numpy (for example through the pandas query method):    

I posted the issue at pandas and numexpr:
https://github.com/pandas-dev/pandas/issues/25369
https://github.com/pydata/numexpr/issues/331
https://stackoverflow.com/questions/54759936/extension-dtypes-in-pandas-appear-to-have-a-bug-with-query

It was suggested I also post here at numpy, but if this does not seem appropriate, please feel free to close or delete this report.

The following code using the pandas ("pd") query method fails, apparently because it is passed along to numexpr and numpy and the datatype used (Int32Dtype, note the capital letter I) is not recognized or understood:

```
df_test = pd.DataFrame(data=[4,5,6], columns=["col_test"])
df_test = df_test.astype(dtype={"col_test": pd.Int32Dtype()})
df_test.query("col_test != 6")
```
Last lines of the long error message are:

> File "...\site_packages\numexpr\necompiler.py", line 822, in evaluate zip(names, arguments)] File "...\site_packages\numexpr\necompiler.py", line 821, in signature = [(name, getType(arg)) for (name, arg) in File "...\site_packages\numexpr\necompiler.py", line 703, in getType raise ValueError("unknown type %s" % a.dtype.name) ValueError: unknown type object

**Comment by rgommers** [comment]
I don't think that's fixable on our end, pandas should take care not to pass its own custom dtype that numpy knows nothing about to numpy.

**Comment by seberg** [comment]
I agree with Ralf, at this time we cannot really provide anything that can fix it. Numpy should not have to import pandas or something like this. If there is some concrete idea what numpy can do or we are missing a bit how numpy comes into the picture here, please reopen/comment!
