### ISSUE TITLE
poly1d coefficients appear to be immutable

### ISSUE THREAD

**Issue by ketch** [numpy/numpy#13347]
In some older versions of numpy, it was possible to change the coefficients of a `poly1d` object.  Now it seems not possible.  According to https://github.com/numpy/numpy/issues/9385 I believe the coefficients should still be mutable.

### Reproducing code example:

```python
import numpy as np
import numpy
p = numpy.poly1d((1,1))
print(p)
p.c[0]=0
print(p)
```
Both print statements print `array([1, 1])`.  

### Numpy/Python version information:

I am using numpy version 1.16.2.

**Comment by eric-wieser** [comment]
It looks like I introduced this again in #8788...
