### ISSUE TITLE
Proper pronunciation not in documentation

### ISSUE THREAD

**Issue by jaschaffer** [numpy/numpy#13353]
Hello, I just like to quickly point out that the proper pronunciation for numpy does not appear on the main page of the documentation.  I believe a short line would be all that is needed to cut down on the rampant mispronunciation I have observed in my career (some people really think it's pronounced num-pie and not numpee?!  Really??!!!)

Thank you for your time.

Regards,
James Schaffer

**Comment by eric-wieser** [comment]
> I believe a short line would be all that is needed

This assumes that internally the maintainers all use the same pronunciation, which in my experience we do not (at least, if I include myself)

**Comment by tylerjereddy** [comment]
From the Wikipedia [entry for NumPy](https://en.wikipedia.org/wiki/NumPy):

![image](https://user-images.githubusercontent.com/7903078/56255209-dc4ebb00-6078-11e9-9152-c2fd4c9c0d15.png)

Wikipedia cites reddit, so it must be true.

**Comment by seberg** [comment]
At some point I think I switched to using the second version (more), confuses most people in I talk to, and I often have to repeat myself ;).

**Comment by seberg** [comment]
I am going to close this. Unless Travis or so chimes in, I do not see a reason, both pronounciations are fairly common, and none of the core devs seems to care.
