### ISSUE TITLE
DOC: SciPy numpy documentation out of date

### ISSUE THREAD

**Issue by daniel-goldstein** [numpy/numpy#13355]
Noticed an error in the [matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html) docs that was fixed by #12560 but is still not updated in the published documentation. Specifically,
```python
>>> a = a = np.full([9,5,7,3], True, dtype=bool)
>>> c = np.full([9, 5, 4,3], True, dtype=bool)
>>> np.dot(a, c).shape
(9, 5, 7, 9, 5, 4)
>>> np.matmul(a, c).shape # n is 5, k is 3, m is 4
(9, 5, 7, 4)
```

The fix was committed on Dec 17, 2018, and the SciPy page was last updated Jan 31, 2019. Just curious if this is an issue and, if not, if the page will be updated soon with the corrected docs.

**Comment by mattip** [comment]
Marked for backporting as 1.16 is a long-term release. Thanks for the heads up

**Comment by seberg** [comment]
Seems this is now backported, so closing.
