### ISSUE TITLE
Squeeze() fails when array shape contains 0

### ISSUE THREAD

**Issue by abduallahmohamed** [numpy/numpy#13364]
When trying to squeeze an array that has a shape of [0,:,:] the squeezed array is [0,:,:] rather than [:,:]. 

### Reproducing code example:

```python
import numpy as np 
import sys
x = np.ones((1,100,100))
#Bug
v = x[0:0,:,:]
print(v.shape)
v_squeezed = v.squeeze()
print(v_squeezed.shape)

```

output: 

> (0, 100, 100)
> (0, 100, 100)

### Numpy/Python version information:

1.16.2 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

**Comment by eric-wieser** [comment]
This is by design:

> The input array, but with all or a subset of the dimensions of length 1 removed.

```
>>> print(1 in v.shape)
False
```

note that `(0, 100, 100)` has 0 elements, but `(0, 100, 100)` has 10000 elements. If it behaved the way you're asking we would have to generate new data to fill those.
