### ISSUE TITLE
mean of an empty list

### ISSUE THREAD

**Issue by shuaitang** [numpy/numpy#13365]
The mean of an empty list is 'nan', which is supposed to be 0 I believe.

### Reproducing code example:

```python
import numpy as np
np.mean([])

```

### Error message:

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

### Numpy/Python version information:

1.16.0 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609]

**Comment by eric-wieser** [comment]
There's some good discussion [on stack exchange](https://math.stackexchange.com/q/909395/1896) about why NaN is correct behavior here.

**Comment by shuaitang** [comment]
Thanks!

**Comment by lucky-lidong** [comment]
3q
