### ISSUE TITLE
 TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by arunadevikaruppasamy** [numpy/numpy#13378]
Please kindly help me to resolve this issue.  
I have to access only training values as the index values from out_input1( tuple) value

##Y is the label in 800 labelled MNIST dataset
training=np.where(Y)
beta=np.zeros(len(Y)+1)
Kb=np.zeros(n2)
print(Kb)
out_input1=Y[np.where(Y)]**(Kb+beta[-1])
### in matlab the code is sv=training(out>0) ##
training_list_sv=training(np.where(out_input1>0))

**Comment by matthew-brett** [comment]
`np.where` returns a tuple, so `training` is a tuple, and `training(anything)` willl generate the error you see.  You probably mean `training` to be an array, and you want to index into the array with `training[something]` (note square brackets).

**Comment by arunadevikaruppasamy** [comment]
Hi, 
Even i cahnged the tuple into array format and tried like the following code. Kindly help me. I am getting an error

**training_array=np.array(training)
SV_index2=training_array[np.where(out_input1>0)]**

**IndexError                                Traceback (most recent call last)**
<ipython-input-236-e887918d685d> in <module>
      1 training_array=np.array(training)
----> 2 SV_index2=training_array[np.where(out_input1>0)]

**IndexError: index 1 is out of bounds for axis 0 with size 1**

**Comment by arunadevikaruppasamy** [comment]
HI
I used this statement to place the tuple as indices inside a array. and found the output

**np.in1d(np.arange(len(indices)), training_array)**
   **index2=training_array[mask]**
Thank you@matthew-brett for your reply
