### ISSUE TITLE
test_scalarprint fails:  numpy.float64 should be used

### ISSUE THREAD

**Issue by epcc-mjf** [numpy/numpy#13376]
Intel x86_64
Linux 3.0.101-0.47.106.59-default
gcc 6.1.0
python 3.6.0
numpy 1.16.2

In test_dragon4 in https://github.com/numpy/numpy/blob/master/numpy/core/tests/test_scalarprint.py there is

```python
fpos64 = lambda x, **k: np.format_float_positional(np.float64(x), **k)
...
assert_equal(fpos64(0.5**(1022 + 52), unique=False, precision=1074), ...)
```
and I get the error "E       OverflowError: (34, 'Numerical result out of range')"

I think this is an error in the test.  `numpy.float64(0.5)` should be used
instead of `0.5` which is an ordinary Python `float`, which has the
following limits:

```python
>>> sys.float_info
sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)
```

**Comment by seberg** [comment]
This may be a denormal number, but I do not see why it should give you an overflow error during the test run. The python expression `0.5**(1022 + 52)` should not cause an OverflowError on any system I think, even if you system does not support it, it would simply return 0.0.

Can anyone reproduce it, or is there anything special about your system (I do not know right now where to start, but maybe a virtual machine or so?)

**Comment by epcc-mjf** [comment]
This was on a Cray XC30, but that is just x86_64.  Testing a different installation of Python 3 gives the same result.  On a different cluster (also x86_64), I get 5e-324, the smallest denormal double.

And on the Cray, 0.5**1022*0.5**52 gives 5e-324.  Possibly we configured something incorrectly when we built Python.  I'll close this issue and look in detail how we have built Python.

Sorry for the premature bug report, and thanks for pointing out that this is a denormal number.

**Comment by seberg** [comment]
Well, I am sure you saw something. Please let us know/reopen if there is a chance that numpy is at fault here!

**Comment by epcc-mjf** [comment]
This test failure is because of an old libm (i.e., old glibc).  On the Cray system (www.archer.ac.uk) glibc is 2.11.3, on the other cluster (www.cirrus.ac.uk) glibc is 2.17.  On the Cray, with glibc 2.11.3, a test C program compiled with gcc 7.2.0 -std=c99 -lm gives:

errno =  0  pow(0.500000,1022.000000) = 2.225074e-308
errno = 34  pow(0.500000,1023.000000) = 1.112537e-308
errno = 34  pow(0.500000,1073.000000) = 9.881313e-324
errno = 34  pow(0.500000,1074.000000) = 4.940656e-324
errno = 34  pow(0.500000,1075.000000) = 4.940656e-324
errno = 34  pow(0.500000,1076.000000) = 0.000000e+00
errno = 34  pow(0.500000,1077.000000) = 0.000000e+00

on the other cluster, with glibc 2.17, the same program compiled with gcc 7.2.0 -std=c99 -lm gives:

errno =  0  pow(0.500000,1022.000000) = 2.225074e-308
errno =  0  pow(0.500000,1023.000000) = 1.112537e-308
errno =  0  pow(0.500000,1073.000000) = 9.881313e-324
errno =  0  pow(0.500000,1074.000000) = 4.940656e-324
errno = 34  pow(0.500000,1075.000000) = 0.000000e+00
errno = 34  pow(0.500000,1076.000000) = 0.000000e+00
errno = 34  pow(0.500000,1077.000000) = 0.000000e+00

Using the fenv functions shows that all the non-zero errnos are underflows (FE_UNDERFLOW).  (And, yes, there is a different result for 0.5**1075 - I think 2.11.3 in incorrect.)

In Python 3.7.3 (and 3.6.0) there is a test for errno==34 (ERANGE) and result==0.0, to give no error, otherwise an underflow is reported as an Overflow.  For example, on the Cray:

>>> 0.5**(1022+53)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: (34, 'Numerical result out of range')
>>> 0.5**(1022+54)
0.0

which is exactly what is seen in the test failure, for 1022+52 = 1074.

So, unless you want to support rather old systems, then the test does not need to be changed.

**Comment by seberg** [comment]
Thanks for the followup @epcc-mjf fixing the test may be an option, though considering how old it is, not sure it is worth the trouble. @charris I know we sometimes blacklist certain glibc functions for certain versions, I doubt it makes sense here, but I am just not too familiar with that part?

**Comment by charris** [comment]
We do when we have a fallback math function that fixes the error, the blacklist is in `numpy/core/src/common/npy_config.h`. @epcc-mjf If you are doing your own numpy builds you might try running some experiments, it's an easy edit. It would be nice to know which library version fixed the problem,  but that is probably a lot of work for little gain.

**Comment by epcc-mjf** [comment]
Hi Charles,

Thanks  for the suggestions.

Unfortunately, there isn't a fall-back function for npy_pow, so I get "undefined symbol: npy_pow" if I simply #undef HAVE_POW.  But even if I did have a fall-back, I think the test will still fail, since it uses Python ** operator, not Numpy's power function.  So, I will document the failed test:  since it is for an underflow, I think our users will see little effect.

All I know at the moment is that glibc 2.11.3 doesn't work, and 2.16 does.

Mark

-----Original Message-----
We do when we have a fallback math function that fixes the error, the blacklist is in numpy/core/src/common/npy_config.h. @epcc-mjf <https://github.com/epcc-mjf>  If you are doing your own numpy builds you might try running some experiments, it's an easy edit. It would be nice to know which library version fixed the problem, but that is probably a lot of work for little gain.

The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336.

**Comment by seberg** [comment]
@epcc-mjf, this is a warning being raised, right? It may be that if you set numpy into release mode, the test suit will only report a warning and not an actual test failure/error.

**Comment by epcc-mjf** [comment]
Hi Sebastian,

It's a failure, not a warning.  How do I set Numpy in release mode?  Currently everything compiles with "-DNDEBUG" but I don't see anywhere a setting for release mode.

Since the test that fails is to test the output of reals rather than test underflows, you could use Numpy float rather than a Python float in the test.

Mark

-----Original Message-----

**Comment by charris** [comment]
Edit the root `setup.py` and set `ISRELEASED` to `True` so that the version is correctly reported. You may also want to edit `pytest.ini` if you are compiling from the repo, as that is the file that sets warnings to errors and is absent in releases.

**Comment by epcc-mjf** [comment]
Hi Charles,

I have been using the 1.16.2 release, not the Git repo, so ISRELEASED = True in setup.py already.  pytest.ini is present, so I could ignore " OverflowError: \(34,", but I look at the test results (rather than just testing for overall pass/fail), so it is better to not ignore that test and for me to add a comment to our instructions.

Mark

The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336.
