### ISSUE TITLE
Does reshape create a pointer to the array, so changes the array in a local function will influence it globally.

### ISSUE THREAD

**Issue by Rothdyt** [numpy/numpy#13380]
### Reproducing code example:

Please consider the following minimal reproducible scenarios.

```python
import numpy as np
def test(x):
    b = x[-1]
    for i in range(4):
        b += 100

a = 2
b = 1
x = np.array([a,b]).reshape(-1,1)
x_0 =  np.array([a, b])
```

The first experiment:

```python
test(x)
print("b val:", b)
print("x val:", x)
```

the output is

```
b val: 1
x val: [[  2]
 [401]]
```

The first experiment:

```python
test(x_0)
print("b val:", b)
print("x val:", x_0)
```

the output is

```
b val: 1
x val: [2 1]
```

I am wondering why after calling the reshape on `x`, changes inside the  function will influence the value of `x[-1]` globally in the first case while it won't happen in the second case.

### Numpy/Python version information:

Version: '1.16.2'

**Comment by mattip** [comment]
For a multi-dimensional ndarray, `arr[-1]` returns a 1-d view of the original array. For a 1-d ndarray, `arr[-1]` returns a 0-d scalar, the data held is detached from that of the original array.
```
a1 = np.array([1, 2]).reshape(-1, 1)
x1.base
```
prints `array([1, 2])` indicating that `x1` holds a reference to another array, modifying `x1` will modify that array.
```
a2 = np.array([1, 2])
print(x2.base)
```
prints `None`, indicating that `x2` owns its data, and modifying `x2` will not modify anything else. 

You could also look at `x1.flags` and `x2.flags`, note that the former has `OWNDATA = False` while the latter has `OWNDATA = True`

Closing, stackoverflow may be a better place for these kind of questions.

**Comment by eric-wieser** [comment]
If you use `x[...,-1]` instead of `x[-1]` then both will behave the same way
