### ISSUE TITLE
Tests in numpy.distutils.tests.test_system_info evoke crashed 'cl.exe' dialog and require manual intervention to close the dialog

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [numpy/numpy#13387]
With NumPy 1.16.3 on Windows, on a machine with Visual Studio installed, but not activated, running the following test

```sh
pytest --pyargs numpy.distutils.tests.test_system_info
```

cause Windows to pop 'Application Crashed' window, which need to be dismissed manually. 

The error comes from execution of `have_compiler()` function in [test_system_info.py#L60](https://github.com/numpy/numpy/blob/maintenance/1.16.x/numpy/distutils/tests/test_system_info.py#L60).

![image](https://user-images.githubusercontent.com/21087696/56532471-6d131400-651b-11e9-84ae-ba8d8952bf96.png)

The code I was executing:

```python
import numpy as np
np.__version__
from subprocess import Popen, PIPE
from numpy.distutils import customized_ccompiler
compiler = customized_ccompiler()
compiler.initialize()
cmd = [compiler.cc]
cmd
Popen(cmd, stdout=PIPE, stderr=PIPE) # crash
```

If the compiler environment is activated this goes through just fine, as well as when no compiler is installed.

My attempt to suppress the crashing window using https://stackoverflow.com/questions/5069224/handling-subprocess-crash-in-windows were not successful.

This is hampering automation of builds of numpy.

**Comment by mattip** [comment]
The code to call [`SetErrorMode`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680621(v=vs.85).aspx) should reset to the old values after the call, see below. Although as you point out it will not catch this class of errors. Maybe @zooba could shed some light?

<details>

```
if sys.platform.startswith('win'):
    # Do not open "do you wish to report" dialog box 
    import ctypes
    SEM_NOGPFAULTERRORBOX = 0x0002 # From MSDN
    old_err_mode = ctypes.windll.kernel32.GetErrorMode()
    new_err_mode = old_err_mode | SEM_NOGPFAULTERRORBOX
    ctypes.windll.kernel32.SetErrorMode(new_err_mode)
#
# execute some Popen here
#            
if sys.platform.startswith('win'):
    ctypes.windll.kernel32.SetErrorMode(old_err_mode)
```

**Comment by rgommers** [comment]
> If the compiler environment is activated this goes through just fine, as well as when no compiler is installed.

The `have_compiler` code wasn't touched in the last 2 years. So this is due to changes in Anaconda, and it happens when the only installed compiler is the conda-installed one and the `base` env is deactivated so conda doesn't do it's envvar/sysroot dance?

**Comment by oleksandr-pavlyk** [comment]
@rgommers We are not using Anaconda-provided compilers at this point. The machine has several versions of system-installed Visual Studios and an Intel Compiler.

I am able to reproduce the pop-up of the modal window issue even with PyPI installed numpy 1.16.3 into a conda environment with only cpython:

![image](https://user-images.githubusercontent.com/21087696/56584234-fae51280-65a0-11e9-83be-acacb805090d.png)

The environment was built using 

```
conda create -n pypi -c defaults python=3.6 --yes
conda activate pypi
pip --no-cache-dir numpy==1.16.3 pytest 
pytest --pyargs numpy.distutils.tests.test_system_info
```

but you are correct that this same behavior can be reproduced when pip-installing ``numpy==1.16.2``.

**Comment by rgommers** [comment]
Thanks @oleksandr-pavlyk. That does still seem to have something to do with recent changes in conda. I noticed that activating any conda env will set things like `sysroot`, `LDFLAGS`, etc. - does unsetting all of those help?

**Comment by oleksandr-pavlyk** [comment]
I am using the latest version of conda and conda-build. Activating my base environment does not set those variables, or rather does not set `LDFAGS`, `CFLAGS` or `sysroot`.

```text
C:\Users\opavlyk\devel\miniconda3cb3\Scripts>activate

(base) C:\Users\opavlyk\devel\miniconda3cb3\Scripts>echo %LDFLAGS%
%LDFLAGS%

(base) C:\Users\opavlyk\devel\miniconda3cb3\Scripts>echo %CFLAGS%
%CFLAGS%

(base) C:\Users\opavlyk\devel\miniconda3cb3\Scripts>conda list conda
# packages in environment at C:\Users\opavlyk\devel\miniconda3cb3:
#
# Name                    Version                   Build  Channel
conda                     4.6.14                   py37_0
conda-build               3.17.8                   py37_0
conda-env                 2.6.0                         1
conda-verify              3.1.1                    py37_0
```

**Comment by oleksandr-pavlyk** [comment]
where does one take Python with pip from other than conda, just for testing?

**Comment by rgommers** [comment]
> where does one take Python with pip from other than conda, just for testing?

Download Python from python.org, install pip with `python -m ensurepip --upgrade` works.

**Comment by oleksandr-pavlyk** [comment]
Indeed, using Python37 from python.org and the following packages

```
C:\Users\opavlyk\devel>Python\Python37-32\Scripts\pip.exe freeze
atomicwrites==1.3.0
attrs==19.1.0
backcall==0.1.0
colorama==0.4.1
decorator==4.4.0
ipython==7.4.0
ipython-genutils==0.2.0
jedi==0.13.3
more-itertools==7.0.0
numpy==1.16.3
parso==0.4.0
pickleshare==0.7.5
pluggy==0.9.0
prompt-toolkit==2.0.9
py==1.8.0
Pygments==2.3.1
pytest==4.4.1
six==1.12.0
traitlets==4.3.2
wcwidth==0.1.7
```

the test passes with no issues:

```

C:\Users\opavlyk\devel>Python\Python37-32\Scripts\pytest.exe --pyargs numpy.distutils.tests.test_system_info
================================================= test session starts =================================================
platform win32 -- Python 3.7.3, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: C:\Users\opavlyk\devel
collected 5 items

python\python37-32\lib\site-packages\numpy\distutils\tests\test_system_info.py ....s                             [100%]

========================================= 4 passed, 1 skipped in 3.68 seconds =========================================
```

I can reproduce the behavior in conda environment with numpy 1.16.3 from Anaconda as well:

```
conda create -n anac_np1163 -c defaults pytest ipython numpy python=3.7
conda activate anac_np1163
pytest --pyargs numpy.distutils.tests.test_system_info
```

@msarahan Any suggestions on how to debug this?

**Comment by oleksandr-pavlyk** [comment]
Please change tags from bug, backport-canidate to Anaconda/Intel.

**Comment by msarahan** [comment]
No idea, but @mingwandroid may know more.  The ways that I know we differ from upstream python on Windows are:

1. unvendoring openssl
2. maybe PGO (not sure how upstream does things)
3. maybe statically linking libpython (not sure how upstream does things)

I don't see how any of those might be related here, but who knows?  Activating the env is the important part, but you're already doing that.

**Comment by oleksandr-pavlyk** [comment]
@mingwandroid Ping.

**Comment by mattip** [comment]
> Please change tags from bug, backport-canidate to Anaconda/Intel.

Tags changed. Is there an anaconda issue we can link to?

**Comment by oleksandr-pavlyk** [comment]
No. I will create one though and post a link here.

I doubt the issue has anything to do with the way CPython is compiled by Anaconda, because our recipe is different, and the issue is reproducible with Intel Distribution for Python.

**Comment by mattip** [comment]
@oleksandr-pavlyk any updates to this issue?

**Comment by zooba** [comment]
Sorry I didn't see the original ping.

My guess is that this is (was?) due to the default DLL search order being changed in Anaconda and then inherited by the compiler executables.

Most of MSVC should be fine, but there are a couple of features that may still rely on it (I know PGO profiling is one of them, not sure what else).

So it could either be because Anaconda was calling SetDefaultDllDirectories, or because Anaconda was adding many more directories to PATH. I'm not sure which exactly, as I didn't keep track of the different settings that were included over time.

**Comment by rgommers** [comment]
Python 3.8 is the last Python version where things were in flux in conda defaults/conda-forge regarding DLL paths on Windows. We are dropping Python 3.8 in 2023 (NEP 29 says Apr 14, 2023 is the date, so we may do it for NumPy 1.25.0 or 1.26.0). Given no changes here for 2 years, let's consider this issue non-actionable anymore.

Thanks for the discussion all!
