### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by rutujar** [numpy/numpy#13385]
code:

for (lpBox, chars) in plates:
        # reconstruct lpBox
        lpBox = np.array(lpBox).reshape((-1, 1, 2)).astype(np.int32)

error:

ValueError                                Traceback (most recent call last)
<ipython-input-7-2b9d90a9f412> in <module>
     67     for (lpBox, chars) in plates:
     68         # reconstruct lpBox
---> 69         lpBox = np.array(lpBox).reshape((-1, 1, 2)).astype(np.int32)
     70 
     71         # initialize the text containing the recognized characters

ValueError: setting an array element with a sequence.

**Comment by mattip** [comment]
What is `lpBox` when the error occurs? If it is large, attach a file rather than pasting here.

**Comment by seberg** [comment]
Closing in favor of issue-6584

**Comment by seberg** [comment]
Sorry, gh-6584 of course
