### ISSUE TITLE
Can't import numpy properly on mac os

### ISSUE THREAD

**Issue by mac-os-noob** [numpy/numpy#13398]
`<!--` Please describe the issue in detail here, and fill in the fields below --> I cannot import numpy. I installed and reinstalled it a few times using 

pip install --upgrade --force-reinstall numpy

but nothing works. I also tried adding numpy folder to my PYTHONPATH explicitly, but that didn't work either.  

(i am using numpy together with opencv, and while installing the latter i and to mess with command line per their tutorials)
### Reproducing code example:

```python
import numpy as np

```

### Error message:

 Traceback (most recent call last):
  File "/Users/askhatsarkeev/Library/Python/3.7/lib/python/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/Users/askhatsarkeev/Library/Python/3.7/lib/python/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/askhatsarkeev/Library/Python/3.7/lib/python/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/askhatsarkeev/Documents/Python/exercises/cv_fft.py", line 1, in <module>
    import numpy as np
  File "/Users/askhatsarkeev/Library/Python/3.7/lib/python/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/askhatsarkeev/Library/Python/3.7/lib/python/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/local/opt/python/bin/python3.7),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: PyCapsule_Import could not import module "datetime"

numpy version 1.16.3, python version 3.7

**Comment by matthew-brett** [comment]
What do you get for:

```
python -c 'import datetime'
```

?

How did you install Python?

**Comment by mac-os-noob** [comment]
I installed python using Homebrew (brew install python3). 

When I typed `python -c 'import datetime` in the terminal, nothing happened (no errors)

Thanks for trying to help me, as the username suggests, I don't really know what I'm doing

**Comment by matthew-brett** [comment]
Is that the same Python as you're using above?

What do you get for:

```
python -c 'import numpy'
```

**Comment by mac-os-noob** [comment]
Again, no errors. I do realise that typing that in the terminal should be "equivalent" to typing into IDE, so it seems pretty weird to me that one version works and the other one doesn't.

**Comment by matthew-brett** [comment]
Aha - your error was in an IDE?  Then you may be using a different Python. Which IDE?  How did you install it?  In the IDE, type:

```
import datetime
```

In the IDE, what to you get for:

```
import sys
sys.prefix
```

?

**Comment by mac-os-noob** [comment]
I'm using PyCharm (the free edition). When I am trying to import just datetime in IDE it works, unlike numpy (i just tried again, and it gave error "no module named 'numpy' ")

As for system prefix, I get 

/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7

**Comment by mac-os-noob** [comment]
Hi Matthew, somehow numpy works now (and the rest of the packages such as cv2, matplotlib etc). I have no idea how this happened  - the only thing I did was trying to downgrade to python 3.6 and then going back for 3.7 again. But thank for helping anyway

**Comment by charris** [comment]
ISTR previous reports of this problem with PyCharm, it was some sort of path problem. Anyway, closing as it seems to be working now.

**Comment by Krishnna-desai** [comment]
how to install python in window10

**Comment by mattip** [comment]
@Krishnna-desai this issue is closed. Please open a new one explaining what you tried and why it didn't work.
