### ISSUE TITLE
Cannot create a masked array from ndarray data and Python list mask

### ISSUE THREAD

**Issue by mcara** [numpy/numpy#13410]
This issue arose from exploring https://github.com/numpy/numpy/issues/13408. Masked array creation fails when `data` is a `numpy.ndarray` while `mask` is a Python list.

### Reproducing code example:

```python
import numpy as np 
c = np.ma.array(
    np.array([(1, 3, 5), (2, 4, 6)]), 
    mask=[(True, False, False),  (False, False, False)], 
    dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')]
)
```

### Error message:

```
---------------------------------------------------------------------------
MaskError                                 Traceback (most recent call last)
<ipython-input-174-6b4915bfc205> in <module>
      3                 mask=[( True, False, False),
      4                       (False, False, False)],
----> 5                 dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

~/.../lib/python3.6/site-packages/numpy/ma/core.py in array(data, dtype, copy, order, mask, fill_value, keep_mask, hard_mask, shrink, subok, ndmin)
   6375                        subok=subok, keep_mask=keep_mask,
   6376                        hard_mask=hard_mask, fill_value=fill_value,
-> 6377                        ndmin=ndmin, shrink=shrink, order=order)
   6378 array.__doc__ = masked_array.__doc__
   6379 

~/.../lib/python3.6/site-packages/numpy/ma/core.py in __new__(cls, data, mask, dtype, copy, subok, ndmin, fill_value, keep_mask, hard_mask, shrink, order, **options)
   2863                     msg = "Mask and data not compatible: data size is %i, " + \
   2864                           "mask size is %i."
-> 2865                     raise MaskError(msg % (nd, nm))
   2866                 copy = True
   2867             # Set the mask to the new value

MaskError: Mask and data not compatible: data size is 6, mask size is 2.
```
### Numpy/Python version information:
```
1.16.2 3.6.1 (default, May 18 2017, 16:32:13) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

**Comment by mcara** [comment]
Similarly, swapping location of `np.array` (`data`<->`mask`) produces a similar error:

**Comment by pllim** [comment]
I can confirm that this also happens with Numpy 1.16.3 and the code here does not contradict what API claims to be possible: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.array.html#numpy.ma.array

**Comment by seberg** [comment]
I do not think the issue is what you think it is? If you check the output of when you do not give the mask, you will find that you are getting basically what:
```
np.array(np.array([(1, 3, 5), (2, 4, 6)]), dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])
```
gives, which is:
```
array([[(1, 1, 1), (3, 3, 3), (5, 5, 5)],
       [(2, 2, 2), (4, 4, 4), (6, 6, 6)]],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])
```
and thus not the expected array (what you would get if you do not put in an array already. So the issue here would be that the first array is cast to the new dtype (and this is done by repeating each value), when during coercion from list, the tuples are assigned to different parts of the dtype.

So this is a casting vs. coercion issue, and I am not sure it is too easy to fix. I do not think it has to do anything with masked arrays.

**Comment by mcara** [comment]
Very interesting and thanks for looking into this.
