### ISSUE TITLE
 Feature request: Add one_hot function

### ISSUE THREAD

**Issue by OhadRubin** [numpy/numpy#13419]
It would be nice if numpy had something like tensorflow's tf.one_hot.
I've seen enough implementations to see that most people implement it very naively.

**Comment by seberg** [comment]
It seems to me that in many cases this is much like doing:
```
indices = np.array([0, 1, 2])
depth = 3
val0 = 0
val1 = 1

arr = np.full(indices.shape + (depth,), val0)  # or useing zeros, which has probably no overhead.
np.put_along_axis(arr, indices[..., None], val1, -1)
```
but I guess that is the naive implementation you are alluring too?

I suppose the main discussion here would be whether it is used enough to warrant putting into numpy. If you want to push this, a ping to the mailing list and some more details may be good (I have not used tensorflow or so, so I am not sure right now where this is used regularly).

**Comment by rgommers** [comment]
> 

I suppose the main discussion here would be whether it is used enough to warrant putting into numpy.

**Comment by LukeWood** [comment]
@rgommers do you still consider `np.one_hot()` out of scope?  It seems pretty widely used, maybe the field of ML has grown enough to justify this API?

**Comment by rgommers** [comment]
I still see no point in duplicating what scikit-learn already has, yes. It's specific to ML, and with `numpy` alone you won't be doing ML. So if you use it with scikit-learn, or another library like XGBoost or similar, those will already have it.
