### ISSUE TITLE
TST, BLD: implicit declaration warning -> error

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#13437]
See #10723 for related discussion, and the Travis logs [here](https://travis-ci.org/numpy/numpy/jobs/518651420) for an example by searching for `arraytypes.c.src`

In short, `warning: implicit declaration of function` should probably be turned into a compiler error instead of just a warning. 

In this case, a C function was used before its prototype was included / available, which caused a substantial loss of core dev time due to debugging the strange behavior that ensued.

I think NumPy does have precedent for grepping through compiler warnings and erroring out on a selected subset of them. I believe this happens on some Travis CI runs, and perhaps that would be the most appropriate place for this for now.

I suspect there's probably some way to get gcc to swap that over to an error as well, but not sure we want to go down the rabbit hole of injecting more default compiler flags at this time.

**Comment by rgommers** [comment]
It's editing one line in `tools/travis-test.sh`:
```
# make some warnings fatal, mostly to match windows compilers
werrors="-Werror=vla -Werror=nonnull -Werror=pointer-arith"
```
please add to that rather than grepping a build log.
