### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by OB100** [numpy/numpy#13434]
In the code below, each call to np.arange leaks as one can see when running it. 
Happens in Python 3.6 and 3.7 (both Windows and Linux) but not in Python 2.7.
Numpy version is 1.16.3.

It seems that np.random.shuffle is involved, since when it is removed - the leak stops.

### Reproducing code example:
import numpy as np
from psutil import virtual_memory
N = 1024 * 1024 * 128
print("Initial free memory      :", virtual_memory().free)
for i in range(10):
    A = np.arange(N)
    print("Free memory after arange :", virtual_memory().free)
    np.random.shuffle(A)
    print("Free memory after shuffle:", virtual_memory().free)

### Numpy/Python version information: import sys, numpy; print(numpy.__version__, sys.version):
1.16.3 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]

**Comment by mattip** [comment]
Add a `gc.collect()` in the loop to break reference cycles, then memory use stays approximately constant

**Comment by rgommers** [comment]
indeed. @mattip please feel free to close issues straight away.

**Comment by OB100** [comment]
Oh - ok.
Thanks!
