### ISSUE TITLE
License not detected on repo, and some issues

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#13447]
Our license file contains additions to the standard BSD 3-clause license that make GitHub report it as "other". The GitHub license determination is automatic, and documented at https://help.github.com/en/articles/licensing-a-repository#detecting-a-license.

The advice there is to move complexity like licenses of vendored libraries to README or some other place.

Most vendored things are BSD, however not all. The main issue is `dragon4`, which is a custom non OSI-approved license. This is really not so helpful. On the PR that added it (gh-9941) there a note saying *Please check the license at the top of the dragon4.c file to confirm it is suitable.*. Apparently no one did. This was too hidden in the description, and should not have been merged without explicit review. A bit hard to do much about now ....

Will look into what next.

The mention of Apache 2 is also not helpful, but we should be able to nuke that fairly easily I think, by modifying `scipy-sphinx-theme`.

**Comment by rgommers** [comment]
> This was too hidden in the description, and should not have been merged without explicit review. A bit hard to do much about now ....

For clarification: I think the actual license text is compatible with BSD. The problems are that (a) it's not OSI-approved (and we signed up to only use OSI approved licenses when we joined NumFOCUS) and (b) that any kind of custom license results in much more effort for anyone trying to get NumPy approved for use in a company that does even basic legal due diligence.

I'm playing with the GitHub detection algorithm now.

**Comment by seberg** [comment]
Could we see how to best adapt the dragon4 license and ask the author to re-license it for us?

**Comment by charris** [comment]
> The problems are that (a) it's not OSI-approved

Oh, that's nasty. @seberg\'s suggestion sounds like the best thing if it works.

**Comment by rgommers** [comment]
Okay, there's _very_ little you can deviate before the license checker gets unhappy. Adding a plain BSD license plus 2 blank lines and `See also LICENSES_BUNDLED` works, add a couple more words and BSD license changes to "other".

> Oh, that's nasty. @seberg's suggestion sounds like the best thing if it works.

Yes it would be best. Not holding my breath though, someone else already asked 5 years ago and the guy said it's too much work to set up a repo with a license. But I guess all we need is an email. I will try.

**Comment by mattip** [comment]
Some of the BRNGs in randomgen pr #13163 - [splitmix64](https://github.com/numpy/numpy/pull/13163/files#diff-4e9fa533fb7a54a34bc6819301ea7a20R1), xoroshiro128, xorshift, xoroshiro256starstar and xoroshiro512starstar are licensed [Creative Commons 0 1.0 Universal](http://creativecommons.org/publicdomain/zero/1.0) which is not OSI approved (see https://wiki.creativecommons.org/wiki/CC0_FAQ about half way down) since the OSI does not recommend Creative Commons for code. Is this a problem?

**Comment by rgommers** [comment]
> since the OSI does not recommend Creative Commons for code. Is this a problem?

hmm, I think not really. it's a very common license, and I'm pretty sure we have incorporated more CC0 or other public domain code without listing it explicitly. 

There was also mention of Apache 2 licensed code in that PR. Is that gone now @mattip? (because that would be a problem)

**Comment by mattip** [comment]
There are other brngs in randomgen that are Apache2 licensed: entropy, pcg32, pcg64. Isn't that OK? It is the first license listed under OSI approval https://opensource.org/licenses. In my experience corporate legal approval is easiest to get for the top 3: Apache 2, BSD and MIT, without much preference between them. Some lawyers actually prefer Apache 2 for the patent clause.

**Comment by rkern** [comment]
We've talked about this before: Apache 2 is not GPLv2 compatible, and we want numpy to be GPLv2 compatible.

**Comment by rgommers** [comment]
I've added a blocking review to the randomgen PR about this.

**Comment by rgommers** [comment]
About this issue, this is what I want to do first:

- separate out the listing of bundled bits of code with their own license into a `LICENSE_bundled.txt` file.
- Let `python setup.py sdist` concatenate the two files.

This solves the issue that GitHub doesn't recognize our license. And it's similar to what we already do for wheels (https://github.com/MacPython/numpy-wheels), which contain OpenBLAS for example (GPLv3 + runtime exception).

After that I'll try to contact the dragon4 author.

**Comment by shoyer** [comment]
I'm a little puzzled by GitHub's algorithm here. Including licenses for vendored code in a LICENSE file is totally standard, and GitHub actually seems to be OK with this in some cases, e.g., look at the license for Apache Arrow:
https://github.com/apache/arrow/blob/master/LICENSE.txt

**Comment by shoyer** [comment]
Apparently there's a special exception/bug to this logic for the Apache License: https://github.com/licensee/licensee/issues/234

**Comment by rgommers** [comment]
@shoyer yes I agree, this is just a bit annoying. There's no authoritative reference I could find on how best to deal with distributing multi-license code, however several stackoverflow answers and blogs recommended the way we have it currently.

If GitHub makes an exception for Apache, then why not for BSD? However, even if they're willing to fix it I suspect it will take some time to discuss and implement.

**Comment by rgommers** [comment]
> Apparently there's a special exception/bug to this logic for the Apache License: licensee/licensee#234

after looking into that, it's because the Apache license has a line saying `END OF TERMS AND CONDITIONS`, after which the parsing stops. we can't add that, so I'm not sure it's equivalent.

**Comment by mattip** [comment]
Since #13471 is merged, can we close this?

**Comment by rgommers** [comment]
Not yet. It's fixed in the GitHub API, but the UI still says "view license". I've got a support issue open about flushing the cache so that we get to see the license in the UI too. Then I'll close this.

**Comment by rgommers** [comment]
It was indeed the caching - flushing the cache made it work:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/98330/58588549-31791180-8260-11e9-94bb-ae9e3037235e.png">
