### ISSUE TITLE
numpy.sin(numpy.pi) doesn't return 0

### ISSUE THREAD

**Issue by MateXon** [numpy/numpy#13453]
When running the following:

### Reproducing code example:

```python
import numpy as np

np.sin(np.pi)
```

Instead of getting 0 as a result, I get 1.2246467991473532e-16. This behavior persists when I try any integer multiple of pi.

I'm running numpy ver. 1.16.2 on Python 3.7.3, and I'm using the Anaconda distribution with PyCharm IDE.

**Comment by seberg** [comment]
Thanks for the report. Note that the same is also true for the standard library `pi` function. Floating point numbers are imprecise and you always have to expect slight imprecisions (especially on the order of your results here, comparing it to `pi` the result is a very small precision error (at least compared to `np.pi` as the constant is imprecise as well of course).

Have a look at:
https://en.wikipedia.org/wiki/Double-precision_floating-point_format
https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

if you have some time. If you need higher precision, there are a few options to choose from (mostly outside of numpy itself).
