### ISSUE TITLE
numpy.random.uniform default value low 

### ISSUE THREAD

**Issue by johannes90** [numpy/numpy#13451]
When reading the docu on numpy.random.uniform(low=0.0, high=1.0, size=None)
it says low and high are optional. 
Therefore, I would assume, wenn I just pass one float <high> as an argument, the function would return samples drawn from a uniform distribution \in [0.0,  <high_val>).

But it seems that the default value for <low> is 1.0 instead of 0.0

### Reproducing code example:

```python
import numpy as np
np.random.uniform(1.0)
```

### Numpy/Python version information:

1.15.1 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]

**Comment by mattip** [comment]
The first positional argument goes to `low`, the second to `high`. So `np.random.uniform(1)` sets 'low` to 1 and leaves `high` at 1. The [documentation](http://www.numpy.org/devdocs/reference/generated/numpy.random.uniform.html#numpy.random.uniform) states "When `high == low`, values of low will be returned", so `low` is returned.

**Comment by mattip** [comment]
Closing. If more clarification is needed please reopen with additional information.
