### ISSUE TITLE
Sequence too large 

### ISSUE THREAD

**Issue by andrewnaguib** [numpy/numpy#13450]
I'm trying to create an `ndarray` of a shape `np.repeat(2, K)` where `K` varies from `2` to `2048`.

### Reproducing code example:

```python
import numpy as np
np.full(np.repeat(2, 64), 1, dtype=np.uint8)
```

### Error message:

```
ValueError: sequence too large; cannot be greater than 32
```

### Numpy/Python version information:

```
1.16.2 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] 
```
Additional questions:

* The [following line in NumPy source code](https://github.com/numpy/numpy/blob/b0a52b76c2bebe5c237722589d13bf02affa9c43/numpy/core/include/numpy/ndarraytypes.h#L30)

```C
#define NPY_MAXDIMS 32
#define NPY_MAXARGS 32
```
Why are you limited to this number of dims (i.e., `32`)?

* Is forking the library and allowing it to accept higher dims possible?, is it as simple as changing the aforementioned line?

**Comment by mattip** [comment]
Are you really trying to create a multidimensional array with 64 dimensions or are you trying to create a 2d array with shape `(2,64)` ? A 64 dimensional array will quickly exhaust memory unless most of the dimensions are 1. If your desired shape is indeed (2, 2, 2, .... 2) you will need `2**64` bytes of memory just to store `np.uint8` values, when `2**30` is 1GB.

If you are trying to create a 2 by 64 2-d array of data, you should use `np.ones((2, 64))`

**Comment by seberg** [comment]
Indeed, also note that an array of shape `(2,) * 64` has `2**64` elements, so it is implausibly large in any case.

Increase those constants (at least moderately) should work fine. Might want to increase both at the same time, just to be sure. There is probably some danger of a dark corner in numpy not acting correctly if you do, but overall the only thing that is directly effect is the stack space required probably (so if you increase things a lot, you will run into trouble, I do not know where that would happen).

Honestly, I doubt that is what you want though, or that it is the best solution. Increasing maxargs is a serious request we have, I am not sure I saw a request for increased maxdims before.

**Comment by seberg** [comment]
The error message could probably be improved though.

**Comment by andrewnaguib** [comment]
@mattip Yes. I want to create a multidimensional array with 64 dimensions, this is to save joint distribution of 64 dimension (i.e., the case in a nutshell).

@seberg I will reconsider the case again and see how can I optimize it. Meanwhile, If you have suggestion for a better error message, I could submit a PR for it ([here is the line to be changed](https://github.com/numpy/numpy/blob/dea85807c258ded3f75528cce2a444468de93bc1/numpy/core/src/multiarray/conversion_utils.c#L119)). I suggest:

```
Maximum supported dimension for an ndarray is <<NPY_MAXDIMS>>.
```

**Comment by seberg** [comment]
@andrewnaguib sure, something mentioning the number of dimensions is good. I am not 100% sure that this function may not be used elsewhere. Another nice thing would be to report the actual number given. If you like to improve it, please just open a PR and we can discuss it there.

**Comment by andrewnaguib** [comment]
@seberg Great. I will close this issue. Meanwhile, I will reconsider my experiments and see what would be a possible optimization.
