### ISSUE TITLE
(nan)argmax and (nan)argmin should optionally return a bool array

### ISSUE THREAD

**Issue by Didou09** [numpy/numpy#13454]
Hi, 

I make regular use of the very efficient (nan)argmin and (nan)argmax numpy functions.
I feel having them return an array of bool indices instead of a dimension-reduced array of int indices would be valuable.

Indeed, let's consider a collection of 2D arrays, varying with time along axis 0 and a spatial coordinate (radius) along axis 1:
**data1, data2, data3...**

The spacial coordinate (radius) is itself a 2D array of the same size, because it changes at every time:
**radius**

If I want to get, for each array, its value at the lowest / highest spacial coordinate for each time I have to:
* use argmin / argmax to get the index array **ind** of the min/max coordinate at each time
* use that info to extract the corresponding value from each array

But if the array of indices is returned as int, I have to loop over time for each array (using list comprehension):

```python
import numpy as np
value_of_data1_at_min_radius = np.array([ data1[i, ind[i]] for i in ind ])
```

That implies looping, on a lot of time steps.
This does not feel very right since the key info (**ind**) is computed once and efficiently

If there was an option to return ind as a bool array looping on time would be avoided as applying it directly to each array would be sufficient.

What do you think ?
Thanks

**Comment by seberg** [comment]
There is `np.take_along_axis` (in newer numpy versions) to help you do the indexing operation without list comprehension as far as I can see. If you are on older numpy versions, you could do the same advanced indexing operation yourself. (the idea is to index the first dimension with `np.arange`).

Advanced indexing is tricky though, so if you cannot find what you need, do not hesitate to ask.

**Comment by Didou09** [comment]
Thanks,

I did not know about take_along_axis(), and I do have an older numpy version, so advanced indexing it is (and I wasn't very familiar with advanced integer indexing).

I understand that this would fix it (with nt = size of time):

```python
# indices of minimum radius for each time
ind = np.argmin(radius,axis=1)

# all indices of time
indt = np.arange(0,nt)

# value (vs time) of each array, at minimum radius
value_of_data1_at_min_radius = data1[ indt, ind ]
value_of_data2_at_min_radius = data2[ indt, ind ]
...
```

Thanks very much for your help, I guess there is no need to add this to a wishlist then.
