### ISSUE TITLE
ENH: add divergence, curl, and laplacian to `np.linalg`

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#13459]
There has been the request (in the form of PR gh-6727) to add the linear operators `divergence`, `curl`, and `laplace` to `np.linalg`.

While it probably needs some discussion, the request seems reasonable. However, the PR stalled years ago and still needed quite a lot of work. But, the PR (gh-6727) may in any case provide a basis to pick this up again, and contain valuable discussion.

**Comment by rgommers** [comment]
I think that is out of scope, better for `scipy.linalg`.

**Comment by seberg** [comment]
I am not against closing this, which is why I attached Wish List and not enhancement :)

**Comment by rgommers** [comment]
We meant for wish list to be a higher level thing than enhancement - like "just too small to put on the roadmap, but we want it".

Okay, let's close then. 

Thanks for going through those stalled PRs!
