### ISSUE TITLE
Incorrect "new in version" info in npymath docs.

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#13461]
https://docs.scipy.org/doc/numpy/reference/c-api.coremath.html#half-precision-functions says that half-precision functions were added to npymath in version 2.0.0, but that's clearly not true :)
From https://github.com/numpy/numpy/commit/9b72aa96cec9d182062f378fca869aaa303f1ca9 it looks like this should be 1.6.0.

### Numpy/Python version information:

numpy 1.16 docs.

**Comment by charris** [comment]
That sounds right. It was @mwiebe\'s learning project :)
