### ISSUE TITLE
Too big difference between vectorized and not vectorized operations

### ISSUE THREAD

**Issue by ubbikk** [numpy/numpy#13474]
The following code fails:
### Reproducing code example:

```python
import numpy as np
x=np.load('arr.npy')
a=1-x[0]
b=(1-x)[0]
print(a-b)
assert np.abs(a-b)<1e-10
```

I'm not sure it's a bug but it seems too huge difference (~ 1e-8) 
I've spent several hours debugging my code and got here

### Numpy/Python version information:

1.14.5 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0]

[arr.npy.gz](https://github.com/numpy/numpy/files/3145615/arr.npy.gz)

**Comment by seberg** [comment]
Your array is a float32 array, and one operation casts to float64, the other does not, so errors of that magnitude should be expected, feels a bit large maybe in any case but it is certainly no bug. (That `1-x[0]` casts to float64 may be strange, but the casting rules are known to be strange in places when it comes to scalars and there are issues open about it).
