### ISSUE TITLE
Index array access of MaskedArray is slow

### ISSUE THREAD

**Issue by parejkoj** [numpy/numpy#13488]
Accessing a MaskedArray by index array is much slower than accessing the underlying array. For example:

```
xx=np.random.random(10000)
yy=np.ma.masked_array(xx)
%timeit yy[ind]                                                        
9.85 µs ± 73.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
%timeit xx[ind]                                                        
2.28 µs ± 13.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

I noticed this when using `astropy.table.Table.read` to speed up reading of `.csv` files, instead of `np.genfromtxt`. The data reading portion of the code got faster, but subsequent indexing was much slower. In that case, I can do `np.array(Table.read(file, format='csv').as_array().data`, with no obvious speed loss, but that shouldn't be necessary.

This is with numpy 1.16.2.

**Comment by seberg** [comment]
It feels a bit slow, but frankly, I doubt there is much to do here. Of course we always appreciate speed enhancements, but the MaskedArray code needs to handle some fairly complex things in python, while the normal indexing (in this path) is fairly optimized C code. It may be interesting to do timings of the masked array code, but I expect that this is just the typical overhead you need to expect. E.g. if you fetch 10000 elements with `ind`, the difference gets much closer to what is expected for large arrays.

**Comment by eric-wieser** [comment]
I'm not sure if it's relevant here, but a bunch of time in `MaskedArray` is spent trying to guess whether `arr[ind]` should return a scalar or an array:

https://github.com/numpy/numpy/blob/64b3e6791ff8cc51986b8dfbf5e63643304d2804/numpy/ma/core.py#L3168-L3215

**Comment by seberg** [comment]
Oh man, that is ugly logic... Good reason for exposing whether or not the result is a expected to be a scalar from the indexing machinery (especially assuming I manage to move forward the `oindex`, etc. stuff in the nearer future).

**Comment by rgommers** [comment]
PRs to improve performance or to improve functionality/maintainability of `numpy.ma` (or other parts of numpy) are always welcome. However, there's nothing particularly surprising reported here - `numpy.ma` is written in pure Python and deserves some maintenance in general, we know that. So I'll close the issue, given that there is no bug or very egregious issue.

Thanks all!
