### ISSUE TITLE
Ubuntu import issue in dynamic library

### ISSUE THREAD

**Issue by darknoon** [numpy/numpy#13484]
When I try to import the numpy extension within my C++ code on linux, I get an "undefined symbol" error. It's working OK on macOS.

I'm using CMake to build a node.js extension that links agains Python (works fine), and then loads the numpy extension. When I built a regular executable with a .cpp file, importing numpy worked fine.

I'm guessing something about the linker flags is wrong in my configuration, could someone point me in the right direction?

### Reproducing code example:

I made a Dockerfile on [this branch](https://github.com/darknoon/node-embed-python/tree/docker-test
) that reproduces my environment, including how I installed numpy. 

Reproduce with:
```
git clone --branch docker-test https://github.com/darknoon/node-embed-python
docker build --tag node-embed-python -f docker/Dockerfile .
docker run --rm -it node-embed-python yarn test
```

### Error message:

> Python: 
> 
>   IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> …
> 
> Original error was: /usr/local/lib/python3.6/dist-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError

### Numpy/Python version information:

```
root@257b38495d01:/src# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.random.randn(4)
array([-1.1923296 , -1.24721901, -1.04530495,  0.22025358])
>>> np.__version__
'1.16.3'
```

**Comment by seberg** [comment]
OK, I am not sure what is going on or have dug into it. But the symbol you are missing is a python symbol, so are you are sure you compiled it with the same python version you are running on and that nothing went wrong in the linking step? (maybe check `ldd /usr/local/lib/python3.6/dist-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so` or so). It almost certainly is not an issue with numpy, but with the installatio/building itself.

**Comment by darknoon** [comment]
@seberg yes, I'm sure I compiled it with the same python version. I am able to call into python functions fine, the only issues happen when trying to load the numpy dynamic library. It seems that the symbol lookup is different when numpy is getting loaded within an executable vs when I'm doing it in a dynamic library. I am less familiar with `rpath` on linux compared to macOS, perhaps that is the issue?

I'm looking for the correct linking flags for my binary to get numpy to be able to find the python symbols. Currently, it's compiled with:

```
-g -fPIC   -std=gnu++11
```

and linked with 

```
-Wl,-rpath,/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.so
```

here is the output of `ldd` on the numpy shared library:
```
root@7f01f5692bfd:/src# ldd /usr/local/lib/python3.6/dist-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffcc03f4000)
        libopenblasp-r0-382c8f3a.3.5.dev.so => /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libopenblasp-r0-382c8f3a.3.5.dev.so (0x00007fd27c92a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd27c58c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd27c36d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd27bf7c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd27ec8c000)
        libgfortran-ed201abd.so.3.0.0 => /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0 (0x00007fd27bc82000)
```


<details><summary><code>ldd</code> on the python3 binary</summary>

```
root@7f01f5692bfd:/src# ldd /usr/bin/python3
        linux-vdso.so.1 (0x00007ffdc8586000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd7ff899000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd7ff67a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd7ff476000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fd7ff273000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fd7ff041000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd7fee24000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd7fea86000)
```

</details>


<details><summary><code>ldd</code>on my binary</summary>

```
root@7f01f5692bfd:/src# ldd build/Debug/node-embed-python.node 
        linux-vdso.so.1 (0x00007ffd74be0000)
        libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007f1458241000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1457eb8000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1457ca0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f14578af000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f145767d000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1457460000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1457241000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f145703d000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f1456e3a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1456a9c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1458b12000)
```

</details>




<details><summary><code>ldd</code>on the node binary</summary>

```
root@7f01f5692bfd:/src# ldd /usr/bin/node
        linux-vdso.so.1 (0x00007ffca7dcf000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f52b0428000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f52b0220000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f52afe97000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f52afaf9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f52af8e1000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f52af6c2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f52af2d1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f52b062c000)```

</details>

**Comment by mattip** [comment]
does the solution in the [comment](https://github.com/numpy/numpy/issues/13717#issuecomment-499042465) on #13717 help?

**Comment by rgommers** [comment]
no further follow-up and not a NumPy bug, so closing
