### ISSUE TITLE
Problem building numpy with intel compiler and msvc

### ISSUE THREAD

**Issue by r-mike** [numpy/numpy#13481]
I am having problems building numpy from source with a intel compiler on windows. According to [this] link I can compile and install numpy with the following command (x86). 
```
python setup.py config --compiler=intelw build_clib --compiler=intelw build_ext --compiler=intelw install
```
But the build fails with the following error:
```
error: Microsoft Visual C++ 14.1 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```
This is strange, since I have installed the latest v141 and v140 toolset. 
I started the debugger and figured out, that I can solve this problem by replacing the msvc compiler in numpy.distutils.msvc9compiler (line 4) with the newer one.
```Python
from distutils.msvc9compiler import MSVCCompiler as _MSVCCompiler
```
to 
```Python
from distutils._msvccompiler import MSVCCompiler as _MSVCCompiler
```
Additionaly I updated the find_exe() calls in numpy.distutils.intelccompiler. 
Is this an issue or did I miss something? According to the following description the distutils._msvccompiler should replace the older distutils.msvc9compiler. 
```Python
"""distutils._msvccompiler

Contains MSVCCompiler, an implementation of the abstract CCompiler class
for Microsoft Visual Studio 2015.

The module is compatible with VS 2015 and later. You can find legacy support
for older versions in distutils.msvc9compiler and distutils.msvccompiler.
"""
```

### Numpy/Python version information:
I have installed Microsoft Visual Studio 2017 Professional (v15.9.11)
I have also built python 3.7.3 from source [MSC v.1916 32 bit (Intel)]. 
I am using the latest numpy version.

[this]: https://software.intel.com/en-us/articles/building-numpyscipy-with-intel-mkl-and-intel-fortran-on-windows

**Comment by charris** [comment]
Could you make a PR with these fixes? Also, which numpy version, python version are you compiling. Note that we are dropping the older MSVC compiler versions in master as we need good C99 support. I'm not clear on the exact versions we support at this point except >= 2015.

**Comment by r-mike** [comment]
I have created PR https://github.com/numpy/numpy/pull/13492
With this changes I am still having an error later in the build with npymath: 
```numpy\core\src\npymath\npy_math_private.h(521): error: identifier "_complex" is undefined.```
Currently I think this is just a problem with the include paths on my side. I will look into this later.
I am compiling python version:
```3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]```
Numpy version:
```1.17.0.dev0+808bdcf```

**Comment by mattip** [comment]
Can you confirm that #13492 solves all the build problems?

**Comment by r-mike** [comment]
Unfortunately not. I am still having issues building `npy_math.c`. The build fails with an error: 
```
numpy\core\src\npymath\npy_math_private.h(511): error: identifier "_complex" is undefined
          complex double c99_z;
          ^
```
I am not sure if this is a problem with my setup or because of the changes to `numpy.distutils._msvccompiler`. I will investigate further into this.

**Comment by ohanar** [comment]
I've successfully built the 1.16.x branch with the intel compiler + msvc. The thing missing here is that you also have to set the environment variables DISTUTILS_USE_SDK=1 and MSSdk=1, otherwise distutils will try to import the msvc environment, overwriting some of intel's environment (which is what is causing the _complex undefined errors).

That said, I haven't been able to successfully build the 1.17.x with the intel compiler (on either windows or linux).

**Comment by rgommers** [comment]
We switched build systems from `numpy.distutils` to Meson, and hence this issue is no longer relevant. Building with Intel compilers should work fine now.

Thanks all.
