### ISSUE TITLE
Duplicate axis in tuple are not allowed when doing arithmetic operation

### ISSUE THREAD

**Issue by andrewnaguib** [numpy/numpy#13480]
### Reproducing code example:

```python
import numpy as np
z = np.ones((2, 3, 4))
z.sum((0, 0, 0))
```

### Error message:

```
ValueError: duplicate value in 'axis'
```

Even though I could do:

```Python
z.sum(0, keepdims=True).sum(0, keepdims=True).sum(0, keepdims=True)
```

This happens to be caused by [this snippet](https://github.com/numpy/numpy/blob/8db1b077736e8418c60f2b802dab461be13f189d/numpy/core/src/multiarray/conversion_utils.c#L265-L280).

```C
            PyObject *tmp = PyTuple_GET_ITEM(axis_in, i);
            int axis = PyArray_PyIntAsInt_ErrMsg(tmp,
                          "integers are required for the axis tuple elements");
            if (error_converting(axis)) {
                return NPY_FAIL;
            }
            if (check_and_adjust_axis(&axis, ndim) < 0) {
                return NPY_FAIL;
            }
            if (out_axis_flags[axis]) {
                PyErr_SetString(PyExc_ValueError,
                        "duplicate value in 'axis'");
                return NPY_FAIL;
            }
            out_axis_flags[axis] = 1;
```

I'm not sure why do you prevent duplicate axis?
### Numpy/Python version information:

```
1.16.2 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
Not that it answers your question, but `a.sum((x, y, z))` is (aside from forbidding duplicates) equivalent to `a.sum(x, keepdims=True).sum(y, keepdims=True).sum(z, keepdims=True)`, not `a.sum(x).sum(y).sum(z)`.

**Comment by andrewnaguib** [comment]
@eric-wieser Aw, I see. It was a false positive alarm; I will edit the issue. I said so because both ways in the following snippet are generating the same output
```
z = np.ones((2, 3, 4, 5, 6))
z.sum((4, -4, -3 , 0)) == z.sum(4).sum(-4).sum(-3).sum(0)
```

**Comment by eric-wieser** [comment]
As for the actual question - I think we prevent duplicate axes to protect the user from doing something they didn't mean to. Using the same axis twice in a reduction is a little weird, and certainly not the common case.

If you're currently using `arr.sum(list_of_axes)`, and it's failing, then you can use `arr.sum(set(list_of_axes))` to make sure this check if never hit. In some ways that's a good thing, as it encourages you to explain in your code _why_ you expect to have duplicates.

**Comment by andrewnaguib** [comment]
Thank you, it's much more clear now :) I will close the issue.
