### ISSUE TITLE
Value Error while apply np.vactorize to np.array with dtype=object

### ISSUE THREAD

**Issue by Max16hr** [numpy/numpy#13494]
Given is a numpy array with `dtype=object`. I want to map a function on that array, that will replace every value with a list of values. This raises an error `ValueError: setting an array element with a sequence` although it is possible to set some lists to the array by direct assignment.

### Reproducing code example:

```python
import numpy as np

# Define a random array 'a' with dtype 'object'.
a = np.pi * np.random.rand(3, 2).astype(object)
tmp = a[0, 0]

# No problem to set any list to 'a'.
a[0, 0] = [1, 1.5]
print(a)

# Reset 'a'.
a[0, 0] = tmp
print(a)

# Map a function on 'a' with np.vectorize.
vectorize = np.vectorize(lambda x: [np.cos(x), np.sin(x)])
vectorize(a) # <-- error
print(a)

```

### Error message:

```
Traceback (most recent call last):
  File "~.py", line 17, in <module>
    vectorize(a)
  File "C:\Program Files\Python\Python_3.7.3\lib\site-packages\numpy\lib\function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Program Files\Python\Python_3.7.3\lib\site-packages\numpy\lib\function_base.py", line 2170, in _vectorize_call
    res = array(outputs, copy=False, subok=True, dtype=otypes[0])
ValueError: setting an array element with a sequence.
```

### Numpy/Python version information:

Python 3.7.3
Numpy 1.16.3

**Comment by seberg** [comment]
It won't be very fast (and I am suprised I had to add the `np.asarray` call, but you can get what you want, you just need to have a careful look at the documentation and provide `otypes`:

`vectorize = np.vectorize(lambda x: [np.cos(x), np.sin(x)], otypes=(np.float64, np.float64))`

Or possibly use the `signature` kwarg (had to add an `np.asarray` call:

`vectorize = np.vectorize(lambda x: np.asarray([np.cos(x), np.sin(x)]), signature="()->(2)")`

If you have more questions, please do not hesitate to ahead and ask, I am happy to reopen. But it seems to me not like an issue but really a help request at the moment, so will close this.
