### ISSUE TITLE
BUG: exp and log cast float16 to float32

### ISSUE THREAD

**Issue by toslunar** [numpy/numpy#13493]
After #13134 is merged, `np.exp` and `np.log` return float32 arrays for float16 inputs.  Is the change intended?  I could not find docs for it (https://www.numpy.org/devdocs/reference/generated/numpy.exp.html), while it is documented that `np.sum` casts ints to the default platform integer.

### Reproducing code example:

```python
import numpy as np
print(np.exp(np.array([1, 2], np.float16)).dtype)  # => float32
print(np.log(np.array([1, 2], np.float16)).dtype)  # => float32
```

### Numpy/Python version information:

```
1.17.0.dev0+64b3e67 3.7.1 (default, Nov  6 2018, 21:02:07)
[Clang 10.0.0 (clang-1000.10.44.4)]
```

**Comment by charris** [comment]
Looks like an unintended change. @r-devulap @mattip Thoughts? Maybe we need some tests...

**Comment by mattip** [comment]
Adding tests and looking for a fix

**Comment by r-devulap** [comment]
Looking into it ..

**Comment by seberg** [comment]
I am sure you already got it, but it will be because of the linear search of the loops, if the "f,f->f" loops are registered first, they are found instead of the "e,e->e" loops.

**Comment by seberg** [comment]
Sorry for the spam. (compare also `np.sqrt` which currently has a funny loop duplication, but not this issue).

**Comment by mattip** [comment]
I thought changing the type to `TD('f', astype={'e':'f'}, simd=[('avx2', 'f'), ('avx512f', 'f')])` (adding the astype kwarg) would have solved it, but the test is still failing. Somehow the `simd` part is not respecting the `astype`

**Comment by mattip** [comment]
Got it, need to **not** use simd on 'e' which makes sense

**Comment by r-devulap** [comment]
that was quick! thank you @mattip :)
