### ISSUE TITLE
"Modulus" refers to normalizing by largest singular value in docs

### ISSUE THREAD

**Issue by arvoelke** [numpy/numpy#13497]
https://github.com/numpy/numpy/blob/33415905e85c51c3348c1def9dfa306fbd358b5e/numpy/linalg/linalg.py#L1903-L1904

^ This code from master corresponds to the documentation for [numpy.linalg.pinv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.pinv.html?highlight=modulus):

> Singular values smaller (in modulus) than _rcond * largest_singular_value_ (again, in modulus) are set to zero.

Note that singular values cannot be complex. They are always real and non-negative. And so this is a confusing use of the term "modulus" to me. From what I can see, the singular values are normalized by the largest value. For example, if `s = [2. 1. 0.]` and `rcond = 1e-15`, then `cutoff = 2e-15` and so `s > cutoff` is effectively normalizing `s` by the largest singular value (2) before comparing to `rcond` (i.e., by cross-multiplying).

https://github.com/numpy/numpy/blob/33415905e85c51c3348c1def9dfa306fbd358b5e/numpy/linalg/linalg.py#L1968-L1969

Perhaps I misunderstand the usage of this term, but I think it would be more appropriate to say something like...?

> Singular values smaller than rcond (normalized such that the largest singular value is one) are set to zero.

**Comment by charris** [comment]
I think you are correct. Would you like to submit a PR making corrections?

**Comment by arvoelke** [comment]
Sure! I realized after that my suggestion isn't perfect because of the degenerate case of all zero singular values, but I'll put something quick together.
