### ISSUE TITLE
Update mailmap for 1.17.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#13509]
Mailmap needs updating for the 1.17 release. Could the following folks reply here with an official name and email address?

- [x] @adeak
- [ ] @euronion
- [x] @kikocorreoso
- [x] @psschand
- [x] @spacescientist
- [x] @vrindaaa

TIA, Chuck (the release manager)

**Comment by adeak** [comment]
Is it enough if I say you can use my credentials as per commit 28211265d903df95fd4a1c41798061329351fa96 in master? I can also be more explicit if necessary but I figure scrapers are less of an issue this way :)

**Comment by charris** [comment]
@adeak We can make an exception if the contributor really, really wants it, but the name and a valid address serves both as verification of the contributor and a way to reach them if needed. Your commit address is `adeak <adeak@users.noreply.github.com>`, which is not the best for communication :)

**Comment by adeak** [comment]
@charris All my locally made commits (with a weird exception from January) have proper credentials, according to the git log only a recent squashed merge commit has my dummy github data. Anyway:
`Andras Deak <deak.andris@gmail.com>`

The reason I have the dummy credentials set up is that creating github gists uses that, and I don't want my email address spread all over the place for throwaway code snippets I might show random strangers. Of course for proper open-source contributions I want to and have to assign my identity to my work.

**Comment by charris** [comment]
@adeak Thanks, I see your other commits now. Mailmap will put all the variations under one name.

**Comment by psschand** [comment]
SuryaChand P  / psschand@gmail.com

**Comment by spacescientist** [comment]
Please use @spacescientist (`aspacescientist@protonmail.com`). Thank you.

**Comment by charris** [comment]
As complete is it looks like it will get, so closing.
