### ISSUE TITLE
Numpy with multithreading process with openBlas in Redhat linux 7.4 version and Anacoda Python 3.6.5

### ISSUE THREAD

**Issue by krishm228** [numpy/numpy#13505]
Problem Statement: we would like to enable numpy with multithreading process with openBlas in Redhat linux 7.4 version and Anacoda Python 3.6.5 (/opt/anaconda3)but unable to achieve it.Could you please help us with  exact location to place the site.cfg file and also help us in providing /testing the steps for multithreading using numpy

The following steps has been executed 

1)After installing  OpenBLAS under default /opt directory we have uninstall existing numpy using pip (pip uninstall numpy)
2) Then created a file .numpy-site.cfg in root home directory with the following content:
 [default]
include_dirs = /opt/OpenBLAS/include
library_dirs = /opt/OpenBLAS/lib

[openblas]
openblas_libs = openblas
include_dirs = /opt/OpenBLAS/include
library_dirs = /opt/OpenBLAS/lib

[lapack]
lapack_libs = openblas

[atlas]
atlas_libs = openblas
libraries = openblas

3)Then install numpy again (pip install numpy)

4)configuration details as shown below.where library_dirs is pointing to '/usr/local/lib' instead '/opt/OpenBLAS/lib'
  
 command tested :python -c "import numpy; print(numpy.__config__.show())"

o/p:

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None

5) Then we have tested mulithread scenario using the following 
  
 5.1) single thread-- OMP_NUM_THREADS=1 python testmultithread.py

o/p:  version: 1.16.3
maxint:  9223372036854775807

BLAS info:
 * libraries ['mkl_rt', 'pthread']
 * library_dirs ['/opt/anaconda3/lib']
 * define_macros [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
 * include_dirs ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

dot: 1.804373 sec

5.2 )Multi Thread --OMP_NUM_THREADS=2 python testmultithread.py
version: 1.16.3
maxint:  9223372036854775807

BLAS info:
 * libraries ['mkl_rt', 'pthread']
 * library_dirs ['/opt/anaconda3/lib']
 * define_macros [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
 * include_dirs ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

dot: 1.011364 sec

As shown above in the output ,we couldn't see multithreading using OpenBlas and using TOP command we could see only one PID process

Thanks in Advance

**Comment by mattip** [comment]
You can query any of the OpenBlas [extension functions] using ctypes, or use the [threadpoolctl](https://github.com/joblib/threadpoolctl) package.

**Comment by rgommers** [comment]
The question was answered, and we've switched build systems in the meantime. So I'll close this - thanks all.
