### ISSUE TITLE
ENH: confirm accuracy of basic math functions

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13515]
We do not verify results of our math functions (sin, cos, exp, log, ...) against a "gold standard" which makes changing the algorithms used to calculate them tricky. Python has a [tests](https://github.com/python/cpython/blob/v3.7.3/Lib/test/math_testcases.txt) based on generating "true" values for certain interesting cases. We should explore adding these kinds of tests for the various built-in float and integer types, perhaps [mpmath](http://mpmath.org/) could help generate the "true" values.

**Comment by mattip** [comment]
See also this [email thread](https://mail.python.org/pipermail/python-dev/2012-September/121645.html) from 2012 with the author of the python test files on using mpfr to calculate the results

**Comment by seberg** [comment]
Not sure it is relevant, but there was also just this to do testing for scipy on scipy-dev: https://mail.python.org/pipermail/scipy-dev/2019-May/023508.html

**Comment by juliantaylor** [comment]
glibc has a testsuite for math functions which could be used as input for what is interesting to test:
https://github.com/lattera/glibc/blob/master/math/README.libm-test

**Comment by mattip** [comment]
Python  has a test suite for complex numbers when testing [cmath](https://github.com/python/cpython/blob/v3.7.3/Lib/test/test_cmath.py) based on a [text file of results](https://github.com/python/cpython/blob/v3.7.3/Lib/test/cmath_testcases.txt), we should be consistent with these results or document why we differ.

**Comment by r-devulap** [comment]
PR #14048 addressed this issue for float32 exp, log, sin and cos.

**Comment by r-devulap** [comment]
PR #19485 can hopefully close this issue?

**Comment by mattip** [comment]
Closing, we now have better accuracy tests
