### ISSUE TITLE
Feature request: Add tau constant

### ISSUE THREAD

**Issue by leventis** [numpy/numpy#13511]
This is a request to add the [constant](https://www.numpy.org/devdocs/reference/constants.html#module-numpy.doc.constants) [`tau`](https://tauday.com/).

### Reproducing code example:

```python
import numpy as np
>>> np.tau
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'numpy' has no attribute 'tau'
>>> np.version.version
'1.15.3'
```

**Comment by eric-wieser** [comment]
Already rejected in #9696
