### ISSUE TITLE
"Working with NumPy source code" - mention relevance to SciPy?

### ISSUE THREAD

**Issue by mdhaber** [numpy/numpy#13536]
[Working with NumPy Source Code](https://docs.scipy.org/doc/numpy/dev/gitwash/index.html) is a valuable reference for both NumPy and SciPy developers. 

Unfortunately, it doesn't mention "SciPy"/`scipy` at all (as some joint documents, like [NumPy/SciPy Testing Guidelines](https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt) and [NumPy Distutils - Users Guide](https://github.com/numpy/numpy/blob/master/doc/DISTUTILS.rst.txt) do), so _new_ SciPy developers don't know how relevant it is. 

One thought is to change the title to:
"Working with NumPy/SciPy source code"
and to adjust the [introduction](https://docs.scipy.org/doc/numpy/dev/gitwash/git_intro.html):

> These pages describe a git and github workflow for the NumPy and SciPy projects. They were originally written in the context of NumPy, but may be applied to SciPy by replacing all instances of "NumPy"/`numpy` with "SciPy"/`scipy`."

(If you can think of any instances where "SciPy"/`scipy` isn't a drop-in replacement, please let me know. I would also modify the text to call those out.)

Thoughts? If it sounds OK, I can submit a PR.

**Comment by rgommers** [comment]
> Working with NumPy Source Code is a valuable reference for both NumPy and SciPy developers.

Please use the [latest version](https://www.numpy.org/devdocs/dev/index.html) of that, it's significantly improved from the version you're linking to.

> Thoughts? If it sounds OK, I can submit a PR.

I'm not sure if all the NumPy devs will be happy with that. If not, we can just copy it over. Some extra work, but easier for readers in the end.

**Comment by mdhaber** [comment]
I guess I'll copy them over.
