### ISSUE TITLE
document or fix unpackbits performance regression

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#13537]
https://github.com/numpy/numpy/pull/12962 removed the lookup table for unpack bits causing a factor 8 performance regression:

```
       before           after         ratio
     [08b17aee]       [e6227a03]
     <v1.16.3^0>       <master>  
+      5.80±0.5μs         46.4±1μs     8.00  bench_core.UnpackBits.time_unpackbits
+         120±2μs         911±20μs     7.58  bench_core.UnpackBits.time_unpackbits_axis1

```

While the function is probably not that critical for performance the change is of rather large magnitude and should probably be added to the release notes.

As for fixing to simplify the code one could just bitswap the data, well performing functions for that could be generally useful and might even be worth exposing (e.g. blosc has code for that).

**Comment by juliantaylor** [comment]
If you want to restore the performance, I can create a PR for it.

**Comment by eric-wieser** [comment]
This came up in the sprint yesterday, I think there was no awareness of just how great the slowdown was. There was a previous revision of the `bitorder` PR that used two lookup tables.

**Comment by juliantaylor** [comment]
Yes I saw the PR and the discussion. Unfortunately I did not see it at the time or I could have answered some questions about it.
But a discussion whether the extra code is worth the extra complexity might be a good idea.
I do think it is ok as the speedup is significant, lookup tables are not uncommon optimizations, the tests are quite thorough and we also have extended the use cases of the function with the bitorder flag.

@mattip as you worked on the code, do you have an opinion on whether the lookup table should be kept or not?

**Comment by mattip** [comment]
I think it makes sense to restore a single lookup table and `npy_bswap8` the input before the lookup if needed. Sorry for not measuring. I am working on a PR

**Comment by juliantaylor** [comment]
no don't bother I can do so.
I already tested using one lookup table its about 80% slower than two tables.

**Comment by juliantaylor** [comment]
imo 2 lookup tables makes the code simpler than converting from one as you have the order check in only one spot instead of 8 places.
it costs us 2kb of memory if the functions are used but that is pretty insignificant for numpy runtime.

**Comment by mattip** [comment]
OK, thanks
