### ISSUE TITLE
Redundant Parentheses with Return Statements in numpy/linalg/lapack_lite/f2c.c

### ISSUE THREAD

**Issue by hdamron17** [numpy/numpy#13543]
According to the [NumPy C Style Guide](https://www.numpy.org/devdocs/dev/style_guide.html),

> The return statement should not get redundant parentheses:
> ```
> return Py_None; /* correct */
> return(Py_None); /* incorrect */

However, the file `numpy/linalg/lapack_lite/f2c.c` violates this rule 22 times. This file seems to be the only violation of the rule in all .c and .h files within the repository.

I am willing to make these changes if they are deemed necessary.

Output of `find . \( -name "*.c" -o -name "*.h" \) | xargs grep "return("`:
```
./numpy/linalg/lapack_lite/f2c.c:	return((float)real);
./numpy/linalg/lapack_lite/f2c.c:return(temp);
./numpy/linalg/lapack_lite/f2c.c:	return((double)real);
./numpy/linalg/lapack_lite/f2c.c:return(temp);
./numpy/linalg/lapack_lite/f2c.c:return(z->i);
./numpy/linalg/lapack_lite/f2c.c:return(z->i);
./numpy/linalg/lapack_lite/f2c.c:return( log10e * logf(*x) );
./numpy/linalg/lapack_lite/f2c.c:return( log10e * log(*x) );
./numpy/linalg/lapack_lite/f2c.c:return( *b >= 0.0f ? x : -x);
./numpy/linalg/lapack_lite/f2c.c:return( *b >= 0 ? x : -x);
./numpy/linalg/lapack_lite/f2c.c:return( (*x)>=0 ?
./numpy/linalg/lapack_lite/f2c.c:return(pow(*ap, *bp) );
./numpy/linalg/lapack_lite/f2c.c:return(pow);
./numpy/linalg/lapack_lite/f2c.c:return(pow);
./numpy/linalg/lapack_lite/f2c.c:			return( *a - *b );
./numpy/linalg/lapack_lite/f2c.c:			return( ' ' - *b );
./numpy/linalg/lapack_lite/f2c.c:			return( *a - *b );
./numpy/linalg/lapack_lite/f2c.c:			return(*a - ' ');
./numpy/linalg/lapack_lite/f2c.c:return(0);
./numpy/linalg/lapack_lite/f2c.c:return( f__cabsf( z->r, z->i ) );
./numpy/linalg/lapack_lite/f2c.c:return( f__cabs( z->r, z->i ) );
./numpy/linalg/lapack_lite/f2c.c:	return(pow);
```

**Comment by seberg** [comment]
Sure, woukd be OK to change as a style fix. there may be many other things there, in that case could do that as well if you are touching things...

we do not necessarily clean up very old files unlrss there is some bigger change, but nothung wrong with it.

**Comment by eric-wieser** [comment]
Isn't that a generated/vendored file?

**Comment by seberg** [comment]
Yeah, sorry, was on the phone when i wrote that. We should not modify vendored files for such things...
