### ISSUE TITLE
OpenBlas - Numpy setup -Library_dirs Path issue- RHEL7.4

### ISSUE THREAD

**Issue by krishm228** [numpy/numpy#13545]
Using the following link tried to setup Numpy with OpenBlas
https://stackoverflow.com/questions/11443302/compiling-numpy-with-openblas-integration

The configuration  using command **python setup.py config** as shows below  as per the above link specified
 
setup.py:417: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
Running from numpy source directory.
Cythonizing sources
numpy/random/mtrand/randint_helpers.pxi.in has not changed
numpy/random/mtrand/mtrand.pyx has not changed
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

After numpy installation

Numpy config shows as follows

import numpy as np;
np.config.show()
blas_mkl_info:
NOT AVAILABLE
blis_info:
NOT AVAILABLE
openblas_info:
libraries = ['openblas', 'openblas']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
libraries = ['openblas', 'openblas']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
NOT AVAILABLE
openblas_lapack_info:
libraries = ['openblas', 'openblas']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
libraries = ['openblas', 'openblas']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None)]

Library_dirs is not pointing to /opt/OpenBlas/lib ...How to resolve this ??
I have updated paths of  library_dirs in site.cfg and .numpy-site.cfg  as /opt/OpenBlas/lib...

Thanks in advance

**Comment by krishm228** [comment]
Further 
python setup.py config
----------------
setup.py:417: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
Running from numpy source directory.
Cythonizing sources
numpy/random/mtrand/randint_helpers.pxi.in has not changed
numpy/random/mtrand/mtrand.pyx has not changed
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

**Comment by krishm228** [comment]
could someone please help as soon as possible..

**Comment by mattip** [comment]
Is the problem that numpy is built with OpenBLAS but you would like it to use the one in `/opt/OpenBlas/lib` not `/usr/local/lib` ?

**Comment by krishm228** [comment]
@mattip ,thanks for your response . you are correct. we would like to use /opt/OpenBlas/lib. Just incase, If that doesn't require then how can we confirm OpenBlas is working for numpy ?

**Comment by mattip** [comment]
Your choice of which `*.so` is used is a runtime-configuration option, not a buld-time one, so the various cfg files will not help. Things like `LD_LIBRARY_PATH` and `ldconfig` can help set the search order, and tools like `ldd` and `strace` can verify what is happening.

You can confirm that you are using OpenBLAS with python code like this, since only if you are using OpenBLAS will `get_config` work.

```
import numpy, ctypes, os
dll = ctypes.CDLL(numpy.core._multiarray_umath.__file__)
get_config = dll.openblas_get_config
get_config.restype=ctypes.c_char_p
res = get_config()
print('OpenBLAS get_config returned', str(res))
```

**Comment by krishm228** [comment]
@mattip , Thanks for your help, I will evaluate using the above script provided, Could you Please help in providing latest document/information or steps to implement numpy with OpenBlas on RHEL 7.4 ...I will cross verify each step from my end in case of any gaps.

**Comment by mattip** [comment]
You should check what your OS packager uses to build the numpy package. I don't use RHEL 7.4.

**Comment by krishm228** [comment]
@mattip , I have got  following output after running above specified code .
Output:
OpenBLAS get_config returned b'OpenBLAS 0.3.5.dev DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64'

Is that confirms OpenBlas is being used for Numpy ?

**Comment by krishm228** [comment]
> Your choice of which `*.so` is used is a runtime-configuration option, not a buld-time one, so the various cfg files will not help. Things like `LD_LIBRARY_PATH` and `ldconfig` can help set the search order, and tools like `ldd` and `strace` can verify what is happening.
> 
> You can confirm that you are using OpenBLAS with python code like this, since only if you are using OpenBLAS will `get_config` work.
> 
> ```
> import numpy, ctypes, os
> dll = ctypes.CDLL(numpy.core._multiarray_umath.__file__)
> get_config = dll.openblas_get_config
> get_config.restype=ctypes.c_char_p
> res = get_config()
> print('OpenBLAS get_config returned', str(res))
> ```

@mattip , I have got following output after running above specified code .
Output:
OpenBLAS get_config returned b'OpenBLAS 0.3.5.dev DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64'

Is that confirms OpenBlas is being used for Numpy ?

**Comment by krishm228** [comment]
> Is the problem that numpy is built with OpenBLAS but you would like it to use the one in `/opt/OpenBlas/lib` not `/usr/local/lib` ?

Just wondering why library_dirs is not pointing to /opt/OpenBlas/lib.any potential settings to be checked here  ? could you please help @mattip

**Comment by krishm228** [comment]
> > Your choice of which `*.so` is used is a runtime-configuration option, not a buld-time one, so the various cfg files will not help. Things like `LD_LIBRARY_PATH` and `ldconfig` can help set the search order, and tools like `ldd` and `strace` can verify what is happening.
> > You can confirm that you are using OpenBLAS with python code like this, since only if you are using OpenBLAS will `get_config` work.
> > ```
> > import numpy, ctypes, os
> > dll = ctypes.CDLL(numpy.core._multiarray_umath.__file__)
> > get_config = dll.openblas_get_config
> > get_config.restype=ctypes.c_char_p
> > res = get_config()
> > print('OpenBLAS get_config returned', str(res))
> > ```
> 
> @mattip , I have got following output after running above specified code .
> Output:
> OpenBLAS get_config returned b'OpenBLAS 0.3.5.dev DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64'
> 
> Is that confirms OpenBlas is being used for Numpy ?

@mattip : When we are testing with following code snippet, still we could see o/p with mkl_rt?  Could you please let me know if any changes are require to  use as OpenBlas?
--------------------------------------------------------------------code starts -----------------
#!/usr/bin/env python
import numpy
from numpy.distutils.system_info import get_info
import sys
import timeit

print("version: %s" % numpy.__version__)
print("maxint:  %i\n" % sys.maxsize)

info = get_info('blas_opt')
print('BLAS info:')
for kk, vv in info.items():
    print(' * ' + kk + ' ' + str(vv))

setup = "import numpy; x = numpy.random.random((5000, 5000))"
count = 10

t = timeit.Timer("numpy.dot(x, x.T)", setup=setup)
print("\ndot: %f sec" % (t.timeit(count) / count))

-------------------------------------------------------code ends ---------------------
command :OPENBLAS_NUM_THREADS=4 python multithread.py
O/P: 
version: 1.16.3
maxint:  9223372036854775807

BLAS info:
 * libraries ['mkl_rt', 'pthread']
 * library_dirs ['/opt/anaconda3/lib']
 * define_macros [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
 * include_dirs ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

dot: 1.794868 sec

---------------------

**Comment by mattip** [comment]
The linalg backend (MKL, OpenBLAS or others) is frozen at compile time to one option, you cannot change that without recompiling.

It seems we have transitioned into general questions which might be better handled on StackOverflow.

**Comment by rgommers** [comment]
Questions were answered, I'll close this issue. Thanks all.
