### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by zxleegit** [numpy/numpy#13556]
### Reproducing code example:

```python
int main(int argc, char* argv[])
{
		Py_Initialize();
		PyRun_SimpleString("import numpy as np");
		Py_Finalize();
		return 0;
}
```

### Error message:
Traceback (most recent call last):
  File "D:\Python37\Lib\site-packages\numpy\core\__init__.py", line 40, in <module>
    from . import multiarray
  File "D:\Python37\Lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "D:\Python37\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python37\Lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "D:\Python37\Lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

### Numpy/Python version information:

python version 3.7.1 
numpy version 1.16.3
vs2017 debug

**Comment by utsavdahiya** [comment]
How did you solve this?

**Comment by spartha77** [comment]
I too had the same problem. I solved it.
My problem statement: (Windows)

-> I had installed Python3.5 at C:\Python35, 
-> I invoked Python and ran "import numpy" 
It gave rise to similar problem.
<< I then realized that the numpy installation was at C:\Users\partha3x\AppData\Roaming\Python\Python37\site-packages\numpy\core\ and NOT from the path I had mentioned at the time of installation. 
-> So, I modified (re-installed) python at the user profile home directory.
-> The home profile directory is 
C:\Users\partha3x\AppData\Local\Programs\Python\Python37
->Uninstalled the numpy 
->Re-installed numpy
With this "import numpy" call succeeded in python 

With Visual Studio 2019, I had the same problem. I followed the following steps
-> Uninstalled all Pythons that which were installed using VIsual Studio installer. (Not sure if this step helped me)
-> In the project properties, in which I was invoking Python (embedded Python) from C++ project, I had set additional Libraries ( Project properties->Linker->General->Additional Library Directories I added C:\Users\partha3x\AppData\Roaming\Python\Python37\site-packages\numpy\core\lib AND -> In the project properties -> Linker->Input->Additional Dependencies , I added npymath.lib.

These fixed the issues. 

In Linux, similar to the project properties, the files have to be compiled with additional dependencies with additional directories using make files.

Hope this helps.

**Comment by sourabhgupta811** [comment]
@zxleegit @spartha77 @utsavdahiya I am stuck on the same problem. I am using vs 2019 and I tried the above solution and added the respective library and dependency path under Linker. But the issue still remains. Please help me with it.
I am using Python 3.7.9 and numpy version 1.19.1

**Comment by mattip** [comment]
This issue is closed. @sourabhgupta811 if you are having problems installing/using NumPy please open a new issue and describe it from the beginning.
