### ISSUE TITLE
ImportError: No module named 'kiwisolver'

### ISSUE THREAD

**Issue by karshan77** [numpy/numpy#13594]
Hi,

I am getting the error when I'm executing the command `python3 legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config`.

So, I have tried to install kiwisolver by following command `pip3 install kiwisolver`. Even though the error not getting resolved. So, I went checked into the kiwisolver installed directory. Only one directory is available in the name "kiwisolver-1.1.0.dist-info". No kiwisolver librarries has been installed. How to install kiwisolver properly?

I am working on ubuntu 16.04.

Thanks.

**Comment by mattip** [comment]
This is the numpy issue tracker, perhaps ask on [their issue tracker](https://github.com/nucleic/kiwi) instead

**Comment by karshan77** [comment]
sure @mattip . Thank you.
