### ISSUE TITLE
Minor documentation error in np.take_along_axis

### ISSUE THREAD

**Issue by javidcf** [numpy/numpy#13598]
There is a minor mistake in the documentation of [`np.take_along_axis`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.take_along_axis.html). In the "Notes" section there is a snippet functionally equivalent to the function that begins with:

```python
Ni, M, Nk = a.shape[:axis], a.shape[axis], a.shape[axis+1:]
J = indices.shape[axis]  # Need not equal M
out = np.empty(Nk + (J,) + Nk)
```

As I understand it, the definition of `out` should be:

````python
out = np.empty(Ni + (J,) + Nk)
````

With the initial `Nk` replaced by `Ni`.

### Reproducing code example

NA

### Error message

NA

### Numpy/Python version information:

1.16.1

**Comment by seberg** [comment]
Looks right, thanks. Want to create a PR to fix it? For such small things, the edit button on the file on github is even fine.
