### ISSUE TITLE
Segfault after loading pickled void objects

### ISSUE THREAD

**Issue by balodja** [numpy/numpy#13593]
The title is self sufficient. I'm getting segmentation faults after unpickling void numpy objects. That's quite easy to reproduce.

### Reproducing code example:

To reproduce the bug two steps a needed. At first dump the void object:
```python
import pickle
import numpy as np

dt = np.dtype([('name', 'O')])
a = np.empty(1, dtype=dt)
a['name'] = 'eman'

with open('b.pickle', 'wb') as file:
    pickle.dump(a[0], file)
```

Then try to load and print the pickled object from *another* interpreter:
```python
import pickle
print(pickle.load(open('b.pickle', 'rb')))
# Segmentation fault here
```

### Error message:
I'm typing the GDB traceback here.

```
Starting program: /home/balodja/tmp/tmpenv/bin/python a.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4df8700 (LWP 19796)]
[New Thread 0x7ffff45f7700 (LWP 19797)]
[New Thread 0x7ffff1df6700 (LWP 19798)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff6fdfd78 in PyArray_Item_INCREF (data=0xc57570 "\340\065\a\034S\177", descr=0x7fffec232150) at numpy/core/src/multiarray/refcount.c:39
39      numpy/core/src/multiarray/refcount.c: No such file or directory.
```

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.16.3 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0]
```

**Comment by eric-wieser** [comment]
This only happens when the void type contains objects, right?

**Comment by seberg** [comment]
I think the bug is actually in the void pickling. The array correctly checks that it cannot do a simple pickle operation, but it will create a list of void objects instead. And those fail the pickling.

**Comment by seberg** [comment]
Hmm, no, that was wrong I think. Maybe I am missing something earlier on, but it seems to me it should be converting to a list, which should be converting the items to tuples, which I guess is should be fine. Right now I am not quite sure why it even calls into `PyArray_Item_INCREF`, but have to dig some more later probably.

**Comment by charris** [comment]
Pushing this off to 1.17.2 (if it happens).

**Comment by charris** [comment]
What do we want to do about this?

**Comment by mattip** [comment]
Calling pickle on `a[0]` currently encodes the object's pointer as bytes:
```
>>> a = np.array([(bytearray(b'abcdef'),)], dtype=[('name', 'O')])
>>> a[0].__reduce__()
(<built-in function scalar>, (dtype([('name', 'O')]), b'\xf0qq\xf0\xff\x7f\x00\x00'))
```
The code in `gentype_reduce` to pickle a scalar *does* check for an object dtype, but *not* for a dtype containing an object. The parallel code in `array_reduce` will check that the dtype has the NPY_LIST_PICKLE flag and build a proper value for the pickle.

So step 1 is to add code to check the dtype's flags for NPY_LIST_PICKLE, and if so create something similar to what `array_reduce` produces:
```
>>> r = a[0].__reduce__()
>>> r
(<built-in function scalar>, (dtype([('name', 'O')]), (bytearray(b'abcdef'),)))
```

However, that brings us to step 2 which is to load this pickle, we need to reconstitute it:
```
>> r[0](*r[1])
TypeError: initializing object must be a string
```
So `scalar` (which internally is `array_scalar`) also needs to learn to handle void dtypes.
