### ISSUE TITLE
ImportError：cannot map zero-fill pages: Invalid argument

### ISSUE THREAD

**Issue by haveonename** [numpy/numpy#13607]
### Error message:
Traceback (most recent call last):
  File "hdret.py", line 36, in <module>
  File "hdret.py", line 9, in dedupAndCom
  File "/home/hdret/PyInstaller-3.4/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "common/DDPCompress.py", line 4, in <module>
  File "/home/hdret/PyInstaller-3.4/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "common/Estimate.py", line 5, in <module>
  File "/home/hdret/PyInstaller-3.4/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "common/MultiProcessEstimate.py", line 22, in <module>
  File "/home/hdret/PyInstaller-3.4/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "algorithm/dedup_estimation.py", line 6, in <module>
  File "/home/hdret/PyInstaller-3.4/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/numpy/__init__.py", line 142, in <module>
  File "/home/hdret/PyInstaller-3.4/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/numpy/core/__init__.py", line 71, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /vmfs/volumes/582ad7ca-e2b4da5a-3468-200bc71fec7d/clh/usenumpy.3/hdret),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /tmp/_MEI27doMp/numpy.core._multiarray_umath.so: cannot map zero-fill pages: Invalid argument

### Numpy/Python version information:

Pyhton：2.7.9
Numpy:1.16.1 and 1.16.3

**Comment by mattip** [comment]
googling the error, it could be due to a VM running out of memory or a buggy gcc 4.6 compiler. How are you installing numpy into your machine? I am intrigued by `sys.executable` reporting `/vmfs/volumes/582ad7ca-e2b4da5a-3468-200bc71fec7d/clh/usenumpy.3/hdret` as a python executable, that seems like a trucated string which would support the out-of-memory premise.

**Comment by bbbbbbbbba** [comment]
Sounds like a frozen python application to me...

**Comment by haveonename** [comment]
I packaged my Python program into executable files on the Red Hat 6.8 system(gcc version 4.4.7 ), and then ran the packaged files on the Esxi5.5 system (hdret is my executable file). This error occurred. In addition, I have increased the memory of the esxi system to 10GB.And the system temporary directory (/tmp) has been modified to other larger directories.

**Comment by haveonename** [comment]
> that seems like a trucated string which would support the out-of-memory premise.

I installed it in "pip install numpy-xxx.whl" mode; The  "/vmfs/volumes/582ad7ca-e2b4da5a-3468-200bc71fec7d/clh/usenumpy.3/" is the Running Path of the executable file .

**Comment by mattip** [comment]
What happens when you do not package the app, or when you use system-provided python packages instead of compiling your own?

**Comment by haveonename** [comment]
According to my test, the unpackaged situation can run, and it can run on RedHat and SUSE systems after packaging, but this error will occur on Esxi system;  I also want to know how much memory ‘numpy’ needs after I start the packaged program, this program only uses the phrase 'import numpy'. Maybe that's the problem.

**Comment by seberg** [comment]
Closing as it is a 3 year old installation/build problem possibly related to frozen build.  Followups welcome (e.g. as a new issue or just here).
