### ISSUE TITLE
ndarray.require: missing return value documentation

### ISSUE THREAD

**Issue by henon** [numpy/numpy#13608]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.require.html

The docs say "returns an array ... " but the return value is not documented.

**Comment by seberg** [comment]
Sounds right, it should have the Returns section. Do you want to make a PR to add it? You can even use the edit button on the file on github. A good commit message would be appreciated.

**Comment by pmk21** [comment]
Hello @seberg. New to contributing here, I would like to fix this.

**Comment by seberg** [comment]
@pmk21 please just do. You may want to have a look at http://www.numpy.org/devdocs/dev/index.html and possibly the documentation of how to document: http://www.numpy.org/devdocs/docs/index.html. We do not typically assign issues (it may happen sometimes, but that is usually a core dev marking it so they do not forget it).
