### ISSUE TITLE
BUG: np.arange() returns unexpected result

### ISSUE THREAD

**Issue by Clarmy** [numpy/numpy#13613]
### Reproducing code example:
According to np.arange's docstring, np.arange's result won't incluede the stop value. But in practice, sometimes the result includes the stop value.

The example:
```python
In [1]: import numpy as np
In [2]: np.arange(112.8,112.9,0.01)
Out[2]:
array([112.8 , 112.81, 112.82, 112.83, 112.84, 112.85, 112.86, 112.87,
       112.88, 112.89, 112.9 ])
```
The result should exclude the last element: `112.9`.

### Error message:
No error message.

### Numpy/Python version information:
1.16.2 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

**Comment by rkern** [comment]
The docstring does note that in the case of floating point arguments, it sometimes will end with a value `>=` the given stop value.

**Comment by Clarmy** [comment]
> The docstring does note that in the case of floating point arguments, it sometimes will end with a value `>=` the given stop value.

Thank you. Is there any way to know when does it happen and how to avoid it?

**Comment by charris** [comment]
The problem is that the numbers you use for the limits and step are not exactly represented by IEEE floating point numbers, so the computations are not what you expect. The `np.linspace` function is generally more satisfactory for these cases.

**Comment by Clarmy** [comment]
@charris  Thank you.
