### ISSUE TITLE
np.round(0.5) returns 0.0

### ISSUE THREAD

**Issue by terrancewong** [numpy/numpy#13614]
```
In [7]: np.round(0.5)
Out[7]: 0.0

In [8]: np.version.full_version
Out[8]: '1.16.2'

In [9]: np.version.git_revision
Out[9]: '0eeb158ead494e130a25239ac8473a06451b1072'
```

**Comment by charris** [comment]
That's correct, NumPy rounds to even.

**Comment by tanguyduval** [comment]
This behaviour can cause big anomalies when dealing with fixed point numbers (even and odd numbers are not equiprobable)... should be solved.

**Comment by rkern** [comment]
We're comfortable with the current behavior. It's a quite standard and defensible default for floating point arithmetic. It's not the right thing to do in every possible application, like the one that you mentioned, but those are more specific, and you can implement what you want in those cases.

**Comment by tanguyduval** [comment]
Thanks @rkern, I agree now.

For tracability, the reason of this behavior is to prevent statistical bias: rounding to even has the property to round up as often as it rounds down. Rounding to upper value has an upper statistical bias.
On the other hand, even values are over-represented..

In my case I prefer the second behavior, so with my fixed floating point I just add a tiny number before rounding.

**Comment by terrancewong** [comment]
This is quite "engineering round" instead of "mathematical round", that's my point. 
Although something.5 could extremely rare be exactly something.50000000000000000000000000000000000 in IEEE754

**Comment by eric-wieser** [comment]
Note that even python's `round` does this:
```python
>>> round(0.5)
0
```


> Although something.5 could extremely rare be exactly something.50000000000000000000000000000000000 in IEEE754

Nope, the closest `double` it can get is `0.5000000000000001` (which is the output of `np.nextafter(0.5, float('inf'))`)

**Comment by terrancewong** [comment]
meh, try 1.5

**Comment by terrancewong** [comment]
no hope.
