### ISSUE TITLE
Importing the multiarray numpy extension module failed. No module named _multiarray_umath

### ISSUE THREAD

**Issue by shashank-kv** [numpy/numpy#13612]
I have uninstalled, reinstalled numpy but still nothing seems to be working. Can someone help me with this?

**Comment by mattip** [comment]
We can only begin to help if you provide the information requested. Please read the error message and the text in the new issue template, and post here the required texts.

**Comment by lordoftheseas** [comment]
'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "CWAnalyzerGUI.py", line 28, in <module>
    from chipwhisperer.common.ui.CWMainGUI import CWMainGUI, makeApplication
  File "/Users/shashankkv/chipwhisperer/software/chipwhisperer/__init__.py", line 1, in <module>
    from chipwhisperer.capture.api.acquisition_controller import AcquisitionController
  File "/Users/shashankkv/chipwhisperer/software/chipwhisperer/capture/api/acquisition_controller.py", line 27, in <module>
    from chipwhisperer.common.utils import util
  File "/Users/shashankkv/chipwhisperer/software/chipwhisperer/common/utils/util.py", line 31, in <module>
    import numpy as np
  File "/usr/local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named _multiarray_umath


This is the entire error message.

**Comment by abhinavsagar** [comment]
You have 2 options
- uninstall numpy and lnstall the latest version ie 1.16
- uninstall numpy and use conda install numpy

**Comment by mattip** [comment]
You are using `/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python`, but importing `/usr/local/lib/python3.7/site-packages/numpy`. This would seem to indicate you are using **python2.7.16**, and importing a version of numpy for **python3.7**. Are you somehow setting `PYTHONPATH` or changing `sys.path` to point to `/usr/local/lib/python3.7`?

**Comment by lordoftheseas** [comment]
@abhinavsagar I have uninstalled and reinstalled several times. @mattip when I printed sys.path I got the following output

/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/usr/local/lib/python3.7/site-packages
/usr/local/lib/python3.7/site-packages
/usr/local/lib/python3.7/site-packages
/usr/local/lib/python3.7/site-packages
/usr/local/lib/python3.7/site-packages
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Users/shashankkv/Library/Python/2.7/lib/python/site-packages
/Users/shashankkv/chipwhisperer/software
/Users/shashankkv/Library/Python/2.7/lib/python/site-packages/pyusb-1.0.2-py2.7.egg
/Users/shashankkv/Library/Python/2.7/lib/python/site-packages/docutils-0.14-py2.7.egg
/Users/shashankkv/Library/Python/2.7/lib/python/site-packages/pyserial-3.4-py2.7.egg
/Users/shashankkv/Library/Python/2.7/lib/python/site-packages/configobj-5.0.6-py2.7.egg
/Users/shashankkv/Library/Python/2.7/lib/python/site-packages/six-1.12.0-py2.7.egg
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

**Comment by mattip** [comment]
Note all the `/usr/local/lib/python3.7/site-packages` in your `sys.path`. That is wrong. Where is it coming from? What happens when you print `os.environ.get('PYTHONPATH')` and/or `os.environ.get('PYTHONSTARTUP')`?

**Comment by lordoftheseas** [comment]
It prints None for both

**Comment by mattip** [comment]
something is messing with `sys.path`, you need to find that and remove it.

**Comment by lordoftheseas** [comment]
Could you guide me a little more on how to go about it?

**Comment by mattip** [comment]
not really, sorry, it could be almost anything.

**Comment by matthew-brett** [comment]
Have a look at https://stackoverflow.com/a/28433195 for some hints on how to get started debugging sys.path.
