### ISSUE TITLE
incorrect indexing example in documentation 

### ISSUE THREAD

**Issue by henon** [numpy/numpy#13611]
The second example at [Combining index arrays with slices](https://docs.scipy.org/doc/numpy/user/basics.indexing.html?highlight=slice#combining-index-arrays-with-slices) is incorrect as you can see below. Here is the example again:

```python
>>> y[b[:,5],1:3]
array([[22, 23],
       [29, 30]])
```

and this is what really happens:

```python
>>> import numpy as np
>>> y = np.arange(35).reshape(5, 7)
>>> b = np.array([[True, True, False], [False, True, True]])
>>> y[b[:,5],1:3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 5 is out of bounds for axis 1 with size 3
>>>```

**Comment by seberg** [comment]
Thanks! The example uses the previously `b = y > 20` instead of that definition of `b`. Would you like to create a small PR to update the documentation? That would be very much appreciated!

**Comment by shreyateeza** [comment]
@seberg I would like to work on this issue.

**Comment by mattip** [comment]
Welcome. We do not assign issues, please follow the [developement workflow](http://www.numpy.org/devdocs/dev/index.html) and issue a pull request. You may find the [documentation about the documentation](http://www.numpy.org/devdocs/docs/index.html) helpful.

**Comment by oribro** [comment]
Hi,
This is my first commit here on numpy and I'll appreciate any feedback.
Sorry @shreyateeza, I assumed you left it for now.
Thanks in advance

**Comment by seberg** [comment]
Fixed in gh-13621.
