### ISSUE TITLE
apply_along_axis with keepdims argument

### ISSUE THREAD

**Issue by agamemnonc** [numpy/numpy#13615]
It seems that `apply_along_axis` implicitly reduces the dimensionality.

Would it be possible to support an additional argument `keepdims` to choose whether to keep the original dimensionality or not?

**Comment by eric-wieser** [comment]
Are you sure you need it? You can achieve the same effect by just keeping the axis within your function:
```python
>>> a = np.zeros((3, 4, 5))
>>> np.apply_along_axis(lambda x: x[0], 1, a).shape
(3, 5)
>>> np.apply_along_axis(lambda x: [x[0]], 1, a).shape
(3, 1, 5)
>>> np.apply_along_axis(lambda x: x[:1], 1, a).shape
(3, 1, 5)
```

**Comment by agamemnonc** [comment]
Thanks.

However, I am not sure how this solution can be used to write code that supports both cases (i.e. `keepdims=True` and `keepdims=False`) based on the user's input?

**Comment by eric-wieser** [comment]
> based on the user's input 

That's not `apply_along_axis`'s concern, that's the problem of the function that it calls. For example:
```python
def do_sum_a_dumb_way(a, keepdims):
    return np.apply_along_axis(lambda x: np.sum(x, keepdims=keepdims), 1, a).shape
```

Without seeing your intended use case, it's difficult to know what you're asking for here.

**Comment by agamemnonc** [comment]
Something like the following:

```python
import numpy as np

def func_1d(a):
    """Some complicated function that only works in 1-d.
    
    Let's assume that the following function is impossible to compute in 2-d
    or higher.
    """
    if a[0] + a[1] < 2:
        return a[2]
    else:
        return a[3]

a = np.random.randn(10,2)
np.apply_along_axis(lambda x: func_1d, 0, a).shape # (2,)
np.apply_along_axis(lambda x: [func_1d], 0, a).shape # (1, 2)
```

Now, would it be possible to write a function `func_nd()` that does that with an input argument `keepdims`? One obvious solution would be:
```python
def func_nd(a, keepdims):
    """Compute ```func_1d``` in higher dimensions with the option of keeping
    the original dimensionality.
    """
    if keepdims:
        return np.apply_along_axis(lambda x: [func_1d], 0, a).shape # (1, 2)
    else:
        return np.apply_along_axis(lambda x: func_1d, 0, a).shape # (2,)
```

However, would it be possible to avoid the `if` statement?

If `apply_along_axis` supported `keepdims`, it would also be possible to avoid the requirement for using  a `lambda` expression.

**Comment by mhvk** [comment]
@agamemnonc - I think with @eric-wieser that this still has to be the function's choice. In particular, I think `keepdims` would be a strange addition in that it would only hold if the function returned a scalar, yet `apply_along_axis` is very much written with the idea that the function can return an answer with any dimension it wants:
```
a = np.zeros((3, 4, 5))
np.apply_along_axis(lambda x: np.zeros((2, 2)), 1, a).shape
# (3, 2, 2, 5)
```
I think one is better off just writing a function like you have, or, perhaps better since more function-agnostic, one that checks the shape of the result afterwards and inserts a new axis at the right position (e.g., with `np.expand_dims`)

**Comment by agamemnonc** [comment]
> @agamemnonc - I think with @eric-wieser that this still has to be the function's choice. In particular, I think `keepdims` would be a strange addition in that it would only hold if the function returned a scalar, yet `apply_along_axis` is very much written with the idea that the function can return an answer with any dimension it wants:

OK, agreed.

> 
> ```
> a = np.zeros((3, 4, 5))
> np.apply_along_axis(lambda x: np.zeros((2, 2)), 1, a).shape
> # (3, 2, 2, 5)
> ```
> 
> I think one is better off just writing a function like you have, or, perhaps better since more function-agnostic, one that checks the shape of the result afterwards and inserts a new axis at the right position (e.g., with `np.expand_dims`)

Thanks, that's what I have been doing, I was just wondering if there is a more elegant solution than this.

**Comment by mhvk** [comment]
>  I was just wondering if there is a more elegant solution than this.

Always good to ask! Many times there is.
