### ISSUE TITLE
Wilcoxon Sign Rank with Pratt for dealing with ties

### ISSUE THREAD

**Issue by jlmeunier** [numpy/numpy#13618]
scipy.stats.wilcoxon offers 3 alternatives to deal with ties.

One is "pratt" and it behaves strangely: the pvalue goes to 0 when one adds ("enough") ties to a balanced number of wins and losses. 

Since Pratt designed this method to deal with ties, I'm really surprised by its behavior.

Anyone more knowledgeable than me to tell if the implementation has an issue, or if this is what one must expect?

Thanks,

JL Meunier

### Reproducing code example:
import scipy.stats
scipy.stats.wilcoxon([1]*5+[0]*40+[-1]*5, zero_method="pratt")
""" WilcoxonResult(statistic=227.5, pvalue=7.443261472320598e-05)"""

""" should be 1.0, because both are clearly equal"""

"""like "zplitt" says:"""
scipy.stats.wilcoxon([1]*5+[0]*40+[-1]*5, zero_method="zsplit")
"""WilcoxonResult(statistic=637.5, pvalue=1.0)"""

""" the number of ties is causing this problem:"""
scipy.stats.wilcoxon([1]*5             +[-1]*5, zero_method="pratt")
""" WilcoxonResult(statistic=27.5, pvalue=1.0)"""

"""above 18 ties, things go badly with Pratt method"""
scipy.stats.wilcoxon([1]*5+[0]*18+[-1]*5, zero_method="pratt")
"""WilcoxonResult(statistic=117.5, pvalue=0.05029433145349)"""

### Numpy/Python version information:

1.16.2 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
You should report this at the scipy tracker, not this one. @rgommers, does the "transfer issue" button work for you as a member of both projects?

**Comment by jlmeunier** [comment]
Sorry, following a link I ended storing an issue with numpy. My mistake anyway. 
I'll make an issue on scipy. Thanks.
