### ISSUE TITLE
ndarray behaving differently for big-endian architecture

### ISSUE THREAD

**Issue by shahidhs-ibm** [numpy/numpy#13638]
ndarray is giving different results on big-endian architectures (s390x Vs Intel), possibly a bug in ndarray implementation for big-endian architectures.

### Reproducing code example:

On Intel:
```
>>> import numpy as np
>>> z = np.ndarray(shape=(), buffer=np.array([1,2,3]), dtype=np.int32)
>>> z
array(1, dtype=int32)
```

On s390x:
```
>>> import numpy as np
>>> z = np.ndarray(shape=(), buffer=np.array([1,2,3]), dtype=np.int32)
>>> z
array(0, dtype=int32)
```

### Numpy/Python version information:
```
>>> import sys, numpy;
>>> print(numpy.__version__, sys.version)
1.16.3 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
```

**Comment by matthew-brett** [comment]
Your code is asking Numpy to make an int32 scalar where the underlying memory is made from three float64s.  So, the scalar is a view onto the first 32 bits of a float64, of value 1.   What you get depends on the bit pattern for float64 1.0, which can differ for big and little endian: https://stackoverflow.com/questions/9056373/what-is-the-difference-between-big-and-little-endian-floats#9056399

**Comment by shahidhs-ibm** [comment]
@matthew-brett Agreed that this difference in the result is due to endianness, however, isn't this something that needs to be handled in numpy itself? Numpy do not support the big-endian architecture?

**Comment by mattip** [comment]
you have to be explicit if you want to round-trip consistently across different architectures.
```
np.ndarray(shape=(), buffer=np.array([1,2,3], dtype='<i8'), dtype='<i4')
```

**Comment by matthew-brett** [comment]
Numpy does deal with endian issues for standard high-level use, but you are trying to do something rather odd, which is to force Numpy to interpret the first part of the memory of an array with one data type as a different data type.    In that case, @mattip is exactly right, if you want numpy to interpret some raw memory for you, you have to tell it the format of that memory.

**Comment by shahidhs-ibm** [comment]
@mattip @matthew-brett I am facing this issue in TensorFlow code. In TensorFlow issue [#11431](https://github.com/tensorflow/tensorflow/issues/11431#issuecomment-328455666) I addressed the issue with same resolution. 
However now in another issue [#28114](https://github.com/tensorflow/tensorflow/issues/28114#issuecomment-495285144) this solution is not feasible as TensorFlow code has some strict dtype checks which fails in other tests if dtype is changed.
If we could handle the differences in numpy itself (by adding byteswap) and generate uniform results across different architectures, that will be great! 
Please let me know your thoughts. Any pointers highly appreciated!

**Comment by charris** [comment]
Numpy is doing *exactly* what it is documented to do, nor do I think it should be changed. The endianess problem is in your code. Perhaps you should explain what you are trying to do at a higher level so that we could suggest other approaches that you might use. Why, for instance, are you using the buffer protocol?

**Comment by mattip** [comment]
You can detect machine-endian with `sys.byteorder`, and use `arr.byteswap` to switch when needed. NumPy will not add this for you, you need to decide when it is appropriate

**Comment by eric-wieser** [comment]
@matthew-brett: I think you mean `int64` not `float64`

**Comment by seberg** [comment]
Indeed, I will close this (but please feel free to discuss or ask to reopen if we are missing something). But you are directly using commands that go down to the machine representation, so they *have to* give such different results. `np.ndarray` is a very low level access and should only be used if you are fully aware of the in-memory representation, etc.

**Comment by seberg** [comment]
If an array may have the wrong datatype and you want to cast it, the typical thing would be to use:

```
arr.astype(np.int32, copy=False)
```
possibly adding `casting="safe"` or `casting="same_kind`", or the equivalent `np.asarray`/`np.array` calls.

**Comment by mattip** [comment]
why not `arr.view()` ?

**Comment by seberg** [comment]
`view` should be preferred over `np.ndarray`, but I thought the issue here was to use value-based casting and not memory interpretation?

**Comment by matthew-brett** [comment]
@eric-wieser - oops - yes - I do mean int64, thanks.

```
[ins] In [4]: np.array([1,2,3]).dtype                                                                                                            
Out[4]: dtype('int64')
```

**Comment by shahidhs-ibm** [comment]
Thanks for the help and pointers. The problem is that TensorFlow code prefers int32 and float32 (TF [#14017](https://github.com/tensorflow/tensorflow/issues/14017#issuecomment-356549090)). The places where TF code uses default data type i.e. int64 and float64, the difference in results due to big vs little endian causes test failures.
We have fixed the big vs little endian differences at the library side in past so wanted to check if that can be done at numpy too.

**Comment by seberg** [comment]
Numpy provides the tools to do byte swapping, but you will have to explain more what you think can possibly change within numpy, since I think we all feel that what is happening is exactly what should happen right now.
