### ISSUE TITLE
DOC: missing return value documentation for matrix_rank and tensordot

### ISSUE THREAD

**Issue by henon** [numpy/numpy#13630]
I am generating a C# API for NumPy called [NumSharp](https://github.com/SciSharp/NumSharp) from the Numpy docs using our specialized [code generator](https://github.com/SciSharp/CodeMinion) for that task. This way I am finding lots of inconsistencies or bugs. Here is what I found:

* [np.linalg.matrix_rank](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.matrix_rank.html)
* [np.linalg.tensordot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tensordot.html)

are both missing a return value documentation

**Comment by eric-wieser** [comment]
I'm not sure I'd consider this a bug. The docstring is "returns ...", putting this in a special section seems like overkill.

It seems to me you'd be better served by type annotations - have you looked at parsing our stubs instead?

**Comment by charris** [comment]
I think it should have the standard return section.
