### ISSUE TITLE
np.zeros(10, dtype=[]) calls malloc(0)

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13645]
... and `malloc(0)` is implementation-defined. This works fine on my machine, but may throw an exception on other machines.

This happens via `PyDataMem_NEW`, so we at least have a point we can intercept this. We should probably do one of:
* Ensure that `PyDataMem_NEW(0)` is never called (and perhaps make it fail on all platforms to make this detectable)
* Special-case `PyDataMem_NEW(0)` to mean `PyDataMem_NEW(1)`, so that it the allocation always succeeds
* Do the above conditionally on feature-detection of `malloc(0) == NULL` performed in `configtest`, to avoid the cost of the conditional on platforms with the version of `malloc` which is convenient for us.

There are probably a few places where there is a similar problem with `PyDataMem_RENEW(ptr, 0)`, except that does the wrong thing on all platforms

**Comment by mattip** [comment]
Closing, fixed by #13691 which both asserts `!=0` and fixes all the places it could be called.

**Comment by eric-wieser** [comment]
We probably want to add a test for this somewhere, since that PR does not.

**Comment by mattip** [comment]
All the code paths in the PR show 100% coverage, implying they are tested, which is why I did not require additional tests before merging. Although one more test could not hurt.
