### ISSUE TITLE
problem with apply_along_axis with flatnonzero

### ISSUE THREAD

**Issue by jrm346** [numpy/numpy#13651]
Hi,

I'm having problems with apply_along_axis used in conjunction with flatnonzero. I'm trying to take one dimension of my array, which is a bunch of 0s and 1s and replace it with the indices where there is a 1. To do this i want to apply faltnonzero on the last dimension but when i do this I get inconsistent results. 

```python
>>>x
array([[1, 0],
       [0, 1]])
>>>numpy.apply_along_axis(numpy.flatnonzero, -1, x)
array([[0],
       [1]], dtype=int64)  # <-------- This is what i want
>>>z
array([[0, 0],
       [1, 0]])
>>>numpy.apply_along_axis(numpy.flatnonzero, -1, z)
array([], shape=(2, 0), dtype=int64)  # <--------- should be array([[],[0], dtype=int64)
>>>y
array([[1, 0],
       [0, 0]])
>>>numpy.apply_along_axis(numpy.flatnonzero, -1, y)  # <-------- gives an error!!!
Traceback (most recent call last):
  File "C:\Users\abaka\Anaconda3\envs\nlu_dev\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\abaka\Anaconda3\envs\nlu_dev\lib\site-packages\numpy-1.16.3-py3.6-win-amd64.egg\numpy\lib\shape_base.py", line 403, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
ValueError: could not broadcast input array from shape (0) into shape (1)
```

Is this a bug in numpy or am i doing something stupid?

**Comment by seberg** [comment]
Numpy does not support ragged arrays (arrays without a clear n-dimenisonal shape). You can use the nozero function and try to work with that output. It will give you the positions in n-dimensions. Or work with an array of array objects (or a list of arrays).

The output that you are looking for cannot be represented as a single numpy array, which is why you have these problems.

**Comment by jrm346** [comment]
Ok. thanks for the speedy response. Unfortunate that there's no easy way to do this in numpy. I looked in to using nonzero but honestly it was a lot more straight forward to just iterate of the dimensions of the array I wanted with some for loops. Thanks anyway.
