### ISSUE TITLE
BUG: can_cast inconsistent with as_type for structured types

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#13667]
In #6053, the behaviour of structured dtypes was changed to generally work by position, not by name. However, it seems `can_cast` was not updated accordingly:
```
np.can_cast('f8,i8', [('f0', 'f8'), ('f1', 'i8')])
# True
np.can_cast('f8,i8', [('f1', 'f8'), ('f0', 'i8')])
# False
np.can_cast('f8,i8', [('f1', 'i8'), ('f0', 'f8')])
# True

a = np.array([(1.234, 10)], 'f8,i8')
a.astype([('f0', 'f8'), ('f1', 'i8')])
# array([(1.234, 10)], dtype=[('f0', '<f8'), ('f1', '<i8')])
a.astype([('f1', 'f8'), ('f0', 'i8')])
# array([(1.234, 10)], dtype=[('f1', '<f8'), ('f0', '<i8')])
a.astype([('f1', 'i8'), ('f0', 'f8')])
# array([(1, 10.)], dtype=[('f1', '<i8'), ('f0', '<f8')])
```
Probably mostly the result of there being no tests of `can_cast` for structured types...

cc @ahaldane

**Comment by seberg** [comment]
This should now be aligned, and the name mismatch is considered a "safe" cast (but an equivalent cast though).
