### ISSUE TITLE
BUG: RandomState has wrong named argument. 

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#13669]
RandomState must accept `seed` keyword argument. 

See  https://travis-ci.org/statsmodels/statsmodels/jobs/538769896 for details.

### Reproducing code example:

```python
import numpy as np
np.random.RandomState(seed=0)
```

### Error message:
```
E   TypeError: __init__() got an unexpected keyword argument 'seed'
```

### Numpy/Python version information:
```
numpy: 1.17.0.dev0+12cb453 (/home/travis/build/statsmodels/statsmodels/venv/lib/python3.7/site-packages/numpy)
```

**Comment by tylerjereddy** [comment]
This seems to be happening in SciPy too -- https://github.com/scipy/scipy/pull/10231#issuecomment-497007952

**Comment by tylerjereddy** [comment]
Curiously, I can't reproduce locally with latest NumPy master + SciPy test suite, but the nightly NumPy wheel does cause a problem on Linux it seems.
