### ISSUE TITLE
dragon4 code has a custom non-OSI approved license

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#13674]
First reported in gh-13447, but the discussion there is mixed with the main issue about GitHub license detection mechanism. This is important enough to get its own issue. Copying content over:

Most vendored things are BSD, however not all. The main issue is dragon4, which is a custom non OSI-approved license. This is really not so helpful. On the PR that added it (gh-9941) there a note saying _Please check the license at the top of the dragon4.c file to confirm it is suitable.._ Apparently no one did. This was too hidden in the description, and should not have been merged without explicit review. A bit hard to do much about now ....

For clarification: I think the actual license text is compatible with BSD. The problems are that (a) it's not OSI-approved (and we signed up to only use OSI approved licenses when we joined NumFOCUS) and (b) that any kind of custom license results in much more effort for anyone trying to get NumPy approved for use in a company that does even basic legal due diligence.

> Could we see how to best adapt the dragon4 license and ask the author to re-license it for us?

Yes it would be best. Not holding my breath though, someone else already asked 5 years ago and the guy said it's too much work to set up a repo with a license. But I guess all we need is an email. I will try.

**Comment by mattip** [comment]
@rgommers any progress?

**Comment by rgommers** [comment]
Email sent, now waiting for a response.
