### ISSUE TITLE
ENH: check object shape when using the __array__ protocol

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13671]
Consider a class `T` that implements the `__array__` protocol with shape (0, 0) and has length 0, so it is consistent with itself. When calling `np.array([T()])`, the result has shape `(1, 0)`; 1 from the list and 0 since that is what T-as-sequence reports as its length. But should the result shape be `(1, 0, 0)`, i.e. should the `__array__` protocol take precedence over the sequence?

This came up in #13659 when discussing the case of `pandas.DataFrame()` which exhibits this behavior. Below is a class taken from the test to fix that issue.

<details>

```
        class T(object):
            def __array__(self):
                return np.ndarray(shape=(0,0))

            # Make sure __array__ is used instead of Sequence methods.
            def __iter__(self):
                return iter([])

            def __getitem__(self, idx):
                raise AssertionError("__getitem__ was called")

            def __len__(self):
                return 0
```

**Comment by seberg** [comment]
I think it is pretty clear that `__array__`, etc. should take precedence here. But, we do not really want to call `__array__` multiple times. Possibly, it could be only probed when a 0 dimension is hit, but it is probably all a bit tricky.

**Comment by eric-wieser** [comment]
Perhaps we should cache calls to __array__ during the first shape-discovery pass so that we can avoid repeating the calls in the second pass?

**Comment by seberg** [comment]
Just to note that array-likes which are not sequence likes are also a class of broken objects here (PIL images are probably in this class).

**Comment by seberg** [comment]
This has been fixed by my rewrite of `np.array`.
