### ISSUE TITLE
DOC: C-API dtype->f->(scanfunc|fromstr) incorrect.

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#13686]
The C-documetation on the `scanfunc` and `fromstr` ArrFunc slots are incorrect [0]. The scanfunc, uses the same return value convention as [`fscanf`](https://en.cppreference.com/w/cpp/io/c/fscanf).

`fromstr` is mostly correct (and I am willing to change the code to make it fully correct), although I am wondering if we should note that the pointer should not be moved past a possibly `'\0'` byte. On the other hand, that part is probably clear.

Both functions should note that they must work without the Python GIL, and will need to grab the GIL if they wish to indicate an error. However, a generic "invalid" data Exception will be set in the future if the data was not fully read.

[0] https://docs.scipy.org/doc/numpy-1.16.0/reference/c-api.types-and-structures.html#c.PyArray_ArrFuncs.scanfunc

**Comment by mattip** [comment]
Closing, fixed by #13692
