### ISSUE TITLE
critical memory leak

### ISSUE THREAD

**Issue by wwilly** [numpy/numpy#13680]
After execution of this code at EOP, there is still resident memory.

```python
before 28.270592
after 681.447424
```

AFAIK, after the return of a function, python should release objects used by the function. Here, after voluntarily del the content of the list a and the list itself, and call garbage collection in the function, and outside the function, it seems that there something still resident in memory.

I'm missing something somewhere to remove all objects of that function?
This is part of a bigger work that use much more memory, and it cause serious swapping problem.

### Reproducing code example:

```python
import numpy as np
import sys, numpy; print(numpy.__version__, sys.version)
import gc
import psutil

# import objgraph

def fun():
    nr_files = 223
    nr_col = 8 * 5
    nr_samples = 10624
    a = []
    
    input("before")
    for i in range(nr_files * nr_col):
        a.append(np.linspace(0, 5, num=nr_samples))
        

    input("after")

    # print(a)
    
    for i in a:
        del i
    del a
    
    gc.collect()

    input("after gc")

    return

def main():
    input("BOP")
    
    # objgraph.show_growth()
    # roots = objgraph.get_leaking_objects()
    # print("leaking objects: ", len(roots))

    before = psutil.Process().memory_info().rss / 1e6
    
    fun()
    
    # print("after call:")
    # objgraph.show_growth()
    # roots = objgraph.get_leaking_objects()
    # print("leaking objects: ", len(roots))

    gc.collect()

    after = psutil.Process().memory_info().rss / 1e6

    print("before", before)
    print("after", after)

    input("EOP")
        
if __name__ == '__main__':
    main()
```

### Numpy/Python version information:

1.16.4 3.7.2 (default, Feb 14 2019, 13:29:05)
[GCC 6.3.0 20170516]

**Comment by seberg** [comment]
This is expected behaviour the operating system (or maybe python have to check), caches these  allocations on certain systems. If you repeat your function a few times, you will see that memory usage settles, so the memory is freed, it just remains with the process for optimization. (numpy does some caching as well, but I do not think that is what you see).

**Comment by wwilly** [comment]
Is it possible to remove that caching or really free up this memory?

In fact my real case do some processing in parallel with a ProcessPoolExecutor. It appears that only some worker grow the memory as crazy, but only for a few. Because it doesn't release the memory to the OS, all this process end up in swapping like crazy at one point.

**Comment by seberg** [comment]
@wwilly I do not think NumPy caches serious amounts of memory here, it does not cache such large allocations (it is not worth the trouble). Are you sure that you are clearing up everything in the actual script?  I think you have to figure out what your actual program does different from the above script you gave probably. Why would some workers need a lot of memory and most do not?

**Comment by wwilly** [comment]
@seberg Thanks.
Each process in the pool read csv data, process it, and then write another csv file.
It's only a few that sometime are bigger than others. I fact, I use pandas for that.
The trick is, the data read are about at most 5MB, the last resulting csv is ~500MB. I didn't thought that pandas with numpy  should eat like 2GB for concatenating. Some other dataset could generate a bit bigger file, but resulting data is not much than this one.
I think I simply over simplify the mechanism of pandas to do stuff, and a bit more cool with the memory. So I jump to parallelise my code, and beem, in space.

I'm curious about this caching stuff, is that memory reusable by other stuff than pandas+numpy object at the end?
Because here, keep ~681MB for caching to maybe optimise later stuff is still serious if it's not reusable/reused in the script itself.
And what about other process running at the same time that could be exhausted because one long script just EAT the memory at one point, but only for a few seconds. I mean, if you need to create a script that call multiple subscript in shell, as so when the script is done it freeup this cache, it seriously not easy to write such thing all the time. And I thing it's a bit against the scripting principle with automatic management. Here I expressly ask for garbage collection, after deleting it. Should I unload numpy as well to say I'm done with such objects, you can free up everything instead of bazookating the python interpreter itself?

Maybe I simply prefer C where I control those stuff...

**Comment by charris** [comment]
Operating systems will cache files in memory for efficiency. If another program needs the memory the cached data will be pushed out. It may also help to close files when you are done with them.

**Comment by seberg** [comment]
I think you really do not have to worry about htese "caches", the should not be your problem. What you should possibly worry about if you are not freeing up some memory for real (i.e. using only a small chunk of some array, but you keep referencing the whole big array keeping it alive).

**Comment by wwilly** [comment]
I understand about OS, but here is in python process world. How does it now anything about the other process running in the OS? Here I only use this thing inside this function, so if let say I'm asking a numpy object of a 1TB in that function only, and nothing else after that, but the script is still running. Is those 1TB will stay here, even after del the object, and gc it? That seriously against good process community, don't you think?

**Comment by eric-wieser** [comment]
Note that this does nothing useful
```
for i in a:
    del i
```
reads as
"create a new references to keep a[...] alive, then immediately delete the reference again"
