### ISSUE TITLE
Assemble release notes at release time, not during development

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13707]
This has been brought up before (#8603), but I think it's time to create a tracking issue.

We have a number of problems with how we currently manage release notes:

* They frequently create merge conflicts which are frustrating for everyone to rebase
* If a PR does not make it into its intended release, the PR is unmergeable until someone gets around to moving the release notes
* If a PR is scheduled for a future version that isn't the next release, there's no way to write the release notes at all until it becomes the "current" release
* Backported PRs requires manual reassembly of release notes

All of these would be fixed by a "one file per section" approach to release notes, which matches what matplotlib and cpython do.

Some options:

* Do the merge manually (via `cat` or similar?) [like matplotlib does](https://matplotlib.org/devel/release_guide.html#update-and-validate-the-docs)
* Use [`blurb`](https://pypi.org/project/blurb/), which is what cpython does
* Use [`towncrier`](https://pypi.org/project/towncrier/), which has been suggested in the past

Some advantages of what we already do:

* It's typically possible to blame the release notes to find the patch that introduced the change
* You can read the master release notes in a single place. We could probably achieve this in the dev-docs anyway though.

**Comment by eric-wieser** [comment]
@tacaswell: would be great to hear matplotlib's perspective on this

**Comment by rgommers** [comment]
SciPy did what NumPy does, considered the same problem, and switched to just putting release notes in a wiki page at merge time. It solves the pain points, the tradeoffs are:
- ICon: it's still some manual work (not much, but probably more than `blurb`/`towncrier`)
- Pro: there's no tool/syntax to learn, so you can just ask any contributor "can you please edit this wiki page" and they know what to do.

**Comment by seberg** [comment]
Just to note, we discussed it a bit today, and while nobody seemed to have a huge preference, I think the consensus was to try the wiki based approach while probably editing the initial PRs post/comment to include a draft of the release notes which can be copied over easily.

**Comment by mattip** [comment]
Matplotlib has a PR to move to towncrier matplotlib/matplotlib#14589.

**Comment by seberg** [comment]
IIRC there was a lot of support for that as well on the mailing list. Lets bring it up tomorrow and unless Chuck feels differently, probably go for it for 1.18.

**Comment by anntzer** [comment]
I noted that the dev meeting notes mention the fact that this will require using pyproject.toml.  Note that this is not the case, and indeed, for matplotlib, we are putting the config in towncrier.toml (requires a flag when invoking towncrier; see discussion in https://github.com/matplotlib/matplotlib/pull/14589).

**Comment by seberg** [comment]
@anntzer I would maybe prefer that solution, but I have not seen that towncrier actually added that functionality as of now (it does exist for `python -m towncrier.check`, but that seems not the correct incarnation?). Although... assuming we are right and towncrier does not support/check for `towncrier.toml` yet, we could fix that upstream I suppose.

**Comment by anntzer** [comment]
I haven't checked in depth that the PR on matplotlib's side actually works :p just pointing out the discussion.

**Comment by tacaswell** [comment]
Matplotlib moved from PRs editing one file to one file per change for exactly the reasons in the OP (mostly the merge conflicts).  However, the manual re-combination is surprisingly time consuming (hence why we are looking at towncrier).

With the wiki approach do you copy the wiki page into the main docs at release time?

**Comment by rgommers** [comment]
> With the wiki approach do you copy the wiki page into the main docs at release time?

Yes indeed. The process is as simple as asking on any PR that needs release notes to add an entry to (e.g. for 1.3.) https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.3.0, and then after branching copy the whole thing into a single release notes file. No machinery, no conflicts. It's quite nice.

**Comment by seberg** [comment]
I will close this, there may still be some bumps about towncrier, but it should be working fine (although with the current development version). And this was about the general thing, not specifics.
