### ISSUE TITLE
Deprecate the aliased constants in the top-level namespaces

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13705]
Continuing from #13696.

In the spirit of

> There should be one-- and preferably only one --obvious way to do it.

I think we should deprecate (either via a warning, or via using the word "deprecated" in the docstring):

* `np.Inf`, `np.infty`, `np.Infinity`, `np.PINF` - these are worse ways to spell `np.inf`, and the doc already recommends the latter
* `np.NINF` - this is a worse way to spell `-np.inf`
* `np.NAN`, `np.NaN` - these are worse ways to spell `np.nan`, and the doc already recommends the latter
* `np.NZERO`, `np.PZERO` - these are weirdly capitalized compared to the other recommended constants, and are shorter as `0.0` and `-0.0`

**Comment by rgommers** [comment]
I agree with the sentiment. I don't think they're used much, they are indeed worse, and clutter up the namespace.

The maintenance overhead of these is really low, so I would suggest to perhaps remove them only is we do a 2.0 release, but happy to see them deprecated (docs or warning, no preference) now.

**Comment by mattip** [comment]
Note this would require modifying `__getattr__` for the module, much as #13525 did, but would check for the deprecated forms as the `attr` argument to the function, and so would only be available for python 3.7 and up.

**Comment by eric-wieser** [comment]
#6103 is the poster-child for `__getattr__`, this is some minor cleanup we could add on once the infrastructure in place. I might take a look at this set of issues once py 3.5 reaches EOL

**Comment by lucascolley** [comment]
Can this be closed now following gh-24357?

**Comment by rgommers** [comment]
Indeed, thanks @lucascolley
