### ISSUE TITLE
isin() is not matching some floats correctly

### ISSUE THREAD

**Issue by homocomputeris** [numpy/numpy#13711]
`numpy.isin()` does not match some values
### Reproducing code example:

```python
import numpy as np
a = np.arange(0.05, 1.0, 0.05)
b = np.array([0.05, 0.85])
np.isin(b, a)

a = np.arange(0.05, 1.0, 0.05)
b = np.array([0.05, 0.8])
np.isin(b, a)
```

### Error message:
```python
array([ True, False])
array([ True, True])
```

### Numpy/Python version information:
```
1.16.4 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127]
```

**Comment by seberg** [comment]
@homocomputeris this is simply floating point imprecision, using logic such as `isin` on floating point is going to be error prone. And the docs do ask you to take care when expecting exact results from `arange`.

**Comment by homocomputeris** [comment]
@seberg Why doesn't the function use something like `allclose` with a user-defined tolerance?
There was a relevant issue https://github.com/numpy/numpy/issues/7784

**Comment by seberg** [comment]
Well, to be honest. I am not sure I like it in numpy, but apparently we do have an open issue for it, and PR/discussion are welcome (I think we should run such a thing by the mailing list before commiting though).

For the other set functions it is more difficult to define. My general gut feeling would be that things like nearest neighbour search fits the problem better, but that may be just me. And maybe it really is a common use case, and at least for `in1d` it seems *fairly* unambiguous (although the actual definition of "close" is not necessarily easy).
