### ISSUE TITLE
ENH: array_equal should have an option to compare NaNs as equal

### ISSUE THREAD

**Issue by allefeld** [numpy/numpy#13727]
I'm trying to use `array_equal` to avoid storing multiple identical arrays in a list. However, if the arrays contain NaNs at the same places, this leads to a return value of `False`.

I understand that numerically, NaNs stand in for undefined numbers, and therefore `np.nan == np.nan` is `False`. It makes perfect sense when comparing arrays elementwise. But if I'm comparing arrays as a whole, I may be interested in the question whether they contain the same values, where NaN is one such possible value. To achieve that, I have to resort to assertion trickery, or `allclose`, see <https://stackoverflow.com/questions/10710328/comparing-numpy-arrays-containing-nan>.

I propose to give `array_equal` an boolean keyword argument `equal_nan` that defaults to `False`.

### Reproducing code example:

```python
import numpy as np
np.array_equal(np.array(np.nan), np.array(np.nan)) 
```

### Error message:

N/A

### Numpy/Python version information:

1.16.3 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

**Comment by bbbbbbbbba** [comment]
Can you describe your scenario more clearly? I struggle to imagine a scenario where exactly equal arrays with NaN is a regular occurence (so that optimizing them away results in non-negligible gain) or where your program's correctness depends on this behavior (and yet the smallest numerical difference is not tolerated).

If, as I thought, the scenario is unlikely to occur anywhere else, you should probably write your own function if you really need this behavior.

Meanwhile, the documentation can maybe use a tweak of words, since as you discovered, `array_equal` checks for "equal" elements instead of "same" ones.

**Comment by allefeld** [comment]
To my mind, this is not a question of a likely or unlikely scenario. I can and have written my own code to circumvent it. I reported it here because I think it is a (small) flaw in the numpy API. Having a simple way to see whether two arrays have the same contents, and therefore one can substituted for the other, appears elementary to me.

To back this up within-Python, the [reference](https://docs.python.org/3/reference/expressions.html?highlight=comparison#value-comparisons) formulates "the desire that all objects should be reflexive (i.e. x is y implies x == y)". It also states that this is deliberately broken e.g. for float-NaNs, and as I wrote, the behavior of `==` for numpy arrays is perfectly sensible. But if we cannot have reflexivity for `==`, then there should be some alternative means of determining sameness that reflects `is`. As a demonstration:

```
>>> a = np.array([np.nan])
>>> b = a
>>> a is b
True
>>> np.array_equal(a, b)
False
```

Outside of Python, for example Matlab has `isequal` which does not treat same-place NaNs as equal, but in addition there is `isequaln` which does. I'm not an expert in R, but as far as I understand, the `single.NA` option of `identical` does the same thing.

Note that what I'm proposing would not break anything; I'm just saying there should be an option to `array_equal` which allows NaNs to be treated as equal. So the idea would be

```
>>> a = np.array([np.nan])
>>> b = a
>>> a is b
True
>>> np.array_equal(a, b, equal_nan=True)
True
>>> c = np.array([np.nan])
>>> np.array_equal(a, c, equal_nan=True)
True
```

But to answer your question, my scenario is the following: I'm writing an OpenGL program which sends array data (in the form of `np.array`) to a shader program for rendering. This data can be used in different ways, and I want to make life easier for the user by making sure that I don't send redundant data several times, thereby unnecessarily using GPU memory. For this reason, I keep a Python list of these arrays, and when the user adds another array it is checked whether an equivalent array is already there, so the new use is replaced by a reference to the existing data. It's a caching mechanism, if you will.

**Comment by seberg** [comment]
Well, just to point it out, but our testing utils do provide this functionality, because there it commonly happens that such tests are necessary. The question is whether it makes sense for the rest of the API.

**Comment by bbbbbbbbba** [comment]
@allefeld I already guessed it might be for caching, but I wonder what a likely reason would be for sending the same data in the first place (I don't have much idea how a typical shader program works). Isn't checking array equality by value slow?

**Comment by seberg** [comment]
If it is for caching purposes (which I agree seems a bit strange), doesn't it make much more sense to view the array as uintXX and use bit wise equality in any case?

**Comment by allefeld** [comment]
@seberg yes, I used the testing functionality to implement this myself, and the uint way would be an alternative.

But as I said, this is not about my application. In my opinion, such a function simply belongs into the numpy main API. As I pointed out, it is present in two other popular numerical packages, so why not in numpy? Identity of contents is an elementary concept, not something exotic / special interest.

If it helps, I could try to come up with the source modification myself and make a pull request. But not if you guys are completely closed against it.

**Comment by seberg** [comment]
@allefeld use case is important. Because we may not want to add an option which is only used by very few power users (who can likely find the uint alternative and which may be more fitting in any case).

 R is a nice data point, but then R actually has a reasonable notion of `NA` values, which we currently do not have. So yes, for users who use NaN for invalid data it is a more valid use case. We currently have `isclose` with the option for that purpose. If someone were to use NaN and floats instead of integers (or similar) and thus not want to use `isclose` that would be an argument.

I am not as such opposed (although also not enthusiastic about it), but I do think the question about use case was important, because I really believe that for you a power-user approach of checking bit-wise equality is likely better.

**Comment by allefeld** [comment]
@seberg, I understand. My view is that in this case, it is just something that makes the API more complete, regardless of how often or not the feature would be used.

I was so far a Matlab user (transitioning slowly), and in the toolboxes I have installed, I can say that `isequaln` is used by both Fieldtrip and SPM, two popular packages for analysis of neurophysiological data. NaN is for example used in fMRI statistical result images (NIfTI format) to indicate that in a specific voxel a test statistic was not computed because the voxel is outside of the brain. Zero-masking is also used (for integer-based images), but clearly more ambiguous. Anyway, in such a case one would still like to be able to check easily whether two brain maps are identical. As a matter of fact, the arrays I'm working with right now are from NIfTI files.

`isclose` can certainly used as a functional equivalent, but is in my opinion semantically too different. ("Explicit is better than implicit.")

Regarding implementation, I had a look at `np.testing.assert_equal` and I'm afraid I won't be able to tell what it does exactly without working more into the code. It is also more general, working for "scalars, lists, tuples, dictionaries". But would you expect there to be a difference between bitwise comparison and whatever `assert_equal` does? I guess another edge case would be whether `+0` and `-0` are treated as being the same: `==` and `array_equal` think so, `assert_equal` does not.

**Comment by bbbbbbbbba** [comment]
No, I don't think Python APIs are the more the merrier. One of the Python principles is "There should be one-- and preferably only one --obvious way to do it." Sometimes, that means not giving out ready-made ropes that a careless programmer can easily hang themselves with.

You mentioning the specific meaning of NaN in your dataset does give us a new perspective. I guess NaNs are tricky things, and there are certainly times where their "standard" handling isn't what you want.

**Comment by allefeld** [comment]
@bbbbbbbbba well, I'd say my point is that for what I'm trying to do, there is currently no obvious way to do it, but instead several non-obvious ones. And yes, NaN are tricky, and both comparing them as unequal and comparing them as equal have their legitimate use.

@seberg how should I proceed? Does it make sense that I submit a pull request? Or is there some other forum instead of this discussion where I should make my case?

**Comment by seberg** [comment]
@allefeld if you have a specific idea, such as adding the kwarg to `array_equal`, you should write to the mailing list. If you are fairly confident that it will be accepted, you can go ahead with a PR of course.

**Comment by bbbbbbbbba** [comment]
@allefeld I'd say the obvious way is `((a == b) | (numpy.isnan(a) & numpy.isnan(b))).all()`, and you come to it naturally by doing away with the notion that NaNs should be "naturally" considered equal.

**Comment by Kai-Striega** [comment]
Just some thoughts: 

> I guess another edge case would be whether +0 and -0 are treated as being equal

```python
n [1]: import numpy as np                                                      

In [2]: a, b = np.random.ranf(1000), np.random.ranf(1000)                       

In [3]: np.equal(-0, +0)                                                         
Out[3]: True
```

The complication is that IEEE-754 defines ``-0,+0`` as equal so, technically, NumPy follows the standard behaviour for both NaN and zeros.

> we may not want to add an option which is only used by very few power users

:+1: 

> I'd say the obvious way is ``((a == b) | (numpy.isnan(a) & numpy.isnan(b))).all()``

This is very similar to how the ``equal_nan`` argument in [isclose](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.isclose.html) works.

https://github.com/numpy/numpy/blob/685b9ace06f1dc50e2698099d7a2b6a241379318/numpy/core/numeric.py#L2537-L2542

> the notion that NaNs should be "naturally" considered equal.

Personally, I don't consider NaNs to "naturally" equal, all they tell us is that whatever they represent is not a (floating-point) number, but this becomes far too philosophical for me.

**Comment by allefeld** [comment]
Alright, I don't know when I'll get around to it, but I will prepare a code change and present it on the mailing list for discussion & decision.

**Comment by namurphy** [comment]
One of the places where I have to compare arrays with NaNs is when I'm writing tests to make sure that different functions can handle/propagate arrays with NaNs (and also infinities) in them correctly.  When writing tests like these, I've found it extremely helpful and time-saving to be able to use the `equal_nan` keyword argument in `numpy.isclose` and `numpy.allclose`.  I would certainly find an `equal_nan` keyword argument in `numpy.array_equal` to be very useful and time-saving too.  Thank you for raising this issue!

-------------
*I am NaN, I am a free man!*  
—No. 6 (from *The Prisoner*)

**Comment by seberg** [comment]
@namurphy are you aware of `np.testing.assert_array_equal`, etc. family of functions?

**Comment by namurphy** [comment]
Good point, I had forgotten about those very useful functions.  Most of my tests involve [`Quantity`](https://docs.astropy.org/en/stable/api/astropy.units.Quantity.html#astropy.units.Quantity) instances from `astropy.units`, which are subclasses of `np.ndarray` with units.  I typically use `astropy.units.isclose` and `astropy.units.allclose` for comparison, which are units-aware wrappers of `np.isclose` and `np.allclose`.  It's from using those functions that I've become such a big fan of the `equal_nan` keyword argument.

**Comment by allefeld** [comment]
I still think this shold be implemented, but I'm sorry I haven't gotten around to it.

**Comment by mattip** [comment]
It seems the idea of adding a keyword to allow comparisons of NaN and maybe even +0, -0 is useful. It would need to be discussed on the mailing list, but in a triage meeting opinions were positive.

**Comment by adeak** [comment]
If I understand correctly, [this was implemented in 1.19](https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html), added in https://github.com/numpy/numpy/pull/16128

**Comment by allefeld** [comment]
@adeak, great news!

**Comment by adeak** [comment]
@allefeld what I mean to say was: this issue can be closed now ;)
