### ISSUE TITLE
histogradd dispatcher does not dispatch correctly on bins

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#13728]
As a reminder for myself if nobody else gets around to it: `bins` in `histogramdd` is a sequence of arrays, not an array itself, so one should dispatch on things inside it (if iterable).

EDIT: `samples` may also be interpreted wrong, since it can be a sequence of arrays.

**Comment by mhvk** [comment]
And `histogram2d` also does not dispatch correctly on `bins`

**Comment by abhinavsagar** [comment]
Should we document this ?

**Comment by mhvk** [comment]
@abhinavsagar - we should fix it! Ideally before 1.17 comes out...

**Comment by mhvk** [comment]
I'll cc @shoyer just in case he has time before me.

**Comment by shoyer** [comment]
OK, these are pretty messy functions! See https://github.com/numpy/numpy/pull/13757 for a PR.
