### ISSUE TITLE
np.load(..., allow_pickle=False) can not unpack `None` values

### ISSUE THREAD

**Issue by megies** [numpy/numpy#13722]
When using `np.load(..., allow_pickle=False)` on a npz that has `None` values in it, the deserialization fails, complaining about object-typed content. This especially hits since the change of the default for this option in numpy/numpy#13359. An easy solution would be to simply set `allow_pickle=True` but since there is a valid reason behind discouraging this, I would prefer a better solution.

It seems that any (? or at least most?) other Python builtins (like `True` and `False`) can be unpacked without problems and i would hope that `None` would also be handled, so that this special case handling does not have to be done in all third party packages using numpy. I feel that this might hit a considerable number of numpy users. 

### Reproducing code example:

```python
import io
import numpy as np

values = {
    'a': True,
    'b': False,
    'c': 1,
    'd': None,
    }

bio = io.BytesIO()
np.savez_compressed(bio, **values)
bio.seek(0)
data = np.load(bio, allow_pickle=False)

for key, value in sorted(values.items()):
    try:
        assert data[key] == value
    except:
        print('Problem with key "%s", originally "%s"' % (key, type(value)))
        raise
    print('Key "%s" OK.' % key)
```

### Error message:

```
Key "a" OK.
Key "b" OK.
Key "c" OK.
Problem with key "d", originally "<type 'NoneType'>"

Traceback (most recent call last):
  File "npbug.py", line 20, in <module>
    assert data[key] == value
  File "/home/megies/anaconda/envs/default/lib/python2.7/site-packages/numpy/lib/npyio.py", line 235, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/megies/anaconda/envs/default/lib/python2.7/site-packages/numpy/lib/format.py", line 645, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

### Numpy/Python version information:

('1.14.5', '2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:16:05)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]')

**Comment by charris** [comment]
Can you be more specific on what the exact problem is and what you propose as a solution?

**Comment by megies** [comment]
I guess you could what I'm missing is a numpy dtype equivalent of Python's builtin `None`. Such that `None` could be stored and recovered while not being recognized as a generic object-type but with a builtin numpy type. But I guess this would mean a major change in deep internals in numpy, so I guess this has to be closed as a won't fix.

I'm using npz to serialize semi-complex Python objects that have considerable amounts of processed data in it (various numpy arrays) and then some parameter settings (can be strings, bools, ints/floats, booleans, None values) into a single npz file. But I guess I can work around it with some minor added logic during de/serialization.

**Comment by Cartucho** [comment]
@megies What about removing from the dictionary the values that are None?

```
values_filtered = {k: v for k, v in values.items() if v is not None}
np.savez_compressed(bio, **values_filtered)
```

and then you can check if they exist

```
if 'd' in data.files:
     print("d found")
else:
     print("d not found")
```

**Comment by megies** [comment]
@Cartucho might have been an option, not sure right now, its too long ago. I worked around it in some way. The real case at hand was more complex than the above mini example though, so can't say for sure.
