### ISSUE TITLE
np.datetime64 incorrectly includes year 0

### ISSUE THREAD

**Issue by timcera** [numpy/numpy#13749]
Subtraction of BCE dates from CE dates are 365 days to large.  Suspect that np.datetime64 incorrectly includes year 0.

Using https://aa.usno.navy.mil/data/docs/JulianDate.php as reference:
0001-01-01 has a Julian date of 1721423.500000
-0001-01-01 has a Julian date of 1721057.500000
The difference using the Julian dates between these two dates is 366 days.

### Reproducing code example:

```python
import numpy as np
bce = np.datetime64('-001-01-01')
ce = np.datetime64('001-01-01')
print(ce-bce)    # prints '731 days', should be '366 days'
```

### Numpy/Python version information:

1.16.3 3.7.3 (default, May 22 2019, 00:01:31) 
[GCC 6.3.0 20170516]

**Comment by eric-wieser** [comment]
Numpy uses ISO 8601 dates, in which according to Wikipedia (citing Annex B.1.1 of the standard):

> by convention 1 BC is labelled +0000, 2 BC is labeled −0001, and so on.

**Comment by timcera** [comment]
Thanks.  Have to keep this in mind.
