### ISSUE TITLE
.sort() to optionally sort inplace/to not sort inplace

### ISSUE THREAD

**Issue by kr4in** [numpy/numpy#13747]
The .sort() function working inplace can be annoying. Had a look a it seems you have to use np.sort(arr) to return a sorted array. When chaining functions this can make the code less readable. Also seems inconsistent with functions like .argsort() and .reshape() but first time posting for numpy so don't know much about the API convention!

### Reproducing code example:

```python
import numpy as np
arr = np.array([1,3,2,5])
arr.sort() # Returns NoneType, arr is now sorted in ascending order
np.sort() # Returns np.array([1,2,3,5])

```

### Numpy/Python version information:

1.16.2 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]

**Comment by mhvk** [comment]
I agree that it is not that consistent with the other methods - it would have been more logical to have an `out` argument that one could set to the array itself.

But unfortunately I don't see how to change this in a useful way: any extra arguments we would add would not make it more consistent and destroy the advantage of being able to use `arr.sort()` inside an equation or so.

**Comment by ewmoore** [comment]
This was almost certainly done to mimic the sort function on a python list.

**Comment by kr4in** [comment]
Thanks for the speedy reply both!

Def must've come from traditional Python lists.

@mhvk agree having an "out" parameter would break the pattern. Would just changing it to be not inplace be too much of a change? Can't think of an example where sorting an array like that would be useful.

**Comment by mhvk** [comment]
We definitely cannot change it to not be in-place by default. People will now have code like
```
arr = <complicated operation>
arr.sort()
<do something else>
```
Just in numpy itself there are already 50 instances of this pattern...
(`find numpy -name \*.py -exec grep \.sort\(\) {} \;|wc`)

**Comment by bbbbbbbbba** [comment]
@kr4in Apart from compatibility issues, most common sort algorithms are "natrally" in-place. And more often than not, we don't care about the original order anymore, so creating a new array is just a waste of time and space.

Maybe a non-in-place sort can be named `arr.sorted()`, although that would be a different syntax than builtin `sorted`...

**Comment by kr4in** [comment]
@mhvk Ahh okay - yeah that wouldn't be a good idea. Also cheers for sharing how you found that out - will use that command in the future to double check this.

@bbbbbbbbba Agreed, the original order is usually unimportant. I guess it might just be my style so probably a personal grievance!

Thanks guys for clearing this up - seems like it wouldn't be worth changing it and there are a few ways round it anyway. Will close.

**Comment by mhvk** [comment]
@kr4in - no worries - thanks for reporting/suggesting.
