### ISSUE TITLE
Exception has occurred: ImportError - Importing the multiarray numpy extension module failed.

### ISSUE THREAD

**Issue by alpmar** [numpy/numpy#13748]
Python 3.7.3 was installed when I created the conda environment for this project.
Numpy was installed on my conda environment via the conda install numpy command. I did pip unistall numpy prior to that.
My operating system is OS X Yosemite 10.10.5
I do have multiple Python versions.

**Comment by eric-wieser** [comment]
Please show the full output of the traceback

**Comment by alpmar** [comment]
Full output is: 
Exception has occurred: ImportError


IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /Users/owner1/.conda/envs/env02/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
  File "/Users/owner1/Documents/aaMyDocsfromMac/DiversosComBk/ProfTD2/TechTD2/td2code/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
  File "/Users/owner1/Documents/aaMyDocsfromMac/DiversosComBk/ProfTD2/TechTD2/td2code/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/owner1/Documents/aaMyDocsfromMac/DiversosComBk/ProfTD2/TechTD2/td2code/a35m_engine_v2_00.py", line 24, in <module>
    import numpy as np
  File "/Users/owner1/Documents/aaMyDocsfromMac/DiversosComBk/ProfTD2/TechTD2/td2code/a70t__orch.py", line 22, in <module>
    import a35m_engine_v2_00
