### ISSUE TITLE
"Contributing to NumPy" links not rendering?

### ISSUE THREAD

**Issue by mdhaber** [numpy/numpy#13740]
[Contributing to NumPy](https://www.numpy.org/devdocs/dev/index.html) has some text that is probably intended to render as hyperlinks but doesn't. Instead, it just appears in italics:

Commit locally as you progress (`git add` and `git commit`) Use a _properly formatted_ commit message, write tests that fail before your change and pass afterward, run all the tests _locally_. Be sure to document any changed behavior in docstrings, keeping to the NumPy docstring _standard_.

From `numpy/doc/source/dev/index.rst`:
```
Commit locally as you progress (``git add`` and ``git commit``)
     Use a `properly formatted <writing-the-commit-message>` commit message,
     write tests that fail before your change and pass afterward, run all the
     `tests locally <development-environment>`. Be sure to document any
     changed behavior in docstrings, keeping to the NumPy docstring
     `standard <howto-document>`.
```
There are many other instances throughout the document (which is otherwise great, BTW).

**Comment by eric-wieser** [comment]
cc @mattip: I thought we made it a build error when this type of thing happens.

**Comment by kritisingh1** [comment]
I think there is some problem with the markdown. We need a `_` after the backticks to turn the text into a link. Thanks @mdhaber for pointing it out. Fixing.

**Comment by mattip** [comment]
We have not yet turned on `-n` when building documentation, which would fail on bad internal references.

**Comment by rgommers** [comment]
> We have not yet turned on `-n` when building documentation, which would fail on bad internal references.

Which kind of internal references? If you are referring to single backticks for parameters/returns, that should not be relevant - just copy the SciPy setup for turning on warning detection. If it's about broken links between packages, then it seems kind of important to fix those (and there can't be _that_ many right?).

**Comment by mattip** [comment]
single backticks are used (and fail) all over the documentation. Turning on the warning detection `SPHINXOPTS='-n' make html` results in over 1000 warnings. See also issue #13114
