### ISSUE TITLE
Issue combining memory-mapped arrays from the same file

### ISSUE THREAD

**Issue by henrypinkard** [numpy/numpy#13756]
Hi, I've run into a bug with combining multiple memory-mapped files into a dask array. I wasn't able to figure out if this is a problem with dask or numpy, so posting on both (dask issue [here](https://github.com/dask/dask/issues/4920))

The context is, I have a large binary file that contains several chunks of data that I'd like to combine into a single multidimensional array, without having to immediately read all of these chunks into memory. My strategy for doing so is is to use np.memmap to create multiple memory-mapped arrays which are views different parts of the same binary file. Then, I use da.stack to make these part of the same dask array. However, when I then try to access the data in the dask array, it copies the second memory-mapped array twice instead of doing the first and then the second. 

### Reproducing code example:

```
import dask.array as da
import numpy as np

#create a file with 10 random bytes
file = open('demo_data', 'wb')
file.write(b'ashekwicht')
file.close()

#open the file and read the bytes the bytes we just wrote
file = open('demo_data', 'rb')
first10 = np.frombuffer(file.read(10), np.uint8)
print('The first 5 bytes of the file are: {}'.format(first10[:5]))
print('The next 5 bytes of the file are: {}'.format(first10[5:]))

#now create two memory mapped views into the same file
mmap1 = np.memmap(file, dtype=np.uint8, mode='r', offset=0, shape=5)
mmap2 = np.memmap(file, dtype=np.uint8, mode='r', offset=5, shape=5)

#combine them with dask and read the 10 bytes again
dask_array = da.stack((mmap1, mmap2))
print('First 5 byte values {}'.format(np.array(dask_array[0, :])))
print('Next 5 byte values {}'.format(np.array(dask_array[1, :])))
```

### Numpy/Python version information:

dask 1.2.2
numpy 1.14.5
python 3.6.8

**Comment by seberg** [comment]
My guess would be that it is a dask issue, with dask trying to be smart about memory mapping and gets something wrong. If you remove the `memmap` part of it by using `mmap1 = mmap1.view(np.ndarray)`, it works.

**Comment by jcrist** [comment]
This is a dask issue (responded there), this should be closed here.
