### ISSUE TITLE
import numpy causes Python crash on Windows Server 2012 R2

### ISSUE THREAD

**Issue by kzhui125** [numpy/numpy#13750]
I am using Numpy 1.16.3, Windows Server 2012 R2

I meet the same problem with:

https://stackoverflow.com/questions/56088235/import-numpy-causes-python-crash-with-numpy-version-1-16-0-and-upwards

**Comment by kzhui125** [comment]
Now I can't use tensorflow 1.13.1 on Windows Server 2012 R2:

tensorflow 1.13.1 doesn't work with numpy 1.5.4
numpy 16+ doesn't work with Windows Server 2012 R2

sad

```
>>> import tensorflow
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
```

**Comment by mattip** [comment]
According to [this page] that OS has not seen an update in over 5 years. Am I wrong? Are you running in a VM or on bare metal? What CPU do you have? Please help convince us why we should support such an out-of-date system, most of us know little about windows.

The StackOverflow question is something different but maybe related.

When you reply, please also add the **entire** traceback.

**Comment by kzhui125** [comment]
python368 + tensorflow 1.12.0 works now
