### ISSUE TITLE
BUG: Incorrect release of GIL in nonzero code

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#13753]
The one dimensional loop seems to be also used for data types that include references (and thus obviously need the API). But the GIL release macro does not appear to be limited to non-object dtypes.

@garyg1 since you were just working on that code, maybe you want to take a look? I realized when I almost merged and it seemed a bit like a different issue anyway.

EDIT: offending line:

https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/item_selection.c#L2265

The fix is spelled out in the `CountNonzero` function: `needs_api = PyDataType_FLAGCHK(dtype, NPY_NEEDS_PYAPI);`

**Comment by garyg1** [comment]
Sure, I'll take a look.

**Comment by eric-wieser** [comment]
xref #9300?
