### ISSUE TITLE
The _masked flag for random integers in an interval seems to be reversed.

### ISSUE THREAD

**Issue by bduvenhage** [numpy/numpy#13769]
The _masked=True flag at https://github.com/numpy/numpy/blob/6420e7f528a6c42422966544e453bdb2805ff620/numpy/random/generator.pyx#L442
seems from the comments to be meant to be selecting Lemire's method as the default. 

Should it not rather be `_masked=False` because setting the flag to False would in fact select Lemire's method. 

See the randomgen comment at https://github.com/numpy/numpy/blob/6420e7f528a6c42422966544e453bdb2805ff620/numpy/random/bounded_integers.pyx.in#L239
for more info.

Also the reference at https://github.com/numpy/numpy/blob/6420e7f528a6c42422966544e453bdb2805ff620/numpy/random/generator.pyx#L421
should perhaps rather be the formal journal reference:
Fast Random Integer Generation in an Interval, ACM Transactions on Modeling and Computer Simulation 29 (1), 2019

### Numpy/Python version information:

1.17.0.dev0+6420e7f 3.6.5 (default, Apr 25 2018, 14:23:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

**Comment by rkern** [comment]
I believe that's correct: we should be using `_masked = False` there.

**Comment by bduvenhage** [comment]
Can I do a pull request for the code and reference update?

@lemire Are you happy with the reference as proposed?

**Comment by mattip** [comment]
@bduvenhage nice catch. We don't really assign PRs, they are always welcome. The changes can be in two different PRs since the issues are not related.

**Comment by bduvenhage** [comment]
@mattip Please see https://github.com/bduvenhage/numpy/commit/20ea07ead2a9370ba88b4cfd5bb916f67310f05c

The change causes some of the random tests to fail because the stream of bounded integers are different for Lemire's methods than for masked rejection sampling.

How do you want to handle this?

**Comment by mattip** [comment]
Please make it into a PR against this repo so we can see the CI failures and get others to comment on it, i.e. @bashtage

**Comment by bashtage** [comment]
IIRC we had decided to use the new method in Generator since this has generally better performance.
