### ISSUE TITLE
BUILD: clean up handling of dll loading on Windows

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13764]
In ~#13109~ #13019 we forced preloading of support DLLs on windows. As per the discussion that starts with [this comment](https://github.com/numpy/numpy/pull/13019#issuecomment-467694625). We should move the code to a `numpy/_distributor_init.py` file in [MacPython/numpy-wheels](https://github.com/MacPython/numpy-wheels)  and wrap it in a try-except in case `__file__` does not exist.

This issue should be resolved before 1.17

xref gh-12994

**Comment by abhinavsagar** [comment]
Could I work on this ?

**Comment by rgommers** [comment]
@abhinavsagar this is not the best issue to work on for a new contributor, and @mattip is on it already

**Comment by abhinavsagar** [comment]
Got it.
