### ISSUE TITLE
DOC: Missing macros in C structs documentation

### ISSUE THREAD

**Issue by kritisingh1** [numpy/numpy#13775]
While working on improving the documentation [here](https://www.numpy.org/devdocs/reference/c-api.types-and-structures.html) , I came across a few macros which were mentioned in the page but were not documented. So far I got the following : -
- NPY_QUICKSORT
- NPY_HEAPSORT
- NPY_MERGESORT
- NPY_MAXARGS
- PyUFunc_One
- PyUFunc_Zero
- PyUFunc_None
- PyUFunc_AllOnes
- PyIntpArrType_Type
- PyUIntpArrType_Type
- NPY_ARR_HAS_DESCR
- ARR_HAS_DESCR

**Comment by seberg** [comment]
> * NPY_QUICKSORT
> * NPY_HEAPSORT
> * NPY_MERGESORT

These are part of the `NPY_SORTKIND` enum, and should probably link to that. (Mergesort and Stablesort are identical right now, and it is likely `MERGESORT` would be better replaced by `STABLESORT`).

> * NPY_MAXARGS

Similar to `NPY_MAXDIMS`, this is the maximum number of array arguments typically used. An example would be for the iterator which can only iterate this many (32) arrays at once.

> * PyUFunc_One
> * PyUFunc_Zero
> * PyUFunc_None

While not an Enum, they are much like an enum, they seem only explained in the code at `ufuncobject.h` around line 124. There are a few more values. They are only used with respect to the `identity` slot of the `UFunc` struct.
It seems they are currently documented a bit sloppily as `.. c:var:: PyUFunc_{VALUE}`. But the definition is outdated, with more being added now.

> * PyUFunc_AllOnes

This one does not seem to exist.

> * PyIntpArrType_Type
> * PyUIntpArrType_Type

As the text says, these are aliases to another integer type, such as possibly `PyLongArrType_Type`, it seems OK to me as it is only used where it is being defined, although the text may not be very clear?

> * NPY_ARR_HAS_DESCR
> * ARR_HAS_DESCR

We should replace `ARR_HAS_DESCR` with the prefixed version. Not sure, if you want to link it, does linking with `PyArrayInterface.flags` documentation make sense?
