### ISSUE TITLE
Fatal Error <Python.h> not found in ndarrayobject.h

### ISSUE THREAD

**Issue by dieterkh** [numpy/numpy#13776]
I imported matplotlibcpp.h into my C++ code and this uses `#include <numpy/arrayobject.h>` which has a reference to <Python.h>. Currently on my mac the proper reference is <Python/Python.h> hence the code fails to run on my current system. I don't know if there's a fix to this error yet.

### Reproducing code example:
It's an issue coming with running numpy in C++, further details on this are shown: [here](https://github.com/lava/matplotlib-cpp/issues/117)

### Error message:
Full error message, if any (starting from line Traceback: ...) -->
```
In file included from ./include/matplotlibcpp.h:19:
In file included from /usr/local/include/numpy/arrayobject.h:4:
/usr/local/include/numpy/ndarrayobject.h:11:10: fatal error: 'Python.h' file
      not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.
make: *** [main.o] Error 1
gh0st$ 
```
### Numpy/Python version information:
```
1.16.2 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]
```

**Comment by charris** [comment]
Sounds like you need to add a flag to the compiler command line showing which paths to search for the include files. This doesn't sound like a numpy issue, so closing.
