### ISSUE TITLE
DOC: string operations section doesn't specify module 

### ISSUE THREAD

**Issue by rlabbe** [numpy/numpy#13778]
The section https://docs.scipy.org/doc/numpy/reference/routines.html has a link to "string operations". The header of the routines page states that you import with "import numpy as np". Subsections that require imports list the module in the name of the link. For example "Linear algebra (numpy.linalg)". "String operations" has no such specification.

When you go to the page link (https://docs.scipy.org/doc/numpy/reference/routines.char.html) it starts with "This module provides..." The module name is not specified; what module is "this"? It is not in the main numpy namespace; for example I cannot write np.lower('HI').

I assume these are the routines from numpy.core.chararray, since "numpy.core.chararray.lower("HI") works, but who can say without running grep over the library?

My suggestion is to add "(numpy.core.chararray)", or whatever the correct module is, to the title of this page.

**Comment by Shekharrajak** [comment]
Hello,

I want to work on this issue. I am not clear about the first point : 

> Subsections that require imports list the module in the name of the link. For example "Linear algebra (numpy.linalg)". "String operations" has no such specification.

I didn't understand the above line.


About second point : 

As far as I know to use `add` we need to import `numpy.core.defchararray ` module : 

```
In [1]: import numpy as np                                                      

In [2]: a1 = np.array(['a', 'b'])                                               

In [3]: a2 = np.array(['c', 'd'])                                             

In [4]: add(a1, a2)                                                             
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-8a0aac00de10> in <module>
----> 1 add(a1, a2)

NameError: name 'add' is not defined

In [5]: np.core.defchararray.add(a1, a2)                                        
Out[5]: array(['ac', 'bd'], dtype='<U2')


In [7]: from numpy.core.defchararray import add                                 

In [8]: add(a1, a2)                                                             
Out[8]: array(['ac', 'bd'], dtype='<U2')

```

and importing `defchararray` module we can use all it's the methods : 

```
In [3]: from numpy.core.defchararray import *                                   

In [4]: lower('Hi')                                                             
Out[4]: array('hi', dtype='<U2')


In [8]: capitalize('hi')                                                        
Out[8]: array('Hi', dtype='<U2')


```

So in this link: https://docs.scipy.org/doc/numpy/reference/routines.char.html, it should write : 

```
numpy.core.defchararray module provides a set of vectorized string operations for arrays of type numpy.string_ or numpy.unicode_. All of them are based on the string methods in the Python standard library.
```

Right?
