### ISSUE TITLE
Memory Error when running numpy.fft

### ISSUE THREAD

**Issue by Landau11th** [numpy/numpy#13782]
Encountered an memory error when using numpy.fft. I am using Windows.
The code below cannot stably reproduce the error, sometimes the machine just crash.
In general, one can observe the memory occupied by Python keeps increasing when running the code, until memory error.

Apologies if this is not the right place to ask such questions.
### Reproducing code example:

```python
import numpy as np

def distance(image1, image2):    
    res = np.fft.fft2(image1)
    res *= np.fft.fft2(image2)
    res = np.fft.ifft2(res)
    #inner = abs( np.max(np.fft.ifft2(res), axis=0))
    #inner = np.abs(np.max(np.fft.ifft2(res)))
    del res
    return None#np.sqrt((1.+inner)/2.)

if __name__ == "__main__":
    N = 55
    a_size = 40000
    repeated = 2000
    a = [ np.random.rand(N,N) for i in range(a_size) ]
    b = np.random.rand(N,N)

    for j in range(repeated):
        #input("Press any key to start %d loop" % j)
        for i in range(a_size):
            d = distance(a[i], b)
```

### Error message:

MemoryError
### Numpy/Python version information:

sys: '3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]'
numpy: 1.16.2

**Comment by seberg** [comment]
@oleksandr-pavlyk this sounds like it is probably related to intels FFT? @Landau11th it might already be solved, but removing `mkl` from your conda environment might be a quick fix if you need an acute get things running fast.

If you need help, you may want to look at issues labeled with "29 - Intel/Anaconda"
