### ISSUE TITLE
np.putmask doesn't dispatch to other.putmask override, but works with NEP18

### ISSUE THREAD

**Issue by pilkibun** [numpy/numpy#13806]
With most numpy non-ufuncs functions I've encountered so far, if an arbitrary
object is given to it, and it has a name-and-signature-compatible method of the same name, that method will be called instead of numpy's own implementation.
So for example, implementing a suitable `round` method on any `MyObject` and
then calling `np.round(MyObject)` will dispatch to MyObject.round() to do the work.

This is very convenient, but it doesn't seem to work with `np.putmask`

```python
class Foo(object):    
    def __getattribute__(self, name):
        print(f"requested '{name}'")        
        return super(Foo,self).__getattribute__(name)   
                    
    def __array_ufunc__(self,func, *args, **kwds):
            print("__array_ufunc__", func)
            return NotImplemented
    def putmask(self,*args, **kwds):
        print("putmask called")

#    def __array_function__(self,func, *args, **kwds):        
#        print("__array_function__", func)
#        print(args)
#        return [1,2,3]
 
ar=Foo()        
np.putmask(ar, [0,1], 0)

TypeError: putmask() argument 1 must be numpy.ndarray, not Foo
```

But if the NEP18 interface is used, putmask invokes `__array_function__` without complaint. Is this by design or is it a bug?

cc @shoyer

**Comment by jorisvandenbossche** [comment]
@pilkibun ndarray has no `putmask` method to dispatch to, only a `put` method (there are both `np.put` and `np.putmask`, which are different, I suppose that `np.put` will dispatch to `ndarray.put()`)

**Comment by pilkibun** [comment]
I see. so NEP18 really is the only way to override it?

**Comment by seberg** [comment]
@pilkibun yes, I suppose one could say that is exactly why we have NEP18 after all.

**Comment by pilkibun** [comment]
That's important to know. Thanks.
