### ISSUE TITLE
development version setup

### ISSUE THREAD

**Issue by Shekharrajak** [numpy/numpy#13800]
### Reproducing code example:

I run the test using 

```
python runtests.py -v

```
but it after completion I got this `FAILED (KNOWNFAIL=7, SKIP=15, errors=1, failures=1)

So is the test failing and need to fix them?

### Error message:

```
======================================================================
ERROR: Failure: DeprecationWarning (Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/shekharrajak/anaconda3/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/shekharrajak/anaconda3/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/shekharrajak/Documents/githubRepos/scipy/numpy/build/testenv/lib/python3.7/site-packages/numpy/core/tests/test_datetime.py", line 23, in <module>
    class TestDateTime(TestCase):
  File "/home/shekharrajak/Documents/githubRepos/scipy/numpy/build/testenv/lib/python3.7/site-packages/numpy/core/tests/test_datetime.py", line 1377, in TestDateTime
    @dec.skipif(not _has_pytz, "The pytz module is not available.")
  File "/home/shekharrajak/Documents/githubRepos/scipy/numpy/build/testenv/lib/python3.7/site-packages/numpy/testing/decorators.py", line 126, in skip_decorator
    if isinstance(skip_condition, collections.Callable):
  File "/home/shekharrajak/anaconda3/lib/python3.7/collections/__init__.py", line 52, in __getattr__
    DeprecationWarning, stacklevel=2)
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

======================================================================
FAIL: test_utils.test_clear_and_catch_warnings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/numpy/build/testenv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py", line 770, in test_clear_and_catch_warnings
    assert_warn_len_equal(my_mod, 1)
  File "/home/numpy/build/testenv/lib/python3.7/site-packages/numpy/testing/tests/test_utils.py", line 743, in assert_warn_len_equal
    assert_equal(len(mod_warns), 2)  # including 'version'
  File "/home/numpy/build/testenv/lib/python3.7/site-packages/numpy/testing/utils.py", line 372, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 1
 DESIRED: 2

----------------------------------------------------------------------
Ran 6042 tests in 38.515s

FAILED (KNOWNFAIL=7, SKIP=15, errors=1, failures=1)

```
### Numpy/Python version information:

Building from source using Python 3.7

1.11.0.dev0+106bfd6 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0]

**Comment by mattip** [comment]
NumPy 1.11 was released over three years ago. The latest release is 1.16.4.

**Comment by Shekharrajak** [comment]
Yeah! Sorry I was using old branch. I have update my branch with latest version available in numpy repo.

Actually I was trying to use the cloned version to check my changes, but I got this error :

```
(numpy-dev)   numpy ➜ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__, sys.version)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/numpy/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/numpy/numpy/core/__init__.py", line 90, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/numpy/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

```

I am following this article: https://www.numpy.org/devdocs/dev/development_environment.html

**Comment by Shekharrajak** [comment]
The same error when I run 

```
(numpy-dev)  python runtests.py -v                             
Building, see build.log...
    ... build in progress
Build OK
Traceback (most recent call last):
  File "runtests.py", line 491, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 265, in main
    __import__(PROJECT_MODULE)
  File "/home/numpy/build/testenv/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/numpy/build/testenv/lib/python3.7/site-packages/numpy/core/__init__.py", line 90, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/numpy/build/testenv/lib/python3.7/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

```

**Comment by mattip** [comment]
`git clean -xfd`

**Comment by Shekharrajak** [comment]
Thanks @mattip ! Now I am able to run the tests and my local changes using this command inside the cloned folder : 

```
python runtests.py -g --python test_do_not_commit.py 

Building, see build.log...
Build OK
Enabling display of all warnings
1.17.0.dev0+17e7ba7 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

```

where test_do_not_commit.py file contains : 

```
import sys, numpy; print(numpy.__version__, sys.version)
```

**Comment by Shekharrajak** [comment]
When I am trying to get the docs using  `make html`, I am getting this version check error : 

```
make html
mkdir -p build
touch build/generate-stamp
installed numpy 0eeb158ead != current repo git version '17e7ba7aa9'
use "make dist" or "GITVER=0eeb158ead make html ..."
Makefile:56: recipe for target 'version-check' failed
make: *** [version-check] Error 1

```
`0eeb158ead` is the commit that is installed in my system using conda and `17e7ba7aa9`
 is the commit that is present in my cloned folder. So isn't it should use `17e7ba7aa9` directly for building the HTML doc ?

**Comment by Shekharrajak** [comment]
Now I have removed the numpy installed version (conda installed version) from the environment and installed the cloned version using : `python setup.py build_ext -i`. I am able to see the latest commit inside the cloned folder : 

```
python3 -c "import numpy; print(numpy.version.git_revision[:10])"
17e7ba7aa9

```
but when I run make html inside the doc folder I get the error : 

```
(numpy-dev) shekharrajak ➜  numpy :  cd doc  
(numpy-dev) shekharrajak ➜  doc : make html
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
installed numpy != current repo git version '17e7ba7aa9'
use "make dist" or "GITVER= make html ..."
Makefile:56: recipe for target 'version-check' failed
make: *** [version-check] Error 1

```
Also in this error message we should not print these lines : 

```
installed numpy != current repo git version '17e7ba7aa9'
use "make dist" or "GITVER= make html ..."
```
since GIVER is nothing here.

**Comment by mattip** [comment]
The documents are built out of numpy docstrings, so you must have numpy installed. 

Some of the documentation is tied to a specific numpy commit, so there is a check that the numpy installed and docstrings used for documentation is the one used to build the documentation. You can override the check by copy-pasting the command. PR for clarification welcome.

**Comment by Shekharrajak** [comment]
Thanks @mattip , for letting me know this point. Is there any way to generate the HTML for docs (from the cloned folder), so that I can verify that my documentation related changes will reflect correctly in HTML file?

**Comment by seberg** [comment]
you need to "install" numpy, one trick that may work for you if you do not want to think about it is running `python runtest.py --shell` and then making the docs from that shell (which sets up PYTHONPATH to point to the runtest build version within that shell).

**Comment by Shekharrajak** [comment]
Thanks @seberg for comment. I tried this (inside the doc folder of numpy): 

```
$ python ../runtests.py --shell make html
Building, see build.log...
cBuild OK
Spawning a shell (/usr/bin/zsh)...
/usr/bin/zsh: can't open input file: make

```

Also this 

```
$ python ../runtests.py --shell "print('Hello')" 
Building, see build.log...
Build OK
Spawning a shell (/usr/bin/zsh)...
/usr/bin/zsh: can't open input file: print('Hello')

```

It looks like I am doing something wrong. Please let me know some example how to use `--shell` here.

I think we should have a script that runs all this for developer. I will try to create a sample.

**Comment by mattip** [comment]
I think this use case is better served by working through the [how to build documentation](www.numpy.org/devdocs/docs/howto_build_docs.html) page and expanding whatever is missing there as well as making it more discoverable. Why didn't `make dist` work for you?

**Comment by Shekharrajak** [comment]
With `make dist` I am getting this error: 

```

......
...
.....
Running Sphinx v1.8.2
1.17.dev0 1.17.0.dev0+89b7875

Traceback (most recent call last):
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/shekharrajak/Documents/numpy/doc/sphinxext/numpydoc/__init__.py", line 3, in <module>
    from .numpydoc import setup
  File "/home/shekharrajak/Documents/numpy/doc/sphinxext/numpydoc/numpydoc.py", line 29, in <module>
    from sphinx.util.compat import Directive
ImportError: cannot import name 'Directive' from 'sphinx.util.compat' (/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/util/compat.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension numpydoc (exception: cannot import name 'Directive' from 'sphinx.util.compat' (/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/util/compat.py))

Extension error:
Could not import extension numpydoc (exception: cannot import name 'Directive' from 'sphinx.util.compat' (/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/util/compat.py))
Makefile:140: recipe for target 'html' failed
make[1]: *** [html] Error 2
make[1]: Leaving directory '/home/shekharrajak/Documents/numpy/doc'
Makefile:92: recipe for target 'dist' failed
make: *** [dist] Error 2
```

As per this [comment](https://github.com/rtfd/readthedocs.org/issues/4057#issuecomment-386371190), sphinx.util.compat.Directive is deprecated and removed in latest version of Sphinix.

**Comment by mattip** [comment]
hmm. Our CI and deploy builds pin sphinx to 1.8.5 via `pip install sphinx==1.8.5`. Could you open a separate issue for this? We should either fix for a modern sphinx or document the need to downgrade.

**Comment by Shekharrajak** [comment]
Yeah! I upgraded sphinx to v1.8.5. But still I got the same error. Now I have done one commit on my branch and trying `make html` which is also returning the same error `cannot import name 'Directive' from 'sphinx.util.compat' (/home/shekharrajak/anaconda3/lib/python3.7/site-packages/sphinx/util/compat.py))`.

**Comment by Shekharrajak** [comment]
After understanding makefile and conf.py file. I installed the numpy from the source (even though if we don't install numpy then one of the dependency (matplotlib) of Sphinx will install numpy :sweat_smile: ).

I am able to generate the docs in doc/build folder. Thanks @mattip , @seberg  for help.

**Comment by mattip** [comment]
It seems the documentation on setting your environment up tripped you up, missing `git clean -xfd`, `git submodule update` and `make html`. Could you suggest ways we could make that more clear?

**Comment by Shekharrajak** [comment]
I thought we can build the docs just having the source code, but there is some dependency which require numpy (like matplotlib in sphinx). Also I messed with my working branch which was not updated so when I updated the submodule, it fetched the old commits of `sphinxext`.

Some error message like `make html` suggest to use `make dist` or using GITVER but I think inside it uses `html` only and throw the same error, when NumPy is not installed.

**Comment by Shekharrajak** [comment]
To run `make HTML` smoothly for my changes and commit. I need to run : 

```
$ python setup.py build_ext -i

$ export PYTHONPATH=$PWD

$ make html
```

I think first 2 commands can be automated in `make html` . What do you think ? @mattip

**Comment by mattip** [comment]
No, this should not be in the Makefile. We could improve the error message when numpy cannot be imported at all, but this is a documentation Makefile not one for numpy itself.

It seems you are missing a `cd` somewhere in your sequence, are you sure that works as written? 

Perhaps you could make a PR against the [build the documentation](http://www.numpy.org/devdocs/docs/howto_build_docs.html) page, which only states "... you will need to first build NumPy, and install it so that the correct version is imported..."

**Comment by Shekharrajak** [comment]
> It seems you are missing a `cd` somewhere in your sequence, are you sure that works as written?

Yeah! I am aware of it. I updated the above comment.
 
> Perhaps you could make a PR against the [build the documentation](http://www.numpy.org/devdocs/docs/howto_build_docs.html) page, which only states "... you will need to first build NumPy, and install it so that the correct version is imported..."

I think the this command sequence should be written : 

```
$ python setup.py build_ext -i

$ export PYTHONPATH=$PWD

$  cd doc 

$ git clean -xdf  

$ make html

```
in the [build the documentation](http://www.numpy.org/devdocs/docs/howto_build_docs.html). WDYT?

**Comment by mattip** [comment]
I am not a big fan of `python setup.py build_ext --inplace`, since it creates artifacts mixed in with the code. I prefer `python -mpip install --target /tmp/siteroot; cd doc; PYTHONPATH=/tmp/siteroot make html`.

**Comment by rgommers** [comment]
@mattip that's a lot harder to remember and more to type, without having any real advantage. fine if you prefer it, but inplace build is the standard so please don't modify docs for this.

**Comment by Shekharrajak** [comment]
Yeah, I am also trying to understand this command`python -mpip install --target /tmp/siteroot; cd doc; PYTHONPATH=/tmp/siteroot make html`, since I am not able to run it without error.
