### ISSUE TITLE
No module named 'mvpa2'

### ISSUE THREAD

**Issue by Mahdidrm** [numpy/numpy#13804]
Hello
I am using of Python 3.7 and version of numpy is 1.16.2 ; I want to sparse coding for dictionary learning; 
unfortunately when i run my code i have this error: 
  from mvpa2.suite import SimpleSOMMapper
ModuleNotFoundError: No module named 'mvpa2'

I searched a lot in internet, reinstalled numpy but it does't work;
please help me; Thanks

**Comment by mattip** [comment]
What is `mvpa2` ? It is not part of numpy. A quick search turns up [this](http://www.pymvpa.org/installation.html), are you following the instructions there or some other tutorial?

**Comment by Mahdidrm** [comment]
@mattip  I am so sorry that was my mistake; 
my meaning is mvpa2; I have searched a lot for solving this but the given ways does not work;

**Comment by mattip** [comment]
You have opened an issue in numpy, perhaps you meant to open it on [their issue tracker](https://github.com/PyMVPA/PyMVPA/issues) instead. There is not a lot we can do here, closing.
