### ISSUE TITLE
Element assignment does not work for mixed datatypes

### ISSUE THREAD

**Issue by anuppari** [numpy/numpy#13817]
When setting one variable of dtype int with another variable of dtype float, the assignment doesn't happen. No error is raised. I would expect an automatic conversion if possible, and an error thrown if not.

### Reproducing code example:

```python
import numpy as np

a = np.array([5.0/3.0, 5.0/3.0])
b = np.array([1, 1])
b[:] = a
print('b:', b)
```
prints:
```python
b: [1 1]
```

### Error message:
No error message. If this is expected to be an error, than an error should be displayed.

### Numpy/Python version information:
1.16.3 3.6.7 (default, May 21 2019, 09:58:25) 
[GCC 7.4.0]

**Comment by mhvk** [comment]
It does actually assign (try initializing `b` with 0s and you'll see), and it does it by blindly converting to integer.

One could indeed argue it should fail or warn, but that ship has sailed long ago...

p.s. If this answers your question, please just close the issue. And of course do feel welcome to ask other things - the next time it may well be a bug.

**Comment by seberg** [comment]
Hmm, putting a warning on such unsafe casts could be a thing in the future. I would not be surprised if we already have an issue about it somewhere. But yes, otherwise it is expected/intentional behaviour.

**Comment by anuppari** [comment]
Looks like similar requests for warnings are in issues #8733 and #12449, so I'll close this one.
