### ISSUE TITLE
Unexpected behavior from matmul

### ISSUE THREAD

**Issue by bsavitzky** [numpy/numpy#13828]
I've run into some unexpected behavior when using `numpy.matmul`.  For shape (2,2) array `ar1` and shape (2,N) array `ar2`, the function's behavior appears to change unexpectedly with the dimension N. 

### Reproducing code example:

```python
import numpy as np
ar1 = np.array([[1,0.1],[-0.1,1]])
ar2 = np.vstack([np.ones(100),np.zeros(100)])

ans1 = np.matmul(ar1,ar2[:,:7])
ans2 = np.matmul(ar1,ar2[:,:8])
```

In the code above, ans1 gives the expected result of

```
array([[ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1]])
```

Similarly, I get the expected result when slicing ar2 with ar2[:,:i] for any `i < 8`.  However, ans2 is:

```
array([[1.1, 1.1, 1.1, 1.1, 0. , 0. , 0. , 0. ],
       [0.9, 0.9, 0.9, 0.9, 0. , 0. , 0. , 0. ]])
```

for other values of `i > 8`, the behavior becomes stranger.  E.g. `i = 10` yields:

```
array([[ 1.1,  1.1,  1.1,  1.1,  0. ,  0. ,  0. ,  0. ,  1. ,  1. ],
       [ 0.9,  0.9,  0.9,  0.9,  0. ,  0. ,  0. ,  0. , -0.1, -0.1]])
```

and `i=20` yields:

```
array([[ 1.1,  1.1,  1.1,  1.1,  0. ,  0. ,  0. ,  0. ,  1.1,  1.1,  1.1,
         1.1,  0. ,  0. ,  0. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [ 0.9,  0.9,  0.9,  0.9,  0. ,  0. ,  0. ,  0. ,  0.9,  0.9,  0.9,
         0.9,  0. ,  0. ,  0. ,  0. , -0.1, -0.1, -0.1, -0.1]])
```

Have I misunderstood the intended behavior here?  This is definitely not reproducing standard matrix multiplication. Thanks for any help!

Ben

### Numpy/Python version information:

1.16.4
3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

**Comment by seberg** [comment]
@bsavitzky could you provide the exact operating system as well as the method of installation (i.e. Anaconda). If you are on linux/mac, maybe also run something like (very hacky and prints too much but... ) https://gist.github.com/seberg/ce4563f3cb00e33997e4f80675b80953

**Comment by bsavitzky** [comment]
Thanks for the quick reply.  I'm running linux 18.04.2 LTS.  The output of the script you sent is:

Probing Multiarray
------------------
OpenBLAS:
    num threads: 32
    version info: OpenBLAS 0.3.6 DYNAMIC_ARCH NO_AFFINITY SkylakeX MAX_THREADS=128

Probing Linalg
--------------
OpenBLAS:
    num threads: 32
    version info: OpenBLAS 0.3.6 DYNAMIC_ARCH NO_AFFINITY SkylakeX MAX_THREADS=128

LDD information:
----------------
running: ldd /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd81bfc000)
	libopenblas.so.0 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../../libopenblas.so.0 (0x00007f9cff9f8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9cff65a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9cff43b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9cff04a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9d019b4000)
	libgfortran.so.4 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libgfortran.so.4 (0x00007f9d01a94000)
	libquadmath.so.0 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libquadmath.so.0 (0x00007f9d01a58000)
	libgcc_s.so.1 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libgcc_s.so.1 (0x00007f9d01a44000)
running: ldd /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/_umath_linalg.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd19cc8000)
	libopenblas.so.0 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../../libopenblas.so.0 (0x00007fc574d92000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc574b73000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc574782000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc5743e4000)
	libgfortran.so.4 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../.././libgfortran.so.4 (0x00007fc576ad4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc576a1f000)
	libquadmath.so.0 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../.././libquadmath.so.0 (0x00007fc576a98000)
	libgcc_s.so.1 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../.././libgcc_s.so.1 (0x00007fc576a84000)

**Comment by seberg** [comment]
@bsavitzky just to be sure: This is the numpy that comes with the Ubuntu system, or not? Also, because it is becoming more common: You are not running on a virtual machine or any such things?

This is likely related to OpenBLAS, and virtual machines did cause problems before in this regard.

**Comment by bsavitzky** [comment]
I'm running an Anaconda installation.  

Additionally, I just ran the same minimal example shown above on a mac (also an anaconda installation) with no problem, so it does it appear that this is likely an OS specific bug.

**Comment by seberg** [comment]
Hmm, we specifically ask building with OpenBLAS v0.3.7 and you seem to have 0.3.6 (unless there was a reporting issue there).  Of the top of my head, I am not sure if that was a bug related to matrix multiplication though.@charris, maybe you remember without looking it up?

**Comment by seberg** [comment]
Yeah, I think it should be that OpenBLAS issue @bsavitzky. Just to be sure, run the script again with:
```
OPENBLAS_CORETYPE=Haswell python
```

Which will disable the (broken) SkylakeX kernel. Upgrading openblas (if you can) should then fix the issue.

**Comment by bsavitzky** [comment]
Running the script with the options above gives:

Probing Multiarray
------------------
OpenBLAS:
    num threads: 32
    version info: OpenBLAS 0.3.6 DYNAMIC_ARCH NO_AFFINITY SkylakeX MAX_THREADS=128

Probing Linalg
--------------
OpenBLAS:
    num threads: 32
    version info: OpenBLAS 0.3.6 DYNAMIC_ARCH NO_AFFINITY SkylakeX MAX_THREADS=128

LDD information:
----------------
running: ldd /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc70be3000)
	libopenblas.so.0 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../../libopenblas.so.0 (0x00007feaefdae000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007feaefa10000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feaef7f1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feaef400000)
	/lib64/ld-linux-x86-64.so.2 (0x00007feaf1d6a000)
	libgfortran.so.4 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libgfortran.so.4 (0x00007feaf1e4a000)
	libquadmath.so.0 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libquadmath.so.0 (0x00007feaf1e0e000)
	libgcc_s.so.1 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../.././libgcc_s.so.1 (0x00007feaf1dfa000)
running: ldd /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/_umath_linalg.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc11def000)
	libopenblas.so.0 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../../libopenblas.so.0 (0x00007fd952a43000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd952824000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd952433000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd952095000)
	libgfortran.so.4 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../.././libgfortran.so.4 (0x00007fd954785000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd9546d0000)
	libquadmath.so.0 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../.././libquadmath.so.0 (0x00007fd954749000)
	libgcc_s.so.1 => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../.././libgcc_s.so.1 (0x00007fd954735000)

**Comment by seberg** [comment]
@bsavitzky thanks, I meant your test:
```bash
OPENBLAS_CORETYPE=Haswell python -c "import numpy as np
ar1 = np.array([[1,0.1],[-0.1,1]])
ar2 = np.vstack([np.ones(100),np.zeros(100)])

ans1 = np.matmul(ar1,ar2[:,:7])
ans2 = np.matmul(ar1,ar2[:,:8])
print(ans1)
print(ans2)"
```

The output should not have printed "SkylakeX" anymore with that environmnet variable set. (or use `export OPENBLAS_CORETYPE=Haswell` to make the change persistent for the terminal history.

**Comment by bsavitzky** [comment]
Ah, I see - that code works correctly!  Output:

```
[[ 1.   1.   1.   1.   1.   1.   1. ]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]]
[[ 1.   1.   1.   1.   1.   1.   1.   1. ]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]]
```

With respect to upgrading openBLAS - my anaconda installation is up to date, and it seems anaconda is only supporting up to openBLAS 0.3.6 (https://anaconda.org/anaconda/openblas), so perhaps others will also have this issue?

**Comment by seberg** [comment]
@bsavitzky probably. Maybe you can check if Anaconda already has an issue about this? Our release notes specifically ask to use a newer openblas version, and I think this was one of the issues why. The other option would be for them to disable the skylakex kernels maybe.

**Comment by charris** [comment]
@seberg It was svd, but the problem was apparently due to dgemm on SkylakeX. The last OpenBLAS release was 3.6, but we made our last release using the OpenBLAS development branch because 3.6 didn't cure the problems. There may also be a compiler problem, there are some reports that using gcc 9.1 fixes some things.

**Comment by bsavitzky** [comment]
Ok, I've just done a more thorough update of my anaconda installation (`conda install anaconda` plus cleaning and updating), and all appears to be well now on my machine.  The numpy linking script now outputs:

Probing Multiarray
------------------
MKL: 
    max threads: 16
    version info: Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications                                                                                                                                                                                                                                                                                                                                                                                                      

Probing Linalg
--------------
MKL: 
    max threads: 16
    version info: Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications                                                                                                                                                                                                                                                                                                                                                                                                      

LDD information:
----------------
running: ldd /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd67d7e000)
	libmkl_rt.so => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/core/../../../../libmkl_rt.so (0x00007fdc3fc71000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc3fa52000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdc3f6b4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc3f2c3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdc406ba000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc3f0bf000)
running: ldd /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/_umath_linalg.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffcced76000)
	libmkl_rt.so => /home/ben/Software/anaconda3/lib/python3.7/site-packages/numpy/linalg/../../../../libmkl_rt.so (0x00007fd8eb996000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd8eb777000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd8eb386000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd8eb182000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd8ec07d000)

Which doesn't mention OpenBLAS at all, just MKL.  This is farther under the hood than I really understand, so for now I'll just be happy my machine is working.  I checked and didn't find an anaconda issue about this problem.  Not sure what to make of that, given that this works with the updates I've just run - still, as day-to-day `conda update --all' calls didn't catch this, it does seem like a bug that could be problematic for some users.  As someone with a little more of an insiders view: do you think this is worth posting an issue for the anaconda developers, or was the problem just that I was not keeping my local distribution up to date?

In any event, thanks for all your help!

**Comment by seberg** [comment]
@bsavitzky whatever you did switched over to the MKL version, so also avoids those bad OpenBLAS skylake kernels.

@charris, hmmm seems a high dimensional problem. Maybe this is just the simpler reproducer for that dgemm problem, but should we ping anaconda in any case?

**Comment by charris** [comment]
> but should we ping anaconda in any case?

I'm surprised they don't know about it, but if they are distributing OpenBLAS they should be pinged. The NumPy issue is #13401 which should have some links to several OpenBLAS issues. #13478 is another.

**Comment by bsavitzky** [comment]
I'm not certain what standard protocol is here, but as this problem is now solved on my machine and is linked to a separate anaconda issue, it seems like this can now be closed, yes?  Thanks again for the help, @seberg

**Comment by tylerjereddy** [comment]
The problem of assuming that the latest stable release of OpenBLAS works with the latest stable release of NumPy and / or SciPy shows up a lot. Hopefully, with the continued improvements in testing upstream that assumption will become less dubious over time.
