### ISSUE TITLE
np.testing.assert_array_less "Mismatch:" wrong with scalar first argument

### ISSUE THREAD

**Issue by borispf** [numpy/numpy#13834]
When the first argument to `np.testing.assert_array_less` is a scalar, the mismatch percentage reported is 100% * &lt;number of mismatched items&gt;, which can be arbitrarily large.

The error seems to be in `numpy.testing._private.utils.assert_array_compare` on [this line](https://github.com/numpy/numpy/blob/a1cd310ea6192945b7f4e452ad5794b291da77a5/numpy/testing/_private/utils.py#L807):

```python
mismatch = 100. * (reduced.size - reduced.sum(dtype=intp)) / ox.size
```

Maybe that line could be:

```python
mismatch = 100. * (reduced.size - reduced.sum(dtype=intp)) / max(ox.size, oy.size)
```

I would be happy to implement such a small fix and write a test for it if someone is able to review it.

### Reproducing code example:

```python
import numpy as np
np.testing.assert_array_less(1, np.zeros((91, 1)))
```

### Error message:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "[snip]/.venv/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1095, in assert_array_less
    equal_inf=False)
  File "[snip]/.venv/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not less-ordered

Mismatch: 9.1e+03%
Max absolute difference: 1.
Max relative difference: inf
 x: array(1)
 y: array([[0.],
       [0.],
       [0.],...
```

I would expect mismatch to be 100%, not over 9000.

### Numpy/Python version information:

1.16.4 3.7.3 (default, May 10 2019, 14:46:04) 
[Clang 10.0.1 (clang-1001.0.46.4)]

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue, @borispf.  This was fixed by https://github.com/numpy/numpy/pull/14349.
