### ISSUE TITLE
high-level documentation for __array_function__ missing

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#13844]
This was noted in the tracking issue (gh-12028) but didn't have its own issue. I wanted to refer to these docs today and found them missing.

Documentation is needed in two places:
- [ ] https://www.numpy.org/devdocs/reference/arrays.classes.html#special-attributes-and-methods
- [ ] https://www.numpy.org/devdocs/user/basics.subclassing.html

A bigger-picture issue is that the subclassing doc nor other docs really discuss the issues with subclassing, and when it would be more appropriate to implement a duck array instead.

**Comment by rgommers** [comment]
@danielballan is planning to work on this at the sprint tomorrow (thank you!). If anyone else has updates or relevant docs, please comment in the next 20 hours or so.

Two other write-ups that may be useful:
- Adoption of `__array_function/ufunc__` protocol by PyTorch design proposal/discussion: https://github.com/pytorch/pytorch/issues/22402
- http://blog.christianperone.com/2019/07/numpy-dispatcher-when-numpy-becomes-a-protocol-for-an-ecosystem/

And also my PyData talk from two months ago where I discussed/demoed `__array_function__`: https://www.youtube.com/watch?v=HVLPJnvInzM&t=10s

**Comment by danielballan** [comment]
Thanks for the references, @rgommers.
