### ISSUE TITLE
SystemError when masking a structured array of size 1<<31

### ISSUE THREAD

**Issue by econtal** [numpy/numpy#13842]
Applying a boolean mask on a structured array of size `1<<31 = 2147483648` (or slightly larger) fails with:

```
SystemError: ../Objects/tupleobject.c:71: bad argument to internal function
```

It does not matter the content of the boolean mask, or the number or inner dtype of fields in the structured dtype.

It seems this affect any size from`(1<<31)` to `(1<<32)-2`, but masking works for `(1<<32)-1` and above.

### Reproducing code example:

Example with size `1<<31`, one single field and an arbitrary boolean mask:
```python
import numpy
a = numpy.empty(1<<31, dtype=[('f0', 'float64')])
mask = a['f0'] > 0
a[mask]  # fails with SystemError
```

Example with size `(1<<32)-2`, two fields, and a mask of `False` only:

```python
import numpy
a = numpy.zeros((1<<32)-2, dtype=[('f0', 'uint8'), ('f1', 'uint64')])
mask = numpy.zeros(a.size, dtype='bool')
a[mask]  # fails with SystemError
```

### Numpy/Python version information:
numpy: 1.16.3 
python: tested on 2.7.12, 3.5.2, 3.7.2

**Comment by seberg** [comment]
Hmmm, can reproduce on 1.16.2, but not on current master.

**Comment by seberg** [comment]
Well, the error should be fixed by this:
```diff
--- a/numpy/core/src/multiarray/mapping.c
+++ b/numpy/core/src/multiarray/mapping.c
@@ -1440,7 +1440,8 @@ _get_field_view(PyArrayObject *arr, PyObject *ind, PyArrayObject **view)
     }
     /* next check for a list of field names */
     else if (PySequence_Check(ind) && !PyTuple_Check(ind)) {
-        int seqlen, i;
+        int i;
+        Py_ssize_t seqlen;
         PyObject *name = NULL, *tup;
         PyObject *fields, *names;
         PyArray_Descr *view_dtype;
```
that code path was cleaned up in master, so that this fix would only be applicable to the maintenance branch. Want to create a PR? Should be possible to create a test, although maybe not vital (also some compilers probably would catch this).

**Comment by econtal** [comment]
Thanks for your quick support and finding the cause.

It seems both `seqlen` and `i` needs to be casted. Otherwise `i` may overflow in the `for` loop. Indeed, master uses:
```c
npy_intp seqlen, i;
```
I'll propose a PR for this tiny change.

**Comment by Kai-Striega** [comment]
@seberg can we close this?

**Comment by eric-wieser** [comment]
Sure
