### ISSUE TITLE
Do not force 128-bit emulation for PCG64

### ISSUE THREAD

**Issue by rkern** [numpy/numpy#13857]
I noticed that we are [forcing 128-bit arithmetic emulation](https://github.com/numpy/numpy/blob/master/numpy/random/setup.py#L61) even when it could be supported. I assume this was a temporary measure, but `pcg64.h` appears to not be written correctly without emulation for some reason. @bashtage @mattip Can you clarify?

**Comment by bashtage** [comment]
I'm pretty sure I didn't make that change, so don't know why it was added.  I was also suspicious of the performance drop. All of the previous tables have been made using randomgen code since the code was essentially identical  This table was made using numpy master to include SFC.
