### ISSUE TITLE
Update mailmap for 1.17

### ISSUE THREAD

**Issue by charris** [numpy/numpy#13862]
Could the following people respond to this issue with the name that should be used in listing contributors to the 1.17.0 release.

- [ ] @aashuli
- [x] @bduvenhage
- [x] @euronion
- [x] @jeremiedbb
- [x] @jeremycl01
- [x] @kai-striega
- [x] @kikocorreoso
- [x] @kirienko
- [ ] @parul
- [x] @shekharrajak
- [x] @sorenrasmussenai
- [x] @spacescientist

EDIT: Also include a valid email if you don't currently have one. Might also want to add it to your github account.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by sorenrasmussenai** [comment]
Soren Rasmussen (or Søren Rasmussen, if special characters are allowed)

**Comment by charris** [comment]
@sorenrasmussenai  Do you have an email?

**Comment by sorenrasmussenai** [comment]
> @sorenrasmussenai Do you have an email?

soren.rasmussen@alexandra.dk

**Comment by bduvenhage** [comment]
Bernardt Duvenhage

**Comment by jeremiedbb** [comment]
Jérémie du Boisberranger

**Comment by charris** [comment]
@jeremiedbb Do you have a contact email?

**Comment by jeremiedbb** [comment]
jeremie.du-boisberranger@inria.fr

**Comment by Kai-Striega** [comment]
Kai Striega
kaistriega@gmail.com

**Comment by Shekharrajak** [comment]
Name : Shekhar Prasad Rajak (@Shekharrajak) 
MailID: shekharrajak@live.com

**Comment by kirienko** [comment]
Yury Kirienko

пт, 28 июн. 2019 г. в 21:28, Charles Harris <notifications@github.com>:

**Comment by jeremycl01** [comment]
Jeremy Lay
jlay80@gmail.com

**Comment by euronion** [comment]
Johannes Hampp
johannes.hampp@zeu.uni-giessen.de

**Comment by spacescientist** [comment]
Please use @spacescientist (aspacescientist@protonmail.com). Thank you.

**Comment by kikocorreoso** [comment]
Hi, please, use @kikocorreoso (kachine@protonmail.com). Thanks.

**Comment by charris** [comment]
Closing for 1.17.0.
