### ISSUE TITLE
Chebfit coefficient order

### ISSUE THREAD

**Issue by eladwass** [numpy/numpy#13866]
Hi 
I'm using chebyshev polynomials to compress data. when plotting the return coefficients I receive a mirrored plot of what I expect. 
I was wandering if the return coefficient from chebfit is from C_n to 0 (like in Matlab) and not 0 to C_n as documented. 
also it is weird to me that C_0 does not represent the DC value of my 1D signal.

### Reproducing code example:
x_axis = np.linspace(-1, 1, len(sample))
degree = len(sample)-1
coefs,extra_data = np.polynomial.chebyshev.chebfit(x_axis, sample, degree,full=True)

reconstructed = np.polynomial.chebyshev.chebval(x_axis, coefs)
print(np.linalg.norm(reconstructed-data))
plt.plot(coefs)
plt.title('coeficient. count={0}'.format(len(coefs)))
plt.show()

Im tring to reproduce this patent from NASA:
https://patents.google.com/patent/US20040093364A1/en

Thanks ahead
Elad

**Comment by charris** [comment]
Should be c_0 ... c_n, unless something else is messing with things. What happens if you use the recommended `Chebyshev.fit` class method of the Chebyshev class? Note that that will use scaled and shifted polynomials for numerical stability but will still evaluate correctly as it tracks that. `from numpy.polynomial import Chebyshev as T`

**Comment by eladwass** [comment]
Hi 

Unfortunately got same result with Chebyshev class. what the shifted/scaled polynomial means? 

Anyhow this is the graphs I expect to see (large around 0 and decay over time):
![US20040093364A1-20040513-D00002](https://user-images.githubusercontent.com/15740376/60388109-7e494580-9ab5-11e9-864f-86bf980b1a5c.png)
and this is what I receive (exactly the opposite...ignore block size):
![Capture](https://user-images.githubusercontent.com/15740376/60388197-a38a8380-9ab6-11e9-9a25-b860e67ed22e.JPG)

**Comment by charris** [comment]
My guess is pilot error, but without the data and sample points it isn't possible to discover what the problem is. Note that you have 512 coefficients while the patent uses blocks of what looks like 16 data points.

As an aside, the patent seems trivial. How in the world did that get a pass?

**Comment by charris** [comment]
Also note that the "Chebyshev transform" as shown in the patent seems to assume that the data points used to evaluate the polynomials are at the Chebyshev points, so you cannot just use the sample number. In fact, it looks to be a DCT. Googles... yep "Chebyshev transform" is another name for the DCT, see https://en.wikipedia.org/wiki/Discrete_Chebyshev_transform.

**Comment by eladwass** [comment]
charris!
THANK YOU VERY MUCH!!!!!
I used : scipy.fftpack.dct(sample,norm = 'ortho') and worked amazing!
ha ha I can't believe that  the patent is simply performing DCT-type2!

thanks again!
