### ISSUE TITLE
Defining overrides for aliased NumPy functions in NumPy

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#13877]
There are handful of NumPy functions that are implemented as aliases of other NumPy function. These include at least `min`, `max`, `round` (non-ufuncs) and `abs` (an alias of the `np.absolute` ufunc):
https://github.com/numpy/numpy/blob/b4105bf03f16e0bd38c6a74ba32de5b0a69ed190/numpy/core/__init__.py#L92-L93

Because `np.min` is defined as `amin`, that's also how you have to override the function with `__array_function__`. This leads to surprising behaviors for libraries like `dask`, which wrote its `__array_function__` method to alias numpy functions to dask/cupy functions of the same name: because `dask.array.amin` does not exist, `numpy.min` (an alias for `numpy.amin`) doesn't work: https://github.com/dask/dask/issues/5031

Things we could do about this on the NumPy side:
1. Nothing -- the error message is clear enough. Dask can implement `amin`/`amax` easily enough.
2. Define separate wrapper functions, so they can be overridden by the name users specify. Interestingly this is already the case for `round_`, which is a wrapper around `around`.

I think option (2) makes sense for `min`, `max` and `round`. It's not a great option for `abs`, since that would mean it no longer goes through `__array_ufunc__`.

**Comment by rgommers** [comment]
> Nothing -- the error message is clear enough. Dask can implement `amin`/`amax` easily enough.

That's forcing API pollution though ....

For `abs` we could switch around the names and make `absolute` the alias.

**Comment by eric-wieser** [comment]
It doesn't sound to me like we need to do anything for abs/absolute -
they're two names for the same ufunc, so neither are affected by the
__array_function__ mechanism. Even the dask __array_ufunc__ can pick its
favorite spelling, and because they're aliases will automatically work for
both.

**Comment by shoyer** [comment]
I agree that it would make sense to reverse the aliases for `min`/`max`/`round`. Certainly these names are much more commonly used.

I agree that we can probably leave `absolute` as is.

**Comment by rgommers** [comment]
We discussed this in the triage meeting:
- preferred indeed to reverse the aliases
- don't want to deprecate the aliases
- the issue in Dask was solved without namespace pollution

So just switch the aliases and close this seems like the way to go.
