### ISSUE TITLE
`AttributeError` when taking sine of huge number

### ISSUE THREAD

**Issue by cool-RR** [numpy/numpy#13875]
```python
import numpy as np
np.sin(70**11)
```

### Error message:

```
Traceback (most recent call last):                 
  File "a.py", line 2, in <module>                 
    np.sin(70**11)                                 
AttributeError: 'int' object has no attribute 'sin'
```

### Numpy/Python version information:

```
1.16.4 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
```

**Comment by eric-wieser** [comment]
Fixed in #12700 to produce a better error message, now gives:
```
>>> np.sin(70**11)
AttributeError: 'int' object has no attribute 'sin'

The above exception was the direct cause of the following exception:

TypeError: loop of ufunc does not support argument 0 of type int which has no callable sin method
```

**Comment by cool-RR** [comment]
Maybe I'm missing something, but the "fixed" version still seems like a completely opaque error message.

Someone runs `np.sin(7)` and it works, and suddenly for a big number it doesn't work. Shouldn't the error message be something like `Input is too large to calculate sin, use float`?

**Comment by seberg** [comment]
Until we get rid of automatic coercion to an object array this is probably about as good as it will get. We could maybe make the error message spell out a bit more things, but we cannot just put in "input is too large" or so, at the point where the error message happens that would just be guessing. Although maybe you can suggest a wording which makes things easier.

**Comment by cool-RR** [comment]
Can't the error catching logic check whether this is an int which is above a certain threshold, and then use the "int is too large" message?

**Comment by eric-wieser** [comment]
No, because `np.sin(np.array(1, dtype=object))` has the same problem
