### ISSUE TITLE
DOC, ENH: add new recfunctions to `__all__`

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13889]
PR #11526 added a number of new functions to `lib.recfunctions` but these are not automatically documented since they were not added to `__all__`.

Whoever fixes this should make sure the PR includes any needed fixes to the docstrings by running `runtests.py --refguide-check`

**Comment by colinsnyder** [comment]
Hello,

I am a new contributor and would like to help on this issue.

To clarify, I am simply adding the four new functions mentioned in #11526 to __all__ , then checking for fixes to the docstrings? Thanks.

**Comment by colinsnyder** [comment]
#13964

I believe that this PR fixes both __all__ and the docstrings.

Thank you.

**Comment by tapaswenipathak** [comment]
Hi folks: Is the ticket open? Can I work on it?

**Comment by rgommers** [comment]
this was fixed, issue should have been closed. all function docs are present in https://numpy.org/devdocs/user/basics.rec.html?highlight=apply_along_fields#numpy.lib.recfunctions.apply_along_fields.

thanks for asking @tapaswenipathak
