### ISSUE TITLE
Feature request: fromstring to read complex array

### ISSUE THREAD

**Issue by ogauthe** [numpy/numpy#13891]
Hello,

[np.fromstring](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fromstring.html) is not able to process complex data type. This would be useful to read from text input file. At least the documentation should mention that complex is not accepted as dtype.

### Reproducing code example:
```python
import numpy as np
s = '1+0.4j, 0.5j, 0.6j, 0.3j'
np.fromstring(s, sep=',', dtype=complex)
```

### Error message:
```python
ValueError: don't know how to read character strings with that array type
```

In case someone else is interested, my workaround was
```python
np.array(s.split(',')).astype(complex)
```

### Numpy/Python version information:
Python 3.6.3
numpy 1.14.3

**Comment by zjpoh** [comment]
@seberg As we discussed at SciPy, I would like to try working on this. Just to double check, the following location is where I should be adding the code to parse complex values right?
https://github.com/numpy/numpy/blob/6ca558fef265b6d286e1868a7bea5723a503a8ba/numpy/core/src/multiarray/arraytypes.c.src#L1759-L1765

It took a while for me to find it but I think it's a good exercise. =)

BTW, I think it would be nice to add to `np.fromstring` docstring on the supported dtypes.

Thanks!

**Comment by seberg** [comment]
Yes, that is the main ting to define.

**Comment by seberg** [comment]
The linked PR impleemnted this long ago.
