### ISSUE TITLE
Quickstart guide recommends np.set_printoptions(threshold=np.nan), which fails

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13900]
We should update [this guide](https://github.com/eric-wieser/numpy/blob/master/doc/source/user/quickstart.rst#printing-arrays) to use `sys.maxsize`.

@mattip, I'm correct in assuming you prefer that to np.inf?

**Comment by mattip** [comment]
yes, and it should be mentioned as the preferred `max` value in the [docstring](https://github.com/eric-wieser/numpy/blob/master/numpy/core/arrayprint.py#L106) as well

**Comment by sameshl** [comment]
@mattip Can you help me figure out why the tests on my PR are failing, I have just updated the documentation and docstrings.

**Comment by sameshl** [comment]
@mattip Can you review my PR https://github.com/numpy/numpy/pull/13948
