### ISSUE TITLE
np.einsum() gives wrong result

### ISSUE THREAD

**Issue by mgbukov** [numpy/numpy#13903]
`numpy.einsum()` seems to give a wrong result in a calculation where the final output should be a hermitian matrix. 

An alternative, somewhat lower-level, calculation produces the correct result.

My suspicion is that there is a numerical instability going on somewhere. 

### Reproducing code example:

The following data files are needed to run the code below:
[einsum_bug_vec.txt](https://github.com/numpy/numpy/files/3356186/einsum_bug_vec.txt)
[einsum_bug_weights.txt](https://github.com/numpy/numpy/files/3356187/einsum_bug_weights.txt)

Here is the script:
[einsum_bug.txt](https://github.com/numpy/numpy/files/3356216/einsum_bug.txt)

```python
import sys
import numpy as np
print(np.__version__, sys.version)

# the data files are attached below
complex_vecs=np.loadtxt('einsum_bug_vec.txt', delimiter=',').view(complex)   # (107,32) array
real_weights=np.loadtxt('einsum_bug_weights.txt', delimiter=',')   # (107,) array

print(complex_vecs.shape, real_weights.shape)

# pedestrian calculation: gives a hermitian matrix
A=np.zeros((32,32),dtype=np.complex128)
for s, vec in enumerate(complex_vecs):
	A+=real_weights[s]*np.einsum('i,j->ij',vec.conj(),vec) 

# einsum calculation: erroneously gives a non-hermitian matrix
A_einsum=np.einsum('s,si,sj->ij',real_weights,complex_vecs.conj(),complex_vecs)


print(np.linalg.norm(A-A.T.conj())) # 0.0, as it should be
print(np.linalg.norm(A_einsum-A_einsum.T.conj())) # 0.19771954288603175, this is suspicious

print(np.linalg.norm(A-A_einsum)) # 0.254093277317957, the two matrices should be equal
```

### Numpy/Python version information:

numpy version: 1.16.4 3.7.3 (default, Mar 27 2019, 16:54:48)
sys version: [Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by mgbukov** [comment]
not sure if it helps any further, but it looks like the following nested call of `np.einsum` does the job
```
A_einsum2=np.einsum('s,sij->ij',real_weights, np.einsum('si,sj->sij',complex_vecs.conj(),complex_vecs) )
print(np.linalg.norm(A-A_einsum2)) # 0.0
```
but applying `einsum()` in the reverse order does not:
```
A_einsum3=np.einsum('si,sj->ij',complex_vecs.conj(), np.einsum('s,si->si',real_weights,complex_vecs) )
```

**Comment by seberg** [comment]
I think these are just numerical errors due to the iteration/operation order, if you check at the relative error:
```
In [21]: (abs((A - A_einsum))/abs(A)).max()
Out[21]: 6.513579290501166e-16
```
it is very much within numerical precision for every single element in A and `A_einsum`. Happy to be convinced otherwise, or convinced that einsum can do something better here though.

**Comment by seberg** [comment]
Two year old issue, that was probably about typical numerical inaccuracy, closing.
