### ISSUE TITLE
ctypes data address guaranteed to remain static?

### ISSUE THREAD

**Issue by SamKG** [numpy/numpy#13906]
Is the memory address given by np.ndarray.ctypes.data guaranteed to remain the same? In other words, is it guaranteed to be safe to reference this memory address and read from the array?

**Comment by eric-wieser** [comment]
It's only guaranteed if you keep the array object alive. Using `.ctypes.data_as(ctypes.c_void_p)` will ensure that happens (at least, in newer versions of numpy)

**Comment by seberg** [comment]
Sounds like the question is answered, closing. Thanks Eric.
