### ISSUE TITLE
np.array returns 1970-01-01 instead of 'NaT'

### ISSUE THREAD

**Issue by timcera** [numpy/numpy#13917]
### Reproducing code example:
On my ARM Chromebook, running Debian 9.9 under Crouton I have a problem where the answer should be 'NaT', but I am getting '1970-01-01T00:00:00.000000000'.

```python
import numpy as np
x = np.array([1,2,np.nan,np.nan]).astype('M8[ns]')
print(x)
```
Will print:

    array(['1970-01-01T00:00:00.000000001', '1970-01-01T00:00:00.000000002',
           '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000'],
          dtype='datetime64[ns]')

### Error message:
No error message.

### Numpy/Python version information:

1.16.3 3.7.3 (default, May 22 2019, 00:01:31) 
[GCC 6.3.0 20170516]

**Comment by charris** [comment]
Hmm, I don't see that here. Where did you get NumPy?

**Comment by charris** [comment]
I suppose there could be a logic problem with the NaT/NaN values on ARM.
```
[9]: x[2].tostring()                                                         
Out[9]: b'\x00\x00\x00\x00\x00\x00\x00\x80'
```

**Comment by seberg** [comment]
I think we had that before, maybe never fixed, that on `np.nan` being cast to int is not well defined. On many platforms it happens to give `MIN_INT` so that it works out, but not on all.

**Comment by seberg** [comment]
Ah, xref-8780

**Comment by timcera** [comment]
> Hmm, I don't see that here. Where did you get NumPy?

pip install numpy

**Comment by timcera** [comment]
> Ah, xref: [gh-8780](https://github.com/numpy/numpy/issues/8780)

Maybe related, however the same code above on a x86_64 machine...

    array(['1970-01-01T00:00:00.000000001', '1970-01-01T00:00:00.000000002',
                                     'NaT',                           'NaT'],
          dtype='datetime64[ns]')

**Comment by seberg** [comment]
Yes, sorry I xref'ed the wrong one, the correct duplicate is: gh-8325

**Comment by seberg** [comment]
This was fixed long ago by gh-14669.  There is still an issue with `float16`, but I will open a new issue for that.
