### ISSUE TITLE
Crosslink between newbyteorder and byteswap

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#13915]
It would be good to include an example somewhere showing that `arr.newbyteorder().byteswap()` produces an array with the same values but different representation in memory.

Related to gh-10372

**Comment by leeyspaul** [comment]
Hello! Happy to take this up. @eric-wieser

**Comment by keyboardbear** [comment]
Looks like this is completed. Can we mark it as closed?

**Comment by mattip** [comment]
Closing.
