### ISSUE TITLE
Contributing/pull request guidelines should clarify what's required for new features

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#13924]
With some frequency, we get new contributors making pull requests to NumPy for feature enhancements / API changes.

It would be great to have something to point them to that to clarify:
1. If at all possible, NumPy prefers *not* to add new APIs, but rather to leave these to more specialized packages.
2. New features (certainly new functions) generally need to be discussed on the mailing list first.

This should appear prominently in both our contributor guide in the docs and CONTRIBUTING.md:
https://github.com/numpy/numpy/blob/master/.github/CONTRIBUTING.md

**Comment by eric-wieser** [comment]
Also absent from our docs: the fact that tests need to be written to go with new features
