### ISSUE TITLE
STY: avoid `import *` pattern

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#13942]
Moving away from it would be a PITA since it is used a bunch, but this pattern makes it difficult for newcomers to see where things are defined.

**Comment by eric-wieser** [comment]
The new practice from @shoyer of overriding `__module__ = "numpy"` makes finding things even harder.

I find that with a mildly smart editor that is aware of function definitions, the problem you describe doesn't affect me much.

I'm not sure the effects of such a change are a net positive effect on maintainability, let alone if they're worth the transition cost.

**Comment by rgommers** [comment]
There's two things here:
1. `import *` by end users - if this is in our docs anywhere, we should fix it
2. `import *` internally in NumPy; this isn't really an issue. Even `??` in IPython will tell you exactly where things are defined. And locating things defined in C is way harder anyway.

**Comment by jbrockmendel** [comment]
closing as duplicate of #13525
