### ISSUE TITLE
Documentation for numpy.var and numpy.std is misleading

### ISSUE THREAD

**Issue by katastrofa999** [numpy/numpy#13940]
Documentation in https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html#numpy.var contains this statement 

> 
> The variance is the average of the squared deviations from the mean, i.e., var = mean(abs(x - x.mean())**2).
> 
> The mean is normally calculated as x.sum() / N, where N = len(x). If, however, ddof is specified, the divisor N - ddof is used instead. 

It is not clear which mean is calculated using `N - ddof` instead of `N`, and the first part of the second sentence suggests (to me, at least) that it's the inner mean - which is not the case (and rightly so).

Suggested (IMHO clearer) rewording:

> The outer mean is normally calculated as t.sum() / N, where N = len(x). If, however, ddof is specified, the divisor N - ddof is used instead.

The same problem is present in the documentation for `nanvar`, `std` and `nanstd`. Similar rewording should make it clearer.

**Comment by mattip** [comment]
I am not familiar with "inner mean" and "outer mean". The suggested text should indicate some definition for the terms, either a link or a mathematical formula, and should define `t` in terms of `x`

**Comment by katastrofa999** [comment]
"Outer" means in this context the one less nested. Maybe another word is better?

t = abs(x - x.mean())**2

(NB, the `abs` is redundant here).

**Comment by matthew-brett** [comment]
I have also not heard the term 'inner' and 'outer' mean - I think that would be confusing.

**Comment by katastrofa999** [comment]
How about:

The first mean is normally calculated as t.sum() / N, where N = len(x) and t = (x - x.mean())**2. If, however, ddof is specified, the divisor N - ddof is used instead.

(And get rid of the abs).

**Comment by bjnath** [comment]
The `Notes` section explains why `abs` is not redundant:

> Note that for complex numbers, the absolute value is taken before squaring, so that the result is always real and nonnegative.

`Notes` also explains explains the intended use of `ddof`  (`delta degrees of freedom`):

> In standard statistical practice, ddof=1 provides an unbiased estimator of the variance of a hypothetical infinite population. ddof=0 provides a maximum likelihood estimate of the variance for normally distributed variables.

`ddof` would not be useful for an inner mean, because N will already have been reduced by the outliers that you removed.

**Comment by seberg** [comment]
True, lets just reopen for now? `outer` seems better, but maybe the best is just just expand the whole docstring a bit, the "outer" mean also uses `x` and misses the `x - x.mean()` part, I am wondering if splitting it up using `deviation = x - x.mean()`. Or just spelling out the whole formula *including* ddof, and then mentioning that with `ddof=0` the outer sum/N becomes a simple mean?

Anyway, I will hope for a nice suggestion in form of a PR, that we can then merge quickly :).

**Comment by rkern** [comment]
I like splitting it up (for clarity, if not concision), and I like including `ddof`.

**Comment by bjnath** [comment]
I apologize; I misread

> "Outer" means in this context the one less nested. 

We might avoid "inner mean" and "outer mean" because the terms already have significance: [inner](https://www.dummies.com/education/science/biology/other-means-besides-the-arithmetic-mean-to-measure-central-tendency/), [outer](https://www.tandfonline.com/keyword/Outer+Mean).

Two other reviewers also took "inner mean" and "outer mean" to be things in their own right and not a reference to inside and outside the parens. Like me, one other reviewer thought this way even after reading the sentance about nesting.

**Comment by bjnath** [comment]
Here is a proposed wording:

![image](https://user-images.githubusercontent.com/6691888/83334017-aca94500-a271-11ea-8680-8b0f11873f6a.png)

I'm new to NumPy so some notation may need straightening out. 

I can then file a PR that includes standard deviation as well.

**Comment by rossbar** [comment]
Just to make sure the conversation is focused on the correct version of the docstring: the wording for the Notes in `var` was recently updated (see #16278) following similar changes to `std` (see discussion in #16267).

**Comment by bjnath** [comment]
Unless I'm mistaken, the commits referenced by @rossbar  suggest this issue has already been dealt with.
