### ISSUE TITLE
Cannot apply numpy functions to large integers

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#13954]
**Steps to reproduce:**
* Assign a large integer above the limit for C `long` to a Python variable.
* Try to perform some scalar operation from numpy functions on that, e.g.
```python
import numpy as np
large_int = 12345678900000000000000000000
np.log10(large_int)
```

**Expected behavior:** should cast it to the required type and output an answer.

**Actual behavior:** does not cast it, throws instead
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'log10'
```

Code works fine if it's converted to Python float beforehand:
```python
import numpy as np
large_int = 12345678900000000000000000000
np.log10(float(large_int))
```

**Comment by sameshl** [comment]
@mattip I would love to take this up. But I was having trouble finding where function log10 is implemented. Can you please help me out on how I should solve this issue.

Thanks!

**Comment by seberg** [comment]
@sameshl it automatically calls the `log10` attribute. (the new versions have a bit better error). The issue here is more that there would have to be a decision about trying to do this. And I have to admit: Unless we first type the array as a `python integer` (instead of any python `object`), I may need some convincing that this is a good idea to discover the python int and cast it silently.

**Comment by sameshl** [comment]
So, if I understand you correctly: you want to go ahead with the idea of discovering and typecasting to int only when the user has explicitly typed array as python integer?

If this, then how do you suggest we handle this issue?

**Comment by seberg** [comment]
@sameshl yes, and that is currently not possible and something we want to spend a lot of effort on in the near future. But basically, that depends on other very large changes.

**Comment by sameshl** [comment]
@seberg I see. This would be a very large change indeed.
I guess we then could close this issue?

**Comment by david-cortes** [comment]
Another funny issue which is probably caused by the same mechanism:
```python
import numpy as np, pandas as pd
s = pd.Series(np.arange(5).astype('float64') + np.array([1.0]).astype('float64')).astype('object')
np.log10(s)
```
```
Traceback (most recent call last):

  File "<ipython-input-14-104f06b0ecd5>", line 1, in <module>
    np.log10(s)

AttributeError: 'float' object has no attribute 'log10'
```

**Comment by seberg** [comment]
Yes, it is the same issue. We have older issues for it, I am not completely against being smarter here, but my tendency is to not really touch it by trying to make it work for `object`. Lets discuss a bit, but may close soon if the discussion does not continue.
