### ISSUE TITLE
No module named _multiarray_umath

### ISSUE THREAD

**Issue by Henry9099** [numpy/numpy#13957]
### Reproducing code example:

import numpy

### Error message:
Traceback (most recent call last):
  File "H:\Python\BBGData\v2\test.py", line 34, in <module>
    import numpy
  File "C:\Users\henry.thomas\AppData\Local\Continuum\anaconda3\Lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\henry.thomas\AppData\Local\Continuum\anaconda3\Lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Python27\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named _multiarray_umath

[Finished in 0.2s with exit code 1]
[shell_cmd: python -u "H:\Python\BBGData\v2\test.py"]
[dir: H:\Python\BBGData\v2]
[path: C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Boxstarter;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\henry.thomas\AppData\Local\Continuum\anaconda3;C:\Users\henry.thomas\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\henry.thomas\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\henry.thomas\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\henry.thomas\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\henry.thomas\AppData\Local\Microsoft\WindowsApps;C:\blp\DAPI\DDE;C:\blp\DAPI\blpapi_cpp_3.13.1.1-windows\blpapi_cpp_3.13.1.1\lib;C:\blp\DAPI;]
### Numpy/Python version information:

System version:
2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]

- installed Python with anaconda
- installed numpy with pip

really appreciate any help

**Comment by mattip** [comment]
If you installed from anaconda, you should stick with conda as your package manager and not pip. `conda install numpy` or `conda update numpy` from an anaconda command prompt

**Comment by Henry9099** [comment]
It running correctly in Anaconda....i'm trying to then run in my text editor (sublime) and that's when I get the issue. Also won't run in IDLE

**Comment by Henry9099** [comment]
Not sure how to fix this...but I just installed spyder from Anaconda Navigator which will work fine. Thanks for your help @mattip
