### ISSUE TITLE
 ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### ISSUE THREAD

**Issue by BharathVittal** [numpy/numpy#13969]
```
df2=pd.DataFrame(np.arange(20,1001,20).reshape(5,10),index=('A1 A2 A3 A4 A5'.split()),columns = ('a1 a2 a3 a4 a5 a6 a7 a8 a9 a10'.split()))

df2

df2[df2>400] | df2[df2>400] 


TypeError                                 Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py in na_op(x, y)
   2000         try:
-> 2001             result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
   2002         except TypeError:

/anaconda3/lib/python3.7/site-packages/pandas/core/computation/expressions.py in evaluate(op, op_str, a, b, use_numexpr, **eval_kwargs)
    207     if use_numexpr:
--> 208         return _evaluate(op, op_str, a, b, **eval_kwargs)
    209     return _evaluate_standard(op, op_str, a, b)

/anaconda3/lib/python3.7/site-packages/pandas/core/computation/expressions.py in _evaluate_numexpr(op, op_str, a, b, truediv, reversed, **eval_kwargs)
    122     if result is None:
--> 123         result = _evaluate_standard(op, op_str, a, b)
    124 

/anaconda3/lib/python3.7/site-packages/pandas/core/computation/expressions.py in _evaluate_standard(op, op_str, a, b, **eval_kwargs)
     67     with np.errstate(all='ignore'):
---> 68         return op(a, b)
     69 

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-141-70080915df96> in <module>
----> 1 df2[df2>400] | df2[df2>400]

/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py in f(self, other, axis, level, fill_value)
   2021             # Another DataFrame
   2022             pass_op = op if should_series_dispatch(self, other, op) else na_op
-> 2023             return self._combine_frame(other, pass_op, fill_value, level)
   2024         elif isinstance(other, ABCSeries):
   2025             # For these values of `axis`, we end up dispatching to Series op,

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in _combine_frame(self, other, func, fill_value, level)
   5088             return ops.dispatch_to_series(this, other, _arith_op)
   5089         else:
-> 5090             result = _arith_op(this.values, other.values)
   5091             return self._constructor(result,
   5092                                      index=new_index, columns=new_columns,

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in _arith_op(left, right)
   5082             # left._binop(right, func, fill_value=fill_value)
   5083             left, right = ops.fill_binop(left, right, fill_value)
-> 5084             return func(left, right)
   5085 
   5086         if ops.should_series_dispatch(this, other, func):

/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py in na_op(x, y)
   2001             result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
   2002         except TypeError:
-> 2003             result = masked_arith_op(x, y, op)
   2004 
   2005         result = missing.fill_zeros(result, x, y, op_name, fill_zeros)

/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py in masked_arith_op(x, y, op)
   1007             with np.errstate(all='ignore'):
   1008                 result[mask] = op(xrav[mask],
-> 1009                                   com.values_from_object(yrav[mask]))
   1010 
   1011     else:

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
```
​

**Comment by mattip** [comment]
Are you sure you wanted to do a [bit-wise `or`](https://stackoverflow.com/questions/3845018/boolean-operators-vs-bitwise-operators) and not a logical one: `df2[df2>400] or df2[df2>400]

**Comment by philippbeer** [comment]
Hello, I am not sure that my issue fits to the example above but I see the following behavior:
I want to do a bitwise or of two arrays with the same shape (and also same unique values). My numpy arrays can be described like this:
shape of ar1: (4194304,) and 
ar2: (4194304,)
unique val of ar1: [0. 1.] and 
ar2: [0. 1.]

## Analysis
So I ran something comparable on a smaller scale:
ar = np.array([1,0,1,0])
ar2 = np.array([1,0,0,0])
ar3 = np.array([ar,ar2])
ar3.shape
red_ar = ar3[0,:]
np.bitwise_or(red_ar,ar3[1,:])


This small example produces the result I expect:
array([1, 0, 1, 0])

## Trace
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-180-7d0ef27a4792> in <module>
      1 fma = FlajoletMartin(stream.content, copies=2)
----> 2 res = fma.fm()
      3 res

<ipython-input-179-bfefe9329c43> in fm(self)
    179         # reduce bitmap
    180         print(self.bitmaps.shape)
--> 181         red_bitmap = self.reduce_bitmaps(self.bitmaps)
    182 
    183         R = self.rightmost_zero(red_bitmap)

<ipython-input-179-bfefe9329c43> in reduce_bitmaps(self, bitmap)
    156             print(f'shape of ar1: {red1.shape} and \nar2: {red2.shape}')
    157             print(f'unique val of ar1: {np.unique(red1)} and \nar2: {np.unique(red2)}')
--> 158             reduced_bitmap = np.bitwise_or(red1, red2)
    159 #             for i in range(1,bitmap.shape[0]):
    160 #                 assert bitmap[i,:].shape == reduced_bitmap.shape

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by WarrenWeckesser** [comment]
> unique val of ar1: [0. 1.] and
> ar2: [0. 1.]

That shows that `ar1` and `ar2` are arrays of floating point values.  The bitwise operators do not accept floating point inputs.  Convert them to integer arrays (e.g. `ar1.astype(int)`) before passing them to `bitwise_or`.

**Comment by seberg** [comment]
The bitwise operations are only implemented for integers. I assume the original report also was confused by this.  There may be the possibility of discussing changing that, but bitwise operations on floats do seem trickier to understand to me, so right now I doubt we should?  If someone is aware of what bitwise operations on floats will do, they can already use `arr.view(np.uint64)`, etc. to apply bitwise operations on the integer representation.

I will close the issue for now, since I believe there is probably nothing we should change (the error is not ideal, but probably not easy to update). Although it might be nice if it listed the input dtypes.

**Comment by philippbeer** [comment]
Thank you!!

**Comment by ibkvictor** [comment]
> 
@mattip 
How does one do the logical or?
`ds_copy.where((ds_copy.u100 > 30 or ds_copy.v100 > 30), drop = True)`

**Comment by mattip** [comment]
In pandas or numpy?
>>> pd.concat([ds_copy.u100 > 30, ds_copy.v100 > 30])
>>> np.vstack([ds_copy.u100 > 30, ds_copy.v100 > 30])
