### ISSUE TITLE
Cov function

### ISSUE THREAD

**Issue by AlexJohnson1995** [numpy/numpy#13966]
Where can I find the definition of cov function? I could not find it among the files. Could you please tell at which file is it defined?

**Comment by mattip** [comment]
From the 1.17 beta release
```
>>> np.cov._implementation.__code__
<code object cov at 0x7f7fcab07c90, file "numpy/lib/function_base.py", line 2245>

```
or on python2

```
>>> np.cov.func_code
<code object cov at 0x7f5ae08741b0, file "lib/function_base.py", line 2888>
```
If the function is defined in C (part of a c-extension) finding the code is a little more involved

Closing, please reopen if needed
