### ISSUE TITLE
Removing rows with nan

### ISSUE THREAD

**Issue by pahirschberg** [numpy/numpy#13960]
I'm trying to learn phython/ML by doing...  
Am using numpy and starting by reading in a csv file using genfromtxt.  File has data like following:

8665530 | 1/1/1920 0:00 | NaN | 0.233 | NaN | NaN
8665530 | 1/1/1920 1:00 | NaN | -0.024 | NaN | NaN
.
.
.
8665530 | 1/31/2019 1:00 | 0.556 | 0.677 | 0.778  | 1

Next, I convert datetime group to datetime64.  This all seems to work.  Output is:

(numpy.datetime64('1920-01-01T01:00:00.00000'), nan, -0.024, nan)
...

Next, I want to eliminate all 'rows' with nan, but can't get it work.
First tried, 
cleandata = [x for x in data if str(x) != 'nan'] # didn't work because nan is float64 when I checked using .dtype

Next I tried isnan, but it didn't work either.  Any suggestions?

### Reproducing code example:

```
def date_parser(d_bytes):
    s = d_bytes.decode('utf-8')
    return np.datetime64(dt.datetime.strptime(s, '%m/%d/%Y %H:%M')) = np.genfromtxt('Record.csv', delimiter=",", names = True, usecols=(1,2,3,4), dtype=None, converters={1:date_parser})
```

**Comment by seberg** [comment]
There are functions such as `np.isnan` and `np.isfinite`, although I think you probably should be using pandas tools, which has things along dropNA I believe.
