### ISSUE TITLE
Value of zero in array with dtype C char evaluates to 'True'

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#13973]
**Steps to reproduce:**
* Create an array of booleans represented as integers or some other type with something that can be evaluated to Python `False`.
* Convert said array to C `char`.
* Interpret any of those values as boolean.

**Expected behavior:** values corresponding to zero should be taken as `False`.

**Actual behavior:** all values are taken as `True`.

Example
```python
import numpy as np, ctypes
arr = np.array([0, 0, 1])
arr_char = arr.astype(ctypes.c_char)
bool(arr_char[0])
>>>    True
```

**Comment by WarrenWeckesser** [comment]
This is normal behavior.

Note that `arr_char[0]` is a `numpy.bytes_` object with length 1:
```
In [36]: arr_char
Out[36]: array([b'0', b'0', b'1'], dtype='|S1')

In [37]: arr_char[0]
Out[37]: b'0'
```
The "truthiness" of a Python `bytes` object or a NumPy `bytes_` object depends only on its *length*, not on the characters stored in the object;  `bytes` objects with length 0 are False:
```
In [51]: bool(b'')
Out[51]: False

In [52]: bool(b'0')
Out[52]: True

In [53]: bool(np.bytes_(b''))
Out[53]: False

In [54]: bool(np.bytes_(b'0'))
Out[54]: True
```

**Comment by seberg** [comment]
Agreed with Warren, just an addendum that while this one makes sense, there are a lot of corner cases that we badly need to align with Python strings: gh-9875
