### ISSUE TITLE
DEP: finish deprecating redonly result from numpy.broadcast_arrays

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13974]
PR gh-12609 started a deprecation cycle to return read-only results from `numpy.broadcast_arrays`. In issue gh-13929 there was discussion of finishing the deprecation cycle immediately in the 1.17.0 release. This would require undoing all of gh-12609 and simply using the existing `readonly` kwarg when calling `_broadcast_to`

This idea should  hit the mailing list

**Comment by charris** [comment]
Closed, #14030 is in.
