### ISSUE TITLE
np.savez() and np.savez_compressed() don't support allow_pickle=False

### ISSUE THREAD

**Issue by histed** [numpy/numpy#13983]
numpy.save() has an allow_pickle() option
numpy.savez() and savez_compressed() do not.

See allow_pickle=True in _savez()
https://github.com/numpy/numpy/blob/aa1955f0a9d79c94aa067b1cbb147fb8523c819f/numpy/lib/npyio.py#L707

Feature request.

**Comment by pranu-18** [comment]
I would like to work on this issue. @rgommers Can you direct me to the files where the changes are to be made?

**Comment by pranu-18** [comment]
Found the file. Can I start working on it?

**Comment by pranu-18** [comment]
Found the file. Can I continue working on this?

**Comment by rgommers** [comment]
Yes, please go ahead. No need to ask for permission, just dive in:)

**Comment by eric-wieser** [comment]
I don't think we can do this without breaking compatibility. What happens if someone is saving an array today like:
```python
np.savez('file.npz', allow_cucumber=a, allow_pickle=b)
```

For this reason, I'll remove the good-first-issue label.

**Comment by mattip** [comment]
We briefly discussed this at a triage meeting and reached the conclusion that this could break compatibility. Maybe we can design a new API that would avoid the problem, but that would need a strong use case. Closing, please feel free to reopen with a new approach.
