### ISSUE TITLE
error in documentation numpy.matmul

### ISSUE THREAD

**Issue by carloacerbi** [numpy/numpy#13987]
the line 

>>> c = np.full([9, 5, 4,3], True, dtype=bool)

in https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html

should be replaced with 

>>> c = np.full([9, 5, 3, 4], True, dtype=bool)

regards

**Comment by seberg** [comment]
@carloacerbi do you want to make a PR with the change?

**Comment by carloacerbi** [comment]
I am new to this. With pleasure. What should I do?

**Comment by kritisingh1** [comment]
Hi @carloacerbi thanks for reporting this. If you are interested in fixing this issue, [this](https://www.numpy.org/devdocs/dev/index.html) might me helpful to you.

**Comment by sameshl** [comment]
Hi @carloacerbi , you could probably look into `numpy/core/code_generators/ufunc_docstrings.py` to solve this issue. 
@kritisingh1 correct me if I am wrong.

**Comment by Ahmed-Gamaleldin** [comment]
Hi all,
I am new to GitHub and search to complete my first contribution somewhere. 
I am a little bit confused about the concept of "Issues" and will be thankful if anyone answers my trivial solution.
Can I pick any "Issue", for example this one, and solve it even if i am not the initiator of this issue ?

**Comment by seberg** [comment]
Yes of course. Unless someone specifically and recently said they are already working on it, you should feel free to make a pull request to fix it.

**Comment by Ahmed-Gamaleldin** [comment]
@seberg 
Thanks for your reply.
Sorry for bothering you with my questions, but i am trying to figure the open source world out, so i will ask again :)
Is it usual that the issue initiator to not be assigned to it especially it's simple like our issue here ?
pulling a request means that i am highlighting that i will work on the issue or means that i finished it already ?
Thnx in advance

**Comment by dashohoxha** [comment]
> Is it usual that the issue initiator to not be assigned to it especially it's simple like our issue here ?
> pulling a request means that i am highlighting that i will work on the issue or means that i finished it already ?

@Ahmed-Gamaleldin 
This short guide answers some parts of your questions: https://guides.github.com/introduction/flow/

**Comment by seberg** [comment]
The guides are probably better than anything I can write. Carloacerbi said he might look into it, at least for us here, that is the only reason to maybe wait a bit. But please do not worry too much about it, everyone is happy about a PR that makes a small fix and this is so small that I do not think we have to worry too much about the unlikely case that work gets done twice.

**Comment by Ahmed-Gamaleldin** [comment]
@dashohoxha  thnx for offering such a great guide !
@seberg thnx again for your nice help and words :)

**Comment by sameshl** [comment]
@seberg I checked on the docstrings of  [np.matmul](https://github.com/numpy/numpy/blob/ea965e4cd328fbcf76b03ff749ef06d2aa38c28b/numpy/core/code_generators/ufunc_docstrings.py#L2646-L2656) and the example there is correct. But the one on the [matmul documentation website](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html) is wrong. Looks like the website docs have not been updated yet ?

**Comment by seberg** [comment]
Sounds like it can be closed then, the up to date docs are here: http://numpy.org/devdocs/reference/generated/numpy.matmul.html?highlight=matmul#numpy.matmul

**Comment by sameshl** [comment]
@seberg Just curious, how often do the docs on the website get updated? :sweat_smile:

**Comment by seberg** [comment]
The devdocs immediately, the others at every release.

**Comment by sameshl** [comment]
Thanks! :+1:
