### ISSUE TITLE
couldn't install 1.16.4 using 'sudo -H pip3 install numpy'

### ISSUE THREAD

**Issue by Des-Nerger** [numpy/numpy#13981]
Edit (mattip): `sudo -H pip3 install numpy` fails

Sorry, right now I have no specifics about what of the errors in the log are aborting my installation, so I'll just post the log. Hope someone will help to make this issue clearer.
[numpy_install.log](https://github.com/numpy/numpy/files/3389366/numpy_install.log)

**Comment by charris** [comment]
Hmm, my guess is a permissions problem, maybe originating in distutils. The log doesn't have much information about the error.

**Comment by mattip** [comment]
Is there a reason you are using `sudo -H pip3 install numpy` and not `pip install --user numpy`? If this succeeds, it will mess up your system package manager (apt or yum) and is considered bad practice.

**Comment by Des-Nerger** [comment]
Ok, now I know what it was.
From the log:
```
x86_64-linux-gnu-gcc-ar: adding 4 object files to build/temp.linux-x86_64-3.4/libnpymath.a
    error: Command "x86_64-linux-gnu-gcc-ar rc build/temp.linux-x86_64-3.4/libnpymath.a build/temp.linux-x86_64-3.4/numpy/core/src/npymath/npy_math.o build/temp.linux-x86_64-3.4/build/src.linux-x86_64-3.4/numpy/core/src/npymath/ieee754.o build/temp.linux-x86_64-3.4/build/src.linux-x86_64-3.4/numpy/core/src/npymath/npy_math_complex.o build/temp.linux-x86_64-3.4/numpy/core/src/npymath/halffloat.o" failed with exit status 127
```
So I tried to just run `x86_64-linux-gnu-gcc-ar`:
```
x86_64-linux-gnu-gcc-ar: command not found
```
Apparently, I didn't have symlink for x86_64-linux-gnu-gcc-ar.
My distro is Debian-based and the current update-alternatives config for gcc was:
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 40 \
	--slave /usr/bin/g++ g++ /usr/bin/g++-8 \
	--slave /usr/bin/x86_64-linux-gnu-g++ x86_64-linux-gnu-g++ /usr/bin/g++-8 \
	--slave /usr/bin/x86_64-linux-gnu-gcc x86_64-linux-gnu-gcc /usr/bin/gcc-8 \
	--slave /usr/bin/x86_64-linux-gnu-cpp x86_64-linux-gnu-cpp /usr/bin/cpp-8
```
so I just added `--slave /usr/bin/x86_64-linux-gnu-gcc-ar x86_64-linux-gnu-gcc-ar /usr/bin/x86_64-linux-gnu-gcc-ar-8` to it. After that, numpy was able to be installed successfully.

**Comment by charris** [comment]
@Des-Nerger Thanks for the followup.
