### ISSUE TITLE
Spelling error in npy_tempita "delimeters" kwarg

### ISSUE THREAD

**Issue by Kai-Striega** [numpy/numpy#13986]
The ``Template`` object's kwarg ``delimeters`` -> ``delimiters`` in the init function and several other places.

For example see line 108:
https://github.com/numpy/numpy/blob/e55bcb2f2c40852be7d9f0e6e262c332dd2b277d/tools/npy_tempita/__init__.py#L106-L109

The full list of occurences:
```python
(numpy-dev) kai@kaiT470:~/numpy-git$ grep -nr "delimeter" ./tools/npy_tempita/
./tools/npy_tempita/__init__.py:108:                 delimeters=None):
./tools/npy_tempita/__init__.py:111:        # set delimeters
./tools/npy_tempita/__init__.py:112:        if delimeters is None:
./tools/npy_tempita/__init__.py:113:            delimeters = (self.default_namespace['start_braces'],
./tools/npy_tempita/__init__.py:116:            assert len(delimeters) == 2 and all(
./tools/npy_tempita/__init__.py:117:                [isinstance(delimeter, basestring_)
./tools/npy_tempita/__init__.py:118:                    for delimeter in delimeters])
./tools/npy_tempita/__init__.py:120:            self.default_namespace['start_braces'] = delimeters[0]
./tools/npy_tempita/__init__.py:121:            self.default_namespace['end_braces'] = delimeters[1]
./tools/npy_tempita/__init__.py:122:        self.delimeters = delimeters
./tools/npy_tempita/__init__.py:146:            delimeters=self.delimeters)
./tools/npy_tempita/__init__.py:395:def sub(content, delimeters=None, **kw):
./tools/npy_tempita/__init__.py:397:    tmpl = Template(content, name=name, delimeters=delimeters)
./tools/npy_tempita/__init__.py:655:def lex(s, name=None, trim_whitespace=True, line_offset=0, delimeters=None):
./tools/npy_tempita/__init__.py:656:    if delimeters is None:
./tools/npy_tempita/__init__.py:657:        delimeters = (Template.default_namespace['start_braces'],
./tools/npy_tempita/__init__.py:663:    token_re = re.compile(r'%s|%s' % (re.escape(delimeters[0]),
./tools/npy_tempita/__init__.py:664:                                      re.escape(delimeters[1])))
./tools/npy_tempita/__init__.py:668:        if expr == delimeters[0] and in_expr:
./tools/npy_tempita/__init__.py:669:            raise TemplateError('%s inside expression' % delimeters[0],
./tools/npy_tempita/__init__.py:672:        elif expr == delimeters[1] and not in_expr:
./tools/npy_tempita/__init__.py:673:            raise TemplateError('%s outside expression' % delimeters[1],
./tools/npy_tempita/__init__.py:676:        if expr == delimeters[0]:
./tools/npy_tempita/__init__.py:687:        raise TemplateError('No %s to finish last expression' % delimeters[1],
./tools/npy_tempita/__init__.py:825:def parse(s, name=None, line_offset=0, delimeters=None):
./tools/npy_tempita/__init__.py:827:    if delimeters is None:
./tools/npy_tempita/__init__.py:828:        delimeters = (Template.default_namespace['start_braces'],
./tools/npy_tempita/__init__.py:830:    tokens = lex(s, name=name, line_offset=line_offset, delimeters=delimeters)
```

**Comment by charris** [comment]
Hmm, this is a vendored file. I *think* it would be OK to change a keyword, NumPy doesn't seem to use it and `tools` is pretty much a private set of files.

**Comment by mattip** [comment]
We use it in the vendored `tools/cythonize.py` which is called in `./setup.py` for the `numpy.random` cython files. I wonder if we could just use the non-vendored version of cythonize these days

**Comment by charris** [comment]
> I wonder if we could just use the non-vendored version of cythonize these days

Don't know. Tempita is vendored because it needed fixes, some of which I sent upstream. I don't think Cython guarantees that it will be present, it is an internal Cython tool.

The question I had was if the misspelled keyword was used, it isn't, so we could change it if we want to, The [original](https://github.com/gjhiggins/tempita) is inactive. But unless we want to also provide documentation, it is probably best to keep the original spelling for folks who might google for it.

**Comment by Kai-Striega** [comment]
I've done a quick survey. "npy_tempita" doesn't appear in any other public Github, Bitbucket or  Google search. If it is used, I suspect the chance of anyone Googling it is pretty low.

Should deprecate ``delimeters`` in favor of ``delimiters``? That will give anyone with private repos a chance to adjust their code if needed.

**Comment by charris** [comment]
I'm not worried about other users, I meant folks who google for user documentation. However, now that I check (https://pyrocore.readthedocs.io/en/latest/tempita.html), the documentation uses `delimiters` :) So does the original code (https://bitbucket.org/ianb/tempita/src/default/tempita/__init__.py). Looks like someone "fixed" that. So let's unfix the fix.

**Comment by eric-wieser** [comment]
This was actually reported (and fixed) upstream in https://bitbucket.org/ianb/tempita/issues/7/misspelling-of-delimiters-in.

Perhaps we should re-vendor tempita from the latest version.
