### ISSUE TITLE
Calling np.array or np.asarray on a tensorflow Tensor returns a Tensor rather than an ndarray

### ISSUE THREAD

**Issue by robieta** [numpy/numpy#14000]
### Reproducing code example:

[gist](https://colab.sandbox.google.com/gist/robieta/977b634f642d910c503c841e2b5d300e/tf_tensor_asarray.ipynb#scrollTo=wM1-z7lMFbQc)

```python
import numpy as np
import tensorflow as tf

x = tf.ones(())
print(np.array(x))
print(np.asarray(x))
print(np.asarray(x, dtype=np.float))
```

### Error message:

Either no error or `ValueError: setting an array element with a sequence.`. (Full details and stack trace in the linked gist.) Converting a tensorflow Tensor to a numpy array does not make sense, so any attempt to convert it is expected to fail with a message to that effect. It is not clear whether this is an issue with numpy or tensorflow.

### Numpy/Python version information:

1.16.4 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

tensorflow==1.14.1

cc @dynamicwebpaige

**Comment by seberg** [comment]
@robieta I do not have tensorflow installed right now. Did you have a place to just try it out online? And if not, what does `x.__array__()` give you, or is `x.__array_interface__` defined?

**Comment by robieta** [comment]
[Google colab](https://colab.research.google.com) comes with TensorFlow installed and also allows `! pip <stuff>`, so you should be able to adjust your environment as needed. It's free but requires a google account. Will that work for you?

**Comment by rkern** [comment]
It's not returning a `Tensor`. It's returning a rank-0 `ndarray` of `dtype=object`, like it usually does when given an object that numpy doesn't know about (i.e. not an int, float, str, or sequence of same). The `__str__()` that you are `print()`ing hides this.

```
[~]
|1> import numpy as np

[~]
|2> import tensorflow

[~]
|3> t = tensorflow.ones(())

[~]
|4> type(t)
tensorflow.python.framework.ops.Tensor

[~]
|5> type(np.array(t))
numpy.ndarray

[~]
|6> class A():
..>     pass
..> 

[~]
|7> np.array(A())
array(<__main__.A object at 0x7ff3be10c240>, dtype=object)

[~]
|8> x = np.array(t)

[~]
|9> x
array(<tf.Tensor 'ones:0' shape=() dtype=float32>, dtype=object)

[~]
|10> print(x)
Tensor("ones:0", shape=(), dtype=float32)
```

**Comment by seberg** [comment]
I think the only problem is that we give the wrong error, because we assume the only reasonable reason for an error in that place is that there is a sequence.

The fact that it cannot work, is that Tensorflow does not even attempt to making it work.

**Comment by amueller** [comment]
Ah, I was misinterpretting what ``np.array`` does here because I was fooled by the ``__repr__``.
@robieta that means making ``__array__`` raise an error is probably the right solution.
@seberg does it seem reasonable to define ``__array__`` and have it raise an error if we want to avoid the singleton object array thing, which will basically never make sense?

**Comment by seberg** [comment]
@robieta quite frankly, on my debian, it does not ust pip3 install... In any case, I think the only thing to do here is to chain the exceptions to be a tiny bit clearer, because I expect that Tensors act a bit like being a sequence (on the C-side).

```diff
diff --git a/numpy/core/src/multiarray/arraytypes.c.src b/numpy/core/src/multiarray/arraytypes.c.src
index 3b986ed04..2abf169bd 100644
--- a/numpy/core/src/multiarray/arraytypes.c.src
+++ b/numpy/core/src/multiarray/arraytypes.c.src
@@ -221,9 +221,7 @@ static int
         if (PySequence_NoString_Check(op)) {
             PyErr_SetString(PyExc_ValueError,
                     "setting an array element with a sequence.");
-            Py_DECREF(type);
-            Py_XDECREF(value);
-            Py_XDECREF(traceback);
+            npy_PyErr_ChainExceptionsCause(exc, val, tb);
         }
         else {
             PyErr_Restore(type, value, traceback);
```

**Comment by robieta** [comment]
Sounds good. Thanks everyone for your help.

**Comment by seberg** [comment]
I created pr gh-14004, which might clarify the error a bit (there is an example for my patch as well)
