### ISSUE TITLE
Boolean based binary operations do not broadcast when used in reduce.

### ISSUE THREAD

**Issue by cdusold** [numpy/numpy#14017]
When reducing boolean arrays, broadcasting does not work, even though it works for individual operations

### Reproducing code example:

```python
import numpy as np

a = np.ones([2,1,1], dtype=bool)
b = np.ones([1,2,1], dtype=bool)
c = np.ones([1,1,2], dtype=bool)

expected = np.multiply.reduce((a,b,c))

also_expected = np.logical_and(np.logical_and(a, b), c)

assert np.all(also_expected == expected)

#This throws 'ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()'
actual = np.logical_and.reduce((a,b,c))

assert np.all(actual == expected)

expected = np.add.reduce((a,b,c))

#This throws 'ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()'
actual = np.logical_or.reduce((a,b,c))

assert np.all(actual == expected)
```

### Error message:

```
Traceback (most recent call last):
  File "myproblem.py", line 14, in <module>
    actual = np.logical_and.reduce((a,b,c))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Numpy/Python version information:

1.16.2 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]

I also checked the latest miniconda docker container out and ran it with python 2 on 1.16.4 and it was still a problem.

**Comment by seberg** [comment]
I think you are expecting the behaviour of `functools.reduce` not of `np.ufunc.reduce`. NumPy will always coerce to array first: `np.asarray((a, b, c))` before calling the reduce attribute (which also reduces everything without an axis argument).

If you inspect the result of `np.asarray((a, b, c))` you will understand why it cannot work in this way. You may be interested in `np.broadcast_arrays`, which may or may not help you.

I will close this for now, please feel free to keep discussing (or asking for reopening it if there is something you feel we can do to improve the situation).

**Comment by cdusold** [comment]
@seberg That explains why np.multiply.reduce seems to result in exactly what I was expecting. Thank you. Hoewever, it only explains why np.logical_and.reduce doesn't work if it is applying python's builtin `and` instead of numpy's across the first dimension of the array, which is unintuitive. I expect the ufunc to be used in all cases, or for `np.logical_and.reduce(np.ones([2,2,2], dtype=bool))` to fail.

Still
```python
d = np.array([object(), object()])
d[0] = np.ones([2,2], dtype=bool)
d[1] = np.ones([2,2], dtype=bool)
np.logical_and.reduce(d)
```
fails because of the lack of coercing (since it's already an array of objects) so that shows that this is the case.

Unless otherwise informed, this does raise one documentation error. np.logical_and specifies that x1 and x2 have to have the same shape, but  `np.logical_and([[True, True]], [[True], [True], [True]])` broadcasts as other ufuncs without this restriction do. I'll wait on further explanation before I file that report.

**Comment by seberg** [comment]
Numpy does not handle nested arrays in any special way, so logical and does indeed basically use the Python `and` internally. That will fail for arrays (because `bool(arr)` cannot be defined). Note that your arrays (if you have an object array) could just as well be of a completely different shape, etc.

**Comment by eric-wieser** [comment]
For some extra clarity here:

* `np.logical_and.reduce((a, b, c))` translates to
    ```
    o_arr = np.empty(3, dtype=object)  # object because the shapes do not match
    o_arr[0] = a
    o_arr[1] = b
    o_arr[2] = c
    np.logical_and.reduce(o_arr)
    ```
* `np.logical_and.reduce(o_arr)` translates to `o_arr[0] and o_arr[1] and o_arr[2]`
* `and` on numpy arrays isn't supported (and can't be overloaded in python)

Knowing this, you can cheat and use `bitwise_and` instead, since that ends up translating to `o_arr[0] & o_arr[1] & o_arr[2]`:
```
>>> np.bitwise_and.reduce((a, b, c))
array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])
```

**Comment by cdusold** [comment]
I saw the bitwise_and workaround, and it's great for my use case; thank you eric-wieser. I think using an explicit broadcast before reduce is a better fix readability wise, thank you Seberg.

That all makes sense. I'm a little disappointed (not in this, mostly at python's lack of operator overload, even though it makes some sense if you ignore the "we are all adults here" ideology of Python), but the overload issue explains my logic break. I hope I'm not bothering you two. I do appreciate the clarification.

This doesn't change the fact that the shape isn't required to be the same in the base logical_and even though the documentation says it does. It is required in the reduce call though. I'm guessing because the base __call__ to a ufunc has extra logic to handle the broadcasting when it is binary, either in the __array_prepare__ or between it and the call the __array_ufunc__, but reduce is a non-binary operation, so the __array_prepare__ wouldn't broadcast, and the actual reduction skips that step as the array should already be prepared. I don't know if I'm off base but that seems logical based on the documentation. It would cause __array_ufunc__ to skip to the python and operation in reduce, and the __call__ version to actually have the same shape as required by the documentation.

**Comment by eric-wieser** [comment]
> This doesn't change the fact that the shape isn't required to be the same in the base logical_and even though the documentation says it does

This sounds like a documentation error, and ought to be updated to match the docs for other ufuncs like `np.add` which specify something more reasonable.

> the actual reduction skips that step as the array should already be prepared.

Correct, `reduce` expects to be provided with a single array, not a list of arrays. Passes the latter results in best-guess conversion logic that probably isn't what you want.
