### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by pranavmondhe** [numpy/numpy#14015]
Hi Folks,
I am using Python 3.7.3 on Windows10 using Pycharm 2019.1.3 Community Edition for testing some application.
I have installed numpy version = 1.15.4.

Below is the error while running my application- I have no idea how to solve this please help!!!

*****************************************************************************************************
C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\Scripts\python.exe C:/S3/Tools/OPCUA_Client/app.py
Traceback (most recent call last):
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/S3/Tools/OPCUA_Client/app.py", line 1, in <module>
    from uaclient.mainwindow import main
  File "C:\S3\Tools\OPCUA_Client\uaclient\mainwindow.py", line 21, in <module>
    from uaclient.graphwidget import GraphUI
  File "C:\S3\Tools\OPCUA_Client\uaclient\graphwidget.py", line 14, in <module>
    import pyqtgraph as pg
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\pyqtgraph\__init__.py", line 19, in <module>
    import numpy  ## pyqtgraph requires numpy
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.

*****************************************************************************************************

**Comment by mattip** [comment]
It is hard to tell what the core problem is. Here are a few suggestions of directions you can try:
Where did you get your python and numpy? Are other users of this app able to use it?

If you open a dos console cmd.exe and run the following line, does it succeed? What does it print?
```
C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\Scripts\python.exe -c "import sys; print(sys.version); import numpy; print(numpy.__version__)"
```

**Comment by pranavmondhe** [comment]
@mattip 
Thanks for your reply.
I have installed python from python.org and numpy from pip inside a virtual environment.

I ran your command. I got the same error which is listed above. Please see its output:--

C:\Users\INUpm>C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\Scripts\python.exe -c "import sys; print(sys.version); import numpy; print(numpy.__version__)"
3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Traceback (most recent call last):
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.

**Comment by mattip** [comment]
There should be a file in `C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\.libs\*.dll`. The `_multiarray_umath.pyd` module in the pip package (the one that is failing to load) depends on this. Perhaps there is a problem with your `PATH` variable that is causing the `PATH` mangling we do when loading NumPy to fail. You could try any of these (assuming the directory is the one I note):
- check that your PATH environment variable is not too long and that all the directories in it exist
- manually prepend the directory to your PATH environment variable before you start pycharm and/or python rather than depending on NumPy to append it:  `set PATH=<path-to-.libs>;%PATH%`
- use the pip package from 1.17rc1 via `pip install --upgrade --pre numpy` (we changed the method we use to work around this problem in numpy 1.17)
- use conda rather than python from python.org and then conda install numpy.

**Comment by pranavmondhe** [comment]
Hi @mattip 
There was no such file from my path(C:\S3\PLC_EmbeddedEnv\AutoTestEnv37\lib\site-packages\numpy\.libs\*.dll) in my virtual environment for python3.7.3

Then i re-created virtual environment using python 3.7.4 and while installing same numpy version(1.15.4) - IT WORKED. 

Later on i found out the my old virtual env had no issue (i just copied that dll under .libs folder from above path - it worked fine)

So the question is - Is this okay? Or better to download 1.17rc1 ?

There is another big issue : whenever i give pip --version i get error as fatal error in launcher.
Please see attach file.
Not sure if my virtual env is okay.

![error](https://user-images.githubusercontent.com/49450244/61303650-c8356980-a7df-11e9-9a84-db3839dee818.PNG)

**Comment by mattip** [comment]
Glad you found the problem. It seems your virtualenv is not okay. That is the beauty of virtuanenv, you can just rebuild from scratch and wipe the old one. `python -m pip freeze > requirements.txt` then build a new base virtualenv and `python -m pip install -r requirements.txt`

**Comment by pranavmondhe** [comment]
HI @mattip 
Everytime i build a new virtual env, pip --version gives me that error. Do need to file a new issue? My virtual env looks fine as i can upgrade packages and upgrade pip okay.
Just pip --version doesn't works everytime on any newly created environments.

While installing i latest numpy found that **1.17rc2** also got released not sure which to use now or shall i stay with rc1 ?

**Comment by mattip** [comment]
Somehow you are calling (shortened for clarity) `python.exe pip.exe --version` rather than `pip.exe --version` or `python -m pip --version`. 
1.17rc2 was release a few minutes ago.

**Comment by pranavmondhe** [comment]
Hi @mattip 
python -m pip --version command worked in my virtual env. 

Wondering why pip --version doesn't works when virtual env is created, commited in svn and then checked-out in another m/c then pip --version doesn't work though it worked on PC where we first create it.

I will close this issue now since issue is resolved. Much Thanks.

**Comment by pranavmondhe** [comment]
Issue resolved.!!!

**Comment by kbantoec** [comment]
Download this wheel file and add it in your `C:\Users\<username>` folder: https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy.

Execute `pip install <wheel file> --user` for instance from your command line.  In my case, the wheel file was `numpy-1.18.4+mkl-cp38-cp38-win_amd64.whl`.

Make sure all other dependencies are up to date. You can for instance execute `pip install <package> --upgrade` if a package needs to be upgraded.

Hope this will help someone.
