### ISSUE TITLE
np.char.split returns an array of lists, not a 2d array

### ISSUE THREAD

**Issue by Msegade** [numpy/numpy#14014]
The returned array of the function np.char.split gives an array of list, which has to be further processed to produce a normal 2d numpy array

### Example

```python
>>> a = np.array([['0.1 0.2 0.3'], ['0.3 0.4 0.5'], ['0.5 0.6 0.7']])
>>> np.char.split(a)
array([[list(['0.1', '0.2', '0.3'])],
       [list(['0.3', '0.4', '0.5'])],
       [list(['0.5', '0.6', '0.7'])]], dtype=object)
```

### Solution 

To ease the processing of the arrays, it will be better to have the function return 

```python
array([['0.1', '0.2', '0.3'],
       ['0.3', '0.4', '0.5'],
       ['0.5', '0.6', '0.7']], dtype='<U3')
```

**Comment by eric-wieser** [comment]
What would you have the following produce?
```python
>>> a = np.array([['0.1 0.2'], ['0.3 0.4 0.5 0.6']])
>>> np.char.split(a)
```

**Comment by Msegade** [comment]
Ok, I see the issue. Maybe a function argument that generates the 2d array if the resulting lists have the same length, and otherwise raises an exception?

`np.char.split(a, homogeneous_array=True)`

**Comment by amjangde** [comment]
First convert the array (i.e. array of lists returned by the split() method) to list. So now we have list of lists. And now use 'np.array()' method to convert the list (i.e. list of lists) to a 2D array.

Please refer this [converty numpy array of arrays to 2d array
](https://stackoverflow.com/questions/50971123/converty-numpy-array-of-arrays-to-2d-array)

example:

date_cols = ['2012-12-12', '2011-11-11', '2010-10-10']

date_cols = np.char.split(date_cols,'-') 

//here we will get array of lists
//date_cols will look like -> [list(['2012', '12', '12']), list(['2011', '11', '11']), list(['2010', '10', '10'])]

date_cols = date_cols.tolist()
date_cols = np.array(date_cols)

//date_cols will look like this -> [['2012' '12' '12'] ['2011' '11' '11'] ['2010' '10' '10']    which is a 2D array

**Comment by eric-wieser** [comment]
A way to solve this is to use:
```python
def array_of_lists_to_array(arr):
    return np.apply_along_axis(lambda a: np.array(a[0]), -1, arr[..., None])
```
