### ISSUE TITLE
When I import packages from a folder，I got the following problem.

### ISSUE THREAD

**Issue by wasdfghjklr** [numpy/numpy#14016]
### Reproducing code example:

```python
import sys
sys.path.append('../')
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from models.graphicalLasso import GraphicalLasso as GL
```

### Error message:
In [6]:from models.graphicalLasso import GraphicalLasso as GL
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

Kernel died, restarting

### Numpy/Python version information:

python 3.7.1
numpy 1.15.4

**Comment by seberg** [comment]
@wasdfghjklr you will have to give details on how you installed numpy (and maybe that models module) also things such as if you are using anaconda/pip (both). The usage of `sys.path.append` before numpy makes me a bit worried. Numpy has to be compiled and installed properly and it looks like it might not be (I would also encourage you to look into not using `sys.path` for your own `models` module)

**Comment by seberg** [comment]
No more details and likely an installation support question to begin with, closing.
