### ISSUE TITLE
Feature request: memory efficient interface for eigh and similar eigensolvers

### ISSUE THREAD

**Issue by refraction-ray** [numpy/numpy#14024]
This is a feature request and the proposal only show differences when the dimension of matrix is very large. Specifically, this proposal is useful only when one wants to solve full eigenvalue problems on a matrix as large as possible on given hardwares. 

Say `m` is a very large real symmetric matrix, to get the full eigen spectrum, we can use `np.linalg.eigvalsh(m)`. The underlying Lapack routine is `dsyevd('N',...)` which requires only O(N) extra work space besides the matrix itself (N^2) with the cost that the matrix `m` is changed after eigenvalue problem solving. Namely, the original matrix is not kept in the routine. The total memory requirement is $8(N^2+2N)$ for real (double) symmetric matrix `m` with size N*N. In the implementation of numpy, it is definitely necessary to keep `m` when calling `eigvalsh(m)` by default, and therefore the memory requirement on the same problem is at least $8(2N^2+2N)$ due to a copy of original matrix.

It would be better that there are some interfaces in numpy that can directly do `dsyevd` without copy `m`. Namely, `m` should be some rubbish after calling `eigvalsh_mem(m)`, only return values from this function make sense. The gain is that now we can solve eigenvalue problems with memory of order N^2 instead of 2N^2 in python; we have save half of the memory as well as the time to copy large matrix `m`. I believe other eigen and svd decom wrappers follow the same arguments. Note, lapack wrappers in scipy doesn't solve this issue, since their interface also keeps the original matrix. 

Of course, all these discussions are only relevant after the fix of https://github.com/numpy/numpy/issues/13956. Otherwise, the limitation of possible matrix size is not from hardwares but from 32bit int parameters for `lwork`.

One may argue that such new interfaces which destroy input array are counterintuitive and not pythonic at all, and I admit this.

**Comment by seberg** [comment]
Hmm, I am not sure that we should go there inside NumPy on first sight. I believe there are lowlevel access functions in scipy (or are those only available from cython) for which you have to take care of everything, but it will save a lot of overhead.

My first impression would could mention this in some form (although, not immediately sure where, maybe a note on the overview page) in the documentation.

**Comment by seberg** [comment]
I am pretty sure scip.linalg.lapack has pretty much exactly this. If not, we can reopen (although even if not, scipy is probably the better place).

**Comment by refraction-ray** [comment]
@seberg, I have verified scipy.linalg.lapack routines, at least `dsyevd`, the original matrix is still kept in python context, which make the memory overhead the same as numpy.linalg.eigh. But it may be ok the issue is kept closed, since it might not be a good idea to implement such interface in python which destroy the original matrix (it is just too counterintuitive in python). And I agree scipy is a better place to do that if necessary, namely there should be another interface on lapack that lower than scipy.linalg.lapack wrapper.

**Comment by seberg** [comment]
@refraction-ray to be honest, there seems to be an argument `overwrite_a` did you check the documentation?

**Comment by refraction-ray** [comment]
@seberg , Yes, I have tried this flag. Somehow, the memory usage is still around two matrix 16N^2 instead of one 8N^2. I used something like this: `la.lapack.dsyevd(h,compute_v=0,lwork=2*h.shape[0]+1,overwrite_a=1)`. The time it required is also much longer than a direct call on Lapack routine in C. Also the final matrix `h` seems to be the same after the calculation. No idea why.
