### ISSUE TITLE
DOC: Merge two indexing documentation pages 

### ISSUE THREAD

**Issue by sameshl** [numpy/numpy#14038]
xref:https://github.com/numpy/numpy/issues/12195
Currently we have:

    https://docs.scipy.org/doc/numpy-1.15.0/user/basics.indexing.html
    https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html

I added a link between each other on pr https://github.com/numpy/numpy/pull/14025 but the info still remains a bit haywire and lot of the info could be merged.
Making it a issue so I could get any suggestions on how they could be improved. I will start working on this

EDIT: latest versions:
- https://numpy.org/devdocs/user/basics.indexing.html
- https://numpy.org/devdocs/reference/arrays.indexing.html

**Comment by sameshl** [comment]
@mattip Not much actually :sweat_smile:. But I can finish it by the end of this weekend. It would greatly help if I could get a rough TOC of how the indexing pages could be.

**Comment by mattip** [comment]
I think the user page should be greatly reduced, and refer to the reference page for more information. Perhaps the basic idea below should be echoed on the user page, with a link to the reference page. I would remove the "Single element indexing", "Other indexing options", "Index arrays", "Indexing Multi-dimensional arrays", "Boolean or “mask” index arrays", and "Combining index arrays with slices", but make sure the content exists on the `reference` page. The other sections are a bit different, and contain information that could stay there.

I like the layout of the `reference` page. The information you remove from the `user page about mixing indexing types should be merged in under `Advanced Indexing".

> ndarrays can be indexed using the standard Python x[obj] syntax, where x is the array and obj the selection. There are three kinds of indexing available: field access, basic slicing, advanced indexing. Which one occurs depends on obj.

Of course once we see how it looks maybe we will decide to rearrange it differently.

**Comment by PraveshMoelchand** [comment]
Hi @sameshl, have you made any progress with this? I'd like to help out with this issue!

**Comment by sameshl** [comment]
@PraveshMoelchand I have not done much on this issue. You can take this up :+1:

**Comment by rgommers** [comment]
Latest versions:
- https://numpy.org/devdocs/user/basics.indexing.html
- https://numpy.org/devdocs/reference/arrays.indexing.html
