### ISSUE TITLE
IPython completion problem

### ISSUE THREAD

**Issue by Bucchiman** [numpy/numpy#14031]
Dear Numpy commiter,

I installed `IPython==7.6.1` and then `Numpy==1.16.4`.
I excuted IPython and import Numpy.
However, the completion of IPython was not working for Numpy.

```
$ ipython
>> import numpy as np
>> a = np.    # Then I pushed the TAB key, but the completion was not working.
```

I comfirmed this problem was solved on less than `Numpy==1.15.x`.

Sincerely,

**Comment by seberg** [comment]
I just tried it and can reproduce this on a new IPython version, however, I have the exact same problem with `import math` and `math. …`, so I think this should have to do with IPython. @Bucchiman can you reopen this as an IPython issue? If they think there is anything to be done on numpys side, we can reopen/open a new one.
