### ISSUE TITLE
DOC: Emphasize the need to run tests when building from source

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#14037]
xref #12991 

We should emphasize the need to run tests as part of the documentation for [building numpy from source](https://www.numpy.org/doc/1.17/user/building.html) and in the developer setup [build page](https://www.numpy.org/doc/1.17/dev/development_environment.html#building-in-place). At the same time, the second page should defer to the first as it has more complete instructions.

**Comment by sameshl** [comment]
@mattip Shoudn't the [first page](https://numpy.org/doc/1.17/user/building.html) link to the --> [second page](https://numpy.org/doc/1.17/dev/development_environment.html#building-in-place) as the second one has more info regarding running tests?

**Comment by mattip** [comment]
Sounds good. So one would emphasize the build instructions and variants, and the other the tests and variants.993489
