### ISSUE TITLE
Bug report in np.linalg.matrix_rank

### ISSUE THREAD

**Issue by youkaichao** [numpy/numpy#14047]
Somehow I find [this](https://drive.google.com/open?id=1jZHjnOyAxK--4TD0bgppKtFGtfiNn0N8) magic matrix that fails the `np.linalg.matrix_rank` function.

### Reproducing code example:

```python
import numpy as np

data = np.load('tmp.npy')

data.shape # (810000, 9)

np.linalg.matrix_rank(data) # 7

np.linalg.matrix_rank(data[190:300]) # 9
```

### Numpy/Python version information:

1.16.2 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

**Comment by seberg** [comment]
Your matrix probably has a bad condition number: https://en.wikipedia.org/wiki/Condition_number check `np.linalg.cond`. As noted in the documentation, the code uses SVD to find the matrix rank which is numerically pretty good, but there are always tiny errors that can push you on the wrong side of things if your matrix is badly conditioned.

**Comment by seberg** [comment]
I am pretty sure `scip.linalg.lapack` has pretty much exactly this. If not, we can reopen (although even if not, scipy is probably the better place).

**Comment by seberg** [comment]
Whooops wrong issue, but probably right to close anyway, just comment if you are not satisfied or think there is more going on.

**Comment by youkaichao** [comment]
I checked the condition number using `np.linalg.cond`, it is `16.05493`, which is not very bad, I assume.

**Comment by pv** [comment]
The reason is the default value for `tol=` keyword:
```
tol : (...) array_like, float, optional
    threshold below which SVD values are considered zero. If `tol` is
    None, and ``S`` is an array with singular values for `M`, and
    ``eps`` is the epsilon value for datatype of ``S``, then `tol` is
    set to ``S.max() * max(M.shape) * eps``.
```

**Comment by youkaichao** [comment]
@pv Thanks for your reply! After replacing the `tol` argument with `1e-10`, I get the correct result.
I'm confused with the default `tol` though, which is dramatically large for large matrix.
