### ISSUE TITLE
np.sum() will return NA if one element of the vector is na 

### ISSUE THREAD

**Issue by isaac-you** [numpy/numpy#14054]
```
v1 = np.random.randint(100,size=1000,dtype=np.float)
v1[np.random.randint(30,size=10)] = np.nan
v1.sum()
Out[131]: nan
```
np.__version__
Out[132]: '1.16.2'

python 3.6 

So if there is one element is NA , then the np.sum(v1) will be NA
Is there the parameter to control the NA 
for example skip the NA  then sum the rest of the elements 
Thank you

**Comment by johannfaouzi** [comment]
[numpy.nansum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nansum.html) sounds like what you are looking for.

**Comment by seberg** [comment]
Thanks @johannfaouzi, indeed (possibly also the `where` kwarg for ufuncs). There is also MaskedArrays in numpy, which may or may not be useful to you depending on how much you work with masked data. Pandas in some cases has slightly more straight forward support for NA data.
