### ISSUE TITLE
NumPy 1.17 RC fails to compile with Intel C Compile 2016

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [numpy/numpy#14059]
Compiling NumPy 1.17.0rc2 sources with Intel C Compiler 2016, which does not yet implement `__builtin_cpu_supports("avx512f")` fails with compilation error:

```
icc: numpy/core/src/umath/cpuid.c
numpy/core/src/umath/cpuid.c(63): catastrophic error: invalid use of '__builtin_cpu_supports'
compilation aborted for numpy/core/src/umath/cpuid.c (code 1)
```

Recent Intel C compiler (2019) proceeds just fine.

There is config test to probe compiler for support of `__builtin_cpu_supports`, but the the test does not discriminate between supported arguments.

**Comment by oleksandr-pavlyk** [comment]
@mattip This is the issue with 1.17 sources and older compiler that I mentioned at the sprint.

To reproduce I did:
    1. `conda create -n b_np117 -c defaults --override-channels python setuptools cython pip pytest mkl-devel`
    2. `git clone http://github.com/numpy/numpy.git --branch maintenance/1.17.x numpy_src`
    3. `conda activate b_np117`
    4. Edit `site.cfg`. So that
```
(b_np117) [16:15:03 vmlin numpy_src_tmp]$ cat site.cfg
[mkl]
library_dirs = /tmp/miniconda/envs/b_np117/lib
include_dirs = /tmp/miniconda/envs/b_np117/include
lapack_libs = mkl_rt
mkl_libs = mkl_rt
```
5. Check compiler version:
```
(b_np117) [17:02:25 vmlin numpy_src_tmp]$ icc --version
icc (ICC) 16.0.3 20160415
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
``` 
6. Execute `CFLAGS="-DNDEBUG -I$PREFIX/include $CFLAGS" python setup.py config_cc --compiler=intelem config_fc --fcompiler=intelem build --force build_ext --inplace`

**Comment by mattip** [comment]
It seems we need someone with that compiler to test and fix this.

**Comment by oleksandr-pavlyk** [comment]
I definitely volunteer with testing and fixing it, but I would appreciate some guidance as what to try tweaking and where.

**Comment by seberg** [comment]
Pinging @r-devulap, maybe you can have a look/know something? It seems he wrote (or modified it and is also at Intel – albeit a very different part).

**Comment by r-devulap** [comment]
@oleksandr-pavlyk could you try this fix from my branch https://github.com/r-devulap/numpy/tree/avx512-cpuid and let me know if that fixes your problem. If it does, I can submit a PR.

**Comment by r-devulap** [comment]
never mind, created a PR with a simpler fix.
