### ISSUE TITLE
len(ndarray.data) wrong

### ISSUE THREAD

**Issue by 2xB** [numpy/numpy#14067]
### Reproducing code example:

```python
import numpy as np
a = 10
b = 20
arr = np.zeros((a, b))
print(len(arr.data))
print(len(bytes(arr.data)))
```

Expected: `len(arr.data)` should be the same as `len(bytes(arr.data))`.
Reality: `len(arr.data)` is the same as the size of the array in its first direction (namely `a` in this example).

### Consequence
Sending and receiving multi-dimensional arrays via `multiprocessing.Pipe.send_bytes` does not work reliably on multi-dimensional arrays:

```python3
import numpy as np
from multiprocessing import Pipe
p1, p2 = Pipe()
arr = np.zeros((3, 5, 6), dtype=np.uint8)
p2.send_bytes(arr)
pm = p1.recv_bytes()
print(pm)
```

### Numpy/Python version information:

numpy 1.16.4
Python 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]

**Comment by pv** [comment]
```
>>> type(arr.data)
<class 'memoryview'>
```
which is a pure-Python object. If you believe it's a bug, it's a Python bug (probably in `multiprocessing.Pipe.send_bytes`).

**Comment by eric-wieser** [comment]
Looks like user error to me. `sendbytes` is presumably expecting a 1d buffer object of type byte, such as `bytes` or `bytearray`.  Is there a reason you don't just use `.send`?

**Comment by rkern** [comment]
Well, `ndarray.data` used to be a `buffer` on Python 2, so that code snippet used to work. Now, it's a `memoryview` on Python 3. Which is generally an improvement, but the two are not interchangeable. Importantly, right now, it doesn't look like there's a straightforward way to just get a memory buffer of the data of an array (assuming contiguity) that looks like a bytestring without copying.

**Comment by rkern** [comment]
I guess `p2.send_bytes(arr.data.cast('B'))` would work.

**Comment by rkern** [comment]
Arguably, that's what `send_bytes()` should be doing when it gets a `memoryview`-able object that has a different format, so I'd still agree that the place to fix would be `multiprocessing`.

**Comment by eric-wieser** [comment]
Looking more closely at the behavior of `os.write`, it seems that writing any binary object to a file / pipe is usually allowed. So in this case, `multiprocessing` should be using
```diff
-n = len(buf)
+buf = memoryview(buf)
+n = buf.nbytes
```
