### ISSUE TITLE
Multiplication produces "q"-dtype outputs from "l"-dtype inputs

### ISSUE THREAD

**Issue by dcolascione** [numpy/numpy#14075]
```
In [75]: (np.int64(8020016004) * np.asarray([np.int64(12342124)])).dtype.char      
Out[75]: 'q'
```

The result here is `q`. I'd expect it to be `l`, because both inputs have the `l`-dtype.  For smaller multiplications, the conversion doesn't happen:

```
In [77]: (np.int64(3) * np.asarray([np.int64(12342124)])).dtype.char               
Out[77]: 'l'
```

**Comment by eric-wieser** [comment]
Two things are happening here:

* Numpy has inherited weird value-based type promotions when one input is scalar or 0d
* Numpy is inconsistent between picking between `long` and `long long` when both are 64-bit, but nothing should care about that anyway

**Comment by seberg** [comment]
Going to close this, as the issue (if it is an issue) is in the value-based logic, which is phased out with NEP 50 on main/NumPy 2.0.  I.e. that code is scheduled for deletion, it should normally be unused.
