### ISSUE TITLE
`test_ufunc_noncontiguous` too restrictive

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [numpy/numpy#14087]
Numpy 1.17 has added `numpy.core.tests.test_ufunc.py::test_ufunc_noncontiguous`, which insists that result of ufunc applied to an array be bit-wise identical, using `assert_equal` for strided and non-strided loops.

These tests might fail (as they do in Intel patched NumPy), if different implementations of universal function loop are used depending on the stride.

For example:

```
>>> svml_res = np.arccosh(np.arange(1,7, dtype='f'))
>>> libm_res = np.array([np.arccosh(x) for x in np.arange(1,7, dtype='f')], 'f')
>>> svml_res == libm_res
array([ True,  True,  True,  True,  True, False])
>>> svml_res - libm_res
array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 2.3841858e-07], dtype=float32)
>>> (svml_res - libm_res)[-1]
2.3841858e-07
>>> np.finfo('f').eps
1.1920929e-07
``` 

The failure is at 2 epsilons of the type.

So this test essentially precludes using different implementations for different strides.

How do you feel about relaxing `np.testing.assert_equal` to `np.testing.assert_almost_equal` with absolute/relative tolerance set to a multiple of type's epsilon ?

N.B.: OpenCL 2.0 standard mandates of implementation to uniformly be withing several ULPs of the true value.

**Comment by charris** [comment]
The test should be changed. Note that we no longer recommend `assert_almost_equal` for these
```
    .. note:: It is recommended to use one of `assert_allclose`,
              `assert_array_almost_equal_nulp` or `assert_array_max_ulp`
              instead of this function for more consistent floating point
              comparisons.
```

**Comment by charris** [comment]
Forgot to add that a PR would be welcome.

**Comment by oleksandr-pavlyk** [comment]
@charris Goes without saying. Will have it ready in a bit.
