### ISSUE TITLE
Typo in c-api/array.rst doc

### ISSUE THREAD

**Issue by f380cedric** [numpy/numpy#14099]
In `numpy/doc/source/reference/c-api/array.rst` ([line 3380](https://github.com/numpy/numpy/blame/691e6dbe1fd70c7638daf3ab38e877419babeed2/doc/source/reference/c-api/array.rst#L3380)), there is an "Equivalent to", but the sentence has not been completed.

**Comment by colinsnyder** [comment]
.. c:function:: NPY_BEGIN_THREADS_DESCR(PyArray_Descr *dtype)

        Useful to release the GIL only if *dtype* does not contain
        arbitrary Python objects which may need the Python interpreter
        during execution of the loop. Equivalent to



Unless someone has an idea of where to go with that sentence, I can just remove it.
