### ISSUE TITLE
New characteristic to cumsu

### ISSUE THREAD

**Issue by josephnowak** [numpy/numpy#14107]
Hi, I would like to know if is possible to add to the cumsum method the option to make an operation (multiplication of a constant for example or a lambda function) while it is making every sum to get something like this: https://stackoverflow.com/questions/34182755/cumulative-addition-multiplication-in-numpy, I know this could look a little unnecesarry but this kind of cumulative sum appears in some formulas of economic indexs and I think there are other cases where this can be useful. The reason of this request is that when the data is very big use a normal python loop is not a nice option due to the time it take.

**Comment by shoyer** [comment]
I'm sorry, but I don't think this operation is useful enough across a range of applications to make sense in NumPy. We try to be pretty strict about pushing domain specific functionality to other packages these days, to minimize the growth of NumPy's maintainence burden.

**Comment by rgommers** [comment]
agreed, that's too specific, closing. thanks @josephnowak and @shoyer
