### ISSUE TITLE
mypy static type check raises no stub file for module 'numpy'

### ISSUE THREAD

**Issue by QuantumNovice** [numpy/numpy#14105]
### Reproducing code example:

```python
# below is line 9
from numpy import array, cos, sin, radians, cross 
```
```batch
py -m mypy in_static_equilibrium.py
```

### Error message:
```batch
in_static_equilibrium.py:9: error: No library stub file for module 'numpy'
in_static_equilibrium.py:9: note: (Stub files are from https://github.com/python/typeshed)
```

### Numpy/Python version information:
Python 3.7.3
Numpy 1.16.4
`1.16.4 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`

**Comment by ksunden** [comment]
Numpy does not have stable type hints at this time.

There is a repo that has experimental type hints: 
https://github.com/numpy/numpy-stubs

It's a hard problem to specify numpy's existing typing system (which predates PEP484) within the language type hints.

See also #7370

**Comment by seberg** [comment]
Thanks @ksunden, lets close this. The stubs is not a super active repository right now. So @QuantumNovice if you want to contribute it, that is of course very welcome.
