### ISSUE TITLE
Can numpy.ma module give some warnings when result is MaskedConstant(--)?

### ISSUE THREAD

**Issue by 12ycli** [numpy/numpy#14111]
While using numpy.ma module in some complex operation, sometimes the result can be `MasedConst(--)` because every element is masked. `MasedConst(--)` is Nan outside of numpy.ma. This can be avoided carefully. However, sometimes I just forget about it. Take `np.ma.sum(masked_patch1 - masked_patch2)` for example, this works as we expected most of the time. However, sometimes you just got some errors which mention you got some Nan in your data and finally you realize sometime `np.ma.sum` output `MasedConst(--)` because `masked_patch1 - masked_patch2` can get all elements masked.
I suggest numpy.ma module would give some warnings when result is MasedConst(--) so programmer can get some hints their input to the function is array all masked.

**Comment by seberg** [comment]
I honestly doubt that we want to create warnings there every time a masked constant is created.

Note that there is a warning when you do `float(MaskedConstant)`. It might be that this does not exist on older numpy versions (1.16 has it). Or maybe there are paths were the conversions happens without a warning?

We could discuss it though, can you give more details about what you are doing that the masked constant is converted to NaN without a warning?

**Comment by 12ycli** [comment]
Sorry! I just have noticed there is a warning when I do `float(MaskedConstant)`. 
This is my simplified code. I collected some features in a list and finally I convert them to `numpy.array`. I got the warning in the latter operation. However, in this situation, I have to check 
back to features and find out where I got a masked element. This gets messy when I collect all the features for millions of samples in the list and finally convert the list to array. 
Most the time we just use functions from `np.ma` expecting got some number but `MasedConst(--)`. This is like we do division when Denominator is zero. Some function warn you your Denominator is zero and some function just give you a INF without a warning. In my opinion, warning is better for knowing things are not as we expected.

```
def test_np_ma():
    array = np.array([[0,1],
                      [2,3]])
    print('array:', array)

    masked_array1 = np.ma.array(array, mask=[[True,True],[False,False]])
    masked_array2 = np.ma.array(array, mask=[[False,False],[True,True]])
    print('masked_array1:', masked_array1)
    print('masked_array2:', masked_array2)

    ret = np.ma.average(masked_array1 - masked_array2)
    print('ret:', ret)

    return ret


def test_np_ma2():
    features = []

    ret = test_np_ma()
    features.append(ret)

    # ... collect more features

    # ...finally we got all the samples and their features in element
    features = np.array(features)
    print(features)


if __name__ == '__main__':
    test_np_ma2()
```
I got information below.
```
F:/satellite/proj/test.py:123: UserWarning: Warning: converting a masked element to nan.
  features = np.array(features)
array: [[0 1]
 [2 3]]
masked_array1: [[-- --]
 [2 3]]
masked_array2: [[0 1]
 [-- --]]
ret: --
[nan]
```

**Comment by seberg** [comment]
@12ycli I do think this is intentional behaviour. Note that the only place where we opted to do something similar to what you suggest are the `np.nansum`, etc. style functions (and sometimes I am not sure anymore it was the right choice).

In your example there is a warning at the end? Do you feel that `test_np_ma` should give a warning? The problem with warnings is that they can be quite annoying (and not necessarily easy to silence), so I think this type of discussion should probably go the mailing list or have a concrete proposal.

**Comment by rgommers** [comment]
Our current design seems about right, and there's no more follow-up in this issue for >3 years, so let's close it. Thanks all!
