### ISSUE TITLE
Synchronize FFT implementation with scipy?

### ISSUE THREAD

**Issue by mreineck** [numpy/numpy#14116]
Scipy has now switched to an evolved version of the `pocketfft` library, which provides (among a few other new features) better performance for multi-dimensional transforms and full support for single and long double precision. The new `scipy.fft` module also provides an interface that is closer to `numpy.fft` than `scipy.fftpack` was.

It may be profitable if scipy and numpy could actually use one and the same code for their FFTs, but I'm not sure if this is possible, since `pypocketfft` is C++ and relies on `pybind11` for interfacing with Python.

Please feel free to close if this can't be done for whatever reason; I just wanted to put the suggestion on the table.

**Comment by rgommers** [comment]
Thanks for asking @mreineck. My sense of this is that the benefits are not significant enough to start requiring a C++ compiler and adding a new dependency. Also, we should probably just ship things first and let both NumPy and SciPy settle down a little before even considering a next overhaul.

**Comment by mreineck** [comment]
> Also, we should probably just ship things first and let both NumPy and SciPy settle down a little before even considering a next overhaul.

Absolutely! I didn't mean to say that this should be rushed. Then let's close this for now.
