### ISSUE TITLE
module 'numpy.core.umath' has no attribute 'matmul'   i upgraded pandas from 0.23.0   to 0.24.0  and numpy from 1.15 to 1.16.1

### ISSUE THREAD

**Issue by Waqar199230039** [numpy/numpy#14125]
Before with pandas 0.23.0 and numpy 1.15 version all was ok , but after i update i am getting this error 

module 'numpy.core.umath' has no attribute 'matmul'

**Comment by charris** [comment]
Hmm, there is something wrong with the install. How did you do the update?

**Comment by Waqar199230039** [comment]
find out the problem. there was two versions of numpy in path , removed one now working fine.
