### ISSUE TITLE
Synchronize np.load(allow_pickle=True) with scipy.sparse.load_npz

### ISSUE THREAD

**Issue by doumbouyarene** [numpy/numpy#14120]
Can't use scipy.sparse.load_npz since it's uses numpy.load which now requires allow_pickle to be explicitly set to True.

### Reproducing code example:

```python
import numpy as np
import scipy.sparse as sparse

user_indicator_features = sparse.load_npz(user_feat_file)
```

### Error message:

bash-3.2$ python main.py --task predict
Using TensorFlow backend.
1564089376.935315

Traceback (most recent call last):
  File "main.py", line 130, in <module>
    user_indicator_features = sparse.load_npz(user_feat_file)
  File "/anaconda3/lib/python3.7/site-packages/scipy/sparse/_matrix_io.py", line 131, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/Users/rdoumbouya/.local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 451, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

### Numpy/Python version information:
Python 3.7.3
Numpy 1.16.4
Scipy 1.2.1

**Comment by pv** [comment]
sparse.load_npz has always set allow_pickle=False, since files saved by
save_npz do not contain pickled data.
