### ISSUE TITLE
'import numpy' fails with 1.17.0 compiled with -O0

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [numpy/numpy#14137]
## Steps to reproduce

On a Linux box

1. Create conda env:  `conda create -n build_np_1_17_0 -c defaults cython setuptools pytest python`
2. Install MKL library into it: `conda install -n build_np_1_17_0 -c intel mkl-devel`
3. Activate the environment: `conda activate build_np_1_17_0`
4. Clone numpy and checkout v1.17.0 tag: `git clone http://github.com/numpy/numpy --branch v1.17.0 numpy_sources && cd numpy_sources`
5. Build numpy: `CFLAGS="$CFLAGS -O0 -g" python setup.py build_ext --inplace`.
6. Import: `python -c "import numpy"`.

```
Original error was: /tmp/numpy_sources/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: avx2_scalef_ps
```

With the default `-O3` flags it compiles and runs fine.

This likely has to do with use of `NPY_GCC_OPT_3` in the definition of `avx2_scalef_ps` in [simd.inc.src#L1227](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/simd.inc.src#L1227).

**Comment by oleksandr-pavlyk** [comment]
I forgot to mention editing `site.cfg` as follows:

```
$ cat site.cfg
[mkl]
library_dirs = /tmp/miniconda3/envs/build_np_1_17/lib
include_dirs = /tmp/miniconda3/envs/build_np_1_17/include
lapack_libs = mkl_rt
mkl_libs = mkl_rt
```

**Comment by r-devulap** [comment]
The only difference between `avx2_scalef_ps `and other `avx2_* `functions is that its missing the `static `keyword. Does the error go away when you make `avx2_scalef_ps ` static?
