### ISSUE TITLE
np.abs core dumps on array of size >= 2 ** 31

### ISSUE THREAD

**Issue by dmbelov** [numpy/numpy#14136]
The function `np.abs` causes segmentation fault when is called on array of size >= `2 ** 31`.  I guess, somewhere in the code one uses int32 for pointers instead of int64.

### Reproducing code example:

```python
import numpy as np
aa = np.ones(2 ** 31)
np.abs(aa)
```
Segmentation fault

### Numpy/Python version information:

1.16.4 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

**Comment by charris** [comment]
What platform are you running on? I get an out of memory error with this and 16B memory.

**Comment by seberg** [comment]
Maybe an intel patched anaconda? Unless it is simply a memor issue hitting in a bad way.

**Comment by dmbelov** [comment]
my machine has 1Tb of memory.  I rewrote function abs using Numba, and it
works without any problems.

**Comment by seberg** [comment]
Do you use an anaconda build with MKL? E.g. how did you install numpy, and is `numpy.__mkl_version__` defined (I forgot what the best ways to diagnose were)?

**Comment by dmbelov** [comment]
Yes, I have numpy linked with MKL.  I used default channel in conda to
install it.

**Comment by seberg** [comment]
@oleksandr-pavlyk do you think this might be one of the intel patches? part of a `CHUNKED_VML_CALL2` or so? @dmbelov I could try with a machine with enough memory some time next week. Or does this also occur with `np.float32`? Could you run a debugger? Say run it in `gdb`?

**Comment by mattip** [comment]
This issue is stale. Should we close it?

**Comment by seberg** [comment]
Yes, agreed. I just tried it with a machine with enough memory. Could be system related of course, but it is far more likely it was an Intel bug to begin with.
