### ISSUE TITLE
Fancy indexing on read-only memmap creates a read-only copy

### ISSUE THREAD

**Issue by jeremiedbb** [numpy/numpy#14132]
Fancy indexing on an array creates a copy. If the array is read-only, the copy is writeable and owns its data.
```python
a = np.array([1,2,3])
a.setflags(write=False)
b = a[[1,2]]
b.flags
>>>  C_CONTIGUOUS : True
     F_CONTIGUOUS : True
     OWNDATA : True  #
     WRITEABLE : True  #
     ALIGNED : True
     WRITEBACKIFCOPY : False
     UPDATEIFCOPY : False
```
However fancy indexing on a memmap creates a read-only copy.
```python
m = np.memmap('tmp', dtype='int', mode='w+', shape=(3,))
m[:] = a[:]
m = np.memmap('tmp', dtype='int', mode='r', shape=(3,))
b = m[[1,2]]
b.flags 
>>>  C_CONTIGUOUS : True
     F_CONTIGUOUS : True
     OWNDATA : False  #
     WRITEABLE : False  #
     ALIGNED : True
     WRITEBACKIFCOPY : False
     UPDATEIFCOPY : False
```
And it seems that it does not own its data, but then who is its base ?

**Comment by rth** [comment]
Also, in case anyone is wondering, `b` above is an array not a mmap,
```py
>>> m
memmap([1, 2, 3])
>>> b
array([2, 3])
```

**Comment by seberg** [comment]
The problem is here:
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/mapping.c#L1695

The writeable flag has to be cleared. The only tricky thing is to double check what flags are necessary at all (probably none, and just passing in 0 is fine).

Want to have a look?

**Comment by jeremiedbb** [comment]
@seberg 

I've looked at it and there's something I don't understand. When using fancy indexing, a new result array is created:
```c
result = PyArray_NewFromDescr(&PyArray_Type,
                              PyArray_DESCR(self),
                              PyArray_NDIM(ind),
                              PyArray_SHAPE(ind),
                              NULL, NULL,
                              /* Same order as indices */
                              PyArray_ISFORTRAN(ind) ?
                                  NPY_ARRAY_F_CONTIGUOUS : 0,
                              NULL);
```

and then, a new one may be created with this one as base:
```c
wrap_out_array:
    if (!PyArray_CheckExact(self)) {
        /*
         * Need to create a new array as if the old one never existed.
         */
        PyArrayObject *tmp_arr = (PyArrayObject *)result;

        Py_INCREF(PyArray_DESCR(tmp_arr));
        result = PyArray_NewFromDescrAndBase(
                Py_TYPE(self),
                PyArray_DESCR(tmp_arr),
                PyArray_NDIM(tmp_arr),
                PyArray_SHAPE(tmp_arr),
                PyArray_STRIDES(tmp_arr),
                PyArray_BYTES(tmp_arr),
                PyArray_FLAGS(tmp_arr),
                (PyObject *)self, (PyObject *)tmp_arr);
        Py_DECREF(tmp_arr);
        if (result == NULL) {
            goto finish;
        }
    }
```

Why is this step necessary ? What is the purpose of PyArray_CheckExact ?
In which situation returning the previously created array is problematic ?

**Comment by seberg** [comment]
@jeremiedbb the second call is for subclasses. The first call always returns an "exact" (non-subclass) numpy array. Since the first call only has the contiguity as flags, I do not think the second one requires any flags at all.

**Comment by jeremiedbb** [comment]
The second call uses the flags of `self`. Using the flags of `tmp_arr` solves the writeable issue.

However it does not solve the owndata issue. Since it's a call of `PyArray_NewFromDescrAndBase`, its base is `tmp_arr`. But it should not have a base, right ?

Why returning the array after the first call is not enough ?

**Comment by seberg** [comment]
The owndata is part is not an issue, there is nothing wrong with it having a base. This is because the subclass may need the data.

**Comment by jeremiedbb** [comment]
Thanks for the clarification. I opened #14171.
