### ISSUE TITLE
DOC: np.array(<numpy data type>, dtype=object).item() doesn't return python scalar

### ISSUE THREAD

**Issue by mroeschke** [numpy/numpy#14139]
### Reproducing code example:

```python
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np; np.__version__
'1.17.0'
>>> type(np.array([np.bool_(True)], dtype=object).item())
<class 'numpy.bool_'>
>>> type(np.array([np.int64(1)], dtype=object).item())
<class 'numpy.int64'>
```

From the `item` [docstring](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.item.html), I would expect the above example to still return `bool` and `int` respectively even if `dtype=object`. If this is the expected behavior, it would be great if the documentation was updated with this edge case.

**Comment by seberg** [comment]
This is not a bug, maybe the documentation could be clarified, although I am not sure, putting a numpy scalar into an `object` array, it should be clear that the numpy scalar is already a python object?

**Comment by mroeschke** [comment]
Sure, but the returned python object is still a numpy scalar and not the related python scalar as the docs would suggest.

I understand how the behavior is expected nonetheless.

**Comment by seberg** [comment]
I am open for doc improvement suggestions. Although, I have to admit I am not sure about how to make it better without making it unnecessarily complicated. Maybe saying that for an array with object dtype the elements are returned as-is. Anyway, suggestions/PR welcome.

**Comment by maximz** [comment]
Thanks!

Since `.item()` has this edge case, is there any other way to reliably extract the base-python-type equivalent of a numpy-typed object?

The use case (https://github.com/pandas-dev/pandas/issues/27616) is passing data to a serializer which only knows how to process vanilla python types.

**Comment by eric-wieser** [comment]
@maximz: you could call `item()` recursively - but your recursion would be unbounded for `np.longdouble`, for which item returns self.

**Comment by maximz** [comment]
@eric-wieser Thanks for your prompt reply!

Do you think that recursion should be the responsibility of `item()` itself, since the current docstring is `Copy an element of an array to a standard Python scalar and return it.`?

It strikes me as odd to build "call `item()` recursively till we no longer have numpy types" outside numpy itself. I think I would expect numpy to abstract away the details of converting back to standard python types, so that users don't have to worry about implementing this multiple invocation strategy themselves. But I defer to your perspective on the role of `item()`.

**Comment by eric-wieser** [comment]
`item()`'s job is to unpack a series of bytes into memory into a python object. If those series of bytes in memory happen to be a `PyObject *` then numpy's job is simply to hand you an `object`.

**Comment by maximz** [comment]
Thanks @eric-wieser !
