### ISSUE TITLE
Feature Request: Add SSPipe as a Submodule

### ISSUE THREAD

**Issue by jtelleriar** [numpy/numpy#14135]
Would it be possible to add (Port) SSPipe as a submodule in numpy?

https://pypi.org/project/sspipe/
https://sspipe.github.io/
https://github.com/sspipe/sspipe

It is a great feature, but if we want to use it as standard python programming syntax, it should be part of a well-supported package such as numpy.

**Comment by eric-wieser** [comment]
While a cool package, this doesn't strike me as within the scope of numpy at all

**Comment by jtelleriar** [comment]
This is how R's functional pipe works:

https://magrittr.tidyverse.org/

**Comment by rgommers** [comment]
agreed, anyone can use SSPipe, there's no reason it needs to live in numpy - and it's certainly out of scope. closing. thanks @jtelleriar
