### ISSUE TITLE
How to force build system to use a particular BLAS/LAPACK?

### ISSUE THREAD

**Issue by adamjstewart** [numpy/numpy#14146]
Hi, I'm a [Spack](https://spack.io/) developer and I've been playing around with our `numpy` package for awhile now. One issue that we've continually faced is the inability to tell `numpy` _which_ BLAS/LAPACK library we want to build with. We will create a `site.cfg` like:
```
[openblas]
libraries=openblas
library_dirs=/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/openblas-0.3.6-3yts3o25cqf437oxaa4qzfhiw3swc7j2/lib
rpath=/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/openblas-0.3.6-3yts3o25cqf437oxaa4qzfhiw3swc7j2/lib
```
which works great... unless MKL is installed on the system, in which case `numpy` decides to use that instead. Inevitably, the `rpath` isn't set (because we were never trying to build with MKL), and this leads to many problems at runtime. Some examples:

- https://github.com/spack/spack/issues/5327
- https://github.com/spack/spack/issues/6634
- https://github.com/spack/spack/issues/8616
- https://github.com/spack/spack/issues/10361
- https://github.com/numpy/numpy/issues/8653

Recently, we discovered a hack, where we can use a `site.cfg` like:
```
[openblas]
libraries=openblas
library_dirs=/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/openblas-0.3.6-3yts3o25cqf437oxaa4qzfhiw3swc7j2/lib
rpath=/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/openblas-0.3.6-3yts3o25cqf437oxaa4qzfhiw3swc7j2/lib
[mkl]
libraries=
library_dirs=
rpath=
[atlas]
libraries=
library_dirs=
rpath=
```
to prevent `numpy` from looking for MKL or ATLAS elsewhere. This worked fine, until the release of `numpy` 1.17.0, when we noticed build failures for `numexpr`: https://github.com/pydata/numexpr/issues/340

It seems like this isn't the right way to do things. So is there a better way to tell `numpy` which BLAS/LAPACK implementation to use?

@scheibelp @huqy @robbmcleod @scottwittenburg @s-sajid-ali

**Comment by seberg** [comment]
Maybe setting `NPY_LAPACK_ORDER=ATLAS,openblas,MKL` or similar can help you? I am not sure that one made it into the release notes. See also gh-13132

**Comment by s-sajid-ali** [comment]
From what I remember, numpy picks up MKL libraries if the MKL env vars are set regardless of what's present in site.cfg. Is this correct ?

**Comment by adamjstewart** [comment]
Thanks @seberg, I'll try that out and get back to you!

**Comment by adamjstewart** [comment]
As far as I can tell, this fix is working perfectly. I'll reopen if I encounter any more problems. Thanks for your help!
