### ISSUE TITLE
DOC: link to SciPy's multidimensional interpolation functions

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#14154]
### Reproducing code example:

np.interp currently requires its `fp` argument to be one-dimensional.  An obvious generalization would be to allow interpolation of `R->R^n` functions, by allowing `fp` to have shape (..., len(x)) (or (len(x), ...) -- whichever is consistent with e.g. polyfit).  Obviously the shapes of `left` and `right` should be adjusted accordingly.

Thoughts?

### Numpy/Python version information:

```
1.17.0 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
```

**Comment by parrenin** [comment]
I second this request.
It would make things a lot faster for multidimensional arrays.

**Comment by parrenin** [comment]
Another way to accomplish this would be to save the linear operator associated with an interp(x, xp, .) function and to apply that to various sets of fp.

**Comment by rgommers** [comment]
I agree with @mattip's change of the subject here: NumPy should not grow its interpolation functionality, but cross-link to `scipy.interpolate` in docstrings.

**Comment by rgommers** [comment]
Adding "good first issue". Note: please use intersphinx mapping for linking, i.e. a fully-qualified name with single backticks like so:
```
`scipy.interpolate.UnivariateSpline`
```

**Comment by LSchroefl** [comment]
May I try?

**Comment by rgommers** [comment]
@LSchroefl please go for it. No need to ask for permission, you can work on this or any topic that seems interesting to you.
