### ISSUE TITLE
Is `np.alen` in use/needed?

### ISSUE THREAD

**Issue by stuartarchibald** [numpy/numpy#14155]
This was opened on the Numba issue tracker: https://github.com/numba/numba/pull/4374

It seems like NumPy has a function `alen()`  which does AFAICT not appear in the documentation but evidently exists https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py#L2758. Git blame suggests it appeared in and hasn't changed since ~2005. I cannot see any places in the NumPy code base where this is used apart from its own unit tests. It also has some perhaps unusual behaviour, e.g.:

```python
import numpy as np
np.alen(np) # <--- yes this works !
```

I'm not sure what the use case for this function would be?
Perhaps it {c,sh}ould be considered for deprecation?

**Comment by seberg** [comment]
It is not surprising that this works. That said, I agree that we should deprecate it, there already is a good way to spell it with pythons `len` and it seems to just have strange (at least when thinking about it nowadays) behaviour.

**Comment by stuartarchibald** [comment]
Thanks for looking at this. In the context of seeing how to implement this in Numba's type constrained domain, what worked/didn't work was puzzling until we looked at the source. Seems like deprecating it would be a sensible plan, I will propose that Numba doesn't support it on this basis.

**Comment by seberg** [comment]
Well, numpy functions coerce to arrays very aggressively. The `ndmin=1` is a nice added touch ;). Sure, do not put it in. I am sure Ralf also did not include it into his `rnumpy` idea/start.

**Comment by stuartarchibald** [comment]
yeah, the `ndmin=1` was what was causing things we couldn't quite guess at :) Thanks for the feedback, much appreciated.

**Comment by guilhermeleobas** [comment]
Hi @seberg, I'd like to work on this. Can you point me some direction? Should I just remove any mention of `np.alen` from the source code?

**Comment by seberg** [comment]
No, the function needs a deprecation warning and at least one test exercising that deprecation. Please check other deprecated functions `np.core.numeric.load` seems to be such a function, so modeling after that may work.

**Comment by eric-wieser** [comment]
Closed in #14181

**Comment by stuartarchibald** [comment]
Thanks all!
