### ISSUE TITLE
Feature Request: Compatibility with high precision integer calculations

### ISSUE THREAD

**Issue by annacnev** [numpy/numpy#14167]
I have a simulation that deals with a lot of numpy matrices and arrays. At one point of the simulation, the numbers go towards infinity and then numpy converts them to Inf values, giving me an overflow error. The Inf values mess up the proceeding functions, and I just get out 'NaN' filled matrices. If I import gmpy high precision library, convert the np.float64 -> float-> gmpy.mpfr and then do the calculation and convert the answer back to float, everything works fine. However, this is not really efficient to do, and the final answer from that line comes out to something that the np.float64 dtype could handle, but the intermediate calculations to get to the correct output can't be done by numpy because of the very large numbers. 

It would be nice if when matrices or arrays are initialized, we could set how to handle overflow errors by defining a backup dtype to use. Example:

numpy.zeros((2, 1), dtype=np.float64, overflow=gp.mpfr') <-in this case use use np.float64, but if it's too big, use gp.mpfr with default set to None (use inf).

### Reproducing code example 

(this code is 2000+ lines long and takes 5 hours to run before the error is reproduced so I just am posting the snippet as to how I fixed it):

```python
import numpy as np
import gmpy2 as gp

		y = multiply(self.Hct_avg_mod[self.cycle_m - 1], self.C[0:self.c_elem, t - 1])
		for x in range(0, len(y)):
			z = gp.mpfr(float((y[x]-0.16438)/0.070943))
			self.cap_press[x] = float(7.0624 * z**9 + 52.852 * z**8 + 142.78 * z**7 + 149.52 * z**6 + 2.6376 * z**5 - 81.241 * z**4 - 7.5042 * z**3 + 36.224 * z**2 + 27.711 * z + 37.752)
```

**Comment by charris** [comment]
Is there no way you can fix the algorithm to use smaller numbers? Scaling, perhaps?

**Comment by annacnev** [comment]
no, the capillary pressure (cap_press) is a factor of maybe 200/400 variables in this simulation.. if I scaled the z factor then it would scale the cap_press and then scale all the rest. This is a code that I directly converted from Matlab to python, and Matlab handles the higher precision with no issues.. so I was recommending the feature because it would be nice if, in the future, numpy could be as powerful as Matlab so those in scientific computing have an open-source robust library to use rather than shelling out $$$ for Matlab.

**Comment by seberg** [comment]
OK, let me look at this a bit closer. For that formula to overflow, it is necessary for z to be larger then:
```
min_z_val = ((np.finfo(np.float64).max) / 7.0624 / 9)**(1/9)
print(min_z_val)
# 1.1224550830735295e+34
```
while the relative numerical precision of floating point numbers is less then `1e-16`. Since `min_z_val` is so large, the relative difference between consecutive terms is thus so large, that only the first term matters within the precision of floating point numerics.

Thus, unless I had some thinking error, you must be working with 32 bit floating point numbers or something similar, or what you describe is not even possible (with negative `z`), to achieve that the intermediate result can be infinite with the final result being finite.

As to some propitiatory software doing something different, I do not believe it will do what you suggest it does. What it might do is have a higher preference to give you 64 bit floating point numbers.

**Comment by seberg** [comment]
I think using the polynomial tools in numpy may also help with improving numerical precision here? I doubt the approach of writing out the polynomial directly like that is numerically the best way.

**Comment by annacnev** [comment]
Hey, I can send you the simulation if you’d like to run it. The error occurs about 4.5 hours in, but I can not send it publicly due to it being for academic research and not published yet. As for the propriety software, I can also send the full Matlab code and you’ll see it runs without overflow. The precision I need to is about 10**300, with the gmpy libraries added I get the exact same graph outputs as the Matlab code, without them I get NaN values and nothing so it has to be due to precision and that’s why I’m recommending the feature

**Comment by charris** [comment]
That is not a good way to compute a polynomial value. I know you didn't write the code, but it makes me suspicious :) It is also common to scale variables and matrices for numerical stability when polynomials are involved. Matlab uses single/double precision floats, as does numpy, so there is likely another cause of the problems somewhere in the code translation. Perhaps as Sebastian has suggested by 32 bit floats slipping in there someplace when the translation was made. For instance, there was no need to call float on the polynomial result, which makes me more suspicious about the translation. The polynomial coefficients themselves are of low precision. Note that if very large ranges are needed, there are facilities for working with logarithms.

Is `z` a scalar?

**Comment by annacnev** [comment]
ah, 32 bit float was the issue. Now I feel like a dweeb for missing that. Thank you can mark this as closed! Sorry for the fuss!

**Comment by charris** [comment]
No problem, we have all been there. Thanks for letting us know the upshot.
