### ISSUE TITLE
numpy.fft: Undocumented behavior of `s` argument

### ISSUE THREAD

**Issue by peterbell10** [numpy/numpy#14179]
Ref: scipy/scipy#10569

The `s` parameter for nd-fft functions is documented as being a "sequence of ints", however it is also possible to supply `None` in any of the elements and the corresponding default value is used. e.g.
```python
import numpy as np
x = np.arange(10)
assert np.fft.fftn(x, s=(None,)).shape == 10
```

This is a consequence of numpy using the 1d `fft` internally
https://github.com/numpy/numpy/blob/ee309d9bc6f1b4995397f95c1e279bdd977051ad/numpy/fft/pocketfft.py#L647-L648

Is this behaviour intentional? If so then it doesn't seem to be documented anywhere that I could see.

**Comment by mreineck** [comment]
The behaviour was already present before the pocketfft switch. Pity ... otherwise it would definitely have been an oversight.

**Comment by seberg** [comment]
I am not sure, I am OK with adding it to the documentation, or simply deprecating it. Adding it to the documentation seems like the easier step right now though and does not mean we cannot deprecate it later.
