### ISSUE TITLE
0-length ifft raises ZeroDivisionError instead of ValueError

### ISSUE THREAD

**Issue by peterbell10** [numpy/numpy#14176]
0-length `ifft` raises `ZeroDivisionError` instead of `ValueError`.

### Reproducing code example:

```python
import numpy as np
x = np.arange(10)
np.fft.ifft(x, 0)
```

### Error message:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<__array_function__ internals>", line 6, in ifft
File "/home/peter/.local/lib/python3.7/site-packages/numpy/fft/pocketfft.py", line 274, in ifft
      fct = 1/n
ZeroDivisionError: division by zero
```
Which is this line
https://github.com/numpy/numpy/blob/ee309d9bc6f1b4995397f95c1e279bdd977051ad/numpy/fft/pocketfft.py#L274

Whereas the expected error is from here
https://github.com/numpy/numpy/blob/ee309d9bc6f1b4995397f95c1e279bdd977051ad/numpy/fft/pocketfft.py#L52-L54

### Numpy/Python version information:

1.17.0

**Comment by peterbell10** [comment]
On a related note, `np.fft.fft(x, 0, norm='ortho')` also gives a division by zero warning.

**Comment by seberg** [comment]
Pinging @mreineck do yo uwant to have a quick look?

**Comment by sameshl** [comment]
@seberg I would like to work on this, but I can't figure out a way to intercept the `n<1` condition before ` fct = 1/n ` and then redirect to **Value Error** in `_raw_fft`. Any suggestions ?

**Comment by mreineck** [comment]
Hmm, how about computing `inv_fct` instead of `fct` everywhere in `pocketfft.py` and then simply check for `inv_fct==0` in _raw_fft?

**Comment by mreineck** [comment]
> Hmm, how about computing inv_fct instead of fct everywhere in pocketfft.py and then simply check for inv_fct==0 in _raw_fft?

If this is considered an acceptable fix, I can provide a PR during the next days.

**Comment by seberg** [comment]
I wonder what happened before. I did not check the code carefully, but that sounds good to me.

**Comment by mreineck** [comment]
I think there were some `max(N,1)` safeguards in the code originally. Let's see whether my fix works.

**Comment by mreineck** [comment]
> I wonder what happened before

Pre-1.17, the (unscaled) FFT was always carried out first, potentially raising an exception for zero-length transforms, and only afterwards the factor was computed and applied. Since `pocketfft` allows specifying a factor and possibly avoids an additional pass over the array, the computation moved ahead of the FFT.

**Comment by charris** [comment]
Removed the backport candidate label. An error message is raised, just not the preferred one. That can wait on 1.18.

**Comment by cvav-git** [comment]
Hi all! I just checked the above minimal code example and the error raised is correctly a `ValueError`; I believe this issue is successfully resolved so you can go ahead and mark it as closed. I'm using `numpy 1.18.4`.

**Comment by charris** [comment]
Thanks for the heads up.
