### ISSUE TITLE
Numpy load failure

### ISSUE THREAD

**Issue by acsavag20** [numpy/numpy#14172]
Numpy fails to load due to _mklinit 

### Reproducing code example:

```python
import numpy
```

### Error message:
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Ana
conda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\EID\AppData\Local\Continuum\anaconda3\lib\site-packages\pan
das\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\EID\AppData\Local\Continuum\anaconda3\lib\site-packages\num
py\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\EID\AppData\Local\Continuum\anaconda3\lib\site-packages\num
py\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

### Numpy/Python version information:

Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by seberg** [comment]
The error you copy pasted includes:
```
Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load. To activate this environment
please see https://conda.io/activation
```
which is exactly what is going on here. If you did the steps mentioned there, you may want to seek support for conda. If you continue to have issue, please just comment and we can reopen.
