### ISSUE TITLE
Weird dtype->f->(scanfunc|fromstr) inconsistency

### ISSUE THREAD

**Issue by zjpoh** [numpy/numpy#14173]
I found the following inconsistency in `PyArray_FromString`.

In the following line we check `dtype->f->scanfunc == NULL` to determine if the C function to read from string is defined.
https://github.com/numpy/numpy/blob/ee309d9bc6f1b4995397f95c1e279bdd977051ad/numpy/core/src/multiarray/ctors.c#L4003

If `dtype->f->scanfunc != NULL`, then `array_from_text` is called with `fromstr_next_element` to read the next element from string. 
https://github.com/numpy/numpy/blob/ee309d9bc6f1b4995397f95c1e279bdd977051ad/numpy/core/src/multiarray/ctors.c#L4017-L4021

However, the actual function that read from string is `dtype->f->fromstr`, not `dtype->f->scanfunc`.
https://github.com/numpy/numpy/blob/ee309d9bc6f1b4995397f95c1e279bdd977051ad/numpy/core/src/multiarray/ctors.c#L47-L51

This doesn't cause any breaking problem because, in the code, if `dtype->f->scanfunc` is defined then `dtype->f->fromstr` is also defined. However, I think it's easier to maintain if the check is checking the actual function.

Thoughts?

**Comment by seberg** [comment]
Sounds like a copy paste error from 20 years ago, PRs welcome.
