### ISSUE TITLE
ValueError: EOF: reading array data, expected 262144 bytes got 5924

### ISSUE THREAD

**Issue by msfchen** [numpy/numpy#14202]
I downloaded a GitHub repo (https://github.com/svakulenk0/tweet2vec_clustering) and tried to run it in the environment described below. But I was getting the ValueError shown in the title of the issue. I would hope to get some help here on how to resolve the issue.

### Numpy/Python version information:

The environment I tried:
python 2.7.16 + (numpy 1.16.3 or numpy 1.13.3 or 1.12.1)
python 2.7.13 + (numpy 1.12.1 or numpy 1.11.3)
theano 1.0.3, fastcluster (1.1.25 ~ 1.1.21 corresponding to numpy version)
in Windows 10 Enterprise 64-bit OS

### Reproducing code example:
In the downloaded repo, simply run the test_clustering_pipeline.py.

In the t2v.py
```
def load_params(path):
    """
    Load previously saved model
    """
    params = OrderedDict()

    with open(path,'r') as f:
        npzfile = np.load(f)
        for kk, vv in npzfile.iteritems():
            params[kk] = vv

    return params
```
The file that was tried to be loaded was the best_model.npz file in the model folder of the repo.

### Error message: 

```
======================================================================
ERROR: test_clustering_pipeline_cluster (__main__.TestClusteringPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_clustering_pipeline.py", line 38, in test_clustering_pipeline_cluster
    show_results=True, output_path=results_path, distance_threshold=1.6)
  File "C:\Temp\t2vd_cluster\clustering_pipeline.py", line 121, in run_pipeline
    embeddings = save_embeddings(tweets_path, models_path, embs_path)
  File "C:\Temp\t2vd_cluster\tweet2vec\encode_char.py", line 120, in save_embeddings
    embeddings = generate_embeddings([outfile, modelpath])
  File "C:\Temp\t2vd_cluster\tweet2vec\encode_char.py", line 55, in generate_embeddings
    params = load_params('%s/best_model.npz' % model_path)
  File "C:\Temp\t2vd_cluster\tweet2vec\t2v.py", line 105, in load_params
    for kk, vv in npzfile.iteritems():
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\t2vd\lib\site-packages\numpy\lib\npyio.py", line 243, in iteritems
    yield (f, self[f])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\t2vd\lib\site-packages\numpy\lib\npyio.py", line 224, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\t2vd\lib\site-packages\numpy\lib\format.py", line 664, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\t2vd\lib\site-packages\numpy\lib\format.py", line 811, in _read_bytes
    raise ValueError(msg % (error_template, size, len(data)))
ValueError: EOF: reading array data, expected 262144 bytes got 5924

======================================================================
ERROR: test_generate_embeddings (__main__.TestClusteringPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_clustering_pipeline.py", line 23, in test_generate_embeddings
    embeddings = generate_embeddings([tweets_path, MODELS_PATH])
  File "C:\Temp\t2vd_cluster\tweet2vec\encode_char.py", line 55, in generate_embeddings
    params = load_params('%s/best_model.npz' % model_path)
  File "C:\Temp\t2vd_cluster\tweet2vec\t2v.py", line 105, in load_params
    for kk, vv in npzfile.iteritems():
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\t2vd\lib\site-packages\numpy\lib\npyio.py", line 243, in iteritems
    yield (f, self[f])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\t2vd\lib\site-packages\numpy\lib\npyio.py", line 224, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\t2vd\lib\site-packages\numpy\lib\format.py", line 664, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\t2vd\lib\site-packages\numpy\lib\format.py", line 811, in _read_bytes
    raise ValueError(msg % (error_template, size, len(data)))
ValueError: EOF: reading array data, expected 262144 bytes got 5924

----------------------------------------------------------------------
Ran 3 tests in 0.031s

FAILED (errors=2)

```

**Comment by jwd0023** [comment]
Please try to make an easier-to-run reproducing code example. I spent around 30 minutes trying to get the random repository you linked to work (still doesn't work).

The issue is in the single line:

```for kk, vv in npzfile.iteritems():```

A (complete) reproducing code example is:

```
with open("models/best_model.npz") as f:
    print npzfile.values()
```

I couldn't figure out exactly why this causes errors, but looking at code examples using np.load() use it very differently. If you replace

```
    with open(path,'r') as f:
        npzfile = np.load(f)
        for kk, vv in npzfile.iteritems():
            params[kk] = vv
```

in the code with

```
    npzfile = np.load(path)
    for kk, vv in npzfile.iteritems():
        params[kk] = vv
```

Honestly, I think this is a case of the repository code being junky.

**Comment by msfchen** [comment]
Hi Joe, thank you so very much for the help. You suggestion of removing the line "with open …" indeed resolved the error. Best regards, msfchen

**Comment by seberg** [comment]
@msfchen I think you may want to try again using "rb" when opening a file. I expect that is the real fix here (although, I suppose for your particular code, passing a string is also fine).

**Comment by jwd0023** [comment]
@seberg @msfchen Changing to "rb" also does fix the issue. 

Either way, I think issue should be closed. This is an issue with application code, not Numpy.

**Comment by seberg** [comment]
Hmmm, but it is one of those things, where it may be possible to detect very quickly whether this is an error. For example by checking `.mode` or just specifically checking if the `type` is `_io.TextIOWrapper` to catch the common mistake.

**Comment by jwd0023** [comment]
Yeah, we could do something like ```assert(npzfile.zip.fp.mode == 'rb')```, but it seems a bit ugly.

Like I said in an earlier comment, if you look at common usage of np.load(), the path is used instead of a file. I'd personally prefer _disallowing_ files as inputs so that np.load() can take care of how the file should be opened.

There's probably good reason why it's done the way it is, however. I just don't know that reason.

**Comment by jwd0023** [comment]
Also quick note on the assertion if it's going to be added: make sure you use ```npzfile.zip.fp.mode``` and **not** ```npzfile.zip.mode```. 

Turns out ```assert(npzfile.zip.mode == 'r')``` is true for both r and rb modes. Only ```npzfile.zip.fp.mode``` distinguishes r from rb.

**Comment by msfchen** [comment]
Hi @seberg, thank you so very much for the suggestion of using "rb". It did resolve the error. The suggestion lead me to read more relevant explanations about the issue, such as [this](https://superuser.com/questions/677736/why-is-there-a-difference-between-text-and-binary-files-in-windows). Yes, this issue is not numpy issue. It's most likely that the author of the repo, and the npz file, used a non-Windows environment; but I use a Windows environment. I really appreciate you both for the tremendous help. Best regards, msfchen
