### ISSUE TITLE
Line integral function

### ISSUE THREAD

**Issue by AlexJohnson1995** [numpy/numpy#14218]
Is there any built-in function to calculate line integral on closed contour? Of course, it is possible to do some operations on paper to transform it into Riemann integral, but a built-in solution would do it better.

**Comment by charris** [comment]
No. This sounds more appropriate for some downstream package. Given the needed derivative of the curve, I'd guess that there are specialized variants of the standard integrators out there for doing that. Stackoverflow might be a better place to ask the question.
