### ISSUE TITLE
docs for numpy.linalg.norm inconsistent with behavior

### ISSUE THREAD

**Issue by Sohl-Dickstein** [numpy/numpy#14215]
The docs for numpy.linalg.norm say that 
```
x : array_like
Input array. If axis is None, x must be 1-D or 2-D.
```
while in practice, norm works as one might hope for higher dimensional inputs. e.g., the following code produces the correct norm:
```python
a = np.ones((2,3,4))
print(np.linalg.norm(a))
```
(it looks like the linalg.norm code has a "fast path" which is run in simple cases, and which doesn't enforce this restriction: https://github.com/numpy/numpy/blob/v1.17.0/numpy/linalg/linalg.py#L2472 ).

It's great that NumPy handles the situation correctly! The docs should probably be updated though. This led to inconsistent behavior in https://github.com/google/jax, which emulates the numpy API, where jax implemented the restriction from the docs.

(thanks to @hawkinsp for identifying the source of the differing behavior in jax, and the "fast path" in the numpy code)

**Comment by charris** [comment]
The documentation has been fixed, however there is currently a proposal to deprecate using norm for `ndim > 2`. @Sohl-Dickstein You should comment at #14719 if you want to keep the current behavior.
