### ISSUE TITLE
stray outdated copy of docs on ReadTheDocs

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#14226]
for `v1.11.0`: https://numpy.readthedocs.io/en/latest/

@shoyer you're listed as one of the two maintainers (not sure who the other person is), could you delete the deployed docs on RTD?

**Comment by shoyer** [comment]
Everything should be hidden now.

I'd be happy to share the credentials if anyone else wants to work with this...

**Comment by rgommers** [comment]
Thanks!

> I'd be happy to share the credentials if anyone else wants to work with this...

that may be useful in case we want to use this for anything in the future? could you add me (RTD username `rgommers`)?

**Comment by shoyer** [comment]
Done!
