### ISSUE TITLE
BUG: np.lexsort MemoryError on empty array with non-standard strides

### ISSUE THREAD

**Issue by batterseapower** [numpy/numpy#14228]
Numpy 1.17.0 raises MemoryError when using `lexsort` on an empty array with non-standard `strides`. If `strides` is the natural one, or if there is >= 1 element in the input, then it works as expected.

### Reproducing code example:

```python
import numpy as np

xs = np.array([], dtype='i8')
assert xs.strides == (8,)
assert np.lexsort((xs,)).shape[0] == 0 # Works

ys = np.array([0], dtype='i8')
ys.strides = (16,)
assert np.lexsort((ys,)).shape[0] == 1 # Works

xs.strides = (16,)
assert np.lexsort((xs,)).shape[0] == 0 # MemoryError
```

### Numpy/Python version information:

1.17.0 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]

**Comment by batterseapower** [comment]
The problem is that in the `needcopy` case of `PyArray_LexSort`, a length 0 array causes failure (https://github.com/numpy/numpy/blob/ea965e4cd328fbcf76b03ff749ef06d2aa38c28b/numpy/core/src/multiarray/item_selection.c#L1519)

No error code at the point when it fails, in which case the function assumes that the cause is memory exhaustion (https://github.com/numpy/numpy/blob/ea965e4cd328fbcf76b03ff749ef06d2aa38c28b/numpy/core/src/multiarray/item_selection.c#L1621)

The fix is probably to ensure that `needcopy=false` if `N=0`.

**Comment by mattip** [comment]
Thanks for tracking this down. Is this a regression from previous versions? 

Would you like to make a pull request? Please add a failing test to `numpy/core/tests/test_regression.py` (if it is a regression) or `numpy/core/tests/test_multiarray.py` near the existing lexsort tests, make sure the test fails with `python runtests.py`, then add the fix and make sure the test passes.

**Comment by batterseapower** [comment]
It definitely does work in 1.13.1 and (I think) in 1.16 so this is a regression. I believe it was introduced in https://github.com/numpy/numpy/commit/03052b72ba39e2f1cd1994cec470f6be818f06a6

I will make a PR.
