### ISSUE TITLE
A weird error in polyfit

### ISSUE THREAD

**Issue by Artlist-creator** [numpy/numpy#14242]
### Something weird happened with numpy when i tried to run my code:

```python
import os
os.environ["OPENBLAS_NUM_THREADS"] = "1"
import numpy as np
import pylab
import re
def generate_models(x, y, degs):
    """
    Generate regression models by fitting a polynomial for each degree in degs
    to points (x, y).
    Args:
        x: a list with length N, representing the x-coords of N sample points
        y: a list with length N, representing the y-coords of N sample points
        degs: a list of degrees of the fitting polynomial
    Returns:
        a list of numpy arrays, where each array is a 1-d array of coefficients
        that minimizes the squared error of the fitting polynomial
    """
    return list(map(lambda deg : np.polyfit(x ,y ,deg), degs)) #or pylab
#OR
    return [ np.polyfit(x,y, deg) for deg in degs] #or pylab

```

It gave me

### Error message:
    File "/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/polynomial.py", line 602, in polyfit
    raise TypeError("expected x and y to have same length")

But when i tried :
   `return map(lambda deg : pylab.polyfit(x ,y ,deg), degs)`
which run without any issues

### Numpy/Python version information:

Python 3.7.3 (default, Mar 27 2019, 22:11:17)
IPython 7.7.0 
numpy 1.16.4

**Comment by seberg** [comment]
Sorry, this is a bit hard to believe, can you give example inputs to your function that work one way and not the other? For numpy both calls look exactly the same.

**Comment by Artlist-creator** [comment]
Yeah. Actually when I checked my input did not append as I expected. My fault , thank you for making me realise.

**Comment by NadeemNicoR** [comment]
Can i know what the problem here was ?

**Comment by GIRIJA-KALYANI** [comment]
Is this issue solved?

**Comment by ctmhoang** [comment]
Yes, the problems came from my side. It was not from the package itself. If my memory serves, I think my pass-in processed data did not have the same length as I excepted.

**Comment by GIRIJA-KALYANI** [comment]
That's with mine too, could you please help me solve mine.
I get the same error as attached
![image](https://user-images.githubusercontent.com/7091088/112197644-4fccb000-8c32-11eb-8a77-d9bc5032778b.png)

Here is my code:
from __future__ import division
import numpy
from matplotlib import pyplot
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import pycwt as wavelet
dat = pd.read_csv("K:\Data\PhD\DataAnalysis\Processing\Ross_Monthly.csv")
title = 'Sea Ice Extent'
label = 'Ross Sea'
units = 'sq km'
t0 = 1979.0
dt = 0.25  # In years

#creating time in arrays
N = dat.size #length of the time domain
t = numpy.arange(0, N) * dt + t0

#de-trending and normalsie 
p = numpy.polyfit(t - t0, dat, 1)
--> dat_notrend = dat - numpy.polyval(p, t - t0)
std = dat_notrend.std()  # Standard deviation
var = std ** 2  # Variance
**dat_norm = dat_notrend / std  # Normalized dataset**

dat_norm - is the issue 
it shows: ValueError: Unable to coerce to Series, length must be 1: given 503
dat_notrend = dat - numpy.polyval(p, t - t0)
