### ISSUE TITLE
Possible Memory Leak in np.linalg.inv(), version 1.17.0

### ISSUE THREAD

**Issue by tjysdsg** [numpy/numpy#14251]
I was building an application which requires a large amount of inverse matrix computation, and I came across a memory leaking problem. After fixing my own code, I found that `numpy` is leaking some memory every time I called `np.linalg.inv()`. And after several thousands of calls, my system's memory has been eaten up.

The reason that I thought the problem was `np.linalg.inv()` call was because that results of `tracemalloc`.

#### Reproducing code example without tracemalloc:
```python
import numpy as np
x = np.random.random((30, 30))
for i in range(10000):
    a = np.linalg.inv(x)
```
#### Reproducing code example using tracemalloc and gc:
```python
import numpy as np
import tracemalloc
import gc
tracemalloc.start()
x = np.random.random((30, 30))
snapshot1 = tracemalloc.take_snapshot()
for i in range(10000):
    a = np.linalg.inv(x)
    del a

gc.collect()
snapshot2 = tracemalloc.take_snapshot()
top_stats = snapshot2.compare_to(snapshot1, 'lineno')
for stat in top_stats[:10]:
    print(stat)
```
### Output of tracemalloc:
```
tmp.py:8: size=1112 B (+1112 B), count=1 (+1), average=1112 B
<__array_function__ internals>:6: size=488 B (+488 B), count=1 (+1), average=488 B
/home/tjy/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:547: size=480 B (+480 B), count=1 (+1), average=480 B
/home/tjy/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:117: size=464 B (+464 B), count=1 (+1), average=464 B
/home/tjy/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:546: size=456 B (+456 B), count=1 (+1), average=456 B
/home/tjy/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:544: size=448 B (+448 B), count=1 (+1), average=448 B
/home/tjy/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:545: size=440 B (+440 B), count=1 (+1), average=440 B
/home/tjy/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:152: size=440 B (+440 B), count=1 (+1), average=440 B
/home/tjy/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:550: size=432 B (+432 B), count=1 (+1), average=432 B
/home/tjy/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:150: size=424 B (+424 B), count=1 (+1), average=424 B
```

### Numpy/Python version information:
```
1.17.0 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
```

**Comment by seberg** [comment]
@tjysdsg hmmm, not sure what is going on. I can reproduce the tracemalloc result on 1.17 partially, but the first part does not seem to increase memory footprint over time for me, I assume it does very obviously do so for you? I am wondering how much could be also related to the linear algebra backend (e.g. MKL) or be anaconda specific (patches by anaconda/Intel).

There were some smaller memory leaks fixed in various places recently, you could try with the master branch to see if that helps as well?

**Comment by tjysdsg** [comment]
I just found out that np.linalg.inv() was not the main reason that caused the memory footprint to grow. Sorry for the misinformation. However, I haven't tested the code example using tracemalloc and gc using the latest commit. Maybe somebody can help?

Anyway, my current problem is solved, thanks for the reply @seberg
