### ISSUE TITLE
Faulty random.uniform()

### ISSUE THREAD

**Issue by sursu** [numpy/numpy#14267]
I suspect there is an issue with the numpy random number generator. That or scipy has an issue.
Given some odd results I've obtained I tend to believe that the issue is with numpy.  

### Reproducing code example:

Imports & Preliminaries:
```python
import numpy as np
import scipy.stats as stats
import plotly.graph_objects as go

# Seed
np.random.seed(seed=8675309)

# Sample size
N = 10**5

# To see how results scale with dimension we'll consider
# behavior one thorugh ten dimensions
Ds = np.arange(1,11)
idxs = np.arange(10).repeat(2)
plot_Ds = list(np.arange(0.5,11).repeat(2)[1:-1])
```
Computations:
```python
delta_means, delta_ses = np.zeros(shape=(2, len(Ds)))

for i, D in enumerate(Ds):
      
    # Sample points
    x = np.random.uniform(-3, 3, size=(2,N,D))
    # x = stats.uniform.rvs(-3, 3, size=(2,N,D))
    
    # Compute distance between them
    delta_samples = np.linalg.norm(np.diff(x, axis=0)[0], axis=1)
  
    # Estimate average distance
    delta_means[i], delta_ses[i] = compute_mc_stats(delta_samples)

    # Estimate distance quantiles
    delta_quantiles[i] = np.percentile(delta_samples, quant_probs)

# Upper & Lower bands
y_upper = delta_means[idxs] + 2 * delta_ses[idxs]
y_lower = delta_means[idxs] - 2 * delta_ses[idxs]
```
Plot:
```python
# Plot average distance between points versus dimension
fig = go.Figure()
fig.add_scatter(x=plot_Ds, y=delta_means[idxs])

fig.layout.update(xaxis_title='Dimension', xaxis_range=[plot_Ds[0], plot_Ds[-1]],
                  yaxis_title='Average Distance Between Points', yaxis_range=[0,5],
                  showlegend=False, height=600)
fig.show()
```
![newplot](https://user-images.githubusercontent.com/12001304/62954894-71c44680-bdf0-11e9-826d-bbea1f487273.png)

If we now comment out the sampling with numpy and do it with scipy we get a somewhat different plot:
![newplot (1)](https://user-images.githubusercontent.com/12001304/62954905-75f06400-bdf0-11e9-8d2b-1b48ba4b5b4a.png)

### Numpy/Python version information:

Numpy: 1.17.0
Python: 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]

**Comment by seberg** [comment]
The two commands have a different signature, so you are simply comparing two different distributions.

**Comment by sursu** [comment]
@seberg please be more explicit: what do you mean by "different signature"?

Why do you claim that these are 2 different distributions?

**Comment by rkern** [comment]
The first two arguments for [`np.random.uniform(low, high)`](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.mtrand.RandomState.uniform.html) are `low` and `high`. The first two arguments for [`scipy.stats.uniform.rvs(loc, scale)`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.uniform.html) are `loc` and `scale`. `low=loc`, `high=loc + scale`.
