### ISSUE TITLE
negative  element in some power operations output unexpected nan

### ISSUE THREAD

**Issue by Sarah112358** [numpy/numpy#14273]
When the element of ndarray is negative, it returns nan in some power operations:

```python
import numpy as np
a=np.ones(3)*(-1000)
for i in a:
    print(i**(1/3))
```
output:
nan
nan
nan

while ,
```python
print((-1000)**(1/3))
```
output:
(5+8.660254037844384j)

### Error message:
RuntimeWarning: invalid value encountered in double_scalars

### Numpy/Python version information:
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
numpy 1.14.0

**Comment by eric-wieser** [comment]
Numpy will not automatically promote real numbers to complex - you can be probably use `np.power(a, 1/3, dtype=complex)` to get the result you want.

**Comment by Sarah112358** [comment]
> Numpy will not automatically promote real numbers to complex - you can be probably use `np.power(a, 1/3, dtype=complex)` to get the result you want.

This solved my problem, thanks a lot.
