### ISSUE TITLE
numpy.nonzero can report a zero value as nonzero

### ISSUE THREAD

**Issue by ellades** [numpy/numpy#14271]
### Reproducing code example:

```python
import numpy as np
np.nonzero([[0,0],[1,1]])
```

### Error message:

No error message

### Numpy/Python version information:

1.16.4 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by WarrenWeckesser** [comment]
There is no problem here.  This is what I get:

```
In [17]: a = np.array([[0, 0], [1, 1]])                                         

In [18]: i, j = np.nonzero(a)                                                   
```

`i` hold the first index (i.e. the rows) of the nonzero values.

```
In [19]: i                                                                      
Out[19]: array([1, 1])
```

`j` holds the second index (i.e. the columns) of the nonzero values.

```
In [20]: j                                                                      
Out[20]: array([0, 1])
```

These are the nonzero values:

```
In [21]: a[i, j]                                                                
Out[21]: array([1, 1])
```
