### ISSUE TITLE
DLL load failed: The specified module could not be found. numpy.core from importing geopandas 

### ISSUE THREAD

**Issue by royanc** [numpy/numpy#14288]
Hi

Trying to import geopandas on pycharm 3.7 with anaconda.
after : `import geopandas`

I get this error:
`Traceback (most recent call last):
  File "C:\Users\royanc\.conda\envs\cond\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\royanc\.conda\envs\cond\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\royanc\.conda\envs\cond\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.
`
`During handling of the above exception, another exception occurred:
`   `
Traceback (most recent call last):
  File "C:/Users/royanc/PycharmProjects/last/last.py", line 1, in <module>
    import geopandas
  File "C:\Users\royanc\.conda\envs\cond\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Users\royanc\.conda\envs\cond\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    import numpy as np
  File "C:\Users\royanc\.conda\envs\cond\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\royanc\.conda\envs\cond\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 
`
`IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
` 
 `Importing the numpy c-extensions failed.` 
 `- Try uninstalling and reinstalling numpy.
 `- If you have already done that, then:`
  ` 1. Check that you expected to use Python3.7 from ` `"C:\Users\royanc\.conda\envs\cond\python.exe",`
 `     and that you have no directories in your PATH or PYTHONPATH that can`
  `    interfere with the Python and numpy version "1.17.0" you're trying to use.`
   `2. If (1) looks fine, you can open a new issue at`
    `  https://github.com/numpy/numpy/issues.  Please include details on:`
     ` - how you installed Python`
      `- how you installed numpy`
      `- your operating system`
      `- whether or not you have multiple versions of Python installed`
     ` - if you built from source, your compiler versions and ideally a build log
  
`- If you're working with a numpy git repository, try `git clean -xdf``
`  (removes all files not under version control) and rebuild numpy.`

`Note: this error has many possible causes, so please don't comment on`
`an existing issue about this - open a new one instead.`

`Original error was: DLL load failed: The specified module could not be found.`

after a lot of reading I understood I need all packages have to be downloaded from same channel so i changed in the anaconda navigator the channel to  https://conda.anaconda.org/conda-forge/
and install geopandas again throw this channel, also try with the default one but its not working as well.
this is the conda list:

# packages in environment at C:\Users\royanc\.conda\envs\cond:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.70.0               h6a4c333_2    conda-forge
bzip2                     1.0.8                hfa6e2cd_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cfitsio                   3.470                hfa6e2cd_1    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.65.3               h4496350_0    conda-forge
expat                     2.2.5             habb2df7_1003    conda-forge
fiona                     1.8.6            py37h2979200_4    conda-forge
freetype                  2.10.0               h563cfd7_1    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      2.4.2            py37he6b6c38_4    conda-forge
geopandas                 0.5.1                      py_0    conda-forge
geos                      3.7.2                habb2df7_1    conda-forge
geotiff                   1.5.1                h8f84788_2    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3            hc0c2ac7_1002    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.5          nompi_hcc15c50_1100    conda-forge
icu                       64.2                 he025d50_0    conda-forge
intel-openmp              2019.4                      245
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            hf7dc31f_1005    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
libcurl                   7.65.3               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   2.4.2                h2bdb96c_4    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4ece8bf_1010    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
libnetcdf                 4.6.2             ha953453_1002    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     11.5                 hb0bdaea_0    conda-forge
libspatialindex           1.8.5                he025d50_4    conda-forge
libspatialite             4.3.0a            h832c139_1029    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.0.10            h6512ee2_1003    conda-forge
libxml2                   2.9.9                h9ce36c8_2    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
mkl                       2019.4                      245
msys2-conda-epoch         20160418                      1
munch                     2.3.2                      py_0    conda-forge
numpy                     1.17.0           py37hc71023c_0    conda-forge
openjpeg                  2.3.1                ha922770_0    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pandas                    0.25.0           py37he350917_0    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
pip                       19.2.2                   py37_0    conda-forge
poppler                   0.67.0               h92819f6_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 h06f7779_0    conda-forge
proj4                     6.1.0                hc2d0af5_2    conda-forge
pyproj                    2.2.1            py37h3f740ce_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
rtree                     0.8.3           py37h21ff451_1002    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
shapely                   1.6.4           py37ha35856d_1006    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hfa6e2cd_0    conda-forge
tk                        8.6.9             hfa6e2cd_1002    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wheel                     0.33.4                   py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1005    conda-forge
zstd                      1.4.0                hd8a0e53_0    conda-forge

any ideas solving this will be appreciated
TIA
``

**Comment by mdoubko** [comment]
Dear all,
I am getting pretty much the same error with pandas and numpy.
- I install everything via Anaconda into one environmental variables
- I make sure that PATH and PYTHONPATH does not cause any conflicts and
- run everything from my environmntal variable
I am very much interested in any hints or suggestions for other dependency management software above Conda that may avoid these situations.

thanks
Marcela

**Comment by mdoubko** [comment]
I downgraded to Python 36. Everything works fine.

**Comment by rgommers** [comment]
This was an install issue that has long since been resolved, so I'll close this issue.
