### ISSUE TITLE
azure-pipeline numpy.numpy (Linux_PyPy3) tests failing

### ISSUE THREAD

**Issue by maxwell-aladago** [numpy/numpy#14280]
I believe there are problems with the `azure-pipeline numpy.numpy (Linux_PyPy3)` and `azure-pipeline numpy.numpy` pipelines. I could be wrong but all PRs in the last 18hrs are failing on those threads as seen in [#14278](https://github.com/numpy/numpy/pull/14278), [#14241](https://github.com/numpy/numpy/pull/14241), [#14279](https://github.com/numpy/numpy/pull/14279). @seberg, can you please look at this?

**Comment by mattip** [comment]
The build uses the latest nightly build of PyPy, which was broken. It is now fixed. Thanks for the heads up.
