### ISSUE TITLE
DOC, BUILD: improve documentation around site.cfg

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#14286]
Documentation of `site.cfg` exists in `numpy/distutils/system_info.py` but that is not extracted as a docstring into the sphinx-built documentation.

`site.cfg` is also mentioned in  `./INSTALLATION.rst.txt`, but that file is also not linked into the sphinx-built documentation, the information there should be merged with the other bits and pieces about building from source and installation.

**Comment by rgommers** [comment]
`site.cfg.example` should be self-documenting, what is needed in addition is some high level docs on when/why to use it. That should go mainly into https://www.numpy.org/devdocs/user/building.html and be linked from https://www.numpy.org/devdocs/reference/distutils.html

**Comment by mkoeppe** [comment]
`site.cfg.example` in master seems to be outdated:
{{{
# Defaults
# ========
# The settings given here will apply to all other sections if not overridden.
# This is a good place to add general library and include directories like
# /usr/local/{lib,include}
#
#[ALL]
#library_dirs = /usr/local/lib
#include_dirs = /usr/local/include
}}}
But the installation scripts actually does not seem to respect the ALL section; instead one has to use [DEFAULT], which is handled https://docs.python.org/2/library/configparser.html / https://docs.python.org/3.8/library/configparser.html.

(Related old issues: https://github.com/numpy/numpy/issues/1285 and
https://github.com/numpy/numpy/issues/1349)

**Comment by mattip** [comment]
@mkoeppe see [this comment](https://github.com/numpy/numpy/pull/15338#discussion_r368249819) on the linked PR.
