### ISSUE TITLE
Add back `--durations` flag for python3.6-dbg testing on travisCI 

### ISSUE THREAD

**Issue by charris** [numpy/numpy#14293]
Current pytest versions 5.0.1 and 5.1.0 abort when running on python3.6-dbg and passed that flag, so it is temporarily commented out. It should be uncommented when pytest is fixed and the pytest version pinned. The affected files are `tools/travis-test.sh` and `tools/travis-before-install.sh`

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mattip** [comment]
Pushing this off to 1.19 since the underlying issue is solved with python 3.7, but travis is still running a version of python before the fix.

**Comment by seberg** [comment]
Sounds like we might as well push it of once more, tagged for 1.20.
