### ISSUE TITLE
Can't get post on mailing list

### ISSUE THREAD

**Issue by NGeorgescu** [numpy/numpy#14304]
Hi,

Issue a bit unrelated to the numpy codebase itself.  I'm trying to get my PR on the mailing list and can't, tried multiple email addresses, posting on the nabble boards, and emailing numpy-discussion@scipy.org directly.  I'm definitely subscribed and even getting the mailing list emails to my inbox.

Is there something obvious I'm missing?

Thanks

**Comment by mattip** [comment]
We should really correct that, wherever it appeared. The correct address is numpy-discussion@python.org, as documented [here](https://scipy.org/scipylib/mailing-lists.html), although I notice it still has NumPy-svn for commit-related discussions :(

**Comment by mattip** [comment]
xref scipy/scipy.org#308

**Comment by NGeorgescu** [comment]
At the top of the page [here](http://numpy-discussion.10968.n7.nabble.com/) also, if you click on [more options](http://numpy-discussion.10968.n7.nabble.com/mailing_list/MailingListOptions.jtp?forum=2)

**Comment by mattip** [comment]
I posted on the [nabble forum](http://support.nabble.com/Update-information-on-the-NumPy-mailing-list-archive-td7604127.html) asking how to update that. Thanks for the heads up.

**Comment by mattip** [comment]
Thanks @NGeorgescu, the nabble page has now been corrected.

**Comment by zoj613** [comment]
My post was recently rejected because I had changed my email address using nabble. Is there a way to correct this?
