### ISSUE TITLE
OpenBLAS and AVX512 issues in wheels

### ISSUE THREAD

**Issue by rth** [numpy/numpy#14305]
Latest OpenBLAS releases come with alarming notes about issues with AVX512 support,
```
OpenBLAS 0.3.7 version (Aug 11, 2019)
 - the SKYLAKEX (AVX512) DGEMM helper functions have now been 
   disabled to fix remaining errors in DGEMM, DSYMM and DTRMM

OpenBLAS 0.3.6 version (Apr 29, 2019)
- the AVX512 DGEMM kernel has been disabled again due to unsolved 
  problems
```
I'm not sure if that implies that those were producing incorrect results before. There are certainly a number of issues on the OpenBlas tracker about it.

As far as I understand the openblas version included in numpy wheels on PyPi [is 3.5](https://github.com/numpy/numpy/blob/67940ffec87b75ff72250ae9b2890fac6a134681/tools/openblas_support.py#L18)?  Could this have affected past numpy wheels? If so which versions are affected?

I imagine tests on machines with AVX 512 are not part of the CI.

For instance, there is a report in https://github.com/scikit-learn/scikit-learn/issues/14603 of a calculation (mostly consisting of matrix multiplication) producing wrong results on an machine with AVX512 using pip installed numpy 1.16.2. (It's not yet 100% sure that this is the root cause though).

**Comment by charris** [comment]
1.17 OpenBLAS was compiled from the development branch and should have Skylake support disabled. Same for 1.16.4, but earlier versions use an older OpenBLAS library.

**Comment by charris** [comment]
See the 1.16.4 release note.

**Comment by charris** [comment]
I note that a compiled OpenBLAS 3.7 is now available and uploaded on Aug 12. See https://github.com/MacPython/openblas-libs/pull/5. It looks like it has some performance improvements. Hmm, probably not worth backporting to current releases, but we should use it in testing master. @tylerjereddy Thoughts?

**Comment by rth** [comment]
Thanks for the explanations. Glad that it was fixed!

> See the [1.16.4 release note](https://docs.scipy.org/doc/numpy/release.html#numpy-1-16-4-release-notes).

Indeed, still "The wheels on PyPI are linked with OpenBLAS v0.3.7-dev, which should fix issues on Skylake series cpus." is a fairly mild characterization of the dot product returning incorrect results. Also Intel generation name is not something that people pay too much attention too IMO, indicating that it affects AVX512 might be more explicit.

**Comment by tylerjereddy** [comment]
Yeah, I added a regression guard in OpenBLAS CI upstream using the Intel SDE emulator for SkylakeX--we discussed putting it in NumPy itself but I think in the end more devs preferred upstream for faster feedback at the source, etc.

@charris Yeah, I'll work on bumping it in master, which means a few manual builds on some of the more exotic platforms on gcc compile farm first.
