### ISSUE TITLE
numpy.clip is not documented to be a ufunc

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#14319]
In numpy 1.17 `clip` is now a ufunc. However it does not appear on the listing of ufuncs on https://docs.scipy.org/doc/numpy/reference/ufuncs.html. It should be added. I would do it myself but I'm unsure if there are other places this should be mentioned.

**Comment by seberg** [comment]
I am not sure it should be, since it is unfortunately still a thin wrapper around ufunc(s), and also still goes via the `arr.clip` method.

**Comment by ngoldbaum** [comment]
OK, in that case is there a developer facing exhaustive list of ufuncs somewhere? I was using the page I linked to while working on unyt and my notification about the existence of the new ufunc was via a bug report from a user.

**Comment by seberg** [comment]
Hmmm, you are right, the list should probably include the `np.core.umath.clip` (combined minimum+maximum) ternary implementation. But since the implementation is so hidden, I am not sure we want it to show up on that page? OTOH, it is very important for `__array_ufunc__` implemeneters...

**Comment by ngoldbaum** [comment]
`ones_like` as well

**Comment by rgommers** [comment]
> Hmmm, you are right, the list should probably include the `np.core.umath.clip` (combined minimum+maximum) ternary implementation. But since the implementation is so hidden, I am not sure we want it to show up on that page? OTOH, it is very important for `__array_ufunc__` implemeneters...

-1 on that, `core.umath` is not public.

> OK, in that case is there a developer facing exhaustive list of ufuncs somewhere?

I don't think there is, but this could be auto-generated fairly easily I'd think. Piggybacking on `numpy/tests/test_public_api.py` to scan through all public objects and check if they're ufuncs could be a way to do it.

**Comment by ngoldbaum** [comment]
`np.clip` isn't visible on the ufuncs docs, but it is present in the set returned by `numpy.testing.overrides.get_overridable_numpy_ufuncs`, so I'm going to close this as authors of types that implement `__array_ufunc__` have a public API to check for all supported numpy ufuncs now.
