### ISSUE TITLE
regarding zero dimension array

### ISSUE THREAD

**Issue by vainaijr** [numpy/numpy#14312]
### Reproducing code example:

```python
import numpy as np
x_np = np.random.rand(4,1,0)
y_np = np.random.rand(4,1,1)
x_np + y_np
```

### Error message:

this gives 
array([], shape=(4, 1, 0), dtype=float64)

why does adding an empty array to some array, return an empty array, shouldn't it have returned y_np?

**Comment by seberg** [comment]
It is a (slightly confusing) corner case of broadcasting rules. If the shape mismatches you have an error, unless one of the arrays has a shape of exactly 1 in that dimension. If the shape is exactly 1, it is repeated as many times as necessary. "As many times as necessary" can very much be zero times.
