### ISSUE TITLE
Feature Request: Linear step function (similar to numpy.heaviside)

### ISSUE THREAD

**Issue by kolibril13** [numpy/numpy#14314]
Often I use this function:
![image](https://user-images.githubusercontent.com/44469195/63411541-07199900-c3f6-11e9-9fec-f1365c9265b9.png)
which is defined as:
![func](https://user-images.githubusercontent.com/44469195/63411609-2ca6a280-c3f6-11e9-9071-9ecf4976f234.png)
So very similar to the [numpy heaviside function](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.heaviside.html), but with an linear interval between 0 and 1.
Therefore I wrote the function "linear_step_func".
Is there an interest of making it a numpy function?
```python
import numpy as np
import matplotlib.pyplot as plt

x= np.linspace(0., 10., 100)
def linear_step_func(x,x0,x1):
    y= np.piecewise(x, [
        x < x0, 
       (x >= x0) & (x <= x1), 
        x > x1],
            [0.,
            lambda x: x/(x1-x0)+x0/(x0-x1), 
             1.]
       )
    return y
plt.plot(x, linear_step_func(x,2, 5))
plt.show()
```

**Comment by rgommers** [comment]
Thanks for asking @kolibril13. I think that doesn't meet our bar for inclusion in NumPy itself (which is high these days). It's fairly easy to do yourself if you need this, as your code shows. There's many such utility functions we could include, but it would fill up the numpy namespace with things most users may never need.

**Comment by kolibril13** [comment]
ok, thanks!

**Comment by eric-wieser** [comment]
I'm starting to wonder whether heaviside met the bar for inclusion, not that that matters now.

**Comment by rgommers** [comment]
It wouldn't today for sure I think. The bar was _a lot_ lower 10-15 years ago.

**Comment by eric-wieser** [comment]
Well, that was only two years ago (gh-8795)

**Comment by rgommers** [comment]
> Well, that was only two years ago (gh-8795)

hmm I totally missed that. I think that was a mistake.

**Comment by Mastercol01** [comment]
> 
> 
> I'm starting to wonder whether heaviside met the bar for inclusion, not that that matters now.

Well, I cannot talk for any other developers, but, as STEM student, I can tell you it has proven useful quite sometimes.
