### ISSUE TITLE
Arithmetic operations on 0-dimensional arrays return different objects for relatively small and large values.

### ISSUE THREAD

**Issue by maxwell-aladago** [numpy/numpy#14327]
### Reproducing code example:

```python
import numpy as np
x = np.array(43) - np.array(18)
y = np.array(473963742225900817127911193656584771) - np.array(18535119325151578301457182298393896)
z = np.array(473963742225900817127911193656584771) + np.array(18535119325151578301457182298393896)

print("type x = ", type(x))
print("type y = ", type(y))
print("type z = ", type(z))
```
 produces the results

```
type x = <class 'numpy.int64'>
type y =  <class 'int'>
type  z =  <class 'int'>
```

### Error message:
There is no error message. It's probably a bug or a desired behaviour. Any explanations for this behaviour will be greatly appreciated. 

### Numpy/Python version information:

```
1.18.0.dev0+2958ede 3.6.7rc2 (v3.6.7rc2:4893861ab5, Oct 13 2018, 05:25:29) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```

**Comment by maxwell-aladago** [comment]
Additional note: this isn't the case for floats for the numbers tested above. For example, 

```
import numpy as np
y = np.array(473963742225900817127911193656584771.0) - np.array(18535119325151578301457182298393896.0)

print("type y = ", type(y))
type y =  <class 'numpy.float64'>

```

**Comment by mattip** [comment]
`type(y)` is the wrong question, the question is "what is the `dtype`". `y.dtype` in the original example results in `object`. 

The values in `y` and `z` cannot be represented exactly by any of the available int or float types, so the python object is retained in the ndarray. Best practices would be to reason about the dtype you expect to use, and explicitly use it when creating an ndarray.

**Comment by maxwell-aladago** [comment]
Thank you for the clear explanation @mattip. 

`y.dtype` does return a `float64` though as indicated in the additional note. 

Thank you

**Comment by mattip** [comment]
473963742225900817127911193656584771.0 is not what you think it is after you run it through the python interpreter - it is rounded to the nearest float64 value. So when numpy tries to decide how to store it, `float64` is the correct dtype.

This will result in `0.0` even though they differ by 1.0
```
`473963742225900817127911193656584771.0 - 473963742225900817127911193656584770.0`
```
