### ISSUE TITLE
feature request: get most frequent number in an np array. 

### ISSUE THREAD

**Issue by danFromTelAviv** [numpy/numpy#14329]
On a number of occasions, I would have found it very convenient to have something like: np.most_frequent(np_array, axis=1)
This would return the most frequent number. You can do that with hitograms as a workaround but I think it would be very nice as a feature in numpy.

**Comment by WarrenWeckesser** [comment]
Do you mean you want the [mode](https://en.wikipedia.org/wiki/Mode_(statistics))?  Take a look at [scipy.stats.mode](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html).

**Comment by danFromTelAviv** [comment]
embarrassing. 
Yeah - that's exactly what I needed. Thanks!

**Comment by seberg** [comment]
`np.unique` has a similar option as well.
