### ISSUE TITLE
numpy.sum does not fail when sum indices exceed array bounds

### ISSUE THREAD

**Issue by kjfergu** [numpy/numpy#14324]
numpy.sum will not fail/error if the indices of the sum exceeds the bounds of the array. It doesn't appear to do anything particularly bad (Looks like it just keeps adding 0), but I'd say it's unexpected behavior.

### Reproducing code example:

```python
import numpy as np
x = np.random.random(10)
x[10] # Should produce an error and does
np.sum(x[0:9]) # Okay
np.sum(x[0:10]) # Shouldn't work, but does
np.sum(x[0:100]) # Also works, same result as previous line
np.sum(x[20:100]) # Also works, result is 0
```

Edit:

I also just confirmed that none of the indices have to be within the array bounds. np.sum just returns 0 in those cases. I edited my example to show this.

**Comment by kjfergu** [comment]
Since I forgot to add this in my previous post:

```
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print(np.__version__)
1.16.4
```

**Comment by eric-wieser** [comment]
Not a bug, this matches how regular python behaves:
```python
a = [1, 2, 3]
a[1:]  # [2, 3]
a[1:3]  # [2, 3]
a[1:30000]  # [2, 3]
a[10:]  # []
a[10:100000]  # []
```
