### ISSUE TITLE
Shippable checks failing

### ISSUE THREAD

**Issue by maxwell-aladago** [numpy/numpy#14336]
The `shippable` checks for PRs seems to be failing.

 The error message is 
```
sudo docker run -d --privileged --name shippable-dind docker:17.09.1-dind 0s  
docker: Error response from daemon: Conflict. The container name "/shippable-dind" is already in use by container "8d42ce9836972a4991a7abe7dbc2425b909985818952c257d933003ec2958e75". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

see [#14335] for details.

**Comment by seberg** [comment]
Yeah, they seem flaky currently, open/reopen seems to sometimes fix it, but if it persists we may have to look into it.

**Comment by maxwell-aladago** [comment]
Closing and reopening worked. Thank you

**Comment by seberg** [comment]
Honestly, I do not know shippable well, but the errors seem to while spinning up the docker image, and I am not sure we have direct control over that at all.

**Comment by tylerjereddy** [comment]
We saw this shortly before SciPy conference too, I think. I tried emailing them about it but never heard back.

**Comment by tylerjereddy** [comment]
We could also look into `drone.io`, which OpenBLAS is now using in their CI upstream for flavors of ARM ([example build](https://cloud.drone.io/xianyi/OpenBLAS/64)). I think @isuruf drafted in the testing code for that upstream. It looks like they support directed acyclic graphs for complex pipelines too, if we wanted to save some resources with initial "sniff tests," etc.

**Comment by mattip** [comment]
xref Shippable/support#4882 from July, I added a note there about the current failures

**Comment by seberg** [comment]
Lets close this, I am not sure I have seen shippable tests failing recently, and there is nothing specific to do for us.
