### ISSUE TITLE
viewing an array with a fieldless structured dtype does not update the dtype:

### ISSUE THREAD

**Issue by ahaldane** [numpy/numpy#14344]
As discovered in #14310 , viewing an array with a fieldless structured dtype does not update the dtype/itemsize:

```python
>>> a = np.zeros(2, dtype={'names':[], 'formats':[], 'offsets':[], 'itemsize':8})
>>> b = a.view(np.dtype([]))
>>> b
array([], shape=(2, 0),
      dtype={'names':[], 'formats':[], 'offsets':[], 'itemsize':8})
>>> b.dtype == np.dtype([])
False
```

**Comment by eric-wieser** [comment]
In my opinion, the expected behavior here is to throw an exception, since the new array would need to be 8/0 times longer.

**Comment by ahaldane** [comment]
Yeah, I was just thinking about that too.

Alternatively, we could add a special case for size-0 arrays, which can always be viewed as any dtype. But I'm not sure I like special cases.
