### ISSUE TITLE
PytestTester is not available via np.testing despite docstring claiming so

### ISSUE THREAD

**Issue by qwhelan** [numpy/numpy#14354]
I'm working on replacing `nose` with `pytest` in a downstream dependency that currently exposes a `numpy.test()`-style interface. I was trying to decide if I should deprecate that or switch to `PytestTester` and the `numpy` docs are a bit unclear.

The `PytestTester` docstring states (https://github.com/numpy/numpy/blob/master/numpy/_pytesttester.py#L51):
```
    This class is made available in ``numpy.testing``, and a test function
    is typically added to a package's __init__.py like so::
```
However, it is explicitly not exported within `numpy/testing/__init__.py`: https://github.com/numpy/numpy/blob/master/numpy/testing/__init__.py#L22

Is `PytestTester` part of the public API?

Docstring suggests so, but only being available via `numpy._pytesttester` suggests that it is private.

Worth mentioning that `scipy.test()` used to leverage `numpy.testing.Tester()`. Now, it uses its own implementation (`scipy._libs._testutils.PytestTester`)

**Comment by charris** [comment]
> Is PytestTester part of the public API?

Good question. Strictly speaking, no, it has some numpy specific warning suppression. Your best bet is probably to copy it and make any needed changes. In the long term, there has been some discussion about making `runtests.py` generally available in a separate project, and `_pytesttester.py` would seem to go along with that. I note that NumPy PytestTester was copied from Scipy and modified, so you wouldn't be doing anything new. Unlike with nose, folks are expected to roll their own pytest testing instead of relying on NumPy, but that doesn't mean you can't borrow what you need :)

**Comment by charris** [comment]
Two other files that may be useful are `pytest.ini` in the root numpy directory and `numpy/conftest.py`. The other change we made switching to pytest was adding an `__init__.py` file to each test directory.

**Comment by charris** [comment]
The misleading documentation is because `pytesttester.py` was moved to a more directly accessible location and the documentation was not updated.

**Comment by charris** [comment]
Note also that there is no `runtestsuite` functionality in pytest, so using `runtests.py` helps with that.

**Comment by qwhelan** [comment]
@charris Thanks, I'll submit a PR to update the docs and probably copy for now. The rest of the test suite tooling isn't currently being used by `bottleneck` - it's just potentially convenient to ask a user to run `.test()` against the actually installed module.

**Comment by charris** [comment]
Note that `slow` is registered as a marker in `conftest.py`. I don't know how you folks have things setup, but recent pytest will complain that marker isn't registered.

**Comment by charris** [comment]
And, one more thing :) We replaced all of the nose based test decorators defined by NumPy with pytest versions.

**Comment by mattip** [comment]
It seems the doc change in #14355 should have been enough to close this. Please reopen with more comments if I am mistaken
