### ISSUE TITLE
Numpy docs are down: bad SSL cert

### ISSUE THREAD

**Issue by drammock** [numpy/numpy#14361]
Numpy doc website is down (and thus every CI that pulls in numpy's objects.inv file is failing).

### Reproducing code example:

navigate to https://www.numpy.org/

### Error message:

Error 526 Ray ID: 50c0ff380f962a53 • 2019-08-25 22:28:04 UTC
Invalid SSL certificate

**Comment by rgommers** [comment]
Just opened the same issue as https://github.com/numpy/numpy.org/issues/34

Looking at it. Cc @stefanv who set up CloudFlare.

**Comment by rgommers** [comment]
It's back up (with a workaround). Closing this, the numpy.org issue is the one to keep open. Thanks for reporting @drammock
