### ISSUE TITLE
windows 64 bit import tensorflow error

### ISSUE THREAD

**Issue by f756692193** [numpy/numpy#14362]
My python version is 3.6.7，I have installed tensorflow 1.14(numpy version is 1.17) successed。but when I import tensorflow, it appear error：ImportError: DLL load failed: 找不到指定的模块
The detail error as fllows：

F:\ChromeDownload>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "F:\Soft\Python\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Soft\Python\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "F:\Soft\Python\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "F:\Soft\Python\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "F:\Soft\Python\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "F:\Soft\Python\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: 找不到指定的模块。

**Comment by mattip** [comment]
(Google translates that error message to "The specified module could not be found")
Where did you get your python/numpy? The following questions assume you got numpy from `pip install numpy` from the PyPI:

Do you have a file `F:\Soft\Python\lib\site-packages\numpy\core\_multiarray_umath*.pyd`? What is its exact name?

Do you have a file `numpy/_distributor_init.py` ? It should be preloading the DLL files in `numpy/.libs/*.dll`, and there should be a DLL file there. Is there?

**Comment by seberg** [comment]
A broken numpy install without followup in a few weeks. I will close this for now. @f756692193  we will need some followup if you want to have help with this, otherwise it is hard to say why the installation is broken. We can reopen/keep discussing.
