### ISSUE TITLE
PyCapsule_Import could not import module "datetime"

### ISSUE THREAD

**Issue by nikoembd** [numpy/numpy#14377]
Hello, everybody,

I originally try to use asammdf to export signal values from a mdf file.
I installed python 3.7.4 and asammdf-5.10.3. After I get the error I installed also datetime package via pip.
My code which leads to this error is in "mdfileparse.py":
```python
from asammdf import MDF, Signal
import numpy as np

mdf3 = MDF('mdf1066.MDF')
sig = mdf3.get('DEV_OBC_AI_CHAdeMO_permission')
sig.plot()
```

### Error message:
![image](https://user-images.githubusercontent.com/7009167/63772616-20cd4b80-c8e2-11e9-81e9-9019df239916.png)

### Numpy/Python version information:

numpy 1.17.0
python 3.7.4
Windows 10

I had also a python 3.6 in advance installed, which I removed afterwards.
Now what can be the problem?

**Comment by mattip** [comment]
what happens if you put this at the top of your file, does it succeed? What does it print?
```
import datetime
print(datetime)
```

**Comment by nikoembd** [comment]
seems I don't have the problem anymore. 
Hard to say how this is fixed, but after datetime installation I made a restart and ran the script line by line in the IDLE PyShell. Installing afterwards matplotlib allowed me to see everything correct.

**Comment by mattip** [comment]
Closing. Not sure what you mean by "datetime installation", it is an integral part of the python stdlib, but glad to see it all worked out.
