### ISSUE TITLE
It seemed that NumPy spend a lot of time on loading packages

### ISSUE THREAD

**Issue by ringsaturn** [numpy/numpy#14374]
### Reproducing code example:

Write a `demo.py`:

```python
from __future__ import print_function

import time

import numpy as np
import six

if six.PY3:
    timer_func = time.process_time
else:
    timer_func = time.clock

n = 1000

start = timer_func()
precise = 2
for i in range(n):
    np.round(np.array(range(i)), precise)
end = timer_func()
print(end-start)

```

Then run it like this:

```shell
# Py2
python -m cProfile -o demo-py2.prof demo.py

# Py3
python -m cProfile -o demo-py3.prof demo.py
```

And view the profiles with snakeviz `pip install snakeviz`:

```shell
# Under Python2's virtual env:
snakeviz demo-py2.prof

# Under Python3's virtual env:
snakeviz demo-py2.prof
```

Get web page:

![NumPy-Python2](https://user-images.githubusercontent.com/13536789/63755276-e7e4a500-c8e8-11e9-9ca0-0411d3e986d1.png)

![NumPy-Python3](https://user-images.githubusercontent.com/13536789/63755281-ea46ff00-c8e8-11e9-9481-5a3575e39be7.png)

And the purple part it time cost on loading packages.

### Numpy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.16.4 2.7.16 (default, Apr 12 2019, 15:32:40)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]
```

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.16.4 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)]
```

**Comment by mattip** [comment]
Duplicate of gh-11457. PR gh-14083 and others are trying to reduce import time. You are testing an old version of NumPy, please retest against HEAD (on python3 only) as we do not intend to backporting these changes to the LTS 1.16 branch.

**Comment by ringsaturn** [comment]
I'm wondering since which version the long import time bug is introduced. So I can use an elder version before this problem is solved.

**Comment by ringsaturn** [comment]
Can you estimate when the problem will be solved?

**Comment by jbrockmendel** [comment]
It looks like np.testing has already been made lazy in master (for py37+).  #14083 discusses potential other optimizations, but there is relatively little remaining low-hanging fruit.  Removing a `platform` import in `core._internal` shaves about 5% off of import time; it isn't obvious to me that this is worth the effort at this poinit.

**Comment by ringsaturn** [comment]
Thanks for explaining. And looking forward to next release!
