### ISSUE TITLE
DLL load error on fresh numpy from conda-forge

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#14380]
Just tried to install `numpy` build with `openblas` in a fresh `conda` environment:
```
conda install conda-forge::numpy "blas=*=openblas"
```

Then upon importing I get a long message with this part at the end:
```
ImportError                               Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\envs\py3f\lib\site-packages\numpy\core\__init__.py in <module>
     16 try:
---> 17     from . import multiarray
     18 except ImportError as exc:

~\AppData\Local\Continuum\anaconda3\envs\py3f\lib\site-packages\numpy\core\multiarray.py in <module>
     13 
---> 14 from . import overrides
     15 from . import _multiarray_umath

~\AppData\Local\Continuum\anaconda3\envs\py3f\lib\site-packages\numpy\core\overrides.py in <module>
      6 
----> 7 from numpy.core._multiarray_umath import (
      8     add_docstring, implement_array_function, _get_implementing_args)

ImportError: DLL load failed: The specified module could not be found.
```

Platform:
* Conda 4.7.11
* Python 3.7.4
* Numpy 1.17.1
* OpenBLAS 0.3.7
* Windows 10

I had experienced a similar error in Linux too when `pip` tries to install another `numpy` version as a dependency of another package, ignoring the `conda` install that's already present (issue there is only with the openblas version), but this time it happens on a fresh install with `conda`-only files, in windows.

If I go into the folder I can see that it has all the required `.pyd` files, and they are for the right python version (3.7). Trying to import `_multiarray_umath` directly into a python session throws the following too:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

The MKL version does not seem to be affected.

**Comment by david-cortes** [comment]
> This sounds like a conda problem, you should report it there.

But this is from the `numpy` channel in `conda-forge`, which is not mantained by `conda`.

**Comment by matthew-brett** [comment]
I don't think the conda-forge numpy is maintained by us either - maybe try over at https://github.com/conda-forge/numpy-feedstock/issues ?
