### ISSUE TITLE
bug in documentation example code for subclassing ndarray

### ISSUE THREAD

**Issue by jonpovey** [numpy/numpy#14386]
There seems to be a minor bug in the example code for subclassing ndarray [in this section of the online documentation](https://docs.scipy.org/doc/numpy/user/basics.subclassing.html#a-brief-python-primer-on-new-and-init)

The example for class C includes a call to `object.__new__()` with more than one argument:

```python
class C(object):
    def __new__(cls, *args):
        print('Cls in __new__:', cls)
        print('Args in __new__:', args)
        return object.__new__(cls, *args)
```

Calling this results in an error:

```
  File "/home/jon/python/ndarray_testing.py", line 31, in __new__
    return object.__new__(cls, *args)

TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

If the extra argument to `object.__new__()` is removed, the example works as expected.

### Fixed example:

```python
class C(object):
    def __new__(cls, *args):
        print('Cls in __new__:', cls)
        print('Args in __new__:', args)
        return object.__new__(cls)

    def __init__(self, *args):
        print('type(self) in __init__:', type(self))
        print('Args in __init__:', args)
```

### Output of fixed example
```
In [129]: C('foo')
Cls in __new__: <class '__main__.C'>
Args in __new__: ('foo',)
type(self) in __init__: <class '__main__.C'>
Args in __init__: ('foo',)
Out[129]: <__main__.C at 0x7f27fb972710>
```

### Numpy/Python version information:

1.16.2 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

**Comment by rgommers** [comment]
thanks for the report @jonpovey. fix taken over in gh-14395
