### ISSUE TITLE
doc: NumPy 1.16 doc links dead

### ISSUE THREAD

**Issue by mgorny** [numpy/numpy#14388]
The links for documentation for 1.16 on https://numpy.org/doc/ are dead: all of '[HTML+zip] [Reference Guide PDF] [User Guide PDF]' go to non-existing files (404).

**Comment by mattip** [comment]
thanks, should be fixed now, be sure to refresh the page. Note the current documentation is for 1.16.4, the documentation for the newly release 1.16.5 is not up yet

**Comment by mattip** [comment]
Please reopen or open a new issue if there are other broken links, that part of numpy.org is quite new.

**Comment by mgorny** [comment]
Is it intentional that the documentation files do not have a version suffix like for the other branches? Does this mean they'll get silently replaced with a new version breaking checksums for everything relying on them?

**Comment by mattip** [comment]
good point. We don't currently supply checksums

**Comment by mgorny** [comment]
But downstreams do use checksums to verify that files did not change since the package maintainer verified them. This means once the files are replaced, packages no longer build.

**Comment by mgorny** [comment]
For all packaging systems that build from source, e.g. Gentoo, *BSD ports, pkgsrc.
