### ISSUE TITLE
Converting char to bool fails when it encounters false

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#14406]
If I initialize a numpy array of C `char` and try to convert it to numpy booleans, it throws an error whenever it encounters a zero (`false`).

```python
import numpy as np, ctypes
np.zeros(5, dtype = ctypes.c_char).astype("bool")
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-284bcf3dfeb8> in <module>
      1 import numpy as np, ctypes
----> 2 np.zeros(5, dtype = ctypes.c_char).astype("bool")

ValueError: invalid literal for int() with base 10: ''
```

**Comment by seberg** [comment]
Hmmm, this is a bit strange. Probably some very old behaviour. You are right, empty strings should be interpreted as False, the problem will be that changing may be tricky with backwards compatibility

In any case, I will close this for discussion to conginue in gh-9875 which is much more comprehensive.
