### ISSUE TITLE
ModuleNotFound-ImportError

### ISSUE THREAD

**Issue by Onroy** [numpy/numpy#14405]
Hello. I installed Tensorflow and was trying out this experimental practice code for DL. I have been getting the ModuleNotFoundError and ImportError every time I try to run the notebook. I thought it was initially a conflict between my VSCode Python and Anaconda Distribution Python and completely uninstalled both and reinstalled Anaconda and its dependancies but I am getting the same error. Please help.

###########################Reproducing code
#Import modules
import tensorflow as tf
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mp
#import mglearn

#Initialize variables
#Recall that tensors are vectors i.e. Multi-D arrays
x=tf.constant([0,1,5,9,5])
y=tf.constant([6,7,0,9,3])

#Multiply the two vectors
z=tf.multiply(x,y)

#To display results, you have to initialize the session
sess=tf.Session()

#Print result
print(sess.run(z))

#close session
sess.close()

#Another means to initialize and close session automatically
with tf.Session as sess:
    out=sess.run(z)
    print(out)
    

###########################Exceptions
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core._multiarray_umath failed to import

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.umath failed to import

**Comment by Onroy** [comment]
I have managed to fix my problem.
Anybody experiencing a similar issue, update numpy to the latest version or at least v.1.16.0 using pip install --user numpy --upgrade --ignore-installed. You can do the same for scipy and tensorflow.

After installation, if there exist path descrepancies, copy items in the new path (something like C:\Users\Nyang'\AppData\Roaming\Python\Python37\Scripts ) and paste them in the Anaconda path (C:\ProgramData\Anaconda3\Scripts). Rerun your Notebooks. Should be working perfectly. Any other errors, check you system environment variables.

**Comment by mattip** [comment]
What version of anaconda are you using? What happens if you try only importing numpy, What happens if you run `import numpy` directly in the Anaconda Prompt (Start Menu -> Ananconda3 64 bit -> Anaconda Prompt -> should open up a black DOS command line -> python<Return> -> `import numpy`

If importing numpy gives an error, please copy paste the text of the error, not an image, and use the "<>" in the toolbar here to format it as code

**Comment by mattip** [comment]
Thanks for the update. Closing
