### ISSUE TITLE
Regression: lexsort gives wrong results on short integer types

### ISSUE THREAD

**Issue by batterseapower** [numpy/numpy#14413]
Changing the dtype of a lexsort argument like this should not change the result, but it does with numpy 1.17.0 and 1.17.1:

```python
np.lexsort((np.array([0, 1, 2, 0]), np.array([0, 0, 0, 1], dtype='int8'))) # [0, 3, 1, 2]
np.lexsort((np.array([0, 1, 2, 0]), np.array([0, 0, 0, 1], dtype='int32'))) # [0, 1, 2, 3]
```

The problem does not affect 1.16.4 so this is a regression.

```
1.17.1
3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
```

(Can also reproduce on `3.7.1 (default, Dec 14 2018, 19:28:38) \n[GCC 7.3.0]` so it's not a Windows thing)

**Comment by eric-wieser** [comment]
What was the 1.16 output?

**Comment by batterseapower** [comment]
The correct result is `[0, 1, 2, 3]`, which is what 1.16.4 outputs in both cases.

**Comment by batterseapower** [comment]
I didn't spot anything obvious at https://github.com/numpy/numpy/blame/4246ce2a391314acc1da90d56ff4f995d45e18a9/numpy/core/src/multiarray/item_selection.c#L1389 which could be the culprit, maybe the problem is in timsort itself? But I can't reproduce using argsort.

**Comment by eric-wieser** [comment]
I think this might be radix sort being off, which is selected based on the type. @hameerabbasi, does that sound plausible?

**Comment by hameerabbasi** [comment]
Radix sort is selected based on type indeed, with it being used for `int8` and `int16` IIRC. However, Radix sort is a layer under lexsort... So lexsort is somehow sorting with the arrays having reversed priorities.

**Comment by charris** [comment]
If I change the sort to `timsort`, int8 works fine, so radixsort is doing something wrong, probably not using the correct indirect keys for argsort.

**Comment by charris** [comment]
Looks like `PyArray_ArgSort` also needs a fix to call radix sort.

**Comment by batterseapower** [comment]
Aha - I see, so the error is somewhere around https://github.com/numpy/numpy/blob/a9143a4c78c0819f9f56f8239bfc118f1fc0a6c6/numpy/core/src/npysort/radixsort.c.src#L140? Not immediately obvious to me where, but the algorithm is pretty hairy!

**Comment by eric-wieser** [comment]
It seems that `aradixsort0_@suff@` only works correctly when passed a `tosort` that is `[0, 1, 2, 3]`.

Unfortunately the only code that exercises passing anything but that argument is `lexsort`

**Comment by eric-wieser** [comment]
I think this is the incorrect line

https://github.com/numpy/numpy/blob/e3f4c536a0014789dbd0321926b4f62c39d73719/numpy/core/src/npysort/radixsort.c.src#L175

**Comment by hameerabbasi** [comment]
I'll take a look shortly, I think this should be an easy fix, but still need to be sure.

**Comment by eric-wieser** [comment]
Something seems fishy with this loop:
https://github.com/numpy/numpy/blob/e3f4c536a0014789dbd0321926b4f62c39d73719/numpy/core/src/npysort/radixsort.c.src#L174-L178
Because since the iterations are independent, and assuming to_sort contains unique integers in 1..N, it must be equivalent to this one, which doesn't use tosort at all!
```C
        for (i = 0; i < num; i++) {
            @type@ k = KEY_OF(arr[i]);
            npy_intp dst = cnt[cols[l]][nth_byte_@suff@(k, cols[l])]++;
            aux[dst] = i;
        }
```

**Comment by eric-wieser** [comment]
I suspect the API makes no guarantees about the values of `tosort`, and therefore using its elements as an index as `arr[tosort[i]]` does is invalid anyway.

**Comment by eric-wieser** [comment]
Here's a case that fails without lexsort:
```
In [6]: np.array([0x1010, 0x0010, 0x1000], np.uint16)[::-1].argsort(kind='stable')
Out[6]: array([2, 0, 1], dtype=int64)

In [7]: np.array([0x1010, 0x0010, 0x1000], np.uint64)[::-1].argsort(kind='stable')
Out[7]: array([1, 2, 0], dtype=int64)
```

**Comment by hameerabbasi** [comment]
That's unrelated to radix sort, it's timsort there, Radix sort is only used for `int8` and `int16`.
