### ISSUE TITLE
Spyder cannot find module 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by felixems** [numpy/numpy#14419]
When I attempt to run any piece of code which requires numpy in Spyder, it fails with the following error:

```
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\felix.swadel\AppData\Local\Continuum\anaconda3\pythonw.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

How I Installed Python and Numpy:

When this problem arose I had both python 3.6 and 3.7 installed. I removed both from my PATH variable, and uninstalled both, before uninstalling Anaconda completely. I then reinstalled Anaconda though the graphical installer for Windows 64-bit.
My OS is Windows 10 Pro.

Any help would be greatly appreciated!

**Comment by seberg** [comment]
Can you check PYTHONPATH (or `import sys; sys.path`). You are in a clean install of anaconda otherwise? I think we will need a bit more information to help out what is wrong with the installation.

**Comment by search2tq** [comment]
i am seeing similar issue, in my case the numpy library is zipped and passed as param for spark / oozie job. i am using python3 and numpy-1.17.2 version.

**Comment by mattip** [comment]
Closing. The original reporter did not update the issue with more information as requested. 

@search2tq your issue is not the same, please open a new issue if still relevant and specify the operating system/python version on the host, and on the spark / oozie remote machine. In general that tactic will not work since there will be incompatibilities between the two system.
