### ISSUE TITLE
numpy.loadtxt "skipcols" - New parameter needed

### ISSUE THREAD

**Issue by szg0000** [numpy/numpy#14427]
New parameter needed, to add the columns which need to be skipped.
e.g:
columns = (1,2,3)  - to skip columns 2,3,4

**Comment by kalvdans** [comment]
I think it is redundant since we already have `usecols` which does the same thing.

usecols=(0,4) - to skip columns 2,3,4

**Comment by szg0000** [comment]
Sometimes you don't know how many columns you have.

**Comment by eric-wieser** [comment]
Duplicate of #13878
