### ISSUE TITLE
np.sum does not propagate nan when the input is a pandas series

### ISSUE THREAD

**Issue by nikhgarg** [numpy/numpy#14424]
np.sum does not propagate nan when the input is a pandas series.

### Reproducing code example:

```python
import numpy as np
import pandas as pd

ar = [0, np.nan]
arseries = pd.Series(ar)
print(np.sum(ar))
print(np.sum(arseries))
```
Output:
```python
nan
0.0
```

### Numpy/Python version information:

1.14.2 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]

**Comment by ewmoore** [comment]
Since a pandas series has a sum method, np.sum calls that instead of doing the sum itself.  Since it defaults to skipna=True, you get 0.0 instead of nan.

**Comment by nikhgarg** [comment]
Does this defaulting happen for all array_like's that have their own sum function, and is this documented anywhere?

**Comment by seberg** [comment]
Yes, it happens for all array likes. Most of the numpy functions which correspond to methods on the array object, will attempt to call the corresponding method on the object. I doubt this is mentioned very specficially, [NEP 22](https://numpy.org/neps/nep-0022-ndarray-duck-typing-overview.html) mentions this specific case briefly.

Note that these functions can also be overriden now using `__array_function__`, which should allow pandas to be better about inheriting numpy behaviour if they wish so.
