### ISSUE TITLE
DOC: Add canonical link to latest release docs

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#14443]
The documentation doesn't have 

```
<link rel="canonical" href="LOCATION" />
```
pointing to the latest release docs.  This would help google a lot in always referring to the latest release docs when searching for things like `numpy sort`.  I currently get 1.9 as the top hit, and for many other searches I get 1.13.

For example, `numpy.sort` should have

```
<link rel="canonical" href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html">
```
which would over time get google to prefer the latest release docs. This would be in the docs for all versions so that Google would do the right thing, and no depend on external links to various versions to determine which is authoritative. 

Requires modifying the template, which I *think* might be being improved in GSOD.

**Comment by rgommers** [comment]
great idea, thanks @bashtage. 

> Requires modifying the template, which I _think_ might be being improved in GSOD.

indeed:) Cc @Shekharrajak

**Comment by rgommers** [comment]
This is done: https://numpy.org/doc/stable/

**Comment by bashtage** [comment]
I can't see a change that would make those canonical.  I'm no web expert but I don't see rel="canonical" in the page
