### ISSUE TITLE
numpy 1.16.5: numpy/core/tests/test_indexing.py::TestIndexing::test_boolean_shape_mismatch Segmentation fault

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#14449]
Hello,
while preparing numpy 1.16.5 package for Debian, the build process failed when running tests with this error:

```
NumPy version 1.16.5
NumPy relaxed strides checking option: True
============================= test session starts ==============================
platform linux2 -- Python 2.7.16+, pytest-4.6.5, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python2.7
cachedir: .pytest_cache
rootdir: /build/python-numpy-1.16.5, inifile: pytest.ini
collecting ... collected 7521 items / 166 deselected / 7355 selected

....

tmp/usr/lib/python2.7/dist-packages/numpy/core/tests/test_indexing.py::TestIndexing::test_single_int_index PASSED [ 10%]
tmp/usr/lib/python2.7/dist-packages/numpy/core/tests/test_indexing.py::TestIndexing::test_single_bool_index PASSED [ 10%]
tmp/usr/lib/python2.7/dist-packages/numpy/core/tests/test_indexing.py::TestIndexing::test_boolean_shape_mismatch Segmentation fault
```

i tried twice and the tests always failed on that specific test. This is for python 2.7.16. Let me know if i can help you debug the issue further (if it helps, i'm on an amd64 machine)

Regards,
Sandro

**Comment by charris** [comment]
Did those tests pass in 1.16.4? What Cython version? We do test with relaxed strides checking, but not on Python 2.7.

**Comment by charris** [comment]
NVM Cython, it isn't relevant to those functions. The only thing that looks possibly relevant is #13715.

**Comment by sandrotosi** [comment]
hmmm i believe this is my mistake :D :dagger: 
i adapted a different patch  from the same PR, without realizing it was already backported to 1.16.5 (or one of the previous patch releases we dont have in Debian) and so it was crashing.

removing the patch, the error goes away.

Sorry for the noise and confusion
