### ISSUE TITLE
ENH: Pivoted Cholesky Decomposition

### ISSUE THREAD

**Issue by jordan-melendez** [numpy/numpy#14450]
I am curious if there would be interest in adding a pivoted Cholesky function to `numpy.linalg`. The Pivoted Cholesky algorithm is a stable way to decompose ill-conditioned matrices, and is also a way to find a low-rank approximation the the Cholesky decomposition. This has wide applicability to the popular kernel methods in machine learning applications.

This functionality is available within [GSL](https://www.gnu.org/software/gsl/doc/html/linalg.html#pivoted-cholesky-decomposition) and [TensorFlow Probability](https://www.tensorflow.org/probability/api_docs/python/tfp/math/pivoted_cholesky), but I have yet to find a fast python version.

Here are some publications describing the algorithm and its use cases:
* [Liu et al (2019)](https://arxiv.org/pdf/1505.06195.pdf)
* [Harbrecht et al. (2012)](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=C9731825327E04A3EA523EDB31DA0378?doi=10.1.1.659.6096&rep=rep1&type=pdf)
* [Hammarling et al (2007)](http://eprints.maths.manchester.ac.uk/689/1/para_paper.pdf)
* [Bastos and OHagan (2007)](http://www.mucm.ac.uk/Pages/Downloads/Internal%20Reports/INT2.2.1%20LB%20Pivoting%20Cholesky%20Decomposition.pdf)

**Comment by charris** [comment]
I believe that functionality is now available in SciPy, but would need to check. @rgommers Do you know anything about that?

**Comment by pv** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.ldl.html seems to be what GSL has iiuc

**Comment by jordan-melendez** [comment]
@pv thank you for the link. I tested `ldl` against the TFP codes and I do not think that these are equivalent. The pivoted Cholesky decomposition solves P^T A P = L L^T for a particular form of L.

And with respect to the speed, I should have been more clear. I haven't found **any** python codes that perform this operation, besides my Cython-wrapped GSL codes and the TFP codes. The TFP seems like overkill and could certainly be faster if coded without any TF-specific code.

**Comment by charris** [comment]
I think you are looking for  the LAPACK `*pstrf` functions, which are available in SciPy but I don't see a higher level interface. I seem to recall something related passing by in the SciPy list in the past year, but maybe I missed the details.

**Comment by pv** [comment]
@jordan-melendez: why are they not equivalent? The GSL codes solve `P A P^T = LDL^T` which is the same.

**Comment by charris** [comment]
``` 
DPSTRF computes the Cholesky factorization with complete
 pivoting of a real symmetric positive semidefinite matrix A.
```

**Comment by jordan-melendez** [comment]
@charris yes, I think `dpstrf` is what I want! Now I need to figure out how to call it... I'm not super familiar with using LAPACK via scipy

@pv There exist GSL codes that do what I want. This is what my Cython code wraps. but unless I'm missing something, `ldl` is not doing what I want.

**Comment by pv** [comment]
The difference appears to be that `?sytrf` (ie `ldl`) may have 2x2 blocks in D, whereas GSL has diagonal D, and `?pstrf` includes it in the `L` factors, plus then possible details of the pivoting strategy.

**Comment by jordan-melendez** [comment]
@charris I just checked in https://docs.scipy.org/doc/scipy/reference/linalg.lapack.html, and `*pstrf` do not appear to be available in scipy. When I call

```python
sp.linalg.get_lapack_funcs('pstrf')
```
I get
```python
ValueError: LAPACK function dpstrf could not be found
```

**Comment by charris** [comment]
@pv I think the useful part may be the semidefinite proviso which allows dispensing with the `d`. The `*pstrf` functions return the numerical rank and return the effective factorization when the matric fails to be semidefinite. It seems like a good choice for `multivariate_normal` but is not available in NumPy.

**Comment by charris** [comment]
@jordan-melendez Looks like the documentation was added last weekend :)
```
commit 5d044c0f0de15293864b58b8748951088ee444d9
Author: Eric Larson <larson.eric.d@gmail.com>
Date:   Fri Aug 30 15:58:16 2019 -0400

    MAINT: Check that scipy.linalg.lapack functions are documented
```

**Comment by pv** [comment]
The `pstrf` routines were added only recently to the (not yet released) scipy 1.4.0

**Comment by jordan-melendez** [comment]
ahh got it. Thank you both for the info! So I guess the takeaway is: this is probably better suited for scipy than numpy, and wait for the 1.4.0 release that should at least contain `pstrf` and hopefully a higher level function as well.

And it would be neat to see this applied in `multivariate_normal`. I've run into problems with ill-conditioned matrices before, especially when playing with Gaussian processes. The Bastos & O'Hagan paper linked above discusses a modification of the pivoted Cholesky algorithm to solve this very problem.

**Comment by charris** [comment]
@jordan-melendez You might want to open an issue on scipy and ask for a higher level function.

**Comment by NathanWycoff** [comment]
I just wrote a pure python implementation for my own purposes, if it would be of any use to anyone find it [here](https://github.com/NathanWycoff/PivotedCholesky).

**Comment by mattip** [comment]
Closing, future comments and submissions should happen in the scipy repo or mailing list.
