### ISSUE TITLE
np.sinc() documentation "It works in 2-D as well" looks misleading

### ISSUE THREAD

**Issue by hhoppe** [numpy/numpy#14466]
The [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sinc.html#numpy.sinc) currently states:

> It works in 2-D as well:
> >>> x = np.linspace(-4, 4, 401)
> >>> xx = np.outer(x, x)
> >>> plt.imshow(np.sinc(xx))

This does not seem useful as it is computing np.sinc(x*y) over the domain [-4,4]*[-4,4].

In almost all cases, the desired generalization of np.sinc() to 2D is instead np.sinc(x)*np.sinc(y) [see [Wikipedia entry](https://en.wikipedia.org/wiki/Sinc_function#Higher_dimensions)]:

  xx, yy = np.meshgrid(np.linspace(-4, 4, 401), np.linspace(-4, 4, 401))
  plt.imshow(np.sinc(xx) * np.sinc(yy), cmap='gray')

**Comment by eric-wieser** [comment]
I'm not convinced this section is even useful in the docs. All ufuncs work "in 2d" (read: on 2d inputs). I'd be in favor of removing it.

**Comment by sameshl** [comment]
@eric-wieser If there is consensus I would love to help to remove it.
