### ISSUE TITLE
why np.dot(A, A.T)[0] and np.dot(A[0], A.T)  return different value when A is np.float32

### ISSUE THREAD

**Issue by akikan** [numpy/numpy#14471]
I want to return same values when this two calculation method.
・np.dot(A, A.T)[0]
・np.dot(A[0], A.T)

However two calculation method returns not same values. I want to know reason why different values.

### Reproducing code example:

```python
import numpy as np
temp = np.random.rand(20,20)
temp = temp.astype(np.float32)

# dot all
print(np.dot(temp,temp.T)[0])
>>[6.5369897 5.2805567 5.280808  5.869511  4.305103  3.911598  6.532375
 4.1619434 5.0178237 4.8641796 5.0499    4.9761305 4.148727  4.980519
 4.241932  5.0298777 4.760759  5.94255   5.3025136 4.234557 ]

# dot part
print(np.dot(temp[0],temp.T))
>>[6.5369897 5.280557  5.2808075 5.869511  4.3051033 3.911598  6.532375
 4.1619434 5.0178237 4.8641796 5.0499    4.9761305 4.1487274 4.980519
 4.241932  5.0298777 4.7607594 5.94255   5.302514  4.2345567]



np.testing.assert_array_equal(np.dot(temp,temp.T)[0], np.dot(temp[0],temp.T))

AssertionError: 
Arrays are not equal

Mismatch: 35%
Max absolute difference: 4.7683716e-07
Max relative difference: 1.14935766e-07
 x: array([6.53699 , 5.280557, 5.280808, 5.869511, 4.305103, 3.911598,
       6.532375, 4.161943, 5.017824, 4.86418 , 5.0499  , 4.97613 ,
       4.148727, 4.980519, 4.241932, 5.029878, 4.760759, 5.94255 ,
       5.302514, 4.234557], dtype=float32)
 y: array([6.53699 , 5.280557, 5.280807, 5.869511, 4.305103, 3.911598,
       6.532375, 4.161943, 5.017824, 4.86418 , 5.0499  , 4.97613 ,
       4.148727, 4.980519, 4.241932, 5.029878, 4.760759, 5.94255 ,
       5.302514, 4.234557], dtype=float32)

```

### Error message:
nothing

### Numpy/Python version information:

python : 3.6.5
numpy : 1.16.4

**Comment by seberg** [comment]
Floating point precision is only around that much (if the arrays are larger, you should expect larger errors). If you are not sure that float32 is good for your application, you may want to just avoid it. See also https://en.wikipedia.org/wiki/Single-precision_floating-point_format and https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by akikan** [comment]
sorry. maybe the "numpy.float32" created a misunderstanding.

・np.dot(A, A.T)[0]
・np.dot(A[0], A.T)

I think  these are same calculation. Data type and using number are same.
And call same method.

**Comment by akikan** [comment]
@seberg thank you for reply.

sorry. maybe the "numpy.float32" created a misunderstanding.

・np.dot(A, A.T)[0]
・np.dot(A[0], A.T)

I think  these are same calculation. Data type and using number are same.
And call same method.

**Comment by seberg** [comment]
No confusion as I said, order (and even more things) matter. So a + b + c in computers is different from c + b + a. So the differnet calls can differ in that way.

**Comment by akikan** [comment]
oh...
thank you!
