### ISSUE TITLE
Embedded Python: import numpy.core._multiarray_umath - undefined symbol

### ISSUE THREAD

**Issue by mariusalexander** [numpy/numpy#14480]
Hello,

my application has a python console embedded (It links against a python3.7m.so in the lib directory of my python env). I can import python packages like lxml but not numpy. It fails when trying to `import numpy.core._multiarray_umath` and throws `undefined symbol: PyExc_ImportError`. Numpy was installed in a python 3.7.4 environmnet with `pip install numpy`. The env was created using Miniconda on Debian10. I also tried importing numpy after installing it via conda with `conda install numpy`. It fails at the same step, but throws a different undefined symbol error: `PyMemoryView_FromObject`. I can however import numpy in the console of the OS. 

Does somebody have a hint or any idea? Thanks in advance!

### Reproducing code example:

_(since I import it in our own console, might be hard to reproduce. Here are the steps I did)_

Creating a python env with numpy:
conda create -p ./python37 python
conda activate python37
pip install numpy OR conda install numpy

In our Python Console:
import numpy

### Error message:

**Using pip install numpy**

import numpy
Traceback (most recent call last):
  File "pythonPath/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "pythonPath/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "pythonPath/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: pythonPath/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pythonPath/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "pythonPath/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: pythonPath/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError

**Using conda install numpy** 

The same as above but with a different undefined symbol: PyMemoryView_FromObject 

### Numpy/Python version information:

numpy version after pip install numpy: 1.17.2
numpy version after conda install numpy 1.1.6.4

`conda list` produces:
```
# packages in environment at pythonPath:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     1  
certifi                   2019.6.16                py37_1  
intel-openmp              2019.4                      243  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.14           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.4           py37h7e9f1db_0
numpy-base                1.16.4           py37hde5b4d6_0  
openssl                   1.1.1d               h7b6447c_0  
pip                       19.2.2                   py37_0  
python                    3.7.4                h265db76_1  
readline                  7.0                  h7b6447c_5  
setuptools                41.0.1                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.4                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3
```

`sys.path` produces:
pythonPath/lib/python37.zip
pythonPath/lib/python3.7
pythonPath/lib/python3.7/lib-dynload
pythonPath/lib/python3.7/site-packages

**Comment by mattip** [comment]
Those symbols come from python. Somehow you are not making those symbols available to numpy correctly in your embedded console. Can you import lxml or any other c-extension module?

**Comment by mariusalexander** [comment]
Yes I can import lxml, but I honestly dont know any other c-extension modules, since im quite new to python. Thank you for the hint. Our console is build with PythonQt by the way, I have opened an issue there aswell.

**Comment by seberg** [comment]
Did you figure this out @mariusalexander? I think we may have to close this, since this is unlikely to be an issue with NumPy, but with the setup. However, it would be nice if you can post any solution here, since other users tend to find these issues.

**Comment by mariusalexander** [comment]
I am sorry for not updating this issue. Indeed I could figure this out and it was _not_ related to NumPy, but to the setup of my Python Instance. Somehow the python library was not linked propperly. Currently I can't get a hold of the code I uesed to configure the instance, but it worked in the end! Thank you for your help.
