### ISSUE TITLE
BUILD: missing -fPIC on AIX

### ISSUE THREAD

**Issue by vcleniukBHS** [numpy/numpy#14488]
Platform: AIX
Version: 7.1
Python 3.6.5 from Bulls' Freeware
pip 19.2.3 from /opt/freeware/lib/python3.6/site-packages/pip (python 3.6)
numpy                  1.17.2

Issue: Numpy installs but does not import.
Error on import:
Original error was: Could not load module /opt/freeware/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.so.
        The local-exec model was used for thread-local
           storage, but the module is not the main program.
Examine the .loader section header with the 'dump -Hv' command.
### Reproducing code example:

```python
import numpy as np

### Error message:
### Numpy/Python version information:

<!-- Output from 'import sys, numpy; print(numpy.__version__, sys.version)' -->
>>> import sys, numpy; print(numpy.__version__, sys.version)
Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.6/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/opt/freeware/lib64/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/opt/freeware/lib64/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: Could not load module /opt/freeware/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.so.
        The local-exec model was used for thread-local
           storage, but the module is not the main program.
Examine the .loader section header with the 'dump -Hv' command.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/freeware/lib64/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/opt/freeware/lib64/python3.6/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/usr/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: Could not load module /opt/freeware/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.so.
        The local-exec model was used for thread-local
           storage, but the module is not the main program.
Examine the .loader section header with the 'dump -Hv' command.

>>>

**Comment by seberg** [comment]
Not sure what to make of this right now. I find: https://stackoverflow.com/questions/31704639/compiling-numpy-for-python3-for-aix-works-but-import-fails which may be on spot with `-fPIC` but it also says that some of our files should have additional includes, and I do not understand why `-fPIC` is not set in any case? I thought we test `AIX` nowadays, is there something special about this setup?

**Comment by rgommers** [comment]
>  I thought we test `AIX` nowadays, is there something special about this setup?

We don't, wish we could (no CI system available for it). You must be thinking of ppcle64.

That said, the IBM team (@ayappanec) has been contributing build fixes, and the status when building NumPy with GCC should be pretty decent (`xlc` we can't support).

> Issue: Numpy installs but does not import.

Without a full build log, there's not much we can say about that.

**Comment by mattip** [comment]
> Python 3.6.5 from Bulls' Freeware

It appears this version of python has a bug. When building a shared object, python's stdlib `distutils` pull the compiler flags from the `sysconfig.get_config_vars('CCSHARED')` value, which should include anything the platform needs. These are baked into python at compile time. @vcleniukBHS could you report what `import sysconfig; print(sysconfig.get_config_vars('CCSHARED')) prints?

**Comment by ayappanec** [comment]
AIX Toolbox Python3 don't have this issue. The "-fPIC" flag is passed appropriately. 
https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha#P

**Comment by rgommers** [comment]
> AIX Toolbox Python3 don't have this issue

Thanks @ayappanec!

Let's close this issue then, since it's not a NumPy issue. In general we'll recommend to use GCC and AIX Toolbox Python3 for AIX users. We can take patches for XLC and for other Python versions if users contribute them, but a lot of that stuff is so non-standard that it's very hard to get to work and support.
