### ISSUE TITLE
Different results from numpy.cov and numpy.var

### ISSUE THREAD

**Issue by FoxerLee** [numpy/numpy#14496]
I tried to use numpy.cov to calculate a covariance matrix. 
However, when I check the results, I find the value for Σ<sub>00</sub> is different between the value that I use numpy.var to calculate. 
Considering the math definition, Σ<sub>00</sub> should be equal to the variance of X<sub>0</sub>.

The result of numpy.var is the same as I use a calculator.

I think my code may have some mistakes, but I can`t find them :(

Here is my data (I do change the format of data to numpy.array. Below is just easy to see):
x = [109, 105, 111, 109, 117, 105, 84, 101, 83, 79, 101, 86, 95, 94, 94, 106, 105, 131, 74, 91, 99, 104, 126, 84, 87, 87, 108, 53, 82, 123, 95, 102, 114, 121, 85, 112, 119, 118, 87, 114, 85, 95, 92, 70, 123]

y = [397, 469, 422, 420, 489, 388, 399, 469, 453, 432, 474, 506, 433, 491, 440, 442, 434, 355, 451, 469, 402, 407, 423, 511, 402, 423, 368, 427, 431, 372, 411, 429, 428, 403, 451, 394, 474, 381, 480, 396, 444, 426, 404, 397, 372]

### Reproducing code example:

```python
import numpy as np
...
# here is for np.cov()
tmp = np.stack((x, y), axis=0)
sigma = np.cov(tmp)
print(sigma)

# and here is for np.var()
var = x.var()
print(var)
```

### Numpy/Python version information:
numpy: 1.17.2
python: 3.7.1

Thanks for help!

**Comment by seberg** [comment]
Cov defaults to the unbiased version normalizing with `(N - 1)`, you can set `ddof=1` to get the same result. Maybe this could be clearer from the documentation, but I think it is a very typical default.
