### ISSUE TITLE
show_config displays useless info when installed through conda-forge channel

### ISSUE THREAD

**Issue by jeremiedbb** [numpy/numpy#14492]
The recent BLAS scheme change in the numpy feedstock on conda-forge (https://github.com/conda-forge/numpy-feedstock/pull/143) make numpy always linked against libblas and liblapack which are actually symlinks to libopenblas. This makes show-config useless in this case:

```python
import numpy
numpy.show_config()

blas_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack']
    library_dirs = ['/home/jeremie/miniconda/envs/tst/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/jeremie/miniconda/envs/tst/include']
blas_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['/home/jeremie/miniconda/envs/tst/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/jeremie/miniconda/envs/tst/include']
lapack_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack']
    library_dirs = ['/home/jeremie/miniconda/envs/tst/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/jeremie/miniconda/envs/tst/include']
lapack_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['/home/jeremie/miniconda/envs/tst/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/jeremie/miniconda/envs/tst/include']
```

**Comment by mattip** [comment]
ok, I am wrong. It doesn't work on windows

**Comment by seberg** [comment]
@mattip can you try my funny hack? If you have MKL?

**Comment by mattip** [comment]
@cgohlke any ideas how to do this on windows? Does the code above work?

**Comment by jeremiedbb** [comment]
> Note that threadpoolctl doesn't work with debian's update-alternatives as threadpoolctl relies on the name of the realpath of the library.

We made a new release a few days ago. It includes the support symlinks, so it should support also support the update-alternatives system.

The main issue is that it does not support netlib blas or atlas, because it's designed to inspect libraries managing a threadpool (although atlas can be built in multhreaded mode so we might add this one at some point).
However it should not be too much work to tweak it into a runtime blas detection tool.

**Comment by seberg** [comment]
How big is our insterest in attempting to do runtime inspection for the purpose of either controlling threads, or simply being able to tell users to run `np.show_config()` to get more useful information about their system. If we expand `show_config`, I think we should also ask downstream patchers to include distributer information, so that we know it is an intel/Anaconda-patched version without any hassle.

**Comment by rgommers** [comment]
It would be quite nice to have better diagnostics. Not just runtime - I'm tempted to just stash the whole build log in it. We get so many bug reports we can't deal with because we never get a build log.

**Comment by mattip** [comment]
In addition to the build log, we should show `_numpy_config.h` and `config.h`

xref gh-9258 to add documentation to `show_config` and make it discoverable

**Comment by mattip** [comment]
Closing. This relates to the old distutils-based show_config.
