### ISSUE TITLE
Numpy isn't working on hackerrank.

### ISSUE THREAD

**Issue by Luca715** [numpy/numpy#14505]
I am on hackerrank, I installed anaconda before and numpy works fine on my spyder IDE but not on hackerrank. My os is windows 10 and I don't have multiple versions of python installed.
### Reproducing code example:
``` import numpy```

```python
import numpy as np
<< your code here >>
```

**Comment by charris** [comment]
Could you supply some information as to what the problem was? What is hackerrank?

**Comment by Luca715** [comment]
Yeah sure, HackerRank is a website that has coding exercises in various languages. I tried importing numpy on the Hackerrank kernel and it is giving me this message:

• IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
• 
• Importing the multiarray numpy extension module failed. Most
• likely you are trying to import a failed build of numpy.
• Here is how to proceed:
• - If you're working with a numpy git repository, try `git clean -xdf`
• (removes all files not under version control) and rebuild numpy.
• - If you are simply trying to use the numpy version that you have installed:
• your installation is broken - please reinstall numpy.
• - If you have already reinstalled and that did not fix the problem, then:
• 1. Check that you are using the Python you expect (you're using /usr/local/bin/python3),
• and that you have no directories in your PATH or PYTHONPATH that can
• interfere with the Python and numpy versions you're trying to use.
• 2. If (1) looks fine, you can open a new issue at
• https://github.com/numpy/numpy/issues. Please include details on:
• - how you installed Python
• - how you installed numpy
• - your operating system
• - whether or not you have multiple versions of Python installed
• - if you built from source, your compiler versions and ideally a build log
• 
• Note: this error has many possible causes, so please don't comment on
• an existing issue about this - open a new one instead.
• 
• Original error was: PyCapsule_Import could not import module "datetime"
• 


Sent from Mail for Windows 10

**Comment by charris** [comment]
Hmm. We have had one other recent report of a problem with that, the error comes from cPython. Can you import `datetime`? What Python version are you running?

**Comment by Luca715** [comment]
It could not import datetime, Python version is 3.7.

Sent from Mail for Windows 10

**Comment by MSeifert04** [comment]
You encounter this problem when submitting your code on the hackerrank website? 

If yes, that seems like something the hackerrank developers needs to solve.

**Comment by Luca715** [comment]
Yeah to the first question, and I agree with you it does seem like it’s their problem since numpy works fine in other kernels. I don’t know why they ask people to go to GitHub.

Sent from Mail for Windows 10

**Comment by MSeifert04** [comment]
@Luca715 Maybe you can contact the Hackerrank support and give them a link to this github issue. Only the hackerrank staff knows how they manage/installed Python/NumPy in the service/environment that they use on the website and that's essential information to solve this problem.

**Comment by Luca715** [comment]
Yeah I’ll do that. Thanks for the help though.

Sent from Mail for Windows 10

**Comment by MSeifert04** [comment]
Just for cross-reference: A similar problem was reported in #14377, #13398, and #14474

**Comment by mattip** [comment]
Closing this one as a duplicate and since the user does not control their environment
