### ISSUE TITLE
np.random.binomial produces inconsistent output with same seed in 1.16 -> 1.17

### ISSUE THREAD

**Issue by dburkhardt** [numpy/numpy#14522]
### Reproducing code example:

```python
import numpy as np
np.random.seed(42)

np.random.binomial(1, np.linspace(0, 1, 1000), 1000).sum()
```

produces `515` on version 1.16.3 and `514` on version 1.17.0+

### Numpy/Python version information:

```
1.16.3 3.7.3 (default, Mar 26 2019, 21:43:19)
[GCC 8.2.1 20181127]
```

and 

```
1.17.2 3.7.3 (default, Mar 26 2019, 21:43:19)
[GCC 8.2.1 20181127]
```

**Comment by WarrenWeckesser** [comment]
Simpler example:

```
In [44]: np.__version__
Out[44]: '1.16.4'
In [45]: np.random.seed(12345)
In [46]: np.random.binomial(1, [0, 0.5])
Out[46]: array([0, 0])
```

```
In [60]: np.__version__
Out[60]: '1.18.0.dev0+33d5f9c'
In [61]: np.random.seed(12345)
In [62]: np.random.binomial(1, [0, 0.5])
Out[62]: array([0, 1])
```

**Comment by WarrenWeckesser** [comment]
This appears to be the result of an explicit check for `p = 0` in the new code: https://github.com/numpy/numpy/blob/e4de01d073f554dbed4a1f25fe6bb8cbb4e40b5e/numpy/random/src/distributions/distributions.c#L908

The old code did not have this shortcut, so it would it makes at least one more call to `rk_double(state)` than is made in the new code.

**Comment by charris** [comment]
Looks like a regression, the call sequence of the old code should not have been changed unless the values resulted in a hang, in which case it probably wouldn't matter since no one would use those values.

**Comment by WarrenWeckesser** [comment]
@charris, I'm looking into fixing the regression.

**Comment by charris** [comment]
@WarrenWeckesser Great, I was just starting to investigate.

We do test the generated sequences for many things, but it seems that doesn't catch changes in corner cases. Good thing we no longer make that guarantee :)

**Comment by dburkhardt** [comment]
Thank you all for looking into this! I really appreciate the work you put into Numpy.
