### ISSUE TITLE
Python import error with numpy

### ISSUE THREAD

**Issue by picgallo** [numpy/numpy#14537]
### Reproducing code example:

Python 3.6.9 (default, Jul 21 2019, 14:33:59)
[GCC 7.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/lib/python3.6/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)

```python
import numpy as np
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/lib/python3.6/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)


<!-- Remove these sections for a feature request -->

### Error message:

<!-- If you are reporting a segfault please include a GDB traceback, which you
can generate by following
https://github.com/numpy/numpy/blob/master/doc/source/dev/development_environment.rst#debugging -->

<!-- Full error message, if any (starting from line Traceback: ...) -->

### Numpy/Python version information:

<!-- Output from 'import sys, numpy; print(numpy.__version__, sys.version)' -->

**Comment by picgallo** [comment]
I hope I'm using this correctly. I'm running Python3.6.9 from Cygwin on the Windows 10 OS. Using Cygwin (64-bit) I completely uninstalled and then reinstalled the python numpy module. I have checked that there is absolutely no interference with my PYTHONPATH (I even set it to "" (empty), and still get this error.

**Comment by picgallo** [comment]
Am I using this comment area correctly?

**Comment by mattip** [comment]
You might want to read about [github markdown in comments](https://guides.github.com/features/mastering-markdown/) and the use of three backticks to syntax-highlight code. In particular, there are some lines missing from the trackback that describe the version of numpy you are using and the exact path of your python executable.

We don't have many users that we know of using cygwin. Could you go into a little more detail where you got your python from, and how exactly you are installing numpy?

**Comment by picgallo** [comment]
I installed Python3 (3.6) and Python2 (2.7) from Cygwin. I also
specifically installed the numpy module from Cygwin. Cygwin would call
these packages, and makes it easy to install, upgrade, or remove packages
from many mirrored sites. When installing any package, it resolves
dependencies on other packages that it may need, and makes sure you install
those also if you haven't already done so. The simplest way I could show
the error I was getting when importing numpy was simply to run python3 from
the command line and type in the single line "import numpy". Below is
(hopefully) a more complete traceback from all of this (though I read your
suggested link to gethub's markdown, I'm still uncertain how/when to use
it).  What follows between the two lines demarcated by dashes is the
literal results of this simplified test.
-------------------  8< --- code starts below this cut ------------
$ python3

Python 3.6.9 (default, Jul 21 2019, 14:33:59)

[GCC 7.4.0] on cygwin

Type "help", "copyright", "credits" or "license" for more information.

>>> import numpy

Traceback (most recent call last):

File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 40, in
<module>

from . import multiarray

File "/usr/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12,
in <module>

from . import overrides

File "/usr/lib/python3.6/site-packages/numpy/core/overrides.py", line 6, in
<module>

from numpy.core._multiarray_umath import (

ImportError: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "<stdin>", line 1, in <module>

File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 142, in
<module>

from . import core

File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 71, in
<module>

raise ImportError(msg)

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed. Most

likely you are trying to import a failed build of numpy.

Here is how to proceed:

- If you're working with a numpy git repository, try `git clean -xdf`

(removes all files not under version control) and rebuild numpy.

- If you are simply trying to use the numpy version that you have installed:

your installation is broken - please reinstall numpy.

- If you have already reinstalled and that did not fix the problem, then:

1. Check that you are using the Python you expect (you're using
/usr/bin/python3),

and that you have no directories in your PATH or PYTHONPATH that can

interfere with the Python and numpy versions you're trying to use.

2. If (1) looks fine, you can open a new issue at

https://github.com/numpy/numpy/issues. Please include details on:

- how you installed Python

- how you installed numpy

- your operating system

- whether or not you have multiple versions of Python installed

- if you built from source, your compiler versions and ideally a build log

Note: this error has many possible causes, so please don't comment on

an existing issue about this - open a new one instead.

Original error was: No such file or directory

>>>

----------------  end of code example ---------

Since the ultimate source of the error originates in the _multiarray_umath
module under numpy.core, I tried to examine that, but it is a dll

 (specifically, _multiarray_umath.cpython-36m-x86_64-cygwin.dll) so I could
not probe any further on my own.


Does this help?

Mike

**Comment by passedball** [comment]
did you resolve it???

**Comment by anirudh2290** [comment]
@passedball Please go through the troubleshooting docs to see if it helps to resolve your issue.

**Comment by rossbar** [comment]
I'm going to close this due to inactivity. If the issue persists or you think you have a related issue, please first check the linked troubleshooting guide. If that doesn't help, open a new issue with current info on the system and installation procedure.
