### ISSUE TITLE
Missing .. versionadded in `prepend` parameter of np.diff

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#14538]
There is no versionadded tag for prepend on https://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html. This is not a huge problem, but I've started using that argument quite a bit more, so it would be nice to know what versions break my code.

I would be happy to submit a PR, but am not sure what the correct version is (I think it's 1.16.0, but would prefer to have an expert verify).

**Comment by seberg** [comment]
Yes, it is in the 1.16 release notes.

**Comment by madphysicist** [comment]
@seberg. I apologize for the laziness. My corporate firewall gets all weird with GitHub. I could have waited til I got home. Thanks for the check.
