### ISSUE TITLE
Import Numpy on embedded Python 3.5.7 in C++ application

### ISSUE THREAD

**Issue by csouza0804** [numpy/numpy#14549]
Hello all,

I'm trying to embedded Python in c++ application and everything is ok, but when importing numpy I got this error message. I've already included everything on PATH and create PYTHONPATH and nothing works.

Do you have any advice for me? 

I must embed Python on my application because I don't want to make my user to install python and all of libraries that must have. On windows it is working, but on Linux it isn't.

I'm using lubuntu 16.04.

My application uses Qt 4.8.4 and gcc-4.8.

Thank you in advance.

Claudio Souza

### Numpy/Python version information:
I've downloaded Numpy from pip and from git, Always trying the latest version.
pip - numpy 1.17.2
git - numpy 1.18.0

### Error message:
Traceback (most recent call last):
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/_multiarray_umath.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyExc_RecursionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.5 from "/usr/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.0.dev0+7618f19" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/_multiarray_umath.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyExc_RecursionError

**Comment by seberg** [comment]
That is a sumbol which should be exported by Python, maybe check `ldd /home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/_multiarray_umath.cpython-35m-x86_64-linux-gnu.so`. I expect a linking issue. Possibly linking against the systems python2.

**Comment by csouza0804** [comment]
I thing that I forgot to mention. 
I've compiled Python 3.5.7 by myself.

@seberg 
I did what you said and got this
lmdc@lmdc-VirtualBox:~/testPython/Python3.5.7$ ldd /home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy/core/_multiarray_umath.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffe6beda000)
	libopenblasp-r0-2ecf47d5.3.7.dev.so => /home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy/core/../.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so (0x00007f440d185000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f440ce7c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f440cc5f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f440c895000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f440f50e000)
	libgfortran-ed201abd.so.3.0.0 => /home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0 (0x00007f440c59b000)

**Comment by seberg** [comment]
Sorry, yeah python is not explicitly linked like this. In any case, the only thing I can think of is that either during compilation of numpy you are picking up wrong header files (how do you install/compile numpy), or your program is embedding an incorrect python version.
Specifically `PyExc_RecursionError` is new in python 3.5, which is the oldest supported python version by NumPy. I cannot really help much, except asking how you compiled NumPy maybe, and to make sure that your program loads the correct python (the paths look like it though?). I am sure this is not an issue with numpy, this is a problem you would see with any python extension using this or similar symbols.

**Comment by csouza0804** [comment]
Hello,
@seberg 

I could run compile Python3.5.7 twice, once compiling with --enable-shared and once without it.
From Qt Creator, it is running without any problem, but when I call from the terminal, it return the following error:

Btw, I know that it is not numpy problem, but know I'm only asking if you have already faced a problem like that. I will wait some minutes for your reply or someone that is able to and close this ticket.
I only opened this issue because it was suggested from the error message.

Thank you so much.

```
Traceback (most recent call last):
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/multiarray.py", line 9, in <module>
    import functools
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/weakref.py", line 12, in <module>
    from _weakref import (
ImportError: cannot import name '_remove_dead_weakref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lmdc/testPython/moduleHello.py", line 1, in <module>
    import numpy
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/lmdc/testPython/Python3.5.7/lib/python3.5/site-packages/numpy-1.18.0.dev0+7618f19-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.5 from "/usr/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.0.dev0+7618f19" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: cannot import name '_remove_dead_weakref'
```

**Comment by csouza0804** [comment]
Guys, after recompiling using --enable-shared and embedding in my project, it works.
I don't know if it is a better solution but it is working!
