### ISSUE TITLE
np.ascontiguousarray() incorrect behavior on empty arrays

### ISSUE THREAD

**Issue by nikhilmishra000** [numpy/numpy#14550]
`np.ascontiguousarray()` does not work on arrays with zero elements

### Reproducing code example:

```python
import numpy as np

x = np.zeros((0, 3, 4))[..., ::-1]
print(x.strides) # (96, 32, -8)
y = np.ascontiguousarray(x)
print(y.strides) # still (96, 32, -8), but should be (96, 32, 8)
```

### Error message:

Behavior is incorrect (output array still has negative strides).

### Numpy/Python version information:

```
1.16.1 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57)
[GCC 7.2.0]```

**Comment by eric-wieser** [comment]
I think numpy defines empty arrays to be contiguous, since if you have 0 elements there are no discontinuities.

**Comment by seberg** [comment]
Indeed, this has been the case for years. NumPy defines contiguity not based on random strides, but based on actual memory layout. There is actually a compile time evn variable that might still work to disable it `NPY_RELAXED_STRIDE_CHECKING=0`.

In any case, everything is correct here, if you know that your array is contiugous, maybe double check and then *do not do assumptions about the stride values, use the itemsize and shape instead*!
