### ISSUE TITLE
Support matrix/scalar multiplication for `np.matmul`

### ISSUE THREAD

**Issue by yaroslavvb** [numpy/numpy#14559]
Would it be feasible to have matrix/scalar and vector/scalar multiplication in `np.matmul` match behavior of `np.dot`?

Since`np.matmul` already supports mixing rank-2 and rank-1 tensors, extending it to rank-0 would not make it more confusing.

The reason for not using `np.dot` is because of preference for matmul broadcasting rules (see https://github.com/tensorflow/tensorflow/issues/5523)

**Comment by seberg** [comment]
@yaroslavvb there has been a discussion about this at the time and it was described in detail even in the PEP: https://www.python.org/dev/peps/pep-0465/#semantics last point in the Semantics section, I think this type of thing should probably be brought up on the mailing list, and then should have to be signed off by Python itself.

I do not want to discourage you from exploring it, but it will require some more convincing and possibly a bit of a uphill battle considering that it is defined by a PEP.

**Comment by yaroslavvb** [comment]
@seberg thanks for the background, the motivation is more clear now.
