### ISSUE TITLE
Checking presence of key in dictionary before assigning.

### ISSUE THREAD

**Issue by farziengineer** [numpy/numpy#14560]
https://github.com/numpy/numpy/blob/685aef76de436bf2b42a74a52a22041d08a79007/numpy/f2py/capi_maps.py#L244-L247

The above snippet traverses the dictionary twice. It can be avoided by the following snippet.
```python 
a = var.get('result', var['name'])
```

**Comment by seberg** [comment]
Closing, thanks for the hint. I guess we may not do this one, but in general small maintenance is always welcome!
