### ISSUE TITLE
np.set_printoptions param error

### ISSUE THREAD

**Issue by daidai21** [numpy/numpy#14575]
### Reproducing code example:

```python
import numpy as np
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None)
```

### Error message:

```python
np.set_printoptions(degeitems=5)
```
param threshold=None support win, but not support ubuntu

### Numpy/Python version information:

Python3.7.1,  numpy1.15.4 in Windows
python 3.6.8, numpy1.16.4 in Ubuntu

**Comment by mattip** [comment]
Not clear what your are reporting. This works fine for me on Ubuntu with python 3.6.7
```
import numpy as np
np.set_printoptions(precision=None, threshold=None, edgeitems=None, 
          linewidth=None, suppress=None, nanstr=None, infstr=None)
np.set_printoptions(edgeitems=5)
```
Please try  to show code so we can reproduce the failure, and provide the traceback from the error you see (as text, not a screen capture)

**Comment by daidai21** [comment]
This is my config error. sorry.
