### ISSUE TITLE
Bool Numpy.ndarray Error

### ISSUE THREAD

**Issue by achanger** [numpy/numpy#14589]
### Reproducing code example:

```python
import numpy as np

bool_arr = np.zeros(shape=(2,2)) < -1
"""
Then `bool_arr`  is 
array([[False, False],
       [False, False]])
"""

if bool_arr[(0,0)] is False:
    print('bool_arr[(0,0)] is False')
# should output 'bool_arr[(0,0)] is False'  but Nothing is happended.

if not bool_arr[(0,0)]:
    print('bool_arr[(0,0)] is False')
# output : 'bool_arr[(0,0)] is False'



```

### Numpy/Python version information:

my numpy Version: 1.16.4

**Comment by seberg** [comment]
NumPy has its own bool scalars, which are different singletons from the python ones, becaues they have additional methods. You can use `item` if you must convert, or just do not use the `is` operator.

**Comment by achanger** [comment]
> NumPy has its own bool scalars, which are different singletons from the python ones, becaues they have additional methods. You can use `item` if you must convert, or just do not use the `is` operator.

thanks!
