### ISSUE TITLE
Status of aliased/wrapped functions, including `numpy.cumproduct`, `np.alltrue`, `np.sometrue`.

### ISSUE THREAD

**Issue by stuartarchibald** [numpy/numpy#14584]
These functions exist and are part of the public API.

* `round_` (has docstring, has documentation)
* `product` (has docstring, no documentation)
* `cumproduct` (has docstring, no documentation)
* `sometrue` (has docstring, no documentation)
* `alltrue` (has docstring, no documentation)
* `rank` (has docstring, no documentation)

they also all trivially alias/wrap something else in the API that is more prevalent and clearly supported/documented.

Numba has just received PRs to enable support for a few of these functions, but I am now wondering if they are actually needed in NumPy itself. There seems to be limited internal references in the NumPy code base to the above.

This ticket is of a similar ilk to https://github.com/numpy/numpy/issues/14155.

Thanks in advance for your input!

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/pull/4604 https://github.com/numba/numba/pull/4583

**Comment by seberg** [comment]
I think we agree. Most of them should be deprecated and removed, I think `rank` just has been removed completely in the dev version. One reason why this has not happened yet is that we have a lot of constants and direct aliases as well. And those would be a bit easier deprecated if we can rely on users having python 3.7 with module level `__getattr__`.
(That said, a few of these are not direct aliases, so there is no reason to hesitate tagging on a deprecation warning)

**Comment by stuartarchibald** [comment]
Thanks for the info @seberg. I think I'm of the view then that there's not a lot of merit in Numba supporting these, new code should use the new equivalent functions and old code using these could trivially be updated to work with Numba, Numba would even permit a direct alias defined locally and just compile it anyway. Will raise it at our core dev meeting. Thanks again for the input, much appreciated.
