### ISSUE TITLE
Update docs on extending numpy.random with Cython/Numba for 1.18.0 release

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#14594]
The Cython/Numba API for `numpy.random` was removed for `1.17.3` in gh-14593. The `extending` docs were removed there, but left as is in `master` (on request of @mattip, see gh-14562). Assuming we reintroduce a complete API that can be used from Cython and Numba in 1.18.0, make sure to update these docs. If we don't manage that reintroduction, then completely remove the docs.

**Comment by mattip** [comment]
We now test and [document](https://numpy.org/devdocs/reference/random/extending.html) extending via cython and numba. CFFI will be merged soon. Closing. Please reopen if I misunderstood and more is needed.
