### ISSUE TITLE
Unexpected behavior combining slices and index arrays in ndarray

### ISSUE THREAD

**Issue by jhigbie** [numpy/numpy#14609]
Combining index array and slice of ndarray gives unexpected behavor. Documentation of indexing seems to suggest that slicing and indexed arrays can be mixed and matched freely, but examply below suggests that doing this (particularly when followed by a reshape operation that masks change in shape) can be dangerous and lead to wrong results.  At the very least, I think this should raise a warning, but to my inexpert eye it looks like a bug that should be fixed. Thanks!

### Reproducing code example:
 m = np.arange(24).reshape(2,3,4)                                                                                  
m[0, :2, np.array([1,2,3])].shape  #Gives (3, 2)
m[0, :2, 1:4].shape   # Gives (2, 3)

### Numpy/Python version information:
Numpy: 1.15.4     
Python: 3.6.5     
Dist: Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]

**Comment by seberg** [comment]
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#combining-advanced-and-basic-indexing and also https://numpy.org/neps/nep-0021-advanced-indexing.html We should get that at some point.

**Comment by seberg** [comment]
Doc improvements are always welcome... although I think even that is possibly on the agenda for the GSoD (but not sure this specific). If you have suggestions, please open a PR!
