### ISSUE TITLE
Seg. fault with ufunc given NULL for `data` in `PyUFunc_FromFuncAndData`.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#14613]
The documentation of the `data` argument of [`PyUFunc_FromFuncAndData`](https://numpy.org/devdocs/reference/c-api/ufunc.html#c.PyUFunc_FromFuncAndData) says

* data – Should be NULL or a pointer to an array of size ntypes . This array may contain arbitrary extra-data to be passed to the corresponding loop function in the func array.

But if I pass in NULL for this argument, I get a seg. fault when the ufunc is called.  If I pass in an array of NULLs, it works as expected.

Is this a mistake in the documentation, or a bug in the ufunc code?

 It would be nice if passing in `NULL` worked, so I didn't have to create a dummy array to avoid the seg. fault.

### Reproducing code example:

In the line https://github.com/WarrenWeckesser/ufunclab/blob/b42b249b86c9710a179015608aee9358639edcd3/src/logfactorial/logfactorial_ufunc.c#L92, change `data` to `NULL`.  When the ufunc created by this function is called, Python will seg. fault.

### Numpy/Python version information:

```
In [8]: numpy.__version__                                                                                                            
Out[8]: '1.18.0.dev0+68bd6e3'

In [9]: sys.version                                                                                                                  
Out[9]: '3.7.3 (default, Mar 27 2019, 16:54:48) \n[Clang 4.0.1 (tags/RELEASE_401/final)]'
```

**Comment by seberg** [comment]
I would like to deprecate this function in any case hopefully sooner rather than later, and not sure how annoying the bookkeeping would be. So I would probably just update the docs. But can't say I care much either way.

**Comment by madphysicist** [comment]
Ran into the same issue. @seberg I am using this function because it's the one recommended by the tutorial here: https://numpy.org/doc/stable/user/c-info.ufunc-tutorial.html. The page has a bunch of potentially questionable advice, though it certainly got me off the ground. What alternative do you recommend?

**Comment by seberg** [comment]
There is new API in `experimental_dtype_api.h`.  Fixes to docs and/or code welcome though, since the new API will not be there for a while.  I am just not enthusiastic about fixing this API that we should get rid of as soon as possible (which is not very fast).

**Comment by madphysicist** [comment]
I came across this because it's the recommended path from the tutorial. Since I'm making grammar and whitespace corrections to that (#20683), I'll submit a one line change removing the offending like from the docs. It's not the "right" solution, but given all you've said, it appears to be the pragmatic one.

**Comment by madphysicist** [comment]
@seberg #20686. Let me know if it's in the right direction.

**Comment by madphysicist** [comment]
Same behavior here by the way: https://github.com/madphysicist/is_integer_ufunc/blob/main/is_integer.c#L228, leading to the ugly workaround a few lines up: https://github.com/madphysicist/is_integer_ufunc/blob/main/is_integer.c#L204. Hopefully #20689 fixes this.
