### ISSUE TITLE
[Bug] Wrong Numpy .stride/.contiguous calculations when making view of a non-contiguous ndarray

### ISSUE THREAD

**Issue by VideoPlayerCode** [numpy/numpy#14627]
Numpy is doing something very wrong when you tell it to make a view of a non-contigous view.

The example below is very simple:
- `img1` = original ndarray with contiguous ("read forwards" memory).
- `img2` = a view of img1, with reversed stride ("read backwards" memory) for the 3rd dimension.
- `img3` = a partial sub-view of img2...

The bug: Numpy creates the `img3` PyArray object with reverse strides (same as img2, which is correct), but with both `contiguous` flags set to true (WTF?!).

### Reproducing code example:

Run this in the Python console:

```python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> img1 = np.zeros([1080, 1920, 3], np.uint8)
>>> img1.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

>>> img1.strides
(5760, 3, 1)
>>> img2 = img1[...,::-1] # make view with reversed strides
>>> img2.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

>>> img2.strides
(5760, 3, -1)
>>> img3 = img2[0:0,100:100] # make partial view of the img2-view's reversed strides
>>> img3.flags
  C_CONTIGUOUS : True <--- WTF?
  F_CONTIGUOUS : True <-- DOUBLE-WTF!?
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

>>> img3.strides
(5760, 3, -1)
>>>
```

### Numpy/Python version information:

Output from 'import sys, numpy; print(numpy.__version__, sys.version):

```
1.17.1 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
```

**Comment by charris** [comment]
`img2[0:0, 100:100]` is an empty array.

**Comment by VideoPlayerCode** [comment]
@charris Oh god, you're right. I never checked the contents of the array, and I messed up on the copying ranges, misremembering it as `[x1:y1,x2:y2]` but it's actually `[x1:x2,y1:y2]`.

Here's the fixed example 3:

```
>>> img3 = img2[0:100,0:100]
>>> img3.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

>>> img3.strides
(5760, 3, -1)
```

Alright, the slices do copy the strides properly and detect the contiguous flag properly.

And if I go back to the original example (which created a 0-size array) and try `img3 = img2[0:0,100:100]; img3.reshape((10,10,3))` (somehow reshaping the slices to take more data from the underlying RAM) does not mess things up either since `cannot reshape array of size 0 into shape (10,10,3)`...

So I can safely and happily conclude that I was wrong about the views creating incorrect contiguous/strides values.

**The only thing that maybe can be complained about is that the views say `C_CONTIGUOUS : True, F_CONTIGUOUS : True` when they're a 0-byte slice of a non-contiguous memory. But oh well, maybe not worth fixing?**

**Comment by mattip** [comment]
Closing. In the numpy universe, empty arrays are contiguous by definition, even if they are views of non-contiguous arrays. If you wish to probe the base array, check `arr.base`. If you disagree or I misinterpreted, please reopen.

**Comment by VideoPlayerCode** [comment]
@mattip I agree, a 0-byte view can be called contiguous since it's literally empty. It just looked weird to see a view of a non-contiguous array be marked as contiguous. But I agree with the rationale behind saying that `empty = contiguous`.
