### ISSUE TITLE
Add API documentation for np.distutils.core.Extension class

### ISSUE THREAD

**Issue by dstansby** [numpy/numpy#14633]
[The f2py docs mention](https://docs.scipy.org/doc/numpy/f2py/distutils.html) that the `numpy.distutils.core.Extension` class can be used, but as far as I can tell there is no documentation of this class either in the main numpy documentation or in the f2py documentation.

**Comment by rgommers** [comment]
Thanks @dstansby. Looking at that, it does seem like that's public and needs to be added to the docs. `numpy.distutils.core` may have been meant as the thing that imports the public API part from other Python files in that directory. Unclear though. For now, adding `core.Extension` to the docs sounds good.
