### ISSUE TITLE
Pretty print a numpy array 

### ISSUE THREAD

**Issue by sursu** [numpy/numpy#14647]
I would like to make a suggestion.

Often when I work with matrices I want to see them.
Take the following example:
```python
A = np.random.normal(size=(8,8))
```
If I print this matrix, the result looks like this:
```
array([[-0.4197841 ,  0.8869173 , -1.01218841,  0.20962467, -1.66233783,
         0.75916283, -0.79514077,  1.39641687],
       [-1.31457829,  0.64820939, -0.52143379,  1.10524647, -0.3702006 ,
        -0.64543357, -1.65307164, -0.42988743],
       [-1.73077336, -0.05517376,  1.52026569, -0.18947726, -0.59604738,
         0.96965635, -0.33915261,  0.20560888],
       [ 0.69676854, -0.85949005,  0.33328365,  1.34804733, -0.68506514,
         2.71773932, -0.54172768, -0.79013522],
       [ 0.69281042, -0.31912083, -1.05589426,  0.29144272,  0.56898699,
        -0.9181396 , -0.85048835,  1.2285    ],
       [ 1.35718271,  0.44395911,  0.08274088, -1.9552798 , -0.36522002,
         0.23038457,  1.09807025,  0.45192115],
       [ 2.3159305 , -1.76762656, -0.34567323, -0.1662745 , -0.98934354,
        -0.72486807,  0.23108727,  0.86718998],
       [-0.74078575,  0.49186028, -0.77618801,  0.91610707, -1.86301596,
         1.302024  ,  1.62730292,  0.57522481]])
```
This looks even worse when scientific notation is involved.

I would very much like to see something like Mathematica's `TableForm`, or `MatrixForm`, or `Grid` (in order of preference):
```Mathematica
A = RandomVariate[NormalDistribution[], {13, 13}];
A // TableForm
```
![image](https://user-images.githubusercontent.com/12001304/66261212-82c67e00-e7c9-11e9-825b-0717946f8ea8.png)

I know about this solution:
```python
with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
    print(A)
```
but, it is a bit cumbersome.

**Comment by eric-wieser** [comment]
Are you looking for something suitable for notebook use?

One option would be to use HTML tables there, something like this: https://www.reddit.com/r/Python/comments/9un3bz/pretty_printing_of_numpy_ndarrays_descriptions_in/

**Comment by sursu** [comment]
I see your implementation @eric-wieser , and I like it. But, it is impractical to search for it every time I want to just view a matrix.

I could simply use:
```python
A = pd.DataFrame(A)
A.columns = ['']*A.shape[1]
print(A.to_string(index=False))
```
But, I was hoping there would be a `numpy` function to just help me view my 2D array without bothering too much.

**Comment by WarrenWeckesser** [comment]
You could make a little wrapper of `printoptions` that hooks into the `__array_ufunc__` protocol to make a print function out of `//`:

```
import numpy as np

class PrintArray:

    def __init__(self, **kwargs):
        self._kwargs = kwargs

    def __repr__(self):
        rpr = ('PrintArray(' +
               ', '.join([f'{name}={value}' for name, value in self._kwargs.items()]) +
               ')')
        return rpr

    def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
        if ufunc != np.floor_divide:
            return NotImplemented
        a = inputs[0]
        with np.printoptions(**self._kwargs):
            print(a)
```

For example,
```
In [159]: np.random.seed(123454321)

In [160]: x = np.random.randn(3, 12)**2
```
Here's the default output for `x` in an ipython session:
```
In [161]: x
Out[161]: 
array([[5.42920903e-02, 1.74842606e+00, 2.95241848e-03, 3.75340944e-01,
        5.63148262e-01, 3.26371748e-01, 4.32310452e-02, 1.64979215e+00,
        3.41208058e-01, 1.35821383e+00, 5.64967184e-01, 1.50425895e-04],
       [4.15542015e-01, 1.27261392e+00, 7.39076695e+00, 3.61627449e-02,
        4.00270703e-02, 2.74343136e-01, 1.07449461e-01, 1.43529972e+00,
        1.11001164e+00, 1.05004814e+00, 1.17776173e+00, 5.72065298e-01],
       [1.67961819e-01, 6.95184128e-01, 1.97822277e-01, 1.66624335e+00,
        6.04639057e-02, 2.71034987e-01, 3.00196534e-01, 2.78154740e-02,
        2.15563380e-01, 1.02378101e-01, 2.28846579e+00, 4.35082459e-01]])
```
Create a `PrintArray` instance. It takes the same arguments as `np.set_printoptions`.  Then execute `x // p`.
```
In [162]: p = PrintArray(precision=4, linewidth=150, suppress=True)

In [163]: x // p
[[0.0543 1.7484 0.003  0.3753 0.5631 0.3264 0.0432 1.6498 0.3412 1.3582 0.565  0.0002]
 [0.4155 1.2726 7.3908 0.0362 0.04   0.2743 0.1074 1.4353 1.11   1.05   1.1778 0.5721]
 [0.168  0.6952 0.1978 1.6662 0.0605 0.271  0.3002 0.0278 0.2156 0.1024 2.2885 0.4351]]
```
Of course, you could have the method `__array_ufunc__` do whatever you want.  It doesn't have to be a wrapper of `np.printoptions`.

You have to create the instance `p` once, but then you can reuse it, e.g.:

```
In [195]: y = np.exp(-np.linspace(0, 15, 12))

In [196]: y
Out[196]: 
array([1.00000000e+00, 2.55729160e-01, 6.53974032e-02, 1.67240230e-02,
       4.27682035e-03, 1.09370768e-03, 2.79692945e-04, 7.15256418e-05,
       1.82911923e-05, 4.67759124e-06, 1.19619648e-06, 3.05902321e-07])

In [197]: y // p
[1.     0.2557 0.0654 0.0167 0.0043 0.0011 0.0003 0.0001 0.     0.     0.     0.    ]
```
Or you can create a new one, with a different set of print options:

```
In [206]: pg = PrintArray(linewidth=150, formatter={'float': '{:8.4g}'.format})                                                                                     

In [207]: y // pg                                                                                                                                                   
[       1   0.2557   0.0654  0.01672 0.004277 0.001094 0.0002797 7.153e-05 1.829e-05 4.678e-06 1.196e-06 3.059e-07]
```

**Comment by sursu** [comment]
@WarrenWeckesser what you've shown is very instructive. Thank you!

In Mathematica `//` is a way of applying specific functions as an afterthought.
In the case above the function applied is `TableForm`.

But I could do something else: say, I have some numbers and I want to apply the `Log` function and the take the `Norm`. In Mathematica I would do:

```Mathematica
RandomReal[1, {10}] // Log // Norm
```
Which I find to be very elegant, natural and easy to read.

To do the same in one line in numpy we would have to do:

```python
np.linalg.norm(np.log(np.random.uniform(size=10)))
```

Specifically, placing the brackets is somewhat annoying.

It would be really cool (and before seeing your example, thought impossible by me) to have something like:

```python
np.random.uniform(size=10) // np.log // np.linalg.norm
```

I know that `//` is already a reserved `numpy` operator, but certainly something else can be adopted say `/.`.

**Comment by eric-wieser** [comment]
> However, it is a bit impractical to search for it every time I want to just view a matrix.

My comment was that we could consider either building such a feature into numpy, or adding a separate `numpy_pprint` module - I'm certainly not advocating that that reddit post become the only way to use that code!

**Comment by eric-wieser** [comment]
> It would be really cool (and, before seeing your example, thought by me impossible in Python) to have something like:

This seems out of scope for numpy. There are many existing python snippets for functional piping like this - a quick search reveals https://github.com/sspipe/sspipe.

**Comment by eric-wieser** [comment]
>

> I know about this solution:
> 
> ```python
> with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
>     print(A)
> ```
> 
> but, it is a bit cumbersome.

Can't you wrap it in a function?
```
def TableForm(A):
    with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.4f}'.format}, linewidth=100):
        print(A)
```

**Comment by sursu** [comment]
> Can't you wrap it in a function?

I can. But, sometimes I have to tinker too much to make it the output look nice (for instance when the scale of the numbers varies).
I prefer there to be a `numpy` function for that.

**Comment by eric-wieser** [comment]
> I prefer there to be a numpy function for that.

There already is the `array2string` function, which allows you to do the tinkering. What makes your set of tinkered values objectively better than any other set? It doesn't make sense to add a new function for every user who has a different preference. I'm not saying your set of values isn't necessarily better - I'm just saying that you need a fairly convincing argument for why they're better.

Perhaps one answer to that is "it exactly matches Mathematica". I think there'd be scope for a standalone module to help transition mathematica users, but I don't think it belongs in numpy itself.

It might also be that our defaults are just... bad. But again, you need to convince us and other users of that.

**Comment by sursu** [comment]
@eric-wieser I have signaled that there is an issue.

> It doesn't make sense to add a new function for every user who has a different preference.

It also doesn't make sense to adopt something aesthetically displeasing as default.

If you like how this looks:
![image](https://user-images.githubusercontent.com/12001304/66321681-4443d700-e921-11e9-9edc-858f9a31c3fa.png)

or, after tinkering with your `array2string` function:

```python
print(np.array2string(A, suppress_small=True, formatter={'float': '{:0.4f}'.format}))
```
![image](https://user-images.githubusercontent.com/12001304/66321929-9d136f80-e921-11e9-872c-fc7c9b0b84a5.png)

then I cannot convince you that there needs to be a change.

**Comment by eric-wieser** [comment]
> or, after tinkering with your array2string function:

I just copied the settings you suggested in your original comment. You're right though, both my suggestion and your original comment produce totally unreadable output.

> I cannot convince you that there needs to be a change.

I'm not saying I think a change is a bad idea - I think what I'm struggling with is exactly what change you're asking for. Is it:

1. Defaulting to not using the `array` prefix? You already get this with `print(A)`, but your REPL is showing you  `print(repr(A))`, which is quite deliberately more verbose.
2. A brand new syntax for printing, `arr // modifier`? This seems firmly out of scope for numpy, but is something I'd encourage you to explore in a hypothetical `numpy_mathematica` package.
3. A different default of `precision=4, suppress_small=True`? This needs careful discussion, but might not be out of the question.
4. A different default of `linewidth=100`?
5. An entirely new formatting feature that can't be achieved via `array2string` today?

**Comment by Command2017** [comment]
Hey Hey
I just created a little package called numpyprint, which prints numpy arrays nicely in a table. It porvides some options to change the output. I just started with the package and so far it works fine for me. 

https://pypi.org/project/numpyprint/0.1.1/#description

Of course it is not perfect for everything but i think for a short overview it will work ;-) 

What do you think about it ?

**Comment by eric-wieser** [comment]
@Command2017, your PyPI release links to https://github.com/pypa/sampleproject, which looks questionable!

**Comment by Command2017** [comment]
@eric-wieser 

Hey thanks for your replay. I copy and pasted a template and overlooked that url. I just fixed it.
https://pypi.org/project/numpyprint
