### ISSUE TITLE
Lots of build warnings about signed-unsigned comparisons.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#14655]
```
numpy/core/src/umath/simd.inc.src:260:9: note: in expansion of macro ‘IS_BLOCKABLE_BINARY_SCALAR1’
     if (IS_BLOCKABLE_BINARY_SCALAR1(sizeof(@type@), vector_size_bytes)) {
         ^
numpy/core/src/umath/simd.inc.src:87:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      ((abs_ptrdiff(args[2], args[0]) >= (vsize)) || \
```

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mattip** [comment]
What OS/compiler did you use? I don't seem to be able to reproduce this on HEAD.

**Comment by charris** [comment]
IIRC, it was clang on OS X wheels builds... See https://travis-ci.org/MacPython/numpy-wheels/jobs/622320926.

**Comment by rgommers** [comment]
this happens quite often though. maybe we should add `-Werror` on the macOS CI build, just like we do on TravisCI for GCC.

**Comment by mattip** [comment]
> maybe we should add -Werror on the macOS CI build

There still are many warnings with clang on macOS. Someone could try to work through them by running `CC=clang python runtests.py --warn-error` or `CC-clang python setup.py buld --warn-error` which will add `-Werror` to the build steps after configuration (which emits many errors by design)

**Comment by seberg** [comment]
I have some clang-tidy warnings, which I would not mind working through, but none of them point to actual issues really. Things like "switch without default" or "possibly unititialized variable". We can add `default: assert(0);` to silence them. I am not sure about initializing a variable when it is not necessary, though. At least uninitialized variables being read will create valgrind errors...

Not sure if those are (partiall?) the same.
