### ISSUE TITLE
np.ma.masked_where sets .mask to False when there is no masked elements in an array

### ISSUE THREAD

**Issue by guziy** [numpy/numpy#14650]
The problem is that np.ma.masked_where puts a single boolean into the mask field if the condition in masked_where always False... That is a pain, not sure why it is like this... I would expect it to give me a vector of the same shape and size as the input...

Cheers

### Reproducing code example:

```python
In [12]: import numpy as np                                                                                                                                  

In [13]: x = np.arange(10)                                                                                                                                   

In [14]: y = np.ma.masked_where(x > 100, x)                                                                                                                  

In [15]: y.mask                                                                                                                                              
Out[15]: False
```

### Error message:
No error message ..

### Numpy/Python version information:
```
1.17.2 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
> That is a pain, not sure why it is like this... 

The short answer is we probably got the design wrong, and now it's hard to fix because people might be relying on it... There are probably other issues about setting `.mask`  to `np.ma.nomask` causing issues.

**Comment by eric-wieser** [comment]
One workaround would be to expose the `shrink` argument defined here:

https://github.com/numpy/numpy/blob/a8c730bc17ad3479dfba844bd860d85547b0e712/numpy/ma/core.py#L1689-L1705

`np.ma.masked_where(x > 100, x, shrink=False)` would then behave as expected.

**Comment by efiring** [comment]
Where is the pain coming from?  Can you work around it by always using `np.ma.getmaskarray()` when you want to extract the full mask?  That works with array-likes, not just masked arrays.

**Comment by guziy** [comment]
Thanks @efiring and @eric-wieser:

The pain was the necessity to treat .mask property as smth that can be either a scalar or a matrix.. I guess np.ma.getmaskarray would work... 

cheers

**Comment by fengluoqiuwu** [comment]
> Where is the pain coming from?

Indeed, another challenge arises from the various bugs and misunderstandings related to the shrink mask.

>The problem is that np.ma.masked_where puts a single boolean into the mask field if the condition in masked_where always False... That is a pain, not sure why it is like this... I would expect it to give me a vector of the same shape and size as the input...

However, since this behavior isn't classified as a bug, I believe it may be appropriate to close the issue. Thank you for your insights!

**Comment by guziy** [comment]
not a bug, I got the response, thanks to all ))
