### ISSUE TITLE
types compare as not-equal (e.g. np.int32 != np.int32)

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#14667]
From https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=18674
```
>           assert res_type == ex_type
E           AssertionError: assert <class 'numpy.int32'> == <class 'numpy.int32'>
```

I've also seen this for `assert np.uint64 == np.uint64` failing.  Is this behavior intentional?

**Comment by eric-wieser** [comment]
In 1.18, this will fail with the somewhat clearer `AssertionError: assert <class 'numpy.int32'> == <class 'numpy.intc'>`

**Comment by jbrockmendel** [comment]
Thanks, I'll look into this.

**Comment by eric-wieser** [comment]
#10151 is merged, so this can be closed - the error message will be clear.
