### ISSUE TITLE
proposal: in-place shift API for ndarray

### ISSUE THREAD

**Issue by link89** [numpy/numpy#14660]
In real time signal process, it's very common to use a fixed length ndarray as a buffer to store incoming data.
When new data is coming, the oldest data will be shifted out and new one's will be shifted in, and then we can continue to process new data.

I really hope numpy can provide a in-place shift API for this purpose, as for now I have to create new array when new data is coming, which will not only waste memory but also waste time, make it less 'real time'.

It's not like `np.roll`, whose behavior is more like `cyclic shift register`. IMHO, implement in-place`shift` is much easier and cheaper than in-place`roll`. Really hope you can consider this suggestion. Thanks! 

A simple use case like this:
```python
arr = np.arange(10)
new_data = np.zeros(4)
arr.shift(new_data)
# then arr will become [4, 5, 6, 7, 8, 9, 0, 0, 0, 0]
```

**Comment by eric-wieser** [comment]
I assume the function you're looking for is:
```python
def shift(arr, to_append):
    end = len(arr)-len(to_append)
    keep = arr[len(arr)-len(to_append):]
    arr[:end] = arr[len(to_append):]
    arr[end:] = to_append
```

It's not clear to me that this belongs as a method of `np.ndarray`, but it might be useful elsewhere in numpy or scipy.

**Comment by link89** [comment]
That's how I do for now. By saying in-place, we can make use of low level C API like&nbsp; memmove for better performance


 
---Original---

**Comment by eric-wieser** [comment]
`arr[:end] = arr[len(to_append):]` already calls `memmove` under the hood, I don't think the performance gain of putting this in C is significant.

**Comment by link89** [comment]
I see. The style `arr[len(to_append):]` make me think a new array is created. It's good to know the way to `shift` is correct. Thanks for you reply. @eric-wieser
