### ISSUE TITLE
phoronix benchmark scikit-learn endures performance regression because of numpy upgrade

### ISSUE THREAD

**Issue by jim0421** [numpy/numpy#14664]
### how to install and run phoronix on debian/ubuntu:

```shell
wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.8.0_all.deb
sudo apt install gdebi-core
sudo gdebi phoronix-test-suite_7.8.0_all.deb
phoronix-test-suite --version
phoronix-test-suite install scikit-learn-1.0.1
phoronix-test-suite run scikit-learn-1.0.1
```

### Problem description:
During the update of numpy from 1.16.4 to 1.17.2, there is a obvious performance dropdown.
Pls, give me some instruction on the performance regression, thank you.

**Comment by rth** [comment]
As far as I understood that is running benchmarks for scikit-Learn 0.17.1 (released in Feb 2016). I don't this the results are too relevant today.

Also the question is probably too broad for the numpy issue tracker in any case. 

Could you please open an issue at https://github.com/scikit-learn/scikit-learn about it? A better benchmark would probably be https://github.com/jeremiedbb/scikit-learn_benchmarks it would be interesting to see if changing numpy versions has a similar effect.

**Comment by rgommers** [comment]
Agreed, thanks for answering this @rth. Closing.
