### ISSUE TITLE
Support arbitrary dimension in transpose

### ISSUE THREAD

**Issue by EpicWink** [numpy/numpy#14665]
Currently, to transpose an array with unknown dimension, one has to first find out the dimension, then use that to build up the transpose argument.

I propose supporting a new argument format to the `axes` parameter of `transpose` which allows the unspecified dimensions to be filled in order.

One possible syntax is to use the `Ellipsis` (`...`), similar to automatic unspecified shape expansion in slicing (eg `b = a[..., 1]`):
```python
transposed = array.transpose((..., 1))
```
Which would be equivalent to
```python
transposed = array.transpose((*[j for j in range(a.ndim) if j not in (1,)], 1))
```

### Example:

```python
import numpy as np
original = np.array([
    [[7, 2, 8], [1, 9, 2], [1, 8, 4], [3, 1, 3], [5, 6, 0]],
    [[3, 5, 5], [4, 8, 2], [6, 1, 3], [0, 5, 2], [9, 3, 5]],
    [[0, 3, 6], [0, 4, 4], [1, 1, 8], [6, 2, 2], [5, 6, 6]],
    [[3, 5, 1], [2, 2, 3], [5, 9, 6], [0, 2, 0], [4, 8, 4]]])
expected1 = np.array([
    [[7, 1, 1, 3, 5], [3, 4, 6, 0, 9], [0, 0, 1, 6, 5], [3, 2, 5, 0, 4]],
    [[2, 9, 8, 1, 6], [5, 8, 1, 5, 3], [3, 4, 1, 2, 6], [5, 2, 9, 2, 8]],
    [[8, 2, 4, 3, 0], [5, 2, 3, 2, 5], [6, 4, 8, 2, 6], [1, 3, 6, 0, 4]]])
expected2 = np.array([
    [[7, 2, 8], [3, 5, 5], [0, 3, 6], [3, 5, 1]],
    [[1, 9, 2], [4, 8, 2], [0, 4, 4], [2, 2, 3]],
    [[1, 8, 4], [6, 1, 3], [1, 1, 8], [5, 9, 6]],
    [[3, 1, 3], [0, 5, 2], [6, 2, 2], [0, 2, 0]],
    [[5, 6, 0], [9, 3, 5], [5, 6, 6], [4, 8, 4]]])

# Current method
transposed1 = original.transpose((-1, *tuple(range(a.ndim - 1))))
assert np.all(transposed1 == expected1) and transposed1.shape == expected1.shape

transposed2 = original.transpose((*tuple(j for j in range(a.ndim) if j not in (0, 2)), 0, 2))
assert np.all(transposed2 == expected2) and transposed2.shape == expected2.shape

# Proposed syntax
transposed1_v2 =  original.transpose((-1, ...))
assert np.all(transposed1_v2 == expected1) and transposed1_v2.shape == expected1.shape

transposed2_v2 =  original.transpose((..., 0, 2))
assert np.all(transposed2_v2 == expected2) and transposed2_v2.shape == expected2.shape
```

### Environment:
* NumPy: 1.17.1
* Python: 3.7.3 (default, Aug 20 2019, 17:04:43) [GCC 8.3.0]

**Comment by seberg** [comment]
Just to note, but you are aware of `np.moveaxis` and `np.swapaxis`, which seem to me like they cover at least part of this in a pretty good way as well?

**Comment by EpicWink** [comment]
> Just to note, but you are aware of `np.moveaxis` and `np.swapaxis`, which seem to me like they cover at least part of this in a pretty good way as well?

I wasn't aware of them, thanks for enlightening. For my purposes [`np.moveaxis`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.moveaxis.html) is all I need, however the original proposal is more general

**Comment by rossbar** [comment]
This didn't generate a lot of discussion here, so I'm going to close it. If you are interested in pursuing this feature request, please feel free to take it to the mailing list!
