### ISSUE TITLE
Is 'numpy.all()' defined to be vacuously true for empty arrays?

### ISSUE THREAD

**Issue by miccoli** [numpy/numpy#14679]
Recently I was surprised by the truth value of `ndarray.all()` and `ndarray.any()` of empty arrays.

### Reproducing code example:

```python
>>> import numpy as np
>>> np.array([]).all()
True
>>> np.array([]).any()
False
```
I suppose that the rationale is:

- **all()**: *test whether all array elements along a given axis evaluate to True*. This is [vacuously true](https://en.wikipedia.org/wiki/Vacuous_truth).

- **any()**: *test whether any array element along a given axis evaluates to True*. This is the converse of the above: in an empty array there is no truish value, so `.any()` is `False`

If this is the intended behaviour, maybe a line in the docs could be helpful.

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.17.2 3.7.3 (default, May  7 2019, 10:18:31) 
[Clang 10.0.1 (clang-1001.0.46.4)]
```

**Comment by eric-wieser** [comment]
This matches the behavior of the python builtins:
```
>>> all([])
True
>>> any([])
False
```
Can you suggest a doc change that would make this less surprising to you?

**Comment by miccoli** [comment]
@eric-wieser Actually I reviewed my code, and I noticed that the surprise effect was very beneficial to me, because it helped me to spot a logical error I made. BTW, after thinking about this, I found that the present definition is not only mathematically consistent but also the only sensible one.

Since there is no doubt that this is the correct behaviour, I will close this issue.

If you think that it could be useful to others, I can open a doc-only pull request to add a brief note, (on the lines of the python docs on the [builtins](https://docs.python.org/3/library/functions.html#all)) to explicitly remind numpy users of this feature. Please let me know your opinion, and thank you for your precious time.


(Next time I will think twice before hitting the create-new-feature button; there is already enough entropy in the universe without my help...)
