### ISSUE TITLE
Doc improvement suggestions: list () and tolist () are very different.

### ISSUE THREAD

**Issue by toropippi** [numpy/numpy#14683]
numpy 1.15.4
python 3.7.1

I refer to this doc but I spent a lot of time discovering the following.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html?highlight=tolist#numpy.ndarray.tolist

```python
import numpy as np

npA=np.uint32([1,2,3])

listA=list(npA)
print(type(listA)) # <class 'list'>
print(type(listA[0])) # <class 'numpy.uint32'>

listA2 = npA.tolist()
print(type(listA2)) # <class 'list'>
print(type(listA2[0])) # <class 'int'>
```

I wanted to calculate numbers greater than 32bit integers, but I should have used tolist() only.

**Comment by mattip** [comment]
What would you suggest to make `tolist` more discoverable?

**Comment by toropippi** [comment]
I hope that there is a mutual link between "https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html?highlight=tolist#numpy.ndarray.tolist" and "https://docs.python.org/3/library/stdtypes.html#list".

**Comment by eric-wieser** [comment]
Updating these docs would probably do the trick:

> For a 1D array, a.tolist() is almost the same as list(a):
> ```
> >>>
> >>> a = np.array([1, 2])
> >>> list(a)
> [1, 2]
> >>> a.tolist()
> [1, 2]
> ```

We should draw attention to the fact that one list contains numpy scalars, while the other contains python scalars
