### ISSUE TITLE
Unexpected behaviour of np.finfo with None

### ISSUE THREAD

**Issue by juampamuc** [numpy/numpy#14684]
I am using numpy.iinfo and np.finfo to test whether a given type or value is corresponds to an integer or a float. There is a weird behaviour when dealing with **None**.

The following fails, as expected:

     import numpy as np
     np.iinfo(None)

Nevertheless

     import numpy as np
     np.finfo(None)

does not, as I would expect. Is that a bug?
IMHO when type(None) returns NoneType, then np.finfo should fail as np.iinfo does.

**Comment by seberg** [comment]
`None` is often/typically interpreted as `Float64`. See: `np.dtype(None)`. It is useful for defaults. In this case it probably could be removed.
