### ISSUE TITLE
BUG: Fix np.einsum errors on Power9 Linux and z/Linux.

### ISSUE THREAD

**Issue by jwoehr** [numpy/numpy#14692]
An array index fails on Power9 Linux and z/Linux.

PR follows this issue, but not sure that x86 will be happy with the proposed fix

### Reproducing code example:

```
(qdev_venv) [linux1@jwoehr1 Qiskit]$ python
Python 3.6.8 (default, Jun 11 2019, 14:52:20) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> tensor = np.random.rand(10, 10, 10, 10)
>>> np.einsum('ijij->', tensor)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in einsum
  File "/home/linux1/work/Qiskit/qdev_venv/lib64/python3.6/site-packages/numpy/core/einsumfunc.py", line 1356, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: dimensions in operand 0 for collapsing index 'þ' don't match (-1419377904 != 10)
>>> 
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in einsum
  File "/home/linux1/work/Qiskit/qdev_venv/lib64/python3.6/site-packages/numpy/core/einsumfunc.py", line 1356, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: dimensions in operand 0 for collapsing index 'þ' don't match (-1419377904 != 10)
```
### Numpy/Python version information:

1.17.2 3.6.8 (default, Jun 11 2019, 14:52:20) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by seberg** [comment]
Thanks for looking at it. The Poer9 part is the tricky one, CI should tell us if there are issues on platforms with signed char. xref gh-12689, which is probably the identical issue, so if you find a fix we can close that as well :).

**Comment by jwoehr** [comment]
@seberg  I'll bet I found the wrong fix :(

There will probably have to be a platform test there, which is not what I coded ...

**Comment by seberg** [comment]
I am not sure about this, but just out of principle, shouldn't it work to type every single usage of the chars correctly? I am wondering if clang-tidy might already tell me about half the issues, should check.

**Comment by jwoehr** [comment]
Yes,  gh-12689 is the same issue.

Now the question is "Did what I coded break `einsum` on x86 platforms?"

**Comment by jwoehr** [comment]
When the tests complete, I will be most appreciative of any guidance you can offer on this issue.
I am not a `numpy` guru, I am contributing to IBM Qiskit.
I just installed Qiskit on z/Linux and found this.

**Comment by seberg** [comment]
I don't really know much about this, pretty certainly not more than discussed in the other issue. But I wonder if we should change the function signature of `parse_operand_subscripts` to use `signed char` and see where it goes from there?

**Comment by jwoehr** [comment]
Thank you for promising suggestion. I will work on it tomorrow.

**Comment by jwoehr** [comment]
Spent most of today getting later version of CMake to build so that I could build LLVM to get `clang-tidy` :) Building LLVM now ... I guess this exploration will take a few days  ...

**Comment by jwoehr** [comment]
Okay, I've stopped playing with tools and am looking at the code now. I've just learned what Einstein summation is :)

**Comment by jwoehr** [comment]
Hot on the track but my connection to z/Linux just went down :) more tomorrow.

**Comment by jwoehr** [comment]
This is puzzle wrapped in an enigma wrapped in a mystery :)

**Comment by jwoehr** [comment]
> I don't really know much about this, pretty certainly not more than discussed in the other issue. But I wonder if we should change the function signature of `parse_operand_subscripts` to use `signed char` and see where it goes from there?

@seberg If I understand your suggestion correctly, you mean a diff to `master` like this:
```
--- numpy/core/src/multiarray/einsum.c.src	2019-10-18 13:59:42.905439337 -0600
+++ /home/jax/tmp/einsum.c.src	2019-10-18 13:59:32.601640248 -0600
@@ -1791,7 +1791,7 @@
  */
 
 static int
-parse_operand_subscripts(char *subscripts, int length,
+parse_operand_subscripts(signed char *subscripts, int length,
                          int ndim, int iop, char *op_labels,
                          char *label_counts, int *min_label, int *max_label)
 {
@@ -2562,7 +2562,7 @@
             return NULL;
         }
 
-        if (parse_operand_subscripts(subscripts, length,
+        if (parse_operand_subscripts((signed char *)subscripts, length,
                         PyArray_NDIM(op_in[iop]),
                         iop, op_labels[iop], label_counts,
                         &min_label, &max_label) < 0) {
```

If that is the case, this seems to work on x86 and still causes the problem on power9 and s390x.

**Comment by seberg** [comment]
Dunno, all of my things were just thoughts/hypothesizing, I do not know these things well enough to be certain about anything. Hope you can make some progress, but if not maybe we have to see if we can get such a machine at some point.

**Comment by jwoehr** [comment]
Thanks, @seberg , I will continue to work on it.

I try the "magic solutions" first, and if they do not work, I start actually studying the code :)

**Comment by charris** [comment]
I know that it would run on machines with unsigned characters after we fixed things before,  so possibly this problem is fairly newly introduced. See original at #2398. I suspect #11095 might be related and it looks like @mattip has been looking in some of the same places.

**Comment by jwoehr** [comment]
Thank you @charris.

I will check out those issues.

**Comment by mattip** [comment]
I can confirm there is a problem on the Power9 ppc64le machine gcc135 from the [gcc build farm](https://cfarm.tetaneutral.net/machines/list) which uses gcc 4.8.5, but this code does not error on x86:

```
>>> import numpy as np
>>> tensor = np.random.rand(10, 10, 10, 10)
>>> np.einsum('ijij->', tensor)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in einsum
  File "/home/mattip/numpy/build/testenv/lib64/python3.6/site-packages/numpy/core/einsumfunc.py", line 1356, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: dimensions in operand 0 for collapsing index 'þ' don't match (0 != 10)
```

Two problems with that error: it should not appear, and the index letter seems random. What is 'þ' ?

There are a number of warnings in the
[build.log](https://github.com/numpy/numpy/files/3747014/build.log)
) when using `-Wall -std=c99`, but none of them seem related to this issue.

**Comment by jwoehr** [comment]
sizes.c:
======
```
#include <stdio.h>
#include <limits.h>
int main (int argc, char *argv[]) {
        printf("unsigned char %ld\n", sizeof(unsigned char));
        printf("signed char %ld\n", sizeof(signed char));
        printf("int %ld\n", sizeof(int));
        printf("unsigned int %ld\n", sizeof(unsigned int));
        printf("long %ld\n", sizeof(long));
        printf("unsigned long %ld\n", sizeof(unsigned long));
        printf("double %ld\n", sizeof(double));
        printf("float %ld\n", sizeof(float));
        printf("CHAR_BIT == %d\n", CHAR_BIT);
        printf("SCHAR_MIN == %d\n", SCHAR_MIN);
        printf("SCHAR_MAX == %d\n", SCHAR_MAX);
        printf("UCHAR_MAX == %d\n", UCHAR_MAX);
        printf("CHAR_MIN == %d\n", CHAR_MIN);
        printf("CHAR_MAX == %d\n", CHAR_MAX);
        return 0;
}
```
Output from the 3 platforms we are discussing (note the values for `CHAR_MIN`  and `CHAR_MAX`):

sizes_x86_64_ubuntu.txt:
====================
```
unsigned char 1
signed char 1
int 4
unsigned int 4
long 8
unsigned long 8
double 8
float 4
CHAR_BIT == 8
SCHAR_MIN == -128
SCHAR_MAX == 127
UCHAR_MAX == 255
CHAR_MIN == -128
CHAR_MAX == 127
```

sizes_p9_rhel.txt:
==============
```
unsigned char 1
signed char 1
int 4
unsigned int 4
long 8
unsigned long 8
double 8
float 4
CHAR_BIT == 8
SCHAR_MIN == -128
SCHAR_MAX == 127
UCHAR_MAX == 255
CHAR_MIN == 0
CHAR_MAX == 255
```
sizes_s390x_rhel.txt:
=================
```
unsigned char 1
signed char 1
int 4
unsigned int 4
long 8
unsigned long 8
double 8
float 4
CHAR_BIT == 8
SCHAR_MIN == -128
SCHAR_MAX == 127
UCHAR_MAX == 255
CHAR_MIN == 0
CHAR_MAX == 255
```
BTW @mattip `þ` is the character "thorn" from Anglo-Saxon and Icelandic!

**Comment by mattip** [comment]
got it, [this line](https://github.com/numpy/numpy/blob/v1.17.3/numpy/core/src/multiarray/einsum.c.src#L1879) should be `int label = (signed char)op_labels[idim];`, otherwise `label < 0` will never be true for systems like ppc where `char` is `unsigned char`

**Comment by mattip** [comment]
now to write the test. What would the equivalent non-einsum call to `np.einsum('ijij->', a) return?

**Comment by WarrenWeckesser** [comment]
> What would the equivalent non-einsum call to `np.einsum('ijij->', a) return?

You could use a couple calls to `trace`:

```
In [69]: tensor = np.random.rand(10, 10, 10, 10)                                                                                               

In [70]: np.einsum('ijij->', tensor)                                                                                                           
Out[70]: 47.46929252478759

In [71]: np.trace(tensor, axis1=0, axis2=2).trace()                                                                                            
Out[71]: 47.46929252478759
```

**Comment by jwoehr** [comment]
> got it, [this line](https://github.com/numpy/numpy/blob/v1.17.3/numpy/core/src/multiarray/einsum.c.src#L1879) should be `int label = (signed char)op_labels[idim];`, otherwise `label < 0` will never be true for systems like ppc where `char` is `unsigned char`

@mattip I took `einsum.c.src` fresh from master and made the one change you noted.

Now it does not throw an error on power9 RHEL nor on s390x RHEL.

It also seems to behave on x86, though I thought I had it fixed before and it failed the build conveyor.

We will see if with the new change it passes the build conveyor and if so I will look at identifying a proper test case.

Thank you for your help!

**Comment by jwoehr** [comment]
> now to write the test. What would the equivalent non-einsum call to `np.einsum('ijij->', a) return?

I have no idea :) Makes it hard to write the test.

**Comment by jwoehr** [comment]
The problem is that this code was working fine on x86_64 and will only fail on other architectures which this project does not test on, so it's hard to define a regression test.

**Comment by mattip** [comment]
We have a ppc64le machine in the travis test CI matrix. The problem then is that we had no test for the case of repeating collapsing dimensions. 

@WarrenWeckesser suggested a path to compare the einsum answer to a non-einsum calculation above.
