### ISSUE TITLE
 No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by 02yogesh16** [numpy/numpy#14694]
Hello All,
I am trying to use numpy to plot via matplotlib. I am using a C-API for that. While ploting I am getting the following numpy error; 
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

I am attaching two screen shots for details;

Traceback (most recent call last):
  File "C:\Python374\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "C:\Python374\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Python374\lib\site-packages\numpy\core\overrides.py", line 9, in <module>
    from numpy.core._multiarray_umath import add_docstring, ndarray
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python374\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Python374\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\Yogesh Kumar\Desktop\Code\C++\Jerk Navigation\Debug\Jerk Navigation.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

Traceback (most recent call last):
  File "C:\Python374\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "C:\Python374\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Python374\lib\site-packages\numpy\core\overrides.py", line 9, in <module>
    from numpy.core._multiarray_umath import add_docstring, ndarray
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python374\lib\site-packages\matplotlib\__init__.py", line 138, in <module>
    from . import cbook, rcsetup
  File "C:\Python374\lib\site-packages\matplotlib\cbook\__init__.py", line 31, in <module>
    import numpy as np
  File "C:\Python374\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Python374\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\Yogesh Kumar\Desktop\Code\C++\Jerk Navigation\Debug\Jerk Navigation.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

I tried with uninstalling and reinstalling numpy version 1.4.1, 1.6.0 and 1.7.- but none of them are working. I am using Windows 10 and Visual studio 17, and Python 3.7.4.

**Comment by 02yogesh16** [comment]
For more information, I am using this package for ploting in Visual Studio 17.

https://github.com/lava/matplotlib-cpp

**Comment by mattip** [comment]
Do you have a `python.exe` under `C:\Python374`? If so, can you run it and then `import numpy` from there? If so, then something is wrong with `C:\Users\Yogesh Kumar\Desktop\Code\C++\Jerk Navigation\Debug\Jerk Navigation.exe`. The name suggests it is using a debug build of python which would require a debug build of numpy, either that or perhaps it provides a different version of python?

**Comment by 02yogesh16** [comment]
Thanks mattip for your comment.

Yes, python.exe exists there and I am able to import numpy using:  python import numpy. But when I am trying to import numpy from debug version of python then I am getting the exact same error; i.e.,  python_d import numpy is giving the same error. I think that the issue is with the debug version of either python or numpy, as you also have pointed out. I tried importing debug version of numpy but that is also not working.

**Comment by mattip** [comment]
As I pointed out elsewhere, you probably do not want to invest in recompiling all the packages you use. You may be better off using a "release version with debugging information" and reducing optimization so you can debug your part of the program but still use common wheel binaries

**Comment by 02yogesh16** [comment]
Thanks, release version works.
