### ISSUE TITLE
DOC: add sample Notebook tutorials for beginners

### ISSUE THREAD

**Issue by r0cketr1kky** [numpy/numpy#14690]
As beginners tend to use this library as the first step towards coding Machine Learning algorithms, there is a necessity to bring in quality tutorials for them so that they have a strong foundation of mathematics on tensor size matching, vectors etc. 

Beginners can be from any background so having a notebook that explains the mathematics behind numpy would be beneficial for the community to refer back on the basics and it could also act as a refresher of concepts too.

**Comment by mattip** [comment]
Are there any particular examples you find compelling? We are actively trying to work on this now, and any input would be welcome. You could start by submitting your [user story](https://github.com/numpy/numpy.org/issues/42), or commenting on the content of PR gh-14546, which can be viewed here: [basic tutorial](https://9619-908607-gh.circle-artifacts.com/0/home/circleci/repo/doc/build/html/user/absolute-beginners-outline.html)

**Comment by rubitry** [comment]
i have made a notebook for beginners, so if you want you could refer that.  [https://github.com/rubitry/python-notes/tree/master/NumPy%20for%20Beginners](numpy-notebook)

**Comment by pdebuyl** [comment]
@mattip the user disappeard (is now a ghost). I propose to close, especially given the fact that the tutorial in #14546 has been merged.

**Comment by WarrenWeckesser** [comment]
@pdebuyl, agreed, closing.
