### ISSUE TITLE
Build python3.8 wheels for latest releases

### ISSUE THREAD

**Issue by bsipocz** [numpy/numpy#14698]
Now that Python 3.8.0 is out, I foresee that more and more downstream packages would like to test against it. To help reduce their CI build time, it would be extremely nice to have wheels available on PyPI for at least the latest numpy release.

**Comment by bsipocz** [comment]
It seems that some kind of numpy 1.18.dev is included in the travis 3.8-dev VM, but nevertheless it would be better for downstream to have a control over to test with a released version rather than a not clearly defined developer version of numpy.

**Comment by charris** [comment]
We build pre-release wheels, they can be found at https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com. They are usually a cron job, which only builds for manylinux1 and osx but I ping the build now and then so there are also windows versions. Scipy and several other projects test against them, so you can see how it is done.

I plan to release 1.17.3 soon with python3.8 wheels. Should be easy, but multibuild needs updating to do that with previous releases and something might break. You may want to look into that for your own wheels builds at some point.

**Comment by bsipocz** [comment]
Thanks for the update. It's perfectly all right for us to wait for 1.17.3. 
(Looking into the wheel building machinery is not something I want to normally do, but something I have to 😉 )

**Comment by charris** [comment]
We just got it working last week, the current wheels were built against 3.8.0rc1, but should be good. Will update as soon as we figure out why the lastest NumPy merge broke the tests :)

**Comment by charris** [comment]
Just to update, I built wheels for 1.17.3 yesterday, but ran into an issue on windows which is being worked on (https://github.com/matthew-brett/multibuild/pull/271). I will finish the build and upload soon after that is fixed.

**Comment by bsipocz** [comment]
The 1.17.3 wheel on the travis 3.8-dev setup works as expected for astropy CI. Thank you @charris!

**Comment by charris** [comment]
Thanks for the feedback. Closing now.
