### ISSUE TITLE
Numpy package installed for Ubuntu 14.04 doesn't work on Ubuntu 16.04(For Python 3 Only)

### ISSUE THREAD

**Issue by dibya001** [numpy/numpy#14706]
installed numpy on ubuntu 14.04 docker image for python 3.4. Numpy version == 1.16.4
While using that numpy package on Ubuntu 16.04, getting import errors
 from numpy.core._multiarray_umath import (
ImportError: No module named 'numpy.core._multiarray_umath

**Comment by mattip** [comment]
That is expected. The wheels marked as manylinux have gone through a process to make sure any needed support libraries are supplied by the wheel. If you really need this workflow, you should investigate the [multibuild](https://github.com/matthew-brett/multibuild/) or [cibuildwheel](https://github.com/joerick/cibuildwheel). The basic idea is to build via a manylinux docker image which sets a baseline linux system to be supported, then to fixup the wheel with auditwheel to make it truly portable.

**Comment by mattip** [comment]
closing. @dibya001 if there is more that we can reasonably do to support this workflow, please reopen with more comments/suggestions.
