### ISSUE TITLE
Code-freeze and deprecate numpy.lib.financial

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#14712]
[NEP 32](https://numpy.org/neps/nep-0032-remove-financial-functions.html) has been accepted.  The implementation plan for the NEP says

* Create a new Python package, numpy_financial, to be maintained in the top-level NumPy github organization. This repository will contain the definitions and unit tests for the financial functions. The package will be added to PyPI so it can be installed with pip.
* Deprecate the financial functions in the numpy namespace, beginning in NumPy version 1.18. Remove the financial functions from NumPy version 1.20.

This is the issue to track that implementation.  We will code-freeze the financial functions in NumPy, and add deprecation warnings for NumPy 1.18.

The web page for the replacement is https://numpy.org/numpy-financial/

**Comment by mattip** [comment]
Closing, the numpy/numpy-financial package is pip-installable, and DeprecationWarnings have been added. If I am mistaken please reopen with new actionable steps. Thanks @WarrenWeckesser for implementing this.
