### ISSUE TITLE
Adding link to rendered docs artifacts as a github status link

### ISSUE THREAD

**Issue by bsipocz** [numpy/numpy#14724]
E.g. using the [Giles](https://github.com/Cadair/giles)/[Baldrick](https://github.com/OpenAstronomy/Baldrick) bot of @Cadair, it's super nice to share an easily accessible link to the circleCI build docs artifacts as part of the PR checks.

<img width="679" alt="Screen Shot 2019-10-15 at 17 52 51" src="https://user-images.githubusercontent.com/6788290/66879782-a8474a80-ef74-11e9-8c72-63a5ced8cb34.png">

**Comment by seberg** [comment]
That is really cool! It is pretty sad we have these nice doc builds, but they are so tricky to get (even if you can infer a URL in principle).

**Comment by bsipocz** [comment]
Well, in astropy the "Details" link above points nicely to the rendered `index.html`, e.g. https://46728-2081289-gh.circle-artifacts.com/0/home/circleci/project/docs/_build/html/index.html

**Comment by rgommers** [comment]
About to get this fixed in gh-15005

**Comment by rossbar** [comment]
This was closed by #16337 which superceded #15005
