### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by TheJam282** [numpy/numpy#14741]
I am getting the following import error "Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory. "

I have read the instructions if it has given me to troubleshoot but still not getting it to work. Nothing is connected to git.   
I do have Sense Hat imported to the code but not sure whether that makes a difference

**Comment by mattip** [comment]
Are you by chance on raspberrypi? You might be interested in these other issues that fixed that problem, you can see them by searching the [issues for lib77blas](https://github.com/numpy/numpy/issues?utf8=%E2%9C%93&q=is%3Aissue+libf77blas). If not, please include
- the entire original error message
- the output of sys.version
- telling us where and how you got numpy installed

**Comment by mattip** [comment]
Closing. @TheJam282 if there is more information on this problem, or if the suggested solution does not help you, please reopen with the requested information
