### ISSUE TITLE
ENH: fromarrays should only require arrays to have the same shape prefix

### ISSUE THREAD

**Issue by flying-sheep** [numpy/numpy#14748]
### Reproducing code example:

```python
import numpy as np
np.core.records.fromarrays([
    np.array([1,2,3]),
    np.array(['x','y','z']),
    np.array([[1,2], [3,4], [5,6]]),
], names='a,b,c')
```

### Error message:

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-378bebb9b79e> in <module>
      3     np.array(['x','y','z']),
      4     np.array([[1,2], [3,4], [5,6]]),
----> 5 ], names='a,b,c')

/usr/lib/python3.7/site-packages/numpy/core/records.py in fromarrays(arrayList, dtype, shape, formats, names, titles, aligned, byteorder)
    637         testshape = obj.shape[:obj.ndim - nn]
    638         if testshape != shape:
--> 639             raise ValueError("array-shape mismatch in array %d" % k)
    640 
    641     _array = recarray(shape, descr)

ValueError: array-shape mismatch in array 2
```

### Numpy/Python version information:

1.17.2, 3.74

**Comment by eric-wieser** [comment]
Does this still raise if you change the length of the array to 2 instead of 3?

If not, then I think you're suggestion conflicts with broadcasting, and it's too late to change it.

**Comment by flying-sheep** [comment]
Still raises if I add a `.T` after the 2D array.

**Comment by mattip** [comment]
The dtype discovery code does not take subarrays into consideration. You need to pass in a dtype for this to work:

``` python
import numpy as np
a = np.arange(3)
b = np.array(['x','y','z'])
c = np.array([[1,2], [3,4], [5,6]])
dt = np.dtype([('x', '<i8'), ('y', '<U1'), ('z', '<i8', (2,))])
# or dt = np.dtype({'names':['x', 'y', 'z'], 'formats':['i8', 'U1', ('i8', 2)]})
np.core.records.fromarrays([a, b, c], dtype=dt)
rec.array([(0, 'x', [1, 2]), (1, 'y', [3, 4]), (2, 'z', [5, 6])],
          dtype=[('x', '<i8'), ('y', '<U1'), ('z', '<i8', (2,))])
```

We might consider a PR to enhance the `fromarrays` function. I think this is a case where hypothesis might be able to generate pathological sequences for conversion. But on the other hand I don't know whether this is a commonly requested feature. Maybe we should document the shortcomings of the current code in the docstring and mark this as a documentation issue. Is this common in your workflow?

**Comment by crkurdelak** [comment]
This issue hasn't been touched in 4 years, so I propose we close it. It could be reopened if anyone has interest in adding to the documentation like mattip suggested.
