### ISSUE TITLE
Error converting to datetime64 from int on Windows

### ISSUE THREAD

**Issue by olegtarasov** [numpy/numpy#14749]
### Reproducing code example:

```python
from numpy import datetime64

date = datetime64(datetime.utcnow())
print(date)
date2 = datetime64(int(date.astype(int)), "us")
print(date2)
```
### Expected:

Printed values are identical:

```
2019-10-21T09:37:07.506524
2019-10-21T09:37:07.506524
```

### Actual (Windows only):

Code above works fine on MacOs under Python 3.7.3 in Anaconda.

I get this result under Windows:

```
2019-10-21T09:37:07.506524
1970-01-01T00:30:34.815836
```

Dates are not equal.

### Numpy/Python version information:

1.17.1 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]

**Comment by olegtarasov** [comment]
Ok, I found a workaround:

```python
date2 = datetime64(int(date.astype(np.int64)), "us")
print(date2)
```

Seems to give the desired result under Windows. But still it's unexpected to get different results under different OS'es when using plain `int`.

**Comment by mattip** [comment]
`int` becomes `np.int_` which can changed dependent on platform. Closing. Please reopen if more action is needed.
