### ISSUE TITLE
DOC: scipy.interpolate.RectSphereBivariateSpline

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#14759]
A couple of doc issues here:

1. v has to be a "1-D array of latitude coordinates in strictly ascending order. Coordinates must be given in radians and lie within the interval (0, pi)".   But actually, a v in this range is a colatitude, not a latitude (latitudes go from -pi/2 to pi/2).  

2. Also, it should be emphasized that (0, pi) really does mean an open interval, and 0 and pi are not allowed for v.  If you put them in, the error message is completely cryptic.

**Comment by Kai-Striega** [comment]
@rgommers I think that this was meant to be a SciPy issue, are you able to transfer it?

**Comment by rgommers** [comment]
No, that only works between different repos inside a single GitHub org.

So closing. @keithbriggs can you report this on the SciPy issue tracker please?
