### ISSUE TITLE
Sublime Text build system from conda environment: Numpy "DLL load failed: The specified module could not be found"

### ISSUE THREAD

**Issue by sjoerdloenen** [numpy/numpy#14755]
When using the numpy package in a python script ran within sublime text I get the error "DLL load failed: The specified module could not be found".

I already tried reinstalling numpy using conda, but to no avail.

I established different "build systems" within sublime text to run the python code (extremely basic test code, see below). The build systems use python executable files: "C:/Users/Sjoerd/Miniconda3/envs/DevPython37/python", where DevPython37 is my user defined name of the conda environment related to the python version I want to use. I have one environment with Python 3.7 and one with 2.7. The error occurs with both environments.

When starting sublime text from the anaconda prompt this error does not occur. 
Also when I start jupyter notebook from the anaconda prompt and use numpy in the jupyter notebook, numpy also works fine.
However, I would like it to work when I start up sublime text from any location and not just when using the terminal. I hope someone is able to help me resolve this issue. 

There is some (to me seemingly) similar issue relating to PyCharm (https://github.com/ContinuumIO/anaconda-issues/issues/1508#issuecomment-446339859). This is how I figured out it works when opening sublime text from the terminal.

### System specifications:

I use Windows 10 on a 64-bit machine.
Python version: error occurs with both the Python3.7 (with numpy 1.16.5) build system and the Python2.7 (with numpy 1.16.5) build system.
Conda version 4.7.12 (installed through Miniconda3)

### Reproducing code example:
Test code that raises the numpy error
```
import time
import numpy as np

for i in range(5):
	print ("hello world...")
	time.sleep(1)

A = np.array([1,2,3])
print A
```
(NOTE: with python3.7 the syntax of print is adapted to print(A))

The code to establish the build system (".sublime-build" file, located at "C:\Users\Sjoerd\AppData\Roaming\Sublime Text 3\Packages\User"). python2.7 case is similar.
```
{
    "cmd": ["C:/Users/Sjoerd/Miniconda3/envs/DevPython37/python", "-u", "$file"],
    "selector": "source.python",
    "file_regex": "^\\s*File \"(...*?)\", line ([0-9]*)"
}
```

### Error message:
ERROR MESSAGE WHEN USING PYTHON27 BUILD SYSTEM: 
```
Traceback (most recent call last):
  File "C:\Users\Sjoerd\Documents\Python_Projects\Hello_world_test.py", line 2, in <module>
    import numpy as np
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython27\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython27\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
```

ERROR MESSAGE WHEN USING PYTHON37 BUILD SYSTEM: 
```
Traceback (most recent call last):
  File "C:\Users\Sjoerd\Documents\Python_Projects\Hello_world_test.py", line 3, in <module>
    import numpy as np
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython37\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython37\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by mattip** [comment]
The problem with 3.7 seems like anaconda is not being properly initialized. I think you need to activate the environment before calling it. `_mklinit` does not come from vanilla numpy.

Since you did not include the actual ImportError on 2.7 it is difficult to determine what is going on.

**Comment by sjoerdloenen** [comment]
Thanks for the response.

Using the Anaconda Prompt, I have activated the anaconda environment to which the python 3.7 build system points before running the python script in sublime text. This still raises the same error.

Could you explain what you mean by `_mklinit` does not come from vanilla numpy. What means `_mklinit` and what is vanilla numpy?

Here is the complete message from the output panel when running with Python2.7. It gives an empty ImportError.
```
Traceback (most recent call last):
  File "C:\Users\Sjoerd\Documents\Python_Projects\Hello_world_test.py", line 3, in <module>
    import numpy as np
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython27\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\Sjoerd\Miniconda3\envs\DevPython27\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\Sjoerd\Miniconda3\envs\DevPython27\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

[Finished in 0.1s with exit code 1]
[cmd: ['C:/Users/Sjoerd/Miniconda3/envs/DevPython27/python', '-u', 'C:\\Users\\Sjoerd\\Documents\\Python_Projects\\Hello_world_test.py']]
[dir: C:\Users\Sjoerd\Documents\Python_Projects]
[path: C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Users\Sjoerd\AppData\Local\Microsoft\WindowsApps;]
```

**Comment by mattip** [comment]
> What means `_mklinit` and what is vanilla numpy?

Anaconda builds numpy with the Intel MKL library. "Vanilla numpy" is what you get from the numpy project (this repo) and does not ship with MKL. You might have more luck working through this issue on the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues)

**Comment by mattip** [comment]
@sjoerdloenen did you work out what is going on? Did you open an issue with Anaconda?

**Comment by sjoerdloenen** [comment]
@mattip Dear Mattip, thanks for coming back to me, I appreciate it. 
I was away for a while, but have opened an issue on the Anaconda issue tracker: https://github.com/ContinuumIO/anaconda-issues/issues/11504. Let's hope someone will be able to resolve the issue. 
I will certainly update you when it has been resolved, but up till now I have not yet found a solution.

**Comment by sjoerdloenen** [comment]
@mattip Up till now I have not received a solution. 
The bottom line probably is that I need to activate the conda (python) environment before running the interpreter such that the necessary entries are added to the PATH and the DLL's can be successfully loaded.
I have not found anyone who knows how to do this via sublime text, but jjhelmus (https://github.com/ContinuumIO/anaconda-issues/issues/11504#issuecomment-564077928) knows how to do this through the command prompt. 
So maybe the solution is writing a batch file, which upon running activates the environment and opens sublime text through that environment. In that case I think it should work.

**Comment by Olivezer** [comment]
Hello, after struggling a lot and almost giving up, I found the solution !!!
Step 1. Follow these [instructions.](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/sublime/l)
Step 2. Press Ctrl+Shift+P and select Conda:Activate Environment.
Step 3. Import numpy and cry from happiness.
Happy coding !

**Comment by mdorovkov** [comment]
I had exactly the same problem with Sublime Text 3 and I've found an easy solution:

I added to Path on Windows 10 the following:
C:\Users\Your_User_Name\Anaconda3\Library\bin

I found the solution at the following stackoverflow discussion (the first answer) even though it was not specificcaly about sublime text:
https://stackoverflow.com/questions/54974444/pydev-eclipse-not-loading-mklinit-when-run-from-a-conda-environment

**Comment by mattip** [comment]
That solution is fine for now, but what happens in six months when you delete that anaconda installation, install a newer version to a different path, and forget you added anaconda to the path?

**Comment by mattip** [comment]
This also complicates the use of multiple python environments on one machine. Anaconda's workflow is to activate/deactivate environments as needed, changing the system path permanently will, sooner or later, harm that workflow.

**Comment by sjoerdloenen** [comment]
> Hello, after struggling a lot and almost giving up, I found the solution !!!
> Step 1. Follow these [instructions.](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/sublime/l)
> Step 2. Press Ctrl+Shift+P and select Conda:Activate Environment.
> Step 3. Import numpy and cry from happiness.
> Happy coding !

@Olivezer, First of all, thanks for helping! 
I tried to follow your suggestion, but when hitting your link I get a 404 - page not found error. Could you check whether the page you referred to is still active or re-upload the link to the existing page.
Lots of thanks in advance.

**Comment by Olivezer** [comment]
> @Olivezer, First of all, thanks for helping!
> I tried to follow your suggestion, but when hitting your link I get a 404 - page not found error. Could you check whether the page you referred to is still active or re-upload the link to the existing page.
> Lots of thanks in advance.

Hi @sjoerdloenen ,  indeed, I accidentally added an extra character to the link. It is now fixed. Tell me if that solution works for you. If that doesn't work, check that you're actually building the system with Conda (and not python or conda with a lowercase 'c').
Best regards

**Comment by sjoerdloenen** [comment]
> Hello, after struggling a lot and almost giving up, I found the solution !!!
> Step 1. Follow these [instructions.](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/sublime/)
> Step 2. Press Ctrl+Shift+P and select Conda:Activate Environment.
> Step 3. Import numpy and cry from happiness.
> Happy coding !

Currently crying from happiness. Thanks a lot Olivezer, this worked for me:). To me this seems like a very elegant solution.

**Comment by Olivezer** [comment]
> 
> Currently crying from happiness. Thanks a lot Olivezer, this worked for me:). To me this seems like a very elegant solution.

Glad it worked out for you :) Maybe you should mention this solution on your Anaconda issue you also opened, this would allow for a maximum of people to benefit from this solution.
Best regards

**Comment by life-speedrunner** [comment]
would anyone know how to add this conda package to an interactive sublimerepl?

**Comment by mattip** [comment]
@life-speedrunner you may have better luck asking such questions on a sublime support forum. It would be nice if someone would put the suggested solution into sublime's/conda's documentation (maybe someone already has?), as this is all about using conda inside sublime which is only tangentially connected to numpy.

Closing, since the original issue has a solution.

**Comment by zoonessj** [comment]
I tried everything but remain same problem,  In my case Re-Installing anaconda  and relink sys paths fixed my problem

**Comment by lwbaqueros** [comment]
I have the same problem. always using Sublime Text with miniconda and several environments, no problem, but I got this error since I moved to Anaconda.

**Comment by lwbaqueros** [comment]
Run in cmd y en anaconda prompt `echo %PATH%`. It must return the same values. If not, add all the anaconda environmental variables to the environmental path of windows. That solved my problem. 
![image](https://user-images.githubusercontent.com/46763074/156812634-674bf0f1-7707-4e3c-8b37-0e09df853da2.png)
