### ISSUE TITLE
np.array([0.0, 1.0, 2.0], ndmin=2) fails on big endian system

### ISSUE THREAD

**Issue by mwhudson** [numpy/numpy#14767]
### Reproducing code example:

```python
import numpy as np
np.array([0.0, 1.0, 2.0], ndmin=2) 
```

on a big endian system, e.g. Ubuntu on s390x (which I realise is not the most accessible of platforms)

### Error message:

ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)

### Numpy/Python version information:

1.17.3

What's going on? Well e256762b022acf5d0df096cf178704518b782b89 changed the ndmin local variable from an "int" to an "npy_intp". On 64-bit linux int is 32 bits and npy_intp aka intptr_t is 64 bits. &ndmin is passed to PyArg_ParseTupleAndKeywords against a "i" argument spec ... and you can see where this is going. Casting a long* to an int* and writing through it works OK on little endian but very much does not on big endian. There's no PyArg_ParseTupleAndKeywords code for intptr_t, so the best fix is probably to change ndmin back to an int and be a little careful in the fast path that "ndmin = PyLong_AsLong(ndmin_obj)" does not overflow.

**Comment by mwhudson** [comment]
Here's the simple patch I am testing for Ubuntu:

```diff
Description: Fix int/intptr_t confusion in np.array handling of ndmin
Author: Michael Hudson-Doyle <michael.hudson@ubuntu.com>
Bug: https://github.com/numpy/numpy/issues/14767
Bug-Ubuntu: https://bugs.launchpad.net/ubuntu/+source/numpy/+bug/1849477
Last-Update: 2019-10-24
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
--- a/numpy/core/src/multiarray/multiarraymodule.c
+++ b/numpy/core/src/multiarray/multiarraymodule.c
@@ -1581,8 +1581,7 @@
     PyArrayObject *oparr = NULL, *ret = NULL;
     npy_bool subok = NPY_FALSE;
     npy_bool copy = NPY_TRUE;
-    int nd;
-    npy_intp ndmin = 0;
+    int ndmin = 0, nd;
     PyArray_Descr *type = NULL;
     PyArray_Descr *oldtype = NULL;
     NPY_ORDER order = NPY_KEEPORDER;
@@ -1644,13 +1643,15 @@
 
             ndmin_obj = PyDict_GetItem(kws, npy_ma_str_ndmin);
             if (ndmin_obj) {
-                ndmin = PyLong_AsLong(ndmin_obj);
-                if (error_converting(ndmin)) {
+                long t;
+                t = PyLong_AsLong(ndmin_obj);
+                if (error_converting(t)) {
                     goto clean_type;
                 }
-                else if (ndmin > NPY_MAXDIMS) {
+                else if (t > NPY_MAXDIMS) {
                     goto full_path;
                 }
+                ndmin = t;
             }
 
             /* copy=False with default dtype, order (any is OK) and ndim */
```

**Comment by eric-wieser** [comment]
I've been thinking about writing lgtm queries to catch this type of mistake... There's no way this is the only one.

**Comment by mwhudson** [comment]
You might be right but fwiw all tests pass on s390x with this patch applied.

**Comment by mattip** [comment]
@mwhudson would you like to make this a PR?
