### ISSUE TITLE
Performance: np.hypot slower than np.sqrt(x**2 + y**2).

### ISSUE THREAD

**Issue by MaxNoe** [numpy/numpy#14761]
`numpy.hypot` is slower than just calculating `np.sqrt(x**2 + y**2)`. 
As these should be equivalent, shouldn't the more specialized function be faster?
E.g. by not creating new arrays for `x**2`, `y**2`, `x**2 + y**2` and the result? 

### Reproducing code example:

```python
In [1]: import numpy as np

In [2]: x, y = np.random.uniform(0, 50, (2, 10_000))

In [3]: %timeit np.hypot(x, y)
218 µs ± 29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [4]: %timeit np.sqrt(x**2 + y**2)
45 µs ± 1.14 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

### Numpy/Python version information:

Tested on python compiled from source on centos 7 with numpy pypi wheel:
```
1.17.3 3.7.5 (default, Oct 23 2019, 09:38:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

and on anaconda python / numpy
```
1.17.2 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0]
```

**Comment by ewmoore** [comment]
The specialized function is provided because it uses an algorithm that
avoids underflow or overflow when computing its result. The simply textbook
approach fails for very small or very large numbers since their square may
not not fit into a double precision number.  It isn’t there for speed.

**Comment by charris** [comment]
See https://www.johndcook.com/blog/2010/06/02/whats-so-hard-about-finding-a-hypotenuse/ for more discussion.
