### ISSUE TITLE
DOC: np.isneginf should not allow inputs with different shapes

### ISSUE THREAD

**Issue by guilhermeleobas** [numpy/numpy#14760]
Following up on the discussion on the Numba issue tracker: [numba/numba#4610](https://github.com/numba/numba/pull/4610)

The NumPy docs state that the second input of `np.isneginf` must have the same dimensions as the first input. But NumPy is accepting parameters with different dimensions (see section below). Is this a bug or the specification is wrong?

> out : ndarray
> A boolean array with the same dimensions as the input.

### Reproducing code example:

```python
>>> import numpy as np
>>> np.isneginf(np.NINF, np.zeros(1, dtype=np.bool))
array([ True])
```

### Numpy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.17.0 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by eric-wieser** [comment]
This behavior is by design - see also:
```python
>>> out = np.empty((3, 3))
>>> np.add(1, 1, out=out)
array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])
```

**Comment by stuartarchibald** [comment]
I think a similar fix is also needed for the `np.isposinf`docs. 

@guilhermeleobas I think that unfortunately Numba will need to compile return type specialisations to handle this.

**Comment by guilhermeleobas** [comment]
Thanks for the feedback @eric-wieser. I will try to send a PR for this as soon as I have some cycles to spare.

@stuartarchibald, yes, that's true. I will adjust my PR on Numba to address this issue.

Thanks.

**Comment by guilhermeleobas** [comment]
@eric-wieser, I was checking this issue again and I am in doubt now if a changing in the docs is really necessary. `np.isneginf` as well as `np.isposinf` always outputs a boolean array, right? If so, a call of the form `np.isneginf(2)` will always output `array(False, dtype=bool)`. Maybe this is somewhat clear in the docs: an input with a single scalar value is converted to an array and the output will be an array with a single element.
