### ISSUE TITLE
DOC: Example of using np.lib.tracemalloc_domain

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#14766]
It would be good to have a documented example of using `np.lib.tracemalloc_domain` with Python's [`tracemalloc`]( https://docs.python.org/3/library/tracemalloc.html ) to filter out NumPy memory allocations. Ideally this would be simple enough that users could copy-paste it when trying to debug memory usage issues.

**Comment by InessaPawson** [comment]
@jakirkham, if the example in https://github.com/numpy/numpy/pull/23648 addresses this issue, please close it.

**Comment by jakirkham** [comment]
Thanks Inessa! 🙏 

Just looked at [the rendered docs (based on `main`)]( https://numpy.org/devdocs/reference/c-api/data_memory.html#example-of-memory-tracing-with-np-lib-tracemalloc-domain ), this looks great 😄
