### ISSUE TITLE
'LoadDriver' 'DLL load failed

### ISSUE THREAD

**Issue by Jeyaanand** [numpy/numpy#14764]
'LoadDriver' 'DLL load failed while running in Quali server

Logs:
“Command execution failed with 'General Execution' error.
Failed to start execution: Unexpected error - Python unhandled exception was raised while invoking server method 'LoadDriver' 'DLL load failed: The specified procedure could not be found.”

**Comment by mattip** [comment]
Closing. If this is a NumPy problem, please reopen and explain how NumPy is involved, specify your NumPy and Python versions, and tell us how you installed python and NumPy.
