### ISSUE TITLE
Proposal : more backward compatible variant of import_array()?

### ISSUE THREAD

**Issue by bartoli** [numpy/numpy#14773]
Issue : Calling import_array() from C code using numpy, causes a dependency to a numpy version

Use case : i call import_array()  to use the C API of my numpy 1.16 in C++ code that is wrapped to a python module by swig. If i try to import that python module in a python environment that has numpy 1.11, import_array() fails because of the multiarray module rename of 1.16 (and then because of the difference of numpy ABI and API versions)

I understand that the API changes slightly at each version, but assuming one only uses a few basic PyArray* functions, couldn't there be a second slightly modified version of import_array, with a big comment USE AT YOUR OWN RISK, that would try to import both new or old multiarray module names, and ignore API version checks, so a developper can easily try to enable backwards compatibility to other numpy versions?

**Comment by rgommers** [comment]
You should do it the other way around - if you have both numpy 1.11 and 1.16, then compile against 1.11. 

> I understand that the API changes slightly at each version, but assuming one only uses a few basic PyArray* functions, couldn't there be a second slightly modified version of import_array, with a big comment USE AT YOUR OWN RISK

We don't like such use-at-your-own-risk things; we either put in the effort to make something work properly, or not. So there could in theory be such a function, but there's not.
