### ISSUE TITLE
arm64: Fails to build on PyPy

### ISSUE THREAD

**Issue by om26er** [numpy/numpy#14780]
Latest PyPy supports arm64 but it seems Numpy fails to build on that environment

### Reproducing example:

```bash
apt update
apt install g++
wget https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.2.0-aarch64.tar.bz2
tar xf pypy3.6-v7.2.0-aarch64.tar.bz2
pypy3.6-v7.2.0-aarch64/bin/pypy3 -m ensurepip
pypy3.6-v7.2.0-aarch64/bin/pypy3 -m pip install numpy
```

### Build failure logs
I have attached them as a file since that's quite a few hundred lines.
[numpy_fail.log](https://github.com/numpy/numpy/files/3771926/numpy_fail.log)

**Comment by om26er** [comment]
some of the interesting bits
```
...
  compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/root/pypy3.6-v7.2.0-aarch64/include -c'
  gcc: _configtest.c
  _configtest.c:1:10: fatal error: sys/endian.h: No such file or directory
   #include <sys/endian.h>
            ^~~~~~~~~~~~~~
...
```
Also
```
...
  compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/root/pypy3.6-v7.2.0-aarch64/include -c'
  gcc: _configtest.c
  _configtest.c:1:10: fatal error: xmmintrin.h: No such file or directory
   #include <xmmintrin.h>
            ^~~~~~~~~~~~~
  compilation terminated.
...
```

**Comment by eric-wieser** [comment]
Those sections are likely not interesting - those are the results of numpy working out what is available to the compiler, and are not real failures.

**Comment by mattip** [comment]
This seems like a PyPy problem. It is messing up the templating of the `*.src` files. This does not happen on x86, as the CI runs are succeeding. 

xref [pypy issue 3104](https://bitbucket.org/pypy/pypy/issues/3104/aarch64-pyyp-72-fails-to-use-templating)

**Comment by mattip** [comment]
Thanks for the report. The PyPy issue was solved. If you try again with a nightly build from http://buildbot.pypy.org/nightly/py3.6 it should just work. Closing, please reopen or open a new issue if problems remain.
