### ISSUE TITLE
numpy.asarray() removes fill value from pandas SparseArrays

### ISSUE THREAD

**Issue by jtanman** [numpy/numpy#14783]
numpy.asarray() removes the fill value from pandas SparseArrays.

### Reproducing code example:

```python
import numpy as np
import pandas as pd
arr = np.random.randint(2, size=10)
sparr = pd.SparseArray(arr, fill_value=0)
np_arr = np.asarray(sparr)
```

Gives

    ipdb> arr
    array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0])
    ipdb> sparr
    [1, 0, 1, 1, 1, 0, 1, 1, 0, 0]
    Fill: 0
    IntIndex
    Indices: array([0, 2, 3, 4, 6, 7], dtype=int32)

    ipdb> np_arr
    array([1, 1, 1, 1, 1, 1])

### Numpy/Python version information:

1.17.3 3.7.1 | packaged by conda-forge | (default, Mar 13 2019, 05:40:40)
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by TemitopeOladokun** [comment]
Nice observation. I got this at my end too
The index are totally substituted

`
import numpy as np
import pandas as pd
arr = np.random.randint(2, size=10)
sparr = pd.SparseArray(arr, fill_value=0)
np_arr = np.asarray(sparr)
` 

These are my observations
`
arr
Out[2]:
array([1, 1, 1, 0, 0, 0, 0, 0, 1, 0])

sparr
Out[3]:
[1, 1, 1, 0, 0, 0, 0, 0, 1, 0]
Fill: 0
IntIndex
Indices: array([0, 1, 2, 8])

np_arr
Out[4]:
array([1, 1, 1, 1])
`
​

**Comment by seberg** [comment]
This is something that should probably be solved on the pandas side and is only indirectly a numpy issue. Pandas could opt to give a warning here, or refuse to convert. It is possible that they cannot do this, but we certainly cannot change things.

**Comment by shoyer** [comment]
Please file a bug report with pandas. This behavior is entirely determined by the `__array__()` method on SparseArray.
