### ISSUE TITLE
numpy for 64 bit windows

### ISSUE THREAD

**Issue by Dan-Patterson** [numpy/numpy#14785]
The anaconda distribution for python 3.6 and 3.7 64 bit Windows, has numpy at version 1.16.5.
I Have to do a conda update (no pip for a variety of reasons).
Is the reason for this at your end or theirs? 
Equivalent specs for Linux is already into the 1.17 range.

**Comment by charris** [comment]
Anaconda isn't our responsibility, you should ask them or google for solutions.

**Comment by Dan-Patterson** [comment]
I will ask... after 'googling' and checking their site.  Surprised that there hasn't been anyone else with a similar issue or no one here noticed.  thanks

**Comment by rgommers** [comment]
Thanks for reporting @Dan-Patterson. This is really annoying, I thought that was finally solved. But apparently not on Windows.

I see you reported it at https://github.com/ContinuumIO/anaconda-issues/issues/11399, thanks for that.

**Comment by Dan-Patterson** [comment]
[https://github.com/ContinuumIO/anaconda-issues/issues/11399]
closed on anaconda.
