### ISSUE TITLE
ValueError: sort array is read-only

### ISSUE THREAD

**Issue by corner100** [numpy/numpy#14795]
Tried to sort an array from a diagonal matrix. Can you help me. What did I do wrong?

### Reproducing code example:

```python
import numpy as np
s1 = np.random.uniform(-1,0,1000)
s_viel = np.tile(s1, (1000,1))
s2 = np.random.uniform(-1,0,1000)
s_diff = s_viel-s2
s_diff_2 = np.matmul(s_diff,s_diff.T)
s_diff_2_diag = s_diff_2.diagonal()
s_diff_2_diag.sort() #### Error here
```

### Numpy/Python version information:
Python 3.6
Output from 'import sys, numpy; print(numpy.__version__, sys.version):
1.17.1 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]

**Comment by mproszewska** [comment]
[Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diagonal.html) describes that behaviour and suggests using np.diagonal(a).copy().

**Comment by seberg** [comment]
Indeed, sort is in-place, so you have to do a copy. `np.sort`, the function, should do the copy for you.
