### ISSUE TITLE
Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by milthorpe** [numpy/numpy#14797]
Installing numpy in an apparently-clean Ubuntu 18.04 python environment complains about a failed build.

### Reproducing code example:

```
$ pip uninstall numpy
$ pip install numpy
$ python
import numpy as np
```

### Error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/milthorpe/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/milthorpe/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/local/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: ~/.local/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so: undefined symbol: PyUnicodeUCS4_FromObject

### Numpy/Python version information:

1.16.5

### System information

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
$ pip show numpy
Name: numpy
Version: 1.16.5
$ ls /usr/local/lib/python2.7/site-packages/
README
$ ls /usr/local/lib/python2.7/dist-packages/
intelhex  intelhex-2.2.1.dist-info
$ ls ~/.local/lib/python2.7/site-packages/
numpy  numpy-1.16.5.dist-info
$ echo $PYTHONPATH

$ echo $PATH
~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin
$ ls ~/.local/bin
f2py  f2py2  f2py2.7

**Comment by mattip** [comment]
Maybe you have a [USC2 build of python](https://docs.python.org/2.7/faq/extending.html#when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2). Is this a normal x86_64 machine? Could you try the code in that FAQ answer:
```
import sys
if sys.maxunicode > 65535:
    print 'UCS4 build'
else:
    print 'UCS2 build'
```
`pip` thinks you have a USC4 build.

**Comment by milthorpe** [comment]
Yes, according to the code above I have a USC2 build. This is an ordinary x86_64 machine:
```
$ uname -mipsrv
Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64
```
