### ISSUE TITLE
`numpy.trapz` returns the wrong result when integrating over x values of type `pandas.Datetime`.

### ISSUE THREAD

**Issue by apuchitnis** [numpy/numpy#14806]
`numpy.trapz` returns the wrong result when integrating over x values of type `pandas.Datetime`.

### Reproducing code example:

```python
import numpy as np
import pandas as pd
import datetime

data = pd.DataFrame([[datetime.datetime(2019, 1, 1, 0, 0), 0],
                     [datetime.datetime(2019, 1, 1, 0, 10), 50],
                     [datetime.datetime(2019, 1, 1, 0, 20), 100],
                     [datetime.datetime(2019, 1, 1, 0, 30), 150],
                     [datetime.datetime(2019, 1, 1, 0, 40), 50],
                     [datetime.datetime(2019, 1, 1, 0, 50), 0],
                     [datetime.datetime(2019, 1, 1, 1, 0), 0]],
                    columns=['x', 'y'])
data = data.set_index('x')

print(type(data.index)) # `pandas.core.indexes.datetimes.DatetimeIndex`

integral = np.trapz(data['y'], data.index).astype('timedelta64[s]')
print(integral) #210000 seconds <- correct answer

data['y'] *= 10000
integral = np.trapz(data['y'], data.index).astype('timedelta64[s]')
print(integral) #2100000000 seconds <- correct answer

data['y'] *= 10
integral = np.trapz(data['y'], data.index).astype('timedelta64[s]')
print(integral) #7605244118 seconds <- WRONG! incorrect answer. correct answer is 21000000000 seconds.
```

Note that this error only occurs when x is of the type `pandas.core.indexes.datetimes.DatetimeIndex`, as in the example above. If we were to instead do `data.index.to_pydatetime()` to convert the index into `datetime.Datetime` (and used `.total_seconds()` to convert the integral result into seconds), the integral would be correct.

### Numpy/Python version information:

```
1.17.2 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]
```

**Comment by apuchitnis** [comment]
I don't know if this is an issue with `numpy` or with `pandas`. Do let me know if the issue is with `pandas`, so I can raise the issue with them instead.

**Comment by eric-wieser** [comment]
Can you add `print(data['y'])` before the incorrect answer?

**Comment by apuchitnis** [comment]
> Can you add `print(data['y'])` before the incorrect answer?

Sure. I get:
```
x
2019-01-01 00:00:00           0
2019-01-01 00:10:00     5000000
2019-01-01 00:20:00    10000000
2019-01-01 00:30:00    15000000
2019-01-01 00:40:00     5000000
2019-01-01 00:50:00           0
2019-01-01 01:00:00           0
Name: y, dtype: int64
```
The `y` values are 100000 times larger than the original `data`, as expected.

**Comment by ianbillett** [comment]
Apologies @apuchitnis, but I don't fully understand the point of your example. 

Are you saying that only when you multiply `data[y]` by an arbitrary amount it appears to randomly break the integral calculation?

**Comment by eric-wieser** [comment]
The issue is that `data.index.dtype` is `datetime64[ns]`, so the multiplication quickly overflows.

**Comment by apuchitnis** [comment]
> Apologies @apuchitnis, but I don't fully understand the point of your example.
> 
> Are you saying that only when you multiply `data[y]` by an arbitrary amount it appears to randomly break the integral calculation?

Not exactly. My point is that when the values become very large, then the integral breaks.

> The issue is that `data.index.dtype` is `datetime64[ns]`, so the multiplication quickly overflows.

Yep, I thought this would be the case.

Is there any way we can perform integral more safely, or provide an error to the user when an overflow occurs?

Also, clearly nanosecond accuracy is not needed for this integral. It would be great if a user could specify the resolution for the internal representation. For examples, representing minutes instead of nanoseconds would be fine in this example.

**Comment by eric-wieser** [comment]
>  or provide an error to the user when an overflow occurs

Detecting integer overflow is expensive, so numpy has chosen in general not to do it. Perhaps that would change in future, but it's a decision with far-reaching implications.

>  It would be great if a user could specify the resolution for the internal representation

For your problem, they effectively can - pass in `data.index.astype('datetime64[m]')` or  even`data.index.astype('datetime64[10m]')` instead.

If you specifically care about having a different result type to the input type, then we probably need to make trapz a gufunc.

There's probably a way to construct your dataframe to work with lower-precision times in the first place, but I couldn't tell you how.

**Comment by apuchitnis** [comment]
> > or provide an error to the user when an overflow occurs
> 
> Detecting integer overflow is expensive, so numpy has chosen in general not to do it. Perhaps that would change in future, but it's a decision with far-reaching implications.

Got it. Would using [`numpy.seterr()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.seterr.html) allow me to detect overflow conditions here?

> > It would be great if a user could specify the resolution for the internal representation
> 
> For your problem, they effectively can - pass in `data.index.astype('datetime64[m]')` or even`data.index.astype('datetime64[10m]')` instead.

thanks for the hint :+1:! I'll try this out.

From what I understand, numpy does not currently intend to solve/detect this type of problem, and I also have a workaround. So I will close this issue.
