### ISSUE TITLE
float128 should have __floor__, __ceil__ and __trunc__

### ISSUE THREAD

**Issue by serhiy-storchaka** [numpy/numpy#14811]
`math.floor()` and `math.ceil()` can produce incorrect result for `float128` due to double rounding. `math.trunc()` doe not work with `float128` (but `int()` works).

### Reproducing code example:
```python
>>> import numpy as np
>>> import math
>>> x = np.float128('0.99999999999999999995')
>>> x < 1
True
>>> np.floor(x)
0.0
>>> math.floor(x)
1
>>> np.trunc(x)
0.0
>>> y = np.float128('1.0000000000000000001')
>>> y > 1
True
>>> np.ceil(y)
2.0
>>> math.ceil(y)
1
>>> z = np.float128()
>>> np.trunc(z)
0.0
>>> math.trunc(z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type numpy.float128 doesn't define __trunc__ method
>>> int(z)
0
```

This can be solved by implementing `__floor__`, `__ceil__` and `__trunc__` in `float128`.

### Numpy/Python version information:
1.13.3 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]

**Comment by eric-wieser** [comment]
Overlaps with #13375 - this applies to all the floating point types.

**Comment by serhiy-storchaka** [comment]
Other examples:
```python
>>> t = np.float128('1e1000')
>>> t
9.9999999999999999997e+999
>>> np.floor(t)
9.9999999999999999997e+999
>>> np.ceil(t)
9.9999999999999999997e+999
>>> np.trunc(t)
9.9999999999999999997e+999
>>> math.floor(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
>>> math.ceil(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
>>> math.trunc(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type numpy.float128 doesn't define __trunc__ method
>>> int(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
```
The latter one surprised me.
```python
>>> t.__int__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
```

**Comment by eric-wieser** [comment]
In your opinion, what should `trunc(np.array([np.float128('1e1000')]))` return? An object array, or an array with overflowed values?

**Comment by serhiy-storchaka** [comment]
Sorry, I know very little about NumPy, but I would expect `math.trunc()` returning an object array (containing `int` instances) and `numpy.trunc()` returning a `float128` array. You could use `math.trunc()` or `numpy.trunc()` depending on your needs.

Other possibility is to introduce the `float128int` type which is a subtype of `float128`, but can contain only integer values and has the `__index__` method. But I think this is too complicated.

**Comment by seberg** [comment]
@serhiy-storchaka could you add a comment to the issue linked by Eric and close this? It seems good to keep this in one place?

**Comment by rossbar** [comment]
Closing as duplicate to keep the discussion centralized in #13375. Please add any additional comments (including a potentially a summary of the discussion here) to that thread.
