### ISSUE TITLE
f2py user's guide uses python 2 syntax for print

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#14812]
For example, in the section [Using F2PY bindings in Python](https://docs.scipy.org/doc/numpy/f2py/python-usage.html) there is an example with instructions such as 

> In Python:
```python
    >>> import ftype
    >>> print ftype.__doc__
    This module 'ftype' is auto-generated with f2py (version:2.28.198-1366).
    Functions:
      foo(n=13)
    COMMON blocks:
      /data/ a,x(3)
    .
```
If this is relevant I'm happy to submit a PR making sure that the docs are compatible with Python 3.

**Comment by mattip** [comment]
xref gh-14732 which tries to run code in the rst files.

A PR would be welcome. The file in question is `ftype_session.dat`. The site for numpy documentation has moved to https://numpy.org/doc, and the current HEAD's documentation is https://numpy.org/devdocs. I wonder how we can get google to start sending people to the newer docs.

**Comment by melissawm** [comment]
Ok, while working on this I realized some of the outputs that I get don't match the documentation. For example, the first example on the [Getting Started](https://numpy.org/devdocs/f2py/getting-started.html) is the `fib1.f` file, and when I import it I get

```python
>>> print(fib1.fib.__doc__)                                                                                                                                                                          
fib(a,[n])

Wrapper for ``fib``.

Parameters
----------
a : input rank-1 array('d') with bounds (n)

Other Parameters
----------------
n : input int, optional
    Default: len(a)
```

which is different from what is listed on that page. Should I open a new PR for this or can I include this in the docs update?

Thanks for the help!

**Comment by mattip** [comment]
It can be in the same PR. 

By the way, if you have not seen it yet, you may find it helpful to look at our [developer workflow](https://numpy.org/devdocs/dev/index.html#development-process-summary) guide, we would appreciate feedback and suggestions on how to better organize the information for new contributors.

**Comment by melissawm** [comment]
While checking this, I realized another strange behaviour: in https://numpy.org/devdocs/f2py/python-usage.html, under String arguments, the example should result in 

```python
>>> import numpy
>>> a=numpy.array('123')
>>> b=numpy.array('123')
>>> c=numpy.array('123')
>>> d=numpy.array('123')
>>> mystring.foo(a,b,c,d)
 A=123
 B=123
 C=123
 D=123
 CHANGE A,B,C,D
 A=A23
 B=B23
 C=C23
 D=D23
>>> a.tostring(),b.tostring(),c.tostring(),d.tostring()
('123', 'B23', '123', 'D23')
```

but I'm getting 

```python
>>> import numpy
>>> a = numpy.array('123')
>>> b = numpy.array('123')
>>> c = numpy.array('123')
>>> d = numpy.array('123')
>>> mystring.foo(a,b,c,d)
 A=1    
 B=1    
 C=1           
 D=1           
 CHANGE A,B,C,D
 A=A    
 B=B    
 C=C           
 D=D           
>>> a.tostring(), b.tostring(), c.tostring(), d.tostring()
(b'1\x00\x00\x002\x00\x00\x003\x00\x00\x00', b'B          \x00', b'1\x00\x00\x002\x00\x00\x003\x00\x00\x00', b'D          \x00')
>>>
```

I was looking around for an issue about this and found #9370 which might be related (but I'm not sure). 

Is this expected behaviour?

**Comment by melissawm** [comment]
I think I see what's going on. Because of the change in string types between Python2 and Python3, the `numpy.dtype('c')` option must be used for strings to be correctly represented by f2py. 

Here's the test I did:
```fortran
C FILE: STRINGTEST.F
      SUBROUTINE FOO(A)
      CHARACTER*5 A
Cf2py intent(in) a
      PRINT*, "A=",A
      PRINT*, "CHANGE A:"
      A(1:1) = 'A'
      PRINT*, A
      END
C END OF FILE STRINGTEST.F
```
After doing `python -m numpy.f2py -c stringtest.f -m mystring` I get:
```python
>>> import mystring
>>> mystring.foo('12345')
 A=12345
 change a
 A(1) = A
 A2345
>>> import numpy
>>> mystring.foo(numpy.array('12345'))
 A=1    
 change a
 A(1) = A
 A    
>>> mystring.foo(numpy.array('12345', numpy.dtype('c')))
 A=12345
 change a
 A(1) = A
 A2345
>>> 
```
So I'm proposing a change in the docs to make it clearer.
