### ISSUE TITLE
BLD: 32-bit windows builds fail to download mingw32

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#14822]
The win32 failure to download mingw is becoming annoying. [OpenBLAS](https://github.com/xianyi/OpenBLAS/blob/develop/appveyor.yml) and [numpy-wheels](https://github.com/MacPython/numpy-wheels/blob/master/.appveyor.yml) use Appveyor not azure, which comes with mingw. It seems the azure images have a [version of mingw](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-MinGW.ps1#L9). The script seems to indicate it also has mingw32. We should figure out if it has a 32-bit mingw and try to use it rather than downloading our own, or maybe skip the f2py tests on 32-bit windows builds.

**Comment by carlkl** [comment]
related:

- [ENH: Poll: availability for 32bit Windows scipy binaries in future?](https://github.com/scipy/scipy/issues/16286)
- [ENH: Developing a dedicated compiler toolchain for windows scipy-meson builds](https://github.com/rgommers/scipy/issues/140)
- [DOC: building on Windows uses GCC with Meson, not MSVC](https://github.com/scipy/scipy/issues/16322)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by charris** [comment]
Note that NumPy no longer uses Appveyor.

**Comment by mattip** [comment]
Closing, the build is quite reliable now.
