### ISSUE TITLE
Numpy One-Liner Sigmoid Function Fails

### ISSUE THREAD

**Issue by Danc2050** [numpy/numpy#14824]
I believe I am most likely at fault for this and am missing something, but I felt the need to post anyways. The issue is that I cannot successfully do a sigmoid function in `numpy` with a one liner, but am successful using `scipy`'s sigmoid function `expit`.

### Reproducing code example:
The problem is the classical MNIST dataset. I have a set of weights:
`weights_ji = np.random.uniform(-0.5, 0.5, size = (785,20))`
and a set of train data that is 785 rows (e.g.,):

[train_data(785 rows).log](https://github.com/numpy/numpy/files/3801198/train_data.785.rows.log)

```python
import numpy as np
from scipy.special import expit # sigmoid function
train = # array/vector from train_data(785 rows).log
hidden_perceptrons = 1 / np.add(1, np.exp(train @ weights_ji)) # sigmoid function is 1 / 1 + e^x
print(hidden_perceptrons)
hidden_perceptrons = expit(train @ weights_ji)
print(hidden_perceptrons) # this gives the correct value
input() # meant to pause so as to allow review for debuggers
```
I most likely am to blame again. Sorry if that is the case! Thank you for the extra eye on this.

**Comment by mattip** [comment]
Can you give a concrete example of the difference: how you used `scipy.expit` and what the output was vs. what output you got from your code? It would be better to start with a small example: 3x4 or so would be sufficient.

**Comment by Danc2050** [comment]
**Concrete Example**
```
import numpy as np
from scipy.special import expit
#------variable setup---------#
>>>train = np.array([1.0, 0.01176471, 0.07058824]) # 1 is for bias unit
>>>weights_ji = np.random.uniform(-0.5, 0.5, size = (3,4))
array([[0.73105858, 0.73105858, 0.73105858, 0.73105858],
       [0.73105858, 0.73105858, 0.73105858, 0.73105858],
       [0.73105858, 0.73105858, 0.73105858, 0.73105858]])
#------numpy sigmoid---------#
>>>1/ np.add(1, np.exp(train @ weights_ji))
array([0.31189746, 0.31189746, 0.31189746, 0.31189746])
#------scipy sigmoid---------#
>>>expit(train @ weights_ji)
array([0.68810254, 0.68810254, 0.68810254, 0.68810254])

**Comment by WarrenWeckesser** [comment]
@Danc2050, you are missing a minus sign.  `scipy.special.expit` implements `1/(1 + exp(-x))`:

```
In [27]: 1 / np.add(1, np.exp(-train @ weights_ji))                                                    
Out[27]: array([0.46164975, 0.46052359, 0.60913405, 0.39213173])

In [28]: expit(train @ weights_ji)                                                                     
Out[28]: array([0.46164975, 0.46052359, 0.60913405, 0.39213173])
```

**Comment by Danc2050** [comment]
@WarrenWeckesser Thank you!
