### ISSUE TITLE
`np.isnan` raises an error for datetime (NaT) 

### ISSUE THREAD

**Issue by mathause** [numpy/numpy#14831]
### Reproducing code example:

```python
import numpy as np
a = np.array(['1999-12-15', 'NaT'], dtype='M8[ns]')

np.isnan(a)
np.nanmin(a)
np.nanmax(a)
```

### Error message:

Each of those raises an: 
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### Background

Numpy 1.18 returns `NaT` for `np.min(a)` (it did skip `NaT` before 1.18; #14717). This breaks xarray (pydata/xarray#3409) and pandas (pandas-dev/pandas#29058) - therefore it would be good to make `np.isnan` work with `datetime`.

Also: #9009, #1307, #5222

### Numpy/Python version information:
1.18.0.dev0+3b5db53 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
[GCC 7.3.0]

**Comment by seberg** [comment]
Marked for 1.18. release, I guess probably Matti's PR is the practical thing to do.
