### ISSUE TITLE
Compiled from source on armv7, segmentation fault in random test suite.

### ISSUE THREAD

**Issue by tasansal** [numpy/numpy#14833]
Hi, I compiled BLAS/LAPACK (blis/openblas) libraries from source and after that compiled numpy linking to those libraries. When I run the test suite I get a segmentation fault at random number generator. ScipPy tests complete successfully, issue is with numpy only. Device is a Raspberry Pi 4 with 4GB of memory.

Additional Info:
- Doesn't happen if I install the pre-compiled package from deb, which links to the default BLAS/LAPACK.
- Seems to be related to the MT19937 tests (multinomial, basic).
- I tried all OpenBLAS instead of BLIS+OpenBLAS. Still happening.

### Reproducing code example:

Here is how I compiled BLAS/LAPACK libraries:
BLIS
```
./configure --enable-cblas --enable-threading=openmp --enable-shared --prefix=/opt/blis cortexa15
make -j4
sudo make install
```

OpenBLAS
```
make -j4 PREFIX=/opt/OpenBLAS
make install PREFIX=/opt/OpenBLAS
```

Also tried 
OpenBLAS
```
make -j4 PREFIX=/opt/OpenBLAS USE_OPENMP=1 USE_LOCKING=1
make install PREFIX=/opt/OpenBLAS
```

numpy/scipy
Copy site.cfg.example and name it site.cfg, then uncomment the required LAPACK/BLAS library code.
On RPi we are using BLIS and OpenBLAS libraries installed to /opt/XXXX
We run this command on both numpy and scipy source directories
```
sudo python3 setup.py build -j 4 install
```

Then lets run a config parse and run all tests
```
python3 -c "import numpy; numpy.__config__.show(); numpy.test(verbose=2)"
python3 -c "import scipy; scipy.__config__.show(); scipy.test(verbose=2)"
```

Config printout:
blas_mkl_info:
  NOT AVAILABLE
blis_info:
    libraries = ['blis', 'blis']
    library_dirs = ['/opt/blis/lib']
    define_macros = [('HAVE_CBLAS', None)]
    include_dirs = ['/opt/blis/include/blis']
    language = c
    runtime_library_dirs = ['/opt/blis/lib']
blas_opt_info:
    libraries = ['blis', 'blis']
    library_dirs = ['/opt/blis/lib']
    define_macros = [('HAVE_CBLAS', None)]
    include_dirs = ['/opt/blis/include/blis']
    language = c
    runtime_library_dirs = ['/opt/blis/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/OpenBLAS/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/OpenBLAS/lib']

### Error message:

GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/python3 -c import\ numpy\;\ numpy.random.test\(verbose=5\) -g --python import\ numpy\;\ numpy.random.test\(verbose=5\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb55cb460 (LWP 21701)]
[New Thread 0xb4dca460 (LWP 21702)]
[New Thread 0xb35c9460 (LWP 21703)]
[Thread 0xb35c9460 (LWP 21703) exited]
[Thread 0xb4dca460 (LWP 21702) exited]
[Thread 0xb55cb460 (LWP 21701) exited]
[Detaching after fork from child process 21712]
NumPy version 1.17.3
NumPy relaxed strides checking option: True
=========================================== test session starts ===========================================
platform linux -- Python 3.7.3, pytest-5.2.2, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/pi/downloads/src
plugins: cov-2.8.1
collected 1043 items                                                                                      

tests/test_direct.py::test_seedsequence <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_raw <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_random_raw <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_gauss_inv <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_uniform_double <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_uniform_float <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_repr <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_str <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_pickle <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_invalid_state_type <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  0%]
tests/test_direct.py::TestPhilox::test_invalid_state_value <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPhilox::test_invalid_init_type <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPhilox::test_invalid_init_values <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPhilox::test_benchmark <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPhilox::test_cffi <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py SKIPPED [  1%]
tests/test_direct.py::TestPhilox::test_ctypes <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPhilox::test_getstate <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPhilox::test_set_key <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPCG64::test_raw <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPCG64::test_random_raw <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  1%]
tests/test_direct.py::TestPCG64::test_gauss_inv <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_uniform_double <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_uniform_float <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_repr <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_str <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_pickle <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_invalid_state_type <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_invalid_state_value <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_invalid_init_type <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_invalid_init_values <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_benchmark <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  2%]
tests/test_direct.py::TestPCG64::test_cffi <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py SKIPPED [  3%]
tests/test_direct.py::TestPCG64::test_ctypes <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestPCG64::test_getstate <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestPCG64::test_advance_symmetry <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestMT19937::test_raw <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestMT19937::test_random_raw <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestMT19937::test_gauss_inv <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestMT19937::test_uniform_double <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestMT19937::test_uniform_float <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestMT19937::test_repr <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  3%]
tests/test_direct.py::TestMT19937::test_str <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_pickle <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_invalid_state_type <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_invalid_state_value <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_invalid_init_type <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_invalid_init_values <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_benchmark <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_cffi <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py SKIPPED [  4%]
tests/test_direct.py::TestMT19937::test_ctypes <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_getstate <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_seed_float_array <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  4%]
tests/test_direct.py::TestMT19937::test_state_tuple <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_raw <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_random_raw <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_gauss_inv <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_uniform_double <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_uniform_float <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_repr <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_str <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_pickle <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_invalid_state_type <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  5%]
tests/test_direct.py::TestSFC64::test_invalid_state_value <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  6%]
tests/test_direct.py::TestSFC64::test_invalid_init_type <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  6%]
tests/test_direct.py::TestSFC64::test_invalid_init_values <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  6%]
tests/test_direct.py::TestSFC64::test_benchmark <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  6%]
tests/test_direct.py::TestSFC64::test_cffi <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py SKIPPED [  6%]
tests/test_direct.py::TestSFC64::test_ctypes <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  6%]
tests/test_direct.py::TestSFC64::test_getstate <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  6%]
tests/test_direct.py::TestDefaultRNG::test_seed <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  6%]
tests/test_direct.py::TestDefaultRNG::test_passthrough <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_direct.py PASSED [  6%]
tests/test_generator_mt19937.py::TestSeed::test_scalar <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py PASSED [  6%]
tests/test_generator_mt19937.py::TestSeed::test_array <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py PASSED [  6%]
tests/test_generator_mt19937.py::TestSeed::test_seedsequence <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py PASSED [  7%]
tests/test_generator_mt19937.py::TestSeed::test_invalid_scalar <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py PASSED [  7%]
tests/test_generator_mt19937.py::TestSeed::test_invalid_array <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py PASSED [  7%]
tests/test_generator_mt19937.py::TestSeed::test_noninstantized_bitgen <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py PASSED [  7%]
tests/test_generator_mt19937.py::TestBinomial::test_n_zero <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py PASSED [  7%]
tests/test_generator_mt19937.py::TestBinomial::test_p_is_nan <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py PASSED [  7%]
tests/test_generator_mt19937.py::TestMultinomial::test_basic <- ../../../../usr/local/lib/python3.7/dist-packages/numpy-1.17.3-py3.7-linux-armv7l.egg/numpy/random/tests/test_generator_mt19937.py 
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
random_multinomial (bitgen_state=0xafa98108, n=<optimized out>, mnix=0x64, pix=<optimized out>, 
    d=7178080, binomial=0x451fe8) at numpy/random/src/distributions/distributions.c:1772
1772	    mnix[j] = random_binomial(bitgen_state, pix[j] / remaining_p, dn, binomial);

### Numpy/Python version information:

1.17.3 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0]

**Comment by mattip** [comment]
The random number routines do not use linalg libraries, so there is something more subtle going on here. Can you examine the core dump or run under a debugger to find out where the segfault is happening?

**Comment by mattip** [comment]
@tasansal were you able to debug this?

**Comment by bashtage** [comment]
@mattip I think if there was an issue it would have been fixed with changes to multinomial.

**Comment by rossbar** [comment]
I'm going to close this one due to inactivity. If the issue persists, please reopen with up-to-date info about the problem.

**Comment by allsey87** [comment]
Just adding this here in case it is relevant. I am seeing the following warning when I statically link everything together, although this is with Pyodide's config (and perhaps patches).

```
wasm-ld: warning: function signature mismatch: random_multinomial
>>> defined as (i32, i64, i32, i32, i32, i32) -> void in dist/libnumpy.a(_generator.o)
>>> defined as (i32, i32, i32, i32, i32, i32) -> void in dist/libnumpy.a(distributions.o)
```
