### ISSUE TITLE
distutils can not recongnize Intel Fortran

### ISSUE THREAD

**Issue by jlovemercury** [numpy/numpy#14835]
When I attempted to use f2py with Intel Fortran, it seemed that distutils can not find ifort in my computer, and raised the numpy.distutils.fcompiler.CompilerNotFound.

The reason is that, Intel Compilers are set to print their version information via standard error, not the stand output. So that these information cannot be captured by subprocess.check_output in numpy/distutils/ccomplier.py.

It works now after adding 'stderr=subprocess.STDOUT' into check_output.

**Comment by rgommers** [comment]
is that a change in the most recent version of the Intel compilers? this always used to work fine. and what exact command are you building with?

**Comment by eric-wieser** [comment]
Wasn't this fixed in #12831?

**Comment by jlovemercury** [comment]
> Is this a duplicate of #10569, which was fixed in #12831?

Yes, that is the case. But I think this should be fixed, the way distutils seek and obtain the version information is not wise.

> is that a change in the most recent version of the Intel compilers? this always used to work fine. and what exact command are you building with?

I just used 'f2py --fcompiler=intelem' to build my fortran code, and the thing is exactly the same as #12831 . 
The numpy version on my computer is 1.16.2. It seems that this bug has not been fixed yet.

**Comment by eric-wieser** [comment]
>  But I think this should be fixed, the way distutils seek and obtain the version information is not wise.

What do you think it should do instead?

> The numpy version on my computer is 1.16.2. It seems that this bug has not been fixed yet.

You need at least 1.16.4 for the fix

**Comment by jlovemercury** [comment]
> > But I think this should be fixed, the way distutils seek and obtain the version information is not wise.
> 
> What do you think it should do instead?

Access the version number via some 'internal' way? I'm not sure. But I think catching output sounds unstable. Everything will go wrong if compiler vendors decide to change.

> > The numpy version on my computer is 1.16.2. It seems that this bug has not been fixed yet.
> 
> You need at least 1.16.4 for the fix

Thank you for suggestion.
