### ISSUE TITLE
linspace not equally spaced?

### ISSUE THREAD

**Issue by barriecooper** [numpy/numpy#14832]
Differences between successive terms in linspace are not necessarily equally spaced.  See below for an example.  When using linspace in numerical simulations, these errors can accumulate and become unbounded (which is how a student and I spotted the issue).

### Reproducing code example:

```python
import numpy as np
t = np.linspace(0,50,10001)
print(t[0])
print(t[1])
print(t[1]-t[0])
print(t[3])
print(t[4])
print(t[4]-t[3])
print(t[5])
print(t[6])
print(t[6]-t[5])
```

### Error message:

No error message.

### Numpy/Python version information:

1.17.3 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]

**Comment by eric-wieser** [comment]
There do not exist `10001` equally spaced floating point numbers between 0 and 50, so it is not surprising that linspace is unable to produce them.

If you use `2**13 + 1 = 8193` points instead, it will divide exactly:
```
In [44]: a = np.linspace(0, 50, 8193)

In [45]: ad = np.diff(a)

In [46]: np.all(ad == ad[0])
Out[46]: True
```

**Comment by barriecooper** [comment]
Thanks!
