### ISSUE TITLE
PyArray_Check always fails on arrays returned from Python callback

### ISSUE THREAD

**Issue by mcara** [numpy/numpy#14849]
I am not sure whether this is a bug, a limitation, or simply my mis-understanding. Fundamentally, I am trying to implement the example from https://docs.python.org/3/extending/extending.html#calling-python-functions-from-c with the callback function returning a `numpy.ndarray`. Then in the C code, I want to make sure that the returned result is indeed (as expected by the C code) a `numpy.ndarray`. I do that by 
calling `PyArray_Check()` on the `result` from the callback function. The result of `PyArray_Check()` seems to be always `False` (0).

One (possibly important) detail is that in actuality I have a Python code calling C code that needs Python callback supplied from my Python code.

### Reproducing code example:

It is difficult to provide a complete working example for my issue. However, if one can implement the code in https://docs.python.org/3/extending/extending.html#calling-python-functions-from-c, then my callback function is:

```python
import numpy as np
def callback(arg):
    return np.ones(arg)
```

and the relevant C code is:

```C
int arg;
PyObject *arglist;
PyObject *result;
...
arg = 123;
...
/* Time to call the callback */
arglist = Py_BuildValue("(i)", arg);
result = PyObject_CallObject(my_callback, arglist);
Py_DECREF(arglist);

if (!PyArray_Check(result)) {
      PyErr_SetString(PyExc_TypeError, "callback must return a numpy.ndarray.");
      Py_DECREF(result);
      return NULL;
}
printf("callback array ndim: %d\n", PyArray_NDIM(result));
...
```

I always get the error message about incorrect type from the callback. If I comment out the `PyArray_Check` block, the next `printf` statement works fine and it appears that I can successfully use other array API on the `result` object.

### Numpy/Python version information:

```
1.17.2 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]
```
Also,
```
1.17.3 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by mcara** [comment]
Sorry, this issue is likely due to weird setup on my side.

**Comment by misaka-10032** [comment]
Did you link the numpy library twice in your binary? I met the problem before, and it disappeared when I linked the library only once.

**Comment by mcara** [comment]
Unfortunately, I do not remember what happened.
