### ISSUE TITLE
numpy.arange returns vector with the wrong length

### ISSUE THREAD

**Issue by pj1989** [numpy/numpy#14840]
`numpy.arange(0, X, X/L)` should return an array or vector of length `L`. More precisely, should return `[0, X/L*1, X/L*2, ... X/L*(L-1)]`

For some values of X, however, this returns a vector of length `L+1` including also the term `X/L*L`.

```
import numpy 
L = 1000000
X = 1000
print(len(numpy.arange(0, X, X/L)) == L)
>> True

L = 100000
X = 17.32573393714543
print(len(numpy.arange(0, X, X/L)) == L)
>> True

L = 1000000
X = 17.32573393714543
print(len(numpy.arange(0, X, X/L)) == L)
>> False
```

This is obviously due to some floating point error, but I think that the behavior should be fixed as can cause issues in codes that expect the output to be of a given length.

### Numpy/Python version information:

1.17.2 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]

**Comment by charris** [comment]
This is what `linspace` is for. Also note the function documentation

>When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.
