### ISSUE TITLE
Error import Numpy

### ISSUE THREAD

**Issue by Tvektvek** [numpy/numpy#14848]
Unable to import numpy, similar issue for matplotlib as well. '

Installed python 3.7 with Anaconda navigator create function. Also tried to install with anaconda prompt and 'conda create --name n' with similar result. Uninstalled python between each try. 
Numpy installed with 'conda install -c conda-forge numpy' after first running 'activate n' 
Running Windows 10 version 1903
There are two pythons that I can find with 'where python'
C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\python.exe
C:\Users\username\AppData\Local\Microsoft\WindowsApps\python.exe
Last one is a 0 kb file that links to microsoft store installation for python that I am unable to remove. 

### Reproducing code example:
```python
import numpy 

```

### Error message:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/username/PycharmProjects/Projectname/test.py", line 1, in <module>
    import numpy
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

### Numpy/Python version information:
Running
 ```python
import sys, numpy; print(numpy.__version__, sys.version)

```
###Gives Error message

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/username/PycharmProjects/Projectname/test.py", line 1, in <module>
    import sys, numpy
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\n\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\joeyf\AppData\Local\Continuum\anaconda3\envs\Photon\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

**Comment by mattip** [comment]
This is the second report in two days about users having problems with conda on windows. Did something recently change?

xref gh-14846

**Comment by rgommers** [comment]
Let's make sure this is what's happening:
```
conda create --name numpy-dev
conda activate numpy-dev
conda install -c conda-forge numpy
python -c "import numpy"  # fails with missing DLL
```
@Tvektvek can you confirm? Does it happen when you omit `-c conda-forge` as well (assuming you get `numpy` from `defaults` then, please check with `conda list numpy`)?

**Comment by Tvektvek** [comment]
So I managed to solve it, and am no longer getting the message. I tried a lot of different things but think what solved it was that I installed visual C++ build tool 14.0 which as I understand it is needed for pip? I am fairly new to python and programming, so maybe someone more experienced could confirm if this could be the solution or if it was something else I did.


> Let's make sure this is what's happening:
> 
> ```
> conda create --name numpy-dev
> conda activate numpy-dev
> conda install -c conda-forge numpy
> python -c "import numpy"  # fails with missing DLL
> ```
> 
> @Tvektvek can you confirm? Does it happen when you omit `-c conda-forge` as well (assuming you get `numpy` from `defaults` then, please check with `conda list numpy`)?
It works in either case now.

**Comment by rgommers** [comment]
> I tried a lot of different things but think what solved it was that I installed visual C++ build tool 14.0

Interesting. That's a known (and IIRC fixed in master) issue for SciPy. NumPy doesn't contain C++ code and I haven't seen the issue for NumPy before. Perhaps due to a recent change in the conda build toolchain. Let's see if we get more reports.

**Comment by fillipelgm** [comment]
> Let's make sure this is what's happening:
> 
> ```
> conda create --name numpy-dev
> conda activate numpy-dev
> conda install -c conda-forge numpy
> python -c "import numpy"  # fails with missing DLL
> ```
> 
> @Tvektvek can you confirm? Does it happen when you omit `-c conda-forge` as well (assuming you get `numpy` from `defaults` then, please check with `conda list numpy`)?

So, I have the exact same issue. I created new environments according to your instructions. If I use the default channel I get the same message as described by @Tvektvek . Using -c conda-forge, I get this:

Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

I tried installing only the visual c++ tools contained here as well (unsuccessfully though): https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

How can I solve this?

**Comment by zof1985** [comment]
I'm having the same issue even after a miniconda3 fresh installation. After install, the command was:
`conda create -n Py3 numpy`

I'm working on Windows 10.

**Comment by robinflight** [comment]
I was also running into this error after installing numpy 1.17.3 within a fresh Anaconda environment (I tried both Python 3.7 and 3.6, but neither worked).

The solution that fixed the problem for me was to update blas, from the pre-installed 2.12 version to 2.14

Hope that helps

**Comment by rgommers** [comment]
> The solution that fixed the problem for me was to update blas, from the pre-installed 2.12 version to 2.14

Hmm interesting, I'd like to see the exact changes there. It would be helpful if you could put the contents of your `anaconda3/conda-meta/history` file in a gist and link it here.

**Comment by robinflight** [comment]
All of the changes were made within a freshly created environment (doc36):
https://gist.github.com/robinflight/4f74b4738608655a6b16b0c5d06c943d

**Comment by rgommers** [comment]
> The solution that fixed the problem for me was to update blas, from the pre-installed 2.12 version to 2.14

Okay, so what happened here included a change in the installed numpy, from `defaults` to `conda-forge`:
```
-anaconda::numpy-1.17.3-py36hc29fe80_0
-anaconda::numpy-base-1.17.3-py36ha711998_0
...
-conda-forge::blas-2.12-openblas
-conda-forge::libblas-3.8.0-12_openblas
-conda-forge::libcblas-3.8.0-12_openblas
-conda-forge::liblapack-3.8.0-12_openblas
-conda-forge::liblapacke-3.8.0-12_openblas
-conda-forge::libopenblas-0.3.7-hd44dcd8_1
+conda-forge::blas-2.14-openblas
+conda-forge::libblas-3.8.0-14_openblas
+conda-forge::libcblas-3.8.0-14_openblas
+conda-forge::libgfortran-4.0.0-2
+conda-forge::liblapack-3.8.0-14_openblas
+conda-forge::liblapacke-3.8.0-14_openblas
+conda-forge::libopenblas-0.3.7-h4bb4525_3
+conda-forge::llvm-openmp-9.0.0-h40edb58_0
+conda-forge::numpy-1.17.3-py36hde6bac1_0
```

If you look closely, you had `numpy` from the `anaconda` channel combined with `openblas-2.12` from `conda-forge`. That makes very little sense to me. @jjhelmus am I missing something here? That's four users in the last week reporting `numpy` in `defaults` is broken on Windows 10.

Also the switching back and forth earlier between `defaults` and `anaconda` looks weird, but I'm unsure it's related.

**Comment by rossbar** [comment]
This has been inactive for a while, so I'm going to close it. If the issue persists, please open a new issue with information about the system and installation method.

**Comment by kingsyard** [comment]
to keep it simple

pip install numpy  
if then also you get the error try with some particular versions that your work may need.

like pip install numpy==0.9 like this check clearly which version of numpy you need.

if you couldnt install it then try

pip install   --user numpy

second one is where you are providing permission.(granting user permission).

if you have got any other quarie you can contact us at www.smartaitechnologies.com for more

**Comment by mattip** [comment]
@kingsyard this issue and the others you commented on are closed. Please do not abuse the open nature of github advertising your services. I deleted duplicate content from other issues here and reported this to github.com

**Comment by kingsyard** [comment]
sorry i understand .thank you
