### ISSUE TITLE
random.shuffle() does not always shuffle array

### ISSUE THREAD

**Issue by CYHSM** [numpy/numpy#14850]
When calling random.shuffle() with more than one row index, the resulting array is not changed after the call. Calling it on the full array or on one row index has the expected result of shuffling the array in place. 

### Reproducing code example:

```python
import numpy as np

original = np.arange(0,20).reshape(4,5)
shuffled = np.arange(0,20).reshape(4,5)

# --- shuffle full array
print(original)
np.random.shuffle(shuffled)
print(shuffled)
try:
    np.testing.assert_equal(original, shuffled) # Errors correctly
    print('Equal')
except:
    print('Not equal')

# --- now just shuffle one row
original = np.arange(0,20).reshape(4,5)
shuffled = np.arange(0,20).reshape(4,5)

print(original)
np.random.shuffle(shuffled[:,0])
print(shuffled)
try:
    np.testing.assert_equal(original, shuffled) # Errors correctly
    print('Equal')
except:
    print('Not equal')
    
# --- now shuffle two rows
original = np.arange(0,20).reshape(4,5)
shuffled = np.arange(0,20).reshape(4,5)

print(original)
np.random.shuffle(shuffled[:,[0,1]])
print(shuffled)
try:
    np.testing.assert_equal(original, shuffled) # No error as array did not change
    print('Equal')
except:
    print('Not equal')
```

The expected behaviour would be that both rows are shuffled. The behaviour as it is now is very confusing as the array does not change at all after the call to random.shuffle(). I might have some time to look into it when somebody tells me where this might be coming from. Thanks. 

### Numpy/Python version information:

1.17.3 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]

**Comment by WarrenWeckesser** [comment]
The expression `shuffled[:,[0,1]]` uses "fancy indexing" in the second slot.  This results in a *copy* of the data from `shuffled` being created.  E.g., in the following, changing `a` in place does not change `shuffled`:

```
In [19]: shuffled = np.arange(0,20).reshape(4,5)                                

In [20]: a = shuffled[:,[0,1]]                                                  

In [21]: a                                                                      
Out[21]: 
array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [22]: a[0,0] = 99                                                            

In [23]: a                                                                      
Out[23]: 
array([[99,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [24]: shuffled                                                               
Out[24]: 
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])
```

This means the call `np.random.shuffle(shuffled[:,[0,1]])` is shuffling a copy of the first two columns of `shuffled`, but no reference to that copy has been saved, so its memory is eventually garbage collected.

Instead of using fancy indexing, use a slice such as `0:2` (or simply `:2`):

```
In [26]: shuffled = np.arange(0,20).reshape(4,5)                                

In [27]: np.random.shuffle(shuffled[:,:2])                                      

In [28]: shuffled                                                               
Out[28]: 
array([[10, 11,  2,  3,  4],
       [15, 16,  7,  8,  9],
       [ 0,  1, 12, 13, 14],
       [ 5,  6, 17, 18, 19]])
```

**Comment by WarrenWeckesser** [comment]
@CYHSM, I'm closing the issue, but questions or further discussion are welcome.

**Comment by CYHSM** [comment]
Okay thanks for the clarification. I think the slice like `0:2` does only work if I want to shuffle continuous rows, so the solution to this would be something more like this: 
```python
for r in row_indices:
    np.random.shuffle(shuffled[:,r])
```
which feels a bit inefficient. In any case, do you think it would be good if the function warns about that behaviour? I guess people expect the line `np.random.shuffle(shuffled[:,[0,1]])` to change the array, while as it is now the call to the function has the same effect as not calling the function.

**Comment by WarrenWeckesser** [comment]
> In any case, do you think it would be good if the function warns about that behaviour? I guess people expect the line np.random.shuffle(shuffled[:,[0,1]]) to change the array, while as it is now the call to the function has the same effect as not calling the function.

`shuffle` is not making the copy.  The copy happens when you index with `[0, 1]`, which takes place before the argument is passed to `shuffle`.  `shuffle` has no way of knowing that the user has passed in a copy of the array.  It just gets an array and shuffles it in-place.

That is, this line

    np.random.shuffle(shuffled[:,[0,1]])

is effectively the same as

    tmp = shuffled[:,[0,1]]  # Makes a copy!
    np.random.shuffle(tmp)
    del tmp

The real issue is being aware that indexing with a sequence such as `[0, 1]` results in a copy of the data.
