### ISSUE TITLE
ufunc 'add' doesn't respect python 3 arithmetic rules

### ISSUE THREAD

**Issue by kakila** [numpy/numpy#14869]
In place addition of numpy arrays doesn't respect python native casting behavior.

### Reproducing code example:

```python
import numpy as np
a = 0; b = 1.0
a_np = np.array(a)
b_np = np.array(b)
# Python 3 returns float with in place op or not
a += b
print(type(a))
a = 0
a = a + b
print(type(a))
a = 0
# Numpy not in place works the same
a_np = a_np + b_np
print(a_np.dtype)
a_np = np.array(a)
# This raises the error
# UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
a_np += b_np
```
### Error message:

```python
UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

### Numpy/Python version information:

```python
1.17.3 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
```

**Comment by charris** [comment]
Python numeric types are immutable, so can't be used for true inplace operations. The inplace notation `a += b` is just syntactic sugar for `a = a + b`. Numpy arrays are mutable, i.e., the contents can be changed, hence the requirement that the right hand side can be safely cast to the array type.
