### ISSUE TITLE
DOC: f2py docs outdated: extension module has no attribute 'has_column_major_storage'

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#14862]
The f2py docs state that one can use the `has_column_major_storage(<array>)` function to test whether this is true of NumPy arrays. However, this command results in an AttributeError: after compiling the example `array.f` from https://numpy.org/devdocs/f2py/python-usage.html using the command
``f2py -c -m arr array.f -DF2PY_REPORT_ON_ARRAY_COPY=1`` (as the docs indicate), one gets:

```python
>>> import numpy as np
>>> import arr
>>> a = arr.foo([[1, 2, 3], [4, 5, 6]])
>>> arr.has_column_major_storage(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'arr' has no attribute 'has_column_major_storage'
>>> print(numpy.__version__, sys.version)
1.17.3 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0]
>>> 
```

My guess is that the docs are outdated and maybe there is a new method to do the same thing, but I couldn't find it.

**Comment by WarrenWeckesser** [comment]
It looks like that function was removed in 2005: https://github.com/numpy/numpy/commit/1523841beea21af826131945038ea89e686815b9

**Comment by rgommers** [comment]
I think it should just be replaced by `arr.flags.f_contiguous`. That's already mentioned in that doc page, with the disclaimer that it's a little slower - but that shouldn't really be an issue.
