### ISSUE TITLE
Cross-compiling for ARM fails due to platform detection code in random/setup.py

### ISSUE THREAD

**Issue by guillerodriguez** [numpy/numpy#14861]
Cross-compiling for ARM fails due to platform detection code in random/setup.py.

setup.py checks `platform.machine()` to decide whether to add `-msse2` to CFLAGS. However when cross compiling, the info returned by `platform.machine()` refers to the host machine, not to the target machine.

https://github.com/numpy/numpy/blob/2aa3bbab5f49af4c14338bff30b82a3ccaff7935/numpy/random/setup.py#L50

If the host machine is "INTEL-LIKE" but the target machine is ARM, `-msse2` is incorrectly added to CFLAGS and compilation fails.

### Error message:

```
arm-v7a-linux-gnueabihf-gcc: error: unrecognized command line option '-msse2'
error: Command "arm-v7a-linux-gnueabihf-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNPY_NO_DEPRECATED_API=0 -Inumpy/random -Inumpy/random/src -Inumpy/random/src/mt19937 -Inumpy/core/include -Ibuild/src.linux2-arm-3.5/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/avazquez_2/work/current/platform-var-som-mx6/build-target/Python-3.5.4/Include -I/home/avazquez_2/work/current/platform-var-som-mx6/build-target/Python-3.5.4 -Ibuild/src.linux2-arm-3.5/numpy/core/src/common -Ibuild/src.linux2-arm-3.5/numpy/core/src/npymath -Ibuild/src.linux2-arm-3.5/numpy/core/src/common -Ibuild/src.linux2-arm-3.5/numpy/core/src/npymath -c numpy/random/src/mt19937/mt19937-jump.c -o build/temp.linux2-arm-3.5/numpy/random/src/mt19937/mt19937-jump.o -MMD -MF build/temp.linux2-arm-3.5/numpy/random/src/mt19937/mt19937-jump.o.d -U__GNUC_GNU_INLINE__ -std=c99 -msse2" failed with exit status 1
```

### Numpy/Python version information:

 * Numpy 1.17.3
 * Python 3.5.4

**Comment by mattip** [comment]
@guillerodriguez  Is this the only place that needs adjusting for cross-compilation?
@rkern, @bashtage is there a reason to explicitly target msse2 or does the compiler just do that for us?

**Comment by bashtage** [comment]
It was needed when some sse2-dependent bit generators were included, so it can probably be dropped. 

It is only required on i686 in any case, and so probably doesn't have a meaningful effect on end-users if removed. 

How is msse2 passes on Linux/i686 builds in other code? Can this be adapted?

**Comment by guillerodriguez** [comment]
> @guillerodriguez Is this the only place that needs adjusting for cross-compilation?

Yes, I can confirm that this is the only place that needs adjusting for cross-compilation.

**Comment by mattip** [comment]
> How is msse2 passes on Linux/i686 builds in other code? Can this be adapted?

I don't think we do ever pass that flag. In another project, I have seen used of 
```
#if defined(__SSE2__) || defined(__x86_64__) || defined(__amd64__)
#define HAVE_SSE2
#endif
```

and we have tools like `config.check_func` to compile-and-check for features. I think we should remove the flag.

**Comment by rgommers** [comment]
> I don't think we do ever pass that flag.

Correct I think, with one harmless exception for building Accelerate in `distutils/system_info.py`. Also on Windows we do use `'/arch:SSE2` in the distutils compiler configs.

`numpy.random` should be using something like `NPY_HAVE_SSE2_INTRINSICS` I guess, rather than reinvent the check for the feature.
