### ISSUE TITLE
ImportError: Cannot imporrt name SystemRandom

### ISSUE THREAD

**Issue by AVI18794** [numpy/numpy#14860]
### Reproducing code example:

```python
import numpy as np
import matplotlib.pyplot as plt
import time
import numpy as np
ysample = np.random.randint(-50, 50, 100)
xdata = []
ydata = []
plt.show()
axes = plt.gca()
axes.set_xlim(0, 100)
axes.set_ylim(-50, +50)
line, = axes.plot(xdata, ydata, 'r-')
for i in range(100):
    xdata.append(i)
    ydata.append(ysample[i])
    line.set_xdata(xdata)
    line.set_ydata(ydata)
    plt.draw()
    plt.pause(1e-17)
    time.sleep(0.1)
plt.show()

```

  from . import random
  File "C:\Miniconda\envs\cv_course\lib\site-packages\numpy\random\__init__.py", line 181, in <module>
    from . import _pickle
  File "C:\Miniconda\envs\cv_course\lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 9, in init numpy.random.mtrand
  File "mt19937.pyx", line 1, in init numpy.random.mt19937
  File "bit_generator.pyx", line 43, in init numpy.random.bit_generator

### Numpy/Python version information: 

1.17.3

**Comment by mattip** [comment]
What python are you using? Where did you get it? [random.SystemRandom](https://docs.python.org/2/library/random.html#random.SystemRandom) has been supported since 2.4, so `from random import SystemRandom` should be supported by your python.

**Comment by rkern** [comment]
Do you have a module named `random.py` somewhere that isn't the standard library's `random` module? For example, is this script that you posted for us named `random.py`?

**Comment by mattip** [comment]
Closing since the issue author has not responded for a week. @AVI18794 please reopen with more information if you are still unable to import numpy.

**Comment by AVI18794** [comment]
I fixed this issue by reinstalling the python.There was some mess with the inbuilt packages so it was throwing this error no matter what environment I create.

**Comment by WarrenWeckesser** [comment]
@AVI18794, thanks for the update.

**Comment by Hocnonsense** [comment]
I met the same program. The message seemed like this:
```cmd
Traceback (most recent call last):
  File "bit_generator.pyx", line 40, in numpy.random.bit_generator
  File "D:\Code\python\.Anaconda\envs\game\lib\secrets.py", line 20, in <module>
    from random import SystemRandom
ImportError: cannot import name 'SystemRandom' from 'random' (D:\Code\python\WholeCellEcoliRelease\wholecell\utils\random.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Code\python\WholeCellEcoliRelease\wholecell\utils\linear_programming.py", line 16, in <module>
    import numpy as np
  File "D:\Code\python\.Anaconda\envs\game\lib\site-packages\numpy\__init__.py", line 151, in <module>
    from . import random
  File "D:\Code\python\.Anaconda\envs\game\lib\site-packages\numpy\random\__init__.py", line 179, in <module>
    from . import _pickle
  File "D:\Code\python\.Anaconda\envs\game\lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 43, in init numpy.random.bit_generator
ImportError: cannot import name SystemRandom
```

It occurred when I tried to run command `python random.py` in cmd of Windows10. However, when run it by press "F5" in vscode ({"type":"python","request":"launch","program":"${file}","console":"integratedTerminal"},) it will run correctly.

Why?

**Comment by eric-wieser** [comment]
Because when you run it the first way, your random module shadows the built-in module.

**Comment by mattip** [comment]
"your random module" in this case refers to `D:\Code\python\WholeCellEcoliRelease\wholecell\utils\random.py` which is shadowing the NumPy random module

**Comment by Hocnonsense** [comment]
Thanks!

**Comment by subhayanghosh** [comment]
@rkern  Hey, I was facing the same problem and due to the issue that you mentioned. Thanks :)

**Comment by mesrp88** [comment]
when file name in random.py you will face this issue.. today I faced the same issue.

**Comment by jaredkrinke** [comment]
Can NumPy use a relative module reference to prevent this problem?

**Comment by rkern** [comment]
No, this is a naming conflict between the user's top-level module and a top-level stdlib module, not a conflict between the user's top-level module and an internal `numpy` subpackage. There is nothing `numpy` can do about that conflict.

**Comment by neilmolky** [comment]
I fixed this by renaming some of my .py files that made up the project. In particular secrets.py seemed to be conflicting with something which would make sense if there is a similar secrets module in the numpy package.

**Comment by WarrenWeckesser** [comment]
Thanks @neilmolky.  [`secrets`](https://docs.python.org/3/library/secrets.html) is a module in the Python standard library, and it is used by NumPy in the `bit_generator` code of the `random` module:
https://github.com/numpy/numpy/blob/6932eff2c2f634e9b88e940b9f5c02a24b6e71f6/numpy/random/bit_generator.pyx#L38

So if you have a Python file called `secrets.py` that shadows the standard library, it will break the NumPy's random module.
