### ISSUE TITLE
Parameterize unwrap to allow for different ranges (not just -pi, pi)

### ISSUE THREAD

**Issue by kmader** [numpy/numpy#14876]
The idea would be to make unwrap a more general function applicable to problems like quantization overflow (uint8 254+1 -> 0) and allow for `min_val` and `max_val` parameters (which would default to give the same behavior as currently implemented).
### Reproducing code example:

```python
import numpy as np
np.unwrap([0, 1, 2, 0], min_val=0, max_val=3)
```
should give `array([0., 1., 2., 3.])`

**Comment by adeak** [comment]
This change would also make it nicer to unwrap degrees instead of radians.

**Comment by scimax** [comment]
I just had the case of trying to unwrap degrees instead of radians. I changed the `discont` argument to 180, but as the results were weird, I realized that it won't unwrap over 360 degree. I'm looking forward to this pull request being merged!

**Comment by eric-wieser** [comment]
The pull request in its current form is not correct, and the author seems to have lost interest. @scimax, if you're interesting in attempting to fix this yourself, please do - I'd recommend you copy the tests, API, and documentation from that PR, but perhaps try and come up with your own implementation since the one there is incorrect.

**Comment by scimax** [comment]
@eric-wieser I will give it a try. From my first thoughts I would guess it has something to do with the boundaries of interval, and actually with the [question](https://github.com/numpy/numpy/pull/14877#discussion_r351515748) you have already asked. The goal of the line containing the `(ddmod == -pi)` code, is to map the data from the half open interval `[-π,π)` to the half open interval `(-π, π]`, which is also used in [arctan2](https://en.wikipedia.org/wiki/Atan2). Actually, I think the description of the [return value of `np.arctan2`](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html) is not really correct, as the interval is denoted as `[-pi, pi]`.

I'm confused about the boundary treatment as it compares floating point numbers, which of course is subject to floating points errors.

This example illustrates the use of the line very well (omitting the line `_nx.copyto(ddmod, pi, where=(ddmod == -pi) & (dd > 0))`):
```py
>>> p = np.array([-np.pi, 0, np.pi])
>>> dd = np.diff(p)
>>> dd
array([3.14159265, 3.14159265])
>>> ddmod = np.mod(dd + np.pi, 2*np.pi) - np.pi
>>> ddmod
array([-3.14159265, -3.14159265])
>>> ph_correct = ddmod - dd
>>> ph_correct
array([-6.28318531, -6.28318531])
>>> up = np.array(p, copy=True, dtype='d')
>>> up[1:] = p[1:] + ph_correct.cumsum()
>>> up
array([-3.14159265, -6.28318531, -9.42477796])
>>>
```
