### ISSUE TITLE
`random.randint` returns value lesser than lower bound for some values of the seed.

### ISSUE THREAD

**Issue by vnherdeiro** [numpy/numpy#14889]
I spotted this bug in numpy 1.17.2

```python
np.random.seed(41)
np.random.randint(low=10,)
```
returns `0`, less than the lower bound set to 10. This bug is propagating in [pyod](https://github.com/yzhao062/pyod) 

See https://github.com/yzhao062/pyod/issues/141

**Comment by vnherdeiro** [comment]
Edit: typo in title

**Comment by eric-wieser** [comment]
From the docs:
```
Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
```

This is as expected

**Comment by vnherdeiro** [comment]
Ok, noted. Thanks for the prompt answer. I find it misleading when reading the code `randint(low=X)`, but I guess there are other motivations to keep it like that.

**Comment by eric-wieser** [comment]
> I find it misleading when reading the code `randint(low=X)`

Me too. I would strongly recommend not writing that code, and writing it as `randint(X)` instead.

**Comment by charris** [comment]
I wonder if we should issue a warning in this situation.

**Comment by eric-wieser** [comment]
It's hard to catch without creating an even more confusing signature. One option is:
```python
def randint(*args, **kwargs):
    def randint(low, high=None, size=None, dtype='l'):
        return low, high, size, dtype
    low, high, size, dtype = randint(*args, **kwargs)  # parse and produce an appropriate error
    if {'low', 'high'} & set(kwargs):
        deprecation_warning("pass positionally only")
     # rest as before
```
