### ISSUE TITLE
ImportError: Unable to import required dependencies: numpy: 

### ISSUE THREAD

**Issue by spiralulam** [numpy/numpy#14888]
I did install Python 3.7 using miniconda. After that I tried to import pandas and got the error message shoen below. And I did uninstall and reinstall numpy using conda. Further, I checked PATH and PYTHONPATH as well as the path to python.exe. Everything seems fine. Operating system is Windows 10.

### Error message:

Traceback (most recent call last):
  File "C:/01_Initiatives/ap-inventory-reduction/invred/main.py", line 1, in <module>
    from invred.analysis import Analysis
  File "C:\01_Initiatives\ap-inventory-reduction\invred\__init__.py", line 1, in <module>
    from invred.analysis import *
  File "C:\01_Initiatives\ap-inventory-reduction\invred\analysis.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\SudermN\AppData\Local\Continuum\miniconda3\envs\ap-inv-red\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\SudermN\AppData\Local\Continuum\miniconda3\envs\ap-inv-red\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Das angegebene Modul wurde nicht gefunden.

### Numpy/Python version information:

Python 3.7.5
Numpy 1.17.3
Pandas 0.25.2

**Comment by spiralulam** [comment]
And I did uninstall and reinstall numpy using conda. Further, I checked PATH and PYTHONPATH as well as the path to python.exe. Everything seems fine.

**Comment by rossbar** [comment]
If this is still an issue, please check out [this troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html) for tips on how to resolve this problem.

Closing for now due to inactivity. If the issue persists and the troubleshooting guide doesn't help, please open a new issue with current info about the system and installation method.
