### ISSUE TITLE
Numpy FFTs return data types don't match input data types

### ISSUE THREAD

**Issue by carterbox** [numpy/numpy#14892]
Unlike other functions, the NumPy FFT functions do not return arrays whose data types match the input arrays. Instead, `complex64` is promoted to `complex128`.

### Reproducing code example:

```python
import sys
import numpy as np

print(np.__version__, sys.version)

input = np.ones((5, 5), dtype='complex64')

output = np.square(input)
assert output.dtype == 'complex64', f"{output.dtype} square"  # assert passes

output = np.fft.fft2(input)
assert output.dtype == 'complex64', f"{output.dtype} fft"  # assert fails
```

### Numpy/Python version information:

1.17.3 3.8.0 | packaged by conda-forge | (default, Nov  6 2019, 23:20:36) 
[GCC 7.3.0]

**Comment by charris** [comment]
You need SciPy to get support for float32/complex64.

**Comment by carterbox** [comment]
I'm going to open a pull-request with an addition to the documentation page noting that `numpy.fft` is inconsistent with other NumPy functions because it promotes `float32/complex64` arrays to `float64/complex128` arrays.
