### ISSUE TITLE
use travis to enable CI on s390x

### ISSUE THREAD

**Issue by mwhudson** [numpy/numpy#14904]
In the discussion on https://github.com/numpy/numpy/pull/14769 we bemoaned the fact that there was no easy way to run CI on a big endian system. Well, now there is: https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z. I haven't tried this myself and I don't know how bad the capacity limits are in practice but: worth a try?

**Comment by WarrenWeckesser** [comment]
> worth a try?

Certainly!  Is it as simple as adding a couple lines to the existing `.travis.yml`?

**Comment by hugovk** [comment]
Yes! 

That blog lists NumPy under "Some examples of build jobs using IBM Power CPU architecture can be found here:" 

https://travis-ci.com/akhileshbhople/numpy

:)

**Comment by charris** [comment]
That example seems to come from the current NumPy `travis.yml` file.

**Comment by charris** [comment]
Seems to work https://travis-ci.org/numpy/numpy/builds/612072427?utm_source=github_status&utm_medium=notification .

**Comment by charris** [comment]
Try with `arm64` as well. I think we should be able to get 10 parallel jobs but not sure how.
