### ISSUE TITLE
Importing the numpy c-extensions failed

### ISSUE THREAD

**Issue by Ramimashkouk** [numpy/numpy#14910]
### Importing the numpy c-extensions failed
I installed _python 3.7_ on my windows system to work on _**visual studio code**_. Everything was going well, including using the libraries.
I uninstalled python using the _uninstalling program tool in control panel_. And installed _**Miniconda 3**_.
I checked that everything works well, and then installed the numpy library using `conda install numpy` in my terminal _**GitBash**_ on **_windows 10_**, then checked it on my visial studio code, but it failed to start.
### Reproducing code example:

```python
import numpy as np
A = np.array([[-1], [7], [-26]])
```

### Error message:

> Traceback (most recent call last):
>   File "C:\Users\ramim\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
>     from . import multiarray
>   File "C:\Users\ramim\Miniconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
>     from . import overrides
>   File "C:\Users\ramim\Miniconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
>     from numpy.core._multiarray_umath import (
> ImportError: DLL load failed: Не найден указанный модуль.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:/Users/ramim/Desktop/22/Matrix library/alsf.py", line 3, in <module>
>     import numpy as np
>   File "C:\Users\ramim\Miniconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
>     from . import core
>   File "C:\Users\ramim\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
>     raise ImportError(msg)
> ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy c-extensions failed.
> - Try uninstalling and reinstalling numpy.
> - If you have already done that, then:
>   1. Check that you expected to use Python3.7 from "C:\Users\ramim\Miniconda3\python.exe",
>      and that you have no directories in your PATH or PYTHONPATH that can
>      interfere with the Python and numpy version "1.17.3" you're trying to use.
>   2. If (1) looks fine, you can open a new issue at
>      https://github.com/numpy/numpy/issues.  Please include details on:
>      - how you installed Python
>      - how you installed numpy
>      - your operating system
>      - whether or not you have multiple versions of Python installed
>      - if you built from source, your compiler versions and ideally a build log
> 
> - If you're working with a numpy git repository, try `git clean -xdf`
>   (removes all files not under version control) and rebuild numpy.
> 
> Note: this error has many possible causes, so please don't comment on
> an existing issue about this - open a new one instead.
> 
> Original error was: DLL load failed: Не найден указанный модуль.
> 

### Numpy/Python version information:

Python 3.7.5
Numpy 1.17.3

I tried to uninstall and install the numpy library again, but it was useless. Note: when I type in the teminal conda install numpy, it says:

> All requested packages already installed

That's how I checked if numpy is really installed!

_**_How to solve that?_**_

**Comment by haoqg** [comment]
解决了吗？我也碰到同样的问题了

**Comment by mattip** [comment]
Shouldn't the bash python environment and the windows python environment be separate?

**Comment by Ramimashkouk** [comment]
@mattip 
Could you explain more what do you mean?

**Comment by mattip** [comment]
> I checked that everything works well, and then installed the numpy library using conda install numpy in my terminal GitBash on windows 10

How dd you check that everything works? Also via the GitBash terminal? It seems you might be mixing things together. I think GitBash is a cygwin-based terminal, not a pure windows one, so it may be using a different set of python/conda environments than the one you checked things with originally. Of course I may be totally off target since we have been getting numerous reports of people having problems with conda and windows.

**Comment by Ramimashkouk** [comment]
Actually, everything works well, including _numpy_, in the GitBash terminal. But when it comes to _visual studio code_ or to _windows CMD_, python itself works well, but import any library like `import numpy` or `import pandas` fails.

**Comment by kzy77** [comment]
I have two python environment,I think is this reason?

**Comment by Ramimashkouk** [comment]
Nothing I tried had worked.
I've uninstalled the whole Mininconda and installed the normal python for Visual Studio Code.
And for my desire to work on Gitbash and Miniconda, I installed Linux, beside the windows, and the miniconda as well ))

**Comment by Htleah** [comment]
Python 3.7.2 
Numpy 1.18.1
In PyCharm
In my virtual environment, I use this code:
conda install -c intel mkl-service
the error disappear.
