### ISSUE TITLE
Equality between arrays of shape(1,) and shape(0,)

### ISSUE THREAD

**Issue by DevinShanahan** [numpy/numpy#14916]
I expect a single boolean output when comparing equality of arrays that have different shapes and I expect a numpy array of boolean values when the arrays have the same shape, assuming they have the same dtype.  However, this is not the case between an array of shape(1,) and an array of shape(0,).
### Reproducing code example:
```python
import numpy as np

x1 = np.array([1, 2])
y1 = np.array([])
eq1 = x1 == y1
assert eq1 is False

x2 = np.array([1, 2])
y2 = np.array([1, 3])
eq2 = x2 == y2
assert isinstance(eq2, np.ndarray)

x3 = np.array([1])
y3 = np.array([])
eq3 = x3 == y3
assert eq3 is False
```

### Error message:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-129-bb191fde4bab> in <module>
     14 y3 = np.array([])
     15 eq3 = x3 == y3
---> 16 assert eq3 is False

AssertionError:
```
### Numpy/Python version information:

Numpy: 1.17.3
Python: 3.6.8

**Comment by eric-wieser** [comment]
> I expect a single boolean output when comparing equality of arrays that have different shapes

While this happens, it emits:
```
DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
```

In future it will error.

What you're seeing is that when you compare a `(1,)` array to an `(N,)` array, you get broadcasting, comparing each element of the `(N,)` array to the single item in the `(1,)` array and producing an `(N,)` result.

In your particular case, N is zero, so the result is also an empty array.
