### ISSUE TITLE
Supporting `__array_function__` on `ascontiguousarray` and `asfortranarray`

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#14911]
Currently it appears `array` is called to construct new arrays internally in [`ascontiguousarray`]( https://github.com/numpy/numpy/blob/cf704e7f245e89c623bd82cbdba7c2dd07cf5fb4/numpy/core/_asarray.py#L179 ) and [`asfortranarray`]( https://github.com/numpy/numpy/blob/cf704e7f245e89c623bd82cbdba7c2dd07cf5fb4/numpy/core/_asarray.py#L220 ). This causes issues if these functions are called on something that is not a NumPy array. It would be useful to instead have these be dispatchable on array type to allow the appropriate kind of array to be created should that be needed. Alternatively it might be nice to rewrite these to use the `reshape` method, which would also allow the array type to be taken into account.

cc @pentschev @mrocklin

**Comment by rgommers** [comment]
That makes sense I think. Those functions take an `array_like` as first parameter, so they should have had a dispatcher added by design. @shoyer did you leave these out on purpose, or was it an oversight?

**Comment by jakirkham** [comment]
FWIW we might be able to rewrite them slightly to get the intended behavior as well. This seems to work for Fortran ordered (unless I'm missing something). C order should be similar.

```python
np.atleast_1d(a.astype(a.dtype, order="F", copy=False))
```

Side note: I like that we now have a label for these kinds of issues. 😄

**Comment by shoyer** [comment]
I did intentionally omit these from `__array_function__`, under the theory that these were routines for explicitly creating NumPy arrays.

**Comment by rgommers** [comment]
Hmm yeah, that's true, sort of. They're probably mostly used with array rather than sequence input to guarantee C/Fortran ordering, but it's a thin wrapper around `np.array`.

@jakirkham your example will break sequence input.

**Comment by jakirkham** [comment]
I would have assumed people use the array constructor for that. Generally I see users calling this on existing arrays where they want to enforce a constraint on the data layout.

Well we could flip the order of operations. That said, I’m not normally seeing this called on `list`s.

**Comment by seberg** [comment]
The `like=` argument has been introduced, so this is supported now.
