### ISSUE TITLE
The function np.power has alittle issue

### ISSUE THREAD

**Issue by qiezikuangge** [numpy/numpy#14913]
When I use `np.power(-1, 1/3)`, it gives return a warning:

    invalid value encountered in power

But we know $(-1)_(1/3)=-1$

**Comment by mreineck** [comment]
I expect this happens because the result of the Python operation "1/3" is not exactly the same number as the mathematical fraction "1/3". Floating point numbers only have finite accuracy.

**Comment by matthew-brett** [comment]
I think this is because `np.power` doesn't like any negative number to a non-integer power.  I'm not sure why - it wasn't obvious from a quick read of the docs.  

For example `np.power(-1,  1/3)` gives `nan`, but `np.array(-1) ** (1/3)` gives -1.0.

**Comment by mreineck** [comment]
> For example np.power(-1, 1/3) gives nan, but np.array(-1) ** (1/3) gives -1.0.

That returns `NaN` for me as well (numpy 1.17.4, Python 3.7.5 on x86_64 Linux).

**Comment by eric-wieser** [comment]
Note that you get a non-nan result if you do the computation on complex numbers:
```
>>> np.power(-1j, 1/3)
(0.8660254037844387-0.49999999999999994j)
```

**Comment by seberg** [comment]
@matthew-brett which version of numpy gives -1 for the `**` operator? (just curious, 1.16 does not, but maybe there are/were special paths for certain roots).

Sounds to me like this is the correct result, especially since there are multiple solutions. Do we document anywhere which solution is chosen by the complex version?

**Comment by jeronimozc** [comment]
Has this moved anywhere? I was wondering about this. I just tried it on numpy 1.18.1, and still getting weird results.
```
>>> np.power(-1,1/3,dtype=np.complex)
(0.5000000000000001-0.8660254037844386j)
```
It doesn't seem to make much sense.

**Comment by eric-wieser** [comment]
@jeronimozc: that matches the behavior of `**` in python. If you want &1, use `np.cbrt`.

**Comment by jeronimozc** [comment]
OK, thanks! Sorry to comment further, but I am still looking for a) how to get other fractional powers with negative numbers (1/5, 1/7, ...), and b) is there documentation that explains why this is the behavior of `np.power` and `**`?

**Comment by eric-wieser** [comment]
@jeronimozc: numpy.power follows the behavior of `**` from Python (and I think the `cpow` function from C) so the question you're asking is no longer really about numpy.
