### ISSUE TITLE
`linspace(0, 2, 1, endpoint=False, retstep=True)` returns `nan` as a step

### ISSUE THREAD

**Issue by david-zwicker** [numpy/numpy#14927]
Calling
```python
import numpy as np
np.linspace(0, 2, 1, endpoint=False, retstep=True)
```
returns `(array([0.]), nan)`, whereas I think `(array([0.]), 2.)` would be a more consistent result.

Obviously, this is a slightly degenerated case, but it was the cause of a difficult to debug problem in my code base, which would have been avoided if linspace returned the suggest result.

The suggest result is a direct consequence of the calculations in the linspace function, where the following definitions are made
```python
delta = stop - start
div = (num - 1) if endpoint else num
step = delta / div
```
Note that the case `num == 1` has a hardcoded alternative path, which enforces `step = NaN`.

**Comment by seberg** [comment]
I think you are right, do you want to look into making a PR?

**Comment by david-zwicker** [comment]
I just open a pull request on this. There is only one line changed in the code (+ some a test).

**Comment by seberg** [comment]
Thanks, just for the fun of it: Small world, I used to be in the Luther group at MPIDS :).

**Comment by david-zwicker** [comment]
That's funny, but I'm not surprised since it's a great institute :)
