### ISSUE TITLE
"RuntimeWarning: numpy.ufunc size changed..." when numpy is used with other packages within a unittest

### ISSUE THREAD

**Issue by normanius** [numpy/numpy#14920]
When `numpy` is imported along with another package that makes use of `numpy`, I get a runtime warning that reads as follows:

```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
```

Strangely, this problem occurs only within a unittest TestCase. See below for how to reproduce the problem. I found several resources in the web referring to this warning. The "internet" seems to suggest to either ignore this warning or to update the versions of numpy or the other library involved, because it's an actual instance of "binary incompatibility". I currently tend to go for the first option.

What strikes me, however, is that the warning is issued only under the condition that the second package is imported from within a test case. I cannot reproduce this problem otherwise. Because of that "sometimes nature", I decided to drop a bug report here.

I can reproduce the problem with python3.6, python3.7 - but not with python3.8. Besides `scipy`, I used also other packages such as `pandas`, `seaborn` or `scikit-learn`, with the same result (the only difference being that the warning is sometimes issued multiple times).

Let me know if you think this issue is related rather to how unittests are executed in python.

### Reproducing code example:
```
import unittest
import numpy as np
# import scipy.io               # <=== If scipy import outside test, no warning

class Test(unittest.TestCase):
    def test(self):
        # import numpy as np    # <=== If numpy import within test, no warning
        import scipy.io
        pass

if __name__ == "__main__":
    unittest.main(verbosity=2)
```

If I A) import numpy within the test, or B) if I import scipy outside the test, no warning is issued. How comes?

### Numpy/Python version information:

Numpy: 1.17.4

- **(reproducible)** Python 3.7.5 (v3.7.5:5c02a39a0b, Oct 14 2019, 18:49:57)   
- **(reproducible)** Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31)  
- **(not reproducible)** Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)  

(Scipy: 1.3.2)
(pandas: 0.25.1)
(seaborn: 0.9.0)
(sklearn: 0.21.3)

System: MacOS 10.14.5

**Comment by charris** [comment]
This is usually issued when code compiled with one version of NumPy is run with another. NumPy occasionally changes the size of structures at the C level, but does so in a way that should be forward compatible, i.e., extensions compiled against an older NumPy can be run with a newer version that may have larger structures. The other way round doesn't go. The check is made by Cython generated code and the exact behavior depends on the Cython version used and the version of NumPy used when the code was generated. It is also possible that unittest is changing the warnings allowed in some way. The precise problem here is hard to diagnose from the provided information.

**Comment by normanius** [comment]
Many thanks for the explanations. This is useful in understanding the cause of the warning. 

Can you reproduce the problem on your end with the minimal reproducing example? (I added the version of the other packages, and the system in the description above).

I acquired python as Framework from python.org, and I'm installing packages through `pip` - hoping that the package manager ensures compatibility. Do you think it's better to report the issue to the [pypa guys](https://github.com/pypa/pip/issues)?

Or do you think it's a possibility that unittest is causing the inconsistent behavior? In that case, I would place an issue in the [python bug tracker](https://bugs.python.org/).

**Comment by charris** [comment]
I can't track this down without a lot of work. Where did you get your NumPy?

**Comment by normanius** [comment]
`pip install numpy`, like all other packages I'm using.

**Comment by normanius** [comment]
If it's a matter of versions and package manager, feel free to close the issue. 

I thought it would be good for you to know about this. But as far as I can see, you are aware about these things, and can't do anything about it.

**Comment by rgommers** [comment]
> If it's a matter of versions and package manager, feel free to close the issue.

It's that, plus warning filters that may be reset by `unittest` or `pytest` perhaps (we have a filter for this warning in `__init__.py`). There's nothing we can do about it, and it doesn't seem like a pressing problem, so closing. Thanks @normanius

**Comment by normanius** [comment]
As for `__init__.py`, yes, in deed, warnings are filtered there: [lines 191ff](https://github.com/numpy/numpy/blob/b2b45fe9b65db490b84e90fea587c5bb867906eb/numpy/__init__.py#L191-L194)

And it's also true that [unittest](https://github.com/python/cpython/tree/master/Lib/unittest) is fiddling around a lot with warnings, naturally. So, now it's much clearer to me what's going on. 

Thanks for the support!
