### ISSUE TITLE
QR raw unexpected layout

### ISSUE THREAD

**Issue by johnc1231** [numpy/numpy#14953]
I do not get the output I expect from doing numpy qr when `mode = 'raw'`

### Reproducing code example:

```python
import numpy as np
print(np.linalg.qr(np.arange(9).reshape((3, 3)), mode="raw"))
print(np.linalg.qr(np.arange(9).reshape((3, 3)), mode="r"))
```

The output of the above looks like

```(array([[-6.70820393e+00,  4.47213595e-01,  8.94427191e-01],
       [-8.04984472e+00,  1.09544512e+00,  9.57790092e-01],
       [-9.39148551e+00,  2.19089023e+00, -8.88178420e-16]]), array([1.        , 1.04309992, 0.        ]))

[[-6.70820393e+00 -8.04984472e+00 -9.39148551e+00]
 [ 0.00000000e+00  1.09544512e+00  2.19089023e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
```

What is surprising here is that in the raw output, the first ndarray has the `R` matrix encoded in its lower triangle. Based on description of `dgeqrf` in LAPACK (http://www.netlib.org/lapack/explore-html/df/dc5/group__variants_g_ecomputational_ga3766ea903391b5cf9008132f7440ec7b.html) and the fact that R is an upper triangular matrix, I'd expect the raw output to have `R` in the upper triangle. If the current behavior is the intended behavior, we probably ought to document what the output of raw will look like. 

### Numpy/Python version information:

1.17.1 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by seberg** [comment]
@johnc1231 can you have a look at whether or not the Notes section explains this in enough detail? Otherwise maybe point out what is missing to the documentation?

**Comment by johnc1231** [comment]
Agh, under the mode parameter it does say "note, h is transposed for calling fortran". So I guess that's documented behavior. I guess I thought that just meant it was stored in Fortran format internally, not that the matrix was transposed and stored in C format.
