### ISSUE TITLE
numpy.unique gives wrong output for list of sets

### ISSUE THREAD

**Issue by rashidrafeek** [numpy/numpy#14956]
The `numpy.unique` function gives wrong output for a list of sets.

```python
>>> import numpy as np
>>> sets1 = [{1},{2},{1}]
>>> np.unique(sets1)
array([{1}, {2}, {1}], dtype=object)
```
But this doesn't occur if the unique elments are adjacent.
```python
>>> sets2 = [{2},{1},{1}]
>>> np.unique(sets2)
array([{2}, {1}], dtype=object)
```

I understand that this is because `numpy.sort` can't sort a list of sets. But isn't the `numpy.unique` meant to work for a list of sets?

### Numpy/Python version information:

1.17.2 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0]

**Comment by mattip** [comment]
I think you have answered your own question: since sets can only be compared for equality and not for greater-than or less-than, `unique` cannot work on lists of sets. 

Closing. If there is more to say on this, please reopen.
