### ISSUE TITLE
Memory leak when using np.conjugate() on sparse matrices.

### ISSUE THREAD

**Issue by jag0nzalez** [numpy/numpy#14950]
When using numpy.conjugate() on sparse matrices the memory usage keeps increasing.
This bug can't be reproduced with $(sparse_matrix).conjugate()

#### Check RAM usage when testing this:
```python
import numpy as np
from scipy import sparse
cm = sparse.csr_matrix(np.array([1+1*1j, 2+2*1j, 3+3*1j, 4+4*1j]))

def leak_test():
    np.conjugate(cm)

while True:
    leak_test()
```
#### This code isn't affected:
```python
import numpy as np
from scipy import sparse
cm = sparse.csr_matrix(np.array([1+1*1j, 2+2*1j, 3+3*1j, 4+4*1j]))

def test():
    cm.conjugate()

while True:
    test()
```

### Numpy/Python version information:

```
1.17.4 3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0]
```

**Comment by seberg** [comment]
Cannot reproduce on 1.16.4 (and have to update scipy probably). Which scipy version are you using, I think it is likely that this is an issue in scipy and not numpy.

**Comment by jag0nzalez** [comment]
Scipy version is:
```
1.3.1 3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0]
```

**Comment by jhmenke** [comment]
> Cannot reproduce on 1.16.4 (and have to update scipy probably). Which scipy version are you using, I think it is likely that this is an issue in scipy and not numpy.

I also had issues with memory leaking in sparse matrices, exclusively in 1.17. Downgrading to 1.16 "solved" it.

**Comment by seberg** [comment]
@jhmenke thanks, I will try to reproduce then. I suppose the easiest way to track it down may be to bisect the commit that made it start. If it is indeed `conjugate` it may be that it happens for all ufuncs (effectively, pretty much all math functions). That should leak quite often.

**Comment by seberg** [comment]
Hmmm, I cannot reproduce it on NumPy Master with SciPy 1.2 or SciPy 1.3.3. Could you also try upgrading SciPy? (And checking the exact SciPy versions?).

**Comment by jhmenke** [comment]
> If it is indeed `conjugate` it may be that it happens for all ufuncs (effectively, pretty much all math functions). That should leak quite often.

It did, 32 GB of memory were full within a few hours where memory footprint should be constant at a few GB.

I will try to replicate it and send you the software versions i used.

**Comment by jhmenke** [comment]
I was using scipy 1.3.1 and numpy 1.17.2 when the error occured.

**Comment by jhmenke** [comment]
Okay so i updated numpy to 1.17.4 and scipy to 1.3.3 and could not replicate the OP issue. However, with that versions my code is still rapidly leaking memory.

So i downgraded only numpy to 1.16.0 while scipy is still 1.3.3 and i am seeing constant memory use like it should be.

The code does a lot of math computations, e.g., calling functions in this file repeatedly (thousands of times): https://github.com/e2nIEE/pandapower/blob/develop/pandapower/pypower/dSbr_dV.py

Not really sure how to create a minimal example though.

**Comment by seberg** [comment]
Any chance you can try NumPy 1.16.x together with SciPy 1.3.1 to narrow down if its mainly SciPy? I tried to search the scipy issue tracker, but found no reference to such a leak quickly.

To be honest, tracking down memory leaks like this is a bit tricky. There is the line memory profiler, but I doubt it is useful. The most useful thing might be to manually bisect the code. I.e. delete half of it and if it persits, delete another half until you are left with hopefully one line of code that is enough to reproduce. If it is for example ufuncs, it could be that half the lines show the leak...

**Comment by jag0nzalez** [comment]
I tried with NumPy 1.16.5 and SciPy 1.3.1 but I couldn't reproduce it.
I did a git bisect and found that it happens since 33bbcf5ad1be03b68e0d9c4876a0d6dc3708e3ca.

**Comment by eric-wieser** [comment]
Nice find. It's a missing Py_DECREF(func) I think.

**Comment by mattip** [comment]
Thanks @jag0nzalez for bisecting this down. Can you check that latest HEAD fixes the issue?

**Comment by jag0nzalez** [comment]
Yes @mattip , it's fixed now!
