### ISSUE TITLE
On import: "undefined symbol: PyModule_Create2"

### ISSUE THREAD

**Issue by musbur** [numpy/numpy#14958]
### Reproducing code example:
```
$ python
Python 3.6.8 (default, Nov 22 2019, 11:16:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
[...] (see below for full stack trace)
```
This is happening in a freshly built Python 3.6.8 installation (with -DPy_DEBUG) in a newly set-up virtualenv. I have another virtualenv using the same Python version that came with the system, and there I could install and import numpy just fine. See below on the "pip" call.

```
$ which python
/usr/local/python_debug/env/bin/python

$ echo $PATH
/usr/local/python_debug/env/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/dh/.local/bin
$ echo $PYTHONPATH

$

$ pip install numpy
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/d2/ab/43e678759326f728de861edbef34b8e2ad1b1490505f20e0d1f0716c3bf4/numpy-1.17.4-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.17.4
$


```

### Error message:

Traceback (most recent call last):
  File "/usr/local/python_debug/env/lib/python3.6/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/local/python_debug/env/lib/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/local/python_debug/env/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /usr/local/python_debug/env/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyModule_Create2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python_debug/env/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/python_debug/env/lib/python3.6/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/usr/local/python_debug/env/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /usr/local/python_debug/env/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyModule_Create2

### Numpy/Python version information:

Python 3.6.8 (default, Nov 22 2019, 11:16:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux

**Comment by seberg** [comment]
You can try `python -mpip install numpy`. It is installing a wheel for you, so I expect pip is still pointing to the system python/pip.

**Comment by musbur** [comment]
Somehow the issue went away but I don't know what I did differently, thanks!
