### ISSUE TITLE
Nested structured arrays do not allow natural, unobscured indexing

### ISSUE THREAD

**Issue by smax1** [numpy/numpy#14964]
If we nest structured arrays, they do not allow natural and unobscured indexing. One has to resort to explicit zero-rank to scalar reductions, greatly impacting readability and intent of the code.

Worse, for rec.arrays even 'zero-rank index padding' trick does not work as shown in example below.

Interestingly, common operations (e.g. + for numbers or concat for strings) when applied to zero-order results produce the scalars.

```python
# Edit: tried with python 3.7.5, numpy 1.17.3

import numpy as np

a1 = np.array((1,'str2', \
          np.array((3,'str4', \
              np.array((5,'str6','str7'),dtype=[('a3','O'),('b3','O'),('c3','O')]) \
          ),dtype=[('a2','O'),('b2','O'),('c2','O')]) \
     ),dtype=[('a1','O'),('b1','O'),('c1','O')])

# Works but cumbersome:
a1['c1'][()]['c2'][()]['c3']
# Probably intended, but does not work:
a1['c1']['c2']['c3']

b1 = np.rec.array((1,'str2', \
          np.rec.array((3,'str4', \
              np.rec.array((5,'str6','str7'),dtype=[('a3','O'),('b3','O'),('c3','O')]) \
          ),dtype=[('a2','O'),('b2','O'),('c2','O')]) \
     ),dtype=[('a1','O'),('b1','O'),('c1','O')])
# Can not get this working neither the (possibly) intended way:
b1.c1.c2.c3

# ..., nor with zero-rank indexing padding:
b1.c1[()].c2[()].c3

```

**Comment by eric-wieser** [comment]
The underlying issue here is you are using structures with objects holding nested arrays, not literally nested structures. Will expand on that remark when I have time.

**Comment by eric-wieser** [comment]
```
b1 = np.array((
	1,'str2',(
		3, 'str4', (
			5, 'str6', 'str7'
		)
    )
), dtype=[
	('a1','O'), ('b1','O'), ('c1', [
		('a2','O'),('b2','O'),('c2', [
			('a3','O'),('b3','O'),('c3','O')
		])
	])
]).view(np.recarray)
```
makes it work
```
>>> b1.c1.c2.c3
array('str7', dtype=object)
```

**Comment by seberg** [comment]
Please check Erics suggestion. Indexing fields alwyas returns an array of the same shape. Changing that would be problematic (it basically would be guessing your intention, and others may have different needs/intentions).
Making the explicit full (single) dtype solves this issue (although I suppose it may come with its own issues).

**Comment by smax1** [comment]
Thank you for the replies and the example. Could you clarify the following points, please?

1. My immediate need is easy use of scipy.io.loadmat result. It returns nested arrays for nested Matlab structs. Is there a an easy, idiomatic way for un-nesting the nested arrays?

2. Indexing a field today always returns a rank-zero array. But if we apply an operation to that rank-zero array (e.g. +0 to a number or +'' to a string) the operation returns a scalar, not rank-zero array. This appears to be an inconsistency. To maintain the "need/intention", the ops should not strip the rank-zero array.

3. Is there a way to add attribute access overload to rank-zero array that would forward to the contained scalar? Would it break any existing test cases?

**Comment by seberg** [comment]
> Thank you for the replies and the example. Could you clarify the following points, please?
> 
> 1. My immediate need is easy use of scipy.io.loadmat result. It returns nested arrays for nested Matlab structs. Is there a an easy, idiomatic way for un-nesting the nested arrays?

I would suggest writing a custom recursive function. That probably is fairly straight forward. I cannot immediately think of a function that would already do it for you.

> 2. Indexing a field today always returns a rank-zero array. But if we apply an operation to that rank-zero array (e.g. +0 to a number or +'' to a string) the operation returns a scalar, not rank-zero array. This appears to be an inconsistency. To maintain the "need/intention", the ops should not strip the rank-zero array.

Yes, this is an unfortunate general behaviour of NumPy. I would love to fix it, but it is a longstanding issue and behaviour. I think the history is that for anything but object arrays, it is not such a big problem and it speeds up many operations quite a bit.

> 3. Is there a way to add attribute access overload to rank-zero array that would forward to the contained scalar? Would it break any existing test cases?

I am not quite sure what you mean by this. You can get the scalar with `arr[()]`, you can get a python object (not quite the same thing) with `arr.item()`. I do not think we want to dabble into forwarding attribute access. One thing that could work is to use `np.frompyfunc(lambda x: getattr(x, "attribute"))` and use the (vectorized) function. But it would be slow on scalars.

**Comment by eric-wieser** [comment]
> It returns nested arrays for nested Matlab structs. Is there a an easy, idiomatic way for un-nesting the nested arrays?

Can you give some example matlab code for constructing such a struct?

**Comment by smax1** [comment]
My pleasure. Here is the Matlab example:

```
s11 = struct('a',1,'b',[1 2 3]);
s12 = struct('a',[4 5 6 7]','b',2);
s21 = struct('a',[8 9],'b',1);
s22 = struct('a',2,'b',[3 2 1]);
s31 = struct('a',[5 4 7; 1 3 2],'b',1);
s32 = struct('a',3,'b',[1 2; 3 7; 5 6]);
sa2 = [s11 s12; s21 s22; s31 s32];
sca2 = {s11 s12; s21 s22; s31 s32};
ss1 = struct('a',s11,'b',s12);
sss1 = struct('b',s21,'c',s22,'d',ss1);

s11 = struct('a',1,'b',[1 2 3]);
s12 = struct('b',[4 5 6 7]','c',2);
s21 = struct('c',[8 9],'d',1);
s22 = struct('d',2,'e',[3 2 1]);
s31 = struct('e',[5 4 7; 1 3 2],'f',1);
s32 = struct('f',3,'g',[1 2; 3 7; 5 6]);
sca22 = {s11 s12; s21 s22; s31 s32}';

conf0 = struct_dupf( ...
'fun1',@rand, ...
'a',1,'b',[7 5 3; 2 3 1],'c',[7 5 3; 2 3 1]', ...
'a1',[1 2 3],'a2',[4 5 6]', ...
'sa2',sa2,'sca2',sca2,'ss1',ss1,'sss1',sss1,'sca22',sca22);

save scipy_io_test1 conf0 sa2 sca2 sca22 s11 s12 s21 s22 s31 s32 ss1 sss1
```
And the python counterpart:

```
# We are interested to reach into tr['conf0']
import scipy.io as sio
tr = sio.loadmat('scipy_io_test1',squeeze_me=True)
```

**Comment by eric-wieser** [comment]
Ah, so your structs are non-uniform, meaning you won't be able to unpack them into anything but an object array. This perhaps looks like a `scipy.io` feature request now - these lines are causing your pain:

https://github.com/scipy/scipy/blob/e7d5dd4a77a2c330a467fde773e267d5cbb90f13/scipy/io/matlab/mio_utils.pyx#L19-L21

**Comment by smax1** [comment]
Regardless if structures are uniform or not, squeeze_me=True seems to do its job correctly -- it removes all singleton dimensions.

Even if the arrays of structures were uniform, 
```
sa2 = struct('a',{1,2,3},'b',{3,4,5});
sca2 = num2cell(sa2);
conf2 = struct('sa2',{sa2},'sca2',{sca2},'c',struct('d',1));
save scipy_io_test2 conf2
```
it is reaching into the nested scalar that causes the inconvenience:

```
import scipy.io as sio
tr = sio.loadmat('scipy_io_test2',squeeze_me=True)
conf2 = tr['conf2']
conf2['c'][()]['d']
``` 

So I was wondering if returning a scalar for an object field access is not feasible and rank-zero array is a must, would it be possible to overload __getitem__ operator of the array so that field access is forwarded to the contained object?

**Comment by eric-wieser** [comment]
The line I point to there is `squeeze_me` being deliberately ignored _because_ you have a structured type. It's not at all clear to me that's sensible behavior.

**Comment by smax1** [comment]
The referenced code 
https://github.com/scipy/scipy/blob/e7d5dd4a77a2c330a467fde773e267d5cbb90f13/scipy/io/matlab/mio_utils.pyx#L19-L21

seems to make sense. For example:
```
c = array((3, array((2, array((1, 'str2'), dtype=[('a', 'O'), ('b', 'O')])),
      dtype=[('c', 'O'), ('d', 'O')]), array((1, 'str2'), dtype=[('a', 'O'), ('b', 'O')])),
      dtype=[('e', 'O'), ('f', 'O'), ('g', 'O')])
c.ndim
c.dtype.kind
c.item()
```

Produces this:
```
In [60]: c = array((3, array((2, array((1, 'str2'), dtype=[('a', 'O'), ('b', 'O')])),
    ...:       dtype=[('c', 'O'), ('d', 'O')]), array((1, 'str2'), dtype=[('a', 'O'), ('b', 'O')])),
    ...:       dtype=[('e', 'O'), ('f', 'O'), ('g', 'O')])
In [61]: c.ndim
Out[61]: 0
In [62]: c.dtype.kind
Out[62]: 'V'
In [63]: c.item()
Out[63]: (3, array((2, array((1, 'str2'), dtype=[('a', 'O'), ('b', 'O')])),
       dtype=[('c', 'O'), ('d', 'O')]), array((1, 'str2'), dtype=[('a', 'O'), ('b', 'O')]))
```
-- which strips one layer of field type information, returning a tuple. This is not likely to be intended by squeeze_element.

I see no problem with the nested arrays returned by scipy.io.loadmat. It is accessing into these nested arrays which is cumbersome.

**Comment by eric-wieser** [comment]
Ah, you're quite right, `void.item()` does return a tuple.

In that case, the fix is marginally more involved: https://github.com/scipy/scipy/pull/11165
