### ISSUE TITLE
DOC: add proper docstrings and documentation to refguide-check

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#14961]
`tools/refguide-check.py` needs work documenting the functions. xref gh-14732.

This file is not shipped with NumPy and does not appear on the numpy.org website, but still should be properly documented.

**Comment by san7988** [comment]
Hi,

is this complete?

Thanks

**Comment by eric-wieser** [comment]
Unless you can see a PR linked either in a comment or a cross reference, then a safe assumption is to assume not. 

So no, this still needs doing :)

**Comment by san7988** [comment]
Sorry but I'm a newbie to OS so please bear with me.
I went through issue #14732 to understand the issue more.

I just wanted to understand this issue clearly so please help me with that.
The above mentioned file has some methods with docstrings and some without them. So we need to add documentation to methods missing docstrings. Is my understanding right?

Thanks

**Comment by mattip** [comment]
The idea is to use the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) docstring standard to document at least the higher-level functions: `main`, `check_items`, `check_rst`, `check_doctests`, and perhaps one level lower.

**Comment by san7988** [comment]
So if we take an example, in method `check_doctests` we have currently:
`def check_doctests(module, verbose, ns=None, dots=True, doctest_warnings=False):`
   ` """Check code in docstrings of the module's public symbols.`
`    Returns: list of [(item_name, success_flag, output), ...]`
  `  """`

should be something like:

`"""`
`Check code in docstrings of the module's public symbols.`

`Returns`
`--------`
`list of [(item_name, success_flag, output), ...]`
`"""`

Is that correct?

**Comment by mattip** [comment]
Correct, as well we should document the parameters

**Comment by san7988** [comment]
Cool. I'm on it.
Thanks

**Comment by san7988** [comment]
Hi,

I have done changes. Should I go ahead and create the PR?

**Comment by mattip** [comment]
Yes. Please take a look at the [developer workflow](https://numpy.org/devdocs/dev/development_workflow.html) around working with git and making a PR.
