### ISSUE TITLE
np.argsort() wrong result

### ISSUE THREAD

**Issue by mycstar** [numpy/numpy#14963]
### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mycstar** [comment]
bb = [12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12]
np.argsort(bb)
array([ 0, 14, 13, 12, 11, 10,  9, 15,  8,  6,  5,  4,  3,  2,  1,  7, 16])
big surprise, python 3.6, numpy version is 1.17, once bb length more than 15, the result will not make sense

**Comment by mycstar** [comment]
something wrong

**Comment by charris** [comment]
No. The result is correct in that the elements are correctly sorted if taken by the indices. You seem to be expecting the result of a stable sort, but that is not the default. Try `kind='mergesort').
