### ISSUE TITLE
Importing the numpy c-extensions failed

### ISSUE THREAD

**Issue by amajiration** [numpy/numpy#14968]
While trying to run tensorflow, I keep getting this message: "ImportError:  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!  Importing the numpy c-extensions failed." This was the video I used as a guide to set it up: https://www.youtube.com/watch?v=tPq6NIboLSc

**Comment by matthew-brett** [comment]
Did you see any advice on how to solve the issue, as the error message promises?

What did you try?

**Comment by eric-wieser** [comment]
Closing. Please read the advice that appears in the error message, and open a new issue with the information it asks for.
