### ISSUE TITLE
no scalar overflow RuntimeWarning in a specific case

### ISSUE THREAD

**Issue by opk12** [numpy/numpy#14971]
### Reproducing code example:

```python
import numpy as np
a = np.int64(2**62)

a * np.int64(2**10)
# 0
a * np.int64(3) == -a
# True

np.geterr()['over']
# 'warn'

# In fact, a * np.int64(2**20) warns:
# __main__:1: RuntimeWarning: overflow encountered in long_scalars
# 0
```

### Numpy/Python version information:

1.17.4 3.7.5 (default, Oct 17 2019, 12:16:48) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

Numpy from pip, Python from fedora 31 repo.

**Comment by mattip** [comment]
I do get a warning when running with `-Walways`
```python
$ python -Walways
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.int64(2**62)
>>> a * np.int(2**10)
__main__:1: RuntimeWarning: overflow encountered in long_scalars
0
>>> np.__version__
'1.18.0.dev0+e9452bf'
```

**Comment by opk12** [comment]
Sorry, I was not aware of -Walways and the reproducer statements were tested in a different order than the one posted above. Keep up with the good work, Python and numpy are awesome.
