### ISSUE TITLE
DOC, TST: check docstrings in doc/*rst files

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#14970]
We recently added the ability for refguide-check to test the `*.rst` files in `doc` and below. There are failures that should be fixed. Some hints to run the tests and find the broken docstrings:
- the docstrings much match the numpy version, so you should install it locally
- run the refguide-check `python tools/refguide-check.py --rst`

Currently for me this prints out many failures, the summary is below

* [x] doc/source/reference/maskedarray.baseclass.rst
* [x] doc/source/reference/arrays.ndarray.rst
* [x] doc/source/reference/routines.polynomials.classes.rst
* [x] doc/source/reference/arrays.datetime.rst (gh-15717)
* [x] doc/source/reference/arrays.nditer.rst
* [x] doc/source/reference/arrays.dtypes.rst
* [x] doc/source/reference/arrays.indexing.rst
* [x] doc/source/reference/distutils.rst
* [x] doc/source/reference/arrays.classes.rst
* [x] doc/source/reference/c-api/coremath.rst
* [x] doc/source/f2py/getting-started.rst
* [x] doc/source/user/c-info.python-as-glue.rst
* [x] doc/source/user/quickstart.rst (gh-15703)
* [x] doc/source/user/tutorial-svd.rst (gh-15710)
<details>

```
ERROR:  failed checking doc/source/reference/maskedarray.baseclass.rst
        failed checking doc/source/reference/arrays.ndarray.rst
        failed checking doc/source/reference/routines.polynomials.classes.rst
        failed checking doc/source/reference/arrays.datetime.rst
        failed checking doc/source/reference/arrays.nditer.rst
        failed checking doc/source/reference/arrays.dtypes.rst
        failed checking doc/source/reference/arrays.indexing.rst
        failed checking doc/source/reference/distutils.rst
        failed checking doc/source/reference/arrays.classes.rst
        failed checking doc/source/reference/c-api/coremath.rst
        failed checking doc/source/f2py/getting-started.rst
        failed checking doc/source/user/c-info.python-as-glue.rst
        failed checking doc/source/user/quickstart.rst
```

</details> 

When all the errors are fixed, we should enable this check on CI to make sure new errors do not crop up.

**Comment by Sriharsha-hatwar** [comment]
Was trying to run the command `python tools/refguide-check.py --rst` I got this : 
```
Traceback (most recent call last):
  File "tools/refguide_check.py", line 36, in <module>
    import docutils.core
ModuleNotFoundError: No module named 'docutils'
``` 
I am pretty sure that I installed in develop mode. do I need to raise an issue as its not installing `docutils` while installing in `develop` mode ?  

PS : I meant I have used `python setup.py develop`

**Comment by mattip** [comment]
It seems our documentation does not mention dependencies for building and testing docs. I think the minimum is (taken from the circleCI config file) `pip install cython sphinx==2.2.0 matplotlib ipython`. It would be good to add that somewhere.

**Comment by souvik3333** [comment]
Hi, I am getting this error.
```
Traceback (most recent call last):
  File "tools/refguide_check.py", line 51, in <module>
    from numpydoc.docscrape_sphinx import get_doc_object
ModuleNotFoundError: No module named 'numpydoc'
```
Did I miss something during install process?

**Comment by rgommers** [comment]
@souvik3333 for running `refguide_check` you will need to install the `numpydoc` package, it's a dependency

**Comment by tud111317** [comment]
For me, it also fails on `doc/source/user/absolute_beginners.rst`. I've started fixing that file.

**Comment by tud111317** [comment]
One of the errors comes from here:
```python
import pandas as pd
pd.read_csv('music.csv').values
x = pd.read_csv('music.csv', columns=['float_colname_1', ...]).values
```
It fails because 'music.csv' cannot be found. What would be a good approach to this? Creating a temporary file, using `StringIO` or something else?

**Comment by seberg** [comment]
I doubt we want to change the `music.txt` example, except possibly ignore the error. IMO `StringIO` is much too complicated to be useful here and it is OK that it does not actually execute.

**Comment by tud111317** [comment]
How about using `# doctest: +SKIP` to ignore such tests?

**Comment by pdebuyl** [comment]
It is also possible to include the datafile

**Comment by mattip** [comment]
In gh-15439 I created the file on-the-fly from data to match the image

**Comment by pdebuyl** [comment]
Typical sources of error:

- The `__repr__` seems to depend on the Python or NumPy version. There are changes in the display of commas and of a space around `=` signs. I did not investigate systematically what version of Python/NumPy produces what output as I hope that someone here will know better. The doctests cannot pass with all currently supported versions. Requires decision. Such as updating all the doctest outputs to match the current output.
- Erroneous multiline inputs. Easy to fix.
- Mismatch between `<type ...>` and `<class ...>` reprs. Requires decision.
- Missing imports. Easy to fix.
- Assumption that `from numpy import *` for some variables/functions that miss the `np.` prefix. Easy to fix.

I am willing to do the "easy" ones :-) and to apply decisions concerning the rest.

**Comment by eric-wieser** [comment]
Answering some of those

> The __repr__ seems to depend on the Python or NumPy version

The docs should always reflect the latest numpy version formatting. If there's a python-dependent issue, then please give a specific example

> Mismatch between <type ...> and <class ...> reprs. Requires decision.

`<type ...>` is leftover from python 2, we only support 3 now so our docs should use `<class ...>`

**Comment by pdebuyl** [comment]
I did not do a combinatorial test. From more manual testing, the change comes form the "formatting overhaul" in NumPy 1.14, with the exception of the "type <-> class" output.

I suggest to change everything then, is that ok @eric-wieser  ?

**Comment by eric-wieser** [comment]
I think that should be fine - but don't feel you need to fix everything all at once - fixing half of the rst files and getting the PR merged is better than half-fixing all of them and not finding the time to finish up :)

**Comment by pdebuyl** [comment]
Hi @eric-wieser 

There remain issues.

1. In the nditer page, I am not sure of the expected output of some doctests...
2. The cython and f2py examples would need a compilation step. Is that foreseen? I can manage cython and f2py fine but in the context of documentation builds it is of course a matter of organization.
3. In the datetime page, the deprecation warning is not seen by the doctest runner.
4. For distutils, the example does not run (it would involve actually having sources for an extension).

For 4, may I simply skip the two failing commands of distutils (due to missing `foo.c` file)?

**Comment by pdebuyl** [comment]
Ok, I file a new PR with only the consensual changes.

**Comment by tud111317** [comment]
`c-info.python-as-glue.rst` contains Fortran code that needs to be run with `f2py`. Should the subroutine be saved to a file on the fly, and `f2py` run with `subprocess`? Or just skip those tests?

**Comment by pdebuyl** [comment]
Regarding arrays.datetime.rst , the deprecation warning on line 390 does not show. I cannot find how to output the warning to the testrunner.

There is also an un-marked deprecation on line 102 about the datetime input with a timezone. pytest catches it but refguide_check.py does not complain.

**Comment by pdebuyl** [comment]
BUG: In https://numpy.org/devdocs/reference/arrays.indexing.html#boolean-array-indexing , in the "rowsum" example:

```
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1, keepdims=True)
rowsum.shape

x[rowsum <= 2, :]    # fails

x[rowsum <= 2]
```

The last two examples fail. For the one annotated with "fails", this is of course expected.

The last line results in

```
IndexError: boolean index did not match indexed array along dimension 1; dimension is 2 but corresponding boolean dimension is 1
```

I could find no reason for it not to fail. I actually find the example confusing and would suggest to simply remove it.

**Comment by seberg** [comment]
Interesting, this can be achieved more or less correctly if `keepdims` is not used, but boolean indexing currently does not broadcast. I had some discussion about it recently. When we add `.oindex`, and `.vindex`, we could in principle think about making boolean array indexing use broadcasting behaviour (i.e. the second one could work).

@pdebuyl updates/clarification in the docs are always appreciated!

**Comment by seberg** [comment]
Ah, right we should just delete that. It points out a caveat which has since been fixed by converting into an error.

**Comment by pdebuyl** [comment]
@seberg thanks for the reply, I filed a PR that fixes the minor issues with that file and deletes the outdated example #15694

**Comment by eric-wieser** [comment]
Only four files left according to https://github.com/numpy/numpy/pull/15703#discussion_r388123904

**Comment by pdebuyl** [comment]
Back to datetime.

- The example on line 102

        np.datetime64('2010-03-14T15Z') == np.datetime64('2010-03-14T15:00:00.00Z')

  can be deleted as it uses timezones which are deprecated.
- The example on line 389

       np.datetime64('2000-01-01T00:00:00-08')

  generates a deprecation warning that is not captured by the test runner.

For both examples, the solution is either to `# doctest: +SKIP` them or to capture the warning. I cannot make the latter option work though.

**Comment by pdebuyl** [comment]
Agree about line 102. I also removed the section about change with NumPy 1.11 but kept the sentence for information, in the first section.

> For backwards compatibility, datetime64 still parses timezone offsets,
> which it handles by converting to UTC. However, the resulting datetime
> is timezone naive.

PR coming.

**Comment by pdebuyl** [comment]
The remaining failures are:

```
ERROR:  failed checking doc/source/reference/arrays.nditer.rst
        failed checking doc/source/user/c-info.python-as-glue.rst
        failed checking doc/source/f2py/getting-started.rst
```

For these files, one needs to build extension modules. As the test runner uses a temporary workdirectory, the steps are:

1. copy relevant source file
2. build at run time

This is not straightforward with the current setup. For "1", either the files exist and are "literalinclude"d in the rst file and one needs to copy them from the source tree, or they are in the rst file and must be extracted.

The alternative is to skip those files.

**Comment by eric-wieser** [comment]
> The alternative is to skip those files.

Can we ignore only sections of those files? Perhaps a `doctest: SKIP` marker or something?

**Comment by pdebuyl** [comment]
Yes, we can skip every test that requires an external module.

**Comment by eric-wieser** [comment]
I think skipping them is fine, as long as we have an open issue to track unskipping them. Stopping future regressions being introduced now is far more useful than spending lots of time testing unimportant bits of docs.

**Comment by mattip** [comment]
Final tasks to close this issue:
- [ ] open an issue to remove the skips
- [ ] enable running refguide-check --rst in CI
- [ ] open an issue about the possibility of moving to astropy's doctest and dropping refguide-check

**Comment by mattip** [comment]
Closing this, refguide-check --rst is now running as part of CI
