### ISSUE TITLE
Documentation improvement proposal: numpy.random.Generator.choice

### ISSUE THREAD

**Issue by michaels011235** [numpy/numpy#14986]
### Reproducing code example:

```python
import numpy as np
rg = np.random.default_rng(seed=1)
rg.choice(np.arange(12).reshape((2,-1)), size=(2,2), replace=True)
```

### Documentation improvement proposal:

 <https://numpy.org/doc/1.17/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice>

In this documentation: I'd change the 

> a : 1-D array-like or int 

and 

> size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn from the 1-d a. If a has more than one dimension, the size shape will be inserted into the axis dimension, so the output ndim will be a.ndim - 1 + len(size). Default is None, in which case a single value is returned.

The function is able to accept a n-dimensional array, so the 1-D part does not really make sense.

### Numpy/Python version information:

1.17.4 
3.7.4 (default, Aug  5 2019, 16:45:29) 
[GCC 7.4.0]

**Comment by seberg** [comment]
@michaels011235 Can you make a proposal and create a PR for it? That makes our live a bit easier, and we like getting contributions :).
