### ISSUE TITLE
numpy.unique return counts for n-dimensional arrays not working.

### ISSUE THREAD

**Issue by michaels011235** [numpy/numpy#14987]
### Reproducing code example:

```python
a = np.array([[3,3, 4,5,6], [8,8,9,6,3]])
elements, counts = np.unique(a, axis=1, return_counts=True)
print(a, elements, counts, sep='\n\n')

# Output:
#[[3 3 4 5 6]
#  [8 8 9 6 3]]

# [[3 4 5 6]
#  [8 9 6 3]]

# [2 1 1 1]
```

### Expected results:

```python
a = np.array([[3,3, 4,5,6], [8,8,9,6,3]])
elements, counts = np.unique(a, axis=1, return_counts=True)
print(a, elements, counts, sep='\n\n')

# Output:
#[[3 3 4 5 6]
#  [8 8 9 6 3]]

# [[3 4 5 6]
#  [8 9 6 3]]

# [[2 1 1 1]
#    [2 1 1 1]]
```
`counts == np.array([[2, 1, 1, 1],[2, 1, 1, 1]])` shall be `True`. 

### Numpy/Python version information:

1.17.4 3.7.4 (default, Aug  5 2019, 16:45:29) 
[GCC 7.4.0]

**Comment by WarrenWeckesser** [comment]
@michaels011235, when you apply `unique` to a 2-d array with `axis=1`, you are, in effect, finding the unique *columns*.  In this case, `counts` is a 1-d array that gives the number of occurrences of each unique column.

Another example:
```
In [174]: x                                                                     
Out[174]: 
array([[1, 1, 2, 1, 2, 1, 0, 2, 1, 2],
       [2, 2, 1, 2, 2, 2, 1, 2, 1, 1]])

In [175]: ucols, counts = np.unique(x, axis=1, return_counts=True)              

In [176]: ucols                                                                 
Out[176]: 
array([[0, 1, 1, 2, 2],
       [1, 1, 2, 1, 2]])

In [177]: counts                                                                
Out[177]: array([1, 1, 4, 2, 2])
```
So, for example, the column containing `[1, 2]` occurs 4 times in `x`.

In other words, `unique` is working as expected, so I'm closing the issue.  Further comments or questions are welcome.  In particular, if the documentation is unclear, suggestions for improving it would be appreciated.

**Comment by michaels011235** [comment]
@WarrenWeckesser Thanks for your answer, `unique` works as expected. I made an error.

I've got a question: Given an array like `a` in my example, how to find the unique elements of each row (or along any other axis) and return the counts? So, basically I'm asking, how to produce my expected output.

I'd be glad at an answer :)

**Comment by WarrenWeckesser** [comment]
@michaels011235, there is a complication in your question that makes it difficult to use `numpy.unique` efficiently.  In general, the number of unique elements in each row of a 2-d array won't be the same, so the result isn't nicely expressible as a numpy array.  For example, suppose `a` is

```
In [33]: a = np.array([[3, 3, 4, 5, 6], [8, 8, 8, 6, 3], [4, 4, 5, 5, 5]])                       

In [34]: a                                                                                       
Out[34]: 
array([[3, 3, 4, 5, 6],
       [8, 8, 8, 6, 3],
       [4, 4, 5, 5, 5]])
```
The number of unique elements in each row is different.  You have to decide how you want to handle a case like this.

One possible approach is look at all the values in the input array to determine the unique values, and then return a 2-d array whose rows gives the counts of the unique elements in each row of the input.  For example,

```python
def unique_in_rows(a):
    """
    Find the unique values in `a` (a 2-d array), and count the occurrences
    of the unique values in each row of `a`.

    Returns
    -------
    u : ndarray
        The sorted unique values in `a`.
    counts : ndarray, shape (a.shape[0], len(u))
        The counts of the unique values in each row.
    """
    m = a.shape[0]
    u, inv = np.unique(a, return_inverse=True)
    inv = inv.reshape(a.shape)
    counts = np.zeros((m, len(u)), dtype=int)
    np.add.at(counts, (np.arange(m).reshape(-1, 1), inv), 1) 
    return u, counts
```
With the array `a` that I gave above:

```
In [20]: a = np.array([[3, 3, 4, 5, 6], [8, 8, 8, 6, 3], [4, 4, 5, 5, 5]])

In [21]: a
Out[21]: 
array([[3, 3, 4, 5, 6],
       [8, 8, 8, 6, 3],
       [4, 4, 5, 5, 5]])

In [22]: u, counts = unique_in_rows(a)

In [23]: u
Out[23]: array([3, 4, 5, 6, 8])

In [24]: counts
Out[24]: 
array([[2, 1, 1, 1, 0],
       [1, 0, 0, 1, 3],
       [0, 2, 3, 0, 0]])
```

**Comment by michaels011235** [comment]
@WarrenWeckesser Wow, thanks a lot for your comprehensive answer. I really appreciate you taking your time to write it.
