### ISSUE TITLE
Geometric Mean

### ISSUE THREAD

**Issue by YuriyTigiev** [numpy/numpy#14985]
Please add a function "geometric mean" with an option - replace any zero values with 1 before calculation.  

`np.geomean([1, 2, 3, 0, 4 ]) = (1 * 2 * 3 * 1 * 4) ** (1/5) = 1.8881750225898039643281294894555‬`

**Comment by progmatic-99** [comment]
can i work on this?

**Comment by YuriyTigiev** [comment]
Yes. You can.

**Comment by eric-wieser** [comment]
@progmatic-99: Note that without a maintainer approving of the idea, you risk building something that even if perfectly written, is deemed not well suited to numpy.

I'm sort of +0 on this - it's mostly trivial to write as:
```
def geometric_mean(x, axis=1):
    count = a.shape[axis]  # this part is hard for tuples of axes, perhaps we need this bit in numpy
    return np.prod(x, axis=axis)**(1/count)
```

> replace any zero values with 1 before calculation

This seems nonsensical to me. Write `geometric_mean(a[a != 0])` or `geometric_mean(np.where(a == 0. 1. a))` if you really want this behavior.

**Comment by charris** [comment]
ISTR some discussion of adding the geometric mean to SciPy.

**Comment by WarrenWeckesser** [comment]
Note that SciPy has [`scipy.stats.gmean`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gmean.html).

FYI: Using the formulation `prod(x)**(1/n)` can overflow unnecessarily.  That can be avoided by working with logarithms.  Something like:

```
def gmean(a, axis=None, keepdims=False):
    # Assume `a` is a NumPy array, or some other object
    # for which 1.0*a is defined.
    with np.errstate(divide='ignore', invalid='ignore'):
        g = np.exp(np.mean(np.log(1.0*a), axis=axis, keepdims=keepdims))
    return g
```
E.g.

```
In [100]: gmean([2, 4, 8])                                                      
Out[100]: 4.0

In [101]: x                                                                     
Out[101]: 
array([[ 4,  4,  2,  6,  4],
       [ 4,  0,  7,  8,  3],
       [ 2,  9, -1,  2,  8]], dtype=int8)

In [102]: gmean(x, axis=1, keepdims=True)                                       
Out[102]: 
array([[3.77635005],
       [0.        ],
       [       nan]])
```

**Comment by WarrenWeckesser** [comment]
Given that SciPy has `gmean`, I'm closing the issue, but if any NumPy devs think we should also have it in NumPy (perhaps implemented as a gufunc), go ahead an reopen the issue.

**Comment by seberg** [comment]
:+1:, but if the original openers think it is hard to find. We can add a `See Also` or so to `np.mean`.

**Comment by YuriyTigiev** [comment]
> 👍, but if the original openers think it is hard to find. We can add a `See Also` or so to `np.mean`.

http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/generated/numpy.mean.html

Why Numpy doesn't support a  common function "geometric mean" from out of the box?
Yes, it's possible to use SciPy, but in this case, I should need to install an additional library only to use one function.

gmean should support three mode 
1) calc with 0 values
2) removed 0 values 
3) replace 0 values with 1

```

import numpy as np

a = np.array([1,2,3,4,0,5])
a = a[a != 0]

def gmean(a, axis=None, keepdims=False):
    # Assume `a` is a NumPy array, or some other object
    # for which 1.0*a is defined.
    with np.errstate(divide='ignore', invalid='ignore'):
        g = np.exp(np.mean(np.log(1.0*a), axis=axis, keepdims=keepdims))
    return g

print(gmean(a))
print(((1 * 2 * 3 * 1 * 4) ** (1/5)))

2.6051710846973517
1.888175022589804



```

**Comment by mattip** [comment]
The list of "one more function" is infinitely long. See all the [issues and pull requests marked "wish list"](https://github.com/numpy/numpy/labels/23%20-%20Wish%20List). When we add a new API function to NumPy, that means CuPy, JAX, PyTorch, Dask and others must also implement it, so we are very concerned with the cost of adding more top-level functions.

Our approach is more that since SciPy has this function, we will not re-implement it in NumPy.
