### ISSUE TITLE
np.abs fails MIN_INT edge case

### ISSUE THREAD

**Issue by cabosanlucas** [numpy/numpy#14984]
np.abs on a MIN_INT values returns negative numbers.
 
### Reproducing code example:

```python
import numpy as np
t = np.array([-1, 2, 43, -32768], dtype=np.int16)
print(np.abs(t))
```
or
```python
import numpy as np
t = np.array([-1, 2, 43, -2147483648], dtype=np.int32)
print(np.abs(t))
```
### Numpy/Python version information:

1.17.3 3.7.4 (default, Oct 12 2019, 18:55:28) 
[Clang 11.0.0 (clang-1100.0.33.8)]

**Comment by seberg** [comment]
Thanks, we probably need better integer overflow machinery to really do anything about this though. See also gh-5657 which this is a duplicate of (so closing this one).
