### ISSUE TITLE
bitwise operation failure

### ISSUE THREAD

**Issue by faustellar1995** [numpy/numpy#14991]
Something goes wrong when testing some bitwise algorithms in python, then I break the code apart to find an annoying bug as below:

```python
from numpy import int32
x = int32(-17)
i = x>>int32(31)
print(type(x^i))
#numpy.int32

print(x^i-i)
#-17, things go wrong here
z = x^i
print(z-i)
#17, different from above
```

### Numpy/Python version information:
1.16.2 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
This is python operator precedence, and nothing to do with numpy. `a^b - c` means `a ^ (b - c)` in python

**Comment by faustellar1995** [comment]
sorry for that....
