### ISSUE TITLE
raspberry pi Import error

### ISSUE THREAD

**Issue by alexjpm** [numpy/numpy#15001]
Hi everyone,

I'm using a raspberry pi 3B+.  I was running python 2.7.13 with numpy version 1.16.5 (installed via pip) fine, but have finally got round to upgrading the code to python 3.7.3.  Installing numpy version 1.17.4.  However, I now get the following error when trying to import numpy:

>>> import numpy                                                                     
Traceback (most recent call last):                                                   
  File "/usr/src/prt37/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, 
in <module>                                                                          
    from . import multiarray                                                         
  File "/usr/src/prt37/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14
, in <module>                                                                        
    from . import overrides                                                          
  File "/usr/src/prt37/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, 
in <module>                                                                          
    from numpy.core._multiarray_umath import (                                       
ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (requ
ired by /usr/src/prt37/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpyth
on-37m-arm-linux-gnueabihf.so)                                                       
                                                                                     
During handling of the above exception, another exception occurred:                  
                                                                                     
Traceback (most recent call last):                                                   
  File "<stdin>", line 1, in <module>                                                
  File "/usr/src/prt37/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <
module>                                                                              
    from . import core                                                               
  File "/usr/src/prt37/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, 
in <module>                                                                          
    raise ImportError(msg)                                                           
ImportError:                                                                         
                                                                                     
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                   
                                                                                     
Importing the numpy c-extensions failed.                                             
- Try uninstalling and reinstalling numpy.                                           
- If you have already done that, then:                                               
  1. Check that you expected to use Python3.7 from "/usr/src/prt37/bin/python",      
     and that you have no directories in your PATH or PYTHONPATH that can            
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not foun
d (required by /usr/src/prt37/lib/python3.7/site-packages/numpy/core/_multiarray_umat
h.cpython-37m-arm-linux-gnueabihf.so)

Originally i just pip installed numpy.  Since then I've tried:
sudo apt install libatlas3-base
and re-installing via pip, also uninstalling and then installing via:
sudo apt-get install python3-numpy

however both result in the same error.

Has anyone got any ideas why this is and how to fix it?  Python 2.7.13 and numpy 1.16.5 continues to work fine.

Thanks,

Alex

**Comment by mattip** [comment]
> `/lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found`

You somehow got a version of this file that is not supported by your OS. That file does not come from any python or pip command, rather it is part of the base libc apt package itself, so it is strange that it is incompatible with your libc.

**Comment by alexjpm** [comment]
Ended up compiling from source:
```
pip install Cython
cd ~/Downloads
git clone https://github.com/numpy/numpy.git
python setup.py install
```
