### ISSUE TITLE
[Observation] Runtime to append into array

### ISSUE THREAD

**Issue by Allainn** [numpy/numpy#15015]
### Reproducing code example:

```python
import numpy as np
import time

uvmin=np.array([])
u=np.random.rand(1000000,1)
v=np.random.rand(1000000,1)
t1=time.process_time()
# First loop
for i in range(len(u)):
    if(u[i] < v[i]):
        np.append(uvmin,u[i])
    else:
        np.append(uvmin,v[i])
print(time.process_time()-t1)

u=np.random.rand(1000000,1)
v=np.random.rand(1000000,1)
uvmin_aux=[]
t1=time.process_time()
# Second loop
for i in range(len(u)):
    if(u[i] < v[i]):
        uvmin_aux.append(u[i])
    else:
        uvmin_aux.append(v[i])
uvmin=np.array(uvmin_aux)
print(time.process_time()-t1)
```

### Observation:
When inserting into an array using numpy.append, the runtime is 3.5x longer than appending a normal array and then converting to a numpy array.

Processor Model: Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz
RAM 8GB

First loop median time: 9.399925601900009
Second loop median time: 2.535257241700003

**Comment by eric-wieser** [comment]
`np.append` is almost always the wrong solution. If you know the size of the array in advance, then you should pre-allocate it to the right size immediately. Appending in a loop like that is O(N^2), because numpy is not designed for that use case.

**Comment by Allainn** [comment]
Could it be because the whole array is traversed to add at the end?
Thanks for the tip, I will check the runtime for this case.

**Comment by eric-wieser** [comment]
Yes, exactly. Here's the source:

https://github.com/numpy/numpy/blob/master/numpy/lib/function_base.py#L4678-L4684

Note that all it does is `concatenate` new data on the end, which makes a copy

**Comment by seberg** [comment]
This is currently noted in the Return section of the documentation. It is how append works and has to work, but if you think the documentation is unclear on this. Improvements are always very welcome!

**Comment by Allainn** [comment]
I had not observed that a new array is allocated and filled.
Why not use a data structure that allocates only the new node and performs the pointing?

**Comment by charris** [comment]
The whole point of ndarray is to simplify memory layout so as to gain speed of execution and enable the use of standard numerical libraries and compiler optimizations. If you want dynamic structures, Python lists serve that purpose.

**Comment by seberg** [comment]
@Allainn you can have a `view` into an array. Which means there can be other objects using the same chunk of memory. There is simply no technology, under the simple memory layout that we use, to achieve safety. Basically, you cannot do it without losing all comforts of python.

**Comment by Allainn** [comment]
Thanks for the clarifications.
My problem is to perform an optimization of code that was rewritten from matlab to python and this point is where there is a longer execution time, and the algorithm performs several calculations in an array because it is a temporal autoregression algorithm, with the change This way the execution time has been greatly reduced and numpy really helps a lot in the necessary calculations. But I still couldn't get close to matlab efficiency, even using numpy-mkl.

**Comment by charris** [comment]
If you can provide some details, there may be a more efficient way to achieve the same result.

**Comment by rossbar** [comment]
I'm going to close this as it seems like the question was largely resolved, and there was never any followup discussion related to the specific use-case. PRs with suggestions to approve the documentation are still welcome.
