### ISSUE TITLE
BUG: np.save and np.load do not properly handle dtype.metadata

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#15017]
xref gh-14142 (issue) and gh-14994 (always warn when saving an array with metadata).

Dtypes with metadata, or with subdtypes with metadata, either discard the metadata when saving via `np.save`, or crash when loading them via `np.load`.

Currently the "fix" adopted in 1.18 is to always warn.

EDIT (seberg): Giving the warning message:
```
metadata on a dtype may be saved or ignored, but will raise if saved when read. Use another form of storage.
```

**Comment by seberg** [comment]
I'll close this.  We are not almost perfect at dropping metadata with the warning, I think.  Dunno if that is the right state, but I think a new issue woudl be better for it.
