### ISSUE TITLE
Unable to import numpy through xlwings

### ISSUE THREAD

**Issue by corel-cr** [numpy/numpy#15018]
Hi. I started playing with xlwings today & got the error below. I installed Python & numpy using the latest version of Anaconda as of today. I'm calling numpy through xlwings, which I think may be the issue. I can run numpy through Jupyter just fine. I'm using Windows 10 & don't have multiple version of Python installed. 

Thanks.

-------

---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\adrian\desktop\Calculations.py", line 7, in <module>

    import pandas as pd

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\__init__.py", line 17, in <module>

    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)

ImportError: Unable to import required dependencies:

numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.

- Try uninstalling and reinstalling numpy.

- If you have already done that, then:

  1. Check that you expected to use Python3.7 from "C:\ProgramData\Anaconda3\python.exe",

     and that you have no directories in your PATH or PYTHONPATH that can

     interfere with the Python and numpy version "1.17.4" you're trying to use.

  2. If (1) looks fine, you can open a new issue at

     https://github.com/numpy/numpy/issues.  Please include details on:

     - how you installed Python

     - how you installed numpy

     - your operating system

     - whether or not you have multiple versions of Python installed

     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`

  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on

an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

**Comment by mattip** [comment]
This is more an issue with anaconda. I think you need to somehow activate your environment to set the paths up to properly find the DLLs.

**Comment by corel-cr** [comment]
I tried reactivating my environment and that did not seem to take care of it. I had to uninstall & reinstall numpy using pip (not conda) and that appears to have fixed it. Thanks!

**Comment by rossbar** [comment]
Closing as resolved.
