### ISSUE TITLE
Deprecation warnings about object arrays in wheel build.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#15044]
See https://travis-ci.org/MacPython/numpy-wheels/jobs/620443138 for examples.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by charris** [comment]
Not sure why these warnings are not raising an error.

**Comment by mattip** [comment]
The [CI logs](https://travis-ci.org/MacPython/numpy-wheels/jobs/620443138#L2490) say it is using a wheel from [this directory](https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com/wheelhouse) but I do not see the wheel there. I wanted to try it out locally. Is it somehow removed?

**Comment by charris** [comment]
You need the pre-release builds: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/.

I'm thinking this might an artifact of using Python3.6 on bionic as the driving python. I'm testing the release branch not, it uses the old setup with Python3.5 on trusty.

**Comment by mattip** [comment]
Thanks for the link, the wheel used in CI shows up there.

In CI, it seems multibuild short-curciuts `pip install` and uses a file on the local filesystem see [`multibuild/common_utils/install_wheel`](https://github.com/matthew-brett/multibuild/blob/devel/common_utils.sh#L335) (which calls python to find the local file)

In any case I would be surprised if the driving python and OS play any part, since this is all supposed to happen inside a multibuild docker

**Comment by charris** [comment]
Yep, the warnings don't show up on the release branch. Hmm...

**Comment by rgommers** [comment]
That CI log is plain confusing. The daily wheel job simply builds a wheel locally, installs it (see [here](https://travis-ci.org/MacPython/numpy-wheels/jobs/620443138#L2416)), runs the tests and only uploads it in the `after_success` step.

**Comment by charris** [comment]
I'm off to bed, at least the release branch is not troublesome.

**Comment by mattip** [comment]
Found it: the test is creating a ragged array sorter [here](https://github.com/numpy/numpy/blob/master/numpy/core/tests/test_multiarray.py#L2288). That test has been there since 2013 or so. There must be some interaction with `assert_raises` masking the warning.

**Comment by seberg** [comment]
This issue was specitic to the 1.18 release and seemed to be fixed by revert.  Closing.
