### ISSUE TITLE
BUG: ptp fails on bool

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#15057]
### Reproducing code example:

```
import numpy as np
rg = np.random.default_rng()
np.ptp(rg.integers(0,2,size=100).astype("bool"))
```

### Error message:

TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

### Numpy/Python version information:

```
import sys, numpy; print(numpy.__version__, sys.version)
1.17.4 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
```

**Comment by eric-wieser** [comment]
Would you expect the result to be a float or bool?

**Comment by bashtage** [comment]
I'm happy either way as long as I can test using ptp(x, axis=0) == 0.  Probably a bool, and so True/False.  I assume ptp(x.astype(np.float32), axis=0) is a float32.

**Comment by bashtage** [comment]
Type seems to be preserved by ptp except where it spills over (int types).

**Comment by eric-wieser** [comment]
I'd argue that the current behavior is correct - ptp is not defined over things on which subtraction isn't defined.

Having said that, the operation `all_values_equal(x, axis=...)`, which you implement as `ptp(x, axis=....) == 0` _is_ well-defined on booleans, it's just your implementation that isn't.

I'd argue that `ptp(x) == 0` is a bad way to implement this anyway - why not `max(x) == min(x)`, which is fewer comparisons?

**Comment by WarrenWeckesser** [comment]
FWIW: When I was testing various ways to check that an array is constant earlier this year, the fastest turned out to be `(x == x[0]).all()`.  In my case, `x` was a 1-d aray and I  knew the length was not 0.  To check for constant values along the first dimension of an n-d array, you could use `(x == x[0]).all(axis=0)`.

**Comment by eric-wieser** [comment]
Perhaps it would be worth adding to numpy somewhere:
```python
def all_same(arr, *, axis):
    axis = normalize_axis_tuple(axis, arr.ndim)
    sl = [slice(None)]*arr.ndim
    for ax in axis:
         sl[axis] = slice(None, 1)
    return (x == x[tuple(sl)]).all(axis=axis)
```
Note by using `[:1]` instead of `[0]` it works for size 0 arrays too

**Comment by bashtage** [comment]
@eric-wieser  The original justification for ptp was that it should be about 2x as fast as using max and min.  I think the implementation in NumPy isn't and is actually doing two separate passes.  

@WarrenWeckesser The potential issue there is that it requires creating an intermediate array that has the same dimension as x.  If x is large, then this array will also be large. The ptp method uses a reduction first, and then does creates an intermediate with the same size as the reduction.

**Comment by eric-wieser** [comment]
> The original justification for ptp was that it should be about 2x as fast as using max and min. I think the implementation in NumPy isn't and is actually doing two separate passes.

`ptp` is implemented as `max() - min()` inside numpy, so is actually 4 passes once you include the subraction and the equality check, vs `max() == min()` which is 3, or @WarrenWeckesser's suggestion which is 2

**Comment by bashtage** [comment]
For me, the reduction dimension is negligible relative to the shape of the axis being reduced (1000-10000000x smaller), so it is pretty negligible.

A loopy implementation of `all_same` would avoid intermediates.

**Comment by bashtage** [comment]
In terms of thinking about the choice here, it is hard to understand by why some ops, e.g., `sum`, happily cast bools to integers, while other, e.g., `ptp`, do not.

**Comment by bashtage** [comment]
This seems to be a rabbit hole where it is hard to be fully consistent. For example

```
>>> x = np.bool_(True)
>>> x + x
True
>>> np.array([x, x]).sum()
2
```

**Comment by WarrenWeckesser** [comment]
I don't know the details, but there is a lot of relevant *history* here, including some churn back in version 1.13 when the deprecation of boolean subtraction that was added in 1.9 (I think) was converted to an error (e.g. https://github.com/numpy/numpy/issues/9251, https://github.com/numpy/numpy/pull/9255).  I didn't spend enough time searching to find the original discussion of the deprecation of boolean subtraction.  Digging into that history is probably necessary to explain how we ended with the current behavior.

Can someone familiar with the details and history comment here?  Is there more to do, or is the current behavior the best compromise at the moment (and therefore this issue should be closed)?

**Comment by bashtage** [comment]
After this thread, I went with something like

```python
def all_same(arr, *, axis):
    _max = arr.max(axis=axis)
    _min = arr.min(axis=axis)
    return _max == _min
```

which is what was originally suggested.  Seems to work correctly for `nan` as well.

**Comment by seberg** [comment]
@bashtage nice. Sounds like we can close this then. I personally think it is OK if `ptp` does not like booleans much (although others mileage may vary). I will close this, if anyone disagrees just comment!

**Comment by bashtage** [comment]
It would be nice if there was some more consistency for booleans w.r.t when they are treated as 1 and normal int math appears or when adding is treated as `logical_or`.

**Comment by seberg** [comment]
Yes, I agree, but we are in a tricky position here. Python traditionally treats booleans exactly like 0 and 1 (they are just singletons of a subclass of int). We have been stricter, because it is even stranger in NumPy world (e.g. with limited dtype precision and what happens if you index with a boolean).

But we cannot decide that `np.True_ + np.True_` stops working, it is too "normal" in the python world. The subtract is a case where we push back. Python is moving slowly in that direction, but until they change math as well...
