### ISSUE TITLE
Need full names for 1.18.0 release

### ISSUE THREAD

**Issue by charris** [numpy/numpy#15055]
Could the following reply with full name and mail address so that .mailmap can be updated?

- [x] @keewis 
- [x] @mreineck 
- [x] @zoj613 

Thanks

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by zoj613** [comment]
@charris 
Full name: Zolisa Bleki
email address: blkzol001@myuct.ac.za

**Comment by zoj613** [comment]
@charris 
Full name: Zolisa Bleki
email address: zolisa.bleki@gmail.com

**Comment by mreineck** [comment]
That's Martin Reinecke, martin@mpa-garching.mpg.de

**Comment by keewis** [comment]
Justus Magin <keewis@posteo.de>

**Comment by charris** [comment]
Thanks all.
