### ISSUE TITLE
logical_and and logical_or documentation

### ISSUE THREAD

**Issue by Dan-Patterson** [numpy/numpy#15062]
logical_and   : Compute the truth value of x1 AND x2 element-wise.
 logical_or      :   Compute the truth value of x1 OR x2 `element-wise.

So far, good, however, both show this in the Returns section

y : ndarray or bool
Boolean result of the logical OR operation applied to the elements of x1 and x2; the shape is determined by broadcasting. This is a scalar if both x1 and x2 are scalars.

I am thinking that AND should be with logical_and and OR should be with logical_or
 
 np.__version__  # '1.17.2'
sys.version  # '3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]' -->

**Comment by eric-wieser** [comment]
Please file a PR to fix this :)

**Comment by eric-wieser** [comment]
> Please file a PR

To elaborate on that - if you click the link above, you'll be able to edit in-browser, and github will guide you through the process of making a PR.

If you like, you could also make all the edits locally on your filesystem, but I find for small changes its not worth the effort.

**Comment by rossbar** [comment]
It looks like this change has already been made in #14621 and has been included in 1.18.0rc1. Nice catch @Dan-Patterson !

**Comment by eric-wieser** [comment]
Looks like this was already fixed in master when you found it
