### ISSUE TITLE
ImportError('Unable to import required dependencies:\nnumpy: 

### ISSUE THREAD

**Issue by RafaelRueda** [numpy/numpy#15060]
Hi,

I'm trying to use numpy on my python script on my server, but as it's not a dedicated server, I don't have access to the shell or to install anything. 
So what I'm doing is putting the source code into the folder where my python script is running as I'm doing with other python modules, but numpy gives me an error which is the following

Error Report : ', ImportError('Unable to import required dependencies:\nnumpy: No module named numpy\npytz: No module named pytz\ndateutil: No module named dateutil',))

the version i'm trying to use it's the latest one that I could get from gitHub
https://github.com/numpy/numpy

This would be the master
![image](https://user-images.githubusercontent.com/10001883/70283622-a04f9e00-17a0-11ea-95e7-37d74188961e.png)

But what i'm just copying on my folder where my script is the numpy folder inside the master:
![image](https://user-images.githubusercontent.com/10001883/70283637-ae9dba00-17a0-11ea-9ac0-73e9011f853e.png)

If I don't do the previous step and just copy the master folder directly, It gets me this error

Error Report : ', ImportError('Unable to import required dependencies:\nnumpy: Error importing numpy: you should not try to import numpy from\n its source directory; please exit the numpy source tree, and relaunch\n your python interpreter from there.\npytz: No module named pytz\ndateutil: No module named dateutil',))

I'm using python 3.7 and the server where it's working is Linux.

**Comment by Athul8raj** [comment]
This is an error thrown from the __init__.py file of numpy . They have restricted the setup of numpy using the method you have adopted above.
They are using a global variable (__NUMPY_SETUP__)  which is set to True on the setup.py file. and this flag is checked in the __init__ file. If it is not found, it throws the error.
So you either have to do a pip install like a normal setup or if that's not possible you have to comment out those lines of code checking for this flag and install the required dependencies manually.

**Comment by mattip** [comment]
NumPy is a c-extension module, you cannot simply copy the source to site-packages and hope it will work.

> I don't have access to the shell or to install anything

This is what `pip install --user ...` is meant for. It will install packages to a user-owned directory. Another alternative is to use virtualenv/venv which will go a long way toward isolating the entire python installation.
