### ISSUE TITLE
macOS 10.15 python3.7 Intel MKL ERROR: CPU 0 is not supported

### ISSUE THREAD

**Issue by liygzting** [numpy/numpy#15078]
### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

### Numpy/Python version information:

Hi
My Mac OS up to 10.15 ,when I install numpy and pytorch .and run
```
# 完成官方的手写字识别的小程序

import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 构造的网络框架主体
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # 线性连接
        self.fc1 = nn.Linear(16*6*6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self,x):
        # 池化层
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

net = Net()
print(net)

params = list(net.parameters())
print(len(params))
print(params[0].size())

input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

```
I got this error :Intel MKL ERROR: CPU 0 is not supported.

but macOS no NumPy  mkl

**Comment by mattip** [comment]
This `import numpy; numpy.show_config()` should show what backends NumPy is using. Where did you download python and numpy? If you are using conda (Anaconda, mini-conda, ...) they ship the MKL backend, which is [advertised](https://software.intel.com/en-us/mkl) to work on macOS. Are you running on an x86 processor?

**Comment by liygzting** [comment]
yes, it's x86 processor computer and my os is MacOS 10.15.

PS:
>>> import numpy
>>> numpy.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

**Comment by mattip** [comment]
This would seem to indicate you are not using MKL for NumPy. Perhaps the error comes from pytorch, not numpy? Could you paste the actual error? 

If you select your pasted text and click on the `<>` button in the toolbar, it will convert it to code (I edited your comment above)

**Comment by liygzting** [comment]
this？

>>> import numpy
>>> numpy.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

**Comment by liygzting** [comment]
I think what you said makes sense, simply running numpy is perfect, but pytorch uses parallel computing and something goes wrong
To be honest, I don't know how to implement the operation you said.
Excuse me for more details
Thank you

**Comment by liygzting** [comment]
`>>> import numpy
>>> numpy.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]`

**Comment by liygzting** [comment]
or?
`# 完成官方的手写字识别的小程序

import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 构造的网络框架主体
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # 线性连接
        self.fc1 = nn.Linear(16*6*6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self,x):
        # 池化层
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

net = Net()
print(net)

params = list(net.parameters())
print(len(params))
print(params[0].size())

input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)`

**Comment by liygzting** [comment]
actual error like :

```
>>> import torch
>>> import torch.nn as nn
>>> import torch.nn.functional as F
>>> class Net(nn.Module):
...     def __init__(self):
...         super(Net, self).__init__()
...         # 构造的网络框架主体
...         # kernel
...         self.conv1 = nn.Conv2d(1, 6, 3)
...         self.conv2 = nn.Conv2d(6, 16, 3)
...         # 线性连接
...         self.fc1 = nn.Linear(16*6*6, 120)
...         self.fc2 = nn.Linear(120, 84)
...         self.fc3 = nn.Linear(84, 10)
...     def forward(self,x):
...         # 池化层
...         x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
...         x = F.max_pool2d(F.relu(self.conv2(x)), 2)
...         x = x.view(-1, self.num_flat_features(x))
...         x = F.relu(self.fc1(x))
...         x = F.relu(self.fc2(x))
...         x = self.fc3(x)
...         return x
...     def num_flat_features(self, x):
...         size = x.size()[1:]
...         num_features = 1
...         for s in size:
...             num_features *= s
...         return num_features
... 
>>> net = Net()
>>> print(net)
Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
>>> params = list(net.parameters())
>>> print(len(params))
10
>>> print(params[0].size())
torch.Size([6, 1, 3, 3])
>>> input = torch.randn(1, 1, 32, 32)
>>> out = net(input)
Intel MKL ERROR: CPU 0 is not supported.
print(out)a
```

**Comment by mattip** [comment]
This is outside the realm of what we can help with here, sorry. This issue seems to be very similar pytorch/pytorch#31044.

Closing. If you discover there is some connection to numpy, please reopen or open a new issue.

**Comment by vpirogov** [comment]
See discussion in https://github.com/pytorch/pytorch/issues/31106.

**Comment by hevinzhou** [comment]
@vpirogov @mattip 

the discussion in [#31106](https://github.com/pytorch/pytorch/issues/31106) doesn't work for me.

- **terminal test result**:

```
(base) ➜  ~ python
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Intel MKL ERROR: CPU 0 is not supported.
(base) ➜  ~ echo $MKL_DEBUG_CPU_TYPE
5
```

- that's my env:
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | ryzen 2600   |
