### ISSUE TITLE
Occasional MemoryError in i686 wheels builds.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#15071]
See https://travis-ci.org/MacPython/numpy-wheels/jobs/621347829 .

This seems new, I haven't seen it for the 1.18.x builds.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by rgommers** [comment]
Probably already fixed in commit d3f6a7eddc68. At least the `requires_memory` decorator was updated there.

**Comment by charris** [comment]
Still there: https://travis-ci.org/MacPython/numpy-wheels/jobs/622056399, but only for Python 3.7 i686 as before.  Once is happenstance...

**Comment by charris** [comment]
Hmm, now failed for Python 3.6 i386... and Python 3.8 i386 also.

**Comment by pv** [comment]
Quick workaround is to add `export NPY_AVAILABLE_MEM=6GB` to top of `run_tests` in `numpy-wheels/config.sh` to skip the test unconditionally --- presumably the test was previously usually skipped.

The issue may be that the memory requirement is checked at import time, for which gh-15072 should help.

**Comment by charris** [comment]
Seems to be fixed.
