### ISSUE TITLE
BUG: max of a masked array with dype np.float16 returns inf

### ISSUE THREAD

**Issue by w-k-jones** [numpy/numpy#15077]
Finding the maximum of a masked array with dtype np.float16 returns inf if some (but not all) elements are masked

### Reproducing code example:

```python
import numpy as np
from numpy import ma
test_array = ma.array(np.random.rand(10), mask=np.eye(10)[0], dtype=np.float16)
print(test_array)
print(test_array.max())
```

1.17.4 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by WarrenWeckesser** [comment]
This is still a bug in the master branch:

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.19.0.dev0+bf9614b'

In [3]: x = np.ma.array([-1, 2, 0, 1], mask=[False, False, True, False], dtype=np.float16)

In [4]: x
Out[4]: 
masked_array(data=[-1.0, 2.0, --, 1.0],
             mask=[False, False,  True, False],
       fill_value=1e+20,
            dtype=float16)
```
Both `x.max()` and `x.argmax()` are incorrect:
```
In [5]: x.max()
Out[5]: inf

In [6]: x.argmax()
Out[6]: 2
```
`x.min()` and `x.argmin()` return correct results:
```
In [7]: x.min()
Out[7]: -1.0

In [8]: x.argmin()
Out[8]: 0
```

**Comment by seberg** [comment]
The reason is that the `max_filler` and `min_filler` are set to `numpy.float16: None`. Which in turn seems to default to the `fill_value` set on the array. That is `1e20` which does not make sense, because it is even out of bounds for float16. But generally `None` as a fill value for minimum and maximum seems strange to begin with. (Complex should have the same issues)

**Comment by w-k-jones** [comment]
> The reason is that the `max_filler` and `min_filler` are set to `numpy.float16: None`. Which in turn seems to default to the `fill_value` set on the array. That is `1e20` which does not make sense, because it is even out of bounds for float16. But generally `None` as a fill value for minimum and maximum seems strange to begin with. (Complex should have the same issues)

Thanks for pointing out the reason behind it. I've created a pull request that fixes the issue here (https://github.com/numpy/numpy/pull/15086#issue-351368156). It simply sets the min and max values for all numpy float and complex dtypes to +/- inf, which should suffice for complex values as only the real part needs to be inf for comparisons

**Comment by seberg** [comment]
Clposed by gh-15991 thanks for starting this effor @w-k-jones.
