### ISSUE TITLE
Divide by zero doesn't give error for numpy.float64

### ISSUE THREAD

**Issue by byogi06** [numpy/numpy#15089]
When we divide one variable(type numpy.float64 ) with another variable(type numpy.float64 ) which is 0 , it simply return value as **inf** instead of throwing error.

It should not return **inf** (I guess its infinity )  value, as it doesn't make any sense.

### Reproducing code example:

```python
import numpy as np
a=np.float64(1.0)
b=np.float64(0.0)
c=a/b
print(c)
output = inf
```

### Error message:

As such there is no error but it should give error as explained above.

### Numpy/Python version information:

1.17.4

**Comment by WarrenWeckesser** [comment]
Returning `inf` (or `-inf`) when dividing a nonzero `float64` by 0 is part of the [IEEE 754 floating point standard](https://en.wikipedia.org/wiki/IEEE_754).  If you search the internet for something like "IEEE 754 divide by zero", you'll find lots of informatin about this (e.g. https://stackoverflow.com/questions/14682005/why-does-division-by-zero-in-ieee754-standard-results-in-infinite-value).

You say there is no error, but in fact, a *warning* is generated:

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.17.4'

In [3]: a = np.float64(1.0)

In [4]: b = np.float64(0.0)
```
Note that a warning is generated when you divide by zero:
```
In [5]: c = a / b
/Users/warren/mc37scipy/bin/ipython:1: RuntimeWarning: divide by zero encountered in double_scalars
  #!/Users/warren/mc37scipy/bin/python

In [6]: c                                                                       
Out[6]: inf
```
With `numpy.seterr`, you can change the behavior from generating a warning to raising an exception:
```
In [7]: np.seterr(divide='raise')                                               
Out[7]: {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [8]: c = a / b                                                               
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
<ipython-input-8-249b22ba83f7> in <module>
----> 1 c = a / b

FloatingPointError: divide by zero encountered in double_scalars
```

The reported behavior is correct, so I'm closing the issue.

**Comment by byogi06** [comment]
Thanks  @WarrenWeckesser for details, It helps. I will close this issue too
