### ISSUE TITLE
Import Error Numpy

### ISSUE THREAD

**Issue by omega3948** [numpy/numpy#15092]
I'm attempting to import opencv but am being thrown an error from Numpy.After the initial import numpy didnt work i tried importing the core multi array specifically. I attempted uninstalling and reinstalling numpy via the anaconda prompt using conda install numpy. I did the same thing with opencv. Conda list shows numpy and numpy-base. Python -c "import numpy" also executes without issue.

import numpy
import numpy.core.multiarray
import cv2

print(cv2.__version__)

```python
import numpy as np
<< your code here >>
```

### Error message:

C:\Users\N\Anaconda3\python.exe D:/Experiments/Python/Program/ImageProcessing/Demo/demo.py
Traceback (most recent call last):
  File "C:\Users\N\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\N\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\N\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Experiments/Python/Program/ImageProcessing/Demo/demo.py", line 1, in <module>
    import numpy
  File "C:\Users\N\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\N\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\N\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

### Numpy/Numpy-Base: 1.17.4
       Python: 3.7.1

**Comment by charris** [comment]
ISTR a previous report about opencv. These problems usually result from mixing pip and anaconda, or from an application that ends up installing another version of NumPy due to some dependency requirement.  On windows, there might also be several python/numpy installations. What does a global search for NumPy show?

**Comment by omega3948** [comment]
I'm seeing 3 folders for numpy 1.17.4 in the packages folder for anaconda as well as 1 folder for numpy 1.15.4  in that same folder as well as the dist-info folder for 1.16.4 in the opencv folder. I previously attempted to uninstall / reinstall numpy form the anaconda command line and that didnt delete all these. Will a manual delete stop giving me errors?

**Comment by charris** [comment]
I can't really say what will happen, but it does look like you have too many versions of numpy. If you are happy to work with anaconda, it probably makes sense to remove all except what anaconda provides. Where did you get opencv?

**Comment by omega3948** [comment]
I believe I downloaded the package from the website and used pip to install it a few months back. When I started working out of pycharm last night the project interpreter couldnt find the copy of opencv-contrib-python or opencv-python to uninstall even though the 4.0.0.21 versions were shown as being installed. 

Deleting the all the other versions still doesnt seem to be fixing the issue. I think Pycharm and Spyder may have been using different versions of the libraries I had installed. I think I'll try uninstalling anaconda, spyder, and pycharm, then reinstalling and see does that fix the issue. 

I started with anaconda but then ended up doing more projects that involved downloading other libraries that didn't come with anaconda.

**Comment by seberg** [comment]
The error indeed looks like it did not even find `numpy.core._multiarray_umath`, which may also be a path issue I guess. Did your uninstall/install plan work out? There does not seem much more we can do porobably. I am going to tentetavily close, but please comment if the problem persists and we can reopen it.
