### ISSUE TITLE
DOC: f2py: The configuration file ".f2py_f2cmap" is not documented.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#15096]
`f2py` provides a means to map Fortran data types to C types in a file called `.f2py_f2cmap`.  The use of this file is not documented in the `f2py` documentation in https://github.com/numpy/numpy/tree/master/doc/source/f2py

The file was mentioned in the FAQ at http://cens.ioc.ee/projects/f2py2e/FAQ.html, but that URL now gives a 404 error.  Whether or not that FAQ can be restored, the documentation of `.f2py_f2cmap` should be integrated into the `f2py` documentation at https://github.com/numpy/numpy/tree/master/doc/source/f2py

**Comment by charris** [comment]
http://web.archive.org/web/20161001180518/https://sysbio.ioc.ee/projects/f2py2e/FAQ.html

**Comment by WarrenWeckesser** [comment]
Thanks Chuck, and hooray for the internet archive!
