### ISSUE TITLE
int64 and float64 conversion roundtrip off by 1

### ISSUE THREAD

**Issue by arksch** [numpy/numpy#15094]
int64 to float64 to int64 conversion is off by 1 for some big integers
Found this due to some autoconversions in pandas that lead to strange behavior.

### Reproducing code example:

```python
import numpy as np
n = np.int64(9340351261291575)
print(n.astype(np.float64).astype(np.int64))
>>> 9340351261291576
n - n.astype(np.float64).astype(np.int64)
>>> -1
```

Strangely, it only breaks for the roundtrip but works for single conversions.
```
>>> n - n.astype(np.float64)
0.0
>>> n.astype(np.float64) - n.astype(np.float64).astype(np.int64)
0.0
```

### Numpy/Python version information:

1.16.5 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

Using anaconda 2019.10 build py37_0 on win32 (Windows 10) with numpy build py37h19fb1c0_0

**Comment by eric-wieser** [comment]
There is no 64-bit floating point number that equals `9340351261291575`. You can see that in python without involving numpy:
```
>>> 9340351261291575.0
9340351261291576.0
```
