### ISSUE TITLE
arr.mean(axis=0)[2] != arr[:,2].mean()

### ISSUE THREAD

**Issue by cv3d** [numpy/numpy#15093]
Mean before masking and after it are very different...

### Reproducing code example:
```python
import numpy
arr  = (100000000 * numpy.random.random((1000000, 3))).astype('float32')
print(arr.astype('float64').mean(axis=0)[2])
print(arr[:, 2].mean())
print(arr.mean(axis=0)[2])  # strong loss of precision
```

### Error message:
Loss of precision

### Numpy/Python version information:
Python 2.7.13
NumPy 1.14.2 (Mostly applies to other version as well)

**Comment by tuoxie2046** [comment]
NumPy 1.16.* has the same issue.

**Comment by seberg** [comment]
See also gh-11331 this is expected, there are some open issues about adding a stable sum, but it is a speed tradeoff. Basically, you should expect naive precision currently, but sometimes NumPy gives you more (probably most of the time), at no cost of speed.

**Comment by mproszewska** [comment]
I  believe that parameter `dtype` should be used for better precision. 
```
print(arr[:, 2].mean(dtype='float64'))
```

**Comment by seberg** [comment]
Yes, setting a larger dtype may often be a good option (especially when working with float32 arrays, etc.), it will quite a bit slower, but you have much more precision available. I am going to close this issue. We can keep discussing on the old issues though. I still think it is a bit annoying that we provide so much better precision in some but not all cases, but it seems better to take the improved precision where we can (and it covers a very large amount of cases).

Generally, the lack of stable summation methods is of course something where contributions/working on it could be very nice.
