### ISSUE TITLE
numpy.polyfit error of a sample:TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by jbxiang** [numpy/numpy#15104]
### Reproducing code example:

```python
import numpy as np
<< `x = np.array([0, 1, 2, 3])
 y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T`
>>
```

### Error message:TypeError: 'int' object is not callable
[https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html#numpy.linalg.lstsq](url)

**Comment by eric-wieser** [comment]
This bug report doesn't make sense to me. Your example does not use `polyfit` (nor does it even error), and the link you give is to lstsq.

Can you provide more information to clarify this?

**Comment by mattip** [comment]
Closing. @jbxiang if needed please reopen with more information.
