### ISSUE TITLE
multiarray_umath.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by dvdabeele** [numpy/numpy#15102]
Troubles trying to run numpy, apparently due to a failure to link with a shared library.

I am working on an offline Linux machine (Red Hat 4.8.5-11) (absolutely no internet connection allowed here), under a tight deadline ... Not much experience with Python.

I use Python 3.6.3 installed in a virtual environment (as I do not have admin rights on the machine).

I did a local install of numpy-1.17.4-cp36-cp36m-manylinux1_x86_64.whl (via pip install --user numpy-1.17.4-cp36-cp36m-manylinux1_x86_64.whl) that appeared to go fine.

When I try to import numpy, I get the following error message:

### Reproducing code example:
>>> import numpy as np
Traceback (most recent call last):
  File "/export/home/cm/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/export/home/cm/.local/lib/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/export/home/cm/.local/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /export/home/cm/.local/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home/cm/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/export/home/cm/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

 ...

Original error was: /export/home/cm/.local/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

### Numpy/Python version information:

Numpy 1.17.4
Python 3.6.3 for Linux 64 bit, Red Hat 4.8.5-11

**Comment by mattip** [comment]
It may be a permissions thing. What are the permissions on `/export/home/cm/.local/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so` ?

Using `pip --user` together with a virtual environment is considered an anti-pattern, the whole point of a virtualenv is to isolate packages from "leaking" outside it. You should be installing directly into the virtual environment

**Comment by dvdabeele** [comment]
Good afternoon  - thanks for the quick reply. 

**It may be a permissions thing. What are the permissions on /export/home/cm/.local/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so ?**

cm@sv-arg-cbs-s1:/export/home/cm/.local/lib/python3.6/site-packages/numpy $ ls -ld core
drwxr-x--- 6 cm cm 4096 Dec 12 13:58 core
cm@sv-arg-cbs-s1:/export/home/cm/.local/lib/python3.6/site-packages/numpy $ ls -l core
total 22804
-rw-r----- 1 cm cm   201718 Dec 12 13:58 _add_newdocs.py
-rw-r----- 1 cm cm        0 Dec 12 13:58 _aliased_types.py
-rw-r----- 1 cm cm    60821 Dec 12 13:58 arrayprint.py

**Using pip --user together with a virtual environment is considered an anti-pattern, the whole point of a virtualenv is to isolate packages from "leaking" outside it. You should be installing directly into the virtual environment**

I did not install directly into the virtual environment as this give me a 'permission denied' on the folder /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages, see below. I am puzzled by this as I had expected that the installed files would be located under the tree of my virtual environment. I am definitely working in a separate environment, I had to set it up myself as by default this Linux box only runs Python2.7.

_pip install --no-index --find-links=./. six
Collecting six
Installing collected packages: six
  Running setup.py install for six ... error
    Complete output from command /opt/rh/rh-python36/root/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t6d2rjjs/six/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0c79qnbq-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying six.py -> build/lib
    running install_lib
    copying build/lib/six.py -> /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages
    error: could not create '/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/six.py': Permission denied

    ----------------------------------------

Command "/opt/rh/rh-python36/root/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t6d2rjjs/six/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0c79qnbq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t6d2rjjs/six/_

**Comment by dvdabeele** [comment]
No progress today, other than that this is clearly unrelated to virtual environments. For some reason, linking against the library underneath refuses to work. Could it be related to an overall security setting on the Linux machine I've been given?

_Original error was: /export/home/cm/.local/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted_

**Comment by charris** [comment]
> Could it be related to an overall security setting on the Linux machine I've been given?

Maybe an account setting?

**Comment by dvdabeele** [comment]
OK, problem solved. The Linux machine I was given had some disk partitions mounted 'no-exec' and the numpy shared libraries were installed on these partitions. I could manually give them execute permissions but these were overridden by the system. I stumbled on this by accident, could have looked forever. When moving the numpy shared library to another disk partition, it now works fine. 

Thanks for your time & have a nice weekend.

**Comment by rattling** [comment]
dvdabeele's fix worked for me.  In my case had to work on the drive so remounted it with executable permissions https://stackoverflow.com/questions/64109848/cannot-use-pip-within-venv/64110234#64110234
