### ISSUE TITLE
DEP: Add FutureWarning into `ufunc.outer` with `matrix` input

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#15105]
Currently `ufunc.outer` explicitly drops `martix`, since the outut will normally not be a Matrix subclass in any case. In my opinion we should:

 1. Add a FutureWarning there for 1-2 releases that this will not be done in the Future, users should simply ensure the input is an array. In most cases this means an error will be raised.
 2. Remove this, probably within one version of Deprecation. One less thing to worry about when we try to move matrix out of NumPy.

This is all very easy to do, just that I am concentrating on trying a larger cleanup right now.

**Comment by seberg** [comment]
There may be an alternative no-deprecation solution where `__array_prepare__` is used to drop the matrix when the context is "outer", I am not 100% it gets context though. (`__array__` does, but it does not apply)

**Comment by rossbar** [comment]
Looks like this was closed by #16232. If not, please reopen.
