### ISSUE TITLE
Numerical imprecision (overflow) in logsumexp/exp with short floats

### ISSUE THREAD

**Issue by pdimitrov-thoughtriver** [numpy/numpy#15117]
Simple overflow reproduced in the code below. It only happens when embedding the call to logsumexp of short floats in a larger array.

### Reproducing code example:

```python
import numpy as np
from scipy.special import logsumexp

print(np.__version__)
print(np.exp(logsumexp(np.log(np.zeros(100) == 0))))  # here, it does compute the result properly
print(np.exp([0, logsumexp(np.log(np.zeros(100) == 0))]))  # here, it doesn't!
print(np.exp([0, logsumexp(np.log(np.zeros(100) == 0))])[1] -
    np.exp(logsumexp(np.log(np.zeros(100) == 0))))  # difference

# no overflow with larger float sizes:
print(np.exp([0, logsumexp(np.log(np.zeros(100) == 0, dtype = "float64"))]))
print(np.exp(logsumexp(np.log(np.zeros(100) == 0, dtype = "float64"))))
print(np.exp([0, logsumexp(np.log(np.zeros(100) == 0, dtype = "float64"))])[1] -
    np.exp(logsumexp(np.log(np.zeros(100) == 0, dtype = "float64"))))

```

### Numpy/Python version information:

1.17.4 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0]

**Comment by seberg** [comment]
My personal preference would be if the first things would just error out, because you are feeding a boolean array into `log`. We could change that (it is not even very difficult, but needs broader discussion; I personally think it would be good to fail and ask you to specify a floating point type).

Given that you end up with `float16` due to this behaviour, you will have **exceedingly little numerical precision**. Unless you know what you are doing, avoid float16, and probably even float32 for many things.

**Comment by pdimitrov-thoughtriver** [comment]
Hi,

Thank you for the concern, but the way this is written is precisely the desired behavoiur I'm after - computing confusion matrices for both boolean and float arrays so I want to cover the same cases with the same code.

I just did a bit more digging and it's actually the appearance of correct results for this particular set of data - from rounding in float16 vs. the upcasting from float16 to float64 (last example):

np.exp(logsumexp(np.zeros(2, dtype="float64")).astype("float64"))  # returns 2.0
np.exp(logsumexp(np.zeros(2, dtype="float16")).astype("float16"))   # 2.0  - shows the correct result, but only because of rounding in float16 
np.exp(logsumexp(np.zeros(2, dtype="float64")).astype("float16"))  # 2.0
np.exp(logsumexp(np.zeros(2, dtype="float16")).astype("float64"))  # 2.0004244339097745 - because of upcasting - it appears to be doing worse than the float16 case

On the other hand with a number has more decimals we get the right impression:
np.exp(np.array(np.log(2.76), dtype="float16").astype("float64"))  # returns 2.7610885385501014
np.exp(np.array(np.log(2.76), dtype="float64").astype("float64"))  # 2.7599999999999993
np.exp(np.array(np.log(2.76), dtype="float16").astype("float16"))  # 2.762 - now it appears correctly to have lost more precision as it should given it has lower precision

Thank you

**Comment by seberg** [comment]
Ah, ok. If you are OK with float16 for the moment (when the input is boolean), I guess it works fine? I still think it would be better to not silently go to float16, it is a way too imprecise datatype for too many things IMO.
One thing about float16 specifically is that most hardware does not have it, so temporary results may or may not be stored as float32 (i.e. during summation), which might make predicting how good the final precision is hard.

One other note: You could use `dtype = np.result_type(arr.dtype, np.float32); np.log(..., dtype=dtype)` to ensure that the work is done with at least 32bit precision.
