### ISSUE TITLE
np.sum(arr) not equal to reduce(lambda a, b: a+b, arr)

### ISSUE THREAD

**Issue by colin-zhou** [numpy/numpy#15122]
a random array of np.float64 sum not equal to reduce(lambda a, b: a+b, arr) version

### Reproducing code example:

```python
import numpy as np
import sys
x = np.random.random(200)
print("np_sum    ", np.sum(x), file=sys.stderr)
print("reduce_sum", functools.reduce(lambda a,b: b + a, x), file=sys.stderr)
```

### Error message:
the result shows some thing like this (this should be equal)

np_sum     99.13225730835295
reduce_sum 99.13225730835288

### Numpy/Python version information:
1.15.2 3.5.6 (default, Nov 16 2018, 15:50:58) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

**Comment by eric-wieser** [comment]
Floating point addition is not associative, `(a + b) + c != a + (b + c)`. Numpy uses pairwise summation, so does not perform the additions in the same order. This tends to produce a more accurate answer than the left-to-right approach used by reduce.
