### ISSUE TITLE
Gufunc incorrect broadcasts on non-core output dimensions

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#15139]
I have been wrapping some "Standards of Astronomy" code in gufuncs, and encountered puzzling behaviour for cases where one gives an output array: broadcasting will happen over the non-core dimensions. The effect can be seen from the test examples in `umath`:
```
import numpy as np
from numpy.core._umath_tests import inner1d, cross1d

a = np.arange(9.).reshape(3, 3)
inner1d(a, np.array([1., 0., 0.]))
# array([0., 3., 6.])
inner1d(a, np.array([1., 0., 0.]), out=np.empty(()))
# Oops, no error, instead just:
# array(6.)

cross1d(a, np.array([1., 0., 0.]))
# array([[ 0.,  2., -1.],
#        [ 0.,  5., -4.],
#        [ 0.,  8., -7.]])
cross1d(a, np.array([1., 0., 0.]), out=np.empty(3))
# No error!? Instead
# array([ 0.,  8., -7.])
```
So, by default, broadcasting is allowed in output non-core dimensions. Indeed, in the `nditer` [creation](https://github.com/numpy/numpy/blob/190ac3e99015ddded029d8811829da1b48b69b97/numpy/core/src/umath/ufunc_object.c#L2839), one sees that `NPY_ITER_REDUCE_OK` is included.

The [solution used by `matmul`](https://github.com/numpy/numpy/blob/190ac3e99015ddded029d8811829da1b48b69b97/numpy/core/src/umath/ufunc_object.c#L343) is to set the output as write-only, in which case its reduction is no longer allowed.

But that fails for gufuncs with more complicated signatures, in which there are independent output dimensions, like `()->(),(3, 3)`: for those, setting to write-only, the arrays can neither be created nor passed in, since in the initial call to the iterator, those dimensions have to be reduceable (e.g., in the example just given, for scalar input, the first output operand has `op_axes=-1, -1`), although of course in the final iteration those dimensions are not used at all (they're [removed](https://github.com/numpy/numpy/blob/190ac3e99015ddded029d8811829da1b48b69b97/numpy/core/src/umath/ufunc_object.c#L2927) before the iteration is done).

Not quite sure how to solve this...

**Comment by seberg** [comment]
Hmmm, tricky. Since we want to use NpyIters allocation, I suppose the only easy option is to check whether this happens after the fact?

**Comment by mhvk** [comment]
Yes, that's what I concluded too: broadcasting and thus read-write have to be temporarily enabled in order to allocate the outputs, and then it has to be checked after the fact.

Or one needs the option to tell the iterator that the given axis is going to be removed anyway, so not to bother about checking (say, `-2`...).

**Comment by seberg** [comment]
Hmm, good point. Maybe worth investigating. Just in case it happens to fit well with the code float in NpyIter. Although, while maybe not documented, it would be additional public API; but maybe its not that bad API...

**Comment by mhvk** [comment]
Indeed. Am not very familiar with `nditer` at all, but I did track down where the error is raised: https://github.com/numpy/numpy/blob/190ac3e99015ddded029d8811829da1b48b69b97/numpy/core/src/multiarray/nditer_constr.c#L1648-L1670

**Comment by mhvk** [comment]
Sorry, should clarify: where the error is raised if you explicitly set the output to write-only, as is done in `matmul`. Flag-wise, it would be more logical to pass on to the iterator that reductions are not OK, but that some particular axes should not be worried about.

**Comment by seberg** [comment]
Nice, may look at it later, although maybe you are in a roll. It seems to me that your `-2` idea likely works? (Although I am only 90% sure right it works correctly if `out` is provided for any possible signature...).

**Comment by mhvk** [comment]
OK, I'll try to have a PR with the `-2` option up. It is rather ugly, but at least gives us something concrete to discuss.
