### ISSUE TITLE
Numpy.minimum.at()

### ISSUE THREAD

**Issue by xu-kai-xu** [numpy/numpy#15130]
I find an interesting function `np.minimum.at(D, P12[:, 0], L)`,  `np.minimum.at(D, P12[:, 1], L)`;
where `D = numpy.inf*numpy.ones((64, ))`, `l = numpy.ones(144)`, and `P12` is a 144*2 array i attached as follows:
[np_minimum_at.txt](https://github.com/numpy/numpy/files/3983382/np_minimum_at.txt)

I google for nothing about this function. So i wish someone can tell me the logic of this function. Thanks.

**Comment by eric-wieser** [comment]
Documentation is here: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.at.html

**Comment by xu-kai-xu** [comment]
Thanks a lot. @eric-wieser
