### ISSUE TITLE
Isn't it interesting! Inconsistent behavior of float number with a long tail.

### ISSUE THREAD

**Issue by yuziGuo** [numpy/numpy#15131]
My numpy version is 1.17.4. 
The issue is as below:

![image](https://user-images.githubusercontent.com/29125659/71178656-9b631200-22a9-11ea-9c3b-2ca025be906e.png)

Please compare to this. **The issue is not there in python built-in dtype('float64')**:

![image](https://user-images.githubusercontent.com/29125659/71179078-6c996b80-22aa-11ea-89b4-8eb2f197a866.png)

**Comment by eric-wieser** [comment]
Please can you paste your code as text rather than an image, so that we can reproduce it?

Uploading your `ipynb` would also be ok.

**Comment by matthew-brett** [comment]
@yuziGuo - I think you'll find this is just a display output issue.   Here's what I think you're noticing:

```
[ins] In [2]: test = 0.9999999999                                                               

[ins] In [3]: test                                                                              
Out[3]: 0.9999999999

[ins] In [4]: test_arr = np.array([test], dtype='float64')                                      

[ins] In [5]: test_arr                                                                          
Out[5]: array([1.])
```

Numpy displays the value as 1, but Python shows all the value with the decimal places.

But - the values are the same:

```
[ins] In [6]: test == 1                                                                         
Out[6]: False

[ins] In [7]: test_arr == 1                                                                     
Out[7]: array([False])

[ins] In [8]: test == test_arr                                                                  
Out[8]: array([ True])
```

And you can configure Numpy's display to show the full value if you want:

```
[ins] In [9]: np.set_printoptions(precision=16)                                                 

[ins] In [10]: test_arr                                                                         
Out[10]: array([0.9999999999])
```

**Comment by eric-wieser** [comment]
I'd recommend `precision=None`, if you want to see the exact value

**Comment by yuziGuo** [comment]
> Please can you paste your code as text rather than an image, so that we can reproduce it?
> 
> Uploading your `ipynb` would also be ok.



> Please can you paste your code as text rather than an image, so that we can reproduce it?
> 
> Uploading your `ipynb` would also be 

> @yuziGuo - I think you'll find this is just a display output issue. Here's what I think you're noticing:
> 
> ```
> [ins] In [2]: test = 0.9999999999                                                               
> 
> [ins] In [3]: test                                                                              
> Out[3]: 0.9999999999
> 
> [ins] In [4]: test_arr = np.array([test], dtype='float64')                                      
> 
> [ins] In [5]: test_arr                                                                          
> Out[5]: array([1.])
> ```
> 
> Numpy displays the value as 1, but Python shows all the value with the decimal places.
> 
> But - the values are the same:
> 
> ```
> [ins] In [6]: test == 1                                                                         
> Out[6]: False
> 
> [ins] In [7]: test_arr == 1                                                                     
> Out[7]: array([False])
> 
> [ins] In [8]: test == test_arr                                                                  
> Out[8]: array([ True])
> ```
> 
> And you can configure Numpy's display to show the full value if you want:
> 
> ```
> [ins] In [9]: np.set_printoptions(precision=16)                                                 
> 
> [ins] In [10]: test_arr                                                                         
> Out[10]: array([0.9999999999])
> ```

Thank you very much! Thanks for your wonderful work and kind reply.

**Comment by yuziGuo** [comment]
> precision=None

Great. Thank you buddy.
