### ISSUE TITLE
Numpy installed but "ModuleNotFoundError: No module named 'pickle5" 

### ISSUE THREAD

**Issue by Noodledoms** [numpy/numpy#15147]
I have the numpy package installed, but when I run a test on it I keep getting the error: "ModuleNotFoundError: No module named 'pickle5"
When I go to install pickle5, I get another error that just says:
ERROR: Command errored out with exit status 1
I tried putting "pip install pickle5" into my system terminal and that gave me a similar error.
Also had this problem with scipy and would really appreciate some help.

**Comment by charris** [comment]
Pickle5 is new in Python3.8 so needs to be installed for previous versions as you have attempted. My guess is that pip points to a different python version than you are using in the terminal. Try doing `python3 -mpip install pickle5 --user`.

**Comment by charris** [comment]
What versions of Python/NumPy are you using? The test really should be skipped if pickle5 is not available.

**Comment by Noodledoms** [comment]
> Pickle5 is new in Python3.8 so needs to be installed for previous versions as you have attempted. My guess is that pip points to a different python version than you are using in the terminal. Try doing python3 -mpip install pickle5 --user.

>What versions of Python/NumPy are you using? The test really should be skipped if pickle5 is not available.

I tried that now and got : 
'-mpip' is not recognized as an internal or external command,
operable program or batch file.
And I'm using python 3.8.1 with Pycharm, what do you mean the test should be skipped?

**Comment by charris** [comment]
Did you run exactly as shown?
```
charris@fc [numpy.git (master)]$ python3.8 -mpip --version
pip 19.0.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

```
There should be no problem if you are actually running 3.8.1, although ISTR previous problem reports about pycharm. Where did you get Python? Do you have several versions hanging around? Are you on Windows?

**Comment by Noodledoms** [comment]
I installed it from python.org, this is the only version I have, and I am on windows. I didn't run that exactly, but when I did that now, it said "19.0.3" is and unknown command?

**Comment by charris** [comment]
The second line is the output from the first line, not part of the command. I'm pretty sure there is an problem with your installation, which can be tricky on Windows. We usually recommend running [anaconda](https://www.anaconda.com) or some other standard distribution on Windows. There is a PyCharm for Anaconda. Are you running the professional or community version?

**Comment by Noodledoms** [comment]
Community version, I see the "Create Project" with "Conda", but I can't find a location where it will let me create it.

**Comment by mattip** [comment]
I think this is an issue with your PyCharm installation, and not one for the NumPy issue tracker. Perhaps searching around for instructions on installing pycharm and anaconda (like [this tutorial](https://ericzhng.github.io/eric-blogs/2018/10/17/tensorflow-pycharm) would be more productive. In general, the steps are
- Install PyCharm (you have done this, so no need to redo)
- Install Anaconda by downloading from [anaconda](https://www.anaconda.com/download/#windows)
- Tell PyCharm to use that enviroment

**Comment by mattip** [comment]
Closing, please reopen if there is a specific problem with NumPy.
