### ISSUE TITLE
BUG: np.where converts floats to int

### ISSUE THREAD

**Issue by pensono** [numpy/numpy#15148]
### Reproducing code example:

```python
import numpy as np

data = np.arange(0, 1, .1)
print(data)
test = np.where(data < .5)
print(test)
```

### Error message:

Expected to print:
```
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0., .1, .2, .3, .4]
```

Actually prints:
```
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
(array([0, 1, 2, 3, 4], dtype=int64),)
```

It seems that `np.where` is also returning a single element tuple.

### Numpy/Python version information:

1.17.4 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by mattip** [comment]
xref gh-12470, [this change](https://github.com/numpy/numpy/pull/12470/files#diff-f34f42e8ed03fa7919591120abdd9133L379) seems wrong.

**Comment by mattip** [comment]
it seems the change is right but there is some other problem

**Comment by mattip** [comment]
This is [documented](https://numpy.org/devdocs/reference/generated/numpy.where.html), and is functioning according to the note at the top of the documentation.
> When only `condition` is provided, this function is a shorthand for `np.asarray(condition).nonzero()`. Using `nonzero` directly should be preferred, as it behaves correctly for subclasses. The rest of this documentation covers only the case where all three arguments are provided.

Closing. Please reopen if something still is not clear.

**Comment by eric-wieser** [comment]
You're looking for `data[data < .5]`
