### ISSUE TITLE
f2py: dealing with a user-defined type sequence

### ISSUE THREAD

**Issue by rgalarcia** [numpy/numpy#15157]
I am trying to make a Python wrapper of a Fortran code using _f2py_. The Fortran code is a subroutine which defines the following argument with a user-defined type:

`type( tm_code_retour ) :: ier`

This _'tm_code_retour'_ type is in its turn defined in an external Fortran module which is properly imported into the subroutine. The definition of the type in the Fortran module is as follows:

```
type tm_code_retour     
   ! utile pour toutes les routines utilisateurs

   sequence
   integer                   :: valeur    ! valeur du code retour
   integer                   :: routine   ! numero de la routine
   integer                   :: biblio    ! bibliotheque
   character(len=pm_message) :: message   ! message

end type tm_code_retour
```

However, the creation of the Python wrapper with _f2py_ fails, with the following error:

> getctype: No C-type found in "{'typespec': 'type', 'typename': 'tm_code_retour'}", assuming void.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/__main__.py", line 6, in <module>
>     main()
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 683, in main
>     run_compile()
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 650, in run_compile
>     setup(ext_modules=[ext])
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/distutils/core.py", line 171, in setup
>     return old_setup(**new_attr)
>   File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/distutils/command/build.py", line 47, in run
>     old_build.run(self)
>   File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 148, in run
>     self.build_sources()
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 165, in build_sources
>     self.build_extension_sources(ext)
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 325, in build_extension_sources
>     sources = self.f2py_sources(sources, ext)
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 562, in f2py_sources
>     ['-m', ext_name]+f_sources)
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 457, in run_main
>     ret = buildmodules(postlist)
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 384, in buildmodules
>     dict_append(ret[mnames[i]], rules.buildmodule(modules[i], um))
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/rules.py", line 1194, in buildmodule
>     api, wrap = buildapi(nb)
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/rules.py", line 1368, in buildapi
>     vrd = capi_maps.sign2map(a, var[a])
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/capi_maps.py", line 603, in sign2map
>     ret['pydocsign'], ret['pydocsignout'] = getpydocsign(a, var)
>   File "/home/developer/.local/lib/python3.6/site-packages/numpy/f2py/capi_maps.py", line 412, in getpydocsign
>     sig = '%s : %s %s%s' % (a, opt, c2py_map[ctype], init)
> KeyError: 'void'

I reckon that _f2py_ fails because it does not identify an analogous C type for the user-defined Python type, and it wrongly assigns void as the type of the argument, when it is a Fortran sequence. Can this be solved?

Reading documentation, I have found that a _.f2py_f2cmap_ file can be created in the same folder as the Fortran subroutine, and that the mapping between user-defined and C types can be manually specified there. However, I have only found examples for single user-defined arguments, not sequences. Thus, I am in doubt about if user-defined sequences are supported by _f2py_, and if so, what is the fix for proper wrapping to Python.

**Comment by nedlrichards** [comment]
Does this mean that user defined types are a total no go for f2py? Would it make sense to add a note in the documentation if this is the case?

**Comment by HaoZeke** [comment]
Closing in favor of https://github.com/numpy/numpy/issues/21160.
