### ISSUE TITLE
Docs don't mention that NumPy 1.18 requires cython for build

### ISSUE THREAD

**Issue by virtuald** [numpy/numpy#15151]
Install documentation doesn't mention that Cython is now required to build wheels (as implemented in https://github.com/numpy/numpy/commit/d630d96598f1b7ea044d60bea8cd2b87778f072a).

https://numpy.org/devdocs/user/building.html:

> To build development versions of NumPy, you’ll need a recent version of Cython. Released NumPy sources on PyPi include the C files generated from Cython code, so for released versions having Cython installed isn’t needed.

**Comment by rgommers** [comment]
Thanks for reporting @virtuald, I forgot about that docs page. Fix coming shortly.
