### ISSUE TITLE
setup.py bdist_wheel numpy fails on arm64

### ISSUE THREAD

**Issue by srohit0** [numpy/numpy#15168]
building numpy from source code fails on arm64 because of missing dependency Cython.

  ModuleNotFoundError: No module named 'Cython'

### Reproducing code example:

```python setup.py bdist_wheel```

### Error message:

  Running setup.py bdist_wheel for numpy: started
  Running setup.py bdist_wheel for numpy: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u485u_8l/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpijsuuig2pip-wheel- --python-tag cp36:
  Running from numpy source directory.
  Cythonizing sources
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_philox.pyx
  Traceback (most recent call last):
    File "/tmp/pip-build-u485u_8l/numpy/tools/cythonize.py", line 61, in process_pyx
      from Cython.Compiler.Version import version as cython_version
  ModuleNotFoundError: No module named 'Cython'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-build-u485u_8l/numpy/tools/cythonize.py", line 238, in <module>
      main()
    File "/tmp/pip-build-u485u_8l/numpy/tools/cythonize.py", line 234, in main
      find_process_files(root_dir)

**Comment by eric-wieser** [comment]
Perhaps we should add cython to setup_requires

**Comment by rgommers** [comment]
No, this is expected, you just need to install Cython yourself. From the PR that dropped adding generated Cython sources to the sdist (gh-14453):

Another note: this is not in `setup_requires` on purpose. For one because `generate_cython` runs before `setup(**metadata)` is invoked. For another, because if anyone runs `python setup.py install` they can simply deal with any error if they get it. And using `setup_requires` would invoke `easy_install` in some cases, which isn't nice anyway.

**Comment by rgommers** [comment]
And for completeness: `pip install .` does work, because Cython is in `pyproject.toml`. That's the right way to handle build dependencies.

**Comment by srohit0** [comment]
```pip3 install numpy``` did not work on arm64 (works on other platforms like arm, arm7, amd etc) and that kicked in ```python setup.py bdist_wheel``` which fails.

```pipe3 install numpy``` behaves differently on arm vs arm64. We've found workaround for now. 

@rgommers, closing the PR does not resolve the issue.

**Comment by eric-wieser** [comment]
> pip3 install numpy did not work on arm64

Please report a bug for that then, not a bug for your workaround which as @rgommers points out is behaving as expected.

**Comment by mattip** [comment]
What version of each of python, pip, setuptools ?
