### ISSUE TITLE
Create wheel for Alpine Linux

### ISSUE THREAD

**Issue by aviramha** [numpy/numpy#15163]
My Dockerfile that installs numpy takes years to build because of compiling numpy each time.
I think many will benefit from having a pre-built wheel for Alpine Linux, and the cost should be minimal.

I wanted to create a PR but couldn't find if there's automation for pushing to PyPi..

**Comment by rgommers** [comment]
Please use the `py3-numpy` package that Alpine provides: https://pkgs.alpinelinux.org/packages?name=*numpy.

Alpine is not manylinux compliant so I don't think we want to put wheels on PyPI.

**Comment by WillDaSilva** [comment]
@rgommers Now that [PEP 656](https://www.python.org/dev/peps/pep-0656/) has been accepted, this should be reconsidered.

**Comment by rgommers** [comment]
Makes sense, reopening. Thanks @WillDaSilva

**Comment by mattip** [comment]
It would be good if a tool like multibuild or cibuildwheel grew support for PEP 656 wheels, that would make it easier to support not only NumPy but Scipy and others as well.

**Comment by mattip** [comment]
Closing this since #20089 is more complete, even though this issue is earlier. Please continue the discussion there.
