### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by JustM57** [numpy/numpy#15167]
I have pandas DataFrame with millions of row.
Then I use groupby and calculate quantiles.
The idea is that I perform this calculation in a loop chunkway.
On the second step I recieve an error message on the line "dfg.quantile(all_quantiles)"
The bug appears if the data is quite large. I don't have any problem with the RAM size. 90% is free

here is my function:

`
def create_pool(data):
     groups=['YEAR','ASSURED_ID','POLICY_ID','REGION_ID','CONTRACT_PROGRAM_POPULARITY']

    dfg = data.groupby(groups)['CLINIC_OFFICE_DIST']

    dfg_stats = dfg.agg([np.mean, len]).stack()

    all_quantiles = [.0, .5, .25, .75]

    print(dfg_stats.shape)
    dfg_quantiles = dfg.quantile(all_quantiles)
    print(dfg_quantiles.shape)

    dfg_stats = dfg_stats.append(dfg_quantiles).sort_index()

    dfg_stats = dfg_stats.reset_index(level=5)

    dfg_stats.columns = ['stat', 'dist']

    dfg_stats = dfg_stats.pivot_table(values='dist', index=['YEAR', 'ASSURED_ID', 'POLICY_ID', 'REGION_ID', 'CONTRACT_PROGRAM_POPULARITY'], columns='stat')

    dfg_stats.columns = dfg_stats.columns.map(lambda x: 'DISTANCE_' + str(x).upper())

    data = data.merge(dfg_stats, left_on=['YEAR', 'ASSURED_ID', 'POLICY_ID', 'REGION_ID', 'CONTRACT_PROGRAM_POPULARITY'], right_index=True,
                      how='left').drop_duplicates()

    data = data.swifter.set_npartitions(19).allow_dask_on_strings(enable=True).apply(
        create_distance_metrics, axis=1)

    data['DIST_MEAN'] = 100 * data['CLINIC_OFFICE_DIST'] / data['DISTANCE_MEAN']

    data = data.drop(dfg_stats.columns, axis=1)

    return data`

> munmap_chunk(): invalid pointer
> 
> Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

numpy: 1.17.3 
sys: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0]

**Comment by JustM57** [comment]
Found exactly what was the problem. My first thought was the size... But actually the reason is that initial data was containing NaNs in REGION_ID.

**Comment by seberg** [comment]
I assume tat you found the issue means I can close this? I will do this, please note if there is an issue here with numpy.
