### ISSUE TITLE
Enhanced? NEP29 calculator

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpy#15173]
The proposed NEP29 script is good, but I find that it lacks in 2 areas:

1. Data must be manually entered.
2. It doesn't have a rule input for the number of minimum minor versions.

This gist attempts to solve it:
https://gist.github.com/hmaarrfk/0e2a01d57f07f55eb99d177da92691b6

Not sure where it best first in the ecosystem, but I want to use this to justify dropping `scipy < 1` for scikit-image so I figured I would share.

Comments are appreciated.

**Comment by mattip** [comment]
If we could rewrite it in javascript, we could make it part of the website

**Comment by tacaswell** [comment]
Might as well package it and put it on pypi?  Should also include a python version as part of the output.

**Comment by hmaarrfk** [comment]
python version?

i guess i could create a nep29 calculator.

**Comment by hmaarrfk** [comment]
https://github.com/hmaarrfk/nep29

PRs welcome for command line utility and whatnot.

**Comment by hmaarrfk** [comment]
>  Should also include a python version as part of the output.

Do you mean the part of nep29 that discusses the python versions to support? A PR would be welcome.

**Comment by bsipocz** [comment]
How do you feel about closing this and instead point users to use the website and tools in SPEC0 for the version drop calendar, webpage, etc?

 https://scientific-python.org/specs/spec-0000/

**Comment by hmaarrfk** [comment]
In `SPEC-0000` I cannot enter a random 3rd party package name. 


```
$ nep29 pydantic
| version |    date    |
|:-------:|:----------:|
|  2.3.0  | 2023-08-23 |
|  2.2.0  | 2023-08-17 |
|  2.1.0  | 2023-07-25 |
|   2.0   | 2023-06-30 |
|  1.10.0 | 2022-08-30 |
|  1.9.0  | 2021-12-31 |

**Comment by bsipocz** [comment]
Strictly speaking NEP29 is for policies for Python and Numpy versions only. The document it self is not really going into details about third party support, nor promises a maintained tool. 
However, but we did that generalization in SPEC0.  So I would suggest to upstream any generic, and tool related issues upstream, and therefore close this issue here, rather than mix that into NEP29.

**Comment by hmaarrfk** [comment]
i thought this issue was opened on the `nep29` page. I don't have the bandwidth to work on this, if somebody from numpy wants it, they can re-open.
