### ISSUE TITLE
Intel/ubuntu: Fails to build on PyPy 

### ISSUE THREAD

**Issue by braid3** [numpy/numpy#15171]
Fails to build on PyPy
### Reproducing code example:

```python
import numpy 
```

### Error message:
Traceback (most recent call last):
  File "/home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/_multiarray_umath.pypy36-pp73-x86_64-linux-gnu.so)

### Numpy/Python version information:
1.16.65/2.7.13 (724f1a7d62e8, Dec 23 2019, 15:36:24)
[PyPy 7.3.0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

-------------------------------------------------------------------------------------
- I installed pypy with gnome-software.  
    get-app builds a different pypy (7.1.1+dfsg-1) but results in the same problem. 

- how to install numpy:  
   1. $ pypy get-pip.py --user  
   2. $ pypy -m pip install numpy --user  

- Operating system: Ubuntu 19.10 (18.04 LTS has the same problem) 
-------------------------------------------------------------------------------------------------------
**Output from 'import sys, numpy**
Traceback (most recent call last):
  File "/home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/_multiarray_umath.pypy36-pp73-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/donguk/.local/lib/pypy3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/snap/pypy3/50/bin/pypy3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/donguk/.local/lib/pypy3.6/site-packages/numpy/core/_multiarray_umath.pypy36-pp73-x86_64-linux-gnu.so)

**Comment by mattip** [comment]
Can reproduce
```
$curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$snap install --classic pypy3
$pypy3 get-pip.py --user
$pypy3 -mpip install --user cython
$pypy3 -mpip install --user numpy
$pypy3 -c "import numpy"
```
It prints the same error message.
I can

**Comment by braid3** [comment]
The same error appears on my laptop with your command list.

**Comment by mattip** [comment]
It seems to be specific to the snap. If I download the regular release, it works fine
```
$ curl https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.0-linux64.tar.bz2 \
               -o pypy3.tar.bz2
$ tar -xf pypy3.tar.bz2
$ pypy3.6-v7.3.0-linux64/bin/pypy3 -mensurepip
$ pypy3.6-v7.3.0-linux64/bin/pypy3 -mpip install --force-reinstall --no-cache-dir \
          cython numpy
$ pypy3.6-v7.3.0-linux64/bin/pypy3 -c "import numpy"
```
No error

**Comment by mattip** [comment]
xref stefanor/pypy3-snap#1

**Comment by braid3** [comment]
I have a download problem.

$ curl https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.0-linux64.tar.bz2 -o pypy3.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
