### ISSUE TITLE
dsTypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### ISSUE THREAD

**Issue by moranavni** [numpy/numpy#15188]
I am running a program on Python and I try to generate statistics outputs from an array.
The code line:
 regressor_OLS = sm.OLS(y,X_opt).fit() 
is given an elaborate error.

This is the code
# Multiple Linear Regression

# Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing the dataset
dataset = pd.read_csv('50_Startups.csv')

#Getting the independent variables
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values
print (dataset)

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [3])], remainder = 'passthrough')
X = ct.fit_transform(X)
      
# Avoiding the Dummy Variable Trap
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =0)

# Fitting Multiple Linear Regression Model to the Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)

#Building the Optimal Model using Backward Elimination
import statsmodels.api as sm

#Add columns of 1
X= np.append(arr = np.ones((50,1)).astype(int), values = X, axis =1)
X_opt = X[:,[0,1,2,3,4,5]]

#Multiple Linear Regression Model --- OLS
regressor_OLS = sm.OLS(y,X_opt).fit()
regressor_OLS.summary()

### Reproducing code example:

```python
import numpy as np

### Error message:
ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

<!-- Full error message, if any (starting from line Traceback: ...) -->


  File "C:\Users\morana\Documents\AI\UDEMY\Machine Learning A-Z\Part 2 - Regression\Section 5 - Multiple Linear Regression\multiple linear regression.py", line 46, in <module>
    regressor_OLS = sm.OLS(y,X_opt).fit()

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py", line 838, in __init__
    hasconst=hasconst, **kwargs)

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py", line 684, in __init__
    weights=weights, hasconst=hasconst, **kwargs)

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py", line 196, in __init__
    super(RegressionModel, self).__init__(endog, exog, **kwargs)

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\model.py", line 216, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\model.py", line 68, in __init__
    **kwargs)

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\model.py", line 91, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\data.py", line 635, in handle_data
    **kwargs)

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\data.py", line 80, in __init__
    self._handle_constant(hasconst)

  File "C:\Users\morana\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\data.py", line 125, in _handle_constant
    if not np.isfinite(ptp_).all():

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### Numpy/Python version information:
Spyder 4.0.0
1.17.4 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by filip-stolinski** [comment]
Hey!
Your X_opt array has a dtype of object and this may be causing an error. Try changing it to float. For example you can use this:
X= np.append(arr = np.ones((50,1)).astype(int), values = X, axis =1)
X_opt = X[:,[0,1,2,3,4,5]]
X_opt = np.array(X_opt, dtype=float)

Have fun :D

**Comment by riderman10000** [comment]
Thanks @filip-stolinski  for your solution

**Comment by AliRazaPanjwani** [comment]
@filip-stolinski Thank you very much for your solution. It definitely Works

**Comment by mattip** [comment]
Closing. Please reopen or open a new issue if needed.

**Comment by Dev-Gaju** [comment]
Thanks @filip-stolinski

**Comment by sidalikharef** [comment]
@filip-stolinski  thank you that works for me <3

**Comment by SamuelOsondu** [comment]
Thanks so much!!

**Comment by TyrionLannisterr** [comment]
you are my God

**Comment by TyrionLannisterr** [comment]
X_opt = X_train[:, [0, 1, 3, 4]]
X_opt = np.array(X_opt, dtype=float)
X_opt = sm.add_constant(X_opt)
# data = np.append(X_train, values=y_train[:, np.newaxis], axis=1)
# regressor_OLS = sm.ols(formula='y~0+1+2+3+4', data=pd.DataFrame(data))
# regressor_OLS.fit().summary()
X = np.random.rand(40, 2)*10000000
X=sm.add_constant(X)
model = sm.OLS(y_train, X_opt)
