### ISSUE TITLE
Getting a Type Error while using np.unique with array of dtype=object

### ISSUE THREAD

**Issue by Jerevia** [numpy/numpy#15199]
Getting a `TypeError` while using `np.unique` with array of `dtype=object`

### Reproducing code example:

```python
import numpy as np

a = np.array([1, 2, 3, 2, 'a', 'b', 'a'], dtype=object)
np.unique(a)
```

### Error message:
```
----> 1 np.unique(a)

<__array_function__ internals> in unique(*args, **kwargs)

~/miniconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts, axis)
    260     ar = np.asanyarray(ar)
    261     if axis is None:
--> 262         ret = _unique1d(ar, return_index, return_inverse, return_counts)
    263         return _unpack_tuple(ret)
    264 

~/miniconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py in _unique1d(ar, return_index, return_inverse, return_counts)
    308         aux = ar[perm]
    309     else:
--> 310         ar.sort()
    311         aux = ar
    312     mask = np.empty(aux.shape, dtype=np.bool_)

TypeError: '<' not supported between instances of 'str' and 'int'
```

### Numpy/Python version information:

1.18.0 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by subhrm** [comment]
It worked fine for me !

    >>> a = np.array([1, 2, 3, 2, 'a', 'b', 'a'])
    >>> np.unique(a)
    array(['1', '2', '3', 'a', 'b'], dtype='<U21')
    >>> np.__version__
    '1.18.0'
    >>> import sys
    >>> sys.version
    '3.7.5 (default, Nov  7 2019, 10:50:52) \n[GCC 8.3.0]'

**Comment by Jerevia** [comment]
> It worked fine for me !
> 
> ```
> >>> a = np.array([1, 2, 3, 2, 'a', 'b', 'a'])
> >>> np.unique(a)
> array(['1', '2', '3', 'a', 'b'], dtype='<U21')
> >>> np.__version__
> '1.18.0'
> >>> import sys
> >>> sys.version
> '3.7.5 (default, Nov  7 2019, 10:50:52) \n[GCC 8.3.0]'
> ```

Sorry for this careless, I forgot to add the `dtype=object` argument, already updated now.

**Comment by mattip** [comment]
Since the docstring of unique states "Returns the sorted unique elements of an array", I think this is a "can't fix": we cannot sort a mixture of strings and integers.

Object arrays are supported as long as the underlying objects are well behaved. In many cases object arrays work, but in this instance it does not. A `set` might be better suited to your use case: `set([1, 1, 1, 'a', 'b'])` -> `set(['a', 1, 'b'])`

**Comment by WarrenWeckesser** [comment]
@Jerevia, thanks for reporting the issue.  This issue is a duplicate of https://github.com/numpy/numpy/issues/641, so I'm closing it.  Further discussion should be continued in the old issue, which is still open.
