### ISSUE TITLE
BUG: Array creation functions with very large argument crashes Python

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#15193]
This is on macOS 10.12.6.  Executing `np.arange(2**33)` crashes the interpreter:
```
~$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.19.0.dev0+c18b3f5'
>>> np.arange(2**33)
Killed: 9
```

This appears to be an old problem.  It crashes like this in NumPy 1.8.0rc1 (the version installed with the macOS system python).

**Comment by WarrenWeckesser** [comment]
Once I started looking into this, I realized it is a problem I've seen before, and I don't think there is an easy solution.  It comes down to `malloc` "succeeding" without actually allocating physical memory.  The OS only attempts to allocate physical memory when the process tries to use the memory.  When the requested allocation is too big, the OS fails to find a physical block of memory, and kills the process.

Anything that allocates a big enough array will likely show the same behavior.  For example,

```
In [1]: import numpy as np                                                      

In [2]: a = np.ones(2**33, dtype=int)                                           
Killed: 9
```

Here's a simple C program to demonstrate:

```c
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
    long n = 8589934592;
    long *p = malloc(n*sizeof(long));
    if (!p) {
        printf("malloc failed\n");
        return -1;
    }
    printf("malloc succeeded.\n");
    for (long i = 0; i < n; ++i) {
        p[i] = i;
    }
    printf("Done!\n");

    return 0;
}
```
```
$ gcc main.c -o main
$ ./main
malloc succeeded.
Killed: 9
$
```

cf. https://github.com/numpy/numpy/pull/11959

**Comment by undali** [comment]
Is it OS dependent?
My ubuntu 19.10's malloc() return NULL, if it can't allocate large memory.

Numpy shows error too:
`>>> np.arange(2**33)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: Unable to allocate array with shape (8589934592,) and data type int64

>>> numpy.__version__
'1.17.4'
`

**Comment by seberg** [comment]
Should be reproducable on your ubuntu. Most operating systems overallocate I believe. I.e. the sum of all memory used by all programs exceeds the actual available memory on the system. So there should be a sweetspot where you can reproduce it. However, you will have to adjust the values to your systems, just keep reducing the size of your array until you do not get the `MemoryError` immediately (if you have swap this may be very slow once you do not get the error).

**Comment by WarrenWeckesser** [comment]
I don't think this is something we can fix, so I'm closing the issue.
