### ISSUE TITLE
numpy multithreading bug

### ISSUE THREAD

**Issue by regissss** [numpy/numpy#15190]
Recently, I made a [post on stackoverflow](https://stackoverflow.com/questions/59445147/weird-bug-in-pandas-and-numpy-regarding-multithreading) showing a threading bug in Numpy. But almost 5 days passed, I got no answer.

Could someone help take a look?

Numpy/Python version information:
1.17.2 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0]

**Comment by rgommers** [comment]
You got a bunch of feedback, and as comments on SO suggest this is not a NumPy issue. It's specific to Intel/Anaconda patches made to NumPy in the conda defaults or IntelPython distribution. 

I believe this may have been removed in the most recent Numpy version in the conda `defaults` channel. If not, you can report it at https://github.com/ContinuumIO/anaconda-issues

**Comment by regissss** [comment]
@rgommers Thank you so much for reply.
