### ISSUE TITLE
Test failures on Fedora

### ISSUE THREAD

**Issue by limburgher** [numpy/numpy#15202]
==================================== ERRORS ====================================
_ ERROR collecting build/testenv/lib64/python3.7/site-packages/numpy/core/tests/test_multiarray.py _
ImportError while importing test module '/home/gwyn/fedora/git/numpy/numpy-1.18.0/build/testenv/lib64/python3.7/site-packages/numpy/core/tests/test_multiarray.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
numpy/core/tests/test_multiarray.py:23: in <module>
    from test.support import no_tracing
E   ModuleNotFoundError: No module named 'test'
_ ERROR collecting build/testenv/lib64/python3.7/site-packages/numpy/core/tests/test_regression.py _
ImportError while importing test module '/home/gwyn/fedora/git/numpy/numpy-1.18.0/build/testenv/lib64/python3.7/site-packages/numpy/core/tests/test_regression.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
numpy/core/tests/test_regression.py:20: in <module>
    from test.support import no_tracing
E   ModuleNotFoundError: No module named 'test'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
176 deselected, 2 error in 12.55 seconds
error: Bad exit status from /var/tmp/rpm-tmp.llNGWr (%check)

The project builds fine. This began during the 1.18.0 RCs.

**Comment by pv** [comment]
In Fedora, the file is in `python3-test` package.

**Comment by pv** [comment]
@mattip: numpy probably shouldn't use the `test` module --- its documentation says "Any use of this package outside of Python’s standard library is discouraged as code mentioned here can change or be removed without notice between releases of Python."

**Comment by limburgher** [comment]
> In Fedora, the file is in `python3-test` package.

This works, thanks!
