### ISSUE TITLE
Feature request: np.random.categorical

### ISSUE THREAD

**Issue by carlosgmartin** [numpy/numpy#15201]
Add a function `np.random.categorical` that samples from *multiple* [categorical distributions](https://en.wikipedia.org/wiki/Categorical_distribution) simultaneously. It should take as an argument an array `p` that has the category probabilities along the last axis, i.e. `(p.sum(-1) == 1).all()`. [`np.random.multinomial`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.multinomial.html) and [`np.random.choice`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.choice.html) only sample from a single categorical distribution.

### Reproducing code example:

```python
import numpy as np
def categorical(p):
    return (p.cumsum(-1) >= np.random.uniform(size=p.shape[:-1])[..., None]).argmax(-1)
```

**Comment by rgommers** [comment]
Thanks for the suggestion @carlosgmartin. I'm afraid that this is too niche to add to NumPy. In addition, as you show it's a one-liner, and we prefer not to add such utility functions.

**Comment by carlosgmartin** [comment]
@rgommers Thanks for your reply. I strongly disagree that this is niche. The categorical distribution (a loaded dice roll) is absolutely pervasive in scientific computing, perhaps second only to the uniform distribution. It's certainly no more niche than most functions in [`np.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html). I've constructed a convenient one-liner for it, but my request is for the benefit of other users who may not know how to construct such a one-liner and resort to less efficient means (like Python for loops).

If you do change your mind, consider extending `numpy.random.choice` to handle a multidimensional `p` to achieve the same end without adding a new function.

**Comment by rgommers** [comment]
> ... is absolutely pervasive in scientific computing, perhaps second only to the uniform distribution. It's certainly less niche than the vast majority of functions ...

eh, no - there's a reason it has never been asked for before (I just searched this issue tracker to confirm), and the distribution has only been mentioned once (in gh-14117). try to be less sure in your assertions:)

extending `choice` to accept a multi-dimensional `p` is more acceptable. as a distribution, if it would go anywhere, `scipy.stats` is probably more appropriate.

**Comment by carlosgmartin** [comment]
> try to be less sure in your assertions:)

@rgommers The categorical distribution is often used without being referred to as such. Did you search for `random.choice`? That's a categorical distribution. It returns more results than any other `random.*` distribution I searched for.

I also searched `"categorical" language:Python` on GitHub and got 1M+ code hits (`"categorical distribution"` yields 19K+).

**Comment by grisaitis** [comment]
I think both of you make good points. 

I would also like to see `categorical` included. But I understand the API cluttering and code maintenance overhead. 

Reasons for:
- very basic distribution
- other convenience distributions are included (`binomial` is subsumed by `multinomial`)
- potential optimizations compared to `multinomial(1, ..)`

Reasons against:
- API clutter / tech debt
- `bernoulli` doesn't exist either
- no one has asked until @carlosgmartin and I
- `multinomial(1, pvals, size)` works
- R doesn't have it ([distributions](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Distributions.html))

**Comment by carlosgmartin** [comment]
@grisaitis Does [`multinomial`](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.multinomial.html) work with multidimensional `pvals`?

**Comment by grisaitis** [comment]
> @grisaitis Does multinomial work with multidimensional pvals?

Good question. No.

All samples are from the same parameterized distribution (same probability vector). This differs from `norm` for example.

**Comment by yoavram** [comment]
I would love to see multinomial that takes multidimensional `pvals`, this would be extremely useful for implementing multi-type Wright-Fisher simulations.

**Comment by bashtage** [comment]
@rgommers There is a relatively straight forward feature enhancement here to support multidimensional pvals in multinomial that would nest this original request. Should this issue be reopened with a different title?

**Comment by rgommers** [comment]
> Should this issue be reopened with a different title?

That makes sense, thanks @bashtage

**Comment by bashtage** [comment]
The broadcast support for multinomial basically solves this with a single `argmax`. It is awaiting review.

**Comment by altosaar** [comment]
Fantastic - thanks for letting us know @bashtage !
