### ISSUE TITLE
DOC: linear algebra section of quickstart tutorial is incomplete

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#15204]
The [Quickstart Tutorial](https://numpy.org/devdocs/user/quickstart.html) through version 1.19.dev0 contains an incomplete section on linear algebra near the end of the page.

The section starts off with the statement: "Work in progress. Basic linear algebra to be included here." which seems like it is a reminder for developers rather than user-facing documentation. 

I searched through the issues and didn't see this raised anywhere; I wanted to make sure it was raised so that it doesn't fall through the cracks.

**Comment by AND2797** [comment]
I would like to work on this!

**Comment by sushmanthnatha** [comment]
I am ready and interested to work on this issue

**Comment by mattip** [comment]
I think this has been started in gh-15295

**Comment by devangmukherjee** [comment]
I have completed the required issue and I would like to raise a PR.
@mattip

**Comment by devangmukherjee** [comment]
#15490 this is my PR and it has passed the test too
