### ISSUE TITLE
DOC: Missing entry in the list of avalaible ufunc

### ISSUE THREAD

**Issue by hippo91** [numpy/numpy#15214]
Hi and thank you for your remarkable work on `numpy`.
This issue concerns the documentation of `numpy`, that's why i'm not using the standard issue template.
In the list of available `ufunc` functions i do not see any entry concerning the `float_power` function.
However it seems that this function has all the attributes of a `ufunc` instance.
I'm i wrong?
Thanks again.

**Comment by mattip** [comment]
If you mean [here](https://numpy.org/devdocs/reference/ufuncs.html#available-ufuncs), then yes, it seems it is missing. The source for that is [here](https://github.com/numpy/numpy/blob/v1.18.0/doc/source/reference/ufuncs.rst#available-ufuncs), would you like to make a PR to add it? You might also check that all the functions `[x for x in dir(np) if isinstance(getattr(np, x), np.ufunc)]` are listed.

**Comment by hippo91** [comment]
@mattip ok i'm gonna make a PR ASAP.

**Comment by hippo91** [comment]
@mattip , thanks to the following code https://gist.github.com/hippo91/eed099df061fe399502c05aa99cd9531, i found that the ufunc instances:
  - abs
  - matmul
  - float_power
  - degrees
  - radians
  - bitwise_not

are not documented. I added them to the `ufuncs.rst` file and i can see them on the corresponding html file (`build/html/reference/ufuncs.html`) however for two of them (`abs`, `bitwise_not`) the link toward the specific documentation is broken. 
This seems to be due to the fact that those two functions are infact aliases of, respectively, `absolute` and `invert`. 
I modified the `ufunc_docstrings.py` file in order to add specific entries for both functions but i can't figure out how this module can generate `rst` or `html` files. 
Can you give me an hint please?
Thanks in advance

**Comment by rossbar** [comment]
Thanks for looking into this @hippo91. The failure to generate autolinks to numpy aliases is a more general problem that affects more than just the ufunc docs (for example: `np.row_stack`, which is an alias of `np.vstack` has the same issue, though the documentation is generated by a different mechanism).

My two cents: I recommend that you create a PR that documents the non-aliases (i.e. leave out `abs` and `bitwise_not`). You can then create an issue for the alias-documenting problem.

**Comment by hippo91** [comment]
@rossbar thanks for your answer.
I made the first PR and will do the next one ASAP.

**Comment by hippo91** [comment]
As the first PR has been accepted, i close this issue and will open another one for alias-documenting problem.
