### ISSUE TITLE
`np.load` should accept an `out` argument

### ISSUE THREAD

**Issue by jakelevi1996** [numpy/numpy#15210]
When I am saving and loading multiple arrays from a .npz file, I have to do it like this:

```python
np.savez(filename, out1, out2, out3, etc)

# Later in the code:

with np.load(filename) as loaded_data:
    (
        out1, out2, out3, etc
    ) = (loaded_data[name] for name in loaded_data.files)
```

Various numpy functions accept an `out` argument to specify the output array, EG:

```python
numpy.dot(a, b, out=None)
```

It would be neat if I could load multiple arrays from a .npz file using this same syntax; it might look something like this:

```python
np.load(filename, out=[out1, out2, out3, etc])
```

**Comment by eric-wieser** [comment]
Out arguments are usually only there to avoid allocations. In particular, what you suggest would only work if you already know the shape and type of the file contents before opening it.

**Comment by rossbar** [comment]
This feature proposal didn't generate much discussion here, so I'm going to close it. If anyone is interested in restarting the discussion, please consider posting a proposal to the mailing list.
