### ISSUE TITLE
wrong result of np.inner of two column vectors

### ISSUE THREAD

**Issue by w19787** [numpy/numpy#15234]
Per definition of Euclidean inner product, if u, v are same dimension vector, the inner product (u, v) = u(transpose)v, but the following numpy inner operator return matrix instead scalar

import numpy as np
cv = np.arange(1,4).reshape(3,1)
cw = np.arange(5,8).reshape(3,1)
np.inner(cv, cw)

and if you calculate np.outer(cv, cw). the result is same as np.inner. is this A BUG?
>>
array([[ 5,  6,  7],
       [10, 12, 14],
       [15, 18, 21]])

so what is definition of inner product of two column vector in numpy?

**Comment by eric-wieser** [comment]
[the notes](https://docs.scipy.org/doc/numpy/reference/generated/numpy.inner.html) in the docs are fairly clear on this - inner sums the products of the last two axes.

**Comment by w19787** [comment]
> [the notes](https://docs.scipy.org/doc/numpy/reference/generated/numpy.inner.html) in the docs are fairly clear on this - inner sums the products of the last two axes.

do you think the docs is conflicted with linear algebra inner product definition? how to explain the result of inner and outer product is same for "column" vector?
