### ISSUE TITLE
gcc -std=c99 flag and excess floating point precision handling

### ISSUE THREAD

**Issue by pv** [numpy/numpy#15237]
Numpy 1.18.0 adds `-std=c99` unconditionally to C compiler options. This has indirect consequences, dealing with which may be annoying for downstream projects.

One issue is that for gcc, `-std=c99` also turns on `-fexcess-precision=standard` which causes floating-point behavior changes with `-mfpmath=387` (i.e. typically on by default on i386 platform, but not on x86_64).

A particular point here is that the floating point literal macros in `npy_math.h` probably would need casts added, along the lines of `#define NPY_PI_2     ((double)1.570796326794896619231321691639751442)` in order to behave in a non-surprising way.

Granted, downstream projects maybe can fix this type of problems in their code, but I'm not sure if Numpy should force the compiler configuration change on them.

### Reproducing code example:

Note that `-std=c99` changes floating point excess precision handling:
```
cat <<__EOF__ > bad.c
#include <stdio.h>

int main() 
{
     double x = 1e300;
     if (x == 1e300) {
        printf("OK\n");
     } else {
        printf("FAIL\n");
    }
}
__EOF__
gcc --version
# -> gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
gcc -mfpmath=387 -I/usr/include/python3.7m -o bad bad.c
./bad
# -> OK
gcc -std=c99 -mfpmath=387 -I/usr/include/python3.7m -o bad bad.c
./bad
# -> FAIL
gcc -std=c99 -mfpmath=387 -fexcess-precision=fast -I/usr/include/python3.7m -o bad bad.c
./bad
# -> OK
```
Adding `(double)` cast before the literal makes the comparison behave as expected. This also hits e.g. numeric floating constants defined in Numpy headers.

**Comment by charris** [comment]
I'm perfectly happy to remove it. @mattip I don't recall the motivation for the change, what was it?

**Comment by mattip** [comment]
We have c99 code in pocketfft. Maybe we could add it only in that setup.py

**Comment by charris** [comment]
> We have c99 code in pocketfft.

@mattip But that wasn't a problem for the tests or the builds, we just added the flag when needed. What was the specific problem it solved?

**Comment by mattip** [comment]
We added the flag in CI. Then people built from source as part of installing another package that depends on NumPy and got build errors. gh-14702, gh-12766, gh-14147

**Comment by charris** [comment]
@mattip OK, thanks for the reminder.

**Comment by xnox** [comment]
`-std=c99` flag has unintended consequences on modern Ubuntu development release. It forces the precision to reduced on s390x and result in misscompilation to the point of loosing more than 10^-6 floating point precission.

Ubuntu in groovy defaults to at C18 standard. It would be nice for numpy configuration to test which standard the compiler defaults, and raise it to C99 if it is below C99. But never lower it down to C99.

```
$ gcc -dM -E - < /dev/null | grep STDC_VER
#define __STDC_VERSION__ 201710L

$ gcc -std=c99 -dM -E - < /dev/null | grep STDC_VER
#define __STDC_VERSION__ 199901L
```

`201710L` constant is for C18  (ISO/IEC 9899:2018).

At the moment we had to revert and remove the "std=c99" flag out of numpy. Would it be more appropriate to test that compiler is below c99 and only add that flag to raise the standard?

**Comment by charris** [comment]
> It forces the precision to reduce on s390x

Out of curiosity, why does it do that? Is poor precision part of the c99 standard?

**Comment by xnox** [comment]
> > It forces the precision to reduce on s390x
> 
> Out of curiosity, why does it do that? Is poor precision part of the c99 standard?

I was pointed at a wikipage explaining how the exponent and floating point number of digits for precision is different on S/390 because it predates C language. Thus on s390x, higher standard version is required when all of that was aligned. Or like quad precision is adequate everywhere. Let me find that again.

**Comment by xnox** [comment]
> > > It forces the precision to reduce on s390x
> > 
> > 
> > Out of curiosity, why does it do that? Is poor precision part of the c99 standard?
> 
> I was pointed at a wikipage explaining how the exponent and floating point number of digits for precision is different on S/390 because it predates C language. Thus on s390x, higher standard version is required when all of that was aligned. Or like quad precision is adequate everywhere. Let me find that again.

https://en.wikipedia.org/wiki/IBM_hexadecimal_floating_point

Maybe in addition to c99 flag we should be specifying to use the IEEE precision? or maybe just that?

With or without, s390x precision issue, for Ubuntu, I don't wish any code to use c99 anymore, because there are too much undefined behavior and bugs in c99.

**Comment by charris** [comment]
@xnox Sounds like c99 is abused to flag backwards compatibility with an outdated compiler :) Well, it is what it is.

**Comment by xnox** [comment]
> @xnox Sounds like c99 is abused to flag backwards compatibility with an outdated compiler :) Well, it is what it is.

I'm so 2008, and this stuff is so last century late =)))))))))))))))
