### ISSUE TITLE
BUG: test_umath::test_loss_of_precision[complex256] fails on  ppc64le and aarch64

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpy#15243]
It seems that `test_umath::test_loss_of_precision[complex256]` is failing on ppc64le and aarch64 on conda-forge.

Not too sure why.

But we had to skip the tests a while back.

Could be due to bug with libc.

We will make CI runs again once 1.17.5 and 1.18.0 are through.

https://github.com/conda-forge/numpy-feedstock/pull/180

**Comment by hmaarrfk** [comment]
Still a bug even with openblas 0.3.7

**Comment by charris** [comment]
What compilers/flags are you using?

**Comment by hmaarrfk** [comment]
```
+CC=$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-cc
+CFLAGS=-mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/numpy-1.17.5 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix

+CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/powerpc64le-conda_cos7-linux-gnu/sysroot/usr

+CONDA_BUILD_SYSROOT=$BUILD_PREFIX/powerpc64le-conda_cos7-linux-gnu/sysroot

+_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_powerpc64le_conda_cos7_linux_gnu

+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include

+CPP=$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-cpp

+DEBUG_CFLAGS=-mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/numpy-1.17.5 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix

+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include

+GCC_AR=$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gcc-ar

+GCC=$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gcc

+GCC_NM=$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gcc-nm

+GCC_RANLIB=$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-gcc-ranlib

+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
```

```
    _libgcc_mutex:               0.1-main           defaults   
    binutils_impl_linux-ppc64le: 2.33.1-hb209c28_7  conda-forge
    binutils_linux-ppc64le:      2.33.1-h959c939_16 conda-forge
    gcc_impl_linux-ppc64le:      8.2.0-he01c8ba_2   conda-forge
    gcc_linux-ppc64le:           8.2.0-h9f3bcec_16  conda-forge
    ld_impl_linux-ppc64le:       2.33.1-h0f24833_7  conda-forge
    libgcc-ng:                   8.2.0-h822a55f_2   conda-forge
    libstdcxx-ng:                8.2.0-h822a55f_2   conda-forge
```

https://travis-ci.com/conda-forge/numpy-feedstock/jobs/272496917#L430

^^^ This build skips the problematic test.

**Comment by seberg** [comment]
@hmaarrfk I am trying to figure out where the bug is, or how serious it is, but am unable to do so. Maybe I am missing it, but could you provide the full error failure output? As of now, I have no clue which ufunc (assuming it is that) has the error or how big it is. I assume that this is not an intel-patched version of NumPy we are talking of as well?

**Comment by hmaarrfk** [comment]
Lets wait until https://github.com/conda-forge/numpy-feedstock/pull/180 gets merged into CF, then we can simply uncomment the skip test line and iterate on it.

**Comment by mattip** [comment]
Closing since the conda-forge issue was closed. Please open a new issue as needed.

**Comment by h-vetinari** [comment]
I tried undoing this skip in https://github.com/conda-forge/numpy-feedstock/pull/227 as part of routine test skip hygiene and found that it's still an issue. Sample CI run [here](https://travis-ci.com/github/conda-forge/numpy-feedstock/builds/225387025).

Could we reopen this issue to keep the previous context, or would you like a new one?

**Comment by charris** [comment]
Reopened.

**Comment by h-vetinari** [comment]
Now that travis is back online in conda-forge (allowing us to run on native hardware and not in emulation, which had its own problems), this error still exists on PPC (though not on aarch anymore), cf. https://github.com/conda-forge/numpy-feedstock/pull/268 ([CI run](https://app.travis-ci.com/github/conda-forge/numpy-feedstock/jobs/566559818))

At first glance it looks like a run-of-the-mill tolerance violation, but it's actually pretty substantial (well, in the context of 128bit accuracy at least) - relative error of `4e-19` instead of `<1.2e-30`, so it misses by a cool 11 orders of magnitude. 😅 

```
x = array([1.00000000e-20, 1.21736864e-20, 1.48198641e-20, 1.80412378e-20,
       2.19628372e-20, 2.67368693e-20, 3.254862...5156e-04, 4.54267386e-04,
       5.53010871e-04, 6.73218092e-04, 8.19554595e-04, 9.97700064e-04],
      dtype=float128)
rtol = 1.23259516440783094595582588325435e-30
    def check(x, rtol):
        x = x.astype(real_dtype)
    
        z = x.astype(dtype)
        d = np.absolute(np.arcsinh(x)/np.arcsinh(z).real - 1)
>       assert_(np.all(d < rtol), (np.argmax(d), x[np.argmax(d)], d.max(),
                                  'arcsinh'))
E       AssertionError: (131, 1.54987431981169249551435343964035e-09, 4.0035173453529620614007210953362e-19, 'arcsinh')
```

**Comment by charris** [comment]
Hmm, The complex versions have always been difficult, but this is real. It almost seems that it is done in double, or perhaps a function adapted from double without sufficient changes. Can you determine what library it comes from?

**Comment by charris** [comment]
Also, can you check if it is detected during the build (HAVE_ASINH)?

**Comment by h-vetinari** [comment]
> Hmm, The complex versions have always been difficult, but this is real.

I haven't looked at that test in detail, but it fails only with `test_loss_of_precision[complex256]`. I guess `z` is supposed to complex and `x` is the real-only reference?

> Also, can you check if it is detected during the build (HAVE_ASINH)?

Where should this show up? Perhaps our log is not verbose enough, but I don't see it in the [logs](https://app.travis-ci.com/github/conda-forge/numpy-feedstock/builds/249197224).

**Comment by charris** [comment]
It is contained in `config.h`,  a file generated as part of the build. The easiest way to find it is to grep for something definite, say `HAVE_SIN`, among the build artifacts. AFAIK, only power 9 has quad precision, earlier models had double double.

**Comment by mattip** [comment]
If this showed up only on ppc64le, I would say it is another manifestation of #15763

**Comment by h-vetinari** [comment]
Thanks for the link @mattip. In fact, it is explicitly mentioned in the last [comment](https://github.com/numpy/numpy/issues/15763#issuecomment-809986395) there. I think the proposed solution there is reasonable as well - reuse the `bad_arcsinh`-skip from #16214 also on PPC (not just aarch).

**Comment by h-vetinari** [comment]
Somewhat related sidenote: Chasing down the git blame also lead me to stumble across https://github.com/numpy/numpy/pull/20427 - it's possible that [`get_glibc_version`](https://github.com/numpy/numpy/blob/v1.22.3/numpy/core/tests/test_umath.py#L21-L27) might be broken entirely on ppc, especially if it uses a different name for the env-var than `CS_GNU_LIBC_VERSION`.

**Comment by hmaarrfk** [comment]
I think the env-var is correct. On the conda-forge ppe64le machine:
```
(base) [hmaarrfk@conda-forge-p8-1 ~]$ python -c "import os; print(os.confstr('CS_GNU_LIBC_VERSION'))"
glibc 2.17
(base) [hmaarrfk@conda-forge-p8-1 ~]$ arch
ppc64le
```

**Comment by hmaarrfk** [comment]
Also, python uses this too:
https://github.com/python/cpython/blob/main/Lib/platform.py#L178

**Comment by charris** [comment]
On Mon, Apr 11, 2022 at 6:37 AM Mark Harfouche ***@***.***>
wrote:

> I think the env-var is correct. On the conda-forge ppe64le machine:
>
> (base) ***@***.*** ~]$ python -c "import os; print(os.confstr('CS_GNU_LIBC_VERSION'))"
> glibc 2.17
> (base) ***@***.*** ~]$ arch
> ppc64le
>
>
Makes me wonder if it is defined in the manylinux2014 docker images.

Chuck
