### ISSUE TITLE
Make the ufunc loop signature const correct

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15252]
Today, the ufunc loop signature (PyUFuncGenericFunction) is

https://github.com/numpy/numpy/blob/3883be372b6ec46b9aac612069c1281241b1a133/numpy/__init__.pxd#L844

I would argue it should be `(char **, npy_intp const *, npy_intp const*, void *)`, ie inner loops are not allowed to modify the shape or stride.

Changing this would force users to either:
* Ignore compiler warnings
* Add `const` to their loop signatures

Creating this issue now so that I can reference it internally.

**Comment by seberg** [comment]
I think it is completely fine to force downstream to adapt to compiler warnings. I am not sure it was ever correct to modify these values (maybe temporarily), but if you do such magic it is fine if you have to cast away the const manually.

**Comment by Kai-Striega** [comment]
@eric-wieser I've been looking to get more involved with the C-API, would you mind if I work on this?

**Comment by eric-wieser** [comment]
@Kai-Striega, Please do!
