### ISSUE TITLE
Conversion to Boolean with fractions.Fraction and numpy integers

### ISSUE THREAD

**Issue by francois-durand** [numpy/numpy#15277]
When defining a Fraction based on a numpy array of integers, the numerator is a numpy integer, which causes problems when converting to bool.

### Reproducing code example:

```python
import numpy as np
from fractions import Fraction
numerators = np.array([4, 3])
my_fraction = Fraction(numerators[0], 100)
print(repr(my_fraction))
print(bool(my_fraction))
```

In this example ``my_fraction`` is represented as ``Fraction(4, 100)``, and one would expect that it converts to True; but it raises an error instead.

### Error message:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    print(bool(my_fraction))
TypeError: __bool__ should return bool, returned numpy.bool_

### Numpy/Python version information:

Numpy 1.17.2
Python 3.7.4

**Comment by seberg** [comment]
Hmmm, Fraction uses `self.nominator != 0`, but we return a numpy bool for that. I am not quite sure we should change that to be honest. OTOH, there is also no reason why Fractions in python should not use `bool(self.nominator)` which gives the same result and is defined explicitly as returning a python bool.

**Comment by eric-wieser** [comment]
Agreed, this sounds like something that should be fixed upstream in cpython

**Comment by seberg** [comment]
@francois-durand do you want to open a ticket on bugs.python.org and link it? Even if python says we are doing evil things, it can be adapted there. And we can just create a PR for that as well.

**Comment by francois-durand** [comment]
Thanks for your answers. I opened a ticket on bugs.python.org: https://bugs.python.org/issue39274 .

**Comment by seberg** [comment]
I opened a PR to python to fix things there. I doubt we can change anything in NumPy in a reasonable time-frame, so closing.
