### ISSUE TITLE
np.empty_like not working with zeros array

### ISSUE THREAD

**Issue by tirthasheshpatel** [numpy/numpy#15293]
When an array created using `np.zeros` is passed as an argument to `np.empty_like`, the array is initialized to `0` instead of being uninitialized!

### Reproducing code example:
```python
a = np.zeros((2, 5), dtype=np.float32)
print(a)

b = np.empty_like(a)
print(b)
```

Output:

```
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
```

### Numpy/Python version information:

System: Linux

Numpy Version: 1.18.1

Python Version: 3.6.9

**Comment by eric-wieser** [comment]
Does seem very suspicious:
```
In [44]: a = np.arange(10, dtype=np.float32).reshape((2, 5))
    ...: print(a)
    ...:
    ...: b = np.empty_like(a)
    ...: print(b)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
```

**Comment by eric-wieser** [comment]
The threshold for this happening seems to be 1KiB of array data

**Comment by tirthasheshpatel** [comment]
Yeah! very odd it's behaving that way!

**Comment by charris** [comment]
Might be picking up temporary/cached object memory.

**Comment by seberg** [comment]
The only thing is, that this sounds a bit like we might be creating a copy of the first array here for some reason? (why can it find an identically cached version?)

**Comment by WarrenWeckesser** [comment]
The result can depend on when `print()` is called.  For example:

```
import numpy as np

a = np.zeros((2, 5), dtype=np.float32)
print(a)

b = np.empty_like(a)
print(b)
```
Output:
```
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
```
But this version
```
import numpy as np

a = np.zeros((2, 5), dtype=np.float32)
b = np.empty_like(a)

print(a)
print(b)
```
generates:
```
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0.00e+00 2.00e+00 0.00e+00 2.00e+00 4.20e-45]
 [1.63e-43 1.56e-43 1.60e-43 1.70e-43 0.00e+00]]
```
So I suspect there is nothing to be concerned about.

This is on macOS 10.12.6, with numpy 1.17.2.

**Comment by seberg** [comment]
Ahh, the print statement will probably create a temporary copy for some reason... That seems OK.

**Comment by seberg** [comment]
Thanks Warren, nice catch. I will close this. This is the caching mechanism that numpy uses to avoid many small/mid-sized allocations, and thus is simply expected here currently.
