### ISSUE TITLE
Why reshape method shows unexpected argument?

### ISSUE THREAD

**Issue by mail2chromium** [numpy/numpy#15290]
I am learning NumPy from this site: [[Numpy Org](https://numpy.org/devdocs/user/quickstart.html)]
I figured out the reshape method only takes two arguments as follows:

`    def reshape(self, shape, order='C'): # real signature unknown; restored from __doc__
`

But when I place `np.arange(24).reshape(2, 3, 4)` in Python IDLE i.e PyCharm, it is showing that the third argument is unexpected which is *" 4 "* in this case. Here is another fact, which is that the output of the `reshape()` method is ** as required ** with changing dimensions. 

Here is the referenced issue @rgommers:
![Reshape-Method-Issue](https://github.com/mail2chromium/NLP-Estimation-Analysis-Using-Python/blob/master/Untitled.png)

**Comment by matthew-brett** [comment]
But - as you said - the method only takes two arguments, and you have passed three: `2`, `3` and `4`.  You probably want:

```python
np.arange(24).reshape((2, 3, 4)) 
```

where the tuple `(2, 3, 4)` is the value for the `shape` argument.

**Comment by mail2chromium** [comment]
@matthew-brett 

Have you looked at the referenced picture given in the question. Why it is showing **"Unexpected Argument"** but the output is perfect. Why this specific indication about an argument?

**Comment by seberg** [comment]
The actual signature of the method (not the function) is: `reshape(*shape, *, order="C")` or `reshape(shape, *, order="C")`. But the second version is preferred, so the doc might only list that one. (In other words, if there is only a single argument in the arg tuple `*shape` it is treated as `shape` instead.

**Comment by seberg** [comment]
Additionally: PyCharm tries to read the signature from the `numpydoc` docstring I think, so it would suggest that the signature may be wrong based on the preference in the doc string. I think this can be closed, we probably do not want to change the docstring.

**Comment by seberg** [comment]
In case the docstring does not mention the alternative at all, it would be nice if you would want to add it though!
