### ISSUE TITLE
Output type of round is inconsistent with python built-in

### ISSUE THREAD

**Issue by Ehsan-MAE** [numpy/numpy#15297]
[Based on official python doc](https://docs.python.org/3/library/functions.html#round), the output of `round` function is integer when ndigits is omitted. However, numpy does not follow this rule, and the output of rounded numpy still is a float. I think this behavior cause bugs!

### Reproducing code example:

```python
>>> for x in np.linspace(0,1,5):
...     print(round(x * 5.))
... 
0.0
1.0
2.0
4.0
5.0
>>> for x in map(float,np.linspace(0,1,5)):
...     print(round(x * 5.))
... 
0
1
2
4
5
```

### Numpy/Python version information:
1.18.1 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]

**Comment by PhanatosZou** [comment]
take

**Comment by tsturzl** [comment]
This is an issue for me also. I wrote an algorithm and tested it with python floats, and now that I'm passing in numpy float64s I'm getting an issue where `round` returns a rounded numpy.float64 rather than an integer per the specifications of the python docs. My only work around for this is to convert all of my input data into python floats, which is a pain and also inefficient as I have to add an unnecessary loop to cast each input type simply so that round works as expected.

**Comment by charris** [comment]
Python 2 rounded floats to floats, rounding to integers came in with Python 3. NumPy needed to maintain compatibility with existing code, and I think that is still an issue even though Python 2.7 support has been dropped. The `__round__` method was also new in Python 3.

**Comment by seberg** [comment]
There are a lot of open issue here:  gh-11557, gh-5700, gh-3511, and gh-11810 (the last one included a comment listing the former).
The difficulty of scalars and 0-D arrays generally behaving the same might be another related thing, with one thing being that numpy integers will not work for things like `round(10e100)`.

I think we may be able to change this, not sure how big the priority is right now, going through the old discussion and sending a summary/suggestion to the mailing list might be the best to push this forward.

**Comment by homm** [comment]
> NumPy needed to maintain compatibility with existing code

NumPy needed to maintain compatibility with the current Python. Compatibility between python 2 and python 3 was broken, so NumPy would have to do the same.

**Comment by hameerabbasi** [comment]
I'd like to add this to triage review for this week's meeting.

**Comment by mattip** [comment]
In discussion we would propose:
- change scalar floats to return integers for `__round__`
- not change anything else: not 0d arrays and not other numpy functionality
- the proposal should hit the mailing list

**Comment by hameerabbasi** [comment]
Posted to the mailing list: https://mail.python.org/pipermail/numpy-discussion/2020-February/080442.html
