### ISSUE TITLE
ENH: add a Khatri-Rao Product function

### ISSUE THREAD

**Issue by EverLookNeverSee** [numpy/numpy#15298]
Implementation of khatri-rao product for ndarrays
[https://research.wmz.ninja/articles/2017/12/vectorization-kronecker-product-and-khatri-rao-product.html](https://research.wmz.ninja/articles/2017/12/vectorization-kronecker-product-and-khatri-rao-product.html)

@eric-wieser

**Comment by mattip** [comment]
Is this an an enhancement proposal? When filing an issue here a bit of context why you think this is a problem or what you think this may contribute would be helpful.

**Comment by EverLookNeverSee** [comment]
@mattip Yes this is an enhancement proposal. numpy already has kronecker product(np.kron) , but has not khatri-rao product .that's why it would be an enhancement for numpy.

**Comment by EverLookNeverSee** [comment]
i would like to work on this issue @mattip

**Comment by eric-wieser** [comment]
Not sure why you tagged me here. This should be a one-liner with `einsum` and `reshape`. I'd encourage you to paste an implementation here for people arriving from Google, but I see this as a little too niche for numpy, especially since we provide all the tools to build it.

**Comment by eric-wieser** [comment]
From [this reference](https://math.stackexchange.com/a/1916083/1896), the (fully vectorized) implementation is just:
```python
def khatri_rao(a, b):
    c = a[...,:,np.newaxis,:] * b[...,:,np.newaxis,:]
    return c.reshape((-1,) + c.shape[2:])  # collapse the first two axes
```

**Comment by eric-wieser** [comment]
Closing since I don't think this is fundamental enough for numpy. If it's widely used in some fields, it might have a home as `scipy.linalg.khatri_rao`.

@rgommers, does it make sense to hit the "transfer issue" button to send it there?

**Comment by rgommers** [comment]
> @rgommers, does it make sense to hit the "transfer issue" button to send it there?

It would, if that were possible. You can only transfer issues between repos in the same organization account.

@EverLookNeverSee please feel free to transfer this to https://github.com/scipy/scipy/issues and propose the function as a new feature on the [scipy-dev mailing list](https://scipy.org/scipylib/mailing-lists.html)

**Comment by eric-wieser** [comment]
Ah, I assumed that as a maintainer for both you'd be able to do that.

I can think of an awful hack where you

* create a repo called `numpy/rgommers-issue-shuttle`
* Transfer the issue to there
* Transfer the repo to `scipy/rgommers-issue-shuttle`
* Transfer the issue to `scipy/scipy`
* Transfer the issue back to `rgommers/rgommers-issue-shuttle`, ready for it's next departure

**Comment by EverLookNeverSee** [comment]
@rgommers 
i will open a new issue on scipy issue tracker

**Comment by dkl78167816** [comment]
> From [this reference](https://math.stackexchange.com/a/1916083/1896), the (fully vectorized) implementation is just:
> 
> ```python
> def khatri_rao(a, b):
>     c = a[...,:,np.newaxis,:] * b[...,np.newaxis,:,:]
>     # collapse the first two axes
>     return c.reshape((-1,) + c.shape[2:])
> ```
> 
> ```python
> >>> a = np.array(sympy.symbols('a b c d e f'), object).reshape((2, 3))
> >>> a
> array([[a, b, c],
>        [d, e, f]], dtype=object)
> >>> b = np.array(sympy.symbols('g h i j k l'), object).reshape((2, 3))
> >>> b
> array([[g, h, i],
>        [j, k, l]], dtype=object)
> >>> khatri_rao(a, b)
> array([[a*g, b*h, c*i],
>        [a*j, b*k, c*l],
>        [d*g, e*h, f*i],
>        [d*j, e*k, f*l]], dtype=object)
> ```

Also
```python
C = np.vstack([np.kron(A[:, k], B[:, k]) for k in range(A.shape[1])]).T
return C
`

**Comment by dpmccabe** [comment]
The face-splitting product (rowwise version):

```
import numpy
import sympy
a = np.array(sympy.symbols("a1:5(1:6)"), "object").reshape((4, 5))
print(a)
[[a11 a12 a13 a14 a15]
 [a21 a22 a23 a24 a25]
 [a31 a32 a33 a34 a35]
 [a41 a42 a43 a44 a45]]
b = np.array(sympy.symbols("b1:5(1:4)"), "object").reshape((4, 3))
print(b)
[[b11 b12 b13]
 [b21 b22 b23]
 [b31 b32 b33]
 [b41 b42 b43]]
c = np.vstack([np.kron(a[r], b[r]) for r in range(a.shape[0])])
print(c)
[[a11*b11 a11*b12 a11*b13 a12*b11 a12*b12 a12*b13 a13*b11 a13*b12 a13*b13
  a14*b11 a14*b12 a14*b13 a15*b11 a15*b12 a15*b13]
 [a21*b21 a21*b22 a21*b23 a22*b21 a22*b22 a22*b23 a23*b21 a23*b22 a23*b23
  a24*b21 a24*b22 a24*b23 a25*b21 a25*b22 a25*b23]
 [a31*b31 a31*b32 a31*b33 a32*b31 a32*b32 a32*b33 a33*b31 a33*b32 a33*b33
  a34*b31 a34*b32 a34*b33 a35*b31 a35*b32 a35*b33]
 [a41*b41 a41*b42 a41*b43 a42*b41 a42*b42 a42*b43 a43*b41 a43*b42 a43*b43
  a44*b41 a44*b42 a44*b43 a45*b41 a45*b42 a45*b43]]
```

Or:
```
c = a[..., np.newaxis, :] * b[..., np.newaxis]
c = c.reshape((c.shape[0], c.shape[1] * c.shape[2]))
print(c)
[[a11*b11 a12*b11 a13*b11 a14*b11 a15*b11 a11*b12 a12*b12 a13*b12 a14*b12
  a15*b12 a11*b13 a12*b13 a13*b13 a14*b13 a15*b13]
 [a21*b21 a22*b21 a23*b21 a24*b21 a25*b21 a21*b22 a22*b22 a23*b22 a24*b22
  a25*b22 a21*b23 a22*b23 a23*b23 a24*b23 a25*b23]
 [a31*b31 a32*b31 a33*b31 a34*b31 a35*b31 a31*b32 a32*b32 a33*b32 a34*b32
  a35*b32 a31*b33 a32*b33 a33*b33 a34*b33 a35*b33]
 [a41*b41 a42*b41 a43*b41 a44*b41 a45*b41 a41*b42 a42*b42 a43*b42 a44*b42
  a45*b42 a41*b43 a42*b43 a43*b43 a44*b43 a45*b43]]
```
