### ISSUE TITLE
BUG: f2py does not print names of COMMON data block items

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#15308]
This can be seen if one executes [this example](https://numpy.org/devdocs/f2py/python-usage.html#common-blocks) from the docs: running

```bash
f2py -c -m common common.f
```
and then importing in python gives the following output:

```python
>>> import common
>>> print(common.data.__doc__)
'i'-scalar
'i'-array(4)
'f'-array(2,3)
```

The expected output is 
```python
>>> print(common.data.__doc__)
i - 'i'-scalar
x - 'i'-array(4)
a - 'f'-array(2,3)
```

This has been introduced sometime in the past as the correct output is listed in the current version of the docs. 

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.19.0.dev0+b7d0258 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
Relevant fortran lines:
https://github.com/numpy/numpy/blob/624d34cbda2f8f7614733743f028c0dd6a5c9952/doc/source/f2py/common.f#L3-L5

**Comment by eric-wieser** [comment]
Worth noting that we have a test that expects the current behavior:

https://github.com/numpy/numpy/blob/624d34cbda2f8f7614733743f028c0dd6a5c9952/numpy/f2py/tests/test_block_docstring.py#L7-L23

**Comment by eric-wieser** [comment]
I think this diff is to blame: https://github.com/bobeldering/numpy/commit/b356ef022e2b6bb3ae6290281e25454475a2a16a#diff-2f941876fe4226986f07907b449a11b0L135

**Comment by melissawm** [comment]
#17373 actually fixed this as well.
