### ISSUE TITLE
Python 2 code clean up tracker

### ISSUE THREAD

**Issue by sethtroisi** [numpy/numpy#15306]
This is a tracker bug for my work on Python2 code cleanup.

I'm creating it to both track my PRs and to allow me to add `TODO[gh-####]` for future work I want to do but have broken out.

**Comment by sethtroisi** [comment]
Work so far
C code
#15232 #15231 
#15304
#15233 

Removing python2 only APIs
#15239 #15263 #15268 #15272

**Comment by Zac-HD** [comment]
@sethtroisi - have you seen `pyupgrade`?  I've loved it for a while, but it was invaluable when removing Py2 compat from the Hypothesis codebase :smile:

**Comment by sethtroisi** [comment]
@Zac-HD I have not, I took a look at their README and I'm not sure if it's going to work the way that numpy has done their PY2->PY3 changes but I'll defiantly give it a try.

**Comment by eric-wieser** [comment]
Some postoned work: https://github.com/numpy/numpy/pull/15307/files#r365453208

**Comment by sethtroisi** [comment]
https://github.com/numpy/numpy/blob/master/numpy/lib/npyio.py#L421

**Comment by mattip** [comment]
xref gh-15352, although not directly connected to this cleanup

**Comment by sethtroisi** [comment]
I thought I had left some `str("...")` in one of my PR which was to be replaced with `"..."`
`grep -ri '\bstr(".*")'` shows only one intentional result, so this is good right now. I also checked for `str(b"...")`

**Comment by sethtroisi** [comment]
#15377

**Comment by sethtroisi** [comment]
I promised to try and upstream some of the changes I've made to [tools/refguide_check.py](https://github.com/numpy/numpy/blob/master/tools/refguide_check.py) to scipy.
especially those in https://github.com/numpy/numpy/pull/15449, https://github.com/numpy/numpy/pull/15417, and https://github.com/numpy/numpy/pull/15430

**Comment by mattip** [comment]
I think this is finished, so closing. Please reopen or open a new issue if there is still more 2.7 cleanup to be done.
