### ISSUE TITLE
np.dtype hangs on self-referential dtypes

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15301]
Malicious, but:
```python
>>> l = []
>>> l.append(('a', l))
>>> np.dtype(l)
# hangs, probably also stackoverflow
```
Should raise a RecursionError.

**Comment by PhanatosZou** [comment]
May I work on this issue? I'm new here.

**Comment by eric-wieser** [comment]
Sure, but it's not a particularly easy one, and will be almost entirely C code.

The rough gist is that on the codepath that stackoverflows, we need a call to `Py_EnterRecursiveCall` something like what we already do here:

https://github.com/numpy/numpy/blob/0aa8370c68f037659327bb97aad1ee5548b0f6ca/numpy/core/src/multiarray/descriptor.c#L125-L135

In principle, any function in that file that starts with `_convert` and calls `_convert_from_any` or one of it's callers needs this type of clause.

**Comment by PhanatosZou** [comment]
> Sure, but it's not a particularly easy one, and will be almost entirely C code.
> 
> The rough gist is that on the codepath that stackoverflows, we need a call to `Py_EnterRecursiveCall` something like what we already do here:
> 
> https://github.com/numpy/numpy/blob/0aa8370c68f037659327bb97aad1ee5548b0f6ca/numpy/core/src/multiarray/descriptor.c#L125-L135
> 
> In principle, any function in that file that starts with `_convert` and calls `_convert_from_any` or one of it's callers needs this type of clause.

Got it. Thanks! I'll work on it.

**Comment by eric-wieser** [comment]
I recommend you wait for #15310 before making a start, since once that goes in all you have to do is find calls to `_convert_from_any`

**Comment by PhanatosZou** [comment]
Sure. Thanks for the advice!

**Comment by eric-wieser** [comment]
@PhanatosZou, that PR is merged - please feel free to try to fix this!
