### ISSUE TITLE
Replace calls to `_report_generic_error` with a more useful error message.

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15316]
Right now, many failures of `np.dtype(obj)` go to this path:

https://github.com/numpy/numpy/blob/80fc0f5ac661740b1267a726a37b5bc570903cb4/numpy/core/src/multiarray/descriptor.c#L42-L49

For example

https://github.com/numpy/numpy/blob/80fc0f5ac661740b1267a726a37b5bc570903cb4/numpy/core/src/multiarray/descriptor.c#L443-L446

We should replace some or all of these calls in this file with more helpful error messages, such as in the above case:
```diff
-_report_generic_error();
+PyErr_Format(PyExc_TypeError, "Field elements must be 2-tuples, got %R", item);
```

If we replace all of them, then we should remove the `_report_generic_error` function entirely

**Comment by faizan2700** [comment]
Hello I want to contribute to this issue but I am having one problem please help.
After forking repo I have cloned it on my laptop and now from numpy directory I am trying to import numpy but it is giving error that I can't import numpy from there and exit from there and then import it. if I am in some other directory and the numpy directory path to sys.path and then import numpy it gives the same error. but if I  have made some changes in source code and want to test the effect of it in interpreter or test numpy how do I do that when I can not import it?

My question is when you make changes in numpy how do you import the source of numpy and check that ?

**Comment by eric-wieser** [comment]
> how do you import the source of numpy and check that ?

I normally uses `py -3.8 runtests.py -i`, which opens an ipython shell with your in-development numpy

**Comment by hasansajedi** [comment]
When this error occured?
Can you leave here an input example?

**Comment by ericmariasis** [comment]
take

**Comment by ericmariasis** [comment]
I created a pull request for the  enhancement.
