### ISSUE TITLE
ImportError when import numpy on iOS at 3.8

### ISSUE THREAD

**Issue by youmenglidang** [numpy/numpy#15314]
We use Apple-support-python to build python3.8 environment on iOS , and we can run simple python script successfully on it but got something wrong with complex script, such as script which import numpy.

xx.py could run on my mac(python3.8 the same as iOS), but after building python 3.8 environment on iOS, copying numpy module into some of python's path, xx.py got wrong. Please see details blow.

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/init.py", line 17, in 
from . import multiarray
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/multiarray.py", line 14, in 
from . import overrides
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in 
from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "snore_screening.py", line 28, in 
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/init.py", line 142, in 
from . import core
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/init.py", line 47, in 
raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.

Try uninstalling and reinstalling numpy.

If you have already done that, then:

Check that you expected to use Python3.8 from "/Users/Squirrel./Library/Developer/CoreSimulator/Devices/CC0C34D5-8BEA-4A16-A540-7706ED049ED4/data/Containers/Bundle/Application/C72BC45B-7B67-4950-89F5-9DADDE41452C/SnoreMonitor.app/SnoreMonitor",
and that you have no directories in your PATH or PYTHONPATH that can
interfere with the Python and numpy version "1.17.4" you're trying to use.
If (1) looks fine, you can open a new issue at
https://github.com/numpy/numpy/issues. Please include details on:
how you installed Python
how you installed numpy
your operating system
whether or not you have multiple versions of Python installed
if you built from source, your compiler versions and ideally a build log
If you're working with a numpy git repository, try git clean -xdf
(removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by mattip** [comment]
In general, you cannot simply copy c-extension modules: they need to be compiled for the target platform. The name of a shared-object containing a c-extension module will reflect this. How do the names of c-extension modules ('_ssl' for instance) compare to the name of the numpy.core._multiarra_umat shared oblect?

**Comment by youmenglidang** [comment]
> In general, you cannot simply copy c-extension modules: they need to be compiled for the target platform. The name of a shared-object containing a c-extension module will reflect this. How do the names of c-extension modules ('_ssl' for instance) compare to the name of the numpy.core._multiarra_umat shared oblect?

thanks for reply.So Do you mean that what I shall do is to compile the library of numpy for iOS platfrom?if you mean that then please show me the concrete steps.

**Comment by mattip** [comment]
You should be able to `pip install` numpy for this platform now. Closing, please reopen if that fails.

**Comment by LengQH** [comment]
I am the same as you. Have you solved this problem? How to import numpy in IOS ？

**Comment by stoneCoder** [comment]
How do you compile _multiarray_umath.cpython-38-darwin.so for arm64 in iOS env.I build for this tips invalid conversion between vector type '__m64'
