### ISSUE TITLE
Squeeze array with one element returns an array with no shape

### ISSUE THREAD

**Issue by elikbelik** [numpy/numpy#15313]
When squeezing an array that has only one element we get a non-dimensional array (instead of an array with one dimension).

### Reproducing code example:

```python
import numpy as np
arr = np.array([[1238]]).squeeze()
arr.shape
arr[0]
```

### Error message:
IndexError: too many indices for array

### Numpy/Python version information:
1.16.4 3.6.8 |Anaconda custom (64-bit)| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
This is by design, the shape is `()`, ie a 0d array (wrapped scalar).

**Comment by eric-wieser** [comment]
Actually, let's reopen this as a documentation task to add an example of this behavior to the docstring
