### ISSUE TITLE
ENH: Improve error message: `IndexError: too many indices for array`

### ISSUE THREAD

**Issue by AbhisekRao** [numpy/numpy#15321]
**IndexError: too many indices for array**

### error example:

File "object_detection/mobilenet_test.py", line 153, in <module>
    line_thickness=8)
  File "/home/abhisek/Desktop/models/research/object_detection/utils/visualization_utils.py", line 798, in visualize_boxes_and_labels_on_image_array
    if scores is None or scores[i] > min_score_thresh:
IndexError: too many indices for array

> Unable to start the inference due to the error " IndexError: too many indices for array "

**Comment by seberg** [comment]
Maybe the error should be improved to include: "...; array has N-dimension, but X were indexed" (where X is larger than N).

**Comment by MrGrayCode** [comment]
@seberg Can I take up this issue as my first contribution to numpy?

**Comment by eric-wieser** [comment]
Please do! You'll want to start by searching the c code for the error message.

**Comment by AbhisekRao** [comment]
even after the changes the video is streaming but unable to detect objects as it suppose to.

**Comment by mattip** [comment]
@AbhisekRao you will need to provide more information: what exactly are you trying to do, and why do you think the problem stems from NumPy?

**Comment by LaisaLI** [comment]
I'd like to take up this one as my first contribution to NumPy.
I checked the source code. There are 6 places using `too many indices for array` as the error message in `numpy/numpy/core/src/multiarray/mapping.c`. In my view, we can give different messages for different situations. I'm not sure if it's suitable. As I didn't contribute to NumPy before, I'd like to ask for somebody's advice.

**Comment by AtsushiSakai** [comment]
@mattip Hi. I think this issue should be closed by #15832
