### ISSUE TITLE
DOC/DEP: Document and/or deprecate `uint0` and `int0`

### ISSUE THREAD

**Issue by Rubix982** [numpy/numpy#15334]
Hi.

The page at https://numpy.org/devdocs/user/basics.types.html does not include a valid data type in numpy, that is, int0.
Request to edit the datatype into the doc.

<------ reproducing code example ------>

```python
>>> import numpy as np
>>> np.int0 is np.int64
True
>>> np.__version__
'1.81.1'
>>> exit()
```

# After exiting

[user@linux~]$ python --version
Python 3.8.1

The code example is provided thanks to user 'Right leg' from here, 
 https://stackoverflow.com/questions/48350693/what-is-numpy-method-int0 .

Thank you.

----

**EDIT by seberg: In gh-11025 Robert notes that "In Numeric, Int0 is indeed equivalent to Int8"** if this is documented, we have to make sure to be correct as to whether this is an alias to `intp` or to `int8`.

**Comment by eric-wieser** [comment]
Related: #11025

**Comment by seberg** [comment]
Well, I will not oppose to adding it to the documentation, but only if it reads: deprecated clearly. We should deprecate them in code as well, but that is only reasonable in 3.7+, so for now I am not quite sure (but I would definitely merge a PR proposing it :)).

**Comment by Rubix982** [comment]
I would be happy to make the PR.
Where can I find it in this repository? 
Sorry, I'm completely new to this kind of stuff - merging and PRs.

**Comment by eric-wieser** [comment]
> We should deprecate them in code as well, but that is only reasonable in 3.7+

We should probably focus on writing the NEP for #14901 before we try and deprecate anything else like it.

**Comment by Rubix982** [comment]
@eric-wieser alright, I'll keep this issue open till then.

**Comment by seberg** [comment]
Those odd alias (`int0`, etc.) are finally all gone.
