### ISSUE TITLE
Unexpected type passed to vectorized function when called with array of datetime64

### ISSUE THREAD

**Issue by metoffice-jmfrancis** [numpy/numpy#15337]
Given I:
* create an array of `datetime64`
* define a function `f` and `vectorize` it

When I pass the array to the vectorized function

Then the first object passed to `f` is a `datetime64` but all subsequent objects are `datetime.datetime`.

### Reproducing code example:

```
from numpy import arange, datetime64, timedelta64, vectorize, version

hours = arange(
    datetime64("2020-01-01T00"),
    datetime64("2020-01-01T04"),
    timedelta64(1, "h")
)

def what_type_is(x):
    print(type(x))
    return x

for x in hours:
    what_type_is(x)

print()

vectorize(what_type_is)(hours)
```

Example output:
```
<class 'numpy.datetime64'>
<class 'numpy.datetime64'>
<class 'numpy.datetime64'>
<class 'numpy.datetime64'>

<class 'numpy.datetime64'>
<class 'datetime.datetime'>
<class 'datetime.datetime'>
<class 'datetime.datetime'>
<class 'datetime.datetime'>
```

### Numpy/Python version information:

```
>>> platform.platform()
'Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-redhat-7.7-Maipo'
>>> sys.version
'3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) \n[GCC 7.3.0]'
>>> numpy.__version__
'1.18.1'
```

**Comment by miccoli** [comment]
I think this is desired behaviour. In fact

```
>>> vectorize(what_type_is)(arange(2, dtype=numpy.float32))
<class 'numpy.float32'>
<class 'float'>
<class 'float'>
array([0., 1.], dtype=float32)
>>> vectorize(what_type_is)(arange(2, dtype=numpy.float64))
<class 'numpy.float64'>
<class 'float'>
<class 'float'>
array([0., 1.])
>>> vectorize(what_type_is)(arange(2, dtype=numpy.float128))
<class 'numpy.float128'>
<class 'numpy.float128'>
<class 'numpy.float128'>
array([0., 1.], dtype=float128)
```

I've not checked the source, but my assumption is that the `pyfunc` in the `vectorize` call is assumed to be a *Python* function, so the arguments to `pyfunc` are casted to a compatible scalar native python type, if possible.

In fact in my first two examples we have calls with python native `float`, while in the last example the argument is left as an extended precision numpy float, which is not present as a native python type.

**Comment by miccoli** [comment]
Indeed see these lines where the conversion takes place: <https://github.com/numpy/numpy/blob/bf6859c4248d3595493d2d809bafe1bc200ad6fa/numpy/lib/function_base.py#L2152-L2154>

In fact:
```
>>> numpy.array(hours, copy=False, subok=True, dtype=object)
array([datetime.datetime(2020, 1, 1, 0, 0),
       datetime.datetime(2020, 1, 1, 1, 0),
       datetime.datetime(2020, 1, 1, 2, 0),
       datetime.datetime(2020, 1, 1, 3, 0)], dtype=object)
```

**Comment by metoffice-jmfrancis** [comment]
OK, that's good. Thank you for checking.

(I see I should be able to use the `otypes` argument to get what I wanted.)
