### ISSUE TITLE
Numpy Importing the multiarray numpy extension module failed error

### ISSUE THREAD

**Issue by wonaya** [numpy/numpy#15339]
Hi, I am trying to install a package that has a several dependencies by writing a dockerfile.
It's using python 2.7.15, and I was trying to install numpy 1.16.5

### Reproducing code example:

RUN wget https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz
RUN tar -xzf Python-2.7.15.tgz ; cd Python-2.7.15 ; ./configure ; make ; sudo make install
RUN sudo apt-get install -y python-dev python-tk python-pip
ENV PYTHONPATH "$PYTHONPATH:/usr/local/lib/python2.7/dist-packages:/usr/lib:/usr/lib/python2.7/site-packages"

RUN pip install opencv-python --force-reinstall --ignore-installed
RUN pip install --force-reinstall numpy==1.16.5

CMD python /data/test.py (which just has import numpy in its code)
I

```python
import numpy as np
<< your code here >>
```

### Error message:

Traceback (most recent call last):
  File "/data/test.py", line 1, in <module>
    import numpy
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

**Comment by rossbar** [comment]
I'm going to close this one since it never started up any discussion. If the issue persists, please feel free to reopen with current info about the system and installation procedure.
