### ISSUE TITLE
tobytes() returns different values for an array with a dict inside

### ISSUE THREAD

**Issue by jrhone** [numpy/numpy#15340]
Two numpy arrays holding separate dicts of the same data will return different values for `tobytes()`

If this isn't a bug, why does this behavior happen?

### Reproducing code example:

```python
import numpy as np

np1 = np.array([{'c': 20, 'd': 30}])
np2 = np.array([{'c': 20, 'd': 30}])

print(np1.tobytes())  
# b'P\xef\x8bI\x01\x00\x00\x00'

print(np2.tobytes())  
# b'\xa0\xe0\x8eI\x01\x00\x00\x00'
```

### Numpy/Python version information:

>>> numpy.__version__
'1.18.1'

>>> sys.version
'3.7.4 (default, Aug 13 2019, 15:17:50) \n[Clang 4.0.1 (tags/RELEASE_401/final)]'

### OS info:

macOS Catalina v10.15.1

**Comment by WarrenWeckesser** [comment]
The arrays that you created are object arrays.  Note the value of `dtype`:

```
In [38]: np1 = np.array([{'c': 20, 'd': 30}])

In [39]: np1                                                                                                                      
Out[39]: array([{'c': 20, 'd': 30}], dtype=object)
```
The means the values actually stored in the numpy array are memory pointers.  Just the pointers are processed by `tobytes()`, not the objects that they point to.

For example: `id` returns the address of an object.  This snippet shows that the `tobytes()` method has returned the bytes of the address of dictionary stored in `np1`:

```
In [48]: id(np1[0])    # Address of the dictionary stored in np1.
Out[48]: 4511260992

In [49]: sum(v*256**p for (p, v) in enumerate(np1.tobytes()))   # Convert the result of `tobytes` to a number.                                                                    
Out[49]: 4511260992
```
