### ISSUE TITLE
raise TypeError( TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

### ISSUE THREAD

**Issue by DarkKnight6777** [numpy/numpy#15345]
I am using the latest version of numpy and facing this issue. I have already seen the answer from https://github.com/rbgirshick/py-faster-rcnn/issues/481#issuecomment-278730631 but cannot find the mentioned files in my windows pc.

Also seen solution by downgrading it to 1.11.0 but I need to use the latest version for my work.
The code is from cosmoTransitions package

`
              
   import numpy as np
             
   from cosmoTransitions import generic_potential

   v2 = 246.**2

   class model1(generic_potential.generic_potential):
    """
    A sample model which makes use of the *generic_potential* class.

    This model doesn't have any physical significance. Instead, it is chosen
    to highlight some of the features of the *generic_potential* class.
    It consists of two scalar fields labeled *phi1* and *phi2*, plus a mixing
    term and an extra boson whose mass depends on both fields.
    It has low-temperature, mid-temperature, and high-temperature phases, all
    of which are found from the *getPhases()* function.
    """
    def init(self,m1=120.,m2=50.,mu=25.,Y1=.1,Y2=.15,n=30):
        """
          m1 - tree-level mass of first singlet when mu = 0.
          m2 - tree-level mass of second singlet when mu = 0.
          mu - mass coefficient for the mixing term.
          Y1 - Coupling of the extra boson to the two scalars individually
          Y2 - Coupling to the two scalars together: m^2 = Y2*s1*s2
          n - degrees of freedom of the boson that is coupling.
        """
        # The init method is called by the generic_potential class, after it
        # already does some of its own initialization in the default __init__()
        # method. This is necessary for all subclasses to implement.

        # This first line is absolutely essential in all subclasses.
        # It specifies the number of field-dimensions in the theory.
        self.Ndim = 2

        # self.renormScaleSq is the renormalization scale used in the
        # Coleman-Weinberg potential.
        self.renormScaleSq = v2

        # This next block sets all of the parameters that go into the potential
        # and the masses. This will obviously need to be changed for different
        # models.
        self.l1 = .5*m1**2/v2
        self.l2 = .5*m2**2/v2
        self.mu2 = mu**2
        self.Y1, self.Y2 = Y1, Y2
        self.n = n

    def forbidPhaseCrit(self, X):
        """
        forbidPhaseCrit is useful to set if there is, for example, a Z2 symmetry
        in the theory and you don't want to double-count all of the phases. In
        this case, we're throwing away all phases whose zeroth (since python
        starts arrays at 0) field component of the vev goes below -5. Note that
        we don't want to set this to just going below zero, since we are
        interested in phases with vevs exactly at 0, and floating point numbers
        will never be accurate enough to ensure that these aren't slightly
        negative.
        """
        return (np.array([X])[...,0] < -5.0).any()

    def V0(self, X):
        """
        This method defines the tree-level potential. It should generally be
        subclassed. (You could also subclass Vtot() directly, and put in all of
        quantum corrections yourself).
        """
        # X is the input field array. It is helpful to ensure that it is a
        # numpy array before splitting it into its components.
        X = np.asanyarray(X)
        # x and y are the two fields that make up the input. The array should
        # always be defined such that the very last axis contains the different
        # fields, hence the ellipses.
        # (For example, X can be an array of N two dimensional points and have
        # shape (N,2), but it should NOT be a series of two arrays of length N
        # and have shape (2,N).)
        phi1,phi2 = X[...,0], X[...,1]
        r = .25*self.l1*(phi1*phi1-v2)**2 + .25*self.l2*(phi2*phi2-v2)**2
        r -= self.mu2*phi1*phi2
        return r

    def boson_massSq(self, X, T):
        X = np.array(X)
        phi1,phi2 = X[...,0], X[...,1]

        # We need to define the field-dependnet boson masses. This is obviously
        # model-dependent.
        # Note that these can also include temperature-dependent corrections.
        a = self.l1*(3*phi1*phi1 - v2)
        b = self.l2*(3*phi2*phi2 - v2)
        A = .5*(a+b)
        B = np.sqrt(.25*(a-b)**2 + self.mu2**2)
        mb = self.Y1*(phi1*phi1+phi2*phi2) + self.Y2*phi1*phi2
        M = np.array([A+B, A-B, mb])

        # At this point, we have an array of boson masses, but each entry might
        # be an array itself. This happens if the input X is an array of points.
        # The generic_potential class requires that the output of this function
        # have the different masses lie along the last axis, just like the
        # different fields lie along the last axis of X, so we need to reorder
        # the axes. The next line does this, and should probably be included in
        # all subclasses.
        M = np.rollaxis(M, 0, len(M.shape))

        # The number of degrees of freedom for the masses. This should be a
        # one-dimensional array with the same number of entries as there are
        # masses.
        dof = np.array([1, 1, self.n])

        # c is a constant for each particle used in the Coleman-Weinberg
        # potential using MS-bar renormalization. It equals 1.5 for all scalars
        # and the longitudinal polarizations of the gauge bosons, and 0.5 for
        # transverse gauge bosons.
        c = np.array([1.5, 1.5, 1.5])

        return M, dof, c

    def approxZeroTMin(self):
        # There are generically two minima at zero temperature in this model,
        # and we want to include both of them.
        v = v2**.5
        return [np.array([v,v]), np.array([v,-v])]

and this is producing the following error
`

### Error message:

```    
     Traceback (most recent call last):
     File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
       num = operator.index(num)
    TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\Lib\test\testModel1.py", line 168, in <module>
    from test import testModel1
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\test\testModel1.py", line 170, in <module>
    m.findAllTransitions()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cosmoTransitions\generic_potential.py", line 622, in findAllTransitions
    self.TnTrans = transitionFinder.findAllTransitions(
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cosmoTransitions\transitionFinder.py", line 926, in findAllTransitions
    trans = tunnelFromPhase(phases, start_phase, V, dV, Tmax,
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cosmoTransitions\transitionFinder.py", line 836, in tunnelFromPhase
    Tnuc = optimize.brentq(_tunnelFromPhaseAtT, Tmin, Tmax, args=args,
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\scipy\optimize\zeros.py", line 780, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cosmoTransitions\transitionFinder.py", line 707, in _tunnelFromPhaseAtT
    tobj = pathDeformation.fullTunneling(
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cosmoTransitions\pathDeformation.py", line 951, in fullTunneling
    path = SplinePath(pts, V, dV, V_spline_samples=V_spline_samples,
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cosmoTransitions\pathDeformation.py", line 764, in __init__
    x = np.linspace(xmin, 0, nx)[:, np.newaxis]
  File "<__array_function__ internals>", line 5, in linspace
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\core\function_base.py", line 119, in linspace
    raise TypeError(
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.`
```

**Comment by eric-wieser** [comment]
You need to show the full stack trace, including the place where you actually call `linspace`

**Comment by eric-wieser** [comment]
Your problem is in this line:
```
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cosmoTransitions\pathDeformation.py", line 764, in __init__
    x = np.linspace(xmin, 0, nx)[:, np.newaxis]
```
`nx` is a float, but needs to be an integer. I don't know where `nx` comes from there, but it's a proble either with `cosmoTransitions` or `testModel1`, not with numpy.

**Comment by eric-wieser** [comment]
The bug is here:

https://github.com/clwainwright/CosmoTransitions/blob/master/cosmoTransitions/pathDeformation.py#L761-L762

 Arguably, the underlying issue is that `np.ceil` returns a float not an int - but there's already an issue open about that. As a workaround they need to cast to `int`.
