### ISSUE TITLE
"module not found error" in VS Code using Conda

### ISSUE THREAD

**Issue by tzmanish** [numpy/numpy#15343]
I installed miniconda in 'MS Visual Studio 2019' and created an 'Conda Environment (Python 3.7, 64-bit)' in which numpy is installed and works fine in MS Visual Studio but when I activate same environment in 'VS Code',  I get module not found error.

### Reproducing code example:

```python
import numpy as np
```

### Error message:

PS D:\Google Drive\code\Machine Learning A-Z> cd 'd:\Google Drive\code\Machine Learning A-Z'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Users\tzman\.conda\envs\MLEnv\python.exe' 'c:\Users\tzman\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '60451' 'd:\Google Drive\code\Machine Learning A-Z\HelloWorld.py' 
C:\Users\tzman\.conda\envs\MLEnv\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\tzman\.conda\envs\MLEnv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\tzman\.conda\envs\MLEnv\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\tzman\.conda\envs\MLEnv\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\tzman\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\tzman\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\tzman\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\tzman\.conda\envs\MLEnv\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\tzman\.conda\envs\MLEnv\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\tzman\.conda\envs\MLEnv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Google Drive\code\Machine Learning A-Z\HelloWorld.py", line 1, in <module>
    import numpy as np
  File "C:\Users\tzman\.conda\envs\MLEnv\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\tzman\.conda\envs\MLEnv\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\tzman\.conda\envs\MLEnv\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

### Numpy/Python version information:

Python 3.7, 64-bit    
numpy 1.18.1

### How I installed Python

I installed miniconda in 'MS Visual Studio 2019' and created an 'Conda Environment'

### your operating system

Windows 10 Home

### Whether or not you have multiple versions of Python installed

No

**Comment by mattip** [comment]
You may have more luck getting a response in a VS Code or Conda forum/issue tracker

**Comment by gsdaemon** [comment]
@tzmanish have you found a solution?

**Comment by l3d00m** [comment]
I have the same error too using anaconda and Visual Studio code with numpy=1.18.1

Activating the conda env and executing `import numpy` in the corresponding python shell works, but as soon as I use VScode for this it gives me the same import error (I made sure that both use the same python env by printing the python version via sys.version at the beginning)

It works as soon as I force numpy=1.17.5 wihthin the env, so I assume this is a bug in the VSC integration or something like that?

So for anyone with the same issue do `conda install numpy=1.17.5` as a workaround.

**Comment by l3d00m** [comment]
@tzmanish @gsdaemon I edited my comment, does it work for you if you start it VSCode like that?

**Comment by seberg** [comment]
Closing in favor of gh-15183 which seems to include possible a bit more info.

**Comment by rishi-221b-bakerstreet** [comment]
Anyone has solved the issue why Visual Studio Code is not considering the libraries from Anaconda Python?

**Comment by l3d00m** [comment]
How about you read the previous comments? I explained how I fixed it for me.

**Comment by jafjdev** [comment]
Hello!  Im getting similar error with PyCharm, im using conda environment and im unable to run 


_UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package,_


i installed mkl-service using conda and still having same issue.

**Comment by l3d00m** [comment]
Have you tried what I described in my comment or any of the stuff from the unlinked comments?

**Comment by xinstein** [comment]
> I have the same error too using anaconda and Visual Studio code with numpy=1.18.1
> 
> Activating the conda env and executing `import numpy` in the corresponding python shell works, but as soon as I use VScode for this it gives me the same import error (I made sure that both use the same python env by printing the python version via sys.version at the beginning)
> 
> It works as soon as I force numpy=1.17.5 wihthin the env, so I assume this is a bug in the VSC integration or something like that?
> 
> ~So for anyone with the same issue do `conda install numpy=1.17.5` as a workaround.~
> 
> **EDIT:** This wasn't numpy specific, I had this occur with `shapely` and the old version of numpy too suddenly, which made me find this: https://stackoverflow.com/a/58125351 It seems that the standalone support in VSCode for anaconda isn't that great, so it's preferred to activate the environment and then run VScode by typing in `code`.

THAT SOLVED IT!!!

**Comment by sagnik1511** [comment]
This issue happens when you run VS code standalone and not in the anaconda prompt. The more complicated solution is to add anaconda path to your system path and make VSCode understand the conda virtual environment. But the simpler solution is to open anaconda prompt and then type:

    `(base) C:\Users\{your_user}>conda activate {your_env}
    ({your_env}) C:\Users\{your_user}>code`
to open VSCode through anaconda. Hope it works.


copied from StackOverflow. This worked for me.

**Comment by vladnega** [comment]
I was running into the same problem, and I fixed it by selecting the correct *python interpreter* in vscode. Each conda environment points to a different python interpreter (different file path), so it was just a matter of choosing the right one.

From VS Code's Command Palette choose `Python: Select Interpreter` and the select the interpreter specific to your conda environment.
