### ISSUE TITLE
np.linalg.solve documentation suggests ambigous behaviour

### ISSUE THREAD

**Issue by DerWeh** [numpy/numpy#15349]
The docstring shows of `numpy.linalg.solve`:
```
a : (…, M, M) array_like
b : {(…, M,), (…, M, K)}, array_like
```
which leads to ambiguous conclusions. Let's stick to first choice. This would mean for `a.shape =  (M, M)`, `b.shape = (N, M)` I should expect a result of `x.shape = (N, M)`. 

Of course, it cannot really work, as there is always an uncertainty, if `b` should be interpreted as `(..., M)` or `(..., M, K)` (after all, what should we do if `M==K`?). Nevertheless, the documentation should be more explicit, as new users will be easily confused.

I personally would remove the ambiguity completely. One idea would simply be adding an argument e.g. `b_is_matrix: bool` to specify which signature `(..., M)` or `(..., M, K)` should apply.
The other idea would be, to remove `(..., M, K)` completely, as it can be obtained trivially by passing `b.T` (or `np.swapaxes(b, -1, -2)`) and using broadcasting.

### Reproducing code example:

```python
import numpy as np

a = np.ones((1, 1))
b = b = np.ones((2, 1))
np.linalg.solve(a, b)
```

### Error message:

```python
ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 2 is different from 1)
```
### Numpy/Python version information:

1.18.1 3.6.1 (default, Nov 11 2017, 14:50:47)
[GCC 4.9.2]

**Comment by ZisIsNotZis** [comment]
The `...` in `a` and `b` should be the same thing actually. Therefore,

> a.shape = (M, M), b.shape = (N, M)

is illegal. `a` already indicates that `...=empty`, therefore `b` have to start with `M` and might have an extra axis after this.

**Comment by eric-wieser** [comment]
A hint from the comments:
https://github.com/numpy/numpy/blob/d9b1e32cb8ef90d6b4a47853241db2a28146a57d/numpy/linalg/linalg.py#L394-400

**Comment by eric-wieser** [comment]
Originates from https://github.com/numpy/numpy/commit/04ad33ed7b6b6a0eee2a0a6e98fc8d598db487ad#diff-6858bbac5c5c59bdddf245c69d6a547cR359, cc @pv.

**Comment by seberg** [comment]
Hmmm, that exact match may be a bit tricky. Another logic we have is to do it like matmul, and make it: `{(M,), (..., M, K)}, array_like`. I think that would be a subset of the current behaviour, so it could work. To be friendly to current users, we _could_ add a keyword in principle I guess.

**Comment by DerWeh** [comment]
Concerning documentation:

> 
> 
> The `...` in `a` and `b` should be the same thing actually. Therefore,
> 
> > a.shape = (M, M), b.shape = (N, M)
> 
> is illegal. `a` already indicates that `...=empty`, therefore `b` have to start with `M` and might have an extra axis after this.

Yes I get, that this is the current behavior. But I don't think that this is obvious for new users. I looked a bit around in the documentation, and there is hardly any usage of the Ellipsis.

However, it often used when indexing arrays as well as when using `np.einsum`.
My first naive line of thought when I read the docstring was, that it should behave like in `np.einsum`.
However, in `np.einsum` no exact match is needed.

As the Ellipsis has a different meaning in the documentation (be the same thing actually) as in code (any additional dimension, just should be broadcastable), further explanation is necessary.

But of course, it might be that I just think strangely and it's obvious to everyone else.


Concerning broadcasting:
@seberg this also sounds like a reasonable option. I don't have a strong opinion here, I just feel like the current version results for me often in ugly code, as I want to have the inputs broadcasted.

**Comment by DerWeh** [comment]
> 
> 
> A hint from the comments:
> 
> https://github.com/numpy/numpy/blob/d9b1e32cb8ef90d6b4a47853241db2a28146a57d/numpy/linalg/linalg.py#L394-L399
> .
> 
> This seems like potentially dangerous behavior.

I didn't really have time to put much thought into it, but this see,s to me like it would be a good place to give the user control by a keyword argument, something like `b_is_matrix` or `b_is_vector` defaulting to `None` which would be the current behavior of guessing. If set explicitly by the user we just do
```python
 if  b_is_vector: 
     gufunc = _umath_linalg.solve1 
 else: 
     gufunc = _umath_linalg.solve
```
skipping the checks, whether it can be determined automatically.

**Comment by seberg** [comment]
@DerWeh do you want to make a PR with this, I think it would be good to explore at least. The correct route here will be to give a DeprecationWarning, we should not change this over night. Make it `VisibleDeprecationWarning` if you think new users are probably writing a bug (but I doubt that is true here).

**Comment by WarrenWeckesser** [comment]
Another ship that has already sailed, but for future reference and for those unfamiliar with gufunc behavior: if we could use the gufunc `solve1` (from `numpy.linalg._umath_linalg`) with signature `(m,m),(m)->(m)` as the public `solve` function, it would handle broadcasting of stacked matrices and stacked `b` vectors automatically.  The only quirk would be that, by default, the "stacked" `b` vectors would have to be given with shape `(K, M)`.  That is, the default behavior would require the `b` vectors be in the rows of the input array.   If a user's input is more naturally generated with shape `(M, K)`, they could just transpose the input, or use the `axes` parameter of the gufunc.   This would amount to @DerWeh's suggestion to "remove (..., M, K) completely, as it can be obtained trivially by passing b.T (or np.swapaxes(b, -1, -2)) and using broadcasting", and would expose the other features of the gufunc API as a bonus.
