### ISSUE TITLE
_shell_utils.py does not return expected result

### ISSUE THREAD

**Issue by pajarrige** [numpy/numpy#15356]
Under Windows 7, _shell_utils.NativeParser.split (WindowsParser.split) splits executable names containing blanks.

For my Intel Fortran compiler, it should return: ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2018\\windows\\bin\\intel64\\ifort.exe']

Currently, it returns: ['C:\\Program', 'Files', '(x86)\\IntelSWTools\\compilers_and_libraries_2018\\windows\\bin\\intel64\\ifort.exe']

This results in:
```
- info message: "Could not locate executable C:\Program", 
 - incorrect compiler run commands:
compiling Fortran 90 module sources
Fortran f77 compiler: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe /nologo /MD /nbs /names:lowercase /assume:underscore /O1 /arch:IA32 /QaxSSE3
Fortran f90 compiler: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe /nologo /MD /nbs /names:lowercase /assume:underscore /O1 /arch:IA32 /QaxSSE3
Fortran fix compiler: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe /nologo /MD /nbs /names:lowercase /assume:underscore /O1 /arch:IA32 /QaxSSE3
 - warning message after compile instructions (see below)
```
### Error message:
```
ifort.exe:f90: D:\PAJarrige\IstDvp\Gan_API\Python\gandll\pyGanSim.f90
ifort: command line warning #10161: unrecognized source type 'Files'; object file assumed
ifort: command line warning #10161: unrecognized source type '(x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe'; object file assumed
```
### Numpy/Python version information:
1.18.0

**Comment by eric-wieser** [comment]
This is by design - `split('C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe')` will split the spaces.

To not split spaces, you need to use quotes:
```
"C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe"
```
This is consistent with how it behaves on the command line.

**Comment by pajarrige** [comment]
I understand, but as it is used in the numpy.distutils machinery and the argument (exe filename) is not quoted, this produces incorrect results.
Similarly, paths to include folders in the compile line are no longer quoted with python 3.8.1 / numpy 1.18.1, while they were with python 3.7.5 / numpy 1.15.0:

python 3.8.1 / numpy 1.18.1:
compile options: '-Ibuild\src.win32-3.8\build\src.win32-3.8\ganessa -IC:\Program Files (x86)\Python38-32\lib\site-packages\numpy\core\include -IC:\Program Files (x86)\Python38-32\include -IC:\Program Files (x86)\Python38-32\include -c'

python 3.7.5 / numpy 1.15.0:
compile options: '-Ibuild\src.win32-3.7\build\src.win32-3.7\ganessa -I"C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\core\include" -I"C:\Program Files (x86)\Python37-32\include" -I"C:\Program Files (x86)\Python37-32\include" -c'

Generated compilation and link command lines exhibit a similar mishandling of blanks in paths to compiler libs.

De : Eric Wieser [mailto:notifications@github.com]
Envoyé : lundi 20 janvier 2020 18:28
À : numpy/numpy <numpy@noreply.github.com>
Cc : Jarrige, Pierre-Antoine <pierre-antoine.jarrige@suez.com>; Author <author@noreply.github.com>
Objet : Re: [numpy/numpy] _shell_utils.py does not return expected result (#15356)


This is by design - split('C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe') will split the spaces.

To not split spaces, you need to use quotes:

"C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\intel64\ifort.exe"

This is consistent with how it behaves on the command line.

**Comment by eric-wieser** [comment]
> I understand, but as it is used in the numpy.distutils machinery and the argument (exe filename) is not quoted

One of these two things is a bug:
* The fact that distutils is not applying suitable quotes
* The fact that distutils is going through this function at all.

It looks like you missed the edit to my comment above - can you answer the question there?

**Comment by pajarrige** [comment]
I'm using a distutil.cfg in the setup folder, with the following content:
[build] 
compiler=msvc
fcompiler=intelv

**Comment by pajarrige** [comment]
Before running the build, I set the environment variables using:
	call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018\windows\bin\compilervars.bat" ia32 vs2015

**Comment by eric-wieser** [comment]
> Similarly, paths to include folders in the compile line are no longer quoted

How exactly are you concluding this? It's possible we're just printing them to the log unquoted, and executing the original list. If it's from a log, can you attach the full log here?

**Comment by pajarrige** [comment]
[build38_2020.log](https://github.com/numpy/numpy/files/4104773/build38_2020.log)
[build37_2020.log](https://github.com/numpy/numpy/files/4104774/build37_2020.log)
Attached are the builds fwith python 3.8 (not OK: buids but .pyd not functional) and python 3.7 (build and run OK)

**Comment by eric-wieser** [comment]
I don't see any evidence of the `Could not locate executable C:\Program` issue in that log. Could you find me the log that contains that text?

Regarding include paths no longer having quotes - that's just a quirk of the log, the list of arguments is `" ".join`ed before printing (but not before execution).

**Comment by pajarrige** [comment]
Sorry I patched _shell_utils.py. Here is a log I got with the original file. I added a print comment to make sure.
[test.log](https://github.com/numpy/numpy/files/4104831/test.log)

**Comment by eric-wieser** [comment]
Where did you add the print? Can you add `import traceback; traceback.print_stack()` there too, so I can see what the call stack is leading up to the print?

**Comment by eric-wieser** [comment]
Perhaps a local change like:
```diff
--- C:\Users\wiese\Repos\numeric-python\numpy\numpy\distutils\exec_command.py	Wed Jan 22 10:11:26 2020
+++ C:\Users\wiese\Repos\numeric-python\numpy\numpy\distutils\exec_command.py	Thu Jan 23 18:36:51 2020
@@ -160,6 +160,7 @@
                 return f_ext
 
     log.warn('Could not locate executable %s' % orig_exe)
+    import traceback; traceback.print_stack()
     return None
 
 ############################################################
```

**Comment by eric-wieser** [comment]
No need, I think I understand the bug now - it would have been really helpful had you pointed to the line calling `split` that you felt was wrong in the first post.

`NativeParser.split(f90)` is the right thing to do if `f90` is a string from an environment variable, but is not the right thing to do if taken from the first item of a set of command line arguments.

**Comment by pajarrige** [comment]
Here is a log where I added print statements in "C:\Program Files (x86)\Python38-32\Lib\site-packages\numpy\distutils\fcompiler\__init__.py". 
[build200123.log](https://github.com/numpy/numpy/files/4104972/build200123.log)
I think you are right.
(I reinstalled numpy so I had to find again th place, I'm not so familiar with libs code...)

**Comment by eric-wieser** [comment]
#15404 is my first stab at fixing this

**Comment by seberg** [comment]
@eric-wieser you added the 1.19 milestone at some point, do you think we should aim for that? Or maybe the opposite, aim for early after branching?

**Comment by HaoZeke** [comment]
No longer reproducible after https://github.com/numpy/numpy/pull/24532. :)
