### ISSUE TITLE
Accessing elements of an array with `dtype="U"` may raise `UnicodeDecodeError`

### ISSUE THREAD

**Issue by Zac-HD** [numpy/numpy#15363]
### Reproducing code example:

```python
import sys
import numpy as np

arr = np.zeros(shape=1, dtype="U1")
for i in range(1, sys.maxunicode + 1):
    arr[0] = chr(i)
    arr[0]
```

### Error message:

```python-traceback
In [35]: arr = np.zeros(shape=1, dtype="U1")
    ...: for i in range(1, sys.maxunicode + 1):
    ...:     arr[0] = chr(i)
    ...:     arr[0]
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-35-5a43f3fdb19c> in <module>
      2 for i in range(1, sys.maxunicode + 1):
      3     arr[0] = chr(i)
----> 4     arr[0]

UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: 
	code point in surrogate code point range(0xd800, 0xe000)
```

For some later codepoints the message is instead `code point not in range(0x110000)` (false, as the problematic codepoints are all `<= 0xdfff`).  For extra bonus fun some affected code points are `< 0xd800`, and not all surrogate characters are affected.

### Numpy/Python version information:

Numpy 1.17.4  
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
Does it work without numpy?
```
for i in range(1, sys.maxunicode + 1):
    chr(i).encode('utf-32-le').decode('utf-32-le')
```

**Comment by Zac-HD** [comment]
```python-traceback
      1 for i in range(1, sys.maxunicode + 1):
----> 2     chr(i).encode('utf-32-le').decode('utf-32-le')
      3

UnicodeEncodeError: 'utf-32-le' codec can't encode character '\ud800' in position 0:
    surrogates not allowed
```

But note that the array problem doesn't start until `'\ud82d'`, so some surrogates clearly *are* allowed.

**Comment by mattip** [comment]
Are there open issues that point to this being a problem users have encountered? There are many dark corners in using characters/strings in NumPy arrays since there will always be an impedance mismatch between arrays and unicode. Perhaps we should leave them alone.

**Comment by Zac-HD** [comment]
If the impedence mismatch is so bad that users can't rely on being able to index their arrays, surely we should be deprecating unicode (and perhaps all string) arrays altogther?

I haven't seen issues related to it, but I would expect this to arise in practice for users who are processing text files on Windows (utf-16), and that seems more and more likely with the Python 2 transition now happening even in large and slow institutions.  String arrays, numpy, and memory-mapped columnar text files are otherwise a great fit!

**Comment by charris** [comment]
ISTR reading recent discussions of Python and unicode surrogates somewhere. My impression was that things were in flux.

**Comment by eric-wieser** [comment]
For reference this succeeds:
```python
import sys
for i in range(1, sys.maxunicode + 1):
    chr(i).encode('utf-32-le', errors='surrogatepass').decode('utf-32-le', errors='surrogatepass')
```

**Comment by Zac-HD** [comment]
I think using `errors='surrogatepass'` when accessing elements of unicode arrays would resolve this issue :smile:

**Comment by eric-wieser** [comment]
Solution here is to stop using our `PyUCS2Buffer_AsUCS4` workaround and just use the Python 3.3 API. Will put out a patch in the next few days.

**Comment by Zac-HD** [comment]
Awesome!  Thanks @eric-wieser and all reviewers ❤️
