### ISSUE TITLE
Pandas.groupby.mean() returns infinity although finite values used in the dataframe

### ISSUE THREAD

**Issue by BishoyKelleny** [numpy/numpy#15371]
I am aggregating over some data-frame with respect to entity IDs ('Pickup Census Tract') and averaging the corresponding values ('milePrice'),
In the outcome df, some rows are inf, although I removed any inf values before performing my calculations, I expect this issue has to do with the datatype float64 and the average algorithm used in Pandas (numpy), and tried to round my data and limit the precision to 2 decimals, but it didn't help much, I also tried to get the sum and I would then divide by the entities count, but also didn't help, I am new to Python and there must be something I miss!
Any advice on this issue? 
### Reproducing code example:

```python
import numpy as np
gb=totalTrips.groupby('Pickup Census Tract')
gb.agg({
    'Pickup Census Tract':np.count_nonzero,
    'milePrice':np.mean
})
```

**Comment by seberg** [comment]
I do not think we can help you as is. The largest representable number is `np.finfo(np.float64).max` which is above `1e308`, so if you have such large numbers which you are adding up, you will have a problem.
If you are handling data with a huge range of magnitudes (this is more common with probabilities and small numbers though), it might make sense to work with logarithms instead. Although I have my doubts that this is what you need.

The only real thing I can tell you is to inspect your data carefully and see what exactly you are working with and whether there are some strange types (such as `float16` or even `float32` which have _much_ small range of representable numbers).

**Comment by BishoyKelleny** [comment]
Thank you so much for your response .. actually I tried something and it worked, let me post it here it might help others in the future. I induced Pandas to use float32 for all float columns before reading the csv file, this solved the issue.
