### ISSUE TITLE
dir(numpy) returns duplicate "testing"

### ISSUE THREAD

**Issue by pyscripter** [numpy/numpy#15383]
### Reproducing code example:

```python
import numpy as np
>>> np.__version__
'1.18.1'
>>> len(dir(np))
620
>>> np.testing
<module 'numpy.testing' from 'C:\\Python\\Python38\\lib\\site-packages\\numpy\\testing\\__init__.py'>
>>> len(dir(np))
621
>>> [i for i in dir(np) if i == "testing"]
['testing', 'testing']
```
### Error:
"testing" appears twice in dir(np)

### Numpy/Python version information:

Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
>>> np.__version__
'1.18.1'

**Comment by pyscripter** [comment]
See also https://stackoverflow.com/questions/59851684/python-duplicates-in-dir-is-it-a-bug

**Comment by seberg** [comment]
@pyscripter want to open a PR wih that fix (and best a test)?
