### ISSUE TITLE
numpy array flatten() does not work on jagged arrays

### ISSUE THREAD

**Issue by vnick001** [numpy/numpy#15388]
Hi, 
don't know if this is a bug or a "feature" but flatten does not always work (as expected), 
Interactive Python 3.7 shell:
>>> import numpy
>>> a =[[1,2],[3,4]]
>>> n = numpy.array(a).flatten()
>>> n
array([1, 2, 3, 4])

--->> so far so good but now:

>>> a =[[1,2,5,6],[3,4]]
>>> n = numpy.array(a).flatten()
>>> n
array([list([1, 2, 5, 6]), list([3, 4])], dtype=object)

--->> This is at least not what I would expect from the flatten-method!
Is there a way to avoid that and to get a real flattening? Or is it a bug?
Cheers Nick

**Comment by charris** [comment]
The result *is* the real flattening, the elements (lists) of the object array are exposed in a 1-D array. You can concatenate the arrays like
```
In [2]: a = array([list([1, 2, 5, 6]), list([3, 4])], dtype=object)             

In [3]: a.sum()                                                                 
Out[3]: [1, 2, 5, 6, 3, 4]
```
