### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by surksha** [numpy/numpy#15384]
(env) C:\Python\Python38\Scripts>pip install p:\GDAL-3.0.3-cp38-cp38-win_amd64.whl
Processing p:\gdal-3.0.3-cp38-cp38-win_amd64.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument

(env) C:\Python\Python38\Scripts>python -m install  p:\GDAL-3.0.3-cp38-cp38-win_amd64.whl
C:\env\Scripts\python.exe: No module named install

(env) C:\Python\Python38\Scripts>python -m  pip install  p:\GDAL-3.0.3-cp38-cp38-win_amd64.whl
Processing p:\gdal-3.0.3-cp38-cp38-win_amd64.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument

**Comment by surksha** [comment]
is there anyone who can help me solve this issue? I wanted to use map in my project but getting error in GDAL installation. i have spend much time to solve this error but unable to solve. Please help if anyone know the solution.

**Comment by mattip** [comment]
I think you might have better luck on StackOverflow, but you will have to report there
- where you got `GDAL-3.0.3-cp38-cp38-win_amd64.whl`
- the **entire** error report, not just the last line.

Closing. Feel free to reopen if this is related to NumPy somehow.

**Comment by surksha** [comment]
C:\>pip install gdal
Collecting gdal
  Using cached GDAL-3.0.3.tar.gz (577 kB)
Installing collected packages: gdal
    Running setup.py install for gdal ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\91937\\AppData\\Local\\Temp\\pip-install-7wv46ju7\\gdal\\setup.py'"'"'; __file__='"'"'C:\\Users\\91937\\AppData\\Local\\Temp\\pip-install-7wv46ju7\\gdal\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\91937\AppData\Local\Temp\pip-record-k5sssgnz\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python38\Include\gdal'
         cwd: C:\Users\91937\AppData\Local\Temp\pip-install-7wv46ju7\gdal\
    Complete output (32 lines):
    WARNING: numpy not available!  Array support will not be enabled
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    copying gdal.py -> build\lib.win-amd64-3.8
    copying ogr.py -> build\lib.win-amd64-3.8
    copying osr.py -> build\lib.win-amd64-3.8
    copying gdalconst.py -> build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\osgeo
    copying osgeo\gdal.py -> build\lib.win-amd64-3.8\osgeo
    copying osgeo\gdalconst.py -> build\lib.win-amd64-3.8\osgeo
    copying osgeo\gdalnumeric.py -> build\lib.win-amd64-3.8\osgeo
    copying osgeo\gdal_array.py -> build\lib.win-amd64-3.8\osgeo
    copying osgeo\gnm.py -> build\lib.win-amd64-3.8\osgeo
    copying osgeo\ogr.py -> build\lib.win-amd64-3.8\osgeo
    copying osgeo\osr.py -> build\lib.win-amd64-3.8\osgeo
    copying osgeo\__init__.py -> build\lib.win-amd64-3.8\osgeo
    Fixing build\lib.win-amd64-3.8\gdal.py build\lib.win-amd64-3.8\ogr.py build\lib.win-amd64-3.8\osr.py build\lib.win-amd64-3.8\gdalconst.py build\lib.win-amd64-3.8\osgeo\gdal.py build\lib.win-amd64-3.8\osgeo\gdalconst.py build\lib.win-amd64-3.8\osgeo\gdalnumeric.py build\lib.win-amd64-3.8\osgeo\gdal_array.py build\lib.win-amd64-3.8\osgeo\gnm.py build\lib.win-amd64-3.8\osgeo\ogr.py build\lib.win-amd64-3.8\osgeo\osr.py build\lib.win-amd64-3.8\osgeo\__init__.py
    Skipping optional fixer: ws_comma
    Fixing build\lib.win-amd64-3.8\gdal.py build\lib.win-amd64-3.8\ogr.py build\lib.win-amd64-3.8\osr.py build\lib.win-amd64-3.8\gdalconst.py build\lib.win-amd64-3.8\osgeo\gdal.py build\lib.win-amd64-3.8\osgeo\gdalconst.py build\lib.win-amd64-3.8\osgeo\gdalnumeric.py build\lib.win-amd64-3.8\osgeo\gdal_array.py build\lib.win-amd64-3.8\osgeo\gnm.py build\lib.win-amd64-3.8\osgeo\ogr.py build\lib.win-amd64-3.8\osgeo\osr.py build\lib.win-amd64-3.8\osgeo\__init__.py
    Skipping optional fixer: ws_comma
    running build_ext
    building 'osgeo._gdal' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\extensions
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -Ic:\python\python38\include -Ic:\python\python38\include -I. "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpextensions/gdal_wrap.cpp /Fobuild\temp.win-amd64-3.8\Release\extensions/gdal_wrap.obj
    gdal_wrap.cpp
    extensions/gdal_wrap.cpp(3173): fatal error C1083: Cannot open include file: 'cpl_port.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\91937\\AppData\\Local\\Temp\\pip-install-7wv46ju7\\gdal\\setup.py'"'"'; __file__='"'"'C:\\Users\\91937\\AppData\\Local\\Temp\\pip-install-7wv46ju7\\gdal\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\91937\AppData\Local\Temp\pip-record-k5sssgnz\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python38\Include\gdal' Check the logs for full command output.

C:\>

**Comment by surksha** [comment]
how to deal with this now
