### ISSUE TITLE
dynamic module does not define module export function (PyInit__multiarray_umath)

### ISSUE THREAD

**Issue by gitboi-99** [numpy/numpy#15390]
Hi there,

I'm getting this error trying to import numpy after installing Tensorflow. Starting a new topic as the error message suggested.

I'm currently using Jupyter (5.5.0 I believe) from an installation of Anaconda (5.2). The version of numpy bundled with anaconda (1.14.1) works by itself, however tensorflow requires 1.16.0 or greater. Installing tensorflow from an anaconda prompt with ```pip install --user tensorflow``` results in numpy 1.18.1 being installed in the user directory, and when trying to import tensorflow (or just numpy) after this installation results in the below error. I tried reinstalling the oldest supported version of numpy (1.16.0) manually, however this results in the same error when trying to import. No other Python versions installed except what came with Anaconda 5.2.

Note that the ```--user``` install method is due to running on a work laptop with some fairly heavy installation restrictions.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

#### From numpy 1.16.0:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Roaming\Python\Python36\site-packages\numpy\core\__init__.py in <module>()
     15 try:
---> 16     from . import multiarray
     17 except ImportError as exc:

~\AppData\Roaming\Python\Python36\site-packages\numpy\core\multiarray.py in <module>()
     11 
---> 12 from . import overrides
     13 from . import _multiarray_umath

~\AppData\Roaming\Python\Python36\site-packages\numpy\core\overrides.py in <module>()
      8 
----> 9 from numpy.core._multiarray_umath import add_docstring, ndarray
     10 from numpy.compat._inspect import getargspec

ImportError: dynamic module does not define module export function (PyInit__multiarray_umath)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-0489c759b1c4> in <module>()
      4 from lib import siteutil as jjg
      5 from lib import scatslib
----> 6 from lib import sm_decoding as sm
      7 from lib import LX_extraction_extraction as LXE
      8 from lib import VS_processing as vs

~\Documents\Python Scripts\GIT\JourneyAnalyticsGroup\lib\sm_decoding.py in <module>()
      2 import datetime
      3 from datetime import timedelta, date
----> 4 import numpy as np
      5 import pandas as pd
      6 import mmap

~\AppData\Roaming\Python\Python36\site-packages\numpy\__init__.py in <module>()
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~\AppData\Roaming\Python\Python36\site-packages\numpy\core\__init__.py in <module>()
     45 Original error was: %s
     46 """ % (sys.executable, exc)
---> 47     raise ImportError(msg)
     48 finally:
     49     for envkey in env_added:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\ProgramData\Anaconda3\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dynamic module does not define module export function (PyInit__multiarray_umath)

#### From numpy 1.18.1:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Roaming\Python\Python36\site-packages\numpy\core\__init__.py in <module>()
     23 try:
---> 24     from . import multiarray
     25 except ImportError as exc:

~\AppData\Roaming\Python\Python36\site-packages\numpy\core\multiarray.py in <module>()
     13 
---> 14 from . import overrides
     15 from . import _multiarray_umath

~\AppData\Roaming\Python\Python36\site-packages\numpy\core\overrides.py in <module>()
      6 
----> 7 from numpy.core._multiarray_umath import (
      8     add_docstring, implement_array_function, _get_implementing_args)

ImportError: dynamic module does not define module export function (PyInit__multiarray_umath)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-0489c759b1c4> in <module>()
      4 from lib import siteutil as jjg
      5 from lib import scatslib
----> 6 from lib import sm_decoding as sm
      7 from lib import LX_extraction_extraction as LXE
      8 from lib import VS_processing as vs

~\Documents\Python Scripts\GIT\JourneyAnalyticsGroup\lib\sm_decoding.py in <module>()
      2 import datetime
      3 from datetime import timedelta, date
----> 4 import numpy as np
      5 import pandas as pd
      6 import mmap

~\AppData\Roaming\Python\Python36\site-packages\numpy\__init__.py in <module>()
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~\AppData\Roaming\Python\Python36\site-packages\numpy\core\__init__.py in <module>()
     52 """ % (sys.version_info[0], sys.version_info[1], sys.executable,
     53         __version__, exc)
---> 54     raise ImportError(msg)
     55 finally:
     56     for envkey in env_added:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "C:\ProgramData\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dynamic module does not define module export function (PyInit__multiarray_umath)

### Numpy/Python version information:

Sys: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Numpy: 1.18.1 and 1.16.0 (oldest version supported by TensorFlow) were attempted; same error.
Numpy 1.14.1 was installed with the anaconda install and does not have any errors if I remove the newer ```--user``` installed versions.
Windows 10: version 1803 (OS Build 17134.1130)

**Comment by mattip** [comment]
Are you sure you are using python3's pip? I think the error you are getting indicates you are trying to load a python2 c-extension module (`_multiarray_umath.pyd`) with python3. You might want to use `python3 -mpip install --user ...` instead of `pip install --user ...`.

**Comment by gitboi-99** [comment]
> Are you sure you are using python3's pip? I think the error you are getting indicates you are trying to load a python2 c-extension module (`_multiarray_umath.pyd`) with python3. You might want to use `python3 -mpip install --user ...` instead of `pip install --user ...`.

I think it's installing a python 3 module. I get the below status message as part of the installation process; does the ```cp36``` mean it's getting a python 3.6 module? 

```Collecting numpy<2.0,>=1.16.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/53/74/b997e4c7b4abc668e99f4c3dba87ee2c6f7559319af756cc1ede37665a8d/numpy-1.18.1-cp36-cp36m-win_amd64.whl (12.8MB)```

**Comment by dinesh-rajaveeran** [comment]
@gitboi-99 Any luck ? I'm facing the same issue when trying to execute a Kivy Python App based on bumpy on XCode-> iOS.
`File "/Users/drajaveeran/kivy_example/kivy-ios/dist/root/python3/lib/python3.7/imp.py", line 342, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__multiarray_umath)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/drajaveeran/kivy_example/kivy-ios/ttt-ios/YourApp/main.py", line 11, in <module>
   File "/Users/drajaveeran/kivy_example/kivy-ios/ttt-ios/YourApp/lib/view/mainmenuview.py", line 4, in <module>
   File "/Users/drajaveeran/kivy_example/kivy-ios/ttt-ios/YourApp/lib/view/singleplayerview.py", line 10, in <module>
   File "/Users/drajaveeran/kivy_example/kivy-ios/ttt-ios/YourApp/lib/game/bot.py", line 2, in <module>
   File "/Users/drajaveeran/Library/Developer/CoreSimulator/Devices/D9D9B754-9F05-4CA2-A4B3-0D9190245C08/data/Containers/Bundle/Application/955956E8-9EA0-4B4B-A55E-2E38B9C54AFF/ttt.app/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
     from . import core
   File "/Users/drajaveeran/Library/Developer/CoreSimulator/Devices/D9D9B754-9F05-4CA2-A4B3-0D9190245C08/data/Containers/Bundle/Application/955956E8-9EA0-4B4B-A55E-2E38B9C54AFF/ttt.app/lib/python3.7/site-packages/numpy/core/__init__.py", line 54, in <module>
     raise ImportError(msg)
 ImportError: 
 
 IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!`

**Comment by gitboi-99** [comment]
I'm sorry, no. I ended up giving up and using the much simpler neural net
classifier from the sklearn library. I hope you have more luck than I do,
seems like a quirky library to get installed properly.

**Comment by rossbar** [comment]
I'm going to close this due to inactivity. If the issue persists please reopen, or if there are problems that you believe might be related, please open a new issue and link to this one.

**Comment by tdunnigan** [comment]
> @gitboi-99 Any luck ? I'm facing the same issue when trying to execute a Kivy Python App based on bumpy on XCode-> iOS.
> `File "/Users/drajaveeran/kivy_example/kivy-ios/dist/root/python3/lib/python3.7/imp.py", line 342, in load_dynamic
> ImportError: dynamic module does not define module export function (PyInit__multiarray_umath)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Users/drajaveeran/kivy_example/kivy-ios/ttt-ios/YourApp/main.py", line 11, in
> File "/Users/drajaveeran/kivy_example/kivy-ios/ttt-ios/YourApp/lib/view/mainmenuview.py", line 4, in
> File "/Users/drajaveeran/kivy_example/kivy-ios/ttt-ios/YourApp/lib/view/singleplayerview.py", line 10, in
> File "/Users/drajaveeran/kivy_example/kivy-ios/ttt-ios/YourApp/lib/game/bot.py", line 2, in
> File "/Users/drajaveeran/Library/Developer/CoreSimulator/Devices/D9D9B754-9F05-4CA2-A4B3-0D9190245C08/data/Containers/Bundle/Application/955956E8-9EA0-4B4B-A55E-2E38B9C54AFF/ttt.app/lib/python3.7/site-packages/numpy/**init**.py", line 142, in
> from . import core
> File "/Users/drajaveeran/Library/Developer/CoreSimulator/Devices/D9D9B754-9F05-4CA2-A4B3-0D9190245C08/data/Containers/Bundle/Application/955956E8-9EA0-4B4B-A55E-2E38B9C54AFF/ttt.app/lib/python3.7/site-packages/numpy/core/**init**.py", line 54, in
> raise ImportError(msg)
> ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!`
Were you ever able to resolve this issue?  Running into the same problems right now while trying to run a Kivy app in XCode.

**Comment by dinesh-rajaveeran** [comment]
@tdunnigan Yes, I finally made it work somehow.
Python 3.7.6
Numpy 1.18.1
Kivy 1.11
XCode 10.2

**Comment by ResearcherSara** [comment]
Do anyone suggest any advice for this issue? I am using python3.9 with openai0.20 and getting "Exception has occurred: ImportError
dynamic module does not define module export function (PyInit_md)
ModuleNotFoundError: No module named 'chardet'" error. So tired of not knowing what to do:-(
