### ISSUE TITLE
Add "blkdiag" command from MATLAB (Trac #943)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1541]
_Original ticket http://projects.scipy.org/numpy/ticket/943 on 2008-10-27 by trac user chrismurf, assigned to unknown._

A command similar to MATLAB's "blkdiag" would be handy in Numpy.  I'm not sure what the correct component is for this - I can imagine it going in the normal namespace like 'diag', but tagged the numpy.linalg component in case it's deemed unworthy of the normal namespace.

I've attached an example implementation, which almost certainly breaks every Numpy coding convention (but is functional).  If there's interest but the code quality is not acceptable, I'm happy to clean it up for inclusion.

**Comment by mattip** [comment]
Closing, `block_diag` exists in scipy
