### ISSUE TITLE
error: No module named 'numpy', when it is installed

### ISSUE THREAD

**Issue by Andreas-debug** [numpy/numpy#15424]
Hello, I am creating this issue since it seems nothing else is working.
My Python is unable to import NumPy, even when pip says it is installed, and all other modules work just fine.

`python import numpy as np` generates the error: ```Traceback (most recent call last):
  File "C:\Users\andre\Downloads\full voice\Real-Time-Voice-Cloning-master\demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "C:\Users\andre\Downloads\full voice\Real-Time-Voice-Cloning-master\utils\argutils.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'```

I am using Python 3.7.5, and downloading with pip 20.0.1 on windows 10. 
I do not have multiple versions of Python installed, and am building in Python 3.7.5 Shell

Thanks in advance,
Andrew

**Comment by mattip** [comment]
Can you show the output of `python -mpip install numpy` ?

**Comment by Andreas-debug** [comment]
> Can you show the output of `python -mpip install numpy` ?

`Requirement already satisfied: numpy in c:\users\andre\appdata\local\programs\python\python37-32\lib\site-packages (1.18.1)`

**Comment by mattip** [comment]
So you should be using the python in `c:\users\andre\appdata\local\programs\python\python37-32`. If you put `import sys; print(sys.executable)` in `C:\Users\andre\Downloads\full voice\Real-Time-Voice-Cloning-master\utils\argutils.py` before the `import numpy as np`, does it show that python?

**Comment by Andreas-debug** [comment]
No it doesn't... Any way to fix that issue? `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\pythonw.exe` is the path

**Comment by Andreas-debug** [comment]
I found a solution. I just uninstalled the python IDE for Visual Studio, and now it works.
Thanks for the help!

**Comment by Andreas-debug** [comment]
Realized someone might need this...

**Comment by mattip** [comment]
Closing, this is common but each instance is a bit different.

**Comment by asmaaayyash** [comment]
i am having this problem right now, still don't know the solution, can someone help?

**Comment by mattip** [comment]
@asmaaayyash this issue is closed. Please open a new one, and provide
- what exactly is the error message (as pasted text, not an image)
- how you installed python and numpy

**Comment by sub-h** [comment]
The python -mpip install numpy command worked for me
Thanks a lot!

**Comment by headcrabz** [comment]
python -mpip install numpy worked for me as well.
