### ISSUE TITLE
MAINT: Use fstrings instead of other string formatting methods

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#15420]
In many cases, fstrings (i.e. `f"{variable}"` are more readable than old style `"%s" % variable` or `"{}".format(variable)` versions. These were until now unused within NumPy due to support for Python <=3.5.

While not a high priority, replacing these in parts can be a straight forward task for new developers who wish to contribute, since it mainly requires finding these instances and making a small judgment call of how much it improves readability and how best to format the code based on [PEP-8](https://www.python.org/dev/peps/pep-0008/) guidelines and our [contribution guidelines](https://docs.scipy.org/doc/numpy/dev/).

Pull requests very welcome, simply reference this issue in a PR so that others will know you are working on it. It is probably best to concentrate on a certain part of NumPy to keep the PRs concise.

(I opened the issue mainly to incentive new contributions, so if this does not happen, or it appears the readability improvements are not worth it, do not hesitate to close it.)

**Comment by fk03983** [comment]
I am working on the files inside linalg directory.

**Comment by notanton** [comment]
I have submitted a pull request updating the files inside `numpy/polynomial` (#15434) for review.

**Comment by mattip** [comment]
I am a bit concerned about the churn this issue is causing. While the intention is good, maybe we should close this, and slowly replace formatting code when we touch it for other reasons.
