### ISSUE TITLE
np.divide np.mod, returns "wrong" number

### ISSUE THREAD

**Issue by stokhos** [numpy/numpy#15432]
np.divid(4.1,0.1) and  np.mod(4.1,0.1) return 40.999999999999, instead of 41.

### Reproducing code example:

```python
import numpy as np
np.divid(4.1,0.1) and  np.mod(4.1,0.1)

```

### Error message:
No error message

### Numpy/Python version information:
'1.17.3'

**Comment by charris** [comment]
`0.1` cannot be exactly represented in IEEE floating point, so the numbers you think are being used are *not* the numbers that are actually being used.
```
In [1]: '%30.23f' % 0.1                                                         
Out[1]: '     0.10000000000000000555112'
```

**Comment by stokhos** [comment]
Yes, I know this, is there a workaround for this?
mod(4.1,0.1)==0, this returns false, but it should be true. And in finance we deal with small float number a lot.

**Comment by stokhos** [comment]
can we add this to mod operation 

np.abs(np.mod(4.1,0.1) - 0.1) > eps

**Comment by WarrenWeckesser** [comment]
Do you have to use numpy?  A standard suggestion for working around the limitations of IEEE floating point representation is to use something like the `decimal` library:

```
In [47]: from decimal import Decimal

In [48]: a = Decimal('4.1')

In [49]: b = Decimal('0.1')

In [50]: a / b
Out[50]: Decimal('41')

In [51]: mod(a, b)
Out[51]: Decimal('0.0')
```

**Comment by eric-wieser** [comment]
Don't forget you can put Decimal objects in numpy arrays
