### ISSUE TITLE
np.histogram does not support np.ndarray subclasses

### ISSUE THREAD

**Issue by l-johnston** [numpy/numpy#15437]
When computing a histogram where the input data and range are both of the same np.ndarray subclass, np.histogram fails. The subclass in this case is [unyt_array](https://github.com/yt-project/unyt) that extends np.ndarray with physical units. The first line of ``histogram`` converts the input data to a pure np.ndarray, then subsequently attempts to subtract first_edge, which is of unyt_array type, from this unitless np.ndarray. The unyt library converts the np.ndarray to a dimensionless unyt_array and the subtraction raises an exception since the operands have different units (dimensions).

The problem is in ``_ravel_and_check_weights`` where the first line of this function, ``a = np.asarray(a)`` converts the unyt_array to np.ndarray. Replacing ``np.asarray`` with ``np.asanyarray`` solves the problem.

Is it possible for numpy to update ``_ravel_and_check_weights`` so that ``histogram`` fully supports subclasses?

### Reproducing code example:

```python
import numpy as np
from unyt import unyt_array
x = unyt_array(np.random.normal(size=1000), "m")
isinstance(x, np.ndarray)
True
np.histogram(x, bins=10, range=(x.min(), x.max()))
```

### Error message:

Traceback (most recent call last):
  File "/mnt/d/Python/unyt/.venv/lib/python3.6/site-packages/numpy-1.18.1-py3.6-linux-x86_64.egg/numpy/lib/histograms.py", line 368, in _unsigned_subtract
    dt = signed_to_unsigned[dt.type]
KeyError: <class 'numpy.float64'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in histogram
  File "/mnt/d/Python/unyt/.venv/lib/python3.6/site-packages/numpy-1.18.1-py3.6-linux-x86_64.egg/numpy/lib/histograms.py", line 869, in histogram
    f_indices = _unsigned_subtract(tmp_a, first_edge) * norm
  File "/mnt/d/Python/unyt/.venv/lib/python3.6/site-packages/numpy-1.18.1-py3.6-linux-x86_64.egg/numpy/lib/histograms.py", line 370, in _unsigned_subtract
    return np.subtract(a, b, dtype=dt)
  File "/mnt/d/Python/unyt/unyt/unyt/array.py", line 1733, in __array_ufunc__
    raise UnitOperationError(ufunc, u0, u1)
unyt.exceptions.UnitOperationError: The <ufunc 'subtract'> operator for unyt_arrays with units "dimensionless" (dimensions "1") and "m" (dimensions "(length)") is not well defined.

### Numpy/Python version information:
1.18.1 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0]

**Comment by rgommers** [comment]
A `unyt_array` is accepted just fine, the issue is the `unyt_quantity`'s in `range`. This works:
```
np.histogram(x, bins=10, range=(float(x.min()), float(x.max())))
```

**Comment by l-johnston** [comment]
Ultimately, the objective is to preserve the units so that the range can be set using values with units. Take a look at the very beginning of np.histogram where it converts the incoming array using np.asarray and strips the unit information.

np.histogram differs from some other Numpy functions that do a better job of working with ndarray subclasses. I would like the Numpy team to consider this aspect of histogram.

Matplotlib uses np.histogram and this is where I first discovered the problem. Unyt has matplotlib support making it possible to plot with units and that means even configuring the axis limits using values with units.

**Comment by rgommers** [comment]
> Ultimately, the objective is to preserve the units so that the range can be set using values with units. 

At best, units will get stripped from everything and things work, returning ndarrays.

> Take a look at the very beginning of np.histogram where it converts the incoming array using np.asarray and strips the unit information.

The `asarray` call can't be avoided there, any chance to it will be backwards incompatible. Making things work like in my `range=(float(x.min()), ...` line above is possible. For a more complete solution that does return a `unyt_array`, `unyt` needs to implement `__array_function__`, as @ngoldbaum said in https://github.com/yt-project/unyt/issues/130.
