### ISSUE TITLE
Non-deterministic behavior from numpy.fromfile

### ISSUE THREAD

**Issue by tantrev** [numpy/numpy#15440]
I've been trying to use numpy.fromfile with dask's delayed interface to parallelize reading a very large file (~1.3TB) because I seem to have hit the throughput limit from numpy using a single thread.  Unfortunately, I've been running into some problems with a toy dataset.  On my Windows 10 laptop with a SSD, the code below (without any dask parallelism) shows that using numpy's fromfile with an offset occasionally leads to non-deterministic behavior.  I'm not quite sure what's going on, but it'd be nice to get to the bottom of it.  An example dataset may be found here (test.txt in the code below) - https://pastebin.com/raw/PG3A7SUz

### Reproducing code example:

```
import numpy as np
import os
import pandas as pd

myfile = "test.txt" #File has 99 rows, 1025 columns
method = "b+r" 
numSplits = 5
fileSize = os.path.getsize(myfile)
totalNumRows = int(fileSize/1025)
rowChunkSize = int(np.ceil(totalNumRows/numSplits))
data = []

def getData(inputFile,inputChunk,inputChunkSize):
    inputFile2 = open(inputFile,mode="b+r")
    current_row = int(inputChunk/1025)
    return_df = pd.DataFrame(np.fromfile(inputFile2,dtype=('uint8',1025),sep="",count=inputChunkSize,offset=inputChunk)==48)
    return_index = range(current_row,current_row+return_df.shape[0])
    return_df.index = return_index
    inputFile2.close()
    return return_df

resultList = list()

for i in range(99):
    result1 = (getData(myfile,0,99)==getData(myfile,0,100)).sum().sum()
    result2 = (getData(myfile,1,99)==getData(myfile,1,100)).sum().sum()
    result3 = (getData(myfile,2,99)==getData(myfile,2,100)).sum().sum()
    resultList.append((result1,result2,result3))
    
result_df = pd.DataFrame(resultList)
print(result_df.describe())
```

###Example code output

```
                    0              1              2
 count      99.000000      99.000000      99.000000
 mean   100657.777778   94950.333333   94950.262626
 std      7902.411334   20039.451069   20039.708708
 min     22824.000000   22669.000000   22668.000000
 25%    101452.000000  100450.000000  100450.000000
 50%    101452.000000  100450.000000  100450.000000
 75%    101452.000000  100450.000000  100450.000000
 max    101452.000000  100450.000000  100450.000000
```

### Numpy/Python version information:

1.17.2 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

**Comment by seberg** [comment]
I do not see the point, you are using an offset, so why do you expect the same result, I modified it to return an array and did:
```
In [46]: d1 = getData(myfile, 0, 99)                                                                                    
In [47]: d2 = getData(myfile, 2, 99)                                                                                    
In [48]: (d1.ravel()[2:] == d2.ravel()[:-2]).all()                                                                      
Out[48]: True
```
seems correct to me.

**Comment by tantrev** [comment]
Sorry, the code above is a bit confusing and I didn't quite explain clearly.  In the above case, the offset by itself does not seem to be the root of the problem (though I think l have observed that behavior).  What's happening is that when an offset is used with fromfile and different arguments to the count function, the same result is not always returned.

If you look at the output from the pandas describe function, it should **always** return the same answer for each result. But it doesn't.  That's why something fishy is going on.

**Comment by seberg** [comment]
@tantrev, I do not see it and I tried to reproduce it. Could you please refine your example to be a bit more easy to read and preferably remove all pandas. Ideally, make the loop so that it breaks/raises an error when the failure occurred (if it only occurs after a while).

**Comment by tantrev** [comment]
So you're absolutely right - I was having either having an issue with pandas or numerical accuracy (from approximately current_row), it's not entirely clear which.  After getting rid of both, everything started acting sanely (including numpy's from_file).

I did notice though that the "count" argument in numpy's fromfile seems to require a "reasonable" number (i.e. it can't extend beyond the end of the file) for rational output though.

For example, when the above code has been converted to use arrays with the above dataset (99 rows, 1025 columns):
```
a = getData(myfile,0,99).ravel()
b = getData(myfile,0,99).ravel()
c = a==b
print(c.sum())
```
produces different output than:
```
a = getData(myfile,0,99).ravel()
b = getData(myfile,0,100).ravel()
c = a==b
print(c.sum())
```

**Comment by seberg** [comment]
Can you see if you can make a simple example for the possible `count` issue and open a new issue? That would be great, I would not be surprised at all about issues with the `count` argument.

**Comment by tantrev** [comment]
Of course!  I'm just about to have dinner, but will make a new issue later tonight.  Thanks for the help.
