### ISSUE TITLE
ImportError: DLL load failed: The specified module (TestRailTools) could not be found. 

### ISSUE THREAD

**Issue by Jeyaanand** [numpy/numpy#15443]
Unable to import TestRailTools binary file from the module directory "utilities.testrail", a binary file is available in the path not importable.

>>> import utilities.testrail.TestRailTools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
>>>
>>> dir(utilities.testrail)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>>

**Comment by mattip** [comment]
Hi @Jeyaanand you are reporting an issue on the NumPy issue tracker. Is there a reason you think this has something to do with NumPy? If so, please follow the instructions that appear when you open a new issue: 
- describe the issue in detail
- A short code example
```python
import numpy as np
<< your code here >>
```
- the complete error message
- Output from `import sys, numpy; print(numpy.__version__, sys.version)`

I will close this so you can start over and use the template to report correctly. Note that most of us have absolutely no experience with TestRailTools, so will need help if that is part of the problem.

**Comment by Jeyaanand** [comment]
Hi Matti,

It's not related to NumPy, created testrail module and trying to import binary file in  the name of TestRailTools which not getting imported
