### ISSUE TITLE
importing numpy issue

### ISSUE THREAD

**Issue by bshmid** [numpy/numpy#15455]
hallo, I'm having a problem with importing numpy
just by having:

import numpy

alone I'm getting:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "IPIPE_DTMF_encoder_WC.py", line 2, in <module>
    import numpy
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

I'm using RPI3,
Python 3.6.8 is running as default, I've checked for numpy installed:

pi@raspberrypi:~ $ sudo apt-get install python-numpy python3-numpy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-numpy is already the newest version (1:1.16.2-1).
python3-numpy is already the newest version (1:1.16.2-1).
0 upgraded, 0 newly installed, 0 to remove and 297 not upgraded.

Thanks a lot

**Comment by neal2018** [comment]
Have you tried reinstalling numpy? It seems reinstallation should solve the problem.

**Comment by mattip** [comment]
You are using `/usr/bin/python`, which on most systems is python2. But you are importing from `/usr/lib/python3`. Could you confirm that `/usr/bin/python` is indeed python3.6.8?

**Comment by bshmid** [comment]
> You are using `/usr/bin/python`, which on most systems is python2. But you are importing from `/usr/lib/python3`. Could you confirm that `/usr/bin/python` is indeed python3.6.8?

I think I can by:
pi@raspberrypi:~ $ python -V
Python 3.6.8

**Comment by mattip** [comment]
What does `ls /usr/lib/python3/dist-packages/numpy/core/*.so` show? There should be a `_multiarray_umath*.so`.

**Comment by bshmid** [comment]
> ls /usr/lib/python3/dist-packages/numpy/core/*.so

pi@raspberrypi:~ $ ls /usr/lib/python3/dist-packages/numpy/core/*.so
/usr/lib/python3/dist-packages/numpy/core/_dummy.cpython-37m-arm-linux-gnueabihf.so
/usr/lib/python3/dist-packages/numpy/core/_multiarray_tests.cpython-37m-arm-linux-gnueabihf.so
/usr/lib/python3/dist-packages/numpy/core/_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so
/usr/lib/python3/dist-packages/numpy/core/_operand_flag_tests.cpython-37m-arm-linux-gnueabihf.so
/usr/lib/python3/dist-packages/numpy/core/_rational_tests.cpython-37m-arm-linux-gnueabihf.so
/usr/lib/python3/dist-packages/numpy/core/_struct_ufunc_tests.cpython-37m-arm-linux-gnueabihf.so
/usr/lib/python3/dist-packages/numpy/core/_umath_tests.cpython-37m-arm-linux-gnueabihf.so

**Comment by mattip** [comment]
It is there, but it is the version for python37 `_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so` and you are using python 36. You need to find a numpy package for python36, not python37

**Comment by bshmid** [comment]
> It is there, but it is the version for python37 `_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so` and you are using python 36. You need to find a numpy package for python36, not python37

I see all the packages are like that.
Does that mean I have to reinstall numpy? And what is the best way to do so? My pip keeps on telling me:  ImportError: cannot import name 'sysconfig'

**Comment by mattip** [comment]
I think you might have to look for python36-numpy. You may be trying to do something your distro does not support. There is not a lot we can do from here since we do not package NumPy for distributions. You may have better luck on forums that specialize in your distribution of linux.

**Comment by bshmid** [comment]
Thanks a million, I did :+1: 
pi@raspberrypi:~ $ python3.6 -m pip install numpy
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy
  Using cached numpy-1.18.1.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... done
  Created wheel for numpy: filename=numpy-1.18.1-cp36-cp36m-linux_armv7l.whl size=10579958 sha256=bbd2e75a7843ee90ef32deb5beac21868b9b24c00323994fed92f072f4c45e11
  Stored in directory: /home/pi/.cache/pip/wheels/92/18/20/83339b2576b5911519a6b616d8b4a6df8b14358ba5cd612a0b
Successfully built numpy
Installing collected packages: numpy
Successfully installed numpy-1.18.1

And that cured the problem.
