### ISSUE TITLE
zeros(None) behaves as zeros(()), and likewise for ones, empty, full

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#15454]
The first argument to np.zeros is documented as `shape : int or tuple of ints`, but actually None is also allowed, with the same meaning as the empty tuple ().

### Reproducing code example:

```python
In [1]: np.zeros(None)                                                                                              
Out[1]: numpy.ndarray(0.)

In [2]: np.zeros(None).shape                                                                                        
Out[2]: ()
```

I think erroring out instead may help catching some bugs (well, it would have in my case :-)).

### Numpy/Python version information:

1.18.1 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0]

**Comment by eric-wieser** [comment]
Might be interesting to see how noisy a deprecation is here.

**Comment by seberg** [comment]
I would be OK with trying it as well, if there is no serious fallout in the main downstream packages. My clandestine motives would be thinking that `None`, in some places, could mean "scalar".

**Comment by seberg** [comment]
There has been a deprecation warning on this for a while actually, so closing.  I suppose this might come up again whenever someone looks into finalizing the warning.
