### ISSUE TITLE
BUG: Large overhead in some random functions

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#15460]
This issue is extracted from gitter (by @andyfaff – I saw it only randomly, so creating this before we forget).

Some random generator functions such as `random()` have a huge overhead compared to their legacy `RandomState` versions:
```
rs = np.random.RandomState()
rg = np.random.default_rng()

%timeit rs.random()                                       
# 432 ns ± 9.18 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%timeit rg.random()                                       
# 5.19 µs ± 61.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

The reason for this is the support of the `dtype=` keyword argument. A secondary reason (and maybe second speed issue) is that `np.dtype.name` is a *very* slow operations (it could plausibly be cached).

However, the solution here will be to simply avoid the whole `np.dtype(dtype).name` construct as much as possible and maybe adding a fastpath for the case when `dtype` is not used. `np.dtype(dtype).type is np.float64` may be a solution, or `dtype is np.float64 or np.dtype(dtype) is np.float64` to speed up the default branch.

---

Checking that we have benchmarks – or adding simple small array ones in a first commit – for this would be good when this is fixed.

**Comment by eric-wieser** [comment]
> avoid the whole np.dtype(dtype).name construct as much as possible

Agreed, hopefully the slowness is enough to motivate people not to use it ;)

**Comment by andyfaff** [comment]
Is a similar speedup possible for `Generator.uniform`, as well as `Generator.random`?. It seems that they're probably going to be doing exactly the same, except the former does the optional scaling.

```
>>> %timeit rs.random()
308 ns ± 7.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

>>> %timeit rg.uniform()
2.11 µs ± 73.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

>>> %timeit rg.random()
3.37 µs ± 85.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
We're only talking a couple of microseconds, but it's worth it if it's an easy win.

**Comment by seberg** [comment]
I consider it a speed bug, since the added overhead is a small factor larger than a typical (fairly simple) python function call (and almost a factor of 10 of what it should be).
This is probably a fairly straight forward issue to solve, so PRs welcome.

**Comment by przemb** [comment]
I will try to speed it up ;)

**Comment by mattip** [comment]
@przemb you may find the comments starting [here](https://github.com/numpy/numpy/pull/15463#pullrequestreview-351965452) from gh- 15463 useful

**Comment by przemb** [comment]
@mattip Thank you so much :) I tried to follow mentioned comments, in case of any potential improvements please let me know.
