### ISSUE TITLE
np.linalg.svd with hermitian=True does not properly sort singular values

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#15462]
### Reproducing code example:

`svd` with `hermitian=True` (introduced by @eric-wieser in https://github.com/numpy/numpy/pull/12693) has a bug with the order of singular values:
```python
import numpy as np

a = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
u, s, v = np.linalg.svd(a, hermitian=True)
print(s)
```
Outputs: `[1.41421356e+00 6.07153217e-18 1.41421356e+00]`

Per the contract of `svd`, the singular values should be sorted in descending order, but they aren't here. That's because we simply reverse the order of eigenvalues than sorting, which only suffices if all eigenvalues happen to be positive.

### Numpy/Python version information:

1.17.5 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]

**Comment by charris** [comment]
I assume you would like to see this fixed in a 1.17.6?

**Comment by seberg** [comment]
Would make sense probably. I just it with high, because it seems to me like this can cause silent result corruption with a harmless looking change.

**Comment by eric-wieser** [comment]
Darn, that was silly of me, ordering `x` doesn't order `x**2`. I suppose we need an `argsort` in there
