### ISSUE TITLE
np.array(..., dtype=longdouble) does not always produce longdouble

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15467]
```python
>>> np.array(1, dtype=np.longdouble).dtype.type is np.longdouble
True
>>> np.array(np.float64(1), dtype=np.longdouble).dtype.type is np.longdouble
False
```
Same for overlapping integer types :
```python
>>> long_overlap = np.intc if windows else np.longlong
>>> np.array(1, dtype=long_overlap).dtype.type is long_overlap
True
>>> np.array(np.int_(1), dtype=long_overlap).dtype.type is long_overlap
False
```

**Comment by seberg** [comment]
Hmm, must be a bug in the type promotion/common dtype operation thingking that `promote(longdouble, double)` is double and not longdouble (both directions should be ensured to return longdouble/the theoretically larger dtype).

**Comment by eric-wieser** [comment]
Overzealous use of `PyArray_EquivTypes`, it seems - PR submitted.

**Comment by eric-wieser** [comment]
I wish I'd written down why I cared about this - I'm pretty sure it blocked me somewhere else...
