### ISSUE TITLE
Segfault with malicious string subclass

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15472]
This code:

https://github.com/numpy/numpy/blob/8493ea5655d7da7645fed2c6ec5c341605364cc8/numpy/core/src/multiarray/scalartypes.c.src#L2646-L2651

Can only be exercised for `str_` subclasses when combined with something strangely odd like:

```python
class Evil:
    fired = False
    def __str__(self):
        if not self.fired:
            self.fired = True
            raise NotImplementedError
        return "benign"

class Bad(np.str_): pass

Bad(Evil())  # segfault
```

I don't think we're supposed to write to a live unicode object, especially one with no buffer allocated.

cc @seberg, who's been reviewing some of my changes around these lines

**Comment by rossbar** [comment]
I ran the above example in v1.18.1 and got the `NotImplementedError` instead of the segfault. I did a `git bisect` to locate which change introduced the segfault and came back with c0ca814

I'm not sure whether this was expected behavior with c0ca814, but hopefully this info is helpful.

**Comment by eric-wieser** [comment]
That's good to know, thanks. The commit in question fixed a different segfault IIRC, but there's clearly more to do here.

**Comment by eric-wieser** [comment]
Segfault seems to be gone, but the returned string is empty and the error silenced.

**Comment by charris** [comment]
@eric-wieser @seberg Just thought I'd ping this to check the status.

**Comment by rgommers** [comment]
Given the trouble with issues with titles like the one used here, how about we change the title and close this, unless there is something urgent left to do?

**Comment by rgommers** [comment]
The segfault was fixed 2 years ago, closing. Please open a new issue if there's anything of interest left to do.
