### ISSUE TITLE
Installing Fiona/GeoPandas

### ISSUE THREAD

**Issue by L-Haw** [numpy/numpy#15478]
<! I should start by stating that I am very new to Python. I need to install "geopandas", but it seems that I need to install "Fiona" first. I am having issues installing the latter.>

### Reproducing code example:

<! -- python setup.py build_ext -I'C:\Program Files\GDAL\include' -lgdal_i -L'C:\Program Files\GDAL\lib' install Fiona --gdalversion 2.2 >

```python
import numpy as np
<< -- >>
```

### Error message:

<! -- Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    from numpy.distutils.core import setup
  File "C:\Program Files\QGIS 2.18\apps\Python27\Lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\QGIS 2.18\apps\Python27\Lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Program Files\QGIS 2.18\apps\Python27\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found) >

### Numpy/Python version information:

<! -- '1.16.5', '2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)]' >

**Comment by rossbar** [comment]
@L-Haw this is very likely an issue with setting up environments on your system. Assuming you are using `conda` to install python packages on your system, please try the following:

```bash
conda create -n testenv python
conda activate testenv
conda install numpy
python -c "import numpy as np; print(np.__version__)"
```
If you get a `numpy` error from the above procedure, please follow up below. If not, then this is likely not a numpy issue and is related to the way your environment is specified or the other packages you are attempting to install.

**Comment by L-Haw** [comment]
Dear Ross. Thanks for your answer. I tried to create the testenv via the 1st instruction ( conda create -n testenv python ) but I get the following error:
`Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package sqlite conflicts for:
python -> sqlite[version='>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0']
Package vc conflicts for:
python -> vc[version='10.*|14.*|9.*|>=14,<15.0a0|>=14.1,<15.0a0|>=9,<10.0a0']
Package openssl conflicts for:
python -> openssl[version='>=1.1.1a,<1.1.2a']
Package vs2008_runtime conflicts for:
python -> vs2008_runtime
Package vs2010_runtime conflicts for:
python -> vs2010_runtime
Package pip conflicts for:
python -> pip
Package vs2015_runtime conflicts for:
python -> vs2015_runtime
Note that strict channel priority may have removed packages required for satisfiability.`
I should say that I'm new to Python and have little knowledge about how environments and packages are linked or communicate with each others... I would be grateful if you can suggest a reference, webpage, youtube video, etc. that explains these fundamental stuff (ideally for people with Matlab background).
Thanks again Ross!

**Comment by rossbar** [comment]
Yes, this indicates there is something wrong with your anaconda/python installation. I am not a windows user so I can't comment on the specific package conflicts. If I were in your shoes I would try uninstalling/reinstalling anaconda and reading/following [the environment management docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) carefully.

Re: documentation for learning about python, the [official python documentation](https://docs.python.org/3/) is the ultimate resource - you might want to focus specifically on the [python setup and usage docs](https://docs.python.org/3/using/index.html). The [Hitchhiker's Guide to Python](https://docs.python-guide.org/) is another nice resource - many find it a bit more accessible than the docs.

Since this is not a NumPy issue, I'm closing the ticket. If you have issues with NumPy specifically down the road, feel free to open a new one. Good luck!

**Comment by L-Haw** [comment]
Many thanks for your answer Ross and for the links! I was afraid that the only way out will be to uninstall/install everything (I am using other software connected to Python as well), but will consider doing so now.
Thanks for your time!
Lara
