### ISSUE TITLE
libraries= vs blas_libs= in site.cfg

### ISSUE THREAD

**Issue by dimpase** [numpy/numpy#15481]
This is folloup to #15338, where is was discovered that options in `site.cfg`'s section `libraries` and
`blas_libs` in `[blas]` section are not equivalent. Namely
```
[blas]
libraries=foo,bar
...
```
does not lead to both `foo` and `bar` picked up in linker's flags, only `-lfoo` is added, whereas
```
[blas]
blas_libs=foo,bar
...
```
does add both `-lfoo -lbar`

In some cases it leads to a problem (where `libblas` and `libcblas` are different libraries).

**Comment by rgommers** [comment]
Both `site.cfg.example` and the `setup.py` based build are now gone, so I will close this issue. Thanks @dimpase.
