### ISSUE TITLE
Add Rademacher Distribution to numpy.random

### ISSUE THREAD

**Issue by r0cketr1kky** [numpy/numpy#15489]
I want to write a function to include Rademacher distribution that generates a random number i.e. values +1 and -1 with equal probability. Could you assign me this task?

**Comment by rkern** [comment]
I don't think we'll add this distribution to `numpy.random`. At this point in time, we are trying to keep the number of distributions that we add to a minimum.

The Rademacher distribution is easily produced from the methods already available, and if one wanted to squeeze the last bit of performance out, one can now write a Cython function to do so in one's own package.

**Comment by r0cketr1kky** [comment]
Cool Thanks a lot @rkern
