### ISSUE TITLE
Please show the full output array in doc examples

### ISSUE THREAD

**Issue by jontwo** [numpy/numpy#15496]
The doc page for [numpy.unique](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html) shows a truncated array in the examples, which isn't particularly helpful.

```
>>> a = np.array([1, 2, 6, 4, 2, 3, 2])
>>> u, indices = np.unique(a, return_inverse=True)
>>> u
array([1, 2, 3, 4, 6])
>>> indices
array([0, 1, 4, ..., 1, 2, 1])
>>> u[indices]
array([1, 2, 6, ..., 2, 3, 2])
```

For such a small array, it wouldn't be so bad if you showed the whole thing.

**Comment by seberg** [comment]
Makeing sure it is printed fully (by changing the doc or just shortening the array slightly more) seems reasonably. Do you want to open a PR?

**Comment by jontwo** [comment]
Done #15510
