### ISSUE TITLE
Object array of arrays not freeing memory properly

### ISSUE THREAD

**Issue by pkomiske** [numpy/numpy#15498]
I have a numpy object array that holds differently sized numpy arrays. When I delete the object array, the memory corresponding to the element arrays is sometimes not freed. Running on macOS 10.15.2 (with python 3.7.6 and numpy 1.18.1) seems to free the memory properly while Ubuntu 19.10 (python 3.7.5, numpy 1.18.1) does not.

### Reproducing code example:

Running the following minimal snippet in a jupyter notebook allows me to examine the memory consumed by python using a process monitor:

```python
import numpy as np

x = np.zeros(100000, dtype='O')
for i in range(len(x)):
    x[i] = np.random.rand(np.random.randint(25, 125), 50)
```

This causes ~2.9 GB to be allocated. Now calling `del x` results in this 2.9 GB being released on macOS but not on Ubuntu. Running an explicit garbage collection, `gc.collect()`, also does not seem to help. This behavior eventually causes my program to consume all memory on my Ubuntu server, rendering it useless.

**Comment by seberg** [comment]
This should only be the behaviour of the operating system about how memory is reclaimed (i.e. the memory is free'd but it still belongs belongs/is counted towards your program). If you run the same code again, you should notice that the memory does not *keep* increasing.

If you try that and find that it keeps increasing, there could be a memory leak here, so please comment/open another issue!
