### ISSUE TITLE
multinomial accepts multi-dimensional arrays but returns unexpected counts or raises ValueError

### ISSUE THREAD

**Issue by pvanmulbregt** [numpy/numpy#15492]
https://github.com/scipy/scipy/issues/11422 noticed that `scipy.stats.multinomial(n,pvals).rvs()` is not vectorized. 
`scipy.stats.multinomial(n,pvals).rvs` calls `rng.multinomial(n, pvals)` for some Generator rng, (such as `rng == np.random.default_rng`)

`rng.multinomial(n, pvals)` accepts multidimensional arrays for `pvals` but then partially treats `pvals` as a collection of one-dimensional arrays, and partially as a 1-d array.
When passed an array of shape `(m,p)`, `multinomial` decides that there are  `m` (not `p`) possible outcomes in the experiment.  It then takes the first `(m-1)` elements of the multi-dimensional array and uses those as the first `(m-1)` probabilities. The final probability is implied, and is `1-sum(first m-1 probabilities)`.  This selection of probabilities may cross rows.
[`rng.multinomial` also has an optional `size` keyword.  That doesn't impact this issue.]

I.e. It appears that it is effectively doing the following for an array  of shape `(m, p)`:
```
probabilities = pvals.flatten()[:m]  # May cross rows, or stop before end of first row
if np.sum(probabilities[:-1]) > 1: raise ValueError(...)
probabilities[-1] = 1 - np.sum(probabilities[:-1])
# Generate a single length m array of counts using probabilities
#  (but user expects m arrays of length p)
...
```

I.e. When passed a multi-dimensional array, `rng.multinomial` will either: a) raise an Exception;  or b) will return a 1-d array of ints to the user, rather than a multi-dimensional array.

Is `multinomial` expected to respect multi-dimensional arrays?
If not, should it immediately raise a ValueError if `pvals` is not 1-d?

### Reproducing code example:

```python
import numpy as np
rng = np.random.default_rng()
rng.multinomial(20, np.array([[0,1], [1,0], [0,1]]))  
# produces single 3-element array([ 0, 20,  0]), but user expecting 3 2-element arrays

rng.multinomial(20, np.array([[0,1], [1,0], [0,1], [0,1]]))    
# User expecting 4 2-element arrays, gets an Exception.
```
The error occurs because it treated the (4,2) array as an array of length 4, and used 2 values from row 0, and 1 values from row 1. It summed the first 3 elements of [0, 1, 1, 0, 0, 1, 0, 1] to get 2.0 which is bigger than 1, so raised an Exception.

### Error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-103-63e116799aea> in <module>
----> 1 rng.multinomial(20, np.array([[0,1], [1,0], [0,1], [0,1]]))

generator.pyx in numpy.random.generator.Generator.multinomial()

ValueError: sum(pvals[:-1]) > 1.0
```

### Numpy/Python version information:
```
1.17.3 3.8.0 (default, Nov  6 2019, 15:49:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by seberg** [comment]
Ok, so the current way `pvals` is coerced, is by really just using `len(pvals)` and then creating a C-contiguous arrays (and *assuming* it will be 1D).

Ideally the result should probably broadcast `p`. I am not sure how simple this is, so adding a `ValueError` if the array is not 1-D would seem like a reasonable first and quick step to at least not return an incorrect result.

@pvanmulbregt do you happen to know if there is a regression compared to NumPy 1.16?

**Comment by pvanmulbregt** [comment]
@seberg I don't know whether it's a regression or has always been the case.

**Comment by rossbar** [comment]
@seberg the behavior is indeed different in v1.16:

```python
>>> import numpy as np
>>> print(np.__version__)
1.16.0
>>> np.random.multinomial(20, np.array([[0,1], [1,0], [0,1]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4624, in mtrand.RandomState.multinomial
ValueError: object too deep for desired array
```
```python

>>> import numpy as np
>>> print(np.__version__)
1.18.0
>>> rng = np.random.default_rng()
>>> rng.multinomial(20, np.array([[0,1], [1,0], [0,1]]))
array([ 0, 20,  0])
```

**Comment by panpiort8** [comment]
I can take that issue

**Comment by seberg** [comment]
Cool, sure, go ahead, just open a PR and reference the issue! Let me know if you have any difficulties.

**Comment by panpiort8** [comment]
As I understand, the problem is that `numpy.random.Generator.multinomial` doesn't throw `ValueError` when multidimensional `pval` is passed, so isn't defensive enough? 

But we are wondering about solution that accepts multidimensional `pval` and does something sensible?
> Ideally the result should probably broadcast `p`.

To my mind accepting multidimensional `pval` will be kind of inelegant, because `multinomial` is supposed to draw samples from single multinomial distribution and there no such thing (or am I wrong?) as 'generalized' multidimensional multinomial distribution. And even if we let 'multinomial' to generate data from different multionomial distributions at once, there are going to be problem with integrating it with `n` (number of experiments). What does a single experiment mean? Draw samples for just single distribution? Or draw samples for all distributions? How to group results? By 'id' of distribution or 'id' of experiment? Do we allow some distributions to have more parameters than others? Actually why not? I thinks whatever we do - it'll make things overcomplicated.

Of course I may be wrong and I'll glad to see what you think :)

**Comment by panpiort8** [comment]
As I understand, the problem is that `numpy.random.Generator.multinomial` doesn't throw `ValueError` when multidimensional `pval` is passed, so isn't defensive enough? 

But we are wondering about solution that accepts multidimensional `pval` and does something sensible?
> Ideally the result should probably broadcast `p`.

**Comment by seberg** [comment]
Yes, the ideal result is that when `pval` has more dimensions, these dimensions are added to the output dimensions (if it fits with the other inputs). But, it would be OK to just go to an error for now, since that is the old behaviour.
