### ISSUE TITLE
Distributed testing with xdist similar to SciPy

### ISSUE THREAD

**Issue by sethtroisi** [numpy/numpy#15501]
While contributing to SciPy I noticed their `runtests.py` supports distributed/multithreading during both building and **testing**. This seems to be a relatively simple change https://github.com/scipy/scipy/pull/10172.

Is this something numpy has already tried? would like to be added?

I'm happy to try and code it up if it's a good idea to try.

**Comment by mattip** [comment]
I kind of like it that the build and the tests are separate. Why should they be forced to be tied? In general, I think we should not copy all the pytest options into runtests, rather allow developers to specify them after `--` instead:
```
python runtests.py -j2 -- -n 4
```

**Comment by sethtroisi** [comment]
I'm hearing you're for adding support for some/all pytest flags and would prefer specifying them in a different way (after `--` ) than scipy does. I'll try to code that up and see what happens.

**Comment by seberg** [comment]
@sethtroisi everything after `--` is already forwarded to pytest. So there is nothing much that needs to be done. My gut feeling is that unlike SciPy where tests run very long, NumPy tests run much faster, and often I only run a single test file anyway. But, I am not opposed either if anyone feels it would help speed up their workflow.

**Comment by sethtroisi** [comment]
Ahh, I was confused, I tried with -- and it didn't work but it was because that computer didn't have pytest-xdist installed. I'm closing this as this seems to be handled. The tests do take 1-2 minutes so maybe it would be worth a note in the documentation somewhere (I'll take a look) but no code changes are needed.
