### ISSUE TITLE
API: _get_ndarray_c_version imported but not added to __all__

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#15518]
`_get_ndarray_c_version` is [imported](https://github.com/numpy/numpy/blob/v1.18.1/numpy/core/multiarray.py#L20) from `_multiarray_umath` but not added to `__all__`. I am not sure what would be more correct: remove it from the import or add it to `__all__`

**Comment by rgommers** [comment]
Can you explain the question a little more? `__all__` is for public functions, and this one starts with an underscore.

**Comment by eric-wieser** [comment]
We can't delete it without breaking code that does `np.core.multiarray._get_ndarray_c_version`, which worked in 1.12.1 (before the merge with umath).

When `multiarray` was a C module, there was no `__all__`, meaning only underscore-free names were imported with `*` - so I don't think it needs to be in `__all__` either.

**Comment by eric-wieser** [comment]
More context in https://github.com/numpy/numpy/pull/13876/commits/ae65a534645ca26992c208275c7a9554450edf73

**Comment by mwtoews** [comment]
I'd advise either adding the function to `numpy/core/multiarray.py`'s `__all__` or marking this import with `# noqa: F401`
