### ISSUE TITLE
Missing link to NumPy 1.18 documentation

### ISSUE THREAD

**Issue by eda-ricercatore** [numpy/numpy#15514]
See https://docs.scipy.org/doc/numpy/reference/ for the NumPy 1.17 documentation. https://numpy.org/devdocs/ refers to NumPy 1.19 documentation. 

From https://numpy.org/doc/, there is no mention of NumPy 1.18 documentation. 

![no-numpy-1-18-documentation](https://user-images.githubusercontent.com/18295279/73811247-9a753980-479e-11ea-94d4-152ac8236330.jpg)
![missing-numpy-1-19-documentation](https://user-images.githubusercontent.com/18295279/73811262-a4973800-479e-11ea-81f4-e3d57d6702cd.jpg)

**Comment by rossbar** [comment]
Good catch @eda-ricercatore , this is related to #15155

**Comment by mattip** [comment]
Closing as a duplicate. It would be good to solve this soon.
