### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by uwmdm** [numpy/numpy#15512]
PS C:\Users\mmeena\Wi2020\metadatamap> python app.py
Traceback (most recent call last):
  File "C:\Users\mmeena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\mmeena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\mmeena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import numpy as np
  File "C:\Users\mmeena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\mmeena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\mmeena\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

Just thought I'd open an issue:

I did try installing and reinstalling numpy (several times - directly from pip and by using .whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy)

I am using Python 3.7 from the path listed above - there are no directories in my PATH variable that is directing to any other python version. Python 3.7 was installed via Microsoft store.

I do have a Python 3.6 version installed in C:\ drive though. (Python 3.7 is for my user account)

I use a Windows 64-bit operating system and x64 processor.

**Comment by charris** [comment]
Looks like #15431, which is an MKL2020 bug.

**Comment by uwmdm** [comment]
Yes I am using pip to install the wheel. Because of #15431 I tried using numpy-mkl versions 1.17 and 1.16 but the error persists.

**Comment by mattip** [comment]
Does the PATH have another python installation on it?

**Comment by uwmdm** [comment]
There is a Python 3.6 version installed on the C:\
and I am using 3.7 installed for my own user account... python command on the terminal opens up Python 3.7 but let me check the path variables once again..

**Comment by uwmdm** [comment]
There are no Path variables pointing to Python 3.6

**Comment by uwmdm** [comment]
This is my Path Variable

PS C:\Users\mmeena> $ENV:Path                                                                                                                                                                                                       C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Boost\lib;C:\cmake-3.16.3-win64-x64\bin;C:\cygwin64\bin;C:\Program Files\Git\cmd;C:\vcpkg;C:\Users\mmeena\AppData\Local\Microsoft\WindowsApps;C:\Users\mmeena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts;C:\Users\mmeena\Documents\cmake-3.16.3-win64-x64\bin; 



And Python 3.6 is present in - C:\ProgramFiles\Python36

Even when I download numpy 1.17.5 mkl whl for python 37 windows 64 - I get Numpy Import Error : Original error was: DLL load failed: The specified module could not be found.

**Comment by mattip** [comment]
What is printed out when you start python? For instance, mine prints
```
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by uwmdm** [comment]
![image](https://user-images.githubusercontent.com/60676880/74295083-c2abed80-4cf4-11ea-8ec1-0c71c6442862.png)

**Comment by mattip** [comment]
Do you have PYTHONHOME or PYTHONPATH set?
If there is no sensitive information in it could you paste your PATH variable (as text, not as an image)?

**Comment by uwmdm** [comment]
PYTHONHOME or PYTHONPATH is not set in my system variables


Environment Variables 

For my user account

PATH 
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
C:\Users\mmeena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts
C:\Users\mmeena\Documents\cmake-3.16.3-win64-x64\bin


For the system

PATH 
%SystemRoot%\system32
%SystemRoot%
%SystemRoot%\System32\Wbem
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
%SYSTEMROOT%\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Boost\lib
C:\cmake-3.16.3-win64-x64\bin
C:\cygwin64\bin
C:\Program Files\Git\cmd
C:\vcpkg

**Comment by rossbar** [comment]
I'm going to close this due to inactivity. If the problem persists, first check out this [troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html) to see if it helps resolve the issue. If not, please open a new issue with current information about the system.
