### ISSUE TITLE
Issue running numpy via matplotlib on WSL 

### ISSUE THREAD

**Issue by toonarmycaptain** [numpy/numpy#15520]
Numpy appears to be missing some c-extension files? I'm trying to run under python3//python3.8 in WSL Ubuntu. It's being called I believe by pytest via matplotlib, as it's not a dependency I'm using or had installed directly, although I've tried doing so and upgrading and installing `apt-get install python3-numpy.` as a workaround. 

A curious element is that, conformed by `python -c 'import numpy; print(numpy.version.version)` returns 1.18.1 for `python3.8`, and an error on `python` and `python3`, whereas the error references numpy 1.17.3. I freshly installed WSL/Ubuntu and python several times and in several combinations (eg installing `python-numpy` before installing my project's matplotlib dependency) to make sure it wasn't an issue of cluttered/confused python/site packages installations. I've tried both latest and a couple of older versions of pip and setuptools, and I've tried those and numpy, as several issue resolutions suggest. The error persists. 

I'll note that it seems numpy seems to actually run ok, as least in the probably minimal manner in which matplotlib uses it in my use case, as matplotlib is able to create and save a chart.

### Reproducing code example:
```
toonarmycaptain@DESKTOP-05F10IK:/mnt/c/Users/david/OneDrive/Programming/PycharmProjects/dionysus$ python3.8 -m pytest
================================================= test session starts ==================================================
platform linux -- Python 3.8.1, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/c/Users/david/OneDrive/Programming/PycharmProjects/dionysus, inifile: pytest.ini
plugins: cov-2.8.1, mypy-0.4.2
collected 0 items / 1 error

======================================================== ERRORS ========================================================
____________________________________________ ERROR collecting test session _____________________________________________
/home/toonarmycaptain/.local/lib/python3.8/site-packages/_pytest/config/__init__.py:459: in _importconftest
    return self._conftestpath2mod[key]
E   KeyError: PosixPath('/mnt/c/Users/david/OneDrive/Programming/PycharmProjects/dionysus/dionysus_env/Lib/site-packages/numpy/conftest.py')

During handling of the above exception, another exception occurred:
dionysus_env/Lib/site-packages/numpy/core/__init__.py:17: in <module>
    from . import multiarray
dionysus_env/Lib/site-packages/numpy/core/multiarray.py:14: in <module>
    from . import overrides
dionysus_env/Lib/site-packages/numpy/core/overrides.py:7: in <module>
    from numpy.core._multiarray_umath import (
E   ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:
/home/toonarmycaptain/.local/lib/python3.8/site-packages/_pytest/config/__init__.py:465: in _importconftest
    mod = conftestpath.pyimport()
/home/toonarmycaptain/.local/lib/python3.8/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
dionysus_env/Lib/site-packages/numpy/__init__.py:142: in <module>
    from . import core
dionysus_env/Lib/site-packages/numpy/core/__init__.py:47: in <module>
    raise ImportError(msg)
E   ImportError:
E
E   IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
E
E   Importing the numpy c-extensions failed.
E   - Try uninstalling and reinstalling numpy.
E   - If you have already done that, then:
E     1. Check that you expected to use Python3.8 from "/usr/bin/python3.8",
E        and that you have no directories in your PATH or PYTHONPATH that can
E        interfere with the Python and numpy version "1.17.3" you're trying to use.
E     2. If (1) looks fine, you can open a new issue at
E        https://github.com/numpy/numpy/issues.  Please include details on:
E        - how you installed Python
E        - how you installed numpy
E        - your operating system
E        - whether or not you have multiple versions of Python installed
E        - if you built from source, your compiler versions and ideally a build log
E
E   - If you're working with a numpy git repository, try `git clean -xdf`
E     (removes all files not under version control) and rebuild numpy.
E
E   Note: this error has many possible causes, so please don't comment on
E   an existing issue about this - open a new one instead.
E
E   Original error was: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:
/home/toonarmycaptain/.local/lib/python3.8/site-packages/py/_path/common.py:383: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
/home/toonarmycaptain/.local/lib/python3.8/site-packages/py/_path/common.py:435: in gen
    for p in self.gen(subdir):
/home/toonarmycaptain/.local/lib/python3.8/site-packages/py/_path/common.py:435: in gen
    for p in self.gen(subdir):
/home/toonarmycaptain/.local/lib/python3.8/site-packages/py/_path/common.py:435: in gen
    for p in self.gen(subdir):
/home/toonarmycaptain/.local/lib/python3.8/site-packages/py/_path/common.py:424: in gen
    dirs = self.optsort([p for p in entries
/home/toonarmycaptain/.local/lib/python3.8/site-packages/py/_path/common.py:425: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
/home/toonarmycaptain/.local/lib/python3.8/site-packages/_pytest/main.py:626: in _recurse
    ihook = self.gethookproxy(dirpath)
/home/toonarmycaptain/.local/lib/python3.8/site-packages/_pytest/main.py:445: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
/home/toonarmycaptain/.local/lib/python3.8/site-packages/_pytest/config/__init__.py:437: in _getconftestmodules
    mod = self._importconftest(conftestpath)
/home/toonarmycaptain/.local/lib/python3.8/site-packages/_pytest/config/__init__.py:473: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: (local('/mnt/c/Users/david/OneDrive/Programming/PycharmProjects/dionysus/dionysus_env/Lib/site-packages/numpy/conftest.py'), (<class 'ImportError'>, ImportError('\n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy c-extensions failed.\n- Try uninstalling and reinstalling numpy.\n- If you have already done that, then:\n  1. Check that you expected to use Python3.8 from "/usr/bin/python3.8",\n     and that you have no directories in your PATH or PYTHONPATH that can\n     interfere with the Python and numpy version "1.17.3" you\'re trying to use.\n  2. If (1) looks fine, you can open a new issue at\n     https://github.com/numpy/numpy/issues.  Please include details on:\n     - how you installed Python\n     - how you installed numpy\n     - your operating system\n     - whether or not you have multiple versions of Python installed\n     - if you built from source, your compiler versions and ideally a build log\n\n- If you\'re working with a numpy git repository, try `git clean -xdf`\n  (removes all files not under version control) and rebuild numpy.\n\nNote: this error has many possible causes, so please don\'t comment on\nan existing issue about this - open a new one instead.\n\nOriginal error was: No module named \'numpy.core._multiarray_umath\'\n'), <traceback object at 0x7ff7c2a76900>))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================== 1 error in 3.10s ===================================================
```

### Numpy/Python version information:
```
$python3.8 --version
Python 3.8.1
$python3.8 -c 'import numpy; print(numpy.version.version)'
1.18.1
$python3.8 -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.18.1 3.8.1 (default, Dec 31 2019, 18:42:42)
[GCC 7.4.0]
```
Also to not this is Ubuntu 18.04 on Windows10 WSL downloaded in the last couple of days.

**Comment by toonarmycaptain** [comment]
Probable cause, it looks like the Windows env inside my project folder (placed there by Pycharm) is causing the problem. It appears that pytest is using the WSL install of python for 'everything' except numpy - a test for matplotlib.__file__ shows it to be in `'/usr/local/lib/python3.8/dist-packages/matplotlib/__init__.py' whereas the numpy that matplotlib is using is being found in the Windows env...?
When run from the interpreter, however, I get:
```
>>> import numpy, matplotlib
>>> matplotlib.__file__
'/usr/local/lib/python3.8/dist-packages/matplotlib/__init__.py'
>>> numpy.__file__
'/home/toonarmycaptain/.local/lib/python3.8/site-packages/numpy/__init__.py'
```

So maybe this an issue with matplotlib, python's module discovery, or WSL?

**Comment by rossbar** [comment]
Based on your first description, it seems like you have several different Python versions installed. You can test this with `which python3.8` and `which python3`. Note that relying on your distribution's package manager (i.e. `apt`) will install packages for the system Python (likely the result of `which python3`, unless you've changed aliases on your system). Things can get pretty complicated if you are relying on multiple different package management systems and have several versions of python installed.

**Comment by toonarmycaptain** [comment]
I've only used apt-get to install python3.8/pip from deadsnakes, and from there used `python3.8 -m pip install -r requirements.txt -r requirements_dev.txt` to install project app and testing dependencies, then run tests using `python3.8 -m pytest` in the project directory. 

I've since discovered that if I run `python3.8 -m pytest ./test_suite` it doesn't have the issue, I suppose because it doesn't look through the `dionysus_env` directory which has the Win10 env installed and managed by Pycharm? So this might be a pytest issue. Or a matplotlib one, although import `numpy as np` should only be looking in the python env rather than in the current directory/children for imports.

**Comment by rossbar** [comment]
I only mentioned the environment confusion based on your first comment that you used `apt-get` to install `python-numpy`. To me, that explains some of your original issue, i.e. why you get v1.18 when you do `python3.8 -c import numpy; print(numpy.__version__)` but different results when using `python` or `python3`.

Your above comment suggests that everything runs as expected (minus tests) when everything is installed via python3.8 and pip. Without additional info it's difficult to say what's causing the behavior with `pytest`. Based on the context, I would bet that you are correct and that it is some sort of configuration/env specification issue with the project that you are testing.

I am going to close this for now as it seems this is likely related to the project you are using rather than an issue with `numpy`, `matplotlib`, `pytest`, etc. If you disagree or have more specific information that points to this being a `numpy` problem, feel free to re-open. I hope this was helpful - glad to hear it sounds like you are (at least close to) having it all figured out.

**Comment by toonarmycaptain** [comment]
Oh, no, I just tried `python-numpy` as I'd seen that as a solution to some issues people have had, it didn't solve the issue, and I made a fresh install of Ubuntu and repeated the install as I described, and kept seeing the error.
