### ISSUE TITLE
Numpy wont import in Python 3 in anaconda env

### ISSUE THREAD

**Issue by AiliMaki** [numpy/numpy#15523]
I am using anaconda2 to manage my environments. I am setting up an enviornment to run a colleague's code.
I had to use pip to install the version of PyQT5 he has.
I tried installing numpy with conda, and with pip, but to no avail either way it refuses to import.

### Reproducing code example:

from pycharm python console using this environment:
import numpy

```python
import numpy as np

```
### Error message:
C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py:20: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  module = self._system_import(name, *args, **kwargs)
Traceback (most recent call last):
  File "C:\Users\bloomqui\Anaconda2\envs\tubeinfo\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\bloomqui\Anaconda2\envs\tubeinfo\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\bloomqui\Anaconda2\envs\tubeinfo\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\bloomqui\Anaconda2\envs\tubeinfo\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\bloomqui\Anaconda2\envs\tubeinfo\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\bloomqui\Anaconda2\envs\tubeinfo\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.
Original error was: DLL load failed: The specified module could not be found.

### Numpy/Python version information:

Base environment:
anaconda 2019.10 (Fresh re-install)
conda 4.8.2
Environment for code:
Python 3.7.6
numpy 1.18.8 (currently installed via pip)
PyQt5 5.14.1 (installed via pip)

**Comment by charris** [comment]
ISTR PyQT5 causing problems. I also assume NumPy is 1.18.1?

**Comment by mattip** [comment]
Before you installed PyQT5 it all worked?

**Comment by AiliMaki** [comment]
Sorry, yes NumPy is 1.18.1. Also, note I am running on Windows 10.  I don't know if numpy worked before I installed PyQT5.  In fact I think i installed PyQT5 first. I was putting in the libraries needed to run the code - waiting for PyCharm to be happy that everything was there....

**Comment by AiliMaki** [comment]
I just made a brand new environment with Python 3.7.6 and installed numpy 1.18.1 (using conda). Numpy still fails to import.

**Comment by mattip** [comment]
Did you activate the conda environment by running `path\to\anaconda\Scripts\activate`?

**Comment by AiliMaki** [comment]
I am using PyCharm.  I have the project pointing to the python.exe file in the correct anaconda environment directory, which has worked fine for other anaconda environments and Pycharm.

**Comment by AiliMaki** [comment]
I rolled back the conda install of  numpy and did a pip install, and now I can import numpy. I then did a pip install of pyQT5. Things till seem happy. I will test that import numpy still works after each package I need gets added.

**Comment by AiliMaki** [comment]
Things seem to work now. Still puzzled why conda install of numpy resulted in broken numpy that would not import.

**Comment by robsss** [comment]
it's timeconsuming. I fix the problem by using anaconda inherited editor jupyterlab. 
if someone has the same question, hope it will be useful.

**Comment by robsss** [comment]
the right way to open it is anaconda navigator-->launch jupyterlab

**Comment by Fliens** [comment]
> it's timeconsuming. I fix the problem by using anaconda inherited editor jupyterlab.
> if someone has the same question, hope it will be useful.

So you programmed in jupyterlab to get around the numpy error?

**Comment by miko-code** [comment]
I have the same issue and using jupyterlab dose solve it

**Comment by seberg** [comment]
If you are using pycharm, check the pycharm help forum please: https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html Otherwise, ensure that your conda environment is activated: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment

If nothing works, you might think about opening a conda issue, there used to be some problems e.g. with PyQT5 interaction. I do not know whether that is still a thing. If you find some other solution, please post it here, so others might find it.

**Comment by kayvij** [comment]
I tried everything mentioned here and nothing worked. The following worked:

1. Uninstall Conda
2. Install Conda again **(But make sure to select the "Set Anaconda Path" and "Register Python" options at the end of the installation)**

**Comment by gptshubham595** [comment]
NOT WORKING, any of the solution!

**Comment by tghunt** [comment]
I recently removed an older anaconda 3.7 install and re-installed the latest.  I experienced this issue with the new install and found that one needs to make sure the correct PYTHON_PATH is set for the environment you are working in.  While working in PyCharm I simply add PYTHON_PATH to the 'Run/Debug Configurations'.  Depending on you setup, you could put it elsewhere to make it the default for your system.

**Comment by szakharov7723** [comment]
If none of the previous solutions work you may also try
`pip install --upgrade pip`
`easy_install pip` (soon will be depreciated)
`pip uninstall numpy`
`pip install numpy`

Specifically in my case both numpy and python were up to date
but error was exactly (or nearly) like in issue.

**Comment by Breno-BR** [comment]
This is what solved for me...

Installed this version of Qt Creator.

Qt Creator 4.13.1
Based on Qt 5.15.1 (MSVC 2019, 32 bit)
Built on Sep 16 2020 01:27:57

I created a venv with Python 3.8.2 and the following libraries:
[qt_requirements.txt](https://github.com/numpy/numpy/files/6325913/qt_requirements.txt)

And I also installed mkl like this:

conda install -c conda-forge mkl-service

And you also need to configure Qt in Tools/Options like this:

![QT_Env](https://user-images.githubusercontent.com/62098988/115041420-da5aa500-9ea8-11eb-914e-4ca7ec1d3b72.png)

**Comment by wkitlasten** [comment]
Similar issue in VS Code. The notebook runs fine when activating jupyter notebook from the cmd line (same environment).

I solved my issue by changing the default terminal from PowerShell to cmd.

0) ctrl+`, or View>Terminal
1) terminal dropdown window Set Default Profile
2) select cmd

![image](https://user-images.githubusercontent.com/14982084/124670032-825f9780-df07-11eb-8577-182318bcf952.png)
