### ISSUE TITLE
numpy.delete is not working

### ISSUE THREAD

**Issue by rampallishyam** [numpy/numpy#15529]
### Reproducing code example:

```python
import numpy as np

x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)

np.delete(x, 1, axis=1)
print(x)

<!-- Output from 'import sys, numpy; print(numpy.__version__, sys.version)' -->
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

**Comment by eric-wieser** [comment]
From the docs (emphasis mine), this is by design:
> **Return a new array** with sub-arrays along an axis deleted.

**Comment by rampallishyam** [comment]
Thanks, it works now. Feeling much better after having struggles for hours.
Can you tell the reason why is it so? Just curious.

**Comment by eric-wieser** [comment]
The size of numpy arrays is immutable by design, because otherwise array views would not be safe.

Given these, it's not possible for `delete` to operate in place. `append` is the same.

If you still find this non-obvious, I'd welcome a PR that improves the documentation to make it more obvious.

**Comment by rampallishyam** [comment]
I think it is clear. A numpy array is like a tuple. But in real world application, I do not know yet why this would be useful.

**Comment by seberg** [comment]
@rampallishyam it is not useful by itself, it is **necessary** to allow for *view* semantics, and view semantics are one of the most central concepts in numpy. Thus, a NumPy array is *not* like a tuple, since its content is mutable (can change), just not its size.
