### ISSUE TITLE
DOC: Listing of all numpy functions that support __array_function__

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#15544]
Is there a listing of all numpy functions one would need to wrap to fully support all of the API that is wrappable via `__array_function__`? This seems like something that could be generated by introspection on the numpy source code and included in the numpy documentation, as far as I can see it doesn't exist.

Having such a document to look at would make it much easier for downstream projects to add `__array_function__` support. See https://github.com/yt-project/unyt/issues/139 for more details of my usage.

**Comment by shoyer** [comment]
This should probably end up in the docs eventually, but in the meantime here's the current list:
<details>
numpy.alen
numpy.all
numpy.allclose
numpy.alltrue
numpy.amax
numpy.amin
numpy.angle
numpy.any
numpy.append
numpy.apply_along_axis
numpy.apply_over_axes
numpy.argmax
numpy.argmin
numpy.argpartition
numpy.argsort
numpy.argwhere
numpy.around
numpy.array2string
numpy.array_equal
numpy.array_equiv
numpy.array_repr
numpy.array_split
numpy.array_str
numpy.asfarray
numpy.asscalar
numpy.atleast_1d
numpy.atleast_2d
numpy.atleast_3d
numpy.average
numpy.bincount
numpy.block
numpy.broadcast_arrays
numpy.broadcast_to
numpy.busday_count
numpy.busday_offset
numpy.can_cast
numpy.char.add
numpy.char.capitalize
numpy.char.center
numpy.char.count
numpy.char.decode
numpy.char.encode
numpy.char.endswith
numpy.char.equal
numpy.char.expandtabs
numpy.char.find
numpy.char.greater
numpy.char.greater_equal
numpy.char.index
numpy.char.isalnum
numpy.char.isalpha
numpy.char.isdecimal
numpy.char.isdigit
numpy.char.islower
numpy.char.isnumeric
numpy.char.isspace
numpy.char.istitle
numpy.char.isupper
numpy.char.join
numpy.char.less
numpy.char.less_equal
numpy.char.ljust
numpy.char.lower
numpy.char.lstrip
numpy.char.mod
numpy.char.multiply
numpy.char.not_equal
numpy.char.partition
numpy.char.replace
numpy.char.rfind
numpy.char.rindex
numpy.char.rjust
numpy.char.rpartition
numpy.char.rsplit
numpy.char.rstrip
numpy.char.split
numpy.char.splitlines
numpy.char.startswith
numpy.char.str_len
numpy.char.strip
numpy.char.swapcase
numpy.char.title
numpy.char.translate
numpy.char.upper
numpy.char.zfill
numpy.choose
numpy.clip
numpy.column_stack
numpy.common_type
numpy.compress
numpy.concatenate
numpy.convolve
numpy.copy
numpy.copyto
numpy.corrcoef
numpy.correlate
numpy.count_nonzero
numpy.cov
numpy.cross
numpy.cumprod
numpy.cumproduct
numpy.cumsum
numpy.datetime_as_string
numpy.delete
numpy.diag
numpy.diag_indices_from
numpy.diagflat
numpy.diagonal
numpy.diff
numpy.digitize
numpy.dot
numpy.dsplit
numpy.dstack
numpy.ediff1d
numpy.einsum
numpy.einsum_path
numpy.empty_like
numpy.expand_dims
numpy.extract
numpy.fft.fft
numpy.fft.fft2
numpy.fft.fftn
numpy.fft.fftshift
numpy.fft.hfft
numpy.fft.ifft
numpy.fft.ifft2
numpy.fft.ifftn
numpy.fft.ifftshift
numpy.fft.ihfft
numpy.fft.irfft
numpy.fft.irfft2
numpy.fft.irfftn
numpy.fft.rfft
numpy.fft.rfft2
numpy.fft.rfftn
numpy.fill_diagonal
numpy.fix
numpy.flatnonzero
numpy.flip
numpy.fliplr
numpy.flipud
numpy.full_like
numpy.fv
numpy.geomspace
numpy.gradient
numpy.histogram
numpy.histogram2d
numpy.histogram_bin_edges
numpy.histogramdd
numpy.hsplit
numpy.hstack
numpy.i0
numpy.imag
numpy.in1d
numpy.inner
numpy.insert
numpy.interp
numpy.intersect1d
numpy.ipmt
numpy.irr
numpy.is_busday
numpy.isclose
numpy.iscomplex
numpy.iscomplexobj
numpy.isin
numpy.isneginf
numpy.isposinf
numpy.isreal
numpy.isrealobj
numpy.ix_
numpy.kron
numpy.lexsort
numpy.lib.scimath.arccos
numpy.lib.scimath.arcsin
numpy.lib.scimath.arctanh
numpy.lib.scimath.log
numpy.lib.scimath.log10
numpy.lib.scimath.log2
numpy.lib.scimath.logn
numpy.lib.scimath.power
numpy.lib.scimath.sqrt
numpy.linalg.cholesky
numpy.linalg.cond
numpy.linalg.det
numpy.linalg.eig
numpy.linalg.eigh
numpy.linalg.eigvals
numpy.linalg.eigvalsh
numpy.linalg.inv
numpy.linalg.lstsq
numpy.linalg.matrix_power
numpy.linalg.matrix_rank
numpy.linalg.multi_dot
numpy.linalg.norm
numpy.linalg.pinv
numpy.linalg.qr
numpy.linalg.slogdet
numpy.linalg.solve
numpy.linalg.svd
numpy.linalg.tensorinv
numpy.linalg.tensorsolve
numpy.linspace
numpy.logspace
numpy.may_share_memory
numpy.mean
numpy.median
numpy.meshgrid
numpy.min_scalar_type
numpy.mirr
numpy.moveaxis
numpy.msort
numpy.nan_to_num
numpy.nanargmax
numpy.nanargmin
numpy.nancumprod
numpy.nancumsum
numpy.nanmax
numpy.nanmean
numpy.nanmedian
numpy.nanmin
numpy.nanpercentile
numpy.nanprod
numpy.nanquantile
numpy.nanstd
numpy.nansum
numpy.nanvar
numpy.ndim
numpy.nonzero
numpy.nper
numpy.npv
numpy.ones_like
numpy.outer
numpy.packbits
numpy.pad
numpy.partition
numpy.percentile
numpy.piecewise
numpy.place
numpy.pmt
numpy.poly
numpy.polyadd
numpy.polyder
numpy.polydiv
numpy.polyfit
numpy.polyint
numpy.polymul
numpy.polysub
numpy.polyval
numpy.ppmt
numpy.prod
numpy.product
numpy.ptp
numpy.put
numpy.put_along_axis
numpy.putmask
numpy.pv
numpy.quantile
numpy.rate
numpy.ravel
numpy.ravel_multi_index
numpy.real
numpy.real_if_close
numpy.repeat
numpy.reshape
numpy.resize
numpy.result_type
numpy.roll
numpy.rollaxis
numpy.roots
numpy.rot90
numpy.round_
numpy.save
numpy.savetxt
numpy.savez
numpy.savez_compressed
numpy.searchsorted
numpy.select
numpy.setdiff1d
numpy.setxor1d
numpy.shape
numpy.shares_memory
numpy.sinc
numpy.size
numpy.sometrue
numpy.sort
numpy.sort_complex
numpy.split
numpy.squeeze
numpy.stack
numpy.std
numpy.sum
numpy.swapaxes
numpy.take
numpy.take_along_axis
numpy.tensordot
numpy.tile
numpy.trace
numpy.transpose
numpy.trapz
numpy.tril
numpy.tril_indices_from
numpy.trim_zeros
numpy.triu
numpy.triu_indices_from
numpy.union1d
numpy.unique
numpy.unpackbits
numpy.unravel_index
numpy.unwrap
numpy.vander
numpy.var
numpy.vdot
numpy.vsplit
numpy.vstack
numpy.where
numpy.zeros_like
</detail>

As is, I'm not sure how useful it is, but perhaps with some careful curation...

**Comment by mattip** [comment]
@shoyer how did you produce the list? Maybe we could add the incantation without the result to the documentation

**Comment by shoyer** [comment]
I hacked something directly into np.core.override to save every decorated
function into a list.

**Comment by rgommers** [comment]
I distinctly remember another issue about this, but can't find it anymore. I commented somewhere that it would be useful/nice to extend https://github.com/numpy/numpy/blob/master/numpy/tests/test_public_api.py to both do this and test for changes.

**Comment by mhvk** [comment]
A complete list would indeed be very helpful. Right now, in `astropy.units`, I create it myself so that I know if a new function appears: 
https://github.com/astropy/astropy/blob/25ac198cfe0040d34f139ae6d7417c3a3e12768c/astropy/units/tests/test_quantity_non_ufuncs.py#L22-L32

**Comment by alescrocaro** [comment]
Hello, I want to work on this issue. Could you please give me some tips to start?

**Comment by InessaPawson** [comment]
@ngoldbaum We discussed your request at today's triage meeting. The NumPy dev team would like to help downstream projects to add `__array_function__ `support. What would be the best format to share the list of these functions with your project?

**Comment by ngoldbaum** [comment]
In practice right now we have [a test](https://github.com/yt-project/unyt/blob/0c07fc899091787a34a26a01299b21c24052a479/unyt/tests/test_array_functions.py#L257) that finds all the callables in the `np`, `np.linalg`, and `np.fft` namespaces that have a `__wrapped__` attribute.

If e.g. `numpy.testing` has a public API I could call in my tests to get a list of all functions that support `__array_function__` and I no longer had to rely on numpy implementation details to build that list on my own that would be great. It would also be nice to ask fir a list of all the ufuncs that support `__array_ufunc__`.

**Comment by ngoldbaum** [comment]
I'm also happy to try implementing this if my above proposal is acceptable.

**Comment by InessaPawson** [comment]
@ngoldbaum, it would be great!
We are not quite sure what would be the best way to implement it. Since this could be helpful for other downstream projects, perhaps, let's ask for feedback from the mailing list subscribers.

**Comment by seberg** [comment]
Cool, the main question is where to put it and maybe how to expose.  I would be fine with just `np.core.overrides.<something>` and just document it as more or less public.  But maybe someon has a better idea.  Testing seems also OK, if we assume that is really the main purpose?
(I just don't think it belongs anywhere really user visible.)

**Comment by mhvk** [comment]
I like `np.testing.overrides`. I'd suggest having both implementation-independent functions that allow one to check whether a function can be overridden (say, `overrides.allows_array_ufunc_override`, `overrides.allow_array_function_override`), and exposed sets of all functions that allow it (say, `overrides.functions` and `overrides.ufuncs`).

One question is how to make this discoverable. I guess with the documentation of `__array_ufunc__` and `__array_function__` -- maybe even add it to the relevant NEPs?
