### ISSUE TITLE
Replace https://docs.scipy.org/doc/numpy/ with a redirect to the new docs

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15540]
This would probably help with SEO pointing to the new docs site.

As it is, a lot of links are now pointing at stale 1.17 docs, without the reader really being aware that they're looking in the wrong place.

I'm not sure exactly how `docs.scipy.org` is hosted, but one option might just be to add something like this to a `.htaccess`:
```
Redirect 301 /doc/numpy/ https://numpy.org/doc/1.17/
```

**Comment by rgommers** [comment]
> `Redirect 301 /doc/numpy/ https://numpy.org/doc/1.17/`

That's equally stale, I think you meant `doc/1.18/`?

Would be nice to have a `https://numpy.org/doc/latest/` to point to.

**Comment by rgommers** [comment]
I created the redirect. Thanks for the suggestion Eric.



> I'm not sure exactly how `docs.scipy.org` is hosted,

It's an AWS server with a few people having access to upload and change the directories that serve up scipy.org and docs.scipy.org

**Comment by rgommers** [comment]
We'd like to move away from that server to completely static hosting. Going to take a while ....

**Comment by eric-wieser** [comment]
> That's equally stale, I think you meant `doc/1.18/`

My point was that that way the version is the same, but I suppose that doesn't matter.

**Comment by rgommers** [comment]
Indeed, doesn't matter - that link is supposed to point to the latest stable release.

**Comment by eric-wieser** [comment]
> Would be nice to have a https://numpy.org/doc/latest/ to point to.

Is `numpy.org` served in a way that makes this easy (eg via a htaccess again?)

**Comment by rgommers** [comment]
It's just GitHub Pages.

**Comment by rgommers** [comment]
This gave problems, intersphinx doesn't like a redirect, still somewhat unclear why - see gh-15564.

Right now there's no way for people to update their intersphinx config, because there's no generic "latest stable" URL at https://numpy.org/doc/. We should add that before we re-enable the redirect.

**Comment by eric-wieser** [comment]
Good point about intersphinx needing a "latest" url.

**Comment by mattip** [comment]
There are some hints [here](https://superdevresources.com/redirects-jekyll-github-pages/) about doing this for a jekyll site on github pages, with hints about meta refresh tags. Maybe someone who understands could take a look?

**Comment by eric-wieser** [comment]
Another option would be just to duplicate the `1.18` directory to `latest` as part of the doc update process. Using `<link rel="canonical">` to mark one as the canonical one would be enough to make google happy, and using this approach means that users can more easily get permalinks to "latest" docs, rather than finding themselves redirected immediately.

**Comment by mattip** [comment]
Sounds reasonable and probably the best course of action. I hope we don't shoot ourselves in the foot with this one:

> users can more easily get permalinks to "latest" docs

Yes, although what happens when they permalink to a specific document and then we refactor the documentation or the class changes and that document is no longer valid in the next version? Then their link is broken.

**Comment by eric-wieser** [comment]
I suppose the choices are, via an unspecified mechanism:

1. Redirect `/1.18` to `/latest`
2. Redirect `/latest` to `1.18`
3. Allow both to coexist, tell search engines to prefer `1.18`
4. Allow both to coexist, tell search engines to prefer `latest`

Note that meta refreshes are not an option for intersphinx data - we have no choice but to make a copy there.

**Comment by eric-wieser** [comment]
> Then their link is broken.

I suppose that's the danger of giving users "latest" links in the first place. Maybe we only need it for sphinx?

**Comment by mattip** [comment]
In the community discussion we decided to go with a "stable" redirect to point to latest release, and a "latest" redirect to point to HEAD of development. The fact that API documentation links will break when they change is a feature: it indicates they need to update their documentation. Links to narrative documentation are more sensitive, but it is difficult to promise internal section titles will not change. The page layout should change more slowly (at least until the NEP 44 website overhaul), so most changes should find the right page but a missing anchor.

Downstream library authors should be using the intersphinx data so as long as the section headings remain the same they should be OK.

**Comment by rossbar** [comment]
A `stable` URL was introduced in numpy/doc#4, and the redirection from scipy.org appears to be working as well as intersphinx. If there are still things that need to be covered please reopen.
