### ISSUE TITLE
Numpy ImportError

### ISSUE THREAD

**Issue by jichengfei025** [numpy/numpy#15542]
E:\4-Coding\py_project\screenshot>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
E:\installed\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "E:\installed\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "E:\installed\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "E:\installed\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\installed\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "E:\installed\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

**Comment by jichengfei025** [comment]
conda list:

# packages in environment at E:\installed\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
altgraph                  0.16.1                   pypi_0    pypi
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
asn1crypto                1.3.0                    py37_0    defaults
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.3.0                     py_0    defaults
automat                   0.8.0                      py_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.6.1                      py_0    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
bcrypt                    3.1.7            py37he774522_0    defaults
beautifulsoup4            4.8.2                    py37_0    defaults
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bleach                    3.1.0                    py37_0    defaults
bzip2                     1.0.6                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ca-certificates           2020.1.1                      0    defaults
certifi                   2019.11.28               py37_0    defaults
cffi                      1.13.2           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.0                      py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.3                      py_0    defaults
conda                     4.8.2                    py37_0    defaults
conda-build               3.18.8                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.0            py37h62dcd97_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         3    defaults
constantly                15.1.0           py37h28b3542_0    defaults
cryptography              2.8              py37h7a1dbc1_0    defaults
cssselect                 1.1.0                      py_0    defaults
decorator                 4.4.1                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py37_0    defaults
filelock                  3.0.12                     py_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
future                    0.18.2                   py37_0    defaults
glob2                     0.7                        py_0    defaults
hyperlink                 19.0.0                     py_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.6.1                    pypi_0    pypi
importlib_metadata        1.5.0                    py37_0    defaults
incremental               17.5.0                   py37_0    defaults
inflect                   4.1.0                    py37_0    defaults
intel-openmp              2020.0                      166    defaults
ipykernel                 5.1.4            py37h39e3cac_0    defaults
ipython                   7.12.0           py37h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.1                      py_0    defaults
jaraco.itertools          5.0.0                      py_0    defaults
jedi                      0.16.0                   py37_0    defaults
jinja2                    2.11.1                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
json5                     0.9.0                      py_0    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter_client            5.3.4                    py37_0    defaults
jupyter_core              4.6.1                    py37_0    defaults
jupyterlab                1.2.6              pyhf63ae98_0    defaults
jupyterlab_server         1.0.6                      py_0    defaults
kiwisolver                1.1.0                    pypi_0    pypi
libarchive                3.3.3                h0643e63_5    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.9.0                ha925a31_2    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libtiff                   4.1.0                h56a325e_0    defaults
libxml2                   2.9.9                h464c3ec_0    defaults
libxslt                   1.1.33               h579f668_0    defaults
lxml                      4.5.0            py37h1350720_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
macholib                  1.11                       py_0    defaults
markupsafe                1.1.1            py37he774522_0    defaults
menuinst                  1.4.16           py37he774522_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
mkl                       2019.4                      245    defaults
mkl-service               2.3.0            py37hb782905_0    defaults
mkl_fft                   1.0.15           py37h14836fe_0    defaults
mkl_random                1.1.0            py37h675688f_0    defaults
more-itertools            8.2.0                      py_0    defaults
msys2-conda-epoch         20160418                      1    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  5.0.4                      py_0    defaults
notebook                  6.0.3                    py37_0    defaults
numpy                     1.18.1           py37h93ca92e_0    defaults
numpy-base                1.18.1           py37hc3f5095_1    defaults
olefile                   0.46                     py37_0    defaults
opencv-python             4.1.2.30                 pypi_0    pypi
openssl                   1.1.1d               he774522_3    defaults
packaging                 20.1                       py_0    defaults
pandoc                    1.19.2.1                      1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pandocfilters             1.4.2                    py37_1    defaults
parsel                    1.5.2                    py37_0    defaults
parso                     0.6.0                      py_0    defaults
pefile                    2019.4.18                  py_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    7.0.0            py37hcc1f983_0    defaults
pip                       20.0.2                   py37_1    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.13.1                   py37_0    defaults
powershell_shortcut       0.0.1                         2    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            3.0.3                      py_0    defaults
psutil                    5.6.7            py37he774522_0    defaults
py                        1.8.1                      py_0    defaults
py-lief                   0.9.0            py37ha925a31_2    defaults
pyasn1                    0.4.8                      py_0    defaults
pyasn1-modules            0.2.7                      py_0    defaults
pycosat                   0.6.3            py37he774522_0    defaults
pycparser                 2.19                     py37_0    defaults
pycryptodome              3.8.2            py37he774522_0    defaults
pydispatcher              2.0.5                    py37_1    defaults
pygments                  2.5.2                      py_0    defaults
pyhamcrest                1.9.0                    py37_2    defaults
pyinstaller               3.6              py37h2a8f88b_1    defaults
pymysql                   0.9.3                    py37_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.6                      py_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pyrsistent                0.15.7           py37he774522_0    defaults
pysocks                   1.7.1                    py37_0    defaults
pytest                    5.3.5                    pypi_0    pypi
pytest-runner             5.2                        py_0    defaults
python                    3.7.3                h8c8aaf0_1    defaults
python-dateutil           2.8.1                      py_0    defaults
python-libarchive-c       2.8                     py37_13    defaults
pytz                      2019.3                     py_0    defaults
pywin32                   227              py37he774522_1    defaults
pywin32-ctypes            0.2.0                    py37_0    defaults
pywinpty                  0.5.7                    py37_0    defaults
pyyaml                    5.3              py37he774522_0    defaults
pyzmq                     18.1.1           py37ha925a31_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtpy                      1.9.0                      py_0    defaults
queuelib                  1.5.0                    py37_0    defaults
requests                  2.22.0                   py37_1    defaults
ruamel_yaml               0.15.87          py37he774522_0    defaults
scrapy                    1.6.0                    py37_0    defaults
selenium                  3.141.0          py37he774522_0    defaults
send2trash                1.5.0                    py37_0    defaults
service_identity          18.1.0           py37h28b3542_0    defaults
setuptools                45.2.0                   pypi_0    pypi
sip                       4.19.8           py37h6538335_0    defaults
six                       1.14.0                   py37_0    defaults
soupsieve                 1.9.5                    py37_0    defaults
sqlite                    3.31.1               he774522_0    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
tornado                   6.0.3            py37he774522_1    defaults
tqdm                      4.42.0                     py_0    defaults
traitlets                 4.3.3                    py37_0    defaults
twisted                   19.10.0          py37he774522_0    defaults
urllib3                   1.25.8                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
virtualenv                16.7.9                   pypi_0    pypi
virtualenv-clone          0.5.3                    pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_1    defaults
w3lib                     1.21.0                     py_0    defaults
wcwidth                   0.1.8                      py_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.34.2                   py37_0    defaults
widgetsnbextension        3.5.1                    py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zipp                      2.1.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zope                      1.0                      py37_1    defaults
zope.interface            4.7.1            py37he774522_0    defaults
zstd                      1.3.7                h508b16e_0    defaults

**Comment by mattip** [comment]
You need to activate the Anaconda environment. 
```
Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load. To activate this environment
please see https://conda.io/activation
```

Are there any conda people we could reach out to to get this fixed on their side? We are getting alot of issues opened about activation

**Comment by jichengfei025** [comment]
The isssue still exists after activating. And 
There is only one env in my system.

E:\4-Coding\py_project\screenshot>conda env list
# conda environments:
#
base                  *  E:\installed\Anaconda3


E:\4-Coding\py_project\screenshot>conda activate ase
Could not find conda environment: ase
You can list all discoverable environments with `conda info --envs`.


E:\4-Coding\py_project\screenshot>conda activate base

(base) E:\4-Coding\py_project\screenshot>conda env list
# conda environments:
#
base                  *  E:\installed\Anaconda3

**Comment by rossbar** [comment]
I'm going to close this as resolved.

>  But there is only one env in my system, and it works before.

The `conda` environment management docs are probably a good place to search for the answer to this question.
