### ISSUE TITLE
On armv7l, zero division does not raise

### ISSUE THREAD

**Issue by ckastner** [numpy/numpy#15562]
On a Debian armel host, a zero division does not raise an exception.

### Reproducing code example:

```python
import platform
print(platform.machine())

import numpy as np
np.seterr(all='raise')

one = np.array([1])
print(one/one)

zero = np.array([0])
print(zero/zero)
```

### (Lack of) Error message:

On an armv7l host, this produces
```
>>> import platform
>>> print(platform.machine())
armv7l
>>> 
>>> import numpy as np
>>> np.seterr(all='raise')
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>> 
>>> one = np.array([1])
>>> print(one/one)
[1.]
>>> 
>>> zero = np.array([0])
>>> print(zero/zero)
[nan]
```

Compare this to an x86_64 host:

```
>>> import platform
>>> print(platform.machine())
x86_64
>>> 
>>> import numpy as np
>>> np.seterr(all='raise')
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>> 
>>> one = np.array([1])
>>> print(one/one)
[1.]
>>> 
>>> zero = np.array([0])
>>> print(zero/zero)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: invalid value encountered in true_divide
>>> 
```

I have yet to try this with 1.18.1, but I'm having troubles installing that one on our porter boxes (I don't have access to this hardware myself, the issue was discovered by one of our build boxes when building scikit-learn).

This may or may not be related to #14900.

### Numpy/Python version information:

1.17.4 3.7.6 (default, Jan 20 2020, 05:56:53) 
[GCC 9.2.1 20200117]

**Comment by seberg** [comment]
That issue is unrelated. The issue here is with the platform and how it handles floating point errors. NumPy defines this after the following line: https://github.com/numpy/numpy/blob/1f9ab28a9ee5a0cda956da35d0c77a3a4c4bcd55/numpy/core/src/npymath/ieee754.c.src#L573

Which is platform dependend, and I do not know what should or will happen on armel. If you know the platform, maybe you can see how floating point error flags are handled on it, and whether we need to modify the code to make it work right?

**Comment by ckastner** [comment]
I'm afraid that I'm not familiar with the platform at all. I just noticed this issue on one of our build hosts, where it was triggered by scikit-learn's test suite.

Currently, we're working around this by disabling that one test. After all, first- and second-gen Raspberry Pis, and other armel systems, aren't exactly the target platforms for scientific computing.

I have remote access to armel hosts, where I might be able to help in debugging.

**Comment by mattip** [comment]
PR welcome since that is not one of our CI-tested platforms. If the CPU is being defined correctly in the code @seberg pointed to, and it does not set the flags when it encounters an error, then we need to manually check for nan in the division and set the flag. This is expensive, so it should be done only for that platform.

**Comment by ckastner** [comment]
This does seem to be a general (ie, NumPy-independent) platform issue.

I created a minimal test case and [reported it](https://lists.debian.org/debian-arm/2020/02/msg00076.html) to our ARM list.

Looking at the following test,

https://github.com/numpy/numpy/blob/2eedaa4cf94cf54bbd4d8428aa39271410f22e9f/numpy/core/tests/test_errstate.py#L9

it appears that Debian already reported FE exception issues in the (way) past, see #14139 

What's odd though is that division by zero is tested,

https://github.com/numpy/numpy/blob/2eedaa4cf94cf54bbd4d8428aa39271410f22e9f/numpy/core/tests/test_errstate.py#L20-L28

and thus I'd expect this test to fail, but from the most recent [build log](https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armel&ver=1%3A1.17.4-5&stamp=1577011576&raw=0), it passed.

Apparently, division by zero with a scalar does get caught, it's the array division that doesn't get caught.

I just submitted PR #15577 that extends the test to check for array division as well. This way, the issue at least gets detected. I believe that the fix ideally should come from the platform, however. I'll see how the discussion on our ARM list goes.
