### ISSUE TITLE
Unclear documentation of np.copy

### ISSUE THREAD

**Issue by moble** [numpy/numpy#15570]
A very painful bug of mine turns out to originate in the different behaviors of `np.copy(a)` and `a.copy()` — specifically, the fact that the latter preserves subclass, whereas the former does not.

If I look through the actual code, it's clear why this happens, but it's certainly not clear from the documentation that it will happen.  In fact, I consider the documentation for `np.copy` downright misleading because it addresses *one* difference between the two (namely, the default `order` argument), which lulled me into believing that it was the only difference.  (And yes, the documentation technically refers to `ndarray.copy`, while my subclass was not `ndarray`, but I don't read documentation like a lawyer.)

I'll acknowledge that changing the default behavior is off the table, so I'll suggest two possibilities that would at least help avoid this situation:

1. Add a `subok=False` option to `np.copy` that is just passed through to `np.array`.  The default behavior will remain the same, but the presence of this argument will alert the user to the fact that there might be an issue.

2. Add to the docstring an explicit statement of the fact that subclasses will not pass through.

https://github.com/numpy/numpy/blob/d9b1e32cb8ef90d6b4a47853241db2a28146a57d/numpy/lib/function_base.py#L745-L790

**Comment by moble** [comment]
Ah!  In fact, there was discussion of precisely this problem in #3474, in which people seemed open to the idea of changing the default behavior to call the subclass's copy method, and PR #6509 was even opened to implement item 1 from above (but died due to forgetfulness).

**Comment by rossbar** [comment]
Thanks for re-bringing up this issue. There was a consensus that a PR along the lines of #6509 would be welcome, in addition to modifying the doc string of `np.copy` to discourage it's use in favor of `.copy()` methods.

**Comment by rossbar** [comment]
Closed by #15685
