### ISSUE TITLE
axis/dimension bug in numpy.gradient()

### ISSUE THREAD

**Issue by drsmith48** [numpy/numpy#15572]
I believe this line in `numpy.gradient()` should be: `elif n == N`.
https://github.com/numpy/numpy/blob/1f9ab28a9ee5a0cda956da35d0c77a3a4c4bcd55/numpy/lib/function_base.py#L961
`N` is the number of dimensions in the input array, `n` is the number of specifications for dimension spacings in `varargs`, and `len_axes` is the number of axes specified in the `axis` keyword.  It seems to me that the current conditional (`n == len_axes`) is nonsensical because it is valid to take a gradient in a single dimension of a multi-dimensional array such that `n < len_axes`.  Also, the docs for the `axis` keyword supports this scenario.  If the conditional were `n == N`, then the number of specified dimension spacings must match the number of dimensions, which is sensible.  Also, this usage is in line with the docs that say `varargs` must be a single scalar or a list with `N` elements.

**Comment by eric-wieser** [comment]
> because it is valid to take a gradient in a single dimension

Doing this would mean that `len(axes) == 1`, so I don't see a contradiction with the current implementation.

**Comment by drsmith48** [comment]
If `n>1` (a multi-dimensional array) and `len(axis) == 1` (so the gradient of single dimension of a multi-dimensional array), then the current implementation gives `n` is not in [0, 1, len(axis)] and the entire if/elif structure resorts to the TypeError in `else`.  It seems to me this should be a valid use case.

**Comment by eric-wieser** [comment]
Did you mean `N` in that comment and not `n`? Clearly the variable names are non-ideal.

**Comment by eric-wieser** [comment]
`n` is the number of `dx` items provided, and there should be an axis for each of these.

**Comment by seberg** [comment]
@drsmith48 can you construct an example what is wrong? I would also be very happy about cleaning up the variable names a bit! But right now it seems to me we can probably close this soon?

**Comment by rgommers** [comment]
no response in 2.5 months and looks like no bug here, closing
