### ISSUE TITLE
Does np.random.binomial use Mersenne twister sequence?

### ISSUE THREAD

**Issue by sqjin** [numpy/numpy#15578]
Hello!  I know np.random.rand uses the Mersenne twister to generate random numbers.  I am wondering whether np.random.binomial also uses Mersenne twister sequence?  If not, how can I use Mersenne twister to generate random numbers from the binomial distribution?  Thanks so much!

**Comment by rkern** [comment]
All of the `np.random.*` distribution functions use the same pseudo-random stream underneath, in this case the Mersenne Twister.

**Comment by sqjin** [comment]
@rkern Thanks! But do you have any idea how to get the same random numbers in Python and Matlab?   I am converting some Matlab codes to python.  I have verified that _np.random.rand_ gives the same random numbers as the Matlab function '_rand_' when setting the seed to be the same.  Both of them use the Mersenne Twister algorithm.  However, the results from _np.random.binomial_ are not the same as the Matlab function '_binornd_'.  Any suggestions are really appreciated.

**Comment by rkern** [comment]
The Mersenne Twister is just the uniform random number generator. It produces a sequence of pseudo-random bits, essentially. To get the non-uniform distributions, like the normal distribution or the binomial distribution, both MATLAB and we need to run certain algorithms that use the sequence of random bits from the uniform random number generator. There are often a number of different ways to implement each non-uniform distribution. We use a different method for binomial than MATLAB does. This is unrelated to the Mersenne Twister algorithm underneath. Strict bit-for-bit compatibility of the non-uniform distributions with MATLAB is not a goal for numpy. You will need to find another way to test the correct implementation of your ported code.

**Comment by sqjin** [comment]
@rkern I see. Thanks so much for your detailed explanations.
