### ISSUE TITLE
Non-standard behaviour of bool() with ndarrays

### ISSUE THREAD

**Issue by Marco-Sulla** [numpy/numpy#15573]
```python
Python 3.9.0a0 (heads/master-dirty:d8ca2354ed, Oct 30 2019, 20:25:01) 
[GCC 9.2.1 20190909] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.ones(0)
>>> bool(a)
<stdin>:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
False
>>> a = np.ones(1)
>>> bool(a)
True
>>> a = np.ones(2)
>>> bool(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> np.__version__
'1.18.1'
```

This is not compliant with the [Python standard](https://docs.python.org/3/library/stdtypes.html#truth):

> By default, an object is considered true unless its class defines either a `__bool__()` method that returns False or a `__len__()` method that returns zero

What's the usefulness of making `bool()` working only for arrays with one value? This way:

```python
if myndarray:
   # code here
```

can't be done, as it's very common in Python.

IMHO `ndarray` should follow the standard of any other Python iterable (iterators apart): return 0 if the array length is 0, 1 otherwise. And it's much simple, you have only to remove the current `__bool__` implementation :)

**Comment by eric-wieser** [comment]
Allowing this would be really dangerous, as `bool(arr == 42)` would be true even if `arr = [0, 1, 2]`, since `bool([False, False, False])`.

**Comment by Marco-Sulla** [comment]
...because you also redefined the `__eq__` operator?

Oh. My. God.

This is completely unpythonic. The standard of any iterable in Python is that the equality can be done only between iterables of the same (sub)type. This is why Python is considered a strong-typed language.

You could had implement the current behavior of __eq__ using simply another method, like 
```python
myarray.equal(7*9)
```

But at this time is too much late...

I mean, this is not Python. If you wanted a free implementation of  Matlab, there was already GNU Octave.

**Comment by eric-wieser** [comment]
> You could had implemented the current behavior of `__eq__` using simply another method, like
> 
> ```python
> myarray.equal(7*9)
> ```

Before declaring any more parts of numpy unpythonic, I think it's worth realizing that some parts of numpy are pythonic by definition, as the language itself actually changed to accommodate numpy. For instance, `a @ b` became a better spelling for `a.dot(b)` (roughly speaking).

Thinking of numpy arrays as iterables is not a particularly useful mental model, for all the reasons you're giving.

**Comment by Marco-Sulla** [comment]
Well, but `ndarray`s **are** iterables:

```python
>>> a
array([1., 1.])
>>> iter(a)
<iterator object at 0x7f9ff17f35e0>
```

And about `__matmul__` operator, this operator simply did not existed before in Python. `__bool__` and `__eq__` yes, on the contrary. And theirs behavior NumPy implemented are completely unpythonic.

**Comment by Marco-Sulla** [comment]
Furthermore, this is also against [PEP 8](https://www.python.org/dev/peps/pep-0008/):

> For sequences, (strings, lists, tuples), use the fact that empty sequences are false.
```python
Yes: if not seq:
     if seq:

No:  if len(seq):
     if not len(seq):
```

**Comment by seberg** [comment]
@Marco-Sulla I am happy if you create a more "pythonic" array (one that does not embrace array-programming as well). But please do not complain about such fundamental and widely popular design choices here.

The whole *point* of NumPy is to use the type information to transform Python into an array programming language. Which is incredibly powerful and elegant for the tasks it is used to.

And yes that implies that for NumPy types, operators have a different meaning (elementwise and broadcasting). And yes, that can in some cases lead to slight inconsistencies. But those are really very small in practice and not worse then remembering that `==` is different then a hypothetical `elementiwse==` operator.

In any case, you cannot argue with the ridiculous success of NumPy. So if you come from a background that does not wrangle with data and for which "array programming" is super powerful, and dislike the embrace of array programming, use a different tool.

`@` was created **for** NumPy. If NumPy was considered odd and bad, I think Python would have rejected it as a motivation for adding a whole operator :).

Or to give the old quote: "Practicallity beats purity" and anything short of full blown array programming is not practicable for the things that NumPy is used and loved for.

**Comment by Marco-Sulla** [comment]
> I am happy if you create a more "pythonic" array

I have first to finish the python and CPython implementation of `frozendict`. And to finish pointless discussions on internet :-P

> (one that does not embrace array-programming as well)

And why?

> But please do not complain about such fundamental and widely popular design choices here.

I'm not complaining, I'm simply expressing my astonishment about `numpy` design. And, you know, the fact something is very popular does not mean nothing. Javascript, Windows and WhatsApp, for example, are very popular.

> The whole _point_ of NumPy is to use the type information to transform Python into an array programming language. Which is incredibly powerful and elegant for the tasks it is used to.

And this is absolutely good.

> And yes that implies that for NumPy types, operators have a different meaning (elementwise and broadcasting). And yes, that can in some cases lead to slight inconsistencies. But those are really very small in practice

Very small? `numpy` broken Duck Typing.

An example?

```python
def some_operation_on_an_iterable(it):
    if not it:
        raise ValueError("The argument must be a non empty iterable")
    
    # code here
```

This trivial function does not work if you pass a `numpy` array. I don't know if you understand how much **serious and common** this is.

> if you [...] dislike the embrace of array programming, use a different tool.

I never said I dislike array programming. I simply said `numpy` could had be designed in a pythonic way. It was not. Amen.

(On the contrary, it seems to me that `numpy` intentionally broken Python good and established practices only to attract Matlab people...) 

> `@` was created **for** NumPy. If NumPy was considered odd and bad, I think Python would have rejected it as a motivation for adding a whole operator :).

No one said nothing bad about the `__matmul__` operator. Eric Wieser started to talk about `@` and I don't know why :-D

> Or to give the old quote: "Practicallity beats purity"

Well, you forgot the Peter's phrase before: 

> Special cases aren't special enough to break the rules

**Comment by seberg** [comment]
Yup, there is no point in discussing this. Obviously NumPy as quirks, obviously NumPy is super popular, and obviously those who use and love it have embraced most of these quirks as integral design choices for convenient array programming.
So we can just be astonished together that NumPy is as popular and useful as it is given the quirks!

**Comment by Marco-Sulla** [comment]
I'm more astonished about the fact you didn't replied to my core point: Duck Typing.

**Comment by mattip** [comment]
The real issue is that NumPy is more of an ndarray than an iterator. We define the comparison operators as we do because oh-so-long-ago we needed to get answers to `a == b` that are also ndarrays and not booleans, this is very useful for pardigms like `a[a != b]`. 

Simply declaring numpy unpythonic or even breaking ducktyping is not going to convince us to make such an invasive change because of the pain it will cause to our users. However we do have a process to discuss such things, and there is room to present your case in a non-confrontational manner. The ground rules are laid out in our [NEP](https://numpy.org/neps) process.

I would suggest we slow this discussion down and more carefully consider the tone it takes.

**Comment by Marco-Sulla** [comment]
> this is very useful for pardigms like `a[a != b]`.

Pythonic way:

```python
filter(lambda x: x != num, iterable)
```

"Readability counts."
But unluckily `numpy.array()` does not support filter objects...

> [...] is not going to convince us to make such an invasive change

Maybe I did not express me very well. I already said it's too late now to change the whole thing. My hope is only that you, or some of you, had understood that it was not a good idea at all, and in future follow a more standard way to implement things in Python at least.
