### ISSUE TITLE
Q: Prerelease wheels no longer have OpenBLAS

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#15580]
As of a day or two ago, some builds that use:
```
pip install -f "https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com" --pre numpy
```
seem to have gotten a lot slower. Digging into it, two days ago (e.g., on `1.19.0.dev0+af0dfce`) we saw `openblas` listed as the linked library (i.e., had something other than `NOT AVAILABLE` listed under it in `np.show_config()`), now on `1.19.0.dev0+2eedaa4` [we get](https://travis-ci.org/mne-tools/mne-python/jobs/651272784#L2582):

<details><summary>np.show_config()</summary>

```
$ python -c "import numpy; numpy.show_config()"
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
blas_info:
  NOT AVAILABLE
blas_src_info:
  NOT AVAILABLE
blas_opt_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
  NOT AVAILABLE
lapack_src_info:
  NOT AVAILABLE
lapack_opt_info:
  NOT AVAILABLE
numpy_linalg_lapack_lite:
    language = c
    define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
```

</details>

Is this intended, or a bug when migrating to manylinux2010 builds?

Apologies if this should live in https://github.com/MacPython/numpy-wheels instead, or if I'm missing something obvious.

**Comment by charris** [comment]
It is a bug. Using manylinux2010 for the pre-wheels is an attempt to discover such problems early.

**Comment by charris** [comment]
We probably need to compile OpenBLAS libraries for manylinux2010, they may even already exist. @mattip @tylerjereddy Thoughts?

**Comment by mattip** [comment]
I don't see why this should happen.

Our different CI systems use different methods to find and download the OpenBLAS libs. This repo's CI uses `tools/openblas_support.py`, which has the `manylinux1` part of the name hard-coded into the file name, but that is not relevant here.

numpy-wheels uses the gfortran_utils subrepo function [get_gf_lib_for_suf](https://github.com/MacPython/gfortran-install/blob/e9764d0a8f4e3adcd385c319e7742177193484c7/gfortran_utils.sh#L45), which gets the file name from [`get_distutils_platform`](https://github.com/MacPython/gfortran-install/blob/e9764d0a8f4e3adcd385c319e7742177193484c7/gfortran_utils.sh#L23) which is also hard-coded to manylinux1.

@charris can you point me to the log where that build happened? @larsoner what platform and OS are you using?

**Comment by mattip** [comment]
I found the build log.

It seems the libfortran needed is [not found](https://travis-ci.org/MacPython/numpy-wheels/jobs/650537240#L426) when building wheels, here is the linked log lin:
```
gcc/x86_64-redhat-linux/8/ld: warning: libgfortran.so.3, needed \
      by /usr/local/lib/libopenblas.so, not found
```

**Comment by mattip** [comment]
to prevent this in the future, the numpy-wheels build should have a check like the one in tools/.travis-test.sh
```
$PYTHON ../tools/openblas_support.py --check_version $OPENBLAS_VERSION
```

**Comment by charris** [comment]
@mattip Nice find. I suppose we could install the libraries but ideally they would be part of the docker image.

**Comment by mattip** [comment]
[Working on it](https://github.com/MacPython/numpy-wheels/pull/73/files#diff-56755ef7919deca2e30854b110f67bdeR12) as part of MacPython/numpy-wheels#73, but now I am getting a failure on the 32-bit build not passing the latest `test_umath_accuracy.py` PR.

**Comment by seberg** [comment]
@mattip is this fixed and/or the milestone not important?

**Comment by charris** [comment]
Yes, it has been fixed in the wheels repository, I checked a couple of days ago. Will do so again when the first 1.19 release is made.

**Comment by mattip** [comment]
The wheel building (on linux and mac) now [checks](https://github.com/MacPython/numpy-wheels/blob/master/config.sh#L48) that the expected OpenBLAS is used. Unfortunately I still haven't found a good, simple way to check windows.

**Comment by charris** [comment]
A quick way to check is the size, wheels -- now that they are stripped -- should run 10 - 14 MB compressed. OpenBLAS is the single largest part of the content.
