### ISSUE TITLE
Numpy installation error: ImportError: DLL load failed: The specified module could not be found.  // Importing the numpy c-extensions failed.

### ISSUE THREAD

**Issue by calum6371** [numpy/numpy#15588]
Hello,

Haven't used python or numpy for several years so trying to get back into it. I installed Conda and set up on Windows 10, VS Studio code. 

When trying to install numpy with `conda install numpy` I get an error which seems very common but I haven't managed to find any solutions for.

### Reproducing code example:
```python
import numpy as np
```

### Error message:
I get the following error(s). 

```
C:\Users\calum\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\calum\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\calum\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\calum\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\Zeit-IT\readcsv.py", line 2, in <module>
    import numpy as np
  File "C:\Users\calum\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\calum\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\calum\AppData\Local\Continuum\anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
```

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.18.1 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
```

### Other Info & Outputs
```
(base) C:\Users\calum> conda install mkl -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
``` 

```
(base) C:\Users\calum>conda list numpy
# packages in environment at C:\Users\calum\AppData\Local\Continuum\anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
```

I am currently not working in a virtual environment and I have no other python versions installed.

Windows 10

Python version is 3.7.4.

I have checked my PATH contains the links to `C:\Users\calum\AppData\Local\Continuum\anaconda3\Scripts` and `C:\Users\calum\AppData\Local\Continuum\anaconda`

Thanks for any help.

**Comment by mattip** [comment]
There is a bit of this that doesn't make sense to me, maybe you can explain where I am confused. In the middle of the issue, you have 
```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.18.1 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
```
which shows you **can** import numpy. But when you run `h:\Zeit-IT\readcsv.py`, you **cannot** import numpy. What is different? Perhaps the second one is being run in an way that does not activate the conda environment?

**Comment by calum6371** [comment]
Interesting, thanks for pointing this out!

I think what is happening is that while on VS Code I use the keyboard to run via the extension [code-runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner), which caused the error above. 

But when activating python in the terminal or running with  `python readcsv.py` it works. 

So I believe the the problem is code runner not knowing how to activate my conda environment and thus find the installed packages.

No idea how to actually solve this problem but the work around is to not use code runner.

**Comment by mattip** [comment]
There are some hints in the VS Code docs [here](https://code.visualstudio.com/docs/python/environments), do any of them work for you?

**Comment by criscieleferreira** [comment]
@calum6371 Do you figure out how to solve your problem? I have the same problem. I´m new to python and All of these. If you have any advice to share I´ll be gratefull.

**Comment by calum6371** [comment]
@criscieleferreira I actually just changed my workflow. As mentioned above I stopped using[ code-runner, ](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) which was not activating the correct conda environment. 

I solved this problem by running directly in the VS python terminal e.g. typing `python myscript.py`. 

One thing to check is to make sure you are loading the correct python environment within VS code. Hit `Ctrl + Shift + P` and select 'Python: Select Interpreter` then choose the correct path. For me this points to a virtual environment I made (Search how to do this if you're unsure) in Conda `~AppData/Local/Continuum/ Anaconda/Python.exe`. 

If you're not running the correct environment your packages (e..g numpy for me in the case above) won't be loaded.

Hope that helps.

**Comment by rossbar** [comment]
Seems like this was resolved when the conda activation problems of the original workflow were cleared up, so I'm going to close this. For related issues please see the [troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html), especially the sections about environment management with VS code.
