### ISSUE TITLE
np.max doesn't work for comparing float numbers

### ISSUE THREAD

**Issue by zxdawn** [numpy/numpy#15586]
### Reproducing code example:

```python
import numpy as np
print (np.max(450.0802234473462, 85.0))
```

### Error message:

```
    print (np.max(450.0802234473462, 85.0))
  File "<__array_function__ internals>", line 6, in amax
  File "E:\miniconda3\envs\python37\lib\site-packages\numpy\core\fromnumeric.py", line 2621, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "E:\miniconda3\envs\python37\lib\site-packages\numpy\core\fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: 'float' object cannot be interpreted as an integer
```

### Numpy/Python version information:

1.17.4 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]

**Comment by zxdawn** [comment]
Sorry ... it should be `print (np.max([450.0802234473462, 85.0]))`.

**Comment by LamForest** [comment]
ndarray.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)

np.max should be applied to a ndarray. Despite the same name with Python's bulit-in `max`,  it has different usage.
