### ISSUE TITLE
BUG: test_umath_accuracy tests for a specific NAN

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#15593]
Inside the manylinux2010 i686 docker, `log(-1)` returns `nan`, but it is a different `nan` than the one expected by the [data](https://github.com/numpy/numpy/pull/14048/files#diff-c3b4a71eff65b42180aea2630ee50a92R11) used in `test_umath_accuracy`. The tests expect `0xffc00000`, but the glibc `log()` function on this platform returns `0x7fc00000`. Both are `nan`, but [`assert_array_max_ulp`](https://github.com/numpy/numpy/pull/14048/files#diff-8df7ea06c4577eeeba7aa23db566034aR53) uses `nulp_diff` which is very literal:
```
>>> import numpy as np, numpy.testing
>>> x = np.int32(0xffc00000).view(np.float32)
>>> y = np.int32(0x7fc00000).view(np.float32)
>>> print(x, y)
nan nan
>>> numpy.testing._private.utils.nulp_diff(y, x)
8388608.0
```
`np.isnan` returns True for both.

I think the test be relaxed to accept more than one `nan`.

**Comment by r-devulap** [comment]
I will update the test and submit a patch.
