### ISSUE TITLE
np.dot() precision problem

### ISSUE THREAD

**Issue by daniel-kukiela** [numpy/numpy#15591]
`np.dot()` seem to have precision problem

### Reproducing code example:

```python
import numpy as np
p64 = np.ones(1000, dtype=np.float64)+1e-14
print(np.dot(p64, p64))
print((p64 * p64).sum())
p32 = np.ones(1000, dtype=np.float32)+1e-7
print(np.dot(p32, p32))
print((p32 * p32).sum())
```

Tested on my PC and my laptop.

PC:
```py
>>> import numpy as np
>>> p64 = np.ones(1000, dtype=np.float64)+1e-14
>>> print(np.dot(p64, p64))
1000.0000000000208
>>> print((p64 * p64).sum())
1000.0000000000198
>>> p32 = np.ones(1000, dtype=np.float32)+1e-7
>>> print(np.dot(p32, p32))
1000.0001
>>> print((p32 * p32).sum())
1000.0001
```

Laptop:
```py
>>> import numpy as np
>>> p64 = np.ones(1000, dtype=np.float64)+1e-14
>>> print(np.dot(p64, p64))
1000.0000000000207
>>> print((p64 * p64).sum())
1000.0000000000198
>>> p32 = np.ones(1000, dtype=np.float32)+1e-7
>>> print(np.dot(p32, p32))
1000.00006
>>> print((p32 * p32).sum())
1000.0001
```

What causes difference in `np.dot()` between those machines? I'm getting different results and that breaks repeat-ability so other people using my code won't get same results.

Is there any workaround?

### Numpy/Python version information:

On both machines there is Python 3.7.6 and NumPy 1.18.1

**Comment by seberg** [comment]
Different systems may give different results. The main variance should be which BLAS numpy is linked against (OpenBLAS, MKL, ...). But even within each BLAS the actual code differs for different CPUs: It is a high dimensional problem, and at least within the limits of allowing to reorder calculations in combination with the limited precision of floating point maths, you have to expect differences.
