### ISSUE TITLE
BUG: AVX-512 path for `ufunc.accumulate` is broken

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#15597]
We use `np.minimum.accumulate` in statsmodels.  Recent pre-release tests have started failing on after calls to `np.minimum.accumulate`.  

This code only fails on systems with AVX-512. Passes on systems with AVX and AVX2.

### Reproducing code example:

```python
import numpy as np
ntests = 10
pvals = np.random.random_sample(10)
pvals_corrected_raw = np.arange(ntests, 0, -1) * pvals
pvals_corrected = np.minimum.accumulate(pvals_corrected_raw[::-1])[::-1]
```

Failing job:

https://travis-ci.org/statsmodels/statsmodels/jobs/651893167

### Error message:

No error, but wrong results.  Likely strides are off since we often seem empty-like values in places. 

### Numpy/Python version information:

```
Python: 3.7.5.final.0
cython: 3.0a0
numpy: 1.19.0.dev0+4d2b585
scipy: 1.5.0.dev0+f614064 
pandas: 1.1.0.dev0+500.g06eb8db97 
```

**Comment by bashtage** [comment]
xref statsmodels/statsmodels#6524

**Comment by bashtage** [comment]
cc @josef-pkt @kshedden

**Comment by josef-pkt** [comment]
here's a maximum example from the unit tests

```
pvals = np.array([0.002, 0.004, 0.006, 0.008, 0.01 , 0.012])
ntests = len(pvals)

pvals_corrected_raw = pvals * np.arange(ntests, 0, -1)
pvals_corrected = np.maximum.accumulate(pvals_corrected_raw)
pvals_corrected

# expected array([0.012, 0.02 , 0.024, 0.024, 0.024, 0.024])
# in failing test array([0.012, 0.02 , 0.024, 0.024, 0.02 , 0.012])
```

the original pvals in the test is a view, but pvals_corrected_raw shouldn't be

(Pdb) pval.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

**Comment by seberg** [comment]
@r-devulap can you ave a look?

**Comment by r-devulap** [comment]
yup, taking a look ..

**Comment by r-devulap** [comment]
Found the bug, `np.maximum.accumulate` results in input and output arrays being overlapped in memory in the maximum/minimum function. Added a pre-check to prevent vectorized code in such a scenario in PR https://github.com/numpy/numpy/pull/15612

**Comment by r-devulap** [comment]
I brought up this question when I submitted the patch (see comments https://github.com/numpy/numpy/pull/14867#issuecomment-560984763). There are no tests covering `np.maximum.accumulate`. Can someone help me understand under what scenarios do we expect input and output arrays to overlap in memory to ensure we haven't missed all the use cases.
