### ISSUE TITLE
np.pad will cast constant_values to type of input

### ISSUE THREAD

**Issue by takotab** [numpy/numpy#15606]
np.pad(np.arange(10.)[None,:], pad_width=[(0,0),(1,0)], mode='constant', constant_values = 4.5)
array([[4.5, 0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. ]])

np.pad(np.arange(10)[None,:], pad_width=[(0,0),(1,0)], mode='constant', constant_values = 4.5)
array([[4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Note the change of the 4.5 to 4 on location 0 in the second run.

Is this desired behavior? And also to silently?

**Comment by Qiyu8** [comment]
The second array's dtype is int, so 4.5 is forced converted to 4.

**Comment by takotab** [comment]
So this is the desired behavior with the constant_value being a float?

**Comment by rsokl** [comment]
Yes that is the desired behavior
