### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by fpedu** [numpy/numpy#15613]
I have installed Python by execuble archive on Python.org
I do use Windows 10 64 bits
Numpy already comes with Anaconda3, I uninstalled and installed numpy with conda install/uninstall numpy (I do use 1.18.1 version)
I have just one python version (3.7.4)
I was tryna import tensorflow
I can neither import numpy nor tensorflow
Error Message:
PS C:\Users\filip\Desktop\Filipe\Python\Scripts> & C:/Users/filip/AppData/Local/Continuum/anaconda3/python.exe c:/Users/filip/Desktop/Filipe/Python/Scripts/Teste.py
C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy_init_.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
from . import distributor_init
Traceback (most recent call last):
File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core_init.py", line 24, in
from . import multiarray
File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in
from . import overrides
File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in
from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:/Users/filip/Desktop/Filipe/Python/Scripts/Teste.py", line 1, in
import numpy as np
File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy_init_.py", line 142, in
from . import core
File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core_init_.py", line 54, in
raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.

Try uninstalling and reinstalling numpy.

If you have already done that, then:

Check that you expected to use Python3.7 from "C:\Users\filip\AppData\Local\Continuum\anaconda3\python.exe",
and that you have no directories in your PATH or PYTHONPATH that can
interfere with the Python and numpy version "1.18.1" you're trying to use.
If (1) looks fine, you can open a new issue at
https://github.com/numpy/numpy/issues. Please include details on:
how you installed Python
how you installed numpy
your operating system
whether or not you have multiple versions of Python installed
if you built from source, your compiler versions and ideally a build log
If you're working with a numpy git repository, try git clean -xdf
(removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Não foi possível encontrar o módulo especificado.

NOTE: My Python CLI does work and I did active the conda environment

**Comment by ReneKat** [comment]
I'm having the same issue

**Comment by fpedu** [comment]
What a mess ;-;

**Comment by rossbar** [comment]
@ReneKat - if you take a closer look at the error message, you will see:

> Note: this error has many possible causes, so please don't comment on
> an existing issue about this - open a new one instead.

It is unlikely that what is causing the issues is *exactly* related to @fpedu 's case, but thanks for reporting anyways. The error message is indeed long so it's understandable if you didn't make it all the way to the bottom :)

In any case, assuming you are both using Anaconda on Windows, can each of you try the following:

```
conda create -n testenv python
conda activate testenv
conda install numpy
python -c "import numpy as np; print(np.__version__)"
```

**Comment by fpedu** [comment]
@rossbar It did work at testenv, but i need it workinf on my main python code
I still cannot import numpy or tensoflow

**Comment by rossbar** [comment]
This means that there is an issue with how you installed, configured, or use Python on your system. Note that one of the main features of `conda` is environment management, which allows you to have completely "sandboxed" environments that include all of the dependencies you need for individual projects. The above code snippet is an example of setting up such an environment and installing numpy into it. You can take the above example and extend it to specify an environment that you actually want for your work: for example, replace `testenv` with a name that describes the project you're working on, and add additional libraries to the install (e.g. `tensorflow`, based on your above example). I'd also recommend you take a close look at the [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html), particularly the "concepts" and "configuration" sections of the user guide.

Since this is not a numpy issue, I'm closing this for now. @ReneKat if you're still having problems please open a new one. I hope this was helpful!

**Comment by ReneKat** [comment]
Hi @rossbar,
Thank you so much for your replies! I am using Mac OSX. 
I'm actually having an issue with CONCOCT that has led me to my numpy installation error. 
I will work on troubleshooting more and if still am having issues will open a new one. 
Thank you!
René
