### ISSUE TITLE
numpy.isclose/allclose doesn't handle very large integers

### ISSUE THREAD

**Issue by fxthomas** [numpy/numpy#15618]
`numpy.isclose` (as well as `numpy.allclose` and `math.isclose`) behave strangely for very large integers. I assume that this is caused by internal conversions to `float`, as the docs mention:

```
If the following equation is element-wise True, then allclose returns True.
    absolute(a - b) <= (atol + rtol * absolute(b))
```

I stumbled onto this while unit-testing one of my tools with random data, which is why the example is a bit unrealistic, but I feel that this may need at least a mention in the docs or a warning at runtime.

Python docs for `math.isclose` specifically mention that it only compares floating-point numbers.

### Reproducing code example:

```python
import numpy as np
a = np.int64(1589056744433029441)
b = np.int64(1589056744433029431)
print(np.isclose(a, b, atol=1, rtol=0))   # True
print(a == b)                             # False
print(a - b)                              # 10
```

### Numpy/Python version information:

1.18.1 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]

**Comment by charris** [comment]
> I assume that this is caused by internal conversions to float

Yes,
```
In [9]: float(a) - float(b)                                                     
Out[9]: 0.0
```

**Comment by rossbar** [comment]
@fxthomas the use-case for `*close` methods with integers isn't clear to me: comparison of integers can be exact. If you had a particular case in mind I'd be curious if you wouldn't mind sharing - if not that's okay too. Similarly, if you have a specific idea how the docs could be improved please create a PR - I'd be happy to review.

**Comment by rossbar** [comment]
`isclose` does convert to an `np.inexact` type. This could be mentioned in the docs, though see my comment above about `isclose` with ints.

**Comment by rgommers** [comment]
The question seems answered, and there is no bug (this is just how it works). So closing. Thanks all.
