### ISSUE TITLE
Array creation behaves strangely with (very) deeply nested lists

### ISSUE THREAD

**Issue by DvdMgr** [numpy/numpy#15611]
I'm a bit confused by how numpy creates arrays from deeply nested lists. Everything works fine up to 32 dimensions, however it seems that when there are more than 32 nested lists in the passed data a list object is inserted, instead of it being converted to a numpy dimension. Correspondingly, the dtype of the array changes to `np.object`.

### Reproducing code example:

```python
import numpy as np

# This is ok
test_array_32 = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])
print("Array initialized from 32 nested lists:")
print(test_array_32)
print("Dtype: %s" % test_array_32.dtype)

# This is strange
test_array_33 = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])
print("Array initialized from 33 nested lists:")
print(test_array_33)
print("Dtype: %s" % test_array_33.dtype)

# This is strange but consistent
test_array_many = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])
print("Array initialized from many nested lists:")
print(test_array_many)
print("Dtype: %s" % test_array_many.dtype)

# This throws an error
test_array_many_forced = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]], dtype=np.int)
print("Array initialized from many nested lists, forced to dtype=np.int:")
print(test_array_many_forced)
print("Dtype: %s" % test_array_many_forced.dtype)

```

Output of the above program for convenience:
```
Array initialized from 32 nested lists:
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
Dtype: int64
Array initialized from 33 nested lists:
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[list([1])]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
Dtype: object
Array initialized from many nested lists:
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[list([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
Dtype: object
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-117-d641b1b0ad21> in <module>
----> 1 import codecs, os;__pyfile = codecs.open('''/tmp/pysgh9na''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/pysgh9na''');exec(compile(__code, '''/home/davide/numpyissue.py''', 'exec'));

~/numpyissue.py in <module>
     20 
     21 # This throws an error
---> 22 test_array_many = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]], dtype=np.int)
     23 print("Array initialized from many nested lists, forced to dtype=int:")
     24 print(test_array_many)

ValueError: setting an array element with a sequence.
```

### Numpy/Python version information:

1.17.4 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0]

**Comment by seberg** [comment]
Good point, I think it could be good to add a deprecation warning and turn it into an array. Also fits well with the deprecation of automatically returning `objects` for ragged list inputs. A decision will be if we want `np.array(nested_lists, dtype=object)` to just keep doing what it does not.

PRs welcome, I expect it should be fairly uncontroversial to add at least a DeprecationWarning here!

**Comment by DvdMgr** [comment]
So, is there any solution to this issue I can implement in my own code to correctly have more than 32 dimensions in the output array?

**Comment by seberg** [comment]
No, NumPy is hardcoded to be limited to 32 dimensions. You can change this (`NPY_MAX_DIMS`, I may also change `NPY_MAX_ARGS` since it identical just to be sure in case they are mixed up somewhere). But you would have to recompile your own version of NumPy. Changing that limit would be a whole other discussion with the main question being the use case. I remember one other person once having a use case (where most dimensions had size 1 for some reason). But generally, even a an array shaped `(2,) * 32` is so large that it seems unlikely to happen much in practice.

**Comment by DvdMgr** [comment]
Huh, didn't know that, thanks for the clarification!

In our case, the 'need' for lots of dimensions is to collect simulation results, where the simulation under study has a lot of parameters. When dealing with these simulations, typically we want to explore the behavior of some settings, and don't know in advance which one (it depends on results). So, even though most dimensions will have size 1, we might have to explore other values for some random dimension eventually. In order to make the code easier to deal with, we prefer to have a fixed number of dimensions, and change their sizes based on our needs. 

I'll just remove some parameters I don't expect we will need to play with down the road, to reduce the number of dimensions in the array. 

Feel free to close this if you want, you definitely answered my question, and thanks again!

**Comment by seberg** [comment]
Yeah, we should add that to the "ragged deprecation warning" though, and at least force you to use `dtype=object` to get the broken result, since that is just brand new in NumPy.

**Comment by eric-wieser** [comment]
Agreed that this falls under the same umbrella of needing `dtype=object` as the ragged stuff

**Comment by mattip** [comment]
I think we should error out whenever the recursion level goes over 32 in the type detection. I'm not sure I see the connection with ragged arrays, other than the mismatch between what NumPy is designed to do well and what the user desires.

I would think any system with over 30 input parameters will suffer from the [curse of dimensionality](https://en.wikipedia.org/wiki/Curse_of_dimensionality) and determining the influence of each parameter on the outcome would be quite difficult, but that is just an off-the-cuff observation with no basis in your actual use case.

**Comment by eric-wieser** [comment]
> I'm not sure I see the connection with ragged arrays

The common theme is a difficultly distinguishing between array dimensions and lengths of `list` objects within the array - both things that would be solved if we had some kind of `object_array_with_depth(nested_list, depth=30)` call.

**Comment by DvdMgr** [comment]
> I would think any system with over 30 input parameters will suffer from the [curse of dimensionality](https://en.wikipedia.org/wiki/Curse_of_dimensionality) and determining the influence of each parameter on the outcome would be quite difficult, but that is just an off-the-cuff observation with no basis in your actual use case.

I understand you might want a hard limit on dimensionality (and I think in this case having numpy throw an error would have saved me some time) - the following comment is just to give further insight on our use case. I agree, in general exploring and making sense of a system in >30-D space would be a nightmare - in our application, however, dimensions often have size 2 (since they represent switches), or are normally kept at size 1 and are only seldom (and manually) changed. Writing code where we assign each dimension to a parameter, even if it's just to have size 1, is much more manageable and easy when compared to having to change the whole array structure to analyze the impact of one new parameter.

**Comment by mattip** [comment]
We should probably take the discussion of your use-case off this issue, feel free to ping me by mail. Just one parting comment because I can't resist: sometimes you can model states efficiently as an encoding: for instance for your case you could use a 32-bit integer and encode each binary state as a bit, saving a considerable amount of memory.

**Comment by seberg** [comment]
While this is similar to the ragged array case, I will move the milestone for now, IIRC this is slightly more annoying, and my new branches would make it trivial. If anyone feels we should look into this for 1.19, please ping me.

**Comment by seberg** [comment]
Cloisng this, gh-16200 added a visible deprecation warning in line with the ragged array warning.
