### ISSUE TITLE
DOC: broken link in f2py getting started

### ISSUE THREAD

**Issue by EverLookNeverSee** [numpy/numpy#15629]
There are 2 links in the following link that raises 404 error:

[Three ways to wrap - getting started](https://numpy.org/devdocs/f2py/getting-started.html)

Links are as follows:
[example fortran 77 code](https://numpy.org/devdocs/f2py/fib1.f)
and
[modified version of the example Fortran code](https://numpy.org/devdocs/f2py/fib3.f)

**Comment by mattip** [comment]
Thanks for the report. Fixed in gh-15633

**Comment by EverLookNeverSee** [comment]
@mattip Your welcome!
