### ISSUE TITLE
Converting data types takes longer time

### ISSUE THREAD

**Issue by Hellcat1005** [numpy/numpy#15621]
### Reproducing code example:
import numpy as np
import time

a = np.zeros((400, 400, 400), dtype=np.int32)
a[a == 0] = 255
t1 = time.time()
b = a.astype(np.float32)
print(time.time() - t1)

For numpy 1.17.3, it take 5 seconds. For numpy 1.16.4, only 0.1 seconds.

**Comment by charris** [comment]
I don't see this on my machine:
```
In [3]: %timeit b = a.astype(np.float32)                                        
22.4 ms ± 320 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]: np.__version__                                                          
Out[4]: '1.19.0.dev0+f1a247f'

```
I suspect this is another case of #15545.

**Comment by charris** [comment]
Possibly useful info:
- gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
- vmlinuz-5.4.8-200.fc31.x86_64

**Comment by seberg** [comment]
@Hellcat1005 just to be sure and narrow it down, gh-15545 suggests that this is a kernel speed issue that was fixed (probably in 4.6), could you tell what `uname -a` gives you (which kernel version you have). To help converge on the issue?
(I also cannot reproduce the slowdown, but my kernel/gcc versions are almost identical to Chucks)

**Comment by Hellcat1005** [comment]
@seberg 
uname -a gives me: Linux huiying 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bmerry** [comment]
@Hellcat1005 upgrading to kernel 4.15 fixed similar performance issues for me. Assuming you're using Ubuntu 16.04, try installing linux-image-generic-hwe-16.04.

**Comment by rossbar** [comment]
Seems very likely this is another instance of gh-15545, for which a fix was introduced in gh-15769. If the issue persists, please open a new issue with information about the system.
