### ISSUE TITLE
Unique QR decomposition (feature suggestion)

### ISSUE THREAD

**Issue by pmla** [numpy/numpy#15628]
There are multiple possible QR decompositions of a matrix A. It would be very convenient if numpy calculated a unique QR decomposition where possible. For a square matrix A: "If A is invertible, then the factorization is unique if we require the diagonal elements of R to be positive." (from [Wikipedia](https://en.wikipedia.org/wiki/QR_decomposition)). For rectangular matrices with m>n, R can be made unique but not all the rows of Q.

### Reproducing code example:

This snippet shows a unique QR decomposition:
```python
import itertools
import numpy as np
from numpy.testing import assert_almost_equal


def unique_qr(A):
    Q, R = np.linalg.qr(A)
    signs = 2 * (np.diag(R) >= 0) - 1
    Q = Q * signs[np.newaxis, :]
    R = R * signs[:, np.newaxis]
    return Q, R


rng = np.random.RandomState(seed=0)
for m, n in itertools.product(range(1, 5), repeat=2):
    A = rng.uniform(-1, 1, (m, n))
    Q, R = unique_qr(A)
    assert_almost_equal(Q @ R, A)
```

If this feature is deemed suitable for numpy I will make a PR. Perhaps as a optional parameter rather than a default?

**Comment by rossbar** [comment]
Not a lot of discussion here - perhaps the mailing list would be better? This feature proposal would perhaps be relevant for scipy as well.

**Comment by rgommers** [comment]
Shouldn't be the default it looks like, because it's slower and getting a valid decomposition in the most performant way is more important.

Can I ask what the use case is? Any well-written code should not rely on this uniqueness I'd think?

**Comment by rgommers** [comment]
Also, I think this feature probably should go into `scipy.linalg`. `scipy.linalg` should be a superset of `numpy.linalg`, making them diverge in different ways would not be good.

**Comment by melissawm** [comment]
I agree, the QR decomposition is not supposed to be unique unless one assumes positivity in the diagonal of R, and I do think this discussion fits `scipy.linalg` better. Also, many other computer algebra systems and linear algebra packages behave this way (i.e. not guaranteeing uniqueness of the QR decomposition).

**Comment by pmla** [comment]
Thank you all for your feedback. I will move the discussion to SciPy as suggested.
