### ISSUE TITLE
Negative 2^63 when broadcasting np.inf into np.array

### ISSUE THREAD

**Issue by mousomer** [numpy/numpy#15649]
numpy inf - when broadcasted into an integer Numpy Array - yields (-2 ^ 63). 

### Reproducing code example:

```python
import numpy as np
mat1 = np.array([[0,1],[2,3]])
mat2 = np.array([[0.0,1.0],[2.0,3.0]])

mat1[:, 1] = np.inf
mat2[:, 1] = np.inf

out1 = np.min(mat1)
out2 = np.min(mat2)
print(out1, out2)

```

output on my machine:
(-9223372036854775808, 0.0)

out1[0,1] is indeed -9223372036854775808

### Numpy/Python version information:

1.18.1 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

### Machine info:

Model Name:	MacBook Pro
Model Identifier:	MacBookPro15,1
Processor Name:	8-Core Intel Core i9

**Comment by eric-wieser** [comment]
`(int) inf` is implementation-defined in C, which is where numpy gets its behavior from.

**Comment by Qiyu8** [comment]
If np.inf is forcibly converted to an integer in python, I got an error "OverflowError: cannot convert float infinity to integer", while numpy is automatically converted to a mininal Integer value.

**Comment by mousomer** [comment]
Thanks @Qiyu8 . Mended the brackets.
Yes, `np.int(np.inf)` yields an Error. But the broadcasting works and converts without warning, which resulted in an annoying bug. Didn't find any relevant warning while googling this.

**Comment by eric-wieser** [comment]
Don't be tricked by `np.int` and `np.inf` - neither are numpy types, being exactly `int` and `float('inf')` respectively.

**Comment by rossbar** [comment]
Maybe a note about `np.array([np.inf]).astype(int)` would be useful? Suggestions welcome but if not then I think this can be closed as sufficiently answered.
