### ISSUE TITLE
np.frombuffer to populate existing array without duplicated copy operation

### ISSUE THREAD

**Issue by dtrawins** [numpy/numpy#15646]
I'm using python shared memory from multiprocessing package to share numpy arrays between processes.
There is a caveat, however, that populating such objects from buffer requires duplicate copy operation.
np.frombuffer creates new array and there is no option to populate existing array which is linked with a shared memory buffer.
In result, it is required to run 2 operations: deserializing the buffer content to numpy object and the second to copy elements from that array to the one linked with shared memory.
I would like to propose extending np.frombuffer to take additional argument of existing numpy array that would be populated with the content instead of creating new one.
### Reproducing code example:
```python
import numpy as np
from multiprocessing import shared_memory

input = np.ones((1,10,10,10))
b = input.tobytes()

input_shm = shared_memory.SharedMemory(create=True, size=input.nbytes)
write_array = np.ndarray(input.shape, dtype=input.dtype,buffer=input_shm.buf)

content = np.frombuffer(b,dtype=input.dtype).reshape(input.shape) # this is one copy extensive operation

write_array[:] = content[:]  # this is duplicate copy to populate shared memory buffer

restored_numpy = np.ndarray(input.shape, dtype=input.dtype,buffer=input_shm.buf)
# reading from shared memory is quick - attaching the memory block

print("restored",restored_numpy)

```
The desired behaviour would be like:
```python
np.frombuffer(b,dtype=input.dtype,target_ndarray=write_array) 
# deserialization and populating the shared memory buffer at one time

```
### Numpy/Python version information:

import sys, numpy; print(numpy.__version__, sys.version)
1.18.1 3.8.1 (default, Jan 22 2020, 16:31:49)
[GCC 9.2.1 20200111 gcc-9-branch@280154]

**Comment by seberg** [comment]
@dtrawins I have to admit I am not following what you are saying. `np.frombuffer` does not create a copy, it creates a new view into the buffer (check `content.base`). Reshape *might* copy, but in your example will not.
There is not a single operation in your code that I would think creates a new array.

**Comment by seberg** [comment]
I suppose the `b.tobytes()` operation does a copy though, what is the reason for that? If you must convert to something like a buffer, use `memoryview`?

**Comment by dtrawins** [comment]
@seberg Thank you for a quick response.
b.tobytes() is an example how to create a buffer. In real life example the buffer would be ingested from external source. So I get a user input in a serialized form and attempt to deserialize it and share between processes in numpy format. 
Shared memory is allocated different memoryview object so there is a need to copy the data.
My thinking was, that doing it in a single operation, as part of np.frombuffer conversion, should speed up the pipeline. So instead of running 2 expensive operations (frombuffer and numpy copy) maybe just one step should be faster (frombuffer populating directly the target memoryview object)?

**Comment by eric-wieser** [comment]
> So instead of running 2 expensive operations (frombuffer and numpy copy)

`frombuffer` is an `O(1)` operation, and is _not_ expensive. Only the `O(n)` copy is expensive.

**Comment by rossbar** [comment]
There is an example in the [multiprocessing documentation](https://docs.python.org/3/library/multiprocessing.shared_memory.html) on using SharedMemory objects with numpy arrays. The example is quite informative and shows how you can create numpy arrays from the shared memory buffer (without copies). The only copy in that example is the original one to populate the shared memory object - all subsequent created arrays share the buffer without creating copies.
