### ISSUE TITLE
BenchMark: How to run a single benchmark test?

### ISSUE THREAD

**Issue by Qiyu8** [numpy/numpy#15671]
I want to test the performance optimization of a function such as np.multiply，After reading the benchmark ReadMe file, I get the following command(multiply function lies in bench_avx suite):
`python runtests.py --bench-compare HEAD bench_avx`
It takes about 4 minutes to complete the test, so much time wasted in testing other functions such as sin/cos/exp, because they also lies in bench_avx, Is there any way that I could run a single multiply benchmark test without adding new suite?

BTW, I spend some time in benchmark setup, because the ReadMe file didn't tell developers that asv and virtualenv should be preinstalled by pip before benchmarking, maybe doc should be improved.

**Comment by mattip** [comment]
A PR to improve the doc would be helpful. The best people to add content are those who are new to the process since they know what is missing.

As for running a specific benchmark: I think you would have to go the `cd benchmarks; asv ...` route, but I am not sure what the proper asv syntax is.
