### ISSUE TITLE
still have shebang as #!/usr/bin/env python

### ISSUE THREAD

**Issue by sandy-lcq** [numpy/numpy#15687]
With the lastest code, many files like setup.py also have shebang as "#!/usr/bin/env python"
although we have explicitly need python3, as code in setup.py

if sys.version_info[:2] < (3, 6):
    raise RuntimeError("Python version >= 3.6 required.")

should we change shebang like "#!/usr/bin/env python3"? Because on some new distro  like fedora31,  it only install python3 and don't have a link python -> python3.
with shebang "#!/usr/bin/env python", error will reported

**Comment by charris** [comment]
On fedora31, `python` *does* point to `python3` :)
```
charris@fc [~]$ python --version
Python 3.7.6
```
That said, we should change the shebangs, or maybe even remove them.

**Comment by sandy-lcq** [comment]
maybe on desktop verison of fedora31 have python -> python3, because it installed package python-unversioned-command by default.   I  checked on fedora31 docker images,  it don't have that link.  and also according to  https://www.python.org/dev/peps/pep-0394/ , it is decided by distro that if the link will be created.  so it is possible that have host that don't have python, but only python3.

**Comment by charris** [comment]
It was in the [Fedora 31 release notes](https://www.marksei.com/fedora-31-new-features-python-2-eol-32bit-dropped/). Someone might have changed the link for some reason. Anyway, it doesn't matter much. I think we should just drop the shebangs or explicitly change them.

**Comment by seberg** [comment]
+1 for python3 version shbangs, want to create a PR?

**Comment by sandy-lcq** [comment]
create a pr for this issue

https://github.com/numpy/numpy/pull/15701

**Comment by seberg** [comment]
Thanks @sandy-lcq seems like we can close this then (the PR has been merged).
