### ISSUE TITLE
Casting from np.object --> np.string_ results in silent truncation of strings to 8 characters

### ISSUE THREAD

**Issue by alimuldal** [numpy/numpy#15686]
### Reproducing code example:

```python
In [1]: np.array(['A string with >8 characters'], np.object).astype(np.string_)
Out[1]: array([b'A string with >8 characters'], dtype='|S27')

In [2]: np.array([np.array('A string with >8 characters', np.object)], np.object).astype(np.string_)
Out[2]: array([b'A string'], dtype='|S8')  # Ouch!

In [3]: np.array([np.array('A string with >8 characters', np.object)], np.string_)
Out[3]: array([b'A string'], dtype='|S8')  # Ouch!
```
This behaviour seems to be specific to 1D object arrays containing 0D object arrays:
```python
# Outer array is 0D --> no truncation
In [4]: np.array(np.array('A string with >8 characters', np.object), object).astype(np.string_)
Out[4]: array(b'A string with >8 characters', dtype='|S27')

# Inner array is 1D --> no truncation
In [5]: np.array([np.array(['A string with >8 characters'], np.object)], np.object).astype(np.string_)
Out[5]: array([[b'A string with >8 characters']], dtype='|S27')

# Inner array is `string_` rather than `object` --> no truncation
In [6]: np.array([np.array('A string with >8 characters', np.string_)], np.object).astype(np.string_)
Out[6]: array([b'A string with >8 characters'], dtype='|S27')
```
### Numpy/Python version information:

```shell
~$ python -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.18.1 3.8.0 (default, Oct 27 2019, 15:36:55) 
[GCC 9.2.1 20190909]
```
I see the same behaviour with numpy 1.16.4 and Python 3.6.7.

**Comment by seberg** [comment]
Thanks for reporting. It is a bit more complicated than it might appear at first. You are creating a nested array in that case which throws NumPy off. Now I have accepted that NumPy should special case casts coming from `object` arrays.

Now, the real question may be whether:
```
In [19]: np.array([np.array('A string with >8 characters', np.object)], np.object)                                      
Out[19]: array([array('A string with >8 characters', dtype=object)], dtype=object)
```
is correct, when a non 0-D array is unpacked in this case– in the above that would mean:
```
Out[19]: array(['A string with >8 characters'], dtype=object)
```
which would behave correctly.

As to the behaviour of nested arrays: Yes, it is strange, but the best you could hope for is NumPy calling `str(inner_array)` which works out OKish for a 0-D array, but may also be unexpected (although arguably correct) for non 0-D arrays.

So there are two issues here, fixing either would actually "fix" the examples you gave. I am curious what to do about the first one though, should we unpack all arrays during array-coercion? I am leaning a bit to yes...

**Comment by alimuldal** [comment]
I would have expect the inner 0D array to be unpacked, i.e.
```python
In [19]: np.array([np.array('A string with >8 characters', np.object)], np.object)
Out[19]: array(['A string with >8 characters'], dtype=object)
```
since this seems consistent with how unpacking works for other dtypes. That would also imply
```python
In [19]: np.array([np.array('A string with >8 characters', np.string_)], np.object)
Out[19]: array(['A string with >8 characters'], dtype=object)
```
which also seems more reasonable to me than the current behaviour:
```
Out[19]: array([array(b'A string with >8 characters', dtype='|S27')], dtype=object)
```
but maybe there are consequences that I haven't thought through yet.

> As to the behaviour of nested arrays: Yes, it is strange, but the best you could hope for is NumPy calling `str(inner_array)` which works out OKish for a 0-D array, but may also be unexpected (although arguably correct) for non 0-D arrays.

I'd expect the result to be the same as what you'd get by recursively casting each of the object arrays to `np.string_`, then combining them all into a single array. This seems consistent with what happens when you cast nested object arrays to some other dtype, e.g.

```python
In [141]: np.array([np.array(3, np.object)], np.object).astype(float)
Out[141]: array([3.])
```

How do you think  we ending up with strings that are truncated to 8 characters?

**Comment by seberg** [comment]
Sorry for not explaining that part. When you have a nested array, NumPy uses `arr.itemsize` (or `arr.dtype.itemsize`) instead of `len(str(element))`. That is of course not really reasonable *except* for 0-D string arrays which are included...

**Comment by alimuldal** [comment]
Ah, I see, that makes sense now

**Comment by seberg** [comment]
This uses now the `str` of the included object, i.e. the "nested array" is printed:
```python
>>> np.array([np.array('A string with >8 characters', np.string_)], np.object)
array([array(b'A string with >8 characters', dtype='|S27')], dtype=object)
```
I do think this is probably about as good as it gets, but it certainly is better than the original behaviour, so I am going to close the issue.  I am not convinced unpacking 0-D arrays would be any better, but if anyone disagrees please open an issue specific to that.
