### ISSUE TITLE
PERF: Variance of complex array

### ISSUE THREAD

**Issue by dsaxton** [numpy/numpy#15684]
```python
import sys
import numpy as np

print(sys.version)
# 3.7.4 (default, Aug 13 2019, 15:17:50) 
# [Clang 4.0.1 (tags/RELEASE_401/final)]
print(np.__version__)
# 1.18.1

np.random.seed(2357)
n = 10 ** 8
arr = np.random.randn(n) + 1j * np.random.randn(n)

%timeit arr.var()
# 1.99 s ± 36 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit arr.real.var() + arr.imag.var()
# 1.25 s ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

v1 = arr.var()
v2 = arr.real.var() + arr.imag.var()

np.testing.assert_almost_equal(v1, v2)
```

It looks like summing the variances of the real and imaginary parts of a complex array is almost twice as fast as using `var` directly (and gives the same answer), so maybe there's something slowing down the calculation in this case (or maybe it makes sense to calculate the variance in this way)?

**Comment by rossbar** [comment]
I see the same thing on 2fd9ff8 though to a lesser degree:
```python
>>> %timeit arr.var()
863 ms ± 7.89 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>>> %timeit arr.real.var() + arr.imag.var()
713 ms ± 2.49 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

A closer look with `line_profiler` IDs the line calling `conjugate` as the likely culprit:

https://github.com/numpy/numpy/blob/6894bbc6d396b87464cbc21516d239d5f94f13b7/numpy/core/_methods.py#L191-L195
