### ISSUE TITLE
How does `__bytes__` work for NumPy arrays?

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#15698]
NumPy arrays support `__bytes__`, which is really great. Though after spending a bit looking at the code, it is not clear how this works. Would someone be able to provide some insight on how this works? Thanks in advance 🙂

### Reproducing code example:

```python
In [1]: import numpy as np                                                      

In [2]: a = np.arange(6, dtype="u1").reshape((2, 3), order="F"); a              
Out[2]: 
array([[0, 2, 4],
       [1, 3, 5]], dtype=uint8)

In [3]: a.tobytes()                                                             
Out[3]: b'\x00\x02\x04\x01\x03\x05'

In [4]: bytes(a)                                                                
Out[4]: b'\x00\x02\x04\x01\x03\x05'
```

### Error message:

Nothing! It works great 😄

### Numpy/Python version information:

```
1.18.1 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:03:31) 
[GCC Clang 9.0.0 (tags/RELEASE_900/final)]
```

**Comment by jakirkham** [comment]
After thinking about this a bit more, I wonder if NumPy is actually just falling back to Python to implement this through the [Python Buffer Protocol]( https://docs.python.org/3/c-api/buffer.html ). In particular [`PyBytes_FromObject`]( https://docs.python.org/3/c-api/bytes.html#c.PyBytes_FromObject ) looks relevant, which the [`bytes` constructor]( https://github.com/python/cpython/blob/7b3ab5921fa25ed8b97b6296f97c5c78aacf5447/Objects/bytesobject.c#L2535-L2536 ) calls [here]( https://github.com/python/cpython/blob/7b3ab5921fa25ed8b97b6296f97c5c78aacf5447/Objects/bytesobject.c#L2631 ).

**Comment by mattip** [comment]
`PyBytes_FromObject` eventually calls `bf_getbuffer` (on python3) which goes to `array_getbuffer`, since ndarray fills that slot [here](https://github.com/numpy/numpy/blob/v1.18.1/numpy/core/src/multiarray/buffer.c#L954). Note there is no way to fill those slots from CPython (unlike `__add__` and friends), you must use a C-extension. PyPy worked around this by creating a [bufferable](https://doc.pypy.org/en/latest/__pypy__-module.html) base class where those slots will call the python-level `__buffer__` class method which must return a memoryview.

**Comment by Harshan01** [comment]
I did some tests and found out that empty shape tuple with `int` dtype provides different values for `tobytes` and `bytes`.

```
In [1]: import numpy as np                                                                                                                                                                                  

In [2]: def test(): 
   ...:     for func in [np.ones, np.zeros, np.empty]: 
   ...:         for shape in [(), (0), (1)]: 
   ...:             for dtype in [np.int8, np.int16, np.int32, np.int64, np.float16, np.float32, np.float64]: 
   ...:                 a = func(shape, dtype=dtype) 
   ...:                 try: 
   ...:                     assert a.tobytes() == bytes(a) 
   ...:                     print(func.__name__, '\t', shape, '\t', np.dtype(dtype), '  \t\tPASS') 
   ...:                 except AssertionError: 
   ...:                     print(func.__name__, '\t', shape, '\t', np.dtype(dtype), '  \t\t\tFAIL') 
   ...:                                                                                                                                                                                                     

In [3]: test()                                                                                                                                                                                              
ones 	 () 	 int8   			FAIL
ones 	 () 	 int16   			FAIL
ones 	 () 	 int32   			FAIL
ones 	 () 	 int64   			FAIL
ones 	 () 	 float16   		PASS
ones 	 () 	 float32   		PASS
ones 	 () 	 float64   		PASS
ones 	 0 	 int8   		PASS
ones 	 0 	 int16   		PASS
ones 	 0 	 int32   		PASS
ones 	 0 	 int64   		PASS
ones 	 0 	 float16   		PASS
ones 	 0 	 float32   		PASS
ones 	 0 	 float64   		PASS
ones 	 1 	 int8   		PASS
ones 	 1 	 int16   		PASS
ones 	 1 	 int32   		PASS
ones 	 1 	 int64   		PASS
ones 	 1 	 float16   		PASS
ones 	 1 	 float32   		PASS
ones 	 1 	 float64   		PASS
zeros 	 () 	 int8   			FAIL
zeros 	 () 	 int16   			FAIL
zeros 	 () 	 int32   			FAIL
zeros 	 () 	 int64   			FAIL
zeros 	 () 	 float16   		PASS
zeros 	 () 	 float32   		PASS
zeros 	 () 	 float64   		PASS
zeros 	 0 	 int8   		PASS
zeros 	 0 	 int16   		PASS
zeros 	 0 	 int32   		PASS
zeros 	 0 	 int64   		PASS
zeros 	 0 	 float16   		PASS
zeros 	 0 	 float32   		PASS
zeros 	 0 	 float64   		PASS
zeros 	 1 	 int8   		PASS
zeros 	 1 	 int16   		PASS
zeros 	 1 	 int32   		PASS
zeros 	 1 	 int64   		PASS
zeros 	 1 	 float16   		PASS
zeros 	 1 	 float32   		PASS
zeros 	 1 	 float64   		PASS
empty 	 () 	 int8   			FAIL
empty 	 () 	 int16   			FAIL
empty 	 () 	 int32   			FAIL
empty 	 () 	 int64   			FAIL
empty 	 () 	 float16   		PASS
empty 	 () 	 float32   		PASS
empty 	 () 	 float64   		PASS
empty 	 0 	 int8   		PASS
empty 	 0 	 int16   		PASS
empty 	 0 	 int32   		PASS
empty 	 0 	 int64   		PASS
empty 	 0 	 float16   		PASS
empty 	 0 	 float32   		PASS
empty 	 0 	 float64   		PASS
empty 	 1 	 int8   		PASS
empty 	 1 	 int16   		PASS
empty 	 1 	 int32   		PASS
empty 	 1 	 int64   		PASS
empty 	 1 	 float16   		PASS
empty 	 1 	 float32   		PASS
empty 	 1 	 float64   		PASS


```

**Comment by eric-wieser** [comment]
Note that your test is misleading, `(1)` is not the tuple `(1,)` but just `1`. It turns out not to matter though.

What you're seeing is that the `bytes(int)` constructor takes precedence over the `bytes(buffer)` constructor.

If you do `bytes(np.int32(4))`, you get four zeros. If you do `bytes(np.float32(4))`, you get the bytes representation of the float.

Unfortunately there's nothing numpy can do about this.

**Comment by mattip** [comment]
Closing, I think the question was answered. Please re-open if there is a need.

**Comment by jakirkham** [comment]
Yep, thanks Matti and Eric! 😄

**Comment by eric-wieser** [comment]
If you do end up opening a bugs.python.org entry, please link it here :)
