### ISSUE TITLE
Deprecated practice described in quickstart guide

### ISSUE THREAD

**Issue by banfelder** [numpy/numpy#15699]
In the Quickstart Guide section "Indexing with Arrays of Indices"...
   https://github.com/numpy/numpy/blob/master/doc/source/user/quickstart.rst#indexing-with-arrays-of-indices
...the narrative says that "we can put i and j in a sequence (say a **list**) and then do the indexing with the **list**." Use of a list in this way is now deprecated. The sample code has been updated recently (8493ea565) to use a tuple, but the text of the description should be changed to no longer say that a list should be used.

**Comment by rossbar** [comment]
+1 - good catch @banfelder , a PR to fix the corresponding text would be welcome.

**Comment by Jimver** [comment]
I'm working on it!

**Comment by Jimver** [comment]
PR is now open at #15705
