### ISSUE TITLE
Do not put the generated import library in python tree (Trac #972)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1570]
_Original ticket http://projects.scipy.org/numpy/ticket/972 on 2008-12-19 by @cournape, assigned to @cournape._

While working on mingw-w64 support, I noticed that libpython*.a is put into C:\Python25\libs, which is not so good for at least two reasons:
- it is not regenerated when available, even if it is broken.
- we should not put anything in the python tree anyway.

**Comment by mattip** [comment]
Closing, we no longer put anything into 'Libs'. Please reopen if I misunderstood.
