### ISSUE TITLE
Jupyter Notebook .py module import numpy not defined

### ISSUE THREAD

**Issue by edwardrjtaylor** [numpy/numpy#15707]
Am importing another .py file in Jupyter Notebook 
### Reproducing code example:

```python
import numpy as np
from PythonFile import *
AnExampleFunction(params)
```
### Error message:
Points to the line calling AnExampleFunction in python code
**~/UserDirectory/PythonFile.py in AnExampleFunction(params,...)**
Points to a line in the code using np
**NameError: name 'np' is not defined** 

### Numpy/Python version information:
Python 3 miniconda Jupyter Notebook, importing a .py file from Spyder running 3.7.6

**Comment by eric-wieser** [comment]
You need to add `import numpy as np` to `PythonFile.py`

**Comment by edwardrjtaylor** [comment]
Importing numpy in both modules did not correct the issue

**Comment by rossbar** [comment]
@edwardrjtaylor this is not a `numpy`-specific issue - [the python documentation](https://docs.python.org/3/reference/executionmodel.html) might help clear this up.
