### ISSUE TITLE
np.arctan2(-0.0, -0.0) vs np.arctan2(-0, -0) Why do they return -pi and 0??

### ISSUE THREAD

**Issue by kaungsgit** [numpy/numpy#15725]
Why does np.arctan2(-0.0, -0.0) return -pi and np.arctan2(-0, -0) return 0?

### Reproducing code example:
np.arctan2(-0, -0)
Out[35]: 0.0
np.arctan2(-0.0, -0.0)
Out[36]: -3.141592653589793

```python
import numpy as np
np.arctan2(-0, -0)
np.arctan2(-0.0, -0.0)
```

**Comment by kaungsgit** [comment]
Same thing observed with math library...

**Comment by eric-wieser** [comment]
`-0` and `0` are indistinguishable, as integers have no signed zero. Floating point numbers (both numpy and pure python) are IEEE754, which _do_ have different representations for positive and negative zero.

**Comment by eric-wieser** [comment]
The behavior on floats is specified in the docs here: https://numpy.org/devdocs/reference/generated/numpy.arctan2.html?highlight=atan2
