### ISSUE TITLE
Importing the numpy c-extensions failed.

### ISSUE THREAD

**Issue by Napan0s** [numpy/numpy#15744]
Hi everyone,
I've done this many times with no problems at all.
Today i flashed a brand new raspbian lite img with the updated image from the raspberry website, everything was working fine until i decided to work in python with numpy and it gave me this error.
I've tried it both from a file and from a python3 environment in terminal.
Please help me !!

Note:
I've already tried reinstalling the library
I did it by pip3 install numpy
### Reproducing code example:

```python
import numpy
```

### Error message:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/usr/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

### Numpy/Python version information:
Python 3.7.3
Numpy-1.18.1

**Comment by mattip** [comment]
Looking at gh-11110, perhaps this would solve the problem?
```
sudo apt-get install libatlas-base-dev
```

**Comment by mitchba98** [comment]
Worked for me, thanks @mattip 

> Looking at [gh-11110](https://github.com/numpy/numpy/issues/11110), perhaps this would solve the problem?
> 
> ```
> sudo apt-get install libatlas-base-dev
> ```

**Comment by Napan0s** [comment]
Worked for me too!!! Thank you so much you made my day
