### ISSUE TITLE
Array divide assignment return 0

### ISSUE THREAD

**Issue by klam2159** [numpy/numpy#15758]
When I create a new array and perform a column division assignment by taking each element in the column and dividing it by the sum of the column, I would get 0 return for that whole column. Why is this? and how do I get it to return the exact answer? 

```python
import numpy as np
A = np.arange(15).reshape(3,5)
A[:,0] = A[:,0]/np.sum(A[:,0])
```

### Output:
array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0, 11, 12, 13, 14]])

### Numpy/Python version information:
Python 3.7

**Comment by seberg** [comment]
The array `A` has an integer datatype that cannot represent the result., so the result of `A[:, 0]/ A[:, 0].sum()` is a floating point value, when storing it back into `A` the precision is lost. Note that if you would write it as `A[:, 0] /= A[:, 0].sum()` NumPy would actually complain about the unsafe cast. However, it does the cast lossy cast silently in your code, which is equivalent to:
```
mport numpy as np
A = np.arange(15).reshape(3,5)
tmp = A[:,0]/np.sum(A[:,0])
A[:,0] = tmp  # unsafe assignment
```

**Comment by klam2159** [comment]
Thank you very much!
