### ISSUE TITLE
linalg.solve slower with more CPUs

### ISSUE THREAD

**Issue by mpariente** [numpy/numpy#15764]
This issue was first reported [here](https://github.com/craffel/mir_eval/issues/326).
### Reproducing code example:
Add this to `solve_speed_test.py`
```python
import numpy as np

# Define out of function so we don't time it.
flen = 512
G = np.random.randn(flen, flen)
D = np.random.randn(flen)

def time_solve():
    # List comprehension is to get max CPU usage.
    [np.linalg.solve(G, D) for _ in range(10)]

```
Then, time it using all CPUs 
```
python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
```
and with only one CPU 
```
taskset --cpu-list 0 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
```
These are the results I get on a 32 CPU machine:
```
mpariente@grcinq-29:tmp$ nproc --all
32
mpariente@grcinq-29:tmp$ taskset --cpu-list 0 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"                                              
10 loops, best of 3: 74 msec per loop
mpariente@grcinq-29:tmp$ python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"                                                                   
10 loops, best of 3: 1.42 sec per loop
```
This is also replicated on three others with different specs.

### Numpy/Python version information:
- Python 3.6
- Numpy 1.18.1

Maybe this is a know issue, and it depends a lot on the shape but we'd like some help on this.

**Comment by rgommers** [comment]
How did you install Python and NumPy? And can you show the output of `np.show_config()`?

**Comment by mattip** [comment]
Could you try various numbers of cpus 1, 2, 4, 8, 16

**Comment by mpariente** [comment]
> How did you install Python and NumPy? And can you show the output of `np.show_config()`?

Python was installed with anaconda3 on the three machines, NumPy was installed with pip. Here's the config on one of the machine.
```
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```



> Could you try various numbers of cpus 1, 2, 4, 8, 16

I did try, here are some samples :
```
(asteroid3.6) mpariente@grcinq-29:tmp$ taskset --cpu-list 0 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
10 loops, best of 3: 36.8 msec per loop
(asteroid3.6) mpariente@grcinq-29:tmp$ taskset --cpu-list 0 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
10 loops, best of 3: 36.9 msec per loop
(asteroid3.6) mpariente@grcinq-29:tmp$ taskset --cpu-list 0,1 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
10 loops, best of 3: 36.2 msec per loop
(asteroid3.6) mpariente@grcinq-29:tmp$ taskset --cpu-list 0,1,2,3 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
10 loops, best of 3: 25.5 msec per loop
(asteroid3.6) mpariente@grcinq-29:tmp$ taskset --cpu-list 0,1,2,3,4,5,6,7 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
10 loops, best of 3: 42 msec per loop
(asteroid3.6) mpariente@grcinq-29:tmp$ taskset --cpu-list 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
10 loops, best of 3: 282 msec per loop
```
I feel stupid to write a cpu list, do you know a simple way to give a number of CPUs? 

Thanks for the reactivity

**Comment by seberg** [comment]
You can try also `OMP_NUM_THREADS=1`, etc. since you are probably using OpenBLAS and that is one way to control how many threads openblas will use. Note that this issue probably needs to be moved to OpenBLAS, since NumPy is not involved in the decision of how many CPUs will be used.

**Comment by mpariente** [comment]
> You can try also `OMP_NUM_THREADS=1`, etc. 

Can you elaborate on the etc please? I did try `OMP_NUM_THREADS=1` but what else can I try? 

> Note that this issue probably needs to be moved to OpenBLAS, since NumPy is not involved in the decision of how many CPUs will be used.

Ok, thanks. I really don't know how NumPy interfaces with all the BLAS libraries, any way you could help with this?

**Comment by mpariente** [comment]
Just an update. Installed mkl with conda and NumPy with conda, now I get this : 
```
tmp$ taskset --cpu-list 0 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"                                                            
10 loops, best of 3: 8.01 sec per loop
tmp$ python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
10 loops, best of 3: 14.6 msec per loop
tmp$ OMP_NUM_THREADS=1 python -m timeit -s "from solve_speed_test import time_solve" "time_solve()"
10 loops, best of 3: 35.8 msec per loop
```

```
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/mpariente/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/mpariente/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/mpariente/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/mpariente/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/mpariente/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/mpariente/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/mpariente/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/mpariente/anaconda3/include']
```
This all sounds weird to me, sorry. Is it normal behavior?

**Comment by mattip** [comment]
You may be interested in the python package [threadpoolctl](https://github.com/joblib/threadpoolctl) which tries to provide a convenient API for such tasks.  I am not sure that `OMP_NUM_THREADS` is the correct way to set threads for MKL.

The lack of speedup when going from `--cpu-list 0` to `--cpu-list 0,1` might indicate that you have not disabled hyperthreading so effectively are running with the same resources in both cases. It seems your sample size is best served on your machine with 4 (effectively 2) CPUs.

> Is it normal behaviour?

Unfortunately yes. Strategies inside software like MKL or OpenBLAS for splitting tasks between CPUs may not be optimal; they need to balance task size, memory bandwidth, CPU caching and resource availability. There are no set interfaces for querying the machine across vendors and operating systems, so libraries are forced to choose generic strategies that don't always provide optimal results. Some people with high end machines end up using their own heuristics and OS-level tools like [taskset](https://linux.die.net/man/1/taskset) to partition the machine optimally. Tools like [Intel's VTune](https://software.intel.com/en-us/vtune), [AMD's uProf](https://developer.amd.com/amd-uprof/) or [Concurrency Visualizer](https://docs.microsoft.com/en-us/visualstudio/profiling/common-patterns-for-poorly-behaved-multithreaded-applications?view=vs-2019) (part of Visual Studio) can help determine when resource contention is slowing down your task. The fact that such tools exist and that people are willing to pay the license fees to use them show this is not a solved problem. Note that using GPGPUs also suffer from these types of problems, and GPU vendors also supply tools to analyze where slowdowns occur.

**Comment by mpariente** [comment]
Thank you very much for your answer, it was very informative ! 
I'll try `threadpoolctl` combined with multiprocessing then.

**Comment by mattip** [comment]
It is a shame `threadpoolctl` is not more discoverable. I will close this, please give more feedback as your work progresses (to OpenBLAS, MKL, or `threadpoolctl`) since only with feedback will the library authors be able to tweak their heuristics.

**Comment by jlucier** [comment]
Answers / responses to the below statement are welcome, but certainly not expected. I'd just like to document my experience for anyone else unfortunate enough to stumble here, and maybe get some insight into what the hell is going on haha.
____

Long story very very short, a lot of my company's signal processing seems to end up in these "BLAS" functions called by Numpy or Scipy when trying to solve matrices. We use `scipy.signals.firwin` and `scipy.signals.filtfilt` a lot.

Anyway, I was able to see a **24x speedup simply by setting `OMP_NUM_THREADS=1`**. I suspect that OpenBLAS is just trying too hard to parallelize on the relatively small inputs we're giving it? I don't have the energy to dig into this deeply, but this seems like a pretty ridiculous experience to have had.

Evidently, this issue has lurked since my company upgraded to Numpy / Scipy versions which bundled OpenBLAS. Fortunately, our overall system's performance was not dominated by how fast we can solve matrices, but clearly one particular module was heavily. We didn't have this issue when when compiling Numpy / Scipy against ATLAS or `libblas` and `liblapack`.

This leaves me with a question: why did the maintainers elect to bundle OpenBLAS with Numpy and Scipy? Is it really efficient for large inputs? Or other circumstances? I suppose I'm just blown away how much worse it is in our use case. Am I just dumb, and missed a section of the doc on performance tuning?
