### ISSUE TITLE
Add a How-To guide on storing and loading array data

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#15760]
Right now the _only_ information on storing data in NumPy arrays on disk is the bare-bones function listing in https://numpy.org/devdocs/reference/routines.io.html. All it mentions is the functions available in NumPy itself.

It would be very useful to have a How-To guide (see [NEP 44](https://numpy.org/neps/nep-0044-restructuring-numpy-docs.html) for what a How-To guide is) on data storage covering:
- the options: NumPy built-in functionality (mainly the `.npy`/`.npz` format), Zarr, HDF5 & co, Bloscpack, pickling (anything else?)
- short summary of the storage model (e.g. Zarr chunked compressed n-D arrays, optionally in groups; HDF5 filesystem-like in one file)
- performance (I/O speed, size on disk)
- portability
- dependencies
- maturity
- recommendations for what to use when

My impression is that we should use `.npy` for the really simple cases, and direct people to Zarr for pretty much anything else (related: https://github.com/zarr-developers/community/issues/28).

Data source(s) to use: 
- preferably use real-world data (we plan to produce a datasets package that we can rely on for the NumPy docs). 
- should use a regular dtype (e.g. float64), but can also show a structured dtype and an object dtype (solutions may be different for those).

_TBD: how much example code should it have, and if we do add example code with Zarr and perhaps also Pytables, should we run the code in CI so we're sure that code remains working._

My tentative answer: yes let's add example code, yes let's run CI for any code we add, TBD can we do this sensibly with Sphinx or is this a good time to start with notebooks?

**Comment by Irio** [comment]
In this how-to guide, I'd wish to read about:

* common problems that I might run into and how to tackle e.g., pickle an object and later change the source code of the class that generated it.
* when to use NumPy, when to approach from other libraries such as Pandas e.g., there's a `.xls` file with the numbers
* when to consider using a database for storage (not necessarily tell how to do it, but give a direction of what to google for finding details or link to a secondary how-to/tutorial)
* the possibility of losing information between saving & loading from a file

On formats, possibly: Apache Parquet, Protocol Buffers.

On storage model: it can be really helpful to use images here. One could create an image showing a simplified model of how NumPy maintains the data in memory; from that, how each format will store the information. It would be helpful for building a better mental model of what happens behind the scenes and understand the trade-offs.

Finally: depending on the title/keywords used, I bet people wanting to save this data in S3 or Cloud Storage may get to this how-to.

**Comment by rgommers** [comment]
Thanks for the ideas @Irio, they're quite useful. The ones I'm not sure about are:
- "using a database" - for array data the answer is never I think
- protocol buffers - those aren't really for storage on disk and I can't imagine many people making that link

> On storage model: it can be really helpful to use images here

This would be really nice if it can be worked out. Not sure it's easy to do though - the differences will be in things like metadata and compression for the various binary formats.

**Comment by melissawm** [comment]
Quick comment: I've been working on this and have the feeling it might be best done as a notebook because it will add all those dependencies (Zarr, Pytables, etc) to the NumPy build which I don't think is a good idea. However, I really think we should have a static version that doesn't run through the CI as part of our documentation (noting that we don't have any how-tos yet and this should at least be there for completeness).

**Comment by rgommers** [comment]
Agreed, thanks Melissa. We can just exclude the page from CI.

**Comment by bjnath** [comment]
If we approach this monolithically we'll end up with a doc that's too long and too treelike to be a useful how-to.  I'd propose breaking up the job this way:

1. A file "How to load and store NumPy array data," which is mostly pointers to a set of narrower how-tos. It  says something like:
>  - For the simplest solution, see "How to load and store files in X format"
> -  For large (>100 GB) datasets, see "How to load and store files in Y format"
 >-  For maximum performance, see...

2. Each of those narrow how-tos includes a line like
>  X format is optimized for x-property files, For a survey of other I/O techniques, see 'How to load and store NumPy array data'

3.  Each narrow how-to lays out a path to working code. This can include other practical information -- troubleshooting, avoiding typical mistakes, etc. But there are no explanations not directly relevant to getting working code; instead the how-to links to a separate article ( "For internals of X format...").

4. Finally, we have a single deep-dive article (with a title like "NumPy I/O in depth") that has headings for each format;  the narrow how-to's each link to a heading. The article might have a disclaimer line of its own ("This article describes the internals of file formats. For how-to information on I/O, see...").

**Comment by melissawm** [comment]
Hi @bjnath ,

That is basically how I'm approaching it. It has been very difficult to cover all the requests from here so I have split the document for the sake of readability. I'm still working on this but I do welcome ideas and a review after that!

**Comment by rossbar** [comment]
#13470 could be a source of a relevant example to illustrate the limitations of `to/fromfile`

**Comment by melissawm** [comment]
Hello, all!

I have a [draft for this How To at the numpy-tutorials](https://github.com/numpy/numpy-tutorials/pull/14) repo. I'd appreciate if you could comment and give me any feedback there. The reason why I'm not adding this as a part of the main NumPy documentation is the dependencies and the time required to build the document; I think this is much more suitable to be built separately from the main documentation. 

If you have any considerations, please comment here or over at the numpy-tutorials PR so we can move this forward. Thanks!

**Comment by bjnath** [comment]
I've written [an alternative how-to for I/O](https://github.com/numpy/numpy-tutorials/pull/15) that uses a leaner approach that may work better for how-to readers.

**Comment by mattip** [comment]
Closed by [the IO howto](https://numpy.org/devdocs/user/how-to-io.html). Please open a new issue for follow on suggestions.
