### ISSUE TITLE
zip import failed to import numpy 1.16.3

### ISSUE THREAD

**Issue by TaurusYin** [numpy/numpy#15772]
I have to use zipimport to pack the numpy package. the package is install by "pip install -t numpy==1.16.3 . " to export the pip library and then I zip the library into zip file called library.zip.

If I just insert the directory of the "library", it works but if I import the zip file, it failed and popped up the error message below

![image](https://user-images.githubusercontent.com/5126301/76924634-eecd1680-6911-11ea-8be4-260f073f8522.png)
![image](https://user-images.githubusercontent.com/5126301/76925308-fc839b80-6913-11ea-957c-a926ce08a957.png)

```python
import numpy as np
<< your code here >>

import sys
import logging
sys.path.insert(0, '/tmp/library.zip')
sys.path.pop()
print(sys.path)
import numpy as np
import zipimport
print("zip import")
importer = zipimport.zipimporter('/tmp/library.zip')
module = importer.load_module('numpy')
print(module)
```

### Error message:
> /root/test_numpy.py(6)<module>()
-> print(sys.path)
(Pdb) 
['/tmp/library.zip', '', '/home/anaconda3/lib/python36.zip', '/home/anaconda3/lib/python3.6', '/home/anaconda3/lib/python3.6/lib-dynload']
> /root/test_numpy.py(10)<module>()
-> import numpy as np
(Pdb) 
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/anaconda3/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by mattip** [comment]
I don't think you can use zipimport with packages that have c-extension modules, that is why projects like pyinstaller, py2exe, and cx_freeze exist. Closing as invalid, please reopen if there is something numpy-specific with your problem.
