### ISSUE TITLE
Assign slice with one feature to empty slice doesn't raise ValuError

### ISSUE THREAD

**Issue by grudloff** [numpy/numpy#15787]
The normal behaviour when assigning to an empty slice a non-empty slice is a ValueError because of the mismatch in dimensions. For some reason when the slice that is being asigned has only one feature it will not change the original array but nor will it throw a ValueError. Is this behaviour intentional or is it a bug?

### Reproducing code example:
This throws a ValueError:
```python
import numpy as np
A = np.ones((3,3))
A[4:5, :] = np.ones((2,3))
```
Thrown error:
```
ValueError: could not broadcast input array from shape (2,3) into shape (0,3)
```
In contrast, the following code won't throw any Error whatsoever.
```python
import numpy as np
A = np.ones((3,3))
A[4:5, :] = np.ones((1,3))*2
print(A)
```
And the original array is not modified as seen by the output of this code:
```
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
```
The same behaviour is obtained with any number of dimensions as long as the assigned slice has only one feature.

### Numpy/Python version information:
```
1.17.2 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
This is by design, and I think is explained in the comments of #15495.

**Comment by grudloff** [comment]
Thanks!
