### ISSUE TITLE
upgraded Thonny 3.2.7 cannot load numpy, even after reinstall

### ISSUE THREAD

**Issue by phr0gger** [numpy/numpy#15783]
upgraded from Thonny 3.2.6 to 3.2.7
could no import bumpy
resintalling bumpy did not help
using default interpereter, but the path looks funny. instead of 
"/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/bin/python3.7"
I see:
"/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.7/bin/python3.7/bin/python3.7"
This should resolve to the same path, but maybe it does not reliably?
### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by phr0gger** [comment]
spellchecker made "bumpy" out of bumpy

**Comment by rossbar** [comment]
Possibly related to #15670

**Comment by rossbar** [comment]
I'm going to close this due to inactivity - it seems like some potential solutions were discussed over in #15670. Feel free to reopen with current info if the issue persists.
