### ISSUE TITLE
np.fromiter crashes if NPY_RELAXED_STRIDES_DEBUG is set

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15789]
If numpy is built with `NPY_RELAXED_STRIDES_DEBUG == 1`, then fromiter uses the invalid strides.

```python
import numpy as np

NPY_RELAXED_STRIDES_DEBUG = np.ones(1, np.uint8).strides[0] != 1
assert NPY_RELAXED_STRIDES_DEBUG 

class MyIter:
    def __length_hint__(self):
        # only required to be an estimate, this is legal
        return 1  
    def __iter__(self):
        return iter([1, 2, 3])

x = np.fromiter(MyIter(), int)
# segfault
```

Tested on an approximation of master.

**Comment by seberg** [comment]
Hmmmm, I guess this may only be hit with a size hint of 1 and thus not well tested. Seems like the only fix would be to set the stride itemsize when `NPY_RELAXED_STRIDES_DEBUG` is set. (Either immediately, or whenever updating the array size). Not that I expect much usage of `NPY_RELAXED_STRIDES_DEBUG` anymore.

**Comment by eric-wieser** [comment]
Indeed, this only happens when `__length_hint__` returns `1`
