### ISSUE TITLE
ndarray.astype Call Raises SystemError

### ISSUE THREAD

**Issue by brandtbucher** [numpy/numpy#15790]
I'm currently trying to hunt down a `SystemError`, and could use some help. Basically, it occurs when attempting certain failing conversions from unicode to string arrays:

```py
import numpy as np

CHAR = "\x80"  # Anything >= 0x80, so we raise a UnicodeEncodeError.
CHAIN = 1  # How many errors will be chained together.
ITEMSIZE = 3  # dtype itemsize, anything except 0, 1, 2, or 4.

nasty = np.array([CHAR] * (128 * CHAIN + 1), dtype=f"U{ITEMSIZE}")
nasty.astype("S")
```

To recap, the error only happens with:
- A total array size of 129 or more (shape doesn't matter). Every additional 128 elements adds a new chained exception.
- A unicode itemsize not equal to 0, 1, 2, or 4.

On CPython 3.9.0a4 and NumPy 1.18.2, the above gives me:

```
UnicodeEncodeError: 'ascii' codec can't encode character '\x80' in position 0: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
SystemError: <class 'UnicodeEncodeError'> returned a result with an error set
```

I've spent quite a while digging around `dtype_transfer.c`, but I'm afraid that I can't find exactly where this is happening. My hunch is that an error raised during processing of a 128-element block isn't caught until all other blocks are finished as well. If several blocks fail, Python complains that the previous exceptions aren't being handled.

If somebody could help me figure out exactly what's going on here (or even provide a good guess), I would definitely appreciate it.

**Comment by seberg** [comment]
We have a problem in general in the ufunc and casting machinery, that errors are not properly propagated right away (gh-15411). Although, even in this context, it feels like a bug that we are not cutting the iteration short at least (leading to less, and probably even a sensible error in this case).

OK, so let me try to unravel the mystry. First of all, we have the bug I linked above. This bug kicks in only if you have multiple inner-loop casting calls. Now the thing is that in `dtype_transfer.c` (or supporting files), there is somewhere a secondary casting buffer (additionally to the typical buffer used by the iterator in ufuncs). This casting buffer must have a size of 128 (small emough to not matter, but large enough to offset the calls to the actual vectorized casting function).

This vectorized casting function can *stop* the iteration on error, but it currently *cannot* report the error out (the bug I mentioned), thus if you have more then 128 items, it will just call the inner loop once more on the next 128 items. And now that there is already an error set, you get the `SystemError` being chained.

We may be able to do a band-aid fix, the true fix will be to revise everything to properly return an error reporting from all these functions (make them non-void return)...

**Comment by seberg** [comment]
Oh, sorry. I forgot to mention, the actual casting is defined here: `https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arraytypes.c.src#L1558`
which is the function that cannot report the error out...

**Comment by eric-wieser** [comment]
These lines are where we bail out early, but don't indicate that to the caller:

https://github.com/numpy/numpy/blob/0b9b176dcef7f14f56dbd543c89e6da6c6b7b2e4/numpy/core/src/multiarray/arraytypes.c.src#L1576-L1579

**Comment by brandtbucher** [comment]
Thanks so much for your help with this!

>We may be able to do a band-aid fix...

I've never contributed to NumPy before, but would something like this be PR-worthy?

https://github.com/numpy/numpy/compare/master...brandtbucher:unsafe-cast

I basically create error-checking versions of `_strided_to_strided_contig_align_wrap` and `_strided_to_strided_contig_align_wrap_init_dest`. I figured it was better to create two new functions than to force `out_needs_api` for the existing ones.

**Comment by anirudhnarayanan** [comment]
I'd like to work on this issue. Can I proceed in doing so?

**Comment by mattip** [comment]
@brandtbucher This seems reasonable as a point of departure in light of the discussion on the issue. However I see your commit messages are not following the [suggested style](https://numpy.org/devdocs/dev/development_workflow.html#writing-the-commit-message), which I admit could be more discoverable. Not a big deal, but if you could rewrite those it would be nice. I assume your code passes the test suite, which is usually the low bar for issuing a PR.

@anirudhnarayanan it seems @brandtbucher is already making progress here. If you have something to add to the discussion please do so. Were you thinking of another approach, or have comments to @brandtbucher 's code?

**Comment by eric-wieser** [comment]
> I figured it was better to create two new functions than to force out_needs_api for the existing ones.

Instead of duplicating the code, it might make sense to create a helper function that _does_ take `out_needs_api`, and then call it from both the `safe` and normal functions.

Either way, that looks sensible enough for you to open a PR for more detailed review :).

**Comment by brandtbucher** [comment]
> However I see your commit messages are not following the suggested style, which I admit could be more discoverable.

I actually had seen that, but for some reason I assumed that format was for maintainers to use for squashed merge commits or something. I'll go ahead and fix that.
 
> Instead of duplicating the code, it might make sense to create a helper function that does take out_needs_api, and then call it from both the safe and normal functions.

Great suggestion.
