### ISSUE TITLE
pandas function expanding - in numpy

### ISSUE THREAD

**Issue by andrewczgithub** [numpy/numpy#15795]
Hi All,

Apologies but i am wondering if there is a equivalent numpy function for the pandas expanding function below -
 
```
 returns.expanding(min_periods=minperiods).sum().apply(np.exp)

    dd = np.log((cum_rets/peak_rets)) ** 2
    ulcer = np.sqrt(dd.expanding(min_periods=minperiods).sum())
```

**Comment by WarrenWeckesser** [comment]
Looks like [`np.nancumsum`](https://numpy.org/devdocs/reference/generated/numpy.nancumsum.html) is close.

Here's a Pandas example:

```
In [7]: import pandas as pd

In [8]: df = pd.DataFrame({'B': [0, 1, 2, np.nan, 4]})

In [9]: df.expanding(min_periods=2).sum()
Out[9]: 
     B
0  NaN
1  1.0
2  3.0
3  3.0
4  7.0
```

This converts the dataframe to a numpy array and applies `nancumsum`:

```
In [10]: x = df.to_numpy()
In [11]: x
Out[11]: 
array([[ 0.],
       [ 1.],
       [ 2.],
       [nan],
       [ 4.]])

In [12]: np.nancumsum(x, axis=0)
Out[12]: 
array([[0.],
       [1.],
       [3.],
       [3.],
       [7.]])
```

**Comment by WarrenWeckesser** [comment]
For reference: [`pandas.DataFrame.expanding`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.expanding.html)

**Comment by andrewczgithub** [comment]
hey @wackywendell !!

Thank you!

what if min_periods were to change.
can numpy change the min periods as well?
Best,
Andrew

**Comment by WarrenWeckesser** [comment]
> hey @wackywendell !!

Not me. 😃 

> what if min_periods were to change.

The Pandas `expanding` function has the notion of `min_periods`, which is the minimum number of elements required for the operation that is applied to the expanding set.  So if `min_periods` is 2, Pandas will set the first element of the result to `NA`; if `min_periods` is 4, the first 3 elements will be `NA`, etc.

For example,

```
In [17]: df2 = pd.DataFrame({'B': [0, -3, 1, 8, 2, np.nan, 4, -10, 12]})                 

In [18]: df2.expanding(min_periods=4).sum()                                              
Out[18]: 
      B
0   NaN
1   NaN
2   NaN
3   6.0
4   8.0
5   8.0
6  12.0
7   2.0
8  14.0
```
NumPy's `nancumsum` has no such feature.  The first element of the output (assuming it is not `nan`) is the first element of the input; the second output is the sum of the first two input  elements, and so on.  If you must emulate the Pandas behavior exactly, you could simply set the appropriate elements of the output of `nancumsum` to `nan` (assuming the input is, in fact, an array of *floating point* values).  E.g.

```
In [19]: x = df2.to_numpy()

In [20]: result = np.nancumsum(x, axis=0)

In [21]: min_periods = 4

In [22]: result[:min_periods-1] = np.nan

In [23]: result
Out[23]: 
array([[nan],
       [nan],
       [nan],
       [ 6.],
       [ 8.],
       [ 8.],
       [12.],
       [ 2.],
       [14.]])
```

**Comment by andrewczgithub** [comment]
@WarrenWeckesser !! you are a champion. 
such a clear explanation!
I will give it a try!
the issue can now be considered closed.

**Comment by WarrenWeckesser** [comment]
@andrewczgithub, I just updated my previous comment.  My first version assumed no `nan`s occurred within the first `min_periods` of beginning of the input.

**Comment by andrewczgithub** [comment]
Hi @WarrenWeckesser sorry 
but i am trying to convert he below finction into numpy and i am having trouble

' ' '
def cumulative_returns(returns, minperiods):
    return returns.expanding(min_periods=minperiods).sum().apply(np.exp)

' ' '

**Comment by andrewczgithub** [comment]
and the below one.

I am so sorry but i am pulling my hair out :(

# Define a function 'grit_index'
def grit_index(returns, minperiods):
    cum_rets = cumulative_returns(returns, minperiods).fillna(method='ffill')
    peak_rets = cum_rets.cummax()
    dd = np.log((cum_rets/peak_rets)) ** 2
    ulcer = np.sqrt(dd.expanding(min_periods=minperiods).sum())
    grit = cum_rets * ulcer ** -1
    return grit

**Comment by WarrenWeckesser** [comment]
@andrewczgithub, have you considered asking this on stackoverflow?  If you tag the stackoverflow question with `numpy` and `pandas`, your question will be visible to a much larger group with expertise in both libraries.

We generally use the numpy github issues for dealing with bug reports, and not for extended Q&A about using numpy.

**Comment by andrewczgithub** [comment]
hi @WarrenWeckesser but had not had much success.
I should be pretty close -
my attempt is below -

def cumulative_returns_numpy(returns, minperiods):
    returns=returns.to_numpy()
    data=np.nancumsum(returns)
    data[:minperiods-1] = np.nan
    data=np.exp(data.sum())
    return data

**Comment by andrewczgithub** [comment]
I did it !!!


def cumulative_returns_numpy(returns, minperiods):
    returns=returns.to_numpy()
    data=np.nancumsum(returns)
    data[:minperiods-1] = np.nan
    data=np.exp(data)
    return data


Thank you for your help @WarrenWeckesser  your a champion and a scholar

**Comment by WarrenWeckesser** [comment]
@andrewczgithub, here's another version.  This should also handle `nan`s in the beginning of the DataFrame:

```
def cumulative_returns_numpy(returns, minperiods):
    # This code assumes `returns` is a DataFrame, so
    # the following numpy array will be 2-d.
    returns = returns.to_numpy()
    data = np.nancumsum(returns, axis=0)
    too_few = np.isfinite(returns).cumsum(axis=0) < min_periods 
    data[too_few] = np.nan
    data = np.exp(data)
    return data
```

**Comment by andrewczgithub** [comment]
what a hero!! thank you so much @WarrenWeckesser
