### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._ufunc_config'

### ISSUE THREAD

**Issue by tapobrata22** [numpy/numpy#15811]
Hi, 
I was trying to install Tensorflow on my local machine and for that I created a new virtual environment named tensorflow1.  These are the codes I used. 

C:\> conda create -n tensorflow1 pip python=3.5

C:\> activate tensorflow1

(tensorflow1) C:\>python -m pip install --upgrade pip
(tensorflow1) C:\> pip install --ignore-installed --upgrade tensorflow-gpu
(tensorflow1) C:\> conda install -c anaconda protobuf
(tensorflow1) C:\> pip install pillow
(tensorflow1) C:\> pip install lxml
(tensorflow1) C:\> pip install Cython
(tensorflow1) C:\> pip install contextlib2
(tensorflow1) C:\> pip install jupyter
(tensorflow1) C:\> pip install matplotlib
(tensorflow1) C:\> pip install pandas
(tensorflow1) C:\> pip install opencv-python

After doing this, when I tried to import libraries like - 
import numpy as np 

I got the error message as -  
ModuleNotFoundError: No module named 'numpy.core._ufunc_config'

I am not able to import any single library. 

What changes need to be done ?

**Comment by mattip** [comment]
Can you paste the complete error message (as text, not as an image)? Perhaps your PATH does not begin with the path to tensorflow1, and a different python is being used? How are you trying to import the libraries?

**Comment by tapobrata22** [comment]
Hello Matt,

Yes, I think my paths are different and a different Python is being called.
Can you please guide me on how to change the paths using Jupyter or Spyder
?

Thanks for the response.

**Comment by tapobrata22** [comment]
This is the error which I am getting - 

import numpy as np
Traceback (most recent call last):

  File "<ipython-input-2-0aa0b027fcb6>", line 1, in <module>
    import numpy as np

  File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core

  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 95, in <module>
    from . import numeric

  File "C:\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 36, in <module>
    from ._ufunc_config import errstate

ModuleNotFoundError: No module named 'numpy.core._ufunc_config'

**Comment by mattip** [comment]
When you activate tensorflow1, what does `import sys; print(sys.executable)` show? The numpy you **want** to use should be somewhere close to that path. You are using a numpy in a generic `C:'Anaconda3` directory, which is probably incorrect. 

The import mechanism uses `sys.path` which is a list of directories to search for modules to import. It can be influenced by many things, including environment variables like PYTHONPATH or PYTHONSTARTUP. Perhaps one of those is set?

**Comment by mattip** [comment]
Closing. The original reporter offered no new information after 7 days. Please reopen if more help is needed.
