### ISSUE TITLE
ENH: Add a where argument to np.mean

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15818]
This would match and be implemented via the `where` argument in `np.sum`.

Most of the work here comes from implementing `np.core._methods._count_reduce_items` correctly to handle the where argument.

Perhaps worth fixing #15817 first.

**Comment by sgasse** [comment]
Hey @eric-wieser, I looked into this and came up with a way of adding the `where` argument. My approach is not to rewrite `np.core._methods._count_reduce_items`. Instead, I sum up the `where` mask along the same axis as the mean is calculated and divide by those values.

- Could you please have a look whether the general approach looks OK?
- Would this be submitted as `ENH` or `API`, given that the argument list of `np.mean` would change?
- I think that I should add tests using the `where` argument.
- I still have a failing test, `numpy.lib.tests.test_function_base.TestMedian`. The test expects more warning than are now _necessary_ I guess. Would it be OK if I change it?

On master, when I run
```
a = np.array([], dtype=float, ndmin=3)
np.median(a, axis=0)
```
this output is
```
numpy/core/fromnumeric.py:3348: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```
so a warning about the empty slice and a invalid divide. This is expected in the test.

However with my changed implementation, the empty slice is detected even earlier, so the second error never occurs:
```
numpy/core/fromnumeric.py:3355: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
```

**Comment by eric-wieser** [comment]
@sgasse, thanks for making a start on this. I recommend you open a draft PR with your changes, at first glance they look to be on the right track, and it will be easier to give you feedback in PR form.

**Comment by eric-wieser** [comment]
I think the main complexity here is being fast - summing over an array of ones is not a particularly efficient solution to the problem, although it's certainly correct.

**Comment by sgasse** [comment]
@eric-wieser sure, I just did not want to waste CI resources for a PR that I know would fail the checks.

You are right that speed is a limitation. In this commit, I catch the case that `where` is just a boolean and do not initialize the logical mask in that case. This gives a good speedup for cases where the parameter is not set explicitly. I have also added a few test cases and made sure to pass all other tests without changing them.

I think optimization potential lies in the 'in between' cases: When `where` is a broadcastable array that is much smaller than the array of which to calculate the mean. Maybe I can find an abstract way of calculating `rcount` for those cases without a mask.

Other than that, do you think there is a much faster way of calculating the mean in case a dense mask is given as `where`?

**Comment by rossbar** [comment]
Since performance is a concern, it might be worthwhile to define a few benchmarks for the benchmarking suite to evaluate the performance for various inputs to `where`. It doesn't appear that there are any benchmarks of the `where` kwarg for `sum` either, so something could be added there as well to provide a baseline for comparison.

**Comment by sgasse** [comment]
> Since performance is a concern, it might be worthwhile to define a few benchmarks for the benchmarking suite to evaluate the performance for various inputs to `where`. It doesn't appear that there are any benchmarks of the `where` kwarg for `sum` either, so something could be added there as well to provide a baseline for comparison.

Sounds good! Should it maybe be an issue in itself to add benchmarks for `np.sum`, `np.mean` and `np.var` with different `where` arguments? Or would you want it to be part of this?

**Comment by rossbar** [comment]
> Sounds good! Should it maybe be an issue in itself to add benchmarks for np.sum, np.mean and np.var with different where arguments? Or would you want it to be part of this?

It wouldn't hurt to have it as part of this PR I think, especially if it's useful in evaluating the performance of features being added (with existing ones serving as a nice baseline). I don't think it's critical though so don't let it hold up your other work!

**Comment by eric-wieser** [comment]
I don't think a benchmark is needed here, it's pretty clear that at least for the no-mask and full-mask case this is already optimal, and the intermediate cases could be optimized by a future patch.

**Comment by eric-wieser** [comment]
(however if you want to add some, don't let me deter you!)

**Comment by sgasse** [comment]
I guess I agree with @eric-wieser here that there is only a subset with substantial room for efficiency gains right now. If it's OK, I would prefer to merge these changes once they are good and move benchmarking to a new issue.

**Comment by mtsokol** [comment]
Hi! 
Ive' been porting this enhancement to `jax` and just wanted to ask if such error with `where` keyword is expected: https://github.com/numpy/numpy/issues/18552
Thank you for any advice!
