### ISSUE TITLE
Error recalling numpy using Python 3.7 on a Raspberry pi 3+

### ISSUE THREAD

**Issue by jjsr17** [numpy/numpy#15819]
I am trying to use numpy on a Rpi 3+ using Python 3.7

Python 3.7 was installed using these instructions: 

https://installvirtual.com/install-python-3-7-on-raspberry-pi/

### Reproducing code example:

running python via terminal :

import numpy as np

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages.numpy/core/__init__.py", line 24, in <module>
  from . import multiarray
File "/usr/local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
  from . import overrides
FIle "/usr/local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
  from numpy.core._multiarray_umath import (
ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version 'GLIBC_2.27' not found (required by /usr/local/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so)

During handling of the above exception, another exception occurred:

Traceback ( most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.7/site-packages/numpy/__init__.py",line142, in <module>
  from . import core
File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 54, in <module>
  raise ImportError(msg)

ImportError:

IMPORTANT : PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/usr/local/bin/python3.7"
      and that you have no directories in your PATH or PYTHONPATH that can
      interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
      https://github.com/numpy/numpy/issues. Please include details on:
      - how you installed Python
      - how you installed numpy
      - your operating system
      - whether or not you have multiple version of Python installed
      - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try 'git clean -xdf'
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on 
an existing issue about this - open a new one instead.

Original error was: /lib/arm-linux-gnueabihf/libm.so.6:  version 'GLIBC_2.27' not found (required by /usr/local/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so)

**Comment by mattip** [comment]
The numpy you are trying to use was not compiled for your platform. I am not sure those directions are the best way, since you are building python from source which means you probably will need to build any other packages you want to use from source as well. Are you sure you need python3.7 and your package manager does not provide it?

**Comment by jjsr17** [comment]
I want to update the version of python I am using. I am currently using Python 2.7. I looked up the latest version just to get the upgrade out of the way. What would you recommend? I am kind of new to this.

**Comment by mattip** [comment]
`apt-get install python3 python3-numpy` then call it using `python3 myscript.py`

**Comment by jjsr17** [comment]
Could you explain the use of that specific nomenclature to install scripts?

**Comment by rossbar** [comment]
@jjsr17 mattip's advice shows how to install python on Raspbian using the OS's built-in package manager, `apt`. 

> It worked. Thanks! Could you explain the use of that specific nomenclature to install scripts?

I'm not sure I understand this statement: if you are requesting that the advice above be added to installation instructions for NumPy, note that they are OS-specific and apply only to Debian-based Linux distributions that use the `apt` package manager.

**Comment by rossbar** [comment]
It seems like this is resolved - if not, please feel free to re-open with specific information about the remaining issue.
