### ISSUE TITLE
wrong error message 

### ISSUE THREAD

**Issue by rushabh-v** [numpy/numpy#15813]
In the below code, `bin[i]` is checked to be greater than `1` and the error message being raised is that bin[i] should be positive. Probably it should be like `bins[i] must be greater than zero.`
https://github.com/numpy/numpy/blob/91118b3363b636f932f7ff6748d8259e9eb2c23a/numpy/lib/histograms.py#L1049-L1051

I would like to open a PR to fix it if someone ensures the reality of the issue.

**Comment by eric-wieser** [comment]
Thanks for the report, but [0 is usually considered not positive](https://math.stackexchange.com/questions/26705/is-zero-positive-or-negative), so the error message is correct.

That is to say, the definition of "`x` is positive" is `x > 0`, not `x >= 0`.

If you mean the latter, you'd say _"`x` is non-negative"_.
