### ISSUE TITLE
No deprecation warning from 1.17.5 to 1.18.1 for float conversion in linspace()

### ISSUE THREAD

**Issue by moorepants** [numpy/numpy#15821]
`linspace()` has always converted floats to integers for the `num=` kwarg (for as long as I can remember). But now I'm getting a TypeError with 1.18.1. This is breaking lots of downstream code and isn't too hard to fix but is rather annoying. I'm submitting this because there seemed to be no deprecation warning for this change. Ideally things like this would have year long deprecation cycles (at least).

### Reproducing code example:

```
(numpy1.17) moorepants@garuda:four_bar_linkage(master)$ python
Python 3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 18:16:37) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.17.5'
>>> np.linspace(0.0, 1.0, num=10.0)
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])
>>> 
(numpy1.17) moorepants@garuda:four_bar_linkage(master)$ 
(numpy1.17) moorepants@garuda:four_bar_linkage(master)$ deact
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
moorepants@garuda:four_bar_linkage(master)$ python
Python 3.6.10 | packaged by conda-forge | (default, Mar  5 2020, 10:05:08) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.18.1'
>>> np.linspace(0.0, 1.0, num=10.0)
Traceback (most recent call last):
  File "/home/moorepants/miniconda3/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/moorepants/miniconda3/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

```

**Comment by eric-wieser** [comment]
The deprecation warning had been there for 6 releases, supposedly:

https://github.com/numpy/numpy/blob/4cd613a7dc3030a315ff04fcf7a93dcc5d83451d/numpy/core/function_base.py#L127-L128

It looks like your warning settings are just such that they are not shown.

**Comment by eric-wieser** [comment]
You may be interested in [PEP-565](https://www.python.org/dev/peps/pep-0565), which made a change to the default behavior of deprecation warnings.

**Comment by moorepants** [comment]
Do you happen to know how I check if my deprecation warnings are some how turned off?

**Comment by moorepants** [comment]
This works:

```
moorepants@garuda:pydy(master)$ ipython
Python 3.6.10 | packaged by conda-forge | (default, Mar  5 2020, 10:05:08) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import warnings                                                                                                                                                                                            

In [2]: warnings.warn(DeprecationWarning('test'))                                                                                                                                                                  
/home/moorepants/miniconda3/bin/ipython:1: DeprecationWarning: test
  #!/home/moorepants/miniconda3/bin/python
```

**Comment by eric-wieser** [comment]
If you use `warnings.simplefilter("always")` in your 1.17 environment, does the warning show?

If so, can you paste the exact output?

**Comment by moorepants** [comment]
It does and I don't seem to have the `PYTHONWARNINGS` variable set. Not sure why I'd have anything other than default behavior (which I thought would be to show warnings).

```
(numpy1.17) moorepants@garuda:pydy(master)$ python
Python 3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 18:16:37) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.17.5'
>>> import warnings
>>> warnings.simplefilter('always')
>>> np.linspace(0.0, 1.0, num=5.0)
<__array_function__ internals>:5: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
array([0.  , 0.25, 0.5 , 0.75, 1.  ])
>>> import os
>>> os.environ['PYTHONWARNINGS']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moorepants/miniconda3/envs/numpy1.17/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'PYTHONWARNINGS'
>>> 
```

**Comment by moorepants** [comment]
This worked too:

```
>>> warnings.simplefilter('default')
>>> np.linspace(0.0, 1.0, num=5.0)
<__array_function__ internals>:5: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
array([0.  , 0.25, 0.5 , 0.75, 1.  ])
>>> 
```

Not sure why it would be set to `ignore` on startup (if it is).

**Comment by eric-wieser** [comment]
Thanks, that confirms my suspicion. The `stacklevel` argument was wrong, so it never showed up attached to `__main__`, meaning it was filtered by default.

Sounds like we need to test all of our warnings for this mistake.

**Comment by eric-wieser** [comment]
This might be stray voltage from introducing `__array_function__` changing all the stack levels, cc @shoyer.

**Comment by moorepants** [comment]
Ok, I knew that I see deprecation warnings with other packages and didn't recall ever customizing my warning control, so good to know it isn't something buried in my system's configuration.

Thanks for looking into this and I hope that it helps.

**Comment by mattip** [comment]
> The deprecation warning had been there for 6 releases ...

So it should have showed up for 3-4 releases before any `__array_function__` and stack level changes, right?

**Comment by seberg** [comment]
@mattip yes, I just tested with 1.16.x IPython will show the warning (tested on a python2). My guess is that this is unfortunate, but probably more effort to try and go back and forth...

**Comment by rossbar** [comment]
I'm going to close this one as the specific instance seems to have been chased down, but I agree that it might be worth auditing other warnings to catch related issues.
