### ISSUE TITLE
Matrix get transposed in high rank array using tuple indexing. 

### ISSUE THREAD

**Issue by mailhexu** [numpy/numpy#15825]
For a m\*n\*p array A, if I use A[i, :, (j, k, ..)], i.e. a number for the first dim, and a tuple for indexing the last dimension, A tranposed matrix is get, which seems to be a bug.   See examle below.

### Reproducing code example:

```python
import numpy as np

a=np.random.random((2,3,3))
a[0, :, (1,2)].shape    # (2,3)   a bug?
a[0, :, np.array((1,2))]  #(2,3)  same as above
a[0, :, 1:3].shape       #(3,2)  This time it is correct.
a[0][:, (1,2)]               #(3,2)   correct.

assert a[0,:, (1,2)].shape == a[0][ :, (1,2) ].shape ,  "Confusing behavior"

```

### Numpy/Python version information:

1.18.0 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]

**Comment by eric-wieser** [comment]
This is [documented behavior](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#combining-advanced-and-basic-indexing) unfortunately, so even though it is confusing it's too late to change it.

**Comment by eric-wieser** [comment]
In this case, numpy interprets `a[0, :, (1,2)]` as `a[np.array([0, 0]), :, np.array([1,2])]`.

Once it's performed this transformation, it's lost the information telling it where to insert the new axis, so it just puts it at the start.

**Comment by mailhexu** [comment]
Thanks for clarifying!
