### ISSUE TITLE
numpy for python 3 on macOS Catalina

### ISSUE THREAD

**Issue by ishanpkhrel** [numpy/numpy#15828]
Hi, 
 I am trying to have a stable python3 environment on my mac running on macOS Catalina. Catalina comes with python 2.7 standard, but I want to use python3. I installed python 3 with homebrew, and then used homebrew to install numpy as well.
I deleted python 2.7 and currently, I have python 3 installed on my mac.
```python
which python
```
/usr/bin/python
 and 
``` python
python --version
```
Python 3.7.3
But every time I try and run a macro with numpy included, I get this:
```python -c 'import numpy' ```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
I know that i'm not linking numpy to python3. I can't find any solution online that gives me a straightforward approach. I have to say that i'm a newbie interms of macOS code structure.

**Comment by anirudh2290** [comment]
Have you installed numpy : `pip3 install --user numpy` ?

**Comment by rossbar** [comment]
Your output from `which python` is likely a link, you may need to do a bit of link-following to figure out which version `/usr/bin/python` is actually pointing to; try `ls -l /usr/bin/python`

**Comment by ishanpkhrel** [comment]
@anirudh2290 , with the ```python pip3 install --user numpy``` I get 
```Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (1.18.1)```
but however when i look at the symlink,
``` which python``` is actually pointing to 
```/usr/bin/python@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7```
but I made sure that i changed the symlink to point to python3!!!
Currently, ```which python3``` gives me:
```/usr/local/bin/python3```
which then points to :
```/usr/local/bin/python3@ -> ../Cellar/python/3.7.7/bin/python3```
I am very confused... I know this is a linking issue, but I am not that well versed interms of where things are in the macOS framework with any confidence. Any help would be great guys! 
Thanks to @rossbar as well!

**Comment by mattip** [comment]
Why not just save yourself trouble and explicitly use `python3` whenever you want to invoke python3? Also, especially when you are getting started, I would recommend using `python3 -m pip` over `pip` or `pip3` since then you are sure you are using the correct pip version (notice the `-m` : that means "import pip and call it")

**Comment by rossbar** [comment]
I'm not familiar with `homebrew` or how package management works on macs generally. One alternative you might consider is using Python virtual environments (via a tool like `virtualenv` for example) or the `conda` package manager. These are nice solutions for decoupling from your OS's built-in package manager.

**Comment by ishanpkhrel** [comment]
Thanks guys, It seems that I already have numpy for python3 installed and running via python3 works. 
THe reason I wanted to change the symlinks was because I have python 2.7 as well as python3 installed, and all dependencies (numpy and matplotlib) are downloaded for both. I have a mac with 128Gb and didn't wanna take up the hard disk that much. So I wanted to uninstall python 2.7 and keep everything to python 3. I guess i'll have to understand more about homebrew and how it manages packages to understand how to unlink everything related to python 2.7. For now, I have a working solution. Thanks

**Comment by rossbar** [comment]
Hopefully the discussion helped!
