### ISSUE TITLE
VS code cannot find 'numpy' after installation

### ISSUE THREAD

**Issue by lilygeorge** [numpy/numpy#15823]
After I install  numpy in path (C:\Users\hp\AppData\Local\Programs\Python\Python38>pip install numpy),  I still have the same error (error: No module named 'numpy) when run simple program with numpy, how can fix this please??! 
I use python with VS code and the output for this command 
pip install numpy
Requirement already satisfied: numpy c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (1.18.1)

**Comment by rossbar** [comment]
@lilygeorge can you be more specific in how you installed NumPy. Did you install to a Python environment using e.g. `conda` or `virtualenv`? If so, you should make sure that the environment in which you installed NumPy is activated in your VS code session.

**Comment by mattip** [comment]
Closing, the original reporter was not responsive after 7 days. If needed please reopen with more information.
