### ISSUE TITLE
error on "NumPy for Matlab users" web page

### ISSUE THREAD

**Issue by tomkilpatrick** [numpy/numpy#15837]
I found an error on the following web page:
https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html

The equivalent of y=x(:) (Matlab) in Numpy is y = x.flatten('F'), not y = x.flatten(). Matlab uses Fortran-ordering, rather than the C-style ordering that is default in Numpy.

**Comment by seberg** [comment]
True, might be good to add. Alternatively, maybe in the `Notes` column is even enough. Want to give it a try by opening a PR?

**Comment by pdebuyl** [comment]
Proposal: add the sentence 

    To obtain a the same data ordering than in Matlab, use x.flatten('F').

in the notes.

**Comment by tomkilpatrick** [comment]
I would suggest changing the table entry to 
`y = x.flatten('F')`

And then the Notes could say something like 
`Note that x.flatten() will read the array with C-style ordering, which is the default in NumPy`

I haven't submitted a pull request before; could you point me toward the html file that needs to be edited? Sorry for my ignorance.

**Comment by pdebuyl** [comment]
@tomkilpatrick the process for contributing to NumPy is documented at https://numpy.org/devdocs/dev/index.html

After the standard "building NumPy" part with the git process, you should check the section on building the documentation: https://numpy.org/devdocs/dev/index.html#building-docs

I already prepared a branch with my proposal. If @seberg is ok with your version you can either submit a PR or I can do it as well.
