### ISSUE TITLE
Question about the sourse code

### ISSUE THREAD

**Issue by xw547** [numpy/numpy#15833]
I am actually learning about numerical analysis now and curious about the way that you do matrix multiplication, as the professor mentioned in the lecture that it can be very hard for us to do something as good as you do. 

Is it possible for me to have the source code for the function np.matmul? It would be of great help for me.

Thank you so much for your time and attention.

**Comment by rkern** [comment]
The source code within numpy is not especially optimized. numpy relies on external optimized linear algebra libraries for the speed of matrix multiplication, like [OpenBLAS](https://github.com/xianyi/OpenBLAS). Reading the source code of OpenBLAS will not be very enlightening. These are _very_ optimized algorithms, these days, and it's hard to discern the high-level strategy from the low-level implementation. However, there is [reasonably good documentation](https://github.com/xianyi/OpenBLAS/wiki/Developer-manual#optimize-gemm) that explains the strategies at a higher level ("GEMM" stands for "GEneral Matrix Multiplication"). [Here's the paper](https://www.cs.utexas.edu/~flame/pubs/GotoTOMS_revision.pdf) linked to in that section. [Other good references can be found from the FLAME project.](http://www.cs.utexas.edu/~flame/web/publications.html)
