### ISSUE TITLE
DOC: numpy.ma.sort and copying behaviour

### ISSUE THREAD

**Issue by adeak** [numpy/numpy#15841]
I started out thinking I've found a docbug but I'm becoming less sure. The problem is that [the documentation of `numpy.ma.sort`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.sort.html) ([devdocs version](https://numpy.org/devdocs/reference/generated/numpy.ma.sort.html#numpy.ma.sort)) says
> Sort the array, in-place
> [...]
> Returns: `sorted_array`

Whereas the behaviour seems to be the opposite:
```py
>>> import numpy as np
>>> arr = np.arange(5)[::-1]
>>> np.ma.sort(arr)
array([0, 1, 2, 3, 4])
>>> arr
array([4, 3, 2, 1, 0])
```

The weird thing is that I've found https://github.com/numpy/numpy/issues/1966 which suggests that until 2010 the docs had mentioned a copy and the behaviour was mutating, and the docstring was subsequently fixed. However looking at the git blame even [in commit 5cb370e923 from 2008](https://github.com/numpy/numpy/blob/5cb370e9234582f62231384c26a426301dad3331/numpy/ma/core.py#L2859) I can see
```py
from numpy import array as narray
# [...]
def sort(...):
    a = narray(a, copy=True, subok=True)
```
This seems to me that even in 2008 it should have returned a copy, which makes the linked docbug issue very confusing. What am I missing?

Ultimately I think this is a docbug, because `np.ma.sort` should match `np.sort` which copies (and is documented as such), whereas the corresponding instance methods should sort in-place.

**Comment by seberg** [comment]
You are right, the documentation is incorrect. The issue is that the function `np.ma.sort()` does and should copy, while the method `np.ma.MaskedArray.sort()` does not, and should not, copy.

The issue is that the documentation for both function is identical (the function just uses the methods documentation), which is incorrect with respect to the in-place behaviour.

**Comment by adeak** [comment]
@seberg thanks for the feedback. I was expecting some deep magic deciding which docstring to use, but then I noticed
```py
sort.__doc__ = MaskedArray.sort.__doc__
```

The question is whether the rest of the docstring could/should be copied over to `np.ma.sort` instead. I've never had to use masked arrays before, but it seems to me that `np.ma.sort` falls back on `np.ma.MaskedArray.sort` (after the copy). So unless there are some subtleties with the `axis` kwarg then I suspect the two docstring _can_ agree. But then they have to be maintained independently.

And I've just noticed that some links to other sort functions are missing in "See also" and the "Notes" (see doc links in my first post). If these are missing as an oversight then these could also be fixed at the same time.

**Comment by vrakesh** [comment]
I looked at other sort method/function doc strings, they do not seem to deviate from the actual functionality. Will create a PR to correct this.

Guess this line should do to fix this particular doc

```python
sort.__doc__ = '\n'.join(["Returns a sorted array."]
                         + MaskedArray.sort.__doc__.splitlines()[2:])
```

**Comment by adeak** [comment]
@vrakesh I'm not sure that monkeypatching the docstring like that is a good idea. Seems very fragile to me. If we keep an explicit copy of the docstring the risk is having a stale docstring down the line (if the API of `MaskedArray.sort` changes), but at least we're guaranteed to have an unbroken (if stale) version of a docstring at all times.

**Comment by vrakesh** [comment]
@adeak I do agree with your point and see the validity. But the function is always going to wrap around the class method, with only change being creating a copy. Shouldn't we just maintain one doc string , rather than duplicate 90% of it. I am open to either approach.

**Comment by adeak** [comment]
Yes, the fact that it's a thin wrapper is the reason why you might want to not copy the docstring. But what I meant by "fragile" is this: what if three years from now the first sentence of `MaskedArray.sort`'s docstring changes, and the header no longer occupies a single line? We'd cut off some of that docstring and have a silently broken docstring for `numpy.ma.sort`.

It's not very likely that this would happen to the docstring, but it's a nontrivial decision to make. That's also why I've been waiting for developer feedback.

**Comment by vrakesh** [comment]
@adeak Agreed, it's not trivial,  let's wait for more folks to chime in

**Comment by seberg** [comment]
I dunno, I think obviously broken is better than silently outdated. If you wish, add a test or assert mayb.

**Comment by eric-wieser** [comment]
You could use `.split("\n\n", 1)[0]` to throw away the first paragraph.
