### ISSUE TITLE
Public functions in np.core.records with improperly formatted docstrings

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#15853]
Some public functions defined in `numpy/core/records.py` and accessible via the `np.rec` namespace have incomplete docstrings that do not fully comply with the [numpydoc standard](https://numpydoc.readthedocs.io/en/latest/format.html).

For example:

https://github.com/numpy/numpy/blob/43ca3a5bd882dc69bca0fa777113e6821c9f44e0/numpy/core/records.py#L596-L609

At the very least, this docstring is missing the `Parameters` and `Returns` sections as well as the `Examples` header above the examples.

A listing of functions that this issue applies to in `numpy/core/records.py`

 - `fromarrays`
 - `fromrecords`
 - `fromstring`
 - `fromfile`
 - `array`

Additionally (perhaps a separate issue), there are two other functions which are "public" (i.e. name does not start with an underscore) though from context it appears that they may be intended only for internal use within the `records` submodule. They also do not have proper docstrings:
 - `find_duplicate`
 - `get_remaining_size`

### Numpy/Python version information:

1.19.0.dev0+0b9b176 3.8.2 (default, Feb 26 2020, 22:21:03)

**Comment by rgommers** [comment]
After gh-15899 was merged, `fromstring` and `array` are left, others were fixed.

**Comment by anirudh2290** [comment]
also would be nice to have some examples for `np.record` .

**Comment by a1pha** [comment]
Can I work on this issue? I have reviewed the numpydoc standard and would like to help contribute.

**Comment by rossbar** [comment]
Please feel free @a1pha !

**Comment by tohabyuraev** [comment]
Sorry for the two commits. A small mistake when working with GitHub.

**Comment by rossbar** [comment]
Docstrings have now been added to each of the listed functions.
