### ISSUE TITLE
DOC: older documentation show up in google searches

### ISSUE THREAD

**Issue by mesejo** [numpy/numpy#15857]
There is an error in the documentation of [numpy.broadcast.iters](https://docs.scipy.org/doc/numpy/reference/generated/numpy.broadcast.iters.html#numpy-broadcast-iters), the following code is taken from the documentation.

### Reproducing code example:

```python
import numpy as np
x = np.array([1, 2, 3])
y = np.array([[4], [5], [6]])
b = np.broadcast(x, y)
row, col = b.iters
print(row.next(), col.next())
```
### Error message:

> 
> Traceback (most recent call last):
>   File "/path/to/main.py", line 7, in <module>
>     print(row.next(), col.next())
> AttributeError: 'numpy.flatiter' object has no attribute 'next'

### Numpy/Python version information:

> 1.17.4 3.6.9 
> (default, Nov  7 2019, 10:44:02) 
> [GCC 8.3.0]

This can be fixed by using the built-in function [next](https://docs.python.org/3/library/functions.html#next).

```import numpy as np

x = np.array([1, 2, 3])
y = np.array([[4], [5], [6]])
b = np.broadcast(x, y)
row, col = b.iters
print(next(row), next(col))

**Comment by eric-wieser** [comment]
Well spotted. Patch welcome!

**Comment by mattip** [comment]
That is an outdated version of the documentation. Please see the [current page](https://numpy.org/devdocs/reference/generated/numpy.broadcast.iters.html#numpy-broadcast-iters). Did you reach the documentation via a link that should be fixed?

**Comment by mesejo** [comment]
@mattip This is the [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.broadcast.iters.html#numpy.broadcast.iters) to the broken documentation.

**Comment by mattip** [comment]
Yes, that is an outdated link, the documentation now lives on https://numpy.org/docs. I meant to ask how did you arrive at that link: via a search result, via a link from some other document which should be updated to point at https://numpy.org/docs, via a tutorial that should also be updated, ...

**Comment by mesejo** [comment]
I googled numpy broadcast

**Comment by mattip** [comment]
Indeed, google (and duck-duck-go) do not return numpy.org docs, only scipy.org ones.  I wonder if we should remove those links from scipy.org?

**Comment by mattip** [comment]
Changing the title

**Comment by rossbar** [comment]
I think this is at least partially addressed by warning banners, e.g. numpy/doc#7

**Comment by rossbar** [comment]
Closing this now that numpy/doc#7 is in. If there are any other specific ideas on how this situation could be improved for users coming from search engines, please open a new issue to discuss.
