### ISSUE TITLE
Numpy import

### ISSUE THREAD

**Issue by HorusCRM** [numpy/numpy#15862]
I have very short program (2 lines).
It runs well in terminal.
It failed when I call it from C# 

**My Python Code**
import numpy
print("hello")

C# program and Python program are in the same folder.
NO MORE TO SAY

```python
import numpy as np
<< your code here >>
```

**Comment by HorusCRM** [comment]
I work with Visual Studio Code 1.43.2 and with Anaconda4 packages (python coming from it)

**Comment by eric-wieser** [comment]
Please show the error message, which you've left empty in your issue description.

**Comment by HorusCRM** [comment]
The message is

C:\Users\actemium\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\actemium\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\actemium\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\actemium\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testTorch.py", line 4, in <module>
    import numpy
  File "C:\Users\actemium\anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\actemium\anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\actemium\anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Le module spécifié est introuvable.

**Comment by eric-wieser** [comment]
That warning on the first looks like the issue, although it may just be that your conda environment is not activated.

**Comment by HorusCRM** [comment]
Yes !
When before running the dotnet program, I do
C:/Users/actemium/anaconda3/Scripts/activate
(base) "myProgramFolder">conda activate base

Its works, thank you !

Does it signify that when I will need to run the final program on none developper machine, It will be necessary to have anaconda installed ?

**Comment by eric-wieser** [comment]
Your issue was that you were using anaconda but not activating it. If you don't use anaconda, but instead use a different python installation, you will not need to activate anaconda.
