### ISSUE TITLE
Concatenate with sequence that contains empty sequences. (Trac #988)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1586]
_Original ticket http://projects.scipy.org/numpy/ticket/988 on 2009-01-22 by trac user kelson, assigned to unknown._

Howdy,

After searching for this defect, perhaps nobody else has been bothered
by this behaviour, but has anybody else noticed:

```
concatenate ( [[1],[2],[3],[4]] ).dtype = int32

concatenate ( [[1],[2],[3],[]] ).dtype = int32

concatenate ( [[],[2],[3],[4]] ).dtype = float64
```

I have a lot of old-style Numeric stuff that likes to concatenate lists
of indices which then were used with take [which does not like floats]. So
below [in theory] I attach my attempt at a patch so that empty items in the sequence are
not used to influence the common type that is used by PyArray_ConvertToCommonType.

Maybe it is of some value, or maybe I didn't do this in a kosher manner and
someone else has an idea of where things should be rethought for this defect?

Cheerio.

**Comment by eric-wieser** [comment]
On master, `concatenate ( [[1],[2],[3],[]] ).dtype` changed from `int32`, to `float64`

**Comment by WGautier** [comment]
Still seeing this on 1.15.0.

```
>>> np.concatenate(([],[1])).dtype
dtype('float64')
>>> np.concatenate(([2],[1])).dtype
dtype('int64')
```

**Comment by eric-wieser** [comment]
Yes, returning float64 is correct

**Comment by WGautier** [comment]
Technically true, but it's not the most intuitive result from a simple concatenate function.

I will work around it.

**Comment by eric-wieser** [comment]
The best way to avoid this kind of problem is to work with arrays rather than lists where possible, and specify explicit dtypes in the few times when you need to convert.

**Comment by mattip** [comment]
Closing
