### ISSUE TITLE
DOC: misleading description in https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.lstsq.html

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#15874]
This starts by saying "Solves the equation a x = b", which (except in special cases) it does not do.  Perhaps better is to start with "Computes a vector x that minimizes the Euclidean 2-norm || b - a x ||^2.  If the minimal 2-norm is zero, then we have ax=b."

**Comment by mattip** [comment]
The [newer documentation](https://numpy.org/devdocs/reference/generated/numpy.linalg.lstsq.html) is different. Is there a reason you are using the old, outdated documentation?

**Comment by pdebuyl** [comment]
The current documentation is here:

https://numpy.org/doc/1.18/reference/generated/numpy.linalg.lstsq.html#numpy.linalg.lstsq

The text is

> Solves the equation a x = b by computing a vector x that minimizes the squared Euclidean 2-norm \| b - a x \|^2_2. The equation may be under-, well-, or over-determined (i.e., the number of linearly independent rows of a can be less than, equal to, or greater than its number of linearly independent columns). If a is square and of full rank, then x (but for round-off error) is the “exact” solution of the equation.

The link that you mention refers to the documentation of an older version of NumPy (1.13.0), which will probably not be updated.

For information, NumPy now publishes the documentation on its own website: numpy.org

**Comment by keithbriggs** [comment]
Ok, but the newer docs still say "Solves the equation ax=b".    Like most people, I use the docs which google finds.   There is no easy way to know that they are not the latest.

Keith


________________________________

**Comment by pdebuyl** [comment]
I find the current wording careful. It states directly and in the same sentence that "solves" "by computing...".

The google problem is annoying. The NumPy developers have no control on Google's results of course, but should keep this in mind.

**Comment by keithbriggs** [comment]
I still think my wording is better: "Computes a vector x that minimizes the Euclidean 2-norm || b - a x ||^2. If the minimal 2-norm is zero, then we have ax=b".  The obsolete pages could all have a warning added at the top, maybe with a link to the latest.

**Comment by pdebuyl** [comment]
For the specific wording, I leave it to the maintainers who ultimately take the decisions.

I agree that we should put a warning on the older documentation.

**Comment by melissawm** [comment]
Not a maintainer, but I agree with @keithbriggs from a mathematical point of view.

**Comment by seberg** [comment]
Sure, doc improvements are always welcome. Would be good to have a PR with a suggestion. I personally would hope we can find something simpler than "Computes a vector x that minimizes the Euclidean 2-norm || b - a x ||^2. If the minimal 2-norm is zero, then we have ax=b".

Not that it shouldn't mention all of that, but even if it is a bit misleading, saying "solves ax=b", or maybe "Tries to (approximately) solve solve ax=b" seems much simpler to me. Some users may already be confused by "2-norm", although the only solution to that would be mentioning that only after "in the least squares sense" or so.

**Comment by keithbriggs** [comment]
-exp(iπ).

**Comment by pdebuyl** [comment]
@keithbriggs do you have an interest in preparing a pull request? Else, I'll do it.

**Comment by keithbriggs** [comment]
You can probably do it quicker than me.
Thanks!


________________________________

**Comment by pdebuyl** [comment]
PR submitted #15920
