### ISSUE TITLE
DOC: missing doc of numpy.ma.apply_over_axes in API list.

### ISSUE THREAD

**Issue by AtsushiSakai** [numpy/numpy#15889]
This is a minor issue about documentation.

The function numpy.ma.apply_over_axes is implemented. 
https://github.com/numpy/numpy/blob/4092a9e160cc247a4a45724579a0c829733688ca/numpy/ma/extras.py#L408-L429

However, its documentation is missing in API list of official doc:
Masked array operations — NumPy v1.11 Manual 
http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/routines.ma.html 
It should be in the Miscellanea section.

### Numpy/Python version information:
Numpy:1.11.0

**Comment by eric-wieser** [comment]
That docs link is very outdated and not the official one.

This is already fixed here: https://numpy.org/devdocs/reference/generated/numpy.ma.apply_along_axis.html

**Comment by AtsushiSakai** [comment]
@eric-wieser Oh. I'm sorry my link was wrong. 
However, the link still looks missing in your link:
https://numpy.org/devdocs/reference/routines.ma.html#miscellanea

I mean missing numpy.ma.apply_over__axes, not numpy.ma.apply_along_axis.

**Comment by eric-wieser** [comment]
Apologies, I misread that
