### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.random.bit_generator'

### ISSUE THREAD

**Issue by Qiyu8** [numpy/numpy#15888]
After update to the latest development code.The error occurs when import numpy.
### Reproducing code example:
```python
import numpy as np
```
### Error Traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/Qiyu/numpy/numpy/__init__.py", line 151, in <module>
    from . import random
  File "/usr/Qiyu/numpy/numpy/random/__init__.py", line 184, in <module>
    from .bit_generator import SeedSequence, BitGenerator
ModuleNotFoundError: No module named 'numpy.random.bit_generator'

**Comment by mattip** [comment]
did you `git clean -xfd` befoure building?

**Comment by Qiyu8** [comment]
@mattip Thanks for your quick reply, forgot to clean git repository.
