### ISSUE TITLE
DEP: Check integer array indices when result/`subspace` is empty

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#15898]
Quote from @jbrockmendel 

This matches the numpy behavior:

```
arr = np.array([]).reshape(0, 0)
nd3 = np.random.randint(5, size=(2, 2, 2))
arr[nd3] = 0
```

This may be a numpy bug as well cc @seberg ?

---

The above should validate the integer index and raise an error due to out of bound values. I am aware that there are issues with this when there are multiple array-indices which have an empty *broadcast* shape. But, I am not (at least anymore) aware of it when the slicing "subspace" is empty as opposed to the "advanced indexing" part being empty, and we should probably fix that.

(had to put the subspace word, it used to be a running gag with Jaime :))

**Comment by eric-wieser** [comment]
Mind linking to the issue you're quoting? Not sure why github doesn't do that automatically...

**Comment by seberg** [comment]
Forgot, and I could not move it here because of the different organization, the original issue is: https://github.com/pandas-dev/pandas/issues/32896 where pandas removed some internal checks and the NumPy ones do not pick this up.

**Comment by seberg** [comment]
Ah, so the reason is that `mit->size` is the full size, so it is `0` in the case. With a single (not multiple) indices, this causes the loop to never be called at all. Probably just checking `NpyIter_GetSize(mit->outer)` instead could be a workaround.

**Comment by seberg** [comment]
Hmmm, it seems pre NumPy 1.9 behaviour was to ignore incorrect indices when they broadcast away (or maybe even when the result is empty, I would have to dig up such an ancient NumPy version). I am considering tagging on a DeprecationWarning for now, and we just enable index checking always fairly rapidly, it is arguable just buggy behaviour (I am not sure why I replicated the old behaviour, it may have just been because I noticed that).
