### ISSUE TITLE
Np.Select add additional input type such as dict

### ISSUE THREAD

**Issue by matthewmturner** [numpy/numpy#15902]
Hi, I'm a huge fan of np.select() - it makes it very easy to categorize records in a table when there are a lot of potential categories.  The only issue I have with it is that you have two separate lists to track, conditions and choices.  This isnt so bad when dealing with only a handful of conditions but as the number grows it becomes difficult to track which list item in conditions corresponds to which list item in choices.  I end up having to add a comment for each line of my conditions to say which choice it generates.    I was wondering if we could alternately supply a dictionary/tuple (or any type that allows you to see the condition and choice in proximity to each other) where the keys are the choice and the values are the conditions.  
### Reproducing code example:

```python
import numpy as np

#Current
conditions = [x == 1, x == 2, x == 3]
choices = ["One", "Two", "Three"] 
np.select(conditions, choices)

#Proposed
logic = {
    "One": x==1,
    "Two": x==2,
    "Three": x==3
}

np.select(logic)
```

**Comment by seberg** [comment]
Since we accept any iterable currently, I am not sure how easy it is to switch over, but maybe possible.

However, at least the code you gave above, can be written as well (and maybe more dogmatic) using:
```python
# chocies is a lookup table(lut)
choices = np.array(["Zero", "One", "Two", "Three"])
result = choices[x]
```
I realize that maybe your actual use case you cannot map `x` to integers.

**Comment by matthewmturner** [comment]
Hi - thanks for the feedback.  Youre correct that my uses cases cannot map to integers.  Do you think the dict like input option could be looked into?

thx much.

**Comment by rossbar** [comment]
More examples of potential use-cases might help engender some discussion here, as the original example is clearly well-covered in NumPy.

**Comment by oliver-pola** [comment]
@matthewmturner If your problem is "end up having to add a comment for each line of my conditions to say which choice it generates", you could use that dictionary for nice code in that part, and then call select like this?

```
np.select(logic.values(), logic.keys())
```

**Comment by matthewmturner** [comment]
@oliver-pola you're totally right, thanks!
