### ISSUE TITLE
No module found: 'numpy.core_multiarray_unmath'

### ISSUE THREAD

**Issue by jimporeilly** [numpy/numpy#15919]
I receive this error "No module found: 'numpy.core_multiarray_unmath'" when I execute my app.  The app is a C++ application running in VS 2019. The code below is an embedded python script.  The original script runs fine in Jupyter Notebook.  I get no further than calling import numpy. I have reloaded newer and older versions of Python and Tensorflow and numpy. Have not found a combination that works. setting the Py_SetPath() makes no difference. My environmental variables are all correct. I only have one install of Python. Deleted all traces of earlier ones that I know off.  Because the script works in Jupyter notebook, I am wondering if VC2019 could be the issue?

### Reproducing code example:

        Py_Initialize();
	//Py_SetPath(cStr);

	pModule = PyImport_AddModule("__main__"); //create main module
	PyRun_SimpleString(stdOutErr.c_str()); //invoke code to redirect

	PyRun_SimpleString("import numpy \n");
	
	//PyRun_SimpleString("import tensorflow \n");
	//PyRun_SimpleString("import cv2 \n");

	//PyRun_SimpleString("def prepare(filepath): IMG_SIZE = 40 img_array = cv2.imread(filepath) 
        new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE)) print(filepath) return 
          new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3)");
	//PyRun_SimpleString("return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3) \n");
	
	//PyRun_SimpleString( "model = tensorflow.keras.models.load_model('stake.model') " );
	
	//PyRun_SimpleString("prediction = model.predict([prepare('c:/visiondata/all/100.bmp')]) " );
	//PyRun_SimpleString("print(prediction)");
         Py_Finalize();

### Error message:
  No module found: 'numpy.core_multiarray_unmath

### Numpy/Python version information:

>>> print(sys.version)
3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
>>> print(numpy.__version__)
1.18.2
>>>

**Comment by charris** [comment]
How did you install NumPy? Are you running Conda? Do you have multiple Python installations?These problems are invariably installation or environment related, the tricky bit is to figure out just which problem you have and, in order to do that, we need more detailed information.

**Comment by jimporeilly** [comment]
No I did not use Conda. Installed everything through a cmd window w/administrative rights. Many times.

**Comment by charris** [comment]
Using pip? Do you have more than one Python installation? More than one NumPy installation? Does `_multiarray_umath` actually exist?

**Comment by jimporeilly** [comment]
There is a file in the python /site-packages/core/python/_multiarray_unmathcp36....pyd that is close. Yes I am using pip. Before I reloaded an older version of Python, I searched for any traces of the previous install and deleted. Tried different versions of Pip too. What I have not done is load Anaconda and go from there.

**Comment by charris** [comment]
I assume this was NumPy 1.18 64 bit? I see a `_multiarray_umath.cp36-win_amd64.pyd` (not unmathcp36` in the wheel that looks like it belongs in `numpy/core` (not /site-packages/core).  I don't run windows, so don't know how pip installs, but that looks fishy. Can you try upgrading pip using the same python you want to use? `python -m pip install --upgrade pip` then try again?

@mattip does that look familiar? IIRC, windows has moved the recommended installation location of *.pyd files.

**Comment by charris** [comment]
Can you run numpy without tensorflow and the rest? Sometimes those programs can mess up the path.

**Comment by mattip** [comment]
The original error message contains valuable information about which pytohn is being used and where the numpy is being loaded from.  As @charris states, using `python -mpip install` is preferable to using `pip install`. What do you mean "different versions of pip"? Can you copy-paste (as text) the error message (extra points for formatting it as code using the "<> insert code" command from the toolbar) and the exact set of commands you used to install?

As the error message states, do you have PYTHON related environment variables set? What does 
```
set PY
```

show from your DOS command window?

**Comment by jimporeilly** [comment]
Below is the error message in full.  I have PYTHONHOME  and PYTHONPATH  and PATH set to "C:\program files\python36" and no other installs. Set PY returns: "environmental variable PY not set". I upgraded pip. I have also tried all this without having tensorflow installed, getting the same error.  I am in Debug mode and will try Release tomorrow.

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "C:\Projects\snoBot3\x64\Debug\Vision.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by mattip** [comment]
Note you are running `C:\Projects\snoBot3\x64\Debug\Vision.exe` not `C:\program files\python36\python.exe`. I suspect `Vision.exe` is searching for a different c-extension library than the one in `C:\Program Files\Python36\lib\site-packages\numpy\core`. Is `Vision.exe` some kind of wrapper? You should not have `PYTHONHOME` nor `PYTHONPATH` set at all unless you absolutely must, those values make a mess of managing different python environments.

**Comment by jimporeilly** [comment]
C:\Projects\snoBot3\x64\Debug\Vision.exe. is the location of my VS2019 executable. I can move it elsewhere and run it. But where? Should I be looking at some <path> command for the C++ environment and not Python?  I will look at this.  Odd that set PY returns "environmental variable PY not set" when PYTHONHOME is populated. I will also try with them deleted.

**Comment by jimporeilly** [comment]
OK. I deleted all Python Environmental variables. No change. I moved my executable to the Python directory. No change. But I recompiled my app in Release mode and the error went away. So it was VS2019 Debug interfering with the c-extension library locations. Onto other problems.  THANKS FOR ALL THE HELP!

**Comment by mattip** [comment]
So you were probably running some kind of debug python version, which searches for debug c-extension modules rather than the release ones. If you want to do that, you need to recompile the entire stack of libraries you want to import. A better strategy is to compile in release with minimal optimization and debug info, then you can get the best of both worlds.

**Comment by anirudh2290** [comment]
Looks like @jimporeilly issue has been resolved. Closing.
