### ISSUE TITLE
重装numpy后import失败

### ISSUE THREAD

**Issue by chenqingzhu2019** [numpy/numpy#15912]
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangqiudan/.jumbo/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/wangqiudan/.jumbo/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/wangqiudan/.jumbo/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by /home/wangqiudan/.jumbo/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so)

**Comment by mattip** [comment]
are you running on a distribution that uses musl not glibc?

**Comment by chenqingzhu2019** [comment]
> are you running on a distribution that uses musl not glibc?

how to check it?

**Comment by mattip** [comment]
how did you install python and numpy?

**Comment by mattip** [comment]
try `ld --version`

**Comment by chenqingzhu2019** [comment]
> how did you install python and numpy?
python : I forgot
numpy   :pip install numpy

> try `ld --version`

GNU ld (GNU Binutils) 2.23.2
Copyright 2012 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

**Comment by chenqingzhu2019** [comment]
> how did you install python and numpy?

i just want to update my numpy version，after update，i cannot import it，so i try reinstall numpy，but error again
