### ISSUE TITLE
ImportError: Something is wrong with the numpy installation can't fix this

### ISSUE THREAD

**Issue by cervantes-loves-ai** [numpy/numpy#15910]
### Reproducing code example:

```
<< sudo python extract_C3D_feature.py 
 >>
```
Traceback (most recent call last):
  File "extract_C3D_feature.py", line 7, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 91, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/usr/local/lib/python2.7/dist-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

**Comment by Manvi07** [comment]
A similar problem is discussed [here.](https://stackoverflow.com/questions/54715835/numpy-is-installed-but-still-getting-error/55652317) This might help.

**Comment by anirudh2290** [comment]
@cervantes-loves-ai can you list the installed numpy versions. As @Manvi07 mentioned, removing previously installed numpy installed versions and installing a new version might help.

**Comment by rossbar** [comment]
Closing this as it seems very likely that the problem lies in system configuration rather than something specific to numpy, and it's been a while since there's been any active discussion. If the issue persists, feel free to reopen with more specific information about the system, installation method, etc.
