### ISSUE TITLE
Negative binomial sampling bug when p=0

### ISSUE THREAD

**Issue by adamgayoso** [numpy/numpy#15913]
Negative binomial sample when p=0:

`np.random.negative_binomial(1, 0)`

![Screen Shot 2020-04-05 at 6 43 43 PM](https://user-images.githubusercontent.com/10859440/78516502-a36a9300-776e-11ea-9e65-bb073d2a730f.png)

I believe the output should be 0 in this case.

1.18.2 3.7.3 (default, Mar 31 2019, 11:50:42) 
[Clang 10.0.1 (clang-1001.0.46.3)]

**Comment by WarrenWeckesser** [comment]
> I believe the output should be 0 in this case.

If `p`, the probability of "success", is 0, then the expected number of failures before encountering 1 success is infinite.

The return value is `-2**63 = -9223372036854775808`, i.e. the most negative 64 bit signed integer.  Perhaps a better behavior is to raise an exception.  That is, simply don't allow `p = 0`.

Note: the issue exists in the new random code, too:
```

In [6]: import numpy as np                                                      

In [7]: np.__version__                                                          
Out[7]: '1.19.0.dev0+0f6a3aa'

In [8]: rng = np.random.default_rng()                                           

In [9]: rng.negative_binomial(1, 0, size=6)                                     
Out[9]: 
array([-9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, -9223372036854775808])
```

**Comment by WarrenWeckesser** [comment]
P.S. @adamgayoso, thanks for reporting the issue!

**Comment by adamgayoso** [comment]
Looking at the NB pmf on the [numpy docs](https://docs.scipy.org/doc/numpy-1.17.0/reference/random/generated/numpy.random.Generator.negative_binomial.html#numpy.random.Generator.negative_binomial)
![Screen Shot 2020-04-05 at 7 42 16 PM](https://user-images.githubusercontent.com/10859440/78518524-90a78c80-7775-11ea-85ee-50d5f859f48f.png)
Then plugging in `p=0` should mean that `P(0; n, p=0)` should be 1, if you assume 0^0=1, which appears to be the case when defining things like the binomial distribution?

For what it's worth, I tried this in pytorch and the return value is 0

```python
>>> from torch.distributions import NegativeBinomial
>>> NegativeBinomial(10000, probs=0).sample()
tensor(0.)
```

**Comment by WarrenWeckesser** [comment]
> ...if you assume 0^0=1 and n>0

0^1 is 0.

> For what it's worth, I tried this in pytorch ...

Unfortunately, there is not a standardized way to parameterize the negative binomial distribution.  PyTorch and NumPy use different conventions.  There is a short note about this issue in the box on the right side of the [wikipedia page about the negative binomial distribution](https://en.wikipedia.org/wiki/Negative_binomial_distribution) that is worth reading.

In both PyTorch and NumPy, `p` is the probability of success.  The difference is that in PyTorch, [`NegativeBinomial`](https://pytorch.org/docs/stable/distributions.html#negativebinomial) draws samples from the

>  distribution of the number of successful independent and identical Bernoulli trials before `total_count` failures are achieved.

NumPy draws samples from the distribution of the number of failures until `n` successes are encountered.  If `p` is 0, then a success is never encountered, so the probability distribution is 0 for any finite number of failures.  In other words, it is not really a meaningful distribution.

I'm preparing a pull request that will requiring `p > 0` for NumPy's `random_binomial` method.

**Comment by adamgayoso** [comment]
Thanks for catching that. I'll admit it's very confusing going back and forth between wikipedia, pytorch, and numpy!!

**Comment by WarrenWeckesser** [comment]
Pull request to disallow p=0 in `Generator.negative_binomial`: https://github.com/numpy/numpy/pull/15914

**Comment by WarrenWeckesser** [comment]
@adamgayoso, the pull request gh-15914, in which the `negative_binomial` method of [`numpy.random.Generator`](https://numpy.org/devdocs/reference/random/generator.html#numpy.random.Generator) is changed to disallow p=0, has been merged.  With the master branch of numpy (and using the new [numpy.random](https://numpy.org/devdocs/reference/random/index.html) API), we have:

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.19.0.dev0+e78d076'

In [3]: rng = np.random.default_rng()

In [4]: rng.negative_binomial(1, 0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-d61ac7f10aa5> in <module>
----> 1 rng.negative_binomial(1, 0)

_generator.pyx in numpy.random._generator.Generator.negative_binomial()

_common.pyx in numpy.random._common.disc()

_common.pyx in numpy.random._common.check_constraint()

ValueError: p <= 0, p > 1 or p contains NaNs
```
 Note, however, that the function `numpy.random.negative_binomial` has *not* also been updated.  That function is part of the "legacy" random API.  The legacy code is usually only updated if a bug causes Python to crash.  If you are writing new code, you should use the new API.
