### ISSUE TITLE
Numpy module not found

### ISSUE THREAD

**Issue by kanak8278** [numpy/numpy#15927]
### Reproducing code example:

```python
import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by kanak8278** [comment]
I have already installed numpy module

**Comment by anirudh2290** [comment]
How did you install numpy ? What environment are you installing it in ? Requires more information to be able to help. 

Request to maintainers to tag this "00-Question"

**Comment by rgommers** [comment]
> Request to maintainers to tag this "00-Question"

Done. I also sent you an invite for the triage team, so you have permissions to add labels yourself.

**Comment by anirudh2290** [comment]
> > Request to maintainers to tag this "00-Question"
> 
> Done. I also sent you an invite for the triage team, so you have permissions to add labels yourself.

thank you!

**Comment by anirudh2290** [comment]
This has been idle for a few days. Closing, please feel free to comment/reopen if this is still an issue.
