### ISSUE TITLE
NUMPY

### ISSUE THREAD

**Issue by sanathk12** [numpy/numpy#15937]
I have download numpy from command prompt,I am getting error as 
RuntimeError: Broken toolchain: cannot link a simple C program
So,I downloaded numpy package from anaconda prompt and replaced numpy files from anaconda file to pycharm file.But is also giving error
 Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "C:\Users\Admin\Desktop\.PyCharmCE2019.3\pap.py\venv\Scripts\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

So what should I do know ?

**Comment by rgommers** [comment]
> `RuntimeError: Broken toolchain: cannot link a simple C program`

You cannot get that error from `import numpy`, only if you're trying to build NumPy from source. Please install with `pip` or `conda`.

**Comment by eric-wieser** [comment]
@rgommers, I think you missed this bit:

> So,I downloaded numpy package from anaconda prompt and replaced numpy files from 
anaconda file to pycharm file.But is also giving error

Either way, this is not supported. You can't take numpy installed for one python configuration and expect a manual file copy to make it work in a different one.

**Comment by sanathk12** [comment]
> @rgommers, I think you missed this bit:
> 
> > So,I downloaded numpy package from anaconda prompt and replaced numpy files from
> > anaconda file to pycharm file.But is also giving error
> 
> Either way, this is not supported. You can't take numpy installed for one python configuration (conda) and expect a manual file copy to make it work in a different one (whatever pycharm is using).

How can I download numpy into pycharm  if I am getting error as 
RuntimeError: Broken toolchain: cannot link a simple C program

**Comment by sanathk12** [comment]
> > `RuntimeError: Broken toolchain: cannot link a simple C program`
> 
> You cannot get that error from `import numpy`, only if you're trying to build NumPy from source. Please install with `pip` or `conda`.

Installing Numph from pip giving error as 
RuntimeError: Broken toolchain: cannot link a simple C program

**Comment by rgommers** [comment]
You can't "download numpy into pycharm". What you do is `conda install numpy` (if Python is from Anaconda) or `pip install numpy` (otherwise). And then you point your IDE at the right Python version. Never copy anything around. Please read an introductory tutorial on how to get started using Python.
