### ISSUE TITLE
Unbelievably Slow---Element wise operation(exp) to 3D array.

### ISSUE THREAD

**Issue by xichaoqiang** [numpy/numpy#15933]
I want to use a three-dimensional matrix to get rid of the for loop in my calculations.

I compared the processing speed of numpy and cupy to a (2000,1000,50) size matrix.

 Found that numpy's element operation is too slow. How should I improve?

### Reproducing code example:

```python
import numpy as np
import cupy as cp
from time import time

m=2000
n=1000
k=50;

temp_fv=np.random.rand(m,n,1)
temp_s=np.random.rand(m,1,k)+1j*np.random.rand(m,1,k)
temp_x=np.arange(k)
temp_x=temp_x[None,None,:]
GPU_C=1
t0=time()  
if GPU_C==1:
    temp_fv=cp.asarray(temp_fv);
    temp_x=cp.asarray(temp_x);
    tmp=(cp.pi*2*1j)*(temp_fv*temp_x)       
    print(time()-t0)
    temp_fv = cp.exp(tmp)#nf*nv*nx
    print(time()-t0)
else:
    tmp=(np.pi*2*1j)*(temp_fv*temp_x)       
    print(time()-t0)
    temp_fv = np.exp(tmp)#nf*nv*nx
    print(time()-t0)
```

### Result message:
```
step1 run with cupy =  0.004988670349121094 s
step2 run with cupy =  0.009970903396606445 s

step1 run with numpy =  1.8999218940734863 s
step2 run with numpy =  11.546433925628662 s
```

### Numpy/Python version information:

1.14.3 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)

**Comment by grlee77** [comment]
CUDA supports asynchronous execution of kernels, so you may need to add a `cp.cuda.Device().synchronize()` prior to printing the times in the GPU case.  I expect this will increase the number some, although it should still be much faster than NumPy.
(If you have a recent version of CuPy you can try the `cupyx.time.repeat` utility that operates somewhat like IPython's `%timeit`, but takes care of the synchronization for you)

For the particular case of `np.exp`, #15648 may help with this particular computation in a future release if you have a CPU supporting AVX-512. You may also be able to get a faster computation now if you can tolerate switching to single precision for the arrays.

**Comment by xichaoqiang** [comment]
Thanks for your reply.The type of my array is complex64.

I'm not sure how to switchthem to single precision.

**Comment by mattip** [comment]
Use numpy1.18 and then specify the desired dtype in the calls: 

```
rng = np.random.default_rng(); 
temp_fv=rng.random(size=(m, n, 1), dtype=np.float32)
...
temp_x=np.arange(k, dtype=np.float32)
...
```

or, if you are stuck with pre-1.18 numpy, use array.astype('float32') to change the dtype

**Comment by xichaoqiang** [comment]
Thanks. Is there 32bit complex data type?Because my data type is complex

**Comment by rossbar** [comment]
@xichaoqiang `complex64` is the single-precision complex type, with a 32-bit float to represent the real and imaginary components.

**Comment by xichaoqiang** [comment]
Thanks for your reply.I think I can close this issue.
