### ISSUE TITLE
random.choice changes types of values

### ISSUE THREAD

**Issue by mitar** [numpy/numpy#15935]
If I have a list of Python values, and I use `numpy.random.choice`, I would assume that I would get back one of the values in the list, as-is. But in fact, `numpy.random.choice` converts values to numpy types.

### Reproducing code example:

```python
import numpy as np
import random
print(type(random.choice([True, False])) is bool)  # True
print(type(np.random.choice([True, False])) is bool)  # False
```

This is really surprising and can lead to strange issues for us where for example then sampled value cannot be JSON serializable. `np.random.choice` has additional arguments like `replace`, so it is not simply a question of replacing `random.choice`. But ideally, it should behave on lists like `random.choice`.

### Numpy/Python version information:

```
1.18.2 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
```

**Comment by eric-wieser** [comment]
Numpy functions are intended to work on numpy arrays, not on lists. If you pass a list, we'll convert it to a numpy array for you.

If you do the conversion yourself, you can tell numpy not to attempt to convert the elements of the list:
```python
l = [True, False]
arr = np.array(l, dtype=object)  # keep objects unchanged
assert type(np.random.choice(arr)) is bool
```

**Comment by mitar** [comment]
Thanks. I think that would be useful to document though. I will make a PR to add a comment about that. It would have helped me debug this issue a lot.

**Comment by mitar** [comment]
I made: https://github.com/numpy/numpy/pull/15969
