### ISSUE TITLE
RMS (root mean squared error) calculation is missing from numpy package

### ISSUE THREAD

**Issue by dcsaba89** [numpy/numpy#15940]
RMS (root mean squared error) is a frequently used statistical measure.

I would be happy to work on it to be added to numpy.

**Comment by rossbar** [comment]
This has been suggested before; generally the consensus is against adding functionality that can be easily composed from existing numpy functions. See #12579 for additional discussion.

Thanks for sharing the idea!

**Comment by dcsaba89** [comment]
Sorry for asking but what makes 'mean' function different? mean is a very commonly used function which can be simply derived from sum and count. In my opinion, mean is used  very frequently to make it a standalone function in numpy. The same stands for pivoting in pandas (I know that is a different package), but pivot_table is also a function that could be implemented by the users again and again by using simple existing functionalities like aggregate, transform, filters, etc.

**Comment by eric-wieser** [comment]
`np.mean` already exists.

Please look at the discussion in the issue @rossbar links to, rather than repeating it here.

**Comment by eric-wieser** [comment]
Duplicate of #12579
