### ISSUE TITLE
Php Python import numpy

### ISSUE THREAD

**Issue by HorusCRM** [numpy/numpy#15945]
During a call to a Python Module from php an error occured

Executing Python Code within a terminal runs well
Executing with Php code raise the error

```python Code
import sys
import numpy as np
print(sys.path)
```
Php Code
<?php
   $res = exec( "python.exe pyModule.py", $var); 
or
   $res = exec( "C:\\users\\actemium\\anaconda3\\python.exe pyModule.py", $var);
?>
### Error message:
C:\users\actemium\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\users\actemium\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\users\actemium\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\users\actemium\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Le module sp�cifi� est introuvable.

**Comment by HorusCRM** [comment]
Php Code is 
<?php
    $res = exec( "python.exe pyModule.py", $var); 
?>
or
<?php
    $res = exec( "C:\\users\\actemium\\anaconda3\\python.exe pyModule.py", $var);
?>

**Comment by HorusCRM** [comment]
$res = exec( "python.exe pyModule.py", $var);                 
    $res = exec( "C:\\users\\actemium\\anaconda3\\python.exe pyModule.py", $var);

**Comment by mattip** [comment]
You need to [activate your anaconda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment) before starting python.

You should do something like 
```
conda activate <myenv>
```
where you replace `<myenv>` with your environment name, commonly `base` so
```
conda activate base
```
Only when it is active can you run your php scripts

**Comment by HorusCRM** [comment]
I understand, but I will need to call the php file via an Internet Browser. Apache will not launch conda envirionnement. But perhaps, it is impossible.

**Comment by mattip** [comment]
Then you should not use conda. Use a "vanilla" python and use your platform package installer or `pip install` instead.

**Comment by HorusCRM** [comment]
I understand, thanky you. 
I will check soon. 
Waiting this, I close the issue.

**Comment by mattip** [comment]
Also note that it can be tricky to get Apache to use the python you want it to. Make sure you print `sys.executable` when testing your setup, this will show you the actual exe used by Apache

**Comment by HorusCRM** [comment]
Ok ok, thank you again. 
Running "Conda activate base" in command line works fine.
I also succeed running it inside a Visual Studio Code Terminal.
Regarding Apache, I understand that it will be a challenge, It is too early, so I will not promise something on it to my requesters. It will be a good surprise for them, it is not a mandatory request.
