### ISSUE TITLE
Receive '_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError' when trying to execute embedded python program with numpy

### ISSUE THREAD

**Issue by jayurbain** [numpy/numpy#15948]
Receive '_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError' when trying to execute embedded python program with numpy.

Any direction would be greatly appreciated. Thanks, Jay

If I remove numpy from the program, everything works. It appears the correct libraries are not be properly linked.

Original error was: /home/jay/anaconda3/envs/registration/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

### Reproducing code example:
# cython_cheat.txt

mkdir registration
cd registration

# create environment
$ conda create -n registration python=3.7
$ conda activate registration
$ conda install scikit-image
$ conda install matplotlib
$ conda install -c conda-forge opencv
$ conda install cython
$ conda install gcc_linux-64
$ conda list

# create pyx and setup files and past in the following code for each file
$ nano hello.pyx

    # cython: language_level=3
    import numpy as np
    print(__name__)

    if __name__ == "__main__":
        print("Hi, I'm embedded.")
        for i in np.arange(10):
            print(i)
    else:
        print("I'm being imported.")

$ nano setup.py

    from setuptools import setup
    from Cython.Build import cythonize

    setup(
        ext_modules = cythonize("hello.pyx")
    )

# generate c file
$ python -m cython hello.pyx --embed

# verify you have a hello.c file
$ ls -lt

# retrieve compiler CFLAGS and linker LDFLAGS
# get CFLAGS
$ ~/anaconda3/envs/registration/lib/python3.7/config-3.7m-x86_64-linux-gnu/python-config.py --cflags
# get LDFLAGS
$ ~/anaconda3/envs/registration/lib/python3.7/config-3.7m-x86_64-linux-gnu/python-config.py --ldflags

# get conda python path and set PYTHONPATH and PYTHONHOME to something like the following
$ which python

$ export PYTHONPATH='/home/jay/anaconda3/envs/registration/lib/python37.zip:/home/jay/anaconda3/envs/registration/bin/python:/home/jay/anaconda3/envs/registration/lib:/home/jay/anaconda3/envs/registration/lib/python3.7/site-packages'
$ export PYTHONHOME='/home/jay/anaconda3/envs/registration'

#  compile and link
$ x86_64-conda_cos6-linux-gnu-gcc -c hello.c -o hello.o -I/home/jay/anaconda3/envs/registration/include/python3.7m -I/home/jay/anaconda3/envs/registration/include/python3.7m -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
$ x86_64-conda_cos6-linux-gnu-gcc hello.o -L/home/jay/anaconda3/envs/registration/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lpthread -ldl -lutil -lrt -lm

$ ./a.out # get this result by removing numpy from program
  __main__
Hi, I'm embedded.

### Error message:

Error:
---------------------------------------------
(registration) jay@dlbox1:~/registration$ ./a.out
Traceback (most recent call last):
  File "/home/jay/anaconda3/envs/registration/lib/python3.7/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/jay/anaconda3/envs/registration/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/jay/anaconda3/envs/registration/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/jay/anaconda3/envs/registration/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello.pyx", line 2, in init hello
    import numpy as np
  File "/home/jay/anaconda3/envs/registration/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/jay/anaconda3/envs/registration/lib/python3.7/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/home/jay/registration/a.out",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /home/jay/anaconda3/envs/registration/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError

----------------------------------------------------

### Numpy/Python version information:

Cython     0.29.16            
numpy      1.18.2

>>> import sys, numpy; print(numpy.__version__, sys.version)
1.18.2 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0]

**Comment by mattip** [comment]
Since you are using Anaconda, you may need to activate your environment before running `a.out`

**Comment by jayurbain** [comment]
I was able to solve the problem.

When I issued the following python-config command for --ldflags it did not return all of the required libraries:
~/anaconda3/envs/registration/lib/python3.7/config-3.7m-x86_64-linux-gnu/python-config.py --ldflags

It was missing"
/home/jay/anaconda3/envs/registration/lib

Here is the correct link command:
x86_64-conda_cos6-linux-gnu-gcc embedded -L/home/jay/anaconda3/envs/registration/lib -L/home/jay/anaconda3/envs/registration/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lpthread -ldl  -lutil -lrt -lm -Xlinker -export-dynamic

Also, it is unnecessary to set PYTHONPATH and PYTHONHOME.

Reverse engineering this Makefile was what I needed:
https://github.com/cython/cython/blob/master/Demos/embed/Makefile

Thanks,
Jay
