### ISSUE TITLE
np.corrcoef produces incorrect outputs with very large arrays

### ISSUE THREAD

**Issue by lampinen** [numpy/numpy#15943]
np.corrcoef appears to fail with very large inputs (1-d array with about 5 billion entries). Correlating an array with itself does not give a correlation matrix of all 1s, as expected, but rather returns off-diagonal entries near 0. Calculating the correlation manually does seem to work. The problem seems consistent with 5 billion entries in the array, but at 1 billion it appears to work correctly (at least the one time I tried the smaller size).

This is on a system with 250 GB of memory, and np is only using around half of that, and is not giving a memory error or anything, so I don't think it is running out of memory. I therefore suspect it is some sort of overflow. However, I wouldn't

I recognize that fixing this might not be worth the effort it would take, given that relatively few users may encounter it, but it would be nice if it raised a warning or something rather than silently giving incorrect results. It took me quite a while to track down why my results suddenly made no sense with a new (larger) dataset.

Apologies if I missed another bug about this, or some documentation.

### Reproducing code example:

```python
import numpy as np

np.random.seed(0)
x = np.random.random([5000000000])  # a large 1-d array

print(np.corrcoef(x[:1000], x[:1000]))  # works as expected, returns [[1., 1.], [1., 1.]]
print(np.corrcoef(x, x))  # returns incorrect matrix with off diagonal entries near 0


# manually calculating appears to work
x = x - np.mean(x)
std = np.std(x)
print(np.mean((x / std) * (x / std)))
```

### Numpy/Python version information:

Python 3.6.9 and Numpy 1.16.2

**Comment by seberg** [comment]
The issue has to do with different numerical accuracy depending on various code paths taking during summation (basically your code happens to be more exact). Possible that could be improved for corrcoef specifically, but generally, you have just too many elements to expect the sum to have reasonable accuracy without using some more stable methods. E.g. if you subtract the mean first, and then run `np.corrcoef` again, you will get a more accurate answer.

**Comment by mattip** [comment]
Closing, since there is little we can do inside of numpy to mitigate the rounding errors. Please reopen if there are other opinions.
