### ISSUE TITLE
Broken toolchain: cannot link a simple C program，build numpy 1.16.0 on AIX6.1

### ISSUE THREAD

**Issue by absoult-dev** [numpy/numpy#15958]
bash-5.0# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/4.8.5/lto-wrapper
Target: powerpc-ibm-aix6.1.0.0
Configured with: ../gcc-4.8.5/configure --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --with-local-prefix=/opt/freeware --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --with-cloog=no --with-ppl=no --disable-libstdcxx-pch --enable-__cxa_atexit
Thread model: aix
gcc version 4.8.5 (GCC) 
bash-5.0# python -V
Python 2.7.16

Python 2.7.16 is down from AIXTOOLS，installed by smitty installp. When I run：python setup.py install，the errors turned out：

Running from numpy source directory.

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install numpy`   (last NumPy release on PyPi)

blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

blis_info:
customize UnixCCompiler
  libraries blis not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_3_10_blas_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries tatlas not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_3_10_blas_info:
customize UnixCCompiler
  libraries satlas not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_blas_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_blas_info:
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

accelerate_info:
  NOT AVAILABLE

/software/numpy-1.16.0/numpy/distutils/system_info.py:625: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
blas_info:
customize UnixCCompiler
  libraries blas not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

/software/numpy-1.16.0/numpy/distutils/system_info.py:625: UserWarning: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  self.calc_info()
blas_src_info:
  NOT AVAILABLE

/software/numpy-1.16.0/numpy/distutils/system_info.py:625: UserWarning: 
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  self.calc_info()
  NOT AVAILABLE

/bin/sh: svnversion:  not found.
non-existing path in 'numpy/distutils': 'site.cfg'
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_lapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_clapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas,lapack not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /opt/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /opt/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /opt/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /opt/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /opt/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /opt/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /opt/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /opt/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

lapack_info:
customize UnixCCompiler
  libraries lapack not found in ['/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

/software/numpy-1.16.0/numpy/distutils/system_info.py:625: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
lapack_src_info:
  NOT AVAILABLE

/software/numpy-1.16.0/numpy/distutils/system_info.py:625: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
  NOT AVAILABLE

/opt/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
running build_src
build_src
building py_modules sources
building library "npymath" sources
get_default_fcompiler: matching types: '['ibm', 'gnu', 'gnu95']'
customize IBMFCompiler
Could not locate executable xlf90
Could not locate executable g77
customize GnuFCompiler
Could not locate executable f77
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
Could not locate executable /opt/lib/python2.7/config/ld_so_aix gcc -bI:/opt/lib/python2.7/config/python.exp
Found executable /usr/bin/ld
customize Gnu95FCompiler
customize Gnu95FCompiler using config
C compiler: gcc -lgcc -DNDEBUG -O -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts

compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/include/python2.7 -c'
gcc: _configtest.c
exec(): 0509-036 Cannot load program /opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/4.8.5/cc1 because of the following errors:
        0509-130 Symbol resolution failed for /usr/lib/libgmp.a(libgmp.so.10) because:
        0509-136   Symbol _GLOBAL__AIXI_shr_o (number 2) is not exported from
                   dependent module /opt/freeware/lib/libgcc_s.a(shr.o).
        0509-136   Symbol _GLOBAL__AIXD_shr_o (number 3) is not exported from
                   dependent module /opt/freeware/lib/libgcc_s.a(shr.o).
        0509-026 System error: Error 0
        0509-192 Examine .loader section symbols with the
                 'dump -Tv' command.
failure.
removing: _configtest.c _configtest.o
Traceback (most recent call last):
  File "setup.py", line 415, in <module>
    setup_package()
  File "setup.py", line 407, in setup_package
    setup(**metadata)
  File "/software/numpy-1.16.0/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "build/bdist.aix-6.1/egg/setuptools/__init__.py", line 129, in setup
  File "/opt/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/software/numpy-1.16.0/numpy/distutils/command/install.py", line 62, in run
    r = self.setuptools_run()
  File "/software/numpy-1.16.0/numpy/distutils/command/install.py", line 56, in setuptools_run
    self.do_egg_install()
  File "build/bdist.aix-6.1/egg/setuptools/command/install.py", line 109, in do_egg_install
  File "/opt/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.aix-6.1/egg/setuptools/command/bdist_egg.py", line 161, in run
  File "/opt/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/software/numpy-1.16.0/numpy/distutils/command/egg_info.py", line 26, in run
    self.run_command("build_src")
  File "/opt/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/software/numpy-1.16.0/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/software/numpy-1.16.0/numpy/distutils/command/build_src.py", line 159, in build_sources
    self.build_library_sources(*libname_info)
  File "/software/numpy-1.16.0/numpy/distutils/command/build_src.py", line 292, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/software/numpy-1.16.0/numpy/distutils/command/build_src.py", line 375, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 667, in get_mathlib_info
    raise RuntimeError("Broken toolchain: cannot link a simple C program")
RuntimeError: Broken toolchain: cannot link a simple C program

**Comment by absoult-dev** [comment]
I've tried:
export LDSHARED=gcc
export CC=gcc
export LDSHARED="/opt/lib/python2.7/config/ld_so_aix gcc -bI:/opt/lib/python2.7/config/python.exp"
export CFLAGS="-pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts"

but it reported the sanm errors

**Comment by rgommers** [comment]
First error
```
exec(): 0509-036 Cannot load program /opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/4.8.5/cc1 because of the following errors:
0509-130 Symbol resolution failed for /usr/lib/libgmp.a(libgmp.so.10) because:
0509-136 Symbol _GLOBAL__AIXI_shr_o (number 2) is not exported from
dependent module /opt/freeware/lib/libgcc_s.a(shr.o).
```

One of the first hits [here](https://www.ibm.com/developerworks/community/forums/html/topic?id=3e041d1e-16cc-44f1-951c-29e313d08789) says you need GCC 6.3.0 (maybe higher version now), yours still seems to be 4.8.5. 

https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha says the current version of GCC is in AIX Toolbox is 8.3.0, so you got a _really_ old version from somewhere.

**Comment by absoult-dev** [comment]
> First error
> 
> ```
> exec(): 0509-036 Cannot load program /opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/4.8.5/cc1 because of the following errors:
> 0509-130 Symbol resolution failed for /usr/lib/libgmp.a(libgmp.so.10) because:
> 0509-136 Symbol _GLOBAL__AIXI_shr_o (number 2) is not exported from
> dependent module /opt/freeware/lib/libgcc_s.a(shr.o).
> ```
> 
> One of the first hits [here](https://www.ibm.com/developerworks/community/forums/html/topic?id=3e041d1e-16cc-44f1-951c-29e313d08789) says you need GCC 6.3.0 (maybe higher version now), yours still seems to be 4.8.5.
> 
> https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha says the current version of GCC is in AIX Toolbox is 8.3.0, so you got a _really_ old version from somewhere.

OK,I got it  Thanks for your reply!

**Comment by absoult-dev** [comment]
> > First error
> > ```
> > exec(): 0509-036 Cannot load program /opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/4.8.5/cc1 because of the following errors:
> > 0509-130 Symbol resolution failed for /usr/lib/libgmp.a(libgmp.so.10) because:
> > 0509-136 Symbol _GLOBAL__AIXI_shr_o (number 2) is not exported from
> > dependent module /opt/freeware/lib/libgcc_s.a(shr.o).
> > ```
> > 
> > 
> > One of the first hits [here](https://www.ibm.com/developerworks/community/forums/html/topic?id=3e041d1e-16cc-44f1-951c-29e313d08789) says you need GCC 6.3.0 (maybe higher version now), yours still seems to be 4.8.5.
> > https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha says the current version of GCC is in AIX Toolbox is 8.3.0, so you got a _really_ old version from somewhere.
> 
> OK,I got it Thanks for your reply!



> First error
> 
> ```
> exec(): 0509-036 Cannot load program /opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/4.8.5/cc1 because of the following errors:
> 0509-130 Symbol resolution failed for /usr/lib/libgmp.a(libgmp.so.10) because:
> 0509-136 Symbol _GLOBAL__AIXI_shr_o (number 2) is not exported from
> dependent module /opt/freeware/lib/libgcc_s.a(shr.o).
> ```
> 
> One of the first hits [here](https://www.ibm.com/developerworks/community/forums/html/topic?id=3e041d1e-16cc-44f1-951c-29e313d08789) says you need GCC 6.3.0 (maybe higher version now), yours still seems to be 4.8.5.
> 
> https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha says the current version of GCC is in AIX Toolbox is 8.3.0, so you got a _really_ old version from somewhere.

Is numpy 1.18.1 or later supports to be builed on GCC 6.3.0 or GCC 8.3.0.I had tried build numpy 1.16.0 on GCC 6.3.0,but return the errors:_configtest.c:1:5: warning: conflicting types for built-in function 'exp'

**Comment by mattip** [comment]
That is not an error, it is part of how numpy.distutils probes your system to see if it supports various functions.

**Comment by absoult-dev** [comment]
> That is not an error, it is part of how numpy.distutils probes your system to see if it supports various functions.

It means this is not the error that ocuured by gcc 6.3.0 or python 2.7?

**Comment by mattip** [comment]
You said:
> I had tried build numpy 1.16.0 on GCC 6.3.0,but return the errors: `_configtest.c:1:5: warning: conflicting types for built-in function 'exp'`

The build should have continued from there. That is normal output from configuration, and can be ignored. When you build NumPy 1.18.0 and higher, they should not normally be displayed. Please use an up-to-date version.

**Comment by rossbar** [comment]
I'm going to close this due to inactivity - if the issue persists, please feel free to reopen with a fresh description of the current state of things.
