### ISSUE TITLE
Fail to build nump 1.13.1 on aix 6.1 with gcc

### ISSUE THREAD

**Issue by absoult-dev** [numpy/numpy#15952]
bash-5.0# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/lto-wrapper
Target: powerpc-ibm-aix6.1.0.0
Configured with: ../gcc-6.3.0/configure --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --with-local-prefix=/opt/freeware --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran,objc,obj-c++ --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --with-cloog=no --with-ppl=no --disable-libstdcxx-pch --enable-__cxa_atexit --host=powerpc-ibm-aix6.1.0.0
Thread model: aix
gcc version 6.3.0 (GCC) 
bash-5.0# python -V
Python 2.7.13
bash-5.0# uname -a
AIX localhost 1 6 00C4D4064C00

When I start to run：python setup.py install，The errors comes：

Running from numpy source directory.

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install numpy`   (last NumPy release on PyPi)

blas_opt_info:
blas_mkl_info:
  libraries mkl_rt not found in ['/usr/bin/../../opt/freeware/lib', '/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

blis_info:
  libraries blis not found in ['/usr/bin/../../opt/freeware/lib', '/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_info:
  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/bin/../../opt/freeware/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/bin/../../opt/freeware/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

/bin/sh: svnversion:  not found.
non-existing path in 'numpy/distutils': 'site.cfg'
/bin/sh: svnversion:  not found.
F2PY Version 2
lapack_opt_info:
lapack_mkl_info:
  libraries mkl_rt not found in ['/usr/bin/../../opt/freeware/lib', '/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_lapack_info:
customize UnixCCompiler
C compiler: gcc -lgcc -DNDEBUG -O2 -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts

creating /tmp/tmpwzmhGn/tmp
creating /tmp/tmpwzmhGn/tmp/tmpwzmhGn
compile options: '-c'
gcc: /tmp/tmpwzmhGn/source.c
/tmp/tmpwzmhGn/source.c:1:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void zungqr();
 ^~~~
/tmp/tmpwzmhGn/source.c: In function 'main':
/tmp/tmpwzmhGn/source.c:4:13: warning: implicit declaration of function 'zungqr_' [-Wimplicit-function-declaration]
             zungqr_();
             ^~~~~~~
gcc -lgcc /tmp/tmpwzmhGn/tmp/tmpwzmhGn/source.o -L/usr/bin/../../opt/freeware/lib -lopenblas -o /tmp/tmpwzmhGn/a.out
ld: 0711-317 ERROR: Undefined symbol: .zungqr_
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
ld: 0711-317 ERROR: Undefined symbol: .zungqr_
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas,tatlas not found in /usr/bin/../../opt/freeware/lib
  libraries lapack_atlas not found in /usr/bin/../../opt/freeware/lib
  libraries tatlas,tatlas not found in /opt/lib
  libraries lapack_atlas not found in /opt/lib
  libraries tatlas,tatlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries tatlas,tatlas not found in /usr/lib/
  libraries lapack_atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries satlas,satlas not found in /usr/bin/../../opt/freeware/lib
  libraries lapack_atlas not found in /usr/bin/../../opt/freeware/lib
  libraries satlas,satlas not found in /opt/lib
  libraries lapack_atlas not found in /opt/lib
  libraries satlas,satlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries satlas,satlas not found in /usr/lib/
  libraries lapack_atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in /usr/bin/../../opt/freeware/lib
  libraries lapack_atlas not found in /usr/bin/../../opt/freeware/lib
  libraries ptf77blas,ptcblas,atlas not found in /opt/lib
  libraries lapack_atlas not found in /opt/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
  libraries lapack_atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries f77blas,cblas,atlas not found in /usr/bin/../../opt/freeware/lib
  libraries lapack_atlas not found in /usr/bin/../../opt/freeware/lib
  libraries f77blas,cblas,atlas not found in /opt/lib
  libraries lapack_atlas not found in /opt/lib
  libraries f77blas,cblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries f77blas,cblas,atlas not found in /usr/lib/
  libraries lapack_atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

/software/numpy-1.13.1/numpy/distutils/system_info.py:572: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
lapack_info:
  libraries lapack not found in ['/usr/bin/../../opt/freeware/lib', '/opt/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

/software/numpy-1.13.1/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
lapack_src_info:
  NOT AVAILABLE

/software/numpy-1.13.1/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
  NOT AVAILABLE

/opt/freeware/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
running build_src
build_src
building py_modules sources
building library "npymath" sources
customize IBMFCompiler
Could not locate executable xlf90
Could not locate executable xlf
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
Could not locate executable /opt/freeware/lib/python2.7/config/ld_so_aix gcc -bI:/opt/freeware/lib/python2.7/config/python.exp
customize Gnu95FCompiler
customize Gnu95FCompiler using config
C compiler: gcc -lgcc -DNDEBUG -O2 -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/freeware/include/python2.7 -c'
gcc: _configtest.c
gcc -lgcc _configtest.o -o _configtest
success!
removing: _configtest.c _configtest.o _configtest
C compiler: gcc -lgcc -DNDEBUG -O2 -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/freeware/include/python2.7 -c'
gcc: _configtest.c
_configtest.c:1:5: warning: conflicting types for built-in function 'exp'
 int exp (void);
     ^~~
gcc -lgcc _configtest.o -o _configtest
ld: 0711-317 ERROR: Undefined symbol: .exp
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
ld: 0711-317 ERROR: Undefined symbol: .exp
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
failure.
removing: _configtest.c _configtest.o
C compiler: gcc -lgcc -DNDEBUG -O2 -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/freeware/include/python2.7 -c'
gcc: _configtest.c
_configtest.c:1:5: warning: conflicting types for built-in function 'exp'
 int exp (void);
     ^~~
gcc -lgcc _configtest.o -lm -o _configtest
collect2: fatal error: library libm not found
compilation terminated.
collect2: fatal error: library libm not found
compilation terminated.
failure.
removing: _configtest.c _configtest.o
C compiler: gcc -lgcc -DNDEBUG -O2 -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/freeware/include/python2.7 -c'
gcc: _configtest.c
_configtest.c:1:5: warning: conflicting types for built-in function 'exp'
 int exp (void);
     ^~~
gcc -lgcc _configtest.o -lcpml -o _configtest
collect2: fatal error: library libcpml not found
compilation terminated.
collect2: fatal error: library libcpml not found
compilation terminated.
failure.
removing: _configtest.c _configtest.o
Traceback (most recent call last):
  File "setup.py", line 392, in <module>
    setup_package()
  File "setup.py", line 384, in setup_package
    setup(**metadata)
  File "/software/numpy-1.13.1/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "build/bdist.aix-6.1/egg/setuptools/__init__.py", line 129, in setup
  File "/opt/freeware/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/freeware/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/freeware/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/software/numpy-1.13.1/numpy/distutils/command/install.py", line 62, in run
    r = self.setuptools_run()
  File "/software/numpy-1.13.1/numpy/distutils/command/install.py", line 56, in setuptools_run
    self.do_egg_install()
  File "build/bdist.aix-6.1/egg/setuptools/command/install.py", line 109, in do_egg_install
  File "/opt/freeware/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/freeware/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.aix-6.1/egg/setuptools/command/bdist_egg.py", line 161, in run
  File "/opt/freeware/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/freeware/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/software/numpy-1.13.1/numpy/distutils/command/egg_info.py", line 26, in run
    self.run_command("build_src")
  File "/opt/freeware/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/freeware/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/software/numpy-1.13.1/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/software/numpy-1.13.1/numpy/distutils/command/build_src.py", line 159, in build_sources
    self.build_library_sources(*libname_info)
  File "/software/numpy-1.13.1/numpy/distutils/command/build_src.py", line 294, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/software/numpy-1.13.1/numpy/distutils/command/build_src.py", line 377, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 675, in get_mathlib_info
    mlibs = check_mathlib(config_cmd)
  File "numpy/core/setup.py", line 373, in check_mathlib
    raise EnvironmentError("math library missing; rerun "
EnvironmentError: math library missing; rerun setup.py after setting the MATHLIB env variable

**Comment by seberg** [comment]
Hmm, NumPy 1.13 is an awfully old version, can you try with master or at least 1.18 which is the latest release candidate? I am not certain that we had any AIX stuff in 1.13. If you are stuck with Python 2, I guess the version to try is 1.16.

Although the MATHLIB error may be just something you have to set up correctly in site config or environment variables.

**Comment by absoult-dev** [comment]
> Hmm, NumPy 1.13 is an awfully old version, can you try with master or at least 1.18 which is the latest release candidate? I am not certain that we had any AIX stuff in 1.13. If you are stuck with Python 2, I guess the version to try is 1.16.
> 
> Although the MATHLIB error may be just something you have to set up correctly in site config or environment variables.

I had tried 1.16，but it returned the same errors

**Comment by rgommers** [comment]
I think you need a version with gh-12420 in it (which is indeed 1.16.0), and you will want to use Python3 from AIX Toolbox (see https://github.com/numpy/numpy/issues/14488#issuecomment-533974482).

**Comment by rgommers** [comment]
@absoult-dev you're still using Python 2.7 says your log, I'm afraid it'll be hard to find a working version of NumPy for that - perhaps applying a patch from another AIX issue on this tracker will help in case you really can't upgrade to Python 3.x

Please feel free to keep posting, but I'll close the issue since Python 2.7 is now really unsupported.
