### ISSUE TITLE
Einsum indexing very fragile, because it tests for int (and int64 is not int)

### ISSUE THREAD

**Issue by orichardson** [numpy/numpy#15961]
The index arrays for einsum do not accept the output of any numpy array, because these datatypes cannot be ints (see #2951; #12322). The test should be modified to accept numpy ints, because converting the datatype to 'int' explicitly is counter-intuitive and unnecessary.

Though easy to circumvent, this will incur a lot of unnecessary debugging time, as it appears to break abstraction boundaries, has strange interactions with `tolist`, and indices that work in test environments fail when constructed programatically.

### Reproducing code example:

```python
import numpy as np
X = np.arange(9).reshape(3,3)

# each of these results in an identical list [0] as far as equality test is concerned 
idx1 = [0]                # list[ int ] 
idx2 = np.unique(idx1)    # np.array [int64]
idx3 = idx2.tolist()      # list [int]
idx3 = list(idx2)         # list [int64]

np.einsum(X, [0], idx1 ) # succeeds
np.einsum(X, [0], idx2 ) # fails
np.einsum(X, [0], idx3 ) # succeeds
np.einsum(X, [0], idx4 ) # fails

```

### Error message:

ValueError: each subscript must be either an integer or an ellipsis

Full error message if `optimize_arg` is `False`:

```
<__array_function__ internals> in einsum(*args, **kwargs)

~/.local/lib/python3.6/site-packages/numpy/core/einsumfunc.py in einsum(*operands, **kwargs)
   1354     # If no optimization, run pure einsum
   1355     if optimize_arg is False:
-> 1356         return c_einsum(*operands, **kwargs)
   1357 
   1358     valid_einsum_kwargs = ['out', 'dtype', 'order', 'casting']

ValueError: each subscript must be either an integer or an ellipsis
```
Full error message when `optimize_arg` is `True`:
```
<__array_function__ internals> in einsum(*args, **kwargs)

~/.local/lib/python3.6/site-packages/numpy/core/einsumfunc.py in einsum(*operands, **kwargs)
   1377     # Build the contraction list and operand
   1378     operands, contraction_list = einsum_path(*operands, optimize=optimize_arg,
-> 1379                                              einsum_call=True)
   1380 
   1381     handle_out = False
```
### Numpy/Python version information:

1.17.3 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]

**Comment by eric-wieser** [comment]
We ought to be calling `operator.index` or the equivalent C API here, rather than the `PyInt_Check` I assume we must be doing today.

**Comment by eric-wieser** [comment]
Relevant lines are here:

https://github.com/numpy/numpy/blob/b489287af94b32d6a6d550c6e05f1cf92adf3248/numpy/core/src/multiarray/multiarraymodule.c#L2462-L2501

Logic ought to be the C equivalent of:
```python
try:
    s = operator.index(item)
except TypeError as e:
    raise TypeError("each subscript must be either an integer "
                    "or an ellipsis") from e
```

**Comment by guilhermeleobas** [comment]
I will take this one.

**Comment by tinaoberoi** [comment]
@guilhermeleobas you working on this ? If not I would like to take this up. Thanks

**Comment by guilhermeleobas** [comment]
Hi @tinaoberoi, it was on my plans but you can go ahead and work on it :)

**Comment by tinaoberoi** [comment]
Thanks @guilhermeleobas , I new here, any previous findings and help is appreciated. :-)

**Comment by rlintott** [comment]
I'm also a first time contributor. I might try fixing this. I don't really mind if you contribute first. In any case, the experience is good for me.
