### ISSUE TITLE
nextafter(float16(inf), float16(0)) returns nan and issues `RuntimeWarning: invalid value`

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#15977]
### Reproducing code example:

Numpys `nextafter` for the `float16` representation of `inf` gives `nan` rather than `finfo(float16).max`:

```python
import numpy as np
np.nextafter(np.float16(np.inf), np.float16(0))
```

### Error message:

The result is:

```
<stdin>:1: RuntimeWarning: invalid value encountered in nextafter
nan
```

I would have expected:
- no RuntimeWarning, as infinity should be valid in `nextafter`
- a return value of `65500.0`, which is `finfo(float16).max`.

### Numpy/Python version information:

```
>>> print(np.__version__, sys.version)
1.18.1 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
Looks like whoever was implementing it never thought of that case:

https://github.com/numpy/numpy/blob/c6916f44904b46c7c7bdb92ceb5242f3f6e00474/numpy/core/src/npymath/halffloat.c#L114-L147

Hopefully a straightforward fix.
