### ISSUE TITLE
Aggregate functions with nan support as array methods

### ISSUE THREAD

**Issue by max3-2** [numpy/numpy#15974]
Hi,

as stated by the title, basic aggregations are only existent for the non-nan type. When suspecting (or having) nan's in the array, the long version of np.nan_ has to be used.
Can this be added to the basic aggregations to work with the nan versions? This might fall in line with #7452 which is still open and I think not finally decided on.

### Reproducing code example

```python
import numpy as np
a =np.random.random((10,))
a[0] = np.nan 
a.min()  # Works as expected
np.nanmin(a)  # Works as expected

a.nanmin() # Error
```

**Comment by rossbar** [comment]
I think you're right that this is largely covered in #7452. I'm going to close this one since it didn't raise any additional discussion. If you are interested in pursuing this, you may want to bring it up on the mailing list, which is probably a better forum for this discussion.
