### ISSUE TITLE
single-segment vs contiguous arrays in numpy

### ISSUE THREAD

**Issue by anirudh2290** [numpy/numpy#15980]
In the doc, I see references to single-segment and contiguous and my understanding is that  they can be used interchangeably i.e. single-segment array is same as contiguous array. Is my understanding correct ? The [doc](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html) doesn't call this out explicitly and this let me looking for other numpy documentation which defines single-segment arrays but couldn't find any.

**Comment by seberg** [comment]
I think you are absolutely correct. The difference may come from the fact that single segment can be either C- or F-contiguous. Further, I suspect that one of the NumPy ancestors did not really know about 0-D arrays, the `PyArray_ISONESEGMENT` macro also checks for 0D specifically (possibly with a quick check that no insanely old NumPy version actually requires that).

**Comment by anirudh2290** [comment]
> I think you are absolutely correct. The difference may come from the fact that single segment can be either C- or F-contiguous.

Contiguous array also means either C contiguous or Fortran contiguous right ? The doc seems to suggest contiguous arrays means either C contiguous or F contiguous. 
Although from the code it seems, PyArray_ISCONTIGUOUS macro seems to check only for if c contiguous flag is true.

```
#define PyArray_ISCONTIGUOUS(m) PyArray_CHKFLAGS((m), NPY_ARRAY_C_CONTIGUOUS)
```

> possibly with a quick check that no insanely old NumPy version actually requires that – EDIT: This comment was supposed to say Maybe we should just remove that, possibly ...

I am not sure I understand the recommendation here.  Are you suggesting we should remove the 0d check and only check if it is C or F contiguous ?

**Comment by seberg** [comment]
```
#define PyArray_ISONESEGMENT(m) (PyArray_NDIM(m) == 0 || ...
```
That first NDIM check is not necessary, I think we can remove it. But since it is a marco and technically in most cases we are forward compatible, I thought it might make sense to check if e.g. 1.6 always considers 0D contiguous.

**Comment by anirudh2290** [comment]
thanks @seberg,  will check that and report back.

**Comment by seberg** [comment]
To be honest, not sure how much trouble its worth, but related. Some odd functions, like `np.ascontiguousarray` actually enforce at least one dimension, which I can only explain by backward compatibility with numeric/numarray or times where 0D arrays were not really a thing.

**Comment by anirudh2290** [comment]
looks like 0d are considered both C and F Contiguous in 1.6.2

```
>>> np.__version__
'1.6.2'
>>> x = np.array(0)
>>> x.ndim
0
>>> x.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>>
```

**Comment by anirudh2290** [comment]
the oldest version i was able to find a difference for was 1.5.1. The flags for a 0d array say C contiguous as true and F contiguous as false. The other later versions that i checked (1.6.0, 1.6.2, 1.10.1) all have both C contiguous and F contiguous set to True. Also, np.ascontiguousarray seems to be handling 0d arrays fine without throwing an error for any of these versions.

```
>>> x = np.array(0)
>>> np.__version__
'1.5.1'
>>> x.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>> np.ascontiguousarray(x).flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

Can I conclude that : both contiguous and single segment mean the same thing (at least after 1.6) i.e. "either C contiguous or F contiguous or both" ?

**Comment by seberg** [comment]
Yes, you can do that and even update the documentation to that effect if you find it clearer (single segment might be nice to mention for those who do not know contiguous as well as non-native speakers I guess). As I said, I guess there may be some ancient historical reasons and that is all there is. The only thing is that I am not sure if we sometimes conflate `contiguous` and `C-contiguous`.

**Comment by charris** [comment]
> sometimes conflate contiguous and C-contiguous

`contiguous` was the original, `C-contiguous` was added as an alias because it is more descriptive and it is what should be used. We kept `contiguous` for backwards compatibility, I don't know if it is still used anywhere.

**Comment by anirudh2290** [comment]
> We kept contiguous for backwards compatibility, I don't know if it is still used anywhere.

Its used in docs in a few places. Some docs are very careful to prefix it with C-style and F-style. But its also used without this prefix in other places (for example array_is_contiguous in https://docs.scipy.org/doc/numpy-1.13.0/reference/swig.interface-file.html). In the code, I see 
```
#define PyArray_ISCONTIGUOUS(m) PyArray_CHKFLAGS((m), NPY_ARRAY_C_CONTIGUOUS)
```
this macro being used at a bunch of different places, but i havent looked into each of these cases to see if this really means anything to the end user or if its just being used in place of `PyArray_IS_C_CONTIGUOUS`

**Comment by anirudh2290** [comment]
The PR to update doc is resolved, closing.
