### ISSUE TITLE
"ImportError" after compilation with Nuitka

### ISSUE THREAD

**Issue by gauthierbuttez** [numpy/numpy#16002]
Hi,

I am trying to compile my python program with Nuitka. 
I have Python 3.7 on Windows 10.
The compilation goes fine but when I execute the .exe of my program freshly complicated, I get this error:
http://prntscr.com/s0z64w

So I follow the recommendation displayed on the screen:
I uninstall and reinstall bumpy 1.18.2.
I uninstall, reinstall and double-check my python 3.7.
I compile again my python script with nuitka and again I get the same issue.

Do you have any idea how can I fix that please?

**Comment by mattip** [comment]
1) Please do not use screenshots, copy paste text instead
2) Where is the error message? Did it end up in a different part of the output?
3) You will have better luck asking on a Nuitka-oriented forum or browsing their [issue tracker](https://github.com/Nuitka/Nuitka/issues/190). People here have very little experience with Nuitka

**Comment by gauthierbuttez** [comment]
Thanks for reply.
1. Ok.
2. There was no error message. Everything shoes on output is in the screenshot.
3. I did and wait for their answer.

**Comment by rossbar** [comment]
The corresponding Nuitka issue is closed and it doesn't seem there is any additional information, so I'm going to close here as well. If the issue persists and there is more specific info, please feel free to re-start the discussion.
