### ISSUE TITLE
'setup.py install --skip-build' misses generated files

### ISSUE THREAD

**Issue by mgorny** [numpy/numpy#16005]
### Reproducing code example:

```
python3.8 setup.py build config_fc --noopt --noarch --fcompiler=gnu95
python3.8 setup.py install --skip-build --root=<some-directory> config_fc --noopt --noarch --fcompiler=gnu95
```

### Error message:

The install tree is missing the following files that are normally installed (without `--skip-build`):

```
/usr/lib/python3.8/site-packages/numpy/core/include/numpy/__multiarray_api.h
/usr/lib/python3.8/site-packages/numpy/core/include/numpy/multiarray_api.txt
/usr/lib/python3.8/site-packages/numpy/core/include/numpy/_numpyconfig.h
/usr/lib/python3.8/site-packages/numpy/core/include/numpy/__ufunc_api.h
/usr/lib/python3.8/site-packages/numpy/core/include/numpy/ufunc_api.txt
/usr/lib/python3.8/site-packages/numpy/core/lib/npy-pkg-config/mlib.ini
/usr/lib/python3.8/site-packages/numpy/core/lib/npy-pkg-config/npymath.ini
```

### Numpy/Python version information:

```
$ python -c  'import sys, numpy; print(numpy.__version__, sys.version)'
1.17.4 3.8.2 (default, Apr  4 2020, 10:16:10) 
[GCC 9.2.0]
```

**Comment by mgorny** [comment]
I am able to workaround it via prepending `build_src` before `install`.

**Comment by rossbar** [comment]
This seems resolved - is the `build_src` solution a workaround or the proper way to handle this?

**Comment by mgorny** [comment]
It's only a workaround. The proper way would be to pass complete file list to `setup()` and not modify file lists inside commands. They should really be immutable.

**Comment by rgommers** [comment]
It would be nice if this can be addressed with a minimally invasive patch, like adding missing files with `add_data_files`. Complete file listing in `setup.py` seems undesirable, I'd rather raise an error on `--skip-build` in that case - it's a marginal option that I've never seen used before.

**Comment by rgommers** [comment]
We won't be changing this anymore now that `numpy.distutils` is deprecated. As we recently noticed in SciPy, `--skip-build` is a bad idea anyway. I'll close this issue.
