### ISSUE TITLE
Feature request: add optional units attribute to np.ndarrays 

### ISSUE THREAD

**Issue by Didou09** [numpy/numpy#16019]
For physics and engineering, wouldn't it be interesting to add a (empty by default) attribute 'units' to np.ndarrays ?

Like the shape, ndim or dtype, the array would carry its units with it.
It could be a str that the user could decide to set or not.

That would make it easier for developpers in physics to double-check consistency.

Anybody else interested ?

On the longer-run, an optional unit-checking mechanism could be implemented and called when performing operations on arrays (to check consistency or even derive the units of the output from the units of the input)

**Comment by eric-wieser** [comment]
You might want to check out `astropy`, which already provides facilities for this.

There are plans in the medium term to make it easier to embed `units` in the `dtype`, which would integrate better into numpy (NEP-41 touches on this).

**Comment by mhvk** [comment]
See http://docs.astropy.org/en/latest/units/index.html

It has been a long-standing wish to have the units package move up to numpy or scipy, since obviously it is not astronomy-specific. In any case, comments/improvements most welcome.

**Comment by rgommers** [comment]
Let's close this, since the question is answered and there are units libraries and we have NEP 41 in progress. Thanks all
