### ISSUE TITLE
Docs link is outdated on PyPI

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#16018]
https://github.com/numpy/numpy/blob/1d598997543637b9882d1663117b573210a20583/setup.py#L439

I assume we should be using a `numpy.org` link here, possibly derived from the version number?

**Comment by mattip** [comment]
I think this should be https://numpy.org/doc/stable

**Comment by eric-wieser** [comment]
I'd argue it should be pinned to the release, so that if someone goes to a historic pypi release, they get a link to the corresponding historic docs page.
