### ISSUE TITLE
ImportError -wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by raj8080** [numpy/numpy#16013]
Python version - 3.8
Numpy version-1.18.2
Openwrt build system

I am compiling the package pandas but while import numpy it has the following error

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/source/openwrt/staging_dir/hostpkg/bin/python3.8",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /source/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38.so: wrong ELF class: ELFCLASS32

**Comment by mattip** [comment]
How did you build/install numpy? I think you got a version not supported on your architecture.

**Comment by raj8080** [comment]
by the openwrt makefile...can you suggest me some version...

**Comment by mattip** [comment]
Does openwrt have a package manager? Are you cross compiling or building directly on the hardware? Are you following a guide from somewhere else?

**Comment by raj8080** [comment]
I am creating  a makefile in the openwrt sdk, yes cross compiling not building directly on the hardware...
not following anyone...

**Comment by raj8080** [comment]
yes, it has the package manager but numpy is not available so created the package...

**Comment by mattip** [comment]
so maybe the build is not using the cross-compiler, and creating a native shared object instead of a openwrt one. I don't think cross-compiling python c-extension packages works, but perhaps you can prove me wrong. [This package](https://bitbucket.org/lambacck/distutilscross/src/default/) exists but is over 10 years old.

**Comment by raj8080** [comment]
i compiled many python package but i have problem with this numpy package...
the link you shared i didnt get the point it showing some disutilscross....

**Comment by mattip** [comment]
> i didnt get the point it showing some disutilscross....

My point was that as far as I know cross-compiling c-extension packages is an unsolved problem. 

> i compiled many python package

Do they contain c-extensions or are they pure python? Could you give some examples of a c-extension package that works?

**Comment by raj8080** [comment]
no idea about this c-extension python...

**Comment by rossbar** [comment]
This seems like a pretty specialized use-case and one that is not likely to generate a lot of discussion, though it would be great @raj8080 if you could follow up if you figure out how to do this. AFAIK there is no existing documentation for this use-case; perhaps others might find such feedback useful

**Comment by rgommers** [comment]
I'll close this for lack of follow up. Cross compiling NumPy works, and the rest is a general "cross compilation is not well supported by distutils/setuptools" issue. https://github.com/benfogle/crossenv should help though.
