### ISSUE TITLE
DOC: add versioning note to the top of the docs via javascript

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#16016]
On [scikit-learn's docs](https://github.com/scikit-learn/scikit-learn.github.io/blob/master/versionwarning.js) they use a javascript to add a note to the top of the [non-current docs](https://scikit-learn.org/0.19/modules/linear_model.html#stochastic-gradient-descent-sgd) "This is documentation for an old release of Scikit-learn (version 0.19). Try the latest stable release (version 0.22) or development (unstable) versions.". We should do something like that, The docs on docs.scipy.org/doc/numpy have already been modified by hand with the following diff (applied to all the different versions):

```diff
$ diff --context /srv/docs_scipy_org/doc/numpy-1.4.x/_static/doctools.js /srv/docs_scipy_org/doc/numpy-1.3.x/_static/doctools.js
*** /srv/docs_scipy_org/doc/numpy-1.4.x/_static/doctools.js	Mon Mar 13 18:01:14 2017
--- /srv/docs_scipy_org/doc/numpy-1.3.x/_static/doctools.js	Sun Apr 12 18:34:25 2020
***************
*** 97,102 ****
--- 97,103 ----
      this.fixFirefoxAnchorBug();
      this.highlightSearchWords();
      this.initModIndex();
+     this.add_outdated_note();
    },
  
    /**
*** 221,226 ****
--- 222,241 ----
      });
      var url = parts.join('/');
      return path.substring(url.lastIndexOf('/') + 1, path.length - 1);
+   },
+   add_outdated_note : function() {
+     var msg = 'This is documentation for an old release of NumPy. ' +
+               'The latest documentation can be seen at ' +
+ 	      '<a href="https://numpy.org/doc/stable">https://numpy.org/doc/stable</a>'
+     $('.body').prepend(
+     '<p style="' +
+     [
+ 	'padding: 1em',
+ 	'font-size: 1.5em',
+ 	'border: 1px solid red',
+ 	'background: pink',
+     ].join('; ') +
+     '">' + msg + '</p>')
    }
  };
```

**Comment by divyabhushan** [comment]
Hi @mattip, Is this issue still open?

**Comment by mattip** [comment]
Yes

**Comment by divyabhushan** [comment]
Could you assign it to me?

**Comment by mattip** [comment]
We don't usually assign issues. If you wish to pick this up, you should read the [contribtion docs](https://numpy.org/doc/stable/dev/index.html). 

This is a bit tricky, since we serve documentation from a specialized repo https://github.com/numpy/doc, as explained in the Readme there. Each version has its own `_static` directory, so one option would be to modify the `doctools.js` in each subdirectory there as a PR against that repo. 

Looking forward, I think we should look for a better solution:
- It would be good to somehow parametrize a [`<base>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) in all the pages served via  https://github.com/numpy/doc, and have only one version of the theming `_static` content. Maybe we could create a commented out `<base>` element when building documentation, and replace it when deploying to https://github.com/numpy/doc
- We should use the [Version](https://github.com/numpy/doc/blob/master/1.18/about.html#L18) attribute to trigger whether to display the "outdated" `<div>`

Personally, I am not a big fan of using javascript for this kind of a thing: we could use a css class `outdated_$VERSION` for this content on each page, and hide or show the class via a css stylesheet which is updated on each new release.

**Comment by rossbar** [comment]
This may be closed by numpy/doc#7 - it would be great if we could get eyes on it, especially from reviewers who are familiar with similar approaches used in other projects (the linked PR appears to originate from similar changes to scipy)

**Comment by mattip** [comment]
Yes, numpy/doc#7 will close this.

**Comment by rossbar** [comment]
Closing now that the linked PR is in
