### ISSUE TITLE
this is wrong setup.py to run

### ISSUE THREAD

**Issue by joezhou099** [numpy/numpy#16028]
hi there,

i used /path/to/python setup.py install, but got error 'this is wrong setup.py to run', may i know how to solve it please? thanks

**Comment by mattip** [comment]
What was your `$pwd` ? you should be in the top directory, not in `numpy/numpy`

**Comment by seberg** [comment]
@joezhou099 this exact error happens if you run the setup.py that should be in `./numpy/setup.py`, not `./setup.py`, so if those are the paths you are on, the best guess I have is that something is wrong in how you extracted the files. There should be a `numpy` folder inside a `numpy` folder...

**Comment by joezhou099** [comment]
> @joezhou099 this exact error happens if you run the setup.py that should be in `./numpy/setup.py`, not `./setup.py`, so if those are the paths you are on, the best guess I have is that something is wrong in how you extracted the files. There should be a `numpy` folder inside a `numpy` folder...

I used./numpy/setup.py, it reported wrong setup.py. i looked at./numpy/setup.py, its main function only prints "Wrong setup.py". I used./setup.py, it reported no cythonize.py found.

**Comment by seberg** [comment]
You probably need to run it from the same directory...

**Comment by joezhou099** [comment]
> You probably need to run it from the same directory...

So the correct setup.py should be the one with setup_package() in the main function? Also, is numpy release on this repository compatible with centos 7.6.1810 (AltArch), which is aarch64 system rather than x86
