### ISSUE TITLE
Install numpy on aarch64

### ISSUE THREAD

**Issue by joezhou099** [numpy/numpy#16029]
Can i install numpy of this repository on aarch64? I tried but it gave many missing header files that aarch64 gcc does not have. Pls help! Much appreciated!

**Comment by rgommers** [comment]
conda-forge has packages for `aarch64`. If you prefer to build from source, that should work too - NumPy has CI for `aarch64`, see https://github.com/numpy/numpy/blob/master/shippable.yml for hints.
