### ISSUE TITLE
Efficient way to create a complex array from two real arrays

### ISSUE THREAD

**Issue by zhcui** [numpy/numpy#16039]
Dear NumPy developers,

This may be more like a question. I have two real arrays (`a` and `b`), and I would like create a complex array (`c`) which takes the two real arrays as its real and imaginary parts respectively.

The simplest one would be 
`c = a + b * 1.0j`
However, since my data size is quite large, such code is not very efficient.

We can also do the following,
`c = np.empty(data_shape, dtype=np.complex128)`
`c.real = a`
`c.imag = b`

I am wondering is there a better way to do that (e.g. using `buffer` or something)? 

Thank you very much!
Zhihao

**Comment by eric-wieser** [comment]
Your approach using `empty` is as you can get, short of avoiding the intermediate `a` and `b` arrays completely.

**Comment by seberg** [comment]
Indeed, unless you can use, an out argument directly, such as `np.add(arr1, arr2, out=c.real)`, which may than be faster.
Hope this helped, closing.

**Comment by zhcui** [comment]
Thanks you both for answers. Just an additional question, the real and imaginary data in a complex array is continuous. right? I mean the c.real and c.imag are adjacent in address?

**Comment by seberg** [comment]
> I mean the c.real and c.imag are adjacent in address?

Yes, this is baked in very low into NumPy that all elements are contiguous memory.

**Comment by mattip** [comment]
The elements are contiguous and interleaved: c[0].real, c[0].imag, c[1].real, c[1].imag, not c[0].real, c[1].real, ... c[n-1].real, c[0].imag, c[1].imag, ...

**Comment by zhcui** [comment]
> The elements are contiguous and interleaved: c[0].real, c[0].imag, c[1].real, c[1].imag, not c[0].real, c[1].real, ... c[n-1].real, c[0].imag, c[1].imag, ...

I see, I guess this is the reason why we can view the `(n, 2)` double array to a complex array.
