### ISSUE TITLE
when I run this part of my code, this error appeared ,I don't know whats the problem? when i run it for year 2019 that exist in my data set, the figure was shown ,but it doesn't show the prediction year'2020'

### ISSUE THREAD

**Issue by MatGod7** [numpy/numpy#16034]
Did you find the solution to your problem?

when I run this part of my code, this error appeared ,I don't know whats the problem? when i run it for year 2019 that exist in my data set, the figure was shown ,but it doesn't show the prediction year'2020'

![error](https://user-images.githubusercontent.com/41548139/70789007-65082d00-1da7-11ea-8c97-b0c201263ea4.JPG)

_Originally posted by @Nocturnehub in https://github.com/numpy/numpy/issues/7431#issuecomment-565366736_

**Comment by anirudh2290** [comment]
as suggested in the related issue (https://github.com/numpy/numpy/issues/7431#issuecomment-567678472), there are two things you should try:

1. Check if you have object  dtype used somewhere and if you don't really need object dtype (for example if you can force it to numerical types please do that)
2. check if updating numpy helps when using datetime.

**Comment by Nocturnehub** [comment]
@MatGod7 Unfortunately I didn't follow that project anymore and didn't debug , but try to update your numpy, maybe it help you.

**Comment by rossbar** [comment]
I'm going to close this due to inactivity - if the issue persists please reopen with updated info on the problem.
