### ISSUE TITLE
strip_zeros kwarg no longer available in FloatFormat

### ISSUE THREAD

**Issue by moorepants** [numpy/numpy#16036]
### Reproducing code example:

I've been using this context manager in some code to control array printing:

```python
import contextlib

import numpy as np
import numpy.core.arrayprint as arrayprint


@contextlib.contextmanager
def printoptions(strip_zeros=False, **kwargs):
    """Allows you to set NumPy array print formatting locally.
    Taken from:
    http://stackoverflow.com/questions/2891790/pretty-printing-of-numpy-array
    """

    origcall = arrayprint.FloatFormat.__call__

    def __call__(self, x, strip_zeros=strip_zeros):
        return origcall.__call__(self, x, strip_zeros)

    arrayprint.FloatFormat.__call__ = __call__
    original = np.get_printoptions()
    np.set_printoptions(**kwargs)
    yield
    np.set_printoptions(**original)
    arrayprint.FloatFormat.__call__ = origcall
```

`FloatFormat` was removed in NumPy 1.18.0 but prior to that https://github.com/numpy/numpy/pull/9941 removed the `strip_zeros` kwarg from `FloatFormat.__call__`. This seems to be a backwards incompatible change. It also seems like that kwarg likely did not have a unit test.

Regardless, I'm trying to figure out how to reproduce the behavior of `strip_zeros=False` prior to PR #9941.

### Numpy/Python version information:

```
In [10]: import sys, numpy; print(numpy.__version__, sys.version)                                                                           
1.18.1 3.6.10 | packaged by conda-forge | (default, Apr  6 2020, 14:52:36) 
[GCC 7.3.0]
```

**Comment by seberg** [comment]
Hmmm, thanks for the report. I honestly do not think we ever considered `FloatFormat` to be public API, its unfortunate that we cannot just add underscores over night to signal such things easier.

Is the `floatmode="fixed"` argument to print-options what you are looking for?!

This has been inside NumPy for 3 releases now in that case. I am a bit curious whether this is more something you noticed, or something that actually creates issues for you? Because I am not immediately sure there is much gain in trying to undo these changes, especially with such a long delay?

**Comment by seberg** [comment]
Also note that `np.printoptions` is a context manager already, so no need to do this yourself.

**Comment by moorepants** [comment]
> Also note that np.printoptions is a context manager already, so no need to do this yourself.

I think that's since numpy 1.15. I'm updating a library that supports back to 1.13 still.

**Comment by moorepants** [comment]
> This has been inside NumPy for 3 releases now in that case. I am a bit curious whether this is more something you noticed, or something that actually creates issues for you? 

I have a stable library that I developed a decade ago and I update it about once a year now to ensure it works with the recent libraries. I'm behind on the update a bit but it is blocking some travis builds and I need to come up with a work around. I'm mostly looking for that, not expecting you all to undo changes.

**Comment by moorepants** [comment]
> Is the floatmode="fixed" argument to print-options what you are looking for?!

I'll investigate. Thanks.

**Comment by rossbar** [comment]
@moorepants is there anything actionable here in your opinion? We should probably review the arrayprint module to verify that any public/exposed functions are intended to be so.

**Comment by moorepants** [comment]
I haven't had time to figure out a workaround in my library, it is still on my todo list. As for actionable items from you all, I suspect you'd have to decide if you want to address this or not in the NumPy codebase.

**Comment by rossbar** [comment]
The discussion in #16869 turned up the source of the issue, see #11924 . I will close this for now as picking up the linked NEP seems like the best way for preventing issues like this in the future.
