### ISSUE TITLE
1.19.0: tests failure on armel

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#16049]
Hello
I've recently uploaded numpy/1.8.3 to debian, and the test suite reported a failure when running on the architecture `armel`, full log at https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armel&ver=1%3A1.18.3-1&stamp=1587357650&raw=0 , extract

python3.8: `= 15 failed, 10225 passed, 90 skipped, 180 deselected, 18 xfailed, 2 xpassed in 886.89 seconds =`
python3.8 "debug": `= 15 failed, 10225 passed, 90 skipped, 180 deselected, 18 xfailed, 2 xpassed in 1455.94 seconds =`

15 failures are too many to report verbatim here, let me just report the failed test:

python3.8:
```
TestErrstate.test_invalid
TestHalf.test_half_fpe
TestBoolCmp.test_float
TestSeterr.test_divide_err
TestSeterr.test_errobj
TestFloatExceptions.test_floating_exceptions
TestFloatExceptions.test_warnings
TestLog2.test_log2_special
TestSpecialFloats.test_exp_values
TestSpecialFloats.test_log_values
TestSpecialFloats.test_sincos_values
TestSpecialFloats.test_square_values
TestSpecialFloats.test_reciprocal_values
TestClog.test_special_values
TestMedian.test_empty
```

python3.8 "debug"
```
TestErrstate.test_invalid
TestHalf.test_half_fpe
TestBoolCmp.test_float
TestSeterr.test_divide_err
TestSeterr.test_errobj
TestFloatExceptions.test_floating_exceptions
TestFloatExceptions.test_warnings
TestLog2.test_log2_special
TestSpecialFloats.test_exp_values
TestSpecialFloats.test_log_values
TestSpecialFloats.test_sincos_values
TestSpecialFloats.test_square_values
TestSpecialFloats.test_reciprocal_values
TestClog.test_special_values
TestMedian.test_empty
```

**Comment by seberg** [comment]
I think most or even all of these are due to `armel` not having floating point error flags, or rather buggy software floating point error support? At least one of these tests already have a:
```
@pytest.mark.skipif(platform.machine() == "armv5tel", reason="See gh-413.")
```
although that one shows up above, so I guess it doesn't match this platform, but should also be skipped here.
My guess is, we have to skip all of these tests, maybe we should have a global testing variable.

**Comment by sandrotosi** [comment]
same 15 failures with 1.8.4

**Comment by seberg** [comment]
@sandrotosi thanks for the update. We didn't actually try to do anything about this in 1.18.4... There were just two regressions that needed ironing out.

**Comment by sandrotosi** [comment]
same issues with 1.19.0rc2: https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armel&ver=1%3A1.19.0%7Erc2-2&stamp=1591493504&raw=0

**Comment by sandrotosi** [comment]
there are still some test failures with 1.19.0: https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armel&ver=1%3A1.19.0-1&stamp=1592795834&raw=0

**Comment by charris** [comment]
This is on armel, right? Do you also test on armhf?
>The armel architecture supports the ARMv4 instruction set. This architecture handles floating-point computation in a compatibility mode which it slows performance but allows compatibility with code written for processors without floating point units. So you can use the armel architecture to build high compatible systems.
>
>The armhf architecture supports ARMv7 platform, and more, it adds direct hardware floating-point support. This means the armhf architecture is faster than the armel one, but it lacks the compatibility with the old architectures.

I'm wondering if we should support armel, there may be problems in the emulation.

**Comment by charris** [comment]
There may also be a problem detecting the correct platform during compilation, since armel is being run on an armhf machine.

**Comment by sandrotosi** [comment]
we do also test on armhf: https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armhf&ver=1%3A1.19.0-1&stamp=1592790588&raw=0 (but i noticed there the fix for https://github.com/numpy/numpy/issues/16516 was not included in the 1.19.0 final release, but since it's in master i didnt mention that)

**Comment by charris** [comment]
The armhf fix is in 1.19.0 final, see #16526.

**Comment by sandrotosi** [comment]
oh i was probably looking at another PR for master (not the one for maint/1.19.x)

but i'm afraid it didnt work fully, from the [link above](https://www.youtube.com/playlist?list=PLCTHcU1KoD99Rim2tzg-IhYY2iu9FFvNo):

```
=================================== FAILURES ===================================
_______________________ Test_ARM_Features.test_features ________________________

self = <numpy.core.tests.test_cpu_features.Test_ARM_Features object at 0xf34d9490>

    def test_features(self):
        self.load_flags()
        for gname, features in self.features_groups.items():
            test_features = [self.cpu_have(f) for f in features]
>           assert_equal(__cpu_features__.get(gname), all(test_features))
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: True
E            DESIRED: False

features   = ['NEON', 'HALF']
gname      = 'NEON_FP16'
self       = <numpy.core.tests.test_cpu_features.Test_ARM_Features object at 0xf34d9490>
test_features = [False, False]

tmp/usr/lib/python3/dist-packages/numpy/core/tests/test_cpu_features.py:20: AssertionError
= 1 failed, 10800 passed, 89 skipped, 108 deselected, 19 xfailed, 2 xpassed in 230.28 seconds =
``` on armhf numpy/1.19.0

**Comment by charris** [comment]
I'm going to guess the test may be broken. @seiko2plus Thoughts?

**Comment by charris** [comment]
Does 'NEON_FP16' mean it is compiled with the (non-IEEE float16) arm instruction set? IIRC, that is a compiler flag.

**Comment by sandrotosi** [comment]
the build link contains the whole output of numpy build and test phases. I tried a dumb search for `neon` and `float16` but i couldnt find any gcc flag being used, maybe it has a different name? if so it should be there (unless it's somehow implicit on that architecture)

**Comment by charris** [comment]
> ARM processors support (via a floating point control register bit) an "alternative half-precision" format, which does away with the special case for an exponent value of 31 (111112).[10] It is almost identical to the IEEE format, but there is no encoding for infinity or NaNs; instead, an exponent of 31 encodes normalized numbers in the range 65536 to 131008.

For gcc

>ARM targets support two incompatible representations for half-precision floating-point values. You must choose one of the representations and use it consistently in your program.
>
>Specifying -mfp16-format=ieee selects the IEEE 754-2008 format. This format can represent normalized values in the range of 2^{-14} to 65504. There are 11 bits of significand precision, approximately 3 decimal digits.
>
>Specifying -mfp16-format=alternative selects the ARM alternative format. This representation is similar to the IEEE format, but does not support infinities or NaNs. Instead, the range of exponents is extended, so that this format can represent normalized values in the range of 2^{-14} to 131008.
>
>The GCC port for AArch64 only supports the IEEE 754-2008 format, and does not require use of the -mfp16-format command-line option.

I don't think this matters for NumPy, we currently implement float16 in platform independent C code. I'm just curious.

**Comment by seiko2plus** [comment]
@sandrotosi, this error is different than the one in #16516.
The ARMHF chip in #16516 was supporting `FP16`, but the above testing log show no support for it
Please could you provide the build log? also, a dump of `/proc/cpuinfo` if it's possible.

@charris,
>  I'm going to guess the test may be broken.

Not sure yet, the issue here that NumPy reports the availability of `FP16` and `NEON` while the parsed `/proc/cpuinfo` reports nothing.

> Does 'NEON_FP16' mean it is compiled with the (non-IEEE float16) arm instruction set? IIRC, that is a compiler flag.

By `NEON_FP16`, we mean a feature group represents both NEON and FP16 features.
`FP16` is a hardware feature providing single-precision and half-precision conversions.

> I don't think this matters for NumPy, we currently implement float16 in platform-independent C code. I'm just curious.

It matters actually, It should be used within the universal intrinsics and the current infrastructure supports it through `--cpu-baseline` and `--cpu-dispatch`. on ARMHF the infrastructure will use compiler flags `-mfpu=neon-fp16 -mfp16-format=ieee` to enable NEON and FP16 with IEEE support.

**Comment by seiko2plus** [comment]
@sandrotosi, I checked the updated link of the build log, well it seems that Debian now running armhf's rootfs over aarch64 via chroot, right? I guess the issue here is Debian uses a fake `/proc/cpuinfo`, Is that right too?

**Comment by sandrotosi** [comment]
from what i can see, it looks like it was built on this machine: https://db.debian.org/machines.cgi?host=arm-arm-01 but i'm afraid i'm not familiar with the particular setup of the arm* architectures build machines/instances

**Comment by seiko2plus** [comment]
@sandrotosi, as I can see that machine is definitely ARMv8 CHIP, I'm not sure about how Debian mounted the rootfs of armhf since there's no dump for `/proc/cpuinfo` or extra information about the chroot implementation.
However, I wonder if you could build numpy with this patch #16674? so we can determine the problem from the extra debugging information.

**Comment by mattip** [comment]
Ping @sandrotosi Did this get resolved?

**Comment by sandrotosi** [comment]
nope, this is still an issue with 1.19.1: https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armel&ver=1%3A1.19.1-1&stamp=1595472320&raw=0

**Comment by mattip** [comment]
Did you try with latest HEAD that contains #16674? That PR did not make it into a release yet.

**Comment by sandrotosi** [comment]
I can confirm this is still happening with 1.21.4: [build log](https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armel&ver=1%3A1.21.4-1&stamp=1636535948&raw=0) (search for `short test summary info` to jump directly to the summary)

**Comment by mattip** [comment]
The test added in #16674 to detect that the feature list is consistent passes, there is this line in the log
```
test_cpu_features.py::Test_ARM_Features::test_features PASSED
```

**Comment by sandrotosi** [comment]
sure that test is pasing, what i was pointing out is that the same failures originally reported with this issue are still present with 1.21.4; [latest build log](https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armel&ver=1%3A1.21.4-2&stamp=1637392521&raw=0) shows 22 failures

**Comment by seiko2plus** [comment]
@sandrotosi, what about `armhf`?

**Comment by sandrotosi** [comment]
[armhf build log](https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armhf&ver=1%3A1.21.4-2&stamp=1637392091&raw=0) shows 2 failures:

```
FAILED tmp/usr/lib/python3/dist-packages/numpy/typing/tests/test_generic_alias.py::TestGenericAlias::test_getattr[__copy__]
FAILED tmp/usr/lib/python3/dist-packages/numpy/typing/tests/test_generic_alias.py::TestGenericAlias::test_getattr[__deepcopy__]
```

for both python 3.9 and 3.10

**Comment by seiko2plus** [comment]
most of `armel`'s errors are related to FP exceptions. as far as I know, `ARM/VFPv3` doesn't offer support for traping floating-point exceptions, so I think these errors are pretty normal unless if we have to handle it softly, or just suppress them.

**Comment by seiko2plus** [comment]
I think you need to pass flag `-mfloat-abi=softfp` to the compiler in order to add support for traping float exceptions on `armel`.

**Comment by sandrotosi** [comment]
i thought the compiler flags were handled by the numpy build system?

**Comment by seiko2plus** [comment]
I'm not sure about the above comments but I checked the provided build log of `armel` and I didn't see the flag `-mfloat-abi`. NumPy build system usually just handles extra necessary flags mostly related to CPU optimizations, the rest flags that have been exposed within the build log above came from [python/sysconfig](https://docs.python.org/3/library/sysconfig.html) e.g.:
```Bash
#! python
Python 3.9.5 (default, May 19 2021, 11:32:47) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sysconfig import get_config_vars
>>> get_config_vars('CFLAGS')
['-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2   ']
>>>

**Comment by sandrotosi** [comment]
closing outdated issues i reported long ago
