### ISSUE TITLE
1.19.0: tests failure on s390x

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#16046]
Hello,
I've recently uploaded numpy/1.8.3 to debian, and the test suite reported a failure when running with the debug flavor of python3.8 on the architecture `s390x`, full log at https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=s390x&ver=1%3A1.18.3-1&stamp=1587351308&raw=0 , extract:

```
___________________ TestRationalFunctions.test_gcd_overflow ____________________

self = <numpy.core.tests.test_umath.TestRationalFunctions object at 0x3ffa1549dc0>

    def test_gcd_overflow(self):
        for dtype in (np.int32, np.int64):
            # verify that we don't overflow when taking abs(x)
            # not relevant for lcm, where the result is unrepresentable anyway
            a = dtype(np.iinfo(dtype).min)  # negative power of two
            q = -(a // 4)
>           assert_equal(np.gcd(a,  q*3), q)
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: -2305843009213693952
E            DESIRED: 2305843009213693952

a          = -9223372036854775808
dtype      = <class 'numpy.int64'>
q          = 2305843009213693952
self       = <numpy.core.tests.test_umath.TestRationalFunctions object at 0x3ffa1549dc0>

tmp/usr/lib/python3/dist-packages/numpy/core/tests/test_umath.py:2599: AssertionError
= 1 failed, 10243 passed, 85 skipped, 180 deselected, 18 xfailed, 2 xpassed in 90.10 seconds =
```

**Comment by charris** [comment]
The two failures you report are curious, as nothing has changed regarding the two functions in 1.18.3. Did earlier 1.18 releases pass? Do you get the same errors with different optimization flags?

**Comment by charris** [comment]
We do test with s390x. Do you get the same failure if you don't run with non-debug Python3.8?

**Comment by sandrotosi** [comment]
no failures when running "plain" python3.8, only that single failure using the debug flavor

also not sure if the first comment relates to this issue or not (you mention 2 functions, while there's a single failure here, let me know and i can clarify/investigate further)

**Comment by charris** [comment]
> also not sure if the first comment relates to this issue or not

I was referring to the two issues reported at the time of the comment. Do any of the architectures fail with the non-debug version of Python 3.8? IIRC, there were bugs in the debug versions. It is getting late for any more fixes in 1.18.x, we have just one regression fix planned and we will release before our rackspace time runs out at the end of the month. Any fixes after that will need to wait on 1.19, which you should probable start testing now as the release will be out in about three weeks. Can you build from the repository? You should be able to produce source releases for testing if not.

**Comment by sandrotosi** [comment]
yes, i did report if there are tests failures either with the plain or debug version for python3.8: #16047 #16048 #16049 all have the same (or similar) failures on both plain and debug versions.

it's fine to wait for fixes for the 1.19.x series, but i'm afraid i dont have much time to test what's on master right now, as most of my time in Debian is spent working to remove python2 from the distribution. but when you're gonna but a beta or RC release, i'll definitely try to upload it asap and report back

**Comment by rgommers** [comment]
It's both a corner case of a not-often-used function _and_ only occurs in a debug build. So I'd say add a `skipif` in Debian and don't spend time on this. If it happens again for 1.19.0 we could take over the `skipif` in NumPy for this platform.

**Comment by seberg** [comment]
Yeah, I wonder if `%` itself (and actually possibly pythons `math.gcd`) will have similar problems on that architecture, since that is the backbone of the gcd calculation.

**Comment by sandrotosi** [comment]
just note that this build failures are not fatal for the debian build, as they tend to appear from time to time on this uncommon architectures. So i usually just let them fail and report the error back her for your attention.

if you decide to add a skipIf i'd just leave it there, but i usually dont add it as patch in debian as then i'd have to disable them with every new release, detect which ones are still valid, remove the ones that are fixed, etc etc; feels just extra work with little gain

**Comment by sandrotosi** [comment]
this is still happening on 1.8.4:

```
=================================== FAILURES ===================================
___________________ TestRationalFunctions.test_gcd_overflow ____________________

self = <numpy.core.tests.test_umath.TestRationalFunctions object at 0x3ffa47bb2d0>

    def test_gcd_overflow(self):
        for dtype in (np.int32, np.int64):
            # verify that we don't overflow when taking abs(x)
            # not relevant for lcm, where the result is unrepresentable anyway
            a = dtype(np.iinfo(dtype).min)  # negative power of two
            q = -(a // 4)
>           assert_equal(np.gcd(a,  q*3), q)
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: -2305843009213693952
E            DESIRED: 2305843009213693952

a          = -9223372036854775808
dtype      = <class 'numpy.int64'>
q          = 2305843009213693952
self       = <numpy.core.tests.test_umath.TestRationalFunctions object at 0x3ffa47bb2d0>

tmp/usr/lib/python3/dist-packages/numpy/core/tests/test_umath.py:2599: AssertionError
```

**Comment by anirudh2290** [comment]
> We do test with s390x. Do you get the same failure if you run with non-debug Python3.8?

are these tests part of the ci for every PR or do these tests run elsewhere ? I tried looking, in the CI I mostly found tests for x64, i686.

**Comment by rgommers** [comment]
> are these tests part of the ci for every PR or do these tests run elsewhere ? I tried looking, in the CI I mostly found tests for x64, i686.

There's an `s390x` job in `.travis.yml`, it runs the test suite on every PR.

**Comment by sandrotosi** [comment]
This is still happening with 1.19.0rc2: https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=s390x&ver=1%3A1.19.0%7Erc2-2&stamp=1591492021&raw=0

**Comment by sandrotosi** [comment]
This is still happening with 1.19.0 final: 

```
=================================== FAILURES ===================================
___________________ TestRationalFunctions.test_gcd_overflow ____________________

self = <numpy.core.tests.test_umath.TestRationalFunctions object at 0x3ff77505e60>

    def test_gcd_overflow(self):
        for dtype in (np.int32, np.int64):
            # verify that we don't overflow when taking abs(x)
            # not relevant for lcm, where the result is unrepresentable anyway
            a = dtype(np.iinfo(dtype).min)  # negative power of two
            q = -(a // 4)
>           assert_equal(np.gcd(a,  q*3), q)
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: -2305843009213693952
E            DESIRED: 2305843009213693952

a          = -9223372036854775808
dtype      = <class 'numpy.int64'>
q          = 2305843009213693952
self       = <numpy.core.tests.test_umath.TestRationalFunctions object at 0x3ff77505e60>

tmp/usr/lib/python3/dist-packages/numpy/core/tests/test_umath.py:2651: AssertionError
```
full log [here](https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=s390x&ver=1%3A1.19.0-1&stamp=1592789284&raw=0)

**Comment by sandrotosi** [comment]
closing outdated issues i reported long ago
