### ISSUE TITLE
import_array() get a error "numpy.core.multiarray failed to import"

### ISSUE THREAD

**Issue by ccl-private** [numpy/numpy#16040]
I include  "numpy/arrayobject.h" in my c++ code.
when I run import_array(), an error ocurred:"RuntimeError: _ARRAY_API is not PyCapsule object".
Then I used PyErr_Print(), and I got   "numpy.core.multiarray failed to import".
I don't known why this happened.

### C++ code :

```c++
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
#include <Python.h>
#include "numpy/arrayobject.h"

int init_numpy()
{
	import_array();
}

int main(int argc, char **argv)

{
	Py_Initialize();
	
	init_numpy();

	PyErr_Print();
       Py_Finalize();
       return 0;
}
```

### Numpy/Python version information:
numpy 1.17, python3.5

**Comment by mattip** [comment]
when you run `python -c"import numpy"` exactly in the same environment and directory that you run the compiled code, does it succeed?

**Comment by ccl-private** [comment]
![image](https://user-images.githubusercontent.com/36214675/79955082-dae87780-84b0-11ea-86b1-6f13cf8c479f.png)
python -c"import numpy" succeed.

**Comment by mattip** [comment]
Which python are you linking with? it should be the same as the one you successfully import with, check `python -c "import sysconfig; print(sysconfig.get_config_var('BLDLIBRARY'))"`

**Comment by ccl-private** [comment]
![image](https://user-images.githubusercontent.com/36214675/79966648-50a80f80-84c0-11ea-81f5-6bc60119a152.png)
I use python3 via CMakeList.txt.
And this is part of cmake's output. It seems that python3 is found.
![image](https://user-images.githubusercontent.com/36214675/79967080-f491bb00-84c0-11ea-97a3-23f37c6db35e.png)

**Comment by ccl-private** [comment]
I uninstalled python-numpy via "apt purge", and a new error occured.
![image](https://user-images.githubusercontent.com/36214675/79967854-f445ef80-84c1-11ea-976b-25815e950e98.png)
Am I still using python2?

**Comment by ccl-private** [comment]
here is may PATH and PYTHONPATH
![image](https://user-images.githubusercontent.com/36214675/79969313-e8f3c380-84c3-11ea-9bae-514398168743.png)
In /usr/bin, there are having python2 and python3 both.
![image](https://user-images.githubusercontent.com/36214675/79969500-2f492280-84c4-11ea-8218-b94051b082de.png)

**Comment by ccl-private** [comment]
my default python is python2.

**Comment by anirudh2290** [comment]
As mentioned by @mattip this is probably happening because 1, that is mixing up of python2 and python3. I think you need to make sure : you are using python3 include dirs, using numpy include dirs for this exact python3 version and linking with the corresponding python3 libs and numpy libs installed for the python3 version.

**Comment by ccl-private** [comment]
I find the reason. 
This is because I include ROS(catkin) in my CMakeList.txt. ROS includes a python2 environment itself, so I always use python2, even though I set python3 in CMakeList.txt after.
Without ROS, it works fine.

__________CMakeList.txt______________

cmake_minimum_required(VERSION 2.8)

project( face_v3_c )

find_package( OpenCV REQUIRED )

# find_package(catkin REQUIRED COMPONENTS
 # roscpp
 # std_msgs
 # sensor_msgs
 # cv_bridge
 # image_transport
# )

# include_directories(
	# ${catkin_INCLUDE_DIRS}
# )

# find_package (Python3 COMPONENTS Interpreter Development)
include_directories("/usr/include/python3.5")
link_directories("/usr/lib/python3.5/config-3.5m-aarch64-linux-gnu")

# numpy
include_directories("/usr/local/lib/python3.5/dist-packages/numpy/core/include")

add_executable( face_v3_c simple.cpp )
target_link_libraries( face_v3_c ${OpenCV_LIBS} ${catkin_LIBRARIES} python3.5 )
