### ISSUE TITLE
TypeError: only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by karippery** [numpy/numpy#16045]
Hello friends,
I am new in python platform. I got a strange error.  when I run my program sometime it works sometimes not.  I didn't understand the problem yet.  I  believe this is because of numpy. 
i attach my code here 
population.py
```
import numpy as np


class Population:
    def __init__(self, population_len, cromosome_len):
        self.population_len = population_len
        self.cromosome_len = cromosome_len

    def create_population(self):
        population = np.random.randint(2, 6, size=(self.population_len,self.cromosome_len))
        return population


    def find_fitness_rate(self):
        fitnessrates = np.array(self.sum(axis=1))
        return fitnessrates


    def select_parents_MaxValue(self):
        find_index = np.argmax(Population.find_fitness_rate(self))
        firstwinner = np.array(self[find_index])
        largest=max(Population.find_fitness_rate(self))

    # find second winner in the population
        sort_second_pop = np.sort(Population.find_fitness_rate(self))
        second_element_index = np.where(Population.find_fitness_rate(self) == sort_second_pop[-2] )
        secondwinner=np.array(self[second_element_index[0]])
        if len(secondwinner) > 1:
            secondwinner = secondwinner[1]
        else:
            secondwinner[0]
        return firstwinner, secondwinner

```
```
crossover.py
import random
import numpy as np

class Crossover:
    def __init__(self, parent_1, parent_2):
        self.parent_1 :  parent_1
        self.parent_2 = parent_2

    def whole_arithmetic_crossover(parent1, parent2 ,alfa):
        cross_child1 = []
        cross_child2 = []
        for index, gen in enumerate(parent1,start=0):
            y = parent2[index]
            new_gen = alfa*gen+(1-alfa)*y
            cross_child1=np.append(cross_child1,[float(new_gen)],axis=0)
            #cross_child1 = np.append(cross_child1, np.expm1(new_gen), axis=0)
        for index,gen in enumerate(parent2, start=0):
            x = parent1[index]
            new_gen = alfa*gen+(1-alfa)*x
            cross_child2 = np.append(cross_child2,[float(new_gen)],axis=0)
        return cross_child1,cross_child2



```
**error i got** 

> Traceback (most recent call last):
>   File "D:///app.py", line 14, in <module>
>     cross_AC = Crossover.whole_arithmetic_crossover(parent1,parent2,0.5)
>   File "D:\\\crossover.py", line 16, in whole_arithmetic_crossover
>     cross_child1=np.append(cross_child1,[float(new_gen)],axis=0)
> TypeError: only size-1 arrays can be converted to Python scalars

**Comment by seberg** [comment]
This is not the best place to ask such questions really. If you can ask people locally that would be much better (or maybe on other websites).
In any case, to help you track this down you should carefully look at all the data you are putting in, and disect your commands. I will tell you now that this error will be in `float(new_gen)` and the error refers to `new_gen` as the array which is not of size-1.

Having less commands on the same line, or using a debugger will make tracking down such things easier.

**Comment by linehammer** [comment]
The error "only length-1 arrays can be converted to Python scalars" is raised when the function expects a single value but you pass an array instead. This means that when you're trying to cast into an integer something that isn't just one scalar. Once you will look at the call signature of np.int, you'll see that it accepts a single value, not an array. 

What you can do is use .[astype](http://net-informations.com/ds/pd/default.htm)(int)
