### ISSUE TITLE
NumPy mailling list banning all subscriptions

### ISSUE THREAD

**Issue by ellisonbg** [numpy/numpy#16058]
It looks like the NumPy mailing list is banning all subscribers. I tried to subscribe under 3 different emails and got the following message each time:

"The email address you supplied is banned from this mailing list. If you think this restriction is erroneous, please contact the list owners at numpy-discussion-owner@python.org. "

I realize I am not following the instructions here (I can do that if needed), but wanted to see if this is the intentional user flow to sign up (I hope not).

**Comment by pv** [comment]
Subscription should be open to all. I'm not sure who is the list
administrator, but maybe following the instructions works...

**Comment by seberg** [comment]
That is pretty bad... Not sure either who is owner though. I just tried at https://mail.python.org/mailman/subscribe/numpy-discussion to be sure, and it worked fine for my berkeley address.

**Comment by rgommers** [comment]
It's admin-ed by the python.org admins, none of the NumPy maintainers have permissions. @ellisonbg if you email `numpy-discussion-owner@python.org`, please Cc/Bcc me - it's helpful to have a history of issues in my email archive. 

In the last 1-2 years this has been working fine, before migrating to python.org we had way more issues.

**Comment by ellisonbg** [comment]
I have emailed them and will report back.

**Comment by seberg** [comment]
Hopefully this issue resolved itself?  There was also the move to mailman3 which may have helped.  If not, please ping or open a new issue.
