### ISSUE TITLE
Original error was: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by vicarious11** [numpy/numpy#16062]
Hi , 
I am using Pycharm to create a venv in my project. I am using pandas for data analysis. The code runs fine for sometime but after half n hour and so of running my main file, it throws the error.

Reinstalling the packages, fixes it for a short duration but i am unable to find a permanent fix for this

This is the error.

### Error message:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/Users/anarchy/Desktop/Everything/Template/Projects/Python/log-analytics/venv/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by seberg** [comment]
@vicarious11 please check the PyCharm documentation link I put here: https://github.com/numpy/numpy/wiki/ImportError-Troubleshooting#using-anacondaconda-python-within-pycharm (the site will move)

**Comment by vicarious11** [comment]
I still dont understand how this will resolve my issue.

**Comment by seberg** [comment]
It sounds like you are not correctly activating your venv, that is the best guess and honestly the best advice I am able to give.

**Comment by vicarious11** [comment]
I set the project interpreter in the Pycharm to my current directory folder and use python3.7.
Anyway i will check it out. Sad.

**Comment by seberg** [comment]
Well, its not something NumPy can control and people are working hard on providing you a way to have different environments and multiple Python installations work side by side.

Unfortunately, that means you have to take care when setting things up. This is an issue of PyCharm, so if you feel PyCharm can help you make that easier, maybe you can take it up there. The only PyCharm documentation I am aware of, is the one that was linked above: https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html and the general conda help on virtual environments: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment

Maybe they are forcing virtual environments on users too strongly, but the issues without them would be even more confusing. I hope it helps you, but there is really no reason to complain about the situation here, we have no control over it, and are simply trying to help if we can.
