### ISSUE TITLE
Mailmap update for 1.19.0

### ISSUE THREAD

**Issue by charris** [numpy/numpy#16082]
Could the following folks please reply to this issue with a full name and mailing address. We need it in assigning credit for the PRs in the NumPy 1.19.0 release.

- [x] @Keewis
- [ ] @Jim
- [ ] @Anthony
- [ ] @Adam
- [x] @Mibu287
- [x] @Qiyu8
- [x] @and-sang
- [x] @hippo91
- [ ] @jfbu
- [x] @kishimoto-banana
- [x] @m-podhajski
- [ ] @nglinh
- [x] @panpiort8
- [x] @sgasse

TIA,

Chuck

**Comment by Mibu287** [comment]
@charris : My name and email is Bui Duc Minh - buiducminh287@gmail.com

**Comment by Qiyu8** [comment]
@charris : My name and email is Chunlin Fang - fangchunlin@huawei.com

**Comment by kishimoto-banana** [comment]
@charris  : My name and email is Masashi Kishimoto - drehbleistift@gmail.com

**Comment by panpiort8** [comment]
@charris I'm Piotr Gaiński dociebieaniuszlem@gmail.com

**Comment by sgasse** [comment]
@charris My name is Simon Gasse - simon.gasse@gmail.com

**Comment by hippo91** [comment]
@hippo91 : my name and email address are Guillaume Peillex -
guillaume.peillex@gmail.com

Thanks.

Le lun. 27 avr. 2020 à 02:53, Charles Harris <notifications@github.com> a
écrit :

**Comment by m-podhajski** [comment]
@charris  I'm Marcin Podhajski podhajskimarcin@gmail.com

**Comment by and-sang** [comment]
my name's Andrea Sangalli - and-sang@outlook.com

**Comment by keewis** [comment]
@charris, my name is already in `.mailmap` on master (and the information there is up-to-date).

**Comment by jfbu** [comment]
@charris No need to credit in my case. Good luck with the release, congratulations on great work.
