### ISSUE TITLE
np.set_printoptions Issue for single values evaluation

### ISSUE THREAD

**Issue by ThomasGl** [numpy/numpy#16089]
### Code Used:

```python
import numpy as np

leftLimit = -1
rightLimit = 3
delta=0.05

z=np.arange(leftLimit,rightLimit+delta,delta)
np.set_printoptions(precision=5,suppress=True)
```

### Crucial Error if using np.where(z==variable):

The evidence of the error in attempt of use is presented by:
```python
print(z)#Such present the correct values

print(z[index_position])#If analyzed individually it shows different values
```

The used in VsCode was:

![code_python](https://user-images.githubusercontent.com/56161967/80376529-9d199380-88a2-11ea-8ffe-1662411f22cb.PNG)

with an output given as:

![output_python](https://user-images.githubusercontent.com/56161967/80376557-aacf1900-88a2-11ea-9b4e-81da3266e69e.PNG)

Thus, we can observe there's a flaw in design and the value given is not an actual conversion to a zero float/double with precision of 5 decimal cases. Such, causes issues to tracking when using:

np.where(z==position)

as the expected value isn't defined due to this crucial mistake
 

### Numpy/Python version information:

Output: 1.18.3 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
I think `np.set_printoptions` only affects arrays - scalars are printed in a way that matches python. @ahaldane might remember if this is deliberate.

**Comment by WarrenWeckesser** [comment]
I suspect there are two issues here.  One is: why is z[20] not exactly 0? `arange` with floating point values performs floating point calculations, and suffers from the same imprecision that all floating point calculations do; see, e.g. ["What Every Computer Scientist Should Know About Floating-Point Arithmetic"](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html).

As you've seen, the value `z[20]` is not *exactly* 0; similarly, the value `z[21]` is not exactly 0.05.  If you `print(z[21])`, you'll get something like `0.05000000000000093`. (In fact, 0.05 can't be represented exactly in 64 bit floating point.)

The other issue might be: why does the output generated by `print(z)` show `0.` for `z[20]` when the actual value of `z[20]` is `8.881784197001252e-16`?  That is a consequence of using `suppress=True` in `set_printoptions()`, as explained in the [`set_printoptions()` docstring](https://numpy.org/devdocs/reference/generated/numpy.set_printoptions.html).  The confusing part might also be that the docstring does not explain that `set_printoptions()` only affects the output for *arrays*.  The output format for a scalar does not use those options. `z[20]` is a scalar, so `print(z[20])` shows the full precision.

**Comment by ThomasGl** [comment]
Thanks guys, so just concluding the issue, `set_printoptions()` its only a printing procedure but does not change the value of each component in the array? It seems very odd. By the way, I found a solution after some research+try & errors here it is:

```python
z=np.around(np.arange(leftLimit,rightLimit+delta,delta),5)
```
With the correction:
![code_python2](https://user-images.githubusercontent.com/56161967/80410941-08c82480-88d4-11ea-9570-121aa6fb990e.PNG)

Finally I get:
![output_python2](https://user-images.githubusercontent.com/56161967/80410994-21383f00-88d4-11ea-96f0-44070dff7627.PNG)

I solved my problem, yet I am not sure if its a issue in numpy library, anyone?

**Comment by seberg** [comment]
@ThomasGl just to be sure, please do not confuse printing vs. actual values. What you are doing there is changing the values by rounding them, `printoptions` changes how they are shown on the console when you print them out.
If all you want to do is print it at that point, sure go ahead and round. But if you do anything except printing be sure that rounding makes sense.

Since the difference only concerns *printing*, there is no difference between elements (components) and the full array or so. It is just that you can choose to show less precision when printing arrays, and for a single number you have to use a different method, e.g. `print(f{z[20]:.2f})`.

Closing, since I think we have other issues open about the difference and Warren explained in detail all the things involved in printing numpy arrays.

**Comment by ThomasGl** [comment]
Amazing Thank You!
