### ISSUE TITLE
ImportError: Unable to load the required dependencies

### ISSUE THREAD

**Issue by skregas** [numpy/numpy#16096]
Attempting to run my python project in DEBUG mode in Visual Studio Code. I'm using a virtual env
build with: `conda env myenv`
I've double-checked the PATH (not using PYTHONPATH) and Visual Studio Code is pointed at the correct env. 
- Installed Python through the Anaconda project. Python version 3.7
```
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
```
- Uninstalled and reinstalled numpy using the conda package manager: 
```
$ conda remove numpy
$ conda install numpy
```
 - OS: Windows 10 64-bit

- Python 3.8 is also installed under Program Files
```
C:\Users\c625ksz>python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
The Python 3.8 installation does not have numpy installed with it.

**Exception has occurred: ImportError
Unable to import required dependencies:
numpy:** 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\c625ksz\AppData\Local\Continuum\anaconda3\envs\default-motor-env\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

**Comment by mattip** [comment]
> run my python project in DEBUG mode 

Try running in RELEASE mode with debug symbols and no optimization.  Full DEBUG mode on windows changes the names of the DLLS python expects to find, so if you wish to truly work in DEBUG mode you will need to recompile the entire stack of python modules you work with.

**Comment by skregas** [comment]
In RELEASE the code runs fine, no errors importing numpy

**Comment by mattip** [comment]
Great to hear. Closing, please reopen if there is more to discuss.
