### ISSUE TITLE
Issues on importing numpy

### ISSUE THREAD

**Issue by Frank-KHY** [numpy/numpy#16099]
When I use the "python.exe" in Anaconda3 to run my python codes(which imports numpy),  this error message pops up.

-------------------------------
C:\Users\frank\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\frank\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\frank\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\frank\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: 找不到指定的模組。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Codes\Python\Cylinder_Reflection\main.py", line 2, in <module>
    from vpython import*
  File "C:\Users\frank\anaconda3\lib\site-packages\vpython\__init__.py", line 52, in <module>
    from numpy import arange
  File "C:\Users\frank\anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\frank\anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\frank\anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: 找不到指定的模組。

----
This error appeared after I recently update my packages using conda.
I have tried to reinstalled the entire anaconda, remove and reinstall numpy, install numpy via pip instead of conda, but none of these solve the problem.
However, this error won't occur when I use jupyter notebook.

python version : 3.7.6.final.0
numpy version : 1.18.3 (installed via pip) and 1.18.1 (installed via conda)
operating system : Windows 10

**Comment by seberg** [comment]
We are in the process of revising that error message and pointing to a website with help instead. Could you see whether this document would help you?:

https://github.com/numpy/numpy/blob/d530d23b0fc792e63cca97d88799b5fecac805ef/doc/source/user/troubleshooting.rst

**Comment by saguerraty** [comment]
I'm getting the exact same issue when using python installed through Anaconda 3. I'm using a virtual environment with python 3.6.9 and numpy 1.18.1 on windows 10 with vs code. I tried reinstalling numpy through the anaconda prompt and continue to see the same issue :/

**Comment by mattip** [comment]
Did you follow the reccomendation at the top of the message 
> UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service

If so, did you read the page [linked to above](https://github.com/numpy/numpy/blob/d530d23b0fc792e63cca97d88799b5fecac805ef/doc/source/user/troubleshooting.rst), especially the part about activating your environment?

**Comment by saguerraty** [comment]
What seems to be causing the issue is the conda prompt. I fixed the path for my user in vs to make sure the environment I'm working in is active when running the code and closed the conda cmd prompt in windows and that did the trick :) seems like an issue for the people at anaconda in my case.

**Comment by Frank-KHY** [comment]
I found that my python.exe won't automatically activate the environment (it seemed to do that before), so I add a line to activate the environment and everything works now. Thanks for everyone's helping!
