### ISSUE TITLE
Making np.timedelta64 handle keyword arguments

### ISSUE THREAD

**Issue by leifdenby** [numpy/numpy#16095]
I recently had an issue where I was trying to increment a `np.datetime64` object using `np.timedelta64`, but couldn't get the `timedelta64` object be anything but zero. Eventually I found out it was because `np.timedelta64` ignores all keyword arguments, and I was expecting it to have the same call signature as `datetime.timedelta`. I think it would be nice if `np.timedelta64` did accept keyword arguments or issued a warning that it doesn't. I would be happy to contribute this if people think it would be useful.

### Reproducing code example:

It would be nice if the following was `True`, or at least `np.timedelta64` issued a warning when keyword arguments are passed in (and ignored).

```python
import numpy as np
import datetime as dt

np.timedelta64(dt.timedelta(seconds=10)) == np.timedelta64(seconds=10)
```

### Numpy/Python version information:

1.18.3 3.6.3 |Anaconda, Inc.| (default, Dec  5 2017, 17:30:25)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by eric-wieser** [comment]
Fixed already in master, #15446
