### ISSUE TITLE
np.unique does not appear to handle dtype=object correctly

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#16093]
Code example:

```python
import numpy as np

s1 = {1, 2}
s2 = {1, 3, 4}
s3 = {1, 4}

s = [s1, s2, s1, s3]
a = np.array(s)

u, c = np.unique(a, return_counts=True)

print(repr(u))
print(repr(c))
print(a[0] is a[2], a[0] == a[2])
print(u[0] is u[2], u[0] == u[2])
```
Output

```
array([{1, 2}, {1, 3, 4}, {1, 2}, {1, 4}], dtype=object)
array([1, 1, 1, 1])
True True
True True
```

No error is thrown, but `u` is equal to `a` and all the counts are 1. The references are identical in elements 0, 2 of `s`, `a` and `u`. I would expect `unique` to treat at least identical references as identical. Applying `__eq__` for `dtype=object` would be preferable. The least preferable option would be documenting the deficiency and accepting it. 

Numpy version: 1.16.3
Sys version: 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]

**Comment by seberg** [comment]
unique uses sorting, there is no way it can work reliable with objects that:
1. Provide comparison operations
2. Do *not* provide an order.

Since I am not aware that python gives a way to notice that (it quacks like an object with a defined order), I doubt there is anything easy to do...
