### ISSUE TITLE
Specifying `otypes` in `vectorize` crashes default argument function.

### ISSUE THREAD

**Issue by hylkedonker** [numpy/numpy#16120]
Whenever using `vectorize` on a function with a default value argument (e.g., `def f(x, y=1.0)`) without passing the `otypes` argument, the function `vectorize` works as expected. When, however, the `otypes` argument is specified (with e.g., `otypes=[float]`), calling the vectorized function without passing the default value argument leads to a `ValueError: invalid number of arguments`.

### Reproducing code example:

```python
import numpy as np

def f(x, y=1.0):
    return x * y

f = np.vectorize(f)
g = np.vectorize(f, otypes=[float])

# Evaluate function specifying the default value argument.
f(np.arange(3.0), 1.0)
g(np.arange(3.0), 1.0)

# Error when no default argument is passed.
f(np.arange(3.0))
g(np.arange(3.0))  # Crash!
```

### Error message:
```
Traceback (most recent call last):
  File "function.py", line 17, in <module>
    g(np.arange(3.0))  # Crash!
  File "/home/hylke/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/hylke/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2167, in _vectorize_call
    outputs = ufunc(*inputs)
ValueError: invalid number of arguments
```

### Numpy/Python version information:

1.18.3 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0]

**Comment by WarrenWeckesser** [comment]
This bug exists in the master branch too.  I have a potential fix in progress.

**Comment by WarrenWeckesser** [comment]
Proposed fix is in https://github.com/numpy/numpy/pull/16125.

**Comment by arvoelke** [comment]
Is there a work-around for this? I want to be able to support older versions of NumPy and this is preventing that from happening. I'd prefer to keep `otypes` for efficiency.

Curiously, this doesn't always seem to happen. Whether or not the error is triggered can also depend on some additional context (e.g., whether or not some completely separate unit tests have been run). I haven't quite been able to isolate that, but it does happen deterministically.
