### ISSUE TITLE
flag to enable debug logs obtained when NPY_UF_DBG_TRACING=1

### ISSUE THREAD

**Issue by anirudh2290** [numpy/numpy#16135]
It would be nice to have something like :
```
python3 setup.py build_ext --devlog --inplace -j $(nproc)
```

which would enable the detailed logging in ufunc by setting NPY_UF_DBG_TRACING and other such flags, if there are any.

**Comment by seberg** [comment]
I think I would be happy if we add some convenient flags as env variables or build options (maybe with a short note in runtests.py how to use them), or a list of such options in the dev help.
To be honest, I have rarely used those debug print options, they are useful, but mainly if you debug very deep stuff in the iterator.  I am dubious that generally enabling all of them (if there are actually more than iterator and ufunc) is useful, it would probably be too spammy.

**Comment by seberg** [comment]
Btw. on a related note, if you are using an editor which relies on `CMakeLists.txt`, it is fairly straight forward to point the `CMakeLists.txt` to the files created when running `python3 runtests.py`, so that at least 9% of the IDE features work correclty (one trick I would love is to figure out if I could make my IDE learn how to deal with `.c.src` files, but I guess that is too much).

I could provide a super-hacky cmakelist.txt...

**Comment by anirudh2290** [comment]
i use ctags and cscope with vim and i generate my cscope files after the build so the .c file names are cached. I am able to jump into the .c files  when reading code. and gdb, also jumps into the .c.src files which i was initially surprised about. why i found this `NPY_UF_DBG_TRACING=1` was to figure out the code flow, which may be useful for beginners like me.

**Comment by seberg** [comment]
Yeah, all of that works for me, just the live syntax analysis of the c.src files doesn't work since its not valid C code after all...

**Comment by anirudh2290** [comment]
> Yeah, all of that works for me, just the live syntax analysis of the c.src files doesn't work since its not valid C code after all...

ok, got it, yes that cmakelists.txt will be useful for me sometime in the future when I get to modifying these .c.src files !

**Comment by rgommers** [comment]
Is this still relevant? There's only two files which use this define, and in `ufunc_object.c` it's unconditionally set to `0`:
```
numpy/core/src/umath/ufunc_type_resolution.c
31:#ifndef NPY_UF_DBG_TRACING
32:    #define NPY_UF_DBG_TRACING 0
1591:#if NPY_UF_DBG_TRACING

numpy/core/src/umath/ufunc_object.c
68:#define NPY_UF_DBG_TRACING 0
70:#if NPY_UF_DBG_TRACING
2363:#if NPY_UF_DBG_TRACING
3079:#if NPY_UF_DBG_TRACING
3497:#if NPY_UF_DBG_TRACING
```

**Comment by mattip** [comment]
> it's unconditionally set to 0

I used this once or twice by editing the file and setting `#define NPY_UF_DBG_TRACING 1`. I don't really think we need more than that.

**Comment by seberg** [comment]
Yeah, let's close it, this is very occasionally useful, but it isn't important to be more available really.  If anyone ever wants to expand or reduce it, fine with me too.
