### ISSUE TITLE
DLL load failed on Visual Studio Code

### ISSUE THREAD

**Issue by ayahea** [numpy/numpy#16139]
VSC is not able to import numpy. I'm using Anaconda3, so I made sure it was updated and reinstalled numpy, and even used different numpy versions, but VSC still would not recognize numpy. Not sure if it has to do with getting an error when it automatically runs "conda activate base." 

### Reproducing code example:

```python
import numpy
x = numpy.array([1,2,3])
print(x)
```

### Error message:

```
PS C:\Users\**\Desktop\**> conda activate base
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script     
file, or operable program. Check the spelling of the name, or if a path was included,    
verify that the path is correct and try again.
At line:1 char:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundExcepti  
   on
    + FullyQualifiedErrorId : CommandNotFoundException
 PS C:\Users\**\Desktop\***t> & C:/Users/**/Anaconda3/python.exe "c:/Users/**/Desktop/**/test.py"
Traceback (most recent call last):
  File "C:\Users\**\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\**\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in 
<module>
    from . import overrides
  File "C:\Users\**\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/**/Desktop/Courses/CS AI/Tournament/test.py", line 1, in <module>     
    import numpy
  File "C:\Users\**\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\**\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\**\Anaconda3\python.exe", 
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
```

### Numpy/Python version information:

Numpy 1.17.4 (I also tried 1.18.1) 
Python 3.7.3

**Comment by mattip** [comment]
Activating the environment is needed. The first step is to fix that error, then if you are still not able to load numpy please update this issue.

**Comment by ayahea** [comment]
How do I activate the environment? VSC runs Python fine, it's just a few libraries that it fails to import--does this still mean the environment is not activated? The command in VSC "conda activate base" is not recognized. When I "select interpreter" for Python, there is only one option available and it seems to be the correct one "Python 3.7.3 64-bit ('base':conda) ~\Anaconda3\python.exe".

**Comment by seberg** [comment]
There is a comment here that claims that VSCode is just not able to cope with anaconda (I guess activate it correctly): https://github.com/numpy/numpy/issues/15343

There is a comment here: https://github.com/numpy/numpy/issues/15183 which looks like it may have a way to make VSCode actually do the right thing.

If you figure this out, can you post the solution so we can include it in our new troubleshooting page? (https://numpy.org/devdocs/user/troubleshooting-importerror.html)

**Comment by ayahea** [comment]
Thank you, following the steps in https://github.com/numpy/numpy/issues/15183#issuecomment-603575874 I was able to get it to work.

**Comment by seberg** [comment]
Seems like the correct thing to link to would be https://code.visualstudio.com/docs/python/environments
