### ISSUE TITLE
trapz() should raise a warning if x is not sorted.

### ISSUE THREAD

**Issue by brpy** [numpy/numpy#16136]
trapz computes wrong result if x is not sorted. Raising a warning if x is out of order will be quite helpful.

**Comment by rossbar** [comment]
Generally, there are even more potential "problems" than `x` not being ordered. For instance, `x` is also assumed to be unique, but this is not checked either. More input validation could be added to `trapz` to catch things like this, but IMO this might get noisy - I think it's fine to rely on the user to meet the conditions on the input necessary for the trapezoidal rule to work as expected.

The documentation could be improved to explicitly state the conditions that `x` is assumed to meet, which in principle provides users with better guidance without the overhead/noise of extra input checking.

**Comment by brpy** [comment]
Ok got it. I would love to contribute to documentation. How do I do it?

**Comment by rossbar** [comment]
Thanks for expressing your interest! There's some [documentation](https://numpy.org/devdocs/dev/howto-docs.html) giving an overview on contributing to NumPy's documentation.

In this particular case, you would be modifying the `trapz` function docstring. There is more documentation that covers the general processes of getting, modifying, and building the NumPy source [here](https://numpy.org/devdocs/dev/index.html). Hopefully this info is helpful!

**Comment by brpy** [comment]
Thank you. Shall I add it in the 'Notes' section?

**Comment by rossbar** [comment]
That would work - or you could add it to the parameter description for `x`

**Comment by eric-wieser** [comment]
I don't agree with the discussion here. When passed two arguments, `trapz` approximates

![image](https://user-images.githubusercontent.com/425260/81393584-86800180-9118-11ea-8ba3-1ac8849098ce.png)

namely, the area between a curve and the x axis. If your curve goes back on itself, then it has the usual meaning of counting as negative area towards the total sum.

**Comment by brpy** [comment]
> I don't agree with the discussion here. When passed two arguments, `trapz` approximates
> 
> ![image](https://user-images.githubusercontent.com/425260/81394007-2d649d80-9119-11ea-99d9-6362f46caf85.png)
> 
> Note that when you do not pass `x`, then `trapz` assumes `x(t) = t` meaning `dx/dt = 1`.
> 
> namely, the area between a curve and the x axis. If your curve goes back on itself, then it has the usual meaning of counting as negative area towards the total sum.

Yes `trapz()` mathematically does the correct thing. But I think it has to be specified in the docs that `trapz` integrates `y` in the **order of samples specified** `x`.

I had this issue when points were generated in a non-sequential order wrt. `x`. I had assumed `trapz` would take this into account and give a result I was expecting i.e, Area under the graph but It gave a mathematically correct answer.

So, it would be helpful if docs mentioned that integration is done in the **order of samples specified** `x`.

I could make changes to my PR if you agree.
Else, please feel free to close the issue

**Comment by eric-wieser** [comment]
You're right, the docs are still pretty vague here, and need _something_ changed. Feel free to update your PR to try and address that.

**Comment by rossbar** [comment]
Sorry for not being thorough enough in the initial discussions - I hope I didn't lead you too far into the weeds @brpy - that's a really nice problem statement you offer above.

**Comment by brpy** [comment]
> Sorry for not being thorough enough in the initial discussions - I hope I didn't lead you too far into the weeds @brpy - that's a really nice problem statement you offer above.

Not an issue. Your discussion helped me understand the overhead when `x` is checked for sorted order and improving docs would be a better choice as you said.

**Comment by brpy** [comment]
PR #19041 fixes this.

Closed!
