### ISSUE TITLE
Issue with numpy from fresh Anaconda install

### ISSUE THREAD

**Issue by samuelbloom2** [numpy/numpy#16143]
I made a fresh install of Anaconda for Windows from the link 
https://repo.anaconda.com/archive/Anaconda3-2020.02-Windows-x86_64.exe
and upon executing from the Spyder console `import numpy` I get the error
> Traceback (most recent call last):
> 
>   File "C:\Users\Sam\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 16, in <module>
>     from . import multiarray
> 
>   File "C:\Users\Sam\AppData\Roaming\Python\Python37\site-packages\numpy\core\multiarray.py", line 12, in <module>
>     from . import overrides
> 
>   File "C:\Users\Sam\AppData\Roaming\Python\Python37\site-packages\numpy\core\overrides.py", line 9, in <module>
>     from numpy.core._multiarray_umath import add_docstring, ndarray
> 
> ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-d4cdadb62aa7>", line 1, in <module>
>     import numpy
> 
>   File "C:\Users\Sam\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in <module>
>     from . import core
> 
>   File "C:\Users\Sam\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 47, in <module>
>     raise ImportError(msg)
> 
> ImportError: 
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> Here is how to proceed:
> - If you're working with a numpy git repository, try `git clean -xdf`
>   (removes all files not under version control) and rebuild numpy.
> - If you are simply trying to use the numpy version that you have installed:
>   your installation is broken - please reinstall numpy.
> - If you have already reinstalled and that did not fix the problem, then:
>   1. Check that you are using the Python you expect (you're using C:\Users\Sam\anaconda3\pythonw.exe),
>      and that you have no directories in your PATH or PYTHONPATH that can
>      interfere with the Python and numpy versions you're trying to use.
>   2. If (1) looks fine, you can open a new issue at
>      https://github.com/numpy/numpy/issues.  Please include details on:
>      - how you installed Python
>      - how you installed numpy
>      - your operating system
>      - whether or not you have multiple versions of Python installed
>      - if you built from source, your compiler versions and ideally a build log
> 
>      Note: this error has many possible causes, so please don't comment on
>      an existing issue about this - open a new one instead.
> 
> Original error was: No module named 'numpy.core._multiarray_umath'

After trying 
`conda install numpy`
and restarting the environment, I get the same error. So, I'm following the instructions and posting an issue here. 

I'm running Windows 10 Home 64-bit (10.0, Build 18362). 

Please let me know what other information would be useful to help sort this out. Thank you!

**Comment by seberg** [comment]
Please check the new help page: https://numpy.org/devdocs/user/troubleshooting-importerror.html and see if you find the information you need there.  Did you read all of the information carefully? because the paths it prints do *not* look like anaconda paths.

**Comment by samuelbloom2** [comment]
Hi Sebastian, 
No, the information there did not help. What do you mean by
> the paths it prints do not look like anaconda paths.
?

If it matters, I installed Anaconda as a user on this machine, not as admin.

**Comment by rossbar** [comment]
> the paths it prints do not look like anaconda paths.

I think what he means is that Anaconda/miniconda etc. usually install to a location on the filesystem that has `*conda` somewhere in the name, e.g. `/path/to/your/user/miniconda/bin/python`

The implication here is that you may have multiple installations on your system, and Spyder may be picking up a different one than you intend. Try checking that your `PYTHONPATH` is set up correctly.

**Comment by rossbar** [comment]
I'm going to close this for now due to inactivity - if the issue persists (or you have feedback on the troubleshooting doc) please feel free to re-start the discussion.

**Comment by nfnpmc** [comment]
The new page " https://numpy.org/devdocs/user/troubleshooting-importerror.html " returns 404! This helps a lot!

**Comment by seberg** [comment]
There was a brief outage of most of the website.
