### ISSUE TITLE
12 * 12 and 12**2 behave in different ways with `numpy.int8`

### ISSUE THREAD

**Issue by sshojiro** [numpy/numpy#16150]
I attempted to run machine learning code saving memory, so set integer parameters in data-type `numpy.int8`. I have encountered a bug and just want to report it here. It is interesting for me that `n**2` and `n*n` are carried out in different ways. 

### Reproducing code example:

```bash  
$ python -c 'import numpy;print(numpy.int8(11)*numpy.int8(11))'
121

$ python -c 'import numpy;print(numpy.int8(12)*numpy.int8(12))'
-c:1: RuntimeWarning: overflow encountered in byte_scalars
-112

$ python -c 'import numpy;print(numpy.int8(12)**2) ' 
144

$ python -c 'import numpy;print(numpy.int8(11)*numpy.int8(12))' 
-c:1: RuntimeWarning: overflow encountered in byte_scalars
-124
```

### Numpy/Python version information:

Relevant information is here:

```bash 
conda 4.8.2
Python 3.7.7
msgpack-numpy      0.4.3.2            
numpy              1.18.2 
```

**Comment by eric-wieser** [comment]
`int8` can only represent `x` when `-128 <= x < 128`. That does not include 144.

When you do `n**2`, numpy interprets this as `n**np.int_(2)`. This results in type promotion, which increases the range of the type to include 144.

**Comment by sshojiro** [comment]
@eric-wieser 
Thank you for the instruction!
