### ISSUE TITLE
np.sum enhancement: matmul is faster than sum over axis (for integers)

### ISSUE THREAD

**Issue by sharpblade4** [numpy/numpy#16158]
Hello numpy's community. First, a bit of gratitude: I've been using numpy for a long while and really appreciate the hard work you're all doing. 
To the subject, I'd like to propose a small enhancement to numpy.sum. Background: recently I tried to optimize a component and while playing with the code and measuring performance I noticed that computing a sum over axis is slower than doing so using a matrix-multiplication (i.e. the sum of a matrix ndarray across an axis is slower than multiplying that matrix by a vector of ones in the appropriate shape).  
I'll attach a piece of code to make things clearer:
```
import numpy as np
dim = 10000
vec = np.ones(dim, dtype=np.uint8)
mat = np.random.randint(0, 255, size=(dim,dim), dtype=np.uint8)
np.testing.assert_equal(np.matmul(mat, vec), np.sum(mat, axis=1))

%timeit -n 100 np.matmul(np.random.randint(0, 255, size=(dim,dim), dtype=np.uint8), vec)
>>> 100 loops, best of 3: 852 ms per loop
%timeit -n 100 np.sum(np.random.randint(0, 255, size=(dim,dim), dtype=np.uint8), axis=1)
>>> 100 loops, best of 3: 938 ms per loop
```

I don't know the reason for this gap but I guess that matmul is using vectorian-capabilities of the CPU while sum doesn't. If that's the case, then I'd like to contribute a mini-feature that when applying sum over axis of integers, numpy will check for the support of vectorian operations and if it has them it will compute the sum in matmul instead of the regular way np.sum works. 

I'd like to hear your thoughts, is this really the reason for the better runtime? will it be OK if I'll offer such contribution?

Thanks,
Ron

### Numpy/Python version information:
1.18.3 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Comment by charris** [comment]
This has been noted before. Not sure what the best approach would be here.

**Comment by sharpblade4** [comment]
@charris  what do you think about the following suggestion:
I'll change np.sum such that whenever it is called upon some integer ndarray and along one of the last two axes, instead of dispatching sum call for np.matmul on a generated np.ones in the appropriate shape and dtype.

**Comment by rossbar** [comment]
It seems likely that the speedup in this case is due to BLAS/MKL being used (you could check with `np.show_config`). However, this means that the performance boost for sum would not be general, so I'm not sure it would be worth re-implementing sum in terms of linear algebra calls.

I would consider this more of a "pro-tip" - if you're using accelerated linear algebra backends, you'll get better performance if you can re-formulate your problems in terms of linear algebra operations.
