### ISSUE TITLE
DOC: https://numpy.org/doc/stable/reference/routines.math.html

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#16165]
There are inconsistencies in the short descriptions here.  Sometimes the definite article is used and sometimes not, which makes it hard to see whether two functions do the same job or not, because the texts don't align:

```
fmod(x1, x2, /[, out, where, casting, …]) | Return the element-wise remainder of division.
mod(x1, x2, /[, out, where, casting, order, …]) | Return element-wise remainder of division
```

Then some of the descriptions say "return ...", some say "returns", and some say neither.   Isn't the "return(s)" always redundant?  Obviously the function returns what it has computed.

Finally, the indefinite article in "Returns a true division of the inputs, element-wise" suggests that there is more than one true division.   Is this really the case?

**Comment by eric-wieser** [comment]
I think the indefinite operation in the latter is considering division by 2 vs division by 3 as multiple divisions.

Either way, feel free to make a PR with improved wording.

**Comment by anirudh2290** [comment]
Yes, the doc can use some grammatical fixes and return/ returns uniformly. return may not be in redundant in cases where it may not be clear from the function name as to what it returns. 

> Finally, the indefinite article in "Returns a true division of the inputs, element-wise" suggests that there is more than one true division. Is this really the case?

Not sure if there is a deeper reason but to me it looks like one of the two functions should be deprecated.

**Comment by anirudh2290** [comment]
oops, missed @eric-wieser's earlier comment here.

**Comment by rossbar** [comment]
I think this will need a PR with a concrete proposal to push it forward. I'll leave it open for now, but will close in the near future if there's no proposal to move forward. Please feel free to contribute suggestions!

**Comment by lalitmusmade** [comment]
Working on this as part of the PyDataGlobal 2021 NumPy-SciPy sprint
