### ISSUE TITLE
Should all negative integer power error in numpy ? 

### ISSUE THREAD

**Issue by anirudh2290** [numpy/numpy#16166]
Example:

```
 >>> 2 ** -1
0.5
>>> np.power(0, -1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.
>> np.power(2, -3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Integers to negative integer powers are not allowed.
```

I understand the intention to error on `np.power(0, -1)` in https://github.com/numpy/numpy/issues/7510 . But why are we erroring on all negative integer powers, shouldnt it convert arguments to float and return a float result like python ?

**Comment by seberg** [comment]
Power is faithful to the input types. That should not change just because the input happens to be a scalar and we do not want to inspect all elements for a negative value to decide whether the result may be supposed to be a float.

**Comment by anirudh2290** [comment]
Thanks @seberg that kind of makes sense. Also, found an old discussion on the mailing list here : http://numpy-discussion.10968.n7.nabble.com/Integers-to-integer-powers-td42984.html . Seems like another reason we didn't do this was to avoid breakage for users expecting output dtype to be int outweighs the need for the right answer for negative powers. Also we seem to have np.float_power for (int) ** (negative int) use case. Closing this for now.
