### ISSUE TITLE
PyCharm Type checker warning when correctly initializing a random.BitGenerator

### ISSUE THREAD

**Issue by ndunnewind** [numpy/numpy#16177]
The Type checker inspection in PyCharm (2020.1.1) gives the following warning when trying to initialize a ``random.BitGenerator`` with an ``array_like`` of ints or a ``random.SeedSequence``: ``Expected type 'Optional[int]', got 'SeedSequence' instead``. It tries to interpret the types given for the ``seed`` argument in the docstring:

```python
seed : {None, int, array_like[ints], SeedSequence}, optional
```

However, it only recognizes ``None`` and ``int``.

### Reproducing code example:

```python
from numpy.random import SeedSequence, SFC64
ss = SeedSequence()
rng = SFC64(ss)
rng = SFC64([1, 2, 3])
```

### Numpy/Python version information:

1.18.4 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]

**Comment by bashtage** [comment]
I think this needs to be reported to JetBrians; there does not appear to be anything to do here in NumPy. JetBrains is not parsing array_like[int] and SeedSequence in their crawler.

**Comment by seberg** [comment]
Yeah, we never use the `[int]` qualifier right now possibly. It might be OK to write `sequence of ints` as well (not sure). But overall, docstrings are not perfect typing, I guess. PR to make it prettier are welcome, and if that happens to help your inspection good.

**Comment by bashtage** [comment]
Is NumPy open to type annotations?  I suspect not, but this would be one way to provide precision to PyCharm.

**Comment by seberg** [comment]
Its on the todo list, being worked on in `numpy-stubs` (but is planned to move to numpy proper soon enough)... Its not trivial, but hopefully things be rolling soon.

**Comment by bashtage** [comment]
Are PRs with changes like

```
def __init__(seed: Optional[Union[int,Sequence[int],"SeedSequence"]], ..
```

accepted? Or still waiting to open the typing flood gates( or horror, depending). I have added typing to 30k LOC, and while ultimately worth it (found bugs, better and clearer completion now), getting past the corners of mypy was a real challenge.

**Comment by seberg** [comment]
Hmmm, we have not discussed it much. IIRC, the main issue is that we cannot currently spell `array-like`, but since here `sequence[int]` probably works about as well... The question is whether it makes sense to add it to the very few functions which do not have `array-like` as input.

@person142 is the person to ping on it. My best guess is: *Very* soon, but probably not quite yet.

**Comment by rossbar** [comment]
Support for type annotations has made it into master now. I will close this now, but if there are still issues please reopen to restart the discussion!
