### ISSUE TITLE
Import Numpy working in Spyder but not while executing .py file

### ISSUE THREAD

**Issue by AjayNorman** [numpy/numpy#16178]
Import Numpy working in Spyder but not while executing .py file

### Reproducing code example:

import numpy as np

other imports like openpyxl, os, fuzzywuzzy… everything is working when executing .py file. Import numpy, pandas, matplotib are terminating the execution of the program while double clicking the .py file directly. But when I run the python script inside Spyder, there is no error.

### Numpy/Python version information: 

 **1.18.1 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]**

Python version: 3.7.7

**Comment by ndunnewind** [comment]
I think Spyder is using the Anaconda Python interpreter (in which these packages are installed by default), while double clicking launches a different interpreter (in which e.g. NumPy is not installed). Thus, the latter raises an ImportError. Either try installing these packages or use the interpreter used by Spyder to execute the .py files.

**Comment by AjayNorman** [comment]
Thanks a lot for the response. Can you let me know how do I use the interpreter used by Spyder to execute the .py files? and how do I find out what interpreter Spyder is using to run the code?

**Comment by seberg** [comment]
@AjayNorman please check:

https://numpy.org/devdocs/user/troubleshooting-importerror.html

In particular there is a link to the anaconda user-guide explaining about environment activation, which is almost certainly your problem. I am going to close this for now, feel free to ask more and please tell us if this there is something we can add to that troubleshooting page.

**Comment by AjayNorman** [comment]
Sorry this is not related to environment issue. My environment is already Active

**Comment by mattip** [comment]
> Can you let me know how do I use the interpreter used by Spyder to execute the .py files? and how do I find out what interpreter Spyder is using to run the code?

One way to find out which interpreter is running is to type `import sys; print(sys.executable) in the console window that successfully imports numpy.

**Comment by AjayNorman** [comment]
Found the correct interpreter now with the above comment. Now how can I use the same interpreter while double clicking the .py file?

**Comment by mattip** [comment]
Hmm. General Windows stuff?
OK: Right click -> open with -> (find the interpreter) ->always use this program

**Comment by AjayNorman** [comment]
Problem solved. This is how its solved. I uninstalled Numpy, Pandas, Matplotlib from Anaconda prompt. NOTE: Anaconda prompt MUST be run with "Run as administrator option". Once uninstalled from anaconda prompt, reinstall pandas. Reinstalling pandas will install Numpy as well on its own. Then reinstall matplotlib. It worked. Thanks for all your inputs.
