### ISSUE TITLE
Numpy will not build with XL compiler on linux/RHEL7/ppc64le/power9 system

### ISSUE THREAD

**Issue by becker33** [numpy/numpy#16172]
When built with `--fcompiler=ibm` on linux, the build system complains that ibm is not a valid compiler for posix.

### Reproducing code example:

```
python setup.py build --fcompiler=ibm
```
or
```
python setup.py build --fcompiler=ibm --compiler=ibm
```

### Error message:

At import time
undefined reference to 'zungqr_'

**Comment by becker33** [comment]
It appears from looking in the code base that the IBM compiler is only defined for AIX systems. The output from the build lists `clang` as the compiler even when told to use IBM.

**Comment by tylerjereddy** [comment]
I'm having some success with a `CC=xlc python setup.py install` incantation after changing a few build flags. But it looks like I need to be able to link in a new static library to at least one of the NumPy object files that is built.

Just dumping the `-L/path/to/lib` and `-lnameoflib` in the `linker_so` object in `distutils` machinery doesn't seem to suffice.

There's a static library `libxl.a` that provides the `_fill` symbol NumPy complains about at import time, so I need that linked in somehow:

`numpy/core/_multiarray_umath.cpython-37m-powerpc64le-linux-gnu.so: undefined symbol: _fill`

**Comment by rgommers** [comment]
We switched build systems from `numpy.distutils` to Meson, so this issue is no longer relevant. Hence I'll close it - thanks all.
