### ISSUE TITLE
Deprecate @dec.slow

### ISSUE THREAD

**Issue by sethtroisi** [numpy/numpy#16184]
```bash
~/Projects/numpy$ grep -ri --exclude-dir='build' '@dec.*slow' .
doc/TESTS.rst.txt:  @dec.slow
doc/TESTS.rst.txt:      @dec.slow
numpy/testing/tests/test_decorators.py:        @dec.slow
numpy/testing/_private/decorators.py:      @dec.slow
```

I looked in scipy and `@dec.slow` is only used in one file and seems not to cause tests to end up being not run in `-m fast`.

I'm hoping that I can get approval to delete the mention in 
[doc/TESTS.rst.txt](https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt#labeling-tests)

and mark the decorator deprecated (or just delete it) from
[numpy/testing/tests/test_decorators.py](https://github.com/numpy/numpy/blob/master/numpy/testing/tests/test_decorators.py)

**Comment by charris** [comment]
The decorators are only kept around for folks using the old NumPy nose framework. Some distros have  patched nose to work with recent Python, but it looks like nose2 has replaced it in fedora. We may want to issue a FutureWarning when any of the framework is imported and then remove it. Or maybe not. It needs to be discussed on the list. Note the other nose files in `numpy/testing/_private`.

**Comment by rgommers** [comment]
> I'm hoping that I can get approval to delete the mention in
> [doc/TESTS.rst.txt](https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt#labeling-tests)

Yes let's remove it there, since those instructions should be using pytest now.

> and mark the decorator deprecated (or just delete it) from
> [numpy/testing/tests/test_decorators.py](https://github.com/numpy/numpy/blob/master/numpy/testing/tests/test_decorators.py)

Let's not deprecate it, that could be really annoying for people still using `nose` (no idea how many are left). I think we should leave them all, and then at some point in a couple of years separate everything at once from numpy, just like we did with financial functions.

**Comment by rossbar** [comment]
PR's to update `doc/TESTS.rst.txt` to de-emphasize `@dec.slow` would be a welcome improvement.
