### ISSUE TITLE
Possible Improvements to NEP 23 ?

### ISSUE THREAD

**Issue by anirudh2290** [numpy/numpy#16193]
The NEP 23 is a good read to understand Numpy's backward compatibility policy. 
Just listing a few possible improvements here.

- [ ] Resolution not listed, its not clear if it is accepted.
- [ ] Discussion missing. Two links that I found : https://github.com/numpy/numpy/issues/10156 , 
http://numpy-discussion.10968.n7.nabble.com/backwards-compatibility-and-deprecation-policy-NEP-td45941i20.html , there is probably more.
- [ ] References and Footnotes missing.
- [ ] doesn't mention the guideline for using FutureWarning.

**Comment by rgommers** [comment]
Thanks @anirudh2290 for the suggestions. Note that that NEP gives a reasonable impression of our approach to backwards compatibility, however it was never accepted. I plan to come back to it in the next couple of months - finishing that up is a deliverable of the CZI grant we got last October.

**Comment by h-vetinari** [comment]
This was likely closed by #18097, though it's still missing the acceptance.

**Comment by rgommers** [comment]
Thanks @h-vetinari, I forgot about this one. I'll close it through the next PR which changes the status to accepted and adds the mailing list links.
