### ISSUE TITLE
np.cov behaves strangely in ARM-based machine

### ISSUE THREAD

**Issue by Qiyu8** [numpy/numpy#16190]
### Reproducing code example:
test case `test_2d_without_missing` in `test_extras.py ` cannot run correctly in arm based machine. The simplyfied version of that case is like below.
```python
import numpy as np
from numpy.ma.extras import cov
x = np.arange(12).reshape(3, 4)
print(cov(x, rowvar=False))
print(np.cov(x, rowvar=False))
```
The result is:
[[16.0 16.0 16.0 16.0]
 [16.0 16.0 16.0 16.0]
 [16.0 16.0 16.0 16.0]
 [16.0 16.0 16.0 16.0]]
[[16. 16. 16. 16.]
 [16. 16. 16. nan]
 [16. 16. 16. 16.]
 [16. nan 16. 16.]]

It looks like if np.cov is excuted after cov, a strange array that containing a nan is produced, but if np.cov is excuted before cov, np.cov behaves normally. 

### Numpy/Python version information:

1.19.0.dev0+7e3fd81 3.7.0 (default, Mar 16 2020, 00:02:15)

**Comment by matthew-brett** [comment]
I guess you mean `np.ma.extras`?  What do you get for:

```python
import numpy as np
from numpy.ma.extras import cov

x = np.arange(12).reshape(3, 4)

print(np.cov(x, rowvar=False))
print(cov(x, rowvar=False))
print(np.cov(x, rowvar=False))
```

?

**Comment by Qiyu8** [comment]
@matthew-brett The result is:
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16.0 16.0 16.0 16.0]
 [16.0 16.0 16.0 16.0]
 [16.0 16.0 16.0 16.0]
 [16.0 16.0 16.0 16.0]]
[[16. 16. 16. 16.]
 [16. 16. 16. nan]
 [16. 16. 16. 16.]
 [16. nan 16. 16.]]

**Comment by matthew-brett** [comment]
What do you get if you print out `x` between each call to `cov` or `np.cov`?

**Comment by seberg** [comment]
I would be tempted to blame the BLAS package here, anything else just doesn't add up to me. I.e. the `np.dot` call doing something wrong. @Qiyu8 any chance you can swap out the BLAS, or use a reference version?

**Comment by Qiyu8** [comment]
> What do you get if you print out `x` between each call to `cov` or `np.cov`?

all of the x is identical same:
```
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
```

the strange thing is that if I print out x between each call, the `nan` result disappeared! everything get back to normal.

**Comment by Qiyu8** [comment]
> I would be tempted to blame the BLAS package here, anything else just doesn't add up to me. I.e. the `np.dot` call doing something wrong. @Qiyu8 any chance you can swap out the BLAS, or use a reference version?

@seberg I didn't use any BLAS package, just uses a reference version.

**Comment by seberg** [comment]
@Qiyu8 can you check taking the path:
```
np.core.multiarray._multiarray_umath.__file__
```
and running `ldd path` gives you? Or did you compile it with empty `NPY_BLAS_ORDER`?

**Comment by Qiyu8** [comment]
@seberg After running `ldd /usr/chunlin/numpy/numpy/core/_multiarray_umath.cpython-37m-aarch64-linux-gnu.so`, the result is:
        ```
linux-vdso.so.1 (0x0000ffff99535000)
        libopenblas.so.0 => /usr/local/lib/libopenblas.so.0 (0x0000ffff98db1000)
        libm.so.6 => /lib64/libm.so.6 (0x0000ffff98ce0000)
        libpython3.7m.so.1.0 => /lib64/libpython3.7m.so.1.0 (0x0000ffff989aa000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000ffff98975000)
        libc.so.6 => /lib64/libc.so.6 (0x0000ffff987ef000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff994f7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000ffff987ce000)
        libutil.so.1 => /lib64/libutil.so.1 (0x0000ffff987ad000)
```
secondly, I compiled numpy with the normal command `python3 setup.py develop`

**Comment by Qiyu8** [comment]
After some test, I know what went wrong, an older version of OpenBlas was installed long time ago by other linux user, the nan problem disappeared after uninstalling OpenBlas, so just as seberg noticed, It's BLAS package that should blame.

**Comment by seberg** [comment]
You may want to use opeblas for speed, but make sure its up to date...
