### ISSUE TITLE
Importing the numpy c-extensions failed

### ISSUE THREAD

**Issue by MinkaMay** [numpy/numpy#16194]
Hey all, I am having some issues installing numpy, with the following error message:

I'm not sure if this is the source of the issue, but on the below error message where it says 'Check that you expected to use Python3.7 from "/usr/local/bin/python3-32" ', whereas for me Python3.7 is from /Users/jli/anaconda3/lib/python3.7 (I found this using python -c "import sys; print('\n'.join(sys.path))")

But I am not sure how to change this path in order to resolve the issue?

Thank you very much for your help :)

--------------------

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): no suitable image found.Did find:
        /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so: mach-o, but wrong architecture
        /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/usr/local/bin/python3-32",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
        /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so: mach-o, but wrong architecture
        /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so: mach-o, but wrong architecture

**Comment by rossbar** [comment]
@MinkaMay please take a look at [this doc page](https://numpy.org/devdocs/user/troubleshooting-importerror.html) to see if the suggestions there are helpful to you.

**Comment by MinkaMay** [comment]
> @MinkaMay please take a look at [this doc page](https://numpy.org/devdocs/user/troubleshooting-importerror.html) to see if the suggestions there are helpful to you.

@rossbar Hi Ross, thank you for this... I did take a look but unfortunately I am unsure of how to solve the problem :(

My operating system is MacOS and I only have 1 version of Python installed.

**Comment by rossbar** [comment]
> I'm not sure if this is the source of the issue, but on the below error message where it says 'Check that you expected to use Python3.7 from "/usr/local/bin/python3-32" ', whereas for me Python3.7 is from /Users/jli/anaconda3/lib/python3.7 (I found this using python -c "import sys; print('\n'.join(sys.path))")

You mentioned that you only have one version of Python installed on your system, but from the above comment it seems like there are multiple. The error message indicates that it was running the executable at `/usr/local/bin/python3-32` whereas it looks like you were expecting the Anaconda Python to be picked up. This indicates that your `PATH` or `PYTHONPATH` are probably not set up the way you expect them to be. Perhaps these docs on [determining your Python executable](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-path/) and [configuring your conda install on macOS](https://docs.anaconda.com/anaconda/install/mac-os/) (particularly step 7) can help.

**Comment by Ethan777100** [comment]
i also face the same issue.

i want to run Python 3.8.3 in Virtual Environment

```
Exception has occurred: ImportError
Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "c:\xxx\.venv\Scripts\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
  File "...\**__init__.py**", line 4, in <module>
    import pandas
  File "...\**run.py**", line 3, in <module>
    from xxx import plotter, xxx
```


But i clearly installed numpy 1.18.2 inside my computer. Able to help me out too? I tried uninstall/reinstall alr...doesn't work.

**Comment by mattip** [comment]
@Ethan777100 at the end of the message you copy-pasted it says
>Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Please take a look at our new document on [troubleshooting](https://numpy.org/devdocs/user/troubleshooting-importerror.html). We should add to that: if you are in a virtualenv, you should be using `python -m pip` or even better `path/to/python -m pip` to prevent situations that the wrong version of `pip` is used.

**Comment by Ethan777100** [comment]
sorry, i dont know wat i dont know. i read that bef i posted my question. 

```
`import os
PYTHONPATH = os.environ['PYTHONPATH'].split(os.pathsep)
print("The PYTHONPATH is:", PYTHONPATH)
PATH = os.environ['PATH'].split(os.pathsep)
print("The PATH is:", PATH)`
```

i just now copy paste this into my console. nothing worked. Which are the sections inside this block of code that i need to subtuite as accordingly?

**Comment by rossbar** [comment]
I'm going to close this issue due to inactivity and the fact that multiple different issues were conflated here. If the issue(s) persist, please create new issues with the specific information about your individual system(s)
