### ISSUE TITLE
Cannot enforce zero correlation in samples

### ISSUE THREAD

**Issue by Nathan-Furnal** [numpy/numpy#16192]
### Reproducing code example:

```python

import numpy as np
np.random.seed(11)
n=100
mean = [0, 0]
cov = [[1, 0], [0, 1]]      # Should have zero covariance

x, y = np.random.multivariate_normal(mean=mean, cov=cov, size=n).T

np.corrcoef(x,y)
```
yields: 

```
array([[ 1., -0.02736689],
       [-0.02736689,  1.]])  
```

While I'd expect to see : 

```
array([[ 1., 0],
       [0,  1.]])  
```

or some irrelevant numbers like ``1e-16``. This can be reproduced for any seed.

This doesn't cause any problem in ``R`` for example : 

```R
library(MASS)
library(purrr)

# Means
m1 <- 5
m2 <- 10
# variances
s1 <- 5
s2 <- 1
# Correlations
cov <- 0

set.seed(11)

dat <- mvrnorm(20, mu = c(m1, m2),
                     Sigma = matrix(c(s1,cov,
                                      cov, s2),
                                    ncol = 2, byrow = TRUE),
                     empirical = TRUE)

dat %>% cor()
```
Where the correlation matrix behaves as I'd expect. 

### Numpy/Python version information:

1.18.3 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52)
[GCC 7.3.0]

**Comment by charris** [comment]
Too few samples, random errors of that size (bit bigger, actually) are expected.

**Comment by Nathan-Furnal** [comment]
@charris But ``mvrnorm`` allows to enforce the parameters on the sample rather than from the population, I can't do that in numpy

**Comment by eric-wieser** [comment]
What does r do if you pick something tiny like `n=10`?

**Comment by charris** [comment]
Why would you do that? It is no longer a random sample.

**Comment by Nathan-Furnal** [comment]
@eric-wieser It enforces this with the ``mvrnorm`` function and the ``EMPIRICAL`` argument, the [function is here](https://github.com/cran/MASS/blob/master/R/mvrnorm.R) 

Basically it rescales the inputs and use SVD to get the principal components

**Comment by WarrenWeckesser** [comment]
For reference: https://rdrr.io/cran/MASS/man/mvrnorm.html

Example:

```
> mu <- c(0, 0)
> Sigma <- diag(2)
> x <- mvrnorm(10, mu, Sigma, empirical=FALSE)
> cor(x)
           [,1]       [,2]
[1,] 1.00000000 0.08625169
[2,] 0.08625169 1.00000000
> x <- mvrnorm(10, mu, Sigma, empirical=TRUE)
> cor(x)
              [,1]          [,2]
[1,]  1.000000e+00 -9.009569e-17
[2,] -9.009569e-17  1.000000e+00
```

**Comment by eric-wieser** [comment]
I wonder if this is sufficiently niche to belong to scipy.stats instead.

**Comment by Nathan-Furnal** [comment]
@eric-wieser You make a good point, this probably belongs in scipy instead

**Comment by eric-wieser** [comment]
I'd ask it again, and link to this issue.

I recommend you phrase it in terms of transforming the samples to have _exactly_ the requested statistics, and adding an `empirical` argument to match R.

It seems like this would be a reasonable request for many distributions, not just mvr. Even a standard normal could have this behavior.

**Comment by Nathan-Furnal** [comment]
Thanks I'll do that

**Comment by rkern** [comment]
I don't think we'd _modify_ any existing functionality in either `numpy` or `scipy` to do this. It just doesn't fit into the existing frameworks well. I also don't think it's particularly generalizable to other distributions. Note that the R implementation is in a helper package for a textbook, not a standard library component.

I would recommend implementing this for your own purposes. Then you can use the GPLed `MASS` implementation as a reference.

**Comment by charris** [comment]
@eric-wieser It isn't a standard multivariate normal any more and is size dependent. SVD will certainly give orthogonal vectors, but from what distribution are they taken? Note that one could also use QR to othogonalize the vectors, they will span the same subspace.

**Comment by Nathan-Furnal** [comment]
Alright, I'm not sure if this is needed but here is my piece of code to reproduce the behavior anyway :

```python
def mvrnorm(n, mean, cov, empirical=False):
    X = np.random.multivariate_normal(mean=mean, cov=cov, size=n)
    if empirical:
        X = X - X.mean(axis=0)
        *_, vh = np.linalg.svd(X)
        X = np.matmul(X, vh)
        X = X/X.std(axis=0)
    return X
```

**Comment by Nathan-Furnal** [comment]
Alright, I tried to roll it myself:

```python
def mvrnorm(n, mean, cov, empirical=False):
    X = np.random.multivariate_normal(mean=mean, cov=cov, size=n)
    if empirical:
        X = X - X.mean(axis=0)
        *_, vh = np.linalg.svd(X)
        X = X@vh
        X = X/X.std(axis=0)
    return X
```

But it doesn't work everytime!! Seemingly at random I get relatively large correlations

While I never get the problem in R : 

```R
mat <- matrix(rnorm(200), nrow=100, ncol=2)
mat <- scale(mat, TRUE, FALSE)
mat <- mat %*% svd(mat, nu=0)$v
mat <- scale(mat, FALSE, TRUE)

print(cor(mat))
```

Can someone help me sort it out?

**Comment by rkern** [comment]
You want `vh.T`. Our `svd()` routine follows the convention where the Hermitian of the `V` matrix gets returned (which is why we name it `vh` in the docstring), whereas your `R` code is using the straight `V` matrix.

**Comment by Nathan-Furnal** [comment]
Thanks @rkern that was very useful and thanks everyone for the input, I'll go ahead and close the issue!
