### ISSUE TITLE
Build numpy for unsupported platform

### ISSUE THREAD

**Issue by tfedyanin** [numpy/numpy#16191]
Hello, I have hardware with exotic VLIW architecture and try to build numpy and I have the error from `numpy/core/include/numpy/npy_cpu.h`:
```
#error Unknown CPU, please report this to numpy maintainers with
```
I try to comment this line :-) and build numpy with next command:
```shell
BLAS=None LAPACK=None ATLAS=None pip -v install --global-option="-j 30" .
```
After an hour I get a message about successful build, but numpy doesn't work:

### Reproducing code example:

```shell
(env377) localhost ~/tim/airflow_bin # python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, May  7 2020, 20:15:10)
[GCC 5.5] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Illegal instruction
```
### Numpy/Python version information:
Python 3.7.7
```
>>> print(sys.version)
3.7.7 (tags/v3.7.7:d7c567b08f, May  7 2020, 20:15:10)
[GCC 5.5]
```
Numpy 1.18.2

I understand that the value of numpy in optimizations, but is it possible to build functional distribution without the support of any particular platform?

**Comment by seberg** [comment]
I am not a CPU specialist, but I think it may make sense to find out which instruction is failing... There area also sometimes issues around virtual machines. The build process tries to not use specialized instructions unless the CPU supports it, but something is incorrectly detected here apparently. Unfortunately, I think you will need someone who is a specialist for that hardware to help probably.

**Comment by rgommers** [comment]
No follow-up, so closing. In case there is more to do here and you've found out which instructions are the problem, we can always reopen. PRs for making the build work on new CPU families are also welcome.

Thanks both.
