### ISSUE TITLE
numpy.deprecate indentation question

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#16202]
This code has two functions marked as deprecated with `numpy.deprecate`:

```
import numpy as np


@np.deprecate(message="foo() is no longer supported.")
def foo():
    """This is foo.

    It doesn't do anything.
    """
    return


@np.deprecate(message="bar() is no longer supported.")
def bar():
    """
    This is bar.

    It does the same thing as foo().
    """
    return
```
The docstrings of `foo` and `bar` end up like this:

```
In [5]: print(foo.__doc__)                                                        
`foo` is deprecated!
foo() is no longer supported.

    This is foo.

    It doesn't do anything.
    

In [6]: print(bar.__doc__)                                                        
`bar` is deprecated!
bar() is no longer supported.

    This is bar.

    It does the same thing as foo().
```
Note that the indentation of the added deprecation text doesn't match the indentation of the original docstring.  Is this intentional?  It messes up the HTML documentation; see, for example, the online documentation for [`scipy.stats.itemfreq`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.itemfreq.html).  That gray bar in front of what was originally the first line of the docstring ("Return a 2-D array...") shouldn't be there.

A related issue was reported in https://github.com/numpy/numpy/issues/8058, which was closed by https://github.com/numpy/numpy/pull/8131.

**Comment by mattip** [comment]
I would say it is not intended. If we are going to touch this, the modified decorator should accept additional arguments and insert its message after the first line so that the docstring looks like
```
This is bar.

.. deprecated:: 1.19
  bar() is no longer supported.

It does the same thing as foo().
```

This might be tricky to dedent if the `message` is longer than 78 characters
