### ISSUE TITLE
busday_count with holiday not working

### ISSUE THREAD

**Issue by j-jm** [numpy/numpy#16206]
### Reproducing code example:
```
# create an array of days off that includes 2 schools calendars
def days_off(org1, org2): 
    sch_cal1 = cal[cal['ORGID'] == org1]
    sch_cal2 = cal[cal['ORGID'] == org2]
    days_off1 = sch_cal1['HOL'].values. tolist()
    days_off2 = sch_cal2['HOL'].values. tolist()
    days_off = np.array(list(set().union(days_off1, days_off2))) # merge unique cal days in 1 list
    print(org1, org2, days_off)
    return (days_off)

# calculate total days off (weekend+holidays) for any 2 schools
def corr_ol(row):
    c_ol = []
    d1 = row['OLB']
    d2 = row['OLE']
    org1 = row['sch1']
    org2 = row['sch2']
    hol = days_off(org1, org2)
    c_ol = np.busday_count(d1, d2, weekmask='1111100', holidays = hol)
    return(c_ol)

# use apply to process the whole column (Corr_Overlap)
ol['Corr_Overlap'] = ol.apply(corr_ol, axis = 1)
ol.to_csv(process_folder + r'\valid_overlaps.csv')
ol
```

```python
import numpy as np
<< your code here >>
```

### Error message:

```ValueError                                Traceback (most recent call last)
<ipython-input-8-9f0b0315d36d> in <module>
----> 1 ol['Corr_Overlap'] = ol.apply(corr_ol, axis = 1)
      2 ol.to_csv(process_folder + r'\valid_overlaps.csv')
      3 ol

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6911             kwds=kwds,
   6912         )
-> 6913         return op.get_result()
   6914 
   6915     def applymap(self, func):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\apply.py in get_result(self)
    184             return self.apply_raw()
    185 
--> 186         return self.apply_standard()
    187 
    188     def apply_empty_result(self):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\apply.py in apply_standard(self)
    290 
    291         # compute the result using the series generator
--> 292         self.apply_series_generator()
    293 
    294         # wrap results

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\apply.py in apply_series_generator(self)
    319             try:
    320                 for i, v in enumerate(series_gen):
--> 321                     results[i] = self.f(v)
    322                     keys.append(v.name)
    323             except Exception as e:

<ipython-input-7-563918756ab6> in corr_ol(row)
      6     org2 = row['sch2']
      7     hol = days_off(org1, org2)
----> 8     c_ol = np.busday_count(d1, d2, weekmask='1111100', holidays = hol)
      9 # , holidays = days_off(d1,d2)
     10     return(c_ol)

ValueError: ('Cannot safely convert provided holidays input into an array of dates', 'occurred at index 0')
```

**Comment by Mandeep0001** [comment]
Hi @j-jm , can you please provide a clear reproducing example of the above issue, i tried to reproduce it, but it didnt work. Like if you can tell the holidays format and kind off values you are passing.

I have tried below code and it worked fine :

import numpy as np
np.busday_count('2020-05-12', '2020-05-17',weekmask='Tue',holidays=['2014-01-01','2020-05-16'])

**Comment by j-jm** [comment]
Thanks Mandeep,  yes the function works fine.  What doesn't work is when I call it from another function which itself processes each row of my df.  So this line 'ol['Corr_Overlap'] = ol.apply(corr_ol, axis = 1)' crashes.  Take a look at corr_ol.  I checked the format of my dates and they are fine.

**Comment by seberg** [comment]
Its hard to say what to do or how to help you here. This seems like an issue of passing dataframes to NumPy functions, which typically works, but sometimes has subtle small problems.
If you give a full example that might help us. Also you want to ask at pandas rather... It is even poassible that pandas has already fixed the issue.
It is unlikely that it is an issue in NumPy at all, but it may be that pandas can solve it or has already solved it.

**Comment by j-jm** [comment]
Hi,
did some troubleshooting.  I am pretty sure the problem is here:
 'days_off = np.array(list(set().union(days_off1, days_off2)))'.
  There is a problem with the array which causes busday to crash.

**Comment by seberg** [comment]
@j-jm can you give some details on *what* went wrong in that command? Is it numpy related or just a small issue in your code?

**Comment by j-jm** [comment]
Definitely an issue with my code.  I included the error above.  There is something about the days_off array that busday_count doesn't like.
