### ISSUE TITLE
tests fail with gcc10 on i586

### ISSUE THREAD

**Issue by mcepl** [numpy/numpy#16212]
(originally filed as https://bugzilla.suse.com/show_bug.cgi?id=1170833)

When running the test suite while building the distribution packages for openSUSE/Factory (development channel of the distribution with the latest packages), ``TestArctan2SpecialValues`` fails:
```
[  374s] self = <numpy.core.tests.test_umath.TestArctan2SpecialValues object at 0xa99a3a18>
[  374s] 
[  374s]     def test_nan_any(self):
[  374s]         # atan2(nan, x) returns nan for any x, including inf
[  374s] >       assert_arctan2_isnan(np.nan, np.inf)
[  374s] 
[  374s] self       = <numpy.core.tests.test_umath.TestArctan2SpecialValues object at 0xa99a3a18>
[  374s] 
[  374s] ../../../BUILDROOT/python-numpy-1.18.2-3.4.i386/usr/lib/python3.8/site-packages/numpy/core/tests/test_umath.py:1017: 
[  374s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  374s] 
[  374s] x = nan, y = inf
[  374s] 
[  374s]     def assert_arctan2_isnan(x, y):
[  374s] >       assert_(np.isnan(ncu.arctan2(x, y)), "arctan(%s, %s) is %s, not nan" % (x, y, ncu.arctan2(x, y)))
[  374s] E       RuntimeWarning: invalid value encountered in arctan2
[  374s] 
[  374s] x          = nan
[  374s] y          = inf
```

### Numpy/Python version information:

NumPy 1.18.4
Python3 3.8.2
gcc gcc10-10.0.1+git175037-2.5
[Complete build log with all details](https://github.com/numpy/numpy/files/4615077/_log.txt)

Perhaps related to #4909, #2417 ?

**Comment by anirudh2290** [comment]
This is probably something that changed on gcc 10. I dont see the RuntimeWarning: invalid value encountered in arctan2 on earlier gcc versions. IEEE 754 standard certainly mentions setting invalid flag when nan is one of arguments and i couldnt find any exceptions for this particular use case. If this is in compliance with the standard, we probably need to change the test, to suppress this warning for now.

**Comment by marxin** [comment]
I agree that there's a change related to GCC 10.
Can you please create a code snippet that will present that? I can then discuss that in the GCC community.

**Comment by mcepl** [comment]
OK, correction … it is not just one test, but 72 of them. See the attached [build log](https://github.com/numpy/numpy/files/4622420/_log.txt).

**Comment by mcepl** [comment]
OK, so reorganization of test calling make the test suite pass:
```
export PYTHONDONTWRITEBYTECODE=1
export PATH=/home/abuild/rpmbuild/BUILDROOT/python-numpy-1.18.4-0.i386/usr/bin:/var/lib/build/ccache/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin
mkdir testing
pushd testing
export PYTHONPATH=:/usr/lib/python3.8/site-packages:/home/abuild/rpmbuild/BUILDROOT/python-numpy-1.18.4-0.i386/usr/lib/python3.8/site-packages
PYTHONDONTWRITEBYTECODE=1
py.test-3.8 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v -n auto --pyargs numpy /home/abuild/rpmbuild/BUILDROOT/python-numpy-1.18.4-0.i386/usr/lib/
```

**Comment by anirudh2290** [comment]
i am not quite sure i understand what exactly fixed the problem, but good to hear it fixed hte problem.

**Comment by mcepl** [comment]
Better settings of both ``$PATH`` and ``$PYTHONPATH``.
