### ISSUE TITLE
The PyArray_SearchSorted function has wrong signature in ``__init__.pxd``

### ISSUE THREAD

**Issue by charris** [numpy/numpy#16219]
See comment at https://github.com/numpy/numpy/pull/12284#discussion_r424014950.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by jbrockmendel** [comment]
just opened https://github.com/cython/cython/pull/3606 in cython

**Comment by mattip** [comment]
From the comment:
> Since 2012 it has been `PyArray_SearchSorted(ndarray, object,  NPY_SEARCHSIDE, object)`

The changeset was 313fe46046, which was made (before we started using PRs) after Cython built the `__init__.pxd` file in 2009, and the change was never reflected into the `__init__.pxd`.
