### ISSUE TITLE
set_array_base: ValueError: Cannot set the NumPy array 'base' dependency more than once

### ISSUE THREAD

**Issue by Xianqi-Zhang** [numpy/numpy#16211]
Hi
I use Cython and numpy in my code, and problems with set_array_base occured.
My code:
```python
import numpy as np
cimport numpy as cnp
from libc.stdlib cimport malloc, free
cnp.import_array()
cnp.import_ufunc()

cdef class _finalizer:

    cdef void *_data
    
    def __cinit__(self):
        self._data = NULL
        
    def __dealloc__(self):
        print('_finalizer.__dealloc__')
        if self._data:
            free(self._data)

cpdef make_matrix(int nrows, int ncols):

    cdef float *mat = <float*>malloc(nrows * ncols * sizeof(float))
    
    cdef float[:, ::1] mv = <float[:nrows, :ncols]>mat
    cdef cnp.ndarray arr = np.asarray(mv)
    
    cdef _finalizer f = _finalizer()
    f._data = <void*>mat
    cnp.set_array_base(arr, f)
    
    return arr
```

When i use this in python, like this:
```
import numpy_cleanup as nc
nc.make_matrix(100, 100)
ValueError: Cannot set the NumPy array 'base' dependency more than once
```
Do u have any idea? Thank you for your any reply!

**Comment by eric-wieser** [comment]
Please post code and not just screenshots of code.

I assume this is the function causing you trouble:

https://github.com/numpy/numpy/blob/872c6b7de255059a580de414d0030f86471193b1/numpy/__init__.pxd#L950-L952

**Comment by mattip** [comment]
You should not be calling both `arr = np.asarray(mv)` (which sets `arr.base`) and `set_array_base(arr, f)`. If `arr.base` is not None you cannot call `set_array_base`. What are you actually trying to accomplish with your code?

**Comment by Xianqi-Zhang** [comment]
> You should not be calling both `arr = np.asarray(mv)` (which sets `arr.base`) and `set_array_base(arr, f)`. If `arr.base` is not None you cannot call `set_array_base`. What are you actually trying to accomplish with your code?

Thank u for your reply.

Because C has no automatic memory management features, so I want to tie a object which has __dealloc__ method, so that it correct and automatic memory management.

arr = np.asarray(mv) is used to convert  to ndarray, because if directly cnp.set_array_base(mv, f), it will raise error:
 Cannot convert numpy_cleanup._memoryviewslice to numpy.ndarray

(This method is about the book Cython-A guide for python programmer chapter10.3 Wrapping C and C++ Arrays)

**Comment by Xianqi-Zhang** [comment]
> Please post code and not just screenshots of code.
> 
> I assume this is the function causing you trouble:
> 
> https://github.com/numpy/numpy/blob/872c6b7de255059a580de414d0030f86471193b1/numpy/__init__.pxd#L950-L952
> 
> It looks like this behavior is deliberate:
> 
> https://github.com/numpy/numpy/blob/84a4c4b03a43c915151193685588f80759f2ea44/numpy/core/src/multiarray/arrayobject.c#L173-L183

I' sorry and I update the issue, add the code.
Do any method in numpy , can convert memoryviews to ndarray and set my own base at the same time? So that to merge arr = np.asarray(mv), set_array_base.

**Comment by eric-wieser** [comment]
I think you're trying to solve the wrong problem - you should be trying to set the `.obj` attribute of the memoryview, before numpy retrieves it at all. Your `memoryview` object ought to be managing its own finalizer, meaning all numpy has to do is hold onto the memoryview.

This sounds like something you'd do better to discuss with cython developers - a quick google did not reveal anything relevant to me.

**Comment by Xianqi-Zhang** [comment]
> I think you're trying to solve the wrong problem - you should be trying to set the `.obj` attribute of the memoryview, before numpy retrieves it at all. Your `memoryview` object ought to be managing its own finalizer, meaning all numpy has to do is hold onto the memoryview.
> 
> This sounds like something you'd do better to discuss with cython developers - a quick google did not reveal anything relevant to me.

Thank you.
