### ISSUE TITLE
np.array behaves differently when ndim exceeds the limit

### ISSUE THREAD

**Issue by Qiyu8** [numpy/numpy#16222]
### Reproducing code example:
```python
import numpy as np
nested = 1.5
for i in range(np.MAXDIMS):
      nested = [nested]
# no error
np.array([nested])
#if dtype is specified, throws a ValueError exception
np.array([nested], dtype=np.float64)
```
Is this behavior intentional or wrong?
### Numpy/Python version information:
1.19.0.dev0+84a4c4b 3.6.8

**Comment by seberg** [comment]
You can do `dtype=object`, I think without object, we may want to give a deprecation warning here as well (i.e. similar to the ragged case), I think we have an issue open about that, but do not know exactly where. Not sure I am in a rush to do that for 1.19 though...

**Comment by seberg** [comment]
I remember moving the milestone for an issue about adding a warning to this yesterday. so I will cose this, thanks for the report.
