### ISSUE TITLE
unclear behavior of nd-arrays

### ISSUE THREAD

**Issue by biondiettore** [numpy/numpy#16229]
### Reproducing code example:

```python
import numpy as np
a = np.zeros((100,))
b = np.zeros((100,1))
c = a + b
c.shape
```
The shape of c is (100,100), which is unclear to me why it should become a matrix since we are adding two vectors. Is this behavior intentional or there is something unclear to me with broadcasting?

### Numpy/Python version information:
1.18.1 3.7.7 
[GCC 7.3.0]

**Comment by seberg** [comment]
Hi, this is one of the core feature of how NumPy operates. Please check: https://numpy.org/doc/stable/user/basics.broadcasting.html

**Comment by biondiettore** [comment]
I understand now. So a numpy array of shape (100,) is treated as (1,100) and not (100, 1). Not extremely intuitive since the shape attribute simply returns (100,). I guess it is a design choice, which could lead other users to unexpected behaviors. Thanks for the reply!

**Comment by seberg** [comment]
@biondiettore the important thing to remember is that NumPy is an N-dimensional array, not a two dimensional array. So `(1, 100)` and `(100,)` are very different. Although they behave the same in the broadcasting context.
