### ISSUE TITLE
Does numpy not support sort by comparator?

### ISSUE THREAD

**Issue by tynanseltzer** [numpy/numpy#16233]
Hi, I apologize if this is the wrong place, but I cannot find anywhere that numpy allows for sorting based on comparator. There is the argsort and reindex method, but once again, that requires that a numeric value can be applied to the objects to be sorted, rather than the looser requirements of a comparator. Is this something that would be wanted? Was this intentionally not supported?

**Comment by shoyer** [comment]
`np.sort` is fast because it loops in C, not Python, but that isn't possible with a custom comparator. If you want to do this, you should just use Python's built-in `sorted()` and convert back into a NumPy array.

**Comment by tynanseltzer** [comment]
So I guess my confusion is that C certainly supports custom comparators. Is it an issue in passing the comparator to C and ensuring that the comparator itself isn't horribly inefficient? Anyway, thanks!

**Comment by shoyer** [comment]
It is certainly possible to pass in C function pointers via Python, but it isn't very convenient.

In theory something like SciPy's `LowLevelCallable` could work in NumPy, but I don't know how much it would be used:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.LowLevelCallable.html
