### ISSUE TITLE
Importing the numpy c-extensions failed.

### ISSUE THREAD

**Issue by Rich133** [numpy/numpy#16235]
### Python Code:

height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

np_height = np.array(height)
np_weight = np.array(weight)

### Error message:

Traceback (most recent call last):
  File "C:\Users\rsjar\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\rsjar\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\rsjar\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\EclipseWorkspaces\csse120\DEP_Printout\src\DEP_Printout.py", line 12, in <module>
    import numpy as np
  File "C:\Users\rsjar\anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\rsjar\anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\rsjar\anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

### Numpy/Python version information:

Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]

Numpy 1.18.4

**Comment by seberg** [comment]
Can you check the new documentation: https://numpy.org/devdocs/user/troubleshooting-importerror.html it has a link concerning anaconda+eclipse that probably helps you. If not, please not it here, so we can add a solution for your setup in case other users run into it.

**Comment by Rich133** [comment]
Hi, Thanks for your quick response!

I followed this link and as far as I can tell I have my interpreter for eclipse set up correctly.

![image](https://user-images.githubusercontent.com/65328937/81984421-dca8f380-9688-11ea-9124-681ac2a7030d.png)

I have run 
`conda activate`
as well.

I have no idea if my path or Pythonpath is set up correctly. I suspect I might have made a mess of them as I have no idea what I am doing with this. When I tried to run:

```
import os
PYTHONPATH = os.environ['PYTHONPATH'].split(os.pathsep)
```

All i got was:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    PYTHONPATH = os.environ['PYTHONPATH'].split(os.pathsep)
  File "C:\Users\rsjar\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'PYTHONPATH'

![image](https://user-images.githubusercontent.com/65328937/81984621-2f82ab00-9689-11ea-82be-770ece53c172.png)

![image](https://user-images.githubusercontent.com/65328937/81984657-3c9f9a00-9689-11ea-8025-419f5cfd9f42.png)

Thanks,
Rich

**Comment by seberg** [comment]
Oh, you don't have a pythonpath then, we have to fix that, it must use ` os.environ.get('PYTHONPATH', 
"").split(os.pathsep)` not indexing... 

In any case, I do not know, and I cannot help you more, others may, but its not a NumPy specific issue as far as I know, so you may want to ask either eclipse or conda people.

**Comment by rossbar** [comment]
I agree with @seberg  that this is an environment setup issue, not anything NumPy specific. That being said, I'd recommend taking another look at the [anaconda pydev config docs](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/eclipse-pydev/) and pay extra close attention to steps 5-7. Note in 7b the bottom window of the pydev config GUI shows the "libraries found" --- after a proper configuration, you should see numpy on that list.

**Comment by Rich133** [comment]
Ok thanks guys. Tried everything I could think of but was not able to solve it. Reinstalled Anaconda and still did not work. Resorted to using standard python and now having no issues.
