### ISSUE TITLE
.ptp() can return negative numbers

### ISSUE THREAD

**Issue by endolith** [numpy/numpy#16234]
This is worked around in https://github.com/numpy/numpy/pull/14381 and mentioned in https://github.com/numpy/numpy/issues/3292#issuecomment-543626173 but still seems to behave like this.  I don't see why anyone would ever *want* it to return a negative number, so I think it should be considered a bug.

### Reproducing code example:

```python
import numpy as np
np.array([32767, -1], np.int16).ptp()
```

It returns `np.int16(-32768)`, but it should logically return `np.uint16(32768)` or `int(32768)`.

### Numpy/Python version information:

1.17.4 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

**Comment by WarrenWeckesser** [comment]
The issue reported in gh-3292 was that the name `ptp` is cryptic.  The suggestion to change the name to something more informative got several +1s, but I guess there was not enough agreement or interest among the developers at the time to actually change the name.  

The issue reported gh-14831 was the same one that you are reporting here: `ptp` can return negative values when it processes signed integer arrays.

My comment about [`peaktopeak`](https://github.com/WarrenWeckesser/ufunclab#ufunclabpeaktopeak) in gh-3292 was partly made to give another possible new name, but also to point out a new implementation that avoids the negative values by returning an unsigned integer when the input is signed integers.

The behavior of `ptp` has come up at least once in the weekly community/triage meetings, but it hasn't become a high enough priority for anyone to take action.  If there is more interest now in getting `peaktopeak`--or something like it--into numpy, I can start working on that.

**Comment by WarrenWeckesser** [comment]
> The behavior of ptp has come up at least once in the weekly community/triage meetings, but it hasn't become a high enough priority for anyone to take action. If there is more interest now in getting peaktopeak--or something like it--into numpy, I can start working on that.

Argh, I remembered it being discussed but not the conclusion.  Matti's comment when closing gh-3292 was that the function was more appropriate for scipy.   So I think this can go on the scipy to-do list, as a possible enhancement for `scipy.signal`.

**Comment by endolith** [comment]
> So I think this can go on the scipy to-do list, as a possible enhancement for scipy.signal.

Would `.ptp` be removed from numpy, then?

**Comment by WarrenWeckesser** [comment]
No, there is no plan to remove `ptp`.

At a minimum, I guess we should add a warning to the docstring about the behavior with signed integers, with a work-around and with an example in the "Examples" section.

**Comment by WarrenWeckesser** [comment]
FWIW, the masked array version at least gives the warning ` RuntimeWarning: overflow encountered in byte_scalars`:

```
In [27]: m = np.ma.MaskedArray([-100, 100, 0, 10], dtype=np.int8)                                       

In [28]: m.ptp()                                                                                        
/Users/warren/mc37np/lib/python3.7/site-packages/numpy-1.19.0.dev0+59e8fc6-py3.7-macosx-10.9-x86_64.egg/numpy/ma/core.py:5890: RuntimeWarning: overflow encountered in byte_scalars
  keepdims=keepdims)
Out[28]: -56
```

**Comment by WarrenWeckesser** [comment]
> ... the masked array version at least gives the warning...

Except that it doesn't warn when an `axis` is given:

```
In [3]: y
Out[3]: 
masked_array(
  data=[[  1, 127],
        [  0, 127],
        [ -1, 127],
        [ -2, 127]],
  mask=False,
  fill_value=999999,
  dtype=int8)

In [4]: y.ptp(axis=1)  # No warning
Out[4]: 
masked_array(data=[ 126,  127, -128, -127],
             mask=False,
       fill_value=999999,
            dtype=int8)

In [5]: y[2].ptp()  # This warns
/Users/warren/mc37np/lib/python3.7/site-packages/numpy-1.19.0.dev0+59e8fc6-py3.7-macosx-10.9-x86_64.egg/numpy/ma/core.py:5939: RuntimeWarning: overflow encountered in byte_scalars
  keepdims=keepdims)
Out[5]: -128
```

**Comment by WarrenWeckesser** [comment]
> At a minimum, I guess we should add a warning to the docstring

See https://github.com/numpy/numpy/pull/16240

**Comment by mattip** [comment]
Closing, since I think improving documentation is all we can do at this point. The issue around `int` wrap-around warnings in ufuncs is much bigger than this issue. Maybe someday we can get a new warn-on-overflow `int` dtype. Please reopen if there is more to do.

**Comment by rgommers** [comment]
> If there is more interest now in getting `peaktopeak`--or something like it--into numpy, I can start working on that.

I'd rather not see that, too trivial/niche for numpy at this point.
