### ISSUE TITLE
Importing the numpy c-extensions failed, connection with Microsoft Power BI

### ISSUE THREAD

**Issue by Mitcha0209** [numpy/numpy#16236]
I have a problem using a python script with Microsoft Power BI. Usually Python works fine by itself but if I want to run Python from Power BI it has problems loading numpy.
The versions I use:
Python: 3.7.6
numpy: 1.18.1
mkl-service: 2.3.0

Do you have an idea what could be wrong and why he could not finde the numpy packages?

I get the following error message:

DataSource.Error: ADO.NET: Þўτћόŉ ŝċгιρτ эřŕôґ.
C:\Users\name.lastname\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\name.lastname\Anaconda3\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\name.lastname\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Þўτћόŉ ŝċгιρτ эřŕôґ.
C:\Users\name.lastname\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\name.lastname\Anaconda3\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that...
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException

**Comment by seberg** [comment]
These type of issues are usually around environment activation, we have a new website:

https://numpy.org/devdocs/user/troubleshooting-importerror.html

can you see if the links there help you? (E.g. on anaconda environment activation). If your case is someone special, we would also like to add it to the site so other users can find the solution more easily.

**Comment by Mitcha0209** [comment]
I have tried it already with activating the anaconda environment but it wasn't working either. 

Then I uninstalled Anaconda and only installed Python. This is giving no error and I can run a Python-Script from Power BI.
This is more or less solving my problem. I just can't use the Anaconda-distribution.

**Comment by seberg** [comment]
That doesn't seem like it should be a problem... But in that case maybe some other PATH/PYTHONPATH issues? Maybe you should raise this at the Anaconda people, they may know what bad interaction is likely with Power BI.
