### ISSUE TITLE
Changes to SVD tutorial based on Daniele Procida's guidelines

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#16244]
[Linear algebra on n-dimensional arrays](https://numpy.org/devdocs/user/tutorial-svd.html) may be the NumPy documentation's first [Daniele Procida-style](https://documentation.divio.com/tutorials/) tutorial. It's detailed, engaging, and useful. 

As the first tutorial it will be a model for tutorials to come, so I'd like to offer suggestions. 

I've submitted PR #16245 to address a number of these points.

```
Before reading this tutorial, you should know a bit of Python. 
```
1. Tutorials shouldn't take too much for granted, but we can set a baseline. Rather than putting this on every tutorial, let's assume table stakes for users of a Python library is some knowledge of Python.

2. Psychologically, we should put objectives first and prerequisites after. Show them what they're getting before talking price.
<br>

```
>>> img = misc.face()
```
3. Should tutorials use examples from the IPython shell rather than the Python interpreter? We don't want to lend credibility to a bad choice.  On the other hand, maybe nobody takes these literally.
<br>

```
Note: If you prefer, you can use your own image
```
4. Procida's tutorial recommendations include  `What you ask the beginner to do must work` and `Tutorials need to be...built around specific, particular actions.` Both these suggest we not offer a roll-your-own option at this point in the tutorial -- but "Using your own image" is great idea for a "Next steps" section.
 <br>

```
Note: If you are executing the commands above in the IPython shell, 
it might be necessary to use the command plt.show() to show the image window.
```
5. For sections like these, perhaps we can use a dedicated `If you have trouble` rST admonition rather than `Note`.

6. `plt.show()` surprised me when I tried it --  it ran in the foreground and stole my cursor. I'd know what to do in bash but wasn't sure what to do in IPython. If the only option is ctrl-C, we can add a sentence: "You'll need to use ctrl-C to return to the IPython command line."
<br>

```
an array of 3 matrices, each having shape 768x1024.
```
7. He's asking why the shape isn't 1024x768:
![image](https://user-images.githubusercontent.com/6691888/81816971-097ad080-94fa-11ea-9175-6e87198f0f38.png)
<br>

```
This operation, dividing an array by a scalar, works because of NumPy's
broadcasting rules.
```
8. While this is true, it may be confusing to introduce broadcasting here. Linear algebra allows multiplication by a scalar and NumPy is doing the expected thing.  It seems strange to make a fuss about it. It might be better to wait for "Applying to all colors." 

9. We started with 0..255 values in the image, rescaled them to 0.0..1.0, and never scaled them back, but `plt.imshow` still works fine. Perhaps we can add a note (with the other notes at the bottom) explaining why we didn't need to rescale.
<br>

```
(Note that in real-world applications, it would be better to use, for example, the
img_as_float utility function from ``scikit-image``).
```
10. This is important guidance, but might better be moved to a section at the end. Procida says, `Maybe...there are different ways to access a certain API. It doesn’t matter: right now, your learner does not need to know about those in order to make progress.`

    Also, moving the section out of the main flow makes it easier to explain why using scikit-learn is a better idea.
<br>

```
Here, we will use the SVD (Singular Value Decomposition)
```
11. The linked-to [Wikipedia entry](https://en.wikipedia.org/wiki/Singular_value_decomposition) on SVD will dismay some readers:

> In linear algebra, the singular value decomposition (SVD) is a factorization of a real or complex matrix that generalizes the eigendecomposition of a square normal matrix to any m×n matrix via an extension of the polar decomposition.

A friendlier introduction we might link to: https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254?gi=2729cca75ba3
<br>

```
Note: ...users are encouraged to use the scipy module for real-world applications.
```
12. As with the scikit-learn advice, let's move it out of the main flow, and explain there
what makes SciPy a better choice.
<br>

```
To see if this makes sense in our image, we should use a colormap from matplotlib 
corresponding to the color we wish to see in out image (otherwise, matplotlib will 
default to a colormap that does not correspond to the real data). In our case, we are 
approximating the grayscale portion of the image, so we will use the colormap gray:
```
13. In line with Procida's recommendations, perhaps reword as "To see if this makes sense in our image, we will use the ``gray`` colormap from Matplotlib."
<br>

```
the linear algebra functions in NumPy expect to see an array of the form (N, M, M)
```
14. Maybe <a href="https://www.codecogs.com/eqnedit.php?latex=\small&space;(N,M_1,&space;M_2)" target="_blank"><img src="https://latex.codecogs.com/png.latex?\small&space;(N,M_1,&space;M_2)" title="\small (N,M_1, M_2)" /></a>?
<br>

```
Even though the image is not as sharp, using a small number of k singular values (compared to the original set of 768 values), we can recover many of the distinguishing features from this image.
```
15. We've promised compression -- the reader may be curious about measuring it. What makes zero-filling Sigma produce a smaller image file?
<br>

```
Of course, this is not the best method to approximate an image. However, there is,
in fact, a result in linear algebra that says that the approximation we built above is 
the best we can get
```
16. This wasn't completely clear; it looks like it *is* the best way.  Also I wasn't sure why this was "of course" not the best.  

Is this a legitimate paraphrase:
    

> Numerically, SVD compression is unbeatable: a result in linear algebra says that the approximation we built above is the best we can get in terms of the norm of the difference between the original and reduced matrices. But human eyes disagree;  lossy image compression techniques used in practice, like jpeg, are built around discarding data that the eye won't notice is missing.
<br>

```
 You can see this by looking at the shape above...using the ndim property of this array,
 we can see 
```
18. Should it be `we` or `you` in a tutorial, or is it fine to use both? (My own view is that switching around is natural and nobody notices.)
<br>

```
you should also have matplotlib and SciPy installed 
```
17. Something minor -- a uniform spelling for Matplotlib.  [Matplotlib's home page](https://matplotlib.org/) consistently uses uppercase, as in...

> A large number of third party packages extend and build on Matplotlib functionality

...except for the logo:
![image](https://user-images.githubusercontent.com/6691888/81815236-bef85480-94f7-11ea-951f-1210ca7e5780.png)

Are we down with upper?
<br>

**Comment by mattip** [comment]
Thanks for the comments.

> Should tutorials use examples from the IPython shell rather than the Python interpreter?

I don't think we should prefer one shell over another. As you state later on, there are quirks in the way each shell or IDE works with plotting. Perhaps we could link to a "getting started with python and plotting" tutorial. We should have a section on "reading this content" like there used to be in some programming books which describes the format of the code snippets, something like:
> `>>>` at the beginning of the line in the following snippet means "type this into your interpreter shell" and a line without that is the expected output. Clicking on the `>>>` in the upper right corner will reformat the snippet for convenient copy-pasting, although we recommend you type the commands in order to make sure you fully understand them.

> "You'll need to use ctrl-C to return to the IPython command line."

Maybe "You might need to close the window to continue the tutorial", since different shells handle this differently.

**Comment by matthew-brett** [comment]
But - I wonder whether we should standardize to the IPython shell.  None of us use the unmodified shell, I guess, other than for quick debugging in virtualenvs and the like.   So the `>>>` markup, though standard for raw Python, will likely be unfamiliar to most people getting started in scientific Python.

**Comment by bjnath** [comment]
>  ctrl-C 

Good point. We do need to keep the step concrete, because it's not necessarily clear what it takes to close the window. If there's a leading alternative way, we might say "close the display window by typing ctrl-C, twister-Ƹ, or your system's equivalent."  Users on rarer systems will be accustomed to translating mainstream instructions.

> We should have a section on "reading this content"

We can make this a standing last line of `Prerequisites`:
```
If this is your first tutorial, see "Tutorial notation" for help running the examples.
```
That section would explain `>>>` along the lines of Matti's suggestion, perhaps saying also how the convention arose and that nowadays there are better choices. I'm torn between helping users to whom `>>>` is news and experienced users who'll think,"You dragged me here for *this*"?

> 'Getting started with plotting'

We can change the admonition about viewing in IPython to
```
.. note::
  If you have trouble, see "Python plotting from your environment." 
```
We can't YMMV the zillion shells and IDEs -- a tutorial must be "guaranteed to work," in Procida's words -- but populating and maintaining such a page will be taxing and out of our scope. If we can't find an outside page, maybe we can work with Matplotlib to get one up on their pages that every site in the scientific Python community can link to.

**Comment by bjnath** [comment]
I've just realized there's a much approach the plotting and prompt issues. 

It's legitimate for a tutorial to dictate the tools you need to complete the exercise.  The tutorial doesn't claim to serve all races and creeds simultaneously: it walks the reader through using a tool, holding everything else constant.

So it's not "if you're using IPython" but "Start the IPython shell."

**Comment by rgommers** [comment]
Still, `>>>` is standard throughout all packages and examples, and you can use it as the IPython prompt as well. There's no point changing this, that will just lead to a ton of churn with little upside. Plus numbered in/out will be quite annoying if one adds or removes something - then all numbering needs updating.

**Comment by rgommers** [comment]
Nice detailed feedback @bjnath!

**Comment by eric-wieser** [comment]
> Plus numbered in/out will be quite annoying if one adds or removes something - then all numbering needs updating.

If we use `.. ipython` for the code blocks like the in-the-works `np.ma` tutorial does, then this will be a non-issue.

**Comment by matthew-brett** [comment]
Personally, I think the churn is worth it - it means that the tutorial will look like what we'd expect the user to use and see.

**Comment by rgommers** [comment]
> Personally, I think the churn is worth it - it means that the tutorial will look like what we'd expect the user to use and see.

I didn't mean this one tutorial. We have `>>>` in every single docstring and other doc item. What would you convert, all tutorials and longer-form docs, but not the docstring examples?

**Comment by matthew-brett** [comment]
Yes - that's my instinct - that we'd convert the tutorials, and then say something like: "You will see `>>>` as a prompt in the docstring examples.  This is a standard way of writing a Python example.  To use in the IPython shell, you can copy paste the example directly, including the `>>>` prompts".  But I may well be underestimating the extent to which docstring examples and tutorials are interleaved.

**Comment by rgommers** [comment]
> But I may well be underestimating the extent to which docstring examples and tutorials are interleaved.

They're not interleaved in where they live in the code, there's only linking back and forth. This could work indeed. IIRC the "hide" button for code blocks is broken/missing for `.. ipython::`, so it's more difficult to copy examples into a `.py` file or notebook. If that's still true, maybe worth fixing. Then it's probably an improvement - I still regularly encounter people using the plain Python interpreter, which is almost never what they actually need.

**Comment by matthew-brett** [comment]
In that case I would have thought standardizing to the IPython shell would be a big win, possibly keeping in mind they may be using Jupyter.

**Comment by melissawm** [comment]
Thanks for the detailed feedback, @bjnath . I think many points raised are great, I'll just comment on a few:

- For the SVD definition, I avoided linking to a private blog or particular web page because we can't be sure it will be online forever, and we also can't be sure it won't be modified in the future, which could bring maintainability issues. Wikipedia is a much safer bet in that regard. I'm not sure what would be ideal here.
- Point 14 (N, M, M) comes directly from the NumPy documentation, so I left it unchanged so the reader could do an easier cognitive link to that material.
- Point 16: SVD is a way to approximate matrices, but not semantic image information. For example there is no distinction between edges, shadows, colors, everything gets compressed in weird unpredictable ways in the general case. This means that we'll have less information to store (instead of, say, NxN+MxM+max(M,N) values we could store only (NxK)+(KxM)+(K) values, which is much smaller for small K). So, mathematically it is the best way but in practice it's complicated :)
> Numerically, SVD compression is unbeatable: a result in linear algebra says that the approximation we built above is the best we can get in terms of the norm of the difference between the original and reduced matrices. But human eyes disagree; lossy image compression techniques used in practice, like jpeg, are built around discarding data that the eye won't notice is missing.
I think this does a great job of explaining it, yes!

All the other points are ok with me!

**Comment by bjnath** [comment]
Thanks for your comments @melissawm. There are some points still unaddressed. Some need wider discussion (starred items) and some I'm unable to answer without your help.

<b>3,6* </b>-- Should tutorials restrict users to one platform (eg IPython)? This will (perhaps) resolve 3 (what kind of prompts to print) and 6 (we'll give specific instructions based on the specific platform). 

<b>5*</b> -- Dedicated reST admonition for troubleshooting sted 'Note'. Not sure what admonitions are available.

<b>7</b> -- Brief explanation of why the apparently 1024x768 image is a 768x1024 matrix.

<b>9</b> -- Brief explanation of why plt.imshow still works even though matrix is 0.0..1.0 sted 0..255.

<b>10,12</b> -- Brief explanation of why skimage and scipy are better approaches than what the tutorial did

<b>18*</b> -- "We" or "you" or both -- I'll assume "both" is noncontroversial -- whichever pronoun makes most sense in context.

<b>17</b> -- I'll assume following the home page spellings for packages is noncontroversial.

I updated my PR for the tutorial -- awaits comments, @rossbar and @melissawm. The PR has moved; it's now #16386 (was #16245).

**Comment by melissawm** [comment]
Hi @bjnath , I'll give you my two cents but if you have different views feel free :)

3, 6: I would go for IPython in this case. I think this is what most people use nowadays anyway. But this should be made explicit in the text.
5: I think this is your choice. I like "if you have trouble" for some comments but others are truly Notes, so it really depends. 
17: Makes sense
18: You can decide on that based on your experience: I'm not a native english speaker so you have way more qualification than me to decide on those things :)

10, 12: Basically, NumPy is not guaranteed to use an optimized version of BLAS/LAPACK for its linear algebra libraries. Also, NumPy is not focused on image processing or manipulation, so using a specialized package like scikit-image is always best. We didn't use it here because 1) our focus is on NumPy operations and 2) we wanted to keep dependencies to a minimum, since this documentation is built with NumPy, so any dependencies to the tutorials end up as dependencies to NumPy.

**Comment by melissawm** [comment]
I believe we have addressed most of this already - please feel free to reopen if you feel otherwise.
