### ISSUE TITLE
Built from source ignores runtime_library_dirs and requires LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by MerlinDumeur** [numpy/numpy#16250]
I built numpy from source against BLIS, which went fine.
However at runtime, numpy is not able to find the library, even though I specified the same path for build time and run time in the `site.cfg` file.

After building, when I try to import numpy I get the following error:

```
ImportError: libblis.so.3: cannot open shared object file: No such file or directory
```

However if I use `LD_LIBRARY_PATH=/usr/local/lib python`, then the import works fine.

When I do `np.show_config`, I get the following output:

```
blis_info:
    libraries = ['blis', 'blis']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include']
    language = c
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['blis', 'blis']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include']
    language = c
    runtime_library_dirs = ['/usr/local/lib']
```

However, I should not need to specify `LD_LIBRARY_PATH` for this to work.
As described in the `site.cfg.examples` file:

> runtime_library_dirs/rpath:
>       List of directories that contains the libraries that should be 
>       used at runtime, thereby disregarding the LD_LIBRARY_PATH variable.

This is not the behaviour that I observe though, so something must be wrong here.
Could you help me figure out where that could be coming from ? I don't know where to start.

**Comment by rgommers** [comment]
Sorry this didn't get any replies @MerlinDumeur. It looks like something was indeed wrong there. In the meantime we've switched build systems, so this all works differently now. Hence I'll close the issue.
