### ISSUE TITLE
rounding errors in np.arange

### ISSUE THREAD

**Issue by danielhrisca** [numpy/numpy#16251]
When settings the dtype to 32 bit float, there are some rounding errors during the execution of np.arange

### Reproducing code example:

```python
import numpy as np

print(np.arange(19992504.83851, 19992505.31851, 0.0001))
print(np.arange(19992504.83851, 19992505.31851, 0.0001, dtype='f4'))
```
outputs
```
array([19992504.83851   , 19992504.83861   , 19992504.83871   , ...,
       19992505.31831812, 19992505.31841812, 19992505.31851812])
array([19992504., 19992504., 19992504., ..., 19992504., 19992504.,
       19992504.], dtype=float32)
```

### Numpy/Python version information:

Tested with numpy 1.18.4 and 1.16.0

**Comment by charris** [comment]
Note that float32 only has about 7 digits of accuracy, the result is unsurprising.

**Comment by rk-mlu** [comment]
This is not an issue with np.arange but with the data type. 

np.float32 has a precision of only 6 decimals. Hence numbers like 19992504.83851, 19992505.31851 cannot be resolved by this data type. Use np.float64 instead, which has a resolution of about 16 decimals.

**Comment by eric-wieser** [comment]
The above comments explain why you see this with float32. There _is_ an issue in arange, but that's already covered by #16159, which is just a more extreme case of losing precision.

**Comment by danielhrisca** [comment]
I appreciate the explanation, I though the limitation was only on the decimals (1e-6) and could not figure out why the code was "not working"

**Comment by shaurysrivastav27** [comment]
You can try using np.float64 instead of np.float32 due to the 6 decimal places limitations.
