### ISSUE TITLE
Importing numpy causes ctypes.WinDLL to fail with cryptic message on Windows

### ISSUE THREAD

**Issue by Ennsye** [numpy/numpy#16255]
If numpy has been imported, ctypes.WinDLL(libpath) fails for any library. The import order appears to be irrelevant. Importing numpy after the WinDLL call causes no problems. The bug is not present for all Numpy/Python version combinations.

### Reproducing code example:
```python
import numpy as np
import ctypes
lib = ctypes.WinDLL("libtest")
```
```
Error message:
Traceback (most recent call last):
  File "test2.py", line 3, in <module>
    lib = ctypes.WinDLL("libtest")
  File "C:\Users\14167\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
Numpy/Python version information on a system where the bug exists:
1.18.1 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

And on one where the bug is absent:
1.16.5 3.7.4 (default, Aug 9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

Both Windows 10 systems are version 10.0.18362.

**Comment by eric-wieser** [comment]
Are both python installations anaconda?

**Comment by Ennsye** [comment]
> Are both python installations anaconda?

Yes. v4.8.3 on the system with the bug, v4.7.12 on the one without it.

**Comment by eric-wieser** [comment]
I expect it will work fine if you use an absolute path

**Comment by Ennsye** [comment]
It does. So, relative path works before importing numpy, but absolute path is needed after.

**Comment by eric-wieser** [comment]
This is due to something calling `SetDefaultDllDirectories`, which switches windows to using a more secure dll-loading mode.

**Comment by zooba** [comment]
Some versions of Anaconda have patched Python itself to make this call, I don't know exactly which ones.

Python 3.8 has a few alternative ways to deal with it, but if you can use an absolute path, that's going to be best.

**Comment by rossbar** [comment]
Closing as this seems resolved - please re-open for further discussion as necessary!
