### ISSUE TITLE
Numpy choice without replace vs shuffle

### ISSUE THREAD

**Issue by bgmoshe** [numpy/numpy#16268]
In some code base I was working on,  the user wants to draw X patients out of a list L, without replacemnt.
In order to make it simple, the programmer iterated over np.random.permutation(L).
BUT, sometimes the X patients are very small group (lets say 100 out of 100k), so I replaced it with np.random.choice with replace=False.
I noticed that it was slower. Even if size=10 and the array was huge.
### Reproducing code example:
Snippets out of jupyter notebook:
![image](https://user-images.githubusercontent.com/33910305/82135138-beb5cd00-9807-11ea-9913-6566f3f762c8.png)
![image](https://user-images.githubusercontent.com/33910305/82135177-31bf4380-9808-11ea-98c6-e5d40a6089e3.png)

**Comment by seberg** [comment]
We are not planning on changing the implementation of choice (its not fast). But please do use the new API, which *is* fast:
```
rng = np.random.default_rng()
%timeit rng.choice(x, size=10, replace=False)
```
Maybe the docs could mention this huge performance difference more clearly, although the new API is generally faster...

**Comment by bgmoshe** [comment]
@seberg Cool, I guess I never saw it :).
Now I see this though:
![image](https://user-images.githubusercontent.com/33910305/82143510-29d5c280-984d-11ea-843e-2aa5019a8d93.png)

So is there a reason to use shuffle at all? It seems like it is not comparable to choice on entire array w/o replacement

**Comment by bgmoshe** [comment]
@seberg BTW, why the weird name default_rng was chosen?
It is a confusing name (can also be misleading, when I saw it first I thought it was for range only [since rng is used many times as abbriviation to range])

**Comment by seberg** [comment]
RNG is Random Number Generator. I think we don't typically drop vowels in NumPy, but I can see it being used for range elsewhere.
Not sure about shuffle vs. choice speed, although it seems not like a huge difference. Could be that the fast path of shuffle could be made slightly faster.

**Comment by rossbar** [comment]
> So is there a reason to use shuffle at all? It seems like it is not comparable to choice on entire array w/o replacement

@bgmoshe note that the differences in the `timeit` results between shuffle and choice provided above are not significant (take a closer look at the std. dev.). Also, it very likely depends on the size of x. On my system:

```python
>>> rg = np.random.default_rng()
>>> x = rg.random(int(1e6))
>>> %timeit rg.choice(x, size=len(x), replace=False)
20.5 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
>>> %timeit rg.shuffle(x)
13.6 ms ± 459 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by bgmoshe** [comment]
@rossbar You got a point about stdev.
Interesting.I tired what you wrote and shuffle is fater now, but still in stdev.
 Just interesting to know when I should use shuffle instead.
Because, in general, you would want shuffle to have the same speed as choice on the whole array, o.w you would slice the shuffle when it is not effiecient.

**Comment by rossbar** [comment]
Generally I would not expect the performance to differ significantly between the two except perhaps for small arrays, where tasks like creating new arrays can be a significant chunk of the total runtime. A quick [perfplot](https://github.com/nschloe/perfplot/) bears this out:

![perfplot](https://user-images.githubusercontent.com/1268991/82157457-6649f400-9836-11ea-8aee-05e119587f96.png)

If it were me, all other things being equal (or at least not significantly different), I would choose which function to use based on code-clarity: `rg.shuffle` is easier to quickly understand than `rg.choice(a, len(a), replace=False)`.

Hopefully the discussion sufficiently addresses the initial issue - if not, please feel free to re-open!
