### ISSUE TITLE
Proposal: Adopt Google's documentation style guide

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#16262]
I'd suggest we put the [Google developer documentation style guide](https://developers.google.com/style) on our bookshelf next to [Procida](https://documentation.divio.com).

Style guides preemptively answer questions like "How should we capitalize titles?" (#16261), but the value of this particular guide goes further; it gives useful and perhaps not always obvious writing advice, including but not limited to:

> Some things to avoid where possible
> - Using phrases like simply, It's that simple, It's easy, or quickly in a procedure.
> - Placeholder phrases like please note and at this time.
> - Starting all sentences with the same phrase (such as You can or To do).

It's biggish, but it's browsable, and eventually most of us will have read some of it, some of us will have read most of it...etc. It disclaims absolute authority, and we wouldn't give it that authority anyway. It's a good way to pick up some neat writing guidance specifically for documentation, and to have a benchmark when classic recurring questions come up.

**Comment by rgommers** [comment]
Thanks for the suggestion @bjnath. Consistent style would be quite useful. I'm not familiar with the Google style guide (or other style guides for that matter), it looks good though from a quick browse.

@mkg33 maybe you have an opinion here? Is this largely consistent with the SciPy style choices you made?

**Comment by mkg33** [comment]
@rgommers I read the most important parts of the Google style guide and it's 100% consistent with the changes I'd proposed (especially when it comes to the consistent US spelling and abbreviations plus punctuation). I think we should vote on adopting the conventions listed in the guide. They're pretty universal and offer a concrete point of reference for the contributors.

**Comment by rgommers** [comment]
We discussed this on the docs meeting, everyone was positive - let's do this! Notes from the meeting:

- Uniform documentation style guide (Google):
    - Here's the guide: https://developers.google.com/style
    - Maja says this would have really helped her in last years' GSoD project for SciPy.
    - Ross notes that we should make sure to inform people that this does not refer to the docstrings
    - This can be included in the reviewer's guide for documentation issues
    - We should make sure to not be too picky in order to not alienate possible contributor's because English is not their first language
    - Overall feeling: everyone is positive.

**Comment by rgommers** [comment]
@bjnath I think we should also add the reference to the Google style guide to https://numpy.org/devdocs/docs/howto_document.html#overview, that will help contributors get this right. Would you mind doing that?
