### ISSUE TITLE
Make coremath lib known to distutils, so other extensions can use it (Trac #1028)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1626]
_Original ticket http://projects.scipy.org/numpy/ticket/1028 on 2009-02-26 by @cournape, assigned to @cournape._

COre math routines are now in separate lib, but extensions outside core cannot use it automatically.

**Comment by mattip** [comment]
I think this is about the separation of umath and multiarray. Since they are now combined,I will close this. Please reopen with a better description if I misunderstood.
