### ISSUE TITLE
Where are the 1.19 docs?

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#16279]
I'm planning a PR that reorganizes https://numpy.org/doc so all doc links appear together, in the same big print -- rather than having the newest version off to the side in small print.

https://numpy.org/devdocs/ is now at 1.20, so I'd include a 1.19 link in the column of doc releases. But there's no https://numpy.org/doc/1.19 the way there is for 1.18. 

Where can I link to for the 1.19 docs?

**Comment by charris** [comment]
They aren't ready yet.

**Comment by rossbar** [comment]
I think @charris  is in the process of preparing the 1.19 release as we speak! The docs are uploaded to the [numpy/doc](https://github.com/numpy/doc) repo, following the instructions [here](https://github.com/numpy/numpy/blob/master/doc/HOWTO_RELEASE.rst.txt#build-and-archive-documentation).
