### ISSUE TITLE
wheel build fails due to pep517_build_failure

### ISSUE THREAD

**Issue by n8v8R** [numpy/numpy#16271]
**Environment**

* pip version: 20.1
* Python version: 3.7.7
* OS: OpenWrt 19.07.2 (kernel 4.14.180)

* setuptools version: 46.4.0
* wheel version: 0.34.2
* Cython version: 0.29.17
* gcc version 7.4.0
* CPU type: ARM Cortex-A9  (arch armv7l | Little Endian)

**Description**
wheel build failing

**Expected behavior**
wheel build succeeding

**How to Reproduce**
`pip -vvv install -U numpy` aborts with

**Output**
>  Building wheel for numpy (PEP 517) ... error   
>  ERROR: Failed building wheel for numpy   
>Failed to build numpy   
>ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  **File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 378, in run
    ", ".join(r.name for r in pep517_build_failures)))**
pip._internal.exceptions.InstallationError: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
Removed build tracker: '/tmp/pip-req-tracker-mejic7_9'
___
According to https://github.com/pypa/pip/blob/master/src/pip/_internal/commands/install.py#L363 it would seem correlated to

`r.name for r in pep517_build_failures`

**Comment by rgommers** [comment]
@n8v8R can you show us the full output please? You're just starting from where the build has already failed and showing us the `pip` handling of that.

**Comment by n8v8R** [comment]
sure, here it is [pip output.txt](https://github.com/numpy/numpy/files/4640217/pip.output.txt)

**Comment by mattip** [comment]
The actual error seems to be
> gcc: error: /home/beast/beast/workspace/turris-os-packages-lions-omnia/build/include/hardened-ld-pie.specs: No such file or directory

Do other projects build on this platform? Perhaps related to gh-16013, where they got NumPy to build on openwrt but also faced compiler misconfiguration issues.

**Comment by n8v8R** [comment]
> Do other projects build on this platform?

I do not use the device (router) to compile because of its hardware specifications are just not suitable.

The issue is rather a causality tail from wanting to utilise https://pypi.org/project/flent/

* flent functionally depends on matplotlib
* matplotlib functionally depends on numpy
____
**Not sure**, the issue might be caused by the OpenWrt compiling toolchain https://openwrt.org/docs/guide-developer/build-system/use-buildsystem stating:

>Do everything as normal user, don't use root user or sudo!

**Comment by n8v8R** [comment]
gave it a go with particular PEP517 option -> `pip -vvv install --use-pep517 -U numpy` but the outcome is the same. [pip output.txt](https://github.com/numpy/numpy/files/4640329/pip.output.txt)


There is something in the output:

>/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
  error: Command "gcc [...]" failed with exit status 1

makes me wondering why *distutils* are being invoked at all, thought it would obsolete?

**Comment by mattip** [comment]
The line
> gcc: error: /home/beast/beast/workspace/turris-os-packages-lions-omnia/build/include/hardened-ld-pie.specs: No such file or directory

is still the error failing your build. You need to fix that. 

According to [this thread](https://github.com/openwrt/packages/issues/6226), adding `-fPIC` to your `LDFLAGS` may help, but that was a simple 5 minute search for that error and openwrt, YMMV.

We use distutils as a backend build system with specializations for the scientific python stack, it is far from obsolete.

**Comment by n8v8R** [comment]
Thank you for the feedback and the pointer. I am not much into compiling and having to look into compiler flags and figuring out where/how to deploy is just too cumbersome. Instead will forego the installation of *numpy*.
