### ISSUE TITLE
DOC: Incorrect listing of `order` parameter in tobytes

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#16282]
The docstring for `tobytes` ([link to source](https://github.com/numpy/numpy/blob/e66453568b685dee47d6e6e634b3a47edffcaeed/numpy/core/_add_newdocs.py#L3935-L3969)) lists the options for the order parameter as 'C', 'F', and None but does not include 'A' or 'K' (as in e.g. the copy docstring). 'Any' is also mentioned as a (seemingly) valid input for the `order` argument in the first part of the docstring.

### Numpy/Python version information:

1.19.0.dev0+35d5c2f 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0]

**Comment by abhilash42** [comment]
Hi, I am interested to work on this.

**Comment by rossbar** [comment]
Please feel free to do so!

**Comment by abhilash42** [comment]
Thanks! Had a doubt. There is no 'Any' valid input for order argument, actually it meant was if no order is given: choose C as default order, unless F_CONTIGUOUS flag is set. When I try, `x.tobytes('Any')`, get an error of `Please pass in 'C', 'F', 'A', or 'K' instead`. I think the statement needs clarification, right?

**Comment by abhilash42** [comment]
Got clarity: I think 'Any' is nothing but 'A' order.

**Comment by rossbar** [comment]
> When I try, x.tobytes('Any'), get an error of Please pass in 'C', 'F', 'A', or 'K' instead

Correct - this is the crux of what needs clarification
