### ISSUE TITLE
ARM-only test failure on 1.19.0 rc1

### ISSUE THREAD

**Issue by limburgher** [numpy/numpy#16302]
Build succeeds on Fedora Rawhide but fails on ARM due to test issue.

### Reproducing code example:

N/A

### Error message:

See attached log

### Numpy/Python version information:

Numpy 1.19.0 rc1, python 3.8.3

**Comment by limburgher** [comment]
[build.log](https://github.com/numpy/numpy/files/4651491/build.log)

**Comment by seberg** [comment]
@limburgher do you know if the test is simply incorrect here and the CPU supports NEON-VFPv4/ASIMD but the test thinks it should not?

This test runs for:
```
is_arm = re.match("^(arm|aarch64)", machine, re.IGNORECASE)
@pytest.mark.skipif(not is_linux or not is_arm, reason="Only for Linux and ARM")
```
I am thinking we may change what to expect based on the actual CPU?

**Comment by limburgher** [comment]
That's possible, the cpu in question here is armv7hl, and the aarch64 build succeeded:

https://koji.fedoraproject.org/koji/taskinfo?taskID=44694407

**Comment by seberg** [comment]
@seiko2plus wrote these tests. Sayed, maybe you know immediately how/if it needs adjustment?

**Comment by seiko2plus** [comment]
@seberg, According to the attached log, NumPy detects `ASIMD` while `/proc/cpuinfo` missing this feature. @limburgher, please could you verify the CPU Arch? Is that 32-bit kernel running on Arm8(AArch32 states)?

**Comment by sharkcz** [comment]
The Fedora armv7 builders are armv7 virtual machines (on KVM) running on aarch64 hw. The distro armv7 ABI is defined with `-march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard ` (https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/master/f/buildflags.md)

**Comment by hrw** [comment]
The thing is that most of armv7 distributions do builds without NEON enabled because there were some cpus which lacked it.

**Comment by seberg** [comment]
Is there some trivial way to adjust the test to capture that?

**Comment by nullr0ute** [comment]
@seberg you shouldn't really be doing runtime detection of features for compile time functionality. Maybe if a set of CFLAGs is passed in trust what the flags are specifiying and turn off run time detection.

**Comment by seiko2plus** [comment]
@limburgher, please could you try this patch #16304?

@sharkcz,
> The Fedora armv7 builders are armv7 virtual machines (on KVM) running on aarch64 hw

thank you!.

@hrw,
> The thing is that most of armv7 distributions do builds without NEON enabled because there were some cpus which lacked it.

The current NumPy CPU detection code is mainly designed to pave the way for #13516, and by default, the baseline features for Arm7 don't contain any SIMD features only through dispatched features.
 
@nullr0ute,

> you shouldn't really be doing runtime detection of features for compile time functionality. 

On Linux/Arm, we check the ELF auxiliary vector, and on other platforms we failback to the compiler definitions of the baseline features that in case of #13516 been merged, hopefully soon.

**Comment by Qiyu8** [comment]
@seiko2plus  should we using `/proc/cpuinfo` to detect CPU feature in order to enhance the robustness?

**Comment by vrakesh** [comment]
#16321 is related to this

**Comment by seiko2plus** [comment]
@Qiyu8, detect feature through auxiliary vector is more robust and it works fine for almost all kernels but maybe parsing `/proc/cpuinfo` could be the last choice when parsing `auxv` fails.

@vrakesh,
> #16321 is related to this

No, the issue here is 32-bit kernel (armhf) that work on ARMv8 doesn't report if `ASIMD` (a32 instructions) is available or not, so to work around it we assume that ASIMD is supported if we detect an ARM8 processor through checking the `hwcap2` features, this issue should be resolved by #16304

**Comment by charris** [comment]
Can anyone report back on trying @seiko2plus patch #16304?

**Comment by charris** [comment]
If not, I'll put it in 1.19.0rc2 for testing.
