### ISSUE TITLE
Linking numpy 1.18.x and MKL 2019/2020 succeeds during build but fails during runtime

### ISSUE THREAD

**Issue by i-shenl** [numpy/numpy#16310]
I'm trying to install numpy 1.18.x (1.1.8.1 and 1.18.4)  from source on python 3.8.2 on Windows with linkage to MKL 2019 but get the error below when running "import numpy" after running the python interpretor despite following the instructions in it to try to rectify it. I've looked through the issues tracker here and tried the suggestions in them but to no avail. Building numpy against MKL does not appear to be a problem but the build output says "numpy 1.18.x installed successfully" and there are no apparent errors when I check the build log after it builds. Re-installing numpy from a wheel won't help because I need to be able to build and install it from source and linked to MKL.

I've tried adding the path to the MKL redistributables and libraries to the PATH variable but that did not help. Any ideas on what else I can do to troubleshoot this? My questions are:

1) what DLL is it looking? 
2) Related to step 1, I tried doing a dependency check on the _multiarray_umath.cp38-win_amd64 extension file that was built and the deps it needs are there. Is this the correct file to check?
3) What binaries should I be looking for and expect to see after it finishes building? 
4) what other library paths can I try adding before running?
5) Do the instructions in this link https://software.intel.com/content/www/us/en/develop/articles/building-numpyscipy-with-intel-mkl-and-intel-fortran-on-windows.html on building numpy with python 3.8 and MKL still apply? I tried them but no luck. 
6) I see Christoph Golke managed to do it but there are no build steps on his site. Would it be wrong to assume that he didn't have to tweak any files?. https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy  

### Numpy/Python version information:

1.18.1 on python 3.8.2 on Windows with MKL 2019. Have tried 1.18.4 and MKL 2020 but still get 
the same error. Have tried it on Windows Server 2016 and Windows 10.

## Environment

Have set MKLROOT to the location of the MKL headers and libraries when building. Also tried setting the paths to the MKL libs in site.cfg but no luck.

### Error message:

Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "C:\Temp\ActiveState-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Temp\ActiveState-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Temp\ActiveState-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Temp\ActiveState-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Temp\ActiveState-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "C:\Temp\ActiveState-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

**Comment by mattip** [comment]
Python 3.8 introduced a new way of telling windows where to look for support DLLs. They decided `PATH` was not the right way to do it, and introduced a new [`os.add_dll_directory`](https://docs.python.org/3/library/os.html#os.add_dll_directory) function. Please try calling this with the path to your added DLLs. Note that the wheels you download from PyPI or ananconda activation should do this for you. In the case of PyPI wheels, the code is found [in `generate_config_py`](https://github.com/numpy/numpy/blob/v1.19.0rc1/numpy/distutils/misc_util.py#L2289) and generates a `__config__` file which should be loaded as part of `import numpy` Maybe this file is not being generated or its contents are not correct for your local build.

**Comment by i-shenl** [comment]
Thanks. That did the trick. Didn't realize that they changed it in 3.8. This can be closed now.
