### ISSUE TITLE
Possible typo "homogenous"

### ISSUE THREAD

**Issue by tbm** [numpy/numpy#16324]
The documentation uses the word "homogenous" a few times.

I think the correct spelling is "homogen**e**ous".  I was wondering if "homogenous" might be a scientific term.  I found:

* Homogenous is an older scientific term that describes similar tissues or organs. It has been replaced by homologous
* According to The Oxford Guide to English Usage, the word homogenous is a frequent error for homogeneous

So I'm not sure...

**Comment by rossbar** [comment]
It is very likely that "homogeneous" is always the intended word, and that instances of "homogenous" are just misspellings. A PR to fix this would be welcome.

**Comment by kevmo** [comment]
@tbm, you are correct.  @rossbar - was looking for something to contribute, here you go.  Thanks for all your excellent work on this library! https://github.com/numpy/numpy/pull/16333
