### ISSUE TITLE
BUG: Refcounting issues in current master

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#16339]
I ran a valgrind-leaks (with python3.7 debug) on current master, which should thus also apply to 1.19 (deleted the spurious ones):

* ```numpy/core/tests/test_scalarbuffer.py::TestScalarPEP3118::test_str_ucs4[ascii]: leaked references: [3, 3], memory blocks: [4, 4]```
* (Real known leak in an error path, I don't care. Tidying that code up would be worth more than fixing the leak) ```numpy/core/tests/test_ufunc.py::TestUfunc::test_inplace_fancy_indexing: leaked references: [1, 1]```
* (PR to fix is open) ```numpy/lib/tests/test_function_base.py::TestAddDocstring::test_add_same_docstring: leaked references: [1, 1], memory blocks: [1, 1]```
* (PR to fix is open) ```numpy/lib/tests/test_function_base.py::TestAddDocstring::test_different_docstring_fails: leaked references: [1, 1]```
* ```numpy/random/tests/test_generator_mt19937.py::TestMultinomial::test_multidimensional_pvals: leaked references: [1, 1]```
* ```numpy/random/tests/test_generator_mt19937.py::TestRandomDist::test_dirichlet_bad_alpha: leaked references: [1, 1]```
* ```numpy/random/tests/test_random.py::TestMultinomial::test_multidimensional_pvals: leaked references: [1, 1]```
* ```numpy/random/tests/test_random.py::TestRandomDist::test_dirichlet_bad_alpha: leaked references: [1, 1]```

The random ones seem real and like they are all related to https://github.com/numpy/numpy/pull/15876 but I did not yet figure it out. It may or may not be a real memory leak.

I would like the random ones fixed, just to be sure its not leaking a full `pvals`.

EDIT: Btw. in case someone wonders if we should run this regularly. The full run took almost 8 hours.

**Comment by h-vetinari** [comment]
> EDIT: Btw. in case someone wonders if we should run this regularly. The full run took almost 8 hours.

Would it make sense to run something more expensive CI jobs like valgrind (or asv perf checks) in a nightly CI?

**Comment by seberg** [comment]
I dunno, asv is currently hosted on a machine by Pauli. I guess it could make sense but I am not too motivated on doing it and bugs are actually pretty rare. I guess like 1-3 per release and usually trivial (i.e. it seems fine if we fix it up later and the original author is not involved).
I guess with larger changes, this would flush out bugs much more likely, but its fairly easy to run locally.

What I would like more to get the code coverage running again.

**Comment by seberg** [comment]
I doubt the first one is a serious leak. I was unable to reproduce it running that single file. I will just blame the buffer caching machinery being hit in that particular run in that particular test. (Although I am not yet clear why it should trigger, since pytest-leaks runs the test multiple times).

**Comment by seberg** [comment]
Surprisingly, it seems valgrind found an actual dimension leak somewhere, and I need to narrow it down...

**Comment by seberg** [comment]
Found it, har... breaking the ABI (in a tiny way, if thats necessary?) to enable tracemalloc on the dimensions might be good... then I would have found this earlier. But I guess not high preiority. (I rarely ran the full valgrind _with full leakchecking_ since that took 24 hours now – with enabling test-level leak precision though, checking less often is much faster).

**Comment by seberg** [comment]
Found using valgrind, this may or may not be a real issue:
```
________________________________________________________________________________________________________________ TestCharacter.test_char_radd ________________________________________________________________________________________________________________
[VALGRIND LEAK]

Valgrind has detected a memory leak:

**488386** 
**488386** **********************************************************************
**488386** build/testenv/lib/python3.8/site-packages/numpy/core/tests/test_scalarinherit.py::TestCharacter::test_char_radd
**488386** **********************************************************************
==488386== 48 (+48) (32 (+32) direct, 16 (+16) indirect) bytes in 1 (+1) blocks are definitely lost in loss record 5,323 of 33,034
==488386==    at 0x483677F: malloc (vg_replace_malloc.c:309)
==488386==    by 0x6A74B10: _buffer_info_new (buffer.c:458)
==488386==    by 0x6A74B10: _buffer_get_info (buffer.c:595)
==488386==    by 0x6A75252: gentype_getbuffer (buffer.c:817)
==488386==    by 0x5F32D2: UnknownInlinedFun (abstract.c:364)
==488386==    by 0x5F32D2: bytes_concat.lto_priv.0 (bytesobject.c:1439)
==488386==    by 0x567A88: _PyEval_EvalFrameDefault (ceval.c:1559)
```

It has to do with buffers and that on scalars... which is notorious since we store them in a dictionary as integers. But as far as I can see, that test should be freeing the scalar and thus the bufferinfo...

**Comment by seberg** [comment]
There is one more in a pickle test that was confusing me, not that I guess it will happen. But parameterized test, if run only once will leak the buffer-info of course, since the array is attached to the parameterize and thus never cleared in that test run...
