### ISSUE TITLE
Make ctypes completely optional on Windows

### ISSUE THREAD

**Issue by zooba** [numpy/numpy#16331]
There are a couple of places where `ctypes` is presumed to be available, which means `numpy` cannot be imported on systems/distributions that do not include it.

These are [`_dtype_ctypes.py`](https://github.com/numpy/numpy/blob/master/numpy/core/_dtype_ctypes.py), and the [`_distributor_init.py`](https://github.com/numpy/numpy/blob/bfb156741a92f77c13c50d82fc5a1f4d6177a9f5/tools/openblas_support.py#L197) generated for `libopenblas`.

The `_dtype_ctypes` module seems easy enough to update to match the other ctypes-using modules (or simply delay the [eager import](https://github.com/numpy/numpy/blob/master/numpy/core/__init__.py#L100) or handle it failing). I can't find any uses in numpy itself though, so I have no idea what its compatibility constraints are.

The `_distributor_init.py` file is somewhat redundant with the [generated `__config__.py`](https://github.com/numpy/numpy/blob/8087e1de04d011f7ce66bf80dbef4a0599b14f7a/numpy/distutils/misc_util.py#L2289), but could also just do nothing when ctypes fails to import.

I'm happy to send a PR, but it's not obvious which fixes would be preferred. If I were going to keep it simple, I'd defer the `import ctypes` in `_dtype_ctypes` into the function(s) that use it, and add an early exit from the `_distributor_init.py` when ctypes is unavailable.

**Comment by eric-wieser** [comment]
> I can't find any uses in numpy itself though, so I have no idea what its compatibility constraints are.

It's imported by the c extension modules.

**Comment by eric-wieser** [comment]
The use in distributor_init is windows only, right? Is that ever missing ctypes anyway?

**Comment by zooba** [comment]
> The use in distributor_init is windows only, right? Is that ever missing ctypes anyway?

It is if you care enough about security to disable it :)

> It's imported by the c extension module

Okay, thanks for the pointer. But it looks like it is only used when you have passed in ctypes values? Which means if you're not using ctypes, you'll never hit those code paths?

**Comment by eric-wieser** [comment]
> Which means if you're not using ctypes, you'll never hit those code paths?

Correct. It's possible the module isn't even imported in that case.

**Comment by seberg** [comment]
@zooba just cruious, but I am a bit wondering about the security part. If you disable ctypes for security, it seems to me that allowing full NumPy API access would be an issue. Of it is much less convenient convenient then using ctypes directly, but probably not much more than a small layer of obfuscation? (The main issue is the `__array_interface__`, since it allows passing data by pointer.)

**Comment by zooba** [comment]
> Correct. It's possible the module isn't even imported in that case.

Unfortunately not, it's imported as part of `numpy/core/__init__.py` --> https://github.com/numpy/numpy/blob/master/numpy/core/__init__.py#L100

> If you disable ctypes for security, it seems to me that allowing full NumPy API access would be an issue.

Yeah, you're probably right. I'll deal with that one when our pentesters discover it ;) Thanks for the heads-up though.

**Comment by zooba** [comment]
I posted a PR with the changes I made in my fork. There's more than can be done to tidy up these bits of code, but I went with the minimal change.
