### ISSUE TITLE
Uninformative error message when trying to install using python<3.6

### ISSUE THREAD

**Issue by wrzadkow** [numpy/numpy#16345]
Because `setup.py` (lines [182](https://github.com/numpy/numpy/blob/master/setup.py#L182), [191](https://github.com/numpy/numpy/blob/master/setup.py#L191)) uses f-strings introduced in python 3.6, anyone using lower version of python would get a syntax error message. The [code checking if version>=3.6](https://github.com/numpy/numpy/blob/master/setup.py#L29) and producing an informative error message for the user would not be executed.

Possible solutions include but are not limited to:
1. Putting the f-strings in try-catch block, e.g.
```
try:
    eval("raise ValueError(f'Submodule {p} missing')")
except SyntaxError:
    raise RuntimeError('Support for f-strings required')
```

2. Removing f-strings and using "traditional" string formatting methods for backward compatibility

AFAIK using `from __future__ import` would be troublesome here https://stackoverflow.com/questions/42097052/can-i-import-pythons-3-6s-formatted-string-literals-f-strings-into-older-3-x

If a decision is made to address this non-critical issue and change `setup.py` in any way, I will be glad to submit a PR.

### Reproducing code example:
e.g. `python setup.py build_ext -i`

### Error message:
```
  File "setup.py", line 182
    raise ValueError(f'Submodule {p} missing')
                                            ^
SyntaxError: invalid syntax
```

### Numpy/Python version information:
`1.16.3 3.5.2`

**Comment by eric-wieser** [comment]
We should just remove the f-strings in this file I think
