### ISSUE TITLE
Unnecessary copying of read-only arrays negates benefit of BLAS saxpy

### ISSUE THREAD

**Issue by brpdt** [numpy/numpy#16347]
BLAS saxpy provides a substantial improvement over the native numpy equivalent but any improvement is lost when _input_ x is marked read-only:

### Reproduction

```python
import scipy.linalg.blas, numpy as np, mkl
mkl.set_num_threads(1)

size = 100*1000**2
y = np.zeros(size, dtype=np.float32)
x = np.ones_like(y)
a = 0.1

# blas: 10 loops, best of 3: 75.3 ms per loop
scipy.linalg.blas.saxpy(x, y, a=a)

# numpy: 1 loop, best of 3: 202 ms per loop
y += x * a
```

However when x is read-only saxpy is no faster than numpy as f2py makes a copy of x:

```python
x.setflags(write=False)

# blas: 1 loop, best of 3: 210 ms per loop
scipy.linalg.blas.saxpy(x, y, a=a)

# numpy: 1 loop, best of 3: 206 ms per loop
y += x * a
```

### Root cause

The copy is made as this test of layout order fails for read-only arrays: https://github.com/numpy/numpy/blob/master/numpy/f2py/src/fortranobject.c#L737.

The test is calling:

```c
#define PyArray_ISFARRAY(m) PyArray_FLAGSWAP(m, NPY_ARRAY_FARRAY)
```

But those flags test for a writable arrays:

```c
#define NPY_ARRAY_BEHAVED (NPY_ARRAY_ALIGNED | NPY_ARRAY_WRITEABLE)
 ...
#define NPY_ARRAY_FARRAY (NPY_ARRAY_F_CONTIGUOUS | NPY_ARRAY_BEHAVED)
```

Arguments marked intent(in) should instead check array flags against NPY_ARRAY_FARRAY_RO to avoid this unnecessary copy:

```c
#define NPY_ARRAY_FARRAY_RO (NPY_ARRAY_F_CONTIGUOUS | NPY_ARRAY_ALIGNED)
```

 [1] x is readonly in our use-case as we wrap a network buffer using np.frombuffer(str). It's no longer possible to force this writable due to change https://github.com/numpy/numpy/pull/11739.

### Numpy/Python version information:

numpy 1.16.5
python 3.7.5

**Comment by eric-wieser** [comment]
Seems very reasonable, patch welcome.

> x is readonly in our use-case as we wrap a network buffer using np.frombuffer(str). It's no longer possible to force this writable due to change

Would it be possible to get your network buffer using `readinto`, so that you can use `np.frombuffer(bytearray)` instead?
