### ISSUE TITLE
Inconsistent behaviour of division of 0d ndarray compared to 1+d ndarray with respect to dtype

### ISSUE THREAD

**Issue by KelSolaar** [numpy/numpy#16353]
Hi,

This one gave me some headaches and was hard to pin-point but here it is: Dividing a `ndarray` with a single scalar element and a `dtype` different from `np.float64`, e.g. `np.float16` produces a different `dtype` than dividing a `ndarray` with a sequence of that single scalar.

The single-scalar based array does not preserve its `dtype` while the sequence-based one does. I'm assuming it is because the paths taken to perform the division are different but this behaviour caught me by surprise (and not a good one :) ).

### Reproducing code example:

```python
>>> import numpy as np
>>> type(np.array(57.65625, dtype=np.float16))
<class 'numpy.ndarray'>
>>> type(np.array([57.65625], dtype=np.float16))
<class 'numpy.ndarray'>
>>> (np.array(57.65625, dtype=np.float16) / 100).dtype
dtype('float64')
>>> (np.array([57.65625], dtype=np.float16) / 100).dtype
dtype('float16')
```

**Bonus Code**

It seems like the dividend type always wins here.

```python
>>> (np.array(57.65625, dtype=np.float16) / np.array([57.65625], dtype=np.float64)).dtype
dtype('float64')
>>> (np.array(57.65625, dtype=np.float64) / np.array([57.65625], dtype=np.float16)).dtype
dtype('float16')
```

### Numpy/Python version information:

```
1.18.1 3.7.6 (default, Dec 30 2019, 19:38:26)
[Clang 11.0.0 (clang-1100.0.33.16)]
```

**Comment by eric-wieser** [comment]
I think what you're actually seeing here is that the non-0d array type always wins

**Comment by KelSolaar** [comment]
Hi @eric-wieser,

This explains the *Bonus Code* but what about the `dtype` change in the main repro-code example?

**Comment by eric-wieser** [comment]
It's the  same thing, except in the first line example both objects are 0d, so the result is found as the best type to contain both 100 (inferred as `np.int_`) and `np.float16`.

In the second one, the array just wins, so the type of the `100` is ignored.

We're not super happy with this behavior, but it's tricky to change.

**Comment by KelSolaar** [comment]
Thanks Eric, makes sense, is it something worth documenting?

Maybe in the [dtypes](https://numpy.org/doc/stable/reference/arrays.dtypes.html) page? It shares some traits with this older issue I reported a few years ago: https://github.com/numpy/numpy/issues/11956

**Comment by seberg** [comment]
Consistent in main now due to NEP 50.

**Comment by KelSolaar** [comment]
Thanks a lot, glad to see all those coming in!
