### ISSUE TITLE
Python 3 is Incompatible with Numpy.

### ISSUE THREAD

**Issue by Excalibur-Proto** [numpy/numpy#16361]
When running python 3.3 with Numpy 1.18, error is returned: "numpy module is not found."

It seems in general the latest version of numpy isn't compatible with Python 3.3 (I have checked the system environment variables to ensure that numpy is in them from the control panel.)

**Comment by charris** [comment]
1.8 supports Python >= 3.5, we haven't supported 3.3 for a long time. That may not be the problem here, how did you try to install numpy, and why such an old version of Python?

**Comment by Excalibur-Proto** [comment]
Hi! I upgraded to 3.8 and got the same issue. . .
I installed numpy with pip3 install numpy.

**Comment by charris** [comment]
Try `python3.8 -mpip install numpy`.  You never know what python version pip3 points to. For reference, what OS are you using?

**Comment by charris** [comment]
It is bad to overlay system Python (if any), things break, so be careful.

**Comment by Excalibur-Proto** [comment]
Thanks so much for your help! I'm using W10.

**Comment by Excalibur-Proto** [comment]
It says "-mpip is not recognized as an internal or external command."

**Comment by charris** [comment]
It needs to be the full string: `python3.8 -mpip install numpy`. You might find it easier on Windows to use  Anaconda or some other distribution.

**Comment by mattip** [comment]
> I have checked the system environment variables to ensure that numpy is in them from the control panel

This sounds wrong. You need to install a complete python environment for each version of python you work with. They should be self contained. Adding paths for python to any system-wide environment variables (PATH, PYTHONPATH, PYTHONHOME, ...) is usually problematic.

**Comment by rossbar** [comment]
I'm going to close this due to inactivity - if the issue persists please feel free to reopen!
