### ISSUE TITLE
np.cov

### ISSUE THREAD

**Issue by MilanCugur** [numpy/numpy#16379]
### Reproducing code example:

```python
import numpy as np
np.cov(MATRIX)
```

### Error message:

If there are nan columns in matrix MATRIX numpy fill all RAM on mu pc. Afterwards its going to be killed by os.

**Comment by eric-wieser** [comment]
Can you show `type(MATRIX)`, `MATRIX.dtype`, and `MATRIX.shape` so we can attempt to debug this?

**Comment by rossbar** [comment]
I'm going to go ahead and close this due to lack of information to go on.

@MilanCugur if you are still having issues, feel free to re-open/open a new issue with additional information on OS, version numbers, how numpy was installed, etc.
