### ISSUE TITLE
DOC: Improper configuration for LaTeX documentation

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#16372]
The `conf.py` in `doc/source` lists has the following configuration building latex documents:

https://github.com/numpy/numpy/blob/3f11db40d80b6ff122f41185b0b93637bdff0e39/doc/source/conf.py#L158-L166

However, `user/index` was removed in 22356fc0 as part of the NEP 44 restructuring, which means this configuration is no longer valid and attempting to build the latex docs (as is done for the documentation release process, for example) will fail as a result.

Either `doc/source/user/index.rst` should be added back or the sphinx configuration needs to be updated with a new start file for the user guide.

### Reproducing code example:

Within a properly setup environment for building docs:

```
cd doc && make latex
```

### Error message:

The following warning is given by sphinx:

```
WARNING: "latex_documents" config value references unknown document user/index
```

The build will terminate without attempting to compile `numpy-user.tex`.

### Numpy/Python version information:

Python 3.8.3 | numpy v1.20.0.dev0+3f11db4

**Comment by melissawm** [comment]
I'm not sure what's the best way forward here, since the old "User Guide" would now be equivalent to everything under "For users"  on the main docs page. Maybe adding a `index.rst` that contains just the links to those sections?

**Comment by rossbar** [comment]
Yeah I wasn't sure either - I have a proposal in #16373 that tries to achieve the best of both worlds, i.e. leave the html docs relatively untouched (by reintroducing index as an orphan), but adds back the necessary component for the latex build.

If that solution sounds okay, please take a look at the toctree in #16373 to see if the listings there should be updated.

**Comment by mattip** [comment]
It would be nice if we could hide the unwanted links with an [`.. only` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-only). But it doesn't work, there are a few "won't fix" issues like [this one](https://github.com/sphinx-doc/sphinx/issues/1717) about this.

**Comment by rossbar** [comment]
Thanks for the info @mattip , I'll give `.. only` a try.

**Comment by rossbar** [comment]
AFAICT after trying reading about `.. only` and `.. ifconfig` these directives are helpful for control which content *within* files is presented, but not whether the file itself is included for different configurations. We could include a `.. only` directive in `user/index.rst`, but that wouldn't suppress the generation of the html file itself, it would just make the page itself blank.
