### ISSUE TITLE
np.where returns tuple instead of array

### ISSUE THREAD

**Issue by Baschdl** [numpy/numpy#16374]
Contradictory to the documentation, `np.where` returns a tupel with the new array instead of only the array.

### Reproducing code example:
```python
import numpy as np

a =  np.arange(10)
np.where(a < 5)
# (array([0, 1, 2, 3, 4]),)
```

### Numpy/Python version information:

1.17.2 3.7.4 and also 1.18.4 3.7.7

**Comment by rossbar** [comment]
The top of the docstring for `np.where` includes this note:

```
.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.
```

So the "Returns" section of the docstring only applies to the use case where three arguments are specified, thus an ndarray output should not necessarily be expected.

IMO the documentation is clear in this regard, though PRs to improve the documentation are welcome.

**Comment by Baschdl** [comment]
I personally find it a bit confusing currently because I would assume that the method even as a shorthand for another method returns the same type as `np.where(condition, x, y)`. Even more confusing is that `np.where(condition, x, y)` returns values (x or y) where `np.asarray(condition).nonzero()` returns the matching indices.

I agree with you that all the needed information is in the current note but an additional comment in the returns section could make it clearer. I'm happy to open a PR if you're fine with an addition to the returns section.

**Comment by rossbar** [comment]
Of course - please feel free to propose anything that would be an improvement in your opinion!

**Comment by eric-wieser** [comment]
It's unfortunate that `where` was built this way. The simplest mental model is _"never use `where(arr)`, always use `nonzero(arr)`"_. If you follow that rule, no one reading your codebase has to work out what these docs mean in the first place!

**Comment by eric-wieser** [comment]
Unfortunately, we likely can't actually deprecate it and force people to make this switch, because there will be way too many use cases in the wild.

**Comment by eric-wieser** [comment]
@Baschdl: Do you think you'll get around to proposing a wording change? If not, I think we should close this - it's too subjective for anyone else to work on it I think.

**Comment by Baschdl** [comment]
Yes, probably in the next few days

**Comment by rossbar** [comment]
I'm going to close this due to inactivity - PRs with proposed wording improvements are of course still welcome!
