### ISSUE TITLE
I think this already exists? Using the wikipedia example:

### ISSUE THREAD

**Issue by tatar28** [numpy/numpy#16381]
I think this already exists? Using the wikipedia example:

```python
>>> np.percentile(15, 20, 35, 40, 50], [5, 30, 40, 50, 100], interpolation='lower')
array([15, 20, 20, 35, 50])
```

_Originally posted by @eric-wieser in https://github.com/numpy/numpy/issues/10736#issuecomment-372551345_

**Comment by tatar28** [comment]
I think this already exists? Using the wikipedia example:

**Comment by tatar28** [comment]
I think this already exists? Using the wikipedia example:

**Comment by tatar28** [comment]
I do not understand the conversion of documents or various system projects. Problems with language and language help in an easy way that I understand and can access.

**Comment by eric-wieser** [comment]
@tatar28, what exactly are you trying to do here?

**Comment by tatar28** [comment]
> I think this already exists? Using the wikipedia example:
> 
> ```python
> >>> np.percentile(15, 20, 35, 40, 50], [5, 30, 40, 50, 100], interpolation='lower')
> array([15, 20, 20, 35, 50])
> ```
> 
> _Originally posted by @eric-wieser in [#10736 (comment)](https://github.com/numpy/numpy/issues/10736#issuecomment-372551345)_
