### ISSUE TITLE
Increase font size of user documentation 

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#16388]
Our user docs would be more readable -- hence effective -- if the type were larger.

If you were to guess at a glance which of these had a clearer author, wouldn't you guess the second?
<br>
![image](https://user-images.githubusercontent.com/6691888/82939397-51214380-9f61-11ea-8198-155c03ff9a44.png)

<br>

![image](https://user-images.githubusercontent.com/6691888/82939615-9b0a2980-9f61-11ea-8e69-1ef34932eb04.png)

Looks matter -- as we know from our new website.

Increasing the font size would be the docs equivalent of "Did you lose weight? Did you get a haircut?"

- The automated pages probably can stay as they are. 
- No change in the Table of Contents sidebars, where space is at a premium already. 
- The non-sidebar TOCs should get larger type, too, but not as large as the text.

**Comment by rgommers** [comment]
I agree. We should be moving the docs over to the new Sphinx theme (https://github.com/scipy/scipy-sphinx-theme-v2) which already has larger font I believe.

**Comment by bjnath** [comment]
No need to keep this open then. Thanks!
