### ISSUE TITLE
Docstring example for np.records.core.fromstring doesn't render properly

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#16390]
The docstring for `np.core.records.fromstring` contains the following snippet:

```rst
    Examples                                                                    
    --------                                                                    
    >>> a = b'\x01\x02\x03abc'                                                  
    >>> np.core.records.fromstring(a, dtype='u1,u1,u1,S3')                      
    rec.array([(1, 2, 3, b'abc')],                                              
            dtype=[('f0', 'u1'), ('f1', 'u1'), ('f2', 'u1'), ('f3', 'S3')])
```

Some characters from the example are dropped in the [rendered docstring](https://numpy.org/devdocs/reference/generated/numpy.core.records.fromstring.html), i.e. `a = b'\x01\x02\x03abc` becomes `a = b'abc'`.

### Numpy/Python version information:

1.20.0.dev0+e4894ae 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]

**Comment by rossbar** [comment]
Also reported here: sphinx-doc/sphinx#7735

**Comment by WarrenWeckesser** [comment]
This should be fixed by making the docstring a raw string: https://github.com/numpy/numpy/pull/16393
