### ISSUE TITLE
Numpy array error - storing data

### ISSUE THREAD

**Issue by OldTyke** [numpy/numpy#16401]
After working out a value, the value stored in the numpy array differs from the original.

### Reproducing code example:

import numpy as np

num = 54133488902259149863

TESTNUMS = 256

y = num.bit_length ()
y = y // 8

testArray = np.zeros((TESTNUMS, 2))

for x in range(2, TESTNUMS):
    xMod1 = x
    for count in range(1, y):
        xMod1 = ( xMod1 << 8) 
        xMod1 = xMod1 | x

    if x == 64:
        print( "{0:b}".format(xMod1))
        print(xMod1)
    testArray[x,1] = xMod1

    if x == 64:
        print(int(testArray[x,1]))
        print(int(testArray[64,1]))
        print(xMod1)

    testArray[x,0] = x

I have singled out 64 for the example

Output of the above code is:

runfile('G:/pY/Mixed/Mixed/crap.py', wdir='G:/pY/Mixed/Mixed')
100000001000000010000000100000001000000010000000100000001000000
4629771061636907072
4629771061636907008
4629771061636907008
4629771061636907072

making the stored value differ from the calculated one.

```

<!-- Remove these sections for a feature request -->

### Error message:

Noine

### Numpy/Python version information:

import sys, numpy; print(numpy.__version__, sys.version)
1.18.1 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)]

**Comment by mattip** [comment]
Please reformat the code snippet to turn it into valid python: use the `...` in the upper right-hand corner of your description comment to get a pull-down menu, and hit edit, then use the `<>` code format on the tool bar. More info [here](https://guides.github.com/features/mastering-markdown/). You can use the "Preview" tab to make sure it looks OK. 

Once that works, try to reformulate what you expect vs. what you got in terms of the variables you are using: "I expected `testArray[64, 1]` to be `xxx` but got `yyy`". You used the terms "stored" and "calculated", it is not clear to me what they refer to.

**Comment by rossbar** [comment]
I'm going to close due to inactivity - if the problem persists please follow up (a well-formatted minimal-reproducing example would be very helpful).
