### ISSUE TITLE
Numpy wheel for ARMv7 processor 

### ISSUE THREAD

**Issue by FlorentijnD** [numpy/numpy#16424]
@Feature request/question

**System information**
- Hardware : Freescale i.MX6 Quad/DualLite
- Processor: ARMv7 Processor rev 10 (v71)
- OS Platform and Distribution: Yocto built Linux distribution (kernel 4.9.4+)
- Installed python version: 3.6.5 (can be altered to 3.7/3.8)
- Installed pip3 version: 9.0.3 (can be altered too)

I'm trying to find a numpy wheel which I can install using pip3 on the hardware as described above. I tried the p36 wheel of this index (https://gergely.imreh.net/wheels/numpy/) to no avail (`numpy-1.12.0-cp36-cp36m-linux_armv71.manylinux1_armv71.whl is not a supported wheel on this platform`). Where could I find them?

**Comment by rgommers** [comment]
I don't know, I'm not aware of any. For ARMv7 binaries I think you could use, e.g., Debian or Berryconda, or build from source.

We're adding `aarch64` wheels, but ARMv7 won't happen anymore. There's no CI support for it, nor `manylinux` support I believe.

**Comment by FlorentijnD** [comment]
Do you mean installing the zip on PyPi as "building from source"? (https://files.pythonhosted.org/packages/2d/f3/795e50e3ea2dc7bc9d1a2eeea9997d5dce63b801e08dfc37c2efce341977/numpy-1.18.4.zip) If so, I'm encountering an issue: `No matching distribution found for setuptools` `Could not find a version that satisfies the requirement setuptools (from versions: none)` though I have setuptools (47.1.1) installed

**Comment by rgommers** [comment]
> Do you mean installing the zip on PyPi as "building from source"?

Indeed. Either with pip, or downloading it and doing `python setup.py install`.

Looks like you're using `pip`, which tries to do an isolated install. For that it needs to reinstall all dependencies in a tmpdir, and it fails to find setuptools - maybe because something was wrong in your network, or because of some metadata issue for armv7. Either way, I suggest avoiding pip.

**Comment by FlorentijnD** [comment]
Installing from source seems to have worked fine. Thank you for your help!
