### ISSUE TITLE
Ufuncs return scalars for 0D input (Trac #1044)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1642]
_Original ticket http://projects.scipy.org/numpy/ticket/1044 on 2009-03-09 by @pv, assigned to unknown._

--- Continuation of #1440.

Ufuncs return array scalars for 0D array input:

```
>>> import numpy as np
>>> type(np.conjugate(np.array(1+2j)))
<type 'numpy.complex128'>
>>> type(np.sum(np.array(3.), np.array(5.)))
<type 'numpy.float64'>
```

Should they return 0D arrays instead?

**Comment by eric-wieser** [comment]
Related to #5819

**Comment by eric-wieser** [comment]
This PR duplicates #4563 - since there's more relevant discussion there, I'm closing this one.
