### ISSUE TITLE
__str__-method seems to use __repr__-method of dtype instead of __str__

### ISSUE THREAD

**Issue by FranzAtGithub** [numpy/numpy#16443]
Hello,

I am teaching the basics of numerical linear algebra using NumPy to implement some examples. In this context I would like to use the `decimal.Decimal` class inside of an `ndarray` to showcase the relevance of the number of precision bits for the outcome of an algorithm.

However I find the the screen output of such an array is rather hard to read. It seems as if NumPy displays the contents of an array using the `__repr__`-method instead of the `__str__` method.

To see this consider the following script:

```python
import numpy as np
import decimal as dm
print(dm.Decimal('1.2').__repr__())
print(dm.Decimal('1.2').__str__())
print(np.array([dm.Decimal('1.2')]).__repr__())
print(np.array([dm.Decimal('1.2')]).__str__())  # this should give [1.2]
```
The last line gives `[Decimal('1.2')]` but I feel like it would better simply give `[1.2]`.

Is this intended behavior?
Can I "fix" this without to much boilerplate code (that could confuse students)?

I am using:
Ubuntu 18.04
Python 3.6.9
Numpy 1.17.4

**Comment by eric-wieser** [comment]
Note that this behavior is consistent with the behavior of `str([Decimal('1.2')])` when not using `numpy`, so it's unlikely we will change this.

However, you can certainly configure this to behave how you want:
```python
with np.printoptions(formatter=dict(object=str)):
    print(np.array([dm.Decimal('1.2')]))
```
or if you want it to be set globally
```python
np.set_printoptions(formatter=dict(object=str)):
print(np.array([dm.Decimal('1.2')]))
```

**Comment by FranzAtGithub** [comment]
Thank you very much.
In fact I was not aware of the fact that this is the same behavior for normal lists as well.
