### ISSUE TITLE
problem with site-packages/numpy/core/overrides.py: numpy.core._multiarray_umath not found

### ISSUE THREAD

**Issue by LiranAvda-TAU** [numpy/numpy#16451]
Hello, I've been using numpy in my code and everything was good, now I'm trying to deploy the app to an A2HOSTING server and I get this error when trying to import numpy (from down upward):

[ E 2020-05-31 02:36:36.1358 14684/T33 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/wormcool/wormcoolkit: The application process exited prematurely.
App 19124 output:   File "/home/wormcool/virtualenv/wormcoolkit/3.6/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
App 19124 output:   File "/home/wormcool/virtualenv/wormcoolkit/3.6/lib/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
App 19124 output:   File "/home/wormcool/virtualenv/wormcoolkit/3.6/lib/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
App 19124 output:   File "/home/wormcool/virtualenv/wormcoolkit/3.6/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
App 19124 output:   File "/home/wormcool/virtualenv/wormcoolkit/3.6/lib/python3.6/site-packages/pandas/__init__.py", line 11, in <module>

I looked into the overrides.py file in line 7 and I suspect the problen is with numpy.core._multiarray_umath, since it's mentioned in the line and is no where in the directory (this is all the error I get from the error log)

### Numpy/Python version information:
python: I'm using python 3.6.8 but I've also tried to switch to 3.7.3 (these are the options I'm offered) and nothing changed. On my local pc where the code runs and numpy is imported successfully I use anaconda and python 3.6.9 (I cannot use anaconda on the server)
numpy: I'm using 1.18.4

Please tell me what can I do. I've tried uninstalling and installing numpy again and searched for answers through the internet but found none that worked for me.

**Comment by mattip** [comment]
> I'm trying to deploy the app to A2HOSTING server 

How did you deploy the app? Did you follow [this guide](https://www.a2hosting.com/kb/developer-corner/python/using-virtualenv-and-pip) to create a virtualenv and pip-install numpy?

**Comment by LiranAvda-TAU** [comment]
Yes, I followed this guide, every other thing works and the app itself runs if I delete the numpy import and the relevant code

> > I'm trying to deploy the app to A2HOSTING server
> 
> How did you deploy the app? Did you follow [this guide](https://www.a2hosting.com/kb/developer-corner/python/using-virtualenv-and-pip) to create a virtualenv and pip-install numpy?

Yes, I followed this guide. Every other installation and import works just fine and I pretty much done with the deployment part (if I take out the numpy related part of code)

**Comment by rossbar** [comment]
It seems like there hasn't been any activity here. I'm going to close for now but if the issue persists please feel free to re-open with any additional information that can help narrow down the problem.
