### ISSUE TITLE
Numpy throws columns during slicing

### ISSUE THREAD

**Issue by Harvey13** [numpy/numpy#16455]
Hello 
I'm using numpy on Google Colab and I have this strange behaviour :

```
print(C1,type(y_target))
test390_data =y_target [:,C1:(C1+390)]
test490_data =y_target [:,C1:(C1+490)]
print("test390_data",test390_data.shape)
print("test490_data",test490_data.shape)

```
gives me the following response : 

```
4 <class 'numpy.ndarray'>
test390_data (15074, 390)
test490_data (15074, 486)

```
**Why 486 ?**

_import sys, numpy; print(numpy.__version__, sys.version)
1.18.4 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]_

**Comment by eric-wieser** [comment]
Because there are only 490 columns, so numpy interprets `4:494` as `4:490`
