### ISSUE TITLE
Module not found error 

### ISSUE THREAD

**Issue by Chizzyhub** [numpy/numpy#16478]
I have an issue trying to run all numpy related codes on my gitbash but it runs perfectly fine on my Jupyter notebook. I have only one version of python installed on my system. i tried uninstalling and installing pandas and numpy after i got a **"missing dependencies error"** but now I'm getting another error.

```python
this is the code i typed in my notepad plus
import numpy as np
X = np.array([1,3])

#Trying to run it on git bash gave me the following error message

**Traceback (most recent call last):**
  File "C:\Users\user\Anaconda3\lib\site-packages\numpy\core\__init__.py", line
24, in <module>
    from . import multiarray
  File "C:\Users\user\Anaconda3\lib\site-packages\numpy\core\multiarray.py", lin
e 14, in <module>
    from . import overrides
  File "C:\Users\user\Anaconda3\lib\site-packages\numpy\core\overrides.py", line
 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "learning.py", line 1, in <module>
    import numpy as np
  File "C:\Users\user\Anaconda3\lib\site-packages\numpy\__init__.py", line 142,
in <module>
    from . import core
  File "C:\Users\user\Anaconda3\lib\site-packages\numpy\core\__init__.py", line
54, in <module>
    raise ImportError(msg)
ImportError:
```

My numpy version is 1.18.1 and my python version 3.7 on Anaconda in windows 7 64bit
![Capture](https://user-images.githubusercontent.com/61868329/83468441-ab943580-a474-11ea-8706-33a4749bed00.JPG)

**Comment by mattip** [comment]
Please read [this page](https://numpy.org/devdocs/user/troubleshooting-importerror.html) carefully. Since you only reported part of the error message it is difficult to help you. Typically when using Anaconda users forget to  [activate](https://numpy.org/devdocs/user/troubleshooting-importerror.html#using-python-from-conda-anaconda) their conda environment, perhaps this is tripping you up as well.

**Comment by Chizzyhub** [comment]
Thanks for the help but I reported all the error messages I got. If there's specific error message you'd like to see please let me know

**Comment by seberg** [comment]
Well, the image did not show up due to a formatting error and you did not copy the whole message... In either case the advice Matti linked is still the best we can offer at this time.

**Comment by Chizzyhub** [comment]
Well the entire message is in the image.
And the image is showing up well on my mobile device. Let me resend the image again

**Comment by Chizzyhub** [comment]
![83468441-ab943580-a474-11ea-8706-33a4749bed00](https://user-images.githubusercontent.com/61868329/83536100-b5f11680-a4ea-11ea-9bfc-ace44cfd4ef4.jpeg)

**Comment by seberg** [comment]
@Chizzyhub it was not showing up, I edited the message just before.

**Comment by Chizzyhub** [comment]
I'm sorry, do you mean the image is not still showing up.
Should I send it in a different format. Cos I uploaded it in .jpeg format

**Comment by seberg** [comment]
The images show up (now), you should rather spend time making sure you know everything about activating conda environments that you may need to know.

**Comment by Chizzyhub** [comment]
Everything in the suggestion works fine that's why I opened this issue. I can't seem to figure out the problem and I urgently need it to work as time is not on my side.

**Comment by seberg** [comment]
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#determining-your-current-environment ?

**Comment by Chizzyhub** [comment]
I've checked that out
All the right modules are installed

**Comment by seberg** [comment]
The page I linked was the "Determining your current environment", which shows you if you activated it within that shell. I am not sure what it has to do with installed modules.

**Comment by mattip** [comment]
The warning at the top of your image is a hint that you have not properly activated your conda environment. You need to do `conda activate xxxx` before you run any python commands.

**Comment by Chizzyhub** [comment]
I did see that though.
So to activate conda in git bash, how would I go about it?
Conda activate myenv(what would take the position of myenv?)

**Comment by mattip** [comment]
Click on the page @seberg linked to. It says 
> By default, the active environment---the one you are currently using---is shown in parentheses () or brackets [] at the beginning of your command prompt:
```
(myenv) $
```
> If you do not see this, run:
```
conda info --envs
```

**Comment by Chizzyhub** [comment]
Mine shows (base)

**Comment by seberg** [comment]
And another thing, what is it with the MINGW64 console? Anaconda is fully compiled using msvc, if this mingw64 console changes include paths, things will break.

**Comment by Chizzyhub** [comment]
That terminal in the image is the git bash terminal.

**Comment by rossbar** [comment]
I'm going to close this for now due to inactivity - if the issue persists please feel free to reopen.
