### ISSUE TITLE
pip3 installing numpy  doesn't work on centos7

### ISSUE THREAD

**Issue by kevinsingapore** [numpy/numpy#16480]
OS: centos7-aarch64

**Comment by mattip** [comment]
Closing. We will be providing a wheel once 1.19 is released. If you wish to reopen, please provide more information: what you tried, what happened, what you expected, why you think it failed where others have succeeded.

**Comment by kevinsingapore** [comment]
> Closing. We will be providing a wheel once 1.19 is released. If you wish to reopen, please provide more information: what you tried, what happened, what you expected, why you think it failed where others have succeeded.

OS-Environment：Centos7 (aarch64)
