### ISSUE TITLE
python3.6 and python3.5  cannot access numpy in ubuntu20

### ISSUE THREAD

**Issue by auo355** [numpy/numpy#16494]
I installed ubuntu 20 and it came with the default Python3.7
 I installed python 3.5 and python 3.6 so that i can work with a project on self driving vehicle from coursera.
 
When i run python3.6, i get the error:
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "module_7.py", line 24, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/usr/bin/python3.6",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by charris** [comment]
You need to install NumPy for each Python version. Did you do that?

**Comment by auo355** [comment]
I did but still got the same error for python3.6

for python3.5, when i entered the command   $ python3.5 -m pip install numpy --user
I got the error /usr/local/bin/python3.5: No module named pip

**Comment by auo355** [comment]
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/augustine/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages

**Comment by mattip** [comment]
Calling `python3.6 pip install --user numpy` should have put it in `/home/augustine/.local/lib/python3.6/site-packages`. Is there a numpy directory there?

**Comment by auo355** [comment]
No. There is no numpy directory there

**Comment by rossbar** [comment]
I am going to close this for now as it seems to be more of a system-specific configuration issue. If the issue persists, see the documentation here: https://numpy.org/devdocs/user/troubleshooting-importerror.html for troubleshooting tips.
