### ISSUE TITLE
SWIG: pyfragments.swg dereferences a nullptr for overloaded functions

### ISSUE THREAD

**Issue by gieseanw** [numpy/numpy#16492]
When SWIG (post SWIG-1.3.23) encounters overloaded functions, it generates a wrapper function for each one. Then, it creates a single entry point function for Python to call. This entry point function attempts to find the right overload. It does this by performing test casts of the arguments until it finds an overload that works, which it then calls. This bug happens during those test casts, because SWIG passes a nullptr for the value to convert.

### Reproducing code example:

This reproduces the issue for Windows (64 bit)
```cpp
void repro(unsigned long i = 0)
{
}
```

This reproduces the issue for Linux/gcc (64 bit)
```cpp
void repro(size_t i = 0)
{
}
```

We get a segmentation fault in both scenarios.
The issue comes from
https://github.com/numpy/numpy/blob/master/tools/swig/pyfragments.swg#L59
and
https://github.com/numpy/numpy/blob/master/tools/swig/pyfragments.swg#L109

It can be fixed by first checking for a nullptr (like SWIG's other pyfragments.swg do):

For example:
```cpp
if(!val) return SWIG_OK;
PyArray_CastScalarToCtype(obj, (void*)val, ulongDescr);
```

I'd submit a formal pull request, but for legal reasons I am only allowed to submit this bug report for now.

**Comment by Iamsoto** [comment]
Hi,
I'm new to numpy contributions and want to help out! 
this issue doesn't seem too difficult (for now), mind if I take this?

**Comment by mattip** [comment]
We do not assign issues to users, so you are welcome to try. One of the tricky things about this is the lack of tests for SWIG in our CI runs. You would need to convince someone the fix is correct.

**Comment by Iamsoto** [comment]
hi @gieseanw 
It appears I'm having a problem replicating this error. Would you mind sharing more on how to reproduce it?

I made a seperate directory with my own CMakeLists.txt and .h/.ccp/.i files (thanks to the example in #11876)
It looks like this:
```
CMAKE_MINIMUM_REQUIRED(VERSION 3.10.2)


# Set up libfoo
add_library(foo
	repro.cpp
)
add_definitions(-fPIC)
target_link_libraries(foo)

# Set up swig
SET(InterfaceFile foo.i)

FIND_PACKAGE(SWIG 4 REQUIRED)
FIND_PACKAGE(PythonLibs REQUIRED)
INCLUDE(${SWIG_USE_FILE})

SET(CMAKE_SWIG_FLAGS -c++)

# Get the python site-packages directory
EXECUTE_PROCESS(COMMAND python -c "import site; print(site.getsitepackages()[0])"
	OUTPUT_VARIABLE PYTHON_SITE
	OUTPUT_STRIP_TRAILING_WHITESPACE)

# INCLUDE SOURCE
INCLUDE_DIRECTORIES( ${CMAKE_SOURCE_DIR} )
INCLUDE_DIRECTORIES( ${CMAKE_CURRENT_SOURCE_DIR} )

# PYTHON DIRECTORIES
INCLUDE_DIRECTORIES(${PYTHON_INCLUDE_DIRS} )
LINK_DIRECTORIES( ${PYTHON_LIBRARIES} )

# NUMPY INCLUDES
INCLUDE_DIRECTORIES( SYSTEM /home/brian/Desktop/numpy/numpy/numpy/core/include/ )

SET_SOURCE_FILES_PROPERTIES(${InterfaceFile} PROPERTIES SWIG_MODULE_NAME Foo)
SET_SOURCE_FILES_PROPERTIES(${InterfaceFile} PROPERTIES CPLUSPLUS ON)

SET(SWIG_MODULE_Foo_EXTRA_DEPS
	repro.h
)
SWIG_ADD_MODULE(Foo python ${InterfaceFile})

SWIG_LINK_LIBRARIES(Foo ${PythonFramework} foo)
SET(DLLSuffix so)
```
repro.h: 
```
#include <stdio.h>
void repro(size_t i = 0);
```

repro.cpp (I thought this would replicate the seg fault):
```
#include "repro.h"
void repro(size_t i)
{
	printf("Success :D ");
}
```
interface file: 
```
%module Foo

%{
#include "numpy/arrayobject.h"
#include "repro.h"
%}

%include "numpy.i"

%init
%{
import_array();
%}

%include "repro.h"
```
When I run cmake .. && make everything appears to compile correctly. 
And when I run
 
```
import Foo
Foo.repro()
```
I get 'Success :D'

Feel free to point out anything I've messedup with. I'm still new to SWIG so that's entirely possible. Just trying to learn. 

Here are some specs: 
**Ubuntu** 18.04.3
**SWIG** 4.0.2
**numpy** 1.20.0.dev0+073316d
**cmake** 3.10.2
**gcc** 7.5.0
**Python** 3.6.9

**Comment by gieseanw** [comment]
@Iamsoto make sure pyfragments.swg is in the working directory from where you run swig, per the note from swig: https://github.com/swig/swig/blob/master/Lib/python/pyfragments.swg

You should see the generated fragments in the resulting .cxx file. 

Next, the python script to reproduce this should use a numpy.int64, obtained e.g., like so:

```
import numpy
import Foo
a = numpy.array([1, 2, 3])
Foo.repro(a[0])
```


The other thing to be wary of is that I believe this is technically undefined behavior. I was lucky to enough to get a segfault on both platforms.

In the generated .cxx file for your repro, swig should have generated a wrapper like

```
SWIGINTERNINLINE int
SWIG_AsVal_size_t (PyObject * obj, size_t *val)
```
When you step through your code via gdb, you'll see that internally this function has a test like:

`if (sizeof(size_t) <= sizeof(unsigned long))`
which passes on my platform, and then the function delegates to 

`SWIG_AsVal_unsigned_SS_long`, which the numpy pyfragments.swg has overwritten the end of.

The code eventually reaches 
`if (!PyArray_IsScalar(obj, Integer)) return SWIG_TypeError;`

The check passes, so the code moves on, but `val` is a nullptr the first time around (because SWIG is doing a test cast on the arguments using nullptr first). This causes `PyArray_CastScalarToCtype` to attempt to write to a nullptr.

**Comment by Iamsoto** [comment]
Thank you for the info @gieseanw  !
I do indeed get a seg fault now. The problem was me not using a numpy .int64, which makes sense since that's how the `SWIG_AsVal_size_t` gets called. 

I will start drafting a pull request now I guess!

@mattip for this particular issue, could you let me know where you think a good place to put the tests are? Since there doesn't seem to be anything testing just the _pyfragments.swg_ file per say.

**Comment by mattip** [comment]
There is a `tools/swig/test` directory. But with that, I don't think we run any of those tests currently in CI, nor does it seem do we ship the contents of tools/swig in our wheels. How do users of SWIG usually get numpy wrappers?

**Comment by Iamsoto** [comment]
Hmmm... tools/swig/tests will test some data sctructures being built using numpy.i (and so implicitly pyfragments.swg). But I don't see a test specifically for _pyfragments.swg_. I'm looking at this PR, #11877 that modifys the _pyfragments.swg_ file to fix a bug, but doesn't seem to update any tests. 

So I think, based on that, I will go ahead and make a PR and just make sure all the current tools/swig/tests still pass.
