### ISSUE TITLE
Erratic performance of array transposition operations

### ISSUE THREAD

**Issue by mreineck** [numpy/numpy#16498]
I'm running simple timings of `numpy.ndarray` transposition on an otherwise idle machine and get extreme variations (almost two orders of magnitude) in the required CPU time.
I'm using numpy 1.17.4 with ipython 7.14.0 and Python 3.8.3

### Reproducing code example:

```
martin@debian:~$ ipython3
Python 3.8.3 (default, May 14 2020, 11:03:12) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np                                                      

In [2]: a=np.zeros((56,256,256))                                                

In [3]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                   
3.68 ms ± 8.28 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]: a=np.zeros((56,256,256))                                                

In [5]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                   
251 ms ± 1.16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
When I continue this procedure, the timings stay around the 251ms mark and don't go back to the single-digit numbers (which are actually the ones I would expect ... 200+ ms for this task appears extremely slow)

Are there two fundamentally different code paths in `ascontinguousarray()`? Or is this some bad interaction with the memory manager?

NOTE: the repeated definition of `a` in line 4 is essential; without this statement, performance doesn't degrade.

**Comment by eric-wieser** [comment]
Note that `transpose` is basically free, so the actual performance variation you're seeing is in `ascontiguousarray`

**Comment by eric-wieser** [comment]
On windows with the same numpy version I get no issue:
```
In [89]: a=np.zeros((56,256,256))

In [90]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))
33.2 ms ± 1.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [91]: a=np.zeros((56,256,256))

In [92]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))
32.5 ms ± 772 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
So it looks like you're hitting a memory manager issue. Perhaps one array spanned multiple pages, while the other did not? You could  look at `hex(a.ctypes.data)` to try and work that out.

**Comment by mreineck** [comment]
OK, I get 
```
0x7f2ba75da010
0x7f2ba91da010
```
for the first array, and
```
0x24e77d0
0x40e77d0
```
for the second one. I'm pretty sure that both span multiple memory pages, even if huge pages are active, because the array is almost 30MB.
I think it's quite surprising that the second array ends up at a completely different corner of address space, but on the other hand that shouldn't make any difference.,,

**Comment by mreineck** [comment]
It could also be a bad interaction between the starting addresses of `a` and the temporary output array. The first stride of `a` is nasty (this is deliberate, because I originally planned to analyze whether `ascontiguousarray` does something clever when presented with "difficult" strides), and it might be that unlucky placement of the output array leads to even more cache thrashing.

 Do you happen to know how `ascontiguousarray` works internally? Does it just proceed linearly through the output array, or linearly through the input array, or does it apply optimizations like blocking etc. when that is beneficial?

My main motivation for all this is speeding up the Fourier transforms in `scipy.fft` in the presence of critical strides...

**Comment by seberg** [comment]
I can reproduce the wide fluctuations. And I can disable hugepages and it makes no difference. Further, I cannot see actual alignment changes.

I would be very interested if you can figure this out, because my guess is, that it is the same effect that tends to mess up half of my benchmarking attempts with wide unrelated fluctuations...

**Comment by charris** [comment]
I don't see this, it ranges 22-29 ms on my hardware. Fedora 32, NumPy 1.20.0.dev0+470c783, Intel i5.

**Comment by seberg** [comment]
@mreineck sorry about your actual question: NumPy unfortunately has *no* blocking iteration. Thus it will try to find the best iteration order, which is probably not a very good guess in general. I think this hsould give you an idea:
```
it = np.nditer([a.transpose(1, 2, 0).copy(), a.transpose(1, 2, 0)])
it.itviews[0].strides
it.itviews[1].strides
```
(it seems those should be iterated in C-order.)

**Comment by charris** [comment]
Upgraded kernel to 5.4.15, now runs consistently around 24 ms right after reboot. Could be memory gets crowded after the machine is up most of the day.

**Comment by seberg** [comment]
@charris, I do not remember nearly as many irregular timings before I switchted to me newest computer, so I am tempted to think that it might have something to do with very up-to-date hardware. (I see about a factor of 10x difference on Debian with a 5.6 kernel and i7-8650U CPU – I disabled turboboost)

On the notion of a blocked iterator. I used to think this is hard, and should be something someone with experience in the field should contribute and we can review.  But... I thought it was super difficult, when I think I may have blatantly overestimated the cost of at least *improving* the situation a lot.

1. Our iterator already *combines* axes, splitting them up and rearranging order should be super difficult.
2. It probably mainly matters for out-of-cache arrays, so I assume testing whether this kind of rearranging makes sense produces very little overhead. And when we actually do it, the overheads do not matter.

We may have a bit of an annoying case where we always use strided-loops (also for filling buffers), and the best block sizes may be so small that we see more overheads (in the outer iteration). OTOH, I expect that this all does not matter, in the sense that it would still improve things a lot, and there is just more room for further improvements.

**Comment by charris** [comment]
@seberg This is with your self compiled NumPy? What are your CFLAGS?

**Comment by mreineck** [comment]
> I do not remember nearly as many irregular timings before I switchted to me newest computer, so I am tempted to think that it might have something to do with very up-to-date hardware.

FWIW, I'm seeing this on a 5-year-old laptop with a Core i5-5300U CPU. Software is pretty up-to-dat, though (Debian testing).

I know that writing an all-round efficient and general transposition code is a really hard problem. Based on my spare time (don't have too much at the moment unfortunately) I'll try to come up with something that performs OK in most cases; if I want to improve my FFTs, there is no way around this.

Still, it would be great to understand the origin of the problem above. I suspect that it only occurs in the presence of critical strides; that at least should be easy to verify. After that I'll see if I can reproduce this with a mockup in C or C++.

**Comment by charris** [comment]
My CFLAGS are
```
echo $CFLAGS
-Wall -Wstrict-prototypes -O2 -pipe -fomit-frame-pointer -fno-strict-aliasing -Wmaybe-uninitialized -Wdeprecated-declarations -march=native
```

**Comment by mhvk** [comment]
I do see the difference, but intriguingly can get back to "fast" behaviour by doing `del a` before redefining `a`.
```
In [2]: a=np.zeros((56,256,256))                                                

In [3]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                   
2.48 ms ± 28.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]: a=np.zeros((56,256,256))                                                

In [5]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                   
10.5 ms ± 52.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [6]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                   
10.6 ms ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: a=np.zeros((56,256,256))                                                

In [8]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                   
10.5 ms ± 61.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [9]: del a                                                                   

In [10]: a=np.zeros((56,256,256))                                               

In [11]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                  
2.5 ms ± 17.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [12]: a=np.zeros((56,256,256))                                               

In [13]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                  
10.5 ms ± 114 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [14]: a=np.zeros((56,256,256))                                               

In [15]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                  
10.6 ms ± 37.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [16]: del a                                                                  

In [17]: a=np.zeros((56,256,256))                                               

In [18]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                  
2.5 ms ± 25.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by mhvk** [comment]
p.s. It is not `ipython` specific:
```
mhvk@weasel:~$ python3
Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import timeit
>>> a=np.zeros((56,256,256))
>>> timeit.timeit("np.ascontiguousarray(np.transpose(a,(1,2,0)))", number=100,globals=globals())
0.2941491529927589
>>> timeit.timeit("np.ascontiguousarray(np.transpose(a,(1,2,0)))", number=100,globals=globals())
0.27124356100102887
>>> a=np.zeros((56,256,256))
>>> timeit.timeit("np.ascontiguousarray(np.transpose(a,(1,2,0)))", number=100,globals=globals())
1.1942435969976941
>>> del a
>>> a=np.zeros((56,256,256))
>>> timeit.timeit("np.ascontiguousarray(np.transpose(a,(1,2,0)))", number=100,globals=globals())
0.39235656399978325
>>> np.__version__
'1.17.4'
```

**Comment by charris** [comment]
> I know that writing an all-round efficient and general transposition code is a really hard problem.

I once implemented it as a sort just for the improved memory access :) I don't recall if it worked.

**Comment by mhvk** [comment]
p.s. On transposition, I recall there being a nice paper by the people who later implemented it for FFTW. Probably just one of the references at https://en.wikipedia.org/wiki/In-place_matrix_transposition

**Comment by charris** [comment]
@mhvk Interesting. I once implemented bit reversal for FFT's using swaps and cycles.

**Comment by seberg** [comment]
@charris it was with the default flags of `runtests.py` (but I think the same with the debian shipped NumPy 1.18.1). I have turboboost currently disabled, and used cpu-pinning, madvise was both always on, or `madvise` (and setting it off in NumPy). I do not think any of these settings matter.

I can reproduce the `del` behaviour Marten notes. 

This case is extreme, but I am sure I have seen other less extreme similar cases (which also toggled by doing unrelated code changes). And I assume it is the same effect (some cache thrashing?) except here @mreineck  chose strides which make the issue magnitudes larger.

Maybe @r-devulap has an idea of what may be at the core of it? It would be nice to know why it happens. Whether or not we can do something about is a different issue...

**Comment by charris** [comment]
> I can reproduce the del behaviour Marten notes.

I get the opposite behavior, times go from 23 to 30 ms. But this does suggest that memory management may be playing a role. I'm running Python 3.8 in case that matters.

**Comment by seberg** [comment]
I suppose it is possible that it has to do with the compiler/GCC version as well (I am on 9.x, Chuck is on 10.x)? I did check alignments, and in both cases it seemed like 16 byte alignments.

**Comment by charris** [comment]
Memory management would probably depend on glibc, so glibc 2.31 here.

**Comment by mhvk** [comment]
I checked a bit further and one thing that possibly differs from @mreineck is that if on his line 4 I define a new array, `b`, and then test on `b`, it also is slow.

And the deleting trick does not always work....

It does not seem directly related to where in memory the array is: the first and last one below are in the same place but have different timings:
```
In [10]: a=np.zeros((56,256,256))                                               

In [11]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                  
8.94 ms ± 16.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [12]: print(f'{hex(a.ctypes.data)}\n{hex(a.ctypes.data + a.nbytes)}')        
0x43108b0
0x5f108b0

In [13]: a=np.zeros((56,256,256))                                               

In [14]: print(f'{hex(a.ctypes.data)}\n{hex(a.ctypes.data + a.nbytes)}')        
0x5f108c0
0x7b108c0

In [15]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                  
8.98 ms ± 61.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [16]: del a                                                                  

In [17]: a=np.zeros((56,256,256))                                               

In [18]: print(f'{hex(a.ctypes.data)}\n{hex(a.ctypes.data + a.nbytes)}')        
0x43108b0
0x5f108b0

In [19]: %timeit np.ascontiguousarray(np.transpose(a,(1,2,0)))                  
2.32 ms ± 1.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by mhvk** [comment]
p.s. `np.copy` is a factor of 2 faster, but also has similar differences. Bizarre.

**Comment by charris** [comment]
@mhvk Address mapping can do funny things. I don't think you can make a direct connection from virtual addresses to physical memory.

**Comment by r-devulap** [comment]
The deleting trick didn't work for me either. Curious to know why this behavior.

**Comment by r-devulap** [comment]
I couldn't reproduce this performance difference for `np.ones`. Is there something special about how memory is allocated for `np.zeros`? 

```
import numpy as np                                                              
import timeit                                                                   
import psutil                                                                   
print("available mem in bytes before = ", psutil.virtual_memory()._asdict()['available'])
a=np.zeros((56,256,256))                                                        
print("available mem in bytes after = ", psutil.virtual_memory()._asdict()['available'])
```

produced: 

```
available mem in bytes before =  28737015808
available mem in bytes after =  28737015808
```

No memory was allocated! If you use `np.ones` instead of `np.zeros` about 27Mb was allocated, which is what you would expect: 

```
available mem in bytes before =  28735860736
available mem in bytes after =  28706693120
```

**Comment by seberg** [comment]
Ohhh, yes... zeros uses `calloc`, so that explains how the first copy can be super fast (for me it is only 20%  slower than the contiguous copy, even though it is out of memory, and numpy is not smart!).

So, I guess the mystery is just why the kernel knows that this is uninitialized `calloc` memory only for the first round, but after that forgets...?

**Comment by r-devulap** [comment]
I suspect its the `timeit`. The first you use `timeit`, memory usage goes up. See how available memory changes for this code (sorry for pasting some horribly written code): 
```
import numpy as np                                                              
import timeit                                                                   
import psutil                                                                   
print("available mem in bytes before = ", psutil.virtual_memory()._asdict()['available'])
a=np.zeros((56,256,256))                                                        
print("available mem in bytes after = ", psutil.virtual_memory()._asdict()['available'])
print(timeit.timeit("np.ascontiguousarray(np.transpose(a,(1,2,0)))",number=100,globals=globals()))
print("available mem in bytes = ", psutil.virtual_memory()._asdict()['available'])
b=np.zeros((56,256,256))                                                        
print("available mem in bytes = ", psutil.virtual_memory()._asdict()['available'])
print(timeit.timeit("np.ascontiguousarray(np.transpose(b,(1,2,0)))",number=100,globals=globals()))
print("available mem in bytes = ", psutil.virtual_memory()._asdict()['available'])

```

```
available mem in bytes before =  28751581184
available mem in bytes after =  28751581184
0.23380761500447989
available mem in bytes =  28692770816
available mem in bytes =  28692770816
1.7012474024668336
available mem in bytes =  28692873216
```

**Comment by mhvk** [comment]
Wow, nice sleuthing! (for the record, confirmed)

**Comment by r-devulap** [comment]
There are some neat tricks being playing behind the scenes for `np.zeros`! Unable to narrow it down though :( 
Compare the L1d cache misses via perf analysis for `np.zeros` and `np.ones`.



```
a=np.ones((56,256,256))
print(timeit.timeit("np.ascontiguousarray(np.transpose(a,(1,2,0)))",number=1000,globals=globals()))
```

    15,206,752,428      instructions              #    0.26  insn per cycle           (46.11%)
     1,048,826,573      branches                  #   59.374 M/sec                    (46.12%)
         4,803,953      branch-misses             #    0.46% of all branches          (46.14%)
     4,831,278,031      L1-dcache-loads           #  273.498 M/sec                    (46.16%)
     4,189,345,485      L1-dcache-load-misses     #   86.71% of all L1-dcache hits    (46.18%)

For: 

```
a=np.zeros((56,256,256))
print(timeit.timeit("np.ascontiguousarray(np.transpose(a,(1,2,0)))",number=1000,globals=globals()))
```

    15,322,093,740      instructions              #    2.01  insn per cycle           (45.77%)                                                                                                
     1,051,510,833      branches                  #  453.164 M/sec                    (45.94%)                                                                                                
         4,258,015      branch-misses             #    0.40% of all branches          (46.12%)                                                                                                
     4,832,977,335      L1-dcache-loads           # 2082.844 M/sec                    (46.29%)                                                                                                
       483,420,244      L1-dcache-load-misses     #   10.00% of all L1-dcache hits    (46.46%) 

Both have roughly the same numbers except for L1d cache load misses. For an array way bigger than the L1d cache, `np.zeros `has just 10% cache misses compared to 87% misses for `np.ones`, which is what you would expect.

**Comment by seberg** [comment]
@r-devulap out of general curiosity, how do you generate those statistics?

**Comment by r-devulap** [comment]
Using perf on linux: `perf stat -ddd taskset 0x01 python yourscript.py` (I use the taskset so that the python script doesnt jump around CPU's).

**Comment by seberg** [comment]
Thanks, I use `perf`, but never used `perf stat`!

**Comment by r-devulap** [comment]
To me it looks like an effect of copy on write optimization in the kernel https://stackoverflow.com/a/6005003/1932716. Unfortunately I dont know the details of the kernel implementation to explain the details ..

**Comment by mreineck** [comment]
@r-devulap Thank you for the beautiful analysis! I think that copy-on-write is the fundamental reason for the fast timings -  the kernel just presents the same page over and over instead of many different ones, since it knows that they are all identical.

I guess the lesson to take away from this is: never benchmark on arrays produced with `numpy.zeros()`; if possible, use `numpy.ones()` or (to be extra paranoid and avoid any chance of deduplication) random numbers.

From my point of view this can be closed, but I'll leave it open just in case that any `numpy/scipy` benchmarks need updating based on the new insights.

**Comment by mhvk** [comment]
Same. Always nice to learn something new!

**Comment by r-devulap** [comment]
Seems like this was already discussed in https://github.com/numpy/numpy/pull/11959 and added to the benchmarks README file.

**Comment by mreineck** [comment]
OK, so no more need to keep this open. Thanks again!
