### ISSUE TITLE
Can't pickle UFuncTypeError

### ISSUE THREAD

**Issue by crusaderky** [numpy/numpy#16490]
numpy 1.18.4-py38h8854b6b_0 (conda-forge)
Linux x64

```python
import pickle
import numpy


try:
    numpy.ones(1) * "foo"
except Exception as e:
    pickle.dumps(e)
```
Output:
```
Traceback (most recent call last):
  File "ufunctypeerror.py", line 6, in <module>
    numpy.ones(1) * "foo"
numpy.core._exceptions.UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ufunctypeerror.py", line 8, in <module>
    pickle.dumps(e)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
```

**Comment by eric-wieser** [comment]
The error seems to come from:

https://github.com/python/cpython/blob/df773f8c5454acebe08c31e7308597fa5a8bf5df/Modules/_pickle.c#L3581-L3650

I can't help feeling there's a bug in the error message formatting here by python itself.

**Comment by eric-wieser** [comment]
Ah, I see the problem now. It's `@_display_as_base` causing the issue, and the simplest repro is:
```python
import pickle
from numpy.core._exceptions import _UFuncNoLoopError
pickle.dumps(_UFuncNoLoopError)
```

**Comment by seberg** [comment]
Hmmm, do we have to set the qualname as well to make printing nice?

**Comment by eric-wieser** [comment]
If we want to keep digging, we could attach a metaclass to override pickling...

**Comment by seberg** [comment]
I would prefer if we can avoid it if it has no big issues (not sure if we can set a pickler externally, but I guess that is also type based). Printing seems fine without qualname, since it seems to rely on `__name__`. I suppose there may be subtleties where the qualname shines through?

**Comment by eric-wieser** [comment]
It sounds like we want to drop both of these lines then:

https://github.com/numpy/numpy/blob/master/numpy/core/_exceptions.py#L29-L30

**Comment by seberg** [comment]
I tried, and it pickles if I just drop the qualname, so maybe its fine?

**Comment by eric-wieser** [comment]
The module setting is currently a no-op anyway, but in all the cases when it isn't it would also break pickling.

**Comment by skinny121** [comment]
This also happens with `MemoryError` arising from allocating an array.

**Comment by seberg** [comment]
Hmmm, is this urgent enough to be fixed for 1.19.3? It seems like this may be problematic in some schemes of multiprocessing!

**Comment by yjheo15** [comment]
Hello, I'd like to pick up this issue. Are there any PRs I should take a look at to know the current progress?
I am new to open-source and this will be my first contribution.

**Comment by seberg** [comment]
There is already a PR open for the simple fix. We were still a bit hesitant, because it makes the printing slightly worse so it may be nice to clean this up a bit more thoroughly, but that is not super straight forward.
