### ISSUE TITLE
numpy.expand_dims(): out of range axes is allowed when using tuple of axes, but single axis.

### ISSUE THREAD

**Issue by lyh458** [numpy/numpy#16509]
Out of range axes are forbidden and raise an AxisError in [numpy.expand_dims](https://numpy.org/devdocs/reference/generated/numpy.expand_dims.html?highlight=expand_dims#numpy-expand-dims), but it seems that the rule only works to single parameter of axis, but a tuple of axes.

### Reproducing code example:
```python
import numpy as np
x = np.array([1, 2])  # x.ndim = 1
y = np.expand_dims(x, axis=2)  # axis = 2 > x.ndim is not allowed, and will raise an AxisError
y = np.expand_dims(x, axis=(2, 0))  # axis = 2 > x.ndim but is allowed
```

### Error message:
> **AxisError                                 Traceback (most recent call last)**
<ipython-input-4-57b69002f697> in <module>
      1 import numpy as np
      2 x = np.array([1, 2])  # x.ndim = 1
----> 3 y = np.expand_dims(x, axis=2)  # axis = 2 > x.ndim is not allowed, and will raise an AxisError
      4 y = np.expand_dims(x, axis=(2, 0))  # axis = 2 > x.ndim but is allowed

> <__array_function__ internals> in expand_dims(*args, **kwargs)

> C:\Softwares\anaconda3\lib\site-packages\numpy\lib\shape_base.py in expand_dims(a, axis)
    595 
    596     out_ndim = len(axis) + a.ndim
--> 597     axis = normalize_axis_tuple(axis, out_ndim)
    598 
    599     shape_it = iter(a.shape)

> C:\Softwares\anaconda3\lib\site-packages\numpy\core\numeric.py in normalize_axis_tuple(axis, ndim, argname, allow_duplicate)
   1325             pass
   1326     # Going via an iterator directly is slower than via list comprehension.
-> 1327     axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
   1328     if not allow_duplicate and len(set(axis)) != len(axis):
   1329         if argname:

> C:\Softwares\anaconda3\lib\site-packages\numpy\core\numeric.py in <listcomp>(.0)
   1325             pass
   1326     # Going via an iterator directly is slower than via list comprehension.
-> 1327     axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
   1328     if not allow_duplicate and len(set(axis)) != len(axis):
   1329         if argname:

> **AxisError: axis 2 is out of bounds for array of dimension 2**

### Numpy/Python version information:
Python: 3.7.7
Numpy: 1.81.1

**Comment by eric-wieser** [comment]
The second call is legal because it reads "expand the array to 3d, where axes 0 and 1 are the inserted dimensions".

**Comment by nrobinson12** [comment]
This is really confusing to me. I'm wondering if anybody could please explain this in more detail for me.
How do tuples work in `expand_dims`?
In particular, how is the second call legal?
```python
x = np.array([1, 2]) # x.ndim = 1
y = np.expand_dims(x, axis=(2, 0)) # axis = 2 > x.ndim but is allowed
```

**Comment by seberg** [comment]
@nrobinson12 the `axis` refer to the axis number in the *output*. So here the `output_ndim = x.ndim + len(axis)` which is 3, so you are "expanding" 0 and 2 making the output shape: `(1, -1, 1)` with `-1` being filled in from `x`, so it becomes `(1, x.shape[0], 1)`.

By the way, this function is written in python, so e.g. in ipython you can write `np.expand_dims??` and look at the code!

**Comment by shubhamias12** [comment]
### Can anyone help out ?
 File "e:\Dissertation\coding\skin lession\MSRF-Net-main\MSRF-Net-main\train.py", line 82, in <module>
    edge_x_val  =  np.expand_dims(edge_x_val,axis=3)
  File "<__array_function__ internals>", line 5, in expand_dims
  File "C:\Users\sharm\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\shape_base.py", line 597, in expand_dims
    axis = normalize_axis_tuple(axis, out_ndim)
  File "C:\Users\sharm\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\numeric.py", line 1358, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "C:\Users\sharm\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\numeric.py", line 1358, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 3 is out of bounds for array of dimension 2

**Comment by mattip** [comment]
@shubhamias12 please open a new issue if you can't figure this out. You are trying to use the function in a way that has been deprecated. Please carefully read the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html?highlight=expand_dims).
