### ISSUE TITLE
numpy.linalg.inv returns wrong matrix?

### ISSUE THREAD

**Issue by maygloomoff** [numpy/numpy#16517]
I have the matrix to be inverted **XSmat**
**numpy.linalg.inv** returns matrix **numpy_output** that seemed correct
I cheked the output by multiplication:  **numpy_output * XSmat**
and got correct identity matrix! But ...

I repeated same operation in **MS Excel**, and got other inverced matrix, that seemed correct too ...
Multiplication on origin matrix got correct identity matrix! Inverced matrix **numpy_output** by multiplication on **XSmat** in MS Excel returns **NOT correct identity matrix**!

So, I have two the inverce matrix for one matrix, and both are correct (in its environment)!
Help me make a choice, please!

All data in attached file:
[compare matrix.xlsx](https://github.com/numpy/numpy/files/4741479/compare.matrix.xlsx)

P.S. I can imagine different algorithms for inverce matrix, but i can not write other algorithm for multiplication of matrix.
**

```python
import numpy as np
numpy_output= np.linalg.inv(Xmat)
```

### Numpy/Python version information:
1.18.1 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

**Comment by matthew-brett** [comment]
I'm not sure what's going on with these calculations but, on my system (macOS, default pip 1.18.5):

* xmat has a very small singular value 8e-10.
* I get a different Numpy inverse from you.
* My inverse, and your Excel's inverse, do invert xmat.
* Your Numpy inverse does not.
* My Numpy and your Excel agree on the multiplication of xmat and your Numpy's inverse.

In case anyone wants to replicate, and, like me, they do not have Excel:

```python
import numpy as np
import numpy.linalg as npl
import pandas as pd

sheet = pd.read_excel('compare.matrix.xlsx')
xmat = np.array(sheet.iloc[:7, :7]).astype(float)
xl_ixmat = np.array(sheet.iloc[8:15, :7]).astype(float)
np_ixmat = np.array(sheet.iloc[16:23, :7]).astype(float)
np_inved = np.array(sheet.iloc[8:15, 8:15]).astype(float)

# Numpy's inverse on my system.
ixmat = npl.inv(xmat)

# Singular values.
U, S, V = npl.svd(xmat)
print('Singular values\n', S)

def matclose(m1, m2):
    print(np.allclose(m1, m2, atol=5e-4))

print("Is my Numpy's inverse similar to yours?")
matclose(np_ixmat, ixmat)
print("Is my Numpy's inverse similar to Excel's?")
matclose(np_ixmat, xl_ixmat)
print("Does my Numpy's inverse invert xmat?")
matclose(ixmat @ xmat, np.eye(7))
print("Does your Numpy's inverse invert xmat?")
matclose(np_ixmat @ xmat, np.eye(7))
print("Does your Excel's inverse invert xmat?")
matclose(xl_ixmat @ xmat, np.eye(7))
print("Do I get a similar result to Excel for your Numpy inverse?")
matclose(np_ixmat @ xmat, np_inved)
```

**Comment by rossbar** [comment]
@maygloomoff are you still having this issue?

**Comment by maygloomoff** [comment]
No, thanks. I made certain conclusions for myself.3:26, 11 июля 2020 г., Ross Barnowski <notifications@github.com>:
@maygloomoff are you still having this issue?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
С уважением, Пыжьянов И.В.

**Comment by rossbar** [comment]
Okay, closing then - if the issue reappears or more specific information becomes available, please feel free to reopen!
