### ISSUE TITLE
1.19.0rc2: tests failure on armhf

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#16516]
Hello,
running tests for numpy 1.19.0rc2 fails on arch `armhf` with this failure (both for plain and debug flavors):

```
=================================== FAILURES ===================================
_______________________ Test_ARM_Features.test_features ________________________

self = <numpy.core.tests.test_cpu_features.Test_ARM_Features object at 0xb2a0b0e8>

    def test_features(self):
        self.load_flags()
        for gname, features in self.features_groups.items():
            test_features = [self.cpu_have(f) for f in features]
>           assert_equal(__cpu_features__.get(gname), all(test_features))
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: True
E            DESIRED: False

features   = ['NEON', 'HALF']
gname      = 'NEON_FP16'
self       = <numpy.core.tests.test_cpu_features.Test_ARM_Features object at 0xb2a0b0e8>
test_features = [False, True]

tmp/usr/lib/python3/dist-packages/numpy/core/tests/test_cpu_features.py:20: AssertionError
```

full build log [here](https://buildd.debian.org/status/fetch.php?pkg=numpy&arch=armhf&ver=1%3A1.19.0%7Erc2-2&stamp=1591497276&raw=0). It was not failing with 1.18.4

**Comment by charris** [comment]
> It was not failing with 1.18.4

The tests are new. We are trying to improve ARM feature detection @seiko2plus Thoughts?

> DeprecationWarning: the imp module is deprecated ...

Maybe need to update pytest to get rid of this.

**Comment by seiko2plus** [comment]
@charris, my bad :), Marvell MV78460 SoC/370/XP CPU the one that used in the build according to [Debian](https://db.debian.org/machines.cgi?host=hartmann) comes with CPU feature "HALF" without the support of NEON, while the current code was assuming the availability of NEON if HALF is available, which is wrong. Great that the testing unit was able to detect this issue.
