### ISSUE TITLE
Eigenvalues of A.T != eigenvalues of A

### ISSUE THREAD

**Issue by marchinidavide** [numpy/numpy#16512]
First of all, apologies if this topic was already discussed but after a brief research I didn't find any issue on this.
More a comment than an issue: I generate a random square matrix A and compute its eigenvalues and those of its transpose. In theory they should be equal (works if I sort them and compare with `np.allclose`), but if I compare the elements using builtint `set`, the output is False.

### Reproducing code example:

```python
import numpy as np
np.random.seed(42)
A = np.random.randn(10, 10)

# Use builtin set operator
evalA = set(np.linalg.eigvals(A))
evalAt = set(np.linalg.eigvals(A.T))
print(evalA == evalAt) # False

# Use np.allclose (but need to sort, can)
evalA = np.sort(np.linalg.eigvals(A))
evalAt = np.sort(np.linalg.eigvals(A.T))
print(np.allclose(evalA, evalAt)) # True
```

### Numpy/Python version information:

1.18.4 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:33:30)
[Clang 9.0.1 ]

**Comment by charris** [comment]
The eigenvalues won't be the same numerically because floating point computations are inexact and depend on the order in which they are performed. That is normal and is why tests of floating point results don't require exact equality.

**Comment by marchinidavide** [comment]
Fully agree! As I mentioned, it's more something to be aware of than a real issue. One can always write custom eigenvalues function as:

```python
def evals(a):
    return (np.sort(np.linalg.eigvals(a)) + np.sort(np.linalg.eigvals(a.T))) * 0.5
```
Also, `set` might not be the best structure to test equality of non sorted eigenvalues. Maybe `Counter` from `collections` module is a better fit.

**Comment by charris** [comment]
`set` will test exact equality.

**Comment by RRiva** [comment]
On top of that, the complex plane cannot be ordered, so the eigenvalues can be returned in any order.

**Comment by marchinidavide** [comment]
I agree. However the `np.sort` in `evals` function sorts by the real part first and the imaginary part second. It is enough to make `set` work on the specific example.
I'll close the issue.
