### ISSUE TITLE
BUG: f2py does not correctly report the f2py version in the docstrings of compiled extension modules

### ISSUE THREAD

**Issue by sturlamolden** [numpy/numpy#16525]
f2py tries to report the version of f2py in the docstring of the extension module. However, as the import of ```__svn_version__```  in ```numpy/numpy/f2py/__version__.py``` always fails, the f2py version reported in the docstrings always has the value of ```'2'```.

f2py should instead use a versioning mechanism that actually works, or at least include the NumPy version in the resported f2py version. This way it would be possible for projects like SciPy to query the version of f2py used for cmpilation (which might be different from the currently imported numpy) and correct for known bugs, such as the recently fixed issue with callbacks to Python not being threadsafe.

https://github.com/numpy/numpy/blob/581eab37b5d558ba9b8035f3fa82cfa617e70e26/numpy/f2py/__version__.py#L1-L8

Here is an example showing the problem:
```
>>> _cobyla.__doc__
"This module '_cobyla' is auto-generated with f2py (version:2).\nFunctions:\n  x,dinfo = minimize(calcfc,m,x,rhobeg,rhoend,dinfo,iprint=1,maxfun=100,calcfc_extra_args=())\n."
```

**Comment by eric-wieser** [comment]
`__f2py_version__` might be a better name, but agreed that a module-level constant is the way to go.

I think putting the version in the module `__doc__` would also be reasonable, just in case its useful in Sphinx docs generated from the module.

**Comment by sturlamolden** [comment]
I suggest ```__f2py_numpy_version__``` to avoid confusion as it is the version of NumPy with which f2py is associated. The version of f2py itself is probably unknown after it became a part of NumPy.
