### ISSUE TITLE
Typing support for dtypes

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#16545]
Per https://github.com/numpy/numpy/issues/7370#issuecomment-346126667, we could specify dtype as part of ndarray types (including type inference) by using NumPy's [scalar types](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.scalars.html), e.g., `np.ndarray[Any, np.float64]` or `np.ndarray[np.float64, Any]` (where `Any` indicates the shape).

Is this a good way to indicate dtypes? How would we handle dtypes that don't have a well specified scalar type? For example:
- `datetime64` and `timedelta64` do not have precision as part of the type
- [`np.void`](https://stackoverflow.com/questions/25247190/numpy-void-type-how-to-use-it) is used for all arbitrary structured dtypes, but doesn't indicate the field names or subtypes (side note: `np.struct` would be a much better name)
- string dtypes have their size as part of the type

One simple answer is to not worry about more detailed type information for now, and worry about more precise specification for scalar types later, when support in the typing module becomes available (e.g., for integer types or custom struct-like data structures like `TypedDict`).

**Comment by person142** [comment]
Updating this issue with my current plan to support dtypes; see also the discussion with @seberg in https://github.com/numpy/numpy-stubs/pull/48.

- Stubs have been moved into NumPy itself, and https://github.com/numpy/numpy/pull/15508 has been merged so we have dtype subclasses on master
- We write a mypy plugin using `get_dynamic_class_hook`:

  https://mypy.readthedocs.io/en/latest/extending_mypy.html#current-list-of-plugin-hooks

  to support creating the dynamic dtype classes at type-checking time
- We can then make ndarray generic over dtype, and not just the scalar hierarchy

**Comment by BvB93** [comment]
The PR for introducing dtype support is up: https://github.com/numpy/numpy/pull/17719.

**Comment by davetapley** [comment]
Sanity check, should something like `datetime64['us', UTC])` type check okay? 
I get `Expected no type arguments for class "datetime64"` 🤔
