### ISSUE TITLE
Indexing style leads to different output

### ISSUE THREAD

**Issue by Cevheriferd** [numpy/numpy#16552]
```python
import numpy as np
a = np.array( [[1,2,3] , [4,5,]] )
x = np.array( [1,0] )
y = np.array( [1,0] )
print(a[x][y])
print(a[x,y])
```

These two print statements give different outputs. In the numpy indexing document it states that the operations in the two print statements are the same.
Link of document: https://numpy.org/devdocs/user/basics.indexing.html

### Numpy/Python version information:

1.18.1 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

**Comment by seberg** [comment]
Can you say where the documentation is wrong or could be clarified.  The case you are showing is explained in this section: https://numpy.org/devdocs/user/basics.indexing.html#indexing-multi-dimensional-arrays and while I am sure it can be improved it seems correct on first glance.

**Comment by Cevheriferd** [comment]
> 
> 
> Can you say where the documentation is wrong or could be clarified. The case you are showing is explained in this section: https://numpy.org/devdocs/user/basics.indexing.html#indexing-multi-dimensional-arrays and while I am sure it can be improved it seems correct on first glance.

An example of the the case I presented can't be found at the indexing page. 
Specifically the developers imply the following:
![Annotation 2020-06-09 223950](https://user-images.githubusercontent.com/66697666/84197453-3cd16080-aaa2-11ea-915e-4c4d3a29f31f.jpg)
 
So using an index for array A like A[x][y] or  A[x,y] should lead to the same output according to the documentation. Which is the case for a 1 dimensional input. But the code I presented shows a different thing. The 2 print statements actually differin output!. 

So one of the two things is the case:
The documentation is wrong about the equality of the 2 indexing possibilities. Or there is a structural bug in which leads to 2 different outputs. I hope I clarified the issue.

**Comment by mattip** [comment]
The documentation you refer to is under the heading `Single element indexing`. You are not using a single element,.

**Comment by Cevheriferd** [comment]
> 
> 
> The documentation you refer to is under the heading `Single element indexing`. You are not using a single element,.

That doesn't change anything, even in the paragraph of multidimensional array indexing this issue/phenomenon doesn't appear.

**Comment by rossbar** [comment]
There is an important distinction between two different *kinds* of indexing behavior that are both accessed with the `[]` syntax: "basic" and "advanced" indexing. The case you originally reference from the documentation (`x[0][2] == x[0, 2]`) holds for *basic* indexing, but in your case, `x` and `y` are arrays, which triggers *advanced* indexing, which has different behavior. Note that the indexing article in the [reference guide](https://numpy.org/devdocs/reference/arrays.indexing.html) is a bit more clear on this distinction than the one in the user guide linked above. Hopefully this helps - if you have ideas for improvements to the various documentation pages on indexing (see e.g. #14038), please feel free to propose changes!

**Comment by rossbar** [comment]
I'm going to go ahead and close this for now - any ideas related to specific improvements to the indexing documentation are more than welcome!
