### ISSUE TITLE
BUG: NumPy build failure with Python nightly

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#16553]
Over on sphinx-gallery we test against Python nightly, and lately we [have been getting](https://travis-ci.org/github/sphinx-gallery/sphinx-gallery/jobs/696574346#L1645) this failure:
```
gcc: numpy/core/src/multiarray/scalarapi.c
    numpy/core/src/multiarray/scalarapi.c: In function ‘PyArray_Scalar’:
    numpy/core/src/multiarray/scalarapi.c:798:27: error: lvalue required as left operand of assignment
                 Py_SIZE(vobj) = itemsize;
```
Discussion [over in PyCurl](https://github.com/pycurl/pycurl/pull/636) currently leads to the suggested fix:
```
#if PY_VERSION_HEX < 0x030900a4
    #define Py_SET_TYPE(obj, new_type) do { Py_TYPE(obj) = (new_type); } while (0)
#endif
```
`git grep Py_SIZE` suggests there are only a few places a fix is needed:
```
numpy/core/src/multiarray/scalarapi.c:            Py_SIZE(vobj) = itemsize;
numpy/core/src/multiarray/scalartypes.c.src:        Py_SIZE(self) * Py_TYPE(self)->tp_itemsize;
numpy/core/src/multiarray/scalartypes.c.src:        npy_free_cache(v->obval, Py_SIZE(v));
numpy/core/src/multiarray/scalartypes.c.src:        Py_SIZE((PyVoidScalarObject *)ret) = (int) memu;
```

**Comment by charris** [comment]
I believe these have been fixed in NumPy master. You might want to test against the NumPy nightlies (actually built weekly on Sunday).

**Comment by larsoner** [comment]
Ahh okay, great!

**Comment by charris** [comment]
Also fixed in upcoming 1.19.0, should be out in a week or two.

**Comment by charris** [comment]
See #16417.

**Comment by larsoner** [comment]
Argh, sorry I should have searched existing issues better. I can confirm things work fine building with `master` source zipball with latest Python nightly on Travis for Sphinx-gallery
