### ISSUE TITLE
Feature: dedup (remove consecutive duplicate elements)

### ISSUE THREAD

**Issue by Feelx234** [numpy/numpy#16559]
Hello numpy community,

I would like to know whether there is interest in a **dedup** function. Dedup removes *consecutive duplicate values* from a vector. This is in contrast with a generic unique function which keeps only one version of each unique element across the vector:
```python
>>> a = [1, 1, 2, 2, 2, 3, 2, 4]
>>> dedup(a)
array([1, 2, 3, 2, 4])
>>> np.unique(a)
array([1, 2, 3, 4])
```

I am aware that dedup only makes sense on 1D-vectors as otherwise the notion of consecutive elements seems less well defined. Maybe that would position it in the numpy.lib.arraysetops.

### Examples of dedup
Out in the wild, a dedup function exists in the rust standard library for vectors [dedup](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.dedup), the cpp standard library also has a dedup function that is called [unique](https://en.cppreference.com/w/cpp/algorithm/unique). There is also a [stackoverflow question](https://stackoverflow.com/questions/37839928/remove-following-duplicates-in-a-numpy-array) asking how to achieve such a feature in numpy.

### Motivation
The trivial motivation is, that it exists out in the wild, so it is probably being used by different developers. 
My personal motivation is, that I saw a version for at most two consecutive elements in the numpy/lib/arraysetops.py like so:
```python
mask = aux[1:] == aux[:-1]
int1d = aux[:-1][mask]
```
Which makes sense for the `return_indices=True` case but feels very inefficient otherwise.
This is where a **dedup** method would come in handy. I would expect it to be way faster even in the simple case of at most two consecutive elements. It should also be much faster than using numpy.unique function.

### How to implement
Unfortunately, I am not (yet) a very experienced fortran or cpp developer. But I guess wrapping and exposing e.g. the cpp unique function should be a trivial thing to do for numerical numpy arrays. Not sure how this would work for object arrays though.

### Is there a need for it?
Before I dive into implementing such a functionality, I'd like to know whether **dedup**  is a useful thing to be had (from the numpy community point of view). So feel free to comment!

Thanks for your feedback!

PS: If you have a better name, go ahead and suggest that as well

**Comment by eric-wieser** [comment]
A nasty hack, but you can get this today with:
```python
class CantSortThis(np.ndarray):
    def sort(self):
        pass
```
```python
>>> np.unique(np.array([1, 1, 2, 2, 2, 3, 2, 4]).view(CantSortThis)).view(np.ndarray)
array([1, 2, 3, 2, 4])
```
If you were to implement this, I'd probably recommend changing the implementation of `unique` to be roughly `dedup(np.sort(arr))`. Most of the logic you need is already there, it would just need extracting to a new function.

Let's see what other maintainers thing about the usefulness of this function before going ahead with implementing.

**Comment by rossbar** [comment]
I took a crack at how you could get this behavior and came up with: `np.r_[ a[np.nonzero(np.diff(a))[0]], a[-1] ]` or, without the `np.r_`: `np.concatenate((a[np.nonzero(np.diff(a))[0], [a[-1]]))`

**Comment by turtleizzy** [comment]
A small change to return the index of the first occurrence if necessary.
```
def dedup(a, return_index=False):
    dupIdx = np.r_[[0], np.nonzero(np.diff(a))[0] + 1]
    if return_index:
        return a[dupIdx], dupIdx
    else:
        return a[dupIdx]

a = np.array([1, 1, 1, 2, 2, 1, 1, 2, 3, 3, 3, 4])
a_dedup, idx = dedup(a, True)
# a_dedup = array([1, 2, 1, 2, 3, 4])
# idx = array([ 0,  3,  5,  7,  8, 11])
```

**Comment by WarrenWeckesser** [comment]
There does not appear to be interest in adding this to numpy.  Close?

**Comment by WarrenWeckesser** [comment]
OK, closing.  Anyone interested in seeing `dedup` in NumPy can continue the conversation here.  We can reopen the request if it turns out there is interest and sufficiently compelling use-cases.

**Comment by fzimmermann89** [comment]
This functionality exists in pytorch as https://pytorch.org/docs/stable/generated/torch.unique_consecutive.html

I came here looking for a similiar function in numpy to avoid the pytorch dependency.
