### ISSUE TITLE
Import error inside 3ds Max Python 2.7 environment

### ISSUE THREAD

**Issue by hjlld** [numpy/numpy#16557]
I use numpy 1.16.6 inside Autodesk 3DS Max 2021 with python 2.7. I've got error below and according it i'm here to create a new issue.

<details>
  <summary>IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
</summary>
<pre><code>

Traceback (most recent call last):
  File "<string>", line 8, in <find>
  File "E:\Program Files\Autodesk\3ds Max 2021\python\lib\site-packages\matplotlib\__init__.py", line 129, in <<module>>
  File "<string>", line 8, in <find>
  File "E:\Program Files\Autodesk\3ds Max 2021\python\lib\site-packages\matplotlib\cbook\__init__.py", line 39, in <<module>>
  File "<string>", line 8, in <find>
  File "E:\Program Files\Autodesk\3ds Max 2021\python\lib\site-packages\numpy\__init__.py", line 142, in <<module>>
  File "<string>", line 8, in <find>
  File "E:\Program Files\Autodesk\3ds Max 2021\python\lib\site-packages\numpy\core\__init__.py", line 71, in <<module>>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using E:\Program Files\Autodesk\3ds Max 2021\3dsmax.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
</code></pre>

</details>

Run it again will popup another import error:

`ImportError: cannot import name _distributor_init`

The same code run successfully inside an independent Python 3.7 environment.

All packages' installations are successful.

     - how you installed Python:  python 2.7 as a compoent of Autodesk 3DS Max 2021 
     - how you installed numpy:  `.\3dsmaxpy.exe -m pip install numpy`
     - your operating system: Windows 10 Home Edition 1019 18363.836
     - whether or not you have multiple versions of Python installed: I have an independent Python 3.7 installed in default path.

**Comment by mattip** [comment]
We don't really support 2.7 anymore. You may want to 
- check what `PYD` files exist in `E:\Program Files\Autodesk\3ds Max 2021\python\lib\site-packages\numpy\core`, my python2.7 has `_multiarray_umath.pyd`
- make sure that `E:\Program Files\Autodesk\3ds Max 2021\python\lib\site-packages\numpy\.libs` exists, contains a DLL
- try to print `os.environ['PATH'] at the point of failure and make sure the `.libs` directory is in the PATH at that point.

**Comment by hjlld** [comment]
Thanks a lot. I update it to Python 3.7 inside 3Ds Max 2021, now it works.
