### ISSUE TITLE
No module named 'numpy'

### ISSUE THREAD

**Issue by CarolineCauffman** [numpy/numpy#16560]
Python 3.8.3 (32bit) and IDLE worked perfectly under windows 10 until I tried to import numpy. This resulted in an error message: modulenotfound:no module named 'numpy'. I removed Python entirely, installed it again, installed numpy via cmd and pip and received the message that numpy was installed. Then I opened IDLE and tried again to import numpy. I got the same error message as before: modulenotfound:no module named 'numpy'. Is there any solution for this problem?
![Knipsel](https://user-images.githubusercontent.com/66596674/84280713-f4648200-ab37-11ea-8696-e6e42880ea2a.PNG)

**Comment by anirudh2290** [comment]
What command did you run for installing numpy? (Did you try if `python -m pip install numpy` helps) I think the installation doc probably covers this, but It happens a lot that the python version that numpy is installed for is different from the python version for which you are importing numpy.

**Comment by CarolineCauffman** [comment]
?Thanks. It is solved.

________________________________
Van: Anirudh Subramanian <notifications@github.com>
Verzonden: vrijdag 12 juni 2020 2:11
Aan: numpy/numpy
CC: Cauffman, Caroline (PR); Author
Onderwerp: Re: [numpy/numpy] No module named 'numpy' (#16560)


What command did you run for installing numpy? (Did you try if python -m pip install numpy helps) I think the installation doc probably covers this, but It happens a lot that the python version that numpy is installed for is different from the python version for which you are importing numpy.

-
