### ISSUE TITLE
DISCUSS: Consider whether it should be `Dtypelike` or `DTypeLike`

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#16562]
The stubs currently add `DtypeLike` as "anything that can be coerced by `np.dtype`.  However, with new user dtypes, the dtype classes will be the important building-blocks probably.  For these I currently use the spelling `DType` (capital T).

This does not need to affect the stubs, however, it may be that the stubs basically end up using the DType class as the category (i.e. byte order and string length rarely make a difference probably).  In this case keeping the spelling between the `DType` class and the `DTypeLike` synched up, may make additional sense.  Otherwise, being intentionally different may be an argument.

I guess I use the `DType` capitalization as a short form of camel-case `DataType`, but I am open to reconsider that as well.

**Comment by person142** [comment]
> however, it may be that the stubs basically end up using the DType class as the category

Have a branch where I'm working on making that happen, so `DTypeLike` seems like the right call to me too.

**Comment by BvB93** [comment]
Just a reminder that we should decide on `DTypeLike` or `DtypeLike` before 1.20.
All reactions thus far have been positive to the proposed name change, so I'd say lets just switch to `DTypeLike`.

**Comment by BvB93** [comment]
Alright, the pull request is up: https://github.com/numpy/numpy/pull/17699.
