### ISSUE TITLE
Needlessly iterates over RHS array in object array slice assignment

### ISSUE THREAD

**Issue by inducer** [numpy/numpy#16564]
Consider the following code:

```python
class FakeArray:
    nopes = 0

    def __len__(self):
        FakeArray.nopes += 1
        return 10

    def __getitem__(self, idx):
        FakeArray.nopes += 1
        if idx > 10:
            raise IndexError()


import numpy as np
a = np.zeros(1, dtype=np.object)
a[:] = [FakeArray()]

assert FakeArray.nopes == 0, FakeArray.nopes
```

Since the shape of the LHS of the assignment is known, I would not expect numpy to go poking around in the internal structure of the RHS. Yet, it does, as illustrated by this code. To be specific, I get `nopes == 14` when I run the above code.

This matters to me because I would like to use object arrays of arrays that live on the GPU. Those can easily have millions of entries, and so this iteration seemingly needlessly introduces a very high cost, only to end up at the O(1) thing I feel like I asked for: Take the `FakeArray`, and stick it into a single-entry object array.

### Numpy/Python version information:

```
Numpy: 1.18.5
Python: 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0]
```

**Comment by seberg** [comment]
Actually, gh-16200 already only calls `len()` and never `__getitem__` here, so seems I already kind-of fixed it.  But I am not sure I would call it a feature at this time, as opposed to a beneficial implementation detail.

In any case, seems I could not think of any way it would create an issue when limiting the maximum number of dimensions here to begin with, and we (or pandas/astropy/scipy) do not have tests tripping with the change. (With the exception of a single array-like input, which supports reverse broadcasting potentially.)

**Comment by rossbar** [comment]
It seems that this may be "fixed" as a side-effect of the dtype overhaul? I'll leave it open for now, but if update to array coercion sufficiently handles the original problem and there's no further, general discussion then it might make sense to close.

**Comment by seberg** [comment]
Yes, I think we can consider this fixed.
