### ISSUE TITLE
DOC: Update documentation on minimum gcc version

### ISSUE THREAD

**Issue by youngquan** [numpy/numpy#16576]
### Reproducing code example:

```python
pip wheel numpy
```

### Error message:

```
In file included from numpy/core/src/umath/loops.c.src:50:0:
  numpy/core/src/umath/loops.c.src: In function ‘LONG_right_shift’:
  numpy/core/src/umath/loops.c.src:694:47: internal compiler error: in expand_shift_1, at expmed.c:2349
       BINARY_LOOP_FAST(@type@, @type@, *out = npy_rshift@c@(in1, in2));
                                                 ^
  numpy/core/src/umath/fast_loop_macros.h:180:9: note: in definition of macro ‘BASE_BINARY_LOOP_S_INP’
           op; \
           ^
  numpy/core/src/umath/loops.c.src:694:5: note: in expansion of macro ‘BINARY_LOOP_FAST’
       BINARY_LOOP_FAST(@type@, @type@, *out = npy_rshift@c@(in1, in2));
       ^
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
```

### Numpy/Python version information:
numpy 1.18.5
Python 3.7.7
gcc 5.4.0

**Comment by mattip** [comment]
Please update the gcc you are using. Search for yum and devtoolset-9 for instructions if you are on CentOS/Redhat.

**Comment by youngquan** [comment]
I updated the gcc, and it worked. However, the instructions from the offcial numpy docs doesn't mention a higher gcc version to build numpy from source:
> GCC 4.x (and later) compilers are recommended. 

Maybe, the content of page  [Building from source](https://numpy.org/doc/stable/user/building.html) should change.

**Comment by mattip** [comment]
We don't get much feedback on those instructions, so a PR to improve them would be welcome.

**Comment by ObliviousParadigm** [comment]
Hey @seberg! I'm a newbie to Open Source contributions. Can I work on this?

**Comment by ObliviousParadigm** [comment]
take

**Comment by jtprof** [comment]
> I updated the gcc, and it worked. However, the instructions from the offcial numpy docs doesn't mention a higher gcc version to build numpy from source:
> 
> > GCC 4.x (and later) compilers are recommended.
> 
> Maybe, the content of page [Building from source](https://numpy.org/doc/stable/user/building.html) should be modified.

Hi Yang,
What exactly gcc version have you used successfully? How did you update it (yum, apt, source, etc)? Also, what Linux distribution do you have?

Thank you in advance.

**Comment by youngquan** [comment]
I pulled the offical python image from docker hub to build numpy, the gcc version in the image is:
```bash
# gcc --version
gcc (Debian 8.3.0-6) 8.3.0
```
The Linux distribution of my server is:
```bash
# lsb_release 
No LSB modules are available.
root@master:~# lsb_release -da
No LSB modules are available.
Distributor ID: Kylin
Description:    Kylin 4.0.2
Release:        4.0.2
Codename:       juniper
```
May you can get more information from [here](https://www.ubuntukylin.com/) or [here](http://www.kylinos.cn/).
