### ISSUE TITLE
Make the first `np.generic` argument positional-only?

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#16577]
Currently the first argument of `np.generic` constructors  (_e.g._ `np.float64.__init__()`; [ref](https://github.com/numpy/numpy/blob/02d66ecd80a1851c3b206f4d778687b38c9d2c36/numpy/__init__.pyi#L456-L457)) can be supplied as either positional or keyword argument. However supplying a keyword will simply result in the passed value being ignored, the respective generic subclass thus falling back to a default value (see Example). This could lead to some, potentially, dangerous situations and I feel such usage should be actively discouraged.

Therefore I'd to propose making the first argument of generic constructors positional-only. 
This can be accomplished by prepending it with `__` (see [PEP 484](https://www.python.org/dev/peps/pep-0484/#positional-only-arguments)).

Any thoughts?

Example
---------
``` python
>>> import numpy as np

>>> np.float64()  # Returns a default value
0.0
>>> np.float64(100)
100.0
>>> np.float64(x=100)
0.0 
>>> np.float64(a=1, b=2, c=3, d=4)  # An arbitrary amount of kwargs can be provided
0.0  
```

Proposed new signature
-------------------------
``` python
class np.float64(floating):
    def __init__(self, __value: SupportsFloat = ...) -> None:
        ...
```

**Comment by eric-wieser** [comment]
> However supplying a keyword will simply result in the passed value being ignored,

Are you sure about this? I thought it now raises TypeError.

**Comment by BvB93** [comment]
> Are you sure about this? I thought it now raises TypeError.

I'm getting the same result on both `1.18.4` and the master branch.

**Comment by person142** [comment]
👍 seems like the right call to me.

(Aside: we could also special-case the "no args" case and use `Literal`s to get the return value right...)

**Comment by BvB93** [comment]
Alright, I've created a pull request addressing the issue at https://github.com/numpy/numpy/pull/16583.

**Comment by eric-wieser** [comment]
I was pretty sure I fixed this in #15446...

**Comment by BvB93** [comment]
So this is a bit odd: If I supply these bogus keyword arguments to any generic it does indeed raise a `TypeError`... Except for `np.float64`, which seems to be doing its own thing.

``` python
>>> import numpy as np
>>> np.__version__
'1.20.0.dev0+bcd4827'

>>> np.float64(a=1, b=2, c=3)
0.0

>>> np.float32(a=1, b=2, c=3)
TypeError: function takes at most 1 keyword argument (3 given)

>>> np.int64(a=1, b=2, c=3)
TypeError: function takes at most 1 keyword argument (3 given)
```

**Comment by eric-wieser** [comment]
Does complex128 have the same issue?

**Comment by BvB93** [comment]
> Does complex128 have the same issue?

No, `complex128` works fine. 

In fact, it seems that `float64` is the sole ill-behaved exception here.
Every single `generic` displayed below raises `TypeError` when calling them as `cls(a=1, b=2, c=3)`
``` python
['bool_',
 'bytes_',
 'complex128',
 'complex256',
 'complex64',
 'datetime64',
 'float128',
 'float16',
 'float32',
 'int16',
 'int32',
 'int64',
 'int8',
 'longlong',
 'object_',
 'record',
 'str_',
 'timedelta64',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'ulonglong']
```

**Comment by eric-wieser** [comment]
What you've found is a python bug, not a numpy one:
```python
In [14]: class Foo(float):
    ...:     pass
    ...:

In [15]: Foo(1, what=2)
Out[15]: 1.0
```
