### ISSUE TITLE
DOC: unify the docs for np.transpose and ndarray.transpose 

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#16584]
We have two different bits of documentation for transpose, that essentially repeat the same information:

https://numpy.org/devdocs/reference/generated/numpy.transpose

https://numpy.org/devdocs/reference/generated/numpy.ndarray.transpose

We should probably combine these together in some way.

At the very least, we should add a cross-link between them like we do for `ndarray.sort` and `sort`.

**Comment by melissawm** [comment]
Right now, #16588 adds cross-links between `ndarray.transpose` and `transpose`, but we're still missing a unification of the actual documentation.
