### ISSUE TITLE
ImportError: Unable to import required dependencies: numpy: running python script from power BI

### ISSUE THREAD

**Issue by WaleAdelanwa** [numpy/numpy#16593]
I am trying to run a python script from power BI, I have installed all the modules and dependencies but still get this error. I have uninstall and reinstall numpy but still not working. I installed python 3.8 and I am using windows 10. I do not think I have multiple python versions of python installed

### Reproducing code example:

This is the code I ran
from pycaret.clustering import *
dataset = get_clusters(data = dataset)

### Error message:
```
DataSource.Error: ADO.NET: Python script error.
C:\Users\Wale\Anaconda3\envs\pyhon=3.8\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\Wale\Anaconda3\envs\pyhon=3.8\lib\site-packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "C:\Use...
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException
```

### Numpy/Python version information:

python 3.8 and  numpy version "1.18.1"

**Comment by eric-wieser** [comment]
Possibly relevant: https://community.powerbi.com/t5/Desktop/Microsoft-PowerBI-Scripting-Python-Exceptions/td-p/850714

**Comment by eric-wieser** [comment]
Duplicate of #16495

**Comment by WaleAdelanwa** [comment]
I have resolved this error. The python version on my pc is different from anaconda, I reinstalled version on myenv to match with the pc version
