### ISSUE TITLE
Slower performance of fftn in 1.18 compared to 1.16

### ISSUE THREAD

**Issue by Tokariew** [numpy/numpy#16595]
Slower performance of fftn in 1.18 compared to 1.16

### Reproducing code example:

```python
import numpy as np
a = np.random.rand(364*4,364,364) +1j * np.random.rand(364*4,364,364) +1j
%timeit np.fft.fftn(a)
```
1.16 -- 1.28s
1.18 -- 9.62s
1.14 scipy -- 1.98s

### Numpy/Python version information:

I using anaconda distribution. 1.16 is on 2019.10 and 1.18 is on 2020.02

1.18.1 3.7.6 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)]
1.16.5 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

On 1.18 version numpy use only single thread for computing fftn, but using scipy 1.14 with workers=-1 i still get slower performance, even if i have maxed cpu usage.

**Comment by charris** [comment]
Can you check if Anaconda is using the MKL FFT versions?

**Comment by Tokariew** [comment]
How i check it?
In both cases MKL FFT is installed in environments. Not sure if it is used…
I got quite similar result if I remove MKL FFT package, or use numpy package from conda-forge repository

**Comment by achimnol** [comment]
Try `np.show_config()` to see what backends are being used by numpy.

**Comment by Tokariew** [comment]
```
np.show_config()
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Conda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Conda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Conda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Conda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Conda\\Library\\include']
```

With new anaconda 2020.02 and numpy 1.18, mkl_info part is omitted.

**Comment by seberg** [comment]
Anaconda used to ship some intel patches, which was a disservice to many users, us, and generally confusing (i.e. you had a numpy that was not really numpy).

You should be able to get those patches, or run intel fft somehow else. Another approach could be to use `pyfftw`.  Unless there is some indication that there is more to the issue. I think we can close this @Tokariew, and you hopefully found out how to achieve the setup you want with the new version of numpy?

**Comment by mreineck** [comment]
I'm quite happy to see that `scipy`'s FFT is not too far away from the MKL timings - much of the remaining discrepancy can probably be explained by the fact that `scipy` does not ship AVX-optimized binaries, which would make `scipy.fft` faster again.

Let's hope that `numpy.fft` can switch to the `scipy` version as well at some point!

**Comment by Tokariew** [comment]
Can be close now…
