### ISSUE TITLE
DOC: Update language on numpy.squeeze

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#16610]
In the [numpy.squeeze](https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html) docstring, the use of "single-dimensional" and "singleton dimensions" (in the reference to numpy.expand_dims) is a bit confusing. This could be improved by using "one-dimensional" instead or rewording the docstring.

**Comment by ramalho** [comment]
I agree. Also, I looked for a glossary definition of "singleton dimension" and could not find it. If we are going to stick with this term, we need to define it somewhere in the docs.

**Comment by seberg** [comment]
I would be happy to avoid the term entirely.  There do not really seem to be many places where its used in the docs (a grep found 2, plus a few commit messages/code comments).
If we need such a term, then it would make sense in the broadcasting documentation.  While "dimension of size one" feels a bit long, I honestly do not think "singleton" has the right connotation to begin with.

**Comment by ramalho** [comment]
I am a newbie, so I did not know how prevalent was the term. If it occurs only twice, it doesn't deserve it's own jargon entry, in my opinion. I like "dimension of size one" or "dimension of length one" like @melissawm tweeted.

**Comment by ruppysuppy** [comment]
@melissawm and @seberg, I would like to work on this issue. 
Do I need to change all these files: [numpy/core/fromnumeric.py](https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py#L1450),  [numpy/core/_add_newdocs.py](https://github.com/numpy/numpy/blob/master/numpy/core/_add_newdocs.py#L3754) and [numpy/matrixlib/defmatrix.py](https://github.com/numpy/numpy/blob/master/numpy/matrixlib/defmatrix.py#L332) or only [numpy/core/fromnumeric.py](https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py#L1450)?

**Comment by eric-wieser** [comment]
@ruppysuppy: Changing all of those sounds good to me :)
