### ISSUE TITLE
Add a format specifier for Py_ssize_t (Trac #1063)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1661]
_Original ticket http://projects.scipy.org/numpy/ticket/1063 on 2009-03-23 by @cournape, assigned to unknown._

Right now, we have no portable way to print a Py_ssize_t (%z). Would be nice to fix a couple of warnings on some 64 bits arch.

**Comment by seberg** [comment]
We have `INTP_FMT`, and I assume these compiler warnings are fixed.
