### ISSUE TITLE
Shippable always fails

### ISSUE THREAD

**Issue by sturlamolden** [numpy/numpy#16611]
Shippable runs are consistently failing on "restore cache".

```
tar -xzf /home/shippable/cache/buildCache.tar.gz 14s  
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by sturlamolden** [comment]
It worked until it had a timeout on June 8. All runs on Shippable were then skipped until yesterday, when ut had one successful run, and has since then been consistently failing.

**Comment by sturlamolden** [comment]
There is now 20 consecutive CI failures with Shippable. We need to turn that thing off because it pollutes every PR with a failed check.

**Comment by tylerjereddy** [comment]
Or we could at least patiently try to follow the instructions to reset the cache:

http://docs.shippable.com/ci/caching/

I've clicked on the reset cache button in the UI for the NumPy project on shippable. There's also a tag for commit messages that can be used to reset cache.

If that still doesn't work, then using Travis or drone or whatever is an alternative, but it is not like those are impervious to maintenance issues either.

**Comment by sturlamolden** [comment]
Shippable had two successful Ci runs, and is not failling om cache restore again.

**Comment by sturlamolden** [comment]
Looks like the problem has returned.

**Comment by tylerjereddy** [comment]
> Looks like the problem has returned.

On what basis? If they fail on the restore cache stage then they don't have the updated yaml file. Just rebase them.
