### ISSUE TITLE
Appending new max value to np.array doesn't update its argmax

### ISSUE THREAD

**Issue by KeithYJohnson** [numpy/numpy#16634]
When appending to a numpy array, if the appended value is the new max value in the array, np.argmax will still return the previous max value of the array.  I read the docs and it didn't mention anything about guarantees being broken if you mutate an array, but still, not sure if this is expected/known behavior;  if so, my apologies!  And please let me know and I'll close the issue :)

### Reproducing code example:

```python
import numpy as np
>>> x = np.array([1,9,0,2])
>>> x.argmax()
1
>>> np.append(x,[10])
array([ 1,  9,  0,  2, 10])
>>> x.argmax()
1
>>> y = np.array([ 1,  9,  0,  2, 10])
>>> y.argmax()
4
>>> np.argmax(x)
1
>>> np.argmax(y)
4

>>> np.version.version
'1.18.5'
```

### Error message:

N/A.

### Numpy/Python version information:

```
import sys, numpy; print(numpy.__version__, sys.version)
1.18.5 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:10:22)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

**Comment by matthew-brett** [comment]
Append doesn't work in-place - it returns a new array with the value appended:

```python
[ins] In [5]: x_dash = np.append(x,[10])                                                           
[ins] In [6]: x_dash.argmax()                                                                      
Out[6]: 4
```

**Comment by KeithYJohnson** [comment]
Ahh I see, I had expected it to mutate the array as python's list's append does, which on second thought doesn't quite make sense as you're not calling append on the numpy array itself.  My bad, thanks for the quick reply!
