### ISSUE TITLE
Unexpected behaviour instead of MemoryError

### ISSUE THREAD

**Issue by HenrikJStromberg** [numpy/numpy#16636]
I have accidentally created an array vastly bigger than the available system memory by using a broadcasting operation. However this did not result in a MemoryError as I would have expected. Instead it returns a Python bool (not an array). I think throwing the exception instead would be more convenient. Under other circumstances it caused unexpected behavior of PyCharm. Since this is much harder to reproduce and will probably be fixed with the main issue I will not go into more detail for this. I have also reproduced the issue on a clean Ubuntu VM without an IDE or Virtual environments.

### Reproducing code example:
```python
import numpy as np
a = np.arange(15, dtype=int)
print(type(a[:, None] == np.arange(a.max() + 1).T)) # returns numpy.ndarray as expected

b = np.arange(10**6, dtype=int)
print(type(b[:, None] == np.arange(b.max() + 1).T)) # returns bool
```

### Numpy/Python version information:
1.18.2 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]

### Machine info:
OS: Windows 10.0.18362 Built 18362
Physical memory: 24 GB
Page file: 67,4 GB
CPU: Intel i7 7820X
IDE: PyCharm Community Edition 2020.1

### VM info:
OS: Ubuntu 18.04.4 LTS
Memory: 4838 MB
Swap 947 MB
Virtualization: VMware Workstation 15 Pro

**Comment by charris** [comment]
Hmm.  A couple of question, are you running in some sort of virtual environment or have a large amount of virtual memory? IIRC, we do two checks, one on memory size and the second if the memory allocation returns an error. The return is definitely strange, I wonder if it is the size of the needed memory?

**Comment by seberg** [comment]
I think if you enable deprecation warnings, you should probably be seeing one here, because the actual comparison failed.

It is an interesting thing that it does not fail here with a `TypeError` (which we may just convert into a result of all `False`, but rather a MemoryError, which should definitely just be floated to the user.
