### ISSUE TITLE
[DOC] Clarification on boolean indexing example in the documentation

### ISSUE THREAD

**Issue by samukweku** [numpy/numpy#16637]
### Reproducing code example:

The second example under boolean indexing gives a result for ```rowsum``` which I cannot replicate. 

documentation link -- > [boolean indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html#boolean-array-indexing)

```python
import numpy as np
x = np.array([[0, 1], [1, 1], [2, 2]])

rowsum = x.sum(-1, keepdims=True)

print(rowsum.shape)
(3, 1)

#this is the part that I am referring to
x[rowsum <= 2]
array([0, 1])
```

### Error message:

```
x[rowsum<=2]

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-102-e659010a9bc6> in <module>
----> 1 x[rowsum<=2]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 2 but corresponding boolean dimension is 1
```

### Numpy/Python version information: 1.18.5

The error is clear, since they are of different dimensions. Just checking if the result in the docs is a typo, or something else that I missed. Thanks for your time.

**Comment by melissawm** [comment]
Thanks for reporting this, @samukweku ! This example has been removed in PR #15694, so it should be ok for the next release. You can check out the new docs at https://numpy.org/devdocs
