### ISSUE TITLE
Native libs at wrong path in Linux wheels

### ISSUE THREAD

**Issue by joeringg** [numpy/numpy#16655]
Apologies if this has already been reported or is not actually an issue.  I don't have that much experience with the expected structure for Python wheels, but I think there may be an inconsistency with package structure from the 1.18.3 version onward.

I've been building a custom AWS Lambda layer for Python 3.6 that installs numpy via pip.  The Linux environment is CentOS 6-like, and openblas is not installed.  When updating from 1.18.2 to 1.19.0, I got an error stating `libopenblasp-r0-34a18dc3.3.7.so: cannot open shared object file: No such file or directory`.  Reverting to 1.18.2 and `numpy-1.18.2-cp36-cp36m-manylinux1_x86_64.whl` solved the problem, but I got the same error again with 1.18.3.

Digging in, it seems that the folder structure for packaged shared libs has changed from `numpy/.libs` to `numpy.libs` (see output below), but I'm not sure if this is intentional or not.  Downloading other wheels (from pypi) for windows and macos, the shared libs seem to still be packaged in `numpy/.libs` or `numpy/.dylibs` respectively.  This seems to be consistent for all python versions and Linux wheels.

I wasn't able to find any commits between 1.18.2 and 1.18.3 that seemed to explain the change.  I did verify that wheels for 1.18.3, 1.18.4, 1.18.5, and 1.19.0 have this folder structure.

``` 
joe$ unzip -l numpy-1.19.0-cp36-cp36m-macosx_10_9_x86_64.whl | grep blas
 63257476  06-20-2020 19:23   numpy/.dylibs/libopenblas.0.dylib
joe$ unzip -l numpy-1.19.0-cp38-cp38-win_amd64.whl | grep blas
 32939993  06-20-2020 19:22   numpy/.libs/libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll 
joe$ unzip -l numpy-1.19.0-cp36-cp36m-manylinux1_x86_64.whl | grep blas
 29530352  06-20-2020 19:43   numpy.libs/libopenblasp-r0-edd6b1a3.3.9.dev.so 
joe$ unzip -l numpy-1.19.0-cp37-cp37m-manylinux1_x86_64.whl | grep blas
 29530352  06-20-2020 19:32   numpy.libs/libopenblasp-r0-edd6b1a3.3.9.dev.so 
joe$ unzip -l numpy-1.19.0-cp36-cp36m-manylinux2010_x86_64.whl | grep blas
 30077440  06-20-2020 19:34   numpy.libs/libopenblasp-r0-ae94cfde.3.9.dev.so 
joe$ unzip -l numpy-1.18.3-cp36-cp36m-manylinux1_x86_64.whl | grep blas
 29724672  04-19-2020 17:31   numpy.libs/libopenblasp-r0-34a18dc3.3.7.so 
joe$ unzip -l numpy-1.18.2-cp36-cp36m-manylinux1_x86_64.whl | grep blas
 29724672  03-10-2020 04:52   numpy/.libs/libopenblasp-r0-34a18dc3.3.7.so
```

**Comment by mattip** [comment]
It seems at least the RPATH is consistent with the weird directory name:
```
$ objdump -x core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so |grep RPATH
  RPATH                $ORIGIN/../../numpy.libs
```

The change was unintentional, but should be harmless as long as your install process preserves the `numpy.libs` library in place next to the `numpy` one.

**Comment by mattip** [comment]
fwiw, latest scipy wheels have the same directory structure.

**Comment by mattip** [comment]
This apparently is intentional. It was done by pypa/auditwheel#90 in order to address pypa/auditwheel#89.

**Comment by joeringg** [comment]
Great, thanks for the info!  I can easily adjust my build script but I appreciate the sanity check.

**Comment by rossbar** [comment]
This seems to have been sufficiently tracked-down, so I'm going to close it. Feel free to reopen for further discussion as needed.
