### ISSUE TITLE
Please consider adding a NumpySlice type annotation, and exposing Shape, ShapeLike

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#16657]
I often use something like this:
```python
NumpySlice = Tuple[Union[int, None, slice, ndarray], ...]
```
but I guess this is more general?
```python
NumpySlice = Union[ndarray, Tuple[Union[int, None, slice, ndarray], ...]]
```

Also, why aren't `_Shape` and `_ShapeLike` exposed as `Shape` and `ShapeLike`?  It would be nice to use those and the leading underscore makes them seem private and internal.

**Comment by shoyer** [comment]
Could you elaborate on your use case for NumpySlice? For the most part, I would imagine that makes sense to use more specific types, rather than "everything supported by NumPy's indexing"

> Also, why aren't `_Shape` and `_ShapeLike` exposed as `Shape` and `ShapeLike`? It would be nice to use those and the leading underscore makes them seem private and internal.

These *are* private and internal :).

- `Shape = Tuple[int, ...]` is an example of code so short and simple that it's better to duplicate rather than import it.
- `ShapeLike` isn't a type that is used consistently inside NumPy -- there is no single path for canonicalizing or type-checking shapes. Without looking it up, I wouldn't even know what it refers to, e.g., would it include 1D numpy array or not?

**Comment by NeilGirdhar** [comment]
Here's where I'm currently using slice:

I use this method:
```python
    def _col_slice(i: SliceLike) -> SliceLike:
        return (slice(None), *i)
```
here:
```
        xs = np.linspace(0.0, self.iterations * self.time_step, self.iterations, endpoint=False)
        all_ys = np.asarray(getattr(self.trajectory, name))
        for i in np.ndindex(all_ys.shape[1:]):
            ys = all_ys[self._col_slice(i)]
            axis.plot(xs, ys, label=str(i))
```
Here's another place:
```python
    def index_into_component(
            self,
            component_index: int,
            slice_into_matched_signals: SliceLike) -> SliceLike:
        """
        Args:
            component_index: The index of the component signals.
            slice_into_matched_signals: A slice into the matched signals.

        Returns:
            The slice corresponding to “slice_into_matched_signals” into signals for component
            “component_index”.
        """
        assert (len(slice_into_matched_signals)
                == len(self._matched_signal_shape))
        retval = []
        for s_i, ic_i in zip(self._non_integer_indices(component_index),
                             slice_into_matched_signals):
            if s_i == np.newaxis:
                continue
            assert s_i == slice(None)
            retval.append(ic_i)
        return tuple(retval)
```

As for `ShapeLike`, here's an example:
```python
def sum_tensors(tensors: Collection[Tensor],
                shape: Optional[ShapeLike] = None) -> Tensor:
    if not tensors:
        return jnp.zeros(shape)
    return reduce(add, tensors)
```

**Comment by BvB93** [comment]
While I can definitely see its usefulness, I feel that exposing such an annotation to the public namespace would be premature. 
Namely we'd first need `ndarray` the be made generic with respect to its dtype; afterwards we can properly annotate array-like objects consisting of integers or booleans, which is what we'd need for something like the proposed `NumpySlice`.

**Comment by NeilGirdhar** [comment]
@BvB93 Okay, that makes sense. Are typed `ndarray` in the plans for 1.20?

**Comment by BvB93** [comment]
As for as I'm aware there are no concrete plans yet for when proper dtype support will be implemented.
If you're interested then I'd recommend keeping an eye on https://github.com/numpy/numpy/issues/16545.

**Comment by NeilGirdhar** [comment]
Thank you, I will do that.

**Comment by person142** [comment]
> Are typed ndarray in the plans for 1.20?

My goal is yes. Part of the reason for merging the stubs early in the 1.20 release cycle was to get it ironed out.

**Comment by person142** [comment]
No promises, but I think I should have updates on this in the weeks time scale.

**Comment by NeilGirdhar** [comment]
That is awesome!!
