### ISSUE TITLE
1.18 Build Failure Ubuntu 16.04, Python 3.8 Gnu 9 Compilers: Cythonize Failed.

### ISSUE THREAD

**Issue by chrisgmorton** [numpy/numpy#16663]
The NumPy 1.18.5 build fails on Ubuntu 16.04 with a cythonize error, using Python 3.8.3 built from source with GNU 9.3.0 compiler set. The NumPy 1.17.5 build completes successfully with same setup so something changed from 1.17 to 1.18 to cause the error. The NumPy 1.18.5 build completes successfully on MacOSX 10.15.5 Catalina, using Python 3.8.3 built with Xcode compilers and NumPy built with GNU 9.2 compiler set provided by hpc.sourceforge.net.

### Error message:

```
Running from numpy source directory.

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install numpy`   (last NumPy release on PyPi)


Cythonizing sources
Processing numpy/random/.__bounded_integers.pxd.in
Traceback (most recent call last):
  File "/mnt/d/fusion/build/numpy-1.18.5/tools/cythonize.py", line 238, in <module>
    main()
  File "/mnt/d/fusion/build/numpy-1.18.5/tools/cythonize.py", line 234, in main
    find_process_files(root_dir)
  File "/mnt/d/fusion/build/numpy-1.18.5/tools/cythonize.py", line 225, in find_process_files
    process(root_dir, fromfile, tofile, function, hash_db)
  File "/mnt/d/fusion/build/numpy-1.18.5/tools/cythonize.py", line 191, in process
    processor_function(fromfile, tofile)
  File "/mnt/d/fusion/build/numpy-1.18.5/tools/cythonize.py", line 125, in process_tempita_pxd
    tmpl = f.read()
  File "/mnt/d/fusion/prod/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 37: invalid start byte
Traceback (most recent call last):
  File "setup.py", line 488, in <module>
    setup_package()
  File "setup.py", line 469, in setup_package
    generate_cython()
  File "setup.py", line 275, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
```
### Numpy/Python version information:
Numpy 1.18.5, Python 3.8.3, gcc, g++, gfortran 9.3.0, Cython 0.29.20

**Comment by charris** [comment]
IIRC, I've seen similar failures when the repo isn't cleaned between builds. You don't say where you got the source or how you are installing.

**Comment by chrisgmorton** [comment]
Install was using 
```
python3.8 -s setup.py install --prefix=<path to install dir>
```

Downloaded from pipit.org: [https://pypi.org/project/numpy/1.18.5/#files](url)

It's zip file so I unzipped, tared and gziped it on Mac before pushing to a git server and then pulling onto Win 10 machine running WSL 1.

**Comment by charris** [comment]
I can't see why that should fail, athough ISTR other problems with WSL and there are a lot of steps.  What happens if you directly download the tar file at https://github.com/numpy/numpy/releases/download/v1.19.0/numpy-1.19.0.tar.gz and use that?

**Comment by chrisgmorton** [comment]
I was able to successfully build 1.19.0 on Ubuntu using the source download you provided. Thanks.
 I will test and also check out the build on Catalina next.

**Comment by chrisgmorton** [comment]
All tests pass on Ubuntu 18.04 (WSL2) and Catalina.
