### ISSUE TITLE
float64 and float128 give different result for 3 decimal value number

### ISSUE THREAD

**Issue by mohammadalimehdizadeh** [numpy/numpy#16661]
```python
In [2]: import numpy as np                                                      

In [3]: np.float64(0.998)                                                       
Out[3]: 0.998

In [4]: np.float128(0.998)                                                      
Out[4]: 0.9979999999999999982

In [5]: np.float64('0.998')==np.float128('0.998')                               
Out[5]: False

```

### Numpy/Python version information:

In [7]: import sys, numpy; print(numpy.__version__, sys.version)                
1.18.1 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]

**Comment by eric-wieser** [comment]
Neither `float64` nor `float128` can store `0.998` exactly. More precision gives a better approximation, and two approximations of different quality should not be expected to be equal.

**Comment by eric-wieser** [comment]
@ahaldane, is there a bug in `float128.__repr__` here? Shouldn't it give the minimum number of digits needed to roundtrip?

**Comment by eric-wieser** [comment]
This might make it clearer what is going on:
```
In [1]: import numpy as np

In [2]: np.float128(0.998)
Out[2]: 0.9979999999999999982

In [3]: np.float128('0.998')
Out[3]: 0.998
```

**Comment by mohammadalimehdizadeh** [comment]
@eric-wieser thanks for your response.
I find decimal module of python built in useful and it solve my problem.

**Comment by mohammadalimehdizadeh** [comment]
but 0.998 is an exact value?

**Comment by charris** [comment]
> but 0.998 is an exact value?

Not in base two.
