### ISSUE TITLE
API: Determine private/public functions in lib.format

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#16681]
`numpy.lib.format` defines [several functions](https://numpy.org/devdocs/reference/generated/numpy.lib.format.html#module-numpy.lib.format) (see listing at the bottom of the page). Some of these functions are clearly intended to be public (e.g. `open_memmap`) whereas others seem intended for internal use only. 

It would be good to review the functions, determine which are intended to be public, and:
 1. Add them to `__all__` (currently an empty list)
 2. Ensure that their docstrings are picked up by sphinx and included in the html documentation.

Related discussions: #13414 #16664

### Numpy/Python version information:

1.20.0.dev0+7af1024 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]

**Comment by mattip** [comment]
Closing, the functions mentioned on that page now all have a docstiong. Please reopen if I misunderstood.
