### ISSUE TITLE
ENH: Make `c_distributions` (`npyrandom`) includes more convenient

### ISSUE THREAD

**Issue by zoj613** [numpy/numpy#16686]
When trying to replicate example 3 in the random extending section https://numpy.org/devdocs/reference/random/examples/cython/extending_distributions.pyx.html I get a `undefined symbol: random_standard_uniform_fill_f` Import error.

The cython extension compiles fine with no issues until I try to run the function in a python script

### Reproducing code example:
example 3 in https://numpy.org/devdocs/reference/random/examples/cython/extending_distributions.pyx.html

When inside a python session
```python
#cython: language_level=3

# example.pyx
import numpy as np
cimport numpy as np
cimport cython
from cpython.pycapsule cimport PyCapsule_IsValid, PyCapsule_GetPointer
from libc.stdint cimport uint16_t, uint64_t
from numpy.random cimport bitgen_t
from numpy.random import PCG64
from numpy.random.c_distributions cimport (
      random_standard_uniform_fill, random_standard_uniform_fill_f)


def uniforms_ex(Py_ssize_t n, dtype=np.float64):
    cdef Py_ssize_t i
    cdef bitgen_t *rng
    cdef const char *capsule_name = "BitGenerator"
    cdef np.ndarray randoms

    bit_generator = PCG64()
    capsule = bit_generator.capsule
    # Optional check that the capsule if from a BitGenerator
    if not PyCapsule_IsValid(capsule, capsule_name):
        raise ValueError("Invalid pointer to anon_func_state")
    # Cast the pointer
    rng = <bitgen_t *> PyCapsule_GetPointer(capsule, capsule_name)

    _dtype = np.dtype(dtype)
    randoms = np.empty(n, dtype=_dtype)
    if _dtype == np.float32:
        with bit_generator.lock:
            random_standard_uniform_fill_f(rng, n, <float*>np.PyArray_DATA(randoms))
    elif _dtype == np.float64:
        with bit_generator.lock:
            random_standard_uniform_fill(rng, n, <double*>np.PyArray_DATA(randoms))
    else:
        raise TypeError('Unsupported dtype %r for random' % _dtype)
    return randoms
```

```python

if __name__ == "__main__":
    print(uniforms_ex(100))
```

### Error message:
```
Traceback (most recent call last):
  File "/example_script.py", line 2, in <module>
    from example import uniform_ex
ImportError: /home/npy_extend/example.cpython-36m-x86_64-linux-gnu.so: undefined symbol: random_standard_uniform_fill_f
```
### Numpy/Python version information:
```
1.19.0 3.6.10 (default, May 29 2020, 15:31:17) 
[GCC 9.3.0]
```

**Comment by zoj613** [comment]
@charris do you have an idea why the import is failing here? I would like to be able to use the distributions directly in a custom cython module.

**Comment by mattip** [comment]
Where did you get numpy? 

We are supposed to [run that code in the tests](https://github.com/numpy/numpy/blob/v1.19.0/numpy/random/tests/test_extending.py#L84), maybe that test is getting skipped?

**Comment by zoj613** [comment]
> Where did you get numpy?
> 
> We are supposed to [run that code in the tests](https://github.com/numpy/numpy/blob/v1.19.0/numpy/random/tests/test_extending.py#L84), maybe that test is getting skipped?

Got numpy through `pip install -U numpy`

**Comment by seberg** [comment]
Did you add the manual include in the setup.py or cython linking step (both library and library path)?  The example setup in the documentation has the correct incarnation.

**Comment by zoj613** [comment]
@seberg the setup looks like this:
```python
from distutils.command.build_ext import build_ext
from distutils.core import Extension, setup

import numpy as np
from Cython.Build import cythonize

extensions = [
    Extension(
        "npy_extend/**", ["npy_extend/**.pyx"],
        include_dirs=[np.get_include()],
        library_dirs=[np.get_include()],
    ),
]

ext = cythonize(extensions, include_path=[np.get_include()], annotate=True)

setup(ext_modules=ext, cmdclass={'build_ext': build_ext})
```

**Comment by mattip** [comment]
Yes, [this line](https://github.com/numpy/numpy/blob/v1.19.0/numpy/random/_examples/cython/setup.py#L33) `libraries=['npyrandom'],` is missing.

**Comment by zoj613** [comment]
> Yes, [this line](https://github.com/numpy/numpy/blob/v1.19.0/numpy/random/_examples/cython/setup.py#L33) `libraries=['npyrandom'],` is missing.

This doesn't work. Okay, Im confused now. Why do I need to include this line when I already have `np.get_include()`? Im not running the example directly from the numpy module. I modified it into a `example.pyx` module so as to test if I can use the c_distributions in my programs as shown in the mini-script I attached in the OP. However even after added the line I still get the import error.

**Comment by seberg** [comment]
The include is currently not placed there, you also need to add to the include path (its further up). That is currently pretty inconvenient, and we should probably have a nicer way to do it (i.e. `np.get_includes("npyrandom")` or so).

**Comment by seberg** [comment]
@zoj613 can you confirm that adding the path works for you?  I realize it is a bit inconvenient, so I think we should leave this open to see whether we cannot make it a bit more straight forward (at least not having to add `../../` to the paths manually).

**Comment by mattip** [comment]
> This doesn't work. 

What exactly doesn't work? It compiles and still fails or fails to compile? You need to link to the library in that line since it provides the functions you are missing. The `library_dirs` tells the linker where the library is located, so you need both the `library_dirs` and the `libraries` lines.

**Comment by zoj613** [comment]
> > This doesn't work.
> 
> What exactly doesn't work? It compiles and still fails or fails to compile? You need to link to the library in that line since it provides the functions you are missing. The `library_dirs` tells the linker where the library is located, so you need both the `library_dirs` and the `libraries` lines.

I went back and rewrote the setup file according o the style shown in the extending documentation you linked to and now it works. Thanks. Is there a reason why I needed to link to the `libnpyrandom.a` library file? I initially thought all numpy cython number libraries would be linked by just using `np.get_include()`

**Comment by zoj613** [comment]
@mattip @seberg 

Is it normal for the regular `np.random.default_rng` to result in faster generation of random numbers compared to tthe c_functions?

Lets say I have these two base classes for defining a "general" distribution class:
``python

cdef class Distribution:
    cdef object random_state
    cdef object bitgen
    cdef bitgen_t* rng

    def __cinit__(self, random_state=None):
        self.bitgen = PCG64(random_state)
        cdef const char* capsule_name = 'BitGenerator'
        capsule = self.bitgen.capsule

        if not PyCapsule_IsValid(capsule, capsule_name):
            raise ValueError("Invalid pointer to anon_func_state")

        self.rng = <bitgen_t*>PyCapsule_GetPointer(capsule, capsule_name)
        self.random_state = random_state

    def __reduce__(self):
        return self.__class__, (self.random_state,)

cdef class Distribution2:
    cdef object random_state
    cdef object rng

    def __cinit__(self, random_state=None):
        self.random_state = random_state
        self.rng = np.random.default_rng(random_state)

    def __reduce__(self):
        return self.__class__, (self.random_state,)
```

and then define concrete implementation of a distribution this way:
```python

cdef class SparseMultivariateNormal(Distribution):

    cpdef tuple rvs(self, double[:] mean, cov):
        cdef int size = mean.shape[0]
        cdef np.ndarray arr = np.empty(size)

        factor = sparse_cholesky(cov, ordering_method='default')
        L = factor.L()
        chol = factor.apply_Pt(L)

        with self.bitgen.lock, nogil:
            random_standard_normal_fill(
                self.rng, size, <double*>np.PyArray_DATA(arr)
            )

        arr = mean + chol * arr
        return arr, factor

cdef class SparseMultivariateNormal2(Distribution2):

    cpdef tuple rvs(self, double[:] mean, cov):
        cdef int size = mean.shape[0]

        factor = sparse_cholesky(cov, ordering_method='default')
        L = factor.L()
        chol = factor.apply_Pt(L)

        arr = self.rng.standard_normal(size)
        arr = mean + chol * arr
        return arr, factor 
```

The runtime when sampling repeatably using the python level random number generator seems to be 1second faster than using c level random number generation here. Is this normal or am I not using this correctly?

**Comment by mattip** [comment]
> Is there a reason why I needed to link to the libnpyrandom.a library file? I initially thought all numpy cython libraries would be linked by just using np.get_include()

 A github issues is not the best place to discuss the way C compilers work, but I will give a quick summary (hopefully accurate enough as to not start a whole new discussion) with terms in italics so you can search for them and learn more elsewhere. The result of `get_include` is a path to *header files* with *function declarations*. `libnpyrandom.a` is an *library archive* which basically strings together *object files*, which are compiled implementations of the source code for the functions. Your code has lines like `#include file.h` so the compiler goes and finds `file.h` along the *include path*, where it can find the function declaration. At *link* time the linker need to be able to find the implementations, so it searches for libraries and *shared objects* along the *link path*.

Since rewriting the `setup.py` to add the linker directive `libraries=['npyrandom']` solves the problem, I think we can close this issue.
