### ISSUE TITLE
numpy.delete axis=1 takes much longer with list of length 1 than int

### ISSUE THREAD

**Issue by DevinShanahan** [numpy/numpy#16685]
Delete takes much longer with `obj=[0]` than `obj=0` when `axis=1`. This does not appear to be the case for `axis=0`. 

```python
import numpy as np
import timeit

arr = np.arange(300000000).reshape(100000, 3000)
lst = [0]

timeInt = timeit.timeit('np.delete(arr, obj=0, axis=1)', setup='from __main__ import np, arr', number=3) / 3
timeList = timeit.timeit('np.delete(arr, obj=lst, axis=1)', setup='from __main__ import np, arr, lst', number=3) / 3
print(timeInt)
print(timeList)
```
```
1.4012748020001407 
5.888861911666633
```

### Numpy/Python version information:

1.18.1 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by eric-wieser** [comment]
Did you mean to write `=` instead of `-`?

**Comment by eric-wieser** [comment]
A slightly shorter and faster test-case:
```
In [10]: arr = np.arange(3000000).reshape(1000, 3000)

In [11]: %timeit np.delete(arr, obj=[0], axis=1)
16.3 ms ± 2.2 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [12]: %timeit np.delete(arr, obj=0, axis=1)
10.1 ms ± 352 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by eric-wieser** [comment]
The short answer is because `delete` has an optimized case for when `obj` is a single integer.

**Comment by DevinShanahan** [comment]
Yes, sorry, I edited to use `=`. I see the optimization for single integers in the source. Is there any reason that it couldn't be extended for arrays of shape `(1,)`?

**Comment by InessaPawson** [comment]
The issue was solved by https://github.com/numpy/numpy/pull/16895.
