### ISSUE TITLE
DOC: Update Sum function with axis

### ISSUE THREAD

**Issue by cyxoc** [numpy/numpy#16697]
In this Documention  https://numpy.org/devdocs/user/absolute_beginners.html 
Sum of rows of an numpy array is denoted by b.sum(axis=0), but the axis should be equal to 1 for sum of rows and 0 for sum of columns.

pleas refer to the screenshot below from the documentation web page.

![image](https://user-images.githubusercontent.com/26023337/85929562-73e1a780-b8d3-11ea-88cd-90ca73d57e85.png)

**Comment by WarrenWeckesser** [comment]
When the text says "sum the rows", it is talking about creating the sum `row 0  + row 1 + row 2 + ...`, not the sum of the values within each row.

If anyone else also finds this confusing, perhaps we can update the text to clarify the operation being demonstrated.  Suggestions are welcome.

**Comment by melissawm** [comment]
I'll admit that not being a native english speaker this has ALWAYS confused me. The only way I could understand this is by reasoning that the axis in the arguments is the axis to be "collapsed". Maybe this can be noted somewhere in that guide?

**Comment by seberg** [comment]
I think in many cases, we maybe should always add an additional word, such as along or over, although I feel there may be a clearer word(ing) (at least this is very introductory, so a full sentence is also fine).

This is the typical use of `axis`  in numpy (although there are rare exceptions).

**Comment by eric-wieser** [comment]
Perhaps one way to help think how to word this would be to attempt to describe the operation on a 3d array.

**Comment by PRUBHTEJ** [comment]
Is this issue still relevant?
If yes, I can try to update the documentation, but since I'm a new contributor, I'll be needing some guidance.

**Comment by melissawm** [comment]
Hello, @PRUBHTEJ , if you have a suggestion about rewording this, maybe we can discuss it here in the issue before a pull request is submitted. If you need help submitting the PR once we have resolved this, I'll be happy to help!

**Comment by PRUBHTEJ** [comment]
Great, @melissawm. I'll try to go through the documentation first, so as to get a gist of it.

**Comment by ash248cool** [comment]
I don't understand why this is labelled as a bug!

**Comment by eric-wieser** [comment]
@ash248cool: I don't understand your comment, this is _not_ labelled as a bug.

**Comment by Arko07-quanta** [comment]
@eric-wieser #17185 if we add the elements of rows with same index doesn't that mean adding the columns?

**Comment by EvaJau** [comment]
Hello, I will work on that issue.
