### ISSUE TITLE
OverflowError for np.random.RandomState()

### ISSUE THREAD

**Issue by RuofanKong** [numpy/numpy#16695]
I run the following code to uniformly generate a random float64 number. By default, the Python float is float64, and the same applies to numpy if I don't miss anything. However, when I feed the low and high with float64 min/max limit respectively, it raises the overflow error as below.

### Reproducing code example:
```python
import numpy as np
rand_gen = np.random.RandomState()
rand_gen.uniform(low=-1.79769313e308, high=1.79769313e308, size=[1])
```
### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1091, in numpy.random.mtrand.RandomState.uniform
OverflowError: Range exceeds valid bounds
```

### Numpy/Python version information:
- Python version: 3.6.5
- numpy version: 1.18.2

**Comment by seberg** [comment]
The reason for this is that the algorithm uses the range internally, so it is bounded by the range fitting into a double. Not sure whether there is any reasonable generalization or different approach. Lets ping @bashtage just in case.

**Comment by bashtage** [comment]
```
_low = PyFloat_AsDouble(low)
_high = PyFloat_AsDouble(high)
range = _high - _low
if not np.isfinite(range):
    raise OverflowError('Range exceeds valid bounds')
```
Seems pretty clear. The values are produced by first generating [0,1), then multiplying by range, and then adding to the low.  This would require a range of `2*np.finfo(float).max`.  You can generate this range by hand by generating [0,ffinfo(float).max) and then multiplying by a value that is 50% 1 and 50% -1.

```
np.isfinite(1.79769313e308-(-1.79769313e308))
Out[2]: False
```

Would say by design. 

Also, don't use `RandomState`, use `Generator` (which will also raise).

**Comment by RuofanKong** [comment]
@bashtage Thanks for the comment! Probably I'm not super clear on my description. In fact, what I mean is the default float convention in Python is float64, so my question is: Isn't it supposed to keep the same default convention for `numpy.random.RandomState()` instead of double?

**Comment by bashtage** [comment]
Python float is c double on all platforms I've ever used.

**Comment by RuofanKong** [comment]
@bashtage Ah thanks for pointing it out! yeah it's c double and it should be consistent. I'm closing the ticket. Also thanks @seberg for comments!

**Comment by seberg** [comment]
Ok, cool, yeah, the only serious thing to be done for now, would probably to add `Range (high - low) exceeds ...`, which I think would be a worthy small improvement.

**Comment by jluttine** [comment]
> Ok, cool, yeah, the only serious thing to be done for now, would probably to add `Range (high - low) exceeds ...`, which I think would be a worthy small improvement.

This improvement to the error message would be great.
