### ISSUE TITLE
np.histogram ignores last bin

### ISSUE THREAD

**Issue by jiwidi** [numpy/numpy#16698]
### Reproducing code example:

```python
import numpy as np
a = [1,2,2,3,3,4,4]
bins = [1,2,3,4]

np.histogram(a,bins)
```
Returns `(array([1, 2, 4]), array([1, 2, 3, 4]))` where the count of bins `array([1, 2, 4])` is wrong, is ignoring the last bin and in this case assigning counts of 4 to counts of 3. 

The desired output of counts should be `[1,2,2,2]` and there is a fix adding a extra dummy bin:

```python
import numpy as np
a = [1,2,2,3,3,4,4]
bins = [1,2,3,4,5]

np.histogram(a,bins)
```
Returns `(array([1, 2, 2, 2]), array([1, 2, 3, 4, 5]))` where the count of bins is correct.

### Numpy/Python version information:
Python 3.7.6
Numpy 1.18.1

### Summary

Hi! So I actually found a bug for np.histogram where bins counts are not correctly being calculated, if it happens to be correct I would love to work on a fix and follow with a PR

**Comment by rossbar** [comment]
Note that when `bins` is a sequence, it defines bin *edges*. From the docstring for np.histogram:

>    If `bins` is a
>    sequence, it defines a monotonically increasing array of bin edges,
>    including the rightmost edge, allowing for non-uniform bin widths.

In fact, the exact case presented above (`bins=[1, 2, 3, 4]`) is mentioned in the `Notes` section of the `np.histogram` docstring.

You may also want to check out `np.bincount`, which is closer to what appears to be your intended use-case. I hope this is helpful!
