### ISSUE TITLE
Which numpy version to install?

### ISSUE THREAD

**Issue by bergen288** [numpy/numpy#16711]
A lot of python packages require numpy and I am confused with their required numpy version.  My installed numpy is  the most recent v1.19.0.  But my following package installations are failed with the requirement of old numpy versions.   "statsmodels" required numpy v1.16.1 while the others require v1.16.0.  I am concerned that numpy 1.16.0 is pretty old version and it won't support all other packages.  What's the best way to go?
Thanks.
```r
Keras-2.4.3-py2.py3-none-any.whl.log:  ERROR: Could not find a version that satisfies the requirement numpy==1.16.0 (from versions: 1.19.0)
Theano-1.0.4.tar.gz.log:  ERROR: Could not find a version that satisfies the requirement numpy==1.16.0 (from versions: 1.19.0)
scikit_video-1.1.11-py2.py3-none-any.whl.log:  ERROR: Could not find a version that satisfies the requirement numpy==1.16.0 (from versions: 1.19.0)
seaborn-0.10.1-py3-none-any.whl.log:  ERROR: Could not find a version that satisfies the requirement numpy==1.16.0 (from versions: 1.19.0)
statsmodels-0.11.1.tar.gz.log:  ERROR: Could not find a version that satisfies the requirement numpy==1.16.1 (from versions: 1.16.0, 1.19.0)
```

**Comment by rgommers** [comment]
Hi @bergen288, you should give more details on what you did exactly, because it is not the case that other packages require an exact numpy version. They typically require a minimum version only, e.g. for statsmodels:
https://github.com/statsmodels/statsmodels/blob/master/requirements.txt

**Comment by bergen288** [comment]
Ok, let's take statsmodels as an example. Below is my installation log.  It is failed due to lack of ``` ERROR: No matching distribution found for numpy==1.16.1```
```r
Looking in links: ./
Processing ./statsmodels-0.11.1.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /opt/freeware/lib/python3.7/site-packages/pip-20.2.dev1-py3.7.egg/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ccd7yzht/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links ./ -- setuptools wheel 'cython>=0.29.14' 'numpy==1.14.5; python_version=='"'"'3.5'"'"'' 'numpy==1.14.5; python_version=='"'"'3.6'"'"'' 'numpy==1.16.1; python_version=='"'"'3.7'"'"'' 'numpy==1.17.5; python_version>='"'"'3.8'"'"'' 'scipy>=1.0'
       cwd: None
  Complete output (9 lines):
  Looking in links: ./
  Ignoring numpy: markers 'python_version == "3.5"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8"' don't match your environment
  Processing ./setuptools-47.3.1-py3-none-any.whl
  Processing ./wheel-0.34.2-py2.py3-none-any.whl
  Processing ./Cython-0.29.20-py2.py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement numpy==1.16.1 (from versions: 1.16.0, 1.19.0)
  ERROR: No matching distribution found for numpy==1.16.1
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /opt/freeware/lib/python3.7/site-packages/pip-20.2.dev1-py3.7.egg/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ccd7yzht/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links ./ -- setuptools wheel 'cython>=0.29.14' 'numpy==1.14.5; python_version=='"'"'3.5'"'"'' 'numpy==1.14.5; python_version=='"'"'3.6'"'"'' 'numpy==1.16.1; python_version=='"'"'3.7'"'"'' 'numpy==1.17.5; python_version>='"'"'3.8'"'"'' 'scipy>=1.0' Check the logs for full command output.
```

**Comment by rgommers** [comment]
Again, please tell us _exactly_ what you are doing. What OS, how did you install Python, and what command are you executing here?

**Comment by bergen288** [comment]
My server is AIX7.2 on IBM P9 Atomic S924 system without internet access. Python3.7 is installed with IBM RPM file downloaded from https://www.ibm.com/support/pages/node/883796#P. All python packages are downloaded to my PC first, then upload to AIX server.  The following script is used to install target packages such as ```statsmodels-0.11.1.tar.gz``` from default directory.

```r
pkg=$1
sudo python -m pip install --no-index --find-links ./ $pkg
```

**Comment by rgommers** [comment]
Okay, so what's happening is that there's no binary wheel for AIX for statmodels hence a source build is attempted, and so the lowest supported numpy version (`==1.16.1` here) is requested for an isolated build (this is related to PEP 517/518 and `pyproject.toml`). Try to add `--no-build-isolation` to your install command.

**Comment by bergen288** [comment]
After adding ```--no-build-isolation``` to my script, my installation for ```statsmodels-0.11.1.tar.gz``` is failed due to different error.  It depends on scipy which has some unavailable library staffs.  I will submit new issue to scipy forum.
Thanks a lot.
