### ISSUE TITLE
Callback on write?

### ISSUE THREAD

**Issue by Korijn** [numpy/numpy#16712]
I just have a question: since there is a writeable flag, Numpy must have a mechanism to _detect_ writes. I'd be interested to see if there is also a way to configure a callback when a write is detected? It would make ndarray's observable!

If there is no such system, how hard do you think it would be to implement it? Is there a central piece of code that processes write operations and checks against the writeable flag?

**Comment by seberg** [comment]
We do have a private function which is called for most writes. The only purpose of that is currently to warn the user in cases where we deprecate writing to the array.

Could you say a bit more about the use-case?  In general it is not easy to detect writing to an array, because you can write to an array e.g. by first calling `memoryview(arr)`, but we do not know if the purpose is writing to it (it likely is, but its not guaranteed). And that pattern is for example very common in cython code.

**Comment by Korijn** [comment]
Sorry, this is going to be a bit of a rant. :) My end goal is to simplify the life of developers of stateful applications.

> We do have a private function which is called for most writes. The only purpose of that is currently to warn the user in cases where we deprecate writing to the array.

I was actually referring to this behavior, but I suppose it is closely related to what you describe:

```python
>>> import numpy as np
>>> a = np.arange(10)
>>> a.flags.writeable = False
>>> a[5] = 100
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: assignment destination is read-only
```

> Could you say a bit more about the use-case? In general it is not easy to detect writing to an array, because you can write to an array e.g. by first calling `memoryview(arr)`, but we do not know if the purpose is writing to it (it likely is, but its not guaranteed). And that pattern is for example very common in cython code.

I'm developing a caching module for functions. It's different from lru_cache and memoization in that the functions are expected to have no parameters and instead operate on external state. My module tracks which external variables are actually being used to compute the function's output and monitors those dependencies to know when the function needs to be re-evaluated. 

Here's some example code from my current draft (not very polished and pretty yet, sorry):

```python
from deppy import make_reactive, cached

a = make_reactive(
    {"foo": 5, "bar": [6, 7, 8], "quux": 10, "quuz": {"a": 1, "b": 2}}
)
execute_count = 0

def bla():
    global execute_count
    execute_count += 1
    multi = 0
    if a["quux"] == 10:
        multi = a["foo"] * 5
    else:
        multi = a["bar"][-1] * 5
    return multi * a["quuz"]["b"]

cached_bla = cached(bla)
assert cached_bla() == 50
assert cached_bla() == 50
assert execute_count == 1
a["quux"] = 25
assert cached_bla() == 80
assert cached_bla() == 80
assert execute_count == 2
a["quuz"]["b"] = 3
assert cached_bla() == 120
assert cached_bla() == 120
assert execute_count == 3
```

You can also write functions that are dependent on other cached functions:

```python
    def bla2():
        global execute_count
        execute_count += 1
        return a["foo"] * cached_bla()

    cached_bla2 = cached(bla2)
    assert cached_bla2() == 600
    assert cached_bla2() == 600
    assert execute_count == 4
    a["quuz"]["b"] = 4
    assert cached_bla2() == 800
    assert cached_bla2() == 800
    assert execute_count == 6
```

This allows developers to construct dependency graphs of "computed state" and is based on a concept borrowed from [vue.js](https://vuejs.org/). It makes state management significantly easier: the system tracks dirty state for you automatically and recomputation is performed lazily and only when dirty.

I've got this working for dicts, sets, lists and tuples, since I can hook into the magic methods that mutate their contents. This makes the module useful in its current state for basic applications. However, scientific/graphic applications often use numpy, and I don't have a way to hook into the "write and read magic methods of ndarrays" yet. This is where my question comes from.

**Comment by eric-wieser** [comment]
This is basically impossible, unless you also monkey-patch memoryview:
```python
a = np.arange(10)
def bla():
    return a[0]
cached_bla = cached(bla)

cached_bla()  # 0

 # 1, if you tried really hard and overloaded `__setitem__` / `__getitem__` / `__array_ufunc__` / ...
a[1] = 1
cached_bla()  # 1 if you're lucky

# i see no way you could possibly intercept this, it's a direct memory write.
memoryview(a)[1] = 2
cached_bla()  # 2 iff you hook into your MMU _maybe_
```

**Comment by Korijn** [comment]
I don't intend to implement a watertight solution. I know there is no such thing, and provide fallback solutions (like manually setting a dirty flag). However, most common cases are pretty easy to cover and make the effort wortwhile.

(Vue.js' solution also has a bunch of [caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats) but that doesn't make the library useless)

**Comment by eric-wieser** [comment]
Perhaps your approach could be something like:
```
def detect_write(arr, func):
    old_w = arr.flags.writeable
    arr.flags.writeable = False
    try:
        return False, func(arr)
    except ValueError:  # if it helped you, we could consider a more specific error type here
        pass
    finally:
        arr.flags.writeable = old_w
    return True, func(arr)
```

**Comment by Korijn** [comment]
For future readers, this would have been my preferred approach:

` # 1, if you tried really hard and overloaded `__setitem__` / `__getitem__` / `__array_ufunc__` / ...`

However, I found a way to avoid the need for ndarray observability. :) The library is done and released by the way, in case you're interested: https://github.com/Korijn/observ
