### ISSUE TITLE
issue with documentation

### ISSUE THREAD

**Issue by gokhalen** [numpy/numpy#16717]
I have a small issue with the quickstart documentation here. 

https://numpy.org/devdocs/user/quickstart.html#view-or-shallow-copy

### Reproducing code example:

```python
import numpy as np
a=np.arange(16).reshape(4,4)
c=a.view()
```
The documentation says` c.base is a` evaluates to `True` but it seems to evaluate to `False`  on my machine. Perhaps the documentation is supposed to be `c.base is a.base`?

Thanks,

Nachiket

**Comment by eric-wieser** [comment]
Not just your machine, this code is wrong.

**Comment by eric-wieser** [comment]
....

Except, the code you put in this issue is not the same as what appears in the docs?

**Comment by gokhalen** [comment]
> ....
> 
> Except, the code you put in this issue is not the same as what appears in the docs?

Sorry, my mistake. I tried to make a small test case to illustrate what I thought was the error. The code in the docs is correct. But it means that there is a gap in my understanding. But the issue tracker is probably not the right place to discuss this. Shall I close the issue?

**Comment by pv** [comment]
The tutorial is a bit misleading --- when constructing views, IIRC base is generally the non-view object that actually owns the data.

**Comment by eric-wieser** [comment]
I think your understanding is basically there. The key point is either:

* `a` owns its own data (is the original array). `a.base is None`, and `b.base is a`
* `a` is in turn a view of another array (in this case, the temporary that was reshaped). `a.base is b.base is that_temporary_array`

**Comment by gokhalen** [comment]
Thanks, makes sense.
