### ISSUE TITLE
Python int too large to convert to C long

### ISSUE THREAD

**Issue by amsinha9** [numpy/numpy#16721]
I have 2 numpy arrays, a.shape = (897840, 382) and b.shape = (908160, 382), in which all of the elements in the matrix are decimals, such as 0.065096239001539. I am able to vertically stack the arrays using np.vstack((a, b)), however, when I try to save the numpy array out as a matlab array, I get the error, "OverflowError: Python int too large to convert to C long". How can I resolve this?

### Reproducing code example:

```python
import numpy as np
import scipy.io as sio

a = np.random.rand(897840, 382)
b = np.random.rand(908160, 382)

combined = np.vstack((a, b))

dict = {}
dict['test'] = combined

sio.savemat('test.mat', dict)

```
### Error message:

OverflowError                             Traceback (most recent call last)
<ipython-input-16-f389eeb65f8f> in <module>()
      2 dict['test'] = combined
      3 
----> 4 sio.savemat('test.mat', dict)

~\AppData\Roaming\Python\Python36\site-packages\scipy\io\matlab\mio.py in savemat(file_name, mdict, appendmat, format, long_field_names, do_compression, oned_as)
    217     else:
    218         raise ValueError("Format should be '4' or '5'")
--> 219     MW.put_variables(mdict)
    220     if file_opened:
    221         file_stream.close()

~\AppData\Roaming\Python\Python36\site-packages\scipy\io\matlab\mio5.py in put_variables(self, mdict, write_header)
    847                 self.file_stream.write(out_str)
    848             else:  # not compressing
--> 849                 self._matrix_writer.write_top(var, asbytes(name), is_global)

~\AppData\Roaming\Python\Python36\site-packages\scipy\io\matlab\mio5.py in write_top(self, arr, name, is_global)
    588         self._var_name = name
    589         # write the header and data
--> 590         self.write(arr)
    591 
    592     def write(self, arr):

~\AppData\Roaming\Python\Python36\site-packages\scipy\io\matlab\mio5.py in write(self, arr)
    627             self.write_char(narr, codec)
    628         else:
--> 629             self.write_numeric(narr)
    630         self.update_matrix_tag(mat_tag_pos)
    631 

~\AppData\Roaming\Python\Python36\site-packages\scipy\io\matlab\mio5.py in write_numeric(self, arr)
    653             self.write_element(arr.imag)
    654         else:
--> 655             self.write_element(arr)
    656 
    657     def write_char(self, arr, codec='ascii'):

~\AppData\Roaming\Python\Python36\site-packages\scipy\io\matlab\mio5.py in write_element(self, arr, mdtype)
    494             self.write_smalldata_element(arr, mdtype, byte_count)
    495         else:
--> 496             self.write_regular_element(arr, mdtype, byte_count)
    497 
    498     def write_smalldata_element(self, arr, mdtype, byte_count):

~\AppData\Roaming\Python\Python36\site-packages\scipy\io\matlab\mio5.py in write_regular_element(self, arr, mdtype, byte_count)
    508         tag = np.zeros((), NDT_TAG_FULL)
    509         tag['mdtype'] = mdtype
--> 510         tag['byte_count'] = byte_count
    511         self.write_bytes(tag)
    512         self.write_bytes(arr)

OverflowError: Python int too large to convert to C long

### Numpy/Python version information:

Numpy 1.14.3
1.14.3 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

**Comment by bashtage** [comment]
The bug is in `sio.savemat('test.mat', dict)`. You should open an issue on SciPy's repo.
