### ISSUE TITLE
Improving contiguity detection (Trac #1075)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1673]
_Original ticket http://projects.scipy.org/numpy/ticket/1075 on 2009-03-31 by @cournape, assigned to unknown._

The contiguous nature of arrays is more conservative than it should:

    #!python
    import numpy as np
    a = np.ones(10)
    b = a[None, :]
    print a.flags
    print b.flags

b is just a view on a, and the data buffer is contiguous in both cases, but b is flagged as neither C or F contiguous

**Comment by jakirkham** [comment]
Interesting related case I saw elsewhere. Don't know if it is worth a new issue or if it should stay here.

    In [1]: import numpy as np
    
    In [2]: a = np.arange(5)
    
    In [3]: a1 = a.reshape(1,5)
    
    In [4]: a2 = a[None]
    
    In [5]: a.shape, a.strides, a.flags.c_contiguous
    Out[5]: ((5,), (8,), True)
    
    In [6]: a1.shape, a1.strides, a1.flags.c_contiguous
    Out[6]: ((1, 5), (40, 8), True)
    
    In [7]: a2.shape, a2.strides, a2.flags.c_contiguous
    Out[7]: ((1, 5), (0, 8), False)

**Comment by seberg** [comment]
Yeah, frankly I stopped caring about it. Of course you could try to fix
the strides for the indexing, but RELAXED_STRIDES would fix it the
other way around in any case. And yes, it does mean that reshape can be
faster then the [None] trick.

**Comment by jakirkham** [comment]
So, is this the issue you were referring to before?

**Comment by seberg** [comment]
Sorry, no idea what you mean by before.

**Comment by jakirkham** [comment]
Fair.

> I have been waiting for probably 2-3 years for finally shipping relaxed strides, and guess what, in 1.11 we had to push that off for another two releases....

( https://github.com/numpy/numpy/issues/7164#issuecomment-178693968 )

**Comment by njsmith** [comment]
@jakirkham: yes, with relaxed strides enabled the weird behavior you're talking about goes away -- `a1` and `a2` both have `c_contiguous == True`. And no-one has much appetite for trying to keep adding more heuristics to fix these issues one-at-a-time -- it's not a game we can win. That's why we want to turn relaxed strides on -- so we can stop playing that game :-).

**Comment by jakirkham** [comment]
Sounds great! I think I saw somewhere this is scheduled for 1.12.0. Is that true?

**Comment by njsmith** [comment]
@jakirkham: I'm not sure -- it's a bit disruptive (it turns out there is code that was relying on the buggy behavior :-/), so we've been going back and forth on when to turn it on for real. I'd certainly be +1 for enabling it in 1.12.0b1 and seeing how bad the yells are.

**Comment by jakirkham** [comment]
>  I'm not sure -- it's a bit disruptive (it turns out there is code that was relying on the buggy behavior :-/)...

Spacebar heating. Unfortunate indeed. What are some of the "negative" consequences?

> I'd certainly be +1 for enabling it in 1.12.0b1 and seeing how bad the yells are.

Sounds good. So, if I wanted to test some code with this, would I just do something like add in `-DNPY_RELAXED_STRIDE_CHECKING=1` to the compile flags or is there something else/more I would need to do?

**Comment by seberg** [comment]
Just check `np.test()` tells you true (or test one of these examples).
We have it on in development versions as default for a long time now,
so any development version will do. There are two main issues:
  1. Code that assumes that for C-contiguous
     arr.strides[-1] == arr.dtype.itemsize
  2. Logic that gets confused by things like fortran ordered arrays
     suddenly *also* being C-order, and on top of that us prefering
     C-order.

**Comment by seberg** [comment]
Further problems are incompatibilities. E.g. cython rejecting such a
numpy array because it is not contiguous in its opinion while numpy
said it was. We clean that up a little nowadays, and cython relaxed
that check, but....

**Comment by jakirkham** [comment]
Thanks for clarifying.

**Comment by seberg** [comment]
I will close this, will have a small look at the final situation here soon/now I think.

**Comment by seberg** [comment]
Obviously, if anyone finds any issues for a downstream project with the relaxed strides setting, please do open a new issue to discuss it!
