### ISSUE TITLE
numpy.quantile raises an error for correctly sized out parameter

### ISSUE THREAD

**Issue by heitorschueroff** [numpy/numpy#16733]
numpy.quantile is rejecting a correctly sized out paremeter when q is a tensor and keepdims=True (see below for example).

### Reproducing code example:

```python
import numpy as np
np.quantile(np.random.randn(2, 4), [0.5, 0.7], axis=0, keepdims=True, out=np.ndarray((2, 1, 4)))
```

### Error message:

ValueError: non-broadcastable output operand with shape (2,1,4) doesn't match the broadcast shape (2,2,4)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in quantile
  File "/opt/miniconda3/envs/torch/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3817, in quantile
    return _quantile_unchecked(
  File "/opt/miniconda3/envs/torch/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3824, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "/opt/miniconda3/envs/torch/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3403, in _ureduce
    r = func(a, **kwargs)
  File "/opt/miniconda3/envs/torch/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3953, in _quantile_ureduce_func
    r = add(x1, x2, out=out)
ValueError: non-broadcastable output operand with shape (2,1,4) doesn't match the broadcast shape (2,2,4)

### Expected:

Running the same code without providing out argument shows that the result has shape (2,1,4). Also note that running the following code snippet does work even though the dimensions are not correct.

```python
import numpy as np
np.quantile(np.random.randn(2, 4), [0.5, 0.7], axis=0, keepdims=True, out=np.ndarray((2, 4)))
```

### Numpy/Python version information:

1.18.1 3.8.3 (default, May 19 2020, 13:54:14) 
[Clang 10.0.0 ]

**Comment by sarthakchaudhary13** [comment]
Hello @seberg, I was trying to figure this one out and I traced the error is due to *out parameter* in *add function* from `_multiarray_umath` when called in `_lerp` from `numpy/lib/function_base.py`, see below.
```
    lerp_interpolation = asanyarray(add(a, diff_b_a*t, out=out))
```
If I remove *out parameter* and add `if statement` on `lerp_interpolation` to reshape if *out parameter* is passed the error is gone 
- Output
```
import numpy as np
np.quantile(np.random.randn(2, 4), [0.5, 0.7], axis=0, keepdims=True, out=np.ndarray((2, 1, 4)))

>>> array([[[-0.12024295,  0.46587341,  0.06791209, -0.67760114]],

       [[-0.09585494,  0.91001616,  0.58532174, -0.65120728]]])
```
am I on the right track?

**Comment by seberg** [comment]
@sarthakchaudhary13 the bug is actually in `_quantile_unchecked` (and we probably need to double check other functions using the `_ureduce` pattern.

**Comment by seberg** [comment]
`out` handling in quantiles and related was fixed (don't quite remember how long ago).
