### ISSUE TITLE
Scalars are returned when passing 0D arrays to `out`

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#16734]
While adding type hints to `numpy.core.fromnumeric` (https://github.com/numpy/numpy/pull/16729) some inconsistent behavior was observed for many function when an `ndarray` was provided to the `out` parameter (_e.g._ [amax](https://numpy.org/doc/stable/reference/generated/numpy.amax.html#numpy.amax)). 

Generally speaking when an array is provided to `out` it is modified inplace and returned, yet an exception to this rule was observed when passing a `generic`, in which case a `generic` was returned rather than the passed `ndarray`. 
As can be seen in the example below, this behavior is limited to `generic`. Builtin scalars, sequences and numpy arrays all return the `ndarray` specified in `out`.

A (potentially incomplete) list of known affected functions:
* `take()`
* `choose()`
* `argmax()`
* `argmin()`
* `clip()`
* `sum()`
* `all()`
* `any()`
* `ptp()`
* `amax()`
* `amin()`
* `prod()`
* `around()`
* `mean()`
* `std()`
* `var()`

### Reproducing code example:

```python
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.20.0.dev0+5a42440'

In [3]: out = np.zeros((), dtype='int32')

In [4]: np.sum(0, out=out)  # Builtin scalar
Out[4]: array(0)

In [5]: np.sum(np.int64(0), out=out)  # generic
Out[5]: 0

In [6]: np.sum(np.int64(0), out=out).__class__  # It seems like `out.take(0)` is called and returned?
Out[6]: numpy.int32

In [7]: np.sum([0], out=out)  # Builtin sequence
Out[7]: array(0)

In [8]: np.sum(np.zeros(1), out=out)  # ndarray
Out[8]: array(0)
```

### Error message:

Not applicable

### Numpy/Python version information:

* NumPy version: `1.20.0.dev0+62f26cf` 
* Python version(s): `3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:21:09) \n[Clang 9.0.1 ]`

**Comment by BvB93** [comment]
What seems to be happening here is that not even the `out` parameter is immune to automatic 0d -> scalar conveversions.

**Comment by BvB93** [comment]
> What seems to be happening here is that not even the out parameter is immune to automatic 0d -> scalar conversions.

I would say that this is might be one of the more problematic cases involving 0d -> scalar casts,
as it means `out is func(..., out=out)` is not guaranteed to hold.

**Comment by seberg** [comment]
Going to close, since I assume gh-25409 is going in any moment and it fixes this.
