### ISSUE TITLE
Is numpy safe to use with overlapping inputs and output?

### ISSUE THREAD

**Issue by skoehler** [numpy/numpy#16749]
I fail to find the part of the documentation that would state that numpy is always safe to use with overlapping inputs and outputs. In particular, I cannot be sure right now,  whether I'm using numpy in a safe way. For example, `numpy.subtract` does not even mention the overlapping issue.

Consider the following code (which assumes that `d` is a numpy array).
```python
d[1:] -= d[:-1]
np.subtract(d[1:], d[:-1], out=d[1:])
```
My hope would be that both is equivalent to
```python
...
d[9] -= d[8]
d[8] -= d[7]
d[7] -= d[6]
d[6] -= d[5]
...
```

As you can see, this only works if the subtraction is done from back to front for two reasons:
- the value of d[i-1] must not be changed before d[i-1] is subtracted from d[i]
- the result is written back to d[i]

One can imagine where the subtraction can only be done front to back, for example.
```python
np.subtract(d[1:], d[:-1], out=d[:-1])
```

Is numpy safe to use in such situations? Is the subtraction performed in-place?
Where is the documentation of that issue?

Maybe there is even a combination of overlapping inputs and outputs that cannot work, no matter the direction?

**Comment by pv** [comment]
It does not appear to be stated in the documentation, but see
https://numpy.org/doc/stable/release/1.13.0-notes.html#ufunc-behavior-for-overlapping-inputs

**Comment by skoehler** [comment]
First of all, thank you for pointing me to some source of information. I should probably check the numpy version in my script.

I'd really like to see documentation about this issue. I'm dealing with arrays with gigabytes of data here. Automatically created copies will increase the memory consumption of my script dramatically. At least, I should know when copies are created. For example, does numpy have both algorithms, namely one that works from back to front and one that works from front to back? If not, I would probably have to think about revising my algorithm so that no automatic copies are created. I currently don't see a way to disable automatically created copies.

In particular, I'm still wondering whether `d[1:]-=d[:-1]` or `d[:-1] -= d[1:]` are done in-place or not.

**Comment by pv** [comment]
Whether copies are created is an implementation detail. If this is an issue, you'll probably need to assume that they are created if there is overlap.

**Comment by rossbar** [comment]
Coincidentally, I recently noticed a related bit of outdated documentation over in scipy-lectures/scipy-lecture-notes#486. It might be good to add something about this to e.g. the user/reference documentation to increase visibility.
