### ISSUE TITLE
Document ndindex(shape)

### ISSUE THREAD

**Issue by inducer** [numpy/numpy#16745]
This usage of `ndindex`:
```
>>> list(np.ndindex((3,2)))
[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1)]
```
seems to work with 
```
>>> np.__version__
'1.18.4'
```
but it's not [documented](https://numpy.org/doc/stable/reference/generated/numpy.ndindex.html). Is this usage intended to be allowed? (I'd like it to be, because if `shape == 5` then `np.index(shape)` works while `np.ndindex(*shape)` does not.) If it is, could it be added to the docs?

**Comment by seberg** [comment]
We may want to make that version the preferred documented one, and just briefly mention the other option as well.  In most cases (e.g. also `arr.reshape()` where we allow both, we prefer the tuple-version in the docs).

**Comment by rossbar** [comment]
Just to clarify this a bit - I think there are two things that make the `np.ndindex` docstring confusing:
 1. The signature of the `np.ndindex` docstring is inconsistent with the Parameters listing
 2. Additionally, the type listing in the Parameters section is incorrect: both tuples and list of ints are allowed.

**Comment by rohitsanj** [comment]
> Additionally, the type listing in the Parameters section is incorrect: both tuples and list of ints are allowed.

Hey @rossbar, I tried to pass a list of ints but I got the following error. Am I missing something here?

```python
>>> list(np.ndindex([1, 2]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rohitsanjay/numpy/numpy/lib/index_tricks.py", line 650, in __init__
    strides=_nx.zeros_like(shape))
  File "/Users/rohitsanjay/numpy/numpy/lib/stride_tricks.py", line 101, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "/Users/rohitsanjay/numpy/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: 'list' object cannot be interpreted as an integer
```
