### ISSUE TITLE
numpy.random.RandomState.choice produces different results when p is None versus p given equal proabilities 

### ISSUE THREAD

**Issue by hermidalc** [numpy/numpy#16766]
`numpy.random.RandomState.choice`, which e.g. pandas and other major libraries still use, unexpectedly produces different results when `p=None` versus setting p to a list of equal probabilities, is this intentional?

### Reproducing code example:

```python
import numpy as np

aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']

rng = np.random.RandomState(777)
for _ in range(10):
    print(rng.choice(aa_milne_arr))
```
```
Christopher
Christopher
Christopher
piglet
Christopher
rabbit
Christopher
rabbit
Christopher
pooh
```
```python
rng = np.random.RandomState(777)
for _ in range(10):
    print(rng.choice(aa_milne_arr, p=[0.25] * 4))
```
```
pooh
rabbit
pooh
rabbit
Christopher
Christopher
piglet
Christopher
rabbit
piglet
```

### Numpy/Python version information:

1.18.5 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) [GCC 7.5.0]

**Comment by rkern** [comment]
Yes, two different codepaths. `p=None` doesn't generate equal probabilities and then use the same weighted-sampling codepath.

**Comment by hermidalc** [comment]
> Yes, two different codepaths. `p=None` doesn't generate equal probabilities and then use the same weighted-sampling codepath.

Wouldn't it make sense that they should produce the same results?

**Comment by rkern** [comment]
Weighted sampling (even when all of the weights are even) is slower, more complicated, and subject to a tiny bit more error than unweighted sampling. They are two different approaches to sampling, so the two codepaths aren't going to reproduce the same sequence in detail even in the case that the weights are even. The speed increase with the `p=None` codepath is worth the difference. In general, we expect that people using `p=something_not_none` are almost always using uneven weights, so I don't think it's worth checking the `p` for evenness (and risk a certain amount of error) to use the `p=None` codepath. You usually have to apply specific effort to create the even weights (it rarely happens by accident), so you can just use `p=None` in those cases.
