### ISSUE TITLE
Speed up trim_zeros

### ISSUE THREAD

**Issue by jonashaag** [numpy/numpy#16783]
```py
a = np.hstack([
    np.zeros((100_000,)),
    np.random.uniform(size=(100_000,)),
    np.zeros((100_000,)),
])
trim_zeros(a)
```

Here the call to `trim_zeros` takes about 50ms.

Looking at the implementation of `trim_zeros`, it is implemented in the most obvious and unoptimized way imaginable (a for loop looking at each item separately).

I think there should be a warning in the documentation about the fact that it's entirely unoptimized and may be horrendously slow, or we should strive to improve performance.

As an implementation idea to improve performance, I prototyped a "block-wise" trim function to be used before `trim_zeros`:

```py
def fast_trim_zeros(filt, trim='fb'):
    filt = trim_zeros_block(filt, trim)
    return np.trim_zeros(filt, trim)


def trim_zeros_block(filt, trim='fb', block_size=1024):
    """Trim blocks of zeros"""
    trim = trim.upper()
    first = 0
    if 'F' in trim:
        for i in range(0, len(filt), block_size):
            if np.any(filt[i:i+block_size] != 0.):
                first = i
                break
    last = len(filt)
    if 'B' in trim:
        for i in range(len(filt)-1, block_size - 1, -block_size):
            if np.any(filt[i-block_size:i] != 0.):
                last = i
                break
    return filt[first:last]
```

Speed of a call to `fast_trim_zeros` is about 2ms, so roughly 25x as fast.

**Comment by Qiyu8** [comment]
Good to hear that, can you provide a pull request and corresponding benchmark test case?

**Comment by jonashaag** [comment]
Are you saying that I should submit a PR with benchmark code or also with the code I suggested above? If the latter, there are probably hundreds of ways to implement it and the code above is just the first thing that came to my mind; so why use exactly that code?

**Comment by BvB93** [comment]
> As an implementation idea to improve performance, I prototyped a "block-wise" trim function to be used before `trim_zeros`

How about converting the passed object into a boolean array and then use `np.argmax()` to find the first/last non-zero element?
With your previously defined example array I'm seeing an increase in execution speed of ~2 orders of magnitude (398 µs versus 37 ms).

```python
import numpy as np

def trim_zeros(filt, trim='fb'):
    a = np.asanyarray(filt, dtype=bool)
    if a.ndim != 1:
        raise ValueError('trim_zeros requires an array of exactly one dimension')

    trim_upper = trim.upper()
    len_a = len(a)
    i = j = None
    
    if 'F' in trim_upper:
        i = a.argmax()
        if not a[i]:  # i.e. all elements of `filt` evaluate to `False`
            return filt[len_a:]

    if 'B' in trim_upper:
        j = len_a - a[::-1].argmax()
        if not a[j]:  # i.e. all elements of `filt` evaluate to `False`
            return filt[len_a:]

    return filt[i:j]
```

**Comment by eric-wieser** [comment]
Does that code work without the `if`s?

**Comment by BvB93** [comment]
> Does that code work without the `if not ...s`?

Without the `if not ...` it will fail if the input array consists entirely of zeros, 
in which case `argmax()` will always return 0 and thus the `filt[i:j] == filt`.

```python
>>> import numpy as np

>>> a = np.zeros(10, dtype=bool)
>>> i = a.argmax()
>>> j = len(a) - a[::-1].argmax()

>>> print(i, j)
0, 10

>>> print(np.all(a == a[i:j]))  # Uhoh, `a` is not being trimmed
True
```

**Comment by BvB93** [comment]
Another option is to check with `np.any()` right at the beginning, though this appears to be a bit slower.

**Comment by eric-wieser** [comment]
> in which case `argmax()` will always return 0

Ah, I thought it might return `len(a) - 1`

**Comment by BvB93** [comment]
Shall I create a pull request with the implementation as proposed above?

**Comment by BvB93** [comment]
I've just created a pull request for the issue at https://github.com/numpy/numpy/pull/16911.
