### ISSUE TITLE
ufunc doc not in html build ? 

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy#16791]
It seem the docstring of "ufunc" is not in the html build of the docs:

```
In [5]: from numpy import ufunc

In [6]: 'whole array' in ufunc.__doc__
Out[6]: True
```

If I grep the html build for "whole array" there is no results...

ufunc doc is set in `numpy/core/_add_newdocs.py`, like other things so there is no reason for it not to be built, it likely miss a entry in generated API ? Am I really bad at searching ? Or maybe that's on purpose.

**Comment by rossbar** [comment]
> Am I really bad at searching ?

Nope, this does indeed seem to be the case.

I can't imagine why it would be left out on purpose, it's likely an oversight or perhaps an autodoc/autosummary is improperly configured somewhere. Note that all the internal links to `` :class:`ufunc` `` are indeed broken.

**Comment by Carreau** [comment]
> Nope, this does indeed seem to be the case.

Thanks ! I don't know if it matters but it's also one of the only non-module that have both , `-`  and `=` title.

**Comment by rossbar** [comment]
Yeah that `Calling ufuncs` section heading trips up `numpydoc` parsing. Not a huge deal but also not a no-brainer fix either.

**Comment by melissawm** [comment]
As a workaround, can we use `-` for the `Calling ufuncs` header for now? Just so the documentation is not missing.

**Comment by rossbar** [comment]
Using a different style heading wouldn't work I don't think, as numpydoc would still trip on any non-recognized heading name. One workaround that should work is replacing

```
Calling ufuncs
==============
```
with 
```
**Calling ufuncs**
```
