### ISSUE TITLE
Importing the numpy c-extensions failed in Jupyter Notebook

### ISSUE THREAD

**Issue by JohnsonWhitney** [numpy/numpy#16799]
I'm trying to run the code below in Jupyter Notebook and got this error message below. I've already uninstall and reinstalled numpy. It says to look at PATH and PYTHONPATH, and after that says to make an Issue here, so that's what I've done.

It's my first time asking about an Issue here so thank you for your patience and let me know if I should have done something differently.

Thank you in advance for your help. 
Sincerely,
Matt
matt.johnson@abcusd.us

Now though, let me make clear what I saw with that path step in case I'm not understanding something:

Code to check PATH:
 import sys
 for p in sys.path:
      print(p)

Gives me this:
C:\Users\matha\anaconda3\envs\genCPU\python36.zip
C:\Users\matha\anaconda3\envs\genCPU\DLLs
C:\Users\matha\anaconda3\envs\genCPU\lib
C:\Users\matha\anaconda3\envs\genCPU
C:\Users\matha\anaconda3\envs\genCPU\lib\site-packages
C:\Users\matha\anaconda3\envs\genCPU\lib\site-packages\win32
C:\Users\matha\anaconda3\envs\genCPU\lib\site-packages\win32\lib
C:\Users\matha\anaconda3\envs\genCPU\lib\site-packages\Pythonwin

I'm expecting to use 3.6 in this environment so it looks fine to me:

Code to check PYTHONPATH (which I don't think I have):

import os
try:
    user_paths = os.environ['PYTHONPATH'].split(os.pathsep)
except KeyError:
    user_paths = []

### Reproducing code example:

```python
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.layers import Input, Flatten, Dense, Conv2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

from tensorflow.keras.datasets import cifar10
```

### Error message:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\anaconda3\envs\genCPU\lib\site-packages\numpy\core\__init__.py in <module>
     16 try:
---> 17     from . import multiarray
     18 except ImportError as exc:

~\anaconda3\envs\genCPU\lib\site-packages\numpy\core\multiarray.py in <module>
     13 
---> 14 from . import overrides
     15 from . import _multiarray_umath

~\anaconda3\envs\genCPU\lib\site-packages\numpy\core\overrides.py in <module>
      6 
----> 7 from numpy.core._multiarray_umath import (
      8     add_docstring, implement_array_function, _get_implementing_args)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-168b3dcea40e> in <module>
----> 1 import numpy as np
      2 import matplotlib.pyplot as plt
      3 
      4 from tensorflow.keras.layers import Input, Flatten, Dense, Conv2D
      5 from tensorflow.keras.models import Model

~\anaconda3\envs\genCPU\lib\site-packages\numpy\__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~\anaconda3\envs\genCPU\lib\site-packages\numpy\core\__init__.py in <module>
     45 """ % (sys.version_info[0], sys.version_info[1], sys.executable,
     46         __version__, exc)
---> 47     raise ImportError(msg)
     48 finally:
     49     for envkey in env_added:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "C:\Users\matha\anaconda3\envs\genCPU\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
### Numpy/Python version information:

1.17.2 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]

**Comment by rossbar** [comment]
@JohnsonWhitney please take a look at the article on [troubleshooting this error](https://numpy.org/devdocs/user/troubleshooting-importerror.html) to see if you find any of the suggestions there helpful.

**Comment by JohnsonWhitney** [comment]
> @JohnsonWhitney please take a look at the article on [troubleshooting this error](https://numpy.org/devdocs/user/troubleshooting-importerror.html) to see if you find any of the suggestions there helpful.

Thank you, still no luck. I don't believe most of those things apply to me (as to be expected), but tried the numpy uninstall and confirmed that it was uninstalled before I reinstall.

It also gives code to run for versions and asks for other things, I'll post here:

>>> import os
>>> print("PYTHONPATH:", os.environ.get('PYTHONPATH'))
PYTHONPATH: None
>>> print("PATH:", os.environ.get('PATH'))
PATH: C:\Users\matha\anaconda3\envs\genCPU;C:\Users\matha\anaconda3\envs\genCPU\Library\mingw-w64\bin;C:\Users\matha\anaconda3\envs\genCPU\Library\usr\bin;C:\Users\matha\anaconda3\envs\genCPU\Library\bin;C:\Users\matha\anaconda3\envs\genCPU\Scripts;C:\Users\matha\anaconda3\envs\genCPU\bin;C:\Users\matha\anaconda3\condabin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Git\cmd;C:\Users\matha\AppData\Local\Microsoft\WindowsApps;.

How installed Python:  With Anaconda
Created environment with: conda create -n genCPU python=3.6 ipykernel
How installed NumPy: conda install numpy=1.17.2

Note: These versions were specified from the book I'm using (https://github.com/davidADSP/GDL_code). Originally I didn't specify the older version of numpy and ran into a bug asking me to check on versions. I then specified the version the author says and got the bug reported above.

I'm on Windows 10 Home.

I do have Python 3.7 on my machine as well, but this environment is 3.6, and the kernel is connected to the correct environment.

I'm trying to get code working from the aforementioned book and thus it's not my own code. I intend to reach out to the author if it looks like there's actually a problem with his code, but the thing I ran seems like it's really too basic to actually be the problem.

Thanks again,
Matt

**Comment by rossbar** [comment]
Hmm, are you activating the genCPU conda environment after it's been created (e.g. `conda activate genCPU`)? I'm not a frequent `conda` user so I'm not sure if it automatically enters environments after creation.

**Comment by JohnsonWhitney** [comment]
> Hmm, are you activating the genCPU conda environment after it's been created (e.g. `conda activate genCPU`)? I'm not a frequent `conda` user so I'm not sure if it automatically enters environments after creation.

I'm selecting the environment within Jupyter Notebook, which is how I've used it before. I don't think I've changed anything in that process so I doubt it's the problem, but if you'd like to give me a recipe to follow, I'll try to follow it.

**Comment by rossbar** [comment]
Does everything work outside of Jupyter notebook, e.g. in the terminal or an IPython session? I'm not aware of how you select conda environments from within Jupyter notebooks so unfortunately I don't have any simple procedure to follow.

**Comment by JohnsonWhitney** [comment]
> Does everything work outside of Jupyter notebook, e.g. in the terminal or an IPython session? I'm not aware of how you select conda environments from within Jupyter notebooks so unfortunately I don't have any simple procedure to follow.

Y'know what? This led me to the answer though I'm still confused as to what was going on.

When I tried to run outside of this environment it wasn't working their either and realized that there were libraries (most notably NumPy) that I had only installed within my virtual environment. Once I got it working in my base environment I tried again in Jupyter Notebook and it worked.

So to me the weird thing is that it appears that even though Jupyter said it was in the intended environment, and even though the libraries the code demanded were installed in that environment, it still needed the libraries implemented in my base environment. That doesn't make a lot of sense to me, but I will note one other thing:

I set up Jupyter Notebook through the base environment. Perhaps, even though I specified a different environment, it still needs the libraries to be implemented in the base? I don't know and welcome any thoughts on the subject.

I want to thank you for being so prompt in giving me advice rossbar. I appreciate it a great deal.

I apologize if you feel I wasted your time with something I should have figured out on my own. Sometimes it just feels like I've gone in circles several times having tried everything...but clearly that wasn't quite true. Thanks for understanding.

Sincerely,,
Matt

**Comment by rossbar** [comment]
> I apologize if you feel I wasted your time with something I should have figured out on my own.

Definitely not! Issues installing/setting up are very common, and it's usually pretty hard to track down where the problem lies. I don't recall the specific issue numbers, but I know this is not the first time that users have had situations where something worked in the notebook but not in the terminal (or vice versa). If you have any tips/steps from how you managed to resolve this issue that you think might be general and perhaps useful to others, please don't hesitate to create a PR to add the info to the [troubleshooting doc (source link)](https://github.com/numpy/numpy/blob/master/doc/source/user/troubleshooting-importerror.rst)!
