### ISSUE TITLE
+= Operator on list of indices - unexpected behaviour

### ISSUE THREAD

**Issue by mishana** [numpy/numpy#16790]
Hi, I stumbled upon an interesting and unexpected (to me) behaviour when using the `+=` operator on a `np.ndarray`:

```python
import numpy as np

a = np.zeros(3)

indices = [0, 0, 1, 1, 2]
a[indices] += 1
```
The thing is, knowing that `+=` avoids creating copies and that slicing also creates views and not copies, I would expect this to add 2 to `a[0]`, 2 to `a[1]` and 1 to `a[2]`. Instead I witness the following:

```python
>>> a
array([1., 1., 1.])
```

Is this a bug? If not, can you please explain this?

Thanks,
Michael

**Comment by eric-wieser** [comment]
`np.add.at` has the behavior you're after.

**Comment by rossbar** [comment]
> slicing also creates views and not copies

Note in the above example, `a[indices]` is an instance of [advanced indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing) which *does* create copies:

```python
>>> b = a[indices]
>>> b.base is a
False
```

**Comment by mishana** [comment]
> > slicing also creates views and not copies
> 
> Note in the above example, `a[indices]` is an instance of [advanced indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing) which _does_ create copies:
> 
> ```python
> >>> b = a[indices]
> >>> b.base is a
> False
> ```

Oh didn't know it's a thing. Thanks :)

**Comment by mishana** [comment]
Interestingly though, `np.add.at` seems much slower.
For example:

```python
import numpy as np

indices = np.arange(1000)
a = np.random.random(size=(1000, 1000))

%timeit np.add.at(a, (indices, indices), 1)
91.4 µs ± 2.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit a[indices, indices] += 1
16.2 µs ± 152 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

**Comment by eric-wieser** [comment]
Ah, therein lies your problem.
```
a[i] += b
```
is interpreted by python as
```python
c = a[i]
c += b
a[i] = c
```
This last line doesn't know how repeated indices should be handled.

**Comment by eric-wieser** [comment]
@mishana: performance differences aren't really relevant when one of your options doesn't work ;)

**Comment by seberg** [comment]
`ufunc.at` is famously slow and should be improved (it basically always had been).  For `np.add` in particular, `np.bincount` should normally be faster, and maybe also a bit easier to grasp.

**Comment by mishana** [comment]
> @mishana: performance differences aren't really relevant when one of your options doesn't work ;)

Well in this case it is relevant, since the indices are unique and they basically produce the same result.

**Comment by mishana** [comment]
> Thanks for the reminder about the copy being created - therein lies your problem.
> 
> ```
> a[i] += b
> ```
> 
> is interpreted by python as
> 
> ```python
> c = a[i]
> c += b
> a[i] = c
> ```
> 
> This last line doesn't know how repeated indices should be handled, as nothing indicates a + operation occurred

Interesting, for some reason I thought the operator is fully overriden in numpy at the C level. It does seem logical now :)

**Comment by eric-wieser** [comment]
Numpy overloads step 2 in a way that uses less memory that `c = c + b`, but python provides no way to overload the combined indexing and augmented assignment.
