### ISSUE TITLE
dynamic module does not define module export function (PyInit_multiarray) in pyodide

### ISSUE THREAD

**Issue by rth** [numpy/numpy#16804]
Numpy 1.15.4 is built in [pyodide](https://github.com/iodide-project/pyodide), and you can try it in a [REPL here](https://pyodide-cdn2.iodide.io/latest/full/console.html). Currently it uses the  
version 1.38.31 of the [emscripten toolchain](https://emscripten.org/) to build to WebAssembly and that mostly works fine. However if I update it emscripten to 1.38.34 in https://github.com/iodide-project/pyodide/pull/480 I get,
```
ImportError: dynamic module does not define module export function (PyInit_multiarray)
```
at import time. The rest of the scientific python packages seems to build fine as far as I can tell (but none can be imported due to the dependency on numpy).

I have read https://numpy.org/doc/stable/user/troubleshooting-importerror.html and some of the similar open issues. 

I understand it might be a bit off topic, but I'm looking for advice on things to try to debug this. For instance, do you think updating the numpy version might help? I can also provide a link to a REPL with the version that fails if it helps.

I would also be available to chat about it as part of the scipy2020 sprint. 

### Reproducing code example:

```python
import numpy as np
```

### Error message:

```
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dynamic module does not define module export function (PyInit_multiarray)
```

### Numpy/Python version information:

Python 3.8.2
Numpy 1.15.4

**Comment by dalcde** [comment]
This should be closed since it is determined to not be a numpy issue, but an issue with emscripten's dynamic loading library.

**Comment by rth** [comment]
Yes, indeed, thank you @dalcde !
