### ISSUE TITLE
Custom array containers lose memoryview functionality

### ISSUE THREAD

**Issue by mdehoon** [numpy/numpy#16803]
The section "Writing custom array containers" in the numpy documentation describes how to write custom N-dimensional arrays that are compatible with the numpy API. Trying the example in this section, however, revealed that the custom array does not support `memoryview`, while numpy's `ndarray` does. Therefore, when passing the custom array to a C-extension module, the buffer protocol cannot be used.

### Reproducing code example:

This is the example from the numpy documentation:
```python
>>> import numpy as np
>>> class DiagonalArray:
...     def __init__(self, N, value):
...         self._N = N
...         self._i = value
...     def __repr__(self):
...         return f"{self.__class__.__name__}(N={self._N}, value={self._i})"
...     def __array__(self):
...         return self._i * np.eye(self._N)
... 
```
Create an instance:
```python
>>> a = DiagonalArray(5, 1)
```
Then call `memoryview`:
```python
>>> memoryview(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: memoryview: a bytes-like object is required, not 'DiagonalArray'
```

Compare this with a regular numpy array, which does support `memoryview`:
```python
>>> b = np.eye(5)
>>> memoryview(b)
<memory at 0x7fb59fea6040>
```

Note that *subclassing* a numpy array retains the memoryview functionality. Using the example from the section "Subclassing ndarray" from the numpy documentation:
```python
>>> import numpy as np
>>> class C(np.ndarray): pass
>>> c = C([5, 5])
>>> memoryview(c)
<memory at 0x7fb59fea6040>
```
and therefore the buffer protocol can be used on the `c` object when passed to a C extension module.

If I understand correctly, the dispatch mechanism is recommended as a replacement for subclassing a numpy array. If so, memoryviews and the buffer protocol should be supported, as this is very important for their efficient use in C extension modules.

One option would be to subclass from a `memoryview` as follows:
```python
>>> class D(memoryview):
...    def __new__(cls, value):
...        self = memoryview.__new__(cls)
...        self.obj = value
...        return self
```
where `value` is a numpy array. However, unfortunately `memoryview` does not support subclassing.

### Numpy/Python version information:

1.18.1 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
[Clang 6.0 (clang-600.0.57)]

**Comment by seberg** [comment]
Unfortunately, this is something that Python does not really make easy or even support, its possible we should create a Python issue about it.  If you define your object in C (at least a small chunk of it), you could implement it fairly easily as a fallback to call the buffer implementation of the contained array.  But, the buffer protocol is C-level only, so I can show you how to create a minimal object with a `data` attribute or so (which holds the numpy array to be exported), which then can be subclasses to add whatever other things you like.

**Comment by mdehoon** [comment]
@seberg  Thank you. Yes, some C code to glue the Python side and the numpy side would work, but it feels like a kludge. Also, this is for a open-source project where few of the developers are comfortable writing C extension code, so it would be difficult to maintain. Then if subclassing does not require C code while wrapping does, we are better of with subclassing.

If Python were to support subclassing of `memoryview`, then I think the issue could be solved. But before we go that route, let's think a bit if there is some solution in numpy.

For example, what if we make use of `tp_base` to define an (abstract) base class that exposes the buffer protocol but nothing else. Users could then create a subclass of the abstract base class (which gives them the buffer protocol); `ndarray` would be a subclass of the same abstract base class, and subclassing `ndarray` could be disallowed.

I am still trying to understand why exactly subclassing `ndarray` is problematic, in particular up to what point subclassing is safe, and which features of `ndarray` would cause a problem.

I would be happy to discuss and try other options.

**Comment by mattip** [comment]
PyPy exposes the `__buffer__` attribute on [PyPy-specific `__pypy__.bufferable`](https://doc.pypy.org/en/latest/__pypy__-module.html#generally-available-functionality) classes which I think does what you want. It would not be too hard to write a CPython class that does this too.

**Comment by mdehoon** [comment]
Cross-reference https://bugs.python.org/issue13797 for a previous discussion related to this issue. Being able to subclass `memoryview` on the Python side seems non-trivial.

**Comment by seberg** [comment]
A few projects, such as `pandas` or `xarray` (probably also `dask.array`), seem to do OK with requiring users to use `.values` or so when the user tries to run a fast cython function or similar.

I am really not sure how to interpret your DiagonalArray example, because I assume that is close to the actual use-case here.  A diagonal array does not have a low-level buffer in a very useful way. You would have to create one every time on access (bloating up memory a lot).  And most sparse libraries usually prefer that "densifying" does not happen silently.  Which means they prefer to provide some method/attribute similar to `dataframe.values`, etc.

I do think making a very thin subclass which supports a `__buffer__` method like PyPy (or something similar, but faster, like a special `.data` attribute), is not hard.  And I will agree that this is something that Python should maybe get better at.  But right now I am not actually sure where to push Python.  (I do think we probably _could_ push Python somewhere here, we just have to figure out what is the right thing to do.  After all,  it is this community that pushed for the buffer protocol in the first place, even if few of those are still around.)

**Comment by mdehoon** [comment]
@seberg  The `DiagonalArray` example was taken from the numpy documentation. My own use case is much simpler.

**Comment by eric-wieser** [comment]
> But right now I am not actually sure where to push Python. (I do think we probably _could_ push Python somewhere here, we just have to figure out what is the right thing to do. After all, it is this community that pushed for the buffer protocol in the first place, even if few of those are still around.)

I can think of two fairly simple fixes to this problem:

* Implement lookups on `__buffer__` as you suggest, with semantics "return an existing buffer". I suppose the slightly complication here is keeping the wrapping object alive with it's buffer, but maybe that isn't necessary
* Publish a standalone package on PyPI providing a base class which implements `tp_buffer` as delegating to `__buffer__`. This will cause a bit of pain for metaclass users, but will make things easy for everyone else.

**Comment by seberg** [comment]
@eric-wieser right, the standalone package would be pretty straight forward, I think. Metaclasses may be an issue, but in the end not super common.

I agree with the fact that interest in the buffer protocol is low (or lets say, similar to the typical NumPy problem, hesitation in the face of tricky situation; i.e. momentum and willigness to risk and change).  It is indeed worry-some that even a PR that has been created and approved by two numpy people (and even got some review from Stefan Krah), got stuck.  Lets try to give a ping there...

**Comment by mdehoon** [comment]
Could somebody help me trying to understand why subclassing a numpy array is discouraged? I am wondering which problem could actually occur, and why wrapping a numpy array is safe.

**Comment by seberg** [comment]
Going to close, the main part of this was never numpy issue.  FWIW, python is adding `__buffer__` now, I think.
