### ISSUE TITLE
BUG: np.array unsafely clips/casts integers if dtype is given (Trac #1083)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1681]
_Original ticket http://projects.scipy.org/numpy/ticket/1083 on 2009-04-11 by @inducer, assigned to unknown._

> > > numpy.array([324938], dtype=numpy.uint8)
> > > array([74], dtype=uint8)

Errors should never pass silently.
Unless explicitly silenced.

**Comment by seberg** [comment]
This may (in a way) be related to the integer overflow issues (e.g. gh-5657), it is a bit annoying that for the default integer dtype coercion fails (C `long` dtype, or maybe 64bit), so in that case an error is actually given.

**Comment by seberg** [comment]
There is a deprecation currently in place for converting out of bound *python* integers (not other integers).

There is the second issue here about allowing more general unsafe casts. But we have at least one issue about that at gh-8733.
