### ISSUE TITLE
linspace should round towards -infinity

### ISSUE THREAD

**Issue by skoehler** [numpy/numpy#16813]
Take a look at the following:

````
>>> np.linspace(0,10,num=50,endpoint=False,dtype=np.int32)
array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8,
       8, 9, 9, 9, 9, 9], dtype=int32)
>>> np.linspace(-1,9,num=50,endpoint=False,dtype=np.int32)
array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,
        2,  2,  2,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8],
      dtype=int32)
````

As you can see, linspace creates a nice linear integer case in the first case. Note so much if the starting point is negative. IMHO, linspace should round towards -infinity when negative numbers are involved.

As a workaround, one can use the following which has the desired output:
````
>>> np.linspace(0,10,num=50,endpoint=False,dtype=np.int32)-1
array([-1, -1, -1, -1, -1,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,
        2,  2,  2,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8],
      dtype=int32)
````

**Comment by marload** [comment]
`np.linspace` casts values using `astype`

In other words, -0.2 is cast as an integer and becomes 0.
This seems to be the expected result.

But I think `linspace` should work the way you suggested.

**Comment by mattip** [comment]
Fixed in #16841

**Comment by degasus** [comment]
Hi, may I ask about your opinion for rounding towards `start` instead of towards `-inf`? Or towards `inf * (start - stop)`.

Within this issue report, I just see arguments against towards zero, and I agree on this discussion.

However, what I do not like about `-inf` is that `linspace(A,B) != -linspace(-A, -B)`. To fullfill this constraint, rounding towards `nearest` or towards `start` would be fine, without breaking the initial request `linspace(A, B) + C == linspace(A + C, B + C)`.

**Comment by skoehler** [comment]
I never considered decreasing sequences. The output below shows, that numpy seems to violate its own documentation. I set endpoint to False, but -10 is included. Rounding towards `A<B ? -inf : inf`, i.e., towards `A`, seems to be the right thing to do.

```
>>> np.linspace(0,10,num=50,endpoint=False,dtype=np.int32)
array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8,
       8, 9, 9, 9, 9, 9], dtype=int32)
>>> np.linspace(0,-10,num=50,endpoint=False,dtype=np.int32)
array([  0,  -1,  -1,  -1,  -1,  -1,  -2,  -2,  -2,  -2,  -2,  -3,  -3,
        -3,  -3,  -3,  -4,  -4,  -4,  -4,  -4,  -5,  -5,  -5,  -5,  -5,
        -6,  -6,  -6,  -6,  -6,  -7,  -7,  -7,  -7,  -7,  -8,  -8,  -8,
        -8,  -8,  -9,  -9,  -9,  -9,  -9, -10, -10, -10, -10], dtype=int32)
```

**Comment by degasus** [comment]
> I never considered decreasing sequences. The output below shows, that numpy seems to violate its own documentation. I set endpoint to False, but -10 is included. Rounding towards `A<B ? -inf : inf`, i.e., towards `A`, seems to be the right thing to do.

I've created a patch for it: https://github.com/numpy/numpy/pull/29295 -- let's see if this fix is worth a modified behavior
