### ISSUE TITLE
binomial can return unitialized integers when `size` is passed with array values for `a` or `p`

### ISSUE THREAD

**Issue by rwalk** [numpy/numpy#16833]
Array values for `a` and for `p` can give strange results when combined with `size`. In particular, it seems like `binomial` can return uninitialized integers (indeterminate values based on what's sitting in memory at the time).

### Reproducing code example:

```python
import numpy as np
import gc
from numpy.random import binomial, seed

seed(2)
for i in range(3):
    print("Run number: {}".format(i) )
    print(binomial(1, [0.3, 0.7], size=(2,1)))
    
# Run number: 0
# [[              1]
#  [139987954384792]]
# Run number: 1
# [[                  1]
#  [4604480259023595110]]
# Run number: 2
# [[                  1]
#  [4604480259023595110]]
```
### Numpy/Python version information:
I'm running python 3.8.2 on ubuntu 20.20 
```
1.19.0 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
```

**Comment by rossbar** [comment]
This behavior is present in the Generator binomial method as well. MRE:

```python
>>> rg = np.random.default_rng(5194367163)
>>> rg.binomial(1, [0.3, 0.7], size=(2, 1))
array([[                  1],
       [4604480259023595110]])
```

**Comment by bashtage** [comment]
It is another instance of #16503.  Need to make another pass since there are a few in the main Generator that not in the of the helper functions in common.

**Comment by bashtage** [comment]
This should raise since (2,) and (2,1) broadcast to a size different than (2,1).
