### ISSUE TITLE
numpy.core._multiarray_umath' error when trying to access numpy from a Windows app.

### ISSUE THREAD

**Issue by caprianil-fsc** [numpy/numpy#16864]
I was trying build a Windows application to run skyfield python code. Later on I wanted to make it a DLL to interface with skyfield python code. But I am getting the below error. Looks like numpy is not getting imported by skyfield.

```
C:\Users\Anil\source\repos\ConsoleApplication3\Debug>ConsoleApplication3.exe multiply multiply 1 2
Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Python\Python38-32\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Python\Python38-32\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath' 
Just importing the skyfield api gives the error in windows console app.
```

The python code using skyfield package. Below is just a snippet but enough to reproduce the issue.

```
from skyfield.api import utc
from skyfield.api import load

def multiply(a,b):
    print("Will compute", a, "times", b)
    c = 0
    for i in range(0, a):
        c = c + b
    return c
```

The embedding C code for Windows is taken from here. It is a basic windows console application and runs with proper include/library paths.

```
https://docs.python.org/3/extending/embedding.html#pure-embedding``````
```

One the console I just run the following windows app.

```
ConsoleApplication3.exe multiply multiply 1 2
```
In windows console app we need to add the include/lib paths.

```
$(VC_IncludePath);$(WindowsSDK_IncludePath);C:\Python\Python38-32\include;$(IncludePath)
C:\Python\Python38-32\libs;$(VC_LibraryPath_x86);$(WindowsSDK_LibraryPath_x86);$(LibraryPath)
```

What might be causing this error ?

**Comment by rossbar** [comment]
How was numpy installed on this system?

**Comment by rossbar** [comment]
I'm going to close this for now due to lack of information. If the issue persists, please feel free to reopen with information about the numpy installation.
