### ISSUE TITLE
API: Review public functionality in arrayprint

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#16869]
#16036 reports downstream issues due to backwards-incompatible changes to classes in `numpy.core.arrayprint`. Based on the lack of docstrings etc. it seems that some functionality in arrayprint was not necessarily intended to be public. It would be good to review this and perhaps provide some more concrete guidance to users.

Incompatible changes introduced in e.g. #9941

**Comment by rgommers** [comment]
It's not public. Nothing in `numpy.core` is public.

**Comment by eric-wieser** [comment]
We should address #11924 at some point...

**Comment by rossbar** [comment]
Thanks for the link @eric-wieser , the description in the draft NEP describes the root cause #16036 . I will close this as duplicate as the problem is described very clearly in #11924
