### ISSUE TITLE
ImportError: DLL load failed for scipy/numpy- python interpreter inside Autodesk VRED

### ISSUE THREAD

**Issue by hajduke** [numpy/numpy#16863]
Autodesk VRED comes with python 2.7.6 in `C:\Program Files\Autodesk\VREDPro-12.0\lib\python`. When going to this directory and installing pip and scipy (+numpy 1.16.6, a version pip chooses)

`C:\Program Files\Autodesk\VREDPro-12.0\lib\python>python ensurepip`
`C:\Program Files\Autodesk\VREDPro-12.0\lib\python>python -m pip install scipy`

the following error message appears when importing scipy/numpy after invoking the interpreter in this directory
```
C:\Program Files\Autodesk\VREDPro-12.0\lib\python>python
Python 2.7.10 (default, Aug  7 2015, 13:03:04) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Autodesk\VREDPro-12.0\lib\python\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\Autodesk\VREDPro-12.0\lib\python\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Program Files\Autodesk\VREDPro-12.0\lib\python\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

Logically, scipy/numpy also do not work inside the VRED environment.

I already tried reinstalling it. And since I also have python 2.7.10 installed in `C:\Python27` including numpy, I also tried removing this directory from `PATH` in order to avoid conflicts. Both steps did not help.
My OS: Windows 10 Pro, 10.0.18363

Thank you.

BR, VL

**Comment by rossbar** [comment]
It looks like you expected to be using Python 2.7.6, but in the interpreter where you see the error you are running Python 2.7.10.

**Comment by hajduke** [comment]
I have also run it after excluding the path where 2.7.10 is, i.e. running 2.7.6 from the directory where it can be found after changing the environment variables.


LIPOVAC, Veljko

________________________________
Von: Ross Barnowski <notifications@github.com>
Gesendet: Dienstag, 14. Juli 2020 19:35
An: numpy/numpy <numpy@noreply.github.com>
Cc: hajduke <lipovac.v@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [numpy/numpy] ImportError: DLL load failed for scipy/numpy- python interpreter inside Autodesk VRED (#16863)


It looks like you expected to be using Python 2.7.6, but in the interpreter where you see the error you are running Python 2.7.10.

**Comment by rossbar** [comment]
Note that switching to the directory containing the binary you want to run is generally not a good way to select which version of Python to use. This is what the PATH and PYTHONPATH envrionment variables are for. Please see [this troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html) to see if you can determine that your environment is set up appropriately.

**Comment by rossbar** [comment]
I'm going to close this one due to inactivity, if the problem persists please feel free to reopen with the most up-to-date information about the system & installation procedure.

**Comment by hajduke** [comment]
@rossbar 

I was able to circumvent this error by using the numpy version 1.19.3.
[It says here](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html), that with the newer versions there is a deeper problem with the linalg subpackage.

BR,
Veljko
