### ISSUE TITLE
[help wanted] how to norm the features?

### ISSUE THREAD

**Issue by ucasiggcas** [numpy/numpy#16865]
hi,dear
I have a features' matrix which shape is (3,4) as follows, and every column is one feature 
now I just want to norm the features, 
```
>>> xx=np.random.randn(3,4)
>>> xx
array([[ 0.18874834,  0.37971162,  0.8287003 , -0.95896989],
       [-0.07977954,  0.04206023, -0.23647192, -0.36731412],
       [ 1.77722951,  0.68746666, -1.77812892,  0.54136854]])
```
should I do as the down?
```
>>> xx/np.linalg.norm(xx, axis=1, keepdims=True)
array([[ 0.14122813,  0.28411357,  0.62006266, -0.71753494],
       [-0.17885252,  0.09429206, -0.53013085, -0.82345738],
       [ 0.66764197,  0.25825679, -0.66797985,  0.20337292]])
```
or this one
```
>>> xx/np.linalg.norm(xx, axis=0, keepdims=True)
array([[ 0.1055047 ,  0.48279508,  0.41939189, -0.8260775 ],
       [-0.04459439,  0.05347867, -0.11967464, -0.31641236],
       [ 0.99341839,  0.87409893, -0.89988245,  0.46634662]])
```
could you pls help me ?
thx

**Comment by rossbar** [comment]
How to best interpret the `axis` kwarg for reductions is a common question. You may find the illustrations in [this tutorial](https://numpy.org/devdocs/user/absolute_beginners.html#creating-matrices) useful. For your particular case, you want to compute the norm of the columns, which would correspond to `axis=0`.
