### ISSUE TITLE
Strange behaviour when mixing basic and advanced indexing

### ISSUE THREAD

**Issue by ucyo** [numpy/numpy#16877]
There is unexpected behaviour if a user mixes basic and advanced indexing strategies.
The results of two indexing operations are different if they are executed back to back or in one go.

### Reproducing code example:

```python
import numpy as np
d = np.zeros((10,20,3))  # random data

# indexing via two operations
e = d[5,:,:]  # e.shape is (20,3), as expected 
e = e[:,[0,2]]  # e.shape is now (20,2) as expected

# same indexing in one go
g = d[5,:,[0,2]]  # g.shape is now (2,20)  ??? 

# this returns false
print(g.shape == e.shape)
```

### Error message:

No error message

### Numpy/Python version information:

```
1.18.5 3.8.3 (default, Jul  2 2020, 16:21:59)
[GCC 7.3.0]
```

**Comment by oliver-pola** [comment]
Looks also confusing to me, but it seems it is the documented behavior.

https://numpy.org/doc/stable/reference/arrays.indexing.html#combining-advanced-and-basic-indexing
> Two cases of index combination need to be distinguished:
> - The advanced indexes are separated by a slice, Ellipsis or newaxis. For example x[arr1, :, arr2].
> - The advanced indexes are all next to each other. For example x[..., arr1, arr2, :] but not x[arr1, :, 1] since 1 is an advanced index in this regard.

We are in the first case here, watch that last sentence also applies to your 5, so it is two advanced indexes separated by a slice. And then the doc continues:
> In the first case, the dimensions resulting from the advanced indexing operation come first in the result array, and the subspace dimensions after that.

**Comment by rossbar** [comment]
Thanks for the excellent answer @oliver-pola !

**Comment by ucyo** [comment]
Thank you for the answer. It is still a strange behaviour :confused:
