### ISSUE TITLE
test_large_zip fails in i586 after #15893

### ISSUE THREAD

**Issue by antlarr-suse** [numpy/numpy#16889]
Hi, it seems #15893 is making the test_large_zip test fail in openSUSE's build service for the i586 architecture with openSUSE Tumbleweed. The test output is:

```
______________________________________________________________________________________ TestSaveTxt.test_large_zip ______________________________________________________________________________________
[gw1] linux -- Python 3.8.3 /usr/bin/python3

self = <numpy.lib.tests.test_io.TestSaveTxt object at 0xe935e610>

    @pytest.mark.skipif(sys.platform=='win32', reason="files>4GB may not work")
    @pytest.mark.slow
    @requires_memory(free_bytes=7e9)
    def test_large_zip(self):
        def check_large_zip():
            # The test takes at least 6GB of memory, writes a file larger than 4GB
            test_data = np.asarray([np.random.rand(np.random.randint(50,100),4)
                                   for i in range(800000)], dtype=object)
            with tempdir() as tmpdir:
                np.savez(os.path.join(tmpdir, 'test.npz'), test_data=test_data)
        # run in a subprocess to ensure memory is released on PyPy, see gh-15775
        p = Process(target=check_large_zip)
        p.start()
        p.join()
>       assert p.exitcode == 0
E       assert 1 == 0
E         +1
E         -0

../../../BUILDROOT/python-numpy-1.19.0-0.i386/usr/lib/python3.8/site-packages/numpy/lib/tests/test_io.py:587: AssertionError
----------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/abuild/rpmbuild/BUILDROOT/python-numpy-1.19.0-0.i386/usr/lib/python3.8/site-packages/numpy/lib/tests/test_io.py", line 582, in check_large_zip
    np.savez(os.path.join(tmpdir, 'test.npz'), test_data=test_data)
  File "<__array_function__ internals>", line 5, in savez
  File "/home/abuild/rpmbuild/BUILDROOT/python-numpy-1.19.0-0.i386/usr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 616, in savez
    _savez(file, args, kwds, False)
  File "/home/abuild/rpmbuild/BUILDROOT/python-numpy-1.19.0-0.i386/usr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 721, in _savez
    format.write_array(fid, val,
  File "/home/abuild/rpmbuild/BUILDROOT/python-numpy-1.19.0-0.i386/usr/lib/python3.8/site-packages/numpy/lib/format.py", line 664, in write_array
    pickle.dump(array, fp, protocol=3, **pickle_kwargs)
MemoryError
======================================================================================= short test summary info ========================================================================================
FAILED ../../../BUILDROOT/python-numpy-1.19.0-0.i386/usr/lib/python3.8/site-packages/numpy/lib/tests/test_io.py::TestSaveTxt::test_large_zip - assert 1 == 0
```

It seems other architectures aren't affected. I tried calling the test without using a separate process and that works fine for i586.

So applying [this patch](https://build.opensuse.org/package/view_file/home:alarrosa:branches:devel:languages:python:numeric/python-numpy/fix-test_large_zip-in-i586.patch?expand=1) _fixes_ it, but I didn't submit it as a PR because I understand that that would be basically reverting #15893 for i586 and that would bring #15775 back.

### Reproducing code example:

Just running the tests in a i586 architecture should show the error.

I understand that setting up such a system might not be quick, so since I can reproduce it easily, if there's any test that would help, please, tell me.

Also, I can provide help to set up a local checkout to test running the tests exactly as they're ran on the obs servers. It's basically a matter of creating an account at https://build.opensuse.org, installing the osc tool and running something like:

```
osc branch devel:languages:python:numeric python-numpy
osc checkout home:<your_obs_username>:branches:devel:languages:python:numeric python-numpy
cd home:<your_obs_username>:branches:devel:languages:python:numeric/python-numpy
osc build openSUSE_Tumbleweed i586
```

### Numpy/Python version information:

1.19.0 3.8.3 (default, May 17 2020, 14:48:56) [GCC]

**Comment by seberg** [comment]
Ah, the `@requires_memory` decorator will ignore MemoryError with the knowledge that those are probably expected on some systems.  But the use of a subprocess is breaking that usage.

Either, we have to preserve whatever error is raised internally, or add a `try: ... except: MemoryError` to the (inner) `check_large_zip` function

**Comment by antlarr-suse** [comment]
I guess a `try: ... except: MemoryError` in the inner function to ignore the exception would work, but I wonder what's really happening.

I added a very simple function to get the available memory from /proc/meminfo (I didn't want to use psutil since that would add a new dependency which I don't have currently installed in my test system):
```
def print_available_memory():
    with open('/proc/meminfo','rt') as memfd:
        avail = [x for x in memfd.readlines() if x.startswith('MemAvailable')]
    print(avail[0])
```
And then changed the inner function to:
```
        def check_large_zip():
            print_available_memory()
            # The test takes at least 6GB of memory, writes a file larger than 4GB
            test_data = np.asarray([np.random.rand(np.random.randint(50,100),4)
                                   for i in range(800000)], dtype=object)
            with tempdir() as tmpdir:
                print_available_memory()
                try:
                    np.savez(os.path.join(tmpdir, 'test.npz'), test_data=test_data)
                except MemoryError:
                    print_available_memory()
                    raise
```

The workers of the obs servers are more constrained, but in my local system where I'm testing in a chroot, it prints:

```
MemAvailable:   28324328 kB

MemAvailable:   26469744 kB

MemAvailable:   25788288 kB
```

~26GB should be enough memory to run the test, isn't it? Which makes me wonder why exactly is pickle raising a MemoryError.

**Comment by seberg** [comment]
@antlarr-suse any chance this is a 32bit system, so that we cannot have a single process use more memory than 4GiB?  I am wondering if our decorator needs to check for 32bit systems and then force the "available memory" to at most 4GiB?

**Comment by antlarr-suse** [comment]
You're right, I tested running the next lines in a python interpreter inside the i586 chroot:

```
>>> import numpy as np
>>> a=np.asarray([np.random.rand(np.random.randint(50,100),4) for i in range(800000)], dtype=object)
>>> b=np.asarray([np.random.rand(np.random.randint(50,100),4) for i in range(800000)], dtype=object)
>>> c=np.asarray([np.random.rand(np.random.randint(50,100),4) for i in range(800000)], dtype=object)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "mtrand.pyx", line 1168, in numpy.random.mtrand.RandomState.rand
  File "mtrand.pyx", line 422, in numpy.random.mtrand.RandomState.random_sample
  File "_common.pyx", line 270, in numpy.random._common.double_fill
MemoryError: Unable to allocate 1.59 KiB for an array with shape (51, 4) and data type float64
```

The python interpreter was using 3.9928 GB at that point, so your guess is completely right there.

But I'm not sure I understand you when you said "force the available memory to at most 4 GiB" in 32bit systems. You mean, changing the decorator (in the 32bit case) to `@requires_memory(free_bytes=4e9)` ? I don't think that'll help.

I think what would work would be to disable the test with something like (with the appropriate `import platform`):
```
@pytest.mark.skipif(platform.architecture()[0] == '32bit', reason="can't use more than 4GB of memory")
```

or maybe do the same check to reduce the `range(800000)` to `range(250000)` to use less memory (I tested 250000 works, but 300000 doesn't) but I guess that would ignore the whole meaning of the test anyway, so skipping it would be as effective.

**Comment by antlarr-suse** [comment]
Btw, I don't have any windows machine at hand, but I think the test for `platform.architecture()[0] == '32bit'` probably covers the existing decorator to skip the test when `sys.platform=='win32'` so that one could probably be removed.

**Comment by seberg** [comment]
I mean adding `mem_free = min(mem_free, (sys.maxsize + 1) * 2)` to the decorators code itself (I am not quite sure that is the best way, but I think it would be good enough).  Unless it is overridden by the environment variable (I don't care about the choice there).

I.e. if the system reports more then 4GiB of free memory, we clip it to 4GiB on 32bit systems.  Adding the `try: ... except: MemoryError` here is still correct though IMO, although it would be nicer if it showed up as an xfail, which requires detecting that it was an actual memory error.

The whole point of this check is to have an output file of more than 2GiB probably. I expect modifying the test to make it pass defeats the purpose of the test itself.

**Comment by seberg** [comment]
Although, maybe its simpler to just skip all of these tests on 32bit platforms...

**Comment by antlarr-suse** [comment]
> I mean adding `mem_free = min(mem_free, (sys.maxsize + 1) * 2)` to the decorators code itself (I am not quite sure that is the best way, but I think it would be good enough). Unless it is overridden by the environment variable (I don't care about the choice there).

Ah, I see now. Yes, I tested adding that line to the decorator and that works too.

> I.e. if the system reports more then 4GiB of free memory, we clip it to 4GiB on 32bit systems. Adding the `try: ... except: MemoryError` here is still correct though IMO, although it would be nicer if it showed up as an xfail, which requires detecting that it was an actual memory error.

Should I provide a PR that sets a "memoryerror_raised" flag in shared memory so it can be "re-raised" in the main process so the decorator catches it and it can use xfail? Or would you take care of fixing it in some other way?

> The whole point of this check is to have an output file of more than 2GiB probably. I expect modifying the test to make it pass defeats the purpose of the test itself.

Yes, that's what I meant with "ignore the meaning of the test".

**Comment by antlarr-suse** [comment]
Just in case I wasn't clear. Something like this (tested and works fine):

```
        def check_large_zip(raised_memoryerror):
            raised_memoryerror.value=False
            # The test takes at least 6GB of memory, writes a file larger than 4GB
            test_data = np.asarray([np.random.rand(np.random.randint(50,100),4)
                                   for i in range(800000)], dtype=object)
            with tempdir() as tmpdir:
                try:
                    np.savez(os.path.join(tmpdir, 'test.npz'), test_data=test_data)
                except MemoryError:
                    raised_memoryerror.value=True
                    raise
        # run in a subprocess to ensure memory is released on PyPy, see gh-15775
        raised_memoryerror = Value(c_bool)
        p = Process(target=check_large_zip, args=(raised_memoryerror,))
        p.start()
        p.join()
        if raised_memoryerror.value:
            raise MemoryError()
        assert p.exitcode == 0
```

**Comment by seberg** [comment]
@antlarr-suse if you are up for making a PR, great! I think something that ignores MemoryError here probably makes sense no matter what we do about the general 32bit problem.
