### ISSUE TITLE
Error in documentation of numpy.ufunc.outer

### ISSUE THREAD

**Issue by avivhu** [numpy/numpy#16880]
The documentation says:

> ... the result, C, of op.outer(A, B) is an array of dimension M + N such that ...

See:
https://numpy.org/doc/stable/reference/generated/numpy.ufunc.outer.html

I think it should say:

> ... the result ... is an array of dimension M x N such that ...

**Comment by eric-wieser** [comment]
No, the currently documentation is correct:
```python
In [1]: import numpy as np

In [2]: a = np.zeros((2, 3))

In [3]: b = np.zeros((4, 5, 6))

In [4]: c = np.multiply.outer(a, b)

In [5]: a.ndim, b.ndim, c.ndim
Out[5]: (2, 3, 5)
```
I think you're reading _"`a` has dimension `N`"_ as `a.shape == (N,)`, but you should be reading it as `a.ndim = N`.

**Comment by avivhu** [comment]
Indeed. I was wrong.
