### ISSUE TITLE
ENH: A very fast algorithm for computing matrix rank

### ISSUE THREAD

**Issue by touqir14** [numpy/numpy#16893]
## 🚀 Feature
I have devised an LUP based [matrix rank computing algorithm](https://github.com/touqir14/LUP-rank-computer) that outperforms significantly the standard Numpy's [matrix_rank](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html) function and PyTorch's GPU accelerated [matrix_rank](https://pytorch.org/docs/master/generated/torch.matrix_rank.html) algorithm for most cases. For instance, for UAR generated 15000 x 15000 matrices, it offers a speedup of about 25 times over Numpy's matrix_rank. See the [benchmarks](https://github.com/touqir14/LUP-rank-computer/blob/master/README.md). Unlike the LU factorization, LUP is stable in practice and I have thoroughly tested the correctness of my implementation.
## Motivation

Computing the matrix rank using Numpy's matrix_rank function can be rather slow, particularly if one deals with large matrices and needs to run multiple times for at least tens of times. This motivated me to come up with a much faster approach than the SVD method used in Numpy's matrix_rank.
## Pitch

I would like to consider the prospect of implementing this as a Numpy function. My implementation uses scipy's [LUP](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html) function and a couple of Cython optimized functions along with the standard Numpy matrix operations. 

Let me know if you need to know more about the algorithm's specifics and testing/benchmarks.

**Comment by eric-wieser** [comment]
> My implementation uses scipy's LUP function

Note that this automatically disqualifies it from being added to numpy, as that would introduce a circular dependency. You might want to consider contributing to to scipy instead.

**Comment by touqir14** [comment]
Thanks for pointing that out. I will post this to scipy's repo.
