### ISSUE TITLE
DOC: Testing Guidelines focuses on SciPy

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#16892]
In the current (NumPy v1.19) [Testing Guidelines](https://numpy.org/doc/stable/reference/testing.html) document, the focus of examples and some explanations is SciPy. 

[This document](https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt), however, seems to have the content we need in our docs. I propose replacing the first document with the second one, eliminating the SciPy examples from our documentation.

**Comment by rossbar** [comment]
I think this was already addressed in #16323 and the changes show in the devdocs. It looks like maybe #16323 should be marked as a backport candidate perhaps though!

**Comment by charris** [comment]
If you want it backported, mark it soon. I'm think it is about time for 1.19.1.

**Comment by rgommers** [comment]
I don't think doc fixes need backporting unless they're serious issues. Either way, let's close this since it's done.
