### ISSUE TITLE
Implement GitHub actions `take` command as in pandas for assigning issues

### ISSUE THREAD

**Issue by leeyspaul** [numpy/numpy#16898]
It seems that [pandas](https://github.com/pandas-dev/pandas/issues/32301) uses GitHub Actions to assign issues automatically to contributors who want to take on issues instead of the original "can I take this?" flow.

I wanted to raise an issue here for community feedback/thoughts on implementing the same workflow here! 

Thank you :)!

**Comment by rgommers** [comment]
We don't work with assigning issues. If we'd want that, step one will be for maintainers to start self-assigning if they'd find that useful.

>  instead of the original "can I take this?" flow.

That's not and has never been a workflow. If anyone wants to work on an issue, no need to ask - just start.

**Comment by rgommers** [comment]
There's nothing to do here, so I'll close the issue. More discussion welcome of course.

**Comment by leeyspaul** [comment]
Sounds good!
