### ISSUE TITLE
Error in np.partition

### ISSUE THREAD

**Issue by cauchy7203** [numpy/numpy#16902]
### Reproducing code example:

```python
import numpy as np
<< your code here >>
a = np.array([46, 57, 23, 39, 1, 10, 0, 120])
np.partition(a,2)
# result
array([  0,   1,  10,  39,  57,  23,  46, 120])
```

According to the documentation *The k-th value of the element will be in its final sorted position.*

But notice that the `k` in this code is 2, *i. e.* the 3rd value `23` should be in its final sorted position, but the final sorted array is 

```python
np.sort(a)
# result
array([  0,   1,  10,  23,  39,  46,  57, 120])
```
The original 3rd value is located in the **4-th** position in the sorted array, but the method `partition` put it in the **6-th** position.

**Comment by WarrenWeckesser** [comment]
The intent of the docstring is to refer to the `k`-th element of the *output* array.  In your example, `k` is 2, so it is the value of `result[2]` (which is 10) that is in its final sorted position.

**Comment by cauchy7203** [comment]
Dear WarrenWeckesser,

Thank you very much for your so fast reply! 

It is clear that I have misunderstood the meaning of this function.

Sorry for my useless report and thanks very much again for your help!

**Comment by WarrenWeckesser** [comment]
No problem, I'm glad the issue is cleared up.
