### ISSUE TITLE
DOC: Update fill_diagonal docstring

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#16901]
The current parameter description for `fill_diagonal` states that the fill value `val` must be a scalar. However, no input-checking is done on `val` and it turns out that array-likes with the same first dimension as `a` will also work, for example::

```python
>>> a = np.zeros((4, 5))
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])
>>> np.fill_diagonal(a, np.arange(a.shape[0]))
>>> a
array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.]])
```

There are also already some examples in the docstring that use lists to fill the diagonal.

**Comment by leeyspaul** [comment]
Hey @rossbar I'll take this one on!
