### ISSUE TITLE
Moore-Penrose Inverse Error for NumPy Matrices (Trac #1093)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1691]
_Original ticket http://projects.scipy.org/numpy/ticket/1093 on 2009-04-23 by trac user mcleane, assigned to unknown._

The inverse functionality in NumPy is useful, for instance A.I will properly calculate
the Moore-Penrose inverse in many cases of rectangular matrices.  However, this functionality is badly broken in at least one instance.

The singular matrix

> > import numpy as np
> > A = np.matrix([[2,1,1],[1,0,-1],[3,1,0]])

incorrectly reports the inverse to be:

> > print A.I

[[ -4.50359963e+15  -4.50359963e+15   4.50359963e+15]
 [  1.35107989e+16   1.35107989e+16  -1.35107989e+16]
 [ -4.50359963e+15  -4.50359963e+15   4.50359963e+15]]

whereas it should be:

[[0.0606060606061 0.151515151515 0.212121212121]
 [0.151515151515 -0.121212121212 0.030303030303]
 [0.393939393939 -0.515151515152 -0.121212121212]]

The correct value above can be calculated in NumPy by a sequence of commands,
by first taking a full rank decomposition EG = A:

> > E = np.matrix([[2,1],[1,0],[3,1]])
> > G = np.matrix([[1,0,-1],[0,1,3]])

then the Moore-Penrose inverse properly calculated by:

> > print G.I*E.I

I suspect the problem lies in using a technique to calculate inverses that fails
badly when A is of neither full column rank nor full row rank, and this problem should be easy to rectify.

**Comment by seberg** [comment]
I think we can close this, since `matrix` is deprecated by now and thus nobody should be using the `matrix.I` attribute anymore (requiring an explicit decision of which method to use).
