### ISSUE TITLE
How to create node class for a tree structure with jitclass

### ISSUE THREAD

**Issue by rashid1844** [numpy/numpy#16912]
I am trying to use jitclass with node class that is used for a tree structure. The problem is that I am not able to store the parent object reference. I tried types.pyobject but wasn't successful.

### Reproducing code example:

```python
spec = [('parent', types.optional(types.pyobject)),
       ('name', types.unicode_type)]
@jitclass(spec)
class Nodes:
    def __init__(self, parent, name):
        self.parent = parent
        self.name = name

p = Nodes(None, 'parent')
c1 = Nodes(p, 'child1')
c2 = Nodes(p, 'child2')
c3 = Nodes(p, 'child3')
```

### Error message:
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x0000015A14537E80>.
Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast instance.jitclass.Nodes#15a151cd9b0<parent:OptionalType(pyobject) i.e. the type 'pyobject or None',name:unicode_type> to OptionalType(pyobject) i.e. the type 'pyobject or None': %".31" = load {i8*, {{i8*, i8}, {i8*, i64, i32, i32, i64, i8*, i8*}}*}, {i8*, {{i8*, i8}, {i8*, i64, i32, i32, i64, i8*, i8*}}*}* %"parent"

File "<ipython-input-72-8d3154ca209d>", line 6:
    def __init__(self, parent, name):
        self.parent = parent
        ^

**Comment by mattip** [comment]
You have posted on the NumPy issue tracker. This does not seem to be a NumPy issue, did you mean to post here? Closing.
