### ISSUE TITLE
ENH: handle SymPy objects in NumPy

### ISSUE THREAD

**Issue by Yukti-09** [numpy/numpy#16927]
import numpy as np
from sympy import *
a = symbols(a)
b = symbols(b)
c = symbols(c)
x = [a b c]
print(np.linalg.norm(x))

I should get something like sqrt(a^2+b^2+c^2)
Instead, I get SyntaxError: invalid syntax.

**Comment by mattip** [comment]
Your example is not python. Try
```
import numpy as np
from sympy import symbols
a = symbols('a')
b = symbols('b')
c = symbols('c')
x = [a, b, c]
print(np.linalg.norm(x))
```
which now raises
```
AttributeError: 'Add' object has no attribute 'sqrt'
```
NumPy does not know how to deal with sympy objects, you need to use sympy semantics. Their docs are here https://docs.sympy.org/latest/tutorial/

**Comment by Yukti-09** [comment]
@mattip My example is a code written in python. sqrt is present in the library 'math'. 
I do understand that numpy cannot deal with sympy objects but if it could, wouldn't it be great!

**Comment by mattip** [comment]
SymPy could support this via the `__array_function__` protocol, see [NEP 18](https://numpy.org/neps/nep-0018-array-function-protocol.html) for more information.

**Comment by Yukti-09** [comment]
Thanks but it didn't serve my purpose much.

**Comment by Yukti-09** [comment]
Is there no way that we can do it?

**Comment by eric-wieser** [comment]
Mattip is right to suggest we close this - we've provided the hooks for sympy to make `np.sin(some_symbol)` work, the ball is now in their court to implement `__array_function__` if they want to support this.

**Comment by Yukti-09** [comment]
Thank you.
