### ISSUE TITLE
ENH : Handle trignometry identities in norm

### ISSUE THREAD

**Issue by Yukti-09** [numpy/numpy#16929]
import numpy as np
from sympy import *
a = symbols('a')
b = symbols('b')
c = symbols('c')
x = Matrix([a*cos(b),a*sin(b),c])
print(x.norm())

Gives an output 
sqrt(Abs(c)**2 + Abs(a*sin(b))**2 + Abs(a*cos(b))**2)
Output we are supposed to get sqrt(Abs(c)**2+Abs(a)**2)

@mattip @eric-wieser

**Comment by mattip** [comment]
This is a sympy issue, not a NumPy one. NumPy is not at all involved in the snippet, you don't need to import it. This would become clearer if you did not `from sympy import *`, which is [considered bad practice](https://www.python.org/dev/peps/pep-0008/#imports) (look for "wildcard imports"). Closing, please try to engage with the sympy community for more help.

**Comment by Yukti-09** [comment]
@mattip Thanks, I will follow your advice.
