### ISSUE TITLE
Error in visual studio code related to numpy

### ISSUE THREAD

**Issue by deep3125** [numpy/numpy#16928]
While importing matplotlib in visual studio code(if I open visual studio directly) may be related to NumPy however if I open it through anaconda or any other ide then it works fine.

### Reproducing code example:
```python
import numpy as np
<< import matplotlib.pyplot as plt>>
```

### Error message:
 UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\deepk\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\deepk\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\deepk\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/deepk/OneDrive/Documents/Python Scripts/imp/my work/python/projects/random_walk.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\deepk\anaconda3\lib\site-packages\matplotlib\__init__.py", line 139, in <module>
    from . import cbook, rcsetup
  File "C:\Users\deepk\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 32, in <module>
    import numpy as np
  File "C:\Users\deepk\anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\deepk\anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\deepk\anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

### Numpy/Python version information:Using anaconda

numpy version: 1.18.1
Python version:3.7

**Comment by seberg** [comment]
Please check the trouble shooting page that the error (on newer NumPy versions) will also refer to: https://numpy.org/devdocs/user/troubleshooting-importerror.html this is an issue of setting up VSCode correctly (especially together with anaconda).

That should fix your problem, if you suspect something more going on, please do comment and I am happy to reopen.

**Comment by deep3125** [comment]
thanks for your reply. But it still does not work, one thing I want to tell you about is this problem has occurred after installing JDK (java development kit) and adding to path variable, also there are many values for user variable (path) and there is pythonpath variable in a user variable.
