### ISSUE TITLE
pylint thinks that `log1p` doesn't return

### ISSUE THREAD

**Issue by tom-programming** [numpy/numpy#16932]
When linting the code any assignment from  `log1p` will produce a linter warning that the function call does not return. Nothing happens with other functions such as `log10`.

### Reproducing code example:

```python
import numpy as np
test = np.log1p(9.5)
```

### Error message:
Assigning to function call which doesn't return
pylint(assignment-from-no-return)

### Numpy/Python version information:

1.18.5 3.6.10 (default, Mar  5 2020, 10:17:47) [MSC v.1900 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
Are you using `numpy-stubs` at all?

**Comment by tom-programming** [comment]
> Are you using `numpy-stubs` at all?

No

**Comment by BvB93** [comment]
It seems that similar issues have been reported before (https://github.com/PyCQA/pylint/issues/2694).

**Comment by seberg** [comment]
Thanks for the link, scrolling through that, it seems it was a pylint issue and is fixed there, so I will close this. I don't see anything strange we are doing in any case.
