### ISSUE TITLE
TravisCI aarch64 job is testing x86_64 not arm64

### ISSUE THREAD

**Issue by rth** [numpy/numpy#16947]
Unless I'm missing something the [aarch64 TravisCI job](https://github.com/numpy/numpy/blob/1ce54575b17071d40e4c1519007b2ec7d9a1b6d3/.travis.yml#L114) is actually running a x86_64/amd64 VM, not an ARM one. 

This can be seen for instance by the wheels names that are downloaded to run tests in CI,
```
 Using cached mypy-0.782-cp37-cp37m-manylinux1_x86_64.whl (20.8 MB)
```
(unlike for e.g. s390x or ppc64le jobs).

The fix would be to specify "arm64" instead of "aarch64" in `.travis.yml`. 

This is due to an unfortunate approach by TravisCI to fall back to amd64 for unsupported architectures, instead of failing (as documented in their docs). The "aarch64" shown in the UI does not seem reliable either, but one can use `$TRAVIS_CPU_ARCH` environment variable to  double check.

Maybe they renamed this arch at some point, not sure.

Discovered while trying to add a similar setup in https://github.com/scikit-learn/scikit-learn/pull/17996

cc @mattip

**Comment by mattip** [comment]
Indeed. You can see in a [build log from a recent PR](https://travis-ci.org/github/numpy/numpy/jobs/711578077#L39) (expand the "Build system information" to see line 39) that the machine architecture is `linux/amd64`, even though the architecture name is aarch64. Thanks!

**Comment by rth** [comment]
Fixed in https://github.com/numpy/numpy/pull/16957, thanks!
