### ISSUE TITLE
histogramdd: maximum supported dimension for an ndarray is 32

### ISSUE THREAD

**Issue by sumanthratna** [numpy/numpy#16958]
I have a 2-D matrix with 64 columns and 12 rows. Each row represents a coordinate in a 64-dimension space. I'd like to histogram this data using `np.histogramdd`, but I'm unable to due to `ValueError: maximum supported dimension for an ndarray is 32, found 64`. 

### Reproducing code example:

```python
import numpy as np


mydata = np.random.randn(12, 64)
hist, edges = np.histogramdd(mydata)
```

### Error message:

```
Traceback (most recent call last):
  File "myproblem.py", line 4, in <module>
    hist, edges = np.histogramdd(mydata, bins=2)
  File "<__array_function__ internals>", line 5, in histogramdd
  File "/private/tmp/venv/lib/python3.8/site-packages/numpy/lib/histograms.py", line 1090, in histogramdd
    xy = np.ravel_multi_index(Ncount, nbin)
  File "<__array_function__ internals>", line 5, in ravel_multi_index
ValueError: maximum supported dimension for an ndarray is 32, found 64
```

### Numpy/Python version information:
```
1.19.1 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)]
```

CC @sagarg22

edit:

it looks like this is known
https://github.com/numpy/numpy/blob/92ebe1e9a6aeb47a881a1226b08218175776f9ea/numpy/lib/histograms.py#L1088-L1090

I'm still unsure of how to solve this.

**Comment by eric-wieser** [comment]
Such a histogram would occupy at the very least 2**64 bytes of memory, which is not possible in RAM of a 64-bit machine.

**Comment by sumanthratna** [comment]
For the record: we're working around this problem by using PCA to determine the most important features, and then selecting only those columns to histogram the data. This should work as long as the number of important features is less than 32.
