### ISSUE TITLE
searchsorted arg names are bad

### ISSUE THREAD

**Issue by krey** [numpy/numpy#16965]
The signature is
```python
np.searchsorted(a, v, side='left', sorter=None)
```

It is difficult to remember which role is played by `a` and which by `v`.

I propose renaming the args to
```python
np.searchsorted(haystack, needles, side='left', sorter=None)
```
(not perfect, I know, but better than `a` and `v`)

This would improve my user experience in jupyter notebook, hitting shift-tab after `np.searchsorted(`.
I'm sure other editors/development environments would benefit too.

Happy to do the PR if there's interest

**Comment by eric-wieser** [comment]
Making this change would break anyone using the following:
```python
np.searchsorted(a=[1], v=1)
```
Note also that the current names mostly match the names for [`bisect.bisect_left`](https://docs.python.org/dev/library/bisect.html#bisect.bisect_left)

**Comment by krey** [comment]
I don't think anyone has ever passed `a` and `v` by keyword. You'd get verbosity without gaining any readability.

Quick code search on github seems to confirm this.

There's always
```python
def searchsorted(haystack=None, needles=None, side='left', sorted=None, **kwargs)
```

Throw if `haystack` or `needles` is `None`, deprecation warning if `a` and `v` are passed in kwargs...

I appreciate the consistency with bisect, but they're also in the wrong here IMO

**Comment by eric-wieser** [comment]
> I don't think anyone has ever passed `a` and `v` by keyword. You'd get verbosity without gaining any readability.
> I appreciate the consistency with bisect, but they're also in the wrong here IMO, but it's not as bad

Even if you don't think anyone has done so, we can't be sure, and risk breaking people.
If you could persuade cpython to change the argument names, we'd be happy to follow suit :)

> At the very least we could change the docstring to Find indices where the elements 'v' should be inserted into 'a' to maintain order.

Documentation PRs are always appreciated!

**Comment by seberg** [comment]
You could probably rename it by temporarily adding two keyword arguments with the same meaning... It doesn't feel like high priority, and indeed it would not be bad if Python would have nicer names as well.

**Comment by ddasilva** [comment]
Seeing as @seberg closed the merge request to solve this, should this issue be closed as well? is there any work to be done?

**Comment by charris** [comment]
@ddasilva Thanks for the heads up.
