### ISSUE TITLE
consistent advanced slicing

### ISSUE THREAD

**Issue by 2sn** [numpy/numpy#16978]
### Reproducing code example:

```python
>>> import numpy as np
>>> a = np.ndarray((5,6,7))
>>> a.shape
(5, 6, 7)
>>> a[[[0,1]],[[0],[1],[2]],:].shape
(3, 2, 7)
>>> a[:,[[0,1]],[[0],[1],[2]]].shape
(5, 3, 2)
>>> a[[[0,1]],:,[[0],[1],[2]]].shape
(3, 2, 6)
```
I think the outcome of the third example is unexpected and inconsistent having seen the first two.  I it would be more consistent either have the index dimensions `(3,2)` always be first, or preserve location of the "free" coordinate `:` to obtain a shape of `(3,6,2)`.

### Numpy/Python version information:

1.19.1 3.8.4 (default, Jul 14 2020, 11:50:51) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]

**Comment by shoyer** [comment]
Many of us agree with you that it's undesirable, but this is NumPy's documented behavior. See here for an (unimplemented) proposal for changing it: https://numpy.org/neps/nep-0021-advanced-indexing.html

**Comment by seberg** [comment]
Its ancient but linking gh-6075 which could be picked up at some point, it was fairly far along.  Other than that, I assume this can be closed as a duplicate. Thanks for reporting @2sn.

**Comment by 2sn** [comment]
Could the change be implemented with some warning of obsolescence and a transition be made at a major numpy revision? 
It would help newbies as well as experienced _numpy_ users.

**Comment by seberg** [comment]
I think the main path we have is to sit down and finish of `.vindex` and `.oindex`, etc. and then (with a bit of delay) start deprecating multiple advanced indices for normal indexing entirely.  That is definitely possible, the PR I linked has a large chunk of the necessary code, which may need some cleanup and more tests, etc.
