### ISSUE TITLE
Feature request: Specifying destination of np.load, like `np.load(... out=)`

### ISSUE THREAD

**Issue by JiaRu2016** [numpy/numpy#16979]
Is there any way we can specifying destination of `np.load()` ?  Maybe looks like

```python
np.load('path/to/small_array.npy', out=large_array[some_slice])
```

It seems 
```
large_array[some_slice] = np.load('path/to/small_array')
```
will "copy" the array two times.  Can we make it just one copy ?

**Comment by rossbar** [comment]
Maybe `np.memmap` or, for `.npy` files, `numpy.lib.format.open_memmap` is appropriate for your use-case?

**Comment by JiaRu2016** [comment]
@rossbar I'v read document of `memmap` and it solves my question:

```python
large_array[some_slice] = np.load('path/to/small_array', mmap_mode='r')
```
is even more fast than simple `np.load()`. I suppose `array[slice] = np.load(  mmap_mode='r')` saved time of allocating memmory and only "copy" once.

**Comment by rossbar** [comment]
I'm glad that the docs contained the answer you were looking for! I'm going to close this as resolved - if you have further questions/comments or ideas of how to increase the visibility of the `memmap` features in the docs, please feel free to follow up.
