### ISSUE TITLE
Datetime substraction conversion error

### ISSUE THREAD

**Issue by jochengietzen** [numpy/numpy#16984]
When substracting two datetime64 objects, the result in microseconds is off. Minimal example shows that instead of expected 1123.456 microseconds the timedelta is 1123456 microseconds.

### Reproducing code example:

```python
import numpy as np
print(np.datetime64('2020-10-10T20:00:01.123456') - np.datetime64('2020-10-10T20:00:00.0'))
>> 1123456 microseconds
```

### Numpy/Python version information:

1.19.1 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by eric-wieser** [comment]
You're confusing milliseconds and microseconds.

**Comment by jochengietzen** [comment]
Thanks... 🤦
