### ISSUE TITLE
TST: typing tests slow on shippable arm64 runs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#16980]
Our arm64 runs are quite slow, so we add `--durations` to find the slowest tests. Here are the results from a [random run](https://app.shippable.com/github/numpy/numpy/dashboard) (choose a successful Job from "Latest Status" -> "build_ci" -> python runtests.py ... -> scroll to the end) . The 
typing tests are almost an order of magnitude slower than the rest, and take 201 of the 581 seconds total to run. On non-ARM test runs they do not show this slowdown. Any thoughts?

```
-- Docs: https://docs.pytest.org/en/latest/warnings.html
- generated xml file: /root/src/github.com/numpy/numpy/shippable/testresults/tests.xml -
========================== slowest 10 test durations ===========================
122.43s call     tests/test_typing.py::test_success[numerictypes.py]
88.92s call     tests/test_typing.py::test_success[simple_py3.py]
14.69s call     f2py/tests/test_compile_function.py::test_f2py_init_compile[extra_args0]
14.64s call     f2py/tests/test_compile_function.py::test_f2py_init_compile[]
14.64s call     f2py/tests/test_compile_function.py::test_f2py_init_compile[--noopt --debug]
14.19s call     tests/test_typing.py::test_fail[fromnumeric.py]
11.50s call     tests/test_typing.py::test_reveal[fromnumeric.py]
11.43s call     tests/test_typing.py::test_success[fromnumeric.py]
7.93s setup    core/tests/test_cython.py::test_get_datetime64_unit
7.93s setup    f2py/tests/test_return_integer.py::TestF90ReturnInteger::test_all[t0]
```

**Comment by rgommers** [comment]
Looking at the wheel sizes at https://pypi.org/project/mypy/#files, the Linux/Windows/macOS wheels include `mypyc`, while there's no `aarch64` wheel so that falls back to pure Python. Same for conda, no `aarch64` package.

I didn't look into more detail, but seems likely - perhaps fixable by building a wheel for CI, or by contributing an `aarch64` build directly to the mypy project.

**Comment by mattip** [comment]
Maybe we should optionally skip the typing tests if mypyc is not available. We could add a test for mypyc and mark the tests as "slow", so that running the full test suite would not skip them.

**Comment by mattip** [comment]
Tried skipping based on existence of mypyc. It turns out mypyc is built when `pip install`ing mypy, so the problem is somewhere else.

**Comment by BvB93** [comment]
Do we still need this issue now that the typing tests are marked as slow?

**Comment by mattip** [comment]
Thanks, closing. Please reopen or open a new issue if it turns out I am wrong.
