### ISSUE TITLE
np.lib.stride_tricks.as_strided raises `ValueError: array is too big`

### ISSUE THREAD

**Issue by FirefoxMetzger** [numpy/numpy#16994]
When creating (very) large arrays via `as_strided` numpy raises an exception as soon as the array would consume more memory than would fit on the machine. I find this behavior strange since the new array shares memory with an already existing array that does fit into memory.

Is there any particular reason behind this behavior? If not, would it be worthwhile (moreso possible) to not perform this check here?

### Reproducing code example:

```python
import numpy as np

base = 100
foo = np.ones(100)

# to reproduce this bug, you need less than 100 000 petabytes of memory
# if you have more, please add a 0 below (or as many as you may need)
dims = 10

bar = np.lib.stride_tricks.as_strided(
    foo, [base] * dims, [0] * (dims - 1) + [8])
```

### Error message:

```
Traceback (most recent call last):
  File "numpy_bug_mwe.py", line 7, in <module>
    bar = np.lib.stride_tricks.as_strided(foo, [base] * dims, [0] * (dims - 1) + [8])
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\stride_tricks.py", line 103, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```

### Numpy/Python version information:

1.18.2 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

Similar code also fails in python3.6, 3.7, and 3.8 (all 32-bit) (AzureDevOps CI). I can look up the respective numpy version if necessary.

**Comment by eric-wieser** [comment]
> numpy raises an exception as soon as the array would consume more memory than would fit on the machine. I find this behavior strange since the new array shares memory with an already existing array that does fit into memory.

It's not that the array doesn't fit into memory - "larger than the maximum possible size." means "the size does not fit in `ndarray.size`, which is of type `intptr_t`.

**Comment by seberg** [comment]
Yeah, I am going to close this, we can keep discussing though.  Changing to unsigned sounds like it would trickle down to a lot of ABI and API also, possibly including things like the Python buffer-protocol itself. So I think we would need to have *very* good reasons to consider allowing larger sizes.
I admit, its a bigger issue on 32bit platforms, but the same problems apply.

**Comment by FirefoxMetzger** [comment]
Ah! My bad then; I misunderstood the error message. `arr.size * arr.dtype.itemsize` sounded like the size of the array in memory. 

Could it be an idea to make the error message more specific in this case, e.g. `"ValueError: array is too big; `arr.size` must be representable by a {platform.architecture()[0]} integer"`?

If you allow me another stupid question on this topic: The reason that `arr.size` is necessary is that python buffers need a length, correct? Because in my mind I don't see why numpy itself needs `arr.size` to manipulate the array if it has `arr.shape` and `arr.strides`. Is there a good resource I can use to read up on this?

**Comment by seberg** [comment]
Well, we also have things like `nbytes` and it is nice that currently `arr.view(np.uint8)` can't (typically) fail, while not including the itemsize would break that in more cases (currently the `ndim` can change and could be more than the maximum of 32).  So there are a few things that may see the array as a `bytes` array (probably including buffer export).

Well, another thing is that array shapes are also limited by this, and it would also remove the ability to do `arr.reshape(-1)` – assuming it is no-copy or you have enough memory.
