### ISSUE TITLE
Ambiguous documentation example for `array_split`

### ISSUE THREAD

**Issue by ZeliTheZealot** [numpy/numpy#17001]
The examples make it unclear as to whether `array_split`, with arguments `ary` and `n`, splits `ary` into

1. `n` arrays of near equal size, or
2.  a few arrays of near equal size, with the maximum array length capped at `n`.

### Reproducing code example:

The existing code examples are:
```python
import numpy as np
x = np.arange(8.0)
np.array_split(x, 3)
 #   [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]
x = np.arange(7.0)
np.array_split(x, 3)
 #   [array([0.,  1.,  2.]), array([3.,  4.]), array([5.,  6.])]
```
A better code example is 
```python
import numpy as np
c = np.arange(9)
np.array_split(c, 4)
# [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
```
### Link:
https://numpy.org/doc/stable/reference/generated/numpy.array_split.html

**Comment by eric-wieser** [comment]
Good idea - a documentation PR would be appreciated.
