### ISSUE TITLE
Typo in tutorial-ma.rst

### ISSUE THREAD

**Issue by NikosAlexandris** [numpy/numpy#17003]
In the https://github.com/numpy/numpy/blob/99010006fabea949d13aae8caea10abf97cbaed9/doc/source/user/tutorial-ma.rst tutorial, [line 135](https://github.com/numpy/numpy/blame/99010006fabea949d13aae8caea10abf97cbaed9/doc/source/user/tutorial-ma.rst#L135), the `usecols=(0, 1)` is wrong.

The complete command there is:
```
locations = np.genfromtxt(filename, dtype=np.unicode_, delimiter=",",
                              skip_header=7, usecols=(0, 1),
                              encoding="utf-8-sig")
```
It should be instead `usecols=(0, 2)`, i.e..
```python
locations = numpy.genfromtxt(filename, dtype=numpy.unicode_, delimiter=',',
                              skip_header=7, usecols=range(0,2),
                              encoding="utf-8-sig")
```
so that the following instruction will work as expected:
```python
china_total = nbcases[locations[:, 1] == 'China'].sum(axis=0)
```

**Comment by raisinghanii** [comment]
I am new to open sources contributing,As this is a typo Issue I hope I can solve it. I request to get assigned to solve this issue.

**Comment by rossbar** [comment]
@NikosAlexandris the tutorial in its current form is correct. The form of the columns in the portion of the file that is being read is: `Province/States, Country/Region, WHO region, ...`. We are interested in the first two columns i.e. (0, 1). You can convince yourself of this by running the examples on the data; the dataset is located in `doc/source/user/who_covid_19_sit_rep_time_series.csv`.

Please feel free to reopen if you find further potential issues!

**Comment by NikosAlexandris** [comment]
@rossbar Check this out https://gist.github.com/NikosAlexandris/7a527ef48eeecc5d4cd2243091ea7c40.

This is from a Jupyter Notebook. It's strange, isn't it?

**Comment by NikosAlexandris** [comment]
Or actually here: https://gesis.mybinder.org/binder/v2/gh/ipython/ipython-in-depth/7e5ce96cc9251083979efdfc393425f1229a4a68?filepath=binder%2Fissue_with_numpy.genfromtxt_usecols.ipynb

**Comment by melissawm** [comment]
@NikosAlexandris your code is different than what is on the tutorial. You use `usecols=range(0, 1)` instead of `usecols=(0, 1)`, and I that's why you get the different result.

**Comment by NikosAlexandris** [comment]
@melissawm Thank you so much for your attention!

(@self: strange how this `range()` got on the way...)
