### ISSUE TITLE
BUG: datetime64, timedelta64 comparisons do not return NotImplemented

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#17017]
I expected datetime64 and timedelta64 comparison methods to return NotImplemented when operating with pd.NaT, which has `__array_priority__ = 100`.

```
import numpy as np
import pandas as pd

ts = np.datetime64("now", "ns")
td = np.timedelta64(0, "ns")

assert pd.NaT.__array_priority__ == 100

>>> ts.__lt__(pd.NaT)
array(False)

>>> td.__lt__(pd.NaT)
array(False)
```

**Comment by seberg** [comment]
@jbrockmendel hmm, the code is a bit weird. but effectively will do:
```
def __lt__(self, other):
    arr = np.asarray(self)
    return arr < other
```
I.e. it seems like it should be deferring to the pandas `NaT`, but after converting itself into an array.  Is it possible that this is what happens, but still problematic?

**Comment by seberg** [comment]
That said, I do think it would be fair to defer right away, although this is a common (and sometimes buggy) path currently for when the other object is a scalar not known to NumPy.

**Comment by jbrockmendel** [comment]
> Is it possible that this is what happens, but still problematic?

Seems like a reasonable explanation.  For some reason comparing against Timestamp works as expected

**Comment by seberg** [comment]
Returning an array instead of a scalar here shows that this is all slightly weird... Since its the right thing to do for pandas, but guessing that we should convert that array to a scalar seems only half right (although possibly more right than the current result). OTOH, I guess it doesn't matter too much...
