### ISSUE TITLE
BUG: 32-bit builds are emitting a warning that is not causing the builds to fail

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#17019]
We build 32-bit linux inside a manylinux2010 docker. Randomly checking the build log, I see a [warning](https://dev.azure.com/numpy/numpy/_build/results?buildId=11884&view=logs&j=c4fbb33d-b115-53c9-54fa-705790f154ff&t=1437d177-db37-57b8-1516-a6c596dd8a61&l=4241) from `SeedSequence_get_assembled_entropy`
```
warning: comparison of integer expressions of different signedness: \
    ‘Py_ssize_t’ {aka ‘int’} and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]
     __pyx_t_6 = ((__pyx_t_5 < __pyx_v_self->pool_size) != 0);
```

Two problems: why did the build pass, and why are we using two different types

**Comment by mattip** [comment]
warning, not error

**Comment by mattip** [comment]
The answer to the second question is that our  ["grep-over-the-warnings" script](https://github.com/numpy/numpy/blob/v1.19.1/tools/travis-test.sh#L55) is only run in travis, and this runs in Azure.

**Comment by mattip** [comment]
It seems `self.pool_size` is an `int` but `len(x)` returns a `Py_ssize_t`

**Comment by bashtage** [comment]
pool_size is `uint32_t`

https://github.com/numpy/numpy/blob/4f2b219647ae6a7928590be2b709894ae2403274/numpy/random/bit_generator.pxd#L26

Should be Py_ssize_t.  Free change since no one will be using a pool size of 2*31 or 2**32.
