### ISSUE TITLE
Sigmoid Function in Numpy

### ISSUE THREAD

**Issue by Srikeshram** [numpy/numpy#17034]
**Sigmoid** activation plays a vital role in the Machine Learning....But the **numpy** library does not have the in-built function to calculate the sigmoid function of a number.So I want to contribute the code for the sigmoid to the numpy library.Please Assign this issue to me....

**Comment by eric-wieser** [comment]
Are you looking for `np.tanh`?

**Comment by Srikeshram** [comment]
No...Sigmoid Function which is used as the activation function for the output layer in the Deep Learning and it is used for **Logistic Regression**
Sigmoid= y=1/(1+e^(-x))
![Unipolar-sigmoid-function](https://user-images.githubusercontent.com/63420229/89733974-b8d22f80-da76-11ea-8fb4-cf89401f50b0.png)

**Comment by rgommers** [comment]
You want `scipy.special.expit`. SciPy docs enhancements to make it more discoverable are welcome, but it already has "sigmoid" in the docstring so not sure there's more to do there.

We won't be adding deep learning specific activation functions to NumPy.
