### ISSUE TITLE
np.random.randint fails with large integers with default dtype on Windows

### ISSUE THREAD

**Issue by asishm** [numpy/numpy#17038]
np.random.randint results in ValueError when specifying arguments that overflow int32 on Windows. I've seen some related discussions around the platform dependent default int behavior (#9464, #12332, #16535). If this classifies as a duplicate of the issues I've referenced, feel free to close this. (similar issue happens when creating an arrays of small integers which defaults to a dtype of int32, but you run into np.prod returning 0 if it overflows, but that's a separate discussion.)

Right now code written on Linux won't work on Windows platforms (assuming both are 64 bit).

### Reproducing code example:

```python
import numpy as np
np.random.randint(34353543525, 5465445754, size=5)
```

### Error message:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-38-47b726322196> in <module>
----> 1 np.random.randint(34353543525, 5465445754, size=5)

mtrand.pyx in numpy.random.mtrand.RandomState.randint()

_bounded_integers.pyx in numpy.random._bounded_integers._rand_int32()

ValueError: high is out of bounds for int32
```

### Numpy/Python version information:

1.18.1 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]

**Comment by mahendran-narayanan** [comment]
The default dtype value is int32. You can change the default value like this.

`np.random.randint(34353543525, 5465445754, size=5,dtype=np.int64())`

In this code the value of `low > high`. This also results in `ValueError` 

Low has 11 digits whereas high has 10 digits.

**Comment by mattip** [comment]
Use the [new APIs](https://numpy.org/devdocs/reference/random/new-or-different.html). This, for example works on numpy 1.19.1 on 32-bit windows, without needing a dtype (note I changed `high` to be greater than `low`):
```
> python.exe
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.19.1'
>>> rng = np.random.default_rng()
>>> rng.integers(34353543525, 45465445754, size=5)
array([39465619412, 41951588483, 43995292305, 44838963907, 39107527584],
      dtype=int64)
```

**Comment by bashtage** [comment]
> The default dtype value is int32. You can change the default value like this.
> 
> `np.random.randint(34353543525, 5465445754, size=5,dtype=np.int64())`
> 
> Even after change it results in `ValueError`.
> 
> Low has 11 digits whereas high has 10 digits.


You are getting a ValueError because your low, the first value, is larger than the high, the second value. low must be < high.

```
34353543525
5465445754
```

```
np.random.randint(5465445754, 34353543525, size=5,dtype=np.int64())
Out[8]: 
array([29587182839, 24577250622, 27288451852, 31989221439, 21562581406],
      dtype=int64)
```

works as expected.

**Comment by mattip** [comment]
Closing.
