### ISSUE TITLE
Segfault when pickling array >2G size

### ISSUE THREAD

**Issue by stphnlyd** [numpy/numpy#17045]
See below for reproducing code. I studied it a little bit and found it caused by this line You see it converts iter->index to int which is 4 bytes
https://github.com/numpy/numpy/blob/00a45b4dca164105b50ba29e1735e96b573b639c/numpy/core/src/multiarray/methods.c#L1619 

btw seems this (int) conversion is used at multiple places like https://github.com/numpy/numpy/blob/00a45b4dca164105b50ba29e1735e96b573b639c/numpy/core/src/multiarray/methods.c#L1639

### Reproducing code example:

To try this you probably need a machine of large memory. Mine is 64GB and I believe 32GB is not enough.

```python
import numpy as np
x = np.empty(2**31+1, dtype='object')
x.__reduce__()
```

### Numpy/Python version information:

1.19.1 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]

**Comment by eric-wieser** [comment]
I suspect this is a holdover from when `PyList_GET_ITEM` accepted `int` and not `Py_ssize_t`.

This looks like a very easy fix (remove the casts), want to make a PR?
