### ISSUE TITLE
Rotation Matrix 

### ISSUE THREAD

**Issue by Yukti-09** [numpy/numpy#17043]
The following code creates a rotation matrix in 2D taking the angle as 30 degrees.
```
import numpy as np

theta = np.radians(30)

r = np.array(( (np.cos(theta), -np.sin(theta)),
               (np.sin(theta),  np.cos(theta)) ))

print('rotation matrix:')
print(r)
```
Output:
```
rotation matrix:
[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]
```
We can add a single function that takes the angle and dimension as the input and returns a rotation matrix.

**Comment by seberg** [comment]
Scipy has toold around rotation matrices, not quite sure if this exactly, but I expect so, and if not it would be a much better place due to that.

**Comment by rgommers** [comment]
Hi @Yukti-09, please use the `Rotation` class in `scipy.spatial.transform` for that.

We won't add functionality to NumPy that's already in SciPy, so I'll close this issue.

**Comment by eric-wieser** [comment]
Scipy doesn't seem to have anything to construct a 2D rotation, which feels like a slight omission...

But agreed this doesn't belong in `numpy`.

**Comment by Yukti-09** [comment]
I'll raise the issue in Scipy. Thank you for your help!
