### ISSUE TITLE
BUG: Modified bessel function i0 broken for complex inputs

### ISSUE THREAD

**Issue by peterbell10** [numpy/numpy#17060]
### Reproducing code example:

From the [docstring](https://numpy.org/doc/stable/reference/generated/numpy.i0.html):

```python
>>> np.i0([0., 1. + 2j])
```

The expected result should be complex:
```python
array([ 1.00000000+0.j        ,  0.18785373+0.64616944j])  # may vary
```

Whereas the actual result is real:
```python
array([1.       , 2.6993365])
```

From the history, this was broken by gh-11233 which changed `x[x < 0] = -x[x < 0]` into `x = np.abs(x)`.

### Numpy/Python version information:

```
1.19.1 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
Are you sure this function is well defined on complex inputs?

Scipy doesn't seem to implement it either:
```
In [46]: scipy.special.i0
Out[46]: <ufunc 'i0'>

In [47]: scipy.special.i0.types
Out[47]: ['f->f', 'd->d']
```

**Comment by peterbell10** [comment]
Well the docstring specifically mentions support for complex inputs, so I don't see why not.
