### ISSUE TITLE
ENH: Policy on tools that share information with commercial firms

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#17066]
No policy is in place on whether it's permissible to use tools like Google Analytics or Algolia search that send information to a commercial firm.

Without a policy, the issue can be raised and argued repeatedly, with inconsistent outcomes.

NumPy (Steering Council?) should lay down under what conditions, if any, this kind of use is acceptable.

**Comment by eric-wieser** [comment]
I think we need to be precise here - from most to least objectionable, there are many actions which _could_ share information with commercial firms:

* Using numpy
* Installing numpy
* Building numpy 
* Opening numpy HTML build artifacts
* Accessing the public numpy webpage
* Numpy development activity on github

**Comment by bjnath** [comment]
@eric-wieser If these questions are for me, I should clarify that I have no feelings on this and no wish to draft policy. I am trying to avoid skirmishes that can keep cropping up and ending in ad-hoc decisions. 

@mattip The community would benefit from clarity on the limits you'd like to see.  Where do you draw the line, so that others can apply the same rules?

For instance, Zoom and Slack are commercial tools; are they inside or outside the zone of exclusion, and on what basis?

**Comment by rgommers** [comment]
> I think we need to be precise here - from most to least objectionable, there are many actions which _could_ share information with commercial firms:
> 
>     * Using numpy
> 
>     * Installing numpy
> 
>     * Building numpy


Good point. All the above, which are about using NumPy the library, don't have and must not have any telemetry involved (with the exception of if you invoke a tool that access a package repository like PyPI or anaconda.org).

>     * Opening numpy HTML build artifacts

this one may be a special case, depending on whether you mean locally or as hosted under numpy.org

> 
>     * Accessing the public numpy webpage
> 
>     * Numpy development activity on github

This is interacting with NumPy the project. We make use of GitHub, Google Analytics, Zoom, Slack, HackMD, etc. - we are mindful of privacy but have no policy for or against commercial vs. open source tools. We do what is effective to run our project.

**Comment by bjnath** [comment]
Thanks @rgommers. This is clear and helpful.

**Comment by rgommers** [comment]
Let's keep this open for a little while, it's not like I can/should decide this by myself. My answer is basically the status quo of today. It may be worth having a chat in the community call about this - I'll put it on the agenda.

**Comment by bjnath** [comment]
@rgommers 
> It may be worth having a chat in the community call 

And/or the mailing list.

**Comment by rgommers** [comment]
Discussed in today's Community Call:

- No major disagreement with the discussion above
- Google Analytics: is present on numpy.org. --> seems fine; @mattip is more worried about matching expectations when interacting with something from NumPy (in this case, a user can set their browser to block this stuff if they care, so not much of a worry).
  - For now we're good; if someone wants to put in the work to have a more privacy-sensitive option, they're welcome to do so.
