### ISSUE TITLE
Html docs need canonical URLs

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#17069]
See https://github.com/numpy/numpy/issues/17037#issuecomment-672356421. Basically, we now have stable links, some metadata is needed to tell Google et al. to prefer those pages rather than the release version specific page with the same content.

**Comment by mattip** [comment]
So it seems we need a `<link rel="canonical" href="https://numpy.org/doc/stable/path/to/me.html" />` link in the header of every `path/to/me.rst` file, and the link should be absolute (contains `https://numpy.org`) not relative.

**Comment by mattip** [comment]
xref https://support.google.com/webmasters/answer/139066 from the comment.

**Comment by susan-shu-c** [comment]
I can attempt this if no one has!

**Comment by mattip** [comment]
@susan-shu-c we don't really assign issues, help is welcome. We do appreciate that getting started with NumPy can be challenging, so please feel free to submit a PR, even if it is clearly wrong, and ask for help. 

We have a general overview of how to contribute [here](https://numpy.org/doc/stable/dev/index.html). Since this is a documentation issue, you will want to also read about [building the docs](https://numpy.org/doc/stable/dev/index.html#building-docs) locally.

**Comment by bjnath** [comment]
> link in the header of every path/to/me.rst file

@mattip Could you clarify what you mean by the "header" of an `rst` file?

**Comment by mattip** [comment]
@bjnath great question, it seems the PR author figured out it should actually be in the `layout.html` template.

**Comment by eric-wieser** [comment]
Should we omit canonical urls for https://numpy.org/devdocs/index.html, so that google still indexes the top-level pages separately?

**Comment by mattip** [comment]
Reopening. gh-17210 should take care of the HEAD documents available as https://numpy.org/devdocs/, but we should also add that tag to all the documents in the directories of https://github.com/numpy/doc.

**Comment by susan-shu-c** [comment]
Good point, I could take a look at that as well

**Comment by pv** [comment]
rel=canonical is already added by https://github.com/numpy/doc/blob/master/_static/versionwarning.js_t

**Comment by mattip** [comment]
... And I was the one to merge it in numpy/doc#7. So this issue was based on only looking at sources and the PR should be reverted :( Sorry for my short memory.

**Comment by susan-shu-c** [comment]
Glad it's all sorted out (in this case, remembered) regardless! 😁
