### ISSUE TITLE
difference between vectorize and frompyfunc

### ISSUE THREAD

**Issue by FrankHui** [numpy/numpy#17071]
### Reproducing code example:

```python
import numpy as np
import pandas as pd


class T:
    def __init__(self, val):
        self.val = val

    def add(self):
        self.val += 1


def add(instance):
    instance.add()
    return instance


df = pd.DataFrame(data=[T(1), T(2)], columns=['t'])
df['t'] = np.vectorize(add)(df['t'])
print(df['t'].apply(lambda x: x.val).values)  # [3, 3], T(1) adds twice

df = pd.DataFrame(data=[T(2), T(1)], columns=['t'])
df['t'] = np.vectorize(add)(df['t'])
print(df['t'].apply(lambda x: x.val).values)  # [4, 2], T(2) adds twice

df = pd.DataFrame(data=[T(1), T(2)], columns=['t'])
df['t'] = np.frompyfunc(add, 1, 1)(df['t'])
print(df['t'].apply(lambda x: x.val).values)  # [2, 3] which is expected

```

np.vectorize(add) makes first instance of the series adds twice, while np.frompyfunc(add, 1, 1) works.
It's really interesting...

**Comment by eric-wieser** [comment]
This is documented behavior:

> If otypes is not specified, then a call to the function with the first argument will be used to determine the number of outputs. The results of this call will be cached if cache is True to prevent calling the function twice. However, to implement the cache, the original function must be wrapped which will slow down subsequent calls, so only do this if your function is expensive.

`frompyfunc` only supports `dtype=object`, so doesn't need to call the function to work out the number of outputs and result types.

The docs could maybe be a little clearer here.

**Comment by FrankHui** [comment]
I see. Many thanks for quick response.
