### ISSUE TITLE
user/index and user/tutorials_index toctrees overlap

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#17077]
The `user/index` toctree:

https://github.com/numpy/numpy/blob/0311c93c8c43cd913303c529673d69575901475e/doc/source/user/index.rst#L14-L26

Inlcudes `user/tutorials_index`, which includes many of the same pages

https://github.com/numpy/numpy/blob/0311c93c8c43cd913303c529673d69575901475e/doc/source/user/tutorials_index.rst#L11-L20

Pages should have only one toctree parent, not two. We need to decide just one place to put:

* basics 
*    misc 
*    numpy-for-matlab-users 
*    building 
*    c-info

**Comment by eric-wieser** [comment]
Introduced by #15843, ping @melissawm

**Comment by melissawm** [comment]
Woops. Will fix shortly, thanks for the ping @eric-wieser !
