### ISSUE TITLE
ValueError: Seed must be between 0 and 2**32 - 1

### ISSUE THREAD

**Issue by anasalzuvix** [numpy/numpy#17079]
When i set 
numpy.random.seed(4294967296) in my program and try to Generate an Array then i get this error 
```
  File "mtrand.pyx", line 244, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1
```
is it possible to Generate a numpy array with seed(4294967296) or more?

**Comment by mattip** [comment]
You should be using the [newer API](https://numpy.org/devdocs/reference/random/new-or-different.html#new-or-different) rather than `numpy.random`, so
```
rng = numpy.random.default_rng(numpy.random.SeedSequence(4294967296))
```

which can be shortened to 
```
rng = numpy.random.default_rng(4294967296)
```

**Comment by anasalzuvix** [comment]
> You should be using the [newer API](https://numpy.org/devdocs/reference/random/new-or-different.html#new-or-different) rather than `numpy.random`, so
> 
> ```
> rng = numpy.random.default_rng(numpy.random.SeedSequence(4294967296))
> ```
> 
> which can be shortened to
> 
> ```
> rng = numpy.random.default_rng(4294967296)
> ```

thanks a lot
