### ISSUE TITLE
ENH, DOC: Adding new templates for issues

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#17073]
NumPy's [contributor guide](https://numpy.org/devdocs/dev/index.html) says the following:

> If your commit introduces a new feature or changes functionality, post on the mailing list to explain your changes. For bug fixes, documentation updates, etc., this is generally not necessary, though if you do not get any reaction, do feel free to ask for review.

Sometimes users don't see this, and end up proposing new features without prior discussion. Using better issue templates might help minimize this and direct users to the right forum or project.

As an example, when [opening a new issue in PyTorch](https://github.com/pytorch/pytorch/issues/new/choose), one is presented a set of options to choose from: Bug, Feature Request, Documentation and Question/Support. 

![PyTorch New Issue templates](https://i.imgur.com/aR046YO.png)

NumPy could have the same set of issue types, or a different set. When proposing a new feature, the template should direct users to the mailing list, for example.

**Comment by eric-wieser** [comment]
While a good idea, I think this GitHub feature only works for issues, not PRs - so it won't help with directing PRs to also email the mailing list.

**Comment by melissawm** [comment]
This is true, but the idea is to increase visibility of this recommendation, given that some people reach the repo directly and don't really read the Contributor Guide completely before submitting issues or PR's.
