### ISSUE TITLE
Feature request: Give dimension(s) (optionally) a name

### ISSUE THREAD

**Issue by sebhahn** [numpy/numpy#17072]
Would it be possible to add a feature to optionally give dimension in numpy arrays a name (or create a array subclass)?

A use case is [creating NetCDF variables](https://unidata.github.io/netcdf4-python/netCDF4/index.html#netCDF4.Group.createVariable) which requires a dimension name (and dtype which is known). I'm using the undocumented `.metadata` field in `np.dtype` for this kind of information at the moment, which is kind of awkward. BTW xarray could benefit also from this feature as well, because creating an xarray data structure (e.g. [a DataArray](http://xarray.pydata.org/en/stable/data-structures.html#creating-a-dataarray)) also requires to define/know dimension name(s).

**Comment by rgommers** [comment]
That's been discussed for about 15 years, and many attempts have been made. The answer at this point in time is: use Xarray is you want named axes.

**Comment by sebhahn** [comment]
Oh :disappointed: 

Maybe make a final attempt?

**Comment by eric-wieser** [comment]
Is using `xarray` not an option for you?

**Comment by sebhahn** [comment]
actually I'm about to change using it, but I don't see the point to go from numpy -> xarray -> netCDF4 just to get a less [messy interface/code](https://github.com/TUW-GEO/pynetcf/blob/master/src/pynetcf/point_data.py#L264) (i.e. not using `numpy.dtype.metadata`) to get dimension names for an array, which finally should be used to create a netCDF4 variable.

Maybe there is a more elegant way (without xarray), and that's why I was asking my initial question.

**Comment by eric-wieser** [comment]
In case you missed it, `xarray` has [builtin netCDF support](http://xarray.pydata.org/en/stable/io.html).

**Comment by eric-wieser** [comment]
In fact, it even has support for the climate and forecast conventions that your package is about: http://xarray.pydata.org/en/stable/weather-climate.html

**Comment by sebhahn** [comment]
I know, we developed our package at the same time xarray became popular. What we needed was to support reading/writing time series NetCDF data in [indexed ragged or contiguous ragged format](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#time-series-data) which is not supported by xarray out of the box. At some point we might change to xarray as a backend for our package, but so far our packaged worked fine for us
