### ISSUE TITLE
vdot returns incorrect results on ppc64le

### ISSUE THREAD

**Issue by QuLogic** [numpy/numpy#17087]
### Reproducing code example:

```python
import sys

import numpy as np


if len(sys.argv) > 1:
    shape = (int(sys.argv[1]), )
else:
    shape = (20,)

np.random.seed(1337)
x = 2 * np.random.random((2,) + shape) - 1
x = x[0] + 1j * x[1]
y = 2 * np.random.random((2,) + shape) - 1
y = y[0] + 1j * y[1]

print('x', x)
print('y', y)
print('xy', np.vdot(x, y))
print('yx', np.vdot(y, x))
```

### Error message:

On x86_64, this returns the same results for `xy` and `yx`, with the sign of the imaginary component flipped:
```
$ python3 check.py
x ...
y ...
xy (0.38772781971416226-0.306563166009585j)
yx (0.38772781971416226+0.306563166009585j)
```
but on ppc64le, the results are inconsistent:
```
$ python3 /check.py 
x ...
y ...
xy (0.38772781971416226+0.41646398560368747j)
yx (0.38772781971416226+0.6851997484294434j)
```
(I left out `x` and `y` because they were the same across the platforms.)

The cutoff appears to be at 8 values:
```
$ python3 /check.py 7
x ...
y ...
xy (-2.431549937460346+0.8398024431551804j)
yx (-2.431549937460346-0.8398024431551804j)

$ python3 /check.py 8
x ...
y ...
xy (1.8625629165512865+1.7376479099330644j)
yx (1.8625629165512865-0.17989740020617262j)
```

### Numpy/Python version information:

This fails on Fedora 32, with:
```
1.18.4
3.8.5 (default, Jul 31 2020, 00:00:00) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

This _works_ on Fedora 31 with 1.17.4.

**Comment by charris** [comment]
How did you install NumPy?

**Comment by QuLogic** [comment]
Those are the Fedora packages. I am trying to install via `pip` to test, but since there are no wheels, that will take some time.

**Comment by mattip** [comment]
The 7 - 8 change makes me suspect some issue with a bad optimization that kicks in with 8 values. Are you using any blas accelerator?

**Comment by seberg** [comment]
Sounds like this was an OpenBLAS issue or so, so going to close, as I doubt there is anything to do for us.

(Unless it persists with up to date wheels, but can't check that easily.)
