### ISSUE TITLE
BUG: f2py fails with gfortran version >= 10 under windows | Checked up to numpy version 1.18.5

### ISSUE THREAD

**Issue by MGStruct** [numpy/numpy#17081]
Dear numpy Team,

I encountered the following error/bug while using f2py with a recent gfortran compiler (the latest MSYS2/Ming64 version). The compilation fails due to an unknown compiler flag, namely ="-mno-cygwin". This bug was originally fixed years ago [Link](https://f2py-users.cens.ioc.narkive.com/3hJhBZc1/mno-cygwin), but the fix has not aged well.

### Reproducing code example:

The problem is the following snippet from gnu.py. v[1] contains a string with the current version of gfortran (e.g. 9.02.00). However, the if statement evaluates to false with version 10.xx.xx. 

```python
class Gnu95FCompiler(GnuFCompiler):
    compiler_type = 'gnu95'
    compiler_aliases = ('gfortran', )
    description = 'GNU Fortran 95 compiler'

    def version_match(self, version_string):
        v = self.gnu_version_match(version_string)
        if not v or v[0] != 'gfortran':
            return None
        v = v[1]
        if v >= '4.':
            # gcc-4 series releases do not support -mno-cygwin option
            pass
        else:
            # use -mno-cygwin flag for gfortran when Python is not
            # Cygwin-Python
            if sys.platform == 'win32':
                for key in [
                        'version_cmd', 'compiler_f77', 'compiler_f90',
                        'compiler_fix', 'linker_so', 'linker_exe'
                ]:
                    self.executables[key].append('-mno-cygwin')
        return v
```

### Error message:

The compilation fails with exit code 1. 

### Numpy/Python version information:

Checked up to version 1.18.5.

Kind regards

**Comment by eric-wieser** [comment]
Fixed in #16468 I think.

**Comment by melissawm** [comment]
Hi @MGStruct , can you confirm that the fix linked above resolves your issue? Thanks!

**Comment by carlkl** [comment]
Works for me with Msys2 gcc-12 and a recent numpy.

I propose to close this issue.
