### ISSUE TITLE
Gauss-Hermite quadrature initialization fails after creating a plot with dashed lines

### ISSUE THREAD

**Issue by ndalchau** [numpy/numpy#17082]
I have unearthed a very strange problem when combining using Gauss-Hermite quadrature in a script that also does some plotting. 

#### Minimal example
``` python 
import matplotlib.pyplot as plt
import numpy as np
plt.plot([0, 1], [0, 1], 'k--')
degree = 11
np.polynomial.hermite.hermgauss(degree)
```

#### Error message 
```
Traceback (most recent call last):
  File "..\TransfectionOXB\np_bug.py", line 5, in <module>
    np.polynomial.hermite.hermgauss(degree)
  File "c:\depot\XXX\venv\lib\site-packages\numpy\polynomial\hermite.py", line 1586, in hermgauss
    x = la.eigvalsh(m)
  File "<__array_function__ internals>", line 6, in eigvalsh
  File "c:\depot\XXX\venv\lib\site-packages\numpy\linalg\linalg.py", line 1176, in eigvalsh
    w = gufunc(a, signature=signature, extobj=extobj)
  File "c:\depot\XXX\venv\lib\site-packages\numpy\linalg\linalg.py", line 94, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.LinAlgError: Eigenvalues did not converge
```

#### Surprising workarounds/fixes
I have no idea why there is any dependency of hermgauss on matplotlib, but the following observations make this even more surprising:
- Using `degree` < 10 resolves the problem
- Changing the plot format from `--` to `-` (or anything else) also resolves the problem

#### Version information
I believe this is a problem on Windows only, as a colleague using Windows verified this bug on his system, while a mac user did not receive any error message. 
I'm currently using:
- Windows 10 Enterprise, version 2004, OS build 19041.450
- python version 3.7.8
- numpy version 1.19.1
- matplotlib version 3.3.1

I've tried it on a few other versions of numpy and matplotlib, but there is no difference.

**Comment by charris** [comment]
What Windows version are you running? There have been problems reported against latest Windows update that we have been unable to track down. This sounds a bit different because of the matplotlib dependence, but who knows.

**Comment by ndalchau** [comment]
I'm on Windows 10 Enterprise, version 2004. The OS build is 19041.450.

**Comment by charris** [comment]
That is the Windows version that has been causing problems, see #16744.

**Comment by ndalchau** [comment]
Thanks for pointing me to this potentially related issue. I'll try and locate a Windows machine running something pre-2004/19041, to confirm it is the same problem.

**Comment by ndalchau** [comment]
I ran the script on a fresh Windows installation, build 17763.1397. No problems! So this is probably related to #16744.

**Comment by krazyeom** [comment]
I've not got any issue using this version of [numpy+mkl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy )

**Comment by charris** [comment]
Closing as a duplicate, thanks for the report.

**Comment by krazyeom** [comment]
> I ran the script on a fresh Windows installation, build 17763.1397. No problems! So this is probably related to #16744.

https://support.microsoft.com/en-us/help/4565349/windows-10-update-kb4565349

Build 17763.1397 is only for Windows 10, version 1809(Applies to: Windows 10, version 1809, all editionsWindows Server version 1809Windows Server 2019, all editions). 
There is no issues in this case for windows 10, version 1809.

**Comment by krazyeom** [comment]
https://support.microsoft.com/en-us/help/4566782
August 11, 2020—KB4566782 (OS Build 19041.450). 

I have still same issue on Windows 10, Version 2004

![image](https://user-images.githubusercontent.com/442477/91782991-adb78d00-ec39-11ea-8f44-e3e9c4ca4508.png)
