### ISSUE TITLE
Need to update NumPy for Matlab users documentation

### ISSUE THREAD

**Issue by cooperrc** [numpy/numpy#17094]
The current [NumPy for Matlab users](https://github.com/numpy/numpy/blob/master/doc/source/user/numpy-for-matlab-users.rst) is out of date. 

The discussion regarding `matrix` vs `array` can be ~~removed~~ edited, since we suggest all users employ `array`. The table of equivalent commands needs a review and update.

**Comment by rossbar** [comment]
> The discussion regarding matrix vs array can be removed, since we suggest all users employ array.

Just to chime in here - I'd be against *removing* [this section](https://github.com/numpy/numpy/blob/master/doc/source/user/numpy-for-matlab-users.rst#array-or-matrix-which-should-i-use) as it is a useful reference of the differences between matrices and arrays. Unfortunately `numpy.matrix` still pops up quite often in the wild (I've seen it most often with the `todense` method of `scipy.sparse` matrices). I'm all for stronger language (`matrix` should not be used in new code), but would be -1 on removing the listing of the distinctions entirely.

**Comment by 8bitmp3** [comment]
Agree with @cooperrc - it's good to distinguish `numpy.matrix` vs `numpy.array`, since an array can be N-dimensional (and form a matrix or a tensor).

Also agree with @rossbar re: `numpy.matrix`. NumPy has an object called `matrix` but the generally accepted practice is use to arrays, such as `numpy.array()`

**Comment by cooperrc** [comment]
> 
> Just to chime in here - I'd be against *removing* [this section](https://github.com/numpy/numpy/blob/master/doc/source/user/numpy-for-matlab-users.rst#array-or-matrix-which-should-i-use) as it is a useful reference of the differences between matrices and arrays. Unfortunately `numpy.matrix` still pops up quite often in the wild (I've seen it most often with the `todense` method of `scipy.sparse` matrices). I'm all for stronger language (`matrix` should not be used in new code), but would be -1 on removing the listing of the distinctions entirely. 


I have no problem leaving it, but `np.matrix` just seemed so limited. 

I hadn't seen a use case for `np.matrix` when converting a Matlab user to NumPy user. The main user difference I notice is that Matlab arrays are always >1D, while NumPy arrays are >0D. I see now that `np.matrix` results in 2D arrays, similar to a default Matlab array. 

For reference, NumPy

```
>>> np.shape(np.array([1,2,3]))
(3,)
```

Vs Matlab

```
>>> shape([1,2,3])
(1,3)
```

Vs `np.matrix`
```
np.shape(np.matrix([1,2,3]))
(1,3)
```

**Comment by bjnath** [comment]
Scattered Matlab references appear on other pages; for instance

[To ignore NaN values (MATLAB behavior), please use nanmax.](https://numpy.org/doc/stable/reference/generated/numpy.amax.html)

If that information isn't already on the Matlab page, it should be added.

Moreover, once it's been added,  it should be removed from the original page: 
* It's done inconsistently. Users can't (and shouldn't) count on seeing Matlab differences for every routine where they might exist. Dropping them in once in a while is therefore unhelpful.
* It's a maintenance headache; it's easy for such references to silently fall out of date. A Matlab page can fall out of date, too, but it's obvious.

**Comment by eric-wieser** [comment]
I think emphasizing the difference from matlab in the function docstring provides a fair bit of value, it would be a shame to lose that.

> It's a maintenance headache; it's easy for such references to silently fall out of date. A Matlab page can fall out of date, too, but it's obvious.

I'd argue the reverse - typically things fall out of date because the numpy function changes. If the matlab comparison was next to the implementation, it has a far greater chance of being updated than if it's in a forgotten doc page somewhere.

It would be great if the matlab behavior page could compile a list of references to matlab from other documentation pages. That should be well within the grasps of a sphinx plugin.

**Comment by bjnath** [comment]
> forgotten doc page

Matlab users say they constantly refer to this page.


> would be great if the matlab behavior page could compile a list of references to matlab from other documentation pages


It would be great not to refer to Matlab at all except on a page dedicated to Matlab. A line like this:

> To ignore NaN values please use nanmax.

is extremely helpful and should stay in. Matlab users will wonder how to ignore NaN values and this will tell them. If they don't know what their tool does it's not our role to instruct them.

**Comment by cooperrc** [comment]
> I think emphasizing the difference from matlab in the function docstring provides a fair bit of value, it would be a shame to lose that.

@eric-wieser, there are a lot of NumPy functions that seem to be built to parallel Matlab functions. In that sense, if the original intention was to create a Matlab-style NumPy equivalent, then maybe its worth keeping the reference in the docstring. 

> It would be great not to refer to Matlab at all except on a page dedicated to Matlab. A line like this:
> 
> > To ignore NaN values use nanmax.
> 
> is extremely helpful and should stay in. Matlab users will wonder how to ignore NaN values and this will tell them. It's not our job to provide Matlab instruction to users who don't know what their tool does.

@bjnath, you have a valid point. The goal of NumPy docs is to tell the general user how to use NumPy, not how the functions relate to Matlab. As a parallel, but somewhat related point, we don't provide R or Mathematica translations in the docstrings. I don't think it hurts to have a reference to Matlab in the docstrings, but I would like to hear from others about their thoughts. 

Either way, I think it may be nice to create a "Matlab-map" in the NumPy for Matlab users doc. Right now its a static table that needs updating, but maybe we could create a Matlab tag that updates if a function can supplement a Matlab-style function.

**Comment by cooperrc** [comment]
Following up on where MATLAB references show up. Currently, there are 7 `MATLAB` references I found with a quick grep:

`$ grep "MATLAB" ./build/testenv/lib/python3.8/site-packages/numpy/*/*.py`

```
core/fromnumeric.py:    diag : MATLAB work-a-like for 1-D and 2-D arrays.
core/fromnumeric.py:    (MATLAB behavior), please use nanmax.
core/fromnumeric.py:    (MATLAB behavior), please use nanmin.
lib/npyio.py:    scipy.io.loadmat : reads MATLAB data files
lib/twodim_base.py:    diag : MATLAB work-alike for 1-D and 2-D arrays.
linalg/linalg.py:    the symbols defined above). This is the algorithm MATLAB uses [1].  It also
linalg/linalg.py:    .. [1] MATLAB reference documention, "Rank"
```
