### ISSUE TITLE
numpy-1.18.5 download installs numpy-1.18.5-py38h6530119_0 with missing Lib and Scripts folders when via anaconda3 / condaforge (with good numpy-1.18.5-py38h72c728b_0) 

### ISSUE THREAD

**Issue by Joan-Millington** [numpy/numpy#17098]
anaconda3 conda-forge numpy-1.18.5 install downloads numpy-1.18.5-py38h6530119_0 with missing Lib and Scripts folders (plus numpy-1.18.5-py38h72c728b_0 = good)

numpy-1.18.5-py38h6530119_0 only has info folder.

(Sorry if you already know about or have fixed it. I logged initially with anaconda, then conda-forge by mistake. I haven't checked to see if it is still an issue because I don't want to mess-up numpy again (it is running okay after full uninstall, folder delete etc. and re-install, deleting numpy-1.18.5-py38h6530119_0).

I had a usual numpy error message, could have been many reasons. I fixed by the complete uninstall of all python and anaconda software, folder deletion etc, then re-install, frequently deleting numpy-1.18.5-py38h6530119_0 which kept downloading at each stage.

**Comment by isuruf** [comment]
This is not an issue. `numpy` `py38h6530119_0` from defaults is an empty package with a requirement of `numpy-base` which has all the files in it. There's no `numpy-base` in conda-forge.

**Comment by Joan-Millington** [comment]
Thank you for the update. Joan.
