### ISSUE TITLE
ENH: Make numpy scalars subtypes of their builtin counterpart during type checking

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#17105]
This issue proposes making `np.generic`s subclasses of their respective builtin counterpart during the process type checking.

Numpy has a number of `np.generic` subclasses which is serve as counterpart to certain builtin objects (_e.g._ `builtins.int` & `np.int64`) and whenever a builtin scalar is expected it can generally be substituted for its numpy-based counterpart.
One of the situations where things become more difficult is static typing, as this requires explicit specifying both classes as valid types, lest a passed object might be rejected static type checkers such as mypy:

``` python
In [1]: import numpy as np
   ...: from typing import Union

In [2]: def func(a: Union[int, np.int64]) -> None:  # This can quickly get rather ugly
   ...:     pass
   ...:
```

https://github.com/numpy/numpy/pull/17096 was created in order to make this process a bit smoother; so that the same `Union`s don't have to be redefined every single time. However, a simpler solution (which I'm proposing here instead) would be to make certain `np.generic` subclasses a subclass of their respective builtin counterpart for the purpose of type checking (this will _not_ affect the classes' runtime behavior). 
Note that `mypy` already does something similar for the buitin numerical types, _.e.g._ it considers `int` a subclass of float` and `float` a subclass of `complex` (even though this is, strictly speaking, incorrect).

This approach has the following advantages:

1. It improves general readability: `Union[cls_builtin, cls_np]` simply becomes `cls_builtin`.
2. It takes advantage of the fact that, generally speaking, builtin scalars can be substituted for their `np.generic`-based counterpart without issue.
3. It will substantially increase the compatibility of numpy scalars with functions as typed by third-parties. To illustrate this point the example below provides a very reasonable annotated function; yet (in its current state) the likes of `mypy` will raise an error here.

``` python
In [1]: import numpy as np

In [2]: def func(a: int) -> int:
   ...:     return a * 2
   ...:

In [3]: func(np.int64(1))  # mypy(error): Argument 1 to "func" has incompatible type "int64"; expected "int"
Out[3]: 3
```

Example Implementation
--------------------------
``` python
class complexfloating(np.inexact, complex): ...
    ...

class str_(np.character, str):
    ...
```

**Comment by eric-wieser** [comment]
Your example confuses me a little - `str_` is _already a subclass of `str`:
```
In [497]: np.str_.__bases__
(str, numpy.character)
```

**Comment by eric-wieser** [comment]
Something to watch out for - would such a change make the following pass mypy?

```python
np.int64(1).to_bytes(2, byteorder='big')
```
`np.int64.to_bytes` does not exist, but `int.to_bytes` does.

**Comment by BvB93** [comment]
> Your example confuses me a little - `str_` is _already a subclass of `str`:

You're right, I'll update it with a better example.

**Comment by BvB93** [comment]
> Something to watch out for - would such a change make the following pass mypy?

It will; like the example you provided above there are a couple of cases where this will result in false positives. (1)
It should however be stressed that same holds for the `int` / `float` situation (_e.g._ `float.is_integer()` exists but `int.is_integer()` does not).

1 Annotating such false positives as, for example, `None` would somewhat alleviate the issue.

**Comment by BvB93** [comment]
Closing this issue for now; feel free to reopen in the future.
