### ISSUE TITLE
execute instance methods by putting their instances in numpy

### ISSUE THREAD

**Issue by FrankHui** [numpy/numpy#17101]
Recently in my work, at first the business logic is easy, so I just put all the attributes in columns of DataFrame, and hanle them by numpy math, which is really fast. Every row is an object to me. 
But as the logic was becoming more and more complicated, the origin way is kind of procedure-oriented and hard to expand for some cases such as two objects have some related operations.
So I turn to OOP and create the class of object, and now it's too slow because of for-loop. I've learned that ufunc implemented for-loop in C language. So I tried a kind of stupid way(method3) as below. 

### Reproducing code example:
```python
import numpy as np
import pandas as pd
import time

PENDING = 0


class Foo:
    def __init__(self, val1, val2):
        self.val1 = val1
        self.val2 = val2
        self.val = PENDING

    def foo(self):
        self.val1 += 1
        self.val2 += self.val1
        self.val = self.val1 / self.val2


nums = 1000000
val1_list = range(nums)
val2_list = range(1, nums + 1)

# method1
df = pd.DataFrame({'val1': val1_list, 'val2': val2_list})
t1 = time.time()
df.loc[:, 'val3'] = df['val1'] + df['val2']
print('method1 takes', time.time() - t1)

# method2
res_list = [Foo(val1, val2) for val1, val2 in zip(val1_list, val2_list)]
t1 = time.time()
for foo_obj in res_list:
    foo_obj.foo()
print('method2 takes', time.time() - t1)

# method3
df = pd.DataFrame(data=[Foo(val1, val2) for val1, val2 in zip(val1_list, val2_list)], columns=['foo'])


def f(obj):
    obj.foo()
    return obj


t1 = time.time()
np.vectorize(f, otypes=[Foo])(df['foo'])
print('method3 takes', time.time() - t1)
```

However, it doesn't work, actually it spends a little more than method1 and method2.
So is it expected and is there any way I can do to take advantage of numpy to speed up while I keep OOP?

**Comment by BvB93** [comment]
Note that `np.vectorize()` is essentially a normal python `for` loop (see the "Notes" section of the [docs](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html)) and offers no advantages in terms of performance.

What you'd probably want to do here is to directly operate on a set of arrays, rather than manually performing element-wise arithmetic. This should be quite a bit faster as it relies on the array's optimized underlying C code.

Examples
----------
``` python

class Foo2(Foo):
    def __init__(self, val1, val2):
        self.val1 = np.array(val1)
        self.val2 = np.array(val2)
        self.val = PENDING

obj = Foo2(val1_list, val2_list)
obj.foo()
```

**Comment by FrankHui** [comment]
For np.vectorize, to be clear, I've learned that it's just basically a elegant for-loop, but it's a for-loop in C, right? Although the content of the loop is in python. So, I think it's supposed to be faster than method2, the pure python for-loop.

If the above were correct, actually what I want to is just speeding up by taking advantage of the for-loop of C, while keeping the OOP. Foo2 can't solve my problem, let me take a more appropriate example, which is more similar with my business logic.
```python
class Node:
    def __init__(self, val, up=None):
        self.val = val
        self.up = up

    def supply(self, qty):
        self.val += qty
        self.up.val -= qty

```
In this example, supply will affect other instance and I guess it can't turned to directly operate on a set of arrays.
So, my core problem is, is numpy's ufunc supposed to speed up a loop over a list of node.supply?

**Comment by seberg** [comment]
Closing, since this seems to have been a question about the speed of vectorize and the fact that it doesn't speed things up significantly.
