### ISSUE TITLE
ppc (32 and 64 bits) test failure: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex64'>,) (Trac #1113)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1711]
_Original ticket http://projects.scipy.org/numpy/ticket/1113 on 2009-05-20 by @dwf, assigned to unknown._

I'm seeing this test fail with a PPC64 build on with a 4-way universal binary Python 2.6.2, r7007. Looks similar to #1636, but it's a complex64 rather than a complex256.

```
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex64'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python64.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/Library/Frameworks/Python64.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/tests/test_umath.py", line 524, in check_loss_of_precision
    assert np.all(d < 1e-15)
AssertionError
```

**Comment by bsipocz** [comment]
I can't test this, but original was reported 10 years ago on a python2.6 build, and other xref issues has been fixed. I suppose it can be closed as obsolete (if not fixed).

**Comment by mattip** [comment]
Closing. We have a PPC64le run in CI (thanks to travisCI) that runs to completion with no failures.
