### ISSUE TITLE
ENH: Add __getitem__ to flatiter type definition

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#17113]
### Reproducing code example:

Run mypy on a simple file

```
import numpy as np

a = np.empty((2,2))
b = a.flat[[0,1]]
```

### Error message:

You will get

```
error: Value of type "flatiter[ndarray]" is not indexable
```

Need to add `__getitem__` to pyi file.

### Numpy/Python version information:

```
1.20.0.dev0+986e533 3.8.3 (default, Jul  2 2020, 16:21:59)
[GCC 7.3.0]
```

**Comment by BvB93** [comment]
Besides  `__getitem__` and `__array__` it also appears that `__len__` is missing.
