### ISSUE TITLE
> Can you show the output of `python -mpip install numpy` ?

### ISSUE THREAD

**Issue by dharmendra-code** [numpy/numpy#17120]
> Can you show the output of `python -mpip install numpy` ?

`Requirement already satisfied: numpy in c:\users\andre\appdata\local\programs\python\python37-32\lib\site-packages (1.18.1)`

_Originally posted by @Andreas-debug in https://github.com/numpy/numpy/issues/15424#issuecomment-578495743_

**Comment by mattip** [comment]
Closing, this seems like a spambot. Please reopen with more context if this is meant to be a valid issue.
