### ISSUE TITLE
Wheel builds are failing on aarch64.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17126]
See https://travis-ci.org/github/MacPython/numpy-wheels/jobs/719738469. The problem seems to be in `TestTrimZeros.test_deprecated[arr1-FutureWarning]`.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mattip** [comment]
To save others a click: the error seems to be that `np.trim_zeros(arr)` is raising `AttributeError("'bool' object has no attribute 'ndim'")` when the test expects that to succeed with a `DeprecationWarning`, where `arr` is `np.random.rand(10).astype(str)`. Apparently it reaches [this line](https://github.com/numpy/numpy/blob/master/numpy/lib/function_base.py#L1650) with `arr is True`. @BvB93 could you take a look? We may want to revert gh-17058 and gh-16911, the behavior of `trim_zeros` is not easily optimized.
