### ISSUE TITLE
function frombuffer have insert double zeros

### ISSUE THREAD

**Issue by l1351868270** [numpy/numpy#17128]
### Reproducing code example:

```python
import numpy as np
val = np.array([300, 14, 14, 1024])
print(val.dtype) # int32
val_bytes = bytes(val)
val_array = np.frombuffer(val_bytes, dtype=np.int32)
print(val_array)  # [ 300    0   14    0   14    0 1024    0]
```
### Error message:
In the windows platform, the val_array is  right: [ 300 14 14 1024]. In the linux platform the val_array is wrong: [ 300    0   14    0   14    0 1024    0]

1.18.1 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0]

**Comment by eric-wieser** [comment]
Your code example is incorrect, on Linux `print(val.dtype) # int32` prints `int64`

**Comment by l1351868270** [comment]
thanks
