### ISSUE TITLE
DOC: redirect notice to `default_rng()` is not linked

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#17140]
From [this documentation page](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html)

![image](https://user-images.githubusercontent.com/425260/90962035-d951af00-e4a4-11ea-8dea-2a45793376c1.png)

None of that message is actually clickable.

**Comment by bashtage** [comment]
I think is because it looks bad to have `:class:~numpy.random.default_rng` in a function doc string.  This note should probably be a See Also with an explainer why to see default_rng

**Comment by kubekmonika** [comment]
I will work on this issue today.

**Comment by h-vetinari** [comment]
While wanting to migrate a library to the new way of the random generators, I wanted to find out since which numpy version the `default_rng` is supported (since I'll have to bump the ancient requirements) - would be super cool if someone could add this information, seeing that this issue concerns that particular docstring already.

**Comment by h-vetinari** [comment]
> I wanted to find out since which numpy version the `default_rng` is supported

Found it with some spelunking: #13840, which first appeared in 1.17.0

**Comment by rkern** [comment]
https://numpy.org/doc/stable/reference/random/

The main entrypoint to the documentation of `numpy.random` mentions 1.17 several times.

**Comment by h-vetinari** [comment]
I saw that afterwards as well, but to me the first place to look is still https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng - would it hurt to add a _New in version 1.17.0_ there?

**Comment by zoj613** [comment]
Maybe not directly related here but I think its worth mentioning in the docs that the random c-api is only available from 1.19.0 onwards. I did not know this until I ran into compile errors because I assumed it has been around since 1.17.0

**Comment by rkern** [comment]
@h-vetinari @zoj613 Please go ahead and open new PRs for the additions that you would like to see.

**Comment by bsipocz** [comment]
I believe all the concerns here are addressed by now (there is both a link and version numbers mentioned), so I'm closing the issue. Please reopen if you think something is still missing.
