### ISSUE TITLE
Fromstring simply ignores invalid data

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1714]
_Original ticket http://projects.scipy.org/numpy/ticket/1116 on 2009-05-23 by @charris, assigned to unknown._

The fromstring ctor operates incorrectly on empty text strings.

```
In [1]: fromstring("", sep=" ")
Out[1]: array([ 0.])

In [2]: fromstring("")
Out[2]: array([], dtype=float64)
```

---

Summary by @seberg:

The remaining issue seems to be that `np.fromstring("1. 2 3 a b c 1.", sep=" ")` will drop remaining data, when it should error. A deprecation on this is probably the way to go.

**Comment by seberg** [comment]
Closing this in favor of gh-6076 (same issue, but much newer).
