### ISSUE TITLE
Original error was: DLL load failed: 找不到指定的模块

### ISSUE THREAD

**Issue by pindaoer** [numpy/numpy#17157]
### ERROR：
2020-08-25 13:54:19,111=====ERROR++++++

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\yuancheng.BDGF-YFXT-TDM1\AppData\Local\Programs\Python\Python37\python.exe"
  * The NumPy version is: "1.18.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: 找不到指定的模块。

### I have a Java Web service that calls a Python script to process the file, and every time I get here, I fail to import numpy, but the other packages are right:

```
Java：
    String[] args = { this.pyEnvironmentPath, this.pyFilePath, uploadPath, configPath, downLoadPath };
      Process pr = Runtime.getRuntime().exec(args);
```

### Strange :
      There was no problem when I opened CMD on the windows server to import NUMPY

**Comment by seberg** [comment]
Sorry you had this issue, but it has been a long time ago, and seems like a setup issue with the environment that the Java Web service runs in anyway.
