### ISSUE TITLE
Assign np.number its own type for comparisons

### ISSUE THREAD

**Issue by njriasan** [numpy/numpy#17156]
Currently numba converts `np.number` to `np.float64` for the purposes of creating a type. However there a certain functions where types are passed as arguments and `np.float64` has a different meaning from `np.number`. Often this means that `np.number` should match all numbers but `np.float64` should not.

This is difficult to handle without providing `np.number` a separate type because types are provided by user code.

### Reproducing code example:

```python
import numpy as np
import numba
>>> numba.core.typing.typeof.typeof(np.number)
class(float64)
>>> numba.core.typing.typeof.typeof(np.int32)
class(int32)
>>> numba.core.typing.typeof.typeof(np.float64)
class(float64)
```

**Comment by eric-wieser** [comment]
Did you mean to open this against `numba/numba`?

**Comment by njriasan** [comment]
Yes. I'm sorry.

**Comment by seberg** [comment]
To be fair, this is proably NumPy's fault to begin with:
```
In [1]: np.dtype(np.number)                                                                                             
Out[1]: dtype('float64')
```
but, since that is very strange I added a DeprecationWarning in master:
```
In [1]: np.dtype(np.number)                                                                                             
<ipython-input-1-6e1c1d6614e3>:1: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  np.dtype(np.number)
Out[1]: dtype('float64')
```
which likely will fix numba as well once done.  The warning is a bit strange, and could be fixed up, the reason is that `np.number` seems only matched indirectly because `floating` is a subclass of it, and I did not realize that.
