### ISSUE TITLE
[Request] Sampling multivariate normal from inverse covariance

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#17158]
The functions for sampling random numbers from a multivariate normal distribution:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.multivariate_normal.html
Take as input a covariance matrix.

In some situations, one has instead the inverse of the covariance matrix (a.k.a. the precision matrix), from which there are efficient ways to transform a random sample of standard normal numbers to the desired multivariate normal distribution without inverting such matrix to restore the original covariance matrix.

Would be nice if the multivariate normal sampling functions would allow passing an inverse covariance too, with a boolean parameter to tell whether the matrix that is being passed is the covariance or the inverse covariance. Maybe also an option for passing the Cholesky decomposition of the covariance if already available.

**Comment by eric-wieser** [comment]
> Maybe also an option for passing the Cholesky decomposition of the covariance if already available.

This was originally part of the PR at https://github.com/numpy/numpy/pull/14197#issuecomment-518886946, looks like we forgot to open a tracking issue when I requested we split it to a future PR.

**Comment by bashtage** [comment]
What is the case for passing the precision? The precision has to be both square rooted and inverted before it can be used to generate normals.  I think there is a good case for letting users pass a square root of a covariance matrix so that no further computation is needed before generating the normals.

**Comment by david-cortes** [comment]
The case is sampling from a multivariate distribution in a situation in which it's easier or already-done to get the inverse of the covariance. For example, suppose you have a logistic regression model and you want to get a sample of the coefficients from it: the variance-covariance matrix of the coefficients is given by `(X.T @ diag(sigm(X@w) * (1-sigm(X@w)) @ X)^-1` - you can already  get the inverse covariance before getting the covariance itself.

Also there's more methods of sampling from the inverse covariance. For example, `multivariate_normal` supports `method="eigh"`. The eigen vectors of the inverse of a matrix are also eigenvectors of the original matrix, and the eigen values of the inverse are one divided by the eigen values of the original. Implementing the "eigh" method from the inverse covariance would be just as fast (only extra step is the division).

**Comment by eric-wieser** [comment]
I think @david-cortes' point about the inverse parametrization is that its easier to do `L = inv(cholesky(precision))` than it is to do `L = cholesky(inv(precision))`, as inverting lower triangular matrices is easy?

I'm not sure that argument actually works though, because numpy has no function inverse specialized to triangular matrices.

**Comment by bashtage** [comment]
> Also there's more methods of sampling from the inverse covariance. For example, multivariate_normal supports method="eigh". The eigen vectors of the inverse of a matrix are also eigenvectors of the original matrix, and the eigen values of the inverse are one divided by the eigen values of the original. Implementing the "eigh" method from the inverse covariance would be just as fast (only extra step is the division).

IMO this is a case of putting too much into NumPy.  The "correct" (MO, of course) path is to support the "factor" method (or "root", or whatever you want to call it) so that users can pass in their pre-factorized covariance so that no further processing is done in `multivariate_normal`. This path allows all of the scenarios to be handled without adding lots of special cases. This also lets users self-handle the case where they know a lot about the structure of the covariance, e.g., it is toeplitz or blocked.

**Comment by MarcoGorelli** [comment]
As far as I understand, one can sample using the inverse covariance matrix without having to invert it. A colleague of mine has such an implementation:

```python
# Generate samples from a multi-variate normal distribution with provided precision matrix WITHOUT inverting
    def _mv_normal_sample(self, mu=0, precision_matrix=None, num_samples=1):

    # Precision matrix must be a square matrix
    assert precision_matrix.shape[0] == precision_matrix.shape[1], 'Precision matrix must be a square matrix'

    dim = precision_matrix.shape[0]

    chol_U = cholesky(precision_matrix, lower=False)

    # Create num_samples iid standard normal vectors
    z_vector_matrix = np.random.normal(loc=0, scale=1, size=[num_samples, dim])

    # Sample from the MV normal with precision matrix by solving the Cholesky decomp for each normal vector
    samples = np.squeeze(np.array(
        [solve_triangular(a=chol_U, b=z_vector_matrix[i, :], unit_diagonal=False) + mu for i in
         range(num_samples)]))

    return (samples)
```

As @david-cortes points out, there are situations in which it would be useful to do this, and having to invert the inverse covariance matrix would be more computationally intensive that sampling using it directly.

Would a PR be welcome?

**Comment by zoj613** [comment]
> As far as I understand, one can sample using the inverse covariance matrix without having to invert it. A colleague of mine has such an implementation:
> 
> ```python
> # Generate samples from a multi-variate normal distribution with provided precision matrix WITHOUT inverting
> def _mv_normal_sample(self, mu=0, precision_matrix=None, num_samples=1):
> 
>     # Precision matrix must be a square matrix
>     assert precision_matrix.shape[0] == precision_matrix.shape[1], 'Precision matrix must be a square matrix'
> 
>     dim = precision_matrix.shape[0]
> 
>     chol_U = cholesky(precision_matrix, lower=False)
> 
>     # Create num_samples iid standard normal vectors
>     z_vector_matrix = np.random.normal(loc=0, scale=1, size=[num_samples, dim])
> 
>     # Sample from the MV normal with precision matrix by solving the Cholesky decomp for each normal vector
>     samples = np.squeeze(np.array(
>         [solve_triangular(a=chol_U, b=z_vector_matrix[i, :], unit_diagonal=False) + mu for i in
>          range(num_samples)]))
> 
>     return (samples)
> ```
> 
> As @david-cortes points out, there are situations in which it would be useful to do this, and having to invert the inverse covariance matrix would be more computationally intensive that sampling using it directly.
> 
> Would a PR be welcome?

Isn't `solve_triangular` a scipy function? I'm not sure numpy uses scipy as a dependency. Also wouldn't it be better to solve multiple right hands sides at once instead of using a list comprehension, and then use `ravel` to reshape to a 1d array?

That said, there is a [paper](https://arxiv.org/pdf/1607.04751v2.pdf) (Algorithm 4) that shows a fast way to sample from a multivariate normal using a structured precision matrix that is a sum of an invertible matrix and a low-rank matrix. In some Bayesian algorithms, the precision has to constructed in this way. So this algorithm might be better in such cases where you have the pieces to make the precision.

**Comment by bashtage** [comment]
It is but it is just a call to a LAPACK function DTRTRS so not technically impossible.  I still think it is too specialized for inclusion in NumPy.  Moreover, if a package wants really fast sampling for a particular covariance/precision structure, it is much simpler to write a low-level, high-performance implementation that can be shipped to users of the downstream package.  This said, I do still there there is a case for the `"factor"` method.

**Comment by bashtage** [comment]
@zoj613 I see you have done exactly that in your implementation. It is nice to see that this feature is being picked up.

**Comment by MarcoGorelli** [comment]
>  I still think it is too specialized for inclusion in NumPy. 

Sure, no worries

> I have an implementation of this here.

Cool, thanks

**Comment by eoghanf** [comment]
I disagree that it is "too specialized to be included in Numpy". The precision matrix parametrization of any statistical model is as natural as the covariance matrix parametrization. There is no good reason to consider the covariance matrix as "natural" and the precision matrix as "specialized". Secondly, a key feature of Numpy is speed and (related to this) scalability. Inverting a matrix is neither fast nor scalable.

**Comment by david-cortes** [comment]
Closing as this is now implemented in the latest version of SciPy through the `Covariance` class which accepts different constructor forms such as precision and Cholesky - example:
```python
import numpy as np
from scipy.stats import multivariate_normal as mvn, Covariance
rng = np.random.default_rng(seed=123)

Precision = rng.standard_normal(size=(5,4))
Precision = Precision.T @ Precision
Cov = Covariance.from_precision(Precision)
mu = rng.standard_normal(size=4)

X = mvn.rvs(mean=mu, cov=Cov, size=10_000, random_state=rng)
np.cov(X, rowvar=False) / Cov.covariance
```
```
array([[0.99898643, 1.0105079 , 0.99282811, 0.98943079],
       [1.0105079 , 1.02823677, 1.01985032, 1.01248909],
       [0.99282811, 1.01985032, 1.00294806, 0.99169528],
       [0.98943079, 1.01248909, 0.99169528, 0.98830811]])
```
