### ISSUE TITLE
numpy.empty has a bug for complex 

### ISSUE THREAD

**Issue by ZHANGGU** [numpy/numpy#17165]
**Numpy version 1.17.3**

np.empty() gives strange behaviours when it is created for "complex" !

Se the enclosed figure, after repetive executation, Fgiure 3 and Figure 7 shows much deviated values as in the plot

### Reproducing code example:
```python
mp_corr2 # a complex vector
obs_4fft = np.empty((nfft, ), dtype='complex')
halvwin = 100
obs_4fft[0:halvwin] = mp_corr2[idx_max:idx_max+halvwin]
obs_4fft[-halvwin::] = mp_corr2[idx_max-halvwin:idx_max]
obs_4fft[halvwin+1:-halvwin] = 0 + 1j*0
plt.figure()
plt.plot(np.real(obs_4fft))
plt.plot(np.imag(obs_4fft))
plt.plot(np.abs(obs_4fft))
```

### Error message:

![image](https://user-images.githubusercontent.com/8365180/91297779-2da7a800-e79f-11ea-882c-ddeb8e2305ad.png)

### Numpy/Python version information:
1.17.3

**Comment by eric-wieser** [comment]
What makes you think `empty` is to blame?

**Comment by eric-wieser** [comment]
Your mistake is that you never set `obs_4fft[halvwin]`
