### ISSUE TITLE
AVX test failures for 32 bit manylinux1 wheels

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17174]
See test [here](https://dev.azure.com/numpy/numpy/_build/results?buildId=12323&view=logs&j=d1321064-f6c3-56b7-0172-6d994d01c836&t=3e664a8f-27c8-559d-01e9-e1651f65562b). The problem is in `TestAVXUfuncs.test_avx_based_ufunc`. Note that the manylinux2010 wheels are fine. One possible solution not providing manylinux1 wheels for NumPy 1.20.

TestAVXUfuncs.test_avx_based_ufunc

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mattip** [comment]
this is the flaky 'reciprocal' ufunc on 32-bits we have seen in other places. like [this issue](https://github.com/MacPython/numpy-wheels/pull/73#issuecomment-596182413) about msse2 flags, [this one](https://github.com/MacPython/numpy-wheels/pull/99#issuecomment-669721208) that seems to be a [problem with older gcc](https://github.com/MacPython/numpy-wheels/pull/99#issuecomment-678765336)

**Comment by mattip** [comment]
I think dropping manylinux1 wheels for linux-32-bit is an option. Should we run it past the mailing list?

**Comment by charris** [comment]
> Should we run it past the mailing list?

Yes, it was one of the options I was considering for 1.20. The other was dropping Python 3.6, at least from the wheels. I think moving to newer compilers is something we need to do when we can.

**Comment by charris** [comment]
I'll make a post.

**Comment by seiko2plus** [comment]
@mattip,
> I think dropping manylinux1 wheels for linux-32-bit is an option

No wait, please assign me to this issue, I will fix it.

**Comment by charris** [comment]
> No wait, please assign me to this issue, I will fix it.

Done. Note that I (we?) were contemplating that even without the 32 bit problems.

**Comment by seiko2plus** [comment]
@charris, this issue will be resolved by #16247, I will reduce the amount of work so it can only cover (sqrt, absolute, square, reciprocal) to speed up the progress since NEON requires a lot of emulations.
