### ISSUE TITLE
numpy.arange not accurate with float values

### ISSUE THREAD

**Issue by dunpealcloud** [numpy/numpy#17189]
when i use numpy.arange create a array,if i set the 0.4 as limit,the array contain 0.4,only 0.4 had the problem 
### Reproducing code example:

```python
import numpy as np
list(np.arange(0.1,0.4,0.1).round(1))
```

### Numpy/Python version information:

1.18.1

**Comment by mattip** [comment]
As mentioned in [the documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html), you want to use `linspace` not `arange` for floating point numbers. Your example would be better written for `arange` as `list(np.arange(1, 4, 1) / 10.0)`

**Comment by bjnath** [comment]
@mattip It's great that [the `arange` doc](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) has this case listed prominently -- but I wonder if, before we move on, we can clarify "the results will often not be consistent." Consistent with respect to what? There must be some simple rewording that will make what happens clearer.

**Comment by eric-wieser** [comment]
I think we should add very explicitly to the examples section one of these cases.

**Comment by rossbar** [comment]
#16796 proposes adding some warnings/examples to the arange docstring but needs a bit more attention - it might be a good place to focus these efforts.

**Comment by melissawm** [comment]
This issue has been addressed on the `np.arange` documentation, so I'm closing. Thanks all!
