### ISSUE TITLE
Can not run Python script in powerbi desktop

### ISSUE THREAD

**Issue by thuantv-vp** [numpy/numpy#17187]
**I have create csv file named "dataset" and write a python script to import it to Powerbi desktop.
When I get data in powerbi desktop and paste above script, PBI show the error as following:**
_"Details: "ADO.NET: Python script error.
C:\Users\Admin\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies"_

### Reproducing code example:

**My python script is:**
"import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
df = pd.read_csv(r'C:\Users\Admin\Desktop\Python\Python_to_powerbi\Dataset.csv')
print(df)"

And I also attach my csv file.
https://github.com/thuantv-vp/Python-and-powerbi/blob/master/Dataset.csv
For more information
I use Anaconda with python version is 3.7.4
and Numpy version is 1.18.1
Matplotlib is also installed

Please help me to fix this integration error. Many [thanks]

```python
<< import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
df = pd.read_csv(r'C:\Users\Admin\Desktop\Python\Python_to_powerbi\Dataset.csv')
print(df)>>
```

**Comment by matthew-brett** [comment]
Are you sure this is a Numpy problem?  What do you get if you start Python again, and do just `import numpy`?

**Comment by matthew-brett** [comment]
Closing for now, please do reopen if you believe this is due to Numpy.
