### ISSUE TITLE
A bug for numpy.mod

### ISSUE THREAD

**Issue by GuoWenbo314** [numpy/numpy#17194]
### Reproducing code example:

```python
import numpy as np
print(np.mod(19**15, 3329))
```

### Error message:
The output of this code is 992.0  and it is a float point number. The true value of this code should be 699. Other modulus also get a wrong float point result.

### Numpy/Python version information:
Python version 3.8.2
Numpy version 1.19.1
Platform: Ubuntu20.04

**Comment by eric-wieser** [comment]
This gives the right answer:

>>> print(np.mod(19**15, np.uint64(3329)))
699

Numpy sees `19**15` as a `uint64`, and `3329` as a `int64`. A longstanding issue is that numpy picks `float64` when faced with having to unify these two types.

**Comment by GuoWenbo314** [comment]
> This gives the right answer:
> 
> ```
> >>> print(np.mod(19**15, np.uint64(3329)))
> 699
> ```
> 
> Numpy sees `19**15` as a `uint64`, and `3329` as a `int64`. A longstanding issue is that numpy picks `float64` when faced with having to unify these two types. There are many other open issues about this.

Very thank you. But why a bigger number, such as np.mod(19**20, 3329), don't have this question?

**Comment by eric-wieser** [comment]
Because numpy gives `19**20` type `object`.

**Comment by GuoWenbo314** [comment]
> Because numpy gives `19**20` type `object`. You can experiment with `np.array(19**20).dtype` to see what's goin
