### ISSUE TITLE
Help compiling sisl (f2py) in windows10/msys2/python3.8

### ISSUE THREAD

**Issue by kovalp** [numpy/numpy#17190]
Hi,

Recently, we were able to compile a library SISL in Windows 10 with Python 3.7 (3.7.7 and 3.7.8, numpy 1.19.1) using MSYS2 (MinGW32 compiler). Here is the corresponding issue in the SISL repo https://github.com/zerothi/sisl/issues/244

The compilation with Python 3.8 (3.8.4 or 3.8.5, numpy 1.19.1) is seemingly successful. However, the "import sisl" produces an ImportError error.

The python was installed from the official executable https://www.python.org/ftp/python/3.8.4/python-3.8.4rc1-amd64.exe

pip freeze here [pip3.8.out.txt](https://github.com/numpy/numpy/files/5147828/pip3.8.out.txt)

A setup output is here  [python-setup.out.txt](https://github.com/numpy/numpy/files/5147843/python-setup.out.txt)

### Reproducing code example:

`python -m sisl
`

We produced a minimal project https://github.com/kovalp/sisl_approach_f2py which suffers from a similar problem as SISL. Namely, when installing sisl_approach_f2py with python 3.7, python -c "import package1; package1.hello_world()" produces a "Hello world" message from the fortran module, while when installing with python 3.8, the import is failing with the ImportError `ImportError: DLL load failed while importing _sources: The specified module could not be found.`

### Error message:

```
ImportError: DLL load failed while importing _siesta: The specified module could not be found.
DLL load failed while importing _siesta: The specified module could not be found.
```

```
 $ python -m sisl
Traceback (most recent call last):
  File "C:\Users\koval\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\koval\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\koval\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\koval\AppData\Local\Programs\Python\Python38\lib\site-packages\sisl\__init__.py", line 128, in <module>
    from . import io
  File "C:\Users\koval\AppData\Local\Programs\Python\Python38\lib\site-packages\sisl\io\__init__.py", line 284, in <module>
    from .tbtrans import *
  File "C:\Users\koval\AppData\Local\Programs\Python\Python38\lib\site-packages\sisl\io\tbtrans\__init__.py", line 71, in <module>
    from .delta import *
  File "C:\Users\koval\AppData\Local\Programs\Python\Python38\lib\site-packages\sisl\io\tbtrans\delta.py", line 16, in <module>
    from ..siesta._siesta import siesta_sc_off
ImportError: DLL load failed while importing _siesta: The specified module could not be found.
DLL load failed while importing _siesta: The specified module could not be found.
```

### Numpy/Python version information:

```
$ python -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.19.1 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)]
```

**Comment by mattip** [comment]
Python 3.8 changed the way dlls are discovered. Until then, dlls were found on the PATH, so you could manipulate `os.environ['PATH']` to add a directory. Now you must use [`os.add_dll_directory`](https://docs.python.org/3/library/os.html#os.add_dll_directory). 

So perhaps your `siesta_sc_off` c-extension module requires other dlls . You can use [depends.exe](http://dependencywalker.com/) to discover what dlls `siesta_sc_off` depends on.

**Comment by kovalp** [comment]
Thank you! We will try something. @zerothi

**Comment by kovalp** [comment]
> Python 3.8 changed the way dlls are discovered. Until then, dlls were found on the PATH, so you could manipulate os.environ['PATH'] to add a directory. Now you must use os.add_dll_directory.
> So perhaps your siesta_sc_off c-extension module requires other dlls . You can use depends.exe to discover what dlls siesta_sc_off depends on.

The dependency walker discovers a lot of absent dlls.
![image](https://user-images.githubusercontent.com/8431900/93758924-93098000-fc09-11ea-8000-644457d505dc.png)

**Comment by mattip** [comment]
A few hints:

1. One way to use depends.exe with the exact environment that is used when you load the c-extension module is to put a line like this just before `import _siesta`:
```
import subprocess
subprocess.popen([r'c:\full-path\to\depends.exe', r'c:\full\path\to\_siesta.pyd`]). 
```

This way any runtime dependencies provided by python or other libraries already loaded into the process should be captured.

2. You can ignore things needed by `KERNEL*.DLL` and anything with an hourglass in front of it. If `KERNEL*.DLL` can't find its own dependencies, your system could not boot in the first place, so those will 99% of the time be things you can safely ignore.

**Comment by kovalp** [comment]
If I ignore all system DLLs, then everything seems fine. I do not see the problem when looking at the output of depends.exe.

**Comment by kovalp** [comment]
I think the dynamical linking with f2py is broken in windows10/gfortran-from-msys/python3.8. I am curious now whether there are positive precedents for using f2py in python3.8. Maybe only Intelfortran compiler works now?

**Comment by kovalp** [comment]
> Python 3.8 changed the way dlls are discovered. Until then, dlls were found on the PATH, so you could manipulate os.environ['PATH'] to add a directory. Now you must use os.add_dll_directory.
> So perhaps your siesta_sc_off c-extension module requires other dlls . You can use depends.exe to discover what dlls siesta_sc_off depends on.

In a minimal project using Cython and f2py https://github.com/kovalp/sisl_approach_f2py we have two Python modules: one is from Cython source, another from Fortran. Both modules compile into .pyd files (which contain the dll libraries, right?) *in the same directory*. Paradoxically, the module originating from the Cython source could be imported and the function from it produces the intended print statement, while the module originating from the Fortran source could not be loaded

```
python -c "import package1"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python38\lib\site-packages\package1-1.0-py3.8-win-amd64.egg\package1\__init__.py", line 7, in <module>
    from ._sources import hello_world
ImportError: DLL load failed while importing _sources: The specified module could not be found.
```

**Comment by floatingCatty** [comment]
> If I ignore all system DLLs, then everything seems fine. I do not see the problem when looking at the output of depends.exe.

Hello, I wondered how to ignore all system DLLs? I come across the same problem. Thanks.

**Comment by kovalp** [comment]
There is an option to achieve that I guess. Sorry, I cannot comment more
precisely.

**Comment by HaoZeke** [comment]
Closing as redundant since the build backend switch to `meson`.
