### ISSUE TITLE
DOC: Change rubrics to real headers

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#17203]
After the theme switch, there's now a separate sidebar for in-document headings.

The tutorial documents deliberately avoided this before, I think because the old theme made it look bad?
As a result, thatright sidebar is absent: https://numpy.org/devdocs/user/tutorial-ma.html

We should switch back to using real headings.

cc @melissawm, since I think you argued for `..rubric` originally.

**Comment by melissawm** [comment]
This had actually been a request from a reviewer in the SVD tutorial, but you're right that the new theme handles this better. I'll fix that, thanks for the heads up!
