### ISSUE TITLE
DOC: unify the fonts for headers and body

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#17200]
The recently merged pydata-sphinx-theme uses the Open Sans fonts for headers:
```
header-style,h1,h2,h3,h4,h5,h6{
    margin:2.75rem 0 1.05rem;
    font-family:Open Sans,sans-serif;
    font-weight:400;
    line-height:1.15;
}
```
and the basic body elements use Lato

```
body{
    background-color:#fff;
    font-family:Lato,sans-serif;
    font-weight:400;
    line-height:1.65;
    color:#333;
    padding-top:75px
}
```

We should unify this to one of the font families (perhaps in `doc/source/_templates/layout.html`)

**Comment by eric-wieser** [comment]
> We should unify this to one of the font families

Why? If the argument isn't numpy specific, wouldn't it make more sense to open this upstream?

**Comment by mattip** [comment]
This has been fixed. Closing.
