### ISSUE TITLE
Function to get broadcast shape from a list of shapes

### ISSUE THREAD

**Issue by asmeurer** [numpy/numpy#17217]
It would be helpful if NumPy had a function that took a bunch of shapes as input and returned the broadcasted shape of those shapes, or raised an error if they cannot be broadcast.

Right now, the only way to do this is to actually construct arrays with the given shapes and pass them to `np.broadcast` or `np.broadcast_arrays`. As far as I can tell, the actual logic to get a broadcast shape is buried inside of the PyArray_Broadcast C function

**Comment by eric-wieser** [comment]
I agree, this is definitely something we should expose somewhere

> Right now, the only way to do this is to actually construct arrays with the given shapes

A neat trick is to use `np.empty(shape, dtype=[])`, which allocates no memory so is safe even with large shapes.

**Comment by madhulikajc** [comment]
Hi, I would like to contribute to this. Based on @eric-wieser's comment above, I was thinking of doing something like:

```
def broadcast_shape(*args):
    arrays = list(map(lambda x: np.empty(x), args))
    return np.broadcast(*arrays).shape
```

Let me know if this approach seems good to you. I thought about exposing the logic in the `PyArray_Broadcast` C function to directly calculate the broadcast_shape, but it seems that some refactoring will be necessary to have that function operate on shapes in addition to arrays. I didn't think that np.empty would add much overhead. 

If you approve a direction, I will follow the numpy contribution guidelines and write new tests before opening a PR.

**Comment by rgommers** [comment]
Done in gh-17535, closing.
