### ISSUE TITLE
problems getting pypy3 to recognize numpy on Ubuntu under Windows 10 (WSL)

### ISSUE THREAD

**Issue by gokhalen** [numpy/numpy#17218]
I have problems getting pypy3 working with numpy on Ubuntu under Windows 10 (WSL).  The system python has no trouble recognizing and running numpy correctly. pypy3  is finding the correct numpy (the same one that system python finds) 

pypy3 version: (3.6.9 7.3.1+dfsg-4, Apr 22 2020, 05:15:29) [PyPy 7.3.1 with GCC 9.3.0] on linux).
system python version: (Python 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0] on linux) 

Both system python and pypy3 were installed using apt install 

### Reproducing code example:

```
import numpy as np
```

### Error message:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testpypy3.py", line 1, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/usr/bin/pypy3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

### Numpy/Python version information:

Using system python3.8: 1.17.4 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0]
Using pypy3: 
import sys; print(sys.version)
3.6.9 (7.3.1+dfsg-4, Apr 22 2020, 05:15:29)
[PyPy 7.3.1 with GCC 9.3.0]

Also, for system Python output of print(numpy.__file__) is  /usr/lib/python3/dist-packages/numpy/__init__.py  which is the same numpy that pypy3 is finding.

**Comment by eric-wieser** [comment]
You can't use the same numpy installation for both cpyhon and pypy. You'll need to install numpy inside pypy separately.

**Comment by gokhalen** [comment]
Thanks.  This is probably better asked on the pypy list but

pypy3 -mpip install numpy 

says,

Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.17.4)

**Comment by eric-wieser** [comment]
Pass `--upgrade`

**Comment by mattip** [comment]
I think there is a problem with your setup, as pointed out in the [pypy issue](https://foss.heptapod.net/pypy/pypy/-/issues/3293)
```
numpy in /usr/lib/python3/dist-packages
```
is going to cause problems for any user-installed python that looks there. That is probably the location for your package manager-provided files.

**Comment by gokhalen** [comment]
> Pass `--upgrade`

I tried  

pypy3 -mpip --upgrade install numpy 

it says

no such option: --upgrade

I also tried various variations on the previous command, but none of them seem to work.

**Comment by narcispr** [comment]
Same error with WSL2 on windows 11.
Using 3.7.12 (7.3.7+dfsg-1~ppa1~ubuntu20.04, Oct 26 2021, 02:00:43)\n[PyPy 7.3.7 with GCC 9.3.0]'

Any solution so far?

**Comment by mattip** [comment]
The command should be `pypy3 -m pip install --upgrade  numpy --user`
