### ISSUE TITLE
saving tuple of arrays -> broadcast error

### ISSUE THREAD

**Issue by scleronomic** [numpy/numpy#17213]
I noticed some strange behaviour when saving tuples of ndarrays.
When one of them is clearly a different shape it works correct. But if the arrays seem similar (ie. their first dimension is the same),  but they are not 'broadcastable' an error is thrown.
It seems strange, that is possible to pass a random set of array, but it does not work if the arrays are somehow similar and 
numpy tries to broadcast them to a single array. 

### Reproducing code example:
```python
import numpy as np
np.save('dummy1.npy', (np.zeros((10, 3)), np.zeros(5)))
a, b = np.load('dummy1.npy', allow_pickle=True)
# Works

np.save('dummy2.npy', (np.zeros((10, 3)), np.zeros(10)))
# ValueError: could not broadcast input array from shape (10,3) into shape (10)

# Workaround
np.save('dummy3.npy', (np.zeros((10, 3)), np.zeros(10), []))
a, b, _ = np.load('dummy3.npy', allow_pickle=True)

# np. save calls np.asanyarray() and this is basically just np.array() here the error is thrown
a = np.array((np.zeros((10, 3)), np.zeros(3)))  # Works
b = np.array((np.zeros((10, 3)), np.zeros(10)))  # Breaks
``` 
In the case of np.array it makes sense to throw an error because most of the time the user wants a broadcasted array,
but the behaviour when saving was a little unexpected for me.

### Error message:
Traceback (most recent call last):
  File "/Users/jote/opt/miniconda3/envs/mp_tf2/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-b9d6ff9dea9c>", line 1, in <module>
    np.save('dummy2.npy', (np.zeros((10, 3)), np.zeros(10)))
  File "<__array_function__ internals>", line 6, in save
  File "/Users/jote/opt/miniconda3/envs/mp_tf2/lib/python3.7/site-packages/numpy/lib/npyio.py", line 551, in save
    arr = np.asanyarray(arr)
  File "/Users/jote/opt/miniconda3/envs/mp_tf2/lib/python3.7/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: could not broadcast input array from shape (10,3) into shape (10)

### Numpy/Python version information:
python: 3.7.7 
numpy: 1.18.5

**Comment by eric-wieser** [comment]
`np.save` only supports saving arrays, not tuples. If you want to save tuples, use `pickle`.

Your error is the same one that you get with:

```python
>>> np.array([np.zeros((10, 3)), np.zeros(10)])
ValueError: could not broadcast input array from shape (10,3) into shape (10)
```

**Comment by eric-wieser** [comment]
Closing in favor of #17224, which I think captures the underlying issue better.
