### ISSUE TITLE
distutils MSVC: CCompiler_spawn() got an unexpected keyword argument 'env'

### ISSUE THREAD

**Issue by mbeyeler** [numpy/numpy#17216]
In the words of @jaraco, it looks like numpy is incompatible with pypa/distutils#6, which breaks the building of Cython-based extensions using MSVC. Triggered by switching from setuptools 49.6 to 50.0 (see also pypa/setuptools#2368)

### Error message:

```
self.run_command('build_ext')
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\numpy\distutils\command\build_ext.py", line 274, in run
    self.build_extensions()
  File "D:\a\1\s\setup.py", line 168, in build_extensions
    if self.can_compile_link(compile_flags, link_flags):
  File "D:\a\1\s\setup.py", line 142, in can_compile_link
    extra_postargs=compile_flags)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 403, in compile
    self.spawn(args)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 507, in spawn
    return super().spawn(cmd, env=env)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\numpy\distutils\ccompiler.py", line 92, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
```

### Numpy/Python version information:
numpy-1.18.5-cp35-cp35m-win_amd64.whl
setuptools 50.0

Thanks,
Michael

**Comment by rgommers** [comment]
Yes we're aware. For now set the `SETUPTOOLS_USE_DISTUTILS` environment variable to `"stdlib"`.


> In the words of @jaraco, it looks like numpy is incompatible with [pypa/distutils#6](https://github.com/pypa/distutils/pull/6), which breaks the building of Cython-based extensions using MSVC.

That's one of the issues yes, investigation ongoing in https://github.com/scipy/scipy/pull/12798.

It's not quite "NumPy is incompatible", it's more like _"`setuptools` make a massive breaking change in 50.0 without considering `numpy.disutils`, which (just like `setuptools`) monkeypatches `distutils` extensively"_. I'd like to get a better sense if we can work around things before opening a discussion on the setuptools repo. I expect not though; SciPy and other packages have to build with already released NumPy versions for example, so there's likely nothing better than setting `SETUPTOOLS_USE_DISTUTILS` for a long time.

**Comment by sverzakov** [comment]
Another option is to keep setuptools <=49.1.2.

The env keyword parameter of spawn() was added to both distools and setuptool simultaneously, but distools are the part of the Standard Lib (are the part of Python release) and setuptools are "pip installable". And distools of latest stable Python releases (3.7.9 and 3.8.5) do not have spawn() with env parameter.

So, it seems that setuptools > 49.1.2 are not compatible with distools of Python < 3.9.

**Comment by rgommers** [comment]
> Another option is to keep setuptools <=49.1.2.

Yes that's the safest thing to do for now, so I recommend doing that. 

It's not a long-term solution though (see https://github.com/numpy/numpy/pull/17209#issuecomment-685181604). I'm done for today, but will open a conversation on how to deal with the whole situation tomorrow.
