### ISSUE TITLE
Getting TypeError: No loop matching the specified signature and casting was found for ufunc true_divide despite using np.true_divide

### ISSUE THREAD

**Issue by sids07** [numpy/numpy#17221]
I was trying to compute ((A+B)*(-A/2)) in place (without copy):
I first tried simple np.divide(A,4,out=A) it gave me the above error.
I then tried np.true_divide(A,4,out=A) but still, I am getting the same error.

### Reproducing code example:

```python
import numpy as np
A = np.array([1,2,3,4])
B = np.array([3,4,5,6])

>> np.divide(A,4,out=A)


>> np.true_divide(A, 4, out=A)

>> A/4
array([0.25, 0.5 , 0.75, 1.  ])

```

### Numpy/Python version information:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-97-6a0b8bb59f6d> in <module>
----> 1 np.divide(A,4,out=A)

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-101-808ba4563783> in <module>
----> 1 np.true_divide(A, 4, out=A)

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

**Comment by eric-wieser** [comment]
For what it's worth, the two functions are just aliases
```python
>>> np.divide is np.true_divide
True
```

Your output array is an integer array, but `divide` computes a float. Casting a float to an integer is unsafe (loses information), so numpy does not allow it unless you explicitly ask: `np.divide(A,4,out=A, casting='unsafe')` will work.

Clearly we could improve this error message.

**Comment by sids07** [comment]
Thanks @eric-wieser for your help.

**Comment by eric-wieser** [comment]
#14843 may help with the message here

**Comment by sids07** [comment]
Wonderful @eric-wieser. This error message is not so clear and should be changed in my view as well 😊
