### ISSUE TITLE
numpy.power() returns RuntimeWarning when negative number is passed

### ISSUE THREAD

**Issue by eng-ak** [numpy/numpy#17226]
Hi,
while I am using NumPy power functions I discovered that it returns nan for solvable numbers as shown in the example below:  

```python
import numpy as np
np.power(-0.02040816, 0.75089074076058459)
RuntimeWarning: invalid value encountered in power
Out[3]: nan
```
however, using any calculator will output -0.0521552. I tried to remove the negative sign and run the operation for positive value and it gives me the correct answer which means there is an error in negative numbers.

I am using python 3.8.1 with NumPy 1.18.1

**Comment by eric-wieser** [comment]
>  using any calculator will output -0.0521552

Well, python gives
```
>>> (-0.02040816)**0.75089074076058459
(-0.03815436891112847+0.03794142609599409j)
```
so it looks like either your calculator is wrong or you're using it wrongly. Are you sure you're typing `(-x)^y` in your calculator and not `-(x^y)`?

**Comment by eric-wieser** [comment]
Numpy gives the same result if you tell it complex numbers are allowed:

```python
>> np.power(-0.02040816, 0.75089074076058459, dtype=complex)
(-0.038154368911128486+0.037941426095994095j)
```

**Comment by eng-ak** [comment]
>  Are you sure you're typing `(-x)^y` in your calculator and not `-(x^y)`?

I didn't put any parenthesis which I suppose my calculator did the power first then it assigns the negative sign. I am using the Casio fx-991ES calculator.
Your reply solves my question, Thank you very much
