### ISSUE TITLE
Using numpy.convolve() with int16 arrays results in errors in cross correlation result

### ISSUE THREAD

**Issue by cal-armstrong** [numpy/numpy#17234]
When running numpy.convolve() with arrays of type int16 (e.g. when arrays are read from a .wav file) the cross correlation output looks very noisy and is not accurate. This can be fixed by casting the arrays to type float64 but this is not documented anywhere I can see.

### Reproducing code example:

```python

import matplotlib.pyplot as plt
import numpy as np

a = np.concatenate((np.linspace(0, 100, 50), np.linspace(100, 0, 50))).astype(np.int16)
b = a.astype(np.float64)

corr = np.correlate(a, a, mode="full")
corr2 = np.correlate(b, b, mode="full")

plt.plot(corr)
plt.plot(corr2)
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/425260/92109618-40466080-ede1-11ea-9b2f-33e7e14fa068.png)

### Error message:

No error message.

### Numpy/Python version information:

1.18.1 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
`corr.dtype` is `np.int16`, your data is overflowing. What behavior would you expect here?

**Comment by cal-armstrong** [comment]
Ideally behaviour would recognise the non-valid data type and at least generate a warning. This current result is non-obvious and requires plotting the output array (and being knowledgeable of what the expected result should be) to really identify the results are incorrect.

The online documentation could also specify the required datatype.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by eric-wieser** [comment]
> Ideally behaviour would recognise the non-valid data type

Well, the data-type is valid - your array was just too large for it to be safe. `np.correlate(a[:5], a[:5], mode="full")` behaves perfectly sensibly. Detecting overflow is slow, but is probably something numpy generally needs to be able to do if asked - it's certainly a source of confusion for users.

> The online documentation could also specify the required datatype.

That's a good idea. Something like "the output type will match the input types" or something. @seberg, is `PyArray_ObjectType` anything like `result_type`, or is it a different set of rules again?

**Comment by cal-armstrong** [comment]
Ah OK this makes sense, I think it's purhaps a bigger issue as the output values of the cross correlation can be so significantly larger than the input values in a way that isn't imidiately obvious.

For example, the order of magnitude depends of the length of the array, not just a straight forward mathematical operation. So if I were to do 10^1000000 it would be (somewhat) obvious to expect overflow, but applying a cross correlation to an array:
10*np.ones(1000000)
It's not so obvious to expect it.

Purhaps even worth considering that logic in the documentation. And noting that users may experience overflow in the case of very long arrays.


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by seberg** [comment]
@eric-wieser `PyArray_ObjectType` is identical to `np.array(obj).dtype` or `np.promote_types(minimal_dtype, np.array(obj).dtype)`. So yes, but a bit different.

**Comment by seberg** [comment]
Closing in favor of gh-8987, while I guess `np.convolve` may be a bit special, since its not a ufunc, its probably second in line after a fix for ufuncs...
