### ISSUE TITLE
TEST: pytest has deprecated the logging mechanism we use

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#17230]
Some tests are emitting this warning:
```
/python3.7/site-packages/_pytest/compat.py:340: PytestDeprecationWarning: The \
TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead \
at your own risk.

See https://docs.pytest.org/en/stable/deprecations.html#terminalreporter-writer for \
more information.

```
The link https://docs.pytest.org/en/stable/deprecations.html#terminalreporter-writer doesn't really help figure out where this is being used, and grepping around didn't get me any hits. Who is our resident pytest expert?

**Comment by WarrenWeckesser** [comment]
Is this still occurring?  Was it Python 3.7 only?  I don't see those warnings when running the full test suite with Python 3.9.1 and pytest 6.2.4.

**Comment by mattip** [comment]
The attribute was removed in pytest 6.0. Closing.
