### ISSUE TITLE
implement the rest of the dictionary interface for NpzFile (Trac #1125)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1723]
_Original ticket http://projects.scipy.org/numpy/ticket/1125 on 2009-06-03 by @dwf, assigned to unknown._

The patch attached implements a more complete dictionary interface for NpzFile. That is to say, it provides (in addition to the already present **getitem**()):
- `__contains__` - tests for containment of a key in self.files
- `__iter__` - returns an iterator over self.files
- keys() - returns a copy of self.files
- values() - returns a list of all arrays in the NpzFile
- iterkeys() - returns an iterator [really a generator] over all items in self.files
- itervalues() - returns an iterator over all arrays in the NpzFile
- items() - returns a list of (key, value) pair tuples
- iteritems()  - returns an iterator over (key, value) pair tuples

This allows the convenient "for fname in mynpzfile"  syntax, as well as letting you write code that doesn't care whether its input is an in-memory dictionary or a lazily-loaded NpzFile.

**Comment by Nodd** [comment]
`NpzFile` has everything except `values()` and `itervalues()` in numpy 1.14.0.
