### ISSUE TITLE
DeprecatedWarning: apply_along_axis and dtype=object

### ISSUE THREAD

**Issue by f380cedric** [numpy/numpy#17249]
Since #15119, `np.apply_along_axis` throws a DeprecatedWarning when func1d returns object dtype.
I am using it with [`scipy.signal.find_peaks`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html) since it easily allows to keep shape, Numpy's indexing style, etc.
I am expecting that it will become an error at some point in the future.

Would it be possible to add a `dtype` kwarg?

### Reproducing code example:

```python
import numpy as np
def foo(dummy):
    return 1,"1",[1],(1,)

arr = np.apply_along_axis(foo, -1, np.random.randn(5,2,200))
```

### Error message:

```python
/usr/lib/python3/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
```

### Numpy/Python version information:

```
1.19.1 3.8.5 (default, Aug  2 2020, 15:09:07)
[GCC 10.2.0]
```

**Comment by eric-wieser** [comment]
I think this problem goes away if you use either:
```
def foo(dummy):
    return np.array([1,"1",[1],(1,)], dtype=object)
```
Or construct a suitable structured data type instead

**Comment by f380cedric** [comment]
> 
> 
> I think this problem goes away if you use either:
> 
> ```
> def foo(dummy):
>     return np.array([1,"1",[1],(1,)], dtype=object)
> ```
> 
> Or construct a suitable structured data type instead

It was a MWE. As said earlier, my used case was with [`scipy.signal.find_peaks`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html).
Most of the time, I use it with external libraries. And I cannot expect that external libraries, even Scipy, will rewrite their returns so that they comply with the new deprecation.

I could define a wrapper function, or use the short example in the [`np.apply_along_axis` doc](https://numpy.org/doc/stable/reference/generated/numpy.apply_along_axis.html).
But it worked before, and I do not think that the idea behind that deprecation was to injure `np.apply_along_axis`.

**Comment by seberg** [comment]
@f380cedric can you give an example of what you pass into `find_peaks` to run into this issue? Is it that the input to find peaks is an object array?

**Comment by f380cedric** [comment]
> 
> 
> @f380cedric can you give an example of what you pass into `find_peaks` to run into this issue? Is it that the input to find peaks is an object array?
``` python
import numpy as np
from scipy import signal
arr = np.apply_along_axis(signal.find_peaks, -1, np.random.randn(5,2,200), distance=30)
```
The issue is that `find_peaks` returns something that can only be stored in an object array, since it returns (`ndarray`, `dict`).
Even if it was only returning a `ndarray` (no dict), it will still throws the deprecation since returned `ndarray`s can have different sizes (you do not find the same number of peaks across 1D slices).

**Comment by seberg** [comment]
Oh ok, I guess I could have guessed that.  In any case, I am not sure I see a reason for not asking you to wrap `signal.find_peaks`.
It is an arbitrary function to NumPy, and if it returns oddly formated data, than it seems good to ask you to clarify the siutation (i.e. convert to an array manually), maybe you expect a float64 output, but a corner case lead to a different result.

**Comment by f380cedric** [comment]
I have not encountered breakages with other NumPy's functions.
It seems appropriate to me to wrap external library's functions.
I'll close. Thanks
