### ISSUE TITLE
[1.19.1] sum() bug

### ISSUE THREAD

**Issue by iperov** [numpy/numpy#17246]
sum() bug

### Reproducing code example:

```python
while True:
    np_val = np.random.randint( 2**5, size=(16*512*512,) ).astype(np.float32)
    np_val_len = len(np_val)
    
    # whole sum
    sum_1 = np_val.sum() 
    
    # sum after half summation
    sum_2 = (np_val[0:np_val_len//2] + np_val[np_val_len//2:]).sum() 
    
    if sum_1 != sum_2:
        print(f'fail, {sum_1} {sum_2}')
    else:
        print('ok')
```

### Result:

![cmd_2020-09-04_12-35-05](https://user-images.githubusercontent.com/8076202/92219728-01311180-eeac-11ea-9231-ac8254032b62.jpg)

### Numpy/Python version information:

1.19.1 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
Floating point addition is not associative, in general `(a + b) + c != a + (b + c)`

**Comment by iperov** [comment]
> Floating point addition is not associative, in general (a + b) + c != a + (b + c)

I agree if input values have digits after dot. 
But there are integer numbers and result is also integer.

**Comment by eric-wieser** [comment]
It applies for integers too. Float32 cannot represent odd integers above 2^24

**Comment by iperov** [comment]
ok
