### ISSUE TITLE
Weird behaviour of Numpy with unsized arrays

### ISSUE THREAD

**Issue by Joueswant** [numpy/numpy#17251]
Hi there, 
First of all congratulations for Numpy, in the end, it is an amazing and very polished tool. Yet, I would like to comment an unexpected behaviour (for me), instrinsic in the nature of the types `numpy.ndarray` and `numpy.ma.MaskedArray`.

In Python there is a very cool way to difference an int, float, etc. from any sequence by using `hasattr`, for instance:
```python
hasattr(1989, "__len__")
False
hasattr([1989], "__len__")
True
```
Now, assume the following arrays:
```python
arr1 = np.array(1989)
arr2 = np.array([1989])

hasattr(arr1 , "__len__")
True #That should be False
hasattr(arr2 , "__len__")
True
```
The point is that given the nature of `np.array`, it always have `size` and `shape` and therefore, an attribute `len`. But `arr1` is an unsized object after all. Is this an expected behaviour? Is there a way to fix this?

My numpy version is: '1.19.1'

**Comment by eric-wieser** [comment]
Note that what python actually cares about is `type(...).__len__`. So the only way to fix this would be to make `array(1)` and `array([1])` have different types.

**Comment by eric-wieser** [comment]
You can use instead
```
try:
    len(x)
except TypeError:
    # not a list

**Comment by Joueswant** [comment]
Thanks for the answers Eric, I can fix it in my script without problems. I was just wondering if this was an issue to work on or you are already aware of that.

**Comment by seberg** [comment]
Going to close this, pretty sure we have other issues about 0-d arrays "pretending" to be sequences.

And there isn't really anything easy that can be done, anyway.  Not without using different types, and we can't do that.  (I suppose some metaclass magic might be able to do something, but that seems way too heavy weight.)
