### ISSUE TITLE
np.std incosistent behavior when all values are equal

### ISSUE THREAD

**Issue by mglowacki100** [numpy/numpy#17261]
From statistics point of view standard deviation when all values are equal should be `0`. For `arr1` result is as expected: `0`, but for `arr2` is `1.3877787807814457e-17` - very small but not 0, which leads to issues with e.g. `zscore`.
As discussed here: https://stackoverflow.com/questions/63772729/numpy-std-standard-deviation-function-weird-behavior issue is caused by floating errors. 
I think the problem could be solved by checking for "equality" before calculating `std = sqrt(mean(abs(x - x.mean())**2))`; when all values are equal `std` should return `0.0`
Why this is important? For example `zscore` from `scipy.stats` is calculated as "(x-np.mean)/np.std ". Division by `0` return `np.nan` but division even by small number gives "proper number", but it also should be `nan`. 
### Reproducing code example:

```python
import numpy as np
arr1 = [20.0] * 3
#[20.0, 20.0, 20.0]

arr2 = [-0.087] * 3
#[-0.087, -0.087, -0.087]

np.std(arr1) #0.0
np.std(arr2) #1.3877787807814457e-17
```

### Numpy/Python version information:
1.19.1 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]

**Comment by eric-wieser** [comment]
I assume what's happening here is `np.mean(arr2) != -0.087`, for the usual summation reasons.

**Comment by mglowacki100** [comment]
@eric-wieser yes, np.mean(arr2) = -0.0870000000000000**1**
but for array like `[-0.087, -0.087, -0.087]` there is no need to calculate it.

**Comment by eric-wieser** [comment]
Just to check, what does `np.array(arr2)[0]` display as?

**Comment by mglowacki100** [comment]
`np.array(arr2)[0]` is displayed as `-0.087`
