### ISSUE TITLE
DOC: request for tutorial saving and loading NumPy arrays

### ISSUE THREAD

**Issue by cooperrc** [numpy/numpy#17266]
### Feature Request

As part of my [Google Summer of Docs](https://hackmd.io/@cooperrc/BJTwgETjU) working with @melissawm and @rgommers,  I would like to create a tutorial on saving and loading NumPy arrays by demonstrating LU-decomposition with a Hilbert matrix. I've done some initial testing and found that even for LU-decomposition of 100x100 Hilbert arrays, if you use `savez` and `savetxt` with default formatting there is no difference between `load` and `loadtxt`. I had expected roundoff error in `savetxt`, but the default options work really well. 

Here is my proposed tutorial title and outline:

title: __Saving, loading, and sharing your NumPy arrays__
subtitle: _with LU-decomposition of the Hilbert matrix_

1. Background and required tools
  a. Hilbert matrix is made with `H[i, j] = 1/(i+j+1)` _0-based index_
  b. Use Python loops to create arrays `np.array`
  c. Use `scipy.linalg.lu` to get `p, l, u` LU-decomposition
  d. Save arrays using `savez` and `savetxt`

2. Creating your Hilbert matrix and LU-decomposition:
  a. Demonstrate the Python way: `H = np.array([[1/(i+j+1) for j in range(N)] for i in range(N)])`
  b. Get the LU decomposition with `p, l, u = scipy.linalg.lu(H)`
  c. bigger array = smaller floating point numbers
  d. the work is done, now we need to save it for (1) loading into another Python session (2) sharing with other people

3. Saving the work
  a. Use `np.savez` to save all 4 arrays into an output file
  b. Use `np.savetxt`in 2 steps:
    i. reshape arrays into vectors
    ii. save vectors to file with descriptive header

4. Loading the work
  a. Show how `np.load` creates dictionary, here as `H`, `p`, `l`, and 'u'
  b. Show a 2x2 example `cat` for the `savetxt`
  c. Use `loadtxt` to load the arrays saved to text
  d. Use `np.reshape` to get arrays back into NxN shape

5. Wrapping up
  a. Compare `*.npz` file to text output (`savez` vs `savetxt`)
  b. Discuss roundoff errors if `savetxt`'s  `fmt` is used 
  c. Discuss benefits/drawbacks of `np.savez` and `np.savetxt` e.g. speed and accuracy vs formatting and readability

### Numpy/Python version information: 

NumPy v1.19.1 
Sys version v3.8.3 GCC 7.3.0

**Comment by bjnath** [comment]
Elsewhere I asked @cooperrc 
> What's the motivation for including the Hilbert matrix and LU decomposition in a lesson on saving and loading?

He responded:

> There are a lot of examples floating around with random numbers out there. One thing that would be nice here is that the matrix doesn't change due to different seeds and sizes of the matrix, but you do get a little discussion of roundoff error due to the ill-conditioning at larger sizes.
It also makes for a little extra insight into building NumPy arrays. You can create nested for-loops inside lists.

**Comment by cooperrc** [comment]
> Elsewhere I asked @cooperrc
> 
> > What's the motivation for including the Hilbert matrix and LU decomposition in a lesson on saving and loading?
> 
> He responded:
> 
> > There are a lot of examples floating around with random numbers out there. One thing that would be nice here is that the matrix doesn't change due to different seeds and sizes of the matrix, but you do get a little discussion of roundoff error due to the ill-conditioning at larger sizes.
> > It also makes for a little extra insight into building NumPy arrays. You can create nested for-loops inside lists.

Thanks @bjnath, to me its nice to have a matrix or example that takes a little work, but isn't going to change next time you use it. Putting a little work into the array (here creating a function with some for-loops) demonstrates a necessity to save your work. As an example of creating `H` and the roundoff discussion, 

for 2x2 `H`:

```python
>>> H = np.array([[1/(i+j+1) for j in range(2)] for i in range(2)])
>>> H
array([[1.        , 0.5       ], 
       [0.5       , 0.33333333]])
```

Then, for a 4x4 matrix you have `H`:
```python
>>> H = np.array([[1/(i+j+1) for j in range(4)] for i in range(4)])
>>> H
array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])
```

The bigger `H` gets, the smaller `H[-1,-1]` gets. Here its 1/3 (2x2) vs 1/7 (4x4)

**Comment by bjnath** [comment]
@cooperrc The Unix idea of "do one thing well" might be applied to tutorials. If we plan a seven-course dinner,  we'll frustrate the users who have to read through linear algebra discussion when they want to try out I/O and frustrate the users who wanted to hear more about the matrices. 

That's probably why we see so many I/O examples using random numbers -- they get array creation out of the way so they can focus on I/O.

So one recommendation is to write tutorials that solve just one problem and that prune away everything unrelated.

That would suggest splitting the tutorial in two, but I'm not sure the right components are here. It's instructive to see how the matrix is created idiomatically, but that might not be enough content for a tutorial.  Similarly, I'm not sure how much drama the Hilbert matrix adds to an I/O demonstration; the corner does get small, but not all that quickly. Am I missing the point?

**Comment by cooperrc** [comment]
> @cooperrc The Unix idea of "do one thing well" might be applied to tutorials. If we plan a seven-course dinner, we'll frustrate the users who have to read through linear algebra discussion when they want to try out I/O and frustrate the users who wanted to hear more about the matrices.

That's true, this does try to jam a couple ideas into one tutorial. 

> That's probably why we see so many I/O examples using random numbers -- they get array creation out of the way so they can focus on I/O.

When I see random number generation and then saving, I always feel like there could be a different few steps to build a matrix. Generating random numbers is its own entire field of work and the user has to go through a few steps to call the functions anyway. A problem here might be that Hilbert matrices are too niche. 

Maybe there would be a broader interest something like a linear regression that starts with loading and ends with saving. It would just require a csv or other set of data. 

> So one recommendation is to write tutorials that solve just one problem and that prune away everything unrelated.

That would make sense to me. 
 
> That would suggest splitting the tutorial in two, but I'm not sure the right components are here. It's instructive to see how the matrix is created idiomatically, but that might not be enough content for a tutorial. 

I agree, building this matrix is a little too quick to warrant an entire discussion. 

> Similarly, I'm not sure how much drama the Hilbert matrix adds to an I/O demonstration; the corner does get small, but not all that quickly. Am I missing the point?

I use Hilbert matrices in class for examples of ill-conditioned matrices. The matrix itself has elements that are small, but when you perform LU-decomposition or try to solve Hx = b, you run into numerical issues (depending upon size).

**Comment by cooperrc** [comment]
After discussing options with the NumPy documentation committee, it might be better to build a tutorial around a typical user workflow:

1. Load a csv into a NumPy array
2. Do some math, e.g. linear regression
3. Save the results in two formats and compare:
  a. *.npz
  b. Back to csv

One thought on a csv dataset to read into the workspace would be a [cleaned-up transistor count per integrated circuit](https://en.m.wikipedia.org/wiki/Transistor_count). Then, the regression leads to an experimental measure of Moore's law. 

`log(transistors) = slope * year + intercept`

Final results are intercept, slope, and predicted transistor counts.

**Comment by bjnath** [comment]
+1 on choice of Moore's law -- has wide interest, and it's a nice twist to fit a model that isn't linear.

But I'm unclear what's getting stored. Are we planning a plot with both the original data and a straight line?

**Comment by melissawm** [comment]
@cooperrc just for clarification: do you think the tutorial as it is planned right now would close the issue of having a tutorial on saving/loading NumPy arrays? My feeling is that is has morphed into something a little different. If that is the case, we should maybe discuss if an IO focused tutorial is necessary and what it should cover.

**Comment by cooperrc** [comment]
> @cooperrc just for clarification: do you think the tutorial as it is planned right now would close the issue of having a tutorial on saving/loading NumPy arrays? My feeling is that is has morphed into something a little different. If that is the case, we should maybe discuss if an IO focused tutorial is necessary and what it should cover.

@melissawm, the tutorial I wrote does not specifically address this issue. I can write a tutorial that is shorter and addresses this issue directly. Would that be better?

**Comment by mattip** [comment]
I think a short tutorial that expands on the points of the [IO howto](https://numpy.org/devdocs/user/how-to-io.html) along the lines of the original title **Saving, loading, and sharing your NumPy arrays** would be good. This would use a boring routine to create some non-interesting multi-dimensional data. Then a subsequent tutorial could go into more detail about doing the same thing but with more interesting data.

**Comment by bjnath** [comment]
In the [Basics](https://numpy.org/devdocs/user/basics.html) section we have an article [Importing data with genfromtxt](https://numpy.org/devdocs/user/basics.io.genfromtxt.html).

It doesn't cover all the bases of saving, loading, and sharing, but it might be adapted into a useful I/O tutorial.

**Comment by cooperrc** [comment]
> > I think a short tutorial that expands on the points of the [IO howto](https://numpy.org/devdocs/user/how-to-io.html) along the lines of the original title **Saving, loading, and sharing your NumPy arrays** would be good. This would use a boring routine to create some non-interesting multi-dimensional data. Then a subsequent tutorial could go into more detail about doing the same thing but with more interesting data.
> 
> I like this idea (and @bjnath 's suggestion can certainly be incorporated). @cooperrc would you be willing to work on it now or after your Moore's Law tutorial is finished? 

I can get started on the IO tutorial while others get a chance to look at the Moore's law tutorial. @bjnath had a great idea to update the existing document.

**Comment by cooperrc** [comment]
To work towards closing this issue, I created a short tutorial in numpy-tutorials to save and load NumPy arrays. [PR #34](https://github.com/numpy/numpy-tutorials/pull/34). 

This tutorial creates two arrays `x = np.arange(0,10)` and `y = x**2`, then saves them using `savez` and `savetxt`.
