### ISSUE TITLE
Modulo operation causes `np.random.multivariate_normal` to fail with svd convergence error

### ISSUE THREAD

**Issue by fvollmer** [numpy/numpy#17270]
The following code fails with an error (`numpy.linalg.LinAlgError: SVD did not converge`). This occurs if:
 * there is this unused import (`import scipy.linalg`)
 * a modulo operation is performed (`x1 % 2`)

This is unexpcected to me, because the modulo operation shouldn't have any side effects, but even copying the vector won't help.

Another interesting observation is that only the first excecution of `np.random.multivariate_normal` fails. As a workaround I could just catch the first exception and run it again:

```python
try:
    sample = np.random.multivariate_normal(np.zeros(len(points)), cov)
except np.linalg.LinAlgError as e:
    print("First try failed:", e)
sample = np.random.multivariate_normal(np.zeros(len(points)), cov)
```

I was able to reproduce this error another windows pc with anaconda python, but not on linux.

### Reproducing code example:

```python
import numpy as np
# this unused import is important to reproduce the weird side effect of modulo calculation
import scipy.linalg


def k(x1, x2):
    base = np.pi * (x1[:, None, :] - x2[None, :, :])
    exp_dist = np.exp(-0.5 * np.sum(np.square(np.sin(base)), axis=-1))

    # the following statement shouldn't have any side effects
    x1 % 2
    #np.mod(x1, 2)
    #np.mod(x1.copy(), 2)

    return exp_dist


n = 10
points = np.atleast_2d(np.linspace(0, 360, 10)).T
cov = k(points, points)
np.random.multivariate_normal(np.zeros(len(points)), cov)
```

### Error message:

```
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\fg-localization\other\weird_behavior.py", line 21, in <module>
    np.random.multivariate_normal(np.zeros(len(points)), cov)
  File "mtrand.pyx", line 4084, in numpy.random.mtrand.RandomState.multivariate_normal
  File "C:\Users\user\Anaconda3\envs\fg-localization\lib\site-packages\scipy\linalg\decomp_svd.py", line 132, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```

### Numpy/Python version information:

Fails on windows with:
```
1.19.1 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
```

Runs on linux with:
```
1.19.1 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0]
```

**Comment by charris** [comment]
What Windows version? SVD is known to be troublesome on Windows 2004 (latest update), see #16744.

**Comment by fvollmer** [comment]
Windows 10

**Comment by charris** [comment]
@fvollmer Yep, that sounds like #16744.

**Comment by fvollmer** [comment]
@charris thanks for the hint!

I had somone try the example on an older windows 10 (Build 1903)
![grafik](https://user-images.githubusercontent.com/16699443/92489819-7d9b5b80-f1f0-11ea-987e-7551590b976c.png)
and there was no problem. Seems like it could be related to #16744.

**Comment by fvollmer** [comment]
I'll close this issue, because it looks like a duplicate of #16744
