### ISSUE TITLE
error while trying to use tensorboard

### ISSUE THREAD

**Issue by majidkamyabalberta** [numpy/numpy#17274]
I have received the below error while trying to use "tensorboard --logdir runs"
I have multiple python and tried to install tensorflow by using pip3 install tensorflow and also pip install tensorflow.  my operating system is ubuntu and I installed numpy in the same way.
I have tried the steps in the error and it didnt work out. thanks in advance for your help
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 40, in <module>
>     from . import multiarray
>   File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 12, in <module>
>     from . import overrides
>   File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 6, in <module>
>     from numpy.core._multiarray_umath import (
> ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/majid/.local/bin/tensorboard", line 5, in <module>
>     from tensorboard.main import run_main
>   File "/home/majid/.local/lib/python3.8/site-packages/tensorboard/main.py", line 28, in <module>
>     import tensorflow as tf
>   File "/home/majid/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "/home/majid/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
>     from tensorflow.python.eager import context
>   File "/home/majid/.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
>     import numpy as np
>   File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
>     from . import core
>   File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 71, in <module>
>     raise ImportError(msg)
> ImportError: 
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> Here is how to proceed:
> - If you're working with a numpy git repository, try `git clean -xdf`
>   (removes all files not under version control) and rebuild numpy.
> - If you are simply trying to use the numpy version that you have installed:
>   your installation is broken - please reinstall numpy.
> - If you have already reinstalled and that did not fix the problem, then:
>   1. Check that you are using the Python you expect (you're using /usr/bin/python3.8),
>      and that you have no directories in your PATH or PYTHONPATH that can
>      interfere with the Python and numpy versions you're trying to use.
>   2. If (1) looks fine, you can open a new issue at
>      https://github.com/numpy/numpy/issues.  Please include details on:
>      - how you installed Python
>      - how you installed numpy
>      - your operating system
>      - whether or not you have multiple versions of Python installed
>      - if you built from source, your compiler versions and ideally a build log
> 
>      Note: this error has many possible causes, so please don't comment on
>      an existing issue about this - open a new one instead.
> 
> Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by mattip** [comment]
You are using the distribution provided numpy, not one specific to your python. So you are picking up the one you installed via `sudo apt install python3-numpy` which is the one for some other version of numpy. Since you are using python3.8, you need to do one of (in order of my personal preference)
- use conda/miniconda to provide optimal isolation between your pythons, not only pip packages but many system utilities as well such as mkl and more
- create a virtual environment, activate it, and install all the packages inside it
- use the system python3, not python3.8

In any case, I always try to use `python -mpip install`, and add `--user` if I am outside a virtualenv/conda env to avoid this problem. However ubuntu/debian puposefully makes this difficult to force you into one of the other solutions.

**Comment by majidkamyabalberta** [comment]
my problem is fixed by your help, thanks however could you please be more
specific about the first option? do I just have to install conda or do I
have to also run some sort of commands in the terminal.

**Comment by mattip** [comment]
https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html

Glad to hear your problem is solved. Please close unless there is a specific NumPy problem

**Comment by majidkamyabalberta** [comment]
Thanks mattip
