### ISSUE TITLE
Python 3.8.5 numpy.linalg.svd not correct matrix U calculation

### ISSUE THREAD

**Issue by koslayn** [numpy/numpy#17287]
When i use `numpy.linalg.svd` I get not correct calculation U matrix in python 3.8.5, in python 3.8.4 everything is fine:

### Reproducing code example:
```python
from platform import python_version
print(f'python: {python_version()}')

import numpy as np
print(f'numpy: {np.__version__}')
from numpy.linalg import svd, det

A = np.array([[3,2,2],[2,3,-2]])
u, s, vh = np.linalg.svd(A, full_matrices=True, compute_uv=True, hermitian=False)

print(f'Matrix U: \n{u}')
```

### output python 3.8.5
```
python: 3.8.5
numpy: 1.19.1
Matrix U:
[[ 0.70710678 -0.70710678]
[ 0.70710678 0.70710678]]
```

### output python 3.8.4
```
python: 3.8.4
numpy: 1.19.1
Matrix U:
[[-0.70710678 -0.70710678]
[-0.70710678 0.70710678]]
```

#### Windows miniconda
```1.19.1 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 00:43:28) [MSC v.1916 64 bit (AMD64)]```

#### Jupyter Docker Stacks
```1.19.1 3.8.4 | packaged by conda-forge | (default, Jul 17 2020, 15:16:46) [GCC 7.5.0]```

**Comment by melissawm** [comment]
Hi @koslayn , I can't seem to reproduce that. I get the same matrix for `u` in both Python 3.8.4 and 3.8.5 (both on Linux). However, [the SVD decomposition is not unique]((https://en.wikipedia.org/wiki/Singular_value_decomposition)) and I'm thinking maybe your different installations refer to different versions of BLAS, and that can change how the results from the underlying SVD routine are chosen. Can you check if the product of the factors `u`, `s` and `vh` you found in each case, with appropriate dimensions for `s`, result in your matrix `A`?

**Comment by koslayn** [comment]
Hi @melissawm, thanks for your explanation.   
The product of the factors return the same matrix `A`.

### Reproducing code example:
```python
from platform import python_version
print(f'Python: {python_version()}')

import numpy as np
print(f'Numpy: {np.__version__}')
from numpy.linalg import svd, det

A = np.array([[3,2,2],[2,3,-2]])

u, s, vh = np.linalg.svd(A, full_matrices=True, compute_uv=True, hermitian=False)

print(f'Matrix U: \n{u}')
print(f'Matrix S: \n{s}')
print(f'Matrix VH: \n{vh}')
print(f'======================')

true_s = np.zeros((u.shape[1], vh.shape[0]))
true_s[:s.size, :s.size] = np.diag(s)

print(f'Reconstruction A \n{u.dot(true_s).dot(vh)}')
```
### **Out** Python 3.8.5 Windows 
```
Python: 3.8.5
Numpy: 1.19.1
Matrix U: 
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Matrix S: 
[5. 3.]
Matrix VH: 
[[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]
======================
Reconstruction A 
[[ 3.  2.  2.]
 [ 2.  3. -2.]]
```
### **Out** Python 3.8.4 Docker 
```
Python: 3.8.4
Numpy: 1.19.1
Matrix U: 
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Matrix S: 
[5. 3.]
Matrix VH: 
[[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]
======================
Reconstruction A 
[[ 3.  2.  2.]
 [ 2.  3. -2.]]
```
