### ISSUE TITLE
numpy.unique( foo , return_counts=True) doesn't work

### ISSUE THREAD

**Issue by KellenX** [numpy/numpy#17282]
### Reproducing code example:

```python
import numpy as np
values, counts = np.unique(my_numpy_series, return_counts=True)
dict(zip(values, counts))
```

### Error message:

TypeError                                 Traceback (most recent call last)
<ipython-input-37-0ab9843ab55c> in <module>()
----> 1 values, counts = np.unique(Spiceman_Age.histology_abbreviation, return_counts=True)
      2 dict(zip(values, counts))

<__array_function__ internals> in unique(*args, **kwargs)

/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts, axis)
    261     ar = np.asanyarray(ar)
    262     if axis is None:
--> 263         ret = _unique1d(ar, return_index, return_inverse, return_counts)
    264         return _unpack_tuple(ret)
    265 

/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py in _unique1d(ar, return_index, return_inverse, return_counts)
    309         aux = ar[perm]
    310     else:
--> 311         ar.sort()
    312         aux = ar
    313     mask = np.empty(aux.shape, dtype=np.bool_)

TypeError: '<' not supported between instances of 'float' and 'str'

### Numpy/Python version information:

1.19.1 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:19:23) 
[GCC Clang 10.0.1 ]

**Comment by rossbar** [comment]
Note this line in the provided traceback: `TypeError: '<' not supported between instances of 'float' and 'str'`

Perhaps there is a problem with the input data? Can you provide a minimal example of `my_numpy_series` that results this error? For example, the following works for object arrays with mixed data:

```python
>>> a = np.array([1, 1, 3, 'a', 'b'])
>>> np.unique(a, return_counts=True)
(array(['1', '3', 'a', 'b'], dtype='<U21'), array([2, 1, 1, 1]))
```

**Comment by KellenX** [comment]
> Note this line in the provided traceback: `TypeError: '<' not supported between instances of 'float' and 'str'`
> 
> Perhaps there is a problem with the input data? Can you provide a minimal example of `my_numpy_series` that results this error? For example, the following works for object arrays with mixed data:
> 
> ```python
> >>> a = np.array([1, 1, 3, 'a', 'b'])
> >>> np.unique(a, return_counts=True)
> (array(['1', '3', 'a', 'b'], dtype='<U21'), array([2, 1, 1, 1]))
> ```

I found that the probleme is caused by a  'nan' in my_pandas_series. It's solved after I did my_pandas_series.dropna(). Thank you for checking this for me.
