### ISSUE TITLE
Why does int64's is not inherited from "int", but "float64" is inherited from "float"?

### ISSUE THREAD

**Issue by svetlyak40wt** [numpy/numpy#17283]
### Reproducing code example:

```python
import numpy

numpy.float64.mro() -> [numpy.float64,
                        numpy.floating,
                        numpy.inexact,
                        numpy.number,
                        numpy.generic,
                        # Here the standard float type:
                        float,
                        object]

numpy.int64.mro() -> [numpy.int64,
                      numpy.signedinteger,
                      numpy.integer,
                      numpy.number,
                      numpy.generic,
                      object]


isinstance(numpy.float64(1.2345), float) -> True

isinstance(numpy.int64(1), int) -> False
```

### Numpy/Python version information:

```
import sys, numpy; print(numpy.__version__, sys.version)
1.19.1 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
```

**Comment by svetlyak40wt** [comment]
Probably this is the related issue:

https://h.yandex-team.ru/?https%3A%2F%2Fgithub.com%2Fnumpy%2Fnumpy%2Fissues%2F17105

**Comment by bashtage** [comment]
One reason might be that C Int is platform dependent. This mattered on Python 2.x. As fas as I know, c double aka float64  is not.

Another reason is that python int on 3.x supports arbitrary size values.

**Comment by eric-wieser** [comment]
> Another reason is that python int on 3.x supports arbitrary size values.

This is the reason. On python 2, `np.int_` did subclass `int`.

**Comment by charris** [comment]
That float64 subclasses Python float is unfortunate :) In the Python2 integer case subclassing led to printing oddities that differed across platforms, good riddance to that.

**Comment by svetlyak40wt** [comment]
So, the real issue is that `np.float64` subclasses` float`? Am I right?

**Comment by rkern** [comment]
It's not an issue that necessarily needs to be fixed. It's just a choice that was made to try to make the most common scalar objects compatible with code that's expecting plain-old builtin Python types. It has some consequences that are annoying, but removing it at this late stage would also have consequences.

**Comment by eric-wieser** [comment]
`np.float_` (aka `np.float64`) isn't the only outlier here either - `np.complex_` subclasses `complex`, `np.str_` subclasses `str`, and `np.bytes_` subclasses `bytes`.

**Comment by svetlyak40wt** [comment]
I didn't mean the "issue" should be fixed. Just want to clarify the situation and to decide if some sort of workaround is needed in my own application.

**Comment by rkern** [comment]
What you are observing is an intentional design choice constrained by what's possible in Python's type system (i.e. `np.int_` cannot subclass `int` because in Python 3, `int`s are no longer built around a C type).
