### ISSUE TITLE
The pygments 2.7.0 release breaks custom NumPyC lexer

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17301]
Complains about `DISTUTILS.rst.txt` line 431.
```
.. code-block:: NumPyC
```
None of this markup is new, so something else has changed.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by seberg** [comment]
Hmmm, there is this setup:
```
def setup(app):
    # add a config value for `ifconfig` directives
    app.add_config_value('python_version_major', str(sys.version_info.major), 'env')
    app.add_lexer('NumPyC', NumPyLexer)
```
function in `doc/source/conf.py`. I guess for some reason that stopped working?!

**Comment by mattip** [comment]
Scolling to the end of the "build numpy" step from a  [successful CirclCI run](https://circleci.com/api/v1.1/project/github/numpy/numpy/15693/output/103/0?file=true&allocation-id=5f5d313d437a5406b309d0f4-0-build%2F3C094ACC) and the one from a [later failing run](https://circleci.com/api/v1.1/project/github/numpy/numpy/15692/output/103/0?file=true&allocation-id=5f5d1adf7232fa63671ba3cf-0-build%2F20983BCF) it seems somehow `pip install -r doc_requirements.txt` is failing to install sphinx. In fact, the failed run does not even report that the version of sphinx is up to date. [Here](https://app.circleci.com/pipelines/github/numpy/numpy) is the CircleCI history. I pasted the relevant part of the CircleCI "build numpy" step below for reference

<details>

```
      - run:
          name: build numpy
          command: |
            . venv/bin/activate
            pip install --upgrade pip 'setuptools<49.2.0'
            pip install -r test_requirements.txt
            pip install .
            pip install -r doc_requirements.txt


```

**Comment by mattip** [comment]
Closing, it seems to be resolved. Please reopen as needed or open a new issue.
