### ISSUE TITLE
Use of PyArrayObject or PyArrayObject_fields type for C extension with numpy

### ISSUE THREAD

**Issue by marcocod** [numpy/numpy#17306]
This is a documentation issue.
I'm writing a c extension module that uses numpy object. In the page https://numpy.org/doc/stable/reference/c-api/types-and-structures.html it is written to use the PyArrayObject and it works, but the compiler gives the following warning:

#warning directive: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"

If I add this define I cannot use the PyArrayObject anymore.
Looking the include of numpy ndarraytypes.h it seems that I have to use the PyArrayObject_fields type instead.
I would like to know if it's better to use the PyArrayObject and ignore the warning of deprecated api, or it's better to use the PyArrayObject_fields though is not mentioned in the documentation.
I dont' feel very confortable looking the headers files on my own instead of using the official documentation.

**Comment by eric-wieser** [comment]
You should use neither, and use the other API functions to extract the information you need from the `PyArrayObject`

**Comment by marcocod** [comment]
Ok, I used the PyArrayObject type with the macro PyArray_DATA and it works without warnings.
Sorry but I was accessing directly to the struct fields.

**Comment by marcocod** [comment]
Ok, I used the PyArrayObject type with the macro PyArray_DATA and it works without warnings.
Sorry but I was accessing directly to the struct fields.
