### ISSUE TITLE
mypy test errors when using `python runtests.py`

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17316]
I see 14 typing errors that seem related to the added stubs when simply using runtests.py in the usual way. I assume that I am missing something but have no idea what it is.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mattip** [comment]
I am also seeing failures at commit 7b7e7fe4936a in `numpy/typing/tests/test_typing.py`. The travis test installs numpy, then does `mkdir -p empty; cd empty; python ../runtests.py` Perhaps some of the data files are missing from the shipped wheel, or a package version is causing some test variants to be skipped? I see 50 dots in the successful run, so that implies 50 tests are being run, which is the same as my local run, but I get "36 failed, 14 passed, 1 warning in 203.63s"



<details>

For reference, a [passing travis log](https://travis-ci.org/github/numpy/numpy/jobs/727196251#L6591) shows [these packages](https://travis-ci.org/github/numpy/numpy/jobs/727196251#L6151):
> Successfully installed attrs-20.2.0 cffi-1.14.2 coverage-5.3 hypothesis-5.35.1 iniconfig-1.0.1 more-itertools-8.5.0 mypy-0.782 mypy-extensions-0.4.3 packaging-20.4 pluggy-0.13.1 py-1.9.0 pycparser-2.20 pyparsing-2.4.7 pytest-6.0.2 pytest-cov-2.10.1 pytz-2020.1 six-1.15.0 sortedcontainers-2.2.2 toml-0.10.1 typed-ast-1.4.1 typing-extensions-3.7.4.3

**Comment by mattip** [comment]
@BvB93 ping

**Comment by BvB93** [comment]
Locally I'm not seeing any typing-related errors when running either `python runtests.py -t numpy/typing` or the full test suit with `mkdir -p empty; cd empty; python ../runtests.py`. Am i missing something here?

**Comment by charris** [comment]
`python3.8 runtests.py -t numpy/typing` fails for me. My Python version is 3.8.5.

**Comment by mattip** [comment]
Thanks for checking. It might be something from the package list in the details above. Locally I see these differences (all the others are the same, especially `mypy*`, `typ*`):

package | my version |travis version
---|---|---
attrs | 19.3.0 | 20.2.0
cffi | 1.14.1 | 1.14.2
coverage | 5.2.1 | 5.3
hypothesis | 5.33.0 | 5.35.1
more-itertools | 8.4.0 | 8.5.0
pytest | 6.0.1 | 6.0.2

**Comment by BvB93** [comment]
For reference (macOS, python 3.8.3):

package | my version |travis version
---|---|---
attrs | 19.3.0 | 20.2.0
cffi | 1.14.2 | 1.14.2
coverage | 5.1 | 5.3
hypothesis | 5.26.0 | 5.35.1
more-itertools | 8.3.0 | 8.5.0
pytest | 6.0.1 | 6.0.2

Could any of you show me an example of these failed test runs?
I'm curious as to whether they contain any useful information.

**Comment by mattip** [comment]
It seems to be some failure in mypy serializing? [here is the output](https://gist.github.com/mattip/efe21e39bf2c4ca99998b32fc261952f) of the tests. The first assertion error is on line 1635 of that output.

**Comment by BvB93** [comment]
Yes, there is definitely something wrong with mypy itself here.
The `AssertionError` seems to be raised somewhere during the `mypy.api()` call, just before the actual typing tests themselves are run.

The lack of actual error messages isn't helping either...
```
>   ???
E   AssertionError
```

**Comment by BvB93** [comment]
After clearing out my mypy cache I've finally managed to reproduce the issue, though only when running `python ./runtests.py --mypy numpy`. Apparently it's an unsolved bug related to import cycles (https://github.com/python/mypy/issues/8481) and indeed, removing `core` from the imports seems to resolve the issue. 

This is definitely something to keep an eye out for in the future, especially once annotations are added for public sub-modules.
