### ISSUE TITLE
Increased output when running f2py (possibly due to SIMD detection code)

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#17321]
In NumPy 1.20, when compiling extensions with f2py, there is a lot of compiler options/testing output that is not there in 1.19:

### Reproducing code example:

Saving `fib1.f` from [the documentation](https://numpy.org/devdocs/f2py/f2py.getting-started.html) and running

```bash
f2py -c -m fib1 fib1.f
```

results in several blocks similar to

```
compile options: '-I/opt/miniconda3/envs/numpy-dev/include/python3.8 -c'
extra options: '-msse2'
CCompilerOpt.feature_test[1448] : testing feature 'SSE' with flags (-msse -msse2)
C compiler: gcc -pthread -B /opt/miniconda3/envs/numpy-dev/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
```

[Full output in a pastebin](https://pastebin.com/HrJgK9Km)

This also increases the compilation time as several of those tests are apparently executed during compilation.

### Numpy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.0.dev0+087ad5e 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0]
```

**Comment by seiko2plus** [comment]
I think we can just explicitly disabling `CCompilerOpt` through `--disable-optimization` since Fortran isn't supported yet.
```diff
--- a/numpy/f2py/f2py2e.py
+++ b/numpy/f2py/f2py2e.py
@@ -650,7 +650,9 @@ def run_compile():
     sys.argv.extend(['build',
                      '--build-temp', build_dir,
                      '--build-base', build_dir,
-                     '--build-platlib', '.'])
+                     '--build-platlib', '.',
+                     # disable CCompilerOpt
+                     '--disable-optimization'])
     if fc_flags:
         sys.argv.extend(['config_fc'] + fc_flags)
     if flib_flags:
````

**Comment by seiko2plus** [comment]
@melissawm,
> This also increases the compilation time as several of those tests are apparently executed during compilation.

Only for the first time, since `CCompilerOpt` should cache test cases.

**Comment by seiko2plus** [comment]
@rgommers, Should we support infrastructure SIMD optimizations for Fortran and Cython(we can allow universal intrinsics)?

**Comment by melissawm** [comment]
> @melissawm,
> 
> > This also increases the compilation time as several of those tests are apparently executed during compilation.
> 
> Only for the first time, since `CCompilerOpt` should cache test cases.

Note really what I'm observing. Re-running the command a few times without changing the code gives me the same compilation time for every run, about 5 seconds:
```bash
real    0m5,393s
user    0m4,600s
sys     0m0,950s
```
For NumPy 1.19 I get ~1sec:
```bash
real    0m0,940s
user    0m1,067s
sys     0m0,332s
```
I don't think this is a huge deal but I guess it could cause big compilation times in packages that make extensive use of f2py. Disabling `CCompilerOpt` seems reasonable for now.

**Comment by seiko2plus** [comment]
@rgommers,
> Cython: not sure, what would that take? Doesn't seem like a priority anyway, let's focus on regular C code and performance-critical parts like ufunc loops first.

We can discuss it later but it would better if we just passed the baseline compiler flags to the generated C sources,
in case if the user changed the default configuration of `--cpu-baseline`.

@melissawm,
> > > This also increases the compilation time as several of those tests are apparently executed during compilation.
> > 
> > 
> > Only for the first time, since `CCompilerOpt` should cache test cases.
> 
> Note really what I'm observing. Re-running the command a few times without changing the code gives me the same compilation time for every run, about 5 seconds:

Aaah, I take it back the `CCompilerOpt` cache doesn't work within `f2py` due to removing the build dir
if the default of `--build-dir` set to `tempfile.mkdtemp()`. see ->

https://github.com/numpy/numpy/blob/08690a9e394406562f636f90bcc899430bf3cdee/numpy/f2py/f2py2e.py#L91-L93

https://github.com/numpy/numpy/blob/08690a9e394406562f636f90bcc899430bf3cdee/numpy/f2py/f2py2e.py#L514-L516

>  I don't think this is a huge deal but I guess it could cause big compilation times in packages that make extensive use of f2py. Disabling CCompilerOpt seems reasonable for now.

Indeed, I'm going to open a pull request for it, thank you for your report.
