### ISSUE TITLE
numpy.unqiue inconsistent for float close to 0

### ISSUE THREAD

**Issue by lucyleeow** [numpy/numpy#17327]
Inconsistent behaviour of `numpy.unique` for floats above and below 0 vs other numbers (see code). e.g., `(0 - 1e-310)` and `0` are kept as unique values whereas `3` and `(3 + 1e-310)` are one value (3) after `np.unique`.
Not sure if this is expected behaviour, if so please let me know.

### Reproducing code example:

```python
import numpy as np
a = np.array([-1, (0 - 1e-310), 0, (0 + 1e-310), 1, (1 + 1e-310), 3, (3 + 1e-310)])
np.unique(a)
```
returns:
```
array([-1.e+000, -1.e-310,  0.e+000,  1.e-310,  1.e+000,  3.e+000])
```

### Numpy/Python version information:

> 1.18.3 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]

(Related to https://github.com/scikit-learn/scikit-learn/pull/17758#issuecomment-690129182)

**Comment by eric-wieser** [comment]
Well, according to python
```python
>>> 3 + 1e-310 == 3
True
```
