### ISSUE TITLE
Add JMP/SAS/Minitab Quantile/Percentile method to np.percentile

### ISSUE THREAD

**Issue by jelther** [numpy/numpy#17322]
### Reproducing code example:

The quantile method that JMP software [(JMP Documentation)](https://www.jmp.com/support/help/en/15.1/#page/jmp/quantiles.shtml#ww1685306) uses is not covered by numpy.

```python
import numpy as np

seriessample = [1,2,3,4]

print(f"Series Sample {seriessample}.")
for interpolation in {'linear', 'lower', 'higher', 'midpoint', 'nearest'}:
    print(f"Method {interpolation}")
    for q in [0.25,0.75]:
        print(f"Quantile {q} ;"
              f"Value = {np.quantile(seriessample,q,interpolation=interpolation)}")

"""
Output:

Series Sample [1, 2, 3, 4]

Method nearest
    Quantile 0.25 ;Value = 2
    Quantile 0.75 ;Value = 3

Method linear
    Quantile 0.25 ;Value = 1.75
    Quantile 0.75 ;Value = 3.25

Method midpoint
    Quantile 0.25 ;Value = 1.5
    Quantile 0.75 ;Value = 3.5

Method higher
    Quantile 0.25 ;Value = 2
    Quantile 0.75 ;Value = 4

Method lower
    Quantile 0.25 ;Value = 1
    Quantile 0.75 ;Value = 3
"""
```

### Expected output:

For the series [1,2,3,4], according to [this link](http://jse.amstat.org/v14n3/langford.html) the quantiles q1 and q3 should be (1.25, 3.75).

### Numpy/Python version information:

```
1.19.1 3.8.1 (default, Sep  3 2020, 10:23:25) 
[GCC 9.3.0]
```

### Additional Info:

It's expected to have numerous number of quantile methods. Despite that, numpy should cover what other numerical softwares use to be able to cross code between the plataforms.

**Comment by eric-wieser** [comment]
See also #10736

**Comment by seberg** [comment]
Probably this is `"inverted_cdf"` these days.  I don't think I have much appetite for more modes to quantile.  But if there is a clear request (based off what we have now), we should open a new issue.
