### ISSUE TITLE
DOC: NumPy distutils documentation is focused on SciPy

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#17323]
The [NumPy Distutils User Guide](https://numpy.org/devdocs/reference/distutils_guide.html) presents adding new features to SciPy as its main motivation. This may actually be the case, but I'd think that this piece of documentation belongs in SciPy, not NumPy. The user guide should focus more on distutils itself, and link to the "Adding new SciPy features" from the SciPy docs (for the moment, they actually point to NumPy's User Guide for this).

**Comment by rgommers** [comment]
This is a fairly hopeless case. `numpy.distutils` is going to change significantly in the coming 1-2 years (because of `distutils` being merged into `setuptools`), so I would not spend any effort on touching the docs for it now.

**Comment by melissawm** [comment]
Ok, that makes sense. Thanks for the info!
