### ISSUE TITLE
ENH: add a canonical way to determine if dtype is integer, floating point or complex

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#17325]
There is currently no good way (AFAIK) to figure out if the dtype of an array is integer, floating point or complex. Right now one of these is the most common probably:
```
x.dtype.kind in np.typecodes["AllFloat"]
```

```
np.issubdtype(x.dtype, np.floating)
```

Both are pretty awful.

A naive way to write code in the absence of something like `is_floating_point`/`is_integer`/`is_complex` would be:
```
x.dtype in (np.float16, np.float32, np.float64)
```
The trouble is that we have extended precision dtypes, and only one of `float96` or `float128` will actually exist (the other one will raise an `AttributeError`, also annoying and a frequent source of bugs).

Adding a set of functions `is_floating_point`/`is_integer`/`is_complex` (whether with or without an underscore in the name, or naming it `floating` or `floating_point`) seems like a good idea to me. 

In other libraries: TensorFlow doesn't seem to have any API for this, PyTorch has `is_floating_point` and `is_complex`.

Thoughts?

**Comment by eric-wieser** [comment]
In my mind, we already have canonical spellings for these and they areare:

* `np.issubdtype(x.dtype, np.integer)`
* `np.issubdtype(x.dtype, np.floating)`
* `np.issubdtype(x.dtype, np.complexfloating)`

Perhaps these spellings are too long, but "provide a convenient spelling" is different to "provide a canonical one".

---

> The trouble is that we have extended precision dtypes, and only one of float96 or float128 will actually exist (the other one will raise an AttributeError, also annoying and a frequent source of bugs).

While I would not recommend using this approach of listing the types, the safe spelling is
```
x.dtype in (np.half, np.single, np.double, np.longdouble)
```

**Comment by rgommers** [comment]
> In my mind, we already have canonical spellings for these and they are

There's a number of issues with that:

- It's not documented as far as I can tell, I'd expect it in https://numpy.org/devdocs/reference/arrays.dtypes.html or on https://numpy.org/devdocs/reference/routines.dtype.html.
- If I check NumPy and SciPy both methods I mentioned are used 
- If one reads the docstring for `np.floating`, all it says is _"Abstract base class of all floating-point scalar types"_. So someone familiar with Python would probably try to use `isinstance` first.
- The `issubdtype` docstring says _"Returns True if first argument is a typecode lower/equal in type hierarchy."_ which won't make sense to many users, and it's not even clear why one would prefer that over `issubsctype` given the one-line descriptions.
- Users that want to know "is this an array of floats or integers?" shouldn't have to understand the details of NumPy's dtype hierarchy.

I'm not too interested in arguing about the semantics of "canonical", so let me just say: there is no good way of doing this currently - should we add `is_floating`, `is_complex` and `is_integer` or something similarly named as a sane way of doing this?

**Comment by eric-wieser** [comment]
My leaning is towards making the documentation much clearer for [`issubdtype`](https://numpy.org/doc/stable/reference/generated/numpy.issubdtype.html) and those abstract classes.  We already have an open issue about the various inconsistent pages documenting the scalar types, fixing that would help a fair bit here.

Also, we already have

* [`iscomplex`](https://numpy.org/doc/stable/reference/generated/numpy.iscomplex.html)
* [`iscomplexobj`](https://numpy.org/doc/stable/reference/generated/numpy.iscomplexobj.html)
* [`isreal`](https://numpy.org/doc/stable/reference/generated/numpy.isreal.html)
* [`isrealobj`](https://numpy.org/doc/stable/reference/generated/numpy.isrealobj.html)

IMO, introducing more functions will make things more confusing not less.

**Comment by rgommers** [comment]
Oh yes, that doesn't help, more weird and badly documented functions:(
```
In [13]: z = np.arange(3, dtype=np.complex64)                              

In [14]: np.iscomplex(z)                                                   
Out[14]: array([False, False, False])

In [15]: np.iscomplexobj(z)                                                
Out[15]: True

In [16]: np.iscomplexobj(z.dtype)   # iscomplexobj docstring: "Check for a complex type ...."                        
Out[16]: False
```

**Comment by eric-wieser** [comment]
>  it's not even clear why one would prefer that over `issubsctype` given the one-line descriptions.

It looks like this we probably should deprecate one or of the other of these. `issubsctype` looks weird, because it tries to squash the semantics of `isinstance` and `issubclass` into a single function.

**Comment by rgommers** [comment]
Deprecating `issubsctype` sounds like a good idea to me - but then maybe all the other `sctype` ones as well? 

And hide some of the other weird stuff like `issubclass_` towards the bottom of the page with some disclaimer, if we don't want to deprecate it?

**Comment by andyfaff** [comment]
You can distinguish integers from floating point immediately using `np.issubdtype(o, np.inexact)`

**Comment by seberg** [comment]
My mid-term goal would be that we do have an inexact DType, to be just a bit clearer than the `np.inexact` scalar.  `np.issubdtype` does not check whether it is an "instance" (e.g. array with an inexact dtype or scalar of one).

That does not actually touch `np.issubdtype`, it rather makes it more precise/extensible.

I do not think we have API equivalent to pythons `isinstance`, which would be something like:
```
def is_dtype_instance(obj, DType):
    return isinstance(np.array(obj).dtype, DType)
```
Admittingly, it currently works with `np.issubdtype`, but that is only because `np.dtype(obj)` works if `np.dtype(obj.dtype)` succeeds.
That is the weird dual use Eric was referring too.  `np.issubdtype` is really equivalent to `issubclass`.

**Comment by andyfaff** [comment]
On a semi related topic, is it possible to enumerate all the inexact types somehow? Is there a list somewhere?

**Comment by seberg** [comment]
`np.typecodes` has them in a sense, other than that, probably not unless you want to check `__subclasses__()`...

**Comment by andyfaff** [comment]
Are typecodes that the machine doesn't support eliminated from that list?

**Comment by eric-wieser** [comment]
There is no such thing as an unsupported type, only aliases that exist on some but not all platforms.

**Comment by axil** [comment]
The very first example from the first post:

`x.dtype.kind in np.typecodes["AllFloat"]`

is apparently incorrect:

```
>>> np.array([1,2,3], dtype=np.uint8).dtype.kind in np.typecodes['UnsignedInteger']
False
>>> np.array([1,2,3], dtype=np.uint8).dtype.kind in np.typecodes['AllInteger']
False
```

It should've been `x.dtype.char` instead of `x.dtype.kind`:

```
>>> np.array([1,2,3], dtype=np.uint8).dtype.char in np.typecodes['UnsignedInteger']
False
>>> np.array([1,2,3], dtype=np.uint8).dtype.char in np.typecodes['AllInteger']
False
```

Also, `bool`, `str`, `bytes`, `object` and `void` dtypes ('?', 'U', 'S', 'O', 'V' accordingly) are missing from the `np.typecodes` dict (except under the 'All' key).

**Comment by ntessore** [comment]
FWIW, when implementing special functions, I find `iscomplexobj` to be the most useful interface. That's usually either for determining whether an input dtype needs to be widened for functions mapping reals to complexes,[^1] or whether a faster branch can be taken for purely real input.

[^1]: I would love to have a companion `ascomplexobj()` function that takes care of figuring out the appropriate complex type.

**Comment by rgommers** [comment]
For 2.0 we deprecated or removed `sctype` APIs, we cleaned up dtype aliases so there's one canonical name for each dtype with Pythonic and one with C-like names, and we added `numpy.isdtype`. So I think we addressed this issue to a sufficient extent.

Thanks all!
