### ISSUE TITLE
alternative to MATLAB's `my_array = start : step : stop`

### ISSUE THREAD

**Issue by Felix-neko** [numpy/numpy#17339]
Hi folks! And thank you for a brilliant project.

We are migrating from MATLAB to numpy and have to port some MATLAB code to Python. In MATLAB we often used such languate idiom as  `my_array = start : step : stop`. It's just like `np.arange`, but stop value is also included to arrray if last step steps on it.

Can you support an option to enable same behaviour for `np.arange`?

**Comment by mattip** [comment]
I think you are looking for [`linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace) especially if any of start, stop, step are floating-point values. If you are using integers and really want to use `step`, just use `stop + step` as the endpoint.

**Comment by Qiyu8** [comment]
@Felix-neko I'm interested in your motive for migrating, can you describe your requirements in detail, there are plenty of works to do if you want to migrate from MATLAB to numpy, and we are willing to help.

**Comment by Felix-neko** [comment]
> @Felix-neko I'm interested in your motive for migrating, can you describe your requirements in detail, there are plenty of works to do if you want to migrate from MATLAB to numpy, and we are willing to help.

My motivation to migrate from MATLAB to Python is simple: MATLAB is a good choice to make a single-page calculation script, but it is not an option to create complicated projects with dozens of connected classes. MATLAB lacks general purpose libraries, there are no even such library as C++ STL. Of course we want migrate to Python and forget MATLAB as a nightmare.

**Comment by InessaPawson** [comment]
@Felix-neko I’ll close this issue as @mattip has already answered your question.
For further information about the NumPy functions for partitioning domains, refer to this how-to-guide: [numpy.org/doc/stable/user/how-to-partition.html](https://numpy.org/doc/stable/user/how-to-partition.html).
