### ISSUE TITLE
update PyPI classifiers to not install with unsupported Python versions

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#17349]
Right now if you do `pip-3.9 install numpy`, it will try to build NumPy for a version that does not support Python 3.9 yet (as stated in the release notes, and in `numpy/__init__.py`). We should see if we can fix the PyPI classifiers for this.

EDIT: or it's `python_requires='>=3.6'` in `setup.py`.

**Comment by eric-wieser** [comment]
It's definitely python_requires that's relevant.

**Comment by hugovk** [comment]
Do you mean by setting an upper bound, like `python_requires='>=3.6,<3.9'`?

I think the new problem would be that pip will just loop through releases and reject any with that, but find an older version with `python_requires='>=3.6'` and fail on that instead.

**Comment by eric-wieser** [comment]
Yeah, I think @hugovk's point is a good one here - it sounds like doing this will make things worse not better.

Perhaps we should simply emit a warning in setup.py?

**Comment by rgommers** [comment]
Good point. Warning in `setup.py` makes sense to me.
