### ISSUE TITLE
print(np.arange(0.1,0.4,0.1)) returns [0.1 0.2 0.3 0.4]

### ISSUE THREAD

**Issue by alexlim510** [numpy/numpy#17342]
### Reproducing code example:

```python
import numpy as np
print(np.arange(0.1,0.4,0.1))
```

### Error message:

returns [0.1 0.2 0.3 0.4]
### Numpy/Python version information:

1.16.0 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

**Comment by melissawm** [comment]
Hi @alexlim510 , this is known behavior. From the `arange` documentation:

> When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.

See, for example, #17189 .

**Comment by alexlim510** [comment]
I see! Pardon me for not reading the documentation .
