### ISSUE TITLE
Inconsistent dtype behavior of ragged array creation

### ISSUE THREAD

**Issue by Temigo** [numpy/numpy#17345]
I wonder whether this behavior is expected or not in the creation of ragged arrays. 

 When creating an array of subarrays of different lengths (i.e. ragged array), I want to enforce that the subarrays are of dtype `np.int64`. To create a ragged array, we also now need to explicitly set `dtype=object` on the parent array. It works fine most of the time (i.e. the parent array gets dtype `object`, the child arrays have dtype `np.int64` after casting them), except when all subarrays have the same length (i.e. when it *could* be a regular array, not a ragged array). In that case, all the child arrays get assigned a dtype `object` regardless of my casting to `np.int64`. 

### Reproducing code example:

If I turn a list of subarrays of varying lengths and dtype `np.int64` into a ragged array, the subarrays keep their dtype `np.int64`. If instead all subarrays have the same length (includes the case where there is only 1 subarray), all subarrays are assigned a dtype `object`.

```python
        >>> import numpy as np
        >>> # A single array - was expecting [dtype('int64')]
        >>> a = np.array([np.array([0,1,2,3]).astype(np.int64)], dtype=object)
        >>> [x.dtype for x in a]
        [dtype('O')]
        >>> # 2 arrays of different lengths (ragged array) - works fine
        >>> a = np.array([np.array([5]).astype(np.int64), np.array([6,7]).astype(np.int64)], dtype=object)
        >>> [x.dtype for x in a]
        [dtype('int64'), dtype('int64')]
        >>> # 2 arrays of same length (pseudo ragged array?) - was expecting [dtype('int64'), dtype('int64')]
        >>> a = np.array([np.array([5,6]).astype(np.int64), np.array([6,7]).astype(np.int64)], dtype=object)
        >>> [x.dtype for x in a]
        [dtype('O'), dtype('O')]
```

### NumPy/Python version information:
Python 3.6.9

NumPy 1.19.0 3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]

**Comment by seberg** [comment]
I guess it is expected, but definitely surprising.  NumPy always tries to unpack arrays contained in a nested list for `np.array()`. So in most cases (i.e. when the shape matches), it will basically call `arr.astype(new_dtype)` on the array inside the list.
The odd case is the ragged version, where NumPy realizes that it cannot unpack the array and then is OK with just storing the full array (never calling `arr.astype(new_dtype)`.

It is possible to force the behaviour of the ragged case, if you know the result shape that you are expecting:
```
seq = [np.array([0,1,2,3]).astype(np.int64)]
a = np.empty(len(seq), dtype=object)
a[...] = seq
```

**Comment by Temigo** [comment]
Ok, that makes sense. Thank you for your explanation!

**Comment by seberg** [comment]
Hmm, it is annoying that this means that `dtype=object` is often not a correct drop in to replace the warning.  It could be nice if we can come up with documentation/deprecation warning that would have helped you.
