### ISSUE TITLE
latest numpy version is not supported in AWS lambda deployment package

### ISSUE THREAD

**Issue by ManudattaG** [numpy/numpy#17355]
I am using Python 3.8 and installed numpy 1.19.2 as well as tried with 1.17 as deployment package to layers in aws lambda function. I am getting errors

1. Error when I tried with 1.17
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /var/lang/bin/python3.8),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

2. Error when tried with 1.19.2
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/var/lang/bin/python3.8"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

Please suggest. Thanks!

**Comment by pdangelo4** [comment]
Hi @ManudattaG 

Had the same issue.

Add a second layer to your lambda,  choose AWS Layers > AWSLambda-Python38-SciPy1x

in the dropdown for it you will notice it includes numpy 1.19.2

Hope that helps

**Comment by jbblanton** [comment]
I have also spent the day struggling with this. I tried a few things and, ultimately, ended up reverting my Lambda function to runtime of Python 3.7. Then I used of the AWS layer for SciPy (provides a working numpy) + a shared layer for pandas-gbq (provides a working pandas), found here - https://github.com/mthenw/awesome-layers

**Comment by seberg** [comment]
Since this was about running on AWS and not NumPy itself (and is pretty old now anyways), closing.
