### ISSUE TITLE
Mypy static checking fails for any numpy import

### ISSUE THREAD

**Issue by Vozf** [numpy/numpy#17358]
When importing numpy
``` 
import numpy as np
```
and checking with mypy it fails with 
```
error: Skipping analyzing 'numpy': found module but no type hints or library stubs
```
There is also missing `py.typed` in python/lib/numpy after installation however it is present in the repository

np==1.19.2

**Comment by BvB93** [comment]
> np==1.19.2

This is the crux of the issue: the new typing features are scheduled to be released with numpy 1.20.

**Comment by Vozf** [comment]
So mypy shouldn't work in 19.2?

**Comment by BvB93** [comment]
Yes, for the time being you can either silence the errors globally with the 
[ignore-missing-imports](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-ignore-missing-imports) mypy option or silence them specifically for numpy:

``` python
import numpy as np  # type: ignore[import]
```

In both cases `np` will be inferred as `typing.Any`.

**Comment by Vozf** [comment]
Ok. thanks.
