### ISSUE TITLE
no module named numpy

### ISSUE THREAD

**Issue by tushart04** [numpy/numpy#17363]
I have install numpy in Visual code using this intallation process 
pip install numpy 
it was properly however i am practising the programming code for numpy its throws the error saying 
  File ".\Arrayslice.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
I tried mpip install numpy still this issue is not fix

**Comment by mattip** [comment]
If that is the entire error message, you probably have two python environments on you computer. One is being used by Visual Code, and you installed numpy in the other. You can debug this by putting these lines in `Arrayslice.py` just before `import numpy as np`, and it will print which python you are using.
```
import sys
print(sys.executable)
```

You may find the hints on [this page](https://numpy.org/devdocs/user/troubleshooting-importerror.html) helpful

**Comment by tushart04** [comment]
import sys
print(sys.executable)
import numpy as np
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is:')
print(x)
print('\n')
# Now we will print the items greater than 5

print('The items greater than 5 are: ')
print(x[x>5])

This is my code and i have tried what you have ask for 

this is the output i got 

py .\BooleanIndex.py
C:\Users\Aman\AppData\Local\Programs\Python\Python38\python.exe
Traceback (most recent call last):
  File ".\BooleanIndex.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by mattip** [comment]
OK, so you should always use `C:\Users\Aman\AppData\Local\Programs\Python\Python38\python.exe` as your python:
```
C:\Users\Aman\AppData\Local\Programs\Python\Python38\python.exe -mpip install numpy
```

When you paste output, you can use the "format code" option on the toolbar, to get the proper formatting. I reformatted your reply.

**Comment by mattip** [comment]
Also: please spend some time looking at  [this page](https://numpy.org/devdocs/user/troubleshooting-importerror.html). You are not the first person to encounter this problem, others have given hints that may help you, especially the section on [visual code](https://numpy.org/devdocs/user/troubleshooting-importerror.html#using-vscode-with-anaconda-conda-python-or-environments)

**Comment by developershutt** [comment]
try "pip3 install numpy --no-cache-dir" instead of "pip install numpy"

**Comment by seberg** [comment]
Going to close, since it is almost certainly a problem with how VS Code's python environment is set up, and has been inactive for >1 year.
