### ISSUE TITLE
when i change tf.random.normal to np.random.normal,somthing went worry

### ISSUE THREAD

**Issue by pengweimin** [numpy/numpy#17366]
noise = np.random.normal(size= [32, 100])
since the tf.random.normal default output is float32
so
--------------------------------------
noise = noise.atype(np.float32)
--------------------------------------
and change to tensor
--------------------------------------
 noise = tf.convert_to_tensor(noise)
----------------------------------------
then

AttributeError: 'numpy.ndarray' object has no attribute 'atype'

**Comment by rkern** [comment]
You have a typo: `atype` should be `astype`.
