### ISSUE TITLE
Very small differences in `randn()` values since NumPy 1.17

### ISSUE THREAD

**Issue by cthiemann** [numpy/numpy#17379]
I'm maintaining an extension module which uses a copy of randomkit to produce the same random numbers as NumPy's `randn()`. After upgrading NumPy from 1.16.4 to 1.18.4, a unit-test asserting identical random number sequences failed.

On first sight, #16715 looked like my problem, but since I'm compiling NumPy and the extension on the same machine, I can rule out libc or other library changes. After some digging around, I'm pretty sure that the culprit is the `-std=c99` flag being used for compiling `numpy.random` since NumPy 1.17.

I appreciate that the differences are very small (certainly look like rounding errors), but they are definitively due to a change in NumPy and not in the environment. Whether this violates the stream-compatibility guarantee is not for me to assess, but in case it helps, here's how I narrowed it down to the compiler flag:

Fetch an older version of `randomkit.{h,c}` (which doesn't need NumPy headers to compile), e.g.:

- https://github.com/numpy/numpy/blob/v1.10.0/numpy/random/mtrand/randomkit.h
- https://github.com/numpy/numpy/blob/v1.10.0/numpy/random/mtrand/randomkit.c

Then, save and run this simple C program:

```
#include <stdio.h>
#include "randomkit.h"

int main(int argc, char *argv) {
    double v;
    rk_state state;
    rk_seed(4, &state);
    for (int i = 0; i < 35; i++) {
        v = rk_gauss(&state);
    }
    printf("%30.25f\n", v);
}
```

Here's the output with different compiler flags (I wouldn't be surprised if the differences depend on the CPU type, so you may have to change the `35` in the for loop to select a number that's actually different):

```
$ gcc rktest.c randomkit.c -o rktest -lm && ./rktest
  -1.1055840438194008967798254
$ gcc rktest.c randomkit.c -o rktest -lm -march=native -Os && ./rktest
  -1.1055840438194013408690353
$ gcc rktest.c randomkit.c -o rktest -lm -march=native -Os -std=c99 && ./rktest
  -1.1055840438194008967798254
```

I have to add both `-march=native` and `-Os` (or `-O2` or `-O3`) to get the number ending in `353`, but I use those flags for compiling both NumPy and my extension module. The `-std=c99` flag added by NumPy's `setup.py` for `numpy.random` will make `randn()` return the `...254` number while my extension module returns the `...353` number.

This seems related to #15237 but #16619 is not a fix in this case because the `setup.py` for `numpy.random` explicitly adds `-std=c99` while #16619 only auto-adds the flag if using an old GCC compiler. There's a comment in `numpy/random/setup.py` saying some bit generators require C99, but I only see a reference to that in PCG64 which suggests it needs C99 or better, not downgrading to C99.

It sounds like the explicit flag should be removed from `setup.py` then, or am I missing something?

**Comment by charris** [comment]
NumPy does require c99 compatibility these days, but as noted, whether a flag is needed depends on the (gcc) compiler version and we intended to make that explicit. So this sounds like a bug.

**Comment by charris** [comment]
Just to be sure, you also check the actual numbers rather than their printed values?

**Comment by charris** [comment]
Also, we cannot make the guarantee for random distributions that depend on library implementations of floating point functions. Note that `rk_gauss` uses `log` and `sqrt`. That we did make that guarantee was an oversight.

**Comment by rkern** [comment]
No, we did call out that source of variability even in the old policy. The issue here is that the only thing that changed was `numpy` choosing to use different build settings, and thus pulling in different libraries (or maybe some other rearrangement of the floating point arithmetic). This is close to, but still a little distinct from the situation where a _user_ decides to build with a different compiler, etc. I don't know if it's distinct enough to yank out that build flag for `mtrand`. I'm increasingly tired of trying to nail down everything to the last bit. But if it's easy to drop that build flag, maybe it's worth it.

**Comment by cthiemann** [comment]
Thanks for your quick replies!

Yes, I also compared the actual numbers. The failing unit test looks something like this:
```
rng = numpy.random.mtrand.RandomState()
rng.seed(4)

state = ext.get_rk_state()
ext.rk_seed(4, state)

for i in range(45):
    self.assertEqual(ext.rk_gauss(state), rng.randn())
```
And fails with:
```
AssertionError: -1.1055840438194013 != -1.105584043819401
```

As for being "tired of trying to nail down everything to the last bit": I hear you and hope I didn't contribute to any frustration. I had meant to reply to #16715 just for the benefit of future internet travellers coming across it via searching, but then realized that my problem was slightly different and apparently easy to fix (pending review by someone who actually knows a thing about the `numpy.random` bit-generators). However, we're about to migrate to the new PCG64 anyway (and use it via the C API instead of copying code), so the only real effect of fixing this might as well just be you gaining a handful of academic respect points from a neuroscience professor (and myself) who loves NumPy as much as nailing down everything to the last bit ;-)

**Comment by rkern** [comment]
> As for being "tired of trying to nail down everything to the last bit": I hear you and hope I didn't contribute to any frustration.

No worries, you're not. I'm entirely hoist by my own petard, here. :-)

**Comment by charris** [comment]
Should we close this?

**Comment by seberg** [comment]
Closing this, as suggested also by Chuck here.  (This was never guaranteed, which may be unfortunate, but it isn't really under numpy's control anyway.)
