### ISSUE TITLE
test_structured_object_indexing seems racy

### ISSUE THREAD

**Issue by StefanBruens** [numpy/numpy#17381]
On the openSUSE OBS, there are occasional failures of the test_structured_object_indexing test:

```
[  740s]     def test_structured_object_indexing(self, shape, index, items_changed,
[  740s]                                         dt, pat, count, singleton):
[  740s]         """Structured object reference counting for advanced indexing."""
[  740s]         zero = 0
[  740s]         one = 1
[  740s]     
[  740s]         arr = np.zeros(shape, dt)
[  740s]     
[  740s]         gc.collect()
[  740s]         before_zero = sys.getrefcount(zero)
[  740s]         before_one = sys.getrefcount(one)
[  740s]         # Test item getting:
[  740s]         part = arr[index]
[  740s]         after_zero = sys.getrefcount(zero)
[  740s]         assert after_zero - before_zero == count * items_changed
[  740s]         del part
[  740s]         # Test item setting:
[  740s]         arr[index] = one
[  740s]         gc.collect()
[  740s]         after_zero = sys.getrefcount(zero)
[  740s]         after_one = sys.getrefcount(one)
[  740s] >       assert before_zero - after_zero == count * items_changed
[  740s] E       assert 11 == 12
[  740s] E         +11
[  740s] E         -12
```
Integers are full objects in Python, and small integers are always shared, not only when copying.

The tests are run with pytest-xdist, with up to 16 threads (workers have different numbers of cores).

**Comment by StefanBruens** [comment]
Some more data points:
- with 8 workers or less, I have not seen this problem
- happens with both openblas-openmp and netlib blas.

**Comment by rgommers** [comment]
Seen on conda-forge as well: https://github.com/conda-forge/numpy-feedstock/pull/225

**Comment by seberg** [comment]
Is there some race condition in NumPy or is it just that small integers are shared and their reference count can be affected by a different thread somewhere? (I assume it is the latter, 1.20 did include a bug fix for a similar race-condition though, so happy to be corrected.)

If its just the small integers, we probably should skip the `zero` and use some unique integer instead of the `ones`.
