### ISSUE TITLE
Import error with a compiled python version with valgrind options

### ISSUE THREAD

**Issue by dmidge8** [numpy/numpy#17387]
With python 3.7.7, there are some optional compilations flags that enable some tooling to better use valgrind. It is advised in the python readme to define `--without-pymalloc --with-pydebug --with-valgrind` during the compilation. A stackoverflow page explains how it is supposed to be working: https://stackoverflow.com/questions/20112989/how-to-use-valgrind-with-python.
Doing so however prevents to use numpy v.18.1 and all libraries that depends on it (such as `hashlib` that is used to verify some packages).

This bugs is partially explained in this two locations:
- https://stackoverflow.com/questions/64049417/compiled-python-version-modulenotfounderror-at-import#64084387 (Failing to import some modules)
- https://github.com/numpy/numpy/issues/11558 (Similar issue on this bug tracker but that I can't reopen).

### Reproducing code example:

Compile python3.7 
```
$ ./configure --prefix=/tmp/python3.7     --enable-ipv6     --with-ensurepip=no     --with-computed-gotos     --with-system-ffi     --enable-loadable-sqlite-extensions     --with-lto --without-pymalloc --with-pydebug --with-valgrind
$ make
```
Then try to use numpy with the compiled version of python
```
$python3.7
> import numpy as np
```
Then, two situation occurs. Either:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```
Or
```
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/home/educroc/.conda/envs/rlautoplan/bin/python3.7",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by charris** [comment]
Did you also install numpy with the compiled python?

**Comment by seberg** [comment]
I am not sure if you may have to recompile when using `--with-pydebug` (possibly not on linux but on windows). I can import the normal numpy using `python3.8d` on debian, but I am not sure there is much of a point? Debug build has to modify macros like `Py_INCREF`, I think.

In any case, if all you want is run valgrind, I suggest you do not do anything, and instead use `PYTHONMALLOC=malloc`. I am not sure what exactly `--with-valgrind` does, but from what I have seen the main thing is probably also just modifying `malloc`. There may be some smaller things it changes, but I do not think it is much and likely mostly relevant if you are testing python itself.

**Comment by seberg** [comment]
Old installation issue/question, closing.
