### ISSUE TITLE
basic array operators are hard to find in the docs

### ISSUE THREAD

**Issue by drevicko** [numpy/numpy#17384]
## Documentation

Documentation on [basic operations](https://numpy.org/doc/stable/user/quickstart.html#basic-operations) is hard to find. It would be very useful if associated operators were mentioned in the documentation of method equivalents. 

For example, element-wise logical operations such as `np.logical_or(a, b)` have an operator equivalent `a | b`. The operational form, however, is not mentioned in the [`np.logical_or`](https://numpy.org/doc/stable/reference/generated/numpy.logical_or.html) documentation nor in the [summary page](https://numpy.org/doc/stable/reference/routines.logic.html) of logic functions. In fact, I've searched for it in numpy documentation a number of times over the years, and always have difficulty finding it.

**Comment by shoyer** [comment]
I agree, this would be a welcome improvement.

You can find one such list in an appendix to NEP 13:
https://numpy.org/neps/nep-0013-ufunc-overrides.html#list-of-operators-and-numpy-ufuncs

**Comment by Rashmi-K-A** [comment]
Hi, I would love to tackle this one, can I take this?

**Comment by mattip** [comment]
@Rashmi-K-A welcome. We don't assign issues, anyone is welcome to submit a PR. When you submit a PR, please reference this issue with something like `xref gh-17384`.With that, you will want to read [Contributing to NumPy](https://numpy.org/devdocs/dev/index.html) and the [NumPy’s Documentation](https://numpy.org/devdocs/docs/index.html) guide. Feel free to reach out if something doesn't make sense.

**Comment by Riya-11** [comment]
Hi, is this issue being already worked upon? If not, I would love to contribute! Thanks :)

**Comment by Rashmi-K-A** [comment]
Hey @Riya-11, I have already started working on this!

**Comment by ayushgharat234** [comment]
Is someone already working on this issue, because I have my content to add for this or we can collaborate together
