### ISSUE TITLE
Newer versions of pytest are failing because of multiple hypothesis imports.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17390]
The CI tests fail for newer pytest on account of a pytest warning, see https://travis-ci.org/github/numpy/numpy/jobs/730868650 and https://github.com/pytest-dev/pytest/issues/7810. If I comment out hypothesis related code in `numpy/_pytesttester.py` the warning goes away. The other place hypothesis is imported is `numpy/configtest.py`. I seems we need to get rid of one of the imports.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by charris** [comment]
@Zac-HD Thoughts?

**Comment by Zac-HD** [comment]
The reason we have this configuration split over two places is, per #16879, that we want `numpy.test()` to be deterministic, but running the tests in development mode to be randomised and save failing examples.

Given this issue, the "right way to do that" is probably to move *all* the config into `conftest.py`, and then decide which settings profile to load based on whether or not we're running via `numpy.test()`.  I don't know how to detect that, but happy to write the PR to do everything else - and include that if someone can advise me.

**Comment by mattip** [comment]
I think moving all the config into one place is desirable.

"running the tests in development mode" [imports](https://github.com/numpy/numpy/blob/v1.19.2/runtests.py#L283) and [runs](https://github.com/numpy/numpy/blob/v1.19.2/runtests.py#L309) `numpy.test()`. The only way I can think of to do what you ask is to add an extra argument to the call to set the mode: either deterministic or development. I am not so good with names: whether to have `deterministc` flag that defaults to True and is set to False in `runtests.py` or a `development` flag that defaults to False and is set True in `runtests.py`

**Comment by charris** [comment]
IIRC, we now detect "development" by the presence of `pytest.ini`.

**Comment by mattip** [comment]
@Zac-HD any progress on that PR?

**Comment by Zac-HD** [comment]
Apologies for the delay; it's been bumped to the top of my OSS todo list and I expect to have something up over the weekend :slightly_smiling_face:
