### ISSUE TITLE
dtype control for corrcoef

### ISSUE THREAD

**Issue by orenbenkiki** [numpy/numpy#17395]
## Feature

I am computing a cross-correlation matrix of 150K * 150K matrix of float32.

Numpy insists on making the results dtype be float64. This causes the amount of memory to be "too much".

I would debate that default, but changing it would probably be too disruptive (not backward compatible).

However, how about a dtype parameter for corrcoef?

In general I would have liked to see a dtype parameter "everywhere" to override the float64 default...

**Comment by lschwetlick** [comment]
Looks like corrcoef relies on  [cov](https://github.com/numpy/numpy/blob/73157efcd17da95ce984d1595ac4907233b9dbf5/numpy/lib/function_base.py#L2619) in which deliberately  [casts to float64](https://github.com/numpy/numpy/blob/73157efcd17da95ce984d1595ac4907233b9dbf5/numpy/lib/function_base.py#L2404).

I made an experimental PR for this, and it seems to work without much of a hitch.

[This is my first PR to numpy so I'm happy to get any feedback you might have!]

**Comment by orenbenkiki** [comment]
Wow, thanks!
