### ISSUE TITLE
DOC: Duplicate "Code of Conduct" pages

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#17415]
We have two Code of Conduct pages:

* [In the Sphinx pages](https://numpy.org/devdocs/dev/conduct/code_of_conduct.html#diversity-statement)
* [In the Hugo pages](https://numpy.org/code-of-conduct/)

Should the Sphinx version be removed?

**Comment by rgommers** [comment]
Yes, good catch, this was still a TODO. We should prefer the Hugo version indeed, and get rid of the Sphinx one.
