### ISSUE TITLE
DOC: Multiple diversity pages

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#17414]
We have two pages labeled "diversity statement":

* The new one: [NumPy diversity and inclusion statement](https://numpy.org/diversity_sep2020/) 

* The one in the Code of Conduct: [Diversity Statement](https://numpy.org/devdocs/dev/conduct/code_of_conduct.html#diversity-statement)

Neither mentions the other.  
* Should the new statement have at least a link to the CoC diversity statement?
* Should the new statement say "September 2020" in the title to indicate that it's issued at a particular point in time in response to events (unlike the CoC),  and will be updated? 
> # NumPy diversity and inclusion statement: September 2020

**Comment by bjnath** [comment]
Just realized we have two copies of the CoC itself -- the [Sphinx page](https://numpy.org/devdocs/dev/conduct/code_of_conduct.html#diversity-statement) referenced above and [one in the Hugo pages](https://numpy.org/code-of-conduct/).

Since this issue doesn't involve changing the CoC, I'll make a separate issue about the duplication.

**Comment by melissawm** [comment]
Regarding the statement from September 2020, I believe that page won't change. The two diversity statements serve different purposes. I would suggest closing this and leaving things as they are.

**Comment by rgommers** [comment]
Yes I agree, let's not change anything here. I gave @bjnath some more context on Slack. Thanks for bringing this up and fixing the CoC duplication @bjnath. Closing.
