### ISSUE TITLE
DOC: Move "security vulnerability" to top of issues menu

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#17434]
"Report a security vulnerability" needs to be the first Issues menu item. It's ineffective where it is. Nobody will read past "Bug Report."

![image](https://user-images.githubusercontent.com/6691888/94994602-a3edb600-0566-11eb-80fd-e1414fad8a20.png)

"Bug report" becomes the second item. People without security issues will find it immediately.

(Also: "Bug report" and "Feature request" headings should not capitalize "report" and "request").

**Comment by eric-wieser** [comment]
This is out of our control, that link is added automatically by github

**Comment by charris** [comment]
Shouldn't security vulnerabilities be privately communicated?

**Comment by bjnath** [comment]
@eric-wieser 

Does github control all the placement -- including the order of the `Get started` items themselves (I see they're alphabetical)? 

If we control the `Get started` ordering we could change security to a `Get started` item.

But adding a security proviso to the bug-report tag seems worthwhile either way; I'll try it.

@charris 
> Shouldn't security vulnerabilities be privately communicated?

That's the idea -- we don't want people with security vulnerabilities making bug reports, so we hope to grab their attention before they try.

**Comment by bjnath** [comment]
@eric-wieser  No need to respond to earlier comment; I see how it works.

**Comment by eric-wieser** [comment]
> Shouldn't security vulnerabilities be privately communicated?

@charris, the "view policy link" opens our tidelift document that explains exactly that :)
