### ISSUE TITLE
Non-unique indexing wont broadcast multiple times

### ISSUE THREAD

**Issue by holymonson** [numpy/numpy#17441]
### Reproducing code example:

```python
import numpy as np
a = np.arange(3)
a[[1, 2, 2]] += 100
```
Result: 
```python
>>> a
array([ 0, 101, 102])
```
Expect:
```python
>>> a
array([ 0, 101, 202])
```

Index `2` is non-unique, it should broadcast to `+=` multiple times. But now `a[[1, 2, 2]] += 100` is no different from `a[[1, 2]] += 100`.

### NumPy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.19.1 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:18:42)
[Clang 10.0.1 ]
```

**Comment by rossbar** [comment]
Note that `a[[1, 2, 2]]` is an instance of [advanced indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing) which results in copies of the original array, so the original operation `a[[1, 2, 2]] += 100` translates to\*:

```python
tmp = a[[1, 2, 2]]
a[[1, 2, 2]] = tmp + 100
```

To get the behavior you were expecting, try checking out the [ufunc `at` method](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.at.html#numpy.ufunc.at).

Hopefully this is sufficient to answer your question - if not, please feel free to follow up.

\* Thanks @seberg for the explanation
