### ISSUE TITLE
squaring of integers in arrays may give negative values.

### ISSUE THREAD

**Issue by AdityaSavara** [numpy/numpy#17452]
squaring of integers in arrays may give negative values.
### Reproducing code example:

This works fine:
`np.array([300000.0])**2`
This does not:
`np.array([300000])**2`
This does not:
`np.square(np.array([300000]))`

The latter two give negative numbers out. This happened as part of a larger array and gave me really confusing errors that were hard to track down. It happens with 300000, but not with 400000. So it's not all integers of this size.

```python
import numpy as np
np.square(np.array([300000]))
```

### NumPy/Python version information:

1.16.4 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]

**Comment by AdityaSavara** [comment]
I tried elsewhere with no problem: 1.17.3 3.8.0 (default, Nov 14 2019, 22:29:45) 

But tried again after updating numpy on this computer:
1.18.1 3.7.1 (default, Nov 24 2018, 22:14:32) [MSC v.1912 64 bit (AMD64)]

So it's not my version of numpy that's the problem.

**Comment by eric-wieser** [comment]
If you're seeing different results in different places, chances are one is using `np.int32` (windows), and the other is using `np.int64` (linux). Either way, overflow is expected - if you want arbitrary precision integers, use `dtype=object`.

**Comment by AdityaSavara** [comment]
Sorry, I think you are right. I had made a mistake in my comparison to the max value of int32. These are in fact above that. I am closing the issue.
