### ISSUE TITLE
DOC: HTTP 404 on Code of Conduct URL

### ISSUE THREAD

**Issue by stuartarchibald** [numpy/numpy#17458]
## Documentation

Not sure where to file this. The github template for the Code Of Conduct https://github.com/numpy/numpy/blob/master/.github/CODE_OF_CONDUCT.md (https://github.com/numpy/numpy/blame/master/.github/CODE_OF_CONDUCT.md#L1) refers to an address that 404s, namely
https://www.numpy.org/devdocs/dev/conduct/code_of_conduct.html, not sure if this an issue with the URL or the place to which it points.

**Comment by mattip** [comment]
Thanks. That should be https://numpy.org/code-of-conduct/. PR welcome.

**Comment by stuartarchibald** [comment]
> Thanks. That should be https://numpy.org/code-of-conduct/. PR welcome.

Thanks, done in #17459
