### ISSUE TITLE
squaring of integers in arrays may give negative values.

### ISSUE THREAD

**Issue by AdityaSavara** [numpy/numpy#17451]
squaring of integers in arrays may give negative values.
### Reproducing code example:

This works fine:
`np.array([300000.0])**2`
This does not:
`np.array([300000])**2`
This does not:
`np.square(np.array([300000]))`

The latter two give negative numbers out. This happened as part of a larger array and gave me really confusing errors that were hard to track down.
```python
import numpy as np
`np.square(np.array([300000]))`
```

### NumPy/Python version information:

1.16.4 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]

**Comment by AdityaSavara** [comment]
The issue got posted twice. I am closing this one and leaving the other open.

**Comment by charris** [comment]
Expected. Integer arithmetic is modular arithmetic and we don't check for overflow.
