### ISSUE TITLE
Problem in random.normal

### ISSUE THREAD

**Issue by zorawar12** [numpy/numpy#17469]
I generated 10 random numbers from a normal distribution, in two different versions of Numpy(1.17 and 1.15)

Then randomly I pick a number and check if it is the maximum out of 10.

I do it using two different ways in both the versions, out of which 1 version(1.15) gives same result in both ways whereas another version(1.17) gives different results in both ways.

method 1:
generate 10 numbers, pick one in random, check if matches with the maximum
method 2:
generate 10 numbers, sort it, pick one in random, check if matches with the maximum

picking in random is done through a voting method(which is complex to provide here).

can you please tell me the differences in both the versions of random.normal function?

if you are interested to go through the entire code, please visit https://github.com/zorawar12/yes_no_units/blob/master/src/

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by rgommers** [comment]
No follow-up for >6 months and this is not actionable, so I'll close the issue. The question about possible changes in `random.normal` were answered.
