### ISSUE TITLE
Core: Convolve and Correlate mode check in core/numeric.py

### ISSUE THREAD

**Issue by aitikgupta** [numpy/numpy#17476]
### Reproducing code example:

```python
import numpy as np
y = np.convolve(np.ones(1,), np.ones((1,))/1, mode='random_mode')
```

### Error message:
    637 def _mode_from_name(mode):                                  <--- numpy/core/numeric.py
    638     if isinstance(mode, basestring):
    639         return _mode_from_name_dict[mode.lower()[0]]            
    640     return mode
    
    KeyError: 'r'

### NumPy/Python version information:

1.18.5 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]

### Discussion:
Current modes for numpy.convolve, and numpy.correlate are 'valid', 'same' or 'full'. If there is any other string provided it raises a KeyError with the first letter.
**In fact,**
```python
import numpy as np
y = np.convolve(np.ones(1,), np.ones((1,))/1, mode='very_random_mode')
```
**Does NOT raise an error. As it is simply mistaken for 'valid'** (the very first character is checked)
Think there should be a check here:
https://github.com/numpy/numpy/blob/2eed8784d5946e420500bf87f9af305d87aaa055/numpy/core/numeric.py#L670 which makes sure the mode is in fact, corresponding to (modified?) keys of https://github.com/numpy/numpy/blob/2eed8784d5946e420500bf87f9af305d87aaa055/numpy/core/numeric.py#L665-L667

**Comment by aitikgupta** [comment]
If the issue is valid, I'll create a PR once I run the tests locally. 👍🏼

**Comment by eric-wieser** [comment]
This seems like a sensible change to me - we already did something similar for other string arguments elsewhere in numpy (eg `mode='clip'`). We should find what we did in that PR and do the same (ie, did we immediately error, or emit a deprecation warning?)

**Comment by aitikgupta** [comment]
> This seems like a sensible change to me - we already did something similar for other string arguments elsewhere in numpy (eg `mode='clip'`). We should find what we did in that PR and do the same (ie, did we immediately error, or emit a deprecation warning?)

Took me some time, but do you mean https://github.com/numpy/numpy/pull/16056?
It emits a deprecation warning if inexact modes are present. Ref:
https://github.com/numpy/numpy/blob/9e37e585cc86ff6dc821d0566baacc137cb16343/numpy/core/src/multiarray/conversion_utils.c#L625-L632
We can do a similar thing here: https://github.com/numpy/numpy/blob/2eed8784d5946e420500bf87f9af305d87aaa055/numpy/core/numeric.py#L665-L673

**Comment by eric-wieser** [comment]
Thanks for finding that - yes, that is the one I mean, nice job.
