### ISSUE TITLE
CPython 3.9 wheels

### ISSUE THREAD

**Issue by hroncok** [numpy/numpy#17482]
Hello. Could you please release CPython 3.9 manylinux wheels on PyPI?

Python 3.9.0 final was released this week: https://www.python.org/downloads/release/python-390/

Thank You.

**Comment by mattip** [comment]
xref MacPython/numpy-wheels#101. When that PR passes, we can begin the process of uploading wheels. We are waiting for Azure to support python 3.9, see this issue actions/virtual-environments#1740. According to [this comment](https://github.com/actions/virtual-environments/issues/1740#issuecomment-704287158) that should be solved soon but not before next week. 

If someone wishes to help, they could try to do a PR to move the wheel building from Azure to github actions, which is more flexible.

**Comment by mattip** [comment]
Changing the title to reflect the idea that we will release 39. wheels for all architectures together.

**Comment by Luttik** [comment]
Would it be possible to use an alternative for azure to build the numpy official wheels? For me, numpy is always the blocking library when new python versions release.

**Comment by matthew-brett** [comment]
Is there any way of installing the latest Python on Azure?  That's what we were doing on Appveyor - installing the binaries from Python.org as soon as they were released.

**Comment by charris** [comment]
> Is there any way of installing the latest Python on Azure?

Yes, and Github actions can do it now. We have also been releasing manylinux2010 Python 3.9 nightly wheels for a while. However, I expect the cached versions of Python 3.9 to be available in a day or two which will take care of Mac and Windows wheels, and I'd also like to get a fix for the Windows 2004 fmod problem as well, although that may have to wait. I expect next time things will move much faster on Azure, the Azure team is aware that they need to be better prepared for the next Python release.

**Comment by hugovk** [comment]
Everyone give this an upvote for Azure Pipelines to have on-demand Python, like GitHub Actions does:

* https://github.com/microsoft/azure-pipelines-tasks/issues/13319

(re: https://github.com/actions/virtual-environments/issues/1740#issuecomment-705363333)

**Comment by matthew-brett** [comment]
I would only say - it would be worth considering what to do if Azure does not speed up this process for next time.   Previous discussions I've seen from Microsoft folks has implied that they are not as invested in wheels as many of us are - not surprisingly - and so it's possible this may not be high up their priority list.

**Comment by charris** [comment]
> this may not be high up their priority list

I have the impression that they are also considering making some of the development versions available, which would be helpful. We will see.

**Comment by takluyver** [comment]
It appears the images on Azure have Python 3.9 now.

**Comment by jpivarski** [comment]
Is there a PR, a progress bar, or something I can watch to estimate when this will be done? My project depends on NumPy and I want to know how to schedule my own work. Thanks!

**Comment by effigies** [comment]
FWIW, I've just subscribed to this issue.

Nightly wheels are being built, so if you're comfortable using prereleases for testing, you can get your CI set up using those for now: https://anaconda.org/scipy-wheels-nightly/numpy/files

**Comment by cclauss** [comment]
https://github.com/numpy/numpy/releases/tag/v1.19.3 should close this issue.

**Comment by hroncok** [comment]
Thanks to everybody who made the wheels happen.
