### ISSUE TITLE
Deduplicate dtype documentation

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#17486]
## Documentation

We still have a fair bit of overlap between these two pages:

* `user/basics.types.rst`: https://numpy.org/devdocs/user/basics.types.html - table of scalar type and type aliases
* `reference/arrays.scalars.rst`: https://numpy.org/devdocs/reference/arrays.scalars.html - autodoc listings of scalar types and type aliases

It's tempting to remove the table on the first page, and tell users to look at the docs on the second.

If nothing else, it would be good to describe to the reader how the pages relate to each other - right now the former links to the latter only via the (currently broken) class names. A "see also" link somewhere would make the connection a little easier to understand.

**Comment by tech-gian** [comment]
Hello!
I would like to help closing this issue. I have a question.
Do you want to fully remove the 2 tables from the first page and replace them with some text that describes the types in general and provides link to the types of the second page,

 or you want to replace the description from each element in the table with a link to corresponding type in the second page and add somewhere some text to describe how the pages related, with "see also" link?

**Comment by eric-wieser** [comment]
I don't really know what exactly I want here - part of the goal of opening this issue was to get some discussion about how to unify the pages a bit.

> or you want to replace the description from each element in the table with a link to corresponding type in the second page

As of not very long ago, the left column of the table _is_ a link to the second page.

**Comment by tech-gian** [comment]
> As of not very long ago, the left column of the table _is_ a link to the second page.
I didn't noticed that, by my mistake.
Well, I think that the first table is very useful and it should stay in the page. The second one could be replaced with a short text (no longer than 3 paragraphs) that describes how someone could find the aliases types in the second page, giving him the corresponding links and some tips to not get lost in the second page.

**Comment by tech-gian** [comment]
@mattip Thank you very much for these basic changes in the PR linked with issue and title! It's one of my first PR.
