### ISSUE TITLE
Condition comparing incompatible types in "numpy.lib.utils.info"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [numpy/numpy#17490]
Hello,

While analyzing numpy on SonarCloud I saw what looks like an error in [`numpy/lib/utils.py`](https://github.com/numpy/numpy/blob/a699f2879ab3836fe6d1619c518c85956a3075c1/numpy/lib/utils.py#L589-L590):

<img width="1587" alt="Screenshot 2020-10-07 at 15 16 54" src="https://user-images.githubusercontent.com/40498978/95335860-2dc3b900-08b0-11eb-9410-61b80acce587.png">

You can see the issue in SonarCloud [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_numpy&issues=AXUCzxpM_fo4ewk0XFBT&open=AXUCzxpM_fo4ewk0XFBT).

The condition of this `if` statement will always be True because it compares a `dict` and a `list` with the operator `!=`. The [code of `pydoc.allmethods`](https://github.com/python/cpython/blob/044a1048ca93d466965afc027b91a5a9eb9ce23c/Lib/pydoc.py#L247) clearly shows that it will always return a `dict`.

I guess the developer intended to write instead:
```
if methods != {}:
```

In case you have any question, suggestion or if you see a False Positive on SonarCloud you can reach out on [SonarSource community forum](https://community.sonarsource.com/).

A few notes in case you want to use SonarCloud:
* I am currently testing the python analyzer so [the numpy project I created on SonarCloud](https://sonarcloud.io/dashboard?id=nicolas-harraudeau-sonarsource_numpy) will only show python issues, but SonarCloud can also analyze C/C++ code and other languages.
* SonarCloud can easily import pylint and flake8 issues in case you want to use a rule SonarCloud does not already provide. Note however that pylint/flake8 rules and SonarCloud rules are implemented differently. You might see new issues with SonarCloud, or less issues in some cases (we try to avoid False Positives as much as possible).
* SonarCloud is free for open-source projects.

**Comment by eric-wieser** [comment]
Thanks for the report. This looks valid, but the only effect is that in the `np.info` function which is probably rarely used, a `Methods:` heading is printed even if there is no content to print.

A patch would be welcome nonetheless.

**Comment by stevejoachim** [comment]
Hey All, I just submitted a PR for this. I know it's a pretty tiny fix, but I love numpy and was looking for a way to get my feet wet with open source. This is my first PR ever!

**Comment by stevejoachim** [comment]
Tried following all the contributing guidelines, but please let me know if I went wrong anywhere.

**Comment by nicolas-harraudeau-sonarsource** [comment]
Hi @eric-wieser,

Excuse me if this is not the right channel for this kind of announcement. I don't know if NumPy mailing list is for NumPy developers or NumPy users.

About two weeks ago I reported [a few bugs](https://github.com/numpy/numpy/issues?q=is%3Aissue+author%3Anicolas-harraudeau-sonarsource+) found in the NumPy repository. This effort was part of a bigger SonarSource Bug Report Campaign. We found some interesting issues in different high-quality projects and we plan to share this result with developers at large **[in this blog post](https://docs.google.com/document/d/1xUPnMO78OoED5MGf65d6GW2tb4td2pmjvgTPBlNfFNE/edit?usp=sharing)**. Please reach out by the 30th of October if you see anything bothering you.

Kind regards,
 
Nicolas

**Comment by eric-wieser** [comment]
I don't see anything to bother me there. It only draws attention to #17489, and that's not a security vulnerability and already publically visible anyway. Perhaps @rgommers has an opinion.

**Comment by rgommers** [comment]
Seems fine to me too. Thanks for asking @nicolas-harraudeau-sonarsource

**Comment by nicolas-harraudeau-sonarsource** [comment]
Thank you for your rapid and positive answers @eric-wieser @rgommers!
