### ISSUE TITLE
DOC: 'Governance' in Sphinx pages: delete/move/keep?

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#17496]
There are overlaps between the  [governance section](https://numpy.org/devdocs/dev/governance/index.html) in the Sphinx pages and [About us](https://numpy.org/about/) in the Hugo pages. But they're not identical.

What should be done about the Sphinx pages? Remove them, merge them into Hugo (as new pages?), leave them alone?

**Comment by tech-gian** [comment]
Hello!
I think that a good idea is to delete this page: https://numpy.org/devdocs/dev/governance/people.html
and to change the links from the governance section to link to the corresponding "sections" in the About us page.
