### ISSUE TITLE
TypeError due to bad string formatting in "Template.substitute"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [numpy/numpy#17491]
Hello,

While analyzing numpy on SonarCloud I saw what looks like an error in [`tools/npy_tempita/__init__.py`](https://github.com/numpy/numpy/blob/388e8197e15403345950edc23ae5fc7a3cb0f644/tools/npy_tempita/__init__.py#L180-L182):

<img width="1596" alt="Screenshot 2020-10-07 at 15 49 11" src="https://user-images.githubusercontent.com/40498978/95339836-ca885580-08b4-11eb-98d3-312962128792.png">

You can see the issue in SonarCloud [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_numpy&issues=AXUCzx_s_fo4ewk0XFHQ&open=AXUCzx_s_fo4ewk0XFHQ).

The code tries to raise a TypeError and ends up raising another one ;)
It looks like the developer transformed a string into a tuple by mistake. Calling the operator `%` on two tuples will raise the exception:
```
TypeError: unsupported operand type(s) for %: 'tuple' and 'tuple'
```

The code could also be simplified a bit as follow:
```
raise TypeError(
    "If you pass in a single argument, you must pass in a "
    "dict-like object (with a .items() method); you gave %r"
     % args[0])
```

In case you have any question, suggestion or if you see a False Positive on SonarCloud you can reach out on [SonarSource community forum](https://community.sonarsource.com/).

A few notes in case you want to use SonarCloud:
* I am currently testing the python analyzer so [the numpy project I created on SonarCloud](https://sonarcloud.io/dashboard?id=nicolas-harraudeau-sonarsource_numpy) will only show python issues, but SonarCloud can also analyze C/C++ code and other languages.
* SonarCloud can easily import pylint and flake8 issues in case you want to use a rule SonarCloud does not already provide. Note however that pylint/flake8 rules and SonarCloud rules are implemented differently. You might see new issues with SonarCloud, or less issues in some cases (we try to avoid False Positives as much as possible).
* SonarCloud is free for open-source projects.

**Comment by eric-wieser** [comment]
`npy_tempita` is vendored code, so we're unlikely to do anything about this.

**Comment by nicolas-harraudeau-sonarsource** [comment]
@eric-wieser Thanks for investigating this and sorry for noise.

**Comment by rgommers** [comment]
Agreed, closing. Thanks for the report @nicolas-harraudeau-sonarsource
