### ISSUE TITLE
DOC: Missing site table of contents

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#17494]
We've lost the site table of contents with the new pydata theme.

[contents.html](https://numpy.org/doc/1.19/contents.html) in our last stable release:
![image](https://user-images.githubusercontent.com/6691888/95370729-3e236600-08a7-11eb-97eb-1db44d075265.png)

[contents.html](https://numpy.org/devdocs/contents.html) in devdocs:
![image](https://user-images.githubusercontent.com/6691888/95371004-9bb7b280-08a7-11eb-830a-f6ce53e1c383.png)

The table of contents is a big help in navigating a site as large and tangled as this one --  possibly even more valuable for the NumPy team than for outside users, as we reorganize the pages.

Any way to get it back?

**Comment by eric-wieser** [comment]
Remove `:maxdepth: 1`?

**Comment by bjnath** [comment]
@eric-wieser  Thanks!
