### ISSUE TITLE
ENH: Mark all constants as `Final`

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#17507]
A number of constants are present in the main numpy namespace, however their annotations 
are currently not marked as such.

TODO
------
- [ ] Mark constants (see below) with [`typing.Final`](https://docs.python.org/3/library/typing.html#typing.Final). For example, `Inf: float` should become `Inf: Final[float]`. 
Note that `Final` was introduced to the builtin `typing` module in python 3.8; for older versions it'll have to be imported from `typing_extensions`.

https://github.com/numpy/numpy/blob/29c58e632ce51e75e946014f076aba803ee57dde/numpy/__init__.pyi#L1600-L1641

**Comment by lucasace** [comment]
Could I take this up?

**Comment by BvB93** [comment]
Sure, feel free to go ahead.
