### ISSUE TITLE
DOC: Polynomial module

### ISSUE THREAD

**Issue by Mandroide** [numpy/numpy#17513]
## Documentation
When you search polynomial [here](https://numpy.org/doc/stable/search.html?q=polynomial&check_keywords=yes&area=default), the first line says: numpy.polynomial (Python module, in **_\<no title\>_**) in comparison with the [development version](https://numpy.org/devdocs/search.html?q=polynomial).

Also, I believe that [this page](https://numpy.org/doc/stable/reference/routines.polynomials.package.html) is missing valuable information in comparison with the [development one](https://numpy.org/devdocs/reference/routines.polynomials.package.html)

When I read the [stable one](https://numpy.org/doc/stable/reference/routines.polynomials.classes.html), I thought it was a mistake when the examples skipped a submodule.

**Comment by rossbar** [comment]
Yes, the polynomial package documentation has seen some recent changes which are visible in the devdocs but not yet in `stable`, which comes from numpy 1.19. The changes that you see for the devdocs will be reflected in `stable` when a new version of numpy is released. In the meantime, I would recommend using the [latest polynomial documentation](https://numpy.org/devdocs/reference/routines.polynomials.html)

**Comment by melissawm** [comment]
It looks like this can be closed - if the newest polynomial documentation is still not sufficient, feel free to re-open.
