### ISSUE TITLE
DOC: License has 2005 copyright date

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#17519]
The first line of the [license page](https://numpy.org/devdocs/license.html) is 

> Copyright (c) 2005, NumPy Developers

Is the date OK, or should it be `2005-2020`, similar to the page footers?

Also, the page footers list a different copyright holder:

> © Copyright 2008-2020, The SciPy community

Also OK?

**Comment by rgommers** [comment]
That page is some copy floating around, `LICENSE.txt` in the root dir of the repo is the authoritative copy and says:
```
Copyright (c) 2005-2020, NumPy Developers.
```
