### ISSUE TITLE
Mac OSX installer sets file owner to UID 501 regardless of installing user's UID (Trac #1155)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1753]
_Original ticket http://projects.scipy.org/numpy/ticket/1155 on 2009-06-30 by trac user gorm, assigned to @rgommers._

It appears that the mac OSX installers (.dmg) sets the file ownership of all installed files to UID 501 regardless of the actual UID of the installing user. (I have a UID different from 501 due to NFS-related issues). I suspect the correct behavior would be to set the owner to be the user actually running the installer.

**Comment by mattip** [comment]
@matthew-brett can we close this?

**Comment by matthew-brett** [comment]
We gave up on the mpkg installler a long time ago, so yes, let's close this one.
