### ISSUE TITLE
Change the ALLOW_THREADS and BUFSIZE variables used by numpy.

### ISSUE THREAD

**Issue by hongyi-zhao** [numpy/numpy#17531]
Hi,

On Ubuntu 20.04 with python 3.8.3 managed by pyenv, I try to run [the mu.py script](https://notebook.rcc.uchicago.edu/files/acs.chemmater.9b05047/Data/bulk/dft/mu.py) with numpy. The [dateset](https://notebook.rcc.uchicago.edu/files/acs.chemmater.9b05047/Data/bulk/dft/dos/BiVO4.dos-202018-sm003) manipulated by it is rather huge. So I want to use the parallelization processing power of numpy with the following settings: 
```
import os
os.environ["ALLOW_THREADS"] = "20"
os.environ["BUFSIZE"] = "8192000"
```

But when I debug the script, I find that the values for the above variables are not changed accordingly, see the following for the real values observed for my case:

```
ALLOW_THREADS   1
BUFSIZE                  8192
```

OTOH, I also find that the script will keep running and never end. When I press 'Ctrl + c', it will give the following output: 

```
$ python mu.py
[-10.999 -10.999 -10.999 ...  20.     20.     20.   ] [4.973e-84
4.973e-84 4.973e-84 ... 4.973e-84 4.973e-84 4.973e-84]

I have to terminate it and obtained the following information:

^CTraceback (most recent call last):
  File "mu.py", line 38, in <module>
    integrand=DOS*fermi_array(energy,mu,kT)
  File "/home/werner/.pyenv/versions/datasci/lib/python3.8/site-packages/numpy/lib/function_base.py",
line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/werner/.pyenv/versions/datasci/lib/python3.8/site-packages/numpy/lib/function_base.py",
line 2192, in _vectorize_call
    outputs = ufunc(*inputs)
  File "mu.py", line 8, in fermi
    return 1./(exp((E-mu)/kT)+1)
KeyboardInterrupt
```
Any helps and hints for this problem will be highly appreciated?

Regards,
HY

**Comment by seberg** [comment]
Neither of these are environment variables which are settable, and ALLOW_THREADS doesn't set the number of threads.

1. If you would like threading, you can do manual threading or find tools that do use threading. NumPy allows you to use multiple cores and threading, but it doesn't employ it typically. `ALLOW_THREADS` exists, but it is a compile time variable which is boolean (true or false) and I am sure it is already True.
2. `BUFSIZE` can be changed for individual calls and there is a `np.setbufsize` command. But increasing the buffer size is unlikely to help you much. Increasing it as much as you are trying here is almost guaranteed to make performance worse. Buffers have to be small (size depends on the CPU, but lets say around 1MB may be a likely useful maximum).

What you really want to be doing is to *not* use `np.vectorize`. That function does not speed up code, you have to use NumPy array operations.

**Comment by hongyi-zhao** [comment]
> Neither of these are environment variables which are settable, and ALLOW_THREADS doesn't set the number of threads.
> 
>     1. If you would like threading, you can do manual threading or find tools that do use threading. NumPy allows you to use multiple cores and threading, but it doesn't employ it typically. `ALLOW_THREADS` exists, but it is a compile time variable which is boolean (true or false) and I am sure it is already True.
> 
>     2. `BUFSIZE` can be changed for individual calls and there is a `np.setbufsize` command. But increasing the buffer size is unlikely to help you much. Increasing it as much as you are trying here is almost guaranteed to make performance worse. Buffers have to be small (size depends on the CPU, but lets say around 1MB may be a likely useful maximum).

Do you mean this variable can be set with a larger value for CPU which has larger bufsize, and vice versa?

> 
> 
> What you really want to be doing is to _not_ use `np.vectorize`. That function does not speed up code, you have to use NumPy array operations.

Then, when should I use *np.vectorize*?

**Comment by seberg** [comment]
`np.vectorize` turns non-array aware functions into array-aware functions.  All functions you are using already seem already array aware, so they already operate on the full array.  `np.vectorize` does not speed anything up, when it is unnecessary it will be a *huge* slowdown.

You can change the buffer size, but I am absolutely certain that is spending effort on a worthless optimization here.  The problem is that you are not using array functions (functions that operate on a full array) as intended in pure NumPy (projects like numba are different).
What you should rather do is learn about how to "vectorize"/make sure your functions operate on full NumPy arrays.

**Comment by hongyi-zhao** [comment]
> `np.vectorize` turns non-array aware functions into array-aware functions. All functions you are using already seem already array aware, so they already operate on the full array. `np.vectorize` does not speed anything up, when it is unnecessary it will be a _huge_ slowdown.
> 
> You can change the buffer size, but I am absolutely certain that is spending effort on a worthless optimization here. The problem is that you are not using array functions (functions that operate on a full array) as intended in pure NumPy (projects like numba are different).

You first say "so they already operate on the full array", and then say, "you are not using array functions (functions that operate on a full array)". It seems your presentation is inconsistency. Maybe I misunderstand you. Any more hints?

> What you should rather do is learn about how to "vectorize"/make sure your functions operate on full NumPy arrays.

**Comment by seberg** [comment]
Honestly, I think you had similar and more answers on the mailing list. I do not think it makes sense to repeat this here when the mailing list is the better place to ask to begin with.
