### ISSUE TITLE
Numpy linalg.eigh not working on windows 10 

### ISSUE THREAD

**Issue by Chunde** [numpy/numpy#17543]
I tried to solve the eigenvalues and eigenvectors of a Hermitian matrix, the code used to work nicely and still works in Cocalc, but not on my windows 10 (the system got some updates) now, and the error is very confusing, I can not figure out what is happening now, maybe someone also has a similar issue.

Python version: 3.7.2
NumPy version: 1.16
windows version:  Windows Pro 19041.508
Intel: i7-3930K, 64 GB memory.

### Reproducing code example:
I am not sure if this can be reproduced on another system, but it can be reproduced in my computer, I recorded a video showing how that happens:

https://www.youtube.com/watch?v=ZA_0kyXiXco

The matrix is 2048 by 2048, and if I call the   `linalg.eigh  `twice, it works. That is funny!

**Comment by charris** [comment]
There is a know problem on Windows 10 Version 2004. See #16744 and [Windows report](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html).

**Comment by Chunde** [comment]
> There is a known problem on Windows 10 Version 2004. See #16744 and [Windows report](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html).

Thanks charris, it seems this issue has been fixed right? I will have a look into the detail.

**Comment by charris** [comment]
Not fixed yet. Windows will need to release an updated library to fix their end, and OpenBLAS is working to add a workaround. But I won't feel comfortable until Microsoft releases a fix. If you have the option, I'd downgrade Windows and wait.

**Comment by bashtage** [comment]
> OpenBLAS is working to add a workaround

OpenBLAS has merged this into master and so hopefully it should work without modification from NumPy using a master build of OpenBLAS.

**Comment by seberg** [comment]
Since the workaround for the fmod thing exists, and the actual windows bug hopefully gets slowly fixed, I am going to close.  The more comprehensive duplicate gh-16744 is also closed.
