### ISSUE TITLE
cumsum() changes endianness

### ISSUE THREAD

**Issue by tkzv** [numpy/numpy#17544]
When I apply numpy.cumsum() to a big-endian array, the result is little-endian. 
Observed on AMD64 machine running 64-bit Linux.

### Reproducing code example:

```python
import numpy as np
c = np.array([1, 2, 3], dtype='>i4')
u = np.cumsum(c, dtype='>i4')
print(c, c.dtype, c.view('u1'), sep='\t')
print(u, u.dtype, u.view('u1'), sep='\t')
```

The output is:
```
[1 2 3] >i4     [0 0 0 1 0 0 0 2 0 0 0 3]
[1 3 6] int32   [1 0 0 0 3 0 0 0 6 0 0 0]
```
instead of
```
[1 2 3] >i4     [0 0 0 1 0 0 0 2 0 0 0 3]
[1 3 6] >i4     [0 0 0 1 0 0 0 3 0 0 0 6]
```

### NumPy/Python version information:

1.19.1 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]

**Comment by rossbar** [comment]
This is not specific to `cumsum` - see #15088 for details. I will close this as duplicate, please feel free to add to the discussion there!

**Comment by eric-wieser** [comment]
As mentioned by @rkern, this case is different because the output dtype is explicit yet still ignored.

**Comment by seberg** [comment]
There is the added issue that currently `dtype=` only fixes the operation DType (class, as in typenumber) of the *first* operand. Only for reduction does that directly set the output.  Although in general, we can likely get away with modifying that (there are some tricky points, but they are rare, such as timedelta division).

`dask` has `output_dtypes` I wouldn't be surprised if we have to think about that at some point. As a replacement for `out=new_empty_array_with_fixed_dtype` which is the only current workaround.

**Comment by seberg** [comment]
This is now specific to `cumsum` and some other functions, ufuncs also do this, but give a scary warning that they ignore the exact dtype.

Nothing is quite ideal here, but I think we have to go via the error route before we can think about preserving the dtype instance.  Or add `output_dtype=` to be (theoretically) distinct from the "operation (output) DType".
