### ISSUE TITLE
Potential bug in np.logical_not

### ISSUE THREAD

**Issue by axsk** [numpy/numpy#17560]
I believe to have stumbled upon a bug in `np.logical_not`.
As I understand it from the docs when applied to to a boolean array `x` with the `where` argument set to `x` as well it should flip the value of all Trues and therefore result in an array of Falses only.

This does not happen though..

### Reproducing code example:

```python
import numpy as np
x = np.random.rand(1000) > .5
f = np.logical_not(x, where=x)
assert (f==False).all()
```

### NumPy/Python version information:

1.19.2 3.8.6 (default, Oct  8 2020, 14:06:32) 
[Clang 12.0.0 (clang-1200.0.32.2)]

**Comment by eric-wieser** [comment]
This is documented behavior (emphasis mine):

> `where` :array_like, optional
> > This condition is broadcast over the input. At locations where the condition is True, the out array will be set to the ufunc result. Elsewhere, the out array will retain its original value. Note that if an uninitialized out array is created via the default out=None, **locations within it where the condition is False will remain uninitialized**.

**Comment by axsk** [comment]
My bad, I even recall reading this but apperently didn't understand it.
Sorry for the noise.
