### ISSUE TITLE
DEP: Finalize the deprecation of `np.typeDict`?

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#17585]
The `np.typeDict` dictionary is currently marked as a deprecated alias for `np.sctypeDict`:

https://github.com/numpy/numpy/blob/fb27bd593222f42b4dad5286dcb9be4b74f34273/numpy/core/numerictypes.py#L544-L545

The thing is, it has been marked as such over 14 years (https://github.com/numpy/numpy/commit/668950285c407593a368336ff2e737c5da84af7d). Can it be removed at this point?

**Comment by eric-wieser** [comment]
I'd be in favor of deprecating it using the module level `__getattr__` in `numpy/__init__.py`.

**Comment by BvB93** [comment]
That would definitely be the safer option, especially since I don't think it's mentioned anywhere outside of that single comment.
