### ISSUE TITLE
Getting error: MemoryError: Unable to allocate 201. GiB for an array with shape (2999, 2999, 2999) and data type int64

### ISSUE THREAD

**Issue by balandongiv** [numpy/numpy#17595]
I got the following error

    MemoryError: Unable to allocate 201. GiB for an array with shape (2999, 2999, 2999) and data type int64

when creating a meshgrid with Numpy using the following code

dimension=3
tot_length=2000
list_no=range(1, tot_length)
arr = np.meshgrid ( *[list_no for _ in range ( dimension )] )

May I know where to change the int64 to int32 or, other possible setting that can allow me to maximize the number of tot_length which is higher than the value 2000

Similar post has been posted [elsewhere](https://stackoverflow.com/q/64448748/6446053)

**Comment by eric-wieser** [comment]
Closing, this is better suited to stackoverflow, and I've tried to help there. It's good to see that the new error message made you immediately think about using a narrower dtype, which is something that a plain `MemoryError` before we improved it might not have.
