### ISSUE TITLE
wrong output shape for complex multi-dimensional gets

### ISSUE THREAD

**Issue by MRossol** [numpy/numpy#17604]
Requesting a combination of slices, lists, and integers from 3 + dimensional arrays returns an array of the wrong shape

### Reproducing code example:

```python
import numpy as np

# 3D example
arr3 = np.arange(10**3).reshape((10, 10, 10))

slice_get = arr3[0, :, 1:3] # has shape (10, 2) as expected
list_get = arr3[0, :, [1, 2]] # has shape (2, 10) ?

np.arrayequal(slice_get, list_get) # returns False
np.array_equal(slice_get.flatten(), list_get.flatten()) # also returns False
np.array_equal(slice_get, list_get.T) # returns True!

# 4D example
arr4 = np.arange(10**4).reshape((10, 10, 10, 10))

slice_get = arr4[:, 1:3, :, 0]  # has shape (10, 10, 2) as expected
list_get = arr4[:, [1, 2], :, 0] # has shape (2, 10, 10) ?

np.arrayequal(slice_get, list_get) # returns False
np.array_equal(slice_get.flatten(), list_get.flatten()) # also returns False
np.array_equal(slice_get, list_get.T) # returns False
np.array_equal(slice_get, list_get.reshape(slice_get.shape)) # also returns False...
```

### NumPy/Python version information:

1.19.1 3.7.7 (default, May  6 2020, 04:59:01)
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by rossbar** [comment]
In your example, `slice_get` and `list_get` trigger two different kinds of indexing: basic indexing and advanced indexing, respectively. In fact, `list_get` combines basic and advanced indexing. [This article](https://numpy.org/devdocs/reference/arrays.indexing.html) covers the varying indexing schemes, with [this section](https://numpy.org/devdocs/reference/arrays.indexing.html#combining-advanced-and-basic-indexing) perhaps being especially relevant for your use-case.

**Comment by kdheepak** [comment]
Thanks for the comment! That makes sense: `slice_get` and `list_get` do different things (views and copies for performance reasons), and the docs page is very informative.

Is there a way to reshape the result of `list_get` to ensure it has the same shape and values of `slice_get` for any `n` dimensional array? Even after reading the docs (and experimenting in the repl) I wasn't able to see an way to do that.

**Comment by seberg** [comment]
We have (old) ideas on improving the general situation, but unfortunately, I am not focusing on it now: https://numpy.org/neps/nep-0021-advanced-indexing.html

What I would suggest is that you split out the single `0` here (assuming that this is all you need) into `arr4[..., 0][:, [1, 2], :]` since the `arr4[..., 0]` part is just a view, it is a very cheap operation.

**Comment by kdheepak** [comment]
Thanks for the answers!
