### ISSUE TITLE
Bundled licenses needs update

### ISSUE THREAD

**Issue by mitchnegus** [numpy/numpy#17606]
## Documentation

Looks like the [`LICENSES_bundled.txt`](https://github.com/numpy/numpy/blob/master/LICENSES_bundled.txt) file may be a bit outdated. It appears that the sphinxext submodule was removed in  #17332 and the scipy sphinx theme submodule was removed in #17074 and swapped for the pydata sphinx theme. (Both now seem to be installation dependencies, so I'm guessing they shouldn't be listed in this text file anymore).

**Comment by mitchnegus** [comment]
(I'm happy to make the change, I just haven't contributed to numpy before, so figured it'd be good to get a second opinion...)

**Comment by seberg** [comment]
Good find, a PR would be very welcome!
