### ISSUE TITLE
numpy.where deems null values to contain substring

### ISSUE THREAD

**Issue by jhuo7** [numpy/numpy#17616]
When numpy.where parses results from pandas str.contains, it deems np.nan and NoneType to contain the condition substring.
### Reproducing code example:

```python
import numpy as np
import pandas as pd

# numpy parsing the pandas str.contains results and deems np.nan to contain substring
teststr = pd.Series(['one','two','rome',np.nan])
print(teststr.str.contains('rome'))
print(np.where(teststr.str.contains('rome')))

# numpy parsing the pandas str.contains results and deems NoneType to contain substring
teststr1 = pd.Series(['one','two','rome',type(None)])
print(teststr1.str.contains('rome'))
print(np.where(teststr1.str.contains('rome')))
```

#### software versions
```
#### python           : 3.6.8.final.0
#### python-bits      : 64
#### OS               : Windows
#### OS-release       : 10
#### machine          : AMD64
#### processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
#### pandas           : 1.0.5
#### numpy            : 1.18.5
#### pytz             : 2020.1
#### dateutil         : 2.8.1
#### pip              : 20.1.1
#### setuptools       : 49.2.0.post20200714
```

**Comment by BvB93** [comment]
This sounds more like a pandas issue rather than a numpy one.

The problem seems to be that `pd.Series(...).str.contains(...)` sets a value to `np.nan` 
(instead of a boolean) whenever the `contains(...)` operation fails for a particular element. 
`np.nan` is subsequently picked up by the `np.where()` call, it being a truthful object:

``` python
In [1]: import numpy as np

In [2]: bool(np.nan)
Out[2]: True
```

**Comment by seberg** [comment]
It is a pandas issue, but it is by (old) design. `np.nan` is used for `NA` in pandas, and if you want that convention, you have to stick to pandas functions.

Now, new pandas versions are growing better `NA` values, so you could check those out and there may be a fix in the mid-term. But as of now, this is probably just how things are if you work with "NA" in pandas.
