### ISSUE TITLE
Apache error :  AH01215: import numpy  AH01215: ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by huitikho** [numpy/numpy#17634]
For details, please refer to the attached documents Doc129.docx
[Doc129.docx](https://github.com/numpy/numpy/files/5437069/Doc129.docx)
(https://github.com/numpy/numpy/files/5437068/Doc129.docx)

**Comment by abhijeet1813** [comment]
Have you simply tried installing 'numpy' using pip

**Comment by seberg** [comment]
Old install issue, and nobody will want to open a `docx` to hunt down environment issues.  If you still have some issues check: https://numpy.org/devdocs/user/troubleshooting-importerror.html you may try to open another issue, answering the questions that the error message asks you to investigate.
