### ISSUE TITLE
Original error was: DLL load failed:找不到指定的模块。

### ISSUE THREAD

**Issue by Liuxiang15** [numpy/numpy#17648]
### Reproducing code example:

```python
import pandas as pd
```

### Error message:

Import Error: Unable to import required dependencies: numpy：
...

Original error was: DLL load failed:找不到指定的模块。
### NumPy/Python version information:
Python 3.7.4 32位
numpy 1.19.2

**Comment by eric-wieser** [comment]
Translates to "Cannot find the specified module"

Either way, there's not enough information here to act on. Please read through https://numpy.org/doc/stable/user/troubleshooting-importerror.html, and see if anything there helps.

**Comment by Liuxiang15** [comment]
> Google says `找不到指定的模块` translates to "Cannot find the specified module"
> 
> Either way, there's not enough information here to act on. Please read through https://numpy.org/doc/stable/user/troubleshooting-importerror.html, and see if anything there helps.

Thanks very much.I will try this way.
