### ISSUE TITLE
BUG: NPY_ITER_BUFFERED is set on ufunc reductions, causing bufferred iteration

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#17649]
Even if there is no need, `PyUFunc_ReduceWrapper` unilaterally add the `NPY_ITER_BUFFERED` flag to iteration [here](https://github.com/numpy/numpy/blob/459991afcddfce6fbbae3fa83467fe607f2de7d0/numpy/core/src/umath/reduction.c#L230) and `iterator_loop` adds it [here](https://github.com/numpy/numpy/blob/f4a4ddd56e1c3107a8b376d2e72cd5334676627a/numpy/core/src/umath/ufunc_object.c#L1444). This breaks up the iteration into np.getbuffersize()` chunks, slowing down iteration. xref [this comment](https://github.com/numpy/numpy/issues/3446#issuecomment-19511987).

**Comment by seberg** [comment]
I suppose this is the same issue as gh-17471?

**Comment by mattip** [comment]
Ahh, right. I couldn't find the issue because I searched for `NPY_ITER_BUFFERED`, but the flag is `NPY_ITFLAG_BUFFER`
