### ISSUE TITLE
3D array automatically converted into 1D

### ISSUE THREAD

**Issue by matkaa94** [numpy/numpy#17651]
### Reproducing code example:

```
length=300

while buycounter!=length or nbuycounter !=length:
    current, currency,y = V2.get_data_random_currency(SEQ_LEN,900,1)
    if y==1 and buycounter !=length:
        validation_x.append(current.values)
        validation_y.append(y)
        buycounter=buycounter+1
    elif y==0 and nbuycounter!=length:
        validation_x.append(current.values)
        validation_y.append(y)
        nbuycounter=nbuycounter+1

validation_x = np.asarray(validation_x)
validation_x, validation_y = shuffle(validation_x, validation_y, random_state=0)

pickle.dump(validation_x,open("train300_x.pkl","wb"))
pickle.dump(validation_y,open("train300_y.pkl","wb"))




train_x=pickle.load(open("train100_x.pkl","rb"))
train_y=pickle.load(open("train100_y.pkl","rb"))
validation_x=pickle.load(open("train300_x.pkl","rb"))
validation_y=pickle.load(open("train300_y.pkl","rb"))

train_x = np.asarray(train_x)
train_y = np.asarray(train_y)
validation_x = np.asarray(validation_x)
validation_y = np.asarray(validation_y)
```

After executing this code sample i get a strange problem. The code should generate a 3D array with following shape (300,96,8).

The thing now is, if i put the length on some smaller value, like 100, i get an 3D array. If i put like now the length 300, i get following shape:

```
In[7]:validation_x.shape
Out[7]: (600,)
```

Why is that happening and is there any solution to get these big .pkl files back to an 3D array?

Im happy for any input you guys have!

**Comment by charris** [comment]
Do you close the files anywhere?

**Comment by matkaa94** [comment]
> Do you close the files anywhere?

No i dont. I will try out now.

Thanks!

**Comment by matkaa94** [comment]
I changed now the commands to

`with open("train300_y.pkl", "wb") as f:
    pickle.dump(validation_y, f)`

and 
`with open("train300_x.pkl", "rb") as f:
    train_x = pickle.load(f)`

I read that this command closes the file as soon as the statement ends. But this also doesnt work..

I was also thinking maybe my batches dont have the same length and maybe because of this it puts them into an 1D array with numpy objects inside, but appending two arrays with different lengths works.
