### ISSUE TITLE
[numpy-1.19.3, py3.6.2, dockerized env] - Fatal Python error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by moylop260** [numpy/numpy#17674]
### Reproducing code example:

After release 1.19.3 
 - The following error is raised: `Fatal Python error: Segmentation fault (core dumped)`

(I just enabled the following flag: `export PYTHONFAULTHANDLER=1` but not there is a good output)

I'm using python3.6 virtualenv, using a docker container.

But If I install numpy==1.19.2 the error is not raised.

### NumPy/Python version information:
`python -c "import sys, numpy; print(numpy.__version__, sys.version)"`

🔴 With error
1.19.3 3.6.2 (default, Jul 29 2017, 00:00:00)
[GCC 4.8.4]

🟢 without error
1.19.2 3.6.2 (default, Jul 29 2017, 00:00:00)
[GCC 4.8.4]

What command should I executed to get more info about this issue?

**Comment by seberg** [comment]
@moylop260 hmm, interesting this happens without any other changes. I wonder if there is some other reason involved, e.g. a virtual machine, or so?

Could you try running it using `gdb` (which you may need to install):
```
gdb --args python -c "import sys, numpy; print(numpy.__version__, sys.version)"
```
Then type `r` (or `run`) and hit enter.

**Comment by charris** [comment]
Could be the change in the OpenBLAS library version, perhaps hardware detection related.

**Comment by mattip** [comment]
Where exactly is the segfault? On first import? In some routine? What hardware are you running on (`uname -a`)

**Comment by moylop260** [comment]
`$ uname -a`

Inside docker container
`Linux HOSTNAME 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

In the host
`Linux HOSTNAME 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Running
`gdb --args python3 -c "import sys, numpy; print(numpy.__version__, sys.version)"`

It is running well.

But running our custom program using where it is importing the packages using the following way:
 - https://github.com/odoo/odoo/blob/92ef3b2dd4655913198d10d06598b799fdcae6d0/odoo/modules/module.py#L366-L368

`gdb --args python3 -c "import sys, numpy; print(numpy.__version__, sys.version)"`

```txt
$ gdb --args python3 odoo-bin
gdb --args python3 ~/odoo-12.0/odoo-bin -d openerp_template -i benandfrank --xmlrpc-port=18069 --logfile=out.txt
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
(gdb) r
Starting program: /.repo_requirements/virtualenv/python3.6/bin/python3 /home/odoo/odoo-12.0/odoo-bin -d openerp_template -i benandfrank --xmlrpc-port=18069 --logfile=out.txt
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[New Thread 0x7fb7d2225700 (LWP 1613)]
[New Thread 0x7fb7ca094700 (LWP 1615)]
[New Thread 0x7fb7c9893700 (LWP 1616)]
[New Thread 0x7fb7c1092700 (LWP 1617)]
[New Thread 0x7fb7b8891700 (LWP 1618)]
[New Thread 0x7fb7b0090700 (LWP 1619)]
[New Thread 0x7fb7a788f700 (LWP 1620)]
[New Thread 0x7fb79f08e700 (LWP 1621)]
[New Thread 0x7fb79688d700 (LWP 1622)]
[New Thread 0x7fb78e08c700 (LWP 1623)]
[New Thread 0x7fb78588b700 (LWP 1624)]
[New Thread 0x7fb77d08a700 (LWP 1625)]
[New Thread 0x7fb774889700 (LWP 1626)]
[New Thread 0x7fb76c088700 (LWP 1627)]
[New Thread 0x7fb763887700 (LWP 1628)]
[New Thread 0x7fb75b086700 (LWP 1629)]
[New Thread 0x7fb752885700 (LWP 1630)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fb752885700 (LWP 1630)]
0x0000000000000000 in ?? ()
```

If I install the previous version:
`pip install numpy==1.19.2`

The segmentation fault is not reproduced:

```txt
gdb --args python3 ~/odoo-12.0/odoo-bin -d openerp_template -i benandfrank --xmlrpc-port=18069 --logfile=out.txt
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
(gdb) r
Starting program: /.repo_requirements/virtualenv/python3.6/bin/python3 /home/odoo/odoo-12.0/odoo-bin -d openerp_template -i benandfrank --xmlrpc-port=18069 --logfile=out.txt
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[New Thread 0x7fdb6d8da700 (LWP 1658)]
[New Thread 0x7fdb65df8700 (LWP 1660)]
[New Thread 0x7fdb655f7700 (LWP 1661)]
[New Thread 0x7fdb62df6700 (LWP 1662)]
[New Thread 0x7fdb605f5700 (LWP 1663)]
[New Thread 0x7fdb5ddf4700 (LWP 1664)]
[New Thread 0x7fdb5b5f3700 (LWP 1665)]
[New Thread 0x7fdb58df2700 (LWP 1666)]
[New Thread 0x7fdb565f1700 (LWP 1667)]
[New Thread 0x7fdb53df0700 (LWP 1668)]
[New Thread 0x7fdb515ef700 (LWP 1669)]
[New Thread 0x7fdb4edee700 (LWP 1670)]
[New Thread 0x7fdb4c5ed700 (LWP 1671)]
[New Thread 0x7fdb49dec700 (LWP 1672)]
[New Thread 0x7fdb475eb700 (LWP 1673)]
[New Thread 0x7fdb44dea700 (LWP 1674)]
[New Thread 0x7fdb425e9700 (LWP 1675)]
[New Thread 0x7fdb3fde8700 (LWP 1676)]
[New Thread 0x7fdb3d5e7700 (LWP 1677)]
[New Thread 0x7fdb3ade6700 (LWP 1678)]
[New Thread 0x7fdb385e5700 (LWP 1679)]
[New Thread 0x7fdb35de4700 (LWP 1680)]
[New Thread 0x7fdb335e3700 (LWP 1681)]
[New Thread 0x7fdb30de2700 (LWP 1682)]
[New Thread 0x7fdb2e5e1700 (LWP 1683)]
[New Thread 0x7fdb2bde0700 (LWP 1684)]
[New Thread 0x7fdb295df700 (LWP 1685)]
[New Thread 0x7fdb26dde700 (LWP 1686)]
[New Thread 0x7fdb245dd700 (LWP 1687)]
[New Thread 0x7fdb21ddc700 (LWP 1688)]
[New Thread 0x7fdb1f5db700 (LWP 1689)]
[New Thread 0x7fdb1adda700 (LWP 1690)]
```


It is using `docker --version`
 - `Docker version 19.03.13, build 4484c46d9d`

What another command I should run?

**Comment by seberg** [comment]
I guess OpenBLAS is the best guess right now but that doesn't seem to say much, unless it is OpenBLAS threading related. One try to narrow it down could be trying to set the environment variable `OMP_NUM_THREADS=1` and/or trying to see if there is a hardware detection issue by setting `OPENBLAS_CORETYPE=haswell` (potentially with `OPENBLAS_VERBOSE=2` to be sure it worked).  Although if it was the latter, I would have somewhat expected a more useful backtrace.

**Comment by charris** [comment]
Not many things changed

- BLD: set upper versions for build dependencies
- BUG: Set deprecated fields to null in PyArray_InitArrFuncs 
- ENH: Warn on unsupported Python 3.10+
- MAINT: Update test_requirements.txt.
- ENH: Support for the NVIDIA HPC SDK nvfortran compiler
- BUG: Cygwin Workaround for #14787 on affected platforms
- BUG: Fix memory leak of buffer-info cache due to relaxed strides
- MAINT: Backport openblas_support from master.
- TST: Add Python 3.9 to the CI testing on Windows, Mac.
- TST: Simplify source path names in test_extending.

The only two, other than OpenBLAS, that look possible are the memory leak fix and nulling the deprecated fields. This would be an easy bisect if we had a simple way to test.

**Comment by charris** [comment]
@moylop260 Does your program have any C code or is it pure python.

**Comment by moylop260** [comment]
> @charris Does your program have any C code or is it pure python.

I think it is pure python but it is using a lot of other libraries (maybe with C code)

> Not many things changed

Let me revert sha by sha from v1.19.2 to v1.19.3
in order to know what is the change reproducing it
Installing using `(v1.19.3)$ pip install .`

I will be back

**Comment by moylop260** [comment]
Using 
 - `(v1.19.3)$ pip install .` 🟢 (It is running well)
 - `pip install numpy==1.19.3` 🔴 (It is reproducing the error)

Maybe, it not related with the changes but package build.

I just put here the output installing and uninstalling

🔴 
```txt
$ pip install numpy==1.19.3
Collecting numpy==1.19.3
  Using cached numpy-1.19.3-cp36-cp36m-manylinux2010_x86_64.whl (14.9 MB)
Installing collected packages: numpy
Successfully installed numpy-1.19.3

$ pip uninstall numpy
Found existing installation: numpy 1.19.3
Uninstalling numpy-1.19.3:
  Would remove:
    /virtualenv/python3.6/bin/f2py
    /virtualenv/python3.6/bin/f2py3
    /virtualenv/python3.6/bin/f2py3.6
    /virtualenv/python3.6/lib/python3.6/site-packages/numpy-1.19.3.dist-info/*
    /virtualenv/python3.6/lib/python3.6/site-packages/numpy.libs/libgfortran-2e0d59d6.so.5.0.0
    /virtualenv/python3.6/lib/python3.6/site-packages/numpy.libs/libopenblasp-r0-a32f1dca.3.12.so
    /virtualenv/python3.6/lib/python3.6/site-packages/numpy.libs/libquadmath-2d0c479f.so.0.0.0
    /virtualenv/python3.6/lib/python3.6/site-packages/numpy.libs/libz-eb09ad1d.so.1.2.3
    /virtualenv/python3.6/lib/python3.6/site-packages/numpy/*
```



🟢 
```txt
(v1.19.3)$ git log -r -1 --oneline
5010177cf (HEAD -> v1.19.3, tag: v1.19.3) REL: NumPy 1.19.3 release.

(v1.19.3)$ pip install .
Created wheel for numpy: filename=numpy-1.19.3-cp36-cp36m-linux_x86_64.whl size=10498376 sha256=1c798acde71e7e800b37b3b79aef4dbdb9a01a270b47e89dd43292799909ed24
  Stored in directory: /tmp/pip-ephem-wheel-cache-wk7jbnti/wheels/80/4e/3e/d6f0d3d1d0e6c064a0d152f30c9cec6

(v1.19.3)$ pip uninstall numpy
Found existing installation: numpy 1.19.3
Uninstalling numpy-1.19.3:
  Would remove:
    /virtualenv/python3.6/bin/f2py
    /virtualenv/python3.6/bin/f2py3
    /virtualenv/python3.6/bin/f2py3.6
    /virtualenv/python3.6/lib/python3.6/site-packages/numpy-1.19.3.dist-info/*
    /virtualenv/python3.6/lib/python3.6/site-packages/numpy/*
```

Notice there is not `numpy.libs` so I installed again using pypi package
`$ pip install numpy==1.19.3`

After installed I just deleted all files from `numpy.libs` folder
 - `rm /virtualenv/python3.6/lib/python3.6/site-packages/numpy.libs/*.so`

And now, it was fixed! 🟢 
I mean, the issue is not reproduced.

Checking differences between `numpy.libs` of 1.19.3 and 1.19.2 the `so` libraries different are:
 - 🔴 1.19.3 `numpy.libs/libopenblasp-r0-a32f1dca.3.12.so`
 - 🟢 1.19.2 `numpy.libs/libopenblasp-r0-ae94cfde.3.9.dev.so`

**Comment by mihaimaruseac** [comment]
TensorFlow building against C++ Numpy crashes with OOM on the Windows VMs.

**Comment by mattip** [comment]
Maybe we should back out the OpenBLAS 0.3.12, and put in the PR to detect a bad `fmod` in windows instead.

**Comment by seberg** [comment]
That is unfortunate, but does seem likely necessary.

**Comment by charris** [comment]
I've reopened the warning PR. I'll put it into master also, as at this point we probably don't want the 3.12 library in 1.20 either. It would be nice to pin down what the problem to something easily reproducible so that OpenBLAS could be fixed.

**Comment by moylop260** [comment]
Off-Topic just for record, about this version

In other environment, where this error is not reproduced all processors were consuming 100%
 - ![image](https://user-images.githubusercontent.com/6644187/97733169-1934a400-1a9d-11eb-8f4e-a39c7759fbcd.png)

We just uninstalled `numpy` and now the error was fixed.

**Comment by charris** [comment]
> It is very unfortunate

We are missing some tests that might catch this sort of thing, but not sure how to do that.

**Comment by charris** [comment]
@moylop260 Could you try installing 1.19.4 from the staging repo:
```
python -mpip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple numpy
```
I'd like to get it tested before uploading to PyPI.

**Comment by moylop260** [comment]
Hi @charris 

Thanks for fixing

Installing numpy-1.19.4 is not reproduced anymore.

**Comment by moylop260** [comment]
> We are missing some tests that might catch this sort of thing, but not sure how to do that.

I think it is a corner case since that we have different host server  but they are not reproducing the same issue
Even if we are using the same docker image

I think it is reproduced only for a particular kind of processors.

Let me collect this information if you want.

Or let me, what kind of output do you need?

If you need something else don't doubt

**Comment by charris** [comment]
@moylop260 Thanks for checking. Any information about the processor reported in the docker environment would be helpful to the OpenBLAS developers, we can't stick with an old library version forever :)

@mihaimaruseac Could you also check if your problem is fixed?

**Comment by mihaimaruseac** [comment]
Will trigger a test build later today, sorry for the delay. We are in the process of a new TF release and the CI system is currently used for the release.

**Comment by moylop260** [comment]
I have created the following folder:
 -  https://drive.google.com/drive/folders/18mcYQu4GGPzwCRj14Pzy8LvfC9bcLid8?usp=sharing

There is the info of:
 - docker --version
 - cat /proc/cpuinfo
 - cat /proc/meminfo

And more.

I hope it helps to make a corner case environment to reproduce it running unittest

Regards!

**Comment by charris** [comment]
>I have created the following folder:

@moylop260 Thanks.

**Comment by mihaimaruseac** [comment]
TF also seems to no longer have issues. Thank you

**Comment by charris** [comment]
@mihaimaruseac Thanks for testing.

**Comment by moylop260** [comment]
Thanks for the fix

I confirm that our CI is green again after:
 - https://pypi.org/project/numpy/1.19.4

Thank you!

**Comment by embray** [comment]
Was anyone ever able to pinpoint exactly why Numpy was segfaulting with OpenBLAS 0.3.12?  We are having a similar problem in SageMath with OpenBLAS 0.3.13, though it seems to be hardware-dependent.

**Comment by mattip** [comment]
My theory is that OpenBLAS has CPU detection logic that is used to activate different optimizations.. If the docker image somehow interferes with this logic, OpenBLAS will try to use features that do not exist. You may have some luck overriding the logic by setting `OPENBLAS_NUM_THREADS=1` or by [setting the core type](https://github.com/xianyi/OpenBLAS/wiki/Faq#choose_target_dynamic) with `OPENBLAS_CORETYPE=???`.
