### ISSUE TITLE
Documentation for np.int_ is misleading

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#17671]
A lot of new users are tripped up by the fact that `np.int_` (aka C `long`) is typically 32-bit on windows and 64-bit on linux. Unfortunately, our docs give the impression that it is 64-bit, and the "on this platform" disambiguation is easy to miss:

![image](https://user-images.githubusercontent.com/425260/97556700-b6c2a180-19d1-11eb-9a52-d3e691eba568.png)

It would be good to explicit warn that this integer type is far more likely than any other to vary between platform.

We might also want to adjust the "on this platform" text to be phrased differently for the online docs, where "this platform" means "the build server" not "the platform of the user viewing it".

**Comment by BvB93** [comment]
Might it be an idea to explicitly mention the platform?
Something like `f"Alias on {sys.platform}"`?

**Comment by aryanxk02** [comment]
> A lot of new users are tripped up by the fact that `np.int_` (aka C `long`) is typically 32-bit on windows and 64-bit on linux. Unfortunately, our docs give the impression that it is 64-bit, and the "on this platform" disambiguation is easy to miss:
> 
> ![image](https://user-images.githubusercontent.com/425260/97556700-b6c2a180-19d1-11eb-9a52-d3e691eba568.png)
> 
> It would be good to explicit warn that this integer type is far more likely than any other to vary between platform.
> 
> We might also want to adjust the "on this platform" text to be phrased differently for the online docs, where "this platform" means "the build server" not "the platform of the user viewing it".

Hello, Aryan here. I'm a beginner to Open Source Contribution and would like to fix this issue. Would be glad if you guide me through this. Thank you!

**Comment by rpolley** [comment]
Going to take a shot at fixing this, unless @aryanxk02 is still working on it.

**Comment by KamaljeetSahoo** [comment]
I'm a beginner to Open Source Contribution too, I would like to fix the issue if @aryanxk02 and @rpolley are not working in this issue.

**Comment by rpolley** [comment]
Just realized I never actually linked back to this issue in my PR https://github.com/numpy/numpy/pull/18085

**Comment by melissawm** [comment]
I'm closing this one as resolved by the PR mentioned above, but if you want to start with documentation @KamaljeetSahoo we do have some open issues that you can work on, and you can find them if you search for the DOC prefix or the `04 - Documentation` label. If you find something but need help or have questions feel free to tag me in the issue. Cheers!
