### ISSUE TITLE
Cannot compile numpy with libFLAME support on Ubuntu 20.04

### ISSUE THREAD

**Issue by kehlert** [numpy/numpy#17686]
### Reproducing code example:

First compiled libFLAME with

```bash
./configure --enable-vector-intrinsics=sse --enable-max-arg-list-hack
make
make install
```

Then compiled numpy, which failed to use flame, but did successfully compile with the built-in LAPACK. It also successfully used BLIS.

```bash
NP_BLAS_ORDER=blis NPY_LAPACK_ORDER=flame python setup.py build
```

I confirmed that _/usr/local/lib/libflame.a_ is available. I searched for a relevant issue, but didn't see one (yet). Would appreciate some help. Thanks!

### Error message:

Running from numpy source directory.
Cythonizing sources
numpy/random/_bounded_integers.pxd.in has not changed
numpy/random/_bounded_integers.pyx has not changed
numpy/random/mtrand.pyx has not changed
numpy/random/_bounded_integers.pyx.in has not changed
numpy/random/_pcg64.pyx has not changed
numpy/random/_philox.pyx has not changed
numpy/random/bit_generator.pyx has not changed
numpy/random/_common.pyx has not changed
numpy/random/_sfc64.pyx has not changed
numpy/random/_mt19937.pyx has not changed
numpy/random/_generator.pyx has not changed
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/home/kurt/research/numpy_blis_benchmarks/blis_bm_env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

blis_info:
  FOUND:
    libraries = ['blis', 'blis']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c

  FOUND:
    libraries = ['blis', 'blis']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c

non-existing path in 'numpy/distutils': 'site.cfg'
lapack_opt_info:
flame_info:
C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

creating /tmp/tmpvjcn492z/tmp
creating /tmp/tmpvjcn492z/tmp/tmpvjcn492z
compile options: '-c'
x86_64-linux-gnu-gcc: /tmp/tmpvjcn492z/source.c
x86_64-linux-gnu-gcc -pthread /tmp/tmpvjcn492z/tmp/tmpvjcn492z/source.o -L/usr/local/lib -lflame -o /tmp/tmpvjcn492z/a.out
**/usr/bin/ld: /tmp/tmpvjcn492z/tmp/tmpvjcn492z/source.o: in function `main':
/tmp/tmpvjcn492z/source.c:4: undefined reference to `zungqr_'
collect2: error: ld returned 1 exit status**
C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

creating /tmp/tmp36bvwggf/tmp
creating /tmp/tmp36bvwggf/tmp/tmp36bvwggf
compile options: '-c'
x86_64-linux-gnu-gcc: /tmp/tmp36bvwggf/source.c
x86_64-linux-gnu-gcc -pthread /tmp/tmp36bvwggf/tmp/tmp36bvwggf/source.o -L/usr/local/lib -L/usr/local/lib -lflame -lblis -lblis -o /tmp/tmp36bvwggf/a.out
**/usr/bin/ld: /tmp/tmp36bvwggf/tmp/tmp36bvwggf/source.o: in function `main':
/tmp/tmp36bvwggf/source.c:4: undefined reference to `zungqr_'
collect2: error: ld returned 1 exit status
NOT AVAILABLE**

**
/home/kurt/repos/numpy/numpy/distutils/system_info.py:844: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
/home/kurt/repos/numpy/numpy/distutils/system_info.py:844: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
  NOT AVAILABLE
**

numpy_linalg_lapack_lite:
  FOUND:
    language = c
    define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources

**Comment by FiodarM** [comment]
I seem to run in the same problem also on Ubuntu 20.04 (WSL).

**Comment by rgommers** [comment]
It worked here in 2019: https://github.com/numpy/numpy/issues/14205#issuecomment-534308138

It looks to me like, as the build log says, you have to use a `site.cfg` file to point to `libflame.a`, it won't be recognized automatically. Please see `site.cfg.example` in the root of the repo for details.

Note that `numpy.distutils` is deprecated, so we won't add autodetection of `libflame.a` now. It will come in a future build system.
