### ISSUE TITLE
Name and email addresses needed for 1.20.0 release

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17688]
Could the following please comment with a name and email address needed for the NumPy 1.20.0 release.

- [x] @Alex
- [x] @DumbMice
- [ ] @JMFT
- [ ] @Jack
- [x] @Jakob
- [ ] @Neal C
- [x] @Pan Jan
- [x] @Paul
- [x] @abhilash42
- [x] @andryandrew
- [x] @ashutosh619-sudo
- [x] @bjnath
- [ ] @danbeibei
- [x] @davidedalbosco
- [x] @dojafrat
- [ ] @dpitch40
- [ ] @forfun
- [ ] @iamsoto
- [x] @isabela-pf
- [x] @jakobjakobson13
- [ ] @jbrockmendel
- [x] @johnthagen
- [x] @karan-dhir
- [x] @leakec
- [x] @leeyspaul
- [x] @lkdmttg7
- [x] @madhulikajc
- [x] @marload
- [ ] @mitch
- [x] @peterbell10
- [x] @qiyu8
- [x] @raisinghanii
- [ ] @skywalker
- [ ] @stphnlyd
- [x] @stuartarchibald
- [x] @tabhi0797
- [x] @takanori-pskq
- [x] @tirthasheshpatel
- [x] @vorfol
- [ ] @谭九鼎

**Comment by abhilash42** [comment]
Name: Abhilash Barigidad
Email: abhilash.ub@gmail.com
Thanks!

**Comment by davidedalbosco** [comment]
Name: Davide Dal Bosco
Email: davidemcwood@gmail.com
Ty

**Comment by alex** [comment]
Why?

Name: Alex Gaynor
Email: alex.gaynor@gmail.com

**Comment by madhulikajc** [comment]
Name: Madhulika Jain Chambers
Email: madhulikajain@gmail.com

Thank you!

**Comment by andryandrew** [comment]
Name: Andrea Olivo
Email andryandrew@gmail.com

Thanks!

**Comment by johnthagen** [comment]
Name: John Hagen
Email: johnthagen@gmail.com

**Comment by jakob** [comment]
I think you are probably mistaking me for someone else, I (@jakob) haven't contributed to Numpy.

**Comment by tirthasheshpatel** [comment]
Name: Tirth Patel
E-mail: tirthasheshpatel@gmail.com

**Comment by charris** [comment]
>Why?

@alex I wrote with a capital "a", i.e., `@Alex`, but github changes it to lower case even though the underlying text is still capitalized. Weird, but I didn't notice and apologize for the unexpected ping.

**Comment by leakec** [comment]
Name: Carl Leake
Email: leakec57@gmail.com

Thank you!

**Comment by vorfol** [comment]
Name: Sergei Vorfolomeev
Email: svorfolomeev@vmssoftware.com

**Comment by DumbMice** [comment]
Name: Bangcheng Yang
Email: bangchengyang@hotmail.com

**Comment by Ashutosh619-sudo** [comment]
Name: Ashutosh Singh
Email: ashutoshsinghrkt@gmail.com

**Comment by karan-dhir** [comment]
Name: Karan Dhir
Email: karan.dhir@berkeley.edu

Thank you!

**Comment by takanori-pskq** [comment]
Name: Takanori Hirano
Email: takanori17h@gmail.com

Thank you!

**Comment by peterbell10** [comment]
Name: Peter Bell
Email: peterbell10@live.co.uk

**Comment by lkdmttg7** [comment]
Name: Rajas Rade
Email: raderajas@gmail.com

**Comment by isabela-pf** [comment]
Name: Isabela Presedo-Floyd
Email: irpf.design@gmail.com

Thank you!

**Comment by leeyspaul** [comment]
Name: Paul YS Lee
Email: leeyspaul@gmail.com

Thank you!

**Comment by raisinghanii** [comment]
Name: Yogesh Raisinghani
Email: vanshita12004@gmail.com

Thanks!

**Comment by marload** [comment]
Name: Wansoo Kim
Email: rladhkstn8@gmail.com
