### ISSUE TITLE
abs does not work with -maxint (Trac #1172)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1770]
_Original ticket http://projects.scipy.org/numpy/ticket/1172 on 2009-07-15 by trac user etu, assigned to unknown._

> > > a = array([-128], int8)
> > > a
> > > array([-128], dtype=int8)
> > > abs(a)
> > > array([-128], dtype=int8)

**Comment by seberg** [comment]
Closing this in favor of the duplicate in gh-5657 (may be more duplicates out there).
