### ISSUE TITLE
Polyfit lambda function

### ISSUE THREAD

**Issue by XtremeGood** [numpy/numpy#17707]
## Feature
Currently the `np.polyfit(x, y, order)` returns the coefficients. It would be convenient if at the cost of an additional argument it would return a lambda function. That lambda function can then be used with various other functions like the `scipy.integrate.quad`

```

coeffs = np.polyfit(x, 1/y, 3)
(lambda x:sum([coeffs[len(coeffs) - k - 1] *x**k for k, i in enumerate(coeffs)] )
```

**Comment by XtremeGood** [comment]
Also, a little bit off-topic but isn't there any Github issues for Python feature request?

**Comment by charris** [comment]
Might try the `Polynomial` class, the `Polynomial.fit ` class method returns a Polynomial instance. See the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.html#numpy.polynomial.polynomial.Polynomial).

**Comment by eric-wieser** [comment]
Yeah, everything you describe sounds like you actually want `Polynomial.fit`, which:
* Has a nice `__repr__`
* Implements `__call__`

**Comment by XtremeGood** [comment]
![image](https://user-images.githubusercontent.com/40588378/98039742-2eb32080-1e45-11eb-8df9-096677b85881.png)

Amazing results. Thanks for the help!!

**Comment by charris** [comment]
> But one has to be very careful with the reversal of the coeffs.

Think of them as the leading terms of a series.

**Comment by XtremeGood** [comment]
> 
> 
> > But one has to be very careful with the reversal of the coeffs.
> 
> Think of them as the leading terms of a series.

No I mean like polyfit gives in decreasing order where here they are to be put in reverse order. I have to use matlab during exams as some questions will be requiring them. But I 'm more comfortable with python so it can lead to errors.

**Comment by eric-wieser** [comment]
If you use `Polynomial.fit` instead of `polyfit` then you don't have to reverse the coefficients yourself.

**Comment by XtremeGood** [comment]
> 
> 
> If you use [`Polynomial.fit`](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.fit.html#numpy.polynomial.polynomial.Polynomial.fit) instead of `polyfit` then you don't have to reverse the coefficients yourself.

Thanks @eric-wieser . This would save my errors, at least a bit.

**Comment by XtremeGood** [comment]
![image](https://user-images.githubusercontent.com/40588378/98113772-27822600-1eca-11eb-8dcd-724e9a9344d5.png)

It's not giving me equivalent results.

**Comment by eric-wieser** [comment]
Does passing `domain=[]` fix the problem?

**Comment by XtremeGood** [comment]
Right 5.524 * .18**3 is .033. Thanks, I can now rely on this. That works, thanks!
