### ISSUE TITLE
update Array Creation document

### ISSUE THREAD

**Issue by cooperrc** [numpy/numpy#17710]
## Documentation

I am proposing an update to the current [Array Creation](https://numpy.org/doc/stable/user/basics.creation.html) tutorial as part of Google Season of Docs. The current document has a few missing pieces (like Reading Arrays from disk and binary creation). I would like to limit this document to a tutorial that discusses 3 topics:
1. Python list/tuple conversion to array
2. NumPy array-creation functions
3. SciPy and openCV array creation

I will add slicing/mutation to the list of ways to "create an array" since array operations result in newly created arrays. 

# Below is the proposed outline

**************
Array creation
**************

.. seealso:: :ref:`Array creation routines <routines.array-creation>`

What you'll do
==============
Create NumPy arrays using converting Python objects to arrays, using
NumPy functions, and using external functions. 

What you'll learn
=================
- Use the `numpy.array` function to convert Python objects
- Use common `numpy` functions to create 1D and 2D arrays
- Display your NumPy arrays in plots and text outputs

What you'll need
================

You'll need the NumPy and matplotlib libraries installed and loaded into
your session. 

```
import numpy as np
import matplotlib.pyplot as plt
import cv2
```

---

Introduction
============

There are 6 general mechanisms for creating arrays. This tutorial covers
the first three mechanisms:

1) Conversion from other Python structures (e.g., lists, tuples)
2) Intrinsic numpy array creation objects (e.g., arange, ones, zeros,
   etc.)
3) Use of special library functions (e.g., random, PIL)

outside the scope of this tutorial, but covered in more depth in other
How-to's and tutorials:

4) Reading arrays from disk, either from standard or custom formats [1](https://numpy.org/devdocs/user/how-to-io.html),
[2](https://github.com/numpy/numpy-tutorials/blob/master/content/save-load-arrays.ipynb)
5) Creating arrays from raw bytes through the use of strings or buffers
6)  replicating, joining, or otherwise expanding or mutating existing arrays

This tutorial will not cover creating object arrays or structured
arrays. Both of those are covered in their own sections.

Creating NumPy arrays from Python objects
====================================================

- Simple examples of `np.array` len 3,4
- end with `np.array([1, 2, 3, 4, 5, 6, 7, 8 , 9, 10])`

Creating NumPy arrays with built-in functions
=============================================

- Use `arange`, `linspace`, `logspace`, `zeros`, `meshgrid`, `empty` &
  `full`,  `identity`
- Link to [Array creation
  routines](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation) 

Creating NumPy arrays with SciPy libraries
=============================================

- Use `default_rng.random`, OpenCV `cv2.imread`, [scipy special
  matrices](https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html#special-matrices)

Wrapping up
===========

- You can create nd arrays from a number of Python functions
- Your arrays can build coordinate systems and store data
- You can even build and work with image data

**Comment by melissawm** [comment]
Just to clarify: would this mean updating the array creation document or moving it into a tutorial with similar content?

I would classify the current document as an [Explanation](https://documentation.divio.com/explanation/), and depending on the content we are looking to cover it might be a better choice instead of a tutorial. What do you think @cooperrc ?

**Comment by cooperrc** [comment]
> Just to clarify: would this mean updating the array creation document or moving it into a tutorial with similar content?
> 
> I would classify the current document as an [Explanation](https://documentation.divio.com/explanation/), and depending on the content we are looking to cover it might be a better choice instead of a tutorial. What do you think @cooperrc ?

@melissawm, this is an important distinction. I had assumed _probably incorrectly_ this document is a work-in-progress tutorial. It had a few elements that describe how to use some functions and a few explanations in between. 

I agree, this would make a nice explanation document. It would be a good place to discuss the `dtype` assignment best-practices. Let me build an alternative outline that is an explanation document. 

My thoughts on this document were that the first section would describe basic 1d array creation, then it would describe more involved higher dimensional array creation as it continued.

**Comment by cooperrc** [comment]
@melissawm, below is a proposed explanation document for _Array creation_. I wanted to create levels of understanding/discussion and I think separating functions into 1D, 2D and >2D is a nice way to build the content. Users with little need/background in linear algebra can look at 1D array creation and users that are looking for representation of higher dimensional tensors can move to the end and look at ND creation. 

Introduction
============

- arrays are NumPy objects that make linear algebra and data processing faster in Python
- arrays inherit types, but you can/should specfy `dtype`

There are 6 general mechanisms for creating arrays. This document describes
the first four mechanisms:

1) Conversion from other Python structures (e.g., lists, tuples)
2) Intrinsic numpy array creation objects (e.g., arange, ones, zeros,
   etc.)
3) Use of special library functions (e.g., random, PIL)
4) replicating, joining, or otherwise expanding or mutating existing arrays

outside the scope of this explanation, but covered in more depth in other
How-to's and tutorials:

5) Reading arrays from disk, either from standard or custom formats [1](https://numpy.org/devdocs/user/how-to-io.html),
[2](https://github.com/numpy/numpy-tutorials/blob/master/content/save-load-arrays.ipynb)
6) Creating arrays from raw bytes through the use of strings or buffers

This tutorial will not cover creating object arrays or structured
arrays. Both of those are covered in their own sections.

## Creating 1D arrays
- Convert python list or tuple
- NumPy functions that are 1D e.g. arange, linspace,
- SciPy functions that are 1D e.g. FFT, random.norm
- combine arrays using `concatenate` 

## Creating 2D arrays
- Convert python list or tuple
- NumPy functions that are 2D e.g. rng.random, zeros,
  meshgrid
- Use `default_rng.random`, OpenCV `cv2.imread`, [scipy special
  matrices](https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html#special-matrices)
- combine arrays using `block`, `vstack` and `hstack`

## Creating higher-D arrays
- Convert python list or tuple add list comprehension discussion
- NumPy functions that are ND e.g. rng.random, zeros,
- SciPy functions that are ND e.g. `cv2.imread` 
- using `newaxis` and 

Next steps
===========
- build arrays to represent data, models, and more
- check out the how-tos and tutorials to see arrays in action

**Comment by mattip** [comment]
> arrays inherit types, but you can/should specify dtype

I think it would be good to have a document like this to point to, especially if it gives an example of overflow when adding two `int32`  arrays.

**Comment by melissawm** [comment]
Thanks for thinking about this, @cooperrc . I think this is a valuable document - I just don't know exactly how to classify it. On the one hand, a simple how-to would not cut it, as there is a lot of best-practice to be discussed in this document. On the other hand, [the documentation system](https://documentation.divio.com/explanation/) we are using says

> Explanation should do things that the other parts of the documentation do not. It’s not the place of an explanation to instruct the user in how to do something. Nor should it provide technical description. These functions of documentation are already taken care of in other sections.

I do think the current document fits as an explanation - I don't think examples should be excluded from an explanation page. But your proposal above has a lot of "how-to" points. This could mean the content you are thinking about could end up in two separate documents, an Explanation and a How-To. 

What do you think?

**Comment by cooperrc** [comment]
Thanks @melissawm, maybe you're right that we could have:

0. "Array Creation" - explanation of general inputs and dtypes
1. "How to create 1D arrays",  
2. "How to create 2D arrays", and 
3. "How to create ND arrays." 

Maybe this "NumPy Basics" section could be an explanation space like a "Fundamentals of NumPy". The "Array creation" could be updated to describe all 6 methods that are mentioned in the current document. 

I suggested 3 how-to's, but if you feel like it should be one I could see that working too.

**Comment by a-elhag** [comment]
@melissawm @cooperrc @mattip 

What about adding a fourth one:

4. "How to be mindful of overflows"


It would go through a couple examples of where overflows commonly happen and ways to remedy that. But I'm not sure if this warrants its own `how-to` (or is even applicable here).

**Comment by cooperrc** [comment]
> @melissawm @cooperrc @mattip
> 
> What about adding a fourth one:
> 
> 1. "How to be mindful of overflows"
> 
> It would go through a couple examples of where overflows commonly happen and ways to remedy that. But I'm not sure if this warrants its own `how-to` (or is even applicable here).

@a-elhag, this sounds like a nice How-to. Maybe "How to avoid overflow" or "How to manage overflow"?

If we put together these documents, it will update the Array Creation (original issue) and fill in some much-needed how-to space. @melissawm, what do you think?

**Comment by melissawm** [comment]
The content sounds great to me! I'd say that the "Array creation" explanation and the "How to avoid/manage overflow" are the priorities.

**Comment by cooperrc** [comment]
@melissawm thanks for setting priorities on this thread. 

@a-elhag, did you want to tackle the how to manage/avoid overflow and I'll update Array creation.

**Comment by a-elhag** [comment]
@cooperrc that sounds good to me.
