### ISSUE TITLE
TST: Create tests for correct `__module__` overriding

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#17724]
We should maybe have a test for this type of thing somewhere - verifying that only objects actually in the `np.` namespace have `__module__` set this way.

_Originally posted by @eric-wieser in https://github.com/numpy/numpy/pull/17723#issuecomment-723126822_

---

This might overlap to some degree with the fact that we should probably move the sanity checks in the `__array_function__` wrappers into a test rather than running them at import time.

**Comment by lvllvl** [comment]
Hi,

I noticed a recent contribution added the `test__module__attribute()` function in the [numpy/tests/test_public_api.py](https://github.com/numpy/numpy/blob/88cbe514a17bcbe17f393f511a64869f17327167/numpy/tests/test_public_api.py#L684) file. 

This `test__module__attribute()` function appears to dynamically verify the correctness of `__module__` attributes for objects in the NumPy namespace.

I believe the contribution addresses this issue. Could someone confirm if this fully resolves this it?

If not, could you clarify what additional work remains?

**Comment by seberg** [comment]
Yes, I assume it does.  CC @mtsokol.
