### ISSUE TITLE
DOC: Mention `scipy.signal.correlate` and FFT method in `np.correlate`

### ISSUE THREAD

**Issue by henrikh** [numpy/numpy#17721]
## Documentation

[`numpy.correlate`](https://numpy.org/doc/stable/reference/generated/numpy.correlate.html) is quite slow compared to [`scipy.signal.correlate`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.correlate.html). The following code should demonstrate the difference:

```Python
import numpy as np
import scipy.signal
from numpy.random import default_rng
import time


rng = default_rng()

n = round(1e5)

d = rng.choice([-1, 1], (n,))

sigma = 0.01

s = d + sigma*rng.standard_normal((n,))

startTime = time.time()
print(np.max(np.abs(scipy.signal.correlate(d, s, mode="full"))))
print('time with scipy: {}'.format(time.time()-startTime))

startTime = time.time()
print(np.max(np.abs(np.correlate(d, s, mode="full"))))
print('time with numpy: {}'.format(time.time()-startTime))
```

With the results:

* `n = 1e4`: 0.024 s vs. 0.031 s
* `n = 1e5`: 27 s vs. 0.046 s

This is quite a difference.

Scipy and numpy are obviously different projects, but I think it would make sense, in the name of educating users of numpy, to mention, that `numpy.correlate` and `scipy.signal.correlate` have such different performance characteristics. Just a short sentence would go a long way; perhaps along the lines of: "`numpy.correlate` performs slowly because [algorithm choice]; for large arrays `scipy.signal.correlate` might be considered" (just a suggestion).

**Comment by seberg** [comment]
You are right, it should be added to the "See Also" section and probably in the Notes.

The important point here is that the `scipy.signal` version switches to the `fft` which has far superior performance characteristic. I am not sure we are likley to add it (at least to switch the flip to default to using it), but the Notes should mention that the convolution can often be calculated much faster using the FFT and that this is readily available, e.g. in scipy.
