### ISSUE TITLE
Sorting algorithm in np.argsort

### ISSUE THREAD

**Issue by pandorica-opens** [numpy/numpy#17734]
## Sorting algorithm in np.argsort

I want to benchmark ```np.argsort``` by comparing different sorting algorithms, that are `‘quicksort’`(that is actually *introsort*), `‘mergesort’`, `‘heapsort’`, `‘stable’` available in the [`np.argsort` documentation](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html). I was wondering how was the *pivot* chosen in the i.e. `quicksort`. 

I found the [source file for `np.sort`](https://github.com/numpy/numpy/blob/2bacec9ecb0fc665117a22027b73812509a99f56/numpy/core/src/npysort/quicksort.c.src) and the choice of *pivot* is clear there. However, I cannot find the file describing what is happening under the hood of the `np.argsort`. The reasonable assumption would be that the methods are performing the same sorting, however, I would want to somehow verify it.

**Comment by charris** [comment]
Argsort uses the same algorithm except that the elements are indirectly accessed through the index, which is what is actually sorted.

**Comment by pandorica-opens** [comment]
> Argsort uses the same algorithm except that the elements are indirectly accessed through the index, which is what is actually sorted.

can I look it up somewhere?

**Comment by pandorica-opens** [comment]
When calling `np.argsort(kind='quicksort')` the call gets dispatched to [`PyArray_ArgSort`](https://github.com/numpy/numpy/blob/18a6e3e505ee416ddfc617f3e9afdff5a031c2c2/numpy/core/src/multiarray/item_selection.c#L1399) and then to [`npy_aquicksort`](https://github.com/numpy/numpy/blob/dc56a3f61f62c571d3331e77076662043aacf0ed/numpy/core/src/npysort/quicksort.c.src#L542) (C source links):

This also includes a choice of pivot identical to link to [`np.sort`](https://github.com/numpy/numpy/blob/2bacec9ecb0fc665117a22027b73812509a99f56/numpy/core/src/npysort/quicksort.c.src):

    pm = pl + ((pr - pl) >> 1);
