### ISSUE TITLE
Version mismatch between pip list and numpy.__version__

### ISSUE THREAD

**Issue by AashishV** [numpy/numpy#17742]
Hi, I have installed numpy 1.19.4 using pip 20.2.4 but when I check the version in python shell the version given is 1.15.1

```python
import numpy as np
print(np.__version__)
```

The print statement gives back 1.15.1 while pip list says the numpy version is 1.19.4. I am using Ubuntu 18.04 computer with python 3.6.12.

**Comment by eric-wieser** [comment]
Your `pip` is operating under a different python installation to your `python`. Running `pip -V` and `python -V` should reveal the issue.

**Comment by AashishV** [comment]
Thank you! But I dug in little deeper and found that intel-numpy is also installed with my requirements.txt and somehow it overrides the regular numpy. Any solutions for that?
