### ISSUE TITLE
Divide by zero warning on import on Windows ARM

### ISSUE THREAD

**Issue by fonnesbeck** [numpy/numpy#17747]
Running on Python 3.8.5 on Windows ARM (Surface Pro X), I get the warnings below on import of numpy.

### Error message:

```
In [1]: import numpy
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:172: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-112)),
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:51: RuntimeWarning: divide by zero encountered in log10
  self.precision = int(-log10(self.eps))
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:52: RuntimeWarning: divide by zero encountered in power
  self.resolution = float_to_float(float_conv(10) ** (-self.precision))
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:184: RuntimeWarning: divide by zero encountered in exp2
  epsneg_f80 = exp2(ld(-64))
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:185: RuntimeWarning: divide by zero encountered in exp2
  tiny_f80 = exp2(ld(-16382))
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:199: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-63)),
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:211: RuntimeWarning: divide by zero encountered in nextafter
  huge_dd = (umath.nextafter(ld(inf), ld(0))
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:224: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-105)),
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:225: RuntimeWarning: divide by zero encountered in exp2
  epsneg= exp2(ld(-106)),
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\core\getlimits.py:227: RuntimeWarning: divide by zero encountered in exp2
  tiny=exp2(ld(-1022)))
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\__init__.py:244: RuntimeWarning: divide by zero encountered in subtract
  if not abs(x.dot(x) - 2.0) < 1e-5:
C:\Users\fonne\anaconda3\envs\heat_maps\lib\site-packages\numpy\__init__.py:244: RuntimeWarning: divide by zero encountered in absolute
  if not abs(x.dot(x) - 2.0) < 1e-5:
```

### NumPy/Python version information:

1.19.4 3.8.5 (default, Sep  4 2020, 00:03:40) [MSC v.1916 32 bit (Intel)]

**Comment by charris** [comment]
How did you install NumPy?

**Comment by fonnesbeck** [comment]
Its in a conda env, but installed via pip.

**Comment by fonnesbeck** [comment]
I just tried creating a fresh conda env and installed numpy 1.19.2 using conda. I get the same warning on import.

**Comment by charris** [comment]
I'm asking because we don't release or test ARM Windows wheels, so either NumPy is getting compiled from source on your machine or someone else is providing them. Can you try downloading the wheel -- `pip download numpy` -- and check the name of the wheel?

**Comment by fonnesbeck** [comment]
I'm getting:

    numpy-1.19.4-cp38-cp38-win32.whl

It looks like this is being run under emulation, then. I know it does that for regular windows apps; did not know it happened for Python as well.

**Comment by charris** [comment]
Looks like the emulation is having floating point library problems, not sure why. There may be something we can do to help but I have no idea what.

**Comment by charris** [comment]
@zooba Maybe someone at microsoft can point us in the right direction.

**Comment by zooba** [comment]
The right direction is almost certainly a bug in the emulation. I ran some of these tests last year and things were much better overall with native ARM64 builds (at least in core CPython), but I'm waiting until we get some public CI systems before releasing my builds and effectively forcing you all to support it :)

How is the code raising these warnings working? Clearly they aren't _errors_, so I guess it's checking a flag that isn't actually meaningful here?

**Comment by mattip** [comment]
> How is the code raising these warnings working? Clearly they aren't errors, so I guess it's checking a flag that isn't actually meaningful here?

There is a [sanity check on import](https://github.com/numpy/numpy/blob/953c0827c6f31b574a6792f815ebd47def91df97/numpy/__init__.py#L303). This would usually go through OpenBLAS, but perhaps the package + emulation is somehow diabling that, and using a ufunc to calculate the result. We trap floating point errors in ufuncs, each [compiler/cpu combination](https://github.com/numpy/numpy/blob/v1.19.4/numpy/core/src/npymath/ieee754.c.src#L578) has a different way of detecting floating point errors. For MSVC we use `_statusfp()`. These are then turned into warnings.

**Comment by charris** [comment]
If we build for Windows on ARM64, mingw/Fortran may be a problem. I miss the days when Microsoft provided a Fortran compiler, even though there was a problem with memory/register long integer divides on the 186 processor (`1/-1 == 1`) :)

**Comment by fonnesbeck** [comment]
@zooba I haven't used it extensively, so I'm not sure. I mostly use Python via WSL2 (which works just fine on ARM64).

**Comment by fonnesbeck** [comment]
@charris can it be cross-compiled from Linux ARM?

**Comment by n-assem** [comment]
# You may want to add this code to run first by ipython (in your ipython profile startup)
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore")
    import numpy as np
np.seterr(divide = 'ignore')

**Comment by seberg** [comment]
Going to close this, since its rather old and I suspect we would notice if this spurious warnings wasn't squelched on current versions.  (we may actually have added `np.errstate(all="ignore")` on these calculations.
