### ISSUE TITLE
Importing does not work

### ISSUE THREAD

**Issue by fast-and-curious-1910** [numpy/numpy#17746]
Not even importing works.

```python
import numpy as np
import praw
import settings
```

### Error message while importing

```bash
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Palash\anaconda3\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\Palash\anaconda3\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\Palash\\anaconda3\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in 
the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

[Full Link ](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html)

When I open the link i get a post on ``fmod() after an update on windows 2004 is causing problems`` 

### NumPy/Python version information:
conda 4.8.3
python 3.8.3
numpy 1.19.4

**Comment by seberg** [comment]
That is the correct link, it is a bug in windows, which Microsoft has to fix. One thing you can try is using `numpy==1.19.3` (pin to  a slightly earlier version). That version is identical but uses an updated OpenBLAS which works around that issue.  (The other OpenBLAS had a different set of issues, but those we are aware of shouldn't affect you).

**Comment by fast-and-curious-1910** [comment]
> That is the correct link, it is a bug in windows, which Microsoft has to fix. One thing you can try is using `numpy==1.19.3` (pin to a slightly earlier version). That version is identical but uses an updated OpenBLAS which works around that issue. (The other OpenBLAS had a different set of issues, but those we are aware of shouldn't affect you).

Ill try that! 
Thank You!
