### ISSUE TITLE
Got different result when calculatingarray in different dtype

### ISSUE THREAD

**Issue by BavonChao** [numpy/numpy#17757]
### Reproducing code example:

```python
import numpy as np

a = np.array([ 82, 664], dtype=np.uint64)
b = np.array([ 82, 345], dtype=np.uint64)
b - a.astype(np.uint32)
>> array([0, 18446744073709551297], dtype=uint64)
b - a.astype(np.int32)
>> array([   0., -319.])
```

### NumPy/Python version information:

1.19.2 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]

I thought I shouldn't deal with the dtype of array when doing calculation between them, so I just run `b - a.astype(np.uint32)` ,then I got wrong result, when I firstly met this bug, I thought it's because of `np.arctan2` in my code.

**Comment by mattip** [comment]
NumPy uses C semantics, [overflow is on you to check](https://numpy.org/doc/stable/user/basics.types.html?highlight=overflow#overflow-errors). Is there something else we could do here to improve documentation? Did you work through any numpy tutorials that avoided mentioning this feature of dtypes?

**Comment by mattip** [comment]
@cooperrc @8bitmp3 @melissawm - this highlights the need for a basic array creation tutorial explaining dtypes and overflow

**Comment by BavonChao** [comment]
> 
> 
> @cooperrc @8bitmp3 @melissawm - this highlights the need for a basic array creation tutorial explaining dtypes and overflow

I've added `dtype=np.int32` in my code to ensure the input array is right dtype, thanks for replying, I'll close this issue.
