### ISSUE TITLE
ValueError obtaining the mean of a numpy double array with dtype = object

### ISSUE THREAD

**Issue by juacarri** [numpy/numpy#17762]
#### Describe the bug
I'm getting the error "ValueError: operands could not be broadcast together with shapes (5,) (4,)" when I try to obtain the mean distance of the neighborhood of 50 points. The distance of the neighborhood is calculated using the function BallTree. The query of this function is returning a numpy double array with the distance between the central point and the neighborhood, and I'm searching to get the mean distances between the central point and the neighborhood.

#### Steps/Code to Reproduce

```
import numpy as np
import sklearn.neighbors

rng = np.random.RandomState(0)
X = rng.random_sample((50, 3))

treeBall_Neighbors = sklearn.neighbors.BallTree(X, leaf_size=2)
indices_Neighbors,distance_Neighbors=treeBall_Neighbors.query_radius(X[:], r=0.2,count_only=False,return_distance=True)

print(distance_Neighbors.mean())
```

#### Expected Results
It is curious because if I try to obtain the mean distance one by one, I am not getting errors:
```
print(distance_Neighbors[0].mean())
print(distance_Neighbors[1].mean())
```
#### Actual Results
The error is the following:
```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\numpy\core\_methods.py", line 75, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
ValueError: operands could not be broadcast together with shapes (5,) (4,) 
```

#### Versions
```
System:
    python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
executable: C:\Python37\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.2
      sklearn: 0.23.2
        numpy: 1.16.1
        scipy: 1.2.0
       Cython: 0.29.6
       pandas: 1.1.4
   matplotlib: 3.0.2
       joblib: 0.14.1
threadpoolctl: 2.1.0

Built with OpenMP: True
None
```

**Comment by juacarri** [comment]
Finally I solved with this solution: np.vectorize(np.mean)(distance_Neighbors)

**Comment by seberg** [comment]
That sounds like a reasonable solution if you want the individual mean for each point (no matter how many neighbours). NumPy just doesn't play well with such "ragged" arrays (or array of arrays with different shapes).  Just because it is a cool project (as far as I have heard, I have never used it). If you work with such "ragged" arrays more often, `awkward-array` is all about them.
