### ISSUE TITLE
BUG: Using start/step as keywords only has incorrect behaviour

### ISSUE THREAD

**Issue by piratla1** [numpy/numpy#17764]
Did version 1.18.5 break numpy.arange??
```
import numpy as np
print(np.__version__)
arr3 = np.arange(start=5)
print(arr3)
arr4 = np.arange(stop=8)
print(arr4)

1.18.5
[0 1 2 3 4]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-11be2fcdeb56> in <module>
      3 arr3 = np.arange(start=5)
      4 print(arr3)
----> 5 arr4 = np.arange(stop=8)
      6 print(arr4)

TypeError: arange() missing required argument 'start' (pos 1)
```

**Comment by matthew-brett** [comment]
Gosh - yes - that's super-weird.   You can see that the `np.arange(start=5)` is in fact using a `stop` value of 5 and a `start` value of 0.   But yes, the error for `stop=5` is not what one would expect.

**Comment by piratla1** [comment]
Yes .. I thought only stop was throwing an error, so I tried only start (though it is incorrect).

**Comment by charris** [comment]
The only significant recent change seems to be #10263.

**Comment by seberg** [comment]
As far as I can tell this behaviour is unchanged since the dawn of time, so it is not a regression. But I agree, we should probably make start given only as kwarg an error (we could deprecate, but I guess its weird enough to be called a bug) and make `stop` allow `stop` only.

This could actually be a nice simple thing for a newcomer to work on.

**Comment by charris** [comment]
The error message comes from Python, so perhaps the parsing has changed?

**Comment by seberg** [comment]
@charris this has always been `!PyArg_ParseTupleAndKeywords(args, kws, "O|OOO&", kwd, &o_start,`  (I went back to 2005) meaning that `start` is a required argument, which is incorrect.

**Comment by charris** [comment]
And is new in Python 3.7.

**Comment by seberg** [comment]
Just noticed there is another subtlety here and that is: `np.arange(1, None)` which does the same as `np.arange(1)` (that is related, but a bit different to the other fix, so don't want to add to that right now).
