### ISSUE TITLE
Building wheel from source on Windows 64bit fails on "running build scripts" because of a file exception

### ISSUE THREAD

**Issue by ginwakeup** [numpy/numpy#17767]
Hi,
I am trying to build numpy 1.9.1 from source to output a whl for a vs2015 python compiler.

The build command works fine, but bdist_wheel fails throwing a file exception.

Of course I tried to restart my machine, but I think that the process that it's using f2py.py is the same that is trying to copy it maybe?
No idea.

### Reproducing code example:
python.exe numpy/setup.py bdist_wheel 

### Error message:
```
running build_scripts
  adding 'build\scripts.win-amd64-2.7\f2py.py' to scripts
copying build\scripts.win-amd64-2.7\f2py.py -> build\scripts.win-amd64-2.7
error: could not delete 'build\scripts.win-amd64-2.7\f2py.py': The process cannot access the file because it is being used by another process
```

### NumPy/Python version information:

1.9.1

**Comment by mattip** [comment]
In CI we do this [slightly differently](https://github.com/numpy/numpy/blob/v1.19.1/azure-steps-windows.yml#L43) via `pip wheel -v -v -v --no-build-isolation --no-use-pep517 --wheel-dir=dist .`. Does that work instead?

**Comment by ginwakeup** [comment]
> 
> 
> In CI we do this [slightly differently](https://github.com/numpy/numpy/blob/v1.19.1/azure-steps-windows.yml#L43) via `pip wheel -v -v -v --no-build-isolation --no-use-pep517 --wheel-dir=dist .`. Does that work instead?

Hey, thanks for the tip.
I could build it successfully with this command, but something weird happens.
My numpy source is for 1.9.1 version, but using this command the output wheel is named: **numpy-1.16.6**
How is that possible?

**Comment by ginwakeup** [comment]
Reading the logs, I found the following:

 ```
 Looking up "https://files.pythonhosted.org/packages/14/ef/9f2eeb4ff0c733ad9149f17266e388c308e171fdb8c2415dbb472e2bbc0f/numpy-1.16.6-cp27-cp27m-win_amd64.whl" in the cache
...
  Current age based on date: 4670296
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 4670296
  Using cached numpy-1.16.6-cp27-cp27m-win_amd64.whl (11.9 MB)

```

So, not sure of what's going on with this command, probably it's not building the target source but fetching it from pypi? I've also tried using --no-cache-dir, but it didn't help.

**Comment by ginwakeup** [comment]
I've ended up with a different version of the command to use the source I downloaded and put on my disk:

python -m pip wheel --no-index -v -v -v numpy\1.9.1\source --no-build-isolation --no-use-pep517 --wheel-dir=..\output

But then again, the same error as before comes out, which makes sense, since pip wheel is the same thing as calling setup.py sdist bdist_wheel :(
```

No module named msvccompiler in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using build_ext
  running build_scripts
    adding 'build\scripts.win-amd64-2.7\f2py.py' to scripts
  copying build\scripts.win-amd64-2.7\f2py.py -> build\scripts.win-amd64-2.7
  error: could not delete 'build\scripts.win-amd64-2.7\f2py.py': The process cannot access the file because it is being used by another process
```

**Comment by ginwakeup** [comment]
Even something simple as the following still gives me the same error about f2py..

`python -m pip wheel https://files.pythonhosted.org/packages/41/39/45791d98f1c82789b96d7bdc36f34792d0106b44680fb946d5de9cd5c979/numpy-1.9.1.tar.gz`

**Comment by charris** [comment]
Why are you using 1.9? It is _way_ obsolete and there are no windows wheels for it.

**Comment by ginwakeup** [comment]
> 
> 
> Why are you using 1.9? It is _way_ obsolete and there are no windows wheels for it.

You just made me realize that numpy 1.9.1 doesn't have wheels for Windows, I don't know how I didn't notice.
We updated to 1.10.1 anyway, thank you!

**Comment by mattip** [comment]
Closing, please reopen if there is more to do here.

**Comment by Pikamander2** [comment]
To anyone getting here from Google: If you're using a program like Dropbox, try pausing its automatic syncing.

If you attempt to run `py -m build` in a Dropbox folder, Dropbox will temporarily lock the files while it uploads them, causing this error:

    [WinError 32] The process cannot access the file because it is being used by another process
    error: [WinError 32] The process cannot access the file because it is being used by another process

Once you've paused its syncing, you can rerun the `py -m build` command and it should build without any issues.
