### ISSUE TITLE
NumPy Testing Assertion Not Verbose

### ISSUE THREAD

**Issue by nrobinson12** [numpy/numpy#17770]
When asserting two different multidimensional arrays, the output that is printed after the exception does not show each _full_ array.

The exception and comparison are expected, however, the output does not give enough information to see what the difference between the two arrays is. It appends ellipsis on both of the arrays, and if the value in question is in the ellipsis then you cannot immediately see the value that is different.

### Reproducing code example:

```python
import numpy as np
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
y = np.array([[[1,2],[3,4]],[[6,6],[7,8]]])
np.testing.assert_array_equal(x, y)
```

### Error message:

```
Traceback (most recent call last):
  File "t.py", line 14, in <module>
    np.testing.assert_array_equal(x, y)
  File "/home/nick/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 930, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/nick/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Mismatched elements: 1 / 8 (12.5%)
Max absolute difference: 1
Max relative difference: 0.16666667
 x: array([[[1, 2],
        [3, 4]],
...
 y: array([[[1, 2],
        [3, 4]],
...
```

### NumPy/Python version information:

NumPy 1.19.3
Python 3.8.5
(default, Jul 28 2020, 12:59:40)

**Comment by rgommers** [comment]
> the output that is printed after the exception does not show each _full_ array.

This is on purpose. Arrays can be really large, and this would make the output completely unreadable. 

I don't think there's anything to do here. The user should rerun the test, and drop into a debugger for example.
