### ISSUE TITLE
DLL load failed on new build on/for windows

### ISSUE THREAD

**Issue by fuckfrancisco** [numpy/numpy#17771]
### Steps to reproduce:
compile OpenBLAS
```
cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang.exe -DCMAKE_Fortran_COMPILER:FILEPATH=F:\Miniconda3\Library\bin\flang.exe ^
-DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE -DDYNAMIC_ARCH=OFF -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_FLAGS:STRING="/DWIN32 /D_WINDOWS /W0" ^
-DBUILD_WITHOUT_CBLAS:BOOL=OFF  -DBUILD_WITHOUT_LAPACK:BOOL=OFF -DCMAKE_CONFIGURATION_TYPES:STRING=Release -DNOFORTRAN=0 -DNUM_PARALLEL=12 ^
-DNUM_THREADS=12 -DUSE_THREAD=12 -DINTERFACE64=1 -DBUILD_SHARED_LIBS=ON ^
-DCMAKE_Fortran_FLAGS:STRING="-O3  -g0 -DNDEBUG -pipe -fvectorize" ^
 ..
```

compile numpy-1.19.4 with it linker in DLL or static (both don't work)
```
python setup.py build --fcompiler=flang
  FOUND:
    libraries = ['openblas_64', 'openblas_64']
    library_dirs = ['T:\\OBLAS\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    libraries = ['openblas_64', 'openblas_64']
    library_dirs = ['T:\\OBLAS\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```
both compile without errors with the provided instructions but at runtime numpy can't "find" the DLL (even when the DLL is put into system32), and the numpy created wheel doesn't contain a .libs directory in it

**Comment by fuckfrancisco** [comment]
I recompiled openBLAS again for static library from the releases (first was from git), it appears to be working:
```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'G:\\temp\\tmpc0stas2w.npy'
6 failed, 10486 passed, 488 skipped, 17 xfailed, 1 xpassed, 1 warning, 1 error in 275.09s (0:04:35)
```
is this a normal performance metric for a numpy.test('full') with openBLAS ? (haswell 3900 mhz)

**Comment by fuckfrancisco** [comment]
I did a test on the original version (pip3 install numpy==1.19.4):
```
6 failed, 10485 passed, 487 skipped, 19 xfailed, 1 xpassed, 1 warning, 1 error in 339.02s (0:05:39)
```
not that much of a diffrence in speed ?

**Comment by fuckfrancisco** [comment]
64bit OpenBLAS doesn't work:
```
-DINTERFACE64=1 -DSYMBOLSUFFIX=64_

source.obj : error LNK2001: unresolved external symbol cblas_dgemm64_
source.obj : error LNK2001: unresolved external symbol dgemm_64_
```

**Comment by fuckfrancisco** [comment]
I got a huge performance drop on this build :x
```
Dotted two 4096x4096 matrices in 2.97 s.
Dotted two vectors of length 524288 in 0.20 ms.
SVD of a 2048x1024 matrix in 8.73 s.
Cholesky decomposition of a 2048x2048 matrix in 1.28 s.
Eigendecomposition of a 2048x2048 matrix in 46.86 s.
```
the original version:
```
Dotted two 4096x4096 matrices in 3.03 s.
Dotted two vectors of length 524288 in 0.20 ms.
SVD of a 2048x1024 matrix in 1.54 s.
Cholesky decomposition of a 2048x2048 matrix in 0.17 s.
Eigendecomposition of a 2048x2048 matrix in 10.00 s.
```
is it possible OpenBLAS is so slow ?

**Comment by mattip** [comment]
Is there an issue with NumPy you wish to report or something actionable you wish to improve? If you want to replicate the build process, please note the [options we use for windows](https://github.com/MacPython/openblas-libs/blob/master/tools/build_openblas.sh#L69). Benchmark your build against the wheel you can download from PyPI.

If you want to document your progress as you learn about compiling NumPy, please do not use the issue tracker as your scratchpad.

**Comment by fuckfrancisco** [comment]
excuse me ? are you blind or what ?
read my messages maybe ?
you are blind that you don't see performance 5 times lower ?
you are blind that you don't see config detecting only CBLAS ?
are you blind that you don't see that your "options we use for windows" is not on https://numpy.org/devdocs/user/building.html ?

**Comment by fuckfrancisco** [comment]
2000 problems, did you ever asked yourself how many of them are because you don't wear your glasses ?

**Comment by fuckfrancisco** [comment]
I rebuilt with your script on MSYS2, but I still got those undefined references

**Comment by seberg** [comment]
These are unlikely to be actual issues with NumPy, but rather you asking for help. And since it is unlikely to be an issue with NumPy rather than a general linking difficult, you are probably asking for someones goodwill here. Even if it was an issue you should really tune down several notches...  Building is frustrating, but Matti did give you a good start to continue your work.

I will close the issue. Try giving some full details of how the latest try failed and maybe someone can help you (there are not many who know building on windows well here, so you are probably better of asking elsewhere, debugging remotely is hard).

**Comment by fuckfrancisco** [comment]
my deer kapitaine, whare is "elsewhere" ? how likely is it that this "elsewhere" will know how to complie bether than the original programmers of the whole damn project ? let me get this straight: your project doesn't compile when used with your own instructions on your own site is not considered a problem with your project ?

**Comment by mattip** [comment]
> are you blind that you don't see that your "options we use for windows" is not on https://numpy.org/devdocs/user/building.html ?

If you figure it out, feel free to submit a PR to update the docs. I am not obligated to help you, your tone is offensive. Please abide by the [code of conduct](https://numpy.org/code-of-conduct/).

**Comment by fuckfrancisco** [comment]
my deer kapitaine, if you are not here to help me or whoever else that is trying to use your project, why the hell did you make numpy in the first place ?? you did not intend people to use your project ?? what is the point of your project if it cannot be used by others ?? cheese's chrisp where the hell logic went this generation OMG.... you are supposed to be a programmer matti did you forget your brain in the washing machine or something ??
