### ISSUE TITLE
Unable to use Path object to load file in linux, but can use string

### ISSUE THREAD

**Issue by BYDeloitte** [numpy/numpy#17779]
I produced the following file using np.save in Windows (I can't upload .npy file, just unzip this and you will get the .npy):
[dummy.zip](https://github.com/numpy/numpy/files/5543076/dummy.zip)

I can successfully load it back in Windows using the following code:
`dummy=np.load(some_path/'dummy.npy',allow_pickle=True).item()`
where some_path is a pathlib.Path object.
However, when I move the file to a linux environment, I get an error. Below is the result after I type uname -a
> Linux jupyter-ye-2c-20bryan 5.3.0-1035-azure #36-Ubuntu SMP Thu Aug 6 09:21:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Reproducing code example:

```python
import numpy as np
from pathlib import Path
some_path=Path('<relevant path>')
dummy=np.load(some_path/'dummy.npy',allow_pickle=True).item()
```
Note that: `dummy=np.load(str(some_path/'dummy.npy'),allow_pickle=True).item()` will successfully run

### Error message:

> ---------------------------------------------------------------------------
> UnicodeDecodeError                        Traceback (most recent call last)
> <ipython-input-3-f4716225a7bb> in <module>
>       1 ## Load dictionary
> ----> 2 dummy = np.load(some_path/'dummy.npy',allow_pickle=True).item()
> 
> /opt/conda/envs/f2013/lib/python3.7/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
>     421         _ZIP_SUFFIX = b'PK\x05\x06' # empty zip files start with this
>     422         N = len(format.MAGIC_PREFIX)
> --> 423         magic = fid.read(N)
>     424         # If the file size is less than N, we need to make sure not
>     425         # to seek past the beginning of the file
> 
> /opt/conda/envs/f2013/lib/python3.7/site-packages/fastcore/utils.py in read(self, size, encoding)
>     483 def read(self:Path, size=-1, encoding='utf8'):
>     484     "Read the content of `fname`"
> --> 485     with self.open(encoding=encoding) as f: return f.read(size)
>     486 
>     487 # Cell
> 
> /opt/conda/envs/f2013/lib/python3.7/codecs.py in decode(self, input, final)
>     320         # decode input (taking the buffer into account)
>     321         data = self.buffer + input
> --> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
>     323         # keep undecoded input until the next call
>     324         self.buffer = data[consumed:]
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

### NumPy/Python version information:

`import sys, numpy; print(numpy.__version__, sys.version)`

produces:

> 1.19.2 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
> [GCC 7.5.0]

**Comment by BvB93** [comment]
> ```
> /opt/conda/envs/f2013/lib/python3.7/site-packages/fastcore/utils.py in read(self, size, encoding)
>     483 def read(self:Path, size=-1, encoding='utf8'):
>     484     "Read the content of `fname`"
> --> 485     with self.open(encoding=encoding) as f: return f.read(size)
>     486 
>     487 # Cell
> ```

By the looks of it you somehow added a `read` method to the `pathlib.Path` class, 
which causes `np.load` to identify it as file-like, rather than a path-like, object.

**Comment by BYDeloitte** [comment]
You are absolutely right, I missed that - it is another package that I installed creating this issue. Thanks, I'm going to close this issue.
