### ISSUE TITLE
mgrid[] dimensionality is inconsistent

### ISSUE THREAD

**Issue by drzowie** [numpy/numpy#17772]
Indeixng the numpy.mgrid object produces an array whose first axis runs over vector dimension; the vector contains
an index into the subsequent dimensions.  For example, mgrid[0:5,0:5] produces a 2x5x5 array, and if x and y are 
in-range integers, mgrid[0:5,0;5][:,x,y] generally has the value [x,y].

The problem is that single-dimensional indexing of mgrid does not hew to this pattern.  To keep to the pattern, indexing mgrid
with a single range of N elements should produce a 1xN output array, but it does not.

### Reproducing code example:

import numpy as np
a = np.mgrid[0:5]
b = np.mgrid[0:5,0:5]
c = np.mgrid[0:5,0:5,0:5]
d = np.mgrid[0:5,0:5,0:5,0:5]

assert( d.shape == (4,5,5,5,5) )  # okay!
assert( c.shape == (3,5,5,5) )     # okay!
assert( b.shape == (2,5,5) )        # okay!
assert( a.shape == (1,5) )            # oops

### Error message:

Traceback (most recent call last):
  File "myproblem.py", line 10, in <module>
    assert( a.shape == (1,5) )            # oops
AssertionError

### NumPy/Python version information:

1.19.2 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]

**Comment by eric-wieser** [comment]
Does `np.mgrid[0:5,]` behave as you expect?

**Comment by drzowie** [comment]
Yes.  Yes, it does.

I'll close this -- apparently due to user error.

**Comment by eric-wieser** [comment]
If you have any ideas for making the documentation clearer here, PRs are welcome
