### ISSUE TITLE
constructor/converter of array as a vector 

### ISSUE THREAD

**Issue by frhack** [numpy/numpy#17781]
## Feature

Add to the API a method `np.vector(object)` as shortcut to create a (1,) array.

v = **`np.vector([1,2,3,4])`**

as shortcut of  `np.array([1,2,3,4]).reshape(-1,1)` and

`a = np.array([1,2,3,4]`)

v = **`np.vector(a)`**

to convert (1,) array to (1,1) array. Shortcut for `a.reshape(-1,1)`

**Comment by seberg** [comment]
I think we have at least two alternatives: `np.array(..., ndmin=2)` and `np.atleast_2d(...)`. If you would like a `vector` shorthand because it fits better with your code, I would suggest defining a small wrapper yourself.  I do not think there will be much appetite to add such a shorthand in NumPy, unless I am missing a feature or prior art?

**Comment by frhack** [comment]
> I think we have at least two alternatives: `np.array(..., ndmin=2)` and `np.atleast_2d(...)`. If you would like a `vector` shorthand because it fits better with your code, I would suggest defining a small wrapper yourself. I do not think there will be much appetite to add such a shorthand in NumPy, unless I am missing a feature or prior art?

unfortunately ndmin=2 is not useful because it give us a row vector, whereas the default shape in linear algebra is column vector

**Comment by seberg** [comment]
That is fair enough, others may disagree, but I think introducing such a name for a 1-2 line helper function is a too steep hill to climb in any case.  It would probably be better to start a discussion on the mailing list if you are enthusiastic about it. (Btw. another method is `np.array(...)[..., np.newaxis]`.

**Comment by frhack** [comment]
> That is fair enough, others may disagree, but I think introducing such a name for a 1-2 line helper function is a too steep hill to climb in any case. It would probably be better to start a discussion on the mailing list if you are enthusiastic about it. (Btw. another method is `np.array(...)[..., np.newaxis]`.

we have great syntax support for inner and outer product. What we miss is a straightforward syntax to create vectors.

```
vectore1 = np.array([1,2,3,4]).reshape(-1,1) 
vectore2 = np.array([4,5,6]).reshape(-1,1) 

inner = vectore1.T @ vectore2
outer= vectore1 @ vectore2.T
```

**Comment by seberg** [comment]
@frhack I want to encourage you to make your own small module, so you can write:
```
from frhack import colvec, rowvec

vectore1 = colvec([1, 2, 3, 4])
```
Such a prominent name needs much more deliberation to land in NumPy. For example, Julia has proper rowvec and colvec objects which are 1-D, but behave like vectors in math. (There is a video by them on why having both row and column vectors is a great idea, and just something that our math notation rarely needs to distinguish).

**Comment by frhack** [comment]
> @frhack I want to encourage you to make your own small module, so you can write:
> 
> ```
> from frhack import colvec, rowvec
> 
> vectore1 = colvec([1, 2, 3, 4])
> ```
> 
> Such a prominent name needs much more deliberation to land in NumPy. 

Hi agree with you, I just wanted to highlight that vector creation is cumbesrtome at this time in NumPy.
My syntax is just an example of possible semplification

**Comment by charris** [comment]
This possibility has been discussed before, but it was a long time ago.
