### ISSUE TITLE
Numpy 1.19.4 fails to pass a sanity check due to a bug in the windows runtime.

### ISSUE THREAD

**Issue by axelande** [numpy/numpy#17783]
### Reproducing code example:
[This stackoverflow thread](https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an) explains the issue.

The problem occurs when a fresh installation of numpy 1.19.4 is installed and used. (In my case it occurs while numpy is used for setup.py while importing `setup` from `numpy.distutils.core` which is the first instance where I use numpy in this project..)

**Comment by eric-wieser** [comment]
There's lots of discussion about this in #16744. The solution is either to:
* Use an older version of windows
* Use an older version of numpy

I would recommend [this answer](https://stackoverflow.com/a/64661876/102441) from that stackoverflow thread.
