### ISSUE TITLE
newline='n' in numpy.savetxt documentation

### ISSUE THREAD

**Issue by bersbersbers** [numpy/numpy#17799]
## Documentation

https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html says:

> `numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='n', header='', footer='', comments='# ', encoding=None)`

Note `newline='n'`, which is incorrect - it should be `newline='\n'`.

Looks similar to #4092

**Comment by eric-wieser** [comment]
This one looks like either a numpy_doc bug or a sphinx bug. Updating to sphinx 3 may fix it.

**Comment by mattip** [comment]
Fixed in [the devdocs](https://numpy.org/devdocs/reference/generated/numpy.savetxt.html). Closing.
