### ISSUE TITLE
same values in input matrices and same prodcedures, but different regression results

### ISSUE THREAD

**Issue by xuweichn** [numpy/numpy#17808]
When practicing on regression, I built input matrics by manul definition and vander method respectively. the the input values in both matrices are the same, I got the coefficients with lstsq method and they are same, but the regression resulta are not same.

### Reproducing code example:

```python
import numpy as np
#!/usr/bin/env python
# coding: utf-8

import numpy as np
import matplotlib.pyplot as plt


print('the numpy version:', np.__version__)

x = np.linspace(-2 * np.pi, 2 * np.pi, 50)

def f(x):
    return 0.5 * x + np.sin(x)

# manual construction of input matrix for regression
matrix = np.zeros((3+1, len(x)))
matrix[3, :] = np.sin(x)
matrix[2, :] = x ** 2
matrix[1, :] = x
matrix[0, :] = 1
coe = np.linalg.lstsq(matrix.T, f(x), rcond=-1)[0]
reg = coe @ matrix

# generating input matrix by using numpy.vander function
matrix1 = np.vander(x, 4, increasing=True).T
matrix1[3, :] = np.sin(x)
coe1 = np.linalg.lstsq(matrix1.T, f(x), rcond=-1)[0]
reg1 = coe1 @ matrix1

print('Are matrix and matrix1 equal?', True if (matrix != matrix1).sum()==0 else False)
print('Are coe and coe1 equal?', True if (coe != coe1).sum()==0 else False)
print('Are reg and reg_1 equal?', True if (reg != reg1).sum()==0 else False)
print('How many items are unequal in reg and reg1?', (reg != reg1).sum())

```
the outputs:
the numpy version: 1.19.2
Are matrix and matrix1 equal? True
Are coe and coe1 equal? True
Are reg and reg_1 equal? False
How many items are unequal in reg and reg1? 14

**Comment by mattip** [comment]
Your comparison leaves no room for floating point numerical accuracy. You should use one of the [comparison functions](https://numpy.org/devdocs/reference/routines.logic.html#comparison), not `==`

**Comment by xuweichn** [comment]
thx mattip.
i use np.equal(matrix, matrix1), and got this.
array([ True,  True,  True,  True,  True, False, False,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True, False, False,
       False,  True,  True, False,  True])

my question is the values in matrix and matrix1 are equal. values in coe and coe1 are equal. then do dot product for coe / matrix and coe1 / matrix1. why the results are different? 

When I build matrix2 manually, like what I did for matrix, then the results or dot product are equal.

**Comment by mattip** [comment]
Sorry, I should have been more specific. Use `np.all_close` not `np.equal`. Floating point calculations are inherintly non-exact. For more information peruse some of the [closed issues about floating point accuracy](https://github.com/numpy/numpy/issues?q=is%3Aissue+is%3Aclosed+floating+point+accuracy) or this [wikipedia overview article](https://en.wikipedia.org/wiki/Floating-point_error_mitigation)

**Comment by xuweichn** [comment]
many thx.
