### ISSUE TITLE
bad example for `np.linalg.solve`

### ISSUE THREAD

**Issue by nailbiter91** [numpy/numpy#17811]
with all respect, I think the example given in https://github.com/numpy/numpy/blob/92ebe1e9a6aeb47a881a1226b08218175776f9ea/numpy/linalg/linalg.py#L365

is the particularly unsuitable one. Since the coefficient matrix here is symmetric, novice user cannot immediately understand from this example, whether coefficient matrix should be given in row-first order or column-first order.

**Comment by eric-wieser** [comment]
That's a good point - would you like to make a PR to improve it?

**Comment by nailbiter91** [comment]
sure. give me a minute

**Comment by nailbiter** [comment]
done
