### ISSUE TITLE
Result of float32 * Python float depends on scalar vs. array

### ISSUE THREAD

**Issue by dopplershift** [numpy/numpy#17816]
So I ran into this and I'm baffled:
```python
import numpy as np

# Prints "float32"
print(np.find_common_type([np.float32], [float]))

# Prints "float64"--HUH?
print(np.find_common_type([], [np.float32, float]))
```

I like the first answer, can live with the second, but find the fact that they're different really confusing. Am I missing something?

I'm hitting this with calculations that are changing the returned dtype not just based on the dtype of the inputs, but on **whether they're scalars or not**.

**Comment by BvB93** [comment]
It's mentioned in the `np.result_type()` [docs](https://numpy.org/doc/stable/reference/generated/numpy.result_type.html), but I'm not sure if it's mentioned anywhere else:

> Type promotion in NumPy works similarly to the rules in languages like C++, with some slight differences. When both scalars and arrays are used, the array’s type takes precedence and the actual value of the scalar is taken into account.

**Comment by dopplershift** [comment]
Not quite what I'm talking about in this case though:
```python
# float32
(np.array([1.], dtype=np.float32) * 1.).dtype

# float64
(np.float32(1.) * 1.).dtype
```

There's no value-based promotion here--just that using a scalar triggers promotion it seems.

**Comment by seberg** [comment]
@BvB93's explenation is correct. The first case is exactly "value based promotion", which allows demoting of the Python float (or currently "scalar" in general `np.array(1.)` or `np.float64(1.)` would work as well **if the other argument is an array** (meaning not zero dimensional here).

The confusing thing is that "array" actually means `not 0D` right now.  My personal hope is that we can transition to applying value based promotion only to Python integers and floating point numbers (and not to `np.float64(1.)` which *has* a type).

I suppose the documentation could probably be improved...
