### ISSUE TITLE
Python crash on access to the result of numpy.fromfile

### ISSUE THREAD

**Issue by takeshi87** [numpy/numpy#17819]
Python crashes on access to array read from a file, in case count is above file size (and probably some other restrictions - not all combinations of file size, count and offset result in crash. The one below was verified to crash on two different computers).
Provided dtype also seems to be an important factor.

### Reproducing code example:

```python
import numpy as np
np.zeros(511).tofile('testfile')
print(np.fromfile('testfile', dtype=np.dtype((np.int32, 2)), count = 100000))

```

### Error message:

Python crash due to memory access violation

### NumPy/Python version information:

1.17.4 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]

**Comment by charris** [comment]
Works for me on master.

**Comment by takeshi87** [comment]
I'm not sure what it depends on... I've just tested it with master ("1.20.0.dev0+269f2f2") and the same crash again. Or did you mean python master?
I've also it tested on 3 additional laptops (not checking their python/numpy verions... probably not very fresh one), with same issue being reproducing.

**Comment by charris** [comment]
What platform are you running on?

**Comment by takeshi87** [comment]
x86_64, linux. CPU - I tried a few different, actually all from Intel. Also tried on one VM, with same result.

**Comment by seberg** [comment]
I can reproduce it on master.  Probably a bug with the dtype shape being absorbed into the array :grimacing:...

**Comment by seberg** [comment]
Although, I thought we had fixed some bug around this recently, hmmmm...

**Comment by charris** [comment]
And how are you installing NumPy. I'm running fedora 33, python 3.9, gcc 10.2.1.
```
In [1]: numpy.__version__                                                       
Out[1]: '1.20.0.dev0+269f2f2'

In [2]: np.zeros(511).tofile('testfile')                                        

In [3]: print(np.fromfile('testfile', dtype=np.dtype((np.int32, 2)), count = 100
   ...: 000))                                                                   
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
```

**Comment by seberg** [comment]
Yeah, found the issue... This is reallocing, it might be that the kernel block size or so matters, and the realloc in your case just keeps enough of the old memory around...

**Comment by takeshi87** [comment]
charris: I just did "pip3 install git+https://github.com/numpy/numpy" in venv
Same version reported, but issue still happening.

**Comment by seberg** [comment]
Maybe someone wants to have a quick look, I doubt I will do today, but can do tomorrow. The issue is that the DType is replaced by this point (`arr.dtype` is not the original dtype): https://github.com/numpy/numpy/blob/5e3c943202b5ee95a0676423b85dbaee8013b073/numpy/core/src/multiarray/ctors.c#L3487-L3491

Probably can also be triggered for the normal text path.  Not sure how to best solve it, by just checking the arrays size, or holding on to the original `dtype`, or multiplying with the `elsize` instead of returning only the number...

**Comment by charris** [comment]
I wonder why I am not seeing this?

**Comment by seberg** [comment]
Yeah, its strange, but I am not sure how large allocation page sizes are? Or maybe it depends even on hugepage settings?  One thing that might work to trigger, is to do a loop with different sizes:
```python
for i in range(500, 1000):
    import numpy as np
    np.zeros(i).tofile('testfile')
    print(np.fromfile('testfile', dtype=np.dtype((np.int32, 2)), count = 100000))
```

**Comment by charris** [comment]
I've got hugepages and glibc 2.32 .

**Comment by charris** [comment]
All the sizes work fine. Just in case it makes a difference, kernel 5.9.8 .

**Comment by seberg** [comment]
Hmm, I got glibc 2.31-4, uname gives `5.9.0-2-amd64 #1 SMP Debian 5.9.6-1 (2020-11-08) x86_64 GNU/Linux` and hugepages is `[always]`...  On an Intel machine.

Really curious why the difference...  The code is defnitely wrong `const size_t nsize = PyArray_MAX(nread,1)*PyArray_DESCR(ret)->elsize; ` is too small by a factor of 2, so at some point (maybe even larger?) it must fail really.
