### ISSUE TITLE
type hint: bug in ndarray type

### ISSUE THREAD

**Issue by sfolje0** [numpy/numpy#17826]
I think there is a bug in type hints in numpy package, precisely in ndarray type.
I think that in case of np.array that has one row with only integers (type `int` or `int[64]`) and one row at least one float (e.g. type `float`), then it produces an error since rows have different types so conflict like "np.ndarray[float] != np.ndarray[int]" occurs. 

### Reproducing code example:

```python
# bug.py
import numpy as np 
arr = np.array([[4.2, 2, 3.5], [12, 3, 6]])   
```
and run mypy:
```
$ mypy bug.py 
```

### Error message:
bug.py:3: error: Argument 1 to "array" has incompatible type "List[object]"; expected "Union[List[bool], List[List[bool]], List[List[List[bool]]], List[List[List[List[bool]]]]]"

### NumPy/Python version information:
1.19.2 / 3.8.5

**Comment by BvB93** [comment]
Note that type hints won't be distributed with numpy until the 1.20 release; 
it seems like some third party stub-only package is responsible for the issue at hand.

**Comment by sfolje0** [comment]
>it seems like some third party stub-only package is responsible for the issue at hand.

It is true that I have installed module `data-science-types` version 0.2.20, which I think for me enabled type hints feature. But I thought that type hints are somehow implemented in this repo since .pyi files are present. I thought [installed module](https://pypi.org/project/data-science-types/) just somehow enabled them. I will go there then.
