### ISSUE TITLE
Update Landing page and table of contents - devdocs

### ISSUE THREAD

**Issue by cooperrc** [numpy/numpy#17845]
## Documentation
This issue proposes a redesign of the NumPy Documentation website at www.numpy.org/devdocs. This issue is part of Google Season of Docs to help redesign, add content, and build community in NumPy documentation. My suggestions are designed to implement [NEP 44](https://numpy.org/neps/nep-0044-restructuring-numpy-docs.html)

I would like to make three updates to the website:
1. Match the [landing page](https://numpy.org/devdocs/) to the [table of
contents](https://numpy.org/devdocs/user/whatisnumpy.html)
2. Rename "NumPy basics" to "NumPy Fundamentals"
3. Remove "Explanations" and use "NumPy Fundamentals" as the
explanations section (following the [Divio docs
descriptions](https://documentation.divio.com/))

## 1- Match the [landing page](https://numpy.org/devdocs/) to the [table of contents](https://numpy.org/devdocs/user/whatisnumpy.html)

The current landing page does not match the main documentation table of contents. As the user clicks on an item in the main page, new content appears and the order is slightly different for reference, the current landing vs table of contents is show below:

<table>
<tr>
<th>Landing Page</th>
<th>Table of Contents</th>
</tr>
<tr>
<td>
For users:

- What is NumPy?
- Installation
- Quickstart
- Absolute beginner's guide
- Tutorials
- How-tos
- NumPy API reference
- Explanations
- F2Py guide
- Glossary

For developers/contributors:
- NumPy contributor guide
- Under-the-hood docs
- Building and extending the documentation
- The numpydoc docstring guide
- Benchmarking
- NumPy Enhancement Proposals

Meta Information:
- Reporting bugs
- Release notes
- Document conventions
- License of NumPy

</td>
<td>

- What is NumPy?
- Installation
- NumPy quickstart
- NumPy: the absolute basics for beginners
- NumPy basics
- Miscellaneous
- NumPy for MATLAB users
- Building from source
- Using NumPy C-API
- NumPy Tutorials
- NumPy How Tos
- Explanations
- F2PY Users Guide and Reference Manual
- Glossary
- Under-the-hood Documentation for developers
- NumPy’s Documentation
- Reporting bugs
- Release Notes
- Documentation conventions
- NumPy license

</td>
</tr>
</table>

### Proposed Landing vs Table of Contents:
I propose the new landing page and table of contents should match as such:

<table>
<tr>
<th>Landing Page</th>
<th>Table of Contents</th>
</tr>
<tr>
<td>
For users:

- What is NumPy?
- NumPy: the absolute beginner's guide
- Installation
- NumPy quickstart
- NumPy for MATLAB users
- NumPy Tutorials
- NumPy How Tos
- NumPy ~~basics~~ fundamentals
- Building from source
- Using NumPy C-API
- ~~Explanations~~ _remove_
- F2PY Users Guide and Reference Manual
- Glossary

For developers/contributors:
- NumPy contributor guide
- Under-the-hood docs
- A guide to NumPy documentation 
- Building the NumPy API and reference docs
- Benchmarking
- NumPy Enhancement Proposals

Meta Information:
- Reporting bugs
- Release notes
- Document conventions
- License of NumPy

</td>
<td>

- What is NumPy?
- NumPy: the absolute basics for beginners
- Installation
- NumPy quickstart
- ~~Miscellaneous~~ _remove_
- NumPy for MATLAB users
- NumPy Tutorials
- NumPy How Tos
- NumPy ~~basics~~ fundamentals
- ~~Explanations~~ _remove_
- Building from source
- Using NumPy C-API
- F2PY Users Guide and Reference Manual
- Glossary
- NumPy contributor guide
- Under-the-hood docs
- A guide to NumPy documentation 
- Building the NumPy API and reference docs
- Benchmarking
- NumPy Enhancement Proposals
- Reporting bugs
- Release notes
- Document conventions
- License of NumPy

</td>
</tr>
</table>

## 2- Rename "NumPy basics" to "NumPy Fundamentals" and reorganize content

The NumPy Basics section consists of the following content:
- Data types
- Array creation
- I/O with NumPy
- Indexing
- Broadcasting
- Byte-swapping
- Structured arrays
- Writing custom array containers
- Subclassing ndarray

These articles have very useful information for users, but they do not cover the basics. The basics are covered in [Absolute Basics for beginners](https://numpy.org/devdocs/user/absolute_beginners.html). I propose adding a description to these articles as [Explanation Material](https://numpy.org/devdocs/user/absolute_beginners.html) and relabel the section as "NumPy Fundamentals". This documentation space can be used to clarify parts of NumPy and describe design decisions in NumPy. Most of this content is already there, but it will help to
capture it in its own section and label it. 

I also propose the content be reorganized from common/basic tasks to less common/advanced tasks as such:
- Array creation
- Indexing
- I/O with NumPy
- Data types
- Broadcasting
- Byte-swapping
- Structured arrays
- Writing custom array containers
- Subclassing ndarray

## 3- Remove "Explanations" and use "NumPy Fundamentals" as the explanations section (following the [Divio docs descriptions](https://documentation.divio.com/))

Following from part 2, by using "NumPy ~~Basics~~ Fundamentals" as the explanation section in the documentation, there is no need for the "Explanations" link. The current link brings the user to a subset of the "NumPy Basics":
- Broadcasting

**Comment by melissawm** [comment]
That sounds reasonable and doable. 

What do you propose we do with the contents of the Miscellaneous section? Where should they live? I think that page does contain valuable information, and could use an update (but that would be a separate issue).

**Comment by cooperrc** [comment]
> What do you propose we do with the contents of the Miscellaneous section? Where should they live? I think that page does contain valuable information, and could use an update (but that would be a separate issue).

The content needs a new name. I think a 2-part rename would be a good start:
* move IEEE 754 Floating Point Special Values  to -> Basics/Data Types
* Rename Miscellaneous -> Handling exceptions and interfacing to C/C++ and Fortran

Really the C, Fortran, and C++ headings should link to the more detailed C-API and f2py. 

Alternatively, we can leave it as is and handle it in another PR where the content is updated and moved into different locations: 
* IEEE 754 Floating Point Special Values  to -> NumPy ~~Basics~~ Fundamentals/Data Types _make a sub-heading here_
* How NumPy handles numerical exceptions -> NumPy ~~Basics~~ Fundamentals _give its own doc_
* Fortran -> f2py 
* Interfacing to C -> C-API
* Interfacing to C++ -> C-API

**Comment by melissawm** [comment]
I think the second option makes more sense - let's do one thing at a time. 

Pinging @mattip for opinions on the updating of the landing page :)

**Comment by mattip** [comment]
All the proposed changes 1-3 look good. 
Perhaps each step could be done in a separate PR so we don't get overwhelmed. 
Splitting up "Miscellaneous" could be a 4th step.

**Comment by sleeplessinseattledev** [comment]
I'll start with step 1.

**Comment by cooperrc** [comment]
> I'll start with step 1.

Awesome, thanks @sleeplessinseattledev. Step 2 is covered in #17889. Now, we just have one step left to close this:

- [x] Step 1: update the landing page #17845
- [x] Step 2: rename NumPy Basics -> NumPy Fundamentals #17889 
- [ ]  Step 3: remove the "Explanations" section from the table of contents.

**Comment by sleeplessinseattledev** [comment]
Hi! I'm not sure if I did this correctly! I added orphan to the top of the explanations file as well as adding hidden to the toctree. I might be way off, but would be happy to correct it if this isn't right! 

I'm not familiar with sphinx but tried to figure it out by reading the documentation.

**Comment by mattip** [comment]
Closing, please reopen if I misunderstood. Thanks to all, it looks much nicer now.
