### ISSUE TITLE
numpy aborts on import due to OpenBLAS using too much memory

### ISSUE THREAD

**Issue by burlen** [numpy/numpy#17856]
When I attempt to import numpy on NERSC Cori KNL Nodes (68 physical cores, 4*68 = 272 hyperthreads) an abort that crashes the program occurs. This apparently coming from OpenBLAS, however I think this is a numpy issue since it occurs in import numpy, I've compiled Numpy with default options, and numpy is the one using /configuring OpenBLAS in this case. 

I can work around this by `export OMP_NUM_THREADS=1` however this work around is problematic because there is other software that is parallelized using OpenMP that will be called from my Python script and this other code doesn't have the 256 thread limit that OpenBLAS does.

A solution might be for numpy to configure OpenBLAS to use a fixed number of threads by default.  In my experience using more than the number of physical cores rarely provides a speed up in numerical codes. Further, in MPI parallel codes one must take into account the number of physical cores per MPI rank. Eg if one ran 68 MPI ranks per node and in each ramk OpenBLAS tried to use 272 cores, overall performance would be degraded.  For those reasons, configuring OpenBLAS to use 1 thread would likely be the best default value.

An alternate solution could be a numpy specific hook to set the number of OpenBLAS threads as used by numpy. This way it will not interfere with other codes that use OpenMP for parallelism.

Yet another solution, would be for OpenBLAS not to call abort, however if it tried to use 256 cores on these systems less than optimal performance would be achieved.

### Reproducing code example:
```
$python3
Python 3.8.5 (default, Nov 18 2020, 06:04:22) 
[GCC 8.3.0 20190222 (Cray Inc.)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy

OpenBLAS Warning : The number of CPU/Cores(272) is beyond the limit(256). Terminated.
```

### Error message:
```
OpenBLAS Warning : The number of CPU/Cores(272) is beyond the limit(256). Terminated.
```

### NumPy/Python version information:
```
Python 3.8.5 (default, Nov 18 2020, 06:04:22) 
[GCC 8.3.0 20190222 (Cray Inc.)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.19.1 3.8.5 (default, Nov 18 2020, 06:04:22) 
[GCC 8.3.0 20190222 (Cray Inc.)]
```

**Comment by mattip** [comment]
I wrote a [long answer](https://github.com/numpy/numpy/issues/15764#issuecomment-599878277) on a similar issue in March, the bottom line was to manage your threads with [threadpoolctl](https://github.com/joblib/threadpoolctl) and to carefully benchmark your entire project (not micro-benchmarking individual functions) with different strategies to partition your work. I would be very interested to hear your experiences working with OpenBLAS utilizeing more than 200 threads. In most common scenarios, better performance would be achieved by partitioning work to separate processes on a higher level with tools like dask than low-level fan-in fan-out on single function calls like NumPy's use of OpenBLAS in `linalg`.

**Comment by burlen** [comment]
@mattip I agree completely with you, but... just to clarify this bug report isn't about a performance issue with OpenBLAS or numpy, but rather an issue that `import numpy` aborts on this system. This abort makes our code difficult to use. Also, the work around - setting `OMP_NUM_THREADS` could interfere with other libraries - OpenBLAS is not the only one using OpenMP.

**Comment by seberg** [comment]
Just FYI in case it helps. You can also use `OPENBLAS_NUM_THREADS`, which is openblas specific.

**Comment by burlen** [comment]
@seberg Thanks, yes `OPENBALS_NUM_THREADS` is better.

Also, either` OPENBALS_NUM_THREADS` or `OMP_NUM_THREADS` must be set to 1 to prevent the abort. Setting to other values leads to the same problem (see example below). This is less than ideal because I often make runs such that each MPI process has more than 1 physical core and blas could use them with out issue. In that case I could set the variable manually to tell the right number.

With `OMP_NUM_THREADS`
```
$export OMP_NUM_THREADS=1
$python3 -c "import numpy"
$export OMP_NUM_THREADS=4
$python3 -c "import numpy"

OpenBLAS Warning : The number of CPU/Cores(272) is beyond the limit(256). Terminated.
```

With `OPENBLAS_NUM_THREADS`
```
$export OPENBLAS_NUM_THREADS=1                                                                                                                                                                                                                                             
$unset OMP_NUM_THREADS 
$python3 -c "import numpy"
$export OPENBLAS_NUM_THREADS=4
$python3 -c "import numpy"

OpenBLAS Warning : The number of CPU/Cores(272) is beyond the limit(256). Terminated
```

**Comment by charris** [comment]
Hmm, that sounds like it may be an OpenBLAS bug.

**Comment by mattip** [comment]
@burlen if you have a few moments, could you try with the latest wheels `pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy-1.21.0.dev0`, which now has an updated OpenBLAS (I triggered a wheel build just now)?

**Comment by yerfdogyrag** [comment]
As a note: I had the same issue on numpy-1.20.2 with a host that has 80 cores and VM ulimit of 10G (it's a shared login host).  Basically, the first thing 'import numpy' would try and do is start 80 threads which blows out the VM and I'd get a segfault.

I did a pip install of 1.21.0.dev0+1518 and I'm no longer seeing the issue, but it appears to be because something is now limiting the number of threads to 64.   I'd actually prefer the default to be something smaller than that (8 or 16), but it's a least bound to something sane.

**Comment by rgommers** [comment]
xref https://github.com/MacPython/openblas-libs/pull/64 for details. That's the OpenBLAS build we bundle in wheels, and it's set to max 64 threads. Users who build NumPy against their own BLAS library are of course free to set a different limit.

It looks to me like there is nothing left to do - can we close this?

**Comment by mattip** [comment]
I am pretty sure OpenBLAS now limits the buffers it creates on startup. @burlen could you try again?

**Comment by seberg** [comment]
Lets close it, sounds like it should be fixed.  If it comes up again on newer versions, please do open a new issue!  Thanks everyone.
