### ISSUE TITLE
DOC: Review and expand docstrings for np.gradient()

### ISSUE THREAD

**Issue by investment-ml** [numpy/numpy#17867]
### Reproducing code example:

```python
import numpy as np
x = np.array([0, 1, 2, 3, 4])
dx = np.gradient(x)
y = x**2
np.gradient(y, dx, edge_order=2)
```

### Error message:

```
array([nan, inf, inf, inf, nan])
```

shouldn't it be the following?

```
array([-0.,  2.,  4.,  6.,  8.])
```

### NumPy/Python version information:

```
1.19.4 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]
```

**Comment by dutitello** [comment]
The problem here is that the second argument (`*varargs`) isn't always `dx`, as said in the docs: 

```
Spacing between f values. Default unitary spacing for all dimensions. Spacing can be specified using:
1. single scalar to specify a sample distance for all dimensions.
2. N scalars to specify a constant sample distance for each dimension. i.e. dx, dy, dz, …
3. N arrays to specify the coordinates of the values along each dimension of F. The length of the array must match the size of the corresponding dimension
4. Any combination of N scalars/arrays with the meaning of 2. and 3.
```

In your code you're using `dx` as the `x` values, since you have just one dimension and passed a 5 values array, by the end, as all `x` are the same it broke (maybe here a verification could be made). 

Finally, in your case you should do:
``` python
import numpy as np
x = np.array([0, 1, 2, 3, 4])
y = x**2
np.gradient(y, x, edge_order=2)
```

**Comment by investment-ml** [comment]
Understood. Then I will suggest that when the user passes an array of identical values of the same size of the f, numpy could provide a warning instead. Also some examples for np.gradient in this regard would be very helpful.

**Comment by eric-wieser** [comment]
> Understood. Then I will suggest that when the user passes an array of identical values of the same size as the f, numpy could provide a warning instead. Right now, there are several ugly warnings related to "RuntimeWarning: divide by zero encountered".

Using heuristics for warnings is usually a bad idea, because then users get annoyed, silence all your warnings, and then the non-heuristics ones are lost too
 
> Also some examples for np.gradient in this regard would be very helpful, specifically simple examples like f=x**2, f'x = 2*x, and how to obtain np.gradient to show exactly f'x = 2*x, or f = exp(x), f'x = exp(x).

A documentation PR would definitely be welcome.

**Comment by pojaghi** [comment]
Hi, I'd like to give this a try as part of Grace Hopper OSX day.

**Comment by Ramyahkay** [comment]
Hi, I would like to give this a shot as part of Grace Hopper's OSD (Numpy) day 2022.

**Comment by Pooja-Barai** [comment]
> Hi, I would like to give this a shot as part of Grace Hopper's OSD (Numpy) day 2022.

Hi, I'll be working with Ramya as I would also like to give this a try as part of Grace Hopper OSX day!

**Comment by mattip** [comment]
We do not assign issues. When you submit a PR, be sure to link back to this issue to let others know where they can collaborate or see progress.
