### ISSUE TITLE
BUG: ndarray.putmask should respect the writeable flag

### ISSUE THREAD

**Issue by adlerandy** [numpy/numpy#17871]
Most numpy modify-in-place functions give an error if write=False.
This doesn't happen for np.putmask

```python
a = np.arange(12); a.setflags(write = False)
np.putmask(a, a >= 2, 5)  # Success (Unexpected)
# The expected behaviour is
np.put(a, [3,4],5) # Error "ndarray.put should respect the writeable flag"
```

This is similar to a previous issue (ndarray.put should respect the writeable flag) 
https://github.com/numpy/numpy/pull/5132

Surprisingly, putmask calls np.copy, which gives the expected error.
-- Andy

**Comment by ayush1300** [comment]
In implementation of function put, they have used the function PyArray_FailUnlessWriteable to check if the array is writable or not. Whereas for implementation of putmask, there is no such use of the function. I think maybe thats why there is an error.
