### ISSUE TITLE
np.random.uniform does not raise ValueError when `low > high`, even though other distribution do (like np.random.randint)

### ISSUE THREAD

**Issue by bvavrik** [numpy/numpy#17905]
`print(np.random.randint(2, 1))` raises `ValueError`, also the documentation of `np.random.uniform` says those inputs are `low` and `high`.

### Reproducing code example:

```python
import numpy as np
print(np.random.uniform(2, 1))
```

### NumPy/Python version information:

1.19.2 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0]

**Comment by waderoberts123** [comment]
This is the error message I get: **ValueError: low >= high**

It's not possible to have a low value greater than the high value.

**Comment by seberg** [comment]
Sounds like it should probably be considered a bug, and judging by @waderoberts123 it is probably a regression introduced more recently (the most likely release is NumPy 1.17, but I did not check).  Unless this was actually on purpose, which I do not remember.

**Comment by waderoberts123** [comment]
Were the parameters of the function changed? This seems reasonable and not like a bug to me. You specify the lowest int in the distribution range and the highest int in the range. Why would you want to put a higher number in the low parameter than the high parameter?

```
>>> import numpy as np

>>> print(np.random.randint(1, 10, (10,)))
[6 6 1 3 1 3 5 6 4 8]
```

**Comment by seberg** [comment]
Nevermind, not a regression then, probably.

@waderoberts123 I think you just misread, the example is `np.random.uniform(2, 1)`, so I am not 100% sure if this is (semi) intentional and a documentation fix rather than a bug.

**Comment by bvavrik** [comment]
Yeah, the other option is to fix the documentation. I was also thinking about reporting it as a documentation issue, but as the other distribution raise the error and it is much more intuitive (at least for me), I decided to report that as a bug.

Sorry for the unclear formulation (I admit, it is weird), I just wanted to follow the template.

**Comment by sparkingdark** [comment]
Is it up for work @seberg

**Comment by seberg** [comment]
@sparkingdark sure, please feel free. I am not quite sure what will be way we should fix it, yet.  Just change it, do a deprecation (since it probably worked for very long), or update the docs because I am missing a reason why to allow this.  I think probably a deprecation.

Pinging @bashtage who probably knows what to do.

**Comment by sparkingdark** [comment]
Okay that's will try it. Currently experimenting with numpy and learning
more about it.

**Comment by bashtage** [comment]
Seems like a bug.  Didn't bother checking why it works symmetrically.

**Comment by rkern** [comment]
It works that way because that's how `rk_uniform()` from RandomKit worked, and `RandomState.uniform()` was basically just exposing that behavior. #7026 outlines the history. There is a note in the docstring about this.
