### ISSUE TITLE
Replace variable from writeable to writable

### ISSUE THREAD

**Issue by yoonghm** [numpy/numpy#17928]
## Replace variable `writeable` to `writable`

We may use `writable` instead of `writeable` as in the code, causing error.
Suggest to consider to change the variable `writeable` to `writable`.

**Comment by seberg** [comment]
@yoonghm I think NumPy uses the `writeable` spelling pretty much everywhere (in the code), so I doubt we want to use `writable`.

For now I will update this to a documentation issue to use `writeable` with the `e` in at least most doc-strings.  Or is there any specific error/API that you stumbled upon which has inconsistent naming?

**Comment by yoonghm** [comment]
It is very drastic to change too. Let me close the issue.

**Comment by matthew-brett** [comment]
The Oxford English Dictionary does record "writeable" as a valid alternative spelling, but has "writable" as the main entry.

Python `file` objects have a `writable()` method.

Just mentioning in case it's worth considering an alias.
