### ISSUE TITLE
Non sensical `fill_value: {var}` in masked array

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy#17944]
The following thing introduced by 61f9f6d0fb169cadefe35ea2bdd783848aa771f5 (Stefanv 2007), then seem to have spread by copy-past in the file; and is only present there in the numpy codebase.

```
numpy/ma/core.py
5442:        fill_value : {var}, optional
5500:        fill_value : {var}, optional
5546:        fill_value : {var}, optional
5597:        fill_value : {var}, optional
5668:        fill_value : {var}, optional
5802:        fill_value : {var}, optional
5879:        fill_value : {var}, optional
```

I'm not sure what this means, and Stefan said:

> Probably meant something like 'various', but I don't think that is a notion still used.

This make jedi (that is used for tab-completion) choke on the docstrings to infer types. `{...}` is usually used to denotes set of values, like `{True, False}`, `{'C','F'}`, but `{var}` does not make much sense to me.

If that has a specific meaning; can it be clarified ? otherwise removed ?

**Comment by mattip** [comment]
@BvB93 thoughts?

**Comment by BvB93** [comment]
> @BvB93 thoughts?

The only thing I can think of is that it stands for "variable", as in the to-be supplied scalar is variable.

**Comment by rossbar** [comment]
FWIW `{var}` seems at odds with the [numpydoc standard (see bullet 4 on parameters)](https://numpydoc.readthedocs.io/en/latest/format.html), which notes that curly braces are indeed to be interpreted as sets of options in the parameter type listing.

It should be checked for each instance, but at first glance it looks like `{var}` should be replaced with `scalar or None`

**Comment by Carreau** [comment]
See #17955 , `scalar or None` seem to fit in all cases;
