### ISSUE TITLE
BUG: error: "NPY_HAVE_AVX512BW" is not defined

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#17969]
Builds after merge [are failing](https://github.com/numpy/numpy/runs/1525606424?check_suite_focus=true#step:4:4335) with the message
```
numpy/core/src/common/simd/avx512/conversion.h:59:7: error: "NPY_HAVE_AVX512BW" is not defined, evaluates to 0 [-Werror=undef]
```

**Comment by mattip** [comment]
@seiko2plus ping

**Comment by seiko2plus** [comment]
after #17789, CI builders didn't run on #17791 before, I gonna fix it right now sorry
