### ISSUE TITLE
Running f2py with intel visual Fortran compiler gives unrecognized library file as output, if allocatable arrays are present.

### ISSUE THREAD

**Issue by JasperDec** [numpy/numpy#17967]
I am trying to wrap a set of Fortran codes using f2py, using the intel visual Fortran compiler for a 64 bit system. A minimal example of a Fortran module that gives an error reads as follows. I save this file as ```circlemodule.F90 ``` 

```
 MODULE Circle
!---------------------------------------------------------------------
!
!  Module containing definitions of variables needed to
!  compute the area of a circle of radius r
!
!---------------------------------------------------------------------
   REAL, ALLOCATABLE, DIMENSION(:,:) :: B
   REAL, PARAMETER :: Pi = 3.1415927
   REAL :: radius
END MODULE Circle
```
If I save this file and run ``` python -m numpy.f2py -c circlemodule.F90 -m circlemodule``` from command line f2py finishes without errors, and a file ```circlemodule.cp37-win_amd64.pyd``` is created. However if I then run the following python script in that same directory:
```
import circlemodule

print(circlemodule.__doc__)
```
I get the following error,
```
ImportError: DLL load failed: The specified module could not be found.
```
`Interestingly if I remove the line ```   REAL, ALLOCATABLE, DIMENSION(:,:) :: B``` from the Fortran code this does not occur, and everything works as expected. Thus I do not believe this is a problem with my path, it seems like the generated pyd file somehow does not mesh with Python. I am using Python version 3.6.6 and numpy 1.19.4. My Fortran compiler is the Intel Fortran Compiler Classic 2021. I have already confirmed that this issue does not occur when using gfortran instead, but this is not an option for me since I need to use the MKL library for my application.

**Comment by HaoZeke** [comment]
Since `distutils` is gone now, and it works on `f2py`

```bash
f2py -c circlemodule.f90 -m circ
```

```python
In [1]: import circ
In [2]: print(circ.__doc__)
This module 'circ' is auto-generated with f2py (version:2.0.0.dev0+git20231111.9340fca).
Functions:
Fortran 90/95 modules:
  circle --- b,pi,radius.
```

@JasperDec could you check on the latest `numpy` with `FC` set for `meson` to use the `intel` visual Fortran compiler? If it still persists feel free to reopen :)
