### ISSUE TITLE
DOC: Consider improving release note/warnings for `np.int` deprecation

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#17977]
It seems we should try to improve the release notes (and probably warnings) for the `np.int` and other python alias deprecations.  At least that is my current take-away from the mailing list discussion.

To be fair, the release notes currently state:

> Replacing uses of items in the first column with the contents of the second column will work identically and silence the deprecation warning.

Which is very "recipe" style (and importantly will yield the same results both for `dtype=` use and scalar `np.int(5)` use.  So I am not sure there is actually much of an issue, some thought:

* I do think our type table in the normal docs is pretty clear about what everything means, an additional link there might help?
* Should we point to (or prefer) `np.float64` and `np.int64`? `np.float64` seems like a clearer spelling for `np.float_`.  For integers it is more tricky, though. `int64` may not be ideal on a 32bit system `intp` is often good but confusing...

**Comment by eric-wieser** [comment]
> our type table in the normal docs

I assume you're referring to https://numpy.org/devdocs/reference/arrays.scalars.html?

**Comment by seberg** [comment]
Ooops, I was thinking of: https://numpy.org/devdocs/user/basics.types.html

**Comment by charris** [comment]
@seberg Can this be closed?
