### ISSUE TITLE
h_vmem >= 20G required just to import numpy

### ISSUE THREAD

**Issue by nick-youngblut** [numpy/numpy#17980]
Simply importing numpy requires >=20G of h_vmem for all qsub jobs (SGE cluster running Ubuntu 18.04.5).

### Reproducing code example:

```
conda create -n np_env python=3.7 numpy=1.19.4
```

#### Example of error 

```
qlogin -l h_vmem=10G 
conda activate np_env
```

```python
import numpy as np
Segmentation fault
```

#### Example of providing enough memory

```
qlogin -l h_vmem=20G 
conda activate np_env
```

```python
import numpy as np
# no Segmentation fault
```

**Comment by mattip** [comment]
Could you try with the 1.20rc1 via `pip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple numpy`? We updated OpenBLAS to use less memory for each thread in the pool of threads it opens.

**Comment by nick-youngblut** [comment]
`pip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple numpy` just installs `1.19.4` when I try with either py3.7 or py3.8

**Comment by mattip** [comment]
Ahh, right. Try `python -m pip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple numpy==1.20.0rc1`

**Comment by mattip** [comment]
Or `python -m pip install --only-binary=:all: -i https://pypi.anaconda.org/multibuild-wheels-staging/simple numpy==1.20.0rc1` to make sure you are getting the pre-built wheel

**Comment by nick-youngblut** [comment]
That helped! Now I only need >=9G for h_vmem instead of >=20G

**Comment by mattip** [comment]
That suggests you are running on a machine with many cores, and OpenBLAS will open a thread pool to prepare itself to work on **all** of them. In general that only makes sense if you have huge problems to solve in the first place, so 9GB is not excessive. If you wish to control the number of cores OpenBLAS sees, I think you might find the [threadpoolctl](https://pypi.org/project/threadpoolctl/) package helpful.

**Comment by nick-youngblut** [comment]
Yeah, most nodes on the cluster have >100 cores. `export OPENBLAS_NUM_THREADS=1` does the trick
