### ISSUE TITLE
[BUG] Incorrect casting when adding a scalar to an numpy.ndarray containing a scalar 

### ISSUE THREAD

**Issue by miguelusque** [numpy/numpy#17988]
Hi,

I have just noticed that when I add a scalar to a `numpy.ndarray` containing a scalar, the output datatype is `numpy.int64`, instead of `numpy.ndarray`.

Somehow, I was expecting it to be a `numpy.ndarray`.

As a piece of secondary information, I have noticed that CuPy and JAX keep their original datatypes when performing the operation above (`cupy.core.core.ndarray` and `jax.interpreters.xla._DeviceArray` respectively).

### Reproducing code example:
Input:
```python
import cupy as cp
import numpy as np

s_np = np.array(5)
s_cp = cp.array(5)
print(type(s_np), type(s_cp))

x_np = 3 + s_np
x_cp = 3 + s_cp
print(type(x_np), type(x_cp))
```

Output:
```python
<class 'numpy.ndarray'> <class 'cupy.core.core.ndarray'>
<class 'numpy.int64'> <class 'cupy.core.core.ndarray'>
```

### NumPy/Python version information:

1.18.5 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]

**Comment by YosephKS** [comment]
Hey @miguelusque, this is my first time for this repo and I would like to contribute by resolving this issue. I am not very sure whether it'll be good as a first issue (because all the other `good first issue` were taken), but if I am allowed to make some changes, I'll do my best.

**Comment by miguelusque** [comment]
Hi @YosephKS ,

Thank you for your message.

Unfortunately, I do not belong to NumPy organization, so I cannot advise on that.

Regards,
Miguel

**Comment by seberg** [comment]
Almost all NumPy functions return scalars when you may expect a 0-D array result. This can be a pretty big headache in certain scenarios (the biggest being `object` arrays probably).

The historical reason for this is mainly speed I think (it was before my time): Scalars can often be much faster than arrays.  I don't think anyone on the core team nowadays still considers this a good idea.  The solution is tricky however, and subtly modifies behaviour downstream.  So this is one of the things on the "things to consider for a major release" list.

Of course cupy, JAX, etc. all have picked a simple solution (and seem to fare quite well with it), the don't have _any_ scalars at all.

xref gh-4563 although I am not sure there is a great overview issue about it open.
