### ISSUE TITLE
BUG: Avoid f-strings in `setup.py`?

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#17984]
This is a very simple and small fix, but we should probably avoid Python version specific syntax in the main `setup.py` so that a nice the "Python version >= 3.7 required." error message is given reliably.

I may just do a fix, but if someone beats me to it, all the better :).

**Comment by seberg** [comment]
Well, just realized 1.19.x also includes f-strings and unlike this time I don't remember complaints there, so I guess we probably can just do that as it is a trivial fix, but also maybe doesn't need to be a "policy"...

**Comment by charris** [comment]
Note that the python version is checked ahead of this, so I would just move that up top and then we are free to use f strings.

**Comment by seberg** [comment]
@charris I think because this is a syntax error it fails to parse the file already?  Of course you only run into this if you try to build from source, so not sure it really matters much.

**Comment by eric-wieser** [comment]
Yeah, it's syntax so the order is irrelevant. We've regressed on this multiple times now I think.

**Comment by eric-wieser** [comment]
> Well, just realized 1.19.x also includes f-strings

Didn't we fix that in #16355?

**Comment by seberg** [comment]
Seems it snuck in again for the Python 3.10 error. So it seems the original release of 1.19.x had no issue (and I guess almost nobody uses a later release *and* the source).
