### ISSUE TITLE
numpy import error when running script as cron job

### ISSUE THREAD

**Issue by flipper66** [numpy/numpy#18003]
Python (3.6) was installed as part of Cygwin-X installation on windows 10 computer.
numpy was also installed using the Cygwin-X installer
Operating system in win10 (20H2)
There is a 2.7 instance of python installed in the cygwin environment, and a different distribution installed under windows

I am running my python program as a cygwin cron job.  I have tried a couple things to see if it was path related:
1) I've tried running the cron job to source the user profile before running, and explicitly stating the python to use:
`15,45 * * * * source /home/picarro/.profile; /usr/bin/python3.6 /home/picarro/share/zipraw_2dayprior.py -d -dv omegabus -rds omegabus >> /home/picarro/logs/omegazip.log 2>&1`
2) I've tried creating a shell script that sets environment variables to make sure python3.6 is first and then using cron to run the shell script:
```
#!/usr/bin/bash

source /home/picarro/.profile
source /home/picarro/.bashrc

PATH=/home/picarro/bin:/home/picarro/share:/usr/lib/python3.6:/usr/lib/python3.6
/site-packages:/usr/lib/python3.6.zip:/usr/lib/python3.6/lib-dynload:/usr/lib/py
thon3.6/site-packages/IPythhon/extension:$PATH

# Zip the GPS raw files older than 2 days
/usr/bin/python3.6 /home/picarro/share/zipraw_2dayprior.py -d >> /home/picarro/logs/zip_gpstrh.sh.log 2>&1
```
Note the above PATH is the same as what I see in ipython3.6 when I do a sys.path.

3) I've tried explicitly adding paths using sys.path.add in the python program:
```
#!/usr/bin/python3/6
import os,sys

sys_pth=sys.path

py_pth=['/usr/bin', '/usr/lib/python36.zip', '/usr/lib/python3.6',
    '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3.6/site-packages',
    '/usr/lib/python3.6/site-packages/IPython/extensions',
    '/home/picarro/.ipython'
    ]

for d in py_pth:
    if not d in sys_pth:
        sys.path.append(d)
        print("adding {} to system path".format(d))

import glob
import datetime,time
import numpy as np
import zipfile
import argparse
```
4) I've tried running script without using sys.path.append:
```
#!/usr/bin/python3.6
import os,sys
import glob
import datetime,time
import numpy as np
import zipfile
import argparse
```
5) I've tried using #!/usr/bin/env python3.6 in instead of #!/usr/bin/python3.6 and running the cron job with
   /home/picarro/share/zipraw_2dayprior.py -d >> /home/picarro/logs/zipraw.log 2>&1

When I run the script from the command line or ipython3.6 using any of the following methods, the program runs flawlessly:
> picarro@ ~/share
> $ ./zipraw_2dayprior.py -d
> changed working directory to /home/picarro/data/gps_serial
> Walking all subdirectories for files with extension: .csv
> .csv files found for unique dates: ['2020.12.14']
> 2020-12-15T22:15:38: .csv files for 2020.12.14 are less than 2 days old, skipping
or
> picarro ~/share
> $ /usr/bin/python3.6 /home/picarro/share/zipraw_2dayprior.py -d
> changed working directory to /home/picarro/data/gps_serial
> Walking all subdirectories for files with extension: .csv
> .csv files found for unique dates: ['2020.12.14']
> 2020-12-15T22:17:01: .csv files for 2020.12.14 are less than 2 days old, skippin
or
> picarro@Picarro-CFK2324 ~/share
> $ ipython
> Python 3.6.9 (default, Jul 21 2019, 14:33:59) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 5.8.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> In [1]: %run /home/picarro/share/zipraw_2dayprior.py -d
> changed working directory to /home/picarro/data/gps_serial
> Walking all subdirectories for files with extension: .csv
> .csv files found for unique dates: ['2020.12.14']
> 2020-12-15T22:17:41: .csv files for 2020.12.14 are less than 2 days old, skipping
or using the shell script:
> picarro@Picarro-CFK2324 ~/share
> $ /home/picarro/share/zip_gpstrh.sh 
> 15 Dec 2020 22:33:42

(note I added an echo date in the shell script so there would be some output)
which results in the following in the log file:

> changed working directory to /home/picarro/data/gps_serial
> Walking all subdirectories for files with extension: .csv
> .csv files found for unique dates: ['2020.12.14']
> 2020-12-15T22:36:19: .csv files for 2020.12.14 are less than 2 days old, skipping

When the cron job runs (either the shell script running the program, or running the program directly from cron) I get:

> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 40, in <m
> odule>
>     from . import multiarray
>   File "/usr/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in 
> <module>
>     from . import overrides
>   File "/usr/lib/python3.6/site-packages/numpy/core/overrides.py", line 6, in <m
> odule>
>     from numpy.core._multiarray_umath import (
> ImportError: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/picarro/share/zipraw_2dayprior.py", line 20, in <module>
>     import numpy as np
>   File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
>     from . import core
>   File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 71, in <module>
>     raise ImportError(msg)
> ImportError: 
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> Here is how to proceed:
> - If you're working with a numpy git repository, try `git clean -xdf`
>   (removes all files not under version control) and rebuild numpy.
> - If you are simply trying to use the numpy version that you have installed:
>   your installation is broken - please reinstall numpy.
> - If you have already reinstalled and that did not fix the problem, then:
>   1. Check that you are using the Python you expect (you're using /usr/bin/python3.6),
>      and that you have no directories in your PATH or PYTHONPATH that can
>      interfere with the Python and numpy versions you're trying to use.
>   2. If (1) looks fine, you can open a new issue at
>      https://github.com/numpy/numpy/issues.  Please include details on:
>      - how you installed Python
>      - how you installed numpy
>      - your operating system
>      - whether or not you have multiple versions of Python installed
>      - if you built from source, your compiler versions and ideally a build log
> 
>      Note: this error has many possible causes, so please don't comment on
>      an existing issue about this - open a new one instead.
> 
> Original error was: No such file or directory

Oh, and I added a print statement in the shell script to show the the path when the cron job runs, and this is what I get:

> /home/picarro/bin:/home/picarro/share:/usr/lib/python3.6:/usr/lib/python3.6/site
> -packages:/usr/lib/python3.6.zip:/usr/lib/python3.6/lib-dynload:/usr/lib/python3
> .6/site-packages/IPythhon/extension:/bin:/cygdrive/c/Python27:/cygdrive/c/Python
> 27/Scripts:/cygdrive/c/Python27/Lib/site-packages/PyQt4:/cygdrive/c/WINDOWS/syst
> em32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/S
> ystem32/WindowsPowerShell/v1.0:/cygdrive/c/Python27:/cygdrive/c/Python27/DLLs:/c
> ygdrive/c/Python27/Lib/site-packages/vtk:/cygdrive/c/Python27/gnuplot/binary:/cy
> gdrive/c/Python27/Lib/site-packages/osgeo:/cygdrive/c/Program Files (x86)/python
> xy/SciTE-3.2.2-1:/cygdrive/c/Program Files (x86)/pythonxy/console:/cygdrive/c/MinGW32-xy/bin:/cygdrive/c/Program Files (x86)/pythonxy/swig:/cygdrive/c/Program Files (x86)/pythonxy/gettext/bin:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Program Files (x86)/NTP/bin:/cygdrive/c/Program Files/PuTTY:/cygdrive/c/Program Files (x86)/WinSCP:/cygdrive/c/Users/picarro/AppData/Local/Microsoft/WindowsApps

``

**Comment by mattip** [comment]
Since numpy works outside your cron script, this is not really a numpy issue. You seem to be mixing together `sys.path` and `os.environ['PATH']`. They are two different things. `sys.path` is where the python interpreter expects to find python packages at import, and `os.environ['PATH']` is where the operating system expects to find excecutable programs like `python` or `ls` or `gcc`. You might have some luck ensuring that your `PATH` environment variables (not `sys.path`) match between your normal console where ipytohn3.6 works and in your cron script.

**Comment by mattip** [comment]
Closing, please reopen if I misunderstood.

**Comment by alan-iwashita** [comment]
I had a very similar problem.  I kept search and found this solution helped me get around issues with environment settings that we're preventing some imports from working properly. 

A simple workaround for adding your regular PATH in shell commands in cron is to have the cronjob source your profile by running bash in a login shell. for example instead of

* * * * * some command
You can instead run

* * * * * bash -lc some command
That way if your profile sets the PATH or other environment variables to something special, it also gets included in your command.
