### ISSUE TITLE
Fp16 support in numpy  has lower precision than IEEE half

### ISSUE THREAD

**Issue by dhirajnitk** [numpy/numpy#18006]
np.float16(np.sqrt(2))
-> 1.414

Reality: 
1.41406 
I used half c++ library &  copied numpy half_float.c/half_float.h and they both seem to give 1.41406. 

       for(int i =2; i<40; i++) {
        std::cout << "sqrt(half): " << sqrt(half((float)i)) << std::endl;
        std::cout<<"sqrt(Std(Float)): "<<std::sqrt((float)i)<<std::endl;
        npy_half sqrt_i =  npy_float_to_half(std::sqrt(i));
        std::cout<<"sqrt(half-numpy): "<<npy_half_to_float(sqrt_i)<<std::endl;
    }

This is definitely not precision printing issue . I altered precision to 
 `np.set_printoptions(precision=10).`  but  still seem to get 1.411

**Comment by eric-wieser** [comment]
> This is definitely not precision printing issue.

Despite this claim, this is definitely a printing issue:
```
In [56]: f = np.float16(np.sqrt(2))

In [57]: half = np.float16(np.sqrt(2))

In [58]: full = float(half)

In [59]: full == half
Out[59]: True

In [60]: str(full)
Out[60]: '1.4140625'

In [61]: str(half)
Out[61]: '1.414'
```

This behavior is by design - numpy only prints as many decimal places as is needed to make `np.float16(str(f))` round-trip.

**Comment by eric-wieser** [comment]
Note that `set_printoptions` does not affect the printing of scalars, only of arrays.

**Comment by dhirajnitk** [comment]
The half for sqrt should be print 1.1406 not 1.14

**Comment by dhirajnitk** [comment]
Thanks.. I got 1.4140625 with npy_half_to_float in c as well

**Comment by eric-wieser** [comment]
> The half for sqrt should print 1.1406 not 1.14

What makes you say this? (ignoring your typo) the numbers are the same:
```
In [62]: np.half("1.41406") == np.half("1.414")
Out[62]: True
```
So numpy chooses the shorter printout.

**Comment by matthew-brett** [comment]
Put another way:

```python
[ins] In [2]: half = np.float16(np.sqrt(2))

[ins] In [3]: float(half)
Out[3]: 1.4140625
```
