### ISSUE TITLE
BUG? equality of structured arrays is by field names rather than position

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#18010]
A bug or perhaps a surprise: in #6053, assignment for structured arrays was changed to be by position rather than field name. However, it seems equality checking was forgotten, leading to the following strange behaviour, where one assigns something but cannot then test equality. It would seem an oversight, so cc @ahaldane, who did #6053.
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.21.0.dev0+215.gd7a75e8e8'

In [3]: a = np.array([(1, 2), (3, 4)], dtype=[('a', 'i'), ('b', 'i')])

In [4]: b = np.zeros(2, dtype='i,i')

In [5]: a
Out[5]: array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i4')])

In [6]: b
Out[6]: array([(0, 0), (0, 0)], dtype=[('f0', '<i4'), ('f1', '<i4')])

In [7]: b[:] = a

In [8]: b
Out[8]: array([(1, 2), (3, 4)], dtype=[('f0', '<i4'), ('f1', '<i4')])

In [9]: a == b
<ipython-input-9-eeadcaeab874>:1: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  a == b
Out[9]: False

In [10]: a == b.astype(a.dtype)
Out[10]: array([ True,  True])
```

p.s. @seberg - is it expected that the cast cannot be done as "safe"? Or is this still in the process of being changed?
```
In [12]: a == b.astype(a.dtype, casting='safe')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-896f15d3d149> in <module>
----> 1 a == b.astype(a.dtype, casting='safe')

TypeError: Cannot cast array data from dtype([('f0', '<i4'), ('f1', '<i4')]) to dtype([('a', '<i4'), ('b', '<i4')]) according to the rule 'safe'
```

**Comment by seberg** [comment]
Hmm, gh-15509 is related and had some discussion on safe casting or not (but it was pretty long, so...).  It seems the PR did make/keep the comparison fail (i.e. force the same field order *and* field names).

The cast itself should indeed use the field order for *can cast*, and I think gh-15509 fixed that. Although it is debatable whether the result should use "safe" or "same_kind" casting when the names do not match (we discussed that a bit there IIRC, but I do not have a strong opinion anymore, just a slight tendency to same-kind).

Maybe it is time to prioritize that PR a bit after all...

**Comment by mhvk** [comment]
@seberg - belated thanks! I had a quick look at gh-15509 and it does look that would fix this - would be nice to have it in!

**Comment by seberg** [comment]
So the current behaviour is that the casting is fixed, but comparisons still requires promotion to work.  And promotion is (correctly) strict about field names.

To fix that, we would need a comparison specific promotion function.  That could be part of moving the comparison to a ufunc now (like the string C++ ufuncs).  But that would add a quite large amount of complexity probably.

That is probably not particularly tough, but requires to duplicate/refactor the current promotion to allow ignoring field names.

**Comment by mhvk** [comment]
Yes, the comparison is still rather tricky. But not sure it needs new promotion. Perhaps instead we should just follow the general `np.equal` default of `casting='same_kind'`? (which is now well-behaved!)

**Comment by seberg** [comment]
Yes, it needs custom promotion, since you still want to be able to compare `f8,i4` and `i4,f8` because that promotes but neither direction is a "same kind" cast.
Note that I mean "promotion" specific to `==` not the generic promotion (common dtype) that concatentation uses.

**Comment by seberg** [comment]
@mhvk I am going to close this, but please reopen if you disagree.  I think we are in a decent spot now, with casting going by field and promotion+comparisons enforcing field order _and_ names to match (comparison use normal promotion).
I suppose structured comparison could be relaxed a bit, but I am not sure that comparing different names is actually useful.

Part of the original discussion is of course now still very true:  You can assign to another array, but cannot then compare to the same.  This is not weird though (except that it currently errors):  You can also assign ints to strings, but they won't compare.

**Comment by mhvk** [comment]
Yes, agreed! It is in a good state now.
