### ISSUE TITLE
No module named 'numpy.core._multiarray_umath' while installing from wheel file

### ISSUE THREAD

**Issue by connectsachit** [numpy/numpy#18025]
I am running a spark-submit , where I am passing wheel files for all dependencies in --py-files
I am using pandas , and since pandas requires numpy. It is giving me following error:

No module named 'numpy.core._multiarray_umath

Spark submit command used:
spark-submit --py-files wheelforpandas,wheelfornumpy,....  mainscript.py

Pandas Version : 0.25.0

**Comment by rgommers** [comment]
This will be an environment issue, you are picking up a numpy source repo or an incorrectly built numpy.

There's nothing wrong here, but if you need more help for this kind of install issue, please supply the full details of how you installed numpy and python.
