### ISSUE TITLE
Numpy saying it's not installed, while it is installed with pip??

### ISSUE THREAD

**Issue by 0noca** [numpy/numpy#18040]
```python
import numpy as np

n_array = np.array([ [1,2,3,4,5],[5,4,3,2,1] ])
print(n_array)
```

### Error message:
ModuleNotFoundError: No module named 'numpy'

### NumPy/Python version information:

Traceback (most recent call last):
  File "C:\Users\Onoca\IdeaProjects\data\scratch.py", line 1, in <module>
    import sys, numpy; print(numpy.__version__, sys.version)
ModuleNotFoundError: No module named 'numpy'

### > python -mpip install numpy <

Requirement already satisfied: numpy in c:\users\onoca\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (1.19.4)

#### EDIT

I installed Numpy in 'C:\Users\Onoca\venv\Scripts'
and now I'm getting a new error.

Traceback (most recent call last):
  File "C:\Users\Onoca\IdeaProjects\data\scratch.py", line 1, in <module>
    import numpy as np
  File "C:\Users\Onoca\venv\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\Onoca\venv\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\Onoca\\venv\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**Comment by mattip** [comment]
Use `python -m pip install numpy==1.19.3`

**Comment by 0noca** [comment]
> Use `python -m pip install numpy==1.19.3`

 The script f2py.exe is installed in 'C:\Users\Onoca\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Should I mind this, or?

**Comment by rgommers** [comment]
Don't worry about the warning.

No issue to fix in NumPy, Matti already gave the correct workaround, so I'll close this now.
