### ISSUE TITLE
NumPy not importing for 3.9

### ISSUE THREAD

**Issue by nith2001** [numpy/numpy#18041]
New to Github so I'm not perfect with the details, so I'll try my best. Essentially, I'm trying to import numpy and run it and it's not working when I run it with 3.9, but it's working with 3.8. Here's some of the code and Terminal commands.

Code:
import numpy as np
print("Hello World")

**_Terminal Command:_**

**Input**
$ python3.9 numpytesting.py
**Output**
Traceback (most recent call last):
  File "/Users/vikram/Documents/Python/PythonCode/numpytesting.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Input**
python3.8 numpytesting.py
**Output**
Hello World

I have my pips installed and my latest version of NumPy installed as well. It's also weird because, I'm pretty sure I deleted 3.8 and only have 3.9 in my Applications folder, which is really weird. I'm thinking it's probably due to the location of some of the stuff I've downloaded but I can't be sure since I'm not very tech savvy when it comes to downloading locations and the technicalities behind it. Feel free to ask for more details since I'm still getting used to posting questions on coding forums. Any help will be appreciated!

**Comment by charris** [comment]
The CLI pip cannot be relied on if you have more than one Python installed. Try `python -mpip install numpy --user`, where `python` is the version you want to use.

**Comment by nith2001** [comment]
Tried that, and here was the output:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (1.8.0rc1)
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install --upgrade pip' command.

**Comment by rossbar** [comment]
Try @charris 's suggestion again, but with `python3` or `python3.9` in place of the `python`

**Comment by nith2001** [comment]
Awesome, that worked! Sorry, I blanked forgot to replace the python with python3.9. The same method worked when I replaced the command with SciPy.
