### ISSUE TITLE
Inner product of binary vectors may yield incorrect results

### ISSUE THREAD

**Issue by miranska** [numpy/numpy#18056]
When computing the inner product of arrays containing binary variables, I would expect to see the following behaviour:
```
dot([1, 1, 0], [1, 1, 0]) = sum(and([1, 1, 0], [1, 1, 0])) = sum([1, 1, 0]) = 0,
```
as the summation would be done using xor-ing. However, I get 1 instead.

### Reproducing code example:

```python
import numpy as np
x = np.array([1, 1, 0], dtype=bool)
binary_dot_product = np.dot(x,x)
assert binary_dot_product == 0
```

### Error message:

The assertion in the example above fails because of the `binary_dot_product  == True` (1) rather than `False` (0).

### NumPy/Python version information:

```
1.19.4 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]
```

**Comment by charris** [comment]
The numpy booleans are not a binary ring,  the '+' operator is equivalent to `or`, not `xor`. People find that more useful for their applications.

**Comment by charris** [comment]
Note that `sum` casts booleans to integers. If you want `xor` you can do
```
In [1]: np.logical_xor.reduce([1, 1, 0])                                        
Out[1]: False
```

**Comment by miranska** [comment]
@charris , thank you! I wonder if the documentation for the `np.dot` function should be updated. Currently, it says
> If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

Perhaps it can be extended to say something like 
> This does not apply to the boolean vectors. To compute the inner product of a pair of boolean vectors, use `np.logical_xor.reduce(np.logical_and(a, b))`.

**Comment by eric-wieser** [comment]
@miranska, it's not clear to me that there is an established convention for what "inner product" means on booleans, so your suggested wording doesn't seem like an improvement to me.

We probably should put in the docs somewhere what `*` and `+` mean on booleans in numpy, but I don't think that belongs in the docs for `dot`. `np.add` and `np.multiply` seem like sensible places to describe that.

**Comment by charris** [comment]
Just to note that there was discussion of that choice. IIRC, economists use the current convention.

**Comment by javad-doliskani** [comment]
It seems to me that the terminology doesn't really represent the mathematics behind the definition. For example, an inner product is always bilinear, meaning that <a + b, c> = <a, c> + <b, c>. The current convention doesn't satisfy this property: let w and v be boolean vectors where v is not all false. Then <w + v, v> = <w, v> + <v, v>.  According to the current convention, the right hand side is always "true" no matter what w is, since <v, v> is always "true". But if you set w = Not(v) then the left hand side is false! Am I missing something here?

**Comment by eric-wieser** [comment]
> the right hand side is always "true" no matter what w is, since <v, v> is always "true".

This is false if `v` contains all `False` entries

> But if you set w = Not(v) then the left hand side is false!

This statement is also false, `w + v` is `Or(w, v)` and `Or(Not(v), v)` contains all `True` entries.

**Comment by javad-doliskani** [comment]
@eric-wieser the condition on v was that it is not all false, but your second point is correct. I misinterpreted the definition of addition for boolean vectors. So if I am not mistaking you are using a definition of inner product over boolean algebras, for example as in https://cs.du.edu/~frederic/research/0902.1290.pdf.

**Comment by charris** [comment]
> doesn't really represent the mathematics behind the definition

True, but somewhat beside the point :) The practice of using xor in order to have a ring/field was popular some time ago -- you will find it in old texts about measure theory and boolean algebra -- but in practice other conventions have replaced it.

**Comment by miranska** [comment]
@charris, @eric-wieser, @javad-doliskani, thank you for the insightful discussion! Given the ambiguity of the problem, let's close this one as-is.
