### ISSUE TITLE
numpy.distutils.cpuinfo does not support modern featuresets

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#18058]
### Reproducing code example:

```python
>>> import numpy.distutils.cpuinfo
>>> numpy.distutils.cpuinfo.cpu.info[0]
{'Processor': '0', 'Component Information': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'Identifier': 'Intel64 Family 6 Model 142 Stepping 10', 'Family': 6, 'Model': 142, 'Stepping': 10, 'Configuration Data': b'\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00', 'ProcessorNameString': 'Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz', 'VendorIdentifier': 'GenuineIntel', 'FeatureSet': 823869439, '~MHz': 2112, 'Update Revision': b'\x00\x00\x00\x00\xca\x00\x00\x00', 'Previous Update Revision': b'\x00\x00\x00\x00\xca\x00\x00\x00', 'Update Status': 7, 'Platform Specific Field 1': 128, 'Platform Specific Field 2': b'\x00\x00\x00\x00'}
```

On windows, this contains no information about whether more modern feature sets are supported, particularly `avx2`. Since this information is implicitly contained on the linux-side, this leads to non-portable code like the following in the wild:
https://github.com/facebookresearch/faiss/blob/v1.6.5/faiss/python/loader.py#L19

I'm now trying to figure out how to do so on windows (in the context of https://github.com/conda-forge/faiss-split-feedstock/issues/23), and so I had a look at the state of https://github.com/numpy/numpy/blob/master/numpy/distutils/cpuinfo.py. I think this file hasn't been kept up-to-date for a while, and the question is if there is even a desire to update this for more featuresets, e.g. à la:
```python
>>> numpy.distutils.cpuinfo.cpu._has_avx2()
```

Particularly, I'm wondering if -- with all the recent work on universal SIMD intrinsics -- there wouldn't be reusable infrastructure for this already? @seiko2plus @Qiyu8 

Edit: Java gives the following output:
```
CPU:total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 142 stepping 10, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx, fma 
```

### NumPy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.19.4 3.8.6 | packaged by conda-forge | (default, Dec 22 2020, 09:52:49) [MSC v.1916 64 bit (AMD64)]
```

**Comment by seiko2plus** [comment]
> Particularly, I'm wondering if -- with all the recent work on universal SIMD intrinsics -- there wouldn't be reusable infrastructure for this already?

we didn't expose it yet but you can access the detected CPU features starting from "1.19.0"
```Python
>>> from numpy.core._multiarray_umath import __cpu_features__ as cpu_have
>>> cpu_have["AVX2"]
````

**Comment by h-vetinari** [comment]
Thanks so much @seiko2plus, this is exactly what I needed for the moment! I'd hope this becomes public API somewhere (maybe even worth a thought if this belongs in CPython itself)?

**Comment by mattip** [comment]
We need to think about what namespace to expose it in. Maybe, as an extension to python `platform`, we could have `numpy.platform`. xref gh-9258 and gh-14492 about deficiencies in `show_config` too.

**Comment by seiko2plus** [comment]
@mattip, please be aware that `__cpu_features__` affected by the environment variable `NPY_DISABLE_CPU_FEATURES` which allows the user to disable certain features in runtime.

**Comment by h-vetinari** [comment]
Gentle ping on this :)

**Comment by mattip** [comment]
> `__cpu_features__` [are] affected by the environment variable `NPY_DISABLE_CPU_FEATURES` 

So we may want to expose 3 sets of features
- what the NumPy build can support
- a best guess of what is supported on the runtime machine
- what will be used in the code (including anything like environment variables)

**Comment by mattip** [comment]
I think we can close this. `show_config` on my machine now shows
```
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

and we are deprecating numpy.distutils. Please reopen if there is more information needed.
