### ISSUE TITLE
Support for float hex format for matrix()

### ISSUE THREAD

**Issue by kenorb** [numpy/numpy#18060]
Similar to #5504, `np.matrix` should be able to interpret float hex format.

So this works fine:

```pycon
>>> np.matrix("[1.1 1.2 1.3 1.4]")
matrix([[1.1, 1.2, 1.3, 1.4]])
```

Also the following array of hexes works fine using `np.array()`:

```pycon
>>> np.array("[%s %s %s %s]" % (1.1.hex(), 1.2.hex(), 1.3.hex(), 1.4.hex()))
array('[0x1.199999999999ap+0 0x1.3333333333333p+0 0x1.4cccccccccccdp+0 0x1.6666666666666p+0]',
      dtype='<U85')
```

However `np.matrix()` fails to interpret it:

```pycon
>>> np.matrix("[%s %s %s %s]" % (1.1.hex(), 1.2.hex(), 1.3.hex(), 1.4.hex()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/numpy/matrixlib/defmatrix.py", line 142, in __new__
    data = _convert_from_string(data)
  File "/usr/local/lib/python3.9/site-packages/numpy/matrixlib/defmatrix.py", line 26, in _convert_from_string
    newrow.extend(map(ast.literal_eval, temp))
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    0x1.199999999999ap+0
       ^
SyntaxError: invalid syntax
```

My version:
```pycon
>>> np.__version__
'1.19.4'
```

**Comment by eric-wieser** [comment]
It's worth noting that `0x1.199999999999ap+0` is not valid python syntax, and raises `SyntaxError`. The output of `float.hex` is only usable with `float.fromhex`.

> Also the following array of hexes works fine using `np.array()`:

That's not creating an array at all, that's just a single string inside a 0-d Array, hence the `dtype="U..."`

> However `np.matrix()` fails to interpret it:

`np.matrix` is deprecated, I'd recommend not using it.

**Comment by kenorb** [comment]
> `np.matrix` is deprecated, I'd recommend not using it.

`np.matrix` is the only method that I've found (apart of json) that can interpret multidimensional arrays (higher than 1D) from the string correctly, where loads()/loadtxt()/fromstring() and other fails. Related: [How to read numpy 2D array from string?](https://stackoverflow.com/a/35616578/55075).

My case is having file with multidimensional arrays in the text file which needs to be loaded. So wrapping np.array() around np.matrix() works fine, e.g.

```
>>> np.array(np.matrix("[[1.1] [1.2] [1.3] [1.4]]"))
array([[1.1, 1.2, 1.3, 1.4]])
```

However I'd like to load multidimensional arrays from the text file which I've written in the hex format such as this one:

```
>>> np.array(np.matrix("[0x1.3956d40000000p-3 -0x1.81a7620000000p-5 0x1.c5db060000000p-4 0x1.5473460000000p-6 0x1.385f480000000p-3]"))
```

but this generates the SyntaxError.

**Comment by rossbar** [comment]
I agree with @eric-wieser here, especially since the hex float repr isn't valid Python syntax: as pointed out above, this is not something that is works with `np.array` either.
