### ISSUE TITLE
ENH: Polya-gamma distribution

### ISSUE THREAD

**Issue by zoj613** [numpy/numpy#18076]
## Feature

I would like to know if Numpy accepts addition of new distributions since the implementation of the Generator interface. If so, what is the criteria for a particular distribution to be accepted? The reason why i'm asking is because I would like to propose adding the Polya-gamma distribution to numpy, for the following reasons:

1) Polya-gamma random variables are commonly used as auxiliary variables during data augmentation in Bayesian sampling algorithms, which have wide-spread usage in Statistics and recently, Machine learning.
2) Since this distribution is mostly useful for random sampling, it since appropriate to have it in numpy and not projects like scipy [1].
3) The only python/C++ implementation of the sampler available is licensed under GPLv3 which I believe limits copying into packages that choose to use a different license [2].
4) Numpy's random API makes adding the distribution painless.

I have done preliminary work on this by implementing the distribution sampler as decribed in [3]; see: https://github.com/numpy/numpy/compare/master...zoj613:polyagamma .
There is a more efficient sampling algorithm described in a later paper [4], but I chose not to start with that one unless I know it is worth investing time in.

Refs:
[1] https://github.com/scipy/scipy/issues/11009
[2] https://github.com/slinderman/pypolyagamma
[3] https://arxiv.org/pdf/1205.0310v1.pdf
[4] https://arxiv.org/pdf/1405.0506.pdf

**Comment by mattip** [comment]
The NumPy random module is meant to be a bare minimum of distributions while providing the foundation of best-practices SeedSequences and BitGenerators for other packages to build upon. I don't understand why the Poly-gamma distribution is a bad fit for SciPy or for statsmodels?

**Comment by zoj613** [comment]
> The NumPy random module is meant to be a bare minimum of distributions while providing the foundation of best-practices SeedSequences and BitGenerators for other packages to build upon. I don't understand why the Poly-gamma distribution is a bad fit for SciPy or for statsmodels?

Scipy requires much more than random variable sampling. it requires calculating pdfs, cdfs, etc for all parameters in the distribution's support. Therefore not making the Polyagamma a good candidate for inclusion. See [this](https://docs.scipy.org/doc/scipy/reference/dev/contributor/adding_new.html) and [that](https://github.com/scipy/scipy/issues/11009#issuecomment-549520451)

**Comment by zoj613** [comment]
@bashtage would probably give a better answer regarding suitability of inclusion into statsmodels.

**Comment by eric-wieser** [comment]
What is scipy's support like for our new bitgenerator objects?

**Comment by zoj613** [comment]
> What is scipy's support like for our new bitgenerator objects?

I think its mostly supported through the `random_state` parameter in the class constructor and `rvs` methods. One would need to pass a `Generator` instance, which is then used internally to generate variables from the appropriate distribution. See: https://github.com/scipy/scipy/blob/b21b3032df098275b61c6501bdb3fa9ae4c99288/scipy/_lib/_util.py#L190

**Comment by rkern** [comment]
Now that we have C and Cython APIs for drawing uniform numbers from the underlying `BitGenerator`s, we lean against adding more distributions to `Generator`. We fully appreciate that it would reduce the number of dependencies for users, but NumPy maintenance time is a limited resource and the "everything including the kitchen sink" approach has strained that resource. I think we would prefer to see new distributions implemented in external packages first, then consider adding them to `Generator` if that's actually causing problems for people. And even then, popular, standard packages like `scipy` or `statsmodels` (though I can't speak for that project) might be better places.

Notionally, I would not object to have a function for Polya-Gamma sampling in `scipy.stats` without implementing a full `Distribution`; I think the nature and applications of this distribution warrant this. We've done similar things with multivariate distributions before we tried to standardize a common `Distribution`-like interface for them. But `scipy` still depends on `numpy` 1.16, before the new `BitGenerator` interface was added.

I am going to recommend implementing this in a standalone package with an eye to moving it into `scipy.stats` when it bumps up its `numpy` requirement to 1.17+.

**Comment by zoj613** [comment]
> Now that we have C and Cython APIs for drawing uniform numbers from the underlying `BitGenerator`s, we lean against adding more distributions to `Generator`. We fully appreciate that it would reduce the number of dependencies for users, but NumPy maintenance time is a limited resource and the "everything including the kitchen sink" approach has strained that resource. I think we would prefer to see new distributions implemented in external packages first, then consider adding them to `Generator` if that's actually causing problems for people. And even then, popular, standard packages like `scipy` or `statsmodels` (though I can't speak for that project) might be better places.
> 
> Notionally, I would not object to have a function for Polya-Gamma sampling in `scipy.stats` without implementing a full `Distribution`; I think the nature and applications of this distribution warrant this. We've done similar things with multivariate distributions before we tried to standardize a common `Distribution`-like interface for them. But `scipy` still depends on `numpy` 1.16, before the new `BitGenerator` interface was added.
> 
> I am going to recommend implementing this in a standalone package with an eye to moving it into `scipy.stats` when it bumps up its `numpy` requirement to 1.17+.

@rkern Thanks for the insightful comment. I totally understand the concerns with maintenance. After some thought, I agree that maybe it would be best to have it as a seperate package and hopefully get it added in the future to scipy. I will continue development at https://github.com/zoj613/polya-gamma for those interested in using the code or contributing.

**Comment by bashtage** [comment]
@zoj613  You could contribute it to randomgen.  It has a class ExtendedGenerator that has some distributions that are not in NumPy.

**Comment by zoj613** [comment]
> @zoj613 You could contribute it to randomgen. It has a class ExtendedGenerator that has some distributions that are not in NumPy.

Thanks @bashtage , I will be sure to open an issue/pull request once I feel it's ready for a review. I have a question with regards to best practices for applying the bitgenerator lock during sampling. Is it recommended to always use when sampling or just when filling an array with values? It wasn't clear to me just from looking into the numpy source code for the _generator.pyx module.

**Comment by bashtage** [comment]
The lock should always be acquired before calling the underlying bit-generator functions. This is required to thread safety.  If you look through the Generator module and its supporting classes, you will see it is always acquired before anything random is generated.
