### ISSUE TITLE
Claiming wrong rounding error in 2*1/sqrt(2)*1/sqrt(2)=1 when printing real number in vectors

### ISSUE THREAD

**Issue by HenrikBach1** [numpy/numpy#18073]
Hi

Below code sample cannot prove that 

$(|+\rangle + |-\rangle) / \sqrt{2} = 2 * |0\rangle / \sqrt{2} / \sqrt{2}  = |0\rangle$.

That is

``` python
((ket_plus + ket_minus) / np.sqrt(2)) = 2 / np.sqrt(2) / np.sqrt(2) * ket0 = ket0
```

Code:
```python
import numpy as np

ket0 = np.array([[1.], [0.]])
ket1 = np.array([[0.], [1.]])

H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
X = np.array([[0, 1], [1, 0]])

# ket_plus = H @ ket0
ket_plus = np.array([[1],[1]]) / np.sqrt(2)
# ket_minus = H @ ket1
ket_minus = np.array([[1],[-1]]) / np.sqrt(2)

2*1/np.sqrt(2)*1/np.sqrt(2)

ket0
((ket_plus + ket_minus) / np.sqrt(2))
((ket_plus + ket_minus) / np.sqrt(2)) == ket0
```

### Error message:

``` shell
 2*1/np.sqrt(2)*1/np.sqrt(2)
0.9999999999999999 #<----------------------------------- True rounding error
 
 ket0
array([[1.],
       [0.]])
 ((ket_plus + ket_minus) / np.sqrt(2))
array([[1.], #<----------------------------------------------- False shown real number
       [0.]])
 ((ket_plus + ket_minus) / np.sqrt(2)) == ket0
array([[False], #<------------------------------------------- Comparison operator takes above rounding error into account
       [ True]])
```

Above code may also be found at: https://repl.it/@HenrikBach1/Quantum#main.py

### NumPy/Python version information:

repl.it:
``` shell
1.19.1 3.8.5 (default, Jul 20 2020, 19:48:14) 
[GCC 7.5.0]
```

and 

VSC with ms-python.python (v2020.12.424452561): 
``` shell
1.19.0 3.7.8 (default, Jun 30 2020, 18:36:05) 
[GCC 8.3.0]
```

Thank you.

**Comment by eric-wieser** [comment]
I think what you're seeing here is that the default printing behavior is to round in order to not give very long printouts. Have a look at [`np.printoptions`]("numpy.printoptions — NumPy v1.19 Manual" https://numpy.org/doc/stable/reference/generated/numpy.printoptions.html) for how to customize this.

**Comment by HenrikBach1** [comment]
Thank you for your suggestion.

However, setting 'np.set_printoptions(precision=2)' or setting 'precision=9' doesn't seem to have any effect on printing.

**Comment by eric-wieser** [comment]
Does `floatmode="unique"` show the difference?

**Comment by HenrikBach1** [comment]
No difference. Neither single or in combination with precision.
