### ISSUE TITLE
str(ndarray) is 30x times slower than str(ndarray.tolist)

### ISSUE THREAD

**Issue by ArtyomKaltovich** [numpy/numpy#18098]
Hello, I've experience some interesting performance behavior.

### Reproducing code example:

```python
>>> a = np.array([[1, 2], [3, 4]])                                                                                  
>>> a
array([[1, 2],
          [3, 4]])
>>> timeit.timeit(lambda: str(a), number=10000)
0.35753169999998136
>>> timeit.timeit(lambda: str(a.tolist()), number=10000)
0.01220519999969838 
```

It isn't reproduced for 1d arrays, some issues with recursion?

### NumPy/Python version information:
numpy==1.19.4
python==3.8.6 and 3.6.8 (50x times slower) (I don't have any more installed for tests :))
Windows OS

Best Regards and Happy New Year,
Artyom.

**Comment by Dan-Patterson** [comment]
`a = np.array([[1, 2], [3, 4]])

str(a)
'[[1 2]\n [3 4]]'

str(a.tolist())
'[[1, 2], [3, 4]]'`

different representations.

**Comment by ArtyomKaltovich** [comment]
Hello @Dan-Patterson, I agree with you, I just want to notify, the problem is with several dimensions I guess. not with commas)

**Comment by ajinkyajawale14** [comment]
@Dan-Patterson @ArtyomKaltovich @godber @carletes @brentp Hello Guys, I'm a Data Engineer works alot with numpy and pandas, I'd like to pick up this issue and work on it.. kindly approve.. Thanks, Happy new year guys!

**Comment by mattip** [comment]
Hi @ajinkyajawale14. We don't assign issues, everyone is invited to contribute where they can. With that, when you open a PR related to this issue, you should cross-reference it with something like `Fixes gh-18098` or `xref gh-18098` in the PR description to link it back to here so we know someone is working on it.

**Comment by seberg** [comment]
@ArtyomKaltovich could you clarify if this is "interesting performance" or an actual performance issue for you? My first reaction is that yes it is slow (for one it is largely implemented in Python since nice representation is tricky), but that printing is not speed relevant except in a few exceedingly rare scenarios (I cannot really think of one, outside maybe testing).

**Comment by ArtyomKaltovich** [comment]
Hello, no this is not an issue for me, I just wanted to notify you, because I find it interesting. Why there is so big difference? :)

You are right, it can be a problem in case of doctesting and input-output, actually, every script needs to output something, but we spend more time on calculation and even importing numpy, so it isn't bottleneck.:)

**Comment by Dan-Patterson** [comment]
Timing differences for things that yielded the same result might be interesting.  Close?
