### ISSUE TITLE
BUG: Numpy array assignment gives copy instead of array reference

### ISSUE THREAD

**Issue by msjd78** [numpy/numpy#18094]
See the following screen. Can someone describe why array is being copied instead of creating reference?

![Screenshot from 2020-12-30 14-03-40](https://user-images.githubusercontent.com/40379607/103341254-3f2ff200-4aa8-11eb-8cbc-bd181d7f267d.jpg)

**Comment by kshitij12345** [comment]
I think it is copying because you are doing
```
b = b * 3 # b * 3 creates a temp output and binds the temp to variable.
```

Instead you should do,
```
b *= 3
```

This will multiply in-place and the change will be reflected in `a`.

Sample
```python
>>> a = np.array([1, 2])
>>> b = a
>>> b *= 3
>>> b
array([3, 6])
>>> a
array([3, 6])

```

**Comment by msjd78** [comment]
Dear Kshitij,
Thanks for reply. Definitely I am missing something. 
As per definition below, my simple code should work (as b=b*3 => b*=3). Your given technique does the job, but why not mine?

"By default, NumPy does not create a copy of an array when you reference the original array variable using the = assignment operator. Instead, it simply points the new variable to the old variable, which allows the second variable to make modification to the original variable - even if this is not your intention."
