### ISSUE TITLE
need in-built rolling window function in numpy

### ISSUE THREAD

**Issue by enigdata** [numpy/numpy#18113]
Can we have inbuilt rolling window function in numpy, just as in pandas? pd.rolling(...)

**Comment by eric-wieser** [comment]
Will https://numpy.org/devdocs/reference/generated/numpy.lib.stride_tricks.sliding_window_view.html do what you're after (will be part of 1.20.0)

**Comment by bashtage** [comment]
Probably can be closed as answered. Bottleneck provides most basic rolling window functions.

**Comment by seberg** [comment]
Right, the docs of `sliding_window_view` even link to bottleneck :); Closing.
