### ISSUE TITLE
`array()` of nested empty list freezes Python

### ISSUE THREAD

**Issue by OverLordGoldDragon** [numpy/numpy#18117]
```python
import numpy as np
ls = []
_ = [ls.append(ls) for _ in range(2)]
np.array(ls)
```
Second nest sufficient to make Python unresponsive and un-interruptible. Reproduced both from IPython, Anaconda Powershell Prompt console, and when running `.py` as script.

Numpy v1.19.4, Python 3.7.7, Windows 10.

**Comment by eric-wieser** [comment]
Note this will try to allocate an array of `2**32` elements of type `object`, which may eventually succeed in systems with 32GB of memory.

Nevertheless, we should ideally respond to ctrl+C here.

**Comment by seberg** [comment]
We could add a `PyInterrupt_Occurred()` (if that was the command) check every time we entering another level of sequence unpacking.  That should be easy to do for someone familiar with C-API and not scared of digging into the code.
