### ISSUE TITLE
"ValueError: source code string cannot contain null bytes" 

### ISSUE THREAD

**Issue by caozhen-alex** [numpy/numpy#18125]
## Description
"ValueError: source code string cannot contain null bytes" raised while importing numpy. Strangely, numpy is imported perfectly in terminal end.

<img width="1021" alt="Screenshot 2021-01-06 at 1 57 22 AM" src="https://user-images.githubusercontent.com/26409810/103681570-9ced9e00-4fc2-11eb-9092-c36a3358040a.png">
<img width="528" alt="Screenshot 2021-01-06 at 1 57 43 AM" src="https://user-images.githubusercontent.com/26409810/103681582-a0812500-4fc2-11eb-8cf1-42bacbab08d6.png">

## Context
- Operating System and version: macOS Big Sur
- Browser and version: Version 14.0.2 (16610.3.7.1.9)
- JupyterLab version: 2.2.6
- numpy version: 1.19.2
- python version: 3.9.1
- miniconda version: 4.9.2

**Comment by seberg** [comment]
Considering that this is a year old without any comments: closing.  Something must hae been wrong with the setup (multiple python/numpy versions? Strange PYTHONPATH, a bad install)?  We are unlikely to be able to help even if it is still an open problem.
