### ISSUE TITLE
.any() not returning Boolean for object dtype

### ISSUE THREAD

**Issue by rmwenzel** [numpy/numpy#18129]
### Reproducing code example:

.any() sometimes isn't returning Booleans. The code

```python
import numpy as np
arr = np.array([[1, 's'], [np.nan, 't']]).astype(object)
arr.any(axis=1)
```
returns

```python
['1' 'nan']
```

Same for 1-d arrays 

```python
import numpy as np
arr = np.array(['s', 1], dtype=object)
arr.any()
```
returns 

```python
arr = np.array(['s', 1], dtype=object)
arr.any()
```

Note for the 2-d array the first column is returned, for the 1-d array the first element.

### NumPy/Python version information:

1.18.5 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]

**Comment by rkern** [comment]
I think that's how it has always behaved. `np.any()` is essentially `np.logical_or.reduce()`, and `np.logical_or()` on object arrays follows the behavior of the `or` operator, returning the first of its operands that is truthy, not a `bool`. `np.any()` predates the builtin `any()`, so the difference is unfortunate, but not a bug.

**Comment by rmwenzel** [comment]
@rkern thanks. The behavior surfaced using `pandas.DataFrame.any()` https://github.com/numpy/numpy/issues/18129 and expectations were based on their docs. You mentioned a difference between `np.any()` and built-in `any()` is this the difference between `np.any(arr)` and `arr.any()`? Both seem to give the same result.

```python
arr = np.array(['s', 1], dtype=object)
np.any(arr)
```
also returns `s`.

**Comment by rkern** [comment]
No, I meant the Python builtin `any()`. It came into the language after Numeric (numpy's predecessor) had the function `Numeric.any()` (now `numpy.any()`). If the builtin `any()` had existed earlier (with its `bool`-returning behavior), we probably would have made `Numeric.any()` match.

**Comment by rkern** [comment]
Actually, that timing may not be true. Faulty memory.

**Comment by rkern** [comment]
I think they came in with `numpy`, which was released a little before Python 2.5, the first release with the `any()` and `all()` builtins. So a closer-run thing than I remember. We might also have had `any()` and `all()` in the Numeric-based `scipy` earlier than that, though it's more effort than I think it's worth to do the code archaeology to figure out.

**Comment by rmwenzel** [comment]
I see, thanks for clarifying, didn't know Python's built-in s`.any()` and `.all()`. Since this isn't a bug, I think it makes sense to close issue.

**Comment by rmwenzel** [comment]
There's open issue already #4352
