### ISSUE TITLE
changing the prototype of stack function

### ISSUE THREAD

**Issue by DavidePatria** [numpy/numpy#18132]
https://github.com/numpy/numpy/blob/92ebe1e9a6aeb47a881a1226b08218175776f9ea/numpy/core/shape_base.py#L358-L434

the doc should be written as the one of the concatenate function, as

np.stack((a1,a2,...),axis=0,out=none))

instead of using "arrays" to mean "(a1,a2,...)"

**Comment by eric-wieser** [comment]
Can you elaborate on the change you're suggesting? Are you talking about the `parameters` section? The `examples` section?

**Comment by DystopianLphant** [comment]
I'm talking about 
`def stack(arrays, axis=0, out=None): `

the definition is not consistent with other numpy functions like concatenate. It took me a few minutes to realise the use was the same. not a big deal of course, if I looked at the examples I would have realised it, but I think it would be better if it were consistent over all functions

**Comment by eric-wieser** [comment]
What are you suggesting that line should be instead?

**Comment by DystopianLphant** [comment]
`numpy.concatenate((a1, a2, ...), axis=0, out=None)`
like this one

**Comment by eric-wieser** [comment]
Sorry, but we have to use legal python syntax:
```
>>> def stack((a1, a2, ...), axis=0, out=None): pass
  File "<ipython-input-62-524e6e6c5d59>", line 1
    def stack((a1, a2, ...), axis=0, out=None): pass
              ^
SyntaxError: invalid syntax
```

**Comment by seberg** [comment]
The concatenate docstring is a bit weird, because its signature line comes from C and is just  a string, but actually does include the invalid syntax. I admit it is probably nicer to read, so I am not sure we have to change it.

**Comment by seberg** [comment]
Going to close, it isn't worth to keep this potential documentation improvement open if it isn't clear how to improve it.
