### ISSUE TITLE
numpy wants nonexistent numpy/core/src

### ISSUE THREAD

**Issue by limburgher** [numpy/numpy#18135]
See https://bugzilla.redhat.com/show_bug.cgi?id=1913810, prevents building sympy.

**Comment by charris** [comment]
Wasn't there a fix for this? See #18100.

**Comment by limburgher** [comment]
So it'll be fixed in rc3?

**Comment by charris** [comment]
> So it'll be fixed in rc3
 
Hopefully. We are currently waiting on pyarrow, so I might put one out in a week or two, especially if the OpenBLAS compiler problems currently reported on AARCH64 get addressed.

**Comment by limburgher** [comment]
Ok, I'll keep an eye out.

**Comment by seiko2plus** [comment]
Thank you for your report.
This bug has been reported by #18092, and already resolved by #18100 as @charris mentioned.
