### ISSUE TITLE
random.Generator.shuffle() warns about ragged nested sequences

### ISSUE THREAD

**Issue by cifkao** [numpy/numpy#18142]
With a "ragged nested sequence", `Generator.shuffle()` triggers a warning in `asarray()`. This is unexpected, since I'm only trying to shuffle the sequence, not convert it to a NumPy array.

This only happens with `Generator` and not with `random.shuffle()`.

It is unclear how to call `shuffle()` without triggering this warning.

### Reproducing code example:

```python
import numpy as np
seq = [[], [], 1]
np.random.default_rng().shuffle(seq)
print(seq)
```

### Error message:

/ldaphome/ocifka/venv/spe/lib/python3.7/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)

### NumPy/Python version information:

1.19.4 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]

**Comment by cifkao** [comment]
This actually seems to be triggered by `np.ndim`. This is called by `Generator.shuffle` in order to support the `axis` parameter.

It seems like `len()` should be used instead for non-NumPy sequences when `axis == 0`.

**Comment by seberg** [comment]
Since the function is documented to support sequences, I agree that this was an oversight. Technically a regression in 1.18 (the API was new in 1.17 though).
