### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by ernestum** [numpy/numpy#18159]
## Documentation

The numpy documentation at https://numpy.org/doc is down (I get an 404 error)

**Comment by rgommers** [comment]
Thanks. We know, working on it in https://github.com/numpy/numpy.github.com/pull/1

**Comment by ernestum** [comment]
Oh sorry for the duplicate then

**Comment by rgommers** [comment]
no worries, I'll leave this open till it's fixed, or someone else will open a new issue

**Comment by mattip** [comment]
Should be working now. Please reopen if something is still not working.
