### ISSUE TITLE
bool_ no longer a dtype in 1.20.rc2

### ISSUE THREAD

**Issue by Harmenius** [numpy/numpy#18165]
This is my first bug report so please bear with me if I made a mistake or left out some vital information.
When upgrading from `numpy==1.18.1` to `numpy==1.20.rc2`, one of my unit tests broke. It was running the equivalent of  
```python
import dask.dataframe as dd
data = """timestamp,string,boolean,integer
2020-11-09 13:50:31.488 UTC,words,False,12"""
with open("data.csv", "w") as f:
    f.writelines(data)
dd.read_csv("data.csv", assume_missing=True)
```

I don't know if you are already aware of this issue (searching did not turn up anything) or if the pandas developers are aware of this already and will change their implementation.

This happened both on my development machine as well as in a docker image `docker.io/library/python:3.7.5-slim` (used for running the unit tests)

### Reproducing code example:

```python
import numpy as np
print(isinstance(np.bool_, type(np.dtype)))
```

This breaks pandas/core/dtypes/cast.py:construct_1d_arraylike_from_scalar

```python
import numpy as np
from pandas.core.dtypes.cast import construct_1d_arraylike_from_scalar
construct_1d_arraylike_from_scalar(False, 10, np.bool_)
```

### Error message:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/hprins/[redacted]/venv/lib/python3.8/site-packages/pandas-0.25.3-py3.8-macosx-10.15-x86_64.egg/pandas/core/dtypes/cast.py", line 1233, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

### NumPy/Python version information:
Broken:
1.20.0rc2 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]

Working:
1.18.1 3.7.8 (default, Jul  8 2020, 14:18:28) 
[Clang 11.0.3 (clang-1103.0.32.62)]

**Comment by seberg** [comment]
Seems like a fixed pandas bug, the line `isinstance(np.bool_, type(np.dtype))` did change behaviour, but doesn't make much sense to begin with (if anything, it should be `isinstance(np.bool, np.generic)`).  Unfortunately, the only solution is probably to upgrade pandas as well (I only checked that 1.0 doesn't have the fix yet).

**Comment by Harmenius** [comment]
Right, so I was using incompatible version and can fix it by downgrading (which I did) or properly upgrading (which I will do). In the future, I suppose I should check pandas before posting a bug report.
Thanks! Closing.

**Comment by seberg** [comment]
Yeah, frankly, it would be nicer if a year old pandas would work without issues. But yeah, generally it is better if the base package (NumPy) is not (too much) newer than the downstream (pandas).
For NumPy the usual safe bet is that ~1 year newer should be fine (i.e. you may see warnings but everything works), this is an unfortunate exception.
