### ISSUE TITLE
the `equal` ufunc raises an exception where `==` works fine

### ISSUE THREAD

**Issue by Stigjb** [numpy/numpy#18171]
### Reproducing code example:

```python
import numpy as np

l = [list('foo'), list('bar'), list('baz')]

np.array(l) == 'a'  # Works
np.equal(l, 'a')  # Error!
np.equal(l, 'a', dtype='object')  # Works
```

**Expectation**: all three expressions should return the same value:

```
[[False False False]
 [False  True False]
 [False  True False]]
```

### Error message:

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    np.equal(l, 'a')
numpy.core._exceptions.UFuncTypeError: ufunc 'equal' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> dtype('bool')
```

### NumPy/Python version information:

- Numpy 1.19.4
- Python 3.8.7

---

**EDIT: At this time, string and bytes *are* supported.  Supporting `np.equal` and `np.not_equal` for structured dtypes would be a worthwhile addition.  But possibly somewhat larger (due to complexity), project.**

**Comment by WarrenWeckesser** [comment]
After initally tagging this as a bug, I switched it to an enhancement request.  None of the [comparison ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html#comparison-functions) handle the flexible dtypes (i.e. `bytes` and `str`).

```
In [61]: l = [list('foo'), list('bar'), list('baz')]

In [62]: np.array(l) <= 'a'
Out[62]: 
array([[False, False, False],
       [False,  True, False],
       [False,  True, False]])

In [63]: np.less_equal(l, 'a')
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-63-725027435d3b> in <module>
----> 1 np.less_equal(l, 'a')

UFuncTypeError: ufunc 'less_equal' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> dtype('bool')
```

Neither do `maximum` and `minimum`.

**Comment by seberg** [comment]
Note that the machinery now exists to make them handle them as ufuncs more reasonable, and it would be a very nice project for someone to move all of the comparison (including `==` itself) to use it!

**Comment by seberg** [comment]
Will be fixed by gh-21041 (although structured dtypes will remain as an odd one out for the moment).

**Comment by seberg** [comment]
Closing, as mentioned above, the string issue is fixed.
