### ISSUE TITLE
Unable to compile code using Numpy 1.16+ for Python 2.7

### ISSUE THREAD

**Issue by VisionaryMind** [numpy/numpy#18188]
I am aware that everyone is porting their code over to Python3 and, for the most part, keeping their NumPy dependency at 1.16 and above, however this is causing problems for libraries such as OpenCV 4.5 on Ubuntu 18.04 systems with ROS Melodic. Specifically, this effects NVIDIA edge devices (Xavier, Jetson, etc.), but I presume it will also be relevant for other platforms that, for whatever reason, have a requirement to stay on Python 2.

When attempting to compile Python bindings for OpenCV 4.5.1, we run into a well-known error stemming from an attempt to call import_array() from the __multiarray_.h. Here is the code that compiles for Python 3 but not for Python 2:

`#if defined(CV_PYTHON_3)
// === Python 3

static struct PyModuleDef cv2_moduledef =
{
    PyModuleDef_HEAD_INIT,
    MODULESTR,
    "Python wrapper for OpenCV.",
    -1,     /* size of per-interpreter state of the module,
               or -1 if the module keeps state in global variables. */
    special_methods
};

PyMODINIT_FUNC PyInit_cv2();
PyObject* PyInit_cv2()
{
    import_array(); // from numpy
    PyObject* m = PyModule_Create(&cv2_moduledef);
    if (!init_body(m))
        return NULL;
    return m;
}

#else

//=== Python 2
PyMODINIT_FUNC initcv2();
void initcv2()
{
    import_array(); // from numpy
    PyObject* m = Py_InitModule(MODULESTR, special_methods);
    init_body(m);
}

#endif`

When attempting to build the code that contains this snippet, the following error is thrown:

`In file included from /usr/include/sched.h:29:0, from /usr/include/pthread.h:23, from /usr/include/aarch64-linux-gnu/c++/7/bits/gthr-default.h:35, from /usr/include/aarch64-linux-gnu/c++/7/bits/gthr.h:148, from /usr/include/c++/7/ext/atomicity.h:35, from /usr/include/c++/7/bits/basic_string.h:39, from /usr/include/c++/7/string:52, from /usr/include/c++/7/stdexcept:39, from /usr/include/c++/7/array:39, from /home/visionarymind/Downloads/opencv/modules/core/include/opencv2/core/cvdef.h:738, from /home/visionarymind/Downloads/opencv/modules/core/include/opencv2/core/cvstd.hpp:51, from /home/visionarymind/Downloads/opencv/modules/core/include/opencv2/core/utils/configuration.private.hpp:8, from /home/visionarymind/Downloads/opencv/modules/python/src2/cv2.cpp:35: /home/visionarymind/Downloads/opencv/modules/python/src2/cv2.cpp: In function ‘void initcv2()’: /home/visionarymind/Downloads/opencv/modules/python/src2/cv2.cpp:2137:5: error: return-statement with a value, in function returning 'void' [-fpermissive] import_array(); // from numpy ^ /home/visionarymind/Downloads/opencv/modules/python/src2/cv2.cpp:2137:5: error: expected ‘;’ before ‘__null’ import_array(); // from numpy`

We have tried removing NumPy and installing with specific version 1.13.2, but the error remains. I understand this is not a problem related to NumPy directly, but there are many developers running into this problem as a result of being constrained to the platforms I list above, so a workaround would be very helpful.

How might the OpenCV snippet above be modified so that this error is not thrown?

**Comment by charris** [comment]
@VisionaryMind The NumPy 1.16.x series was the last to support Python 2.7 and most of the shims have been stripped out. Is there a problem using 1.16?

**Comment by VisionaryMind** [comment]
> @VisionaryMind The NumPy 1.16.x series was the last to support Python 2.7 and most of the shims have been stripped out. Is there a problem using 1.16?

Using 1.16 is what caused this issue. We then downgraded to 1.13.2, but the issue remains.

**Comment by charris** [comment]
The relevant code is
```
#if PY_VERSION_HEX >= 0x03000000
#define NUMPY_IMPORT_ARRAY_RETVAL NULL
#else
#define NUMPY_IMPORT_ARRAY_RETVAL
#endif

#define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }

#define import_array1(ret) {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return ret; } }

#define import_array2(msg, ret) {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, msg); return ret; } }
```
Looks to me like `NUMPY_IMPORT_ARRAY_RETVAL` is not being correctly defined for Python 2.7 for some reason.

**Comment by VisionaryMind** [comment]
Yes, this was my original thought, but putting a NULL after RETVAL for Python 2 does not resolve the issue.

**Comment by charris** [comment]
It looks like it _is_ returning NULL, and it shouldn't be. It should just be `return;`, i.e., no return value.

**Comment by rgommers** [comment]
Question was answered, so hopefully problem is resolved. I'll close this issue since there's nothing to fix in NumPy. More comments to help other Python 2.7 users are very welcome of course.
