### ISSUE TITLE
mypy --strict error when importing numpy.typing

### ISSUE THREAD

**Issue by pmav99** [numpy/numpy#18190]
`mypy --strict` disables `implicit_reexport`. Consequently mypy throws an error when trying to import `ArrayLike` and `DTypeLike` from `numpy.typing`.

### Reproducing code example:

```python
from numpy.typing import ArrayLike
```

### Error message:

```
$ mypy --strict foo.py
foo.py:1: error: Module 'numpy.typing' has no attribute 'ArrayLike'
Found 1 error in 1 file (checked 1 source file)
```

### NumPy/Python version information:

```
$ python -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.20.0rc2 3.8.6 (default, Dec 18 2020, 13:50:46) 
[GCC 10.2.0]

$ mypy --version
mypy 0.790
```

### Possible workarounds

I guess that the reason why this happens is than `__all__` is not set when on `TYPE_CHECKING` mode:
https://github.com/numpy/numpy/blob/af8e67c4fd368bae710b01f32611b10dfab02b61/numpy/typing/__init__.py#L156-L165

If setting `__all__` is not possible, a workaround might be to "explicitly reexport" the objects using something this:

``` python
from ._array_like import ArrayLike as ArrayLike
from ._dtype_like import DTypeLike as DTypeLike
```

It might also be possible to enable implicit reexports for this specific module using the numpy mypy plugin.

**Comment by BvB93** [comment]
> If setting `__all__` is not possible, a workaround might be to "explicitly reexport" the objects using something this:
>
> ``` python
> from ._array_like import ArrayLike as ArrayLike
> from ._dtype_like import DTypeLike as DTypeLike
> ```

Nice and simple, I feel that this is approach would neatly fix the entire issue.
Would you be willing to submit a PR?

**Comment by pmav99** [comment]
Sure no problem with that. Which style is preferable?

``` diff
- from ._array_like import _SupportsArray, ArrayLike
+ from ._array_like import _SupportsArray, ArrayLike as ArrayLike
 from ._shape import _Shape, _ShapeLike
- from ._dtype_like import _SupportsDType, _VoidDTypeLike, DTypeLike
+ from ._dtype_like import _SupportsDType, _VoidDTypeLike, DTypeLike as DTypeLike
```

vs

``` diff
- from ._array_like import _SupportsArray, ArrayLike
+ from ._array_like import _SupportsArray
+ from ._array_like import ArrayLike as ArrayLike
 from ._shape import _Shape, _ShapeLike
- from ._dtype_like import _SupportsDType, _VoidDTypeLike, DTypeLike
+ from ._dtype_like import _SupportsDType, _VoidDTypeLike
+ from ._dtype_like import DTypeLike as DTypeLike

```

**Comment by BvB93** [comment]
Personally I prefer the first one.
Feel free to use a (parenthesized) multi-line import if the statement becomes too long.
