### ISSUE TITLE
overflow during numpy import

### ISSUE THREAD

**Issue by MaduxCaster** [numpy/numpy#18202]
Hello,

I meet the following unpleasant behavior when using numpy version 1.19.2 with anaconda, on linux centos 7.6.
Numpy generate an overflow when it is imported, in core/getlimits.py, line 161: 
        huge_f128 = (ld(1) - epsneg_f128) / tiny_f128 * ld(4)
        
Most of time, it is quiet. But if something has enabling overflow trap before, this can lead to a crash.
So importing depend on what had happen before.

For example, let us consider a simple C-coded library:
```
// my_functions.c
#include <fenv.h>    // for FE_OVERFLOW
#include <signal.h>  // for SIGFPE
#include <stdio.h>   // for printf()
#include <stdlib.h>  // for exit()
void handler(int signum)
{
   printf("Error, overflow detected !!\n") ;
   exit(-1) ;
}
void enable_overflow_trap(void)
{
   printf( "Start overflow trap...\n" ) ;
   signal( SIGFPE, handler) ;
   feenableexcept( FE_OVERFLOW ) ;
}
// end of my_functions.c
```

This file is compiled with gcc (system one, so 4.8.5) with following command :
`gcc -fPIC -shared -o my_functions.so  my_functions.c`

Then, in a python program, if I first enable overflow trap before importing numpy, I have a crash. Following script :
```
import ctypes
import os
my_functions = ctypes.CDLL( os.path.abspath("my_functions.so") )
my_functions.enable_overflow_trap()
import numpy
print("Normal end")
```
leads to :
```
Start overflow trap...
Error, overflow detected !!
```

I can go around this behaviour by importing numpy first. But sometimes, it is difficult to change if I don't have enough permissions on scripts. It can also be difficult to detect if it is inside other programs. I first met this behaviour by loading a great C/C++ library, then importing matplotlib (which import numpy). Crash was detected inside the C/C++ library during matplotlib import, which was disturbing.

I am not sure of what append in numpy file core/getlimits.py. But I can imagine fix this behaviour with one of the following solutions :
- disable fpe trap when numpy may generate some, with something equivalent to C functions feholdexcept/feclearexcept/feupdateenv for example,
- modify line 157:
```
    epsneg_f128 = exp2(ld(-113))
```
by something identical to like line 184 :
```
    epsneg_f128 = exp2(ld(-64))
```
- modify line 161:
```
        huge_f128 = (ld(1) - epsneg_f128) / tiny_f128 * ld(4)
```
by
```
        huge_f128 = (ld(1) - epsneg_f128) / tiny_f128 * ld(3.9)
```
Or something else...

However, I don't know if it is an expected behaviour, but is is unpleasant.

Thanks for your attention.

Raphaël

**Comment by MaduxCaster** [comment]
Perhaps a better solution could be to replace line 157:
    epsneg_f128 = exp2(ld(-113))
by something like:
    if( ld(1)!=ld(1)-exp2(ld(-113)) ):
        epsneg_f128 = exp2(ld(-113))
    elif( ld(1)!=ld(1)-exp2(ld(-64)) ):
        epsneg_f128 = exp2(ld(-64))
    elif( ld(1)!=ld(1)-exp2(ld(-53)) ):
        epsneg_f128 = exp2(ld(-53))
    else:
        raise Exception("Problem with longdouble")

**Comment by mattip** [comment]
This is not a problem localized to import, right? If someone uses numpy and happens to get an overflow error, NumPy (or any well-behaved library) internally detect that and converts the value to a `+float('inf')` or `-float('inf')` without a signal handler. We could consider adding a signal handler of our own, but that just seems like an arms race: whoever wants to detect this situation will just invent a better way to work around our mask. When would a user of scientific python want to trap overflow signals that may naturally occur in mathematical calculations?

**Comment by MaduxCaster** [comment]
I think that what to do with an overflow is user dependant. Some people may want use it as inf, other should stop the code with an error if overflow appears because it must not appear.
The question could be "Is it an expected behaviour that an overflow occurs ?" During an application run, I think it is application (user and/or developer) dependant. During a library importation, I would answer no it isn't.

**Comment by emckee2006** [comment]
I get a similar issue (pasted below). How can I decide what to do with the issue if I can't even import the library? What do I need to do to be able to use the library?

Python 3.9.5 (default, Jun  4 2021, 19:08:14) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-55)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mckeee1/newsys/lib/python3.9/site-packages/numpy/__init__.py", line 218, in <module>
    core.getlimits._register_known_types()
  File "/home/mckeee1/newsys/lib/python3.9/site-packages/numpy/core/getlimits.py", line 214, in _register_known_types
    float_dd_ma = MachArLike(ld,
  File "/home/mckeee1/newsys/lib/python3.9/site-packages/numpy/core/getlimits.py", line 51, in __init__
    self.precision = int(-log10(self.eps))
OverflowError: cannot convert longdouble infinity to integer

**Comment by MaduxCaster** [comment]
Hello emckee2006,
The easiest way I have found to go around this problem is to import numpy first, and the library which change overflow management at the end. Then, the numpy overflow is ignored and I'm able to work. Perhaps it could also work for you.
Raphaël

**Comment by emckee2006** [comment]
I simply open python3 and type "import numpy". There isn't anything else
imported...

**Comment by mattip** [comment]
@emckee2006 what OS, where did you get python/numpy? Are you running inside a docker or other virtualization?

**Comment by emckee2006** [comment]
Compiled python3 from the official sources and installed numpy via pip. I
included a screen capture of the error on my initial post which I think has
my compiler and OS version (yes, it is rather old). I'm not in front of the
system right now, or I'd copy and paste the specs here.

**Comment by seberg** [comment]
Closing, I think this must be worked around by the users who set FPE errors to fail, seeh also gh-20504 where workaround were used on the user-side.  NumPy relies on flags, if someone finds a way to work around it in the import, I am happy to review/merge it.  But I just don't see it worthwhile (and think it is likely not easy).
