### ISSUE TITLE
[np.random] shuffle is not compatible with pytorch tensor

### ISSUE THREAD

**Issue by cdluminate** [numpy/numpy#18206]
When shuffling a pytorch tensor with `numpy.random.shuffle`, incorrect result will be produced with 100% (so far) chance.

### Reproducing code example:

```python
import torch as th
import numpy as np

N = 10
x = th.arange(N)
print(x)
np.random.shuffle(x)
print(x)
assert(len(set(x.tolist())) == N)
```

### Error message:

```
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 2, 1, 3, 4, 6, 3, 3, 9])
Traceback (most recent call last):
  File "x.py", line 9, in <module>
    assert(len(set(x.tolist())) == N)
AssertionError
```

In the shuffled result, `0` and `3` occured twice, which is clearly problematic.

### NumPy/Python version information:

numpy '1.18.5' through anaconda.

See also: https://github.com/pytorch/pytorch/issues/50880

**Comment by rkern** [comment]
I've added some comments on pytorch/pytorch#50880

I suspect that we'll need input from both communities to properly resolve this, so I apologize to all for the bifurcated discussion.

**Comment by rkern** [comment]
@rgommers and I have discussed this on the pytorch issue and converged on some recommendations:

- Warn if the object is not an `ndarray` or a `MutableSequence`. Most of the new array types that will be problematic to `shuffle()` won't support `MutableSequence`. And those are more likely than custom objects that would work okay to `shuffle()` but, for whatever reason, don't declare that they are `MutableSequence`s. We can evaluate later if this should turn into a deprecation and eventual `raise`.
- Change the type description from `array_like` to something that is more explicit. `array_like` implies that the object is converted to an `ndarray`, which is not the case for `shuffle()`.

**Comment by rgommers** [comment]
Thanks @rkern. 

> @charris charris added this to the 1.20.0 release milestone 14 hours ago 

@charris would indeed be nice to take this along, the change should not require an RC3 I'd think. I'm happy to submit a PR this weekend - is Sunday in time?

**Comment by charris** [comment]
Arrow tagged 3.0.0 Monday, but a new pyarrow isn't up on PyPI yet, so Sunday will be fine. I'm planning on making the 1.20.0 release the weekend after this.

**Comment by rgommers** [comment]
Thanks. Fix in gh-18211.
