### ISSUE TITLE
Compiler note in ppc64le CI testing.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#18220]
See https://travis-ci.com/github/numpy/numpy/jobs/474759559. The ~warning~ note is
```
note: the ABI of passing aggregates with 16-byte alignment has changed in GCC 5
```
The note shows up for long double types, mostly in the sorting routines. Anyone know why or if it is significant? The tests usually pass.

**Comment by seiko2plus** [comment]
> The note shows up for long double types, mostly in the sorting routines

According to the mail archive of [gcc/msg00634](https://gcc.gnu.org/legacy-ml/gcc-patches/2014-07/msg00634.html), ABI change affects to:

>  passing a struct by value that is
>   * not a float/vector special case, and
>   * has a size of 1, 2, 4, 8, or 16 bytes, and
>   * has an alignment requirement of 16 bytes or more
>  [ Not *all* these cases will see change, but all cases that change
>  will share these properties.  ]

> Anyone know why or if it is significant? The tests usually pass.

We can just suppress the ABI warnings through CLI `-Wno-psabi` or `#pragma`. ABI changes cause incompatible binaries with older versions of GCC e.g. `GCC 4.9`.

**Comment by seberg** [comment]
I'll assume that this has become irrelevant with passage of time.
