### ISSUE TITLE
np.vecterize interaction with max infers wrong otype

### ISSUE THREAD

**Issue by AlsonYang** [numpy/numpy#18239]
When np.vecterize is used to wrap function that utlize the python default max function, even if the input dtype is 'float', the output dtype is still 'int'. it surprisingly works fine with the min function. 

In the code below, df_test['duration'] returns int array by applying compute_delinquent_duration function. The other two implementations using pandas or map both return the right type as float. 

I know with np.vectorize, I can use the function argument otypes=np.float to force output to be float, but I think the default behaviour could cause unexpected behaviour if users are not aware of this issue. 

### Reproducing code example:

```python
import numpy as np
import pandas as pd

# bad --> interaction of np.vectorize with max return int
def compute_delinquent_duration(arrears_months):
    return max(arrears_months - 3.1, 0) # return Int --> bad
#    return min(arrears_months - 3.1, 0) # return float --> good
compute_delinquent_duration = np.vectorize(compute_delinquent_duration)

# good --> return float
def compute_delinquent_duration2(row):
    return max(row['arrears_months'] - 3.1 ,0)
  
# good --> return float
def compute_delinquent_duration3(arrears_months):
    return max(arrears_months - 3.1 ,0)

df_test = pd.DataFrame(columns = ['arrears_months'], data = [3,3.1,4.3, 4.1, 5]) # return int for compute_delinquent_duration
# df_test = pd.DataFrame(columns = ['arrears_months'], data = [4.2, 3,4, 4, 5]) # return float for compute_delinquent_duration

df_test['duration'] = compute_delinquent_duration(df_test['arrears_months'])
df_test['duration2'] = df_test.apply(compute_delinquent_duration2, axis = 1)
df_test['duration3'] = list(map(compute_delinquent_duration3, df_test['arrears_months']))
print(df_test)
print(df_test.dtypes)
```

### Error:
No error message, but wrong return type. 

### output:
   arrears_months  duration  duration2  duration3
0             3.0         0        0.0        0.0
1             3.1         0        0.0        0.0
2             4.3         1        1.2        1.2
3             4.1         0        1.0        1.0
4             5.0         1        1.9        1.9

### NumPy/Python version information:
1.18.2 3.7.6 (default, Dec 30 2019, 19:38:28)

**Comment by seberg** [comment]
Seems correct to me, in the sense that `max(..., 0)` *can* (and does in the test run) return an integer and it is entirely possible for you to ensure that it does not.  In many cases defining `otypes` may be a good thing to ensure this in any case.

**Comment by AlsonYang** [comment]
In the output, the columns 'duration' is the np.vectorize implementation, and 'duration2' and 'duration3' are pd.apply and map implementation. I know specifying otypes is good practice, but I doubt most of the users would not do it. 

Without specifying otypes, the np implemention gives diff result than the other implementations, which users might not aware, as in the arrears_months columns = [3, 3.1, 4.3, 4.1, 5] is defined to be float, while using float array in an operation returns int array is really unexpected behavior. 

Although it's probably not necessary, but align the outcome of one implementation with other implementations (especially map is the default python function), could really be beneficial to the users.

**Comment by AlsonYang** [comment]
> Seems correct to me, in the sense that `max(..., 0)` _can_ (and does in the test run) return an integer and it is entirely possible for you to ensure that it does not. In many cases defining `otypes` may be a good thing to ensure this in any case.

In the output, the columns 'duration' is the np.vectorize implementation, and 'duration2' and 'duration3' are pd.apply and map implementation. I know specifying otypes is good practice, but I doubt most of the users would not do it.

Without specifying otypes, the np implemention gives diff result than the other implementations, which users might not aware, as in the arrears_months columns = [3, 3.1, 4.3, 4.1, 5] is defined to be float, while using float array in an operation returns int array is really unexpected behavior.

Although it's probably not necessary, but align the outcome of one implementation with other implementations (especially map is the default python function), could really be beneficial to the users.

**Comment by seberg** [comment]
You return `max(-0.1, 0)` which *is* an integer for the first value, and that is how it is designed to work; maybe that can be changed, but I doubt it, you always have similar issues if the type is fixed at some point.
