### ISSUE TITLE
Need to remove easy_install usage from doc/Makefile

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#18246]
There's still an `easy_install` usage in that Makefile, which gets invoked via `make dist`. That is going to break in the near future; `easy_install` was removed from `setuptools` three days ago.

Here's a stab at a fix, not quite right though because we shouldn't be invoking `pip` - it is much smarter now so when you point it at a wheel to install and that wheel provides `numpy`, that messes with the list of packages it knows it already has installed. Maybe we should just manually unzip the wheel instead.

```
diff --git a/doc/Makefile b/doc/Makefile
index 68d496389e..11c4145c95 100644
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -65,12 +65,7 @@ gitwash-update:
 #------------------------------------------------------------------------------
 
 # Build the current numpy version, and extract docs from it.
-# We have to be careful of some issues:
-#
-# - Everything must be done using the same Python version
-# - We must use eggs (otherwise they might override PYTHONPATH on import).
-# - Different versions of easy_install install to different directories (!)
-#
+# Note: be careful here to use the same Python version
 
 
 INSTALL_DIR = $(CURDIR)/build/inst-dist
@@ -116,10 +111,11 @@ real-dist: dist-build html-build
        find build/dist -type d -print0 | xargs -0r chmod g+s
 
 dist-build:
-       rm -f ../dist/*.egg
-       cd .. && $(PYTHON) setup.py bdist_egg
+       rm -f ../dist/*.whl
+       cd .. && $(PYTHON) setup.py bdist_wheel
        install -d $(subst :, ,$(INSTALL_PPH))
-       $(PYTHON) `which easy_install` --prefix=$(INSTALL_DIR) ../dist/*.egg
+       # FIXME: cannot use pip, because it will mess with the already-install numpy version even if given a prefix
+       $(PYTHON) -m pip install --no-warn-conflicts --prefix=$(INSTALL_DIR) ../dist/*.whl
```

**Comment by rgommers** [comment]
On second thought, we should probably just get rid of `make dist` completely, and build all release artifacts via CI. `make dist` is really weird, the `Makefile` for the docs should just build the docs, not jump through weird hoops to build numpy and put it in a nonstandard place.

**Comment by charris** [comment]
`runtests` has most of the machinery needed to build docs.

**Comment by charris** [comment]
@rgommers What is your current thinking about this?

**Comment by rgommers** [comment]
No change, we should do it. I don't plan to do it any time soon though, too many other things to do. For now, if it breaks, just make sure to use an older setuptools version.

**Comment by seberg** [comment]
@rgommers is this an issue that needs to be fixed in 1.23.0 or can we push the milestone here?

**Comment by rgommers** [comment]
Updated to 1.24.0; it only affects doc builds so it can always be worked around if it breaks.

**Comment by bsipocz** [comment]
https://github.com/numpy/numpy/pull/21849 took care of this, so I'm closing.
