### ISSUE TITLE
Function to create a sliding N by M window over an ndarray

### ISSUE THREAD

**Issue by tomergt45** [numpy/numpy#18242]
Given the following ndarray:

```
arr = array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
```

I need a function that would efficiently return a sliding window with size N x M over the array, something like:

```
>>> np.window(arr, winsize=(2, 2))
array([[[1, 2],
        [4, 5]],

       [[2, 3],
        [5, 6]],

       [[4, 5],
        [7, 8]],

       [[5, 6],
        [8, 9]]])
```

After a lot of time of repeatedly writing a function that does that, I think it will be useful to have a native, efficient function in NumPy that does that exact same thing, I don't mind writing it myself and contribute to the project but I'm not familiar with the NumPy inner infrastructure, although I don't mind learning it for this purpose.

**Comment by tomergt45** [comment]
Just noticed this function has been added to version 1.20.0, hooray!

Although writing `np.lib.stride_tricks.sliding_window_view` is a mouthful, would be great if this could be moved to the main module and have its name shortened

**Comment by eric-wieser** [comment]
Well, you're free to do
```python
from numpy.lib.stride_stricks import sliding_window_view
```

I think @rgommers voiced against putting this in the main namespace on the mailing list, although I may be mistaken.

But yes, `sliding_window_view(arr, window_shape=(2, 2))` should do exactly what this issues asks for, so I think this issue can be closed. If you want to discuss naming, I'd recommend finding and responding to the mailing list thread, or opening a new issue.
