### ISSUE TITLE
no silent overflow option (Trac #1226)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1824]
_Original ticket http://projects.scipy.org/numpy/ticket/1226 on 2009-09-18 by trac user jloper, assigned to unknown._

> array(2**32,int32)
> OverflowError
> 
> array(2*_30,int32)_4
> 0

oh it would just make me so happy if these two commands COULD have the same output.  just a little flag somewhere.  a little "i love overflow errors" flag.  Just for me.

**Comment by seberg** [comment]
I think I prefer the creation of the array to error out here (you can probably get around it by creating an object array and casting). As for the integer overflow, it is a duplicate of gh-8987 (and maybe more).
