### ISSUE TITLE
incorrect text on web page

### ISSUE THREAD

**Issue by norbert-hoppe** [numpy/numpy#18256]
On the web page https://numpy.org/doc/stable/user/basics.types.html,
chapter 'Overflow Errors'
Text           'For example, numpy.power evaluates 100 * 10 ** 8 correctly for 64-bit integers'
should be  'For example, numpy.power evaluates 100 ** 8 correctly for 64-bit integers'
Regards

**Comment by mattip** [comment]
PR welcome

**Comment by sleeplessinseattledev** [comment]
I'll do this one!
