### ISSUE TITLE
argmax not returning first occurrence of max value in array

### ISSUE THREAD

**Issue by monahan19** [numpy/numpy#18261]
### Reproducing code example:

```python
import numpy as np
>>> data = [11, -10, 3, 15, -9, 8, 14, -20, -20, 16, -15, 18, 20, -3, -5, -16, 21, 22, 11, -19, -19, 19, 21, 15, 18, -9, 26, -2, 7, -20, -6, 15, -8, 22, 0, -9, -16, -14, -16, 27, -17, -8, 16, 20, -6]
>>> np.argmax(data)   # should return 16
39  
>>>
```

### Error message:

Error here is with the result

argmax should return the first occurrence of the max value (20) - which is at data[12], instead it returns the last occurrence of the max value at data[39]

From https://numpy.org/doc/stable/reference/generated/numpy.argmax.html :
_Notes
In case of multiple occurrences of the maximum values, the indices corresponding to the first occurrence are returned._

### NumPy/Python version information:
see this in all versions tested (python 2.7, python3.8.6, windows and raspberry pi)

1.19.5 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
and 
1.19.3 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]

**Comment by rkern** [comment]
`data[39] == 27` which is the maximum value in this list.

**Comment by rkern** [comment]
If I clip the data such that there are multiple maximum values of 20, we get the `argmax` of 12 as expected:

```
[~]
|9> clipped = np.clip(data, -100, 20)

[~]
|10> np.argmax(clipped)
12
```

I don't think there is a bug here.
