### ISSUE TITLE
Unevaluated markup in 1.20.0 release notes

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#18266]
See https://github.com/numpy/numpy/releases/v1.20.0, it has random markup like:
- `[numpy.lib.stride_tricks.sliding_window_view]{.title-ref}`
- `[~numpy.broadcast_shapes]{.title-ref}`
- `{.interpreted-text role="ref"}`
- `numpy.bool\_` (backslash shouldn't be there)
- `{.interpreted-text role="func"}`

It works fine in https://numpy.org/doc/1.20/release/1.20.0-notes.html, but I'd much prefer we stay with standard single and double backticks so it looks normal on GitHub too and I don't have to do extensive checking and edits before uploading to Tidelift.

**Comment by eric-wieser** [comment]
This is presumably an artefact of a bad rst to Markdown converter?

**Comment by rgommers** [comment]
Ah very odd. I didn't even consider that this stuff was not present in `source/release/1.20.0-notes.rst`. Seems to be a new GitHub rendering bug.

Thanks for pointing that out. Closing.

**Comment by charris** [comment]
I convert the notes from rst to md for github using pandoc. The conversion often needs a little fixing up and I missed that. The big fixup needed for 1.20.0 was a table. It would be nice if the github window accepted rst files.

**Comment by rgommers** [comment]
That explains it, thanks.

**Comment by charris** [comment]
The main translation problem is folks using back ticks for links in the release notes. That works fine when building the docs, not so well with standalone release notes.
