### ISSUE TITLE
Dictionary with np.nan fails to pickle and unpickle correctly

### ISSUE THREAD

**Issue by rp4fx12** [numpy/numpy#18260]
I'm not sure if this is the right place to be posting the issue (the issue might be with pickle or something else) but when I create two equivalent dictionaries with a np.nan, they pass a an equality test but when I pickle and unpickle one, the same equality check fails (See below example). I would expect the result to be consistent between both examples but I'm not entirely sure what's going on. I posted a simplified version of the error that we were seeing in our application. Let me know if I need to provide more information, am doing something wrong or if this needs to be raised against another library. 

### Reproducing code example:

```python
>>> import numpy as np
>>> a = {1: np.nan}
>>> d = {1: np.nan}
>>> a == d
True
>>> import pickle
>>> pickle.loads(pickle.dumps(a)) == d
False
>>> pickle.loads(pickle.dumps(d)) == d
False
>>> print(pickle.loads(pickle.dumps(d)))
{1: nan}
```

### Error message:

N/A

### NumPy/Python version information:

1.17.3 3.7.4 (default, Dec  9 2019, 22:13:34)
[Clang 11.0.0 (clang-1100.0.33.8)]

**Comment by eric-wieser** [comment]
Your code example doesn't actually use numpy in any meaningful way. You would see exactly the same behavior by defining `nan = float("nan")` and using `nan` instead of `np.nan` - so while I agree this is annoying, I don't think numpy can do anything about it.

**Comment by rp4fx12** [comment]
I posted an updated version of this issue in the python bug tracker and got back a response that explains why this is expected behavior. Linking it here - in case anyone else runs into the same or a similar issue: https://bugs.python.org/issue43078
