### ISSUE TITLE
MAINT: shuffle warning specificity

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#18273]
gh-18211 Introduced a warning for shuffling all memoryviews in Cython--would it be possible to not issue this warning for 1D C-contiguous memoryviews, for which there is no risk of problems per https://github.com/scipy/scipy/issues/13468? It seems a little broad maybe.

Conversely, the downstream fixes are pretty trivial--just seems to be a bit of extra churn that probably could be avoided.

**Comment by rgommers** [comment]
It's possible, it just needs special-casing.

**Comment by tylerjereddy** [comment]
Ok, I'll try to make a PR today if possible--to me it makes sense not to impose the change downstream for the special case if not broken/needed.

**Comment by rkern** [comment]
Memoryviews can be detected and converted to `ndarray`s with `asarray`, then passed through the rest of the function just fine.
