### ISSUE TITLE
typing: numpy.__version__ not visible to mypy

### ISSUE THREAD

**Issue by henryiii** [numpy/numpy#18270]
### Reproducing code example:

```python
import numpy as np
np.__version__
```

### Error message:

```bash
mypy tmp.py --python-version=3.7
tmp.py:2: error: Module has no attribute "__version__"; maybe "version"?
Found 1 error in 1 file (checked 1 source file)
```

### NumPy/Python version information:

Notice that `numpy.__version__` is literally in the issue template! It should be public, typable API:

> Output from `'import sys, numpy; print(numpy.__version__, sys.version)'`

```
1.20.0 3.8.2 (default, Nov  4 2020, 21:23:28)
[Clang 12.0.0 (clang-1200.0.32.28)]
```

**Comment by henryiii** [comment]
Appears to have been fixed in master, 

https://github.com/numpy/numpy/blob/de8bb00dbf007b65095e858ff2490b8df39b9047/numpy/__init__.pyi#L316

but sadly not backported to the maintenance 1.20 branch. Okay, closing.

**Comment by BvB93** [comment]
A missing object in the stub files is arguably ground for a backport, especially since 
these are rather simple and straightforward annotations.

Are there objections against backporting these 3 lines to 1.20.1? https://github.com/numpy/numpy/blob/d075ba2ce1579138e0fd53a611f88ad18003bbdc/numpy/__init__.pyi#L315-L317

**Comment by charris** [comment]
I don't have a problem with backporting this.

**Comment by charris** [comment]
@BvB93 Want to make a PR?

**Comment by BvB93** [comment]
Sure, I'll make a PR a bit later this week.
Before that, I'm going to comb through the stub files once more though, to check if we missed any similar cases.

**Comment by BvB93** [comment]
I've found a handful of other missing annotations in https://github.com/numpy/numpy/pull/18302; I'll get create a PR to close this issue after it's been merged.

**Comment by BvB93** [comment]
Resolved as of https://github.com/numpy/numpy/pull/18306.
