### ISSUE TITLE
unique does not support None

### ISSUE THREAD

**Issue by sam-s** [numpy/numpy#18288]
### Reproducing code example:

```python
import numpy as np
np.unique(np.array(["abc",1,2,None,3,"3",2]))
```

Note that removing `None` fixes the issue:
```
np.unique(np.array(["abc",1,2,3,"3",2]))
```
returns 
```
array(['1', '2', '3', 'abc'], dtype='<U21')
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in unique
  File "/Users/sam.steingold/.virtualenvs/brazeds/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 262, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/Users/sam.steingold/.virtualenvs/brazeds/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 323, in _unique1d
    ar.sort()
TypeError: '<' not supported between instances of 'int' and 'str'
```

### NumPy/Python version information:

numpy `1.20.0`
python
```
3.9.1 (default, Jan  8 2021, 17:17:17) 
[Clang 12.0.0 (clang-1200.0.32.28)]
```

**Comment by eric-wieser** [comment]
You're seeing two things happening here:

* `unique` requires entries to be sortable. The array `np.array([1, "1"], dtype=object)` is not sortable, and also fails in `unique`. I think there are other issues open about this.
* There's some weird coercion going on that makes `np.array([1, "1"])` a string array but `np.array([1, "1", None])` an object array. This means that `unique` somewhat works without `None` in the array, but notice that it replaced your `1` with `"1"`. I think @seberg probably wants to remove this behavior, which would make both cases in your report fail.

**Comment by seberg** [comment]
That code will indeed give a FutureWarning on master, the point is that we actually go to `object` as a fallback, so you will just always get an object array; Of course `"1" > 1` fails in Python, so at the end that will still mean that both will error in the future.

One of these days, maybe we have to think about having a very lightweight hashtable or so to make this type of operations more powerful (to be clear, its on nobody's agenda, and the typical answer is "use pandas" or similar). Although, I am actually not sure that `unique` would even be a prime target.
