### ISSUE TITLE
Parameter for np.corrcoef to provide p-value

### ISSUE THREAD

**Issue by aleksejs-fomins** [numpy/numpy#18283]
Currently there is no fast way to compute a matrix of correlation coefficients and the associated p-values using numpy or scipy without writing extensive code oneself. For community discussion see, for example, here

https://stackoverflow.com/questions/24432101/correlation-coefficients-and-p-values-for-all-pairs-of-rows-of-a-matrix

**Comment by WarrenWeckesser** [comment]
I think computing p-values is  out of scope for NumPy, and this issue would be more appropriate for SciPy.  SciPy has both `scipy.stats.pearsonr` and `scipy.stats.linregress`.  Both of these currently accept just a 1-d array for `x` and `y`, but there are issues on the SciPy github repository related to extending `pearsonr` to handle higher dimensional arrays.

**Comment by seberg** [comment]
Closing, as explained it is out of scope and scipy has solutions (which may be useful to extend).
