### ISSUE TITLE
Wrong eigenvector from numpy.linalg.eig()

### ISSUE THREAD

**Issue by syncsam** [numpy/numpy#18296]
Trying to find the eigenvector of the smallest eigenvalue of matrix

A = array([[ 2., -1.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  2.]])

using numpy.linalg.eig(). Inspecting the results, the smallest eigenvalue is 0.15224093 and its eigenvector is 
[-0.19134172  0.35355339  0.46193977 -0.5         0.46193977  0.35355339  0.19134172], which is wrong.

![image](https://user-images.githubusercontent.com/11826332/106564635-72164b80-6568-11eb-8edd-331496da9224.png)

**Comment by WarrenWeckesser** [comment]
You haven't shown the exact code that you used, so we can't check that you are using `np.linalg.eig` correctly.  I can't reproduce your result:
```
In [21]: a = np.array([[ 2., -1., 0., 0., 0., 0., 0.], 
    ...: [-1., 2., -1., 0., 0., 0., 0.], 
    ...: [ 0., -1., 2., -1., 0., 0., 0.], 
    ...: [ 0., 0., -1., 2., -1., 0., 0.], 
    ...: [ 0., 0., 0., -1., 2., -1., 0.], 
    ...: [ 0., 0., 0., 0., -1., 2., -1.], 
    ...: [ 0., 0., 0., 0., 0., -1., 2.]])                                                                           

In [22]: evals, evecs = np.linalg.eig(a)

In [23]: evals[4]  # eigenvalue
Out[23]: 0.15224093497742724

In [24]: evecs[:, 4]  # corresponding eigenvector
Out[24]: 
array([-0.19134172, -0.35355339, -0.46193977, -0.5       , -0.46193977,
       -0.35355339, -0.19134172])
```
We can verify that `evecs[:, 4]` is an eigenvector associated with the eigenvalue `evals[4]`:
```
In [25]: a @ evecs[:, 4]
Out[25]: 
array([-0.02913004, -0.0538253 , -0.07032614, -0.07612047, -0.07032614,
       -0.0538253 , -0.02913004])

In [26]: evals[4] * evecs[:, 4]
Out[26]: 
array([-0.02913004, -0.0538253 , -0.07032614, -0.07612047, -0.07032614,
       -0.0538253 , -0.02913004])
```

**Comment by syncsam** [comment]
> You haven't shown the exact code that you used, so we can't check that you are using `np.linalg.eig` correctly. I can't reproduce your result:
> 
> ```
> In [21]: A = np.array([[ 2., -1., 0., 0., 0., 0., 0.], 
>     ...: [-1., 2., -1., 0., 0., 0., 0.], 
>     ...: [ 0., -1., 2., -1., 0., 0., 0.], 
>     ...: [ 0., 0., -1., 2., -1., 0., 0.], 
>     ...: [ 0., 0., 0., -1., 2., -1., 0.], 
>     ...: [ 0., 0., 0., 0., -1., 2., -1.], 
>     ...: [ 0., 0., 0., 0., 0., -1., 2.]])                                                                           
> 
> In [22]: evals, evecs = np.linalg.eig(A)
> 
> In [23]: evals[4]  # eigenvalue
> Out[23]: 0.15224093497742724
> 
> In [24]: evecs[:, 4]  # corresponding eigenvector
> Out[24]: 
> array([-0.19134172, -0.35355339, -0.46193977, -0.5       , -0.46193977,
>        -0.35355339, -0.19134172])
> ```
> 
> We can verify that `evecs[:, 4]` is an eigenvector associated with the eigenvalue `evals[4]`:
> 
> ```
> In [25]: a @ evecs[:, 4]
> Out[25]: 
> array([-0.02913004, -0.0538253 , -0.07032614, -0.07612047, -0.07032614,
>        -0.0538253 , -0.02913004])
> 
> In [26]: evals[4] * evecs[:, 4]
> Out[26]: 
> array([-0.02913004, -0.0538253 , -0.07032614, -0.07612047, -0.07032614,
>        -0.0538253 , -0.02913004])
> ```

Sorry, I should make it clear that I was comparing the result obtained from Matlab. By using the function eig() on the matrix A in Matlab, the eigenvector corresponding to the minimum eigenvalue (0.152240934977426)   is 
[0.191341716182545 0.353553390593274 0.461939766255644 0.500000000000000 0.461939766255643 0.353553390593273 0.191341716182545]

**Comment by melissawm** [comment]
Eigenvectors are only unique up to linear transformations - in fact, you can see that they differ by sign only in your case. This means the result is correct, just taking a different basis for the eigenspace (as verified by @WarrenWeckesser above).
