### ISSUE TITLE
Formating remainder

### ISSUE THREAD

**Issue by blancc** [numpy/numpy#18300]
## Documentation

On [this](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html) page of the documentation, the "See also" section contains "doc.indexing" which is not supposed to be there.

**Comment by bryanccho** [comment]
Are we looking to remove the `doc.indexing` and add an explanation for `atleast_1d`... ?

This also appears [here](https://numpy.org/doc/stable/reference/generated/numpy.ma.expand_dims.html?highlight=doc%20indexing)

**Comment by blancc** [comment]
I don't know about the explanation du the `doc.indexing` seems to be an artifact or something

**Comment by bryanccho** [comment]
I can go ahead and fix this.  This is my first time contributing to open source.  Do I clone, branch and then submit a PR?

**Comment by melissawm** [comment]
Something like that! Please check out [contributor guide](https://numpy.org/doc/stable/dev/index.html), and let us know if you have questions.

**Comment by aryanxk02** [comment]
@bryanccho hey but there is an explanation to atleast_1d so there is no need to add anything for it right?

**Comment by melissawm** [comment]
@carrolsong I think you meant to work on this but did a commit to your own fork, and never submitted a pull request for this. Are you interested in picking this up? I can help you if you need assistance. Cheers!

**Comment by seberg** [comment]
fixed on main.
