### ISSUE TITLE
Assignment of invalid floats to signed integers

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#18316]
In an attempt to not relax the behaviour of certains `np.asarray(np.float64(np.nan), dtype=int)` calls (a NumPy NaN is cast to an integer during coercion), incidentally, this also was turned into an error:
```
arr = np.array([1])
arr[...] = np.float64(np.nan)
```
because I aligned how assignment and array coercion works (at least much more than it used to be).

I actually *like* the error, but it is not super clean:
```
arr[...] = np.array(np.nan)
```
succeeds (because casting a NaN to iteger currently works without any warning or error). Trying to be minimal, it also only happens for signed integers right now.

In the long run, I would like the array cast also to at least give a warning (if that is permissible performance wise), at which point it would be nicer to just give the same warning for the scalar.

Just to be clear, *none of this affects Python NaN* `arr[...] = np.nan`, but within `np.pad`, that gets converted to a float64 array temporarily, so the difference suddenly matters.

Chances are, we can and will just leave things as they are, it is a subtle change and the new behaviour is probably even nicer, whether quite consistent or not.  But it is a bit trickier than most issues.

**Comment by charris** [comment]
Changed the milestone to 1.21.0.

**Comment by seberg** [comment]
Closing this, since it is pretty much the same as gh-17495 and I think there was probably more info there.  As said there, I hope that we can fix this by e.g. always warning here, but at this point, it is probably OK not to milestone it specifically.
