### ISSUE TITLE
test_build_import is failing on windows.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#18312]
See results [here](https://tinyurl.com/y55txleq). The problem seems to be missing `nm`, I think we have seen that before.

**Comment by mattip** [comment]
i think we should move the fast check build to the linux_native build so the flaky mingw does not prevent the rest of the CI from running. We could also mark that test as flaky, but then we will never pay attention to it when it fails

**Comment by charris** [comment]
> i think we should move the fast check build to the linux_native build

Good idea.

**Comment by rgommers** [comment]
do we still need this issue @charris, @mattip?

**Comment by mattip** [comment]
Done, closing.
