### ISSUE TITLE
Possible memory leak after deleting both Numpy array and its slice view ?

### ISSUE THREAD

**Issue by touqir14** [numpy/numpy#18318]
So, I allocated an array and then created a slice view of it and then I first deleted the original array and afterwards its slice view. Memory consumption did not change. Also, this isn't happening always. I have seen cases where the memory allocator does not immediately give back memory to the OS and I wanted to double check whether that is whats happening here.

```python
import numpy as np
x = np.random.rand(10000,10000) # The python process's RAM usage jumps to around 820MB
y = x[:1, :]
del x
del y # After doing this, RAM usage does not change. Hence python's process keeps on consuming over 800MB.
```

### NumPy/Python version information:

 Output from ```import sys, numpy; print(numpy.__version__, sys.version) ``` : 
1.21.0.dev0+430.ge745a19cb 3.7.9+ (heads/3.7:225e365, Nov 16 2020, 23:39:30) 
[GCC 9.3.0]
Running on Ubuntu 20.04 LTS with linux kernel: 5.4.0-42-generic .

**Comment by seberg** [comment]
This in itself is normal behaviour, of how the operating system and python reclaim memory. Try allocating `x` again repeatedly and you will see that the memory "settles" around those 800 MB.

**Comment by touqir14** [comment]
Right. I once noticed this behaviour in one of my C extensions where I needed to repeatedly allocate and deallocate memory. It also happens with other memory allocators specially when each deallocation is significantly small compared to the total allocated memory. Memory allocators usually use a threshold on the amount of deallocation for deciding whether to give back that memory to prevent memory fragmentation, hence prevent performance degradation.
