### ISSUE TITLE
Pickling `type` of `dtype` object fails on NumPy 1.20

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#18325]
### Reproducing code example:

On NumPy 1.19.5, the following is possible...

```python
In [1]: import pickle
   ...: import numpy as np

In [2]: t = type(np.arange(10, dtype="int64").dtype)

In [3]: pickle.loads(pickle.dumps(t))
Out[3]: numpy.dtype
```

However on NumPy 1.20.0 we see the following error...

```python
In [1]: import pickle
   ...: import numpy as np

In [2]: t = type(np.arange(10, dtype="int64").dtype)

In [3]: pickle.loads(pickle.dumps(t))
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-3-c105e6dd98fb> in <module>
----> 1 pickle.loads(pickle.dumps(t))

PicklingError: Can't pickle <class 'numpy.dtype[int64]'>: attribute lookup dtype[int64] on numpy failed
```

Not sure if this is expected to fail, but we encountered this in our test suite when upgrading to NumPy 1.20

### Error message:

```python
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-3-c105e6dd98fb> in <module>
----> 1 pickle.loads(pickle.dumps(t))

PicklingError: Can't pickle <class 'numpy.dtype[int64]'>: attribute lookup dtype[int64] on numpy failed
```

### NumPy/Python version information:

```
1.20.0 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:32:59) 
[Clang 11.0.1 ]
```

cc @madsbk @pentschev @quasiben

**Comment by seberg** [comment]
@BvB93 do we have a nice place in `np.typing` to put things like `np.typing.Float64` there? Such a rename would be the simplest solution...

DTypes probably should/could be proper heap-types as well, which would probably allow to fix this more easily, but it a swath to wade through (In some future, we probably want everything to be heap types anyway, because it should make certain things cleaner, such as HPy support).

**Comment by seberg** [comment]
Oops, I just realized that there is actually a simple work around that seems to be sufficient and only rely on the existence of `dtype.type`, which is not a very strong requirement.

**Comment by seberg** [comment]
@jakirkham would you be able to check if gh-18332 works for you? It will allow pickling the class, but I am starting to expect the class is just part of a more elaborate scheme, and I am not sure that pans out with the fix?

**Comment by jakirkham** [comment]
Ofc, thanks for working on this Sebastian 😄

Should I rebuild from source to try or do you think I can just apply that change to an exiting build of NumPy 1.20?

**Comment by seberg** [comment]
No need to rebuild, its just a pure python change.  Thanks!

**Comment by jakirkham** [comment]
Looks good! Thanks again for the quick fix Sebastian 😄 

```python
In [1]: import pickle
   ...: import numpy as np

In [2]: t = type(np.arange(10, dtype="int64").dtype)

In [3]: pickle.loads(pickle.dumps(t))
Out[3]: numpy.dtype[int64]
```

**Comment by seberg** [comment]
Oh, thanks for checking. I am/was a bit worried that the original issue was more general and possibly did something like:
```
arg = "f8"
dt = np.dtype(arg)
dtype_type = type(dt)

dtype_type(arg)
```
I.e. after unpickling, you would instantiate the dtype again with arguments originally meant for `np.dtype`. But that would break currently (and I am not sure I want it to work generally, since `np.dtype` is a mini-language basically).

**Comment by jakirkham** [comment]
No worries. At least in our use case, we created an array first

I know I have written and seen code like `np.dtype(arg).type`. Though that is a bit different than what we have here. Also I don't think I've seen the result be pickled in that case. That said, this case does appear to pickle correctly

```python
In [1]: import pickle
   ...: import numpy as np

In [2]: pickle.loads(pickle.dumps(np.dtype("int64").type))
Out[2]: numpy.int64
```

**Comment by seberg** [comment]
Yeah, pickling the `dtype.type` is totally fine (in fact, it is the solution here at the moment).  `dtype.type` is the scalar type though which is different from `type(dtype)` its a bit confusing :).

**Comment by hernot** [comment]
This is back or still there in 1.21.2 (git: 2fe48d2d98a85c8ea3f3d5caffd952ea69e99335) fresh install from pypi

Just got the follwoing error on numpy.dtype('float16')  on python 3.7 and onward. 

 _pickle.PicklingError: Can't pickle <class 'numpy.dtype[float16]'>: it's not found as numpy.dtype[float16]

but also on 'float32' as well as 'int16' So it seems that the last fix did not catch all

**Comment by seberg** [comment]
@hernot I cannot reproduce it even with that exact version.  Could you please check everything, especially the numpy version?  Ideally, paste a small, reproducing snippet that includes the version print.

**Comment by hernot** [comment]
It is only with dill they call in their own save_type function the save_type funktion of the Pickler provided by pickle it self and pass as name the __qualname__ of the dtype class. which reads:

dtype[float16]

So i guess it is a dill package problem and has to be checked by them first before continuing here. Are there any informations i should pass to them beyond version numbers, which could help them to fix. Do you think including a link to this pr and related issues in my report on their issue tracker would be a good or a bad idea?

**Comment by seberg** [comment]
Well, we probably should eventually change the name/qualname to point to something that is an actual valid name.  But I am surprised that dill would not do what pickle does;  and I am not sure we should backport such a change.
I am not sure if we should have a qualname at all, but I guess Python just assumes its right here...

**Comment by seberg** [comment]
I don't know. NumPy has:
```
copyreg.pickle(type(dtype), _DType_reduce, _DType_reconstruct)
```
and the dill people should give input if they think that is not good enough.

**Comment by hernot** [comment]
Hm the official pickle documentation says that per default the copyreg.dispatch table is used 

https://docs.python.org/3/library/pickle.html#pickle.Pickler.dispatch_table

And if dill claims to be a replacement for vanilla pickle just in addition to memory structure also storing python interpreter state than as a user i do expect that dill also behaves, fells and works  apart from this like vanilla pickle, and not like a pickler customized for my personal projects needs.
