### ISSUE TITLE
Large arrays not reusing memory previously used by many small arrays

### ISSUE THREAD

**Issue by fcharras** [numpy/numpy#18358]
### Reproducing code example:
Consider the following sequence of instruction, and execute it in a python interpreter while paying attention to the RAM usage after each one:
```
import numpy as np
# 1: allocates 5000*100000*4 Bytes
a = np.ones(5000*100000, dtype=np.int32)  

# 2: garbage collection free the previous allocation
a = None 

# 3: allocates again but with many small arrays
a = [np.ones(5000, dtype=np.int32) for i in range(100000)] 

# 4: garbage collection does not free the previous allocation !
a = None  

# 5: allocates 5000*100000*4 Bytes on top of the previous allocation
a = np.ones(5000*100000, dtype=np.int32)

# 6: allocates again but with many small arrays
b = [np.ones(5000, dtype=np.int32) for i in range(100000)]
```
#### Expected result
RAM usage after 5 should be equal to RAM usage after 1.

#### Observed result
RAM usage after 5 is twice the RAM usage after 1.

#### What seems to happen
The memory has most likely been freed after 4, since the reference counts of the small arrays allocated during 3 are null, but the RAM usage has not been released by the python interpreter to the system. That's not an issue because the interpreter might re-use it again, but it's not always possible, because it is currently very fragmented: there are a lot of ranges of size 5000x4 Bytes of continuous blocks, intertwined with whatever allocations that might have been added between each blocks and have not been released yet. Thus it can only be reused for allocations of range of blocs of size <= 5000*4 Bytes. We see indeed that It cannot be reused for 5 but it can be reused for 6.

### NumPy/Python version information:
Tested with python 3.9.1 + numpy 1.20 and python 3.7 + numpy 1.15.

**Comment by seberg** [comment]
NumPy doesn't do anything fancy for arrays, the only thing it does and which *might* make a difference is:

1. It caches "very small" arrays, but even your small ones are too large for that.
2. It uses madvise hugepages for `>=4194304` bytes in an array.  Which can be toggled on newer NumPy versions: https://numpy.org/doc/stable/reference/global_state.html

Everything beyond that is operating system defined, and I am not aware of any reason to not trust the OS to do the right thing.

**Comment by fcharras** [comment]
You're right this is not related to numpy, but it's more likely to happen when using numpy because of allocation and release of contiguous blocks.

The example definitely show a counter-intuitive result where ram freed != ram available, and ram used >> size of objects. I wonder if at a lower level the interpreter and/or the OS can be optimized to be better at compacting the allocated memory ?

Overall maybe it can only be prevented with awareness, I found that it helps to anticipate this issue when choosing data structure and workflow (making use of writing to disk and isolating tasks in separate process that will completely release memory when done). On second thought it seems obvious but it does not seem to be a commonly raised programming bad practice, or am I missing something ?

**Comment by seberg** [comment]
@fcharras remember that the operating system just gives virtual memory to the program to begin with, so that is a job the OS probably does (although I don't know the depth of it).
