### ISSUE TITLE
DLL load failed - Manual installation on Windows

### ISSUE THREAD

**Issue by cubanpit** [numpy/numpy#18376]
I am trying to compile NumPy from source on Windows with MSVC linking to Intel MKL.
I am running Windows 10.0.18363 with Microsoft Visual Studio 2019 (16.8.4) and Intel MKL 2017.8.275.

### Steps to reproduce:

1. Download latest Python (3.9.1) and latest NumPy (1.20.1) source.
2. Open a VS command prompt, unpack Python source, build with `PCbuild\build.bat`
3. Run `mklvars.bat intel64` to get the right environment variables set.
4. Add the Intel compilers (needed for `ifort`) to `PATH`:
```set PATH=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\bin\intel64;%PATH%```
5. Create a virtual env, copy a few files from the Python build and activate the virtual env:
```
copy Python\PCbuild\amd64\python39.dll venv\Scripts
copy Python\PC\pyconfig.h venv\Include
```
6. Build NumPy from source and install:
```
pip install . -v
```
7. Try to import NumPy: `python -c "import numpy"`

### Error message:

```
Traceback (most recent call last):
  File "C:\cygwin\home\user\numpy_clean_env\venv\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\cygwin\home\user\numpy_clean_env\venv\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\cygwin\home\user\numpy_clean_env\venv\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\cygwin\home\user\numpy_clean_env\venv\lib\site-packages\numpy\__init__.py", line 145, in <module>
    from . import core
  File "C:\cygwin\home\user\numpy_clean_env\venv\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\cygwin\home\user\numpy_clean_env\venv\Scripts\python.exe"
  * The NumPy version is: "1.20.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
```

The MKL libraries are picked up during compilation since it returns:
```
FOUND:
        libraries = ['mkl_rt']
        library_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries\\windows\\mkl\\lib\\intel64']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries\\windows\\mkl\\lib']
```

I tried to analyze the DLL resolution with Dependencies (the newer version of Dependency Walker) but it seems that the MKL DLL loads fine. There are some DLLs that appear as not correctly loaded, but as far as I understand it is caused by the inspection software limit with Windows API sets, not by actual problems with this DLLs, so I think the system is correctly setup.
Here is a list of the unique DLLs that cause a `NOT_FOUND` in Dependencies when analyzing `_multiarray_umath.pyd`:
```
EMCLIENT.dll (NOT_FOUND) :
HvsiFileTrust.dll (NOT_FOUND) :
UpdateAPI.dll (NOT_FOUND) :
api-ms-win-core-comm-l1-1-0.dll (NOT_FOUND) :
api-ms-win-core-psapi-ansi-l1-1-0.dll (NOT_FOUND) :
api-ms-win-core-psapi-l1-1-0.dll (NOT_FOUND) :
api-ms-win-core-stringansi-l1-1-0.dll (NOT_FOUND) :
api-ms-win-core-versionansi-l1-1-0.dll (NOT_FOUND) :
api-ms-win-core-versionansi-l1-1-1.dll (NOT_FOUND) :
api-ms-win-core-winrt-string-l1-1-0.dll (NOT_FOUND) :
api-ms-win-core-wow64-l1-1-0.dll (NOT_FOUND) :
api-ms-win-core-wow64-l1-1-1.dll (NOT_FOUND) :
api-ms-win-core-xstate-l2-1-0.dll (NOT_FOUND) :
api-ms-win-core-xstate-l2-1-1.dll (NOT_FOUND) :
api-ms-win-coreui-secruntime-l1-1-0.dll (NOT_FOUND) :
ext-ms-mf-pal-l2-1-0.dll (NOT_FOUND) :
ext-ms-onecore-appmodel-emclient-l1-1-0.dll (NOT_FOUND) :
ext-ms-onecore-defaultdiscovery-l1-1-0.dll (NOT_FOUND) :
ext-ms-onecore-orientation-l1-1-0.dll (NOT_FOUND) :
ext-ms-onecore-shellchromeapi-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-appmodel-deployment-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-appmodel-usercontext-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-appmodel-viewscalefactor-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-audiocore-pal-l1-2-0.dll (NOT_FOUND) :
ext-ms-win-com-suspendresiliency-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-core-winrt-remote-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-dwmapi-ext-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-dxcore-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-networking-wlanstorage-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-ntuser-window-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-ntuser-window-l1-1-1.dll (NOT_FOUND) :
ext-ms-win-ntuser-window-l1-1-2.dll (NOT_FOUND) :
ext-ms-win-ntuser-window-l1-1-3.dll (NOT_FOUND) :
ext-ms-win-ntuser-window-l1-1-4.dll (NOT_FOUND) :
ext-ms-win-ras-tapi32-l1-1-1.dll (NOT_FOUND) :
ext-ms-win-ro-typeresolution-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-rtcore-minuser-input-l1-1-1.dll (NOT_FOUND) :
ext-ms-win-rtcore-minuser-private-ext-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-security-capauthz-ext-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-security-chambers-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-shell-knownfolderext-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-shell-shell32-l1-2-0.dll (NOT_FOUND) :
ext-ms-win-shell-shlwapi-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-shell-tabbedtitlebar-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-shell32-shellcom-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-shell32-shellfolders-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-ui-viewmanagement-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-uiacore-l1-1-0.dll (NOT_FOUND) :
ext-ms-win-wer-xbox-l1-1-0.dll (NOT_FOUND) :
ext-ms-win32-subsystem-query-l1-1-0.dll (NOT_FOUND) :
ext-ms-windowscore-deviceinfo-l1-1-0.dll (NOT_FOUND) :
```

Not sure where is the problem, maybe it does not have to do with NumPy, but this was my first guess.
If this is not the case, any suggestion is more than welcome.

EDIT:
Reduced the amount of file copied to the venv in order to compile NumPy, only a header and a DLL files are needed.
These are the elements I removed from the list, the result does not change.
```copy Python\PCbuild\amd64\*.exe venv\Scripts
copy Python\PCbuild\amd64\*.dll venv\Scripts
copy Python\PCbuild\amd64\*.pyd venv\Scripts
copy Python\PCbuild\amd64\python*.lib venv\Lib
copy Python\Include venv\Include
copy Python\Lib\* venv\Lib```

**Comment by cubanpit** [comment]
Solved by following a suggestion on Numpy mailing list ([permalink](http://numpy-discussion.10968.n7.nabble.com/Compile-NumPy-with-ifort-MSVC-and-MKL-DLL-load-failed-tp48968p48970.html)).

> Python >= 3.8 will no longer use PATH for resolving dependencies of
extension modules. Use os.add_dll_directory(mkl_bin_path)
<https://docs.python.org/3/library/os.html#os.add_dll_directory> in all
your scripts before importing numpy or add the call to a
_distributor_init.py file in the numpy package directory.

**Comment by roboserg** [comment]
> Solved by following a suggestion on Numpy mailing list ([permalink](http://numpy-discussion.10968.n7.nabble.com/Compile-NumPy-with-ifort-MSVC-and-MKL-DLL-load-failed-tp48968p48970.html)).
> 
> > Python >= 3.8 will no longer use PATH for resolving dependencies of
> > extension modules. Use os.add_dll_directory(mkl_bin_path)
> > https://docs.python.org/3/library/os.html#os.add_dll_directory in all
> > your scripts before importing numpy or add the call to a
> > _distributor_init.py file in the numpy package directory.

Like this?

```
import os
os.add_dll_directory("C:\\Users\\myname\\miniconda3\\Library\\bin")
```

**Comment by realiti4** [comment]
> Solved by following a suggestion on Numpy mailing list ([permalink](http://numpy-discussion.10968.n7.nabble.com/Compile-NumPy-with-ifort-MSVC-and-MKL-DLL-load-failed-tp48968p48970.html)).
> 
> > Python >= 3.8 will no longer use PATH for resolving dependencies of
> > extension modules. Use os.add_dll_directory(mkl_bin_path)
> > https://docs.python.org/3/library/os.html#os.add_dll_directory in all
> > your scripts before importing numpy or add the call to a
> > _distributor_init.py file in the numpy package directory.

Hi,

What directories are you adding exactly? I can't solve this issue on my source build.
