### ISSUE TITLE
In certain case, v1.20.0 numpy.log returns a slightly different value than v1.19.5

### ISSUE THREAD

**Issue by xgchena** [numpy/numpy#18371]
### Background

Our project uses numpy.log() to calculate [some metrics](https://github.com/aws/amazon-sagemaker-clarify/blob/f7f8d84560c8d491034aa35a5c03e68e373e7ae7/src/smclarify/bias/metrics/pretraining.py#L114). Our last commit to master branch was about a month ago and it built without problem. But lately there is [a build failure due to unit test code got unexpected metric value](https://github.com/xgchena/amazon-sagemaker-clarify/runs/1857585497?check_suite_focus=true). After investigation we pinned the direct cause down to numpy upgrade from v1.19.5 to v1.20.0, it seems that in certain case, v1.20.0 numpy.log returns a slightly different value than v1.19.5. We realized that it is incorrect for our test code to compares floating numbers directly, and we already have [a fix for our test code to assert almost equal by pytest.approx](https://github.com/aws/amazon-sagemaker-clarify/pull/98). But still we'd like to confirm with you if the numpy.log change is an expected precision change or a bug.

### Reproducing code example:

The issue can be reproduced on Linux (tried two distributions: Github Actions on Ubuntu 18.04.5 LTS, and an Amazon AWS EC2 runs Amazon Linux 2), but could not be reproduced on macOS.

For below code snippet,

```python
import numpy as np
v = np.log(0.8181818181818182) # check the value of v
v1 = np.log(np.array([0.8181818181818182])) # check the value of v1[0]
v2 = np.log(np.array([0.8181818181818182,1])) # check the value of v2[0]
```

Here are the results (note that for numpy v1.20.0 on Linux, when the magic number 0.8181818181818182 is NOT the only element in a ndarray, then np.log outputs a slightly different log value for it,

* numpy v1.20.0

| Statement \ Value (v, v1[0] or v2[0])                                | macOS             | Linux               |
| ------------------------------------------------ | ------------------- | ------------------------ |
| v = np.log(0.8181818181818182)       | -0.2006706954621511 | -0.2006706954621511      |
| v1 = np.log(np.array([0.8181818181818182]))       | -0.2006706954621511 | -0.2006706954621511      |
| v2 = np.log(np.array([0.8181818181818182,**1**])) | -0.2006706954621511 | -0.200670695462151**08** |

* numpy v1.19.5

| Statement \ Value (v, v1[0] or v2[0])                                 | macOS             | Linux               |
| ------------------------------------------------ | ------------------- | ------------------------ |
| v = np.log(0.8181818181818182)       | -0.2006706954621511 | -0.2006706954621511      |
| v1 = np.log(np.array([0.8181818181818182]))       | -0.2006706954621511 | -0.2006706954621511      |
| v2 = np.log(np.array([0.8181818181818182,**1**])) | -0.2006706954621511 | -0.2006706954621511 |

### Error message:

N/A

### NumPy/Python version information:

* Amazon AWS EC2 runs Amazon Linux 2

```
('1.20.0', '3.7.9 (default, Feb  6 2021, 09:35:16) \n[GCC 7.3.1 20180712 (Red Hat 7.3.1-12)]')
```

* MacBook Pro runs macOS Catalina 10.15.7

```
('1.20.0', '3.7.9 (default, Nov 20 2020, 18:45:38) \n[Clang 12.0.0 (clang-1200.0.32.27)]')
```

**Comment by charris** [comment]
I don't see this on linux myself, but it may be hardware dependent as NumPy may take advantage of AVX or other vectorizations. Or possibly it is not rounding properly. What hardware do you have?

**Comment by xgchena** [comment]
I'm using a AWS EC2 host of type [m5.4xlarge](https://aws.amazon.com/ec2/instance-types/m5/) for daily development work, here is the CPU info,

```
$ lscpu                                                                                                                                           [23:11:50]
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
Stepping:            4
CPU MHz:             3100.967
BogoMIPS:            5000.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
```

I don't know the hardware configuration of Github Actions runners. We've never seen this problem when using numpy v1.19.5, but our project builds against v1.20 always fail Github Actions or local builds in my EC2 host. Could the issue be correlated to any new commit in v1.20.0?

**Comment by charris** [comment]
> Could the issue be correlated to any new commit in v1.20.0?

There has been a lot of work implementing SIMD in 1.20, in particular #16605. @xiegengxin Thoughts?

**Comment by seberg** [comment]
Yeah, just dug that one out also. Pinging also @Qiyu8.  It might be that the algorithm adopted is slightly less accurate, but I am not sure if that is a deficiency, or simply an expected variation in precision (IIRC things like log should have around <2-3 ULP of error?).  Unless log is defined by IEEE/glibc to be expected to only have 1 ULP?

Note that:
```
np.nextafter(-0.2006706954621511, 0) == -0.20067069546215108
```
So the difference you see is a single ULP difference.  That is _probably_ within expectations, but I am not sure.

**Comment by charris** [comment]
> For all I know, the new result is actually more accurate...)

I did run in extended precision and got `-0.20067069546215109959`, but wouldn't trust that either :) Note that `0.8181818181818182` needs to be converted to float64 to avoid the problem of conversion accuracy before running the computation in higher precision.




-0.200670695462151139049230881898
--




-0.200670695462151139049230881898
--

**Comment by seberg** [comment]
Based on this:
```
from mpmath import *
mp.dps = 40
print(log(0.8181818181818182))
print(float(log(0.8181818181818182)))
```
printing:
```
-0.2006706954621510995923961805002719913669
-0.2006706954621511
```
the non AVX result is the more accurate one I guess. But it both is the two nearest float values possible.

Maybe the only irritating thing is that you can get different results for different array lengths, but I guess similiar differences are probably not uncommon.

**Comment by mattip** [comment]
We have a test for umath accuracy in `numpy/core/tests/test_umath_accuracy.py`. It includes tests for `log`. @xgchena  does your platform pass those tests?
```
$ pip install pytest hypothesis numpy
$ python -c "import numpy as np; np.test(extra_argv=['-k TestAccuracy', '-vv'])"

**Comment by Qiyu8** [comment]
@seberg I agree with you, both `-0.20067069546215110` and `-0.20067069546215108` are the nearest values possible to accurate `-0.20067069546215109`, It's expected result so we shouldn't blame the algorithm in #16605, what I wondered most is AVX512f flag needs to manually enabled in order to triggle that SIMD algorithm, I have not found any evidence that @xgchena did so.

**Comment by seberg** [comment]
Indeed I think we can close this? The solution to use an approximate check is correct in any case.   Just in case it is helpful, NumPy also has approximate assertion functions, such as `np.testing.assert_array_max_ulp` which allows to specify the number of ULP (unit of least precision, i.e. how many bits), the result is allowed to be off.

To also post it again, this is the GCC table: https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html (although I am not quite certain that the vectorized versions are covered here).  This lists it as `-` for all listed architectures (not sure if that means `<1 ULP` or what exactly.  Note for example that the float version is listed as having a different accuracy on different hardware.

It might make sense to document ULPs for certain operations, especially now that there will be more variation with different SIMD algorithms, but I don't think the new SIMD algorithms really changed the precision in a meaningful way. (At least I am not aware of that, and this example is well within expectations.)

**Comment by xgchena** [comment]
> We have a test for umath accuracy in `numpy/core/tests/test_umath_accuracy.py`. It includes tests for `log`. @xgchena does your platform pass those tests?

Yes, the test passed on my EC2 instance.

```
$ pip install pytest hypothesis numpy                                                                                                         [23:55:00]
Requirement already satisfied: pytest in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (6.2.2)
Collecting hypothesis
  Downloading hypothesis-6.1.1-py3-none-any.whl (353 kB)
     |████████████████████████████████| 353 kB 7.2 MB/s 
Requirement already satisfied: numpy in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (1.20.0)
Requirement already satisfied: attrs>=19.2.0 in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from hypothesis) (20.3.0)
Collecting sortedcontainers<3.0.0,>=2.1.0
  Downloading sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: toml in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from pytest) (0.10.2)
Requirement already satisfied: iniconfig in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from pytest) (1.1.1)
Requirement already satisfied: pluggy<1.0.0a1,>=0.12 in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from pytest) (0.13.1)
Requirement already satisfied: packaging in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from pytest) (20.9)
Requirement already satisfied: importlib-metadata>=0.12 in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from pytest) (3.4.0)
Requirement already satisfied: py>=1.8.2 in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from pytest) (1.10.0)
Requirement already satisfied: zipp>=0.5 in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from importlib-metadata>=0.12->pytest) (3.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from importlib-metadata>=0.12->pytest) (3.7.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in ~/.virtualenvs/amazon-sagemaker-clarify/lib/python3.7/site-packages (from packaging->pytest) (2.4.7)
Installing collected packages: sortedcontainers, hypothesis
Successfully installed hypothesis-6.1.1 sortedcontainers-2.3.0
$ python -c "import numpy as np; np.test(extra_argv=['-k TestAccuracy', '-vv'])"                                                              [23:59:06]
NumPy version 1.20.0
NumPy relaxed strides checking option: True
NumPy CPU features: SSE SSE2 SSE3 SSSE3* SSE41* POPCNT* SSE42* AVX* F16C* FMA3* AVX2* AVX512F* AVX512CD* AVX512_KNL? AVX512_KNM? AVX512_SKX* AVX512_CLX? AVX512_CNL? AVX512_ICL?
==================================================================================================== test session starts =====================================================================================================
platform linux -- Python 3.7.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- ~/.virtualenvs/amazon-sagemaker-clarify/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('~/Desktop/workplace/amazon-sagemaker-clarify/.hypothesis/examples')
rootdir: ~/Desktop/workplace/amazon-sagemaker-clarify
plugins: pspec-0.0.4, hypothesis-6.1.1
collected 14426 items / 14425 deselected / 1 selected                                                                                                                                                                        

core/tests/test_umath_accuracy.py::TestAccuracy::test_validate_transcendentals PASSED                                                                                                                                  [100%]

============================================================================================ 1 passed, 14425 deselected in 8.21s =============================================================================================
```

**Comment by xgchena** [comment]
Thanks for the investigation and please feel free to close the issue if you believe the change is expected.
