### ISSUE TITLE
Incorrect interpretation of p-value

### ISSUE THREAD

**Issue by lelayf** [numpy/numpy#18370]
https://github.com/numpy/numpy/blob/9f12028b9453c17b72b26355fd503e512af96a5d/numpy/random/mtrand.pyx#L2175

A p-value is not the probability of the null hypothesis being true. I think the wording in the documentation could be improved to read like this:

`The p-value is about 0.009, which says there is about 1% chance of observing values as extreme as those observed in our intake, conditionally on the null hypothesis of equal means being true. Therefore, the experimenter would reject the null hypothesis at the 5% significance level.`

**Comment by melissawm** [comment]
Thanks, @lelayf . Would you be up to submitting a PR to do this?

**Comment by lelayf** [comment]
Yes, I actually found the reference example in R, which uses a 2-tailed test. I will tweak it as appropriate and submit a PR.
