### ISSUE TITLE
The typing hint for `tofile` should include Path.

### ISSUE THREAD

**Issue by szsdk** [numpy/numpy#18383]
According to the document, the `tofile` function accepts a `Path` object. However, the `tofile` interface does not match it. 
https://github.com/numpy/numpy/blob/3823775ca779f5470b46c24d141fd483fee931d5/numpy/__init__.pyi#L907

**Comment by BvB93** [comment]
By the looks of it `ndarray.tofile` can in fact accept any path-like object, including implementations 
of the `__fspath__` protocol as well as `bytes`: `Union[IO[bytes], str, bytes, os.PathLike[Any]]`.

Would you be willing to submit a PR?

**Comment by szsdk** [comment]
Yeah, I am working on it.
