### ISSUE TITLE
ndarray.sort() doesn't work

### ISSUE THREAD

**Issue by marco13579** [numpy/numpy#18393]
I've tried the simple example:

x = np.array([[1, 2], [3, 4]])
x.sort()

in colab and i obtain nothing. Instead the np.sort(x) work fine. Sure a bug to fix.

Thank you.

**Comment by mreineck** [comment]
As far as I understand, `x.sort()` just sorts the array, but it doesn't return anything.

**Comment by BvB93** [comment]
Per the [docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html#numpy.ndarray.sort): `ndarray.sort()` performs in _in-place_ sorting of the pre-existing array, rather than creating a new array.

``` python
In [1]: import numpy as np

In [2]: x = np.array([3, 4, 1, 2])

In [3]: x.sort()

In [4]: x
Out[4]: array([1, 2, 3, 4])
```
