### ISSUE TITLE
Can't import numpy(pypy7.3.4, Python3.8.7)

### ISSUE THREAD

**Issue by Marusoftware** [numpy/numpy#18410]
### Steps to reproduce:
Can't import numpy.
Python:pypy7.3.4(Python3.8.7)
OS: Linux Mint 20.2
I tried source build.
But it was failed, too.
[build.log](https://github.com/numpy/numpy/files/5978096/build.log)
[install.log](https://github.com/numpy/numpy/files/5978098/install.log)

### Error message:
```
Traceback (most recent call last):
  File "/usr/share/pypy/pypy3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/usr/share/pypy/pypy3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/share/pypy/pypy3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /usr/share/pypy/pypy3.8/site-packages/numpy/core/_multiarray_umath.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: _PyDict_GetItemStringWithError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/pypy/pypy3.8/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/usr/share/pypy/pypy3.8/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/bin/pypy3.8"
  * The NumPy version is: "1.20.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /usr/share/pypy/pypy3.8/site-packages/numpy/core/_multiarray_umath.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: _PyDict_GetItemStringWithError
```

Thank you.

**Comment by mattip** [comment]
I think you should open this in the [PyPy issue tracker](https://bitbucket.org/pypy/pypy/issues). They have not yet released a 3.8 version, and it will be a while until that version is even alpha-level.

**Comment by Marusoftware** [comment]
OK.
But the package for pp38 is available in PyPI.
So, I thought pp38 is supported.

**Comment by mattip** [comment]
> But the package for pp38 is available in PyPI.

Not as a binary wheel. When you do `pip install` and no binary wheel is available, pip downloads the source code and compiles it. That is why you have a build log: you built from source.

**Comment by Marusoftware** [comment]
Oh, sorry.
The binary wheel I used is cached wheel.
When I installed numpy first time, the result wheel was chched...

**Comment by zoomlion** [comment]
I met the same problem as you have met, I believe I have solved it in this way:
reinstall you Numpy in this method:
> pip  install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade numpy
The official package to install Numpy doesn't always work, maybe the problem of the official package.

**Comment by Marusoftware** [comment]
@zoomlion 
Thank you!
Well...What is this link (https://pypi.tuna.tsinghua.edu.cn/simple)?
Private homepage?

**Comment by zoomlion** [comment]
E, sorry for late reply. 
> https://pypi.tuna.tsinghua.edu.cn/simple 

The link is to change to source of pip or conda. You can use this way to find a new way to download packages. 
I found that some packages works if you download it from another source(link).

**Comment by seberg** [comment]
I think PyPy3.8 is now out, and there is nothing to do in NumPy itself anyway.  Thanks for the report, closing.
