### ISSUE TITLE
Problem when environment variable 'F90' is set.

### ISSUE THREAD

**Issue by t-karatsu** [numpy/numpy#18411]
There was a problem installing `scipy` and the build stopped.
This problem is related to some `numpy` source referenced at build time, so please confirm whether the following corrections are appropriate.

### Error message:
```
  File "/home/users/ea01/ea0114/spack/oss-job/spack/spack/opt/spack/linux-rhel8-a64fx/fj-4.2.1a/py-numpy-1.19.4-2xiwdvcjbqhbjvs6oj7gp2repg5xufpt/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 657, in CCompiler_get_version
    version = matcher(output)
  File "/home/users/ea01/ea0114/spack/oss-job/spack/spack/opt/spack/linux-rhel8-a64fx/fj-4.2.1a/py-numpy-1.19.4-2xiwdvcjbqhbjvs6oj7gp2repg5xufpt/lib/python3.8/site-packages/numpy/distutils/fcompiler/gnu.py", line 278, in version_match
    v = self.gnu_version_match(version_string)
  File "/home/users/ea01/ea0114/spack/oss-job/spack/spack/opt/spack/linux-rhel8-a64fx/fj-4.2.1a/py-numpy-1.19.4-2xiwdvcjbqhbjvs6oj7gp2repg5xufpt/lib/python3.8/site-packages/numpy/distutils/fcompiler/gnu.py", line 80, in gnu_version_match
    raise ValueError(err + version_string)
ValueError: A valid Fortran version was not found in this string:
frt: warning: -dumpversion is unrecognized option.
usage: frt [options] files.
```
The environment variable `F90` was set when this error occured. If `F90` is not set, no error will occur.

### Possible causes
The compile commands included in `F90` are used in the compiler version verification process for each compiler.
For example, if you set `/path_to_fujitsu_compier/frt`(Fujitsu compiler) to `F90`, it will be passed directly to the `gnu95` compiler version verification process:
```
・numpy/distutils/fcompiler/gnu.py
    executables = {
        'version_cmd'  : ["<F90>", "-dumpversion"],
```
The `frt` command can not recognize the` -dumpversion` option and issues a warning, which causes an error.
Similarly, If there are other compilers that does not recognize `-dumpversion`, that compiler is likely to have the same problem.

### Draft of correction
```
--- numpy-1.20.0/numpy/distutils/fcompiler/__init__.py.org	2021-02-04 17:38:42.000000000 +0900
+++ numpy-1.20.0/numpy/distutils/fcompiler/__init__.py	2021-02-04 18:29:21.000000000 +0900
@@ -314,7 +314,12 @@
             if not exe_from_environ:
                 possibles = [f90, f77] + self.possible_executables
             else:
-                possibles = [exe_from_environ] + self.possible_executables
+                matching_executables = []
+                for e in exe_from_environ:
+                    for p in self.possible_executables:
+                        if p in e:
+                            matching_executables.append(e)
+                possibles = [matching_executables] + self.possible_executables

             seen = set()
             unique_possibles = []
```
The command that apply to `<F90>` is decided by the `find_executables` function in `numpy/distutils/fcompiler/__init__.py`. Since the avalable command names are defined for each compiler as the `possible_executables`, 
(e.g. `possible_executables = ['gfortran', 'f95']` for the `gnu95` compiler)
add a process to check whether the command fetched from the environment variable is available.
I hope this fix will prevent unexpected command names from being used.

If it becomes a problem not to import `F90` as it is, I think that simply changing the priority of the compiler on the compiler list is one of the countermeasures:
```
・numpy/distutils/fcompiler/__init__.py
_default_compilers = (
    # sys.platform mappings
    ('win32', ('gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95',
               'intelvem', 'intelem', 'flang')),
    ('cygwin.*', ('gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95')),
    ('linux.*', ('gnu95', 'intel', 'lahey', 'pg', 'nv', 'absoft', 'nag', 'vast', 'compaq',
                 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor', 'fujitsu')),
    ('darwin.*', ('gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg')),
```

**Comment by rgommers** [comment]
Thanks for the report @t-karatsu, and sorry you didn't get a reply.

> add a process to check whether the command fetched from the environment variable is available. I hope this fix will prevent unexpected command names from being used.

I think this isn't how env vars like that work. They're interpreter like "you must use this exact compiler" - if that's not recognized then the build should fail.

Both NumPy and SciPy have switched to Meson as the build system now, so all this works differently now. Meson does respect the `FC` environment variable, similar to `F77`/`F90` in numpy.distutils.

I'll close this issue, since it no longer applies.
