### ISSUE TITLE
"TypeError" when importing numpy installed in sub-package directory

### ISSUE THREAD

**Issue by vlipovac** [numpy/numpy#18440]
Helllo,

I am writing an application which relies on numpy. Since it is used on several computers I want to avoid having to install numpy again and again, therefore I am trying to add numpy as a third-party library in a sub-package. After a successfull installation, it yields an error when imported which I was not able to fix alone.

I installed numpy using:

`python -m pip install --no-cache-dir --target=C:\MyCustomPackage\vendor --ignore-installed --upgrade numpy==1.19.3`

My package structure is

```
.MyCuytomPackage\
+-- __init__.py
+-- vendor\
|   +-- __init__.py
```

The code in `MyCustomPackage.__init__.py` is
```from .vendor import numpy```

The code in `MyCustomPackage.vendor.__init__.py` is
```
import sys
import os
mypath = os.path.abspath(os.path.dirname(__file__))
sys.path.append(r'%s' % mypath)
from . import numpy
```
I am appending `__file__` to path since I want to comfortably use `import numpy` in the remaining code of my package.
Importing `numpy` into my modules' `__init__.py` files was originally for testing reasons, but also to be able to use `MyCustomPackage.numpy`

This is the result when importing `MyCustomPackage` into a running interpreter:

![Screenshot 2021-02-18 083353](https://user-images.githubusercontent.com/68282540/108324874-be989280-71c8-11eb-8d9f-0f1f4c8b8f2a.png)

This is the respective line:
```
    float16_ma = MachArLike(f16,
                            machep=-10,
                            negep=-11,
                            minexp=-14,
                            maxexp=16,
                            it=10,
                            iexp=5,
                            ibeta=2,
                            irnd=5,
                            ngrd=0,
                            eps=exp2(f16(-10)),                <-
                            epsneg=exp2(f16(-11)),
                            huge=f16(65504),
                            tiny=f16(2 ** -14))
```

Specifics:
OS: Windows 10.0.19042
Python: 3.7.4
NumPy: 1.19.3
Pip: 21.0.1

I also have numpy installed in Python's default `Lib/site-packages` directory.

I'd appreciate any feedback.

Best regards,

**Comment by hajdukv** [comment]
Was nobody able to reproduce this error?

**Comment by rgommers** [comment]
I suspect no one tried, sorry. The cause will be `from . import numpy`. You can install `numpy` in a custom location and add that location to `sys.path`, but you cannot do a relative import like that since `numpy` isn't actually a part of your package. It would change the module name from `numpy.core` to `MyCuytomPackage.numpy.core`, and that will result in the kind of problem you are seeing here.

Using a plain `import numpy` should fix this.
