### ISSUE TITLE
Allow trailing zeros in np.bytes_

### ISSUE THREAD

**Issue by Tabrizian** [numpy/numpy#18441]
## Feature

How can I create a NumPy array of bytes that does not remove the trailing zeros? `np.bytes_` and `np.str_` remove the trailing zeros. `np.void` requires that every element of the array have the same length. Is there any dtype that can contain blob of bytes with trailing zeros and variable length?

### Reproducing code example:

```python
>>> np.array([b'\x00', b'\x01\x00'], np.void)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Invalid type promotion with void datatypes of different lengths. Use the `np.bytes_` datatype instead to pad the shorter value with trailing zero bytes.
>>> np.array([b'\x00', b'\x01\x00'], np.bytes_)
array([b'', b'\x01'], dtype='|S2')
>>> np.array([b'\x00', b'\x01\x00'], np.str_)
array(['', '\x01'], dtype='<U2')
>>> np.array([b'\x00', b'\x01\x00'], np.object_)
array([b'\x00', b'\x01\x00'], dtype=object)
```

While np.object_ works, the serialization is not appropriate for my use case, because it serializes the pointers instead of the actual underlying byte array.

### NumPy/Python version information:

NumPy Version: 1.20.1

Python: 3.8

**Comment by eric-wieser** [comment]
> Is there any dtype that can contain blob of bytes with trailing zeros and variable length?

No.

I was hoping you could use something like the following:
```python
var_void = np.dtype([('len', np.uint8), ('buff', (np.void, 255))])

def to_object(arr):
    return bytes(memoryview(arr['buff'])[:arr['len']])

def of_object(x):
    arr = np.empty((), var_void)[()]
    arr['len'] = len(x)
    memoryview(arr['buff'].view((np.uint8, 255)))[:len(x)] = x
    return arr

to_object = np.vectorize(to_object, otypes=[object])
of_object = np.vectorize(of_object, otypes=[var_void])
    
```
But `vectorize` seems to ignore the dtypes passed to otypes...

**Comment by Tabrizian** [comment]
@eric-wieser Thanks for the reply. Does it really mean that it is impossible to create an array of bytes that ends with zero? It is not an advanced feature, I'm not sure why it is hard to support this in NumPy.

**Comment by charris** [comment]
What are your trying to do, numerical values or strings?

**Comment by eric-wieser** [comment]
Numpy only supports fixed-size data-types, as the core model of strided memory only works for this case.

My post above works around this by creating a custom fixed-length type, that starts with a prefix indicating how long the value should be interpreted as. Unfortunately there's a bug / design flaw that makes it hard to use `vectorize` for this case. `np.frompyfunc` should be able to work for it though.

**Comment by Tabrizian** [comment]
@charris It can be strings or numerical values. I just want to be able to create an array that looks like below:

```python
np.array([b'\x00', b'\x01\x00'], np.bytes_)
```

**Comment by eric-wieser** [comment]
How do you propose numpy distinguish ` b'\x01\x00'` and `b'\x01' in memory?

Also, I've updated my comment above to work slightly better

**Comment by Tabrizian** [comment]
@eric-wieser Thanks! I'm not familiar with the internals of numpy.

**Comment by seberg** [comment]
I am going to close this. It is very much a valid request and unfortunate, but frankly at this time not a priority.

My preference is that such a feature should probably be prototyped outside of NumPy once possible. I admit, it is _not_ possible right now (in 1.21 it is expected to be, at least with using a bit of private numpy API).  But the thing is, that I am unwilling to consider any addition to NumPy before that in any case, it would just be too much at once...

You can use `bytes` to ignore trailing 0-bytes, and you should be able to use `void` for all equal length _including_ trailing 0 bytes.
