### ISSUE TITLE
Out of memory killer

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpy#18446]
Althought one cannot allocate a single array larger than the amount of virtual memory present, it is possible to allocate two arrays that can cause an out of memory problem.

The problem occurred for us when we allocated a single large array (i.e. more than 50% of the virtual memory), and tried to expand it (we set all known references to None, and tried to allocate a new array).

If we do
```
allocate array
set references to none

import gc
gc.collect()
allocate new array
```
it works, but if we don't invoke the garbage collector manually our program would be killed without notice. 

Since it is a little hard to reproduce issues that depend on the garbage collector behavior, I recreated a reproducing example that doesn't depend on the garbage collector.

I'm not sure there is a smart way to catch Out of Memory errors, but I figured I would ask to see if somebody smarter than me can think of a good way.

### Reproducing code example:
Note that this might make your computer crawl for 5 minutes until your linux kernel gives up and kills the program.

```
$ python allocate_crash.py 
Page faulting first array: 100%|█████████████████████████| 11114532/11114532 [00:11<00:00, 936411.18it/s]
Page faulting second array:  28%|███████▋                   | 3139071/11114532 [03:38<20:37, 6445.69it/s]
Killed
```
```python
import numpy as np
from tqdm import tqdm

import psutil

virtual_memory = psutil.virtual_memory()
available_memory = virtual_memory.available


chunk_size = 4096
array_size = int(available_memory * 0.8)

array_shape = (array_size // chunk_size, chunk_size)

a = np.empty(array_shape, dtype=np.uint8)
b = np.empty(array_shape, dtype=np.uint8)

for i in tqdm(range(a.shape[0]), desc="Page faulting first array"):
    a[i, :] = 0

for i in tqdm(range(b.shape[0]), desc="Page faulting second array"):
    b[i, :] = 0
```

### Error message:
```
$ gdb --args python allocate_crash.py 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
(gdb) run
Starting program: /home/mark/miniforge3/envs/mcam_dev/bin/python allocate_crash.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4c88700 (LWP 114790)]
[New Thread 0x7ffff4487700 (LWP 114791)]
[New Thread 0x7fffebc86700 (LWP 114792)]
[New Thread 0x7fffdb485700 (LWP 114793)]
[New Thread 0x7fffd2c84700 (LWP 114794)]
[New Thread 0x7fffca483700 (LWP 114795)]
[New Thread 0x7fffc1c82700 (LWP 114796)]
[New Thread 0x7fea21f32700 (LWP 114797)]
Page faulting first array: 100%|█████████████████████████| 11318000/11318000 [00:12<00:00, 904065.11it/s]
Page faulting second array:  25%|██████▌                   | 2863790/11318000 [01:33<8:16:13, 283.96it/s][Thread 0x7fea21f32700 (LWP 114797) exited]
[Thread 0x7fffc1c82700 (LWP 114796) exited]
[Thread 0x7fffca483700 (LWP 114795) exited]
[Thread 0x7fffd2c84700 (LWP 114794) exited]
[Thread 0x7fffdb485700 (LWP 114793) exited]
[Thread 0x7ffff4487700 (LWP 114791) exited]
[Thread 0x7ffff4c88700 (LWP 114790) exited]
[Thread 0x7ffff7c1c740 (LWP 114785) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) 

```

### NumPy/Python version information:
```
1.20.1 3.8.6 | packaged by conda-forge | (default, Nov  2 2020, 13:59:27) 
[GCC 7.5.0]
```

**Comment by mattip** [comment]
I cannot think of a clean way to catch this. But you may be interested in using file-based mmap arrays as a way to work with arrays larger than your memory size. Of course, it will need lots of disk space and will be quite slow, essentially equivalent to allocated a large swap cache.

**Comment by hmaarrfk** [comment]
Hmm, thanks for the tip mat! 

My dream is to be able to enable zero copy writes to disk. Not sure if that is possible but if you think of good way. then i would definitely be interested in knowning.

**Comment by seberg** [comment]
I am going to close this, although I think at least on linux an madvise with `MADV_WILLNEED` might cause the kernel to report an error right away, at least in most cases.  So i could imagine that calling that for large array operations, could actually mean we report errors correctly?

**Comment by hmaarrfk** [comment]
Enabling MADVISE is high on my list of priorities..... maybe it cause an error sooner. I can try to remember to report.

unfortunately, i have many other lists of priorities with no clear way to compare their priorities.

Thanks for the tip @seberg
