### ISSUE TITLE
Original error was: No module named 'numpy.core._multiarray_umath' 

### ISSUE THREAD

**Issue by ishaniis** [numpy/numpy#18451]
OS: Ubuntu 20.04
Changes made - 
in ~/.bashrc 
alias python3 = python3.7
(for specific python 3.7 requirements) 

How I installed python ? 
Python pre-installed with the Ubuntu 20.0.

How I installed numpy ?
pip3 install numpy 

Multiple Versions of Python ? 
YES (Python 3.8 and Python 3.7) 

Need help solving this error! 

`python3 spawn_npc.py -n 80
T
raceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spawn_npc.py", line 30, in <module>
    from numpy import random
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/usr/bin/python3.7",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
`

**Comment by mattip** [comment]
Maybe `/usr/bin/python3.7 -m pip install --user numpy` might help? Ubuntu tries hard to prevent you from using `pip` to install into `/usr/lib/python3` since that is where `sudo apt install python3-numpy` should go. Sometimes people succeed, usually by force-installing with `sudo pip3 install ..`, which is rarely what you want.

**Comment by seberg** [comment]
Since this was inactive for most of the year, and clearly an issue with multiple versions (or incorrect install paths or similar), closing.  There is also the new website with a bit of more hints: https://numpy.org/devdocs/user/troubleshooting-importerror.html (although I doubt it would have covered this).
