### ISSUE TITLE
The new doc pages suck

### ISSUE THREAD

**Issue by half-potato** [numpy/numpy#18457]
## Documentation
I was trying to find the right random function for my task (weighted distribution over integers) and I went to the new documentation page for [random](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#module-numpy.random). First of all, it doesn't have a list of the functions. Second, the functions that are on that page are not hyperlinked. I don't need any of the resources on that page. 

The old page for numpy looked like [this](https://numpy.org/doc/1.16/reference/routines.random.html) and is perfect for my task. I use it all the time. The old doc pages were literally some of my favorite API references, while the new pages are just useless for people experienced with numpy. 

Please reconsider the rewrite of the doc pages.

**Comment by rkern** [comment]
They're still there, and linked from the page you referenced.

https://numpy.org/doc/stable/reference/random/legacy.html

**Comment by half-potato** [comment]
How did you find that? It didn't pop up on the search, nor did it show up on the random page.

**Comment by rkern** [comment]
It's the third paragraph: "For convenience and backward compatibility, a single RandomState instance’s methods are imported into the numpy.random namespace, see Legacy Random Generation for the complete list."

**Comment by half-potato** [comment]
Oh, I see. I stopped reading the page because I didn't care about what BitGenerator I was using. It could be dual elliptic curve and it wouldn't concern me, but I see that the new API is to create a new generator, which then has all of the old functions. Also, I've noticed that it's just the new random page that's a completely different format. My bad.

**Comment by eric-wieser** [comment]
The fact that neither the legacy nor generator pages appear in the sidebar is possibly at fault for discoverability here - is there a reason they don't appear as a third-level item? (Or is that only an issue on mobile?)

**Comment by mattip** [comment]
They do not appear on desktop either. I think the top section of the document could be revised with clearer links to the [simple random data](https://numpy.org/doc/stable/reference/random/generator.html#simple-random-data) functions.
