### ISSUE TITLE
Numpy 1.20.1 source install on Ice Lake/Debian fails numpy.linalg.test()

### ISSUE THREAD

**Issue by inducer** [numpy/numpy#18471]
Numpy 1.20.1 installed from source on a fairly standard Debian system on an Intel "Icelake Client" CPU fails
```
python -c 'import numpy; numpy.linalg.test()'
```
with this log: https://gist.github.com/inducer/17675a55fc00f33b2770ab96ef43fcda

This is a "Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz" (in a "Dell XPS 13 2-in-1 7390").

Broadwell and Haswell systems running essentially the same code seem OK. The numpy wheel is also OK on the Icelake CPU.

### Reproducing code example:

```
python3 -m venv numpy-repro-env
source numpy-repro-env/bin/activate
python -m pip install --no-binary ":all:" numpy==1.20.1
python -c 'import numpy; numpy.linalg.test()'
```

### NumPy/Python version information:

```
1.20.1 3.9.1+ (default, Feb  5 2021, 13:46:56) 
[GCC 10.2.1 20210110]
```
Here's what Debian thinks of its `python3`:
```
Package: python3
Version: 3.9.1-1

-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'stable-updates'), (500, 'unstable'), (500, 'stable'), (1, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 5.10.0-3-amd64 (SMP w/8 CPU threads)
Kernel taint flags: TAINT_WARN, TAINT_OOT_MODULE, TAINT_UNSIGNED_MODULE
Locale: LANG=de_DE.UTF-8, LC_CTYPE=de_DE.UTF-8 (charmap=UTF-8), LANGUAGE=de_DE:de
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages python3 depends on:
ii  libpython3-stdlib  3.9.1-1
ii  python3-minimal    3.9.1-1
ii  python3.9          3.9.1-4

python3 recommends no packages.

Versions of packages python3 suggests:
pn  python3-doc   <none>
ii  python3-tk    3.9.1-2
ii  python3-venv  3.9.1-1

-- no debconf information
```
Shared libraries involved:
<details>
<pre>
$ for i in $(find /home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/ -name '*.so'); do echo $i; ldd $i; done
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc67dfb000)
	libopenblas.so.0 => /lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007fbd1a9f6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbd1a8b2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbd1a890000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbd1a6cb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbd1d0ba000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007fbd1a415000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fbd1a3ca000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbd1a3b0000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/core/_operand_flag_tests.cpython-39-x86_64-linux-gnu.so
	statically linked
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/core/_multiarray_tests.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fffe7e99000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1e3ddce000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1e3dfff000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/core/_umath_tests.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd28173000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0f9c1e8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0f9c404000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/core/_rational_tests.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffefb7be000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb204846000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb204a64000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/core/_simd.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffdecf66000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb086b75000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb086f1e000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/core/_struct_ufunc_tests.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffeee3d5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1c3049e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1c306b5000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/fft/_pocketfft_internal.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffdc7956000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f42ce99a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f42cebbf000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/linalg/_umath_linalg.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc3c391000)
	libopenblas.so.0 => /lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007fafe41b0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fafe3feb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fafe3ea7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fafe3e85000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007fafe3bcf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fafe64f3000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fafe3b84000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fafe3b6a000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/linalg/lapack_lite.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd11ffd000)
	libopenblas.so.0 => /lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f75aad00000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f75aab3b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f75aa9f7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f75aa9d5000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f75aa71f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f75ad023000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f75aa6d4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f75aa6ba000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/_generator.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc3f177000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f91592bf000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f91590fa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9159510000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/mtrand.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fffa63e8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f880a2aa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f880a0e5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f880a4dc000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/_bounded_integers.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd805fc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4b3a6af000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b3a4ea000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b3a890000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/_sfc64.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffeec925000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efd6001c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efd6023c000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/_common.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd6f03c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4fb39ff000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4fb3c4b000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/_philox.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fff6c9da000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd2fe055000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd2fe27d000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/_mt19937.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fff647e1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff80efde000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff80f208000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/_pcg64.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffe253a9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3827660000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3827883000)
/home/andreas/src/env-3.9/lib/python3.9/site-packages/numpy/random/bit_generator.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd83ddd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa1cb49c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa1cb6d9000)
</pre>
</details>

and, since you'll likely ask: `/lib/x86_64-linux-gnu/libopenblas.so.0` is from `libopenblas0-pthread:amd64`, which has this to say about itself:
```
Package: libopenblas0-pthread
Version: 0.3.13+ds-2

-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'stable-updates'), (500, 'unstable'), (500, 'stable'), (1, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 5.10.0-3-amd64 (SMP w/8 CPU threads)
Kernel taint flags: TAINT_WARN, TAINT_OOT_MODULE, TAINT_UNSIGNED_MODULE
Locale: LANG=de_DE.UTF-8, LC_CTYPE=de_DE.UTF-8 (charmap=UTF-8), LANGUAGE=de_DE:de
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages libopenblas0-pthread:amd64 depends on:
ii  libc6         2.31-9
ii  libgfortran5  10.2.1-6

libopenblas0-pthread:amd64 recommends no packages.

libopenblas0-pthread:amd64 suggests no packages.

-- no debconf information
```

**Comment by charris** [comment]
The NumPy wheels use OpenBLAS 'v0.3.13-62-gaf2b0d02', which may be a bit later than the Debian version and probably compiled with a different compiler. What compiler are you using?

**Comment by inducer** [comment]
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
```

**Comment by mattip** [comment]
Could you retrieve the OpenBLAS config string? One way to do that is (from [openblas_support.py](https://github.com/numpy/numpy/blob/v1.20.1/tools/openblas_support.py#L280)
```
import numpy
    import ctypes

    dll = ctypes.CDLL(numpy.core._multiarray_umath.__file__)
    if ilp64 == "64_":
        get_config = dll.openblas_get_config64_
    else:
        get_config = dll.openblas_get_config
    get_config.restype = ctypes.c_char_p
    res = get_config()
    print('OpenBLAS get_config returned', str(res))
```
If that shows `DYNAMIC_ARCH`, maybe the CPU detection is failing. Could you try forcing an architecture by using `export OPENBLAS_CORETYPE=PRESCOTT` (the [OpenBLAS FAQ](https://github.com/xianyi/OpenBLAS/wiki/Faq#usage-1) has more information), which is the minimum we use for the [NumPy build](https://github.com/MacPython/openblas-libs/blob/master/tools/build_openblas.sh#L71)

**Comment by inducer** [comment]
Using https://gist.github.com/inducer/2f8490b82128b0591fecf791edef66a6 (slightly modified from what you provided, hopefully OK), I get:
```
OpenBLAS get_config returned b'OpenBLAS 0.3.13 NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY SkylakeX MAX_THREADS=64'
```
whereas
```
$ OPENBLAS_CORETYPE=PRESCOTT python getconf.py
OpenBLAS get_config returned b'OpenBLAS 0.3.13 NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Prescott MAX_THREADS=64'
```
`OPENBLAS_CORETYPE=PRESCOTT` appears to clear the linalg test failure:
```
OPENBLAS_CORETYPE=PRESCOTT python -c 'import numpy; numpy.linalg.test()'                                                                                                           andreas@lightning 11:08
NumPy version 1.20.1
NumPy relaxed strides checking option: True
NumPy CPU features: SSE SSE2 SSE3 SSSE3* SSE41* POPCNT* SSE42* AVX* F16C* FMA3* AVX2* AVX512F* AVX512CD* AVX512_KNL? AVX512_KNM? AVX512_SKX* AVX512_CLX* AVX512_CNL* AVX512_ICL*
......................................................................................................................................................................................................................... [ 70%]
...............................................................................x.........                                                                                                                                 [100%]
305 passed, 28 deselected, 1 xfailed in 3.30s
```

`OPENBLAS_CORETYPE=HASWELL` passes as well.

The (test-passing) OpenBLAS in the numpy wheel agrees that "SkylakeX" should be the description of my system (and that makes sense to me, AVX-512 is availble):
```
OpenBLAS get_config returned b'OpenBLAS 0.3.13.dev DYNAMIC_ARCH NO_AFFINITY SkylakeX MAX_THREADS=64'
```

**Comment by thierry-FreeBSD** [comment]
Same kind of error on FreeBSD: please see https://gist.github.com/thierry-FreeBSD/916b1315f3937244fd11853b4db35c55
And OpenBLAS is identified as:
`OpenBLAS get_config returned b'OpenBLAS 0.3.15 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Nehalem MAX_THREADS=64'`

**Comment by seberg** [comment]
Closing this, since I think there were some bugs in OpenBLAS for Skylake kernels initially (and I guess the Nehalem may be equivalent).  If it goes away with `OPENBLAS_CORETYPE=PRESCOTT` there is nothing to do for us here I think.  @thierry-FreeBSD if this does not apply to you, please open a new issue.
