### ISSUE TITLE
Our github.com redirects are likely to break in April

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#18480]
_Just received this notification:_

Beginning April 15, 2021, we will stop redirecting GitHub Pages sites from *.github.com to the *.github.io domain.

Today, we serve all GitHub Pages sites from the *.github.io domain, but before 2013 we used the *.github.com domain. On April 5, 2013, we deprecated the *.github.com domain for the Pages sites and started redirecting all traffic to the new location. After April 15, 2021, we will stop doing this redirection. We are taking this action to further protect github.com overall.
How does this affect me?

If you’ve configured a custom domain for your Pages site or you directly access your site on *.github.io, you will not be affected by this change. If, however, your site still receives traffic through a redirect from *.github.com, after April 15, 2021 that URL will stop working.

To ensure all affected customers are aware of this change, during two scheduled brownouts, we will temporarily suspend redirection of Pages sites from *.github.com. The brownouts are scheduled for the following dates and times:

    April 1st, 2021 5:00pm UTC - 8:00pm UTC
    April 8th, 2021 5:00pm UTC - 8:00pm UTC

What actions should I take?

We strongly recommend that you remove any external references to *.github.com to avoid any traffic loss to your Pages sites. Additionally, we recommend that you should review your site's dependencies to check for resources that may have been hosted on Pages sites that expected a *.github.com URL. In most cases, simply updating those dependencies to use *.github.io will ensure they continue to work after April 15th.

Please contact support https://github.com/contact if you experience any issues due to these changes.

**Comment by rgommers** [comment]
What needs to happen:

1. Remove `numpy.github.com` entry in CloudFlare (hopefully without breaking anything, do at a time when you have bandwidth to deal with fallout).
2. Search for any other references to `numpy.github.com`.
3. Monitor the brownout on April 1st - if our serve-sites-from-multiple-repos approach is affected, that's when we see if we have to completely redo that whole setup or not.

**Comment by rgommers** [comment]
FYI @stefanv, @joelachance

**Comment by stefanv** [comment]
I don't expect this to affect the multi-repo approach (we don't rely on the `numpy.github.com` domain for that).

`numpy.org` correctly points to `numpy.github.io`.

We have a CAA record that points to `numpy.github.com`.  I don't know if this was ever necessary.  My guess is that it can be removed, but I am not 100% sure on that.

**Comment by joelachance** [comment]
I did update Cloudflare to `github.io` during our Github Actions attempts. So +1 with @stefanv, I dont think this should effect us.
As for the certificate, I think the `numpy.github.com` entry is simply it's name, I'm not sure sure it is related to the domain at all. I don't know how Cloudflare works, but my guess is that we still want the certificate to keep HTTPS.

**Comment by rgommers** [comment]
Sounds good, thanks both! I'll close the issue then.

> my guess is that we still want the certificate to keep HTTPS

yes, I'd think so

**Comment by stefanv** [comment]
@joelachance I have a naive understanding of this, but I thought CAA was a security mechanism that specifies who is allowed to generate certificates on your behalf.

**Comment by joelachance** [comment]
@stefanv That's my understanding too. I took at look at Cloudflare, and I don't think we need to update anything. Things in the SSL/TLS section seem happy, and the DNS settings seem good too.
I was just calling out that the name of the CAA cert in the DNS is `numpy.github.com`, but I think it would happily continue securing connections if we named it `stefans_cert`, for example :)
