### ISSUE TITLE
Hard to discover what SIMD architectures numpy was compiled with

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#18490]
I discovered this in the process of investigating https://github.com/MacPython/numpy-wheels/issues/107. A couple of related things:

- right now `np.show_config` doesn't include SIMD compilation details.
- `np.test()` prints right at the top `NumPy CPU features: SSE  ...` but it is unclear that that is local CPU capability and not what numpy was compiled with.
- The best I found to detect build settings is `np.core._multiarray_umath.__cpu_baseline__`. Did I miss anything?

**Comment by mattip** [comment]
`np.core._multiarray_umath.__cpu_baseline__` is fixed at compile time, and determines the minimum CPU features required. It is set to what we imagine the oldest supported CPU is.

`np.core._multiarray_umath.__cpu_dispatch__` is fixed at compile time, and determines the maximum CPU features available to be dispatched on to speed up operations, if they are detected at runtime. It is mainly determined by the compiler abilities. It will not include any of the `__cpu_basline__` features.

`np.core._multiarray_umath.__cpu_features__` is detected at runtime, and should be somewhere between the two. 

The code to print out that line in tests uses its [own logic](https://github.com/numpy/numpy/blob/e38a64fd8d78d838f950db685a16337aa78f9940/numpy/_pytesttester.py#L37) to show which features are available (baseline features, then the dispatch features. Each dispatch feature is marked with '*' if it is detected and '?' if not detected)

These should be properly wrapped for a nicer user experience, as part of overhauling `np.show_config`, and `np.distutils.cpuinfo`, xref gh-14492 and gh-18058.

**Comment by rgommers** [comment]
Thanks! The `*`, `?` would also be nice to make understandable without having to look up the meaning. Either with a separate entry or with a legend. How about:
```
CPU feature detection for supported SIMD architectures in this NumPy install:
  found: SSE, SSE2, ...
  not found: ..., AVXICL
```

**Comment by seiko2plus** [comment]
> The *, ?

I adopted this format from OpenCV, just one line has all the explanation which make it more friendly when you deal with a large number of CPU features.

> Either with a separate entry or with a legend

You have three params here:

- the baseline features
- dispatched features supported by the running machine `*`
- dispatched features are not supported by the running machine `?`

Adding them into your suggested format:
```
Supported SIMD extensions in this NumPy install:
  baseline: SSE, SSE2, ....
  found: SSE41, AVX2, FMA3, ...
  not found: AVX512F AVX512CD AVX512_SKX, ...
```

I think we can have both formats, and just adding the new one to `np.show_config`. what do you think?

**Comment by rgommers** [comment]
Yes, that sounds great!
