### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. 

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#18492]
I am having a very hard time getting around 
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject.
```
when building wheels using multibuild.  It only occurs on Python 3.9 on both Linux and OSX.  I am certain that I both build and test on 1.19.4.  I'm using the standard multibuild setup.

Should I be surprised by this? Are there any good workarounds?

**Comment by mattip** [comment]
What version of cython are you using?

**Comment by bashtage** [comment]
```
  Downloading numpy-1.19.4-cp39-cp39-manylinux1_i686.whl (11.5 MB)
  Downloading Cython-0.29.22-cp39-cp39-manylinux1_i686.whl (1.9 MB)
```
Looks like 0.29.22.

**Comment by charris** [comment]
You are building with one version of NumPy and testing with another. Which is which? Also make sure your repo is clean.

**Comment by bashtage** [comment]
I don't think that is possible.  Every mention in the multibuild log for NumPy says 1.19.4.

**Comment by bashtage** [comment]
When I look at a failing log the only `numpy-` that I find are 

![image](https://user-images.githubusercontent.com/5585221/109179005-5d049500-7781-11eb-8785-2825d6224153.png)

**Comment by seberg** [comment]
Its weird though 88 is the size of the struct in NumPy 1.20, not 1.19  (unless `PyObject_HEAD` is larger for some reason, but I don't think that is a thing). Is cython more strict here because the struct appears to have shrunk?  Is there any way to check which headers are included for NumPy here?

I am almost surprised we didn't see such issues more often, but the only time I feel I have seen it is when I forgot a `git clean`.

**Comment by bashtage** [comment]
Embarrassingly but not surprising @charris was correct.  Numpy 1.20 was getting silently inserted due to PEP-517 restrictions not being precise enough. pip doesn't report any of the build dependencies it installs into the clear environment (at least by default) which is where the wrong version was being downloaded.
