### ISSUE TITLE
v1.19.5 numpy.ma.masked_where, conditional argument misplaced.

### ISSUE THREAD

**Issue by pogam** [numpy/numpy#18514]
from the help 
`Signature: np.ma.masked_where(condition, a, copy=True)`

however condition seems now to be the second argument in v1.19.5

### Reproducing code example:
```
import numpy as np 
mm = np.zeros([2,2])
mm[0,1]=1
```
`np.ma.masked_array(mm==0,mm)` gives
```
masked_array(
  data=[[True, --],
        [True, True]],
  mask=[[False,  True],
        [False, False]],
  fill_value=True)
```
while `np.ma.masked_array(mm,mm==0)` gives
```
masked_array(
  data=[[--, 1.0],
        [--, --]],
  mask=[[ True, False],
        [ True,  True]],
  fill_value=1e+20)
```

**Comment by seberg** [comment]
You seem to be confusing the commands `np.ma.masked_array` and `np.ma.masked_where`. Please comment and we can reopen if I misunderstood.
