### ISSUE TITLE
Duplicated ARGOUTVIEWM typemaps in numpy SWIG interface

### ISSUE THREAD

**Issue by pkomiske** [numpy/numpy#18521]
In the provided numpy swig interface file, [numpy.i](https://github.com/numpy/numpy/blob/master/tools/swig/numpy.i), the ARGOUTVIEWM typemaps for dimension 4 arrays seem to be erroneously duplicated. Lines [2799-2949](https://github.com/numpy/numpy/blob/master/tools/swig/numpy.i#L2799-L2949) approximately duplicate lines [2951-3101](https://github.com/numpy/numpy/blob/master/tools/swig/numpy.i#L2951-L3101), with the exception of line [2890](https://github.com/numpy/numpy/blob/master/tools/swig/numpy.i#L2890) which appears to be incorrect because it only goes up to dimension 3. It seems to me that lines 2799-2949 should just be deleted. I will make a pull request with this edit.

**Comment by pkomiske** [comment]
I have submitted pull request #18522 to fix this.

**Comment by mattip** [comment]
Closing
