### ISSUE TITLE
random.choice() documentation does not inform of default values

### ISSUE THREAD

**Issue by OGordon100** [numpy/numpy#18528]
## Documentation

See https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html

`replace` does not tell the default value, and does a poor job of saying what the option actually does without looking at the examples. `p`  does not explicitly define the default as None.

These should be replaced as

replace : boolean, optional
Whether the sample is with or without replacement. Default is True, meaning that a value of `a` can be selected multiple times.

p : 1-D array-like, optional
The probabilities associated with each entry in `a`. Default is None, in which case the sample assumes a uniform distribution over all entries in `a`.

**Comment by eric-wieser** [comment]
Isn't it obvious what the defaults are from the top of the page?

![image](https://user-images.githubusercontent.com/425260/109646014-8b9eb900-7b4f-11eb-8177-c5c7f3357008.png)

I suppose it doesn't do any harm to repeat that in the parameters section though.

**Comment by rkern** [comment]
Clarifying the meaning of `replace` this way can be worthwhile. "with replacement" is commonly-known statistical jargon, but still jargon. However, `p`'s default is already described ("If not provided, ..."). When we use `None` as a default placeholder, I think the "if not provided" formulation is clearer about the intent. One rarely actually provides a `None` value.
