### ISSUE TITLE
round is too slow

### ISSUE THREAD

**Issue by yxdragon** [numpy/numpy#18525]
```python
import numpy as np

arr = np.random.rand(1024*1024).astype(np.float32)

start = time()
rst = arr.round().astype(np.int32)
print('round cost', time()-start)

start = time()
sn = np.sign(arr); sn *= 0.5; arr += sn
rst = arr.astype(np.int32)
print('sign cost', time()-start)

>>>
round cost 0.0797889232635498
sign cost 0.004990100860595703
```

why round is 20 times slower than signed + astype?

**Comment by mattip** [comment]
Try using timeit, and making arr larger. Benchmarking is tricky.

**Comment by bashtage** [comment]
You are using the fact that you know your values are between 0 and 1 in your special purpose rounder. A generic rounder will not be able to match the performance. 

A more natural way to code what you are doing it

```
import numpy as np

np.random.default_rng().integers(0,2,dtype=np.int32,size=2**20)
```

5.1 ms on my machine. A tiny bit slower, but then again, the integer sampler is generic.  An even faster way (faster than your round method) is
```
np.random.default_rng().integers(0,2,dtype=bool,size=2**20).astype(np.int32)
```

**Comment by rgommers** [comment]
This seems to be just some confusion around benchmarking. Of course, any PRs to speed up `round` or any other function are welcome. Closing, since it looks like there is nothing to do here.
