### ISSUE TITLE
ImportError: cannot import name 'multiarray' from partially initialized module 'numpy.core'

### ISSUE THREAD

**Issue by petyabaa** [numpy/numpy#18534]
Hi, I've got an error when I tried to import numpy.
I've built my python 3.9.2 by source code (gcc 7.5.0) to my Ubuntu 18.04.5. I've installed numpy with 'sudo -H pip3 install numpy'. I have also a 3.6.9 version of python installed here. I've deleted the defaultly installed 2.x versions before.

### Error message:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/lib/python3/dist-packages/numpy/core/__init__.py in <module>
     15 try:
---> 16     from . import multiarray
     17 except ImportError as exc:

ImportError: cannot import name 'multiarray' from partially initialized module 'numpy.core' (most likely due to a circular import) (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-0aa0b027fcb6> in <module>
----> 1 import numpy as np

/usr/lib/python3/dist-packages/numpy/__init__.py in <module>
    140         return loader(*packages, **options)
    141 
--> 142     from . import add_newdocs
    143     __all__ = ['add_newdocs',
    144                'ModuleDeprecationWarning',

/usr/lib/python3/dist-packages/numpy/add_newdocs.py in <module>
     11 from __future__ import division, absolute_import, print_function
     12 
---> 13 from numpy.lib import add_newdoc
     14 
     15 ###############################################################################

/usr/lib/python3/dist-packages/numpy/lib/__init__.py in <module>
      6 from numpy.version import version as __version__
      7 
----> 8 from .type_check import *
      9 from .index_tricks import *
     10 from .function_base import *

/usr/lib/python3/dist-packages/numpy/lib/type_check.py in <module>
      9            'common_type']
     10 
---> 11 import numpy.core.numeric as _nx
     12 from numpy.core.numeric import asarray, asanyarray, array, isnan, zeros
     13 from .ufunclike import isneginf, isposinf

/usr/lib/python3/dist-packages/numpy/core/__init__.py in <module>
     24 Original error was: %s
     25 """ % (exc,)
---> 26     raise ImportError(msg)
     27 
     28 for envkey in env_added:

ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from partially initialized module 'numpy.core' (most likely due to a circular import) (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

Thanks, Peter

**Comment by rgommers** [comment]
Sorry this did not receive a reply. This is a standard failed build message, so I guess something went wrong. 

> I've installed numpy with 'sudo -H pip3 install numpy'.

This may have been the problem. Never use `sudo pip install` - use `--user` or (better) a virtualenv / conda env.

I'll close this issue.
