### ISSUE TITLE
Packaging>=20.5 required for M1 build

### ISSUE THREAD

**Issue by kulinseth** [numpy/numpy#18532]
The issue is related to when installing numpy using pip on Apple M1 system. To get the correct platform tags on Apple M1 mac, the changes have been upstreamed on setuptools.

### Reproducing code example:
1. Download and install the latest python3 from https://www.python.org/ftp/python/3.9.2/python-3.9.2-macos11.pkg
2. `python3 -m pip install --force-reinstall numpy`

### Error message:
The build fails with 
    assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_universal2')

### NumPy/Python version information:
python version is 3.9.2
numpy version is  1.20.1

After checking out the numpy source and updating the setuptools dependency in numpy, I was able to fix the issue and install numpy :

1. git clone https://github.com/numpy/numpy.git
2. cd numpy , and the patch below
3. `python3 -m pip install .`

```
diff --git a/pyproject.toml b/pyproject.toml
index b1ffd8c76..aed86ca1f 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,7 +1,7 @@
 [build-system]
 # Minimum requirements for the build system to execute.
 requires = [
-    "setuptools<49.2.0",
+    "setuptools>=54",
     "wheel==0.36.2",
     "Cython>=0.29.21,<3.0",  # Note: keep in sync with tools/cythonize.py
 ]
```
Output for the  numpy and sys version:

1.21.0.dev0+922.g168978df6 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:08:59) 
[Clang 12.0.0 (clang-1200.0.32.29)]

**Comment by mattip** [comment]
The setuptools release notes do not mention the need to upgrade. Are you sure this is setuptools and not pip/wheel/packaging?

**Comment by lawrence-danna-apple** [comment]
> Are you sure this is setuptools and not pip/wheel/packaging?

The issue was fixed in  [pypa/packaging/pull/319](https://github.com/pypa/packaging/pull/319). `packaging` is vendored in both `setuptools` and `pip`.    In this case we tested upgrading `pip` to the latest version, but that was not sufficient to get `numpy` to build, but the change to `pyproject.toml` does fix it.

**Comment by mattip** [comment]
That PR to pypa/packaging made it into version 20.5, and is not part of setuptools 54.0.0, which (in version 49.0.0+) vendors packaging 19.2. Something is fishy.

**Comment by mattip** [comment]
The error "assert tag in supported_tags" comes from wheel's `bdist_wheel.py`, which is not part of setuptools. In turn, the tags it is referring to come from pypa/packaging/tags.py, so somehow the build is getting version 20.5 of packaging. Perhaps it would be better to directly pin packaging rather than changing the pinning of setuptools.

**Comment by kulinseth** [comment]
Thanks for taking a look Matt. There seems to be stale dependency when trying to pick up packaging from setuptools. The idea of pinning packaging worked for me:

```
diff --git a/pyproject.toml b/pyproject.toml
index b1ffd8c76..105cd06c1 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,6 +1,7 @@
 [build-system]
 # Minimum requirements for the build system to execute.
 requires = [
+    "pip>20.5",
     "setuptools<49.2.0",
     "wheel==0.36.2",
     "Cython>=0.29.21,<3.0",  # Note: keep in sync with tools/cythonize.py
```

**Comment by mattip** [comment]
I think you meant "packaging==20.5" (packaging != pip, and it is better never to leave an open ended highest version). Feel like making a PR? Note that an additional advantage to pinning to a version is that makes it easier to get notified by dependabot when a new release is available.

**Comment by kulinseth** [comment]
My bad, yes. I will create a PR, i tested with :
```
python3 -m pip install --force-reinstall .
```
diff:
```
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,6 +1,7 @@
 [build-system]
 # Minimum requirements for the build system to execute.
 requires = [
+    "packaging==20.5",
     "setuptools<49.2.0",
     "wheel==0.36.2",
     "Cython>=0.29.21,<3.0",  # Note: keep in sync with tools/cythonize.py
```

**Comment by kulinseth** [comment]
https://github.com/numpy/numpy/pull/18538

**Comment by bashtage** [comment]
@mattip I suspect this can be closed.
