### ISSUE TITLE
Documentation Page Layout on Mobile

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#18549]
## Documentation

The current layout requires me to scroll through about three full screens of what should be side-bar material. I am currently using Firefox 68.7.0 on a Motorola e5. The issue does not seem to be limited to my phone or browser.

Here is a screenshot of `np.roots` as an example:

![Screenshot_20210304-221849](https://user-images.githubusercontent.com/4617010/110067815-76d64700-7d42-11eb-9ec2-d90505a30927.png)
![Screenshot_20210304-221909](https://user-images.githubusercontent.com/4617010/110067833-7dfd5500-7d42-11eb-86c9-d3f9bb8173a6.png)
![Screenshot_20210304-221918](https://user-images.githubusercontent.com/4617010/110067841-8190dc00-7d42-11eb-8389-b591395eb619.png)
![Screenshot_20210304-221924](https://user-images.githubusercontent.com/4617010/110067848-848bcc80-7d42-11eb-8b7f-3a043792a53b.png)

While the new navigation info is sometimes useful, I'm not sure it's the first thing that should be shown on mobile, ahead of the main content.

**Comment by eric-wieser** [comment]
This might be better filled against the pydata sphinx theme

**Comment by madphysicist** [comment]
@eric-wieser What's the difference between that and numpydoc?

**Comment by madphysicist** [comment]
@eric-wieser Done

**Comment by eric-wieser** [comment]
Nympydoc is a docstring parser for sphinx as I understand it, and isn't involved in rendering sphinx do trees to html

**Comment by tupui** [comment]
FYI this is solved in newer versions of the theme. But you have the same issues as with SciPy, 0.10 introduced build speed regressions for projects using templates so we cannot update yet.

**Comment by mattip** [comment]
The speed regression problem is discussed in pydata/pydata-sphinx-theme#889

**Comment by seberg** [comment]
Solved, and not a NumPy issue (pydata sphinx theme one) to begin with.
