### ISSUE TITLE
DOC: false claim about default integer type in "Array creation" basics

### ISSUE THREAD

**Issue by adeak** [numpy/numpy#18540]
The [Array creation](https://numpy.org/devdocs/user/basics.creation.html#converting-python-sequences-to-numpy-arrays) part of the Fundamentals user guide contains the following paragraph (line 78 in `doc/source/user/basics.creation.rst`):
```
The default NumPy behavior is to create arrays in either 64-bit signed
integers or double precision floating point numbers, ``int64`` and
``float``, respectively. If you expect your arrays to be a certain type,
then you need to specify the ``dtype`` while you create the array.
```
This is infamously untrue: the default integer type is platform-dependent, being `int32` on windows, alas.

I don't know whether this user guide page should get into this issue, although my hunch is that the more places this quirk is mentioned early on, the better. But I don't know what depth it's appropriate to discuss this, and whether there are other parts of the documentation we can point users to (which is why this is just an issue and not a PR).

**Comment by Dan-Patterson** [comment]
agreed.... from np.array

dtypedata-type, optional
The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence.

**Comment by leofang** [comment]
This is definitely an annoying one. We from CuPy are fixing a lot of Windows errors because the default int on Windows is `int32`, not `int64`. I feel it's better to fix the code instead of fixing the doc...

**Comment by adeak** [comment]
To be clear we're stuck with the behaviour. Nobody likes it, but it's so fundamental to numpy that it can't really be changed without an opt-in process, and as I understand the machinery is not there to do that. As I understand some open NEPs such as [NEP 31](https://numpy.org/neps/nep-0031-uarray.html) might make it possible to say _once_ that you want your ints to be 64-bit.

But until that happens the behaviour is a given, and all we can do is make it loud and clear in the documentation. This is what this issue is about.

**Comment by amrit110** [comment]
Hi, new contributor here. From the discussion above, seems like making it more explicit in the documentation about the default integer type of the created array for now can be useful. Shall I submit a PR?

**Comment by adeak** [comment]
Hi @amrit110, and welcome :) I've been hoping for some official feedback on the issue, to make sure I'm not missing some subtlety. But the default integer type being different on windows is a fairly robust feature of numpy, so I think opening a PR to fix this in some way would be welcome. Numpy developers can help polish the exact wording in review if necessary.

**Comment by amrit110** [comment]
Thanks @adeak! I've opened a PR with a simple addition to clarify the difference in default int array type for windows. As I understand it, the difference is because of the C long type being int32 on Windows (https://docs.microsoft.com/en-us/cpp/c-language/storage-of-basic-types?redirectedfrom=MSDN&view=msvc-160) as opposed to int64 on unix platforms. Looking forward to any review comments about the exact wording!
