### ISSUE TITLE
numpy.append() similar to std::vector insert

### ISSUE THREAD

**Issue by justinblaber** [numpy/numpy#18561]
I find myself wanting this feature often. The problem with np.append() is I think every time its called it reallocates and copies the arrays, so its very slow.

std::vector I believe has an implementation where the underlying buffer is doubled in size whenever space runs out, so amortized time for inserting is very fast. 

Typically, to get around this I use a python list which has a faster insert, but then i have to convert it to a numpy array which is annoying. 

Is this sort of feature feasible?

**Comment by eric-wieser** [comment]
This is feasible if you know in advance which axes you intend to expand along - but my gut feel is that this would do better as a third party package.

**Comment by eric-wieser** [comment]
The trick is roughly:
* Allocate the larger array
* Slice it down to the initial size
* In your `expand_array(a)` function, use `a.base` to get back to the original expanded array you allocated, and take a larger view of it

**Comment by seberg** [comment]
If you only need basic storage types (e.g. numerical) and a 1-D result. Using the python builtin `array.array` is probably a good method.  It is constructed like a list and will export buffers fine (so no-copy converting to a NumPy array once build).

I personally doubt that NumPy arrays themselves should really grow this type of capabilities, since they are really designed to be immutable containers in most ways.  I suppose it may be plausible to have a subclass/variant of ndarray which does support it, either with less powerful `view` semantics, or more sophisticated memory management (similar to the Python `memoryview`).

**Comment by IchiruTake** [comment]
> I find myself wanting this feature often. The problem with np.append() is I think every time its called it reallocates and copies the arrays, so its very slow.
> 
> std::vector I believe has an implementation where the underlying buffer is doubled in size whenever space runs out, so amortized time for inserting is very fast.
> 
> Typically, to get around this I use a python list which has a faster insert, but then i have to convert it to a numpy array which is annoying.
> 
> Is this sort of feature feasible?

No, the data structure of numpy array is just a fixed array, which thus allowing lower memory allocation and index vectorization. Different from Python List, which acts as a generic stack. I don't really sure what the task you want.

Secondly, the problem you have mentioned related to memory leakage where you create an object, but when you allocate new object by that variable [name], the old objects is not deleted and store somewhere. You would need `del `function to delete that object before re-assigning new object

**Comment by rgommers** [comment]
Agreed with the replies, this can be done as a third-party implementation if desired. But using `np.append` to begin with is usually not the right tool for the job. For those reasons, let's close this issue. Thanks all!

**Comment by vadimkantorov** [comment]
I agree, ".extend" primitive is sometimes useful - when we need to concatenate large array chunks loaded from some other place and cannot afford enough memory to hold both the chunks and the concatenated result. "dynamic array" data-structure is quite wide-spread in other contexts, so might be good to have such a shortcut in core
