### ISSUE TITLE
Applying radial force on a cylinder shape by python libraries, preferring numpy

### ISSUE THREAD

**Issue by alisheikholeslam** [numpy/numpy#18564]
I have used the code below to apply force on some points toward 0,0,0 Coordinate. How to change this code to apply force radially, which applied toward z axis? (I want to do this by python libraries such as numpy)
```
points_coordinate = [[x1,y1,z1],...]
force = -1e-3 * (points_coordinate.T/numpy.linalg.norm(points_coordinate,axis=1)).T
```
how to use numpy.linalg.norm only for XY plane vector calculation?

**Comment by rkern** [comment]
```python
points_coordinate = np.array([[x1,y1,z1],...])
# Project the points onto the X-Y plane by zeroing out the Z coordinate
pc_xy = points_coordinate.copy()
pc_xy[:, 2] = 0.0
force = -1e-3 * (pc_xy.T / np.linalg.norm(pc_xy, axis=1)).T
```

We try to keep Github issues related to bug reports and feature requests. Please subscribe to the [numpy-discussion mailing list](https://www.scipy.org/scipylib/mailing-lists.html) or use a forum like StackOverflow to ask for recommendations on how to use numpy to do particular tasks like this one. Thanks!

**Comment by seberg** [comment]
I am going to close the issue if there is something to follow up, please feel free to continue posting!
