### ISSUE TITLE
CircleCI is failing on merges.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#18568]
See https://tinyurl.com/ya4kod3a for an example. These failures started after the master rename but I don't know that that is the cause.

**Comment by seberg** [comment]
Ah, I will make a PR with a fix, thanks for the note. The problem is that we use `git init`, and that defaults to "master".

**Comment by seberg** [comment]
Arrg, that didn't work. The git on CircleCI doesn't have the `--initial-branch` option apparently!

**Comment by seberg** [comment]
OK, finally fixed by gh-18572.
