### ISSUE TITLE
Misleading error message when stacking a single empty array

### ISSUE THREAD

**Issue by bersbersbers** [numpy/numpy#18589]
### Reproducing code example:

```python
import numpy as np
arr = np.empty(0)
np.stack(arr)
```

### Error message:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<\_\_array_function__ internals>", line 5, in stack
  File ".../numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')

https://github.com/numpy/numpy/blob/2ea7ebdc4294868ec982ad6310d0daf6477fabfc/numpy/core/shape_base.py#L421-L423

This error message implies that no array way passed as an argument, but the argument is an array already. The error message might say something like "non-empty array".

### NumPy/Python version information:

1.19.5 3.8.8 (default, Feb 22 2021, 14:04:38)

**Comment by bersbersbers** [comment]
Alternatively, `np.stack` might return `np.zeros(0)` when an empty array is passed.

**Comment by seberg** [comment]
Closing, the behaviour of rainsing an error seem correct and the explenation fine. Please post if there is something I am missing.

**Comment by bersbersbers** [comment]
1. Error message: I am passing an `array`, and numpy tells me it needs at least one array. That in itself is confusing to me, and numpy could do better by giving a better error message. It could say it needs a "*sequence holding* at least one array", which is consistent with the documentation.

2. Behavior: numpy could also be improved to behave more leniently: note that `np.zeros` expects a shape, which usually is a tuple. Nonetheless, `np.zeros(4)` works, which is helpful to new users. Similary, `np.stack(arr)` could be understood as `np.stack([arr])`. I don't see how interpreting this as `np.stack(list(arr))` is practically useful: as far as I can see, engineering an `array` holding other arrays that can be stacked is pretty hard: even
```python
np.array([np.array([4, 5]), np.array([6, 7])], dtype=object)
```
is merged down to a non-nested array.
```python
np.array([np.array([4, 5]), np.array([6, 7, 8])], dtype=object)
```
can be created as a nested `array` because the dimensions are not identical, but that means exactly they cannot be stacked.

So the only way (that I see) to create a nested array that *can* be merged is by creating a nested array that *cannot* be merged and then replacing the elements of that nested array such that stacking becomes possible. Pretty convoluted (and deprecated anyway).

**Comment by eric-wieser** [comment]
What exactly do you expect `np.stack(arr, axis=axis)` to do? It sounds like you might be looking for `np.moveaxis(arr, 0, axis)` instead

**Comment by bersbersbers** [comment]
I'd expect `np.stack(arr, axis=axis)` to return the same thing as `np.stack([arr], axis=axis)` (for convenience, mainly).

**Comment by eric-wieser** [comment]
This doesn't sound convenient to me. `zeros(2)` is convenient because it saves you typing parentheses of `zeros((2,))`. That argument doesn't apply to `np.stack([arr])`, because we already have a shorter spelling for that; `arr`

**Comment by bersbersbers** [comment]
Agreed, I withdraw the "convenience" argument :) Also, I now understood that 

> `np.stack(arr)` is interpreted as `np.stack(list(array))`

is not how it's literally implemented.

Still, users who issue `np.stack(arr)` after `arr = np.empty(0)` see an incorrect (in my opinion) error message that is very easy to fix.
