### ISSUE TITLE
MAINT: Handle lint failures blocking the CI

### ISSUE THREAD

**Issue by ganesh-k13** [numpy/numpy#18587]
The problem at hand is to unblock the CI from lint failures, so how about making the tests independent of lint in one of Azure or Actions as we have both?

_Originally posted by @ganesh-k13 in https://github.com/numpy/numpy/issues/18579#issuecomment-795429471_

**Comment by bashtage** [comment]
You can tell Azure to not fail when a specific task fails. The bigger issue is that if linting is part of CI then incorrect formatting shoudl fail CI. Why do you want to not fail CI when code is misformatted?

**Comment by ganesh-k13** [comment]
Hey @bashtage , here is a bit more context to this: https://github.com/numpy/numpy/pull/18579#issuecomment-795419138

**Comment by bashtage** [comment]
Then you add `continue-on-error`

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error

**Comment by ganesh-k13** [comment]
Oh that's nice. @mattip , @rgommers , @seberg what say for this?

**Comment by seberg** [comment]
Sounds good to me! Right now it seems not finish CI and making it impossible to merge due to a tiny violation is a bigger issue than finding the perfect solution.

**Comment by ganesh-k13** [comment]
One tiny issue or rather a query as the documentation is not super clear: `continue-on-error` is a `step` level flag as per docs, will it work for `needs` as well?

**Comment by bashtage** [comment]
Submit a PR with it and find out.

**Comment by ganesh-k13** [comment]
Yeah, that seems to be the case: https://github.com/actions/toolkit/issues/399#issuecomment-674594836 and https://github.com/actions/toolkit/issues/399#issuecomment-620367853. Yeah, will try something out, best way to test it out.

**Comment by ganesh-k13** [comment]
For future reference, there are two types of continue-on-error:
1. One for step level, this will let the other steps run, but fails the job on the whole. [ref](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)
2. Job level continue: Here, it may fail in any step *AND* the job will show failed. But the dependant jobs will continue. [ref](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error)
