### ISSUE TITLE
Annotations don't import np.lib.*

### ISSUE THREAD

**Issue by bmerry** [numpy/numpy#18601]
When one imports numpy, the various `np.lib.*` modules are automatically imported. However, the type annotations don't reflect this.

### Reproducing code example:

```python
import numpy as np
np.lib.stride_tricks.DummyArray```

### Error message:

When run with mypy 0.790:
```
st.py:2: error: Module has no attribute "stride_tricks"
Found 1 error in 1 file (checked 1 source file)
```

### NumPy/Python version information:

1.20.1 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]

**Comment by BvB93** [comment]
The `test_public_api` tests claim that the `np.lib.slide_tricks` is a private module though.
Can anyone comment on how up to date the list below is?
https://github.com/numpy/numpy/blob/e376a885bc5545b79e88c155f0aebba27bab639d/numpy/tests/test_public_api.py#L273-L288

**Comment by bmerry** [comment]
Some of the methods in stride_tricks are [publicly documented](https://numpy.org/doc/stable/reference/routines.indexing.html#indexing-like-operations).

The bug also applies to modules that are listed as public in that test e.g. `np.lib.recfunctions`.
