### ISSUE TITLE
Array with shape==(1,) plus empty list or array

### ISSUE THREAD

**Issue by gentlegiantJGC** [numpy/numpy#18600]
Hello, I am not entirely sure if this is a bug or an intended feature. If the behaviour is intended I can't work out what reason it is there for.

First noticed in Numpy 1.19.1 and reproduced in 1.20.1

### Reproducing code example:

```python
import numpy as np
print(np.array([0]) + [])
print(np.array([0]) + np.array([]))
```

### Output
```
array([], dtype=float64)
array([], dtype=float64)
```

### Expected behaviour

I was expecting an error like you would get if you added two arrays together of different sizes.
```
numpy.array([0,0]) + numpy.array([])
numpy.array([0,0]) + []
ValueError: operands could not be broadcast together with shapes (2,) (0,)
```

### NumPy/Python version information:

1.20.1 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
`np.array([1]) + []` means "add 1 to every element of `[]`", just as `np.array([1]) + [1, 2, 3]` means "add 1 to every element of `[1, 2, 3]`". This is called broadcasting.

**Comment by gentlegiantJGC** [comment]
Ah okay. I was thinking of the first value as an array rather than a scalar. Thanks
