### ISSUE TITLE
Incorrect string representation of float16 and float32 for large powers of 2

### ISSUE THREAD

**Issue by clydeclements** [numpy/numpy#18608]
When using `np.float16` and `np.float32` types, I am seeing incorrect string representations of certain numbers that are powers of 2.

### Reproducing code example:

For `np.float16` the problem starts at `2**13` (or 8192):
```python
>>> import numpy as np
>>> np.float16(8192)
8190.0
```

The floating-point numbers immediately before and after that number have the correct string representations:
```python
>>> np.float16(8188)
8188.0
>>> np.float16(8200)
8200.0
```

The problem also occurs for the remaining larger powers of 2 (for those numbers representable as `np.float16`). For example:
```python
>>> np.float16(16384)
16380.0
```

Additionally, similar problems occur for `np.float32` once you reach `2**29`:
```python
>>> np.float32(536870912)
536870900.0
```

### Error message:

There is no error message, rather an incorrect string representation of some floating-point numbers.

### NumPy/Python version information:

```
1.19.2 3.9.1 (default, Dec 11 2020, 06:28:49)
[Clang 10.0.0 ]
```

**Comment by ksunden** [comment]
Saying it is "wrong" is not quite accurate...

IEEE754 16 bit floats have only ~3.3 decimal digits worth of precision (11 bits). Thus the representation for 8190 is exactly the same as 8192. 

Numpys string formatting defaults to the least precise decimal representation which is unique for the floating point number. so it is a bit of a coincidence that the "previous" one had an extra digit of precision (since the next closest after that needed a 4th sig fig to differentiate) and that the "next" one was exact at 8200.

If you look at a larger list, you can see this trend clearly:

```
>>> np.float16(range(8100, 8300))
array([8100., 8100., 8104., 8104., 8104., 8104., 8104., 8108., 8108.,
       8108., 8110., 8110., 8110., 8110., 8110., 8116., 8116., 8116.,
       8120., 8120., 8120., 8120., 8120., 8124., 8124., 8124., 8130.,
       8130., 8130., 8130., 8130., 8132., 8132., 8132., 8136., 8136.,
       8136., 8136., 8136., 8140., 8140., 8140., 8144., 8144., 8144.,
       8144., 8144., 8148., 8148., 8148., 8150., 8150., 8150., 8150.,
       8150., 8156., 8156., 8156., 8160., 8160., 8160., 8160., 8160.,
       8164., 8164., 8164., 8170., 8170., 8170., 8170., 8170., 8172.,
       8172., 8172., 8176., 8176., 8176., 8176., 8176., 8180., 8180.,
       8180., 8184., 8184., 8184., 8184., 8184., 8188., 8188., 8188.,
       8190., 8190., 8190., 8190., 8190., 8190., 8190., 8200., 8200.,
       8200., 8200., 8200., 8200., 8200., 8210., 8210., 8210., 8210.,
       8210., 8210., 8210., 8210., 8210., 8216., 8216., 8216., 8216.,
       8216., 8216., 8216., 8220., 8220., 8220., 8220., 8220., 8220.,
       8220., 8220., 8220., 8230., 8230., 8230., 8230., 8230., 8230.,
       8230., 8240., 8240., 8240., 8240., 8240., 8240., 8240., 8240.,
       8240., 8250., 8250., 8250., 8250., 8250., 8250., 8250., 8260.,
       8260., 8260., 8260., 8260., 8260., 8260., 8260., 8260., 8264.,
       8264., 8264., 8264., 8264., 8264., 8264., 8270., 8270., 8270.,
       8270., 8270., 8270., 8270., 8270., 8270., 8280., 8280., 8280.,
       8280., 8280., 8280., 8280., 8290., 8290., 8290., 8290., 8290.,
       8290., 8290., 8290., 8290., 8296., 8296., 8296., 8296., 8296.,
       8296., 8296.], dtype=float16)
       ```
      
(these priciples extend to float32 which has ~7 decimal digits precision and even float64 and float 128)


For the record, this choice of "least precise that is unique" is why we get to see `0.1`, a number which is not exactly represented by binary, rather than the precise `0.100000001490116119384765625` (for 32 bit).

**Comment by clydeclements** [comment]
Ah, "least precise that is unique". I see now how NumPy arrives at that output. However, to convey the limited digits of precision of float16, I would have expected the string representation to be something like `8190` (or `8.19E3`) and not `8190.0`. The trailing `.0` in the output is surprising to me.

Thanks for the prompt reply!

**Comment by eric-wieser** [comment]
> The trailing `.0` in the output is surprising to me.

I think the idea here is to remind you you're looking at a float and not an integer, which is why we don't use `8190`.

**Comment by clydeclements** [comment]
Okay, now I understand the full reasoning.

I've looked at the referenced documentation for `set_printoptions` and I've been experimenting with that. From what I've seen so far, none of those options affect the printing of scalars, only arrays. (Well except for the `legacy='1.13'` option.) Is that indeed the case?

**Comment by eric-wieser** [comment]
Yes, I think that is the case. Numpy `floatXY` scalars are designed to print out in the same way as python `float` scalars, and like python scalars this printing isn't configurable.

You can always call `np.format_float_scientific` to manually format numpy float scalars.

**Comment by clydeclements** [comment]
Thanks @ksunden and @eric-wieser for straightening out my understanding of this!

**Comment by melissawm** [comment]
Closing as I believe the issue has been clarified, please reopen if this is not the case.
