### ISSUE TITLE
Latest opensuse update broke github actions.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#18619]
See https://tinyurl.com/yj8mngo4 where the Release file was just updated. The github actions error message is:
```
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' no longer has a Release file.
```
I suspect a github script is missing an `sudo apt update`.

**Comment by mattip** [comment]
The error happens during [`sudo apt update`](https://github.com/numpy/numpy/runs/2113623143?check_suite_focus=true#step:4:59). The repo also [does not have a ssl cert](https://github.com/numpy/numpy/runs/2113623143?check_suite_focus=true#step:4:102), so I wonder what is going on.

**Comment by charris** [comment]
I can't figure out where openSUSE comes from in the first place.

**Comment by mattip** [comment]
I tried to look at the [virtual env](https://github.com/numpy/numpy/runs/2113935180?check_suite_focus=true#step:1:6) and figure out where the [source comes from](https://github.com/actions/virtual-environments/blob/ubuntu20/20210309.1/images/linux/Ubuntu2004-README.md) but didn't get very far in finding the sources for `apt update`

**Comment by mattip** [comment]
I restarted the job and it seems to be getting past that point, so maybe it was just a temporary thing.
