### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by Demokritus** [numpy/numpy#18628]
### Steps to reproduce:

In python3 interactive shell gave error message after the attempt to import numpy

The package was installed in Miniconda - conda-4.9.2  in virtual environment
with python=3.7.10 and numpy=1.9.2.
OS - Linux.

### Error message:
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

^[[?2004l^MTraceback (most recent call last):
  File "/home/gsergei/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/home/gsergei/.local/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/gsergei/.local/lib/python3.6/site-packages/numpy/core/overrides.py", line 9, in <module>
    from numpy.core._multiarray_umath import add_docstring, ndarray
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gsergei/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/gsergei/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /scratch/gsergei/miniconda3/envs/py37/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by mattip** [comment]
Please see https://numpy.org/doc/stable/user/troubleshooting-importerror.html

Somehow you are using python from `/scratch/gsergei/miniconda3/envs/py37/bin/python3` but importing NumPy from `/home/gsergei/.local/lib/python3.6/site-packages/numpy`. Note the python3.6 in the import path. This would suggest you have one of the `PYTHON*` environment variables set, like `PYTHONPATH` or `PYTHONSTARTUP`. You can try using `python -E ...` to run your script which will ignore all the `PYTHON*` environment variables.

**Comment by Demokritus** [comment]
> Please see https://numpy.org/doc/stable/user/troubleshooting-importerror.html
> 
> Somehow you are using python from `/scratch/gsergei/miniconda3/envs/py37/bin/python3` but importing NumPy from `/home/gsergei/.local/lib/python3.6/site-packages/numpy`. Note the python3.6 in the import path. This would suggest you have one of the `PYTHON*` environment variables set, like `PYTHONPATH` or `PYTHONSTARTUP`. You can try using `python -E ...` to run your script which will ignore all the `PYTHON*` environment variables.

You advice helped me to solve this issue. Thank you very much.
