### ISSUE TITLE
np.nan weird behaviour on mac arm64

### ISSUE THREAD

**Issue by chumaroz** [numpy/numpy#18647]
### Reproducing code example:

```python
import numpy as np
np.isnan(np.nan)
```

### Error message:

the above code results in False. 
In other words, nan values are not recognized as nan.

### NumPy/Python version information:

1.18.5 3.8.8 (default, Feb 26 2021, 09:10:27) 
[Clang 12.0.0 (clang-1200.0.32.29)]

**Comment by iaryangoyal** [comment]
try to use this
import numpy as np 
np.isnan(np.inf)

**Comment by Qiyu8** [comment]
Have you tried upgrading your version? The result in my ARM64 machine is correct.

**Comment by iaryangoyal** [comment]
yeah I have tried

**Comment by chumaroz** [comment]
> try to use this
> import numpy as np
> np.isnan(np.inf)

@iaryangoyal here I got false as well.

**Comment by chumaroz** [comment]
> Have you tried upgrading your version? The result in my ARM64 machine is correct.

@Qiyu8 where did you get your numpy then? I installed it using the following link:
https://github.com/apple/tensorflow_macos

**Comment by chumaroz** [comment]
appears that numpy package from that [link](https://github.com/apple/tensorflow_macos) is broken.
Installing python 3.8.6 from the python.org and intalling numpy via `python3.8 -mpip install numpy` solves the issue
