### ISSUE TITLE
datetime64 missing type overload for datetime.date

### ISSUE THREAD

**Issue by DStauffman** [numpy/numpy#18640]
### Typing code example:

```python
import datetime
import numpy as np
d = np.datetime64(datetime.date(2021, 3, 17))
```

### Run mypy on file

```
untitled.py:3: error: No overload variant of "datetime64" matches argument type "date"  [call-overload]
untitled.py:3: note: Possible overload variant:
untitled.py:3: note:     def datetime64(self, Union[None, datetime64, Union[str, bytes], datetime] = ..., Union[Union[str, bytes], Tuple[Union[str, bytes], Union[int, integer[Any]]]] = ...) -> datetime64
scripts\untitled0.py:3: note:     <1 more non-matching overload not shown>
Found 1 error in 1 file (checked 1 source file)
```

Running the code with a datetime.datetime works fine, so it appears that numpy is missing datetime.date in the Union of allowable types to pass to np.datetime64

### NumPy/Python version information:

1.20.1 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]

**Comment by BvB93** [comment]
Since `datetime.date` is a superclass of `datetime.datetime`, fixing this issue would be as easy as replacing the later with the former.
Would you be willing to create a PR?

**Comment by BvB93** [comment]
Correction: `np.datetime64` seems to accept any object with the `date`, `month` and `year` attributes: https://github.com/numpy/numpy/blob/bac1f7b06995dbed32d057c93c8c3f580bdedb07/numpy/core/src/multiarray/datetime.c#L2102-L2107

In light of this a protocol might would be more suitable as a replacement:
``` python
class _DatetimeScalar(Protocol):
    @property
    def day(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def year(self) -> int: ...
```

**Comment by DStauffman** [comment]
Yes, I can take a shot at a PR for this.

**Comment by Grasin98** [comment]
I would like to contribute to this. Since I am new to this, could you guide me?

**Comment by mattip** [comment]
Are static typing issues candidates for the "good first issue" label? I would have thought static typing is a difficult subject for beginners to dive into.

**Comment by BvB93** [comment]
> Are static typing issues candidates for the "good first issue" label?

As a general rule I'd say no. Every rule has its exception though, and this particular issue has a small scope and well-defined solution:
replace `dt.datetime` in the `np.datetime64` constructor with aforementioned protocol (https://github.com/numpy/numpy/issues/18640#issuecomment-802045607).

**Comment by oscar139** [comment]
I am new and I was just going to follow along. But after reading up on protocols, mypy, static typing and such. I plugged in @BvB93's recommendations. 

mypy runs on the following
```
import datetime
import numpy as np
d = np.datetime64(datetime.date(2021, 3, 17))
```
with output
```
Success: no issues found in 1 source file
```

**Comment by DStauffman** [comment]
I looked over @oscar139 changes and they look good to me.  I had started working on this but never finished it.  One thing I would recommend is to also add a test case with the datetime.date input to np.datetime64.  In `numpy/tests/data/pass/scalars.py` around line 87, I would add 'np.datetime64(dt.date(2000, 5, 3))` or something along those lines.  Do you want to put that is the same pull request?

**Comment by oscar139** [comment]
Right I meant to ask about testing. I read in the contributing guide...
> write tests that fail before your change and pass afterward 

But as I understand it there isn't anything failing before to pass now aside from the checker (mypy). 

Also this might be picky but @BvB93 points out that... 
> np.datetime64 seems to accept any object with the date, month and year attributes: 

I understand that we need only check for those properties but we named the protocol _DatetimeScalar would _DateScalar be more consistent?

**Comment by oscar139** [comment]
### Update 
Thanks @DStauffman you got me to examine runtest.py and find that there is a mypy option for covering such things. Which fails before the change and then passes after for case `np.datetime64(dt.date(2000, 5, 3))`. I am feeling confident in my work and I am creating the pull request
