### ISSUE TITLE
numpy.nanstd and numpy.nanvar support's ddof to take float while docs mention it to take int, optional

### ISSUE THREAD

**Issue by rawwar** [numpy/numpy#18650]
numpy.nanstd and numpy.nanvar support's ddof to take float while docs mention it to take int, optional
### Reproducing code example:

```python
import numpy as np
In [9]: a = np.array([1,1.5,2,2.5,np.nan])

In [10]: np.nanstd(a)
Out[10]: 0.5590169943749475

In [11]: np.nanstd(a,ddof=1)
Out[11]: 0.6454972243679028

In [12]: np.nanstd(a,ddof=1.5)
Out[12]: 0.7071067811865476

In [13]: np.nanvar(a)
Out[13]: 0.3125

In [14]: np.nanvar(a,ddof=1)
Out[14]: 0.4166666666666667

In [15]: np.nanvar(a,ddof=1.5)
Out[15]: 0.5
```

Further, after studying about degree's of freedom, i understand that it can a fractional.  Below quote is from [wikipedia article](https://en.wikipedia.org/wiki/Degrees_of_freedom_(statistics))
>In the application of these distributions to linear models, the **degrees of freedom parameters can take only integer values. The underlying families of distributions allow fractional values for the degrees-of-freedom parameters**, which can arise in more sophisticated uses. One set of examples is problems where chi-squared approximations based on effective degrees of freedom are used. In other applications, such as modelling heavy-tailed data, a t or F-distribution may be used as an empirical model. In these cases, there is no particular degrees of freedom interpretation to the distribution parameters, even though the terminology may continue to be used.

Not sure if documentation should be updated showing `ddof `can take float as well or it was an unintentional behaviour.

**Comment by rawwar** [comment]
I just noticed that its same for np.std and np.var as well

**Comment by seberg** [comment]
Whether it was intentional or not, we should just update the documentation to `int or float`.  It seems that other software also allows float values and if there is a use-case for it, there seems no good reason to deprecate it again.  Technically, probably even more than floats are supported, but maybe it doesn't matter.

**Comment by rawwar** [comment]
Can this be a good first issue? If so, i can take it up and update the docs

**Comment by seberg** [comment]
Sure, sounds like a safe bet to me @rawwar, although I am not 100% sure that `int or float` is the correct spelling.  Please just open a PR and don't hesitate to ask here if you need help. We are not in a habit of assigning issues.

You can find help on how to build docs [here](https://numpy.org/devdocs/docs/howto_build_docs.html#howto-build-docs) and more general information [here](https://numpy.org/devdocs/dev/index.html).  Although, building the docs locally may not be quite necessary here.

**Comment by rawwar** [comment]
Well, it's a good thing I spent the last several days understanding sphinx to do a minor PR for numba docs
