### ISSUE TITLE
`np.meshgrid` tests do not exercise higher-dimensional grids

### ISSUE THREAD

**Issue by DCtheTall** [numpy/numpy#18655]
`np.meshgrid` is tested [here](https://github.com/numpy/numpy/blob/cb557b79fa0ce467c881830f8e8e042c484ccfaa/numpy/lib/tests/test_function_base.py#L2222).

As you can see, only the 1D and 2D grid usecases are covered by tests, but the documentation states the function should work for N-D grids as well. Perhaps there should also be a test that covers the 3D and 4D case? Perhaps with argument arrays whose length are just 2 or 3 to keep the size of the expected result small.

If this is something you'd want to include, I am happy to supply a PR adding the tests. Otherwise if you think just testing the 2D case is fine, feel free to close this.

**Comment by charris** [comment]
Improved testing is always welcome. Go for it.

**Comment by DCtheTall** [comment]
Thanks @charris, I will send a PR shortly. Also I realize the 3D case is tested (kind of) in the tests covering the different indexing options, but maybe something more thorough can be added 😄

**Comment by DCtheTall** [comment]
@charris I opened a PR with a few test cases I could think of

**Comment by mwtarnowski** [comment]
@DCtheTall, nice work!
@charris, having additional tests successfully merged, is it still an open issue?

**Comment by melissawm** [comment]
It looks like this is resolved - feel free to reopen if that is not the case.
