### ISSUE TITLE
numpy.cross producing wrong output

### ISSUE THREAD

**Issue by MLiew** [numpy/numpy#18653]
I am using numpy.cross() to calculate the cross product of two vectors. When the numbers in the vectors is small, the output is correct, however, when the values in the vector become pretty large(e.g. 7-digits), the output is wrong. 

### Reproducing code example:

```python
import numpy as np
In [1]: rijk = np.array([-2981784, 5207055, 3161595])
        vijk = np.array([-3384, -4887, 4843])
        A = np.cross(rijk, vijk, axis=0)
Out[1]:  [2013776466 -553024864 2127881456]

In [2]: rijk_2 = np.array([-298178.4, 520705.5, 316159.5]) #smaller by ten times
        vijk_2 = np.array([-3384, -4887, 4843])
        A_2 = np.cross(rijk_1, vijk_1, axis=0)
Out[2]: [4.06684821e+09 3.74194243e+08 3.21926525e+09]
```

The correct output for the first input should be [40668482130, 3741942432, 32192652528], but the returned output is far away from the desired output. 

### NumPy/Python version information:
Python version: 3.6.8
NumPy version: 1.18.1

**Comment by charris** [comment]
The problem in the first case is due to integer overflow, the second example works because the computation is done in floating point.

**Comment by MLiew** [comment]
> The problem in the first case is due to integer overflow, the second example works because the computation is done in floating point.

Oh I see, thank you for your reply. Maybe I should use an alternative way to calculate it. Thanks a lot.

**Comment by charris** [comment]
Cross products can be numerically tricky anyway, the best procedure depends on what problem you are trying to solve.
