### ISSUE TITLE
Missmatch between documentation and numpy.where output

### ISSUE THREAD

**Issue by Avatar36Cl211** [numpy/numpy#18668]
Hello,

I would like to highlight a small bug regarding numpy.where function. There is a mismatch between the documentation and the output of the function. It is specified that the output should be a ndarray while it actually returns a ndarray encapsulated into a tuple. A simple example to test it:

```python
import numpy as np
test = np.array([8,0,1,2,3,8,9,10,14,15,16])
print(type(np.where(test > 5)))
=> tuple
print(type(np.where(test > 5)[0]))
=> numpy.ndarray
```

Numpy version I'm using: 1.19.2

Have a good day

**Comment by eric-wieser** [comment]
From the top of [the documentation](https://numpy.org/doc/stable/reference/generated/numpy.where.html):

> When only condition is provided, this function is a shorthand for `np.asarray(condition).nonzero()`. Using `nonzero` directly should be preferred, as it behaves correctly for subclasses. **The rest of this documentation covers only the case where all three arguments are provided.**

(emphasis mine)

**Comment by Avatar36Cl211** [comment]
Ok understood, my bad, the documentation is clear on this point. It's a bit disturbing to have one case where it sends a tuple and another where it sends a numpy.array. This function could return a numpy.array all the time actually. It was not obvious for me, as a user, that it could send different types.

Anyway, I'll adapt my code to remove this tuple.

Thanks for the answer.
