### ISSUE TITLE
scalar does not inherit byteorder from the array it's "created" from (Trac #1268)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1866]
_Original ticket http://projects.scipy.org/numpy/ticket/1268 on 2009-10-20 by @mdboom, assigned to unknown._

```
In [9]: x = np.array([1], dtype='<i4')

In [10]: x[0].dtype.byteorder
Out[10]: '='

In [11]: x = np.array([1], dtype='>i4')

In [12]: x[0].dtype.byteorder
Out[12]: '='
```

This may in fact be correct behavior, but it can lead to confusing use of byteswap, since the following is not guaranteed:

```
x.byteswap().tostring() == x[0].byteswap().tostring()
```

and for that matter, neither is:

```
x.tostring() == x[0].tostring()
```

(This bug began as part of #1857, but is probably a different bug.)

**Comment by mattip** [comment]
Turning this into a documentation issue.

**Comment by melissawm** [comment]
Can anyone (@seberg?) either help me find the original ticket (now showing a 404) or figuring out what to document? Thanks!

**Comment by seberg** [comment]
@melissawm the original ticket only has the same information as shown here AFAIK (I think the track is lost in time, at least I do not know who might still have the data).

There is a warning here now: https://numpy.org/doc/stable/user/basics.byteswapping.html (a bit down the page).  Maybe that is just enough?  Scalars are always stored as native-byteorder, so indexing, etc. can "swap" if the result is a scalar.  OTOH, also ufuncs never "preserve" byte-order, so losing the byte-order information is not that uncommon anyway.

We could probably drop the "currently", I don't really see this changing any time soon (there is probably semi-public API that would even break, anyway).
