### ISSUE TITLE
Inconsistent regression results in np.polynomial.Polynomial

### ISSUE THREAD

**Issue by bdch1234** [numpy/numpy#18677]
I'm wondering why I see different regression results using np.polyfit and the new API np.polynomial?

### Reproducing code example:

```python
import numpy as np
xs = np.random.rand(10)
ys = np.random.rand(10)
coef = np.polyfit(xs, ys, 1).tolist()
print(coef)
```
shows
```python
[0.03358968477472722, 0.5249076650936326]
```
and then
```python
coef_new = np.polynomial.Polynomial.fit(xs, ys, 1).coef.tolist()
coef_new.reverse()
print(coef_new)
```
shows
```python
[0.016158564003230878, 0.541771043043678]
```

### NumPy/Python version information:

1.20.1 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]

**Comment by charris** [comment]
Polynomial fitting scales and shifts the data domain to the interval [-1, 1] and fits it there for numerical stability. The evaluation function knows about this and will yield the same results as a plain old polynomial. You can transform the fitted polynomial `p` to an ordinary polynomial by
```
p.convert()
```
but it isn't recommended. The `convert` method can also convert to series in other basis, Legendre, Chebyshev, etc.

**Comment by bdch1234** [comment]
Got it, thanks for explaining @charris.
