### ISSUE TITLE
data.shape -> (2, 2) becomes (3, 2) without explanation in running example

### ISSUE THREAD

**Issue by depling** [numpy/numpy#18678]
## Documentation

[(https://numpy.org/doc/stable/user/absolute_beginners.html#creating-matrices)]

This example begins with `data = np.array([[1,2],[3,4]])` and continues as a running example.  At the diagram point it becomes `data = np.array([[1,2],[3,4],[5,6]])` without explanation.  Especially with the diagrams this can be confusing.  The diagrams are exactly what is called for in this context, it seems a shame there is this disfluency.

**Comment by cooperrc** [comment]
@melissawm and @mattip 

It looks like this issue was taken care of with #18689 

Can we close?

**Comment by depling** [comment]
Yes, please, this issue has been resolved.
