### ISSUE TITLE
The speed between numpy.zeros, numpy.ones and numpy.empty is not fit

### ISSUE THREAD

**Issue by IchiruTake** [numpy/numpy#18687]
I have made a small test to validate the speed of np.ones, np.zeros, and np.empty in both numpy version 1.19.5 and numpy 1.20.2 and found out that despite any datatype, np.ones always perform slower compared to two other while np.empty and np.zeros always result in the same time. Although the executing time is still small enough, this violate the meaning of time complexity, especially between np.zeros and np.ones (empty: O(1); zeros=ones: O(N))

CODE: 
```
import numpy as np
from time import time
print(np.__version__)

dtypes = [np.uint8, np.uint16, np.uint32, np.uint64, np.int8, np.int16, np.int32, np.int64,
          np.float16, np.float32, np.float64]
empty_speed, zeros_speed, ones_speed = [], [], []
test = 50
for index, dtype in enumerate(dtypes):
    print(dtype)
    start = time()
    for i in range(0, test):
        x = np.zeros(shape=(60000, 1000), dtype=dtype)
    zeros_speed.append(np.float32(time() - start))

    start = time()
    for i in range(0, test):
        x = np.empty(shape=(60000, 1000), dtype=dtype)
    empty_speed.append(np.float32(time() - start))

    start = time()
    for i in range(0, test):
        x = np.ones(shape=(60000, 1000), dtype=dtype)
    ones_speed.append(np.float32(time() - start))

print("np.empty:", empty_speed)
print("np.zeros:", zeros_speed)
print("np.ones:", ones_speed)

```
 
RESULT:
```
np.empty: [0.0009975433, 0.0, 0.0009980202, 0.0019536018, 0.0009965897, 0.0009994507, 0.0009977818, 0.0009968281, 0.0009951591, 0.0009999275, 0.00095772743]
np.zeros: [0.0009968281, 0.005982876, 0.015957355, 0.018989086, 0.048858166, 0.006981373, 0.012964249, 0.024933815, 0.042887688, 0.01196599, 0.02194047]
np.ones: [0.70412874, 1.9734793, 3.471972, 6.609166, 0.8929522, 1.7109797, 3.322414, 6.2496147, 1.4753692, 2.8984761, 5.8197064]
```

**Comment by eric-wieser** [comment]
Note that empty, zeros, and ones are respectively `malloc`, `calloc`, and `malloc; memset`. What you're seeing here is clever handling of `calloc` by the operating system.

**Comment by seberg** [comment]
Indeed, this is just clever optimization by the OS, the time at which the data is actually written "page fault" occurs on the operating system level, is simply delayed for `empty` and `zeros`.  Closing the issue, we could add it to the notes of `zeros` and `empty` in the docs, though (if it isn't mentioned already).
