### ISSUE TITLE
np.power() issues

### ISSUE THREAD

**Issue by 1112114641** [numpy/numpy#18702]
### Reproducing code example:

```python
>>>import numpy as np
>>>x= 0.1
>>>np.power(0.009959573046635367*x,-1.131842132181093) - 0.009959573046635367*x**-1.131842132181093
2497.4348091587904
>>> np.power(0.009959573046635367*x,1.131842132181093) - 0.009959573046635367*x**1.131842132181093
-0.00033479908215012426
>>>x= 1.5
>>>np.power(x,-1.5) - x**-1.5
0.0
>>>np.power(0.000123*x,-1.5) - 0.000123*x**-1.5
399029.90444920457
>>>np.power(0.000123*x,-1) - 0.000123*x**-1
5420.054118542005
```

### Error message:
There is no error message per se, but within the range of x ∈ [0.01,150] for small float base numbers, and negative (int/float) exponents there is a large difference between the np.power() result, and what the result should be like. Could someone please verify and reproduce this?

If this can be reproduced by others, then I assume it is a bug worth fixing.

### NumPy/Python version information:
On my own machine:
```python
>>> import sys
>>> sys.version
'3.8.8 (default, Feb 27 2021, 02:19:17) \n[Clang 12.0.0 (clang-1200.0.32.29)]'
>>>import numpy as np
>>>np.__version__
'1.20.1'
```

I have also verified on my second computer, and also on colab:

```python
>>>import sys
>>>sys.version
'3.7.10 (default, Feb 20 2021, 21:17:23) \n[GCC 7.5.0]'
>>>import numpy as np
>>>np.__version__
'1.19.5'
```

```python
>>> import sys
>>> sys.version
'3.7.6 (default, Sep 29 2020, 14:34:00) \n[Clang 12.0.0 (clang-1200.0.32.2)]'
>>>import numpy as np
>>>np.__version__
'1.19.5'
```

**Comment by charris** [comment]
`0.000123*x**-1.5` needs to be written `(0.000123*x)**-1.5`
