### ISSUE TITLE
np.fromstring not check first arg

### ISSUE THREAD

**Issue by guicunbin** [numpy/numpy#18703]
## np.fromstring not check first arg

In [34]: fs = np.zeros(shape=[256,])

In [35]: type(fs)
Out[35]: numpy.ndarray

In [36]: fs.shape
Out[36]: (256,)

In [37]: fs      = np.fromstring(fs, dtype=np.float32).reshape([-1, 256])
/usr/local/bin/ipython3:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  #!/usr/local/bin/python3.7

In [38]: fs.shape
Out[38]: (2, 256)

**Comment by guicunbin** [comment]
In [26]: fs = np.zeros(shape=[256,])

In [27]: type(fs)
Out[27]: numpy.ndarray

In [28]: fs.shape
Out[28]: (256,)

In [29]: fs      = np.frombuffer(fs, dtype=np.float32).reshape([-1, 256])

In [30]: fs.shape
Out[30]: (2, 256)


np.frombuffer also not check the first arg

**Comment by charris** [comment]
`fs` is `float64`, interpreting it as `float32` makes the array twice as large.

**Comment by seberg** [comment]
This behaviour is correct as described  (if maybe confusing when using these in a situation where they don't really apply). If you use fromstring/frombuffer, you are asking NumPy to interpret the _raw bytes_ in whatever you pass.  Use `np.array` (or `array.astype()` when you know it is a NumPy array) if you want "casting" behaviour.
