### ISSUE TITLE
DOC: Inaccurate output type of `ptp`

### ISSUE THREAD

**Issue by aws-stdun** [numpy/numpy#18719]
## Documentation
The [documentation](https://numpy.org/doc/stable/reference/generated/numpy.ptp.html) states that the output of `ptp` is:

> A new array holding the result, unless out was specified, in which case a reference to out is returned.

However:

```
>>> a = np.arange(10)
>>> type(np.ptp(a))
<class 'numpy.int64'>
```

**Comment by charris** [comment]
You are checking the wrong thing.
```
In [1]: a = np.arange(10)                                                       

In [2]: b = np.ptp(a)                                                           

In [3]: a is b                                                                  
Out[3]: False
```

**Comment by aws-stdun** [comment]
Hi, I believe am checking the correct thing: the return type of `ptp`. 

![Screen Shot 2021-04-02 at 2 22 18 PM](https://user-images.githubusercontent.com/73200162/113455204-e6316c00-93be-11eb-9d19-49ea35d39452.png)

It's easy to see if you pass larger ndarrays to `ptp`, it returns `ndarray` instead of a primitive, so this is an undocumented edge case.

**Comment by charris** [comment]
Ah, NumPy usually returns a scalar when the result would be zero dimensional

**Comment by aws-stdun** [comment]
@charris I was thinking a simple fix would be something like you have for other similar functions.
For example, to quote from [nanmax](https://numpy.org/doc/stable/reference/generated/numpy.nanmax.html):

> An array with the same shape as a, with the specified axis removed. If a is a 0-d array, or if axis is None, an ndarray scalar is returned. The same dtype as a is returned.

**Comment by melissawm** [comment]
@aws-stdun would you consider submitting a PR to fix that?

**Comment by WarrenWeckesser** [comment]
FYI: There are several other functions with similar behavior that also state the return values as just `ndarray`, e.g. [`mean`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [`median`](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [`std`](https://numpy.org/doc/stable/reference/generated/numpy.std.html), [`var`](https://numpy.org/doc/stable/reference/generated/numpy.std.html), [`argmin`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html), [`argmax`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html).

Some examples that already document the return value as `ndarray or scalar` and explain when a scalar is returned are [`amin`](https://numpy.org/doc/stable/reference/generated/numpy.amin.html), [`amax`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html) and `nanmax` as @aws-stdun  pointed out above.

**Comment by aws-stdun** [comment]
> @aws-stdun would you consider submitting a PR to fix that?

Sure.

**Comment by Micky774** [comment]
@aws-stdun Would you still be interested in submitting a PR for this issue, or could I pick it up?
