### ISSUE TITLE
Vague and confusing wording in percentile() documentation

### ISSUE THREAD

**Issue by ddejohn** [numpy/numpy#18716]
There is a very confusing explanation of the "linear" interpolation option in the `percentile()` function documentation:

> ‘linear’: `i + (j - i) * fraction`, where `fraction` is the fractional part of the index surrounded by `i` and `j`.

Specifically, I think this needs to be reworded: "the fractional part of the index surrounded by `i` and `j`." As I think this is entirely too vague.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

**Comment by tech-gian** [comment]
Can I take this? The only thing that needs to be done is to change this phrase?

PS: Do you know in which folder or location could I find the .rst file?

**Comment by melissawm** [comment]
Hi @tech-gian - you are free to submit a PR to fix this. In this case, you will have to edit the docstring of this function, so it is not an rst file, but a Python file. This text occurs both in the `percentile` and the `quantile` functions in `numpy/lib/function_base.py` and again in `nanpercentile` and `nanquantile` in `numpy/lib/nanfunctions.py` - it would be nice if you could check the text in all those locations.

**Comment by eric-wieser** [comment]
@ddejohn, can you suggest a clearer rewording?

**Comment by ddejohn** [comment]
Closing this for now, since this is something I can take care of in a PR on my own, when I find the time. Right now I'm struggling to come up with a rewording that is succinct enough to be appropriate for a docstring.

**Comment by tech-gian** [comment]
If there is anything I can do in a PR, mention my name on the PR or in a future issue.
