### ISSUE TITLE
SunOs/Solaris

### ISSUE THREAD

**Issue by xabi12** [numpy/numpy#18714]
Hi, is there any chance of a .whl package under SunOS/Solaris (Oracle Solaris 11.4 SPARC/ SunOS 5.11)?
I need to install the package on a machine without internet access, unfortunately none of the available ones work
ERROR: numpy-1.20.2-cp39-cp39 ... .whl is not a supported wheel on this platform.

**Comment by mattip** [comment]
In order to build and ship a wheel, we would need to run CI on that system. Is there a CI provider that offers that OS and machine?

**Comment by charris** [comment]
You can build basic wheels with `python setup.py bdist_wheel`, but they may not be optimized.

**Comment by xabi12** [comment]
not working

:~/numpy-1.20.2$ python setup.py bdist_wheel                                                            
Running from numpy source directory.
Cythonizing sources
numpy/random/_bounded_integers.pxd.in has not changed
Processing numpy/random/_common.pyx
Processing numpy/random/_mt19937.pyx
Processing numpy/random/_sfc64.pyx
Processing numpy/random/_bounded_integers.pyx.in
Processing numpy/random/bit_generator.pyx
Processing numpy/random/_philox.pyx
Processing numpy/random/_pcg64.pyx
Processing numpy/random/_generator.pyx
Processing numpy/random/mtrand.pyx
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
(python_venv)

**Comment by mattip** [comment]
python -m pip install wheel

**Comment by xabi12** [comment]
Without internet on the machine I can hardly see it :(
only the package saves me.
Thanks for your help

**Comment by xabi12** [comment]
I compiled it manually :) Thanks for your help
