### ISSUE TITLE
linalg.det and linalg.slogdet rounding error

### ISSUE THREAD

**Issue by tatatupi** [numpy/numpy#18717]
I am not sure to what extent this bug is happening, but for a simple 3x3 matrix, which determinant should be 0 and thus its sign should be 0 and its logdet -inf, the results are wrong.

### Reproducing code example:

```python
import numpy as np
arr = np.linspace(1, 9, 9)
arr = arr.reshape(3, 3)
np.linalg.det(arr) # outputs -9.51619735392994e-16 / should be 0
np.linalg.slogdet(arr) # outputs (-1.0, -34.58836615651031) / should be 0 and -inf
```

**Comment by ZurMaD** [comment]
I tried without errors:

![image](https://user-images.githubusercontent.com/28235457/113482840-0e27da80-9466-11eb-82e6-21713ac219c5.png)

More details about your numpy library:
- OS: Windows/Linux/MacOS ?
- Python version: 2.X,3.X ?
- Numpy version: ?

The version of numpy that I'm using is numpy==1.19.1
you can upgrade with `pip3 install numpy --upgrade`

**Comment by tatatupi** [comment]
I was using 1.20.1. 
Just upgraded to 1.20.2 and it seems to have fixed the problem.

I was using Windows and Python 3.9.2.

Thanks though!

**Comment by tatatupi** [comment]
1.20.2 fixed the issue.
