### ISSUE TITLE
ImportError: Unable to import required dependencies: numpy

### ISSUE THREAD

**Issue by Catadanna** [numpy/numpy#18748]
I have Python 3.7.3 installed on my computer. I upgraded to 3.9, using `sudo apt install python 3.9`. Then I tried to use it in the following code, which is in the file `test.py`. If I run in command line `$ python test.py`, Python 3.7 is used (the version is printed). So I run with `./test.py`, in order to use Python3.9. I get this error.

### I USE : 
Ubuntu version 20.04
Numpy version: 1.20.2
Pandas version : 1.2.3

I first installed numpy and pandas using the commands : 

sudo apt-get install python-numpy
sudo apt-get install python-pandas

## Uninstall reinstall numpy and pandas, in different ways:

TRY 1:
pip uninstall pandas
pip uninstall numpy
pip install numpy
pip install pandas

TRY 2:
pip3 uninstall pandas
pip3 uninstall numpy
pip3 install numpy
pip3 install pandas

TRY 3:
sudo apt-get remove pandas
sudo apt-get remove numpy
sudo apt-get autoremove

OR

sudo apt-get remove python-pandas
sudo apt-get remove python-numpy
sudo apt-get autoremove

THEN 

sudo apt-get install python-numpy
sudo apt-get install python-pandas

## Upgrade numpy and pandas

pip install numpy --upgrade
pip install pandas --upgrade

### Reproducing code example:
```python
#!/usr/bin/env python3.9

import numpy as np
import pandas as pd
import sys

print("Python version", sys.version)

df = pd.read_csv("file.csv")
print(df.shape)
```

### Error message:
ImportError: Unable to import required dependencies: numpy

More precisely :

/home/ubuntu/mypath/./test.py", line 3, in <module>
    import pandas as pd
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.9 from "/usr/bin/python3.9",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

### NumPy/Python version information:

1.20.2 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

1.2.3 3.7.3 (default, Mar 27 2019, 22:11:17)

**Comment by rossbar** [comment]
The main issue here is that there are multiple python versions and a mix of package management systems - i.e. using both `apt` and `pip`. Given all of the procedures you listed above it's difficult to disentangle what specifically is happening at any given stage on your system; note that it's generally best practice *not* to install packages directly to the system python and instead use Python virtual environments (or related environment management tools such as those provided by `conda`). For example, assuming you want to use the `python3.9` instance you've installed via apt:

```bash
$ python3.9 -m venv test_env  # You can replace "test_env" with a name of your choosing
$ source test_env/bin/activate
$ python3.9 -m pip install numpy
```

If for whatever reason you can't use a virtual environment, then you will have to investigate further how/where `pip` and `apt` have installed things (note `pip3` is ambiguous if you have multiple python 3 versions installed) and configure your system to behave the way you expect.

**Comment by Catadanna** [comment]
I removed the libraries I installed with `pip` and `pip3` and reinstalled using `sudo apt-get`, as I did at the beginning. Now as I have Python 3.7.3 as the default Python version, I created a virtual environment `py39` only for the use of Python 3.9. I shall do like that for every new version.
