### ISSUE TITLE
Codecov is failing regularly for PRs.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#18747]
The same unrelated code seems to turn up in the failures irrespective of the PR, which is strange.

**Comment by seberg** [comment]
Do you mean the same one as gh-18529? I think we may have to pin to gcc-8 (if possible) to avoid the bug, which is hopefully fix in the next gcc releases.

**Comment by charris** [comment]
No, the problem is in loop dispatch code, may be due to a recent merge. See https://github.com/numpy/numpy/pull/18737/checks?check_run_id=2288600808. Hmm, I wonder if a PR rebase would fix it.

**Comment by rgommers** [comment]
+1 for removing codecov. A couple of years of experience has shown its approach is fundamentally unreliable, and the added value is very limited.

**Comment by seberg** [comment]
Codecov is useful for making sure that new C-code is covered as well as you think it is.  Our tests are not structured well enough to always know just from a brief look at the tests.  I regularly add a few extra tests based on it.

Happy if you ignore it or set it to "not fail" if possible, but the "annotation" comments are successful IMO and worth a bit of churn.

**Comment by mattip** [comment]
Sounds like setting it to "not fail" would be the best course. Would it still mark the code as it does currently or would reviewers need to take further steps to see possible regressions?
