### ISSUE TITLE
Getting Numpy installation error, when I try to deploy my streamlit application on heroku.

### ISSUE THREAD

**Issue by Vinayaks117** [numpy/numpy#18742]
### Reproducing code example:

Here is my requirements.txt file

numpy==1.19.5
matplotlib==3.1.3
seaborn==0.10.0
plotly==4.14.3
pandas==1.0.1
streamlit==0.79.0
scikit-learn==0.22.2
catboost==0.25
lightgbm==3.2.0
xgboost==1.3.3
flask==1.1.1
keras-preprocessing==1.1.2
tensorflow==2.4.1
nltk==3.4.5

### Error message:

 ERROR: Command errored out with exit status 1: /app/.heroku/python/bin/python -u -c 'import sys, setuptools, tokenize; 
 sys.argv[0] = '"'"'/tmp/pip-install-jbzzotxk/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jbzzotxk/numpy/setup.py'"'"';
 f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();
 exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1wdx687a/install-record.txt 
 --single-version-externally-managed --prefix /tmp/pip-build-env-12xt2oon/overlay --compile --install-headers 
 /tmp/pip-build-env-12xt2oon/overlay/include/python3.9/numpy Check the logs for full command output.

Attached complete error message text file, please have a look.
[heroku error.txt](https://github.com/numpy/numpy/files/6275663/heroku.error.txt)

**Comment by melissawm** [comment]
It looks like this is a heroku problem, not a NumPy problem.

**Comment by batmanscode** [comment]
@Vinayaks117 I am having a similar issue. Have you managed to fix this?

Found this while searching:
https://stackoverflow.com/questions/71976666/heroku-pip-install-suddenly-started-to-return-an-error-use-2to3-is-invalid
