### ISSUE TITLE
iscomplex wrong with zero value

### ISSUE THREAD

**Issue by edyounis** [numpy/numpy#18754]
The `np.iscomplex` function is incorrect when passed a zero-valued complex object.

### Reproducing code example:

```python
>>> import numpy as np
>>> x = complex(0.0j)
>>> x
0j
>>> np.iscomplex(x)
False
>>> isinstance(x, complex)
True
>>> x = np.complex64(0)
>>> x
0j
>>> np.iscomplex(x)
False
```

### Error message:

N/A

### NumPy/Python version information:

```
Python 3.9.2
1.20.1 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0]
```

**Comment by eric-wieser** [comment]
This behavior is documented:

> What is tested is whether the input has a non-zero imaginary part, not if the input type is complex.

Sure, this is perhaps an odd choice of behavior, but we can't change that choice now. `np.iscomplexobj` behaves as you expect.
