### ISSUE TITLE
Numpy arange returns right-border-inclusive array

### ISSUE THREAD

**Issue by Heronalps** [numpy/numpy#18776]
### Reproducing code example:

```python
>>> np.arange(0.8, 1.1, 0.1)
array([0.8, 0.9, 1. , 1.1]) ???
>>> np.arange(0.8, 1.2, 0.1)
array([0.8, 0.9, 1. , 1.1])
>>> np.arange(0.8, 1., 0.1)
array([0.8, 0.9])
```
This issue had been reported in this [closed thread](https://github.com/numpy/numpy/issues/11913).

### NumPy/Python version information:

Python 3.6.8
Numpy 1.19.5

**Comment by huppyflup** [comment]
The 'closed thread' states that this behavior is documented: https://github.com/numpy/numpy/issues/11913#issuecomment-419740405

**Comment by Heronalps** [comment]
> The 'closed thread' states that this behavior is documented: [#11913 (comment)](https://github.com/numpy/numpy/issues/11913#issuecomment-419740405)

Thank you!
