### ISSUE TITLE
numpy.clip documentation could be misleading for a_max < a_min

### ISSUE THREAD

**Issue by xamm** [numpy/numpy#18782]
## Documentation

In the documentation for [clip()](https://numpy.org/doc/stable/reference/generated/numpy.clip.html) the return type is defined as:
> An array with the elements of a, but where values < a_min are replaced with a_min, and those > a_max with a_max.

When a_min is greater than a_max the return values are only defined by a_max:

```
import numpy as np
arr = np.array([1, -0.25, -1])
arr.clip(0, -0.5)
# returns array([-0.5, -0.5, -0.5])
```

If a_min is greater than a_max, the description of the return values in the documentation could be misleading, since all values are replaced by a_max.

It might be good to explain this special behavior in the documentation for the case a_max < a_min.

If a change in documentation is desired, I am happy to contribute.

**Comment by cooperrc** [comment]
It looks like `numpy.clip` checks for `a_min` and then `amax`. Since there is no warning or error, I think it makes sense to add an example where `a_min` > `a_max`. 

I would suggest adding a `Notes` section in the docstring and flip the min/max in the first example e.g. 

```
Notes
--------
When `a_min` is more than `a_max`, `clip` will return an 
array where all values are `a_max`, as seen in the second example. 

Examples
--------
>>> a = np.arange(10)
>>> np.clip(a, 1, 8)
array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])
>>> np.clip(a, a_max = 1, a_min = 8)
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

```

**Comment by cooperrc** [comment]
@xamm, awesome work on the docs addition. Can we close this issue now?

**Comment by xamm** [comment]
From my side this issue can be closed. I just was not sure if I should do this by myself.

**Comment by cooperrc** [comment]
> From my side this issue can be closed. I just was not sure if I should do this by myself.

Thanks again @xamm! We really appreciate your detailed thoughts on this issue. 

@melissawm, I think we are ready to close this issue.

**Comment by seberg** [comment]
@cooperrc if you can't close issues, we have to change that! :)
