### ISSUE TITLE
bug when using numpy.pi numpy.sin

### ISSUE THREAD

**Issue by JohnGarciaFarinha** [numpy/numpy#18783]
I was doing some confirmation for a project and realized this return values of i in the E-12 range which was not expected when using np.pi directly then i try initiating a variable before same bug even converted to float ( even tho i suspect that's the intended output of np.pi but that didn't work also
then i tried with the old 3.14 instead of using np.pi and then the array was well defined now returning the expected graph
or maybe the np.sin() (using pi with more decimals also explodes)
Theres also a chance i m not using it properly
I m using python 3.9.2
```
import numpy as np
import matplotlib.pyplot as plt
t =np.array([i*0.01 for i in range (0,1000)])
pi=float(np.pi)
i=-0.104*np.sin(pi *2*(10**3)*t)
fig, ax = plt.subplots()
ax.plot(t, i)
plt.show()
```

**Comment by eric-wieser** [comment]
What behavior do you expect here? Your graph plots `sin x` at `x = 0pi, 20pi, 40pi, ...` - of course you get a result around zero!

**Comment by seberg** [comment]
Aliasing can be confusing, but all of this is expected as Eric pointed out: https://en.wikipedia.org/wiki/Aliasing

**Comment by JohnGarciaFarinha** [comment]
> 
> 
> What behavior do you expect here? Your graph plots `sin x` at `x = 0pi, 20pi, 40pi, ...` - of course you get a result around zero!

My graph should plot -0.104 * what ever the frequency it has  it should fluctuate between [-0.104,0.104] thats it
When i caculate with np.pi unless i m getting this completely wrong the array should return values between that but in reality i m getting E-12
Another thing i dont get is with 3.14 it works with 3.14159 it doesn't. Problems with np.sin aliasing?
