### ISSUE TITLE
np.testing.assert_array_equal IndexErrors when mixing dtypes and matrices/ndarrays

### ISSUE THREAD

**Issue by mhauru** [numpy/numpy#18817]
In:
```
import sys
import numpy as np

print(np.__version__, sys.version)

A = np.random.randn(2, 2)
B = np.matrix(A.astype(np.float32))
np.testing.assert_array_equal(B, A)
```
Out:
```
1.20.2 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Traceback (most recent call last):
  File "/tmp/bug.py", line 9, in <module>
    np.testing.assert_array_equal(B, A)
  File "/home/mhauru/.local/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 932, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/mhauru/.local/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 830, in assert_array_compare
    max_rel_error = max(error[nonzero] / abs(y[nonzero]))
  File "/home/mhauru/.local/lib/python3.9/site-packages/numpy/matrixlib/defmatrix.py", line 193, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 4
```
The point here is that the first argument to `assert_array_equal` is a float32 `np.matrix`, while the second one is a float64 `np.ndarray`.

**Comment by charris** [comment]
Yes, matrices behave oddly.  It looks like what is happening is that flattened arrays are used, but matrices can't be flattened. Matrices are not a well behaved subclass of ndarray and we encourage folks to stop using them so we can deprecate them :) I'm not convinced this should be considered a bug.

**Comment by seberg** [comment]
I agree, adding more work-arounds for matrices in the core code-base when matrix is all but deprecated doesn't seem worthwhile.  It is easy enough to work around it by using `B.A` in the test.

**Comment by mhauru** [comment]
Well, it's very easy to work around if you know what the cause is, but `IndexError` doesn't exactly point you in the right direction. In my use case, I was calling `.todense()` on some SciPy sparse matrices, not even realising that that was returning `np.matrix` objects, and it took me a while to understand what was going on.

**Comment by seberg** [comment]
I guess adding an `arr.ndim == 1` check to raise an error that includes "bad array subclass modifying shape" is something we would merge if you feel its helpful.

**Comment by mhauru** [comment]
Depends on how imminent the deprecation of np.matrix is I guess. Alternatively, and perhaps better, `.todense()` for SciPy sparse matrices returning ndarrays would have also avoided this for me.

Essentially, what I'm saying is that if np.matrix is so nearly deprecated that this isn't worth fixing, then it sounds like `.todense()` really shouldn't be returning np.matrices.

Not sure if this is the right place to raise that, I don't know how tightly interwoven the Numpy and SciPy projects and teams are.

**Comment by seberg** [comment]
@mhauru what I am saying is that `np.matrix` should be avoided as a direct reference (i.e. the code should not include `np.matrix`).  Doing that would stand in the way of a deprecation that will hopefully happen at some point.  The main reason matrix is in a half deprecated state right now is that `scipy.sparse` builds on it.

You can create an warning about matrix by detecting the bad reshape behaviour of matrix instead of "matrix" itself.  I am happy to merge a PR for that, I just think there may be many similar places, so I don't feel like making it a priority myself.

**Comment by mhauru** [comment]
I understand. The right long term solution it seems would be to purge `scipy.sparse` of `np.matrix`. Based though on what you said above it sounds like the folks caring for `scipy.sparse` are probably aware of the need for that.
