### ISSUE TITLE
np.unravel_index yields mostly incorrect coordinate arrays

### ISSUE THREAD

**Issue by cmatt23** [numpy/numpy#18829]
The coordinate arrays that the unravel_index function yields are sometimes wrong. In my use case, I am looking for the minimum value of a multi-dimensional array along one of its axes. Re-applying the tuple of coordinate arrays to the multi-dimensional array should yield the minimum values but does not (please see example below). I have written a python function that works around this short-coming, which I would like to contribute to the project as a temporary fix (for potential future changes to the C code).

### Reproducing code example:

The example code below yields `False`.

```python
import numpy as np
axis = -1
data = np.random.random(12).reshape(3,2,2)
correct_values = np.min(data, axis=axis)
flat_indices = np.argmin(data, axis=axis)
coord_arrays = np.unravel_index(flat_indices, data.shape)
print(np.array_equal(data[coord_arrays], correct_values))
```

### Error message:
There is no error message; the function runs as intended but the output values that are provided are mostly incorrect. 

### NumPy/Python version information:
1.20.2 3.9.4 (v3.9.4:1f2e3088f3, Apr  4 2021, 12:32:44) 
[Clang 6.0 (clang-600.0.57)]

**Comment by seberg** [comment]
[The documentation](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) includes an example using `take_along_axis` to do this the right way.

**Comment by cmatt23** [comment]
Thank you @seberg. Unfortunately, that still doesn't fix the problem insofar as `unravel_index` doesn't provide the correct tuple of coordinate arrays (what I was actually looking for) for the min/max indices of an array along an axis.

**Comment by rkern** [comment]
The result of `np.argmin(data, axis=axis)` are indices along the given `axis`. They are not indices into the flattened version of `data` (i.e. `data.flat`). `unravel_indices()` is for the latter, not the former.
