### ISSUE TITLE
Switch from imgmath to mathjax

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#18828]
For html doc builds we currently need to have LaTeX installed, which in general is a pain. In the Gitpod setup this also bloats the Docker image. `sphinx.ext.imgmath` needs LaTeX, `sphinx.ext.mathjax` does not.

Older discussion in gh-11753. And from https://github.com/numpy/numpy/pull/18822#issuecomment-824331826:

>> It was needed for `sphinx.ext.imgmath` to work without warnings. From my understanding, the `:math:` directives would not display anything without latex + dvisvgm.
>> 
>> (scipy uses `sphinx.ext.mathjax` so it does not run into this issue)

> Ah thanks, that makes perfect sense now. The SciPy setup works fine, and I think is actually preferable given that we can avoid LaTeX:

- discussion on moving from `mathjax` to `imgmath`: https://github.com/scipy/scipy/pull/7358
- PR to bundle `mathjax` instead: https://github.com/scipy/scipy/pull/7376
- Pandas and scikit-learn use `mathjax` as well, but have limitations for viewing rendered math offline.

I think the SciPy approach is preferred here.

_Proposal: let's switch to `mathjax` and use https://github.com/scipy/scipy-mathjax as a submodule._

**Comment by rgommers** [comment]
MathJAX is also alive and well, and is a NumFOCUS sponsored project. Which is useful; for SciPy it hasn't given any issues in the past four years, but if it does we know that the project is maintained.

**Comment by melissawm** [comment]
I can take a look at this in the next few days - I think this is the right way to go.

**Comment by rgommers** [comment]
Thanks Melissa!

**Comment by rgommers** [comment]
I think it looks equal or better for everything I checked. Reducing the `:nowrap:` doesn't seem needed.  E.g., compare:
- https://numpy.org/devdocs/reference/internals.code-explanations.html?highlight=code%20explanations#reduce, with
- https://19944-908607-gh.circle-artifacts.com/0/doc/build/html/reference/internals.code-explanations.html?highlight=internal%20code%20explanations#reduce

In `main`:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/98330/119199137-d7943680-ba8a-11eb-986d-3d0de9a7b101.png">



After this PR:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/98330/119199105-c9deb100-ba8a-11eb-8c70-c634579a76a3.png">

**Comment by rgommers** [comment]
Meant to post the above on the PR. Ah well.
