### ISSUE TITLE
ENH: Replace the placeholder `Any`-based annotations with explicit function definition

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#18838]
A relativelly simple improvements to the current `Any`-based placeholder annotations would be to replace them with simple unannated function definitions. For the main numpy namespace such enhancements were recently implemented (see below); ideally this can be done as well for all other namespaces before the 1.21 release.

TODO
------
- [x] `np` main namespace: https://github.com/numpy/numpy/pull/18765, https://github.com/numpy/numpy/pull/18780 and https://github.com/numpy/numpy/pull/18799
- [x] ~`np.core` namespace~: private namespace; deliberately kept empty
- [x] `np.char` namespace: https://github.com/numpy/numpy/pull/18842
- [x] `np.ctypeslib` namespace: https://github.com/numpy/numpy/pull/18842
- [x] `np.emath` namespace: https://github.com/numpy/numpy/pull/18842
- [x] `np.f2py` namespace: https://github.com/numpy/numpy/pull/18842
- [x] `np.fft` namespace: https://github.com/numpy/numpy/pull/18842
- [x] `np.lib` namespace: https://github.com/numpy/numpy/pull/18853
- [x] `np.linalg` namespace: https://github.com/numpy/numpy/pull/18853
- [x] `np.ma` namespace: https://github.com/numpy/numpy/pull/18909
- [x] `np.matrixlib` namespace: https://github.com/numpy/numpy/pull/18842
- [x] `np.polynomial` namespace: https://github.com/numpy/numpy/pull/18909
- [X] `np.random` namespace: fully annotated prior to this issue
- [x] `np.rec` namespace: https://github.com/numpy/numpy/pull/18842
- [x] `np.testing` namespace: https://github.com/numpy/numpy/pull/18842 and https://github.com/numpy/numpy/pull/18919
- [X] `np.typing` namespace: fully annotated prior to this issue

**Comment by charris** [comment]
@BvB93 Shall we leave this targeted for 1.21.0?

**Comment by BvB93** [comment]
@charris I'd love to get this wrapped up before 1.21.0. 
As I expect to submit part 3/3 later this week I feel this should be very doable, would you agree?
