### ISSUE TITLE
Define a p-Value in numpy.random.Generator.chisquare

### ISSUE THREAD

**Issue by maxkraft7** [numpy/numpy#18847]
## Feature

When defining random distributions with `numpy.random.Generator.chisquare` it would be helpful to create a certain kind of random distribution and not just work with pure randomness. For some mockup-data for example you need values that have a "realistic" p-Value. Also if that is already a thing and I have just overlooked it, please let me know.

**Comment by rkern** [comment]
We have [full-featured probability distribution objects in `scipy.stats`](https://docs.scipy.org/doc/scipy/reference/stats.html). They are out of scope for `numpy` itself.
