### ISSUE TITLE
How to become a core developper?

### ISSUE THREAD

**Issue by AKJ7** [numpy/numpy#18850]
Hello,

i am great fanatic of this library and would like to become part of the core development team.
I am currently reading "Guide to Numpy" by Travis E. Oliphant, the source code and mastering its Python interface. Moreover i do have have a formal education in Mathematics/Numeric.

My question remains: What should i do to become part of the core development team? Would solving the issues for example be a way to start me off on this path?

Thanks.

**Comment by melissawm** [comment]
Hello, @AKJ7 !

Yes - answering issues and creating pull requests is one way, but there are others. You can check out our [Contribute to NumPy page](https://numpy.org/contribute/), or join our Documentation or Community calls. I will close this issue but feel free to follow up on our mailing list or other community forums. Cheers!
