### ISSUE TITLE
override in operator

### ISSUE THREAD

**Issue by xpmemeda** [numpy/numpy#18866]
I cannot run the following code.
```
n0 = np.ones([2,2])
n1 = np.ones([2, 2])
n2 = np.ones([3, 3])
r = n0 in [n1, n2]
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I want to know if this is a bug or a known allowed error。Actually, I expect to get a False.

**Comment by charris** [comment]
It is intended behavior. Arrays compare element by element and the result is an array of bool which may be a mixture of True and False.
