### ISSUE TITLE
Unusual behavior when creating an array of objects from the list of numpy arrays

### ISSUE THREAD

**Issue by R-Mussabayev** [numpy/numpy#18867]
I want to create a numpy array of objects, where objects are the other numpy arrays have different or exact dimensions. The purpose is to have advanced indexing while working with an array of arrays where nested arrays might have different sizes.

If all the nested arrays have the different dimensions then all is OK:

```
import numpy as np
import random

a = np.array([np.array([0, 1], dtype=int), np.array([0, 1, 2], dtype=int)], dtype=object)
print(a[0].dtype, a[1].dtype)
```

In that case, dtype of all the nested arrays is equal to 'int64'.

But when the nested arrays have the same dimensions then nested arrays becomes also the arrays of objects:

```
a = np.array([np.array([0, 1, 2], dtype=int), np.array([3, 4, 5], dtype=int)], dtype=object)
print(a[0].dtype, a[1].dtype)
```

In that case, dtype of all the nested arrays is equal to 'object'.

The same situation for single array in the list converted to array of objects:

```
a = np.array([np.array([0, 1, 2], dtype=int)], dtype=object)
print(a[0].dtype)
```

In the practice I want to use the following code:
```
a = np.array([np.random.randint(0,5,random.randint(1, 5)) for i in range(n)], dtype = object)
```

If n > 1 then we obtain the array of integer arrays. But if n=1 then we obtain the array of object arrays.

The question is: Is it a BUG? If not, then what is the proper way to dynamically create the array of objects where each object is the NumPy array with different dimensions?

**Comment by bashtage** [comment]
I think the issue is that arrays are list-like, and so when you have regular shaped list-like of list-like (you have list[ndarray]), then it coalesces into a single array.  I would say this is by design. This is needed, for example, to build a 2-d array of objects from list-like.

The reason is doesn't happen is that it isn't possible to coalesce to a jagged array, and so the unequal length example is retailed as an object array or arrays.

**Comment by eric-wieser** [comment]
Doesn't your first code sample emit a warning that partially explains the problem?

**Comment by R-Mussabayev** [comment]
> Doesn't your first code sample emit a warning that partially explains the problem?

No, it doesn't. My NumPy's version is 1.20.1

**Comment by bashtage** [comment]
> a = np.array([np.random.randint(0,5,random.randint(1, 5)) for i in range(n)], dtype = object)

What do you gain from using an object array here over a list?

```python
a = [np.random.randint(0,5,random.randint(1, 5)) for i in range(n)]
```

**Comment by R-Mussabayev** [comment]
> > a = np.array([np.random.randint(0,5,random.randint(1, 5)) for i in range(n)], dtype = object)
> 
> What do you gain from using an object array here over a list?
> 
> ```python
> a = [np.random.randint(0,5,random.randint(1, 5)) for i in range(n)]
> ```

I want to use the "advanced indexing" capability of NumPy to dynamically indexing a subset of unequal length arrays:

import numpy as np
import random

arr = np.array([np.random.randint(0,5,random.randint(1, 5)) for i in range(5)], dtype = object)
new_arr = arr[arr[0]] #advanced indexing for creating new array by the sequence of indices

If it turns out at random that all nested arrays will have the same length, then the following error message will appear:

IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by rkern** [comment]
Not a bug, just an annoyance for a relatively rare use case as a consequence from how we want things to work for more common use cases. The usual workaround I recommend is to collect the arrays into a list, create an empty `dtype=object` array of the right size, then slice-assign them in. You can wrap that up into a utility function if you need to do this in several places.

```python
arrs = [np.array([0, 1], dtype=int), np.array([0, 1, 2], dtype=int)]
a = np.empty(len(arrs), dtype=object)
a[:] = arrs
```

**Comment by R-Mussabayev** [comment]
> Not a bug, just an annoyance for a relatively rare use case as a consequence from how we want things to work for more common use cases. The usual workaround I recommend is to collect the arrays into a list, create an empty `dtype=object` array of the right size, then slice-assign them in. You can wrap that up into a utility function if you need to do this in several places.
> 
> ```python
> arrs = [np.array([0, 1], dtype=int), np.array([0, 1, 2], dtype=int)]
> a = np.empty(len(arrs), dtype=object)
> a[:] = arrs
> ```

Thank you for the useful answer!
