### ISSUE TITLE
np.loadtxt() exception when loading CSV encoded with UTF-8 BOM

### ISSUE THREAD

**Issue by tpowell11** [numpy/numpy#18861]
When loading a file encoded with UTF-8 BOM, ValueError is thrown when reading the byte order mark at the beginning of the file. In this case, the BOM is `EF BB BF` which decoded to `ï»¿`, which naturally could not be converted to a float. The CSV file  [utf-8-bom.csv](https://github.com/tpowell11/tpowell11.github.io/blob/0b54d5ba185588aab3d4862eca44e32d0a35eca4/utf-8-bom.csv) was generated by LoggerPro 3.11. 

### Reproducing code example:

```python
import numpy as np
np.loadtxt('utf-8-bom.csv', delimiter=',',unpack=True)

```
[utf-8-bom.csv](https://github.com/tpowell11/tpowell11.github.io/blob/0b54d5ba185588aab3d4862eca44e32d0a35eca4/utf-8-bom.csv)
Note: I am unsure if GitHub strips BOM makers, if the above file does not cause this error, use a hex editor and add the string of bytes `EF BB BF` to the beginning of any UTF-8 file. 
### Error message:
```
Traceback (most recent call last):
  File "C:\Users\Tom Powell\Documents\GitHub\2020-21-notes\Bio\yeastplot.py", line 7, 
in <module>
    t1, c1, t2, c2, t3, c3, t4, c4 = np.loadtxt('utf-8-bom.csv', delimiter=',', unpack=True) #load data
  File "C:\Users\Tom Powell\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\npyio.py", line 1139, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "C:\Users\Tom Powell\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\npyio.py", line 1067, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "C:\Users\Tom Powell\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\npyio.py", line 1067, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "C:\Users\Tom Powell\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\npyio.py", line 763, in floatconv
    return float(x)
ValueError: could not convert string to float: 'ï»¿"Live'
```

### NumPy/Python version information:
```
>>> import sys, numpy
>>> print(numpy.__version__,sys.version)
1.19.4 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
```

**Comment by seberg** [comment]
I think we just use Python `open()` under the hood, even if you specify `encoding="utf-8"` (which you probably must/should here) and opening in text mode (which is the default), Python doesn't seem to strip it in `open()`.

So I think you should probably upstream the issue to Python's `open` and see what they say.

**Comment by LandingEllipse** [comment]
```python
import numpy as np
np.loadtxt(f, delimiter=",", unpack=True, encoding="utf-8-sig")
```
This of now yields
```
ValueError: could not convert string to float: '"Live'
```
but that's a different issue; you might want to try either
```python
import numpy as np
np.loadtxt(f, delimiter=",", unpack=True, encoding="utf-8-sig", skiprows=1)
```
if you don't care about the column names, or use `np.genfromtxt` with `names=True` to capture them (though be warned that it doesn't by default like the quote-escaped commas in the column names of your example file, so you'll have to do some digging to see if you can get it to play ball on that front).

**Comment by seberg** [comment]
Thanks @LandingEllipse,  I didn't know about `utf-8-sig` as encoding.  I think we can close this then. Its unfortunate that it is hard to find, but I think it is an encoding issue so to speak.

**Comment by tpowell11** [comment]
Thanks, wasn't aware of the more specialized encoding specifiers.
