### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by arunkothari84** [numpy/numpy#18860]
## Documentation

[Reference URL](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)

Typo in first example of One Dimensional Array

![image](https://user-images.githubusercontent.com/58799086/116272520-99169f00-a79e-11eb-84a4-c15eaeaa24f9.png)

**Comment by WarrenWeckesser** [comment]
That looks correct to me.  What is the problem?

**Comment by eric-wieser** [comment]
Duplicate of #8757
