### ISSUE TITLE
mypy / type hints: `np.bool_` and `bool` incompatible

### ISSUE THREAD

**Issue by mlondschien** [numpy/numpy#18876]
### Reproducing code example:

```python
# example.py
import numpy as np

def f(x: bool) -> bool:
    return x

y = np.bool_(True)

print(f(y))
```
yields
```
$ mypy example.py
example.py:9: error: Argument 1 to "f" has incompatible type "bool_"; expected "bool"
Found 1 error in 1 file (checked 1 source file)
```

The same happens for the inverse:
```python
# example.py
import numpy as np

def f(x: np.bool_) -> np.bool_:
    return x

y = True

print(f(y))
```
results in
```
example.py:9: error: Argument 1 to "f" has incompatible type "bool"; expected "bool_"
```

`np.float_` and `np.int_` work fine.

### NumPy/Python version information:

```
1.20.2 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
[GCC 9.3.0]
```

**Comment by BvB93** [comment]
Regardless of whether or not we should make this change (for example,  `True is not np.True_` for starters), 
it is currently impossible to create `bool` subclasses python. This holds both for runtime behavior as
well as static type checking, so there isn't really anything we _can_ do here.

Examples
----------
Runtime:
``` python
In [1]: class bool_(bool): pass
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-823896cfc52c> in <module>
----> 1 class bool_(bool): pass

TypeError: type 'bool' is not an acceptable base type
```

mypy:
``` python
In [2]: from typing import TYPE_CHECKING

In [3]: if TYPE_CHECKING:
   ...:     class bool_(bool): pass  # error: 'bool' is not a valid base class
   ...:
```

**Comment by seberg** [comment]
Getting rid of the numpy bool scalar is a pretty long-shot.  First, we would have to wade through the fact that we return 0-D arrays to scalars every time they don't run away fast enough.  Then, we could consider limiting scalars more or even ditching them altogether (very differenta, although the first might even make sense on the path to ditching them completely).

Only then, we might be able to make our bools the same as python bools.  Should we just close as won't/can't fix @BvB93?

**Comment by BvB93** [comment]
> Only then, we might be able to make our bools the same as python bools. Should we just close as won't/can't fix @BvB93?

I'd say so, yes. Even if we want to fix this only in the stub files itself (so no runtime changes) we'd need changes in the likes of mypy.

**Comment by mlondschien** [comment]
Thanks @BvB93 and @seberg. I've opened an issue at mypy to check whether we can address this there.
