### ISSUE TITLE
Please document the fact that cumsum(a)[-1] != sum(a)

### ISSUE THREAD

**Issue by mitkeyastromouse** [numpy/numpy#18886]
Hi, I recently run into problems because I was assuming that cumsum(a)[-1] always equals to sum(a). 
Why this is not the case has been explained (#9329), but I don't see documented. Would it be possible to document it under help(np.cumsum)?

**Comment by Atharva-Vidwans** [comment]
I would like to work on this issue.

**Comment by Mukulikaa** [comment]
Hey @rossbar, the merge didn't close the issue. Perhaps you can do it manually?

**Comment by mattip** [comment]
Thanks for the reminder
