### ISSUE TITLE
ImportError: No module named numpy

### ISSUE THREAD

**Issue by ifishtoo** [numpy/numpy#18883]
I looked at that doc and did not see my issue listed.
I am following the instructions found at https://github.com/xiph/rnnoise/blob/master/TRAINING-README to train rnnoise to filter the noise from my sound card. 
I installed python3 and python3-numpy using apt install python3 python3-numpy 
When I run 
./bin2hdf5.py ../src/trainning.f32 0 87 training.h5
I get 
Traceback (most recent call last):
  File "./bin2hdf5.py", line 5, in <module>
    import numpy as np
ImportError: No module named numpy

### Steps to reproduce:
clone the rnnoise github dir
mkdir git-rnnoise
cd git-rnnoise
git init
git clone https://github.com/xiph/rnnoise.git
% ./autogen.sh
% ./configure
% make
(1) cd src ; ./compile.sh

(2) ./denoise_training signal.raw noise.raw count > training.f32

    (note the matrix size and replace 500000 87 below)

(3) cd training ; ./bin2hdf5.py ../src/training.f32 0 87 training.h5

There are 2 more steps but I am stuck here...

fresh install  ubuntu 21.05
sudo apt install python python3-numpy
dpkg -l python3 
ii  python3        3.9.4-1      amd64        interactive high-level object-oriented language (default python3 version)
dpkg -l python3-numpy
ii  python3-numpy  1:1.19.5-1ubuntu2 amd64        Fast array facility to the Python 3 language

echo $PATH
/home/victor/bin:/home/victor/.local/bin:/home/victor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/lib/python3.9/dist-packages

I added that last bit in an effort to fix this myself.  I tried downloading a new version of numpy using pip but that did not help either.

### Error message:
$ ./bin2hdf5.py ../src/trainning.f32 0 87 training.h5
Traceback (most recent call last):
  File "./bin2hdf5.py", line 5, in <module>
    import numpy as np
ImportError: No module named numpy

**Comment by mattip** [comment]
The file `bin2hdf5.py` [is setup](https://github.com/xiph/rnnoise/blob/master/training/bin2hdf5.py#L1) to use `python` not `python3`. What happens if instead of 
`./bin2hdf5.py ../src/trainning.f32 0 87 training.h5` 
you try 
`python3 ./bin2hdf5.py ../src/trainning.f32 0 87 training.h5` ?

Usually this problem would be avoided by setting up a conda environment or a virtual environment, where `python` would be linked to `python3`.

**Comment by ifishtoo** [comment]
That worked!!!  Thank you!!!
