### ISSUE TITLE
NumPy master failed to build on Python 3.10.beta.1

### ISSUE THREAD

**Issue by fangchenli** [numpy/numpy#18907]
pandas started testing against Python 3.10 dev. We use `pip install git+https://github.com/numpy/numpy.git` to install NumPy in the CI. NumPy built successfully on Python 3.10.alpha.7, but it started failing on Python 3.10.beta.1, which was released yesterday. 

CI link: https://github.com/pandas-dev/pandas/runs/2502353399

xref https://github.com/pandas-dev/pandas/issues/41313

**Comment by seberg** [comment]
Oh, that double hash changes landed in CPython now, so we have to address gh-18833. But I guess the report also says which python version to condition that on, so should be quick.

**Comment by seberg** [comment]
@fangchenli I am a bit confused, I just tried locally and Python reports `a7`, although I guess I tried off the dev branch, so `a7` definitely works without modification?  Otherwise, I will go with `>a6` for now and if someone notices (unlikely...) we can change it to `>a7`...

**Comment by fangchenli** [comment]
@seberg Yes, `a7` works without modification. And we pined it to `a7` for now. 
For reference: https://github.com/pandas-dev/pandas/blob/master/.github/workflows/python-dev.yml

**Comment by seberg** [comment]
Oh, the tag didn't work, I updated it, the next nightly will be fine (I think they are bi-weekly, so it will be soon).

**Comment by charris** [comment]
>  (I think they are bi-weekly, so it will be soon)

There were two builds, travis (arm64) and azure (the rest), running on different days. I set both to run early Sunday mornings UTC.
