### ISSUE TITLE
Gitpod extensions GitLens and Markdown are broken

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#18904]
GitLens message:
```
Activating extension 'GitLens — Git supercharged' failed: Cannot read property 'fsPath' of undefined
```

I didn't capture the Markdown extension message, but it was unhappy too.

Same on the SciPy repo - something changes somewhere. 

Cc @trallard

**Comment by trallard** [comment]
😭 so much fun. Wil check and fix tomorrow

**Comment by rgommers** [comment]
Yes, VS Code or Gitpod is not super stable with that stuff :shrug:. A few more little things popped up. The sprint will help us polish things:)

**Comment by trallard** [comment]
😬 will pin a working version of the extensions. I avoided doing that to minimise the number of popups but I suppose that is better than having a broken extension.

👍🏼 Yes the sprints should help.

**Comment by trallard** [comment]
Might create another meta issue to track issues / nags discovered during the sprints

**Comment by trallard** [comment]
I have tracked this to the Vim extension - folks in the Gitpod community forum and issue tracker have reported similar issues so just for completeness the options might be to
- Uninstall / disable the extensions causing grief
- Uninstall the vim extension (I suppose most vim users will prefer the former)

Would suggest closing this issue then

**Comment by rgommers** [comment]
Thanks @trallard!

It seems like after I uninstalled the Vim extension I still had issues, but maybe the damage was done by then. I'll wipe everything out thoroughly and will start from scratch.
