### ISSUE TITLE
MAINT: Gitpod improvements/issues tracking 

### ISSUE THREAD

**Issue by trallard** [numpy/numpy#18913]
Opening this issue to track Gitpod related matters

## Issues that need fixing

- [x]  #18904 - no need to fix

## Documentation related

- [ ] Add debugging maintenance docs @trallard  will work on it soon

**Comment by trallard** [comment]
Sent  #18980 to add some user's troubleshooting points and should be able to finish/add the maintainer troubleshooting docs this week.

**Comment by rgommers** [comment]
We decided to remove Gitpod support (see [this mailing list thread](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/SSPI7HVL2PLWPFL42T6UNR2ENARE5A5E/)), so I'll close this issue. Thanks Tania!
