### ISSUE TITLE
Underflow RuntimeWarning in np.exp not raised for np.float32 data type

### ISSUE THREAD

**Issue by BenKMorley** [numpy/numpy#18916]
When the argument of np.exp is sufficiently negative there is an underflow, which should lead to a RuntimeWarning. However, for np.float32 arguments, this doesn't occur (for large negative numbers).

### Reproducing code example:

```python
import numpy as np
import warnings

np.seterr(all='warn')
warnings.filterwarnings('error')


# Triggers Warning
try:
    x = np.exp(np.float64(-1000))

except RuntimeWarning:
    print("Warning triggered for float64 type")


# Doesn't Trigger Warning
try:
    x = np.exp(np.float32(-1000))

except RuntimeWarning:
    print("Message won't print - Warning not triggered for float32 type")

```

### NumPy/Python version information:
Python    3.9.2
numpy    1.20.2
GCC       10.2.0
OS          RHEL 7.9

"""
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.2 3.9.2 (default, Mar 23 2021, 15:21:22) 
[GCC 10.2.0]
"""

**Comment by seberg** [comment]
Can also reproduce on 1.19.x, @r-devulap sorry if it isn't related, but could this be due to the SIMD code branches?

**Comment by r-devulap** [comment]
@seberg It is coming the SIMD code branches. Neither the SIMD implementations for float nor the double report an underflow for `np.exp`. `np.exp(np.float64(-1000))` lands on glibc implementation which reports it correctly.

**Comment by r-devulap** [comment]
I will add a patch to fix this behavior.
