### ISSUE TITLE
New CI failures.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#18932]
CI has started failing somewhat randomly with
```
______________________ TestSpecialFloats.test_exp_values _______________________

self = <numpy.core.tests.test_umath.TestSpecialFloats object at 0x7f7f62e58580>

    def test_exp_values(self):
        x = [np.nan,  np.nan, np.inf, 0.]
        y = [np.nan, -np.nan, np.inf, -np.inf]
        for dt in ['f', 'd', 'g']:
            xf = np.array(x, dtype=dt)
            yf = np.array(y, dtype=dt)
            assert_equal(np.exp(yf), xf)
    
        with np.errstate(over='raise'):
            assert_raises(FloatingPointError, np.exp, np.float32(100.))
            assert_raises(FloatingPointError, np.exp, np.float32(1E19))
            assert_raises(FloatingPointError, np.exp, np.float64(800.))
            assert_raises(FloatingPointError, np.exp, np.float64(1E19))
    
        with np.errstate(under='raise'):
            assert_raises(FloatingPointError, np.exp, np.float32(-1000.))
            assert_raises(FloatingPointError, np.exp, np.float32(-1E19))
>           assert_raises(FloatingPointError, np.exp, np.float64(-1000.))

```

**Comment by charris** [comment]
The test always passes on my machine, perhaps it is hardware related?

**Comment by r-devulap** [comment]
The randomness is a bit worrisome. It might be the case that different standard C libraries vary in how they report underflows, but that doesn't explain randomness.

**Comment by mattip** [comment]
One failing machine is reporting `NumPy CPU features:  SSE SSE2 SSE3* SSSE3* SSE41* POPCNT* SSE42* AVX* F16C* FMA3* AVX2* AVX512F* AVX512CD* AVX512_KNL? AVX512_KNM? AVX512_SKX* AVX512_CLX? AVX512_CNL? AVX512_ICL?`

**Comment by mattip** [comment]
Where a passing machine is reporting `NumPy relaxed strides checking option: False
NumPy CPU features:  SSE SSE2 SSE3 SSSE3* SSE41* POPCNT* SSE42* AVX* F16C* FMA3* AVX2* AVX512F? AVX512CD? AVX512_KNL? AVX512_KNM? AVX512_SKX? AVX512_CLX? AVX512_CNL? AVX512_ICL?`

**Comment by mattip** [comment]
so there is at least one case where it fails when AVX512F (and `AVX512CD`,  `AVX512_SKX`) **are** supported ('*') and passes when `AVX512F` (and `AVX512CD`,  `AVX512_SKX`) **are not** supported ('?'). @seiko2plus ideas?

**Comment by r-devulap** [comment]
@mattip do you know if they use the same compilers?

**Comment by mattip** [comment]
[here](https://github.com/numpy/numpy/actions/runs/818672755) are a bunch of CI runs with some failures, some successes. It seems the failure is correlated very well with AVX512F
run | state |has avx512f |compiler
--|--|--|--
basic (3.8) | success | AVX512F?  | GCC 9.3.0
basic (3.9) | failure | AVX512F* | GCC 9.3.0
debug | failure | AVX512F* | GCC 9.3.0
debug | failure | AVX512F* | GCC 9.3.0
blas64 | failure | AVX512F* | GCC 9.3.0
full | success | AVX512F? | [GCC 7.5.0
benchmark | success | AVX512F? | GCC 9.3.0
no_relaxed_strides | failure | AVX512F* | GCC 9.3.0
use_wheel | success | AVX512F? | GCC 9.3.0
no_array_func | failure | AVX512F* | GCC 9.3.0
no_openblas | failure | AVX512F* | GCC 9.3.0
sdist | success | AVX512F? | GCC 9.3.0

**Comment by seiko2plus** [comment]
just a simple nit, I'm not sure why CI didn't catch it during the pr build but maybe there's was no single worker with AVX512 support at that time.
