### ISSUE TITLE
Potential unsigned integer overflow risk in  FormatScientific of dragon4.c

### ISSUE THREAD

**Issue by Daybreak2019** [numpy/numpy#18937]
### Reproducing code example:
**Snippet **:

```
if (trim_mode != TrimMode_None && numFractionDigits > 0) {
        --pCurOut;
        while (*pCurOut == '0') {
            --pCurOut;
            ++bufferSize;
            --numFractionDigits;
        }
        if (trim_mode == TrimMode_LeaveOneZero && *pCurOut == '.') {
            ++pCurOut;
            *pCurOut = '0';
            **--bufferSize;**    -----> lack of check
            ++numFractionDigits;
        }
        ++pCurOut;
    }
```

### Error message:
When we run our analysis tool on NumPy, a potential int-overflow problem was reported,  see details below:
**File**:  numpy/core/src/multiarray/dragon4.c
**Function**:  FormatScientific
**Details** in [description](https://github.com/Daybreak2019/IssueReport/blob/master/Numpy/case-5648/5648.png)

### NumPy/Python version information:
the main branch of NumPy

**Comment by seberg** [comment]
I honestly doubt this is wrong.  I.e. the `numFrcationDigits` check is sufficient here.  If someone has a nice idea to make it clear in the code fine, otherwise, we could add an assert if it helps such analyzers.

**Comment by Daybreak2019** [comment]
Yes, we can not assert it as a real bug without using Fuzzing tools to expose it, and the complexity of this function also confuse us when we tried to manually figure out the condition.
So we say it is a potential problem here:

     if (trim_mode != TrimMode_None && numFractionDigits > 0) {
        --pCurOut;
        while (*pCurOut == '0') {
            --pCurOut;
            ++bufferSize;
            --numFractionDigits;
        }
        if (trim_mode == TrimMode_LeaveOneZero && *pCurOut == '.') {
            ++pCurOut;
            *pCurOut = '0';
            --bufferSize;                -------------------->  the potential points where int-overflow may happen
            ++numFractionDigits;
        }
        ++pCurOut;
    }

    /* print the exponent into a local buffer and copy into output buffer */
    if (bufferSize > 1) {               -------------------->  the affected branch if int-overflow happens
        char exponentBuffer[7];
        npy_int32 digits[5];
        npy_int32 i, exp_size, count;
        ......................
        /* copy the exponent buffer into the output */
        count = exp_size + 2;
        if (count > (npy_int32)bufferSize - 1) { -------------------->  the boundary check becomes invalid if int-overflow happens
            count = (npy_int32)bufferSize - 1;
        }
        memcpy(pCurOut, exponentBuffer, count);  -------------------->  buf-overflow may happen if int-overflow happens
        pCurOut += count;
        bufferSize -= count;
    }

**Comment by seberg** [comment]
I understand whats weird/potentially wrong.  I don't thin kits wrong, because I think htis can only be entered if the buffer includes `something.<at least one digit>` at the very top of your pasted code (if entering the first `if`). Then at the end of the first if, at worst the buffer will still contain `something.` which is definitely larger than 0.
