### ISSUE TITLE
Inconsistent broadcasting behavior

### ISSUE THREAD

**Issue by mwlon** [numpy/numpy#18947]
### Reproducing code example:

```
import numpy as np

arr = np.ones([5, 3])
pairwise_diff0 = arr[None, :, :] - arr[:, None, :]
pairwise_diff1 = np.subtract(arr[None, :, :], arr[:, None :])
print(pairwise_diff0.shape)
print(pairwise_diff1.shape)
```

### Unexpected result:
`pairwise_diff0` has the correct shape of `[5, 5, 3]`, but `pairwise_diff1` has a nonsensical shape of `[1, 5, 3]`!
```
with minus operator: (5, 5, 3)
with np.subtract: (1, 5, 3)
```

### NumPy/Python version information:

```
1.20.2 3.9.4 (default, Apr  5 2021, 01:50:46) 
[Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by rkern** [comment]
```
pairwise_diff1 = np.subtract(arr[None, :, :], arr[:, None :])
```

You have a typo in the second argument. You are missing a comma after the `None`.

**Comment by seberg** [comment]
Thanks robert, I was getting really confused how that could possibly be a bug :).
