### ISSUE TITLE
Copyright “The SciPy community”

### ISSUE THREAD

**Issue by lbogula** [numpy/numpy#18952]
## Documentation

1. the copyright refers to the "SciPy" community and should be changed to "NumPy". 

2. Should the start date be changed according to the numpy.org webpage? On numpy.org the copyright starts 2019, on the numpy documentation pages it starts 2008

**Comment by rgommers** [comment]
Ah, this is about https://numpy.org/doc/stable/. Changing only the end date seems good, so:
```
Copyright 2008-2020, The SciPy community.
```
should be
```
Copyright 2008-2021, The NumPy community.
```

**Comment by rgommers** [comment]
NumPy is older than 2008, but I think we only had html docs from then on, or some such reason for the 2008 start date:)

**Comment by misalraj** [comment]
hey, @lbogula how did you get that which file need to change?

**Comment by lima-tango** [comment]
> hey, @lbogula how did you get that which file need to change?

Hi @misalraj, since the copyright is written on all pages, we assumed it would be in a configuration file. Therefore, we searched for "SciPy community" in `doc/source/config.py`.
