### ISSUE TITLE
PyArrayNeighborhoodIterObject is left in wrong state after PyArray_ITER_GOTO1D on the underlying iterator

### ISSUE THREAD

**Issue by ReallyNiceGuy** [numpy/numpy#18971]
PyArray_ITER_GOTO1D doesn't update coordinates in non contiguous mode, which is used by PyArrayNeighborhoodIterObject to calculate it's own position on PyArrayNeighborhoodIter_Reset, leaving the PyArrayNeighborhoodIterObject pointing to the last position before the call to PyArray_ITER_GOTO1D.

Note that at creation of a new PyArrayNeighborhoodIterObject, if forces a non contiguous mode on the underlying iterator.

### Reproducing code example:

```c
//img is a 2D contiguous array (1200x1200)
PyArrayIterObject *iter = (PyArrayIterObject *) PyArray_IterNew((PyObject*) img);
npy_intp bounds[] = {-1,1,-1,1};
PyArrayNeighborhoodIterObject*neigh_iter = (PyArrayNeighborhoodIterObject*) PyArray_NeighborhoodIterNew(
                  iter, bounds, NPY_NEIGHBORHOOD_ITER_ZERO_PADDING ,0);
PyArray_ITER_GOTO1D(iter,1000);
PyArrayNeighborhoodIter_Reset(neigh_iter);
// At this point, iter is pointing to the 1000th item,
// but neigh_iter is still pointing to the 0th entry on iter
```

**Comment by seberg** [comment]
Yeah, I agree, it seems like a bug and it the reset should work, if you want are up to it, a PR is welcome to fix it.

That said, I don't want to be pessimistic about it, but this API is very old and the only usage I am aware of is `scipy/signal/correlate_nd.c.src` and I don't really recall anyone ever using it specifically (although I am sure occasionally it is used).  There is no plan to make it go away, but it is not commonly used, and it seems plausible that it could use modernization.
