### ISSUE TITLE
Dependabot is opening PRs on forks

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#18977]
Example: https://github.com/rgommers/numpy/pull/7. This is ridiculous spam - how do we make that stop?

**Comment by mattip** [comment]
Do you have dependabot "turned on" for your personal repos? FWIW, I am not seeing dependabot on my fork.

**Comment by rgommers** [comment]
No I don't. Something just changed with the dependabot config on the GitHub side.

Your fork is way behind, it doesn't even have a `main` branch and https://github.com/mattip/numpy/tree/master/.github doesn't have a `dependabot.yml`. I bet that if you update your fork, you'll get PRs as well.

It's probably something in that `.yml` file that we need to toggle.

**Comment by mattip** [comment]
there is an open issue about it dependabot/dependabot-core#2804

**Comment by rgommers** [comment]
Thanks for finding that. No action for months, and no way to disable:(

It must have come in with gh-18868.

**Comment by rgommers** [comment]
Wow, apparently they haven't fixed this for a very long time: https://github.com/dependabot/dependabot-core/issues/2198. The only workaround is "delete your fork", which I am definitely not doing. I'd rather nuke dependabot.

**Comment by trallard** [comment]
I can confirm this happening in my forks too. For now - I have removed the notifications from my notification centre and added an alias to close the PR and delete the branch 🤷🏽

**Comment by mattip** [comment]
So I guess one work-around might be to delete the main branch, and leave the default branch on my fork as master

**Comment by melissawm** [comment]
> I can confirm this happening in my forks too. For now - I have removed the notifications from my notification centre and added an alias to close the PR and delete the branch 🤷🏽

Can you link to any docs on how to do that? I'd like to get rid of it too

**Comment by rgommers** [comment]
Maybe push a commit that nukes the `dependabot.yml` file in your fork of main, and we can see if you still get spammed in a week?

**Comment by rgommers** [comment]
Okay, dependabot maintainers are not fixing this anytime soon, everyone is getting spammed on their forks, and it's just a massive waste of resources all around. I propose to remove dependabot from the main repo until they fix this. It doesn't bring that much value after all, we can just bump dependencies manually in bunches like we used to - that's actually nicer for the commit logs anyway.

**Comment by mattip** [comment]
I am in favor of removing the dependabot integration from the main repo. If we want, someone could volunteer to be the "dependabot appointee" who will add it to the main branch on their fork. Then the appointee can make PRs to update dependencies as needed.
