### ISSUE TITLE
There should be a default serializer for the type of float32 defined.

### ISSUE THREAD

**Issue by zsong** [numpy/numpy#18994]
### Reproducing code example:

There should be a default serializer for the type of **float32** defined. Flask/jsonify() can serilize the type of float64 but not float32.

The following code throws error: TypeError: Object of type float32 is not JSON serializable
```python
    x = {'value': numpy.float32(0.1)}
    return jsonify(x)
```

This one works:
```python
    x = {'value': numpy.float64(0.1)}
    return jsonify(x)
```

### Error message: 
TypeError: Object of type float32 is not JSON serializable

**Comment by rkern** [comment]
Please see the discussions on #12481 and #16432.

Closing this issue as this is essentially a duplicate request.
