### ISSUE TITLE
Overflow warnings from np.testing.assert_array_equal for subnormal inputs

### ISSUE THREAD

**Issue by hawkinsp** [numpy/numpy#18992]
### Reproducing code example:

```
In [1]: import numpy as np

In [2]: np.testing.assert_array_equal(np.array([1,2,3], np.float32), np.array([1,1e-40,3], np.float32))
/Users/phawkins/.pyenv/versions/3.9.0/envs/py3.9.0/lib/python3.9/site-packages/numpy/testing/_private/utils.py:830: RuntimeWarning: overflow encountered in true_divide
  max_rel_error = max(error[nonzero] / abs(y[nonzero]))
```

It's surprising for `assert_array_equal` to issue any kind of warning.

I suspect the `errstate` guard here: https://github.com/numpy/numpy/blob/74a65e1cef00e3e9805dbc88252a023975b70079/numpy/testing/_private/utils.py#L813
should be suppressing `over` and possibly `under` as well.

### NumPy/Python version information:

```
1.20.3 3.9.0 (default, Nov  9 2020, 14:53:43)
[Clang 11.0.0 (clang-1100.0.33.17)]
```

**Comment by seberg** [comment]
The proposal to ignore everything here seems right to me on first sight. Just if you got time, do you want to look into a PR?
