### ISSUE TITLE
Inconsistent behavior on ufunc "np.ceil"

### ISSUE THREAD

**Issue by MathAmp** [numpy/numpy#19004]
np.ceil (and also np.floor) is not working properly when "where" argument is given.

### Reproducing code example:

```python
import numpy as np

# create random matrix for test
mat = np.random.rand(3, 3, 2)
print("matrix", mat, sep="\n\n")

# give mask and check. 
# Ordinally, mask_0 == mask_2 and mask_1 == mask_3
mask_0 = np.ceil(mat, where=np.array([True, True]))
mask_1 = np.ceil(mat, where=np.array([True, False]))
mask_2 = np.ceil(mat, where=np.array([True, True]))
mask_3 = np.ceil(mat, where=np.array([True, False]))

# check result
print("mask0", mask_0, "mask1", mask_1,
      "mask2", mask_2, "mask3", mask_3, sep="\n\n")
print("\n*** Is mask0 and mask2 consistent? ***")
print(mask_0 == mask_2)
print("\n*** Is mask1 and mask3 consistent? ***")
print(mask_1 == mask_3) # Inconsistent. 

```

### Error message:

No error message. 
mask_1 != mask_3 and especially mask_3 shows strange behavior.

The same error was found for np.floor function.

### NumPy/Python version information:

numpy version : 1.20.3
sys version : 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:23:07) [MSC v.1927 32 bit (Intel)]

**Comment by WarrenWeckesser** [comment]
This is normal behavior.  The docstring for `np.ceil` explains the `where` parameter:
```
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.\
```
The last sentence is important, and explains the strange result you see in `mask_1` and `mask_3`.  You haven't given an `out` parameter, so `ceil` allocates a new array to hold the results; the input `mat` is *not* copied to this new array.  Only the elements of the new array where `where` is True will be assigned values by `ceil`.  Where `where` is False, the memory is not initialized, so it will hold whatever values happened be in the allocated memory.

Actually, the surprising behavior that I observe here is that the values in `mask_1` where `where` is False happen to hold copies of `mat`:
```
In [71]: mat[:,:,1]
Out[71]: 
array([[0.15601633, 0.26378248, 0.97469751],
       [0.40560407, 0.82609818, 0.53414023],
       [0.28433876, 0.33463044, 0.3308359 ]])

In [72]: mask_1[:,:,1]
Out[72]: 
array([[0.15601633, 0.26378248, 0.97469751],
       [0.40560407, 0.82609818, 0.53414023],
       [0.28433876, 0.33463044, 0.3308359 ]])
```
This suggests that perhaps an internal calculation results in a temporary copy of `mat` that is then deallocated, and the same block of memory is used to create the new array that becomes `mask_1`.

The uninitialized values in `mask_3`  are more typical:
```
In [73]: mask_3[:,:,1]
Out[73]: 
array([[0.00000000e+000, 2.05833592e-312, 2.33419537e-312],
       [1.08221785e-312, 2.31297541e-312, 2.29175545e-312],
       [2.37663529e-312, 2.35541533e-312, 1.20953760e-312]])
```
