### ISSUE TITLE
DOC: left navbar is repeated in the devdocs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#19028]
See for instance https://numpy.org/devdocs/dev/index.html

This does not happen in the stable docs. Did something change in the theme?

**Comment by rossbar** [comment]
I'm not sure if it's a change in the theme or a change in how sphinx itself is handling files with multiple `toctree`s. It seems that originally (i.e. in the stable docs) the left sidebar is populated only by the [first toctree](https://github.com/numpy/numpy/blob/main/doc/source/dev/index.rst#contributing-to-numpy), whereas the sidebar in the devdocs is populated by [both toctrees](https://github.com/numpy/numpy/blob/main/doc/source/dev/index.rst#development-process---details).

I have to look at things more carefully to see what specifically changed, but this seems like a good hypothesis to start from.

**Comment by melissawm** [comment]
Removing the `:hidden:` option (see [this commit](https://github.com/numpy/numpy/commit/cb73fa9ae1ad3ecd2c8cb44ef870f76ba6856d44)) solves the issue, but now it seems like this toctree at the beginning of the file is not needed, as the same contents are shown in the left sidebar. 

I propose just removing it.
