### ISSUE TITLE
Allow np.array() to accept string arguments and turn them into 1D, 2D, ...., nD arrays

### ISSUE THREAD

**Issue by benedictusalvian** [numpy/numpy#19027]
## Feature

Suggestion: Allow `np.array()` to accept string arguments and turn them into 1D, 2D, ...., nD arrays, just like `np.matrix()`.

`x = np.matrix("1 0; 0 0")` is able to take in the given string and turn it into the following matrix.
```sh
x =   [ 1 0 ]
      [ 0 0 ]
      # "1 0; 0 0"
```
To turn the matrix into an array, we use `x = np.asarray(x)`.

`x = np.array("1 0; 0 0")` does not allow string inputs to be turned into an array.

I think this feature would be useful when users need to input a matrix into the command line as arguments. Such as
`python -m myModule "1 0; 0 0"`

Because as of now, it is difficult to input matrices into the command line without first turning it into a matrix object then converting it using `np.asarray(x)`.

**Comment by bashtage** [comment]
For now you could use `np.matrix("1 0;0 0").A`.  I think this is too ambiguous to add to `array`.  It could be useful if there was a simple string parser function that works like `matrix` that would work well with a standard string format.

**Comment by eric-wieser** [comment]
I think having `np.array` accept this is a bad idea. Mixing constructors with string parsers just makes everything a mess, especially when it comes to arrays of strings.

An `np.parse_colon_string` function would avoid this concern; but even that just adds to the confusion of `np.genfromtxt` / `np.loadtxt` etc. Personally I think this feature has no place in NumPy.

**Comment by benedictusalvian** [comment]
> 
> 
> I think having `np.array` accept this is a bad idea. Mixing constructors with string parsers just makes everything a mess, especially when it comes to arrays of strings.
> 
> An `np.parse_colon_string` function would avoid this concern; but even that just adds to the confusion of `np.genfromtxt` / `np.loadtxt` etc. Personally I think this feature has no place in NumPy.

That's a fair point. I brought up this feature suggestion partly because the class `numpy.matrix` may be removed in the feature and this workaround `np.matrix("1 0;0 0").A` might no longer work. And without this workaround, it will be difficult for users to input matrices through the command line without building a string parser of our own.

As of now, `numpy.matrix` accepts 
```
Parameters

    data: array_like or string

        If data is a string, it is interpreted as a matrix with commas or
        spaces separating columns, and semicolons separating rows.
```
And `numpy.array` accepts
```
Parameters

    object: array_like

        An array, any object exposing the array interface, an object
        whose __array__ method returns an array, or any (nested) sequence.
```

**Comment by seberg** [comment]
Closing as Eric mentioned earlier, this has no place in `np.array` (and friends).  A dedicated function may make sense, but appetite for that is not very large also (and there is `fromtext` and `loadtxt` although they don't quite cover this request.)
