### ISSUE TITLE
TST: The github actions tests keep getting cancelled

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#19032]
As observed in https://github.com/numpy/numpy/pull/19029 and https://github.com/numpy/numpy/pull/19031 all the github actions workflows keep getting cancelled without a clear indication as to why.
All other CI's (azure, travis, _etc._) appear to be running fine.

Example: https://github.com/numpy/numpy/pull/19029/checks?check_run_id=2611780411

**Comment by charris** [comment]
I've been seeing that for several days. More information here https://github.com/numpy/numpy/actions/runs/854011834/workflow. The problem seems to be in `.github/workflows/circleci.yml`. Not sure why it is suddenly a problem, maybe @larsoner has an idea.

**Comment by charris** [comment]
I'm going to guess that `artifact-path` is broken.

**Comment by larsoner** [comment]
If `artifact-path` is broken, it should still create the link and it will just 404 when you click on it.

I think this is a GitHub-wide thing, I experienced this all day today on this PR (where the artifact redirector is not installed):

https://github.com/pyvista/pyvistaqt/pull/109

Looking at [GitHub Status](https://www.githubstatus.com/) we see there is a problem:

> Update - We continue to observe our services recover with an increasing number of successful builds, we will keep monitoring until full recovery and will provide more updates soon.
> May 18, 16:08 UTC
> Update - We have rolled out a fix and are observing that action runs are slowly improving. We are monitoring recovery and will provide more updates soon.
> May 18, 13:58 UTC
> Update - We have begun rolling out a mitigation attempt and will provide an update once we know more.
> May 18, 13:12 UTC
> Update - We have confirmed that run starts are delayed for a number of customers. We have identified the issue and are working on a fix.
> May 18, 11:06 UTC
> Investigating - We are investigating reports of degraded performance for GitHub Actions.
> May 18, 08:45 UTC

**Comment by BvB93** [comment]
Closing, the github statuses are all back to green and the tests seem to be properly running again.
