### ISSUE TITLE
How to build Linux Binaries for numpy+mkl？

### ISSUE THREAD

**Issue by guoqiangqi** [numpy/numpy#19030]
Thanks for building such great project,  I want to use numpy+mkl in Linux, but currently only windows binaries are available, can anyone tell me how to make numpy+mkl wheel by building from source?

**Comment by bashtage** [comment]
The easy way, if available to you, is to install NumPy using conda, which will default to a build that includes MKL.

**Comment by guoqiangqi** [comment]
> The easy way, if available to you, is to install NumPy using conda, which will default to a build that includes MKL.

Thanks for your reply. Do you have any guides about building `numpy`+`mkl` from source since i have modified  some origin codes in `numpy` ?

**Comment by Qiyu8** [comment]
I tried to build numpy+mkl wheel through this [guide](https://software.intel.com/content/www/us/en/develop/articles/build-numpy-with-mkl-and-icc.html), but the wheel didn't include mkl like [windows one](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy), @bashtage @mattip @charris Any thoughts?

**Comment by Qiyu8** [comment]
After browsering [Windows wheel package (.whl) on Pypi](https://github.com/numpy/numpy/issues/5479), I think @carlkl and @cgohlke may provide solutions, Also [this archived repository](https://github.com/numpy/windows-wheel-builder) may help.

**Comment by bashtage** [comment]
You should post your build command(s) and build log to a gist. One possibility is that Windows supports including libraries while Linux defaults to assuming the libraries are already available.
