### ISSUE TITLE
mcAfee Endpoint security detected a threat numpy 1.20.3

### ISSUE THREAD

**Issue by studioj** [numpy/numpy#19040]
### Steps to reproduce:

pip install numpy==1.20.3

### Not reproducible on :
pip install numpy==1.20.2

### Error message:
![image](https://user-images.githubusercontent.com/22102283/118801799-b45a6300-b8a1-11eb-9fb0-6b194c07c338.png)

it states an issue with random\_common.cp37-win_amd64.pyd

**Comment by bashtage** [comment]
False positive?

![image](https://user-images.githubusercontent.com/5585221/118804621-d3a2c180-b89c-11eb-87ef-2eeee80ba736.png)

**Comment by bashtage** [comment]
FWIW 3.8 also gets a random flag from a different vendor:

![Uploading image.png…]()

**Comment by studioj** [comment]
most likely a random positive but i found no issues in the open/closed list related to this ... 
people looking for the issue will at least have a landing place

**Comment by mattip** [comment]
Please check your pip indices. If you are downloading it from a reputable source (pypi.org) please report this to mcAfee as a false positive.

**Comment by studioj** [comment]
reported to mcAfee they fixed the false positive
