### ISSUE TITLE
Confusing ndarray repr:  always shows dtype as if in native byteorder

### ISSUE THREAD

**Issue by Zac-HD** [numpy/numpy#19059]
```python
>>> from numpy import array, dtype

# The repr of a dtype object distinguishes non-native byteorder.
>>> dtype('<u2')
dtype('uint16')
>>> dtype('>u2')
dtype('>u2')

# But arrays always use the repr of the native endianness
>>> array([0], dtype='<u2')
array([0], dtype=uint16)
>>> array([0], dtype='>u2')
array([0], dtype=uint16)  #   <-- this is confusing
```

This isn't strictly speaking a *bug*, but using the byteorder-sensitive repr of the dtype instead would make it easier to tell when you have an endianness issue in e.g. [this StackOverflow question](https://stackoverflow.com/q/67634660).

**Comment by Zac-HD** [comment]
@mattip - any tips on where I should be looking to fix this?

Twenty minutes with `grep` and examining various `__repr__`-related code snippets didn't get me anywhere, though I can see from https://github.com/numpy/numpy/blob/main/numpy/core/_dtype.py that it might be tricky if I can't simply have the `array` repr defer to the `dtype` repr...

**Comment by seberg** [comment]
Closed by gh-23295
