### ISSUE TITLE
NumPy 1.18.5 release notes and tag

### ISSUE THREAD

**Issue by drjasonharrison** [numpy/numpy#19054]
## Documentation

I cannot find the release notes for NumPy 1.18.5, nor a tag for that release.

https://numpy.org/doc/stable/release/1.18.4-notes.html states that 1.18.4 was the last planned release before 1.19.

and PyPi has a release for 1.18.5: https://pypi.org/project/numpy/1.18.5/

Is there a tag, or release notes, that have been misplaced?

**Comment by charris** [comment]
There was a 1.18.5 release, you can find it at https://github.com/numpy/numpy/releases/tag/v1.18.5. It is missing from the main branch, however. I'll fix that.
