### ISSUE TITLE
Stubs for array_equal appear out of date.

### ISSUE THREAD

**Issue by PhilReinhold** [numpy/numpy#19056]
Stubs for array_equal appear out of date.

### Reproducing code example:

```python
import numpy as np
a = np.array([1])
np.array_equal(a, a, equal_nan=True)
```

Then running mypy on this gives `error: Unexpected keyword argument "equal_nan" for "array_equal"`

I see that #16128 introduced this argument but did not update the stubs. It appears it must be added in https://github.com/numpy/numpy/blob/5f3c3181b5d8db0e430e5f605cc45c4392f04934/numpy/core/numeric.pyi#L241

### Error message:

Running mypy on this gives `error: Unexpected keyword argument "equal_nan" for "array_equal"`

### NumPy/Python version information:

1.20.2 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)]

also mypy v0.812

**Comment by charris** [comment]
@BvB93 Ping.

**Comment by BvB93** [comment]
By the looks of it this should be a simple change to make. Would you be willing to create a PR?
``` diff
- def array_equal(a1: ArrayLike, a2: ArrayLike) -> bool: ... 
+ def array_equal(a1: ArrayLike, a2: ArrayLike, equal_nan: bool = ...) -> bool: ... 
```
