### ISSUE TITLE
Error while installing from source

### ISSUE THREAD

**Issue by alicezanella** [numpy/numpy#19065]
Hello, 
I have to install numpy from source because I'm working on a server. 
After having built Python-3.9.0 I'm trying to install also numpy with this command: 

`python3 setup.py build install --prefix=/home/zanella/softwares/numpy-main`

And this is what I get: 

`Traceback (most recent call last):
  File "/home/zanella/softwares/numpy-main/setup.py", line 50, in <module>
    MAJOR, MINOR, MICRO = FULLVERSION.split('.')[:3]
ValueError: not enough values to unpack (expected 3, got 1)`

Do you have any ideas of what it could be? 

Thank you, 

Alice

**Comment by charris** [comment]
Where did you get NumPy?

**Comment by alicezanella** [comment]
The code here on github

**Comment by charris** [comment]
> The code here on github

Which code? There is the repo, and there are also several files in the tagged release.

**Comment by charris** [comment]
If you are in the repo, what does `git describe` show?

**Comment by alicezanella** [comment]
I checked, I used the wrong repo! Thank you

**Comment by charris** [comment]
You might want to look into downloading the correct numpy wheel as a file, then copying it to the server for installation.
