### ISSUE TITLE
np.int32 not a subdtype of np.int

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#19069]
This throws `False` in the latest numpy versions:
```python
np.issubdtype(np.int32, np.int)
```

**Comment by rkern** [comment]
We have warned that the behavior would change since at least `1.17.4`:

```
/home/rkern/.edm/envs/py36/bin/ipython:1: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  #!/home/rkern/.edm/envs/py36/bin/python3
True
```

Use `np.integer` as the base dtype to detect numpy integer scalars.

**Comment by david-cortes** [comment]
The link in the warning BTW says to use `int`, which also returns `False`:
```python
np.issubdtype(np.int32, int)
```

**Comment by eric-wieser** [comment]
In 1.20 onwards that emits a second warning about `np.int` also being deprecated.

**Comment by rkern** [comment]
What link?

**Comment by rkern** [comment]
Ah, got it. That's not from `issubdtype()` but just from accessing `np.int`, which has always (since _very_ early releases of `numpy`) been just an alias to the builtin `int`, not an actual `numpy` scalar type.

```
|2> np.int
<ipython-input-2-5dcbb6b27796>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.int
int
```

_That_ warning is telling you to use `int` instead of `np.int`, but it doesn't know anything about what you actually intend to use it for, just that the alias is going away eventually.

For your desired behavior in `issubdtype()`, you want `np.integer`.

**Comment by david-cortes** [comment]
Tried yet another NumPy version, I see it now has an informative warning:
```
FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
```
