### ISSUE TITLE
LGTM alerts . 

### ISSUE THREAD

**Issue by charris** [numpy/numpy#19077]
I notice that there are still a fair number LGTM alerts, many of which look pretty simple. I wonder if they would be a good source of issues for the next NumPy sprint?

**Comment by default-303** [comment]
hey, can i have this issue? 
I'm quite new to this so I might need some guidance

**Comment by ganesh-k13** [comment]
Posting for reference the LGTM alerts: https://lgtm.com/projects/g/numpy/numpy/alerts/?mode=list

I can take a look at the errors in arithmetic.h, which were added during our SIMD division change.

**Comment by default-303** [comment]
@ganesh-k13 so i just need to fix the errors/warnings shown in the lgtm page ?

**Comment by mattip** [comment]
> I'm quite new to this so I might need some guidance

Welcome.

Please read the [developer's workflow guide](https://numpy.org/devdocs/dev/development_workflow.html), especially around [commit messages](https://numpy.org/devdocs/dev/development_workflow.html#writing-the-commit-message). 

Some of those errors/warnings will be difficult to fix since LGTM's ideas may not agree with ours. Try to group the fixes in some logical way: for instance, all the unused imports in one PR and in another PR all the integer overflow warnings.

**Comment by default-303** [comment]
@mattip thanks. 

I've removed all of the unused imports only to find out it breaks the code fsr(hoping you'll tell why), but reading the exceptions and restoring the removed imports solved the issue.
I've restored the following imports - 
- [_get_ndarray_c_version](https://lgtm.com/projects/g/numpy/numpy/snapshot/6c44fd65d4e131877d6755842629906ebb18f20b/files/numpy/core/multiarray.py?sort=name&dir=ASC&mode=heatmap#xdc2388d3cba833a1:1)
- [Extension](https://lgtm.com/projects/g/numpy/numpy/snapshot/6c44fd65d4e131877d6755842629906ebb18f20b/files/numpy/distutils/core.py#xd1c458e04315674a:1)

I can now build and run tests. The test results are same after removing unused imports as linked below.

Before fixing imports - 
![before_fixing_unused_imports](https://user-images.githubusercontent.com/54715852/119339084-6503a080-bcae-11eb-83da-7093da5f947f.png)

After fixing imports - 
![after_fixing_unused_imports](https://user-images.githubusercontent.com/54715852/119339222-89f81380-bcae-11eb-9bfe-f7e5426532b2.png)

Do you want me to go ahead and do a pr  ?

**Comment by default-303** [comment]
@mattip do you want me to go ahead and do a pr man? or is there I should be doing first ?

**Comment by mattip** [comment]
A cleanup PR would be welcome. Please be sure it only changes the lines you intend to change: sometimes coding tools can "clean up" formatting which makes PRs harder to review.

**Comment by default-303** [comment]
@charris I've raised a new PR for unused variables. Can anyone check and give a suitable review?

**Comment by mattip** [comment]
Usually review requires a few days. If after a week no-one has reviewed, feel free to ping (without names) in the PR with a "please review" comment.

**Comment by default-303** [comment]
thanks, noted.

**Comment by charris** [comment]
Keeping this open for a while.

**Comment by ManjunathBharadwaj01** [comment]
Hello, can I contribute to this particular issue?
I'm new , and want to learn the GitHub ways, can somebody help me learn?

**Comment by kurchi1205** [comment]
https://lgtm.com/projects/g/numpy/numpy/alerts/?mode=list
I want to make my first contribution by fixing version.py .
Can I work on it?

**Comment by mattip** [comment]
> I want to make my first contribution by fixing version.py .

What would you fix? I am not seeing any [LGTM alerts for `numpy/version.py`](https://lgtm.com/projects/g/numpy/numpy/latest/files/numpy/?sort=name&dir=ASC&mode=heatmap) (last file in the link). Or perhaps you meant the single miniscule [warning in `numpy/_version.py`](https://lgtm.com/projects/g/numpy/numpy/latest/files/numpy/_version.py?sort=name&dir=ASC&mode=heatmap#L501) ?

**Comment by kurchi1205** [comment]
It is listed under error

**Comment by eric-wieser** [comment]
That file is a generated file. The correct fix will be to tell lgtm to ignore that file. You could fix it upstream in versioneer too if you wanted.

**Comment by MansiSMore** [comment]
Hello, I am new to open source contribution, Can I fix the "Suspicious unused loop iteration variable" issue from [https://lgtm.com/projects/g/numpy/numpy/alerts/?mode=list] ???

**Comment by mattip** [comment]
We do not assign work. Anyone can submit a PR. Please mark that as `related to #19077` so others will see that you are working on it.

**Comment by dhivyasreedhar** [comment]
Can I work on this? I'm new so can someone guide me?

**Comment by Stark-developer01** [comment]
Is the issue fixed? Otherwise I would take up the issue.

**Comment by priorigratia** [comment]
I would want to take this issue up if it is still open

**Comment by charris** [comment]
@priorigratia Go ahead, but keep in mind that some of the remaining issues are subtle and harder than they look.

**Comment by satyam8123** [comment]
Let Me Do this issue

**Comment by mattip** [comment]
We do not assign work. Anyone can submit a PR. Please mark that as related to #19077 so others will see that you are working on it.

**Comment by sistaseetaram** [comment]
Hi, I would like to work on the following issue. [regexp miss-match.](https://lgtm.com/projects/g/numpy/numpy/snapshot/4210c98ed9e41321321345682157513296f3e424/files/numpy/linalg/lapack_lite/clapack_scrub.py)  line 227. But I'm confused about what we're trying to match?   Can you please provide test cases so that I can work on it. This is my first project so kindly help me.

**Comment by eric-wieser** [comment]
> Hi, I would like to work on the following issue. [regexp miss-match.](https://lgtm.com/projects/g/numpy/numpy/snapshot/4210c98ed9e41321321345682157513296f3e424/files/numpy/linalg/lapack_lite/clapack_scrub.py) line 227. But I'm confused about what we're trying to match? Can you please provide test cases so that I can work on it. This is my first project so kindly help me.

This code path is exercised by https://github.com/numpy/numpy/blob/main/numpy/linalg/lapack_lite/README.rst

**Comment by sistaseetaram** [comment]
I've gone through it.. and now I'm a bit confused. will you please guide me through it? There are two types of subroutines in f2c_*.c,  extern subroutines and local subroutines, and I am a bit confused whether we're trying to match both or only local subroutines.
Given pattern string:
`` r'/\* Subroutine \*/^\s*(?:(?:inline|static)\s+){0,2}(?!else|typedef|return)\w+\s+\*?\s*(\w+)\s*\([^0]+\)\s*;?'``
As this above regex has multiple errors.
1. it matches no string as ^ is included in between
2. it matches only single line subroutines as stringIO splits at \n and subroutines can be multi-line.
I think it should be changed to 
``r'/\* Subroutine \*/\s*(?:(?:inline|static)\s+){0,2}(?!else|typedef|return)\w+\s+\*?\s*(\w+)\s*\([^0]+|[\n\s]*\)\s*;?'``
suggest changes if wrong. I just started to work on open source so sorry for long messages.

**Comment by acse-srm3018** [comment]
Hi everyone, I'd like to contribute to this issue. I am a beginner in contributing to open source projects. Could someone help and guide me on how to start a contribution?

**Comment by ovynnej** [comment]
@acse-srm3018 If you're still interested in working on this issue, [here's](https://numpy.org/devdocs/dev/index.html#development-process-summary) a summary for first-time contributors to numpy!

**Comment by charris** [comment]
I'm going to close this as we are disabling LGTM. Continuing work to fix the  already found problems is of course welcome.
