### ISSUE TITLE
Feature request: Generator.integers support for out=

### ISSUE THREAD

**Issue by to7m** [numpy/numpy#19088]
It would be nice to have Generator.integers match the functionality of Generator.random by allowing usage of the `out` parameter.

Use case: Repeatedly generating large arrays of indices, without needing to allocate new memory each time.

**Comment by WarrenWeckesser** [comment]
The issue https://github.com/numpy/numpy/issues/15581 is a request to add `out` to all the `Generator` methods, so I'm closing this issue as a duplicate.
