### ISSUE TITLE
memory leak in copy array slice

### ISSUE THREAD

**Issue by laazy** [numpy/numpy#19091]
numpy array will memory leak when copy array slice in another container.

### Reproducing code example:

```python
import numpy as np

def array():
    return np.random.random(3000*40).reshape(3000, 40)

def main():
    l = []
    for i in range(40*5000):
        l.append(array()[-1])
    print(len(l))

if __name__ == '__main__':
    main()
```

### Error message:
No message

### NumPy/Python version information:
NumPy Version : 1.20.3. See this bug in 1.17.3 also.
Python: 3.7.3 and 3.9.1

**Comment by mattip** [comment]
Can you explain what you mean by memory leak? `b = a[-1]` where `a.shape == (3000, 40)` returns a [**view**](https://numpy.org/devdocs/glossary.html?highlight=glossary#term-view) into `a` and keeps a reference to `a`  as `b.base`. If you want a **copy**, you should do `b = a[-1].copy()`.

This is explained also in [indexing](https://numpy.org/devdocs/user/basics.indexing.html#other-indexing-options):
> Note that slices of arrays do not copy the internal array data but only produce new views of the original data. This is different from list or tuple slicing and an explicit copy() is recommended if the original data is not required anymore.

**Comment by laazy** [comment]
My fault.

I didn't know that. Thanks.
