### ISSUE TITLE
gitpod build is failing after merging a PR

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#19103]
I got a message that a [github actions job failed](https://github.com/numpy/numpy/actions/runs/877249695) after merging a PR. Rerunning the job did not clear the error. The error is in the gitpod docker build:
```
buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/bash --login -o pipefail -c conda activate ${CONDA_ENV} &&     python setup.py build_ext --inplace &&     ccache -s]: exit
```

@trallard  thoughts?

**Comment by charris** [comment]
I suspect
```
RUN git clone --depth 1
```

**Comment by charris** [comment]
In particular, the use of `--depth 1`.

**Comment by charris** [comment]
The version needs to be deep enough to reach the tagged commit `v1.22.0.dev0`. I had to fix the clone depth for wheel builds when we started using versioneer. The `--single-branch` option might be useful, although I think it may be the default. I suspect working incorrectly before.

**Comment by charris** [comment]
I would be interesting to see what `FULLVERSION` was before.

**Comment by charris** [comment]
I tested with a local clone and depth=1 did not provide any tags. However
```
git clone --shallow-since=1/1/2021 file:///home/charris/Workspace/numpy.git test-numpy
```
did work and was considerably smaller (10734 vs 179319 objects) than a full clone.
