### ISSUE TITLE
`np.asarray` defaults to `order='K'`, not `'C'`, as docstring suggests

### ISSUE THREAD

**Issue by akukuq** [numpy/numpy#19107]
## Documentation

Docstring for `np.asarray` states that the `order` keyword argument defaults to `'C'`. However, the default behavior corresponds to `'K'`.
This stems directly from the fact that the implementation of `np.asarray` simply passes its arguments to `np.array` whose docstring clearly states that the default `order='K'`.

https://numpy.org/doc/stable/reference/generated/numpy.asarray.html
https://numpy.org/doc/stable/reference/generated/numpy.array.html

I suggest that the current behavior should be preserved - it is likely that users expect `np.asarray` to copy data only if absolutely necessary.

**Comment by BvB93** [comment]
For those interested in tackling the issue: see below for the relevant piece of code.
https://github.com/numpy/numpy/blob/86b9cedb9ac3330ed8c52cebb48f38bfd87298e0/numpy/core/_add_newdocs.py#L907-L927

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue. Please assign me this issue

**Comment by mattip** [comment]
We don't assign issues. When you make a PR to solve this, refer back to here by cross-referencing this issue, something like `fixes #19107` or `closes #19107` or `xref #19107` to indicate you are working on it. See our [developer guide](https://numpy.org/devdocs/dev/development_workflow.html) for more info. You may want to try the [gitpod docker instances](https://numpy.org/devdocs/dev/development_gitpod.html) if you have problems setting up your dev environment.
