### ISSUE TITLE
Use Python 3 CAPI features to cleanup PRINTPYOBJERR

### ISSUE THREAD

**Issue by pearu** [numpy/numpy#19106]
While you're here, we could clean this up using Python 3 CAPI features to
```
   PyErr_SetFormat(#modulename#_error, \"try_pyarr_from_string failed: %R\", obj);
```
but maybe cleaning up all the `PRINTPYOBJERR` calls is best left to another PR

_Originally posted by @eric-wieser in https://github.com/numpy/numpy/pull/18759#discussion_r639681353_

**Comment by HaoZeke** [comment]
Closing for now, there are cleanups which would make sense in the error prints (e.g. I'd like a base exception for all F2PY generated code) but this doesn't seem to be an [actual part of the API](https://docs.python.org/3/c-api/exceptions.html#printing-and-clearing)..
