### ISSUE TITLE
DOC: `howto_build_docs` needs rewrite

### ISSUE THREAD

**Issue by Mukulikaa** [numpy/numpy#19104]
As per the [documentation team meeting](https://hackmd.io/oB_boakvRqKR-_2jRV-Qjg) on 24th May, [Building the NumPy API and reference docs](https://numpy.org/devdocs/docs/howto_build_docs.html) needs to be updated with the following: 

1. Include build guidelines for Windows users; recommend Gitpod and WSL app
2. Explanation for building NumPy before the docs 
3. Remove/modify the submodules section
4. Clarify use of `make latex` and `make dist`

I think points 1 and 2 can be addressed with a dedicated prerequisites section like in [Building from source](https://numpy.org/devdocs/user/building.html#prerequisites).

From the meeting, I gathered that there are no submodules for the docs currently but may re-appear in the future because of mathjax (please correct me if I am wrong). In that case should I remove/comment out the section for the time being? 

I also understood that `make latex` and `make dist` are not usually required for developing the documentation. Should I clarify that they are mostly for release purposes?

cc: @melissawm @rossbar

**Comment by melissawm** [comment]
Hi @Mukulikaa !

> From the meeting, I gathered that there are no submodules for the docs currently but may re-appear in the future because of mathjax (please correct me if I am wrong). In that case should I remove/comment out the section for the time being?

I think this should stay there, see #19036.

> I also understood that make latex and make dist are not usually required for developing the documentation. Should I clarify that they are mostly for release purposes?

That is true for `make dist`, but `make latex` is necessary for PDF output. Not sure how often this is needed these days, but I think it should stay there.

**Comment by Mukulikaa** [comment]
Thank you @melissawm! I'll send in the PR soon.

**Comment by Mukulikaa** [comment]
I was wondering if it would be worth it to write a dedicated doc for WSL setup like the one we have for GitPod.

**Comment by mattip** [comment]
We could use a [tabbed interface](https://sphinx-tabs.readthedocs.io/en/latest/) with directions for
- linux/macOS/WSL, 
- windows, 
- gitpod.

Is there a difference between WSL and linux?

**Comment by Mukulikaa** [comment]
> Is there a difference between WSL and Linux?

Not really. All the Linux commands work in it. I was thinking more along the lines of setting up WSL itself. Though on second thoughts, this [document](https://docs.microsoft.com/en-us/windows/wsl/install-win10) should be enough I guess. 

> We could use a tabbed interface with directions for...

Since instructions for Linux and Gitpod environments are already documented in detail, I think we could aim to include some suggestions for compiler options in the [Building from source doc](https://numpy.org/devdocs/user/building.html) and `make` tool alternatives in the [Building NumPy API and reference docs](https://numpy.org/devdocs/docs/howto_build_docs.html), for Windows users.

**Comment by melissawm** [comment]
> Not really. All the Linux commands work in it. I was thinking more along the lines of setting up WSL itself. Though on second thoughts, this [document](https://docs.microsoft.com/en-us/windows/wsl/install-win10) should be enough I guess.

I think that is definitely the right approach. We don't need to re-write everything, linking to existing docs is perfectly fine.
