### ISSUE TITLE
Different standard deviation values for the same array when cast as different data types

### ISSUE THREAD

**Issue by pearsonkyle** [numpy/numpy#19111]
The code below produces three different outputs for the standard deviation of the same array. I expected these results to be the same or within the precision of their data type. Two out of the three statements below are similar (`int` and `float32`) but `float16` returns inf. Do you know what is going on? 

### Reproducing code example:

```python
import numpy as np
test = np.random.randint(0,1024,(512,512)).astype(np.float16)
print(test.std())
print(test.astype(np.float32).std())
print(test.astype(np.int).std())
```

### Error message:

```
>>> print(test.std())
/Users/kpearson/anaconda3/lib/python3.8/site-packages/numpy/core/_methods.py:183: RuntimeWarning: overflow encountered in reduce
  arrmean = umr_sum(arr, axis, dtype, keepdims=True)
inf
>>> print(test.astype(np.float32).std())
295.61908
>>> print(test.astype(np.int).std())
295.6190704568908
```

### NumPy/Python version information:

1.18.5 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]

**Comment by rkern** [comment]
Part of computing the standard deviation is computing the mean. Part of computing the mean is computing the sum. The sum of your data is out of range to be represented by `float16`.

```
|7> test.sum()                                                                                                                                                                                            
/home/rkern/.edm/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py:38: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
inf
```

You can request that `std()` use a different intermediate precision to do these calculations:

```
|8> test.std(dtype=np.float64)                                                                                                                                                                            
295.54040584932795
```

**Comment by pearsonkyle** [comment]
Thank you!  😊
