### ISSUE TITLE
f2py - arrays above some maximum size segfault when being read from/written to

### ISSUE THREAD

**Issue by keflavich** [numpy/numpy#19112]
f2py appears to have a maximum array size, above which it segfaults.  This is apparently a regression, as I have older versions of f2py (though I can't pinpoint which) that do not reproduce this error.

I haven't bracketed the max size exactly, but (9,999,999) crashes, (1,999,999) doesn't.  I would guess that this is system-dependent and related to available memory, but I'm not sure.

```fortran
      subroutine willsegfault
        implicit none

        real*8 coll(9,999,999)

        coll(1,1,1)=1

        print*,coll(1,1,1)

      end subroutine willsegfault


      subroutine wontsegfault
        implicit none

        real*8 coll(9,10,11)

        coll(1,1,1)=1

        print*,coll(1,1,1)

      end subroutine wontsegfault
```

```shell
f2py -c mwe.f
python -c "import untitled; untitled.wontsegfault(); print('OK'); untitled.willsegfault()"
#    1.0000000000000000
# OK
# Segmentation fault (core dumped)
```

Version info
```shell
$ f2py

Version:     1.20.2
numpy Version: 1.20.2
Requires:    Python 3.5 or higher.
License:     NumPy license (see LICENSE.txt in the NumPy source code)
Copyright 1999 - 2011 Pearu Peterson all rights reserved.
http://cens.ioc.ee/projects/f2py2e/
```

cc @melissawm since you helped me a bit on gitter.

**Comment by melissawm** [comment]
Ok, here's what I found: I've tested this example but only reproduced the segfault with GCC 9.3.0. If I use GCC 10.2.0 I get a warning instead when compiling with f2py:

```
mwe.f:5:30:

    5 |       real*8 coll(9, 999, 999)
      |                              1
Warning: Array ‘coll’ at (1) is larger than limit set by ‘-fmax-stack-var-size=’, moved from stack to static storage. This makes the procedure unsafe when called recursively, or concurrently from multiple threads. Consider using ‘-frecursive’, or increase the ‘-fmax-stack-var-size=’ limit, or change the code to use an ALLOCATABLE array. [-Wsurprising]
```

@keflavich can you confirm which gcc version you are using?

**Comment by keflavich** [comment]
```
$ gcc --version
gcc (crosstool-NG 1.23.0.449-a04d0) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
from anaconda.  In the anaconda channels, there's nothing more recent than 8.2.0.

Do I need to specify a particular version of gcc when using/distributing this code, or is there a fortran workaround?  I don't know much about fortran, but I'll see if I can follow the warning's instructions.

**Comment by keflavich** [comment]
the code I'm trying to `f2py` is f77, which apparently doesn't support allocatable arrays?  Unfortunately, I've verified that the data sizes this code has to work on will generally greatly exceed the empirical upper limit.

**Comment by melissawm** [comment]
I'll try and investigate a bit, thanks for the info!

**Comment by melissawm** [comment]
I don't know yet why this did not raise a warning or error in previous versions of f2py, but maybe the issue was gcc after all. In any case, you can use 

``` 
$ f2py -c mwe.f90 --f22flags="-fno-automatic"
```

([See more info here](https://gcc.gnu.org/onlinedocs/gfortran/Code-Gen-Options.html))

**Comment by keflavich** [comment]
THANKS!  That appears to have fixed it.

... I can't claim to understand what this has done, but that's the usual case for compiler flags.

**Comment by melissawm** [comment]
Closing as resolved - please reopen if you run into more problems.

**Comment by keflavich** [comment]
Thanks. I already have more problems, but I don't know if they're directly related yet.  The code compiles & runs now (no segfault), but the numbers are wrong.  That could be totally unrelated.
