### ISSUE TITLE
cdouble does not take 2 arguments

### ISSUE THREAD

**Issue by hughperman** [numpy/numpy#19125]
cdouble does not take 2 arguments as described in https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.cdouble

Original use case was to use `cdouble(real_values_ndarray, imag_values_ndarray)`

This may be a documentation issue instead of a code issue, if this behavior was not intended to be used.

### Reproducing code example:

```python
import numpy as np
np.cdouble(1,1)
```

### Error message:

TypeError: function takes at most 1 argument (2 given)

### NumPy/Python version information:

1.20.3
3.8.8 (default, Mar 12 2021, 19:49:08) 
[GCC 5.4.0 20160609]

Also tested on various other numpy / python versions, np <1.20.1, 1.15.0, 1.14, 1.17.3> python <3.8.0, 3.7, 3.5, 2.7.12>

**Comment by Dinkarkumar** [comment]
In which file is the cdouble defined ? If anybody knows, please drop the answer. I found several mentions of "cdouble" throughout the codebase but weren't able to find the origin.

**Comment by cubanpit** [comment]
@Dinkarkumar Have you found another clear way to create a numpy complex having two floats for real and imaginary parts?

**Comment by seberg** [comment]
I suspect the clearest work-around may well be to write `np.cdouble(complex(1, 1))`.  This would be nice to get fixed, though.
(That code is a bit messy, probably why it never was.)

**Comment by evinism** [comment]
tuple type of `np.cdouble((1,2))` also seems to work.
