### ISSUE TITLE
Why can't numpy.cross produce correct answer for multi-dimensional arrays?

### ISSUE THREAD

**Issue by iouvxz** [numpy/numpy#19138]
```
import numpy as np

u = np.array([[195, 8, 9]], np.uint8)
v = np.array([250, 166, 68], np.int32)
result1 = np.cross(v, u.astype(np.int32))
result2 = np.cross(v, u)
result3 = np.cross(v, u[0])
print(result1, result2, result3)
```
output is

`[[   950  11010 -30370]] [[182   2  94]] [   950  11010 -30370]`
Why cant np.cross(v,u) produce correct answer, but np.cross(v,u[0]) can ? All results dtypes are numpy.int32

I'm using python 3.9.2 and numpy 1.20.1 .

**Comment by WarrenWeckesser** [comment]
This came up in a question on stackoverflow: ["Why cant't numpy.cross produce correct answer for multi-dimesional array?"](https://stackoverflow.com/questions/67759990/why-cantt-numpy-cross-produce-correct-answer-for-multi-dimesional-array)

The answer to "why" comes down the difference in NumPy's scalar vs array casting rules, e.g.:
```
In [10]: np.int32(3) * np.array([50, 100, 200], dtype=np.uint8)  # Result is uint8
Out[10]: array([150,  44,  88], dtype=uint8)

In [11]: np.array([3], dtype=int32) * np.array([50, 100, 200], dtype=np.uint8)  # Result is int32
Out[11]: array([150, 300, 600], dtype=int32)
```

When one of the arguments to `cross` is 1D, the internal calculations result in `scalar * array` behavior in an intermediate step, even though the output type is based on the types of the array inputs. If both arguments are at least 2D, all the multiplications are `array * array`.

From my comment on the stackoverflow question:

> I would call it a bug--otherwise the user has to know details of the implementation to understand why `np.cross(v, u)` gives the unexpected result while `np.cross([v], u)` gives the expected result. Also, it is a sign that something went wrong when the function returns an array with data type int64 but still does an internal calculation with type uint8.

(On my platform, the default integer type is `int64`; on Windows it will generally be `int32`.)
