### ISSUE TITLE
numpy.linalg.qr installed by pip return NAN in ARM

### ISSUE THREAD

**Issue by KinglittleQ** [numpy/numpy#19133]
numpy.linalg.qr installed by pip does not work in ARM64, but the conda version works well.

Install command:
`pip3 install numpy`

### Reproducing code example:

```python
import numpy as np
rs = np.random.RandomState(10)
x = rs.randn(20, 20)
q, _ = np.linalg.qr(x)

print(np.min(q))
```

### Error message:

```
nan
```

### NumPy/Python version information:

```
1.20.3 3.9.1 (default, Jan 27 2021, 19:17:31)
[GCC 9.3.0]
```

## OS
```
Linux ip-172-28-63-69 5.4.0-1035-aws #37-Ubuntu SMP Wed Jan 6 21:02:01 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by mattip** [comment]
Is this perhaps a graviton2 instance? xref #18422

**Comment by KinglittleQ** [comment]
I think it is related to #18422. Thanks for your reply.
