### ISSUE TITLE
DOC: Merging duplicate array broadcasting docs

### ISSUE THREAD

**Issue by Mukulikaa** [numpy/numpy#19136]
@melissawm pointed out that [Broadcasting](https://numpy.org/devdocs/user/basics.broadcasting.html) and [Array Broadcasting in Numpy](https://numpy.org/devdocs/user/theory.broadcasting.html) contain a lot of duplicate content. [Array Broadcasting in Numpy](https://numpy.org/devdocs/user/theory.broadcasting.html) is also an orphan doc(not in any TOC) and is referenced in only one other place (`Tutorial: Linear algebra on n-dimensional arrays`). 

I think we can merge the unique parts of the orphan doc into the main `Broadcasting` doc. The plan would be to:

- [x] Add Vector quantization section and update internal links
- [x] Add SVGs in `Broadcasting` for examples and Vector quantization section (ref: [Tracking Issue for Graphics](https://github.com/numpy/numpy/issues/18501))
- [x] Add corresponding captions/explanations and alt-text for each figure
- [ ] Remove the orphan doc and corresponding images from the directory

Figures 1 and 5 from [Array Broadcasting in Numpy](https://numpy.org/devdocs/user/theory.broadcasting.html) can be recycled and converted to SVGs, I think (please let me know what you think @MarsBarLee).
Figures 2, 3, 4 seem to be wrong... So I think we can make new graphics for the corresponding examples.

@melissawm please let me know if you have any suggestions/corrections!

**Comment by melissawm** [comment]
Thanks, @Mukulikaa !

I agree that some of the content in the "Array broadcasting in NumPy" can be brought to the main "Broadcasting" page. But some of it definitely reads like a tutorial - might be worth thinking about reformatting that. But this could definitely be a second step once we decide on the basic plan.

One thing to be aware of is potential links to the orphan doc (such as the one found in the SVD Tutorial). Other pages might cite it so we may want to keep some kind of trail to the new doc.

**Comment by MarsBarLee** [comment]
@Mukulikaa If we do go forward with recycling the chosen diagrams, I can certainly convert them!

We can also expand on 'Add corresponding captions/explanations for each figure' to include 'alt-text' ([here are some examples of alt-text for graphs](http://diagramcenter.org/specific-guidelines-g.html#71)). Alt-text is one of the things we're looking at to make the NumPy docs and website more accessible. I have written some guidelines up specifically for NumPy that will be up soon, so once I have that up I can provide more help in that area.

**Comment by Mukulikaa** [comment]
> Alt-text is one of the things we're looking at to make the NumPy docs and website more accessible.

That's a great idea!
