### ISSUE TITLE
Reference instead of copy

### ISSUE THREAD

**Issue by ph4ntome** [numpy/numpy#19150]
In python when you use
a = b[:] 
it copies the values of b to list a
In numpy it creates a reference so updating b values will update a values. This is not in comply with standard python practice.

How to reproduce:
a = np.zeros(10)
a[0]=4
b = a[:]
a[0]=5
b
array([5., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Comment by bashtage** [comment]
This is standard in NumPy and cannot be changed. Slices of arrays create views rather than copies. This is a performance choice, and if you need a copy than you must explicitly use `arr.copy()`

https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html

**Comment by seberg** [comment]
Closing, indeed view semantics are very fundamental to NumPy and explicit copy is necessary occasionally.
