### ISSUE TITLE
f2py - missing c-type option

### ISSUE THREAD

**Issue by 2sn** [numpy/numpy#19159]
## f2py documentation

in 

https://numpy.org/devdocs/f2py/advanced.html

in list of support data types for the `.f2py_f2cmap` file, `long` is not mentioned.  

Although obvious, maybe useful to add for completeness.

**Comment by Dbhasin1** [comment]
I'd like to work on this, is this issue available for taking up?

**Comment by charris** [comment]
Long hasn't been very useful since the time of 16 bit cpus. I'm not clear that it is needed.

**Comment by 2sn** [comment]
If I understand things correctly, it is in the code, the default integer type for Fortran, so, surely, it would be useful.  It is also in the `f2py` code, as default.  it just has been omitted to mention in the doc, maybe because it is too obvious, that's all.  Probably just requires to add some dozen characters to the documentation.

**Comment by charris** [comment]
The problem is that the size of long depends on the platform. This causes a problem with Fortran also, as the default integer type depends on compilation flags. The best approach is to determine the needed size and map it to either int32 (c_int) or int64 (c_longlong).

**Comment by 2sn** [comment]
How would that be done in custom type map, `.f2py_f2cmap` ?

**Comment by HaoZeke** [comment]
Currently `long` is an allowed value for a `.f2py_f2cmap` file, and so the documentation should reflect this. Will track the removal of `long` itself in a different issue.

**Comment by 2sn** [comment]
@HaoZeke thanks for catching up on past issues.
