### ISSUE TITLE
``flatiter``  when big-endian does not update index

### ISSUE THREAD

**Issue by nstarman** [numpy/numpy#19153]
There is a difference in the operations of ``numpy.flatiter`` between little-endian versus big-endian machines. Specifically, the ``.index`` and ``.coords`` attributes update on the ``flatiter`` instances when little-endian, but not when big-endian.

CC: @pllim, @mhvk
See https://github.com/astropy/astropy/issues/11804 and https://github.com/astropy/astropy/pull/11806 for initial bug report and testing of the bug, respectively.

### Reproducing code example:

```python
import numpy as np
x = np.arange(6).reshape(3, 1, 2)
xf = x.flat
endindices = [(xf.index, xf.coords) for _ in xf][-2] # next() oversteps

assert endindices[0] == 5  # should be 5, will be 0 on big-endian
```

**This test will only fail on big-endian machines**

### Error message:

``AssertionError``  The value is 0, not 5.

### NumPy/Python version information:

Platform: Linux-5.4.0-1047-azure-s390x-with-debian-10.9
Numpy : 1.20.3
Python: 3.7.3

**Comment by pllim** [comment]
FWIW, the test log is at https://github.com/astropy/astropy/pull/11806/checks?check_run_id=2722593731 . You can also see in https://github.com/astropy/astropy/blob/main/.github/workflows/ci_cron_weekly.yml how the s390x job is set up.
