### ISSUE TITLE
Could you show me the source code of numpy.arange?

### ISSUE THREAD

**Issue by Vincent0706** [numpy/numpy#19163]
I want to see the source code of numpy.arange to known more about the arange. But I can't find that in the files. Could you show it for me?

**Comment by rkern** [comment]
It's implemented in C.

https://github.com/numpy/numpy/blob/main/numpy/core/src/multiarray/ctors.c#L2944-L3029

We prefer that questions like this be asked on the [numpy-discussion mailing list](https://www.scipy.org/scipylib/mailing-lists.html) and reserve the issue tracker be for bug reports and feature requests. I'm going to close this. If you have followup questions, the mailing list would be the best place.

**Comment by Vincent0706** [comment]
OK, thanks a lot!
