### ISSUE TITLE
Installation Python numpy Library Ubuntu Core

### ISSUE THREAD

**Issue by roeslib** [numpy/numpy#19184]
I am novice working with UBUNTU CORE. What I need is to install numpy library for running a Python script. 

I tried with this lines: 
  -----> sudo snap install numpy
            error: snap "numpy" not found

  ----->sudo snap pip3 install numpy
            error: unknown command "pip3", see 'snap help'

  ----->sudo snap pip install numpy
            error: unknown command "pip", see 'snap help'.

none of them solved my issue. 

Could someone please explain me how to install a Python library in Ubuntu Core? 

Thanks for your help!

**Comment by rossbar** [comment]
Hi @roeslib , your question seems like it would be a better fit for a snap/ubuntu core forum.

That said, assuming you have successfully installed `python` on your system, you should be able to install numpy via pip:
`python -m pip install numpy`
