### ISSUE TITLE
np.testing.allclose doesn't handle uint8 datatype properly

### ISSUE THREAD

**Issue by rggjan** [numpy/numpy#19183]
Running this code:

`np.testing.assert_allclose(np.array([0], dtype=np.uint8), np.array([1], dtype=np.uint8))`

will output:

```
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 255
Max relative difference: 255.
 x: array([0], dtype=uint8)
 y: array([1], dtype=uint8)
```

even though clearly the absolute difference is only 1 instead of 255.

There seems to be an issue with calculating the absolute difference for unsigned types (wrap-around).

Changing the order works fine:

`np.testing.assert_allclose(np.array([1], dtype=np.uint8), np.array([0], dtype=np.uint8))`

```
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 1
Max relative difference: inf
 x: array([1], dtype=uint8)
 y: array([0], dtype=uint8)
```

```python
import numpy as np
<< your code here >>
```

### NumPy/Python version information:

1.18.1 3.7.10 | packaged by conda-forge | (default, Mar 23 2021, 09:14:10)
[Clang 11.1.0 ]

**Comment by rggjan** [comment]
Note: The same example with `float64` works just as expected

`np.testing.assert_allclose(np.array([0], dtype=np.float64), np.array([1], dtype=np.float64))`

```
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 1.
Max relative difference: 1.
 x: array([0.])
 y: array([1.])
```

**Comment by charris** [comment]
`allclose` isn't symmetric, it is "x close to y relative to y".

**Comment by rggjan** [comment]
Yes, that's clear, and this is not the issue. The issue is that numpy says:
"abs(1 - 0)=0"
"abs(0 - 1)=255"

where the first statement is fine, while the second one is clearly wrong...

**Comment by rggjan** [comment]
Or, adding types: 
`abs(uint8(0) - uint8(1))=255`
`abs(float(0) - float(1))=1`

**Comment by rggjan** [comment]
When comparing two `uint8` images, and `numpy` tells you that the "Max absolute difference" is 255 when they only differ by one value (eg one image contains all 0's and one image contains all 1's) that's super confusing...

**Comment by charris** [comment]
The relative difference is 1/0, hence inf. When comparing to zero you should only use `atol`. We may change this going forward.

**Comment by rggjan** [comment]
I'm not talking about the "inf" which is perfectly fine. I'm talking about the "255" which is an issue...

**Comment by mattip** [comment]
Unfortunately `np.uint(0) - np.uint(1)` overflows (with an overflow warning). I am not sure what to do about it. We could theorectically do `if unsigned: np.min(a - b, b - a)` but that seems annoying.

**Comment by charris** [comment]
> abs(uint8(0) - uint8(1))=255

Hmm, that is numerically correct, but I agree it is not working as needed. Overflow is also be a problem with signed integers, and converting to float might not work for 64 bit integers, although it might be good enough.

**Comment by charris** [comment]
> np.min(a - b, b - a)

Doesn't work for signed integers. Try `int8(127)` and `int8(-128)`.

**Comment by mattip** [comment]
right, that is why I put a pseudo-code `if unsigned` in front of the expression, as a short-hand for `if is_unsigned(a) and is_unsigned(b)`

**Comment by BvB93** [comment]
Would [`np.ptp`](https://numpy.org/doc/stable/reference/generated/numpy.ptp.html) potentially offer a solution here? 
It seems to work for unsigned integers out of the box, and for signed integers a negative value is returned in case of overflow, which is easily recognizable for further (potential) fixes.
``` python
In [1]: import numpy as np

In [2]: np.ptp([np.uint8(0), np.uint8(1)])  # <- Insert proper broadcasting
Out[2]: 1

In [3]: np.ptp([np.uint8(1), np.uint8(0)])
Out[3]: 1

In [4]: np.ptp([np.int8(127), np.int8(-128)])
Out[4]: -1

In [5]: np.ptp([np.int8(-128), np.int8(127)])
Out[5]: -1
```

**Comment by WarrenWeckesser** [comment]
There is [`_unsigned_subtract` in histograms.py](https://github.com/WarrenWeckesser/numpy/blob/3ff4924ead45ef6db81778daae08e3c939ea4629/numpy/lib/histograms.py#L337).  That function assumes the first argument is larger, so something like `_unsigned_subtract(max(x, y), min(x, y))` would be needed. E.g.

```
In [16]: x = np.array([10, 1, 44, 93, 125, -120], dtype=np.int8)

In [17]: y = np.array([20, -127, 45, 99, -125, -30], dtype=np.int8)

In [18]: np.abs(x - y)  # Not what we want.
Out[18]: array([  10, -128,    1,    6,    6,   90], dtype=int8)

In [19]: _unsigned_subtract(np.maximum(x, y), np.minimum(x, y))  # Correct absolute differences
Out[19]: array([ 10, 128,   1,   6, 250,  90], dtype=uint8)
```

(Also, FWIW, there is [`ufunclab.peaktopeak`](https://github.com/WarrenWeckesser/ufunclab#peaktopeak).)

**Comment by charris** [comment]
For signed integers, one could use offset binary and treat them as unsigned. Offset binary complements the MSB of two's complement numbers.

**Comment by rggjan** [comment]
> Isn't using `allclose` simply a bad idea for integer types? Perhaps its use should be discouraged here.

Why? Comparing two (uint8 or uint16) images to check if they're similar is a perfect use case for this function, I think. For example, let's say you implement some image processing function and want to write a unit test that the function always produces the same output (for example a gaussian blur). But maybe when optimizing the function, you allow 1 or 2 values absolute difference, since numerical errors and rounding might produce slightly different results.

**Comment by bashtage** [comment]
> Why? Comparing two (uint8 or uint16) images to check if they're similar is a perfect use case for this function, I think. For example, let's say you implement some image processing function and want to write a unit test that the function always produces the same output (for example a gaussian blur). But maybe when optimizing the function, you allow 1 or 2 values absolute difference, since numerical errors and rounding might produce slightly different results.

The strangeness for me comes from the conversion of integers to floats for some of the comparrison but not all (at least if atol and rtol are floats).  If the uints were cast to floats early, then this issue would not occur.  

For the specific case you mention, if everything is (u)integer (including atol and rtol), then you will get an (u)integer comparrison, and it is fairly sensible. This said, I suspect that there are more strange cases out there if atol and rtol are also `uint8` values (like wrapped multiplication, e.g., `np.uint8(32)*np.uint8(32)` which `np.uint8(0)`, although this produces a warning at least)

**Comment by rggjan** [comment]
@bashtage hmm... very good point. Especially `rtol` shold probably always be calculated using floats, as staying in ints for calculating the relative error doesn't make a lot of sense.
Always converting to float64 before doing calculations might be an option, but this is probably not very fast (for large arrays), and would also not work for for uint64 absolute tolerance due to precision loss.

To me, the best option might be converting to some float type only for the rtol calculation, and staying in int types for atol calculations?
