### ISSUE TITLE
Inconsistent results with `np.logical_not` with `where`

### ISSUE THREAD

**Issue by greenstick** [numpy/numpy#19189]
As the title says, I'm getting odd, inconsistent results with `np.logical_not` when using the `where` statement:

```python
>>> a = np.array([1, 0, 0, 1, 0, 1]).astype(bool)
>>> a
array([ True, False, False,  True, False,  True])

>>> b = np.array([1, 0, 0, 0, 1, 0]).astype(bool)
>>> b
array([ True, False, False, False,  True, False])

>>> np.logical_not(a, where = b != True)
array([False,  True,  True, False, False, False])
>>> np.logical_not(a, where = b != True)
array([False,  True,  True, False, False, False])

# Already, the above calls are odd (maybe I'm misunderstanding the implementation) – I would expect the result:
array([True,  True,  True, False, False, False])

>>> np.logical_not(a, where = b == False)
array([False,  True,  True, False, False, False])
>>> np.logical_not(a, where = b == False)
array([False,  True,  True, False, False, False])

# At least this is consistent with the above case, an equivalent Boolean expression. But again, not the expected result. 

# And now, things get weird...
>>> np.logical_not(a, where = b == True)
array([False,  True,  True,  True,  True,  True]) # Not the expected result...
>>> np.logical_not(a, where = b == True)
array([False, False, False, False,  True, False]) # WAT? Why has this same function now evaluated to something completely different?

# Neither of the above results (which are inconsistent with themselves!) are consistent with the expected result:
array([False, False, False, True,  True, True])

# What does an equivalent Boolean expression have to say about it?
>>> np.logical_not(a, where = b != False)
array([False, False, False, False,  True, False])
>>> np.logical_not(a, where = b != False)
array([False, False, False, False,  True, False])

# Well, I guess that's consistent. But again, not what I expected (though maybe I'm not understanding the docs).
```

### Reproducing code example:

```python
import numpy as np

a = np.array([1, 0, 0, 1, 0, 1]).astype(bool)
print(a)

b = np.array([1, 0, 0, 0, 1, 0]).astype(bool)
print(b)

print(np.logical_not(a, where = b != True))
print(np.logical_not(a, where = b != True))

print(np.logical_not(a, where = b == False))
print(np.logical_not(a, where = b == False))

print(np.logical_not(a, where = b == True))
print(np.logical_not(a, where = b == True))

print(np.logical_not(a, where = b != False))
print(np.logical_not(a, where = b != False))

```

### Error message:

No error message is involved.

### NumPy/Python version information:

```
1.20.3 3.9.2 (default, Feb 24 2021, 13:26:09)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by mhvk** [comment]
With `where`, you should also provide an `out` argument: all it does is tell which parts of the *output* array should get the results. If you do not give an explicit `out` argument, a new array is created, which can have random content. See https://numpy.org/devdocs/reference/generated/numpy.ufunc.html

**Comment by greenstick** [comment]
Interesting  – this seems like something that should be clarified in the documentation on `np.logical_not` and I presume other `ufunc`s that accept the `where` keyword. Going to test this, will report back.

**Comment by greenstick** [comment]
It works – solved by passing in the original array `a`. Thanks @mhvk!

```python
>>> import numpy as np
>>>
>>> a = np.array([1, 0, 0, 1, 0, 1]).astype(bool)
>>> print(a)
[ True False False  True False  True]
>>>
>>> b = np.array([1, 0, 0, 0, 1, 0]).astype(bool)
>>> print(b)
[ True False False False  True False]
>>>
>>> print(np.logical_not(a, where = b != True, out = a))
[ True  True  True False False False]
>>> print(np.logical_not(a, where = b != True, out = a))
[ True False False  True False  True]
>>>
>>> print(np.logical_not(a, where = b == False, out = a))
[ True  True  True False False False]
>>> print(np.logical_not(a, where = b == False, out = a))
[ True False False  True False  True]
>>>
>>> print(np.logical_not(a, where = b == True, out = a))
[False False False  True  True  True]
>>> print(np.logical_not(a, where = b == True, out = a))
[ True False False  True False  True]
>>>
>>> print(np.logical_not(a, where = b != False, out = a))
[False False False  True  True  True]
>>> print(np.logical_not(a, where = b != False, out = a))
[ True False False  True False  True]
>>>

# Note – in this case the second function calls should invert the Boolean transform. 
```

**Comment by mhvk** [comment]
p.s.  Regarding documentation, at least on `ipython`, just doing `np.logical_not?`, I get the below. Is there a way to clarify this further?
```
Call signature:  np.logical_not(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'logical_not'>
File:            /usr/lib/python3/dist-packages/numpy/__init__.py
Docstring:      
logical_not(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Compute the truth value of NOT x element-wise.

Parameters
----------
x : array_like
    Logical NOT is applied to the elements of `x`.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.
```

**Comment by greenstick** [comment]
> p.s.  Regarding documentation, at least on `ipython`, just doing `np.logical_not?`, I get the below. Is there a way to clarify this further?
> 
> ```
> 
> Call signature:  np.logical_not(*args, **kwargs)
> 
> Type:            ufunc
> 
> String form:     <ufunc 'logical_not'>
> 
> File:            /usr/lib/python3/dist-packages/numpy/__init__.py
> 
> Docstring:      
> 
> logical_not(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
> 
> 
> 
> Compute the truth value of NOT x element-wise.
> 
> 
> 
> Parameters
> 
> ----------
> 
> x : array_like
> 
>     Logical NOT is applied to the elements of `x`.
> 
> out : ndarray, None, or tuple of ndarray and None, optional
> 
>     A location into which the result is stored. If provided, it must have
> 
>     a shape that the inputs broadcast to. If not provided or None,
> 
>     a freshly-allocated array is returned. A tuple (possible only as a
> 
>     keyword argument) must have length equal to the number of outputs.
> 
> where : array_like, optional
> 
>     This condition is broadcast over the input. At locations where the
> 
>     condition is True, the `out` array will be set to the ufunc result.
> 
>     Elsewhere, the `out` array will retain its original value.
> 
>     Note that if an uninitialized `out` array is created via the default
> 
>     ``out=None``, locations within it where the condition is False will
> 
>     remain uninitialized.
> 
> **kwargs
> 
>     For other keyword-only arguments, see the
> 
>     :ref:`ufunc docs <ufuncs.kwargs>`.
> 
> ```

Lesson learned. This may be a bad habit (given it doesn't account for whether your NumPy library is up to date — though I'm sure I'm not the only one), but my workflow is often to have the API docs open so I can look up methods I don't remember the exact name of. This translates into me going off of the NumPy online docs in 99% of cases.

**Comment by mhvk** [comment]
It is somewhere in the on-line documentation too, but as I had trouble finding it, perhaps no surprise you didn't see it... Anyway, happy that the problem was solved!
