### ISSUE TITLE
DOC: Discussion - How to organize tutorials

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#19191]
## Documentation

Now that https://numpy.org/numpy-tutorials/ is deployed, we need to decide how to organize our internal documentation. 

Currently, [this page](https://numpy.org/devdocs/user/tutorials_index.html) is also called NumPy Tutorials. The two tutorials listed there are also available as Jupyter Notebooks from the [separate numpy-tutorials repo](https://github.com/numpy/numpy-tutorials).

In our docs team meetings, we have discussed two possibilities:

1.  Keeping two sets of tutorials. This would allow us to separate the contents into in-depth guides about NumPy features (in the main sphinx docs) and general tutorials with applications of NumPy in other domains (in the numpy-tutorials repo). In this case, the tutorials section in the main docs would have to be renamed; one suggestion is "NumPy Guides" or similar.
2. Only keeping the numpy-tutorials repo, making the sphinx tutorials page point to the rendered numpy-tutorials site and adding any new content there.

It would be nice to have further input from the community so we can reach a solution. If you have other ideas, please feel free to let us know!

cc @rossbar @rgommers @cooperrc @8bitmp3

**Comment by rgommers** [comment]
I'm in favor of (2). Duplicated content doesn't make sense. Having a clear split between User Guide and `numpy-tutorials` makes sense to me. User Guide focus more on individual NumPy features and how to use them, while Tutorials are more application-focused and teach NumPy usage in the process.

**Comment by MarsBarLee** [comment]
My NumPy [Docs page redesign proposal](https://github.com/numpy/numpy/issues/18419#issuecomment-840078589) would change the main docs/sphinx front page, Getting Started and User Guide page. This redesign would still be useful in both possibilities 1) and 2).

With 2), the main docs/sphinx pages would still act as the first entryway, and even if a user ultimately needs numpy-tutorials, the redesign will help them get there.


This flow could like look like this: Docs front page -> User Guide page -> Tutorials, which would link to numpy-tutorials.

Tutorials could be linked from multiple pages:
Docs front page -> Tutorials
Docs front page -> Getting Started -> Tutorials

**Comment by melissawm** [comment]
PR above has my proposal for now. Once the new landing page is here, we can reorganize if needed. Thanks!
