### ISSUE TITLE
Broadcasting large arrays returns scalar instead of MemoryError

### ISSUE THREAD

**Issue by FirefoxMetzger** [numpy/numpy#19208]
### Reproducing code example:

```python
import numpy as np
size = int(1e7)
foo = np.arange(size)
bar = foo[:, None] == foo[None, :]
assert isinstance(bar, np.ndarray)  # fails type(bar) == bool
```

For small values of `size` the above works as expected. At some point, I briefly encounter a MemoryError, once the result doesn't fit anymore, and beyond that, I simply get a boolean (False) as above.

### Error message:

None. I do get a runtime warning on element-wise comparison though.

```
<ipython-input-2-f77f9b8031fc>:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  bar = foo[:, None] == foo[None, :]
```

### NumPy/Python version information:
1.20.3 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]

First encountered by a user on StackOverflow in this question: https://stackoverflow.com/questions/67882615/fastest-way-to-get-the-minimum-value-of-data-array-in-another-paired-bin-array/

**Comment by FirefoxMetzger** [comment]
@rkern Would you be able to give me some intuition of why this is currently happening? With my current understanding of the library, it happens rather unexpectedly.

**Comment by eric-wieser** [comment]
Some context here:

https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/src/multiarray/arrayobject.c#L1216-L1317

**Comment by eric-wieser** [comment]
If we're not yet ready to conclude that deprecation, we should probably modify it to never silence `MemoryError`.

**Comment by seberg** [comment]
This is fixed.
