### ISSUE TITLE
Numpy.typing mypy plugin error 

### ISSUE THREAD

**Issue by Sednaoui** [numpy/numpy#19215]
I am having trouble adding [numpy_typing](https://numpy.org/devdocs/reference/typing.html#mypy-plugin) to my project to use with mypy. Numpy docs explains that a mypy plugin is distributed with numpy.typing plugin.

### Reproducing code example:

mypy.ini

````
[mypy]
plugins = numpy.typing.mypy_plugin
````

### Error message:
Running mypy, I get this errror: 

`Error importing plugin 'numpy.typing.mypy_plugin': No module named 'numpy.typing`

### NumPy/Python version information:

```
1.19.4 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]
```

**Comment by BvB93** [comment]
Hi @Sednaoui, The mypy plugin will be a new addition in NumPy 1.21.0, while currently you're still using 1.19.4.

**Comment by Sednaoui** [comment]
got it thanks @BvB93! looking forward to it, great job

**Comment by q-wertz** [comment]
With numpy version `1.20.3` I can get it running using the following `mypy.ini` file (non valid .ini syntax)

```ini
import numpy

[mypy]
python_version = 3.9
plugins = numpy.typing.mypy_plugin
warn_return_any = True
warn_unused_configs = True
```

Don't really understand why and also I get the error 
```
mypy.ini: File contains no section headers.
file: 'mypy.ini', line: 1
'import numpy\n'
```

but it seems to work :thinking:

**Comment by ikamensh** [comment]
Same problem: `Error importing plugin 'numpy.typing.mypy_plugin': No module named 'numpy.typing'` with `numpy==1.21.3`.

**Comment by BvB93** [comment]
> Same problem: `Error importing plugin 'numpy.typing.mypy_plugin': No module named 'numpy.typing'` with `numpy==1.21.3`.

If the module cannot be found with numpy >= 1.21 then that would suggest it's grabbing an older numpy installation from somewhere. What does the output of `print(np.__version__)` show?

**Comment by rgommers** [comment]
That may be a different issue. The import works fine for me. So questions:
- Do `import numpy` and `import numpy.typing` work?
- Did you check `numpy.__file__` and `numpy.__version__` to ensure the package is really 1.21.3 (could be a mixup with venv's for example)?
- If so and it's really a bug, it's likely specific to the packaging/install method. How did you install numpy?

**Comment by ikamensh** [comment]
oh, figured it out. So I was in a virtual environment and had correct numpy version as reported (1.21.3), but didn't have mypy in this virtual environment. I had a global mypy installation with `numpy==1.18.5`, which was raising this error.

Advice to earlier me:  check `which mypy` and verify it's the one from your environment.

**Comment by the-matt-morris** [comment]
FWIW I ran into the same situation today when using `pre-commit` and had to add `numpy` as a dependency in my `.pre-commit-config.yaml`:

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies:
          - 'numpy'
```
