### ISSUE TITLE
Errors with type annotations

### ISSUE THREAD

**Issue by peastman** [numpy/numpy#19221]
I'm getting a lot of errors trying to use type annotations with numpy.  Mypy identifies lots of problems in code that is actually completely correct, but the type annotations lead it to think there are errors.  The problems seem to come from two major sources.

1. Functions like `argmin()` and `argmax()` are declared as returning a type that cannot be used as an index.
2. `ArrayLike` is defined in a way that makes Mypy think it cannot be passed to `len()`.

### Reproducing code example 1:

```python
import numpy as np
a = [1, 2, 3]
print(a[np.argmax(a)])
```

### Error message 1:

> test_numpy.py:3: error: No overload variant of "__getitem__" of "list" matches argument type "signedinteger[Any]"
> test_numpy.py:3: note: Possible overload variants:
> test_numpy.py:3: note:     def __getitem__(self, int) -> int
> test_numpy.py:3: note:     def __getitem__(self, slice) -> List[int]

### Reproducing code example 2:

```python
import numpy as np
b: np.typing.ArrayLike = [1, 2, 3]
print(len(b))
```

### Error message 2:

> test_numpy.py:3: error: Argument 1 to "len" has incompatible type "Union[Union[int, float, complex, str, bytes, generic], Sequence[Union[int, float, complex, str, bytes, generic]], Sequence[Sequence[Any]], _SupportsArray]"; expected "Sized"

### NumPy/Python version information:

1.20.3 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ]

**Comment by BvB93** [comment]
Hi @peastman

> Functions like `argmin()` and `argmax()` are declared as returning a type that cannot be used as an index.

Both functions return an instance of [`np.intp`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.intp) in this case, which is a numpy integer-type that does not directly inherit from `builtins.int` (hence the error). The good news here is that the latest mypy 0.902 release contains updated stubs for `list` 
(see https://github.com/python/typeshed/pull/4804), so this false positive should disappear once you update.

> `ArrayLike` is defined in a way that makes `Mypy` think it cannot be passed to `len()`.

This makes perfect sense actually. `ArrayLike` represents all objects that can be coerced into a numpy array.
This includes (nested) sequences, but also various scalar types (_i.e._ 0D array-likes), types that are not guaranteed 
to implement `__len__` .

**Comment by peastman** [comment]
Thanks!  It looks like mypy 0.902 was just released today.  Upgrading fixed the problem.

> ArrayLike represents all objects that can be coerced into a numpy array.

Interesting.  So an `ArrayLike` isn't necessarily "array like" in the sense of being able to treat it like an array (query its size, access its elements, etc.).  I guess if I want that behavior I should specify the type as `Sequence` rather than `ArrayLike`?

**Comment by peastman** [comment]
Thanks!
