### ISSUE TITLE
Modify .any() to return Null if all values are null

### ISSUE THREAD

**Issue by rapatel0** [numpy/numpy#19220]
## Feature

For sparce data it is particuarly helpful to preserve null values when doing reduction operations.  I end up using this (see below) wrapper function to achieve the intended result. Pandas leverages the numpy heavily so i suspect that the change needs to be made in numpy before it will be used downstream. 

```
def any_nan(x):
    if pd.isnull(x).all():
        return pd.NA
    else:
        return x.any(skipna=True)
```

The ask is to add a configuration parameter to `np.any()` that optionally preserves null values when returning the array.  Skip na doesn't seem to have to correct functionality as it will return `false`, if all the values of the array are null. Ideally, with the toggleable parameter, np.any() would return `np.nan` if all values in the array are null

**Comment by rkern** [comment]
This is something that would have to be done in pandas, not numpy. We do not impose "null" semantics onto NaN values. This is the same category of functionality that pandas adds on top of numpy; `skipna` is a pandas thing, not a numpy thing.

**Comment by seberg** [comment]
It is a bit annoying that we return objects at all here (and it was proposed to change it before, the Python builtin `any` does not).

If someone wants to modify anything in NumPy itself, it seems reasonable to expose the `initial=` keyword-only argument of `np.logical_or.reduce` to `np.any` and `arr.any`.  (If that actually helps, but I think it does for `any`.)

**Comment by rapatel0** [comment]
@rkern I didn't realize. I just assumed this would there might be an underlying constraint in numpy. 

Submitted the Feature Request to pandas  [here](https://github.com/pandas-dev/pandas/issues/41967)
