### ISSUE TITLE
np.arange generated an array of wrong length

### ISSUE THREAD

**Issue by geekmm0** [numpy/numpy#19249]
np.arange(begin, begin + n * spacing, spacing) should generate an array [begin, begin + spacing, begin + 2*spacing, ..., begin + (n-1) * spacing].

However in the following example, it generated an array of size (n+1): [begin, begin + spacing, begin + 2*spacing, ..., begin + n * spacing].

An epsilon is needed to generate the expected answer. 
np.arange(begin, begin + n*spacing -  epsilon, spacing) 

### Reproducing code example:

```python
import numpy as np
arr = np.arange(125.8,224.8,3)
print(arr)
epsilon = 1e-6
arr = np.arange(125.8,224.8-epsilon,3)
print(arr)
```

### Error message:

arr = np.arange(125.8,224.8,3)
print(arr)

Out[13]: 
array([125.8, 128.8, 131.8, 134.8, 137.8, 140.8, 143.8, 146.8, 149.8,
       152.8, 155.8, 158.8, 161.8, 164.8, 167.8, 170.8, 173.8, 176.8,
       179.8, 182.8, 185.8, 188.8, 191.8, 194.8, 197.8, 200.8, 203.8,
       206.8, 209.8, 212.8, 215.8, 218.8, 221.8, 224.8])

epsilon = 1e-6
arr = np.arange(125.8,224.8-epsilon,3)
print(arr)

Out[16]: 
array([125.8, 128.8, 131.8, 134.8, 137.8, 140.8, 143.8, 146.8, 149.8,
       152.8, 155.8, 158.8, 161.8, 164.8, 167.8, 170.8, 173.8, 176.8,
       179.8, 182.8, 185.8, 188.8, 191.8, 194.8, 197.8, 200.8, 203.8,
       206.8, 209.8, 212.8, 215.8, 218.8, 221.8])

### NumPy/Python version information:

1.20.2 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)]

**Comment by bashtage** [comment]
This is a known issue and is a limitation of floating point numbers.  If you need to have an exact number of points you can generate the sequence as integers and then convert to floating point, or use `linspace` which will always respect the number of points requested.

**Comment by mattip** [comment]
This comes up so often I am tempted to try a warning when the end condition is within epsilon of the step. Anyhow, please [review the documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange) and suggest how we could make the "When using a non-integer step..." warning more emphatic.

**Comment by melissawm** [comment]
We do have an open PR (#16796) to improve on this documentation - maybe we can merge it now and refine later if necessary.

**Comment by geekmm0** [comment]
The limitation of floating point numbers leads to inconsistent behavior. For example, changing 125.8 to 125.4 and 221.8 to 221.4, the array was of different length. A warning would be helpful.

```
import numpy as np
arr = np.arange(125.4,221.4,3.0)
print(arr)
```

Out[11]: 
array([125.4, 128.4, 131.4, 134.4, 137.4, 140.4, 143.4, 146.4, 149.4,
       152.4, 155.4, 158.4, 161.4, 164.4, 167.4, 170.4, 173.4, 176.4,
       179.4, 182.4, 185.4, 188.4, 191.4, 194.4, 197.4, 200.4, 203.4,
       206.4, 209.4, 212.4, 215.4, 218.4])

**Comment by mattip** [comment]
#16796 was merged, closing this. Please open a new issue if the documentation could still use more tweaks.
