### ISSUE TITLE
Int32 (and Int64) Min Value modulo -1 Causes Python to Crash

### ISSUE THREAD

**Issue by mikeronayne** [numpy/numpy#19246]
Performing the modulo between the minimum value of the dtypes `int32` or `int64` and `-1` causes Python to crash.

NOTE: `np.iinfo(np.int32).min` returns a Python builtin scalar.

The expression will also crash Python if:
- the divisor is a Python builtin scalar and the dividend is the NumPy scalar.
- one of the operands is a NumPy array.

### Reproducing code example:

```python
import numpy as np
np.iinfo(np.int32).min % np.int32(-1)
```

### Error message:

No error message, Python simply crashes.

### NumPy/Python version information:

`1.20.3 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]`

**Comment by charris** [comment]
Works for me on linux with more recent version.
```
In [4]: np.iinfo(np.int32).min % np.int32(-1)                                   
Out[4]: 0

In [5]: numpy.__version__                                                       
Out[5]: '1.21.0.dev0+1752.gef6595517f'
```

**Comment by seberg** [comment]
Hmmm, `int_min / -1` results in an integer overflow.  That might be undefined behaviour, which in turn could crash the interpreter depending on the system (or in this case, maybe leads to a 0, which then crashes)?

If you hardcode the values, GCC warns about undefined behaviour: https://godbolt.org/z/9Mj33545z  And if you select MSV, the compiler actually fails:
```
<source>(9): warning C4427: '%': overflow in constant division, undefined behavior
<source>(9): error C2124: divide or mod by zero
Compiler returned: 2
```
I am surprised nobody ever noticed this before? Did some change make it more likely, or is this just too much of a corner case, since it would only affect `INT_MIN % -1`?

@mikeronayne do you know if this also happens in NumPy 1.19 (or earlier) on your system?

**Comment by seberg** [comment]
Found a windows computer with `MSC v.1912 64 bit (AMD64)` and NumPy 1.18.x.  Seems there is a some chance this might be a regression in 1.20.x?  Unless some other system parameters differ.

**Comment by bashtage** [comment]
Crashes on Windows  1.20.2.

**Comment by seberg** [comment]
Ping @ganesh-k13, do you remember if we had a change in division/modulo that may be causing this?   If that is the case, I wonder if `1.21` might already be fixed.

**Comment by bashtage** [comment]
Crashes on Windows 1.22.0.dev0+177.g75f852edf

**Comment by ganesh-k13** [comment]
Hey @seberg, changes were made to floor divide and modulo was untouched. Unfortunately, as @bashtage mentioned above seems like the build before and after the checkin has the bug, so it was not fixed by that checkin.

**Comment by ganesh-k13** [comment]
If the function below is correct: https://github.com/numpy/numpy/blob/75f852edf94a7293e7982ad516bee314d7187c2d/numpy/core/src/umath/loops.c.src#L794-L799

Then it is missing the MIN and -1 check like:
https://github.com/numpy/numpy/blob/75f852edf94a7293e7982ad516bee314d7187c2d/numpy/core/src/umath/loops.c.src#L876

Could this be the problem?

**Comment by bashtage** [comment]
Python return `0` for ` int(np.iinfo(np.int32).min) % int(-1)`

**Comment by seberg** [comment]
Hmmm, my guess is that this line is the problem: https://github.com/numpy/numpy/blob/75f852edf94a7293e7982ad516bee314d7187c2d/numpy/core/src/umath/loops.c.src#L858

And that `divmod` works just fine here (giving the division by zero warning, which is slightly strange maybe?).

But in that case, it would seem that we changed nothing and it is just system dependent and not actually NumPy version dependent.

**Comment by ganesh-k13** [comment]
I am able to reproduce the crash. Adding a ` || (in1 == NPY_MIN_@TYPE@ && in2 == -1)` is also fixing the issue? Is this the right fix?

**Comment by ganesh-k13** [comment]
@seberg can I raise a PR with this as a fix and some UT?

**Comment by seberg** [comment]
Yeah, that would be great.  Have to think about it a bit, but it seems like the right solution to me.

**Comment by seberg** [comment]
Closing, this issue is fixed in main (and a backport will be made).
