### ISSUE TITLE
BUG: The casting machinery does not check floating point errors.

### ISSUE THREAD

**Issue by andreys42** [numpy/numpy#19248]
## Feature

When intial type of element of numpy array is overflowed there is not exception or warning. This behavior leads to further errors in computations. 
Example :
```

test = np.array([[324212252,1],[324212252,1]])

test = test.astype('float16')

print(test)   #[[inf  1.]
               #[inf  1.]]
```

**Comment by seberg** [comment]
Yeah, the casting machinery never checks CPU floating point flags, right now.  The CPU actually is in charge of noticing this, and does notice it.  But you have to go through some lengths to get NumPy to check for it:
```
In [1]: test = np.array([[324212252,1],[324212252,1]])

In [2]: np.positive(test, signature=(np.float16,)*2)
<ipython-input-2-ac45a9d64b5e>:1: RuntimeWarning: overflow encountered in positive
  np.positive(test, signature=(np.float16,)*2)
Out[2]: 
array([[inf,  1.],
       [inf,  1.]], dtype=float16)
```
The overflow is actually part of the casting (`astype`) here of course, not the `positive`.

**Comment by andreys42** [comment]
It would be awesome to see it "under the hood" in further releases

**Comment by seberg** [comment]
The casting machinery does check for floating-point errors now.
