### ISSUE TITLE
Runtime problems with array printing with development build

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#19255]
When running a development version of NumPy, array printing can cause an infinite loop.

### Reproducing code example:

A minimal reproducer: `python runtests.py --ipython`, then once in the ipython prompt: `a = np.ones(1000); print(a)`

In builds on my system (see below for details), this triggers an infinite loop with 100% single-thread CPU consumption in the python interpreter.

### Additional context

When running with gdb, I see many calls to `count_nonzero` before eventually getting stuck in an infinite loop.

Bisecting identified d20870266 as the problematic commit.

N.B. I've only encountered this with gcc 11.1.0 - I don't see this problem when building with gcc 9.3, at least the one packaged on conda-forge. 

### Version info

1.22.0.dev0+177.g75f852edf 3.9.5 (default, May 24 2021, 12:50:35) 
[GCC 11.1.0]

**Comment by charris** [comment]
What optimization level? gcc 11 won't correctly compile NumPy with `-O3`

**Comment by rossbar** [comment]
> What optimization level? gcc 11 won't correctly compile NumPy with -O3

I don't use any special configuration, so the best answer I can give is: whatever the default build configuration is. Scanning the build log I see mostly `-O1` and `-O3` but again, I didn't manually configure/specify anything. I can attach the build log if that would be useful.

Note also that I am able to build and run the test suite to completion (though there are errors) on 1eb91a332 with gcc 11 --- it is only on d208702 and later that I encounter the infinite loops.

**Comment by melissawm** [comment]
I can confirm all that @rossbar mentioned above. Additionally this prevents building the documentation as it hangs somewhere when building the `numpy.absolute` reference API docs.

**Comment by rossbar** [comment]
@seiko2plus does anything from d208702 jump out to you as potential problem? `count_nonzero_u8` is the last function called (repeatedly) in a gdb session before hitting the hang.

**Comment by seiko2plus** [comment]
@rossbar, It seems a bug on GCC-11 ABI, for somehow the compiler isn't correctly handling(load/store over the stack) the returned SIMD vector. The previous versions of GCC were able to inline the internal loops.
however, we suppose to force inlining any functions that accept or return SIMD registers to avoid being under ABI rules.
#19394 should fixes this issue.

**Comment by charris** [comment]
@rossbar I wasn't able to test this on my old machine, but it looks like a likely fix. Reopen this if the problem persists.

**Comment by rossbar** [comment]
Thanks for the explanation @seiko2plus  - I confirm that #19394 fixes the issue for me.
