### ISSUE TITLE
Inconsistent behaviors in np.full

### ISSUE THREAD

**Issue by ray306** [numpy/numpy#19266]
I need to create the Object-based numpy array but the auto broadcasting sometimes raises an error: 

```python
x = [[1],[2]]
ar = np.full((2,), x, dtype=object)
ar
```

### Error message:
> ValueError: could not broadcast input array from shape (2,1) into shape (2,)

Only if the shapes of the input items are not matched, `np.full` can bypass the inappropriate broadcasting:

```python
x = [[1],[2,2]]
ar = np.full((2,), x, dtype=object)
ar
```

### Output:
> array([list([1]), list([2, 2])], dtype=object)

**Comment by bashtage** [comment]
This is a well known problem when creating object arrays from nested sequences that have array-like dimensions. The workaround is 

```
ar = np.empty(2, dtype=object)
ar[:] = [[1],[2]]
```

**Comment by ray306** [comment]
> This is a well known problem when creating object arrays from nested sequences that have array-like dimensions. The workaround is
> 
> ```
> ar = np.empty(2, dtype=object)
> ar[:] = [[1],[2]]
> ```
> 
> There are other open issues all with similar versions of this.

That works! Thank you a lot!
I am wondering if it is worth introducing a bool/None parameter (perhaps name it "broadcasting") to the array creation methods.

**Comment by mattip** [comment]
Closing. There are other issues open about ragged array creation, please comment there.
