### ISSUE TITLE
Consider changing the default `np.indices` dtype to `np.intp`

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#19274]
The [`np.indices`](https://numpy.org/doc/stable/reference/generated/numpy.indices.html) function returns an array representing the indices of a grid, but despite returning an 
array of indices, its default dtype is based on `np.int_`, rather than `np.intp`. 

Besides being somewhat inconsistent with the practice of returning `np.intp` arrays whenever indices are involved, 
for particularly large arrays this could result in overflow issues on Windows, similar to as what was observed in https://github.com/numpy/numpy/issues/18449.

Note that such a change will effect a number of functions that use `np.indices` under the hood (_e.g._ https://github.com/numpy/numpy/pull/19261#discussion_r652863808).

**Comment by seberg** [comment]
FWIW, it now is the same because we aligned the two.  Could be made explicit (i.e. if we were to change again, this would be nice to audit), but for now it doesn't matter anymore due to gh-24224.
