### ISSUE TITLE
`mgrid` with non-integer slices gives error from mypy

### ISSUE THREAD

**Issue by parhamfh** [numpy/numpy#19282]
As I was trying out `mgrid` according to the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.mgrid.html#numpy.mgrid), I noticed mypy complained about the complex step number. I also used a float as the `stop` value, which does make sense in the context of `mgrid`, and it gave the same error for that too. 

I couldn't see any other issues regarding this but I was unsure of where to post this so apologies if this is the wrong forum.

### Reproducing code example:

mg.py:
```python
import numpy as np

np.mgrid[-1:1:5j]
```

### Error message:

```
＞ mypy .
mg.py:3: error: Slice index must be an integer or None
```

### NumPy/Python version information:

```
1.20.3 3.8.6 (default, Oct  8 2020, 14:06:32)
[Clang 12.0.0 (clang-1200.0.32.2)]
```

mypy: 0.902
MacOS 10.15.7

**Comment by BvB93** [comment]
While this is a valid issue, it is one that can only be fixed upstream in mypy: https://github.com/python/mypy/issues/2410.
Namely, the integer/None requirement is currently hard-coded by mypy for the explicit slice syntax (`:`).

As not even `typing.Any` can be indexed with a non-integer-based `slice`, I don't see anything we 
can do here to fix the issue.
``` python
from typing import Any

obj: Any
obj[0:1j]  # error: Slice index must be an integer or None
```

As for potential ways to deal with the problem? I can think of two option:
* Add a `# type: ignore[misc]` comment.
* Pre-construct the relevant `slice` instance and then pass it to `np.mgrid`: 
  `slc = slice(-1, 1, 5j); np.mgrid[slc]`

**Comment by parhamfh** [comment]
Thank you so much for the quick reply (and sorry about my delayed one!) and the suggested solutions. You are absolutely right, this is on `mypy` so we can close. Ironic that I posted this question after your comment on the mypy issue 😅
