### ISSUE TITLE
[Numpy 1.21.0] typing module breaks when setting TYPE_CHECKING = True

### ISSUE THREAD

**Issue by caenrigen** [numpy/numpy#19296]
Hi! I am having an issue building sphinx docs for other python packages due to the latest changes in numpy (released to pypi an hour ago).

This is an issue that seems to be python version and platform independent.
Started to happen since `numpy` Version: `1.21.0`.

This affects sphinx pipelines that set `typing.TYPE_CHECKING = True` in order to be able to (auto)document type hints in a python repo.

### Steps to reproduce:

```python
import typing
typing.TYPE_CHECKING = True

from numpy import typing  # works on numpy 1.20.3 fails on 1.21.0
```

### Error message:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-aa7e69028c81> in <module>
      2 typing.TYPE_CHECKING = True
      3 
----> 4 from numpy import typing

/usr/local/anaconda3/envs/q38/lib/python3.8/site-packages/numpy/typing/__init__.py in <module>
    351     _ArrayLikeBytes_co,
    352 )
--> 353 from ._generic_alias import (
    354     NDArray as NDArray,
    355     _GenericAlias,

/usr/local/anaconda3/envs/q38/lib/python3.8/site-packages/numpy/typing/_generic_alias.py in <module>
    200 
    201 if TYPE_CHECKING:
--> 202     NDArray = np.ndarray[Any, np.dtype[ScalarType]]
    203 elif sys.version_info >= (3, 9):
    204     _DType = types.GenericAlias(np.dtype, (ScalarType,))

TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

PS Apologies if I did not choose the right label for this issue.

**Comment by BvB93** [comment]
Honestly, I'm surprised this used to work at all, as you're deliberately running code that is not meant to be 
executed during runtime.

How does sphinx usually deal with these types of type-check-only snippets? Since I imagine this can just as 
easily go wrong with other types that aren't generic during runtime (_e.g._ `functools.partial`).

**Comment by caenrigen** [comment]
> Honestly, I'm surprised this used to work at all, as you're deliberately running code that is not meant to be
> executed during runtime.

Indeed we have been luck I guess in the project 

> How does sphinx usually deal with these types of type-check-only snippets? Since I imagine this can just as
> easily go wrong with other types that aren't generic during runtime (_e.g._ `functools.partial`).

I was not specific enough. Sphinx by itself does not set the `TYPE_CHECKING = True`.

This functionality is an option of the sphinx extension that allows the auto-document the type hint annotations.
It is the `set_type_checking_flag` option of the [sphinx-autodoc-typehints](https://pypi.org/project/sphinx-autodoc-typehints/) module.

---

I think i might have a solution to my problem (importing `numpy` or modules that depend on numpy before setting `TYPE_CHECKING = True`. Will test and report back, though I think it would still be good for the code under `if TYPE_CHECKING: ...` to still be valid executable python.

**Comment by caenrigen** [comment]
@BvB93 thank your support and the quick reply!

I just check and found a solution. I leave it up to you guys to close or not this issue.

Cheers!

---

For those that might run into the same issue, my solution:

in your sphinx `conf.py`:
```python
# ...

import lmfit 
# import ... # or other modules that depend on numpy

set_type_checking_flag = True # this will run `typing.TYPE_CHECKING = True`
```

**Comment by BvB93** [comment]
> Will test and report back, though I think it would still be good for the code under `if TYPE_CHECKING: ...` to still be valid executable python.

This is unlikely to happen on the short term though. While I would like to see `ndarray` and `dtype` to be made generic at runtime eventually, this is very much a long term goal. At the very least [PEP 646](https://www.python.org/dev/peps/pep-0646/) will have to be accepted (and implemented) first, so we can properly describe the `ndarray`s shape.

In any case, feel free to access `if TYPE_CHECKING: ...`-embedded content during runtime, but be aware that you should do so at your own risk.
