### ISSUE TITLE
numpy.where result is incorrect in one example, which is very missleading

### ISSUE THREAD

**Issue by lld2006** [numpy/numpy#19304]
https://numpy.org/doc/stable/reference/generated/numpy.where.html
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

8 should be 2

**Comment by rossbar** [comment]
The example is correct, though perhaps difficult to parse. The signature for `where` is:
`np.where(condition, [x, y])`.

When `x` and `y` are provided, this results in the elements being selected from `x` where the condition is True, or `y` where the condition is False.

In this example, we have:
`condition = [[True, False], [True, True]]`
`x = [[1, 2], [3, 4]]` and
`y = [[9, 8], [7, 6]]`.

`np.where` returns elements of `x` where condition is True (at indices [0, 0], [1, 0] and [1, 1]), and the element of `y` at [0, 1], giving `array([[1, 8], [3, 4]])`

**Comment by lld2006** [comment]
read the manual again, and got it. I probably misread the result yesterday. But I tried several times and I cannot reproduce it. Thanks for your time.
