### ISSUE TITLE
DOC: There is no easy way to find the NumPy PDF docs.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#19303]
They are located at `https://numpy.org/doc/`, but there is no visible link to that page.

**Comment by yashasvimisra2798** [comment]
Hey, @rossbar I would like to work on this issue can you please guide me to where exactly shall this link be put up for easy access?

**Comment by rossbar** [comment]
Thanks for your interest @yashasvimisra2798 - off the top of my head I'm not sure what's the best way to handle this. The main sticking point to me is that we don't (AFAIK) host a pdf version of the reference manual or user guide for the development documentation, so any solution would have to take that into account. I'd probably start by trying to modify the doc template with code that toggles showing/hiding links to the appropriate pdf docs hosted on `numpy.org/doc` based on the doc version string, but without having tried this myself I can't promise that this approach is a good one.

**Comment by melissawm** [comment]
I believe the easiest solution would be to add a link under the blurb in the front page, something like

```
Welcome! This is the documentation for NumPy 1.22.0.dev0+421.g89babbd98, last updated Jul 12, 2021. For a PDF version of the documentation, go to https://numpy.org/doc/.
```

**Comment by yashasvimisra2798** [comment]
Thanks @rossbar and @melissawm I'll get working on this :)
