### ISSUE TITLE
isclose accepts bool inputs although the docs state it shouldn't

### ISSUE THREAD

**Issue by pmeier** [numpy/numpy#19309]
## Documentation

The docstring of `numpy.isclose` currently states

https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/numeric.py#L2314

but it happily accepts boolean tensors:

```python
>>> a = np.array([True], dtype=np.bool_)
>>> np.isclose(a, a)
array([ True])
```

**Comment by rossbar** [comment]
This exact issue was discussed in #16835 where the note was introduced - looks like the wording could use a slight update to exclude `bool`. PR welcome!
