### ISSUE TITLE
DOC: Duplicate info on how to build documentation

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#19313]
There is a decent amount of overlap in [documentation subsection of the dev/index page](https://github.com/numpy/numpy/blob/main/doc/source/dev/index.rst#building-docs) and the more detailed [documentation build instructions](https://github.com/numpy/numpy/blob/main/doc/source/docs/howto_build_docs.rst).

There may be an opportunity to reduce duplication here, e.g. by removing most of the details about building docs from dev/index and linking to the `howto_build_docs` article instead.

Pinging @Mukulikaa since you've recently rewritten the latter document.

**Comment by melissawm** [comment]
Good catch! I suggest removing the instructions on how to build docs from the main page and linking to the more complete document... Not that many people are building the docs locally these days, so I would guess that one extra click is not too much of a problem.

**Comment by Mukulikaa** [comment]
Hi! I was wondering if we should keep the three main commands to build the docs i.e., `pip install -r doc_requirements.txt`, `git submodule update --init` and `make html`, on the main page. After that we can link to the expanded document. That way we could maintain the completeness of the main page I guess.

**Comment by rossbar** [comment]
IMO it's best to minimize the amount of duplicate information - for example, if the submodules are removed again in the future, it's best to only have to update one document rather than two. I'd vote to keep it as minimal as possible and link directly to the more detailed document, e.g.

```rst
To build docs, run ``make`` from the ``doc`` directory. ``make help`` lists all targets.
For example, to build the HTML documentation, you can run::

    make html

Additional requirements are necessary to build the development documentation,
please see :doc:`howto_build_docs` for additional details.
```

**Comment by Mukulikaa** [comment]
> if the submodules are removed again in the future, it's best to only have to update one document rather than two.

Yes, that makes sense! I'll send in a PR soon for this :)
