### ISSUE TITLE
[Feature] Rotate a meshgrid

### ISSUE THREAD

**Issue by srkunze** [numpy/numpy#19315]
Many solutions to this are presented on various places such as here: https://stackoverflow.com/questions/29708840/rotate-meshgrid-with-numpy

Wouldn't it be useful to have one single standard solution for rotating a 2D meshgrid?

I guess many projects create their own rotation function.

**Comment by Tewatia5355** [comment]
Sure i will work on this function and would like to make an inbuilt function with appropriate parameters

**Comment by adeak** [comment]
Considering that meshgrids are completely general in `n` dimensions, it seems too specific to me to have a function that works for 2d meshgrids. Why not rotate 3d, 4d and higher grids? The math generalises, and I guess even the API could follow that, but I doubt that this feature would be used too often especially in higher dimensions.

**Comment by Tewatia5355** [comment]
Yes definitely, a generalized function would be better!!, but for that, we need multiple angles of rotations too! I'm confused about how we can tackle that?

**Comment by adeak** [comment]
For a general description you'd probably want to have a vector defining an axis and an angle of rotation around that axis. This works in arbitrary dimensions. Yet another problem, however, is that for your 2d case you actually want to rotate around a perpendicular axis that's along "the third" dimension. In other words, for a 2d mesh you really want a rotation as if your 2d points were embedded in 3d space. And again for a 3d grid you'd usually still want to rotate around a 3d vector. For higher dimensions this becomes again muddy in terms of an API.

**Comment by Tewatia5355** [comment]
So it is like we have to iterate over the vector which has an angle of rotation corresponding to dimensions, and we will rotate the previous 2 ranges of values of dimension, and proceed ahead!
Here the size of the angle of the rotation vector will be 2 less than the number of dimensions we are dealing right? 
I'm sorry if I'm getting a bit wrong, mesh grids are new to me!!!

**Comment by adeak** [comment]
No, what I meant was take an axis (as in "z axis, pointing upward") and rotate your mesh (as in "grid of points in the xy plane") around that axis with a given angle. In 3d you can imagine rotating a cube-shaped grid around, say, a body diagonal as an axis.

But really the point I was trying to make that this is not a feasible feature in my opinion, because the semantics are not clear at all to define in an extensible way, and the utility of the feature would probably not merit its addition to numpy. But I'm not a numpy dev, just sharing my two cents.

**Comment by eric-wieser** [comment]
It feels like the feature you're actually missing here is "construct a rotation matrix" (#17043); actually applying it to the output of `meshgrid` is trivial.

**Comment by Tewatia5355** [comment]
> No, what I meant was take an axis (as in "z axis, pointing upward") and rotate your mesh (as in "grid of points in the xy plane") around that axis with a given angle. In 3d you can imagine rotating a cube-shaped grid around, say, a body diagonal of the cube as an axis.
> 
> But really the point I was trying to make is that this is not a feasible feature in my opinion, because the semantics are not clear at all to define in an extensible way, and the utility of the feature would probably not merit its addition to numpy. But I'm not a numpy dev, just sharing my two cents.

Ohh okay that will make it very complex to implement, there can be different axis around which we can rotate it and all in n dimension. Thanks for clearing out!!

**Comment by Tewatia5355** [comment]
> It feels like the feature you're actually missing here is "construct a rotation matrix" (#17043); actually applying it to the output of `meshgrid` is trivial.

Yeah true, This is more relatable in scipy to implement! Thanks for linking this issue!!

**Comment by srkunze** [comment]
> It feels like the feature you're actually missing here is "construct a rotation matrix" (#17043); actually applying it to the output of meshgrid is trivial.

Errr, guys, sorry for being late to the discussion but I don't get it.

I don't see the triviality:

``` python
import numpy as np
from scipy.spatial.transform import Rotation as R

r = R.from_euler('z', 1)
T_size = slice(2, 30, 1)
P_size = slice(0, 80, 2)
grid = np.mgrid[T_size, P_size]
r.apply(grid)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rotation.pyx", line 1667, in scipy.spatial.transform.rotation.Rotation.apply
ValueError: Expected input of shape (3,) or (P, 3), got (2, 28, 40).
```

**Comment by adeak** [comment]
I wouldn't call it "trivial", but it's easy. `Rotate` expects 3-dimensional vectors, so you have to pad your array with zeros along the first axis to make it 3d, and then transpose and reshape to get a `(P, 3)`-shaped array, then undo these operations in reverse order.

(But for the 2d case I wouldn't even use `Rotation`: the rotation matrix is `[[c, -s], [s, c]]` with the cosine/sine of the rotation angle in there, and you have to apply this 2x2 matrix to the first axis of the `grid`.)

**Comment by srkunze** [comment]
Well, that was why I created this issue in the first place. When you look at the SO entry it's not as "trivial" and "obvious" as it may seem.

And for those among us that "only want rotate" a meshgrid, it takes a lot of time and research to find the best/most efficient/clean way.

**Comment by rkern** [comment]
"Only want to rotate a meshgrid" is a much-too-specific framing for us to add a function specifically for. We'll never add something that only rotates a meshgrid.

It looks like what you actually need is a more convenient way to apply a 2D rotation to a collection of 2D vectors. That could well be in-scope for `scipy.spatial` where we do this for 3D vectors. But probably not in-scope for numpy.

**Comment by srkunze** [comment]
So that's two different things at once.

First, I find it sad that meshgrids are not really considered first-class in numpy although there are multiple ways to create them: `meshgrid`, `mgrid` or `ogrid` even with higher dimensions. In some cases, it feels really awkward to use them because they have the "wrong" shape.
So, too specific might just mean that they simply are not created in a way 100% compatible with the rest of the numpy ecosystem. From my perspective, they aren't anything special.

Second, about the rotation, I think we should discuss this on scipy then, when for whatever reason rotation is out of scope for numpy (whatever the reason here may be).

**Comment by rkern** [comment]
`meshgrid()` is just a function that returns arrays. They indeed aren't anything special. Which is why I'm saying that we're not going to frame functionality in terms of "meshgrids".
