### ISSUE TITLE
Incorrect type annotation for ndarray.real

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#19318]
```python
from typing import Any
import numpy as np
import numpy.typing as npt

decay: npt.NDArray[np.complexfloating[Any, Any]]

reveal_type(decay)  # note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.complexfloating[Any, Any]]]"
reveal_type(decay.real)  # note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.complexfloating[Any, Any]]]"
```
I believe it should be `numpy.ndarray[Any, numpy.dtype[numpy.floating[Any, Any]]]`

**Comment by BvB93** [comment]
> I believe it should be `numpy.ndarray[Any, numpy.dtype[numpy.floating[Any, Any]]]`

Yup, you're completely right.
The issue was recently fixed in https://github.com/numpy/numpy/pull/19286; it should be quite easy to backport.

**Comment by NeilGirdhar** [comment]
Awesome feel free to close this issue whenever it's convenient for you.

Also, I'm really loving the type annotations!!

**Comment by BvB93** [comment]
Closed by https://github.com/numpy/numpy/pull/19324.
