### ISSUE TITLE
Conflict with detecting cpu features

### ISSUE THREAD

**Issue by jhpalmieri** [numpy/numpy#19319]
This is with an iMac Pro, Xeon W processor. If I set `CFLAGS=-march=native`, then `numpy` builds, and the summary information is as follows:

```
########### EXT COMPILER OPTIMIZATION ###########
Platform      : 
  Architecture: x64
  Compiler    : clang

CPU baseline  : 
  Requested   : 'native'
  Enabled     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX
  Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq
  Extra checks: AVX512F_REDUCE AVX512BW_MASK AVX512DQ_MASK

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : AVX512_KNL AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
CCompilerOpt._cache_write[796] : write cache to path -> /Users/jpalmier/Downloads/numpy-1.20.3/build/temp.macosx-10.15-x86_64-3.9/ccompiler_opt_cache_ext.py

########### CLIB COMPILER OPTIMIZATION ###########
Platform      : 
  Architecture: x64
  Compiler    : clang

CPU baseline  : 
  Requested   : 'native'
  Enabled     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX
  Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq
  Extra checks: AVX512F_REDUCE AVX512BW_MASK AVX512DQ_MASK

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : AVX512_KNL AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
CCompilerOpt._cache_write[796] : write cache to path -> /Users/jpalmier/Downloads/numpy-1.20.3/build/temp.macosx-10.15-x86_64-3.9/ccompiler_opt_cache_clib.py
```

It fails to import, though: `python3 -c 'import numpy'` leads to

### Error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jpalmier/.local/lib/python3.9/site-packages/numpy-1.20.3-py3.9-macosx-10.15-x86_64.egg/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/Users/jpalmier/.local/lib/python3.9/site-packages/numpy-1.20.3-py3.9-macosx-10.15-x86_64.egg/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/Users/jpalmier/.local/lib/python3.9/site-packages/numpy-1.20.3-py3.9-macosx-10.15-x86_64.egg/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/jpalmier/.local/lib/python3.9/site-packages/numpy-1.20.3-py3.9-macosx-10.15-x86_64.egg/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
RuntimeError: NumPy was built with baseline optimizations: 
(SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX) but your machine doesn't support:
(AVX512F).
```

The computer actually seems to have `AVX512F` support: `echo | gcc -dM -E - -march=native` prints `#define __AVX512F__ 1`, and `sysctl -a | grep machdep.cpu` prints

```
machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET BMI1 HLE AVX2 FDPEO SMEP BMI2 ERMS INVPCID RTM PQM FPU_CSDS MPX PQE AVX512F AVX512DQ RDSEED ADX SMAP CLFSOPT CLWB IPT AVX512CD AVX512BW AVX512VL MDCLEAR TSXFA IBRS STIBP L1DF SSBD
```

Setting `CFLAGS` to `-march=native` is standard when building SageMath. It can be avoided for `numpy`, but it would be nice to keep it.

### NumPy/Python version information:

This is with version 1.20.3 of numpy, OS X 10.15.7, and

```
% python3 -c 'import sys; print(sys.version)'
3.9.5 (default, May  4 2021, 03:33:11) 
[Clang 12.0.0 (clang-1200.0.32.29)]
```

This machine has various homebrew packages on it, and to build I either have to set `NPY_BLAS_ORDER=''` and `NPY_LAPACK_ORDER=''` or create a site.cfg file containing

```
[openblas]
libraries    = openblas
include_dirs = /usr/local/Cellar/openblas/0.3.15_1/include
library_dirs = /usr/local/Cellar/openblas/0.3.15_1/lib
```

The problem arises either way.

**Comment by dimpase** [comment]
there are many Xeon W chips, perhaps it's a good idea to figure out more details about yours.

**Comment by jhpalmieri** [comment]
> there are many Xeon W chips, perhaps it's a good idea to figure out more details about yours.

I'm happy to provide more information, so please let me know what would be helpful. The short answer is that it's a 2017 iMac Pro with a 3.2 GHz 8-core processor.

**Comment by mattip** [comment]
@seiko2plus any thoughts?

**Comment by dimpase** [comment]
By the way, I think it's a general design bug, that manifests itself here - a very cheap runtime `import ...` test is not carried out when numpy is built.
If it was, it would have been discovered during numpy build.

**Comment by dimpase** [comment]
> I'm happy to provide more information,

Please run in terminal:
```
sysctl -n machdep.cpu.brand_string
```
and report the output. It'd look like `Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz` (this is just an example - on such a machine things are good).

**Comment by seiko2plus** [comment]
@jhpalmieri, @dimpase, please could you verify #19362? because I don't have access to X86/MacOS at the current moment.
This bug had been detected by GO community [#43089](https://github.com/golang/go/issues/43089). On Darwin, threads are created with AVX512 masked off in XCR0 which leads to failling NumPy AVX512 detection. Apple recommends checking AVX512 thread support through commpage/cpu_capabilities64 or via sysctl instead.

**Comment by jhpalmieri** [comment]
> > I'm happy to provide more information,
> 
> Please run in terminal:
> 
> ```
> sysctl -n machdep.cpu.brand_string
> ```
> 
> and report the output. It'd look like `Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz` (this is just an example - on such a machine things are good).

```
% sysctl -n machdep.cpu.brand_string
Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
```

**Comment by jhpalmieri** [comment]
> @jhpalmieri, @dimpase, please could you verify #19362? because I don't have access to X86/MacOS at the current moment.
> This bug had been detected by GO community [#43089](https://github.com/golang/go/issues/43089). On Darwin, threads are created with AVX512 masked off in XCR0 which leads to failling AVX512 detection in NumPy.
> Apple recommends checking AVX512 thread support through commpage/cpu_capabilities64 or via sysctl instead.

I can indeed import NumPy if I build it from that branch, and `AVX512F` is listed in the CPU baseline category in the summary information printed at the end. Are there other things I should check?

**Comment by seiko2plus** [comment]
@jhpalmieri,
> Are there other things I should check?

No, but for extra check, you can run `np.show_config()` and make sure that `AVX512` is listed in the baseline features.

**Comment by dimpase** [comment]
I can't check  #19362 as I lack AVX512 hardware (macOS or not). By the way, I'm surprised that numpy doesn't run a GitHub Actions tests on macOS, it's almost as easy as doing this on Linux.

**Comment by seiko2plus** [comment]
We do have CI worker on macOS, but in order to detect this issue we need a machine with `AVX512` support which isn't available by the CI host/machine, the provided one is usualy MacOS running on VM without even `AVX2` support. Also to be fear the current CPU features test unit only support linux OS.

**Comment by jhpalmieri** [comment]
> @jhpalmieri,
> 
> > Are there other things I should check?
> 
> No, but for extra check, you can run `np.show_config()` and make sure that `AVX512` is listed in the baseline features.

Yes, or at least `AVX512F` is listed:
```
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3,SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX
    found = 
    not found = AVX512_KNL,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

**Comment by seiko2plus** [comment]
@jhpalmieri, Looks fine, thank you a lot.

**Comment by jhpalmieri** [comment]
> By the way, I think it's a general design bug, that manifests itself here - a very cheap runtime `import ...` test is not carried out when numpy is built.
> If it was, it would have been discovered during numpy build.

I think this is a good point: should one of the last phases in building NumPy be to try to import it?
