### ISSUE TITLE
random_double_fill is wrongly defined (I think)

### ISSUE THREAD

**Issue by joemarshall** [numpy/numpy#19312]
In numpy/random/_common.pxd random_double_fill is defined as returning double

`ctypedef double (*random_double_fill)(bitgen_t *state, np.npy_intp count, double* out) nogil`

But in c_distributions.pxd the fill functions are defined as returning void e.g.

`void random_standard_uniform_fill(bitgen_t* bitgen_state, npy_intp cnt, double *out) nogil`

This causes problems on webassembly where return types are checked.

**Comment by rkern** [comment]
I believe you are correct.
