### ISSUE TITLE
Please consider adding abs_square

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#19321]
If you have a complex array, it's often important to produce a real array equal to the squared magnitude: 
```python
def abs_square(x: ComplexArray) -> RealArray:
    return np.square(x.real) + np.square(x.imag)
```
The main benefit is that the right dtype array is returned (as opposed to using `x.conj() * x`), and it's more efficient than `np.square(np.abs(x))`.

**Comment by dlindelof** [comment]
I'm looking for a first issue to contribute to and I'm interested in this one.

Would you object to me calling this function `norm()` instead? That seems to be the convention for the equivalent library in C++ (https://www.cplusplus.com/reference/complex/norm/)

**Comment by NeilGirdhar** [comment]
@dlindelof We should probably wait for the numpy team to decide whether or not to add this, but if they do, then it would be great to have someone volunteer to do the work!

As for the name, `complex_norm` [might be okay](https://math.stackexchange.com/questions/285398/what-is-the-norm-of-a-complex-number), but I don't think `norm` is a good name since it's not a [mathematical norm](https://en.wikipedia.org/wiki/Norm_(mathematics)#Definition).  Also, we wouldn't confusion with `numpy.linalg.norm`.

**Comment by dlindelof** [comment]
Agreed on the possibly confusing name. An alternative name would be [`field_norm`](https://en.wikipedia.org/wiki/Field_norm), which btw is indeed a norm, just not the L2-norm. Also [`abs_square`](http://mathworld.wolfram.com/AbsoluteSquare.html) as per @NeilGirdhar 's original suggestion or `squared_norm` are apparently also used.

**Comment by rkern** [comment]
I would write this in my own code as `abs(z)**2`. I think that's reasonably idiomatic and conforms well to typical math notation. From my measurements, the performance increase is around 2-4x depending on size. I suspect this is not a significant bottleneck in most code. I would likely not expand numpy's API surface just for that performance bump.

It might fit into `scipy.special`, though.

**Comment by mhvk** [comment]
This has been asked many times and indeed is part of a request by me a while ago to try to support complex numbers a bit better (see #13179, which has links to earlier issues as well).

Certainly, much of my own code includes
```
def power(z):
    return z.real**2+z.imag**2
```
I deal with large enough arrays that the factor 4 in time required for doing a `sqrt` only to immediately undo it with a square is definitely painful...

Anyway, I'd really love to have this! I just wish `np.square` already had the right semantics...

**Comment by NeilGirdhar** [comment]
@mhvk Nice issue.  I'll close this in favor of yours, but would you mind changing your description of the corresponding bullet point to be a bit closer to mine?  First of all, it should be called the "norm of a complex number" -- not the "power" or the "square".  And as a result `np.square` would not be logical in my opinion since sometimes you want the square of a complex number.

**Comment by NeilGirdhar** [comment]
@rkern I respect your desire to keep minimize numpy's already huge API.  My true motivation is to have this pushed into numpy so that it ultimately finds its way into JAX where speed is a big deal to me.  As it is, I just use my own function.  Maybe JAX's XLA compiler will eventually learn to optimize the expression you gave.

**Comment by mhvk** [comment]
@NeilGirdhar - OK, renamed to square modulus in #13179 - and certainly too late to change the meaning of `np.square` (though I'd argue that if it had meant square modulus for complex, it would have been fine; a regular square, `z * z`, is much less common; anyway, water under the bridge).

**Comment by NeilGirdhar** [comment]
@mhvk Cheers!  Good luck with your issue, I'll be following it too.
