### ISSUE TITLE
Mask hardness is not well defined

### ISSUE THREAD

**Issue by QuLogic** [numpy/numpy#19331]
## Documentation

In the `MaskedArray` documentation, [handling the mask section](https://numpy.org/doc/stable/reference/maskedarray.baseclass.html#handling-the-mask), there is `harden_mask` and `soften_mask`, with a summary that says "Force the mask to hard|soft":
![image](https://user-images.githubusercontent.com/302469/123337461-409d1d00-d515-11eb-94a3-c1e435edd3f2.png)
So I click on one of those, and it says:
![image](https://user-images.githubusercontent.com/302469/123337553-632f3600-d515-11eb-821b-5d1e1f842ae3.png)
So I click on the `hardmask` property and it says:
![image](https://user-images.githubusercontent.com/302469/123337604-78a46000-d515-11eb-9ede-bd02307f84af.png)

This is all circular and I still have no idea what mask hardness means. There is also the [Masked Array tutorial](https://numpy.org/doc/stable/user/tutorial-ma.html#more-reading) which explicitly states that it does not cover hard vs soft mask and links to the above functions, which of course make no explanation.

**Comment by melissawm** [comment]
There is also a [note here ](https://numpy.org/doc/stable/reference/maskedarray.generic.html#unmasking-an-entry) but I would agree this is probably not sufficient...

**Comment by ForgottenProgramme** [comment]
@melissawm , that note you linked is actually quite helpful. :)
I'd like to open a PR to solve this issue.

**Comment by hmeine** [comment]
I [stumbled over the same problem (see SO post)](https://stackoverflow.com/questions/70611171/what-is-the-difference-between-hard-and-soft-masked-numpy-arrays/70611823#70611823) and was also about to open a PR.  In fact, I found that https://github.com/numpy/numpy/pull/13002/files replaced the attribute documentation with an `:autoattribute:` that is much less helpful, though.

In fact, I would suggest a documentation such as 

> Returns whether the mask is hard (``True``) or soft (``False``). When the mask is hard, masked entries cannot be unmasked by element assignment.

possibly including a link to the note referenced above.

**Comment by Mukulikaa** [comment]
Hi @hmeine, if you want to improve the docstrings for the `hardmask` attribute, you can do it here: https://github.com/numpy/numpy/blob/f4a3e07877eb258f69a7d65d8a3b7e8d96e1aacd/numpy/ma/core.py#L3576-L3579

The other methods and attributes of `numpy.ma` are also defined in the same file (numpy/ma/core.py) AFAIK. If you think they need improvements too, feel free to do so!
