### ISSUE TITLE
generalized mean

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#19341]
[`np.mean`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) computes the arithmetic mean, but there are many other interesting means, e.g, the root mean square, harmonic mean, or the geometric mean. They can all be parametrized with
```math
M_p(x) = \left(\frac{1}{n} \sum_{i=1}^n x_i^p\right)^{1/p}
```
See [Wikipedia on generalized means](https://en.wikipedia.org/wiki/Generalized_mean).

**Comment by bashtage** [comment]
Already available in [`np.linalg.norm`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html).

**Comment by nschloe** [comment]
Yeah, except for the $`1/n`$ term and the fact that the absolte value is taken of all $`x`$. `np.linalg.norm` also doesn't work correctly for  `p=0` and `+-np.inf`.

**Comment by nschloe** [comment]
For future reference, I added a `mean` implementation to [npx](https://github.com/nschloe/npx/blob/main/src/npx/_mean.py) which correctly handles all the cases mentioned above.

**Comment by mattip** [comment]
I will close this as there are alternatives available. @nschloe if you feel `np.linalg.norm` could be improved please open a separate issue.
