### ISSUE TITLE
Potential reference count error for function np.array

### ISSUE THREAD

**Issue by Stardust1225** [numpy/numpy#19358]
I am using a fuzzing testing tool to product abnormal inputs for numpy, and I find that when input True or None to np.array, the reference count would be added 1 after called.

### Reproducing code example:
```
# This code is produced by a fuzzing testing tool.
import sys
import numpy

arg_list = []
arg_list.append(3531)
arg_list.append(True)
arg_list.append(4408.58406918058)
arg_list.append('snjh')
arg_list.append(8563.657940062905)
arg_list.append(False)
arg_list.append(8942.995833939585)
arg_list.append('hrfr')
arg_list.append('hrn[')

# check for refcount
bef_ref = [sys.getrefcount(i) for i in arg_list]
try:
    numpy.array(
        [[arg_list[0], arg_list[1], arg_list[2], arg_list[3]], [arg_list[4], arg_list[5], arg_list[6], arg_list[7]],
         arg_list[8]])
except:
    pass
aft_ref = [sys.getrefcount(i) for i in arg_list]
print(bef_ref)
print(aft_ref)
assert bef_ref == aft_ref
```

### Error message:
```
[5, 769, 5, 5, 5, 883, 5, 5, 5]
[5, 770, 5, 5, 5, 883, 5, 5, 5]
  numpy.array(
Traceback (most recent call last):
    assert bef_ref == aft_ref
AssertionError
```

### NumPy/Python version information:
Numpy 1.21.0rc2

**Comment by seberg** [comment]
You have to expect True/False to fluctuate, they are process wide singletons (same as small integers).  If you want to test with them, repeat the test many times to hopefully stabilize things.
You can potentially avoid those fluctuations, but it will require a lot of care.  I semi-reguarly run the NumPy test suite to leak checkers, such an obvious leak would have been detected.
