### ISSUE TITLE
Potential reference count error in function umath.add.reduce

### ISSUE THREAD

**Issue by Stardust1225** [numpy/numpy#19357]
### Reproducing code example:

```
# This code is produced by a fuzzing testing tool
import sys
import tracemalloc
from numpy.core import umath

arg_list = []
arg_list.append('Test-2')
arg_list.append(1)
arg_list.append('Test-1')
arg_list.append(True)
arg_list.append('keepdims')
arg_list.append(True)

# check for refcount
bef_ref = [sys.getrefcount(i) for i in arg_list]
umath.add.reduce({arg_list[0] : arg_list[1], arg_list[2] : arg_list[3], arg_list[4] : arg_list[5]})
aft_ref = [sys.getrefcount(i) for i in arg_list]
assert bef_ref == aft_ref
```

### Error message:
The reference count for item 'keepdims' is added after calling the function umath.add.reduce

### NumPy/Python version information:
1.21.0rc2。
I am not sure whether this problem remains in version 1.21.0 released 5 days ago.

**Comment by seberg** [comment]
This is intentional, `"keepdims"` is interned/cached during the first call rather than at import time, that is all.  Please repeat calls to test things like this more reliably.
