### ISSUE TITLE
The same program, different versions of Numpy calculation results vary greatly.

### ISSUE THREAD

**Issue by chenjuncheng00** [numpy/numpy#19354]
The same program, on three computers with three versions of numpy calculated different results. Using the same matlab program as the standard, on my computer (Mac os11), python3.7, numpy1.18.0, 1.19.5, and 1.21.0 are all wrong; on another computer (windows10), python3.7, numpy1.18.0 calculate all correct results, 1.19.5 partially correct, 1.21.0 all errors; on the third computer, python3.7, numpy1.19.5 calculate all correct results, other versions are not tested.
The program is a program to achieve three-input three-output generalized predictive control, which requires a large number of matrix calculations. The matlab program results are normal and consistent on different computers, but Numpy is very unstable, and there is a large gap between different versions.
If any developer is concerned about this issue, please contact me at chenjuncheng00@qq.com and I can send you the source program.

**Comment by rkern** [comment]
If it's a linear algebra-heavy program, then its possible that you have optimized different BLAS/LAPACK libraries underneath each of your builds. For many of the linear algebra functions, the way that they are defined has some non-uniqueness, and multiple implementations of the BLAS/LAPACK routines can return different (but all equally valid) results. You'll have to check your code to see if the way that you are testing for correctness is allowing for that non-uniqueness. You don't say what it means for your results to be "correct", "partially correct", and "all errors".

**Comment by chenjuncheng00** [comment]
My code, which implements a 3-input, 3-output generalized predictive control program, involves matrix operations, including matrix transpose, matrix multiplication, matrix addition and subtraction, and matrix inverse. I guess it is possible that the result of the calculation is not unique, but I am not sure how to set up or define this problem. But anyway, the result of Matlab calculation is always correct, but different versions of numpu are considered to have a large difference in the result, what is the principle? What I mean by correct and partially correct is that in my program I need to find three inputs u and three resultant outputs y. The input u is calculated by repeated matrix operations, using the input u of the past moment to find the input u of the current moment, and then the input u of the current moment to find the output y of the current moment, no matter which version of the program in the three computers the output y is correct, the difference lies in the three inputs u The difference lies in the correctness of the three input u. Partially correct means that some of the three input u are correct and some are wrong. All correct means that all three input u are correct. All wrong means that all three input u are wrong. The reference standard for correct or wrong is the matlab program.

**Comment by charris** [comment]
"Predictive" caught my attention, I suspect numerical instability, there are a lot of ways to go wrong that are hard to analyse without data.

**Comment by chenjuncheng00** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        My code, which implements a 3-input, 3-output generalized predictive control program, involves matrix operations, including matrix transpose, matrix multiplication, matrix addition and subtraction, and matrix inverse. I guess it is possible that the result of the calculation is not unique, but I am not sure how to set up or define this problem. But anyway, the result of Matlab calculation is always correct, but different versions of numpu are considered to have a large difference in the result, what is the principle? What I mean by correct and partially correct is that in my program I need to find three inputs u and three resultant outputs y. The input u is calculated by repeated matrix operations, using the input u of the past moment to find the input u of the current moment, and then the input u of the current moment to find the output y of the current moment, no matter which version of the program in the three computers the output y is correct, the difference lies in the three inputs u The difference lies in the correctness of the three input u. Partially correct means that some of the three input u are correct and some are wrong. All correct means that all three input u are correct. All wrong means that all three input u are wrong. The reference standard for correct or wrong is the matlab program.
            
        
    
    
    

    On 06/26/2021 09:26，Robert ***@***.***> wrote： 



If it's a linear algebra-heavy program, then its possible that you have optimized different BLAS/LAPACK libraries underneath each of your builds. For many of the linear algebra functions, the way that they are defined has some non-uniqueness, and multiple implementations of the BLAS/LAPACK routines can return different (but all equally valid) results. You'll have to check your code to see if the way that you are testing for correctness is allowing for that non-uniqueness. You don't say what it means for your results to be "correct", "partially correct", and "all errors".

**Comment by chenjuncheng00** [comment]
> "Predictive" caught my attention, I suspect numerical instability, there are a lot of ways to go wrong that are hard to analyse without data.

The principle of generalized predictive control is to calculate the input u of the current moment using the input u of the past moment, but the key to this problem is that the exact same program, three computers with different Numpy versions calculate different results, but the matlab results are exactly the same, matlab is very stable, but numpy is not stable. Could you tell me if this is caused by the different back-end matrix calculation methods of Numpy and matlab?

**Comment by rkern** [comment]
Possibly, but you are using fairly basic operations that usually don't have the kind of non-uniqueness that I was thinking about. The inverses might be an issue if you have ill-conditioned matrices. Then different BLAS/LAPACK implementations might give you different results. If that's the case, then the MATLAB results may not be any more correct, just that the MATLAB implementations on each of your machines just have the same versions of the accelerated BLAS/LAPACK routines.

I would suggest that you try to reduce your example to the simplest thing that demonstrates the issue. That's a good debugging technique on your own, and necessary if you want to post some code for anyone here to look at. Try logging the condition numbers of the matrices that you are inverting. You should definitely try to avoid explicit inverses and reformulate the algorithm to use `solve()` instead; that is much better behaved. It's not _always_ possible, but it usually is.

**Comment by chenjuncheng00** [comment]
Thank you very much for your reply, the matrix complexity in my arithmetic example is large, I have been using .T for matrix transposition, I will try the solve() method you mentioned. Also, how can I make numpy work under different BLAS/LAPACK, and how can I set it up please? If I still can't solve the problem, I will send the code file to your gmail

**Comment by rkern** [comment]
Transposition is fine; it's only the inverse that you should replace with `solve()` calls, if you can.

The [documentation](https://numpy.org/install/) has some instructions on building numpy with different accelerated BLAS/LAPACK libraries, but I would focus on examining the installations that you currently have. Use `np.show_config()` to see a printout of the information about which of these libraries each installation is linked against.

Please do not email me code offline. I help in public forums like here or the [mailing list](http://www.scipy.org/scipylib/mailing-lists.html). I'm not going to look at your full code. If you get it down to a small, complete, runnable example that demonstrates the difference that you are seeing, then you'll have something that you can post in a Github gist. And you just might have located the source yourself by that process.

**Comment by chenjuncheng00** [comment]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']

**Comment by chenjuncheng00** [comment]
I have tested the results of the Numpy code step by step, the results of the matrix inverse operation is indeed different from matlab, I use numpy.linalg.inv(), I will try the solve() method you said

**Comment by rkern** [comment]
Check the [condition number](https://en.wikipedia.org/wiki/Condition_number) of these matrices using `np.linalg.cond()`. That might tell you how much accuracy you should expect these inverse/solve operations to maintain. Moving to `solve()` helps, but ill-conditioned matrices are still likely to cause numerical instability.

**Comment by chenjuncheng00** [comment]
Thank you very much for your answer. The problem has been solved, I downloaded the numpy version compiled with mkl library from the default source of conda, and the calculation results are right, it seems that other libraries will have problems in the unstable matrix calculation, I remember that matlab uses the mkl library, right?

**Comment by rkern** [comment]
It's not clear to me how you are evaluating whether the calculation is "right". It sounds like you are just comparing to the MATLAB results. If your problem is ill-conditioned, the _problem_ is unstable. Minor changes in the input numbers or in the intermediate arithmetic can cause large effects on the output. Do check the condition numbers of the matrices that you are inverting. I suspect that they are ill-conditioned. If that's the case, then _all_ of these results are just as correct as the MATLAB results.

**Comment by chenjuncheng00** [comment]
I double-checked the calculation results and with numpy(1.20.2)+mkl(2021.2.0), there are still some problems with the calculation results compared to Matlab. My matlab program is identical to the python program, so I just use the python program to compare the calculation results with the matlab program. After I double checked, the result of numpy+mkl matrix inverse operation is exactly the same as matlab, and the result of this inverse operation is always the same in the loop. The calculations that need to be repeated in the loop are matrix multiplication (successive multiplication ) and matrix transposition, which I used np.linalg.multi_dot(), np.dot(), and np.T.

**Comment by rkern** [comment]
When you narrow it down to a minimal complete runnable example that we can look at, we can see if there is an actual correctness issue.

**Comment by bashtage** [comment]
I would recommend trying your program on different version of conda-provided NumPy that all use MKL.  MKL should perform similarly across different OSes as long as they are all AMD64. conda + MKL is probably more comparable to MATLAB when running across different versions and arches.

If you really want to debug it, you should step through the program on different machines until you find the first point where internal values are different. You can then you this point, especially the values that are inputs into the step the produces different outputs, as a simple example that could aid in pinning down the source of the discrepancy.

**Comment by rgommers** [comment]
The questions were answered in a lot of detail (thanks @rkern and @bashtage!), and no more follow-up, so I'll close this.
