### ISSUE TITLE
Add a .clang-format file for pretty printing C code

### ISSUE THREAD

**Issue by charris** [numpy/numpy#19363]
## Feature
It would be useful to have a numpy C style pretty printer, especially for newbies. Clang-format looks like a good
choice that has integrations with git (checks change sets), vim, visual studio, and others. The main work would be
in implementing the style sheet, and there are already examples for [PEP7](https://gist.github.com/pganssle/0e3a5f828b4d07d79447f6ced8e7e4db).

**Comment by bashtage** [comment]
Yes, please!
