### ISSUE TITLE
Floating point precision error in numpy.linalg.eig even for matrices with low index

### ISSUE THREAD

**Issue by 007vedant** [numpy/numpy#19372]
The numpy.linalg.eig method gives floating point precision error when calculating eigenvalues, even for matrices with low index values like 1 or 2.

### Reproducing code example:

```python
import numpy as np

matrix = np.array([[5, -3, 2], [15, -9, 6], [10, -6, 4]])
eigen_vals, eigen_vecs = np.linalg.eig(matrix)
print(eigen_vals)
```

### Error:

```python
[-1.05284738e-07  1.05284741e-07 -4.72372619e-16]
```

The output should be [0, 0, 0] since the matrix is a nilpotent matrix with index = 2, i.e results in zero matrix when multiplied with itself twice. For small index values also the method results in floating point precision errors. 
Performing this with a similar method in Sympy library, we get the correct output of 0 against it's multiplicity i.e 3.

```python
from sympy import Matrix
matrix = Matrix([[5, -3,  2], [15, -9, 6], [10, -6,  4]])
matrix.eigenvals()

```
```python
{0: 3}
```

### NumPy/Python version information:

1.20.3 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]

**Comment by bashtage** [comment]
Same using MKL.  Clearly rank 1.  Gets stranger if you multiple `matirix` by 10.

```
[4.23034422e-14+5.23522739e-07j 4.23034422e-14-5.23522739e-07j 5.60567977e-17+0.00000000e+00j]
```

**Comment by pmli** [comment]
Numerical issues are to be expected when trying to numerically diagonalize a non-diagonalizable matrix (e.g., a nilpotent matrix). Indicators of large errors in the results are the large condition number of the matrix of eigenvectors (see section 7.1.5 in [1]):

```python
>>> np.linalg.cond(eigen_vecs)
250890296.4926859
```

and the large reciprocals of the inner products of the left and right eigenvectors (see section 7.2.2 in [1]):

```python
>>> import scipy.linalg as spla
>>> w, vl, vr = spla.eig(matrix, left=True)
>>> for i in range(3):
...     print(w[i], 1 / np.abs(vl[:, i].conj().dot(vr[:, i])))
... 
(-1.0528473753592244e-07+0j) 109536892.16552238
(1.0528474127162493e-07+0j) 109536881.50886497
(-4.72372619117533e-16+0j) 2.1593039381524903
```

[1] G. H. Golub and C. F. Van Loan, Matrix Computations, 4th edition

**Comment by seberg** [comment]
I am going to close this, the numerical accuracy issues seem the right answer here.  `sympy` is simply the better/right tool if you need the exact answer. (Happy to be corrected, though.)
