### ISSUE TITLE
`os.confstr('CS_GNU_LIBC_VERSION')` unavailable on PyPy

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#19385]
When testing out 1.21 on conda, they hist a problem with the glibc2.12 avx512 bug #19192 on PyPy. See [this comment](https://github.com/conda-forge/numpy-feedstock/pull/237#issuecomment-871217709) The fix for that issue depends on `os.confstr('CS_GNU_LIBC_VERSION')`, which is unavailable in PyPy. I opened [an issue there](https://foss.heptapod.net/pypy/pypy/-/issues/3502). In packaging.tags, they use a ctypes workaround for systems where `os.confstr` does not have that key: https://github.com/pypa/packaging/blob/6b2efc63e3723f7af2d914e656e93cdcc15b6c68/packaging/tags.py#L496. 

I don't know how many other Python versions/implementations are missing the needed support and whether NumPy should bother fixing this or just wait for PyPy to fix it themselves.

**Comment by h-vetinari** [comment]
Fix has landed in PyPy for the next version 7.3.6, and is being carried as a patch (and shipped) by conda-forge already.

**Comment by h-vetinari** [comment]
This issue can now probably be closed?

**Comment by mattip** [comment]
Thanks, closing.
