### ISSUE TITLE
pickling fails on some masked arrays (Trac #1342)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1940]
_Original ticket http://projects.scipy.org/numpy/ticket/1342 on 2009-12-19 by @pierregm, assigned to @pierregm._

The current pickling process fails sometimes

>>> base = ma.array([{'a':1}])
>>> target = cPickle.loads(cPickle.dumps(base))

.../numpy/ma/core.pyc in __setstate__(self, state)
   5408         """
   5409         (_, shp, typ, isf, raw, msk, flv) = state
-> 5410         ndarray.__setstate__(self, (shp, typ, isf, raw))
   5411         self._mask.__setstate__((shp, make_mask_descr(typ), isf, msk))
   5412         self.fill_value = flv

Using 
>>> self._data.tolist(),
instead of
>>> self._data.tostring(cf)
in MaskedArray.__getstate__ solves that particular issue, but breaks the other pickle. 

There's a need for a whole new approach for pickling masked arrays

**Comment by burnpanck** [comment]
And it is still so today!
