### ISSUE TITLE
short-circuit astype if type is already fulfilled

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#19401]
I noticed that `astype` is not a constant-time operation if the requested type is already the dtype of the input array.

![out](https://user-images.githubusercontent.com/181628/124350795-08719a80-dbf7-11eb-828e-05e2b5ab71c5.png)

Code to reproduce:
```python
import numpy as np
import perfplot


def setup(n):
    return np.ones(n, dtype="i4")


def astype_same(a):
    return a.astype("i4")


b = perfplot.bench(
    setup=setup,
    kernels=[astype_same],
    n_range=[2 ** k for k in range(25)],
    xlabel="len(x)",
)
b.show()
```

**Comment by eric-wieser** [comment]
Are you looking for `a.astype("i4", copy=False)`?

**Comment by nschloe** [comment]
Thanks Eric!
