### ISSUE TITLE
`flagsobj` does not live in the main numpy namespace

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#19415]
The `flagsobj` class, instances of which are exposed via [`ndarray.flags`](https://numpy.org/doc/1.20/reference/generated/numpy.ndarray.flags.html), currently claims to be a member of the main `numpy` namespace, a claim that is false.

Considering it's not a public class, I propose to simply change its `__module__` to `np.core.multiarray`.

### Error message:

``` python
In [1]: import numpy

In [2]: ar = numpy.random.rand(10)
   ...: print(type(ar.flags))
numpy.flagsobj

In [3]: getattr(numpy, "flagsobj")
---------------------------------------------------------------------------
AttributeError: module 'numpy' has no attribute 'flagsobj'
```

### NumPy/Python version information:

```
1.22.0.dev0+350.g5a0e044b3
3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:10:34) [MSC v.1916 64 bit (AMD64)]
```

**Comment by seberg** [comment]
That sounds good to me, it really is not a type anyone should need explicitly (but I guess you want for typing).
