### ISSUE TITLE
Different results for numpy.matrix vs numpy.ndarray using numpy.vdot()

### ISSUE THREAD

**Issue by zw340** [numpy/numpy#19438]
### Reproducing code example:

```python
import numpy as np
a = np.matrix([1, 4, 5, 6])
b = np.matrix([4, 1, 2, 2])
np.vdot(a, b)
```
It produces 
```
matrix([[4]])
```
This result is non-sensical. The np.vdot works differently on ndarray and matrix, but in the documentation it only says the input is array_like. It should at least alert the reader that it works differently (or does not work) for np.matrix.

### NumPy/Python version information:
1.16.5 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

**Comment by melissawm** [comment]
From the [`np.vdot` documentation](https://numpy.org/devdocs/reference/generated/numpy.vdot.html):

> Note that vdot handles multidimensional arrays differently than dot: it does not perform a matrix product, but **flattens input arguments to 1-D vectors first**. Consequently, it should only be used for vectors.

As a note, using the [`np.matrix` class is not recommended at this point](https://numpy.org/devdocs/reference/arrays.classes.html#matrix-objects).

**Comment by zw340** [comment]
Not sure how flattening the matrix to vector should give the shown result (I would have assumed that it flattens in the same way as ndarray), but thank you, I will avoid using np.matrix class from now on.

**Comment by seberg** [comment]
> Not sure how flattening the matrix to vector should give the shown result 

It doesn't, this should raise an error. The flattening doesn't actually work (matrices can't really be flattened, but they sometimes pretend they can). And the C-code probably just assumes that it did work out and the result is 1-D and not 2-D. Then it operates on the first (length 1) dimension only, giving you 4.

**Comment by melissawm** [comment]
Yeah not looking at the code I assumed this was a mishandling of dimensions because of the way matrices are defined.
