### ISSUE TITLE
numpy 

### ISSUE THREAD

**Issue by L-JiaHui** [numpy/numpy#19439]
System version  :  centos7
Python version  ：3.7.2
pip3      version  :  18.1
numpy  version  :  1.21.0

An error is reported by referring to Numpy ：
    ![image](https://user-images.githubusercontent.com/63582034/125035901-f2674c80-e0c4-11eb-8d6f-d05b39808c6d.png)

perform ldd -r  /usr/local/python3/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so
![image](https://user-images.githubusercontent.com/63582034/125036028-1dea3700-e0c5-11eb-97e8-6c62865f3395.png)
![image](https://user-images.githubusercontent.com/63582034/125036053-2478ae80-e0c5-11eb-98c7-0cf73566f0f3.png)

What's the reason?

**Comment by bashtage** [comment]
I suspect something is corrupt in your system.  Can you try reinstalling NumPy from pip (and clear the cache to make sure it downloads a new copy).  If this doesn't work, you could also try a vendor provided environment like Anaconda.

**Comment by L-JiaHui** [comment]
Hi,Kevin:
I've tried all kinds of versions of Python and Numpy, and I'm working in a new container with no cache

Here are my installation steps：
![image](https://user-images.githubusercontent.com/63582034/125049050-2184ba80-e0d3-11eb-99d5-b1b055330406.png)
@bashtage

**Comment by bashtage** [comment]
Since you are building Python from source this increases the likelihood that something is wrong with your Python build.  Do you see that same error with both the system-provided Python and with conda-provided python (and conda-provided NumPy)?

**Comment by L-JiaHui** [comment]
I haven't tried Conda yet, but I can use Python3 and NumPy locally, this is a problem on the server, maybe I have a build environment problem

**Comment by seberg** [comment]
@L-JiaHui, I am going to close the issue, since it seems a bit like the Python install is off.  If you are still experiencing problems, and think it is NumPy related, please comment/reopen.
