### ISSUE TITLE
Wrong results in computing eigenvectors

### ISSUE THREAD

**Issue by thmarwa** [numpy/numpy#19448]
The following matrix results in a wrong eigenvector when computed:
```
print (np.linalg.eig(np.mat("2 -1 0; -1 2 -1; 0 -1 2")))
```
which results in the output
```
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  4.05925293e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]
```

The correct values, however, are 
```
v1 = [1, -1.4, 1]
v2 = [-1, 0, 1]
v3 = [1, 1.4, 1]
```
Notice how none of the eigenvectors from the code have all the eigenvector components point up, with the middle one peaking. They are not equivalent wave vectors and there is a very likely bug with the computation.

It's easy to verify, but I put a sample computation link below:
https://www.wolframalpha.com/input/?i=eigenvectors+%7B%7B2%2C-1%2C0%7D%2C+%7B-1%2C2%2C-1%7D%2C+%7B0%2C+-1%2C+2%7D%7D

**Comment by rkern** [comment]
The columns are the eigenvectors, not the rows, [per the documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html). Once read that way, you will see that they are the expected eigenvectors up to the normalization that we do and the (arbitrary) sign.
