### ISSUE TITLE
MAINT: `c.src` file parsing should support utf-8

### ISSUE THREAD

**Issue by gyorokpeter** [numpy/numpy#19454]
I'm just trying "pip install numpy" but it fails with this error.
I have attached the full output of the command.
[output2.txt](https://github.com/numpy/numpy/files/6799731/output2.txt)

**Comment by eric-wieser** [comment]
I think this should probably add `encoding="utf8"`:

https://github.com/numpy/numpy/blob/c07080f12652b2cced2f6ca2cb3e72e085565047/numpy/distutils/conv_template.py#L265

**Comment by rgommers** [comment]
The problem was fixed, and `numpy.distutils` is deprecated so we won't be fixing this. So I'll close this. Thanks all.
