### ISSUE TITLE
Multiplying int array by nans results in unexpected behavior

### ISSUE THREAD

**Issue by vikrapivin** [numpy/numpy#19453]
When you multiply a subset of an int array by np.nan, you get unexpected results.

### Reproducing code example:
```python
import numpy as np
test = np.arange(3)
test[0:1] = np.nan*test[0:1]
print(test)
```

### Error message:
No error message, but you see the following output:

> [-9223372036854775808                    1                    2]

I assume this is incorrect behavior, but maybe I am mistaken. If so, sorry for the false report!

### NumPy/Python version information:

1.21.0 3.9.6 (default, Jun 29 2021, 00:00:00) 
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]

**Comment by bashtage** [comment]
This is because you are forcecasting a float to an integer.  Try

```
import numpy as np
test = np.arange(3.0)
test[0:1] = np.nan*test[0:1]
print(test)
```

```
[nan  1.  2.]
```

Even in your example before you assign it to an integer array, you get

```
 np.nan*test[0:1]
```

```
array([nan])
```

**Comment by vikrapivin** [comment]
I agree that it is a solution to convert to a float array before operations, but if you do something like `np.nan*test`, you will get the implicit conversion to a float of test, which makes sense as np.nan is a float. Shouldn't an operation as the one I highlighted here throw an error or a warning? Or alternatively, convert test to a float type under the hood?

**Comment by seberg** [comment]
> Shouldn't an operation as the one I highlighted here throw an error or a warning?

Yes, it should at least be a warning see gh-19248.  Maybe, it should even be an error (a bit of a question how expensive that would be, I guess)... (This invokes undefined behaviour in C99, the result is not always the smallest possible integer, it is just fairly typical).

**Comment by seberg** [comment]
Going to close this, since there are many related issues open (e.g. the one linked above).
