### ISSUE TITLE
Mypy plugin not loading correctly: failed to identify a `ImportFrom` instance

### ISSUE THREAD

**Issue by b-kamphorst** [numpy/numpy#19465]
`numpy/typing/mypy_plugin.py` raises a `ValueError` when running `mypy` with the numpy plugin.

### Reproducing code example:

Configuration file includes the numpy mypy plugin:
```[cfg]
[mypy]
plugins = numpy.typing.mypy_plugin
```

Issue materializes by running the following command (I use a `venv` virtual environment in Windows):
```bash
python -m mypy ./source
```

### Error message:

```[bash]
(.venv-win) C:\Users\kamphorstb\git\all\secure-learn>python -m mypy ./source/secure_learn
Traceback (most recent call last):
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python39\lib\site-packages\mypy\__main__.py", line 23, in <module>
    console_entry()
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python39\lib\site-packages\mypy\__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy\main.py", line 90, in main
  File "mypy\build.py", line 179, in build
  File "mypy\build.py", line 253, in _build
  File "mypy\build.py", line 2585, in dispatch
  File "mypy\build.py", line 2809, in load_graph
  File "mypy\build.py", line 1875, in __init__
  File "mypy\build.py", line 2112, in compute_dependencies
  File "mypy\plugin.py", line 743, in get_additional_deps
  File "C:\Users\kamphorstb\git\all\secure-learn\.venv-win\lib\site-packages\numpy\typing\mypy_plugin.py", line 120, in get_additional_deps
    i = _index(lst, "numpy.typing._extended_precision")
  File "C:\Users\kamphorstb\git\all\secure-learn\.venv-win\lib\site-packages\numpy\typing\mypy_plugin.py", line 87, in _index
    raise ValueError("Failed to identify a `ImportFrom` instance "
ValueError: Failed to identify a `ImportFrom` instance with the following id: 'numpy.typing._extended_precision'
```

### NumPy/Python version information:

`1.21.0 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]`

**Comment by BvB93** [comment]
Can you show me which mypy version was used here?

**Comment by b-kamphorst** [comment]
Versions:
mypy 0.812 
mypy-extensions 0.4.3

**Comment by b-kamphorst** [comment]
I just updated mypy to version 0.910, but the issue persists.

**Comment by BvB93** [comment]
I have to do some more digging here, as it seems to be non-trivial issue.

Currently I can think of one of two possibilities:
* Mypy is somehow trying to analyze a different (older) `numpy` installation.
* Mypy is failing to parse the content of the main `__init__.pyi` file, hence failing to identify the 
  relevant import statement involving `numpy.typing._extended_precision`.

As I'm not too familair with `venv`, dould you describe how you created this environment?
I've tried to reproduce the error with `conda`, but haven't had an success thus far.

**Comment by BvB93** [comment]
A small update: I've been unable to reproduce the issue even with a virtual environment.

**Comment by BvB93** [comment]
As reproducibility is a bit of an issue here, could you provide some help with the debugging?

Namely, could you follow the instructions below:

1. Navigate to `C:\Users\kamphorstb\git\all\secure-learn\.venv-win\lib\site-packages\numpy\typing\mypy_plugin.py`
2. Insert a `print(file.path)` statement just before the `_index` call on line 120.
https://github.com/numpy/numpy/blob/b235f9e701e14ed6f6f6dcba885f7986a833743f/numpy/typing/mypy_plugin.py#L119-L121

If everything is alright then this _should_ point to the numpy installation inside your virtual environment, 
but I'd very much like to verify this.

**Comment by b-kamphorst** [comment]
@BvB93: Thank you for the efforts, they are well-appreciated.

You seem to have pinpointed the issue. It appears that the plugin works perfectly if I make the virtual environment with 
```[bash]
python -m venv .venv
```
However, it fails if I also include system site packages (I usually do that so that I can leverage global installations of mypy, black, gmpy2, etc.):
```[bash]
python -m venv .venv --system-site-packages
```
In the latter case, the print statement that you requested returns the following path:
```
C:\\Users\\kamphorstb\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy-stubs\\__init__.pyi'
```

It seems clear that the issue only arises in virtualenv and with system site packages enabled. I usually don't experience any issues with my virtual environments and I wonder whether this issue is or is not within numpy's domain of control (e.g. the implementation of these `file.paths`). Any thoughts?

**Comment by BvB93** [comment]
> Any thoughts?

I'm afraid I don't have nothing concrete here. It might be worthwhile to look into the mypy installation though,
as it is mypy which is somehow attempting to analyze the wrong numpy directory.

**Comment by b-kamphorst** [comment]
I'll look into that. I'll close the issue and if I find the solution I'll make sure to share it here.

**Comment by b-kamphorst** [comment]
Found the culprit. Turns out that I also had `data-science-types` installed in the global environment. Mypy was looking into the `numpy-stubs` folder that was created by that library and reached a dead end there.

> In the latter case, the print statement that you requested returns the following path:
> 
> ```
> C:\\Users\\kamphorstb\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy-stubs\\__init__.pyi
> ```
