### ISSUE TITLE
Bug in Numpy in computing CoVariance of a Matrix

### ISSUE THREAD

**Issue by prakashvm** [numpy/numpy#19466]
Hello -

I wish to bring to your kind notice a bug in numpy.

Given any matrix X. While trying to compute the CoVariance matrix of that matrix X, numpy in Python does NOT compute the CoVarianceof the given matrix X.

Instead, numpy comptes the CoVariance of the Transpose of the given matrix X.

This appears to be a bug in numpy.

Please refer to the below website for a given matrix and what the result should be after the computation of it's CoVariance. And I have provided a screenshot of what Python is returning.

https://www.itl.nist.gov/div898/handbook/pmc/section5/pmc541.htm

Please let me know if you have any questions.

Regards,
Prakash

[Bug in Numpy.pdf](https://github.com/numpy/numpy/files/6808319/Bug.in.Numpy.pdf)

**Comment by mattip** [comment]
`np.cov` has a [`rowvar` kwarg](https://numpy.org/doc/stable/reference/generated/numpy.cov.html) that will get you the behaviour you desire.

For future reference, it is pretty easy to show code snippets directly in an issue using three backticks to enclose text-formatted-as-code:
```
>>> import numpy as np
>>> x = np.array([[4,   2,   0.6], 
              [4.2, 2.1, 0.59], 
              [3.9, 2,   0.58],
              [4.3, 2.1, 0.62], 
              [4.1, 2.2, 0.63]])
>>> array([[2.92      , 3.098     , 2.846     , 3.164     , 2.966     ],
       [3.098     , 3.28703333, 3.0199    , 3.3566    , 3.1479    ],
       [2.846     , 3.0199    , 2.7748    , 3.0832    , 2.8933    ],
       [3.164     , 3.3566    , 3.0832    , 3.4288    , 3.2122    ],
       [2.966     , 3.1479    , 2.8933    , 3.2122    , 3.0193    ]])
```

This saves you having to create a PDF and us having to open it. You can also use the "<>" tool on the toolbar to format text if you copy-paste it in.

**Comment by rkern** [comment]
I'm going to close this. This is a matter of convention rather than correctness, both conventions are accessible, and the behavior is documented thoroughly in the docstring.
