### ISSUE TITLE
np.array() error ,return 0 after converting a list

### ISSUE THREAD

**Issue by huangjin520** [numpy/numpy#19474]
When i convert a list to array with np.array, i meet a mistake because the result is 0. First ,I check my list ,it's not none or zero .Second, i test np.array() with list_small, it work normally, as shows in the code.
```python
>>>list_small=[[[1, 2, 3], [], [], []], [[], [], [], []], [[], [], [], []], [[], [], [], []]]
>>>np.array(list_small)
array([[list([1, 2, 3]), list([]), list([]), list([])],
       [list([]), list([]), list([]), list([])],
       [list([]), list([]), list([]), list([])],
       [list([]), list([]), list([]), list([])]], dtype=object)
```
### this is my code and my list:

```python
import numpy as np
my_list= np.load("path")
print(my_list)
my_array= np.array(my_list)
print("my_array:", my_array)
####
[[[],[],[],[],....[0, 0, 1], [0, 0, 1], [0, 1, 1, 1], [0, 1, 1, 1], [0, 1, 1, 1], [0, 1, 1, 1], [0, 1, 1, 1], [1, 3, 1, 1], [1, 3, 1, 1], [1, 3, 1, 1], [1, 3, 1, 1], 
[1, 3, 1, 1], [1, 3, 3, 1, 1, 3], [3, 3, 1, 3], [3, 3, 1, 3], [3, 3, 1, 3], [3, 3, 1, 3], [3, 3, 3, 1, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3],
 [3, 3, 3, 3], [3, 3, 3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 1, 3, 3],...[],[],[],[]]]
my_array: 0
```

### Error message:
my_list comes from  3 dimensions [400,500,0] empty list  by adding elements in special coors. But np.array(my_list) return 0, not ori_value.
![image](https://user-images.githubusercontent.com/68464169/125573429-2c21a268-6efd-4c19-a5b3-b4b7da9bd88e.png)

**Comment by eric-wieser** [comment]
NumPy 1.16.0 is no longer maintained - can you see if the problem persists with the latest version?

**Comment by seberg** [comment]
I am pretty sure we fixed a couple of bugs here since then.  So I am willing to bet this is already fixed.  @huangjin520 it would be awesome if you could check, or make the original list available so others can.

Without further information, there is unfortunately nothing we can do besides recommending trying a newer NumPy version.

Closing the issue, if there is new information, happy to reopen!
