### ISSUE TITLE
numpy.argsort() returns odd results (wrong results)

### ISSUE THREAD

**Issue by ZiqiChai** [numpy/numpy#19471]
### Reproducing code example:

```python
import numpy as np
a=[10,9,8,7,6,5,4,3,2,1,27,0,29,31]
b=np.argsort(a)
print(b)
for i,ind in enumerate(b):
    print(i,a[i],find)
```

### Error message:
this is what I got:
```
[11  9  8  7  6  5  4  3  2  1  0 10 12 13]
0 10 11
1 9 9
2 8 8
3 7 7
4 6 6
5 5 5
6 4 4
7 3 3
8 2 2
9 1 1
10 27 0
11 0 10
12 29 12
13 31 13
```

why `numpy.argsort()` returns such odd res? 
the index for number 27 is 0, which means it's the smallest number in the list.
and the index for 0 is 10, which is obviously wrong as well.

### NumPy/Python version information:

1.19.2 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]

**Comment by rkern** [comment]
[Returns the indices that would sort an array.](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)

The `b[0]` is the index of the smallest number in `a`, i.e. `a[b[0]]`; `b[1]` is the index of the next smallest, etc.. So you want to `print(i, a[ind], ind)`.

**Comment by ZiqiChai** [comment]
> [Returns the indices that would sort an array.](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)
> 
> The `b[0]` is the index of the smallest number in `a`, i.e. `a[b[0]]`; `b[1]` is the index of the next smallest, etc.. So you want to `print(i, a[ind], ind)`.

sorry, the print function is 
`print(i,a[i],ind)`,
which are index for data in a, data in a, and sort index for data in a.
the correct output as I believe should be:

```
0 10 10
1 9 9
2 8 8
3 7 7
4 6 6
5 5 5
6 4 4
7 3 3
8 2 2
9 1 1
10 27 11
11 0 0
12 29 12
13 31 13
```

**Comment by rkern** [comment]
That's what you printed, but that's not related to what `argsort()` is documented to do. Please read the examples. `b[i]` is not related to `a[i]` for the same `i`.

**Comment by rkern** [comment]
To relate it to how our other `arg*()` functions work, `b[0]` is `argmin(a)` and `b[-1]` is `argmax(a)`.

**Comment by ZiqiChai** [comment]
got it
