### ISSUE TITLE
Incorrect result when computing complex numbers

### ISSUE THREAD

**Issue by Davide-sd** [numpy/numpy#19484]
I'm trying to plot the imaginary part of a function. Comparing the results with [wolfram alpha](https://www.wolframalpha.com/input/?i=imag%28sqrt%28-x%29%29), it appears that NumPy has a bug. In the following code example:
* `f2` and `f3` should produce the same result.
* I'm also using SymPy to generate a `mpmath` lambda function, `f1`, which "proves" the point.

### Reproducing code example:

```python
import matplotlib.pyplot as plt
import numpy as np
from sympy import im, sqrt, symbols, lambdify

x = symbols("x")
expr = im(sqrt(-x))
f1 = lambdify([x], expr, modules="mpmath")
f2 = lambda x: (np.real(x)**2 + np.imag(x)**2)**(1/4)*np.sin((1/2)*np.arctan2(-np.imag(x), -np.real(x)))
f3 = lambda x: np.imag(np.sqrt(-x))

xx = np.linspace(-10, 10)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot(xx, [f1(t) for t in xx], label="mpmath")
ax.plot(xx, f2(xx), "o", label="numpy 1")
ax.plot(xx, f3(xx + 0j), label="numpy 2")
plt.legend()
plt.show()
```

### Error message:

![Figure 1(5)](https://user-images.githubusercontent.com/9921777/125819668-daf5ff45-4f00-480e-8dab-bb58dc0af89f.png)

### NumPy/Python version information:

1.21.0

**Comment by Davide-sd** [comment]
Note:

``` python
print(f2(10), f2(10.0))
print(f3(10 + 0j), f3(10.0 + 0j))

# 3.1622776601683795 -3.1622776601683795
# -3.1622776601683795 -3.1622776601683795
```

**Comment by oscarbenjamin** [comment]
This is because of signed zero in floating point:
```python
In [39]: arctan2(-0, -10)
Out[39]: 3.141592653589793

In [40]: arctan2(-0.0, -10)
Out[40]: -3.141592653589793
```
It looks like this is as documented:
https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html

**Comment by rkern** [comment]
You're running into the fact that floating point `0.0` and `-0.0` are distinct and can result in different answers when branch cuts are involved, as they are with `sqrt()` along the negative half of the real number line. `-0.0` is finicky, and you don't always get complete control over when you get it (notably, it's hard to get a -0j when building complex numbers with the semi-literal Python syntax; it's easiest to use `complex(x, -0.0)` to get complete control). In you case, when you pass `10+0j` into `f3()`, you compute `-(10 + 0j)` and do get such a negative 0: `(-10-0j)`.

```
[~]                                                                                               
|34> np.sqrt(complex(-4.0, 0.0))                                                                  
2j

[~]                                                                                               
|35> np.sqrt(complex(-4.0, -0.0))                                                                 
-2j

[~]                                                                                               
|36> import cmath                                                                                 

[~]                                                                                               
|37> cmath.sqrt(complex(-4.0, 0.0))                                                               
2j

[~]                                                                                               
|38> cmath.sqrt(complex(-4.0, -0.0))                                                              
-2j
```

This is [standardized behavior](https://www.iso.org/standard/37994.html) that we thoroughly check. Python also follows this standard. Kahan (as usual) has the [definitive paper on the subject](http://people.freebsd.org/~das/kahan86branch.pdf). `mpmath` [does not currently allow a negative 0](https://mpmath.org/doc/current/technical.html#representation-of-numbers) in its representation of numbers, which is a choice that has other benefits, but does mean that they can't represent these branch cuts.

**Comment by oscarbenjamin** [comment]
Does numpy have an efficient way to flip the sign on negative zeros?

**Comment by asmeurer** [comment]
What do you mean by "flip the sign"? `-x` flips a negative to a positive and vice versa, including for 0. There are the functions [copysign](https://numpy.org/doc/stable/reference/generated/numpy.copysign.html) and [signbit](https://numpy.org/doc/stable/reference/generated/numpy.signbit.html), which can be used to more directly manipulate negative 0.

**Comment by charris** [comment]
@oscarbenjamin Why do you want to flip the sign?

**Comment by oscarbenjamin** [comment]
There is an inconsistency here when using SymPy's `lambdify` function:
```python
In [33]: expr = atan2(-x, -1)

In [34]: expr.subs(x, 0)
Out[34]: π

In [35]: lambdify(x, expr, 'numpy')(0)
Out[35]: 3.141592653589793

In [36]: lambdify(x, expr, 'numpy')(0.0)
Out[36]: -3.141592653589793
```
Generally `lambdify` is supposed to return a function that evaluates to the same value represented by the sympy expression. The code generated by `lambdify` internally is:
```python
In [42]: import inspect

In [43]: print(inspect.getsource(lambdify(x, expr, 'numpy')))
def _lambdifygenerated(x):
    return (arctan2(-x, -1))
```
I'm wondering whether something could be added to that code so that `lambdify` could give the expected result for floating point inputs. It looks like `signbit` could be used
```python
In [55]: a = -np.arange(-2.0, 2.0)

In [56]: a
Out[56]: array([ 2.,  1., -0., -1.])

In [57]: a[np.signbit(a) & (a == 0)] = 0

In [58]: a
Out[58]: array([ 2.,  1.,  0., -1.])
```
but I wonder if there is a better approach. Ideally it wouldn't be necessary for the lambdify function to explicitly coerce the input to an array.

**Comment by rkern** [comment]
There might be room for an `ensure_positive_zeros()` function for such cases. Whether or not sympy will want to use it unconditionally in `lambdify()` to take care of these edge cases is up to sympy. But it can be written to work with scalars, too. I would leave it up to sympy, though.

**Comment by oscarbenjamin** [comment]
An expression form for the operation is:
```python
ensure_positive_zeros = lambda a: a * (1 - 2*np.signbit(a)*(a==0))
```
Perhaps something more efficient is possible: this function takes half as long as `np.arctan2` so using it here would give a 50% slowdown.

I wonder how many other cases there are where this would come up though and I'm unsure about how much of a performance impact it would have.
