### ISSUE TITLE
Shuffle type-hints reject lists

### ISSUE THREAD

**Issue by Olegt0rr** [numpy/numpy#19507]
Shuffle type-hints reject lists

Argument description from [shuffle docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html#numpy-random-shuffle):

> The array, **_LIST_** or mutable sequence to be shuffled.

But it type-hinted as `ndarray or MutableSequence`
Using type hint `ndarray or list or MutableSequence` will fix the problem

### Reproducing code example:

```python
from numpy import random

my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
```

### Error message:

`shuffle()` call is highlighted with message:
```
Expected type 'Union[ndarray, MutableSequence]', got 'List[int]' instead
```

### NumPy/Python version information:
```
1.21.0 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58) 
[Clang 6.0 (clang-600.0.57)]
```

**Comment by BvB93** [comment]
Hi @Olegt0rr,

`shuffle` is currently annotated as taking any array-like object, so it seems you currently have a third-party 
stub package installed that is overriding the numpy-provided annotations.

https://github.com/numpy/numpy/blob/94de9f7007b9264328dfa16dcf60a8c34a2c8ec0/numpy/random/mtrand.pyi#L521

**Comment by Olegt0rr** [comment]
@BvB93, thanks for reply!
It seems my PyCharm didn't use .pyi for numpy and use data from docstring.

It would be nice to update typing in a docstrings too. 
E.g. here: https://github.com/numpy/numpy/blob/main/numpy/random/mtrand.pyx#L4438

**Comment by BvB93** [comment]
The docstring is correct though, and `list` should be valid here as it is a subtype of `MutableSequence`.

In fact, when I construct a test example with an `np.ndarray | MutableSequence` annotation, then passing a list 
behaves as expected (mypy 0.910). Based on this I suspect that there is something funky going on with PyCharm.

``` python
import numpy as np
from typing import MutableSequence

def shuffle(a: np.ndarray | MutableSequence) -> None: ...

my_list = [1, 2, 3, 4, 5]
reveal_type(shuffle(my_list))  # note: Revealed type is "None"
```

**Comment by bashtage** [comment]
There is an issue (you will need to search) where a PyCharm dev described how they use type hints and doc strings.  My recollection is that they need full type hints to use those, and when not available use a crawler they developed.

**Comment by BvB93** [comment]
In any case, this very much sounds like a PyCharm issue.
