### ISSUE TITLE
DOC: Clarify that `np.array` can be 0-dimensional

### ISSUE THREAD

**Issue by gcaria** [numpy/numpy#19504]
## Documentation

From the docstring of `np.array`, its only positional argument is:

> An array, any object exposing the array interface, an object whose __array__ method returns an array, or any (nested) sequence.

From such a description, it is surprising that one can do things like `np.array(1)` (I guess this is done to support 0D arrays).

**Comment by yashasvimisra2798** [comment]
https://numpy.org/doc/stable/reference/generated/numpy.array.html
So adding a line of explanation along with an example here would do?
I can work on that.
