### ISSUE TITLE
DOC: NumPy logo and favicon not loading in devdocs

### ISSUE THREAD

**Issue by Mukulikaa** [numpy/numpy#19509]
I had a look in the developer console and it shows the paths for the images as https://numpy.org/devdocs/_static/_static/favicon/favicon.ico and https://numpy.org/devdocs/_static/_static/numpylogo.svg.

There is an extra `_static` in the paths. I am not sure in which file these paths are defined. If someone can guide me to it, I can look into the issue.

**Comment by manasux** [comment]
I checked the developer console of devdocs. The path mentioned for logo is `_static/_static/numpylogo.svg`, but there is only one _static path inside it, and other than that, the logo image is missing in the whole source code, inside sources of developer console, but after filtering out "logo" in the network section, there is a numpylogo.svg, which is a 404 page svg.

**Comment by Mukulikaa** [comment]
Hi @manasux, the files do exist at `doc/source/_static` and you can see them rendered [here](https://numpy.org/devdocs/_static/numpylogo.svg) and [here](https://numpy.org/devdocs/_static/favicon/favicon.ico). 

I tried commenting out [this line](https://github.com/numpy/numpy/blob/94de9f7007b9264328dfa16dcf60a8c34a2c8ec0/doc/source/conf.py#L176) in `doc/source/conf.py` and it solves the problem. But I'm not sure if it's the right way to do it 🙂.

**Comment by melissawm** [comment]
Thanks for chasing that down, @Mukulikaa - let's talk about this in the docs meeting.

**Comment by melissawm** [comment]
SciPy has solved this in scipy/scipy#14417- we should probably do something similar.

**Comment by melissawm** [comment]
Looks like [dependabot fixed this for us](https://github.com/numpy/numpy/pull/19517) - https://numpy.org/devdocs/ is now showing the logo and favicon again.
