### ISSUE TITLE
Casting `bool_` to `float16` reads internal representation

### ISSUE THREAD

**Issue by toslunar** [numpy/numpy#19514]
Casting `np.bool_` array to `np.float16` reads internal representation.  For example, `np.float16(1) + np.array(42, np.int8).view(bool)` results 43.0.  Other types are fine.
```
>>> {ty: np.dtype(ty).type(1) + np.array(42, np.int8).view(bool) for ty in "?bhilBHILefdgFDGOm"}
{'?': True, 'b': 2, 'h': 2, 'i': 2, 'l': 2, 'B': 2, 'H': 2, 'I': 2, 'L': 2, 'e': 43.0, 'f': 2.0, 'd': 2.0, 'g': 2.0, 'F': (2+0j), 'D': (2+0j), 'G': (2+0j), 'O': 2, 'm': numpy.timedelta64(2)}
```

Values casted from `bool` are not necessarily 0 or 1 in C/C++, but it looks nice for NumPy to fix them for all dtypes.

### Reproducing code example:

```python
import numpy as np
np.testing.assert_equal(np.float16(np.int8([0, 3, -7]).view(bool)), [0, 1, 1])
```

The issue does not seem to apply to `np.bool_` scalars
```
>>> np.float16(np.int8(42).view(bool))
1.0
```
because
```
>>> np.int8(42).view(bool).flags.owndata
True
>>> np.int8(42).view(bool).view(np.int8)
1
```

### Error message:

```
AssertionError:
Arrays are not equal

Mismatched elements: 2 / 3 (66.7%)
Max absolute difference: 248.
Max relative difference: 248.
 x: array([  0.,   3., 249.], dtype=float16)
 y: array([0, 1, 1])
```

### NumPy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.21.0 3.9.6 (default, Jul  5 2021, 10:03:05)
[GCC 7.5.0]
```

**Comment by seberg** [comment]
I expect the logic here needs to be slightly cleaned up, in case anyone wants to take a look:

https://github.com/numpy/numpy/blob/b5de1ceb1f1707d0539446b3d8883f3f8f80cb69/numpy/core/src/multiarray/lowlevel_strided_loops.c.src#L818-L832

**Comment by Bhavay192** [comment]
hey @seberg , Can I solve this issue if this is not yet solved. Thanks

**Comment by seberg** [comment]
I think @yashasvimisra2798 just started looking into a day or two back so probably should give her a chance to finish.  Otherwise, of course though!

**Comment by yashasvimisra2798** [comment]
Yeah @seberg and @Bhavay192 I am working on this and will update soon on this.

**Comment by Bhavay192** [comment]
Hey @seberg, is there any other issue which can be beginner friendly for me to contribute??
