### ISSUE TITLE
Importing `ArrayLike` or `DTypeLike` raises a `NameError` in numpy 1.21.1

### ISSUE THREAD

**Issue by hhtong** [numpy/numpy#19521]
With python 3.7.9, importing `ArrayLike` or `DTypeLike` raises a `NameError` in `numpy==1.21.1`.

I had expected that the `TypeError` raised with `numpy==1.21.0` would have been resolved with this PR : https://github.com/numpy/numpy/pull/19311, but now a `NameError` comes up instead.

### Reproducing code example:

```python
from numpy.typing import ArrayLike, DTypeLike
```

### Error message:
```
>>> from numpy.typing import ArrayLike, DTypeLike
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/htong/env379/lib/python3.7/site-packages/numpy/typing/__init__.py", line 316, in <module>
    from ._dtype_like import (
  File "/Users/htong/env379/lib/python3.7/site-packages/numpy/typing/_dtype_like.py", line 95, in <module>
    class _SupportsDType(Generic[_DType_co]):
NameError: name '_DType_co' is not defined
```

### NumPy/Python version information:
```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.21.1 3.7.9 (default, Jul 16 2021, 10:15:27) 
[Clang 11.0.0 (clang-1100.0.33.16)]
```

**Comment by sourabh69733** [comment]
Try to update your python to `3.8+ or 3.9.1`.

It is not throwing an error in `3.9.1`. 
[
![numpy_error_image](https://user-images.githubusercontent.com/65488467/126487379-f97856bf-2028-4c74-aee1-6e1a0fba0993.png)
](url)

**Comment by sourabh69733** [comment]
[Check here the documentation reference for the previous version of python](https://github.com/numpy/numpy/blob/c07080f12652b2cced2f6ca2cb3e72e085565047/numpy/typing/__init__.py#L11)

**Comment by BvB93** [comment]
The condition for trigger the exception is as following:
* Python 3.7 is used.
* typing-extensions is not installed.

I'm currently working a fix for the issue. Annoyingly enough the relevant code paths have proven difficult to test, 
as typing-extensions is an (indirect) dependency of pytest. https://github.com/numpy/numpy/pull/19525 should help with this though.

**Comment by BvB93** [comment]
Closed by https://github.com/numpy/numpy/pull/19533.
