### ISSUE TITLE
PyCapsule_Import could not import module "datetime"

### ISSUE THREAD

**Issue by TarunSehgal27** [numpy/numpy#19528]
Python installed from python.org
numpy installed using pip
operating system windows10

**Comment by mattip** [comment]
Please copy-paste the complete text of the error, along with the versions of python and numpy you are using.

**Comment by TarunSehgal27** [comment]
Traceback (most recent call last):
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TARUN\PycharmProjects\Python_Project\lottery_simulation.py", line 2, in <module>
    import matplotlib. pyplot as plt
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\matplotlib\cbook\__init__.py", line 28, in <module>
    import numpy as np
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Program Files\Python39\python.exe"
  * The NumPy version is: "1.21.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"


Process finished with exit code 1

Python version 3.9.2
numpy version 1.21.1

**Comment by bashtage** [comment]
```
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
```

this is the key error.  You should reinstall NumPy.  

Can you open a console and run `import numpy as np`?

**Comment by mattip** [comment]
> numpy is working on python IDLE but not in Pycharm

It may be an issue with the way you set up PyCharm to run Python. Note your python is at `C:\Program Files\Python39\python.exe`, so normally NumPy would be installed in C:\Program Files\Python39\site-packages` but you are using NumPy from `C:\Users\TARUN\AppData\Roaming\Python\Python39`

**Comment by TarunSehgal27** [comment]
Yes, numpy run in console but not in Pycharm.
 I uninstall numpy then reinstall it in the C:\Program Files\Python39\Lib\site-packages. But the problem remains intact.

"C:\Program Files\Python39\python.exe" C:/Users/TARUN/PycharmProjects/Python_Project/lottery_simulation.py
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Program Files\Python39\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Program Files\Python39\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TARUN\PycharmProjects\Python_Project\lottery_simulation.py", line 2, in <module>
    import matplotlib. pyplot as plt
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\TARUN\AppData\Roaming\Python\Python39\site-packages\matplotlib\cbook\__init__.py", line 28, in <module>
    import numpy as np
  File "C:\Program Files\Python39\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\Program Files\Python39\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Program Files\Python39\python.exe"
  * The NumPy version is: "1.21.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"


Process finished with exit code 1

**Comment by bashtage** [comment]
I would strongly suggest you install Anaconda and use conda to manage packages.  Unless you ahve develped a lot of expertise in Windows python using python.org, you will be must more productive using Anaconda and conda.

**Comment by sourabh69733** [comment]
`Yes, numpy run in console but not in Pycharm.
I uninstall numpy then reinstall it in the C:\Program Files\Python39\Lib\site-packages. But the problem remains intact.
`
try set to your pycharm path also to your `C:\Program Files`.

**Comment by seberg** [comment]
As Matti also mentioned, and our website linked in the error (almost) links to, you should probably double check that the PyCharm settings make sense and use the correct Python, see the PyCharm help: https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html

The other thought would be to check your `PYTHONPATH`, etc. as we note here: https://numpy.org/devdocs/user/troubleshooting-importerror.html#check-environment-variables to make sure it does not point to a second/different installation.

**Comment by TarunSehgal27** [comment]
> `Yes, numpy run in console but not in Pycharm. I uninstall numpy then reinstall it in the C:\Program Files\Python39\Lib\site-packages. But the problem remains intact. `
> 
> Try to set your Pycharm path also to your `C:\Program Files`.
> 
> The most likely cause of your issues is your Pycharm installation and path conflicts.

Pycharm path is C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.3
Do you want me to change the path of my Python_project. It is installed in C:\Users\TARUN\PycharmProjects\Python_Project.
Should  I change to C:\Program Files

**Comment by sourabh69733** [comment]
> C:\Users\TARUN\PycharmProjects\Python_Project.

Have you tried this?

You have probably python path conflict with pycharm. Did you try reinstallation of pycharm?

If you have created your project with virtualenv, then it could be dependency issues, try to run numpy from your project without creating virtualenv.

**Comment by TarunSehgal27** [comment]
I have tried all the ways. Now I'm trying to do it in Anaconda and Spyder IDE. But now it's showing an error.
Traceback (most recent call last):

  File "C:\Program Files\Python39\Lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray

  File "C:\Program Files\Python39\Lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides

  File "C:\Program Files\Python39\Lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\TARUN\.spyder-py3\temp.py", line 2, in <module>
    import numpy

  File "C:\Program Files\Python39\Lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core

  File "C:\Program Files\Python39\Lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\Anaconda\python.exe"
  * The NumPy version is: "1.21.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

Please fix this.

**Comment by bashtage** [comment]
You need to uninstall all versions of Python other than Anaconda. You are having path conflicts.

**Comment by TarunSehgal27** [comment]
I have uninstalled all versions of Python but no change in output. I cannot understand the problem. Please help with path conflicts.

**Comment by bashtage** [comment]
Does C:\Program Files\Python39\Lib\site-packages\numpy\core_init_.py exist? If so, then there is a python installed that is not Anaconda. If not, can you post the most recent error?

**Comment by TarunSehgal27** [comment]
C:\Program Files\Python39\Lib\site-packages\numpy\__init__.py is present. Does core___init__.py is same as __init__.py. Should I delete Python39 folder from C:\ drive

**Comment by mattip** [comment]
Do you have someone who can help you through installing and setting up your system in real-time? This problem is not really NumPy specific and our issue tracker is not really meant for this kind of support. I appreciate that this must be very frustrating, but it seems we are not making progress via this discussion. Something like the [python discord group](discord.gg/python) or the [python slack community](https://pyslackers.com/web/slack) may be able to help you get going.

**Comment by bashtage** [comment]
I agree with @mattip, but you clearly have Python.org python installed.  You should check again in add remove for anything related to Python and uninstall _except_ Anaconda.  Then if you still have C:\Program Files\Python39, just manually delete this entire directory.

**Comment by seberg** [comment]
Going to close this, since it is a setup issue unrelated to NumPy and also more than half a year inactive now.  I hope you managed to figure it out!
