### ISSUE TITLE
DOC: add mentions of linalg accelerators in the documentation of dot and matmul

### ISSUE THREAD

**Issue by LeeeLiu** [numpy/numpy#19530]
I find that  numpy  dot  operation (matrix multiplication )  is implemented  in C.
But,   numpy  dot   is  still  faster than for loops in C. 
Why???

**Comment by bashtage** [comment]
NumPy generally leverages hand-written kernels written that use SIMD. These are provided by other projects.  If you install using pip, it uses [OpenBLAS](https://en.wikipedia.org/wiki/OpenBLAS).  If you install using conda, it defaults to [Intel's Math Kernel Library (MKL)](https://en.wikipedia.org/wiki/Math_Kernel_Library).  The only way you end up with C-like performance is if you build NumPy from source and do not link to an optimized BLAS library.

**Comment by mattip** [comment]
The use of accelerated linear algebra libraries is described in the [linalg](https://numpy.org/devdocs/reference/routines.linalg.html) documentation. The [dot](https://numpy.org/devdocs/reference/generated/numpy.dot.html?highlight=numpy%20dot#numpy.dot) and [matmul](https://numpy.org/devdocs/reference/generated/numpy.matmul.html) documentation could mention that they can use the linalg routines when applicable. I changed the issue title to indicate this.

PR welcome to enhance the documentation with one sentence and to add a link to linalg would be nice.

**Comment by matthew-brett** [comment]
Only to add that the BLAS libraries that we use are very very highly optimized by using all sorts of tricks to improve performance, and in particular, they work very hard to optimize memory access, so the algorithm can do much of the calculation with values in the CPU cache.  When testing  these algorithms, the authors use metrics like comparing speed to the theoretical optimum, such as the raw total CPU time the component float multiplications and additions would take if there was no memory access overhad, and you are using the most efficient CPU instructions.

**Comment by matthew-brett** [comment]
You'll see some discussion in https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms
