### ISSUE TITLE
DOC: duplicate docstrings in numpy/core/_add_newdocs.py and numpy/core/multiarray.py

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#19531]
## Documentation

When we transistioned to `__array_function__` we ended up with at least one duplicate docstring: in both [numpy/core/_add_newdocs.py](https://github.com/numpy/numpy/blob/v1.21.1/numpy/core/_add_newdocs.py#L3201) and [numpy/core/multiarray.py](https://github.com/numpy/numpy/blob/df6d2600c51502e1877aac563658d0616a75c5e5/numpy/core/multiarray.py#L737) there is a docstring for `dot`. It would be nice to go through and remove this and any other duplicates, I think the ones in `_add_newdocs.py` should be removed.

**Comment by DaveOkpare** [comment]
take

**Comment by henryeleonu** [comment]
I can take up this issue

**Comment by rossbar** [comment]
NumPy typically doesn't assign issues --- if there is no PR linked to this issue, it is safe to assume that no one is working on it so you can feel free to take it up.

**Comment by DaveOkpare** [comment]
Thanks @rossbar
