### ISSUE TITLE
bytes() doesn't respect as_strided() under PyPy

### ISSUE THREAD

**Issue by oconnor663** [numpy/numpy#19536]
Here's a test script:

```python
import numpy
unstrided = numpy.array([1, 2, 3, 4], numpy.uint8)
strided = numpy.lib.stride_tricks.as_strided(unstrided, shape=[2], strides=[2])
print(strided)
print(list(strided))
print(bytes(strided))
```

I'm using Arch Linux and the current version of Numpy from PyPI (1.21.1). Under CPython 3.9.6, that script prints the following (**correct**):

```
[1 3]
[1, 3]
b'\x01\x03'
```

However, under PyPy 7.3.5 it prints (**incorrect**):

```
[1 3]
[1, 3]
b'\x01\x02'  <-- BUG
```

In this case `list(strided)` correctly respects the stride, but `bytes(strided)` doesn't.

**Comment by eric-wieser** [comment]
What does `bytes(memoryview(strided))` give?

**Comment by oconnor663** [comment]
Thanks for the lightning fast response. If I expand the script to this:

```python
import numpy
unstrided = numpy.array([1, 2, 3, 4], numpy.uint8)
strided = numpy.lib.stride_tricks.as_strided(unstrided, shape=[2], strides=[2])
print(strided)
print(list(strided))
print(bytes(strided))
print(memoryview(unstrided))
print(memoryview(strided))
```

Then I see this under CPython:

```
[1 3]
[1, 3]
b'\x01\x03'
<memory at 0x7f90313b3700>
<memory at 0x7f90313b3700>
```

And this under PyPy:

```
❯ python test.py
[1 3]
[1, 3]
b'\x01\x02'
<memory at 0x00005648abb87610>
<memory at 0x00005648abb87640>
```

Looks like the memoryview addresses are the same in the first case but slightly different in the second case. Anything else I can add to the printout?

**Comment by eric-wieser** [comment]
That address isn't interesting, it's just telling you the location of the memoryview object, not the memory it points to.

Can you show `bytes(memoryview(strided))` in your output as I asked? I want to check if there's something special about converting directly between an array and bytes, or if the problem persists if you go through an intermediate memoryview.

This function might help get more info about the memoryview:
```python
import inspect
def memory_view_fields(m):
    return [v for v in inspect.getmembers(m) if not callable(v[1]) and not v[0].startswith('__')]
```
then you can `print(memory_view_fields(memoryview(strided)))` too

**Comment by oconnor663** [comment]
Oof silly mistake on my part. I now have:

```python
import numpy
import inspect
def memory_view_fields(m):
    return [v for v in inspect.getmembers(m) if not callable(v[1]) and not v[0].startswith('__')]
unstrided = numpy.array([1, 2, 3, 4], numpy.uint8)
strided = numpy.lib.stride_tricks.as_strided(unstrided, shape=[2], strides=[2])
print(strided)
print(list(strided))
print(bytes(strided))
print(bytes(memoryview(strided)))
print(memory_view_fields(memoryview(strided)))
```

Under CPython:

```
[1 3]
[1, 3]
b'\x01\x03'
b'\x01\x03'
[('c_contiguous', False), ('contiguous', False), ('f_contiguous', False), ('format', 'B'), ('itemsize', 1), ('nbytes', 2), ('ndim', 1), ('obj', array([1, 3], dtype=uint8)), ('readonly', False), ('shape', (2,)), ('strides', (2,)), ('suboffsets', ())]
```

And under PyPy:

```
[1 3]
[1, 3]
b'\x01\x02'
b'\x01\x02'
[('c_contiguous', False), ('contiguous', False), ('f_contiguous', False), ('format', 'B'), ('itemsize', 1), ('nbytes', 2), ('ndim', 1), ('obj', array([1, 3], dtype=uint8)), ('readonly', False), ('shape', (2,)), ('strides', (2,)), ('suboffsets', ())]
```

**Comment by eric-wieser** [comment]
It looks to me like the problem is PyPy's implementation of `bytes(m)` when `m` is a strided memoryview then

**Comment by oconnor663** [comment]
Ok cool, I'll file a bug there. Do you know of any way to create a strided memoryview without using NumPy?

**Comment by oconnor663** [comment]
Filed https://foss.heptapod.net/pypy/pypy/-/issues/3520.
