### ISSUE TITLE
Adding POWER10 (VSX4) support to the SIMD framework

### ISSUE THREAD

**Issue by nicholaiTukanov** [numpy/numpy#19537]
I would like to understand how to go about extending the SIMD framework in order to add support for POWER10. Specifically, I would like to add the following instructions: `lxvp` and `stxvp` which loads/stores 256 bits into/from two vectors. I believe that this will be able to give a decent performance boost for those on POWER machines since it can half the amount of loads/stores issued.

Additionally, matrix engines (2-D SIMD instructions) are becoming quite popular due to their performance improvements for deep learning and scientific computing. Would it be beneficial to add these new advanced SIMD instructions into the framework or should these instructions be left to libraries such as OpenBLAS and MKL?

**Comment by mattip** [comment]
We have some support for ppc64 in [`numpy/core/src/common/simd/vsx`](https://github.com/numpy/numpy/tree/main. /numpy/core/src/common/simd/vsx) but the [documented](https://numpy.org/devdocs/reference/simd/simd-optimizations.html?highlight=simd#ibm-power-big-endian-cpu-feature-names) support seems quite partial. Contributions to extend it are welcome. Is POWER10 different? Is there documentation for the different 256bit vector operations on POWER10?

**Comment by nicholaiTukanov** [comment]
> Is POWER10 different? Is there documentation for the different 256bit vector operations on POWER10?

[POWER ISA 3.1](https://wiki.raptorcs.com/w/images/f/f5/PowerISA_public.v3.1.pdf) details the new features that POWER10 will have (there are hyperlinks on pg 566 to the new 256 bit load/store instructions).

**Comment by nicholaiTukanov** [comment]
@seiko2plus and I have had an email thread about this, and we are moving the conversation to this issue. 

He has suggested the following workflow for adding VSX4 support:

1. Extend the infrastructure through [ccompiler_opt.py](https://github.com/numpy/numpy/blob/main/numpy/distutils/ccompiler_opt.py)
2. Extend runtime detection support through [npy_cpu_features.c.src](https://github.com/numpy/numpy/blob/main/numpy/core/src/common/npy_cpu_features.c.src)
3. Adding the new VSX4 SIMD instructions such as `lxvp`/`stxvp` into the appropriate location

We also discussed adding support for new advanced SIMD instructions, and @seiko2plus said that it is possible to support them in the universal intrinsics but it requires the following:

> - add new data types for quad registers, e.g. npyv_f32x4
>    note: we already have triple and dual registers.
> - add new data type for quad accumulators e.g. npyv_a4
> - add new data type for dual accumulators e.g. npyv_a2
> - add new intrinsics to convert between accumulators, quad, and dual registers. e.g. npyv_cvt_a4_f32, npyv_cvt_f32_a4
> - covers and emulates MMA intrinsics for all other architectures for used ones.
> 

However, as I mentioned in my initial comment, @seiko2plus also pointed out that 

> NumPy packages are shipped with OpenBlas so technically add SIMD kernels for matrices operations will require a lot of
work that will not be executed unless we decide to drop OpenBLAS from our packages.

Thus, unless someone else knows where NumPy could benefit from such instructions, it is probably best to leave the advanced SIMD instructions to the BLAS libraries.

@seiko2plus please correct me if anything above is incorrect.

**Comment by seiko2plus** [comment]
Sorry for the delayed response, Almost correct except for `lxvp/stxvp`, they are supposed to be used with MMA paired arguments and I don't see any other usage for them.

Along with MMA, VSX4 came with new instructions that support integer mod&division, 64-bit multiply high/low, blend, mask manipulation and extract low/high.

Supporting VSX4 not going to be that hard, except for the MMA part. I can extend the infrastructure for VSX4 or guide you if you facing any issues.

**Comment by nicholaiTukanov** [comment]
> Almost correct except for `lxvp/stxvp`, they are supposed to be used with MMA paired arguments and I don't see any other usage for them.

These instructions can be used generally to load and store 256 bits of data. They are not restricted to MMA. 

> I can extend the infrastructure for VSX4 or guide you if you facing any issues.

I have extended ccompiler_opt.py, npy_cpu_features.c.src, and npy_cpu_features.h to add support for VSX4. I then install numpy using setup.py, and I get the following at the end of the install process:

```########### EXT COMPILER OPTIMIZATION ###########
Platform      : 
  Architecture: ppc64le
  Compiler    : gcc

CPU baseline  : 
  Requested   : 'min'
  Enabled     : VSX VSX2 VSX3
  Flags       : -mcpu=power9 -mtune=power9
  Extra checks: VSX_ASM

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : VSX4
  Generated   : none
CCompilerOpt.cache_flush[810] : write cache to path -> /home/nicholai/prog/repos/nt_np/build/temp.linux-ppc64le-3.9/ccompiler_opt_cache_ext.py

########### CLIB COMPILER OPTIMIZATION ###########
Platform      : 
  Architecture: ppc64le
  Compiler    : gcc

CPU baseline  : 
  Requested   : 'min'
  Enabled     : VSX VSX2 VSX3
  Flags       : -mcpu=power9 -mtune=power9
  Extra checks: VSX_ASM

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : VSX4
  Generated   : none
CCompilerOpt.cache_flush[810] : write cache to path -> /home/nicholai/prog/repos/nt_np/build/temp.linux-ppc64le-3.9/ccompiler_opt_cache_clib.py
```

I assume that since I see VSX4 in CPU dispatch, then NumPy will use the VSX4 specific flags (`-mcpu=power10 -mtune=power10`). @seiko2plus, is this assumption correct? 


Also, I am using runtests.py to make sure I didn't break anything, but I am getting the following failures:

```================================================================================================================== short test summary info ===================================================================================================================
FAILED numpy/distutils/tests/test_ccompiler_opt.py::TestCCompilerOpt_ppc64le_gcc::test_args_options - AssertionError: dispatch features "VSX VSX2 VSX3" not match "vsx vsx2$"
FAILED numpy/distutils/tests/test_ccompiler_opt.py::TestCCompilerOpt_ppc64le_gcc::test_targets_groups - AssertionError: targets "" not match "vsx3$"
FAILED numpy/distutils/tests/test_ccompiler_opt.py::TestCCompilerOpt_ppc64le_gcc::test_targets_multi - AssertionError: targets "" not match "vsx3$"
FAILED numpy/distutils/tests/test_ccompiler_opt.py::TestCCompilerOpt_ppc64le_clang::test_args_options - AssertionError: dispatch features "VSX VSX2 VSX3" not match "vsx vsx2$"
FAILED numpy/distutils/tests/test_ccompiler_opt.py::TestCCompilerOpt_ppc64le_clang::test_targets_groups - AssertionError: targets "" not match "vsx3$"
FAILED numpy/distutils/tests/test_ccompiler_opt.py::TestCCompilerOpt_ppc64le_clang::test_targets_multi - AssertionError: targets "" not match "vsx3$"
```

@seiko2plus, do you know what these failures mean?

**Comment by nicholaiTukanov** [comment]
Also, assuming that NumPy can detect VSX4 and compile with the right flags, where do I add the new VSX4 instructions?

**Comment by seiko2plus** [comment]
These instructions can be used generally to load and store 256 bits of data. They are not restricted to MMA.

But I couldn't find a direct way to extract to the lower and higher 128-bit registers, could you please show me an example of it?

And even if that is possible without extra cycles then logically the compiler suppose to optimize out any sequence 128-bit load/stores of contiguous memory access. Am I missing something?.

> I have extended ccompiler_opt.py, npy_cpu_features.c.src, and npy_cpu_features.h to add support for VSX4. I then install numpy using setup.py, and I get the following at the end of the install process:

Then please forward it to a new pull request so I can review it.

> do you know what these failures mean?

`VSX2` shouldn't imply `VSX3`. Your patch should modify `ccompiler_opt` as follows:

```diff
+        ## Power10/ISA 3.1
+        VSX4 = dict(interest=4, implies="VSX3", extra_checks="VSX4_MMA", implies_detect=False),
         # ARM
         NEON  = dict(interest=1, headers="arm_neon.h"),
         NEON_FP16 = dict(interest=2, implies="NEON"),
@@ -457,12 +459,14 @@ class attribute `conf_features`, also its override
                 VSX3 = dict(
                     flags="-mcpu=power9 -mtune=power9", implies_detect=False
                 )
+                VSX4 = dict(
+                    flags="-mcpu=power10 -mtune=power10", implies_detect=False
+                )
             )
             if self.cc_is_clang:
                 partial["VSX"]["flags"]  = "-maltivec -mvsx"
                 partial["VSX2"]["flags"] = "-mpower8-vector"
                 partial["VSX3"]["flags"] = "-mpower9-vector"
```
And make sure of adding test files for `VSX4` and `VSX4_MMA`, i.e:
numpy/numpy/distutils/checks/cpu_vsx4.c
numpy/numpy/distutils/checks/extra_vsx4_mma.c

> Also, assuming NumPy can detect VSX4 and compile with integer tags, where can I add the new VSX4 instructions?

Away from adding MMA and u/int128(NumPy doesn't support it), you can start with:

- integer division/modulo
   we will need to add raw vsx intrinsics for the corresponding division/modulo, since the universal intrinsics only supports vector division by a scalar, see:

   * /numpy/numpy/core/src/common/simd/intdiv.h
   * /numpy/numpy/core/src/common/simd/vsx/arithmetic.h
   * /numpy/numpy/core/src/umath/loops_arithmetic.dispatch.c.src
   * /numpy/numpy/core/src/umath/loops.c.src

- insert/replace/partial
  They can be used in improving non-contiguous/parial memory access
  * /numpy/numpy/core/src/common/simd/vsx/memory.h

**Comment by seiko2plus** [comment]
@nicholaiTukanov, any updates? please inform me, if you're not willing to work on it.

**Comment by RajalakshmiSR** [comment]
Nicholai has shared the patch and we will test it again once and submit it for review.

**Comment by seiko2plus** [comment]
@RajalakshmiSR, alright, thanks.

**Comment by seiko2plus** [comment]
I agree VSX4 instructions/intrinsics are now accessible through dispatch/baseline paths, and enough intrinsics are covered within universal intrinsics. Thank you @rafaelcfsousa!.
