### ISSUE TITLE
Typing of nditer:  __getattr__ is not sufficient to cover __enter__, __exit___ and __iter__ dunders

### ISSUE THREAD

**Issue by MatthieuDartiailh** [numpy/numpy#19551]
Trying to type check a program using `np.nditer` using mypy 0.812 and 0.910 and numpy 1.21.1 fails complaining about missing dunder methods. Looking at https://github.com/numpy/numpy/blob/main/numpy/__init__.pyi#L767 and https://github.com/numpy/numpy/blob/main/numpy/__init__.pyi#L633 I believe the issue stems from the fact that the presence of `__getattr__` does not automatically cover all dunders. 

Adding the following to nditer stub (below `__getattr__`) allow the code to type check properly. I can make a PR with those changes and any other deemed relevant to improve nditer typing.
```python
    def __enter__(self) -> nditer: ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType]
    ) -> Optional[bool]: ...
    def __iter__(self) -> Any: ...
```

### Reproducing code example:

```python
import numpy as np

a = np.nditer(np.zeros((2, 2, 2)))
with a:
    for b in a:
        pass

```

### Error message:

Mypy output:
```
test.py:4: error: "nditer" has no attribute "__enter__"
test.py:4: error: "nditer" has no attribute "__exit__"
test.py:5: error: "nditer" has no attribute "__iter__" (not iterable)
Found 3 errors in 1 file (checked 1 source file)
```

### NumPy/Python version information:

Python 3.9.1, Numpy 1.21.1, Mypy 0.812 or 0.910 (only tested version)

**Comment by BvB93** [comment]
I'd argue this is a mypy bug, but that doesn't make it any less problematic...
In any case, if you're willing to create a PR then that would be much appreciated!

There are a couple of other dunders that would be worth adding based on a quick comparison
between `object` and `np.nditer`. Just as you proposed with `__iter__`, I'd suggest to use `Any` 
for the likes of `__getitem__`.


``` python
In [9] import numpy as np

In [10]: set(dir(np.nditer)) - set(dir(object))
Out[10]: 
{'__copy__',
 '__delitem__',
 '__enter__',
 '__exit__',
 '__getitem__',
 '__iter__',
 '__len__',
 '__next__',
 '__setitem__',
 'close',
 'copy',
 'debug_print',
 'dtypes',
 'enable_external_loop',
 'finished',
 'has_delayed_bufalloc',
 'has_index',
 'has_multi_index',
 'index',
 'iterationneedsapi',
 'iterindex',
 'iternext',
 'iterrange',
 'itersize',
 'itviews',
 'multi_index',
 'ndim',
 'nop',
 'operands',
 'remove_axis',
 'remove_multi_index',
 'reset',
 'shape',
 'value'}
```

**Comment by MatthieuDartiailh** [comment]
Will do when I get a couple spare cycles.
