### ISSUE TITLE
PyArray_CompareFunc of dtype datetime64 returns incorrect value for 'NaT' objects.

### ISSUE THREAD

**Issue by anmolschauhan** [numpy/numpy#19574]
Sort order for `NaT` values got [changed in numpy 1.18.0](https://numpy.org/doc/stable/release/1.18.0-notes.html#nat-now-sorts-to-the-end-of-arrays).

`PyArray_CompareFunc` of dtype `datetime64` returns incorrect as per the updated sort order.

This is present with numpy 1.20.2 and 1.21 too.

This is reproducible via the following extension module.

compare_bug.c
```c
#include <Python.h>
#include "numpy/arrayobject.h"
#include "numpy/ndarrayobject.h"
#include "numpy/ndarraytypes.h"
#include "numpy/arrayscalars.h"
#include "numpy/ufuncobject.h"


static PyObject*
reproduce_bug(PyObject* self, PyObject* args) {
    PyObject *arr = NULL;
    if (!PyArg_ParseTuple(args, "|O", &arr)) {
        return Py_None;
    }
    PyArrayObject *numpy_arr = (PyArrayObject*) arr;
    // We just compare 0th and 1st element and print out
    // the returned value.
    int x = numpy_arr->descr->f->compare(
        PyArray_GETPTR1(numpy_arr, 0),
        PyArray_GETPTR1(numpy_arr, 1),
        numpy_arr
    );
    printf("DEBUG %d\n", x);
    return Py_None;
}

static PyMethodDef bug_functions[] = {
    {"bug", (PyCFunction)reproduce_bug, METH_VARARGS, NULL},
    { NULL, NULL, 0, NULL }
};

static struct PyModuleDef numpybugmodule = {
    PyModuleDef_HEAD_INIT,
    "numpy_bug",
    NULL,
    -1,   
    bug_functions
};

PyMODINIT_FUNC
PyInit_numpy_bug(void)
{
    return PyModule_Create(&numpybugmodule);
}
```

setup.py
```python
from distutils.core import setup, Extension, DEBUG
import numpy

extra_compile_args = ["-DNDEBUG", "-O3"]
sfc_module = Extension('numpy_bug', sources = ['compare_bug..c'],
                        include_dirs=[numpy.get_include()],
                       extra_compile_args=extra_compile_args)

setup(name = 'mtnumpy', version = '1.0',
    description = 'Python Package with superfastcode C++ extension',
    ext_modules = [sfc_module]
    )
```

Running this after installing above:
```python
In [1]: import numpy, numpy_bug

In [2]: numpy_bug.bug(numpy.array(['NaT', '2020-01-01'], dtype='datetime64[s]')) # should print 1 as per new sort order.
DEBUG -1
```

**Comment by seberg** [comment]
Hmm, yeah, it is a bug.

In general, these functions are a bit tricky: They duplicate ufunc machinery logic, which is error prone.  They also live in a place that should eventually be deprecate/delete entirely.  Although, I am not sure if we need single element versions for these, and whether they would live on the `ArrayMethod` in the future.

Another oddity/unclear thing about these functions is that most of them only work with aligned data.

**Comment by asmeurer** [comment]
PR up at https://github.com/numpy/numpy/pull/19607

**Comment by charris** [comment]
> I also noticed that min/max and argmin/argmax both always return NaT if there is one. But they do the same thing with NaN, so maybe that is intentional.

I don't know if that was ever decided on, it just happens for NaN because all comparisons are false except `nan != nan` and  NaT copies that. Ufuncs also do that when comparing array elements. AFAICT, `PyArray_CompareFunc` is only available from C and used for sorting objects and user types.

**Comment by anmolschauhan** [comment]
Thanks for the fix @asmeurer !
