### ISSUE TITLE
Can cdist be added to numpy ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [numpy/numpy#19583]
It will be nice addition to not install all of scipy just to use cdist

**Comment by bashtage** [comment]
I suspect not. SciPy has a module for this topic, Also, moving things from scipy to NumPy that aren't about the fundamental array container is a very slippery slope since there is not absolute boundary.

**Comment by rkern** [comment]
I also would not move this to numpy. The general direction of numpy development is to remove and not add to this already-overstuffed API. `cdist()` would also bring in a large menagerie of the distance functions as well. That kind of unbounded collection is exactly what scipy is for.

Everyone has that _one thing_ in scipy that, if added to numpy, they wouldn't need to install all of scipy so often. Unfortunately, it's a different _one thing_ for each person.

**Comment by rossbar** [comment]
I'm going to go ahead and close this - the above responses address the original question well. If you would like to continue the discussion, the [numpy-discussion mailing list](https://www.scipy.org/scipylib/mailing-lists.html) is a more appropriate forum.
