### ISSUE TITLE
Using `dtype=str` in functions like `arange`

### ISSUE THREAD

**Issue by tomergt45** [numpy/numpy#19585]
I think using `str` as a `dtype` value can be beneficial, in some cases.

For example:
```
>> np.arange(10, dtype=str)
array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])
```

**Comment by rkern** [comment]
`np.arange(10).astype(str)` will do this already. I'm not sure there is any significant benefit to supporting it in the `dtype=` keyword.
