### ISSUE TITLE
Stop distributing tests to reduce package size

### ISSUE THREAD

**Issue by abhiabhi94** [numpy/numpy#19591]
## Feature

As of now, if I install the package from PyPI, the tests too are shipped alongside. I think tests are mostly intended to be run in an editable(development) environment.

#### Currently
```sh
$ python -m venv venv
$ . venv/bin/activate
$ pip install numpy  
Collecting numpy
  Using cached numpy-1.21.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
Installing collected packages: numpy
Successfully installed numpy-1.21.1
$ ls venv/lib/python3.8/site-packages/numpy/tests/
__init__.py  __pycache__  test_ctypeslib.py  test_matlib.py  test_numpy_version.py  test_public_api.py  test_reloading.py  test_scripts.py  test_warnings.py
```
Not including them in the source and wheel distribution will reduce the package size.

Adding a line `prune numpy/tests` to `MANIFEST.in` should probably do the trick. I would be glad to make the patch if this seems reasonable.

**Comment by rkern** [comment]
They are also distributed so people can test their installation. The location of the tests is intentional. The issue could be revisited, but it's no accident.

**Comment by mattip** [comment]
Shipping the tests allows end users to verify their installation is correct quickly and easily, without installing anything else. This is as easy as `python -c "import numpy as np;np.test()"` for all users of NumPy, not only for developers. How much space would removing this from the wheel save (hint: since the wheel is a zip file, you can use zip tools to remove the tests)?

**Comment by mattip** [comment]
hehe, sorry @rkern for cross-posting

**Comment by abhiabhi94** [comment]
> This is as easy as python -c "import numpy as np;np.test()" for all users of NumPy, not only for developers

As far as I can see, there are other requirements for the tests to run like `pytest`, and other dependencies stated in [`test_requirements.txt`](https://github.com/numpy/numpy/blob/main/test_requirements.txt). As it is, users will have to manually install all the dependencies to test these.

```sh
$ python -c 'import numpy as np;np.test()'                                    
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "../venv/lib/python3.8/site-packages/numpy/_pytesttester.py", line 128, in __call__
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by rkern** [comment]
Sure, but it's straightforward to install those. A separate test suite would not be.

**Comment by abhiabhi94** [comment]
Okay, this may just be a silly question, but i am curious as to why would you want to run the entire test suite to verify the installation? Wouldn't something like just doing `import numpy` or something else to get the version be enough to verify that the package is present and can be imported?

**Comment by ksunden** [comment]
Note that even uncompressed numpy/tests is only 48 KB

**Comment by rkern** [comment]
Largely to test that the linked accelerated BLAS/LAPACK library works okay on your system. That's a complicated component, buildwise, that could fail if it were built wrong for your system (e.g. using advanced SSE instruction sets that aren't on your older CPU).

I don't think there will be any appetite for this from the core devs. The gains are too small relative to the amount of change required. It's not that keeping the tests outside of the package is a bad idea (it's a perfectly valid choice), but we have a lot of history and existing documentation for a such small benefit. I'm going to close this. If a core dev wants to take it up, go ahead and re-open.
