### ISSUE TITLE
runtests.py fails, missing .coveragerc

### ISSUE THREAD

**Issue by limburgher** [numpy/numpy#19617]
.coveragerc is present in git but not release tarballs.

**Comment by charris** [comment]
Is it needed? It is only used for CI testing.

**Comment by limburgher** [comment]
If we want to run the testsuite in the Fedora RPM build, yes. Unless runtests.py can be patched to skip it if not present.

**Comment by charris** [comment]
If you are interested, you could make a PR adding it to `MANIFEST.in`.

**Comment by limburgher** [comment]
I will, thanks!

**Comment by charris** [comment]
Closed by #19619.
