### ISSUE TITLE
Colour intensity is changing when stacking numpy image arrays

### ISSUE THREAD

**Issue by Jimut123** [numpy/numpy#19626]
I am loading an image from [here](https://github.com/Jimut123/simply_junk/blob/main/image.nii.gz?raw=true), which is saved as .nii.gz. The image opens fine (with a dimension of (497x497)), and when displayed using matplotlib, it shows with correct intensities, as shown below:

[![kidney image 1][1]][1]

When we are trying to make it a 3 channel image, by stacking the numpy array, and after plotting it, the intensity changes, as shown below:

[![kidney image 2][2]][2]

Any idea how to resolve this? **Note: I want to make the intensity as close to the one plotted using matplotlib**

### Reproducing code example:

The minimal code to reproduce the problem in google colaboratory is present here:

```python
  import numpy as np
  import nibabel as nib
  from nibabel import nifti1
  import matplotlib.pyplot as plt

  ! wget "https://github.com/Jimut123/simply_junk/blob/main/image.nii.gz?raw=true" -O image.nii.gz

  image_file_name = "image.nii.gz"
  print(image_file_name)
  epi_img = nib.load(image_file_name)
  epi_img_data = epi_img.get_fdata()
  epi_img_data = epi_img_data/epi_img_data.max()
  # epi_img_data = epi_img_data[..., np.newaxis]
  plt.imshow(epi_img_data,cmap='gray')
  plt.show()

  total_mask = np.stack((epi_img_data,)*3, axis=-1)
  plt.imshow(total_mask)
  plt.show()
```

### NumPy/Python version information:

1.19.5 3.7.11 (default, Jul  3 2021, 18:01:19) 
[GCC 7.5.0]

  [1]: https://i.stack.imgur.com/gJ5ar.png
  [2]: https://i.stack.imgur.com/h0sjb.png

**Comment by rossbar** [comment]
For future reference, the numpy issue tracker is typically for bugs and feature requests in numpy itself and is not really the appropriate forum for a general question like this.

The behavior you are seeing is not a result of a bug in numpy or matplotlib, but a general problem in color mapping. Fortunately, one of the [numpy tutorials has a brief section on rgb<->grayscale mapping](https://numpy.org/numpy-tutorials/content/tutorial-svd.html#operations-on-an-axis). I'd suggest starting there and following some of the links for a better description of the general problem, as well as some of the many tools available in scientific Python libraries to solve it.

**Comment by eric-wieser** [comment]
In this particular case, `cmap="gray"` means "make the highest value white and the lowest black", whereas the version without it means "use the values as pixel colors".

But indeed, this is not a numpy question at all, but a matplotlib one.
