### ISSUE TITLE
Mistake in discription

### ISSUE THREAD

**Issue by yellowBunnyy** [numpy/numpy#19629]
https://github.com/numpy/numpy/blob/b235f9e701e14ed6f6f6dcba885f7986a833743f/numpy/core/fromnumeric.py#L1067
`x = np.array([3, 1, 2])
np.argsort(x)
array([1, 2, 0])`

should be:

`x = np.array([3, 1, 2])
np.argsort(x)
array([1, 2, 3])`

**Comment by seberg** [comment]
No, its correct this is argsort, not sort.
