### ISSUE TITLE
types: missing type information for several common functions

### ISSUE THREAD

**Issue by henryiii** [numpy/numpy#19649]
While there have been improvements to the static types, including a few functions being added, (at least) the following functions now are completely missing types:

* `np.frombuffer`
* `np.histogram2d`
* `np.histogramdd`
* `np.broadcast_arrays`
* `np.meshgrid`
* `np.array_split`

Also these, but I think there's a reason for these:

* `np.min` (should use `np.amin`)
* `np.max` (should use `np.amax`)
* `np.diag` (Matlab comp function for `np.diagonal`)

### Reproducing code example:

Use any of these function in mypy and upgrade from 1.20 to 1.21.

### Error message:

A bunch of "Call to untyped function "frombuffer" in typed context" in every package I'm upgrading to use NumPy 1.21 in static typing.

### NumPy/Python version information:

1.21.1, on Python 3.9.

**Comment by charris** [comment]
What mypy version are you using?

**Comment by henryiii** [comment]
0.910

**Comment by BvB93** [comment]
> A bunch of "Call to untyped function "frombuffer" in typed context" in every package I'm upgrading to use NumPy 1.21 in static typing.

Per the error message: mypy is not complaining about an undefined function, it's complaining about a function whose arguments are unannotated. The relevant mypy flag, [`disallow-untyped-calls`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-untyped-calls), is disabled by default; I'd recommend to keep it that way as it demands a level of type coverage that partially typed libraries (such as numpy) cannot provide.

**Comment by henryiii** [comment]
Yes, I thought this was a regression, but it appears it's actually slightly better that before but still partially typed. What is the process for adding types? Is someone adding them in batches, or is it something what would help out if I were to open a PR for the functions I'm interested in? And are the types always in `.pyi` files (looking at the missing `pyi` for `multiarray.py`)?

**Comment by BvB93** [comment]
>Yes, I thought this was a regression, but it appears it's actually slightly better that before but still partially typed. What is the process for adding types? Is someone adding them in batches, or is it something what would help out if I were to open a PR for the functions I'm interested in?

If you want an up date overview of the current typing progress I'd recommend to keep an eye on https://github.com/numpy/numpy/issues/16546 and this is also a good starting point for if anyone is interested in contributing. The hope is to wrap up introducing some (basic?) annotations for the entire library for the 1.22 release, which I think is very much feasible at the current pace.

> And are the types always in `.pyi` files (looking at the missing `pyi` for `multiarray.py`)?

Yes, the type hints are currently exclusivvelly located in `.pyi` stub files (with the exception of `numpy.typing` itself, which mixes inline typing and stub files). As for `multiarray` in particular: the relevant stub file was only added back in https://github.com/numpy/numpy/pull/19060, hence why it's missing from the 1.21 release.
