### ISSUE TITLE
BUG: `runtest.py` fails with a `KeyError`

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#19653]
Since the merging of https://github.com/numpy/numpy/pull/19628 the `python ./runtest.py` fails with a `KeyError`.

Based on the traceback it seems that `sysconfig.get_path('platlib', expand=False)` returns an incorrect formattable string.

### Error message:
```
>>> python .\runtests.py
Traceback (most recent call last):
  File "C:\Users\hardd\Documents\GitHub\numpy\runtests.py", line 695, in <module>
    main(argv=sys.argv[1:])
  File "C:\Users\hardd\Documents\GitHub\numpy\runtests.py", line 192, in main
    site_dir, site_dir_noarch = build_project(args)
  File "C:\Users\hardd\Documents\GitHub\numpy\runtests.py", line 480, in build_project
    site_dir = site_dir_template.format(platbase=dst_dir,
KeyError: 'base'
```

And the content of the offending `site_dir_template` formattable string:

``` python
>>> print(site_dir_template)
{base}/Lib/site-packages
```
### NumPy/Python version information:
1.22.0.dev0+696.g334428c4d
3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:10:34) [MSC v.1916 64 bit (AMD64)]

**Comment by mattip** [comment]
I wonder how it passed CI.
