### ISSUE TITLE
array_equal warns about ragged arrays

### ISSUE THREAD

**Issue by adeak** [numpy/numpy#19669]
When a ragged array is passed to `np.array_equal`, it will emit a `VisibleDeprecationWarning`. Considering the use of this function and earlier issues such as https://github.com/numpy/numpy/issues/9210, we should probably silence any warnings [here](https://github.com/numpy/numpy/blob/887766071724d27431b453b8270f299213b2d189/numpy/core/numeric.py#L2437) (I'll gladly do this if this indeed needs fixing).

### Reproducing code example:

```python
import numpy as np

flat = [0]
ragged = [0, [42]]
np.array_equal(flat, ragged)
```
The logic itself is of course correct: `np.array_equal(ragged, ragged)` is `True`.

### Warning:

```
/home/adeak/tmpenv/lib/python3.9/site-packages/numpy/core/numeric.py:2440: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1, a2 = asarray(a1), asarray(a2)
```

### NumPy/Python version information:
```
1.21.1 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
```

**Comment by mattip** [comment]
This specific use case is called out in [NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html#usage-and-impact). Please adjust your code accordingly.

**Comment by adeak** [comment]
Thanks for the tip @mattip, I didn't think to check the NEP.

Unfortunately, unlike with `assert_equal`, neither of my arrays are literals or known-ragged, so this change would be less straightforward. Fortunately, though, the raggedness was a result of a bug, so I don't see this warning after debugging.

Since this is not a bug, then, I'm closing this.
