### ISSUE TITLE
Compatibility mgrid and linspace 

### ISSUE THREAD

**Issue by srkunze** [numpy/numpy#19670]
I recently wanted to use the same way to construct a `linspace` as I did with an `mgrid`, i.e

```
T_size = slice(2, 30, 1)
P_size = slice(0, 80, 2)
grid = np.mgrid[T_size, P_size]

....

linspace = np.linspace(T_size)
# BOOM... exception
```

```
TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'
```

I think that interoperability here would be great.

**Comment by eric-wieser** [comment]
If you want a function to behave like mgrid, why not just use mgrid? I think `mgrid[T_size]` will do what you want.

**Comment by srkunze** [comment]
Wow, okay. That seem to work. In the interim, I used `np.arange`. Thanks for the enlightment.

Is there a reason why there are at least like three implementations for the same thing?

**Comment by phetdam** [comment]
`np.linspace` is definitely *not* the same thing as `np.arange`. `np.arange` relies on step size to determine how many elements are in the returned array, which excludes the endpoint, while `np.linspace` can include the endpoint and determines step size from the `num` argument, which specifies the number of elements in the returned array.

Personally I use `np.arange` only with integer steps when I need several stepped values starting from zero, e.g. `np.arange(10)` while I use `np.linspace` when I need to include the endpoint and/or require a non-integer step size, e.g. `np.linspace(0, 1, num=150)`. Trying to use `np.arange` for the latter application would not make sense; I'm not interested in spending time computing step sizes.

Hope my explanation makes some sense.

**Comment by melissawm** [comment]
Might be nice to add this explanation somehow in the documentation.

**Comment by phetdam** [comment]
Hm, I think there might not be any need. There are several warnings about using `np.arange` with non-integer steps in the [relevant devdocs](https://numpy.org/devdocs/reference/generated/numpy.arange.html) that advise using `np.linspace` instead, but these warnings aren't shown for `np.arange` [docs page for the stable release](https://numpy.org/doc/stable/reference/generated/numpy.arange.html). The relevant docs source for `np.arange` is [added dynamically](https://github.com/numpy/numpy/blob/main/numpy/core/_add_newdocs.py#L1579). Maybe we just need to update the stable docs?

**Comment by srkunze** [comment]
You can also use imaginary steps to define the number of items in a range when using slices. At least to me it feels like we have a lot of methods to create the very same thing.

Maybe, a separate page aggregating them and explaining when to use which variant would be great. Right now I see:

- np.mgrid
- np.linspace
- np.arange

**Comment by rkern** [comment]
`mgrid` is primarily for creating N-dimensional grids, which `linspace()` and `arange()` don't do. There is overlap between these three methods, certainly, but they are not all methods "to create the very same thing".

**Comment by srkunze** [comment]
@rkern The issue is how to discover this information and how to use it. Python programmers usually strives to have one obvious way. But as soon as you discover all three methods, choosing one of them becomes weird (especially for non-interactive/long-term code).

**Comment by phetdam** [comment]
True, it's not exactly obvious for NumPy beginners and even for more seasoned users to give a specific list of when exactly they would use `linspace`, `arange`, etc., but I think after reading the documentation and maybe trying some examples it should become clear which of the functions might suit their use case best. E.g. from my earlier comment,

> Personally I use `np.arange` only with integer steps when I need several stepped values starting from zero, e.g. `np.arange(10)` while I use `np.linspace` when I need to include the endpoint and/or require a non-integer step size, e.g. `np.linspace(0, 1, num=150)`. Trying to use `np.arange` for the latter application would not make sense[.]

I think an ok rule of thumb is "use whatever takes less tweaking" since that indirectly translates to less code, more readability.

**Comment by melissawm** [comment]
> 
> Maybe, a separate page aggregating them and explaining when to use which variant would be great. Right now I see:
> 
>     * np.mgrid
> 
>     * np.ogrid
> 
>     * np.linspace
> 
>     * np.arange

I think this is a good idea, especially seeing as we regularly have similar issues. I think a "How to partition a domain using NumPy" (please suggest better titles!) would be great.

**Comment by rkern** [comment]
"mgrid, and linspace, and arange, oh my!" :-)

To be clear, I also think this would be a good thing to explain in one page. I just want to be clear that the purpose is to explain the real distinctions between them, not some historical exegesis on why we have mistakenly duplicated functionality.

**Comment by InessaPawson** [comment]
@srkunze We have reviewed the documentation related to the NumPy functions for partitioning domains and added a how-to-guide here: [numpy.org/doc/stable/user/how-to-partition.html](https://numpy.org/doc/stable/user/how-to-partition.html). 
If we addressed all your questions, please close this issue.

**Comment by phetdam** [comment]
Nice, I think this article makes a great addition to the collection of NumPy how-tos.

**Comment by InessaPawson** [comment]
@srkunze I'm going to close this issue as it seems for now you don't have any additional questions on this topic.

**Comment by srkunze** [comment]
@InessaPawson Thanks for your patience. The explainer looks quite informing and comprehensive. Thank a lot! :)
