### ISSUE TITLE
Importing Numpy within Conda throws "double free or corruption (top)" followed by core dump

### ISSUE THREAD

**Issue by baozzhao** [numpy/numpy#19684]
After months without using Python, today I needed to implement something in it using Numpy. However, weirdly, whenever I try to import it within any Conda environment, I get a "double free or corruption" error, followed by a core dump:

> In [1]: import numpy
> double free or corruption (top)
> Aborted (core dumped)

### Reproducing code example:

I mean, this is a hard issue precisely because the error happens at the import of Numpy, so nothing more than a `import numpy` is needed to trigger the bug.

### Error message:

As mentioned above, it is just "double free or corruption (top)" followed by "Aborted (core dumped)".

### NumPy/Python version information:

I am glad to check and give more details about the Numpy version, but I will need help learning how, since I cannot even import Numpy. For the record, I am on Linux Ubuntu, 18.04.

**Comment by mattip** [comment]
`conda list` should show the versions of everything in your environment. Perhaps valgrind would be a tool to pinpoint what is going on, if you have used it before.

**Comment by ShreyPatel4** [comment]
Have you tried reinstalling the package / or have you just roll back for testing instance?

**Comment by melissawm** [comment]
I am closing this as there's really no way to investigate without more information and doesn't seem reproducible. Feel free to reopen if this persists. Thanks!
