### ISSUE TITLE
DOC: Using `shares_memory` and `may_share_memory` to determine if an array is a view or a copy

### ISSUE THREAD

**Issue by Mukulikaa** [numpy/numpy#19688]
I am writing an explanation document on copies and views based on the points in #15793. To answer the question-"How to tell if NumPy created a view or a copy?", I have written about using the `ndarray.base` attribute. 

I found a couple of old answers on StackOverflow that talk about using `shares_memory` and `may_share_memory` to check overlapping memory. So these functions can be used to check for views and copies as well, I think, but is it recommended? I am unsure if I should talk about this in the doc.

I would appreciate any information or opinions on this matter. 🙂

**Comment by eric-wieser** [comment]
The idea behind the `shares_memory` APIs is to answer questions like "are `a` and `b` a view of the same array".

For instance, `np.array([1, 2, 3])[:]` is a view, but it's a view of an array that no one else is using so there's no real reason to care that it's a view. `np.frombuffer(b"test", dtype='u1').base` is also a view, but it's not even a view of an array, it's a view of some other object!

**Comment by Mukulikaa** [comment]
Thanks for your explanation @eric-wieser! I am closing this issue as there are no further doubts.🙂
