### ISSUE TITLE
DOC: Moving NumPy Internals from reference guide to Under the hood docs

### ISSUE THREAD

**Issue by Mukulikaa** [numpy/numpy#19689]
[NumPy internals](https://numpy.org/devdocs/reference/internals.html) is a very detailed and informative set of documents. I feel these docs should be moved to [Under-the-hood Documentation for developers](https://numpy.org/devdocs/dev/underthehood.html#under-the-hood-documentation-for-developers) to make them more visible. 

IMO these documents do not belong in NumPy fundamentals because they contain low-level explanations of NumPy's code which I think are very helpful to developers but not so much to users. However, I am open to other ideas for reorganizing them and would love to hear them!

**Comment by rossbar** [comment]
For a bit of background, the internals doc currently resides in the reference guide, which seems like a poor fit according to NEP 44. I think the under-the-hood docs (currently empty) in the user guide is indeed a sensible place for the internals to end up :+1:
