### ISSUE TITLE
ENH: mention the size of the data  like int32 or int64

### ISSUE THREAD

**Issue by vijayan108** [numpy/numpy#19711]
## Feature

If you're looking to request a new feature or change in functionality, including
adding or changing the meaning of arguments to an existing function, like  in numpy module we need to mention  the  character so that i need some improve for mentioning that  data structure directly analysis that data and give respective structure
 to explain your
reasoning in addition to opening an issue or pull request. You can also check
out our [Contributor Guide]
https://github.com/numpy/numpy/blob/main/numpy/core/_dtype.py if you
need more information. -->https://numpy.org/doc/1.21/user/basics.creation.html

**Comment by mattip** [comment]
Did you mean to request something? The title seems to mention "the size of the data" - could you give an example in code that describes what you would like to see?
