### ISSUE TITLE
DOC: "np." should be added before "array(..."

### ISSUE THREAD

**Issue by summersky08** [numpy/numpy#19726]
## Documentation

I found a small typo in the documentation. In the third code box of [Array Creation at NumPy Fundamentals](https://numpy.org/doc/stable/user/basics.creation.html), we see
`a = array([2, 3, 4], dtype = np.uint32)`
`b = array([5, 6, 7], dtype = np.uint32)`
We should add "np." before "array" i.e.
`a = np.array([2, 3, 4], dtype = np.uint32)`
`b = np.array([5, 6, 7], dtype = np.uint32)`

**Comment by phetdam** [comment]
Correct. I'll try to submit a pull request for this. Thanks!
