### ISSUE TITLE
Discussion archive

### ISSUE THREAD

**Issue by Dan-Patterson** [numpy/numpy#19749]
I would normally post on the discussion forum, but
http://numpy-discussion.10968.n7.nabble.com/
seems to be down/gone.
Are we left with the email-only option?

**Comment by mattip** [comment]
It seems nabble is gone.

We should discuss this at a community meeting. I am not sure what the path forward is and how best to manage the mail archive, browsing via https://mail.python.org/pipermail/numpy-discussion/ is not very friendly.

**Comment by eric-wieser** [comment]
https://mail.python.org/archives/list/python-ideas@python.org/ is much more pleasant; can we upgrade our mailing list software to match?

**Comment by mattip** [comment]
@ewdurbin may have some idea how to migrate the old mail archive to the newer format?

**Comment by Dan-Patterson** [comment]
The python site  would be a nice implementation for NumPy.  Keep us posted.

**Comment by ewdurbin** [comment]
@mattip contact postmaster@python.org!

**Comment by rgommers** [comment]
This is done, see https://scipy.org/scipylib/mailing-lists.html for all the links to the Mailman 3 archives for NumPy and SciPy. Thanks everyone!
