### ISSUE TITLE
mypy errors on len of ArrayLike

### ISSUE THREAD

**Issue by janosh** [numpy/numpy#19744]
### Reproducing code example:

```py
from numpy.typing import ArrayLike


tup: ArrayLike = (1, 2, 3)


print(f"{len(tup)=}")
```

### Error message:

```py
mypy t.py
t.py:7: error: Argument 1 to "len" has incompatible type "Union[Sequence[Sequence[Sequence[Sequence[Sequence[Any]]]]], Union[Union[_SupportsArray[dtype[Any]], Sequence[_SupportsArray[dtype[Any]]], Sequence[Sequence[_SupportsArray[dtype[Any]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]]]], Union[bool, int, float, complex, str, bytes, Sequence[Union[bool, int, float, complex, str, bytes]], Sequence[Sequence[Union[bool, int, float, complex, str, bytes]]], Sequence[Sequence[Sequence[Union[bool, int, float, complex, str, bytes]]]], Sequence[Sequence[Sequence[Sequence[Union[bool, int, float, complex, str, bytes]]]]]]]]";
expected "Sized"
Found 1 error in 1 file (checked 1 source file)
```

Given that `ArrayLike` seems to be a large union of `Sequence`s, and `Sequence` contains `Sized`, shouldn't `ArrayLike` do as well? What type of `ArrayLike` would not support `len()`?
### NumPy/Python version information:

```sh
python -c "import sys, numpy; print(numpy.__version__, sys.version)
```

1.21.1 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)]

**Comment by BvB93** [comment]
Per the [docs](https://numpy.org/doc/stable/reference/typing.html#numpy.typing.ArrayLike): `npt.ArrayLike` also includes scalars and arbitrary objects implementing the `__array__` protocol, 
neither of which is guaranteed to support `__len__`.

**Comment by janosh** [comment]
I see... At the risk of asking an unwelcome question, in what sense is a scalar array-like? By definition, an array is a _collection_ of elements.

**Comment by charris** [comment]
`array_like` is a made up word for anything that can be converted to a NumPy array. I plead guilty to the original sin.

**Comment by baggiponte** [comment]
This might not be the right place, but I was wondering how we can annotate an `ArrayLike` that defines `__len__()`.
