### ISSUE TITLE
ENH: Add an `ndarray` typing protocol

### ISSUE THREAD

**Issue by anuppari** [numpy/numpy#19752]
I'd like to define a protocol that extends the numpy N-D Array. I can't create an abstract base class for unrelated reasons. I'd like to do something like the following:

```python
from typing import Protocol
import numpy.typing import NDArrayProtocol  # Currently doesn't exist

class NdArrayWithMethod(NDArrayProtocol, Protocol):
    def method(self, input) -> None: pass

class ImpementsProtocol(np.ndarray):
    def method(self, input):
        ...

class AlsoImpementsProtocol(np.ndarray):
    def method(self, input):
        ...

def operates on protocol(in: NdArrayWithMethod):
   ...

```

The protocol [cannot subclass](https://www.python.org/dev/peps/pep-0544/#protocols-subclassing-normal-classes) `ndarray` directly, so I need to use something like `NDArrayProtocol`. Is there an ndarray protocol exposed somewhere?

**Comment by BvB93** [comment]
Honestly, I see little value in adding, exposing and maintaining such a massive protocol.

The only use case were such protocol would be appropriate for the mixed nominal/structural subtyping you're trying to express here. And even this is more of band-aid solution necessitated by the lack of `Intersection` type.

> I can't create an abstract base class for unrelated reasons.

Depending on the exact nature of these constraints, you could potentially define a type-check-only ABC and use that as baseclass.

``` python
import abc
import numpy as np
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    class FakeABC(np.ndarray, metaclass=abc.ABCMeta):
        @abc.abstractmethod
        def method(self, input): ...
else:
    FakeABC = np.ndarray
     

class ImpementsMethod(FakeABC):
    def method(self, input): ,..


class AlsoImpementsMethod(FakeABC):
    def method(self, input): ...


def operates_on_fake_abc(in: FakeABC): ... 

```
