### ISSUE TITLE
Missing __array_ufunc__ in type stubs

### ISSUE THREAD

**Issue by anuppari** [numpy/numpy#19773]
mypy complains that `np.ndarray` has no `__array_ufunc__` attribute. Looking at the [type stubs](https://github.com/numpy/numpy/blob/main/numpy/__init__.pyi#L1662), looks like it's missing from the annotations for `ndarray`

### Reproducing code example:

Run `mypy --check-untyped-defs` on the `__array_ufunc__` [example in the subclassing portion of the docs](https://numpy.org/doc/stable/user/basics.subclassing.html#array-ufunc-for-ufuncs).

(By the way, that example has a typo: it should be `import numpy as np` not `input numpy as np`)

### Error message:

```
error: "__array_ufunc__" undefined in superclass
```
Replacing the `super()` call with `np.ndarray` yields:

```
error: "Type[ndarray]" has no attribute "__array_ufunc__"
```

### NumPy/Python version information:

1.20.3 3.8.6 (default, Nov 29 2020, 16:45:43) 
[GCC 9.3.0]

**Comment by AbhirathAnupamJoshi** [comment]
take

**Comment by AbhirathAnupamJoshi** [comment]
take

**Comment by BvB93** [comment]
A quick look at the annotations reveals that there are currently three `ndarray` methods that are 
missing from the stubs:
* `__array_ufunc__`
* `__array_function__`
* `__array_finalize__`

**Comment by BvB93** [comment]
@AbhirathAnupamJoshi we don't generally assign issues, but PRs are very much welcome.
