### ISSUE TITLE
loadtxt strange handling empty lines with `max_rows`

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#19785]
There is a quirk with how `np.loadtxt` counts rows/lines that results in strange behavior when using the `max_rows` parameter. Empty lines (i.e. lines containing only a newline character) are ignored for the purposes of parsing, but are *not* ignored by the row counting. The result is that, if you have a file with blank lines, you have to *also* count the blank lines when using the `max_rows` parameter in order to get the desired number of *data* rows.

### Reproducing code example:

Let's say you have the following data, which includes empty lines between data rows:

```python
>>> import io
>>> f = io.StringIO("1 2\n\n3 4\n\n5 6\n\n")
```

Reading the whole file works as expected (empty rows are ignored):

```python
>>> np.loadtxt(f)
array([[1., 2.],
       [3., 4.],
       [5., 6.]])
```

Now let's say you want to only read the first 2 *data* rows, so you try using `max_rows`:

```python
>>> f.seek(0)
>>> np.loadtxt(f, max_rows=2)  # expecting np.array([[1., 2.], [3., 4.]])
array([1., 2.])
```

This is due to the fact that the blank lines are not ignored when incrementing rows.

There is another inconsistency in that blank lines that precede the first row containing data *are* ignored for the purposes of row counting (unlike blank lines that occur *after* the first data row):

```python
>>> f = io.StringIO("\n\n\n\n\n1 2\n\n3 4\n\n5 6\n\n")
# The empty lines *preceding* the first data row are ignored for row counting
# but empty lines *after* the first data row are not.
>>> np.loadtxt(f, max_rows=3)
array([[1., 2.],
       [3., 4.]])
```

### Expected Behavior

I think it would be an improvement if empty lines were ignored for the purposes of row counting. IMO `max_rows` should be interpreted as the maximum number of rows in the returned array, rather than the maximum number of newlines in the file.

See also BIDS-numpy/npreadtext#20

### NumPy/Python version information:

1.22.0.dev0+954.g5ae53e93b 3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0]

**Comment by vedikar** [comment]
Can I work on this issue ?

**Comment by mattip** [comment]
We don't usually assign issues, the first person to file a PR should link back to the issue to indicate they are giving it a try. Tests are of course critical, please follow the [developer guide](https://numpy.org/devdocs/dev/index.html).

**Comment by seberg** [comment]
The main issue here is making a decision what the behaviour _should_ be.  That is only easy if we decide to consider the current behaviour to be a bug.  (I am not sure how easy it will be to modify the current code.)

The small problem is, that even if it is a bug, users could be working around it by artificially passing a larger `max_rows` than they want.

**Comment by rgommers** [comment]
This ended up on the PyData Global Sprint list, but it's not suitable for newcomers until a decision is made.

@seberg is this still to-be-triaged, or was it discussed?

**Comment by seberg** [comment]
A bit at some point I think, but no real decision.  This is a "needs decision" issue, of course.

**Comment by seberg** [comment]
Closing for now.  The current situation is that we will read `rows` (not lines!), but give a long verbose warning when an empty line is found the first time.

If anyone thinks this may be the wrong choice, please open a new issue.
