### ISSUE TITLE
Feature: KB4598291 is now released

### ISSUE THREAD

**Issue by Harshavardhan-tech** [numpy/numpy#19793]
## Feature

To prevent unexpected runtime behavior, opencv (and numpy 1.19.4 through 1.19.5) contains a check for this fixes this issue. 
[KB4598291 is now released.docx](https://github.com/numpy/numpy/files/7078582/KB4598291.is.now.released.docx)
https://developercommunity2.visualstudio.com/t/fmod-after-an-update-to-windows-2004-is-causing-a/1207405
```
from numpy import arange, linalg, float64
try:
    a = arange(13 * 13, dtype=float64).reshape(13, 13)
    a = a % 17  # calls fmod
    linalg.eig(a)
except for Exception:
    raise RuntimeError("The current Numpy installation (...) fails to pass a sanity check due to a bug in the windows runtime...")
```

**Comment by eric-wieser** [comment]
For reference, the linked docx file contains:

> KB4598291 is now released! Receiving this update will resolve the 64-bit fmod/remainder FPU issue. Additional information about the patch is available here: https://support.microsoft.com/en-us/topic/february-2-2021-kb4598291-os-builds-19041-789-and-19042-789-preview-6a766199-a4f1-616e-1f5c-58bdc3ca5e3b . Note that this fix is not listed in the “Highlights” section of that page. Expanding the “Improvements and fixes” section will list this fix as “Addresses an issue that causes the 64-bit fmod() and remainder() functions to damage the Floating Point Unit (FPU) stack.”.
> This update has started being pushed out to machines today, but this occurs gradually. If you would like to update your machine immediately, you can also get the appropriate .msu from here: https://www.catalog.update.microsoft.com/Search.aspx?q=KB4598291
> 
>

**Comment by mattip** [comment]
I don't understand why you have opened 3 issues about this. Please stop spamming the NumPy repo.
