### ISSUE TITLE
MyPy call to untyped function "median" in typed context

### ISSUE THREAD

**Issue by Akazz-L** [numpy/numpy#19807]
Hi, I'm working with Numpy and MyPy for static type checking and I ran accross this error while running MyPy and calling `np.median` function : `error: Call to untyped function "median" in typed context`
It seems all the functions in `numpy/numpy/lib/function_base.pyi`  including `np.median` are not typed yet which might cause this issue. Any idea on when the typing will be available for those functions ?

**Comment by BvB93** [comment]
`np.median` annotations have been added as of https://github.com/numpy/numpy/pull/20034.
