### ISSUE TITLE
No module named 'numpy.random.default_rng'

### ISSUE THREAD

**Issue by dotehacker** [numpy/numpy#19812]
## Documentation

```
>>> import numpy.random.default_rng
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy.random.default_rng'
```
> my version is --->

```python
>>> np.__version__
'1.21.2'
```

**Comment by rkern** [comment]
That's right. `default_rng` is a function, not a module. This is how to access it:

```
>>> import numpy as np
>>> rng = np.random.default_rng()
```

Is there any documentation that told you to do `import numpy.random.default_rng`? If so, that's incorrect and needs to be fixed. But I don't think we have any such.

**Comment by dotehacker** [comment]
Documentation [book](https://numpy.org/doc/1.21/numpy-user.pdf) page no 65 top

**Comment by rkern** [comment]
Indeed, thank you!

**Comment by dotehacker** [comment]
Welcome, by the way I know the solution, I issued this so that others will not get stuck on that.. Thanks!!
