### ISSUE TITLE
DOC: np.histogramdd input dimensions are mis-documented

### ISSUE THREAD

**Issue by dwysocki** [numpy/numpy#19823]
The docstring for `np.histogramdd` states at the top that the `sample` input must either be an `(N, D) array`, or a `(D, N) array_like`.  However, later in the docstring, an example for the first case is given, which is actually a `(D, N) array`.

```
    sample : (N, D) array, or (D, N) array_like
        The data to be histogrammed.
        Note the unusual interpretation of sample when an array_like:
        * When an array, each row is a coordinate in a D-dimensional space -
          such as ``histogramdd(np.array([p1, p2, p3]))``.
        * When an array_like, each element is the list of values for single
          coordinate - such as ``histogramdd((X, Y, Z))``.
```

Either this elaboration is wrong, and we should use something like `np.array([p1,p2,p3]).T` or `np.column_stack((p1,p2,p3))`, or the `(N, D) array` statement at the top should actually just be `(D, N) array`.  If the latter is the case, then there's no need to distinguish between arrays and array-likes, and the top line should just read

```
    sample : (D, N) array_like
```

At that point, the elaboration is a bit confusing, as there is no unusual interpretation.  `np.shape(np.array([X,Y,Z])) == np.shape((X, Y, Z))`

**Comment by xilin22** [comment]
Hi, I'd like to give this a try as part of Grace Hopper's OSX day.

**Comment by Digya053** [comment]
Hi, I would like to give this a try as part of Grace Hopper Open Source Day.
