### ISSUE TITLE
Can't astype object to string

### ISSUE THREAD

**Issue by Illviljan** [numpy/numpy#19822]
Not sure if this is just user error but I seem unable to change the type of an element to string.

### Reproducing code example:
Sorry about the pandas here but I can't figure out how to recreate the array otherwise:

```python
import pandas as pd
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
a = pd.MultiIndex.from_arrays(arrays, names=('number', 'color')).to_numpy()
# array([(1, 'red'), (1, 'blue'), (2, 'red'), (2, 'blue')], dtype=object)
a.astype(str)
ValueError: setting an array element with a sequence
```

The result I wanted:
```python
np.array(["(1, 'red')", "(1, 'blue')", "(2, 'red')", "(2, 'blue')"], dtype=str)
```

Here's what happen when I just copy the repr:
```python
import numpy as np
a = np.array([(1, 'red'), (1, 'blue'), (2, 'red'), (2, 'blue')], dtype=object)
# array([[1, 'red'],
#        [1, 'blue'],
#        [2, 'red'],
#        [2, 'blue']], dtype=object)
a.astype(str)
# array([['1', 'red'],
#        ['1', 'blue'],
#        ['2', 'red'],
#        ['2', 'blue']], dtype='<U4')
```

### NumPy/Python version information:

1.21.1 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:37:25) [MSC v.1916 64 bit (AMD64)]

**Comment by rossbar** [comment]
Even without the value error, I wouldn't expect `astype` to give you the result you were hoping for. I would expect it to convert the data values to a string, which is indeed what happens when I use the non-pandas part of the original example:

```python
>>> a = array([(1, 'red'), (1, 'blue'), (2, 'red'), (2, 'blue')], dtype=object)
>>> a
array([[1, 'red'],
       [1, 'blue'],
       [2, 'red'],
       [2, 'blue']], dtype=object)
>>> a.astype(str)
array([['1', 'red'],
       ['1', 'blue'],
       ['2', 'red'],
       ['2', 'blue']], dtype='<U4')
```

**Comment by Illviljan** [comment]
Yes in that case it converts it to a 2d array. But in my case I want a 1d array and view those tuples as the data values, which the MultiIndex manages to do somehow,  and then convert them to their string version,

I found a workaround using vectorize:
```python
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
a = pd.MultiIndex.from_arrays(arrays, names=('number', 'color')).to_numpy()
np.vectorize(str)(a)
Out[168]: 
array(["(1, 'red')", "(1, 'blue')", "(2, 'red')", "(2, 'blue')"],
      dtype='<U11')
```

**Comment by anmolbhatheja** [comment]
Use array_str() function to convert 
`arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
a = array_str(arrays)
print(type(a))`

**Comment by rossbar** [comment]
> I found a workaround using vectorize:

Great. I don't think there's anything actionable here and it seems like you were able to resolve your use-case, so I will close this. Please feel free to reopen for followup if needed.

**Comment by Illviljan** [comment]
Isn't an error actionable?

Here's the minimal example, had to dig through pandas to get there:
```python
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
b = np.empty_like(values[0], dtype=object)
for i, v in enumerate(zip(*arrays)):
    b[i] = v
b.astype(str)
ValueError: setting an array element with a sequence
```
