### ISSUE TITLE
Docker build failed.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#19830]
See https://github.com/numpy/numpy/actions/runs/1204103327. Might be related to the documentation build changes.

**Comment by mattip** [comment]
It seems to be something in `setup.py` with the regexp that looks into `FULLVERSION`
```
#14 [build 4/5] RUN conda activate numpy-dev &&     python setup.py build_ext --inplace &&     ccache -s
#14 1.387 Traceback (most recent call last):
#14 1.387   File "/workspace/numpy/setup.py", line 58, in <module>
#14 1.387     MAJOR, MINOR, MICRO = re.match(r'(\d+)\.(\d+)\.(\d+)', FULLVERSION).groups()
#14 1.388 AttributeError: 'NoneType' object has no attribute 'groups'
#14 ERROR: process "/bin/bash --login -o pipefail -c conda activate ${CONDA_ENV} &&     python setup.py build_ext --inplace &&     ccache -s" did not complete successfully: exit code: 1
```

**Comment by mattip** [comment]
So something is wrong with the way the conda env is picking up the `FULLVERSION`
https://github.com/numpy/numpy/blob/b3a66e88b005c4ca783c11e5d934451b7ca72477/setup.py#L50-L60

**Comment by rgommers** [comment]
This CI job has been green for a while, closing.
