### ISSUE TITLE
BUG: `partition`/`argpartition` do not accept `uint64` indices

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#19832]
The `partition` and `argpartition` functions currently raise when the `kth` indices are supplied as a `uint64` array-like.

The functions in question check that the indice-type can safelly be cast to `intp`, which of course will fail in the case of `uint64`. I'm not quite sure how the likes of `__getitem__` and `take` do manage to deal with `uint64`, but there it seems to work just fine. 

https://github.com/numpy/numpy/blob/b3a66e88b005c4ca783c11e5d934451b7ca72477/numpy/core/src/multiarray/item_selection.c#L1295-L1299

### Example
``` python
In [1]: import numpy as np

In [2]: ar = np.arange(10)

In [3]: ar.partition(np.uint64(5))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-fee31ee69481> in <module>
----> 1 ar.partition(np.uint64(5))

TypeError: Partition index must be integer
```

### NumPy/Python version information:

```
1.22.0.dev0+997.g8e4e40f60
3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15) 
[Clang 11.1.0 ]
```

**Comment by seberg** [comment]
In most cases indexing just uses `same-kind` casting and hopes for the best.  So unfortunately, currently it is possible to get silent integer overflow/rollover in some of the indexing code.  Unfortunately, that may just be the best thing to do here right now, also...

**Comment by BvB93** [comment]
I think that overflow might be the lesser of two evils here, especially since `same-kind` also has the disadvantage here of interpreting boolean arrays as a normal numerical indice-array.

**Comment by seberg** [comment]
> since same-kind also has the disadvantage here of interpreting boolean arrays as a normal numerical indice-array.

Good point.  The indexing code would reject boolean earlier on (because it is a masked index).
