### ISSUE TITLE
[Feature request]: Add "round()" member function for "np.array"

### ISSUE THREAD

**Issue by songyuc** [numpy/numpy#19841]
## Feature
Dear developers,
Could you please "round()" member function for "np.array", which will be more like OO programming.
Here is a snippet example:
```python
x = np.array((13,2.5))
y = np.around(x)
y1 = x.around()
```

**Comment by seberg** [comment]
@songyuc we generally try to avoid duplication between functions and methods for the most part now.  Basically, the function version is the typical API for most functionality.  I realize that we probably have dozens of functions that are both functions and methods on `ndarray`, but it would need some very good arguments why `round` is special compared to other ones.  There are more discussions on this, e.g. in gh-7452, but I suspect you should bring this up on the mailing list if you really want to get some support.

Unless there is a good reason why `round` is special here?

**Comment by rgommers** [comment]
No follow-up and we are not going to do this, so closing.
