### ISSUE TITLE
Overview of min/max functions

### ISSUE THREAD

**Issue by timhoffm** [numpy/numpy#19858]
## Documentation

There are multiple min/max functions. While they are crosslinked in "See also" it is hard to tell the difference and choose the right one.

The docs should contain a short description of the differences and a table similar to:

|                    | input 2 arrays | input 1 array + axis |
|--------------------|----------------|----------------------|
| **propagate NaNs** | minimum()      | amin()               |
| **ignore NaNs**    | fmin()         | nanmin()             |

I'd be willing to add such a description. The question is where should it go? It's probably not reasonable to replicate that in a notes section on all four functions (though one could do that). The alternative would be a dedicated page that all docstrings would link to.

**Comment by eric-wieser** [comment]
Not to mention `np.min` and `np.max` which are more sensible spellings of `np.amin` and `np.amax`.

**Comment by yuvalofek** [comment]
I am working on this during the numpy-scipy sprint 2021

**Comment by yuvalofek** [comment]
In the see also sections there are one-liners that describe the differences between these functions. Are those enough, or should we do something else?

**Comment by yuvalofek** [comment]
We are thinking of rearranging the Mathematical functions page (https://numpy.org/devdocs/reference/routines.math.html) to have these functions grouped together so it is easier to differentiate

**Comment by melissawm** [comment]
@yuvalofek I think the point of the issue is to copy those to a centralized place for all the min/max functions. Maybe a good option would be to add them here: https://numpy.org/devdocs/reference/routines.sort.html

**Comment by yuvalofek** [comment]
We are thinking of moving the nanmin, nanmax, amin, and amax from the statistics doc to the math doc and centralizing all of the max/min functions under an 'extrema finding' subsection
