### ISSUE TITLE
np.random.choice - inconsistent behaviour

### ISSUE THREAD

**Issue by atMelnyk** [numpy/numpy#19855]
### Reproducing code example:

```
import numpy as np
 
values = np.arange(10)
 
p = None
np.random.seed(42)
result = np.random.choice(values, 5, replace=False, p=p)
 
print(f"Uniform-implicit: {result}")
 
p = np.ones(10) / 10
np.random.seed(42)
result = np.random.choice(values, 5, replace=False, p=p)
 
print(f"Uniform-explicit: {result}")
```

### Error message:

Inconsistent behaviour around parameter "p". Setting "p" to None and to explicit uniform weights both correspond to the uniform distribution, but produce different results for a given seed.

Proposal: p=None and p=[explicit uniform weights] should produce identical sequences under a given seed.

PS. replace=True/False plays no role in the effect.

### NumPy/Python version information:

1.21.2 3.8.6 (default, Dec 18 2020, 09:43:18)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

**Comment by rkern** [comment]
Sorry, once you introduce explicit numerical probabilities, floating point arithmetic error can introduce inaccuracies. We also can use different, more efficient algorithms when `p=None` than when `p=ones(10)/10`. We only guarantee that identical inputs give identical outputs, not that different inputs that _should_ be the same (under some reasoning) will give identical outputs.
