### ISSUE TITLE
full_like() bug when filled with nan

### ISSUE THREAD

**Issue by mrspatbile-classroom** [numpy/numpy#19866]
### Reproducing code example:

```python
import numpy as np
M =np.array([[[[1,2],[4,5],[6,7]]]])
np.full_like(a=M,fill_value=np.nan)
```

### Expected return:

```
array([[[[nan, nan],
         [nan, nan],
         [nan, nan]]]])
```

### Obtained return:

```

array([[[[-9223372036854775808, -9223372036854775808],
         [-9223372036854775808, -9223372036854775808],
         [-9223372036854775808, -9223372036854775808]]]])
```

**Comment by rkern** [comment]
When passing in the integer `M` array as the array to be like, you are asking that the NaNs be converted into integers. -9223372036854775808 is what that looks like.

```
|3> np.array(np.nan).astype(int)
array(-9223372036854775808)
```

**Comment by mrspatbile-classroom** [comment]
That is right. If I turn one element of the matrix M into float, it correctly returns np.nan.

M =np.array([[[[1.,2],[4,5],[6,7]]]])
np.full_like(a=M,fill_value=np.nan)

Thank you!
