### ISSUE TITLE
No module named 'numpy.core._multiarray_umath' VS Code Ubuntu 20.04

### ISSUE THREAD

**Issue by Sharkoo123** [numpy/numpy#19889]
Hi everyone! I am new to Ubuntu and is trying to run a simple code using **numpy** as below: 

   `import matplotlib.pyplot as plt
    import numpy as np

    x = [1,2,3,4]
    y = [3,5,7,9]
    plt.grid(True)
    plt.xlabel("My X values")
    plt.ylabel("My Y values")
    plt.plot(x,y, 'b-^', lineWidth = 3, markersize = 7, label = "Blue Line")
    plt.legend(loc = "upper center")
    plt.show()`

But VS Code returns an error as below:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nhan_g3_3579/Desktop/pyPro/matPlotLib/matBasic1.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 138, in <module>
    from . import cbook, rcsetup
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 31, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.9 from "/bin/python3.9",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

I have tried uninstall and reinstall **numpy** using:

- pip install numpy

And the terminal returns: Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (1.21.2)

I am looking forward to hearing from you guys. Thank you so much in advance.

**Comment by charris** [comment]
Probably installed in the wrong place, you may have multiple Python versions. Use `python -mpip install` with the relevant `python`, you never know what `pip` alone points to. That said, I believe VS studio requires its own install, there should be other relevant issues for that, or maybe something on stackoverflow.

**Comment by seberg** [comment]
Newe versions of NumPy would direct you to: **https://numpy.org/devdocs/user/troubleshooting-importerror.html**

Please have a look at the site, it should contain links that should help you, this is a problem with installing/setting up VS Studio, but I think we have a link for more information on that website.  If you do not find a solution there, additions to the trouble-shotting websites are appreciated!

**Comment by Sharkoo123** [comment]
Thank you but I don't see any solutions with numpy on Ubuntu. I have tried uninstall and reinstalling VS Code too but nonthing changed

**Comment by Sharkoo123** [comment]
I copied the code to my terminal to run it and it worked. But it is still not working in VS Code.

**Comment by seberg** [comment]
VS code needs some path setups, we linked it in the docs: https://code.visualstudio.com/docs/python/environments

That should be what you are running into probably, although I can't say for sure of course.

**Comment by seberg** [comment]
I hope you found a solution, but it is a problem with the environment/setup in Visual studio (or similar) and not directly related to NumPy.  Since the issue was quiet for a while now, closing.
