### ISSUE TITLE
New SystemError returned from ufunc with a custom data type

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#19904]
In the [`numtypes`](https://github.com/WarrenWeckesser/numtypes) package, I have a custom data type, `nint32`, that is a 32 bit integer with the most negative value reserved as a `nan`.   I noticed the following change in how attempting to add a Python integer to an array with this dtype results in an error. (An error is expected--the implementation is not complete.)

For an array `t` with dtype `nint32`, attempting to calculate `t + 1` results in an error, with the actual type of the error dependent on the NumPy version:
* NumPy 1.20.3:  ValueError: No cast function available.
* NumPy 1.21.2:  TypeError: Cannot cast data from int64 to nint32.
* NumPy main dev branch: SystemError: <ufunc 'add'> returned NULL without setting an error

(See below for ipython sessions with these errors.)

I suspect the `SystemError` raised with the NumPy development version is a bug.

It is certainly possible that there is a bug in the implementation of `nint32`, and the numpy error is just a consequence of that.  I'm looking into that, but I figured I'd put this here in case someone (where "someone" is most likely @seberg :grin:) already knows the likely cause of the change.

<strike>Possibly related: https://github.com/numpy/numpy/issues/19634</strike>
 
-----
All the following is with Python 3.9.1.

With NumPy 1.20.3 (installed with conda)

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.20.3'

In [3]: import numtypes as nt

In [4]: t = np.array([nt.nint32(10), nt.nint32(25)])

In [5]: t
Out[5]: array([10, 25], dtype=nint32)

In [6]: t + 1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-a18e5b75b3a8> in <module>
----> 1 t + 1

ValueError: No cast function available.
```

With NumPy 1.21.2 (installed with pip):

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.21.2'

In [3]: import numtypes as nt

In [4]: t = np.array([nt.nint32(10), nt.nint32(25)])

In [5]: t
Out[5]: array([10, 25], dtype=nint32)

In [6]: t + 1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a18e5b75b3a8> in <module>
----> 1 t + 1

TypeError: Cannot cast data from int64 to nint32.

```

With NumPy 1.22.0.dev0 (a recent snapshot of the main development branch):

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.22.0.dev0+1088.gdf0b1bd75'

In [3]: import numtypes as nt

In [4]: t = np.array([nt.nint32(10), nt.nint32(25)])

In [5]: t
Out[5]: array([10, 25], dtype=nint32)

In [6]: t + 1
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-6-a18e5b75b3a8> in <module>
----> 1 t + 1

SystemError: <ufunc 'add'> returned NULL without setting an error
```

**Comment by seberg** [comment]
Ah, unrelated to the other issue, must be a small bug in the reporting with casts.

The other issue is about the ufunc machinery checking for python errors basically randomly, even though before it just keeps going (because if nobody needs the GIL it cannot even check for errors – of course it can now, but this is legacy API!)
