### ISSUE TITLE
Uniform test style for f2py

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#19922]
Extracted from https://github.com/numpy/numpy/pull/19775#issuecomment-924448130.

At the moment it seems like the newer tests use code and suffix to put the fortran source inside the `test_*.py` (8336e76#diff-beaa766b50d9c2a8df83b293fa468e786d9ffb8b10d3f2a44d46d81084abd022)

However, the older tests had a nicer structure with the source code in a separate f/90 file (even though the older test style can be cleaned up now).

As an example of the older test approach it is the one in `test_mixed.py` or `test_common.py` (8042526).

For new tests, the split .f90 and test_*.py style should be used (with `pathlib` instead of the `_path helper`).

Essentially:
- Migrate all `f2py` tests to use split files
- Update to remove the redundant `_path` helper

**Comment by melissawm** [comment]
Should we create an "f2py testing" project on github?

**Comment by HaoZeke** [comment]
I'm not sure we need to right now, I was under the impression that we could simply work with it here for now... However for some of the other discussions (G3) it would certainly help so actually, lets have one :)

**Comment by HaoZeke** [comment]
Closed by #20517
