### ISSUE TITLE
Proposal: Remove workarond to support byte converters by default in loadtxt

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#19924]
`np.loadtxt` includes a mechanism that automatically encodes with latin-1 before applying converter functions by default. This appears to be a compatibility feature for older versions. The [test suite seems to suggest](https://github.com/numpy/numpy/blob/24c4436b38b0507d757b996a4bd54ce2a9585dd0/numpy/lib/tests/test_io.py#L656-L664) that the primary compatibility concern was the ability to use `decode` as a converter. This seems like a shim to smooth over differences from the Python 2->3 transition and may no longer be necessary, or at least is seems a bit cumbersome as the default.

For example, if a user is expecting the converter functions to take unicode inputs, the default behavior results in a surprising failure:

```python
>>> import io
>>> s = io.StringIO('a b\nc d')
>>> # Note: isdecimal is a string method; there is no bytes counterpart bytes.isdecimal
>>> converters = {i: lambda x: float(x) if x.isdecimal() else float.fromhex(x) for i in range(2)}
>>> np.loadtxt(s, converters=converters)
Traceback (most recent call last)
   ...
AttributeError: 'bytes' object has no attribute 'isdecimal'
```

Another place where this crops up is with inputs that contain characters outside of the latin-1 range:

```python
>>> s = io.StringIO('α β\nγ δ')
>>> converters = {i: lambda x: x.capitalize() for i in range(2)}
>>> np.loadtxt(s, dtype=str, converters=converters)
Traceback (most recent call last)
   ...
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b1' in position 0: ordinal not in range(256)
```

Unfortunately this mechanism is triggered by `encoding="bytes"`, which means that the value of the `encoding` parameter affects how the converters behave:

```python
>>> s = io.StringIO('α β\nγ δ')
>>> np.loadtxt(s, dtype=str)  # works as expected
array([['α', 'β'],
       ['γ', 'δ']], dtype='<U1')
>>> # But doesn't work if converters are used
>>> s.seek(0)
>>> np.loadtxt(s, dtype=str, converters={i: lambda x: x for i in range(2)})
Traceback (most recent call last)
   ...
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b1' in position 0: ordinal not in range(256)
```

My main question is: is the default behavior with `encoding="bytes"` still desirable now that the Python 2->3 transition is complete?

**Comment by seberg** [comment]
We are trying to change the default right now, so I think that would close this (or I assume).
