### ISSUE TITLE
Numpy importing failure

### ISSUE THREAD

**Issue by KevinTsukuyo** [numpy/numpy#19932]
### Reproducing code example:

```python
import pandas as pd
import numpy as np
import os
```

### Error message:

ValueError                                Traceback (most recent call last)
<ipython-input-1-119eb27aa566> in <module>
      1 # -*- coding:ANSI -*-
----> 2 import pandas as pd
      3 import numpy as np
      4 import os
      5 import io

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\__init__.py in <module>
      9 for dependency in hard_dependencies:
     10     try:
---> 11         __import__(dependency)
     12     except ImportError as e:
     13         missing_dependencies.append("{0}: {1}".format(dependency, str(e)))

~\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\__init__.py in <module>
    148     from . import _distributor_init
    149 
--> 150     from . import core
    151     from .core import *
    152     from . import compat

~\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\__init__.py in <module>
     54 del os
     55 
---> 56 from . import umath
     57 
     58 # Check that multiarray,umath are pure python modules wrapping

ValueError: source code string cannot contain null bytes

### NumPy/Python version information:
Python 3.6.4
Numpy 1.21.2

![1632319344232](https://user-images.githubusercontent.com/52930609/134450528-aa52a0f6-2600-4ea0-b519-720ec483db65.png)

**Comment by politecat314** [comment]
This doesn't seem to be a problem with numpy itself. This might be helpful: https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes

**Comment by seberg** [comment]
It indeed sounds like some files are encoding incorrectly.  How did you get/install NumPy?  Whatever happened, at some point in the process it seems like files got converted from ASCII/utf-8 to some local (maybe chinese?) encoding that uses multiple bytes, so if you read it as utf-8 it includes the null bytes?

**Comment by KevinTsukuyo** [comment]
> It indeed sounds like some files are encoding incorrectly. How did you get/install NumPy? Whatever happened, at some point in the process it seems like files got converted from ASCII/utf-8 to some local (maybe chinese?) encoding that uses multiple bytes, so if you read it as utf-8 it includes the null bytes?

I installed numpy using pip and have used it for three years. Such errors never raised before. I don't know how I can check the way I read it. Would you please tell me how to check?

**Comment by KevinTsukuyo** [comment]
> This doesn't seem to be a problem with numpy itself. This might be helpful: https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes

It seems to be a solution, but I don't know  change encoding format under windows using jupyter notebook or command prompt. Would you please tell me hwo?

**Comment by seberg** [comment]
Going to close this issue since it was not active for a few months.  Not sure where the encoding got wrong and I hope you figured it out, but it does not seem directly related to NumPy in any case, so there is nothing to be done for us.
