### ISSUE TITLE
Memory leak of float32 and float16 type

### ISSUE THREAD

**Issue by chrisbpoint** [numpy/numpy#19966]
In a pyqt app that retrieves camera images a numpy array of type uint8 and applies averaging, we discovered a frame rate drop after about 2^16 recorded images. After a long investigation, we nailed down the problem to be a typecast to np.float32 before averaging. With float64, it does not appear though. We used float32 in the first place because it allow faster frame rates than float64.  Profiling the code with 'memory_profiler' (mprof) shows a memory leak at a about 2^16 operations with a corresponding update rate drop.

The sample below shows minimal code that reproduces the issue. 

### Reproducing code example:

The script is named leaky.py in order to run it via mprof run python leaky.py

```python
import numpy as np


def leaky():
    data = np.ones(100000).astype(np.float32)  # zeros or random.randn works as well
                                               # np.float16 leaks too
    for i in range(1, 2**16 + 1000):
        data = data / i  # data /= i does not leak 
                         # other operations, e.g. + or -, leak too
                
if __name__ == "__main__":
   leaky()

```

### Error message:

There is no error message, but 'mprof run python leaky.py' with a corresponding 'mprof plot --output memory-profile.png' shows the memory leak. The leak does not occur with float64, but with float32 and float16 too. Interesting to note that the leak does not occur with compound statements, e.g. data /= i instead of data = data/ i.  Other operations, e.g. + or -, leak too. To increase the effect (i.e. the bump in the plot), just increase the number of np.ones from 100k to 500k.  

### NumPy/Python version information:

1.20.3 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]

**Comment by eric-wieser** [comment]
Is the memory growth unbounded? What operating system is this on?

**Comment by chrisbpoint** [comment]
There is one discrete memory increase at around 2^16 (~65k) recorded images (and correspondingly one discrete drop of update rate), but we never tried beyond (~500k) yet. I may run a longer run now. It has been tested on Ubuntu 18 so far. I may try other OS' as well.

**Comment by chrisbpoint** [comment]
And, as mentioned in the original report, a memory increase depends on the size of the numpy array. I chose 100k elements because then it becomes obvious in the plot, but is still fast enough (couple of seconds).

**Comment by eric-wieser** [comment]
Could you upload the graph that you get on your system?

**Comment by chrisbpoint** [comment]
For 100k elements:
![memory-profile-100k](https://user-images.githubusercontent.com/48798172/134902729-c1a71cd0-498b-4f52-a444-387e4b31d973.png)

For 1000k elements:
![memory-profile-1M](https://user-images.githubusercontent.com/48798172/134902798-48765a2f-0536-4d58-bc9b-fc5ee91ea843.png)

**Comment by eric-wieser** [comment]
If you add a `gc.collect(); sleep(1)` at the end of your program, does the memory drop down to 0 again?

**Comment by chrisbpoint** [comment]
It goes back to a level before when the increase happens, see plot below (for 500k here):
![memory-profile-500k](https://user-images.githubusercontent.com/48798172/134903881-30eab5ff-0ba2-45dd-9fc1-05f5251fb8a0.png)

**Comment by chrisbpoint** [comment]
For reference, the same with a float64 cast (100k loops, and gc collecting at the end):
![memory-profile-float64](https://user-images.githubusercontent.com/48798172/134904318-1995f7f2-d3f0-4ec2-82cb-ad35167fc52e.png)

**Comment by seberg** [comment]
Interesting, but hard to believe that there would be any effect, especially discrete, after such a long time.  If you make it a `while True` loop, I cannot see anything with newer versions.

My guess is that you are seeing some operating system effects or effects of the typical `malloc` allocation strategies?  I would be interested to know what is going on, but I doubt it is a NumPy issue itself and don't know where we would start to understand it.

**Comment by seberg** [comment]
Ah, took a moment to sink in...

The issue is value-based "casting" (actually promotion).  After `2**16` NumPy decides that the "best" way to represent the Python float is a uint32 or int32 (not sure).  `Float32` and `int32` promote to `float64` in NumPy (since not all int32's can be represented as float32).  So the result ends up at float64 making things slow (and requiring more RAM).

The solution is to make use `data / float(i)`.

I want to try to get rid of value based casting at some point, but I doubt it will happen for the next release.

**Comment by chrisbpoint** [comment]
Interesting, `data / float(i)` does avoid the issue indeed. Thanks a lot! Interesting to note that `data /= i` does not need `float(i)`, but probably there is a good explanation for this as well.

**Comment by rkern** [comment]
Yes, `data /= i` modifies `data` inplace using `np.divide(data, i, out=data)` so there is no upcasting because there's no intermediate that it needs to infer the output dtype for; you've already provided the output array with the desired dtype.

This doesn't seem like an actual leak, so I suggest that we can close.

**Comment by seberg** [comment]
That is in

**Comment by chrisbpoint** [comment]
I agree, it is not an actual leak but rather an unpleasant, unexpected behaviour. The original code is part of image averaging 
 (with the line`average = ((N-1)*average + data) / N`) and that is a really common operation. It took me quite a long time to spot this as the source for frame rate dropping and then I had no clue what was actually going on. So if there is no good reason why NumPy decides to suddenly upcast to float64 after `2**16 ` operations, I would recommend to change it in future releases. Anyway, my problem was solved. Thanks for the fast and efficient help!
