### ISSUE TITLE
MSVC2015 (14.0) Build error hexadecimal floating-point not support

### ISSUE THREAD

**Issue by WildRackoon** [numpy/numpy#19971]
Prior to version MSVC17 (15.3), hexadecimal floating-point are not supported.

Documentations states that MSVC is supported, but I am unsure wether MSVC2015 is, can you point me to relevant documentation ?

### Reproducing code example:

Build Numpy on MSVC2015

### Error message:

```
numpy\core\src\umath\loops_trigonometric.dispatch.c.src(41): error C2059: syntax error : 'bad suffix on number'
```

### NumPy/Python version information:

Numpy Version 1.21.0

**Comment by charris** [comment]
Hmm, interesting. Hex floats are a c99 thing and MSVC  2015 is not current enough to have them. The code in question is fairly recent, so this is a change. We do specify c99 compatibility and sufficient compatibility now seems to require MSVC 2017. It would be nice to know for sure that 2017 works :)

**Comment by rgommers** [comment]
We've used 2017 in CI before right? I'm not sure there's anything left to do here, can we close this?
