### ISSUE TITLE
arange sometimes includes "stop", sometimes not

### ISSUE THREAD

**Issue by leocus** [numpy/numpy#19989]
I found that when generating ranges with "arange", for the numbers smaller or equal than 15, it works properly, while from 16 onwards it includes the "stop" number.

### Reproducing code example:

```
>>> a = 15
>>> np.arange(a-0.5,a+.6,0.1)
array([14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4, 15.5])
>>> a = 16
>>> np.arange(a-0.5,a+.6,0.1)
array([15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6])
```

### Error message:
No error messages

### NumPy/Python version information:
Output from 'import sys, numpy; print(numpy._\_version__, sys.version):
1.21.0 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]

**Comment by charris** [comment]
The problem is that IEEE floating point cannot exactly represent those numbers. This is a well known problem that has come up many times before. The solution is to use `linspace`, or use integers that are scaled after the fact.
