### ISSUE TITLE
fft after ifft gives different phase result

### ISSUE THREAD

**Issue by thomasf10** [numpy/numpy#19991]
Starting from a frequency spectrum i take the np.fft.ifft of the spectrum in order to obtain the time signal. After that i want to go back to the frequency domain using np.fft.fft. However, this gives a different frequency spectrum than the one I started with. Namely, the phase is not consistent with the original spectrum.
Original spectrum: 
![image](https://user-images.githubusercontent.com/44842267/135106546-6697b407-0bad-4d16-b4eb-1239994f63c8.png)

Reconstructed spectrum:
![image](https://user-images.githubusercontent.com/44842267/135106637-015864a9-ee6f-4009-8bfd-529997e2e05b.png)

### Reproducing code example:

```python
import numpy as np
import matplotlib.pyplot as plt

#load the spectrum 
freq = 325.16* np.load("ofdm_freq.npy")

#plot the spectrum
plt.plot(np.abs(freq))
plt.title("magnitude")
plt.show()

plt.plot(np.angle(freq))
plt.title("phase")
plt.show()

#go to time domain:
n = 16384
time = ifft(fftshift(freq), n=n)

#go back to frequency domain
reconstructed_freq = fftshift(fft(time, n=n))

#plot reconstructed frequency
plt.plot(np.abs(reconstructed_freq))
plt.title("magnitude")
plt.show()

plt.plot(np.angle(reconstructed_freq))
plt.title("phase")
plt.show()


### NumPy/Python version information:
1.20.1



 The original spectrum can be found in the attachement bellow: 

[](ur
[ofdm_freq.zip](https://github.com/numpy/numpy/files/7244979/ofdm_freq.zip)
l)

**Comment by mreineck** [comment]
If I see correctly, the places where you get different phases are where your input spectrum is exactly 0. After `ifft` and `fft` these places conain small numerical noise and random phases, which is comlpetely expected.

**Comment by WarrenWeckesser** [comment]
I agree with @mreineck: the discrepancy is the result of the random phases of the numerical noise at the those frequencies where the original magnitude was zero.
