### ISSUE TITLE
REGRESSION: Casts from `np.double` to user-defined dtype fail since 1.21

### ISSUE THREAD

**Issue by mwallerb** [numpy/numpy#20009]
### Describe the issue:

Numpy allows us to register a custom dtype from the C API using `PyArray_RegisterDataType()`.  We use this in the [xprec] package to create a data type for software-emulated quadruple precision ("[double-double]") arithmetic.
Now, we also register a set of casts from and to standard numpy dtypes using `PyArray_RegisterCastFunc()`.

Here are links to the relevant code section in xprec for [register] and [cast].

Casting has some strange quirks (see also this perhaps [related issue]), but this has worked for us.  However, since 1.21, **casting fails** from `np.double` to our custom dtype.  All other casts still work.

[xprec]: https://github.com/tuwien-cms/xprec
[double-double]: https://en.m.wikipedia.org/wiki/Double-double_arithmetic
[related issue]: https://github.com/numpy/numpy/issues/14739
[register]: https://github.com/tuwien-cms/xprec/blob/mainline/csrc/_dd_ufunc.c#L520
[cast]: https://github.com/tuwien-cms/xprec/blob/mainline/csrc/_dd_ufunc.c#L641

### Reproduce the code example:

```python
import numpy as np

# our custom dtype
from xprec import ddouble

x = np.ones(3, dtype=np.float32)
x.astype(ddouble)  # works

x = x.astype(float)
x.astype(ddouble)  # fails since 1.21
```

### Error message:

```shell
TypeError: Cannot cast array data from dtype('float64') to dtype(ddouble) according to the rule 'unsafe'
```

### NumPy/Python version information:

1.21.2 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0]

**Comment by seberg** [comment]
The reason is that I added a new way to do casts, and that caches the result from the old one.  Somehow `register_ufuncs` or `register_dtype_in_dicts` calls `np.can_cast` (or similar) and then I cache that the cast is not defined.

What I have not figured out yet, is whether the assumption is just wrong, or the fact that somewhere `can_cast` is called means that there is another lingering bug anyway (and trying to fix it in NumPy is much less helpful).

I could remove that caching for now, the fix/work-around from your side is to define casts first, since they are more basic:
```diff
diff --git a/csrc/_dd_ufunc.c b/csrc/_dd_ufunc.c
index 80b22cd..b745a87 100644
--- a/csrc/_dd_ufunc.c
+++ b/csrc/_dd_ufunc.c
@@ -991,12 +991,12 @@ PyMODINIT_FUNC PyInit__dd_ufunc(void)
     PyArray_Descr *dtype = PyArray_DescrFromType(type_num);
     PyModule_AddObject(module, "dtype", (PyObject *)dtype);
 
+    if (register_casts() < 0)
+        return NULL;
     if (register_ufuncs() < 0)
         return NULL;
     if (register_dtype_in_dicts() < 0)
         return NULL;
-    if (register_casts() < 0)
-        return NULL;
     if (register_constants() < 0)
         return NULL;
```

**Comment by seberg** [comment]
> Casting has some strange quirks

Yes, my work on [NEP 41-43](https://numpy.org/neps/nep-0042-new-dtypes.html) will remove those quirks, although it will likely mean that you need to do a major overhaul of how your dtype is defined at some point.

**Comment by mwallerb** [comment]
@seberg
> I could remove that caching for now, the fix/work-around from your side is to define casts first, since they are more basic:

Thank you very much for the quick workaround!  I would *never* have found that out myself.

**Comment by seberg** [comment]
Thanks for the report, and sorry for the churn.

To be honest, I am tempted to just keep the new behaviour that you cannot modify the cast after it has been "used" (even for user dtypes).  Although, maybe I could add a warning when this happens.  Do you (or anyone else) have an opinion?

**Comment by mwallerb** [comment]
> To be honest, I am tempted to just keep the new behaviour that you cannot modify the cast after it has been "used" (even for user dtypes). Although, maybe I could add a warning when this happens. Do you (or anyone else) have an opinion?

I think, as long as it is transparent and **documented**, the current caching behaviour is fine.  Since I feel the current documentation of the C casting API is somewhat ... terse, this may be a good point to document that as well.  An additional warning would be a help to the users too...

BTW: since we are discussing dtypes - is there a way to register a dtype with `np.finfo`?

**Comment by seberg** [comment]
> I think, as long as it is transparent and documented

Yeah, one problem is that I am replacing all of that API (including how to create a dtype).  I admit, I never looked into improving the docs (nor am very motivated to improve them much).

> Somewhat of tangent since we are discussing dtypes - is there a way to register a dtype with np.finfo?

I would like to have more discussions like this, so any forum is great :).  We don't have a defined way, but I think it would be good to create one.  That probably means, we need to create a way to define an `finfo` instance by passing in all the special values (my guess is, by adding a classmethod).

Such a new classmethod can add the new object to the class cache and make `np.finfo(user_dtype)` work.  I don't think there is a reason to worry that this might break at some point, so I think we could just do that, whether the preferred way to do things may soon change or not.

For new DTypes, I would opt to moving towards defining `DType.finfo` as a property on the dtype (unfortunately I guess not for the class itself).  But even then, you would need the same classmethod, although the DType should do the caching in that case.
