### ISSUE TITLE
long double check is failing on GNU/Linux PPC (Trac #1403)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2001]
_Original ticket http://projects.scipy.org/numpy/ticket/1403 on 2010-02-21 by trac user mounir.lamouri, assigned to unknown._

Since 1.4.0, numpy doesn't work anymore on GNU/Linux PowerPC systems. Indeed, numpy.core is checking the long double type and PowerPC isn't supported.

Please, look at the attached build log.

**Comment by charris** [comment]
Judging by the last comments on #7836 this should be fixed for little endian. Apple was, I believe big endian and I don't know what the status of that is from actual report, but I think is should be OK.

**Comment by charris** [comment]
The ppc problems are being pursued elsewhere, so closing this.
