### ISSUE TITLE
numpy.linalg.eig unstable for symmetric matrices with non-distinct eigenvalues

### ISSUE THREAD

**Issue by TomDeWeer** [numpy/numpy#20012]
### Describe the issue:

As the title states, numpy.linalg.eig becomes unstable for symmetric matrices with non-distinct eigenvalues. The eigenvalues are accurate but the eigenvectors are not, whereas numpy.linalg.eigh (intended for symmetric matrices so also applicable here) achieves machine precision.

Could be that the interface to eig and eigh is slightly different or that I'm just not good at maths, but if that's not the case the problem lies with LAPACK: eig calls LAPACK's _geev routines whereas eigh calls _syevd, _heevd (according to numpy's documentation). 

If fixing the issue is not possible, at least an error should be thrown to prevent returning inaccurate results. 

### Reproduce the code example:

```python
import numpy as np
import scipy.linalg

A = np.array([[2., 1., 1.],
              [1., 2., 1.],
              [1., 1., 2.]])
D, P = np.linalg.eig(A)
Dh, Ph = np.linalg.eigh(A)
print(D)
print(Dh)
print(P-Ph)
error = np.linalg.norm(A - P.dot(np.diag(D)).dot(P.transpose()))
error_h = np.linalg.norm(A - Ph.dot(np.diag(Dh)).dot(Ph.transpose()))
print(error)
print(error_h)
```

### Error message:

```shell
Output: 

[1. 4. 1.]
[1. 1. 4.] -> eigenvalues are the same (but transposed)
[[-1.50284767  1.01960454 -0.90179311]
 [ 1.13442727  0.95062062 -1.06401453]
 [ 0.3684204  -0.23817435  0.23375684]] -> P - Ph is nonzero, so the eigenvectors are the issue
0.5619514869490163  -> LARGE ERROR
4.112323632166545e-15  -> MACHINE PRECISION
```

### NumPy/Python version information:

1.20.1 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]

**Comment by WarrenWeckesser** [comment]
There is no bug here.

* As you noticed, `eig` and `eigh` return the eigenvalues in different orders.  That means the corresponding eigenvectors in the columns of `P` and `Ph` are in different orders, so there is no reason to expect the values in `P - Ph` to be small.

*  In general, the eigenvectors for repeated eigenvalues computed by `eig` will not be mutually orthogonal.   `eig` does not "know" that `A` is symmetric, and its algorithm does not enforce or take advantage of this condition.  So `P.T` will not necessarily be the inverse of `P`, and the error computed by `np.linalg.norm(A - P.dot(np.diag(D)).dot(P.transpose()))` will not necessarily be small.
  Of course, the error computed by `np.linalg.norm(A - P.dot(np.diag(D)).dot(np.linalg.inv(P)))` *will* be small:
      `In [25]: np.linalg.norm(A - P.dot(np.diag(D)).dot(np.linalg.inv(P)))`
      `Out[25]: 1.8209011484034673e-15`
  which verifies that the eigenvalues and eigenvectors computed by `eig` are (to within normal floating point roundoff) correct.

**Comment by WarrenWeckesser** [comment]
Closing, but further comments are welcome, and if there is some other reason to suspect a bug, we can reopen the issue.
