### ISSUE TITLE
BUG: Iterating .npz files with duplicate keys yields unexpected output

### ISSUE THREAD

**Issue by luphord** [numpy/numpy#20033]
### Describe the issue:

[NPZ files](https://numpy.org/devdocs/reference/generated/numpy.lib.format.html) are zip archives and may contain *duplicate* entries. While [numpy.savez](https://numpy.org/devdocs/reference/generated/numpy.savez.html) prevents this by ensuring unique keys on the API level, it is easy to generate a .npz file with duplicate keys by other means, e.g. using [zipfile.ZipFile](https://docs.python.org/3/library/zipfile.html#zipfile-objects).

When iterating over such a .npz file via [NpzFile.items()](https://github.com/numpy/numpy/blob/c37b6af5577584f6ab0a08a161d9d657741341ea/numpy/lib/npyio.py#L104), duplicate keys are yielded multiple times, but always with the **last value stored**. It is not possible to retrieve previous values stored under that key (at least not using the `NpzFile` API) although they are contained in the zip archive.

I would expect one of these alternative behaviors for `NpzFile.items()`:

1. Yield a duplicate key only *once* (with the last value stored). This is consistent with the dictionary-like API of `NpzFile`, but discards content in the zip archive.
2. Yield the correct values stored with duplicate keys. This is consistent with the content of the zip archive, but somewhat at odds with the dictionary-like API.

If there is any interest, I can start contributing a PR for either behavior.

### Reproduce the code example:

```python
from zipfile import ZipFile
import numpy as np

# Generate data.npz with duplicate keys

with ZipFile("data.npz", "w") as zf:
    for a in ([1], [2, 2], [3, 3, 3]):
        with zf.open("duplicate_key.npy", "w") as f:
            np.save(f, a)

# Iterating over data.npz with NpzFile.items() yields the last value multiple times

for key, val in np.load("data.npz").items():
    print(key, val)

# Output:
# duplicate_key [3 3 3]
# duplicate_key [3 3 3]
# duplicate_key [3 3 3]

# But all three original values are still contained in zip file

with ZipFile("data.npz", "r") as zf:
    for info in zf.infolist():
        with zf.open(info) as f:
            print(info, np.load(f))

# Output:
# <ZipInfo filename='duplicate_key.npy' filemode='?rw-------' file_size=136> [1]
# <ZipInfo filename='duplicate_key.npy' filemode='?rw-------' file_size=144> [2 2]
# <ZipInfo filename='duplicate_key.npy' filemode='?rw-------' file_size=152> [3 3 3]
```

### NumPy/Python version information:

1.21.2 3.8.11 (default, Aug  3 2021, 15:09:35) 
[GCC 7.5.0]

**Comment by bashtage** [comment]
What about raising on duplicate keys?  If a file contains multiple keys with the same value then you know it wasn't produced using `savez`, and it would make sense to me that `load` should refuse to operate on files that could not have been produced by `savez`. Anyone who has a zipfile with the same key would then need to manually iterate and read the contents using `ZipFile`.

**Comment by luphord** [comment]
Yes, raising an exception on duplicate keys would be a clean approach and a clear commitment to a dictionary-like API. But it also breaks loading .npz files that loaded just fine until now. You don't think that's an issue?

I am not convinced by the argument "wasn't saved by `numpy.savez`, hence doesn't need to loaded by `numpy.load`". NPZ is a simple file format that can be produced by other applications / platforms / languages rather easily. Actually, I came across this behavior when exporting large arrays from a proprietary C# application for analysis in NumPy and Pandas. While I don't claim that this an argument in favor of supporting duplicate keys, I *do* think that loading .npz files which were *not* generated by `numpy.savez` has its merits.

**Comment by bashtage** [comment]
> Yes, raising an exception on duplicate keys would be a clean approach and a clear commitment to a dictionary-like API. But it also breaks loading .npz files that loaded just fine until now. You don't think that's an issue?

They loaded.  I wouldn't say they loaded "fine".  They loaded and possibly silently returned an array different from what the user thought she was getting.  I would also say these aren't really `npz` files, but are instead third party created zip files that are similar enough to npz files to not crash `load`.  

I agree that npz files should be able to be created by any application, and, as you say, are easy to make.  It would be helpful if there was a npz spec that had requirements of npz files, e.g., that keys must be unique.

FWIW I maintain pandas's Stata reader/writer.  It is based off a spec like https://www.stata.com/help.cgi?dta .  This help immensely when deciding what is permitted or not.

**Comment by luphord** [comment]
> They loaded. I wouldn't say they loaded "fine". They loaded and possibly silently returned an array different from what the user thought she was getting.

Agreed.

> Raising would let the user know that they need to manually open the NPZ to extract the array(s) that they want. This could be part of the error message.

Yes, that would be effective, at least for an interactive use case like data analysis in a Jupyter notebook. Not so much for a server application or data processing pipeline where the user has no access to the file. But as you say, the current behavior is not well defined either.

> At a minimum I think warning (KeyWarning or DuplicateKeyWarning ??) should be shown to users when there are duplicate keys in the zip file.

That is similar to what `ZipFile` does: printing a user warning when duplicate keys are written. Personally, I do not like a warning too much. Duplicate keys should either be supported in a well defined manner or they should be discarded. Warnings could be useful in a transitional state before a version that raises exceptions. In the sense of a deprecation warning I mean.

Unless someone else is worried about a breaking change, I think raising exceptions on duplicate keys is the way to go. I propose to contribute a PR that **checks for duplicate file entries [in the `__init__` method of `NpzFile`](https://github.com/numpy/numpy/blob/c37b6af5577584f6ab0a08a161d9d657741341ea/numpy/lib/npyio.py#L179) and raises an exception** in that case.

**Comment by luphord** [comment]
Fair point! I would vote for raising the exception in `__getitem__` then, as iterating the key without accessing the value does not do any damage. I would still do duplicate detection in `__init__` (but not raise an exception if any) and store duplicate keys in a member for performance reasons. `__init__` iterates all entries in the zip file anyway and `__getitem__` should not perform such an iteration.

BTW: Am I correct that file entries `foo` and `foo.npy` are ambiguous, too?

**Comment by BvB93** [comment]
> I would vote for raising the exception in `__getitem__` then, as iterating the key without accessing the value does not do any damage.

I'm not sure I agree with this statement. With mappings there is a reasonable expectation that a `for k in mapping.keys(): mapping[k]`-type pattern should work, which would obviously not be the case here. 
The most famous user of this would pattern would be the `dict` constructor, which would thus always raise when being passed an `NpzFile`.

**Comment by luphord** [comment]
It seems like a user warning in `__init__` is the maximum we can agree upon. Would you then leave current iteration behaviour unchanged? (i.e. duplicate key appears multiple times, always with the *last* value stored)
