### ISSUE TITLE
BUG: Missing 3.10 wheels for macOS

### ISSUE THREAD

**Issue by dhermes** [numpy/numpy#20045]
### Describe the issue:

Just a tracking issue here, sorry if this is a duplicate (I tried searching and didn't notice anything).

### Reproduce the code example:

```python
# N/A
```

### Error message:

```shell
# N/A
```

### NumPy/Python version information:

1.21.2

**Comment by charris** [comment]
Update (6:13 PM UTC): The images for 64 bit Python 3.10 are available on macOS and Windows. 32 bit Python 3.10 is missing from Windows, Python.h (3.10) is missing from macOS. Will check again later.

**Comment by memark** [comment]
The linked issue is now closed
https://github.com/actions/virtual-environments/issues/4226

Does this mean we can move forward here?

**Comment by mattip** [comment]
There are universal (fat) and arm64 wheels for NumPy 1.21.3 at https://pypi.org/project/numpy/#files. Do those fail to work for you? Progress on the x86_64 ones is waiting for https://github.com/multi-build/multibuild/pull/438.
