### ISSUE TITLE
PCG jump incorrectly emulates uint128 shift

### ISSUE THREAD

**Issue by runewalsh** [numpy/numpy#20048]
In [random/src/pcg64/pcg64.c](https://github.com/numpy/numpy/blob/fb2509ca6398e414a538c239e253395d554bf742/numpy/random/src/pcg64/pcg64.c), uint128 version (`PCG_EMULATED_128BIT_MATH` disabled) performs:
```c
delta /= 2;
```
uint64+64 version (`PCG_EMULATED_128BIT_MATH` enabled) emulates it with manual `delta >>= 1`ing:
```c
delta.low >>= 1;
delta.low += delta.high & 1;
delta.high >>= 1;
```
This is obviously incorrect and will screw up jumps by 2<sup>64</sup> or more (those with `delta.high != 0`). Must be rather:
```c
delta.low = (delta.low >> 1) | (delta.high << 63);
delta.high >>= 1;
```

**Comment by bashtage** [comment]
Definitely a bug.
