### ISSUE TITLE
BUG: numpy dies silently when converting a large array via .tolist()

### ISSUE THREAD

**Issue by FirefoxMetzger** [numpy/numpy#20041]
### Describe the issue:

When creating a large array and calling .tolist() on it numpy crashes silently ~~instead of emitting a out-of-memory exception~~. 

**Edit:** Monitoring the memory, it is actually not a memory problem. My memory usage slowly climbs up to around 30 GB for the python shell (45 GB in use total out of 64 GB available) and then the shell simply dies.

### Reproduce the code example:

```python
import numpy as np
x = np.arange(100000*100*100).reshape(-1, 100, 100)
y = x.tolist()
```

### Error message:

```shell
Killed
```

### NumPy/Python version information:

1.20.3 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]

**Comment by seberg** [comment]
I tried getting an idea where it actually gets killed, but didn't manage.

In any case, it is very unlikely there is anything we can do (or that this even happens in NumPy.  You are creating a gigantic list and a humongous amount of integer objects.  The kernel will over-allocate and then just kill the process when it realizes it doesn't actually have enough memory available.

I am not sure why this happens for you before you run out of memory, maybe something to do with your swap space?  (I don't have swap right now, it just kills when memory is full, as expected).

In any case, this also happens without the reshape, and I had a quick look at our code: The code looks good, if there is something wrong (and I doubt there is anything wrong), it would probably be Python not propagating some out of memory error.  But again, that is very unlikely.  Over-allocation will just lead to weird kills like this.

**Comment by FirefoxMetzger** [comment]
Thanks, @seberg for taking a look at it. 

If it doesn't seem like something is out of the ordinary, I will close this issue to keep things organized.
