### ISSUE TITLE
BUG: Compile numpy 1.19+ to webassembly gives function signature mismatch

### ISSUE THREAD

**Issue by leopsidom** [numpy/numpy#20079]
### Describe the issue:

I'm trying to compile numpy 1.19 / 1.20 / 1.21 to webassembly using pyodide, but get the following error:

>     wasm-ld: error: function signature mismatch: zungqr_64_
> 
>                 defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i64 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_litemodule.o
>                 defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i32 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/f2c_z_lapack.o

Can someone give a pointer what could be wrong ? **The build worked for 1.17 and 1.18**. I had tried to configure NPY_USE_BLAS_ILP64=0 environment variable based on this doc: https://numpy.org/doc/stable/user/building.html#bit-blas-and-lapack in hope of only compiling the 32 bit version. But it's still not working with the same error.

Note: there are multiple BLAS function names that throw this exception: https://github.com/numpy/numpy/blob/main/numpy/linalg/lapack_litemodule.c#L41. I just list one of them for example.

I have a suspicion it could be related to this commit: https://github.com/numpy/numpy/commit/669cd13c692cfe8476e24dad3d42bbbd94547727, but couldn't understand how it can cause the issue.

### Reproduce the code example:

```python
In pyodide, run:

> NPY_USE_BLAS_ILP64=0 PYODIDE_PACKAGES="numpy" make
```

### Error message:

> wasm-ld: error: function signature mismatch: dorgqr_64_
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i64 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_litemodule.o
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i32 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/f2c_d_lapack.o

wasm-ld: error: function signature mismatch: xerbla_64_
>>> defined as (i32, i32) -> i32 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/f2c_z_lapack.o
>>> defined as (i32, i32) -> i64 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/python_xerbla.o

wasm-ld: error: function signature mismatch: dgeqrf_64_
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32) -> i64 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_litemodule.o
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32) -> i32 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/f2c_d_lapack.o

wasm-ld: error: function signature mismatch: zgeqrf_64_
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32) -> i64 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_litemodule.o
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32) -> i32 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/f2c_z_lapack.o

wasm-ld: error: function signature mismatch: dgelsd_64_
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i64 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_litemodule.o
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i32 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/f2c_d_lapack.o

wasm-ld: error: function signature mismatch: zgelsd_64_
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i64 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_litemodule.o
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i32 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/f2c_z_lapack.o

wasm-ld: error: function signature mismatch: zungqr_64_
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i64 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_litemodule.o
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i32 in build/temp.linux-x86_64-3.9/numpy/linalg/lapack_lite/f2c_z_lapack.o

### NumPy/Python version information:

1.19+

**Comment by seberg** [comment]
Sorry, I mean tthe lapack lite code, it seemed to have a type called `integer`, which I assume matches `fortran_int`, but the return values in the file are not typed `integer` but are typed `int` which seems technically wrong.  The corresponding lapack-lite function to your function starts with `int` and not `integer`/`fortran_int` I think.

So it could be that the lapack-lite fortran to C translation step is not quite correct there.

**Comment by leopsidom** [comment]
Okay I think I found the commit that's causing the problem: https://github.com/numpy/numpy/commit/0159b84141a827e9e96df7ddf25c32c6df8dfb6d. It seems it's trying to build lapack-lite in 64 bit integer mode based on system information.

**Comment by seberg** [comment]
Compiling for 64bit seems good, but it seems a bit like the fix is not quite complete.

Since only the return value is broken (based on your errors), it may not be super surprising that this isn't causing mayhem. The return value is stored in a 64bit register in x86 calling convention (see e.g. [here](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-160#return-values)).  So it is effectively binary compatible (at least not on typical hardware).
I am a bit surprised that there is no compiler or linker warning though?

**Comment by leopsidom** [comment]
> Compiling for 64bit seems good, but it seems a bit like the fix is not quite complete

I guess the issue is webassembly currently only supports 32 bit not 64 bit mode so we don't want to build in 64 bit mode when compiling to wasm.

> only the return value is broken

Yeah this part is still  mysterious to me. I do not fully understand why the compiled function signature looks like that. It looks to me the arguments and return values types are not consistent.

> I am a bit surprised that there is no compiler or linker warning though?

There might be some but it's likely I'm not familiar enough with the build tool yet so I missed it somewhere. But I think the added lines in the `setup.py` file in the mentioned commit do look like the issue. i.e. if I comment it out. I was able to build it successfully.

**Comment by seberg** [comment]
Oh, what is `sys.maxsize > 2**32` during setup then?  It is correct, or would removing that addition to `setup.py` in 0159b84141a827e9e96df7ddf25c32c6df8dfb6d "fix" it?
Right now, I am still unsure if this is jus tthe wasm environment/compilation, or a general unnoticed problem (although it now sounds like it would be when compiling for 32bit).

**Comment by leopsidom** [comment]
Yep, removing the lines fix it. My guess here is that we are trying to build to 32 bit mode on a 64 bit machine which causes the issue. 

> although it now sounds like it would be when compiling for 32bit

Yeah, good point. Not sure if the same issue occurs when people try to compile to other 32 bit target on 64 bit machine.

**Comment by seberg** [comment]
So then, there is only a problem with cross compiling 32bit from a 64bit Python (with the fallback lapack).  I am not sure if that is supposed to work, or how you have to approach it anyway?  Is there a build flag that the `setup.py` could check for?

**Comment by leopsidom** [comment]
I'm not sure if there's a flag to disable that. Currently we are creating a patch to comment out the added lines before the compilation.

**Comment by seberg** [comment]
I feel it should be possible to probe the C compiler for the actual size in `numpy/linalg/setup.py`, which probably gives the correct cross compilation environment size.
The default `setup.py` of main NumPy does check/set up type sizes, but I am not familiar enough with distutils to figure out how to probe for the actual size there.

**Comment by seberg** [comment]
These issues are long fixed.
