### ISSUE TITLE
DOC: `divide` vs. `true_divide`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [numpy/numpy#20085]
### Issue with current documentation:

Currently, the docstrings of `numpy.divide`:and  `numpy.true_divide` are different:
https://github.com/numpy/numpy/blob/1eff1c543a8f1e9d7ea29182b8c76db5a2efc3c2/numpy/core/code_generators/ufunc_docstrings.py#L1064
https://github.com/numpy/numpy/blob/1eff1c543a8f1e9d7ea29182b8c76db5a2efc3c2/numpy/core/code_generators/ufunc_docstrings.py#L4014

Yet in the generated documentation, both [`numpy.divide`](https://numpy.org/doc/stable/reference/generated/numpy.divide.html) and [`numpy.true_divide` ](https://numpy.org/doc/stable/reference/generated/numpy.true_divide.html) use the dosctring of `numpy.true_divide`.

In a way, this does make sense, because in Python 3 `numpy.divide` is equivalent to `numpy.true_divide`. However:
1. I cannot find the mechanism which defines `numpy.divide` as an alias of `numpy.true_divide` in the documentation. Can someone help me with that?
2. Like the documentation of [`numpy.unicode_`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.unicode_):
   alias of [`numpy.str_`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.str_)
   I suggest the documentation of `numpy.divide` states it's an alias:
   alias of [`numpy.true_divide`](https://numpy.org/doc/stable/reference/generated/numpy.true_divide.html)

Finally, I'm not certain whether `divide` is an alias of `true_divide`, or `true_divide` an alias of `divide`. For example in `numpy/array_api/_elementwise_functions.py` I can find only `divide`, not `true_divide`:
https://github.com/numpy/numpy/blob/1eff1c543a8f1e9d7ea29182b8c76db5a2efc3c2/numpy/array_api/_elementwise_functions.py#L263-L274

**Comment by drosin** [comment]
As linked in `numpy/__init__.pyi`, np.divide and np.true_divide call the same function.

https://github.com/numpy/numpy/blob/d85523a7433baab1734a5436123cda9497124516/numpy/__init__.pyi#L3172
https://github.com/numpy/numpy/blob/d85523a7433baab1734a5436123cda9497124516/numpy/__init__.pyi#L3238

**Comment by drosin** [comment]
So, can we include in the documentation that divide is an alias for true_divide?

**Comment by rgommers** [comment]
We had a look at this together in the sprint:
- `divide` and `true_divide` are the same object
- There are two entries in `numpy/core/code_generators/ufunc_docstrings.py`, which means that the same docstring gets updated twice. Hence those two entries should be merged. Proposed to keep `'divide'` and put a comment above it that says that `true_divide` and `divide` are the same object, so this docstring is for both.
- While the ufunc is named `true_divide`, that's really for historical reasons. The `/` operator is the "divide" operator I'd say, that should be the preferred name. So in the examples, use `np.divide` and in the Notes section mention that `true_divide` is an alias.
