### ISSUE TITLE
Error importing NumPy 

### ISSUE THREAD

**Issue by danieleyny** [numpy/numpy#20108]
### Steps to reproduce:

I installed NumPy using `brew install numpy. It was able to download everything perfectly fine. From there I tried to run my python script and received an error. I am a beginner in the whole programming realm, any help would be greatly appreciated. 

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/daniel/Desktop/Code/Python/testcode.py", line 6, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

**Comment by seberg** [comment]
Installation problem without followup in a few months. I hope you found a solution, but as we do not provide `brew`, etc. these are not NumPy issues, so closing.  Matti had given some tips, hopefully they helped.
