### ISSUE TITLE
DOC: Strings containing a single null byte are equal to empty string

### ISSUE THREAD

**Issue by josteinbf** [numpy/numpy#20118]
### Describe the issue:

ndarrays containing strings that contain a single null byte, `'\x00'`, compare equal to empty strings. 

### Reproduce the code example:

```python
import numpy as np

print(f'numpy: {np.version.full_version}')

assert '\x00' != ''    # ok
assert np.all(np.array(['\x00']) != np.array(['']))     # fails
```

### Error message:

```shell
Traceback (most recent call last):
  File "----", line 9, in <module>
    assert np.all(np.array(['\x00']) != np.array(['']))
AssertionError
```

### NumPy/Python version information:

python: 3.9.7 (default, Sep  3 2021, 12:37:55) 
[Clang 12.0.5 (clang-1205.0.22.9)]
numpy: 1.21.2

**Comment by saranyadmdrn** [comment]
As part of Grace Hopper Open Source Day, I am looking into this.
