### ISSUE TITLE
DOC: Small grammar correction?

### ISSUE THREAD

**Issue by odros** [numpy/numpy#20122]
### Issue with current documentation:

The second Paragraph in [User Guide :: NumPy quickstart :: The Basics](https://numpy.org/doc/stable/user/quickstart.html#the-basics), seems to have an issue. It reads:  "For example, the coordinates of a point in 3D space [1, 2, 1] has one axis." 

Shouldn't it say "[...] _have_ one axis."? The subject is "the coordinates" in plural, hence -unless something escapes me, such as this being an instance of a noun with plural form but singular meaning- "have" would be the appropriate conjugation.

**Comment by HaoZeke** [comment]
I think perhaps the emphasis is meant to be on *a point*, as in a point with 3 coordinates corresponds to a single axis.

**Comment by rkern** [comment]
https://numpy.org/doc/stable/dev/howto-docs.html
