### ISSUE TITLE
BUG: sdist does not include the svml sources

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#20145]
### Describe the issue:

When building an sdist tarball, the svml sources are not included.

### Reproduce the code example:

```python
.
```

### Error message:

```shell
.
```

### NumPy/Python version information:

This should be fixed before the 1.22 release

**Comment by rgommers** [comment]
This is fixed. Removing the `umath/svml/` directory and then running `python setup.py sdist` gives:
```
...
RuntimeError: Missing `SVML` submodule! Run `git submodule update --init` to fix this.
```
And when the submodule is present on disk, it is included in the sdist.

**Comment by rgommers** [comment]
`check_submodules()` in `setup.py` safeguards that this will work.
