### ISSUE TITLE
DOC: Clarify behavior of np.lib.scimath.sqrt in the presence of negative 0

### ISSUE THREAD

**Issue by kurbobo** [numpy/numpy#20160]
### Idea or request for content:

In numpy.lib.scimath.sqrt we take square root of complex number and formally there are two sqrts of complex numbers.
I found out using this answer
https://github.com/numpy/numpy/issues/19484#issuecomment-880850940
In most cases sqrt with positive imaginary part is returned and only in case of complex(3.4, -0.0) is returned root with negative imaginary part, I think, it is good idea to right it explicitly in documentation to  numpy.lib.scimath.sqrt

**Comment by MuhammadMotawe** [comment]
Working on this as part of the PyDataGlobal 2021 NumPy-SciPy sprint

**Comment by HaoZeke** [comment]
You might consider augmenting the existing documentation with a note on FP numbers as in the comment and an example such as:

```python
In [1]: import numpy as np

In [2]: np.emath.sqrt(complex(-4.0, 0.0))
Out[2]: 2j

In [3]: np.emath.sqrt(complex(-4.0, -0.0))
Out[3]: -2j
```

Mention in the see also box as well that for complex inputs 0.0 and -0.0 are handled differently.
![image](https://user-images.githubusercontent.com/4336207/139541014-87f563cc-b453-4fd2-8428-8470791d9802.png)

**Comment by seberg** [comment]
Should have been closed when merging gh-20244.
