### ISSUE TITLE
CI: Cygwin failure tracking issue

### ISSUE THREAD

**Issue by charris** [numpy/numpy#20221]
The Cygwin testing has started failing. Cygwin version, 3.3.0-1, was released 10/28/2021, which might be related, hence this tracking issue. See https://tinyurl.com/ntz5fk9c for an example.

**Comment by mattip** [comment]
Reopening to ping @DWesl, cygwin started failing consistently

**Comment by DWesl** [comment]
My first guess is that the failures are related to a recent collision of the reference and optimized the BLAS libraries, but I think that would install one version or the other, which should only change speed, not results at the scale NumPy cares about (and not at the scale of the errors I saw).  

On a related note, are any of the other runners using [openblas 0.3.19](https://cygwin.com/pipermail/cygwin-announce/2021-December/010367.html), released [four days ago](https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.19)?  I can't think of any other problems that would primarily affect the solvers and would show up two days ago.

**Comment by mattip** [comment]
No, we have not yet updated to 0.3.19. Have there been any changes in mingw or the base image?

**Comment by mattip** [comment]
Note that setuptools (and its distutils) updated, but that should be pinned.

**Comment by DWesl** [comment]
> No, we have not yet updated to 0.3.19. Have there been any changes in mingw or the base image?

Not to my knowledge, but I haven't worked with Mingw anything for a few years, and even then most of my experience is with Cygwin's cross-compilers.  The relevant update would be to the Cygwin package repository, where a maintainer [uploaded an openblas 0.3.19 package two days ago](https://cygwin.com/pipermail/cygwin-announce/2021-December/010367.html).  If that's an issue, I can try to bully `setup-cygwin` into installing `libopenblas==0.3.18`.

> Note that setuptools (and its distutils) updated, but that should be pinned.

I know Cygwin's setuptools probably updated recently as part of the [python 3.9 rollout]https://cygwin.com/pipermail/cygwin-announce/2021-December/010365.html), but that would have been [fairly early in the process](https://cygwin.com/pipermail/cygwin-apps/2021-December/041750.html).  I also `pip install -r test_requirements.txt`, which does pin setuptools.

**Comment by DWesl** [comment]
I ran the linalg tests locally with OpenBLAS version 0.3.18 installed on Cygwin.  The tests in `numpy/linalg/tests/test_linalg.py` all passed.  I will check the results with OpenBLAS version 0.3.19 in a few days, but the main differences between my local setup and the runners are probably hardware age, OpenBLAS version, and a couple of the python packages that are newer on the CI setup than my local one.

**Comment by DWesl** [comment]
Given that [the Cygwin tests seem to be passing again](https://github.com/numpy/numpy/actions/workflows/cygwin.yml), should we close this?  Or are we waiting for #20669 to go in?

**Comment by seberg** [comment]
Yes, thanks for the heads-up, lets close this.
