### ISSUE TITLE
DOC: numpy.reshape used instead of np.reshape in absolute_beginners.html

### ISSUE THREAD

**Issue by albancolley** [numpy/numpy#20257]
### Issue with current documentation:

The absolute beginners documentation using the wrong module name - **numpy** - it should be np.

![image](https://user-images.githubusercontent.com/8863793/139601631-166055ad-8324-4f05-8e22-fa23cd07b082.png)

See pull request https://github.com/numpy/numpy/pull/20256

**Comment by WarrenWeckesser** [comment]
Fixed in https://github.com/numpy/numpy/pull/20256
