### ISSUE TITLE
BUILD: use cibuildwheel to upload wheels

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#20262]
Continuation of [#20102](https://github.com/numpy/numpy/pull/20102#issuecomment-955637886)

Now that we have a on-demand cibuildwheel process for x86, we should

- [ ] upload weekly to https://anaconda.org/scipy-wheels-nightly/numpy and https://anaconda.org/multibuild-wheels-staging/numpy for releases
- [ ] document the process at https://numpy.org/devdocs/dev/releasing.html
- [ ] add missing wheels for windows 32/~64~ ~and PyPy~ (window-64 done in PR 20383, PyPy done in PR 20565)

I think @charris would prefer to release the upcoming 1.22 via the current process, but once that is out we should move to this workflow.

@thomasjpfan thoughts?

**Comment by thomasjpfan** [comment]
Looks like a good plan to me. One more follow up item is to add Windows support.

**Comment by mattip** [comment]
Something seems off with the current situation. I see a button to trigger a wheel build when I go to https://github.com/numpy/numpy/actions/workflows/wheels.yml (others may not, depending on permissions). When I click the button, the action starts but only completes the version check, it does not build the wheels.

See https://github.com/numpy/numpy/actions/runs/1411885339

**Comment by thomasjpfan** [comment]
There was a typo with in `wheels.yml` fixed here: #20283

**Comment by mattip** [comment]
After manually [triggering a build](https://github.com/numpy/numpy/runs/4089363850?check_suite_focus=true), the macOS 3.10 build could not download python. The other builds ran to completion. At the bottom of the [summary page](https://github.com/numpy/numpy/actions/runs/1415587837) is a link to a single artifacts.zip that has all the successfully built wheels in it.

**Comment by thomasjpfan** [comment]
> After manually triggering a build, the macOS 3.10 build could not download python. 

I think that is an internet issue with either GitHub or python.org, which usually fixes itself. May you start the build again to see if it happens again?

**Comment by mattip** [comment]
I think the package was [pulled and then replaced](https://discuss.python.org/t/disappearing-macos-packages-on-python-org/11737). Weird.

**Comment by mattip** [comment]
The latest scheduled cibuildwheel [CI run](https://github.com/numpy/numpy/runs/4206747827?check_suite_focus=true) failed just now when built with commit `COMMIT_MSG='a181350 ENH: Add the linalg extension to the array_api submodule (#19980)'`. [The failure](https://github.com/numpy/numpy/runs/4206749335?check_suite_focus=true#step:3:371) is
```
creating build/src.macosx-10.9-x86_64-3.8/numpy/distutils
    INFO: building library "npymath" sources
    error: invalid argument '-std=c99' not allowed with 'C++'
```

and may have something to do with adding the flag unconditionally in `CIBW_ENVIRONMENT_MACOS` ?

**Comment by lithomas1** [comment]
My guess is that it is related to #20354 or #20353.

**Comment by seiko2plus** [comment]
@mattip,

> The latest scheduled cibuildwheel [CI run](https://github.com/numpy/numpy/runs/4206747827?check_suite_focus=true) failed just now when built with commit `COMMIT_MSG='a181350 ENH: Add the linalg extension to the array_api submodule (#19980)'`. [The failure](https://github.com/numpy/numpy/runs/4206749335?check_suite_focus=true#step:3:371) is
> 
> ```
> creating build/src.macosx-10.9-x86_64-3.8/numpy/distutils
>     INFO: building library "npymath" sources
>     error: invalid argument '-std=c99' not allowed with 'C++'
> ```
> 
> and may have something to do with adding the flag unconditionally in `CIBW_ENVIRONMENT_MACOS` ?

we need to validate any flags passed to env var `CFLAGS`, `CXXFLAGS` before passing it to the compiler, the current workaround is to filter it manually. try to add `-std=c99` to the following list.

https://github.com/numpy/numpy/blob/fc23679cc0da2716965279add044d323a02e2c42/numpy/distutils/misc_util.py#L2484

**Comment by lithomas1** [comment]
@mattip Do you know what the plans are for aarch wheels? I think we should build them too with cibuildwheel. 

One problem though is picking the CI provider. GHA doesn't have aarch64 IIRC, so we are left with CircleCI or Travis.

Another issue is synchronizing the builds. 

If the releases are triggered via a commit, then CI will all trigger at the same time, and we'll be fine.
Making CircleCI/Travis CI trigger from the workflow_dispatch button on Github Actions is gonna take a little more work/cleverness.

**Comment by nsoranzo** [comment]
@lithomas1 aarch wheels can be built on GHA using emulation, see https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation

**Comment by mattip** [comment]
I am a bit hesitant to commit to emulation for two reasons:
- emulating aarch64 on x86_64 will be really slow
- we depend on passing tests to prove everything works. We may get false positives (tests that fail on emulation but pass on real hardware) and will not be able to check NEON SIMD implementations.

But maybe for this wheel building step it will be "good enough". I think we already skip testing for the macos-arm64 wheels, since that is a cross-compile.

**Comment by lithomas1** [comment]
> I am a bit hesitant to commit to emulation for two reasons:
> 
> * emulating aarch64 on x86_64 will be really slow
> * we depend on passing tests to prove everything works. We may get false positives (tests that fail on emulation but pass on real hardware) and will not be able to check NEON SIMD implementations.
> 
> But maybe for this wheel building step it will be "good enough". I think we already skip testing for the macos-arm64 wheels, since that is a cross-compile.

I agree here. I don't think we should emulate when free CI is available(which isn't available for macos arm64). It's probably not that bad to split wheel-building across two providers, given that cibuildwheel supports Travis/Circle too.
