### ISSUE TITLE
DOC: The documentation of numpy.ma.mean refers to numpy.mean which has different dtype behavior

### ISSUE THREAD

**Issue by canol** [numpy/numpy#20272]
### Issue with current documentation:

After a brief introduction, `numpy.ma.mean` documentation says "Refer to `numpy.mean` for full documentation." which implies that `numpy.mean` parameters behave similarly to `numpy.ma.mean` parameters:

https://numpy.org/doc/stable/reference/generated/numpy.ma.mean.html

But the dtype argument in `numpy.ma.mean()` has a different behavior than `numpy.mean` and it is more prone to overflow errors. When no explicit data type is provided, `numpy.mean` uses `float64` for integer types by default which prevents overflows, whereas `numpy.ma.mean` uses either `int32` or `uint32` depending on the sign of the original array. This is because `numpy.ma.mean` uses `numpy.sum()` internally which has the said behavior with dtype parameter.

This behavior can easily cause overflow errors when `numpy.ma.mean` is not used carefully, especially for somebody who is used to the `numpy.mean` behavior.

For example this code demonstrates the problem (Python 3.8.6, 64-Bit, Windows):

```
import numpy as np
from numpy.ma import MaskedArray

a = np.full((10000, 10000), 65535, dtype=np.uint16)
print(a.mean())  # Output: 65535.0

a_masked = MaskedArray(a, np.zeros(a.shape))
print(a_masked.mean())  # Output: 36.748736
```

As you can see, the outputs of `a.mean()` and `a_masked.mean()` are different even though no element is masked in the masked array.

Giving explicit dtype in `numpy.ma.mean`, which wouldn't overflow, makes it possible to get the correct mean value:

```
a_masked.mean(dtype=np.float64)  # Output: 65535.0
```

### Idea or request for content:

Adding an explanation on the difference of the dtype parameter of `numpy.ma.mean` would be useful to prevent mistakes and prevent giving the user wrong impression that both dtype parameters behave exactly the same.

**Comment by dhivyasreedhar** [comment]
Hi, Can I work on this ?

**Comment by Mukulikaa** [comment]
Hey @dhivyasreedhar, NumPy doesn't assign any issues so feel free to work on whatever you like without permission! You can have a look at the [Contributors' Guide](https://numpy.org/devdocs/dev/index.html) to get started and please don't hesitate to ask doubts.
