### ISSUE TITLE
BUG: einsum all zero for float16

### ISSUE THREAD

**Issue by joergdietrich** [numpy/numpy#20305]
### Describe the issue:

Starting with numpy-1.21.0 (at least some) einsum operations for arrays with dtype=np.float16 yield all zero results.

### Reproduce the code example:

```python
import numpy as np

a = (np.linspace(0, 301, 300).reshape(10, 10, 3) / 301).astype(np.float16)
mat = np.array([[0.39, 0.54, 0.0089], [0.07, 0.96, 0.001], [0.02, 0.13, 0.94]], dtype=np.float16)
assert np.all((a @ mat.T) != 0)
assert np.all(np.einsum("ij, ...j", mat.astype(np.float32), a.astype(np.float32)) != 0)
assert np.all(np.einsum("ij, ...j", mat, a) != 0)
```

### NumPy/Python version information:

1.21.2 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0]

**Comment by seberg** [comment]
@Qiyu8 could  you have a look at this?  This seems possibly related to the einsum SIMD refactor.

**Comment by ogrisel** [comment]
Here is a more minimal reproducer (executed on 1.21.2):

```python
>>> import numpy as np
>>> a = np.array([1.764 , 0.4001], dtype=np.float16)
>>> np.einsum("i,i->", a, a)
1.0
>>> (a ** 2).sum()
3.271
```

the same code works fine on numpy 1.20.3.

**Comment by seberg** [comment]
Turns out the `temptype` usage is spotty in the new code, which would affect only float16.   Have to look into the tests it feels like they should have noticed at least some of this...
