### ISSUE TITLE
Errors using to_array() or (numpy.ndarray) to obtain  raw simulation results .

### ISSUE THREAD

**Issue by teddiclax** [numpy/numpy#20319]
Good day,
I have a model developed using a certain python module for simulating polymer reactions. For instance,I intend to manipulate the resulting string to obtain specific plots. Here the species(or variables were defined:
class StyrenePolymerization(Model):
    def __init__(self, MAX_N=20):
        #
        Model.__init__(self, name="StyrenePolymerization")

        # First, choose a maximum value for the states
        max_state = MAX_N
        print(f"Creating Styrene Polymerization model, MAX_N={MAX_N}")
        # Create Species for all states
        # Variables
        self.add_species(Species(name="I", initial_value=49, mode="discrete"))
        self.add_species(Species(name="R", initial_value=0, mode="discrete"))
        self.add_species(Species(name="M", initial_value=51, mode="discrete"))
        for n in range(1,max_state):
            self.add_species(Species(name=f"P{n}", initial_value=0, mode="discrete"))
            self.add_species(Species(name=f"D{n}", initial_value=0, mode="discrete"))
Here,I intend to obtain a specific plot of conversion,X(X = (M0 - M) / M0) versus the number of chains,n as shown:

MAX_N=10
max_state = MAX_N
for index in range(0, 10):
    for n in range(1,max_state-1):
        np1 = n+1
        s_trajectory = s_result[index]
        d_trajectory = d_result
        plt.plot(s_trajectory['n'], s_trajectory['X'], 'r')
        plt.plot(d_trajectory['n'], d_trajectory['X'], 'k')
        plt.xlabel('Time')
        plt.ylabel('Momoner,M')
        plt.title('Monomer Conversion')

Please, I need the right code or pseudocode (as a headstart) to resolve the problem.
Note: when I invoke for instance the f-string:f"D{nm}" it gives me chain ; D1,D2...

**Comment by rkern** [comment]
We use the issue tracker here to track bug reports and feature requests for numpy development. I'm afraid that we can't use this helpfully to answer usage questions.

You may be able to ask for some help on the [numpy-discussion mailing list](https://mail.python.org/mailman3/lists/numpy-discussion.python.org/) or other forums, but you will have to describe your problem in much more detail before anyone will be able to offer useful advice. You haven't shown us the part of the code that actually uses numpy or the actual error that you refer to in the title. What have you tried? What output are you getting? What output were you expecting? Can you reduce your example down to a small complete snippet of code that reproduces the problem that someone else can run without installing the rest of your code (e.g. `Model`)?

**Comment by teddiclax** [comment]
Thank you for the swift response;
This is what I did. I may be wrong as my programming skill is low.

import numpy as np
np.fromstring('1 ,2', dtype=int, sep='')
np.ndarray(f"(D){n}")
Here is the error message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-a8cc0d23a840> in <module>
----> 1 np.ndarray(f"(D){n}")

TypeError: 'str' object cannot be interpreted as an integer

This is what I intend to solve:
max_state=100
M0=104
D=104;
for n in range(1,max_state-1):
      Ws=(n**2)*(M0**2)*(f"D{n}")
print(Ws)

**Comment by rkern** [comment]
It's not clear to me why you want to make an array from some kind of string. That doesn't seem to be related to plotting the conversion `X` (a number) against `n` (also a number). There are ways to use strings in/as arrays, but I can't advise on the right one because I can't infer what you actually want to achieve by doing so.
