### ISSUE TITLE
BUG: missing Windows wheel for Python 3.10

### ISSUE THREAD

**Issue by danielhrisca** [numpy/numpy#20320]
### Describe the issue:

The recent 1.12.4 release on PyPI is missing the Windows wheels for Python 3.10 

### Reproduce the code example:

```python
pip install numpy
```

### NumPy/Python version information:

1.12.4

**Comment by charris** [comment]
What Python version? Are you running a 32 bit Python?

**Comment by danielhrisca** [comment]
I am using 64 bit Python

**Comment by mattip** [comment]
The recent release was 1.21.4 not 1.12.4, and there are [windows wheels available](https://pypi.org/project/numpy/#files). You should always get some kind of response from `pip install numpy`. If the command does not exists you should see `"'pip is not recognized as an internal or external command`. If the package does not exist you should see `ERROR: Could not find a version that satisfies the requirement`

**Comment by aivarannamaa** [comment]
> Are you running a 32 bit Python?

@mattip, has it been decided to stop publishing win32 wheels? 1.21.4 currently misses win32 wheel for Python 3.10. Will it stay this way?

I'm confused, because https://www.mail-archive.com/numpy-discussion@python.org/msg05512.html says:

> We will continue to offer 32 wheels on Windows as it remains popular there.

**Comment by danielhrisca** [comment]
Sorry for wasting your time, I had a failed pip install but this was caused by `h5py` requiring an older `numpy` version that did not have 3.10 wheels. This can be closed

**Comment by liudonghua123** [comment]
I find that there is only numpy-1.22.3-cp39-cp39-win32.whl, numpy-1.22.3-cp38-cp38-win32.whl exists, numpy-1.22.3-cp310-cp310-win32.whl is missing on https://pypi.org/project/numpy/#files.
