### ISSUE TITLE
BUG: np.linalg.eig gives invalid eigenvectors

### ISSUE THREAD

**Issue by stephen-huan** [numpy/numpy#20322]
### Describe the issue:

numpy gives an invalid eigenvector for the matrix
```text
A = [[1, 1, 1],
     [0, 1, 0],
     [0, 0, 1]]
```
Analytically, the eigenvectors should be some linear combination of (1, 0, 0) and (0, -1, 1). However, numpy returns the vector (1, -1, -1) which is not a valid left or right eigenvector (neither `A@v` nor `v.T@A` is a scalar multiple of `v`). 

Many similar matrices seem to exhibit similar problems, e.g.
```
A = [[1, 0, 1], [0, 1, 0], [0, 0, 1]]
A = [[0, 1, 0], [0, 0, 0], [0, 0, 0]]
```
and so on

I thought it might be the result of some macOS/LAPLACK interaction, so I also tested on both macOS 11.6 and Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-153-generic x86_64).

### Reproduce the code example:

```python
import numpy as np
A = np.array([[1, 1, 1], [0, 1, 0], [0, 0, 1]])
# first "eigenvector" returned by eig
# should have eigenvalue 1, i.e. A@v = v
v = np.linalg.eig(A)[1][0]
print(v)     # array([ 1., -1., -1.])
print(A@v)   # array([-1., -1., -1.])
print(v.T@A) # array([ 1.,  0.,  0.])
```

### NumPy/Python version information:

1.19.5 3.8.5 (default, Aug  4 2020, 23:23:15) 
[Clang 10.0.0 ]

also tested on

1.21.4 3.8.5 (default, Aug  4 2020, 23:23:15) 
[Clang 10.0.0 ]

and 

1.19.5 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]

**Comment by charris** [comment]
The eigenvectors are in the columns, but it looks like it didn't find (0, 1, -1).

**Comment by stephen-huan** [comment]
oh that's embarrasing, I misread the array as a Python list of vectors.
sorry for the trouble, I'll read the documentation more carefully next time.

**Comment by charris** [comment]
> but is is the fact that it did not find the other eigenvector still an issue?

I think so. Where did you get NumPy?

**Comment by stephen-huan** [comment]
In both instances, from pip. Quick testing with miniconda has the same problem.
Also, both scipy and pytorch have the same issue, so I suspect
the issue is with the backend (LAPLACK?) rather than numpy:

```python
import numpy as np

A = np.array([[1, 1, 1], [0, 1, 0], [0, 0, 1]])
np.linalg.eig(A)[1]
array([[ 1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-16]])

import scipy.linalg

scipy.linalg.eig(A)
array([[ 1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-16]])

import torch

torch.eig(torch.Tensor(A), eigenvectors=True)[1]
tensor([[ 1.0000e+00, -1.0000e+00, -1.0000e+00],
        [ 0.0000e+00,  1.1921e-07,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.1921e-07]])
```

**Comment by charris** [comment]
That's interesting. We should check the reference LAPACK functions and see if that is documented.

**Comment by WarrenWeckesser** [comment]
The matrix A id [defective](https://en.wikipedia.org/wiki/Defective_matrix).  Either by hand, or with SymPy as follows:
```
In [140]: A = np.array([[1, 1, 1], [0, 1, 0], [0, 0, 1]])

In [141]: from sympy import Matrix

In [142]: M = Matrix(A)

In [143]: P, J = M.jordan_form()

In [144]: J
Out[144]: 
Matrix([
[1, 1, 0],
[0, 1, 0],
[0, 0, 1]])
```
a Jordan normal form for A can be found.  The eigenvalue 1 has algebraic multiplicity 3 and geometric multiplicity 2.  I don't think the LAPACK eigenproblem solvers make any promises about their results when the input is a defective matrix.
