### ISSUE TITLE
BUG,ENH: DLPack will refuse to export certain strided arrays that could be exported

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#20336]
The following array cannot be exported by DLPack currently, but would be valid.  This is very obscure though:
```
# Not contiguous array (and not size 1) which has strides that along a dimension of size 1, so that they do not matter:
arr = np.ndarray(dtype="f8", strides=(4, 8), shape=(1, 10), buffer=np.ones(1000, dtype="uint8"))
arr.__dlpack__()  # could be exported, but fails.
```
I expected it to be easier to achieve, but `arr.view` only works with C-contiguous arrays. 

EDIT: Honestly, if someone ever is tempted to just close this, fine with me (although fixing is probably also easy).

**Comment by tirthasheshpatel** [comment]
Your example works for me. The `strides % itemsize` check is only done for non-contiguous arrays. But this fails, for example:

```python
>>> x = np.ndarray(dtype='f8', shape=(10,5,1), strides=(8,80,4), buffer=np.ones(1000, dtype=np.uint8), order='F')
>>> y = np._from_dlpack(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: DLPack only supports strides which are a multiple of itemsize.
```

But it'd be nice to be able to export arrays that only have one element in some dimension.
