### ISSUE TITLE
DISCUSS: DLPack imports arrays readonly, but only exports writeable

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#20337]
The current implementation of DLPack always imports arrays readonly (they may come e.g. from JAX which is immutable), and only exports writeable arrays (since NumPy arrays are normally writeable anyway).

This is the strictest possible choice with respect to readonly data, and a change could be considered (or this issue closed and we stick with the current behaviour).  CC @rgommers.

**Comment by rgommers** [comment]
I think importing readonly is nice: it's quite safe, should not interfere with most normal user code, and in case it does the user can consciously flip the writeable flag.

Refusing to export readonly arrays should be fine in practice. JAX made a different choice here (just export, place responsibility on the user) but they're in a different situation - _all_ their arrays are readonly. NumPy users have very few readonly arrays, and if they encounter an issue they can work around it. So should be fine too imho.

**Comment by seberg** [comment]
OK, closing the issue immediately. Just thought I would float/bring it up once.  If anyone disagrees they can open a new one/reopen.

**Comment by rgommers** [comment]
Agreed, good idea to have a record - if anyone has other thoughts, please reopen.
