### ISSUE TITLE
BUG: Gitpod setup is failing to set proper development tag on main branch

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy#20346]
### Describe the issue:

When pulling up gitpod on main, the build fails with `RuntimeError: Cannot parse version 0+untagged.1.g693e22d`.

This looks like the problem described in #20170

### Reproduce the code example:

```python
Open gitpod on the main branch.
```

### Error message:

```shell
HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
mkdir -p .vscode
cp tools/gitpod/settings.json .vscode/settings.json
conda activate numpy-dev
python setup.py build_ext --inplace
echo "🛠 Completed rebuilding NumPy!! 🛠 "
echo "📖 Building docs 📖 "
cd doc
make html
echo "✨ Pre-build complete! You can close this terminal ✨ "

}
(numpy-dev) gitpod > /workspace/numpy $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> mkdir -p .vscode
> cp tools/gitpod/settings.json .vscode/settings.json
> conda activate numpy-dev
> python setup.py build_ext --inplace
> echo "🛠 Completed rebuilding NumPy!! 🛠 "
bash: !!: event not found
> echo "📖 Building docs 📖 "
> cd doc
> make html
> echo "✨ Pre-build complete! You can close this terminal ✨ "
> 
> }
Traceback (most recent call last):
  File "/workspace/numpy/setup.py", line 59, in <module>
    raise RuntimeError(f'Cannot parse version {FULLVERSION}')
RuntimeError: Cannot parse version 0+untagged.1.g693e22d
📖 Building docs 📖 
fatal: No tags can describe '693e22daf8cd0c8fb5789b3b735cfb50309ac409'.
Try --always, or create some tags.
numpy not found, cannot build documentation without successful "import numpy"
make: *** [Makefile:91: version-check] Error 1
✨ Pre-build complete! You can close this terminal ✨ 
(numpy-dev) gitpod > /workspace/numpy/doc $
```

### NumPy/Python version information:

Cannot import numpy.

**Comment by melissawm** [comment]
cc @MarsBarLee

**Comment by MarsBarLee** [comment]
To elaborate on my experiences, this failure to build happened to me starting this week. Some other error messages I've seen are:
```
fatal: no tags can describe 'e869233...'  (the most recent commit's SHA-1)
```
or
```
numpy not found, cannot build documentation without succesful "import numpy"
```
or
```
make: *** [makefile:91 version-check] Error 1
```

**Comment by HaoZeke** [comment]
I wonder if this has anything to do with the branching of the latest version.

**Comment by melissawm** [comment]
It does, updating the tags solves the problem. I'm just not sure how to rebuild (?) the docker image for gitpod.

**Comment by HaoZeke** [comment]
I think the image is being pulled from [the DockerHub](https://hub.docker.com/r/numpy/numpy-gitpod/tags). Also it seems like GitPod only rebuilds if the [Gitpod yml docker key](https://community.gitpod.io/t/how-to-force-a-docker-build/1442) is changed. It doesn't make sense since the DockerHub image is definitely up to date..

Perhaps just changing the Gitpod yml to an older tagged DockerHub image and then changing it back to `latest` would work?

**Comment by melissawm** [comment]
Ah so from the DockerHub link you sent, maybe the image is only generated when the commit hits `main`- so the only way to test locally is to rebuild the docker image locally (I was trying to do this in a branch).

**Comment by rgommers** [comment]
That's correct (about testing).
