### ISSUE TITLE
BUG,ENH: DLPack tries to export the imported "device" information but can fail

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#20340]
The current implementation does not follow the device information fully.  Imagine a Cuda pinned memory allocation being imported:
```
cuda = memoryview(np.arange(100))  # not cuda, but for purposes of showing
arr = np._from_dlpack(cuda)
arr.base is cuda
view = arr[::2]
view.base is arr  # not cuda anymore
```
In this scenario, the current code will set the dlpack device to the cuda pinned memory for `arr.__dlpack__()` but not for `view.__dlpack__()`.  This could be fixed by walking the bases (if they are `ndarray`).  The writeable flag also walks bases in this manner.

**Comment by mattip** [comment]
The example doesn't work, but I think we changed the code to handle this idea properly, no?

**Comment by seberg** [comment]
No, we don't walk the bases, but we could.  Seems like a small thing though, I guess.
