### ISSUE TITLE
BUG: `__import__(numpy).__file__` is `None`

### ISSUE THREAD

**Issue by fAndreuzzi** [numpy/numpy#20355]
### Describe the issue:

I'm trying to run the benchmarks on **Python 3.8.5** with the command `python3 runtests.py --bench-compare main`, but I get an error.

It looks like `__import__('numpy').__file__` is `None`.

### Reproduce the code example:

`python3 runtests.py --bench-compare main`

### Error message:

```shell
Traceback (most recent call last):
  File "runtests.py", line 699, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 202, in main
    site_dir = os.path.sep.join(_temp.__file__.split(os.path.sep)[:-2])
AttributeError: 'NoneType' object has no attribute 'split'
```

### NumPy/Python version information:

Branch `main` of the development version of NumPy.

Python 3.8.5

**Comment by LeonaTaric** [comment]
emmmmmm，what if other branches?

if other branches fail too, maybe it's bug of python3.8, not numpy. 


If you really want to run test, I think you know (or can guess) the value of "site_dir".

force change the value and test.
