### ISSUE TITLE
REL: mailmap update.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#20359]
I am updating mailmap for the NumPy 1.22.0 release. It would be helpful if the following folks could reply to this issue with a full name and their preferred email address so that they can be properly credited as contributors to the release.

- [x] @NectDz
- [x] @himanshu007-creator
- [x] @bdvd
- [x] @default-303
- [x] @iameskild
- [x] @lalitmusmade
- [x] @serge-sans-paille
- [x] @shubham11941140
- [x] @Schleehauf 
- [x] @vinith2
- [ ] @yan-wyb

**Comment by NectDz** [comment]
Name: Kevin Granados
Email: kevingranados62@gmail.com

**Comment by default-303** [comment]
Hey there!!

Name: Ajay DS
email: turingman@protonmail.com

**Comment by himanshu007-creator** [comment]
Name: Himanshu
Email: addyjeridiq@gmail.com

**Comment by serge-sans-paille** [comment]
Name: Serge « sans paille » Guelton
Email: serge.guelton@telecom-bretagne.eu

**Comment by iameskild** [comment]
Hey @charris, thanks for the ping. The [PR I submitted](https://github.com/numpy/numpy/pull/19244) was a joint effort by @ImenRajhi :)

Name: Eskild Eriksen
Email: eskild.eriksen122@gmail.com

**Comment by bdvd** [comment]
Name: David Bodnar
Email: bdvd001@gmail.com

**Comment by charris** [comment]
> The PR I submitted was a joint effort by @ImenRajhi 

Already have ImenRajhi.

**Comment by lalitmusmade** [comment]
Name : Lalit M
Email : lalitmusmade2@gmail.com

**Comment by Schleehauf** [comment]
Sebastian Schleehauf 

***@***.***

**Comment by vinith2** [comment]
Name: Vinith Kishore
email: vinith.kishore@unibas.ch

**Comment by rgommers** [comment]
I see all these names in the 1.22.0 announcement on the mailing list, so this can be closed. Thanks everyone!

**Comment by yan-wyb** [comment]
Name: Yan
email: yan-wyb@foxmail.com
