### ISSUE TITLE
BUG:  /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by eljequercin** [numpy/numpy#20371]
### Describe the issue:

Hello, I have been struggling with a problem when trying to import numpy in my raspberry pi 4.

I have updated GLIBC to 2.29 to try to use numpy but there is no option it always drops me the same message

### Reproduce the code example:

```python
import numpy
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /home/pi/.local/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-arm-linux-gnueabihf.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/Bots/CMS BOTS/BOT.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 28, in <module>
    import numpy as np
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/local/bin/python3"
  * The NumPy version is: "1.21.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /home/pi/.local/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-arm-linux-gnueabihf.so)
```

### NumPy/Python version information:

1.21.4 / 3.9.5

**Comment by mattip** [comment]
What os and version of that os are you running (hint: it is usually in `/etc/lsb-release`)

**Comment by eljequercin** [comment]
Raspbian version 10

**Comment by mattip** [comment]
Raspbian version 10 is based on debian 10, which uses glibc 2.28. You cannot update easily update glibc. We build the aarch64 wheels on PyPI for manylinux2014, which is based on glibc 2.17. I see you are trying to load `cpython-39-arm-linux-gnueabihf.so`, which is a 32-bit c-extension module. This project does not provide 32-bit packages. You should reach out to whoever is providing your numpy.

**Comment by JettJengaGod** [comment]
Is there a different version of numpy which does work on Rasbian 10?

**Comment by mattip** [comment]
I can only answer with another question: where did you get numpy from? If you did `pip install numpy`, please note carefully what source the package is downloaded from. If it is piwheels, you may have more luck on their [issue tracker](https://github.com/piwheels/packages/issues)

**Comment by mattip** [comment]
From the table at the bottom of the [piwheels page](https://www.piwheels.org/), they have support for specific python versions for each Raspian version. It seems you are trying to use the wrong python version (3.9) for Raspian 10 (Buster). 

Raspian/debian nickname | number | python support
---|---|---
Buster | 10 | Python 3.7
Bullseye  | 11 | Python 3.9

**Comment by JettJengaGod** [comment]
> From the table at the bottom of the [piwheels page](https://www.piwheels.org/), they have support for specific python versions for each Raspian version. It seems you are trying to use the wrong python version (3.9) for Raspian 10 (Buster).
> 
> Raspian/debian nickname	number	python support
> Buster	10	Python 3.7
> Bullseye	11	Python 3.9

This is really helpful, thanks!
I'll downgrade my python version and see if that works!

**Comment by JettJengaGod** [comment]
Downgrading to python 3.7 worked like a charm. Just pip installed numpy and it works. Thanks again for the help!
