### ISSUE TITLE
DOC: The np.ma.average documentation does not account for cases where weights contain np.nan.

### ISSUE THREAD

**Issue by Junyeopp** [numpy/numpy#20375]
### Issue with current documentation:

If the input weights array contains `np.nan`, `ma.average` returns `np.nan` even if `np.nan` is in a masked position in the input array.
In the example code below, the `np.nan` in weights is in a masked position in the input array, and it returns `np.nan`

```python
np.ma.average(
    np.ma.array([1., 2., 3., 4.], mask=[False, False, True, True]),
    weights=np.array([1, 1, 1, np.nan]),
    returned=True
)
```

It seems that the `np.nan` in the masked position doesn't need to be summed in this [code](https://github.com/numpy/numpy/blob/v1.21.0/numpy/ma/extras.py#L623).
However, in this [line](https://github.com/numpy/numpy/blob/v1.21.0/numpy/ma/extras.py#L620-L621), `np.nan` is passed regardless of the mask.

Is this situation intentional? Or is it something that needs to be fixed?
If intended, how about adding an example or additional explanation for this situation?

**Comment by scratchmex** [comment]
I think the problem is that a masked `nan` value multiplied by a scalar stills gives you a `nan`.

**Comment by scratchmex** [comment]
I have a solution. Make `wgt` a masked array and attach the mask to it if `a` also have a mask:
```python
>>> wgt = np.array([1, 1, 1, np.nan])
>>> a = np.ma.array([1.0, 2.0, 3.0, 4.0], mask=[False, False, True, True])
>>> wgt = np.ma.asanyarray(wgt)
>>> wgt.sum()
nan
>>> wgt.mask = a.mask
2.0
>>> wgt.sum()
```

I will make a PR

**Comment by Junyeopp** [comment]
@scratchmex
I checked your PR and it works as expected. Thank you for PR!
