### ISSUE TITLE
BUG: removal of `mask` copy code may have broken matplotlib test

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#20372]
A matplotlib test may have been broken by the PR gh-19102 which ended up removing this snippet:
```
        # Backwards compatibility w/ numpy.core.ma.
         if hasattr(data, '_mask') and not isinstance(data, ndarray):
             _data._mask = data._mask
             # FIXME _sharedmask is never used.
             _sharedmask = True
```
From Masked arrays `__new__`.

_Originally posted by @tacaswell in https://github.com/numpy/numpy/pull/19102#discussion_r748914600_

**Comment by tacaswell** [comment]
This appears to have broken a Matplotlib test (xref https://github.com/matplotlib/matplotlib/issues/21632).  I am not sure yet if the broken test represents something that is real and will bite users or if it is something about our fake unit-wrapper in the test suite.

**Comment by dopplershift** [comment]
This is definitely a real issue that affects how the [Pint](https://github.com/hgrecco/pint) library behaves with masked data:
```python
import numpy as np
import pint

ureg = pint.UnitRegistry()
Quantity = ureg.Quantity

data_masked = np.ma.array([1, 2, 3], mask=[True, False, True])
data_masked_units = Quantity(data_masked, 'meters')

print(np.ma.asarray(data_masked_units, float))
```
On 1.21.4, this prints:
```
[-- 2.0 --]
```
On `main`:
```
[1. 2. 3.]
```

Or if you want to reproduce without `pint`, use this implementation of `Quantity`:
```python
class Quantity:
    def __init__(self, data, units):
        self.magnitude = data
        self.units = units

    def __getattr__(self, attr):
        return getattr(self.magnitude, attr)
```
