### ISSUE TITLE
BUG: Inconsistency in the result of the 'var' function (also in 'std')

### ISSUE THREAD

**Issue by cedric-coussinet** [numpy/numpy#20381]
### Describe the issue:

For very special cases :
- arrays with more than one column
- with values that have a non-finite representation in binary like 0.1

Then there is a difference in processing (and an error) in the calculation of the 'std' or 'var' depending on the selection of the data.

The example below uses identical column values but this is just to see the problem better, the problem remains even if you change the first column value.

### Reproduce the code example:

```python
import numpy as np

X = np.zeros((10, 1), dtype="float32")
X[:,0] = 0.1
print(np.var(X, axis=0, dtype="float32")[0])
print(np.var(X[:,0], axis=0, dtype="float32"))
assert np.var(X, axis=0, dtype="float32")[0] == np.var(X[:,0], axis=0, dtype="float32"), "A"

X = np.zeros((10, 2), dtype="float32")
X[:,0] = 0.1
print(np.var(X, axis=0, dtype="float32")[0])
print(np.var(X[:,0], axis=0, dtype="float32"))
assert np.var(X, axis=0, dtype="float32")[0] == np.var(X[:,0], axis=0, dtype="float32"), "B"
```

### Error message:

```shell
0.0
0.0
5.551115e-17
0.0
Traceback (most recent call last):

  File "<ipython-input-60-2851298f0bde>", line 13, in <module>
    assert np.var(X, axis=0, dtype="float32")[0] == np.var(X[:,0], axis=0, dtype="float32"), "B"

AssertionError: B
```

### NumPy/Python version information:

1.20.1 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]

**Comment by bashtage** [comment]
These values are all within the numeric tolerance of zero relative to the base value of 0.1 and the sample size of 10, and so there is no bug.

**Comment by cedric-coussinet** [comment]
The acceptable tolerance depends on the problem, but indeed it is not a bug as the [documentation states](https://numpy.org/doc/stable/reference/generated/numpy.var.html#numpy.var):

> For floating-point input, the variance is computed using the same precision the input has. Depending on the input data, this can cause the results to be inaccurate, especially for float32 (see example below). Specifying a higher-accuracy accumulator using the dtype keyword can alleviate this issue.

Thank you for your answer, and sorry for asking this question.
