### ISSUE TITLE
TEST: distutils.tests.test_mingw32ccompiler.py is fragile

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#20391]
Over in PR #20383, @lithomas1 needed to add `PY_DIR=$(python -c "import sys; print(sys.prefix)"); mkdir $PY_DIR/libs` in order to make this test work. The test should be made more robust, then those lines in the cibuildwheel CI run can be removed.

**Comment by rgommers** [comment]
No longer necessary since we switched to Meson, closing. Thanks Matti and Thomas.
