### ISSUE TITLE
numpy.info interacts poorly with sys.stdout overrides

### ISSUE THREAD

**Issue by FrozenBob** [numpy/numpy#20423]
`numpy.info` uses `sys.stdout` as a default parameter. If `sys.stdout` gets replaced with a new object, `numpy.info` ends up still trying to write to the old `sys.stdout` for any call that doesn't pass an explicit `output` parameter. For example, if you call `numpy.info` in Google Colab, you don't get any info output, because everything gets written to the wrong output stream. (I don't know if the behavior is any different in a regular Jupyter notebook - I don't have Jupyter installed.)

It would be better if `numpy.info` instead used `None` as the default parameter, and did

```
if output is None:
    output = sys.stdout
```

inside the function body, to pick up `sys.stdout` at the time of the call instead of at definition time.

**Comment by WarrenWeckesser** [comment]
At first glance, this seems like a reasonable suggestion.  Does anyone see any reasons to not do this?

**Comment by abatomunkuev** [comment]
Hello! I would like to work on this issue. 

I have checked that in google colab, it doesn't display any information. I am not sure if it is correct reproduction of the issue. 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/55283735/143140286-b4282c1f-59bb-4263-9cc8-dea1f1a90e90.png">
