### ISSUE TITLE
BUG: maximum function with where=mask throwing error

### ISSUE THREAD

**Issue by matteobe** [numpy/numpy#20421]
### Describe the issue:

When using any of the maximum functions (np.max, np.amax, np.maximum) and using a mask for the keyword argument where, the following error is thrown up:

### Reproduce the code example:

```python
import numpy as np

x = np.array([[1, np.NaN], [2, 3]])
mask = np.isnan(x)

np.amax(x, axis=1, where=mask)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/Coding/curis/.venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-3daeee03325c>", line 1, in <module>
    np.amax(a, axis=1, where=m)
  File "<__array_function__ internals>", line 6, in amax
  File "/Users/Coding/curis/.venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2755, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/Users/Coding/curis/.venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: reduction operation 'maximum' does not have an identity, so to use a where mask one has to specify 'initial'
```

### NumPy/Python version information:

python 3.7.3 (default, Apr 24 2020, 18:51:23) 
[Clang 11.0.3 (clang-1103.0.32.62)]
numpy: 1.21.4

**Comment by Yutaro-Sanada** [comment]
In the last line of your example, you calculate the maximum values for ```axis = 1```. 
Then the expected output dimension is ```1 x 2```.
However, the mask is follows;
```python
array([[False,  True],
       [False, False]])
```
The maximum value of 2nd row does not exit, due to ```[False, False]```.
To prevent the error, you need to set ```initial``` as follows;
```python
np.amax(x, axis=1, where=mask, initial=-1) # array([nan, -1.])
```

**Comment by Bhavay192** [comment]
Hey @Yutaro-Sanada, has the issue been resolved?? If no, can you please assign the issue to me??

**Comment by matteobe** [comment]
@Bhavay192 @Yutaro-Sanada the issue is resolved
