### ISSUE TITLE
Test failures on nightly ARM64 wheel builds.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#20426]
See https://app.travis-ci.com/github/MacPython/numpy-wheels/jobs/549013361.
```
FAILED core/tests/test_mem_policy.py::test_new_policy - AssertionError: asser...
FAILED core/tests/test_umath.py::TestComplexFunctions::test_loss_of_precision[complex256]
```

**Comment by mattip** [comment]
The `test_new_policy` failure is due to running the whole test suite with a new memory allocation policy and failing on the same `TestComplexFunctions.test_loss_of_precision[complex256]` test. So there is a single failure of `arcsinh` with `np.long128`. Just before the check is
```
        x_series = np.logspace(-20, -3.001, 200)
        x_basic = np.logspace(-2.999, 0, 10, endpoint=False)

        if glibc_older_than("2.19") and dtype is np.longcomplex:
            if (platform.machine() == 'aarch64' and bad_arcsinh()):
                pytest.skip("Trig functions of np.longcomplex values known "
                            "to be inaccurate on aarch64 for some compilation "
                            "configurations.")

            # It's not guaranteed that the system-provided arc functions
            # are accurate down to a few epsilons. (Eg. on Linux 64-bit
            # So, give more leeway for long complex tests here:
            check(x_series, 50.0*eps)
        else:
>           check(x_series, 2.1*eps)
``` 

Did something change with `arcsinh` recently and we need to blocklist this glibc function?

**Comment by charris** [comment]
That check was updated in #20274.

**Comment by charris** [comment]
Manylinux2014 has glibc 2.17, so should have used the lower precision check, but should probably just xfail/skip the test instead.

**Comment by charris** [comment]
Fixed. Travis-ci Python 3.9 arm64 has gone missing, but the working versions built wheels and passed the tests.
