### ISSUE TITLE
File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice ValueError: probabilities contain NaN

### ISSUE THREAD

**Issue by jocelynbaduria** [numpy/numpy#20431]
### Describe the issue:

I am using it to train policy gradient in RL in [colab](https://colab.research.google.com/drive/1J3VlrQyqNVRglVLa64DFJArqfe2hySzB?usp=sharing)

File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN

### Reproduce the code example:

```python
This is the short code command in terminal to reproduce the result.

python train.py --train data/PHP.csv --valid data/PHP.csv --model-type=pg --episode-count 50 --window-size 10

```

### Error message:

```shell
Episode 1/50:   0% 0/262 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    model_type=model_type, pretrained = pretrained, verbose = verbose)
  File "train.py", line 41, in run
    training_result = train_pg_model(agent, episode, training_data, episode_count = episode_count, batch_size = batch_size, window_size = window_size)
  File "/content/drive/Shareddrives/cmpe_260_RL Project/code/RL-DeepQLearning-Trading/src/methods.py", line 88, in train_pg_model
    action, prob = agent.action(state)
  File "/content/drive/Shareddrives/cmpe_260_RL Project/code/RL-DeepQLearning-Trading/src/pg_agent.py", line 69, in action
    action = np.random.choice(self.action_size, 1, p=prob)
  File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
```

### NumPy/Python version information:

1.19.5 3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]

**Comment by WarrenWeckesser** [comment]
I suspect this is a bug in the code that is calling `np.random.choice`.  @jocelynbaduria, if you really think this is a bug in numpy, we need a much simpler example that reproduces the problem.

**Comment by bashtage** [comment]
Do your probabilities contain `NaN`?  The check for `NaN` is pretty simple so it is likely telling you that the caller is passing a `NaN`

**Comment by jocelynbaduria** [comment]
@WarrenWeckesser I would love to access the mtrand.pyx so I can debug my own code as well. Is this similar to this [fix](https://github.com/numpy/numpy/pull/11264)

**Comment by bashtage** [comment]
Relevant code.  

https://github.com/numpy/numpy/blob/4a8007d5d916126965e811cd1b41ff4de44663b3/numpy/random/mtrand.pyx#L935-L937

**Comment by jocelynbaduria** [comment]
@bashtage Thanks a lot. I am running the code in Colab. Let me try to debug it in visual studio editor.

**Comment by WarrenWeckesser** [comment]
Note that the message about `NaN` can also be triggered if `inf` occurs in the probabilities:
```
In [75]: rng = np.random.default_rng()

In [76]: rng.choice([10, 11, 12], p=[0.5, np.inf, 0])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-76-f1c51d99eb99> in <module>
----> 1 rng.choice([10, 11, 12], p=[0.5, np.inf, 0])

_generator.pyx in numpy.random._generator.Generator.choice()

ValueError: probabilities contain NaN
```

**Comment by jocelynbaduria** [comment]
@WarrenWeckesser thanks a lot I'll make a note of this when debugging.

**Comment by jocelynbaduria** [comment]
Hi @WarrenWeckesser @bashtage . I was able to fix my code. I got some zeros value in my data.

**Comment by jocelynbaduria** [comment]
Thanks for the prompt reply. Appreciate it.
