### ISSUE TITLE
Potentially remove `TestF77Mismatch`?

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#20445]
Conda-forge has been more or less forced recently by the CI provider landscape to cross-compile packages for aarch64 & ppc64le. The tests generally still get run (using emulation through QEMU), but that means that a few special things cannot work.

As such an example, we had to skip `TestF77Mismatch` on the scipy-feedstock - @rgommers later removed it in https://github.com/scipy/scipy/pull/15010, writing:
> We no longer need this test, because g77 is not a thing anymore
(the build will fail or other things will break if an ancient g77
is still used somehow).
>
> This test is also fragile, as seen on conda-forge for the v1.7.2 builds,
the test will fail when the tests run under QEMU with:
>
> `[snip]`
>
> That seems to be because `ldd` may incorrectly report something is not a
dynamic executable if the correct loader cannot be found.

Seeing that these tests doing the same between scipy & numpy, I wanted to propose whether this test could also be removed here. It would save us a further test to skip in the build recipe (which would be beneficial because test skips are easily overlooked later and prone to bitrot).

That said, if the test stays, we can work around it pretty easily.

PS. The failure showed up while [testing](https://github.com/conda-forge/numpy-feedstock/pull/248) 1.22.0rc1, though that has nothing to do with the numpy version, and is due to the intervening infra changes in conda-forge.

**Comment by mattip** [comment]
I think you are talking about this test [TestF77Mismatch](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/linalg/tests/test_build.py#L42)? Indeed if g77 is gone it makes sense to delete the test, thanks.

**Comment by rgommers** [comment]
agreed, +1 for deleting. want to make a PR @h-vetinari?

**Comment by h-vetinari** [comment]
> agreed, +1 for deleting. want to make a PR @h-vetinari?

Done: #20457
