### ISSUE TITLE
ENH: Allow for callable in indexing

### ISSUE THREAD

**Issue by ckp95** [numpy/numpy#20453]
### Proposed new feature or change:

If you have an array built up out of method chaining, sometimes you need to filter it at the very end. This can be annoying because it means you have to create a temporary variable just so you can refer to it in the indexing square brackets.

```py
_temp = long_and_complicated_expression()
result = _temp[_temp >= 0]
```

You could also use the walrus operator but this is odd looking and it still pollutes the namespace:

```py
result = (_temp := long_and_complicated_expression())[_temp >= 0]
```

What I would like is to be able to use a lambda inside the indexing square brackets, which would take the whole array as an argument and give a boolean array:

```py
result = long_and_complicated_expression()[lambda arr: arr >= 0]
```

I should emphasize, the lambda gets the entire array as its argument, and returns an entire mask array of bools. It isn't like the `map` and `filter` builtins where it would call the python function once for each element and thus be slow.

[Pandas already has something similar](https://pandas.pydata.org/pandas-docs/version/0.18.1/whatsnew.html#method-chaininng-improvements); you can pass a lambda into `.loc[]` that takes a Series and returns a boolean indexer.

**Comment by matteosantama** [comment]
I agree this feature would be nice -- it allows for much more elegant code. The basic idea is simple, but there are a few wrinkles to iron out:

1. The [Array API](https://data-apis.org/array-api/latest/API_specification/generated/signatures.array_object.array.__getitem__.html) does not specify a callable as an accepted argument to `__getitem__`. If callables are to be accepted in `np.ndarray.__getitem__`, we would have to decide whether to explicitly disallow them in `np.array_api.Array.__getitem__` (raise an error?).
2. If we are to allow callables in `__getitem__`, then we should probably allow them in `__setitem__` too for consistency (`pandas` allows both). `__setitem__` must return a view, presumably `__getitem__` should also?
3. There's a question of whether callables should be supported for masked arrays and structured arrays too.

**Comment by matteosantama** [comment]
Given the feedback on the discussion [board](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/7C2KNIREE2RTGMACW3S6QXQGSJCX52DW/), it seems like this is not a feature `numpy` is interested in maintaining. This issue can likely be closed as a "wontfix".
