### ISSUE TITLE
F2PY: got "invalid decimal literal (<string>, line 1)" on '1.0d0'

### ISSUE THREAD

**Issue by bilderbuchi** [numpy/numpy#20460]
### Describe the issue:

When using double precision float literals, e.g.  `1.4d0`, in my Fortran code, I get warnings like `"unexpected EOF while parsing (<string>, line 1)" on '1.0d0'`.

I guess some parser does not expect this fortran number format? The pyf file looks ok to my eye, but I don't know what else could be broken by this?

### Reproduce the code example:

```python
> test_d0_float_literals.f90
module test_d0_float_literals
    implicit none
    double precision, parameter :: myparam=1.0d0
end module test_d0_float_literals

> "f2py .\test_d0_float_literals.f90 -m test_float_literals -h test_float_literals.pyf" generates
> test_float_literals.pyf

!    -*- f90 -*-
! Note: the context of this file is case sensitive.

python module test_float_literals ! in 
    interface  ! in :test_float_literals
        module test_d0_float_literals ! in :test_float_literals:.\test_d0_float_literals.f90
            double precision, parameter,optional :: myparam=1.0d0
        end module test_d0_float_literals
    end interface 
end python module test_float_literals

! This file was auto-generated with f2py (version:1.21.4).
! See http://cens.ioc.ee/projects/f2py2e/
```

### Error message:

```shell
> Output from f2py .\test_d0_float_literals.f90 -m test_float_literals -h test_float_literals.pyf

Reading fortran codes...
        Reading file '.\\test_d0_float_literals.f90' (format:free)
Post-processing...
        Block: test_float_literals
                        Block: test_d0_float_literals
In: :test_float_literals:.\test_d0_float_literals.f90:test_d0_float_literals
get_parameters: got "unexpected EOF while parsing (<string>, line 1)" on '1.0d0'
Post-processing (stage 2)...
        Block: test_float_literals
                Block: unknown_interface
                        Block: test_d0_float_literals
Saving signatures to file ".\test_float_literals.pyf"
```

### NumPy/Python version information:

1.21.4 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]

**Comment by melissawm** [comment]
Thanks for the report - I see the warning but the actual module gets built just fine.

**Comment by bilderbuchi** [comment]
Exactly. I was quite surprised that despite a behaviour deviation associated with an "unexpected EOF" this actually completes without error, but I'm not familiar enough with the f2py code to judge if there could be other hidden (and worse) ramifications that are not demonstrated by my MWE.

**Comment by bilderbuchi** [comment]
With current numpy, the error message has changed and is now "get_parameters: got "invalid decimal literal (<string>, line 1)" on '1.0d0'", the rest seems unchanged.

**Comment by HaoZeke** [comment]
The reason is that `1.0d0` is being called in an `eval` statement, and `python` doesn't recognize `1.0d0`.
The relevant code is:
```
            try:
                params[n] = eval(v, g_params, params)
            except Exception as msg:
                params[n] = v
                outmess('get_parameters: got "%s" on %s\n' % (msg, repr(v)))
```

The "fix" in this case is to simply not report the exception for numeric values.

**Comment by bilderbuchi** [comment]
Thanks for the explanation! 
> The "fix" in this case is to simply not report the exception for numeric values.

If you need that value to `eval` successfully (because that is important later in the code), a slightly more complicated fix could be to catch that `SyntaxError`, replace the `d` with an `e`, and retry.
