### ISSUE TITLE
BUG: numpy.round() function 

### ISSUE THREAD

**Issue by Liu-RX** [numpy/numpy#20469]
### Describe the issue:

`numpy.round()` does not return rounded number correctly. As the code example shown below, the function does not return the same value as it should.

### Reproduce the code example:

```python
import numpy as np
print(np.round(84.8324502736, 4))
print(np.round(84.83245, 4))
```

### NumPy/Python version information:

np.__version__ = '1.21.4'
sys.version = '3.8.8 (default, Apr 13 2021, 19:58:26) \n[GCC 7.3.0]'

**Comment by mattip** [comment]
What did you get and what did you expect? What operating system are you running, and which version of that OS?

**Comment by rkern** [comment]
Getting `84.8324` for the second expression is the expected result. We follow the "round-to-nearest-even" convention for values that are exactly halfway between. See the `Notes` in the docstring: https://numpy.org/doc/stable/reference/generated/numpy.around.html
