### ISSUE TITLE
BUG: numpy.fromBuffer is missing type hints

### ISSUE THREAD

**Issue by Avasam** [numpy/numpy#20472]
### Describe the issue:

numpy.fromBuffer is missing type hints, parameters and return type are all `Unknown`

### Reproduce the code example:

```python
import numpy as np
np.frombuffer(b'hello world', dtype='S1')
```

### Error message:

```shell
(function) frombuffer: (buffer: Unknown, dtype: Unknown = ..., count: Unknown = ..., offset: Unknown = ..., *, like: Unknown = ...) -> Unknown
[{
	"resource": "/C:/Users/Avasam/Documents/Git/Auto-Split/src/capture_windows.py",
	"owner": "python",
	"code": "error",
	"severity": 8,
	"message": "Call to untyped function \"frombuffer\" in typed context  [no-untyped-call]",
	"source": "mypy",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}]
```

### NumPy/Python version information:

1.21.1 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]

**Comment by BvB93** [comment]
Type hints for `np.frombuffer` will be added in numpy 1.22.
The first release candidate is already available on [pypi](https://pypi.org/project/numpy/1.22.0rc1/) and if so desired then you can install it with `pip install numpy --pre --upgrade`.
