### ISSUE TITLE
BUG: random.multinomial causes floating point exception if `pvals` has size 0

### ISSUE THREAD

**Issue by jloxh** [numpy/numpy#20483]
### Describe the issue:

Calling `random.multinomial` with `pvals` of size zero (empty list, empty tuple, etc.) produces a floating point exception rather than raising a `ValueError`.

### Reproduce the code example:

```python
import numpy as np

# produces floating point exception
_ = np.random.multinomial(0, [])
```

### Error message:

```shell
Floating point exception (core dumped)
```

### NumPy/Python version information:

1.20.3 3.9.0 (default, Oct 12 2021, 08:34:59) 
[GCC 8.3.0]

**Comment by bashtage** [comment]
If this new or does it happen in older versions?

**Comment by bashtage** [comment]
Need protection against empty pval arrays here(ish)

**Comment by bashtage** [comment]
NumPy 1.16 returns an empty array here, so should do the same.
