### ISSUE TITLE
BUG/API: ~np.array([True, False], dtype=object) contains negative ints

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#20485]
### Describe the issue:

xref https://github.com/pandas-dev/pandas/issues/44257

I expect `~` to operate pointwise on an object dtype ndarray, am surprised by the behavior with bools.

### Reproduce the code example:

```python
import numpy as np

arr = np.array([True, False], dtype=object)

>>> ~arr
array([-2, -1], dtype=object)
```

Expected:

```
>>> ~arr
array([False, True], dtype=object)
```

### NumPy/Python version information:

Running 1.21.4

**Comment by seberg** [comment]
Isn't this just Python's bools being weird bools (because they are basically just special integers):
```
In [1]: ~True, ~False
Out[1]: (-2, -1)
```
This is the pointwise result for python bools.

**Comment by seberg** [comment]
Going over to the pandas issue, maybe your fix is to use `np.logical_not`?

**Comment by jbrockmendel** [comment]
> Isn't this just Python's bools being weird bools (because they are basically just special integers):

Wow, hard to believe I missed this.  I'll see if logical_not can work for our use case.  Thanks.
