### ISSUE TITLE
pickle memmap'd arrays (patch + tests) (Trac #1452)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2049]
_Original ticket http://projects.scipy.org/numpy/ticket/1452 on 2010-04-14 by trac user brentp, assigned to unknown._

currently cant pickle a np.memmap object. this patch adds that functionality.

**Comment by mattip** [comment]
Closing as won't-fix since pickling memmap would require holding the file object. Please reopen with a solution if you feel this is wrong
