### ISSUE TITLE
BUG: kahan_sum should not be called with 0-length arrays

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#20492]
### Describe the issue:

`kahan_sum` is called in `Generator` and `RandomState` with possibly 0-length arrays in `choice`. It then accesses `arr[0]` to initialize the sum. This value does not appear to be well defined in an empty array, and even if it is, might be uninitialized and so random.

### Reproduce the code example:

```python
import numpy as np

np.random.choice([],p=[],size=0)
```

### Error message:

```shell
# Usually raises

ValueError: probabilities do not sum to 1
```

### NumPy/Python version information:

Master and all versions since at least 1.17

**Comment by fifthist** [comment]
Does explicitly passing an empty probability array to `choice` make sense at all? How should values be sampled when the client consciously overrides the default (`None`) and passes no probabilities?

**Comment by mattip** [comment]
@fifthist I think the proposal is to fix the code to always raise a better error than "probabilities do not sum to 1"

**Comment by bashtage** [comment]
> Does explicitly passing an empty probability array to `choice` make sense at all? How should values be sampled when the client consciously overrides the default (`None`) and passes no probabilities?

It is sometimes allowed when there are no outputs, so that this is being used to generate an empty. I think this can occur in real code when the number of samples depends on another calculation, and so returning an empty array when `size=0` can lead to cleaner code.
