### ISSUE TITLE
BUG: calling .T on an Array API array returns a numpy.ndarray

### ISSUE THREAD

**Issue by grlee77** [numpy/numpy#20498]
### Describe the issue:

calling .T on an Array API array currently returns a `numpy.ndarray` when an Array would be expected.

### Reproduce the code example:

```python
import numpy.array_api as api

a = api.ones((5, 1))
print(type(a))
print(type(a.T))
```

gives
```
<class 'numpy.array_api._array_object.Array'>
<class 'numpy.ndarray'>
```

This change in types results in unexpected behavior for code like the following
```Python
a.T * a
```
resulting in a NumPy object array as output instead of a (5, 5) Array of ones

In this specific case using `a.mT` instead would work as expected

### NumPy/Python version information:

1.22.0rc1

**Comment by rgommers** [comment]
Agreed, that looks like a simple oversight. @asmeurer or @honno, could one of you look at fixing this?

**Comment by grlee77** [comment]
Thanks @asmeurer for the quick fix!
