### ISSUE TITLE
BUG: Wrong order of the eigenvectors

### ISSUE THREAD

**Issue by Alexander-Mitrofanov** [numpy/numpy#20513]
### Describe the issue:

It seems that the eigenvectors are provided with the wrong order.
The indices for eigenvalues with the value of 1 are 0 and 4. But corresponding eigenvectors have indexes 0 and 3.

Here is the same matrix from wolfram alpha
[matrix](https://www.wolframalpha.com/input/?i=eigenvectors%7B%7B0%2C0%2C0%2C0%2C0%2C0%7D%2C%7B1%2C0%2C1%2C0%2C0%2C0%7D%2C%7B0%2C1%2C0%2C0%2C0%2C0%7D%2C%7B0%2C0%2C0%2C0%2C2%2F3%2C1%2F3%7D%2C%7B0%2C0%2C0%2C1%2F3%2C0%2C2%2F3%7D%2C%7B0%2C0%2C0%2C2%2F3%2C1%2F3%2C0%7D%7D)

### Reproduce the code example:

```python
import numpy as np


matrix = [[0, 0, 0, 0, 0, 0],
          [1, 0, 1, 0, 0, 0],
          [0, 1, 0, 0, 0, 0],
          [0, 0, 0, 0, 2/3, 1/3],
          [0, 0, 0, 1/3, 0, 2/3],
          [0, 0, 0, 2/3, 1/3, 0]]


w, v = np.linalg.eig(np.asarray(matrix))
eval_close_to_1 = np.abs(w-1.) < 1e-8

# getting indexes of the eigenvalues with the value 1
indices = np.where(eval_close_to_1)[0]
print(indices)

# The second one is wrong
for index in indices:
    print(index)
    print(v[:, index])

# Correct eigenvector for the second eigenvalue with the value 1
print(v[:, 3])
```

### NumPy/Python version information:

1.21.4

**Comment by WarrenWeckesser** [comment]
Eigenvectors are not unique. The eigenvalue 1 has multiplicity 2, and a two-dimensional eigenspace.  Any nonzero vector in this space is a valid eigenvector.

Wolfram Alpha gives v2 = [0, 0, 0, 1, 1, 1] and v3 = [0, 1, 1, 0, 0, 0] as eigenvectors associated with the eigenvalue 1.  NumPy gives:
```
In [18]: np.set_printoptions(suppress=True)  # Don't show tiny values the are numerically 0.

In [19]: v[:, [0, 4]]
Out[19]: 
array([[ 0.        +0.j,  0.        +0.j],
       [-0.        +0.j,  0.69841376+0.j],
       [ 0.        +0.j,  0.69841376+0.j],
       [ 0.57735027+0.j,  0.09025232+0.j],
       [ 0.57735027+0.j,  0.09025232+0.j],
       [ 0.57735027+0.j,  0.09025232+0.j]])
```
The first column is `0.57735027*v2` and the second is `0.69841376*v3 + 0.09025232*v2`.  So the numpy eigenvectors are linear combinations of the eigenvectors reported by Wolfram Alpha.  In other words, both the results give eigenvectors that span the same space, so both are correct.


Note that `v[:,3]` is not an eigenvector for the value 1; it is an eigenvector associated with the eigenvalue -1:
```
In [15]: matrix @ v[:, 3:4]
Out[15]: 
array([[ 0.        +0.j],
       [ 0.70710678+0.j],
       [-0.70710678+0.j],
       [-0.        +0.j],
       [-0.        +0.j],
       [ 0.        +0.j]])

In [16]: v[:, 3:4]
Out[16]: 
array([[ 0.        +0.j],
       [-0.70710678+0.j],
       [ 0.70710678+0.j],
       [ 0.        +0.j],
       [ 0.        +0.j],
       [-0.        +0.j]])
```

**Comment by Alexander-Mitrofanov** [comment]
Thanks a lot for the clarifications.

Is there a simple way to convert the provided numpy eigenvectors to a representation similar to the wolfram output?
