### ISSUE TITLE
BUG,DOC: F2PY CLI usage discrepancy

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#20520]
### Issue with current documentation:

Consider the following examples from the F2PY tests.

```f90
! hiworld.f90
function hi
  print*, "Hello World"
end function
```

```fortran
c      foo77.f
       function t0(value)
         real value
         real t0
         t0 = value
       end
       function t4(value)
         real*4 value
         real*4 t4
         t4 = value
       end
       subroutine s0(t0,value)
         real value
         real t0
cf2py    intent(out) t0
         t0 = value
       end
```

Now consider what this is supposed to generate:

```bash
f2py -m test foo77.f only: td s0 :  hiworld.f90 > out 2>error
```

From the documentation:
```bash
      f2py [<options>] <fortran files> [[[only:]||[skip:]] \\
                                        <fortran functions> ] \\
                                       [: <fortran files> ...]

  only:            Use only fortran functions that follow until `:'.
  :                Get back to <fortran files> mode.

```

What should happen, as I understand, is that three functions should be wrapped, `td, s0, hi`. However what comes through is:

```bash
Reading fortran codes...
	Reading file 'foo77.f' (format:fix,strict)
	Reading file '../cli/hiworld.f90' (format:free)
Post-processing...
	Block: test
			Block: td
			Block: s0
Post-processing (stage 2)...
Building modules...
    Building module "test"...
		Creating wrapper for Fortran function "td"("td")...
        Constructing wrapper function "td"...
          td = td(value)
        Constructing wrapper function "s0"...
          t0 = s0(value)
    Wrote C/API module "test" to file "./testmodule.c"
    Fortran 77 wrappers are saved to "./test-f2pywrappers.f"
```

Essentially, only the functions passed in the `only:` keyword are actually wrapped. This means that `:` is being ignored, and is a bug.

### Idea or request for content:

Personally, though this behaviour is incorrect, and can be fixed in the newer CLI, I'm more of the opinion that for the current `f2py2e` a documentation change should suffice.

**Comment by soma2000-lang** [comment]
@Objectivitix Can I work on this isssue?Please assign me this.

**Comment by InessaPawson** [comment]
Hi, @soma2000-lang! NumPy doesn't assign issues. Just dive right in, no permission needed.

**Comment by HaoZeke** [comment]
Thinking about this now, I don't think it makes sense. Of course `f2py` is correctly returning to `normal` mode. There are essentially 3 options:
- Add to `skipfuncs`
- Add to `onlyfuncs`
- Add to `files`

My assumption here was wrong, even though `f2py` adds to these three lists correctly, there is no association between an `only: :` and a file (which is what would be needed for my original post). In that scenario `file only: : file2` would then associate the `onlyfuncs` with `file`. Currently `f2py` has **one** `onlyfuncs` for the whole set of files.

Weather this needs to change is an enhancement, not a bug, but it might as well be documented a bit better.
