### ISSUE TITLE
BUG: type annotation doesn't work when np.dtype is a return type for function

### ISSUE THREAD

**Issue by bubanoid** [numpy/numpy#20525]
### Describe the issue:

 Type check with `mypy` returns an error. List of packages installed into the virtualenv:
 ```
 attrs==21.2.0
iniconfig==1.1.1
mypy==0.812
mypy-extensions==0.4.3
numpy==1.21.4
packaging==21.3
pluggy==1.0.0
py==1.11.0
pyparsing==3.0.6
pytest==6.2.5
toml==0.10.2
typed-ast==1.4.3
typing_extensions==4.0.1
 ```

### Reproduce the code example:

```python
import numpy as np
import numpy.typing as npt


def as_dtype(d: npt.DTypeLike) -> np.dtype:
    return np.dtype(d)
```

### Error message:

```shell
error: Missing type parameters for generic type "dtype"
```

### NumPy/Python version information:

1.21.4 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) 
[Clang 6.0 (clang-600.0.57)]

**Comment by BvB93** [comment]
Per the error: the type parameter for `np.dtype` is missing and you're apparently running mypy in strict mode:
``` diff
- def as_dtype(d: npt.DTypeLike) -> np.dtype:
+ def as_dtype(d: npt.DTypeLike) -> np.dtype[Any]:
```
