### ISSUE TITLE
TASK: run valgrind and pytest-leaks on the 1.22 branch

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#20536]
Just as a heads up, I had not come to it yet: I am planning to run my `valgrind` and `pytest-leaks` routine in the coming week or so.  Hopefully, it won't find too many issues :)  (last release had very little issues IIRC, but things have been quite a bit in flux, so lets see).

**Comment by charris** [comment]
Should I wait to release 1.22.0rc2? There are a couple of things that should be settled before the final, but I'd like to get more testing of the promotion fixups.

**Comment by seberg** [comment]
No need for waiting for this, usually (and also here) I find a few small memory leaks and easy bug fixes, nothing that needs an rc IMO.  But for the promotion stuff, waiting a few days may make sense.

And pandas seems to possibly have stumbled on some issue about array priorities, but I didn't understand yet what it is about.

**Comment by seberg** [comment]
Currently, I have 4-5 or simple fixes, the one above is still elusive.  It is plausible that it is a very old issue with the iterator, but until now it just never mattered.  Even now it does not actually matter (yet!), because we never do anything relevant with the information.  It may be that the stride is used with `N=1` always, but I am not certain yet.

(More bugs will crawl out of course)

**Comment by seberg** [comment]
Ah, found the reason.  I had grouped getting the fixed strides with clearing the float errors.  I wanted to clear those before filling the scalar.
But, the iterator is only finalized (the buffer fully initialized) after that, because it needs to copy the data after filling the buffer.

Moving that bunch of code a bit later is all that is needed :facepalm:.

**Comment by seberg** [comment]
Done and things fixed up (except that setstate thingy, which should be OK to ignore).
