### ISSUE TITLE
# Error: ImportError:<In Python Maya 2018>

### ISSUE THREAD

**Issue by yogeshnichal** [numpy/numpy#20549]
### Steps to reproduce:

Numpy 1.16.6
Python 2.7.18 pip

### Error message:

```shell
# Error: ImportError: file C:\Program Files\Autodesk\Maya2018\Python\lib\site-packages\numpy\__init__.py line 140: cannot import name _distributor_init #
```

**Comment by mattip** [comment]
We no longer support python2.

**Comment by seberg** [comment]
Indeed, while 1.16.6 should work with a Python 2, this has something to do with wherever you got your python from.  Beyond pointing out that the path `Autodesk/Maya2018` looks like some program shipping its own Python which could interfere with another python on the system (modified PYTHONPATH, etc.), I do not think we will be able to help you.

**Comment by seberg** [comment]
Closing, as there was no followup and it seems to be a custom shipped Python involved (possibly interacting with a system python).  And thus probably a problem with that setup.
