### ISSUE TITLE
Some cross-compilations with NumPy >=1.21.0 causes sigill

### ISSUE THREAD

**Issue by ofisette** [numpy/numpy#20546]
### Steps to reproduce:

If I build a wheel for NumPy 1.21.0 with a Skylake CPU (AVX512) and install it on a machine with an Ivybridge CPU (AVX), it segfaults with `Illegal instruction` during CPU detection in `InitOperators`. However, a NumPy 1.21.0 wheel built with a Haswell CPU (AVX2) works on Ivybridge.

This issue started with 1.21.0. NumPy 1.20.2 does not exhibit this problem. It also affects 1.22.0rc1.

### Error message:

```shell
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00002aaaabf29c0c in InitOperators (dictionary=0x2aaaabdb9b00)
    at build/src.linux-x86_64-3.8/numpy/core/include/numpy/__umath_generated.c:356
```

### Additional information:

I tried compiling with both GCC 10.3.0 and Intel 2020.1. It made no difference.

**Comment by mattip** [comment]
Can you import enough of numpy to run `np.show_config()` on the Ivybridge machine and paste the last few lines? You may have manually edit the offending lines with an `#if 0` where it checks for AVX2 in `__umath_generated.c` when building NumPy on the Skylake machine in order to get numpy to load. `np.show_config()` will indicate which cpu features are tested for and which are being used on the target machine. 

Perhaps the detection is failing and an unavailable SIMD intrinsic is being called. @seiko2plus thoughts?

**Comment by ofisette** [comment]
I cannot get to `np.show_config()` on the Ivybridge machine; since the SIGILLL happens in `InitOperators`, Python crashes when importing NumPy.

I tried editing `__umath_generated.c` as suggested but changes to this generated file do not seem to be picked up even if I run `python setup.py build --force`. Is there a clean way to add debugging information to the CPU detection routines?

I noticed something else: if I build NumPy on the Skylake CPU, but using a Python built for the Ivybridge CPU, the resulting NumPy wheel works on the Ivybridge machine. The wheel is incompatible if it was built using a Python built for Skylake or Haswell CPUs (or presumably anything that supports at least AVX2).

**Comment by seiko2plus** [comment]
@ofisette, Could you please provide us with the build log so we can determine which baseline features and compiler flags are used? maybe, you have provided `-march=native` through the environment which lead to a raise up the ceiling of the baseline features to `AVX512_SKX`. We have a code to detect this behavior and raise a runtime error when it happened but maybe for somehow, the crash happens before the baseline detection.

**Comment by ofisette** [comment]
This turns out to be a problem in our environment, not NumPy. Very sorry for the noise. I attach the build log, which shows that I end up passing `-march=core-avx2` to the build system somehow. This seemed weird, so I tried rebuilding NumPy 1.20.2 for comparison, and this time the same bug kicked in. I must have missed it before because our 1.20.2 wheels were built some time ago, and presumably something changed in our environment in the meantime. I will now try to understand how we end up passing this flag to the build system.

I still attach the requested build log just in case. [build.log](https://github.com/numpy/numpy/files/7713217/build.log)

**Comment by ofisette** [comment]
The root cause of this issue was Python reusing the `CFLAGS` used to compile Python itself to compile C extensions: `distutils.sysconfig.get_config_var("CFLAGS")`. We have managed to work around this by compiling all our NumPy/SciPy wheels with a Python compiled with very low SIMD optimisations. I find this Python behaviour surprising, and it caused us quite a bit of trouble, but it is not a NumPy issue; closing.
