### ISSUE TITLE
ENH: Feature for internally saving data as bits (dtype of bit?)

### ISSUE THREAD

**Issue by tweber68** [numpy/numpy#20542]
### Proposed new feature or change:

I have a machine learning script with datasets with over 20000 columns. In effect, these columns only save 1s and 0s. It's a so called OneHotArray. As numpy's smallest dtype is uint8, the numpy array needs **8 times more memory than necessary**. And it becomes even worse. The machine learning algorithm constructs a view with dtypes of float64. As a consequence, the numpy array needs **64 times more memory than necessary**.

So it would be nice, if numpy had some kind of **dtype of bit**. Perhaps, this could be realized by distinguishing between **dtype** and **viewtype**: Internally numpy could save the data as bits (in a uint8-array or what else), but the view type could determine how numpy returns the internally stored values, e.g. as uint8 or as float64.

**Comment by bashtage** [comment]
Use `np.packbits` to pack them, then save as uint8.

**Comment by tweber68** [comment]
Thank's for your reply. I agree with you, that the ML library has to be adapted, if it wants to save memory. But currently this is not possible, I think. Consider the following code:

```
import numpy as np

a = [[1,0],[0,1]]

n = np.array(a)
n= np.packbits(n)

print(n[1][0])
```

The result is:
```
Traceback (most recent call last):
  File "/home/theo/test2.py", line 8, in <module>
    print(n[1][0])
IndexError: index 1 is out of bounds for axis 0 with size 1
```
With packbits an index operation is not possible any more. But I think the ML library needs such an index access. That's why I thought a dtype of bit would be useful.

**Comment by bashtage** [comment]
> With packbits an index operation is not possible any more. But I think the ML library needs such an index access. That's why I thought a dtype of bit would be useful.

Packed bits are never fast to access.  When you use slices or indexing NumPy uses memory addresses to rapidly subset an array. With packed bits it will always take more computations (memory address math plus applying a mask to the result).  Providing an array-like container that supports all of NumPy would require a substantially different container than the `ndarray` and would probably need support from a 3rd party library. It would probably also need the ML library to directly support using packed data.

Have you raised this scenario on the ML's github issue tracker?

**Comment by tweber68** [comment]
> Have you raised this scenario on the ML's github issue tracker?

Not yet. I will do this. If it's of interest, I could give feedback here...

**Comment by bashtage** [comment]
I suspect an array-like container with packed bit storage is too far from the internals of NumPy to warrant inclusion in NumPy, so the fastest way to get support would be to have support added in downstream projects.

**Comment by tweber68** [comment]
Thank you very much as well for your reply on https://github.com/statsmodels/statsmodels/issues/7935 ! I was already thinking about using partial_fit(). I think, this could be a solution for my problem (although it's not available in all models).

**Comment by seberg** [comment]
Yeah, unfortunately, numpy's memory model relies on byte-sized element sizes.  And since that is public, there is no way to really change that.  So it is interesting, but there is no clear way to do anything about it in NumPy.

I had some ideas about adding bit-size information to dtypes and then ignoring it in NumPy itself.  But have not done it yet, because much of the API is pointer based, so I think you would effectively need to double the DType API with a second set of bitstored-DType API.  (In general, you could imagine bit-sized storage to be padded to bytes normally, but a special container could pack it to bits.)

The main use-case is to store bools as bits.  Maybe that is just special enough to be special (although certain small sized integers are also less common use-cases).

**Comment by tweber68** [comment]
I see that a bitstored-DType API would be a big change in NumPy. So probably adding a feature enabling sparse arrays in the statsmodels (see https://github.com/statsmodels/statsmodels/issues/7935) would make more sense. **NumPy is not a BoolPy.** Perhaps this formula could be the quintessence of this discussion. :-)

**Comment by seberg** [comment]
@tweber68 I should have explained more, my viewpoint is that I am moving more things into an abstracted "DType API" right now (largely finished).  That API is obviously byte based, everything else seems inconvenient, I would not be able to even use it in NumPy.

But, I could imagine that someone comes along and says: I want to use NumPy compatible DTypes, but _also_ use them for my new, shiny, bit-sized element aware container!  And I would be happy to allow you to do that in some form (which we would need to figure out, but it might just be giving you some extra space to store more API on the DType).

But yeah, that has to be a transfer of things from outside NumPy into NumPy for the sake of a better ecosystem compatibility.  The only real thing I am considering as a possibility would be to add storage for "bit-size" to our dtypes just to make API evolution to a possible future where it exists easier.

**Comment by tweber68** [comment]
@seberg Have I correctly understood: the DType API would be part of NumPy? 

>  I want to use NumPy compatible DTypes, but also use them for my new, shiny, bit-sized element aware container!

Yes, that sounds good.

> But yeah, that has to be a transfer of things from outside NumPy into NumPy for the sake of a better ecosystem compatibility. 

The problem is as well, that currently statsmodels additionally converts a uint8-based NumPy array to float64-based NumPy array. I think, this problem can lastly only be solved in statsmodels. My matter was just to formulate a problem. As well, I don't know if NumPy in itself can find a solution for it. At least, it sounds difficult to me. But if you were working on a solution, I would be very interested!

**Comment by seberg** [comment]
Not working on a solution, offering to collaborate or help with one only (assuming this seems a useful approach)...  The major push has to come from outside of NumPy unfortunately.

**Comment by seberg** [comment]
Basically just as `arr.dtype.bit_itemsize` additionally to `arr.dtype.itemsize`.  And by default (so always for the mid-term), we fill it in with `8 * itemsize`.  The only reason to do it earlier rather than later is that evolving C-APIs to grow additional fields may be a bit painful.  (It may not be painful enough to worry about anyway, I have not thought about it quite enough)

**Comment by tweber68** [comment]
@seberg For now, I cannot say, if this is useful. In my case I would just prefer a dtype `bit`. But perhaps this is the first step for developping a bitstored DType-API, which in my point of view would be nice. Perhaps can someone else add a comment?

**Comment by loneosama** [comment]
one thing that I didn't see or might have missed in the above discussion is that to store data in bits, and then operate upon it would need C bitwise operations as well. That first of all will add another level of complexity in the overall project, second bitwise is also dependant on the platform (big vs little-endian). You will then face those issues as well. so this will require major rewrites in many places at worst or at best many new functions for these operations.

**Comment by tweber68** [comment]
Foy my usecase, it would be sufficient, if NumPy treats the bitstored 1s and 0s as numbers. Bitwise operations would not be necessary. 

But all looks like this would be a big change in NumPy to make 1s and 0s stored in bits. Another point: Perhaps in most of the cases, some columns are in bits, others in int8, others in float64, etc. As far as I can see, NumPy allows only one dtype for all the columns. So perhaps only allowing `bit` as dtype would not solve the problem in lots of cases. You would have to allow simultaneously multiple dtypes for different columns. But this would be just a bigger change.

**Comment by seberg** [comment]
Going to close this.  There are some interesting points about bit sized dtypes, but I just don't think there is much to be done in NumPy right now, and NumPy arrays will not hold bit-sized dtypes in the forseeable future:  This would be a large project with careful planning, and it may not even be feasible at all.
It is an interesting topic, though, but e.g. discuss.scientific-python.org is probably a more useful place to try to pursue it (I do think it requires a new "champion" to get anywhere though, unfortunately).
