### ISSUE TITLE
why can't I find numpy pip ? and how can i install it ?

### ISSUE THREAD

**Issue by rifaterdemsahin** [numpy/numpy#20555]
I installed NumPy like this in my docker container running in the azure pipelines

MY DOCKERFILE

# first install that did not work

RUN python3.7 -m pip install numpy==1.19.5 --user

#installed over coda that did not work

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh

RUN chmod +x Miniconda3-py37_4.10.3-Linux-x86_64.sh

RUN bash ./Miniconda3-py37_4.10.3-Linux-x86_64.sh -b -p /miniconda

RUN /miniconda/bin/conda init bashRUN . ~/.bashrc

RUN /miniconda/bin/conda install numpy

ERROR

import numpy as np

E ModuleNotFoundError: No module named 'numpy'

=========================================================================== warnings summary ============================================================================

.tox/py/lib/python3.7/site-packages/_pytest/config/__init__.py:1233

/azp/_work/1/s/.tox/py/lib/python3.7/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: collect_ignore

self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs:https://docs.pytest.org/en/stable/warnings.html

======================================================================== short test summary info ========================================================================

ERROR tests/test_point_cloud_generator.py

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

====================================================================== 1 warning, 1 error in 0.10s ======================================================================

ERROR: InvocationError: '/azp/_work/1/s/.tox/py/bin/pytest --basetemp=/azp/_work/1/s/.tox/py/tmp'

________________________________________________________________________________ summary ________________________________________________________________________________

ERROR: py: commands failed

-----------------------------------------------------------------------------------------------------------------------------------------------------

INSIDE RUNNING CONTAINER

When i check it after logging into azure container instances

root@wk-caas-9f35aafff42b448e99ee2fa01cbcdace-4b890e4cb6367b7b99ef18:/azp/_work/1/s# pip3 show numpy

Name: numpy

Version: 1.19.5

Summary: NumPy is the fundamental package for array computing with Python.

Home-page:https://www.numpy.org

Author: Travis E. Oliphant et al.

Author-email:

License: BSD

Location: /usr/local/lib/python3.7/dist-packages

Requires:

Required-by: csbdeep, h5py, imageio, matplotlib, numba, numpy-quaternion, open3d, opencv-contrib-python, openmesh, pandas, plyfile, pytools, PyWavelets, qck-cv-cameras,qck-cv-shared, scikit-image, scikit-learn, scipy, tifffile, trimesh

root@wk-caas-9f35aafff42b448e99ee2fa01cbcdace-

Maybe i have a none compatible Numpy ?

https://sourceforge.net/projects/numpy/files//NumPy/1.5.0/NOTES.txt/view

Also asked in here
https://www.reddit.com/r/learnpython/comments/rcio65/why_cant_i_find_numpy_pip/hnus18m/?context=3

**Comment by mattip** [comment]
This is the NumPy issue tracker, and you are using many tools around numpy:
- conda
- docker
- pip

so the issue really belongs on stackoverflow and not here. With that, I notice the following:
- In your docker file, typically one uses RUN to set up the docker environment, ENV to set environment variables, and then CMD to run a command at the end. I am not sure where your ENV and CMD rules are. If you are using conda, you will need to modify your ENV and CMD to make sure that conda environment you have created will be used.
- When you enter the docker container and run `pip3 show numpy`, are you sure you have activated the conda environment? Typically we encourage people to run `python3 -m pip ...` instead to emphasize that pip is a package installed in a particular python environment, not a general OS command like `apt install`.

**Comment by seberg** [comment]
Closing the issue, it has been a while and seems to be a setup issue, not a NumPy issue.  Matti has given some useful tips to try and understand it.
