### ISSUE TITLE
BUG: Build wheel in docker with took very long time when adding a particular parameter "--platform linux/arm/v7"

### ISSUE THREAD

**Issue by lothian173** [numpy/numpy#20550]
### Describe the issue:

Build a normal python numpy wheel docker image takes 30-60 seconds (python 3.8 or 3.9), however when docker build command added a parameter **"--platform linux/arm/v7"**, this building numpy wheel process takes more than 11 hours in the exactly same environment.

Environment: Windows 10, debian virtual environment, docker, Apple MBP 2015, i7-4770HQ, 16GB memory with 512 SSD hard disk.

### Reproduce the code example:

```python
Replication to this issue:
(1). Create a python file name as main.py, define any numpy array, add a line system console output. Save and close。
(2). Create a docker file:
FROM python:3.9-buster
WORKDIR /app
COPY . .
RUN pip install --upgrade pip setuptools wheel
RUN apt-get update \
    && apt-get install -y \
    && pip install numpy
CMD ["python", "main.py"]

(3). Execute command:  docker build **--platform linux/arm/v7** -t <image id>, after the waiting for 11 hours this building numpy wheel still running, the output refer to the error message section.
(4). Stop the building process. Remove the parameter and run docker build again, the building of wheel can be done within a few minutes.
```

### Error message:

```shell
...
 => [4/5] RUN apt-get update     && apt-get install -y     && pip install numpy     41061.9s
 => => # Building wheels for collected packages: numpy
 => => #   Building wheel for numpy (PEP 517): started
 => => #   Building wheel for numpy (PEP 517): still running...
 => => #   Building wheel for numpy (PEP 517): still running...
 => => #   Building wheel for numpy (PEP 517): still running...
```

### NumPy/Python version information:

numpy.__version__, sys.version:
`1.21.2 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]`

**Comment by mattip** [comment]
If I understand correctly, you are trying to use docker to emulate a 32-bit arm machine on windows? There are a couple of problems here:
- we do not provide 32-bit ARM wheels, so you have to rebuild from source
- as far as I know, ARM 32-bit emulation is severely limited: you may not be able to use enough memory to cleanly compile, so you may be swapping memory to disk
- since the instruction set is different, emulation will always be much much slower

Can you run other programs successfully with this setup?

**Comment by lothian173** [comment]
> If I understand correctly, you are trying to use docker to emulate a 32-bit arm machine on windows? There are a couple of problems here:
> 
> * we do not provide 32-bit ARM wheels, so you have to rebuild from source
> * as far as I know, ARM 32-bit emulation is severely limited: you may not be able to use enough memory to cleanly compile, so you may be swapping memory to disk
> * since the instruction set is different, emulation will always be much much slower
> 
> Can you run other programs successfully with this setup?

Hi Mattip, 

Thank you for your fast reply, actually I read the comment just after you post and I was thinking about the issue.

Yes my coding is done on my laptop (x86_64 GNU/Linux - 64bits). I am also running docker on a Raspberry pi 4 (ARM 64 bits) as target host however its default OS is 32 bits, hence I tried to add --platform 32 bits parameter in the build. 

When I build the image on the Windows laptop, it is using a debian emulator and the parameter --platform linux/arm/v7 (which request the build to run on a specified 32 bit platform). Since as you mentioned, the Numpy does not provide 32-bit ARM wheels at the moment, the building of wheel is needed and it falls into the issue.

I will try to upgrade Docker target OS to 64 bits and try again, kindly close this issue at the moment.

Thank you.
