### ISSUE TITLE
BUG: `numpy.dot` produces two distinct outputs depending on CPU model

### ISSUE THREAD

**Issue by joshuacwnewton** [numpy/numpy#20564]
### Describe the issue:

In our project, we started to see hardware-specific test failures in our GitHub Actions runners: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3597

After a lot of sleuthing, we determined that the differences in our test results ultimately stemmed from minute differences in the results of `numpy.dot`: 

* We came up with a reproducible example, then ran it repeatedly on GitHub Actions. 
* We noticed that we got exactly 2 distinct outputs for `np.dot` depending on the CPU model. (One of those outputs corresponded to a pass for our overall test suite, while the other output corresponded to a fail.)
* We found that there was one model of Xeon Platinum CPU that consistently produced the "failing" result, while the remaining models of CPUs produced the "passing" result. 
* We also tried locally with our personal PCs, and were able to find additional models that produced those same 2 results.

Here is a summary of the CPU models that produced the two distinct results we found:

* **Failing result**: [Sample Actions run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/1564695723/attempts/1)
    * Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
       * NB: My theory here is that GitHub Actions VMs started using this CPU in November 2021, hence why we started seeing test failures all of a sudden. 
    * Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
       * NB: Somehow we were lucky enough to find an older CPU that produces the same result as the Xeon Platinum.
* **Passing result**: [Sample Actions run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/1564695723/attempts/2)
    * Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
    * Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    * Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
    * Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
    * Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    * Intel(R) Core(TM) i7-7700HQ CPU @ 2.80Ghz
    * There are likely many, many more... this was by far the most common behavior on our machines, and when retrying GitHub Actions runs.

Then, we tried comparing the CPU flags to see if there were any flags that were present in all the passes, but absent from of the failures (and vice versa). We found that passes had the flag `md_clear`, but none of the failures had it:

<details>

```python
flags_fail_i5_3320M = set(['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'dts', 'acpi', 'mmx', 'fxsr', 'sse', 'sse2', 'ss', 'ht', 'tm', 'pbe', 'syscall', 'nx', 'rdtscp', 'lm', 'constant_tsc', 'arch_perfmon', 'pebs', 'bts', 'rep_good', 'nopl', 'xtopology', 'nonstop_tsc', 'cpuid', 'aperfmperf', 'pni', 'pclmulqdq', 'dtes64', 'monitor', 'ds_cpl', 'vmx', 'smx', 'est', 'tm2', 'ssse3', 'cx16', 'xtpr', 'pdcm', 'pcid', 'sse4_1', 'sse4_2', 'x2apic', 'popcnt', 'tsc_deadline_timer', 'aes', 'xsave', 'avx', 'f16c', 'rdrand', 'lahf_lm', 'cpuid_fault', 'epb', 'pti', 'tpr_shadow', 'vnmi', 'flexpriority', 'ept', 'vpid', 'fsgsbase', 'smep', 'erms', 'xsaveopt', 'dtherm', 'ida', 'arat', 'pln', 'pts'])
flags_fail_xeon_8370C = set(['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'mmx', 'fxsr', 'sse', 'sse2', 'ss', 'ht', 'syscall', 'nx', 'pdpe1gb', 'rdtscp', 'lm', 'constant_tsc', 'rep_good', 'nopl', 'xtopology', 'cpuid', 'pni', 'pclmulqdq', 'ssse3', 'fma', 'cx16', 'pcid', 'sse4_1', 'sse4_2', 'movbe', 'popcnt', 'aes', 'xsave', 'avx', 'f16c', 'rdrand', 'hypervisor', 'lahf_lm', 'abm', '3dnowprefetch', 'invpcid_single', 'fsgsbase', 'bmi1', 'hle', 'avx2', 'smep', 'bmi2', 'erms', 'invpcid', 'rtm', 'avx512f', 'avx512dq', 'rdseed', 'adx', 'smap', 'avx512ifma', 'clflushopt', 'clwb', 'avx512cd', 'sha_ni', 'avx512bw', 'avx512vl', 'xsaveopt', 'xsavec', 'xgetbv1', 'xsaves', 'avx512vbmi', 'umip', 'avx512_vbmi2', 'gfni', 'vaes', 'vpclmulqdq', 'avx512_vnni', 'avx512_bitalg', 'avx512_vpopcntdq', 'rdpid', 'arch_capabilities'])

# NB: Only some of the passes were checked, because there were many, many passing CPU models
flags_pass_i7_6700 = set(['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'dts', 'acpi', 'mmx', 'fxsr', 'sse', 'sse2', 'ss', 'ht', 'tm', 'pbe', 'syscall', 'nx', 'pdpe1gb', 'rdtscp', 'lm', 'constant_tsc', 'art', 'arch_perfmon', 'pebs', 'bts', 'rep_good', 'nopl', 'xtopology', 'nonstop_tsc', 'cpuid', 'aperfmperf', 'pni', 'pclmulqdq', 'dtes64', 'monitor', 'ds_cpl', 'vmx', 'smx', 'est', 'tm2', 'ssse3', 'sdbg', 'fma', 'cx16', 'xtpr', 'pdcm', 'pcid', 'sse4_1', 'sse4_2', 'x2apic', 'movbe', 'popcnt', 'tsc_deadline_timer', 'aes', 'xsave', 'avx', 'f16c', 'rdrand', 'lahf_lm', 'abm', '3dnowprefetch', 'cpuid_fault', 'epb', 'invpcid_single', 'pti', 'ssbd', 'ibrs', 'ibpb', 'stibp', 'tpr_shadow', 'vnmi', 'flexpriority', 'ept', 'vpid', 'ept_ad', 'fsgsbase', 'tsc_adjust', 'bmi1', 'hle', 'avx2', 'smep', 'bmi2', 'erms', 'invpcid', 'rtm', 'mpx', 'rdseed', 'adx', 'smap', 'clflushopt', 'intel_pt', 'xsaveopt', 'xsavec', 'xgetbv1', 'xsaves', 'dtherm', 'ida', 'arat', 'pln', 'pts', 'hwp', 'hwp_notify', 'hwp_act_window', 'hwp_epp', 'md_clear', 'flush_l1d'])
flags_pass_xeon_E5_2673 = set(['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'mmx', 'fxsr', 'sse', 'sse2', 'ss', 'ht', 'syscall', 'nx', 'pdpe1gb', 'rdtscp', 'lm', 'constant_tsc', 'rep_good', 'nopl', 'xtopology', 'cpuid', 'pni', 'pclmulqdq', 'ssse3', 'fma', 'cx16', 'pcid', 'sse4_1', 'sse4_2', 'movbe', 'popcnt', 'aes', 'xsave', 'avx', 'f16c', 'rdrand', 'hypervisor', 'lahf_lm', 'abm', '3dnowprefetch', 'invpcid_single', 'pti', 'fsgsbase', 'bmi1', 'hle', 'avx2', 'smep', 'bmi2', 'erms', 'invpcid', 'rtm', 'rdseed', 'adx', 'smap', 'xsaveopt', 'md_clear'])
flags_pass_xeon_8171M = set(['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'mmx', 'fxsr', 'sse', 'sse2', 'ss', 'ht', 'syscall', 'nx', 'pdpe1gb', 'rdtscp', 'lm', 'constant_tsc', 'rep_good', 'nopl', 'xtopology', 'cpuid', 'pni', 'pclmulqdq', 'ssse3', 'fma', 'cx16', 'pcid', 'sse4_1', 'sse4_2', 'movbe', 'popcnt', 'aes', 'xsave', 'avx', 'f16c', 'rdrand', 'hypervisor', 'lahf_lm', 'abm', '3dnowprefetch', 'invpcid_single', 'pti', 'fsgsbase', 'bmi1', 'hle', 'avx2', 'smep', 'bmi2', 'erms', 'invpcid', 'rtm', 'mpx', 'avx512f', 'avx512dq', 'rdseed', 'adx', 'smap', 'clflushopt', 'avx512cd', 'avx512bw', 'avx512vl', 'xsaveopt', 'xsavec', 'xsaves', 'md_clear'])

# Flags present in all 3 passes
flags_pass = flags_pass_i7_6700.intersection(flags_pass_xeon_8171M).intersection(flags_pass_xeon_E5_2673)

# Flags present in passes that are not in failures
flags_pass_not_in_i5 = flags_pass.difference(flags_fail_i5_3320M)
print(flags_pass_not_in_i5)
{'rtm', 'avx2', 'rdseed', 'md_clear', 'abm', 'bmi1', 'smap', '3dnowprefetch', 'bmi2', 'invpcid_single', 'hle', 'pdpe1gb', 'invpcid', 'adx', 'movbe', 'fma'}
flags_pass_not_in_xeon = flags_pass.difference(flags_fail_xeon_8370C)
print(flags_pass_not_in_xeon)
{'pti', 'md_clear'}

# Flags present in passes that are not in either of the failures
flags_pass_not_in_fail = flags_pass_not_in_i5.intersection(flags_pass_not_in_xeon)
print(flags_pass_not_in_fail)
{'md_clear'}
```

</details>

I'm not sure if `md_clear` is a red herring or not, though. But, if you consider that the 2 "failing" CPUs are quite different, the fact that they still had this in common stood out to me.

Anyways, I decided to stop here and report upstream.

### Reproduce the code example:

Please use the following `.npy` files along with the code below to reproduce the issue: [array-files.zip](https://github.com/numpy/numpy/files/7694582/array-files.zip)

```python
import numpy as np

array1 = np.load('array1.npy')
array2 = np.load('array2.npy')
array_dot = array1.dot(array2)

# Test against the "failing" dot product
# On Xeon(R) Platinum 8370C, array_dot should match array_fail, so the tests will fail
array_fail = np.load('result-fail.npy')
print(f"Matches cached 'fail' array: {np.array_equal(array_dot, array_fail)}")

# Test against the "passing" dot product
# On other CPUs, array_dot typically matches array_pass, so the tests will pass
array_pass = np.load('result-pass.npy')
print(f"Matches cached 'pass' array: {np.array_equal(array_dot, array_pass)}")

# Comparing array_pass to array_fail to get a sense of the scale of the differences
diff = array_pass - array_fail
print(diff)
# [[ 7.84313725e-10 -4.67388741e-30  2.69524250e-18  0.00000000e+00]
#  [-9.03617181e-30  0.00000000e+00 -3.20555339e-28  2.84217094e-14]
#  [-2.52468930e-18 -2.00786430e-28 -2.22044605e-16  0.00000000e+00]
#  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
```

### Error message:

```shell
N/A
```

### NumPy/Python version information:

We encountered this issue on a few different setups, provided below as a sample:

##### Machine 1 (pass)
1.18.5 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0]

##### Machine 2 (fail)
1.19.5 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]

##### Machine 3 (pass)
1.19.5 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]

There are likely many more, but I stopped here...

**Comment by charris** [comment]
Small differences of a few ulp are to be expected for floating point. Different compilers, different instruction ordering, different libraries, and other such things all contribute to that. I don't know if it can be affected by microcode, but possibly. The hard problem is deciding when the differences are big enough to be considered software errors :)

**Comment by joshuacwnewton** [comment]
> Small differences of a few ulp are to be expected for floating point. Different compilers, different instruction ordering, different libraries, and other such things all contribute to that. I don't know if it can be affected by microcode, but possibly. The hard problem is deciding when the differences are big enough to be considered software errors :)

That's very fair. I had a feeling that would be the case when I realized the scale that was involved here.

What was curious to me, though, is that we encountered exactly 2 distinct sets of results. When I was debugging this, my assumption was that there would have been a lot of different outcomes (for the reasons you describe). But, precisely 2 outcomes, reproduced on two separate CPUs? It struck me as very interesting!

(But, "interesting" is probably different than "worth spending the time on", hehe. :P)

**Comment by seberg** [comment]
Dot is offloaded to BLAS, implemented by openblas (or something else, depending on your setup).  In any case, any efficient BLAS implementation has special kernels specific to the CPU/system it runs on for maximum speed.
Other things could vary, but you probably just see this type of differences (I would not be sure that you can't see difference on the same system even, e.g. due to different data alignment).

Closing, thanks for going through the trouble to report it, but this seems all in order.  There are testing function in `numpy.testing` to check for approximate equality and equality up to a few ULPs:, e.g. `assert_array_almost_equal_nulp`.  Hopefully that can be helpful for you to work around different systems doing different things.
