### ISSUE TITLE
BUG: `np.sort(..., kind="stable")` for some `int8`/`int16` arrays is incorrect

### ISSUE THREAD

**Issue by honno** [numpy/numpy#20567]
### Describe the issue:

Some arrays of 8 and 16 width ints don't sort correct when stable sort specified. Can't quite identify the pattern, but it seems like unordered inputs containing a mix of positive and negative elements can trigger it.

This also affects `array_api.sort`, which uses stable sort by default so this gets annoying fast heh. cc @asmeurer 

### Reproduce the code example:

```python
>>> np.sort(np.asarray([0, -1], dtype=np.int8), kind="stable")
array([ 0, -1], dtype=int8)      # should be [-1, 0]
...
# different dtypes
>>> np.sort(np.asarray([0, -1], dtype=np.int16), kind="stable")
array([ 0, -1], dtype=int8)      # int16 also incorrect
>>> np.sort(np.asarray([0, -1], dtype=np.int32), kind="stable")
array([-1,  0], dtype=int32)     # int32 and int64 seem to work fine
...
# related examples
>>> np.sort(np.asarray([-1, 0], dtype=np.int8), kind="stable")
array([-1,  0], dtype=int8)
>>> np.sort(np.asarray([-1, -2], dtype=np.int8), kind="stable")
array([-2, -1], dtype=int8)
>>> np.sort(np.asarray([10, -10], dtype=np.int8), kind="stable")
array([ 10, -10], dtype=int8)    # incorrect
>>> np.sort(np.asarray([1, 0], dtype=np.int8), kind="stable")
array([0, 1], dtype=int8)
>>> np.sort(np.asarray([0, -1, -2], dtype=np.int8), kind="stable")
array([-2, -1,  0], dtype=int8)
>>> np.sort(np.asarray([0, -2, -1], dtype=np.int8), kind="stable")
array([ 0, -2, -1], dtype=int8)  # incorrect
```

### NumPy/Python version information:

1.23.0.dev0+144.g4d6e41879 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]

**Comment by charris** [comment]
Probably due to change to use  c++ templates and a missing test we should have :) @serge-sans-paille Thoughts?

**Comment by charris** [comment]
It is a radix sort and it looks like it is sorting the signed bytes as unsigned bytes. Could be a bad dispatch, or a bad comparison.

**Comment by WarrenWeckesser** [comment]
A git bisect says the first bad commit is https://github.com/numpy/numpy/commit/2ae7aeb3aa909b1a16bc58fd0e40dc4476dff35d

**Comment by charris** [comment]
Argsort fails in the same way.

**Comment by serge-sans-paille** [comment]
My fault. I'll investigate.

**Comment by serge-sans-paille** [comment]
#20569 fixes the issues and adds a test case
