### ISSUE TITLE
ENH: Accelerating np.sort with parallel support

### ISSUE THREAD

**Issue by pierre-weiss** [numpy/numpy#20575]
### Proposed new feature or change:

While transforming Matlab code to Python code with numpy, I came across something very surprising to me.

The np.sort function is not parallelized at all and Matlab code is 7 times faster than numpy on my problem.

I described/identified the problem there at first:
https://stackoverflow.com/questions/70332850/numpy-sort-much-slower-than-matlab-sort

Now, I turn to developers to know if it is possible to change the numpy core sort functions :
https://github.com/numpy/numpy/tree/main/numpy/core/src/npysort

to add parallelization.

**Comment by charris** [comment]
I'll just note that boost offers parallel sorts, but I'm not particularly happy with the complexity of same.

**Comment by rgommers** [comment]
Re parallelization: we cannot do that for `sort` or other individual functions before we have an overall design/decision to allow parallel code in NumPy. At this time, everything is single-threaded (except the underlying BLAS/LAPACK library - OpenBLAS/MKL/etc.).

> PR #20133 uses hardware vectorization and speeds up quicksort by nearly 14x.

That seems like the best way forward indeed.

**Comment by rgommers** [comment]
@pierre-weiss do you mind if we close this issue? It's not actionable in the near future.

**Comment by pierre-weiss** [comment]
This is fine with me. I don't really know the usual processes for numpy
development and your answer is perfectly clear. Thanks a lot for your
commitment to this beautiful library.

Best regards,
Pierre

**Comment by rgommers** [comment]
Thanks Pierre.
