### ISSUE TITLE
BUG: np.argsort not returning correct order

### ISSUE THREAD

**Issue by RodrigoVillatoro** [numpy/numpy#20574]
### Describe the issue:

The resulting order of np.argsort appears to be incorrect and does not match with the order returned by x[argsort_idx]. 

Specifically, when sorting in descending order, the highlighted number should be in position 11, not 9. 
![Screenshot 2021-12-13 at 10 49 06](https://user-images.githubusercontent.com/4619414/145800130-2a1be2f3-7bff-4dea-8b2e-7ea3b2e265ba.png)

Strangely enough, this results in the correct ordering of the values: 
![Screenshot 2021-12-13 at 11 15 27](https://user-images.githubusercontent.com/4619414/145800374-87243c1b-3cfa-40ad-b696-79d43d952e85.png)

Not entirely sure what can be going on here. Thanks! 

### Reproduce the code example:

```python
import numpy as np

x = np.array([ 26.929932  ,  17.864126  ,   5.439558  ,  -0.10773016,
        -9.52839   ,  -7.620389  , -11.919527  , -15.451256  ,
       -16.36096   , -18.313873  , -19.791018  , -18.288052  ,
       -21.068373  , -24.030613  , -23.9124    , -25.630302  ,
       -29.34889   , -29.329416  , -29.221819  , -26.609049  ,
       -29.375376  , -28.213442  , -28.636854  , -28.140215  ,
       -27.100985  ])

# Returns incorrect order of indices
list(zip(x, np.argsort(-1*x)))

# Returns correct order of list
x[np.argsort(-1*x)]
```

### NumPy/Python version information:

numpy 1.18.1
python 3.7.10

**Comment by seberg** [comment]
Argsort does not return ranks, it returns sorting indices to be applied to the input.  So the `zip()` does not make any sense, because the order of the argsort result is *sorted* and not the original data order.

**Comment by RodrigoVillatoro** [comment]
You are completely right. Thank you!

**Comment by eric-wieser** [comment]
Duplicate of #8757
