### ISSUE TITLE
DOC: typo in basics.types.rst

### ISSUE THREAD

**Issue by Freed-Wu** [numpy/numpy#20581]
### Issue with current documentation:

In <https://github.com/numpy/numpy/blob/main/doc/source/user/basics.types.rst?plain=1#L261-L262>

```rst
``long double``\\; in particular, the 128-bit IEEE quad precision
data type (FORTRAN's ``REAL*16``\\) is not available.
```

`\\` is unnecessary.

### Idea or request for content:

``` rst
``long double``; in particular, the 128-bit IEEE quad precision
data type (FORTRAN's ``REAL*16``) is not available.
```

**Comment by melissawm** [comment]
Thanks for catching that @Freed-Wu - are you willing to submit a PR to fix this?
