### ISSUE TITLE
ENH: Would numpy like some free MFA tokens from Google and GitHub via OpenSSF?

### ISSUE THREAD

**Issue by david-a-wheeler** [numpy/numpy#20584]
### Proposed new feature or change:

Hi! I work with the [Developer Best Practices Working Group](https://github.com/ossf/wg-best-practices-os-developers) of the Linux Foundation's Open Source Security Foundation (OpenSSF) ["Great Multi-Factor Authentication (MFA) Distribution Project"](https://github.com/ossf/great-mfa-project).

We'd like to give your project *free* MFA hardware tokens from Google and GitHub, for use by your maintainers.  We'd especially like to give them to any of your maintainers who aren't already using any.  Our goal is to help improve the security of open source software (OSS)/Free Software projects.  For example, these tokens can counter attacks that release source code updates and/or packages using stolen passwords.

By **2021-12-20** and preferably much sooner, please let me know:

1. If you want any tokens, and if so...
2. How many Titan tokens from Google (up to 5)
3. How many Yubikey tokens from GitHub (up to 5)
4. The *private* email address to send codes to (this email must *not* go to the public, as these are use-once codes that can be used to get the tokens)
5. If you could use more, how many more.

We would send you coupon codes and validation codes to the private email address.  You would then distribute those codes to the maintainers you choose.  The recipients would use the coupon codes and validation codes to "buy" the tokens from the Google Store and/or GitHub Shop, who would ship the tokens directly to recipients.  These codes are use-once, so make sure you can keep the codes private until they're used by the intended person.

**Important**: The Google coupon codes **must be used by 2021-12-31** on the Google Store or they expire.

How can you trust us? You don't need to. You would get the MFA tokens from Google and GitHub; we're simply offering codes to make them no-cost.  We'll provide some documentation on how to use them, but you don't need to use our documents.

To qualify, each token recipient must:

1. Be a maintainer or contributor to this critical open source software (OSS) project, or to another OSS project that this project depends on (the dependency may be indirect).
2. Try to use an MFA token once they receive the token.  We'd like recipients to use MFA tokens from then on, but at least try.
3. Not reuse the token between different people (the token must not be shared).
4. Consider providing feedback to us (so we can try to fix problems).

We also need each project that receives coupon codes and/or validation codes
to tell us these numbers (preferably within 30 days of getting the codes):

1. How many tokens did you distribute from just Google? From just GitHub?
2. How many people received tokens from just Google? From just GitHub?  From both?
3. How many people didn’t have hardware tokens they used for OSS who received tokens from just Google? From just GitHub? From both?

We ask for this information so we can tell others some simple measures of success. We don't need nor want the names of any individuals participating. It's fine to ask the people who got the codes for that information and provide a best-effort summary.

The MFA tokens are shipped from the US.  They can be shipped internationally, but there are various limitations on where each can be shipped.

In particular, we can't ship somewhere if that is forbidden (sanctioned) under US law.  So at this time we are unable to ship to individuals in China, Afghanistan, Russia, Ukraine, North Korea, Iran, Sudan, and Syria.  Sorry about that.  See the Google and GitHub sites for more shipping information.  [More sanction information is available](https://home.treasury.gov/policy-issues/financial-sanctions/sanctions-programs-and-country-information).

For more information including how-tos and other setup information can be found at the ["Great Multi-Factor Authentication (MFA) Distribution Project" site](https://github.com/ossf/great-mfa-project).

**Comment by rgommers** [comment]
Thanks @david-a-wheeler, and apologies for the slow reply. Looks like we have only a few days left.

My main question is: why would we want to use dedicated hardware tokens, rather than a standard 2FA app (e.g., Authy)? Sorry if it's obvious, but it's not addressed in the links you posted.

Related: I would like us to get better about enabling 2FA(=MFA) on GitHub and PyPI, because still not everyone with access has done that - which is bad for security.

**Comment by david-a-wheeler** [comment]
A 2FA app is better than a simple password. However, hardware tokens are stronger still. Apps are much easier to "take over" because the underlying system (phone/computer) is running other apps, which can sometimes be used to attack the underlying system & steal the keys. In contrast, hardware tokens are single-use so fewer attacks work against them.

Sounds like something we should add :-).

**Comment by david-a-wheeler** [comment]
Fair point, I've added text here: https://github.com/ossf/great-mfa-project/pull/62

**Comment by rgommers** [comment]
Thanks @david-a-wheeler, that's the answer I expected. I'd like to participate in this and get a Titan key (those seem preferable to me over Yubikey, more features/protection + USB-C in addition to regular USB). Let me ping some of the folks who may also be interested and have elevated permissions somewhere - @mattip, @matthew-brett, @charris, @stefanv - can you please reply if you want a hardware key? Anyone else, @numpy/numpy-developers? (feel free to email me instead of replying here if you prefer)

@david-a-wheeler I'll send you a tally and email address by tomorrow.

**Comment by david-a-wheeler** [comment]
@rgommers - Thanks! The Titan token's coupon codes expire at the end of the year (we'll try to get more but we have no guarantees), so that's the key deadline for us. The Yubikey token validation codes don't expire at the end of the year, but the sooner we get them deployed the better :-).

**Comment by charris** [comment]
On Tue, Dec 28, 2021 at 10:46 AM Ralf Gommers ***@***.***>
wrote:

> Thanks @david-a-wheeler <https://github.com/david-a-wheeler>, that's the
> answer I expected. I'd like to participate in this and get a Titan key
> (those seem preferable to me over Yubikey, more features/protection + USB-C
> in addition to regular USB). Let me ping some of the folks who may also be
> interested and have elevated permissions somewhere - @mattip
> <https://github.com/mattip>, @matthew-brett
> <https://github.com/matthew-brett>, @charris <https://github.com/charris>,
> @stefanv <https://github.com/stefanv> - can you please reply if you want
> a hardware key? Anyone else, @numpy/numpy-developers
> <https://github.com/orgs/numpy/teams/numpy-developers>? (feel free to
> email me instead of replying here if you prefer)
>

I'll take a yubikey.

Chuck

**Comment by matthew-brett** [comment]
I'd like a Titan key, thanks.

**Comment by stefanv** [comment]
I would appreciate a Titan key, thank you!

**Comment by mattip** [comment]
I would also appreciate a Titan key, thank you!

**Comment by matthew-brett** [comment]
Feel free to switch me to Yubikey if that's easier.

**Comment by rgommers** [comment]
Thanks for the answers everyone. I expect maybe 1-2 more people to want one, but given it's close to the deadline let's go ahead. If that's okay I'll ask for one extra Yubikey for a straggler. Also I forgot to include a few maintainers of our key dependencies or build infra: @martin-frbg, @scoder, @isuruf please comment on let me know if you'd like an MFA hardware token.

@david-a-wheeler could you send me the codes for 5 Titan and 2 Yubikey tokens at `ralf.gommers@gmail.com` please? I'll distribute them to people who asked, and aggregate the information you wanted afterwards.

**Comment by scoder** [comment]
Happy to get one, either would do.

**Comment by david-a-wheeler** [comment]
I'm working to get the Titan codes out ASAP.

**Comment by rgommers** [comment]
I received the codes, thanks @david-a-wheeler.

> They can be shipped internationally, but there are various limitations on where each can be shipped.
>
> In particular, we can't ship somewhere if that is forbidden (sanctioned) under US law.

Probably a more important limitation for Titan is https://cloud.google.com/titan-security-key#section-5. I tried various Google Play stores, but none will ship to the Netherlands (or abroad in general, the list of supported countries is: Austria, Canada, France, Germany, Italy, Japan, Spain, Switzerland, the UK, and the US). Looks like @mattip and I will be out of luck there (unless we do some indirect shipping via one of those countries).

**Comment by mattip** [comment]
YubiKey is easier?

**Comment by rgommers** [comment]
> YubiKey is easier?

Yep, it says the GitHub Store can ship internationally.

**Comment by david-a-wheeler** [comment]
Google & GitHub both ship internationally, but it appears that Google can ship to fewer locations. Sorry for the trouble.

If anyone originally asked for a Titan key from Google, but that won't work for some reason, please just make it clear how many Yubikeys from GitHub you'd like instead. We'll then send the GitHub validation codes instead. Just let me know what email addresses to send them to! Privately let me know which Google coupon codes you are *not* using, in case we can reuse them elsewhere - you can contact me at dwheeler @ linuxfoundation.org .

**Comment by rgommers** [comment]
Okay, we've taken action here, I'll close the issue. If anyone still wants an MFA device, please let me know by the end of tomorrow.

Thanks again for opening this issue and for working on this initiative @david-a-wheeler.

**Comment by seberg** [comment]
I would also e happy to try out either of the keys. So Yubikey seems good (I did not check into the differences).

**Comment by rgommers** [comment]
Thanks @seberg, I requested one for you.

The window has now closed - most of the people who have rights on PyPI are getting a key, as are most of the people with Admin rights on GitHub. So from that perspective it looks like a good security upgrade for NumPy.
