### ISSUE TITLE
TST: Bump mypy to 0.920

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#20597]
[Mypy 0.920](https://github.com/python/mypy/releases/tag/v0.920) was released earlier today; the pinned version should be bumped once 0.920 is available on both pypi and conda-forge:

- [x] [pypi](https://pypi.org/project/mypy/0.920/)
- [x] [conda-forge](https://anaconda.org/conda-forge/mypy/files?version=0.920)

**Comment by BvB93** [comment]
Ideally we could put this in for the 1.22.0 release, but this will largell depend on when the conda-forge 0.920 release is available.

**Comment by charris** [comment]
Unfortunately, 0.920 isn't backwards compatible.

**Comment by charris** [comment]
I marked this for 1.21.5 just so I can find it if needed.
