### ISSUE TITLE
python libraries for Incomplete Cholesky Factorization

### ISSUE THREAD

**Issue by TiantianUpup** [numpy/numpy#20606]
### Proposed new feature or change:

 don't find library which can perform incomplete cholesky factorization in python,it can only perform complete cholesky factorization,example
```
np.linalg.cholesky(b)
```

**Comment by melissawm** [comment]
In any case, I believe this would be a better fit for scipy.linalg instead.

**Comment by bashtage** [comment]
scipy.linalg is definitely the best place for alternative methods.

**Comment by rgommers** [comment]
Agreed, this is for `scipy.linalg` and out of scope for NumPy - so closing the issue.
