### ISSUE TITLE
BUG: numpy.product fails to multiple arrays with shapes (A, 1) and (A, B)

### ISSUE THREAD

**Issue by lzkelley** [numpy/numpy#20612]
### Describe the issue:

Multiplying arrays with shapes `(A, 1)` and `(A, B)` should broadcast to `(A, B)`, just like `(1, B) x (A, B) ==> (A, B)`, however when using `np.product` the first example fails while the second succeeds.  If you manually create arrays `aa` with shape `(A, 1)` and `bb` with shape `(A, B)`, you can successfully multiple them by doing either `aa * bb` or `np.multiply(aa, bb)`, only `np.product([aa, bb], axis=0)` fails.

This seems like a bug, but if it's "intended" behavior then perhaps at least the docstrings should reflect this behavior.

### Reproduce the code example:

```python
import numpy as np

aa = [
    np.array([[1.0], [2.0]]),
    np.array([[1.0, 2.0, 3.0]])
]
bb = [
    np.array([[1.0]]),
    np.array([[1.0, 2.0, 3.0]])
]

print([a.shape for a in aa])
print(f"Success: {np.product(aa, axis=0)=}")
print("--")
print([b.shape for b in bb])
print(f"Success: {bb[0] * bb[1]=}")
print(f"Success: {np.multiply(*bb)=}")
print(f"Failure: {np.product(bb, axis=0)=}")
```

### Error message:

```shell
[(2, 1), (1, 3)]
/Users/lzkelley/anaconda3/envs/py39/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Success: np.product(aa, axis=0)=array([[1., 2., 3.],
       [2., 4., 6.]])
--
[(1, 1), (1, 3)]
Success: bb[0] * bb[1]=array([[1., 2., 3.]])
Success: np.multiply(*bb)=array([[1., 2., 3.]])
Traceback (most recent call last):
  File "/Users/lzkelley/Programs/kalepy/numpy_bug.py", line 18, in <module>
    print(f"Failure: {np.product(bb, axis=0)=}")
  File "<__array_function__ internals>", line 5, in product
  File "/Users/lzkelley/anaconda3/envs/py39/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3751, in product
    return prod(*args, **kwargs)
  File "<__array_function__ internals>", line 5, in prod
  File "/Users/lzkelley/anaconda3/envs/py39/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3051, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/Users/lzkelley/anaconda3/envs/py39/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: could not broadcast input array from shape (3,) into shape (1,)
```

### NumPy/Python version information:

1.21.4 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 20:33:18) 
[Clang 11.1.0 ]

**Comment by lzkelley** [comment]
It looks like the code just sends things to `numpy.multiply.reduce`, and the [ufunc docstring](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduce.html) specifically says it will produce the same results as (in this case),

```
r = multiply.identity
for i in range(len(A)):
  r = op(r, A[i])
return r
```

However, again if you do this explicitly with the above examples it *works correctly*.

**Comment by rkern** [comment]
Note that the input to `prod()` and `multiply.reduce()` is an `array_like`. If you give it a list, the argument must first be converted to an array. The error message that you see with `bb` is from converting it to an array first, not the operation of `prod()/multiply.reduce()` per se.

```
|9> np.array(bb)                                                                                                                                                                                                     
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-6076c663cd3f> in <module>
----> 1 np.array(bb)

ValueError: could not broadcast input array from shape (3) into shape (1)
```

Converting lists of sequences or other arrays into one big array is a complicated business. We have rules that are largely intended to detect when a user is trying to construct a multidimensional array. Those rules do fall down a bit when the user is trying to construct an object array of arrays, as you implicitly do here. Sometimes it works (see the result of `np.array(aa)`), but sometimes it falls down because the _main_ use case is to construct a big multidimensional array, and it can be hard to discern whether you _wanted_ it to give up and give an array of array objects or if there was a user error in creating a unified multidimensional array.

Consider using `functools.reduce(np.multiply, bb)` for this use case.

**Comment by lzkelley** [comment]
Thanks for your reply @rkern, but I don't understand why that would only impact one of the examples (`bb`) and not the other (`aa`).

**Comment by rkern** [comment]
As I said, the rules that we use to infer the shape that the user intended to create are complicated and don't always capture every intent. The intent that it inferred when the first object it encounters in `aa` was shape `(2,1)` was different from the intent that inferred for `bb` where the first object was shape `(1,1)`. See [`PyArray_DiscoverDTypeAndShape`](https://github.com/numpy/numpy/blob/7125cdfa21081b91907a65b6c888791cf150a0b2/numpy/core/src/multiarray/array_coercion.c#L1134) for the entrypoint for this logic.

In general, if you want to use object arrays of other arrays, we recommend that you construct them more explicitly (`bb2 = np.empty(2, dtype=object); bb2[:] = bb`) and not rely on passing lists of arrays to functions.

**Comment by lzkelley** [comment]
This seems to be somewhere between a bug and a difficult-to-docstring-indirect-behavior, so I will close the issue.

The simplest workarounds are:

```
prod = np.multiply.identity
for i in range(len(bb)):
  prod = np.multiply(prod, bb[i])
```

or (re)creating the argument to an array of objects explicitly first:

```
temp = np.empty(len(bb), dtype=object)
temp[:] = bb
prod = np.product(temp)
```

**Comment by rkern** [comment]
`functools.reduce(np.multiply, bb)` is a simpler way to write the first one.

**Comment by seberg** [comment]
For devs: We had deprecated all of these weirder "ragged" related paths since 1.20 now (some with visibledeprecationwarning, some odder ones not).
Should I look into just removing them now, or do they seem relevant enough to keep a bit longer?  It would be nice to finally close this for the most part :).

**Comment by mattip** [comment]
I think we should wait a bit more. We deprecated in 1.20, so two years would mean the deprecation expires for 1.24.
