### ISSUE TITLE
DOC: 'PyArray_FailUnlessWriteable' is not included in the C API documentation

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#20623]
### Issue with current documentation:

The function `PyArray_FailUnlessWriteable` (added in https://github.com/numpy/numpy/pull/280) does not show up in the [C API documentation](https://numpy.org/devdocs/reference/c-api/index.html).  The function is defined in
https://github.com/numpy/numpy/blob/bb95cf015165bcf85f99ba0d28a7a6e727ca955b/numpy/core/src/multiarray/arrayobject.c#L622-L645

**Comment by mattip** [comment]
It appears this was never properly documented.

I wonder if we can get the documentation out of the header file using the [doxygen workflow](https://numpy.org/devdocs/dev/howto-docs.html#documenting-c-c-code) by reformatting the header and putting a directive in the c-api rst file

**Comment by WarrenWeckesser** [comment]
For now, I added `PyArray_FailUnlessWriteable` to `doc/source/reference/c-api/array.rst` in gh-20647.  Automating the build process for the C API documentation is a great idea, but it is not a project that I plan to take on.

**Comment by mattip** [comment]
> Automating the build process for the C API documentation

Ahh, but it is already automated. All that is required is to properly format the docstring, and to add a directive in the rst to use it.

**Comment by mattip** [comment]
I am working on a PR to #20647
