### ISSUE TITLE
`numpy.repeat` work when the axis is magic number and beyond the dimension range of input

### ISSUE THREAD

**Issue by TestSomething22** [numpy/numpy#20620]
### Describe the issue:

`numpy.repeat` work when the axis is magic number, like 32, and beyond the dimension range of input. It should raise an error. However, when `axis >= 2` and `axis != 32`, it will fail as expected.

### Reproduce the code example:

```python
import numpy
res = numpy.repeat([[0, 0], [0, 0]], repeats=1, axis=32)
print(res)
# [0 0 0 0]
```
Obviously, it should raise an error because `axis=32` is beyond the dimension of input, which is 2. Besides, when `axis >= 2` and `axis != 32`, it will fail as expected. So `32` may be a magic number.

### Error message:

```shell
Result is `[0 0 0 0]`. 
```

### NumPy/Python version information:

1.20.3 3.9.6 (default, Jun 29 2021, 05:25:02) 
[Clang 12.0.5 (clang-1205.0.22.9)]

**Comment by seberg** [comment]
Agreed. 32 (max dims) is (sometimes) used on the C-side for what would be `axis=None` is python, IIRC.  So this should be just changed or deprecated.

**Comment by saswatpp** [comment]
@seberg if we change the default value of axis to `NULL`(rather than `NPY_MAXDIMS`) at the C-side, and similarly in [PyArray_CheckAxis](https://github.com/numpy/numpy/blob/main/numpy/core/src/multiarray/ctors.c#L2888), will it be helpful ?

**Comment by seberg** [comment]
Axis is an integer, so it is not possible to set it to NULL.  My guess is that `PyArray_AxisConverter` needs to check for this up-front.  We should maybe make it a deprecation even, since it seems like basically everything will accept 32/maxdims to meant he same as `axis=None`.

**Comment by seberg** [comment]
Closing, since the deprecation is now merged.
