### ISSUE TITLE
DOC: No doc showing for "np.iterable"

### ISSUE THREAD

**Issue by mocquin** [numpy/numpy#20626]
### Issue with current documentation:

Typing "iterable" in the doc website search bar doesn't show any relevant result regarding the actual "numpy.iterable" function : see [here](https://numpy.org/doc/stable/search.html?q=iterable#)

**Comment by Mukulikaa** [comment]
Thanks for bringing this to our attention @mocquin, seems like it was missed in the documentation. The docstrings do exist at: https://github.com/numpy/numpy/blob/e3b831cd85e2f4d73b0db8e8d501828b50a96c64/numpy/lib/function_base.py#L347-L383

You can also access it with `>>> help(np.iterable)`.
