### ISSUE TITLE
ENH: reduce the overhead of the checks in the multinomial function

### ISSUE THREAD

**Issue by zephyr111** [numpy/numpy#20636]
### Proposed new feature or change:

Hello,

We have [discovered](https://stackoverflow.com/questions/70428623) a performance regression of the `numpy.random.multinomial` function for small arrays apparently caused by the commit 0f3dd0650 which add new checks. The checks are expensive regarding their purpose (especially for small arrays). This can be reproduced with Python 3.9.9 on a x86-64 machine using both Windows and Linux. Is there a way to reduce the overhead of such checks?

For more information, please read [this Stack-Overflow post](https://stackoverflow.com/a/70430803/12939557).

Thank you.

**Comment by mattip** [comment]
Saving a click: this microbenchmark
```
import numpy as np
from timeit import timeit
res = timeit('np.random.multinomial(1, [0.1, 0.2, 0.3, 0.4])', 
             number=1000000, globals=globals())
print(f'numpy version {np.__version__}: {res:.1f} seconds')
```

gives these results:
```
numpy version 1.16.6:  1.5 seconds # 10x faster
numpy version 1.18.1: 15.5 seconds
numpy version 1.19.0: 17.4 seconds
numpy version 1.21.4: 15.1 seconds
```

The commit was part of the enormous PR #13163 to integrate randomgen into numpy.

**Comment by mattip** [comment]
A very good and extensive analysis of the overhead is given by in the linked StackOverflow post linked to above, the analysis points to this line in `mtrand.pyx` causing 75% of the overhead https://github.com/numpy/numpy/blob/7acb0fd4123673dc38aa5634b47f93770e61cfab/numpy/random/mtrand.pyx#L4249

and this line as responsible for 20% more https://github.com/numpy/numpy/blob/7acb0fd4123673dc38aa5634b47f93770e61cfab/numpy/random/mtrand.pyx#L4278

The analysis also points out that calling multinomial 1,000,000 times for a single value in a tight loop is not a good design pattern.

**Comment by mattip** [comment]
Changing the code to use the new Generator 
```
rng = np.random.default_rng()
res = timeit('rng.multinomial(1, [0.1, 0.2, 0.3, 0.4])', 
             number=1000000, globals=globals())
```

produces the same result since the similar code exists in `_generator.pyx`. The function  `check_array_constraint` contains calls to `np.any`, `np.all`, and more which are not nicely optimized by Cython. They call back to the Python C-API to look up the `np.any` and `np.all` functions in numpy and call them with `PyOjbect*`. 

We could refactor `check_array_constraint` faster by avoiding the C-API. I think using a 1d memory view and explicitly looping might work, but would make the code much more unwieldy.

**Comment by bashtage** [comment]
The `check_constraint` can probably be improved since this is for scalars.  

https://github.com/numpy/numpy/blob/01079e29caaad17ddf855d125cc4f47f7a1f8203/numpy/random/_common.pyx#L400-L402

I suspect the `np.` calls are not optimized by Cython.

**Comment by bashtage** [comment]
Annotated Cython shows this is exactly the case:

![image](https://user-images.githubusercontent.com/5585221/147071848-0139af92-fe09-4e95-a985-3a5d5cfe94c5.png)

There are a couple of places where Python API are used that could be pretty easily avoided.

**Comment by bashtage** [comment]
Fixing the performance of the array checker in a tidy manner is a lot harder since the type of the array being checked is not always the same, and so would need paths for different possible types.

**Comment by wguocbp** [comment]
Just installed the latest numpy and it works like a charm, thank you all for the fix and the unexpected fast turnaround, really impressed!

**Comment by mattip** [comment]
Closing since we improved what we can. @zephyr111 please open a new issue or reopen this one if you have an idea for more preformance improvements.
