### ISSUE TITLE
DOC: numpy.ndindex examples have incorrect formatting

### ISSUE THREAD

**Issue by Freed-Wu** [numpy/numpy#20658]
### Issue with current documentation:

In <https://numpy.org/doc/stable/reference/generated/numpy.ndindex.html#numpy.ndindex>, Examples has incorrect format:

```
# dimensions as individual arguments >>> for index in np.ndindex(3, 2, 1): … print(index) (0, 0, 0) (0, 1, 0) (1, 0, 0) (1, 1, 0) (2, 0, 0) (2, 1, 0)

# same dimensions - but in a tuple (3, 2, 1) >>> for index in np.ndindex((3, 2, 1)): … print(index) (0, 0, 0) (0, 1, 0) (1, 0, 0) (1, 1, 0) (2, 0, 0) (2, 1, 0)
```

**Comment by Mukulikaa** [comment]
The examples have been correctly formatted since then in the development version- https://numpy.org/devdocs/reference/generated/numpy.ndindex.html#numpy.ndindex
