### ISSUE TITLE
BUG: numpy.any() raises TypeError with dtype timedelta64/datetime64 

### ISSUE THREAD

**Issue by theOehrly** [numpy/numpy#20661]
### Describe the issue:

A type error is raised when calling `numpy.any()` on an array with dtype timedelta64 or datetime64.

The documentation shows the following example:

```
>>> np.any([-1, 0, 5])
True
```

I would have assumed that this works with datetime/timedelta too.

### Reproduce the code example:

```python
import numpy as np 

a = np.array([np.datetime64('2021-12-26'), np.datetime64('2021-12-27')])
np.any(a)
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 1, in Exec
    def Exec(exp, global_vars, local_vars=None):
  File "<input>", line 1, in <module>
  File "<__array_function__ internals>", line 2, in any
  File "C:\Dateien\Code\CTT\venv\lib\site-packages\numpy\core\fromnumeric.py", line 2268, in any
    @array_function_dispatch(_any_dispatcher)
  File "C:\Dateien\Code\CTT\venv\lib\site-packages\numpy\core\fromnumeric.py", line 69, in _wrapreduction
    def _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs):
TypeError: No loop matching the specified signature and casting was found for ufunc logical_or
```

### NumPy/Python version information:

1.21.5 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

**Comment by seberg** [comment]
Thanks for the report.  The old system was not really able to deal with the awkwardness of logical "reductions" (which are not quite reductions in some sense).  The new system can: This works in NumPy 1.22 (which will be released within a month.

**Comment by theOehrly** [comment]
That's great. Thank you for the quick response

**Comment by theOehrly** [comment]
Can confirm this is fixed. Thanks
