### ISSUE TITLE
BUG: Allow using -std=c++0x on older compilers

### ISSUE THREAD

**Issue by th0ma7** [numpy/numpy#20664]
### Describe the issue:

Using latest version 1.22.0-rc3 `setup.py` enforce c++11 such as:
```
build_info['extra_cxxflags'] = ['-std=c++11']
```
Using Synology toolchain for packages under the SynoCommunity umbrella there are old compilers, oldest being 4.6.4.  Building using theses older toolchains requires passing `-std=c++0x` option.  This works on most old gcc 4.x with one exception being gcc-4.6.4 as it doesn't recognize the `-std=c++11` flag (as both flags ends-up being passed).

The ask would be to have the option of passing `-std=c++0x` for older gcc-4.x versions while keeping `-std=c++11` for newer ones.

Reference SynoCommunity PR: https://github.com/SynoCommunity/spksrc/pull/4998

### Reproduce the code example:

```python
n/a
```

### Error message:

```shell
INFO: arm-marvell-linux-gnueabi-g++: numpy/core/src/umath/clip.cpp
  cc1plus: warning: command line option '-std=c99' is valid for C/ObjC but not for C++ [enabled by default]
  cc1plus: error: unrecognized command line option '-std=c++11'
  cc1plus: warning: command line option '-std=c99' is valid for C/ObjC but not for C++ [enabled by default]
  cc1plus: error: unrecognized command line option '-std=c++11'
  error: Command "/home/spksrc/python38-others/spksrc/toolchain/syno-88f6281-6.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/spksrc/python38-others/spksrc/toolchain/syno-88f6281-6.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -I/home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install//var/packages/bazarr/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install/var/packages/bazarr/target/lib -I /home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install/var/packages/bazarr/target/include -I/home/spksrc/python38-others/spksrc/toolchain/syno-88f6281-6.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -I/home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install//var/packages/bazarr/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install/var/packages/bazarr/target/lib -I /home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install/var/packages/bazarr/target/include -I/home/spksrc/python38-others/spksrc/toolchain/syno-88f6281-6.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -I/home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install//var/packages/bazarr/target/include -I/home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install/var/packages/bazarr/target/include/python3.10 -O0 -pedantic -I/home/spksrc/python38-others/spksrc/toolchain/syno-88f6281-6.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -I/home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install//var/packages/bazarr/target/include -std=c++0x -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.arm-marvell-linux-gnueabi-3.10/numpy/core/src/common -Ibuild/src.arm-marvell-linux-gnueabi-3.10/numpy/core/src/umath -Inumpy/core/include -Ibuild/src.arm-marvell-linux-gnueabi-3.10/numpy/core/include/numpy -Ibuild/src.arm-marvell-linux-gnueabi-3.10/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/crossenv/cross/include -I/home/spksrc/python38-others/spksrc/spk/bazarr/work-88f6281-6.1/install/var/packages/bazarr/target/include/python3.10 -Ibuild/src.arm-marvell-linux-gnueabi-3.10/numpy/core/src/common -Ibuild/src.arm-marvell-linux-gnueabi-3.10/numpy/core/src/npymath -c numpy/core/src/umath/clip.cpp -o build/temp.arm-marvell-linux-gnueabi-3.10/numpy/core/src/umath/clip.o -MMD -MF build/temp.arm-marvell-linux-gnueabi-3.10/numpy/core/src/umath/clip.o.d -std=c99 -std=c++11 -D__STDC_VERSION__=0 -fno-exceptions -fno-rtti" failed with exit status 1
  INFO:
  ########### EXT COMPILER OPTIMIZATION ###########
  INFO: Platform      :
    Architecture: armhf
    Compiler    : gcc
  
  CPU baseline  :
    Requested   : 'min'
    Enabled     : none
    Flags       : none
    Extra checks: none
  
  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : none
    Generated   : none
  INFO: CCompilerOpt.cache_flush[817] : write cache to path -> /tmp/pip-wheel-jkkk0tuc/numpy_1f30966c62ff4e3ebc9a0f3259124654/build/temp.arm-marvell-linux-gnueabi-3.10/ccompiler_opt_cache_ext.py
  INFO:
  ########### CLIB COMPILER OPTIMIZATION ###########
  INFO: Platform      :
    Architecture: armhf
    Compiler    : gcc
  
  CPU baseline  :
    Requested   : 'min'
    Enabled     : none
    Flags       : none
    Extra checks: none
  
  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : none
    Generated   : none
  INFO: CCompilerOpt.cache_flush[817] : write cache to path -> /tmp/pip-wheel-jkkk0tuc/numpy_1f30966c62ff4e3ebc9a0f3259124654/build/temp.arm-marvell-linux-gnueabi-3.10/ccompiler_opt_cache_clib.py
  ----------------------------------------
  ERROR: Failed building wheel for numpy
```

### NumPy/Python version information:

1.22.0-rc3

**Comment by mattip** [comment]
Did this used to work and broke in 1.22?

I seem to recall a discussion about dropping support for gcc4 compilers.

**Comment by charris** [comment]
> I seem to recall a discussion about dropping support for gcc4 compilers.

I  dropped manylinux1 for 1.21.5 because the c++ support was lacking, a mistaken backport caused that problem.  I don't know what version of gcc is needed, but apparently the meaning of `auto` changed somewhere along the line. If it is simply a flag problem it might be fixable, but it would be preferable if Synology could upgrade. Maybe they have a backwards compatibility problem?

**Comment by th0ma7** [comment]
As for synology with the DSM7 they updated to gcc-7.x which solves many of theses problems.  But doing so they also dropped a few archs which are will not be updated anymore (besides a few remaining DSM6 security patches).

The hope here for SynoCommunity is to continue supporting these relatively old but still decent archs with an OS `minus 1` version (we dropped DSM5 whcih is ` minus 2`).  In this case specifically, I believe all is needed is ability to flip between `-std=c++0x` for older gcc-4.x versions while keeping `-std=c++11` for newer ones.

I was looking at the code and it already does that in `setup.py` into the `get_build_overrides()` function.  All is needed (and really looking at thing naively) is to re-use this into `numpy/core/setup.py` to adjust the `extra_cxx_compile_args` variable.

**Comment by th0ma7** [comment]
@charris and @mattip I've been searching for ways to tell gcc to discard unknown options but no luck yet.
I also came accross this: _In versions pre-g++ 4.7, you'll have to use -std=c++0x, for more recent versions you can use -std=c++11._

Would be nice to have this ?regression? fixed for 1.21.next / 1.22.  Thnx in advance.

**Comment by th0ma7** [comment]
Looking at current issues I noticed that this one #20761 seems to be related or duplicate.

**Comment by charris** [comment]
> fixed for 1.21.next / 1.22.

The c++ dependency in 1.21.5 was a mistaken backport, 1.21.4 should have no c++. For 1.22, the idea was to require c++11+ for the introduction of c++. If an earlier version of c++ works we could maybe loosen the requirement, but that may be very compiler dependent.

**Comment by th0ma7** [comment]
Issue is still there.
Last known working version: 1.21.5
Issue on version: 1.22.0-1.22.3

**Comment by th0ma7** [comment]
This is no longer necessary as older platforms toolchains have been deprecated.
