### ISSUE TITLE
DOC: Example section of `numpy.ndindex` is not in a codeblock

### ISSUE THREAD

**Issue by Objectivitix** [numpy/numpy#20667]
### Issue with current documentation:

In the "Examples" section of <https://numpy.org/doc/stable/reference/generated/numpy.ndindex.html#numpy.ndindex>, the lines of code are not formatted correctly. It seems like they are not enclosed in a codeblock.
![image](https://user-images.githubusercontent.com/79152594/147418412-f9143009-1cff-4893-80e3-b3348965ea28.png)

**Comment by WarrenWeckesser** [comment]
This issue is a duplicate of https://github.com/numpy/numpy/issues/20658.  As noted in the duplicaed issue, that docstring of `ndindex` has already been fixed.  (The PR that fixed the issue is https://github.com/numpy/numpy/pull/19186.)

**Comment by Objectivitix** [comment]
Got it, thank you!
