### ISSUE TITLE
Improve docs for writing new ufuncs (e.g. explain GIL issues) (Trac #1470)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2067]
_Original ticket http://projects.scipy.org/numpy/ticket/1470 on 2010-05-02 by trac user kishor.iitr, assigned to @pv._

I am trying to raise an exception in ufunc, I get segmentation fault.
The data type for the functions is PyArray_DOUBLE.

Please note that if we change the type to PyArray_OBJECT then it is working fine.

**Comment by seberg** [comment]
We discussed this in the docs meeting and decided to close the issue.  One thing to point to may be https://github.com/WarrenWeckesser/ufunclab which I think is a decent example for ufuncs, I am not sure that covers the explicit issue about GIL, but basically this issue itself is super old and just doesn't top the priority right now.

The other point is that NEP 43 _does_ clarify quite a lot of these things but with new API.
