### ISSUE TITLE
DOC: Wrong backtick escaping in Development workflow guide `ci_skip`

### ISSUE THREAD

**Issue by corneliusroemer** [numpy/numpy#20676]
### Issue with current documentation:

The backticks of `ci_skip` are wrongly escaped see screenshot:
![image](https://user-images.githubusercontent.com/25161793/147678882-c0c2ca51-55a4-40ec-acf6-c4d226e20a02.png)

Here's the link to the relevant doc section: 
https://numpy.org/devdocs/dev/development_workflow.html#commands-to-skip-continuous-integration

And here's the offending code line:
https://github.com/numpy/numpy/blame/2f41a52d9b2fc70ea2bed6e04de470d854362ccd/doc/source/dev/development_workflow.rst#L208

**Comment by WarrenWeckesser** [comment]
Thanks for pointing this out, @corneliusroemer.

That paragraph attempts to nest double backticks inside text that is already within single asterisks.  According to https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html, such nesting of inline markup is not supported.

It would probably be fine to use the single asterisks around just the word `Note`.

@corneliusroemer, are you interested in submitting a pull request to fix this?
