### ISSUE TITLE
DOC: Reference Gitpod as simple alternative in building from source guide

### ISSUE THREAD

**Issue by corneliusroemer** [numpy/numpy#20679]
### Issue with current documentation:

I spent an hour trying and failing to get numpy to build from source.

I followed the documentation but failed to discover that I could just use Gitpod.

I only became aware of this as @mattip suggested it to me in a comment https://github.com/numpy/numpy/issues/20677#issuecomment-1002744924

### Idea or request for content:

The discoverability of the very helpful Gitpod setup could be improved by including a reference to it in this doc: https://numpy.org/doc/stable/dev/development_environment.html

I overlooked it here, but spent most of the time in the other doc, that's maybe why I missed it. Since Gitpod works so well and is not necessarily something one would expect to exist, having more pointers to it could help.

**Comment by InessaPawson** [comment]
Thank you for your suggestion, @corneliusroemer! We will add the info about setting up NumPy development environment with Gitpod to development_environment.html I'm glad that you found a solution that worked for you.
