### ISSUE TITLE
BUG: possible problem with np.add.accumulate on 32-bit windows

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#20699]
### Describe the issue:

In astropy, there are several failures with numpy 1.22. Most seem related to precision issues, perhaps due to the intel short vector math library. Those we can fix. A very strange one is a failure on win32 only: https://github.com/astropy/astropy/runs/4680891863?check_suite_focus=true, with the most relevant bit being:
```
>                   raw_field[1:, 1] = (np.add.accumulate(raw_field[:-1, 0]) *
                                        dtype.itemsize)
E                   TypeError: the resolved dtypes are not compatible with add.accumulate. Resolved (dtype('int32'), dtype('int32'), dtype('int32'))
```
The crucial bit seems to be a call that should be the equivalent of (sorry, don't have a windows machine so cannot test directly...),
```
np.add.accumulate(np.arange(10, dtype='>i4'))
```
On linux, this does not give any errors, though I can get the same `TypeError` by passing in an explicit dtype,
```
np.add.accumulate(np.arange(10, dtype='>i4'), dtype=np.int32)
```
This same line does not give an error on numpy 1.21.5, so that suggests this problem has to do with the new ufunc/dtype machinery, perhaps doing a wrong inference of the dtype on win32? Hence, cc @seberg.

### Reproduce the code example:

```python
import numpy as np
np.add.accumulate(np.arange(10, dtype='>i4'))
```

### NumPy/Python version information:

platform win32 -- Python 3.9.9
3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Numpy: 1.22.0

**Comment by seberg** [comment]
I will jave a look in a few days. The most likely problem is that I have an identity check in one place, but ensure NBO does not preserve identity.

**Comment by mhvk** [comment]
@seberg - thanks! We've got another strange issue on windows that may be related to some interaction between numpy 1.22.0 and the scipy fitting routines, but are still trying to track that down.

**Comment by ThomasLecocq** [comment]
same here https://github.com/obspy/obspy/issues/2921 - on python 3.8 (https://tests.obspy.org/115143/) or 3.10 (https://tests.obspy.org/115141/) windows 64bits

**Comment by seberg** [comment]
Maybe the best thing to do is to check for "no-casting" rather than relying on identity being guaranteed.  Its better to use identity, but a bit annoying to ensure and only a tiny performance difference if identity does not hold.

**Comment by seberg** [comment]
Have to still add a test, but https://github.com/numpy/numpy/pull/20729 should fix this (by simply relaxing the strict constraint, that I thought might be useful, but seems too tedious to ensure).

**Comment by mhvk** [comment]
That sounds good! It remains a bit strange the problem only occurs on windows...

**Comment by seberg** [comment]
there is an easy explanation: If your test is 32bits, then on 64bit linux you would get the upcast to 64bit behaviour (of add and multiply) and that sidesteps most of the descriptor resolution.

**Comment by mhvk** [comment]
Ah, so it is the fact that it was 32bit that was the relevant clue, not the windows. Thanks, that makes more sense! Of course, this implies the folllowing would fail, as it does, on 64-bit linux (which can be a test in #20729 perhaps):
```
In [11]: np.add.accumulate(np.arange(10, dtype=">i8"))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-b2c0b6ab3de8> in <module>
----> 1 np.add.accumulate(np.arange(10, dtype=">i8"))

TypeError: the resolved dtypes are not compatible with add.accumulate. Resolved (dtype('int64'), dtype('int64'), dtype('int64'))
```
