### ISSUE TITLE
BUG: Type annotation for np.ndindex doesn't accept tuples

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#20706]
The following should pass as far as I can tell:
```python
import numpy as np
np.ndindex((1, 2))  # error: Argument 1 to "ndindex" has incompatible type "Tuple[int, ...]"; expected "SupportsIndex"
```
### NumPy/Python version information:

1.22.0 3.10.1 (main, Dec  8 2021, 14:43:47) [GCC 9.3.0]

**Comment by BvB93** [comment]
Ah yes, there should definitely be an overload for integer tuples here.
PR has been created at https://github.com/numpy/numpy/pull/20710.
