### ISSUE TITLE
DOC: np.ndarray.argmin,argmax docstrings miss keepdims

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#20700]
### Issue with current documentation:

`np.argmin` and `np.argmax` gained a `keepdims` argument, but that has not been added to the signature in the docstrings of the corresponding methods, `np.ndarray.argmin` and `np.ndarray.argmax`.

```
In [6]: np.__version__
Out[6]: '1.22.0'

In [7]: np.ndarray.argmin?
Docstring:
a.argmin(axis=None, out=None)

Return indices of the minimum values along the given axis.

Refer to `numpy.argmin` for detailed documentation.

See Also
--------
numpy.argmin : equivalent function
Type:      method_descriptor

In [8]: a = np.arange(10).reshape(2, 5)

In [9]: a.argmin(axis=0, keepdims=True)
Out[9]: array([[0, 0, 0, 0, 0]])
```

**Comment by soma2000-lang** [comment]
@Objectivitix Can I work on this isssue?Please assign me this.

**Comment by InessaPawson** [comment]
NumPy doesn't assign issues. Just dive right in! No permission needed.

**Comment by mattip** [comment]
Closing since #20700 was merged
