### ISSUE TITLE
DOC: `__array_finalize__` arguments inconsistent between docs and interface

### ISSUE THREAD

**Issue by jcreinhold** [numpy/numpy#20717]
### Issue with current documentation:

The interface for the `__array_finalize__` method in the `ndarray` class for numpy v1.22.0 has no arguments:

https://github.com/numpy/numpy/blob/d64df4553e7763208e150d6039dcb6fd3d5ef0be/numpy/__init__.pyi#L1499

However, [the documentation for subclassing an `ndarray`](https://github.com/numpy/numpy/blob/b513957479ce8d8eeb83339ffa4a3c9b5db7885e/doc/source/user/basics.subclassing.rst#the-role-of-__array_finalize__) states that `__array_finalize__` has one argument called `obj`.

I have [code](https://github.com/jcreinhold/pymedio/blob/main/medio/base.py) that subclasses `ndarray` following the documentation (so it takes the argument called `obj`), and it appears to work with numpy v1.22.0; however, it doesn't pass type checking with mypy due to it having a different type signature than the superclass.

Note that subclasses of `ndarray` in the interface (e.g., [`recarray`](https://github.com/numpy/numpy/blob/main/numpy/__init__.pyi#L3474)) use the single argument in the `__array_finalize__` method.

Which is correct? Or is something more complicated going on under the hood that makes them both correct?

I checked the [devdocs](https://numpy.org/devdocs) and this issue is present in them as well.

### Idea or request for content:

Fix the `ndarray` interface to have one argument or add a disclaimer to the subclassing documentation if something more complicated is going on under the hood.

**Comment by BvB93** [comment]
The piece of the puzzle you're missing here is the `@property` decorator the line above, 
_i.e._ `None` is used as a read-only attribute here: https://github.com/numpy/numpy/blob/d64df4553e7763208e150d6039dcb6fd3d5ef0be/numpy/__init__.pyi#L1498-L1499

I'm don't think `None` is mentioned as a valid alternative for a proper `__array_finalize__` method, this might be something that could be documented better.

**Comment by charris** [comment]
I marked this for tracking purposes.

**Comment by jcreinhold** [comment]
Ah, yes, I did overlook the implications of the `@property` decorator. Thanks for the clarification.

I'm confused how other subclasses in the interface type check (e.g., [recarray](https://github.com/numpy/numpy/blob/main/numpy/__init__.pyi#L3474)). When I subclass `ndarray`, in my project [pymedio](https://github.com/jcreinhold/pymedio/blob/main/medio/base.py), and run mypy (v0.930), I receive the following error message (when I remove the `type: ignore` statement).

```python
medio/base.pyi:20: error: Signature of "__array_finalize__" incompatible with supertype "ndarray"  [override]
medio/base.pyi:20: note:      Superclass:
medio/base.pyi:20: note:          def __array_finalize__(self) -> None
medio/base.pyi:20: note:      Subclass:
medio/base.pyi:20: note:          def __array_finalize__(self, obj: object) -> None
```

Is there a way to fix this in the interface so the instructions for subclassing in the documentation properly type checks when implemented?

It's not clear to me that will be possible, if we need to override a method which takes no arguments with one that does, in which case the documentation should make that more explicit, IMO.

Thanks again for the help!

**Comment by BvB93** [comment]
``` python
from typing import Any, Callable

_ArrayFinalizeFunc = Callable[[Any, ndarray], object]

class ndarray:
    # Or a get-only property, that works too
    __array_finalize__: None | _ArrayFinalizeFunc  
```

Something like the code above should fix most of the issues here, as this will allow `ndarray` subclasses to use either `None` or a method with the appropriate signature. `

This will make the signature of `ndarray.__array_finalize__` a bit worse (as it is always set to `None`), but it will give less of a hassle when subclassing, which is what the attribute is intended for anyway. I suppose this is a price to pay for this weird dual-purpose here of `ndarray` as both abstract and concrete baseclass.

Unfortunately there is also some bad news here: I can't for the life of me get mypy to accept any appropriate subclass methods; there definitely seems to be a bug here:
``` python
# This works
class Foo(ndarray):
    __array_finalize__: Callable[[Foo, ndarray], None]

# This doesn't
class Bar(ndarray):
    # Signature of "__array_finalize__" incompatible with supertype "ndarray"  [override]
    def __array_finalize__(self, obj: ndarray) -> None: ...
```

**Comment by mhvk** [comment]
Ideally, `np.ndarray.__array_finalize__` would actually conform to the documentation...  It always annoyed me that I cannot safely do `super().__array_finalize(obj)` in `ndarray` subclasses, since sometimes one does not necessarily know what is above oneself; see, e.g., https://github.com/astropy/astropy/blob/640c47a42ced760ed9e44ebbc30e072668c0eb25/astropy/units/quantity.py#L531-L537

(Of course, the `np.ndarray.__array_finalize__` would simply do nothing...)

**Comment by BvB93** [comment]
Thus far it seems there are three separate being discussed issues here:
1. The lack of documentation on describing that `__array_finalize__` can be `None` instead of a method.
2. Mypy complaining about super-type incompatibility when defining a `__array_finalize__` method. 
  This should be fixed (-ish?) by https://github.com/numpy/numpy/pull/20764.
3. Does `ndarray.__array_finalize__` have to be `None` in the first place, rather than a no-op method?

The first two are quite easy to resolve, but for the third one I'm not sure what the rationale is behind having a `None`, rather than a method, by default.

**Comment by mhvk** [comment]
I thought we really should get to defining `ndarray.__array_finalize__` - it always annoyed me that it was `None` -- see #20766. With that, the typing can be clean too!
