### ISSUE TITLE
DOC: `hsplit` doc does not include special case for 1-D arrays

### ISSUE THREAD

**Issue by Objectivitix** [numpy/numpy#20711]
### Issue with current documentation:

The documentation for `hsplit` states the follows:
> `hsplit` is equivalent to `split` with `axis=1`, the array is always split along the second axis regardless of the array dimension.

This is not the case for 1-D arrays, as demonstrated by the code for `hsplit`:
```py
if _nx.ndim(ary) == 0:
        raise ValueError('hsplit only works on arrays of 1 or more dimensions')
    if ary.ndim > 1:
        return split(ary, indices_or_sections, 1)
    else:
        return split(ary, indices_or_sections, 0)
```
and by this example:
```py
>>> a = np.array([0, 1, 2, 3, 4, 5])
>>> np.hsplit(a, 2)
[array([0, 1, 2]), array([3, 4, 5])]
```

For 1-D arrays, `hsplit` is equivalent to `split` with `axis=0`, or the first axis.

### Idea or request for content:

Add a brief explanation of this special case in the documentation. (And perhaps even an extra example using a 1-D array?)

**Comment by soma2000-lang** [comment]
@Objectivitix  Can I work on this isssue?Please assign me this.

**Comment by charris** [comment]
NumPy doesn't assign people. Just work on whatever interests you, no permission needed.

**Comment by Objectivitix** [comment]
@charris So do we have approval for a PR to be created to close this issue? If @soma2000-lang would like, they can work on the PR.

**Comment by melissawm** [comment]
@Objectivitix you do not need approval - just go for it :)

**Comment by Objectivitix** [comment]
@melissawm Thank you! I'm contributing for the first time and I'm not quite familiar with the workflow of documentation changes. I see that the docs in `numpy.org` are generated from docstrings in code, so would changing them suffice? Or would I need to do some extra things?

**Comment by melissawm** [comment]
@Objectivitix that's right. After doing your changes please try to build the documentation locally to see if it renders correctly and submit your PR. Also check out our [contributor guide](https://numpy.org/devdocs/dev/index.html) and [instructions on how to build the documentation](https://numpy.org/devdocs/dev/howto_build_docs.html). Feel free to ping me if you have any questions!
