### ISSUE TITLE
ENH: Add dtype-typing support to `np.where`

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#20734]
### Describe the issue:

See https://github.com/microsoft/pyright/issues/2811

### Reproduce the code example:

```python
from typing import Any

import numpy as np
import numpy.typing as npt

RealArray = npt.NDArray[np.floating[Any]]

all_ys: RealArray = np.zeros(10)
reveal_type(all_ys)  # "ndarray[Any, dtype[floating[_64Bit]]]"
all_ys = all_ys + all_ys
reveal_type(all_ys)  # "ndarray[Any, dtype[floating[Any]]]"
all_ys = np.where(True, all_ys, all_ys)
reveal_type(all_ys)  # "ndarray[Any, dtype[Any]]"
```

### NumPy/Python version information:

Numpy 1.22, Python 3.10

**Comment by BvB93** [comment]
Thanks for the report, dtype-typing support (xref https://github.com/numpy/numpy/issues/19252) has yet to be fully implemented, so a number of gaps will be present for now (_e.g._ `np.where` and the ufuncs).

**Comment by NeilGirdhar** [comment]
Okay, thanks for the link.  And thanks for all your work on this!
