### ISSUE TITLE
BUG: numpy False is not python False

### ISSUE THREAD

**Issue by jbrezmorf** [numpy/numpy#20744]
### Describe the issue:

Numpy bool values are different objects than Python bool value objects.
... and there is no such thing as np.false or np.False

### Reproduce the code example:

```python
import numpy as np
f = (np.array([1]) == 2)[0]
f # False
f is False # False
```

### NumPy/Python version information:

1.22.0 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

**Comment by Huntersoulz** [comment]
No, it's not a bug.
`is` operator in python checks whether both the operands refer to the same object or not (present in the same memory location).
Try using:
`import numpy as np
f = (np.array([1]) == 2)[0]
print(f) # False
print(f == False)`

**Comment by jbrezmorf** [comment]
I know how 'is' works. The issue should possibly not be marked as BUG, but the behavior is in conflict with
[PEP8 E712](https://www.flake8rules.com/rules/E712.html). It's a minuscule inconvenience, but more important is confusion 
that numpy bool is different than Python bool.
