### ISSUE TITLE
BUG: the difference between same values of different dtypes is not zero

### ISSUE THREAD

**Issue by breadbread1984** [numpy/numpy#20760]
### Describe the issue:

the difference between same values of different dtypes is not zero.

### Reproduce the code example:

```python
import numpy as np
# the difference is not zero
print(np.array(1e30).astype(np.float64) - np.array(1e30).astype(np.float32))
```

### NumPy/Python version information:

1.19.5 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

**Comment by eric-wieser** [comment]
The difference is not zero because the values are not the same; just as 1/3 rounded to 2 decimal places is not equal to 1/3 rounded to 4 decimal places, `0.33 ≠ 0.3333`.
