### ISSUE TITLE
BUG: numpy.testing now depends on numpy.distutils

### ISSUE THREAD

**Issue by bwoodsend** [numpy/numpy#20769]
### Describe the issue:

As of numpy 1.22.0, specifically after 1b5b5871c725a5b67b55d29c7361a353d8ae13ef, `import numpy.testing` implicitly imports `numpy.distutils`. The exact line that introduced this is https://github.com/numpy/numpy/commit/84e0707afa587e7655410561324ac36085db2b95#diff-657b0df76a18e77d5033e7a763d2e40a58498dee25374a90c4db9850ce2f75d3R13 which appears to load an extension module building helper (utilising `numpy.distutils`) into the `numpy.testing` namespace. This is unfortunate because, despite numpy's own usages of `numpy.testing` being avoided except when testing, downstream projects do still use it. For example `import scipy` imports `numpy.testing` (somewhat unnecessarily IMO but I'll make that case on their issue tracker) which now drags in `numpy.distutils`.

### Reproduce the code example:

```python
# Attempt to load numpy.testing after blocking imports of `numpy.distutils`.
import sys
sys.modules["numpy.distutils"] = None
import numpy.testing

# Alternatively, you can skip the sys.modules blocking and just run:
import numpy.testing
assert "numpy.distutils" not in sys.modules
# But the first provides a traceback which indicates where the import leak is.
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brenainn/.local/lib/python3.9/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from ._private import extbuild, decorators as dec
  File "/home/brenainn/.local/lib/python3.9/site-packages/numpy/testing/_private/extbuild.py", line 11, in <module>
    from numpy.distutils.ccompiler import new_compiler
ModuleNotFoundError: No module named 'numpy.distutils.ccompiler'; 'numpy.distutils' is not a package
```

### NumPy/Python version information:

```
1.22.0 3.9.6 (default, Jul 30 2021, 22:48:59) 
[GCC 11.1.0]
```
This is specific to `numpy 1.22.0`. Earlier versions of numpy did not do this.

---

Note to whoever addresses this: If this is fixed after #20745 is merged then [this conditional statement](https://github.com/numpy/numpy/pull/20745/commits/b2d4cefa9921a3704dc9bafd9f85cf00c62887c1#diff-13812225cf425294c55da63e236ea49a6e426ceb10fea4dac99ef8a49bdd3c13R40-R47) may be made unconditional.

**Comment by bwoodsend** [comment]
CC @rgommers

**Comment by mattip** [comment]
The extbuild module is needed for tests that have c code that is compiled during testing. I think it would be OK to do something like
```
from ._private import decorators as dec
try:
    from ._private import extbuild
except ImportError:
    # extbuild needs numpy.distutils, which is not always available
    extbuild = None
```
   
and then to adjust any tests that try to use extbuild to check for `None` first

**Comment by rgommers** [comment]
Thanks for looking into this @bwoodsend.

> and then to adjust any tests that try to use extbuild to check for `None` first

To make this a little more robust (import shouldn't fail for any reason other than `numpy.distutils missing`), I propose:

```python
from ._private import decorators as dec
try:
    from .. import distutils
    HAS_DISTUTILS = True
except ImportError:
    # extbuild needs numpy.distutils, which is not always available
    HAS_DISTUTILS = False

if HAS_DISTUTILS:
    from ._private import extbuild

....

@pytest.mark.skipif(not HAS_DISTUTILS, reason="builds C extension, which needs numpy.distutils")
```

**Comment by bwoodsend** [comment]
Personally I'd make the imports to `distutils` and `numpy.distutils` in `numpy.testing._private.extbuild` delayed imports:
```diff
diff --git i/numpy/testing/_private/extbuild.py w/numpy/testing/_private/extbuild.py
index 20bf3dcea..fc3916395 100644
--- i/numpy/testing/_private/extbuild.py
+++ w/numpy/testing/_private/extbuild.py
@@ -8,8 +8,6 @@
 import pathlib
 import sys
 import sysconfig
-from numpy.distutils.ccompiler import new_compiler
-from distutils.errors import CompileError
 
 __all__ = ['build_and_import_extension', 'compile_extension_module']
 
@@ -53,6 +51,7 @@ def build_and_import_extension(
     >>> assert not mod.test_bytes(u'abc')
     >>> assert mod.test_bytes(b'abc')
     """
+    from distutils.errors import CompileError
 
     body = prologue + _make_methods(functions, modname)
     init = """PyObject *mod = PyModule_Create(&moduledef);
@@ -221,6 +220,7 @@ def _c_compile(cfile, outputfilename, include_dirs=[], libraries=[],
 def build(cfile, outputfilename, compile_extra, link_extra,
           include_dirs, libraries, library_dirs):
     "cd into the directory where the cfile is, use distutils to build"
+    from numpy.distutils.ccompiler import new_compiler
 
     compiler = new_compiler(force=1, verbose=2)
     compiler.customize('')
```
Then `numpy.testing` can remain unchanged.

**Comment by bwoodsend** [comment]
> @pytest.mark.skipif(not HAS_DISTUTILS, reason="builds C extension, which needs numpy.distutils")

Are you wanting to be able to run numpy's test suite with `numpy.distutils` deleted?

**Comment by mattip** [comment]
If PyInstaller does not ship `numpy.distutils`, then users who try
```
numpy.test(tests=['numpy.core.tests.test_mem_policy'])
```

will get an error. But to be fair, without distutils user who do
```
numpy.test()
```

 will already get an error, since this line will fail when starting to run tests
https://github.com/numpy/numpy/blob/f4a3e07877eb258f69a7d65d8a3b7e8d96e1aacd/numpy/_pytesttester.py#L145

**Comment by bwoodsend** [comment]
`numpy.test(anything)` is going to fail under PyInstaller for a lot more than just that because all the test modules are dynamically imported by pytest's test discovery rather than plain `import` statements (which is all that PyInstaller recognises). To run the test suite frozen we'd need to tell PyInstaller to collect all numpy's submodules irregardless of whether it thinks they're needed or not. This defeats the purpose of testing frozen because you've boycotted PyInstaller's dependency scanner.

**Comment by QuLogic** [comment]
This also 'breaks' downstream test suites that use `np.testing` in Python 3.10 due to #20225, if they happen to do `-Werror`.

**Comment by rgommers** [comment]
> Personally I'd make the imports to `distutils` and `numpy.distutils` in `numpy.testing._private.extbuild` delayed imports:

Yes, this sounds like the best idea.

> Are you wanting to be able to run numpy's test suite with `numpy.distutils` deleted?

I don't really care about this. Deleting `numpy.distutils` is not a valid thing to do, unless you're doing something really specific like PyInstaller does - and then I don't mind if the numpy test suite runs or not (as long as numpy itself still works).

**Comment by bwoodsend** [comment]
OK, PR inbound...
