### ISSUE TITLE
DOC: <Fix the year in license>

### ISSUE THREAD

**Issue by anirudhlakhotia** [numpy/numpy#20777]
### Issue with current documentation:

The current copyright is dated 2021 :)

### Idea or request for content:

Update the license year to 2022

**Comment by rvikunwar** [comment]
hey @anirudhlakhotia , Is this a valid issue . I am a beginner in open source and want to contribute, not sure what to do next. Would you help me ??

**Comment by rkern** [comment]
This was fixed in #20783

We have [information on contributing here](https://numpy.org/contribute/).
