### ISSUE TITLE
BUG: array_api.vecdot is wrong

### ISSUE THREAD

**Issue by zerothi** [numpy/numpy#20775]
### Describe the issue:

Using the `numpy.array_api.vecdot` I get wrong results.

According to the specification the `vecdot` collapses the `axis` dimension to have `N-1` dimensions and performs dot-products along the specified axis, thus removing that axis:
https://data-apis.org/array-api/latest/API_specification/linear_algebra_functions.html#vecdot-x1-x2-axis-1

However, by using `tensordot` it extends the axis for the non-contracted axes.

### Reproduce the code example:

```python
import numpy as np

# recreated implementation (see `numpy/array_api/linalg.py`)
def vecdot(x1, x2, axis=-1):
    return np.tensordot(x1, x2, axes=((axis,), (axis,)))

a = np.random.rand(9, 10, 11)
b = np.random.rand(9, 10, 11)
c = vecdot(a, b, axis=1)
d = np.einsum('ijk,ijk->ik', a, b)
assert d.shape == (9, 11)
# This will fail, the output shape will be (9, 11, 9, 11)
assert c.shape == (9, 11), c.shape
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/nicpa/test.py", line 13, in <module>
    assert c.shape == (9, 11), c.shape
AssertionError: (9, 11, 9, 11)
```

### NumPy/Python version information:

1.21.5
3.9.9

**Comment by AnirudhDagar** [comment]
@charris I think this can be closed. It was fixed in https://github.com/numpy/numpy/pull/21928.

**Comment by charris** [comment]
Thanks for the heads up @AnirudhDagar .
