### ISSUE TITLE
PERF: Drastically lower the overhead of `__array_function__`

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#20790]
With the advent of the FASTCALL/Vectorcall protocol, it is now much easier to drastically lower the overhead currently associated with `__array_function__` without the need to subtly change the semantics, e.g. by in-lining the "not a NumPy array" check.

Here is a branch starting a big chunk of this: https://github.com/numpy/numpy/compare/main...seberg:faster-array-function

However, it is not polished or finished, it requires still the following:
* Fixing `like=` for Python defined functions:  They are broken, I have
  one possible approach, but it is just an "idea stage".
  (should not be hard, but needs a some thought)
* Make sure the C entry-point looks and feel right, such as printing
  (I am not sure what is left to do here, maybe we can find prior art?)
* Enable pickling (should be very easy)
* Ensure PyPy compatibility if necessary
* Change all warning `stacklevel=` to one lower (in wrapped functions).
  (simple, but a lot of churn)
* General code cleanup

This may be a nice and very worthwhile project for someone interested in decreasing overheads and familiar with the Python C-API.  I do not expect any of these things to be particularly hard nuts to crack, but they may be very hard to approach without a good working knowledge of the Python C-API.

**Comment by mattip** [comment]
Since this is a performance enhancement, please add benchmarks before/after the changes.

**Comment by seberg** [comment]
I am not planning to attack this anytime soon, but agreed, we should make sure some benchmarks exists (they may, but not sure we have few "small to midsized arrays" benchmarks, concatenate sped up by 40% for me).

Fortunately, unlike e.g. SIMD, implementing this should not bloat or add much code complexity, though.

**Comment by leofang** [comment]
cc: @pentschev for vis

**Comment by eendebakpt** [comment]
@seberg I tested this some time ago, and it is a very nice performance improvement (in particular for smaller arrays). Do you have interest to pick this up gain?

Vectorcall was only introduced in python 3.9. (and internally in 3.8?). If I read https://numpy.org/neps/nep-0029-deprecation_policy.html correctly, dropping python 3.8 would be an option for the next major numpy release (e.g. 2.0?)

**Comment by seberg** [comment]
Yeah, it would be the right time now to introduce things that rely on vectorcall existing.  Not actually sure it was needed here, since I think the `tp_vectorcall` already exists in 3.8 (but don't recall).

I didn't really plan on prioritizing this, but I would be happy to review and help push it through.  I guess the list above is still correct, unless there is any oddity about moving the callable/functions to C itself.

**Comment by seberg** [comment]
Although just now I saw that cupy abuses `promote_types` for speed (which is not even correct always). And most of the reason that makes a visible difference is probably this overhead...

**Comment by seberg** [comment]
I was wrong, I looked at it :).  Updated the branch, it now does most of the things.  Should get a closish look, but the only big remaining task should be the `stacklevel=` bullet point (updating them all).

Bench results (first one is a random fluctuation, two of them are new, these are only `bench_core.Core` and `bench_dispatching`):
```
       before           after         ratio
     [23035569]       [85489550]
     <main>           <faster-array-function>
+     3.01±0.02ms       3.24±0.2ms     1.08  bench_core.Core.time_eye_3000
-      8.03±0.5μs      7.60±0.01μs     0.95  bench_core.Core.time_diagflat_l100
-      9.02±0.5μs      8.39±0.03μs     0.93  bench_core.Core.time_diagflat_l50_l50
-     3.53±0.03μs      3.27±0.01μs     0.92  bench_core.Core.time_triu_l10x10
-     3.53±0.01μs      3.26±0.02μs     0.92  bench_core.Core.time_tril_l10x10
-         774±3ns          631±1ns     0.81  bench_core.Core.time_ones_100
-     2.67±0.09μs      2.17±0.01μs     0.81  bench_core.Core.time_dstack_l
-       854±0.8ns        671±0.3ns     0.79  bench_overrides.ArrayFunction.time_mock_concatenate_many
-     2.30±0.03μs      1.70±0.02μs     0.74  bench_core.Core.time_vstack_l
-     2.01±0.02μs      1.40±0.03μs     0.70  bench_core.Core.time_hstack_l
-         261±8ns        165±0.1ns     0.63  bench_overrides.ArrayFunction.time_mock_broadcast_to_duck
-         345±1ns        204±0.5ns     0.59  bench_overrides.ArrayFunction.time_mock_concatenate_mixed
-        313±10ns        179±0.4ns     0.57  bench_core.Core.time_empty_like
-         318±1ns        174±0.3ns     0.55  bench_overrides.ArrayFunction.time_mock_concatenate_duck
-         278±3ns          149±3ns     0.54  bench_core.Core.time_can_cast
-         239±3ns        122±0.8ns     0.51  bench_overrides.ArrayFunction.time_mock_broadcast_to_numpy
-       307±0.9ns        126±0.2ns     0.41  bench_overrides.ArrayFunction.time_mock_concatenate_numpy
-         393±6ns       158±0.09ns     0.40  bench_core.Core.time_can_cast_same_kind
```

`result_type` barely changes, it is just too overloaded (although the dispatching adds to it, but it is not as simple and orthogonal of this).

**Comment by eendebakpt** [comment]
The current branch does not convert all methods to vectorcall. I converted the `np.vdot` (see https://github.com/eendebakpt/numpy/tree/vectorcall_pte). This is a method without keyword arguments, but still the vectorcall protocol is faster:
```
python -m pyperf timeit -s "import numpy as np; x=np.array([1.,2.]);" "np.vdot(x,x)"
```

Main:
```
Mean +- std dev: 796 ns +- 47 ns
```
PR
```
Mean +- std dev: 744 ns +- 24 ns
```

Perhaps the `npy_parse_arguments` can be simplified for non keyword argument methods, but even without that converting to vectorcall seems worthwhile.

Some of the methods like `arr_interp` (called from `np.interp`) are declared in `numpy/core/src/multiarray/compiled_base.h`. This is not part of the public API, so they can be converted as well?
 
@seberg If you want I can convert more methods and create a PR against your branch.

**Comment by mattip** [comment]
That seems like a 5% increase? Perhaps we should put this in and use vectorcall in a subsequent PR.

**Comment by seberg** [comment]
It is probably 0-sum without the big change... but, I do think we should just split it out, and using a bit more of vectorcall is fine by me, its not like the syntax is annoying.

Are all happy to try wrapping all functions into a C-callable?  If yes, this should be mostly ready to rumble here, besides the `stacklevel=` issue (yes, I always expect smaller followups will happen, but nothing big).

But, I would rather pull out the change to the parsing then add more right now.  Just to keep the PR a bit smaller, it will be big already anyway with the stacklevel changes.  And that is even though this is not nearly as worthwhile unless we change it also.

**Comment by eendebakpt** [comment]
Without the large update there is indeed hardly any change:

Main: `Mean +- std dev: 1.05 us +- 0.04 us`
Main + vdot to vectorcall: `Mean +- std dev: 1.04 us +- 0.04 us`
Branch: `Mean +- std dev: 796 ns +- 47 ns`
Branch + vdot to vectorcall: `Mean +- std dev: 744 ns +- 24 ns`

I will create a separate PR to convert several methods to vectorcall protocol.

**Comment by eendebakpt** [comment]
> Yeah, it would be the right time now to introduce things that rely on vectorcall existing. Not actually sure it was needed here, since I think the `tp_vectorcall` already exists in 3.8 (but don't recall).

In python 3.8 the vectorcall methods are available, but under different names (underscore). See https://docs.python.org/3/c-api/call.html#the-vectorcall-protocol, note on cpython 3.8.

Compiling the branch on python 3.8 fails, but we can probably get it working by either renaming `PyObject_Vectorcall` to `_PyObject_Vectorcall`, or creating a `#define PyObject_Vectorcall _PyObject_Vectorcall` for python 3.8 (and similar for some of the other vectorcall related objects).

Output on my python 3.8 system:
```
numpy/core/src/multiarray/arrayfunction_override.c:453:25: warning: implicit declaration of function ‘PyObject_Vectorcall’; did you mean ‘PyObject_Format’? [-Wimplicit-function-declaration]
  453 |         relevant_args = PyObject_Vectorcall(
      |                         ^~~~~~~~~~~~~~~~~~~
      |                         PyObject_Format
```

**Comment by charris** [comment]
We are dropping 3.8 in the development branch, although I've got to wonder if PyPy supports the call. @mattip, thoughts?

**Comment by seberg** [comment]
We have been using most of this for a long time (starting in 3.8), the only thing is `PyObject_Vectorcall` itself, I think pypy has it now, but I am not sure.

**Comment by charris** [comment]
We should also be moving to PyPy 3.9 soon after cibuildwheel 2.11.5 comes out.

**Comment by mattip** [comment]
> if PyPy supports the call.

PyPy should follow CPython's C-API functionality. Where it is buggy or missing, that is a problem for PyPy to resolve and should not slow down NumPy development.

**Comment by seberg** [comment]
Btw @eendebakpt since it seems right up your alley to be bothered by it.  The reason `np.result_type` is so slow, is that it does `getattr(dtype, "__array_function__")` so often and that always raises an error of course.  There isn't a funny trick to improve that failure path, is there?
(I suppose we could add a filter for `isinstance(obj, np.dtype)` in the result-type dispatcher itself...)

But it also makes sense to have `promote_types(*types)` probably (I have a start on that), or maybe just a new `common_dtype` function, but I have to hash out the API, I am not quite sure on it (because I would like to support DType classes and dtype instances).

**Comment by eendebakpt** [comment]
@seberg For which case is getting the `__array_function__` the bottleneck? I am not sure I am looking at the same thing, but here is my analysis.

There are already some fast paths, e.g. https://github.com/numpy/numpy/blob/8535df676cf52c97ad4806e0aa76aa33eeea7113/numpy/core/src/multiarray/arrayfunction_override.c#L39 and https://github.com/numpy/numpy/blob/d4b2d4f80060285ac085ea874aceaf9fa1bfb757/numpy/core/src/common/get_attr_string.h#L55 for getting the `__array_function__` quickly. 

For me
```
a=np.array([2.])
np.result_type(1, a)
```
is quite fast (about 300 ns). Slower are `np.result_type(1, a)` or `np.result_type(1, np.float32(3.))`.

The `np.float32` misses the two fast paths, so it gets to the failing `PyObject_GetAttr`. Both the `np.float32` and `int` are expensive because here: https://github.com/numpy/numpy/blob/8535df676cf52c97ad4806e0aa76aa33eeea7113/numpy/core/src/multiarray/multiarraymodule.c#L3603 those objects are converted to a numpy array. Converting a python int to a numpy array just to get the dtype (in `PyArray_ResultType`) is not very efficient. 

It depends a bit on which case you want to optimize, but two ideas:

- In `PyArray_LookupSpecial` use a `PyObject_HasAttr` first, and only if the attribute exists use a `PyObject_GetAttr`. This works if most cases are objects that do not have the `__array_function`
- In `array_result_type` avoid the conversion of the common types to arrays. One could use a cache with arrays for the common types (since we only care about the dtype of the result, not the actual array). Or put the dtype directly in the `arr` (this requires changing `PyArray_ResultType` though)
