### ISSUE TITLE
--plat-name isn't described as Windows-specific and falsely suggests it's relevant to MacOS

### ISSUE THREAD

**Issue by jeffhammond** [numpy/numpy#20812]
### Issue with current documentation:

`python3 setup.py build --help` produces this:
```
  --plat-name (-p)        platform name to build for, if supported (default:
                          macosx-10.14.6-arm64)
```
A reasonable person might infer from this that this option has some relevance to the MacOS platform they are using.

Such a person might `grep` for "plat" and get some ideas and try the following:
```
python3 setup.py build --cpu-baseline="neon" --plat-name=macosx-arm64
```
but they'd be surprised to learn that `--plat-name` is only relevant to Windows, despite the `--help` default:
```
error: --plat-name only supported on Windows (try using './configure --help' on your platform)
```

### Idea or request for content:

I just want the world to make sense.  If help tells me that `--plat-name` has a MacOS default, then it should work on MacOS.  If the option is Windows-specific, it should explicitly say that in `--help`.

**Comment by soma2000-lang** [comment]
@jeffhammond  Sorry  for  a very silly doubt but I am unable to locate the file in this huge codebase where the above changes need to be made.It would be great  if  you can help me with that

**Comment by rgommers** [comment]
Thanks for the report @jeffhammond.  `--plat-name` comes from `distutils`, and given that both `distutils` and `numpy.distutils` are deprecated, I think we won't be fixing this one.

**Comment by rgommers** [comment]
Our own `setup.py` files have now been removed completely, so I will close this issue. Thanks all!
