### ISSUE TITLE
Add xoshiro128++ and xoshiro256++ random number generators to numPy?

### ISSUE THREAD

**Issue by PeterJHaas78** [numpy/numpy#20839]
Hi, I would like to port some code from Java 17 to numPy. I am using the xoshiro256++ generator. It would be great if the xoshiro generators could be be added to the list of supported generators in numPy.

**Comment by rkern** [comment]
We are mostly not interested in adding more `BitGenerator`s to numpy itself. They can now live in external packages, like [bashtage/randomgen](https://github.com/bashtage/randomgen), which will likely welcome your contribution.
