### ISSUE TITLE
BUG: dtype TypeVar in generic functions doesn't accept np.generic subtypes.

### ISSUE THREAD

**Issue by yumasheta** [numpy/numpy#20838]
### Describe the issue:

When using a "factory pattern" generic typed function, that returns a numpy array with the dtype of the given argument, mypy complains about invalid types. However, when using a similar pattern for classes, the revealed types are correct.
I'm not sure if I'm doing something wrong here.

### Reproduce the code example:

```python
from typing import Generic, TypeVar

import numpy as np
import numpy.typing as npt

_ScalarT = TypeVar("_ScalarT", bound=np.generic)


def ndarr_factory(dtype: _ScalarT) -> npt.NDArray[_ScalarT]:
    """Return a new ndarray of given type."""
    return np.empty((), dtype=dtype)
    

a = ndarr_factory(np.float_)   # error: Value of type variable "_ScalarT" of "ndarr_factory" cannot be "Type[floating[Any]]"
reveal_type(a)  # Revealed type is "numpy.ndarray[Any, numpy.dtype[
                # def (Union[None, builtins.str, builtins.bytes, typing.SupportsFloat, typing.SupportsIndex] =)
                # -> numpy.floating[Any]]]"

class NDArrFactory(Generic[_ScalarT]):
    """Save a new ndarray of given type as attribute."""
    
    def __init__(self, arr: npt.NDArray[_ScalarT]) -> None:
        self.arr = arr
    
    def get_value(self, idx:int) -> _ScalarT:
        return self.arr[idx]
        
b = NDArrFactory(np.empty((), dtype=np.float_))
reveal_type(b)  # Revealed type is "test.NDArrFactory[numpy.floating*[Any]]"
val = b.get_value(5)
reveal_type(val)  # Revealed type is "numpy.floating*[Any]"
```

### NumPy/Python version information:

1.22.1 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]

and mypy version: 0.931

**Comment by BvB93** [comment]
Based on your example it seems your missing a `type[...]` encapsulation, as your factory function expects an `np.generic` subtype (not an instance thereof).
``` diff
+ from typing import Type

- def ndarr_factory(dtype: _ScalarT) -> npt.NDArray[_ScalarT]:
+ def ndarr_factory(dtype: Type[_ScalarT]) -> npt.NDArray[_ScalarT]:
    """Return a new ndarray of given type."""
    return np.empty((), dtype=dtype)
```

**Comment by yumasheta** [comment]
You're right! Thanks!

**Comment by jcreinhold** [comment]
@BvB93 I have a follow up question to this because I'm running into a similar problem. If I change your code to the following:

```diff
from typing import Type

- def ndarr_factory(dtype: Type[_ScalarT]) -> npt.NDArray[_ScalarT]:
+ def ndarr_factory(dtype: Type[_ScalarT] = np.float_) -> npt.NDArray[_ScalarT]:
    """Return a new ndarray of given type."""
    return np.empty((), dtype=dtype)
```

and run mypy on it, I get:

```
error: Incompatible default for argument "dtype" (default has type "Type[floating[Any]]", argument has type "Type[_ScalarT]")
```

(That is the only mypy error message; I passed no additional options to mypy and there is no configuration file in the directory in which I'm running it.)

It's not clear to me why passing `np.float_` as a default would be different than passing it as an argument. If you happen have any insight, I'd appreciate it. Or might this be a limitation of mypy?

I can break this out into another issue or open one on mypy if the issue warrants it.

**Environment**:

* mypy==0.931
* numpy==1.22.2
* python==3.9.7

**Comment by BvB93** [comment]
This is more of a general mypy problem with typevars and default parameter values, I'm afraid.
As far as I'm aware the only way of dealing with this limitation is with the help of overloads

``` python
from typing import TypeVar, overload

T = TypeVar("T")

# error: Incompatible default for argument "a" (default has type "Type[float]", argument has type "Type[T]")
def func(a: type[T] = float) -> T:
    pass

# This does work, but is also rather verbose
@overload
def func2() -> float: ...
@overload
def func2(a: type[T]) -> T: ...
def func2(a = float):
    pass
```
