### ISSUE TITLE
BUG: list indexing unexpected behavior

### ISSUE THREAD

**Issue by Leo-xh** [numpy/numpy#20848]
### Describe the issue:

![image](https://user-images.githubusercontent.com/23721828/149947163-1568e93b-e653-4c06-adf6-6bd90da08175.png)
Why is the indexed axis transposed to the first dimension in the first case?

### Reproduce the code example:

```python
import numpy as np
a = np.zeros((200,8,5,1))
a[-1, :, [0,1,]].shape # error
a[-1][:, [0,1,]].shape # right
```

### NumPy/Python version information:

1.18.5 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0]

**Comment by TimerChen** [comment]
I also meet this problem at version '1.21.2'.

**Comment by charris** [comment]
@seberg Thoughts?

**Comment by seberg** [comment]
It is not a bug, it is a known caveat of our wonky "dimension transposing" rule, together with the fact that a single integer also has to be considered an "array" for that purpose.
That is documented at the end of this section: https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing

**Comment by seberg** [comment]
To be clear, due to broadcasting rules for array indices:
```
a[-1, :, [0,1,]]
```
is exactly the same as:
```
a[[-1],:, [0,1,]]
```
And we are lost...  In some cases `np.ix_` can recover the expectation of "outer" indexing, but with slices involved it will not help much.  We would need the `arr.oindex[]` to do this in a non-surprising way.
