### ISSUE TITLE
DOC: Add a version selector

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#20841]
### Issue with current documentation:

It would be nice to add a version selector.

### Idea or request for content:

The Pydata theme we use supports this. [Here](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html?highlight=version#add-a-dropdown-to-switch-between-docs-versions) is the documentation of the feature, note the blue pulldown at the top.

This may be an opportunity to refactor the repo layouts, merging the [devdocs](https://github.com/numpy/devdocs) repo and the [doc](https://github.com/numpy/doc) repo, which means refactoring the target of the CircleCI [devdoc deploy step](https://github.com/numpy/numpy/blob/381684986a20cc5c41afb9fe4a9abc5507684305/.circleci/config.yml#L103)

@MarsBarLee

**Comment by MarsBarLee** [comment]
Thanks for making the issue! I think I try implementing after end of January, after the visual report is complete.

**Comment by melissawm** [comment]
For reference: https://github.com/scipy/scipy/pull/15380

**Comment by tupui** [comment]
@MarsBarLee feel free to ping me if you have questions or want help 😃
