### ISSUE TITLE
BUG: Incorrect typing of return values of numpy.vectorize

### ISSUE THREAD

**Issue by WKuipers** [numpy/numpy#20856]
### Describe the issue:

In https://github.com/numpy/numpy/blob/main/numpy/__init__.pyi#L3692 the return type of __call__ of a vectorized function is defined to always be NDArray[Any], but this is not the case in practice.

As mentioned in the documentation (https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html): 
>... and returns a single numpy array or a tuple of numpy arrays. 

### Reproduce the code example:

```python
a = np.array([[1.0, 2.0], [3.0, 4.0]])
def returns_tuple(a):
     return (a, a)
b: Tuple[np.ndarray] = np.vectorize(returns_tuple)(a)
```

### Error message:

```shell
Incompatible types in assignment (expression has type "ndarray[Any, dtype[Any]]", variable has type "Tuple[ndarray[Any, Any]]")
```

### NumPy/Python version information:

1.22.1 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

**Comment by BvB93** [comment]
You're right, this is something that should be fixed (xref https://github.com/numpy/numpy/pull/20858).

After some further digging it seems setting a return type to anything other than  `Any` will be difficult though, 
as whether an array or a tuple thereof is returned depends on both the vectorized function as well as the literal value of the `signature` parameter.
