### ISSUE TITLE
Import of numpy failed (Python:2.7.15, numpy:1.16.6

### ISSUE THREAD

**Issue by ahemberger** [numpy/numpy#20879]
### Steps to reproduce:

On a windows 10 machine, I have an application that has python bundled internally. In this application's script editor, I type:
```
> print sys.version
 #result:
 2.7.15 (default, May 4 2018, 07:39:01) [GCC 7.3.0 64 bit (AMD64)]
```

I would like to use numpy within this application. To try to achieve this, I install standalone python using anaconda thusly:
`> conda create --name py_2_7_15 --no-default-packages python=2.7.15`

Then, once installed, I use pip to install the appropriate numpy module:
```
>pip install numpy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                    
Collecting numpy
Using cached https://files.pythonhosted.org/packages/14/ef/9f2eeb4ff0c733ad9149f17266e388c308e171fdb8c2415dbb472e2bbc0f/numpy-1.16.6-cp27-cp27m-win_amd64.whl
Installing collected packages: numpy
Successfully installed numpy-1.16.6 
```

At this point, I can verify numpy works great by launching python and importing it:
`Python 2.7.15 |Anaconda, Inc.| (default, Feb 21 2019, 11:55:13) [MSC v.1500 64 bit (AMD64)] on win32                                                                                    Type "help", "copyright", "credits" or "license" for more information.                                                                                                                  >>> import numpy                                                                                                                                                                        >>>`

This all seems great, so I go back into my application and try doing the same thusly:
```
print sys.version
import sys
sys.path.append('C:\Users\me\.conda\envs\py_2_7_15\Lib\site-packages')
import numpy as np

```
Now, however, I'm presented with an error that brings me to this issue page:
```
Python exception: cannot import name _distributor_init
Traceback (most recent call last):
File "<string>", line 3, in <module>
File "C:\Users\me\.conda\envs\py_2_7_15\Lib\site-packages\numpy\__init__.py", line 140, in <module>
from . import _distributor_init
ImportError: cannot import name _distributor_init
```

I'm aware that what I'm trying to do is a bit of a shenanigan, but I'm curious if anyone might offer some clues as to how I might troubleshoot this? 

Thank you!

**Comment by mattip** [comment]
We don't support python2 anymore. With that, I don't think you are copy-pasting exactly what you did since
```
sys.path.append('C:\Users\me\.conda\envs\py_2_7_15\Lib\site-packages')

```

should not work, you need to use raw encoding (note the `r` before the string)
```
sys.path.append(r'C:\Users\me\.conda\envs\py_2_7_15\Lib\site-packages')

```

Doesn't your application have its own pip or a way of installing packages into it?

**Comment by rgommers** [comment]
No follow-up and nothing to fix, so I will close this.
