### ISSUE TITLE
BUG: `np.array_api.can_cast()` should not follow `np.can_cast()` behaviour

### ISSUE THREAD

**Issue by honno** [numpy/numpy#20870]
`np.array_api.can_cast()` currently just wraps `np.can_cast()`, which leads to erroneous behaviour as NumPy proper deviates from the spec. [`xp.can_cast()`](https://data-apis.org/array-api/latest/API_specification/data_type_functions.html#can-cast-from-to) specifies that the result should follow Array API type promotion rules—in the case of arrays, it shouldn't matter if elements are representable by the `to` dtype. cc @asmeurer 

```python
>>> from numpy import array_api as xp
>>> xp.can_cast(xp.bool, xp.int8)
True  # should be False
>>> xp.can_cast(xp.asarray(0, dtype=xp.uint8), xp.int8)
True  # should be False
```

**Comment by asmeurer** [comment]
Should be an easy fix to use the `_result_type` helper.
