### ISSUE TITLE
Unable to build numpy 1.19 on Windows server 2016 with python 3.10

### ISSUE THREAD

**Issue by zoj613** [numpy/numpy#20894]
### Describe the issue:

Im getting this error:
```

      File "C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m86aqya1\numpy\distutils\ccompiler.py", line 90, in <lambda>

        m = lambda self, *args, **kw: func(self, *args, **kw)

    TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
```

Here is the full CI output https://github.com/zoj613/polyagamma/runs/4945358062?check_suite_focus=true

### Reproduce the code example:

```python
building numpy 1.19 on windows with python 3.10
```

### NumPy/Python version information:

numpy 1.19, python 3.10

**Comment by charris** [comment]
NumPy 1.21.x is the first release to support Python 3.10. You will also need vs2017.

**Comment by zoj613** [comment]
> NumPy 1.21.x is the first release to support Python 3.10. You will also need vs2017.

Is it not possible to still build it with numpy 1.19 anyway as long as I have vs2017 or newer?

**Comment by mattip** [comment]
If it works for you perhaps you could comment here what changes you needed to make, in order to help others who may find this issue.

**Comment by zoj613** [comment]
What are the main differences that make it hard to compile numpy 1.19.0 in python 3.10?

**Comment by rgommers** [comment]
> What are the main differences that make it hard to compile numpy 1.19.0 for python 3.10?

There are multiple fixes scattered throughout a years' worth of commit history. I strongly recommend to not spend time on this.

I'll close this, since there is nothing to do here.
