### ISSUE TITLE
DOC: np.linalg.qr documentation example lists wrong result?

### ISSUE THREAD

**Issue by henon** [numpy/numpy#20899]
### Issue with current documentation:

The [documentation of qr](https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html?highlight=linalg) lists this example:

```python
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
A
array([[0, 1],
       [1, 1],
       [1, 1],
       [2, 1]])
b = np.array([1, 0, 2, 1])
q, r = np.linalg.qr(A)
p = np.dot(q.T, b)
np.dot(np.linalg.inv(r), p)
array([  1.1e-16,   1.0e+00]) 
```

However, when I follow the example on python 3.9 I get a different end result:

```python
>>> A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
>>> b = np.array([1, 0, 2, 1])
>>> q, r = np.linalg.qr(A)
>>> p = np.dot(q.T, b)
>>> np.dot(np.linalg.inv(r), p)
array([6.66133815e-16, 1.00000000e+00])
```

1.1e-16 vs 6.6e-16

Is the documentation wrong or outdated?

### Idea or request for content:

None

**Comment by mattip** [comment]
What operating system, where did you get NumPy?

**Comment by henon** [comment]
Windows 10, Vanilla python installation. Did a `pip install numpy`

**Comment by henon** [comment]
Is it maybe a numeric issue? This is Python 3.9 64bit

**Comment by henon** [comment]
>>> import numpy
>>> numpy.version.version
'1.19.4'
>>>

**Comment by bashtage** [comment]
The smallest value depends on the CPU and BLAS library used, so it might differ from what you see.  Ideally, it would use a more numerically stable example

**Comment by melissawm** [comment]
If anyone is interested in doing this, a good example might be:

```
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
A
array([[0, 1],
       [1, 1],
       [1, 1],
       [2, 1]])
b = np.array([1, 2, 2, 3])
q, r = np.linalg.qr(A)
p = np.dot(q.T, b)
np.dot(np.linalg.inv(r), p)
array([  1.,   1.]) 
```

**Comment by ilayn** [comment]
Given the state of the merged PR I think this can be closed if I am not missing anything.
