### ISSUE TITLE
Mac wheel builds for Python 3.8 have stopped working.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#20893]
This seems due to an environment change in azure-pipelines sometime after Jan 7.  My guess is the Python version setting environment changed from 0.193 to 0.197. It can be fixed by using `MACOSX_DEPLOYMENT_TARGET=10.14`.  Note that 10.9 has been unsupported since 2019 and 10.14 is the lowest version currently supported. We can either change to 10.14 or try to get azure to make a change so that 10.9 works again.

Thoughts?

**Comment by rgommers** [comment]
Upgrading to `10.14` should be fine. Scikit-learn has had `10.13` as the lowest supported version for a year already.

**Comment by rgommers** [comment]
This was done for NumPy 1.22.2
