### ISSUE TITLE
TYP: `concatenate` typing produces unexpected errors

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#20901]
### Describe the issue:

Running mypy against 1.22.1 on correct code produces an error.

I think `_SupportsArray` seems to be wrong, and it should be `_ArrayLike`

### Reproduce the code example:

```python
import numpy as np

a = np.array([1.0])
b = [1.0]
np.concatenate((a,b))
```
```


### Error message:

```shell
error: Argument 1 to "concatenate" has incompatible type "Tuple[ndarray[Any, dtype[Any]], List[float]]"; expected "Union[_SupportsArray[dtype[<nothing>]], Sequence[_SupportsArray[dtype[<nothing>]]], Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]]]]]"
```
```


### NumPy/Python version information:

`1.22.1 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]`

**Comment by BvB93** [comment]
I think you may have stumbled upon a mypy bug related to the special casing of tuples. The first three cases succesfully pick the appropriate overload, but the last one somehow ends up at one that's meant for [array-likes implementing `__array__`](https://github.com/numpy/numpy/blob/eee12b6fcf2b05bcdd7fc55da1a5df5d3bee9c28/numpy/core/multiarray.pyi#L295-L304) (which `list[int]` does not, hence the appearance of `<nothing>`).
``` python
import numpy as np

np.concatenate((np.array(1), np.array(1)))  # No error
np.concatenate(([1], [1]))                  # No error
np.concatenate([[1], np.array(1)])          # No error
np.concatenate(([1], np.array(1)))          # Argument 1 to "concatenate" has incompatible type
```

**Comment by bashtage** [comment]
Thanks @BvB93 . Is there a workaround, other than copying to a new array?  I tried using list instead of tuple for input but it didn't have it.  It seems to me having the array first is hitting the issue (this I can't change).

**Comment by BvB93** [comment]
> I tried using list instead of tuple for input but it didn't have it. 

I'm not sure if I'm following, does the example you provided in https://github.com/numpy/numpy/issues/20901#issuecomment-1022405221 work or does it not?

**Comment by bashtage** [comment]
No, two errors.

```python
np.concatenate([[1], np.array(1)])          #  error: Argument 1 to "concatenate" has incompatible type "List[object]"; expected "Union[_SupportsArray[dtype[<nothing>]], Sequence[_SupportsArray[dtype[<nothing>]]], Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]]]]]"
np.concatenate(([1], np.array(1)))          # Argument 1 to "concatenate" has incompatible type "Tuple[List[int], ndarray[Any, dtype[Any]]]"; expected "Union[_SupportsArray[dtype[<nothing>]], Sequence[_SupportsArray[dtype[<nothing>]]], Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[<nothing>]]]]]]]"
```

FWIW
```
mypy --version
mypy 0.931
```
```

**Comment by BvB93** [comment]
Weird, the error for the first one seems to disappear when using the numpy `main` branch (and I honestly have no idea why...).

I do think I've found the culprit though. [`ArrayLike`](https://github.com/numpy/numpy/blob/eee12b6fcf2b05bcdd7fc55da1a5df5d3bee9c28/numpy/typing/_array_like.py#L66-L74) consists four components, but it seems the last two are considered mutually exclusive. Should be easy to fix though by shuffeling the union around a bit:
* Builtin scalar types
* `__array__` implementation
* Nested sequences of builtins scalar types
* Nested sequences of `__array__` implementation

**Comment by JMMarchant** [comment]
> I think you may have stumbled upon a mypy bug related to the special casing of tuples. The first three cases succesfully pick the appropriate overload, but the last one somehow ends up at one that's meant for [array-likes implementing `__array__`](https://github.com/numpy/numpy/blob/eee12b6fcf2b05bcdd7fc55da1a5df5d3bee9c28/numpy/core/multiarray.pyi#L295-L304) (which `list[int]` does not, hence the appearance of `<nothing>`).

If it's a mypy bug, has it been raised with them? I linked them to this issue here https://github.com/python/mypy/issues/12144 but they've pushed back that it's a numpy bug and I don't have the context to know what the explicit bug is in mypy.

**Comment by jorenham** [comment]
This was indeed caused by a bug in Mypy: https://github.com/python/mypy/issues/16935

Their latest [1.11 release](https://github.com/python/mypy/blob/v1.11.0/CHANGELOG.md#mypy-111) includes a fix for this.
