### ISSUE TITLE
TYP: `flatiter` is missing `__setitem__`

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#20915]
### Describe the issue:

The typing information for `__flatiter__` does not define `__setitem__` and so attempts to assign fail.

### Reproduce the code example:

```python
import numpy as np

a = np.empty(10)
a.flat[[0,2,4,6,8]] = np.nan
```

### Error message:

```shell
`Unsupported target for indexed assignment ("flatiter[ndarray[Any, dtype[floating[_64Bit]]]]")`
```

### NumPy/Python version information:

1.22.1 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]

**Comment by BvB93** [comment]
Yes, I must have missed `__setitem__` back in https://github.com/numpy/numpy/pull/17180.
In any case, https://github.com/numpy/numpy/pull/20916 should fix the issue.
