### ISSUE TITLE
functions return NotImplemented instead of raising error (Trac #1494)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2091]
_Original ticket http://projects.scipy.org/numpy/ticket/1494 on 2010-05-27 by @josef-pkt, assigned to unknown._

examples:

    >>> np.sqrt('5')
    NotImplemented
    >>> a = np.sqrt('5')
    >>> type(a)
    <type 'NotImplementedType'>
    
    
    
    >>> np.log(np.array(['5']))
    NotImplemented
    >>> np.power(np.array(['5']),5)
    NotImplemented
    >>> np.multiply(np.array(['5']),5)
    NotImplemented

**Comment by njsmith** [comment]
This has been dealt with by #5964 / #5864.
