### ISSUE TITLE
DOC: broken link in NEP 46

### ISSUE THREAD

**Issue by stefanv** [numpy/numpy#20919]
### Issue with current documentation:

> Jupyter has logos of sponsors and institutional partners in two sections on https://jupyter.org/about. Some subprojects have separate approaches, for example sponsors are listed (by using the all-contributors bot) in the README for jupyterlab-git. For a recent discussion on that, see here.

Link to *here* is broken.

**Comment by soma2000-lang** [comment]
I am working on this @stefanv

**Comment by mattip** [comment]
Closed by #20950
