### ISSUE TITLE
DOC: update numpy.polynomial.legendre.leg2poly (AttributeError in Examples)

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy#20925]
### Issue with current documentation:

This example https://github.com/numpy/numpy/blob/8f8e14ef6150100bf2872a449877f97897b18b06/numpy/polynomial/legendre.py#L181-L189 in leg2poly throw an attribute error on `P.leg2poly(....)`, indeed, since d41fc4d518cb516c254959ca8c096bc8db2c81e9 (2012), leg2poly is not exposed in np.polynomial, and need to be explicitly imported from `np.poly....legendre`.

My guess is it's not the only example in this module that have this issue.

### Idea or request for content:

This example should likely be rewritten, in particular I'm not sure `P` is a common name for numpy.polynomial, especially since uppercase in Python are usually for classes.

**Comment by soma2000-lang** [comment]
@Carreau  I am working in this
