### ISSUE TITLE
help with implementing suggestion in manual

### ISSUE THREAD

**Issue by gmabey** [numpy/numpy#20922]
Hello all,

I am working with an obtuse file format with many segments of int16 arrays in it.  Using `numpy.memmap()` I ended up getting
```
OSError: [Errno 24] Too many open files
```
which led me to this string in the numpy manual:

https://github.com/numpy/numpy/blob/80af3a9474955aa27d6fc779e77f19e51be522dc/numpy/core/memmap.py#L34

However, I've been unable to find an example of how to accomplish this (docstrings on `numpy.ndarray.__new__()` aren't helpful) and from what I can learn about `__new__()` in general, it seems to be much more focused on subclasses ...  So a hint or example of how to complete the last line in this block (or a pointer to where I got off the rails) would be very much appreciated:
```python
fid = open(fname, 'rb+')
WHOLE_FILE=0
fid_mmap = mmap.mmap(fid.fileno(), WHOLE_FILE, access=mmap.ACCESS_READ)
array_buffer = fid_mmap[offset:offset+length_bytes]
mmap_array = numpy.ndarray.__new__(  .... , buffer=array_buffer)
```

**Comment by pletnes** [comment]
I suspect that you have run into an issue with, simply put, more open files than your OS allows. Could you check whether the answer to this stackoverflow question fixes your issue?
https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

**Comment by mattip** [comment]
When you are done with the np.memmap() you need to close it. Our tests of `memmap` use del https://github.com/numpy/numpy/blob/80af3a9474955aa27d6fc779e77f19e51be522dc/numpy/core/tests/test_memmap.py#L34-L37

It is not clear how to do this in general. Related to #13510, the discussion there goes into way more detail.

**Comment by seberg** [comment]
There is nothing wrong with using a single `mmap.mmap` and wrapping it into arrays, though  (or a single `numpy` memmap and splitting it into multiple views using slicing and `arr.view()` to change the dtype for that matter).  If you drop the `__new__` (which is should be dropped from those docs too maybe), you can check the help.  The docs seem pretty good, and all you are missing is shape and dtype.

That said, `np.frombuffer` or even `np.asarray(fid_mmap).view(new_dtype)` is maybe clearer to read.

In any case, I will close this for now.
