### ISSUE TITLE
ENH: adding `casting` option to numpy.stack

### ISSUE THREAD

**Issue by ItamarKanter** [numpy/numpy#20959]
### Proposed new feature or change:

`concatenate` and `stack` are similar methods. I think `stack` will also benefit from controlling what kind of data casting may occur

**Comment by jhonatancunha** [comment]
Hello, I want to work in this issue. Could you please give me some tips to start?

**Comment by ItamarKanter** [comment]
I think you should add a `casting` option to the stack function, and then add it in the call to `_nx.concatenate`
https://github.com/numpy/numpy/blob/bc6a6084f6e49bd78c12508131395304a63cc6ca/numpy/core/shape_base.py#L433
change to:

> return _nx.concatenate(expanded_arrays, axis=axis, out=out, casting=casting)
