### ISSUE TITLE
DOC: NEP `toctree` is mind boggling

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#20952]
### Issue with current documentation:

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/4336207/151837694-4849c9a0-3be4-4e26-857d-bb65bf979f2c.png">
This is the current status of the NEP site.

The sidebar is highly unhelpful for navigation. At the moment finding neps requires searching.

### Idea or request for content:

Lets have the left sidebar ordered by NEP number, and also maybe have the status in brackets/color?

**Comment by soma2000-lang** [comment]
@HaoZeke  can I work on this??

**Comment by mattip** [comment]
@soma2000-lang at this stage you might want to look at the PRs already submitted and comment which you find more appealing

**Comment by seberg** [comment]
The PR is merged, so the situation is at least better now (not sure if anyone still wants a numerical order, but a different issue).
