### ISSUE TITLE
Error when importing numpy.testing

### ISSUE THREAD

**Issue by techandrew** [numpy/numpy#20954]
Since 1.22.0 or 1.22.1 (still working in 1.21.5), some kind of error in the __init__.py file in numpy.testing prevents any kind of use of this module, as "._private" is seemingly undefined, despite the folder being present.

**Comment by lucasSaavedra123** [comment]
Can you add how to reproduce the error? i.e. code or something like that.

**Comment by techandrew** [comment]
`import numpy.testing`

**Comment by mattip** [comment]
What is the entire traceback you are getting? What version of python?

**Comment by techandrew** [comment]
I am using Python 3.10.2 on Windows 11.
I resolved the issue by uninstalling and reinstalling numpy.
I don’t remember the entire traceback, but I know it had to do with the first line in the __init__.py file in testing that called on the _private folder.
