### ISSUE TITLE
DOC: no documentation on the different casting options in numpy.concatenate

### ISSUE THREAD

**Issue by ItamarKanter** [numpy/numpy#20958]
### Idea or request for content:

Adding a short description of each casting option in numpy.concatenate. It is unclear from the names of the options what is the exact differences between them.

**Comment by soma2000-lang** [comment]
@ItamarKanter  I would like to work on this issue

**Comment by Mukulikaa** [comment]
Hi @ItamarKanter, for the time being, you can find descriptions of the casting options in the docstring for [ndarray.astype](https://numpy.org/devdocs/reference/generated/numpy.ndarray.astype.html#numpy.ndarray.astype). 

In the last documentation meeting, we discussed that it would be useful to add these descriptions to our [glossary](https://numpy.org/devdocs/glossary.html#glossary) and link to it wherever required.

**Comment by Mukulikaa** [comment]
Fixed by #24061.
