### ISSUE TITLE
DOC: Building from source: outdated python version 

### ISSUE THREAD

**Issue by m10an** [numpy/numpy#20965]
### Issue with current documentation:

In [prerequisites](https://numpy.org/devdocs/user/building.html#prerequisites) mentioned minimal python version as `3.6.x`, but for main branch is `3.8.x`

**Comment by mattip** [comment]
That should be updated. Want to make a PR? The source is in [doc/source/usr/building.rst](https://github.com/numpy/numpy/blob/main/doc/source/user/building.rst)

**Comment by m10an** [comment]
Yes. I think I'll handle it as first one :)
