### ISSUE TITLE
BUG: ~np.isnan([np.nan, 0, 1]).astype(int) returns -2

### ISSUE THREAD

**Issue by zexuan-zhou** [numpy/numpy#20977]
### Describe the issue:

`~np.isnan([np.nan, 0, 1]).astype(int)` returns `array([-2, -1, -1])`
Did I do something wrong?

### Reproduce the code example:

```python
~np.isnan([np.nan, 0, 1]).astype(int)
```

### NumPy/Python version information:

python: `3.8.10`
numpy: `1.22.1`

**Comment by mattip** [comment]
What do you expect `~` to do? 
It is [documented](https://docs.python.org/3/library/operator.html#operator.__invert__) as the `__invert__` operator, which returns the bitwise inverse of the number. So `a.__invert__()` is is equivalent to `-1 -a` for int values:
```
>>> ~4
-5
>>> ~0
-1
>>> a = np.array(4)
>>> a.tobytes()
b'\x04\x00\x00\x00\x00\x00\x00\x00'
>>> (~a).tobytes()
b'\xfb\xff\xff\xff\xff\xff\xff\xff'
```

**Comment by WarrenWeckesser** [comment]
I agree with closing the issue.  I suspect @zexuan-zhou might have been expecting `~` to have a higher precedence than `.`:
```
In [5]: ~np.isnan([np.nan, 0, 1]).astype(int)
Out[5]: array([-2, -1, -1])

In [6]: (~np.isnan([np.nan, 0, 1])).astype(int)
Out[6]: array([0, 1, 1])
```

**Comment by zexuan-zhou** [comment]
Thank you guys very much. I see where the problem is. Thanks for the help
