### ISSUE TITLE
BUG: numpy.divide has inconsistent behaviour when using the "where" mask

### ISSUE THREAD

**Issue by andres-fr** [numpy/numpy#20997]
### Describe the issue:

In the docs we can see the following description for the `where` argument:
https://numpy.org/doc/stable/reference/generated/numpy.divide.html

> At locations where the condition is True, the out array will be set to the ufunc result. Elsewhere, the out array will retain its original value.

As we can see in the example below, this is not always the case, and inconsistencies can be observed.

### Reproduce the code example:

```python
The following log reproduces the issue on my end:


(Pdb) xx
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

(Pdb) yy
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# OK so far: the yy==0 case is being ignored, and xx=0 is retained
(Pdb) np.divide(xx, yy, where=(yy>0))
array([ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

# Now we trigger a NaN when trying to divide by zero
(Pdb) np.divide(xx, yy, where=(yy>=0))
array([nan, 10., 10., 10., 10., 10., 10., 10., 10., 10.])

# If we now evaluate the exact same statement as before, we get NaN instead of zero!
(Pdb) np.divide(xx, yy, where=(yy>0))
array([nan, 10., 10., 10., 10., 10., 10., 10., 10., 10.])
```
```


### Error message:

```shell
The bug is silent, inconsistent behaviour. No error or segfault that I could find.
```

### NumPy/Python version information:

NumPy: 1.21.5
Python: '3.7.11 (default, Jul 27 2021, 14:32:16) \n[GCC 7.5.0]'
Ubuntu: 20.04

**Comment by aridaybordon** [comment]
Hi, working on NumPy 1.21.4, I am unable to replicate the bug. It just works fine before and after the trigger.

**Comment by andres-fr** [comment]
Hey, thanks for giving this a shot, this is weird.
I just tested again by creating a fresh conda environment with python 3.7.11.
I installed numpy 1.21.4 and wasn't able to reproduce it either.
Then I replaced the version with 1.21.5 and didn't reproduce as well.

Some thoughts:
1. This bug appeared when using the debugger `pdb`
2. The debugger triggered in the middle of a RAM-heavy process

So, it is possible that this could be a bug in the debugger, or that this is still a memory bug that only triggers when there are fewer addresses available (the garbage collector and memory allocation may behave differently).

I am positive that this happened the way described. The variables were defined using `np.arange` for quick testing. Still, it is possible (but very unlikely IMO) that I'm having a blind spot and there is no bug.

**Comment by seberg** [comment]
This is defined behaviour and noted in the docs.  Where should only be used with `out=` (unless  you fill in the other values manuall).  It is not a super uncommon common source for confusion though, so there are some older issues about it.
There may have been thoughts about warning when `out=` is not given, or initializing even, but not sure.

**Comment by andres-fr** [comment]
Thank you! now that you point this out, it does make sense.
I guess it is up to the user to ensure consistency via

```
c = np.divide(a, b, where=(b!=0))
c[b==0] = a[b==0]
```

Fair enough. Sorry for the noise, I'm closing this issue.
