### ISSUE TITLE
BUG: Segmentation fault when unpickling an empty ndarray with a none-zero dimension

### ISSUE THREAD

**Issue by wuciting** [numpy/numpy#21009]
### Describe the issue:

There is a `Segmentation fault` when unpickling an empty ndarray with a none-zero dimension.
The first dimension `93049` may depend on the platform. If you cannot reproduce the error, please increase the first dimension. 
I think it has something to do with the page allocation.

### Reproduce the code example:

```python
import pickle

import numpy as np

a = np.array([]).reshape(93049, 0)
print(a.shape)
s = pickle.dumps(a)
print(s)
b = pickle.loads(s)
print(b)
```

### Error message:

```shell
Segmentation fault (core dumped)
```

### NumPy/Python version information:

1.22.1 3.8.11 (default, Aug  3 2021, 15:09:35)
[GCC 7.5.0]

**Comment by seberg** [comment]
I am very confused why our tests appear to not catch this at least when running in valgrind (at least I assume that they should).  I am pretty sure I know the issue, but it should be a fairly straight forward fix if anyone wants to go bug hunting with `gdb` or `valgrind`. (A test that actually triggers this reliably would be good though, ideally even covering a few other branches.)

**Comment by doctormartin67** [comment]
I traced the problem down using ```gdb``` and it seems the issue comes from ```numpy```. The seg fault occurs in
```at numpy/core/src/multiarray/methods.c:2208```:
`memcpy(PyArray_DATA(self), datastr, num);`
When I take a look at the ```PyArray_DATA``` function it casts ```self``` to a ```PyArrayObject_fields``` struct pointer to access it's ```data``` field.
The comments above the declaration of this struct says that accessing its field is deprecated and that ```NPY_NO_DEPRECATED_API``` should be defined to avoid this issue. Not sure why it isn't though. This is as far I can could go without studying ```numpy``` in more depths.

**Comment by seberg** [comment]
Yes, that is all correct.  The "deprecated" stuff isn't a worry, it only applies to users outside of NumPy anyway (and even then isn't problematic).
The code works for non-empty arrays, so the problem is just the `num`.

**Comment by seberg** [comment]
@doctormartin67 thanks for looking into this, @alexdesiqueira had just started on this yesterday and opened a PR now, sorry about that bad timing.

**Comment by doctormartin67** [comment]
@seberg No worries, always have fun taking a look at seg faults in ```gdb```

**Comment by charris** [comment]
@seberg This is fixed, correct?
