### ISSUE TITLE
BUG: Transposed array change np.frompyfunc behavior

### ISSUE THREAD

**Issue by Howard-O-Neil** [numpy/numpy#21002]
### Describe the issue:

I try to get my custom numpy function working properly. I finger out that np.array pass each pair of 2 value into `np.frompyfunc`

Normally the pair values i assumed will be passed into `np.frompyfunc` in column wise manner (described in code example), which is my expectation

But somehow, with the same input value but from transposing produce different behavior, the pair values are passed in row wise manner, which produce fault results in my project (calculating IoU)

I try to search this on google but have no luck, this issue is really weird and i don't know if it's really a bug or just me don't understand numpy fully.

### Reproduce the code example:

```python
import numpy as np
import pandas as pd

def add(x, y):
    # Print pair value
    print(f"{x} --- {y}")
    return x + y

custom_add = np.frompyfunc(add, 2, 1)

a = np.array([])
for i in range(4):
    u = np.array([1, 2])

    if a.shape[0] <= 0:
        a = np.expand_dims(u, 1)
    else: a = np.concatenate(
        (a, np.expand_dims(u, 1)), 1
    )

b = np.array([])
for i in range(4):
    u = np.array([4, 5])

    if b.shape[0] <= 0:
        b = np.expand_dims(u, 1)
    else: b = np.concatenate(
        (b, np.expand_dims(u, 1)), 1
    )

print(custom_add(a, b))
# 1 --- 4
# 1 --- 4
# 1 --- 4
# 1 --- 4
# 2 --- 5
# 2 --- 5
# 2 --- 5
# 2 --- 5
# [[5 5 5 5]
#  [7 7 7 7]]

a = np.array([[1, 2], [1, 2], [1, 2], [1, 2]]).T
b = np.array([[4, 5], [4, 5], [4, 5], [4, 5]]).T


print(custom_add(a, b))
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# [[5 5 5 5]
#  [7 7 7 7]]
```

### NumPy/Python version information:

1.22.1 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0]

**Comment by seberg** [comment]
> Normally the pair values i assumed will be passed into np.frompyfunc in column wise manner (described in code example), which is my expectation

No, NumPy can do whatever it likes to do and whatever it thinks is fastest.  If you expect things to be passed into a specific order, that means your function is not "vectorized" because order matters (at least along _some_ dimension).

The only place where there may well be an issue, is if you use `custom_add.reduce(...)`, and NumPy correctly guards against that for `np.frompyfunc`.
