### ISSUE TITLE
DOC: scipy docs forwarding link broken

### ISSUE THREAD

**Issue by afeinstein20** [numpy/numpy#21004]
### Issue with current documentation:

Hi,

I think the `scipy` docs changed their docs link to include the version number, which means that all of the `scipy` forwarding links in the `numpy` docs are broken.

Sorry if this is submitted as an issue elsewhere!

### Idea or request for content:

Example --

Currently used link (doesn't work): https://docs.scipy.org/doc/scipy/reference/reference/generated/scipy.signal.fftconvolve.html#scipy.signal.fftconvolve

New link (changes `scipy` to `scipy-1.7.1` works):
https://docs.scipy.org/doc/scipy-1.7.1/reference/reference/generated/scipy.signal.fftconvolve.html#scipy.signal.fftconvolve

**Comment by rossbar** [comment]
Can you point to the specific location in the documentation where you found the broken link? In principle the links to scipy should all be using intersphinx, so it'd be good to update it.

**Comment by afeinstein20** [comment]
From this link https://numpy.org/doc/stable/reference/generated/numpy.convolve.html
Under **See Also**: `scipy.signal.fftconvolve` and `scipy.linalg.toeplitz` go to a "The requested URL /index.html was not found on this server." message

**Comment by rossbar** [comment]
It looks like this is an upstream issue with the URL for the scipy stable docs (see the pinned issue linked above).

**Comment by tylerjereddy** [comment]
I did try to add some redirects so the original link in the issue above that didn't work does seem to work for me now.

I'm not sure if this is the permanent solution we'll adopt just yet though. See the current redirects: https://github.com/tylerjereddy/htaccess_backup/pull/1

**Comment by tylerjereddy** [comment]
Well, the link isn't broken, but maybe still wrong page...

**Comment by melissawm** [comment]
This was fixed by #21016, you can see the results in the devdocs right now: https://numpy.org/devdocs/reference/generated/numpy.convolve.html
