### ISSUE TITLE
TYP: fill_value parameter of full_like function has wrong type

### ISSUE THREAD

**Issue by lorenzomammana** [numpy/numpy#21011]
### Issue with current documentation:

I use a lot of time the function `full_like` from `numpy.core.numeric` and I'm using it in a way that, based on the documentation, wouldn't be possible, particularly I'm using an array-like object to fill a three dimensional matrix, for example this code is perfectly fine and achieves what I need:
`
color_mask = np.full_like(input_img, fill_value=[0, 255, 0])
` 
Where input_img is an ndarray of shape (h, w, 3).

Every time I use this kind of code Pycharm complains saying _Expected type Union[int, float, complex], got List[int] instead_, which is of course correct because fill_value parameter has type scalar.
The problem arise since inside the full_like function the fill_value is only used by `multiarray.copyto` which actually allows array_like type.

So there could possibly be two different issues here:

1. The documentation is wrong and fill_value should be of type array_like rather than scalar
2. The code is wrong in the sense that an array like value should not be accepted by the function as the function was not designed to work with array like type

### Idea or request for content:

The resolution should be very simple, change the type of the parameter to array_like and potentially add this kind of behaviour in the examples section of the docstring.

**Comment by BvB93** [comment]
> So there could possibly be two different issues here:

It's option three I'm afraid: the numpy annotations are being overridden somewhere, be it either via a third-party stub-only package or maybe even PyCharm itself. As you can see, the `fill_value` parameter of [`np.full_like`](https://github.com/numpy/numpy/blob/dff5a6016ed7fce20f18ff4fd142a75e8a03821b/numpy/core/numeric.pyi#L191-L217) is currently annotated as `Any` and, due to the reasons you've described, has at no point been any stricter than that.

**Comment by lorenzomammana** [comment]
Ok I see your point, but I think you don't need to go that far away to see where the numpy annotation is overriden

https://github.com/numpy/numpy/blob/dff5a6016ed7fce20f18ff4fd142a75e8a03821b/numpy/core/numeric.py#L367

Here the docstring for fill_value parameter of the full_like function indicates scalar as the correct type, isn't that wrong?

**Comment by BvB93** [comment]
> Here the docstring for fill_value parameter of the full_like function indicates scalar as the correct type, isn't that wrong?

Yes, I agree that `array_like` would be more appropriate here than just `scalar`, as any object that can broadcasted to the requested shape will suffice. Would you perhaps be interested in creating a PR?

Nevertheless, this will only solve the documentation aspect of the issue, as the annotations used by static type checkers are located in the *.pyi stub files, not the docstrings. A third party package is providing it's own stub files for numpy here; I'd suggest identifying the culprit and filing an issue there.

**Comment by seberg** [comment]
IIRC there we had cases where PyCharm parsed numpydoc docstrings to guess stubs... gotta live with some incorrect stuff if you do that.  (And should use the stubs when they are available, that is a PyCharm issue arguably)

There was some discussion before about what the "right" thing is here.  I don't have a strong opinion on it.  I guess the inention was "scalar", but what we got is "array-like".  There was a suggestion to change it to scalar before, but nobody followed through with it after we pointed out that it would have to go through a proper deprecation cycle.

**Comment by lorenzomammana** [comment]
@BvB93 Sorry I forgot to reply in the end, I can open a PR just to fix at the least the documentation point of view since at least at the moment scalar is not correct, If I have some time I'll also try to investigate the Pycharm side of the issue even tough from some brief search on the internet it appears that Pycharm is actually ignoring the interface definition and taking the typing directly from the implementation, meaning that fixing the doc would probably also fix my initial issue 😅
