### ISSUE TITLE
ENH: make einsum contraction order controllable via alphebetical order of symbols

### ISSUE THREAD

**Issue by catkira** [numpy/numpy#21028]
### Proposed new feature or change:

I have a code where I multiply 3 arrays with einsum. Variables a and c are very small and variable b is very large. To avoid large rounding errors, I have to multiply the large variable with a small variable first. Therefore I have to split up my einsum command like this:
```python
val = np.einsum('i,i...->i...', a, np.einsum('ikj,lk', b, c))
```
It would be nice if I can write all in one expression like
```python
val = np.einsum('m,mkj,lk->mjl', a, b, c)
```
and tell einsum via the alphabetical letters the order in which the multiplications should be done. Here 'k' should be multiplied before 'm'.

**Comment by seberg** [comment]
I am -1 on alphabetic order.  There might be optimizations possible, but I am not sure it is worthwhile.  In any case, I expect `optimize=True` will already find these optimized versions, so I am tempted to close this.
(Not saying that normal einsum without optimization could potentially do _some_ optimization here, but it seems unlikely and `optimize=True` is just the right way.)

**Comment by leofang** [comment]
This does not make sense. What you need is a decent path optimizer, such as opt_einsum or cuQuantum, that offers you the optimal contraction order without resorting to this kind of hacks. Plus, it is currently a limitation in NumPy/CuPy that the einsum expressions can only use alphabets. Once unicode characters are accepted it would be very challenging to make sense of the symbol order (still doable, but not in a human-readable fashion).

**Comment by seberg** [comment]
Lets close this then, thanks for the note Leo and for taking the trouble of trying to find a suggestion to improve NumPy, catkira.
