### ISSUE TITLE
BUG: `np.full` with `like` argument does not trigger `__array_function__` interface

### ISSUE THREAD

**Issue by mocquin** [numpy/numpy#21033]
### Describe the issue:

Calling `np.full(shape, x, like=x)` seems to try to trigger the __array_function__ interface, but is not found in the class that implements it. Am I missing something ?

### Reproduce the code example:

```python
import numpy as np
class Toto():
    
    def __init__(self, value):
        self.value = value
        
    def __array_function__(self, func, types, args, kwargs):
        if func not in HANDLED_FUNCTIONS:
            return NotImplemented
        return HANDLED_FUNCTIONS[func](*args, **kwargs)
    
HANDLED_FUNCTIONS = {}

def wrapped_sum(x, *args, **kwargs):
    return Toto(np.sum(x.value, *args, **kwargs))

def wrapped_full(shape, x, *args, **kwargs):
    return Toto(np.full(shape, x.value, *args, **kwargs))

HANDLED_FUNCTIONS[np.sum] = wrapped_sum
HANDLED_FUNCTIONS[np.full] = wrapped_full

print(np.sum(Toto([1, 2, 3]))) # works as expected
print(np.full((3,3), Toto(28), like=Toto(28))) # raise TypeError no implementation found for 'numpy.full' on types that implement __array_function__: [<class '__main__.Toto'>]
```

### Error message:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/5k/bf4syt7x1zjbhc6b28srzzym0000gn/T/ipykernel_57970/4259881689.py in <module>
     28 
     29 print(np.sum(Toto([1, 2, 3])))
---> 30 print(np.full((3,3), Toto(28), like=Toto(28)))

/opt/anaconda3/lib/python3.9/site-packages/numpy/core/numeric.py in full(shape, fill_value, dtype, order, like)
    336     """
    337     if like is not None:
--> 338         return _full_with_like(shape, fill_value, dtype=dtype, order=order, like=like)
    339 
    340     if dtype is None:

<__array_function__ internals> in full(*args, **kwargs)

TypeError: no implementation found for 'numpy.full' on types that implement __array_function__: [<class '__main__.Toto'>]
```

### NumPy/Python version information:

1.21.4 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]

**Comment by seberg** [comment]
Weird that this wasn't noticed before.  It looks like it passes the wrong public symbol (not `np.full` itself), @pentschev do you have some time to have a look?  Or maybe someone else wants to dig in.  Should not be a hard fix, although the `__array_function__` machinery can confusing.

**Comment by seberg** [comment]
>  i.e., it may wrap a function and thus result in a different object.

Hmmm, can't we just guarantee this, at least so long there was no monkeypatching or anything else weird going on?  It frankly seems strange to me that the publicy API symbol would mismatch, and I was pretty sure the NEP said it should match.

**Comment by mocquin** [comment]
Thanks for the tip, I guess I'll use string lookup from now on.

Also, not sure if related but calling `np.full` without `like=Toto(28)` doesn't seem to trigger the `__array_function__` interface : 
```python
print(np.full((3,3), Toto(28)))
```
returns : 
```

[[<__main__.Toto object at 0x10d1b89d0>
  <__main__.Toto object at 0x10d1b89d0>
  <__main__.Toto object at 0x10d1b89d0>]
 [<__main__.Toto object at 0x10d1b89d0>
  <__main__.Toto object at 0x10d1b89d0>
  <__main__.Toto object at 0x10d1b89d0>]
 [<__main__.Toto object at 0x10d1b89d0>
  <__main__.Toto object at 0x10d1b89d0>
  <__main__.Toto object at 0x10d1b89d0>]]
```

**Comment by seberg** [comment]
> I don't immediately see what's the cause for this other than the C vs Python implementation. Please let me know if something comes to mind.

Yeah, that looks like C vs. Python.  Can we fix the Python pattern?

**Comment by seberg** [comment]
I am suggesting something like this:
```diff
diff --git a/numpy/core/overrides.py b/numpy/core/overrides.py
index 840cf38c9..a756ec7c9 100644
--- a/numpy/core/overrides.py
+++ b/numpy/core/overrides.py
@@ -167,7 +167,7 @@ def decorator(implementation):
             return implementation
         return decorator
 
-    def decorator(implementation):
+    def decorator(implementation, public_api=None):
         if verify:
             verify_matching_signatures(implementation, dispatcher)
 
@@ -175,18 +175,20 @@ def decorator(implementation):
             add_docstring(implementation, dispatcher.__doc__)
 
         @functools.wraps(implementation)
-        def public_api(*args, **kwargs):
+        def new_func(*args, **kwargs):
             relevant_args = dispatcher(*args, **kwargs)
             return implement_array_function(
                 implementation, public_api, relevant_args, args, kwargs)
 
-        public_api.__code__ = public_api.__code__.replace(
+        new_func.__code__ = public_api.__code__.replace(
                 co_name=implementation.__name__,
                 co_filename='<__array_function__ internals>')
         if module is not None:
-            public_api.__module__ = module
+            new_func.__module__ = module
 
-        public_api._implementation = implementation
+        new_func._implementation = implementation
+        if public_api is None:
+            public_api = new_func
 
         return public_api
```

**Comment by pentschev** [comment]
I see your point now @seberg , thanks for clarifying. This indeed would resolve the equality issue, but the problem is that we then replace the dispatcher `_full_with_like` with `full` again, which makes it a recursive call in https://github.com/numpy/numpy/blob/main/numpy/core/numeric.py#L338 . I'm assuming the way you intend `array_function_dispatch` to be called would be:

```python
_full_with_like = array_function_dispatch(
    _full_dispatcher
)(full, public_api=full)
```

Also note I think you wanted to write `new_func.__code__ = new_func.__code__.replace(` (the right-hand side is also `new_func`, or I'm also doing something wrong). If I'm still misunderstanding the overall idea, please let me know.

**Comment by seberg** [comment]
Yeah, I was thinking something like that.  Fair point about the first argument and the recursive call, I guess you might have to introduce a brief helper, like `lambda *args, **kwargs: full(*args, **kwargs)` (we don't care too much about speed here, so...

**Comment by pentschev** [comment]
Actually there's a simpler solution, requires some special-casing but it's quite straightforward. I opened https://github.com/numpy/numpy/pull/21071 to address that.

@mocquin could you also try https://github.com/numpy/numpy/pull/21071 with your original example and make sure it also works for you?
