### ISSUE TITLE
BUG: numpy.kron raises exception when first argument has a zero dimensionality

### ISSUE THREAD

**Issue by PgLoLo** [numpy/numpy#21051]
### Describe the issue:

`numpy.kron` function raises an exception `ValueError: need at least one array to concatenate` when first argument has zero dimensionality (either `[0, N]` or `[N, 0]` shape).

### Reproduce the code example:

```python
import numpy as np

np.kron(np.zeros([0, 3]), np.zeros([2, 2]))  # raises an exception
np.kron(np.zeros([3, 0]), np.zeros([2, 2]))  # raises an exception
np.kron(np.zeros([3, 3]), np.zeros([0, 2]))  # works perfectly fine
np.kron(np.zeros([3, 3]), np.zeros([2, 0]))  # works perfectly fine
```

### Error message:

```shell
ValueError: need at least one array to concatenate
```

### NumPy/Python version information:

1.19.5 3.9.4 (default, Apr  9 2021, 16:34:09)

**Comment by seberg** [comment]
I am not sure why it is invalid? The shape of the result should be defined as `np.mutliply(a.shape, b.shape)`, I think?

However, I admit I am unsure if there is much useful meaning to a Kronecker product with empty arrays.  But I would tend to allow it unless anyone thinks it is guaranteed to be an error when it happens.
We have a lot of empty array behaviours that can seem non-intuitive, but give the correct generalization for the few people who run into it.  (For example, I think we allow selecting nothing from an empty stack of data.)
