### ISSUE TITLE
Numpy multiarray error after importing libraries

### ISSUE THREAD

**Issue by ufukeskici** [numpy/numpy#21055]
### Steps to reproduce:

When I want to import a few libraries on VS Code venv, I get the following error.

My OS is MACOS Big Sur Version 11.6
M1 Macbook M1, 2020
Numpy Version: 1.22.2
Python Version. 3.10

### Error message:

```shell
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python"
  * The NumPy version is: "1.22.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 2): no suitable image found.  Did find:
	/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so: mach-o, but wrong architecture
	/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so: mach-o, but wrong architecture
```

**Comment by HaoZeke** [comment]
For the bug to be reproducible please add details of how Python and Numpy have been installed.

**Comment by ufukeskici** [comment]
I installed python via pkg file download from python.org.
I used numpy path under the python folder. Whwn I want to update numpy iy says already satisfied:

`(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % pip install numpy
Requirement already satisfied: numpy in ./MyDemoEnv/lib/python3.10/site-packages (1.22.2)`

**Comment by mattip** [comment]
I think you might have to update pip to a version that knows about M1 architecture:
```
python -m pip install --upgrade pip
```

then uninstall numpy and reinstall

**Comment by ufukeskici** [comment]
Unfortunately it did notwork:

`(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % python -m pip install --upgrade pip
Requirement already satisfied: pip in ./MyDemoEnv/lib/python3.10/site-packages (22.0.3)
(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % pip uninstall numpy
Found existing installation: numpy 1.22.2
Uninstalling numpy-1.22.2:
  Would remove:
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/f2py
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/f2py3
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/f2py3.10
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy-1.22.2.dist-info/*
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy/*
Proceed (Y/n)? Y
  Successfully uninstalled numpy-1.22.2
(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % pip install numpy
Collecting numpy
  Using cached numpy-1.22.2-cp310-cp310-macosx_11_0_arm64.whl (12.8 MB)
Installing collected packages: numpy
Successfully installed numpy-1.22.2`

**Comment by mattip** [comment]
Can you use `pip install --no-cache numpy` so you get a new download rather than using the cached version?

**Comment by ufukeskici** [comment]
Still same :(

(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % pip uninstall numpy
Found existing installation: numpy 1.22.2
Uninstalling numpy-1.22.2:
  Would remove:
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/f2py
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/f2py3
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/f2py3.10
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy-1.22.2.dist-info/*
    /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy/*
Proceed (Y/n)? Y
  Successfully uninstalled numpy-1.22.2
(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % pip install --no-cache numpy
Collecting numpy
  Downloading numpy-1.22.2-cp310-cp310-macosx_11_0_arm64.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 2.1 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.22.2

**Comment by mattip** [comment]
Weird. What does `file` say?
`file /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so`
`file /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python`

**Comment by ufukeskici** [comment]
Here it is:

(base) ufukeskici@Ufuks-MacBook-Air bin % file /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so
/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so: Mach-O 64-bit bundle arm64


(base) ufukeskici@Ufuks-MacBook-Air bin % file /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python
/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python (for architecture arm64):	Mach-O 64-bit executable arm64

**Comment by mattip** [comment]
ahh. So you have a universal python (supports both x86_64 and arm64) and an arm64 numpy. Maybe something else is telling that python "please use x86_64 mode" before importing numpy. Does this succeed?

`/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python -c "import numpy"

**Comment by ufukeskici** [comment]
Nothing special happened after running this command. No errors or successful result messages. But the issue remains same.

Should I remove python with x86_64 from my Macbook? If yes, how?

Thanks in advance.

**Comment by mattip** [comment]
Nothing happening means the import succeeded. What is the complete code you are trying in the original statement of the problem:
> When I want to import a few libraries on VS Code venv, I get the following error.

My uneducated guess is that either the way you are running the code or some other import is triggering x86_64 mode.

**Comment by ufukeskici** [comment]
For example, I'm trying tp import textblob & wordcloud 

`from textblob import TextBlob`
`from wordcloud import WordCloud`

**Comment by mattip** [comment]
Can you try the other way around: first import numpy, then the others?

**Comment by ufukeskici** [comment]
> Can you try the other way around: first import numpy, then the others?

ı tried all of them seperately. Only running the numpy line did not work. I got the same fault.

**Comment by mattip** [comment]
I don't understand. If from the command line you run this you get an error when importing numpy? That contradicts [this comment](https://github.com/numpy/numpy/issues/21055#issuecomment-1039562016) from above 
```
% /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python
>>> import numpy
>>> import pandas as pd
>>> from textblob import TextBlob
>>> from wordcloud import WordCloud
```

**Comment by ufukeskici** [comment]
Maybe my description is wrong. I've realized that all are related with numpy. So even only importing numpy gives me the error.

**Comment by mattip** [comment]
Let's start over. What do these print?
```
`/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python -c "import platform; print(platform.machine())"

```

```
/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python -c "import numpy; print(numpy.__version__)"
```

```
/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python -c "import numpy; import pandas; import textcloud; import wordcloud; print('all imported')"

**Comment by ufukeskici** [comment]
Here are the outputs:

`(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python -c "import platform; print(platform.machine())"`
`arm64`

`(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python -c "import numpy; print(numpy.__version__)"`
`1.22.2`

`(MyDemoEnv) (base) ufukeskici@Ufuks-MacBook-Air test-project % /Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python -c "import numpy; import pandas; import textblob; import wordcloud; print('all imported')"`
`all imported`

**Comment by mattip** [comment]
> why my python is universal? Is it due to direct .pkg installer

It seems so.

> What is wrong about my numpy installation with Python 3.10 ?

According to your output from above, nothing is wrong with `/Users/ufukeskici/jupyter-notebook/test-project/MyDemoEnv/bin/python`, everything Just Works. 

> I've tried importing numpy in a standard non-venv environment but it did not work at all

Please provide more information: what is "a standard non-venv environment"? Did you install numpy to this environment? How?

**Comment by ufukeskici** [comment]
> Please provide more information: what is "a standard non-venv environment"? Did you install numpy to this environment? How?

It is a .ipynb file running on vscode. It runs without a virtual environment. I installed numpy but it still says

`Requirement already satisfied: numpy in [/Users/ufukeskici/opt/anaconda3/lib/python3.8/site-packages]() (1.20.1)`

Why this is checking 3.8 when I use python 3.10 ?

I think something has messed up my python and library files. If we don't have solution, it is possible to install everything from scratch on vscode ? Or should I add something to .json setting file for python path, etc? I'm not good at this mac stuff so I don't know how to fix this.

**Comment by charris** [comment]
How are you installing NumPy?

**Comment by ufukeskici** [comment]
I've solved the problem. I think there was something wrong with manual installation of Python 3.10 or something else.
I've installed latest stable Python version (which is 3.9) via Homebrew and showed it to VScode to run the notebook.
Then it works fine.

I removed Python 3.10 from my Macbook manually but the following remained:

ufukeskici@Ufuks-MacBook-Air bin % ls -l /usr/local/bin | grep '../Library/Frameworks/Python.framework' 
lrwxr-xr-x  1 root  wheel  67 Feb 14 00:41 2to3 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/2to3
lrwxr-xr-x  1 root  wheel  72 Feb 14 00:41 2to3-3.10 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/2to3-3.10
lrwxr-xr-x  1 root  wheel  68 Feb 14 00:41 idle3 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/idle3
lrwxr-xr-x  1 root  wheel  71 Feb 14 00:41 idle3.10 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/idle3.10
lrwxrwxr-x  1 root  admin  67 Feb 14 00:41 pip3 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/pip3
lrwxrwxr-x  1 root  admin  70 Feb 14 00:41 pip3.10 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/pip3.10
lrwxr-xr-x  1 root  wheel  69 Feb 14 00:41 pydoc3 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/pydoc3
lrwxr-xr-x  1 root  wheel  72 Feb 14 00:41 pydoc3.10 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/pydoc3.10
lrwxr-xr-x  1 root  wheel  62 Feb 14 00:58 python -> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
lrwxr-xr-x  1 root  wheel  70 Feb 14 00:41 python3 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/python3
lrwxr-xr-x  1 root  wheel  77 Feb 14 00:41 python3-config -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/python3-config
lrwxr-xr-x  1 root  wheel  78 Feb 14 00:41 python3-intel64 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/python3-intel64
lrwxr-xr-x  1 root  wheel  73 Feb 14 00:41 python3.10 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
lrwxr-xr-x  1 root  wheel  80 Feb 14 00:41 python3.10-config -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10-config
lrwxr-xr-x  1 root  wheel  81 Feb 14 00:41 python3.10-intel64 -> ../../../Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10-intel64

**Comment by mattip** [comment]
> I've solved the problem. 

Yay! Closing the issue. Please reopen or open a new one as needed.

**Comment by ufukeskici** [comment]
> > I've solved the problem. 
> 
> 
> 
> Yay! Closing the issue. Please reopen or open a new one as needed.

I really appreciate your help! Thank you!

**Comment by fengjixing-stupid** [comment]
I have met up with the same problem as you and have another solution. I just delete the numpy folder and reinstall it in  the terminal of the vscode. It works again and don't have to change the version of python. For other packages it works too.
My machine is also M1, and I use Python 3.9.13. Hoping my advise will still work.

But in this way, the interpreter in IDLE can not import numpy. (I have install the universal version of python 3.9.13, but it just can't import numpy in arm64 form.)
