### ISSUE TITLE
BUG: loadtxt raises an issue on file that used to work

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#21052]
### Describe the issue:

Thanks to the `--pre` wheels, our [CIs found some issues](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=18059&view=logs&j=305851a9-a7bb-55db-0042-7e2b6f48aa1c&t=77eb5bf7-3205-5b54-06c6-183c8195d846&l=3053) with (what I assume is) the `loadtxt` change to C.

### Reproduce the code example:

1. Running `np.loadtxt(fname, skiprows=1)` on [this file](https://github.com/mne-tools/mne-testing-data/blob/master/SSS/test_move_anon_raw.pos) or [this file](https://github.com/mne-tools/mne-testing-data/blob/master/SSS/chpi5_raw_mc.pos) both used to work fine, now we get:
    ```
    mne\chpi.py:84: in read_head_pos
        data = np.loadtxt(fname, skiprows=1)  # first line is header, skip it
    C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\lib\npyio.py:1321: in loadtxt
        arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
    C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\lib\npyio.py:999: in _read
        arr = _load_from_filelike(
    E   ValueError: could not convert string '' to float64 at row 0, column 11.
    ```

2. Running `with open(egi_txt_fname) as fid: data = np.loadtxt(fid)` on [this file](https://github.com/mne-tools/mne-python/blob/main/mne/io/egi/tests/data/test_egi.txt) used to work fine, now we get:

    ```
    C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\lib\npyio.py:1321: in loadtxt
        arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
    C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\lib\npyio.py:999: in _read
        arr = _load_from_filelike(
    E   ValueError: could not convert string '' to float64 at row 0, column 78.
    ```

### NumPy/Python version information:

Platform:            Windows-10-10.0.17763-SP0
Python:              3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
numpy:               1.23.0.dev0+735.g4c60b3263

**Comment by seberg** [comment]
The reason is a trailing `\t\n`, with a normal delimiter the `\t` would start a new field, but for `delimiter=None` that should get stripped away and the new field never started.  I guess we are missing a test for this.

**Comment by seberg** [comment]
Two solutions:
* Just remove the last field if its empty in this case
* Introduce an explicit "skip whitespace" state

I think the latter is probably better, not sure why I didn't do that to begin with.

**Comment by larsoner** [comment]
Either way is fine with me! We can inspect args at our end and pass `skip_whitespace` if it's in the signature. But I imagine you'll have fewer bug reports and fewer people who need to change behavior if you do just strip any trailing whitespace (or whatever `loadtxt` used to do...?). Might be worth looking at if other text reading functions like pandas behave similarly with whitespace removal.

**Comment by seberg** [comment]
This is a plain oversight when it comes to testing (which is almost bound to happen to lead in an error in the code for this stuff ;)).  `delimiter=None` is well defined and we know how it should work.
In the `delimiter=None` the code just starts the new field a too early, so have to see if that is best moved, the whitespace skipped, or ....

**Comment by seberg** [comment]
Well, went with the first option, probably actually the right one.  There might be a plausible small refactor with a new state and creating the next field later, but I don't think it would help related to this fix.
