### ISSUE TITLE
Additional “/reference” in links to SciPy documentation

### ISSUE THREAD

**Issue by qoheniac** [numpy/numpy#21059]
[Here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html), for example, is a link to scipy.linalg.inv which is erroneously 

> https://docs.scipy.org/doc/scipy/reference/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv

instead of

> https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv

**Comment by qoheniac** [comment]
Maybe from [this line](https://github.com/numpy/numpy/blob/c0d36c88b8b525f5869eefd893d1d77ffe41903e/doc/neps/conf.py#L182)?

**Comment by rossbar** [comment]
Thanks for reporting - now that scipy has changed URLs after the 1.8 release some intersphinx links in numpy's `stable` docs are likely broken. This is already fixed in the [devdocs](https://numpy.org/devdocs/reference/generated/numpy.linalg.inv.html)

**Comment by soma2000-lang** [comment]
@rossbar can I work on this

**Comment by rossbar** [comment]
> can I work on this

There really isn't anything to contribute to here - I'm leaving it open as a note-to-self for maintainers to re-upload docs after the next release.

**Comment by seberg** [comment]
These links are fixed now, thanks.
