### ISSUE TITLE
BUG: floordiv of complex number - wrong result

### ISSUE THREAD

**Issue by francof2a** [numpy/numpy#21058]
### Describe the issue:

When a **floor division** (`//` or `floor_divide`) is performed using a _complex number or array_, a wrong result is returned.

> Note: The problem seems to be in the imaginary part, where this always is returned with zero value.

### Reproduce the code example:

```python
import numpy as np

r = np.array(2j) // 2
assert r.item() == 1j

# r is equal to 0j but it must be equal to 1j

np.array(5 + 5j) // 2
# (2+0j) is returned, so the real part is ok but the imaginary part is always zero.
```

### NumPy/Python version information:

1.20.3 3.8.10 | packaged by conda-forge | (default, Sep 13 2021, 21:46:58) 
[GCC 9.4.0]

**Comment by ganesh-k13** [comment]
We removed `floor_divide` support for complex in [1.22](https://numpy.org/doc/stable/release/1.22.0-notes.html?highlight=removed%20floor%20division%20support%20complex%20types#removed-floor-division-support-for-complex-types)
