### ISSUE TITLE
BUG: ppc64le conversion float64->32 are broken for arrays 4+ elements

### ISSUE THREAD

**Issue by henryiii** [numpy/numpy#21062]
### Describe the issue:

Conversions from 64 bit to 32 bit floats or ints are broken on ppc64le if an array has 4 or more elements. This has broken my test suite for several months on conda-forge, and is still a problem.

To reproduce:

```console
$ docker run --platform linux/ppc64le --rm -it continuumio/miniconda3:latest bash
# conda install numpy
```

(or use conda-forge, and any Python version - it just must be ppc64le). The code below works correctly on all other platforms. I've also tried all the casting rules, all misbehave like you see below. There don't seem to be wheels for ppc64le to try there.

### Reproduce the code example:

```python
>>> import numpy as np
>>> s = np.random.normal(size=4); s
array([ 0.04760427, -0.11949105, -1.67610564,  1.38181202])
>>> s.astype(np.float32)
array([ 4.7665749e-18,  1.9329982e-10,  6.0247680e-16, -6.2795307e+26],
      dtype=float32)
>>> np.array([1., 2., 3., 1.00001]).astype(np.float32)
array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.5436204e+36],
      dtype=float32)
```

Less than four elements or single item conversions work correctly.

### NumPy/Python version information:

1.20.3 3.9.5 (default, May 18 2021, 19:43:16)
[GCC 7.3.0]

**Comment by seiko2plus** [comment]
It's a QEMU bug, please check #20964 for more clarification.

**Comment by henryiii** [comment]
Okay, great.
