### ISSUE TITLE
BUG: Failure to build on windows: `'ssize_t': undeclared identifier`

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#21073]
Ever since the merging of https://github.com/numpy/numpy/pull/21025 I've been unable to locally build from the `main` branch when using windows.
The full build log is attached below, but it seems `ssize_t` is currently not defined in tokenize.cpp:

``` 
numpy\core\src\multiarray\textreading\tokenize.cpp(392): error C2065: 'ssize_t': undeclared identifier
numpy\core\src\multiarray\textreading\tokenize.cpp(392): error C2146: syntax error: missing ';' before identifier 'offset_last'
numpy\core\src\multiarray\textreading\tokenize.cpp(392): error C2065: 'offset_last': undeclared identifier
numpy\core\src\multiarray\textreading\tokenize.cpp(393): error C2065: 'ssize_t': undeclared identifier
numpy\core\src\multiarray\textreading\tokenize.cpp(393): error C2146: syntax error: missing ';' before identifier 'end_last'
numpy\core\src\multiarray\textreading\tokenize.cpp(393): error C2065: 'end_last': undeclared identifier
numpy\core\src\multiarray\textreading\tokenize.cpp(394): error C2065: 'end_last': undeclared identifier
numpy\core\src\multiarray\textreading\tokenize.cpp(394): error C2065: 'offset_last': undeclared identifier
```

Reproduce the code example:
------------------------------
``` shell
git clean -xfd
python setup.py build
```

Error message:
---------------
* Full build log: [build_log.txt](https://github.com/numpy/numpy/files/8081332/build_log.txt)

NumPy/Python version information:
-------------------------------------
* Numpy version: `main` branch (post-https://github.com/numpy/numpy/commit/67bb936e8d8bc29c1dc4e54449a173280d43b9dd).
* Python version: `3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:27:13) [MSC v.1929 64 bit (AMD64)]`

**Comment by seberg** [comment]
Its not a builtin?  I guess should just change it to `Py_ssize_t` or `npy_intp` everywhere.

**Comment by BvB93** [comment]
I guess not, it's surprising though that this wasn't caught in the CI before.

**Comment by charris** [comment]
<googles> Yep, it isn't defined in C++. The suggested C++ alternatives are `std::ptrdiff_t` or `std::make_signed_t<std::size_t>`, but using `Py_ssize_t` might be the best option. ISTR using `std::ptrdiff_t` myself for machines with segmented memory, IBM390 for instance.

**Comment by charris** [comment]
`linalg.c.src` uses `ptrdiff_t`.
