### ISSUE TITLE
BUG: Erronous RuntimeWarning

### ISSUE THREAD

**Issue by OulanB** [numpy/numpy#21072]
I compiled a local version of python 3.10 on a manjaro distrib on a lenovo ideapad 5 14alc05 (ryzen 5500U)

Python 3.10.2 (main, Feb 15 2022, 13:42:14) [GCC 11.1.0] on linux

I build an openblas 0.3.19 in /usr/local, which give : 

lrwxrwxrwx  1 root root       27 16 févr. 15:35 libopenblas.so.0 -> libopenblas_zenp-r0.3.19.so
-rw-r--r--  1 root root 29584842 16 févr. 14:57 libopenblas_zenp-r0.3.19.a
-rwxr-xr-x  1 root root 14386232 16 févr. 14:57 libopenblas_zenp-r0.3.19.so
---- in /usr/local/lib
all tests passed ok

Now I build numpy 1.22.2 with the following site.cfg

[openblas]
libraries = openblas
library_dirs = /usr/local/lib
include_dirs = /usr/local/include
runtime_library_dirs = /usr/local/lib

many tests failed due to warning such as 

RuntimeWarning: divide by zero encountered in true_divide
with valid arguments.

A small program exhibit the behavior, see the example : at 'step=delta/div' 2 warning are emitted.

The same program with the local python3.8 and assorted numpy from manjaro does not exhibit the problem.

This is certainly due to a problem with the fpu status flags from AVX extension for a zen 2 processor.
Is the bug in numpy or openblas ... ???

As seen in file included, my version of python/numpy use the same blas/lapack as the manjaro one so the bug should
not be in openblas.

Anyway this is very annoying.

[bug.txt](https://github.com/numpy/numpy/files/8081297/bug.txt)

### Reproduce the code example:

```python
import numpy as np
np.show_config()
delta = np.array([ 4.        +0.j        , -1.20411998+0.j        ,
        1.20411998+0.j        ,  1.90848502+0.j        ,
        4.        +0.j        ,  0.        -1.36437635j])
div=4
step=delta/div
print(delta)
print(div)
print(step)
```

### Error message:

```shell
/home/olivier/test.py:11: RuntimeWarning: divide by zero encountered in true_divide
  step=delta/div
/home/olivier/test.py:11: RuntimeWarning: invalid value encountered in true_divide
  step=delta/div

erronous warning emitted

more infos in included file
```

### NumPy/Python version information:

1.22.2 3.10.2 (main, Feb 15 2022, 13:42:14) [GCC 11.1.0]

Upto date Manjaro linux on an ideapad 5 14alc05 (ryzen 5 5500U)

**Comment by mattip** [comment]
Can you verify that numpy is using your openblas? Something like
```
ldd $(python -c "import numpy as np; print(np.core._multiarray_umath.__file__)")
```

**Comment by rossbar** [comment]
I think this results from a bug in [gcc 11.1](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100778), which is still the gcc version on arch-based systems. From the linked bug report, you can try building with `-fno-tree-slp-vectorize` to see if the problem goes away.

**Comment by OulanB** [comment]
I rechecked that I only use openblas with new paramers in compiling numpy and use the flags given by Rossbar.

The runtimewarning disappear (btw when compiling openblas they use the -fno-tree-vectorize flag)

BLAS=None LAPACK=None ATLAS=None CFLAGS=-fno-tree-slp-vectorize python3 setup.py build

Problem solved
