### ISSUE TITLE
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

### ISSUE THREAD

**Issue by levalencia** [numpy/numpy#21076]
I am having the same issue.
On a new compute instance in Azure ML, I am using Python 3.8 Kernel.

I checked the versions:
pandas 0.25.3
numpy 1.22.2

`.describe `gives the same error;
`TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
`
I also tried:
`scaled_df.select_dtypes(include=[np.number])`

same error:
`TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type`

What should I do?

Update:
I dont understand why when I run pip freeze I get different versions:
numpy==1.18.5
pandas==1.1.5

_Originally posted by @levalencia in https://github.com/numpy/numpy/issues/18355#issuecomment-1041664383_

**Comment by melissawm** [comment]
It looks like you have multiple versions of pandas installed. Make sure your environments are set up correctly (see, for example, https://github.com/numpy/numpy/issues/18355#issuecomment-1040603696)

**Comment by melissawm** [comment]
In that case, it seems you have an old version of pandas just like it was reported in the original issue.

**Comment by levalencia** [comment]
The issue was on my environment, after installing a new compute instance with default conda environments I was able to upgrade numpy, pandas and the error is gone.

**Comment by layedra** [comment]
I was having the same error/issue in my local machine; a `conda update --all` fixed it for me as well. Thanks @levalencia
