### ISSUE TITLE
Feature: higher order singular value decomposition (HOSVD) (Trac #1510)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2107]
_Original ticket http://projects.scipy.org/numpy/ticket/1510 on 2010-06-11 by trac user jiahao, assigned to @pv._

Hi there,

I recently need to compute higher order singular value decompositions (HOSVDs) on some tensors. I coded up a quick and dirty implementation as described in the original paper and thought it might be a useful contribution to the numpy.linalg library. The code is attached and released to you under public domain.

If you do choose to incorporate the code, please note that:

1) the code is a direct implementation of the algorithm described in the original paper, and could probably be done more quickly and cleverly,
2) it has only been tested on the few examples in the original paper
3) there are some discrepancies up to overall signs in some columns of the left singular matrices.

cite:
    Lieven de Lathauwer, Bart de Moor, Joos Vandewalle,
    'A multilinear singular value decomposition',
    SIAM J. Matrix Anal. Appl. 21 (4), 2000, 1253-1278

**Comment by GiggleLiu** [comment]
I am interested in this project, have you done a benchmark with scikit-tensor?

In this fast developing area, the paper you cited is probably outdated.

**Comment by charris** [comment]
Hmm..., scikit-tensor doesn't look terribly active and is GPL-3 licensed, which is unusual for Python software. I'm not sure where the best place for tensor factorization would be, NumPy supplies ndarrays and basic algorithms and this sounds more specialized.

**Comment by mprat** [comment]
Broken links - I am interested in HOSVD as well and am happy to work on this with someone.

**Comment by jsevo** [comment]
Any progress yet? Need to consider this for my work, too.

**Comment by Algomorph** [comment]
+1

**Comment by mattip** [comment]
Strange this is getting attention after 7 years. As noted, the links are no longer valid, and it is not clear this belongs in NumPy in the first place. 

How does what you seek differ from [scikit-tensor](https://github.com/mnick/scikit-tensor), other than the GPL3.0 license?

**Comment by mertall** [comment]
Hey I stumbled upon this post. I coded up a simple HOSVD and I think it would be able to handle most cases. I made two cases, sparse data and regular. https://github.com/mertall/Facial-Recognition/edit/master/HOSVD.py

**Comment by mertall** [comment]
It looks like scikit tensor is failing now, being a nump fanboy, usually I try to do most of my ML through numpy because I can see what is going on step by step. HOSVD should be of value to others who may not want to dig in the trenches of HOSVD and just use it. It has some cool applications such as grabbing emotions of the face.

**Comment by mertall** [comment]
@mattip  what do you think?

**Comment by mattip** [comment]
I think I will close this issue since this is out of scope for NumPy.

**Comment by rgommers** [comment]
I agree. It would fit in `scipy.linalg`, but not in NumPy. @mertall if you'd want to put together a SciPy PR, that would be interesting.
