### ISSUE TITLE
Building wheel for numpy (setup.py) ... error WaveRNN

### ISSUE THREAD

**Issue by ljy-002** [numpy/numpy#21096]
### Steps to reproduce:

Windows: cmd:
WaveRNN>pip install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

Python: 3.9.10
pip: 22.0.3
OS: Windows 10 21H1
Numpy: 1.21.5
No Anaconda

### Additional information:

[第一次安装-失败.txt](https://github.com/numpy/numpy/files/8103319/-.txt)

**Comment by mattip** [comment]
wavernn on github pins to a very old version of [numpy==1.16.2](https://github.com/fatchord/WaveRNN/blob/3595219b2f2f5353f0867a7bb59abcb15aba8831/requirements.txt#L1). Can you edit that line to read `numpy` (a single word) so it does not pin? Then `pip install -r requirements.txt` should use your already-installed numpy1.21.5.

If you must build from source (how do you get OpenBLAS?), in your log there is this error
```
numpy\random\mtrand\mtrand.c(40475): error C2039: "tp_print": 不是 "_typeobject" 的成员
```

which translates to
```
numpy\random\mtrand\mtrand.c(40475): error C2039: "tp_print": not a member of "_typeobject" 
```

which means you are using an old version of Cython to convert `mtrand.pyx` to `mtrand.c`.

**Comment by ljy-002** [comment]
I tried it and it works! Thanks
