### ISSUE TITLE
BUG: Wrong transpose for multi indexing

### ISSUE THREAD

**Issue by PatrickHMGU** [numpy/numpy#21104]
### Describe the issue:

Indexing an multidimensional array with multiple indices returns a wrongly shaped array if one of the indices is an array.

### Reproduce the code example:

```python
import numpy as np

myArray = np.zeros( ( 3, 640, 480 ) )

mySub1 = myArray[ 0, :, [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ] ]

mySub2 = myArray[ 0, :, 0 : 10 ]

mySub1.shape
mySub2.shape
```

### Error message:

```shell
Output for mySub1 is: (10, 640)

Output for mySub2 is: (640, 10)
```

### NumPy/Python version information:

1.22.2 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]

**Comment by PatrickHMGU** [comment]
I have updated it, to make clear it is not a question. It's a bug in numpy.

**Comment by rossbar** [comment]
This is not a bug: the list in the `mySub1` case triggers [advanced indexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing) which has different behavior than the basic indexing used in `mySub2`.

Combining basic and advanced indexing in a single operation can get quite complicated: there's an entire [section on it in the docs](https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing).

**Comment by PatrickHMGU** [comment]
Apologize for my issue, I have never realized that this is a thing.
