### ISSUE TITLE
BUG: log1p output has less precision for the real part of small complex inputs

### ISSUE THREAD

**Issue by vmagno** [numpy/numpy#21105]
### Describe the issue:

The real part of the output of numpy.log1p is rounded down to zero when the real part of a complex input is less than about 1e-15. This does not occur for the imaginary part of a complex input/output, or when the input is real.
For example:
```
>>> import numpy as np
>>> np.log1p(1e-14 + 1e-14j)
(9.992007221626358e-15+9.9999999999999e-15j)
>>> np.log1p(1e-16 + 1e-16j)
1e-16j
>>> np.log1p(1e-16)
1e-16
>>> np.log1p(1e-16j)
1e-16j
```
This occurs on Linux with numpy version 1.22.2, and python version 3.10.2

### Reproduce the code example:

```python
import numpy as np
np.log1p(1e-14 + 1e-14j)
np.log1p(1e-16 + 1e-16j)
np.log1p(1e-16)
np.log1p(1e-16j)
```

### NumPy/Python version information:

1.22.2 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]

**Comment by seberg** [comment]
Identical to the newer gh-22609, closing this one as there is some activity.
