### ISSUE TITLE
BUG: Double indexing assignment doesn't work

### ISSUE THREAD

**Issue by fAndreuzzi** [numpy/numpy#21115]
### Describe the issue:

Assigning a value to a NumPy array after indexing twice does not change the actual array. I theorized that this happened because of fancy indexing (_fancy indexing always returns a copy of the array_) however I'm not sure that fancy indexing is actually used in my simple example.

### Reproduce the code example:

```python
import numpy as np
>>> a = np.array([1,2,3,4,5])
>>> a[[1,2]][0] = 100
# expected: [1,100,3,4,5]
>>> a
array([1, 2, 3, 4, 5])
```

### NumPy/Python version information:

1.21.3 3.9.7 (default, Oct 13 2021, 06:44:56) 
[Clang 12.0.0 (clang-1200.0.32.29)]

**Comment by rkern** [comment]
Your theory is correct. The expression `a[[1,2]][0] = 100` roughly translates to 

```
tmp = a[[1,2]]  # makes a copy
tmp[0] = 100  # modifies the copy
# And that's it. No assignment back to `a`
```

Python syntax doesn't really give us a way to interpret `a[[1,2]][0]` in the way that you want given the constraint that fancy indexing has to make a copy. Typically, other ways of spelling what you want are more readable and maintainable in any case.

**Comment by fAndreuzzi** [comment]
Thank you for the clarification.

**Comment by kabouzeid** [comment]
I find the inconsistency that `a[[1,2]] = 100` works while `a[[1,2]][0] = 100` does not extremely unintuitive.

**Comment by rkern** [comment]
That's fair; it is not intuitive. It's a compromise born of a number of constraints in tensions with one another, not a semantic that anyone specifically desired for that syntax. But it's not going to change because those constraints are still present.
