### ISSUE TITLE
unique and NaN entries (Trac #1514)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2111]
_Original ticket http://projects.scipy.org/numpy/ticket/1514 on 2010-06-18 by trac user rspringuel, assigned to unknown._

When unique operates on an array with multiple NaN entries its return includes a NaN for each entry that was NaN in the original array.

Examples:
a = random.randint(5,size=100).astype(float)

> > > a[12] = nan #add a single nan entry
> > > unique(a)
> > > array([  0.,   1.,   2.,   3.,   4.,  NaN])
> > > a[20] = nan #add a second
> > > unique(a)
> > > array([  0.,   1.,   2.,   3.,   4.,  NaN,  NaN])
> > > a[13] = nan
> > > unique(a) #and a third
> > > array([  0.,   1.,   2.,   3.,   4.,  NaN,  NaN,  NaN])

This is probably due to the fact that x == y evaluates to False if both x and y are NaN.  Unique needs to have "or (isnan(x) and isnan(y))" added to the conditional that checks for the presence of a value in the already identified values.  I don't know were unique lives in numpy and couldn't find it when I went looking, so I can't make the change myself (or even be sure what the exact syntax of the conditional should be).

Also, the following function can be used to patch over the behavior.

def nanunique(x):
    a = numpy.unique(x)
    r = []
    for i in a:
        if i in r or (numpy.isnan(i) and numpy.any(numpy.isnan(r))):
            continue
        else:
            r.append(i)
    return numpy.array(r)

**Comment by maxalbert** [comment]
I'm still seeing this issue with latest master. Which commit should have fixed it? Unless I'm missing something I'd suggest re-opening this issue.

**Comment by jaimefrio** [comment]
This is easy to fix for floats, but I don't see an easy way out for complex or structured dtypes. Will put a quick PR together and we can discuss the options there.

**Comment by charris** [comment]
@jaimefrio I have it fixed for unique using
```
    if issubclass(aux.dtype.type, np.inexact):
        # nans always compare unequal, so encode as integers
        tmp = aux.searchsorted(aux)
    else:
        tmp = aux
    flag = np.concatenate(([True], tmp[1:] != tmp[:-1]))
```
but it looks like all the other operations also have problems. Maybe we need  `nan_equal, nan_not_equal` ufuncs, or maybe something in nanfuntions.

**Comment by jaimefrio** [comment]
Sortsearching `aux` for itself is a smart trick! Although sortsearching *all* of it is a little wasteful, ideally we would want to spot the first entry with a nan, perhaps something along the lines of, after crating `aux` and `flag` as right now, doing:

```
if not aux[-1] == aux[-1]:
    nanidx = np.argmin(aux == aux)
    nanaux = aux[nanidx:].searchsorted(aux[nanidx:])
    flag[nanidx+1:] = nanaux[1:] != nanaux[:-1]
```

or something similar after correcting all of the off by one errors that I have likely introduced there.

**Comment by jaimefrio** [comment]
This last approach of mine would work for float and complex types, but fail for structured dtypes with floating point fields. But I still think that the searchsorting trick, even though it would work for all types, is too wasteful. Some timings:

```
In [10]: a = np.random.randn(1000)

In [11]: %timeit np.unique(a)
10000 loops, best of 3: 69.5 us per loop

In [12]: b = np.sort(a)

In [13]: %timeit b.searchsorted(b)
10000 loops, best of 3: 28.1 us per loop
```

That's going to be a 40% performance hit, which may be OK for a `nanunique` function, but probably not for the general case.

**Comment by Demetrio92** [comment]
2019 called, the OP post is still valid. 

@jaimefrio why can't we have it an option being false by default? 

I mean, this behaviour is confusing at best, and performance is not an excuse.

**Comment by mattip** [comment]
@Demetrio92 while I appreciate your attempt to get this issue moving, irony/sarcasm on the internet can be interpreted differently by different people, please keep it kind. For some of us, performance is very important and we don't casually add code that slows things down. 

PR #2111 may be a better place to comment or make suggestions how to move forward.

**Comment by urimerhav** [comment]
This issue seems to be open for 8 years, but I just want to chime in with a +1 for making the default behavior for `numpy.unique` to be correct rather than fast. This broke my code and I'm sure others have/will suffer from it. We can have an optional "fast=False" and document nan behavior for fast and nans. I'd be surprised if np.unique is very often the performance bottleneck in time-critical applications.

**Comment by ufmayer** [comment]
I ran into the same issue today. The core of the np.unique routine is computing a mask on an unravelled sorted array in numpy/lib/arraysetops.py to find when the values change in that sorted array:
```
mask = np.empty(aux.shape, dtype=np.bool_)
mask[:1] = True
mask[1:] = aux[1:] != aux[:-1]
```
This could be replaced by something like the following, which is pretty much along the lines of jaimefrio's comment from about 5 years ago, but avoids the argmin call:
```
mask = np.empty(aux.shape, dtype=np.bool_)
mask[:1] = True
if np.isnan(aux[-1]):
    aux_firstnan = np.searchsorted(aux, np.nan, side='left')
    mask[1:aux_firstnan] = (aux[1:aux_firstnan] != aux[:aux_firstnan-1])
    mask[aux_firstnan] = True
    mask[aux_firstnan+1:] = False
else:
    mask[1:] = aux[1:] != aux[:-1]
```
Running a few %timeit experiments I observed an at most < 10% runtime penalty if there are very few NaN (say 10 NaN out of 1 million), and it actually runs faster if there are lots of NaN.

**Comment by dderiso** [comment]
+1 
> "If the array does have NaNs then it produces a different result, combining the NaNs, which is the point of it all."

**Comment by Demetrio92** [comment]
@ufmayer submit a PR!

**Comment by dmitra79** [comment]
+1
I would also support returning NaN only once

**Comment by aerobio** [comment]
+1
As long as NaNs appear at the end of sorted arrays, this is what I'm using for 1D arrays for the time being:
```
>>> a = np.array([8, 1, np.nan, 3, np.inf, -np.inf, -2, np.nan, 3])
>>> unique = np.unique(a)
>>> unique
array([-inf,  -2.,   1.,   3.,   8.,  inf,  nan,  nan])
>>> truly_unique = unique[:np.argmax(unique)+1]
>>> truly_unique
array([-inf,  -2.,   1.,   3.,   8.,  inf,  nan])
```
