### ISSUE TITLE
BUG: <np.linspace produces number less than start when start is large number>

### ISSUE THREAD

**Issue by pantelic-dusan** [numpy/numpy#21122]
### Describe the issue:

When using large numbers for start and stop arguments of numpy.linspace output can be incorrect. As showed in example linspace should return [9007199254740993] but it returns [9007199254740992] , even it must produce numbers greater than start argument.

### Reproduce the code example:

```python
import numpy as np
np.linspace(9007199254740993, 9007199254740993, 1)
```

### NumPy/Python version information:

1.22.2 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0]

**Comment by rkern** [comment]
`linspace()` works in floating point numbers. `9007199254740993` is not representable by a float.

```
|1> np.float64(9007199254740993)                                                                                                                                                                                     
9007199254740992.0
```

**Comment by pantelic-dusan** [comment]
Thanks, I just needed to cast start and stop to np.longdouble
