### ISSUE TITLE
Sphinx build is broken?

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#21126]
Latest [circleCI runs](https://app.circleci.com/pipelines/github/numpy/numpy?filter=all) are failing with
```
sphinx.errors.SphinxParallelError: AttributeError: \
    'PosixPath' object has no attribute 'readlink'
```

This started about two days ago, [the last successful run](https://app.circleci.com/pipelines/github/numpy/numpy/13031/workflows/9d262aab-5486-48ba-a795-dc73d23e30ac) was the merge of #21119

**Comment by mayeut** [comment]
seems related to https://github.com/ipython/ipython/issues/13554
I'm currently looking into this.
