### ISSUE TITLE
DOC: Better Developer Friendly addition to Building from Source Page

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy#21156]
### Issue with current documentation:

Additions to the Building from source page for a better developer-friendly experience.

### Addition 1
Page under Consideration - [Building from source](https://numpy.org/devdocs/user/building.html#building-from-source)
The addition of `pip install Cython` just below Cython is listed as a Prerequisite. It could make developer workflow much more smooth and more easily accessible.

Result -
![Cython](https://user-images.githubusercontent.com/41142068/156917921-782c62cb-1aff-46ca-963e-9022a6bbd3ba.png)

### Addition 2 
Page under Consideration - [Building from source](https://numpy.org/devdocs/user/building.html#building-from-source)
Add `pip install -r test_requirements.txt` as **Pre-Step** for testing the builds.

Result - 
![requirements_addition](https://user-images.githubusercontent.com/41142068/156917948-c902e682-9d7f-407c-a7ec-622f0f592a95.png)

Other Reference Pages present, such as
1) [Testing builds](https://numpy.org/devdocs/dev/development_environment.html#testing-builds)
2) [Setting up and using your development environment](https://numpy.org/devdocs/dev/development_environment.html#development-environment).

Also, don't address these Pre-Steps.

All these additions are suggested to make Developer Friendly Documentation and ease their workflows.

**Comment by BvB93** [comment]
> Page under Consideration - [Building from source](https://numpy.org/devdocs/user/building.html#building-from-source)
The addition of pip install Cython just below Cython is listed as a Prerequisite. It could make developer workflow much more smooth and more easily accessible.

Manual installation of Cython shouldn't be necessary, right? Considering it's already specified as a build requirement in `pyproject.toml`.

**Comment by bhavukkalra** [comment]
Thank you for such a thrifty feedback.
I am not quiet versed with `pyproject.toml` but I can affirm your claim. As when I was building numpy on my System.
with Specifications - Windows 10, MingW Compiler Collection.

I didn't needed to have Cython installed either through `pip` or manual installation through source.
So are you suggesting that we should remove the Cython dependency from [Building from source](https://numpy.org/devdocs/user/building.html#building-from-source) entirely?

and what are your thoughts on Addition 2 @BvB93?

**Comment by bhavukkalra** [comment]
Sure, Creating a PR Addressing Addition 2. Will update you on the same!

**Comment by melissawm** [comment]
I believe there is one workflow at least that requires manual installation of cython: If you clone the repo and don't `pip install -r test_requirements.txt` before trying to build (say, if you just want to build the docs).

**Comment by BvB93** [comment]
> I believe there is one workflow at least that requires manual installation of cython: If you clone the repo and don't `pip install -r test_requirements.txt` before trying to build (say, if you just want to build the docs).

That's fair, but if cython is a hard requirement for building the docs (and isn't installed automatically), shouldn't it be added to `test_requirements.txt`?

**Comment by rossbar** [comment]
> That's fair, but if cython is a hard requirement for building the docs (and isn't installed automatically), shouldn't it be added to doc_requirements.txt?

I think it's building numpy itself that's a hard requirement for building the docs from source (there's that check that asserts that the git hash matches the current installed numpy version) so I think listing Cython as a numpy build requirement (in the pyproject.toml) covers the doc-building case?

**Comment by rossbar** [comment]
I think this issue was sufficiently addressed by #21167 - closing.
