### ISSUE TITLE
numpy.concat does not appear to work across broadcast axes (Trac #1518)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2115]
_Original ticket http://projects.scipy.org/numpy/ticket/1518 on 2010-06-22 by trac user eob, assigned to unknown._

When I'm trying to concatenate two tensors together, the concatenate operation does not allow me to use broadcast dimensions (using newaxis) in one of them.

**Comment by jluttine** [comment]
Any news/progress on ```np.concatenate``` supporting broadcasting?

**Comment by jaimefrio** [comment]
There has been some discussions about this on the list in the past, and the collective wisdom dictated that broadcasting in a concatenate operation was more likely to be masking unintended mistakes, than a useful functionality. We probably should close this.

In any case, if you would like to stirr that conversation up again, the right place would be the mailing list, not here.

**Comment by jaimefrio** [comment]
Should this be closed as a "won't fix"?

**Comment by shoyer** [comment]
Agreed. Note  that manual broadcasting is now a little bit easier  because we have broadcast_to.

**Comment by jaimefrio** [comment]
I just needed a tiny bit of positive reinforcement, closed it is. If anyone has a strong opinion against this, feel free to reopen.

**Comment by davidmashburn** [comment]
I found a solution that seems solid to me... just use broadcast_arrays in the form np.concatenate(np.broadcast_arrays(*arrays), axis=...). Ex: np.concatenate(np.broadcast_arrays(0, [1, 2], [[3, 4], [5, 6]]), axis=1)  --> array([[0, 0, 1, 2, 3, 4], [0, 0, 1, 2, 5, 6]])

**Comment by oulenz** [comment]
@davidmashburn I think there is a problem with this solution (and with manual broadcasting in general as suggested by others in this thread). I don't think it makes sense to broadcast in the dimension in which we concatenate. In other words, in your case I would only expect to end up with one column of zeros.

**Comment by boeddeker** [comment]
If someone else also finds this Issue, while searching for a solution of broadcasting in concatenate, I posted my solution at https://stackoverflow.com/questions/56357047/concatenate-with-broadcast/61061019#61061019
