### ISSUE TITLE
BUG: assert np.array([False]).all() is False fails

### ISSUE THREAD

**Issue by jakobkolb** [numpy/numpy#21165]
### Describe the issue:

The title says it all.

Of the tests below, the first one fails, while the second one passes. I would expect them both to pass and I am puzzled by this behavior.

### Reproduce the code example:

```python
import numpy as np
def test_numpy_all_returns_boolean_1():
    assert np.array([False]).all() is False


def test_numpy_all_returns_boolean_2():
    assert np.array([False]).all() == False
```

### Error message:

```shell
>       assert np.array([False]).all() is False
E       assert False is False                                                       
E        +  where False = <built-in method all of numpy.ndarray object at 0x7f43a3c222d0>()                                                                             
E        +    where <built-in method all of numpy.ndarray object at 0x7f43a3c222d0> = array([False]).all                                                                
E        +      where array([False]) = <built-in function array>([False])
E        +        where <built-in function array> = np.array
```

### NumPy/Python version information:

1.22.2 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

**Comment by QuadV** [comment]
`is` and `is not` are Python Identity Operators. Identity operators compare the memory locations of two objects.
The == operator is used to test if two variables are equal.

```
x = ["apple", "banana", "cherry"]
y = x
print(x is y)

```

This will be True, because both are pointing to the same memory location. i.e. they are pointers to the same location. Changes to one will effect the other. 

In the above mentioned case, `np.array([False]).all()` and `False` are different objects/temporary variables pointing to different locations.

**Comment by mattip** [comment]
`np.array([False]).all()` returns a numpy scalar. To convert it to a python boolean, do `bool(np.array([False]).all())`. Usually in tests people do `assert not np.array([False]).all()` or so to avoid comparing the value to `True` or `False`.

**Comment by BvB93** [comment]
[PEP 8](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) rather explicitly advices one to avoid these `is` checks for truth-testing, so I'd honestly just suggest disabling E712 in whatever linter you're using:

> * Don't compare boolean values to True or False using ==:
>
> ``` python
> # Correct:
> if greeting:
> ```
>
> ``` python
> # Wrong:
> if greeting == True:
> ```
> Worse:
>
> ``` python
> # Wrong:
> if greeting is True:
> ```

**Comment by charris** [comment]
`is` works for singletons, usually classes and small integers.
```
In [3]: a = 2**10

In [4]: b = 2**10

In [5]: a is b
Out[5]: False

In [6]: a = 1

In [7]: b = 1

In [8]: a is b
Out[8]: True
```

**Comment by jakobkolb** [comment]
@mattip this is elegant, I'll do that from now on. Thanks everyone for your answers, I'll close this as this clearly isn't a bug and my questions are answered.
