### ISSUE TITLE
incomplete path with np.loadtxt

### ISSUE THREAD

**Issue by LogWell** [numpy/numpy#21173]
### Describe the issue:

[Link](https://rec.ustc.edu.cn/share/672bbc20-9f48-11ec-8fa4-af76c0d5e041) to test file.

When I use `np.loadtxt` to read the path file, some paths lack suffix, that is, the original `*.png` may be read as `*.p` or `*.pn`.

When I take out the problematic line to generate a new file, it can be read normally again.

### Reproduce the code example:

```python
import os
import numpy as np
from glob import glob

path_data_patch_train = "path_data_patch_train.txt"
data_patch_train = np.loadtxt(path_data_patch_train, dtype=str)

for idx, item in enumerate(data_patch_train):
    if idx < 50000 or idx > 70000:
        continue
    for it in item:
        # it = glob(it + "*")[0]
        if not os.path.exists(it):
            print(idx, it)
            exit()

```
```


### Error message:

```shell
59580 /media/lab0/SSD2TS1/NaGenHao/Datasets/dataset@h3d/POSED/GobotreePeople/hdqjd__M1/gtp_cwman_spg_13_andrea_cpl_wk_pntg_adl_ccs_mgr/bRendered_IGLOM/Z000/data_v4/for_network/img_nC_00000.pn
```

### NumPy/Python version information:

1.19.2 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

**Comment by bashtage** [comment]
May or may not be a bug.  Somehow NumPy is guessing that your lines have 185 characters or fewer.  It is then truncating at 185 characters.  A workaround is 

```python
data = np.loadtxt("path_data_patch_train.txt",dtype=np.dtype("<U256"))
```

which assumes that your strings have 256 or fewer characters.  I suspect the 185 is set from reading a few of the initial lines (probably 1) slowly and then committing to a size.  The first line has 1 entry with a size of 158, and that is probably globally setting the size. 

I would probably use pandas

```python
data = pd.read_csv("path_data_patch_train.txt",sep=" ")
```

which gets it correct immediately, at the cost of producing a lot of objects.

**Comment by LogWell** [comment]
```
data = pd.read_csv("path_data_patch_train.txt",sep=" ", header=None)
```

**Comment by seberg** [comment]
There was indeed a bug with large files and `str`, it is fixed on main though.
