### ISSUE TITLE
numpy.distutils mixes CFLAGS and CXXFLAGS (Trac #1521)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2118]
_Original ticket http://projects.scipy.org/numpy/ticket/1521 on 2010-06-25 by trac user killua.eu, assigned to @cournape._

Please see [https://bugs.gentoo.org/show_bug.cgi?id=236332] for details. Thanks!

**Comment by jlec** [comment]
@charris Please reopen. This is still valid until current HEAD.

**Comment by pv** [comment]
This is Python distutils issue, reproducible without numpy distutils. Not something we can or should fix here, especially as it's not causing real problems.

Also, Python distutils calls the env var CPPFLAGS, CXXFLAGS has apparently no effect.

**Comment by pv** [comment]
The place to change would be here: https://github.com/numpy/numpy/blob/master/numpy/distutils/ccompiler.py#L498 Python distutils itself just uses the C compiler command to compile also c++, and uses the cxx command only for linking. There's no concept of separate c++ flags. This in principle could be introduced in numpy.distutils.

**Comment by jlec** [comment]
Here is the corresponding issue http://bugs.python.org/issue1222585 with a proposed patch

**Comment by pv** [comment]
It seems that patch will not land except maybe in Python 3.5. If it lands, numpy.distutils needs changes.
In either case, it may be possible to adjust how the c++ flags are handle in numpy.distutils.

**Comment by woodenToaster** [comment]
@pv I'm trying to build scipy with VS2015 and the intel compiler v16.0.  When it begins compiling the c++ sources, it gives a warning saying
```
icl: command line warning #10381: option '/Qstd=c99' is not valid for C++ compilations
```
then throws several errors.  I can fix these errors by compiling the c++ sources with the `/Qstd=c++11` flag.  Basically I need a way to compile c sources with `/Qstd=c99` and c++ sources with `Qstd=c++11`.  This is holding up our builds, so I really need to fix it soon.  Could you offer any advice on what I would need to change in `numpy.distutils`?  Thanks in advance.

**Comment by InessaPawson** [comment]
Given numpy.distutils has been officially deprecated and the most recent comment dates back to 2015, should we close this PR?
