### ISSUE TITLE
Importing the numpy c-extensions failed in REPLIT

### ISSUE THREAD

**Issue by abeghelli** [numpy/numpy#21181]
Hi!
I have checked this page to deal with the error described in the subject:
https://numpy.org/devdocs/user/troubleshooting-importerror.html

However, no guidance is provided for the online REPLIT environment when finding this error. It might be a temporary platform problem, but I am not sure. Any advice on how to solve the problem would be great. Thanks!

**Comment by mattip** [comment]
What is the replit environment? Do you mean replic.com? I think you would be better off asking in their support, like [this user did](https://replit.com/talk/ask/How-can-I-install-numpy-here/39509)

**Comment by abeghelli** [comment]
Dear Matti,
I had already reviewed all the replit support before asking Numpy (it was not a simple problem of installing a module,). Anyway, I have managed to solve the problem 🙂
All the best, A.

Dr. Alejandra Beghelli (she/her)
Lecturer
Deputy Director of Equality, Diversity and, Inclusion
Electronic & Electrical Engineering Department
University College London
________________________________

**Comment by mattip** [comment]
Could you share the solution?

**Comment by abeghelli** [comment]
Sure, please find it attached.
All the best, A.

Dr. Alejandra Beghelli (she/her)
Lecturer
Deputy Director of Equality, Diversity and, Inclusion
Electronic & Electrical Engineering Department
University College London
________________________________

**Comment by mattip** [comment]
I didn't find an attachment on this github issue. You can't upload an attachment via email.

**Comment by seberg** [comment]
Going to close the issue since you found a solution.  A brief followup so that others may find it would be great though!  (since github removed the attachments)
