### ISSUE TITLE
TYP: np.lib.stride_tricks is not marked as being public

### ISSUE THREAD

**Issue by twoertwein** [numpy/numpy#21183]
### Describe the issue:

`sliding_window_view` is a public function, but it is inaccessible to type checkers.

### Reproduce the code example:

```python
import numpy as np

np.lib.stride_tricks.sliding_window_view
```

### Error message:

```shell
pyright: "stride_tricks" is not a known member of module (reportGeneralTypeIssues)
```

### NumPy/Python version information:

1.22.3 3.10.2 (v3.10.2:a58ebcc, Mar 10 2022, 19:36:59) [GCC 9.4.0]

**Comment by BvB93** [comment]
Ah, found the problem: there is a typo in the re-exporting statement.
The issue should be fixed as of https://github.com/numpy/numpy/pull/21185.

**Comment by twoertwein** [comment]
Great, thank you very much @BvB93!
