### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy' VS Code

### ISSUE THREAD

**Issue by Arthasee** [numpy/numpy#21198]
### Steps to reproduce:

I install numpy 1.22.3 with pip, I'm on macOs X 12.2.1 and I use python 3.10.2 64 bits. 

I uninstall et re-install 3 times numpy but nothing change, when i import numpy it doesn't appear a problem, but when i run my program, they say 'No module named nulmpy'.

If someone can help me, it would be very great

Thanks.

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/pascalbraun/Library/CloudStorage/OneDrive-etu.sorbonne-universite.fr/Anaconda/test.py", line 1, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

**Comment by bhavukkalra** [comment]
MacOSX does comes with its own python installation, Most probably you are installing numpy in one version and trying to import in another.
For instance `pip install numpy` -> Will install numpy for MacOSX default Python 2.7 version
while
`pip3 install numpy` will install numpy for Externally downloaded version.

Solution/Debugging - 
1) Try using `venv` or `anaconda` and create a virtual environment
2) Activate the virtual environment
3) Install numpy in that environment
4) Run python(On MacOSX default Terminal) and try to do `import numpy` it should ideally work

**Comment by Arthasee** [comment]
Hi, I was totally dumb... I didn't run correctly my files with VS Code, everything works well!

Thanks for your help
