### ISSUE TITLE
Additional file auto-generated "x86-qsort.dispatch.avx512_skx.cpp" in gitpod

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy#21190]
### Steps to reproduce:

This issue is coming along with the reporting of issue #21177. When I used gitpod, this additional file was being created and was not added to version control.

File auto-generated - 
![New_issue](https://user-images.githubusercontent.com/41142068/158073470-0dbb6004-07df-4b27-9e02-aa39b546640b.PNG)

On-Further digging, this file was referenced in this commit/ PR - [Changes in setup.py](https://github.com/numpy/numpy/pull/21099/files).

Proposal: If this is a file that is supposed to be generated, then I think this can be added to version control, and this issue can be closed.

Note - Tho issue #21177 has been reported, and gitpod CI build failing, but still able to run gitpod instance with 
Python -  `3.9.10`
Numpy Version - `1.23.0.dev0+885.g27e4970bf`

### Error message:

```shell
NA
```

**Comment by rossbar** [comment]
Maybe an autogenerated file that was accidentally left out of `.gitignore`? @serge-sans-paille thoughts?

**Comment by bhavukkalra** [comment]
This issue seems to have resolved itself and the additional file is not longer getting generated. Closing this for now. Let's see if it is brought up again in the next release.

**Comment by serge-sans-paille** [comment]
(sorry for the delay) In main branch, this file is *not* a generated file, it's the primary source :-)
