### ISSUE TITLE
`np.ma.masked_all` doesn't expect type 'int'

### ISSUE THREAD

**Issue by eliadl** [numpy/numpy#21203]
**Background:**
`np.ma.masked_all` accepts `int` type as valid input and successfully generates output.

**Problem:**
`np.ma.masked_all` doesn't _expect_ the `int` type. It only expects `Union[Iterable, tuple]`.

**Suggested solution:**
`np.ma.masked_all` should expect `int` too, like `np.ma.empty` etc.

**Example:**
```python
np.ma.masked_all(3)
```
returns
```python
masked_array(data=[--, --, --],
             mask=[ True,  True,  True],
       fill_value=1e+20,
            dtype=float64)
```
but it also creates a warning in the IDE:
```
Expected type 'Union[Iterable, tuple]', got 'int' instead 
```

**Environment:**
python 3.7.10 + numpy 1.21.1

**Comment by BvB93** [comment]
> Agreed, the parameter type for `shape` is not correct. `np.ma.masked_all` uses `np.empty` under the hood, so the parameter description (and type annotation) for `shape` in `masked_all` should be updated to match that of `np.empty`.

The `np.ma` namespace currently lacks type annotations, so I'm guessing the relevant IDE is grabbing them from the functions' docstring (similar to https://github.com/numpy/numpy/issues/21011). @eliadl are you using PyCharm by any chance?

**Comment by rossbar** [comment]
> The np.ma namespace currently lacks type annotations, so I'm guessing the relevant IDE is grabbing them from the functions' docstring (similar to https://github.com/numpy/numpy/issues/21011). @eliadl are you using PyCharm by any chance?

Thanks @BvB93 for pointing that out - in that case ignore what I said about type annotations - the parameter type in the docstring should be fixed!
