### ISSUE TITLE
BUG: `__iadd__()` for `numpy.array_api` arrays does not follow negative zeros special case

### ISSUE THREAD

**Issue by honno** [numpy/numpy#21211]
### Describe the issue:

The Array API spec requires [`__add__()`](https://data-apis.org/array-api/latest/API_specification/generated/signatures.array_object.array.__add__.html#signatures.array_object.array.__add__), and by extension `__iadd__()`, to output a negative 0 when both operands are negative 0. NumPy currently follows this special case for `__add__()`, but not for `__iadd__()`. cc @asmeurer 

(I'll have a look at fixing this later.)

### Reproduce the code example:

```python
In [4]: x1 = xp.asarray(-0.)

In [5]: x2 = xp.asarray(-0.)

In [6]: x1 + x2
Out[6]: Array(-0., dtype=float64)

In [7]: x1 += x2

In [8]: x1
Out[8]: Array(0., dtype=float64)  # should be -0.
```

### NumPy/Python version information:

1.22.3 3.8.12 (default, Mar 13 2022, 19:12:08) 
[GCC 9.4.0]

**Comment by asmeurer** [comment]
This seems to be a problem in base NumPy:

```py
>>> import numpy as np
>>> x1 = np.array(-0.)
>>> x1 + x1
-0.0
>>> x1 += x1
>>> x1
array(0.)
```

**Comment by honno** [comment]
> This seems to be a problem in base NumPy

Yep, Sebastian identified the underlying issue in https://github.com/numpy/numpy/pull/21212#issuecomment-1070980917
