### ISSUE TITLE
BUG: float64 nan changes hash

### ISSUE THREAD

**Issue by PrimozGodec** [numpy/numpy#21210]
### Describe the issue:

Float64 nan value changes its hashes, which is annoying when transforming array to another structure (e.g. tuple) and wants to compute has. I would expect that nan's hash would not change. It is happening just for float64 nans and only with Python 3.10. 

### Reproduce the code example:

```python
for i in range(10):
    print(hash(np.float64("nan")))
```
Result:
```
8783812829447
8783812829423
8783812829447
8783812829423
8783812829447
```

Observe different hashes. Also reproducible with running `hash(np.float64("nan"))` multiple times in python console.

### NumPy/Python version information:

1.22.3
Python version: 3.10

**Comment by mattip** [comment]
What python, operating system? Where did you get numpy? What hashes do you see? This does not reproduce for me, I consistently get `0` on ubuntu 20.04 with python3.8, numpy from PyPI.

**Comment by PrimozGodec** [comment]
@mattip sorry for missing information. I added some more descriptions above. It only happens with python 3.10 (it works fine in older versions). [The reason might be nan hashing changes introduced in Python3.10](https://docs.python.org/3/whatsnew/3.10.html)

**Comment by PrimozGodec** [comment]
@mattip 
- outputs are in the description above (look results), 
- operating system (previous comment):

> The behaviour is present in any operating system.

- Where did you get numpy? PyPI (with pip)

**Comment by mattip** [comment]
Thanks! Sorry for being a nudnik.

**Comment by mattip** [comment]
For me (ubuntu 20.10) the values are 8754929507861 and 8754929507857.

**Comment by PrimozGodec** [comment]
For me macOS values alternate when running from the script (like in the results above), but when running from interpreter they are different on every execution:

```
print(hash(np.float32(np.nan)))
8767344821469
print(hash(np.float32(np.nan)))
8767344821477
print(hash(np.float32(np.nan)))
8767344821489
print(hash(np.float32(np.nan)))
8767344821459
print(hash(np.float32(np.nan)))
8767344821477
```

**Comment by seberg** [comment]
We use the Python hash function, so you get a value depending on the identity (I think) on Py <3.10, and a stable result on Py >3.10.  See gh-18908.  Please comment/reopen if I am missing something else.

**Comment by mattip** [comment]
@PrimozGodec you can read more about the motivation in the [CPython issue](https://bugs.python.org/issue43475#msg388508)
