### ISSUE TITLE
DOC: Misspelling "numpy.squeeze"

### ISSUE THREAD

**Issue by lzqlzzq** [numpy/numpy#21215]
### Issue with current documentation:

In documentation of "numpy.squeeze" (https://numpy.org/devdocs/reference/generated/numpy.squeeze.html#numpy.squeeze), paragraph 1, "axis" was misspelling as "axes". I am sure there is no "axes" in numpy?

**Comment by seberg** [comment]
Thanks for the note.  I agree it can be confusing, but is correct: axes is the plural of axis!  But the distinction between "axis" and "axes" can be very confusing, at least for non-native speakers...

The best idea I have right now, is that we use "dimensions" quite often as well, so using that or both, might clarify it.  Doc improvement ideas are always welcome!

**Comment by charris** [comment]
> at least for non-native speakers

Few speak Latin these days :)

**Comment by lzqlzzq** [comment]
Thanks for you explaination~ I shall close this issue.
