### ISSUE TITLE
Syntax for gradient calculation with unevenly spaced data

### ISSUE THREAD

**Issue by Gypaets** [numpy/numpy#21225]
I'm trying to calculate the gradient (df/dx, df/dy) of a 2D function f(x, y) with unevenly spaced data. 

Is there a function do to this in numpy? What is the correct syntax?

I've tried using  [`numpy.gradient`](https://numpy.org/doc/stable/reference/generated/numpy.gradient.html) but can't get the syntax right. 

For example:
```
import numpy as np

x = np.array([0, 1, 2, 2, 0])
y = np.array([0, 1, 0, 2, 2])
f = x + y
```
I expect `np.gradient(f, x, y))` to calculate the right values ([[1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]) but I'm getting an error.

`f` is _An N-dimensional array containing samples of a scalar function._, and after that `x, y` is _N arrays to specify the coordinates of the values along each dimension of F. The length of the array must match the size of the corresponding dimension_ (definition 3. of *varargs).

Other variants (e.g. `np.gradient(f, np.array([x, y]))` don't work either. I can't find a similar example in the documentation. Is there perhaps a different function for this type of gradient calculation? Many thanks

**Comment by mattip** [comment]
I think there is some confusion about what `np.gradient` is calculating. The gradient over `x,y` would require `f` to be 2d. But your `f`  is 1d, the result of adding two vectors. This may help you get going:
```python
>>> x = np.arange(10).reshape([-1, 10])
>>> y = np.arange(10).reshape([10, -1])
>>> f = x + y
>>> f.shape
(10, 10)
>>> np.gradient(f, x[0], y[:,0])
...
```

**Comment by Gypaets** [comment]
Thanks for the reply @mattip. I'm sure that there is some confusion (probably on my side), but I don't understand where.

I have a function _f_ which depends on _x_ and _y_. For me, calculating the [gradient](https://en.wikipedia.org/wiki/Gradient) means getting the derivative of _f_ with respect to _x_ and _y_ . This is what I'm trying to achieve, and I thought that `np.gradient` would be the right function for it. I'm not sure why does _f_ need to be 2d (in reality I have a set of points and the value of the function at each one of them, as shown in the example, and they are 1d arrays).

Following your code, I created a new example that seems to work:

```
x = np.array([[4, 5, 2, 7, 8]])
y = np.transpose(np.array([[1, 2, 5, 7, 3]]))
f = x*y + 3*x + 2*y + 1
dfdx_theoretical = np.transpose(y)[0] + 3
dfdy_theoretical = x[0] + 2

grad = np.gradient(f, x[0], y[:,0])
dfdx_calculated = grad[1][:,0]
dfdy_calculated = grad[0][0,:]

print('df/dx (theoretical): ', dfdx_theoretical, '\ndf/dx (calculated): ', dfdx_calculated)
print('\n\ndf/dy (theoretical): ', dfdy_theoretical, '\ndf/dy (calculated): ', dfdy_calculated)
```
However, once there is a decimal number (e.g. changing 4 to 4.1) in the coordinates, the calculated gradient does not match the theoretical anymore and I don't understand why. Perhaps I am using the function for something it is not intended, but from the documentation (gradient of an N-dimensional array) I think that it should be the right one.

**Comment by Gypaets** [comment]
@mattip Thanks for the explanation, I'm closing this issue. Due to the name `gradient`, I thought it calculated _derivatives_, and not _differences_. I've looked into the `autodiff` packages but the one's I've seen (many thanks to the professor spamming pypi with duplicate and mostly undocumented packages) are not suitable for my case, since they try to evaluate the function themselves. The values of my _f_ are very expensive to compute and are calculated with a simulation in a different program. That's the reason I can only provide the values of _f_ at _x_ and _y_ (mesh node coordinates).

* Your're absolutely right, in my code examples `f` is an array of the values of the function at the points, and not the function itself.
