### ISSUE TITLE
DOC: <numpy.real examples out of order>

### ISSUE THREAD

**Issue by FeynmanDNA** [numpy/numpy#21236]
### Issue with current documentation:

numpy.real **examples** seem to be **out of order**.

The current examples read:
```
    Examples
    --------
    >>> a = np.array([1+2j, 3+4j, 5+6j])
    >>> a.real
    array([1.,  3.,  5.])
    >>> a.real = 9
    >>> a
    array([9.+2.j,  9.+4.j,  9.+6.j])
    >>> a.real = np.array([9, 8, 7])
    >>> a
    array([9.+2.j,  8.+4.j,  7.+6.j])
    >>> np.real(1 + 1j)
    1.0
```

But `a.real = 9` following an existing a.real of array[1,3,5] does not make sense.

Furthermore, a.readl of `[9,8,7]` should be after re-initializing a to be the second last line value

### Idea or request for content:

Here is my suggested edit:
```
    Examples
    --------
    >>> a = np.array([1+2j, 3+4j, 5+6j])
    >>> a.real
    array([1.,  3.,  5.])
    >>> a.real = 9
    >>> a = np.array([9.+2.j,  8.+4.j,  7.+6.j])
    >>> a
    array([9.+2.j,  8.+4.j,  7.+6.j])
    >>> a.real = np.array([9, 8, 7])
    >>> np.real(1 + 1j)
    1.0
```

**Comment by rkern** [comment]
Note that the `=` here is _assignment_, not an equality comparison.
