### ISSUE TITLE
BUG:  importing numpy 1.22.3 throws error No module named 'numpy.random._common'

### ISSUE THREAD

**Issue by sweenb1** [numpy/numpy#21230]
### Describe the issue:

After installing Numpy 1.22.3 (first time install) the "import numpy" command gives error:
No module named 'numpy.random._common'
Tried uninstalling/reinstalling several times. Then uninstalled version 1.22.3 and installed version 1.22.2 and the import worked without error.

### Reproduce the code example:

```python
No code see error message
```

### Error message:

```shell
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\__init__.py", line 155, in <module>
    from . import random
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\__init__.py", line 180, in <module>
    from . import _pickle
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 1, in init numpy.random.bit_generator
ModuleNotFoundError: No module named 'numpy.random._common'
>>>
```

### NumPy/Python version information:

print(sys.version)
3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]

**Comment by charris** [comment]
Probably an install problem. How did you install NumPy, and where did it come from?

**Comment by sweenb1** [comment]
I used "pip install numpy". Pip version is 22.0.4 (Python 10). I don't know where pip downloads from but everything is default.

**Comment by bashtage** [comment]
Do you use McAfee AV?  It is possible the underlying binary is being blocked.

**Comment by sweenb1** [comment]
I do have McAfee. I can't test-disable it because it's corporate controlled.
I compared the 1.22.2 & 1.22.3 folders after each install and found that the file _common.cp310-win_amd64.pyd is missing from the 1.22.3 install. When I copy that file in to the 1.22.3 folder, the error goes away. For some reason 1.22.3 is not installing that file in my system. Maybe caused by McAfee if it thinks it's got a virus or something but I can't tell.
The issue is not affecting me directly. If I'm the only one who reported it feel free to close.

**Comment by charris** [comment]
> I do have McAfee

That's interesting, there is a report of McAfee Endpoint complaining about 1.22.3. See #21234.

I'll close this for now, feel free to comment further is there are developments.

**Comment by miserable-variable** [comment]
I don't understand Python packaging at all but FWIW adding this note.

- I have been trying `spacy` past few days and it worked fine. I tried after several days today and started getting this error without any changes by me
- It did not resolve by enabling McAfee Endpoint Security Timed Groups (which I think is Firewall, not on-access scan, so it may not be what was required)
- Switching to 1.22.2 resolved it
