### ISSUE TITLE
BUG: restructuredtext VSCode Extension Un-responsive in Gitpod

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy#21246]
### Describe the issue:

restructuredtext - An extension which is used to render live preview of the Documentation is not working. In short `unable to display live preview`

Live Preview Not loading up - 

![OBSELETE_PROBLEMS](https://user-images.githubusercontent.com/41142068/160176965-46651ba4-d3bc-4d66-a987-0343a11d36a0.PNG)

**Issue cause** - Deprecated vscode settings, After the [178.0.0](https://github.com/vscode-restructuredtext/vscode-restructuredtext/releases/tag/178.0.0) release (Which was released 12 days ago, from the day of reporting this issue). Which made certain settings the project is using not work any more

**Solution** - Replace the settings with the newer ones

### Reproduce the code example:

```python
Open up the Repo via Gitpod Chrome Extension
```

### NumPy/Python version information:

RAN ON GITPOD

print(numpy.__version__)
**1.23.0.dev0+950.g266aad747**

print(sys.version)
3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0]

**Comment by bashtage** [comment]
I don't think this is a Numpy issue. You should open an issue on the tracker of the extension.

**Comment by bhavukkalra** [comment]
We have to make some changes in our Repo. As explained above they have made some VS code properties that we were using for the Live-Preview to work Obsolete and completely moved to Esbonio based Live-Preview from Docutils based preview(Which we were also using). I am currently working on a PR to use the latest properties which they released in [178.0.0](https://github.com/vscode-restructuredtext/vscode-restructuredtext/releases/tag/178.0.0)

**Comment by rossbar** [comment]
> I don't think this is a Numpy issue. You should open an issue on the tracker of the extension.

NumPy maintains the gitpod instance internally, so I do think the changes in #21250 (or similar) are necessary.

**Comment by trallard** [comment]
Was this ultimately fixed? @bashtage  I got swamped and forgot to check before

**Comment by bhavukkalra** [comment]
Yes, This was fixed with the Attached PR. Closing
