### ISSUE TITLE
Gitpod Instance not able to build docs Failing at "make html"

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy#21252]
### Steps to reproduce:

Open up a  Gitpod Instance. During its Pre-Setup. The Setup fails at the command "make html".

Also tested on local with the same configuration as on Gitpod i.e Conda, Python=3.9 and its dependencies via conda-forge channel got the same error.

Error on Gitpod -
![make-html error](https://user-images.githubusercontent.com/41142068/160254313-604a95b7-5011-42e0-adca-78f3a6797962.PNG)

### Error message:

```shell
WARNING: while setting up extension breathe: node class 'graphviz' is already registered, its visitors will be overridden

Traceback (most recent call last):
  File "/home/gitpod/mambaforge3/envs/numpy-dev/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/gitpod/mambaforge3/envs/numpy-dev/lib/python3.9/site-packages/sphinx/application.py", line 237, in __init__
    self.setup_extension(extension)
  File "/home/gitpod/mambaforge3/envs/numpy-dev/lib/python3.9/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/gitpod/mambaforge3/envs/numpy-dev/lib/python3.9/site-packages/sphinx/registry.py", line 442, in load_extension
    metadata = setup(app)
  File "/home/gitpod/mambaforge3/envs/numpy-dev/lib/python3.9/site-packages/breathe/__init__.py", line 14, in setup
    renderer_setup(app)
  File "/home/gitpod/mambaforge3/envs/numpy-dev/lib/python3.9/site-packages/breathe/renderer/sphinxrenderer.py", line 2613, in setup
    app.add_config_value("graphviz_dot", "dot", "html")
  File "/home/gitpod/mambaforge3/envs/numpy-dev/lib/python3.9/site-packages/sphinx/application.py", line 525, in add_config_value
    self.config.add(name, default, rebuild, types)
  File "/home/gitpod/mambaforge3/envs/numpy-dev/lib/python3.9/site-packages/sphinx/config.py", line 281, in add
    raise ExtensionError(__('Config value %r already present') % name)
sphinx.errors.ExtensionError: Config value 'graphviz_dot' already present
```

**Comment by rossbar** [comment]
IIRC this is a bug in `breathe` - can you check what version of `breathe` is being installed in gitpod? The problem appears to be with version 4.33.0 - see michaeljones/breathe#803.

**Comment by bhavukkalra** [comment]
When I ran `conda search -c conda-forge breathe` to search for what versions of breathe were available. I got a complete list, out of which some entries are
breathe                       4.31.0    pyhd8ed1ab_0  conda-forge         
breathe                       4.32.0    pyhd8ed1ab_0  conda-forge         
breathe                       4.33.0    pyhd8ed1ab_0  conda-forge

In our `environment.yml` file for numpy-dev(The conda environment on which the gitpod loads on) it only mentions `breathe` as a dependency. So I suppose you are correct in assuming it is installing the latest version available i.e `4.33.0`. But what are the possible fixes that we could employ?

Fix the breathe version to an older working one maybe?

**Comment by rossbar** [comment]
Instead of pinning to an old version, I'd advocate for block-listing the one version known not to work, i.e. `breathe != 4.33.0` (assuming this is valid syntax for the environments file)

**Comment by bhavukkalra** [comment]
I was trying to read up on if this could be done I found 3 sources.
1) [Creating Environment from .yml file](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)
2) [Package match specification](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#package-match-specifications)
3) [PEP 440](https://peps.python.org/pep-0440/)

The above mentioned suggestion I did tried. Tried 2 ways but both didn't worked
1) `breathe!=4.33.0` => Gitpod still picks up `4.33.0` 
link - [Branch 1](https://github.com/bhavukkalra/numpy/tree/fix-gitpodFailingBuild)
2) `breathe!= 4.33.0` =>Gitpod still picks up `4.33.0` 
link - [Branch 2](https://github.com/bhavukkalra/numpy/tree/fix-gitpodBuildFail)

**Comment by bhavukkalra** [comment]
Point from the meet
1) Check on two different machines for its working command `conda install -c conda-forge breathe==4.31.0`. If it works then maybe we can merge.
2) Open/Update with an issue in the `breathe` Repo to update the Conda Repo with the `4.33.1` version.
3) I am also trying to setup gitpod on my local fork to see if that brings a change with the use of `!` in `environment.xml`

**Comment by rossbar** [comment]
Thanks for the summary @bhavukkalra 

I was able to verify that adding `breathe!=4.33.0` to environments.yml works as expected (at least locally). Do you want to go ahead and add that pin to #21250?

**Comment by bhavukkalra** [comment]
Sure @rossbar . Just one clarifying question before I add do that. The PR mentioned above was for a different purpose(mainly keeping the restructuredText VS code extension up to date). It was in the process of working on that PR that I found this issue,
Do let me know if I should just add this update commit in the previous PR or create a new one.

**Comment by rossbar** [comment]
> Just one clarifying question before I do that. The PR mentioned above was for a different purpose(mainly keeping the restructuredText VS code extension up to date). It was in the process of working on that PR that I found this issue,
Do let me know if I should just add this update commit in the previous PR or create a new one.

Good question! Generally I agree that it's good to keep PRs as focused as possible, which makes them much easier to review. In this case, all of the changes are related to fixing gitpod, so it doesn't hurt to have them all in the same place.

**Comment by bhavukkalra** [comment]
Update - With the merging of the PR #21250 This issue is now resolved and now the docs are getting generated successfully. So, Closing this issue.

But Issue with Live Preview `pip install esbonio` still remains. (Keeping that Open)
