### ISSUE TITLE
DOC: Sidebars are not pinned on the numpy docs site 

### ISSUE THREAD

**Issue by asmeurer** [numpy/numpy#21264]
### Issue with current documentation:

At https://numpy.org/doc/stable/reference/arrays.indexing.html, for instance, if you scroll down on the page, the sidebars scroll with the content, and stop being visible. This particularly defeats the purpose of the right sidebar, which is supposed to show you which section you are viewing. 

Compare this to the NEPs documentation, e.g., https://numpy.org/neps/nep-0021-advanced-indexing.html, where the sidebars are pinned to the page. 

It's not clear to me why this happens. I think both documents are using the pydata Sphinx theme

**Comment by melissawm** [comment]
@zainasir I wouldn't mind that change, it looks like all content is still visible. If you submit a PR we can test with the other pages and see if the behavior is reasonable. Thanks for looking into this!

**Comment by zainasir** [comment]
Great! I'd be more than happy to do it. Although I can't find the html and css files for the docs. Could you please point me in the right direction.

**Comment by asmeurer** [comment]
But the question is why it does this at all, when other projects that use the pydata sphinx theme do not. There may be a bug in the pydata sphinx theme. Perhaps it has to do with this option, which numpy uses https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#remove-reveal-buttons-for-sidebar-items

**Comment by bhavukkalra** [comment]
I skimmed through this and found that, setting
 "collapse_navigation": True => To False increases the Doc build time to unbearable amount. Like 7X.

Reference -  https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#remove-reveal-buttons-for-sidebar-items

But also it doesn't address the issue as the output is still the same.
**Any other Ideas that we can try?**

I am hoping to learn more about sphinx though this.

**Comment by rossbar** [comment]
I think this has to do with the theme configuration - perhaps from conflicting bootstrap CSS loaded by `sphinx-panels` and the `pydata-sphinx-theme` (see 42c3126).

This appears to be fixed by #21491. Here's a link to a page in the [doc preview](https://output.circle-artifacts.com/output/job/506fce9d-df71-4616-942c-85974d9a7466/artifacts/0/doc/build/html/reference/routines.array-creation.html) for verification: when I scroll down on this page, both the left and right sidebars remain visible as the content in the central part of the page scrolls down.

**Comment by bhavukkalra** [comment]
The page seems much more cleaner in the preview! I didn't knew that there was already PR addressing this Issue. If it gets merged, then after testing this page under consideration. we can close this issue as well.
