### ISSUE TITLE
DOC: Clarify relationship between row_stack and vstack

### ISSUE THREAD

**Issue by jxu** [numpy/numpy#21278]
### Issue with current documentation:

[Current documentation for row_stack](https://numpy.org/doc/stable/reference/generated/numpy.row_stack.html) does not indicate if it is equivalent to vstack, while the code examples and source link directly to vstack. 

column_stack docs indicate it functions like hstack, except it converts 1D input vectors into 2D "column vectors". 

### Idea or request for content:

Clarify relationship between row_stack and vstack, including if they are the same function or not.

**Comment by Ishticode** [comment]
Was there any update on this?

**Comment by eric-wieser** [comment]
This looks like a missing (or disabled) Sphinx feature; it should point out that this is an alias for another name.

The two functions are not only equivalent, but literally the same function object:

https://github.com/numpy/numpy/blob/fbe1b65f5f66ca5a416b23194577a1ed5a4cf1bd/numpy/lib/shape_base.py#L605

**Comment by rossbar** [comment]
Beat me to it - just opened a PR to get this one off the docket
