### ISSUE TITLE
BUG: memory leak when casting SQLAlchemy results to numpy array

### ISSUE THREAD

**Issue by robochat** [numpy/numpy#21271]
### Describe the issue:

I have a long running process that periodically requests data from a postgresql database using sqlalchemy and converts to the results to a numpy array for analysis. I see the process leaking memory on each coercion of the results to a numpy array. The sqlalchemy results are a list of sqlalchemy.engine.row.LegacyRow objects. The issue is the following line in the code below:

    data = np.array(rows) 

In my real process after a couple of days it can be using 9 GB of RAM and after a week it crashes the server. The previous version (python2.7) used less than 200MB even after running for weeks.

While creating the test case, I found that the same issue occurs with a sqlite in memory database. I also saw the same issue on my laptop and my server (both using sqlalchemy v.1.4.32 and v1.4.23). 

I posted this [issue](https://github.com/sqlalchemy/sqlalchemy/issues/7875) to the sqlalchemy github issues and it was confirmed to only occur when using the C-extensions version of sqlalchemy and occurred as far back as v1.3.

### Reproduce the code example:

```python
import sqlalchemy as sql
import numpy as np
import time

dburl = 'sqlite://'
engine = sql.create_engine(dburl, echo=False)

meta = sql.MetaData()

tbl = sql.Table('test_table',meta,
            sql.Column('a',sql.Integer,primary_key=True),
            sql.Column('b',sql.Integer),
            )

meta.create_all(engine)

#fill table
with engine.connect() as conn:
    conn.execute(tbl.insert(),
                 [{'b': i} for i in range(200)]
                 )

#test

while True:
    with engine.connect() as conn:
        query = sql.text("SELECT a, b FROM test_table ORDER BY a LIMIT 200")
        results = conn.execute(query)
        rows = results.fetchall()
        data = np.array(rows)
        
        #fixes that didn't work
        del rows
        results.close()
        del data

        time.sleep(0.1)
```

### Error message:

```shell
Resident memory usage is up to 358MB in just a few minutes and there's no sign of stabilisation.
after a couple of minutes

PID    USER  PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                              
1952762 aaa  20   0  762204 186264  16188 S   5.7   0.9   0:09.77 python3

a bit later

PID    USER  PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND 
1952762 aaa  20   0  934200 358092  16188 S   5.6   1.8   0:21.20 python3
```

### NumPy/Python version information:

Numpy: 1.22.3 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
OS: Linux (CentOS)
Python: 3.6.8
SQLAlchemy: 1.4.32, 1.4.23
Database: Postgresql (v12.9 64bit)
DBAPI: psycopg2

**Comment by seberg** [comment]
I can reproduce it, what is leaked seems to a string created in sqlalchemy:
```
==53451==    by 0x5D4C06: PyUnicode_AsASCIIString (unicodeobject.c:7375)
==53451==    by 0x563C949A: ??? (in /usr/lib/python3/dist-packages/sqlalchemy/cresultproxy.cpython-39-x86_64-linux-gnu.so)
```

Which already points to an idea:  A common bug that I fixed early on when starting in NumPy, was that we got the reference counting for error strings wrong :).

For an unknown object/type, NumPy will check for a few special attributes, like `__array__`, `__array_interface__` to convert it to an array.  This is what happens.  If you just get rows up there, `rows[0]` will be a special object, this will create the same leak:

```python
while True:
    try:
        rows[0].__array__
    except AttributeError:
        pass
```

So I am very sure this is not a NumPy bug, but a bug in that `AttributeError`.  It probably builds an error message, and the forgets to `DECREF` it.  But modern Python is much better, using `PyErr_Format()` will be much more convenient and solve the issue :).
(Not that I checked the code...)

**Comment by seberg** [comment]
Oh, but even if it was not a NumPy bug, thanks for pushing it "upstream" when not making progress "downstream"!

**Comment by robochat** [comment]
Thanks for looking over the issue.

**Comment by mattip** [comment]
Summarizing the discussion on the sqlalchemy side: they are [moving to cython](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#c-extensions-now-ported-to-cython) code for v2 (the report here is about v1.x) and there the leak does not reproduce. They are not likely to investigate this more.
