### ISSUE TITLE
BUG: TypeError: _percentile_dispatcher() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by wuzijianns** [numpy/numpy#21283]
### Describe the issue:

The np.percentile function does not recognize the "method" argument.

### Reproduce the code example:

```python
import numpy as np
arrayNum = np.array([1,1,1,4])
np.percentile(arrayNum, 75, method='linear')
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 4, in percentile
TypeError: _percentile_dispatcher() got an unexpected keyword argument 'method'
```

### NumPy/Python version information:

numpy: anaconda '1.20.3'

**Comment by BvB93** [comment]
That would make sense considering your numpy version, the keyword argument was renamed from `interpolation` to `method` back in NumPy 1.22. Per the [interpolation docs](https://numpy.org/doc/stable/reference/generated/numpy.percentile.html):
> _Changed in version 1.22.0_: This argument was previously called “interpolation” and only offered the “linear” default and last four options.
