### ISSUE TITLE
BUG: Legacy-Install-Failure when pip installing NumPy dependent Python Package

### ISSUE THREAD

**Issue by JaiWillems** [numpy/numpy#21281]
### Describe the issue:

I am developing a Python package with NumPy as a dependency and currently have it published to TestPyPI [here](https://test.pypi.org/project/polare/).

Using a fresh virtual environment (i.e. NumPy not currently installed) with Python 3.8.13, I pip install the package using `pip install -i https://test.pypi.org/simple/ polare`. This produces a legacy-install-failure error when the install process attempts to build the NumPy wheel. The output given in the GitHub Gist, [here](https://gist.github.com/JaiWillems/69bb7cc886f79e4109ea5b458463ab4a), which notes that the error is associated with the NumPy package and not pip itself. I also ensured pip was updated to the most recent version (22.0.4).

The error can be worked around by downloading NumPy first (i.e. using `pip install numpy`) before attempting to install the library or by downloading the wheel binary directly and manually installing (i.e. using `pip install polare-0.1.0-py3-none-any.whl`). Any assistance in a solution or in identifying the cause is greatly appreciated.

### Reproduce the code example:

```python
conda create -n test_polare python=3.8
pip install -i https://test.pypi.org/simple/ polare
```

### NumPy/Python version information:

Python 3.8.13; attempting install of NumPy 1.22.3.

**Comment by seberg** [comment]
I think the reason is just that on the test server the only NumPy version available is `1.9.x`.  That shouldn't even try to install on Python 3.8 probably...

**Comment by JaiWillems** [comment]
I published to PyPI and the install problem went away. Thank you!

**Comment by DanielSank** [comment]
I just ran into this same problem. What should I do or where should I report so that the underlying issue gets fixed?

**Comment by JaiWillems** [comment]
It sounds like a new release on the TestPyPI server would fix it, although I am not sure who to talk to about doing that.

**Comment by mattip** [comment]
Mirroring packages to both locations is unsustainable. Today it is NumPy, tomorrow it will be something else. I think you can add [`--extra-index https://pypi.org/simple`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url) to add the normal pypi.org index.

**Comment by sonjaoffwood** [comment]
I ran into the same issue today - is there any update on a fix for this?

**Comment by mattip** [comment]
Did you try the solution I suggested?

**Comment by sonjaoffwood** [comment]
@mattip Apologies I wasn't fully clear in my response (slightly new to this). So I get the same error, but my package failing with the issue is not on Pypi, so I get exactly the same error, but my build fails on Travis with that issue. Does that make sense?

**Comment by mattip** [comment]
The original problem was that the reporter tried `pip install -i https://some.index.org/simple/ mypackage`, and there was an older version of NumPy on https://some.index.org/simple when the reporter wanted a newer version. I suggested using `pip install -i https://some.index.org/simple/ --extra-index https://pypi.org/simple mypackage`

Does that help your use case? If not please open a new issue, and clearly describe what you want to happen, what is happening instead, and what you are doing to make the wrong thing happen, including snippets of code and error messages (please copy-paste text, not images).

**Comment by ThadeuLuz** [comment]
@mattip suggestion worked for me. Thanks
