### ISSUE TITLE
No module named numpy even after being installed 

### ISSUE THREAD

**Issue by sammy101354** [numpy/numpy#21282]
So I am trying to import numpy. My python is 3.5.2 shell. Working directory is `c:\users\sam\desktop`
 I have exhausted a lot of options 
When I’m in desktop directory, I’ve done `pip show numpy `
It shows
```
name: numpy
Version : 1.21.4
```
I have done `pip3 install numpy` and `pip install numpy `and both shows 
`requirement already satisfied: numpy in c:\users\sam\appdata\local\programs\python\python39\lib\site-package (1.21.4) `

I have done `import sys`; `print(sys.executable)`
It shows `c:\users\sam\appdata\local\programs\python\python35-32\pythonw.exe`

I have done `python -mpip install numpy `
It shows `c:\users\sam\appdata\local\programs\python\python39\lib\site-package (1.21.4)`

I don’t have other versions of python or any virtual environments installed

I am relatively new in python so any help is appreciated. Thank you

**Comment by cookie2004** [comment]
Hi sammy!
What IDE are you using? 

-Erik

**Comment by sammy101354** [comment]
> using?

Hello, I’m using python IDLE

**Comment by sammy101354** [comment]
> Hi sammy! What IDE are you using?
> 
> -Erik

hello, I’m using Python IDLE

**Comment by cookie2004** [comment]
Go to your IDLE shell and enter:

`help('modules')`

Do you see numpy in there?

**Comment by sammy101354** [comment]
> Go to your IDLE shell and enter:
> 
> `help('modules')`
> 
> Do you see numpy in there?

I did. Numpy isn’t here in the list of modules. How do I solve this problem ?

**Comment by cookie2004** [comment]
Run these commands in this order

`import sys`
`import subprocess`
`sub = subprocess.check_call([sys.executable, '-m', 'pip', 'install','numpy'])`

Now try:
`import numpy`

Any error this time?

**Comment by cookie2004** [comment]
*Run those lines in your Python IDLE shell

**Comment by seberg** [comment]
@sammy101354 you mentioned `python 3.5` which is very old, but the traceback point to:
```
c:\users\sam\appdata\local\programs\python\python39
```
which looks like a Python 3.9.  Our [help site](https://numpy.org/devdocs/user/troubleshooting-importerror.html) has some tips on how to debug environment issues such as this, you probably have some `PYTHONPATH` problems.  Or, using Python 3.5 is just an accident anyway?
(Yes, the site mentions a different error, but it should offer some hints as to your problems.)

**Comment by sammy101354** [comment]
> Run these commands in this order
> 
> `import sys` `import subprocess` `sub = subprocess.check_call([sys.executable, '-m', 'pip', 'install','numpy'])`
> 
> Now try: `import numpy`
> 
> Any error this time?

So I ran these commands in the shell. 
it shows 
```
File “c:\users\sam\appdata\local\programs\python\python35-32\lib\subprocess.py”, line 581, 
in check_call raised CalledProcessError(retcode, cmd)
Subprocess.CalledProcessError: Command returned non-zero exit status 1
```

**Comment by sammy101354** [comment]
> 



> @sammy101354 you mentioned `python 3.5` which is very old, but the traceback point to:
> 
> ```
> c:\users\sam\appdata\local\programs\python\python39
> ```
> 
> which looks like a Python 3.9. Our [help site](https://numpy.org/devdocs/user/troubleshooting-importerror.html) has some tips on how to debug environment issues such as this, you probably have some `PYTHONPATH` problems. Or, using Python 3.5 is just an accident anyway? (Yes, the site mentions a different error, but it should offer some hints as to your problems.)

I looked at the link you mentioned. I put this code 
```
import os
print("PYTHONPATH:", os.environ.get('PYTHONPATH'))
print("PATH:", os.environ.get('PATH'))
```

for PYTHONPATH it shows none 
For PATH it shows lots of files paths

**Comment by seberg** [comment]
If `PYTHONPATH` is truly empty, I am not quite sure why you would be picking up a NumPy from:
```
c:\users\sam\appdata\local\programs\python\python39\lib\site-package
```
Which looks like you got a Python 3.9 and the Python 3.5 searches its packages.  NumPy 1.21.4 cannot even be installed on Python 3.5 (it is not compatible at all)!
You must have (or have had) a Python 3.9 installation.  And for some reason that gets picked up or was not deleted fully.  But without `PYTHONPATH`, I am not sure where you should look to find out why that Python finds that.

**Comment by sammy101354** [comment]
> If `PYTHONPATH` is truly empty, I am not quite sure why you would be picking up a NumPy from:
> 
> ```
> c:\users\sam\appdata\local\programs\python\python39\lib\site-package
> ```
> 
> Which looks like you got a Python 3.9 and the Python 3.5 searches its packages. NumPy 1.21.4 cannot even be installed on Python 3.5 (it is not compatible at all)! You must have (or have had) a Python 3.9 installation. And for some reason that gets picked up or was not deleted fully. But without `PYTHONPATH`, I am not sure where you should look to find out why that Python finds that.

So I was looking into it. Yes I had a previous 3.9 version but it wasn’t deleted fully. So I uninstalled the whole thing and installed it again. Now import numpy seems to be working . Thank you very much

**Comment by seberg** [comment]
OK, glad you figured it out.  I am going to close the issue.

I still wonder if there may be some other path/python-path related issues, but you probably don't have to worry for now and hopefully you will have an idea where to look if you run into similar issues again!

**Comment by sammy101354** [comment]
Thank you to both of you. I leaned a lot. Sincerely
