### ISSUE TITLE
BUG: numpy.load mmap mode memory leak

### ISSUE THREAD

**Issue by CamilleChiquet** [numpy/numpy#21292]
### Describe the issue:

Hi.
Here are the steps to reproduce the memory leak I experienced:

- create and save a numpy file to the disk using **numpy.save** function.
- load the same file with **numpy.load** function, but with **mmap_mode='r'**
- create a loop to iterate over the loaded array and convert the data inside this loop into another type using **astype** function
- see your memory increase
- delete the loaded file
- see your memory back to normal level

See my code example to reproduce the problem.
I make a first loop that iterates over the data, without any type conversion: no memory increase, which is the expected behavior because, as I understand numpy and mmap, nothing is loaded into memory except when accessing a portion of the array.
The second loop iterates over the data, but each time a type conversion is made, the memory usage increases, dispite the **gc.collect** call in case unused variables would not have been released from memory.
After that, I delete the array and can see the memory beeing released.

Am I missing some normal python behavior or is there really a memory leak somewhere ?

### Reproduce the code example:

```python
import gc
import os

import numpy as np
import psutil

process = psutil.Process(os.getpid())

# Create a numpy file with random data
timesteps = 10_000
N = 10_000
file_path = "test.npy"
random_data = np.empty((timesteps, N), dtype=np.float64)
np.save(file_path, random_data)

del random_data
gc.collect()

# Load file in mmap mode
file_data = np.load(file_path, mmap_mode='r')

# First loop iterate over all timesteps
print(f"\nMemory usage before first loop: {process.memory_info().rss / 1024 ** 3} Go")
for i, array in enumerate(file_data):
    if i % 1_000 == 0:
        gc.collect()
        # You should be able to see constant memory usage
        print(f"Memory usage: {process.memory_info().rss / 1024 ** 3} Go")

# Second loop iterate over timesteps dimension AND converts the data from float64 to float32
print(f"\nMemory usage before second loop: {process.memory_info().rss / 1024 ** 3} Go")
for i, array in enumerate(file_data):
    array = array.astype(np.float32)
    if i % 1_000 == 0:
        gc.collect()
        # You will see memory usage increase
        print(f"Memory usage: {process.memory_info().rss / 1024 ** 3} Go")

del file_data
gc.collect()
print(f"Memory usage after del: {process.memory_info().rss / 1024 ** 3} Go")
```

### NumPy/Python version information:

1.22.3 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]

**Comment by seberg** [comment]
This looks very much normal to me.  If you memory map the file, it is not loaded into memory by the kernel (only virtual memory is given to the process).
So actual memory use increases when reading more.  Unless usage keeps increasing if you repeat the whole thing, this is simply how the kernel/computer does memory management.

Further, just because you free again, it would even be normal to not give the memory back to the system in some cases, so that it can be reused quicker later.

**Comment by CamilleChiquet** [comment]
Ok understand better now.
What I didn't know at first was that until this line
```python
    array = array.astype(np.float32)
```
no data is loaded.
The data is loaded only when you access it and/or do some processing on it.
So I misinterpreted the results.

Is there a way to "unload" data, in order to avoid keeping everything as we read more and more of the file ?

**Comment by Semnodime** [comment]
numpy apparently does not reuse the pages even when OOM due to page table entries filling up RAM.
