### ISSUE TITLE
BUG: Error when importing numpy on an AWS Lambda function

### ISSUE THREAD

**Issue by mtfbs** [numpy/numpy#21312]
### Describe the issue:

I have numpy along with other libraries on an AWS EFS directory that i append to the path on a lambda function (so it can use the dependencies) that imports numpy (please see screenshot and code below)

![image](https://user-images.githubusercontent.com/43099047/162269835-7dc2e969-879a-4c32-aa10-a25a1311cb34.png)

When I import numpy, i get an error.
Following the troubleshooting hints did not solve the error.

### Reproduce the code example:

```python
import sys, os, json
sys.path.append("/mnt/access")

import numpy

def lambda_handler(event, context):

    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }
```

### Error message:

```shell
Test Event Name
t

Response
{
  "errorMessage": "Unable to import module 'lambda_function': \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.7 from \"/var/lang/bin/python3.7\"\n  * The NumPy version is: \"1.22.3\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: No module named 'numpy.core._multiarray_umath'\n",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}

Function Logs
START RequestId: 0d5ec298-258c-430e-a8ec-e7552ede9eee Version: $LATEST
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
* The Python version is: Python3.7 from "/var/lang/bin/python3.7"
* The NumPy version is: "1.22.3"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
END RequestId:xxxxxxx
REPORT RequestId: xxxxxxxxxx	Duration: 1.70 ms	Billed Duration: 2 ms	Memory Size: 1024 MB	Max Memory Used: 47 MB	Init Duration: 1770.46 ms

Request ID
xxxxxxxxxx
```

### NumPy/Python version information:

Python 3.7
NumPy 1.22.3

**Comment by parthNJ** [comment]
Any solution to this? Just ran into this issue when trying to import langchain which has a numpy dependency on aws lambda.

**Comment by Santiagowwi** [comment]
@parthNJ 
I have the same problem, could you solve it?

**Comment by dsatizabal** [comment]
> I fixed it by removing any numpy files I had on the EFS or that was acessible to the lambda function, until it said "no module named 'numpy'", and them I added the following AWS lambda layer: ![image](https://user-images.githubusercontent.com/43099047/162440571-dfad46f1-c33b-44c5-8ac2-4aba2f714c3a.png)

Cannot see that AWS provided layer :/

**Comment by shawnesquivel** [comment]
> > I fixed it by removing any numpy files I had on the EFS or that was acessible to the lambda function, until it said "no module named 'numpy'", and them I added the following AWS lambda layer: ![image](https://user-images.githubusercontent.com/43099047/162440571-dfad46f1-c33b-44c5-8ac2-4aba2f714c3a.png)
> 
> Cannot see that AWS provided layer :/

same my form looks completely different. anyone have updates on how they solved this?

I tried adding numpy to my requirements.txt and that didn't seem to work.

my AWS layer form looks like this:

<img width="685" alt="image" src="https://github.com/numpy/numpy/assets/94336773/26c5a02b-7447-47e7-81a0-3bc87222b041">

**Comment by shawnesquivel** [comment]
> I fixed it by removing any numpy files I had on the EFS or that was acessible to the lambda function, until it said "no module named 'numpy'", and them I added the following AWS lambda layer: ![image](https://user-images.githubusercontent.com/43099047/162440571-dfad46f1-c33b-44c5-8ac2-4aba2f714c3a.png)



Just to follow up on this, I was able to see this layer by going to Lambda/Functions/LambdaFunction/Code/Layers

But I get this message.

Is it because my dependencies are too big? (I'm using LangChain)

<img width="658" alt="image" src="https://github.com/numpy/numpy/assets/94336773/d7a49419-1cc1-4e2a-8d92-1bcaedc950f8">

**Comment by Santiagowwi** [comment]
@shawnesquivel 
I solved it, but with a docker file, its best way to solve it.

**Comment by shawnesquivel** [comment]
@Santiagowwi thanks for the response.

im a little confused on the steps - did you docker then upload to lambda? some resources are telling me that EC2 might be a better option for the docker images.

for context, im trying to invoke some python scripts, so no preference on EC2/Lambda.

**Comment by Santiagowwi** [comment]
@shawnesquivel 

It doesn't necessarily have to be an EC2 instance, the dockerized file can also work inside a lambda, you can see the configuration of my whole project, I dockerized it and then uploaded it to ECR and then put it in the lambda with the simple configuration.

https://github.com/Santiagowwi/Back-End-DataChimp/blob/main/Dockerfile

I also want to mention that the problem of uploading langchain as a layer to lambda makes me have problems with the other libraries that came from lambda, I did not find which exactly was causing the problem or how to solve it with the layers of lambda, my only solution was to make my application a container image and use it in a lambda so that whenever the api is used it is invoked.

**Comment by shawnesquivel** [comment]
@Santiagowwi 

awesome! thanks for sharing, I'm gonna try to package my code into a docker container, upload to ECR, then access it from the Lambda function as you had some success with it.

and yes, that's exactly how I found this issue, I had some NumPy errors which is a dependency of the LangChain library 😅😅 big headache

**Comment by shawnesquivel** [comment]
Thanks @Santiagowwi !! Your suggestion worked, thanks so much for your help.

Just for everyone else who wants to replicate:
- dockerize your application and test it locally
- upload to Elastic Container Registry
- create lambda function from the image in the ECR 
- test it again

tutorials I used:
- ECR https://youtu.be/t0TXPCwcg3I?t=276
- how to dockerize a python script https://www.youtube.com/watch?v=0TFWtfFY87U&t=832s
- dockerfile for langchain from @Santiagowwi https://github.com/Santiagowwi/Back-End-DataChimp/blob/main/Dockerfile

**Comment by Petya533665** [comment]
The easiest way is to do the following:

`docker pull public.ecr.aws/sam/build-python3.10:1.84.0-20230517004040
docker run -it -v $(pwd):/var/task public.ecr.aws/sam/build-python3.10:1.84.0-20230517004040
pip install langchain langchain_openai openai pinecone colorama xmltodict -t ./python
zip -r layer.zip ./python`
