### ISSUE TITLE
numpy linalg eig gives different results for same input vector on different systems

### ISSUE THREAD

**Issue by aznt00th** [numpy/numpy#21313]
`import numpy as np
x = np.array([[2310.,  150., 2742.],
 [ 150.,   15.,  177.],
 [2742.,  177., 3255.]])

print(np.linalg.eig(x))`

Running the above code on two different systems gives these results:
array([ 5.57459476e+03, -1.59838564e-13,  5.40523595e+00]), array([[ 0.64371971,  0.76200076, -0.07056749],
       [ 0.04169513, -0.12700013, -0.99102598],
       [ 0.76412463, -0.63500064,  0.1135242 ]])

array([ 5.57459476e+03 -2.22392971e-13  5.40523595e+00]), array([[-0.64371971 -0.76200076 -0.07056749],
 [-0.04169513  0.12700013 -0.99102598],
 [-0.76412463  0.63500064  0.1135242 ]])

First environment:
numpy                     1.20.3           py39ha4e8547_0
numpy-base                1.20.3           py39hc2deb75_0
python                    3.9.7                h6244533_1
Windows 10.0.19042 Build 19042
Processor: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz

Second environment
numpy                     1.20.3           py39ha4e8547_0  
numpy-base                1.20.3           py39hc2deb75_0
python                    3.9.7                h6244533_1
Windows 10.0.19042 Build 19042
Processor: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00Ghz, 2995Mhz, 4 Core(s), 8 Logical Processors

**Comment by aznt00th** [comment]
I understand that eigenvalues and eigenvectors are non-unique, but I would expect the call to be deterministic across different systems.

**Comment by mattip** [comment]
That is why numpy has [is_close](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html) and python has [isclose](https://docs.python.org/3/library/math.html#math.isclose). Different libraries handle floats in different ways, even the same CPU can be convinced to return different floating point values for the same calculation by setting some flags to trade off speed for accuracy.

**Comment by aznt00th** [comment]
Making sure I understand you correctly, you're saying the flipping of the positive/negative signs on the eigenvectors is due to floating point errors?

**Comment by mattip** [comment]
yes, your matrix is very close to singular.

**Comment by robertmkjeffrey** [comment]
Thanks @mattip - I thought it might be a floating point error but I didn't even consider near-singularity would be an issue!

We'll be more aware of this in future.

**Comment by melissawm** [comment]
Closing this as it looks there's not much to do - please reopen otherwise.
