### ISSUE TITLE
DOC: negative numbers when squaring array elements

### ISSUE THREAD

**Issue by Socweb** [numpy/numpy#21326]
### Describe the issue:

Initially, I found this error when squaring the difference between vectors. Next, I just tested the np.power function of the library, which shows the error. There is no such error in the original python. Version is 1.20.3 (Kaggle).

### Reproduce the code example:

```python
y = np.array([243, 537824, 39135393, 777600000, 8587340257,53782400000, 247609900000,
1016255020032, 3251888153568, 9738138110976])
x = np.array([1024, 1048576, 60466176, 1073741824, 10000000000, 61917364224, 289254654976, 1099511627776, 3570467226624, 10240000000000])

print((y-x)**2)
#array([              609961,         260867605504,      455002303393089,
          87699979922046976,  1995607549492826049, -7609333369078284288,
         291674082378908672, -4313038676510638080, -1360104329767812096,
       -6487927692526092288])

print(np.power(53782400000-61917364224, 2)) # -7609333369078284288
print((53782400000-61917364224)**2) # 66177642925759922176
```

### NumPy/Python version information:

1.20.3 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0]

**Comment by charris** [comment]
NumPy integer arithmetic is modular. Use floating point instead.

**Comment by melissawm** [comment]
Should we add an example of that kind of overflow [to the docs](https://numpy.org/doc/stable/user/basics.types.html#overflow-errors)?

**Comment by melissawm** [comment]
@Socweb would you be interested in submitting a pull request adding this example to the documentation? You'd ideally add this to [this section on Overflow errors](https://github.com/numpy/numpy/blob/main/doc/source/user/basics.types.rst#overflow-errors).

**Comment by mdhaber** [comment]
@rossbar @melissawm how about just changing the example there to:
```
>>> np.power(100, 9, dtype=np.int64)
1000000000000000000
>>> np.power(100, 9, dtype=np.int32)
-1486618624
```
Then it serves the original purpose (integer interflow can produce unexpected results) and this purpose (it can manifest as a negative result).
