### ISSUE TITLE
ENH: API to check whether Hugepages are enabled

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#21328]
### Proposed new feature or change:

It would be helpful to have a user facing API to be able to check whether Hugepages are enabled or not. This would help when trying to diagnose performance issues users may be seeing.

**Comment by seberg** [comment]
Just to note that a lot of system nowadays just enable hugepages always.  So you would need the ` core.multiarray._set_madvise_hugepage` value and the kernel one.
But really, the NumPy one is only set to `False` on old kernels which had a very slow hugepages (something about super slow defragmentation or so).

On any non ancient kernel (versions `>= 4.6`) it really depends only on the kernel defaults.

**Comment by jakirkham** [comment]
Tried adding a private API based on the discussion here in PR ( https://github.com/numpy/numpy/pull/21498 ).
