### ISSUE TITLE
DOC: Add "Building the Gitpod Instance locally" steps

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy#21344]
### Issue with current documentation:

This issue is created in response to the comment made by @melissawm to also add the Steps required to build the Gitpod Instance locally (issue #21263 )

Making a new issue to track the changes. Will make a new PR for closing this issue.

Target Page - [Development_Gitpod](https://numpy.org/devdocs/dev/development_gitpod.html)

**Comment by rgommers** [comment]
We decided to remove Gitpod support (see [this mailing list thread](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/SSPI7HVL2PLWPFL42T6UNR2ENARE5A5E/)), so I'll close this issue. Thanks @bhavukkalra
