### ISSUE TITLE
ENH: use threadpoolctl to show runtime acceleration framework in show_config()

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#21340]
We should be promoting [threadpoolctl](https://pypi.org/project/threadpoolctl/) as a helper library to show what runtime dependencies are in use. The current `show_config()` shows the build-time configuration of the various acceleration frameworks, but I have never found that to be very helpful. We could instead use threadpoolctl to show what is currently in use. If threadpoolctl is not installed, we could display the help for `show_config` with directions on installing it.

This would help us debug user issues, as we could request the output in the issue template.

**Comment by seberg** [comment]
Yeah, I guess we could just vendor it.  Do you want to just use threadpoolctl as a way to guess the setup more correctly, or also expose the configuration of the number of threads?
The latter could possibly use some thought, but the former seems worthwhile thing to make fetching relevant info easier.

**Comment by mattip** [comment]
I would prefer not to vendor it, they seem to be releasing more frequently than NumPy. I was thinking of conditionally importing it in `show_config`, and if it fails print a helpful message. My first concern is to get information about the setup, but if we get thread info too that would be great.
