### ISSUE TITLE
BUG: conda install numpy can't found

### ISSUE THREAD

**Issue by CarlDegio** [numpy/numpy#21353]
### Describe the issue:

I use conda to install numpy, just like [https://numpy.org/install/](https://numpy.org/install/).

But when I import it in this env, it raise `ModuleNotFoundError: No module named 'numpy'`.

I even reinstall my conda, things doesn't get better. Use pip to install numpy could solve this problem, but why conda can't?

### Reproduce the code example:

```python
import numpy
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

### NumPy/Python version information:

python 3.8.13
numpy 1.22.3(same for conda or pip)

**Comment by mattip** [comment]
Could you provide the exact commands you used to install numpy, starting with `conda create ...`?

**Comment by CarlDegio** [comment]
conda create -n normal python=3.8
conda activate normal
conda config --env --add channels conda-forge
conda install numpy
(And, numpy not in base env)

**Comment by mattip** [comment]
That works for me on Ubuntu 20.04 on x86_64. What does `python -c "import platform as pt; print(pt.uname()` show?

**Comment by CarlDegio** [comment]
I found some other problems (forgot to delete PYTHONHOME variable), and reinstall the anaconda, the env become good after solve these. Thank you. BTW, the way I install numpy also valid for win10

**Comment by mattip** [comment]
Cool, glad you solved it. I will close this then.
