### ISSUE TITLE
np.arange() return array consists of "stop" val in case of np.arange(start=0.69,stop=0.99,step=0.01)

### ISSUE THREAD

**Issue by harshal306** [numpy/numpy#21371]
### Describe the issue:

Usually, when np.arange() is called it returns the numpy array consisting of the start value and its progressive step size up to the stop value.
It can be noted that in the **return numpy.ndarray, stop value is not included.**

### For example:
```py
import numpy as np
a = np.arange(start=0.1,stop=0.2,step=0.02)
```
### It returns
```py
array([0.1 , 0.12, 0.14, 0.16, 0.18])
```
**Please note that 0.2 is not included.**

### However, let's take another example:
```py
a = np.arange(start=0.69,stop=0.99,step=0.01)
```
Ideally, it should not return the array consisting of value 0.99, it should stop at 0.98
but in real it gives the output mentioned below.
```py
array([0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79,
       0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ,
       0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])
```

I wonder **why 0.99** is included in the return array.

### Reproduce the code example:

```python
import numpy as np
a = np.arange(start=0.69,stop=0.99,step=0.01)
```

### Error message:

```shell
array([0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79,
       0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ,
       0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

Ideally, 0.99 should be part of this return numpy array.
```

### NumPy/Python version information:

```py
import numpy as np
np.__version__
```
Version
```py
'1.20.3'
```
Python-version: 3.8.12

**Comment by mattip** [comment]
This is a well known issue/feature when using `arange` with a non-integer `step`, and is described in the [documentation](https://numpy.org/devdocs/reference/generated/numpy.arange.html) and in numerous other issues: #21208, #21134, #20832, #19989, #19249, #18776, to mention just the ones in the past 12 months. Perhaps we should warn whenever `arange` is called with a non-integer `step` argument.

**Comment by harshal306** [comment]
got it thanks.
