### ISSUE TITLE
BUG: getauxval declaration invalid, causes compile issues

### ISSUE THREAD

**Issue by jmgurney** [numpy/numpy#21386]
### Describe the issue:

Trying to install numpy, (main branch) on FreeBSD/aarch64 (aka arm64), using clang, and I get the following compile error:
```
      INFO: cc: numpy/core/src/common/npy_argparse.c                                                                                                                                [133/1808]      INFO: cc: numpy/core/src/common/npy_hashtable.c                                                                                                                                               INFO: cc: numpy/core/src/common/npy_longdouble.c                                                                                                                                              INFO: cc: numpy/core/src/common/ucsnarrow.c                                                                                                                                                   INFO: cc: numpy/core/src/common/ufunc_override.c                                                                                                                                              INFO: cc: numpy/core/src/common/numpyos.c                                                                                                                                                     INFO: cc: build/src.freebsd-14.0-CURRENT-arm64-3.9/numpy/core/src/common/npy_cpu_features.c                                                                                             
      numpy/core/src/common/npy_cpu_features.c.src:586:22: error: static declaration of 'getauxval' follows non-static declaration                                                            
      static unsigned long getauxval(unsigned long k)                                                                                                                                         
                           ^                                                                                                                                                                  
      numpy/core/src/common/npy_cpu_features.c.src:582:37: note: previous declaration is here                                                                                                 
      __attribute__((weak)) unsigned long getauxval(unsigned long); // linker should handle it                                                                                                
                                          ^                                                                                                                                                   
      1 error generated.                                                                                                                                                                      
```

It is very clear that this is the case by code inspection:
https://github.com/numpy/numpy/blob/main/numpy/core/src/common/npy_cpu_features.c.src#L582

### Reproduce the code example:

```python
# I can't install numpy so there is no code to reproduce.
```

### Error message:

```shell
# see above.
```

### NumPy/Python version information:

Main branch as of a few minutes before I filed this issue, the install was attempted via:
```
pip install git+https://github.com/numpy/numpy.git
```

Python version:
```
Python 3.9.12 (main, Mar 27 2022, 01:58:04) 
[Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a on freebsd14
```

FreeBSD version info:
```
FreeBSD generic 14.0-CURRENT FreeBSD 14.0-CURRENT #0 main-n254105-d53927b0bae: Thu Mar 31 09:26:31 UTC 2022     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/arm64.aarch64/sys/GENERIC arm64
```

**Comment by jmgurney** [comment]
Looks like this commit is the problem:
https://github.com/numpy/numpy/commit/c47e9621ebf76f8085ff5ec8b01c07921d14f6a7

Done by @devnexen

**Comment by jmgurney** [comment]
Just for reference, the previous commit works just fine:
```
pip install 'git+https://github.com/numpy/numpy.git@5c7002926ec8ad12785b36024f9da80b7017ad1c#egg=numpy'
```

**Comment by charris** [comment]
Would you like to make a PR?

**Comment by seberg** [comment]
Sounds like the issue is that `getauxval` already exists (presumably correct).  Can we just add a check for that, the code assumes that on `#ifdef __FreeBSD__` it does not exist.

**Comment by jmgurney** [comment]
I'll do a PR if someone tells me what the correct fix is?

Or are you suggesting that I reverse the change that broke things?

**Comment by mattip** [comment]
This came from #18169 which has no comments about the need for this code. Perhaps clang and gcc differ here? In any case, the conservative move would be to fix the current code. It would be nice if @devexen could explain how they tested #18169 and why they needed to add the wrapper around `elf_aux_info`. We don't run FreeBSD in our CI.

**Comment by devnexen** [comment]
> I'll do a PR if someone tells me what the correct fix is?

I might suggest to guard for Linux only the line 582.

**Comment by kevans91** [comment]
> This came from #18169 which has no comments about the need for this code. Perhaps clang and gcc differ here? In any case, the conservative move would be to fix the current code. It would be nice if @devnexen could explain how they tested #18169 and why they needed to add the wrapper around `elf_aux_info`. We don't run FreeBSD in our CI.

FWIW, the wrapper around `elf_aux_info` is pertinent because we (FreeBSD) can't/won't provide a compatible `getauxval()` implementation. Some software (I have no idea the magnitude) assumes the presence means some Linux-specific `AT_*` values are defined. We provide HWCAP/HWCAP2, but beyond that it can get a bit shadier.

re: CI, I don't have time at the moment, but would the numpy project accept the addition of Cirrus CI if a PR comes along that adds it? I think Cirrus is just about the best game in town for FreeBSD runners.
