### ISSUE TITLE
DOC: Scipy links broken with recent documentation versions

### ISSUE THREAD

**Issue by mrtnbrst** [numpy/numpy#21385]
### Issue with current documentation:

Scipy links in the documentation section `See also` are apparently all broken.

The link in the [documentation ](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html) section `See also` that leads to [scipy.linalg.eigh](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eigh.html#scipy.linalg.eigh) has an error in the current version: https://docs.scipy.org/doc/scipy/reference/reference/generated/scipy.linalg.eigh.html#scipy.linalg.eigh.
It contains `/reference` twice.
For this specific documentation page the issue also exists in version [1.21](https://numpy.org/doc/1.21/reference/generated/numpy.linalg.norm.html) but not in version [1.20](https://numpy.org/doc/1.20/reference/generated/numpy.linalg.eigh.html).

The same is true for the scipy link in https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html or https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.polyfit.html?highlight=scipy.interpolate.UnivariateSpline

**Comment by charris** [comment]
I think this is fixed in main. @melissawm Thoughts.

**Comment by melissawm** [comment]
Can confirm this is fixed in the devdocs; see for example https://numpy.org/devdocs/reference/generated/numpy.linalg.norm.html

SciPy had an issue with their docs and the old intersphinx configuration gives us broken links now. Please use the devdocs for now. Thanks!
