### ISSUE TITLE
BUG: assert_allclose() gives int (0) as default value for atol

### ISSUE THREAD

**Issue by phlibi** [numpy/numpy#21398]
### Describe the issue:

`numpy.testing.assert_allclose()` currently has this signature without type hints:

```py
def assert_allclose(actual, desired, rtol=1e-7, atol=0, equal_nan=True,
                    err_msg='', verbose=True):
```
The doc states a floating-point type for `atol`:

>     atol : float, optional
>        Absolute tolerance.

Now, when using a type checker that infers types from the default values if no type hints are available (such as Pylance in VSCode with `"python.analysis.typeCheckingMode": "basic"` in `settings.json`), this causes a type error if a floating-point value is passed for `atol`, since it assumes that `atol` must be an `int`.

The inferred signature of `assert_allclose()` looks like this:
```
(function) assert_allclose: (actual: Unknown, desired: Unknown, rtol: float = 1e-7, atol: int = 0, equal_nan: bool = True, err_msg: str = '', verbose: bool = True) -> None
```

It is absolutely no big deal, but I propose/request to do either of two options:

- Add type annotations for `assert_allclose()` and friends, or
- Change the default value from `0` to `0.0`, making it a float.

### Reproduce the code example:

```python
# Paste into a new file in Visual Studio Code with typeCheckingMode set to "basic".

import numpy as np
a = np.zeros((3,))
np.testing.assert_allclose(a, a, atol=0.1)
```

### Error message:

```shell
Argument of type "float" cannot be assigned to parameter "atol" of type "int" in function "assert_allclose"
  "float" is incompatible with "int"

(This is not a traceback, but the error message of Pylance.)
```

### NumPy/Python version information:

```
1.19.2 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
```

The signature is still the same in [1.22.0](https://github.com/numpy/numpy/blob/v1.22.0/numpy/testing/_private/utils.py#L1476-L1531), however.

**Comment by BvB93** [comment]
Ever since the 1.22 release (xref https://github.com/numpy/numpy/pull/19179) the `numpy.testing` sub-package has a full set of type annotations that static type checkers can use, so I would just recommend you to update numpy in this case.

**Comment by phlibi** [comment]
Ah, my bad, I didn't expect those annotations to have been added to a separate file. Indeed, everything is resolved with the current NumPy version. Sorry to have bothered folks.
