### ISSUE TITLE
Array-API: Need a bot to notify downstream maintainers for any changes in `numpy.array_api`

### ISSUE THREAD

**Issue by leofang** [numpy/numpy#21399]
Sorry for delay. I was tasked to open this issue based on the discussion in an array API meeting a few weeks ago. We need to set up a bot to detect if there's any diff in the `numpy.array_api` module appearing in a PR, if so the bot should notify a list of people (CuPy, MXNet, ...) upon merge to keep them informed.

cc: @rgommers @asmeurer @kmaehashi @honno

**Comment by mattip** [comment]
Until we get a bot, could we make this fail a CI `git diff` test with a nice message "Changing the `array_api` module should be intentional and the following projects should sign off on the change..."

**Comment by leofang** [comment]
I don't think we wanna block/sign off any change, a unilateral notification is sufficient 🙂

**Comment by asmeurer** [comment]
Can we use CODEOWNERS for this? https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by leofang** [comment]
Interesting, this might do the job! Although in this case code owners do not have responsibility to review/respond.

**Comment by asmeurer** [comment]
I think we can just tell people that we are using CODEOWNERS as a way to notify people and they can ignore the actual request to review.

**Comment by leofang** [comment]
See #21583.

**Comment by leofang** [comment]
Apparently #21583 did not work and I will revert it. Let's reopen this issue to track the need.

**Comment by lucascolley** [comment]
can be closed
