### ISSUE TITLE
DOC: Missing entry for `assert_no_warnings`

### ISSUE THREAD

**Issue by Patol75** [numpy/numpy#21397]
### Issue with current documentation:

Looking at [the `numpy.testing` documentation page](https://numpy.org/doc/stable/reference/routines.testing.html#module-numpy.testing), I cannot find any entry referring to the [assert_no_warnings](https://github.com/numpy/numpy/blob/fd646bd693400ce408566674f266407672248cad/numpy/testing/_private/utils.py#L1817-L1850) function. Is this the expected behaviour, or is the entry actually missing?

**Comment by mattip** [comment]
Indeed it seems that function (and maybe some others from `numpy.testing.__all__`) is missing from the [asserts](https://github.com/numpy/numpy/blob/main/doc/source/reference/routines.testing.rst#asserts) section of the documentation source page. I see only 13 functions mentioned, but I get 18 when doing
```
len([x for x in np.testing.__all__ if 'assert' in x])
```

Want to make a PR to add the missing ones?

**Comment by rossbar** [comment]
There's also the question of whether `assert_no_warnings` shouldn't be replaced with other patterns for evaluating warnings in tests, like `warnings.catch_warnings`. I think for new tests that pattern would be recommended over `npt.assert_no_warnings`. Just a thought - this doesn't mean that the missing functions shouldn't be documented.
