### ISSUE TITLE
DOC: Add dark mode switcher

### ISSUE THREAD

**Issue by MarsBarLee** [numpy/numpy#21390]
### Issue with current documentation:

A dark mode has been requested before .

The PyData Sphinx theme recently created a dark mode switcher, and the documentation for implementing it are [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html?highlight=version#add-a-dropdown-to-switch-between-docs-versions). 

An example of the dark mode switcher can be found [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/). It is the sun/moon on the top right coner, next to the version switcher.

It is currently in the dev mode, as the dark mode switcher was included 2 weeks ago. If the dark mode switcher is included in the next PyData Sphinx Theme release with documentation, we can start implementing this for NumPy.

### Idea or request for content:

This is how dark mode looks in the example linked.
![image](https://user-images.githubusercontent.com/46167686/165126091-904fc3f7-6b98-4981-bb8c-1ffc47a2a132.png)

**Comment by eric-wieser** [comment]
> The PyData Sphinx theme recently created a dark mode switcher, and the documentation for implementing it are [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html?highlight=version#add-a-dropdown-to-switch-between-docs-versions).

That doesn't look like the right link to me - that section is describing how to implement a switcher between different versions of numpy, not between different doc themes.

**Comment by MarsBarLee** [comment]
> > The PyData Sphinx theme recently created a dark mode switcher, and the documentation for implementing it are [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html?highlight=version#add-a-dropdown-to-switch-between-docs-versions).
> 
> That doesn't look like the right link to me - that section is describing how to implement a switcher between different versions of numpy, not between different doc themes.

@eric-wieser Oops, you're right, that's not the right link. There may not be documentation for that yet, perhaps when the dark mode option is official released

**Comment by eric-wieser** [comment]
My impression is that we don't have to do anything, simply updating the theme will give us the switcher. Of course that's just a guess!
