### ISSUE TITLE
BUG: Array real and imag don't seem to be visible to Pyright

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#21393]
### Describe the issue:

Array `real` and `imag` don't seem to be visible in Pyright

### Reproduce the code example:
```python
import numpy as np
x = np.zeros(10, dtype=np.float64)
print(x.real)
```

### Error message:
In Pyright, this gives:
```shell
error: Cannot access member "real" for type "NDArray[float64]"
```

### NumPy/Python version information:
1.22.3 3.10.4 (main, Apr  7 2022, 10:39:08) [GCC 11.2.0]

**Comment by mattip** [comment]
This sounds like a bug in Pyright or in your IDE. Not in NumPy. Could you move the issue to their issue tracker?

**Comment by mattip** [comment]
Ahh, maybe an error in the static typing hints? @BvB93 thoughts?

**Comment by BvB93** [comment]
Ugh, a bug in pyright it seems. I thought a workaround was implemented in https://github.com/numpy/numpy/pull/20827, but I guess it didn't quite work after all...
