### ISSUE TITLE
BUG: where/argwhere returns incorrectly shaped array

### ISSUE THREAD

**Issue by Amith225** [numpy/numpy#21404]
### Describe the issue:

this is really weird, i have an array -> x shaped (112800, 47, 1).
when i do:
np.argwhere(np.argwhere(x == x.max(axis=1, keepdims=True)))
i get an array shaped (112801, 3) instead, but its expected to give (112800, 3)

direct code reproduction was not possible, i will attach the .npy file
![image](https://user-images.githubusercontent.com/75326634/165687356-0d3de398-241d-47eb-b3ff-4e9c2c35d4f1.png)
[x.zip](https://github.com/numpy/numpy/files/8579964/x.zip)

### Reproduce the code example:

```python
# direct code reproduction was not possible, i will attach the .npy file
import numpy as np
x = np.load('x.npy')
print(x.shape)
y = np.argwhere(x == x.max(axis=1, keepdims=True))
print(y.shape)
```

### NumPy/Python version information:

1.22.3 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]

**Comment by seberg** [comment]
This looks like correct behaviour.  The issue is only that your array has a column `x[52637]` where two values are true and you are expecting one per column.  `np.argmax` may be a good alternative to get the result you want (e.g. the first one only).  It may also be a good option in any case.
