### ISSUE TITLE
DOC: Dark mode syntax highlighting isn't as color-blind friendly as the light mode

### ISSUE THREAD

**Issue by jakevandervaate** [numpy/numpy#21406]
### Issue with current documentation:

Some of the syntax highlighting in the [proposed dark mode switcher](https://github.com/numpy/numpy/issues/21390) lacks the contrast present in the light mode. The best example I noticed was the json snippet on [this page](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html?#add-a-json-file-to-define-your-switcher-s-versions).

This is a follow up from the documentation meeting conversation with @MarsBarLee and @InessaPawson.

## Original Images

The dark mode's green and orange lack contrast. The pink is harder to see as well.
![Screenshot_20220428-082646](https://user-images.githubusercontent.com/96353168/165764440-b09e76a0-f710-411d-85bd-c576d0a36954.png)

The light mode has more contrast in this example.
![Screenshot_20220428-082708](https://user-images.githubusercontent.com/96353168/165764490-5de01c0a-d2f5-4f7d-9693-f83f649ea57b.png)

---
## Filtered Images
Here is the dark mode image with a green-weak filter to give an idea of what this may look like.
![Screenshot_20220428-082646-green-weak](https://user-images.githubusercontent.com/96353168/165768260-96a83d97-b6bd-4673-806f-2febcd1f9ec2.png)

This is the dark mode image with a green-blind filter applied.
![Screenshot_20220428-082646-green-blind](https://user-images.githubusercontent.com/96353168/165771923-1cc89a29-4f38-49ac-9e02-b17c8840aa9f.png)

**Comment by rossbar** [comment]
Thanks for the feedback @jakevandervaate ! It might be worth opening this issue upstream in the [pydata-sphinx-theme project](https://github.com/pydata/pydata-sphinx-theme/issues) which is where this dark mode is implemented.

**Comment by seberg** [comment]
It would indeed be great to move this to the pydata-sphinx-theme and ping those interested there or reference it from here.

As far as I can tell, the dark-mode is not yet released, so it may be a great time to suggest changes to it in any case.

**Comment by jakevandervaate** [comment]
Thanks for pointing me in the right direction @rossbar and @seberg! I opened [this issue](https://github.com/pydata/pydata-sphinx-theme/issues/649) in [pydata-sphinx-theme](https://github.com/pydata/pydata-sphinx-theme).
