### ISSUE TITLE
BLD: F2PY 32-bit test failures

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#21420]
Do you know why the 32-bit tests are failing?

_Originally posted by @mattip in https://github.com/numpy/numpy/issues/21415#issuecomment-1114119679_

The build failures are due to what looks like a [configuration issue](https://dev.azure.com/numpy/numpy/_build/results?buildId=23711&view=logs&j=c4fbb33d-b115-53c9-54fa-705790f154ff&t=ec74c286-a9c3-5f2c-601e-255fc0544789&l=4424), leading to gfortran-5 not being found.

**Comment by rgommers** [comment]
We don't have that Azure job anymore and I haven't seen anything like this on the 32-bit Python on Windows job in GitHub Actions. So I'll close this issue.
