### ISSUE TITLE
BUG: dereferencing pointer to incomplete type ‘PyFrameObject’ 

### ISSUE THREAD

**Issue by SmartManoj** [numpy/numpy#21422]
### Describe the issue:

Build Failed for Python3.11

### Reproduce the code example:

```python
python3.11 -m pip install git+https://github.com/numpy/numpy
```

### Error message:

```shell
numpy/random/_mt19937.c: In function ‘__Pyx_AddTraceback’:
      numpy/random/_mt19937.c:438:62: error: dereferencing pointer to incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
        438 |   #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
```

### NumPy/Python version information:

`Python 3.11.0a7+ (main, Apr 19 2022, 09:05:09) [GCC 9.4.0] on linux
`

**Comment by bashtage** [comment]
Likely an issue with code generated by Cython. Which cython are you using?

**Comment by seberg** [comment]
Indeed, I suspect you will have to wait for the Cython 0.29.29 release (or maybe try using Cython 3.0) if you want to test with Python 3.11 already.
There should not be anything we can do in NumPy about this (except maybe enforce the version once Cython is released.)

**Comment by SmartManoj** [comment]
https://nekobin.com/yoyayidipa

**Comment by mattip** [comment]
For people who don't want to click on a random link, it leads to a paste-bin site with the log from the build. The first line is `python3.11 -m pip install cython==3.0.0a10`. @SmartManoj You need to use cython HEAD: `python3.11 -m pip install git+https://github.com/cython/cython@master`. See [this comment](https://github.com/cython/cython/issues/4681#issuecomment-1067125244).

**Comment by SmartManoj** [comment]
@mattip Still the same
log: https://nekobin.com/suhozitude

**Comment by mattip** [comment]
This line is suspicious:
> `/tmp/pip-req-build-vn65m44v/numpy/core/setup.py:484: MismatchCAPIWarning: API mismatch detected, the C API version numbers have to be updated. Current C api version is 15, with checksum 04a7bf1e65350926a0e528798da263c0, but recorded checksum for C API version 15 in core/codegen_dir/cversions.txt is b8783365b873681cd204be50cdfb448d. If functions were added in the C API, you have to update C_API_VERSION in /tmp/pip-req-build-vn65m44v/numpy/core/setup_common.py.
>        check_api_version(C_API_VERSION, codegen_dir)


Did you clean out the git checkout before starting `git clean -xfdd` ?

**Comment by mattip** [comment]
Could you paste the top few lines of `numpy/random/_mt19937.c` to show which cython you are using?

**Comment by seberg** [comment]
Going to close this, since this is in generated cython code and Cython seems to have fixed the specific issue (probably included in the new version that just came in).
It seems likely that Cython isn't yet fully compatible with 3.11, but there really isn't much to do about it from our side I think (although a note may be helpful).
