### ISSUE TITLE
BUG: `numpy.empty` returns data identical to already initialized, still allocated array

### ISSUE THREAD

**Issue by jcrist** [numpy/numpy#21454]
### Describe the issue:

This is maybe not a bug, but I'm confused what's happening here so I thought I'd open an issue.

The following sequence of operations repeatedly results in identical arrays on both Linux and mac:

- Create a random array using any random api (e.g. `np.random.uniform`)
- Repr the array (this is required)
- Create a new, empty array with the same shape and dtype using `np.empty`

`np.empty` returns an uninialized array, so the values should be meaningless (and thus this isn't really a bug). I'm just confused how they can end up being identical to values from a different randomly created array. If you don't repr the original array this behavior doesn't show up, so I'm assuming it's something to do with low-level OS memory page stuff or something similar?

### Reproduce the code example:

```python
In [1]: import numpy as np

In [2]: x = np.random.uniform(size=(3, 3, 3))

In [3]: x
Out[3]: 
array([[[0.70761426, 0.51793968, 0.79526172],
        [0.91495855, 0.26384822, 0.56546193],
        [0.32847297, 0.69019015, 0.43311504]],

       [[0.54161632, 0.10466797, 0.88667139],
        [0.44222868, 0.12428965, 0.54102732],
        [0.84964816, 0.61035618, 0.26823964]],

       [[0.43215862, 0.19895904, 0.5333631 ],
        [0.37212446, 0.418719  , 0.49071594],
        [0.50663872, 0.6967123 , 0.71098376]]])

In [4]: x2 = np.empty(x.shape, dtype=x.dtype)

In [5]: x2
Out[5]: 
array([[[0.70761426, 0.51793968, 0.79526172],
        [0.91495855, 0.26384822, 0.56546193],
        [0.32847297, 0.69019015, 0.43311504]],

       [[0.54161632, 0.10466797, 0.88667139],
        [0.44222868, 0.12428965, 0.54102732],
        [0.84964816, 0.61035618, 0.26823964]],

       [[0.43215862, 0.19895904, 0.5333631 ],
        [0.37212446, 0.418719  , 0.49071594],
        [0.50663872, 0.6967123 , 0.71098376]]])

In [6]: x == x2
Out[6]: 
array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])
```

### NumPy/Python version information:

numpy version: `1.21.2`
Python version: `3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48)`

**Comment by jcrist** [comment]
Apologies for opening an issue for mostly amounts to a question (feel free to close). I found this behavior surprising, and wasn't sure where else to ask.

**Comment by rkern** [comment]
Formatting the `repr` of an array does involve some temporary partial copies (via indexing), so yeah I suspect OS page shenanigans stemming from those temporaries.
