### ISSUE TITLE
DOC: Warn about empty values in `empty_like`, `masked_all`, `masked_all_like` like `np.ma.empty` does

### ISSUE THREAD

**Issue by eliadl** [numpy/numpy#21482]
### Issue with current documentation:

Source:
https://numpy.org/doc/stable/reference/generated/numpy.ma.empty.html

Destinations:
https://numpy.org/doc/stable/reference/generated/numpy.ma.empty_like.html
https://numpy.org/doc/stable/reference/generated/numpy.ma.masked_all.html
https://numpy.org/doc/stable/reference/generated/numpy.ma.masked_all_like.html

### Idea or request for content:

I've recently found out the hard way that this warning in [`np.ma.empty`](https://numpy.org/doc/stable/reference/generated/numpy.ma.empty.html
):
> [empty](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty), unlike [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros), does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, **and should be used with caution.**

is missing from the `np.ma` docs of [`empty_like`](https://numpy.org/doc/stable/reference/generated/numpy.ma.empty_like.html
), [`masked_all`](https://numpy.org/doc/stable/reference/generated/numpy.ma.masked_all.html
), [`masked_all_like`](https://numpy.org/doc/stable/reference/generated/numpy.ma.masked_all_like.html).

"Garbage values" are quite rare in python, and it's easy to forget about them.
I never had to use `empty`, but I did find `masked_all` useful for edge cases in masked averaging.
Then one day some change in my code unmasked those empty values, which I'd forgotten about.
This has led to a classic [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug). (in my case, outputs differing between running and debugging)

Future travelers who seek fast and safe behavior of `all_masked` + `zeros`, this seems to do it:
```python
def all_masked_zeros(shape: Union[int, Tuple[int, ...]]) -> np.ma.MaskedArray:
    mat = np.ma.zeros(shape)
    mat[:] = np.ma.masked
    return mat
```

**Comment by rossbar** [comment]
FWIW `np.ma.empty_like` has a similar warning in the Notes section, though the wording is not identical. That could certainly be updated to make the wording consistent with `np.ma.empty`. There is no such note in the `masked_all` or `masked_all_like`. Adding a note to these docstrings would likely be an improvement IMO, though I'm not sure it makes sense to recommend not using them.

**Comment by eliadl** [comment]
I didn't say it should be recommended not to use them.
Just place a fair warning. :)

**Comment by mdhaber** [comment]
@eliadl @rossbar For `empty`, how about something like:

> Unlike other array creation functions (e.g. [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros), [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones), and [full](https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full)), [empty](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty) does not initialize the values of the array, and may therefore be marginally faster. However, the values stored in the newly allocated array are arbitrary. For reproducible behavior, be sure to set each element of the array before reading.

Adapted to the most distant relative `ma.masked_all_like`, it might be

Unlike other masked array creation functions (e.g. [ma.zeros_like](https://numpy.org/doc/stable/reference/generated/numpy.ma.zeros_like.html), [ma.ones_like](https://numpy.org/doc/stable/reference/generated/numpy.ma.ones_like.html)), [ma.masked_all_like](https://numpy.org/doc/stable/reference/generated/numpy.ma.masked_all_like.html#numpy.ma.masked_all_like) does not initialize the values of the array, and may therefore be marginally faster. However, the values stored in the newly allocated array are arbitrary. For reproducible behavior, be sure to set each element of the array before reading.

**Comment by mdhaber** [comment]
Ok, I'll open a PR.
