### ISSUE TITLE
BUG: `np.full_like` casts float to int for non-finite values

### ISSUE THREAD

**Issue by onnoeberhard** [numpy/numpy#21496]
### Describe the issue:

Please see the code snippet below. I create an integer array `a`, then create a new one (`b`) which is supposed to have the same shape as `a`, but filled with the float value `np.nan`. Here, I don't explicitly set the dtype for `b`. NumPy converts these float values to integer.

This is unexpected behaviour, and I assume is not intended as such. I would have expected either
1. `b` is automatically made a float-array (the dtype information from `a` is not used), or
2. A TypeError is thrown, notifying me that I am trying to fill an int-array with float values.

### Reproduce the code example:

```python
>>> import numpy as np
>>> a = np.array([1, 2, 3])
>>> b = np.full_like(a, np.nan)
>>> b
array([-9223372036854775808, -9223372036854775808, -9223372036854775808])
```

### NumPy/Python version information:

1.22.3 3.8.12 (default, Oct 22 2021, 18:39:35) 
[Clang 13.0.0 (clang-1300.0.29.3)]

**Comment by onnoeberhard** [comment]
I have looked again into the docs and it seems like this behaviour is indeed intended.. But would it ever really make sense in this context? I mean casting non-finite float values to int without even throwing a warning?

**Comment by seberg** [comment]
See also gh-21437 which would ensure a warning for this example.  (Not for a value like `2.5` though, we would have to add a cast-safety check explicitly.)

**Comment by seberg** [comment]
Actually, let me close it.  Please don't hesitate to reopen an issue though.  Xref gh-21437 which added the warnings.
