### ISSUE TITLE
BUG: argsort

### ISSUE THREAD

**Issue by CHARLESYY-CAFELATTE** [numpy/numpy#21509]
### Describe the issue:

np.argsort cannot really sort an array

### Reproduce the code example:

```python
import numpy as np
scores = np.random.randn(10,2)
print(scores)
scores = np.argsort(scores,axis=0)
print(scores)
```

### Error message:

```shell
error output as:
[[-0.93424302 -0.25495421]
 [-0.0445277  -0.7277739 ]
 [-0.49270801  0.18517224]
 [ 0.34054662  0.88074911]
 [ 0.37625286 -0.86732847]
 [-0.50659025  0.2918364 ]
 [-1.034566   -0.75474416]
 [ 1.74318646  1.93941125]
 [ 0.76326831  0.5199335 ]
 [ 0.54829216 -0.67852352]]
[[6 4]
 [0 6]
 [5 1]
 [2 9]
 [1 0]
 [3 2]
 [4 5]
 [9 8]
 [8 3]
 [7 7]]
```

### NumPy/Python version information:

numpy==1.22.3
python=3.8

**Comment by mattip** [comment]
What did you expect to get? [`argsort` returns the indices](https://numpy.org/devdocs/reference/generated/numpy.argsort.html), not the values. Perhaps you were looking for [`np.sort`](https://numpy.org/devdocs/reference/generated/numpy.sort.html), or were you looking to sort the rows or columns?

**Comment by CHARLESYY-CAFELATTE** [comment]
Maybe I miss understand this function, I was looking for, say -0.93424302 rank 9th axis=0 so I got an 8 in [0,0] of the output.
