### ISSUE TITLE
BUG: np.linspace(-0.0, 0.0, 1) outpus [0.] which does not include the start value which is -0.0.

### ISSUE THREAD

**Issue by RashulChutani** [numpy/numpy#21513]
### Describe the issue:

Running np.linspace (-0.0, 0.0, 1) outputs array([0.]) which does not include the start value (-0.0).
The documentation says 
Returns samples: ndarray
There are num equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop) (depending on whether endpoint is True or False).
Thus the start value should be always included.

### Reproduce the code example:

```python
import numpy as np
np.linspace(-0.0, 0.0, 1)
```

### Error message:

```shell
The output is [0.0] instead of [-0.0].
```

### NumPy/Python version information:

Numpy: 1.22.3 3.9.12 
sys: [GCC 7.5.0]

**Comment by rkern** [comment]
Negative zeros are fragile and will frequently disappear after many manipulations that "should" leave an input value the same, according to some mental model of floating point arithmetic. It would be difficult to change the code to fully preserve negative zeros without placing special-case checks all over the place solely for negative zeros, making the general case more expensive.

To the extent that `0.0 == -0.0`, I would not consider this a bug in `linspace`. If the negativeness of the 0 is important to the subsequent calculations, I recommend placing it after the `linspace` is computed.

**Comment by InessaPawson** [comment]
@rkern Thank you for the thorough  answer!
@RashulChutani Since your question has been solved, I'll close the issue.
