### ISSUE TITLE
ENH: Support Random Unit Vector

### ISSUE THREAD

**Issue by saroad2** [numpy/numpy#21523]
### Proposed new feature or change:

Description
========

Often you want to randomize a "direction" that doesn't have "size". This can be useful when:
* You want to randomize the direction of an NPC walk developing in a 2D or 3D games, where its speed is a predefined constant.
* You're developing particles simulation with all particles moving in random directions
* etc.

This random direction should be an `n`th dimensional unit vector which is randomize **uniformly** from the unit sphere. That means that sections of the unit sphere with equal areas should have the same chance of getting a vector from.

Implementation
===========

If one wants to randomize `n`th dimensional direction uniformly, one must do the following:
1. Generate `n` components of the vector using the standard normal distribution
2. Find the norm the generated vector
3. Divide the vector by its norm

In simple Python code:
```python
import numpy as np


def sphere_uniform(n: int):
    vec = np.random.normal(size=n)
    norm = np.sqrt(np.sum(vec ** 2))
    return vec / norm
```

This implementation suggestion is based on [this blog post](https://towardsdatascience.com/the-best-way-to-pick-a-unit-vector-7bd0cc54f9b). I'm not sure if there's a faster way of implementing it using C++ and Cython, but I'm confident that someone here will know.

Why Implement It in Numpy?
===================

I believe that random unit vectors are common enough to be a part of Numpy. Scientists, gamers and engineers use random directions all the time, and I believe there is no reason why Numpy won't provide this ability.

**Comment by saroad2** [comment]
Hey @rkern , thanks for the response.

In general, I understand your approach.
Maybe the right thing to do is to add a new library which is not *numpy* or *scipy* that handles distributions and randomizers, hoping it will become the go-to library for everyone using *numpy* and *scipy*.

In any case, I'l open th same issue on *scipy* and see what they think about it.

**Comment by WarrenWeckesser** [comment]
Thanks for the proposal, @saroad2, but this appears to be out of scope for NumPy.

Anyone interested in this method should contribute to the discussion of @saroad2's proposal over in [SciPy](https://github.com/scipy/scipy/issues/16205).
