### ISSUE TITLE
BUG: logical_and returns different results depending on False or None are the first argument

### ISSUE THREAD

**Issue by ssylvain-nvidia** [numpy/numpy#21521]
### Describe the issue:

np.logical_and() seems to follow Kleene's logic for all cases except for logical_and(None, False). The reverse returns the correct answer, logical_and(False, None)

My expectation is that they would both be False since all other permutations follow Kleene's logic

### Reproduce the code example:

```python
import numpy as np

print(np.logical_and(None, False))
print(np.logical_and(False, None))

assert np.logical_and(None, False) == np.logical_and(False, None)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
```

### NumPy/Python version information:

numpy.__version__
'1.21.5'
sys.version
'3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]'

**Comment by rkern** [comment]
`np.logical_and()` does not implement [Kleene logic](https://en.wikipedia.org/wiki/Three-valued_logic#Kleene_and_Priest_logics) with `None` as the "unknown" value. Instead, `logical_and()` follows the type-promotion logic like most ufuncs; seeing `None` as one of the inputs, it upcasts the other value to `dtype=object`, then uses `operator.and_()` to compute the result using Python's boolean logic (i.e. using the semantics of the `and` keyword in the Python language). `None` is "falsey" under those semantics. [Python's binary boolean operators short-circuit](https://docs.python.org/3/reference/expressions.html#boolean-operations): given `x and y`, if `x` is "falsey", then it will be the result of the expression. Both `None` and `False` are "falsey", so `logical_and(None, False)` returns `None` while `logical_and(False, None)` will return `False`, the same as `operator.and_()`.

**Comment by ssylvain-nvidia** [comment]
I understand that's what Python returns. I don't agree that this is what a numerical library should return (Python or not)

**Comment by charris** [comment]
Once `None` is an element, it is no longer a numerical library :)  Note that `None` is  also occasionally used as a shortcut to getting an object array, and at that point operations are provided by the objects.
```
In [1]: np.array(None)
Out[1]: array(None, dtype=object)
```

You can avoid the promotion by specifying a dtype:
```
In [1]: np.array(None, np.bool_)
Out[1]: array(False)
```

**Comment by ssylvain-nvidia** [comment]
A thousand thanks @charris.
