### ISSUE TITLE
Latest Pygments needed for f2py documentation to highlight `meson.build`.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#21557]
I note that Pygments is not currently pinned, or even referenced in `doc_requirements.txt`. Is there any reason not to pin it to the latest version?

Oh, and we have a security warning: https://github.com/numpy/doc/security/dependabot/2. That is in MathJax, is there a good reason not to just use the sphinx default? The most time consuming part of the docs build is cloning the documentation repo.

**Comment by rgommers** [comment]
@charris I don't see what this has to do with `meson`? Typo in your issue title maybe?

> I note that Pygments is not currently pinned, or even referenced in `doc_requirements.txt`. Is there any reason not to pin it to the latest version?

Pins need maintenance and since we've never had any issues with Pygments, it doesn't need one.

> Oh, and we have a security warning: https://github.com/numpy/doc/security/dependabot/2. That is in MathJax, is there a good reason not to just use the sphinx default? The most time consuming part of the docs build is cloning the documentation repo.

Sphinx didn't used to bundle MathJAX, and still doesn't - see https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax. So we need to get it from somewhere for offline usage.

We had a MathJAX related security issue before, I think https://github.com/scipy/scipy/issues/13210#issuecomment-740000755. There may be something else, but I can't find it.

**Comment by rgommers** [comment]
> I note that Pygments is not currently pinned, or even referenced in `doc_requirements.txt`

Re referenced, we do not have a direct dependency on Pygments AFAIK. And transitive dependencies should not be our problem to keep track of.

**Comment by charris** [comment]
> we do not have a direct dependency on Pygments AFAIK

It is needed for the docs. In particular, the need for meson came from the new f2py documentation that covers building with cmake/meson.

**Comment by charris** [comment]
> Pins need maintenance and since we've never had any issues with Pygments, it doesn't need one.

Well, I did spend some time tracking down and fixing that doc build problem.

**Comment by rgommers** [comment]
I'm still very confused by this, maybe point me to the relevant PR or a CI log that shows the issue?

My guess at this point is:
- We don't need `meson` itself to build the docs (that certainly wasn't included in gh-20182)
- We do have code snippets with Meson syntax, so latest Pygments may be needed to highlight them correctly (?)
- Pygments is a transitive dependency of Sphinx, so maybe when we build the docs with an old Sphinx version, we don't pull in a new enough version of Pygments

**Comment by charris** [comment]
The documentation includes `./doc/source/f2py/code/meson.build` and highlights it as meson code.

**Comment by rgommers** [comment]
Okay, that means we don't need the `meson` package indeed, just `pygments`. I've just checked Sphinx, and all recent versions (back to 3.5.2) require
```
'Pygments>=2.0',
```
That means the latest Pygments already gets pulled in. Pygments `>=2.10` has support for Meson. 

So there's nothing to do here.

**Comment by charris** [comment]
Yet the docs didn't build until I upgraded Pygments. Missing a meson Lexer (IIRC).

**Comment by charris** [comment]
And in 1.22.x and main, the Sphinx version is pinned to 4.5.0. That is probably where the problem comes from. What should we use for the Sphinx version? Also, wouldn't `Pygments>=2.0` be OK with a version less that 2.10? The latest version would only be pulled in if there was no current version already installed.

**Comment by rgommers** [comment]
> Also, wouldn't `Pygments>=2.0` be OK with a version less that 2.10?

Any new install created with that environment will install latest Pygments, so it's not really that interesting that Sphinx allows a lower version I'd say. I think you just built the docs in an old environment?

> And in 1.22.x and main, the Sphinx version is pinned to 4.5.0. That is probably where the problem comes from. What should we use for the Sphinx version?

That cannot really be a problem, Sphinx 4.5.0 seems fine. And our doc builds in CI were not failing, right?

**Comment by charris** [comment]
> I think you just built the docs in an old environment?

Of course. The standard builds have never worked for me due to the path being incorrectly set up.

**Comment by charris** [comment]
I also build with Python 3.10 and need to avoid using easy_install. The simplest solution is to simply update `doc_requirements`, I use that anyway because my default Python is updated about once a year. The correct solution is probably to change the whole doc build scheme and use a proper virtual environment.

**Comment by charris** [comment]
Current main fails with `jinja2.exceptions.TemplateNotFound: version-switcher.html`, that needs fixing for 1.23.x.

**Comment by rgommers** [comment]
> The correct solution is probably to change the whole doc build scheme and use a proper virtual environment.

Yes - and we should do the release doc build in CI I'd say; just store the html docs as a zip artifact in GitHub Actions, then download that at release time and upload to the doc server. Much more reliable.

**Comment by charris** [comment]
We also need the pdfs. I suppose we could drop them somewhere along the line, I don't know who uses them anymore. I (almost) fixed current main by updating Sphinx, seems Sphinx 4.5.0 is needed. There is still a pdf bug to track down.

**Comment by rgommers** [comment]
Indeed, let's drop those. SciPy already dropped pdf builds. The LaTeX requirement is a massive pain, and the pdf docs are pretty much useless (2000 pages of stuff that doesn't look good) compared to html. With the downloadable zipped html, I think we no longer need pdf.

**Comment by charris** [comment]
Sounds good, solves some messy problems. We are good to go with the html. Note that `numpy.org` will need an update to drop the pdf links. Do we want to drop them for old versions also? I think for 1.23 I can just link to the broken pdfs, only the last page of the user docs seems to be (unusually) broken there. I'll drop a note to the mailing list.

**Comment by HaoZeke** [comment]
We discussed this a few times at documentation / community meetings and decided they could be reworked.

They are useful for some users (eg. EReader users)

**Comment by astrojuanlu** [comment]
xref to https://github.com/scipy/scipy/issues/15635 where dropping PDF docs for SciPy was discussed

**Comment by bsipocz** [comment]
Is there a method to measure whether there are any EReader users interacting with the docs in this way?

**Comment by charris** [comment]
My experience with technical books on ereaders hasn't been good, they need space. However, there are other options for conversion of HTML to [PDF and ePub](https://www.epubor.com/how-to-convert-html-to-epub.html). Perhaps that sort of thing should be left to a third party?

**Comment by charris** [comment]
Note that LATEX does not support SVG images, that in itself decreases quality and sometime requires that we have both SVG and PNG images of the same thing.

**Comment by HaoZeke** [comment]
Closing as the TeX builds have been removed.
