### ISSUE TITLE
BUG: numpy.random.Generator.multinomial fails for multi-dimensional pvals argument in documentation example

### ISSUE THREAD

**Issue by zeno129** [numpy/numpy#21555]
### Describe the issue:

Multinomial random generator is not working for multi-dimensional `pvals` argument. 

I was originally using a `pvals` with shape `(10,3)` and I got a ValueError. I then tried running an example from the documentation with a 2d `pvals` of shape `(2,3)` and it isn't working either.

Example from the documentation for [numpy.random.Generator.multinomial](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.multinomial.html#numpy.random.Generator.multinomial)
> Generate categorical random variates from two categories where the first has 3 outcomes and the second has 2.
> ```python
> rng.multinomial(1, [[.1, .5, .4 ], [.3, .7, .0]])
>```

I also tried running it with pvals type casted to np.array
```python
rng.multinomial(1, np.array([[.1, .5, .4 ], [.3, .7, .0]]))
```
However, I get the same error.

### Reproduce the code example:

```python
import numpy as np
rng = np.random.default_rng()
rng.multinomial(1, [[.1, .5, .4 ], [.3, .7, .0]])

# expected output:
# array([[0, 0, 1],
#        [0, 1, 0]], dtype=int64)  # random
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_generator.pyx", line 3757, in numpy.random._generator.Generator.multinomial
ValueError: object too deep for desired array
```

### NumPy/Python version information:

```
1.21.2 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
```

**Comment by WarrenWeckesser** [comment]
Support for broadcasting of the arguments of `multinomial` was added in NumPy version 1.22.0.  It looks like we neglected to make a note of this improvement in the [1.22 release notes](https://numpy.org/doc/stable/release/1.22.0-notes.html).

**Comment by seberg** [comment]
If anyone wants to do a small PR, adding a `.. versionchanged::` or `.. versionadded:` tag would make sense.

**Comment by jcusick13** [comment]
I'd be happy to open a PR for the docstring if no one else is working on it.

**Comment by charris** [comment]
@jcusick13 Just go for it.
