### ISSUE TITLE
RuntimeError: Cannot parse version 0+untagged

### ISSUE THREAD

**Issue by unsignedrant** [numpy/numpy#21550]
### Describe the issue:

Build fails on macOS Monterey 12.3.1 / python 3.10.4 / pip 22.1, not sure whether it's a numpy or pip issue though.

### Reproduce the code example:

```python
git clone https://github.com/numpy/numpy
pip install numpy/
```

### Error message:

```shell
% pip install numpy/
Processing ./numpy
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 64, in <module>
          raise RuntimeError(f'Cannot parse version {FULLVERSION}')
      RuntimeError: Cannot parse version 0+untagged.1.gae8b9ce
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### NumPy/Python version information:

python 3.10.4

**Comment by charris** [comment]
Probably a git issue. What git version are you using? See https://github.com/pypa/manylinux/issues/1309 among other places for discussion of the problems caused by the latest update.

Might also see if you have the `v1.23.0.dev0` tag in the repo.

**Comment by unsignedrant** [comment]
It's git version 2.32.1 (Apple Git-133). I tried checking the tag using ` git describe --always --tags`  which gives `ae8b9ce`.

**Comment by charris** [comment]
> It's git version 2.32.1
Should be good.

> I tried checking the tag using git describe --always --tags
I get
```
charris@fc [numpy.git (main)]$ git describe --always --tags
v1.23.0.dev0-1251-g05d90012f4
```
What does `git branch` tell you? I'm curious what you have checked out.

**Comment by unsignedrant** [comment]
I just cloned the repo, no checkouts.

    % git branch
    * main

**Comment by charris** [comment]
OK, you are on the main branch (starred). But the tags seem missing. Try `git pull origin --tags`.

**Comment by unsignedrant** [comment]
I just found out what's wrong. I initially cloned the repo with `--depth 1` which for some reason result in the error. The problem was gone and I was able to build the wheel successfully by cloning without the `--depth` flag.

**Comment by charris** [comment]
> I initially cloned the repo with --depth 1

:+1:  Ah, you didn't say that :) Yes, that will do it.

**Comment by lorentzenchr** [comment]
I have the same problem, but literally did `git clone https://...numpy.git` without the `depth` flag.

**Comment by sunghjung3** [comment]
@lorentzenchr I also had the same problem, but I was able to resolve it by running these 2 lines:
`git submodules update --init`
`git fetch upstream --tags`

**Comment by lorentzenchr** [comment]
@sunghjung3 Thank you so much. That did it (only a tiny typo: `git submodules update --init`).

@charris Should this be documented somewhere?

**Comment by mattip** [comment]
The [gitwash page](https://numpy.org/devdocs/dev/gitwash/development_setup.html#make-the-local-copy) would be a nice place to add documentation about `git fetch upstream --tags`
