### ISSUE TITLE
BUG: `np.log(0)` triggers `RuntimeWarning: divide by zero encountered in log`

### ISSUE THREAD

**Issue by duburcqa** [numpy/numpy#21560]
### Describe the issue:

This behavior is unexpected and misleading since it is well-defined and the result is valid (`-inf`). There is no such issue with other linear algebra libraries such as `torch`.

### Reproduce the code example:

```python
import numpy as np
np.log(0.0)
```

### Error message:

```shell
<stdin>:1: RuntimeWarning: divide by zero encountered in log
-inf
```

### NumPy/Python version information:

1.21.6 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]

**Comment by seberg** [comment]
@duburcqa the same argument can be made for `1./0.`.  I don't think `torch` even *tries* to give the correct warning, i.e. it behaves as NumPy does if you do:
```
with np.errstate(all="ignore"):
    code
```
or in this case to be more specific (there are more ways to just set it process wide):
```
with np.errstate(divide="ignore"):
    np.log(0)
```
So NumPy gives you the option to choose if you want to see this (correct) warning or not.

The general rule is:  If you get a new `inf` (from a fininte numbers), you get a divide by zero warning.  If you get a new NaN, you get an "invalid" warning.

NumPy inherits this behaviour from C99: https://en.cppreference.com/w/cpp/numeric/math/log
Which itself should inherits it from the IEEE 745 standard.

So thanks for the report, but this is correct and the only thing might be to explain better when to expect these warnings in the `np.errstate` documentation or similar.  I am not sure if that could use improvement there.

**Comment by duburcqa** [comment]
Thanks for your answer. I understand the rational and I agree with you it is the right behavior to trigger a warning if it is a rule of numpy to do so when you get a inf from a finite number. Yet, I think the message in particular is misleading because it has nothing to do with a division by zero here.

**Comment by rkern** [comment]
Unfortunately, we don't have much control over that. IEEE-754 uses the same floating-point error flag for both situations. We're just reporting that up.

**Comment by duburcqa** [comment]
It is not possible to overwrite the message on python side ?

**Comment by seberg** [comment]
Yes, we could expand or tweak the message if there is a good suggestion.
