### ISSUE TITLE
CircleCI devdoc upload failure.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#21575]
This is just to track the failure of the [last CircleCI devdoc upload](https://tinyurl.com/5dwb4pk5). If it doesn't persist, this can be closed.

**Comment by charris** [comment]
May just be a conflict with two almost simultaneous accesses.

**Comment by seberg** [comment]
Seems it was just a fluke, probably really that simultaneous access.  Since then we had lots of successful deploys.
