### ISSUE TITLE
DOC: Different behavior for allclose and assert_allclose

### ISSUE THREAD

**Issue by sachu92** [numpy/numpy#21578]
### Describe the issue:

Although the documentation of numpy.testing.assert_allclose says[1] : 

> The test is equivalent to allclose(actual, desired, rtol, atol) (note that allclose has different default values). It compares the difference between actual and desired to atol + rtol * abs(desired).

their behavior differs when comparing arrays of different shapes. In the following example code, the first assertion with `np.allclose` passes, while the second one with `np.testing.assert_allclose` fails.

[1] https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html

### Reproduce the code example:

```python
import numpy as np
arr1 = np.ones(5)
arr2 = np.ones((5, 1))

assert np.allclose(arr1, arr2)
np.testing.assert_allclose(arr1, arr2)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 763, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(shapes (5,), (5, 1) mismatch)
 x: array([1., 1., 1., 1., 1.])
 y: array([[1.],
       [1.],
       [1.],...
```

### NumPy/Python version information:

1.22.3 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]

**Comment by seberg** [comment]
I would consider this intentional.  In testing, checking for the same shape can be useful, but for the main NumPy it is very rare that we would not broadcast (`np.array_equal` does).

Suggestions to update the documentation are appreciated of course, you are right it is only equivalent if you ignore the shape check (and maybe some others?)).

**Comment by sachu92** [comment]
I see. True, there are definitely cases where testing should check for the equality of shapes. 

Perhaps it might help to mention the shape check in the documentation of `numpy.testing.assert_allclose`. My suggestion would be to include the same content of `numpy.testing.assert_array_equal` there, as all of it is also true for `numpy.testing.assert_allclose`.

> Given two array_like objects, check that the shape is equal and all elements of these objects are equal (but see the Notes for the special handling of a scalar). An exception is raised at shape mismatch or conflicting values. In contrast to the standard usage in numpy, NaNs are compared like numbers, no assertion is raised if both objects have NaNs in the same positions.

and as a note:

> When one of x and y is a scalar and the other is array_like, the function checks that each element of the array_like object is equal to the scalar.

**Comment by sachu92** [comment]
Mentioning the shape check is even more important because not all functions in the testing module does the array shape check. For instance, I just noticed that `numpy.testing.assert_array_almost_equal_nulp` does not do it. 

In the following:
```python
import numpy as np
arr1 = np.ones(5)
arr2 = np.ones((5, 1))

np.testing.assert_array_almost_equal(arr1,arr2)
np.testing.assert_array_almost_equal_nulp(arr1, arr2)
```

first assertion fails because the shapes are different, where as the second one passes.

**Comment by Andrej730** [comment]
Came across this too and it is confusing since names `allclose` and `assert_allclose` are identical and suggest that they should do the same thing (until someone stumbles upon the difference), the one just runs `assert` and provides a readable error message.

If the argument is that checking the shape makes sense since it's in `testing`, then I guess `assert_array_almost_equal_nulp` should also check the shape for consistency.
