### ISSUE TITLE
Problems building PDF docs in main.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#21571]
I'm missing some characters, anyone know where these occur or what font is needed?
```
Missing character: There is no 傅 (U+5085) in font [FreeSerif.otf]/OT:script=lat
n;language=dflt;mapping=tex-text;!
Missing character: There is no 立 (U+7ACB) in font [FreeSerif.otf]/OT:script=lat
n;language=dflt;mapping=tex-text;!
Missing character: There is no 业 (U+4E1A) in font [FreeSerif.otf]/OT:script=lat
n;language=dflt;mapping=tex-text;!
Missing character: There is no （ (U+FF08) in font [FreeSerif.otf]/OT:script=lat
n;language=dflt;mapping=tex-text;!
Missing character: There is no ） (U+FF09) in font [FreeSerif.otf]/OT:script=lat
n;language=dflt;mapping=tex-text;!
```

**Comment by WarrenWeckesser** [comment]
Here they are:

https://github.com/numpy/numpy/blob/89b4f725b0babe3ddacb60df972118c9bc6e0e4a/doc/changelog/1.21.4-changelog.rst?plain=1#L14

https://github.com/numpy/numpy/blob/89b4f725b0babe3ddacb60df972118c9bc6e0e4a/doc/source/release/1.21.4-notes.rst?plain=1#L31

**Comment by charris** [comment]
Thanks, looks like the pdf doc build cannot handle the Chinese characters. Removing them fixes one problem.
