### ISSUE TITLE
Problems building numpy-user pdf from main branch

### ISSUE THREAD

**Issue by charris** [numpy/numpy#21573]
This is just to track things as they turn up and get fixed.

- Latex stops and asks for input when it hits this bit
    ```
   .. [*] The reason for setting ``N=3`` is that NumPy will, on the
   ```
   at line 135 in https://github.com/numpy/numpy/blame/main/doc/source/user/depending_on_numpy.rst#L135,
   I think it is bothered by '*'. 

- Building the numpy-user index completely fails with missing references in the 'Python Module Index' section, looks like
    ```
    n
    numpy.f2py, ??
    numpy.lib.recfunctions, ??
   ```
   And that is all that is in that section.  I suspect the first problem originates in
  `doc/source/user/c-info.python-as-glue.rst` and the second in
  `doc/source/user/basics.rec.rst`.

**Comment by charris** [comment]
The latex code for the second problem is:
```
\renewcommand{\indexname}{Python Module Index}
\begin{sphinxtheindex}
\let\bigletter\sphinxstyleindexlettergroup
\bigletter{n}
\item\relax\sphinxstyleindexentry{numpy.f2py}\sphinxstyleindexpageref{f2py/usage:\detokenize{module-numpy.f2py}}
\item\relax\sphinxstyleindexentry{numpy.lib.recfunctions}\sphinxstyleindexpageref{user/basics.rec:\detokenize{module-numpy.lib.recfunctions}}
```

**Comment by charris** [comment]
Note that we might be dropping the pdf documentation, at which point we care about none of this :)

**Comment by mattip** [comment]
+1 for dropping the pdf documentation if it is painful to fix

**Comment by charris** [comment]
We have dropped PDF, so closing this.
