### ISSUE TITLE
Support for Python version 3.10.4??

### ISSUE THREAD

**Issue by 13Quavo** [numpy/numpy#21576]
### Describe the issue:

When I do `pip install numpy ` it says Failed  building wheel for numpy

Any solutions? Thank you

### Reproduce the code example:

```python
a
```

### Error message:

```shell
a
```

### NumPy/Python version information:

a

**Comment by charris** [comment]
What platform are you running on?

**Comment by 13Quavo** [comment]
Termux

**Comment by charris** [comment]
Looks like a known problem on the internet. Your best bet is to google for a solution, looks like there are some.

**Comment by seberg** [comment]
Going to close the issue for now (we can reopen with more information if there may be an actionable item for NumPy).  Next time, please make sure to provide a full build failure information and details like the "Termux" use.

But as @charris said:  For now this does not look like something we can help with, but rather something specific to your system.  (You may get lucky and someone here happens to have a pointer though.)
