### ISSUE TITLE
DOC: Inaccuracy in documentation of np.angle

### ISSUE THREAD

**Issue by edw71** [numpy/numpy#21593]
### Issue with current documentation:

The documentation states that

> Although the angle of the complex number 0 is undefined, numpy.angle(0) returns the value 0.

This seems to be incorrect if the real part of the complex number is -0.0.

For details see my answer to

(https://stackoverflow.com/questions/72056648/why-does-numpy-angle00j-answer-pi-instead-of-zero/72373548#72373548)

**Comment by Meghana-12** [comment]
Hi, can I give this a shot?

**Comment by charris** [comment]
@Meghana-12 No permission needed, go for it.

**Comment by ZicsX** [comment]
Hi @charris

I would suggest adding the following Notes to the documentation:

Although the angle of a complex number is undefined if both the real and imaginary parts are 0.0, ``numpy.angle(0.0+0.0j)`` returns 0.0, which is mathematically equivalent to the angle of the complex number 1.0+0.0j.

If you allow me, I'm willing to create a pull request for it.

**Comment by melissawm** [comment]
@ZicsX that looks good, please open a PR 😄
