### ISSUE TITLE
Travis wheels did not upload on tag push.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#21599]
See https://app.travis-ci.com/github/numpy/numpy/jobs/571387615.

@mattip @EwoutH Ping

**Comment by mattip** [comment]
[`TRAVIS_TAG is v1.23.0rc1`](https://app.travis-ci.com/github/numpy/numpy/jobs/571387615#L23372) so it seems @charris is correct, this is not `refs/tags/v*`

**Comment by charris** [comment]
A manual run puts the wheels in the nightly repo.

**Comment by mattip** [comment]
I restarted that specific travis build manually, which should trigger a wheel upload to nightly with the correct wheel name. If so then we can manually download it from nightly and upload to staging
