### ISSUE TITLE
Allow arbitrary user-defined lambda functions to run in np.outer method

### ISSUE THREAD

**Issue by matthew-halligan** [numpy/numpy#21613]
### Proposed new feature or change:

Hello, I am writing today to suggest that arbitrary lambda functions be allowed in the np.outer() method.

I am following a a lab exercise in "An Introduction To Statistical Learning" that uses R and R's outer function allows for user-defined functions to be used to run the outer function.

I have replicated this functionality in a method I called np.outerf which requires parameters (a, b, FUN, out=None)

```
def outerf(a, b,  FUN, out=None):
   # Initialize an array of zeros with the shape of (a,b) 
    z = np.zeros((len(a), len(b)))
    a = asarray(a)
    b = asarray(b)
    # Nested for loop to iterate and assign values to each index
    for i in range(len(a)):
        for j in range(len(b)):
            z[i][j] = FUN(a[i], b[j])
    return z
```

Calls to outerf look like this:
np.outerf(array_1, array_2, lambda array_1, array_2: array_1+array_2, out=None)

I did not implement the out portion because I don't need it but this code allows the use of arbitrary lambda functions to be run and now I can continue with following the book's lab exercise.

**Comment by WarrenWeckesser** [comment]
FYI: The NumPy [ufuncs](https://numpy.org/doc/stable/user/basics.ufuncs.html) (such as `np.add`, `np.subtract`, `np.arctan2`, etc) have the method `outer`:
```
In [15]: a = np.array([1, 2, 3])

In [16]: b = np.array([10, 20, 30])

In [17]: np.add.outer(a, b)
Out[17]: 
array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [18]: np.arctan2.outer(a, b)
Out[18]: 
array([[0.09966865, 0.0499584 , 0.033321  ],
       [0.19739556, 0.09966865, 0.06656816],
       [0.29145679, 0.14888995, 0.09966865]])
```

For an arbitrary function, you can create a ufunc with [`np.frompyfunc`](https://numpy.org/doc/stable/reference/generated/numpy.frompyfunc.html), and then use its `outer` method.  But be aware that the only data type supported by the generated ufunc is `object`.  For example,

```
In [50]: def fun(a, b):
    ...:     if b > 20:
    ...:         return a + b
    ...:     else:
    ...:         return (a + b)*(a - b)
    ...: 

In [51]: ufun = np.frompyfunc(fun, 2, 1)

In [52]: ufun.outer(a, b)
Out[52]: 
array([[-99, -399, 31],
       [-96, -396, 32],
       [-91, -391, 33]], dtype=object)
```

Note that the data type of the result is `object`.  If desired, the array can be cast to a NumPy type:

```
In [58]: x = ufun.outer(a, b)

In [59]: x.astype(np.int32)
Out[59]: 
array([[ -99, -399,   31],
       [ -96, -396,   32],
       [ -91, -391,   33]], dtype=int32)
```

**Comment by seberg** [comment]
Closing, ufuncs support this, and I seems unlikely that there is any gain over that had by including `func=` into the `np.outer` signature.
