### ISSUE TITLE
BUG: 1.22.4 breaks frombuffer API compared with 1.22.3

### ISSUE THREAD

**Issue by carterbox** [numpy/numpy#21612]
### Describe the issue:

Arrays returned by np.frombuffer() do not have the same base attribute when compared before and after version 1.22.4. I believe this behavior may only be reproduceable on Windows/OSX.

Related:
- https://github.com/numpy/numpy/pull/21324
- https://github.com/tomopy/tomopy/pull/585

### Reproduce the code example:

```python
import numpy as np
import multiprocessing as mp
import ctypes
shared_obj = mp.RawArray(ctypes.c_double, (6, 6))
shared_arr = np.frombuffer(shared_obj)
assert type(shared_arr) == np.ndarray
assert type(shared_obj) == type(shared_arr.base)
```

### Error message:

```shell
>       assert type(shared_obj) == type(shared_arr.base)
E       AssertionError: assert <class 'multiprocessing.sharedctypes.c_double_Array_2'> == <class 'memoryview'>
E        +  where <class 'multiprocessing.sharedctypes.c_double_Array_2'> = type(<multiprocessing.sharedctypes.c_double_Array_2 object at 0x0000010E0B283940>)
E        +  and   <class 'memoryview'> = type(<memory at 0x0000010E0921ED00>)
E        +    where <memory at 0x0000010E0921ED00> = array([6., 6.]).base
```

### NumPy/Python version information:

The code example works on 1.22.3, but not 1.22.4

**Comment by charris** [comment]
Likely the backport of  https://github.com/numpy/numpy/pull/21324. This will also be present in the 1.23.x series. @seberg Thoughts?

**Comment by seberg** [comment]
Yes, this was intentional, because the buffer handling is otherwise unsafe.  Now, there is one escalation level that we could try, and that is checking whether the input object has the `releasebuffer` slot.
Basically, I didn't do this change for a long time for this worry, but then did after there was yet another report how the current handling is incorrect.

That would work for `mp.RawArray` it seems, and I had actually even put a comment considering doing that in there.  So I can do a PR that retains the old behavior more often (and does it for this specific case).

**Comment by seberg** [comment]
It seems `np.ndarray` will still use the unsafe version at this time, so might be a workaround.

**Comment by seberg** [comment]
I think this is the right diff to apply:
```diff
diff --git a/numpy/core/src/multiarray/ctors.c b/numpy/core/src/multiarray/ctors.c
index 743d14558..68bf1438f 100644
--- a/numpy/core/src/multiarray/ctors.c
+++ b/numpy/core/src/multiarray/ctors.c
@@ -3687,15 +3687,16 @@ PyArray_FromBuffer(PyObject *buf, PyArray_Descr *type,
     }
 
     /*
-     * The array check is probably unnecessary.  It preserves the base for
-     * arrays.  This is the "old" buffer protocol, which had no release logic.
-     * (It was assumed that the result is always a view.)
-     *
-     * NOTE: We could also check if `bf_releasebuffer` is defined which should
-     *       be the most precise and safe thing to do.  But that should only be
-     *       necessary if unexpected backcompat issues are found downstream.
+     * We try to preserve the base in case someone uses it (and apparently some
+     * bases can be pickled, see gh-21612).
+     * We do this for arrays and (includes arrays) if the buffer does not
+     * define any cleanup, in which case we know that holding on to the
+     * original object must be sufficient.
      */
-    if (!PyArray_Check(buf)) {
+    if (!PyArray_Check(buf)
+            /* If releasebuffer is support must go via a MemoryView. */
+            && Py_TYPE(buf)->tp_as_buffer
+            && Py_TYPE(buf)->tp_as_buffer->bf_releasebuffer) {
         buf = PyMemoryView_FromObject(buf);
         if (buf == NULL) {
             return NULL;
@@ -3764,7 +3765,7 @@ PyArray_FromBuffer(PyObject *buf, PyArray_Descr *type,
     ret = (PyArrayObject *)PyArray_NewFromDescrAndBase(
             &PyArray_Type, type,
             1, &n, NULL, data,
-            NPY_ARRAY_DEFAULT, NULL, buf);
+            NPY_ARRAY_DEFAULT, NULL, view.obj ? view.obj : buf);
     Py_DECREF(buf);
     if (ret == NULL) {
         return NULL;
```
The second line isn't necessary, although I suspect that it is a bit safer in case some buffer exporter does strange/dangerous things.

**Comment by carterbox** [comment]
Thanks! I will check this sometime next week.

**Comment by seberg** [comment]
I opened gh-21632 for it, since we should just apply that change since you ran into it (omitted the last line it felt like trying to be too smart; so maybe not ideal for a minimal fix).

If that patch is _not_ enough for someone, they are probably out of luck.  The old code lead to bugs and it would need some very good use-case to back it out again fully.

**Comment by carterbox** [comment]
Actually, I'm dumb. I tested on Linux, but I only observed this problem on Windows/OSX. 🙄 Give me a few more minutes.

**Comment by carterbox** [comment]
OK. I tested on Windows with numpy==1.24.0.dev0+89.gc8de16e44. We're probably good (I didn't test on OSX) because I don't own a Mac.
