### ISSUE TITLE
BUG: fft shows error if norm = 'forward' or norm = 'backward' is used

### ISSUE THREAD

**Issue by tupaibasu2004** [numpy/numpy#21633]
### Describe the issue:

norm parameter of fft does not take any value other than None or ortho. Even scipy shows the same error.

### Reproduce the code example:

```python
import numpy as np
fq = 10; N, M = 5, 6
x = np.linspace(0, 2, N)
y = np.linspace(5, 9, M)
xx, yy = np.meshgrid(x, y)
fnc = np.sin(2 * np.pi * (10 * xx + 4 * yy))
# Windowing
winx, winy = np.hanning(N), np.hanning(M)
win2D = np.sqrt(np.outer(winy, winx))
ft = fft.fft2(fnc * win2D, norm="forward")
```

### Error message:

```shell
ValueError: Invalid norm value forward, should be None or "ortho".
```

### NumPy/Python version information:

numpy version 1.19.5

**Comment by WarrenWeckesser** [comment]
You are using NumPy 1.19.5.  The `"forward"` and `"backward"` options were added in NumPy 1.20.0.  This is noted in the description of the `norm` parameter in the [`fft` docstring](https://numpy.org/doc/stable/reference/generated/numpy.fft.fft.html), and in the [NumPy 1.20.0 release notes](https://numpy.org/doc/stable/release/1.20.0-notes.html#norm-backward-forward-keyword-options-for-numpy-fft-functions).
