### ISSUE TITLE
DOC: Broadcasting: last example is misleading, should raise an error

### ISSUE THREAD

**Issue by avm19** [numpy/numpy#21642]
### Issue with current documentation:

The last example in [Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) is confusing (scroll to the very bottom of that page):
```
Observation      (2d array):      10 x 3
Codes            (2d array):       5 x 3
Diff             (3d array):  5 x 10 x 3
```
Following the broadcasting rules, we check the dimensions from right to left. The second-to-last dimensions of `Observation` and `Codes` do not match, so I expect an error message (and it would indeed be raised, unless I am missing something). However, this example is presented as if it were a legit working example illustrating potential performance issues (see the docs to understand the context). I find this misleading.

### Idea or request for content:

Any non-working code or setting must be clearly marked. I suppose, the table should be corrected to read as follows:
```
Observation      (2d array):      10 x 3
Codes            (2d array):  5 x  1 x 3
Diff             (3d array):  5 x 10 x 3
```

**Comment by melissawm** [comment]
Thanks for noticing this @avm19 - do you want to submit a PR for this? 😄 

As a note, in the new example maybe it would be best to note that `codes` is now actually a 3d array.

**Comment by rohitdavas** [comment]
I have added a pull request for this. It is my first contribution. #21689 . I hope I had everything correct.

**Comment by avm19** [comment]
> Thanks for noticing this @avm19 - do you want to submit a PR for this? 😄

Apologies for missing the invitation. Luckily, it is all sorted out now.
