### ISSUE TITLE
ENH: memmap loading data question

### ISSUE THREAD

**Issue by JulesGranget** [numpy/numpy#21657]
### Proposed new feature or change:

I have a question/suggestion regarding the np.memmap function. I use it a lot for relieving my RAM, and notably I use it in scripts that run on the local cluster of my scientific facilities. This cluster is administrated with slurm which organizes on which node goes the job's script. I need to tell slurm which number of core and RAM I need for my job, and if I go up these limits my job gets killed. 

The problem is that scripts that use memmap and work on a local computer perfectly, do not work anymore on the cluster because memmap see an huge RAM on the node I am in when I am on the cluster, wants to load the whole matrix I am asking, and so slurm kills me job.

Hence I was wondering if there is a way to tell memmap to limit the size of data that it can open one by one. I did not find it on the documentation. And if it is not implemented maybe this remark could constitute a suggestion for the future ?

Thank you for your time !
Jules

**Comment by rkern** [comment]
You can memory-map parts of a file using `offset=` and `shape=`. At least on my Linux box, only the pages specified by that get accounted towards the process's virtual memory usage.
