### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by AdversityQuotientAN** [numpy/numpy#21678]
### Steps to reproduce:

Steps:
1. Opened **Command Prompt**
2. Executed command "pip3 install numpy"
3. Executed command "pip3 install scipy"

OS: Windows 10
NumPy version: 1.22.4
Python version: 3.9

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Engineering Probability\file.py", line 4, in <module>    
    import numpy as np
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\numpy\__init__.py", line 144, in <module>
    from . import core
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\user\AppData\Local\Programs\Python\Python39\python.exe"
  * The NumPy version is: "1.22.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Additional information:

Trying to run Python file using NumPy on VS Code.
Seems like the issue is with NumPy and not SciPy.

**Comment by mattip** [comment]
Which of the hints at https://numpy.org/devdocs/user/troubleshooting-importerror.html did you try?

**Comment by AdversityQuotientAN** [comment]
I tried following the hint pertaining to VSCode, but it kept talking about environments and interpreters and such that I wasn't sure how it was relevant to my situation. I feel like I just need to figure out where to put the numpy folder in, and I currently have it in my Python39 folder, although it's still giving me the "No module named 'numpy.core._multiarray_umath'" error.

**Comment by mattip** [comment]
I assume you obtained python from the windows app store.

You cannot copy around the numpy/scipy directories. There are support libraries installed with the package that will not be found if you simply copy. You should use `python -m pip`  instead of `pip3` since you may have more than one python installed on your machine. When you type `pip3 install numpy scipy`, it is not clear into which python environment you will install numpy and scipy. When you specify `python -m pip`, then there is less room for problems.

Try opening a command prompt and reinstalling numpy and scipy:
```
C:\Users\user\AppData\Local\Programs\Python\Python39\python.exe -m pip install --force-reinstall numpy scipy
```

**Comment by AdversityQuotientAN** [comment]
It works now, thank you so much!

**Comment by RohanBhat10** [comment]
Hi,

I am trying to deploy my python code which uses pandas in AWS lambda function. I am getting the same error, Original error was: No module named 'numpy.core._multiarray_umath'. The code runs in my local machine I have added the same packages to AWS layer but I still am getting the same error. I have alse tried installing numpy and pandas as suggested here, python.exe -m pip install --force-reinstall numpy pandas

It did install the latest package but it does not seem to work. Any help is much appreciated.

Thanks!!

**Comment by dipanshusheoran** [comment]
> Hi,
> 
> I am trying to deploy my python code which uses pandas in AWS lambda function. I am getting the same error, Original error was: No module named 'numpy.core._multiarray_umath'. The code runs in my local machine I have added the same packages to AWS layer but I still am getting the same error. I have alse tried installing numpy and pandas as suggested here, python.exe -m pip install --force-reinstall numpy pandas
> 
> It did install the latest package but it does not seem to work. Any help is much appreciated.
> 
> Thanks!!

Hi Rohan , I am working on the exact same project as you i.e. trying to deploy my code on AWS Lambda and getting the same error as you. Please let me know if yours is fixed. Thanks.

**Comment by RohanBhat10** [comment]
> Hi Rohan , I am working on the exact same project as you i.e. trying to deploy my code on AWS Lambda and getting the same error as you. Please let me know if yours is fixed. Thanks.

Hi @dipanshusheoran,

It was an issue with the version of the numpy I extracted when creating the lambda layers. You can download the appropriate version of numpy as per your python version you are using in AWS Lambda. You can go to the following link to download any package, https://pypi.org/project/numpy/#files. I used python 3.10 so I downloaded the following version, [numpy-1.25.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ] here cp310 means it is for 3.10 python version. You can download for yours accordingly.

I tried to attach the python package zip which I used in my lambda layers for python 3.10. After numpy issue gets resolved lambda throws error for lot of other packages which is needed for pandas module. You can provide me your email ID I will send you the package, you can use that by changing your python version to 3.10 in your lambda if not already used.

**Comment by tusharpari** [comment]
Hi @dipanshusheoran 
I have same use case, deploying my code on AWS Lambda, how you resolved this. problem, I am using python 3.10 and numpy 1.25.0, but facing same problem.

**Comment by the-real-henry** [comment]
Also here. @dipanshusheoran. I'm using python 3.11 runtime and numpy 1.24.4 on lambda (AWS Linux). The error is consistent with the original issue.

**Comment by yoyoyeahyoyo** [comment]
python3.10 numpy 1.26.2 can't load "numpy.core._multiarray_umath" in amazon-aws linux docker container.  Running from venv, similar to above recent issues. If I can just find the right C support library to manually compile or which folder to link that should fix it right? Tried install with no-binary and normal pip install, without any difference. In 'lib/python3.10/site-packages/numpy.libs', pip installed have: "libgfortran-040039e1.so.5.0.0, libquadmath-96973f99.so.0.0.0, libopenblas64_p-r0-0cf96a72.3.23.dev.so"

I'm guessing a linking error or a missing wrong version of one of these C libs.

**Comment by mattip** [comment]
This issue is closed. Please open a new issue rather than asking for help here, giving a reproducible workflow for the problem you are experiencing, after following all the hints at https://numpy.org/devdocs/user/troubleshooting-importerror.html
