### ISSUE TITLE
BUG: Segmentation fault for ufunc with output with wrong shape

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#21673]
### Describe the issue:

A strange bug in astropy - https://github.com/astropy/astropy/issues/13283 - boils down to the example below giving a segmentation fault. To trigger the bug, one of the two arguments need to be scalar; if one replaces with `[1.]` in the example, one gets the correct broadcasting error.

### Reproduce the code example:

```python
import numpy as np
np.add(1., [1., 2.], out=np.empty(()))
```

### Error message:

```shell
Segmentation fault
```

### NumPy/Python version information:

1.21.5 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
1.22.4 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]

According to https://github.com/astropy/astropy/issues/13283, the bug was introduced in numpy 1.21

**Comment by seberg** [comment]
Thanks for reporting.  I thought we don't reach the stride checks for 0-D inputs, maybe a confusion with changing code... @eendebakpt would you be up for following up on this, I suspect it is due to our changes.

The gdb traceback:
```
#0  0x00007ffff5a80091 in try_trivial_single_output_loop (context=context@entry=0x7fffffffa540, 
    op=op@entry=0x7fffffffa7e0, order=order@entry=NPY_KEEPORDER, arr_prep=arr_prep@entry=0x7fffffffaae0, 
    full_args=..., errormask=521, extobj=0x0) at numpy/core/src/umath/ufunc_object.c:1346
#1  0x00007ffff5a86eb8 in PyUFunc_GenericFunctionInternal (wheremask=0x0, full_args=..., 
    output_array_prepare=0x7fffffffaae0, order=NPY_KEEPORDER, casting=NPY_SAME_KIND_CASTING, extobj=0x0, 
    op=0x7fffffffa7e0, operation_descrs=0x7fffffffa9e0, ufuncimpl=<optimized out>, ufunc=<optimized out>)
    at numpy/core/src/umath/ufunc_object.c:2703
```

**Comment by seberg** [comment]
Sorry @eendebakpt I overread that this was already in 1.21, so it is much older than your changes :).

**Comment by mhvk** [comment]
A bit of further checking: the segmentation fault also only happens if the output is an array scalar. For `np.add(1., [1., 2.], out=np.empty((1,)))` one gets the (correct) broadcast error. So, to hit the bug, output needs to be an array scalar and one of the inputs also needs to be a scalar or array scalar.
