### ISSUE TITLE
BUG: Incorrect handling of not-equal comparison to nan

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#21685]
### Describe the issue:

For a sufficiently large array `x`, the comparison `x != 0` returns False for elements of `x` that are `nan`. The result should be True.  For example,
```
In [1]: import numpy as np

In [2]: x = np.zeros((4, 8))

In [3]: x[0,0] = np.nan

In [4]: x != 0  # The first element of the result should be True
Out[4]: 
array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [5]: x[:2] != 0  # The result with a smaller array works as expected.
Out[5]: 
array([[ True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

```
The bug appears to have been introduced in gh-21483.

### NumPy/Python version information:

```
In [6]: import sys, numpy; print(numpy.__version__, sys.version)
1.24.0.dev0+136.g15b92f7ab 3.10.1 (main, Jan 14 2022, 02:27:20) [GCC 11.2.0]
```

**Comment by seberg** [comment]
Ping @rafaelcfsousa, could you have a look, since it was likely your PR that introduced this?

**Comment by rafaelcfsousa** [comment]
Ok, I already know what exactly is causing this bug.

The comparison kernels implemented with AVX and AVX512 use the universal intrinsic `npyv_cmpneq_f64` (see below) to compute `np.not_equal` for `dtype=double`.
https://github.com/numpy/numpy/blob/15b92f7abc34dbae4d6ef881c8b4316961e47976/numpy/core/src/common/simd/avx2/operators.h#L212

The universal intrinsic `npyv_cmpneq_f64` for both SIMD extensions listed above uses the flag `_CMP_NEQ_OQ` to indicate how the comparison with NaN has to be done (more info here: https://stackoverflow.com/questions/16988199/how-to-choose-avx-compare-predicate-variants).

For _CMP_NEQ_OQ (Ordered comparisons returns false for NaN operands):
-  `nan` != `nan` --> `false`
-  `nan` != `0`      --> `false`

For _CMP_NEQ_US (Unordered comparison returns true for NaN operands):
- `nan` != `nan` --> `true`
- `nan` != `0`     --> `true`

**Comment by rafaelcfsousa** [comment]
In my point of view, we could follow one of the 4 options below to have this issue resolved:

1) Use _CMP_NEQ_UQ instead of _CMP_NEQ_OQ (but I do not know yet the impact of doing that)

2) Disable the optimization for AVX[2,512] so that SSE2 is used instead

3) Move the dtypes f32 and f64 to new dispatchable source (loops_comparison_fp.dispatch.c.src) and enable on it only SSE (and the other architectures)

4) Use scalar execution for AVX[2,512] when dtype=f32 or f64

**Comment by seberg** [comment]
Using `_CMP_NEQ_OQ` seems right to me on first sight, unless this is used in places where the unorderd version is needed (in which case, I guess we may need both universal intrinsics?)

**Comment by rafaelcfsousa** [comment]
@seberg and @charris :

I think we should use `_CMP_NEQ_UQ` instead of `_CMP_NEQ_OQ`.

```
>>> import numpy as np
>>> np.nan != np.nan
True
>>> np.nan != 0
True
```

The result when I compare anything with NaN values is True.

Btw, `npyv_cmpneq_f32` and `npyv_cmpneq_f64` are only used by `loops_comparison.dispatch.c.src`.

**Comment by seberg** [comment]
Sorry, yes.  I got the wrong intrinsic, I meant: I do think we should swap out the intrinsic used and that seems like it should be the right solution.  Are you planning on making a PR?

**Comment by rafaelcfsousa** [comment]
Yes, I will submit a PR. Give me ~1h and I will submit it (I will test the other comparison function as well).
