### ISSUE TITLE
BUG: Calling sort on a column vector returns the column as is, not sorted. 

### ISSUE THREAD

**Issue by mpcasey2718** [numpy/numpy#21683]
### Describe the issue:

On both linux with python 3.8 and mac with python 3.10, I have found that calling sort on arrays of shape (N,1) leaves the array as is, possibly as if the sorting was done on each row, or just not at all. Transposing the array and then calling sort, or explicitly flattening the array and then calling sort both produce the expected results. 

Sample code is below. The result of np.sort(column) is not sorted. Given that the documentation says that omitting the axis parameter will flatten the array, something appears to be off. I do not know if there is some "strange" behavior in flatten() that does not act on (N, 1) arrays. I suppose adding a transpose for that case would be a sufficient fix?

### Reproduce the code example:

```python
import numpy as np
from numpy.random import Generator, PCG64

rg = Generator(PCG64())

N = 10 
column = rg.standard_normal((N, 1))
print('The entries are', column, sep='\n')
print('')
row = column.T

sortedCol = np.sort(column)
print('The expected to be sorted column entries are', sortedCol, sep='\n')
print('')
sortedRow = np.sort(row)
print('The sorted row entries are', sortedRow, sep='\n')
print('')

# flatCol = np.asanyarray(column).flatten()
flatCol = column.flatten()
print('The flattened column entries are', flatCol, sep='\n')
sortedFlatCol = np.sort(flatCol)
print('')
print('The sorted flattened column entries are', sortedFlatCol, sep='\n')
print('')
print('The difference with the sorted row entries is', sortedFlatCol - sortedRow, sep='\n')
```

### NumPy/Python version information:

For the linux system:

1.21.4 3.8.2 (default, Jul  2 2020, 00:57:00)                                   
[GCC 9.2.0]

I shall need a few days to get the info for the Mac if needed, but python and numpy were installed just last week on that machine.

**Comment by seberg** [comment]
>  Given that the documentation says that omitting the axis parameter will flatten the array,

The documentation does not say this, it says:

    Axis along which to sort. If None, the array is flattened before
    sorting. **The default is -1**, which sorts along the last axis.

So yes, sorting `column` does nothing (except a copy).

**Comment by mpcasey2718** [comment]
Yes, I am sorry; reading the documentation again does show -1 as the default axis parameter. I just would have expected one-dimensional arrays to always be sorted when calling sort on them. The confusion may have arisen from other methods treating axis=None as the default; see argmin for example. I understand that -1 is at least a consistent expected choice for multidimensional arrays though.
