### ISSUE TITLE
BUG: memory leak with ndarray.tolist()

### ISSUE THREAD

**Issue by aamster** [numpy/numpy#21680]
### Describe the issue:

When I call `ndarray.tolist()` on an array in a loop I would expect the process's memory to stay static. However, the memory appears to grow each iteration.

![numpy_mem_leak](https://user-images.githubusercontent.com/5454341/172201261-18559cc6-9176-4f07-97dd-8f5f7d9ea41c.png)

### Reproduce the code example:

```python
import gc
import os

import numpy as np
import pandas as pd
import psutil
from sklearn.linear_model import LinearRegression

from matplotlib import pyplot as plt
import seaborn as sns
from tqdm import tqdm


def main():
    x = np.random.random((int(1e6), 10))

    mem = np.zeros(50)
    process = psutil.Process(os.getpid())

    for i in tqdm(range(50)):
        y = x.tolist()
        mem[i] = process.memory_info().rss

    res = pd.DataFrame(
        {'Memory usage': np.array(mem),
         'iteration': range(len(mem))
         })

    reg = LinearRegression()
    reg.fit(X=res['iteration'].values.reshape(-1, 1),
            y=res['Memory usage'])
    slope = reg.coef_[0]
    intercept = reg.intercept_

    sns.lineplot(data=res, x='iteration', y='Memory usage',
                 marker='o')
    plt.plot([0, res.shape[0]], [intercept, slope * res.shape[0] + intercept],
             color='red')
    plt.show()


if __name__ == '__main__':
    main()
    gc.collect()
    main()

```

### NumPy/Python version information:

```
1.21.5 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]
```

**Comment by aamster** [comment]
@seberg I updated the code to use static memory allocation instead of a list, but I still see the same pattern. I also tried what you suggested to run the same thing twice in one program, but the second call to `main` picks up where the previous left off. Here are the plots from running twice
![tolist1](https://user-images.githubusercontent.com/5454341/172212306-0b6fdc1e-fb78-4dbf-8496-5aee3d05a224.png)
![tolist2](https://user-images.githubusercontent.com/5454341/172212326-e486de91-8a78-427a-a9a4-799013adf9bc.png)

**Comment by seberg** [comment]
Maybe try adding an explicit `import gc; gc.collect()` in between runs (and run one more time).  I am not sure what is going on, but as I said, the memory pressure is much lower for me (although that might be a Python enhancement)

That call creates millions of Python floats (and lists!), if I run things many times, the same pattern (with only tiny increases) just repeats over and over.  There should not be any NumPy difference between Python versions.

**Comment by WarrenWeckesser** [comment]
FWIW: If I add `del y` immediately after `y = x.tolist()`, there is just one increase from `mem[0]` to `mem[1]`; the values `mem[1:]` are all the same (using the NumPy main branch `'1.24.0.dev0+133.gaeb2b2167'` and Python 3.10.1 on Linux).  Note: I removed the use of `tqdm`, so the loop is `for i in range(50):`.

**Comment by aamster** [comment]
@seberg @WarrenWeckesser ok I've convinced myself this is not a numpy issue. If I remove numpy completely and just read a big list from disk each iteration, I see the same monotonically increasing memory behavior. So this is not a numpy issue.
