### ISSUE TITLE
ENH: Replace x**1 with x in polynomials str representation

### ISSUE THREAD

**Issue by axil** [numpy/numpy#21695]
### Proposed new feature or change:

Currently the first degree of the indeterminate variable in polynomials is displayed as x**1:

``` python
>>> import numpy.polynomial as poly
>>> str(poly.Polynomial([1,2,3]))
'1.0 + 2.0·x¹ + 3.0·x²'
```

 Usually the first degree is not written. It is suggested to omit the degree for the term with the power of one:

``` python
>>> import numpy.polynomial as poly
>>> str(poly.Polynomial([1,2,3]))
'1.0 + 2.0·x + 3.0·x²'
```

In Latex representation it is displayed correctly, so there is nothing to be done:

![image](https://user-images.githubusercontent.com/170910/172674584-a89ade80-3d85-4449-90b4-16bd13c4e825.png)

Numpy version: master branch

**Comment by seberg** [comment]
This change was included in gh-21654.  Closing.
