### ISSUE TITLE
BUG: tolist() significantly slower than list comprehension

### ISSUE THREAD

**Issue by aamster** [numpy/numpy#21702]
### Describe the issue:

It appears that `tolist()` is significantly slower than converting to list via a list comprehension. I'm not sure what is going on under the hood of `tolist()` but it is surprising that these would perform much different.

### Reproduce the code example:

```python
import numpy as np

t = np.random.random((1101, 140792))

%%time
l = t.tolist()
"""
CPU times: user 5.47 s, sys: 6.72 s, total: 12.2 s
Wall time: 15.9 s
"""

%%time
l = [x for x in t]
"""
CPU times: user 2.06 s, sys: 1.1 s, total: 3.15 s
Wall time: 3.16 s
"""
```
```


### Error message:

_No response_

### NumPy/Python version information:

1.21.4 3.8.0 (default, Nov  6 2019, 15:49:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by seberg** [comment]
The speed is different because the two things do very different things. `tolist()` is recursive (down to converting the elements to native Python builtins if possible).

**Comment by aamster** [comment]
Thanks @seberg that makes sense.
