### ISSUE TITLE
BUG: np.finfo(float).eps does not influence inequality

### ISSUE THREAD

**Issue by WJ-Huang** [numpy/numpy#21724]
### Describe the issue:

When I compare a number (for example, 40.0) with it minus `eps`, they are equal. 
`np.equal(40.0 - np.finfo(float).eps, 40.0)` returns `True`

### Reproduce the code example:

```python
import numpy as np
np.equal(40.0 - np.finfo(float).eps, 40.0)
40.0 - np.finfo(float).eps == 40.0
```

### NumPy/Python version information:

Numpy 1.21.5 
Python 3.9.7

**Comment by rkern** [comment]
This is expected. The spacing between adjacent floating point numbers grows as the magnitude of the numbers grow. `eps` is defined as the smallest number which added to `1.0` yields a different floating point number. The spacing between `40.0` and the floating point number just before it is larger than `eps`. Subtracting `eps` from `40.0` rounds back to `40.0`.

You can use the `nextafter()` ufunc to explore these spacings.

```
|7> 40.0 - np.nextafter(40.0, -np.inf), np.finfo(float).eps                                                                                                                                                          
(7.105427357601002e-15, 2.220446049250313e-16)
```

The spacing between `40.0` and the the floating point number just before it is 32x the size of `eps`.
