### ISSUE TITLE
ENH: Support for float64 for linalg

### ISSUE THREAD

**Issue by Why-not-now** [numpy/numpy#21736]
### Proposed new feature or change:

The linalg module currently only supports up to float32 from my understanding, however python's default float is float64, thus it is inconvenient to use the linalg module

**Comment by mattip** [comment]
Could you give an example of what you mean, and where you found documentation about linalg being `float32`-only? As far as I know the OpenBLAS routines NumPy uses all support `float64` (`double`), but maybe there is some other BLAS implementation that is restricted to `float32`?

**Comment by Why-not-now** [comment]
Hmm I think I found the error, sorry for the trouble. Basically, on windows, np.longdouble is float64, and thus I thought I could have substituted with double. This was further reinforced by this error.
`TypeError: array type float64 is unsupported in linalg`

Just switched all my data type to double, thanks for the help.
