### ISSUE TITLE
BUG: random number generation problem on numpy.random.uniform

### ISSUE THREAD

**Issue by mgolmahi** [numpy/numpy#21740]
### Describe the issue:

Sometimes the random function of NumPy produces one digit random numbers for all the output array!

### Reproduce the code example:

```python
import numpy

x = numpy.random.uniform(0.0, 100.0, 100)

print(x)
```

### Error message:

```shell
(Note: The code example must be executed several times to produce the incorrect output)

[7.62307672e+01 8.63945282e+01 8.54908590e+01 4.18882162e+00
 6.35815573e+01 6.43555872e+01 7.29339642e+01 2.26660800e+01
 7.92597227e+01 9.71293555e+01 4.44266069e+01 7.58510137e+01
 4.31317442e+01 8.05411583e+01 1.57571885e+01 6.33812654e+01
 6.06543012e+01 1.29055661e+01 1.80588577e+01 9.16155688e+01
 9.36068523e+01 7.93893686e+01 9.80710036e+01 9.61360286e+01
 6.99269116e+01 8.66660591e+00 8.75284417e+00 9.65755623e+01
 8.98829794e+01 3.61783167e+01 3.72917823e+01 5.75947735e+01
 4.15128488e+01 7.15565872e+01 8.97155203e+01 2.11127448e+01
 7.32344189e+01 9.50831045e+01 5.92796441e+01 9.67227185e+01
 4.24729371e+01 5.48231537e+01 6.87170557e+01 7.14499290e+01
 5.56554449e+01 8.29822426e+01 2.96484342e+00 9.82879039e+01
 5.07491204e+01 6.48988416e+01 3.42531309e+01 8.48837562e+01
 9.66282334e+01 2.57520855e+01 6.73890618e+01 1.47533554e+01
 2.08661019e+01 1.12356288e+01 5.25453849e+01 6.29881392e+01
 3.46688435e+01 7.47379391e+01 9.10365956e+01 6.90349672e+00
 4.89790077e-02 4.65008469e+01 5.86182485e+01 6.07324755e+01
 9.38599485e+01 4.76298555e+01 9.98088281e+01 1.96326439e+01
 3.44245155e+01 7.22772728e+01 7.97929539e+01 4.50241112e+01
 6.26566499e+01 4.79076208e+01 7.23944328e+00 8.35719132e+01
 9.06152807e+01 2.28548981e+01 4.74215334e+01 1.47615492e+00
 6.66231954e+01 1.65903026e+01 3.16619531e+01 9.21163710e+01
 3.03350135e+01 8.23514204e+01 4.18972872e+01 5.39236041e+01
 8.75591667e+01 7.90636366e+01 3.81060495e+01 6.18227495e+01
 7.53717560e+01 2.08434897e+01 4.77175942e+01 8.13737850e+00]
```

### NumPy/Python version information:

64-bit Windows 10, Python 3.10.4, NumPy 1.22.4

**Comment by seberg** [comment]
Going to close.  I suspect that it was just a bit of a stumble over the floating point formatting: `7.62307672e+01` meaning `7.62307672 * 10**1` which is `76.2307672...`.

**Comment by mgolmahi** [comment]
> I suspect that it was just a bit of a stumble over the floating point formatting

But other code execution cycles that export the output correctly use the same formatting naturally!

**Comment by mgolmahi** [comment]
> Please explain more what is wrong with this random uniform sample of 100 numbers between 0 and 100. What exactly do you mean by "one digit random numbers"? You might want to re-use the histogram plotting code at the end of the [documentation](https://numpy.org/devdocs/reference/random/generated/numpy.random.uniform.html) to describe the problem.

The number of occurrences of single-digit arrays increases In the long run agains two, three etc arrays.
In fact, this function periodically follows a pattern that violates the random concept.

**Comment by seberg** [comment]
@mgolmahi the reason why you see this "weird" output sometimes is due to *small* numbers being included in the array.  For example in your example above, the number: `4.89790077e-02` which is `0.048979...`.  Because of that NumPy decides to change how the output is **printed**/**formatted**.

**Comment by mgolmahi** [comment]
> @mgolmahi the reason why you see this "weird" output sometimes is due to _small_ numbers being included in the array. For example in your example above, the number: `4.89790077e-02` which is `0.048979...`. Because of that NumPy decides to change how the output is **printed**/**formatted**.

Ok, Thanks. I look old :)
