### ISSUE TITLE
BUG: float16 to datetime/timedelta goes via undefined behavior for NaNs

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#21762]
### Describe the issue:

When converting a float array to datetime/timedelta, NaNs should be converted to NaT (minimum integer).  On many platforms, that is just what happens, however, this is undefined behavior.

This was fixed by gh-14669.  But that PR is missing a fix for `float16 -> datetime/timedelta` casts.  Most platforms are fine, since the weirder behavior typically only gets triggered by SIMD instructions, and we won't use those when half is involved

(xref gh-13917 for the old issue about this)

### Reproduce the code example:

```python
import numpy as np

# the following invokes undefined behavior and should fail to return
# an all NaT array on some platforms:
arr = np.array([np.nan] * 5, dtype=np.float16).astype("m8[s]")
assert np.isnat(arr).all()
```

EDIT: This **can** actually be tested on NumPy main now on most platforms, because it will give an "invalid value" warning.  The correct code would not give such warning.

**Comment by Siddhesh-Agarwal** [comment]
Also, to make matters a bit insane, the `isnan` function still returns `True`
```py
>>> import numpy as np
>>> arr = np.array([np.nan] * 5, dtype='float16').astype("m8[s]")
>>> np.isnat(arr).all()
True
>>> np.isnan(arr).all()
True
```
I don't think it is possible to have both `NaN` and `NaT` types simultaneously

**Comment by Siddhesh-Agarwal** [comment]
> That is a feature, not a bug.

That wass exactly my initial thought but the `00-bug` tag made me feel I was wrong.

**Comment by seberg** [comment]
@Siddhesh-Agarwal the bug is platform dependent.  The *first* line is the problem.  But unless you use the very latest `main` branch, you won't notice the warning I mentioned (which should not happen).  And unless you are on very specific hardware, the `assert` will not fail.
