### ISSUE TITLE
Numpy building error: gcc: build/src.linux-x86_64-3.10/numpy/core/src/umath/loops.c

### ISSUE THREAD

**Issue by Mocchaso** [numpy/numpy#21806]
I'm trying to install Numpy v1.22.4 via `pip`, next via compiling source code.  
I encountered below error when I executed `$ python setup.py build`.

```
error: Command "gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -DNO_ATLAS_INFO=-1 -Ibuild/src.linux-x86_64-3.10/numpy/core/src/common -Ibuild/src.linux-x86_64-3.10/numpy/core/src/umath -Inumpy/core/include -Ibuild/src.linux-x86_64-3.10/numpy/core/include/numpy -Ibuild/src.linux-x86_64-3.10/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/var/www/project/my-product/.venv/include -I/usr/local/include/python3.10 -Ibuild/src.linux-x86_64-3.10/numpy/core/src/common -Ibuild/src.linux-x86_64-3.10/numpy/core/src/npymath -c build/src.linux-x86_64-3.10/numpy/core/src/umath/loops.c -o build/temp.linux-x86_64-cpython-310/build/src.linux-x86_64-3.10/numpy/core/src/umath/loops.o -MMD -MF build/temp.linux-x86_64-cpython-310/build/src.linux-x86_64-3.10/numpy/core/src/umath/loops.o.d -msse -msse2 -msse3" failed with exit status 1
```

<br>

I recently posted a question about this error on StackOverflow.  
*Ref: https://stackoverflow.com/questions/72518989/numpy-building-error-gcc-build-src-linux-x86-64-3-10-numpy-core-src-umath-loop  
*`The things I tried`, `My development environment information`, `Commands I executed` are described on this question.

I received the following comment there.
```
Ok, so your processor does not support AVX-512 (but it support AVX-2 so it would be a good idea to add it using -mavx2 compilation flag). This means that something is built with the support of AVX-512 and then the GCC assembler complains because it is unexpected (the compiler generated AVX-512 assembly instructions). Assuming the problem does not comes from Numpy (the 1.22.4 should be quite stable now), it may be due to a dependent library compiled with AVX-512 (eg. glibc, libm, etc.), some bad old files compiled for AVX-512 that are still in a cache, etc. Hard to say more about this.
```

I'm continuing my investigation in accordance with above comment, but I cannot find out how to investigate about this.

Could you please tell me how to investigate about this error and AVX-512?
 
# Remarks

* Entire execution log of `$ python setup.py build`: [build_log.txt](https://github.com/numpy/numpy/files/8948807/build_log.txt)  
*I extracted this log by executing `$ python setup.py build 2>&1 | tee build_log.txt`
* Then I executed the following commands, but all with almost identical results.
  * Cleaning caches.
    ```
    $ sudo yum clean all
    $ pip cache purge
    ```
  * Changing arguments of `$ python setup.py build`.  
  Ref: https://numpy.org/devdocs/reference/simd/build-options.html
    ```
    $ python setup.py build --cpu-baseline="avx2 fma3" install --user
    
    $ python setup.py build --cpu-baseline="native" bdist
    $ python setup.py build --cpu-baseline=native --cpu-dispatch=none bdist
    $ python setup.py build --cpu-baseline="avx f16c" bdist
    
    $ python setup.py build --cpu-baseline="vsx2" bdist
    
    
    $ python setup.py build --cpu-dispatch="max -avx512f -avx512cd \
    -avx512_knl -avx512_knm -avx512_skx -avx512_clx -avx512_cnl -avx512_icl" \
    bdist
    
    $ NPY_DISABLE_SVML=1 python setup.py build --cpu-dispatch="max -avx512f -avx512cd \
    -avx512_knl -avx512_knm -avx512_skx -avx512_clx -avx512_cnl -avx512_icl" bdist
    
    $ python setup.py build --cpu-baseline="native" --cpu-dispatch="none"
    ```

**Comment by seiko2plus** [comment]
please, could you provides a fresh build log rather than rebuild log.  You can clean the repo via `git clean -xdf` or remove the dir `numpy/build since:
```Bash
INFO: customize UnixCCompiler using new_build_clib
INFO: CCompilerOpt.__init__[781] : load cache from file -> /home/vagrant/src/numpy/build/temp.linux-x86_64-cpython-310/ccompiler_opt_cache_clib.py
INFO: CCompilerOpt.__init__[792] : hit the file cache
```

This error isn't related to your CPU but to the assembler(as), compiler reports the support of `AVX512` but your assembler is not. in other words, you're using a new compiler that doesn't fit the assembler you have. According to the optimization log:

```Bash
########### EXT COMPILER OPTIMIZATION ###########
INFO: Platform      : 
  Architecture: x64
  Compiler    : gcc

CPU baseline  : 
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : -msse -msse2 -msse3
  Extra checks: none

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3
  Generated   : 
              : 
  SSE41       : SSE SSE2 SSE3 SSSE3
  Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1
  Extra checks: none
  Detect      : SSE SSE2 SSE3 SSSE3 SSE41
              : build/src.linux-x86_64-3.10/numpy/core/src/umath/loops_arithmetic.dispatch.c
              : build/src.linux-x86_64-3.10/numpy/core/src/umath/loops_unary_fp.dispatch.c
INFO: CCompilerOpt.cache_flush[825] : write cache to path -> /home/vagrant/src/numpy/build/temp.linux-x86_64-cpython-310/ccompiler_opt_cache_ext.py
```

Your build environment doesn't support `AVX512`  and `AVX2`, however its seems our legacy SIMD code may involved since its doesn't use our newest CPU/dispatch (--cpu-baseline/--cpu-dispatch) mechanism which guard against such assembler errors. upgrading your assembler through the package `Binutils` or using the default repo compiler should pass this build error.

**Comment by Mocchaso** [comment]
@seiko2plus Thank you for replying.

I executed `git clean -xdf`, `python setup.py build 2>&1 | tee build_log.txt`,  
then I extracted a fresh build log: [build_log.txt](https://github.com/numpy/numpy/files/8953054/build_log.txt)
*I'm sorry for a bit mixed Japanese in this log file.

**Comment by rgommers** [comment]
Looks to me like @seiko2plus's explanation above is complete.

The SO post says:
```
Installing gcc v9.5.0, plus v11.3.0.
*Separately from default gcc (v4.4.7).
*I used contrib/download_prerequisites when I installed gcc v11.3.0.
```
So probably it's somehow mixing two of those versions, newer compiler with older assembler.

> however its seems our legacy SIMD code may involved since its doesn't use our newest CPU/dispatch (--cpu-baseline/--cpu-dispatch) mechanism which guard against such assembler errors

Given that this is more robust in `main` than in `1.22.4`, I think we can close this.

**Comment by Mocchaso** [comment]
It seems that [I need at least gcc 11.2, for -O3](https://github.com/numpy/numpy/issues/21075#issuecomment-1047976197 ), then I upgraded GNU assembler with Binutils 2.38 package.  
I could solve my problem by the upgrading.
Thank you so much for helping!
