### ISSUE TITLE
ENH: hot-swapping a BitGenerator

### ISSUE THREAD

**Issue by rkern** [numpy/numpy#21808]
### Proposed new feature or change:

One of the requirements in [NEP 19](https://numpy.org/neps/nep-0019-rng-policy.html#numpy-random) was

> In order to allow certain workarounds, it MUST be possible to replace the BitGenerator underneath the global RandomState with any other BitGenerator object (we leave the precise API details up to the new subsystem).

We partially overlooked this in the hectic flood of new features that we implemented. IIRC, I did successfully insist on making the `_bit_generator` attribute `cdef public` rather than `cdef readonly`, but failed to communicate the full intended use, so it's not really functional.

As people are transitioning away from the `np.random.*` global functions, they may need a transition where they are using code, especially third-party code that they can't change, that still uses the `np.random.*` functions. We want to give them the ability to use a single `BitGenerator` instance shared between their `Generator`-using newer code and the `np.random.*`-using older code. That way, they don't have to manage two different seeds to get reproducible results.

Currently, we can create a new `RandomState` with one of the newer `BitGenerator`s, but we can't change the `BitGenerator` underneath the pre-created global instance `np.random.mtrand._rand`. So I would like to be able to write code that looks like this:

```python
def synch_legacy_randomstate(rng):
    np.random.mtrand._rand._bit_generator = rng.bit_generator

rng = np.random.default_rng(one_single_seed)
synch_legacy_randomstate(rng)

# newer code
rng.uniform(100)
# older code
np.random.uniform(100)
```

The `_bit_generator` attribute is `cdef public`, so we can technically assign a new `BitGenerator` to it, but this is essentially a no-op because the `bitgen_t *` is extracted from the `BitGenerator` object only in the `__init__()`. After re-assigning `_bit_generator`, all of the distribution methods still draw from the old `bitgen_t *`.

We can probably implement this by lifting the `cdef public _bit_generator` attribute to a property and factoring out the `bitgen_t *` extraction so that it can be used in both the `__init__()` and the setter.

@bashtage Any thoughts?

**Comment by rkern** [comment]
@bashtage Any thoughts?

(Apologies if you get this twice. Mistyped your handle in the original draft above, and I don't know if Github sends notifications on edits.)

**Comment by rkern** [comment]
We want this transitional hack to be more forward-focused rather than backwards-focused. So using `np.random.default_rng(seed)` (with a high-quality seed) to derive the `BitGenerator` that is then punched into the global `RandomState`. The other way forces people to use `np.random.seed(seed)` (forcing a low-quality 32-bit seed) and force the suboptimal choice of `MT19937` even in the `Generator`-using code.

**Comment by mhvk** [comment]
In astropy, we have had an (aborted) attempt to start allowing users to pass in random number generators to the (few) functions where we use them (see https://github.com/astropy/astropy/pull/12669). I worried this might not be very useful, since astropy underlies quite a lot of intermediate library code and there is no guarantee that code will also allows passing things on. So, I advocated some context manager or so. If the generator underneath the standard functions becomes hot-swappable, this all becomes far easier without much need for code change at all! (Indeed, perhaps a context manager is a good addition?)

**Comment by rkern** [comment]
I don't think this will help you very much in that case. This is mostly for the case of newer programs that wants to do things with the new (and I will argue better) infrastructure but using older libraries that have not yet been converted. The case you are talking about is flipped: you are the library that wants to upgrade but still being called by legacy-style code from the outside. It's only the outer code that can make use of this proposed functionality, but if it's not changing anyways, it's not going to change to use this either. As a library that wants to upgrade to the new infrastructure, you need a different pattern.

Even with the old infrastructure, we've always recommended passing around `RandomState` objects and not relying the `np.random.*` functions with the implicit global. `scikit-learn` and `scipy` use a function named `check_random_state()` to coerce arguments to a `RandomState`. The argument might be a seed or another `RandomState` or `None`, in which case the global is used. This is a flexible pattern for libraries that might have multiple entrypoints across its API surface.

`default_rng()` was written to perform much the same purpose. It will coerce a seed or pass through a given `Generator`. The major difference is that when given `None`, we will create a fresh `Generator` from OS entropy because we will not be adding a new global RNG state in the new infrastructure. _But_, if you are a library specifically concerned about being used from legacy-style programs that use `np.random.seed()` to get pseudorandom determinism, then you can implement your coercion function differently. For example:

```python
def check_rng(rng=None):
    if rng is None:
        # Grab the BitGenerator from the global RandomState to support legacy applications.
        # I bless the use of private attributes for this purpose.
        bg = np.random.mtrand._rand._bit_generator
        rng = np.random.Generator(bg)
    elif isinstance(rng, np.random.RandomState):
        bg = rng._bit_generator
        rng = np.random.Generator(bg)
    else:
        rng = np.random.default_rng(rng)
    return rng

def uniform_spherical_random_surface(size=1, rng=None):
    rng = check_rng(rng)
    ...
```

So legacy-style code that relied on being able to control the PRNG with `np.random.seed()` at the top can still do so, while users that are using `Generator` (or passing around `RandomState`s still) can also do so. And in either case, you can modernize completely. Everyone has agency to make upgrades at their own pace.

**Comment by mhvk** [comment]
Thanks!  That makes sense. My worry would be about intermediate code that calls `uniform_spherical...` (or any relevant `scipy` routine) without knowing about the `rng` argument. For that case, the ability proposed here to set the global `RandomState` would seem to provide the only way for a user to control what happens. And then I thought this (or a similarly working context manager) might actually be a better way to tell underlying code what random number generator to use.

I should perhaps add that in part this is because of a package I wrote myself which includes a lot of Fourier transforms. Initially, I had implemented the ability to pass on an FFT engine to functions, but I found that this was really cumbersome; it works much better by setting the FFT engine as some global state. But I realize that a random number generator carries state, which may mean it has additional constraints.

**Comment by rkern** [comment]
Yeah, there's a big difference between global _settings_ and constantly-changing global _state_. Both have similar _kinds_ of issues, but the latter case magnifies them because _every_ call is changing the state. Having a context manager that swaps in a `BitGenerator` into the global isn't the pattern that I want to promote. It doesn't solve a lot of the problems that passing around instances does, like multithreading. It still leaves you with the constraints of the legacy API just with another layer of complexity.

The `check_rng()` implementation I gave is the best transitional pattern that I can think of for your case. It's moving in the direction of better patterns while still preserving the ability to use the legacy global if necessary. To make the _best_ use of it does require changing how one calls the function, but it's still adequate if they don't.

**Comment by rkern** [comment]
NEP 19:

> Calling `numpy.random.seed()` thereafter SHOULD just pass the given seed to the current BitGenerator object and not attempt to reset the BitGenerator to the Mersenne Twister.

**Comment by bashtage** [comment]
The issue is the BitGenerators don't support seeding.

**Comment by rkern** [comment]
That's fine. `np.random.seed()` can implement it itself easily enough.

```python
def seed(seed=None):
    rs = np.random.mtrand._rand
    bg = rs._bit_generator
    bg_type = type(bg)
    if bg_type is MT19937:
        # Legacy seeding.
        rs.seed(seed)
    else:
        # Other BitGenerators don't have explicit reseeding, so we instantiate a new BitGenerator
        # with the given seed object and copy over its state.
        # Probably issue a warning here, at least.
        bg.state = bg_type(seed).state
```
