### ISSUE TITLE
Anaconda uploads broken.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#21816]
Just a note, the error is
```
Collecting git+https://github.com/Anaconda-Server/anaconda-client
  Cloning https://github.com/Anaconda-Server/anaconda-client to /tmp/pip-req-build-pbopy05f
  Running command git clone --filter=blob:none --quiet https://github.com/Anaconda-Server/anaconda-client /tmp/pip-req-build-pbopy05f
  Resolved https://github.com/Anaconda-Server/anaconda-client to commit 247f94f77078b075cfa0456c69fc49655f3cfdc9
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting clyent>=1.2.0
  Downloading clyent-1.2.1.tar.gz (20 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
ERROR: Could not find a version that satisfies the requirement conda-package-handling>=1.7.3 (from anaconda-client) (from versions: none)
ERROR: No matching distribution found for conda-package-handling>=1.7.3
Error: Process completed with exit code 1.
```
I suspect a network outage of some sort, there is no recent updates.

**Comment by charris** [comment]
Still broken 6/22/2022.

**Comment by charris** [comment]
Looks like the correct fix is to move to a conda install of `anaconda-client`. The pinning is OK for the 1.23.0 release, but main should be fixed.

**Comment by frgfm** [comment]
Hello :wave: 

Thanks for all your work! I just noticed the 1.23.0 is out on pypi & Github, but not on conda. I understand there was an issue with the automatic release process, but it looks like some issues have been fixed?

Do you have any idea where the 1.23.0 will make its way to conda? :pray: 

Cheers :v:

**Comment by seberg** [comment]
@frgfm this is not about availability in the anaconda distribution or conda-forge. For what its worth, conda-forge already seems to have it: https://anaconda.org/conda-forge/numpy
