### ISSUE TITLE
DOC: Translate documentation into different languages

### ISSUE THREAD

**Issue by GabrielaMarangoni** [numpy/numpy#21818]
### Issue with current documentation:

Do not have documents translated

### Idea or request for content:

Not all developers speak English, so I think it would be interesting to have a translation for better understanding.

**Comment by seberg** [comment]
The website should be translated (I am not quite sure what the status is there).  The documentation is not really planned because it would be a massive undertaking, unfortunately.

**Comment by melissawm** [comment]
Thanks for reporting @GabrielaMarangoni . This is certainly an issue, but unfortunately we don't have the resources to maintain a full translation of the entire documentation into multiple languages at this time. Please check out the website translation issue mentioned above, and let us know if you have other ideas 😄
