### ISSUE TITLE
DOC: anomality on numpy.random index page

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy#21831]
### Issue with current documentation:

While working on creating a list/table for the numpy.random package in Draft PR #21820.

I noticed this anomality

![query](https://user-images.githubusercontent.com/41142068/175240293-7eb5e433-e18f-43f5-a4aa-4c2c945e0424.PNG)

On the left pane all the methods are listed such as
- numpy.random.Generator.bit_Generator
- numpy.random.Generator.integers

but when moved on to the examples its usage if always like this 

1) `np.random.default_rng()` => Initiate the recommended Interface
2) use the desired methods

Query - Does it make sense for the left navigation panel to also reflect the recommended interface i.e 
`np.random.default_rng()` while searching for methods.

I am aware, that the headings are autogenerated by sphinx in correspondence to how the methods are defined, but is it a valid point to be considered?

**Comment by rossbar** [comment]
This is typically how class methods are listed via `autosummary` so it is consistent with other class documentation. There could be an argument for maybe removing the `numpy.random` prefix from the listed methods in the sidebar to potentially make things more readable, but I don't think it makes sense to mention the convenience method `default_rng` for the methods in the side bar --- after all, `Generator` is a generic interface whereas `default_rng` gives a generator instance with a specific `BitGenerator`

**Comment by rkern** [comment]
Similarly, we list all of the `ndarray` methods as `numpy.ndarray.*` there though almost no-one actually uses the `numpy.ndarray` constructor directly. `numpy.ndarray` and `numpy.random.Generator` are the types those methods are on; the other functions that usually construct those types aren't the types.
