### ISSUE TITLE
BUG: lib: `loadtxt` treats `usecols=''` the same as `usecols=[]`.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#21839]
### Describe the issue:

Passing `usecols=''` to `loadtxt()` should raise a TypeError, but instead the empty string is treated the same as `usecols=[]`.

For example,

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.24.0.dev0+361.g3039cd3a9'

In [3]: from io import StringIO

In [4]: np.loadtxt(StringIO('1 2 3\n4 5 6\n'), usecols='')
Out[4]: array([], shape=(2, 0), dtype=float64)
```

I ran into this while working on https://github.com/numpy/numpy/pull/21800.  I'll include a fix there.

### NumPy/Python version information:

1.24.0.dev0+361.g3039cd3a9 3.10.1 (main, Jan 14 2022, 02:27:20) [GCC 11.2.0]

**Comment by WarrenWeckesser** [comment]
Yeah, I'd call it an old bug.  Not a high priority, but now that I see it, and I'm already working on updates to `loadtxt`, it will bother me if I don't fix it. :grin:

**Comment by seberg** [comment]
My main point is that you can do the same thing in a lot of places I am sure.  For example `np.zeros("")` works fine too.  I am not sure I really feel like fixing it, since I bet this is super universal, also for example `sum("")`.
