### ISSUE TITLE
v1.23.0: np.delete casts length-1 boolean masks to integer indices

### ISSUE THREAD

**Issue by jakevdp** [numpy/numpy#21840]
Repro:
```python
import numpy as np

x = np.ones((3, 1))
false_mask = np.array([False], dtype=bool)
true_mask = np.array([True], dtype=bool)
print(np.__version__)
print(repr(np.delete(x, false_mask, axis=-1)))
print(repr(np.delete(x, true_mask, axis=-1)))
```
Result on numpy 1.22.4:
```python
1.22.4
array([[1.],
       [1.],
       [1.]])
array([], shape=(3, 0), dtype=float64)
```
Result on numpy 1.23.0:
```
1.23.0
array([], shape=(3, 0), dtype=float64)
Traceback (most recent call last):
  File "tmp.py", line 8, in <module>
    print(repr(np.delete(x, true_mask, axis=-1)))
  File "<__array_function__ internals>", line 180, in delete
  File "/Users/vanderplas/.local/share/virtualenvs/jax-LBbfM5ix/lib/python3.8/site-packages/numpy/lib/function_base.py", line 5152, in delete
    raise IndexError(
IndexError: index 1 is out of bounds for axis 1 with size 1
```
The CHANGELOG mentions [changes to `np.delete`](https://numpy.org/doc/stable/release/1.19.0-notes.html#numpy-delete-no-longer-casts-boolean-indices-to-integers) in version 1.23.0, but this seems like an unintended change: explicit boolean mask arrays are being implicitly converted to integer in v1.23.0. Moreover, this only seems to affect boolean arrays of length-1: if the mask array is length 2 or more, it is treated correctly.

**Comment by seberg** [comment]
This is certainly due to gh-16895.  If in doubt, we should just revert it, the checks for boolean arrays look shady to me.
