### ISSUE TITLE
DOC: changes to `loadtxt` in numpy v1.23.0

### ISSUE THREAD

**Issue by pranabdas** [numpy/numpy#21852]
### Issue with current documentation:

As noted [here](https://numpy.org/doc/stable/release/1.23.0-notes.html#np-loadtxt-has-recieved-several-changes), now `np.loadtxt` ignores empty lines towards `max_rows`. This includes comment lines (e.g., lines starting with `#`) as well, previously which was not the case and not mentioned in the release notes. Is this breaking change intended? Thank you.

**Comment by seberg** [comment]
Yeah, thw intention was that max rows actually dmsays how much the result will have. So empty as in no data, which could be clarified.

**Comment by charris** [comment]
The previous behavior might be better because it is easier to just count lines of all types in the input data, I suppose it can be argued either way.

**Comment by seberg** [comment]
Yeah, the new meaning allows to say how big the result is, but the "read until this line in the file" meaninig also makes sense if you first manually browsed the file (There is a subtlety that in theory a field could include a newline now, though).  I somewhat tend to this one, because `lines` would be a better name for the other one.  OTOH, its not a strong opinion!

**Comment by charris** [comment]
> because lines would be a better name for the other one.

Is there a lines argument? I can see the point of not confusing lines and (data) rows. But not changing behavior between different NumPy versions could be hard to deal with downstream.

**Comment by seberg** [comment]
No, but there is a warning which explains how to get the old behavior using `itertools.islice`.  There could be a `read_lines`, the other confusion is that `skiprows` actually skips lines.
Ideally, skiprows should maybe be renamed to `skiplines` and we could have a new kwarg to do `read_lines` that has the `itertools.islice` like meaning.

**Comment by pranabdas** [comment]
A new `read_lines` **kwarg** would be helpful. In my particular case, the data size is not predefined (it varies from scan to scan, how long the scan ran, how fine/coarse the scan is set to etc.). Also, data file may contain indefinite number of comment lines (such as, when the scan got interrupted, aborted by the user, and later got restarted etc.). Previously, I could just look for the line number of particular comment line to read what I need, now that is not possible (with `loadtxt`).

**Comment by seberg** [comment]
Ping @WarrenWeckesser maybe you have an opinion on considering to just revert it?  The one tricky thing with providing a `read_lines` kwarg, is addding support for counting lines that are embedded into a row (this is possible with string quoting in CSV now).

**Comment by seberg** [comment]
(Just as another reference `pandas.read_csv` has `nrows`, which has the same logic (not based on the actual number of lines, but based on the number of rows the result will hold).

**Comment by mattip** [comment]
The [mailing list thread](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/YJS73ZRCURXBVS66X4GPKNDQKNMOOOHM/) did not generate any responses. A PR to document the new behaviour was merged. I think we can close this?

**Comment by pranabdas** [comment]
@mattip my actual issue was addressed. You may close it. However, I am not sure if other members want to keep it open to further discuss `max_rows` behavior or implement another keyword. Thank you.

**Comment by mattip** [comment]
Let's close this. If someone wants to further discuss `max_rows` they should open an new issue, and refer back to the salient points from this one.
