### ISSUE TITLE
DOC: document need to define API version to avoid deprecation warning from ndarrayobject.h

### ISSUE THREAD

**Issue by jwuttke** [numpy/numpy#21865]
### Describe the issue:

To make use of function [PyArray_SimpleNew](https://numpy.org/devdocs/reference/c-api/array.html#c.PyArray_SimpleNew), [I guess](https://github.com/numpy/numpy/issues/21864) we need `#include <numpy/ndarrayobject.h>`. However, as soon as that file is included, I get a deprecation warning
```
In file included from /usr/include/python3.10/numpy/ndarraytypes.h:1969,
                 from /usr/include/python3.10/numpy/ndarrayobject.h:12,
                 from ../src.cpp:1:
/usr/include/python3.10/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
```

### Reproduce the code example:

To reproduce, have a src.cpp with a single line,

```C
#include <numpy/ndarrayobject.h>
```
and compile.

### NumPy/Python version information:

1.21.5 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0]

**Comment by jwuttke** [comment]
Sorry, I don't get the logic of this. I want to use a function from the current stable NumPy Array C API, in an up-to date Python3.10 environment. Why should I add an obscure extra code line that refers to a hopelessly outdated NumPy version 1.7? Why do I otherwise see an obscure deprecation warning? Why can this mess not be fixed properly?

**Comment by mattip** [comment]
NumPy is an old project and values backward compatibility, even for very old versions. If you want to use numpy via the C-API, there are conventions you must adhere to. Perhaps if we move to NumPy 2.0 we could change this. See the [roadmap for version 2](https://github.com/numpy/numpy/wiki/NumPy-roadmap-v2) (which could use an update).

**Comment by jwuttke** [comment]
ok, thanks. Added line to the roadmap, and answered https://stackoverflow.com/questions/72775454.
