### ISSUE TITLE
BUG: Does np.cumsum() have a maximum limit？

### ISSUE THREAD

**Issue by Alazia** [numpy/numpy#21878]
### Describe the issue:

```python 
import matplotlib.pyplot as plt
import numpy as np
np.random.seed(0)
nums=np.random.randint(10000, 1000000, 10000)
plt.plot(nums.cumsum())
```
![image](https://user-images.githubusercontent.com/30646709/176411138-496380ac-aeff-40cf-9a1b-1673ce64e8e6.png)

```python
>>> nums=np.random.randint(10000000, 1000000000, 10)
>>> nums.cumsum()
array([  636610453,  1223775495,  2039456427, -2041351294, -1422440888,
       -1168860512,  -241185928,  -133877884,   449249086,  1437063295])
```

### Reproduce the code example:

```python
import matplotlib.pyplot as plt
import numpy as np
np.random.seed(0)
nums=np.random.randint(10000, 1000000, 10000)
plt.plot(nums.cumsum())
```

### NumPy/Python version information:

1.22.2 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

**Comment by Alazia** [comment]
Arithmetic is modular when using integer types, and no error is raised on overflow.
https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html?highlight=cumsum#numpy.cumsum

**Comment by animalmutch** [comment]
Same issue here
