### ISSUE TITLE
BUG: <numpy==1.19.5 5 // np.geomspace(1, 5, 3)=5 2 0>

### ISSUE THREAD

**Issue by huangjun80235** [numpy/numpy#21897]
### Describe the issue:

5 // np.geomspace(1, 5, 3)
array([5., 2., 0.])

### Reproduce the code example:

```python
import numpy as np
5 // np.geomspace(1, 5, 3)
array([5., 2., 0.])
```

### NumPy/Python version information:

numpy==1.19.5

**Comment by seberg** [comment]
Thanksf or opening an issue, but this looks all correct to me on first sight.  Are you sure you did not just typo `//` instead of `/` where the first is floor division?

Closing for now, please do comment if you think there is more to this.
