### ISSUE TITLE
ENH: Use the semantic version instead of the C-API version in the error message for C-API incompatibility

### ISSUE THREAD

**Issue by joaopfg** [numpy/numpy#21901]
### Proposed new feature or change:

In the module `generate_numpy_api`, which is inside the sub package `numpy.core.code_generators `, there is the generation of the C method `static int _import_array(void)`, which has an if statement like the following:

```
if (NPY_FEATURE_VERSION > PyArray_GetNDArrayCFeatureVersion()) {
      PyErr_Format(PyExc_RuntimeError, "module compiled against "\
             "API version 0x%%x but this version of numpy is 0x%%x", \
             (int) NPY_FEATURE_VERSION, (int) PyArray_GetNDArrayCFeatureVersion());
      return -1;
  }
```
I would like to change this error message to, instead of telling about the C-API version, tell about the semantic version of the numpy package. The motivation is that the error seems obscure when using this hexadecimal version that seems to have no relation to the semantic version. Would it be welcome ?

If so, I can try a PR. However, how could I trigger this error for the matter of testing my solution ? Also, is there some way to get the semantic version from the C-API ? Or should I introduce a new macro for it ?

**Comment by seberg** [comment]
@joaopfg can you explain how the changed version will be more useful to users?  The C-API version is the only relevant version here or am I misunderstanding what you are suggesting to change?

**Comment by joaopfg** [comment]
@seberg I think giving the C-API version confuses the regular user. See, for example, this kind of doubt on StackOverflow: https://stackoverflow.com/questions/48054531/runtimeerror-module-compiled-against-api-version-0xc-but-this-version-of-numpy 

There are many similar to this one. The users gets confused when they see this hexadecimal number that seems to have no relation to the semantic version. If we use the semantic version, the user will have a more clean idea that the needs to upgrade or downgrade the version of his numpy.

**Comment by seberg** [comment]
The semantic version is not the interesting one, though.  Maybe you can suggest a rephrase that includes the current versions as is?

**Comment by joaopfg** [comment]
@seberg Please, correct me if I am wrong but, if I understood, the C-API versions set is smaller than the semantic versions set, each semantic version can be mapped to only one C-API version and each C-API version can be mapped a range of semantic versions. 

In this sense, besides telling about both C-API versions, the error message could also tell about the corresponding semantic version ranges of each C-API version so that the user knows to which semantic versions he can upgrade or downgrade his package to get the C-API version he needs. But how to get this mapping from the C-API versions set to the semantic versions set using the C-API ?

**Comment by joaopfg** [comment]
@seberg  The rephrase would be something like `RuntimeError: module compiled against C-API version _v1_ but this C-API version of numpy is _v2_. Consider updating/downgrade your numpy version to some version in the range _v3_-_v4_`.

**Comment by joaopfg** [comment]
@seberg I see. My point is more like a pragmatic suggestion to the user. 

In the case that upgrading the numpy version can be a work around, I think it's worth mentioning it to the user so that he can get a quick fix. Otherwise, the user would have to create an issue, propose a PR or implement a local fix on the package that contains the problematic numpy extension module so that he gets a package with a good compiled extension module. I think most regular users will be afraid of that and will instead go to StackOverflow to get an answer telling them to upgrade the numpy version as a work around =) 

Better save the user some time telling them directly in the error message that upgrading the numpy version can be a work around.

**Comment by mattip** [comment]
Changing the error message to suggest updating the numpy version may sometimes help, but it may also create new unexpected problems. Rarely does a user only have one package that relies on NumPy, and it is notoriously hard to resolve dependencies between various tensorflow/pytorch add-ons. Do you have a specific instance where changing the message would have helped you resolve a problem? If we were to change the message, I would prefer it point to a documentation page under numpy.org that can grow with time to include common cases where users ran into this problem. I think this would be preferable to a blanket suggestion to update numpy, which could break other things.

**Comment by joaopfg** [comment]
@mattip The reason I came is that some coworkers got this error message and were lost about it. When googling this error, all the answers on StackOverflow tell to upgrade numpy version. This was a work around in our case but we didn't understand the reason so I decided to do some research and ended up here.

I agree with your suggestion of making the error message point to a documentation page under numpy.org . Do you have a suggestion of where this documentation would fit and what would be its content ? Is it open for PRs ?

**Comment by mattip** [comment]
We have [the troubleshooting guide](https://numpy.org/doc/stable/user/troubleshooting-importerror.html), the source is [here](https://github.com/numpy/numpy/blob/main/doc/source/user/troubleshooting-importerror.rst). PRs are welcome. I think the date, the message, what two packages+versions caused the problem, and what version of NumPy provided a solution would be specific enough to be helpful.

**Comment by joaopfg** [comment]
@mattip @seberg I opened a PR for this one (https://github.com/numpy/numpy/pull/21943)

**Comment by seberg** [comment]
I actually changed this in NumPy 2.
