### ISSUE TITLE
DOC: The header of `numpy.random.default_rng` doesn't show the optional seed parameter

### ISSUE THREAD

**Issue by soegaard** [numpy/numpy#21910]
### Issue with current documentation:

This image shows that the header:

    numpy.random.default_rng()

doesn't show the optional parameter listed below.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/461765/177031801-bdaac4c4-32ae-4363-9dbb-cf9c7ddd2034.png">

https://numpy.org/doc/stable/reference/random/generator.html

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue, @soegaard.  This has been fixed in gh-21926.
