### ISSUE TITLE
TYP: ndarray is declared to be hashable but it is not hashable

### ISSUE THREAD

**Issue by twoertwein** [numpy/numpy#21930]
### Describe the issue:

`ndarray` inherits `__hash__` from `object` but the implementation sets `__hash__` to `None`. The type anntoations should reflect that.

```py
class ndarray(...): 
    # this is also how typeshed declares list as not hashable: https://github.com/python/typeshed/blob/be2921648cc03407c5ddf42374a5afd23f594c24/stdlib/builtins.pyi#L990 
    __hash__: ClassVar[None]  # type: ignore[assignment]
    ...
```

### Reproduce the code example:

```python
import numpy as np


np.zeros(1).__hash__ is None  # True
reveal_type(np.zeros(1).__hash__)
```

### Error message:

```shell
mypy: "def () -> builtins.int"
pyright: Type of "np.zeros(1).__hash__" is "() -> int"
```

### NumPy/Python version information:

1.23.0

**Comment by BvB93** [comment]
Hm, it might be good to double check it there are any other type that need an explicit `__hash__` declaration while we’re it. This is something that should be fixed though.
