### ISSUE TITLE
BUG: `numpy.distutils.system_info.get_info("blas_opt")` has unsuppressable stdout side effects

### ISSUE THREAD

**Issue by michaelosthege** [numpy/numpy#21942]
### Describe the issue:

Aesara uses `numpy.distutils.system_info.get_info("blas_opt")` to obtain some compiler settings upon import.

However, every this prints the GCC configuration to `stdout` which is incredibly annoying.

We tried to capture/suppress the `stdout/stderr` output (see below), but it doesn't work.

Related issues/PRs:
* https://github.com/conda-forge/aesara-feedstock/issues/54
* https://github.com/aesara-devs/aesara/issues/1005
* https://github.com/aesara-devs/aesara/pull/980

### Reproduce the code example:

```python
from contextlib import redirect_stderr, redirect_stdout
import io
import sys
import numpy.distutils.system_info

class NumpyCompatibleStdoutStringIO(io.StringIO):
    """Used as a temporary replacement of sys.stdout to capture Numpy's output.
    We want to simply use io.StringIO, but this doesn't work because
    Numpy expects the .encoding attribute to be a string. For io.StringIO,
    this attribute is set to None and cannot be modified, hence the need for
    this subclass.
    (See forward_bytes_to_stdout in numpy.distutils.exec_command.)
    """

    encoding = sys.stdout.encoding

# Neither of the following two work:
# stdout_sio, stderr_sio = io.StringIO(), io.StringIO()
stdout_sio, stderr_sio = NumpyCompatibleStdoutStringIO(), NumpyCompatibleStdoutStringIO()

with redirect_stdout(stdout_sio), redirect_stderr(stderr_sio):
    numpy.distutils.system_info.get_info("blas_opt")
```

### Error message:

No error, but unwanted stdout:

```shell
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/Users/osthege/AppData/Local/Continuum/miniconda3/envs/pm3v4/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-5.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --with-gxx-include-dir=/mingw64/include/c++/5.3.0 --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-version-specific-runtime-libs --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev5, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 5.3.0 (Rev5, Built by MSYS2 project)
```

### NumPy/Python version information:

1.19.2 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]

**Comment by rgommers** [comment]
Thanks for the report @michaelosthege. I agree that that is annoying. This code was designed for use at build-time, and at that point it's normal to print to stdout for distutils.

This code is all deprecated, so I'm not inclined to work on it myself anymore, but would be happy to review a patch. Or you could go to the longer-term change you need anyway (either vendor the relevant code you need, or replace it with something better).

**Comment by michaelosthege** [comment]
Thanks @rgommers, I fear the timeline for deprecation, migrating away etc. is mich longer than the patience we/our users have to endure the `stdout` spam.

The print is exactly the same as running `gcc -v`, I just haven't been able to pinpoint the line (in NumPy) where `gcc -v` is invoked.

During my tests I was able to run `gcc -v` without getting the `stdout` lines like this:
```python
subprocess.check_call("gcc -v", stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
```

If we can pinpoint the line in NumPy where the call is invoked, a patch might be as simple as this one-liner.

**Comment by rgommers** [comment]
I have to say that I've never seen this. From the bug reports I'm guessing it's Windows-only. Possibly also a regression?

The code that does this is probably https://github.com/numpy/numpy/blob/main/numpy/distutils/system_info.py#L270-L323. It's weird though because the `gcc` invocation is in the non-`win32` block below it.

**Comment by michaelosthege** [comment]
Yes, Windows only and probably a regression of some sort.

Thanks for the code pointer. I'll investigate and attempt to fix tomorrow!

**Comment by michaelosthege** [comment]
@rgommers I opened a PR here: https://github.com/numpy/numpy/pull/21959
