### ISSUE TITLE
BUG: Incorrect answer when np.array([10]) * (10 ** 18).

### ISSUE THREAD

**Issue by wilixx** [numpy/numpy#21966]
####  For example:

```
import numpy as np
x = np.array([10])
answer = x * (10 ** 18)
print("answer:", answer)  # answer: [-8446744073709551616].  Not correct !!
```
### Reproduce the code example:

```python
import numpy as np
x = np.array([10])
answer = x * (10 ** 18)
print("answer:", answer)  # answer: [-8446744073709551616].  Not correct !!
```

### Error message:

```shell
No error message, since the compiler even supposes "the wrong answer is the correct one. " 
If such code occurs in syetems with high security requirements, disaster may happen.
```

### NumPy/Python version information:
```
>>> import numpy
>>> numpy.__version__
'1.21.0'
```

**Comment by rkern** [comment]
Can you show what you are getting when you use `x = np.array([100])`? I don't get the result that you are expecting. I get something consistent with `int64` clock arithmetic, which is what I am expecting.

```
[~]                                                                                                                                                                                                                  
|1> np.array([10]) * 10**18                                                                                                                                                                                          
array([-8446744073709551616], dtype=int64)

[~]                                                                                                                                                                                                                  
|2> np.array([100]) * 10**18                                                                                                                                                                                         
array([7766279631452241920], dtype=int64)
```

This is all expected, designed behavior. `np.array([10])` creates an `int64` array. When multiplying with an integer scalar, you get an `int64` result. `int64` multiplication uses clock arithmetic.

**Comment by wilixx** [comment]
> Can you show what you are getting when you use `x = np.array([100])`? I don't get the result that you are expecting. I get something consistent with `int64` clock arithmetic, which is what I am expecting.
> 
> ```
> [~]                                                                                                                                                                                                                  
> |1> np.array([10]) * 10**18                                                                                                                                                                                          
> array([-8446744073709551616], dtype=int64)
> 
> [~]                                                                                                                                                                                                                  
> |2> np.array([100]) * 10**18                                                                                                                                                                                         
> array([7766279631452241920], dtype=int64)
> ```
> 
> This is all expected, designed behavior. `np.array([10])` creates an `int64` array. When multiplying with an integer scalar, you get an `int64` result. `int64` multiplication uses clock arithmetic.

Yeah, you are right. However, the issue I submitted eariler may be confusing. Let me restate it: 

### When you multiply 10 ** 18， the answer is incorrect. 

```
import numpy as np
x = np.array([10])
answer = x * (10 ** 18)
print("answer:", answer)   answer : [-8446744073709551616]

```
#### And also x = np.array([100]), incorrect. 
```
import numpy as np
x = np.array([100])
answer = x * (10 ** 18)
print("answer:", answer)   # answer : [7766279631452241920]

```
### **However**, when you multiply 10 ** 19， the answer is correct. 

```
import numpy as np
x = np.array([10])
answer = x * (10 ** 19)
print("answer:", answer)   # answer:  [1.e+20]

```

#### This issue indicates the calculation is not often consistence. And it really causes **hard-to-discover bugs** in my code. 
And for **clock arithmetic**, why the 10**18 follows **clock arithmetic** while the 10**19 does not?

**Comment by ksunden** [comment]
The difference is that 10**18 can itself be represented by an int64, but 10**19 cannot, so it does floating point math instead of integer math

**Comment by wilixx** [comment]
> The difference is that `10**18` can itself be represented by an `int64`, but `10**19` cannot, so it does floating point math instead of integer math, note that the output of 1e+20, is itself dtype of `float64`

### Thank you.  I see.  To avoid the incorrct answer caused by 
```
import numpy as np
x = np.array([10])
answer = x * (10 ** 18)
print("answer:", answer)   # answer : [-8446744073709551616].  Incorrect ！
```

### We need to rewrite 10 by 10.0 to force the float type multiplication. 
```
import numpy as np
x = np.array([10.0]) 
answer = x * (10 ** 18)
print("answer:", answer)   # answer : [[1.e+19]].   Correct now！
```
