### ISSUE TITLE
BUG: incorrect type annotations for np.angle

### ISSUE THREAD

**Issue by bmerry** [numpy/numpy#21972]
### Describe the issue:

The type annotation for `np.angle` seems to assume the return value is a scalar, but if given an array it returns an array. This causes false positives from mypy.

### Reproduce the code example:

```python
import numpy as np

a = np.array([1.0 + 2.0j, 3.0 + 4.0j], dtype=np.dtype(complex))
ang = np.angle(a)
print(ang[0])
```

### Error message:

```shell
angle.py:5: error: Value of type "complexfloating[Any, Any]" is not indexable
```

### NumPy/Python version information:

1.23.1 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]

**Comment by bmerry** [comment]
Apart from the annotation not indicating an array return, it's also incorrect to assume `complexfloating`, since `np.angle` always returns real values.

**Comment by BvB93** [comment]
Good catch! https://github.com/numpy/numpy/pull/21974 should resolve both issues.
