### ISSUE TITLE
build numpy-1.23.1 for aarch64 fail

### ISSUE THREAD

**Issue by stoneCoder** [numpy/numpy#21987]
### Steps to reproduce:

![image](https://user-images.githubusercontent.com/4328939/179137294-ae576cd8-8bca-4040-a7c7-7b28cba45924.png)
![image](https://user-images.githubusercontent.com/4328939/179158734-ed75e2b8-65b3-45ec-bc2b-999e7e0a1411.png)

build loops.c to loops.o fail

### Additional information:
Python 3.8
setuptools-49.2.0

**Comment by mattip** [comment]
Please copy-paste text not images into issues, it is much more friendly for people with visual disabilities and also much easier to search for similar issues.

The error is `invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different sizes`.

I think this is a problem with clang 13. @seiko2plus thoughts?

**Comment by stoneCoder** [comment]
> Please copy-paste text not images into issues, it is much more friendly for people with visual disabilities and also much easier to search for similar issues.
> 
> The error is `invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different sizes`.
> 
> I think this is a problem with clang 13. @seiko2plus thoughts?

I'm afraid that's not the reason.
I use Apple clang version 12.0.0 (clang-1200.0.32.21)
already tips this
invalid conversion between vector type '__m64' (vector of 1 'long long'
      value) and integer type 'int' of different size
clang: error: no such file or directory: 'build/temp.iphoneos-arm64-3.8/build/src.iphoneos-arm64-3.8/numpy/core/src/umath/loops.o'

**Comment by seiko2plus** [comment]
Sorry for the delay, but I need a full build log to determine what we are facing here, the current error is related to MMX(x86) intrinsics while the host is targeting `arm64`, header `mmintrin.h` shouldn't be activated from the first place.

**Comment by rgommers** [comment]
No follow-up, and we now have macOS arm64 in CI and switched build systems, so this issue is almost certainly no longer relevant. Closing - thanks all.
