### ISSUE TITLE
DOC: `masked_print_options` should be `masked_print_option`

### ISSUE THREAD

**Issue by davidgilbertson** [numpy/numpy#21985]
### Issue with current documentation:

The page [Constants of the numpy.ma module](https://numpy.org/doc/stable/reference/maskedarray.baseclass.html#numpy.ma.masked_print_options) references `numpy.ma.masked_print_options`, but this should be `numpy.ma.masked_print_option` (no s).

This exists in a few other places too (e.g. the index)

### Idea or request for content:

Since this can't be set by direct assignment, it might be nice to say that this can be changed with `numpy.ma.masked_print_option.set_display('·')`

**Comment by WarrenWeckesser** [comment]
FYI: The line in the source file is

https://github.com/numpy/numpy/blob/6d5bc233442c034d54e0c0b15fdd7ed27e36fcac/doc/source/reference/maskedarray.baseclass.rst?plain=1#L38

**Comment by MikiPWata** [comment]
working on this

**Comment by WarrenWeckesser** [comment]
This was fixed in https://github.com/numpy/numpy/pull/22013.
