### ISSUE TITLE
DOC: Creating numpy arrays from C arrays

### ISSUE THREAD

**Issue by romgrk** [numpy/numpy#22003]
### Issue with current documentation:

Unclear doc about the use-case I have.

### Idea or request for content:

The documentation describes pretty well how to manipulate an already existing numpy array with C modules. I have the opposite problem, I have some C library that creates data in any form I need it to be, and I would like to load this data into a numpy array so it can be modified through the python API. Ideally I want to be able to move the C arrays directly into the numpy arrays without having to pay any copy cost, as the dataset is quite large.

Is this something that is possible? And if so, what would be the best documents/sources to read to understand how to achieve this?

**Comment by mattip** [comment]
I think you are looking for [the interop guide](https://numpy.org/devdocs/user/basics.interoperability.html). Probably the easiest in your case is the new [dlpack](https://numpy.org/devdocs/user/basics.interoperability.html) protocol

**Comment by romgrk** [comment]
Ok, both links seem to describe what I'm looking for, thanks for your help @mattip :)
