### ISSUE TITLE
DOC: The example for `np.char.decode` gives an example of `encode`

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#22015]
### Issue with current documentation:

The example in the docstring of [`np.char.decode`](https://numpy.org/doc/stable/reference/generated/numpy.char.decode.html) shows the use of `encode`, not `decode`:

https://github.com/numpy/numpy/blob/5ba36b700284a8392af5be542f65ecd262fd2568/numpy/core/defchararray.py#L565-L568

This should be fixed to demonstrate `decode`.

**Comment by BrentTanKian** [comment]
Hi, I would like to work on this, and will likely submit my changes for review over the weekend if that is okay

**Comment by WarrenWeckesser** [comment]
Thanks @BrentTanKian, that sounds good.  We generally don't assign issues, so you can go ahead and work on it.

**Comment by swagatip** [comment]
Looking into this as part of the Grace Hopper OSD NumPy sprint.

**Comment by bsipocz** [comment]
@swagatip - This one has a PR opened with the fix which is quite close to get merged. Could you maybe choose another one, please?

**Comment by swagatip** [comment]
@bsipocz ok thanks for letting me know

**Comment by WarrenWeckesser** [comment]
This was fixed by https://github.com/numpy/numpy/pull/22309.
