### ISSUE TITLE
BUG: <np.sin and/or np.pi returning slightly different results on different os's>

### ISSUE THREAD

**Issue by bethac07** [numpy/numpy#22028]
### Describe the issue:

When trying to run tests on a local Macbook (OSX 11.6.7) and on a GitHub Actions runner (set up to build on `ubuntu-latest`, config file [here](https://github.com/CellProfiler/centrosome/blob/master/.github/workflows/pythonpackage.yml)), we were perplexed by a test that was failing on GH but passing locally. Basically, we're getting tiny differences in the output of some simple math using np.pi and np.sin, and it led to a rounding difference that led to a test failure. Both machines are running Python 3.8.13 and Numpy 1.23.1. We can fix our test by simply adding some rounding, but it seemed to me an unexpected behavior so I wanted to report it here. Please let me know if I can provide any more info!

Mac
```
1.9999999999999998 float64
2.0 float64
2.220446049250313e-16 float64
```
Linux
```
1.9999999999999996 float64
1.9999999999999998 float64
2.220446049250313e-16 float64
```

### Reproduce the code example:

```python
import np
angle = float(30) * np.pi / 180.0
length = 8
sin =  np.sin(angle) * length / 2
y = np.finfo(float).eps + np.sin(angle) * length / 2
eps = np.finfo(float).eps
for eachfloat in [sin,y,eps]:
    print(eachfloat, eachfloat.dtype)
```

### NumPy/Python version information:

Mac:
```
1.23.1 3.8.13 (default, May  8 2022, 17:53:05) 
[Clang 13.0.0 (clang-1300.0.29.30)]
```
Linux:
```
1.23.1 3.8.13 (default, Jun 20 2022, 14:28:56)
[GCC 9.4.0]
```

**Comment by rkern** [comment]
It's this an M1/M2 MacBook or an older Intel MacBook? There _are_ variations in how different CPUs do sequences of floating point arithmetic, and numpy doesn't attempt to hide it. We also do rely on the platform-provided C math library for functions like `sin()`, so that's another source of variation.

**Comment by bethac07** [comment]
2017 Intel. Understood, it's just a test that has been in use in our code base for a long time & this is the first instance we've run across failing, so wanted to make sure it wasn't something that might have recently crept in and started causing issues. Happy to close, thanks for the quick response!

**Comment by rkern** [comment]
I think we did add some SIMD implementations of some ufuncs like `sin()`, and that's yet another place platform variability could have crept in. I'm not 100% up on the details of that, so I don't know right away from your platforms and versions if that might even be a factor.

**Comment by seberg** [comment]
There is intel specific code (SVML) now (only used for the more high end CPUs, and I think not the next generation of CPUs either, so a bit limited).  That may introduce even more changes in precision.  GCC has a list [here](https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html#Errors-in-Math-Functions), but I am not even sure that this list covers the GCC version if automatic SIMD instructions are used (not sure this would happen).

To some degree, there is an open question to what extend we should accept code like intel SVML if it has lower precision than e.g. gcc.
