### ISSUE TITLE
Update `np.bool` to be an alias to `np.bool_` and un-deprecate it

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#22021]
Since NumPy 1.20.0, `np.bool` is deprecated (together with `np.int` and `np.float`). We'd like to keep `np.bool` though, because it's a better name than `np.bool_` and is unambiguous.

There was a long email thread on this topic: https://mail.python.org/archives/list/numpy-discussion@python.org/thread/NZWX22G5L7I5LOMKQ7HIRECUZXV6NA34/#NZWX22G5L7I5LOMKQ7HIRECUZXV6NA34. The approach @seberg suggested there was:
1. Go ahead for now (deprecate)
2. Add a FutureWarning at some point that we _will_ start to export `np.bool` again (but `from numpy import *` is a problem?)
3. Aim to make `np.bool is np.bool_` at some point in the (far) future.

`np.bool` has now been deprecated for four releases, so it's time to take the next step in the next release (1.24.0).

**Comment by eric-wieser** [comment]
Should we do the same for `np.object_` vs `np.object`?

**Comment by rgommers** [comment]
+1 from me, `np.object` is perfectly clear. Less important than `bool`, but has the same rationale.

**Comment by zachcoleman** [comment]
In general, will `bool` still be an alias/converted for the underlying numpy boolean type? Is using `bool` as the `dtype` the most compatible way across `<1.20.0`, `>=1.20.0, <1.25`, and going forward?

**Comment by zombinator0** [comment]
Hi, if this issue is untaken, I would like to have this as my first issue. Can I please get some pointers on where to start?

**Comment by ghylander** [comment]
Hi, I come from #23494.

For now, to avoid confussion, perhaps the text of the "FutureWarning" should be changed?
From the curent text to something along the lines of "Starting in v1.24 `np.bool` was deprecated in favour of `np.bool_`, but will be aliased to `np.bool_` in the future. For now, please use `np.bool_`"?
Provides more information about what is going on, and seems less confusing/conflicting when paired with the `AttributeError` raised later.

**Comment by rgommers** [comment]
`np.bool` is back alive and the preferred name for numpy 2.0 (`np.bool_` is an alias to `np.bool` now):
```python
>>> np.bool
<class 'numpy.bool'>
>>> np.bool_
<class 'numpy.bool'>
```

> Should we do the same for `np.object_` vs `np.object`?

This wasn't done. Can still be done at any time but isn't a blocker for 2.0, so I'll open a new issue for it now to not forget about it. Closing this one to mark that the issue with `bool` has been addressed.

**Comment by ogencoglu** [comment]
What is the purpose of `np.bool` ? Should it be preferred to `bool` when instantiating numpy arrays? Is it faster or more memory efficient?

**Comment by seberg** [comment]
It's a different scalar that behaves slightly differently (there are two reasons for this, historically because numpy scalars pretend to be arrays in part, and in part because Python bools behave more like ints sometimes.)
