### ISSUE TITLE
BUG: Masked array creation fails with structured array

### ISSUE THREAD

**Issue by parched** [numpy/numpy#22041]
### Describe the issue:

When trying to create a mask array with a structured dtype a `TypeError` is thrown. However, the same code with `np.array` instead of `np.ma.array` works fine.

I suspect [this](https://github.com/numpy/numpy/blob/45bc13e6d922690eea43b9d807d476e0f243f836/numpy/ma/core.py#L2868) might just need to catch `TypeError` too.

### Reproduce the code example:

```python
import numpy as np

np.ma.array((1, (b"", b"")), dtype=[("x", np.int_), ("y", [("i", np.void), ("j", np.void)])])
```

### Error message:

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "venv\lib\site-packages\numpy\ma\core.py", line 6610, in array
    return MaskedArray(data, mask=mask, dtype=dtype, copy=copy,
  File "venv\lib\site-packages\numpy\ma\core.py", line 2865, in __new__
    [getmaskarray(np.asanyarray(m, dtype=_data.dtype))
  File "venv\lib\site-packages\numpy\ma\core.py", line 2865, in <listcomp>
    [getmaskarray(np.asanyarray(m, dtype=_data.dtype))
TypeError: a bytes-like object is required, not 'int'
```

### NumPy/Python version information:

numpy: 1.23.0
python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

**Comment by mattip** [comment]
> I suspect [this](https://github.com/numpy/numpy/blob/45bc13e6d922690eea43b9d807d476e0f243f836/numpy/ma/core.py#L2868) might just need to catch TypeError too.

Could you put a PR together to test that hypothesis? It should include a test. We have had problems changing masked array since the tests do not cover the uses by downstream libraries, so we would need to check this kind of a change against astropy to make sure it does not break anything.

**Comment by parched** [comment]
Ok, will do.

In case anyone else hits this, the workaround I'm using is to create the plain array first and then create the masked array from that.
