### ISSUE TITLE
BUG: Inconsistent floating point calc between Windows and Linux using matmul function

### ISSUE THREAD

**Issue by geoanan** [numpy/numpy#22044]
### Describe the issue:

I have a simple script testing the `matmul `function.
When I run the script on a Windows machine (Windows 10 64-bit) and a RedHat (RedHat 7 64-bit) machine, the results are different.

Windows 10 results
Entry [0, 1] = 0.000000000000001346809783922148
Entry [1, 1] = 1.000000000000000000000000000000
Entry [2, 1] = 0.000000000000000000513348854551
Entry [3, 1] = -0.000000000000000056419554088194
Entry [4, 1] = 0.000000000000000012992244502267

RedHat 7 results
Entry [0, 1] = 0.000000000000000000000000000000
Entry [1, 1] = 1.000000000000000000000000000000
Entry [2, 1] = 0.000000000000000000000000000000
Entry [3, 1] = 0.000000000000000000000000000000
Entry [4, 1] = 0.000000000000000000000000000000

Should the values not be the same?

### Reproduce the code example:

```python
import numpy as np
def matrix_multiply_check():
    default_matrix = np.full((100, 100), 1.234567890123, np.float64)

    for i in range(ARRAY_DIM):
        for j in range(i, ARRAY_DIM):
            default_matrix[i, j] = 4.5678912345

    inverse_matrix = np.linalg.inv(default_matrix)
    return np.matmul(inverse_matrix, default_matrix)

if __name__ == "__main__":
    result_matrix = matrix_multiply_check()
    
    for x in range(5):
        print("Entry [" + str(x) + ", 1] = " "%.30f" % result_matrix[x, 1])
```

### NumPy/Python version information:

Numpy version 1.19.5
python version 3.8.8

**Comment by rkern** [comment]
Not necessarily, no. We link against accelerated BLAS and LAPACK libraries to do these linear algebra operations, and those may be different on the different platforms and do the floating point arithmetic in different (but all valid) orders. You are seeing reasonable amounts of variation given that.

**Comment by geoanan** [comment]
Thanks for the clarification @rkern
