### ISSUE TITLE
Some aarch64 nightly wheel uploads failing

### ISSUE THREAD

**Issue by charris** [numpy/numpy#22050]
The travis problem is
```
The job exceeded the maximum log length, and has been terminated.
```
It's a close run thing that happens just before/after the upload. Let's see if that is fixed tonight, 7-17-2022. We might need to figure out how to shorten the log.

**Comment by mattip** [comment]
Maybe we could change this, I don't think we really need `-vvv` on the tests https://github.com/numpy/numpy/blob/950ded32273de4daa941af07bc03acd749227698/tools/wheels/cibw_test_command.sh#L14

**Comment by charris** [comment]
> I don't think we really need -vvv on the tests

Agree. Pytest shows the failing tests anyway. I note that the quick fix worked, also that the aarch64 builds need to be triggered independently from the wheelbuild action. Github actions doesn't seem to have the same limit on log size as travis, but that doesn't mean we shouldn't reduce it.

**Comment by charris** [comment]
All is working now.
