### ISSUE TITLE
BUG: error in string array generated with arange function

### ISSUE THREAD

**Issue by m-aguena** [numpy/numpy#22055]
### Describe the issue:

Arrays created with `np.arange(n, dtype=str)` for `n`>2 raise an error.

### Reproduce the code example:

```python
import numpy as np
np.arange(3, dtype=str)
```

### Error message:

```shell
File "<stdin>", line 1, in <module>
ValueError: no fill-function for data-type.
```

### NumPy/Python version information:

1.23.1, 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]

**Comment by seberg** [comment]
I am not quite convinced that `arange` on strings make much sense.  Maybe you would want `np.arange("a", "z")` to work?  You can cast to string later on with `.astype(str)`.
It may be a bit weird that `n==1` apparently works.  But generally I would lean towards closing it as correct (with the caveat that maybe we should disallow the `n==1` case as well.

**Comment by rkern** [comment]
I concur.

**Comment by m-aguena** [comment]
I agree with this solution, as long as there is consistency (`n==2` also works btw).

**Comment by ddasilva** [comment]
I'm trying to work on this by adding a check to the multiarraymodule.c function for `arange()` which throws a `TypeError` if the dtype is string. I'm stuck trying to figure out how to check if `PyArray_Descr *typecode` is a string. Any advice?

**Comment by ddasilva** [comment]
Nevermind, figured it out. PR coming soon..

**Comment by rgommers** [comment]
PR ready, so that should just be reviewed (seems like not much work) - so removed the `Close?` label.

**Comment by seberg** [comment]
PR wasn't correctly linked, closing.
