### ISSUE TITLE
/.local/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so: undefined symbol: PyUnicodeUCS4_FromObject

### ISSUE THREAD

**Issue by zilmarij** [numpy/numpy#22065]
### Steps to reproduce:

Running a python script with scipy's zeros and array imported, I encounter the following error:
I tried reinstalling numpy as follows:

`pip uninstall numpy`
`pip install numpy`

This  gave the following message

> Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (1.13.3)

So I manually removed numpy from /usr/lib/python2.7/dist-packages and then reinstalled it using:
`pip2.7 install numpy`
 
This command reinstalled numpy in the site-packages, and was accompanied by the following warning:

> WARNING: The scripts f2py, f2py2 and f2py2.7 are installed in '/home/zilmarij/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

I have added the following line to the .bashrc file:
`export PATH=/home/zilmarij/.local/bin:$PATH
`

Th system details are:
OS : Ubuntu 18.04 (bionic)
Multiple Python versions are installed. Output of  `python --version` :

> Python 2.7.17

The problem persists. I would appreciate any help in debugging the issue.

Thanks!

### Error message:

```shell
File "/home/zilmarij/Downloads/sniper-latest/sniper-7.2/scripts/sysenv.py", line 4, in <module>
    from scipy import zeros, array
  File "/home/zilmarij/.local/lib/python2.7/site-packages/scipy/__init__.py", line 62, in <module>
    from numpy import show_config as show_numpy_config
  File "/home/zilmarij/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/zilmarij/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /home/zilmarij/.local/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so: undefined symbol: PyUnicodeUCS4_FromObject
```

**Comment by mattip** [comment]
NumPy does not support python2.7, the minimum version of python currently supported is 3.8.

**Comment by zilmarij** [comment]
The simulator I am using supports python2.7, is there any alternative that I could use for numpy?

**Comment by mattip** [comment]
You already had numpy 1.13.1, why do you need to change it?

**Comment by mattip** [comment]
If you are using the python as installing in your Ubuntu image, then you should stay with that method of installation `sudo apt install python-numpy` and not mix `pip` and `apt`.

**Comment by zilmarij** [comment]
Numpy-1.13.1 throws error when I try to run the python2.7 script (which I am bound to use). That is why I am looking for alternatives for numpy.

**Comment by mattip** [comment]
Why not use a virtual environment
```
sudo apt install virtualenv
virtualenv -p python2 /tmp/my_python2.7
source /tmp/my_python2.7/bin/activate
python -m pip install numpy  # installs NumPy 1.16
# now continue to use this virtualenv to run the old program
```

**Comment by zilmarij** [comment]
Thanks for the tip, I'll surely try it out.
