### ISSUE TITLE
DOC: The issue was unintentionally mistaken

### ISSUE THREAD

**Issue by SamiShalwi** [numpy/numpy#22062]

**Comment by matteosantama** [comment]
Hi @SamiShalwi, are you trying to report an problem? If so, please provide more details, such as a link to the problematic documentation or a code snippet. Otherwise this issue will be closed.

**Comment by seberg** [comment]
Sounds like the intention was to close this again (rather than just change the title), so cloisng. Please open a more comprehensive issue if I misunderstood.
