### ISSUE TITLE
BUG: passing None as like to arange

### ISSUE THREAD

**Issue by ItayVortex** [numpy/numpy#22069]
### Describe the issue:

Calling `arange` with `like=None` gives an error:
```
TypeError: The `like` argument must be an array-like that implements the `__array_function__` protocol.
```
The documentation specify that `like=None` is the default value - https://numpy.org/doc/stable/reference/generated/numpy.arange.html

### Reproduce the code example:

```python
For example:

numpy.arange(100, like=None)

TypeError: The `like` argument must be an array-like that implements the `__array_function__` protocol.
```
But, calling `np.arange(100)` works fine.
```


### Error message:

_No response_

### NumPy/Python version information:

1.21.0 3.9.5 (default, Nov 23 2021, 15:27:38) 
[GCC 9.3.0]

**Comment by mattip** [comment]
The argument is "keyword-only", so if it is specified, it must be an array-like. But it is fine if it is not specified. The `like = None` documentation is indeed a bit misleading.

**Comment by seberg** [comment]
Yeah, it shouldn't be really important that `like=None` works.  I do think it works for Python defined functions though, so in that sense I think it may be easiest to just support it here as well.

**Comment by jordyjwilliams** [comment]
@seberg @ItayVortex opened #22178 to address this. Along with a similar 'issue' for other datatypes. 

If you could all let me know your thoughts that would be great thanks.

First PR into this project so sorry if I messed up any of the 'contribution guidelines'

**Comment by jordyjwilliams** [comment]
@seberg @ItayVortex sorry, took longer than expected however #22178 is performing as I believe the intended result should be. Ready for a review if you don't mind 👁️
