### ISSUE TITLE
BUG: Boolean indexing overwriting problem after np.full initialization

### ISSUE THREAD

**Issue by ZeTrueSte** [numpy/numpy#22074]
### Describe the issue:

There seems to be a problem with overwriting data in a 2D numpy array with boolean indexing for arrays initialized with np.full and small values. The indexing works (correctly generates the True array) but the overwriting doesn't work.
PC: Windows 10, 64bits, intel i7

### Reproduce the code example:

```python
import numpy as np

Mat1 = np.full((1024, 40), 0) # use full
Mat1[Mat1<1e-07] = 1e-07 # doesn't do anything
print(Mat1)

Mat2 = np.zeros((1024, 40)) # use zero
Mat2[Mat2<1e-07] = 1e-07 # works as expected
print(Mat2)
```

### Error message:

```shell
None
```

### NumPy/Python version information:

Numpy  1.21.6, Python 3.9.1

**Comment by WarrenWeckesser** [comment]
The problem is that `Mat1` is created as an *integer* array:
```
In [3]: Mat1 = np.full((1024, 40), 0)

In [4]: Mat1.dtype
Out[4]: dtype('int64')
```
When you try to assign the value 1e-07 to elements of this array, the values are truncated to 0.

To create an array of floating point values, you can use

    Mat1 = np.full((1024, 40), 0.0) # use full

**Comment by ZeTrueSte** [comment]
Yeah sorry, I just realized that, but you beat me to it
