### ISSUE TITLE
BUG: ndarray.base returns memoryview object instead of base object

### ISSUE THREAD

**Issue by florentbr** [numpy/numpy#22077]
### Describe the issue:

The method `ndarray.base` used to return the base object.
I don't know when the regression occurred but as of release 1.23.1,  `ndarray.base` now returns a memory view object (`<memory at 0x000001C6AD0EFDC0>`).

The documentation also states that it should return the base object:

> ndarray.base
>    Base object if memory is from some other object.

### Reproduce the code example:

```python
import numpy as np
import array

buffer = array.array('B', (1,2,3,4))
ys = np.frombuffer(buffer, np.int8)

assert ys.base is buffer  # fails here!
```

### NumPy/Python version information:

1.23.1 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]

**Comment by florentbr** [comment]
This regression was introduced by release 1.22.4
It works as expected till version 1.22.3

**Comment by rkern** [comment]
`.base` is not guaranteed to be any particular object, just _an_ object that will keep the underlying memory from being deallocated as long as the reference to it is kept. In this case, it looks like `frombuffer()` is doing an intermediate transformation of the `array.array` to a `memoryview`, then constructing the `ndarray` from the `memoryview`. The `ndarray` keeps the `memoryview` alive through its reference via the `.base` attribute, and the `memoryview` in turn keeps the `array.array` alive.

**Comment by rkern** [comment]
I'm also pretty sure this fixed a bug. In older versions where the `.base` points directly to the `array.array` without the intermediate `memoryview`, the `array.array` is allowed to reallocate when it gets extended in-place. That leaves the `ndarray` pointing to invalid memory. Having `.base` pointing directly to the `array.array` does not keep the memory alive correctly.

```
|1> np.__version__
'1.21.2'

|2> import array

|3> x = array.array('B', [1, 2, 3, 4])

|4> y = np.frombuffer(x, dtype=np.int8)

|5> y.base
array('B', [1, 2, 3, 4])

|6> x.extend(range(16))

|7> y
array([-80, -22,  58, -11], dtype=int8)
```

With more recent versions that keep the intermediate `memoryview` alive via `.base`, the `array.array` is not allowed to reallocate.

```
|3> numpy.__version__
'1.23.1'

|4> import array

|5> x = array.array('B', [1, 2, 3, 4])

|6> y = np.frombuffer(x, dtype=np.int8)

|7> y
array([1, 2, 3, 4], dtype=int8)

|8> y.base
<memory at 0x7fb4393dd100>

|9> x.extend(range(16))
---------------------------------------------------------------------------
BufferError                               Traceback (most recent call last)
<ipython-input-9-af1ecfcf0516> in <module>
----> 1 x.extend(range(16))

BufferError: cannot resize an array that is exporting buffers
```

**Comment by florentbr** [comment]
It makes sense. Thanks for the explanation.
