### ISSUE TITLE
cannot reshape value XYZ to xyz  - force = True

### ISSUE THREAD

**Issue by maheshs11** [numpy/numpy#22079]
### Proposed new feature or change:

A parameter  called *kwargs force = true 
if force == True , 
accept (i,j,k ) values and try below logic for reshaping

```
image = cv2.imread("/content/paper1.jpg")
_shape_1= image.shape
print("The shape of image is:",_shape_1)
print("The product shape of image is:", np.prod(_shape_1))

dim = np.prod(_shape_1)
num = dim
factors=[]
for i in range(1,num+1):
    if num%i==0:
       factors.append(i)
#print ("Factors of shape is {}  = {}".format(num,factors))

test = []
for i in factors:
  for j in factors:
    for k in range(0,1000):
      if i*j*k == num:
        if i <= 3000 and j <= 5000 and k <=3: # set this values acc to required shape
          test.append([i,j,k])

print("The possible values to reshape: ",test)
print("The size to be reshaped to:",tuple(test[0]))        
moy = np.reshape(image,tuple(test[0]))
new_shape = moy.shape
print("The reshaped image size is: ",new_shape)
```

https://gist.github.com/maheshs11/332ac21ed3bbcf8470f0f5fe7b80459e

**Comment by mattip** [comment]
The code is a snippet that searches the space of all possible shape tuples and reshapes the image to the first one. What is the actual proposal to NumPy? What would you have NumPy do that it does not do now?

NumPy is very hesitant to add new functions and change existing ones, even very simple ones. The changes add maintenance burden, make the documentation heavier, and add to the test suite. In the [developer workflow](https://numpy.org/doc/stable/dev/development_workflow.html#get-the-mailing-list-s-opinion) we ask that new api functions first be vetted on the mailing list to make sure they are popular and complicated enough to justify the extra load.
