### ISSUE TITLE
ENH: generate a random sample based on independent priors in `random.choice`

### ISSUE THREAD

**Issue by rodosingh** [numpy/numpy#22082]
### Proposed new feature or change:

**Objective**: Sample elements from the given iterator (a `list`, a `numpy` array, etc.) based upon pre-defined probabilities associated with each element which may not *sums upto 1*.

## Overview
- In the `numpy.random.choice` function the cases where we're explicitly providing the list of probabilistic values for an input sample, the requirement expects the sum of the whole list to be 1. This makes sense when all the elements are possible observation for a *single* random variable whose **pmf**(`probability mass function`) is nothing but the `p` list.
- But when every element in that list can be regarded as observation of separate independent *Bernoulli* r.v. (`random variable`), then the problem falls into the category of `multi-label`. Intuitively speaking, for each element in the `list` or `array` given to us, we'll toss a coin (may be biased or unbiased) `~B(p)` (i.e., follows Bernoulli with *p* as success probability for head).
- The output `array` or `list` would probably be a ***proper subset*** or can be a ***full list*** or can be an ***empty*** one.
- Plus, here the argument `size` should automatically get **shut down** as we just want which all elements got selected into the output `list` after `n` coin tossess (where `len(list) = n`). Also it may happen that each element is *independent* as argued above, but the `sum(p) = 1`. Then we can probably put an extra argument `independence = True` or `independence = False`.

## Error
```python3
t = np.random.choice(a = [0, 1, 2, 3, 4, 5], size=None, p = [0.5, 0.8, 0.9, 0.2, 0.8, 0.1])
print(t)
```
```
# Output
ValueError                                Traceback (most recent call last)
Input In [29], in <cell line: 1>()
----> 1 np.random.choice(a = [0, 1, 2, 3, 4, 5], size=None, p = [0.5, 0.8, 0.9, 0.2, 0.8, 0.1])

File mtrand.pyx:939, in numpy.random.mtrand.RandomState.choice()

ValueError: probabilities do not sum to 1
```
## Examples for how it should look like
```python
t = np.random.choice(a = [0, 1, 2, 3, 4, 5], size=None, p = [0.5, 0.8, 0.9, 0.2, 0.8, 0.1])
print(t)
```
```
# Output 1
[0, 4, 5]
# Output 2
[0, 1, 2, 4,]
# Output 3
[1, 3, 4, 5]
# Output 4
[1, 2]
# Output 5
[0, 1, 2, 3, 4, 5]
# Output 6
[]
```

**Comment by rkern** [comment]
I don't think we will be adding more semantics to `choice()` for this. Other methods can be composed straightforwardly to do the desired calculations.

```
rng = np.random.default_rng()
choices = np.array([0, 1, 2, 3, 4, 5])
p = np.array([0.5, 0.8, 0.9, 0.2, 0.8, 0.1])
mask = rng.random(size=len(p)) < p
drawn_samples = choices[mask]
```

These days, we have a fairly high bar to extending the random distribution methods. The straightforwardness of the implementation falls below the threshold, in my judgement.

**Comment by WarrenWeckesser** [comment]
Thanks for the suggestion, @rodosingh.

This process is a bunch of independent binomial samples.   According to wikipedia, this process is called [Poisson sampling](https://en.wikipedia.org/wiki/Poisson_sampling).

As @rkern has shown, this can be implemented with a couple lines of code.  Because this is a straightforward composition of existing capabilities, and because (as far as I can recall) there hasn't been historical demand for such a function, I agree with @rkern that this doesn't reach the bar for inclusion in NumPy.

**Comment by rodosingh** [comment]
Got it @rkern and @WarrenWeckesser , thanks for the reply.
