### ISSUE TITLE
BUG: unable to build with musl, 'execinfo.h' file not found

### ISSUE THREAD

**Issue by RinCat** [numpy/numpy#22084]
### Describe the issue:

Unable to build with musl since 'execinfo.h' not exists.

### Reproduce the code example:

```python
N/A
```

### Error message:

```shell
INFO: clang: numpy/core/src/multiarray/temp_elide.c
numpy/core/src/multiarray/temp_elide.c:85:10: fatal error: 'execinfo.h' file not found
#include <execinfo.h>
                    ^~~~~~~~~~~~
1 error generated.
```
```


### NumPy/Python version information:

1.23

**Comment by mattip** [comment]
How are we successfully building wheels for musl if this cannot succeed?

**Comment by RinCat** [comment]
Maybe your system doesn't have a library like libunwind so backtracing is turned off.
I do use clang + musl. This error actually common https://www.google.com/search?q=%27execinfo.h%27+file+not+found+musl

**Comment by seberg** [comment]
If execinfo is required for backtracing in this case, how come we can just skip the include?  Shouldn't some symbol from it be in use at runtime?

**Comment by charris** [comment]
> Shouldn't some symbol from it be in use at runtime?

execinfo also appears in `numpy/linalg/umath_linalg.cpp` in debug mode, but the import is disabled. @RinCat What distro are you using?

**Comment by RinCat** [comment]
> If execinfo is required for backtracing in this case, how come we can just skip the include? Shouldn't some symbol from it be in use at runtime?

execinfo is not required for other backtracing libraries.

It should have `# include <libunwind.h>` if `LDFLAGS="-unwindlib=libunwind"` did not set.
I will try to add a header test.

**Comment by RinCat** [comment]
> > Shouldn't some symbol from it be in use at runtime?
> 
> execinfo also appears in `numpy/linalg/umath_linalg.cpp` in debug mode, but the import is disabled. @RinCat What distro are you using?

I am using Gentoo, however it is experimental musl + clang system which not have official images.
If someone wanna try, I can provide a LXD image.

**Comment by RinCat** [comment]
Here is an example:
https://github.com/htop-dev/htop/blob/f3e70ab389879db5b250bab29f14acb543bfd11f/CRT.c#L29
