### ISSUE TITLE
BUG: Issue with np.arange specifically with np.arange(0.1,0.4,0.1)

### ISSUE THREAD

**Issue by heoun** [numpy/numpy#22094]
### Describe the issue:

This code `np.arange(0.1,0.4,0.1)` should return  `array([0.1, 0.2, 0.3])` but instead it returns `array([0.1, 0.2, 0.3, 0.4])`

I am on the latest numpy version '1.23.1'

### Reproduce the code example:

```python
import numpy as np
np.arange(0.1,0.3,0.1)
np.arange(0.1,0.4,0.1) #this results in including 0.4 when it should be excluded.
#array([0.1, 0.2, 0.3])
np.arange(0.1,0.5,0.1)
```

### NumPy/Python version information:

In [6]: np.__version__
Out[6]: '1.23.1'

### Context for the issue:

Using for some medical documentation parsing ICD9 codes
<img width="493" alt="Screen Shot 2022-08-07 at 11 45 38 PM" src="https://user-images.githubusercontent.com/9059722/183334981-48f9d544-71a6-4fc3-9e1d-cc53ccfbf477.png">
g

**Comment by rkern** [comment]
This is [documented behavior](https://numpy.org/doc/stable/reference/generated/numpy.arange.html). C.f. #17189 (and probably most other issues mentioning `arange` and "floating point")
