### ISSUE TITLE
BUG: Importing numpy causes error when the Windows username contains a single quote

### ISSUE THREAD

**Issue by KeepLost** [numpy/numpy#22093]
### Describe the issue:

Just as the title suggests, on Windows when the username contains a single quote, importing the numpy package would cause an error.

### Reproduce the code example:

```python
python -c "import numpy as np"
```

### Error message:

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Praxelogist's Lab\.conda\envs\losthub\lib\site-packages\numpy\__init__.py", line 124, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Users\Praxelogist's Lab\.conda\envs\losthub\lib\site-packages\numpy\__config__.py", line 14
    blas_info={'libraries': ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'include_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\include'], 'language': 'f77', 'define_macros': [('HAVE_CBLAS', None)]}
                                                                                                                        ^
SyntaxError: invalid syntax
```

### NumPy/Python version information:

numpy==1.23.1

python==3.9.13

### Context for the issue:

The reason behind the error is that in the `__config__.py` file, the file paths specified by the four dictionaries `blas_info`, `blas_opt_info`, `lapack_info`, and `lapack_opt_info` are hard-coded. Since the file path is represented as a string enclosed in single quotes, and the string itself contains a Windows username that also contains a single quote, it's unavoidable that the string would be broken, resulting in a syntax error, e.g.
```python
blas_info={'libraries': ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'include_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\include'], 'language': 'f77', 'define_macros': [('HAVE_CBLAS', None)]}
blas_opt_info={'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'libraries': ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'include_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\include'], 'language': 'f77'}
lapack_info={'libraries': ['lapack', 'blas', 'lapack', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'language': 'f77'}
lapack_opt_info={'libraries': ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'language': 'f77', 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'include_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\include']}
```

**Comment by rkern** [comment]
See [my comment](https://github.com/scipy/scipy/issues/16803#issuecomment-1207650855) on the corresponding `scipy` issue. I think it's a bug with the `conda` packaging, not upstream.

**Comment by bashtage** [comment]
> See [my comment](https://github.com/scipy/scipy/issues/16803#issuecomment-1207650855) on the corresponding `scipy` issue. I think it's a bug with the `conda` packaging, not upstream.

If someone wanted to check, they could (using a name with a single quote) install python.org python and then pip install numpy using the python.org python.

**Comment by ganesh-k13** [comment]
This should get solved as https://github.com/numpy/numpy/pull/22769 is merged and meson becomes the default way to build.

**Comment by mattip** [comment]
Closing. This relates to the old distutils-based `show_config`
