### ISSUE TITLE
BUG: np.vander overflows

### ISSUE THREAD

**Issue by randall-romero** [numpy/numpy#22092]
### Describe the issue:

np.vander can silently overflow for large matrices

Vander returns an array of dtype='int32', which can easily overflow. For example, when computing Vandermonde matrix for array [1,2,3,...,11] one of the entries returned by np.vander is negative, which clearly it makes no sense in this case.

### Reproduce the code example:

```python
import numpy as np

# Returns False, despite it must be true!
(np.vander(np.arange(1,12)) > 0).all()
```

### NumPy/Python version information:

1.21.5 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

I was just preparing a class to illustrate how ill-conditioned  Vandermonde matrices are, how it can worsen as the matrix gets bigger. This class is for teaching numerical methods to economists.  [for my own purposes, it can be fixed using [1,2,3,...11] as floats instead of integers]

**Comment by mattip** [comment]
The core thing to understand is that `vander` will use the dtype of whatever ndarray is used as input. In the case of `np.arange(1, 12)` on windows, this give an ndarray with `dtype==np.int32`. You can use this as a learning moment for the students to teach them how dtypes are fixed throughout calculations (some methods allow choosing the dtype), how numpy does not protect from integer overflow, and to recommend as best-practices that they always think about and then specify the desired dtype when creating an ndarray: `np.arange(1, 12, dtype=np.int64)`

**Comment by randall-romero** [comment]
Thank you for your reply! I agree, I will follow you suggestion and use this example as a learning opportunity instead. Thanks!
