### ISSUE TITLE
Are we ready for Python 3.11 wheels?

### ISSUE THREAD

**Issue by charris** [numpy/numpy#22097]
This is just to ping @mayeut to discover the status of manylinux2014 now that Python 3.11.0rc1 is out. NumPy would like to support that version in the 1.23.2 release.

**Comment by stonebig** [comment]
would we get at same time numpy and scipy (and mkl and blas and blis) wheels for python-3.11.0rc1 ?

**Comment by mayeut** [comment]
Manylinux images now have cpython 3.11rc1

**Comment by charris** [comment]
NumPy 1.23.2 has been released with Python 3.11 wheels.
