### ISSUE TITLE
`NPY_INLINE` not documented, and unclear if it's still relevant with C99's `inline`

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#22100]
I came across this when trying to get rid of `npy_math.h` usage in SciPy. `NPY_INLINE` is used a fair bit, and it is likely fine to replace with plain `inline` now that C99 is required. I'm not sure though. The implementation is `NPY_INLINE` is: https://github.com/numpy/numpy/blob/a642e1f0437571be82966069484dd359732c852b/numpy/core/include/numpy/npy_common.h#L134-L145

The one recent change is commit 50d69741cb35db1a535282060c51e536a863ce99, which fixes an issue with `clang-cl` (making it use plain `inline`). MSVC should be supporting `inline` as well now; the use of `__inline` is very old. For other compilers than GCC, Clang and MSVC the define is empty, and could probably use `inline` too.

Any reason someone knows of not to use plain `inline` in SciPy?

**Comment by charris** [comment]
> Any reason someone knows of not to use plain inline in SciPy?

The new C++ code uses the standard `inline` and I suggest using it for new code. We could also replace `NPY_INLINE` globally. That would be a lot of churn, but it would make onboarding new developers a bit easier if we use standard language features.

**Comment by seberg** [comment]
Agreed with Chuck, the only reason to keep using `NPY_INLINE` is to keep it a bit consistent within or between files.  I would be :+1: to just do the cleanup, its probably not even a very large PR anyway.

**Comment by rgommers** [comment]
Thanks for the feedback @charris and @seberg. I opened a PR for SciPy, it's indeed an easy cleanup. For NumPy I agree we can do the same.

**Comment by charris** [comment]
@Micky774 Want to take a shot at this cleanup?

**Comment by Micky774** [comment]
> @Micky774 Want to take a shot at this cleanup?

Sure!
