### ISSUE TITLE
BUG: np.polynomial.Polynomial.fit produces wrong results

### ISSUE THREAD

**Issue by sam-s** [numpy/numpy#22104]
### Describe the issue:

`np.polynomial.Polynomial.fit` produces polynomials that do _not_ fit the data.

as the code example shows, the result is very different from that of `np.polyfit`

### Reproduce the code example:

```python
import np
x = [0,1,2,3,4]
y = [i*i for i in x] 
p1 = np.polyfit(x,y,2)
# ==> x^2
np.isclose(y,np.poly1d(p1)(x)).all() 
# ==> True
p2 = np.polynomial.Polynomial.fit(x,y,2)
# ==> 4+8x+4x^2 = (2(x+1))^2
np.polynomial.polynomial.polyval(x,p2.coef)
# ==> array([  4.,  16.,  36.,  64., 100.])
```

### NumPy/Python version information:

1.23.1 
3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]

### Context for the issue:

https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html recommends using `np.polynomial.Polynomial.fit` instead of `np.polyfit`

**Comment by charris** [comment]
You are evaluating it incorrectly.
```
In [1]: from numpy.polynomial import Polynomial as P

In [2]: x = np.array([0,1,2,3,4])
   ...: y = np.array([i*i for i in x])

In [3]: p = P.fit(x, y, 2)

In [4]: p(x)
Out[4]: 
array([-4.4408921e-16,  1.0000000e+00,  4.0000000e+00,  9.0000000e+00,
        1.6000000e+01])

In [5]: p.convert()
Out[5]: Polynomial([-4.44089210e-16, -3.99680289e-15,  1.00000000e+00], domain=[-1.,  1.], window=[-1.,  1.])
```
Polynomial.fit uses scaled and shifted polynomials for numerical reasons. If you want the usual polynomials, you need to use the convert method.

**Comment by sam-s** [comment]
```
In [197]:
x
Out [197]:
[0, 1, 2, 3, 4]

In [196]:
p2
Out [196]:
Polynomial([4., 8., 4.], domain=[0., 4.], window=[-1.,  1.])

In [195]:
p2(x)

Truncated Traceback (Use C-c C-$ to view full TB):
File ~/.virtualenvs/myself/lib/python3.10/site-packages/numpy/polynomial/_polybase.py:482, in ABCPolyBase.__call__(self, arg)
    480 def __call__(self, arg):
    481     off, scl = pu.mapparms(self.domain, self.window)
--> 482     arg = off + scl*arg
    483     return self._val(arg, self.coef)

TypeError: can't multiply sequence by non-int of type 'numpy.float64'
```

**Comment by charris** [comment]
Note that the evaluation is also intended to work for object values, which is why the list isn't automatically converted to an array.

**Comment by sam-s** [comment]
Interesting, thank you.

Then what is `np.polynomial.polynomial.polyval` for?
How do I convert `Polynomial` to something suitable for `np.polynomial.polynomial.polyval`?

**Comment by charris** [comment]
All those routines are basically building blocks for the class objects, they are there for those who want to roll their own.  In retrospect, they could have been made private. An exception would be the multi-dimensional versions, never could decide what a class object for that should look like.
