### ISSUE TITLE
DOC: Clarify random number generation in distributed parallel context

### ISSUE THREAD

**Issue by RossBoylan** [numpy/numpy#22119]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.SeedSequence.html
https://numpy.org/doc/stable/reference/random/parallel.html

All the examples describe the spawning as something that is done centrally, leaving me unclear how or if to use this in a decentralized context.  I have Python simulations spawned by a non-python program; each simulation receives the common seed and a simulation number.  Following the docs, it seems the only guarantee is that if each of the simulations spawns all of  the child sequences and then picks its particular one I'll get reproducible independent streams.  This seems very wasteful.

The signature in the documentation for `numpy.random.SeedSequence` does not include `n_children_spawned` though it is listed as one of the parameters.

### Idea or request for content:

1. Do these 2 pieces of code produce the same result?
```python
ss = SeedSequence(MySeed)  # MySeed is a constant passed to every child
bg = ss.spawn(1000)[MyIteration] # MyIteration is the index of this particular simulation in the 1000 simulations
# use bg
```

```python
ss = SeedSequence(MySeed, n_children_spawned=max(0, MyIteration-1))
bg = ss.spawn(1)
# use bg
```
The documentation says that `n_children_spawned` should only be used "if reconstructing a SeedSequence from a serialized form" which doesn't seem to cover what I'm doing.  Unless using an explicit seed does qualify.

2. `spawn_key` is "A third source of entropy".  I presume the `entropy` argument was the first.  What is the second?
3. `spawn_key` is "used internally when calling SeedSequence.spawn".  So if one uses the seed sequence directly, it's completely irrelevant?
4. Will the results from `ss.spawn(3)` match the first 3 results of `ss.spawn(5000)`?
5. What is the recommended way to produce independent, repeatable random numbers with only the weak central information of a seed and the simulation #?

Using `randomgen` I did this:
```python
from randomgen import Generator, PCG64


def main():
	global RG  # the random generator
	args = parse_args()
	seed = args.seed
	if seed:
		RG = Generator(PCG64(seed, args.iteration, mode="sequence"))
	else:
		RG = Generator(PCG64(mode="sequence"))
```
But that doesn't seem to have survived the transition to `NumPy`.

**Comment by rkern** [comment]
Important one first:

5. In your case, where your Python program is spawned by someone else, and each child process has been given the root seed number and a process ID, you can just ignore the `spawn()` method. You don't need it.

Note that `SeedSequence` (and `default_rng()`) can accept not just a single seed integer but a sequence of (non-negative) integers. So you can do the following:

```python
rng = np.random.default_rng([MyIteration, MySeed])
```

1. In spirit, yes (you have to remove the `-1`, though). But you don't really have to do anything like that to achieve your goals here.

2. That's a leftover from an earlier iteration. Thanks for spotting it. We did have a second argument sandwiched between there for other purposes.

3. Essentially, yes. It's largely an implementation detail.

4. If done on equivalent `SeedSequence` objects, yes. Note that calling `spawn()` modifies internal state so that calling `ss.spawn(n); ss.spawn(n)` in sequence gives different results. So start with fresh ones, and you can verify that this is true.

```
[~]                                                                                                                                                                                                                  
|16> np.random.SeedSequence(10).spawn(3)                                                                                                                                                                             
[SeedSequence(
     entropy=10,
     spawn_key=(0,),
 ),
 SeedSequence(
     entropy=10,
     spawn_key=(1,),
 ),
 SeedSequence(
     entropy=10,
     spawn_key=(2,),
 )]

[~]                                                                                                                                                                                                                  
|17> np.random.SeedSequence(10).spawn(5)                                                                                                                                                                             
[SeedSequence(
     entropy=10,
     spawn_key=(0,),
 ),
 SeedSequence(
     entropy=10,
     spawn_key=(1,),
 ),
 SeedSequence(
     entropy=10,
     spawn_key=(2,),
 ),
 SeedSequence(
     entropy=10,
     spawn_key=(3,),
 ),
 SeedSequence(
     entropy=10,
     spawn_key=(4,),
 )]
```

**Comment by rkern** [comment]
And yes, I do agree that there should be another section there on using lists of integers for such scenarios.

**Comment by RossBoylan** [comment]
Thank you so much; that's just the information I needed.

Further thoughts:

Scenario: Extending the Number of Simulations
====================================

I realize some of my questions are implicitly addressing another scenario: You run 1,000 simulations, and then you decide you want to run 2,000 more (for a total of 3,000).

If doing the one at a time, distributed scenario--my concern--using your multiple seed solution it is clear how to extend the simulations and clear that the original 1,000 simulations are reproducible and independent of the total number of simulations.  This assumes the that the second simulation would use MyIteration ranging from 1,000 to 3,000, not 0 to 2,000 (which would be pointless at best for 0 to 1,000).

For the original `spawn` based strategy your answer to 4 guarantees that the first 1,000 are not affected by how many total streams are generated, and I think your answer to 1 indicates it is a way to avoid having to regenerate (and then toss) the first 1,000 streams when doing 1,000 to 3,000.

Correction
========

Agreed that the -1 in my code for item 1 was a mistake (flipping between 0 and 1 based languages is quite a challenge).

Entropy, and the Safety of Using System Entropy
=====================================

On the "third source of entropy" (item 2): in some sense the `entropy` argument really encompasses 2 sources of entropy.  If it is 'None' one gets some system-defined source of entropy (not sure if the docs can be very specific about that or not).  Otherwise, the arguments to `entropy` are themselves a source of entropy.

For `entropy=None` it would be helpful to indicate exactly how random the state is.  Perhaps more accurately, the current documents appear to make some strong claims that it is very random, and I'm not sure  that's true.

https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.html says about `seed`

> If None, then fresh, unpredictable entropy will be pulled from the OS.

and https://numpy.org/doc/stable/reference/random/bit_generators/index.html says

>  We recommend that a stochastic program defaults to using entropy from the OS so that each run is different.

This seems like a pretty strong endorsement of something that has historically been problematic.  Specifically, default entropy often comes from the system clock, which means that multiple processes or threads may not get "fresh, unpredictable entropy".  In fairness, the current `spawn` based model outlined in the current docs would not have this problem because all the bit generator streams are generated in one process before multi-processing happens.  Put  slightly differently, the multiple streams don't come  from multiple calls with `entropy=None` but from a single such call and then a call to `spawn()`.  But for other useage patterns, can one really count on the independence of the streams when `entropy=None`?

Some OS's do have high and low-quality sources of entropy available (clocks being a low-quality source), but not all.  And if `numpy.random` is using the high quality source by default, that comes with its own problems, namely exhaustion of entropy.  In general there are hardware and network sources of entropy available, and I'm not sure how they figure in.  I supposed mostly one could use them to get seed sequences to feed into the `NumPy` machinery.  Or  spend a lot time figuring out how to integrate them into `NumPy`.

**Comment by rkern** [comment]
> Actually, I think there's still room for one problem: conceivably the results for 1,000 to 3,000 generated starting at 1,000 differ from what one would get if doing 0 to 3,000 in one go.

The following are designed to be equivalent:

```python
root_ss = np.random.SeedSequence(seed)
children = root_ss.spawn(3000)
```

```python
root_ss = np.random.SeedSequence(seed)
children = []
children.extend(root_ss.spawn(1000))
# Some time later.
children.extend(root_ss.spawn(1000))
# And again.
children.extend(root_ss.spawn(1000))
```

As for the case of `entropy=None`, we use the best entropy source that the OS gives Python access to via [`secrets.randbits()`](https://docs.python.org/3/library/secrets.html). That's designed to be an entropy source suitable for the generation of cryptographic keys. The precise details are OS-specific, but it's always just about the best that one can do, and definitely the best that `numpy` can do as a default.
