### ISSUE TITLE
BUG: Incorrect documentation for np.stack axis argument

### ISSUE THREAD

**Issue by kratsg** [numpy/numpy#22126]
### Describe the issue:

If you look at the current docstring (https://github.com/numpy/numpy/blob/4ee7b891ee9c3e5d0a805471eb03fb09f5cd65df/numpy/core/shape_base.py#L382-L398) - it seems to indicate that `axis` should be an `Optional[int]` type.

All the current overloads indicate that `axis` should be `SupportsIndex` (https://github.com/numpy/numpy/blob/4ee7b891ee9c3e5d0a805471eb03fb09f5cd65df/numpy/core/shape_base.pyi#L63-L89). The documentation appears to be incorrect that `axis` is an optional type (must be specified).

### Reproduce the code example:

```python
import numpy as np
a = np.array([1,2,3])
np.stack([a, a], axis=None)
```

### Error message:

```shell
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    np.stack([a,a], axis=axis)
  File "<__array_function__ internals>", line 180, in stack
  File "/Users/kratsg/.pyenv/versions/pyhf-dev/lib/python3.8/site-packages/numpy/core/shape_base.py", line 429, in stack
    axis = normalize_axis_index(axis, result_ndim)
TypeError: an integer is required (got type NoneType)
```

### NumPy/Python version information:

1.22.3 3.8.6 (default, Oct 28 2020, 19:59:21) 
[Clang 10.0.1 (clang-1001.0.46.4)]

**Comment by mattip** [comment]
> `np.stack([a, a], axis=None)`

Why use None, the default is `0`.

**Comment by seberg** [comment]
Looks all correct, `None` is not the same as "default" and must not be here (it would have a very different meaning).  Unless I am missing something?
