### ISSUE TITLE
Help for Pyinstaller pack *.exe(it flashed by when i open the *.exe)

### ISSUE THREAD

**Issue by aloeloe1** [numpy/numpy#22128]
from pynput.keyboard import Key,Controller
import time
”“”
codes
“”“

terminal in pycharm

PS C:\Users\zc262\PycharmProjects\pythonProject1> pyinstaller -F typ_and_press_enter.py
43 INFO: PyInstaller: 5.3
43 INFO: Python: 3.9.10
52 INFO: Platform: Windows-10-10.0.22000-SP0
52 INFO: wrote C:\Users\zc262\PycharmProjects\pythonProject1\typ_and_press_enter.spec
53 INFO: UPX is not available.
55 INFO: Extending PYTHONPATH with paths
['C:\\Users\\zc262\\PycharmProjects\\pythonProject1']
206 INFO: checking Analysis
206 INFO: Building Analysis because Analysis-00.toc is non existent
206 INFO: Initializing module dependency graph...
207 INFO: Caching module graph hooks...
217 INFO: Analyzing base_library.zip ...
1781 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
1782 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib'
3382 INFO: Caching module dependency graph...
3478 INFO: running Analysis Analysis-00.toc
3480 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\zc262\AppData\Local\Programs\Python\Python39\python.exe
3507 INFO: Analyzing C:\Users\zc262\PycharmProjects\pythonProject1\typ_and_press_enter.py
3509 INFO: Processing module hooks...
3510 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3511 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3511 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3511 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3660 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3661 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3684 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3685 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3686 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3687 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3688 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3689 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3714 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3789 INFO: checking Tree
3790 INFO: Building Tree because Tree-00.toc is non existent
3790 INFO: Building Tree Tree-00.toc
3824 INFO: checking Tree
3825 INFO: Building Tree because Tree-01.toc is non existent
3825 INFO: Building Tree Tree-01.toc
3873 INFO: checking Tree
3874 INFO: Building Tree because Tree-02.toc is non existent
3874 INFO: Building Tree Tree-02.toc
3884 INFO: Looking for ctypes DLLs
3891 INFO: Analyzing run-time hooks ...
3892 INFO: Including run-time hook 'C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
3895 INFO: Looking for dynamic libraries
4142 INFO: Looking for eggs
4142 INFO: Using Python library C:\Users\zc262\AppData\Local\Programs\Python\Python39\python39.dll
4142 INFO: Found binding redirects:
[]
4153 INFO: Warnings written to C:\Users\zc262\PycharmProjects\pythonProject1\build\typ_and_press_enter\warn-typ_and_press_enter.txt
4177 INFO: Graph cross-reference written to C:\Users\zc262\PycharmProjects\pythonProject1\build\typ_and_press_enter\xref-typ_and_press_enter.html
4191 INFO: checking PYZ
4191 INFO: Building PYZ because PYZ-00.toc is non existent
4191 INFO: Building PYZ (ZlibArchive) C:\Users\zc262\PycharmProjects\pythonProject1\build\typ_and_press_enter\PYZ-00.pyz
4348 INFO: Building PYZ (ZlibArchive) C:\Users\zc262\PycharmProjects\pythonProject1\build\typ_and_press_enter\PYZ-00.pyz completed successfully.
4352 INFO: checking PKG
4352 INFO: Building PKG because PKG-00.toc is non existent
4353 INFO: Building PKG (CArchive) typ_and_press_enter.pkg
5452 INFO: Building PKG (CArchive) typ_and_press_enter.pkg completed successfully.
5454 INFO: Bootloader C:\Users\zc262\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
5455 INFO: checking EXE
5455 INFO: Building EXE because EXE-00.toc is non existent
5456 INFO: Building EXE from EXE-00.toc
5456 INFO: Copying bootloader EXE to C:\Users\zc262\PycharmProjects\pythonProject1\dist\typ_and_press_enter.exe.notanexecutable
5463 INFO: Copying icon to EXE
5464 INFO: Copying icons from ['C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
5464 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
5465 INFO: Writing RT_ICON 1 resource with 3752 bytes
5465 INFO: Writing RT_ICON 2 resource with 2216 bytes
5465 INFO: Writing RT_ICON 3 resource with 1384 bytes
5465 INFO: Writing RT_ICON 4 resource with 37019 bytes
5465 INFO: Writing RT_ICON 5 resource with 9640 bytes
5465 INFO: Writing RT_ICON 6 resource with 4264 bytes
5465 INFO: Writing RT_ICON 7 resource with 1128 bytes
5471 INFO: Copying 0 resources to EXE
5471 INFO: Embedding manifest in EXE
5472 INFO: Updating manifest in C:\Users\zc262\PycharmProjects\pythonProject1\dist\typ_and_press_enter.exe.notanexecutable
5472 INFO: Updating resource type 24 name 1 language 0
5478 INFO: Appending PKG archive to EXE
5481 INFO: Fixing EXE headers
5612 INFO: Building EXE from EXE-00.toc completed successfully.
PS C:\Users\zc262\PycharmProjects\pythonProject1> 

CMD result 

C:\Users\zc262>pyinstaller -F typ_and_press_enter.py
43 INFO: PyInstaller: 5.3
43 INFO: Python: 3.9.10
52 INFO: Platform: Windows-10-10.0.22000-SP0
53 INFO: wrote C:\Users\zc262\typ_and_press_enter.spec
54 INFO: UPX is not available.
55 INFO: Extending PYTHONPATH with paths
['C:\\Users\\zc262']
202 INFO: checking Analysis
206 INFO: checking PYZ
211 INFO: checking PKG
212 INFO: Bootloader C:\Users\zc262\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
212 INFO: checking EXE
212 INFO: Rebuilding EXE-00.toc because typ_and_press_enter.exe missing
213 INFO: Building EXE from EXE-00.toc
213 INFO: Copying bootloader EXE to C:\Users\zc262\dist\typ_and_press_enter.exe.notanexecutable
223 INFO: Copying icon to EXE
225 INFO: Copying icons from ['C:\\Users\\zc262\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
231 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
231 INFO: Writing RT_ICON 1 resource with 3752 bytes
231 INFO: Writing RT_ICON 2 resource with 2216 bytes
232 INFO: Writing RT_ICON 3 resource with 1384 bytes
232 INFO: Writing RT_ICON 4 resource with 37019 bytes
232 INFO: Writing RT_ICON 5 resource with 9640 bytes
233 INFO: Writing RT_ICON 6 resource with 4264 bytes
233 INFO: Writing RT_ICON 7 resource with 1128 bytes
243 INFO: Copying 0 resources to EXE
243 INFO: Embedding manifest in EXE
247 INFO: Updating manifest in C:\Users\zc262\dist\typ_and_press_enter.exe.notanexecutable
248 INFO: Updating resource type 24 name 1 language 0
255 INFO: Appending PKG archive to EXE
260 INFO: Fixing EXE headers
376 INFO: Building EXE from EXE-00.toc completed successfully.

**Comment by mattip** [comment]
Is this a bug report, an enhancement suggestion, or something else? If a bug report, please tell us __all__ of the below (4 answers are expected): 
- what happened and what you expected to happen instead
- how it is related to NumPy
- what versions of NumPy and python are you using, and on what operating system
- how this impacts your work
