### ISSUE TITLE
BUG:  np.random.multivariate_normal gives "RuntimeWarning: covariance is not positive-semidefinite" when it is

### ISSUE THREAD

**Issue by drpepper19** [numpy/numpy#22140]
### Describe the issue:

np.random.multivariate_normal when run with a non-symmetric PD / PSD covariance matrix gives "RuntimeWarning: covariance is not positive-semidefinite". Even though it is PSD. It should warn "RuntimeWarning: covariance is not symmetric".

### Reproduce the code example:

```python
import numpy as np
cov=np.eye(2)
cov[0,1]=.5
print(cov)
print("symmetric?", (cov==cov.T).all())
print("PSD if eigvals all non-negative:", np.linalg.eig(cov)[0])
np.random.multivariate_normal(np.zeros(cov.shape[0]), cov, size=1)
```

### Error message:

```shell
RuntimeWarning: covariance is not positive-semidefinite.
  np.random.multivariate_normal(np.zeros(cov.shape[0]), cov, size=1)
```

### NumPy/Python version information:

('1.23.0', '3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]')

**Comment by bashtage** [comment]
Positive-definite matrices must be symmetric.  It isn't enough to have only positive eigenvalues.

**Comment by drpepper19** [comment]
Absolutely. But the warning should state that the problem is that is isn't symmetric, not that it isn't PSD

**Comment by drpepper19** [comment]
> Positive-definite matrices must be symmetric. It isn't enough to have only positive eigenvalues.

Absolutely. But the warning should state that the problem is that is isn't symmetric, not that it isn't PSD

**Comment by bashtage** [comment]
But it isn't pd since it isn't symmetric. Symmetry is necessary but not sufficient for PD.  I don't think one can meaningfully discuss non symmetric PD matrix because they don't exist.

**Comment by rkern** [comment]
While the current error message is strictly correct, it would be helpful to users who are not as familiar with the mathematical terminology to explicitly use the word "symmetric" somewhere in there. I don't think we should try to test explicitly for symmetry and output a message that _only_ mentions symmetry; we can tolerate a little numerical asymmetry to gracefully deal with outputs from other computations, so testing for symmetry would require applying arbitrary tolerances. But we could just say "covariance is not symmetric positive-semidefinite" to give the user more hints as to what they should check for.

**Comment by drpepper19** [comment]
> But it isn't pd since it isn't symmetric. Symmetry is necessary but not sufficient for PD. I don't think one can meaningfully discuss non symmetric PD matrix because they don't exist.

Sorry, I didn't read your original reply carefully enough. But is that accepted that PD requires symmetry? it does sound like that on [wikipedia](https://en.wikipedia.org/wiki/Definite_matrix), but not [here](https://math.stackexchange.com/questions/1964039/why-do-positive-definite-matrices-have-to-be-symmetric):
_"Positive definite matrices do not have to be symmetric, it is just rather common to add this restriction for examples and worksheet questions."_

**Comment by rkern** [comment]
Indeed, my copy of [_Matrix Computations_](https://www.google.com/books/edition/Matrix_Computations/X5YfsuCWpxMC?hl=en&gbpv=1) defines positive definiteness separately from symmetry and gives special attention to unsymmetric positive definite systems. So there's a reasonably authoritative reference that not all mathematical usage defines "positive definite" in a way that implies symmetry. It's just very, very common to do so.

**Comment by drpepper19** [comment]
OK, so given the ambiguity about whether PD implies symmetry, together with your previous point that it would regardless be helpful to users if symmetry would be mentioned in the warning, doesn't it seem best that this warning should be modified?

**Comment by WarrenWeckesser** [comment]
@drpepper19, that sounds reasonable to me.   Note that the description of `cov` already says "It must be symmetric and positive-semidefinite for proper sampling", so changing the warning to "covariance is not symmetric and positive-semidefinite" makes sense.
