### ISSUE TITLE
BUG: numpy.linalg.eigh slower than numpy.linalg.eig when broadcasting small matrices

### ISSUE THREAD

**Issue by javierttgg** [numpy/numpy#22158]
### Describe the issue:

Thank you for this amazing and crucial package. I noted that [`np.linalg.eigh`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html) is notably faster than [`np.linalg.eig`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html) when applying them to one array. 

However, `eigh` becomes slower than `eig` when broadcasting several small matrices ( $2\times 2$ is the most noticeable case).  As noted in the code example, this issue stops happening when using bigger matrices e.g. $100\times 100$.

Is this a expected behavior in spite of `eigh` already using the fact that the matrices are symmetric?

Thanks in advance.

### Reproduce the code example:

```python
import numpy as np
from time import perf_counter


def compare_times(fun1, fun2, arr):
    """ prints execution_time(fun1(arr)) / prints execution_time(fun1(arr)) """
    # fun1 execution time
    s = perf_counter()
    fun1(a)
    t1 = (perf_counter() - s)
    
    # fun2 execution time
    s = perf_counter()
    fun2(a)
    t2 = (perf_counter() - s)
    
    print(f'\t\ttime({fun1.__name__}) / time({fun2.__name__}) = {t1 / t2}')


if __name__ == "__main__":
    print("1) small symmetric matrices: 2x2")
    d = 2
    print("\t1.1) using only one array")
    a = np.random.rand(d, d)
    a = a.T.dot(a) # force symmetry
    compare_times(np.linalg.eig, np.linalg.eigh, a) # gives ~ 3
    
    print("\t1.2) using 200 arrays")
    a = np.random.rand(200, d, d)
    a = a.transpose(0, 2, 1) @ a
    compare_times(np.linalg.eig, np.linalg.eigh, a) # gives ~ 0.9
    
    print("\t1.2) using 1000 arrays")
    a = np.random.rand(1000, d, d)
    a = a.transpose(0, 2, 1) @ a
    compare_times(np.linalg.eig, np.linalg.eigh, a) # gives ~ 0.7
    
    
    print("\n2) bigger symmetric matrices: 100x100")
    d = 100
    print("\t2.1) using only one array")
    a = np.random.rand(d, d)
    a = a.T.dot(a) # force symmetry
    compare_times(np.linalg.eig, np.linalg.eigh, a) # gives ~ 4
    
    print("\t2.2) using 200 arrays")
    a = np.random.rand(200, d, d)
    a = a.transpose(0, 2, 1) @ a
    compare_times(np.linalg.eig, np.linalg.eigh, a) # gives ~ 4
    
    print("\t1.3) using 1000 arrays")
    a = np.random.rand(1000, d, d)
    a = a.transpose(0, 2, 1) @ a
    compare_times(np.linalg.eig, np.linalg.eigh, a) # gives ~ 4
```

### NumPy/Python version information:

1.21.5 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]

**Comment by seberg** [comment]
Would have to dig into the code to figure this out.  I suspect both end up calling openblas in a tight loop on each of the small matrices.

For small matrices such an approach would be dominated by overheads (setting things up, and just the function calls).  So if those differ for whatever reasons, the results are not unexpected.  However, I am not sure whether the overheads differ due to code in NumPy or due to code in openblas (or whichever linear algebra backend is used).  Linear algebra backends are like not optimized for these small cases.
