### ISSUE TITLE
BUG: inconsistent execution time of .transpose().copy()

### ISSUE THREAD

**Issue by sporadicCactus** [numpy/numpy#22151]
### Describe the issue:

The execution .transpose().copy() time varies inconsistently with the size of the input array. For certain magic sizes the execution time is significantly larger that for slightly smaller and slightly larger sizes.

The first screenshot if from my home machine, Ryzen 9 3950x. The second is from google collab (the variation is not as dramatic, but still significant). The same effect was observed on M1 macbook air and ryzen 9 5950x.

The graph shows .transpose().copy() execution time for arrays of shape (64, 192*dim). The peaks are most pronounced when dim is a multiple of 32.

<img width="500" alt="Screenshot 2022-08-18 at 20 36 40" src="https://user-images.githubusercontent.com/51837750/185481726-53d5fec9-cf95-4a90-83fc-d728125c5edf.png">
<img width="500" alt="Screenshot 2022-08-18 at 20 32 55" src="https://user-images.githubusercontent.com/51837750/185481649-e1ac4aea-cb42-49d9-abe9-9cc801fd7c41.png">
<img width="500" alt="exec_time_graph" src="https://user-images.githubusercontent.com/51837750/185479504-0d08ec44-2f97-4ee4-ac98-97398e804b9b.png">

### Reproduce the code example:

```python
import numpy as np
import timeit

exec_times = []

for dim in [383, 384, 385]:
    x = np.random.rand(64, 192*dim)
    repeats, time = timeit.Timer(lambda: x.transpose().copy()).autorange()
    exec_times.append(round(1000*time/repeats, 2))

print('Execution times, ms:', exec_times)
```

### NumPy/Python version information:

1.23.2 3.8.11 (default, Aug 16 2021, 01:34:40)
[GCC 9.3.0]

### Context for the issue:

I discovered this behaviour when I was trying to tune my memory-intensive numpy operations by experimenting with different array layouts. At some point I found that the rearranging itself was taking a suspiciously large ammount of time.

**Comment by seberg** [comment]
Yes, this is normal cache and malloc affects.  NumPy is not particularly fast with transposing, but anything beyond that, this will due to how memory allocation works and page-faults due to this.

You can probably mess with things like `MALLOC_MMAP_THRESHOLD_` environment variable (and some such), or preload other malloc providers, like `mimalloc` IIRC.  But I currently doubt NumPy should worry about it.

**Comment by sporadicCactus** [comment]
@seberg thanks for your answer! Could you elaborate a bit?
I can understand why the execution time would rise disproportionally with increasing matrix size as we hit cache sizes. But why does execution time peak at specific sizes, while being significantly lower for slightly bigger and slightly smaller sizes?

**Comment by seberg** [comment]
As I said, it has to do with malloc, memory mapping and page faulting. See https://mail.python.org/archives/list/numpy-discussion@python.org/message/576S4MNP2WABE6TWDJNLSEZLEOZSNC3Z/ and that thread for some details.

I suspect we can close the issue, so just doing that.
