### ISSUE TITLE
BUG: numpy fails to cross-compiling with setuptools >= 64.x

### ISSUE THREAD

**Issue by th0ma7** [numpy/numpy#22157]
### Describe the issue:

While preparing python 3.10.6 update I've took care to update all build requirements, including setuptools.
It hapens that it made numpy to fail to build starting with setuptools >= 64.x (also fails on 65.x).
Full build logs can be found here: https://github.com/SynoCommunity/spksrc/runs/7917533394?check_suite_focus=true
Associated SynoCommunity PR: https://github.com/SynoCommunity/spksrc/pull/5395

Note: Associated setuptools bug created https://github.com/pypa/setuptools/issues/3549

### Reproduce the code example:

```python
n/a
```

### NumPy/Python version information:

n/a

**Comment by rgommers** [comment]
Please pin `setuptools` to the last version that works for you - see gh-22154

**Comment by seberg** [comment]
I don't think there is anything to be done about supporting newer setuptools versions, so closing.  Please reopen if I miss something.

**Comment by boegel** [comment]
> Please pin `setuptools` to the last version that works for you - see [gh-22154](https://github.com/numpy/numpy/pull/22154)

@rgommers What's the long term plan here to keep supporting from-source builds of numpy (cross-compiled, or not), any reference to the changes being made to not rely on the deprecated `numpy.distutils` anymore for that?
