### ISSUE TITLE
BUG: genfromtxt will cast all columns to the largest length if all columns are string type

### ISSUE THREAD

**Issue by simonkenny** [numpy/numpy#22160]
### Describe the issue:

When using the genfromtxt function with dtype = None, if all columns are strings the function will generate an output array where all dtypes are the maximum length.

Row 2307 numpy/lib/npyio.py correctly calculates the minimum string length required for each column.
```python
        # Update string types to be the right length
        sized_column_types = column_types[:]
        for i, col_type in enumerate(column_types):
            if np.issubdtype(col_type, np.character):
                n_chars = max(len(row[i]) for row in data)
                **sized_column_types[i] = (col_type, n_chars)**
```

Row 2313  numpy/lib/npyio.py then ignores this and treats the columns as uniform because the base type is str for all columns, with no reference to sized_column_types.
```python
            # If the dtype is uniform (before sizing strings)
            base = {
                c_type
                for c, c_type in zip(converters, column_types)
                if c._checked}
            **if len(base) == 1:**
                uniform_type, = base
                (ddtype, mdtype) = (uniform_type, bool)
```

This can be fixed by changing line 2319 in numpy/lib/npio.py from
```python
            if len(base) == 1:
```
to
```python
            if len(base) == 1 and base != {np.str_}: 
```
### Reproduce the code example:

```python
txt = ['a|a|aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','b|bc|bbbbbbbbbbbbbbbbbbbbbbbbb']
a = np.genfromtxt(txt,dtype=None,delimiter='|',unpack=True,encoding='utf8')
for col in a:
    print(col.dtype)

Output:
<U33
<U33
<U33
```
This is avoided if this direct case is avoided, by having multiple types or including names. 
```python
txt = ['1|a|aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','1|bc|bbbbbbbbbbbbbbbbbbbbbbbbb']
a = np.genfromtxt(txt,dtype=None,delimiter='|',unpack=True,encoding='utf8')
for col in a:
    print(col.dtype)

Output:
int32
<U2
<U33
```

or

```python
txt = ['a|a|aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','a|bc|bbbbbbbbbbbbbbbbbbbbbbbbb']
a = np.genfromtxt(txt,dtype=None,delimiter='|',unpack=True,encoding='utf8',names=['col1','col2','col3'])
for col in a:
    print(col.dtype)

Output:
<U1
<U2
<U33
```

### NumPy/Python version information:

1.22.4 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

### Context for the issue:

When importing a file with one large column of ~160 characters, and 10 other short columns (2-5 characters) it is significantly increasing the memory requirement as it allocates 160 characters for all columns.

**Comment by seberg** [comment]
NumPy arrays are homogenous, if you want different behavior, the only option is to use `object` dtype.

**Comment by simonkenny** [comment]
genfromtxt with separator returns a structured datatype.
Currently this is coercing all datatypes within the structure to be the same length. This is not within a single array. Other code paths within the same function return the expected behaviour.

**Comment by seberg** [comment]
Well, its weird since it thinks it should drop the names when they were not explicitly given and all the dtypes match.  But all strings are "uniform" enough in that sense.
I don't know if genfromtext should ever do that, but I am not sure it should be changed. It would be strange to transition you to a structured dtype from a nonstructured one.

**Comment by simonkenny** [comment]
No problems, thanks for taking the time to respond.

For anyone else who runs into this - putting dummy names in will force numpy to allocate string size column by column reducing memory consumption.
