### ISSUE TITLE
Scheduled nightly builds do not do aarch64 builds.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#22172]
Those builds seem to be run using the multibuild machinery on Saturday nights. The actions builds are run on Wednesday nights. We should should enable both builds to be run via actions so we can disable multibuild entirely. Note that release builds runs do both.

**Comment by mattip** [comment]
The aarch64 builds are done [on travis](https://app.travis-ci.com/github/numpy/numpy/builds/254813569). The run a few hours ago succeeded, and uploaded aarch64 wheels to https://anaconda.org/scipy-wheels-nightly/numpy/files.

**Comment by charris** [comment]
Yep, looks like everything worked this morning.
