### ISSUE TITLE
BUG: inconsistent behaviour of broadcasting with addition assignment operator

### ISSUE THREAD

**Issue by paoloalba** [numpy/numpy#22175]
### Describe the issue:

numpy throws an exception when trying to sum two arrays with compatible/broadcastable shapes when using addition assignment operator.

### Reproduce the code example:

```python
import numpy as np
a1 = np.array([1.0])
a2 = np.array([12.0, 4])

ccc = 0
ccc += a1
print(a1.shape, a2.shape, ccc.shape)
ccc += a2
# ccc = ccc + a2 this line works as expected
```

### Error message:

```shell
ValueError: non-broadcastable output operand with shape (1,) doesn't match the broadcast shape (2,)
```

### NumPy/Python version information:

1.22.4 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]

**Comment by mattip** [comment]
`ccc` is a Python `int`. What would you expect `ccc` to be after `ccc += a2` ?

**Comment by paoloalba** [comment]
`ccc` after the first assignment (`ccc += a1`) is an array of shape `(1,)` . After `ccc += a2` I would expect it to be an array of the same shape as `a2`, i.e. `(2,)`

**Comment by mattip** [comment]
It is bad enough NumPy modifies the type of `ccc` in the first assignment (this could be considered a bug). At least NumPy refuses to change the shape of an object inplace.

**Comment by paoloalba** [comment]
Indeed I would expect not to be a problem to change the shape in place, since we are talking about python. I close the issue since I understand that the topic is known and so desired. Maybe an exceptio with some explicit reference to the conservation of shape would be useful
