### ISSUE TITLE
BUG: test_rint_big_int fails on Core 2 Duo CPU due to precision

### ISSUE THREAD

**Issue by Apteryks** [numpy/numpy#22170]
### Describe the issue:

Building Numpy 1.23.1 with GNU Guix on an old Core 2 Duo (Intel Q6700) CPU, I stumbled on the `test_rint_big_int` failure (see below for the error message).

The error seems to be related to precision, perhaps specific to this x86_64 architecture 

### Reproduce the code example:

```python
It seems to be reproducible every time I build on this Core 2 Duo machine.
```
Reproducible by disabling CPU feature `SSE41` on runtime via:

```Bash
export NPY_DISABLE_CPU_FEATURES="SSE41"
```

### Error message:

```shell
=================================== FAILURES ===================================
______________________________ test_rint_big_int _______________________________
[gw0] linux -- Python 3.9.13 /gnu/store/ir68khi30jzdlcn9sjw0anlgsgsjfjfi-python-3.9.13/bin/python3

    def test_rint_big_int():
        # np.rint bug for large integer values on Windows 32-bit and MKL
        # https://github.com/numpy/numpy/issues/6685
        val = 4607998452777363968
        # This is exactly representable in floating point
        assert_equal(val, int(float(val)))
        # Rint should not change the value
>       assert_equal(val, np.rint(val))
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: 4607998452777363968
E        DESIRED: 4.6079984527773635e+18

val        = 4607998452777363968

/gnu/store/bg6dygk3x2dpc15s40k61hy37nzhaiw2-python-numpy-1.23.1/lib/python3.9/site-packages/numpy/core/tests/test_umath.py:3875: AssertionError
=========================== short test summary info ============================
FAILED ../../core/tests/test_umath.py::test_rint_big_int - AssertionError: 
= 1 failed, 17805 passed, 1370 skipped, 35 xfailed, 7 xpassed in 474.41s (0:07:54) =
error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "./runtests.py" arguments: ("-vv" "--no-build" "--mode=fast" "-j" "4" "--" "-n" "4" "-k" "not test_float_remainder_overflow and not test_pareto") exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 476.8 seconds
```

### NumPy/Python version information:

1.23.1

### Context for the issue:

Occurs while running the test suite during packaging.

EDIT(Sayed): Reproduce

**Comment by seberg** [comment]
What is the compiler and glibc version?  How exactly are you building NumPy (any additional compiler flags?).
Also, could you test what `np.array([4607998452777363968]).astype(np.float64)` gives to make sure that it is indeed `rint` that is rounding and not the cast already (that seems very unlikely).

**Comment by Apteryks** [comment]
The compiler is GCC 10.4.0, and glibc is at 2.33.  The direct dependencies used in the build environment are:
```
bash@5.1.16 gfortran@10.4.0 openblas@0.3.20 python-cython@0.29.30 python-hypothesis@6.43.3
+ python-pytest-xdist@2.5.0 python-pytest@6.2.5 python-typing-extensions@4.3.0
```
The build uses the classic setuptools build, and doesn't have any particular configuration other than setting NPY_NUM_BUILD_JOBS for parallelism and defining a site.cfg file with an openblas section so that its library and headers are found.

**Comment by seberg** [comment]
@seiko2plus is this plausibly SIMD related?  It seems like an oddly niche issue otherwise, since a common test failure should have been reported before.

**Comment by seiko2plus** [comment]
@seberg, It seems so, there's no native support for `rint` on `Intel Q6700` since it doesn't support instruction set of `SSE4.1`, so probably the issue lies in here:
https://github.com/numpy/numpy/blob/cfad62fd73c2a0f3d0dc4d73989071e331898a09/numpy/core/src/common/simd/sse/math.h#L287-L294

**Comment by seiko2plus** [comment]
Disable feature `SSE41` can reproduce this error on modern x86 CPUs through:
```Bash
export NPY_DISABLE_CPU_FEATURES="SSE41"
```
