### ISSUE TITLE
DOC: Partition introselect algorithm characteristics are wrong.

### ISSUE THREAD

**Issue by sapiosexual** [numpy/numpy#22186]
### Issue with current documentation:

[Here](https://numpy.org/doc/stable/reference/generated/numpy.partition.html) introselect stats are stated as 
`‘introselect’ | 1 | O(n) | 0 | no`
But it has to be 
`‘introselect’ | O(n) | O(nlogn) | 0 | no`

**Comment by Kaushik-Iyer** [comment]
Can I make the changes?

**Comment by melissawm** [comment]
@Kaushik-Iyer feel free to submit a PR - if you can provide a source for that info (a reference, paper or description of the algorithm), it would be even better.

**Comment by Kaushik-Iyer** [comment]
Okay I'm on it

**Comment by Kaushik-Iyer** [comment]
Please let me know if I went wrong anywhere in the contributing rules, this is my first time contributing to this project!

**Comment by sapiosexual** [comment]
https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.14.5196&rep=rep1&type=pdf
Original paper for introsort/introselect.

**Comment by seberg** [comment]
Closing the issue, since it is correct.  As noted on the PR, there could be an improvement in the docs though to clarify (e.g. mentioning that the speed is a "rank").
