### ISSUE TITLE
BUG: ndarray subclasses always require both type arguments at runtime

### ISSUE THREAD

**Issue by colehaus** [numpy/numpy#22185]
### Describe the issue:

For ordinary generic classes, (e.g. `class Foo(Generic[A, B])`) subclasses can fix one or more of the generic parameters (e.g. `class FooSubclass(Foo[Any, A])`. After doing so, any reference to the type only has to supply the remaining free `TypeVar`s (e.g. `FooSubclass[float]` instead of `FooSubclass[Any, float]`. This doesn't seem to work with `ndarray`. No matter how many generic parameters are fixed at subclass definition time, future references to the subclass type throw an error at runtime when not given two types.

### Reproduce the code example:

```python
from typing import Any, Generic, TypeAlias, TypeVar

import numpy as np

A = TypeVar("A")
B = TypeVar("B")

class Foo(Generic[A, B]): ... # Define two parameter generic analogous to ndarray
class FooSubclass(Foo[Any, A]): ... # Define partially saturated subclass

class Subclass(np.ndarray[Any, A]): ... # Define partially saturated subclass

x: TypeAlias = Foo[Any, A] # Define partially saturated TypeAlias. No problem
y: TypeAlias = x[float] # Use partially saturated TypeAlias. No problem
z: TypeAlias = FooSubclass[float] # Use partially saturated subclass. No problem 

a: TypeAlias = np.ndarray[Any, A] # Define partially saturated TypeAlias. No problem
b: TypeAlias = a[float] # Use partially saturated TypeAlias. No problem
c: TypeAlias = Subclass[float] # Use partially saturated subclass. Problem
```

### Error message:

```shell
Traceback (most recent call last):
  File "temp.py", line 19, in <module>
    c: TypeAlias = Subclass[float]
TypeError: Too few arguments for Subclass
```

### NumPy/Python version information:

1.22.4 3.10.1 (main, Dec  6 2021, 18:38:26) [GCC 10.3.0]

### Context for the issue:

My initial motive was subclassing `ndarray` and using the subclass type to witness validations (e.g. that the matrix is a covariance matrix) (see the "smart constructor" pattern). But more broadly, this bug seems like it would affect almost anyone who is trying to subclass `ndarray` and also use Python's typing features.

**Comment by BvB93** [comment]
Thanks for the report @colehaus; this is indeed a rather problematic oversight from when `__class_getitem__` was first implemented. PR https://github.com/numpy/numpy/pull/22212 has just been created in order to resolve the issue.
