### ISSUE TITLE
BUG: WSL is missing full `longdouble` support (WSL, not NumPy probably)

### ISSUE THREAD

**Issue by TigerHou2** [numpy/numpy#22187]
### Basic Information
Platform: WSL Ubuntu-20.04
Native OS: Windows 10, Version 10.0.19044 Build 19044
Using Python 3.10.6 from conda-forge within a conda environment
NumPy 1.23.2 installed using `pip install numpy`

### The Issue
`np.finfo(np.longdouble).eps` reports `1.084202172485504434e-19` which suggests support for 80-bit extended precision, but `1+np.finfo(np.longdouble).eps == 1` returns `True`.

I was under the impression that nominally one of two things should occur:
a. On systems where `double` and `longdouble` have the same precision, for example Windows with MSVC, both `np.finfo(np.double).eps` and `np.finfo(np.longdouble).eps` should return `2.220446049250313e-16`, or
b. On systems where `double` and `longdouble` do not have the same precision (i.e. if 80-bit FPs are supported), `np.finfo(np.longdouble).eps` should return `1.084202172485504434e-19` but then `1+np.finfo(np.longdouble).eps == 1` should return `False`.

In my case there seem to be mixed messages, so I can't tell whether extended precision is actually supported or not. 

### Reproduce the code example:

```python
import numpy as np
np.finfo(np.longdouble).eps
1 + np.finfo(np.longdouble).eps
1 + np.finfo(np.longdouble).eps == 1
```

### NumPy/Python version information:

1.23.2 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]

### Context for the issue:

I am trying to use [PINT](https://github.com/nanograv/PINT), an astronomy-related repo for modeling pulsar signals, for academic research. This requires precision on the order of nanoseconds across timescales of years, which necessitates extended precision as part of many key functions.

**Comment by matthew-brett** [comment]
Yes, that is odd.  Agreeing, here is what I get on Mac, consistent with 80-bit extended precision for `np.longdouble`:

```ipython
[ins] In [5]: np.finfo(np.longdouble).eps
Out[5]: 1.084202172485504434e-19

[ins] In [6]: np.finfo(np.float64).eps
Out[6]: 2.220446049250313e-16

[ins] In [7]: 1 + np.finfo(np.longdouble).eps
Out[7]: 1.0000000000000000001

[ins] In [8]: 1 + np.finfo(np.longdouble).eps == 1
Out[8]: False
```

**Comment by MatteoRaso** [comment]
Adding to what @matthew-brett wrote, I get the same results as him on Manjaro.

**Comment by seberg** [comment]
IIRC WSL is known to have buggy support for longdouble, so I don't think there is much we can do unless someone wants to figure out a way to force longdouble == double in NumPy (but that requires recompiling the world...)
@Micky774 might have more pointers about the WSL issues.

**Comment by TigerHou2** [comment]
Just found these two issues raised a while back regarding the same problem, so it does seem to be an issue specific to WSL1. Sorry I didn't see these before opening a new issue.
[BUG: float128 loses precision on windows subsystem for linux](https://github.com/numpy/numpy/issues/8726#issue)
[long double floating point calculations give inexact results](https://github.com/microsoft/WSL/issues/830#issue)

**Comment by matthew-brett** [comment]
@TigerHou2 - are you using WSL1 or WSL2?  Comments in https://github.com/microsoft/WSL/issues/830 seem to imply this is fixed in WSL2.

**Comment by TigerHou2** [comment]
> @TigerHou2 - are you using WSL1 or WSL2? Comments in [microsoft/WSL#830](https://github.com/microsoft/WSL/issues/830) seem to imply this is fixed in WSL2.

WSL1. I concur with what you said, just found the same comment chain a few minutes ago:

> Just found these two issues raised a while back regarding the same problem, so it does seem to be an issue specific to WSL1. The problem supposedly does not occur for in WSL2, although I have not tested this. Sorry I didn't see these before opening a new issue. [BUG: float128 loses precision on windows subsystem for linux](https://github.com/numpy/numpy/issues/8726#issue) [long double floating point calculations give inexact results](https://github.com/microsoft/WSL/issues/830#issue)

**Comment by matthew-brett** [comment]
Just to summarize, in case anyone else finds this thread, there is a bug in WSL1 such that calculations for float80 longdouble are performed at float64 precision, due to a difference in the Floating Point Unit control settings between real Linux and WSL1.  See https://github.com/microsoft/WSL/issues/1748#issue-211840028 for more detail.

**Comment by jlearman** [comment]
Is there a workaround to suppress the error message?  I understand results won't be the expected precision, but for my purposes it's working.

**Comment by pierre-eliep-met** [comment]
I have this error message on WSL 2 also

**Comment by epigramx** [comment]
> I have this error message on WSL 2 also

Also even if it worked on WSL2 it's not an ideal solution, because it order to run WSL2 you are forced to run the entire operating system under a hypervisor (I mean windows itself too!) which is inefficient compared to WSL1. 

WSL1 was the more impressive engineering but I guess it was harder work than just slapping another VM in there.
