### ISSUE TITLE
BUG: Segmentation fault when using shared memory buffer

### ISSUE THREAD

**Issue by LaihoE** [numpy/numpy#22190]
### Describe the issue:

Segfaults when assigning an array to the same variable that created a shared memory block. Obviously not the correct way of using it but relatively easy mistake to make.

### Reproduce the code example:

```python
import numpy as np
from multiprocessing import shared_memory


shm = shared_memory.SharedMemory(create=True, size=8)
shm = np.ndarray((1,), dtype=np.int64, buffer=shm.buf)
print(shm)
```

### Error message:

```shell
Segmentation fault (core dumped)
```

### NumPy/Python version information:

1.23.1 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]

**Comment by seberg** [comment]
`np.ndarray` is a very raw function so it was not changed there.  Using `np.frombuffer` (on newer versions, but you have that) will fix the problem.

**Comment by seberg** [comment]
Closing this, there is a newer one at gh-23305, although not sure if we want to follow up on either.
