### ISSUE TITLE
BUG: <Please write a comprehensive title after the 'BUG: ' prefix>

### ISSUE THREAD

**Issue by gsiisg** [numpy/numpy#22192]
### Describe the issue:

- np.minimum is not giving the correct result if the input is float32 and epsilon is very small
- this behavior is observed when using np.clip(input, eps, 1-eps) as well
- this behavior is found when scikit-learn's log_loss was returning:
"RuntimeWarning: divide by zero encountered in log"
When the input have 1.0, the clip in log_loss still returned 1.0 instead of 0.9999999... therefore when taking log(1-p), when p=1.0, it gives nan.

### Reproduce the code example:

```python
import numpy as np

# should print:
# with eps=1e-7 np.float32 array, max is 0.9999999
# with eps=1e-8 np.float32 array, max is 1.0
# with eps=1e-8 np.float64 array, max is 0.99999999

eps=1e-7
result = np.minimum(np.array([1],dtype=np.float32),1-eps)
print('with eps=1e-7 np.float32 array, max is', max(result))
eps=1e-8
result = np.minimum(np.array([1],dtype=np.float32),1-eps)
print('with eps=1e-8 np.float32 array, max is', max(result))
eps=1e-8
result = np.minimum(np.array([1],dtype=np.float64),1-eps)
print('with eps=1e-8 np.float64 array, max is', max(result))
```

### NumPy/Python version information:

1.21.5 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]

### Context for the issue:

trying to debug why I am getting nan in scikit-learn's log_loss function, turns out clipping was returning non-clipped values for 1-eps, getting 1.0 for y_pred.  When taking the log(1-p), where p = 1.0, gives division by zero warning, resulting in nan.

**Comment by seberg** [comment]
This is an artifact of how the type promotion works with scalar values.  If you work float32, you must use `np.finfo(np.float32).eps`.  You are using an incorrect eps value, and because that value is a Python float (or rather scalar currently), NumPy simply converts it to `float32` here.  `float32(1-eps) == 1` however.

There are many issues open about it and NEP 50 tries to address parts of it, although it does **not** try to change the specific behavior you are seeing since `1-eps` is a Python float scalar.

**Comment by gsiisg** [comment]
"You are using an incorrect eps value"
The epsilon is set by default in the log_loss of scikit 
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.log_loss.html
I'm just trying to understand, are you saying the scikit function is using numpy incorrectly and should have set a different epsilon depending on whether the input is np.float32 or not?

**Comment by seberg** [comment]
> scikit[-learn] function is using numpy clip/minimum incorrectly and should have set a different epsilon depending on whether the input is np.float32 or not?

Yes, if sklearn wants to support float32 "properly", they need to adjust the default.  Another version may be to use `np.nextafter(1., 0.)`, but there you also need to create a 1 with the correct dtype.
Can you open an issue there to see if it should be changed?
