### ISSUE TITLE
BUG: <isinstance does not work properly on nested numpy arrays.>

### ISSUE THREAD

**Issue by pokecheater** [numpy/numpy#22207]
### Describe the issue:

Hey Numpy-Team,

just as the description tells you, here is some code to reproduce.

Thanks in advance and for this awesome library <3
Greetz

### Reproduce the code example:

```python
import numpy as np
test = np.float32(1)
print(test.dtype)
print(isinstance(test, np.floating)) # will eval to True

test = np.float32([[1]])
print(test.dtype)
print(isinstance(test, np.floating)) # will eval to False

# but dtype is in both cases float32 so my expectation is that both should eval to True.
```

### NumPy/Python version information:

1.22.4
MacOSX M1
Python 3.8.9

**Comment by eric-wieser** [comment]
The spelling you want is `np.issubdtype(test.dtype, np.floating)`

**Comment by pokecheater** [comment]
thanks for the hint :)
I used  
if "float" in str(predictions.dtype):
as a workaround so far.

**Comment by pokecheater** [comment]
Okay got my mistake here. Creation of a single value vs. an array. Of course the first one will check if the single value is from a given type and the second one will check if the array is an instance of an dtype which fails of course. 
Thanks again.

<img width="267" alt="Bildschirmfoto 2022-09-06 um 09 55 58" src="https://user-images.githubusercontent.com/20928617/188579018-6744c918-4b7a-4cc5-8daf-39df1aec4c68.png">
