### ISSUE TITLE
BUG: Product of eigen values does not equal computed determinant

### ISSUE THREAD

**Issue by Fernal73** [numpy/numpy#22218]
### Describe the issue:

Isn't the product of the eigen values of a square matrix equal to its determinant? How am I not getting that here? Am I missing something? The trace computes to the sum of the eigen values as expected.

### Reproduce the code example:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# eigendecomposition
from numpy import array
from numpy import trace
from numpy import prod
from numpy import sum
from numpy.linalg import eigvals
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values = eigvals(A)
print(values)
print(det(A))
print(prod(values))
print(trace(A))
print(sum(values))
```

### Error message:

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -8.58274334e-16]
-9.51619735392994e-16
1.5448938003065234e-14
15
14.999999999999986

### NumPy/Python version information:

1.22.4,3.10.6 (main, Aug 16 2022, 12:57:47) [GCC 12.1.0]

### Context for the issue:

What's the explanation?

**Comment by rkern** [comment]
Both values are approximately 0 (relative to the original values in `A`), which is expected for a degenerate array like this one. Floating point arithmetic inherently has errors that will accumulate in different ways when you compute something in two different ways, even if they are supposed to compute the same number when done with infinite-precision real numbers.

**Comment by Fernal73** [comment]
Can you provide an example that does not degenerate? Is this documented as part of Numpy documentation? Will the log also be affected similarly?

**Comment by Fernal73** [comment]
You're right. It does work for matrices that are positive definite such as :
( 2 —1 0
—1 2 —1
 0 —1 2)

**Comment by rkern** [comment]
When I say "degenerate" I mean specifically that its rows are not all linearly independent, thus it has a determinant of `0` (ideally). `det(A)` and `prod(values)` are two ways of computing that same determinant using floating point arithmetic. They will, in general, differ from each other, but should each be "close" to the ideal value of `0`. And by close, we mean about `1e-16` times the magnitude of the input numbers (e.g. about `1` to `10`) times maybe the number of elements in the array (roughly, give or take an order of magnitude or two). We see that actual results to give us that. They can *look* pretty different at first glance when you compare them to _each other_ relatively, but when you are around `0.0`, you the magnitude of the inputs is a more important controlling factor.

This is a fundamental feature of floating point arithmetic. It's omnipresent whenever you use it; it's not really specific to numpy or any particular feature of numpy, so I don't know what kind of documentation would have been useful to you. Some docstrings will talk about floating point round-off error if there is something particularly salient about how it interacts with the function (e.g. conditions under which inputs may cause an exception), but docstrings can't really exhaustively list all of the ways in which floating point arithmetic diverges from ideal real arithmetic for all combinations of functions.

That said, we do occasionally get enough bug reports of this form ("these two different calculations should give the same thing, but they don't") that some kind of tutorial-style article that explains a few of these would be a good thing to have for linking to.

**Comment by Fernal73** [comment]
Thank you very much, @rkern , for the explanation.
For completeness, I'll add the following code:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# eigendecomposition
import numpy as np
from numpy import array
from numpy import trace
from numpy import prod
from numpy import sum
from numpy.linalg import eigvals
from numpy.linalg import det
from numpy.linalg import slogdet
from numpy import log

def verify(A):
    print(A)
    # factorize
    values = eigvals(A)
    print(values)
    print(det(A))
    print(prod(values))
    print(slogdet(A))
    print(sum(log(values)))
    print(trace(A))
    print(sum(values))
    print()


# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
verify(A)

A = array([
    [2,-1,0],
    [-1,2,-1],
    [0,-1,2]])
verify(A)
```
