### ISSUE TITLE
ENH: Add a method which returns the shape of (possibly ragged) arrays

### ISSUE THREAD

**Issue by zacps** [numpy/numpy#22219]
### Proposed new feature or change:

When working with high dimensional arrays it is often easy to accidentally create outputs which are ragged (have dimensions of different sizes). For example the following array is ragged:

```py
ragged = [(1,2,3), (1,2,3,4)]
```

Ragged arrays are not supported by numpy and attempting to treat them like regular arrays usually causes errors.

However, it can be hard to figure out where in a high dimension array the problem is, or to figure out how to reshape the data to have consistent dimensions.

To make this easier, I'd like numpy to support a `np.raggedshape` method which is capable of finding the shape of ragged arrays to support debugging problems like this.

For non-ragged arrays `np.raggedshape(arr)`  would always be equal to `np.shape(arr)`. Otherwise, it would behave like the following:

```py
arr = [
    [[1,2], [1,2], [1,2]],
    [[1,2], [1,2], [1,2], [1,2]]
]
np.raggedshape(arr)
>>> (2, ((3, 2), (4, 2)))
```

`raggedshape` returns all consistent dimensions in the same manner as `shape`, but for non-consistent dimensions returns a tuple consisting of the unique shapes of each element.

**Comment by zacps** [comment]
An (inefficient, probably buggy) implementation of this is below:

```py
from collections.abc import Iterable

def raggedshape(array):
    if not any(isinstance(e, Iterable) for e in array):
        return len(array)
    
    try:
        return array.shape
    except AttributeError:
        unique_shapes = []
        all_shapes = []
        for arr in array:
            s = shape(arr)
            all_shapes.append(s)
            if s not in unique_shapes:
                unique_shapes.append(s)
        if len(unique_shapes) == 1:
            return (len(array), *tuple(unique_shapes))
        else:
            return (len(array), tuple(all_shapes))
```

**Comment by mattip** [comment]
I don't think this belongs in NumPy. See #19113 for more discussion of ragged array discovery and recommended best practices in NumPy, and [NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html) which expresses NumPy's desire to not deal at all with ragged arrays. If you often deal with this type of data, perhaps the [awkward array](https://awkward-array.org/quickstart.html) project might have some methods that help in the discovery phase.

**Comment by zacps** [comment]
That's fair enough, the reason I think that it might be useful in numpy s that finding the shape of ragged arrays can be useful if you create them by accident and want to reshape what you have to be non-ragged.

Of course if you were intending to work with ragged arrays you'd need to use another library.

Even then I can see this is kind of 50/50, but I thought I'd make the suggestion.

**Comment by MatteoRaso** [comment]
@zacps if you do try to use your implementation, be warned that it doesn't work with 3D arrays.

**Comment by rossbar** [comment]
Given the above I will close this as I don't think adding functionality to support ragged shapes (even in the context of trying to convert ragged arrays to regular ones) is aligned with the goal of ultimately reducing the ragged-array footprint.

Thanks for the suggestion @zacps . If you feel very strongly about adding the new functionality, consider posting the suggestion to the mailing list.
