### ISSUE TITLE
The np.filled() function give unexpected results after masking of array.

### ISSUE THREAD

**Issue by kernel-loophole** [numpy/numpy#22226]
### Issue with current documentation:

The  np.filled() function give unexpected results after masking of array.
```
x = np.array([1, 2, 3])
x.view(ma.MaskedArray)
x = [0., 1., -9999., 3., 4.]
mx = ma.masked_values (x, -9999.)
output:
[2. 2. 2. 2. 2.]
```
file:///home/hiader/numerical-computing/masking.py

### Idea or request for content:

Filling in the missing data after masking is give unexpected results .

**Comment by bsipocz** [comment]
What is your numpy version, `python -c "import numpy;print(numpy.__version__)"`? 

I cannot reproduce this with the latest release, your example from above produces the expected output for me:

```
masked_array(data=[0.0, 1.0, --, 3.0, 4.0],
             mask=[False, False,  True, False, False],
       fill_value=-9999.0)
```

**Comment by kernel-loophole** [comment]
I am using numpy version` 1.21.5`

**Comment by kernel-loophole** [comment]
It will create the array correctly, but when it fills in the gaps or missing value , the unexpected result will result.

**Comment by mattip** [comment]
Can you redo your example to show the problem?
- the result of line 2 is not preserved
- line 3 changes the values of `x`, making lines 1 and 2 irrelevant
- the output should never be `[2. 2. 2. 2. 2.]`, that is an invalid string

**Comment by kernel-loophole** [comment]
yes sure

**Comment by kernel-loophole** [comment]
here is the code for that `import numpy as np
import numpy.ma as ma
x = np.array([1, 2, 3])
x.view(ma.MaskedArray)
#x = [0., 1., -9999., 3., 4.]
mx = ma.masked_values (x, x.mean())
mx.filled(mx)
print(mx)`

**Comment by kernel-loophole** [comment]
after running this you can verify the output

**Comment by kernel-loophole** [comment]
output of above code
`[1 -- 3]`

**Comment by rkern** [comment]
Instead of `mx.filled(mx)`, did you mean `mx = ma.filled(mx)`?

**Comment by rkern** [comment]
Both versions of `filled()` (method and function) are working as documented. I think this was just typo in the example causing confusion.

I'm going to close since I don't think there is any change that we need to make, but if you have more questions, we can keep discussing here.

**Comment by kernel-loophole** [comment]
thanks for your support
