### ISSUE TITLE
BUG: index overflow when calling numpy.histogram on float16 data with a min-max range greater than or equal to 65504

### ISSUE THREAD

**Issue by Nathravorn** [numpy/numpy#22238]
### Describe the issue:

When passing data in float16 format to the function `numpy.histogram`, in certain cases, an index overflow occurs, which causes an error.

The error takes root on lines 851 and 852 of the file `numpy/lib/histograms.py`. The lines are the following:

```
    851             f_indices = _unsigned_subtract(tmp_a, first_edge) * norm
    852             indices = f_indices.astype(np.intp)
```

It seems that given two numbers or arrays in float16 dtype, if the distance between them is 65504 or more, `_unsigned_subtract` returns `np.inf`, which becomes either `np.nan` or `np.inf` after multiplication with `norm`.

Then, after the conversion to the `np.intp` dtype, this value becomes `-9223372036854775808`, which is the minimum value allowable for this dtype. This then causes the index error shown in the traceback below.

### Reproduce the code example:

```python
import numpy as np
# As far as I've seen, any two numbers with a distance >= 65504 produce the bug.
a = np.array([-30000, 35504]).astype("float16")
np.histogram(a)
```

### Error message:

```shell
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [66], in <cell line: 3>()
      1 import numpy as np
      2 a = np.array([-30000, 35504]).astype("float16")
----> 3 np.histogram(a)

File <__array_function__ internals>:180, in histogram(*args, **kwargs)

File /opt/conda/lib/python3.8/site-packages/numpy/lib/histograms.py:857, in histogram(a, bins, range, normed, weights, density)
    853 indices[indices == n_equal_bins] -= 1
    855 # The index computation is not guaranteed to give exactly
    856 # consistent results within ~1 ULP of the bin edges.
--> 857 decrement = tmp_a < bin_edges[indices]
    858 indices[decrement] -= 1
    859 # The last bin includes the right edge. The other bins do not.

IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 11
```

### NumPy/Python version information:

Numpy: `1.23.2`
Python: `3.8.13`

### Context for the issue:

This issue affects a significant number of use-cases, since presumably many calculations of histograms in the float16 dtype have a range bigger than 65504.

**Comment by Nathravorn** [comment]
While experimenting with this, I also seem to have found another bug in the `_unsigned_subtract` function. See the code below: 

```
from numpy.lib.histograms import _unsigned_subtract
>>> _unsigned_subtract(np.array(30000, dtype="float32"), np.array(-35000, dtype="float32"))
65000
>>> _unsigned_subtract(np.array(30000, dtype="float16"), np.array(-35000, dtype="float16"))
65020
```
I would have expected the same result from both calls, but the second subtraction weirdly differs by 20 from the expected result. Might this behavior be linked to the bug at hand?

**Comment by seberg** [comment]
65500.0 is the largest number that can be represented by `float16`.  The number of digits of float16 is also so small, that your calculation above is simply the expected result.

So I expect that this is simply what you should expect, the only weird thing is that NumPy doesn't just raise an error because "infinity" cannot be converted to an index, because infinities are created on the way if you use float16.

In general, only use float16 if you know its OK, unless typical in your field, I may also suggest the same for float32.

**Comment by Nathravorn** [comment]
> The number of digits of float16 is also so small, that your calculation above is simply the expected result.

Right, sorry, it's obvious in retrospect.

> 65500.0 is the largest number that can be represented by float16.

Okay, thanks, my bad. I thought the _unsigned_subtract function was supposed to convert to unsigned float16 before doing the subtraction, but I realized that there is no such thing as an unsigned float16 dtype.

> the only weird thing is that NumPy doesn't just raise an error because "infinity" cannot be converted to an index

Yes, it is strange that the conversion to intp doesn't raise an error and instead overflows.

Thanks for your help :)

**Comment by seberg** [comment]
OK, going to close this, since an error would be a bigger discussion and we actually do have a warning now.
