### ISSUE TITLE
BUG: CI: `ubuntu-18.04` runner image is deprecated

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [numpy/numpy#22249]
### Describe the issue:

This part of CI appears to rely on the `ubuntu-18.04` image label:
https://github.com/numpy/numpy/blob/71155e9331cd30dbb37732a74fca5f23ab734aa4/.github/workflows/build_test.yml#L78-L81

However, this runner image is deprecated:
[The Ubuntu 18.04 Actions runner image will begin deprecation on 8/8/22 and will be fully unsupported by 4/1/2023](https://github.com/actions/runner-images/issues/6002)

Alternatives:
* `ubuntu-20.04`
* `ubuntu-latest` (currently an alias of `ubuntu-20.04`)

Ubuntu 20.04 ships with [`g++-7`](https://packages.ubuntu.com/search?keywords=g%2B%2B-7) and [`g++-8`](https://packages.ubuntu.com/search?keywords=g%2B%2B-8) only. As far as I can see, [`g++-6`](https://packages.ubuntu.com/search?keywords=g%2B%2B-6) is available on Ubuntu 18.04 but not on Ubuntu 20.04.

### Reproduce the code example:

```python
-
```

### NumPy/Python version information:

-

**Comment by rgommers** [comment]
Thanks @DimitriPapadopoulos. I'd say we can ignore the deprecation for now, and by April 1, 2023 we can drop GCC6.

**Comment by DimitriPapadopoulos** [comment]
Sure, just remember you'll experience planned CI failures from time to time.

**Comment by seberg** [comment]
We are not using this anymore.
