### ISSUE TITLE
BUG: `np.arange()` sometimes includes the maximum value

### ISSUE THREAD

**Issue by zxdawn** [numpy/numpy#22241]
### Describe the issue:

Sometimes the `np.arange()` includes the right value.

### Reproduce the code example:

```python
import numpy as np

print(np.arange(60., 90., 0.04, dtype='float'))
print(np.arange(60., 90.04, 0.04, dtype='float'))
```

### Error message:

```shell
[60., ......, 89.92, 89.96]
[60., ......, 89.92, 89.96, 90.  , 90.04]]
```

### NumPy/Python version information:

1.22.4 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:05:37) [Clang 13.0.1 ]

### Context for the issue:

This will lead to an unexpected array range.

**Comment by MatteoRaso** [comment]
The documentation says that this sometimes happens when the step isn't an integer.

**Comment by zxdawn** [comment]
Aha, so we should use `np.linspace()` when the step isn't an integer?

**Comment by zxdawn** [comment]
See the similar issue here: https://github.com/numpy/numpy/issues/11913.
Is it better to add a warning when the step is float?
