### ISSUE TITLE
Trouble installing numpy with pip on Python 2.7

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [numpy/numpy#22243]
### Describe the issue:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: numpy in /public/home/zhaoli/software/anaconda3/envs/hicploter/lib/python2.7/site-packages (1.10.4)

### Reproduce the code example:

```python
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: numpy in /public/home/zhaoli/software/anaconda3/envs/hicploter/lib/python2.7/site-packages (1.10.4)
```

### Error message:

```shell
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: numpy in /public/home/zhaoli/software/anaconda3/envs/hicploter/lib/python2.7/site-packages (1.10.4)
```

### NumPy/Python version information:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: numpy in /public/home/zhaoli/software/anaconda3/envs/hicploter/lib/python2.7/site-packages (1.10.4)

### Context for the issue:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: numpy in /public/home/zhaoli/software/anaconda3/envs/hicploter/lib/python2.7/site-packages (1.10.4)

**Comment by Jiangjiangzhang6** [comment]
I install the numpy with version of 1.10.4
but its error when run 
and using the commands "pip install numpy" its show the upload error , but \"python -c "import numpy; print numpy.version.version"\"
its show
![image](https://user-images.githubusercontent.com/101324838/189517510-bfee5e7e-bb7a-44d9-b679-310fdc376675.png)
 
how could i deal with bug ,than you

**Comment by rgommers** [comment]
@Jiangjiangzhang6 can you please provide more detail here so we can help you? This is not an actionable report as is.
- How did you install Python 2.7?
- Are you using a virtualenv, conda env, or other such thing?
- And provide the full install log of running `pip install numpy` please

**Comment by Jiangjiangzhang6** [comment]
use the conda install ，thehicplotter need   python2.7，and the numpy need 1.9.2. I had  installed but its error and just import numpy also show error



---- Replied Message ----
| From | Ralf ***@***.***> |
| Date | 09/11/2022 16:08 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [numpy/numpy] Trouble installing numpy with pip on Python 2.7 (Issue #22243) |

@Jiangjiangzhang6 can you please provide more detail here so we can help you? This is not an actionable report as is.

How did you install Python 2.7?
Are you using a virtualenv, conda env, or other such thing?
And provide the full install log of running pip install numpy please

**Comment by Jiangjiangzhang6** [comment]
![image](https://user-images.githubusercontent.com/101324838/189518159-afd43c78-7ce1-467e-930c-058ca4c8cf6b.png)

**Comment by rgommers** [comment]
When you use `conda` you should install `numpy` with conda rather than with `pip`. Doesn't `conda install numpy=1.9.2` work?

That said, `pip` will install `numpy` as well. I don't see anything wrong with the install part of this. If you can't successfully do `import numpy` afterwards, there is likely something wrong with your environment. You can test it with other packages that don't depend on numpy - if those contain compiled code, I suspect they also won't work for you.

**Comment by seberg** [comment]
Are you sure that there are not two python versions installed and the one providing pip, is not the one you are using?  Did you check `python --version` and where Python is installed (`which python` on linux)?

To make sure you are running pip with the correct python version, you should use `python -mpip install numpy`.  However, if that is the problem, you should probably look and make sure you understand your python setup first.  As the warnings say, using Python 2.7 is also very much not recommended anymore and if you do use `conda` you should install NumPy using that.

It may also be that you are simply forgetting to activate the conda environment and that is the reason you are picking up the wrong python version.

**Comment by Jiangjiangzhang6** [comment]
![image](https://user-images.githubusercontent.com/101324838/189519531-67721139-2489-49f4-8a24-bc0100b3ac51.png)


> When you use `conda` you should install `numpy` with conda rather than with `pip`. Doesn't `conda install numpy=1.9.2` work?
> 
> That said, `pip` will install `numpy` as well. I don't see anything wrong with the install part of this. If you can't successfully do `import numpy` afterwards, there is likely something wrong with your environment. You can test it with other packages that don't depend on numpy - if those contain compiled code, I suspect they also won't work for you.



> Are you sure that there are not two python versions installed and the one providing pip, is not the one you are using? Did you check `python --version` and where Python is installed (`which python` on linux)?
> 
> To make sure you are running pip with the correct python version, you should use `python -mpip install numpy`. However, if that is the problem, you should probably look and make sure you understand your python setup first. As the warnings say, using Python 2.7 is also very much not recommended anymore and if you do use `conda` you should install NumPy using that.
> 
> It may also be that you are simply forgetting to activate the conda environment and that is the reason you are picking up the wrong python version.

**Comment by Jiangjiangzhang6** [comment]
now I search the google , its also casued by numpy

**Comment by seberg** [comment]
@Jiangjiangzhang6 this is almost certainly caused by a bad environment, such as two different Pythonversions and a `PYTHONPATH` variable mixing things up badly.  Our help site:
https://numpy.org/devdocs/user/troubleshooting-importerror.html

Tries to list some common issues and point towards help.  But this is not related to NumPy itself and hard to debug online, if you have someone who can help you locally, that may be better.

**Comment by Jiangjiangzhang6** [comment]
> @Jiangjiangzhang6 this is almost certainly caused by a bad environment, such as two different Pythonversions and a `PYTHONPATH` variable mixing things up badly. Our help site: https://numpy.org/devdocs/user/troubleshooting-importerror.html
> 
> Tries to list some common issues and point towards help. But this is not related to NumPy itself and hard to debug online, if you have someone who can help you locally, that may be better.

thank you 
i had done with it ,its not the error of numpy, its the version problem with the  matplotlib-2.2.5
![image](https://user-images.githubusercontent.com/101324838/189529187-c694adea-d7a5-4e48-9db6-77183ca30c4b.png)
