### ISSUE TITLE
BUG: Possible regression in CPU supported features for aarch64

### ISSUE THREAD

**Issue by stumpylog** [numpy/numpy#22257]
### Describe the issue:

While investigating paperless-ngx/paperless-ngx/issues/1364, it was noticed between `numpy==1.22.3` and `numpy==1.23.1`, the supported SIMD extensions reported by `numpy.show_config()` changed, with `1.23.1` not finding the ASIMDFHM feature.

The device is a ROCK64, with a Cortex A53, Armv8, which I believe should have all th features implied by ASIMDFHM (basing on [the list here](https://numpy.org/devdocs/reference/simd/build-options.html#on-armv8-a64)).

I thought #21749 would fix this, but the issue persists with 1.23.2

### Reproduce the code example:

```python
import numpy
numpy.show_config()
```

#### 1.22.3 Config
```
numpy.show_config()
openblas64__info:
libraries = ['openblas64_', 'openblas64_']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
libraries = ['openblas64_', 'openblas64_']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
libraries = ['openblas64_', 'openblas64_']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
libraries = ['openblas64_', 'openblas64_']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
found =
not found = ASIMDHP,ASIMDDP
```
#### 1.23.1 Config
```
numpy.show_config()
openblas64__info:
libraries = ['openblas64_', 'openblas64_']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
libraries = ['openblas64_', 'openblas64_']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
libraries = ['openblas64_', 'openblas64_']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
libraries = ['openblas64_', 'openblas64_']
library_dirs = ['/usr/local/lib']
language = c
define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
found =
not found = ASIMDHP,ASIMDDP,ASIMDFHM
```
### NumPy/Python version information:

numpy==1.23.1 / numpy==1.23.2

### Context for the issue:

The training of some classifiers goes from a few minutes, to never completing.

**Comment by charris** [comment]
@seiko2plus Thoughts?

**Comment by mattip** [comment]
@seiko2plus thoughts?

**Comment by seiko2plus** [comment]
Compile time detection of `ASIMDFHM` was fixed since numpy==1.23.0rc1 via #22257, however we still didn't support it yet within any of the current SIMD kernels, so been detect it or not wouldn't affect on the performance. Could please provide a minified code to reproduce the performance regression so I can invastigate on it?

**Comment by stumpylog** [comment]
The data that's being used is a personal user's documents and their contents, and I don't have access to anything running aarch64 at the moment.  

I'll see what I can wrangle up anyway, but it's probably going to take some time to make a minified code sample using something.

**Comment by seiko2plus** [comment]
I'm not familiar with `paperless-ngx`, would please provide me the steps to reproduce the error on `gnu/linux`.

**Comment by stumpylog** [comment]
My apologies, it has taken me a while to free up my Pi 3 from other things to be able to test this and boil it all down.  At least with the public dataset for multi-label classification I found and a Pi, I haven't been able to reproduce any sort of slowdown.

Either this requires a certain amount of data or data types which I can't easily produce, or it's something specific to the ROCKPI.  Unless @pedrom34 is able to provide more information, this can probably be closed.
