### ISSUE TITLE
DOC: `np.ctypeslib` - list of functions that are missing examples – tracking issue

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy#22268]
Find below the functions from `np.ctypeslib` that are missing examples in the docstrings. If you have a suggestion for an example, please submit a pull request.
To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)

- [x] as_array
- [ ] as_ctypes
- [ ] as_ctypes_type
- [x] load_library

**IMPORTANT:** Don't close this issue or remove the *"sprintable"* label until all the PRs with examples are merged.

**Comment by Drishttii** [comment]
Hi, I'd like to give this a try as part of Grace Hopper Open Source day.

**Comment by ankur0904** [comment]
@InessaPawson Hi I like to work on this issue.
