### ISSUE TITLE
DOC: `np.char` - list of functions that are missing examples – tracking issue

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy#22267]
Find below the functions from `np.char` that are missing examples in the docstrings. If you have a suggestion for an example, please submit a pull request. 
To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)

- [x]  add
- [ ]  array
- [ ]     asarray
- [ ]     center
- [ ]     encode
- [ ]     equal
- [ ]     expandtabs
- [ ]     find
- [x]     greater
- [ ]     greater_equal
- [ ]     index
- [ ]     isalnum
- [ ]     isalpha
- [ ]     isdecimal
- [ ]     isdigit
- [ ]     islower
- [ ]     isnumeric
- [ ]     isspace
- [ ]     istitle
- [x]     isupper
- [ ]     join
- [ ]     less
- [ ]     less_equal
- [ ]     ljust
- [ ]     mod
- [ ]     multiply
- [ ]     not_equal
- [x]     partition
- [ ]     replace
- [ ]     rfind
- [ ]     rindex
- [ ]     rjust
- [x]     rpartition
- [ ]     rsplit
- [ ]     split
- [x]     splitlines
- [ ]     startswith
- [ ]     str_len
- [ ]     translate
- [ ]     zfill

**Comment by samyukthagopalsamy** [comment]
I would like to work on this documentation issue.

**Comment by SarahCoffland** [comment]
I will work on this one as well.

**Comment by tahsinsoha** [comment]
I would like to work on this too!

**Comment by scollins83** [comment]
I'd like to work on this as well, and am familiar with splitlines, so I'll start with that one.

**Comment by scollinstc** [comment]
> I'd like to work on this as well, and am familiar with splitlines, so I'll start with that one. https://github.com/scollins83/numpy.git

Pasted wrong link - that branch is here: https://github.com/scollins83/numpy/tree/documentation---Add-split-lines-example

**Comment by Eric-Shang** [comment]
I'm working on "partition"

**Comment by kkirtivasan** [comment]
I am working on "greater" as part of Grace Hopper OSD NumPy sprint.

**Comment by Digya053** [comment]
I am working on isdigit and str_len as part of Grace Hopper OSD Numpy sprint.

**Comment by Yunika-Bajracharya** [comment]
I'd like to work on join, multiply, center, split, index for GHC OSD.
