### ISSUE TITLE
DOC: `np.ma` - list of functions that are missing examples – tracking issue

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy#22269]
Find below the functions from `np.ma` that are missing examples in the docstrings. If you have a suggestion for an example, please submit a pull request.
To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)

- [x]     compress_cols
- [ ]     compress_nd
- [x]     compress_rows
- [ ]     compressed
- [ ]     convolve
- [ ]     correlate
- [ ]     cov
- [ ]     diag
- [ ]     ediff1d
- [ ]     in1d
- [ ]     isin
- [ ]     left_shift
- [x]     max
- [x]     min
- [x]     power
- [ ]     put
- [ ]     putmask
- [ ]     reshape
- [ ]     right_shift
- [x]     round
- [x]     round_
- [ ]     setxor1d
- [ ]     sort
- [ ]     take
- [x]     union1d
- [x]     unique

**IMPORTANT:** Don't close this issue or remove the *"sprintable"* label until all the PRs with examples are merged.

**Comment by pojaghi** [comment]
Hi, I'd like to give this a try as part of Grace Hopper OSX day.

**Comment by swagatip** [comment]
@pojaghi Looking into this as part of the Grace Hopper OSD NumPy sprint as well. Lets work on it together

**Comment by snigdhas-mishra** [comment]
I will contribute as well. Starting this as a part of GHC OSDay.

**Comment by rossbar** [comment]
@F3eQnxN3RriK IMO it's okay to leave this closed - we don't necessarily want to *encourage* churn on the `ma` package.
