### ISSUE TITLE
DOC: wrong formula in the documentation of numpy.polynomial.chebyshev.chebpts2

### ISSUE THREAD

**Issue by davideproment** [numpy/numpy#22274]
### Issue with current documentation:

The second sentence of the documentation for [numpy.polynomial.chebyshev.chebpts2()](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.chebyshev.chebpts2.html) states that:

> The Chebyshev points of the second kind are the points cos(x), where x = [pi*k/(npts - 1) for k in range(npts)].

I believe that there is a mistake (either in the Documentation or in the formula!), as what the function returns is -cos(x), not cos(x). 

Below you can find a minimal working example
`import numpy as np`
`import numpy.polynomial.chebyshev as cheb`
`print(np.__version__)`
`npts=4`
`print(cheb.chebpts2(npts))`
`print(np.cos([np.pi*k/(npts-1) for k in range(npts)]))`
whose output is (using Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] on darwin)
`1.23.1`
`[-1.  -0.5  0.5  1. ]`
`[ 1.   0.5 -0.5 -1. ]`
showing that the outputs differ by an overall sign.

**Comment by shashank140195** [comment]
Hi, I'd like to give this a try as part of Grace Hopper's OSX day.

**Comment by charris** [comment]
Same points, different order. I prefer the simpler form, but I suppose many might expect the points in ascending order.

**Comment by charris** [comment]
See also https://en.wikipedia.org/wiki/Chebyshev_polynomials#Roots_and_extrema that shows the roots in the current form.

**Comment by Pro-Coder04** [comment]
I am beginner to open source and would like to work on this issue
@davideproment could you assign it to me

**Comment by davideproment** [comment]
@charris: I agree, it is simply a matter of flipping the array and some authors prefer the ascendant order instead. My point is simply that the formula written on the documentation does not represent what the function really computes, hence should be corrected in order for the formula and the doc to be consistent.
@Pro-Coder04 and @shashank140195: I am not a member of NumPY, you should ask @charris to assign this to you!

**Comment by Pro-Coder04** [comment]
@charris could you please assign me to this issue

**Comment by seberg** [comment]
@Pro-Coder04 we don't usually assign issues formally in NumPy.  Commenting here lets others know that (for the time being at least) you are looking into it.  That is sufficient and as soon as you open a PR it will be linked from here.
