### ISSUE TITLE
DOC: `np.random.Generator` - list of functions that are missing examples – tracking issue

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy#22270]
Find below the functions from `np.random.Generator` that are missing examples in the docstrings. If you have a suggestion for an example, please submit a pull request.
To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)
- [x] beta
- [x] exponential

**IMPORTANT:** Don't close this issue or remove the *"sprintable"* label until all the PRs with examples are merged.

**Comment by lzha97** [comment]
Hi, I'd like to give this a try as part of Grace Hopper OSX day.

**Comment by psankar1016** [comment]
I'd like to give this try as well as part of Grace Hopper OSX day

**Comment by InessaPawson** [comment]
@rkern Do ` beta` or `exponential` need examples in the docstrings?

**Comment by seohyeon-lee-2025** [comment]
Hi, I would like to give this a try as part of GHC Open Source '23.

**Comment by luxedo** [comment]
Examples for `beta` is already present in devdocs.

https://numpy.org/devdocs/reference/random/generated/numpy.random.Generator.beta.html

I believe this issue can be closed
