### ISSUE TITLE
Is there any way of enabling complex256 on arm Macs?

### ISSUE THREAD

**Issue by ziofil** [numpy/numpy#22290]
### Steps to reproduce:

I have an M1 Mac and I know that by default `complex256` isn't available on this platform.
Are there any steps I can take to make it available?

### Error message:

```shell
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [64], in <cell line: 1>()
----> 1 from numpy import complex256

ImportError: cannot import name 'complex256' from 'numpy' (/opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.9/site-packages/numpy/__init__.py)
```

**Comment by charris** [comment]
Not easily, Apple modified the spec, there is no hardware quad precision support. Complex double is the best you can do with the hardware and compiler.
