### ISSUE TITLE
Somthing off with np.square(x) method

### ISSUE THREAD

**Issue by sidn77** [numpy/numpy#22305]
Hello everyone, i just noticed something off with np.square(x) function. 
Below screenshot shows the input and output of the function
![image](https://user-images.githubusercontent.com/16509537/190857463-e86751ff-092e-4daa-a7db-498bf6a21b54.png)

Could someone help debug why is it computing the square of 255 as 1 ?

**Comment by stefanv** [comment]
My guess is that your array has dtype `uint8`, so that what you are seeing is:

```
(255 * 255) % 256 == 1
(51 * 51) % 256 == 41
```

You can get the result you want by casting to a larger integer dtype, or by using the `dtype` argument of `np.square`.
