### ISSUE TITLE
BUG: warning: "cannot convert argument 1 from 'PyObject *' to 'PyArrayObject *'" after disbling deprecated NumPy API warning

### ISSUE THREAD

**Issue by maddukurisrinivasarao** [numpy/numpy#22310]
### Describe the issue:

Sample Code:
PyArray_DATA(PyArray_ZEROS(nd, dims, NPY_COMPLEX128, 1));

Following warning message, while compiling:
warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
Action:
Added the following to disable the warning
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
Results:
cannot convert argument 1 from 'PyObject *' to 'PyArrayObject *
Question:
The following casting worked, but is there any alternate?

  PyArray_DATA((PyArrayObject *)PyArray_ZEROS(nd, dims, NPY_COMPLEX128, 1));

### Reproduce the code example:

```python
PyArray_DATA(PyArray_ZEROS(nd, dims, NPY_COMPLEX128, 1));
```

### Error message:

```shell
cannot convert argument 1 from 'PyObject *' to 'PyArrayObject *'
```

### NumPy/Python version information:

1.22.1

### Context for the issue:

using c-api, to remove deprecated warning message.

**Comment by seberg** [comment]
Hmmm, I am not sure there is a good way to improve this.  The creation function could return an array, but then you will also get a lot of warnings about it not being a `PyObject *` probably.
OTOH, adding the cast to `PyArray_DATA` itself removes the type safety (does not reject arbitrary Python objects anymore).

**Comment by seberg** [comment]
Going to close this, it seems OK to ask you to include the explicit cast for `PyArray_DATA` style macros/functions, even if it means you have to do it also for newly created arrays.  So I can't really think of anything to be done about it.
