### ISSUE TITLE
seems that from 1.23 the 'delimiter' option of loadtxt require single unicode character

### ISSUE THREAD

**Issue by dlanguig3** [numpy/numpy#22311]
### Describe the issue:

It seems that starting from 1.23 the 'delimiter' option of loadtxt requires a single unicode character where a random string was allowed before (and the doc of 1.23 doesn't tell about this new behavior)

So, when running code that worked fine up before 1.23, we get the  error whose stack trace is below.

### Reproduce the code example:

```python
import numpy as np

np.loadtxt(pos_file,comments="@",delimiter="val=",usecols=(0,))

where the text file is something like:
------
field1val=12val=13val=14
field2val=22val=23val=24
------
```

### Error message:

```shell
Traceback (most recent call last):
 File "", line 114, in <module>
   pos_data = np.loadtxt(pos_file,comments="@",delimiter="val=",usecols=(0,))
 File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1313, in loadtxt
   arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
 File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/lib/npyio.py", line 979, in _read
   arr = _load_from_filelike(
TypeError: Text reading control character must be a single unicode character or None; but got: 'val='
```

### NumPy/Python version information:

1.23.0

### Context for the issue:

j

**Comment by rossbar** [comment]
Thanks for reporting. `loadtxt` was re-written in C for 1.23 which resulted in a few breaks with the previous behavior.

While the multi-char delimiter is not possible in 1.23, you may be able to work around this using converters, for example:

```python
>>> txt = io.StringIO("field1val=12val=13val=14\nfield2val=22val=23val=24") # example from OP
>>> conv = lambda s: s.removesuffix("val").removeprefix("field")
>>> np.loadtxt(txt, delimiter="=", converters=conv, encoding=None)
array([[ 1., 12., 13., 14.],
       [ 2., 22., 23., 24.]])
```

**Comment by dlanguig3** [comment]
Hi Ross

thank you for your reply.

I thought this was a bug because the documentation for 1.23 doesn't talk about the new single char restriction. It still tells "str"

regards

david
