### ISSUE TITLE
DOC: Document `finfo()` result holds  a `dtype` attribute

### ISSUE THREAD

**Issue by honno** [numpy/numpy#22330]
Currently `np.finfo()` returns an info object with a `dtype` attribute.

```python
>>> np.finfo(np.float32).dtype
dtype('float32')
```

The main benefit here looks to be finding the component dtype of complex dtypes.

```python
>>> np.finfo(np.complex64).dtype
dtype('float32')
```

This however isn't actually documented behaviour (see [the `numpy.finfo` docs](https://numpy.org/doc/stable/reference/generated/numpy.finfo.html)), although like complex support in `finfo()` recently (see https://github.com/numpy/numpy/issues/22260) this might not be controversial to document in NumPy? I wasn't sure, hence an issue and not a PR.

**Comment by MatteoRaso** [comment]
Yeah, all the attributes should be documented. I noticed that iinfo() also had the same problem, so I added documentation for that one as well in the commit.

**Comment by rgommers** [comment]
Thanks @honno. I don't think it's controversial. It was just missing from the docs.
