### ISSUE TITLE
ENH: Except BaseException in numpy.lookfor again

### ISSUE THREAD

**Issue by lagru** [numpy/numpy#22345]
### Proposed new feature or change:

I apologize if this is not the correct channel to inquire. However, over at scikit-image we've encountered a problem using `numpy.lookfor` on our own library, see https://github.com/scikit-image/scikit-image/issues/6548.

The problem seems to be stemming from a narrower Exception handling introduced by #19393. In our test modules, which `lookfor` tries to import, we use pytest's `importorskip` which raises `Skipped`. Unfortunately `Skippd` does only inherit from `BaseException` and is therefore not handled gracefully by https://github.com/numpy/numpy/blob/3b8dca3d0588048c425488a5e39ceddf815d9138/numpy/lib/utils.py#L976

As I see no other cause in #19393 than fixing a LGTM alert as the reason for this change, I'd like to inquire if we can revert that change. That's likely an easier fix than what we can do on scikit-image's site. Looking at the [exception hierarchy](https://docs.python.org/3/library/exceptions.html#exception-hierarchy) I'm curious if there is a reason why `GeneratorExit` and other classes only deriving from `BaseException` should not be caught while everything else is fine. I get `KeyboardInterrupt`, which enables the user to interrupt this function. But then again why is `SystemExit` caught? In any case the current behavior could be preserved with something like

```python
    ...
except KeyBoardInterrupt:
    raise
except BaseException:
    continue
```
or some version thereof.

Whether this a bug on NumPy's side might depend on if the `module` parameter implies that other modules outside NumPy should be supported. Thanks in advance for the feedback.

**Comment by seberg** [comment]
Considering that I would be tempted to deprecate the whole functionality... :+1: for a simple revert (maybe with a comment, or if anyone wants to be nifty not catching some critical errors like `KeyboardInterrupt`, `MemoryError`, and `RecursionError`).

It doesn't seem worthwhile to spend a lot of cycles on making that code particularly clean.

**Comment by lagru** [comment]
Thanks for the fast fix! Can confirm that this fixes https://github.com/scikit-image/scikit-image/issues/6548.
