### ISSUE TITLE
DOC: Examples contradict numpy.pad pad_width argument API specification.

### ISSUE THREAD

**Issue by fischbacher** [numpy/numpy#22340]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/generated/numpy.pad.html#numpy.pad

Documentation says:

pad_width{sequence, array_like, int}
Number of values padded to the edges of each axis. ((before_1, after_1), … (before_N, after_N)) unique pad widths for each axis. ((before, after),) yields same before and after pad for each axis. (pad,) or int is a shortcut for before = after = pad width for all axes.

So, valid arguments are:
  - Sequences of pairs of integers.
  - A length-1 sequence of an integer - (pad,)
  - An integer.

The examples have:

a = [1, 2, 3, 4, 5]
np.pad(a, (2, 3), 'constant', constant_values=(4, 6))
array([4, 4, 1, ..., 6, 6, 6])

Here, pad_width is a tuple of two integers. This is not valid according to the documented API.

**Comment by rossbar** [comment]
I agree that the wording in the parameter description is imprecise and the case of a single length-2 sequence (which applies the pad to all axes) is not covered. Updated wording suggestions welcome!

**Comment by fischbacher** [comment]
The obvious solution would be to change the examples to stick to the documented API (rather than changing the documented API).

**Comment by InessaPawson** [comment]
@fischbacher Feel free to submit a pull request with better examples.

**Comment by MikiPWata** [comment]
I can work on this if you all don't mind.

**Comment by InessaPawson** [comment]
@MikiPWata, that would be great! 
To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)

**Comment by MikiPWata** [comment]
Thank you!
Yes I will in a moment!

**Comment by MikiPWata** [comment]
@InessaPawson 
Hi! I'm done modifying the examples. Would love to get a review!

**Comment by seberg** [comment]
I do not follow why the idea to change the examples came up.  Adjusting them might make sense, but they are by definition *correct* (they are examples).

So if they contradict the parameter description, then the parameter description is wrong and not the example.

**Comment by MikiPWata** [comment]
Thank you and good point. I will adjust both parameter description and examples.

**Comment by MikiPWata** [comment]
@seberg 
added param description for the single length-2 sequence
improved the examples to have various pad widths

**Comment by MikiPWata** [comment]
@rossbar @InessaPawson 
Sorry to bother, but would love to get a code review. Thank you!

**Comment by InessaPawson** [comment]
@MikiPWata, my apologies for the delay in review. I'm currently traveling. I'll review your PRs on Nov 14th when I'm back to my desk.

**Comment by MikiPWata** [comment]
no worries! thank you so much!
