### ISSUE TITLE
DOC: np.nan() return type bool vs. np.bool_

### ISSUE THREAD

**Issue by timhoffm** [numpy/numpy#22349]
### Issue with current documentation:

`np.isnan()` is documented to return `bool` for scalars (https://numpy.org/doc/stable/reference/generated/numpy.isnan.html).

But it actually returns `np.bool_`. Technically, there are differences, e.g. for the `~` operator.

What is the general policy on this? Is the imprecision/simplification to state `bool` intentional or should it be changed to `np.bool_`?

**Comment by seberg** [comment]
Hmmm, I don't think we have a clear policy.  `np.any`, etc. also are documented this way and do not normally return a Python bool (in rare cases, they could return something different for object array inputs).

My current feeling is that it is OK and practical to just be imprecise, but I am also OK to change it `NumPy bool`.

**Comment by Pro-Coder04** [comment]
Hello I'm interested to solve this issue if it still exists
Could someone assign it to me

**Comment by timhoffm** [comment]
@Pro-Coder04 I think the project has not yet decided whether there is something to do here.

@seberg or other project members: Feel free to close if you want to keep the current state.

**Comment by seberg** [comment]
I am going to close the issue, but if anyone wishes to propose a cleanup, I won't complain :).
