### ISSUE TITLE
BUG: Manipulating mask works for slices but not for integer arrays

### ISSUE THREAD

**Issue by strocode** [numpy/numpy#22348]
### Describe the issue:

Trying to manipulate the mask of a masked array doesn't work if using an index array to slice the array before assigning the mask value. It does work if using a slice, and if slicing or indexing the mask.

It's a bit counterintuitive.

### Reproduce the code example:

```python
import numpy as np
data = np.ma.masked_array(np.arange(10), mask=np.zeros(10))
print(data) # nothing is masked

# using data.mask[indexarray] works
data = np.ma.masked_array(np.arange(10), mask=np.zeros(10))
data.mask[[1,2,3]] = True
print(data) # masked values 1,2,3 - OK

# using data.mask[slice] works
data = np.ma.masked_array(np.arange(10), mask=np.zeros(10))
data.mask[1:4] = True
print(data) # masked values 1,2,3 - OK

# using data[slice].mask works
data = np.ma.masked_array(np.arange(10), mask=np.zeros(10))
data[1:4].mask = True
print(data) # masked values 1,2,3 - OK

# using data[indexarray].mask doesn't change mask!
data = np.ma.masked_array(np.arange(10), mask=np.zeros(10))
data[[1,2,3]].mask = True
print(data) # NOTHING MASKED! - This is unexpected!
```

### NumPy/Python version information:

1.19.5 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0]

**Comment by seberg** [comment]
This is expected, since slices return views, while advanced indexing (indexing with arrays) returns copies.  In that case, you only edit the copy of the mask.

Something like:
```
data[[1, 2, 3]] = np.ma.masked
```
probably works for example (direct assignment).
