### ISSUE TITLE
Nightly travis wheel builds for aarch64 failed testing (segfault).

### ISSUE THREAD

**Issue by charris** [numpy/numpy#22353]
See https://app.travis-ci.com/github/numpy/numpy/builds/256121241.  Note that I reran the build to see if it was something temporary on the travis end.  It is not clear what the problem is, the failures didn't start when the head of the main branch was last updated.

**Comment by mattip** [comment]
It is flaky. The [last few days](https://app.travis-ci.com/github/numpy/numpy/builds) have been OK, but I did need to restart one build on a PR. There was a proposal to explore another CI host somewhere that has aarch64 machines ...

**Comment by andyfaff** [comment]
Cirrus-ci works pretty well for native manylinux_aarch64 and macosx_arm64

**Comment by mattip** [comment]
It seems they have graviton2 AWS machines for aarch64 https://cirrus-ci.org/guide/linux/#__tabbed_1_2

**Comment by andyfaff** [comment]
@charris @mattip `linux_aarch64` is now being tested using the cirrusci cibuildwheel entry. There doesn't seem to be a `linux_aarch64` run on Travis any longer. I think this issue can be closed.

**Comment by charris** [comment]
@andyfaff Thanks for the heads up.
