### ISSUE TITLE
BUG: np.linalg.svd returns non-unitary matrix with full_matrices=False

### ISSUE THREAD

**Issue by alexeyrodriguez** [numpy/numpy#22350]
### Describe the issue:

The svd decomposition returns two unitary matrices and a vector of singular values. While the matrices are unitary for the default parameters that is not the case when setting `full_matrices=False`. See code excerpt

### Reproduce the code example:

```python
import numpy as np

svd_res = np.linalg.svd(np.random.rand(4, 2), full_matrices=False)

# svd_res[0].T @ svd_res[0] is the identity matrix, but
# svd_res[0] @ svd_res[0].T is NOT the (4x4) identity matrix (I expect the product to also be the identity)
```

### NumPy/Python version information:

1.21.6 3.7.14 (default, Sep  8 2022, 00:06:44) 
[GCC 7.5.0]

**Comment by alexeyrodriguez** [comment]
It's possible that this is not a bug and is the expected behavior, but I cannot find this behavior documented.

**Comment by charris** [comment]
It is expected and documented, and I actually think it should be the default as it is in scipy :) You can think of the returned matrices as a subset of the columns of the full matrices, i,e., the columns are mutually orthogonal but not the incomplete rows. This is useful in the common case  where the number of rows in the input matrix is much greater than the number of columns, say a shape like (10**6, 3). In that case the full matrices would have shape (10**6, 10**6), which will cause problems for most people. The full matrices are seldom needed, although there are exceptions. I'm going to close this, but if you can think of a way of improving the documentation, feel free to make a PR.
