### ISSUE TITLE
ENH: Should `np.typing` always (lazy) imported

### ISSUE THREAD

**Issue by leycec** [numpy/numpy#22351]
### Describe the issue:

Curiously, the `numpy.typing` subpackage is advertised as missing when accessed from the standard `import numpy as np` idiom: e.g.,

```python
$ python3.10
>>> import numpy as np
>>> np.typing
Traceback (most recent call last):
  Input In [2] in <cell line: 1>
    np.typing
  File /usr/lib/python3.10/site-packages/numpy/__init__.py:315 in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typing'
>>> np.__version__
'1.22.4'
```

Even worse, this behaviour is **non-deterministic.** Depending on importation order, the same `np.typing` statement raising the above exception suddenly succeeds "mysteriously":

```python
$ python3.10
>>> import numpy as np
>>> import numpy.typing
>>> np.typing
<module 'numpy.typing' from '/usr/lib/python3.10/site-packages/numpy/typing/__init__.py'>
```

**The plot thickens.**

Thanks so much for all the tremendous volunteerism, breathtaking NumPy devs! You make the burgeoning Big Data world go round.

### Reproduce the code example:

```python
import numpy as np
np.typing
```

### Error message:

```shell
Traceback (most recent call last):
  Input In [2] in <cell line: 1>
    np.typing
  File /usr/lib/python3.10/site-packages/numpy/__init__.py:315 in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typing'
```

### NumPy/Python version information:

1.22.4 3.10.6 (main, Sep  6 2022, 17:16:18) [GCC 11.3.0]

### Context for the issue:

`numpy.typing` should be deterministically importable. I mean, ideally, *everything* should be deterministically importable... Lamentably, here we are. `</sigh>`

**Comment by mattip** [comment]
There are many things in python that have side effects. Importing is one of them. We intentionally do not import typing for all users, only for those that want it since it slows down import time. The side-effect of registering the module in the base namespace is unfortunate but cannot be avoided.

I don't think there is anything we can do about it.

**Comment by leycec** [comment]
That's fair enough, I suppose – but there certainly *is* something you can do about it. This is Python.

We have dark and fearsome magic at our disposal here. By the power of inscrutable dunder methods standardized by little-known and poorly documented PEPs, we can materialize almost anything we can envision. That's why we're all here, right? The core of NumPy is all just magic, too.

In this case, [PEP 562](https://peps.python.org/pep-0562) (supported by all actively maintained CPython implementations, which is all anything anyone should care about, because everything else is a security risk) standardized the idea of a module-scoped `__getattr__()` function. By implementing that function in `numpy.__init__`, it's actually trivial for NumPy to satisfy the competing constraints of **(A)** negligible startup time and **(B)** deterministic package imports: e.g.,

```python
# In "numpy.__init__":
def __getattr__(attr_name: str) -> object:
    if attr_name == 'typing':
        from numpy import typing
        return typing

    raise AttributeError(f'"numpy.{attr_name}" not found.')
```

**That's it.** [@beartype itself widely leverages this design pattern throughout its public API, including in `beartype.__init__`](https://github.com/beartype/beartype/blob/7c208ef070b38d80bb1345b336ce110ad1daef9a/beartype/__init__.py#L124). I guarantee worky. Worky is, after all, @beartype's middle name.

**Comment by rossbar** [comment]
IMO proposing to lazily load the typing subpackage is a bit of scope-expansion. That's certainly possible, but should probably be raised on the mailing list for some discussion on whether/how to adopt lazy loading in NumPy.

FWIW there is a general discussion on the topic of lazy loading for ecosystem projects [elsewhere](https://scientific-python.org/specs/spec-0001/)

**Comment by leycec** [comment]
Five additional lines of code to resolve non-determinism in NumPy doesn't *exactly* strike me as egregious. But I also don't maintain NumPy. It's easy for me to armchair this from a cabin in the Canadian wilderness, which is exactly what I'm doing. :sweat: 

Really, *anything* that resolves this issue should be on the table and up for discussion. Non-determinism in software is cancerous to usability, reproducibility, and quality assurance. That's bad. That said, no one seems to be particularly interested in resolving this and [my open-source commitments lie elsewhere](https://github.com/beartype/beartype). I'll sign off for now and let the domain experts in the room run wild with ideas.

Thanks yet again for all the data science, everyone! NumPy is at the centre of everything we do.

**Comment by seberg** [comment]
Lazy imports are becoming a thing and we could do that.  It is indeed a small PR that anyone interested in the feature could open (of course some dev has to merge).

What would help is a brief note that this inconveniences users or is common practice in the typing world.  Right now the argument was that something – that should not be surprising – is surprising.
NumPy has very few other submodules that need explicit importing, so `typing` might be special enough to not extend the argument to all of them.

**Comment by seberg** [comment]
NumPy is doing lazy imports now.

**Comment by CodingCanuck** [comment]
@seberg which release was this fixed in?

I'm still seeing this behavior in numpy 1.26.4, where accessing `np.typing` using the common `np` import alias may or may not raise an error like "module 'numpy' has no attribute 'typing'" depending on the order of imports before that access).

I couldn't find anything in any numpy 2.x release notes that sounded related to this issue.

Thanks!

**Comment by seberg** [comment]
Yes, 2.0.
