### ISSUE TITLE
incorrect binning results with np.arrange

### ISSUE THREAD

**Issue by MengqiYao** [numpy/numpy#22361]
### Describe the issue:

when I use the np.digitize, if the input bin is generated using np.arrange, the binning results are wrong even I set right =True. 

### Reproduce the code example:

```python
number = np.arange(-10,10.2,0.2)
number
a = [0.2,0.4,1.0]
bin_index = np.digitize(a, number,right=True)
number[bin_index]
```

### Error message:

```shell
The results should be [0.2, 0.4, 1.0] it turns out to be array([0.4, 0.6, 1.2])
```

### NumPy/Python version information:

1.21.5 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) 
[Clang 13.0.1 ]

**Comment by rossbar** [comment]
`arange` should not be used with a floating point step, especially when precision is critical. There [are many warnings in the `arange` docstring](https://numpy.org/devdocs/reference/generated/numpy.arange.html) about cases like this. It is recommended to use `linspace` instead; e.g. `number = np.linspace(-10, 10, 101)` for your specific case.

I will close this as duplicate - see e.g. #11913 for one instance of a more detailed discussion of `np.arange` with a floating-point step.

**Comment by InessaPawson** [comment]
@MengqiYao I'll close this issue as per @rossbar's [comment](https://github.com/numpy/numpy/issues/22361#issuecomment-1264049793) above.
