### ISSUE TITLE
DOC: double colon in the absolute basics page

### ISSUE THREAD

**Issue by amagicmuffin** [numpy/numpy#22369]
### Issue with current documentation:

https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-save-and-load-numpy-objects

> If you want to check your array, you can run::

Should probably not have two colons.

### Idea or request for content:

Idea or request for content: have one colon.

**Comment by mattip** [comment]
Thanks. Would you like to submit a PR to fix that? The source lives at [/numpy/numpy//doc/source/user/absolute_beginners.rst](https://github.com/numpy/numpy/blob/main/doc/source/user/absolute_beginners.rst?plain=1#L1507), and there are indeed one two many colons there. There are 3, there should be 2. [Here](https://numpy.org/doc/stable/dev/development_workflow.html) is a guide to the development process.

**Comment by amagicmuffin** [comment]
Thanks so much, just submitted a PR! I think I followed all the instructions right, but I'm newer to git so feel free to let me know if anything went wrong.
