### ISSUE TITLE
BUG: Non-iterability of 0-d array despite being instance of Iterable

### ISSUE THREAD

**Issue by jpauwels** [numpy/numpy#22364]
### Describe the issue:

A 0-d array cannot be iterated over, despite `isinstance(np.array(1), Iterable)` returning `True`.

### Reproduce the code example:

```python
import numpy as np
from typing import Iterable

a = np.array(1)
print(isinstance(a, Iterable))
tuple(a)
```

### Error message:

```shell
Traceback (most recent call last)
Cell In [1], line 6
      4 a = np.array(1)
      5 print(isinstance(a, Iterable))
----> 6 tuple(a)

TypeError: iteration over a 0-d array
```

### NumPy/Python version information:

1.23.3 3.10.6 (main, Sep  7 2022, 17:44:45) [Clang 13.1.6 (clang-1316.0.21.2.5)]

### Context for the issue:

Affecting some of my generic code that should be able to handle, 0-d & 1-d np.arrays and other iterables. I'd settle for having `isinstance(np.array(1), Iterable)` return `False`, but ideally `tuple(np.array(1))` would just return `(1,)`. Same problem exists with `list(np.array(1))`.

**Comment by seberg** [comment]
There are probably issues about this elsewhere, but the simple thing is that this cannot be fixed. All arrays are iterable, including 0-D arrays.  Changing that would require going as far as subclassing `ndarray`.

**Comment by jpauwels** [comment]
To anyone running into the same problem as me, it seems the official workaround is to use [`np.iterable(a)`](https://numpy.org/doc/stable/reference/generated/numpy.iterable.html) instead of `isinstance(a, Iterable)`. The case of a 0-dimensional array is even explicitly mentioned in the docs.
