### ISSUE TITLE
BUG: Array elements with image transformations are all 255 or 0

### ISSUE THREAD

**Issue by jaycola99** [numpy/numpy#22366]
### Describe the issue:

I am using the following code to convert images with only two shades of gray, 0 and 255, to 0 and 1 for a binary classification problem. But when I read the image using PIL's Image and then use the np.array() method to convert the image into an array and output it. My intention was to use `img[img == 255] = 1` to change the grayscale from 255 to 1, but when I finished executing this code the output images were all black images.
The interesting thing is that when I use `print((np.array(img) ! = 255).sum())`, the output may be correct. I don't know the correct answer to this output, but I can tell that the output of this code is correct based on some specific cases.
What is more interesting is that when I use the code to read another image with a gray scale other than 0 and 255 and in RGB format, the output numpy has all elements of 0.

### Reproduce the code example:

```python
import numpy as np
img = Image.open('H0002.bmp').convert('L')
img = img.resize((1444, 1444))
img = np.array(img)
print(img)
img[img == 255] = 1
img = Image.fromarray(img)
img.save('1.bmp')
```

### NumPy/Python version information:

1.23.2 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]

**Comment by jaycola99** [comment]
sorry. I forgot to mention the output in the first paragraph is all 255.

**Comment by mattip** [comment]
I don't think BMP has a binary image format, and in any case you would need to communicate that you desire a binary (0,1) image and not a `uint8` image with all the pixel values equal to 0 or 1. You might be able to change the dtype to `bool`, but I am not sure how well it is supported. There are many ways to convert a `uint8` array to `bool`, depending on if you want to copy the data or not.

In any case this is not a bug in NumPy, please use other students or a site like stackoverflow for such questions.
