### ISSUE TITLE
BUG: should ufunc .types attr contain ISA specific loop variants?

### ISSUE THREAD

**Issue by stuartarchibald** [numpy/numpy#22376]
### Describe the issue:

xref: https://github.com/numba/numba/issues/8478

For a long time, the `.types` attribute on ufuncs has contained char typecode descriptions of the implemented loops. For example:
```pycon
In [1]: import numpy as np

In [2]: np.sin.types
Out[2]: 
['e->e',
 'f->f',
 'd->d',
 'f->f',
 'd->d',
 'g->g',
 'F->F',
 'D->D',
 'G->G',
 'O->O']
```
Since (I think) NumPy 1.23, ISA specific dispatch loops have been added to some ufuncs, these also appear in `.types` as additional registrations ahead of the "original" registered loops. Example:
```pycon
In [3]: np.fmax.types
Out[3]: 
['ff->f',
 'dd->d',
 'gg->g',
 '??->?',
 'bb->b',
 'BB->B',
 'hh->h',
 'HH->H',
 'ii->i',
 'II->I',
 'll->l',
 'LL->L',
 'qq->q',
 'QQ->Q',
 'ee->e',
 'ff->f',
 'dd->d',
 'gg->g',
 'FF->F',
 'DD->D',
 'GG->G',
 'mm->m',
 'MM->M',
 'OO->O']
```
Note how the `ff->f`, `dd->d` and `gg->g` types occur a) first and are b) replicated later on.

I'm not sure that this is actually an issue that would matter in practice except that...

1. In Numba, the `.types` is used as part of the matching logic for type specific code generation, this is now broken by the above due to the following. In NumPy 1.23 a call in Numba to `np.fmax(int64, int64)` resolves via `ff->f` as it is the first "match" (can cast to the type), whereas prior to this it would first match on `ll->l` (as none of the types prior to this would be a safe cast).
2. The `.types` description/char codes are not capturing that some of the loops registered are ISA specific, it looks like a potential mistake/bug in the output.

Essentially this ticket is to seek clarification over the intent so that I can patch Numba against it!

Many thanks in advance for your help.

### Reproduce the code example:

```python
import numpy as np
print(np.fmax.types)
```

### Error message:

```shell
N/A
```

### NumPy/Python version information:

NumPy version 1.23.1

### Context for the issue:

Impacts Numba. xref: https://github.com/numba/numba/issues/8478

**Comment by seberg** [comment]
There are two issues here:
1. Yes, we should just fix it, this is a problem with gh-20131.  Unless I am very confused, duplicating is simply unnecessary (and not used for `minimum/maximum` there).  The reason may be that `fmin` could (but does not) dispatch for integers maybe.  Maybe @Developer-Ecosystem-Engineering can have a quick look, but in general this seems like a small fixup in either case.
   (To be clear, NumPy does *not* really use the loop order here.  Changing it is to not break numba's expectations.)
2. Using the first matching loop is not generally correct.  We need to create new API to allow  you to get it right.  Or we will just pile up more trouble over time...
   Do you prefer Python or C-API to do that?

**Comment by stuartarchibald** [comment]
@seberg Many thanks for your input at today's public Numba meeting. Capturing some notes/discussion in relation to the above.

From the Numba meeting:
* What API would help Numba?

   It was agreed that something like this would be useful:
   ```python
   np.ufunc.resolve_dtypes(dtypes)
   ```
   this would return the `dtypes` used by the inner loop. It would mean that Numba can remove code that is effectively replicating the logic present in NumPy and replace it with a direct query to obtain the result that NumPy would give.
* Does Numba have a need for `np.ufunc.get_loop()` (to get the inner loop)?

   This would be useful to Numba in the case of complicated inner loops such that it doesn't have to replicate the logic with its own version and can just elect to call the NumPy implementation through a function pointer.

* Is there a preference for C-API or Python-API for the above?

   Both are useful, but it was decided that giving priority to the Python API gives the most immediate use.

Other notes on lower priority items:

There was also some discussion about the promotion step within the function resolution being able to insert a new, more specific, inner loop. This lead to wondering about the possibility of exposing a place to replace existing inner loops such that e.g. a JIT compiler could replace an existing loop with a machine specific version.

Thanks again for your help with this  @seberg!

**Comment by Developer-Ecosystem-Engineering** [comment]
> 1. Yes, we should just fix it, this is a problem with [BUG: min/max is slow, re-implement using NEON (#17989) #20131](https://github.com/numpy/numpy/pull/20131).  Unless I am very confused, duplicating is simply unnecessary (and not used for `minimum/maximum` there).  The reason may be that `fmin` could (but does not) dispatch for integers maybe.  Maybe @Developer-Ecosystem-Engineering can have a quick look, but in general this seems like a small fixup in either case.

We will take a look!

**Comment by seberg** [comment]
Sorry, it seems I forgot to fix this for `np.sin` as well, and cupy now noticed that arctan2 (and `cos`) is also affected.  Arctan2 actually leads to incorrect promotion for float16 inputs.
