### ISSUE TITLE
BUG: result of np.exp not compatible between 1.23.X and 1.22.X

### ISSUE THREAD

**Issue by cosama** [numpy/numpy#22386]
### Describe the issue:

After changing to version 1.23.0 (it seem only to affect Ubuntu 20.04) there seem to be a change in how `np.exp` performs it's calculations. The function returns a result now that is not compatible with older version, furthermore it also not compatible anymore with `np.expm1`. It doesn't apply for all number, seems to just be a few edge cases. Here is one:

`numpy==1.23.0`:
```
python3 -c 'import numpy as np; a=6.336541010705443e-14; print((np.exp(-a)).tobytes(), (np.expm1(-a) + 1.0).tobytes())'
b'\xc6\xfd\xff\xff\xff\xff\xef?' b'\xc5\xfd\xff\xff\xff\xff\xef?'
```
which is not the same.

`numpy==1.22.4`:
```
python3 -c 'import numpy as np; a=6.336541010705443e-14; print((np.exp(-a)).tobytes(), (np.expm1(-a) + 1.0).tobytes())'
b'\xc5\xfd\xff\xff\xff\xff\xef?' b'\xc5\xfd\xff\xff\xff\xff\xef?'
```

which is the same.

Obviously the value returned from `np.exp` changed, while `np.exm1` did not. I am not sure what is correct, but we started seeing some test fail that compared the result of the two functions in some form.

### Reproduce the code example:

```python
import numpy as np; a=6.336541010705443e-14; print((np.exp(-a)).tobytes(), (np.expm1(-a) + 1.0).tobytes())'
```

### NumPy/Python version information:

I did the tests on python 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0], but the CI is also failing for other versions of python.
I used 1.23.0 here, but also 1.23.3 seems to still be affected by this. This was done on Ubuntu 20.04.5 LTS. I coworker run the same thing on MacOS 10.15.7 and he didn't saw the issue with either of these versions.

### Context for the issue:

It breaks our CI at https://github.com/lbl-anp/becquerel/. We calculate a lot of exponents for decay measurements and need to get consistent results.

**Comment by cosama** [comment]
We do not have exact comparison but multiplications with large numbers, thus `np.isclose` is failing too for the small difference above. We moved to `np.expm1` to use a single exp type function instead of multiple. It doesn't matter what result they produce as long as it is consistent.

**Comment by rkern** [comment]
You may need to adjust your tolerances in `np.isclose()`, then, to account for the expected inherent imprecision (or instability) in the subsequent floating point operations. This is a 1 ULP change in the result of `np.exp()`, the smallest possible change. If it is getting exploded by later operations, that difference is the inherent amount of tolerance that numerical algorithm needs to compare its results.

**Comment by cosama** [comment]
@rkern Thanks for that comment. I agree we could probably estimate the tolerance based on a 1ULP in the calculation, it is not straight forward though and we might want to think about a better solution for this particular case.

I will close this as the difference seems to be acceptable (I didn't know that a 1ULP change is okay) and thus an issue on our side. It is one of these situations where it is really hard to get it right, if not impossible because of numerical precision.
