### ISSUE TITLE
Numpy version compatibility check

### ISSUE THREAD

**Issue by pradeepdev-1995** [numpy/numpy#22397]
### Issue with current documentation:

There is numpy==1.22 installed on my machine. I want to install another package "X" which internally uses numpy==1.19. What will happen to the NumPy version in my system if I install package X? Will it overwrite the numpy==1.22 with numpy==1.19?

**Comment by mattip** [comment]
Yes, installing a different version of NumPy into a python environment will remove any existing one. You should see something along the lines of "Removing numpy 1.22" (when using `pip`, or a version conflict (if using conda/mamba). This is not a NumPy-specific issue or question. A particular Python environment can have only one copy of a package in `site-packages`. Thus the need for [virtual environments](https://virtualenv.pypa.io/en/latest/) which copy none, parts, or all of `site-packages` into a separate location, possibly using symbolic links to save disk space. Conda also allows creating multiple environments. Please search for more information in other places.

Closing.
