### ISSUE TITLE
DOC: Color scheme not in harmony with the dark mode of pydata-sphinx-theme

### ISSUE THREAD

**Issue by noritada** [numpy/numpy#22408]
### Issue with current documentation:

I often read NumPy documentation in dark mode, and I've found some coloring issues.
I will illustrate some of those issues mainly using [the documentation on `dtypes`](https://numpy.org/devdocs/reference/arrays.dtypes.html) as an example.

### Too dark text for some list components

Numbers in ordered lists and terms in description lists are too dark to read:

![ss 2022-10-08 15 51 41](https://user-images.githubusercontent.com/20850/194695133-e2d53c17-4d03-4b45-8d04-ddfb7fcee5a1.png)
![ss 2022-10-08 15 52 14](https://user-images.githubusercontent.com/20850/194695142-4ca8e3e7-5fdb-4984-b44d-ff36167b9951.png)

This issue also applies to [class definitions](https://numpy.org/devdocs/reference/generated/numpy.dtype.html#numpy.dtype):

![ss 2022-10-08 16 58 09](https://user-images.githubusercontent.com/20850/194696993-151f360a-f268-4d69-a0bc-90ac80a3612c.png)

This is because pydata-sphinx-theme [defines `color` for `body`](https://github.com/pydata/pydata-sphinx-theme/blob/v0.9.0/src/pydata_sphinx_theme/assets/styles/base/_base.scss#L12), whose value changes depending on the mode selected, but numpy.css's definition overwrites it.

### Too light color for the label of "dev" version selection button

The label of "dev" version selection button is colored light gray in the dark mode and the button itself is colored orange. The difference in brightness between those two colors is too small to read.
In the light mode, the label color is black and it looks clear.

![ss 2022-10-08 15 55 00](https://user-images.githubusercontent.com/20850/194696092-a1f7f95d-814f-4cd7-9207-f2f3d969d46b.png)

This is because pydata-sphinx-theme [defines `color` for `#version_switcher_button`](https://github.com/pydata/pydata-sphinx-theme/blob/v0.9.0/src/pydata_sphinx_theme/assets/styles/components/_switcher-version.scss#L3), whose value is `#c9d1d9` in the dark mode although it is `#333333` in the light mode.  numpy.css's definition only overwrites the background color for "dev".

### H3-level section heading colors

I think H3-level section heading colors is a bit too dark, but this may be a matter of opinion:

![ss 2022-10-08 15 54 25](https://user-images.githubusercontent.com/20850/194697146-8daa94fb-9c40-485c-9777-ed6092714556.png)

The cause is the same as that of the issue with the body text color; the color of `h3` is overwritten in numpy.css.

### Idea or request for content:

Some colors may need to be added, changed, or removed so that they can be used in dark mode as well. I will post a PR to show my own suggested changes after this.

**Comment by seberg** [comment]
As far as I understand gh-22409 should have fixed this, please note if not.
