### ISSUE TITLE
DOC: Remove info specific to Python 2 from the latest docs version

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [numpy/numpy#22400]
### Describe the issue:

Code/documentation specific to Python 2 is still scattered in Numpy:
https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/__init__.py#L204-L205

https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/distutils/command/config.py#L46-L50

https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/distutils/mingw32ccompiler.py#L187

https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/_globals.py#L86-L88

https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/core/_add_newdocs.py#L1357-L1358

[**doc/source/reference/c-api/array.rst**](https://github.com/numpy/numpy/blob/main/doc/source/reference/c-api/array.rst)
> ```
>     :c:type:`PyArray_Chunk` structure is binary compatible with the
>     Python's buffer object (through its len member on 32-bit platforms
>     and its ptr member on 64-bit platforms or in Python 2.5). On
> ```

Is it OK to submit a merge request when it's just a documentation issue?

For actual code, I don't always feel comfortable removing code documented to be for Python 2 only: it might be a documentation error and the code might be used by Python 3 too.

**Comment by InessaPawson** [comment]
> Is it OK to submit a merge request when it's just a documentation issue?

@DimitriPapadopoulos It would be preferred if you submit a pull request to address the inconsistencies in the documentation separately.

@melissawm Would in any of the instances above we prefer to keep references to Python 2? What are your thoughts on editing references to Python 2 in the NumPy documentation and code base in general?

**Comment by InessaPawson** [comment]
@DimitriPapadopoulos We have discussed this topic at the latest NumPy documentation team and community meetings. The consensus is that all the mentions of Python 2 should be removed from the NumPy codebase, including documentation. 
Feel free to submit additional commits to your [PR](https://github.com/numpy/numpy/pull/22411) to remove all references to Python 2 from the NumPy documentation.

**Comment by DimitriPapadopoulos** [comment]
I'm afraid it's not as simple as that. For example, the following piece of code is documented to be useful for Python 2. I suspect it is not needed for Python 3. I would rather remove the code, than remove the comment that reminds that the code had been added for Python 2:
https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/_globals.py#L86-L88

On the other hand, I am not 100% certain removing that code is OK. But then I guess this is what tests and reviewers are for.

Is it OK to remove the above code?

**Comment by DimitriPapadopoulos** [comment]
Merge request #22432 addresses this:
https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/distutils/mingw32ccompiler.py#L187

**Comment by DimitriPapadopoulos** [comment]
Merge request https://github.com/numpy/numpy/pull/22433 attempts to address this:

https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/distutils/command/config.py#L46-L67

**Comment by DimitriPapadopoulos** [comment]
Not sure what to do with this one:

https://github.com/numpy/numpy/blob/ae6a3524acc38edfdc3951622fcc598414cc78ec/numpy/_globals.py#L86-L88

Code added by 1271e17ea6ca8abe12f7dd045ac0af8674f594d4 on 4 February 2018, fixes https://github.com/numpy/numpy/issues/8991, closes https://github.com/numpy/numpy/pull/9592.

Clues anyone?

**Comment by seberg** [comment]
@DimitriPapadopoulos reduce is used for pickling, so long pickling and loading round-trip works it is good.  We have a test for this, so it is fine to delete this.

**Comment by melissawm** [comment]
Are we planning on leaving this open for folks who want to keep looking for these references to Python 2, or can we close?

**Comment by DimitriPapadopoulos** [comment]
Just FYI, I have been through `Python 2` and `python 2` (with space).

I have not addressed occurrences of `python2` (without space). Most of them are of historical interest (release notes for example) but a handful of them might be worth looking into.

**Comment by InessaPawson** [comment]
I've opened a new issue (https://github.com/numpy/numpy/issues/22635) to address the outstanding instances.
