### ISSUE TITLE
BUG: argsort return the wrong order!!!!!!!!!!

### ISSUE THREAD

**Issue by IkeYang** [numpy/numpy#22402]
### Describe the issue:

numpy version 1.17.0
python version 3.6.9 
windows 10

the argsort function returns the wrong result.

>>>np.argsort(np.array([3, 1, 2]))
array([1, 2, 0], dtype=int64)

### Reproduce the code example:

```python
import numpy as np

print(np.argsort(np.array([3, 1, 2])))
```

### NumPy/Python version information:

numpy version 1.17.0
python version 3.6.9 
windows 10

**Comment by mattip** [comment]
Why is this wrong? The way to sort [3, 1, 2] is to put 1 first (index 1), then 2 (index 2), then 3 (index 0), so the correct answer is [1, 2, 0]. What answer did you expect and why? Maybe you are confusing `np.argsort` with `np.sort`?

**Comment by rkern** [comment]
`argsort`'s behavior is subtle, and many people expect it to do something different than what it is documented to do (see #8757 and [other closed issues](https://github.com/numpy/numpy/search?q=argsort&state=closed&type=issues)). But it is behaving as designed and documented.

**Comment by IkeYang** [comment]
I am so sorry to misunderstand the code and the documents. Sorry for that.
