### ISSUE TITLE
Cron jobs failing on travis

### ISSUE THREAD

**Issue by charris** [numpy/numpy#22416]
Code 137 (oom) starting in the last week of September when running numpy/core/tests/test_memory/test_mem_policy.py::test_new_policy. See https://app.travis-ci.com/github/numpy/numpy/builds/256377644. Have we changed anything that would affect memory in the last three weeks? If not, I suspect new manylinux2014 wheels or some change in travisci memory policy.

**Comment by charris** [comment]
This also shows up in the 1.23.x branch, so might be related to `test_huge_vectordot` in some way.

**Comment by seberg** [comment]
This was the fixed up `test_huge_vectordot` and the manual memory limit on aarch64, right?  Closing.
