### ISSUE TITLE
DOC: <np.linalg.eig not working 'DOC: ' prefix>

### ISSUE THREAD

**Issue by kernel-loophole** [numpy/numpy#22410]
### Issue with current documentation:

import numpy as np
from numpy import linalg as LA
w, v = LA.eig(np.diag((1, 2, 3,4)))
print(w, v)

**Comment by zain581** [comment]
you may check out the docs for it

**Comment by zain581** [comment]
https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html

**Comment by zain581** [comment]
check it out this may solve the problem

**Comment by kernel-loophole** [comment]
great it wroked
