### ISSUE TITLE
DOC: <numpy.std() describes incorrect default ddof value>

### ISSUE THREAD

**Issue by nadia-paz** [numpy/numpy#22426]
### Issue with current documentation:

[https://numpy.org/doc/stable/reference/generated/numpy.std.html](url)

**`ddof` int,optional**
Means Delta Degrees of Freedom. The divisor used in calculations is N - `ddof`, where N represents the number of elements. **By default `ddof` is zero**.

When I do actual calculations turns out that the default value for `ddof` is **1,** not 0

**Comment by rkern** [comment]
Can you demonstrate with complete runnable example that demonstrates that?

```
In [1]: import numpy as np                                                                                                                                                                  

In [2]: x = np.linspace(0, 1, 11)                                                                                                                                                           

In [3]: np.std(x)                                                                                                                                                                           
Out[3]: 0.31622776601683794

In [4]: np.std(x, ddof=0)                                                                                                                                                                   
Out[4]: 0.31622776601683794

In [5]: np.std(x, ddof=1)                                                                                                                                                                   
Out[5]: 0.33166247903554
```

If you are using `pandas.Series` objects, please note that `pandas.Series.std()` chooses a different default.

**Comment by nadia-paz** [comment]
I'm sorry. My fault, I just went through my code again and noticed that I
applied std() method to Series, not an array. I converted Series to an
array and it returned me the correct std value. You can close the issue.

**Comment by rkern** [comment]
No worries! Thank you for taking the time to go back and look.
