### ISSUE TITLE
BUG: `np.arccos` giving `invalid value` warnings for values that are in range.

### ISSUE THREAD

**Issue by Zach-ER** [numpy/numpy#22423]
### Describe the issue:

I'm using `np` version `1.23.2` and am getting the following error when computing `arccos` in `fp32`.

```
<ipython-input-2-99ce1976fba5>:2: RuntimeWarning: invalid value encountered in arccos
  np.arccos(np.float32(0.9))
```

The value is still computed and I can silence the warnings with the warnings package, but this is not ideal behaviour.

`np.arccos(0.9)` works just fine — as does  `np.arccos(np.float64(0.9))` (which I think are the same thing).

### Reproduce the code example:

```python
import numpy as np
print(np.arccos(np.float32(0.9)))
```
```


### Error message:

```shell
ipython-input-4-62ad8cea88ff>:2: RuntimeWarning: invalid value encountered in arccos
```

### NumPy/Python version information:

1.23.2

**Comment by seberg** [comment]
Thanks for the report, could you help us narrow it down, first please give some details about your system, the first bit of output from `np.test()`.
I.e. what kind of system (linux, Mac, e.g. the first line that `python` prints when invoked in the command line).  Also paste the early output of `np.test()` which shows the CPU features. For me it shows:
```
NumPy CPU features:  NEON NEON_FP16 NEON_VFPV4 ASIMD ASIMDHP* ASIMDDP* ASIMDFHM?
```
Another thing, could you also check whether:
```
np.arccos(np.float32([0.9] * 8))
```
has the same issue?

These types of issues happened before with new SIMD code, so I suspect it will be easy enough to figure out the why.

**Comment by seberg** [comment]
Btw. as a workaround, `with np.errstate(invalid="ignore"):` (or `all="ignore"`) is a nicer way to modify how/if these specific warnings are shown.

**Comment by Zach-ER** [comment]
Thanks for the super-speedy response and workaround!

I am running in Colab.

Early response of `np.test()`: 
```
NumPy version 1.23.2
NumPy relaxed strides checking option: True
NumPy CPU features:  SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2
```

`np.arccos(np.float32([0.9] * 8))` **DOES** have the same issue.

**Comment by seberg** [comment]
Hmmm, weird, sorry fishing a bit now since I don't think we have any special SIMD versions for `acos` except SVML, and SVML is AVX512 only, so that can be ruled out.  It seems likely that this is an issue with the system math library.

What does `python` print out e.g.:
```
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ] on darwin
```
(maybe that helps get an idea).

A bit of a weirder try, what does this do:
```python
lib = ctypes.cdll.LoadLibrary(None)
lib.acos(ctypes.c_float(0.9))
import ctypes
lib = ctypes.cdll.LoadLibrary(None)

def sysacosf(x):
    return lib.acosf(ctypes.c_float(x))

sysacosf = np.frompyfunc(sysacosf, 1, 0)

sysacosf(0.9)  # should not warn
```
If that does not give a warning, this should:
```
sysacosf(np.inf)  # should warn
```

**Comment by Zach-ER** [comment]
Re the `python`, as I said this is a `Colab`. Do you want me to run `!python`?

The weirder idea: no warning at all (as you said).

The last one **does** give a warning:

```
<ipython-input-8-22af4cde8379>:1: RuntimeWarning: invalid value encountered in sysacosf (vectorized)
  sysacosf(np.inf)
```

**Comment by seberg** [comment]
> Re the python, as I said this is a Colab. Do you want me to run !python?

Yeah, I guess. Would have to look up how to get the information best.  Maybe I am just missing something, maybe `np.show_config()` is also useful to look at.

But, right now I don't have a good idea, since I somewhat expected that `ctypes` code chunk to give the warning as well.  So I am wondering whether I am missing something obvious...

**Comment by mattip** [comment]
> I am running in Colab.

Blindly starting up a colab session, I get `numpy==1.21.6` with CPython 3.7.14. Is there a trick to replicate your environment?

**Comment by mattip** [comment]
On this session, I get
```
import platform
platform.libc_ver()
('glibc', '2.26')
```

**Comment by mattip** [comment]
Also, what does `import sys; print(sys.version)` show?

**Comment by Zach-ER** [comment]
I am using an internal Colab at Google.

I get `('glibc', '2.27')` looking at the `platform.libc_ver()`.

`sys.version` gets `3.9.14 (stable, redacted, redacted)`

`np.show_config()` gets 
```
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3,SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    found = 
    not found = 
```

@seberg just to confirm, the `lib.acos` worked fine and the `sysacosf` got the error (I edited an earlier response, just checking we're on the same page)

**Comment by seberg** [comment]
Sorry, I guess I misread.  If you get a warning with the `# should not warn` line, that that proofs that your system math library is faulty and NumPy has nothing to do with it.  Glibc might be the right thing to hunt down, but not imediately sure.

**Comment by mattip** [comment]
I wonder if your python/numpy build is using "bad" math flags like [`-ffast-math`](https://gcc.gnu.org/wiki/FloatingPointMath). This might show up python in 
```
python -c "import sysconfig; print(sysconfig.get_config_var('CFLAGS'))"
``` 

or more generally in any of the values in 

```
python -c "import sysconfig, pprint; pprint.pprint(sysconfig.get_config_vars())"
```

We don't bake the compiler flags used to build NumPy into the build process. I think there is a way to detect the floating-point related registers at runtime.

**Comment by seberg** [comment]
Ah, right... `-ffast-math` definitely might cause this type of things.  In this case probably even a choice in the system math library, not even NumPy compliation itself.

Anyway, closing the issue, since the plot is thickening that this is nothing directly NumPy related.  We can keep discussing though!

**Comment by Zach-ER** [comment]
Thanks so much for your help! I have logged a bug with our internal team.

There is no `-ffast-math` flag I can see but I'm sure we'll get a resolution.

Thanks again — what service 🙌🏻 🙌🏻 🙌🏻 🙌🏻 🙌🏻
