### ISSUE TITLE
numpy installation issue on linux

### ISSUE THREAD

**Issue by raad-altaie** [numpy/numpy#22439]
### Steps to reproduce:

I am trying to install numpy on linux but i am getting the error below

anyone knows how i can fix that?

thanks

### Error message:

```shell
We have compiled some common reasons and troubleshooting tips at:

https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

The Python version is: Python3.7 from "/usr/bin/python3" * The NumPy version is: "1.21.4"
and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

**Comment by rgommers** [comment]
> `Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory`

This doesn't tell us why. If you built from source, can you please provide the full build log?
