### ISSUE TITLE
BUG: Typing warning when subtracting two numpy arrays

### ISSUE THREAD

**Issue by ortk95** [numpy/numpy#22437]
### Describe the issue:

Subtracting two numpy arrays incorrectly produces the typing warning `Operator "-" not supported for types "ndarray[Unknown, Unknown]" and "ndarray[Unknown, Unknown]"`

<img width="600" alt="image" src="https://user-images.githubusercontent.com/26504228/195802734-77ce12f2-6c15-4dee-85a0-1034a3dffb8f.png">

### Reproduce the code example:

```python
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

a = x - y # Operator "-" not supported for types "ndarray[Unknown, Unknown]" and "ndarray[Unknown, Unknown]"

# These are fine:
b = x + y
c = x * y
d = x / y
```

### NumPy/Python version information:

1.21.5 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:43:32) [Clang 12.0.1 ]

### Context for the issue:

This makes it difficult to use numpy when type checking is turned on, as the code is filled with incorrect warnings

**Comment by seberg** [comment]
Ah, as pointed out in the pylance issue, gh-22359 fixed up NumPy to work with their conservative approach (or maybe it was always necessary, not sure, in any case the specific issue is fixed).
