### ISSUE TITLE
BUG: (NEP 18) np.linalg.pinv uses least specialised implementation if first stack elements is a pure np.ndarray

### ISSUE THREAD

**Issue by neutrinoceros** [numpy/numpy#22444]
### Describe the issue:

Implementing a specialised version of `np.linalg.pinv` that works on stack of matrices proves to be tricky (or impossible).

unyt (arrays with units) currently has a very (too) simple specialised implementation, see
https://github.com/yt-project/unyt/blob/7b65bc9a5eefea7d4301da371530ec2ac8124110/unyt/_array_functions.py#L113-L115

We check that it works for single matrices
https://github.com/yt-project/unyt/blob/7b65bc9a5eefea7d4301da371530ec2ac8124110/unyt/tests/test_array_functions.py#L444-L450

However the specialized implementation is completely skipped when
passing a *stack* of arrays, as illustrated in two xfailing tests, where the base implementation is used instead.
https://github.com/yt-project/unyt/blob/7b65bc9a5eefea7d4301da371530ec2ac8124110/unyt/tests/test_array_functions.py#L452-L479

It is not clear wether this behaviour is to be expected, and we would like to know how to best handle this limitation downstream: should be considered a bug in numpy ? should it be advertised in unyt's docs ?

### Reproduce the code example:

```python
# this example is only relevant with unyt installed from the dev branch ATM
# pip install git+https://github.com/yt-project/unyt@main

import numpy as np
import unyt as un

stack = [
    un.unyt_array(np.eye(4), 'g'),
    np.eye(4)
]
assert type(np.linalg.pinv(stack)) is un.unyt_array
```

### Error message:

```shell
AssertionError: ...
```

### NumPy/Python version information:

numpy>=1.17.5
Python>=3.8

**Comment by mhvk** [comment]
In your example, you are passing on a list rather than an actual `unyt` instance; the `__array_function__` dispatch machinery just checks whether the input defines `__array_function__` and a list does not do that (dispatch does not look inside lists except if a list of arrays is expected as for `np.concatenate` etc.). In general, conversion of lists is a "convenience" numpy provides that only works if you want the list to be turned into an array.

p.s.  For reference, here's astropy's implementation: https://github.com/astropy/astropy/blob/e8961b8675c6d490ad0fd11bc3965636a0687ba1/astropy/units/quantity_helper/function_helpers.py#L989-L993

**Comment by neutrinoceros** [comment]
Yes I realize that passing a list is a special case, but since it works with numpy.concatenate, it doesn't seem too far from reach for numpy.linalg.pinv 

If that's actually not fixable on numpy's side we'll just document it as an external limitation, it's just that we'd like to avoid receiving bug reports on this if it's out of our control.

**Comment by seberg** [comment]
Closing, the only question here is whether `np.asarray()` or a version of it should actually promote embedded array-types.  (I.e. functions would call a new `asduckarray()` _before_ dispatching, and that would implicitly deal with the stacking by casting the NumPy array to a unyt one.)

That seems much further fetched though and in the meantime `np.asarray([...], like=stack[0])` exists, `np.concatenate()` also works well for many use-cases.

**Comment by neutrinoceros** [comment]
This is reasonable, thank you for expliciting workarounds here !
