### ISSUE TITLE
No module named 'numpy.core._multiarray_umath' on Ubuntu

### ISSUE THREAD

**Issue by ericahellscythe** [numpy/numpy#22460]
### Steps to reproduce:

No module named 'numpy.core._multiarray_umath' 

Installed Python: apt-get install python3.9
install numpy: apt-get install python3-numpy

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

/usr/lib$ ls -lrt |grep python
drwxr-xr-x   3 root root     4096 Jan 21  2021 python3
drwxr-xr-x  32 root root    20480 Sep 16 18:00 python3.8
drwxr-xr-x  27 root root    24576 Sep 16 18:05 python2.7
drwxr-xr-x  31 root root    12288 Sep 19 10:21 python3.9
drwxr-xr-x  28 root root    12288 Oct  3 18:37 python3.7

### Error message:

```shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arm-orin-01/backup/src/nat_ws/scripts/azure_kinect.py", line 13, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.9 from "/bin/python3.9",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Additional information:

Whenever I click the run button on visual studio code or press ctrl f5 to execute my program, the error message will always appear. 

However, when I run my program using 'python my_python_file.py ', it runs perfectly fine. 

Typing python in the cmd and using numpy also doesn't have any issue.

**Comment by mattip** [comment]
What happens when you type `python3.9 my_python_file.py`? I assume it fails. 

`python` and `python3.9` are different, you need to either use `python` in visual studio code or install numpy for `python3.9`. In general this is the problem python virtual environments are meant to solve, then you would make sure you are using the same virtual environment from the command line and from visual studio code.

**Comment by ericahellscythe** [comment]
AH RIGHT. Thanks for the advice! I solved it. Gonna close the issue now.
