### ISSUE TITLE
BUG: RuntimeWarning on ARM64 but not x86_64 for cosine of float32 NaNs

### ISSUE THREAD

**Issue by blthayer** [numpy/numpy#22461]
### Describe the issue:

The title sums it up, let's let the code do the talking :)

### Reproduce the code example:

On an ARM64 machine running Ubuntu 20.04:

```python
Python 3.10.8 (main, Oct 18 2022, 11:26:55) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'aarch64'
>>> import numpy as np
>>> np.__version__
'1.23.4'
>>> array = np.array([np.nan, np.nan, np.nan], dtype=np.float64)
>>> np.cos(array)
array([nan, nan, nan])
>>> np.cos(array.astype(np.float32))
<stdin>:1: RuntimeWarning: invalid value encountered in cos
array([nan, nan, nan], dtype=float32)
>>> np.seterr()
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>>
```

On an Intel machine running Ubuntu 22.04:

```python
ython 3.10.8 (main, Oct 12 2022, 12:54:48) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'x86_64'
>>> import numpy as np
>>> np.__version__
'1.23.4'
>>> array = np.array([np.nan, np.nan, np.nan], dtype=np.float64)
>>> np.cos(array)
array([nan, nan, nan])
>>> np.cos(array.astype(np.float32))
array([nan, nan, nan], dtype=float32)
>>> np.seterr()
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>>
```

### NumPy/Python version information:

Python: `3.10.8`
Numpy: `1.23.4`

```shell
$ poetry run python -c "import numpy; numpy.show_config()"
<snip blas stuff (@seberg)>

Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP
    not found = ASIMDDP,ASIMDFHM
```

### Context for the issue:

I develop on an Intel machine, but deploy to ARM machines, and this makes things tricky :smile:

**Comment by mattip** [comment]
For completeness, could you show the "Supported SIMD extensions" part of
```
python -c "import numpy; numpy.show_config()"
```

on the aarch64 machine?

**Comment by seberg** [comment]
I can confirm that this comes from a SIMD code problem on AARCH64 (confirming on an M1).  But didn't manage to narrow it down more as of now.  I thought it might be the
```
npyv_b32 simd_mask = npyv_cmple_f32(npyv_abs_f32(x_in), max_cody);
```
but replacing that with a `neq` doesn't help (unless I also remove the result storing, but at that point the compiler might just optimize everything away).
Looks like this needs a deep look into where the warning flag gets set (or what the compiler does).

**Comment by blthayer** [comment]
> For completeness, could you show the "Supported SIMD extensions" part of
> 
> ```
> python -c "import numpy; numpy.show_config()"
> ```
> 
> on the aarch64 machine?

Sure thing!

```shell
$ poetry run python -c "import numpy; numpy.show_config()"
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP
    not found = ASIMDDP,ASIMDFHM

```

**Comment by mattip** [comment]
I think this came from #21955. Maybe scattering a few of these around the code would help?
```
if (fetestexcept(FE_INVALID) != 0) {
  printf("gotcha! %d\n", __LINE__);
}
```

**Comment by seberg** [comment]
Not sure how useful this is, actually (without looking at instruction level).  Maybe @Developer-Ecosystem-Engineering has a tip, since this affects M1s also.

Based on sprinkling those, it would look a bit like it is both the `npyv_store_till_f32` and the `simd_maski != 0`, so I am not sure that there is just a lot of compiler stuff going on.

**Comment by seiko2plus** [comment]
Arm64/ASIMD only supports ordered comparison with exceptions controlled by `FPCR` register, which by default is set to `IOE`; in other words, the RuntimeWarning is caused by `npyv_cmple_f32`:
```C
npyv_b32 simd_mask = npyv_cmple_f32(npyv_abs_f32(x_in), max_cody);
```
Arm64 doesn't provide an inline mask controller to choose between signaling and non-signaling like x86, so the fix usually will cause few instructions.
