### ISSUE TITLE
<Importing the multiarray numpy extension module failed>

### ISSUE THREAD

**Issue by HARAQUEL** [numpy/numpy#22473]
### Steps to reproduce:

Hi! I installed Anaconda to run PartitionFinder on my computer, but when I run my command line 
python C:/PROGRAMAS/partitionfinder2/PartitionFinder.py C:/Users/haust/FilogeniaCapitulonitidus/nitiduscomplex.phy

shows this error: DLL load failed: No se puede encontrar el m¾dulo especificado.

Can you help me please?!

Thanks!

### Error message:

```shell
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\haust\Anaconda2\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: No se puede encontrar el m¾dulo especificado.
```

**Comment by seberg** [comment]
Seems you are working of a pretty old version of NumPy (this should not matter).  Please check out: https://numpy.org/devdocs/user/troubleshooting-importerror.html for some hints of what may be wrong, often the anaconda environment is not properly activated.

**Comment by seberg** [comment]
Going to close the issue. @HARAQUEL you are very welcome to continue the discussion or ask questions, though.  But since this usually is just due to forgetting to activate the environment correctly, I hope you already found the solution!
It is also typically easier to ask someone for help locally for this type of issues.
