### ISSUE TITLE
BUG: Incorrect typing when using array directly verses assignment

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#22470]
### Describe the issue:

The type revealed by mypy depends on whether the array is assigned to a variable or not.  This may very well be a mypy bug.

### Reproduce the code example:

```python
import numpy.typing as npt
import numpy as np

from typing import overload

@overload
def f(x: npt.NDArray[np.int64]) -> npt.NDArray[np.int64]:
    ...
@overload
def f(x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]:
    ...

def f(x):
    return x


a = np.array([1, 2, 3], dtype=np.int64)
reveal_type(a)
reveal_type(f(a))
reveal_type(f(np.array([1, 2, 3], dtype=np.int64)))

b = np.array([1, 2, 3], dtype=np.float64)
reveal_type(b)
reveal_type(f(b))
# This final one returns int64 not float64
reveal_type(f(np.array([1, 2, 3], dtype=np.float64)))
```

### Error message:

```shell
blah.py:18: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.signedinteger[numpy._typing._64Bit]]]"
blah.py:19: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.signedinteger[numpy._typing._64Bit]]]"
blah.py:20: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.signedinteger[numpy._typing._64Bit]]]"
blah.py:23: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.floating[numpy._typing._64Bit]]]"
blah.py:24: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.floating[numpy._typing._64Bit]]]"
blah.py:25: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.signedinteger[numpy._typing._64Bit]]]"
```

### NumPy/Python version information:

1.23.4 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

The final 3 revealed types should be "numpy.ndarray[Any, numpy.dtype[numpy.floating[numpy._typing._64Bit]]]", but for some reason the final is "numpy.ndarray[Any, numpy.dtype[numpy.signedinteger[numpy._typing._64Bit]]]" instead.

**Comment by BvB93** [comment]
Yeah, this definitely sounds like a mypy bug. I've got the suspicion that mypy chokes somewhere and ends up with a `Any`-based dtype, one that passes through the first overload by simply using that as a default.

**Comment by jorenham** [comment]
I just tested this with `mypy==1.11.1` and `numpy==2.1.0rc1`, and mypy still reveals the same (wrong) type.

I also confirmed that `pyright==1.1.376` doesn't have this issue. 
So it's indeed a mypy bug.
