### ISSUE TITLE
ENH: Add the OpenSSF Scorecards GitHub Action

### ISSUE THREAD

**Issue by pnacht** [numpy/numpy#22476]
### Proposed new feature or change:

Hi, I'm Pedro and I'm working for Google and the [Open Source Security Foundation][ossf] to help essential open-source projects improve their supply-chain security. Given that NumPy is, to quote the moto, "the fundamental package for scientific computing with Python," the OpenSSF has identified it as one of the 100 most critical open source projects.

NumPy has already collaborated with the OpenSSF in #20584 (shipping 2FA tokens to NumPy maintainers). Continuing our efforts to improve the security of open-source software, I'd like to suggest the adoption of a new OpenSSF tool, the [Scorecards GitHub Action][sc-gha].

The [Scorecards][sc] system runs dozens of automated security [checks][checks] to help maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, [in partnership with GitHub][sc-blog].

The Action performs these checks automatically after every commit to the main branch. The results of its checks are available on the project's [security dashboard](https://github.com/numpy/numpy/security), and include suggestions on how to solve any issues (see an example below). It's already been adopted by 1800+ projects, including [Tensorflow][tensorflow],  [PyTorch][pytorch], [Angular][angular], and [Flutter][flutter].

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

If you have any questions about Scorecards, you can check out its [FAQ][faq] or just ask me!

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[angular]: https://github.com/angular/angular  
[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[checks]: https://github.com/ossf/scorecard#scorecard-checks
[faq]: https://github.com/ossf/scorecard/blob/main/docs/faq.md#frequently-asked-questions
[flutter]: https://github.com/flutter/flutter
[ossf]: https://openssf.org/
[pytorch]: https://github.com/pytorch/pytorch
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[tensorflow]: https://github.com/tensorflow/tensorflow

[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by seberg** [comment]
@pnacht yes, we were discussing trying it out to see how it is/goes.  So a PR would be a great start for us, I think.
