### ISSUE TITLE
BUG: numpy does not upcast with tensordot and einsum

### ISSUE THREAD

**Issue by cmglaze** [numpy/numpy#22484]
### Describe the issue:

numpy does not appear to upcast output variable types with either `tensordot `or `einsum`, which isn't explained in the docs. This can lead to dramatic deviations in output from expected.

### Reproduce the code example:

```python
import numpy as np

x = np.ones((1000,1)).astype('uint8')
np.tensordot(x,x), np.einsum("ij,ij->j", x,x)
```

### NumPy/Python version information:

1.22.2

### Context for the issue:

Any codebase attempting to optimize for memory footprint by casting variables to smallest required will be affected if they use the affected methods. dot products do appear to upcast, which means that operations which should have equivalent output do not.

**Comment by seberg** [comment]
NumPy almost never promotes beyond the normal common dtype/promotion for mixed dtypes.  The only exceptions are `sum` and `prod` (and functionality using them internally).
You can use `dtype=` to enforce the promotion/upcast.

**Comment by seberg** [comment]
Closing, I don't think are likely to change promotion here at this point.
