### ISSUE TITLE
BUG: mypy error negative of sum

### ISSUE THREAD

**Issue by igordertigor** [numpy/numpy#22495]
### Describe the issue:

When using `-np.sum(x)` to calculate the sum of an array's elements, mypy complains:
```
test.py:5: error: Unsupported operand type for unary - (<nothing>)
Found 1 error in 1 file (checked 1 source file)
```
when using `-x.sum()` instead, it does not complain.

I'm not sure if this is an issue with the mypy plugin at `numpy.testing.mypy_plugin` or with mypy itself. So I'm posting here in case it's the former.

### Reproduce the code example:

```python
import numpy as np


def fail(p: np.ndarray) -> float:
    return -np.sum(p)


def ok(p: np.ndarray) -> float:
    return -p.sum()


if __name__ == '__main__':
    print(fail(np.ones(3)))
    print(ok(np.ones(3)))
```

### Error message:

```shell
See above for error message. The example code works fine and both print statements print '3.0' as expected.
```

### NumPy/Python version information:

1.23.4 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0]

### Context for the issue:

This doesn't directly affect my work as mypy can be silenced for the respecitve line using a `# type: ignore` comment. However, given that mypy-compatibility appears to be something that more and more libraries are aiming at (including numpy) I felt that raising awareness for this issue is useful.

**Comment by Lahiry** [comment]
Hey @igordertigor I'll take a look and try to fix it!

**Comment by aayushagrawal135** [comment]
This seems to work for me correctly, at least for Python 3.8.10.

**Comment by igordertigor** [comment]
Thanks for the update. Then I'll see what mypy says about it.
