### ISSUE TITLE
DOC: No Windows Build

### ISSUE THREAD

**Issue by story645** [numpy/numpy#22499]
### Issue with current documentation:

I can't build it on windows 'cause there's no windows compatible build system.

### Idea or request for content:

I was gonna make a make.bat compatible with the makefile, but since that takes time was wondering if there's interest?

**Comment by mattip** [comment]
Do you mean in parallel to `doc/Makefile` ? Our Makefile does more than just run `sphinx-build`. I don't know if any of that is possible on windows (some of the options may be outdated and unused):
```
$ cd doc
$ make help

Please use `make <target>' where <target> is one of
  clean     to remove generated doc files and start fresh
  docenv    make a virtual environment in which to build docs
  html      to make standalone HTML files
  htmlhelp  to make HTML files and a HTML help project
  latex     to make LaTeX files, you can set PAPER=a4 or PAPER=letter
  changes   to make an overview over all changed/added/deprecated items
  linkcheck to check all external links for integrity
  dist PYVER=... to make a distribution-ready tree
  gitwash-update GITWASH=path/to/gitwash  update gitwash developer docs
  merge-doc TAG=... to clone numpy/doc and archive documentation into it
  show      to show the html output in a browser
```

**Comment by mattip** [comment]
I think the bare minimum would be a good start, then we can add more if needed (probably never)
