### ISSUE TITLE
BUG: `array_dlpack_deleter` does not take the GIL before calling into CPython API

### ISSUE THREAD

**Issue by albanD** [numpy/numpy#22507]
### Describe the issue:

For numpy >= 1.23.4, the repro below fails for latest PyTorch.
Downgrading numpy to 1.21 for example makes the error go away.

It is not clear to me if array_dlpack_deleter should always be called with the GIL already held or not?
If so, what should we do if the python interpreter is already dead by the time where we would like to call this deleter?

### Reproduce the code example:

```python
import torch

x = torch.zeros(10)
data_np = x.detach().cpu().numpy()
rev = torch.utils.dlpack.from_dlpack(data_np)
```

### Error message:

```shell
Fatal Python error: Python memory allocator called without holding the GIL                                           
Python runtime state: finalizing (tstate=0x779540)

Current thread 0x00007ffff7c75740 (most recent call first):
<no Python frame>
Thread 1 "python" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44

                           
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#1  0x00007ffff7d1b5d3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7cced16 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7ca27f3 in __GI_abort () at abort.c:79
#4  0x00000000005154c1 in fatal_error (prefix=prefix@entry=0x0, 
    msg=msg@entry=0x6153e8 "Python memory allocator called without holding the GIL", status=status@entry=-1)
    at Python/pylifecycle.c:2183
#5  0x0000000000517f2a in Py_FatalError (
    msg=msg@entry=0x6153e8 "Python memory allocator called without holding the GIL") at Python/pylifecycle.c:2193
#6  0x000000000046c9b5 in _PyMem_DebugCheckGIL () at Objects/obmalloc.c:2295
#7  0x000000000046ce85 in _PyMem_DebugFree (ctx=0x72a350 <_PyMem_Debug+48>, ptr=0x7c2f80) at Objects/obmalloc.c:2317
#8  0x000000000046dc21 in PyMem_Free (ptr=<optimized out>) at Objects/obmalloc.c:629
#9  0x000000000059e090 in _PyFaulthandler_Fini () at ./Modules/faulthandler.c:1413
#10 0x00000000005154a9 in fatal_error (prefix=prefix@entry=0x0, 
    msg=msg@entry=0x6153e8 "Python memory allocator called without holding the GIL", status=status@entry=-1)
    at Python/pylifecycle.c:2166
#11 0x0000000000517f2a in Py_FatalError (
    msg=msg@entry=0x6153e8 "Python memory allocator called without holding the GIL") at Python/pylifecycle.c:2193
#12 0x000000000046c9b5 in _PyMem_DebugCheckGIL () at Objects/obmalloc.c:2295
#13 0x000000000046ce85 in _PyMem_DebugFree (ctx=0x72a350 <_PyMem_Debug+48>, ptr=0x7fffea6097b0)
    at Objects/obmalloc.c:2317
#14 0x000000000046dc21 in PyMem_Free (ptr=<optimized out>) at Objects/obmalloc.c:629
#15 0x00007fff41216d4a in array_dlpack_deleter ()
   from /home/albandes/local/pytorch/3.8_debug_source_env/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#16 0x00007fffe2a6abbc in c10::deleteInefficientStdFunctionContext(void*) ()
   from /home/albandes/local/pytorch/3.8_debug_source/torch/lib/libc10.so
#17 0x00007fffe97091f6 in c10::StorageImpl::~StorageImpl() ()
   from /home/albandes/local/pytorch/3.8_debug_source/torch/lib/libtorch_python.so
#18 0x00007fffe2a812f9 in c10::TensorImpl::~TensorImpl() ()
   from /home/albandes/local/pytorch/3.8_debug_source/torch/lib/libc10.so
```

### NumPy/Python version information:

1.23.4 3.8.13+ (heads/3.8:69cf0203ab, May 17 2022, 10:58:18) 
[GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]

### Context for the issue:

Original report from user: https://github.com/pytorch/pytorch/issues/88082

**Comment by seberg** [comment]
Yeah, we should probably just add the GIL grabbing here.  would be nice to also add a PR to mention that in DLPack.  PRs welcome ;) (clearly).

**Comment by albanD** [comment]
Hey!
Sure I can send a PR to update this destructor.
Within PyTorch, we use the following pattern in our destructors for objects that can be kept alive by c++ code (and thus outlive the python interpreter):
```c++
  // Leak the pyobj if not initialized.  This can happen if we are running
  // exit handlers that are destructing c++ objects with residual (owned)
  // PyObjects stored in them.
  if (!Py_IsInitialized())
    return;

  pybind11::gil_scoped_acquire gil;
  // The actual destructor code that does decref
```
Should I add this logic as well? Any generic helper file where this kind of logic should live to be re-usable?

> would be nice to also add a PR to mention that in DLPack.

I'm not familiar on how DLPack works. What do you mean here?

**Comment by seberg** [comment]
Somthing like that, clearly Python is always initialized, though and we are not using C++.  Well, DLPack has its own repo and data-api's also has some information.

To ensure everyone implementing it supports non-GIL users, *documenting* the requirement would be helpful.

**Comment by albanD** [comment]
> But IIRC, there is already an issue about that in dlpack.

The corresponding DLPack issue: https://github.com/dmlc/dlpack/issues/103
It does suggest that the destructor should indeed work fine when the GIL is not held. I'll send a PR for this.

**Comment by seberg** [comment]
Closing (seems we forgot to auto-close tag)/

**Comment by seberg** [comment]
The PR was not tagged so it was missed.  I doubt there will be another release, though, unfortunately.  OTOH, I am wondering if you are hitting this due to NumPy or rather some other libs.

**Comment by albanD** [comment]
Yes we did add an optimization recently to be more aggressive with GIL release when calling into c++ destructors. It was "dangerous" but does give quite a nice speedup.
I think that adding a backcompat hack would be ok for sure, not sure how hard it will be though on our end.
