### ISSUE TITLE
BUG: Exit when converting tif images to numpy arrays

### ISSUE THREAD

**Issue by chinoll** [numpy/numpy#22501]
### Describe the issue:

I opened a tif image using PIL, and when it was converted to a numpy array, python exited straight away without any error reporting

### Reproduce the code example:

```python
from PIL import Image
import numpy as np
img = Image.open("image.tif") #image size:500x800,image mode=L
img = np.array(img)
```

### Error message:

```shell
No error message, exit directly
```

### NumPy/Python version information:

1.23.4 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]

**Comment by seberg** [comment]
This is certainly a PIL issue, just try using `img.__array__()` instead to show that.  Can you open an issue there?

**Comment by seberg** [comment]
Closing, happy to help, but I think the next step will be opening the issue there (and checking your PIL version maybe).
