### ISSUE TITLE
BUG: linalg.norm ord=1 not recognising matrices

### ISSUE THREAD

**Issue by ccrnn** [numpy/numpy#22513]
### Describe the issue:

I'm getting the wrong l1 norm for matrices.

### Reproduce the code example:

```python
udash = np.array([[83.352, 34.3638, -3.06576],
[0.708986, -1.14925, 6.39411],
[0.443852, -1.0986, -0.246673]])

npl.norm(udash, ord=1)
```
npl.norm(udash, ord=1)
Out[330]: 84.50483644507106

Seems it's giving me the vector norm. Maybe I've misused this? But it seemed on the documentation that I could use this on a matrix.
```


### Error message:

_No response_

### NumPy/Python version information:

import sys, numpy; print(numpy.__version__, sys.version)
1.23.4 3.10.6 | packaged by conda-forge | (main, Oct  7 2022, 20:14:50) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

_No response_

**Comment by WarrenWeckesser** [comment]
`ord=1` corresponds to the [matrix norm induced by the vector 1-norm](https://en.wikipedia.org/wiki/Matrix_norm#Matrix_norms_induced_by_vector_p-norms).  The formula is in the table of the [norm docstring](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) and  in the wikipedia article: `max(sum(abs(x), axis=0))`.

For example,
```
In [19]: udash
Out[19]: 
array([[83.352   , 34.3638  , -3.06576 ],
       [ 0.708986, -1.14925 ,  6.39411 ],
       [ 0.443852, -1.0986  , -0.246673]])

In [20]: np.linalg.norm(udash, ord=1)
Out[20]: 84.504838

In [21]: np.max(np.sum(np.abs(udash), axis=0))
Out[21]: 84.504838
```
