### ISSUE TITLE
BUG:  No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by fin-github** [numpy/numpy#22517]
### Describe the issue:

 I was using code for an ai premade then while running the script in terminal (not cmd.) I ran the `py main.py` script and it said **No module called Numpy**, I typed the `pip3 install numpy` and it said `Requirement already satisfied: numpy in c:\users\serveradmin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (1.23.4)` I understood what it meant, and dragged numpy into the directory that I was working on. It ran and this time I didn't get that error but this error: `ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Users\finle\AppData\Local\Programs\Python\Python311\python.exe"
  * The NumPy version is: "1.23.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'` I searched up the issue including the numpy.core problem and got basically nothing. Please help.

### Reproduce the code example:

```python
No module named 'numpy.core._multiarray_umath'
```

### Error message:

```shell
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Users\finle\AppData\Local\Programs\Python\Python311\python.exe"
  * The NumPy version is: "1.23.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### NumPy/Python version information:

1.23.4

**Comment by mattip** [comment]
Typing `pip3 install numpy` will use whatever python happens to appear first on your PATH, which apparently is the one in
> `c:\users\serveradmin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0`

and not in
> `C:\Users\finle\AppData\Local\Programs\Python\Python311`

You apparently took a numpy that was built for python3.9 and copied it into a python 3.11. Remove it, and install a proper version:
```
C:\Users\finle\AppData\Local\Programs\Python\Python311\python.exe -m pip install numpy
```

**Comment by seberg** [comment]
Closing, you can try asking further, but there is no numpy issue.  There is clearly an environment issue here, probably the PATH as Matti points out.

**Comment by fin-github** [comment]
Thanks. I found what was wrong. When I uninstalled py 3.9 it didnt uninstall the package in the `c:\users\serveradmin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0` path. When I get the admin password back I will try removing that file. I will update you if that works.
