### ISSUE TITLE
BUG: Value of ndarray depends on previous operations

### ISSUE THREAD

**Issue by ikamensh** [numpy/numpy#22529]
### Describe the issue:

Value of an array depends on whether I do a specific numpy call before initializing it.

### Reproduce the code example:
Good:
```python

import numpy as np

np.ndarray([0])
action = np.ndarray([1])
print(float(action))  # 1.0
```

Bad:
```python
import numpy as np

action = np.ndarray([1])
print(float(action))  # 5e-324
```

### NumPy/Python version information:

1.22.0 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]

### Context for the issue:

This was a bug that took 4hrs to track down, admittedly because I forgot not to use np.ndarray . Since I use np.ndarray for typing in many places, I intuitively initialized it with a constructor.

Remark: I've tested it on python 3.11 and numpy 1.23.4, and result is different - independent of other value being created, `float(np.ndarray([1]))` gives `2.2803010541544873e-31`.

I wish at least a warning was issued, e.g. deprecation warning.

**Comment by rossbar** [comment]
Thanks @ksunden , this is indeed likely the source of the confusion in this case and sufficiently addresses the issue, so I will close this. If questions remain please don't hesitate to follow up.
