### ISSUE TITLE
BUG: Docstring typehint for X in numpy.savetxt leads to incorrect code introspection

### ISSUE THREAD

**Issue by medley56** [numpy/numpy#22526]
### Describe the issue:

NOTE: This is a docstring and code introspection issue, NOT a runtime issue.

The docstring for numpy.savetxt X argument leads to false code introspection warnings.
```
X : 1D or 2D array_like
        Data to be saved to a text file.
```
I believe this should be
```
X : np.ndarray
        Data to be saved to a text file.
```

### Reproduce the code example:

```python
import numpy as np

a = np.array([1,2,3])
np.savetxt('file.csv', a, delimiter=',')  # warning: Expected type 'int', got 'ndarray' instead
```

### Error message:

```shell
N/A
```

### NumPy/Python version information:

1.23.4 3.9.15 (main, Oct 11 2022, 22:27:25) 
[Clang 14.0.0 (clang-1400.0.29.102)]

### Context for the issue:

This should be prioritized because it's an extremely easy fix and will remove false warnings experienced by users when using numpy. People _really_ don't like incorrect warning messages.

**Comment by seberg** [comment]
That sounds more like a bug in whatever PyCharm (IIRC) is doing, thinking that something it doesn't understand is an int?

**Comment by rossbar** [comment]
Indeed, this is a problem with whatever tool is inferring types from the parameter description. Note that the suggested update would be less accurate, as something like `np.savetxt("foo.txt", [1])` works just fine (where `[1]` is a list, which is an `array_like` but not an `ndarray`). Note that this is [explicitly typed](https://github.com/numpy/numpy/blob/77728885a04a3178909111e7ce3f96a544b2796c/numpy/lib/npyio.pyi#L184), so I'm not sure why type inference from the parameter descriptions in the docstrings is still being used.

As the issue lives outside of numpy, I will close this.
