### ISSUE TITLE
BUG: median() does not properly cast the result to a uint8 array passed as the `out` kwarg

### ISSUE THREAD

**Issue by paulmueller** [numpy/numpy#22536]
### Describe the issue:

`median()` produces float arrays. If I pass a `np.uint8` array as the `out` kwarg to `median()`, then the result is not always cast correctly. However, the [docs](https://numpy.org/doc/stable/reference/generated/numpy.median.html) state that the output will be cast:

```
out : ndarray, optional

    Alternative output array in which to place the result. It must have the same
    shape and buffer length as the expected output, but the type (of the output)
    will be cast if necessary.
```

This is the output of the code below:
![image](https://user-images.githubusercontent.com/2853022/200144058-acbd0c5d-ea05-415b-8e69-6643b289cb42.png)

The difference between the outcomes is 128 or 128.5, so this issue might have something to do with the confusion of signed and unsigned integers?

### Reproduce the code example:

```python
import numpy as np

input = np.array([
    [153, 157, 156, 152, 150, 158, 151, 157, 151, 151],
    [153, 157, 156, 154, 150, 159, 151, 156, 152, 152]
   ])


out_1 = np.median(input, axis=0)

out_2 = np.zeros(10, dtype=np.uint8)
np.median(input, out=out_2, axis=0)

# Visualization
import matplotlib.pylab as plt
plt.plot(out_1, label="out_1")
plt.plot(out_2, label="out_2")
plt.legend()
plt.show()
```

### NumPy/Python version information:

1.23.0 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]

**Comment by seberg** [comment]
Probably median is using the out array for the last calculation which would cause this. In most places NumPy should be just refusing using an integer output when the rsult is float (which doesn't remove all problems with low precision ints when a result is int).
I suspect we should deprecate/disallow the float to int cast, although the use of `out` could probably be moved around to make the above work.  But in that case, you just lose the memory advantage for the typical float array case.

**Comment by paulmueller** [comment]
For the sake of completeness: This bug affects `np.int8` and `np.uint8`. It does not affect `np.int16` etc.

I would prefer to deprecate the float to int cast, following your reasoning with the memory advantage.

I am now using `np.partition` directly (which `np.median` wraps) for my use case.

**Comment by r3animat0r** [comment]
Hello, 
if the bug is still relevant i would like to try and contribute a solution for this. 
My idea was to either ignore the type of the given output array if necessary or to throw some kind of exception if the type of the given array is not fitting for the result output.

To test if an value is a float and shouldn't be converted to int, `float(value).is_integer()` or `isinstance(array, np.uint8)` could be used. For the Exception maybe a `ValueError` could be thrown.

**Comment by r3animat0r** [comment]
Realized that this seems to be correct behavior and that there should be no warnings or checks for Integer Overflows (which seems to be the case here). Related discussion to this is in #8987

So i think this Issue can be closed.
