### ISSUE TITLE
Tracking issue: moving to Meson as the build system for NumPy

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#22546]
This is the main tracking issue for the move to Meson as our new build system, until we've made it the default in pyproject.toml and things are looking good. For context:

- `distutils` is removed from the stdlib in Python 3.12, and `numpy.distutils` is deprecated because of that. For details, see https://github.com/numpy/numpy/issues/18588
- What we need from a build system and why Meson: basically the same as for SciPy, see https://github.com/scipy/scipy/issues/13615

### Planning work and integration

_This was initially written up in gh-22468:_

- We use a `meson` branch in this repo: https://github.com/numpy/numpy/tree/meson
- CI: 
  - we ensure regular CI does not run on `meson`, by removing regular CI jobs from the `meson` branch in order to not trigger a lot of unnecessary CI runs
  - we start with one new Linux CI job in the `meson` branch, and deal with other platforms and configs once things have started working on Linux
- Branch rules: 
  - for simple changes where the author is fairly sure that the changes are correct, pushing directly to the `meson` branch is fine,
  - for more complex changes, let's work via PRs to ensure that we get at least cursory review early on
  - since it's a branch in the main repo, merging `main` into `meson` is preferred over rebases. @stefanv, @mattip and @rgommers will align in case the `meson` branch needs rebasing or other history rewriting, to ensure that we don't lose anyone's work.
  - we should avoid making code changes other than build/CI/docs in the `meson` branch; if we need fixes in NumPy itself, we should open separate PRs for those, get them merged quickly, and then merge `main` into `meson`
- Once we are ready to merge initial Meson support into `main`, we will make a careful PR with granular commits and co-authorship for folks who contributed to the code in that commit.
- For tracking the work, we will have:
  - This tracking issue
  - A project board with status per topic and assigned dev: https://github.com/orgs/numpy/projects/7.
  - Documentation on how to test/use the build will live in the `meson` branch itself.
  - Writing a NEP may be useful at some point, but I'd like to postpone that.

Here is the project board: https://github.com/orgs/numpy/projects/7/views/7. Self-assigning topic there is useful if you plan to work on something. Please feel free to add new tasks if you're clear on them being needed. Otherwise please feel free to discuss on this issue or on the `#meson` channel in Slack.

### Timeline

This is probably 3-6 months of work. A key topic will be SIMD support, because pretty much everything else is known to work - it's already done in SciPy. Whatever is not done there is tracked in https://github.com/scipy/scipy/issues/16293. The most important topic there is BLAS/LAPACK support; as of right now that works, but isn't as user-friendly as with `numpy.distutils` - more automatic detection is needed, as well as user-level ways to do things like express a preferred ordering of BLAS libraries.

The Meson 0.65.0 release will come out in ~3 months (quarterly release cycle, and 0.64.0 came out today). We should aim to get some of the things we need into that release.

We typically start testing a new CPython development version ~6 months before it is released. For Python 3.12 that would be Mar-Apr 2023.

**Comment by seiko2plus** [comment]
Regarding to the SIMD support, the current unstable meson [SIMD module](https://mesonbuild.com/Simd-module.html) is pretty simple and doesn't fit our needs. Improving the current unstable meson [SIMD module](https://mesonbuild.com/Simd-module.html) is the ideal way but it may take time to be merged since meson doesn't support custom modules, see https://github.com/mesonbuild/meson/issues/5336#issuecomment-600833098

The alternative solution is to refactor distutils/SIMD (CCompilerOpt) in meson script, but I'm afraid it will contain several workarounds

For example, one of the issues that made me mad is there's no single method for specifying custom compiler flags for each source and the current workaround is to use static libs see https://github.com/mesonbuild/meson/issues/1367

**Comment by seiko2plus** [comment]
I started a new discussion for improving the meson SIMD module, see https://github.com/mesonbuild/meson/discussions/11033

**Comment by rgommers** [comment]
Thanks @seiko2plus! I agree with improving in Meson what can go in there. That is more maintainable and reusable than trying to put it all in one `meson.build` file. I think it's okay for that to take one or two Meson release cycles (so 3-6 months); we have at least until the 1.25.0 release branch point (probably May/June 2023) to get things into Meson, and if we don't manage for some reason we can temporarily use a fork of Meson. We're only going to do this build system transition once, so it'd be nice to make the design as good as possible:)

One thing that isn't 100% clear to me yet is which parts of `compiler_opt.py` should go into Meson, and which one we should keep in NumPy. Looking at https://numpy.org/devdocs/reference/simd/how-it-works.html, some topics are clear, some are more fuzzy:
1. Configuration - not sure, depends on whether Meson wants to know about runtime dispatching (cpu-baseline vs. cpu-dispatch, and the dispatching mechanism itself)
2. Discovering the environment - in Meson (including implicit features, caching, etc.)
3. Validating the requested optimizations - in Meson
4. Generating the main configuration header - probably split; Meson already generates things like `HAVE_SSE2` and that can be extended to all architectures we need, but we will have numpy-specific defines as well
5. Dispatch-able sources and configuration statements - not sure, but probably in NumPy or in a separate project (for reusability, ala `xsimd`; also still unsure if anything from xsimd is reusable), because the code comment inside C source files approach is likely too opinionated for a build system.

Maybe we should hash that out a little here, and update the diagram that is in the docs. That will help communicate what we want to do to the Meson devs.

**Comment by rgommers** [comment]
Okay, progress to report: a build without SIMD options passes all tests under `numpy.test()` in the `meson` branch. This took about ~40 hours of work - less than I expected; luckily there were very few problems that I hadn't already seen in SciPy.

Here's a [CI log that is green](https://github.com/numpy/numpy/actions/runs/3456741047/jobs/5769694881), that took 11 min 12 sec in total (Mypy tests not run, those are way too slow). The build takes ~2 min in CI, and 26 sec on my 12-core machine (7 sec for the configure stage, and 19 sec for the build stage - only build stage is shown below):

![image](https://user-images.githubusercontent.com/98330/201542928-86c78c80-4c9f-42d5-86b6-4bdaa82431f8.png)

I'm sure there are still bugs and missing pieces, both known (e.g., SVML and ILP64 support) and unknown. It's at a stage where it should be usable for development work on NumPy itself for early adopters though. And help is very welcome of course. One thing in particular I don't plan on touching any time soon is Windows support, because I don't have a machine for that. I did migrate Windows-specific build flags etc., but it's unlikely to work out of the box. If someone wants to try, that'd be really helpful.

**Comment by charris** [comment]
It currently takes 2 minutes on my 10 year old i4 using `python setup.py build -j4'. A 4x improvement will be nice.

Reminds me that back around 2000 there was a mini contest to compile the Linux kernel in the shortest time. IIRC, some big IBM machine blew away the competition, building the kernel in some 7 seconds :)

**Comment by eli-schwartz** [comment]
Yup, we are in general interested in improvements to Meson's SIMD support and as I mentioned in the linked discussion, you even have a bit of a clean slate to work with. :)

(Also, following this ticket to keep an eye on where you're all holding -- please let me know what you need and what I can help with.)

**Comment by seiko2plus** [comment]
@rgommers,
> Configuration - not sure, depends on whether Meson wants to know about runtime dispatching (cpu-baseline vs. cpu-dispatch, and the dispatching mechanism itself)

Differentiating between baseline and dispatched features matters to reduce the amount of generated objects and may also improve the performance when the user increases the ceiling of baseline features. we can change the term baseline to "static dispatching" and the term `dispatched-features` to "dynamic dispatching" to make it clear.

The dispatching mechanism itself should be fully implemented within the simd module except for the part it relates to runtime detection.

>  Discovering the environment - in Meson (including implicit features, caching, etc.) Generating the main configuration header - probably split; Meson already generates things like HAVE_SSE2 and that can be extended to all architectures we need, but we will have numpy-specific defines as well

Implicit features aren't supported by meson, but almost everything else is kind of supported but requires extra enhancement so we can deal with a massive amount of CPU features.

> Dispatch-able sources and configuration statements - not sure, but probably in NumPy or in a separate project (for reusability, ala xsimd; also still unsure if anything from xsimd is reusable), because the code comment inside C source files approach is likely too opinionated for a build system.

We still want the dispatchable sources, they aren't limited to certain API designs. However, configuration statements are no longer needed, we can specify the targets through the module method, also there's no need to classify them anymore ".dispatch.c".

> Maybe we should hash that out a little here, and update the diagram that is in the docs. That will help communicate what we want to do to the Meson devs.

Totally agree.

**Comment by rgommers** [comment]
I'm mostly done with implementing the SSE/AVX checks from `numpy/core/setup_common.py` into `numpy/core/meson.build` (a few TODO's, but nothing that can't be done). So I thought this would be a good time to take the [current diagram](https://numpy.org/devdocs/reference/simd/how-it-works.html) and annotate it:

![NumPy_CPU_dispatcher](https://user-images.githubusercontent.com/98330/203097291-f0fc6c90-6b51-4bda-b7f1-59d7b08da6e0.png)

The main interesting part is the "fetch dispatch-able sources" + "handling". That needs detailing out.

> The dispatching mechanism itself should be fully implemented within the simd module except for the part it relates to runtime detection.

To clarify, is the _simd module_ here is `numpy/core/src/_simd` or the Meson SIMD module? I think you meant the former, but I'm not quite sure. Runtime detection is `numpy/core/src/common/npy_cpu_features.c.src` and `numpy/core/src/common/npy_cpu_features.h`, see for example gh-13421. So both of these parts would be in NumPy.

**Comment by rgommers** [comment]
Support for building Meson - minus Windows and SIMD support - is now present in `main` (see gh-22663). Those features can be worked on in the `meson` branch, which is up to date with `main`.

**Comment by mattip** [comment]
I have started with windows. So far I have

<details><summary>some minor fixes</summary>

```diff
diff --git a/building_with_meson.md b/building_with_meson.md
index dd1ca1d94..f9cbd003b 100644
--- a/building_with_meson.md
+++ b/building_with_meson.md
@@ -9,8 +9,14 @@ ### Developer build

 **Install build tools:** Use one of:

-- `mamba create -f environment.yml
-- `pip install -r build_requirements.txt  # also make sure you have pkg-config and the usual system dependencies for NumPy`
+- `mamba env create -f environment.yml && mamba activate numpy-dev
+
+- `python -m pip install -r build_requirements.txt
+  # also make sure you have pkg-config and the usual system dependencies for
+  # NumPy`
+
+Then install devpy:
+- `python -m pip install git+https://github.com/scientific-python/devpy`

 **Compile and install:** `./dev.py build`

diff --git a/environment.yml b/environment.yml
index 8dbb1f80d..37c94e7f1 100644
--- a/environment.yml
+++ b/environment.yml
@@ -15,8 +15,9 @@ dependencies:
   - setuptools=59.2.0
   - meson >= 0.64.0
   - ninja
-  - pkg-config  # note: not available on Windows, comment out this line
+  - pkg-config
   - meson-python
+  - pip   # so you can use pip to install devpy
   # For testing
   - pytest
   - pytest-cov
```

</details>

Then the meson setup runs, and uses MSVC, and fails with incompatibilities with complex numbers. The meson check for `complex double` uses this stanza
```
 #include <complex.h>
        void bar(void) {
            sizeof(complex double);
        }
```

On windows, that needs to be
```
 #include <complex.h>
        void bar(void) {
            sizeof(_Dcomplex);
        }

```

Is there a different way to tell meson "yes, I have `complex v` and its size is `sizeof(v) * 2` for v in float, double, long double ?

**Comment by rgommers** [comment]
Thanks for working on that Matti. 

> `pip   # so you can use pip to install devpy`

`pip` is always pulled in when `python` is installed, so that should not be needed. The other minor fixes LGTM, go ahead and push them to the `meson` branch I'd say.

> Is there a different way to tell meson "yes, I have `complex v` and its size is `sizeof(v) * 2` for v in float, double, long double ?

Every type is checked. In this case, `complex_types_to_check` in `core/meson.build` should yield NO for `complex double` & co. (right?). The logic to tweak is this block:
```meson
  foreach symbol_type: complex_types_to_check
    if cc.has_type(symbol_type[2], prefix: '#include <complex.h>')
      cdata.set10(symbol_type[0], true)
      # Determine size of NumPy's own, struct-based, complex types. Binary
      # compatibility with C99 complex types is checked at build time in `npy_common.h`.
      ftype = symbol_type[3]
      cdata.set(symbol_type[1], cc.sizeof(f'struct {@ftype@ __x; @ftype@ __y;}'))
    endif
  endforeach
```

What seems to be needed is that if `cc.has_type(complex double)` is false, then set the required `HAVE_xxx` definitions that are needed for MSVC (compare with the generated `config.h` and `_numpyconfig.h` from a `setup.py` build).

**Comment by mattip** [comment]
Got it. Getting closer: after 5886138349ba4dd05f90ccff1acc66d0076a4209 now compilation with msvc gets to linking, and fails with
```
meson-generated_numpy_random__common.pyx.c.obj : 
    error LNK2019: unresolved external symbol _npy_signbit_ld referenced in function __pyx_f_5numpy_6random_7_common_check_constraint
numpy\random\_common.cp39-win_amd64.pyd : 
    fatal error LNK1120: 1 unresolved externals
```

Clearly more to do, but making progress.

**Comment by mattip** [comment]
On latest meson HEAD, `python dev.py build` on windows works. I could not run `test`, I get this:
```
(numpy-dev) C:\oss\numpy>python dev.py test
No `site-packages` directory found under build; aborting
```

I have `<base>\build-install\usr\Lib\site-packages`. Is something wrong with the test command?

**Comment by stefanv** [comment]
There's no Python version in the path under Windows? How do you know which Python version it's installed to then? I can fix this specific problem, though, it just won't install multiple Python versions.

**Comment by seiko2plus** [comment]
@rgommers,

> To clarify, is the simd module here is numpy/core/src/_simd or the Meson SIMD module? 
Yes, the meson module; `_simd` is only exist for testing universal intrinsics at the runtime.


> Runtime detection is numpy/core/src/common/npy_cpu_features.c.src and numpy/core/src/common/npy_cpu_features.h, see for example https://github.com/numpy/numpy/pull/13421. So both of these parts would be in NumPy.

Exactly, moving them to meson would still be possible in case if the meson project sees the necessity to provide a runtime library
for the end users. In general, the meson SIMD module is not going to include any runtime functions, just helpers for the final process.

> The main interesting part is the "fetch dispatch-able sources" + "handling". That needs detailing out.

Here is a pseudo-code for the whole cycle it assumes that the meson SIMD module is
fully functional and has everything we need:

```Python
simd_mod = import('simd')
```
 Fetch the supported features and CPU groups
```Python
simd_features = simd_mod.cpu_features(compiler: cc)
```
Append, update, or even removes certain features or group of features
```Python
if not simd_features.has('yyy')
    simd_features.add(
        'yyy', implies : 'xxx',
        args : ['-mzzz', '-mhhh'],
        'test_path' : 'test/path',
        extra_tests : {
            'DEF_NAME' : 'test/path'
        }
    )
endif
if simd_features.has('xxx')
    simd_features.update(
        'xxx', extra_tests : {
            'DEF_NAME' : 'test/path'
        }
    )
endif
```
Test requested optimizations against the compiler based on the user args and return a new instance
that provides the core methods of both static and dynamic dispatching according to the supported CPU features.
```Python
simd = simd_mod.instance(
    get_option('cpu-baseline'), get_option('cpu-dispatch'),
    features : simd_features,
    # Default values of preprocessor #definitions; modifiable by
    # methods `configure_file` and `target` for convenience reasons; see below.
    prefix: 'NPY_',
    numeric: false,
    # may add extra useful options, e.g. specify the value of
    # `min` keyword or `max`, maybe filtration
)
```
Bring the main config file and compiler flags required for
static dispatching that should be applied to all sources.
```Python
# Generates #defenctions of the CPU features
simd_config = simd.configure_file(
  output: 'path/to/npy_cpu_dispatch.h',
  prefix: 'NPY_',
  # If true, then generate definitions with the value 0 for all supported features
  # except baseline features set them to 1
  # if false, then generate definitions for baseline features only
  # similar to what we have now
  numeric: false,
  # we may add different options to make other projects happy,
  # such as allow generating constexpr variables instead.
)
# minmum flags
baseline_flags = simd.baseline_args()
```
Dynamic dispatching or handling the dispatchable sources
```Python
umath_dispatches = {
    'target_x' : simd.target(
        # similar to what `@targets` provides
        [
            'baseline', 'sse41', ['avx2', 'fma3'],
            'avx512_common', 'neon', 'asimd',
            'vsx3'
        ],
        # Dispatchable-sources that shares the same targets
        # No need for mark it with `.dispatch.c*` any more.
        [
            'src/math_functions_0.c',
            'src/math_functions_1.c'
        ],
        # similar to simd.configure_file but for the features of each target above.
        prefix: 'NPY_',
        numeric: false,
        # extra options e.g. keep_baseline, keep_order
    ),
    'target_y' : simd.target(
        [
            'baseline', 'sse42', 'avx',
            'avx512_skx', 'neon', 'asimd',
            'svml', 'vsx3', 'vxe'
        ],
        [
            'src/math_functions_2.c',
            'src/math_functions_3.c'
        ]
    )
}
```

Generate and gather config for each target. It must be in a separate step in case there are any
dependencies between the dispatchable sources.
```Python
umath_dispatch_config = []
foreach name, target : umath_dispatches
    # similar to simd.configure_file but for the
    # each compiled target, required by the final runtime
    # call.
    umath_dispatch_config += target.configure_file(
        output: 'path/to/' + name + '.dispatch.h',
        prefix: 'NPY_',
        numeric: false
    )
endforeach
```

build and retrieve the objects, scenario A:
```Python
umath_dispatch_objects = []
foreach name, target : umath_dispatches
    umath_dispatch_objects += target.build(
        umath_config + umath_dispatch_config,
        c_args : c_args_common + baseline_args,
        include_directories: umath_includes,
        # ...
    )
endforeach
```
build and retrieve the objects, scenario B:
```Python
foreach name, target : umath_dispatches:
    umath_dispatch_objects += static_library(
        name, target.sources(),
        c_args : c_args_common + target.args()
    )
endforeach
```

**Comment by mattip** [comment]
FWIW, testing (after building with meson) runs on windows when I do
```
set PYTHONPATH=<prefix>\build-install\usr\Lib\site-packages
cd build-install
python -c "import numpy; numpy.test()"
```

but segfaults in `numpy.random.tests.test_random.py` inside `test_multinomal`. I am debugging it, seems to be a memory problem when freeing 240,000 bytes.

**Comment by jdstraye** [comment]
What is the ETA for rev 1.25.0 on Windows, and is there a workaround for Python 3.12 in the meantime?

**Comment by mattip** [comment]
Based on tradition, 1.25.0 will be released  in June, with a follow up bug fix 1.25.1 in early July. This is ahead of the first Python3.12 release candidate, which should happen around July 31. If you want to help you can try out the meson branch and help debug the problems there.

**Comment by mattip** [comment]
Following a suggestion from @rgommers, I built twice: once with meson and once with `setup.py` to try to compare the compile flags. In the `build.log` created from the `runtests.py` workflow (which uses `setup.py`), I see this pattern:
```
cl.exe /c /nologo /Od /W3 /GL /DNDEBUG /MD /Zi -I<lots of includes> \
    /Tcsrc.c /Fobuild\temp.win-amd64-3.8\src.obj /GL- -d2VolatileMetadata-
```

and in the `build/build.ninja` file in the section for the same file I see:
```
ARGS = "-I<fewer includes>" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" \
    "/O2" "/Zi" "-d2VolatileMetadata-" "/Fdsrc.c.pdb"
```

So there is a difference:
- `/Od` ([disable optimization](https://learn.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=msvc-160) vs. `/O2` (maximum speed)
- meson does not set `/DNDEBUG`

How does one go about overriding the default meson build flags?

**Comment by eli-schwartz** [comment]
Check out the "optimization" and "b_ndebug" options (and as usual, you can set them in the project default_options).

**Comment by rgommers** [comment]
Awesome! Next step I think is a PR to `main` with needed fixes to `meson.build` files. And ideally a CI job to go with it (either like https://github.com/scipy/scipy/blob/main/.github/workflows/windows.yml, or a slightly simpler flavor which just uses `pip install .` - whatever seems best).

**Comment by mattip** [comment]
I don't understand how the OpenBLAS integration works currently in the linux build. Where does the CI call python tools/openblas_support.py and how does meson use that?

**Comment by rgommers** [comment]
There is no such thing as calling `openblas_support.py` in any of the Meson builds aside from the Windows one. And even for Windows it can only be optional. It's a hack that is needed only if there's no other way to get OpenBLAS installed. For the CI job it's fine though, just parallel to what the SciPy CI job does.

In general, BLAS/LAPACK is configurable via a CLI switch (see `meson_options.txt` in the root of the repo). And then Meson will look for the specified library (OpenBLAS by default) with `pkg-config` and then as a fallback with CMake. Maybe easier to iterate on Slack or jump on a quick call if this raises more questions than answers.

**Comment by rgommers** [comment]
Yes, should work.

**Comment by seiko2plus** [comment]
I have almost implemented the main functions of `distutils.CompilerOpt` that are related to the CPU features in a separate meson module called 'feature',  rather than having one module for CPU features and dispatchable sources. [pr-11307](https://github.com/mesonbuild/meson/pull/11307)

The new module should made it pretty easy to implement any kind of compiler/CPU feature, also it will provide almost all CPU features by default.

For example:
```Meson
project('test', 'c')

feature = import('feature')
cpu_features = feature.cpu_features()

targets = [['AVX2_FMA3', [cpu_features['AVX2'], cpu_features['FMA3']]],
          ['AVX512_COMMON', cpu_features['AVX512_COMMON']],
          ['AVX512_SKX', cpu_features['AVX512_SKX']]]

foreach target : targets
  t = feature.test(target[1])
  if t[0]
    message('target name:', target[0])
    data = t[1]
    message('Implicit features:', data['implicit'])
    message('Compiler arguments:', data['args'])
    message('Headers:', data['headers'])
    message('Need to detect on runtime:', data['detect'])
    message('Supported #definitions:', data['defines'])
    message('Unsupported #definitions:', data['undefines'])
    message('Compiler support this target by ', data['support'])
    message('========================================')
  endif
endforeach
```
<details>
<summary>stdout</summary>

```Bash
Project name: test
Project version: undefined
C compiler for the host machine: cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Test feature "FMA3" : Supported (cached)
Test feature "AVX2" : Supported (cached)
Message: target name: AVX2_FMA3
Message: Implicit features: ['SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C']
Message: Compiler arguments: ['-msse', '-msse2', '-msse3', '-mssse3', '-msse4.1', '-mpopcnt', '-msse4.2', '-mavx', '-mf16c', '-mfma', '-mavx2']
Message: Headers: ['xmmintrin.h', 'emmintrin.h', 'pmmintrin.h', 'tmmintrin.h', 'smmintrin.h', 'popcntintrin.h', 'immintrin.h']
Message: Need to detect on runtime: ['F16C', 'AVX2']
Message: Supported #definitions: ['SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2']
Message: Unsupported #definitions: []
Message: Compiler support this target by  ['ARG', 'FILE']
Message: ========================================
Test feature "AVX512_COMMON" : Supported (cached)
Message: target name: AVX512_COMMON
Message: Implicit features: ['SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2']
Message: Compiler arguments: ['-msse', '-msse2', '-msse3', '-mssse3', '-msse4.1', '-mpopcnt', '-msse4.2', '-mavx', '-mf16c', '-mfma', '-mavx2', '-mavx512f', '-mavx512cd']
Message: Headers: ['xmmintrin.h', 'emmintrin.h', 'pmmintrin.h', 'tmmintrin.h', 'smmintrin.h', 'popcntintrin.h', 'immintrin.h']
Message: Need to detect on runtime: ['AVX512F', 'AVX512CD']
Message: Supported #definitions: ['SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512_COMMON', 'AVX512F', 'AVX512CD', 'AVX512F_REDUCE']
Message: Unsupported #definitions: []
Message: Compiler support this target by  ['ARG', 'FILE']
Message: ========================================
Test feature "AVX512_SKX" : Supported (cached)
Message: target name: AVX512_SKX
Message: Implicit features: ['SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512_COMMON']
Message: Compiler arguments: ['-msse', '-msse2', '-msse3', '-mssse3', '-msse4.1', '-mpopcnt', '-msse4.2', '-mavx', '-mf16c', '-mfma', '-mavx2', '-mavx512f', '-mavx512cd', '-mavx512vl', '-mavx512bw', '-mavx512dq']
Message: Headers: ['xmmintrin.h', 'emmintrin.h', 'pmmintrin.h', 'tmmintrin.h', 'smmintrin.h', 'popcntintrin.h', 'immintrin.h']
Message: Need to detect on runtime: ['AVX512F', 'AVX512CD', 'AVX512VL', 'AVX512BW', 'AVX512DQ']
Message: Supported #definitions: ['SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512_COMMON', 'AVX512F', 'AVX512CD', 'AVX512F_REDUCE', 'AVX512_SKX', 'AVX512VL', 'AVX512BW', 'AVX512DQ', 'AVX512BW_MASK', 'AVX512DQ_MASK']
Message: Unsupported #definitions: []
Message: Compiler support this target by  ['ARG', 'FILE']
Message: ========================================
Build targets in project: 0
```
</details>

**Comment by mattip** [comment]
I am working on #23027 that both enables windows and tries to deal with configuring OpenBLAS via the openblas.pc pkgconfig files in the tarball/zipfile.

**Comment by rgommers** [comment]
@seiko2plus that looks very nice and concise! Will try it out later this week.

**Comment by mattip** [comment]
I think the meson builds should be using [`b_ndebug`](https://mesonbuild.com/Builtin-options.html#base-options) so that `assert()` in C is a NOP. This is added in the old build system since the sysconfig CFLAGS used to build python are merged with the build-defined CFLAGS, and `-DNDEBUG` will appear in the sysconfig CFLAGS for a release build.

**Comment by rgommers** [comment]
@mattip is that also true for debug builds? It seems quite strange to hardcode a flag saying "no-debug" for a debug build. Or did you mean setting the default to `if-release` rather than `true`?

**Comment by mattip** [comment]
> Or did you mean setting the default to if-release rather than true?

+1. I wonder why meson does not do this by default. [CMake does](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Compiler/GNU.cmake#L59), setuptools/distutils does, [qmake does](https://doc.qt.io/qt-6/qmake-variable-reference.html#defines-release) (at least for msvc).

**Comment by rgommers** [comment]
I suspect because it's very much valid to ship `assert`'s - they're never supposed to be encountered in running code, and if that happens it may cause undefined behavior. It''s like `python` vs. `python -OO`. The latter strips `assert` statements for size reasons only. If we actually need this flag to be set, it indicates a bug somewhere that needs addressing. Meson's default seems fine to me.

**Comment by mattip** [comment]
Hmm. Are there open issues to change this default on the other build systems? Otherwise I think it would be better if meson conforms to expected convention and define NDEBUG for release builds. There is a reason to not call asserts on release: they will terminate the process with no further error message or try to open a debugger. If developers wish to leave them live on release code they should be refactored into proper errors.

**Comment by seberg** [comment]
> they're never supposed to be encountered in running code

We have some relatively expensive asserts in fairly hot paths, unless someone wants to review asserts systematically we have to ship without them.  They should not be triggered, but executing the assert statement can be slow.

I rather liked the fact that it used to "inherit" from python, auto-switched to using debug when running with debug python, but it is a relatively niche thing.

**Comment by rgommers** [comment]
Okay, let's change to `if-release` as the default then.

I'll note that there is no "expected convention", `autoconf` does the same as Meson, CMake does the opposite, MSVC recommends another form of debugging than plain C `assert`'s.

> I rather liked the fact that it used to "inherit" from python, auto-switched to using debug when running with debug python, but it is a relatively niche thing.

This is https://github.com/mesonbuild/meson-python/issues/207.

**Comment by mattip** [comment]
autoconf is in a different class from build tools like CMake, setuptools, QMake. Projects like python which use configure/autoconf will work around this by having [reasonable defaults](https://docs.python.org/3/using/configure.html?highlight=ndebug#python-debug-build) to define `NEDBUG`. Older projects like perl will have [project-specific ways](https://github.com/Perl/perl5/blob/fc11df3e7c474d125032d885d145d03146621204/perl.h#L4186) to define it for non-debug builds. As for MSVC: I could not find any specific guidance for it, were you referring to `_DEBUG` which does something very different? I would hope meson wishes to be identified with the newer tools, and not to base itself on autoconf's known user-unfriendly defaults. 

Not defining `NDEBUG` is a UX problem. People migrating from setptools to meson will expect `NDEBUG` to be defined.  At the least this should be part of a migration guide, or meson-python/devpy/cookie-cutter which build on top of meson should set it as a default.

**Comment by rgommers** [comment]
> Not defining `NDEBUG` is a UX problem. People migrating from setptools to meson will expect `NDEBUG` to be defined. At the least this should be part of a migration guide, or meson-python/devpy/cookie-cutter which build on top of meson should set it as a default.

I don't know enough about expectations of different types of users here. I suspect there are reasons for not doing this in Meson; it may make sense in meson-python. @eli-schwartz could I ask you for a recommendation here?

**Comment by eli-schwartz** [comment]
Doing a bit of archaeology...

mesonbuild/meson@f1b6c89d9ca54831b753c7a4fa76d3e0980f8fd3 added the b_ndebug option, as a boolean, in September 2016.

mesonbuild/meson@d232a80e90a9bd4e7c677c695a9c230ac1ec8361 added the if-release value in December 2017, one year and ten versions later, and it left the default in place. Checking out the PR discussion, we find that at the time, there was discussion about whether to default to if-release. This was rejected on the grounds that:
- distros will be unhappy
- projects will break
- distros will be unhappy because projects start breaking

And the reason that projects break is because... GNOME! The gnome ecosystem has the heavily used concept of runtime type checks that you may or may not choose to disable, but if you do then the gnome developers get... not precisely *mad*, but loudly skeptical that your system will be stable. But then again, for portability reasons they also define a `g_free()` wrapper around `free()` which is guaranteed to be safe to use on NULL pointers. After all, there's a pre-ANSI compiler that dumps core!

This is of course tied to the ndebug option, or at least... used to be, in some cases. These days I think they've all moved over to custom options.

There were also general concerns that other projects do exciting things with ndebug as well, such as using it for detecting and reporting ordinary error conditions, plus:
> I recall that when CMake added ndebug by default it raised a big uproar in distro package builders.

I would like to think that projects themselves will better handle that these days. There's a reason Meson makes these options individually toggle'able.

More generally, I ***absolutely*** believe this (`b_ndebug=if-release`) is an appropriate thing for people to put in default_options or as part of a cookiecutter template, because, well... it may be debatable whether that should be the default (but it's worth chipping in here): https://github.com/mesonbuild/meson/issues/2566

But it's not debatable that projects *should* be NDEBUG-safe, which in turn means that when starting a project this is a good default to set up at the project level.

**Comment by rgommers** [comment]
I think we're all good here. The decision was made; we made the switch in `main` to Meson quite a while ago; we have nightlies for Python 3.12 (and other versions) published; there's PRs for SIMD under review; and the other issues discussed here were all resolved. See gh-23981 for the final loose ends.

Thanks everyone!

**Comment by stefanv** [comment]
Thanks, Ralf, for coordinating this transition!
