### ISSUE TITLE
BUG: numpy.random.Generator.dirichlet should accept zeros.

### ISSUE THREAD

**Issue by WayneHajas** [numpy/numpy#22547]
### Describe the issue:

numpy.random.mtrand.RandomState.dirichlet no longer accepts alpha(count)-values that are zero.

With older (e.g. 1.11.3) versions of numpy, dirichlet accepted zero as an alpha(count) value.

>>> numpy.__version__
'1.11.3'
>>> dirichlet([5,9,0,8])
array([ 0.17970351,  0.35902845,  0.        ,  0.46126803])
>>> dirichlet([5,9,0,8])
array([ 0.15228294,  0.45822224,  0.        ,  0.38949482])

With newer (e.g. 1.21.5) versions of numpy, alpha(count) values must be greater than zero.  Very small real-values are accepted.
>>> numpy.__version__
'1.21.5'
>>> dirichlet([5,9,0.000001,8])
array([0.38285451, 0.26206592, 0.        , 0.35507958])
>>> dirichlet([5,9,0,8])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4390, in numpy.random.mtrand.RandomState.dirichlet
ValueError: alpha <= 0

I have some applications where alpha(count|)-values are raw-data and zero is a very valid value.  These applications worked with old versions of numpy but not with newer versions.

### Reproduce the code example:

```python
dirichlet([5,9,0,8])
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4390, in numpy.random.mtrand.RandomState.dirichlet
ValueError: alpha <= 0
```

### NumPy/Python version information:

1.21.5

### Context for the issue:

I have some applications where alpha(count|)-values are raw-data and zero is a very valid value.  These applications worked with old versions of numpy but not with newer versions.

**Comment by rkern** [comment]
This was implemented in #9577. That PR description claims that it hangs when the values are 0, but I don't see how that can be the case as `standard_gamma()` has had special cases for `shape == 0`. It did appear to hang when the values were very, very low but nonzero because of the unprotected loop in that case. I suspect the main reason `alpha[i] == 0` was excluded because Wikipedia entry claims that `alpha[i] > 0` is required, but that is often dodgy.

I think we could make `Generator.dirichlet()` accept `alpha[i] == 0` (though not `RandomState`, per NEP 19).

**Comment by MatteoRaso** [comment]
I think it might actually be important for alpha[i] to be greater than 0. The PDF of the distribution is inversely proportional to B(alpha), which is the product of all gamma(alpha[i]) divided by the gamma of the sum of alpha. If alpha[i] is 0, then gamma(alpha[i]) is inf, which breaks everything.

**Comment by pcralmeida** [comment]
Hello! I would like to work on this issue. From my understanding, accepting `alpha[i] == 0` would suffice, open to sugestions though.

**Comment by WarrenWeckesser** [comment]
The `dirichlet` method of the `Generator` class now allows elements of `alpha` to be zero (see https://github.com/numpy/numpy/pull/23440 and the follow-up https://github.com/numpy/numpy/pull/24220):

```
In [4]: np.__version__
Out[4]: '2.0.0.dev0+git20230813.104addf'

In [5]: rng = np.random.default_rng()

In [6]: rng.dirichlet([5, 9, 0, 8])
Out[6]: array([0.22294196, 0.51402094, 0.        , 0.26303709])

In [7]: rng.dirichlet([5, 9, 0, 8], size=8)
Out[7]: 
array([[0.31371971, 0.31066775, 0.        , 0.37561255],
       [0.25549883, 0.52689855, 0.        , 0.21760262],
       [0.15567579, 0.40443253, 0.        , 0.43989168],
       [0.18513736, 0.55825023, 0.        , 0.25661241],
       [0.25517287, 0.40680073, 0.        , 0.3380264 ],
       [0.29160739, 0.43306643, 0.        , 0.27532618],
       [0.23052236, 0.3841242 , 0.        , 0.38535344],
       [0.18530714, 0.49334535, 0.        , 0.32134751]])

```
Per NEP 19, the `RandomState.dirichlet` (aka `np.random.dirichlet`) won't be updated, so I'm closing this issue.
