### ISSUE TITLE
BUG: Changing element of deepcopy of masked array alters element of original array

### ISSUE THREAD

**Issue by ogliver** [numpy/numpy#22556]
### Describe the issue:

Altering an element of a deepcopy of a masked array alters the element of the original array.

### Reproduce the code example:

```python
import copy
import numpy as np

source = np.ma.array( [ 0,[0,1,2] ] ,dtype=object)
deepcopy = copy.deepcopy(source)

print()
print('Before altering deepcopy:')
print(f'source:   {source}')
print(f'deepcopy: {deepcopy}')

deepcopy[1].append('this should not appear in source')

print()
print('After altering deepcopy:')
print(f'source:   {source}')
print(f'deepcopy: {deepcopy}')

# output:

# Before altering deepcopy:
# source:   [0 list([0, 1, 2])]
# deepcopy: [0 list([0, 1, 2])]

# After altering deepcopy:
# source:   [0 list([0, 1, 2, 'this should not appear in source'])]
# deepcopy: [0 list([0, 1, 2, 'this should not appear in source'])]
```

### NumPy/Python version information:

import sys, numpy; print(numpy.__version__, sys.version)
1.23.3 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]

**Comment by rgommers** [comment]
Thanks for the report @ogliver. At first sight that does look like a real bug. `deepcopy` is supposed to also copy the objects being referenced by the pointers inside the object array.

This looks related to gh-21022, it'd be good to look into both issues together.

**Comment by ayanagrawal2001** [comment]
I'd like to take up this issue along with trying to fix gh-21022 as well. Is that okay?

**Comment by ayanagrawal2001** [comment]
Hi, I would like to look into this as well as the second bug mentioned above

**Comment by LuYunChi** [comment]
> I'd like to take up this issue along with trying to fix [gh-21022](https://github.com/numpy/numpy/issues/21022) as well. Is that okay?

Hi, I have started working on it a few days ago (though haven't progressed too much). Do you want to claim it, or let me continue to work on it?

**Comment by ayanagrawal2001** [comment]
Hey,

Thank you for reaching out. I would like to claim this bug and hope this is
alright with you, since you aren't too far in the process.

I would really appreciate it if you could also share with me any useful
information you might have gathered regarding the bug and also potential
solutions you have considered. This would be of great help to me.

Thanks again.

Best regards,
Ayan

**Comment by LuYunChi** [comment]
OK, it is left to you. I would say, the cause seems to be from `np.array()` whose parameter `copy` is not handled properly. By my understanding, correction should de done either in `core/multiarray.py` as an indirection, or better modify low level C codes.
