### ISSUE TITLE
BUG: np.reshape has no effect in certain cases

### ISSUE THREAD

**Issue by IlayMenahem** [numpy/numpy#22564]
### Describe the issue:

ndarray.reshape has no effect after printing shape in the code example on arr; arr shape stays (3,2,2) before and after the reshape.

os - macos ventura 13.0
python - 3.10.6

### Reproduce the code example:

```python
import numpy as np

arr = np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
print(arr.shape)
arr.reshape((2,6))
print(arr.shape)
```

### NumPy/Python version information:

1.23.4 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]

### Context for the issue:

this bug isn't of high priority since if you don't print shape everything works fine

**Comment by mattip** [comment]
arr.reshape is not an in-place operation: it returns a new ndarray object with the desired shape. The original is not changed. 
```python
>>>arr = np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
>>> print(arr.shape)
(3, 2, 2)
>>> arr2 = arr.reshape((2,6))
>>> print(f"{arr.shape=}")
arr.shape=(3, 2, 2)
>>> print(f"{arr2.shape=}")
arr2.shape=(2, 6)
>>> print(arr2.base is arr)
True

```
