### ISSUE TITLE
BUG: `numpy.percentile` with `inverted_cdf` method (maybe?) returns an incorrect result

### ISSUE THREAD

**Issue by maksymar** [numpy/numpy#22582]
### Describe the issue:

I am looking for the nearest-rank method implementation ([wiki](https://en.wikipedia.org/wiki/Percentile#The_nearest-rank_method)) in `numpy.percentile`, but there are none. The method that produced the closest results is an `inverted_cdf`, but there are some strange discrepancies.

My simple example is an array of 100 increasing numbers from 0 to 99. Obviously `nearest-rank` percentiles would result an array of linearly growing numbers as well. With the exception of p=0 and p=1 both that return the same result, which is the minimum element in the array.

Unexpectedly `inverted_cdf` returns not exactly linear result for percentile values of 7, 14, 28, 55, 56.
Below you can see an example for p=7:
```
[... 5, 6, 7, 8, 9, ...] - input percentile values
[... 4, 5, 6, 7, 8, ...] - expected result
           ?
[... 4, 5, 7, 7, 8, ...] - actual result
```

I would like to know if that's because...
1. I misunderstood `inverted_cdf` method and it should not be equal to `nearest-rank` or
2. `inverted_cdf` indeed calculates a wrong result.

### Reproduce the code example:

```python
import numpy as np

method='inverted_cdf'

def nearest_rank_percentile(arr, p):
    # Nearest rank method, see https://en.wikipedia.org/wiki/Percentile#The_nearest-rank_method
    ceil_div = lambda a, b: a // b + (0 if a % b == 0 else 1)
    ordinal_rank = ceil_div(p * len(arr), 100)
    i = max(0, ordinal_rank-1)
    return sorted(arr)[i]

def verify(arr, p):
    r1 = np.percentile(arr, p, method=method)
    r2 = nearest_rank_percentile(arr, p)
    if r1 == r2:
        print(f'[ OK ] p={p} result {r1}')
    else:
        print(f'[FAIL] p={p} result {r1}!={r2}')

arr = list(range(0, 100))
# Iterate over percentiles in the range of [0, 100].
for p in range(0, 101):
    verify(arr, p)
```

### Error message:

```shell
Output:

[ OK ] p=0 result 0
[ OK ] p=1 result 0
[ OK ] p=2 result 1
...
[ OK ] p=5 result 4
[ OK ] p=6 result 5
[FAIL] p=7 result 7!=6
[ OK ] p=8 result 7
[ OK ] p=9 result 8
...
[ OK ] p=12 result 11
[ OK ] p=13 result 12
[FAIL] p=14 result 14!=13
[ OK ] p=15 result 14
[ OK ] p=16 result 15
...
[ OK ] p=26 result 25
[ OK ] p=27 result 26
[FAIL] p=28 result 28!=27
[ OK ] p=29 result 28
[ OK ] p=30 result 29
...
[ OK ] p=53 result 52
[ OK ] p=54 result 53
[FAIL] p=55 result 55!=54
[FAIL] p=56 result 56!=55
[ OK ] p=57 result 56
[ OK ] p=58 result 57
...
```

### NumPy/Python version information:

```
sys version: 3.9.6 (default, Aug  5 2022, 15:21:02) 
[Clang 14.0.0 (clang-1400.0.29.102)]

numpy version: 1.23.3
```

**Comment by seberg** [comment]
You are simply seeing the limits of floating point precision.  If you have exactly 100 items or so maybe it is better to use `searchsorted` directly.
Yes, percentile goes via quantile, but I doubt there is much to salvange/improve here on first sight.

**Comment by maksymar** [comment]
> You are simply seeing the limits of floating point precision. If you have exactly 100 items or so maybe it is better to use `searchsorted` directly.

I first encountered this issue on an array of some other random size. Switched to 100-elements example for simplicity.

> Yes, percentile goes via quantile, but I doubt there is much to salvange/improve here on first sight.

If the implementation of `nearest-rank` is supposed to return the same result as `inverted_cdf` but without floating point precision issues, then I guess it'd be a solution to switch to this implementation. What do you think?

**Comment by seberg** [comment]
@maksymar to me it seems floating point inaccuracies are basically bound to happen.  Unless you happen to work with integer values and exact multiples of 100.

So I doubt that "switching to this implementation" is a viable option (happy if you/someone investigates it though).

**Comment by maksymar** [comment]
@seberg thank you! 

I missed that `np.percentile` can take input `p` as a floating point (which nearest rank in my example can't).
For my case of 100 integers it would be noticeable, but for floating point numbers it'd be only a border case.

```py
import numpy as np

arr = range(0, 100)
p = 11.00
while p <= 16.25:
    y = np.percentile(arr, p, method='inverted_cdf')
    print(f'p={p:0.2f} y={y}')
    p += 0.25
```

output:
```
p=11.00 y=10

p=11.25 y=11
p=11.50 y=11
p=11.75 y=11
p=12.00 y=11 <- round number

p=12.25 y=12
p=12.50 y=12
p=12.75 y=12
p=13.00 y=12 <- round number

p=13.25 y=13
p=13.50 y=13
p=13.75 y=13

p=14.00 y=14 <- round number, floating point inaccuracy, expected to be on the previous batch
p=14.25 y=14
p=14.50 y=14
p=14.75 y=14
p=15.00 y=14 <- round number

p=15.25 y=15
p=15.50 y=15
p=15.75 y=15
p=16.00 y=15 <- round number

p=16.25 y=16
```

**Comment by seberg** [comment]
Yeah, I do think your definition has its use-case, it just seems like it would probably add unnecessary complexity to try to make it work together with percentile.
