### ISSUE TITLE
during the drop of the float16 to binary, the order of the chars is flipped 

### ISSUE THREAD

**Issue by gideonKogan** [numpy/numpy#22581]
### Describe the issue:

during the drop of the float16 to binary, the order of the chars is flipped 

### Reproduce the code example:

```python
np.array([1]).astype('float16').tofile('test')
with open('test', mode='rb') as file: # b is important -> binary
    fileContent = file.read()
print(fileContent.hex())
# prints 003c rather than 3c00 
# see examples in https://en.wikipedia.org/wiki/Half-precision_floating-point_format
```

### NumPy/Python version information:

1.21.5

**Comment by mattip** [comment]
Float16 is stored as 2 bytes. The order of these bytes in memory depends on `sys.byteorder`. Most chips these days will use [little-endian systems](https://en.wikipedia.org/wiki/Endianness), so the more significant `3c` is stored after the `00` less-significant byte.
