### ISSUE TITLE
BUG: inverse of a array causing crash

### ISSUE THREAD

**Issue by lakshya-4gp** [numpy/numpy#22585]
### Describe the issue:

I'm trying np.linalg.inv with a 3x3 matrix (represents a camera's intrinsic matrix) which is causing kernel to crash in jupyter notebook.
To overcome the same, I've downgraded from 1.23.4 to 1.22.4, in which it works fine.

Issue comes for following array:

array([[514.13902522,   0.        , 640.        ],
       [  0.        , 514.13902522, 360.        ],
       [  0.        ,   0.        ,   1.        ]])

Issue in Version: 1.23.4 

### Reproduce the code example:

```python
import numpy as np
A = np.array([[514.13902522,   0.        , 640.        ],
       [  0.        , 514.13902522, 360.        ],
       [  0.        ,   0.        ,   1.        ]])

np.linalg.inv(A)
```

### NumPy/Python version information:

1.23.4

**Comment by charris** [comment]
Hmm, What OS? And how did you install NumPy?

**Comment by charris** [comment]
Oh, and does it work in a terminal?

**Comment by seberg** [comment]
Closing, since unfortunately there is no information to go by to see why it went wrong without followup.  @lakshya-4gp if you can follow up that would be much appreciated though (starting with the above questions and the result of `python -m threadpoolctl --import numpy` if possible, which requires installing threadpoolctl).

**Comment by lakshya-4gp** [comment]
I'm sorry, I believe notification mail got lost. I'm sorry it has been too long and I've been jumping systems so unfortunately, I cannot provide those details. Maybe if somebody else in the future gets the same issue, they can reopen or create a new issue.
