### ISSUE TITLE
BUG: Inconsistency between in-place `np.matmul` and `__imatmul__`

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#22606]
### Describe the issue:

Not sure what the expected behavior should be here, but noticed that `np.matmul` works in-place and `__imatmul__` doesn't. Guessing they should be consistent (whichever behavior is preferred).

### Reproduce the code example:

```python
import numpy as np

a = np.arange(9).reshape((3, 3))

a1 = a.copy()
np.matmul(a1, a1, out=a1)  # works

a2 = a.copy()
a2 @= a2                   # error
```

This still works when different square matrices are used:

```python
import numpy as np

a = np.arange(9).reshape((3, 3))
b = np.arange(9, 0, -1).reshape((3, 3))

a1 = a.copy()
np.matmul(a1, b, out=a1)  # works

a2 = a.copy()
a2 @= b                   # error
```

### NumPy/Python version information:

1.23.4 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ]

### Context for the issue:

Was playing around with options here after discussion in issue ( https://github.com/data-apis/array-api/issues/509 ).

As a side note, this comes up as [a SO answer]( https://stackoverflow.com/a/60871847 ). So whatever is decided here might be worth including as a response to that answer.

**Comment by jakirkham** [comment]
cc @seberg (in case you have thoughts here)

**Comment by mattip** [comment]
The error message indicates what the problem is, we never got around to implementing the functionality.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: In-place matrix multiplication is not (yet) supported. Use 'a = a @ b' instead of 'a @= b'.
```

**Comment by mattip** [comment]
or rather we couldn't agree on making it work

**Comment by jakirkham** [comment]
Ok so it would be ok to add. It just wasn't done. Wasn't sure if it was something to be avoided (even if well implemented). Thanks for clarifying! 🙏

Follow up question, why are these using two different code paths?

**Comment by mattip** [comment]
It is basically just an alias for `a = np.matmul(a, z, out=a)`. I would think it is quite common in the small 2x2 3x3 or 4x4 2d array case for multiplying image warping matrices or in similar uses for kalman filters.

@seberg do I understand your objection is that it will error out when the shapes don't match? Is the broadcast case any different than when doing `c = a @ b` ?

**Comment by seberg** [comment]
Sorry :(.  The "broadcast problem" is:
```
>>> arr = np.array([1.0, 2.0])
>>> arr @ arr
5.0
>>> np.matmul(arr, arr, out=arr)
```
doesn't make much sense (it fills `out` with repeated operations).  I do feel that is surprising behavior, but maybe it is OK.

But on the other hand, it may just be that my uncertainty just stems from the fact that this problem needs to be accounted for.

I suppose for stacks of square matrices, in-place may also actually be faster (at least in some future).

**Comment by mattip** [comment]
So the problem is that a naive user may be surprised when `a @= a` broadcasts? Maybe we could warn when `@=` broadcasts.

**Comment by mattip** [comment]
Something like "a @= b will broadcast when a @ b would not. If this is intentional, do a = np.matmul(a, b, out=a) instead"

**Comment by seberg** [comment]
Bas' PR gh-21120 currently added an error, but a warning would be OK as well if you prefer.  I do think I prefer it `vector @= vector` is strange, when others might not define the in-place OP (and return a fresh scalar due to Python defaults).

We could just finalize that PR probably, in that case since it seems nobody has reservations about rejecting non-square cases but accepting square ones.

**Comment by jakirkham** [comment]
Could we just error if `ndim < 2`?

Though a warning seems ok as well

**Comment by seberg** [comment]
Just `ndim < 2` would be simpler (no need to convert the other object to an array), it would reject:
```
a = np.array([1., 2., 3.])
a @= np.ones((3, 3))
```
but I am not sure if that actually matters?  If it doesn't seem to matter, it would be nice to simplify the PR.

**Comment by jakirkham** [comment]
We could check `ndim < 2` on both

**Comment by seberg** [comment]
This works now, of course there is no performance advantage to using the in-place version.
