### ISSUE TITLE
BUG: pickle then unpickle gives inconsitent result with original value

### ISSUE THREAD

**Issue by BugWriter2** [numpy/numpy#22602]
### Describe the issue:

Given an iterable of two numpy items with float64 dtype, after pickling and un-pickling, the new value is not exactly same as the original value

### Reproduce the code example:

```python
import numpy as np
import pickle

# an iterable of two numpy items with float64 dtype
v = [np.array([1.2, 2.2]), np.float64(1.2)]

# get the new value by pickling and un-pickling
new_v = pickle.loads(pickle.dumps(v))

# the new value is not exactly same as the original value
assert pickle.dumps(v) == pickle.dumps(new_v)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

### NumPy/Python version information:

1.23.4 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)
[GCC 10.3.0]

**Comment by bsipocz** [comment]
I don't think the picked representation has to be the same, you should compare `v` and `new_v` rather than their pickle dump.

**Comment by BugWriter2** [comment]
Thanks for your clarification, it seems my understanding on `pickle` is incorrect. Indeed I should compare values instead of pickle dump

**Comment by seberg** [comment]
To be fair, I suspect the behavior is due to how NumPy _unpickles_ dtypes, and that is not ideal.  So I agree it is not a bug, but could be a valid enhancement to try to fix up.
