### ISSUE TITLE
DOC: numpy.where poor listing of parameters

### ISSUE THREAD

**Issue by evensong** [numpy/numpy#22627]
### Issue with current documentation:

Current parameters [are listed as](https://numpy.org/doc/stable/reference/generated/numpy.where.html):

numpy.where(condition, [x, y, ]/)

However, the function expects (condition, x, y) where x and y are both array-like. Providing both in a list (as [x,y] suggests) raises the following.

ValueError: either both or neither of x and y should be given

### Idea or request for content:

Change to numpy.where(condition, x, y)

I've tried to find where the source for this is located so I could open a pull request, but I couldn't find the where function in the docs (This is my first time contributing to an open source project).

I've tried to follow the contribution guidelines, but please let me know if I ought to do something differently!

**Comment by eric-wieser** [comment]
The square brackets here have the same meaning as in https://docs.python.org/3/library/curses.html#curses.window.border; it's syntax for optional arguments.

**Comment by eric-wieser** [comment]
Having said that, perhaps we should persuade sphinx to display
```
numpy.where(condition)
numpy.where(condition, x, y)
```

**Comment by InessaPawson** [comment]
The doc string for `numpy.where` is located here: https://github.com/numpy/numpy/blob/cd757902af475c4844de878fbda25c70e2a0e66e/numpy/core/multiarray.py#L346

**Comment by evensong** [comment]
Thanks for the filepath, @InessaPawson . @eric-wieser , I think that it would be helpful for the majority of users to change the format so that it reads exactly as the source code is written. I'll make the change in my fork, is there anything I ought to do before starting a PR?

**Comment by eric-wieser** [comment]
> I think that it would be helpful for the majority of users to change the format so that it reads exactly as the source code is written

The current format is apparently pretty standard; see https://stackoverflow.com/q/1718903/102441
for a question about this.

I think if you view this as a big impediment to newcomers, it might be worth taking it up with python/cpython first. In my opinion it makes sense to adopt the conventions used in the docs there.

**Comment by eric-wieser** [comment]
> so that it reads exactly as the source code is written.

It's perhaps also worth noting that this is where the source code is written:

https://github.com/numpy/numpy/blob/dc8b760f7f58c6c80e2e298de2fb3195c80d9c53/numpy/core/src/multiarray/multiarraymodule.c#L3434

The link given by @InessaPawson is to where the docstring is, but that's not the real function (it's part of the array dispatch mechanism) so the signature there is not accurate.

**Comment by evensong** [comment]
My bad, I meant how it is written in the @ reference to the function in the docs. 

I personally feel that it is much more intuitive to write optional parameters with a default of None rather than using bracket notation, mostly because brackets are already used for lists and the access operators, both of which are used frequently. 

I can bring this up to python, though.

**Comment by eric-wieser** [comment]
> I personally feel that it is much more intuitive to write optional parameters with a default of None rather than using bracket notation

Unfortunately `np.where(cond, None, None)` gives a totally different meaning to `np.where(cond)`, so your suggestion would be actively incorrect.

**Comment by evensong** [comment]
Gotcha. I definitely want the documentation to accurately reflect the code's behavior. I was confused, but what you're saying makes sense; my confusion probably comes more from my own inexperience.

Before I close the issue, though, the docs say where(condition, [x,y]/]. Is that forward slash supposed to be there? It looks like it could be a typo.

**Comment by evensong** [comment]
Gotcha. I think it could be good to find a way to make the docs easier to read, but this isn't the issue I thought it was, so I'll close this issue.
