### ISSUE TITLE
BUG: numpy distutils fails with setuptools 65.6.0

### ISSUE THREAD

**Issue by 2sn** [numpy/numpy#22623]
### Describe the issue:

It tries to import `Log` from `distutils.log` but that has been removed in Version `65.6.0` of distutils.

### Reproduce the code example:

```python
pip3 install starfit
```

### Error message:

```shell
SETUPTOOLS_ENABLE_FEATURES="legacy-editable" pip3 install -e .[testing]
Obtaining file:///home/alex/python/starfit
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/alex/Python/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/alex/Python/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/alex/Python/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-jgu3of18/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-jgu3of18/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jgu3of18/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-build-env-jgu3of18/overlay/lib/python3.10/site-packages/numpy/distutils/__init__.py", line 26, in <module>
          from . import ccompiler
        File "/tmp/pip-build-env-jgu3of18/overlay/lib/python3.10/site-packages/numpy/distutils/ccompiler.py", line 20, in <module>
          from numpy.distutils import log
        File "/tmp/pip-build-env-jgu3of18/overlay/lib/python3.10/site-packages/numpy/distutils/log.py", line 4, in <module>
          from distutils.log import Log as old_Log
      ImportError: cannot import name 'Log' from 'distutils.log' (/tmp/pip-build-env-jgu3of18/overlay/lib/python3.10/site-packages/setuptools/_distutils/log.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
make: *** [Makefile:6: install] Error 1
```

### NumPy/Python version information:

```
1.23.4 3.10.7 (main, Sep 16 2022, 22:25:06) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)]
```

### Context for the issue:

I assume basically no package that uses `numpy.distutils` can be installed from source.

**Comment by 2sn** [comment]
obviously, on can add in

```
[build-system]
requires = ["setuptools<=65.5.1",  ...]
```

**Comment by sphuber** [comment]
It was [this commit](https://github.com/pypa/setuptools/commit/74652cabdeaacadc76ccf126563bed8ee2ccf3ef) that has broken things. The commit added the sentence `Retained for compatibility and should not be used.` to the docstring of the module, but there was no deprecation warning present.

**Comment by charris** [comment]
We have pinned setup_tools to 59.2 and have no plans to support later versions. This issue is why.

**Comment by 2sn** [comment]
@charris So, how do packages that depend on `numpy.distutils` know about this?  It does not seem to propage though by default.

**Comment by charris** [comment]
@2sn Your best bet is to pin the packages locally. Note that NumPy itself will migrate to using meson for building, Python distutils will disappear in Python 3.12. As to how you would know, hmm. Maybe we could add a message to distutils itself. Or we can just hope that setuptools fixes problem promptly.

**Comment by eli-schwartz** [comment]
Per https://github.com/numpy/numpy/issues/21114#issuecomment-1249752059

numpy officially shall not support setuptools 60+, specifically because numpy.distutils requires the CPython standard library version of distutils, and the setuptools version is actively, specifically, trying to change the distutils API because they consider it to be a maintenance burden, which is a problem for people who were, well, using that API.

It's not feasible or practical for the numpy team to continue adapting to setuptools 60+, because having multiple layers of projects all monkey-patching each other was never anything other than a house of cards... but it could work if distutils had a stable API, because once you get the card house built once, you can move in and start living there and it should stay up. But... that's no longer the case.

***There's an explicit offer to merge patches.*** Numpy is not going to try to solve problems in distutils -- but if someone cares enough and wants to put in the work, and it doesn't break people using pinned setuptools, then that's great.

> @charris So, how do packages that depend on `numpy.distutils` know about this? It does not seem to propage though by default.

Dependencies don't need to propagate. If your build system depends on numpy.distutils, then it will already print:

```
>>> import numpy.distutils
<stdin>:1: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 
```

This is sufficient and reasonable warning. If your build system uses numpy.distutils, you need to find a replacement within the year, and you are ***recommended*** (but not required) to pin setuptools, because "any later versions are probably broken, but not guaranteed so".

**Comment by eli-schwartz** [comment]
For https://github.com/conradtchan/starfit specifically, as that needs fortran support, no amount of refactoring/rewriting will let it work with plain setuptools (and there are currently no setuptools plans to add fortran compiler support AFAIK), and the best bet is probably to follow scipy/numpy and use Meson.

**Comment by 2sn** [comment]
@eli-schwartz Yes, I was aware of the warning w/r numpy.distutils discontinuation for Python 3.12.  That the setuptools maintainers would suddenly break compatibility before that, came as a surprise.

**Comment by eli-schwartz** [comment]
> That the setuptools maintainers would suddenly break compatibility before that, came as a surprise.

https://github.com/pypa/setuptools/issues/3532

According to at least one CPython core developer:

> setuptools must not remove, change, or deviate from any distutils APIs until it drops support for Python 3.11 (!). Yes, that means you would have to support your copy for distutils until [October 2027](https://peps.python.org/pep-0664/). In some cases it may even be required to stay bug compatible.

Needless to say, this is not happening -- and setuptools has broken numpy.distutils several times already, though some of them might have been rolled back or just not be universally applicable to all uses of `import numpy.distutils` in project setup.py files.

I seem to recall, the setuptools maintainers consider it acceptable to remove or otherwise backwards-incompatibly break the distutils APIs... for the reason of waiting and seeing if anyone reports that it broke their builds, and thereby ascertain whether those APIs are actually needed in the wild.

**Comment by saimn** [comment]
It also breaks `numpy.ctypeslib.load_library` which is more annoying. Pinning `setuptools` in `pyproject.toml` doesn't help here.

**Comment by eli-schwartz** [comment]
Huh, why does this rely on numpy.distutils at all, interesting. Maybe the get_shared_lib_extension function should find a better home -- it will need one anyway once numpy.distutils is dropped altogether.

**Comment by EimantasStonys** [comment]
For anyone having this broken even with pinned `setuptools` version - another workaround is to export `SETUPTOOLS_USE_DISTUTILS` variable when installing dependencies. Example for Dockerfile:

`RUN SETUPTOOLS_USE_DISTUTILS=stdlib poetry install --no-ansi --no-interaction`

**Comment by rgommers** [comment]
> This also breaks `numpy.testing`, which depends on `numpy.distutils`.

That is something we'd need to fix. As far as I can tell from a quick browse, this should not be the case for external users of `numpy.testing` APIs (only distutils usages are in `numpy/testing/_private/`, which should be numpy-internal). Are you actually using public functions from `numpy.testing` that are broken?

**Comment by SpecLad** [comment]
> > This also breaks `numpy.testing`, which depends on `numpy.distutils`.
> 
> That is something we'd need to fix. As far as I can tell from a quick browse, this should not be the case for external users of `numpy.testing` APIs (only distutils usages are in `numpy/testing/_private/`, which should be numpy-internal). Are you actually using public functions from `numpy.testing` that are broken?

Ah, my bad, looks like this has already been fixed by #20831. I was using an old NumPy version.

**Comment by andyfaff** [comment]
Can this be closed now that distutils has been removed from numpy?

**Comment by rgommers** [comment]
I'd say that yes, this can be closed. NumPy itself does not rely on `distutils` anymore, and doesn't even install `numpy.distutils` on Python >= 3.12. So users of `numpy.distutils` who need Python 3.12 support are having to move, and by and large have already moved. Our recommendation is to move to Meson and `meson-python` - we know it supports everything we needed from `numpy.distutils` and much more - or move to CMake and `scikit-build-core`. Both are way better than `numpy.distutils`/`setuptools`.

We'll still accept PRs with small fixes to `numpy.distutils` if anyone really needs a change for some reason. But this issue doesn't serve a purpose anymore beyond that.

Thanks all!

**Comment by 2sn** [comment]
I think it may not require a fix, but please keep  `numpy.distutils` in`numpy` for users of Python <3.12 for backward compatibility until `numpy` drops Python 3.11suppot in general, along with the dependence as above.

**Comment by rgommers** [comment]
@2sn that is indeed the plan.
