### ISSUE TITLE
BUG: crackfortran.py fails with 'common' blocks with Numpy version > 1.20

### ISSUE THREAD

**Issue by jarau-de** [numpy/numpy#22648]
### Describe the issue:

It seems Fortran 77 'COMMON' blocks are not matched correctly. I got the following error message:

crackline: groupcounter=1 groupname={0: '', 1: 'python module', 2: 'interface', 3: 'block data', 4: 'subroutine'}
crackline: Mismatch of blocks encountered. Trying to fix it by assuming "end" statement.

Following code causes the error:

python module iri16py ! in 
    interface  ! in :iri16py
        block data  ! in :iri16py:iridreg_modified.for
           COMMON /fircom/ eden,tabhe,tabla,tabmo,tabza,tabfl
       end block data 
    end interface 
end python module iri16py

Unfortunately all interface signature code after the common block will be ignored. With Numpy <= 1.20 it runs smooth. All versions above causes this error. If I document out the 'common' line all behaves fine. Please fix that soon. I tried to find out the reason in crackfortran.py, but it seems a bit too complex for me.
f2py seems also to be fine if one removes the space between end block data -> end blockdata.

### Reproduce the code example:

```python
f2py following code:
python module iri16py ! in 
    interface  ! in :iri16py
        block data  ! in :iri16py:iridreg_modified.for
           COMMON /fircom/ eden,tabhe,tabla,tabmo,tabza,tabfl
       end block data 
    end interface 
end python module iri16py
```

### Error message:

```shell
crackline: groupcounter=1 groupname={0: '', 1: 'python module', 2: 'interface', 3: 'block data', 4: 'subroutine'}
crackline: Mismatch of blocks encountered. Trying to fix it by assuming "end" statement.
```

### NumPy/Python version information:

1.21 and above

### Context for the issue:

I use a Python module which make use of old Fortran 77 code. Since f2py ignore all signature code after the COMMON block, the Python module routine gets not compiled in and the load of module fails. Without a fix to this issue I am forced to stay at Numpy 1.20 but I would like to update.

**Comment by charris** [comment]
@pearu @HaoZeke Thoughts?

**Comment by HaoZeke** [comment]
I can't seem to reproduce this as an error. The `crackline` warning is new, but that doesn't change anything. The generated files aren't different w.r.t. to the common block handling either.

```bash
f2py -v
1.24.0.dev0+943.g0075d59ce
f2py -c bug.pyf -m iri16py
python -c "import iri16py; print(iri16py.fircom.eden)"
0.0
```

This has the same result in NumPy 1.20

```bash
f2py -v
2
f2py -c bug.pyf -m iri16py
python -c "import iri16py; print(iri16py.fircom.eden)"
0.0
```

@jarau-de could you mention the exact `f2py` invocation and post the full error log? The warning shouldn't be fatal.

**Comment by HDembinski** [comment]
Thanks for looking into this. We suffer from the same issue.

**Comment by HDembinski** [comment]
I found a temporary hotfix.

Install the latest version of numpy. Replace the folder `f2py` in your installed numpy package with the folder `f2py` from numpy-1.19.5. I tested this for numpy-1.24.1

**Comment by HDembinski** [comment]
@HaoZeke Would it be possible to increasing the priority of this issue? This is a critical bug that makes f2py unusuable in recent numpy releases.

**Comment by HaoZeke** [comment]
@HDembinski sorry for the wait, the fix on https://github.com/numpy/numpy/pull/22657 now works.

The actual issue can be traced to https://github.com/numpy/numpy/commit/e6dab4ff15f25793c81b808d49d5359b8901809f where the parser was updated to include the Fortran 2008 `block` construct, which is used in several other places in the file and caused the issue.

**Comment by HDembinski** [comment]
Thank you very much! Should I test-run this PR on my setup or do you think it is not necessary?

**Comment by mattip** [comment]
@HDembinski if it would be possible to test the PR that would help give confidence that the fix is correct.
