### ISSUE TITLE
DOC: memmap doc does not mention an exception regarding 'mode' and 'shape'

### ISSUE THREAD

**Issue by Ingkarat** [numpy/numpy#22643]
### Issue with current documentation:

numpy.memmap raises an exception when the parameter **mode** is 'w+' and **shape** is not specified. The documentation does not mention this requirement. [Doc v1.23](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html)

The code is modified from the examples in the documentation.
```python
import numpy as np
from tempfile import mkdtemp
import os.path as path
filename = path.join(mkdtemp(), 'newfile.dat')
fp = np.memmap(filename, dtype='float32', mode='w+')
```
```
Traceback (most recent call last):
  File "...\test.py", line 9, in <module>
    fp = np.memmap(filename, dtype='float32', mode='w+')
  File "...\Python39\lib\site-packages\numpy\core\memmap.py", line 223, in __new__
    raise ValueError("shape must be given")
ValueError: shape must be given
```

### Idea or request for content:

A suggestion is to mention this requirement, maybe at the end of the description of the parameter **shape**.
For example, appending "If mode == 'w+' then shape must be specified" to it.

**Comment by sanjail3** [comment]
can I work on this issue?

**Comment by sanjail3** [comment]
I am new to open-source contribution.do  I need to change only documentation for this issue.
