### ISSUE TITLE
Masked Range Array

### ISSUE THREAD

**Issue by modaresimr** [numpy/numpy#22642]
### Proposed new feature or change:

assume we have a big array. 50% of this array is zero and others are in a specific range
for instance:

array shape= 1000,1000,1000

data_roi=(300:700, 500:700, 200:400)

There is no need to put all the values in the memory, and even it is not efficient to use a sparse array.
The operations like + - eq can easily override for only this roi.

It would be great if we could have such a "segment array"

**Comment by mattip** [comment]
This seems like a block sparse array like [SciPy provides](https://docs.scipy.org/doc//scipy/reference/generated/scipy.sparse.bsr_array.html#scipy.sparse.bsr_array) In any case sparse arrays of any kind are out of scope for NumPy

**Comment by seberg** [comment]
Indeed, maybe SciPy provides this already or would be interested in expanding theirs (there may be some momentum in sparse development soon, although I suspect it needs to be directed at infrastructure first.)

But, this agreed, this is out of scope for NumPy, so closing.  It is in scope for NumPy to provide functionality to work interoperate with NumPy, this exists through the [interoperabity features](https://numpy.org/devdocs/user/basics.interoperability.html).
