### ISSUE TITLE
ENH: Add a new inf whose data type is int

### ISSUE THREAD

**Issue by Nclearadwood** [numpy/numpy#22641]
### Proposed new feature or change:

Hi, I am a student and I have very little knowledge about python and numpy, so my suggestion may seem really stupid.
One day I was use numpy to implement Floyd algorithm and then I found the data type of np.inf is float, so i can not use min or max function because other data type are int. So I wonder whether you can add a new inf whose data type is int. Thanks.

**Comment by seberg** [comment]
I think the mailing list answer was nice and in depth.  You *could* create such a datatype, but it does not belong in NumPy proper (more interesting are probably things that use the smallest integer as an `NA`, i.e. masked value or a "not a number" value, but of course you could also reserve more values for +inf and -inf).
I.e. the path to such a new datatype would be starting it outside and then probably only then convincing others that it should be part of NumPy proper.
