### ISSUE TITLE
BUG: using numpy.fromfile cannot load \x00 numbers on the tail of the file

### ISSUE THREAD

**Issue by guchengxi1994** [numpy/numpy#22656]
### Describe the issue:

office binary files(docx,xlsx,...) are ends with \x00, but using `fromfile` cannot read it.
**original file**
![image](https://user-images.githubusercontent.com/33513462/203466358-b85fc473-d2dc-4e1e-b7e0-6658ceb32c9e.png)

**dumped file**
![image](https://user-images.githubusercontent.com/33513462/203466741-3fd764c9-3578-4467-91a7-d12a98371cee.png)

**test docx file**
[test.docx](https://github.com/numpy/numpy/files/10072724/test.docx)

### Reproduce the code example:

```python
import numpy as np


def _load_file_by_numpy(p: str) -> np.ndarray:
    dataArray = np.fromfile(p, dtype=np.int32, count=-1)
    
    return dataArray

if __name__ == "__main__":
    filePath = r"D:\secret_data\secret_data_python_cv\test.docx"
    dataArray = _load_file_by_numpy(filePath)
    print(dataArray.shape)

    dataArray.tofile(r"D:\secret_data\secret_data_python_cv\result.docx")
```

### NumPy/Python version information:

1.23.3 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]

**Comment by rkern** [comment]
When you use `dtype=np.int32`, the length of the data must be an even multiple of 4 bytes. You can see from the hex dump that you would have 2 bytes left over in the original data. When you use `count=-1`, it will truncate any leftover bytes. Those are the 2 bytes that are missing from the written-out data.

I don't know what your use case is, but if you want to load arbitrary data in for some reason, consider `dtype=np.uint8`.
