### ISSUE TITLE
BUG: Quantile function on complex numbers doesn't error

### ISSUE THREAD

**Issue by aschaffer** [numpy/numpy#22652]
### Describe the issue:

Complex numbers are unordered. The complex set, ℂ, is isomorphic with ℝ², which is an unordered vector space. On the other hand, quantiles are the inverse of the cumulative distribution function, CDF. Which is monotonic. It must be, for its inverse to exist.

Consequentially, it makes no mathematical sense to apply quantiles to an unordered set, like a complex input array. Some order can be introduced (e.g., lexicographic) but it is artificial, without a sound mathematical support.

However, both sorting and quantiles functions work in numpy (see example below). Instead, an exception should be thrown.

### Reproduce the code example:

```python
import numpy as np

arr_c = np.array([0.5+3.0j, 2.1+0.5j, 1.6+2.3j], dtype=np.dtype('complex128'))
np.quantile(arr_c, 0.5)
```

### NumPy/Python version information:

1.23.3 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0]

**Comment by seberg** [comment]
Thanks for the issue.  We had a start on deprecating complex sorting, and I think some consensus around the attempt (IIRC, with the idea of providing a way to make complex sort work via an additional `by=` or so).  Or one could maybe flag that the order isn't "proper"...
(See also gh-16700 and issues linked from there.  That would directly tie rejecting this to sorting.)

But, I think it makes sense to be pragmatic here and just add an error to `quantile` for complex results.

**Comment by aschaffer** [comment]
Sure. Yes, I think we need to stay true to the math. The CDF wrt to real random value variable X, is defined as F_X : ℝ →[0, 1], F_X(x) = P(X ≤ x). Hence, the quantile function, which is the inverse of the CDF, has a real codomain (https://en.wikipedia.org/wiki/Quantile_function).

Now, there is an extension, Z, of random variables from real to complex, making F_Z : ℂ →[0, 1]. But in that case the CDF is defined as a joint distribution probability: F_X(z) = P( Re(Z) ≤ Re(z), Im(Z) ≤ Im(z)). (https://en.wikipedia.org/wiki/Complex_random_variable)

So, that _suggests_ that complex quantile function _might_ be possible, but the induced order is not lexicographic but "joint"; i.e.,  for z1, z2 ∈ ℂ: z1 < z2 iff (Re(z1) < Re(z2) and Im(z1) < Im(z2)). 

But that only induces a _partial_ order (what's the order between (1+2j) and (2+j)...?). But then classical sorting still cannot be used on a partial order, you need topological sort. So things are becoming messy. Certainly not what they are now, wrt ℂ.

**Comment by aschaffer** [comment]
Actually, things are actually worse than that: most likely the quantile function for the complex case doesn't even exist. 

Consider complex random variable Z = X + Y⋅j with X, Y (real) random variables being independent, which seems the more natural case. Then,
     
     F_Z(z) = F_X(x)⋅F_Y(y) = P(X≤x)⋅P(Y≤y)

Consider, for example, X,Y as being the scores of 2 separate fair dice. Then,
     F_Z(1+6⋅j) = P(X≤1)⋅P(Y≤6) = P(X∈{1})⋅1 = 1/6
     F_Z(2+3⋅j) = P(X≤2)⋅P(Y≤3) = P(X∈{1,2})⋅P(Y∈{1,2,3}) = 1/3 ⋅ 1/2 = 1/6

Hence, F(z1) = F(z2) for some z1 ≠ z2; i.e., F_Z(z) is not injective ⇒ not bijective ⇒ not invertible ⇒ quantile function doesn't exist!

**Comment by seberg** [comment]
This issue should have been closed, see gh-22703
