### ISSUE TITLE
BUG:  TypeError: data type 'int0' not understood

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#22672]
### Describe the issue:

I think dtype was meant to be deprecated (as per #15334) but apparently the dtype disappeared without notice since last night's nightly build.

### Reproduce the code example:

```python
import numpy as np
np.dtype("int0")
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type 'int0' not understood
```

### NumPy/Python version information:

1.25.0.dev0+11.ga872fd73e

**Comment by seberg** [comment]
Yah, I meant `np.int0` to go away mainly, didn't feel like doing the far more complicated `np.dtype("int0")` dance just before branching.

**Comment by ogrisel** [comment]
Thanks!
