### ISSUE TITLE
BUG: (cos(x)^2+sin(x)^2)>1

### ISSUE THREAD

**Issue by XavierTolza** [numpy/numpy#22691]
### Describe the issue:

Hello.
I ran into some issues because sometimes computing $cos(x)^2+sin(x)^2$ leads to a value slightly above 1.
I did not hve the issue in python3.7 numpy 1.21 and since updating in python3.8 and numpy 1.23 the error appeared.

### Reproduce the code example:

```python
import numpy as np

angle = np.deg2rad(224)
should_be_one = (np.cos(angle) ** 2 + np.sin(angle) ** 2)
print(should_be_one)
```

### Error message:

```shell
$ venv37/bin/python myproblem.py 
1.0
$ venv38/bin/python myproblem.py 
1.0000000000000002
```

### NumPy/Python version information:

Working with the following configuration:
1.21.6 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0]

Not working anymore
1.23.5 3.8.14 (default, Sep 19 2022, 09:47:48) 
[GCC 9.1.1 20190605 (Red Hat 9.1.1-2)]

### Context for the issue:

This can lead to errors, in my case when converting from a spherical coordinate system to another. Indeed when converting from U and V coordinates to theta and phi (see [here](https://fr.mathworks.com/help/phased/ug/spherical-coordinates.html) for the explaination on those two coordinate systems), the function is the following:

```python
def uv_to_thetaphi(u: np.ndarray, v: np.ndarray):
    uv_norm = u**2 + v**2
    theta = np.arcsin(np.sqrt(uv_norm))
    phi = (np.arctan2(v, u) + 2 * np.pi) % (2 * np.pi)
    return theta, phi
```
There you have a call to `arcsin` on `u**2+v**2` which is >1 and thus this leads to nan values.
Using `np.clip` is a solution, but it would hide problems due to incorrect input values from the user.

**Comment by mattip** [comment]
I cannot reproduce with conda:
```
$ python
Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35) 
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.23.5'
>>> angle = np.deg2rad(224)
>>> should_be_one = (np.cos(angle) ** 2 + np.sin(angle) ** 2)
>>> should_be_one <= 1.0
True

```

nor does it reproduce with python from Ubuntu when using the wheel from PyPI:
```
$ /tmp/venv3/bin/python
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.23.5'
>>> angle = np.deg2rad(224)
>>> should_be_one = (np.cos(angle) ** 2 + np.sin(angle) ** 2)
>>> should_be_one <= 1.0
True
```

**Comment by WarrenWeckesser** [comment]
Like @mattip, I can't reproduce the issue with the specific `angle` that you use, but in general, this behavior is unavoidable.  The calculations use finite precision, so you cannot expect $\cos^2x + \sin^2 x$ to be *exactly* 1 for all $x$.

For example, with `angle = 3.909537524467309`, I get `1.0000000000000002`:

```
In [309]: angle = 3.909537524467309

In [310]: np.cos(angle)**2 + np.sin(angle)**2
Out[310]: 1.0000000000000002
```
This is "correct", because it is based on the approximations computed by `np.cos(angle)` and `np.sin(angle)`, and these give the best approximations that can be expected.  This can be verified by checking those values with `mpmath`:

```
In [311]: from mpmath import mp

In [312]: mp.dps = 500

In [313]: float(mp.cos(angle))
Out[313]: -0.7193398003386438

In [314]: np.cos(angle)
Out[314]: -0.7193398003386438

In [315]: float(mp.sin(angle))
Out[315]: -0.694658370459005

In [316]: np.sin(angle)
Out[316]: -0.694658370459005

```
Because those calculations are only approximations of the true value of `cos(angle)` and `sin(angle)`, the sum of the squares is not necessarily 1, and in this case, it is `1.0000000000000002`:
```
In [318]: (-0.7193398003386438)**2 + (-0.694658370459005)**2
Out[318]: 1.0000000000000002
```

**Comment by XavierTolza** [comment]
That seems legit.
Then, what is the right & safe way to use the result of  $cos(x)^2+sin(x)^2$ in an $arcsin$ function?
As stated in the ticket, using `np.clip` could fix it but I'm not sure it would be recommended since incorrect input from the user would lead to valid output.
Nan values should be kept only when $u^2+v^2>1$, but we should have a manual check? Or maybe substract epsilon from the result before appling arcsin?

**Comment by rkern** [comment]
`np.arcsin(np.hypot(u, v))` would probably behave better; I'm not sure that it will _guarantee_ that `np.hypot(cos(theta), sin(theta))` won't go above 1 on any platform, but it seems to do so less in my experience.

It really depends on your use case, but `np.clip()` is a perfectly reasonable thing to do. If you really want to exclude `u, v` values where `np.hypot(u, v) > 1`, decide on the threshold and explicitly check and raise earlier. Don't rely on `np.arcsin()` to validate for your use case.

```python
def uv_to_thetaphi(u: np.ndarray, v: np.ndarray):
    uv_length = np.hypot(u, v)
    if (uv_length > (1 + 10*np.finfo(u.dtype).eps)).any():
        raise ValueError("...")
    theta = np.arcsin(np.clip(uv_length, 0, 1))
    ...
```

**Comment by tomio13** [comment]
It is a numerical calculation issue, I can reproduce using:
```python
import numpy as nu
x = nu.arange(1000)/100.0
y= nu.sin(x)**2 + nu.cos(x)**2
print(y[y > 1.0] - 1.0)
```
I get an array of 36 values: 2.22044605e-16 indicating a numerical representation effect.
