### ISSUE TITLE
BUG: SIGSEGV on PyPy3.7-7.3.9 and numpy 1.21.6

### ISSUE THREAD

**Issue by tammoippen** [numpy/numpy#22695]
### Describe the issue:

Running with the precompiled numpy from pypi, i get segvaults converting datetime64 into python datetimes for pypy3.7.

```sh
$ pypy3.7 -m pip install numpy
Collecting numpy
  Using cached numpy-1.21.6-pp37-pypy37_pp73-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.2 MB)
Installing collected packages: numpy
Successfully installed numpy-1.21.6

$ pypy3 -c 'import numpy as np; np.datetime64("2022-01-01T12:00:00").item()'
fish: Job 1, 'pypy3 -c 'import numpy as np; n…' terminated by signal SIGSEGV (Address boundary error)

```

When building the numpy lib from source, there is no such error.

```sh
$ pypy3.7 -m install --no-binary numpy numpy
Collecting numpy
  Using cached numpy-1.21.6.zip (10.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... done
  Created wheel for numpy: filename=numpy-1.21.6-pp37-pypy37_pp73-linux_x86_64.whl size=6869664 sha256=1fd83a9bfbc319edb988cb1288d9654776b1c2baf98ec927fc9e723a5f1ca470
  Stored in directory: /home/tammo/.cache/pip/wheels/5c/47/f4/e65038499db16c1998bd745b8101da1b1f8a9cc4131df49549
Successfully built numpy
Installing collected packages: numpy

$ pypy3 -c 'import numpy as np; np.datetime64("2022-01-01T12:00:00").item()'

$ # no SIGSEGV
```

### Reproduce the code example:

```python
import numpy

numpy.datetime64("2022-01-01T12:00:00").item()
```

### Error message:

```shell
$ pypy3 -c 'import numpy as np; np.datetime64("2022-01-01T12:00:00").item()'
fish: Job 1, 'pypy3 -c 'import numpy as np; n…' terminated by signal SIGSEGV (Address boundary error)
```

### NumPy/Python version information:

```sh
$ pypy3.7 -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.21.6 3.7.13 (7e0ae751533460d5f89f3ac48ce366d8642d1db5, Mar 29 2022, 06:03:31)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
```

### Context for the issue:

I am maintaining [plotille](https://github.com/tammoippen/plotille) and want to support printing numpy arrays of datetimes as well. My strategy right now is to transform them into native python objects. This is the only combination failing right now: i removed it for now, but would like to test it as well.

Here is a failing run: https://github.com/tammoippen/plotille/actions/runs/3574303228/jobs/6009404104

**Comment by mattip** [comment]
Hmm. PyPy has dropped support for PyPy3.7, and I see the PyPy3.8 and PyPy3.9 CI runs are passing. I can reproduce the problem (somehow the `PyDate_FromDate` macro is failing to call `_PyDate_FromDate` properly), but even if I could figure it out I don't think I could convince the PyPy release manager (me) to release a PyPy3.7 to fix this.

**Comment by mattip** [comment]
More than likely connected to an [issue with binary compatibility and the `TimeZone_UTC` field](https://foss.heptapod.net/pypy/pypy/-/issues/3688), and the use of pypy3.7-v7.3.8 to build the wheel. Maybe if you ran the CI with pypy3.7-v7.3.8 it would pass this test but again I would discourage using pypy3.7.

**Comment by charris** [comment]
@mattip Should we upgrade pypy for the 1.24 releases?

**Comment by mattip** [comment]
@charris done in #22696

**Comment by tammoippen** [comment]
Hi @mattip, thank you for the replay. I was not aware that pypy3.7 v7.3.9 is the last 3.7 release from pypy. That resolves the issue for me - i will drop it as well. I leave the issue open, in case you want to take some action.

**Comment by seberg** [comment]
I don't think there is anything to do, so closing.  Thanks for opening the issue.
