### ISSUE TITLE
DOC: error in the description of `numpy.random.pareto`

### ISSUE THREAD

**Issue by ViktorBezb** [numpy/numpy#22701]
### Issue with current documentation:

The 'Notes' part of the documentation on Pareto distribution is wrong. The density in both pages reads as $p(x) = \frac{am^a}{x^{a+1}}$, but this is obviously not even a density, because the function $p(x)$ is not integrable for $a>0$.

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.pareto.html#numpy.random.Generator.pareto

https://numpy.org/doc/stable/reference/random/generated/numpy.random.pareto.html

**Comment by Mukulikaa** [comment]
Hey @Sinusxdx, I looked it up on Wikipedia and the docs seem correct - [Pareto distribution](https://en.wikipedia.org/wiki/Pareto_distribution#Cumulative_distribution_function).

**Comment by ziyaj** [comment]
Hey @Sinusxdx,

The probability density $p(x$) function is correct. It is integratable. When $x < m$, $p(x)=0$, so we only need to integral from $m$ to $+\infty$.

$\int p(x)dx =  \int_{m}^{+\infty} \frac{am^a}{x^{a+1}} dx = a m^a \int_{m}^{+\infty} \frac{1}{x^{a+1}} dx = a m^a (-\frac{1}{a} x^{-a})|_{m}^{+\infty} = m^a (m^{-a} - +\infty^{-a}) = m^0= 1$. 

Note that $a$ and $m$ are constants, so they can be pulled out of the integral in the beginning. So we are pretty much left with $\int \frac{1}{x^{a+1}} dx$, which is one of the most basic integral. Note that $+\infty^{-a} = \frac{1}{+\infty^a} = 0$.

**Comment by Sinusxdx** [comment]
Hello @Mukulikaa and @ziyaj,

Indeed $p(x)$ is a density if considered only for $x > m$; however this is not reflected in the documentation. It should clearly specify that $p(x) = 0$ for $x < m$. Furthermore, the value of $m$ is not given anywhere: neither in the description, nor it is available as an argument. What is the value of $m$ used in the generation of a random sample? 

Running this commands

```
import numpy as np
min(np.random.pareto(7, size=10000))
}
```

repeatedly I get small numbers like 2.766544932031323e-06. Now,  Pareto random variables cannot take value below $m$. Since I am getting very close to $0$, it seems that the distribution is supported on $[0, +\infty)$. However $p(x)$ is not integrable on  $[0, +\infty)$. Something is wrong here.

**Comment by Mukulikaa** [comment]
Perhaps @melissawm can help out with this!

**Comment by melissawm** [comment]
It feels like something like this could be enough:
![pareto](https://user-images.githubusercontent.com/3949932/205760100-cd4708fe-8e2a-4346-abe1-1cd7a95ef1c3.png)

However, if we do have some code path on forbidden intervals maybe it's worth including a warning?

**Comment by ViktorBezb** [comment]
> It feels like something like this could be enough: ![pareto](https://user-images.githubusercontent.com/3949932/205760100-cd4708fe-8e2a-4346-abe1-1cd7a95ef1c3.png)
> 
> However, if we do have some code path on forbidden intervals maybe it's worth including a warning?

I don't think it is sufficient. Two issues remain: 

1. It is not indicated anywhere what numerical value of $m$ is used.
2. The distribution seems to be supported on $[0, +\infty)$, which should imply $m = 0$. But $m = 0$ is impossible.

I tried to find the code for numpy.random.pareto, and it seems that the source written in another language. I found this [file](https://github.com/numpy/numpy/blob/c90d7c94fd2077d0beca48fa89a423da2b0bb663/numpy/random/mtrand/distributions.c). Is this how Pareto random variables generated? If so, this is the code:

```
double rk_pareto(rk_state *state, double a)
{
    return exp(rk_standard_exponential(state)/a) - 1;
}
```
Hence a Pareto random variable with parameter $a$ is generated as $e^{\xi/a}-1$, where $\xi$ is a standard exponential. From here we get the density $f(x) = \frac{a}{(x+1)^{a+1}}$, $x \geq 0$. Note an important difference with the current notes: $x+1$ instead of $x$ in the denominator, hence everything is integrable on $[0, +\infty)$. 

**Suggestion to modify the notes.** Given the parameter $a > 0$, the probability density for the generated (pseudo-)random number is

$$ f(x) = \frac{a}{(x+1)^{a+1}},  \ \ \   x \geq 0,$$


This corresponds to the Pareto II distribution and can be seen as Pareto I distribution shape $a$ and  scale $m=1$ shifted by $-1$. 

**Disclaimer**: I am a mathematician and I do not have much experience with writing libraries.

**Comment by melissawm** [comment]
Maybe @rkern can take a look - as far as I can see the definition you mention now lives in [this file](https://github.com/numpy/numpy/blob/main/numpy/random/src/distributions/distributions.c)

**Comment by rkern** [comment]
I implemented the distribution based on the algorithm in Luc Devroye's [_Non-Uniform Random Variate Generation_](http://luc.devroye.org/rnbookindex.html) on pg 262, which does indeed match @ViktorBezb's suggested text. Most of the `Notes` in the docstrings were written later by other people at a time when we had fewer tools for reviews. Given the plethora of minor variants of "Pareto distributions" that are out there, those volunteers just found the wrong variant to document by mistake.

**Comment by Matt711** [comment]
I'll work on this issue

**Comment by mkiffer** [comment]
I am not sure I have understood the full complexity of the issue but have created a small change to the formula. 

[https://github.com/numpy/numpy/pull/23347](url)

See the pull request here. 

FROM:
        .. math:: p(x) = \\frac{am^a}{x^{a+1}}
TO:
        .. math:: p(x) = \\frac{am^a}{{x+1}^{a+1}} , x \ge m

**Comment by ViktorBezb** [comment]
> I am not sure I have understood the full complexity of the issue but have created a small change to the formula.
> 
> [https://github.com/numpy/numpy/pull/23347](url)
> 
> See the pull request here.
> 
> FROM: .. math:: p(x) = \frac{am^a}{x^{a+1}} TO: .. math:: p(x) = \frac{am^a}{{x+1}^{a+1}} , x \ge m

This is not sufficient because $m$ is not specified anywhere. The formula should be as in my previous comment.
