### ISSUE TITLE
Indefinite Return Values Of numpy.empty.tolist()

### ISSUE THREAD

**Issue by suuuehgi** [numpy/numpy#22709]
### Describe the issue:

When using `tolist()` method on `numpy.empty`, "random" numbers are being returned. In terms of C, this is plausible, but in terms of python I would like to see this either raise an error or return a list of zeros.
That is, return something definite.

### Reproduce the code example:

```python
import numpy as np
>>> np.empty(10).tolist()
[6.9440541211846e-310, 6.9440541211846e-310, 3.725361380718306e-08, 0.0025140978509631726, 10621648.016143985, 4.3894126211342807e-215, 2.8305573435223495e+26, 3.43106008725432e-306, 3.588899273515368e-306, 2.2253476465298852e-307]
```

### Error message:

```shell
See above.
```

### NumPy/Python version information:

1.21.5 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]

**Comment by seberg** [comment]
Yes, as does `np.empty(10)`.  "empty" is documented to return uninitialized values (if possible).  Uninitialized values are often random like this, can also seemingly make sense.

That is sometimes useful for speed, use `np.zeros()` or similar if you are looking for something that doesn't return "weird" values.

**Comment by suuuehgi** [comment]
All right, thank you!
