### ISSUE TITLE
BLD: enscriptem CI run failed

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#22712]
There is a failure in `TestPower.test_zero_power_nonzero` in the enscriptem wasm CI run, for instance [here](https://github.com/numpy/numpy/actions/runs/3601430941/jobs/6067221009) and [here](https://github.com/numpy/numpy/actions/runs/3601062074/jobs/6066427897#step:9:21891). This is new. 

There is also a warning in the build
> build-wasm-emscripten
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mymindstorm/setup-emsdk@v11

@hoodmane @rth could you take a look?

**Comment by mattip** [comment]
Probably connected to #18535, which I merged before noticing that this build was failing there

**Comment by mattip** [comment]
@prithvitewatia could you also take a look?

**Comment by rth** [comment]
Yes, float exceptions do not work in wasm for that test should be skipped for the emscripten CI. I can make a PR later if anyone doesn't get to it before.

**Comment by mattip** [comment]
Thanks. The node.js warning is tracked at mymindstorm/setup-emsdk#28

**Comment by prithvitewatia** [comment]
@mattip Sure.
