### ISSUE TITLE
BUG: meson.build not working with MSVC

### ISSUE THREAD

**Issue by Neumann-A** [numpy/numpy#22711]
### Describe the issue:

The meson buildsystem numpy has doesn't work with MSVC on windows since the defines 
```
#mesondefine NPY_SIZEOF_COMPLEX_FLOAT
#mesondefine NPY_SIZEOF_COMPLEX_DOUBLE
#mesondefine NPY_SIZEOF_COMPLEX_LONGDOUBLE
```
won't be defined. 

Yielding the following error:
`numpy\core\include\numpy/npy_common.h(430): fatal error C1189: #error:  npy_cdouble definition is not compatible with C99 complex definition !         Please contact NumPy maintainers and give detailed information about your         compiler and platform`

### Reproduce the code example:

```python
-
```

### Error message:

```shell
-
```

### NumPy/Python version information:

-

**Comment by mattip** [comment]
Please follow the [meson tracking issue](https://github.com/numpy/numpy/issues/22546) and the work on the [meson branch](https://github.com/numpy/numpy/tree/meson). For your issue, commit 588613834 should fix it, but more is needed for the MSVC build to work. Help is welcome.

**Comment by ashish-2022** [comment]
Hi @mattip 

I get this error when compiling numpy with intel MKL on Windows.
is there any extra environment variables I need to set for this?

```
 [7/489] Compiling C object numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj
      FAILED: numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj
      "icl" "-Inumpy\core\libnpymath.a.p" "-Inumpy\core" "-I..\..\numpy\core" "-Inumpy\core\include" "-I..\..\numpy\core\include" "-I..\..\numpy\core\src\npymath" "-I..\..\numpy\core\src\common" "-IC:\DE-Python\Include" "-ID:\Script_VMC\numpy-1.26.1\.mesonpy-okitud_x\build\meson_cpu" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Qstd:c99" "/O3" "/arch:SSE3" "-DNPY_HAVE_SSE2" "-DNPY_HAVE_SSE" "-DNPY_HAVE_SSE3" "-DMS_WIN64=" "/Fdnumpy\core\libnpymath.a.p\meson-generated_ieee754.c.pdb" /Fonumpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj "/c" numpy/core/libnpymath.a.p/ieee754.c
      icl: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '/Qdiag-disable:10441' to disable this message.
      ../../numpy/core/include/numpy/npy_common.h(388): catastrophic error: #error directive: npy_cdouble definition is not compatible with C99 complex definition !         Please contact NumPy maintainers and give detailed information about your         compiler and platform
        #error npy_cdouble definition is not compatible with C99 complex definition ! \
         ^

      compilation aborted for numpy/core/libnpymath.a.p/ieee754.c (code 4)
```

**Comment by rgommers** [comment]
@ashish-2022 this is a new issue, because it's about the Intel C/C++ compilers rather than MSVC. I'll move this to gh-25034.
