### ISSUE TITLE
numpy 1.24.0rc1 gives scalar False in masked_invalid when input is plain array

### ISSUE THREAD

**Issue by pllim** [numpy/numpy#22720]
Is this change intentional? I cannot tell.

As a result of this change, when someone pass in plain array and then try to grab the `.mask`, it has `ndim=0` and the shape no longer matches the input, causing some downstream assumptions to break.

xref https://github.com/astropy/specreduce/pull/153

### numpy 1.23.5

```python
>>> import numpy as np
>>> np.ma.masked_invalid([1,2,3])  # Same if I pass in np.array([1,2,3])
masked_array(data=[1, 2, 3],
             mask=[False, False, False],
       fill_value=999999)
```

### numpy 1.24.0rc1

```python
>>> import numpy as np
>>> np.ma.masked_invalid([1,2,3])  # Same if I pass in np.array([1,2,3])
masked_array(data=[1, 2, 3],
             mask=False,
       fill_value=999999)
```

**Comment by seberg** [comment]
Must have been a side-effect of pluggin in `masked_where` here, so not intentional.  I suppose it is not really incorrect in the sense that `arr.mask is False is np.ma.nosmak` and thus a of spelling for "the mask is false everywhere".

But I don't see why not to just add a `get_mask()` call (if that was it) to materialize the full mask (and retain behavior), it isn't like we are aiming for consistency in masked arrays at this point/time.  (and if we did, I wonder if we should just always materialize the mask.)

**Comment by pllim** [comment]
Thanks for the reply!

In 1.24.0rc1, `get_mask` also gives a scalar `False`. But perhaps I have misunderstood what you are saying.

```python
>>> np.ma.core.get_mask([1,2,3])
False
```

**Comment by seberg** [comment]
Oh, it does... I think there should be a way to materialize the full mask, I thinkt here was an internal `_get_mask` or so for that.
(I also wrote `is False` up there, that is incorrect, it is `is np.False_`...)

**Comment by seberg** [comment]
Sorry... the point was, there is some utility function that converts the `nomask` to a full mask... apparently `get_mask` is not it :).

**Comment by pllim** [comment]
So, this feature will ship for sure with 1.24? Just want to know if I should code in check for this or will this be reverted if it wasn't intentional. Thanks!

**Comment by pllim** [comment]
I am neutral as well but then again I am not the main devs for the affected package. I only noticed it in "integration testing". The patch isn't horrible and I really don't know how many more packages use it like this.

https://github.com/astropy/specreduce/pull/153

**Comment by seberg** [comment]
Well, I guess if we are neutral, it means we are not enthusiastic enough about cleaning up the behavior and should just add the hack to retain the old one ;).

**Comment by pllim** [comment]
Actually, since I replied, specreduce has decided to remove this particular usage altogether, so with https://github.com/astropy/specreduce/pull/155 , this issue no longer affects us but still might for a different package, not sure. cc @ojustino

**Comment by ojustino** [comment]
As @pllim said, this is no longer causing problems for `specreduce`, so it's a no-urgency issue for us. As a general user, it would be nice to have a way to get an all-`False` array in this scenario, whether that's through `get_mask()` or a `mask` attribute.
