### ISSUE TITLE
Cirrus fails to upload wheels on tag push.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#22730]
Manually running a build for the 1.24.0 branch does upload the correct wheels, but to the nightly repo. Rerunning the tagged build only reruns the upload, which fails because there are no wheels to upload.

**Comment by charris** [comment]
It seems our cirrus runner ignores tags and relies on commit messages, which we don't use at all. Cirrus itself does run on the tag push, for instance it ran on "branch" v1.24.0rc2, but there was no upload.

**Comment by mattip** [comment]
Do you need the artifacts? I can trigger a build

**Comment by andyfaff** [comment]
Do you have a link for the tag run that didn't upload?

**Comment by charris** [comment]
Not anymore, I reran the build and it failed because of missing wheels :) However, I'd be willing to push/delete tags in the 1.,24.x branch to find out what is going on. IIRC, it wasn't caught as a push or a tag, but the wheels were built. Note that I only pushed a tag, not a commit.

**Comment by charris** [comment]
EDIT: However, cirrus had the branch as `v1.24.0rc2`, i.e., the tag name.  I wondered if there might be a branch restriction on uploads.

**Comment by andyfaff** [comment]
- the [.cirrus.star](https://github.com/numpy/numpy/blob/main/.cirrus.star) script should always run the [`tools/ci/cirrus_general.yml`](https://github.com/numpy/numpy/blob/main/tools/ci/cirrus_general.yml) tasks on any trigger except if the commit message has `[skip ci]`, `[skip cirrus]` in the commit message. There are no branch restrictions, but it is limited to the numpy/numpy repository.
- The [`linux_aarch64` task](https://github.com/numpy/numpy/blob/main/tools/ci/cirrus_general.yml#L14) will run for any trigger.
- The [`wheels_upload` task](https://github.com/numpy/numpy/blob/main/tools/ci/cirrus_general.yml#L49) will also run for any trigger. 
- If the trigger is a tag push then [`CIRRUS_TAG`](https://cirrus-ci.org/guide/writing-tasks/#environment-variables) should be defined. This should [cause `IS_PUSH` to be set to `true`](https://github.com/numpy/numpy/blob/28c81bc4b287255c4570a58e6d6bcd86600cd0b5/tools/ci/cirrus_general.yml#L76).  A debug step might be to echo `CIRRUS_TAG` to the log.
- You should be able to detect from the CI log if `IS_PUSH` is set because the upload environment variables [should be echoed](https://github.com/numpy/numpy/blob/main/tools/wheels/upload_wheels.sh#L17) to the log. One should also see `push and tag event'` being echoed. The first debug step is to look for those echoed variables in the CI log from a pushed tag. If `IS_PUSH` isn't set then some more detective work is required.
- The next step of debugging is to check whether the [`upload_wheels`](https://github.com/numpy/numpy/blob/main/tools/wheels/upload_wheels.sh#L34) function works properly. Given that the nightly upload works, I wonder if the `NUMPY_STAGING_UPLOAD_TOKEN` is correctly configured?

With CI debugging I normally do the majority of the legwork on my own fork. (changing `.cirrus.star` to run on andyfaff/numpy). This would allow you to make as many tags as you like, allowing you to verify all the way up to the upload step.

**Comment by charris** [comment]
> You should be able to detect from the CI log if IS_PUSH is set.

It wasn't, IIRC.

**Comment by charris** [comment]
I have several backports currently running, after they are merged I'll try pushing a tag and see what happens.

**Comment by andyfaff** [comment]
Experimenting on my fork [here](https://cirrus-ci.com/build/5404614040748032). I made a lightweight tag called `test`. One can use the webpage for the run to see debugging info for the run. I can see that `CIRRUS_TAG=test`.

**Comment by charris** [comment]
> CIRRUS_TAG=test

I was wondering if the tag name was incorrectly checked.

**Comment by andyfaff** [comment]
I should've started the tag with a `v`, but I think the tag name is being incorrectly checked. Having another go in https://cirrus-ci.com/build/5714865566777344. I think the test should be `[[ "$CIRRUS_TAG" == v* ]]` rather than `if [[ "$CIRRUS_TAG" == "v*" ]]`

**Comment by andyfaff** [comment]
Looks like the check was incorrect. I'll make a PR to fix it.

**Comment by charris** [comment]
@andyfaff Still a problem. A manual trigger failed with
```
Scheduling was delayed due to a concurrency limit on community tasks
```
Have you seen that before?

**Comment by andyfaff** [comment]
The manual build is running now. Do you have the link for the tag run?

**Comment by charris** [comment]
It says it is executing, but it isn't.  I suspect the error message is misleading and we may have exceeded some usage limit.

> Do you have the link for the tag run?

I tried rerunning those which ruined the logs. `IS_PUSH` was not set. I'm not sure which is the tag push, but you can take a look at https://cirrus-ci.com/task/5838955493457920.

**Comment by charris** [comment]
I wonder if the `mantenance/*` check is not working as expected. I haven't figured out what all the cirrus-ci symbols mean yet.

**Comment by andyfaff** [comment]
https://cirrus-ci.com/task/4693051170881536, it's definitely running

**Comment by charris** [comment]
OK, looks like "delayed" means "delayed" :).

**Comment by andyfaff** [comment]
This is the tag run: https://cirrus-ci.com/build/5067433136881664. it was aborted during the upload step. I think it was because a newer run was started, https://cirrus-ci.com/task/6599542930407424. did you merge a PR before the upload finished, or start the manual run before the upload finished?

**Comment by charris** [comment]
I did the rerun this morning the original task finished last night. It originally failed to upload as not a dispatch_event. IIRC, the rerun failed because it didn't rerun the builds and there were no wheels.

**Comment by charris** [comment]
The manual trigger uploaded to nightly, so that is a work around for the 1.24.0 release.

**Comment by andyfaff** [comment]
I think I know what happened.
The tag run is https://cirrus-ci.com/build/5067433136881664.
The CI script checks for: `[[ "$CIRRUS_TAG" == v* ]] && [[ "$CIRRUS_BRANCH" == maintenance* ]]`. i.e. if there is a tag event (CIRRUS_TAG is only defined when this happens) it has to begin with `v`. If I look at the CI environment variables on  then `CIRRUS_TAG=v1.24.0`, so far so good. The second condition says that `CIRRUS_BRANCH` has to start with `maintenance`. However, for the tag event the branch is `CIRRUS_BRANCH=v1.24.0`, so the `IS_PUSH` variable was not set.

The check would work if the tag was made and pushed on the `maintenance/v*` branch, but the tag appears to have occurred in some other way. 

Can you shed light on how the tagging process occurs?


--------------
The github wheels run has a mix of conditions for `IS_PUSH` to be set. The variable is only set if the sdist step has a condition:
```
      contains(github.event.pull_request.labels.*.name, '14 - Release'))) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && ( ! endsWith(github.ref, 'dev0')))
```
with the variable being set as:
```
      IS_PUSH: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
```
I don't know how to retrieve the github labels from a cirrus-ci run.

**Comment by andyfaff** [comment]
After a little bit of googling:
```
$ curl https://api.github.com/repos/numpy/numpy/issues/22813/labels
[
  {
    "id": 6359817,
    "node_id": "MDU6TGFiZWw2MzU5ODE3",
    "url": "https://api.github.com/repos/numpy/numpy/labels/14%20-%20Release",
    "name": "14 - Release",
    "color": "fef2c0",
    "default": false,
    "description": ""
  },
  {
    "id": 2506085335,
    "node_id": "MDU6TGFiZWwyNTA2MDg1MzM1",
    "url": "https://api.github.com/repos/numpy/numpy/labels/36%20-%20Build",
    "name": "36 - Build",
    "color": "fef2c0",
    "default": false,
    "description": "Build related PR"
  }
]
```
So I could possibly parse the output to figure out if a PR has a `14 - Release` label instead of doing the maintenance branch check.

**Comment by charris** [comment]
I tag the last commit in the branch and push it upstream:
```
$ git tag -a -s v1.24.0 -m"NumPy 1.24.0 release"
$ git push upstream v1.24.0
```

**Comment by andyfaff** [comment]
Last commit in which branch? In the PR branch or in the maintenance branch?

**Comment by charris** [comment]
I think the easiest solution is to not check for the branch. The only relevant tags pushed to main are of the form `v1.25.0.dev0`, so I think the tag check could be made more specific to ignore tags containing `dev0`. It wouldn't even be too bad if that tag did initiate an upload, but it should go to the nightly repository.

**Comment by charris** [comment]
> Last commit in which branch?

The maintenance branch.

**Comment by andyfaff** [comment]
It should be fairly simple to check that a strong doesn't end in dev0

**Comment by charris** [comment]
> This looks like a cirrus oddity where pushing the tag is like making a new branch and not just a new reference.

Or maybe it just checks if it is a push.

**Comment by andyfaff** [comment]
How about something like `[[ $CIRRUS_TAG == v* ]] && [[ $CIRRUS_TAG != *"dev0"* ]]`

**Comment by charris** [comment]
Works in my terminal :) It would be nice if we could do this more directly, but we would need more information on the cirrus environment.

**Comment by andyfaff** [comment]
> would be nice if we could do this more directly

We can check if there is a `14 - Release` label is [present on a PR](https://github.com/numpy/numpy/issues/22730#issuecomment-1356879884). What specifically did you want to check?

**Comment by charris** [comment]
If there were a way to simply determine the branch apart from the tag. My guess is that cirrus is just checks out the tag on push, so it is probably a lost cause. Might just add a comment to clarify things for future maintainers.

> We can check if there is a 14 - Release

Hmm, we could, but currently we just use that for release related so it might be confusing.  That said, the check on the tag name is probably more flexible and I'm happy with it. If we occasionally get an extra upload, and I doubt we will, it is not a big deal.

**Comment by andyfaff** [comment]
> f there were a way to simply determine the branch apart from the tag

That's not immediately apparent from the `CIRRUS_*` environment variables. There is a CIRRUS_BASE_BRANCH, but that's only set for a PR.
