### ISSUE TITLE
DOC: Improve 1.24.0 release notes on converting out-of-bound Python integers

### ISSUE THREAD

**Issue by adrianeboyd** [numpy/numpy#22733]
### Issue with current documentation:

The 1.24.0rc1/2 release notes appear to link to the wrong PR, which I think should be #22385 instead of #22393?

The examples suggesting the use of `np.array().astype()` should include more details about arrays of 64-bit integers related to #19146 because this behavior is very unexpected, e.g.:

```python
a1 = np.array([-1, 0], dtype=np.uint64)
assert a1[0] == np.iinfo(np.uint64).max
a2 = np.array([a1[0], 0]).astype(np.uint64)
assert a1[0] != a2[0]
```

For the case above there is a runtime warning that indicates that something has gone wrong, but many other cases lose precision without any warnings or errors:

```python
a1 = np.array([18194338103975822726, 0], dtype=np.uint64)
assert a1[0] == 18194338103975822726
a2 = np.array([a1[0], 0]).astype(np.uint64)
assert a1[0] != a2[0]
```

**Comment by mattip** [comment]
Hmm. The [rendered release note](https://numpy.org/devdocs/release/1.24.0-notes.html) seems empty. I thought we had it working automatically.

@charris

**Comment by charris** [comment]
@seberg The 1.24.0 documentation won't be available until it is released. The note in main was a place holder, the generated note is in the 2.24.x branch and any fixes should be against that branch. Looks like there was a typo in naming the fragment.

**Comment by seberg** [comment]
Thanks, I will look into fixing the link tomorrow and see if I can find a way to improve the docs.

@adrianeboyd are you hitting this with respect to the `-1` deprecation?  I agree the behavior is terrible and confusing since it goes via float64, I am just a bit surprised that it is super relevant w.r.t. to the specific deprecation.

**Comment by mattip** [comment]
> The 1.24.0 documentation won't be available until it is released. 

thanks @charris, sorry for the noise.

**Comment by adrianeboyd** [comment]
Thanks!

We use uint64 arrays to store mixed uint64 and int32 feature values. Something like this, with a separate header tracking the feature positions:

```
data = [
    [12943039165150086467, 3411606890003347522, 11901859001352538922, 1618900948208871284, 12646065887601541794],
    [15267657372422890137, 13927759927860985106, 15267657372422890137, 15308085513773655218, 12646065887601541794],
    [1, 0, 1, -2, -3],
    [1, -1, -1, -1, -1],
]
```

With the previous casting behavior, you could convert the whole array or any subpart to uint64 using the same generic conversion (or by assigning individual values into the array), without referring to the header or checking the values:

```python
a1 = np.array(data, dtype=np.uint64)
a2 = np.empty(a1.shape, dtype=np.uint64)
for i, row in enumerate(data):
    a2[i] = np.array(row, dtype=np.uint64)
```

With this change, it seems like the only generic option is to check and convert each value individually:

```python
a3 = np.empty(a1.shape, dtype=np.uint64)
for i, row in enumerate(data):
    for j, value in enumerate(row):
        a3[i, j] = np.array(value).astype(np.uint64)
```

My main point in terms of the release notes is that it was very surprising when the suggested change corrupted the uint64 values for what looked on the surface like unaffected uint64->uint64 conversions:

```diff
-np.array(data, dtype=np.uint64)
+np.array(data).astype(np.uint64)
```

(About the deprecation in general, it's not that I don't understand the reasoning and motivation, but I suspect it's going to be more breaking than expected, and not just for the occasional `-1`?)

**Comment by seberg** [comment]
Hmmm, slightly improved now, so going to close.  I am not sure it is actually ideal, or whether we want to reconsider the whole thing.

So happy to reopen (or a new issue), but I guess right now there is nothing clearly actionable.
