### ISSUE TITLE
DOC: hard-to-find seed requirements for `SeedSequence` and `BitGenerators`

### ISSUE THREAD

**Issue by chimaerase** [numpy/numpy#22745]
### Issue with current documentation:

`SeedSequence` documentation only mentions that the `entropy` parameter must be `{None, int, sequence[int]}`.  However, by default it does not accept a negative integer or specify any known upper bounds for int values (see tests below).

After digging, the only mention I found was deep in the documentation for `BitGenerator` (at present, not even directly linked from SeedSequence): "All of the provided BitGenerators will take an arbitrary-sized non-negative integer, or a list of such integers, as a seed".

```
>>> import numpy as np
>>> np.random.SeedSequence(np.iinfo(np.uint64).max+1)
SeedSequence(
    entropy=18446744073709551616,
)
>>> np.random.SeedSequence(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bit_generator.pyx", line 313, in numpy.random.bit_generator.SeedSequence.__init__
  File "bit_generator.pyx", line 387, in numpy.random.bit_generator.SeedSequence.get_assembled_entropy
  File "bit_generator.pyx", line 144, in numpy.random.bit_generator._coerce_to_uint32_array
  File "bit_generator.pyx", line 74, in numpy.random.bit_generator._int_to_uint32_array
ValueError: expected non-negative integer
```

### Idea or request for content:

Suggest propagating documentation for BitGenerator seed limits to SeedSequence, and maybe also to individual BitGenerators so it's more visible.

**Comment by adwiii** [comment]
The original issue appears to have been fixed in #22779.

I ended up here because the documentation [here](https://numpy.org/doc/stable/reference/random/generator.html) for `numpy.random.default_rng` says that `int` is allowed but does not propagate up this note on the requirement to be non-negative. I have opened #24991 to propagate the change.
