### ISSUE TITLE
DOC: api generation creates unused *.txt files in the include directory

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#22768]
### Issue with current documentation:

Commit 7be6aec11a from 2006 added generation of `include/numpy/multiarray_api.txt` and `include/numpy/ufunc_api.txt` from text marked with the `/*NUMPY_API` or `/*UFUNC_API` marker. These are not actually used anywhere, we have array.rst [rendered here](https://numpy.org/devdocs/reference/c-api/array.html) and ufunc.rst [rendered here](https://numpy.org/devdocs/reference/c-api/ufunc.html). Those pages are not very user-friendly, but that is another issue. 

### Idea or request for content:

We should either:
- delete the code to generate those unused files (the code was slightly modified after that commit)
- somehow incorporate the unused files in the array api/ufunc api documentation.

**Comment by rgommers** [comment]
+1 for deleting the codegen
