### ISSUE TITLE
created dtype has no columns

### ISSUE THREAD

**Issue by The1iAmNeo** [numpy/numpy#22765]
i am trying to do something where i slice and say i want a specific amount of rows and specific amount of columns but when creating a dtype array it is only 1 dimensional ... how do i make it so that it can be a shape like (n:5)

![image](https://user-images.githubusercontent.com/95321908/206745762-23e0be6a-1003-4ed1-9b2a-fd08a9428c54.png)

as you can see in the image i want to be able to get all the rows but just the first 2 columns but it wont work ... i even tried to add the labels to the columns section but it didn't work ... so i want the array to have rows instead of tuples all in one row ... like this 

![image](https://user-images.githubusercontent.com/95321908/206793518-64a22857-257f-44ba-b880-f5a03823703e.png)

**Comment by seberg** [comment]
dtype fields are not part of the arrays dimension.  They are indexable only on their own as `arr[field]` or `arr[[field1, field2]]` (generally, I would probably do that index first).

If you want a lot of things like this, you should probably look at dataframes, i.e. `pandas`.
