### ISSUE TITLE
Why does numpy use row-based data as opposed to column-based data?

### ISSUE THREAD

**Issue by PraxTube** [numpy/numpy#22780]
I am quite unsure if this is the right place to ask this question, so if there are any better places please point me towards them.

With that out of the way, what are the reasons numpy uses row-based data instead of column-based data?
I know that row-based data can be accessed faster from the CPU this way, thus increasing performance. Column-based data on the other hand would be more "mathematically correct". 

The performance would be reason alone to justify the convention, but I just wanted to know if there are any other reasons this convention is used (I am aware that not only numpy uses this convention, but that it is used in general, so I suppose another reason is that this follows convention of other libraries too).

**Comment by matthew-brett** [comment]
Could you say more about what you mean by:

> Column-based data on the other hand would be more "mathematically correct".

**Comment by rkern** [comment]
numpy and Python are built on C, which tends towards row-major semantics. Neither C nor Python have multidimensional arrays as native types, so in order for multidimensional arrays to play nicely with Python types, we want them to work a bit like lists of lists (etc., for however many dimensions). So for a 2-dim array `A`, we want `A[i, j] == A[i][j]`. Therefore, `A[i]` needs to refer to a row rather than a column.

As this is a question and no development action will be taken, I will close this issue. That doesn't need to stop the conversation, but there might be other forums where the conversation would be better suited.

**Comment by PraxTube** [comment]
Lets say we have $m$ vectors that are all element of $\mathbb{R}^n$. If we were to write all of the vectors in a matrix , then we would get a $\mathbb{R}^{n \times m}$ matrix, $n$ rows and $m$ columns, where each column is one of the $m$ vectors.

So in this case our data is stored column-wise. If we were to store them row-wise we would have a $\mathbb{R}^{m \times n}$. Of course both are equally valid, however most mathematicians would consider the former to be more common or "correct".

I realize that this may not be the best place to have started this conversation, but I wanted to get an answer from people that are working closely with numpy, which I may not get from asking somewhere like stack-overflow.

Thanks for the reply, that seems like a good point.

**Comment by PraxTube** [comment]
Okay so I actually have a follow-up question to that:

Suppose we have $m$ vectors in $R^{n}$ (or $R^{n,1}$) with $m \gg n$.

We want to transform these by a linear transformation (applying a Matrix $A^{k, n}$) and by a translation given by a vector $b$ in $R^{n}$. This is obviously faster with a 2D NumPy array then with a list of vectors.

When designing an API, would it be preferable to have a Matrix $V$ of shape `(n, m)` or `(m, n)`?

The former is what we are used to from mathematics. It is easy to apply $A$, simply write `A @ V`. Translating $V$ by $b$ is not that easy though, we would need to reshape vector $b$ in this case.

The latter makes it easy to translate $V$ by $b$ (thanks to NumPy broadcasting), but we wouldn't be able to write `A @ V` anymore, but would need to write something like `V @ A.T` instead.

It appears (from limited research) that SciPy, Scikit usually prefer the latter convention (NumPy itself doesn't seem too opinionated on this problem). Why is that?

**Comment by rkern** [comment]
In general, people like to have rows represent individual data items. It matches what we normally see in spreadsheets and other data tables. So that means `V[i]` represents the `i`th data item; we generally _want_ the dataset to be a sequence of data items. Note that I say "data item" rather than "vector". They are not necessarily vectors in a vector space yet. Individual columns may not even be numerical. The facility with which one can do linear algebra is a secondary concern.

**Comment by PraxTube** [comment]
So the fact that libraries like SciPy or Scikit use row-based data may not have anything to do with the mathematics but rather that it's a common convention of storing data items?

Then lets suppose I am writing a library that is purely mathematical and uses a lot of numpy. Would it be reasonable to use column-based data in this case (which at least mathematicians seem like the more intuitive method) or would the fact that the convention clashes with other libraries and common convention be reason enough to also use row-based data.

I know that there is no definite answer to this question because it is opinion-based, but I want to get some more perspective on this question.

**Comment by mattip** [comment]
I think you will find "mathematicians" to be a varied group. Statisticians are quite comfortable with rows representing observations and columns representing categories. Pure mathematicians would not be using NumPy in the first place, they would be using a symbolic library like SymPy.  You seem to be concentrating on a single parameter (the storage format) and not on how to solve a problem, so it is difficult to carry on a discussion. The issue itself has been closed. Is there something actionable we can help you with?

**Comment by matthew-brett** [comment]
Adapting Matti's point a little - I think you'll find that the *storage* order, specifically, very rarely comes up in code.  What does come up is the *index ordering*, and that comes up particularly when you are doing a reshape.   For example:

```python
>>> a = np.arange(12)
>>> b = np.reshape(a, (4, 3))
>>> b
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
>>> c = np.ravel(b)
>>> c
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
```

I'm not a mathematician - but is there a situation in real code where this would be a problem?    If so, you can ask for the row-major index ordering, like this:

```python
>>> np.ravel(b, order='F')
array([ 0,  3,  6,  9,  1,  4,  7, 10,  2,  5,  8, 11])
```

**Comment by PraxTube** [comment]
Thanks for pointing that out Mattip. Maybe I should make it a little bit more concrete what my problem is:

Suppose we want to create the coordinates of 2D grid for a geometry library. The coordinates could be stored in a numpy ndarray. There are two (reasonable) possibilities for the shape of this matrix: `(n, 2)` and `(2, n)`. The former is row-based, the latter column-based.

```python
>>> n = 3
>>> m = 2
>>> xx, yy = np.mgrid[0:n, 0:m]
>>> np.vstack([yy.ravel(), xx.ravel()]).T
array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 2],
       [1, 2]])
>>> np.vstack([yy.ravel(), xx.ravel()])
array([[0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 2, 2]])
```

The mathematicians I am working with would consider the column-based version to be more intuitive, because that's (at least how they) would write it in mathematics too.

So my question is: Would it be preferable to use shape `(n, 2)` or `(2, n)`? And then in general for the API of the library, would it be preferable to use row-based or column-based data?

**Comment by mattip** [comment]
> The mathematicians I am working with would consider the column-based version to be more intuitive, because that's (at least how they) would write it in mathematics too.

I would do it whatever way makes sense to you and document it. NumPy can easily work either way, it is entirely up to you.

**Comment by Offshore132** [comment]
@rkern https://alfie-signalr-hub.github.io/tort/
