### ISSUE TITLE
BUG: invalid value encountered in rint/floor/ceil/trunc on X86(SSE2) and ARMHF(NEON)

### ISSUE THREAD

**Issue by seiko2plus** [numpy/numpy#22797]
### Describe the issue:

Passing any nonfinite float32 value to (rint, floor, ceil, trunc) will raise an invalid FP exception if SSE41 isn't enabled or not supported by the CPU (old x86). The same issue also exists on armhf.

Another case that appeared after #22750, passing float64 qNaN to (rint, floor, ceil, trunc) will also raise an invalid FP exception. 

### Reproduce the code example:

```python
export NPY_DISABLE_CPU_FEATURES="SSE41"
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.seterr(all='raise')
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>> np.trunc(np.float32(-np.inf))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: invalid value encountered in trunc
>>> np.trunc(np.float32(np.nan))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: invalid value encountered in trunc
>>> np.trunc(np.float32(np.inf))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: invalid value encountered in trunc
>>> np.rint(np.float32(np.inf))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: invalid value encountered in rint
>>> np.ceil(np.float32(np.inf))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: invalid value encountered in ceil
>>> np.floor(np.float32(np.inf))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: invalid value encountered in floor
>>>
```

### NumPy/Python version information:

1.23.5 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]

edit:armhf

**Comment by seberg** [comment]
I am starting to wonder whether SSE2 without SSE41 is so rare these days that for some corner cases like this we can get away with accepting a few bad warnings.
Although, I suppose if the fix is easy enough it is better to just apply it.

**Comment by seiko2plus** [comment]
> I am starting to wonder whether SSE2 without SSE41

I had the same thoughts. maybe removing the support single/double optimizations for SSE2 would also be a good choice also for armhf/neon and leave only keep integer SIMD operations. It should reduce the maintenance burden.

> Although, I suppose if the fix is easy enough it is better to just apply it.

it should be fixed by #22771

**Comment by seberg** [comment]
If SSE2 is a significand mainatenence burdon, I do suspect we can consider removing it (so long almost all CPUs have a newer vectorization available).  I guess FPEs are just one issue of many.

**Comment by mattip** [comment]
The "Core2 Q6700" CPU from the original issue was launched in 2007. I think most CPUs [released after 2008](https://en.wikipedia.org/wiki/SSE4#Supporting_CPUs) will support SSE41 (Intel, AMD, and VIA). Maybe it is OK to drop support for optimizations on such old processors? I doubt they are being used in computationally-heavy tasks.

**Comment by charris** [comment]
> Maybe it is OK to drop support for optimizations on such old processors

Works for me, and I have a ten year old Intel I5.
