### ISSUE TITLE
BUG: Importing the numpy c-extensions failed.

### ISSUE THREAD

**Issue by krr27** [numpy/numpy#22808]
### Describe the issue:

Running the following command (in Python 3.9.14):
import numpy as np

Produced an error message that included the following (the complete error message is provided under "Error message:", below):
...
Importing the numpy c-extensions failed.
...
Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

### Reproduce the code example:

```python
import numpy as np
```

### Error message:

```shell
>>> import numpy as np
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.9 from "/usr/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### NumPy/Python version information:

krr@ASEC_XPS_1:~/PX4-Autopilot$ import sys, numpy; print(numpy.__version__, sys.version)
-bash: syntax error near unexpected token `numpy.__version__,'

### Context for the issue:

I am no longer able to build the PX4 firmware, which is blocking the critical path of my development project.

**Comment by charris** [comment]
This is invariably an installation problem. What platform/os are you running on?

**Comment by krr27** [comment]
Ubuntu 20.04.5 LTS, running on WSL (Windows 11)

**Comment by charris** [comment]
I don't use Windows, but I think this has turned up before, something about needing to install separately for windows and WSL.

**Comment by seberg** [comment]
@krr27 how did you install Python and NumPy?  The error sounds like its not finding the compiled parts of NumPy, something to do with the naming of the files not being as expected.  I am not quite sure why this would happen here since it would normally be something like NumPy being compiled for a different system.

**Comment by krr27** [comment]
I don't recall how I installed them. They may have been installed as part of the Ubuntu installation, which I think was part of the Windows WSL set up process.

Does the following answer the question about the naming of files?:

krr@ASEC_XPS_1:/usr/lib/python3/dist-packages/numpy$ ls -lsaR | grep "numpy"
   8 -rw-r--r--  1 root root    7470 Aug 30  2019 generate_numpy_api.py
  8 -rw-r--r-- 1 root root   6338 May 29  2022 generate_numpy_api.cpython-38.pyc
4 drwxr-xr-x 3 root root 4096 May 29  2022 numpy
./core/include/numpy:
 4 -rw-r--r-- 1 root root  1010 Feb 18  2020 _numpyconfig.h
 4 -rw-r--r-- 1 root root  1207 Aug 30  2019 numpyconfig.h
./core/include/numpy/random:
  4 -rw-r--r--  1 root root   700 Jun 15  2019 numpy_distribution.py
 4 -rw-r--r-- 1 root root   869 May 29  2022 numpy_distribution.cpython-38.pyc
 4 -rw-r--r--  1 root root   647 Aug 30  2019 test_numpy_version.py
 4 -rw-r--r-- 1 root root   687 May 29  2022 test_numpy_version.cpython-38.pyc

I tried the following, as suggested by the error message:

krr@ASEC_XPS_1:~$ sudo pip3 install --user numpy
[sudo] password for krr:
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.17.4)

I also tried uninstalling numpy first, as follows:

krr@ASEC_XPS_1:~$ sudo pip3 uninstall numpy
Found existing installation: numpy 1.17.4
Not uninstalling numpy at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'numpy'. No files were found to uninstall.

**Comment by seberg** [comment]
The NumPy install looks like it comes from Ubuntu, yes.  But the Python does not look compatible?  That Ubuntu ships with [`python3.8`](https://packages.ubuntu.com/focal/python3) not 3.9.  I suspect running `/usr/bin/python3.8` will work, but no idea why you have a 3.9 there to begin with, must be some manual install?

**Comment by krr27** [comment]
You were right. python3.9 was causing the problem. I still had python3.8 installed, but the link python3 was pointing to python3.9. 
I changed python3 to point to python3.8, and that fixed the problem.
Thanks for the help!
