### ISSUE TITLE
Project size to large error on wheel upload to PyPI

### ISSUE THREAD

**Issue by charris** [numpy/numpy#22817]
```
Uploading numpy-1.24.0.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB • 00:14 • 735.2 kB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                                         
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                
         Project size too large. Limit for project 'numpy' total size is 30 GB. See https://pypi.org/help/#project-size-limit 
```
Following the link, we can either remove some releases or ask for a large limit. I think we could begin by removing all the rc releases.

@rgommers Because SciPy is also likely to hit this limit in the future.

**Comment by charris** [comment]
> we can either remove some releases or ask for a large limit.

Seems like they would like us to do both :) Looks like Scikit_image also hit this limit at 10GB and requested a larger limit.

**Comment by rgommers** [comment]
Let's do both. +1 for removing more RC releases now. I tend to do that once in a while anyway for older releases, no one has ever complained about it.

SciPy is also close, I can ask for a bump for both.

**Comment by charris** [comment]
I deleted a bunch of rc files which provided about 5GB of free space. I note that there are a bunch of early releases with _no_ files. I'm inclined to leave those just for the timeline. I suggest keeping the rc files for the last two releases.

**Comment by rgommers** [comment]
That sounds good to me.

**Comment by rgommers** [comment]
I cleaned up some SciPy pre-releases as well (FYI @tylerjereddy). And filed the requests:
- NumPy: https://github.com/pypa/pypi-support/issues/2480
- SciPy: https://github.com/pypa/pypi-support/issues/2479

**Comment by tylerjereddy** [comment]
Thanks Ralf
