### ISSUE TITLE
BUG: wrong dtype computing with 0-D teensor

### ISSUE THREAD

**Issue by HydrogenSulfate** [numpy/numpy#22823]
### Describe the issue:

I guess result dtype should be same as input dtype, but code below is not.
```python
import numpy as np

x = np.array([0.04399043, -0.26885903])
y = np.array([-0.99222845, -0.1244299])
x = x.astype("float32")
y = y.astype("float32")
z = np.dot(x, y)
print(z.ndim) # 0
print(z.shape) # ()
print(z.dtype) # float32
print((z**2).dtype) # float64
```

and when `z` is reshaped to `[1]`, dtype is consistent with input as expected
```python
import numpy as np

x = np.array([0.04399043, -0.26885903])
y = np.array([-0.99222845, -0.1244299])
x = x.astype("float32")
y = y.astype("float32")
z = np.dot(x, y).reshape([1]) # reshape to [1]
print(z.ndim) # 1
print(z.shape) # (1,)
print(z.dtype) # float32
print((z**2).dtype) # float32
``` 

### Reproduce the code example:

```python
import numpy as np

x = np.array([0.04399043, -0.26885903])
y = np.array([-0.99222845, -0.1244299])
x = x.astype("float32")
y = y.astype("float32")
z = np.dot(x, y)
print(z.ndim) # 0
print(z.shape) # ()
print(z.dtype) # float32
print((z**2).dtype) # float64
```

```python
import numpy as np

x = np.array([0.04399043, -0.26885903])
y = np.array([-0.99222845, -0.1244299])
x = x.astype("float32")
y = y.astype("float32")
z = np.dot(x, y).reshape([1]) # reshape to [1]
print(z.ndim)
print(z.shape)
print(z.dtype)
print((z**2).dtype)
```

### NumPy/Python version information:

1.21.6 could reproduce this BUG.

**Comment by Pranay144** [comment]
you could use (z**2).astype("float32").

`python
import numpy as np

x = np.array([0.04399043, -0.26885903])
y = np.array([-0.99222845, -0.1244299])
x = x.astype("float32")
y = y.astype("float32")
z = np.dot(x, y)
print(z.ndim) # 0
print(z.shape) # ()
print(z.dtype) # float32
print(((z**2).astype("float32")).dtype) #float32`

**Comment by Pranay144** [comment]
you could use (z**2).astype("float32").

```python
import numpy as np

x = np.array([0.04399043, -0.26885903])
y = np.array([-0.99222845, -0.1244299])

z = np.dot(x, y)
print(z.ndim) # 0
print(z.shape) # ()
print(z.dtype) # float32
print(((z**2).astype("float32")).dtype) #float32
```

**Comment by HydrogenSulfate** [comment]
> you could use (z**2).astype("float32").
> 
> ```python
> import numpy as np
> 
> x = np.array([0.04399043, -0.26885903])
> y = np.array([-0.99222845, -0.1244299])
> 
> z = np.dot(x, y)
> print(z.ndim) # 0
> print(z.shape) # ()
> print(z.dtype) # float32
> print(((z**2).astype("float32")).dtype) #float32
> ```

thanks, but it still remains a type BUG for numpy😥

**Comment by eric-wieser** [comment]
You're not working with a "0-D teensor", you're working with a scalar. If you cast to a 0d array, then things work as you expected:
```python
import numpy as np

x = np.array([0.04399043, -0.26885903])
y = np.array([-0.99222845, -0.1244299])
x = x.astype("float32")
y = y.astype("float32")

z = np.dot(x, y)[...]
print(z.ndim) # 0
print(z.shape) # ()
print(z.dtype) # float32
print((z**2).dtype) # float32
```

**Comment by HydrogenSulfate** [comment]
> You're not working with a "0-D teensor", you're working with a scalar. If you cast to a 0d array, then things work as you expected:
> 
> ```python
> import numpy as np
> 
> x = np.array([0.04399043, -0.26885903])
> y = np.array([-0.99222845, -0.1244299])
> x = x.astype("float32")
> y = y.astype("float32")
> 
> z = np.dot(x, y)[...]
> print(z.ndim) # 0
> print(z.shape) # ()
> print(z.dtype) # float32
> print((z**2).dtype) # float32
> ```

I'm curious about why 0-D tensor is not considered scalar in numpy?

**Comment by seberg** [comment]
NumPy is unfortunately very unclear and not logical about the definition of what it considers a "NumPy scalar" and a 0-D "scalar array".

In general, your observation is unfortunately expected.  `arr**2` for 0-D arrays is (as Eric pointed out) an outlier where this does not happen.

The problem is that NumPy tries to be smart about scalars upcasting and arrays not, but *because* NumPy doesn't distinguish between 0-D arrays and Python scalars this all fails.

[NEP 50](https://numpy.org/neps/nep-0050-scalar-promotion.html) is the attempt to eventually get away from that, you can even try it (requires a new NumPy version):
```
# clearly will go away and might have a few very corner cases
# not 100% working yet:
np._set_promotion_state("weak")

# Your example will give the expected result now
```
In general, the observation is in line with gh-10322, so going to close.  But happy to follow-up!

(I admit, the fact that Eric's solution works is independent of that, it uses the "array" logic, even though the array is 0-D, which is not typical)

**Comment by eric-wieser** [comment]
I was a bit surprised that my solution worked, I came to this issue expecting it to be about that exact spelling not working!
