### ISSUE TITLE
np.logical_xor.accumulate fails on 1.24 on mac

### ISSUE THREAD

**Issue by knutdrand** [numpy/numpy#22841]
### Describe the issue:

.Accumulate on logical_xor gives wrong result on newest version. I suspect the same for bitwise_xor.

### Reproduce the code example:

```python
import numpy as np

a = np.array([False, False,  True, False, False, False, False,  True, False, False,  True, False, False,  True, False, False, False, False, False, False])
np.logical_xor.accumulate(a)
array([False, False,  True,  True, False, False, False,  True,  True,
       False,  True,  True, False,  True,  True, False, False, False,
       False, False])
# Should be [False, False,  True,  True, True, True, True, False,,,,]
```

### NumPy/Python version information:

numpy=1.24
python 3.8, 
mac version 12.5.1

**Comment by seberg** [comment]
Again ping @seiko2plus and maybe @Developer-Ecosystem-Engineering.  This looks like probably the identical issue as gh-22840 (just now slightly different with the reduction).  Presumably introduced by gh-22167.

With a view (although I am not sure how important it is directly without digging in):
```
>>> a = np.array([False, False,  True, False, False, False, False,  True, False, False,  True, False, False,  True, False, False, False, False, False, False])
>>> np.logical_xor.accumulate(a).view(np.uint8)
array([  0,   0, 254, 254,   0,   0,   0, 254, 254,   0, 254, 254,   0,
       254, 254,   0,   0,   0,   0,   0], dtype=uint8)
```

**Comment by Developer-Ecosystem-Engineering** [comment]
Hi @seberg, 

Appears related to https://github.com/numpy/numpy/pull/21483. The aliases for `BOOL_logical_xor` was `BOOL_not_equal`, which was subsequently changed

**Comment by seiko2plus** [comment]
Memory overlaps! The comparison loops of all data types are free of overlap checking:

https://github.com/numpy/numpy/blob/0d1bb8e42228776dc8d35bdcfacf2ff3af366ade/numpy/core/src/umath/fast_loop_macros.h#L381-L392

https://github.com/numpy/numpy/blob/0d1bb8e42228776dc8d35bdcfacf2ff3af366ade/numpy/core/src/umath/loops_comparison.dispatch.c.src#L315-L328

```Diff
+    // multiply by sizeof(@type@) due to SIMD unroll
     /* argument one scalar */
-    if (IS_BLOCKABLE_BINARY_SCALAR1_BOOL(sizeof(@type@), NPY_SIMD_WIDTH)) {
+    if (IS_BLOCKABLE_BINARY_SCALAR1(sizeof(@type@), NPY_SIMD_WIDTH*sizeof(@type@))) {
         simd_binary_scalar1_@kind@_@sfx@(args, dimensions[0]);
         return;
     }
     /* argument two scalar */
-    else if (IS_BLOCKABLE_BINARY_SCALAR2_BOOL(sizeof(@type@), NPY_SIMD_WIDTH)) {
+    else if (IS_BLOCKABLE_BINARY_SCALAR2(sizeof(@type@), NPY_SIMD_WIDTH*sizeof(@type@))) {
         simd_binary_scalar2_@kind@_@sfx@(args, dimensions[0]);
         return;
     }
-    else if (IS_BLOCKABLE_BINARY_BOOL(sizeof(@type@), NPY_SIMD_WIDTH)) {
+    else if (IS_BLOCKABLE_BINARY(sizeof(@type@), NPY_SIMD_WIDTH*sizeof(@type@))) {
         simd_binary_@kind@_@sfx@(args, dimensions[0]);
         return;
     }
```
