### ISSUE TITLE
REGR: Comparing boolean array to True returns incorrect uint8 value with more than 32 values on 1.24.0

### ISSUE THREAD

**Issue by phofl** [numpy/numpy#22840]
### Describe the issue:

When having an array with more than 31 boolean values and doing an equality comparison the underlying value seems off. Applying ``view("uint8")`` to the result returns 254 for every element instead of one. It works fine if ``n<= 31``

Discovered in https://github.com/pandas-dev/pandas/issues/50347

### Reproduce the code example:

```python
import numpy as np

n = 32
na = np.array([True] * n)
(na == True).view("uint8")
```

### Error message:

```shell
[254 254 254 254 254 254 254 254 254 254 254 254 254 254 254 254 254 254
 254 254 254 254 254 254 254 254 254 254 254 254 254 254]
```

### NumPy/Python version information:

1.24.0 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:06) 
[Clang 14.0.6 ]

### Context for the issue:

This seems off to me

**Comment by seberg** [comment]
While we can't control things if people write other values by using `arr.view(bool)`, NumPy should try to fill arrays with the value 1, I expect.

@seiko2plus this looks like it was introduced in gh-22167.

**Comment by Developer-Ecosystem-Engineering** [comment]
`vbicq_u8` and `vornq_u8` args appear swapped

**Comment by charris** [comment]
> I am not sure we should be required to ensure 1/0 values

I like it, myself. It does sometimes make things a bit tricky.

**Comment by seiko2plus** [comment]
> vbicq_u8 and vornq_u8 args appear swapped

my bad, that's true:

https://github.com/numpy/numpy/blob/28329b2aadf87d57371fefe606df6923ada80b93/numpy/core/src/umath/loops_comparison.dispatch.c.src#L237

```diff
-        npyv_store_u8(dst, npyv_andc_u8(npyv_cvt_u8_b8(c), truemask));
+        npyv_store_u8(dst, npyv_andc_u8(truemask, npyv_cvt_u8_b8(c)));
     }
 
     for (; len > 0; --len, ++src1, ++src2, ++dst) {
@@ -258,7 +258,7 @@ static void simd_binary_scalar1_@kind@_b8(char **args, npy_intp len)
     for (; len >= vstep; len -= vstep, src += vstep, dst += vstep) {
-        npyv_store_u8(dst, npyv_andc_u8(npyv_cvt_u8_b8(c), truemask));
+        npyv_store_u8(dst, npyv_andc_u8(truemask, npyv_cvt_u8_b8(c)));
     }
 
     for (; len > 0; --len, ++src, ++dst) {
@@ -281,7 +281,7 @@ static void simd_binary_scalar2_@kind@_b8(char **args, npy_intp len)
     for (; len >= vstep; len -= vstep, src += vstep, dst += vstep) {
-        npyv_store_u8(dst, npyv_andc_u8(npyv_cvt_u8_b8(c), truemask));
+        npyv_store_u8(dst, npyv_andc_u8(truemask, npyv_cvt_u8_b8(c)));
     }
```

**Comment by seiko2plus** [comment]
since #21483
