### ISSUE TITLE
BUG: Mis-handling of NaN in power().

### ISSUE THREAD

**Issue by xkszltl** [numpy/numpy#22844]
### Describe the issue:

NaN is supposed to be very infective.
Anything compute with NaN should result in NaN.
But currently `np.power()` think `nan^0=1`.

### Reproduce the code example:

```python
# macOS
# python3 --version && python3 -m pip show numpy && python3 -c 'import numpy as np; print(np.power(np.nan, 0.0))'
Python 3.10.8
Name: numpy
Version: 1.23.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/local/lib/python3.10/site-packages
Requires: 
Required-by: imagecodecs, imageio, opencv-python, rawpy, scipy, tifffile
1.0

# Debian 11
# python3 --version && python3 -m pip show numpy && python3 -c 'import numpy as np; print(np.power(np.nan, 0.0))'
Python 3.9.2
Name: numpy
Version: 1.23.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/local/lib/python3.9/dist-packages
Requires: 
Required-by: keras2onnx, onnx, onnxconverter-common, onnxmltools, onnxruntime, opencv-python, rawpy, scikit-learn, scipy, skl2onnx
1.0

# CentOS 7
# python3 --version && python3 -m pip show numpy && python3 -c 'import numpy as np; print(np.power(np.nan, 0.0))'
Python 3.6.8
Name: numpy
Version: 1.19.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/local/lib64/python3.6/site-packages
Requires: 
Required-by: keras2onnx, onnx, onnxconverter-common, onnxmltools, onnxruntime, opencv-python, rawpy, scikit-learn, scipy, skl2onnx, torchvision, transformers
1.0

# CentOS 7 with SCL
# scl enable rh-python38 "python3 --version && python3 -m pip show numpy && python3 -c 'import numpy as np; print(np.power(np.nan, 0.0))'"
Python 3.8.13
Name: numpy
Version: 1.23.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /home/xkszltl/.local/lib/python3.8/site-packages
Requires: 
Required-by: keras2onnx, onnx, onnxconverter-common, onnxmltools, opencv-python, rawpy, scikit-learn, scipy, skl2onnx
1.0
```

### NumPy/Python version information:

- numpy 1.23.5 and python 3.10.8, macOS
- numpy 1.23.4 and python 3.9, Debian 11
- numpy 1.23.4 and python 3.8, CentOS 7
- numpy 1.19 and python 3.6, CentOS 7

Not version-specific.

This has been an issue for long, someone filed here originally but not very conclusive.
- https://github.com/numpy/numpy/issues/8931

It also mentioned platform/impl dependent, but at least that's not what I found.

**Comment by xkszltl** [comment]
Python itself may have made the same mistake:
```
# python3 --version && python3 -m pip show numpy && python3 -c 'import math; import numpy as np; print(np.power(np.nan, 0.0)); print(np.nan ** 0.0); print(math.nan ** 0.0)'
Python 3.9.2
Name: numpy
Version: 1.23.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/local/lib/python3.9/dist-packages
Requires: 
Required-by: keras2onnx, onnx, onnxconverter-common, onnxmltools, onnxruntime, opencv-python, rawpy, scikit-learn, scipy, skl2onnx
1.0
1.0
1.0
```

**Comment by seberg** [comment]
Thanks for the report, but that seems all correct.  The correct result is given for example [here](https://en.cppreference.com/w/c/numeric/math/pow) as defined by the C99 standard which follows the IEEE/ISO standard.

The reasoning is that for *any* number the result is 1 and thus it can also be defined for NaN itself.  This is a rare exception where NaN can actually vanish.

If we would return anything but 1 for `nan**0` then this _would_ be a bug (although usually in some system math library).  I believe this is what the old issue is about, but as it is very old, I will close it... chances are no systems are affected anymore.

I suspect there are cases where other usage of NaN, maybe "missing value", would be better served by propagating it, but I doubt there is a great reason to break with the C99/IEEE standard here.

**Comment by xkszltl** [comment]
Thanks @seberg for explanation, sounds good if it's IEEE-compliant.

> The reasoning is that for any number the result is 1 and thus it can also be defined for NaN itself. This is a rare exception where NaN can actually vanish.

Regarding the wording though, I guess "any number" should not be applied to "not a number".
