### ISSUE TITLE
BUG: (main branch only; 1.24.0 fine) bizzare boolean product issue

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#22845]
I did see a number of `bool_` comparison related issues open, but they seem to be fine here for NumPy `1.24.0`, while in my case it is the `main` branch that is a problem and the stable release is working just fine.

I've been looking at some of the failures in SciPy + NumPy `main` branch after the recent release (which confusingly seems to be named/versioned `1.24.0.dev0+1413.gca2575655` in my tests, but clearly causes a number of issues in https://github.com/scipy/scipy/issues/17630#issuecomment-1358008148). Before deciding to release the next RC for SciPy `1.10.0` I wanted to drill down on one of the test failures to make sure I couldn't just easily shim around these, but it looks like this stuff is going to be too tricky because there are tons of them. Maybe not so serious since it just on the unreleased `main` branch so perhaps I'll move forward for now.

Here is a specific reproducer with `*.npy` files available from `np.save` in this tarball:  [arrays.tar.gz](https://github.com/numpy/numpy/files/10273085/arrays.tar.gz)

```python
import numpy as np

print("np.__version__:", np.__version__)

with open("q.npy", "rb") as q_file:
    q = np.load(q_file)

with open("r.npy", "rb") as r_file:
    r = np.load(r_file)

print("q, q.shape, q.dtype:", q, q.shape, q.dtype)
print("r, r.shape, r.dtype:", r, r.shape, r.dtype)

print("q * r:", q * r)
```

The results from `main` and `1.24.0`, respectively, follow:

```
np.__version__: 1.24.0.dev0+1413.gca2575655
q, q.shape, q.dtype: [ True False False ... False False False] (10000,) bool
r, r.shape, r.dtype: [ True  True  True ...  True  True  True] (10000,) bool
q * r: [False False False ... False False False]
```

```
np.__version__: 1.24.0
q, q.shape, q.dtype: [ True False False ... False False False] (10000,) bool
r, r.shape, r.dtype: [ True  True  True ...  True  True  True] (10000,) bool
q * r: [ True False False ... False False False]
```

If you focus on the first element in the result array, the stable release looks much more sensible. 

This manifested as a single (first) element difference in the expected value of the test result for `scipy/stats/tests/test_sampling.py::TestDiscreteGuideTable::test_ppf[u0]`. In fact, the actual value is just fine, but that means `stats.binom.ppf(u, n, p)` may be broken with NumPy `main` at the moment (cc: @mdhaber @tupui ), and naturally these kinds of issues seem to cascade around in a way that I probably can't patch manually, so I'll probably wait for some fixes in NumPy if you agree this is a problem.

**Comment by charris** [comment]
> `1.24.0.dev0+1413.gca2575655`

Looks like you need to pull tags, main should have `1.25.0.dev0*`

**Comment by tylerjereddy** [comment]
I did a `git bisect`:

```
93cbbbef2318eb9a5478c846a60a55b382e4c60d is the first bad commit
commit 93cbbbef2318eb9a5478c846a60a55b382e4c60d
Author: Developer-Ecosystem-Engineering <65677710+Developer-Ecosystem-Engineering@users.noreply.github.com>
Date:   Tue Aug 23 12:44:35 2022 -0700

    ENH: Add SIMD versions of bool logical_and, logical_or, logical_not and absolute
    
    NumPy has SIMD versions of BOOL `logical_and`, `logical_or`, `logical_not`, and `absolute` for SSE2.  The changes here replace that implementation with one that uses their universal intrinsics.  This allows other architectures to have SIMD versions of the functions too.
    
    BOOL `logical_and` and `logical_or` are particularly important for NumPy as that's how  `np.any()` / `np.all()` are implemented.

 .gitignore                                        |    1 +
 numpy/core/code_generators/generate_umath.py      |    4 +
 numpy/core/setup.py                               |    1 +
 numpy/core/setup.py.orig                          | 1173 +++++++++++++++++++++
 numpy/core/src/umath/loops.c.src                  |   92 --
 numpy/core/src/umath/loops.h.src                  |   12 +-
 numpy/core/src/umath/loops_logical.dispatch.c.src |  427 ++++++++
 numpy/core/src/umath/simd.inc.src                 |  211 ----
 8 files changed, 1614 insertions(+), 307 deletions(-)
 create mode 100644 numpy/core/setup.py.orig
 create mode 100644 numpy/core/src/umath/loops_logical.dispatch.c.src
```

**Comment by tylerjereddy** [comment]
That's SIMD stuff, so I'll leave it to the pros I think.

**Comment by Developer-Ecosystem-Engineering** [comment]
Thank you @tylerjereddy, taking a look.

**Comment by mattip** [comment]
@tylerjereddy could you show the result of `numpy.show_runtime()` on that machine?

**Comment by tylerjereddy** [comment]
I think one of the recent (last 24 hours) SIMD fixes may have helped here. The SciPy test seems to have started passing. The "corrupted" array came from a SciPy line that did:

`bool_array == bool_array` for 10,000 elements. Maybe this: https://github.com/numpy/numpy/pull/22846

Let me check real quick

**Comment by tylerjereddy** [comment]
Ok, not only is this test fixed by the commit in gh-22846, but now the entire SciPy testsuite on the release branch is passing with NumPy `main`, so it may very well have been the case that broken large bool mask comparisons were wreaking havoc all over the place.

One thing I can't quite tell is if the current NumPy testsuite + combination of intrinsic options available on CI hardware are sufficient to guard against such regressions in the future. I'll leave that for SIMD folks to decide.

**Comment by seberg** [comment]
Thanks for the nice digging!  What is probably left here is to investigate whether the `logical_and` loop gives bad results if the boolean has weird values when cast to `uint8`.  Because that is probably what is happning.

**Comment by Developer-Ecosystem-Engineering** [comment]
Should be resolved via https://github.com/numpy/numpy/pull/22861
