### ISSUE TITLE
BUG: histogram(x, bins='auto') fails for unknown reason on a simple input dataset

### ISSUE THREAD

**Issue by Alexander-Serov** [numpy/numpy#22854]
### Describe the issue:

A simple code snippet below calculating bins for a given input fails while trying to allocate 12.7 PiB of RAM. Probably related to my floats precision, but is definitely not the expected result.

I would be most grateful if anyone could suggest a workaround while this bug is being fixed.

### Reproduce the code example:

```python
import numpy as np
x = np.array([6.3,
 6.3,
 7.399999999999999,
 7.399999999999999,
 7.399999999999999,
 7.399999999999999,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.4,
 7.407142857142857,
 7.407142857142857,
 7.4125,
 7.4125])
np.histogram(x, density=True, bins="auto")
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/user/miniforge3/envs/clients/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-f76ea541d063>", line 25, in <module>
    np.histogram(x, density=True, bins="auto")
  File "<__array_function__ internals>", line 180, in histogram
  File "/Users/user/miniforge3/envs/clients/lib/python3.8/site-packages/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/Users/user/miniforge3/envs/clients/lib/python3.8/site-packages/numpy/lib/histograms.py", line 446, in _get_bin_edges
    bin_edges = np.linspace(
  File "<__array_function__ internals>", line 180, in linspace
  File "/Users/user/miniforge3/envs/clients/lib/python3.8/site-packages/numpy/core/function_base.py", line 135, in linspace
    y = _nx.arange(0, num, dtype=dt).reshape((-1,) + (1,) * ndim(delta))
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 12.7 PiB for an array with shape (1781062197026280,) and data type float64
```

### NumPy/Python version information:

1.23.3 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:06) 
[Clang 14.0.6 ]

**Comment by mwaskom** [comment]
This is a result of applying the [Freedman-Diaconis](https://numpy.org/devdocs/reference/generated/numpy.histogram_bin_edges.html) rule of thumb to the dataset:

```python
iqr = np.diff(np.percentile(x, [25, 75])).item()
binwidth = 2 * iqr / len(x) ** (1 / 3)
np.ptp(x) / binwidth
```
```
1781062197026278.2
```

There's been some previous discussion about the non-robustness of the "auto" rule here: https://github.com/numpy/numpy/issues/15569

**Comment by Alexander-Serov** [comment]
Indeed, thank you! I haven't seen that this problem has been reported before. Will be following the main discussion then!

**Comment by rossbar** [comment]
This is a known issue with the heuristic-based bin estimators, see e.g. #10297 and #11879 (among others). I'm going to go ahead and close this as duplicate to prevent the discussion from diffusing further!
