### ISSUE TITLE
BUG: FreeBSD issue with `csinl` in 1.24

### ISSUE THREAD

**Issue by oscargus** [numpy/numpy#22850]
### Describe the issue:

It seems like 1.24 requires `csinl`, which FreeBSD doesn't support out of the box, see https://wiki.freebsd.org/Numerics

### Reproduce the code example:

I do not really know where it comes from. It became an issue running the Matplotlib CI on FreeBSD (and is readily solved by restricting to numpy<1.24).

Edit: this is a runtime issue. It compiles fine, but then, upon loading(?) it errors out as it cannot find `csinl`.

### NumPy/Python version information:

1.24

### Context for the issue:

I understand that this may not be a highly prioritized issue, but thought it was worth reporting in case it can be solved in an easy way. (And to some extent it should probably be solved in FreeBSD...)

**Comment by rgommers** [comment]
@oscargus can you please add the full traceback you are seeing?

**Comment by seberg** [comment]
It isn't immediately clear to me which of the cleanup npy_math cleanup PR removed the relevant fallback, seems likely that fallback was just a fallback to double-precision anyway.

**Comment by rgommers** [comment]
FreeBSD is missing a longer list of `complex long double` C99 functions, documented in https://wiki.freebsd.org/Numerics. Quote _"A major focus of ongoing work is on implementing the remaining long double and complex functions specified by the C11 standard but not yet present in libm."_

So we should revive all the missing ones .... sigh
