### ISSUE TITLE
BUG: `numpy.isin` does not function correctly with two arrays with different integer type

### ISSUE THREAD

**Issue by TonyXiang8787** [numpy/numpy#22877]
### Describe the issue:

The function `numpy.isin` sometimes returns the wrong answer, if the integer type of the two arrays (to be compared) are not the same.

The example below shows a `int8` array with one zero and a `int64` array with two values. It should return one `True`. However, it returns `False`.

### Reproduce the code example:

```python
>>> import numpy as np
>>> np.isin(np.zeros(1, dtype=np.int8), np.array([-128, 0], dtype=np.int64), kind='table')
array([False])
```

### Runtime information:

Numpy version
```
>>> print(numpy.__version__)
1.24.0
```

Sys version
```
>>> print(sys.version)
3.11.1 (main, Dec  7 2022, 01:11:34) [GCC 11.3.0]
```

Numpy runtime
```
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'PATH_DELETED_DUE_TO_PRIVACY/.venv/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
```

### Context for the issue:

The problem seems to only occur in version 1.24.

**Comment by nkit-chahal** [comment]
NumPy version 1.20.3
it's working fine

**Comment by TonyXiang8787** [comment]
@nkit-chahal It's a new problem in version 1.24.

**Comment by seberg** [comment]
@MilesCranmer do you have time to have a quick look.  This looks like it must be related to gh-12065 misfiring.
Would be nice to fix for 1.24.1, but considering that needs to go out soon not sure that will happen.

**Comment by MilesCranmer** [comment]
Sure, I have time to look at this today.

**Comment by TonyXiang8787** [comment]
@MilesCranmer After some research I think the problem might be in this line:
https://github.com/numpy/numpy/blob/2b9851ba4f8cc436266d913eb5db75fc702e1eed/numpy/lib/arraysetops.py#L683

```
            outgoing_array[basic_mask] = isin_helper_ar[ar1[basic_mask] -
                                                        ar2_min]
```

If `ar` has a smaller data type, it may overflow here.

**Comment by MilesCranmer** [comment]
Quick question for @seberg: is this behaviour actually incorrect? In other words, do we want `int8(0) == int64(0)` in the context of `isin`, or to have it be `!=`? I could see either thing being technically correct, I suppose it depends on NumPy conventions. (I guess I could see `isin` having different behaviour than `==` if someone has a mixed type array)

**Comment by TonyXiang8787** [comment]
> Quick question for @seberg: is this behaviour actually incorrect? In other words, do we want `int8(0) == int64(0)` in the context of `isin`, or to have it be `!=`? I could see either thing being technically correct, I suppose it depends on NumPy conventions. (I guess I could see `isin` having different behaviour than `==` if someone has a mixed type array)

The behavior before version 1.24 is `int8(0) == int64(0)` in the context of `isin`.

**Comment by MilesCranmer** [comment]
@TonyXiang8787 I think the solution should be implemented by correcting the overflow detection here:

https://github.com/numpy/numpy/blob/2b9851ba4f8cc436266d913eb5db75fc702e1eed/numpy/lib/arraysetops.py#L652

To include information about the type of `ar1`.

**Comment by MilesCranmer** [comment]
Yep this looks like the solution:

```diff
-  range_safe_from_overflow = ar2_range < np.iinfo(ar2.dtype).max 
+  range_safe_from_overflow = ar2_range < np.iinfo(ar2.dtype).max and (ar1_max - ar2_min) < np.iinfo(ar1.dtype).max and (ar1_min - ar2_max) > np.iinfo(ar1.dtype).min
```

I can make a PR when I get into the office, double check this fixes the bug, and also include some new unit tests.

**Comment by MilesCranmer** [comment]
PR created on #22878
