### ISSUE TITLE
DOC: Description of the `axes` parameter in the `rot90` function

### ISSUE THREAD

**Issue by matt-muresan** [numpy/numpy#22873]
### Issue with current documentation:

In the most recent documentation, the first line of the description and the parameter axes is defined as follows:
```
Rotate an array by 90 degrees in the plane specified by axes.
Rotation direction is from the first towards the second axis.
...
    axes : (2,) array_like
        The array is rotated in the plane defined by the axes.
        Axes must be different.
        .. versionadded:: 1.12.0
```

However in previous versions (e.g. version 1.9) before the `axes` parameter was added, the first line read the following:
```
Rotate an array by 90 degrees in the counter-clockwise direction.
```

Although the new description may be more general, it is more difficult to conceptualise what the documentation means when it says "plane defined by the axes" and "first towards the second" when compared to the idea of "counter clockwise". I understand that the `axes` parameter would change this behaviour, but it may be helpful to indicate in the docstring for axes somehow what the implications are of the default parameter in terms of more generally understood concepts like "clockwise" or "anti-clockwise".

### Idea or request for content:

Something mentioning the terms anti-clockwise or clockwise would be preferred to give an immediate useful context of what is happening. I am not sure what the best way to say it is... perhaps even just adding it under the docstring for `axes` and say that the `default rotates in the anti-clockwise direction`.

**Comment by rossbar** [comment]
This is arguably addressed in the Examples section, but it could be helpful to add a sentence to the Extended Summary. PR welcome!
