### ISSUE TITLE
BUG: 1.24.0 introduces inconsistent `array(arr, copy=False)` behavior based on byte order and dtype declaration 

### ISSUE THREAD

**Issue by rsokl** [numpy/numpy#22897]
### Describe the issue:

Starting in numpy 1.24.0 `array(big_end_arr, copy=False, dtype=big_end_arr.dtype)` will return a view instead a reference, whereas `array(big_end_arr, copy=False)` returns a reference. This specifically impacts big-endian byte orderings.

### Reproduce the code example:

```python
from numpy import array

lil_a = array(0, dtype="<f8")
lil_b_impl_dtype = array(lil_a, copy=False)
lil_b_expl_dtype = array(lil_a, copy=False, dtype="<f8")

assert lil_a is lil_b_impl_dtype
assert lil_a is lil_b_expl_dtype

big_a = array(0, dtype=">f8")
big_b_impl_dtype = array(big_a, copy=False)
big_b_expl_dtype = array(big_a, copy=False, dtype=">f8")

assert big_a is big_b_impl_dtype

assert big_b_expl_dtype.base is big_a
assert big_a is big_b_expl_dtype  # FAILS
```

### Runtime information:

```
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}},
 {'architecture': 'SkylakeX',
  'filepath': 'C:\\Users\\rsokl\\miniconda3\\envs\\py310\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None
```

### Context for the issue:

[MyGrad](https://github.com/rsokl/MyGrad) CI caught this error using Hypothesis. See [this test](https://github.com/rsokl/MyGrad/blob/79b55fbbfdaf502d964cf63f882479960f61b3f5/tests/test_tensor_creation.py#L349-L384)

**Comment by seberg** [comment]
This was an intentional change since it ensures preserving e.g. metadata on the dtype if `dtype=...` has metadata attached (i.e. the _result_ has `arr.dtype is dtype`).  It is a bit funny maybe since you just pass in a string that gets converted to a new dtype, rather than a new dtype.
Is this an actual issue or just a funny little thing found by the test suite to you?

**Comment by mhvk** [comment]
The following certainly seems a bit odd:
```
In [2]: np.dtype(">f8") is np.dtype(">f8")
Out[2]: False

In [3]: np.dtype("<f8") is np.dtype("<f8")
Out[3]: True
```
Is it simply that the standard dtypes for a given endianness are always defined and looked up?

I guess in the end it seems like an implementation detail, just like number can be identical or just equal:
```
In [10]: a = 1001.

In [11]: b = 1001.

In [12]: a is b
Out[12]: False

In [13]: a = 1

In [14]: b = 1

In [15]: a is b
Out[15]: True
```

**Comment by rsokl** [comment]
> Is this an actual issue or just a funny little thing found by the test suite to you?

It is an issue insofar as my library's `tensor` function attempts to have parity with `array`. But I can deal with this,

I am more concerned that this could cause very hard to find bugs in libraries like torch or xarray. I don't think it is outlandish to expect these libraries to have patterns like:

```python
new_arr = array(arr, dtype=dtype)

if arr is new_arr:
    # dtype is assumed to match arr.dtype
else:
    # dtype is assumed not to match arr.dtype
```

and for their tests that exercise this pattern to continue passing because they don't expect this behavior to depend on endianess.

**Comment by seberg** [comment]
Well, we changed it because previously:
```
dtype = np.dtype(something)  # or similar

arr = np.array(arr, dtype=dtype)
assert arr.dtype is dtype
```
was not true, which is also weird.  Granted, I think we may have to break that a little bit anyway, but before it was even odder, because even:
```
assert arr.dtype.num == dtype.num
```
failed (i.e. it was actually a "different" dtype).

I don't have a definite answer for what is the best thing, but whatever we choose unexpected things are possible.  (I still lean towards the current behavior being an improvement.)

**Comment by rsokl** [comment]
Fair enough
