### ISSUE TITLE
BUG: np.where float division by zero error in incorrect data type

### ISSUE THREAD

**Issue by MGloder** [numpy/numpy#22903]
### Describe the issue:

If there are three columns, c1,c2,c3, and for c1 it is an object datatype, and float for c2 and c3. 

In this case, if we use np.where() to filter out numbers by using c3 as a condition, and do the calculation on c1/c2/c3, then, the np.where will throw a `ZeroDivisionError: float division by zero`

### Reproduce the code example:

```python
import numpy as np
import pandas as pd

test_df = pd.DataFrame(columns=['c1', 'c2', 'c3'],
                       data=[(08888888.000002, 2, 3), (0, 2, 3), (1, 2, 0), (1, 2, 3)])

test_df['c1'] = test_df['c1'].astype('object')
test_df['another_new_col'] = np.where(
    test_df['c3'] > 0,
    test_df['c1'] / test_df['c2'] / test_df['c3'],
    10
)
test_df.info()
print(test_df)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/xu_yan/Library/Application Support/JetBrains/PyCharmCE2021.3/scratches/scratch.py", line 10, in <module>
    test_df['c1'] / test_df['c2'] / test_df['c3'],
  File "/Users/xu_yan/Project/venv/lib/python3.8/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/Users/xu_yan/Project/venv/lib/python3.8/site-packages/pandas/core/arraylike.py", line 116, in __truediv__
    return self._arith_method(other, operator.truediv)
  File "/Users/xu_yan/Project/venv/lib/python3.8/site-packages/pandas/core/series.py", line 5526, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/Users/xu_yan/Project/venv/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 224, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/Users/xu_yan/Project/venv/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 166, in _na_arithmetic_op
    result = func(left, right)
  File "/Users/xu_yan/Project/venv/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/Users/xu_yan/Project/venv/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 69, in _evaluate_standard
    return op(a, b)
ZeroDivisionError: float division by zero
```

### Runtime information:

1.20.3
3.8.8rc1 (v3.8.8rc1:dfd7d6893b, Feb 16 2021, 15:09:27) 
[Clang 6.0 (clang-600.0.57)]

### Context for the issue:

if we change c1 to float, then everything works

**Comment by seberg** [comment]
Sorry, but NumPy cannot do anything about this here.  The problem is that pandas provides you with an object array containing Python floats, and dividing them by zero raises:
```
type(np.asarray(test_df['c1'])[1])
```
I think there is an open issue about it being difficult to get a NumPy dtype, now that pandas defaults to its NA dtypes.

**Comment by MGloder** [comment]
@seberg Thanks for the reply. If we remove the row `(0, 2, 3)`, it will also raise the `ZeroDivisionError`. is that normal? I think the filter condition just not working

**Comment by seberg** [comment]
You are calculating `test_df['c1'] / test_df['c2'] / test_df['c3']`, the `(1, 2, 0)` will still divide by zero.

**Comment by seberg** [comment]
Going to close, since I don't see what we could do to improve this when pandas returns float objects.
The only thing I can say is that you can try to filter things ahead of time, or maybe better just use `df.to_numpy(dtype=...)` (assuming you know what dtype you want in NumPy).

**Comment by MGloder** [comment]
> t you can try to filter thin
```
test_df['another_new_col'] = np.where(
    test_df['c3'] > 0,
    test_df['c1'] / test_df['c2'] / test_df['c3'],
    10
)
```
I tried to filter c3, so why `(1, 2, 0)` still go to the first branch?

**Comment by seberg** [comment]
Your code is equivalent to:
```
result = test_df['c1'] / test_df['c2'] / test_df['c3']

new_col = np.where(test_df['c3'] > 0, result, 10)
```
you would have to filter ahead of time.  (Honestly, you should probably just not use NumPy's `np.where` function here)

In fact, I see you converted to *object* manually for `c0`, so the error doesn't even originate in NumPy, it originates in the `result = ...` line there and that is all in pandas.
