### ISSUE TITLE
BUG: `np.linspace` slow for small number of points (large overhead?)

### ISSUE THREAD

**Issue by joseph-sch** [numpy/numpy#22915]
### Describe the issue:

I noticed that `np.linspace` is slow compared to alternatives for obtaining the same result with small `num` argument, in the scalar case at least.

For small `num`, I find that `np.interp` and `np.arange` have much lower overhead.

Here are times I measured - we see that from 11 to 10,001 the runtime is almost unchanged, showing that the overhead is dominant:

|                 | 11      | 101     | 1,001   | 10,001  | 100,001 | 1,000,0001 |
|-----------------|---------|---------|---------|---------|---------|------------|
| **np.linspace** | 18.2 µs | 19.6 µs | 20 µs   | 27 µs   | 110 µs  | 3.7 ms     |
| **np.interp**   | 3.98 µs | 4.87 µs | 14.4 µs | 117 µs  | 1.45 ms | 24.9 ms    |
| **np.arange**   | 2.43 µs | 2.59 µs | 3.65 µs | 12.5 µs | 227 µs  | 8.61 ms    |

### Reproduce the code example:

```python
import numpy as np

N = 11
%timeit y = np.linspace(4.936234, 1023.16231, N)
%timeit y = np.interp(x=np.arange(N), xp=[0, N-1], fp=[4.936234, 1023.16231])
%timeit y = np.arange(N, dtype='float') * ((1023.16231 - 4.936234) / (N-1)) + 4.936234
N = 101
%timeit y = np.linspace(4.936234, 1023.16231, N)
%timeit y = np.interp(x=np.arange(N), xp=[0, N-1], fp=[4.936234, 1023.16231])
%timeit y = np.arange(N, dtype='float') * ((1023.16231 - 4.936234) / (N-1)) + 4.936234
N = 1_001
%timeit y = np.linspace(4.936234, 1023.16231, N)
%timeit y = np.interp(x=np.arange(N), xp=[0, N-1], fp=[4.936234, 1023.16231])
%timeit y = np.arange(N, dtype='float') * ((1023.16231 - 4.936234) / (N-1)) + 4.936234
N = 10_001
%timeit y = np.linspace(4.936234, 1023.16231, N)
%timeit y = np.interp(x=np.arange(N), xp=[0, N-1], fp=[4.936234, 1023.16231])
%timeit y = np.arange(N, dtype='float') * ((1023.16231 - 4.936234) / (N-1)) + 4.936234
N = 100_001
%timeit y = np.linspace(4.936234, 1023.16231, N)
%timeit y = np.interp(x=np.arange(N), xp=[0, N-1], fp=[4.936234, 1023.16231])
%timeit y = np.arange(N, dtype='float') * ((1023.16231 - 4.936234) / (N-1)) + 4.936234
N = 1_000_001
%timeit y = np.linspace(4.936234, 1023.16231, N)
%timeit y = np.interp(x=np.arange(N), xp=[0, N-1], fp=[4.936234, 1023.16231])
%timeit y = np.arange(N, dtype='float') * ((1023.16231 - 4.936234) / (N-1)) + 4.936234
```

### Runtime information:

```
1.22.4
3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
```

### Context for the issue:

I understand that `np.linspace` supports non-scalar start and stop arguments, but either its overhead should be lowered, or it should be made clear in the documentation that alternatives are faster for smaller numbers...

**Comment by MatteoRaso** [comment]
From what I can tell from looking at the code, the overhead is from ``` asanyarray ``` being called twice at the beginning and intentionally not using in-place multiplication, which is faster. Unfortunately, these decisions were done to solved certain issues, so it's not as if they can just be changed. That being said, your test is somewhat flawed. You're not giving ``` arange ```  a stepsize as an argument, which makes it go faster. As the documentation says, ``` linspace ``` is better when you have to use non-integer stepsizes.

**Comment by joseph-sch** [comment]
I'll close my issue, assuming that this is a minor issue with no clear solution and that the documentation won't include details about the specific performance of each function.
