### ISSUE TITLE
BUG: fill violating read-only flag

### ISSUE THREAD

**Issue by blowekamp** [numpy/numpy#22922]
### Describe the issue:

Behavior of numpy 1.24.1 changed to `fill` on read-only arrays.

### Reproduce the code example:

```python
import numpy as np
a = np.zeros(11)
a.setflags(write=False)
a.fill(0)
```

### Error message:

```shell
A ValueError exception expected but is no longer raised.
```

### Runtime information:

1.24.1
3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]

WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}}]
None

This changed in behavior has occurred on all our CI systems, windows, Mac and linux. And with python versions 3.7 to 3.11

### Context for the issue:

Our regression test suit is failing. It provides an opportunity for data to unexpectedly change, and invalid states in the software could be entered with undefined behavior.

**Comment by blowekamp** [comment]
@seberg It looks like you are looking into this already. Thank you. 

I ran git bisect and determined the regression happened in ac624d012cc0c3f90da4593e7bb8d9d335fa9696.

**Comment by seberg** [comment]
@blowekamp thanks for the report, yes I know how to fix it.  I was just leaving it sitting for a few days in case someone new to the project wanted to picking it up.

**Comment by panosz** [comment]
Hi, there! I would like to give this a try. However, I have never contributed to numpy before, so I am not sure how this will go (or how long it is going to take)

**Comment by seberg** [comment]
This one has to be relatively quick, but needs a small fix and a test.  The main point for you will be to dig in and understand what needs to be done to fix it (It is a C-change, the regression changeset should help a bit to figure it out).  I can give pointers, but the most interesting thing here will be understanding what is wrong.

**Comment by panosz** [comment]
@seberg, thanks for the reply. I guess I will take a loot at it first and when I am ready I will open a PR and we can pick it up from there.
