### ISSUE TITLE
DOC: possibly misleading description of `numpy.ndarray.nbytes`

### ISSUE THREAD

**Issue by SiLiKhon** [numpy/numpy#22925]
### Issue with current documentation:

I am referring to this line from [the relevant doc page](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.nbytes.html):
https://github.com/numpy/numpy/blob/28c81bc4b287255c4570a58e6d6bcd86600cd0b5/numpy/core/_add_newdocs.py#L2699

Maybe it's worth adding a comment that this may not be the amount of physically consumed bytes in case of a view. Here's an example where `nbytes` returns absurdly large amount of bytes consumed:
```python
import numpy as np

arr = np.broadcast_to(0, (10, 1000000000000))
print(arr.nbytes)  # prints "80000000000000"
```

P.S. See [this discussion on SO](https://stackoverflow.com/questions/74990485/wrong-nbytes-value-in-a-numpy-array-after-broadcasting-with-broadcast-to/74995997).

**Comment by mattip** [comment]
That actually may be considered a bug in the way we calculate `nbytes`. We could try to look at the strides.

**Comment by seberg** [comment]
Note that if you want the actual memory consumed by the object itself (witout parents in case of view), then `sys.getsizeof()` does give the correct answer.

I don't have a quick opinion on whether to fix the docs or consider it a bug.  Either seems fine so long there is no serious compatibility break by things like `len(arr.tobytes())` returning a different size then `arr.nbytes`.

**Comment by MikiPWata** [comment]
Maybe we can add @seberg 's note about `sys.getsizeof() ` to the documentation? I can work on modifying the doc if that's ok.

**Comment by seberg** [comment]
Of course adding a "See Also" section or expanding the docs is always good.

**Comment by MikiPWata** [comment]
sounds good! let me work on that.

**Comment by MikiPWata** [comment]
@seberg 
The PR above is pretty much good to go. Do you mind reviewing it?
Thank you in advance!

**Comment by ntessore** [comment]
While the new docs are great, the use of "consumed" still causes confusion. Can I suggest a change that goes further:

```py
add_newdoc('numpy.core.multiarray', 'ndarray', ('nbytes',
    """
    Total bytes of the elements of the array.

    This is the number of bytes that the elements of the array would
    consume if copied.  Might not be the physical memory currently
    consumed if the array is a view and does not own its data.

    Notes
    -----
    Does not include memory consumed by non-element attributes of the
    array object.

    See Also
    --------
    sys.getsizeof
        Physical memory consumed by the array object itself, including
        owned data and non-element attributes.

    Examples
    --------
    >>> x = np.zeros((3,5,2), dtype=np.complex128)
    >>> x.nbytes
    480
    >>> np.prod(x.shape) * x.itemsize
    480

    Views and broadcasts can have `nbytes` values that are vastly
    different from their memory use:

    >>> x = np.broadcast_to(1., (1000, 1000))
    >>> x.nbytes
    8000000
    >>> import sys
    >>> sys.getsizeof(x)
    128

    """))
```
