### ISSUE TITLE
ENH: Update numpy in a way to make it installable on Termux, as it was working fine in the past

### ISSUE THREAD

**Issue by saalimzafar** [numpy/numpy#22935]
### Proposed new feature or change:

This is causing err from core/setup.py file

if not check_funcs_once(MANDATORY_FUNCS, add_to_moredefs=False):
        raise SystemError("One of the required function to build numpy is not"
                " available (the list is %s)." % str(MANDATORY_FUNCS))

**Comment by mattip** [comment]
What is the complete build log, i.e. which function(s) are missing? Are you falling into this [old termux issue](https://github.com/termux/termux-packages/issues/10808) ?

**Comment by saalimzafar** [comment]
Yes the old termux issue, but the solution it has mentioned is not working for me.

**Comment by saalimzafar** [comment]
I tried the same way earlier, but it worked this time after trail and error.
~ $ MATHLIB="m" pip3 install numpy
Collecting numpy
  Using cached numpy-1.24.1.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... done
  Created wheel for numpy: filename=numpy-1.24.1-cp311-cp311-linux_aarch64.whl size=13789771 sha256=bf2d615de0ff27c45d80ec7a9f80ecb72427b7e2e6677059ae101bd5fd17459b
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/c1/bd/22/de43b43e0ce54db24facd097d74d3ad5a1e05a0598242f844f
Successfully built numpy
Installing collected packages: numpy
**Successfully installed numpy-1.24.1**
