### ISSUE TITLE
DOC: documentation building instructions not clear about `make latex` not usable prior to the `make html` Doxygen trigger

### ISSUE THREAD

**Issue by jfbu** [numpy/numpy#22946]
### Issue with current documentation:

I had problems repeatedly building PDF docs which various versions of Sphinx, so issueing `make clean`  in-between (EDIT: which is not a priori mandatory, but turns out to be safer).  Turns out that the Doxygen step is triggered by `make html`, not by `make latex`. So in a clean empty state, `make latex` will report a build error (which one understands later to be originating in missing XML files from Doxygen).

### Idea or request for content:

Explanations at https://numpy.org/doc/1.24/dev/howto_build_docs.html#instructions are not so clear about that.  Perhaps the Makefile could contain a `Doxygen` target which would be a dependency of the `latex`  target, or the documentation could explicitly say that one needs to execute at least once `make html`.

Tried to look but found no reference to this in the docs and issues.

**Comment by eagunn** [comment]
I recommend this issue be closed. The version addressed, 1.24, did include the ability to generate a PDF, but a) it is fairly old, and b) support for generating PDFs was dropped as of version 1.25. 

PDFs might come back (#27573) but, if they do, presumably we'll be rebuilding both the 'how to build' instructions and the make file.
