### ISSUE TITLE
DOC: "deprecated Numeric compatibility" at https://numpy.org/doc/stable/user/basics.indexing.html

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#22940]
### Issue with current documentation:

https://numpy.org/doc/stable/user/basics.indexing.html says "Also recognize that x[[1, 2, 3]] will trigger advanced indexing, whereas due to the deprecated Numeric compatibility mentioned above, x[[1, 2, slice(None)]] will trigger basic slicing".

I don't think there is anything about deprecated Numeric compatibility mentioned anywhere.

**Comment by seberg** [comment]
Thanks for the note.  This was fixed in gh-22708 so it is fixed in the devdocs.  I don't think we typically backport doc PRs, but I guess we could make an exception.

**Comment by rgommers** [comment]
I tagged that PR as a backport candidate, so @charris can decide. Either way, the issue is already fixed so let's close this.
