### ISSUE TITLE
DOC: wrong [source] link for numpy.typing.NDArray

### ISSUE THREAD

**Issue by mabruzzo** [numpy/numpy#22944]
### Issue with current documentation:

The link to the source code seems to be broken for an entry on the [API Reference page for Type annotations](https://numpy.org/devdocs/reference/typing.html).

Specifically, the problem occurs for [numpy.typing.NDArray](https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray):
- The source-code link currently takes you the repository's main `__init__.py` file.
- It's unclear to me where it should link (or if there should be a source link at all). 

If nothing else, the current link is inconsistent with the only other API-entry on the page with a source link,  [numpy.typing.NBitBase](https://numpy.org/devdocs/reference/typing.html#numpy.typing.NBitBase) (that links to `typing/__init__.py`)

**EDIT**: Actually, this can probably be closed. I was looking at the development version of the documentation. This doesn't appear to be an issue in other versions.

**Comment by InessaPawson** [comment]
Thank you for the update, @mabruzzo! I'll close the issue.
