### ISSUE TITLE
BUG: <error in outer product for complex vectors: ' prefix>

### ISSUE THREAD

**Issue by dariomaio** [numpy/numpy#22942]
### Describe the issue:

Given the two vectors
v = [[-3j],[9]]
w = [[9j],[2], [7]]
the outer product should be 

[(-27+0j), -6j, -21j]
[-81j, (18+0j), (63+0j)]

but np.outer(v,w) returns

[[27. -0.j  0. -6.j  0.-21.j]
 [ 0.+81.j 18. +0.j 63. +0.j]]

### Reproduce the code example:

```python
import numpy as np
v = [[-3j],[9]]
w = [[9j],[2], [7]]
prod= np.outer(v,w)
print('outer product = ')
print(prod)

outer product = 
[[27. -0.j  0. -6.j  0.-21.j]
 [ 0.+81.j 18. +0.j 63. +0.j]]
```

### Runtime information:

1.24.1
3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

In quantum computing the outer product is very  relevant.

**Comment by dariomaio** [comment]
I realize that conjugation is not applied to the second vector

**Comment by dariomaio** [comment]
Dear Sebastian,
thanks for your prompt reply. Unfortunately, the definition adopted by numpy does not conform to the one used for complex vector spaces, as is the case with quantum states.

***@***.***

I've certainly already implemented a function for this, but what worries me the most is that the Qiskit library suggest to use np.outer with wrong results!
I think that as the vdot function handles complex numbers differently than dot(a, b)
Therefore, analogously, numpy should provide an ad hoc function for the outer product of vectors with complex numbers.

Best regards

Dario Maio



Da: Sebastian Berg ***@***.***>
Data: giovedì, 5 gennaio 2023, 18:01
A: numpy/numpy ***@***.***>
Cc: Dario Maio ***@***.***>, Mention ***@***.***>
Oggetto: Re: [numpy/numpy] BUG: <error in outer product for complex vectors: ' prefix> (Issue #22942)

@dariomaio<https://github.com/dariomaio> that is how np.outer is defined, it doesn't do the conjugation, if you need it you should probably just create a small helper function yourself.
I doubt we can change the definition in NumPy, we could only add a new function for this in principle.

**Comment by seberg** [comment]
I am going to close this, since I don't think changing `np.outer` is doable (especially not without discussion that probably doesn't fit an issue).  Adding something new may be, but is also a bigger proposal.

Thus, I think there isn't really anything actionable here, thanks for opening an issue though.

If `Qiskit` suggest to use this for complex things, than that seems like a problem with their documentation.

**Comment by dariomaio** [comment]
Ok thanks for your effort.
Best regards
Dario Maio

Il gio 19 gen 2023, 12:39 Sebastian Berg ***@***.***> ha
scritto:
