### ISSUE TITLE
BUG: Different results after using multi_dot vs functools.reduce for a chain of matrix multiplications

### ISSUE THREAD

**Issue by danielmunioz** [numpy/numpy#22953]
### Describe the issue:

Using multidot as opposed to simply doing a chain of matrix multiplications on a list of arrays yields different results, usually the results differ only on one of the elements of the resulting array (index [2, 1] in the code example).
I'm not sure why this is cause, theoretically all multi_dot does is change the order of operations so technically there shouldn't be any difference on just doing `np.dot(np.dot(A, B), C)` (or as suggested in the docs `reduce(np.dot, (A, B, C))`) vs `multi_dot((A, B, C))` right?

### Reproduce the code example:

```python
import numpy as np
from functools import reduce


arrays = (
    np.array([[-1. , -1. ], [-1. , -1. ], [-1. , -0.5]], dtype=np.float32),
    np.array([[-1.0000000e+00, -1.0000000e+00], [-1.7014118e+38, -1.0000000e+00]], dtype=np.float32),
    np.array([[-1., -2.], [-1., -1.]], dtype=np.float32),
)

print(np.linalg.multi_dot(arrays))
print(reduce(np.dot, arrays))
assert (np.linalg.multi_dot(arrays) != reduce(np.dot, arrays)).all()
```

### Error message:

```shell
[[-1.7014118e+38           -inf]
 [-1.7014118e+38           -inf]
 [-8.5070592e+37           -inf]]
[[-1.7014118e+38           -inf]
 [-1.7014118e+38           -inf]
 [-8.5070592e+37 -1.7014118e+38]]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[61], line 13
     11 print(np.linalg.multi_dot(arrays))
     12 print(reduce(np.dot, arrays))
---> 13 assert (np.linalg.multi_dot(arrays) != reduce(np.dot, arrays)).all()

AssertionError:
```

### Runtime information:

1.23.0
3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]

**Comment by rkern** [comment]
Operations like `+` and `*` that are associative and commutative with real numbers are not always associative or commutative in floating point arithmetic. Changing the order of operations can matter. This is especially the case when you have such large orders of magnitude difference in sizes, as you do here.

**Comment by danielmunioz** [comment]
Thanks for the quick answer!
OK, got it, but I think it's worth mentioning that it also seems to happen with smaller numbers, for example:

```
import numpy as np
from functools import reduce

arrays=(np.array([[-1. , -1. , -1. , -1. , -1. ],
[-1. , -1. , -1. , -1. , -1. ],
[-1. , -1. , -1. , -1. , -1. ],
[-1. , -1. , -1. , -1.9, -1. ],
[-1. , -1. , -1. , -1. , -1. ]], dtype=np.float16),
np.array([[-1. , -1. , -1. , -1. , -1. , -8. ],
[-1. , -1. , -1. , -1. , -1. , -1. ],
[-1. ,  1. ,  2. , -1. ,  1. , -9. ],
[-1. , -1. , -9. , -0.5,  1. ,  1. ],
[-1. , -1. ,  1. , -1. , -1. , -1. ]], dtype=np.float16),
np.array([[-1., -1.],
[-1., -2.],
[-1., -8.],
[-1., -1.],
[-1., -1.],
[-1.,  8.]], dtype=np.float16))

print(np.linalg.multi_dot(arrays))
print(reduce(np.dot, arrays))
```

yields:

```
[[-39.5   63.5 ]
 [-39.5   63.5 ]
 [-39.5   63.5 ]
 [-48.06 -10.78]
 [-39.5   63.5 ]]
[[-39.5    63.5  ]
 [-39.5    63.5  ]
 [-39.5    63.5  ]
 [-48.06  -10.875]
 [-39.5    63.5  ]]
```

~0.1 diff is quite noticeable, how would you recommend dealing with this?, would there be any way to offset this difference sorry?

**Comment by seberg** [comment]
You are using float16 in the new example.  Flopat16 has only a precision of something like 3 decimal digits.  So the difference is not `~0.1` it is still related to how much your input numbers (they differ on a similar order in absolute terms).  You are getting something like 12  ULP difference:
```
np.testing.assert_array_almost_equal_nulp(np.float16(-10.78), np.float16(-10.875), 12)
``` 
That may seem much, but probably expected considering how big the intermediate numbers get (google "catastrophic annihilation floating point math" for example to get an idea).

If you need more precision, use `float32` or `float64`, with `float16` even normal numbers have large differences compared to the precision.

Closing for now, as this looks all like normal floating point math behavior.
