### ISSUE TITLE
License-related confusion

### ISSUE THREAD

**Issue by Ashley123456789** [numpy/numpy#22957]
### Steps to reproduce:

When I **import** numpy as a third-party dependency through Anaconda or pip methods, 

- Should I comply with the LICENSE.txt (i.e., BSD 3-Clause)? Is the **import** action considered as **Redistribution and use** in the LICENSE.txt?
- Do I need to pay attention to **license compatibility**, i.e., can I claim a  **less strict license** than BSD 3-Clause for my projects?

Looking forward to your reply.

**Comment by rkern** [comment]
Answered over at https://github.com/scipy/scipy/issues/17741
