### ISSUE TITLE
BUG: difference in multivariate_normal samples between numpy 1.23.5 and 1.24.1 at same seed

### ISSUE THREAD

**Issue by rikardn** [numpy/numpy#22975]
### Describe the issue:

In some cases sampling from a multivariate normal distribution give different samples between using numpy 1.23.5 and numpy 1.24.1 using the same rng and seed. 

The example with n = 7 or below will give the same samples between the numpy versions, but having n = 8 (or higher) the samples will be different, which is unexpected.

### Reproduce the code example:

```python
import numpy as np

rng = np.random.default_rng(8978)

sigma = [[ 3.77384e-04,  1.78985e-04, -9.45976e-06,  6.95925e-04,  9.76862e-05,
   6.55149e-04,  1.04747e-05,  1.16840e-04,  1.68096e-04, -5.09766e-05],
 [ 1.78985e-04,  1.21699e-04,  4.11940e-06,  2.20735e-04,  1.60894e-04,
   3.55346e-04,  6.13028e-05,  1.04650e-04,  3.06187e-04, -5.86387e-05],
 [-9.45976e-06,  4.11940e-06,  5.79782e-05,  1.94285e-04,  1.97596e-05,
   5.93476e-04,  1.85140e-04,  8.77500e-05, -4.21243e-05,  2.21459e-06],
 [ 6.95925e-04,  2.20735e-04,  1.94285e-04,  3.86191e-03,  2.42335e-04,
   5.52113e-03,  1.11664e-03,  3.50275e-04, -8.96832e-04, -9.95807e-04],
 [ 9.76862e-05,  1.60894e-04,  1.97596e-05,  2.42335e-04,  1.19349e-03,
   1.31357e-03,  2.34006e-04, -3.59009e-06,  2.26896e-03, -9.60314e-04],
 [ 6.55149e-04,  3.55346e-04,  5.93476e-04,  5.52113e-03,  1.31357e-03,
   5.80533e-02,  7.33231e-04,  1.02913e-03,  1.68334e-03,  2.39945e-03],
 [ 1.04747e-05,  6.13028e-05,  1.85140e-04,  1.11664e-03,  2.34006e-04,
   7.33231e-04,  1.78939e-03,  3.31691e-04,  8.53473e-05, -1.04420e-03],
 [ 1.16840e-04,  1.04650e-04,  8.77500e-05,  3.50275e-04, -3.59009e-06,
   1.02913e-03,  3.31691e-04,  7.87703e-04, -5.82814e-04,  6.88541e-04],
 [ 1.68096e-04,  3.06187e-04, -4.21243e-05, -8.96832e-04,  2.26896e-03,
   1.68334e-03,  8.53473e-05, -5.82814e-04,  1.86714e-02,  1.17500e-03],
 [-5.09766e-05, -5.86387e-05,  2.21459e-06, -9.95807e-04, -9.60314e-04,
   2.39945e-03, -1.04420e-03,  6.88541e-04,  1.17500e-03,  1.43419e-02]]

mu = [ 0.0352093,   0.0192129,   0.0227801,   0.0433142,  -0.00279093,  0.983126,
 -0.0570624,   0.0438765,   0.0806757,   0.983166  ]

mu = np.array(mu)
sigma = np.array(sigma)

# If n set to 7 or below the samples will be the same
n = 8

x = rng.multivariate_normal(mu[0:n], sigma[0:n, 0:n], size=1)
print(x)
```

### Runtime information:

1.24.1
3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

Operating system: Linux
Arch: x64

### Context for the issue:

The issue breaks reproducibility of simulation results between the two numpy versions.

**Comment by rkern** [comment]
Please see our PRNG compatibility policy here: https://numpy.org/neps/nep-0019-rng-policy.html

Also, [`multivariate_normal()` is more vulnerable to changes](https://github.com/numpy/numpy/pull/22938/files) to the build because it relies on linear algebra routines that can be changed from build to build. That is more likely what is going on; I don't think we made any changes directly to `multivariate_normal()` between those versions. Unfortunately, that also applies to the otherwise more stable `RandomState` as well as `Generator`.

**Comment by fabian-sp** [comment]
Catching up on this, I have a brief question: do I understand correctly, that if I use `multivariate_normal` with a `Generator`, I can not expet to get identitcal results for same seed on different machines?

I am running unit tests which pass on some machines and fail on others and this is the only thing that would explain this phenomenon.

**Comment by rikardn** [comment]
You shouldn't rely on the same stream of random numbers being produced by different numpy versions.

**Comment by rkern** [comment]
That is correct @fabian-sp. You can try `method='cholesky'`, which will use a [simpler linear algebra routine](https://github.com/numpy/numpy/issues/22919#issuecomment-1370214673) underneath that is _likely_ (but not surely) to vary less on different builds.
