### ISSUE TITLE
BUG: Calling `numpy.histogramdd` with a dictionary of duck arrays does not call the overridden function.

### ISSUE THREAD

**Issue by byrdie** [numpy/numpy#22973]
### Describe the issue:

I'm attempting to make an [xarray](https://docs.xarray.dev/en/stable/)-style ndarray duck type which I'm calling [named_arrays](https://github.com/Kankelborg-Group/named_arrays). I'm trying to override `numpy.histogramdd`, but I can't get the numpy dispatch mechanism to call my overridden function. 

For my use case, it makes the most sense to me to have the `sample` argument of `numpy.histogramdd` be a dictionary where the keys are strings and the values are instances of my duck `ndarray`. The keys represent different components and become the names of the axes of the resulting histogram.

I think it is not working since the `dict[str, DuckArray]` is just an iterable of strings from the dispatch mechanism's perspective, none of which have an implementation of `__array_function__`.

Is there a way to coerce the dispatch mechanism to call the implementation of `__array_function__` in the values of `samples`?

If not I am willing to open a PR to address this issue if there is a way to resolve this in a way that everyone is happy with.

### Reproduce the code example:

```python
import dataclasses
import numpy as np

@dataclasses.dataclass
class DuckArray:
    data: np.ndarray

    def __array_function__(self, func, types, args, kwargs, ):
        if func is np.histogramdd:
            print('Inside DuckArray.__array_function__')
        else:
            return NotImplemented

def test_dict():
    sample = dict(x=DuckArray(np.random.random(11)))
    np.histogramdd(sample)

def test_tuple():
    sample = DuckArray(np.random.random(11)),
    np.histogramdd(sample)
```

### Error message:

```shell
named_arrays\example.py:13 (test_dict)
def test_dict():
        sample = dict(x=DuckArray(np.random.random(11)))
>       np.histogramdd(sample)

example.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<__array_function__ internals>:200: in histogramdd
    ???
..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\histograms.py:1001: in histogramdd
    smin, smax = _get_outer_edges(sample[:,i], range[i])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = array([{'x': DuckArray(data=array([0.95880504, 0.41589853, 0.94013642, 0.90798121, 0.83272869,
              0.7402617...6,
              0.2161453 ]))}                                                                  ],
      dtype=object)
range = None

    def _get_outer_edges(a, range):
        """
        Determine the outer bin edges to use, from either the data or the range
        argument
        """
        if range is not None:
            first_edge, last_edge = range
            if first_edge > last_edge:
                raise ValueError(
                    'max must be larger than min in range parameter.')
            if not (np.isfinite(first_edge) and np.isfinite(last_edge)):
                raise ValueError(
                    "supplied range of [{}, {}] is not finite".format(first_edge, last_edge))
        elif a.size == 0:
            # handle empty arrays. Can't determine range, so use 0-1.
            first_edge, last_edge = 0, 1
        else:
            first_edge, last_edge = a.min(), a.max()
>           if not (np.isfinite(first_edge) and np.isfinite(last_edge)):
E           TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\histograms.py:322: TypeError
```

### Runtime information:

import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.1
3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

**Comment by mattip** [comment]
You will have to override at least `min` and `max` so that this line returns `DuckArrays`
```
first_edge, last_edge = a.min(), a.max()
```

**Comment by byrdie** [comment]
@mattip, apologies, maybe my example was too simple, I definitely have `min`, `max` and many other functions defined in my real `DuckArray`. 

I was just trying to express that the default version of `__array_function__` was being called in the `test_dict()` test instead of my overridden version. If I use the `test_tuple()` test, the overridden version is called the way I want.

I think I am basically asking if the dispatch machinery could be modified to 
1. check if any of the arguments are a `dict` and 
2. check if any of the values of that `dict` have an implementation of `__array_function__` and call that version

Similar to how the dispatch machinery checks if the argument is iterable and then checks if any of the elements of the iterable have `__array_function__` implemented

**Comment by seberg** [comment]
Yes it could be changed, but the signature for `histogramdd` takes a single array, not a sequence of arrays.
It is not like it works with a dictionary of numpy arrays.

**Comment by byrdie** [comment]
@seberg, I'm reasonably certain `histogramdd` can take a sequence of arrays. It says so in the documentation and I just tested it on my machine.

**Comment by byrdie** [comment]
Fair enough, I see your point. But doesn't the fact that my `test_tuple` sample calls my overridden function point to the fact that the dispatch mechanism checks every element of the sequence for `__array_function__` first, before calling `np.asarray()`?

**Comment by byrdie** [comment]
But would we be amenable to modifying the dispatcher to accept dictionaries? This is not the only function I think would benefit, I've also run into this issue trying to override `numpy.ravel_multi_index()`.

**Comment by seberg** [comment]
NumPy accepts dictionaries no-where, and simply ignoring the keys seems weird to me TBH.  I could imagine rejecting dicts (and other iterables) that otherwise don't unpack in `np.asarray(...)` with a better error message.
But on first sight, my feeling is "no".  If you need a sequence of arrays and have a dict, you have to do some work to decide what to do.

If your dict was "special", because it indicates named dimensions, then maybe it should itself implement `__array_function__`?

**Comment by seberg** [comment]
Supporting `dict.values()` was I think discussed before.  I don't remember why that always got stuck (it may have been nothing more than that it is a very odd special path, but I feel there was more).

**Comment by byrdie** [comment]
I would think that the default instance of an array function should just throw an error if they got a dictionary (not throw away the keys), the check should only exist to call overridden versions of the array function.

**Comment by byrdie** [comment]
I can't find that discussion after a cursory search of the issues, do you have any memory of where that discussion occurred?

**Comment by seberg** [comment]
I guess this: https://github.com/numpy/numpy/pull/14539.  I am not sure I see why arguably the same input (a dict of arrays) should work for non-NumPy arrays, but not for numpy arrays.

**Comment by byrdie** [comment]
I see what you're saying, I guess I thought that it might break the principle of least surprise if the function silently throws away the keys. I would be ok if the function operated on the values of the dictionary as well, my thoughts above were just my first instinct as to what should happen.

Overriding all the array functions to work with named axes means that lots of arguments have different types than the usual signatures to the array functions, so I was just used to some inputs working for non-numpy arrays but not for numpy arrays.
