### ISSUE TITLE
 _multiarray_umath.cp311-win32.pyd Problem

### ISSUE THREAD

**Issue by CDeslatte2023** [numpy/numpy#22979]
### Steps to reproduce:

Clean install of Python 3.11.1 (NO Anaconda) on a Virtual Machine (Windows 10) for testing. All Windows updates applied. Flask app running fine on any other machine in my office but not this virtual machine.

Installed modules:
cachelib             0.9.0  
click                8.1.3
colorama             0.4.6
cx-Oracle            8.3.0
Flask                2.2.2
Flask-Session        0.4.0
Flask-SQLAlchemy     3.0.2
greenlet             2.0.1
itsdangerous         2.1.2
Jinja2               3.1.2
MarkupSafe           2.1.1
numpy                1.24.1
pandas               1.5.2
pip                  22.3.1
pyodbc               4.0.35
python-dateutil      2.8.2
pytz                 2022.7
setuptools           65.5.0
six                  1.16.0
SQLAlchemy           1.4.45
sqlalchemy-pervasive 0.2.1
tqdm                 4.64.1
waitress             2.1.2
Werkzeug             2.2.2
wheel                0.38.4

Using waitress to host app on 8080 just like the rest of my local test machines. Program launches from command line and then simply exits back to command prompt.

Windows event viewer application log shows the following:

Faulting application name: python.exe, version: 3.11.1150.1013, time stamp: 0x638f9bc0
Faulting module name: _multiarray_umath.cp311-win32.pyd, version: 0.0.0.0, time stamp: 0x63a91b93
Exception code: 0xc000001d
Fault offset: 0x000269c9
Faulting process id: 0x24540
Faulting application start time: 0x01d92476b1310479
Faulting application path: C:\Python311-32\python.exe
Faulting module path: C:\Python311-32\Lib\site-packages\numpy\core\_multiarray_umath.cp311-win32.pyd
Report Id: 776d714a-fb06-4abe-857b-0d620af76aaa
Faulting package full name: 
Faulting package-relative application ID: 

![Screenshot 2023-01-09 162353](https://user-images.githubusercontent.com/122321131/211420524-94186c74-c3ca-4193-88c9-6ce7b052cc4b.png)

Nothing else to go on really... Googled for hours and couldn't find anything that helped.

### Error message:

```shell
Windows event viewer application log shows the following:

Faulting application name: python.exe, version: 3.11.1150.1013, time stamp: 0x638f9bc0
Faulting module name: _multiarray_umath.cp311-win32.pyd, version: 0.0.0.0, time stamp: 0x63a91b93
```

### Additional information:

Any help would be greatly appreciated. The program taps three databases and returns a Pandas dataset to an HTML table while allows downloading to CSV. It's the exact same code that works on other local PC's.

**Comment by rgommers** [comment]
@CDeslatte2023 thanks for the report. It's hard to get an idea of what's going on here, it would be great if you could:
- try to narrow it down to using just `numpy`, or `numpy` in combination with one other package. the shorter the code/script, the better
- get a traceback from the crash
- check if this problem also exists on numpy 1.23.5/1.24.0 or on Python 3.10 with the same config

**Comment by seberg** [comment]
Just so nobody else searches:  The error code seems to be for "illegal instruction".  Sounds like the SIMD discovery code in NumPy or OpenBLAS misfires probably.  Could you try disabling SIMD features on the VM (see https://numpy.org/devdocs/reference/simd/build-options.html#runtime-dispatch)?  Also may try on the host?

**Comment by CDeslatte2023** [comment]
> Just so nobody else searches: The error code seems to be for "illegal instruction". Sounds like the SIMD discovery code in NumPy or OpenBLAS misfires probably. Could you try disabling SIMD features on the VM (see https://numpy.org/devdocs/reference/simd/build-options.html#runtime-dispatch)? Also may try on the host?

Could you give me some instruction on what you are asking of me. Be glad to try this just unsure as to how.

**Comment by CDeslatte2023** [comment]
Ok based on both your suggestions I ran this simple program on the VM:

import numpy as np

list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]

result = []
for i in range(len(list)):
    result.append(np.mean(list[i]))
print(result)

I get the exact same Event Log message as I previously posted.

@Seberg - I think you are correct in your suggestion I just need some help in disabling said features please.

Thank you all for your time in advance.

**Comment by mattip** [comment]
NumPy tries to use advanced CPU features (SIMD) to speed up operations. If you are getting an "illegal instruction" error, one cause could be that the VM claims it can support one or more of these features but actually cannot. 

You can use the output of [`np.show_runtime()`](https://numpy.org/devdocs/reference/generated/numpy.show_runtime.html#numpy-show-runtime) inside your VM. This should show which SIMD features are detected. For instance, on my machine it shows
```
>>> np.show_runtime()
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]

```

In my case, it shows AVX2 and FMA3 under the `found` section, so I can disable them by setting `NPY_DISABLE_CPU_FEATURES="AVX2,FMA3"` in my environment before running python:
```
set NPY_DISABLE_CPU_FEATURES="AVX2,FMA3"
python <myprogram.py>
```

By installing threadpoolctl `np.show_runtime()` will show additional information:
```
...
{'architecture': 'Zen',
  'filepath': '/tmp/venv3/lib/python3.9/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 24,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
```
If you use the wheel from PyPI, it contains code from the OpenBLAS project to speed up matrix operations. This code too can try to use SIMD instructions. It has a different mechanism for choosing which to use, based on a CPU architecture, mine is `Zen`. You can override this architecture by setting `OPENBLAS_CORETYPE`, a minimal value for x86_64 is OPENBLAS_CORETYPE=Haswell. This too needs to be set before running your program:
```
set OPENBLAS_CORETYPE=Haswell
python <myprogram.py>
```

**Comment by CDeslatte2023** [comment]
Thank you! Just a little more info: vSphere Client version 6.7.0.54000

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/122321131/211596342-22c40d68-4536-4f37-8b15-563d16449091.png)

I will read the above post and follow your instructions and report back.

**Comment by CDeslatte2023** [comment]
And forgive my ignorance but I just set these in the python environment by typing python and getting the >>> first?

**Comment by CDeslatte2023** [comment]
I opened a command prompt on the VM and ran the following.. this is the result.

![numpy1](https://user-images.githubusercontent.com/122321131/211598957-45156a2f-d782-4290-967f-057d33e2ae60.png)


![numpy2](https://user-images.githubusercontent.com/122321131/211599009-5c78d531-d657-4b71-84f6-ad8c1d5b906d.png)

**Comment by mattip** [comment]
From the command prompt
```
C:\Users\15cliffd-wa>
```

Type this
```
C:\Users\15cliffd-wa>python -c "import numpy as np; print(np.show_runtime())"
```

Then to disable some feature, for instance AVX2 and FMA3 try
C:\Users\15cliffd-wa>SET NPY_DISABLE_CPU_FEATURES="AVX2,FMA3"
C:\Users\15cliffd-wa>python -c "import numpy as np; print(np.mean(np.array([4, 12, 34, 25, 78])))"

**Comment by CDeslatte2023** [comment]
![numpy3](https://user-images.githubusercontent.com/122321131/211600817-bdc8339e-8092-49b6-af89-b80fc7008887.png)

This is what it returned. Will try your second line. THANK YOU again for all your help!

**Comment by CDeslatte2023** [comment]
![numpy4](https://user-images.githubusercontent.com/122321131/211601401-0ebe8d1f-0951-4600-9ebd-6676029fef5b.png)

**Comment by mattip** [comment]
Please do not take my directions so literally. Since you do not have FMA3, you cannot disable it. So you need to only disable features that appear in the successful output of `show_runtime`, otherwise the process errors out. Please ask someone around you to help you understand my intentions.

**Comment by CDeslatte2023** [comment]
Is there a command to enable the original features since I have already "disabled" AVX2,FMA3

**Comment by CDeslatte2023** [comment]
I did the following:

"pip uninstall numpy"

I then reinstalled it as well as threadpoolctl.

I still get this and have no idea how to proceed. I apologize as there is no other person here that has any python knowledge.

![numpy5](https://user-images.githubusercontent.com/122321131/211607727-cef853d4-bcbb-4173-a593-a403d17c464b.png)

**Comment by mattip** [comment]
From the command prompt
```
C:\Users\15cliffd-wa>
```

Type this
```
C:\Users\15cliffd-wa>SET NPY_DISABLE_CPU_FEATURES
```

You will see that you have set `NPY_DISABLE_CPU_FEATURES` to `AVX2,FMA3`. You need to unset them: your machine does not have those features (`AVX2` and `FMA3`). So type this to reset it and start over
```
C:\Users\15cliffd-wa>SET NPY_DISABLE_CPU_FEATURES=
```

**Comment by CDeslatte2023** [comment]
Did exactly what you suggested and this happens... and I get the same Event Viewer message..

![numpy6](https://user-images.githubusercontent.com/122321131/211630374-3b8fb1a0-a031-4ae1-8c13-12d1235fe4f2.png)

![numpy7](https://user-images.githubusercontent.com/122321131/211630619-cf12ebd9-b0cf-4dc4-bcfe-9ac010e39df7.png)

**Comment by seberg** [comment]
That is because it is crashing before execution, which is weird.  You should probably try disabling almost all features and see if that helps.
That warning isn't all that important, it is just a warning.  Using `SET NPY_DISABLE_CPU_FEATURES=` clearly just puts you back into the **original** state.

It may be necessary for you to get local help here, and maybe also ask an expert about the virtual machine setup, since that is clearly involved.

**Comment by mattip** [comment]
Closing as stale. Please reopen or open a new issue if you are still stuck.

**Comment by mlubimow** [comment]
I also encountered this issue. I don't know how to fix it, but what I've noticed is that this bug was introduced in 1.24.0. If possible, downgrade numpy to 1.23.5 and it will work fine.
