### ISSUE TITLE
DOC: building documentation emits many FutureWarnings

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#22987]
There are many FutureWarnings when [building docs](https://app.circleci.com/pipelines/github/numpy/numpy/17525/workflows/a1ca64ae-8bb7-457f-97a1-880b0672944d/jobs/29548?invite=true#step-109-152) of the form
> `/home/circleci/repo/venv/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py:678: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.`
>  `return getattr(mod, name_parts[-1]), mod, modname`
> `/home/circleci/repo/venv/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py:701: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.`
>  `obj = getattr(obj, obj_name)`
> `/home/circleci/repo/venv/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py:678: FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.`
>  `return getattr(mod, name_parts[-1]), mod, modname`
> `/home/circleci/repo/venv/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py:701: FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.`
>  `obj = getattr(obj, obj_name)`
> `/home/circleci/repo/venv/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py:678: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.`
> ` return getattr(mod, name_parts[-1]), mod, modname`

I am also seeing an error when building locally with CPython 3.9.16:
```
WARNING: [autosummary] failed to import numpy.finfo.machar.
Possible hints:
* AttributeError: type object 'finfo' has no attribute 'machar'
* ImportError: 
* ModuleNotFoundError: No module named 'numpy.finfo'
```

but I don't see it in CI. Indeed, I cannot run `python -c "import numpy.finfo"`, only `python -c "from numpy import finfo"`. 
Here is the autodoc line: https://github.com/numpy/numpy/blob/df1ee34c7faea1cfc2aef0719444b6fa43887b42/doc/source/reference/routines.dtype.rst?plain=1#L28-L32

**Comment by seberg** [comment]
The warnings are annoying :(.  Something about our Parameter annotation triggering a look on `np.<name>`, I believe.  Maybe we can actually just hide them?

> I cannot run python -c "import numpy.finfo", only python -c "from numpy import finfo".

I suspect the important error is the first one:
> AttributeError: type object 'finfo' has no attribute 'machar'

(and after that sphinx does some fallback strategy that also fails).  That error is *correct*, the weird thing is that your it tries to check for `machar` existence?  That sounds a bit like picking up the 1.23 docstring, but running it against main/1.24?  I can't say that makes much sense to me either...
