### ISSUE TITLE
BUG: Incorrect type list for some ufunc loops (sin, cos, arctan2)

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#22984]
This is a follow up from gh-22376, where I forgot the `sin`/`cos` loops.  CuPy noticed these in https://github.com/cupy/cupy/issues/7243 and also found that `arctan2` has the same issue.

For `arctan2` this is actually a bug also leads to wrong results within NumPy (rather than only causing numba/cupy to be confused).

Just opening the issue in case 1.24.2 is around the corner, should fix it today in either case.

**Comment by kmaehashi** [comment]
Thanks for opening an issue @seberg! It seems `sin` and `cos` are also affected when `int8` is involved because `np.can_cast(np.int8, np.float16)` is True:

NumPy 1.23:

```pycon
>>> np.sin.types
['e->e', 'f->f', 'd->d', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']
>>> np.sin(np.array([0, 1, 2], dtype=np.int8))
array([0.    , 0.8413, 0.909 ], dtype=float16)
>>> np.cos(np.array([0, 1, 2], dtype=np.int8))
array([ 1.    ,  0.5405, -0.4163], dtype=float16)
```

NumPy 1.24:

```pycon
>>> np.sin.types
['f->f', 'e->e', 'd->d', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']
>>> np.sin(np.array([0, 1, 2], dtype=np.int8))
array([0.       , 0.841471 , 0.9092974], dtype=float32)
>>> np.cos(np.array([0, 1, 2], dtype=np.int8))
array([ 1.       ,  0.5403023, -0.4161468], dtype=float32)
```

**Comment by seberg** [comment]
Ah, good point, although I really don't like how we guess at `float16` for integer inputs...
