### ISSUE TITLE
BUG: astype(np.float32, casting="safe") allows casts that loose precision

### ISSUE THREAD

**Issue by maxnoe** [numpy/numpy#22985]
### Describe the issue:

According to the docs:
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html

> ‘safe’ means only casts which can preserve values are allowed.

however, it seems that this is violated for conversions between float64 and float32

### Reproduce the code example:

```python
import numpy as np

print(np.pi)
print(np.asanyarray(np.pi).astype(np.float32, casting="safe"))
```

### Error message:

```shell
3.141592653589793
3.1415927
```

### Runtime information:
```
1.23.5
3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]

also tested with:

1.24.1
3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/mnoethe/.local/conda/envs/np1.24/lib/libopenblasp-r0.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
```

**Comment by seberg** [comment]
This is entangled with NEP 50 and NumPy allowing scalars to be cast more generously.  The weird thing being that 0-D arrays are scalars in that sense.

Maybe NumPy should not apply the "scalar" rules in `astype()`, although it does currently in `np.can_cast` so it would lead to the fun thing that `np.can_cast()` would return True, but that cast would fail :).

On 1.24.x you can disable this behavior (better with the environment variable `NPY_PROMOTION_STATE=weak`):
```
>>> np._set_promotion_state("weak")
>>> np.asanyarray(np.pi).astype(np.float32, casting="safe")
TypeError: Cannot cast scalar from dtype('float64') to dtype('float32') according to the rule 'safe'

```

**Comment by seberg** [comment]
Probably, but it has an underscore for a reason and it may be tricky to not have it an performance impact.  So, I am not interested in putting in a larger amount of effort to make a hack available that seems borderline useful for a handful of power-users.  I might be if there is a clear path that it helps making choices about how the future will look like, but that is why the opt-in exists: for experimentation and getting to know the choice(s).

**Comment by seberg** [comment]
Since NEP 50 is in 2.0, and that is hopefully not supr far out, going to close this.
