### ISSUE TITLE
ENH: How does numpy implement 'advanced indexing' like np.array([1,2,3])[[0,2]]?

### ISSUE THREAD

**Issue by winshot-thu** [numpy/numpy#22992]
### Proposed new feature or change:

I have tested following code and found numpy advanced indexing is slow although I input an ascending continuous sequence as index. I hope it will improve and I wonder why. What happened if I input an array as index? 
```python
from time import time
import numpy as np


data = np.zeros((int(1e7),))
idx = list(range(int(1e6)))

a = time()
for i in range(100):
    data[idx]
b = time()
print(b-a) # 5.627795219421387s 


a = time()
for i in range(100):
    data[:int(1e6)]
b = time()
print(b-a) # 2.47955322265625e-05s 
```

**Comment by rkern** [comment]
In your case, most of the time in the first example is taken up merely by converting `idx` into an array each time. Try `idx = np.arange(int(1e6))` for significantly faster performance. However, it's still not quite as fast as the second example.

Operating systems have fast ways to copy contiguous segments of memory. In the first example, it does not know that you are essentially asking to do that. The `idx` might not have been a list of ascending integers. Instead, it has to compute the memory location of each element one by one and copy it over. CPUs and compilers do not optimize this kind of memory access well. This is the tradeoff for having a more flexible operation. It's possible that there are some microoptimizations that could be done, but the second example will necessarily always be faster.

**Comment by winshot-thu** [comment]
Thanks for your kind reply.
