### ISSUE TITLE
BENCH: Ensure all functions in main namespace that are also present in `array_api` are benchmarked

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#23009]
This is a tracking issue.

The following functions and methods are defined by the [array API standard as of 2022.12](https://data-apis.org/array-api/latest/API_specification/index.html).

- Those which have no `ndarray` equivalent are struck off.

## Methods
- [ ] `__abs__`
- [ ] `__add__`
- [ ] `__and__`
- ~~`__array_namespace__`~~
- [ ] `__bool__`
- [ ] `__complex__`
- [ ] `__dlpack__`
- [ ] `__dlpack_device__`
- [ ] `__eq__`
- [ ] `__float__`
- [ ] `__floordiv__`
- [ ] `__ge__`
- [ ] `__getitem__`
- [ ] `__gt__`
- ~~`__index__`~~ used implicitly for indexing
- [ ] `__int__`
- [ ] `__invert__`
- [ ] `__le__`
- [ ] `__lshift__`
- [ ] `__lt__`
- [ ] `__matmul__`
- [ ] `__mod__`
- [ ] `__mul__`
- [ ] `__ne__`
- [ ] `__neg__`
- [ ] `__or__`
- [ ] `__pos__`
- [ ] `__pow__`
- [ ] `__rshift__`
- [ ] `__setitem__`
- [ ] `__sub__`
- [ ] `__truediv__`
- [ ] `__xor__`
-  ~~`to_device`~~
## Creation Functions
- [x] `arange`
- [x] `asarray`
- [x] `empty`
- [ ] `empty_like`
- [x] `eye`
- [ ] `from_dlpack`
- [ ] `full`
- [ ] `full_like`
- [x] `linspace`
- [ ] `meshgrid`
- [x] `ones`
- [ ] `ones_like`
- [x] `tril`
- [x] `triu`
- [x] `zeros`
- [ ] `zeros_like`
## Data Type Functions
- [ ] `astype`
- [ ] ~~`can_cast`~~
- [ ] ~~`finfo`~~
- [ ] ~~`iinfo`~~
- [ ] ~~`isdtype`~~
- [ ] ~~`result_type`~~
## Element-wise Functions (`ufuncs`)
Most of these are covered in `bench_ufunc` but not for very large arrays.

- [X] `abs`
- [X] `acos`
- [X] `acosh`
- [X] `add`
- [X] `asin`
- [X] `asinh`
- [X] `atan`
- [X] `atan2`
- [X] `atanh`
- [X] `bitwise_and`
- [X] `bitwise_left_shift` == `left_shift`
- [X] `bitwise_invert` == `invert`
- [X] `bitwise_or`
- [X] `bitwise_right_shift` == `right_shift`
- [X] `bitwise_xor`
- [X] `ceil`
- [X] `conj`
- [X] `cos`
- [X] `cosh`
- [X] `divide`
- [X] `equal`
- [X] `exp`
- [X] `expm1`
- [X] `floor`
- [X] `floor_divide`
- [X] `greater`
- [X] `greater_equal`
- [X] `isfinite`
- [X] `isinf`
- [X] `isnan`
- [X] `less`
- [X] `less_equal`
- [X] `log`
- [X] `log1p`
- [X] `log2`
- [X] `log10`
- [X] `logaddexp`
- [X] `logical_and`
- [X] `logical_not`
- [X] `logical_or`
- [X] `logical_xor`
- [X] `multiply`
- [X] `negative`
- [X] `not_equal`
- [X] `positive`
- [X] `pow`
- [X] `real`
- [X] `remainder`
- [X] `round`
- [X] `sign`
- [X] `sin`
- [X] `sinh`
- [X] `square`
- [X] `sqrt`
- [X] `subtract`
- [X] `tan`
- [X] `tanh`
- [X] `trunc`
## Linear Algebra Functions
- [X] `matmul`
- [ ] `matrix_transpose` == `transpose()`
- [x] `tensordot`
- [ ] `vecdot` == `vdot`
## Manipulation Functions
- [ ] `broadcast_arrays`
- [ ] `broadcast_to`
- [ ] `concat`
- [ ] `expand_dims`
- [ ] `flip`
- [ ] `permute_dims`
- [ ] `reshape`
- [ ] `roll`
- [ ] `squeeze`
- [ ] `stack`
## Searching Functions
- [x] `argmax`
- [x] `argmin`
- [x] `nonzero`
- [x] `where`
## Set Functions
- [ ] `unique_all`
- [ ] `unique_counts`
- [ ] `unique_inverse`
- [ ] `unique_values`
## Sorting Functions
- [x] `argsort`
- [x] `sort`
## Statistical Functions
- [x] `max`
- [x] `mean`
- [x] `min`
- [ ] `prod`
- [ ] `std`
- [ ] `sum`
- [x] `var`
## Utility Functions
- [x] `all`
- [x] `any`

**Comment by rgommers** [comment]
I updated the issue title to better capture the intent here. Also, I think the overview is still WIP? I was surprised by how many functions were unchecked; a quick check in `benchmarks/` for `any`, `all`, `sort` and `argsort` shows that they all have some benchmarks already.

**Comment by HaoZeke** [comment]
> I updated the issue title to better capture the intent here. Also, I think the overview is still WIP? I was surprised by how many functions were unchecked; a quick check in `benchmarks/` for `any`, `all`, `sort` and `argsort` shows that they all have some benchmarks already.

Sorry, should have marked it as WIP. All the functions with existing benchmarks have now been checked off.

**Comment by soma2000-lang** [comment]
@rgommers @HaoZeke  I would like to work on one of the  unchecked ones.

**Comment by HaoZeke** [comment]
> @rgommers @HaoZeke I would like to work on one of the unchecked ones.

Most of these are in #23010 , but feel free to open a draft PR with some of the remaining ones. Note that not all of these are relevant to the `ndarray` though.
