### ISSUE TITLE
ENH: Adding alpine to CI Build

### ISSUE THREAD

**Issue by kostyafarber** [numpy/numpy#23001]
### Proposed new feature or change:

# Summary
At pandas there is an ongoing conversation on including Alpine in the CI builds as there are users reporting bugs from Alpine but no testing on the platform right now.

We thought it would be wise to first wait until (if) NumPy include and test Alpine in their CI first. I am requesting adding Alpine has a platform to test on during CI, so pandas can go ahead and use it too.

xref: https://github.com/pandas-dev/pandas/issues/50511

**Comment by seberg** [comment]
See gh-22864 which tests on musl.  Still needs some work, although probably mostly adjusting the tests themselves.  See gh-21200 for wheels (I guess).

**Comment by kostyafarber** [comment]
cc: @WillAyd

**Comment by andyfaff** [comment]
@seberg if there's anything to be changed for gh-22864 please let me know. From my point of view the PR is mergeable, but it does uncover failing tests that need to be looked at.

**Comment by seberg** [comment]
I think we were all hoping you may look into the test failures, adding CI that fails isn't all that nice, so I think we should at least partially clear it up.

IIRC, wasm also was based on musl which adds up: Right now it seems to me that all failures are related to the complex `arcsin` and `arctan` (maybe also `arccos`) and are already xfailed on `IS_WASM`.  It seems we need make that `IS_MUSL`.

The loss of precision in these test does look too big on first sight, is there a MUSL issue  or are we using the fallbacks?

**Comment by andyfaff** [comment]
>  I think we were all hoping you may look into the test failure

Ok, didn't know that. My skill in this area is familiarity is in setting CI up, etc. I'll mark the tests as `xfail`, but I stand a lower chance of being able to fix the fails.

**Comment by rgommers** [comment]
> adding CI that fails isn't all that nice, so I think we should at least partially clear it up.

It's already broken now, so I'd rather have working CI to avoid regressions, and then ask the relevant experts to fix the two issues of interest here. That should not be too hard. Especially if @andyfaff could give some guidance on Docker/Alpine to reproduce the problems. Memory policy would be for @mattip to look at I guess, and the `linalg` failures we have multiple experts.

**Comment by MrMino** [comment]
@rgommers looks like there's no followup on `musllinux` wheels in the issue tracker, or am I missing something? Should I create an issue for it?

Numpy side has been covered with the release of `musllinux` wheels in 1.25.0.
