### ISSUE TITLE
Question: Strange/unintuitive axis swap while slicing high dimensional arrays, 1.21.6

### ISSUE THREAD

**Issue by KrzysztofKalisiak** [numpy/numpy#23012]
### Describe the issue:

When slicing high dimensional arrays which are already sliced axis seem to swap randomly (especially last with first).

Set up:
1. Create 4 dimensional array (float64)
2. Reduce it to 3 dimensions with slicing -> arr[0, :, :, :]
3. Perform additional slicing on create above array -> arr[0, :, :, [0]]
4. Check shape -> arr[0, :, :, [0]].shape
5. It will be (1, x, y) and it should be (x, y, 1)

Error does not appear with not sliced arrays

### Reproduce the code example:

```python
import numpy as np
print(np.__version__)

# weird behavior
aj = np.random.normal(size=(14, 240, 320, 16))
print(aj[0, :, :, :].shape)
print(aj[0, :, :, [0]].shape)

# here normal
b = np.copy(aj[0, :, :, :])
print(b[:, :, :].shape)
print(b[:, :, [0]].shape)

# here also normal
aj_short = np.random.normal(size=(240, 320, 16))
print(aj_short[:, :, :].shape)
print(aj_short[:, :, [0]].shape)
```

### Runtime information:

1.21.6
3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0]

### Context for the issue:

I was doing some random stuff on arrays and spend like 30 minutes figuring out what is happening

**Comment by seberg** [comment]
It is a bit unfortunate and there are ideas on how it might be fixed (but I have not worked on them for years, there is a very drafty "NEP" about it).  In any case, the behavior is explained here: https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing

Going to close it, doc improvements are probably possible.  The problem with this is always discoverability.  We would need to raise an error for it, but that requires the replacement (i.e. that NEP)...
