### ISSUE TITLE
BUG: Vectorize function has no attribute "__name__"

### ISSUE THREAD

**Issue by ShivKJ** [numpy/numpy#23021]
### Describe the issue:

Consider the function,

```python
import numpy as np

def f1(a, b):
    return a + b

@np.vectorize
def f2(a, b):
    return a + b
```

Function `f1` has attribute `__name__` but `f2` (after applying decorator `np.vectorize`) does not have it.

Should we have `__name__` attribute in vectorized function?

I was checking other numpy function, such as `np.sum`, `np.ceil` etc. They all have `__name__` attribute. So I think it is fair and will be consistent if the vectorized function also has `__name__` attribute derived from underlying function `f2`. 

Note that: In example to `vectorize` [documentation](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html), documentation of function being wrapped is set in vectorized function. So I think, just like this, `__name__` of the that function can be set in `vectorize` object.

### Reproduce the code example:

```python
import numpy as np

@np.vectorize
def f2(a, b):
    return a + b

print(f2.__name__)
```

### Error message:

```bash
      3 @np.vectorize
      4 def f2(a, b):
      5     return a + b
----> 7 print(f2.__name__)

AttributeError: 'vectorize' object has no attribute '__name__'
```

### Runtime information:

```bash
1.24.1
3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
```

```bash
[{'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'armv8',
  'filepath': '~/.virtualenvs/exp/lib/python3.10/site-packages/numpy/.dylibs/libopenblas64_.0.dylib', # using ~/ for HOME_DIR
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
```

### Context for the issue:

I have written a function, say A, which takes on argument of type python-int. I was thinking of a way to make this function also work on `np.ndarray`. And that is where I found `np.vectorize`.

Of course, I could have written a separate function, say B, which takes `np.ndarray` and implements the same logic as used in A. But this will lead to duplicacy of code.

What I also observed is that the function B also works on python-int input type argument. But return type is always `np.ndarray` with `ndim` equals to 0.

I wanted to return python int if output of function `B` has `ndim` 0. So I was thinking of creating a decorator.

This is where I found that error that,

```bash
'vectorize' object has no attribute '__name__'
```

**Comment by seberg** [comment]
This seems semi related to gh-9477.  And a bunch of other issues, enabling it to be a reasonable decorator and using `functools.wraps` as is the typical pattern, seems like an easy small project.

N.B.: vectorize serve a purpose, but should only be used when necessary.  For a simple function like the above it is not.  Vectorize does not (significantly) improve the speed, JITers like `numba` can do such things, though.

**Comment by ShivKJ** [comment]
@seberg 
>...For a simple function like the above it is not....

Function mentioned above is provided for simplicity. Actual function is more complicated. And that is why I chose to use the same function on vector inputs as well. 

We could also use **for-loop** but then using function with decorator `np.vectorize` seems more natural to read and write the code and easier to maintain.

**Comment by MatteoRaso** [comment]
>seems like an easy small project.

I'm willing to take a stab at it. Just to be clear, you want gh-9477 to be solved as well?

**Comment by seberg** [comment]
Probably, yes.  The use case here is to use it as a decorator, but that only happens to work for the simple call signature, this class predates decorators...  Matching the functions name makes most sense if the decorator is the intended (otherwise something using the name makes more sense?).
There is an old PR to check out and maybe base off.

**Comment by 1515236544hit** [comment]
` def __name__(self) -> str:
        return self.__name__`

just simply add this to the np. vectorized class

**Comment by 1515236544hit** [comment]
Is this wrong or what i am new to python and exploring it

**Comment by 1515236544hit** [comment]
` self.__name__ = pyfunc.__name__` add this to  the class and also
` def test_name(self):
        @np.vectorize
        def f2(a, b):
            return a + b

        assert f2.__name__ == 'f2'`
to the test function

**Comment by mattip** [comment]
Closed by #23061

**Comment by bsipocz** [comment]
Reopening as #23061 has been reverted.

**Comment by bsipocz** [comment]
Closed by https://github.com/numpy/numpy/pull/23514 ("magic" words have to be present in front of every linked issue number to get them auto-closed at merge)
