### ISSUE TITLE
wrong intersphinx prefix for many numpy functions

### ISSUE THREAD

**Issue by drammock** [numpy/numpy#23032]
in the current objects.inv file (https://numpy.org/devdocs/objects.inv) it appears that many of the functions have changed from `py:function` prefix to the `py:data` prefix. For example:

```
numpy.arange py:function 1 reference/generated/numpy.arange.html#$ -
numpy.arccos py:data 1 reference/generated/numpy.arccos.html#$ -
numpy.arccosh py:data 1 reference/generated/numpy.arccosh.html#$ -
numpy.arcsin py:data 1 reference/generated/numpy.arcsin.html#$ -
numpy.arcsinh py:data 1 reference/generated/numpy.arcsinh.html#$ -
numpy.arctan py:data 1 reference/generated/numpy.arctan.html#$ -
numpy.arctan2 py:data 1 reference/generated/numpy.arctan2.html#$ -
numpy.arctanh py:data 1 reference/generated/numpy.arctanh.html#$ -
numpy.argmax py:data 1 reference/generated/numpy.argmax.html#$ -
numpy.argmin py:data 1 reference/generated/numpy.argmin.html#$ -
numpy.argpartition py:data 1 reference/generated/numpy.argpartition.html#$ -
numpy.argsort py:data 1 reference/generated/numpy.argsort.html#$ -
numpy.argwhere py:data 1 reference/generated/numpy.argwhere.html#$ -
numpy.around py:data 1 reference/generated/numpy.around.html#$ -
numpy.array py:function 1 reference/generated/numpy.array.html#$ -
numpy.array2string py:data 1 reference/generated/numpy.array2string.html#$ -
numpy.array_equal py:data 1 reference/generated/numpy.array_equal.html#$ -
numpy.array_equiv py:data 1 reference/generated/numpy.array_equiv.html#$ -
numpy.array_repr py:data 1 reference/generated/numpy.array_repr.html#$ -
numpy.array_split py:data 1 reference/generated/numpy.array_split.html#$ -
numpy.array_str py:data 1 reference/generated/numpy.array_str.html#$ -
numpy.asanyarray py:function 1 reference/generated/numpy.asanyarray.html#$ -
```
This random chunk of 22 entries has 3 `py:function` entries and 19 `py:data` entries. But aren't all of them functions?  This is causing the MNE-Python CIs to fail because we have lots of things like
```
see :func:`numpy.where` for details
```
which as of today no longer resolve.

**Comment by charris** [comment]
@rossbar Thoughts?

**Comment by drammock** [comment]
was this intentionally closed?  Can you at least tell me if the change to the prefixes is going to stay that way or be reverted?

**Comment by rossbar** [comment]
> @rossbar Thoughts?

Hmm not off the top of my head. The devdocs still claim to be built by sphinx 5.3, so it's likely not due to a change in sphinx/intersphinx (they're on v6 already).

We could bisect to chase down which commit exactly is causing the changes to objects.inv. This would be time-consuming as it would involve a full build+doc build at each step. @drammock do you have info on the timestamps for the last job in MNE-Python where this worked and the first MNE-Python job where this failed readily available?

**Comment by rossbar** [comment]
> We could bisect to chase down which commit exactly is causing the changes to objects.inv. This would be time-consuming as it would involve a full build+doc build at each step

Good news - the objects.inv files are still available as circleci artifacts, so this is a lot easier. Looking into it now...

**Comment by drammock** [comment]
last successful CircleCI run was Tuesday 17 Jan 2023 at 13:00:05 (GMT-6)

first fail was Tuesday 17 Jan 2023 at 13:52:16 (GMT-6)

That should narrow it down :)

**Comment by rossbar** [comment]
Thanks! Based on the timestamps and release note, this is likely due to #23020. Let's ping @seberg

**Comment by seberg** [comment]
Hmmm, so sphinx thinks that a C-callable instance is not necessary a function?

**Comment by mattip** [comment]
Previous to #23020, `isinstance(np.where, types.FunctionType)` was True. Now it is False. Perhaps `_ArrayFunctionDispatcher` should inherit from `PyFunction_Type`

**Comment by seberg** [comment]
Maybe also `PyCMethod`, but SciPy has two places where they just assume that functions have a valid `__code__` attribute (both seem a bit like [this](https://xkcd.com/1172/) simply relying on Python defined functions. I haven't even figured out the Rbf one, but it all doesn't quite add up to me, maybe it is even just expecting a `ValueError`).

`np.add`, etc. also show up as `py:data`, I guess?  I could also just use a bound method, but adding `__code__` to that might be no easier.

Maybe it easier to just break everyone who incorrectly implements a function by all arguments on (including default kwargs) 😄.

**Comment by seberg** [comment]
Nvm. The I suspect the fix for scipy is to just wrap `trapz` into a layer of Python for backcompat until it is fixed in SciPy.  So maybe we can try to make sure to spit out proper C functions/methods here.  They won't have `__code__`, but maybe that shouldn't matter, because with that `trap` exception, why should anyone rely on a NumPy function to be written in Python?

**Comment by seberg** [comment]
@rossbar before I actually try subclassing, is there any way to tell sphinx to consider these functions? This is part of a problem also discussed in gh-22162.

**Comment by seberg** [comment]
The only path that I currently know would work, would be just unwrapping all functions for the purpose of building the docs.  Probably relative simply, but...

**Comment by seberg** [comment]
This monkeypatching would work (I think, I have to confirm `object.inv`):
```
    from numpy.core._multiarray_umath import _ArrayFunctionDispatcher
    from sphinx.ext.autodoc import FunctionDocumenter

    orig_can_doc = FunctionDocumenter.can_document_member
    # Monkeypatch functiondocumenter, first tried to add another one, but
    # sphinx gives a warning then
    def can_document_member(member, membername, isattr, parent):
        if isinstance(member, _ArrayFunctionDispatcher):
            return True
        return orig_can_doc(member, membername, isattr, parent)

    FunctionDocumenter.can_document_member = can_document_member
```

I first tried to register a new FunctionDocumenter subclass, but sphinx gave a warning, so thought why not just monkey-patch...

**Comment by drammock** [comment]
thanks!
