### ISSUE TITLE
MAINT,TASK: CI is clean of Python 3.8 and we require 3.9, some code remnants remain

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#23044]
At this point there are still a few (not many) references to python 3.8 and Python 3.8 specific code paths/tests.  It would be nice to remove them.
This should be a nice small thing to work on, the main complexity is finding everything :).

**Comment by soma2000-lang** [comment]
@seberg will be submitting another pr

**Comment by seberg** [comment]
I will assume @neutrinoceros got most of the relevant things in the PR, so closing.
