### ISSUE TITLE
GOV: Update the NumPy Roadmap

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy#23059]
### Issue with current documentation:

We've reviewed and updated the NumPy Roadmap during the NumPy Team Summit at SciPy'22 on July 12, 2022. 
See the notes here: [https://github.com/numpy/archive/commit/a120891c5e9742515c5b9a3e3749a4321e6f0d34](https://github.com/numpy/archive/commit/a120891c5e9742515c5b9a3e3749a4321e6f0d34)
However, the main document on wiki ([https://github.com/numpy/numpy/wiki/NumPy-roadmap-v2](https://github.com/numpy/numpy/wiki/NumPy-roadmap-v2)) has never been updated.

### Idea or request for content:

Update the NumPy Roadmap.

**Comment by Arya-Gupta** [comment]
I am interested in this issue. Can I be assigned?

**Comment by rgommers** [comment]
https://numpy.org/neps/roadmap.html is up-to-date after gh-26505, and gh-26722 makes some more updates. The action in this issue was hence completed, so closing. I also added a note to the wiki page to forward-link to the roadmap.

**Comment by rootsmusic** [comment]
@rgommers  Delete the [old version](https://github.com/numpy/numpy/wiki/NumPy-Roadmap) of the wiki drafted for brainstorming?

**Comment by rgommers** [comment]
Thanks @rootsmusic. Added a note to it instead, since it contains some content that isn't captured elsewhere.
