### ISSUE TITLE
DOCS: deployment of devdocs failed, deleting the docs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23063]
https://github.com/numpy/devdocs is showing a 404. This is because the deployment step (after a merge-to-main) is removing the docs from https://github.com/numpy/devdocs instead of uploading them. [The deploy step](https://github.com/numpy/numpy/blob/747823cc7e77d1e13705856d10a6ca2a46f4c47d/.circleci/config.yml#L128) should not be run if the build is empty.

This is due to the [documentation build](https://app.circleci.com/pipelines/github/numpy/numpy/17729/workflows/c43d2c87-e712-44ae-9363-e911378bdf01/jobs/29775?invite=true#step-109-172) failing but not reporting the error. Probably fallout from #22948 unifying the two doc build jobs. @tupui could you take a look?

**Comment by seberg** [comment]
It seems the nose removal PR removed an attribute `numpy.testing.dec` that is still document and thus the build fails completely unfortunately.

So two things to fail, but yeah I guess this proofs that we need to improve again that the failures show up immediately in CI.  Probably by just doing that double run again.
