### ISSUE TITLE
DOC: Wrong types in the dtype hierarchy diagram

### ISSUE THREAD

**Issue by aerobio** [numpy/numpy#23078]
### Issue with current documentation:

According to the dtype hierarchy in [numerictypes.py](https://github.com/numpy/numpy/blob/main/numpy/core/numerictypes.py), character types may be:
- ...
    -  character
        - (Python 2)
            - str_ = string_ = bytes_
            - unicode_
        - (Python3)
            - bytes_ = string_
            - str_ = unicode_

But the [dtype hierarchy diagram](https://github.com/numpy/numpy/blob/main/doc/source/reference/figures/dtype-hierarchy.png) shows the Python 2 version only:
- ...
    - character
        - str_
        - unicode_

This is confusing for Python 3 users for whom `str_` and `unicode_` are the same type and `bytes_` or `string_` are missing.

**Comment by Mukulikaa** [comment]
Fixed via #23285.
