### ISSUE TITLE
Python 3.9 - 3.11 - venv - Windows Subsystem for Linux Ubuntu 22.04 - ImportError numpy.core.multiarray

### ISSUE THREAD

**Issue by Joshua-Schroijen** [numpy/numpy#23080]
### Steps to reproduce:

Using Ubuntu 22.04 LTS on Windows Subsystem for Linux
- Create a virtual environment using venv, in a path without spaces to be sure
- Verify <virtual environment>/lib/python3.xx/site-packages/numpy/core folder holds files such as _multiarray_umath.cpython-3xx-x86_64-linux-gnu.so, and that it's added to PATH
- Check PATH and PYTHONPATH are correct (the virtual environment's paths are in fact the first)
- Pip install numpy, with or without --no-binary=:all: flag
- - Verify 
- Install a library depending on numpy
- Get an error like "ImportError: numpy.core.multiarray failed to impor"

**Comment by mattip** [comment]
Could you copy-paste the actual steps you are taking rather than describing them in words? You can use code formatting like
```
$ virtualenv /tmp/myvenv
$ . /tmp/myvenv/bin/activate
$ python -m pip install numpy
$ python -m pip install other-library
$ python -c "import other_library"
```

**Comment by Joshua-Schroijen** [comment]
Hi Matti Picus,

The issue seems to have resolved itself after creating a new virtual environment. I think I'll have to chalk this up to a virtual environment corruption.
