### ISSUE TITLE
BUG: Install error with Numpy: error: legacy-install-failure

### ISSUE THREAD

**Issue by sneddonucsf** [numpy/numpy#23106]
### Describe the issue:

Hello, 

I am trying to install a package called Scenic+  (https://github.com/aertslab/scenicplus) and am running into an issue with installing Numpy as a dependency while installing scenic+. During the install I get a legacy error message. I've tried updating my pip, wheel and setuptools and also creating a new Conda environment and installing there, but am still having the issue with the following details:

### Reproduce the code example:

```python
git clone https://github.com/aertslab/scenicplus
cd scenicplus
pip install -e .
```

### Error message:

```shell
16 errors generated.
            error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.macosx-10.15-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/seandelao/.pyenv/versions/3.7.0/include/python3.7m -Ibuild/src.macosx-10.15-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.15-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.macosx-10.15-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.15-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.macosx-10.15-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.15-x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.macosx-10.15-x86_64-cpython-37/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.macosx-10.15-x86_64-cpython-37/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> numpy
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
```
```


### Runtime information:

Cannot show runtime information. 

### Context for the issue:

_No response_

**Comment by rossbar** [comment]
Are you expecting to be building NumPy from source? Is scenicplus perhaps pinned to an old version of NumPy? I suspect this is an issue with the packaging/dependency specification in that project.

**Comment by seberg** [comment]
We really need more information, which python and how did you install it?  The error you give is also missing any actually useful information.
You normally should not be compiling NumPy, but the error indicates you are, so there is some weird reason for this somewhere and it is completely unclear what it is (it may be version pins as ross said, or you are compiling for a niche platform, or...)

**Comment by sneddonucsf** [comment]
Thank you for the replies! I installed with the following, which is the recommendation on the scenic+ install:
```
conda create --name scenicplus python=3.8
conda activate scenicplus
git clone https://github.com/aertslab/scenicplus
cd scenicplus
pip install -e .
```

Attached is a .docx file with the full error output. 
[Error.docx](https://github.com/numpy/numpy/files/10512783/Error.docx)

**Comment by seberg** [comment]
I am not going to open a docx.  The first line reads a bit like you are using a Python 3.7, I do wonder if you are getting the `pip` and `python` you think you are getting.  Maybe try `python -mpip install` which is safer.

But overall, you should probably install most of the requirements ahead of time using conda anyway, since you are using conda.  In either case, if you end up needing to compile NumPy (which this looks like) something is off and installing it via conda would at least help probably.  (But probably there is more wrong, even via pip you shouldn't normally end up compiling NumPy but rather get a "wheel".)
