### ISSUE TITLE
BUG: Inconsistent behavior between scalar and array operands in Numpy shift operations

### ISSUE THREAD

**Issue by graille** [numpy/numpy#23102]
### Description
When performing a left (or right) shift operation on strongly typed data using scalars, the output type is that of the operand with the most bits. In the following example:

`(np.uint32(1) << np.uint8(10)).dtype`

the output is `dtype('uint32')` because the left operand has more bits than the right operand.

However, when the right operand is a scalar, the same behavior is observed:

`(np.uint32(1) << np.array(10, dtype=np.uint8)).dtype`
the output is `dtype('uint32')` and the resulting value is 1023.

But when the right operand is an array, the behavior is different and the type of the array is preserved.

`(np.uint32(1) << np.array([10], dtype=np.uint8))`
the output is `array([0], dtype=uint8)` and the resulting value is 0.

This results in different behavior and results between arrays and scalars, making it difficult to write generic code for both.

### Expected Behavior
The expected behavior is that when performing a left (or right) shift operation on strongly typed data using scalars or array, the result would be the same

### Actual Behavior
The actual behavior is that when the right operand is a scalar, the output type is that of the operand with the most bits. However, when the right operand is an array, the type of the array is preserved.

### Reproduce the code example:

```python
import numpy as np

x1 = np.uint32(1) << np.uint8(10)
x2 = np.uint32(1) << np.array(10, dtype=np.uint8)
x3 = np.uint32(1) << np.array([10], dtype=np.uint8)

print(f"x1 value={x1}, dtype={x1.dtype}")
print(f"x2 value={x2}, dtype={x2.dtype}")
print(f"x3 value={x3[0]}, dtype={x3.dtype}")
```

### Runtime information:

1.23.5
3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]

### Context for the issue:

This results in different behavior and results between arrays and scalars, making it difficult to write generic code for both.

### Additional Information
I am not sure if this is a bug, but the behavior is quite strange.

**Comment by rkern** [comment]
Please read [my reply to a similar issue from the other day](https://github.com/numpy/numpy/issues/23085#issuecomment-1403115526). The cases you present are a little different, but my explanation of current behavior and the coming changes largely apply, and the links are both relevant. As with that issue, this is designed and documented behavior, and the coming changes would go a long way to getting the behavior that you want, so I am going to close the issue.
