### ISSUE TITLE
BUG: numpy.where() method considers None as False as expected but considers np.nan as True

### ISSUE THREAD

**Issue by sairam-penjarla** [numpy/numpy#23125]
### np.where():

The numpy.where() method is a convenience function that allows for the selection of elements from two input arrays, x and y, based on a given condition. The function takes three arguments: a condition, x, and y. The condition is a boolean array, where elements of x are selected where the condition is True and elements of y are selected where the condition is False. However, there is an issue with the way this method handles the special value NaN (Not a Number).

When the condition is passed as None, the method correctly treats it as False and returns the elements of y as expected. However, when the condition is passed as numpy.nan, the method incorrectly treats it as True and returns the elements of x. This is a problem because NaN is a special value that represents missing or undefined data, and it should be treated as neither True nor False in a boolean context.

# Code
The "C" function related to the numpy where method can be found in [here](https://github.com/numpy/numpy/blob/685b9ace06f1dc50e2698099d7a2b6a241379318/numpy/core/src/multiarray/multiarraymodule.c#L2915)

As you can see, when passing np.nan as a condition, it returns x values where it should return y values. This behavior is not consistent with the rest of the library and it makes it difficult to handle missing data correctly. This issue should be addressed by updating the numpy.where() method to correctly handle NaN values in the condition, in the same way it handles None values.

### Reproduce the code example:

```python
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
condition = np.nan


result = np.where(condition, x, y)
print(result)
# Expecting [5, 6, 7, 8] but getting [1, 2, 3, 4]
```

### Runtime information:

1.24.1
3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]

**Comment by WarrenWeckesser** [comment]
The floating point value `nan` is not considered "falsy".  This is consistent with Python:

```
In [15]: import math

In [16]: bool(math.nan)
Out[16]: True
```

For numeric types, only zero is considered false.

This [stackoverflow question](https://stackoverflow.com/questions/15686318/why-do-not-a-number-values-equal-true-when-cast-as-boolean-in-python-numpy) has more discussion and links.
