### ISSUE TITLE
BUG: LLVM 15 libcxx: _ZNSt3__122__libcpp_verbose_abortEPKcz: symbol not found

### ISSUE THREAD

**Issue by RinCat** [numpy/numpy#23122]
### Describe the issue:

When build numpy with LLVM 15 clang/clang++ and libcxx, it somehow include a symbol from libcxx in the file https://github.com/numpy/numpy/blob/main/numpy/core/src/npysort/binsearch.cpp

```
readelf -s --wide work/numpy-1.24.0-python3_10/temp.linux-x86_64-3.10/numpy/core/src/npysort/binsearch.o
94: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZNSt3__122__libcpp_verbose_abortEPKcz
```

The symbol `_ZNSt3__122__libcpp_verbose_abortEPKcz` is used for abort a program with a special verbose information.
https://libcxx.llvm.org/UsingLibcxx.html#id7
https://reviews.llvm.org/D130562

I don't know why this symbol was added, the code of that cpp don't seem to be relevant.

The numpy can be loaded if using `LD_PRELOAD=/usr/lib/libc++.so.1 python`

### Reproduce the code example:

```python
import numpy
```

### Error message:

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: Error relocating /usr/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: _ZNSt3__122__libcpp_verbose_abortEPKcz: symbol not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/usr/lib/python-exec/python3.10/python"
  * The NumPy version is: "1.24.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: Error relocating /usr/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: _ZNSt3__122__libcpp_verbose_abortEPKcz: symbol not found
```

### Runtime information:

```
1.24.0
3.10.9 (main, Jan 28 2023, 16:07:29) [Clang 15.0.7 ]
```
```
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None
```

**Comment by seberg** [comment]
Are we sure this isn't a regression in clang?  The discussion you linked says it is used for noexception mode, which NumPy must use here.  I don't really see that there can be much of a problem in how we build, but of course I may be missing something obvious.

**Comment by RinCat** [comment]
I don't know if this is a regression in clang or not, but seems only happened for this special file. All C++ files except `binsearch.cpp` do not have this symbol. So I think there might be some special parameter to its build that triggers the problem.

**Comment by seberg** [comment]
I don't think `binsearch.cpp` is special compared to other C++ sources we have.  All are compiled with no-exception (and must be).  I may just be ignorant, but I don't quite see why we should need to link `libc++` here.

How are you compiling and install exactly by the way?

@hawkinsp just in case you can say immediately:  You were running with clang 16, right?  Does it require `libc++` there, or is the fact that it is pulled in just a fluke here?

**Comment by hawkinsp** [comment]
@seberg While we are using `clang` close to head, our build environment is unusual, so we won't be able to learn from it here.

**Comment by RinCat** [comment]
> but I don't quite see why we should need to link `libc++` here.

No, I don't mean to link libc++, but wonder why a libc++ symbol will be included here that I didn't find it is being used anywhere in the code.

> How are you compiling and install exactly by the way?

`setup.py build`

Log [here](https://gist.github.com/RinCat/03c263f35824a5bf8dd4304d1eb3d43a)

**Comment by seberg** [comment]
Hmmm, since I don't really know, let's ask C++ wizards.  @serge-sans-paille do you have an insight into why `clang15` seems to pull in `ibcpp_verbose_abort` in `binsearch.cpp` here?  Is it just clang not being careful with avoiding pulling it in, or should we be linking (or tell clang about it more clearly).

**Comment by serge-sans-paille** [comment]
Are you compiling with `-DNDEBUG` ? I *think* this symbol is brought by `assert` and as we compile without linking to the standard lib, this symbol would indeed be undefined. To avoid the situation, without linking with the standard library, we would need to provide our own assert.

**Comment by serge-sans-paille** [comment]
@RinCat I see no `-DNDEBUG` in the commande line args. Can you try adding it?

**Comment by RinCat** [comment]
@seberg I just used the following flags for C/CXX, but the same issue still exists.

```
INFO: compiling C++ sources
INFO: C compiler: clang++ -DNDEBUG -DNDEBUG -fno-strict-aliasing -fPIC -ftrapping-math
```

I also get some feedback from people who played the compiler. They recommend linking against the c++ standard library, since it is hard to determine which standard library function implementations will use the extra symbols.

**Comment by serge-sans-paille** [comment]
The goal of using the C linker was to *not* use the standard library in a portable way. The underlying idea being that we would only use a minimal set of template helper types / functions and keep the C++ part minimal. The approach is not future-proof, as showcased by current bug. 
Indeed, freestanding is the standardized way of doing so, but it's also very constraining in terms of what we can do.

I guess it's time to allow linking with the standard library?

**Comment by serge-sans-paille** [comment]
Alternatively, we can handle this assert issue by either defining our own or not asserting.

**Comment by rgommers** [comment]
I think we probably need to do both. On the 1.24.x maintenance branch we shouldn't make a switch as large as changing from the C to the C++ linker. For the next minor release (1.25.0) we're switching to Meson, and that would be a good time to switch to the C++ linker.

**Comment by mattip** [comment]
> Are you compiling with -DNDEBUG

While probably not connect directly to this issue, this is a difference between meson and distutils. Meson does not define `-DNDEBUG`. Distutils pulls CFLAGS from sysconfig, which defines `-DNDEBUG`.

**Comment by rgommers** [comment]
> Meson does not define `-DNDEBUG`.

For the record, this is no longer the case with changes in `main` and `meson-python` 0.13.0. See https://github.com/numpy/numpy/issues/23595#issuecomment-1510492182 for details.

**Comment by rgommers** [comment]
@RinCat could you please check if gh-23601 resolves the issue for you?

**Comment by RinCat** [comment]
@rgommers I can confirm https://github.com/numpy/numpy/pull/23601 fixed the issue for me.

**Comment by rgommers** [comment]
Great, thanks for the quick confirmation @RinCat!
