### ISSUE TITLE
BUG: Building on Windows / Python 3.11 / with MKL

### ISSUE THREAD

**Issue by farnyser** [numpy/numpy#23139]
### Describe the issue:

Hi

I'm trying to build a wheel of latest release ( v1.24.1) for python 3.11 / windows linking against MKL (2023.0.0)
I have trouble following the documentation.

I have updated `site.cfg` as : 

```[mkl]
include_dirs = C:\Program Files (x86)\Intel\oneAPI\mkl\2023.0.0\include
library_dirs = C:\Program Files (x86)\Intel\oneAPI\mkl\2023.0.0\lib\intel64
libraries = mkl_rt
lapack_libs =
```

Running `python setup.py build` hang for multiple *days* on the following line:  
> building extension "numpy.core._multiarray_umath" sources

Running `python wheel .` seems to create a wheel successfully, but when installed, importing numpy fails with 
> DLL load failed while importing _multiarray_umath: The specified module could not be found.

What am I missing ? 

### Reproduce the code example:

```python
import numpy
```

### Error message:

```shell
DLL load failed while importing _multiarray_umath: The specified module could not be found.
```

### Runtime information:

3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

### Context for the issue:

Upgrade to python 3.11 + need a MKL version for result stability

**Comment by mattip** [comment]
You may need to add the directories with the MKL DLLS using `os.add_dll_directory()`. If this works from the command line
```
>>> import os
>>> os.add_dll_directory('path/to/bindir')
>>> import numpy
```

then you can add it to a `_distributor_init.py` file in the top-level numpy directory. This file will be called before importing c-extension objects.

**Comment by farnyser** [comment]
It seems to make the wheel works! 
Can you confirm I don't need to build the umath module ? (it's replaced by MKL, right ?) 
Thanks

**Comment by mattip** [comment]
> I don't need to build the umath module ? (it's replaced by MKL, right ?)

We merged the `_multiarray` and `_umath` modules together a number of years ago, it is now `_multiarray_umath` like in the error message from the top of this issue. MKL is used instead of OpenBLAS to provide LAPACK and BLAS functions.

**Comment by farnyser** [comment]
Yes sorry, I was talking about that: 

> Running python setup.py build hang for multiple days on the following line:
>     building extension "numpy.core._multiarray_umath" sources

So I guess there is an issue but it's not blocking since I'm using MKL version instead. 
Thanks

**Comment by bookmagnus** [comment]
I have the same issue in _mulitarray_api.h it is calling the following
`PyObject *numpy = PyImport_ImportModule("numpy.core._multiarray_umath");`
but in my directory under numpy/core there is no multiarray_umath only something called _multiarray_umath.cp311-win_amd64.pyd? I don´t understand how to fix this issue, can you please help me?

**Comment by mattip** [comment]
@bookmagnus that file is a [c-extension module](https://docs.python.org/3/extending/building.html) that, from python, is called `numpy.core._multiarray_umath`. It has a valid [suffix](https://docs.python.org/3/library/importlib.html?highlight=extension_suffixes#importlib.machinery.EXTENSION_SUFFIXES).

Could you provide a little more context? What is calling `_import_array()`? You also probably need to follow the instructions in [this comment](https://github.com/numpy/numpy/issues/23139#issuecomment-1412323734) above.

I am going to close this issue since the original question was answered. If you still need help, please open a new issue describing what you are trying to do.
