### ISSUE TITLE
nan_to_num slow for large arrays

### ISSUE THREAD

**Issue by pedersor** [numpy/numpy#23140]
`numpy.nan_to_num` is very slow for large arrays (e.g. with size 1M+) whereas similar functions like `numpy.where` are not. Taking a quick look at the implementation below, it looks like a rather simple python for loop is used which is likely the cause of poor performance. Can this be improved? 

https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/lib/type_check.py#L404-L521

**Comment by rkern** [comment]
The `for` loop is not looping over individual values. `dest` is a 2-item tuple in the case of a complex dtype and a 1-item tuple otherwise. The iteration overhead should be minimal for large arrays.

**Comment by pedersor** [comment]
> The `for` loop is not looping over individual values. `dest` is a 2-item tuple in the case of a complex dtype and a 1-item tuple otherwise. The iteration overhead should be minimal for large arrays.

Thanks for clarifying this. After running some quick tests I think that the issue is that `nan_to_num` uses more memory. For sufficiently small array, I don't see a large difference between the timings. But for sufficiently larger arrays, `nan_to_num` seems to saturate my memory, resulting in vast slowdowns, whereas `where` did not. So it appears that `nan_to_num` simply has a larger memory overhead that may be hindering depending on available memory?

**Comment by mattip** [comment]
If you want, you can [use `copy=False`](https://numpy.org/devdocs/reference/generated/numpy.nan_to_num.html)

**Comment by pedersor** [comment]
> 

Works, thanks!
