### ISSUE TITLE
BUG: <numpy.random.Generator.choice probability shape in case of ndarray>

### ISSUE THREAD

**Issue by rajkifranciska** [numpy/numpy#23152]
### Describe the issue:

In case of numpy random generator choice, the input array _a_  can be an ndarray. However, if _p_ (the probabilities) is also an ndarray, I get the Error message: ValueError: p must be 1-dimensional

But if I flatten the probabilities, I get the Error message: 
ValueError: a and p must have same size

So I can't see how could one give probabilities in case of an ndarray. 

### Reproduce the code example:

```python
data = np.arange(8).reshape((2,4))
probs = np.array([[1, 1, 1, 1], [1, 1, 0, 0]])
rng = np.random.default_rng()
result = rng.choice(data,axis=1,p=probs)
```

### Error message:

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-a2b2c903a96c> in <module>
      2 probs = np.array([[1, 1, 1, 1], [1, 1, 0, 0]])
      3 rng = np.random.default_rng()
----> 4 result = rng.choice(data,axis=1,p=probs)
      5 print(result)

_generator.pyx in numpy.random._generator.Generator.choice()

ValueError: p must be 1-dimensional
```

### Runtime information:

1.19.5
3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

The random generator choice with an ndarray input is useful if we would like to randomly choose along an axis.

**Comment by rkern** [comment]
Right, when `choice()` is given an n-dimensional array and told to choose along a given axis, it isn't picking individual elements independently for each of the other axes. It's picking the whole sub-arrays that you would get from indexing along that axis. `p` must be a 1D array the same length as the chosen axis.

To give a concrete example, given a 2D array of choices with `axis=0`, `choice()` is going to choose whole _rows_ to put into the output. The individual elements from each row never get mixed up with each other.
