### ISSUE TITLE
No module named 'numpy.core._multiarray_umath' when exeucting matploitlib_cpp

### ISSUE THREAD

**Issue by bookmagnus** [numpy/numpy#23189]
### Describe the issue:

I am trying to use matploitlib_cpp on Windows 11 with Numpy 1.24.2 and Python 3.11, but I keep running in to the following error.
`Original error was: No module named 'numpy.core._multiarray_umath'`

This is what fails (returns nullptr)

`PyObject *numpy = PyImport_ImportModule("numpy.core._multiarray_umath");`

and the following line is comming from` ..\Python3.11\Lib\site-packages\numpy\core\include\numpy\__multiarray_api.h`

In my python installation path
`..\Python3.11\Lib\site-packages\numpy\core `
I have a file named  _multiarray_umath.cp311-win_amd64.pyd but no file named _multiarray_umath. Is this expected behavior?

### Reproduce the code example:

```python
#include "../matplotlibcpp.h"

namespace plt = matplotlibcpp;

int main() {
    plt::plot({1,3,2,4});
    plt::show();
}
```

### Error message:

```shell
OpenMP 2019
Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applicationsTraceback (most recent call last):
  File "C:\Python\Python3.11\Lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Python\Python3.11\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Python\Python3.11\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python3.11\Lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Python\Python3.11\Lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Projects\SFML-Games\SFML-ECS-SpaceInvaders\x64\Debug\SpaceInvaders.exe"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

Traceback (most recent call last):
  File "C:\Python\Python3.11\Lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Python\Python3.11\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Python\Python3.11\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python3.11\Lib\site-packages\matplotlib\__init__.py", line 108, in <module>
    import numpy
  File "C:\Python\Python3.11\Lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Python\Python3.11\Lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Projects\SFML-Games\SFML-ECS-SpaceInvaders\x64\Debug\SpaceInvaders.exe"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Runtime information:

>>> print(numpy.__version__); print(sys.version)
1.24.2
3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]

>>> print(numpy.show_runtime())
3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]

### Context for the issue:

It is a complete blocker for using libtorch with matplotlib_cpp

**Comment by seberg** [comment]
I am not sure what is going on, but it has nothing to do with NumPy, otherwise `print(numpy.__version__)` doesn't work, you can clearly import NumPy from Python, which means you can also import `numpy.core._multiarray_umath`.

Maybe there is some other weird error with your environment.  Or the program is running in a way that forbids simple loading of dynamic libraries (windows has some options for that IIRC).

In either case, I doubt we can help you, maybe the `matplotlib_cpp` people know common pitfalls.  These issues are basically never NumPy issues, NumPy is just the first C-module that you tend to import.

**Comment by seberg** [comment]
The file you saw is correct, its a dll with the name indicating the correct platform.  You are successfully importing NumPy in Python itself.  Thus it must exist.

**Comment by bookmagnus** [comment]
How can I debug this, it looks like _multiarray_umath.cp311-win_amd64.pyd is a binary file

**Comment by bookmagnus** [comment]
I got it working but using the release built binaries instead of debug binaries.

**Comment by seberg** [comment]
Python debugging on windows only works if the full stack is debugging binaries, so there is you reason.

**Comment by iamjadhav** [comment]
@bookmagnus 

I'm facing the same issue. Could you elaborate a bit on your fix?

**Comment by Sree0211** [comment]
> I got it working but using the release built binaries instead of debug binaries.

Hi, I am facing a similar issue, were you able to resolve the problem and run it in debug mode ?
