### ISSUE TITLE
BUG: cirrus CI runs the "upload wheels" job when there is nothing to do, the job fails

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23182]
I think this is fallout from #23127. @andyfaff could you take a look?

Cirrus CI has [been failing](https://cirrus-ci.com/github/numpy/numpy). The problem is twofold:
- the wheels_upload task always runs. It downloads miniconda, sets up a conda environment, installs anaconda-client, downloads the artifacts then sources `./tools/wheels/upload_wheels.sh` and runs `upload_wheels`, which usually will be a NOOP. This takes about 1.5 minutes to run and could be optimized to only do the anaconda setup if wheels need to be uploaded.
- [something fails](https://cirrus-ci.com/task/5683861573599232?logs=upload#L1571) in the download/setup of miniconda with
  ```
  # install miniconda for uploading to anaconda
  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  ...
  bash miniconda.sh -b -p ~/miniconda3
  miniconda.sh: line 29: HOME: unbound variable
  ```

As an aside, `wget` should be using `-q`

**Comment by andyfaff** [comment]
I'll skip the anaconda client install if it's not needed. Then I'll look into the install of miniconda. I don't know why it stopped working, that's 'funny'

**Comment by andyfaff** [comment]
I think this issue can be closed now. I checked that the wheels are currently being uploaded on scipy-wheels-nightly/numpy. In addition the cirrus-ci upload step only tries to upload when required.

**Comment by mattip** [comment]
Thanks @andyfaff
