### ISSUE TITLE
BUG: busday_count returns wrong results with begindates > enddates

### ISSUE THREAD

**Issue by eltoder** [numpy/numpy#23197]
### Describe the issue:

According to the documentation, busday_count

> Counts the number of valid days between begindates and enddates, not including the day of enddates. If enddates specifies a date value that is earlier than the corresponding begindates date value, the count will be negative.

However, [in the implementation](https://github.com/numpy/numpy/blob/6dadb8c40451e934075904f6acdfe341d3b8762e/numpy/core/src/multiarray/datetime_busday.c#L384), if begindates is greater than enddates, the dates are swapped and the result is negated. This has the effect of including the enddates and excluding begindates, which contradicts the above spec.

### Reproduce the code example:

```python
from datetime import date
import numpy as np

d1 = date(1999, 12, 30)
d2 = date(2000, 1, 1)
assert np.busday_count(d1, d2) == 2   # 1999-12-30 and 1999-12-31
assert np.busday_count(d2, d1) == -1  # 1999-12-31 only, end date is excluded
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/elt/code/numpy-test/busday.py", line 8, in <module>
    assert np.busday_count(d2, d1) == -1
AssertionError
```

### Runtime information:

Output from `import sys, numpy; print(numpy.__version__); print(sys.version)`
```shell
1.24.1
3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

Output from `print(numpy.show_runtime())`
```shell
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/elt/.local/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 16,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
```
### Context for the issue:

This breaks the invariant that
```python
count = numpy.busday_count(d1, d2)
numpy.busday_offset(d1, count, "forward" if count > 0 else "backward") == d2
```
for every d1 and every valid d2.

**Comment by eendebakpt** [comment]
@eltoder I think you are right that the documentation does not match the implementation. The easiest fix would be to adjust the documentation, but that will leave the invariant from your comment broken. On the other hand, the current implementation has the property that `np.busday_count(d1, d2)==- np.busday_count(d2, d1)`, which seems intuitive as well. 

Since I am not sure what the best fix is (update documentation, or change the implementation) I will leave the issue open for numpy devs to comment.

**Comment by eltoder** [comment]
@eendebakpt Yes, the current implementation is antisymmetric, which would be intuitive if the interval [begindates, enddates] was treated as closed. But the interval is treated as half-open, so you actually should expect the function to not be antisymmetric.

**Comment by mattip** [comment]
In the example given, `np.busyday_offset(d2, -2) == d1` raises an error `Non-business day date in busday_offset`. However using `date(2000, 1, 3)` works as expected. Can you provide a valid datetime pair that violates
```
count = numpy.busday_count(d1, d2)
numpy.busday_offset(d1, count, "forward" if count > 0 else "backward") == d2
```

**Comment by eltoder** [comment]
@mattip here you go
```python
d1 = date(2000, 1, 1)
d2 = date(1999, 12, 30)
count = np.busday_count(d1, d2)  # -2
d3 = np.busday_offset(d1, count, "forward" if count > 0 else "backward")  # numpy.datetime64('1999-12-29')
assert d2 == d3  # fails
```

**Comment by eltoder** [comment]
Another way to look at this, is to compare `np.busday_count` to a reference implementation:
```python
from datetime import timedelta
from more_itertools import numeric_range
import numpy as np

def busday_count(start, end):
    sign = 1 if start <= end else -1
    dt = timedelta(sign)
    return sign * sum(np.is_busday(date) for date in numeric_range(start, end, dt))
```
I think it's easy to argue that this implementation is correct and does exactly what the spec says. This implementation indeed returns -1 for `busday_count(date(2000, 1, 1), date(1999, 12, 30))`.

**Comment by mattip** [comment]
There is room for either a change in implementation, or a change in documentation:
> If `enddates` specifies a date value that is earlier than the corresponding `begindates` date value, __the values will be switched__ and the count will be negative. __Thus `np.busyday_count(a, b) == -np.busyday_count(b, a)`__. 

Either way, an example comparing `np.busyday_offset(d1, np.busyday_count(d1, d2), "backward") to  `d2` would help clarify that this is intended behaviour. I don't use `busyday`, is there previous art elsewhere or is NumPy the "source of truth" for this API?

**Comment by eendebakpt** [comment]
The code is quite old already. From the commits I gather @mwiebe is the original author.

**Comment by eltoder** [comment]
@mattip Yes, there's a good amount of prior art. For example, [QuantLib](https://www.quantlib.org/) is a well-established library with a lot of calendars, conventions, and business days counting functions. The same example in quantlib works as expected:
```python
import QuantLib as ql

d1 = ql.Date(30, 12, 1999)
d2 = ql.Date(1, 1, 2000)
cal = ql.WeekendsOnly()
assert cal.businessDaysBetween(d1, d2) == 2
assert cal.businessDaysBetween(d2, d1) == -1
```

**Comment by MatteoRaso** [comment]
> 

QuantLib gives you the option of deciding whether or not to include the beginning and ending dates, so that behaviour isn't set in stone. Since Numpy doesn't give you the option to decide whether or not the beginning and ending dates should be included or not, it might be justified to make `busday_count`'s behaviour different from the default behaviour for `businessDaysBetween`.

**Comment by eendebakpt** [comment]
The current implementation and documentation do not match, so I think we should just pick which one to adapt. I have no strong preference, but to see the impact of changing the implementation I created a draft PR #23229. 

Without any backwards compatibility considerations, I would prefer the implementation of the PR slightly over the current implementation.

**Comment by seberg** [comment]
Excluding both dates seems strange enough that maybe we can get away with changing this.  Although I do wonder if we can't also get away with deprecating this and pointing at a downstream library instead?  In general this seems hard to get right (should you have bank holiday support?), so that it feels better in a specialized library?

**Comment by MatteoRaso** [comment]
> Excluding both dates seems strange enough that maybe we can get away with changing this. Although I do wonder if we can't also get away with deprecating this and pointing at a downstream library instead? In general this seems hard to get right (should you have bank holiday support?), so that it feels better in a specialized library?

Another possibility is changing the function to be more like QuantLib equivalent, defaulting to the current behaviour but allowing the user to decide whether the start or end dates should be included. That would keep the function backwards compatible while solving the issue for users who don't like the current behaviour.

**Comment by eendebakpt** [comment]
There have been several options suggested:

1. Modify the docstring
2. Fix the bug (https://github.com/numpy/numpy/pull/23229)
3. Add an option to `busday_count` to select the type of exclusion for the end date (with updated docstring)

@seberg @mattip Can one of you make a decision? (deprecation can be done with any of the options, although with deprecation option 1 seems most logical)

**Comment by eltoder** [comment]
@seberg np.busday_count does support bank holidays already. Numpy provides a fairly complete business days functionally. So far I only found this bug and that a few less common roll methods are not implemented.

**Comment by seberg** [comment]
We discussed it a bit today, and basically decided we should just fix the bug since it seems blatently wrong.  Still need a release note of course!

It would be nice to move some of this out of NumPy, but I don't know how realistic it is, we did that for financial (which is in a similar boat, low maintenance, few users, and also a misfit) and that worked pretty well.

**Comment by eltoder** [comment]
@seberg I agree, it probably makes sense to move this into numpy financial. Maybe the other functions there can take advantage of calendars as well.

**Comment by avallee-eisler** [comment]
Honestly this function is so old, any kind of behavior change should really be more considerate. At the very least, providing some mean for users that rely on previous behavior to keep it, either through a flag to the function, or by providing some sample code on how to keep previous behavior with the new code.

Even though the documentation was not specifically correct for the cases where start date > end date, a lot of further expectations for this implicit behavior has been built with time.

Can someone advise on ways to get back the old behavior, which indeed was not in line with the documentation, but made more sense to me, and all the 12 years of users that relies on it?

**Comment by NewbiZ** [comment]
Honestly this function is so old, any kind of behavior change should really be more considerate. At the very least, providing some mean for users that rely on previous behavior to keep it, either through a flag to the function, or by providing some sample code on how to keep previous behavior with the new code.

Even though the documentation was not specifically correct for the cases where start date > end date, a lot of further expectations for this implicit behavior has been built with time.

Can someone advise on ways to get back the old behavior, which indeed was not in line with the documentation, but made more sense to me, and all the 12 years of users that relies on it?

**Comment by eendebakpt** [comment]
@NewbiZ For scalar arguments d1 and d2, the old behavior can be reproduced with
```
from datetime import date
import numpy as np

def busday_count_old_behavior(d1, d2, *args, **kwargs):
    if d2 < d1:
        d1 = np.datetime64(d1)-1
        d2 = np.datetime64(d2)-1
        return np.busday_count(d1, d2, *args, **kwargs)
    return np.busday_count(d1, d2, *args, **kwargs)

d1 = date(1999, 12, 30)
d2 = date(2000, 1, 1)
    
print(np.is_busday(d1), np.is_busday(d2))
print(f'busday_count: {np.busday_count(d1, d2)}, {np.busday_count(d2, d1)}')
print(f'busday_count: {busday_count_old_behavior(d1, d2)}, {busday_count_old_behavior(d2, d1)}')
```
(note: if you consider using this, make sure to run the old tests on this to check it fully valid). If you need to input d1 or d2 as a range, it should not be hard to modify the example above.

**Comment by eendebakpt** [comment]
On the numpy mailing list there is a discussion on moving the busday functionality out of numpy. See [[Numpy-discussion] Moving busday functionality to numpy-financial](https://mail.python.org/archives/list/numpy-discussion@python.org/message/G3FUF4UCCOBUE6XNJY7O4J2QZ7NB5DXR/)
