### ISSUE TITLE
Matplotlib 3.7.0 breaks circleci and refguide checks in  Numpy 1.24.x

### ISSUE THREAD

**Issue by charris** [numpy/numpy#23209]
This was in the maintenance/1.24.x branch running Python 3.8. I've fixed it there by pinning to v3.6.3 (#23208). It may be the case that this is specific to Python 3.8, which has been dropped in main, but I have opened this issue in case it persists.

**Comment by ksunden** [comment]
```diff
diff --git a/numpy/lib/twodim_base.py b/numpy/lib/twodim_base.py
index ed4f98704..6dcb65651 100644
--- a/numpy/lib/twodim_base.py
+++ b/numpy/lib/twodim_base.py
@@ -754,7 +754,7 @@ def histogram2d(x, y, bins=10, range=None, density=None, weights=None):
     >>> xcenters = (xedges[:-1] + xedges[1:]) / 2
     >>> ycenters = (yedges[:-1] + yedges[1:]) / 2
     >>> im.set_data(xcenters, ycenters, H)
-    >>> ax.images.append(im)
+    >>> ax.add_image(im)
     >>> plt.show()
 
     It is also possible to construct a 2-D histogram without specifying bin
```

This diff fixes the reflib test with mpl 3.7.0. (building the docs now to be sure the result is the same)

Modifying the `ax.images` (and friends) was deprecated in matplotlib 3.5 (see matplotlib/matplotlib#18216)

I do not believe this to be python version specific.
