### ISSUE TITLE
np.searchsorted has inconsited behavior when the datatype of a differs from v

### ISSUE THREAD

**Issue by flaviovdf** [numpy/numpy#23218]
When using `np.searchsorted` with differing data types the behavior of the function changes according to the types. That is,   `np.searchsorted` receives two arguments: (1) `a`: an array in ascending order; (2) `v`: a scalar or array of values to search in `a`. Apparently, when `a` has a "larger" data type than `v` the output is not the same as when `a` and `v` have the same data type. See example below. Colab link also provided.

```python
>>> data = [0.05, 0.15, 0.2]
>>> a = np.array(data, dtype=np.float64)
>>> v = np.float32(0.2)
>>> np.searchsorted(a, v)
3

>>> a = np.array(data, dtype=np.float64)
>>> v = np.float64(0.2)
>>> np.searchsorted(a, v)
2

>>> a = np.array(data, dtype=np.float32)
>>> v = np.float64(0.2)
>>> np.searchsorted(a, v)
2

>>> a = np.array(data, dtype=np.float32)
>>> v = np.float32(0.2)
>>> np.searchsorted(a, v)
2
```

Tested on colab with numpy 1.21 and also locally with versions 1.23 and 1.24.
https://colab.research.google.com/drive/16L25PQ9EK4T5HmHaudto-krIMA7B9qXI?usp=sharing

**Comment by mattip** [comment]
This is due to the rounding of `0.2` when making it into a float. There is no exact representation, the values are approximate:
```
np.float32(0.2) > np.float64(0.2)   # prints True
```

**Comment by flaviovdf** [comment]
Make's sense, closing. Just to be clear, this kind of issue may be common when you have code that rely both on Jax and on Numpy. Jax (or PyTorch, Tensorflow) defaults to float32. Numpy to machine precision.
