### ISSUE TITLE
BUG: `where` keyword argument is ignored in `_array_ufunc__`/`__array_function__` if it is not an instance of `numpy.ndarray`

### ISSUE THREAD

**Issue by byrdie** [numpy/numpy#23219]
### Describe the issue:

If the `where` keyword argument is a `ndarray` duck type that implements `__array_ufunc__` and `__array_function__`, I would've expected its implementation of those methods to be used. Instead, it appears that `where` is just ignored if it is not an instance of `numpy.ndarray`.

### Reproduce the code example:

```python
import dataclasses
import numpy as np

@dataclasses.dataclass
class DuckArray(np.lib.mixins.NDArrayOperatorsMixin):

    value: np.ndarray

    def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
        print("in DuckArray.__array_ufunc__")
        inputs = [inp.value if isinstance(inp, DuckArray) else inp for inp in inputs]
        kwargs = {k: kwargs[k].value if isinstance(kwargs[k], DuckArray) else kwargs[k] for k in kwargs}
        return DuckArray(getattr(ufunc, method)(*inputs, **kwargs))

    def __array_function__(self, func, types, args, kwargs):
        print("in DuckArray.__array_function_")
        args = [arg.value if isinstance(arg, DuckArray) else arg for arg in args]
        kwargs = {k: kwargs[k].value if isinstance(kwargs[k], DuckArray) else kwargs[k] for k in kwargs}
        return DuckArray(func(*args, **kwargs))

def test_ufunc():
    a = np.random.random(5)
    b = DuckArray(a > 0.5)
    c = np.negative(a, where=b)     # doesn't print "in DuckArray.__array_ufunc__" :(
    print(type(c))                  # prints <class 'numpy.ndarray'>
    print(c)

def test_function():
    a = np.random.random(5)
    b = DuckArray(a > 0.5)
    c = np.sum(a, where=b)          # doesn't print "in DuckArray.__array_function_" :(
    print(type(c))                  # prints <class 'numpy.float64'>
    print(c)
```

### Runtime information:

```
1.24.1
3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
```
```
print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None
```

### Context for the issue:

I am working on an array duck type that tries to propagate uncertainties similar to [`astropy.uncertainty.Distribution`](https://docs.astropy.org/en/stable/uncertainty/index.html). I would like to make sure that uncertainties propagate properly in the case where the `where` keyword argument is uncertain, but the inputs are exact.

**Comment by mhvk** [comment]
It was a conscious decision to only consider inputs and outputs, not any other optional arguments -- see [the original NEP](at  https://numpy.org/neps/nep-0013-ufunc-overrides.html). Indeed, we specifically removed the ability to override on optional arguments like `axis` for reductions (which was possible in the initial implementation).

In hindsight, compared with `__array_function__` which looks at all possible array-shaped inputs, it was perhaps a mistake to exclude `where`, which can be array-shaped. 

Is there a specific reason you wanted to override `where` while not having inputs/outputs of similar type? Or is this issue mostly just out of surprise that it didn't work?

**Comment by byrdie** [comment]
@mhvk, thanks for pointing out the original NEP, I hadn't read that documentation yet.

I sort of mentioned this above, but I am trying to implement an array type that represents uncertainties, very similar to `astropy.uncertainty.Distribution`, and I want to make sure uncertainties are propagated correctly through any possible numpy operation.

In the parlance of `astropy.uncertainty.Distribution` (for simplicity of understanding, my library has a bit different syntax), I want something like this to work:
```python3
import numpy as np
import astropy.uncertainty as unc
a = np.random.random(11)
b = unc.normal(np.random.random(11), std=0.1, n_samples=21) > 0.5
c = np.sum(a, where=b)
```
In astropy the above code fails for a different reason, but my code is designed to make this work if `numpy.ndarray.__array_function__` called `where.__array_function__` when all the other inputs return `NotImplemented`.

**Comment by mhvk** [comment]
@seberg, @shoyer - what do you think? My sense is that for consistency with `__array_function__`, `__array_ufunc__` should probably also look at `where` since it can be an array.

@byrdie - thanks for the example, I can indeed see how it might come about that one wants to try summing with a mask that is itself a distribution based on some previous calculation (even if it is perhaps not the most likely thing!).

**Comment by byrdie** [comment]
@mhvk, the code example in my original post tries to test if `where.__array_function__` is called from `__array_function__` but it is the same result as `__array_ufunc__`, it is ignored. Do you know if there is something wrong with my example?

Regardless, I'm happy to try and open a PR to resolve this issue if we decide that we want to fix it.

**Comment by seberg** [comment]
Overall, I don't see a problem with just including `where`.  The use-case is sensible and interesting, albeit tricky.  For example, if you look at it from a dtype promotion point of view the formerly ignored `where` suddenly becomes important for promotion!
(if uncertainty is a dtype, it would promote the other inputs to an uncertainty)

I suppose checking it might need some downstream adjustments (although in practice I suspect it would rarely matter).  So I wouldn't backport it, but it seems to me the use-case outweighs any reservations.

(I am *not* sure what `__array_function__` does with `where=` in all cases at this time!)

I would be interested in an uncertainty dtype, but this is one thing that will be harder to figure out for the dtype promotion case than for `__array_ufunc__` and `__array_function__` :).

**Comment by seberg** [comment]
You could also say that making `where=` not strictly bool, makes a binary operation actually ternary, while the current `where=` is just a mask.  But `__array_ufunc__` seems flexible enough to allow that without much thought.

**Comment by mhvk** [comment]
@byrdie - `np.sum` is also a `ufunc` (specifically, `np.add.reduce`) - so I think we really only have to worry about `__array_ufunc__`.

@seberg - as you note, the change to make is quite small; I agree that this is super unlikely to affect anyone, yet be helpful. Also agree that this should not be back-ported. I also agree that doing this correctly for any class is non-trivial -- but that at some level is not numpy's problem.

**Comment by mhvk** [comment]
@byrdie - separately, if in the process of working on your library, you find things that would make `Distribution` better, please do raise and issue or submit a PR! `Distribution` definitely needs follow-up, to make it work well with `Time`, `SkyCoord`, etc.

**Comment by byrdie** [comment]
@seberg, I should note that my current implementation of uncertainties is just an array duck type with a privileged axis for keeping track of the uncertainties, not a dtype, so the normal dtype promotion rules still apply. That being said, maybe an uncertainty dtype would be the way to go, I hadn't even considered that!

Would someone mind pointing me to where I would make this change? I can't seem to find the spot where `__array_ufunc__` and `__array_function__` does this yet.

**Comment by byrdie** [comment]
@mhvk, thanks for pointing out that `np.sum` is a `ufunc`, I changed the `test_function` test to use `numpy.std` and it does indeed work as promised.

I have identified a few issues with `astropy.uncertainty.Distribution`, I'll try to raise those issues over there shortly.

**Comment by seberg** [comment]
@byrdie this is here: https://github.com/numpy/numpy/blob/main/numpy/core/src/umath/ufunc_object.c#L4073

you would have to extend it to explicitly pass `where_obj` as well and then expand the function (in `override.c`) the same way and check it.

I would be happy to experiment/help with experimenting with uncertainties as a dtype, but this is one of those things that will be harder to figure out there.  And in either case, it would be a longer game, while this can work right now for you.  Even a dual solution might be interesting (this is really much the same story as a unit dtype).

**Comment by seberg** [comment]
We forgot to close this last year, closing.
