### ISSUE TITLE
ENH: sort 16-bit floats without converting to 32-bit floats

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23215]
PR #22315 added AVX512 sorting for 16-bit and 64-bit floats. Along the way we noted:
>  Sort operation mainly based on 16-bit shuffle/permuting instructions has nothing to do with FP unit except for the part that related to comparison wouldn't affect that much on performance and it can be numerically emulated without even the need for cast between single/half precision.

> ... then implementing a float16 sort without casting float16 to float32 would also speed up non-AVX512 architectures.

I think the code in question starts here but I am not sure where the actual implementation of the half-float math is. https://github.com/numpy/numpy/blob/0bd56e7ec12f8ceeb8d082340e71e60b873d5c57/numpy/core/src/npysort/quicksort.cpp#L114

**Comment by r-devulap** [comment]
@mattip `quicksort_(type *start, npy_intp num)` is the template implementation of all dtypes including half-float. The `Tag `information tells which dtype it is. The quicksort implementation uses `Tag::less`, which uses [HALF_LT  ](https://github.com/numpy/numpy/blob/0bd56e7ec12f8ceeb8d082340e71e60b873d5c57/numpy/core/src/npysort/npysort_common.h#L176) for comparison and then sort based on it. It relies on: 

https://github.com/numpy/numpy/blob/0bd56e7ec12f8ceeb8d082340e71e60b873d5c57/numpy/core/src/npysort/npysort_common.h#L145-L172

The comparison is done using bit operations and seems pretty efficient. There is no conversion to FP32 and back.

**Comment by mattip** [comment]
Got it, thanks. Then it seems there is nothing to be done here. The massive speedup in #22315 for 16-bit int and float is entirely due to specialized operations when packing 32 16 bit objects into 512-bit registers. Quite impressive.
