### ISSUE TITLE
BUG?: New SIMD quicksort code may have some issues

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#23234]
A quick heads-up that the x86-simd-sort code (I downloaded HEAD from Github) may have an issue sorting large arrays.

I noticed incorrect results when integrating this into our [vqsort benchmark](https://github.com/google/highway/pull/1140). Happy to discuss in [HN comments](https://news.ycombinator.com/item?id=34810610) or here.

_Originally posted by @jan-wassenberg in https://github.com/numpy/numpy/issues/22315#issuecomment-1434766714_

---

Another thing is that I am not sure that stability guarantees for NaNs has been discussed enough (comment above that one).

**Comment by r-devulap** [comment]
I think both issues were false alarms. As for the NANs, I have added tests in #22315  to ensure we always sort NANs to the end, so I am pretty sure that isn't a problem.

**Comment by seberg** [comment]
Cool, thanks, lets close it then :).
