### ISSUE TITLE
BUG: setting an array element with a sequence and the requested array has an inhomogeneous shape after 1 dimensions.

### ISSUE THREAD

**Issue by Greesh-N** [numpy/numpy#23231]
### Describe the issue:

The below piece of code which is taking sum of a simple Neural Network Model stops working with numpy version 1.24 (was working with numpy version 1.21.0). Can someone please suggest what is the change in numpy which is causing this issue to occur.

### Reproduce the code example:

```python
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.linear1 = nn.Linear(60, 100)
        self.linear2 = nn.Linear(100, 10)

    def forward(self, x):
        x = self.linear1(x)
        x = self.linear2(x)
        return x

def Sum(agg_model, models):
    state_dicts = [model.state_dict() for model in models]
    state_dict = agg_model.state_dict()
    for key in models[0].state_dict():
        model_state=[state[key] for state in state_dicts]
        print(f"{model_state}")
        state_dict[key] = np.sum(model_state, axis=0) 
    agg_model.load_state_dict(state_dict)
    return agg_model
if __name__ == '__main__':
    model = []
    for i in range(2):
        model.append(Net())
    agg_model = Net()
    Sum(agg_model, model)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/ggreeshma/patrick-changes2/openfl/openfl-tutorials/experimental/error_reproduce.py", line 33, in <module>
    Sum(agg_model, model)
  File "/home/ggreeshma/patrick-changes2/openfl/openfl-tutorials/experimental/error_reproduce.py", line 24, in Sum
    state_dict[key] = np.sum(model_state, axis=0) 
  File "<__array_function__ internals>", line 200, in sum
  File "/home/ggreeshma/miniconda3/envs/openfl-practice/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2324, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/home/ggreeshma/miniconda3/envs/openfl-practice/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

### Runtime information:

Numpy version:1.24.0
python:3.8

**Comment by mattip** [comment]
I think the problem is that the call `np.sum(model_state, axis=0)` is using a `model_state` that is not a numpy ndarray. Is it some list-of-lists with unequal number of objects in the sublitsts? This no longer silently creates an object array in more recent NumPy versions. If so, you could do something like `np.sum(np.array(model_state, dtype=object), axis=0)`.

**Comment by Greesh-N** [comment]
I think  it is not list of lists with unequal number of object. It is a tensor which contains multiple array Because Same model_state works with lower versions of numpy(numpy 1.21.0 and 1.22.0). Can you please confirm exactly why we are getting this type of issue in version 1.24.0 and not in lower versions? If it is the problem that it is not numpy ndarray then why this error not observed in earlier version?

**Comment by seberg** [comment]
Because you can operate just fine on the 1-D array that `np.array(model_state)` used to give.  Matti gave the workaround, if the "model state" is a list of NumPy arrays, even just using Python `sum()` (rather than NumPy) would make sense here and give the same results.

Going to close, if you want more hints as to what is going on, please provide the exact information for what `model_state` is, and we may help you.

**Comment by francescoboc** [comment]
> I think the problem is that the call `np.sum(model_state, axis=0)` is using a `model_state` that is not a numpy ndarray. Is it some list-of-lists with unequal number of objects in the sublitsts? This no longer silently creates an object array in more recent NumPy versions. If so, you could do something like `np.sum(np.array(model_state, dtype=object), axis=0)`.

"This no longer silently creates an object array in more recent NumPy versions." ...why?!

**Comment by mattip** [comment]
See [NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html)
