### ISSUE TITLE
BUG: `np.multiply.outer` hangs in multiprocessing

### ISSUE THREAD

**Issue by DanielHabenicht** [numpy/numpy#23244]
### Describe the issue:

Executing multiple (more than 1) `np.multiply` calls with a sufficiently big dataset causes a job in multiprocessing to hang. 

### Reproduce the code example:

```python
from multiprocessing import Pool, cpu_count
import numpy as np
from tqdm import tqdm


def task(num):
    # Just some setup from the codebase the bug seen the first time
    # you might have to increase these for the bug to show.
    T = 10000
    N = 100

    K0 = np.zeros((N, N))
    K1 = np.zeros((N, N))
    Kd = np.zeros((N, N))

    np.fill_diagonal(K0, 0)
    np.fill_diagonal(K1, 1)
    np.fill_diagonal(Kd, 0)

    # Commenting out either of these remove the program hanging
    test1 = np.multiply.outer(K0, np.ones(T))
    test2 = np.multiply.outer(K1, np.ones(T))


if __name__ == "__main__":
    with Pool(processes=cpu_count() - 1) as p:
        # Bug only shows if queing more Jobs than CPU Counts
        jobs = [p.apply_async(func=task, args=[num]) for num in range(cpu_count() + 2)]

        for job in tqdm(jobs):
            job.get()

```

### Error message:

```shell
None, program hangs.
```

### Runtime information:

```bash
>>> print(numpy.__version__)
1.24.2
>>> print(sys.version)
3.10.9 (main, Jan 11 2023, 15:12:53) [GCC 10.2.1 20210110]
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/workspaces/LDIMBench/.venv/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 1,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None
```
The code was executing in a [Devcontainer](https://github.com/TUMT2022/LDIMBenchmark/blob/main/.devcontainer/devcontainer.json) on a Windows 11 machine.

### Context for the issue:

I already had a look at https://github.com/numpy/numpy/issues/17752 and https://github.com/numpy/numpy/issues/5752 but adding the environment variables did not help. I tried: 
```bash
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1;
```

**Comment by DanielHabenicht** [comment]
Using `np.tensordot(K0, np.ones(T), axes=((), ()))` also does not help. 
Even wrapping the offending lines into a `multiprocessing.Lock()` does not seem to help. 

Only thing that might be helping is: using `multiprocessing.get_context("spawn").Pool()`

**Comment by seberg** [comment]
Have you checked that the code works if you do nothing at all in your task?

**Comment by DanielHabenicht** [comment]
The code works as soon as I comment out one of the `np.multiply` lines

**Comment by seberg** [comment]
Well, I get things like:
```
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

So, I suspect it just works on a whim.

**Comment by DanielHabenicht** [comment]
I think thats architecture dependent. I updated the example.

**Comment by DanielHabenicht** [comment]
I just tried it again on a Codespace on this repo: https://github.com/DanielHabenicht/bug-reproduction.numpy/tree/main
It also hangs.

**Comment by DanielHabenicht** [comment]
I adjusted the values on the Codespace reproduction. 

> And you checked that your machine has enough memory to actually run this smoothly?

yeah, it should. On my machine its 32GB. 
But your comment gives me the notion that it might be clashing when reserving the RAM? 

Choosing a matrix which takes to much space on the Codespace results in `numpy.core._exceptions._ArrayMemoryError: Unable to allocate 7.45 GiB for an array with shape (100, 100, 100000) and data type float64` for (T=100000). 

Using T=10000 runs smoothly on the Codespace (most of the time)

Using T=20000 hangs.

**Comment by seberg** [comment]
I don't know, but there is absolutely *nothing* special about `np.multiply.outer` or multiprocessing, which projects like sklearn probably even test on their CI.  An issue with the packaged openblas in a wheel might be possible (depending on how you installed), but it isn't even used here.

So basically, I see no way that this has anything to do with NumPy.  Swapping is the only thought I have right now.  But considering how likely a NumPy issue is, that is as much debugging help I can give right now.

**Comment by seberg** [comment]
My idea still stands, and I am very sure it is correct: You are low on memory, probably running out of it maybe up to the point of jobs dying.

Going to close the issue for now.

**Comment by DanielHabenicht** [comment]
But shouldn't numpy throw an error then, as it does for the other case? (`numpy.core._exceptions._ArrayMemoryError: Unable to allocate 7.45 GiB for an array with shape (100, 100, 100000) and data type float64`)

**Comment by seberg** [comment]
No, unfortunately that is not how it works.  For various reasons, the kernel (any kernel) will just say the memory exists and then throw you out of the plane mid-flight when it notices that it doesn't.

It might be that you can improve the probability of getting an error with certain `madvise` calls, but I think I once tried and it wasn't so simple.

> and the whole process ends (with an error instead of hanging)

that should depend on who the OOM killer throws out of the flying plane.

**Comment by DanielHabenicht** [comment]
Thanks for the comment. 

I could also reproduce the error without multiprocessing (if thats of interest). 
But basically it seems as you suggested. There is not enough RAM to perform the `multiply.outer` calculation.

**Comment by DanielHabenicht** [comment]
To get a clearer error message I can suggest using the newer Python `ProcessPoolExecutor`: https://stackoverflow.com/questions/61492362/multiprocessing-pool-hangs-if-child-process-killed
