### ISSUE TITLE
BUG: `numpy.random.randint` inconsistently raises `ValueError`s

### ISSUE THREAD

**Issue by JulianoLagana** [numpy/numpy#23246]
### Describe the issue:

`numpy.random.randint` samples `[1]` happily with these parameters
```
np.random.randint(1.1, 2.9, size=1)
```
but raises a `{ValueError} low >= high` for
```
np.random.randint([1.1], [2.9], size=1)
```

### Reproduce the code example:

```python
import numpy as np

# No problems
np.random.randint(1.1, 2.9, size=1)

# Raises error
np.random.randint([1.1], [2.9], size=1)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/juliano/Code/wood-analysis/test.py", line 7, in <module>
    np.random.randint([1.1], [2.9], size=1)
  File "mtrand.pyx", line 765, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1262, in numpy.random._bounded_integers._rand_int64
  File "_bounded_integers.pyx", line 686, in numpy.random._bounded_integers._rand_int64_broadcast
ValueError: low >= high
```

### Runtime information:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.1
3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
```

```
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'armv8',
  'filepath': '/Users/juliano/Code/wood-analysis/.venv/lib/python3.10/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None
```

**Comment by rkern** [comment]
We won't be fixing `np.random.randint()` due to [NEP 19](https://numpy.org/neps/nep-0019-rng-policy.html).

I *think* this is fixed for `Generator.integers()` by #23186. @seberg, can you double-check (I'm not in a position to build from source and test at the moment)?

The source of the error is that when the input arrays are floating point, the slow path converts the open upper bound to integer and subtracts `1` to account for the open upper bound, but then does the `np.greater(low_arr, high_arr_converted)` comparison with the floating-point `low_arr`. `1.1 > (int(2.9)-1)`, so we get the error. From my reading, I think #23186 converts both lower and upper bounds to integers first, then does the comparison, so we should get consistent behavior (i.e. treating it as `rng.integers([1], [2])`).

**Comment by seberg** [comment]
> I think this is fixed for Generator.integers() by https://github.com/numpy/numpy/pull/23186. @seberg, can you double-check (I'm not in a position to build from source and test at the moment)?

Yes, the second example gives the same (correct) result now.  I would not backport it, though.  Passing floats to integer generation seems rather niche, and the PR is not super trivial.

Anyway, thanks for the report, happy to say that it was just fixed yesterday.

**Comment by seberg** [comment]
@rkern that code is actually shared between both.  Do you think even the error path/change is not OK with respect to NEP 19?
I think changes should only be possible in cases that either gave an incorrect error or incorrectly did not give an error.

If we want to actually ensure the same (incorrect) errors/results I would need to follow up to duplicate the code, probably.
(All cases are rather odd and niche, float inputs or lower bound larger than `2**63`...)

**Comment by rkern** [comment]
I'm not too fussed about it.

**Comment by rkern** [comment]
Well, raising errors that did _not_ raise errors before (even incorrectly) is more of a problem. I would restore the legacy code paths for `RandomState`.

**Comment by seberg** [comment]
The only example I can actually think of is something like this:
```
In [2]: np.random.randint([np.iinfo(np.int64).max+1], [np.iinfo(np.int64).max], size=1)
Out[2]: array([5004278564393233689])
```
huge values, where the lower bound is larger, but the comparison fails (because of being done in float64).  After that, I guess it is cast to uint64 for generation (so you get some huge interval in reality).
