### ISSUE TITLE
BUG: ma.apply_along_axis is broken after commit 138bba5 

### ISSUE THREAD

**Issue by andyfaff** [numpy/numpy#23258]
### Describe the issue:

A scipy CI entry has recently acquired segfaults. The CI entry installs numpy from the git repo. I did a manual bisection and figured out that commit 138bba5 onwards causes issues. 

xref https://github.com/scipy/scipy/issues/18025.

### Reproduce the code example:

```python
def my_func(a):
    """Average first and last element of a 1-D array"""
    return (a[0] + a[-1]) * 0.5

import numpy as np
b = np.ma.array([1.0, 3.0])
np.ma.apply_along_axis(my_func, 0, b)
```

### Error message:

```shell
uncaught target signal 11 (Segmentation fault) - core dumped
```

### Runtime information:

```
1.25.0.dev0+742.g138bba5ff
3.11.2 (main, Feb  8 2023, 14:49:25) [GCC 11.3.0]

WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.0.dev0+742.g138bba5ff',
  'python': '3.11.2 (main, Feb  8 2023, 14:49:25) [GCC 11.3.0]',
  'uname': uname_result(system='Linux', node='a9b6a04e7c66', release='5.15.49-linuxkit', version='#1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3', 'SSE41', 'POPCNT', 'SSE42'],
                      'not_found': ['AVX',
                                    'F16C',
                                    'FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None
```

**Comment by seberg** [comment]
Argg, I think the PutTo cleanup goto's can happen before the (new) init stuff.  That must be the reason.  I find it surprising that the compiler doesn't warn, since the definitions come after the goto?

**Comment by seberg** [comment]
Sorry, to those who noticed:  Branch protection was not set up as strict as I thought and I had recently changed my local setup to use git rather than https (effectively read only), since I hoped it would make fetching/pushing to PRs easier.
Turns out, that I was mistaken about it being safe from pushing accidentally, since branch protection should ensure that.

**Comment by seberg** [comment]
Anyway, the issue is really fixed (and another cleanup issue in putmask, that I missed).  The commits are pretty minimal, so I think its best to just leave it at that (and I increased branch protection).
