### ISSUE TITLE
numpy documentation code block

### ISSUE THREAD

**Issue by QuantFreedom1022** [numpy/numpy#23253]
this isn't a question about numpy or a problem with the documentation but i am wondering how they make their code blocks so that when you want to copy the info in the code block examples that you aren't able to select those >>> things ... that is the most annoying thing in the world on other website but numpy it doesn't happen ... 

i want to make the same thing on my website but don't know how its done ... does anyone know or can someone point me in the direction to how that is done?

here is an example at the bottom of the page

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html

**Comment by rkern** [comment]
It's a feature of the [PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html) (at least; there may be other implementations that do something similar).

**Comment by QuantFreedom1022** [comment]
yeah i realized that it is more of a CSS issue 
.highlight .gp, .highlight .go {
    -webkit-user-select: none;  /* Chrome all / Safari all */
    -moz-user-select: none;     /* Firefox all */
    -ms-user-select: none;      /* IE 10+ */
    user-select: none;          /* Likely future */      
  }

this was the answer i was looking for :)
