### ISSUE TITLE
BUG: `np.take` function after pickling is about 3 times faster on ubuntu than on windows

### ISSUE THREAD

**Issue by anmyachev** [numpy/numpy#23266]
### Describe the issue:

Hello Numpy developers, I'm one of [Modin](https://github.com/modin-project/modin) developers.

When investigating the difference in performance on a Windows and Linux system (with the same hardware), it turned out to simplify the original code containing Modin to just two dependencies - pandas and numpy. 

**I'm wondering why `np.take` function after pickling is about 2.7 times faster on ubuntu than on windows.**
Data serialization is one of Modin's most fundamental mechanisms, which is why this effect is so interesting to us. Any information would be valuable in finding the cause of this behavior. Thank you!

Current results:

On Ubuntu:
```bash
np.take time: 12.79281759262085 <-- interesting part
custom_iloc time: 13.671087980270386
------------------------------------
pickle time: 6.836403846740723
np.take time: 4.713924169540405 <-- interesting part
custom_iloc+pickle time: 12.220834732055664
```

On Windows:
```bash
np.take time: 12.800208330154419 <-- interesting part
custom_iloc time: 13.644665002822876
------------------------------------
pickle time: 13.562321186065674
np.take time: 12.507266283035278 <-- interesting part
custom_iloc+pickle time: 26.849644422531128
```

### Reproduce the code example:

```python
import numpy as np
import pandas as pd
import time


np.random.seed(1234)
count_rows = 15_000_000
examples = ["wert", "ghjk", "grh", "grhtj", "qbyk", "htl", "kli", "yjk", "fgk", "sdghjk"]
col_names = [f"col{idx}" for idx in range(8)]
df = pd.DataFrame(np.random.choice(examples, size=(count_rows, 8)), columns=col_names)
print("dataframe generated")

# The reproducer is designed for workflows that start by reading csv files.
df.to_csv("test_df2.csv", index=False)
df = pd.read_csv("test_df2.csv")
print("file read")


def custom_iloc(arrays):
    np.random.seed(1234)
    permut = np.random.permutation(len(arrays[0][0]))
    start = time.time()
    for idx in range(len(arrays)):
        _ = np.take(arrays[idx], permut, axis=1)
    print(f"np.take time: {time.time()-start}")



s = time.time()
custom_iloc(df._mgr.arrays)
print(f"custom_iloc time: {time.time() - s}")

print("------------------------------------")

st = time.time()
st2 = time.time()

'''
# the difference is visible (but not as big)
# if you use this code instead of pickling through pickle
arrays = [None] * len(df._mgr.arrays)
for idx in range(len(df._mgr.arrays)):
    temp = df._mgr.arrays[0].__reduce__()
    arr = temp[0](*temp[1])
    arr.__setstate__(temp[2])
    arrays[idx] = arr
'''
import pickle
arrays = pickle.loads(pickle.dumps(df._mgr.arrays))
print(f"pickle time: {time.time()-st2}")

custom_iloc(arrays)
print(f"custom_iloc+pickle time: {time.time() - st}")
```

### Runtime information:

I have the same dependencies on both systems:
```bash
pandas                    1.5.3                    pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
```

Output of `numpy.show_runtime()` on Ubuntu:
```bash
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '.../conda/envs/test_env/lib/python3.9/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None
```

Output of `numpy.show_runtime()` on Windows:
```bash
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '...\\miniconda3\\envs\\test_env\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 24,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None
```

**Comment by seberg** [comment]
I did not try it out. But the most likely difference would be that the default integer type on windows is int32, but indexing uses 64bit on 64bit systems.
On linux, both match up, so the default integer is also the fastest integer type for indexing.

In that sense, if you end up doing indexing (and honestly in general), putting a `dtype=np.intp` somewhere will probably fix the speed difference.  If not, it might be interesting to look closer.

I do have a somwhat hazy plan to make `intp` the default integer in NumPy eventually, but it is a rather large change that *will* break some people.

Of course, some indexing routines could also be optimized for 32bit integer indices in principle.

**Comment by anmyachev** [comment]
> I did not try it out. But the most likely difference would be that the default integer type on windows is int32, but indexing uses 64bit on 64bit systems. On linux, both match up, so the default integer is also the fastest integer type for indexing.
> 
> In that sense, if you end up doing indexing (and honestly in general), putting a `dtype=np.intp` somewhere will probably fix the speed difference. If not, it might be interesting to look closer.
> 
> I do have a somwhat hazy plan to make `intp` the default integer in NumPy eventually, but it is a rather large change that _will_ break some people.
> 
> Of course, some indexing routines could also be optimized for 32bit integer indices in principle.

Thanks @seberg for the answer! 
If I understood you correctly, then the following change does not speed up `np.take` on a Windows machine:
`permut = np.random.permutation(len(arrays[0][0])).astype("intp")`

**Comment by seberg** [comment]
Yes, that was my thought.  If htat isn't the case, I think you may have to profile on windows to see if there is something obvious (i.e. maybe on MSVC some function is not inlined when it should be).
But results can fluctuate heavily sometimes (due to how malloc is implemented) also.  In any case, in that case I don't know any obvious difference.

**Comment by anmyachev** [comment]
> Yes, that was my thought. If htat isn't the case, I think you may have to profile on windows to see if there is something obvious (i.e. maybe on MSVC some function is not inlined when it should be). But results can fluctuate heavily sometimes (due to how malloc is implemented) also. In any case, in that case I don't know any obvious difference.

I don't have enough experience in this. Maybe NumPy has a tutorial in the documentation on how to do this? Can you advise where to look?

**Comment by rkern** [comment]
I didn't see it on my Ubuntu setup with an older numpy `1.21.6`; the `take` was just as slow with and without pickling. Something changed in `1.22`, maybe [NEP 49 allocators](https://numpy.org/neps/nep-0049.html)?

**Comment by seberg** [comment]
Sorry, I realize the interesting part is that copying the array once on linux makes things 3 times as fast maybe.

I had a hunch, and just tried that I disable hugepages (as root do `echo never > /sys/kernel/mm/transparent_hugepage/enabled`, cat first maybe, the default is typically `always`, but could also be `madvise`).  Once I do that I always get the slow result.  So my suspicion is that the way pandas reads the cvs causes it to be stored not as huge pages, but in normal pages.  The copy would ensure hugepages (I suppose loadtxt might be the same in this regard, but not sure).

NEP 49 shouldn't have any influence, since it isn't modified here and in the end we just have a memory pointer either way internally.

**Comment by anmyachev** [comment]
> > I don't have enough experience in this. Maybe NumPy has a tutorial in the documentation on how to do this? Can you advise where to look?
> 
> I personally like using [`py-spy`](https://github.com/benfred/py-spy) for this. You'll need to use the `--native` flag so that stack frames in C get included in the profile.

@ngoldbaum Thank you, I will explore it.

> Sorry, I realize the interesting part is that copying the array once on linux makes things 3 times as fast maybe.

> I had a hunch, and just tried that I disable hugepages (as root do echo never > /sys/kernel/mm/transparent_hugepage/enabled, cat first maybe, the default is typically always, but could also be madvise). Once I do that I always get the slow result. So my suspicion is that the way pandas reads the cvs causes it to be stored not as huge pages, but in normal pages. The copy would ensure hugepages (I suppose loadtxt might be the same in this regard, but not sure).

> NEP 49 shouldn't have any influence, since it isn't modified here and in the end we just have a memory pointer either way internally.

@seberg looks like I have `madvise` option selected (on ubuntu):
```bash
cat /sys/kernel/mm/transparent_hugepage/enabled
always [madvise] never
```
Apparently I need to try to enable large pages on Windows? (if at all possible)

**Comment by seberg** [comment]
While I think windows has hugepages, I suspect it doesn't work as easily as transparent huge pages on newer kernels (we have switch for <4.5 or something because they were very slow with it often).  Where it basically just works even with new `malloc` (yes, we do call madadvise, but it is often even set to "always" anyway nowadays).

OTOH, if it can be made to work reasonably on windows, that could be interesting!  I guess the question is if the current support on windows isn't more like the one on old kernels, which was too slow with memory defragmentation or so, so tends to be not useful in practice.

**Comment by seberg** [comment]
Closing the issue for now, thanks.  It is an interesting effect, but I don't really see any actionable thing to be done about it.
