### ISSUE TITLE
<Pleaserror: Command "gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNPe write a comprehensive title here>

### ISSUE THREAD

**Issue by yourexodus** [numpy/numpy#23267]
### Steps to reproduce:

Hello, I am using OS  Win 10.  I am trying to create my first build. I am using the community edition of pycharm. I am also using a virtual environment Here are my requirements

ansi2html==1.8.0
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==22.2.0
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
blis==0.7.9
Brotli==1.0.9
catalogue==2.0.8
cffi==1.15.1
charset-normalizer==3.0.1
click==7.1.2
colorama==0.4.6
comm==0.1.2
confection==0.0.4
contourpy==1.0.7
cycler==0.11.0
cymem==2.0.7
dash==1.21.0
dash-bootstrap-components==0.13.1
dash-core-components==1.17.1
dash-html-components==1.1.4
dash-table==4.12.0
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl
executing==1.2.0
fastjsonschema==2.16.2
Flask==1.1.4
Flask-Compress==1.10.1
fonttools==4.38.0
fqdn==1.5.1
funcy==1.17
future==0.18.2
gunicorn==20.0.4
idna==3.4
import-ipynb==0.1.4
importlib-metadata==6.0.0
importlib-resources==5.10.2
ipykernel==6.21.2
ipython==8.10.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
itsdangerous==1.1.0
jedi==0.18.2
Jinja2==2.11.3
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.5.1
jupyter-dash==0.4.0
jupyter-events==0.6.3
jupyter_client==8.0.2
jupyter_core==5.2.0
jupyter_server==2.3.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
kiwisolver==1.4.4
langcodes==3.3.0
MarkupSafe==2.0.1
matplotlib==3.7.0
matplotlib-inline==0.1.6
mistune==2.0.5
murmurhash==1.0.9
nbclassic==0.5.1
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.23.4
packaging==21.3
pandas==1.3.3
pandocfilters==1.5.0
parso==0.8.3
pathy==0.10.1
patsy==0.5.3
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.0.0
plotly==5.10.0
preshed==3.0.8
prometheus-client==0.16.0
prompt-toolkit==3.0.36
psutil==5.9.4
pure-eval==0.2.2
pycparser==2.21
pydantic==1.10.4
Pygments==2.14.0
pyLDAvis==3.3.1
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.6
pytz==2022.4
pywin32==305
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.0
qtconsole==5.4.0
QtPy==2.3.0
requests==2.28.2
retrying==1.3.4
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
scipy==1.9.2
seaborn==0.12.2
Send2Trash==1.8.0
six==1.16.0
sklearn==0.0.post2
smart-open==6.3.0
sniffio==1.3.0
soupsieve==2.4
spacy==3.5.0
spacy-legacy==3.0.12
spacy-loggers==1.0.4
srsly==2.4.5
stack-data==0.6.2
statsmodels==0.13.2
tenacity==8.1.0
terminado==0.17.1
textblob==0.17.1
thinc==8.1.7
tinycss2==1.2.1
tornado==6.2
traitlets==5.9.0
typer==0.7.0
typing_extensions==4.4.0
uri-template==1.2.0
urllib3==1.26.14
wasabi==1.1.1
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==1.0.1
widgetsnbextension==4.0.5
wincertstore==0.2
zipp==3.13.0

### Error message:

```shell
remote:                    gcc: build/src.linux-x86_64-3.11/numpy/core/src/umath/matmul.c
remote:                    gcc: build/src.linux-x86_64-3.11/numpy/core/src/umath/clip.c
remote:                    gcc: numpy/core/src/umath/ufunc_object.c
remote:                    gcc: numpy/core/src/umath/extobj.c
remote:                    gcc: build/src.linux-x86_64-3.11/numpy/core/src/umath/scalarmath.c
remote:                    error: Command "gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNP
Y_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_S
OURCE=1 -Ibuild/src.linux-x86_64-3.11/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.11/numpy/core/sr
c/npymath -Ibuild/src.linux-x86_64-3.11/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x
86_64-3.11/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core
/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/app/.herok
u/python/include/python3.11 -Ibuild/src.linux-x86_64-3.11/numpy/core/src/common -Ibuild/src.linux-x86_
64-3.11/numpy/core/src/npymath -c build/src.linux-x86_64-3.11/numpy/core/src/multiarray/scalartypes.c 
-o build/temp.linux-x86_64-3.11/build/src.linux-x86_64-3.11/numpy/core/src/multiarray/scalartypes.o -M
MD -MF build/temp.linux-x86_64-3.11/build/src.linux-x86_64-3.11/numpy/core/src/multiarray/scalartypes.
o.d -std=c99" failed with exit status 1
remote:                    [end of output]
remote:
remote:                note: This error originates from a subprocess, and is likely not a problem with
 pip.
remote:                ERROR: Failed building wheel for numpy
remote:              Failed to build numpy
remote:              ERROR: Could not build wheels for numpy, which is required to install pyproject.t
oml-based projects
remote:              [end of output]
remote:
remote:          note: This error originates from a subprocess, and is likely not a problem with pip. 
remote:        error: subprocess-exited-with-error
remote:
remote:        × pip subprocess to install build dependencies did not run successfully.
remote:        │ exit code: 1
remote:        ╰─> See above for output.
remote:
remote:        note: This error originates from a subprocess, and is likely not a problem with pip.   
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote:  !
remote:  ! ## Warning - The same version of this code has already been built: 8cdbd427e0d29c4d7ef241c1
9c7d790035f80d8b
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version 8cdbd427e0d2
9c4d7ef241c19c7d790035f80d8b
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a diffe
rent branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !     git push heroku <branchname>:main
remote:  !     git push heroku <branchname>:main
remote:  !     git push heroku <branchname>:main
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote:
```

### Additional information:

Please Help!

**Comment by seberg** [comment]
You also snippet away anything interesting from the output.  My guess would be you don't have a full build environment set up yet (visual studio with the right version).  Also there is the question of *how* you are trying to build NumPy.

**Comment by rkern** [comment]
While they may be sitting on a Windows machine, the build shown here is happening remotely on a Linux server via Heroku (or one of the other services that uses Heroku-ish buildpacks). The numpy installation is happening due to a `pip install`. Unfortunately, the actual error message from the failed `gcc` command is omitted (other `gcc` invocations apparently succeeded, so they do have a build environment set up, at least). There might be a log file that was written to, but they will have to check their Heroku documentation to see how to get access to it after the failed build.

It looks like they are building for Python 3.11 and pinning the version of numpy to exactly `1.23.1`. We do not have Python 3.11 wheels for that particular version of numpy, but we do have them for later versions. They can try to specify a more recent version of numpy like `1.24.2` and be able to use the prebuilt binary wheels instead of building from source. Alternately, they can try Python 3.10 instead.

I don't think there is a _whole_ lot more that we can do about the source build without significantly more information, and I don't think we'll be able to really guide them to be able to _get_ that information from their complex environment. Given the availability of binary wheels by adjusting the requested versions, I think we can close this.
