### ISSUE TITLE
BUG: np.unique yields incorrect output for MaskedArray when axis is not None

### ISSUE THREAD

**Issue by hchau630** [numpy/numpy#23281]
### Describe the issue:

np.unique seems to ignore MaskedArray mask when axis is not None, and returns a regular np.ndarray instead of a MaskedArray. In the code example below, the output is
```
<class 'numpy.ma.core.MaskedArray'> [1 2 3 --]
<class 'numpy.ndarray'> [1 2 3 4]
```
but one should instead expect
```
<class 'numpy.ma.core.MaskedArray'> [1 2 3 --]
<class 'numpy.ma.core.MaskedArray'> [1 2 3 --]
```

### Reproduce the code example:

```python
import numpy as np
import numpy.ma as ma

a = ma.array([1,2,3,4,2,3,1,4], mask=[0,0,1,1,0,0,0,1])
out = np.unique(a)
print(type(out), out)
out = np.unique(a, axis=0)
print(type(out), out)
```

### Runtime information:

1.24.2
3.9.13 (main, Oct 13 2022, 16:12:19) 
[Clang 12.0.0 ]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}}]
None

### Context for the issue:

I need to find unique rows in a 2D MaskedArray.

**Comment by rgommers** [comment]
You should be using `np.ma.unique` instead. In general, functions in the main namespace are not aware of the mask of a masked array. Things may or may not work. The semantics not working stems from:
```
>>> np.asarray(a)
array([1, 2, 3, 4, 2, 3, 1, 4])
```
Using any Python function from any library that expects numpy arrays but not masked arrays will react like that. gh-18675 is the issue discussing that, so I'll close this one.

**Comment by hchau630** [comment]
Thanks for taking a look at it. But it appears there is no axis option for np.ma.unique, which I need for performing unique along rows of a 2D array. Also I can't find the documentation for np.ma.unique. Should I open another issue about this?

**Comment by rgommers** [comment]
Ah good point, yes please! One seems to be a documentation issue, and the other a feature request that should not be too difficult to implement.
