### ISSUE TITLE
DOC/TST: potential updates to NumPy Testing Guidelines?

### ISSUE THREAD

**Issue by mdhaber** [numpy/numpy#23283]
### Issue with current documentation:

The [Tests on random data](https://numpy.org/doc/stable/reference/testing.html#tests-on-random-data) section of the [Testing Guidelines](https://numpy.org/devdocs/reference/testing.html) does not recommend the use of `np.random.Generator`. Also, [Creating many similar tests](https://numpy.org/devdocs/reference/testing.html#creating-many-similar-tests) does not mention the use of `pytest.parametrize`.

### Idea or request for content:

Are the recommendations of these sections still considered best practices?

If not, should the "Tests on random data" section be updated to recommend the use of `np.random.default_rng`? (Are Python `random` and the singleton `RandomState` still acceptable in new tests? Are common seeds like `0` OK?)

Should the "Creating many similar tests" section be updated to demonstrate the use of `parametrize`?
<details>

For example, replace:
```python3
class LinalgTestCase:
    def test_single(self):
        a = array([[1., 2.], [3., 4.]], dtype=single)
        b = array([2., 1.], dtype=single)
        self.do(a, b)

    def test_double(self):
        a = array([[1., 2.], [3., 4.]], dtype=double)
        b = array([2., 1.], dtype=double)
        self.do(a, b)
```
with
```python3
class LinalgTestCase:
    @pytest.mark.parametrize('dtype', [single, double])
    def test_dtypes(self):
        a = array([[1, 2], [3, 4]], dtype=dtype)  # or random data?
        b = array([2, 1], dtype=dtype)
        self.do(a, b)
```
?
(Also, what is `imply` further down in the example?)

</details>

I'd be happy to submit a PR, but I thought I'd ask first.

**Comment by rkern** [comment]
As far as the random data part is concerned, the document is still up to date.
