### ISSUE TITLE
BUG: numpy.nan is not behaving as literal 'None'.

### ISSUE THREAD

**Issue by thakurns** [numpy/numpy#23299]
### Describe the issue:

numpy.nan is being treated as object rather than literal ‘None’. 
The inbuilt any() function treating numpy.nan as True.

With None:
   >> any( [False, False, None] )
         False
With numpy.nan:
  >> any( [False, False, numpy.nan])
        True

Where as It should be 'False' for the cases.

### Reproduce the code example:

```python
import numpy as np

print(
    any([False, False, None])
)

print(
    any([False, False, np.nan])
)
```

### Runtime information:

1.21.5
3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

When we pass a column/Series of a Dataframe to any() function, which is a python built-in function, it should treat nan/np.nan as False instead of True/Object/non-zero number.

**Comment by andyfaff** [comment]
`bool(np.nan)` is True, which it should be as it has type 'float', as is `np.inf`.

**Comment by rkern** [comment]
This is also the semantics of the builtin `float` for NaN values. We are going to match Python's choice of semantics here. Python has made the choice that only exact 0.0s will be the only Falsey floating point values.

```
>>> nan = float('NaN')
>>> nan
nan
>>> np.isnan(nan)
True
>>> bool(nan)
True
```
