### ISSUE TITLE
indexing for high dimensional array output is wrong

### ISSUE THREAD

**Issue by JunzheJosephZhu** [numpy/numpy#23296]
### Describe the issue:

When using  np.arange to do tensor indexing on some dimensions, numpy gives wrong output shape.

### Reproduce the code example:

```python
import numpy as np
voxels = np.zeros((12, 11, 18, 3))

print(voxels[np.arange(12), :, :, 0].shape)

print(voxels[:, np.arange(11), :, 1].shape)

print(voxels[:, :, np.arange(18), 2].shape)

print(np.version.version)
```

### Error message:

```shell
(12, 11, 18)
(11, 12, 18)
(12, 11, 18)
1.22.3
```

### Runtime information:

numpy version is 1.22.3

**Comment by rkern** [comment]
The behavior of mixing slices and advanced indexing is [documented here](https://numpy.org/devdocs/user/basics.indexing.html#combining-advanced-and-basic-indexing). There is a [proposal for other, more useful behaviors in NEP 21](https://numpy.org/neps/nep-0021-advanced-indexing.html).

**Comment by JunzheJosephZhu** [comment]
I think you should take another look, the second line printed under expected behavior is supposed to be same as the first and third printed line, but it is not.

**Comment by rkern** [comment]
It may be what you wanted, but it's not the way that it was designed. We know it is a confusing feature, hence the proposed enhancements in NEP 21. But it is working the way it was designed and documented. If you think that the output doesn't match the documentation that I linked to, please cite the relevant portions of the documentation that would give the results that you expected.

**Comment by JunzheJosephZhu** [comment]
thanks, i read into the doc and found the part that describes it.
For others reading the thread, the doc says:
The advanced indices are separated by a slice, [Ellipsis](https://docs.python.org/3/library/constants.html#Ellipsis) or [newaxis](https://numpy.org/devdocs/reference/constants.html#numpy.newaxis). For example x[arr1, :, arr2].

The advanced indices are all next to each other. For example x[..., arr1, arr2, :] but not x[arr1, :, 1] since 1 is an advanced index in this regard.

In the first case, the dimensions resulting from the advanced indexing operation come first in the result array, and the subspace dimensions after that. In the second case, the dimensions from the advanced indexing operations are inserted into the result array at the same spot as they were in the initial array (the latter logic is what makes simple advanced indexing behave just like slicing).
