### ISSUE TITLE
DOC: Character Limit for numpy.save

### ISSUE THREAD

**Issue by zm711** [numpy/numpy#23290]
### Issue with current documentation:

I just ran into an issue where if my filename is > 94 characters (my string length is greater than 94) np.save runs into a 

`FileNotFoundError [Errno 2] No such file or directory` 
with the traceback going to line 518 of `npyio.py`

```python
file_ctx = open(file, "wb")
```
Thus the numpy.save documentation is missing a character limit. 

### Idea or request for content:

I think just adding a character limit in the documentation would be helpful. I went through a bunch of troubleshooting until I realized that my file name was too long. One solution would be to use shorter file names, but my file names come from an electrophysiological recording apparatus with a bunch of metadata, so knowing the limit would be helpful as I break the raw data into subsets of `.npy` files for analysis. Lengthening the limit would also work, but I don't know how hard that would be.

**Comment by eric-wieser** [comment]
What filesystem does your filename live on? This is almost certainly an issue with your filesystem / operating system.

If there's anything to be done it, it would be to file an issue against Python itself to produce a better error message.

**Comment by zm711** [comment]
Thanks both for the response. My work computer is windows, so I haven't been able to test this on my Mac yet. But I was wondering if this was an os issue, so I tried saving the same file name to a blank .txt file on windows and it saved with no problem.  I'll look into your link @mattip and I'll file an issue with Python itself for better error message. Thanks again for the quick response.

**Comment by mattip** [comment]
> I tried saving the same file name to a blank .txt file on windows

Did you save in the same directory as the attempt in python? The file name limitation is the total of: drive + directory_path + filename + suffix

**Comment by zm711** [comment]
Yeah. Same directory. It saved with no problem. This was .txt file saved with Windows though (just Notepad). Not in Python itself.

**Comment by rkern** [comment]
Did all of the parent folders exist before trying to write the file? That's typically what `Errno 2` is going to be raised for in this situation.

Software is always built on other software (`np.save()` is built on `open()`), and [abstractions leak](https://en.wikipedia.org/wiki/Leaky_abstraction). Sometimes, the details of the component software are so critical and specific to the use of the outer software (or is unexpectedly used) that we need to repeat the documentation, but I don't think it rises to that level here. There is no way that we can document every possible reason that `open()` could fail (filesystems are the ultimate in leaky abstractions). The user knows that `np.save()` is dealing with files, so we have to rely that users can seek out and apply general knowledge about files.

**Comment by zm711** [comment]
Everything already existed. I tested the exact same np.save with a slice of my file name limited to 94 characters (not including directory info) and it worked fined. So I just hard coded a check in my code and will truncate file names if too long since I constantly go back and forth between os's. 

Thanks to all.
