### ISSUE TITLE
Advanced indexing is flat out wrong.

### ISSUE THREAD

**Issue by JunzheJosephZhu** [numpy/numpy#23297]
### Describe the issue:

I have a 4D array of shape [12, 11, 18, 3]. When I use np.arange() to do advanced indexing on the first and third dimensions, and index the 4th dimension with an integer, the return shape is [12, 11, 18], as expected. However, when I use np.arange() to do advanced indexing on the second dimension, the output shape is [11, 12, 18], which has the first and second dimensions transposed.

### Reproduce the code example:

```python
import numpy as np
voxels = np.zeros((12, 11, 18, 3))

print(voxels[np.arange(12), :, :, 0].shape)

print(voxels[:, np.arange(11), :, 1].shape)

print(voxels[:, :, np.arange(18), 2].shape)

print(np.version.version)
```

### Error message:

```shell
Expected output:
(12, 11, 18)
(12, 11, 18)
(12, 11, 18)
Actual output:
(12, 11, 18)
**(11, 12, 18)**
(12, 11, 18)
```

### Runtime information:

numpy 1.22.3

**Comment by rkern** [comment]
Please do not open duplicate new issues because developers have closed an issue. You may continue to comment on the old issue (as you have) if you need more information on why it was closed.

Dupe of ##23296

**Comment by JunzheJosephZhu** [comment]
could you take a serious look then? pretty sure we have a bug here

**Comment by rkern** [comment]
I did. This is a well-known (to us core devs) confusing feature. Indeed, it does not work like most people expect it to.
