### ISSUE TITLE
DOC: Include matrix arithmetic examples in the docs for beginners

### ISSUE THREAD

**Issue by wesinalves** [numpy/numpy#23291]
I would like to suggest including examplex of matrix arithmetic in 'Numpy Quickstart' or 'NumPy: the absolute basics for beginners' pages. IMHO, `@` operator is an important topic to be in that pages. I will be glad to work on it.

**Comment by mattip** [comment]
I see it is mentioned in [basic operations](https://numpy.org/devdocs/user/quickstart.html#basic-operations). What is missing?

**Comment by wesinalves** [comment]
you're right, I didn't notice when I read it. Maybe transpose of a matrix would be worth?

**Comment by rossbar** [comment]
> you're right, I didn't notice when I read it. Maybe transpose of a matrix would be worth?

Transposes are also explicitly mentioned in the [quickstart](https://numpy.org/devdocs/user/quickstart.html#changing-the-shape-of-an-array). I'm going to go ahead and close this issue - if you have concrete recommendations re: how the tutorials it may be easier to open a PR with the suggestion to have a more focused discussion.
