### ISSUE TITLE
BUG: meshgrid returns a list while a tuple is expected based on the documentation

### ISSUE THREAD

**Issue by kgabor** [numpy/numpy#23303]
### Describe the issue:

The documentation suggests that the return type is a _tuple_ of arrays.

> For vectors x1, x2,…, xn with lengths Ni=len(xi), returns (N1, N2, N3,..., Nn) shaped arrays if indexing=’ij’ or (N2, N1, N3,..., Nn) shaped arrays if indexing=’xy’ with the elements of xi repeated to fill the matrix along the first dimension for x1, the second for x2 and so on.

However the return type is a _list_. This makes a difference if the result is directly used in indexing as a whole.

### Reproduce the code example:

```python
R = np.arange(9).reshape(3,3)
M = np.meshgrid([0,1,2],[0,1,2], indexing='ij')
# Expected behavior is (3, 3)
R[M].shape
(2, 3, 3, 3)

R[tuple(M)].shape  
(3, 3)
# ===
M = np.meshgrid([0,1,2],[0,1,2], sparse=True, indexing='ij')
R[M] # Error

R[tuple(M)].shape
(3, 3)
```

### Runtime information:

1.24.0
3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]

**Comment by rossbar** [comment]
Agreed - the description and type in the docstring should be updated to reflect the fact that a *list* of ndarray is returned.
