### ISSUE TITLE
BUG: use of folder name 'crackfortran' has unforeseen consequences

### ISSUE THREAD

**Issue by MW1966** [numpy/numpy#23300]
### Describe the issue:

On Windows an attempt to install numpy was blocked by our security program (without explicitly having stated so). It appears to be related to the name crackfortran for the folder. 

I would say that anything with "crack" in the name is likely to be frowned upon by security packages, whether merited or not.

Could you perhaps ensure that future releases don't refer to the software as "crack" as this triggers responses in any heavily security focused organisation? This is particularly true since the updated location will differ based on the version of Python being run.

Please do reach out to me should  you want or need further clarification on this.

Kind Regards
Marcus Webb

### Reproduce the code example:

```python
pip install numpy
Collecting numpy
  Using cached numpy-1.24.2-cp311-cp311-win_amd64.whl (14.8 MB)
Installing collected packages: numpy
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Users\\marcus.webb\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\f2py\\tests\\src\\crackfortran\\accesstype.f90'
Check the permissions.
```

### Error message:

```shell
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Users\\marcus.webb\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\f2py\\tests\\src\\crackfortran\\accesstype.f90'
Check the permissions.
```

### Runtime information:

>>> import sys, numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\marcus.webb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__init__.py", line 144, in <module>
    from . import lib
ImportError: cannot import name 'lib' from partially initialized module 'numpy' (most likely due to a circular import) (C:\Users\marcus.webb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__init__.py)
>>>

### Context for the issue:

Use of a Term that can be put on a blocklist doesn't help anyone.

**Comment by melissawm** [comment]
Thanks for the report - the main file used by f2py has been called `crackfortran.py` for many years so this is surprising 😄 Might be worth checking why the folder triggers this but not the filename.

**Comment by mattip** [comment]
Closing. Please point your company's security team to this issue.
