### ISSUE TITLE
DOC: Add clarification around MSVC compiler minimum version supported

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23301]
### Issue with current documentation:

At https://numpy.org/doc/stable/user/building.html it states
> Much of NumPy is written in C. You will need a C compiler that complies with the C99 standard.

> Part of Numpy is now written in C++. You will also need a C++ compiler that complies with the C++11 standard.

> Note that NumPy is developed mainly using GNU compilers and tested on MSVC and Clang compilers. 

This can be misleading, since MSVC has a loose definition of C99 and C++11 support.

### Idea or request for content:

We should state the versions of compilers we test in CI:

> Note that NumPy is developed mainly using GNU compilers and tested on GCC-??, MSVC from vs2019, and Clang v??? compilers.

**Comment by rgommers** [comment]
https://github.com/numpy/numpy/blob/3b5eff00e49ed8ab1e6c9fa9345e51817a691b2f/meson.build#L31-L35

**Comment by rgommers** [comment]
I believe so. Conda-forge has upgraded to vc142, and we also fixed the offending thing in the static libraries so I thought we had upgraded our own CI and wheels builds too already (?).

**Comment by charris** [comment]
> I thought we had upgraded our own CI and wheels builds too already (?)

I don't recall that, but could be wrong.

**Comment by mattip** [comment]
Closing, meson enforces this for us
