### ISSUE TITLE
DOC: RuntimeError during building document

### ISSUE THREAD

**Issue by F3eQnxN3RriK** [numpy/numpy#23312]
### Issue with current documentation:

The error is arise during building documentation (`make html`) :
```
RuntimeError: The new DType API is currently in an exploratory phase and should NOT be used for production code.  Expect modifications and crashes!  To experiment with the new API you must set `NUMPY_EXPERIMENTAL_DTYPE_API=1` as an environment variable.
```
Despite the error, the build succeeds and html documents are generated.

### Idea or request for content:

It seems to be caused by the link to `numpy.core.umath_tests` in `1.15.0-notes.rst`.

**Comment by seberg** [comment]
Yeah, we could just double quote those there to silence it, I think.  The links are probably broken anyway.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
I would love to work on it , and contribute to opensource , Could you please assign me this and should I wait until the issue has been assigned to me , so that I can start working ?
@melissawm @seberg

**Comment by Mukulikaa** [comment]
Hi @SANTHOSH-MAMIDISETTI, NumPy doesn't assign issues so please feel free to work on any issues you like.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> Hi @SANTHOSH-MAMIDISETTI, NumPy doesn't assign issues so please feel free to work on any issues you like.

Thanks for your reply @Mukulikaa , If at all I need some briefing on the issue or something like that , whom should I mention ? @seberg @F3eQnxN3RriK

**Comment by mattip** [comment]
There is no need to mention anyone in particular. If you have concrete questions, just ask them and someone should answer. If what you are looking for is a mentor, then the github repo is not the place for that. See the other resources at the [contribute](https://numpy.org/contribute/) web page.

**Comment by ellaella12** [comment]
Hi may I check if anyone is working on this ticket currently? @SANTHOSH-MAMIDISETTI if

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> Hi may I check if anyone is working on this ticket currently? @SANTHOSH-MAMIDISETTI If not I would like to give it a go

no I am not working on it @ellaella12  ,

**Comment by ellaella12** [comment]
ok I will give it a go :)

**Comment by ellaella12** [comment]
Hi may I check how i can replicate the Runtime Error? When I run `make html`, release `1.15.0-notes.html` was generated with no runtime errors.

**Comment by F3eQnxN3RriK** [comment]
There was an error when this issue opened, but it seems to have been resolved at some point.
