### ISSUE TITLE
ENH: Explicitly show keys of `.npz` file in repr

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#23319]
### Proposed new feature or change:

Determining the structure of npz files could be made more intuitive by providing info about keys. A quick example:

```python
>>> np.savez("example.npz", x=np.arange(10), y=np.arange(3))  # An example file with multiple keys
>>> data = np.load("example.npz")
# NpzFile repr doesn't provide info about what the file contains
>>> data
<numpy.lib.npyio.NpzFile at 0x7fbd182567a0>
# Keys returns a KeysView as expected with Python dict-likes, but
# the KeysView repr isn't particularly informative
>>> data.keys()
KeysView(<numpy.lib.npyio.NpzFile object at 0x7fbd182567a0>)
# In order to get explicit info about the key, users have to
# know how to inspect this object
>>> list(data.keys()) 
['x', 'y']
# or,
>>> list(data)
['x', 'y']
```

I think the user experience with `.npz` files would be improved by including explicit info about the keys in the NpzFile repr.

**Comment by charris** [comment]
That would be useful. +1.

**Comment by seberg** [comment]
Seeing the PR, I am tempted to suggest to impleemnt a `__repr__` in the directino of:
`<NpzFile 'filename_if_vailable' containig ..., ..., ...>` (maybe cutting down long names or many arrays)?  Or without the `<>` but this repr can't be pasted anyway.

I would lean towards a `__repr__` mainly, `__str__` falls back to it anyway.  Unless you want `str()` to return a more comprehensive summary.
