### ISSUE TITLE
Gitpod build is failing.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#23320]
See https://github.com/numpy/numpy/actions/runs/4319130050. There are two deprecations that look to be causing problems:

```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. I don't see that we use either command, but one of out dependencies may.

**Comment by charris** [comment]
I suspect `build-push-action`. Note that we are using the v2 release, the most recent release is v4. There seems to be awareness of the problem in the closed PR's at https://github.com/docker/build-push-action.

**Comment by charris** [comment]
Note that circleci has also begun failing, may be related, but I don't think it uses github actions.

**Comment by WarrenWeckesser** [comment]
Github is currently experiencing an "incident" with Actions and Pages: https://www.githubstatus.com/

**Comment by charris** [comment]
OK, updated all the actions, and now the deprecation warnings are gone. Closing.
