### ISSUE TITLE
Backports require review by a person other than myself.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#23346]
I can merge directly by checking a box with lots of scary red text, but it seems discouraged. This seems a product of branch protection. I wonder if we can make an exception for maintenance branches and release managers?

**Comment by seberg** [comment]
Hmmm, tried making you special in the branch protection, maybe it helped?

**Comment by charris** [comment]
Review is still required, see https://github.com/numpy/numpy/pull/23343.

**Comment by seberg** [comment]
Oh, a default checkmark not removed in the maintanence branches, should be OK now?

**Comment by charris** [comment]
Thanks. I'm not opposed to requiring reviews, but it does make for some friction in this case.

**Comment by seberg** [comment]
Yeah, we could enable it on the main branch.  But overall, I am not sure it seems useful unless you have code owners maybe and we don't.
