### ISSUE TITLE
DOC: Missing documentation for various numpy.ma functions

### ISSUE THREAD

**Issue by hchau630** [numpy/numpy#23352]
### Issue with current documentation:

There appears to be a few functions in the numpy.ma that is missing from the documentation. The one that I noticed first is `numpy.ma.unique`, and after some poking around in numpy/ma/extras.py, I found the following (possibly incomplete) list of functions missing from the docs:

`diagflat`
`isin`
`in1d`
`intersect1d`
`setdiff1d`
`setxor1d`
`unique`
`union1d`

It appears that these functions already have docstrings, so making them show up on the documentation webpage shouldn't be too much of a hassle.

**Comment by MuhammadNizamani** [comment]
Are you going to document the undocumented function? Should I start documenting them?

**Comment by Mukulikaa** [comment]
Thanks for reporting this, @hchau630. 

@MuhammadNizamani, the docstrings already exist in the file `numpy/numpy/ma/extras.py`. We need to make a new section in the reference API and add them. You can understand how to do this by referring to the existing [numpy.ma](https://numpy.org/devdocs/reference/routines.ma.html) documentation. The doctrings are written in `numpy/numpy/ma/core.py` and generated in the docs through the file `numpy/numpy/doc/source/reference/routines.ma.rst`. If you are interested in contributing to this I am happy to help you further, let me know!

**Comment by MuhammadNizamani** [comment]
@Mukulikaa  I am happy to contribute in numpy. Right now I am going through repo and I am greatefull of your kind offer and I will contact you. Thanks

**Comment by MuhammadNizamani** [comment]
@Mukulikaa to solve the issue my first step would be to list these functions in numpy/numpy/doc/source/reference/routines.ma.rst ?

**Comment by Mukulikaa** [comment]
Fixed via #23368.
