### ISSUE TITLE
Drop TravisCI  ppc64le test?

### ISSUE THREAD

**Issue by charris** [numpy/numpy#23354]
The TravisCI ppc64le test fails on a regular basis for reasons unrelated to NumPy. Almost every PR now fails that test and it is quite annoying. We should stop testing there and find another platform if possible.

**Comment by mattip** [comment]
Hmm. The [build history](https://app.travis-ci.com/github/numpy/numpy/builds) (I hope that is a public link) looks pretty clean for the past two weeks. Am I missing something?

**Comment by charris** [comment]
@pratiklp00 the problem was that the platform was often unavailable, not that it actually failed.
