### ISSUE TITLE
BUG: specifying 'kind' keyword argument in numpy.isin function not possible

### ISSUE THREAD

**Issue by dylanvanw** [numpy/numpy#23369]
### Describe the issue:
Hi there, I found an unexpected error if I use options in this function that are described in the documentation.

The documentation on the numpy.isin function indicates that it should be possible to provide the 'kind' keyword argument: https://numpy.org/doc/stable/reference/generated/numpy.isin.html

However, a TypeError is raised when I try to run the function with that keyword argument.

### Reproduce the code example:

```python
import numpy as np

array1 = np.array([3, 2])
array2 = np.array([5, 2])
np.isin(array1, array2, kind='table')
```

### Error message:

```shell
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_898224/1581531393.py in <module>
      2 
      3 array2 = np.array([5, 2])
----> 4 np.isin(array1,array2, kind='table')

<__array_function__ internals> in isin(*args, **kwargs)

TypeError: _isin_dispatcher() got an unexpected keyword argument 'kind'
```

### Runtime information:

1.21.6
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]

### Context for the issue:

I am working with a very large array so I want to make use of all the possible optimisations that can be applied to this problem.

**Comment by rkern** [comment]
That's the docs for the more recent numpy 1.24 than the 1.21 that you are using. You can change the version of the docs with the dropdown in the upper right hand corner. Here is the version for 1.21:

https://numpy.org/doc/1.21/reference/generated/numpy.isin.html

**Comment by dylanvanw** [comment]
My bad, should have seen that. Thanks!
