### ISSUE TITLE
DOC: Promote to build with meson

### ISSUE THREAD

**Issue by lorentzenchr** [numpy/numpy#23367]
### Issue with current documentation:

I'm developing with MacOS and got errors when trying to build numpy the old way according to https://numpy.org/doc/stable/user/building.html#building-from-source with `python setup.py build_ext --inplace`.

Error message
```
fatal error: 'x86-simd-sort/src/avx512-32bit-qsort.hpp' file not found
    #include "x86-simd-sort/src/avx512-32bit-qsort.hpp"
```

### Idea or request for content:

Building with meson as described in https://github.com/numpy/numpy/blob/main/building_with_meson.md worked out of the box. It would be very nice, if this were documented somewhere (prominent) in https://numpy.org/doc/stable/dev/index.html.

**Comment by rgommers** [comment]
Hi @lorentzenchr, thanks for the issue! And great to hear that switching to Meson resolved the problem.

The Meson build isn't actually 100% complete yet - in particular SIMD support, so if there's any issue with the header above, it will be hidden. Hence I'm not sure that we should already make this switch in contributor-oriented docs. 

The second issue here is that the `./dev.py` experience is still a bit rough compared to `runtests.py` or `python setup.py develop`.

So I'm inclined to hold off for 1-2 more months personally. But there's pros to switching now too of course - more dogfooding, faster builds, and a nicer build system all around. So let's see what others think.

**Comment by lorentzenchr** [comment]
@rgommers Thanks for the super fast reply.

I guess the reason for the meson build to pass is then exactly the missing simd support. Should I open a new issue for my simd file not found error?

**Comment by seberg** [comment]
The reason why the meson build works is probably just that it doesn't even attempt to use this file.

The proper solution is to update the git submodules.  Run: `git submodules update --init`

(It would be nice to give a warning about this being the reason, I am not sure that is easy though.)

**Comment by pentschev** [comment]
Just ran into this and indeed `git submodule update --init` seems to have resolved the issue. Not sure If I overlooked something, but maybe this is something that needs to be updated in https://numpy.org/doc/stable/dev/index.html ?

**Comment by rgommers** [comment]
This came in with gh-22315. @r-devulap would you be able to address these concerns? By:
- implementing checks in the build system so that if a file is missing, there's a comprehensible error for the user? Something like this will do: https://github.com/scipy/scipy/blob/d541c752246a9e196034957d3e044950eec75907/scipy/_lib/setup.py#L4-L9 (plus the same for Meson).
- updating https://numpy.org/doc/stable/dev/index.html

**Comment by r-devulap** [comment]
@rgommers sure, I will do both.

**Comment by r-devulap** [comment]
see https://github.com/numpy/numpy/pull/23372

**Comment by rgommers** [comment]
The issue here is fixed by gh-23372. I'd like to defer other meson-related doc updates until we're actually switching over (the UX may change too, as editable install support is about to land), so let's close this issue.

**Comment by lorentzenchr** [comment]
Thanks again for the fast replies and the improvements made!
