### ISSUE TITLE
DOC: polynomial.polynomial.Polynomial.roots

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#23374]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.roots.html says 

`Compute the roots for the series. Note that the accuracy of the roots decrease the further outside the domain they lie.`

Two problems:
1. grammar - it should be "the accuracy of the roots decreases ..."
2. meaning - what is the "domain" being mentioned here?

**Comment by MatteoRaso** [comment]
>grammar - it should be "the accuracy of the roots decreases ..."

I think both are grammatically correct.

>meaning - what is the "domain" being mentioned here?

This is mentioned elsewhere in the polynomial documentation: https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.html#numpy.polynomial.polynomial.Polynomial

**Comment by Rajeevjewar** [comment]
The sentence is grammatically correct, but it could be revised for clarity:
"Compute the roots of the series, noting that the accuracy of the roots decreases as they move further outside of the domain."

In mathematics, the domain of a function is the set of all possible input values for which the function is defined. The domain can be any set of real or complex numbers, and it depends on the specific function being considered.

In the given sentence, "domain" refers to the set of input values for which the series has valid roots. The accuracy of the roots decreases as they move further away from this set of valid input values.

If It is correct then can I fix it.

**Comment by harshvardhan2707** [comment]
I would like to work on this. This would be my first contribution to Open source. Could someone tell me how to navigate to the doc in question.

**Comment by MatteoRaso** [comment]
> I would like to work on this. This would be my first contribution to Open source. Could someone tell me how to navigate to the doc in question.

The Numpy contributor guide should answer all your questions: https://numpy.org/doc/stable/dev/
