### ISSUE TITLE
ModuleNotFoundError: No module named ‘numpy.core._multiarray_umath’ after updating numpy

### ISSUE THREAD

**Issue by wangchers** [numpy/numpy#23402]
### Describe the issue:

I have a problem with running my code after updating numpy to the latest version (1.24.2) using conda. I get this error:

ModuleNotFoundError: No module named ‘numpy.core._multiarray_umath’

I tried to check and switch my Python environment using conda commands, as suggested by Bing chat mode. I also tried to upgrade numpy to newest version, and add the Anaconda library path to my PATH user variable. None of these methods worked for me.

Can anyone help me solve this problem? Thank you very much!

### Reproduce the code example:

```python
import numpy as np
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\wangchers\.conda\envs\test316\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Users\wangchers\.conda\envs\test316\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\wangchers\.conda\envs\test316\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\develop\test\2023.3.16\test316\main.py", line 21, in <module>
    import numpy as np
  File "C:\Users\wangchers\.conda\envs\test316\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Users\wangchers\.conda\envs\test316\lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Users\wangchers\.conda\envs\test316\python.exe"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


Process finished with exit code 1
```

### Runtime information:

I can't output. When I import numpy, I report an error like Error message i write。

**Comment by wangchers** [comment]
This problem occurred only after I installed opencv in my own virtual environment using "pip install -- target==C:\Users\xx\.conda\envs\test316\Lib\site-packages opencv python".

**Comment by mattip** [comment]
Using `python -m pip install` is preferable to using `pip install --target` since you could be using a `pip` from a different version of python. I would recommend you start over, and copy-paste the commands you use into a document. Then if something goes wrong, paste the list of commands you used here so we can repeat them and work out what happened.

**Comment by MuhammadNizamani** [comment]
> Using `python -m pip install` is preferable to using `pip install --target` since you could be using a `pip` from a different version of python. I would recommend you start over, and copy-paste the commands you use into a document. Then if something goes wrong, paste the list of commands you used here so we can repeat them and work out what happened.

can he try to uninstall Numpy and then install Numpy? if there is an issue of missing modules it would be solved. if still there is an issue then It would be easy to pin.

**Comment by wangchers** [comment]
> > 使用比使用更可取，因为您可以使用来自不同版本的 python。我建议您重新开始，并将您使用的命令复制粘贴到文档中。然后，如果出现问题，请粘贴您在此处使用的命令列表，以便我们可以重复它们并找出发生了什么。`python -m pip install``pip install --target``pip`
> 
> 他可以尝试卸载Numpy然后安装Numpy吗？如果存在缺少模块的问题，则会得到解决。如果仍然存在问题，那么很容易固定。

I had try,but in vain.

**Comment by wangchers** [comment]
> 使用比使用更可取，因为您可以使用来自不同版本的 python。我建议您重新开始，并将您使用的命令复制粘贴到文档中。然后，如果出现问题，请粘贴您在此处使用的命令列表，以便我们可以重复它们并找出发生了什么。`python -m pip install``pip install --target``pip`

I uninstall the python3.11 and install the python3.9.Everything goes right!I heard opencv can be use correctly in python3.3-3.9.If not use python3.3-3.9,the numpy may can't use.Thank you and MuhammadNizamani for your helping!
