### ISSUE TITLE
MAINT: circleci redirector CI job has started failing

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23409]
There are a [number of failed runs](https://github.com/numpy/numpy/actions/workflows/circleci.yml) of the cirecleci redirector. I wonder if this is connected to the dependabot version updates.

**Comment by charris** [comment]
> dependabot version updates.

Might be. But it looks like `larsoner/circleci-artifacts-redirector-action` was loading from the tip of main, and it still is. The latest change is at https://github.com/larsoner/circleci-artifacts-redirector-action/commit/590e7142d7dc855dabe2e9225fa4a5694b76b7cb (two weeks ago) and that looks related to a security alert we are getting  at https://github.com/numpy/numpy/security/code-scanning/137. We could try pinning to the next to last commit, or we can try changing permissions.

**Comment by charris** [comment]
Hmm, we already have things setup as suggested at `larsoner/circleci-artifacts-redirector-action` and step_security only adds the egress controls. I think the security stuff is unrelated.

**Comment by ngoldbaum** [comment]
This was an upstream bug that's been fixed: https://github.com/larsoner/circleci-artifacts-redirector-action/issues/38
