### ISSUE TITLE
DOC: User defined Converters in `np.genfromtxt` get extraneous inputs which the user is not told about.

### ISSUE THREAD

**Issue by timgianitsos** [numpy/numpy#23429]
### Issue with current documentation:

Converters are functions that the user defines and are passed to `np.genfromtxt` to process particular columns.

A user who wants to ensure that the data in a column exists only within a small subset of possible values might want a converter to throw an error if it reads an entry with a bad value. For example, a user might want to ensure that each entry in a column is either `'A'` or `'B'`, and raise an exception otherwise.

This is problematic in terms of how it interacts with some of the code internal to `np.genfromtxt` because some paths through the code pass in other values to test how the converter behaves. For example, [this line](https://github.com/numpy/numpy/blob/1cf882248961a5d411c55d75bff190d7f7eb30e2/numpy/lib/_iotools.py#L804) passes in a `'1'` to each of the converters to test what `dtype` it outputs.

It is very confusing from the user side to see these extraneous `'1'`s passed in with no explanation when debugging, and then to see them not appear in the actual output array.
https://stackoverflow.com/questions/75783751/reading-csv-with-numpy-has-extra-row-of-1s

Furthermore, this behavior changes depending on what [exception the user raises](https://github.com/numpy/numpy/blob/1cf882248961a5d411c55d75bff190d7f7eb30e2/numpy/lib/_iotools.py#L805) and whether the user called `np.genfromtxt` with a [filling_value](https://github.com/numpy/numpy/blob/1cf882248961a5d411c55d75bff190d7f7eb30e2/numpy/lib/_iotools.py#L799).

### Idea or request for content:

The documentation around this behavior in `np.genfromtxt` should be more clear.

A few potential solutions:
- The user is not expected to throw exceptions in the converters
- The implementation could be changed to not pass in these testing values to the converters, or alternatively the user could be told under what circumstances they will be.

It would be problematic if a user has to write a converter with the logic "only accept `'A'` or `'B'`, except in the one situation where you might be passed an extraneous `'1'` by the framework on the first time".

**Comment by MuhammadNizamani** [comment]
Do you mean  the developer should rewrite the function?

**Comment by timgianitsos** [comment]
I'm not sure if there is a workaround to passing test inputs to the converters.

If there is no workaround, then presumably only the documentation would be updated.

**Comment by rossbar** [comment]
IIUC this is a built-in limitation of the dtype discovery mechanism. Perhaps this could be "fixed" but I suspect that might be tricky to get working without interfering with the current dtype inference behavior.

+1 for explicitly documenting the behavior though. I'd recommend adding a fourth bullet to the `Notes` section.
