### ISSUE TITLE
Converting the float type into integer in the dataFrame format produces zeros

### ISSUE THREAD

**Issue by barikbin** [numpy/numpy#23425]
### Describe the issue:

- If one creates an array via decompositions like this one down below: 

```
First_QR_array = First_dataSet.to_numpy(dtype=float)
Q, R = qr(First_QR_array)
Q_1, R_1 = np.linalg.qr(First_QR_array)
```
this often produces negative small float numbers. 

- Then convert this array to a data frame and try to change the dataFrame type into integers, it returns all zeros. 
An example of conversion could be: 

```
float_columns = First_Q_decomposition_dataFrame.select_dtypes(include="float64").columns

First_Q_decomposition_dataFrame[float_columns]=First_Q_decomposition_dataFrame[float_columns].astype('int')

```
this returns all zeros in the dataFrame. But if you change the type in the array format non of the numbers changes into zero. This only happens in dataFrame format. 

### Reproduce the code example:

```python
First_QR_array = First_dataSet.to_numpy(dtype=float)
Q_1, R_1 = np.linalg.qr(First_QR_array)
```

```
float_columns = First_Q_decomposition_dataFrame.select_dtypes(include="float64").columns

First_Q_decomposition_dataFrame[float_columns]=First_Q_decomposition_dataFrame[float_columns].astype('int')
```
```


### Error message:

_No response_

### Runtime information:

1.23.4
3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]

### Context for the issue:

_No response_

**Comment by MatteoRaso** [comment]
Numpy converts floats to integers upwards (e.g `np.int8(-0.9) = 0`). I don't think this is unintended behaviour.

>But if you change the type in the array format non of the numbers changes into zero.

Can you elaborate?

**Comment by barikbin** [comment]
Oops made a mistake!
