### ISSUE TITLE
BUG: `np.where`  may not preserve `Enum` type when used with a mix of `Enums` defined using a custom class that inherits from both `str` and `Enum`

### ISSUE THREAD

**Issue by luke396** [numpy/numpy#23423]
### Describe the issue:

Hi, when using the `np.where` function with an array of `Enums` defined using a custom class that inherits from both `str` and `Enum`, the resulting array does not preserve the `Enum` type as expected. 

### Reproduce the code example:

```python
import numpy as np
from enum import Enum, auto



class TestEnum(str, Enum):
    first = auto()
    second = auto()


cond = np.array([True, False, False])
a = np.array([TestEnum.first, None, None])
b = TestEnum.second
np.where(cond, a, b) 
# now: array([<TestEnum.first: '1'>, 'T', 'T'], dtype=object)
# expected: array([<TestEnum.first: 1>, <TestEnum.second: 2>, <TestEnum.second: 2>], dtype=object)
```
When `class TestEnum(Enum):`, it works well. 

### Runtime information:

1.24.0
3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35) 
[GCC 10.4.0]

### Context for the issue:

xref [BUG: enum not properly handled by fillna · Issue #51941 · pandas-dev/pandas](https://github.com/pandas-dev/pandas/issues/51941)

**Comment by maniben3** [comment]
import numpy as np
from enum import Enum, auto



class TestEnum(str, Enum):
    first = auto()
    second = auto()


cond = np.array([True, False, False])
a = np.array([TestEnum.first, None, None])
b = (TestEnum.second)
b=np.array(b,dtype=np.object)
np.where(cond, a, b) 



<ipython-input-20-77ba9a92fedd>:14: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.array(b,dtype=np.object)
array([<TestEnum.first: '1'>, <TestEnum.second: '2'>,
       <TestEnum.second: '2'>], dtype=object)

#use with np.object

**Comment by luke396** [comment]
`b = np.array(TestEnum.second)` indeed works.
