### ISSUE TITLE
ENH: Add np.random.multivariate_laplace

### ISSUE THREAD

**Issue by jiawei-zhang-a** [numpy/numpy#23433]
### Proposed new feature or change:

I am interested in submitting a new feature proposal to NumPy as an issue. Specifically, I have noticed that np.random.laplace only allows for the specification of location (mean) and scale (decay) parameters, and does not have an option for Multivariate Laplace. Conversely, while numpy.random.multivariate_normal is available for normal distribution, there is currently no equivalent for multivariate Laplace.

`mean = [0, 0]`
`cov = [[1, 0], [0, 100]]`
`x, y = np.random.multivariate_normal(mean, cov, 5000).T`
`loc, scale = 0., 1.`
`s = np.random.laplace(loc, scale, 1000)`

**Comment by rkern** [comment]
Now that it is significantly easier to [implement non-uniform sampling algorithms in C/Cython](https://numpy.org/doc/stable/reference/random/extending.html), we are generally not intending to add more distribution methods, as a matter of policy. I do look forward to seeing your implementation outside of numpy. `scipy.stats` might be a place for it.

**Comment by rkern** [comment]
Issue opened on [scipy/scipy](https://github.com/scipy/scipy/issues/18186)

**Comment by jiawei-zhang-a** [comment]
Thank you so much for the advice!
