### ISSUE TITLE
BUG: arange problem with float

### ISSUE THREAD

**Issue by thalesmaoa** [numpy/numpy#23443]
### Describe the issue:

Try to perform a arange

```
In [1]: import numpy as np

In [2]: np.arange(0,1,.1)
Out[2]: array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

```

Expected output:

```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```

How to check if this is a float problem:

```
In [9]: np.arange(0,1.000000000000001,.1)
Out[9]: array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```

### Reproduce the code example:

```python
import numpy as np
np.arange(0,1,.1)
```

### Runtime information:

```
import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.2
3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0]

print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]

```

**Comment by charris** [comment]
This is because `.1` is not actually `.1` when converted to a IEEE float64, which is  base two.  For this this sort of thing it is advisable to use `linspace`, or just use integers and scale the result. Note that .2, .3, etc., are also not exact.

**Comment by thalesmaoa** [comment]
That is the point. This is known, but others handle it. Numpy doesn't.

Octave:

```
>> [0:.1:1]
ans =

 Columns 1 through 4:

   0.00000   0.10000   0.20000   0.30000

 Columns 5 through 8:

   0.40000   0.50000   0.60000   0.70000

 Columns 9 through 11:

   0.80000   0.90000   1.00000

```

Julia:

```
A = range(0,1,step=.1) 

0.0:0.1:1.0

for element in A

    println(element)

end

0.0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1.0

```

Node.JS

```
Array.from({length: 11}, (_, i) => i/10)
[
    0, 0.1, 0.2, 0.3,
  0.4, 0.5, 0.6, 0.7,
  0.8, 0.9,   1
]
```

**Comment by charris** [comment]
It could perhaps be improved, but IIRC, some packages kind of cheat by making it inexact. The thing is, you really should not do things that way with floats.

**Comment by thalesmaoa** [comment]
Indeed. I can't agree more. I decided to report it as a bug after many complains from my students migrating from Matlab. It is normally used to build a signal with a frequency sample (step). In that scenario, array length doesn't really matter.

**Comment by melissawm** [comment]
@thalesmaoa can you check if [this document](https://numpy.org/doc/stable/user/how-to-partition.html) clarifies what is happening, and if not do you have suggestions for improved documentation? Thanks!

**Comment by thalesmaoa** [comment]
I see, arange can't be used as a replacement of `[0:.1:1]` in Matlab. I noticed that the replacement is:

```
[A:B] % Matlab
np.arange(A, B+1) # Python
```

Sorry abou the confusion! That is clearly presented in the doc.

**Comment by mgeier** [comment]
Now that it has been clarified that the end value is not supposed to be part of the range, what about fixing the following (which still fits the original issue title)?

```pycon
>>> import numpy as np
>>> np.arange(0.5, 1.1, 0.1)
array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])
```

I've created a notebook about this more than ten years ago (https://github.com/mgeier/python-audio/blob/master/misc/arange.ipynb) and I thought that's simply a natural limitation of floating point numbers, but today I saw a video about built-in ranges in Julia (https://www.youtube.com/watch?v=CLGXXPvJmOg), and it seems that Julia handles this better (already before the changes discussed in the video).
