### ISSUE TITLE
DOC: axis type overly restrictive

### ISSUE THREAD

**Issue by Nordicus** [numpy/numpy#23468]
### Issue with current documentation:

[The documentation for the axis parameter in argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) is wrong.
The type hint and document string indicates that argmax can be taken only along a single axis, but with my (not at all extensive, single use-case) testing, it already appears to accept performing argmax along multiple axes simultaneously.
I.e., consider an array a of dimension 4x3x3, calling numpy.argmax(a, axis=(1, 2)), argmax will return an array of dimension 4 having found the argmax in each 3x3 view.
I believe that I've seen similar issues elsewhere, so even once I've submitted a fix for the docs on this issue, I think it's worth checking other functions that take an axis argument?

### Idea or request for content:

numpy.argmax and other similar functions that take axis : int, optional should take axis : None or int or tuple of ints, optional [c.f. sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html).
Clearly, the change to the docs on other functions should follow a test that the behaviour is actually currently supported.

**Comment by seberg** [comment]
Thanks, but looks all correct to me:
```
>>> np.argmax(numpy.ones((4, 3, 3)), axis=(1, 2))
TypeError: 'tuple' object cannot be interpreted as an integer
```
argmax isn't like sum.

(assuming I am not missing something glaring, and closing)
