### ISSUE TITLE
DOC: numpy.reshape, redundent parentheses

### ISSUE THREAD

**Issue by JoryKlaverstijn** [numpy/numpy#23487]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

The following line is written in the first code block of the notes section:
`c.shape = (20)`
The parentheses are redundant, or there should be a `,` after the `20` to make it a tuple.

**Comment by mattip** [comment]
Heh. As written the code does not exemplify the text, the comma would make the example work:
```
# Taking a view makes it possible to modify the shape without modifying
# the initial object.

>>> c = b.view()
>>> c.shape = (20)
Traceback (most recent call last):
   ...
AttributeError: Incompatible shape for in-place modification. Use
`.reshape()` to make a copy with the desired shape.
```

Should be
```
# Taking a view makes it possible to modify the shape without modifying
# the initial object.

>>> c = b.view()
>>> c.shape
(2, 10)
>>> c.shape = (20,)
>>> c.shape
(20,)
```

Would you like to submit a PR?

**Comment by Neilblaze** [comment]
@mattip can I take this up if it's up for grabs? 😄

**Comment by Neilblaze** [comment]
oh sorry, I didn't notice & ended up creating the PR 😓 
@JoryKlaverstijn If you want I can add you as co-author in the same PR! 😄

**Comment by JoryKlaverstijn** [comment]
I think I did it :) @mattip 
https://github.com/numpy/numpy/pull/23491

**Comment by seberg** [comment]
Just an N.B.:  I would strongly discourage the use of `arr.shape = ...`, mutating array metadata like that is not generally safe and has practically no benefit.  Sure, if you just created a new array, its safe, but then `.reshape()` is also.

The only "feature" is that you get an error on copy, which is nothing more than:
```
new = arr.reshape(...)
# For base NumPy arrays, otherwise, may need to use `np.may_share_memory` for ease
if new.base is None:
    raise ValueError("Ahhhhhh, copy was made!")
```

I had proposed adding `copy=False` to reshape for that, but it had some ranks going elsewhere that then got bogged down by discussion about how `copy=...` should be spelled which oscillated back and forth long enough for me to lose enthusiasm.
