### ISSUE TITLE
DOC: undocumented call of tuple type (reshape) 

### ISSUE THREAD

**Issue by ShalokShalom** [numpy/numpy#23485]
### Issue with current documentation:

I see nowhere in the documentation, that 2, causes a tuple to be the type:

https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

The comma seems to call that, where can I see this in the documentation? 

### Idea or request for content:

It seems to be a convention, to call it like that. 

Can we document that?

The same seems to be the case in other functions.

Thanks

**Comment by mattip** [comment]
Could you give an example of what behaviour bothers you? I am not sure I understand where the extra comma is problematic.

**Comment by ShalokShalom** [comment]
Now I understand: I am new to Python, and didn't know that (x, ) is the conventual way of defining a tuple. 

Now it all makes sense.
