### ISSUE TITLE
BUG: np.where(condition) can't find all the elements which satisfy the condition, when the input 1-D array is generated by np.arange()

### ISSUE THREAD

**Issue by REN-Yuke** [numpy/numpy#23482]
### Describe the issue:

**np.where(condition) can't find all the elements which satisfy the condition, when the input 1-D array is generated by np.arange()**

I will show the problem by an example.
Here, iouThrs is [0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95], which presents all the iou threshold I can choose. iouThr is the exact iou threshold I chose. Then I want to know the order of the iouThr value in the list iouThrs.

When I use iouThrs=np.arange(0.5, 1, 0.05) to get iouThrs, there is a bug !
When iouThr=0.5 or 0.55, the output of mp.where(iouThr == iouThrs) is  (array([0], dtype=int64),) or (array([0], dtype=int64),).
But when iThr=0.6 or 0.75 ......, the output of mp.where(iouThr == iouThrs) is (array([], dtype=int64),), which means numpy can not find it in the list.**Only the first two elements perform correctly, others are wrong.** 

When I use iouThrs=np.array([0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.90, 0.95]) to get iouThrs, every thing is OK! So there must be some difference between the result of np.arange() and np.array().

### Reproduce the code example:

```python
import numpy as np


iouThrs = np.arange(0.5, 1, 0.05)
iouThr = 0.75
index = mp.where(iouThr == iouThrs)
print(index)
```

### Error message:

```shell
The correct output should be:
(array([5], dtype=int64),)

But the actual output is:
(array([], dtype=int64),)
```

### Runtime information:

1.21.5
3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

I used cocoEval of [cocoapi](https://github.com/cocodataset/cocoapi) to evaluate my network. But I found that mAP@0.75 is always equal to -1, which should be between 0 and 1. So I scrutinized the code and found it went wrong when selcet a parameter iouThr. 

The below link this where I found the bug. It use np.where() to find the order of iouThr in the p.iouThrs .
[t = np.where(iouThr == p.iouThrs)[0]](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L449)

**Comment by REN-Yuke** [comment]
Alright, I knew why it will be a bug!  WoW, I don't know what to say.
See below:
![1](https://user-images.githubusercontent.com/76557164/228535838-1c7b82ad-0ff5-49a2-96de-3beb22c33316.png)
![2](https://user-images.githubusercontent.com/76557164/228535851-f3f43abc-2f82-46a0-983a-9f25ea5eb9dc.png)
![3](https://user-images.githubusercontent.com/76557164/228535856-ad735fa6-3616-411b-b5e9-5354337ab0b4.png)

**Comment by mattip** [comment]
Floating point arithmetic is tricky.
Glad you realized what the problem is. 
Please in the future copy-paste text rather than images.
