### ISSUE TITLE
iOS: Steps for Build Numpy iOS 

### ISSUE THREAD

**Issue by Nik20112** [numpy/numpy#23493]
### Steps to reproduce:

I do not find any proper steps how to build this numpy lib which compatible for iOS architecture and can use in iOS project.

Please provide the steps so we can generate the framework for iOS

Thanks in advance for support

**Comment by Nik20112** [comment]
I am using Pyto lib for iOS but here are required to add Numpy and other libs. So can compile this lib and add in iOS project.

@mattip Please check the screen shot.

![Screenshot 2023-03-30 at 18 03 32](https://user-images.githubusercontent.com/5564036/228837341-47b2e501-938f-423c-a48a-e6433f608c50.png)

**Comment by mattip** [comment]
I see numpy is [included in pyto's third-party](https://pyto.readthedocs.io/en/latest/third_party.html) libraries. I think you may have better luck getting help on the [pyto reddit group](https://www.reddit.com/r/PytoIDE), as suggested in [their FAQ](https://pyto.readthedocs.io/en/latest/faq.html)

**Comment by seberg** [comment]
Seems more like a problem with pyto or so and generally an old install issue, so closing.
