### ISSUE TITLE
BUG: dot can create a 0d array with dtype=object that can assert in ufuncs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23492]
While debugging #15186, I discovered that the following code hit an [`assert(in1 != NULL)` in the inner loop](https://github.com/numpy/numpy/blob/3e77f904a9cc82e03d20824425e30edcd8088484/numpy/core/src/umath/loops.c.src#L259):
```
>>> a = np.array([0], dtype=object)
>>> b = np.tensordot(a[1:], a[:1], axes=((0,), (0,))
>>> b
array(None, dtype=object)
>>> b.shape
()
>>> b += 1
python: ../numpy/core/src/umath/loops.c.src:259: PyUFunc_OO_O: Assertion `in1 != NULL' failed
```

The assert is only active when debugging. This does not segfault:

```
>>> c = np.array(None, dtype=object)
>>> c += 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by seberg** [comment]
Its just complaining that `np.dot()` doesn't initialize the array correctly (as the comment hopefully explains, the assert is meant to be a: "lets try to not run into it").

But it is pointing out a bug: dot should zero fill the result if the operation is empty (specifically for object array, but really more generally, in all other cases that's just the same as zeroing).

**Comment by seberg** [comment]
Sorry, to be more clear `b` should be `np.array(0, dtype=object)` and not `np.array(None, dtype=object)`.

**Comment by mattip** [comment]
I am not hitting that codepath: the memset is for 0d arrays. This may be another bug?

**Comment by seberg** [comment]
Argg, except need to be careful with `out=`.  Just zero-filling might not properly decref what is in it.  So this is more wrong...

Yes, you are right, the bug you saw first is in `OBJECT_dot`, which doesn't account for the zero size.  Although, I wondering if the memset wasn't supposed to prevent calling it here (but maybe not, probably it was supposed to prevent an outer iteration).

I think I fixed this a decade ago, and I didn't realize about object intricacies :).

**Comment by seberg** [comment]
Oh, then I take that back :), and `OBJECT_dot` is free to not deal with it, hehe.

**Comment by mattip** [comment]
The `memset` codepath is tested in `test_regression`, but the test only runs `dot()` and does not check that the output is usable. I found it in `test_einsum` on line 545 (`np.dot(a[1:], a[:-1])`) since that actually uses the output of `np.dot()` to compare to `np.einsum`. Is is worth an additional test?

**Comment by mattip** [comment]
The test_ticket_1539 tests all combination of dtypes. I think it is enough to check that the output is `0` (and not None). The `memset` code does not change when `out` is supplied.

**Comment by seberg** [comment]
A fix for this was included in gh-18053.
