### ISSUE TITLE
BUG: [meson buildsystem] don't use cc.get_id() == 'msvc'

### ISSUE THREAD

**Issue by Neumann-A** [numpy/numpy#23506]
### Describe the issue:

Basically most cases of `cc.get_id() == 'msvc'` are wrong. 

What you actually want is `cc.get_argument_syntax() == 'msvc'` to e.g. also allow clang-cl to compile numpy. 
(see the patch here https://github.com/Neumann-A/my-vcpkg-ports/blob/master/numpy/fix-build.patch)

### Reproduce the code example:

```python
none needed
```

### Runtime information:

not needed

**Comment by mattip** [comment]
I think there are two things in play here. `get_argument_syntax` is for the command-line arguments, where `get_id` is for quirk detection with the runtime library. Does clang-cl link with a glibc runtime or the msvc runtime?

**Comment by Neumann-A** [comment]
> Does clang-cl link with a glibc runtime or the msvc runtime?

msvc. (and icx probably also does that)

**Comment by rgommers** [comment]
So one of those fixes says that clang-cl does not understand `complex double` and must instead use `_Dcomplex` as type designation. Is that right? I thought that that was really MSVC vs. Clang.

**Comment by Neumann-A** [comment]
```
Command line:  C:/Program Files/LLVM/bin/clang-cl.exe -DWIN32 -D_WIN64 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_ATL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_CRT_INTERNAL_NONSTDC_NAMES -D_CRT_DECLARE_NONSTDC_NAMES -D_FORCENAMELESSUNION -mcrc32 -msse4.2 -utf-8 -std:c11 -D__STDC__=1 -Wno-implicit-function-declaration -WX- -O2 -Oi -MD -Z7 -Brepro -DNDEBUG -IE:/all/vcpkg/installed/x64-win-llvm-release/include E:\b\numpy\x64-win-llvm-release-rel\meson-private\tmpj78vsscz\testfile.c /FoE:\b\numpy\x64-win-llvm-release-rel\meson-private\tmpj78vsscz\output.obj /nologo /showIncludes /utf-8 /c -nologo -DWIN32 -D_WIN64 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_ATL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_CRT_INTERNAL_NONSTDC_NAMES -D_CRT_DECLARE_NONSTDC_NAMES -D_FORCENAMELESSUNION -mcrc32 -msse4.2 -utf-8 -std:c11 -D__STDC__=1 -Wno-implicit-function-declaration -WX- -O2 -Oi -MD -Z7 -Brepro -DNDEBUG /nologo /showIncludes /utf-8 /c /Od /Oi- /clang:-std=c99 

Code:
 #include <complex.h>
        void bar(void) {
            sizeof(_Fcomplex);
        }
Compiler stdout:
 Note: including file: C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\complex.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt.h
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vcruntime.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\sal.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\concurrencysal.h
Note: including file:    C:\Program Files\LLVM\lib\clang\15.0.7\include\vadefs.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vadefs.h

Compiler stderr:
 clang-cl: warning: argument unused during compilation: '-std:c11' [-Wunused-command-line-argument]
clang-cl: warning: argument unused during compilation: '-std:c11' [-Wunused-command-line-argument]
E:\b\numpy\x64-win-llvm-release-rel\meson-private\tmpj78vsscz\testfile.c(3,13): warning: expression result unused [-Wunused-value]
            sizeof(_Fcomplex);
            ^~~~~~~~~~~~~~~~~
1 warning generated.

Checking for type "_Fcomplex" : YES 
```
clang-cl uses mostly the same headers as MSVC and thus provides the same types. Otherwise binary compatibility between MSVC and clang-cl would simply not be possible.

**Comment by rgommers** [comment]
Thanks for confirming @Neumann-A. I think I'll have to go fix this in a few other places too.

**Comment by eli-schwartz** [comment]
> Does clang-cl link with a glibc runtime or the msvc runtime?

It really has nothing to do with glibc, since glibc is not exactly ported to Windows and a libc is probably the wrong target for that. MinGW-based compilers could target either the cygwin runtime (not a glibc -- it's based on newlib instead) or msvcrt / ucrt.

In general, any MinGW-based compiler will not have the MSVC argument syntax. If you check the codebase, you can confirm that any compilers inheriting from VisualStudioLikeCompiler use MSVC argument syntax -- this includes actual MSVC, clang-cl, intel-cl.

**Comment by eli-schwartz** [comment]
> I think there are two things in play here. `get_argument_syntax` is for the command-line arguments, where `get_id` is for quirk detection with the runtime library.

The purpose of id is to tell you what branding the compiler has. This may be useful for a couple reasons, including for example descending into an if statement that then checks some hardcoded version numbers and does something specific depending on the version. It's also useful in cases where, say, you know on Linux that certain options are supported by either clang or gcc but not both. Whatever the reason, if you're checking the compiler id then that means you want to be able to code your logic by targeting compiler names, not targeting interfaces such as OS interfaces.

**Comment by rgommers** [comment]
I opened gh-23551 to address this, mostly taking over @Neumann-A's patch.
