### ISSUE TITLE
DOC: Instructions for skipping CI jobs are unclear

### ISSUE THREAD

**Issue by MatteoRaso** [numpy/numpy#23517]
### Issue with current documentation:

The only instructions for skipping CI jobs are on [a single paragraph](https://numpy.org/doc/stable/dev/development_workflow.html#commands-to-skip-continuous-integration) and don't explain what each of the jobs do. This makes it very difficult to know which ones should be skipped.

### Idea or request for content:

I suggest that the guide is updated to explain what each of the jobs do, ideally with examples of when to skip particular jobs.

**Comment by melissawm** [comment]
This is a good point - for example, the refguide_check is only run under the Azure actions and may be missed if you do a documentation update and use `[skip azp]`

I can put in a quick PR with the details.
