### ISSUE TITLE
BUG: <Error in the Numpy 'cov()' function: ' prefix>

### ISSUE THREAD

**Issue by arnav10goel** [numpy/numpy#23527]
### Describe the issue:

The numpy covariance matrix has a bug as it is saying float has no shape, but why is it calling shape on a float?

### Reproduce the code example:

```python
import numpy as np

covariance_matrix = np.cov(data_matrix, rowvar=False)
```

### Error message:

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/arnav/Desktop/ML Codes/SML_Project/Data.ipynb Cell 3 in ()
     11     return covariance_matrix
     13 # Find the covariance matrix
---> 14 covariance_matrix = find_covariance_matrix(data_matrix[:, :-1])

/Users/arnav/Desktop/ML Codes/SML_Project/Data.ipynb Cell 3 in find_covariance_matrix(data_matrix)
      7 data_matrix = data_matrix - mean
      8 # Find the covariance between any two columns
----> 9 covariance_matrix = np.cov(data_matrix, rowvar=False)
     11 return covariance_matrix

File <__array_function__ internals>:180, in cov(*args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2680, in cov(m, y, rowvar, bias, ddof, fweights, aweights, dtype)
   2677     else:
   2678         w *= aweights
-> 2680 avg, w_sum = average(X, axis=1, weights=w, returned=True)
   2681 w_sum = w_sum[0]
   2683 # Determine the normalization

File <__array_function__ internals>:180, in average(*args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:554, in average(a, axis, weights, returned, keepdims)
...
--> 554     if scl.shape != avg.shape:
    555         scl = np.broadcast_to(scl, avg.shape).copy()
    556     return avg, scl

AttributeError: 'float' object has no attribute 'shape'
```

### Runtime information:

Yes I am running NumPy 1.24.3

### Context for the issue:

It is affecting my course project

**Comment by mattip** [comment]
What is the value of `data_matrix`?

**Comment by olinjohnson** [comment]
Doesn't `np.cov()` accept an array-like object as its first parameter? - A float would not satisfy this condition

https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/lib/function_base.py#L2487-L2544

**Comment by rohan472000** [comment]
To debug this issue, you can try printing the shape and type of `data_matrix` before passing it to `np.cov()`. Additionally, you can try using the `np.asarray()` function to explicitly convert `data_matrix` to a NumPy array before passing it to `np.cov()`.

**Comment by arnav10goel** [comment]
So the input data i.e. data_matrix is a 1217 x 4096 matrix. The data type is float for all the columns of the matrix. It is giving this error when I try to find the covariance matrix. However, when I scale the data, it works perfectly fine. I do not understand why this is happening. Point is after scaling, the matrix would still remain of datatype float which is puzzling and hence probably some bug I can't understand.

**Comment by arnav10goel** [comment]
@mattip @olinjohnson @rohan472000

**Comment by WarrenWeckesser** [comment]
I suspect your array has type `object`.  With NumPy 1.24.3, I can reproduce the error if I pass `cov` an array with type `object`, where all the objects are Python `float` instances.

```
In [7]: np.__version__
Out[7]: '1.24.3'

In [8]: d = np.ones((2, 6), dtype=object)

In [9]: np.cov(d, rowvar=False)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 np.cov(d, rowvar=False)

File <__array_function__ internals>:200, in cov(*args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2681, in cov(m, y, rowvar, bias, ddof, fweights, aweights, dtype)
   2678     else:
   2679         w *= aweights
-> 2681 avg, w_sum = average(X, axis=1, weights=w, returned=True)
   2682 w_sum = w_sum[0]
   2684 # Determine the normalization

File <__array_function__ internals>:200, in average(*args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:555, in average(a, axis, weights, returned, keepdims)
    551     avg = avg_as_array = np.multiply(a, wgt,
    552                       dtype=result_dtype).sum(axis, **keepdims_kw) / scl
    554 if returned:
--> 555     if scl.shape != avg_as_array.shape:
    556         scl = np.broadcast_to(scl, avg_as_array.shape).copy()
    557     return avg, scl

AttributeError: 'float' object has no attribute 'shape'
```

@arnav10goel, can you check the `dtype` attribute of `data_matrix`?  E.g. add `print(data_matix.dtype)`.

If that is the problem, you should be able to fix the issue by using

```
covariance_matrix = np.cov(data_matrix.astype(np.float64), rowvar=False)
```

Or (even better) modify the code where `data_matix` is created to avoid creating an `object` array.  Did you use Pandas to create the array?  Pandas is a common source of `object` arrays.

This is a good example of the need for a *complete* minimal example to be included in the issue.  You haven't shown how you created `data_matrix`, so we can only guess at what the problem might be.

**Comment by arnav10goel** [comment]
Oh yes my bad, that works. Thanks a lot and sorry for the trouble!!
