### ISSUE TITLE
BUG: indexing returns a contiguous array iff index is in the leading dimension

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#23524]
### Describe the issue:

When indexing a numpy array in the leading dimension, the resulting array will be `C_CONTIGUOUS`. If indexing in any other dimension, it's not.

### Reproduce the code example:

```python
import numpy as np

a = np.random.rand(5, 5, 5)
idx = [0, 1, 2, 3, 4]

b = a[idx]
print(b.flags["C_CONTIGUOUS"])

b = a[:, idx]
print(b.flags["C_CONTIGUOUS"])

b = a[..., idx]
print(b.flags["C_CONTIGUOUS"])

```
```python
True
False
False
```

### Runtime information:

```
1.24.2
3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
```
```
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None
```

**Comment by seberg** [comment]
The answer is "yes", this is intentional documented (somewhere).  I don't mind if you want to attempt to tweak it, but I don't think this is a bug.  NumPy doesn't generally guarantee memory order preservation.

Maybe it is a bit unfortunate that you cannot pass `out=` which would allow you to force memory order.  I suppose that would be an argument to have a functional syntax for indexing with kwargs.

**Comment by seberg** [comment]
You could use take, which currently supports it (and supports a carefully crafted out).

But except in corner cases where you index the last dimension and it happens to have 2-5 entries, I would expect that to just be much slower.
