### ISSUE TITLE
Nightly wheel build for macosx on arm64 failing 

### ISSUE THREAD

**Issue by charris** [numpy/numpy#23538]
See https://github.com/numpy/numpy/actions/runs/4624671118/jobs/8188472241. The relevant bit seems to be
```
        raise RuntimeError(
    RuntimeError: Broken toolchain during testing C compiler.
    A compiler with support for C99 language features is required.
```
This is new as of 4/5/2023., I'm guessing it is related to the C++ work. @seiko2plus Any ideas.

**Comment by rgommers** [comment]
So the issue is:
```
     INFO: compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-jk3hxvnd/cp39-macosx_arm64/build/venv/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -Ibuild/src.macosx-11.0-arm64-3.9/numpy/core/src/common -Ibuild/src.macosx-11.0-arm64-3.9/numpy/core/src/npymath -c'
    extra options: '-Werror -std=c99'
    INFO: clang: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpr7mbkah7/test.c
    error: overriding currently unsupported use of floating point exceptions on this target [-Werror,-Wunsupported-floating-point-opt]
    1 error generated.
```

Doesn't immediately look familiar to me.

**Comment by andyfaff** [comment]
It might be time to add a native `macosx_arm64` task to cirrus-ci. 
At the moment those wheel builds aren't being tested either. arm64 is increasingly important compared to x86_64 on macOS.

**Comment by andyfaff** [comment]
In fact the only macOS CI test run that I can find is during the wheel build for `macosx_x86_64`, which happens once a week.

**Comment by charris** [comment]
I believe both architectures are tested in the wheel build. The wheel builds can be tested in PRs by adding the `build` label. However, it would be good to have a test for the mac arm64 builds that always ran.

**Comment by andyfaff** [comment]
`macosx_arm64` isnt being tested in the wheel build. It's not possible to do this because it's a cross compile.

**Comment by andyfaff** [comment]
Building is also broken on my local computer. `git bisect` localises it to d183edf54

```
(numpy-dev) 192-168-1-113:numpy andrew$ clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by mattip** [comment]
This looks suspicious
```
extra options: '-Werror -std=c99'
```

@seiko2plus shouldn't that be `c++17`?

In any case, I agree that a macos arm64 CI run would be helpful.

**Comment by andyfaff** [comment]
Looking into this further the [test program](https://github.com/numpy/numpy/blob/main/setup.py#L296) that's trying to be compiled is:
```
inline int test_inline()
{ return 0; 
}
int main(void)
{ return test_inline(); }
```
I tried compiling that file as `clang test.c -std=c99`.

That came up with this error:
```
Undefined symbols for architecture arm64:
  "_test_inline", referenced from:
      _main in test-31ecf4.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

However, making the function definition either `inline static int test_inline(` or `extern inline int test_inline` successfully compiles.

See https://github.com/llvm/llvm-project/issues/55274 for more details.

I think the test code needs to use one or other of the solutions I suggested.

**Comment by andyfaff** [comment]
Whilst the test program that includes `static` is now more suitable for compilation on `macosx_arm64` it doesn't fix the underlying issue.

I tried to compile the 'improved' program
```
inline static int test_inline() { return 0; }
int main(void)
{ return test_inline(); }
```
but it didn't work:

```
(numpy-dev) 192-168-1-113:numpy andrew$ clang test.c -arch arm64 -std=c99 -ftrapping-math -Werror
error: overriding currently unsupported use of floating point exceptions on this target [-Werror,-Wunsupported-floating-point-opt]
1 error generated.
```

So presumably `-ftrapping-math` is currently unsupported on `macosx_arm64`. This flag is added in [ccompiler.py](https://github.com/numpy/numpy/blob/main/numpy/distutils/ccompiler.py#L397) when clang is being used. I can add something in to avoid the flag being added. However, I'm not sure of the ramifications of doing so.

Related link: https://developer.apple.com/forums/thread/689159

**Comment by charris** [comment]
@andyfaff The arm64 builds were not uploaded in the latest nightly build. I wonder if it is a cron configuration problem?

**Comment by charris** [comment]
This remains a problem.

**Comment by andyfaff** [comment]
Do you have a log file?

**Comment by andyfaff** [comment]
I have another inkling as to what the issue is. What is the cron job called in the cirrus-ci configuration? I think it was originally 'nightly', but @mattip may have changed it to 'weekly' in a031a84979d1deefa5cba78c1fdb564ed74cd674. This means that [this](https://github.com/numpy/numpy/blob/main/.cirrus.star#L20) need to be changed to:

```
if env.get("CIRRUS_CRON", "") == "weekly":
```

I can't say for sure without knowing what the cron job is called. I don't have access to that configuration.

**Comment by charris** [comment]
@andyfaff On further checking, I think it is working.  What threw me off is that the cirrus cron is run on Sundays (settings on the Cirrus web API) rather than Wednesdays like the rest of the wheel builds. If I check for what was uploaded to nightly four days ago I find all 6 of the arm wheel builds (aarch64 & arm64).

**Comment by andyfaff** [comment]
The line I referred to above should still probably be changed.

**Comment by seiko2plus** [comment]
Avoid uses `-Werror` (#23654) should fix this issue since its treats warnings of unsupported compiler options as errors.
> error: overriding currently unsupported use of floating point exceptions on this target
