### ISSUE TITLE
BUG: array type complex256 is unsupported in linalg

### ISSUE THREAD

**Issue by cphys** [numpy/numpy#23536]
### Describe the issue:

When operating on array types of `complex256`,  `numpy.linalg` functions return TypeErrors. The same `scipy.linalg` functions work fine. 

This causes problems with compatibility with projects which are using both packages, especially when using functions such as `sp.linalg.sqrtm` which double the precision of the input complex matrix.

Below I show a simple of example of the same numpy and scipy linalg functions operating on the same `complex256` array and the scipy function works while the numpy function fails. This behavior is not limited to eig, it is repeatable with all of the functions which I tested.

### Reproduce the code example:

```python
import numpy as np
import scipy as sp

# create a numpy array of type complex128
a = np.array([[1.0, 3.0], [1.0, 4.0]],dtype=np.complex128)
print(type(np.square(a[0][0])))

# sqrtm returns an array of complex256
b = sp.linalg.sqrtm(a)
print(type(np.square(b[0][0])))

# arrays of type complex128 will run fine for both
# scipy and numpy functions
print(type(np.linalg.eig(a)[0][0]))
print(type(sp.linalg.eig(a)[0][0]))

# arrays of type complex256 will run for
# scipy functions, but not for the exact same numpy function
# it would seem that scipy functions reduce the precision of
# the complex256 inputs while numpy functions throw a TypeError
print(type(sp.linalg.eig(b)[0][0]))
print(type(np.linalg.eig(b)[0][0]))
```

### Error message:

```shell
<class 'numpy.complex128'>
<class 'numpy.complex256'>
<class 'numpy.complex128'>
<class 'numpy.complex128'>
<class 'numpy.ndarray'>
Traceback (most recent call last):
  File "/home/randygingerbread/projects/scipy_numpy_bug/scipy_test.py", line 20, in <module>
    print(type(np.linalg.qr(b)[0][0]))
  File "<__array_function__ internals>", line 200, in qr
  File "/home/randygingerbread/.local/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 915, in qr
    t, result_t = _commonType(a)
  File "/home/randygingerbread/.local/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 147, in _commonType
    raise TypeError("array type %s is unsupported in linalg" %
TypeError: array type complex256 is unsupported in linalg
```

### Runtime information:

1.24.2
3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/cphys/.local/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 4,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None

### Context for the issue:

When working on projects which include the use of numpy and scipy, and which are performing multiple matrix operations on arrays/matrices, having numpy functions throw errors when encountering `complex256` matrices is problematic.

This is especially true when functions such as `scipy.linalg` will upgrade any `complex128` array to a `complex256`.

**Comment by seberg** [comment]
Which SciPy version are you on?  I don't think SciPy supports this, it just downcasts for you.  And promoting to complex256 seems more likely a bug than intentional.

So I think you should open a SciPy issue, the NumPy behavior looks fine to me (no silent downcast).

**Comment by cphys** [comment]
I am on `scipy 1.10.0`. It actually describes the promoting of the behavior in the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.sqrtm.html) for scipy.linalg.sqrtm.

That was why I posted the bug here. Because all other numpy functions (not in numpy.linalg) are able to operate on `Complex256` type arrays.

I can open the issue over there and see what they say.

**Comment by seberg** [comment]
Frankly, just seems a bit of an ooops, on the SciPy side to me.

**Comment by cphys** [comment]
Yeah I think that you are right.
