### ISSUE TITLE
DOC: deprecated test syntax

### ISSUE THREAD

**Issue by Mikhaylov-yv** [numpy/numpy#23534]
### Issue with current documentation:

Good afternoon.

I made a build of the source code from the main branch and ran the tests.
I got an error when specifying a test as a parameter `--tests TESTS, -t TESTS`
When executing this code:

```
python runtests.py -v -t numpy/core/tests/test_nditer.py
```
I get error: `ERROR: module or package not found: numpy/core/tests/test_nditer.py (missing __init__.py?)`

If I use which syntax

```
python runtests.py -v -t numpy.core.tests.test_nditer
```

Everything works correctly

In the documentation, including the file  [development_environment.rst](https://github.com/numpy/numpy/blob/main/doc/source/dev/development_environment.rst#testing-builds), the first implementation option is indicated. 

## Runtime information:
```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.25.0.dev0+1062.g7f1ce595c
3.10.10 (main, Mar 23 2023, 17:28:09) [GCC 10.2.1 20210110]
>>> print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.0.dev0+1062.g7f1ce595c',
  'python': '3.10.10 (main, Mar 23 2023, 17:28:09) [GCC 10.2.1 20210110]',
  'uname': uname_result(system='Linux', node='aa562c94224b', release='5.15.90.1-microsoft-standard-WSL2', version='#1 SMP Fri Jan 27 02:56:13 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}}]
```

If this documentation is outdated, I might update it.

**Comment by seberg** [comment]
Hmmm, `runtests` does a bit of a round-about invocation of via calling `np.test()`.  Which looks like it ends up using `... --pyargs <test1> <test2>`.

Probably pytest changed `--pyargs` to not accept the directory spelling anymore?  I wonder if we should just tweak `runtests` to also accept paths if that really changed.  OTOH, probably also OK to just document it and get used to the `.` spelling.  (although I think pytest prints the test names as path making copy pasting harder then)

**Comment by Mikhaylov-yv** [comment]
@seberg I agree with you. Specifying the test via the path looks more convenient than what we have now. I'll look in the history of the reasons for these changes.

**Comment by seberg** [comment]
There is a point that I think `spin` should replace runtests relatively soon, either way.  

So rather than trying to hunt that down, that section should maybe just point to using spin instead:
```
spin test
```
(requires installing spin through conda-forge or pip of course)

I suspect `spin` calls `pytest` more directly anyway, so that paths work fine.

**Comment by renoauerbach** [comment]
Documentation has been updated to use spin.  Can we close this issue? https://github.com/numpy/numpy/blob/fba4fc16a26e77ec4ce2b1900577f088b1d5a7a6/doc/source/dev/development_environment.rst?plain=1#L91-L95

**Comment by rossbar** [comment]
Thanks @renoauerbach - I agree, let's close this. If the issue persists, consider opening a new one that highlights any problems with the new workflow.
