### ISSUE TITLE
``CircleCI artifact redirector `` has started failing again.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#23548]
Same error as in #23409. Nothing has changed upstream AFAICT, unless in circleci.

**Comment by charris** [comment]
I think the problem is that the redirector runs before the artifact build starts/finishes. There are some other indications that serialization of tests have changed.

**Comment by melissawm** [comment]
Here's what needs to be done (by a repo owner):

Hi folks! CircleCI doc preview links are currently not working due to an upstream bug. Here's what needs to be done to restore it:

> 1. You can create a personal CircleCI token here (I named mine CIRCLE_STATUS): app.circleci.com/settings/user/tokens
> 2. Add the token value (from the CircleCI website) it to the secrets of your org or project, e.g., for MNE-Python I added it under the name CIRCLE_TOKEN for the org to github.com/organizations/mne-tools/settings/secrets/actions
> 3. Add it to the action as api-token: ${{ secrets.CIRCLECI_TOKEN }} in the with for the action

If any admins on the repo can create the token, I can put in a PR with the api-token definition.

**Comment by jarrodmillman** [comment]
https://github.com/larsoner/circleci-artifacts-redirector-action/issues/40

**Comment by melissawm** [comment]
That is definitely right thanks for the context @jarrodmillman ! Seeing these all across the repos today and trying to help by spreading the word 😄

**Comment by charris** [comment]
Looks fixed, thanks all.
