### ISSUE TITLE
BUG: np.arange(0.1, 0.4, 0.1) gives out wrong output

### ISSUE THREAD

**Issue by dgg95223** [numpy/numpy#23567]
### Describe the issue:

When I try to create an array of `[0.1, 0.2, 0.3] `with `np.arange(0.1, 0.4, 0.1)`, it gives out `[0.1, 0.2, 0.3, 0.4]`.
However, when '0.4' is replaced with other number, for example, 0.3, it can work fine with giving out `[0.1, 0.2]`.

### Reproduce the code example:

```python
import numpy as np
a=np.arange(0.1, 0.4, 0.1)
print(a)
```

### Runtime information:

1.20.3
3.9.7 (default, Sep 16 2021, 13:09:58)
[GCC 7.5.0]

**Comment by rkern** [comment]
This is [documented behavior](https://numpy.org/doc/1.24/reference/generated/numpy.arange.html). We have [more detailed information and recommendations here](https://numpy.org/doc/1.24/user/how-to-partition.html).
