### ISSUE TITLE
ENH: Proposal for   np.sample() method

### ISSUE THREAD

**Issue by eskayML** [numpy/numpy#23575]
### Proposed new feature or change:

Okay, Please don't get me wrong

I'm aware that there's already a module as np.random.sample() & np.random_sample()
 but I looked through them and they didn't really tend to be helpful to me.

Why i made this request was because I was working on a problem where I needed to get 5000 random samples out of a very large numpy array,
This would't have been a problem at all , since pandas actually has the `pd.sample()`  method  but the array i'm working with is greater than 2d

 I tried implementing the default `random.sample(array, 5000)` method from python too,
 it ended produced an error stating that the array must be sorted

Please Is there any way to work around sampling 5000 elements from a 4-dimensional numpy array , if my feature request might go against some rules of this repository

**Comment by bwalshe** [comment]
`np.random.sample()` produces a new array with a entries that are floating point numbers between 0 and 1. So for example you could use the following to generate an array of two random numbers:

```
>>> np.random.sample(2)
array([0.26870356, 0.50479026])
```

It sounds like you actually want `np.random.choice` which allows you to pick numbers from an existing array. That can be used as follows:

```
>>> xs = np.array(range(1_00_00)) # or however you are generating your big array.
>>> np.random.choice(xs, 10) # take a sample of 10 entries from this array
array([5235, 7220, 9640, 2720, 5386,  222, 9454,  388, 4939, 1881]
```

**Comment by eskayML** [comment]
![{993EB742-C526-4801-81AD-7CD2CB98C5CB} png](https://user-images.githubusercontent.com/71832907/231885531-f5a03994-b86b-4f79-9bde-8d76f34a6ecf.jpg)
@bwalshe Thanks for your solution 
but it still doesn't account for the issue of the dataset being more than 1-dimensional

I later came up with a great implementation

```python
num_samples = 5000
indices = np.random.choice(train_images.shape[0], num_samples, replace=False)
selected_samples = train_images[indices]
```

So I randomly  selected indexes out of my array without repetition, so that I can easily access corresponding samples from the train_images
