### ISSUE TITLE
Error from "import numpy": undefined symbol: _ZSt21__glibcxx_assert_failPKciS0_S0_

### ISSUE THREAD

**Issue by cmarmo** [numpy/numpy#23595]
### Steps to reproduce:

I am compiling numpy from source (main 1.25.0.dev0+1173.g7f682bca5) on Fedora 37.
- Python 3.11
- GNU C Library (GNU libc) stable release version 2.36.
- g++ (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2)

I am compiling in a python venv, the C and C++ libraries are from the Fedora distribution.
```
$ pip install -e .
```
The compilation went well, but when importing from the python console:
```
>>> import numpy
```
the following error is thrown

### Error message:

```shell
Traceback (most recent call last):
  File "/home/cmarmo/software/numpy/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/cmarmo/software/numpy/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/cmarmo/software/numpy/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/cmarmo/software/numpy/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZSt21__glibcxx_assert_failPKciS0_S0_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cmarmo/software/numpy/numpy/__init__.py", line 139, in <module>
    from . import core
  File "/home/cmarmo/software/numpy/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/home/cmarmo/numpydevenv/bin/python"
  * The NumPy version is: "1.25.0.dev0+1173.g7f682bca5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /home/cmarmo/software/numpy/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZSt21__glibcxx_assert_failPKciS0_S0_
```

### Additional information:

I have upgraded and downgraded the libstdc++ as far as possible in fedora37, but the error is still there.
I have compiled with meson too and the result is the same.
I don't know if the issue is from numpy or the fedora packaging, but [on the mailing list](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/E3ZNI67JFQ5XJ67XA2ZWEVDXR46SFR5P/) I have been suggested to open an issue here as apparently this behavior is reproducible.

**Comment by charris** [comment]
The problem came in with #23521. @seiko2plus Thoughts?

**Comment by charris** [comment]
There is a closed bug report on redhat bugzilla, it was a library problem, the symbol was hidden. Maybe they reintroduced it? Or maybe it isn't really fixed. See https://bugzilla.redhat.com/show_bug.cgi?id=2060755

**Comment by seberg** [comment]
Might be a bit similar to gh-23122 (which is clang)?  I wonder if there are some asserts we could just remove to make both fine for now?  Although, shouldn't a normal build make asserts debugging?

**Comment by charris** [comment]
The function occurs in
```
charris@fc [numpy.git (testing)]$ grep -r glibcxx_assert_fail
grep: build/testenv/lib64/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so: binary file matches
grep: build/lib.linux-x86_64-3.11/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so: binary file matches
grep: build/temp.linux-x86_64-3.11/numpy/core/src/npysort/selection.o: binary file matches
grep: build/temp.linux-x86_64-3.11/numpy/core/src/npysort/binsearch.o: binary file matches
```

I think the two sort functions are the problem, probably missing a needed compile flag somewhere. @serge-sans-paille Any ideas?

**Comment by rgommers** [comment]
> Might be a bit similar to [gh-23122](https://github.com/numpy/numpy/issues/23122) (which is clang)?

Looks similar indeed. The suggestion in that issue was to switch to using the C++ linker instead of the C linker, which we can do in `main` I'd say.

**Comment by charris** [comment]
There is also this preceding the call:
```
#if __cplusplus >= 201402L
```
Which probably explains why things broke with the c++ upgrade.

**Comment by serge-sans-paille** [comment]
easiest and safest past : use the C++ linker as suggested by @rgommers . The demangled symbol is `std::__glibcxx_assert_fail(char const*, int, char const*, char const*)`, it results from the expansion of `assert`.

Alternate option: use a numpy-specific assert that does not require any library symbol, but there's no guarantee that another symbol won't be needed in the future (unless we use `-ffreestanding`, but this restricts a lot the library part we can use (see https://en.cppreference.com/w/cpp/freestanding , esp. the *Note* section)

**Comment by serge-sans-paille** [comment]
As a side note : it also means that OP is compiling with asserts ON, not 100% sure it's desired.

**Comment by charris** [comment]
Defining NDEBUG in the relevant files makes no difference, which seems unfortunate. The reasoning is
```
#pragma GCC visibility push(default)
  // Avoid the use of assert, because we're trying to keep the <cassert>
  // include out of the mix.
  extern "C++" _GLIBCXX_NORETURN
  void
  __glibcxx_assert_fail(const char* __file, int __line,
			const char* __function, const char* __condition)
  _GLIBCXX_NOEXCEPT;
#pragma GCC visibility pop
```
There doesn't seem any easy way to turn that off.

**Comment by charris** [comment]
In other words, it looks like g++ wants to avoid cassert and doesn't provide a way for us to turn this off.

**Comment by rgommers** [comment]
I think we should be fine flipping the switch now on using the C++ linker. In fact the Meson build already does that. I'll send a PR to do the same for the `setup.py` build.

The `NDEBUG` thing for Meson works like this:
- when you build a wheel, the "build type" is _release_ and hence `-DNDEBUG` is used
- when you use `spin` or another way that uses `meson` directly rather than build a wheel with `meson-python`, `-DNDEBUG is not used

I think we're good there. I won't bother trying to change that in `setup.py`.

**Comment by rgommers** [comment]
I see like a 100 failures on `main` due to recent changes, so I guess there's more to do - but that's unrelated to this particular issue, and switching to the C++ linker seems straightforward. 

@cmarmo could you please check if gh-23601 resolves the issue for you?

**Comment by charris** [comment]
Linking with the C++ library didn't fix things for me, I still get the same error.

**Comment by charris** [comment]
I'm using Fedora 37, gcc version 12.2.1 . @rgommers what compiler/version are you using?

**Comment by cmarmo** [comment]
I confirm the fix does not solve the issue for me.

> I think we should be fine flipping the switch now on using the C++ linker. In fact the Meson build already does that. I'll send a PR to do the same for the setup.py build.

Also note that I have build with meson and I have the same error at the import, so this seems to affect both build systems.

**Comment by charris** [comment]
I can confirm that the symbol is defined in libstdc++.so. Seems that the linking is not quite right yet.

**Comment by charris** [comment]
Looks like gcc is still used for the linking of `_multiarray_umath`.

**Comment by charris** [comment]
Found the problem in numpy distutils, an indentation bug :)  I'll leave the meson fix to @rgommers.

**Comment by cmarmo** [comment]
... #23604 seems to fix the meson build too... is that expected?

**Comment by rgommers** [comment]
> ... #23604 seems to fix the meson build too... is that expected?

That can't really be the case. The Meson build won't touch the distutils `build_ext` class, and was already using the C++ linker.

**Comment by rgommers** [comment]
The issue seems Fedora-specific, so I can't really check.
