### ISSUE TITLE
BUG: RuntimeWarning: overflow encountered in cast when casting large float32 to float16 on Mac

### ISSUE THREAD

**Issue by jcwchen** [numpy/numpy#23606]
### Describe the issue:

When casting large float32 to float16, there is a warning `<stdin>:1: RuntimeWarning: overflow encountered in cast`. I only saw this warning on Mac (M1 or old intel CPU) and other platforms are fine without any warning. ~I also tried to cast a super large float64 to float32 and the result seems good without any warning as well~. Besides, I didn't see such a warning if I use numpy<=1.23. Is it expected that such a warning only happens on Mac? If yes, shall I avoid to use this kind of cast in every kind of platform? Thank you for looking into it.

### Reproduce the code example:

```python
import numpy as np
x = numpy.array([ 1000000 ], dtype=numpy.float32)
y = x.astype(numpy.float16)
```

### Error message:

```shell
<stdin>:1: RuntimeWarning: overflow encountered in cast
```

### Runtime information:

numpy 1.24.2; only happened on Mac.

### Context for the issue:

Although different processor might behave differently, ideally it would be great if numpy can perform consistently on different platforms. I don't know whether I should fix this warning on other platform as well.

**Comment by olinjohnson** [comment]
I'm also getting a similar warning running numpy 1.24.2 on a 2020 Macbook Pro with an i5.

**Comment by jcwchen** [comment]
Hi @olinjohnson,
Thank you for catching that! I tried it on my old Mac (2018 non-M1 machine) and indeed the warning happens as well. Thus this warning seems happens on Mac globally. I will correct the info I have provided.

**Comment by jcwchen** [comment]
Thank you for the clarification and providing a way to disable this kind of warning. After more experiments, sorry that I am wrong about it only happened on Mac. Actually this warning also happens on Windows and Ubuntu as well (while using numpy>=1.24). I will close this one since it's not a bug. Thank you both for looking into it.

**Comment by jason-s** [comment]
> You can for example np.errstate(), i.e.:
>
> ```
> with np.errstate(overflow="ignore"):
>    ...
> ```
>
>to disable the warning.

This is incorrect in 1.2.4; it should be 

```
with np.errstate(over="ignore"):
