### ISSUE TITLE
Numpy module not found

### ISSUE THREAD

**Issue by ainursan210** [numpy/numpy#23616]
### Steps to reproduce:

Dear all,

I need Numpy version==1.20 for installation of hivtrace.
I had errors and I downgraded python to version 3.8 through pyenv. Then, the numpy was installed, but when I try to install the hivtrace, it is saying that the Numpy module is not found. However, if I type "pip show Numpy", it gives me a location of Numpy.
Could anyone please help, I am new in this field.
I attached a traceback if I type "pip install hivtrace"
Thank you!
<img width="932" alt="Снимок экрана 2023-04-20 в 00 24 23" src="https://user-images.githubusercontent.com/130979569/233168784-2ce6e693-c46b-4bc2-824d-d2a57706ca92.png">

**Comment by rohan472000** [comment]
Try uninstalling and reinstalling Numpy and hivtrace:

`
pip uninstall numpy hivtrace
pip install numpy==1.20 hivtrace
`

**Comment by ainursan210** [comment]
> Try uninstalling and reinstalling Numpy and hivtrace:
> 
> `pip uninstall numpy hivtrace` `pip install numpy==1.20 hivtrace`
> 
> If you are still having trouble, you could try creating a new virtual environment and installing Numpy and hivtrace in that environment: `python3 -m venv myenv` `source myenv/bin/activate` `pip install numpy==1.20 hivtrace`
> 
> If none of the above steps work, you could try installing hivtrace from the source code: `git clone https://github.com/veg/hivtrace.git` `cd hivtrace` `pip install -r requirements.txt` `python setup.py install`

Hello

Thank you! I tried all of them: first two did not work. Again, the Numpy module was not found.
Then I tried to install hivtrace from the source code, it worked, till the command: "pip install -r requirements.txt"
The tracebacks is: "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"
Should I just try to re-install python? I think things got worst after I installed python 3.8 through pyenv.

**Comment by rohan472000** [comment]
It's because there is no files named requirements.txt instead it is named as requires.txt, but alternatively you can try installing following things manually:-

`
pip install numpy==1.20
pip install biopython
pip install scipy
pip install dendropy
pip install networkx
pip install matplotlib
pip install pytest
`

**Comment by melissawm** [comment]
It looks like this is a hivtrace installation problem, not a numpy installation problem, so I'm closing. Please reopen if that is not correct!
