### ISSUE TITLE
DOC: Mention NPY_NO_DEPRECATED_API in "For downstream package authors"

### ISSUE THREAD

**Issue by chrisb-fico** [numpy/numpy#23610]
### Issue with current documentation:

[depending_on_numpy.html](https://numpy.org/doc/stable/dev/depending_on_numpy.html), states that "Because the NumPy ABI is only forward compatible, you must build your own binaries (wheels or other package formats) against the lowest NumPy version that you support". Is this completely correct? From reading [deprecations.html](https://numpy.org/doc/stable/reference/c-api/deprecations.html) it sounds like it might be sufficient to e.g. `#define NPY_NO_DEPRECATED_API NPY_1_19_API_VERSION` and then you can compile against any NumPy later than 1.19 while still remaining ABI compatible with 1.19 and later. If thjs is true, then `NPY_NO_DEPRECATED_API` should be clearly highlighted in `depending_on_numpy.html`. It is so much easier to just define this macro rather than try to manage which version of NumPy you are building against on every combination of Python version and platform. I have been doing the latter for several years with much pain. If on the other hand this is false, `deprecations.html` should be updated to clarify that defining `NPY_NO_DEPRECATED_API` is not sufficient to ensure ABI compatibility.

**Comment by rgommers** [comment]
That isn't correct I believe. `NPY_NO_DEPRECATED_API` allows you to _exclude_ using some (deprecated) APIs, but it doesn't prevent _including_ too-new APIs or triggering the Cython version checks.

Using [oldest-supported-numpy](https://pypi.org/project/oldest-supported-numpy/) should do the trick and not result in too much pain right now. You may also be interested in gh-23528, which is about to make a significant improvement to how all this works for 1.25.0.

**Comment by chrisb-fico** [comment]
Thanks for clarifying. I propose adding this note to the end of `deprecations.html`:

> Please note that defining `NPY_NO_DEPRECATED_API` is not sufficient to make your extension
> ABI compatible with NumPy 1.17. For that you must compile against the NumPy 1.17 header files.

If you agree I will open a PR.

gh-23528 looks great!

**Comment by rgommers** [comment]
The first sentence sounds good. For the second one, please link to https://numpy.org/devdocs/dev/depending_on_numpy.html#for-downstream-package-authors rather saying "you must compile against ..." - because that will soon not be true anymore (that is gh-23528).

**Comment by chrisb-fico** [comment]
Since you mention `oldest-supported-numpy`, I wonder if you know of a good solution for Anaconda? The Conda instructions at [depending_on_numpy.html](https://numpy.org/doc/stable/dev/depending_on_numpy.html) relate to building on conda-forge where all build environments are already set up with the oldest available NumPy version. We have a commercial package so we cannot build it on open source infrastructure, we have to set up our own build environments. So far I have done this manually and I am now planning to automate this using the Anaconda REST API to determine the oldest available version of https://anaconda.org/conda-forge/numpy and then configure conda-build accordingly.

**Comment by rgommers** [comment]
I'm not sure there's anything better than specifying versions manually. You may be able to simply copy the version pins from `oldest-supported-numpy` though if the REST API is too much of a pain, I think all relevant versions are present in `conda-forge`, except for some reason 1.17.4 and 1.18.2/3.
