### ISSUE TITLE
DOC: Clarify relation of ravel and reshape(-1)

### ISSUE THREAD

**Issue by grothesque** [numpy/numpy#23629]
### Issue with current documentation:

The reference documentation for `numpy.ravel` says:

> When a view is desired in as many cases as possible, arr.reshape(-1) may be preferable.

This seems to imply that there are cases where (for some ndarray `x`) a call to `numpy.ravel(x)` will not return a view while a call to `x.reshape(-1)` will.  However, although I tried quite hard, I was not able to come up with a case where this would be true.  The confusion seems to be more widespread as exemplified by this [third-party statement about both forms being equivalent](https://aman.ai/primers/numpy/#ravel).

A bit further on, the documentation states:

> It is equivalent to reshape(-1, order=order).

This seems to be meant to resolve the above question, but to what order does the right hand side of `order=order` refer to?

### Idea or request for content:

I suggest to state more clearly when `numpy.ravel(x)` and `x.reshape(-1)` are not equivalent.  An example would be very helpful.

I also suggest clarifying the phrase "It is equivalent to reshape(-1, order=order)".  It is currently unclear to what `=order` refers.

**Comment by seberg** [comment]
The docs begin with:  "Return a **contiguous** flattened array".  It guarantees the contiguous part, reshape does not.

So to see, pass a non-contiguous array and flatten it.  I guess it could be repeated in the notes.  OTOH, unlike  reshape, it actually supports `order="K"`.

**Comment by Sarah-Yifei-Wang** [comment]
I personally think this is a valid point. I am happy to contribute to this issue and make it clearer in the documentation. Should I directly submit a PR or there are additional process involved for contribution?

**Comment by MikiPWata** [comment]
@grothesque 
Hi there,
for order=order, I hope its parameter description on the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html#numpy.ravel) helps
![image](https://github.com/numpy/numpy/assets/105326591/9f87a26d-ace1-40e4-94db-d202ed8fac79)
