### ISSUE TITLE
ImportError: symbol not found (numpy/clang)

### ISSUE THREAD

**Issue by LinuxUserGD** [numpy/numpy#23649]
### Steps to reproduce:

Numpy compiled with GCC on same system works fine (no error in Inkscape).
Steps to reproduce:
- additional flags: `-O3 -pipe -march=skylake -mtune=skylake -D_FORTIFY_SOURCE=3 -gsplit-dwarf -flto=thin`
- LDFLAGS: `-fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed -Wl,--compress-debug-sections=zlib -Wl,-z,relro,-z,now -Wl,--undefined-version -Wl,--plugin-opt=dwo_dir= -Wl,--threads=4`
- Compile numpy-[1.24.2](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/numpy/numpy-1.24.2.ebuild) with clang-[16.0.2](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-devel/clang/clang-16.0.2.ebuild)/[17.0.0_pre20230421](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-devel/clang/clang-17.0.0_pre20230421.ebuild) and `-stdlib=libc++`.
- When trying to save an optimized svg with media-gfx/inkscape-[1.2.2](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-gfx/inkscape/inkscape-1.2.2.ebuild), I get the following error message:

### Error message:

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: Error relocating /usr/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: _ZNSt3__122__libcpp_verbose_abortEPKcz: symbol not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/inkscape/extensions/output_scour.py", line 7, in <module>
    import inkex
  File "/usr/share/inkscape/extensions/inkex/__init__.py", line 11, in <module>
    from .extensions import *
  File "/usr/share/inkscape/extensions/inkex/extensions.py", line 34, in <module>
    from .elements import (
  File "/usr/share/inkscape/extensions/inkex/elements/__init__.py", line 13, in <module>
    from ._polygons import PathElement, Polyline, Polygon, Line, Rectangle, Circle, Ellipse
  File "/usr/share/inkscape/extensions/inkex/elements/_polygons.py", line 31, in <module>
    from ..bezier import pointdistance
  File "/usr/share/inkscape/extensions/inkex/bezier.py", line 29, in <module>
    import numpy
  File "/usr/lib/python3.11/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/usr/lib/python-exec/python3.11/python3"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: Error relocating /usr/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: _ZNSt3__122__libcpp_verbose_abortEPKcz: symbol not found
```

### Additional information:

OS: `Gentoo Linux amd64 musl/clang`
Numpy version: numpy-[1.24.2](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/numpy/numpy-1.24.2.ebuild)
Python version: python-[3.11.3](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-lang/python/python-3.11.3.ebuild)
Not sure if it's related to Numpy or a Clang compiler bug.

**Comment by charris** [comment]
See #23595 for a similar issue in main. The fix there was linking with the c++ lib (#23604 and #23601). I'm not sure why you are seeing this in 1.24.2, in the main branch the problem followed from using C++2017 instead of C++2011.

**Comment by charris** [comment]
Also, I think you will need numpy main for musl, there are wheels musl in the nightly builds:
```
pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy
```

Although you may want to download the musl wheel explicitly, I'm not sure how pip knows which wheel to use. See https://anaconda.org/scipy-wheels-nightly/numpy/files.

**Comment by mattip** [comment]
> I'm not sure how pip knows which wheel to use.

Pip uses pypa/packaging, and packaging knows about the musl platform tag. To find out which tags are compatible with your python, you can ask packaging:
```
python3 -c "from packaging import tags; import pprint; pprint.pprint(list(tags.sys_tags()))"
```
