### ISSUE TITLE
BUG: Problems with order of masked arrays in version 1.24.3

### ISSUE THREAD

**Issue by jcrivenaes** [numpy/numpy#23651]
### Describe the issue:

Confer earlier issue: #22912, apparently solved in  #23635.

A new problem has now arisen, demonstrated in the code below. 

### Reproduce the code example:

```python
#!/usr/bin/env python
import numpy as np

print("Using numpy", np.__version__)


def showcase1():
    """The following works for numpy version < 1.24.0"""
    print("\nShowcase1")
    arr = np.array([[1., 2., 3., 4.], [5., 6., 7., 8.]])
    arr = np.ma.masked_where(arr == 7., arr)

    val = np.ma.filled(arr, fill_value=np.nan)
    val = np.array(val, order="F")
    val = np.ma.masked_invalid(val)
    val1d = val.ravel(order="K")

    expect_here = "[1. 5. 2. 6. 3. -- 4. 8.]"
    print("Expected:", expect_here)

    got = str(val1d).replace("0", "")
    print("Got:", got)
    if got == expect_here:
        print("OK for", np.__version__)
    else:
        print("**** Not OK for numpy version", np.__version__)


def showcase2():
    """The following works for numpy version < 1.24.3; fails in 1.24.3"""
    print("\nShowcase2")
    arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

    # pure numpy ok here
    print("-- pure numpy")
    arrdata_pure_np = np.array(arr, order="F")
    val = np.array(arrdata_pure_np)
    val1d = val.ravel(order="K")
    print("Expected val1d is [1 5 2 6 3 7 4 8]")
    print("Numpy val1d is", str(val1d))
    assert str(val1d) == "[1 5 2 6 3 7 4 8]", "Pure numpy"

    # numpy masked goes wrong for numpy 1.24.3
    print("-- numpy masked")
    arr = np.ma.masked_where(arr == 7, arr)
    arrdata_ma = np.array(arr.data, order="F")
    arrmask_ma = np.array(arr.mask, order="F")
    val = np.ma.array(arrdata_ma, mask=arrmask_ma)
    val1d = val.ravel(order="K")
    print("Expected val1d is [1 5 2 6 3 -- 4 8]")
    print("Numpy masked val1d is", str(val1d))
    ok = str(val1d) == "[1 5 2 6 3 -- 4 8]"
    if ok:
        print("OK for numpy version", np.__version__)
    else:
        print("**** NOT OK for numpy version", np.__version__)


def main():
    showcase1()
    showcase2()

if __name__ == "__main__":
    main()
```

### Error message:

```shell
## Numpy version < 1.24:
Using numpy 1.19.1

Showcase1
Expected: [1. 5. 2. 6. 3. -- 4. 8.]
Got: [1. 5. 2. 6. 3. -- 4. 8.]
OK for 1.19.1

Showcase2
-- pure numpy
Expected val1d is [1 5 2 6 3 7 4 8]
Numpy val1d is [1 5 2 6 3 7 4 8]
-- numpy masked
Expected val1d is [1 5 2 6 3 -- 4 8]
Numpy masked val1d is [1 5 2 6 3 -- 4 8]
OK for numpy version 1.19.1


## Numpy version 1.24.1:
Using numpy 1.24.1

Showcase1
Expected: [1. 5. 2. 6. 3. -- 4. 8.]
Got: [1. 5. 2. 6. 3. nan -- 8.]
**** Not OK for numpy version 1.24.1

Showcase2
-- pure numpy
Expected val1d is [1 5 2 6 3 7 4 8]
Numpy val1d is [1 5 2 6 3 7 4 8]
-- numpy masked
Expected val1d is [1 5 2 6 3 -- 4 8]
Numpy masked val1d is [1 5 2 6 3 -- 4 8]
OK for numpy version 1.24.1


## Numpy version 1.24.3
Using numpy 1.24.3

Showcase1
Expected: [1. 5. 2. 6. 3. -- 4. 8.]
Got: [1. 2. 3. 4. 5. 6. -- 8.]
**** Not OK for numpy version 1.24.3

Showcase2
-- pure numpy
Expected val1d is [1 5 2 6 3 7 4 8]
Numpy val1d is [1 5 2 6 3 7 4 8]
-- numpy masked
Expected val1d is [1 5 2 6 3 -- 4 8]
Numpy masked val1d is [1 2 3 4 5 6 -- 8]
**** NOT OK for numpy version 1.24.3
```

### Runtime information:

See code above

### Context for the issue:

Makes https://github.com/equinor/xtgeo tests fail.

**Comment by mattip** [comment]
I think the problem is that "K" is not handled properly. If the call is `val.ravel("F")` then the 1d array is ordered as expected. The problem is that `np.all(val.ravel("F") != val.ravel("K"))` when `val.flags.f_contiguous is True`

**Comment by mattip** [comment]
Actually, the comment at the top of #23626 (where this was touched) remark that "K" and "A" are not handled correctly. @seberg thoughts?

**Comment by jcrivenaes** [comment]
> I assume you guys don't rely on `"K"` doing the "right" thing? (I am surprised you would use it for more than "do the fastest thing", i.e. I understand test failures, but assume probably that it doesn't lead to actual production errors?)
> 
We do have failures in our production code (xtgeo) also with numpy 1.24.3. 
> Because mask and values don't have to have the same memory order, so `"K"` is really not well defined and we would have to do more work to define it.

Thanks for the info, I was not aware of that (mask vs. values order).

**Comment by seberg** [comment]
Hmmm, it's still not clear to me how you use it that the order is actually important for you?  And how broadly you want to preserve memory order.

**Comment by mattip** [comment]
In the examples, `val._data` is F ordered, while `val._mask` is C ordered. So I guess we used to give precedence to the data order when they conflict and val.ravel("K") is used. Maybe `ravel` should use the `_data` order but emit a new warning in this case?

**Comment by mattip** [comment]
> Of course that pick is exactly reversed now due to the error

Would fixing that error make the cases at the top of the issue pass? If so that is probably good enough.

**Comment by seberg** [comment]
yes

**Comment by jcrivenaes** [comment]
> Hmmm, it's still not clear to me how you use it that the order is actually important for you? And how broadly you want to preserve memory order.

The library (xtgeo) has a built-in C integration (via SWIG) where array memory order is important when exchanging arrays from numpy to C or vice versa. The library reads and writes many alien file formats via C, where some are C ordered 2D or 3D numpy (masked) arrays, other are F ordered. I am sure it is possible to improve our code to make it more robust. However it did work well prior to numpy version 1.24.
