### ISSUE TITLE
BUG: 'invalid value encountered in multiply' in 'isclose'

### ISSUE THREAD

**Issue by axil** [numpy/numpy#23669]
### Describe the issue:

Running `isclose` against a complex ndarray issues a runtime warning (though the answer is correct).

### Reproduce the code example:

```python
>>> import numpy as np
>>> np.isclose(np.array([1j, np.inf]), 0.)
...\lib\site-packages\numpy\core\numeric.py:2382: RuntimeWarning: invalid value encountered in multiply
  x = x * ones_like(cond)
array([False, False])
```
```


### Error message:

_No response_

### Runtime information:

1.24.3
3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]

No need to run print, `show_runtime()` already writes to stdout.

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\<username>\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 4,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

### Context for the issue:

It interferes with the results of my regression tests.

**Comment by mac-lawson** [comment]
I'm drafting a possible fix for this that would involve the explicitly handling the case of complex numbers when isclose is called. It checks if either input is a complex object, and separately checks the equality of the real and imaginary components using isclose.

**Comment by axil** [comment]
@mac-lawson Actually, the answer is correct. It is just the warning that needs to be debugged. I've updated the text of the issue to avoid the ambiguity.

**Comment by axil** [comment]
@anshuman0123 The issue is still open. The original text did not include the result of the function. I've added the result.

The problem is not with the result but with the warning. Potentially, debugging the warning could lead to deeper problems.

**Comment by mac-lawson** [comment]
@axil You probably already know this but if you want to suppress the warning messages without modifying the behavior of your tests, you can set the error-handling mode to 'ignore' for the duration of your tests, and then return it to its previous value once the tests are completed. You could use the numpy.errstate() context manager.

**Comment by axil** [comment]
@mac-lawson Thank you for the clue. Yes, I'm aware of that, and that's what I'll most probably end up with. 

Sometimes it so happens that when debugging an innocent warning, something serious gets revealed.  That was my primary concern here. If someone has a quick glance at the line of the C code in question and confirms there is nothing serious there, that would probably be enough for this issue.

**Comment by seberg** [comment]
At some point in the past year, an `np.errstate()` was called `iclose`, so this is fixed.
