### ISSUE TITLE
BUG: Can't disable veclib in NumPy builds

### ISSUE THREAD

**Issue by xor2k** [numpy/numpy#23667]
### Describe the issue:

I've tried to build Numpy without Blas, Lapack and Atlas on an Apple M1 (MacOS). According to

https://numpy.org/devdocs/user/building.html#disabling-atlas-and-other-accelerated-libraries

this can be done with
```
NPY_BLAS_ORDER= NPY_LAPACK_ORDER= python setup.py build
```
or
```
BLAS=None LAPACK=None ATLAS=None python setup.py build
```
Neither of both commands however prevent veclib from being linked into NumPy at compile time, as
```
import numpy as np
np.show_config()
```
shows
```
...
accelerate_info:
    extra_compile_args = ['-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
blas_opt_info:
    extra_compile_args = ['-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
...
```

### Reproduce the code example:

```python
## Inspired by https://gist.github.com/MarkDana/a9481b8134cf38a556cf23e1e815dafb#ii-install-numpy-with-blas-interface-specified-as-veclib
#
## install NumPy build dependencies, e.g. by
# 
# mamba create -n np_veclib cython pybind11
# conda activate np_veclib
#
## then run
#
# git clone https://github.com/numpy/numpy
# cd numpy
# git submodule update --init
#
## then run
#
# NPY_BLAS_ORDER= NPY_LAPACK_ORDER= python setup.py build
#
## or alternatively
#
# BLAS=None LAPACK=None ATLAS=None python setup.py build
#
## Install NumPy from the current directory
#
# pip install -e .
#
## Finally, run the following Python code

import numpy as np
np.show_config()
```

### Error message:

```shell
Unexpected behaviour as mentioned above
```

### Runtime information:

```
1.25.0.dev0+1256.g5665fdcdf
3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.0.dev0+1256.g5665fdcdf',
  'python': '3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) '
            '[Clang 14.0.6 ]',
  'uname': uname_result(system='Darwin', node='Michaels-Air', release='22.4.0', version='Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}}]
```

**Comment by seberg** [comment]
Please check what `np.show_runtime()`, `np.show_config()` what happens if you would compile fresh, its isn't very reliable.

**Comment by mattip** [comment]
Note that `np.show_runtime()` will show the runtime BLAS alternative actually used only if you `pip install threadpoolctl`. 

I think @seberg's comment about "what happens if you would compile fresh" relates to `np.show_config()`, not to `np.show_runtime()`.

**Comment by xor2k** [comment]
Okay, now it looks good, the line
```
pip install -e .
```
was the problem. It seems to not reuse what `python setup.py build` has already build. I think that's what you meant with "fresh" @seberg, right?

What also works is
```
NPY_BLAS_ORDER= NPY_LAPACK_ORDER= pip install -e .
```
What definitely does not work is importing from the NumPy source directory. So I definitely need to install Numpy to use it in some non-Numpy Python program.

Would this maybe worth a small documentation update? E.g. in https://numpy.org/devdocs/user/building.html#disabling-atlas-and-other-accelerated-libraries

**Comment by rgommers** [comment]
Those docs are all going away soon (as is `NPY_BLAS_ORDER` and every other numpy-specific env var, after we completed our switch to Meson), so I suggest to just close this.

**Comment by mattip** [comment]
Labeled as "distutils". Thanks for the report, closing as "won't fix"
