### ISSUE TITLE
DOC: Indexing of vectors a and b wrong in numpy.outer function documentation

### ISSUE THREAD

**Issue by polarboar** [numpy/numpy#23664]
### Issue with current documentation:

Current documentation says

"Given two vectors, a = [a0, a1, ..., aM] and b = [b0, b1, ..., bN], the outer product [1] is:"

### Idea or request for content:

The arrays should start at a1 and b1 or end at aM-1 and bN-1 given that their lengths are M and N.

**Comment by anshuman0123** [comment]
hey , assign me this issue

**Comment by InessaPawson** [comment]
@anshuman0123 NumPy doesn't assign issues. Just dive right in! No permission needed. To let everyone know that there is work in progress, link your PR to this issue. (If needed, refer to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) on how to do it.)

**Comment by polarboar** [comment]
The array [0,1,2...,M] has M+1 elements.
The array [1,2,3...,M] has M elements
The array [0,1,2...,M-1] has M elements.
I'm thinking of similar indexing for the documentation (unless I'm missing something here).

**Comment by Mukulikaa** [comment]
@polarboar, technically the sizes of the vectors are not mentioned so I think it should be fine.

**Comment by rossbar** [comment]
I think there is ambiguity here as `M` and `N` are used both as the length of the vectors (see e.g. the parameter descriptions) and the indices in the example matrix in the extended summary. I'd recommend modifying the "index" subscripts in the matrix example to use `M-1` and `N-1`.
