### ISSUE TITLE
BUG: Histogram value overflow when dtype of weights is integer of smaller size

### ISSUE THREAD

**Issue by AlkaidCheng** [numpy/numpy#23681]
### Describe the issue:

When passing weights to numpy.histogram, if the dtype of weights has a size smaller than the output histogram value, an overflow will happen which gives a gibberish result. A possible solution is to automatically expand the dtype of the output histogram to the appropriate size.

### Reproduce the code example:

```python
import numpy as np
size = 100000
np.random.seed(0)
x = np.random.rand(size)
weights = np.ones(size, dtype='int8')
hist, bin_edges = np.histogram(x, weights=weights, range=(0, 1), bins=20)

# this gives hist = 
# array([ 100,    5,  -28,  122,  -89,   51, -114,    0,  -92,  -76,  127,
#         -8,   29,   64,  -96,   92,  -22,   54,  -78,  119], dtype=int8)
```

### Runtime information:

Numpy 1.23.3

**Comment by mac-lawson** [comment]
It would be useful to automatically expand the dtype of the output histogram to the appropriate size when passing weights to histogram. #16616 is similar.

**Comment by DuanBoomer** [comment]
Can I work on this issue of no one else is working?
If someone else is already working,
Can we co-solve this issue together?
You can contact me at chiarg1292003@gmail.com

**Comment by mattip** [comment]
Hmm. Are these last comments generated by some AI or actual humans?

**Comment by hmeine** [comment]
I just ran into the very same problem and wanted to file an issue as well; from my POV, a quick improvement would be to at least **document that the resulting accumulator dtype depends on the weights dtype**. This is not at all obvious, and the documentation currently does not state anything about dtypes. When *not* using weights, the dtype is chosen somehow appropriately, but when using weights, it suddenly becomes exactly the dtype of the weights. (My workaround is now to promote the weights before calling `np.histogram()`.
