### ISSUE TITLE
BUG: .tobytes() produces random results

### ISSUE THREAD

**Issue by buhbuhtig** [numpy/numpy#23703]
### Describe the issue:

Working with pandas I was surprised to find that pandas.DataFrame.values.tobytes() produces an unstable (random) result. Then, I was able to localise the problem to the following example: 

Code:
```
arr    =   np.array([['MSFT_2022-01-01', 19980220]], dtype=object)
arr_same = np.array([['MSFT_2022-01-01', 19980220]], dtype=object)
print(        (arr  == arr_same).all() )
print(arr.tobytes() == arr_same.tobytes() )
```
Output:
--->True
!!-->**False**

I'm guessing (not sure) that the output array of bytes contains chunks of memory with random data because of the string type. Is this behaviour by design or is it a bug?

### Reproduce the code example:

```python
import numpy as np
arr      = np.array([['MSFT_2022-01-01', 19980220]], dtype=object)
arr_same = np.array([['MSFT_2022-01-01', 19980220]], dtype=object)
print( (arr == arr_same).all() )
print(arr.tobytes() == arr_same.tobytes() )
```

### Runtime information:

1.21.6
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]

**Comment by rkern** [comment]
The bytes that `dtype=object` arrays actually store are the actual `PyObject *` pointers to the objects. They are memory addresses and are not expected to be related to the value.
