### ISSUE TITLE
DEP: stop building and testing 32-bit windows

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23717]
See the discussion at https://discuss.python.org/t/dropping-32-bit-packages

The builds are difficult to maintain, suffer bit rot, and are not popular.

Another option is to stop testing f2py on this platform, which is the reason we try to install a fortran compiler. ~Building NumPy does not require the fortran compiler, it is only for tests.~ 

Edit: not true, wrapping the OpenBLAS library does require the fortran runtime.

**Comment by carlkl** [comment]
Just to mention one example: Aren't there still a relevant number of users who use python/numpy in together with excel, i.e. pyxll?  MS Office 32-bit is still a thing today in many scenarios, despite the fat that if it is no longer the default version during installing for some time now. 32-bit applications are sunsetting now on Windows, this is obvious. But 32-bit support on Windows may be necessary for some time in the future for those who can't switch to 64-bit. And there is no long term support for any version of python / numpy.

**Comment by charris** [comment]
Looks like Intel is thinking of dropping 32 bit hardware support in the future: https://www.tomshardware.com/news/intel-ponders-transition-to-64-bit-only-x86s-architecture .

**Comment by lithomas1** [comment]
Any idea if/how this would affect people on WASM/pyodide?

**Comment by rgommers** [comment]
> Any idea if/how this would affect people on WASM/pyodide?

It shouldn't, we have a CI job for Pyodide/Emscriptem and that will continue to work: https://github.com/numpy/numpy/blob/main/.github/workflows/emscripten.yml. I'd expect support for WASM and Pyodide to continue to mature.

**Comment by lithomas1** [comment]
I thought WASM is 32-bit for now, maybe I'm understanding what the memory64 proposal(https://github.com/WebAssembly/memory64) is supposed to mean?

**Comment by rgommers** [comment]
Sure, but no one is planning on actively breaking all 32-bit builds I believe. We just need a single CI job that tests that we don't accidentally introduce 64-bit-only things and break 32-bit builds. Users or redistributors may still choose to build them, and this proposal moves 32-bit Windows into the same category as 32-bit Linux on armv7 (Raspberry Pi & co), and some other niche use cases.

@mattip I think your issue description is perhaps a little misleading, in particular to link to your Discourse post from 3 years ago. As I understand it, it is specific to reducing the support status (and our corresponding burden) for 32-bit Windows only. All 32-bit platforms are then supported only on a best-effort basis, we don't create binaries for them but will take patches if they're contributed for a specific platform.

**Comment by mattip** [comment]
Yes, that is correct. CPython has a concept of [support tiers](https://peps.python.org/pep-0011/#support-tiers). I propose moving 32-bit windows from Tier 1 to "other platforms". Perhaps we should have our own page of tiered support.

**Comment by seberg** [comment]
Just to say :+1: if win32 wheels/CI is making trouble (and it seems to be the case right now), there seems to be little reason to not just drop it for now.

(And yes, we still will have 32bit support with CI, just not testing it explicitly for windows, so in an "other platforms" support tier.)

**Comment by charris** [comment]
Note that there are no 32 windows wheels in the 1.26.0b1 release. Do we want them?

**Comment by charris** [comment]
@rgommers Sounds good.

**Comment by pllim** [comment]
Hello! @ngoldbaum pointed me here when I failed to find a win32 wheel for numpy 1.26b. Would be nice if it can be tested downstream before the final release.

xref https://github.com/astropy/astropy/pull/14784 and https://github.com/liberfa/pyerfa/pull/111

**Comment by rgommers** [comment]
With gh-24671 we should get 32-bit wheels back.
