### ISSUE TITLE
Error importing numpy 1.24.3 on windows 7 32 bit

### ISSUE THREAD

**Issue by dabl03** [numpy/numpy#23731]
### Steps to reproduce:

Install numpy:

```bash
C:\> pip install numpy
```

Then I import it:

```python
import numpy
```

Doing so closes the program:

![Captura](https://user-images.githubusercontent.com/66857879/236686585-482b5cbb-2af8-493c-8946-d866eaf162fd.PNG)

### Additional information:

_python version: 3.8_

**Comment by dabl03** [comment]
I solved it using an older version of numpy: v1.23.0:

`pip install --force-reinstall numpy==1.23.0`

**Comment by mattip** [comment]
What system are you running this on? Perhaps this is a virtual machine or a very old CPU that does not support SSE3?

**Comment by dabl03** [comment]
> What system are you running this on? Perhaps this is a virtual machine or a very old CPU that does not support SSE3?

I run it on a windows 7 32 bit operating system on an intel Pentium cpu. You can get it on the Dell page as optiplex 380.

**Comment by charris** [comment]
We are now building wheels with msvc 2019 and the associated library. Did earlier wheels work? If so, for what version did things change.

**Comment by dabl03** [comment]
> We are now building wheels with msvc 2019 and the associated library. Did earlier wheels work? If so, for what version did things change.

If you want, I'll try to compile it with MS build 2017 and see how it turns out, but I'm a bit of a beginner in c/c++ and I don't know anything about cpython

**Comment by mattip** [comment]
> If you want,

I think supporting lastes NumPy versions on Windows 7, 32-bit, on a Pentium CPU is a bit of a stretch for us. The easiest path forward is for you to continue to use NumPy 1.23, or to find a more modern machine and operating system.

**Comment by dabl03** [comment]
> I think supporting latest NumPy versions on Windows 7, 32-bit, on a Pentium CPU is a bit of a stretch for us. The easiest path forward is for you to continue to use NumPy 1.23, or to find a more modern machine and operating system.

Yes, that was the idea of my answer. I won't be able to use a new feature, but that's the problem of using very outdated PCs or with an outdated OS.

I didn't close this thread to see if there is a better solution.

Thank you mattip and @charris

**Comment by rgommers** [comment]
I don't think there is a better solution here than using an older NumPy release or upgrading to more modern hardware. So I'll close this issue. Thanks all!
