### ISSUE TITLE
DOC: Broken link to "PDF Version"

### ISSUE THREAD

**Issue by partev** [numpy/numpy#23732]
### Issue with current documentation:

1. go to the NumPy documentation page here: https://numpy.org/doc/stable/index.html
2.  click on the "Download documentation: [PDF Version](https://numpy.org/doc/stable/numpy-user.pdf)" link.
3. get a 404 Page Not Found Error message:

![image](https://user-images.githubusercontent.com/23830955/236711042-053977fd-55fa-4f40-a085-6439a3d1cd47.png)

**Comment by seberg** [comment]
We have stopped building it.  IIRC, the link should simply be deleted.

**Comment by mattip** [comment]
Removing the link is a good idea.

To get the stable version to stop displaying the download link:
- [this line](https://github.com/numpy/numpy/blob/main/doc/source/index.rst?plain=1#L20) needs to be changed. This will fix the problem going forward.
- that change should be backported
- the stable documents need to be rebuilt and uploaded.

**Comment by SkandaPrasad-S** [comment]
Hey everyone! Is anyone working on this? I would be happy to pick it up

**Comment by partev** [comment]
fixed in PR https://github.com/numpy/numpy/issues/23732
