### ISSUE TITLE
ENH: Computing std/var and mean at the same time 

### ISSUE THREAD

**Issue by ancestor-mithril** [numpy/numpy#23741]
### Proposed new feature or change:

Since computing `np.std` and `np.var` requires calculating the mean, a `std_mean` and `std_var` would be useful for providing both statistics at the same time, similar to the PyTorch feature: https://github.com/pytorch/pytorch/issues/4993.

**Comment by RonaldAJ** [comment]
I have a draft implementation here: https://github.com/soundappraisal/numpy/tree/stdmean-dev-001

I am very uncertain about written and unwritten numpy coding conventions, so I am trying to organize some feedback.

**Comment by RonaldAJ** [comment]
Thanks for the encouragement.

I am trying to start a discussion on the mailing list. I also read somewhere in the feedback on a PR that for API changes a discussion is preferred to happen before a PR.

**Comment by RonaldAJ** [comment]
[Mailing list item](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/TJI6AKD2NT7XSBJTGGJXAQPPLBKGX3XN/)
