### ISSUE TITLE
BUG: numpy segfaults on import with current CPython main

### ISSUE THREAD

**Issue by tacaswell** [numpy/numpy#23766]
### Describe the issue:

numpy segfaults on import with current CPython main.

### Reproduce the code example:

```python
import numpy as np
```

### Error message:

```shell
$ python
Python 3.12.0a7+ (heads/main:46f1c78eeb, May 13 2023, 16:09:15) [GCC 13.1.1 20230429] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np

Segmentation fault (core dumped)
```

### Runtime information:

Due to segfault on import can not get this 🤣 

I can reproduce this with the ~current main branch of numpy + current cython master branch or with the lastest stable cython (0.29.31) + numpy (1.24.x) from pypi.

discovered via https://github.com/tacaswell/build_the_world 

### Context for the issue:

I bisected this back to

```
$ git bisect bad
de64e7561680fdc5358001e9488091e75d4174a3 is the first bad commit
commit de64e7561680fdc5358001e9488091e75d4174a3
Author: Eric Snow <ericsnowcurrently@gmail.com>
Date:   Tue May 2 21:30:03 2023 -0600

    gh-94673: More Per-Interpreter Fields for Builtin Static Types (gh-103912)

    his involves moving tp_dict, tp_bases, and tp_mro to PyInterpreterState, in the same way we did for tp_subclasses.  Those three fields are effectively const for builtin static types (unlike tp_subclasses).  In theory we only need to make their values immortal, along with their contents.  However, that isn't such a simple proposition.  (See gh-103823.)  In the meantime the simplest solution is to move the fields into the interpreter.

    One alternative is to statically allocate the values, but that's its own can of worms.

 Include/internal/pycore_typeobject.h |   7 ++
 Modules/_abc.c                       |   1 +
 Modules/gcmodule.c                   |  31 +----
 Objects/structseq.c                  |   9 +-
 Objects/typeobject.c                 | 223 +++++++++++++++++++++++++++--------
 5 files changed, 185 insertions(+), 86 deletions(-)

```

which came in via https://github.com/python/cpython/pull/103912

**Comment by rgommers** [comment]
Cc @lysnikolaou and @mattip - this is interesting timing, after our discussion a few days ago on NumPy needing updates for CPython changes related to immortal objects. @lysnikolaou maybe this is a good place to start digging in?

**Comment by charris** [comment]
Hmm, if it is new in Python 3.12 we don't need to fix 1.24.x. Which is good :)

**Comment by mattip** [comment]
I am seeing a failed assert in released cython 0.29.3x [here](https://github.com/cython/cython/blob/663c924462adec202c9f469fa346bda1b2264dfa/Cython/Utility/TypeConversion.c#L1047) but that has been fixed on cython master to avoid that path for python>=3.12a7. 

On cython master, compilation fails. In [`__Pyx_PyThreadState_Current`](https://github.com/cython/cython/blob/f797c86c31f4bceabb386278f0d1686cb218da9b/Cython/Utility/ObjectHandling.c#L248) the `tstate` fields used no longer exist in [the struct](https://github.com/python/cpython/blob/dce2d38cb04b541bad477ccc1040a68fa70a9a69/Include/cpython/pystate.h#L118) on CPython 3.12.0a7.

I am curious how you got a build to work with cython master.

**Comment by tacaswell** [comment]
I have `-DCYTHON_FAST_THREAD_STATE=0` in my CFLAGS

```
    CFLAGS = (" -Wall -O2 -pipe -fomit-frame-pointer  "
              "-fno-strict-aliasing -Wmaybe-uninitialized  "
              "-Wdeprecated-declarations -Wimplicit-function-declaration  "
              "-march=native -DCYTHON_FAST_THREAD_STATE=0")
```

is the full set of cflags I am building with.  I'm also going thourgh distutils (changing to meson is on my todo list).

**Comment by mattip** [comment]
Thanks

**Comment by scoder** [comment]
> I am seeing a failed assert in released cython 0.29.3x [here](https://github.com/cython/cython/blob/663c924462adec202c9f469fa346bda1b2264dfa/Cython/Utility/TypeConversion.c#L1047) but that has been fixed on cython master to avoid that path for python>=3.12a7.

I just copied that change to Cython 0.29.x in https://github.com/cython/cython/commit/8af954f812f78d5258cb8440b13cc6944eccf940. It will be included in 0.29.35.

**Comment by lysnikolaou** [comment]
I looked into this after building with CPython and Cython main. This looks like a bug in CPython, but I'm not sure about it. I've opened an issue on python/cpython#104614 with more info about the code path that fails, in order to discuss what the correct way forward is.

**Comment by lysnikolaou** [comment]
Brief status update on this: The issue will be fixed upstream in CPython and will be part of beta2, expected early next week.

**Comment by tacaswell** [comment]
I can confirm I was able to build basically everything in the scipy stack from that PR branch (modulo some cython issues that are unrelated).

**Comment by tacaswell** [comment]
This is resolved upstream, closing.
