### ISSUE TITLE
BUG: Intel MKL Warning with Numpy Import

### ISSUE THREAD

**Issue by jlandgre** [numpy/numpy#23775]
### Describe the issue:

When importing Numpy or Pandas in a Python 3.11.3 Conda environment, I see (two, duplicates of the warning message listed below in "Error message" inputbox:

I can't find MKL documentation explaining this warning.

The messages are not suppressible with warnings.filterwarnings('ignore')

Expected Behavior is that Deprecation warning messages can be suppressed and that messages explain possible remediation actions by user (e.g. install a different version of package xyz etc.)

### Reproduce the code example:

```python
import numpy as np
```

### Error message:

```shell
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
```

### Runtime information:

Output of:
print(np.__version__)
print(sys.version)
print(np.show_runtime())

1.24.3
3.11.3 (main, Apr 19 2023, 18:51:09) [Clang 14.0.6 ]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3', 'SSE41', 'POPCNT', 'SSE42'],
                      'not_found': ['AVX',
                                    'F16C',
                                    'FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

### Context for the issue:

This creates a poor UI when working with both Numpy and Pandas.

**Comment by charris** [comment]
I suspect that warning message is written directly to stderr or stdout by the Intel library. We don't have control over that.

**Comment by jlandgre** [comment]
Hmm. Appreciate advice on how to suppress (and/or get to root cause understanding).  I tried redirecting the error outputs to log files (not sure if I did correctly). That does not affect occurrence of the warnings. Is there another/better way to redirect or suppress such messages? Certainly, this doesn't reflect well on Numpy package UI even if Intel is root cause!

Here is what I tried as unsuccessful workaround
import sys, os
sys.stderr = open("stderr.log", "w")
sys.stdout = open("stdout.log", "w")

import numpy as np

**Comment by rgommers** [comment]
There's nothing that NumPy can do about this indeed. The warning probably is valid, I assume you're on a machine with a CPU which does not support AVX instructions, meaning a future update will stop working.

MKL is not a Python library, so no usage of the `warnings` or `sys` module is going to help you here. You can open a post on the Intel support forum, but my expectation is that they won't do anything with it. You can use an older MKL version for now, or live with the warning, or upgrade your CPU - I don't see other options.

**Comment by jlandgre** [comment]
ok. fair enough. Thanks for laying out the boundaries and good to confirm that it's futile to try suppressing the message. Is it feasible to downgrade MKL without breaking Numpy 1.24 compatibility?  If so, what MKL version would you suggest? I am not familiar with how this interrelationship works, so please excuse if dumb question! 

Pandas 2.0.1 brought Numpy 1.24.3 brought MKL 2023.1.0 in Conda from $conda install -c conda-forge pandas=2.0.1

(BTW, I am working on latest MBP so it's hardly a fringe CPU --M1 Max processor).

**Comment by rgommers** [comment]
> Is it feasible to downgrade MKL without breaking Numpy 1.24 compatibility? If so, what MKL version would you suggest?

It depends. NumPy works fine with older MKL in principle, however if the metadata for the package in the conda `defaults` channel explicitly uses a constraight on >=2023.1.0 then that may be due to how the Anaconda folks built NumPy and `conda` may refuse to go to an older MKL version.

> (BTW, I am working on latest MBP so it's hardly a fringe CPU --M1 Max processor).

Then the error message MKL emits is bogus, because you're not on an Intel CPU (both SSE and AVX are Intel-specific). The reason for that is that MKL only supports Intel hardware: https://www.intel.com/content/www/us/en/developer/articles/system-requirements/oneapi-math-kernel-library-system-requirements.html. Hence the packaging in conda defaults is just wrong, and it causes you to run MKL under Rosetta emulation.

I'd open a new issue on https://github.com/ContinuumIO/anaconda-issues. The `conda-forge` channel gets this right, and won't default to MKL anyway.

**Comment by jlandgre** [comment]
Thanks so much for the guidance and info Ralf

**Comment by AndroidSheepy** [comment]
I met the same issue in arm mac, thanks for the helpful advice XD.

**Comment by DanRunfola** [comment]
Just wanted to flag that someone did raise this over on the anaconda issues page:
https://github.com/ContinuumIO/anaconda-issues/issues/13236

**Comment by annieco29** [comment]
> Just wanted to flag that someone did raise this over on the anaconda issues page: [ContinuumIO/anaconda-issues#13236](https://github.com/ContinuumIO/anaconda-issues/issues/13236)

This post helped me solve the issue!

**Comment by edgar-bonet** [comment]
I found a workaround [posted on an intel forum][1]:

```shell
export MKL_ENABLE_INSTRUCTIONS=SSE4_2
```
[1]: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/CPU-Deprecation-Warning/m-p/1549616/highlight/true#M35531
