### ISSUE TITLE
BUG: Array cannot handle big numbers

### ISSUE THREAD

**Issue by abetatos** [numpy/numpy#23784]
### Describe the issue:

I have a big array of shape (1, 18677, 27066) if I try to set the values of a masking to a great number it ignores and sets a "random" value between 170 - 244
![image](https://github.com/numpy/numpy/assets/76526314/0eeb2a51-c483-4d52-b511-7a67fa1c80f0)
![image](https://github.com/numpy/numpy/assets/76526314/1dce3459-af55-4bc7-b43b-57b67dc8eb77)

Masking is a ones_like(array) array. I have tried increasing values 1 at a time in order to see what happens:
![image](https://github.com/numpy/numpy/assets/76526314/58e83b85-91e7-4e65-8d5d-880e68336beb)
It suddently drops to 0!

Could it raise some errors instead of setting random values?

Python version: 3.10.11
Numpy: I tried with two versions: '1.23.5' and '1.24.3'
System: Ubuntu Ubuntu 22.04.2 LTS

The problem is with the dtype: 
![image](https://github.com/numpy/numpy/assets/76526314/d7d02fa7-80b2-43c1-818a-ac15f05a5f19)
For object or int32:
![image](https://github.com/numpy/numpy/assets/76526314/83891d92-cb1a-4b82-a84b-ea429d43b2e3)

I don't know if this is an expected behaviour due to precision but I prefered to comment the issue. 

Thank you!

### Reproduce the code example:

```python
import numpy as np

a = np.ones((1, 18677, 27066), dtype="object")
a[a==1] = 1000
a
```

### Runtime information:

import sys, numpy
print(numpy.__version__)
print(sys.version)
1.23.5
3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]

Numpy: I tried with two versions: '1.23.5' and '1.24.3'
System: Ubuntu Ubuntu 22.04.2 LTS

### Context for the issue:

It is for a masters degree thesis but I have it controlled changing the dtype, not priority for me but maybe induces some errors.

**Comment by rkern** [comment]
`dtype=np.uint8` can only represent numbers from 0 to 255, unsigned 8-bit integers. Integers outside of that range use "clock arithmetic" to find a value in that range. So `-9999` becomes `(-9999) % 256 = 241`. This is a long-standing design decision that we are comfortable with.
