### ISSUE TITLE
DOC: Source of "generally defined" function in numpy.correlate needs to be made clear to user

### ISSUE THREAD

**Issue by aliphys** [numpy/numpy#23782]
### Issue with current documentation:

In the [Numpy.correlate documentation](https://numpy.org/doc/stable/reference/generated/numpy.correlate.html), we state that the function used for cross-correlating two single dimensional vectors is ' generally defined in signal processing texts':

https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/core/numeric.py#L682-L686

Furthermore, another formula is also mentioned in the Notes section:
https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/core/numeric.py#L712-L719

This creates two issues:
1. It is not clear which formula is used by NumPy in the numpy.correlate function
2. To someone less experienced in this signal analysis, this can look confusing. Please note that NumPy (thanks to its low barrier of entry) may be the first exposure to this mathematical expression. 

### Idea or request for content:

The documentation is improved by these two steps:

1.  The formula/algorithm used in numpy.correlate is clarified. If two formula are considered mathematically/computationally equivalent, this is stated clearly 
2. Adding a source for the function mentioned. As an example, we can see this done in [numpy.outer](https://numpy.org/doc/stable/reference/generated/numpy.outer.html).
     - https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/core/numeric.py#L865
     - https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/core/numeric.py#L900-L904

**Comment by ztzhu1** [comment]
@aliphys Hi. I have experience with NumPy and signal analysis, but it's my first open source contribution. Can I work on this issue?

**Comment by aliphys** [comment]
Great! I'm note a maintainer of NumPy, but I'd be happy to give feedback on your PR. 😊

**Comment by DhavalParmar61** [comment]
I think documentation is proper here implementation is based on the formula mentioned in the definition. In note, the alternate formula is mentioned and also its relation with numpy implementation (in case you want to follow that formula).

**Comment by ztzhu1** [comment]
> I think documentation is proper here implementation is based on the formula mentioned in the definition. In note, the alternate formula is mentioned and also its relation with numpy implementation (in case you want to follow that formula).

That's right! The two formulas are equivalent. 😃

**Comment by aliphys** [comment]
@DhavalParmar61 I do not infer that the two formulas are mathematicall & computationally equivalent from the documentation given the phrase `sometimes correlation may be defined differently`. 
https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/core/numeric.py#L714-L716

As an example, box and cube counting differ both in the mathematical and computational definition, leading to different outcomes. Even though both are valid approaches to calculating the fractal dimension.

**Comment by Mukulikaa** [comment]
I am +1 on adding sources for the formulae and clarifying if they are computationally equivalent.

**Comment by ellaella12** [comment]
hi @ztzhu1, will you still be working on this ticket? if not, i'd like to give a go

**Comment by ztzhu1** [comment]
> hi @ztzhu1, will you still be working on this ticket? if not, i'd like to give a go

Sorry, I'm trapped in my job recently. Please go ahead! ☺️

**Comment by rossbar** [comment]
> This creates two issues:
>  1. It is not clear which formula is used by NumPy in the numpy.correlate function

IMO it's quite clear that the first formula is the one that is used in the implementation. The wording is clear that the Notes is there to clarify for those who may have been expecting a different definition. Of course, "clarity" is subjective, so YMMV!

In any case - the first place I'd look for wording suggestions is the `scipy.signal.correlate` docstring. Perhaps the presentation there is more clear and relevant pieces can be borrowed if so.

**Comment by mattip** [comment]
I think we should close this issue and the accompanying pull request. So far we have one strong advocate for any problem existing, and I add my vote to Ross that the current documentation is sufficient and that the suggestions so far only reduce clarity. @Mukulikaa does PR #24100 move closer to your line of thought?

**Comment by Mukulikaa** [comment]
I only feel strongly about adding the reference- I think it adds more context to the formulae we have mentioned. The other changes in text don't make it better than what we have now so we can just keep it as it is.

**Comment by ellaella12** [comment]
Hi I have changed the branch to only add wikipedia reference to the 2 functions. When you have time, may I request for some help reviewing it? Thank you!
