### ISSUE TITLE
Reinstalling numpy in Abaqus failed with no clue

### ISSUE THREAD

**Issue by drunkwcodes** [numpy/numpy#23788]
### Steps to reproduce:

I accidentally used `ensurepip` in abaqus and `pip install -U numpy` failed while deleting old version (`1.15.4`) and installing new version.

Therefore I copied numpy manually in site-package into the abaqus' site-package. But the ImportError remains despite that the module isn't missing in the folder.

<img width="734" alt="numpy_import_error" src="https://github.com/numpy/numpy/assets/36228443/89f1dd52-4ba6-49ad-b58a-52d6ea9d41fd">

### Error message:

```shell
ImportError: numpy.core.multiarray failed to import
Abaqus Error: Abaqus/CAE Kernel exited with an error.
```

**Comment by mattip** [comment]
1. What is abaqus?
2. In general, you cannot simply copy files form one site-package to another. The versions of python must be the same, as well all the system libraries. Where did you copy the site-package from? 
3. If `pip install` failed there might be bigger problems. What was the error?

**Comment by drunkwcodes** [comment]
@mattip 

1. Abaqus is a simulation software. https://www.3ds.com/products-services/simulia/products/abaqus/abaquscae/

2. I used numpy in python 2.7 site-package. Same as abaqus python.
3. It's a write error in multiarray.py.

I copied the numpy from colleague, the issue is mitigated.
