### ISSUE TITLE
BUG: <ValueError: object __array__ method not producing an array 'BUG: ' prefix>

### ISSUE THREAD

**Issue by janipaDev** [numpy/numpy#23791]
### Describe the issue:

This happen after I upgrade numpy to the lastest version.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[19], line 6
      2 dataloader = DataLoader(dataset=kilgariff_data, batch_size=batch_size, shuffle=True)
      4 for data_dict in dataloader:
      5     # Sort indices of data in batch by lengths.
----> 6     sorted_indices = np.array(data_dict['x_len']).argsort()[::-1].tolist()
      7     data_batch = {name:_tensor[sorted_indices]
      8                   for name, _tensor in data_dict.items()}
      9     print(data_batch)

ValueError: object __array__ method not producing an array

### Reproduce the code example:

```python
import numpy as np

for data_dict in dataloader:
    # Sort indices of data in batch by lengths.
    sorted_indices = np.array(data_dict['x_len']).argsort()[::-1].tolist()
    data_batch = {name:_tensor[sorted_indices]
                  for name, _tensor in data_dict.items()}
    print(data_batch)
    break
```

### Error message:

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[19], line 6
      2 dataloader = DataLoader(dataset=kilgariff_data, batch_size=batch_size, shuffle=True)
      4 for data_dict in dataloader:
      5     # Sort indices of data in batch by lengths.
----> 6     sorted_indices = np.array(data_dict['x_len']).argsort()[::-1].tolist()
      7     data_batch = {name:_tensor[sorted_indices]
      8                   for name, _tensor in data_dict.items()}
      9     print(data_batch)

ValueError: object __array__ method not producing an array
```

### Runtime information:

1.24.3
3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]

**Comment by rkern** [comment]
What is the type of the object in `data_dict['x_len']`?

**Comment by seberg** [comment]
Closing for now, since there was no followup on Robert Kern's question.  Whatever the issue, it is very unlikely to be a NumPy issue, but rather a change in whatever `data_dict['x_len']` is, which NumPy has no influence on.

Please follow up with the information on `data_dict['x_len']` and maybe we can reopen or help.

**Comment by clmdy** [comment]
probably because there are two different numpy versions in your environment,you can pip uninstall numpy and pip  show numpy to see whether there are 2 versions,if so,you should uninstall each of them and install what you need again

**Comment by seberg** [comment]
> probably because there are two different numpy versions in your environment

This is a torch (or so) issue, and not NumPy related.  The only thing that might have an effect is if NumPy now trying to pass `copy=True` triggers the issue (new versions of NumPy do this).  But even then it is not a NumPy issue.
