### ISSUE TITLE
BUG: numpy.polydiv function returns wrong result

### ISSUE THREAD

**Issue by sondertg** [numpy/numpy#23798]
### Describe the issue:

When `u` and `v` both equals `[-1, -1]`, the function returns `-0`. It should be `1` as quotient and `[0, 0]` or `[0]` as remainder.

### Reproduce the code example:

```python
import numpy as np

x = np.array([-1.0,-1.0], dtype='float32')
y = np.array([-1.0,-1.0], dtype='float32')

np.polydiv(x, y)
```

### Runtime information:

1.22.4
3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]

### Context for the issue:

Just a simple polynomial division.

**Comment by WarrenWeckesser** [comment]
Here's what I get with the development version of NumPy:
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.25.0.dev0+1513.g1e8b589033'

In [3]: x = np.array([-1.0,-1.0], dtype='float32')

In [4]: y = np.array([-1.0,-1.0], dtype='float32')

In [5]: np.polydiv(x, y)
Out[5]: (array([1.], dtype=float32), array([0.], dtype=float32))

```

**Comment by sondertg** [comment]
So, will be solved in next release. Thanks, closing the issue.

**Comment by dopplershift** [comment]
Just FYI, this works fine for me on 1.24.3, so might be fixed already in a current release.

**Comment by sondertg** [comment]
I got this from google colab. So, their version is an older one. Thanks for the information. :)
