### ISSUE TITLE
DOC: Documentation example should not mention float128

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy#23820]
### Issue with current documentation:

`np.average` docs says:

```
>>> a = np.ones(5, dtype=np.float128)
>>> w = np.ones(5, dtype=np.complex64)
```

The first line is likely to not work in many machine, and generally I've been told float128 should likely never be in docs, maybe using longdouble ?

The file where this is can be found in numpy/lib/function_base.py

### Idea or request for content:

Use example that work on all platforms/installs, or explicitly state otherwise.

**Comment by DhavalParmar61** [comment]
Can we convert float128 to float64?

**Comment by mattip** [comment]
Changing the examples to float64 seems good to me.
