### ISSUE TITLE
BUG: `digitize` returns a value for `nan`

### ISSUE THREAD

**Issue by berossi99** [numpy/numpy#23853]
### Describe the issue:

When passing a `nan` to `np.digitize`, it will be binned as if it belongs to the largest bin. I believe that it should either return `nan` or raise an exception.

### Reproduce the code example:

```python
import numpy as np
print(np.digitize(np.nan, [0]))
# will print "1"
```

### Error message:

No error message

### Runtime information:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.3
3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)]

>>> print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}}]
None
```

### Context for the issue:

I am not sure if this is the intended behavior, but it seems dangerous to return a result for `nan`.

**Comment by rkern** [comment]
No, it will be binned _outside_ of the largest bin, just like any value larger than the largest bin. That's the best "this is a dodgy value" we have available to us, short of just erroring out. It would be good for us to document this explicitly, but I would prefer this behavior to any other.

**Comment by mattip** [comment]
Closing. The [docs for digitize](https://numpy.org/devdocs/reference/generated/numpy.digitize.html#numpy-digitize) open with 
> If values in x are beyond the bounds of bins, 0 or len(bins) is returned as appropriate.

In the example given, the returned value `1` is `len(bins)`. If it were inside the bins, `0` would be returned. Changing this to raise an exception would be an API change.
