### ISSUE TITLE
DOC: Contributing documentation needs tags fetch before install of fork will work

### ISSUE THREAD

**Issue by DaanVanVugt** [numpy/numpy#23869]
### Issue with current documentation:

When following https://numpy.org/doc/stable/dev/index.html#devindex and then trying a `pip install -e .` or a `python setup.py build_ext --inplace -j 4` I get an error:

```bash
python setup.py build_ext --inplace -j 8
Traceback (most recent call last):
  File "/home/.../numpy2/setup.py", line 47, in <module>
    raise RuntimeError(f'Cannot parse version {FULLVERSION}')
RuntimeError: Cannot parse version 0+untagged.32488.g828fba2
```
additionally, I need to initialize the submodules, but this step will be also mentioned in the command output if forgotten. 

https://numpy.org/doc/stable/dev/gitwash/development_setup.html also doesn't show this step

### Idea or request for content:

Add something like

```bash
git fetch upstream --tags
```
or
```bash
git pull upstream main --tags  
```
to the guide.

**Comment by Mukulikaa** [comment]
The latest dev version of the docs has it - https://numpy.org/devdocs/dev/gitwash/development_setup.html#make-the-local-copy.

**Comment by melissawm** [comment]
Should we keep this open until the next release or can we close? The issue would still be findable if the question comes up again...
