### ISSUE TITLE
BUG: [nightly] np.finfo crashes for unhashable input

### ISSUE THREAD

**Issue by jakevdp** [numpy/numpy#23867]
### Describe the issue:

In the nightly release, if an unhashable object is passed to `np.finfo` the result is a `TypeError`. In the most recent numpy release this is fine. This likely regressed in #23088

### Reproduce the code example:

```python
# current NumPy version
import numpy as np

class NonHashableWithDtype:
  __hash__ = None
  dtype = np.dtype('float32')

x = NonHashableWithDtype()

print(np.__version__)  # 1.22.4
print(np.finfo(x).dtype)  # float32
```
```python
# nightly numpy version
import numpy as np

class NonHashableWithDtype:
  __hash__ = None
  dtype = np.dtype('float32')

x = NonHashableWithDtype()

print(np.__version__)  # 1.22.4
print(np.finfo(x).dtype)  # TypeError: unhashable type: 'NonHashableWithDtype'
```

### Error message:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-74122a6c644f> in <cell line: 10>()
      8 
      9 print(np.__version__)  # 1.22.4
---> 10 print(np.finfo(x).dtype)  # float32

/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py in __new__(cls, dtype)
    483 
    484     def __new__(cls, dtype):
--> 485         obj = cls._finfo_cache.get(dtype)  # most common path
    486         if obj is not None:
    487             return obj

TypeError: unhashable type: 'NonHashableWithDtype'
```

### Runtime information:
```
$ python -c "import numpy; print(numpy.show_runtime()
[{'numpy_version': '1.25.0.dev0+1465.g126b46c7a',
  'python': '3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]',
  'uname': uname_result(system='Linux', node='018ecd4e5eb3', release='5.15.107+', version='#1 SMP Sat Apr 29 09:15:28 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/usr/local/lib/python3.10/dist-packages/numpy.libs/libopenblas64_p-r0-7a851222.3.23.so',
  'internal_api': 'openblas',
  'num_threads': 2,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'}]
```

### Context for the issue:

This causes JAX unit tests to fail with the nightly numpy version: https://github.com/google/jax/actions/runs/4689008012/jobs/8310218419

**Comment by seberg** [comment]
@eendebakpt I thought we made sure to always call `np.dtype()` first here, I guess we didn't or did it slip through somehow?  Can you have a look.

**Comment by jakevdp** [comment]
I just noticed that this also fails for the same reason when passing a numpy array to `finfo`:
```python
np.finfo(np.arange(4.0))
# TypeError: unhashable type: 'numpy.ndarray'
```

**Comment by seberg** [comment]
Right, I remember being worried about something like this, but I guess the final version effectively had the problem.  Maybe even a `try/except` is reasonable in this particular case...  (expecting a dtype input, which is the reasonable thing IMO)

**Comment by eendebakpt** [comment]
> @eendebakpt I thought we made sure to always call `np.dtype()` first here, I guess we didn't or did it slip through somehow? Can you have a look.


I will have a look, but it will take a week before I get to it

**Comment by eendebakpt** [comment]
@seberg @jakevdp I created #14847 to allow `np.info` on non-hashable types with a dtype again. I am wondering whether we should deprecate passing these kinds of objects to `np.info`.

1. Allowing these objects complicates the `np.finfo` implementation
2. These objects are always in the slow path (since they have no hash, they cannot be cached)
3. There is an easy alternative: instead of calling `np.info(x)` one can call `np.finfo(x.dtype)

It seems that `np.info(np.arange(4.0))` was not functional before #https://github.com/numpy/numpy/pull/23088, so that behaviour is unchanged.
