### ISSUE TITLE
Different results for numpy.fft.fft() when passing different types of argument (DataFrame, np.array) with the same valuesBUG: <Please write a comprehensive title after the 'BUG: ' prefix>

### ISSUE THREAD

**Issue by ThemisKoutsellis** [numpy/numpy#23873]
### Describe your issue.

From the attached CSV file, [input_data.csv](https://github.com/scipy/scipy/files/11653905/input_data.csv), I import the, say, `test_list`. Then, I create a `pd.Dataframe` to store my data in `test_df`.

```
from scipy import fft
import numpy as np

test_df = pd.DataFrame(index=range(len(test_list)), columns=['test'])
test_df['test'] = test_list
```
I want to calculate the FFT transform of the signal in `test_df['test']`. However, I get different results when I pass as input different types of arguments to the `scipy.fft.fft()`.

Once I pass the signal as a nympy.array I get the plot #1.

![dummy](https://github.com/scipy/scipy/assets/88409436/7cab8d6a-45e1-4e7f-a377-2d601b84c40b)

Once I pass the signal as a pd.Dataframe I get the plot #2.

![dummy](https://github.com/scipy/scipy/assets/88409436/41fb7740-5c23-4d59-b0f4-a7c5f20ac42c)

Both inputs, np.array and pd.DataFrame contain the same information.

From the problem definition the plot#2 seems to have a better physical interpretation.
However, it is not clear why I get different results.

May be it is a bug?

The code I use is below:

```
from scipy import fft
import numpy as np

test_df = pd.DataFrame(index=range(len(test_list)), columns=['test'])
test_df['test'] = test_list


########## PLOT 1: from Numpy  ##############

to_np = test_df['test'].to_numpy()
print(to_np)

fft_output = fft.fft(to_np)
power = np.abs(fft_output)
freq = numpy.fft.fftfreq(len(to_np))

mask = freq >= 0
freq = freq[mask]
power = power[mask]


plt.plot(freq, power)
plt.show()


########## PLOT 2: from pd.DataFrame  ##############

to_df = test_df['test'].to_frame()
print(to_df)

fft_output = numpy.fft.fft(to_df)
power = np.abs(fft_output)
freq = fft.fftfreq(len(to_df))


mask = freq >= 0
freq = freq[mask]
power = power[mask]


plt.plot(freq, power)
plt.show()

```

### Reproduce the code example:

```python
from scipy import fft
import numpy as np

test_df = pd.DataFrame(index=range(len(test_list)), columns=['test'])
test_df['test'] = test_list


########## PLOT 1: from Numpy  ##############

to_np = test_df['test'].to_numpy()
print(to_np)

fft_output = fft.fft(to_np)
power = np.abs(fft_output)
freq = numpy.fft.fftfreq(len(to_np))

mask = freq >= 0
freq = freq[mask]
power = power[mask]


plt.plot(freq, power)
plt.show()


########## PLOT 2: from pd.DataFrame  ##############

to_df = test_df['test'].to_frame()
print(to_df)

fft_output = numpy.fft.fft(to_df)
power = np.abs(fft_output)
freq = fft.fftfreq(len(to_df))


mask = freq >= 0
freq = freq[mask]
power = power[mask]


plt.plot(freq, power)
plt.show()
```

### Runtime information:

1.23.5
3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ]

**Comment by rossbar** [comment]
Thanks for reporting @ThemisKoutsellis . I'm going to close this in favor of scipy/scipy#18635 to reduce duplication.

**Comment by rossbar** [comment]
It looks like you're using scipy's fft module, so I figured scipy was more appropriate. However, if you've done some additional digging then please feel free to close that and reopen this as you see fit!

**Comment by ThemisKoutsellis** [comment]
In this version of issue I use numpy.` fft_output = numpy.fft.fft(to_df)` i tested both ways (scipy and numpy) and I after realized that it is a numpy issue
