### ISSUE TITLE
ENH: `assert_array_less` should report max violations instead of max differences

### ISSUE THREAD

**Issue by allenlawrence94** [numpy/numpy#23894]
### Proposed new feature or change:

When `numpy.testing.assert_array_less` fails, it reports a "Max absolute difference" and a "Max relative difference". These metrics are the max element-wise differences between the two tested arrays. These make sense to report when testing array equality, but they don't seem useful when asserting that one array is element-wise less than another. It would make more sense to report the maximum values by which the less-than constraint is violated. "Max absolute violation" could be calculated as:

```
np.maximum(array1 - array2, 0).max()
```

when `npt.assert_array_less(array1, array2)` fails. "Max relative violation" could be calculated similarly.

I'd be happy to implement this if people agree. Thanks!

**Comment by seberg** [comment]
Right the difference itself isn't meaningful for those, so I would agree that it should report the difference only for violating terms.
Not sure if it does or doesn't, but we can change the wording in that case to be clearer.

**Comment by allenlawrence94** [comment]
It reports the max difference of all terms, not just violating terms. Here's an example:

```python
from numpy.testing import assert_array_less
import numpy as np

assert_array_less([0., 3., 0.], [1000., 2.5, 1.])
```
which prints:
```
Arrays are not less-ordered

Mismatched elements: 1 / 3 (33.3%)
Max absolute difference: 1000.
Max relative difference: 1.
 x: array([0., 3., 0.])
 y: array([1000. ,    2.5,    1. ])
```

The only violation here 3.0 !< 2.5, but it reports "Max absolute difference: 1000."

**Comment by ellaella12** [comment]
Hi may I check if this issue is open for contribution? I would like to give it a go if it is open

**Comment by mattip** [comment]
We don't assign issues. When you submit a PR, refer back to this with a `#23894` (without the code formatting) so github will create a link to this issue and others will know you are working on it. @allenlawrence94 did you get anywhere with
>  I'd be happy to implement this if people agree.

I don't see a linked PR.

**Comment by allenlawrence94** [comment]
@mattip - no I haven't been able to work on this yet. @ellaella12 - feel free to take it if you like!
