### ISSUE TITLE
ENH: Implement the fft extension in numpy.array_api

### ISSUE THREAD

**Issue by asmeurer** [numpy/numpy#23892]
### Proposed new feature or change:

This is just a tracking issue. I will probably work on this at some point. The [fft extension](https://data-apis.org/array-api/latest/extensions/fourier_transform_functions.html) in the array API needs to be implemented in `numpy.array_api`. This is somewhat blocked on (or should at least be developed in conjunction with) proper support in the [array API test suite](https://github.com/data-apis/array-api-tests).

See the discussion at https://github.com/numpy/numpy/issues/23880#issuecomment-1578050219. The functions should be mostly the same as those in `np.fft`, but there might be some small differences (hence the need for test suite support).

**Comment by lucascolley** [comment]
Hi Aaron, here are two small differences that I have found. These are the only differences that I have found so far, so I agree that the functions are mostly the same as those in `np.fft`.

1. `fftfreq` and `rfftfreq` have the extra optional `device` keyword.
array API: `fftfreq(n, /, *, d=1.0, device=None)`
NumPy: `fftfreq(n, d=1.0)`
2. for the basic fft functions, the default value of `norm` is now `'backward'` not `None`.
array API: `norm: Literal['backward', 'ortho', 'forward'] = 'backward'`
NumPy: `fft(a, n=None, axis=-1, norm=None)`
