### ISSUE TITLE
ENH: datetime64: Remove deprecation warning when constructing with timezone

### ISSUE THREAD

**Issue by alkhwarizmi** [numpy/numpy#23904]
### Proposed new feature or change:

Dear all,

the command `t0 = np.datetime64('2023-06-09T12:18:40Z', 'ns')` produces the warning

```
DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
```

I propose, like others before me, to remove the deprecation warning when constructing datetime64 objects with timezones, because it is a useful and correct feature. [Here](https://www.mail-archive.com/numpy-discussion@python.org/msg04543.html) and [here](https://www.mail-archive.com/numpy-discussion@python.org/msg04550.html) Dr. Yorav-Raphael already raised and well motivated the reasons. I fully share his view and agree with his discussion.

The fact that after 3 years from his call I still see the warning, lets me think that in fact his view passed and the feature is not really going to be removed in future. Therefore, it is just matter to remove the deprecation warning. This would relax me and the colleagues of mine who are relying on this useful conversion.

Sincerely,

**Comment by mattip** [comment]
We discussed this at a triage meeting and feel we should not really deprecate this, rather parsing a datetime with a timezone will continue to take the timezone into account and then dropped. So we would prefer to turn this into a permanent UserWarning:
```
userWarning: no explicit representation of timezones available for np.datetime64
```

**Comment by stefanv** [comment]
It would be good to update the `np.datetime64` docstring to be more explicit as well. Currently, it merely states:

```If created from a 64-bit integer, it represents an offset from
``1970-01-01T00:00:00``.
If created from string, the string can be in ISO 8601 date
or datetime format.
```

So this describes the valid inputs, but doesn't give insight into how it is stored.

**Comment by rmhowe425** [comment]
take

**Comment by rmhowe425** [comment]
@stefanv I can work on this. 

It looks like all that is needed here is a doc update?

**Comment by stefanv** [comment]
Thanks! A doc update, as well as turning the warning into a UserWarning as per Matti's comment.

**Comment by seberg** [comment]
@jbrockmendel sorry for the ping, do you have an opinion on how this should be done?  I guess pandas has some timezone support so the problem isn't as tricky?

**Comment by jbrockmendel** [comment]
> I guess pandas has some timezone support so the problem isn't as tricky?

Yes.  In pandas passing a string with a timezone will return a timezone-aware Timestamp object or datetime64tz dtype.

> do you have an opinion on how this should be done?

I think a UserWarning sounds reasonable.  I'd make sure the message indicates whether you are keeping the local time vs UTC time.
