### ISSUE TITLE
Cannot squeeze axis with size equal to one

### ISSUE THREAD

**Issue by joaolcguerreiro** [numpy/numpy#23903]
### Describe the issue:

Hi, so I'm implementing a function and for that I need to remove the channel dim (axis=0).

I'm doing the following:
`shape = np.array(volume.shape).squeeze(axis=0)`

However I'm getting the error: `ValueError: cannot select an axis to squeeze out which has size not equal to one`

I strongly believe this is wrong. I printed out `np.array(volume.shape)`and `np.array(volume.shape)[0]`which resulted in:
> [  1 200 200 200]
> 1

Really don't know what is happening here...

### Reproduce the code example:

```python
import numpy as np
import torch

volume = torch.rand(1, 200, 200, 200)
np.array(volume.shape)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/joaoguerreiro/Documents/Research/SRMeDiff/code/SRMeDiff/src/visualization/visualization.py", line 154, in <module>
    main()
  File "/Users/joaoguerreiro/Documents/Research/SRMeDiff/code/SRMeDiff/src/visualization/visualization.py", line 125, in main
    display_batch(volumes=volumes, plane=args.plane, dimension=args.dim, slice_index=args.slice, volume_index=args.volume)
  File "/Users/joaoguerreiro/Documents/Research/SRMeDiff/code/SRMeDiff/src/visualization/../../src/utils/utils.py", line 223, in display_batch
    scale_factor = compute_scale_factor(volumes[0]) if volumes else (1, 1, 1)
  File "/Users/joaoguerreiro/Documents/Research/SRMeDiff/code/SRMeDiff/src/visualization/../../src/utils/utils.py", line 201, in compute_scale_factor
    shape = np.array(volume.shape).squeeze(axis=0)
ValueError: cannot select an axis to squeeze out which has size not equal to one
```

### Runtime information:

1.24.3
3.10.11 (main, Apr 20 2023, 13:58:42) [Clang 14.0.6 ]
[{'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'armv8',
  'filepath': '/Users/joaoguerreiro/miniconda3/envs/e2esrseg/lib/libopenblasp-r0.3.21.dylib',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None

**Comment by seberg** [comment]
Sorry, but this is just a weird mind-slip and I don't feel like going into details.  Check the `squeeze` docs, your `np.array(...).shape`, and then think about what you *expect* to happen from an array being squeezed and not a "shape".

**Comment by joaolcguerreiro** [comment]
Oh jesus christ haha I should have done np.array(volume.squeeze(axis=0).shape)... I feel embarrassed right now haha

Thank you :)
