### ISSUE TITLE
DOC: Modification in README.md

### ISSUE THREAD

**Issue by Anurag9492722884** [numpy/numpy#23910]
Hello everyone,

In the [README.md](https://github.com/numpy/numpy#readme) file, in the "It provides" section 

only these were mentioned
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

But we can add one most important feature of the Numpy array object ie
* Memory efficient and maskable arrays

Hope you consider my issue:)

**Comment by rgommers** [comment]
Thanks @Anurag9492722884, but I'll close this. The "maskable" part we don't want to advertise, since `numpy.ma` is basically legacy and users are better off using a dataframe library for solid missing values support. The "memory efficient" is basically covered by the first bullet already.
