### ISSUE TITLE
BUG: ~ndarray(bools, dtype=object) 

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#23926]
### Describe the issue:

Negating an object-dtype ndarray containing bool objects converts to negative integers instead of negating pointwise.

### Reproduce the code example:

```python
arr = np.array([True, False], dtype=object)

>>> ~arr
array([-2, -1], dtype=object)
```

### Runtime information:

1.24.2

**Comment by rkern** [comment]
That's the behavior of `True` and `False` Python objects. Python `bool` objects are just `int` objects with values of 1 and 0. They changed the `__repr__` but left all of the arithmetic operations the same as `int`. When you use `dtype=object`, this is what we expect to happen.

```
>>> ~True, ~False
(-2, -1)

>>> ~1, ~0
(-2, -1)
```
