### ISSUE TITLE
BUG: message "'lscpu' is not recognized as an internal or external command, ..." printed

### ISSUE THREAD

**Issue by lschoe** [numpy/numpy#23954]
### Describe the issue:

On Windows with NumPy 1,25.0rc1, `lscpu` is not available as a shell command.

The call to `lscpu` is introduced in #22982 to implement `check_support_sve()`.

### Reproduce the code example:

```python
import numpy.testing
```

### Error message:

```shell
'lscpu' is not recognized as an internal or external command,
operable program or batch file.
```

### Runtime information:

1.25.0rc1
3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
[{'numpy_version': '1.25.0rc1',
  'python': '3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='MUTS10', release='10', version='10.0.19045', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\Berry\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.23-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'}]
None

### Context for the issue:

This message is printed and may cause confusion or corrupt screen output.

Also happens for example for programs like this `python -c "import sklearn"` , hence not only in testing mode.

**Comment by lschoe** [comment]
Yes, such a catch should work.

So,  `python -c "import sklearn"` and `python -c "import numpy.testing"` will trigger the error message. But only once, so importing `sklearn` later on will not trigger the message again, like in: `python -c "import numpy.testing; import sklearn"`.

**Comment by joaoe** [comment]
Hi.
I decided to contribute a small patch to make the call to the external process happen on demand
https://github.com/numpy/numpy/pull/27472
