### ISSUE TITLE
MAINT: apply pyupgrade to numpy sources

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [numpy/numpy#23976]
### Proposed new feature or change:

I would like to:
1. run [pyupgrade](https://github.com/asottile/pyupgrade) on numpy sources (typically `pyupgrade --py39-plus`),
2. add it as a pre-commit hook if there's interest.

The objective is to make use of recent Python features, such as f-strings, consistent with the current minimal Python version supported. However, most suggestions are consistent with Python 3.5 or event earlier. I feel it is easier to manually upgrade the code, before trying to automate.

See “[Implemented features](https://github.com/asottile/pyupgrade#implemented-features)” for a general overview of the changes suggested by [pyupgrade](https://github.com/asottile/pyupgrade). 

I have already created pull requests with pyupgrade suggestions, some of which have been merged:

* #23826
* #23833 (still in progress)
* #23834
* #23837
* #23977
* #23980

**Comment by DimitriPapadopoulos** [comment]
A few notes:
1. Most importantly, [pyupgrade](https://github.com/asottile/pyupgrade) doesn't simply report issues, rather it fixes them.
2. Also, it is “uncompromising” like [black](https://github.com/psf/black), in the sense that you cannot disable classes of issues. It has few options:
   ```
     -h, --help            show this help message and exit
     --exit-zero-even-if-changed
     --keep-percent-format
     --keep-mock
     --keep-runtime-typing
     --py3-plus, --py3-only
     --py36-plus
     --py37-plus
     --py38-plus
     --py39-plus
     --py310-plus
     --py311-plus
   ```
   Most of the suggestions make sense, but my experience with other modules is that maintainers may dislike some of the opinionated pyupgrade changes, particularly:
   * [Set literals](https://github.com/asottile/pyupgrade#set-literals)
   * [Dictionary comprehensions](https://github.com/asottile/pyupgrade#dictionary-comprehensions)
   * [redundant `open` modes](https://github.com/asottile/pyupgrade#redundant-open-modes)
   
   Yet, they make sense if you think about it. For example, I am less surprised by the result of `{"string"}` (`{'string'}`) than the result of `set("string")` (`{'g', 'i', 'n', 'r', 's', 't'}`).
3. You may need to run pyupgrade twice. These changes are applied sequentially:
   * [printf-style string formatting](https://github.com/asottile/pyupgrade#printf-style-string-formatting) (from old prtinf-style formatting to `format()`)
   * [f-strings](https://github.com/asottile/pyupgrade#f-strings) (from `format()` to f-strings)
4. Some changes break formatting, so pyupgrade is best run together with [black](https://github.com/psf/black) or some other code formatter. For example:
   ```python
   "Some text: %s %s %s %s %s %s" % (parameter_a, parameter_b,
                                     parameter_c, parameter_d,
                                     parameter_e, parameter_f
   )
   ```
   yields:
   ```python
   "Some text: {} {} {} {} {} {}".format(parameter_a, parameter_b,
                                     parameter_c, parameter_d,
                                     parameter_e, parameter_f
   )
   ```
5. While changing all occurrences of `format()` to f-strings will not always be possible or reasonable, at least not without adding temporary variables, pyupgrade will sometimes give up in cases where f-strings do make sense.

For the above reasons, I thought it would be best to review classes of issues fixed by pyugrade in a project, one pull request at a time for each class of changes. This, of course, is somehow tedious, since pyupgrade does not provide a way to apply only a single rule at a time for easier reviewing, but I can do that, or rather have already started as you can see.

**Comment by rgommers** [comment]
@DimitriPapadopoulos thanks for the PRs so far. Some cleanups of really old/outdated constructs may be worth doing. We discourage style-only PRs however; large-scale changes like converting everything to f-strings are a lot of churn, hard to review, and typically not worth it. And we don't want to use pre-commit. So I'd say judiciously chosen PRs welcome, but we'd rather not apply more tools like `pyupgrade` in a blanket fashion.

**Comment by DimitriPapadopoulos** [comment]
It's just that f-strings are not only about style, they're supposed to be faster too. But I understand, it is not worth optimising one line of output here and there.

**Comment by Avasam** [comment]
Alternatively you could use Ruff's `UP` category. Which is configurable if any specific codemod is unwanted, and has safer autofixes.

**Comment by DimitriPapadopoulos** [comment]
Moving to ruff is a much better idea nowadays.
