### ISSUE TITLE
DOC: Minor - text in release emails contains “Python 12” instead of “Python 3.12”

### ISSUE THREAD

**Issue by infinity77** [numpy/numpy#23970]
### Issue with current documentation:

I’m not entirely sure is a documentation issue, but in the release (or pre-release) emails I see the following:

![IMG_0252](https://github.com/numpy/numpy/assets/8988321/ca5b555f-bc71-43a9-b64f-f8260323d1dc)

looks like the “3.” part after “Python” gets stripped away somehow.

Definitely minor and not worth wasting your time on it, but I just wanted to make it known 😊.

Andrea.

**Comment by melissawm** [comment]
Thanks! If it's just the email, I don't think we can fix it 🙂 Looking at the [news page](https://numpy.org/news/) and [the release notes](https://numpy.org/doc/stable/release/1.25.0-notes.html) this is correct, so I am closing this issue. Feel free to reopen if you find anything else. Cheers!
