### ISSUE TITLE
BUG: SciPy is seeing incorrect warnings on MacOS M1 (M2?) `array * scalar`

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#23996]
CC @tylerjereddy.  See https://github.com/scipy/scipy/pull/18697, it seems MacOSX on arm optimizes the multiply in a way that leads to loading uninitialized values/zeros probably, so that `0 * inf` triggers a warning.

I am not sure we should worry too much about it, since clang on MacOS X for arm doesn't properly support `-ftrapping-math` IIRC, which tends to make things difficult, but it is incorrect.  The SciPy test should not show a warning in the specific multiplication.

**Comment by tylerjereddy** [comment]
Let me know if you want me to test anything specific.

**Comment by seberg** [comment]
Thanks, no need...  This is a trivial repro that works on my machine:
```
np.arange(1, 12.) * np.inf
```

**Comment by seberg** [comment]
Ping @Developer-Ecosystem-Engineering since maybe you can have a look at this and there is an easy fix.

**Comment by tylerjereddy** [comment]
See also:
https://github.com/scipy/scipy/pull/18737
https://github.com/scipy/scipy/pull/18738

Flaky behavior, sometimes < 80 failures in 20,000 trials of the same calculation, so reproducing is a bit tricky.

`clang` version:

```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Developer-Ecosystem-Engineering** [comment]
We understand the issue, please stand by

**Comment by Developer-Ecosystem-Engineering** [comment]
Please see https://github.com/numpy/numpy/pull/24054 for a proposed fix.
