### ISSUE TITLE
BUG: Multiply complex128 ufunc inconsistent with AVX2

### ISSUE THREAD

**Issue by jakelishman** [numpy/numpy#24000]
### Describe the issue:

With Numpy 1.25.0 on Intel macOS 13.3.1, I've found a small reproducer where the result of the multiplication ufunc over `complex128` seems to have non-deterministic output; it can vary within the same Python interpreter session for two identical operations.  I cannot reproduce the failures with Numpy 1.24.3, nor with Numpy 1.25 but with AVX2 disabled.

I also couldn't reproduce the failure with any version of Numpy I built from source (to try and bisect), but I suspect that's more to do with me not managing to configure all the same build flags / available libraries as the distributed wheel.

### Reproduce the code example:

```python
import sys
import numpy

a = [
    numpy.array([
        [0.37407431362525206 + 0.7981674467868007j, 0.4497329415302707 + 0.1440049168541349j],
        [0.44973294153027066 - 0.14400491685413508j, -0.37407431362525156 + 0.7981674467868008j],
    ])
    for _ in [None] * 2
]
b = 0.7071067811865476 - 0.7071067811865475j

if (a[0] * b)[1, 1] - (a[1] * b)[1, 1]:
    sys.exit(1)
```

### Runtime information:

Numpy version: 1.25.0
```
>>> np.show_runtime()
[{'numpy_version': '1.25.0',
  'python': '3.10.6 (main, Aug 27 2022, 03:27:18) [Clang 14.0.6 ]',
  'uname': uname_result(system='Darwin', node='ninetales', release='22.4.0', version='Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL']}},
 {'architecture': 'Haswell',
  'filepath': '/Users/jake/code/qiskit/venv310/lib/python3.10/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 4,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'}]
```

### Context for the issue:

The reproducer script above exits in the failure condition intermittently on my machine when AVX2 extensions are available.  The result between the two branches sometimes differs by 1ULP in the imaginary component (`0.2998791303131809+0.8289000979774184j` vs `0.2998791303131809+0.8289000979774185j`).

My expectation was that `multiply` should produce bit-for-bit identical output for the same arrays when the same sets of SIMD extensions are available (as within the same interpreter session).  It's no problem for us if there's some low-ULP differences between different SIMD features being enabled, but the core `multiply` ufunc varying within the same interpreter session appears to have destabilised some more complex numerical decomposition code in our repository (https://github.com/Qiskit/qiskit-terra).

**Comment by ngoldbaum** [comment]
Ping @seiko2plus or @Developer-Ecosystem-Engineering in case this rings a bell.

**Comment by charris** [comment]
Might also be compiler related. @jakelishman What version of clang do you use?

**Comment by jakelishman** [comment]
In the bug report I was using the published wheel, but when I was trying to build Numpy from source myself, I will have been using the Apple clang that corresponded to macOS 13.3.1 (not certain which XCode).  I'm sorry I can't give you the full version string for it, since I've updated my C tooling since then.

**Comment by jakelishman** [comment]
I had some time to come back to this, and I've found that I can reproduce the failures with Numpy built from source if I used the Apple-distributed `clang 14.0.0` but _not_ if I used `clang 14.0.3`, with those two versions corresponding to XCode command-line tools versions 14.2 and 14.3.1 respectively.  For completeness' sake, I used the same versions of `libopenblas64_` and `libgfortran` that the CI wheels jobs downloads, but given they're linked in dynamically and the bug appears to be compiler-related, I'm not sure if that had any impact.

The `macos-12` GitHub image used (as best as I could tell) to build the Numpy wheels for distribution has XCode tools 14.2 / Apple clang 14.0.0, which is the version I was able to reproduce failures locally with.  If it helps, the `macos-13` image has XCode tools 15.0 / Apple clang 14.0.3.  I haven't yet tried with that version of the full command-line tools, but that's (up to any additional Apple-specific patches) a version of clang that was working for me.

**Comment by ngoldbaum** [comment]
@charris do you know whether we can build the mac wheels with a version of clang that doesn’t have this issue?

**Comment by charris** [comment]
@ngoldbaum I expect the problem is which versions of macos we support. If XCode produces backwards compatible code, and I expect it does, we might be able to do something if cirrus supports the needed version.

Looks like cirrus does support latest xcode, but I don't know how far back compatibility of the generated code can go. We have been pretty conservative in supporting older macos versions. Maybe @Developer-Ecosystem-Engineering can help.

**Comment by andyfaff** [comment]
I think it's possible to list the available SDKs by running `ls -l /Library/Developer/CommandLineTools/SDKs`. One can then choose which SDK you wish to use from those. I don't think one can choose from different compilers, but I can't remember.
I'd expect @isuruf to also be a source of knowledge here.

**Comment by isuruf** [comment]
> but I don't know how far back compatibility of the generated code can go. We have been pretty conservative in supporting older macos versions.

It depends on MACOSX_DEPLOYMENT_TARGET only. (Since AVX2 code is guarded behind a runtime CPU selection by numpy)

> I think it's possible to list the available SDKs by running ls -l /Library/Developer/CommandLineTools/SDKs. One can then choose which SDK you wish to use from those. I don't think one can choose from different compilers, but I can't remember.

SDKs and the toolchains (which include clang) are different. If there are two versions of xcode installed (and hence two versions of clang), you can switch by setting,
```
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
```
This makes `/usr/bin/clang` point to the clang from the xcode version selected.

You can also of course change the Cirrus CI image which changes the default xcode selected.

**Comment by jakelishman** [comment]
Changing the build toolchain version sounds (to me?) like it would be a disqualifier for backporting a bugfix - I know I wouldn't consider that on our own projects without at least a minor release unless our hand was forced.  According to [Wikipedia's table of Xcode toolchain versions](https://en.wikipedia.org/wiki/Xcode), despite the version-string similarities, Apple clang 14.0.0 to 14.0.3 came with an upgrade of the backing LLVM from 14 to 15.

Would a palatable, less disruptive change be to decay the compilation of the c64/c128 multiply ufunc to the non-SIMD form if the building compiler is known to be affected?  Something like inserting a
```c
#if @is_mul@ && defined(__clang__) && defined(__apple_build_version__) && \
    __apple_build_version__ >= 14000029 && __apple_build_version__ < 14030022
  goto loop_scalar;
#endif
```
into the `multiply` ufunc here? https://github.com/numpy/numpy/blob/5d4d05a3bb3515d9702d8fc39a0eaff31cfff150/numpy/core/src/umath/loops_arithm_fp.dispatch.c.src#L369-L377

Happy to make a PR doing so, if it would help - locally, that fixed the problems I was seeing.  I pulled those versions of the `__apple_build_version__` from Apple clangs 14.0.0 and 14.0.3 respectively.

**Comment by charris** [comment]
@jakelishman Yes, go ahead and make a PR. and add an explanatory comment with it referring to this issue. One worry is that this particular bug might also appear elsewhere if it is due to one of the SIMD functions not performing correctly.

**Comment by jakelishman** [comment]
Thanks - I've made #24828 after confirming it works locally for our library (well, at least in backport-position for 1.26.x, since we're not Numpy-2 ready yet!).

I tried to reproduce similar failures of the `add` and `sub` ufuncs that are generated from the same codegen, but I never saw any failure of those, so I limited the scalarisation to only `multiply` with affected os/arch/compiler.
