### ISSUE TITLE
BUG: np.float64 multiplication should fail with NotImplemented if it cannot handle the right-hand side object

### ISSUE THREAD

**Issue by timhoffm** [numpy/numpy#24005]
### Describe the issue:

A multiplication `float64_val * obj` can fail with 

> TypeError: Could not convert object to sequence

for certain kinds of `obj`. This behavoir is incorrect and it should instead  return `NotImplemented` (https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types):

> If one of those methods does not support the operation with the supplied arguments, it should return `NotImplemented`.

Returning `NotImplemented` would allow the Python operator logic to go and try `obj.__rmul__(float64_val)`.

---

The object type, where I found this is a bit special: implements `__len__` and `__getitem__`, but is explicitly not iterable (`__iter__ = None`). This is a rare case but explicitly mentioned as a possibility in the python docs https://docs.python.org/3/reference/datamodel.html#special-method-names).

This TypeError likely comes form:

https://github.com/numpy/numpy/blob/dbc454a15d26a9fd23200c62e0214f3ed95756ad/numpy/core/src/multiarray/array_coercion.c#LL1125

### Reproduce the code example:

```python
>>> import numpy as np
>>> class Scalable:
...     def __init__(self, value):
...         self.value = value
...         
...     def __getitem__(self, name):
...         return "Item"
...     
...     def __len__(self):
...         return 2
...     
...     __iter__ = None
...         
...     def __rmul__(self, value):
...         return Scalable(value * self.value)
...     
...     def __repr__(self):
...         return f"Scalable({self.value})"
... 
>>> 0.5 * Scalable(2)  # simple float works
Scalable(1.0)
>>> np.float64(0.5) * Scalable(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Could not convert object to sequence
```

### Error message:

```shell
TypeError: Could not convert object to sequence
```

### Runtime information:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.25.0
3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0]

>>> print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.0',
  'python': '3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='zolxq00617', release='5.4.0-148-generic', version='#165~18.04.1-Ubuntu SMP Thu Apr 20 01:14:06 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX'],
                      'not_found': ['AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]

### Context for the issue:

Priority may be low because it happens only on very specific objects. However, this is a non-compliant behavior and it may be reasonable to more broadly return `NotImplemented` when operators cannot be applied and raise.

Additionally, even if this is not fixed. The report may serve as searchable reference for other people encountering `TypeError: Could not convert object to sequence` - The message is not very helpful and also web search did not provide any helpful insights what the problem is.

**Comment by timhoffm** [comment]
Thanks, for the quick reply. 🚀  Do I understand this correctly: If my class is not a ndarray subtype, the correct way of telling numpy not try to apply ufunc operators to my class is to set `__array_ufunc__ = None`.

**Comment by seberg** [comment]
Yes, I think some errors might look a bit weird, but you could implement a dummy to make them nicer probbaly (or a PR to numpy).  If there is some reason not to, then set `__array_priority__` to some numeric value greater than that of scalars.

**Comment by seberg** [comment]
Closing then.  I don't see how you could do that in a meaningful (specific enough way).  Basically, the above is the way to do it.

I could see that a way to signal "this is a scalar" or "this is an array-like so don't convert" may help with issues around this stuff. (maybe even as a core Python ABC), but it seems like a different issue.
