### ISSUE TITLE
DOC: doc is wrongly updated for empty method

### ISSUE THREAD

**Issue by harikrishna553** [numpy/numpy#24016]
### Issue with current documentation:

Section '2.2.2 Array Creation' of user guide (https://numpy.org/doc/1.21/numpy-user.pdf) quoting below statement.

**the function empty creates an array whose initial content is random and depends on the state of the memory.**

But as 'empty' method  return a new array of given shape and type, without initializing entries.

**Comment by Mukulikaa** [comment]
Both of those statements mean the same thing. The initial random content in an `empty` array is not set or initialized by the function. It is the garbage value that exists from the previous use of the memory where the new array is located at. Hence the phrase "depends on the state of the memory". 
In contrast, `np.zeros` explicitly assigns all elements as zero in the new array.
