### ISSUE TITLE
BUG: TypeError: Cannot enter `np.errstate` twice when creating `np.random.RandomState` instances concurrently

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#24013]
### Describe the issue:

The scikit-learn nightly CI has found a regression when testing against last night's numpy dev wheel:

https://dev.azure.com/scikit-learn/scikit-learn/_build/results?buildId=56067&view=logs&j=dfe99b15-50db-5d7b-b1e9-4105c42527cf&t=ef785ae2-496b-5b02-9f0e-07a6c3ab3081&l=1596

I seems caused by #23936.

It happens when trying to create `numpy.random.RandomState` instances concurrently in different threads. Below is a minimal reproducer:

### Reproduce the code example:

```python
from concurrent.futures import ThreadPoolExecutor
import numpy as np


def build_rngs(*ignored):
    return [np.random.RandomState(i) for i in range(100)]


with ThreadPoolExecutor(max_workers=4) as executor:
    list(executor.map(build_rngs, range(100)))
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/ogrisel/tmp/numpy_errstate.py", line 10, in <module>
    list(executor.map(build_rngs, range(100)))
  File "/Users/ogrisel/mambaforge/envs/numpydev/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/numpydev/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/numpydev/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/mambaforge/envs/numpydev/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/ogrisel/mambaforge/envs/numpydev/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/tmp/numpy_errstate.py", line 6, in build_rngs
    return [np.random.RandomState(i) for i in range(100)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/tmp/numpy_errstate.py", line 6, in <listcomp>
    return [np.random.RandomState(i) for i in range(100)]
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 184, in numpy.random.mtrand.RandomState.__init__
  File "_mt19937.pyx", line 130, in numpy.random._mt19937.MT19937.__init__
  File "/Users/ogrisel/mambaforge/envs/numpydev/lib/python3.11/contextlib.py", line 80, in inner
    with self._recreate_cm():
  File "/Users/ogrisel/mambaforge/envs/numpydev/lib/python3.11/site-packages/numpy/core/_ufunc_config.py", line 406, in __enter__
    raise TypeError("Cannot enter `np.errstate` twice.")
TypeError: Cannot enter `np.errstate` twice.
```

### Runtime information:

2.0.0.dev0+284.g9cba4697a
3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]
[{'numpy_version': '2.0.0.dev0+284.g9cba4697a',
  'python': '3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) '
            '[Clang 15.0.7 ]',
  'uname': uname_result(system='Darwin', node='mba-2.local', release='22.5.0', version='Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103', machine='arm64')},
 {'simd_extensions': {'baseline': [], 'found': [], 'not_found': []}},
 {'architecture': 'armv8',
  'filepath': '/Users/ogrisel/mambaforge/envs/numpydev/lib/python3.11/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'}]
None

### Context for the issue:

It will cause a random regression to scikit-learn users (when training Random Forests with parallelism enabled) if the next numpy version is released in this state.

**Comment by seberg** [comment]
Seems `ContextDecorator` cannot work for an asyncio context manager right away:
```
class ContextDecorator(object):
    "A base class or mixin that enables context managers to work as decorators."

    def _recreate_cm(self):
        """Return a recreated instance of self.

        Allows an otherwise one-shot context manager like
        _GeneratorContextManager to support use as
        a decorator via implicit recreation.

        This is a private interface just for _GeneratorContextManager.
        See issue #11647 for details.
        """
        return self

    def __call__(self, func):
        @wraps(func)
        def inner(*args, **kwds):
            with self._recreate_cm():
                return func(*args, **kwds)
        return inner
```
We need to override `_recreate_cm` there for it to work.  Sincethat isn't actually documented anywhere, maybe we should just implement the `__call__` manually?
