### ISSUE TITLE
why numpy on new machine so slow

### ISSUE THREAD

**Issue by RunxingZhong** [numpy/numpy#24022]
### Steps to reproduce:

# test_numpy.py
```
import numpy as np

def testfunc(x):
    np.random.seed(x)
    X = np.random.randn(5000, 5000)
    np.linalg.eigh(X @ X.T)

# %timeit testfunc(0)

import time
for i in range(2):
    t1 = time.time()
    testfunc(0)
    t2 = time.time()
    print(t2 - t1)
    # break

```
python test_numpy.py

### Error message:

```shell
15.402074337005615
15.52828049659729

each take about 15 sec each testfunc call.
soo slow.

1.  I have test this simple task on another machine too. (same hardware)
machine01 = 15 sec
machine02 = 1.5sec (10 times faster!!)

2. I have test another simple pure c++ program on these two machinws.
machine01 = 20 sec
machine02 = 21 sec
which means these two machine's computing power is close

so I doubt that, some basic lib is incorrect on machine 01, or something wrong happend.
so far, I have try many solutions but failed.
as bellow Additional information: I have list all useful info for you. Thanks

(what should I check next?, please help!)
```

### Additional information:

htop
<img width="1437" alt="image" src="https://github.com/numpy/numpy/assets/13879734/29025894-b95d-4525-9f18-a68ea6af939f">

python --version
<img width="334" alt="image" src="https://github.com/numpy/numpy/assets/13879734/12828677-f56d-4057-9727-14f21be01b54">

python -m cProfile test_numpy.py # check time cost
<img width="849" alt="image" src="https://github.com/numpy/numpy/assets/13879734/855324b7-ef3d-4abf-8ce9-95316817d474">

pip show and config.show()
<img width="1090" alt="image" src="https://github.com/numpy/numpy/assets/13879734/7181c1fa-a725-41a5-ab2f-fddb1f005489">

ldd info
<img width="1322" alt="image" src="https://github.com/numpy/numpy/assets/13879734/e04963ca-abd3-4e6f-9acc-bd5bff372960">

system info
<img width="552" alt="image" src="https://github.com/numpy/numpy/assets/13879734/0bee79dd-3515-484c-8a84-a5d361a13e78">

cpus
<img width="1439" alt="image" src="https://github.com/numpy/numpy/assets/13879734/ea3061e5-ea51-4526-9e9a-86c64be8b926">

free -h
<img width="576" alt="image" src="https://github.com/numpy/numpy/assets/13879734/be06180b-98ad-45e0-8e87-21be153459ec">

**Comment by mattip** [comment]
Please post text not images. The issue template asks for the output of `np.show_runtime()`. Please do that for both machines. I imagine they are using different BLAS implementations, so be sure the output shows which BLAS is in use on each machine.

**Comment by RunxingZhong** [comment]
> 

Thanks for your reply!
I have add np.show_runtime() into my code.

the output as follow:
(base) [root@localhost test]# python test_numpy.py
[{'numpy_version': '1.25.0',
  'python': '3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='localhost', release='5.14.0-325.el9.x86_64', version='#1 SMP PREEMPT_DYNAMIC Fri Jun 9 19:47:16 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/root/anaconda3/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-7a851222.3.23.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'}]
/root/test/test_numpy.py:7: RuntimeWarning: invalid value encountered in matmul
  np.linalg.eigh(X @ X.T)
13.903311729431152
13.9006028175354

actually.  machine 02 and machine 01 is same machine. (machine 01 just re-install centos system, Barely new machine)

**Comment by rkern** [comment]
Sorry, since `machine02` doesn't exist anymore, there isn't much we can do to help track down the discrepancy. It's possible that you accidentally timed just `X @ X.T` on `machine02` instead of the `eigh(X @ X.T)`, I get exactly that 10x difference between the two on my machine.

**Comment by RunxingZhong** [comment]
> Member

I can sure that, I test on exactly the same code.
and I can provide another test result on my another device. (Less computing resources， but faster)

code
```
import numpy as np
np.show_runtime()
print(np.__config__.show())
def testfunc(x):
    np.random.seed(x)
    X = np.random.randn(5000, 5000)
    np.linalg.eigh(X @ X.T)

import time
n = 2
for i in range(n):
    t1 = time.time()
    testfunc(0)
    t2 = time.time()
    print(t2 - t1)
```

output  as follow:
```
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/root/anaconda3/lib/python3.9/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
None
4.656202554702759
4.656385898590088
```

root@centos:~/test $ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
BIOS Vendor ID:      Smdbmds
CPU family:          25
Model:               1
Model name:          AMD EPYC 7K83 64-Core Processor
BIOS Model name:     3.0
Stepping:            0
CPU MHz:             2545.218
BogoMIPS:            5090.43
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-63
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext cpb ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 erms rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 arat fsrm

**Comment by RunxingZhong** [comment]
output on new machine (better cpu, slower speed)

```
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/home/rx/anaconda3/lib/python3.9/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
None
13.472135066986084
13.304012537002563
```

```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  128
  On-line CPU(s) list:   0-127
Vendor ID:               AuthenticAMD
  Model name:            AMD EPYC 7763 64-Core Processor
    CPU family:          25
    Model:               1
    Thread(s) per core:  2
    Core(s) per socket:  64
    Socket(s):           1
    Stepping:            1
    Frequency boost:     enabled
    CPU max MHz:         3529.0520
    CPU min MHz:         1500.0000
    BogoMIPS:            4899.58
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm ex
                         tapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_
                         occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca
Virtualization features:
  Virtualization:        AMD-V
Caches (sum of all):
  L1d:                   2 MiB (64 instances)
  L1i:                   2 MiB (64 instances)
  L2:                    32 MiB (64 instances)
  L3:                    256 MiB (8 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-127
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by celestinoxp** [comment]
I'm not an expert, but any possibility that there is a difference in the energy definitions? Or some turbo mode?
Example: in my pc I can use different types of energy: efficient, performance or turbo.
Do both processors have the same power setting?

**Comment by rgommers** [comment]
`OMP_NUM_THREADS` shouldn't apply to an OpenBLAS build that reports it's built with `pthreads` rather than OpenMP. 

There shouldn't be anything wrong here, and the investigation of this particular machine seems to have stalled, so I'll close this issue. Thanks all.
