### ISSUE TITLE
BUG: astype uint changes array values 

### ISSUE THREAD

**Issue by nagar-omer** [numpy/numpy#24033]
### Describe the issue:

when calling astype(np.uint8) on an array the values change

### Reproduce the code example:

```python
np.linspace(0, 1028, 8).astype(np.uint8)

out >> array([  0, 146,  37, 184,  75, 222, 113,   4], dtype=uint8)
```

### Runtime information:

array([  0, 146,  37, 184,  75, 222, 113,   4], dtype=uint8)

**Comment by ngoldbaum** [comment]
Values larger than 255 cannot be stored in a uint8, I’m not sure what’s expected here besides either an error about the overflowing values or what you’re getting now.

**Comment by seberg** [comment]
Closing, there are other issues about the fact the do silent overflows (actually probably undefined behavior, since we just inherit from C).  Overall, this should be expected.
