### ISSUE TITLE
BUG: `np.array([b""], dtype=object).astype("S")` changes element values in 1.25.0

### ISSUE THREAD

**Issue by Zac-HD** [numpy/numpy#24043]
Converting an object array containing empty bytestrings to `dtype="S"` (unknown-size binary string) replaces some, or occasionally all, elements with size-one bytestrings - presumably whatever happened to be in memory at that location.

This seems like a pretty bad bug to me, and has led to failing CI for https://github.com/HypothesisWorks/hypothesis/pull/3682 ([logs](https://github.com/HypothesisWorks/hypothesis/actions/runs/5366840968/jobs/9736489488?pr=3682#step:6:1337)).

### Reproducing example:

```python
import numpy as np

arr = np.array([b"", b""], dtype=object)
print(arr)
new = arr.astype("S")  # unsized bytestring
print(new)
print(new.astype(object))
```
```python
[b'' b'']
[b'' b'\x04']
[b'' b'\x04']
```

### Runtime information:
```
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.0',
  'python': '3.10.11 (main, Apr 25 2023, 20:05:52) [GCC 9.3.0]',
  'uname': uname_result(system='Linux', ..., machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}}]
```

**Comment by seberg** [comment]
Thanks! yeah that must be it.  We need to use the new dtype in that path, while for structured dtypes we need to replace it.  I think I broadened up using the original one to simplify things...

(Of course, on main branch, we should probably just switch to returning an _actual_ `"S0"` string, but that is a follow-up)
