### ISSUE TITLE
I am facing this issue: ImportError: cannot import name '_validate_lengths'

### ISSUE THREAD

**Issue by Adeel-farukh3** [numpy/numpy#24045]
python: 3.6.9; torch+Cuda: 1.8.1+cu111; Numpy: 1.19.5, but I am getting this error while generating the data for the CLOC Fusion Network dataset. Initially, I was also not able to install pointpillars.egg==info from requirements.txt then I comment it and finished the installation and then built the setup.py file.  
![_validate_lengths error](https://github.com/numpy/numpy/assets/137743163/a1432402-ba6e-4979-a0e3-2a3e5b2e94d6)  
Link of the repository: https://github.com/Loahit5101/PointPillars-Camera-LiDAR-Fusion/tree/main

**Comment by rkern** [comment]
You have a few-years-old version of `skimage` that used private functions from `numpy` that were removed some time ago. Use a more recent version of `skimage` (e.g. `0.18.0` should be sufficient as it contains https://github.com/scikit-image/scikit-image/pull/5081).

I will be closing this as there is nothing left for `numpy` to do about this.

**Comment by Adeel-farukh3** [comment]
![validate_lengths error](https://github.com/numpy/numpy/assets/137743163/ee1caf60-a45a-41c5-82a0-fc4b56b1e7ab)
 I am still facing this error even after the installation of skimage=0.18.0. You can find it in the screenshot. Thank you for your guidance.
