### ISSUE TITLE
BUG: `np.unique` yields inconsistent results in different runs

### ISSUE THREAD

**Issue by xychen2022** [numpy/numpy#24055]
### Describe the issue:

np.unique works inconsistently for the same input in different runs. The issue doesn't always appear but not rare
[label_for_test.nii.gz](https://github.com/numpy/numpy/files/11877127/label_for_test.nii.gz)

### Reproduce the code example:

```python
import numpy as np
import SimpleITK as sitk

labelNII = sitk.ReadImage("label_for_test.nii.gz", sitk.sitkInt32)

unique_ids_pre_resample = np.unique(sitk.GetArrayFromImage(labelNII))
print("unique_ids_pre_resample: ", unique_ids_pre_resample)
```

### Runtime information:

The correct output should be [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]. But depending on runs, the above code example can also give the following (and maybe other outputs):
unique_ids_pre_resample:  [        0         1         2         3         4         5         6
         7         8         9        10        11        12        13
        14        15  67108864 134217728]

**Comment by seberg** [comment]
Thanks for the report @xychen2022, could you please provide the output of `np.show_runtime()` as asked for in the template?  Also which NumPy and where you got it from (pip, conda...) would be good and what OS.

This seems plausibly related to @r-devulap work, but we really should have the confirmation with `np.show_runtime()`.

(It would be great if you could try whether a random/manual dataset can reproduce it, so we don't have to download and install libs just to try it.)

**Comment by r-devulap** [comment]
`np.unique` uses `np.sort` underneath, right?  I ran your script a few hundred times and I don't see the error with v1.25 which has the vectorized sort and argsort. 

@xychen2022 could you please report the NumPy version and `np.show_runtime()` information?

**Comment by rgommers** [comment]
No follow-up and it doesn't seem reproducible, so I'll close this issue. If @xychen2022 comes back with more details and a standalone reproducer, we can reopen if needed.
