### ISSUE TITLE
DOC: return of arctan2

### ISSUE THREAD

**Issue by 3zhang** [numpy/numpy#24056]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html

In `Returns` section the range is described as `[-pi, pi]` which actually should be `(-pi, pi]`.

**Comment by ai-naymul** [comment]
Hey @3zhang , I would love to work on this , may I?

**Comment by MohitKumar020291** [comment]
@seberg, Is @3zhang right? As I am confused in both ranges.

**Comment by melissawm** [comment]
Anyone is welcome to work on the issue, make sure you coordinate (whoever opens the PR first will get a review, so maybe you want to co-author it if that's helpful!)

**Comment by seberg** [comment]
The docs are *numerically* correct; note that -pi is *explicitly* mentioned in the notes. The branch cut does exclude the value in the mathematical definition, but that doesn't mean that it isn't a valid result for any numerical input (in this case -inf).

There is a reason I tagged this as "question", which of course I would have been very happy to see an answer for!

@ai-naymul and @MohitKumar020291 we don't assign issues, if you work on it, just open a PR directly.  If it is a larger issue you can ask for pointers;  I would discourage working on issues were someone started work *recently* (i.e. a week or so), but mainly clashes are rare so it's great if a PR is the first step.
