### ISSUE TITLE
BUG: Wheel version uploads is missing commit hash for nightlies

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#24065]
It seems the meson build is missing this version information.  It is probably in the installed NumPy, but just missing from the filename.

This is breaking our nightly upload.

Maybe there is a small fix to do this, but versioneer is a big thing to do very little and I think it was brought up before to just replacement, so it may well be a good excuse for that.

The alternative (and quickest) fix, would be to upload using `--force`, this seems to be what SciPy is doing, but I find it a bit odd to replace the old wheels?

**Comment by charris** [comment]
> for instance use git

`git describe` gives us all the information we need. I think the problem is somewhere in meson, probably in making the wheels.

**Comment by rgommers** [comment]
It's the uploader that needs adjusting here. We should not manually rename wheels, that's a bad practice that will not match what folks see locally and metadata will be wrong too I believe.

> The alternative (and quickest) fix, would be to upload using `--force`, this seems to be what SciPy is doing, but I find it a bit odd to replace the old wheels?

Yes, this is the way to go. It works fine for SciPy, and it avoid having to clean up wheels manually.

> I think the problem is somewhere in meson, probably in making the wheels.

The "put custom-generated hashes into wheel filenames" is an unsupported feature right now (xref https://github.com/mesonbuild/meson-python/issues/159). It's not easy to do, and not high-prio.

**Comment by mattip** [comment]
We can use `--force` for now. If reproducing errors becomes problematic due to the uncertainty which wheel was used, maybe we could add some metadata that reflects the commit internally to the wheel while not changing the wheel name.

**Comment by rgommers** [comment]
> If reproducing errors becomes problematic due to the uncertainty which wheel was used, maybe we could add some metadata that reflects the commit internally to the wheel while not changing the wheel name.

That's already there: `np.__version__` does contain the full hash (or `np.version.git_revision`).

**Comment by charris** [comment]
> The "put custom-generated hashes into wheel filenames" is an unsupported feature

Does this mean we need to explicitly change the name for rc and patch releases?

**Comment by rgommers** [comment]
In `meson.build`, yes - `2.0.0.dev0` should change to `2.0.0rc1` for the commit tagged as rc1. But that is no different from what we had to do in `setup.py` in the past (pre-versioneer; and in SciPy it's always been like that).
