### ISSUE TITLE
DOC: Where is a real API reference?

### ISSUE THREAD

**Issue by zzador** [numpy/numpy#24078]
### Issue with current documentation:

I have problems finding a real API reference in the numpy documentation. There is a section called API reference but it's much more an API documentation than a reference. I need a real reference where I have ALL the classes and global functions of the library listed on the left side. You know...like the API references of JAVA or the WIN32 API or any other API reference. Is there a real API reference for numpy somewhere?

**Comment by Mukulikaa** [comment]
Hi, @zzador. [This](https://numpy.org/devdocs/reference/index.html) is the only reference guide we maintain. Are you looking for something like the [scikit-learn API Reference](https://scikit-learn.org/stable/modules/classes.html)? There has been some discussion about this topic before and the general consensus was that we are happy to consider a flat API reference page with all functions listed if someone opens a PR implementing it. See [this comment](https://github.com/numpy/numpy/issues/19420#issuecomment-882686647).

**Comment by rgommers** [comment]
The question was answered, so I'll close this issue. Thanks @zzador and @Mukulikaa.
