### ISSUE TITLE
BUG: np.cross gives bad error if `ndim` is 0

### ISSUE THREAD

**Issue by zevbo** [numpy/numpy#24079]
### Describe the issue:

If you pass objects to `np.cross` that have `ndim` 0, it will throw the following very unclear exception:

```
numpy.AxisError: axisa: axis -1 is out of bounds for array of dimension 0
```

### Reproduce the code example:

```python
>> import numpy as np
>> np.cross(0, 0) # Produces error
>> np.cross(np.array(0), np.array([0, 1, 2])) # Produces error
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zev/.cache/.../lib/python3.10/site-packages/numpy/core/numeric.py", line 1587, in cross
    axisa = normalize_axis_index(axisa, a.ndim, msg_prefix='axisa')
numpy.exceptions.AxisError: axisa: axis -1 is out of bounds for array of dimension 0
```
```


### Runtime information:

np. show runtime:
```
[{'numpy_version': '1.25.0',
  'python': '3.10.0 (default, Jun  5 2023, 17:18:34) [GCC 11.3.0]',
  'uname': uname_result(system='Linux', node='zev-linux', release='5.19.0-45-generic', version='#46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/home/zev/.cache/pypoetry/virtualenvs/babbage-DbMGxNC6-py3.10/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-7a851222.3.23.so',
  'internal_api': 'openblas',
  'num_threads': 16,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'}]
```

### Context for the issue:

There should be a simple fix that's just putting a check before and throwing a more reasonable exception

**Comment by mattip** [comment]
> putting a check before and throwing a more reasonable exception

Sounds good. Would you like to submit a PR? It should come with a test. I see we have [test_cross1d](https://github.com/numpy/numpy/blob/60bd99b28b614c0e7a4e28e8a1bdc3ae7858217f/numpy/core/tests/test_ufunc.py#L1191), maybe we should have a `test_cross0d` that uses something like
```
with raises(ValueError) as exc:
   ...
assert "nicer message" in str(exc.value)
```

**Comment by DhavalParmar61** [comment]
@mattip I have created a pull request to resolve the issue. For the test case, we can use the code as shown below.  We are not using unittest in test_numeric.py, so that is the issue. I tried to consider test_cross1d but that is confusing, So if you can provide more details I can try that.

import unittest

def broken_function():
    raise Exception('This is broken')

class MyTestCase(unittest.TestCase):
    def test(self):
        with self.assertRaises(Exception) as context:
            broken_function()

        self.assertTrue('This is broken' in context.exception)

**Comment by mattip** [comment]
We use pytest. You can grep the codebase for examples of its use:
```
arg0d = ...
arg2d = ...
with pytest.raises(ValueError) as exc:
   np.cross(arg0d, arg2d)
assert "nicer message" in str(exc.value)
```

**Comment by DhavalParmar61** [comment]
@mattip New open pull request now takes care of everything related to this issue.

**Comment by DhavalParmar61** [comment]
Close?
