### ISSUE TITLE
ENH: add function to generate hyperbolic secant variates

### ISSUE THREAD

**Issue by Beliavsky** [numpy/numpy#24070]
### Proposed new feature or change:

I request that numpy.random.hyperbolic_secant be added, generating variates from that distribution https://en.wikipedia.org/wiki/Hyperbolic_secant_distribution.  Since the inverse CDF has a simple form, it would be fairly easy to implement. The hyperbolic secant distribution is smooth, symmetric, and unimodal, like the normal distribution, but it has exp(-|x|) tails that are thicker than those of the normal. It resembles the logistic distribution in that way but has excess kurtosis of 2, while the logistic has kurtosis of 1.2.

**Comment by WarrenWeckesser** [comment]
FYI: The hyperbolic secant distibution is implemented in SciPy as [`hypsecant`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.hypsecant.html).  You can use the `rvs()` method of `hypsecant` to generate random variates.

**Comment by rkern** [comment]
As a general matter of policy, we try not to add more continuous distributions like this to `np.random`, especially when they are easy to implement via inversion. The API is already somewhat overstuffed. Especially since this is already implemented in SciPy, I'm going to go ahead and close this.
