### ISSUE TITLE
BUG: Get X of very large Polynomial at Y using `roots`? (Python 3.8, NumPy)

### ISSUE THREAD

**Issue by SvarunSoda** [numpy/numpy#24104]
### Describe the issue:

I'm attempting to calculate all real X-values, at a certain Y-value, of a 20-degree polynomial provided in a coefficent list of ascending powers. I'm using Python 3.8 as well as the `roots` function of the NumPy library.

I attached a code example to this posting, in which I generate a 20-degree polynomial (stored in `coeffs`), and use the `roots` function in order to acquire all X-values (stored in `sols`), at a certain Y-value (stored in `y`). I subsequently filter out all the imaginary solutions, leaving only the real ones at the desired interval of `[0, 17]`, and I plot the plolynomial, alongside the desired Y-value and found real X-values. I colored the polynomial in `gray`, the desired Y-value in `blue` and all the filtered X-values in `red`.

In the included example, I attempt to acquire all real X-values at a the Y-value of `-5`. The X-values are listed as `[3.92, 1.34, 1.13]`, which is clearly incorrect according to the generated plot: 
![image](https://github.com/numpy/numpy/assets/95188575/c579788d-f37d-433a-af71-4f274af956e2)

According to the plot, the actual X-values for a Y-value of `-5` should be ~11.2 and ~16.

### Reproduce the code example:

```python
import numpy as np
import matplotlib.pyplot as plt

def main():
    # Declare 20-degree polynomial
    coeffs = np.array([0.028582380269090664, -11.07209382330515, 81.98886137780704, -231.55726577581814, 344.8963540923082, -312.0774305574022, 185.36300988588312, -75.58767327080196, 21.660357329823697, -4.380346453954649, 0.6125779086029393, -0.05524029639869697, 0.002489646479713822, 4.159253423505381e-05, -9.927184104751197e-06, 8.634292922740336e-08, 3.278890552085848e-08, -3.350925351280405e-10, -1.1510786631391544e-10, -2.3053456641329463e-13, 3.9927010006271344e-13, 8.499990550259627e-15, -1.2514130885401332e-15, -5.653183054629818e-17, 3.5580325101956145e-18, 2.634844330077943e-19, -1.2086461102288157e-20, -9.772155900613053e-22, 8.336597931160041e-23, -2.286862805703104e-24, 2.2638043801338818e-26], dtype = float)
    y = -5

    # Create polynomial data on interval (0, 17)
    polyDataX = np.linspace(0, 17)
    polyDataY = np.empty(shape = len(polyDataX), dtype = float)

    for i in range(len(polyDataX)):
        polyDataY[i] = 0

        for j in range(len(coeffs)):
            polyDataY[i] += coeffs[j] * pow(polyDataX[i], j)

    # Solve for all real solutions
    coeffs[-1] -= y
    sols = np.roots(coeffs).tolist()
    i = 0

    while (i < len(sols)):
        if (sols[i].imag != 0) or (sols[i].real < 0) or (sols[i].real > 17):
            del sols[i]
            i -= 1
        else:
            sols[i] = round(sols[i].real, 2)

        i += 1

    # Plot polynomial & solutions
    plt.xlim([0, 17])
    plt.ylim([-30, 30])
    plt.plot(polyDataX, polyDataY, color = "gray")
    plt.axhline(y, color = "blue")
    
    for sol in sols:
        plt.axvline(sol, color = "red")

    plt.title("Sols: " + str(sols))
    plt.show()
    plt.close()
    plt.clf()

if (__name__ == "__main__"):
    main()
```

### Runtime information:

`print(np.__version__)`: `1.20.1`
`print(sys.version)`: `3.8.8`

**Comment by Vi-Sa-Teja** [comment]
Do not get me wrong but I guess the problem is not with the bug but it is mathematical :
When you are calculating the roots of the function` f(x)(20 degree polynomial) = y` the roots of the equation are acquired with `y=0` not with `y=-5`(as the case with your piece of code), as we are already considering the `y=-5` while calcuating the coefficients.
So while calculating , the new equation would be `g(x) = f(x)-5 = 0` , so if you consider again the `y=-5` you are calculating the roots for `g(x)-5` , I hope you got my point.

**Comment by rkern** [comment]
Note the order of the coefficients. You have them switched between what goes into `np.roots()` (where the last entry is the constant term) and how you've evaluated the polynomial (where the first one is the constant term). If you've evaluated the polynomial the way you want, then you need to be sure to subtract off `y` from the first entry and then pass in the reversed array to `np.roots()`.
