### ISSUE TITLE
BUG: linalg.inv function changes after version 1.24

### ISSUE THREAD

**Issue by aando21** [numpy/numpy#24132]
### Describe the issue:

The inverse matrix function has changed the output after the version 1.24
When applying the linalg.inv() function to the following 8x8 matrix:
![image](https://github.com/numpy/numpy/assets/71491273/7f6bd08b-40cf-4d1e-bb47-ee5db8a54e1f)

I got different results when upgrading numpy to version 1.24.*

on numpy 1.23:
![image](https://github.com/numpy/numpy/assets/71491273/afb2af39-21ad-48b0-98c0-924eea93e170)

on numpy 1.24:
![image](https://github.com/numpy/numpy/assets/71491273/902698d1-1c71-471c-a07f-990da0f07a67)

When checking how scipy did, even though it was a bit different it was a lot more similar result to numpy 1.23 output.

### Reproduce the code example:

```python
import numpy as np

matrix = [[113611323.18455547, 749.0174296066249, 749.0174296066249, 12263.417695652173, -1814.1334472049655, -950.0124596273292, -2979.921370600415, -807.5851325051765], [749.0174296066249, 4.075621118012423, 4.075621118012423, 1.3644927536231883, -0.46532091097308476, -0.004554865424430601, 0.02215320910973103, -0.024534161490683274], [749.0174296066249, 4.075621118012423, 4.075621118012423, 1.3644927536231883, -0.46532091097308476, -0.004554865424430601, 0.02215320910973103, -0.024534161490683274], [12263.417695652173, 1.3644927536231883, 1.3644927536231883, 85.77246376811598, 20.036231884057976, -0.7855072463768117, -2.1565217391304348, -0.0014492753623185754], [-1814.1334472049655, -0.46532091097308476, -0.46532091097308476, 20.036231884057976, 90.64699792960664, 1.1055900621118022, 3.3540372670807423, 0.2515527950310559], [-950.0124596273292, -0.004554865424430601, -0.004554865424430601, -0.7855072463768117, 1.1055900621118022, 1.382194616977226, 4.131262939958592, -0.3316770186335406], [-2979.921370600415, 0.02215320910973103, 0.02215320910973103, -2.1565217391304348, 3.3540372670807423, 4.131262939958592, 12.88530020703933, -0.9540372670807461], [-807.5851325051765, -0.024534161490683274, -0.024534161490683274, -0.0014492753623185754, 0.2515527950310559, -0.3316770186335406, -0.9540372670807461, 0.46149068322981424]]
np_matrix = np.array([np.array(xi) for xi in matrix])
np.linalg.inv(np_matrix)
```

### Runtime information:

for version 1.23.4:
1.23.5
3.9.0 (default, Nov 15 2020, 08:30:55) [MSC v.1916 64 bit (AMD64)]

for version 1.24.4:
1.24.4
3.9.16 (main, May 17 2023, 17:49:16) [MSC v.1916 64 bit (AMD64)]
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}},
 {'architecture': 'SkylakeX',
  'filepath': 'C:\\Users\\AlbertoYoshiyukiAndo\\anaconda3\\envs\\test-tabular-new\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'},
 {'filepath': 'C:\\Users\\AlbertoYoshiyukiAndo\\anaconda3\\envs\\test-tabular-new\\Lib\\site-packages\\sklearn\\.libs\\vcomp140.dll',
  'internal_api': 'openmp',
  'num_threads': 8,
  'prefix': 'vcomp',
  'user_api': 'openmp',
  'version': None},
 {'architecture': 'SkylakeX',
  'filepath': 'C:\\Users\\AlbertoYoshiyukiAndo\\anaconda3\\envs\\test-tabular-new\\Lib\\site-packages\\scipy.libs\\libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0-c2315440d6b6cef5037bad648efc8c59.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21.dev'}]
None

**Comment by rkern** [comment]
```
>>> np.linalg.cond(np_matrix)
9.246032984503929e+22
```

This matrix has a very high [condition number](https://en.wikipedia.org/wiki/Condition_number), about `9e22`. That means that basically no digits are expected to be accurate. Changes to the underlying BLAS/LAPACK might reorder the floating point operations in valid ways and cause minor changes to the computations. Because your problem is so ill-conditioned, those minor changes blow up to look very large to your results. But those changes are no more than what you should expect from this problem. Both answers are valid floating point results for this problem.
