### ISSUE TITLE
BUG: numpy.uint128+ not defined alocation dinamic of memory in user time

### ISSUE THREAD

**Issue by ilixindri** [numpy/numpy#24139]
### Describe the issue:

# My code than not run.
```python
import numpy as np
def randint_large(start, end):
    random_int = np.random.randint(start, end, dtype=np.uint128)
    return random_int
start = 0x0
end = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
random_subset = ''.join(chr(int(hex(randint_large(start, end)), 16)) for _ in range(25))
print(random_subset)
```

### Reproduce the code example:

```python
import numpy as np
start = 0x0
end = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
random_int = np.random.randint(start, end, dtype=np.uint128)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/workspaces/Drafts/myproblem.py", line 4, in <module>
    random_int = np.random.randint(start, end, dtype=np.uint128)
  File "/home/codespace/.local/lib/python3.10/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'uint128'. Did you mean: 'uint16'?
```

### Runtime information:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX'],
                      'not_found': ['AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'SkylakeX',
  'filepath': '/home/codespace/.local/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 2,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None

### Context for the issue:

Generate Random Unicodes.

**Comment by mattip** [comment]
What is unclear about the error message? NumPy does not have `int128` nor `uint128`.

**Comment by ilixindri** [comment]
The message is clear!

**Comment by ilixindri** [comment]
Get to me the implement.

**Comment by ilixindri** [comment]
I need reimplements ~python.chr to accept int128+ as def.
