### ISSUE TITLE
DOC: Possible grammatical error

### ISSUE THREAD

**Issue by patient74** [numpy/numpy#24140]
### Issue with current documentation:

In the section [How to convert a 1D array into a 2D array (how to add a new axis to an array)](https://numpy.org/devdocs/user/absolute_beginners.html#how-to-convert-a-1d-array-into-a-2d-array-how-to-add-a-new-axis-to-an-array) which describes the use of  `np.newaxis` the text 
 
"You can explicitly convert a 1D array `with` either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension: "
 
I think "with" should be replaced by "to".

### Idea or request for content:

In the text,

"You can explicitly convert a 1D array `with` either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension: "

Replace "with" by "to".

**Comment by ngoldbaum** [comment]
I agree, please feel free to submit a pull request. This text lives in `doc/source/user/absolute_beginners.rst`.

**Comment by patient74** [comment]
Thanks! I submitted a pull request
