### ISSUE TITLE
BUG: <Please write a comprehensive title after the 'BUG: ' prefix>

### ISSUE THREAD

**Issue by Kingxudong** [numpy/numpy#24165]
### Describe the issue:

When numpy.argsort is used for sorting, unintelligible results occur for sorting with many duplicate values?Why is that? Is there any remedy？

### Reproduce the code example:

```python
>>> import numpy as np
>>> a=[68,69,70,70,70,71,71,71,71,71,71,71,71,72,72,72,72,72,72,72,72,72,72,72]
>>> b=np.argsort(a)
>>> b
array([ 0,  1,  2,  3,  4, 12, 10,  9, 11,  7,  6,  5,  8, 22, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 23])
```

### Error message:

```shell
Incorrect output
```

### Runtime information:

1

### Context for the issue:

>>> import numpy as np
>>> a=[68,69,70,70,70,71,71,71,71,71,71,71,71,72,72,72,72,72,72,72,72,72,72,72]
>>> b=np.argsort(a)
>>> b
array([ 0,  1,  2,  3,  4, 12, 10,  9, 11,  7,  6,  5,  8, 22, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 23])

**Comment by charris** [comment]
You need to use a stable sort (`kind='stable'`). Argsorts are correct as long as they sort the data.
