### ISSUE TITLE
np.concatenate()

### ISSUE THREAD

**Issue by minfei1998** [numpy/numpy#24169]
### Describe the issue:

Can it be directly spliced without duplicating the data? When the splicing data is too large, the system memory is not enough.

### Reproduce the code example:

```python
np.concatenate()
```

### Runtime information:

np.concatenate()

**Comment by rkern** [comment]
In general, no. `numpy.ndarray` objects have a [very specific memory model](https://numpy.org/doc/1.21/reference/internals.html#internal-organization-of-numpy-arrays) that does not accommodate the kind of splicing that you are asking for.
