### ISSUE TITLE
BUG: `array2string` does not add signs for positive integers

### ISSUE THREAD

**Issue by dan-oak** [numpy/numpy#24181]
### Describe the issue:

`array2string` doesn't add signs for 0 and positive integers, when it works as documentation states for float without issues

### Reproduce the code example:

```python
import numpy as np
arr = np.array([-2, 0, 3])
print(np.array2string(arr, sign='+'))
print(np.array2string(arr.astype(float), sign='+'))

# output:
# [-2  0  3]
# [-2. +0. +3.]
```

### Runtime information:

3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]

**Comment by paulreece** [comment]
After spending a couple hours working on this, I read the [docs](https://numpy.org/doc/stable/reference/generated/numpy.array2string.html) and realized it actually is working as expected. I would suggest changing this to an Enhancement.

>**sign : string, either ‘-’, ‘+’, or ‘ ‘, optional**
Controls printing of the sign of floating-point types. If ‘+’, always print the sign of positive values. If ‘ ‘, always prints a space (whitespace character) in the sign position of positive values. If ‘-’, omit the sign character of positive values. Defaults to numpy.get_printoptions()['sign'].

**Comment by mohammedouahman** [comment]
Review the solution on #24190

**Comment by paulreece** [comment]
@charris I have submitted a solution that passes all current tests(including one I added for this) and uses the conventions set Forth in `FloatingFormat`. Thanks for your time and for taking a look. The PR is [#24191](https://github.com/numpy/numpy/pull/24191)
