### ISSUE TITLE
BUG: Build fail on Fedora

### ISSUE THREAD

**Issue by r-devulap** [numpy/numpy#24195]
### Describe the issue:

Commit 12d0df7b7e3cb7c5fb9512d4c9b56be04047b12d in PR #24006 adds a check to determine binutils version. The function fails on Fedora: 

```
can_link_svml_fp16
    return float(binutils_ver) >= 2.38
ValueError: could not convert string to float: 'GNU ld version 2.37-37.fc36
```

### Reproduce the code example:

```python
python setup.py build
```

### Runtime information:

its a build issue.

**Comment by r-devulap** [comment]
I will add a fix for it, just filing an issue to track it.

**Comment by charris** [comment]
Note that I fixed this in `numpy/core/setup.py` for NumPy 1.26.2.

**Comment by r-devulap** [comment]
Closing, this is irrelevant now.
