### ISSUE TITLE
BUG: Typo in TypeError of `np.pad`

### ISSUE THREAD

**Issue by mocquin** [numpy/numpy#24215]
### Describe the issue:

There is a typo regarding the TypeError message when the inputs of `np.pad` are not integers, the message states "integral" type instead of "integer" type. 
See : 
https://github.com/numpy/numpy/blob/dabb12ec5c27846b1ded065b5e61eabb89d029ed/numpy/lib/arraypad.py#L745C49-L745C58

There is : 
```python
if not pad_width.dtype.kind == 'i':
    raise TypeError('`pad_width` must be of integral type.')
```
I'd expect : 
```python
if not pad_width.dtype.kind == 'i':
    raise TypeError('`pad_width` must be of integer type.')
```

### Reproduce the code example:

```python
import numpy as np
np.pad([0, 1], ((0, 1.0)))
```

### Error message:

```shell
TypeError: `pad_width` must be of integral type.
```

### Runtime information:

1.21.5
3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]

**Comment by Kai-Striega** [comment]
I don't think this is a typo. `integral` refers to the class of possible integer types. E.g. - in C - all of `char`, `short`, `int` and `long` are integral types. See this for a quick summary (https://www.cs.auckland.ac.nz/references/unix/digital/AQTLTBTE/DOCU_032.HTM)

**Comment by seberg** [comment]
Closing, if someone wants to improve it, just create a PR directly, since there is nothing wrong.
