### ISSUE TITLE
ENH: support no-copy pickling for non-contiguous arrays, e.g., recarray

### ISSUE THREAD

**Issue by dlee992** [numpy/numpy#24226]
### Proposed new feature or change:

Following this issue https://github.com/numpy/numpy/issues/11161 and related PR, can we support no-copy pickling for recarray, which is a subclass of ndarray? I think right now we don't support this feature, since recarray is non-contiguous arrays.

If it's possible in your experienced view, I guess we need to do some changes in numpy/core/src/multiarray/methods.c and related tests.

Example is here: https://github.com/ray-project/ray/issues/37573#issuecomment-1645340685. I can make up a version without Ray later.

And I saw a demo for how to handle pd DataFrame https://github.com/numpy/numpy/pull/12011#issuecomment-428915852, don't know if we can have a local trick for recarray too.

**Comment by seberg** [comment]
Yes, you can probably do that, not sure what the rules are around non-contiguous buffers for pickling.  But your examples are contiguous, the problem is just that it is an array subclass and that doesn't go down the buffer pickling path.  Not sure there is actually a good reason for that.

**Comment by dlee992** [comment]
close it for now I think.
