### ISSUE TITLE
question: <numpy.arange>

### ISSUE THREAD

**Issue by chentryto1** [numpy/numpy#24246]
### Describe the issue:

My version of numpy is numpy 1.23.5, python version is 3.8.16 

The result of this line of code includes the right boundary：np.arange(2.05,3.15 + 0.1 ,0.1)

result：array ( [ 2.05, 2.15, 2.25, 2.35, 2.45, 2.55, 2.65, 2.75, 2.85, 2.95, 3.05.
3.15, 3.25 ] )

Why does this happen？The default should not include the right boundary.

### Reproduce the code example:

```python
import numpy as np
np.arange(2.05,3.15 + 0.1 ,0.1)
```

### Runtime information:

1.24.3
3.8.16

**Comment by chentryto1** [comment]
result : array ( [ 2.05, 2.15, 2.25, 2.35, 2.45, 2.55, 2.65, 2.75, 2.85, 2.95, 3.05. 
3.15, 3.25 ] )

**Comment by mattip** [comment]
Welcome to the wonderful wacky world of floating point math on computers. The `arange` documentation [warns about this](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy-arange). 
> When using a non-integer step, such as 0.1, it is often better to use [numpy.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace)

and there is a more detailed description as well.

**Comment by rossbar** [comment]
Thanks @mattip , I will close as duplicate.
