### ISSUE TITLE
DOC: Example code is not returning what is expected

### ISSUE THREAD

**Issue by sc0v1n0** [numpy/numpy#24261]
### Issue with current documentation:

Good evening, I am studying the documentation of the rapid start. I'm not sure if the code below is correct.

![image](https://github.com/numpy/numpy/assets/56802572/21f4bc5b-26ad-4d55-b894-ca982ad4d7d8)

[Quick start](https://numpy.org/devdocs/user/quickstart.html)

![image](https://github.com/numpy/numpy/assets/56802572/129cc3ea-1ccb-44c6-adac-e662526a9737)
![image](https://github.com/numpy/numpy/assets/56802572/6609bbad-f330-426c-9a93-8919c23809d7)

I looked outside the documentation, found an alternative. But this example from the documentation didn't work.

**Comment by melissawm** [comment]
In this particular case, `rg` was defined just a few code blocks above, such that

```
rg = np.random.default_rng(1)
```

I believe this will solve your issue.

**Comment by Nitin-Gahlawat** [comment]
To generate random values using NumPy, we have to use the 'numpy.random.default_rng(seed)' before using random function. If we use the same seed value, we will get the same random value sequence. To generate a different sequence, we need to use a different seed value. An example is shown below.



![Screenshot 2023-07-26 143316](https://github.com/numpy/numpy/assets/101346709/6700f335-bae0-49da-854f-7c1f2e612111)

**Comment by sc0v1n0** [comment]
Good evening, thank you very much for your feedback. I apologize for my lack of attention, I'm following the quick start steps, it just stops recording.

**Comment by sc0v1n0** [comment]
@Nitin-Gahlawat Thank you very much for the example it helped a lot.
