### ISSUE TITLE
BUG: numpy creates N_CPU processes if launched in tmux

### ISSUE THREAD

**Issue by tbenst** [numpy/numpy#24264]
### Describe the issue:

If `import numpy` occurs from a terminal, then numpy creates no processes. If `import numpy` occurs within tmux, then numpy creates N_CPU processes (32 for me). This is highly unexpected behavior. Any idea why?

### Reproduce the code example:

```python
import numpy
from time import sleep

print("sleeping....")
sleep(10000)
exit(0)

# count the number of processes spawned by a process matching a pattern, in this case "2023-"
# watch -n 3 "for pid in \$(ps aux | grep 2023[-] | awk '{print \$2}'); do echo -n 'PID '\$pid': '; count=\$(pstree -p \$pid | grep -o '([[:digit:]]\+' | wc -l); echo \$((count)); done"
```

### Error message:

<img width="1482" alt="local-tmux-vs-terminal" src="https://github.com/numpy/numpy/assets/863327/d16e6833-2ab2-4039-ae75-62652e97260b">

### Runtime information:
```
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}},
 {'architecture': 'Cooperlake',
  'filepath': '/home/tyler/opt/anaconda/envs/gaddy/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 32,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None
```

**Comment by tbenst** [comment]
Also, when I run this script in a HPC environment (Stanford Sherlock), it always creates N_CPU processes, regardless of if `tmux` is used.

**Comment by mattip** [comment]
Those threads (not processes) are created by OpenBLAS, which is used underneath. There are a number of reasons OpenBLAS may not be starting threads:
- OpenBLAS is not being used
- Someone is telling OpenBLAS to [restrict itself to a lower number of threads](https://github.com/xianyi/OpenBLAS/wiki/faq#how-can-i-use-openblas-in-multi-threaded-applications)

I think tmux is masking some other environment changes between the different invocations.

**Comment by mattip** [comment]
Or your scripts are not doing what you think they are, I cannot really follow your workflow.

**Comment by seberg** [comment]
Without follow-up, I think Matti's points above are all information we can give/do, so closing for now.  Feel free to follow up after researching those points.

**Comment by tbenst** [comment]
Don't believe a numpy issue and thanks for the pointers.

I believe the cause was the same as bug in SLURM that relates to improperly setting CPU affinity to only CPU 0 when the `--cpus-per-gpu` flag is used (https://bugs.schedmd.com/show_bug.cgi?id=15632).
```
(base) [tbenst@sh03-ln07 login ~]$ srun  --cpus-per-gpu 4 --gpus 2 -t 1:00:00 --pty bash                                                                                                  
srun: job 25473695 queued and waiting for resources
srun: job 25473695 has been allocated resources
(base) [tbenst@sh03-13n11 ~] (job 25473695) $ python -c 'import os; print(os.sched_getaffinity(0))'
{0}
(base) [tbenst@sh03-13n11 ~] (job 25473695) $ exit
(base) [tbenst@sh03-ln07 login ~]$ srun  -c 4 --gpus 2 -t 1:00:00 --pty bash                                                                                                        
srun: job 25473756 queued and waiting for resources
srun: job 25473756 has been allocated resources
(base) [tbenst@sh03-13n11 ~] (job 25473756) $ python -c 'import os; print(os.sched_getaffinity(0))'
{0, 1, 2, 3}
```

Can also be prevented by `salloc` instead of `srun`.
