### ISSUE TITLE
BUG: Sort method for string numpy arrays

### ISSUE THREAD

**Issue by azrael05** [numpy/numpy#24275]
### Describe the issue:

This is an issue with the inbuilt Python lists also. When using sort on a list or numpy arrays it sorts according to the ASCII values in which Z comes before a. This might not be much of an issue in more cases which in case the arrays contain both small and capital letters this can result in unwanted results.

### Reproduce the code example:

```python
import numpy as np

test_array = np.array(["Alpha","beta","Gamma"])
print(test_array)
## Prints Alpha, beta, Gamma

test_array.sort()
print(test_array)
## Prints Alpha, Gamma, beta
```

### Runtime information:

1.25.0
3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]

### Context for the issue:

This can affect people who are working with textual data which has mixed cases of lowercase and capital letters.

**Comment by ngoldbaum** [comment]
What's really needed here is better support in NumPy (or a library that depends on NumPy) for unicode-aware text operations. If you don't care about the case of the items you're sorting, you could casefold them. In python, you'd do:

```python
>>> sorted(["Alpha","beta","Gamma"], key=str.casefold)
['Alpha', 'beta', 'Gamma']
```

However NumPy doesn't have support for case-folding arrays or a python callable as a key for sorting.

This is not something that's planned for NumPy in the immediate future but may be added eventually once support for strings in general improves (I'm actively working on that).

I'm not sure what your real workflow looks like and how deeply tied to NumPy it is, but you may have more luck for now using pure python if you need to do unicode-aware transformations of strings. I believe Pandas also has support for casefolding string and sorting with a key.

**Comment by seberg** [comment]
I am going to close this, could be reopened to ask for adding casefold, but there is no bug and there are probably more string functions one could add inside or outside of NumPy eventually.
