### ISSUE TITLE
NumPy 2.0 development status & announcements

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#24300]
The purpose of this issue is to serve as a brief "umbrella issue" which (a) links out to some key design proposals and other places where design changes and guidance for the 2.0 release are described, and (b) everyone who is interested can subscribe to in order to get updates from maintainers around the 2.0 release (not everyone may want to subscribe to the mailing list). This issue will remain pinned for high visibility.

The tentative release date for the first release candidate of NumPy 2.0 is around 1 Mar 2024, and the final release 6-8 weeks later.

_EDIT: this issue is for announcements, please do not start technical discussions here_

**Design changes / proposals**

- NumPy 2.0 Project Board: https://github.com/orgs/numpy/projects/9
- Main NumPy Enhancement Proposals for 2.0:

    - [NEP 53 - Evolving the NumPy C-API for NumPy 2.0](https://numpy.org/neps/nep-0053-c-abi-evolution.html)
    - [NEP 52 - Python API cleanup for NumPy 2.0](https://numpy.org/neps/nep-0052-python-api-cleanup.html)
    - [NEP 50 - Promotion rules for Python scalars](https://numpy.org/neps/nep-0050-scalar-promotion.html)

- Slides from the NumPy 2.0 Developer Meeting in April'23: https://github.com/numpy/archive/tree/main/2.0_developer_meeting

**Key guidance for users and downstream package authors**

1. Please review the [2.0 migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html). And for a more detailed overview of changes, please see [the 2.0.0 release notes](https://numpy.org/devdocs/release/2.0.0-notes.html)
2. If you rely on the NumPy C API (e.g. via direct use in C/C++, or via Cython code that uses NumPy), please add a `numpy<2.0` requirement in your package's dependency metadata (for releases only, not on your main dev branch). _Rationale: the NumPy C ABI will change in 2.0, so any compiled extension modules that rely on NumPy are likely to break, they need to be recompiled._
3. If you rely on a large API surface from NumPy's Python API, also consider adding the same ` numpy<2.0` requirement to your metadata. _Rationale: we will do a significant cleanup (see NEP 52), so unless you only use modern/recommended functions and object, your code is likely to require at least some adjustments._
4. Consider cleaning up your code. E.g. remove `from numpy import *`, or importing any private modules like `numpy.core`. See https://github.com/numpy/numpy/blob/main/numpy/tests/test_public_api.py#L114-L126 for what we consider public/private. If it's not in the NumPy docs or in the list of public modules there, don't use it!
5. Plan to do a release of your own packages which depend on `numpy` shortly after the first NumPy 2.0 release candidate is released (probably in Dec 2023). _Rationale: at that point, you can release packages that will work with both 2.0 and 1.X, and hence your own end users will not be seeing much/any disruption (you want `pip install mypacackage` to continue working on the day NumPy 2.0 is released)._
6. Consider testing against NumPy nightlies in your own CI. We publish those at https://anaconda.org/scientific-python-nightly-wheels/numpy, and have documented that as a stable location at https://numpy.org/devdocs/dev/depending_on_numpy.html. _Rationale: this will detect potential issues in your code so you can fix them well ahead of the NumPy 2.0 release_.

**Compatibility status of downstream packages**

See https://github.com/numpy/numpy/issues/26191

**Comment by rgommers** [comment]
It depends on whether those scipy nightlies will then be ABI-compatible with both numpy 2.0-dev and with 1.25.x. That is the plan for the final 2.0 release, but will it be the case during the development cycle @seberg?

**Comment by seberg** [comment]
Yes, of course they will be ABI compliant to both.  I am not really planning on a compat package anymore anyway, I suspect we have few enough things that a few header-only functions are sufficient (and *far* easier to manage).

**Comment by andyfaff** [comment]
e.g. at the moment the scipy pyproject.toml file will want to build against `numpy==1.22.4` for Python 3.10 wheels, that's what the last scipy would've been built against. If we start making wheels against `numpy>=2.0` then I think, but am not sure, that the numpy versionw in pyproject.toml would need to be bumped to the oldest ABI compatible version (1.25.2?).

I know how to amend the build process, but am not sure how to amend the metadata (oldest-supported-numpy as well?) so that we don't get a raft of complaints from people using too old a version of numpy.

**Comment by seberg** [comment]
You don't need `oldest-supported-numpy` anymore (since 1.25.x) unless you need it for things beyond being compatible with older NumPy versions.

**Comment by rgommers** [comment]
Great, then in the nightlies we can just use an unpinned `numpy` build requirement, and install numpy from the scientific-python nightlies bucket, that should work fine.

**Comment by rgommers** [comment]
@andyfaff that'd be a change that is fine to make in SciPy's `main` branch. There are already notes in `pyproject.toml` about this topic. 

This is a pretty detailed discussion for this tracking issue. How about we leave it here at "SciPy nightlies will switch to building against NumPy nightlies soon" and then circle back here once that works to recommend other projects do the same?

**Comment by jakirkham** [comment]
Following up on the discussion above, are there now SciPy nightlies being built with NumPy 2? If so, how would one get them? If not, do we have a sense of when they might be available?

**Comment by andyfaff** [comment]
@jakirkham yes, the scipy nightlies are being built against `numpy>=2.0.0.dev0`. They are available from https://anaconda.org/scientific-python-nightly-wheels/scipy/files.

**Comment by EwoutH** [comment]
> Plan to do a release of your own packages which depend on numpy shortly after the first NumPy 2.0 release candidate is released (probably in Dec 2023).

Would it be useful to do a bit more extensive pre-release schedule than with a regular (minor) NumPy release? Maybe alpha builds every 2 or 3 weeks starting soon, then a month or two ahead every week a beta, and then the last week release candidates.

Since it's such a large release it would be nice being able to test extensively against pre-releases, and having a bit more time for that. It would also engage other communities and maintainers which could offer valuable perspectives before the final release is made.

**Comment by andyfaff** [comment]
There are regular nightly builds which should aid in prerelease testing

**Comment by EwoutH** [comment]
> There are regular nightly builds which should aid in prerelease testing

Agreed, I think there is additional value for "formal" pre-releases, which are published on GitHub and PyPI, can be installed with `pip install numpy --pre`, and feedback can be delivered on. It gives a concrete and easy targets to install and test against.

**Comment by rgommers** [comment]
An update on timeline: there are ~6 topics on the roadmap that still require time and are important to get in for 2.0. At the community meeting two days ago we discussed that we'll likely need another 2 months or so to get those all done and are therefore targeting a first release candidate around the end of the year. The period from RC to final release is at least 6 weeks as usual, but it's possible that that will stretch out more - that depends on how many issues get reported.

**Comment by thomasjpfan** [comment]
I agree with adjusting the pinning recommendation from https://github.com/numpy/numpy/issues/24300#issuecomment-1770748369. In https://github.com/scikit-learn/scikit-learn/pull/27899, scikit-learn needed to explicit install NumPy 2.0 from the nightly index because pandas had `numpy<2.0` on the dev branch.

**Comment by rgommers** [comment]
`numpy<=2.0.0.dev0` in released versions of downstream packages does not make sense to me. We have already broken ABI and API pretty substantially, so if a package builds against 1.2X and then pick up the latest `2.0.0.dev0` that will not work.

> Only release versions should have an upper version pin (unless you know its broken). 
. ...
> because pandas had `numpy<2.0` on the dev branch.

Agreed. It seems like this needs a "for releases only" addition - adding now. That was clearly intended, one should never pin anything on their main branch unless there is a known source-level incompatibility.

**Comment by braingram** [comment]
Thanks all for your hard work on this. Should
> The tentative release date for NumPy 2.0 is end of December 2023.

be updated based on https://github.com/numpy/numpy/issues/24300#issuecomment-1783511140 to state that the first RC will be end of Dec with the release expected in early Feb 2023?

**Comment by rgommers** [comment]
Thanks @braingram, updated now.

**Comment by rgommers** [comment]
Hi all, one more update on timing. We just reviewed all the remaining work items that are deemed important for NumPy 2.0 in the community meeting - they're all in progress or close to the finish line and we're reasonably confident that in one month from now they'll all be done and we can have the first release candidate at the end of January. So this moves the timeline by 1 month.

**Comment by jakevdp** [comment]
Hi @rgommers – I'm having trouble squaring the advice here

> at that point, you can release packages that will work with both 2.0 and 1.X, and hence your own end users will not be seeing much/any disruption (you want pip install mypacackage to continue working on the day NumPy 2.0 is released).

... with the general documentation on ABI compatibility (from http://google3/third_party/py/ml_dtypes/oss/.github/workflows/test.yml;l=64-73;rcl=592609686)

> If a package either uses the NumPy C API directly or it uses some other tool that depends on it like Cython or Pythran, NumPy is a build-time dependency of the package. Because the NumPy ABI is only forward compatible, you must build your own binaries (wheels or other package formats) against the lowest NumPy version that you support (or an even older version).

My experience so far is that if packages are built against 1.X, they don't work with numpy nightly wheels because of ABI compatibility. But if I build against 2.X, the Build-time dependency docs suggest that the wheels won't work with numpy 1.X at runtime.

How should downstream package authors plan to build wheels for release in a future world where NumPy 1.X and 2.X are actively being used?

**Comment by rgommers** [comment]
> My experience so far is that if packages are built against 1.X, they don't work with numpy nightly wheels because of a hard-coded ABI version check.

Yes, this will not work indeed.

> But if I build against 2.X, the Build-time dependency docs quoted above suggest that we shouldn't expect the result to be compatible with numpy 1.X at runtime.

(could you update the link? it goes to something private)

The summary here is:
- This has always been true, _however_ there was a change in NumPy 1.25 where the _exported_ C API is no longer that for the current NumPy version but a much older one (1.19), so things got better compat wise.
- In addition, 2.0 has a compat shim that bridges the ABI differences, in order to make wheels built against 2.0 also work with 1.X by default. 

> How should downstream package authors plan to build wheels for release to ensure compatibility with both NumPy 2.0 and NumPy 1.X?

Build against 2.0 after the ABI-stable 2.0.0rc1 arrives, and declare a runtime dependency of >=1.2x.y (any x.y here should work).

**Comment by jakevdp** [comment]
Link updated, sorry about that

**Comment by rgommers** [comment]
https://numpy.org/doc/1.26/dev/depending_on_numpy.html#build-time-dependency should have more info on the "exported C API version" topic already than those 1.21 docs. 

The 2.0 compat thing isn't anywhere yet except for in this issue I think. We should add it to that same "for downstream distributors" page, and then link it from https://numpy.org/devdocs/numpy_2_0_migration_guide.html.

**Comment by jakevdp** [comment]
Ah, thanks. I just found the 1.21 docs via google search; I hadn't seen the 1.26 update.

**Comment by bashtage** [comment]
Is there any documentation about how to publish NumPy 2 wheels for downstream packages.  As I understand things, packages might need 2 versions - 1 for NumPy <= 1.99 and a second for NumPy >= 2, for each version/ABI supported on PyPI.  Will this be possible?

**Comment by rgommers** [comment]
> it sounds like any build against NumPy 2 will also work on NumPy >= 1.20.x, 

Indeed - and it has to be that way (it's not possible to upload two wheels where the only difference is the numpy version used during the build). No docs yet though, we should fix that before RC1 comes out.

**Comment by seberg** [comment]
It's been documented since 1.25: https://numpy.org/doc/stable/dev/depending_on_numpy.html#build-time-dependency
Maybe you think it should be clarified, otherwise it should just be mentioned again in the release notes wherever it says that you must compile with 2.0.

**Comment by rgommers** [comment]
> It's been documented since 1.25:

All it says is: _"At the time of NumPy 1.25, NumPy 2.0 is expected to be the next release of NumPy. The NumPy 2.0 release is expected to require a different pin, since NumPy 2+ will be needed in order to be compatible with both NumPy 1.x and 2.x."_ That is a bit too sparse, as the questions here highlight. I just opened gh-25512 to add more extensive 2.0-specific docs.

**Comment by bashtage** [comment]
@rgommers Thanks for the write up.  I suppose there is another important practical issue for downstream supporting NumPy 2. 

Suppose a project depends on some mid-stream projects, e.g., `statsmodels -> pandas, scipy -> numpy`.  statsmodels can only really support NumPy 2 if it is running on pandas and scipy that also support numpy 2.  While I haven't seen any plans, I suspect that this will mean that the minimums for the mid-stream projects will be whatever is released after NumPy 2 is GA.  This makes it seem like there is practically 1 set of requirements for NumPy 1 and a different one for NumPy 2.  Is there any practical way to enforce this? 

I think if all projects where capped, e.g., `numpy>=1.xx.0,<2` than it would work fine, since only those that explicitly remove the cap could be used with .  However, with lots of versions missing caps it seems less easy.

**Comment by rgommers** [comment]
> I suspect that this will mean that the minimums for the mid-stream projects will be whatever is released after NumPy 2 is GA. This makes it seem like there is practically 1 set of requirements for NumPy 1 and a different one for NumPy 2. Is there any practical way to enforce this?

I don't think that needs to be the case - and we certainly wouldn't want to enforce this (rather the opposite, we tried hard not to make this kind of a split).

> However, with lots of versions missing caps it seems less easy.

This isn't a necessary requirement - all you need is the most recent pre-2.0-compatible version to contain a `<2` cap. Reason: if a user does `pip install statsmodels` now, they get numpy 1.xx for any version of `pandas`. If they do `pip install statsmodels` and statsmodels has something like `pandas >1.4; scipy >1.8` as requirements, then that won't go wrong - they'll still get the newest versions of everything.

The only thing that can go wrong with missing caps for older versions is if users explicitly do things like `pip install statsmodels "pandas==1.4"`. That may then pull in `numpy` 2.0 and that breaks. But it's break with a clean error message about a numpy version mismatch, and can then easily be remedied by the user (upgrade pandas, or downgrade numpy).

We probably do need to pay some attention to the help page users will find from the ABI mismatch error message, that will get some traffic.

**Comment by seberg** [comment]
> We probably do need to pay some attention to the help page users will find from the ABI mismatch error message, that will get some traffic.

Right, there should be a clear place to google for that tells you to downgrade NumPy or try upgrading the dependency (I am not quite sure when it is useful, but saw an example where `python -v` import tracing was needed to see which module was compiled with the wrong version).

Otherwise, I think this is a non-issue beyond users accidentally creating bad combinations as Ralf said.  Unless you hae to *build* against the oldest supported intermediate package (i.e. like we used to force you to build with the oldest NumPy you want to support)?

**Comment by bashtage** [comment]
Am I correct the the recommendation for numpy 2 compatibility releases would to be remove the build dependency on `oldest-supported-numpy`?

**Comment by rgommers** [comment]
Yes indeed, dropping that - I'll update the README of `oldest-supported-numpy` with a prominent note.

> and to replace with a dependency on `numpy~=2.0.0`?

No, that is too restrictive (it means `>=2.0.0,<2.1`. The upper bound, if used at all, should be `<3` or `<2.3`.

**Comment by rgommers** [comment]
Full deprecation notice for `oldest-supported-numpy` at https://github.com/scipy/oldest-supported-numpy/pull/84 (comments there very welcome).

**Comment by jorisvandenbossche** [comment]
FWIW, the top post links to https://numpy.org/neps/nep-0053-c-abi-evolution.html, which is a bit out of date (I started looking at that instead of the more update to date documentation ..). For example it still mentions a ``numpy2_compat`` package (I don't know if you want to update NEPs after the fact, but otherwise a disclaimer that not everything is up to date might help)

**Comment by seberg** [comment]
Arg, you are right, need to add at least add a note that the `numpy2_compat` thought is descoped (not sure how much for a full rewrite I am up to, especially short term unfortunately).

**Comment by jorisvandenbossche** [comment]
Question for downstream packages releasing more or less now: the general guideline given above is to start releasing wheels (not nightly wheels) built against numpy 2.0 once the first release candidate is out. 
That means that a package is that released this month should still build against numpy 1.x and add the `numpy<2` upper pin. But do you know if there are still changes planned that will break the ABI the coming weeks? Or might it already be generally safe to actually release a numpy-2-built wheel right now?

**Comment by rgommers** [comment]
> But do you know if there are still changes planned that will break the ABI the coming weeks? Or might it already be generally safe to actually release a numpy-2-built wheel right now?

I believe one or two breaks are still planned. So best to stay with 1.x for now.

**Comment by rgommers** [comment]
Hi all, quick update: we're going to need slightly more time, but the finish line is in sight. In today's community meeting we went through the O(10) items still open for the [2.0.0 milestone](https://github.com/numpy/numpy/milestone/118) and concluded that there's only a couple of blocking items left (primarily two necessary C API changes, and one NEP 56 item). These are planned to be completed within the next two weeks, so we should see `2.0.0rc1` in 2-3 weeks from now.

**Comment by glemaitre** [comment]
We are currently releasing scikit-learn and are looking at the transition to NumPy 2.0.

@rgommers we were wondering if in the release process of NumPy, it is conceivable for NumPy to release a last RC that would be the same as 2.0.0 and provide a week for us (and the downstream packages) to build against it. We ensure in this case to not have any downtime and avoid a potential corner case that we saw below.

In our previous release, we pin `numpy < 2` but we realized a corner case: if something trigger the following `pip install numpy==2.0 scikit-learn`, then `pip` would end up trying to install an old version of scikit-learn that does not have the pin and that is not compatible as well.

**Comment by rgommers** [comment]
> release a last RC that would be the same as 2.0.0 and provide a week for us (and the downstream packages) to build against it.

Yes, we'll leave more than enough time and won't do the final 2.0.0 release until at least all the most widely used libraries like scikit-learn, pandas, scipy, etc. are compatible. Otherwise things will turn into a mess indeed.

The regular time period from a numpy RC to the final release is a month or more; I think we'll have 6 weeks at minimum between RC1 and final release (perhaps more depending on how downstream releases go).

**Comment by rgommers** [comment]
> In our previous release, we pin `numpy < 2` but we realized a corner case: if something trigger the following `pip install numpy==2.0 scikit-learn`, then `pip` would end up trying to install an old version of scikit-learn that does not have the pin and that is not compatible as well.

Yes, `pip` selecting older versions is obviously problematic, but getting that changed is being discussed since forever and I don't see it landing any time soon.

Scikit-learn really should always put an upper bound on numpy, not doing so is clearly wrong. Your 2.0-compatible release should either use `<2.x+N` or `<3` (see https://numpy.org/devdocs/dev/depending_on_numpy.html#runtime-dependency-version-ranges). Major NumPy releases are ABI breaks, so not using at least `<3` will set you up for the same problem in case we'd get a numpy 3.0 in a few years (may not happen, but who knows). Given how much you use of the NumPy API, I'd strongly recommend using the `<2.x+N` rule (with N=3).

**Comment by glemaitre** [comment]
> Major NumPy releases are ABI breaks, so not using at least <3 will set you up for the same problem in case we'd get a numpy 3.0 in a few years (may not happen, but who knows). Given how much you use of the NumPy API, I'd strongly recommend using the <2.x+N rule (with N=3).

Thanks. Point taken. I'll bring up on the table to be discussed on our side. This looks reasonable to me.

**Comment by rgommers** [comment]
> These are planned to be completed within the next two weeks, so we should see `2.0.0rc1` in 2-3 weeks from now.

Sorry folks, looks like that was slightly optimistic, we need another similar amount of time. The last bits turned out to be a little larger than expected. We will get there soon!

**Comment by rgommers** [comment]
The `maintenance/2.0.x` branch has been created, so we're almost there - beta 1 will arrive without hours to days. I'll re-post from the mailing list:

Let me give the optimistic and pessimistic timelines. Optimistic:

- 2.0.0b1 later today
- 2.0.0rc1 (ABI stable) in 7-10 days
- 2.0.0 final release in 1 month

Pessimistic:

- 2.0.0b1 within a few days
- 2.0.0rc1 (ABI stable) in 2 weeks
- 2.0.0rc2 in 4 weeks
- 2.0.0rc3 in 6 weeks
- 2.0.0 final release in 8 weeks

For projects which have nontrivial usage of the NumPy API (and especially if they also use the C API), I'd recommend:
1. Check whether things work with 2.0.0b1, ideally asap so if there is anything we missed we can catch it before rc1. Perhaps do a pre-release of your own package
2. Do a final release after 2.0.0rc1 - ideally as soon as possible after, and definitely before the final 2.0.0 release

For (2), note that there are a ton of packages that do not have correct upper bounds, so if you haven't done your own new release that is compatible with both 2.0.0 and 1.26.x *before* 2.0.0 comes out, the users of your project are likely to have a hard time.

**Comment by keltonhalbert** [comment]
Apologies if this is the incorrect place to ask - I perused around the documentation and issues and haven't seen it mentioned, but didn't want to open up an entire issue based on this. If it is preferable to take this somewhere else, kindly let me know and I'll happily delete this and relocate it. 

Is there currently any sense on whether or not the breaking changes, especially those in the C-API, will affect the numpy SWIG interface compatibility? Or should it continue to work as expected? I understand the binary compatibility will be broken, which is fine, just trying to anticipate impacts to C and C++ libraries that leverage SWIG as a bridge to numpy.

**Comment by rgommers** [comment]
Hi @keltonhalbert, great question. I'm fairly sure that the SWIG interface is completely untested inside this repo. A quick search doesn't turn up usage of removed C API for me, but I wouldn't be surprised if for example the `long` -> `intp` default integer change requires a tweak to `tools/swig/numpy.i`. It'd be great if you could check your code with `2.0.0b1` and see if it works.

> If it is preferable to take this somewhere else, kindly let me know and I'll happily delete this and relocate it.

New issues are preferable to commenting on this one, since this is an announcement issue. If you find anything in SWIG support isn't working, could you please open a new issue?

**Comment by keltonhalbert** [comment]
Hi @rgommers, 

Thank you for the quick response and clarity on how to handle any potential issues further. I'll try building with 2.0.0b1 and open a new issue if anything starts to go sideways. 

Also, a preliminary congrats on the forthcoming milestone release. I appreciate the work you all put into developing and maintaining this library!

**Comment by jakirkham** [comment]
In conda-forge, `2.0.0rc1` is now packaged ( https://github.com/conda-forge/numpy-feedstock/issues/311 ) ( https://github.com/conda-forge/numpy-feedstock/pull/312 ), which can be installed via `conda install conda-forge/label/numpy_dev::numpy=2.0.0rc1`

Looks like there are [`2.0.0rc1` wheels on PyPI]( https://pypi.org/project/numpy/2.0.0rc1/#files ), which are installable via `python -m pip install --pre numpy==2.0.0rc1`

**Comment by rgommers** [comment]
With numpy `2.0.0rc1` available, everyone can start doing their 2.0-compatible releases! gh-26191 contains an overview of widely used downstream packages with a compatible release up on PyPI - please feel free to edit or comment on that overview with updates.

Important: the `[build-requires]` in your package's `pyproject.toml` should be updated to select a 2.0 version for isolated builds. Recommendation:
- In your release branches use: `"numpy>=2.0.0rc1,<2.3",` (or `<3` if you don't release often)
- In your `main` branch, use: `"numpy>=2.0.0rc1`
- It will be helpful for distributors to explain the constraint in a code comment, something like: https://github.com/scipy/scipy/blob/19ad5641337aebec6beda3f6789fb5808611ff4a/pyproject.toml#L28-L38

**Comment by larsoner** [comment]
> In conda-forge, 2.0.0rc1 is now packaged ( conda-forge/numpy-feedstock#311 ) ( conda-forge/numpy-feedstock#312 ), which can be installed via conda install conda-forge/label/numpy_dev::numpy=2.0.0rc1

@rgommers @jakirkham what (if anything) should package maintainers do right now to migrate packages on conda-forge? Since binaries are currently built against different NumPy versions for most packages that compile against NumPy (I think?) will there at some point be an auto migration bot that adds NumPy 2.0 or similar?

**Comment by jakirkham** [comment]
This is something we are discussing in conda-forge: https://github.com/conda-forge/conda-forge.github.io/issues/1997

We haven't settled on a plan yet, but we are making progress

**Comment by jakirkham** [comment]
Conda-forge NumPy 2 migration is now in progress

More details in this comment: https://github.com/conda-forge/conda-forge.github.io/issues/1997#issuecomment-2113918420

**Comment by rgommers** [comment]
**Important: we decided on a release date in the community meeting we just had - June 16** (3.5 weeks from today).

Please get your releases done (or pins in place) and do your final testing! 

We'll send an announcement to the mailing list and other project channels as well.

**Comment by charris** [comment]
Pushed this off to 2.0.1 to clear the 2.0.0 milestone.

**Comment by rgommers** [comment]
The 2.0.0 release was uploaded to PyPI about 5 hours ago 🎉. Thanks to everyone who helped make this possible!

We'll leave this issue open for a bit longer, in case more public service announcements turn out to be needed.

**Comment by leofang** [comment]
@rgommers the NumPy 2.0 docs is not yet available, any ETA?

**Comment by seberg** [comment]
@leofang I suspect in about an hour, see https://github.com/numpy/doc/pull/24 (there was some difficulty with building the docs on newer Python versions which delayed it).

**Comment by melissawm** [comment]
Doc pages for NumPy 2.0 are up: https://numpy.org/doc/stable

**Comment by mattip** [comment]
@rgommers can we close this now?

**Comment by rgommers** [comment]
Yes, I think we're good here. Everything went well with the 2.0 release, 2.0.1 is out now (a set of fairly minor fixes), and I don't think we expect to have to make new 2.0-related announcements anymore (which is why we kept this issue open). 

Thanks everyone!
