### ISSUE TITLE
NumPy website and docs seem broken

### ISSUE THREAD

**Issue by phofl** [numpy/numpy#24314]
[This side](https://numpy.org) looks very weird and the api reference gives me a 404: https://numpy.org/doc/stable

**Comment by jrbourbeau** [comment]
I think this was just a transient issue. I was getting a 404 earlier, but things seem to be working again now

**Comment by seberg** [comment]
Yes, Stéfan and Jarrod are on it, and there is an issue on numpy.org so closing here.  Not sure the status, it might be fluky for a bit longer.
