### ISSUE TITLE
Error when installing NumPy from GitHub repository

### ISSUE THREAD

**Issue by fti-rgurav** [numpy/numpy#24329]
### Steps to reproduce:

I attempted to install NumPy from the GitHub repository using the following command:
```
pip install git+https://github.com/numpy/numpy.git@v1.21.1#egg=numpy
```

### Error message:

```shell
However, the installation process encountered an error, and I received the following output:
Collecting numpy
  Cloning https://github.com/numpy/numpy.git (to revision v1.21.1) to /tmp/pip-install-e4yn7btc/numpy_5fd2a8f7eaed49ae90c4ffa2ce51df9f
  Running command git clone --filter=blob:none --quiet https://github.com/numpy/numpy.git /tmp/pip-install-e4yn7btc/numpy_5fd2a8f7eaed49ae90c4ffa2ce51df9f
  Running command git checkout -q e13fc196b121169bac71be6acf1090ccfbd22cac
  Resolved https://github.com/numpy/numpy.git to commit e13fc196b121169bac71be6acf1090ccfbd22cac
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Running from numpy source directory.
      error: Multiple top-level packages discovered in a flat-layout: ['numpy', 'branding'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Additional information:

**Environment:**

- Operating System: Debian 10 
- Python Version: Python 3.7.3
- Setuptools : 68.0.0

**Steps to Reproduce:**

1. Open a terminal.
2. Execute the command: pip install git+https://github.com/numpy/numpy.git@v1.21.1#egg=numpy

**Expected Behavior:**

NumPy should be installed successfully from the GitHub repository.

**Comment by mattip** [comment]
Version 1.21.1 is no longer supported. You may have more luck if you try to pin setuptools to the version in the [pyproject.toml](https://github.com/numpy/numpy/blob/df6d2600c51502e1877aac563658d0616a75c5e5/pyproject.toml#L5), `setuptools<49.2.0`. Is there a reason you cannot use the [PyPI wheels](https://pypi.org/project/numpy/1.22.1/#files)?

**Comment by fti-rgurav** [comment]
Since my version of Python, 3.7.3, is not compatible with Python 1.22.1, I am installing Numpy version 1.21.1, which is compatible with Python 3.7.3. Numpy was successfully installed by PYPI Wheel, but I want to install it through a git repository.

**Comment by rgommers** [comment]
We've switched build systems, so the issue of `setuptools` versions is no longer relevant. Installing directly from GitHub should be working just fine right now. Hence I'll close this issue - thanks all.
