### ISSUE TITLE
ENH: Addition of weierstrass function into numpy functions

### ISSUE THREAD

**Issue by aarda55** [numpy/numpy#24325]
### Proposed new feature or change:

# Proposal:

The proposal for a new feature in this issue is the addition of the weierstrauss function into the capibilities of numpy. The addition of more abstract mathematical function would be an enhancement to numpys capibilities in mathematical research. The weierstrass function is a nowhere-differentiable function and can be used in fractal analysis or research in control theory. This new feature is rather small and would have no drawbacks, considering it would give mathematician another tool to their toolbox to work with in research. If this feature is wanted i can make the PR and would also want to know where this implementation would be wanted in the toolbox.

# Implementation:

      import numpy as np

      def weierstrass(x, a, b, n_max):

      """
      Calculate the Weierstrass function for a given 'x'.
  
      Parameters:
          x (float or array): The input value/values for the function.
          a (float): The 'a' parameter of the Weierstrass function. Governs the rate at which the infinite series converges.
          b (float): The 'b' parameter of the Weierstrass function. Can be expressed as b = 2n+1, where n is a positive integer. 
          n_max (int): The maximum number of terms in the series.
  
      Returns:
          numpy array: The Weierstrass function values corresponding to the input 'x'.
      """

      n = np.arange(n_max + 1)
      term = a**n * np.cos(b**n * np.pi * x)
      return np.sum(term)

# Usage example
        
        """
        All constant are optimized to follow the original function
        """
        x_values = np.linspace(-2, 2, 1000)
        a = 0.5
        b = 3
        n_max = 100
        
        weierstrass_values = np.array([weierstrass(x, a, b, n_max) for x in x_values])

**Comment by WarrenWeckesser** [comment]
This is certainly out of scope for NumPy, so I'm closing this issue.

Also, given that we use finite precision floating point approximations to the real numbers, I have doubts that a *useful* implementation of this function exists.  If I'm wrong, and there is demand for such a function, then SciPy is probably a better home for it.
