### ISSUE TITLE
Nightlies should not have numpy 2.0 wheels (or should have both numpy 1.26 and 2.0 wheels)

### ISSUE THREAD

**Issue by lithomas1** [numpy/numpy#24324]
There have been some C API changes recently on main, and pandas has been affected.

Since 1.26 is the next release, there should be nightlies for 1.26 up.

I think this is just an issue of configuring the Github Actions cron job for this (not sure about cirrus CI).
(https://github.com/orgs/community/discussions/25931)

**Comment by charris** [comment]
We should have a 1.26.0rc1 out soon after the Python 3.12 release. Numpy 1.26 is pretty much 1.25 built with meson and with cython 3 support.

**Comment by seberg** [comment]
Not sure, if three is an easy way to upload the 3.12 nightlies after the rc is out for a week or so?  Unless its super hard, it would make sense, because quite a bit of downstream tests the nightlies I think, but not the rc explicitly.

**Comment by charris** [comment]
@seberg If we do that, we need to get the version fixes for the wheels in first, the 1.26 wheels are currently labeled as 2.0.

**Comment by seberg** [comment]
I dunno, I guess we can manually trigger the action (once the names are right) and disable it (and maybe also cirrus) to not replace it for a few days.

Not sure it is worthwhile as such.  The closest downstream might mainly test with the nightlies, but second order downstream probably does a lot of `--pre` testing in any case.

**Comment by lithomas1** [comment]
Completely understand if this isn't high prio.

Can numpy hold off on merging the 2.0 API/C API changes for a couple weeks until 1.26 comes out then?

**Comment by seberg** [comment]
@lithomas1 are you worried about false messaging about requiring a quick fix?  The only real change on C changes was the complex right now (which you saw), and isn't relevant for 1.26.  OTOH, we could make sure to not merge very disruptive things like the int64 on windows change, but for smaller changes I would prefer to just keep going?

**Comment by lithomas1** [comment]
I think I'm a little worried about not being able to keep up with the 2.0 changes and losing compat with 1.26 in the process.
(I'm assuming that if we're compatible with 2.0 then we'll also be compatible with 1.26.)

Maybe I'm being irrational here though (worst case we can just build from source from the 1.26 branch I guess).

> @lithomas1 are you worried about false messaging about requiring a quick fix? The only real change on C changes was the complex right now (which you saw), and isn't relevant for 1.26. OTOH, we could make sure to not merge very disruptive things like the int64 on windows change, but for smaller changes I would prefer to just keep going?

For smaller things, I definitely agree that it'd be fine to remove them.

**Comment by seberg** [comment]
Since 1.26 should have basically only a few bug backports, I don't think you should worry about losing compat, sanity checking it might be nice, but I think whatever happens, it will be on NumPy to just revert anything in a 1.26.1 if it creates real problem.

**Comment by lithomas1** [comment]
Thanks for the assurances about 1.26. I'll work on getting pandas 2.0 ready then :).

Feel free to close this if there's nothing else to do.

R.e. using pre: I don't think this is really useful for pandas, since we get the same coverage on the lates numpy from nightlies.

**Comment by rgommers** [comment]
> R.e. using pre: I don't think this is really useful for pandas, since we get the same coverage on the lates numpy from nightlies.

**Comment by rgommers** [comment]
> R.e. using pre: I don't think this is really useful for pandas, since we get the same coverage on the lates numpy from nightlies.

Sure, whatever you prefer. My usual strategy is to do only a single job with `main`, because it breaks quite regularly. `--pre` should be fully backwards-compatible normally, and hence is more a sanity check regarding things like packaging constraints that are in a release branch but not main.

> Feel free to close this if there's nothing else to do.

Will do then. Thanks for raising it Thomas!
