### ISSUE TITLE
TYP: ndarray is Iterable[Any]

### ISSUE THREAD

**Issue by twoertwein** [numpy/numpy#24335]
### Describe the issue:

ndarray declares `__iter__` to return `Any` instead of the generic type. This makes ndarray difficult to handle in function overloads that work with any iterable. Depending on how the type checkers handles Any in overloads, it might either pick the first matching overload (pyright) or match none but returns Any (mypy). Both cases are not great.

### Reproduce the code example:

```python
from typing import (
    Iterable,
    overload,
)

import numpy as np

x = np.arange(5)
reveal_type(x)  # numpy.ndarray[Any, numpy.dtype[numpy.signedinteger[Any]]]
reveal_type(x.__iter__)  # def () -> Any

def foo(x: Iterable[np.signedinteger]) -> np.signedinteger:
    return next(iter(x))

reveal_type(foo(x))  # mypy&pyright: np.signedinteger, works because Any matches np.signedinteger


@overload
def bar(x: Iterable[str]) -> str:
    ...

@overload
def bar(x: Iterable[np.signedinteger]) -> np.signedinteger:
    ...

def bar(x: Iterable[np.signedinteger | str]) -> np.signedinteger | str:
    return next(iter(x))

reveal_type(bar(x))  # mypy: Any; pyright: str
```

### Runtime information:

1.25.2
3.11.4 (main, Jun  7 2023, 18:32:58) [GCC 10.2.1 20210110]
[{'numpy_version': '1.25.2',
  'python': '3.11.4 (main, Jun  7 2023, 18:32:58) [GCC 10.2.1 20210110]',
  'uname': uname_result(system='Linux', node='toolbox', release='6.4.7-200.fc38.x86_64', version='#1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/var/home/twoertwein/.cache/pypoetry/virtualenvs/pandas-stubs-DrIM1v70-py3.11/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-5007b62f.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 4,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]

**Comment by BvB93** [comment]
In it's current state it's quite frankly not possible to add a return type more specific than `Any` unless we're willing to resort to returning unions (which is even worse). The `ndarray.__iter__` return type is strongly dependent an the array's dimensionality (scalar? 1d array? raising an exception? These are all valid posibilities depending on the dimension), which is something the we cannot describe with the currently available typing tools.

**Comment by twoertwein** [comment]
Thank you, that makes sense - I forgot for a moment that multi-dimensional ndarrays exist :)
