### ISSUE TITLE
BUG: assert_array_equal errors on scipy sparse matrices

### ISSUE THREAD

**Issue by lobpcg** [numpy/numpy#24351]
### Describe the issue:

assert_array_equal errors on scipy sparse matrices

### Reproduce the code example:

```python
from numpy.testing import assert_array_equal
from scipy.sparse import diags
G = diags(np.ones(2), 1)
assert_array_equal(G, G)
```

### Error message:

```shell
C:\Program Files\Python310\lib\site-packages\numpy\testing\_private\utils.py:746: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.
  val = comparison(x, y)
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\numpy\testing\_private\utils.py", line 746, in assert_array_compare
    val = comparison(x, y)
  File "C:\Program Files\Python310\lib\site-packages\scipy\sparse\_base.py", line 337, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\site-packages\numpy\testing\_private\utils.py", line 924, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "C:\Program Files\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Program Files\Python310\lib\site-packages\numpy\testing\_private\utils.py", line 809, in assert_array_compare
    raise ValueError(msg)
ValueError: 
error during assertion:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\numpy\testing\_private\utils.py", line 746, in assert_array_compare
    val = comparison(x, y)
  File "C:\Program Files\Python310\lib\site-packages\scipy\sparse\_base.py", line 337, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().


Arrays are not equal
 x: array(<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements (1 diagonals) in DIAgonal format>, dtype=object)
 y: array(<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements (1 diagonals) in DIAgonal format>, dtype=object)
```

### Runtime information:

import sys, numpy; print(numpy.__version__); print(sys.version)
1.25.0
3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

print(numpy.show_runtime())
[{'numpy_version': '1.25.0',
  'python': '3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='DESKTOP-4NFN4TA', release='10', version='10.0.22621', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}},
 {'architecture': 'SkylakeX',
  'filepath': 'C:\\Program '
              'Files\\Python310\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.23-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 16,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'},
 {'architecture': 'SkylakeX',
  'filepath': 'C:\\Program '
              'Files\\Python310\\Lib\\site-packages\\scipy.libs\\libopenblas-802f9ed1179cb9c9b03d67ff79f48187.dll',
  'internal_api': 'openblas',
  'num_threads': 16,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.18'}]

**Comment by priyank-p0** [comment]
I believe that it is to be expected when using scipy sparse type object. The error comes from the fact that scipy.sparse has a __bool__ function which expects the input to be of dim(1,1) and returns an error if it is of any other dimension [](https://github.com/scipy/scipy/blob/main/scipy/sparse/_base.py#L327) . If you try running the following code, it works as you would expect. i.e. without returning any errors. 

`from numpy.testing import assert_array_equal
from scipy.sparse import diags
G = diags(np.ones(1))
assert_array_equal(G, G)`

**Comment by seberg** [comment]
Indeed, unless the sparse folks think of a way that NumPy can be useful here there is nothing to do in NumPy.  It is a known issue of `scipy.sparse`, although there is clearly some interaction.  The error here is in a sense lucky, although it is not as clear as it should be.

Closing, since there is at least one SciPy issue open about this.  There is some momentum around scipy sparse right now, so this may well improve and it may also be easier to contribute for that reason.
