### ISSUE TITLE
Deprecation issues in tests with too-new setuptools versions

### ISSUE THREAD

**Issue by charris** [numpy/numpy#24350]
There are two deprecation issues when running `python -mspin test` with Python 3.11:

- `sre_constants` and `sre_parse` are deprecated.  This breaks test collection but can by fixed
  by using recent setuptools.
- `pkg_resources` is deprecated in recent setuptools, this causes `numpy/distutils/tests/test_system_info.py`
   to fail

Note that we have several other uses of `pkg_resources`

- In `tools/npy_tempita/__init__.py`
- ~In numpy/_utils/_pep440.py (copied from SciPy)~
- In `versioneer.py` (going away)

We should fix the usage in the first file.

The easiest quick solution is to upgrade the setuptools version requirement and ignore the test_system_info error.

**Comment by charris** [comment]
We don't use the troublesome parts of tempita, and in fact they don't run :) The version in Cython is no better in that regard. Maybe be can just get rid of much of it.

**Comment by charris** [comment]
`numpy/distutils/tests/test_system_info.py` uses distutils, that needs to be fixed.

**Comment by rgommers** [comment]
Skipping the problematic tests in `numpy.distutils` when the `setuptools` version is >= 60.0 on Python 3.11 sounds right to me. That's what we already required.

**Comment by rgommers** [comment]
`tools/npy_tempita/__init__.py` is only used in the `numpy.distutils` build, so it's going away - no need to worry about that one. I'll open a PR to make the `numpy.distutils` tests pass.

**Comment by charris** [comment]
@rgommers 

We have setuptools pinned in various ways in several locations
- pyproject.toml.setuppy
- test_requirements.txt
- environment.yml

I'm wondering if we should change those pins? That essentially locks us into meson builds, but I think that is already the case.

**Comment by rgommers** [comment]
I'd much prefer not to touch them right now. Most of that is still needed. We should be able to get rid of all them in a few months.
