### ISSUE TITLE
BUG: numpy.insert fails to properly insert when indices array is of type uint64

### ISSUE THREAD

**Issue by tfblum** [numpy/numpy#24359]
### Describe the issue:

I have a very large 1D array of type uint16 and I'm trying to insert pad values at specific indices to make the array properly reshape into a 3D array. The 3rd dimension has varying numbers of elements and so pad values must be added for reshaping to work. 

total size of the array in 1 dimension requires indexing with at least 64bit unsigned integers and when I try to use the numpy.insert method I get a UFuncOutputCastingError described in the traceback. 

### Reproduce the code example:

```python
import numpy as np

arr = np.random.randint(0,2**16, (10,), dtype=np.uint16)
pad = np.array([3,8]), dtype=np.uint64)
pad = np.random.randint(0,2**16, (2,), dtype=np.uint16)
```

### Error message:

```shell
UFuncTypeError                            Traceback (most recent call last)
Cell In[25], line 1
----> 1 arr_copy = np.insert(arr_copy, indices, pad)

File ~\mambaforge\lib\site-packages\numpy\lib\function_base.py:5540, in insert(arr, obj, values, axis)
   5538 numnew = len(indices)
   5539 order = indices.argsort(kind='mergesort')   # stable sort
-> 5540 indices[order] += np.arange(numnew)
   5542 newshape[axis] += numnew
   5543 old_mask = ones(newshape[axis], dtype=bool)

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('uint64') with casting rule 'same_kind'
```

### Runtime information:

1.25.1
3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]

### Context for the issue:

I'm working on an application that takes time based detector data and reshapes it into a series of images. This issue is preventing my work from moving forward with the large datasets required.

**Comment by charris** [comment]
Unsigned 64 bit integers will be a problem, numpy uses signed 64 bit integers for indexing -- after all, indexes can be negative. I think your best bet here is some sort of chunking if you genuinely need unsigned 64 bit indexing.

**Comment by tfblum** [comment]
I looked at our requirements again and I think signed 64 bit integers will work fine. The section of code is running as expected now with that change.
