### ISSUE TITLE
DOC: np.equal() and == behaving differently

### ISSUE THREAD

**Issue by aerobio** [numpy/numpy#24363]
### Issue with current documentation:

[Documentation](https://numpy.org/doc/1.24/reference/generated/numpy.equal.html) (ver. 1.24) for `np.equal()` says:

> The == operator can be used as a shorthand for np.equal on ndarrays.

The reader understands that `==` and `np.equal()` are interchangeable.
However, using ver. 1.24.4, they behave differently when the operand sizes are different:

    >>> a = np.array([1, 2, 3])
    >>> b = np.array([1, 2])
    
    >>> a == b
    <stdin>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
    False
    
    >>> np.equal(a, b)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### Idea or request for content:

While the announced deprecation is not implemented, the documentation should reflect their different behavior.

**Comment by seberg** [comment]
FWIW this one is gone in 1.25.  There are still some differences, I don't know how useful it is to point out the details:
* equal/not_equal may raise an error when `==` and `!=` returns an array of False/true.
* Only the operators currently support `void`/structured dtypes  (this can be changed but requires some work to fold the functionality into a ufunc, which is not super hard but a bit of complexity that needs to be stolen from either the string version or the structured dtypes casts).

**Comment by seberg** [comment]
Closing this one original issue is gone and the rest is covered by gh-9147
