### ISSUE TITLE
DOC: GSOD-NumPy Community Review #2

### ISSUE THREAD

**Issue by MarsBarLee** [numpy/numpy#24382]
### Issue with current documentation:
![image](https://github.com/numpy/numpy/assets/46167686/537d3a9d-e8f5-4844-b3e6-3a528ee0116a)

Hi everyone! I am inviting the community to review the script of the '**NumPy Contributor Comics**', which is the of the GSOD-NumPy 2023 project.'

**The script can be viewed here, as a [Google Doc](https://docs.google.com/document/d/1fjLTDqSkcKMxo8oSTRThllBFpjo5rXS9/edit?usp=sharing&ouid=110556856523158639329&rtpof=true&sd=true)**. You can comment either here on Github or on the Google Doc, whichever you prefer.

These comics aim to show newcomers that NumPy is driven by people who use it: in this case, scientists! These comics will show grad students finding a usability problem in NumPy,  working together to submit an issue, and talking to community members.

For more details, check out the [project roadmap](https://medium.com/@marsbarlee/gsod-numpy-contributor-comics-project-roadmap-521280503fbd).

I will also host a **review session at the next NumPy Community Meeting on August 16**, if you would like to chat!
This thread will be open for the next two weeks and **close on August 23**.

### Idea or request for content:

For review, you can comment on any part, whether you like the idea of the comics, don't like a specific line or not sure what something means.

Some specific parts I would like feedback on:
- **Themes**
  - [On Page 5, ](https://docs.google.com/document/d/1fjLTDqSkcKMxo8oSTRThllBFpjo5rXS9/edit?disco=AAAA3sVZK9Y)does this panel accurately show the tie between open source and open science?
- **Story and Pacing**
  - Does this seem like a reasonable amount of content to cover in 16 pages?
  - Do the three students interacting together feel realistic?
    - eg Since they're beginners, they don't at answer immediately
    - eg not too mean-spirited? They argue, to show different approaches
- **Accuracy**
  - [On Page 3](https://docs.google.com/document/d/1fjLTDqSkcKMxo8oSTRThllBFpjo5rXS9/edit?disco=AAAA3sVZK9c), how accurate is the .npz code?
  - [On Page 7](https://docs.google.com/document/d/1fjLTDqSkcKMxo8oSTRThllBFpjo5rXS9/edit?disco=AAAA3sVZK9k), does the visual metaphor of the NumPy issue tracker as a bulletin board make sense?

**Comment by w1ck-3d** [comment]
Hi, I read your script and find it awesome. The story arch seems nice and the scene switches from the real world to interacting with Github are entertaining.

- Page 5: The bridge from open science to open source makes sense to me. I especially like that exposing the file name of a .npz file literally makes things more transparent.
- Page 7: The bulletin board is a great way to visualize Github issues, in my opinion.

Here's an idea you could consider: One could smoothly transition from playing video games to the NumPy world by using logos. Notice how similar the [Nintendo64 logo](https://upload.wikimedia.org/wikipedia/de/thumb/0/04/Nintendo_64_Logo.svg/1200px-Nintendo_64_Logo.svg.png) (old-school but still...) looks to the [NumPy logo](https://user-images.githubusercontent.com/67586773/105040771-43887300-5a88-11eb-9f01-bee100b9ef22.png).

**Comment by MarsBarLee** [comment]
Hi @w1ck-3d, thank you for reviewing and your comment! I’m glad that the visual metaphors on page 5 and 7 make sense. I also like the suggestion about using logos to transition between scenes. Perhaps to update the old-school and avoid copyrights, we could make a parody of the Switch logo, with two snakes...? Not too far a stretch since the Python logo has two snakes, just like how the Switch logo has two controllers.
