### ISSUE TITLE
ENH: dot() product extension

### ISSUE THREAD

**Issue by alex77g2** [numpy/numpy#24386]
### Proposed new feature or change:

I need to calculate 3 dot-products together: ab=dot(a,b), aa=dot(a,a), bb=dot(b,b), both a and b are 1-D arrays.
aa,ab,bb are scalar (0-D) numbers.
It would be helpful (speed & coding) to combine 3 operations into 1.
ab,aa,bb = dot_triple(a,b) # the naming could be better
Needles to say, my vectors are huge in length and it has to be done often.

Faster, because of memory bandwidth and loading of SIMD registers could be done only once, vs 3 times before.
Code would become smaller, as 3 lines of code become one line of python code.

Trivial (but not faster) implementation:
```
def dot_triple(a,b):
    return dot(a,b), dot(a,a), dot(b,b)
```

Reference C-code:
```
double aa=0, bb=0, ab=0;
if (a==b) { // same array pointer
    aa=dot(a,a); bb=aa; ab=aa;
} else {
  int len = a.length(); // or similar
  for (i=0; i<len; i++) { // later SIMD vectorization
    aa += a[i]*a[i];
    bb += b[i]*b[i];
    ab += a[i]*b[i];
  }
}
return; // all 3 values
```

**Comment by rkern** [comment]
This seems like too specialized a function for `numpy` or `scipy`. I think your own code or a more specialized library would be the best place for such a function.
