### ISSUE TITLE
BUG: make np.iinfo(np.timedelta64) return bits rather than error

### ISSUE THREAD

**Issue by Gabriel-Kissin** [numpy/numpy#24430]
### Describe the issue:

`np.timedelta64` is a type of integer (see code example). Yet `np.iinfo(np.timedelta64)` raises `ValueError: Invalid integer data type 'm'.`  

[Using `np.finfo` i.e. `np.finfo(np.timedelta64)` also raises `ValueError: data type <class 'numpy.timedelta64'> not inexact`  -  as it should].   

So there is no way to find bits for this dtype. 

This presumably happens because `np.iinfo` also has attributes for min and max allowable values for the dtype. And with `np.timedelta64`, the min and max allowable values aren't fixed: as explained [here](https://numpy.org/doc/stable/reference/arrays.datetime.html#datetime-units), it depends on the date unit used, e.g. for years the min, max is [9.2e18 BC, 9.2e18 AD], but for attoseconds the min, max is [ 1969 AD, 1970 AD]. This is dealt with by making `np.iinfo(np.timedelta64)` raise a ValueError. However it might be better if it returned an object without `min` and `max` attributes, just with a `bits` attribute.

### Reproduce the code example:

```python
import numpy as np
print(*np.signedinteger.__subclasses__())
# <class 'numpy.int8'> <class 'numpy.int16'> <class 'numpy.intc'> <class 'numpy.int32'> <class 'numpy.int64'> <class 'numpy.timedelta64'>
np.iinfo(np.timedelta64)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\numpy\core\getlimits.py", line 657, in __init__
    raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'm'.
```

### Runtime information:

1.23.1
3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]

**Comment by seberg** [comment]
But datetime/timedlta is always 64bit as the name says and it is neither a float nor an int.  Tagging in a bit more info to the dtype is OK to me, because it is also nice long-term for all others.  But it isn't clear to me why `iinfo` should accept integers.  Yes, it's a subclass, but that is also a bit weird to begin with.

**Comment by Gabriel-Kissin** [comment]
> But datetime/timedlta is always 64bit as the name says

You're right, with all the dtypes it is clear how much space they take just from their names, e.g. int8 is 8bit. But still, having `np.iinfo` and `.bits` can be useful for cases where it could be given anything, like here. The error arose as I was making a list of all integer types using `np.signedinteger.__subclasses__()` (and `np.unsignedinteger.__subclasses__()`), and needed them sorted in order of how much space they took up. So I used `lambda dtype : np.iinfo(dtype).bits` as a key in the sort. When it hit datetime64, it raised the error.   

> datetime/timedlta is neither a float nor an int... Yes, it's a subclass, but that is also a bit weird to begin with.

I agree I was surprised to see datetime64 considered an integer. I imagine it is because it simply uses a 64bit integer to represent a datatime, e.g. if it is in years then 1 means 1 year after the epoch; if in seconds, then 1 is one second after, etc. So essentially an integer. 
But either way, once numpy classes it as an integer then functions which are meant for integers shouldn't break when given one

**Comment by esapekkasun** [comment]
I tried this to fix the issue and it seems to work:

https://github.com/numpy/numpy/compare/main...esapekkasun:numpy:fix_iinfo_timedelta

This makes the np.iinfo work basically as it would with a 64 bit integer, also returning corresponding min and max values. What do you think?

**Comment by Gabriel-Kissin** [comment]
After a brief look at the code for `iinfo` at https://github.com/numpy/numpy/blob/main/numpy/core/getlimits.py, and a quick test, that does seem to get the .bits to work for timedelta. I just wonder whether it is appropriate for iinfo, given a timedelta64, to return the min and max for int64? I suppose one could argue that it is that number of timedelta units...  but as the units aren't fixed, it depends on that what the min and max really mean

**Comment by esapekkasun** [comment]
I was also thinking whether this is a good solution or not considering the min and max. But `iinfo` is not able to work with the timedelta units, it only returns the "Machine limits" of the type. So to me "Machine limits" sound more like the underlying int64 limits, and that would also make the functionality is similar with other int types.

**Comment by esapekkasun** [comment]
I made another change to the functionality. The class `iinfo` with timedelta64 still works and provides the bits attribute, but trying to access the min or max attributes raises a ValueError. What do you think?

**Comment by Gabriel-Kissin** [comment]
I haven't tested it, but if you then do `np.iinfo(np.timedelta64)` won't it raise ValueError, as iinfo displays a tuple of min and max so assume it automatically evaluates min and max?

**Comment by esapekkasun** [comment]
I also changed __str__ so that it outputs this:

```
np.iinfo(np.timedelta64)
Machine parameters for timedelta64
---------------------------------------------------------------
min = depends on units
max = depends on units
---------------------------------------------------------------
```

**Comment by Gabriel-Kissin** [comment]
oh right sorry I didn't scroll down to see that bit!

**Comment by esapekkasun** [comment]
No problem! Now I finished the implementation and created the pull request. This is my first pull request for Numpy so let's see how it goes.

**Comment by seberg** [comment]
Closing, since we ended up saying that it seems right/OK to reject in the PR.  If someone finds this and disagrees strong enough:  Please just open a new issue.
