### ISSUE TITLE
Sphinx 7.2.2 breaks CircleCI

### ISSUE THREAD

**Issue by charris** [numpy/numpy#24438]
Sphinx 7.2.2, released a few hours ago, breaks breathe and consequently the doc builds. See https://app.circleci.com/pipelines/github/numpy/numpy/21185/workflows/b10277d5-2cd5-4796-84a5-a46c6ce88b84/jobs/33805 .

**Comment by charris** [comment]
See also https://github.com/sphinx-doc/sphinx/issues/11605. Looks like sphinx has pushed this off to breathe: https://github.com/breathe-doc/breathe/issues/943 .

**Comment by AA-Turner** [comment]
Please may you test with [Sphinx 7.2.3](https://pypi.org/project/Sphinx/7.2.3/)?

A

**Comment by bsipocz** [comment]
The new release has fixed this, so I'm closing. I don't think it's worth listing this specific bugfix version number in the config file, but to be 100% certain that it's not tripping people locally building docs, we could even do that.

**Comment by mattip** [comment]
> The new release has fixed this,

FWIW, There is a problem with the 7.2.3 release, so we re-pinned `<7.2.0`. See #24534 and #24543

**Comment by bsipocz** [comment]
Dang, I should have checked `main`, than just follow PRs.

**Comment by AA-Turner** [comment]
Please may you test with [Sphinx 7.2.5](https://pypi.org/project/Sphinx/7.2.5/)? I added special-casing for MathJax, as discussed in https://github.com/sphinx-doc/sphinx/issues/11658.

A
