### ISSUE TITLE
BUG: GCC-Workaround-Intel-Downfall to avoid significant perf-drop

### ISSUE THREAD

**Issue by alex77g2** [numpy/numpy#24447]
### Describe the issue:

2 years ago "Intel Contributes AVX-512 Optimizations To Numpy, Yields Massive Speedups"
www.phoronix.com/news/Intel-Numpy-AVX-512-Landed

Last week the Workaround-Intel-Downfall caused up to 50% perf decrease, especially for AVX-hungry-code (6th .. 11th Intel CPU generation).
"GCC Compiler Adds Software Workaround To Avoid Intel Downfall Performance Hit" (GCC 14 patch)
www.phoronix.com/news/GCC-Workaround-Intel-Downfall
(I think AMD had similar issues last week also, but I'm not sure about this.)

I suggest concidering this in the official releases. As 12+13th gen seems not affected, numpy could decide during installation (check CPU generation) or during numpy-startup, which binary-version (or internal function) to use.

### Reproduce the code example:

```python
pure AVX-performance issue, after microcode update of last week.
```

### Error message:

```shell
performance drop (mentioned by Intel itself up to 50% for AVX-code) until Intel 11th-gen.
```

### Runtime information:

none.

### Context for the issue:

performance drop.

**Comment by seiko2plus** [comment]
Gather/Scatter are used within non-contiguous memory access to handle 32-bit/64-bit stride load/store operations, already don't provide that noticeable performance gain compared to scalar load/store even before even Intel microcode update, I will replace it with scalar emulation to meaure if there any performance regression.

As for Intel SVML, only `sin`, `cos`, and `tan` (single/double precision) are affected with larger arguments. Normal cases aren't a concern so we shouldn't worry about it.

>  (I think AMD had similar issues last week also, but I'm not sure about this.)

Amd ZEN4 is affected too?

**Comment by r-devulap** [comment]
As @seiko2plus mentioned, gather instruction (which is the main culprit for this new vulnerability) is primarily used for non-contiguous cases and it won't affect the benchmarks presented in #19478 for the contiguous case. 

I do suspect this will affect non contiguous cases but only for largish values of strides. A quick profile of `np.exp(arr[::2])` shows that is spends ~ 10% of its compute time in the gather instruction. But a profile of `np.exp(arr[::100])` shows gather in the HOT path (nearly 40% of time). It might be well worth benchmarking with the microcode fix (or the scalar version of gather as @seiko2plus mentioned). Just as an example: If gather were to become slower by 50% hypothetically because of this microcode fix, then I would expect roughly a 5% perf drop in this case for small strides, but up to 20% perf drop for large values of strides. 

#### perf profile for `np.exp(arr[::2])` : 

```
Samples: 32K of event 'cycles:u', Event count (approx.): 22965771463
Overhead  Command  Shared Object                                      Symbol
  76.51%  python   _multiarray_umath.cpython-310-x86_64-linux-gnu.so  [.] __svml_exp8
  21.14%  python   _multiarray_umath.cpython-310-x86_64-linux-gnu.so  [.] DOUBLE_exp_AVX512_SKX
   0.29%  python   python3.10                                         [.] _PyEval_EvalFrameDefault
   0.19%  python   libopenblas64_p-r0-15028c96.3.21.so                [.] blas_thread_server
```
 
Annotate into DOUBLE_exp_AVX512_SKX:

```
 10.48 │400:   kmovb        0x3f72c8(%rip),%k7        # 4559a0 <_fini+0x1814>
  0.02 │       vpgatherqq   (%r12,%zmm1,8),%zmm0{%k7}
 56.22 │       vmovdqa64    %zmm1,-0x70(%rbp)
 10.20 │     → call         __svml_exp8@plt
       │       vmovdqa64    -0x70(%rbp),%zmm1
  0.03 │428:   vmovdqu64    %zmm0,(%rbx)
 13.04 │       sub          $0x8,%r15
  0.03 │       add          -0x78(%rbp),%r12
       │       add          %r13,%rbx
       │     ↑ jmp          394
```

#### perf profile for `np.exp(arr[::100])` : 

```
Samples: 258K of event 'cycles:u', Event count (approx.): 207400703178
Overhead  Command  Shared Object                                      Symbol
  80.37%  python   _multiarray_umath.cpython-310-x86_64-linux-gnu.so  [.] DOUBLE_exp_AVX512_SKX
  18.30%  python   _multiarray_umath.cpython-310-x86_64-linux-gnu.so  [.] __svml_exp8
   0.84%  python   _mt19937.cpython-310-x86_64-linux-gnu.so           [.] __pyx_f_5numpy_6random_8_mt19937_mt19937_double
   0.11%  python   _mt19937.cpython-310-x86_64-linux-gnu.so           [.] mt19937_gen
```
Annotate into DOUBLE_exp_AVX512_SKX:

```
  0.52 │400:   kmovb        0x3f72c8(%rip),%k7        # 4559a0 <_fini+0x1814>
  0.00 │       vpgatherqq   (%r12,%zmm1,8),%zmm0{%k7}
 97.63 │       vmovdqa64    %zmm1,-0x70(%rbp)
  0.53 │     → call         __svml_exp8@plt
       │       vmovdqa64    -0x70(%rbp),%zmm1
       │428:   vmovdqu64    %zmm0,(%rbx)
  0.75 │       sub          $0x8,%r15
       │       add          -0x78(%rbp),%r12
  0.00 │       add          %r13,%rbx
```

**Comment by alex77g2** [comment]
thank you looking into this. For benchmarking it is important to tell the used Intel-generation!
As intensive loads will propably not run on older CPUs, we could restrict to 11+12 or 10..13 ?

**Comment by seberg** [comment]
Closing, @r-devulap did this long ago.
