### ISSUE TITLE
ENH: Bitpacked numpy array similar to vector<bool> in C++

### ISSUE THREAD

**Issue by rafaelha** [numpy/numpy#24454]
### Proposed new feature or change:

A single element in a boolean numpy array is stored as 1 Byte in memory instead of a bit. Would a bitpacked numpy array be feasible, similar to vector<bool> in C++? https://[cplusplus.com/reference/vector/vector-bool/](https://cplusplus.com/reference/vector/vector-bool/)

**Comment by rkern** [comment]
That does not fit into [numpy's memory model](https://numpy.org/doc/1.21/reference/internals.code-explanations.html#memory-model). The [`bitarray`](https://pypi.org/project/bitarray/) package provides such an object, though.
