### ISSUE TITLE
ENH: Arbitrarily large random integers

### ISSUE THREAD

**Issue by dschult** [numpy/numpy#24458]
### Proposed new feature or change:

How can we use numpy's random `integers` function to get uniformly selected integers from an arbitrarily large `high` limit? This is important when dealing with exact probabilities in combinatorially large solution spaces. 

I propose that we add the capability for `integers` to construct arrays of type object_ by having it construct python int's as the objects in the returned array. This would allow arbitrarily large integers.
 
The Python random library's `randrange` constructs values for arbitrary upper limits -- and they are exact when using subclasses of `random.Random` with a `getrandbits` methods (which includes the default rng for most operating systems).

Numpy's random `integers` function rightfully raises on `integers(20**20, dtype=int64)` because the upper limit is above what can be held in an `int64`. But Python `int` objects store arbitrarily large integers. So I would expect `integers(20**20, dtype=object)` to create random integers on the desired range. Instead a TypeError is raised `Unsupported dtype dtype('O') for integers`. It seems we could provide support for dtype('O') by constructing Python `int` values and this would allow arbitrarily large ranges of integers.

The core of this functionality would be close to the seven lines used in [the code of random.Random._randbelow](https://github.com/python/cpython/blob/eb953d6e4484339067837020f77eecac61f8d4f8/Lib/random.py#L242) which 
1) finds the number of bits needed to describe the `high` argument.
2) generates that number of random bits.
3) converts them to a python int and checks if it is larger than the input `high`. If so, repeat from step 2.

I realize that people can just use `random.randrange` to obtain this functionality, but that doesn't return an array, and uses a different RNG possibly requiring tracking two RNG states.

**Comment by rkern** [comment]
I'm not especially interested in adding this functionality to `Generator` per se. Such a function can be built using the primitives in `Generator`, following the `Random.randrange()` general recipe. That would be good for a cookbook entry or an example, but I think it's just out of scope for `Generator` (but only just).

**Comment by rkern** [comment]
Actually, you can *reuse* the `Random.randrange()` implementation if you subclass your [`PythonRandomInterface`](https://github.com/networkx/networkx/blob/main/networkx/utils/misc.py#L274) from `random.Random` and only override a couple of methods. You can forego implementing all of the integer, shuffling, and choice methods with all of their slight incompatibilities with `Random`; this implementation *is* a `random.Random`, just using the numpy PRNGs as the core source of random bits.

<details><summary>Code snippet of `PythonRandomInterface`</summary>

```python
import random

import numpy as np


class PythonRandomInterface(random.Random):
    def __init__(self, rng=None):
        try:
            import numpy as np
        except ImportError:
            msg = "numpy not found, only random.random available."
            warnings.warn(msg, ImportWarning)

        if rng is None:
            self._rng = np.random.mtrand._rand
        else:
            self._rng = rng
        
        # Not necessary, given our overriding of gauss() below, but it's
        # in the superclass and nominally public, so initialize it here.
        self.gauss_next = None

    def random(self):
        """Get the next random number in the range 0.0 <= X < 1.0."""
        return self._rng.random()

    def getrandbits(self, k):
        """getrandbits(k) -> x.  Generates an int with k random bits."""
        if k < 0:
            raise ValueError('number of bits must be non-negative')
        numbytes = (k + 7) // 8                       # bits / 8 and rounded up
        x = int.from_bytes(self._rng.bytes(numbytes), 'big')
        return x >> (numbytes * 8 - k)                # trim excess bits
    
    def getstate(self):
        return self._rng.__getstate__()
    
    def setstate(self, state):
        self._rng.__setstate__(state)

    def seed(self, *args, **kwds):
        "Stub method."
        # Probably not necessary or desirable to implement, but could, if one wanted.
        return None
    
    # Efficiency overrides. The following are not necessary, but are useful.
    
    def gauss(self, mu, sigma):
        return self._rng.normal(mu, sigma)
    
    #    exponential as expovariate with 1/argument,
    def expovariate(self, scale):
        return self._rng.exponential(1 / scale)

    #    pareto as paretovariate with 1/argument,
    def paretovariate(self, shape):
        return self._rng.pareto(shape)
```
</details>

```python
>>> rng = np.random.default_rng(10)
>>> pr_rng = PythonRandomInterface(rng)
>>> pr_rng.randrange(0, 20**20)
91977050288243746065638091
```

**Comment by dschult** [comment]
Awesome!  Thanks!
I had started an attempt at this, but this approach is much cleaner and makes use of existing code in both NX and numpy.
