### ISSUE TITLE
BUG: Incorrect behaviour

### ISSUE THREAD

**Issue by RohitMugalya** [numpy/numpy#24464]
### Describe the issue:

the issue was when casting the dtype of vals in arr into boolean.

### Reproduce the code example:

```python
>>>import numpy as np
>>>arr = np.arange(1, 17).reshape(4, 4)
>>>arr
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
>>>arr.shape
(4, 4)
>>>arr.dtype = bool
>>>arr
array([[ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False]])
>>>arr.shape
(4, 16)
```

### Error message:

```shell
this is a wrong behavior
```

### Runtime information:

1.25.1
3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

### Context for the issue:

I found this when I was learning in ipynb
I was a learner in np and pd.

**Comment by rkern** [comment]
For the value-casting operation you want to perform, use `arr.astype(bool)`.

Assigning `arr.dtype = bool` is a different operation, which tells numpy to reinterpret the bytes inside of `arr` as `bool` in-place, changing the shape to account for the different sizes of `bool` and `int`.

Both operations are useful, so both exist and are distinct.
