### ISSUE TITLE
BUG: using obj->ob_refcount directly is not good practice

### ISSUE THREAD

**Issue by Tapanhaz** [numpy/numpy#24466]
### Describe the issue:

      [351/496] Compiling C object numpy/core/_multiarray_umath.cp312-win_amd64.pyd.p/src_multiarray_sequence.c.obj
      [352/496] Compiling C object numpy/core/_multiarray_umath.cp312-win_amd64.pyd.p/src_multiarray_shape.c.obj
      FAILED: numpy/core/_multiarray_umath.cp312-win_amd64.pyd.p/src_multiarray_shape.c.obj
      "cl" "-Inumpy\core\_multiarray_umath.cp312-win_amd64.pyd.p" "-Inumpy\core" "-I..\..\numpy\core" "-Inumpy\core\include" "-I..\..\numpy\core\include" "-I..\..\numpy\core\src\common" "-I..\..\numpy\core\src\multiarray" "-I..\..\numpy\core\src\npymath" "-I..\..\numpy\core\src\umath" "-IC:/opt/include/openblas" "-ID:\FnO\312_source\nogil-3.12\Include" "-IC:\Users\ONE\AppData\Local\Temp\pip-install-ftjkm6cs\numpy_ea23d8cf4f4b4b42879ede9596e993c2\.mesonpy-_uq51ip0\build\meson_cpu" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/O2" "/Gw" "-DNPY_HAVE_SSE2" "-DNPY_HAVE_SSE" "-DNPY_HAVE_SSE3" "-DHAVE_CBLAS" "-DNPY_INTERNAL_BUILD" "-DHAVE_NPY_CONFIG_H" "-D_FILE_OFFSET_BITS=64" "-D_LARGEFILE_SOURCE=1" "-D_LARGEFILE64_SOURCE=1" "/Fdnumpy\core\_multiarray_umath.cp312-win_amd64.pyd.p\src_multiarray_shape.c.pdb" /Fonumpy/core/_multiarray_umath.cp312-win_amd64.pyd.p/src_multiarray_shape.c.obj "/c" ../../numpy/core/src/multiarray/shape.c
      ../../numpy/core/src/multiarray/shape.c(108): error C2039: 'ob_refcnt': is not a member of '_object'
      D:\FnO\312_source\nogil-3.12\Include\object.h(118): note: see declaration of '_object'
      [353/496] Compiling C object numpy/core/_multiarray_umath.cp312-win_amd64.pyd.p/src_multiarray_strfuncs.c.obj
      [354/496] Compiling C object numpy/core/_multiarray_umath.cp312-win_amd64.pyd.p/src_multiarray_scalarapi.c.obj
      ninja: build stopped: subcommand failed.
      INFO: autodetecting backend as ninja
      INFO: calculating backend command to run: C:\mingw64\bin\ninja.EXE
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Reproduce the code example:

```python
pip install numpy==1.26.0b1
```

### Runtime information:

Error occured when installing numpy in win10 x64

**Comment by mattip** [comment]
What version of python are you using and where did you get it? If you are using the no-gil experimental version, you might want to state that in the issue, we don't support that yet.

**Comment by Tapanhaz** [comment]
Thanks for quick reply. Sorry, that is my mistake. Yes I'm trying to build in a experimental version https://github.com/colesbury/nogil-3.12 based on Python 3.12.0a4. Just now, tried building in official release Python 3.12.0b4 and it is working.

**Comment by mattip** [comment]
I changed the title. I think we should leave this open, directly accessing the `ob_refcnt` here looks wrong and we should change it for NumPy2.0. This is accessed via the PyArray_REFCOUNT macro, which is public API:
```
$ git grep PyArray_REFCOUNT
doc/source/reference/c-api/array.rst:.. c:function:: npy_intp PyArray_REFCOUNT(PyObject* op)
numpy/__init__.cython-30.pxd:    npy_intp PyArray_REFCOUNT(object)
numpy/__init__.pxd:    npy_intp PyArray_REFCOUNT(object)
numpy/core/include/numpy/ndarrayobject.h:#define PyArray_REFCOUNT(obj) (((PyObject *)(obj))->ob_refcnt)
numpy/core/include/numpy/ndarrayobject.h:#define NPY_REFCOUNT PyArray_REFCOUNT
numpy/core/include/numpy/noprefix.h:#define REFCOUNT PyArray_REFCOUNT
numpy/core/src/multiarray/shape.c:            refcnt = PyArray_REFCOUNT(self)
```

and also through the unused `NPY_REFCOUNT` (aliased as `REFCOUNT`) macro

**Comment by seberg** [comment]
I guess we can just delete `PyArray_REFCOUNT` and replace the one actual use with [Py_REFCNT()](https://docs.python.org/3/c-api/structures.html?highlight=refcnt#c.Py_REFCNT).
(I would suspect we may have some other places, but maybe those were already replaced with `Py_REFCNT`)

**Comment by seberg** [comment]
Closing, the replacement happened, I don't think there is more to do.
