### ISSUE TITLE
BUG: <np.diag returns error : 'list' object is not callable>

### ISSUE THREAD

**Issue by xx-VIRUS-xx** [numpy/numpy#24462]
### Reproduce the code example:

```python
import numpy as np
arrr2=np.random.rand(3,4)
print(np.diag(arrr2))
```

### Error message:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[49], line 3
      1 import numpy as np
      2 arrr2=np.random.rand(3,4)
----> 3 print(np.diag([arrr2]))

TypeError: 'list' object is not callable
```

## Output for _import sys, numpy; print(numpy.__version__); print(sys.version)_
1.24.3
3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

## Output for _print(numpy.show_runtime())_
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\HP-PC\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 4,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None

**Comment by jakevdp** [comment]
Hi - thanks for the report! I'm not able to reproduce this with the versions specified, but I have a guess as to what might have happened. You may have inadvertently written `np.diag = list()` previously in your Python session; for example:
```python
import numpy as np
np.diag = [1, 2, 3]  # oops!
arrr2=np.random.rand(3,4)
print(np.diag(arrr2))
```
```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-fd2296a43047>](https://localhost:8080/#) in <cell line: 4>()
      2 np.diag = [1, 2, 3]  # oops!
      3 arrr2=np.random.rand(3,4)
----> 4 print(np.diag(arrr2))

TypeError: 'list' object is not callable
```
I'd suggest restarting your Python session, removing any inadvertent assignment like this, and running your code again.
