### ISSUE TITLE
DOC: `isin` should replace `ar1` and `ar2` by `element` and `test_elements`

### ISSUE THREAD

**Issue by bersbersbers** [numpy/numpy#24472]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/generated/numpy.isin.html uses `ar1` and `ar2`, which are not explained anywhere

### Idea or request for content:

I *suspect* that `ar1` -> `element` and `ar2` -> `test_elements`.

**Comment by mattip** [comment]
We don't assign issues. When you submit a PR, please use the phrase `Closes #24472` which will automatically link back to here and close this issue when that PR is merged.
