### ISSUE TITLE
BUG: `Polynomial.fit()` produces incorrect coefficients but plots correctly

### ISSUE THREAD

**Issue by ohunter** [numpy/numpy#24497]
### Describe the issue:

Using `Polynomial.fit()` from `numpy.polynomial.polynomial` produces incorrect coefficients but correctly with matplotlib. 

### Reproduce the code example:

```python
import numpy as np
from numpy.polynomial.polynomial import Polynomial
import matplotlib.pyplot as plt

x = np.array([0.43907794, 1.69045005, 3.27113063, 5.31284303, 12.03073546, 20.0 , 34.95060373, 40.0219539 , 50.29637761, 59.9780461 ,61.29527991, 66.76180022, 72.55762898, 78.74862788, 80.0, 82.37102086, 84.61031833, 87.83754116])
y = np.array([1.59255172, 1.552, 1.49986207, 1.45186207, 1.39972414, 1.35337931, 1.30124138, 1.28717241, 1.25241379, 1.20855172, 1.20027586, 1.15227586, 1.10013793, 1.05213793, 1.03806897, 1.0, 0.952, 0.90565517])

degree = 3
f = Polynomial.fit(x, y, degree)
g = Polynomial(np.polyfit(x, y, degree)[::-1])

print(f"f(x) = {f}")
print(f"g(x) = {g}")

plt.plot(x, y, 'o')
xx, yy = f.linspace()
plt.plot(xx, yy, lw=2, label='f(x)')
xxx, yyy = g.linspace()
plt.plot(xxx, yyy, lw=2, label='g(x)')
plt.legend()
plt.show()
```

### Runtime information:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.25.2
3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
>>> print(numpy.show_runtime())
[{'numpy_version': '1.25.2',
  'python': '3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='KPC22026425', release='10', version='10.0.19045', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\olejeh\\testing\\ultra_battery_tuning\\venv\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None

**Comment by rossbar** [comment]
This is a common gotcha with the polynomial classes. The `.fit` method auto-magically scales the data to a different domain and by default returns the coefficients in the scaled domain. To get the coefficients in the original, unscaled domain you can use the `convert` method.

The reason it plots correctly is that `f.linspace` also takes into account the `domain` and `window` attributes.

**Comment by eendebakpt** [comment]
In the default representation for the polynomial the domain and window are not included. Even if the documentation is improved, it is easy to be confused by the output. In https://github.com/numpy/numpy/pull/21760 the representation is changed so that the chances of confusion are less. (other ways of changing the representation would also work)

**Comment by ohunter** [comment]
@rossbar I might be using convert incorrectly because I can't get it to produce the correct coefficients whatsoever. I am using desmos to verify whether the coefficients are correct as `linspace` correctly converts it.
I have tried the following things and none of them work:
```py
>>> Polynomial.fit(x, y, degree).convert(domain=(min(x), max(x)))
Polynomial([ 1.2639848 , -0.1109531 , -0.03452314, -0.21762806], domain=[ 0.43907794, 87.83754116], window=[-1.,  1.], symbol='x')
>>> Polynomial.fit(x, y, degree, domain=(min(x), max(x)))
Polynomial([ 1.2639848 , -0.1109531 , -0.03452314, -0.21762806], domain=[ 0.43907794, 87.83754116], window=[-1.,  1.], symbol='x')
>>> Polynomial.fit(x, y, degree).convert(domain=(min(x), max(x)), window=(min(y), max(y)))
Polynomial([ 11.68036826, -24.73673432,  19.83763728,  -5.37193661], domain=[ 0.43907794, 87.83754116], window=[0.90565517, 1.59255172], symbol='x')
>>> Polynomial.fit(x, y, degree, domain=(min(x), max(x)), window=(min(y), max(y)))
Polynomial([ 11.68036826, -24.73673432,  19.83763728,  -5.37193661], domain=[ 0.43907794, 87.83754116], window=[0.90565517, 1.59255172], symbol='x')
```

The comparison can be seen here: www.desmos.com/calculator/qmwvlwlz7a

**Comment by eendebakpt** [comment]
Can you try the following?
```
f = Polynomial.fit(x, y, degree, domain=[0,1], window=[0,1])

```

**Comment by ohunter** [comment]
Still not right
```py
>>> Polynomial.fit(x, y, degree, domain=[0,1], window=[0,1])
Polynomial([ 1.56508655e+00, -1.61852545e-02,  3.27248424e-04, -2.60791543e-06], domain=[0., 1.], window=[0., 1.], symbol='x')
```
The purple is the new polynomial
![image](https://github.com/numpy/numpy/assets/2663525/b6a91e4d-7772-4c32-a50b-3843cf286cb2)

**Comment by charris** [comment]
If you want the usual coefficients, just `p.convert()`. The standard window and domain are `[-1, 1]`. Note that here using that would make the design matrix more ill-conditioned.

**Comment by ohunter** [comment]
@eendebakpt The plot is the same as is in the desmos link in my earlier comment. In your example you are using `linspace` which according to @rossbar's earlier comment converts the outputted values to the expected domain. All I want is the coefficients which when plotted using any plotting software will follow the points.

**Comment by ohunter** [comment]
@charris this is what I get when using convert without any arguments:
```py
>>> f = Polynomial.fit(x, y, degree)
>>> f
Polynomial([ 1.2639848 , -0.1109531 , -0.03452314, -0.21762806], domain=[ 0.43907794, 87.83754116], window=[-1.,  1.], symbol='x')
>>> f.convert()
Polynomial([ 1.56508655e+00, -1.61852544e-02,  3.27248419e-04, -2.60791538e-06], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')
```

The converted polynomial is exactly the same as what I got from setting the domain to (0, 1) which as shown above does not plot correctly.

**Comment by eendebakpt** [comment]
@ohunter Have you entered the coefficients in desmos correctly? In particuler the coefficient for x**3 is `-2.60791538e-06`, which should be entered as `-.00000260791538`.

I have the following on desmos:

![image](https://github.com/numpy/numpy/assets/883786/a1bc65b5-7f1b-4a1d-8f69-1611fb168b8f)
