### ISSUE TITLE
.tobytes() method is producing inconsistent results

### ISSUE THREAD

**Issue by Callum-IBI** [numpy/numpy#24500]
### Describe the issue:

When converting a column of a Pandas DataFrame to a NumPy array and then calling .tobytes(), it returns a different set of values each time. However, if I convert the column to a list and then to a NumPy array, it produces the same values each time.

### Reproduce the code example:

```python
import pandas as pd
import numpy as np

stops_table_dataframe = pd.DataFrame({'stop_id': ['ID_1', 'ID_2', 'ID_3', 'ID_4']})

stop_id_bytes_array = np.array(stops_table_dataframe['stop_id']).tobytes()

# Produces a different byte array each time it's run.
print('stop_id_bytes_array:', stop_id_bytes_array)

stop_id_bytes_array = np.array(stops_table_dataframe['stop_id'].to_list()).tobytes()

# Produces the same byte array each time it's run.
print('stop_id_bytes_array:', stop_id_bytes_array)
```

### Runtime information:

First run:
stop_id_bytes_array: b'pN\xa0\xd0F\x02\x00\x00\xf0\xae\x9f\xd0F\x02\x00\x000\xaa\x9f\xd0F\x02\x00\x00p\xcd\xd0\xd0F\x02\x00\x00'
stop_id_bytes_array: b'I\x00\x00\x00D\x00\x00\x00_\x00\x00\x001\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x002\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x003\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x004\x00\x00\x00'

Second run:
stop_id_bytes_array: b'\xf0J\xae\x03\xc6\x01\x00\x000N\xae\x03\xc6\x01\x00\x00\xb0\xae\xad\x03\xc6\x01\x00\x00\xf0\xa9\xad\x03\xc6\x01\x00\x00'
stop_id_bytes_array: b'I\x00\x00\x00D\x00\x00\x00_\x00\x00\x001\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x002\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x003\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x004\x00\x00\x00'

**Comment by rkern** [comment]
```python
>>> np.array(stops_table_dataframe['stop_id']).dtype
dtype('O')
>>> stops_table_dataframe['stop_id'].__array__()
array(['ID_1', 'ID_2', 'ID_3', 'ID_4'], dtype=object)
```

`Series` containing strings are treated as `dtype=object` arrays, and a direct conversion from the `Series` to `ndarray` will create a `dtype=object` array; this is controlled by `Series.__array__()` method. `.tobytes()` on a `dtype=object` array returns the bytes of the points of the `PyObject*` objects, nothing to do with the string values that those objects point to and almost certainly not what you want to work with.

When you convert the `Series` to a list first, `np.array()` will see a list of strings, that it will then convert to a `dtype=str` array where the underlying bytes are the string values themselves, in UCS-4 format.

The idiomatic and fastest way to ensure that you get a `dtype=str` array is to pass that as an argument to `np.array()`:

```python
>>> np.array(stops_table_dataframe['stop_id'], dtype=str)
array(['ID_1', 'ID_2', 'ID_3', 'ID_4'], dtype='<U4')
>>> _.tobytes()
b'I\x00\x00\x00D\x00\x00\x00_\x00\x00\x001\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x002\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x003\x00\x00\x00I\x00\x00\x00D\x00\x00\x00_\x00\x00\x004\x00\x00\x00'
```
