### ISSUE TITLE
negative stride provides a weird slice result

### ISSUE THREAD

**Issue by d-murashkin** [numpy/numpy#24508]
### Describe the issue:

As far as I understand, negative stride in a slice should provide a view with a reversed order.
However, negative stride values lead to empty arrays and weird (to my understanding) results:
```python
import numpy as np
a = np.arange(10)
a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

a[::-1]
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])  #correct

a[1:5]
array([1, 2, 3, 4])   #correct

a[1:5:-1]
array([], dtype=int64)   # why is it empty?

a[1:5][::-1]
array([4, 3, 2, 1])   # correct, in the example above the result should be same, shouldn't it?

a[1::-1]
array([1, 0])  # what's happening here?
```

Tested on numpy 1.25.2 and 1.22.4.

### Reproduce the code example:

```python
import numpy as np
a = np.arange(10)

print(a[::-1])
print(a[1:5])
print(a[1:5:-1])
print(a[1:5][::-1])
print(a[1::-1])
```

### Runtime information:

np.show_runtime()
[{'numpy_version': '1.25.2',
  'python': '3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) '
            '[GCC 11.3.0]',
  'uname': uname_result(system='Linux', node='eoc-030036l', release='5.15.0-78-generic', version='#85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/localhome/mura_dm/conda/envs/deep/lib/libopenblasp-r0.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

also on older numpy
>>> np.__version__
'1.22.4'
>>> sys.version
'3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0]'

**Comment by rkern** [comment]
This is how negative strides/steps work in most Python sequence slicing, like `list`s.

```python
>>> a = list(range(10))
>>> a[1:5:-1]
[]
```

When you want to go backwards, the `start` needs to be higher than the `stop`.

```python
>>> a[4:0:-1]
[4, 3, 2, 1]
```

Note how they need to be adjusted by one to account for the difference in semantics between `start` and `stop` (`start` is always the actual index you want to start from and `stop` is always one `step` beyond the last item you want in the result).
