### ISSUE TITLE
DOC: Mathematical formulas are not rendered

### ISSUE THREAD

**Issue by F3eQnxN3RriK** [numpy/numpy#24534]
### Issue with current documentation:

The mathematical formulas in the documents are not rendered.
e.g. https://numpy.org/devdocs/reference/routines.polynomials.chebyshev.html#notes
<img width="749" alt="スクリーンショット 2023-08-25 16 43 17" src="https://github.com/numpy/numpy/assets/126044367/3f78a75b-a18a-4ad2-83dc-2c0781af42e8">

**Comment by mattip** [comment]
Hmm. I wonder if this is due to #24516. I submitted PR #24543 to revert that. @AA-Turner does the inability to use MathJax ring any bells?

**Comment by AA-Turner** [comment]
See https://github.com/sphinx-doc/sphinx/issues/11658 for tracking, this is a bug in Sphinx. Thanks for raising it @F3eQnxN3RriK!

A
