### ISSUE TITLE
DOC: the f2py meson backend no longer passes `-fimplicit-none`

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#24550]
### Issue with current documentation:

[Using via meson](https://numpy.org/doc/stable/f2py/buildtools/meson.html) needs to be updated to reflect the new `meson` [defaults](https://mesonbuild.com/Builtin-options.html#core-options).

### Idea or request for content:

This is a good first issue to work on.

**Comment by rgommers** [comment]
Is it just a matter of deleting the first bullet under https://numpy.org/doc/stable/f2py/buildtools/meson.html#salient-points?

**Comment by HaoZeke** [comment]
> Is it just a matter of deleting the first bullet under https://numpy.org/doc/stable/f2py/buildtools/meson.html#salient-points?

Yup, I thought I'd leave it here for a new contributor
