### ISSUE TITLE
BUG: <np.savez_compressed created many huge files in /dev/shm>

### ISSUE THREAD

**Issue by hieutv85** [numpy/numpy#24572]
### Describe the issue:

Hi, 
I currently use some high-performance computers to extract, save time window data of time series. I used np.savez_compressed to compress and then save data as npz format and then load the data. But this created many files in directory /dev/shm. It is so inconvenient to delete the files every time save the data and especially I have to save many time with different window size. I listed below the list of files. 

Please suggest me how to prevent this. Thank you very much. 

The list of files in directory /dev/shm:
4.0K /dev/shm/sem.loky-584-0q_ao9q_
4.0K /dev/shm/sem.loky-584-q6k7dcp1
4.0K /dev/shm/sem.loky-584-6cat869_
4.0K /dev/shm/sem.loky-584-3x1dssl6
4.0K /dev/shm/sem.loky-584-xn8aii5u
4.0K /dev/shm/sem.loky-584-8ko7f5qy
4.0K /dev/shm/sem.loky-584-ykugzxq9
4.0K /dev/shm/sem.loky-584-odtwmpnz
212G /dev/shm/joblib_memmapping_folder_584_14522208d7994053a729cb92d72604c4_61bad9e1223147a88637819500daae48
4.0K /dev/shm/sem.loky-584-8a1tlaia
4.0K /dev/shm/sem.loky-584-bzih3_qt
4.0K /dev/shm/sem.loky-584-2y38zc3t
4.0K /dev/shm/sem.loky-584-ubbdytpn
4.0K /dev/shm/sem.loky-584-fumt2l7v
4.0K /dev/shm/sem.loky-584-e6j668ea
0 /dev/shm/joblib_memmapping_folder_584_14522208d7994053a729cb92d72604c4_c1b73a8e54cd487585e45d9544400307
4.0K /dev/shm/sem.loky-566-0z3ugtnc
4.0K /dev/shm/sem.loky-566-dtmz1b0m
4.0K /dev/shm/sem.loky-566-q4a7x7u1
423G total

### Reproduce the code example:

```python
np.savez_compressed("complexnetwork_participant2", X_sw, yr)
my_arrays = np.load("complexnetwork_participant2.npz", mmap_mode='r')
```

### Runtime information:

1.22.4
3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0]

### Context for the issue:

Please support me, I need to run this experiment for my publication. I am third year PhD student so it is very important for me.

**Comment by rkern** [comment]
I can't replicate this on my Linux system with simple, small data.

Given that the largest file in there starts with `joblib_memmapping_folder`, are you sure that `np.load()` is the issue and not `joblib`'s `MemmappingExecutor`?

```python
>>> import os
>>> import numpy as np
>>> X_sw = np.arange(10)
>>> yr = np.arange(20)
>>> np.savez_compressed("complexnetwork_participant2", X_sw, yr)
>>> my_arrays = np.load("complexnetwork_participant2.npz", mmap_mode='r')
>>> os.listdir('/dev/shm')
[]
```

**Comment by hieutv85** [comment]
Hi @rkern,

Thank you very much because of your fast respond.

I think it is because of np.savez_compressed since the rest of my code is about handling data and machine learning stuffs. I search to find the answers during last two weeks but I cannot find anything. I do not use joblib. I know this is hard to replicate with small data but please support me. I am happy to share the rest of my code via messages.

For more information, my generated data is huge and RAM capacity of the high performance computer can not handle so I using np.memmap as this below tutorial. Basically author just used np.load('./data/X_on_disk.npy', mmap_mode='c') to load the data. I only add one line of code (np.savez_compressed) to save and compress data. 

The tutorial: 
https://colab.research.google.com/github/timeseriesAI/tsai/blob/master/tutorial_nbs/00_How_to_efficiently_work_with_very_large_numpy_arrays.ipynb#scrollTo=4fP-SdZMGuwd

**Comment by rkern** [comment]
*Something* is using `joblib`, and it's not `numpy`. `tsai` has a lot of dependencies, some of which do use `joblib`.

You will not really be able to use `mmap_mode` with compressed `.npz` files in any case. The compression defeats the memory mapping.

**Comment by hieutv85** [comment]
Hi @rkern, 

I just checked my code and there is no thing related to joblib.  I just followed this tutorial as example get to the ideal of how to use mmap_mode but I don't use tsai. I use one line of code from the tutorial (np.load with mmap_mode='r'). 
Are there any other ways that cause the problems of creating many huge files in /dev/shm? I am happy to share my code. 

I used  compressed .npz format since the generated data is too huge (160G for just two input X and y, and I have 15 inputs like that). If you know then could you please suggest me more suitable way to use mmap_mode. 

Thank you very much. Please support me.

**Comment by rkern** [comment]
You may not use `joblib` explicitly, but if any of the machine learning libraries are doing parallel processing, they are likely using `joblib` to do it. That's [the only thing in the world](https://github.com/joblib/joblib/blob/bfd14ebc16ef36fde57b25654a10d5b21ca441d9/joblib/_memmapping_reducer.py#L553-L565) that creates files named `joblib_memmapping_folder_*` in `/dev/shm`

If you can show a self-contained example where `np.savez_compressed()/np.load()` alone creates those files, we'll be happy to follow up with you on it. I will not be examining your entire code to show you exactly where `joblib` is getting used in there.

You can't use `mmap_mode` with `.npz` files, whether compressed or uncompressed. [It will be silently ignored](https://github.com/numpy/numpy/blob/main/numpy/lib/npyio.py#L440-L442); there is no memory-mapping happening in the lines of code that you showed, so those aren't the lines creating files in `/dev/shm`. You can use `mmap_mode` to load individual uncompressed `.npy` files without copying the contents into wired memory. If the arrays are also too large to be help uncompressed on-disk, consider using [`zarr`](https://zarr.readthedocs.io/en/stable/) to represent compressed arrays on-disk and load the contents on-demand similar in style to memory-mapping, at least at the Python level.

I'm going to close this as I am confident that there is no `numpy` bug leading to the behavior you are seeing. If you have one or two followup questions about what I have said, please feel free to ask on the closed issue, but please don't reopen it unless if you have a self-contained reproducer script that only uses `numpy`. If you have more broad-ranging questions about how to do your task, you will have to find [another forum](https://discuss.scientific-python.org/).

**Comment by hieutv85** [comment]
Hi @rkern ,
Thank you very much for your detailed comments. I can understand a lot of things after reading your comments. 

I got the point about joblib. 

It is OK if I upload the input files and my code, then you run the code on your computer to stimulate my experiment. If yes, then may I ask you what your computer’s configuration is. If you any other ideals, then please tell me.  
The script mostly used numpy, sklearn and keras. I can scale down the scope of my experiment (for example extract much smaller set of data, use much smaller time window) and make the script become much simple. About the whole experiment, I used time window with fixed size to extract 32 features from time series data with 1.5 million records. I showed configuration of my clusters below and the running time is about 1 hour (I ran with CPU and did not use GPU), the used RAM is 40% of total RAM. 
The configuration of the clusters:
•	 2x AMD EPYC 7532 2.40GHz 32 cores 256M L3 Cache (Max Turbo Freq. 3.33GHz)
•	1024GB 3200MHz ECC DDR4-RAM (Eight Channel)
•	2x 1.92TB SSD SAS Drives (Raid 1) and 2x 3.84TB SSD SAS Drives (Raid 0)
•	NVIDIA 16GB Graphics Card (For Graphics Only)

Thank you again about your comments about mmap_mode and .npz and suggestions about how to use mmap_mode. 

Please close this topic as your suggestion. I can confirm there is no numpy’s bug here.

**Comment by rkern** [comment]
That is precisely what I said I would not be available to do. Other people on other forums might.
