### ISSUE TITLE
DOC: interpretation of terms in ``quantile`` documentation

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#24588]
### Issue with current documentation:

Please forgive this as-yet-unformed question - but I am struggling with the documentation for `quantile`.   The documentation has this:

"""
Given a vector V of length n, the q-th quantile of V is the value q of the way from the minimum to the maximum in a sorted copy of V.
"""

However - it's not clear to me what this means.   

Assume in what follows that V is sorted.

First "minimum" and "maximum" would normally refer to `min(V)` and `max(V)` but I'm sure we actually mean the minimum and maximum index - so 0 and `n - 1` in Python terms.   So I think this is referring to the distance along the line starting at 0 and ending at n-1, and therefore the "quantile positions" (I made up this term) corresponding to each value in V are:

```python
qps = np.arange(n) / (n - 1)
```

Is that correct?

Is it correct to use the term "plotting positions" for my "quantile positions" `qps`?

Next we have this:

"""
The values and distances of the two nearest neighbors as well as the method parameter will determine the quantile if the normalized ranking does not match the location of q exactly.
"""

I was interested in the cases where the normalized ranking *does* match the location of q exactly - where I'm assuming the "location of q" means my `qps` above.

So I'm taking q for each element `V[i]` to be `qps[i]` - is that right?  Therefore `q = np.quantile(V, qps[i], method=m) == V[i]` for all valid values of m?

If so, it's easy to show that, for many of the methods, that isn't the case.

Just as an example:

```python
n = 4
V = np.arange(n)  # The values.
qps = np.arange(n) / (n - 1)  # Quantile positions
# linear is the default
assert np.allclose(  # Passes
    np.quantile(V, qps, method='linear'), V)
assert np.allclose(. # Fails
    np.quantile(V, qps, method='closest_observation'), V)
```

Have I interpreted these correctly?  If so, or even if not, maybe the docstring needs a rewrite?

**Comment by matthew-brett** [comment]
Sorry - here are the methods where `np.quantile(V, qps[i], method=m) != V[i]`:

```python
# linear is the default
methods = ('linear',  # The efault
           'inverted_cdf',
           'averaged_inverted_cdf',
           'closest_observation',
           'interpolated_inverted_cdf',
           'hazen',
           'weibull',
           'median_unbiased',
           'normal_unbiased')

matches = {}
for method in methods:
    matches[method] = np.allclose(
        np.quantile(V, qps, method=method), V)
matches
```

with output:

```python
{'linear': True,
 'inverted_cdf': True,
 'averaged_inverted_cdf': True,
 'closest_observation': False,
 'interpolated_inverted_cdf': False,
 'hazen': False,
 'weibull': False,
 'median_unbiased': False,
 'normal_unbiased': False}
```

**Comment by mdhaber** [comment]
> Is it correct to use the term "plotting positions" for my "quantile positions" qps?

That looks fair to me. In the notation of reference [1] of `np.quantile`, plotting positions are:

$p_k = \frac{k - \alpha}{n - \alpha - \beta + 1}$

where $n$ is the number of elements, $k \in [1, ..., n]$, and $\alpha$ and $\beta$ are constants. According to the seventh definition of empirical quantiles given in [1], $\alpha = \beta = 1$, so this becomes

$p_k = \frac{k - 1}{n - 1}$

This corresponds with your "quantile positions", so they are a certain choice of "plotting positions".

> Is that correct?

In the sense that `np.quantile`'s default `method='linear'` is based on this definition of plotting positions, yes. This is illustrated by code (similar in spirit to yours):

```python3
import numpy as np
rng = np.random.default_rng(234984259234582435)
n = 10
V = rng.random(size=n)
qps = np.arange(n) / (n - 1)
quantiles = np.quantile(V, qps)
np.testing.assert_allclose(quantiles, np.sort(V))
```

> So I'm taking q for each element `V[i]` to be `qps[i]` - is that right?

As you found, this is true for some methods (if `V` is sorted).

> Therefore `q = np.quantile(V, qps[i], method=m) == V[i]` for all valid values of `m`?

Based on the first sentence of the notes, that is what I might expect. Based on [1], though, I wouldn't expect it to be the case for all methods. Some are based on different conventions for the plotting positions. For instance, `method='weibull'` (Definition 6 in [1]) is based on $\alpha = \beta = 0$, so we have a different identity.

```python3
qps = np.arange(1, n + 1) / (n + 1)
quantiles = np.quantile(V, qps, method='weibull')
np.testing.assert_allclose(quantiles, np.sort(V))
```

> If so, or even if not, maybe the docstring needs a rewrite?

Yes.

**Comment by mdhaber** [comment]
I've looked into this a little more. I'd suggest a rewrite of the notes something like

<img width="674" alt="image" src="https://github.com/numpy/numpy/assets/6570539/663febc7-9e1a-4f10-9889-1c89b980766e">
<img width="679" alt="image" src="https://github.com/numpy/numpy/assets/6570539/36e42fc3-cf47-4e6e-8dfe-34215bd03604">

Would a PR along these lines address your concern @matthew-brett? Some code to check these definitions is below.

<details>

```python3
import numpy as np
rng = np.random.default_rng(356935893569344576)
n = 43  # arbitrary
a = rng.random(size=n)
q = rng.random(size=100*n)  # arbitrarily many
x = np.sort(a)

ms = dict(interpolated_inverted_cdf=lambda q: 0, 
          hazen=lambda q: 1/2, 
          weibull=lambda q: q,  
          linear=lambda q: 1-q, 
          median_unbiased=lambda q: (q + 1)/3,
          normal_unbiased=lambda q: q/4 + 3/8)

for method, mfun in ms.items():
  m = mfun(q)
  j = (q*n + m) // 1 - 1
  g = (q*n + m) % 1

  j = np.asarray(j, dtype=int)
  jp1 = j + 1
  j[j < 0] = 0
  jp1[jp1 > n-1] = n-1

  res = (1-g) * x[j] + g * x[jp1]
  ref = np.quantile(a, q, method=method)
  np.testing.assert_allclose(res, ref)

gs = dict(lower=lambda q: 0, 
          higher=lambda q: 1,
          nearest=lambda q: (q*(n-1) % 1) > 0.5,  
          midpoint=lambda q: 0.5)

for method, gfun in gs.items():
  gfun = gs[method]

  j = q*(n-1) // 1
  g = gfun(q)

  j = np.asarray(j, dtype=int)
  jp1 = j + 1
  j[j < 0] = 0
  jp1[jp1 > n-1] = n-1

  res = (1-g) * x[j] + g * x[jp1]
  ref = np.quantile(a, q, method=method)
  np.testing.assert_allclose(res, ref)

gs = dict(inverted_cdf=lambda q: q*n > 0, 
          averaged_inverted_cdf= lambda q: (1 + (q*n > 0)) / 2)

for method, gfun in gs.items():
  gfun = gs[method]

  m = 0
  j = (q*n + m - 1) // 1
  g = gfun(q)

  j = np.asarray(j, dtype=int)
  jp1 = j + 1
  j[j < 0] = 0
  jp1[jp1 > n-1] = n-1

  res = (1-g) * x[j] + g * x[jp1]
  ref = np.quantile(a, q, method=method)
  np.testing.assert_allclose(res, ref)
```

</details>

**Comment by matthew-brett** [comment]
I wonder whether there is a compromise here, which introduces the problem - as above, and then goes onto the default `linear` case, using something like the current text, while flagging that other methods differ.  Only then, introduce the rather difficult-to-grok general formula from the reference.   My worry it that the formula from [1] does provide a general framework for describing all implementations, but at the expense of making it quite a bit harder to follow the default implementation.

Just as a side-note - I find `x` to be a little confusing as the name for a sorted copy of `a` because we are also implying a plot with plotting positions on the x-axis (which are not `x`) and quantile values on the y-axis (which are not the same as, but closer to `x`).

**Comment by matthew-brett** [comment]
Personally - yes - I would prefer `y` to `x` at least.

I'm sorry for not reading your changes more deeply - but yes - what I meant was close to what you suggest:

> Another possibility is to just to phrase the beginning part as though only the linear method is being described.

but - make clear up front that this is a simplification for the sake of exposition.  I think it's helpful to consider that case, where the plotting positions and quantiles correspond - and then complexify later.

**Comment by mdhaber** [comment]
OK. 

---

Given a sample `a` from an underlying distribution, `quantile` provides a nonparametric estimate of the inverse cumulative distribution function.

By default (`method='linear'`), this is done by interpolating between adjacent elements in ``y``, a sorted copy of `a`:

```
(1-g)*y[j] + g*y[j+1]
```

where the index `j` and coefficient `g` are the integral and fractional components of `q * (n-1)`, and `n` is the number of elements in the sample. 

This a special case of Equation 1 of H&F [1]. More generally, 

- `j = (q*n + m - 1) // 1`, and 
- `g = (q*n + m) % 1`, 

where `m` is defined differently for each value of the `method` parameter below.

| `method`                   | # in H&F [1] | `m`         |
| -------------------------- | ------------ |-------------|
| `interpolated_inverted_cdf`| 4            | `0`         |
| `hazen`                    | 5            | `1/2`       |
| `weibull`                  | 6            | `q`         |
| `linear` (default)         | 7            | `1-q`       |
| `median_unbiased`          | 8            | `(q+1)/3`   |
| `normal_unbiased`          | 9            | `q/4 + 3/8` |

Note that indices `j` and `j + 1` are clipped to the range `0` to `n-1` when the results of the formula would be beyond the allowed range of non-negative indices.

The methods above are all continuous functions of probability `q`. Methods 1-3 of H&F [1] provide three discontinuous estimators, where `j` is defined as above and `m` and `g` are defined as follows.

1. `inverted_cdf`: `m = 0` and `g = int(q*n > 0)`
2. `averaged_inverted_cdf`: `m = 0` and `g = (1 + int(q*n > 0)) / 2`
3. `closest_observation`: `m = -1/2` and `1 - int((g == 0) & (j%2 == 0))`

For backward compatibility with previous versions of NumPy, `quantile` provides four additional discontinuous estimators. Like `method='linear'`, all have `m = 1 - q` so that `j = q*(n-1) // 1`, but `g` is defined as follows.

- `lower`: `g = 0`
- `midpoint`: `g = 0.5`
- `higher`: `g = 1`
- `nearest`: `g = (q*(n-1) % 1) > 0.5`

**Comment by lorentzenchr** [comment]
I think this would be an improvement to the currently difficult reading. You can ping me in a PR if you like.

**Comment by mdhaber** [comment]
Thanks. There were some updates to the original notes with the addition of weights, though. Can you suggest how the new material would be incorporated into this?

**Comment by lorentzenchr** [comment]
At the position where all the methods are explained.
My PR for weights just changed the top and bottom part of the notes section, but all the middle 95% of text is untouched.
