### ISSUE TITLE
BUG: No module name 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by surfettekw** [numpy/numpy#24586]
### Describe the issue:

Please note and check the following:

  * The Python version is: Python3.11 from "/usr/bin/python"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

### Reproduce the code example:

This is not my code - it is for an assignment the problem is I can't even get it to function because the only thing I have close to numpy.core._multiarray_umath is numpy.core._multiarray_umath.cpython-310-x86_64-linux-gnu.so

I would REALLY appreciate assistance - I am newbie but working hard to learn :)

### Error message:

```shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mininet/Downloads/SimulatingNetworks/util/plot_rate.py", line 1, in <module>
    from helper import *
  File "/home/mininet/Downloads/SimulatingNetworks/util/helper.py", line 7, in <module>
    import matplotlib as m
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 104, in <module>
    import numpy
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:
```

### Runtime information:

![image](https://github.com/numpy/numpy/assets/32284645/896254c6-fa12-4cad-8c46-b3459ed75e5b)

### Context for the issue:

Many of the students in my class are having the same exact issue - if we don't get this corrected soon this could be detrimental to our education (and our grades!!!) 

Thank you!!!!!!!

**Comment by surfettekw** [comment]
![image](https://github.com/numpy/numpy/assets/32284645/2e154190-c855-4378-8e8a-2018ffeeccc5)
  Additional image .. Thank you!

**Comment by mattip** [comment]
These two statements conflict:
- The Python version is: Python3.11 
- You have `_multiarray_umath.cpython-310-x86_64-linux-gnu.so`

So you have installed NumPy for python 3.10 (the `310` in the shared object file name) but are using python 3.11. How did you set up this environment? This sometimes happens if people use `sudo pip install` rather than using `apt install ...`. In general, we recommend that you use some form of a virtualenv and install all your dependencies into it, or use your system package manager (apt or yum).

**Comment by surfettekw** [comment]
oh I see that - so this was a script.sh they set up in a VM image they gave us to run through some of these "labs" - what would you do at this point.. downgrade python? Not sure I know how to do that in linux.. but I can try if you feel that is best.. I wish it was as easy as just grabbing the right file and popping it in there.  Or .. can I downgrade numpy? that might be better.. 

Thanks!

**Comment by jacobmcasey** [comment]
Hello @surfettekw,

Seems like there's a version mismatch between the Python you're using and the NumPy installation.

Here's a step-by-step solution:

Confirm the Problem:

Check your Python version: `python --version`
Check NumPy version: ` python -c "import numpy; print(numpy.__version__)"`

Possible Solutions:
-Downgrade Python: If you don't need Python 3.11 specifically, consider downgrading to 3.10.
Reinstall NumPy for Python 3.11:
```
bash
Copy code
pip uninstall numpy
pip install numpy
```
-Use Virtual Environments: This is a best practice to avoid such issues in the future.
```
bash
Copy code
python -m venv myenv
source myenv/bin/activate  # On Windows, use `myenv\Scripts\activate`
pip install numpy
```

**General Recommendations:**
1. Avoid using the system's default Python for development.
2. Always use virtual environments for new projects.

**Comment by rgommers** [comment]
The question was answered, so I'll close this issue.
