### ISSUE TITLE
BUG: Hash of user-defined dtypes changes after unpickling

### ISSUE THREAD

**Issue by li-dan** [numpy/numpy#24595]
### Describe the issue:

The `dtype.__hash__` cache from #5339 is not working properly for user-defined dtypes. The hash value is always zero at the start of a process. This is inefficient, but on its own won't break anything. However, after unpickling, the hash value changes, which breaks code that relies on the hash value, such as dicts.

### Reproduce the code example:

```python
import numpy as np
from numpy.core._rational_tests import rational
import pickle
print(f"{hash(np.dtype(rational))=}")
pickle.loads(pickle.dumps(np.dtype(rational)))
print(f"{hash(np.dtype(rational))=}")
```

### Runtime information:

```python
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
2.0.0.dev0+git20230824.7057b2f
3.10.4 (main, Jul 12 2022, 16:30:02) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
>>> print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '2.0.0.dev0+git20230824.7057b2f',
  'python': '3.10.4 (main, Jul 12 2022, 16:30:02) [GCC 10.3.1 20210422 (Red '
            'Hat 10.3.1-1)]',
  'uname': uname_result(system='Linux', node='...', release='4.18.0-477.15.1.el8_8.x86_64', version='#1 SMP Fri Jun 2 08:27:19 EDT 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}}]
None
```

**Comment by seberg** [comment]
This is not limited to user-defined dtypes, although unlike NumPy ones, they are in practice more often singletons, NumPy dtypes are not in general singletons.
However, it would be good to return the singleton when that makes sense and I don't think we have an attempt at doing so (which includes our own dtype instances).

That would be a good addition.  I am a bit unclear on where the hash value comes from here, which is an independent issue.  The hash may be the object ID/default object hash maybe for user defined dtypes, which is not right (there are more issues with the hash as well...).
