### ISSUE TITLE
DOC: np.load docs don't mention the use of .item

### ISSUE THREAD

**Issue by this-josh** [numpy/numpy#24609]
### Issue with current documentation:

In the [`np.load`](https://numpy.org/doc/stable/reference/generated/numpy.load.html) none of the examples are for dicts which behave slightly differently.

```python
>>> import numpy as np
>>> np.save('del', dict(Q=[2,4]))
>>> r = np.load("del.npy", allow_pickle=True)
>>> r['Q']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
>>> r
array({'Q': [2, 4]}, dtype=object)
```

In fact we must use `r.item()['Q']` but this is not covered in the docs and the error message above does not hint towards `.item()` 

This occurs with v`1.25.2`

### Idea or request for content:

Either the error message or docs should be updated to include this functionality.

**Comment by rgommers** [comment]
`r[()]` works too. This is a standard 0-D array, and you're asking how to get the data out of that. It has nothing to do with either dicts or `np.load`.

**Comment by this-josh** [comment]
Makes sense. I suppose I haven't previously seen [docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.item.html#numpy.ndarray.item) on [how to get data out of a 0-D array](https://stackoverflow.com/a/51150083/13549614) but as you suggest that is a separate issue.
