### ISSUE TITLE
ENH: (Fast) Fractional Fourier Transform

### ISSUE THREAD

**Issue by dirtycomputer** [numpy/numpy#24608]
### Proposed new feature or change:

Please add (Fast) **Fractional** Fourier Transform. 
Until now, numpy only supports (Fast) Fourier Transform. But (Fast) **Fractional** Fourier Transform is a more general algorithm. It will help a lot of researchers. 
paper: https://ieeexplore.ieee.org/abstract/document/536672
some repos: 
https://github.com/nanaln/python_frft/blob/master/frft/frft.py
https://github.com/siddharth-maddali/frft

**Comment by seberg** [comment]
To me, this sounds rather specialized and thus more probably relevant in scipy or as its own standalone package (even if the implementation is maybe simply in terms of existing functions in Python).

**Comment by rkern** [comment]
Agreed.
