### ISSUE TITLE
`np.sort` along last axis / C contiguousity

### ISSUE THREAD

**Issue by eliegoudout** [numpy/numpy#24619]
Hello,

From the doc of [np.sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort):
> All the sort algorithms make temporary copies of the data when sorting along any but the last axis. Consequently, sorting along the last axis is faster and uses less space than sorting along any other axis.

Then I thought "why not transpose before applying then? Since transposing is `O(1)`"

But then I thought that maybe (unsure), transposing actually breaks C contiguousity, and that the above note only applies to C contiguous arrays?

Thus, I think the doc would benefit this added precision. Unless (which I would find very surprising) it doesn't need C contiguousity to hold, in which case replacing `np.sort` with `transposing -> np.sort -> transposing` would seem natural.

Thanks for reading.
Élie

**Comment by seberg** [comment]
The C contiguous part of the docs are right.  But they are confusing this a bit with "last axis" which isn't necessarily contiguous (or even the "fast" axis in memory).
So the note on the last axis being faster is *typically* correct, but not generally.

Transposing doesn't change memory layout and thus doesn't change contiguity.

**Comment by mdhaber** [comment]
@eliegoudout @seberg how about:
> For performance, `sort` makes a temporary copy if needed to make the data [contiguous](https://numpy.org/doc/stable/glossary.html#term-contiguous) in memory along the sort axis. For even better performance and reduced memory consumption, ensure that the array is already contiguous along the sort axis.

**Comment by seberg** [comment]
Sounds fair, I could imagine a future where we change it. (Although, I wouldn't be surprised that copying isn't practically always better almost always when the data isn't already practically sorted.)

**Comment by eliegoudout** [comment]
I think it is indeed pretty fair. Should we specify that this note applies for C contiguousity and not fortran?

**Comment by mdhaber** [comment]
> Should we specify that this note applies for C contiguousity and not fortran?

Is that right @eliegoudout? I assumed that if the array were F-contiguous it would also copy to make the sort axis contiguous along the appropriate axis (not the last, in that case), but I didn't check the code.

**Comment by seberg** [comment]
This has nothing to do with C vs. F order.  "contiguous along the sort axis" is correct and to the point, you could only add that this is often the last axis (-1).  I don't care much if not everyone understands it, ideally this should be buried in the notes somewhere anyway.

**Comment by eliegoudout** [comment]
Thanks @seberg for clarifying, I got confused with the current (wrong) doc:

> All the sort algorithms make temporary copies of the data when sorting along any but the last axis. Consequently, sorting along the last axis is faster and uses less space than sorting along any other axis.

I think what @mdhaber wrote is much better and completely clarifies the situation.
