### ISSUE TITLE
DOC: IndexError message for boolean indexing word choice

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [numpy/numpy#24624]
### Issue with current documentation:

Not sure if this should go in "bug" or "doc", but treating error message as a doc issue.

The error message for boolean fancy indexing with the wrong shape refers to "dimension" for two different concepts: the axis number, and the length of that axis.  By itself it's fine, but can be mildly confusing appears deep in some code where I'm not sure the dimensions of the array that's being indexed.

```python
import numpy as np
arr = np.zeros((3,2))
mask = np.array([True, True])
arr[mask]
```
```
IndexError: boolean index did not match indexed array along dimension 0; 
dimension is 3 but corresponding boolean dimension is 2
```

### Idea or request for content:

Perhaps change it to 
```
IndexError: boolean index did not match indexed array along axis 0; 
dimension is 3 but corresponding boolean dimension is 2
```

Maybe it's a bit of bikeshedding, but it seems clearer to me to use "axis" instead of "dimension" for the first case.

**Comment by richardson312** [comment]
`axis` is probably the correct terminology here; at least as far as I know, it _does_ seem to be referred to as `axis` in most documentation and errors that I've seen.

Example:
`IndexError: index 4 is out of bounds for axis 0 with size 3`
