### ISSUE TITLE
BUG: `blas_thread_server` from libopenblas slows down unrelated calculations

### ISSUE THREAD

**Issue by NAThompson** [numpy/numpy#24639]
### Describe the issue:

After source building python3.12 and running under `perf`, I noticed that my benchmarks were spending a large fraction of their time in `blas_thread_server`. More specifically, if we take the following benchmark:

```python
import pytest

@pytest.mark.benchmark
def test_float_constructor(benchmark):
    benchmark(float, "0.0")
```

and run

```
pip install --pre numpy # installs 1.26.0b1 as of the time of this writing
perf record -g python3.12 -m pytest float_constructor_benchmark.py
perf report -g
```

we see that 14% of the runtime is spent in `numpy.libs/libopenblas64_*...so`, and more specifically the following two instructions in `blas_thread_server` are 95% of that time:

```armasm
mrs x1, cntvct_el0
mrs x3, cntfrq_el0 // couldn't this be cached rather than read every call?
```

I feel fairly confident that I'm seeing [this](https://github.com/xianyi/OpenBLAS/blob/c3f2a3c0ca8d4a3700f81f176dd3f1bc08cff3dd/common_arm64.h#L105), as the full asm is

```armasm
74: ldr x0, [x19]
cbnz x0, e4
nop
nop
nop
...
isb
mrs x1, cntvct_el0
mrs x3, cntfrq_el0
clz w3, w3
ldr w0, [x24]
lsl x1, x1, x3
sub w1, w1, w2
cmp w1, w0
b.ls 74
```

Now, I cannot run `pytest-benchmark` without `numpy`, so I cannot actually exhibit performance gains from removing `numpy` from the stack. However, the following (admittedly imperfect) code does indicate that merely importing `numpy` causes other workflows to be slower:

```
$ python3 -m timeit "import numpy as np; float('0.0')"
1000000 loops, best of 5: 264 ns per loop
$ python3 -m timeit "float('0.0')"
1000000 loops, best of 5: 109 ns per loop
```

### Reproduce the code example:

```python
import pytest

@pytest.mark.benchmark
def test_float_constructor(benchmark):
    benchmark(float, "0.0")
```

### Runtime information:

```python
>>> print(numpy.__version__)
numpy version 1.26.0b1
>>> sys.version
3.12.0rc1+ (heads/3.12:d5c2d453fd) [GCC 12.1.0]
>>> numpy.show_runtime()
system='Linux', release='6.3.0-asahi-6-1-ARCH', machine='aarch64'
```

### Context for the issue:

A comment on importance: I consistently see `blas_thread_server` as the second largest contributor to the total runtime of my benchmarks, only behind `_Py_Eval_EvalFrameDefault`.

**Comment by seberg** [comment]
> $ python3 -m timeit "import numpy as np; float('0.0')"

That isn't the correct way to "merely import numpy", the correct way would be:
```
python  -m timeit -s "import numpy as np" "float('0.0')"
```

Yes, openblas will need a while during import time, this is expected and that is what you are profiling.  To me it sounds like you are not expecting to profile import time, so I am going to assume that this is sufficient as an explanation and close the issue.

**Comment by seberg** [comment]
> false trail-the pytest benchmark is the real issue.

Yes, and it instead proofs that import overheads are a relevant factor that needs to be taken into account.  So please provide more details to show that this is not just import time related.  Or I don't know, use `@pytest.mark.benchmark(min_time=2, max_time=2)` to ensure you are sampling only/mostly the actual benchmark.  Maybe try using `perf -D200` (skipping the first 200 ms after which imports should be finished).

**Comment by rgommers** [comment]
It's not impossible that this is a real issue, but I'm not seeing it:
```python
>>> 'numpy' in globals()
False
>>> 'np' in globals()
False
>>> %timeit float('0.0')
76.4 ns ± 0.242 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
>>> import numpy as np
>>> %timeit float('0.0')
76.2 ns ± 0.217 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

>>> np.show_config(mode='dicts')['Build Dependencies']['blas']
{'name': 'openblas', 'found': True, 'version': '0.3.23', 'detection method': 'pkgconfig', 'include directory': '/home/rgommers/mambaforge/envs/scipy-dev/include', 'lib directory': '/home/rgommers/mambaforge/envs/scipy-dev/lib', 'openblas configuration': 'USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 PRESCOTT MAX_THREADS=128', 'pc file directory': '/home/rgommers/mambaforge/envs/scipy-dev/lib/pkgconfig'}
```

If this is a problem, it probably depends on the exact settings with which the OpenBLAS binary that you are using was built.

**Comment by chandan-fujitsu-research** [comment]
Hi,

Even i am getting same performance as shared by  Mr. NAThompson

do we expect the time consumption by blas_thread_server or any other possible way to reduce it?

please see the perf report of utilization:
![image](https://github.com/numpy/numpy/assets/138875466/d20a5c61-adac-4dc4-9ea3-2e04e166613d)

**Comment by chandan-fujitsu-research** [comment]
I guess i know the reason why it is taking time,

Both bineris are related to numpy and scipy are taking more time. The reason is, Spare matrix implementation is not optimized in openblas. [spblas]
