### ISSUE TITLE
ENH: Support for the Feather data format

### ISSUE THREAD

**Issue by alkhwarizmi** [numpy/numpy#24688]
### Proposed new feature or change:

I propose to create serialising and deserialising procedures for ndarrays in the feather data format. They could be similar to Pandas `to_feather` and `from_feather`, but even better they would allow to store and load a list of numpy arrays.

**Comment by rkern** [comment]
AFAICT, Arrow/Feather are limited to 1D arrays (or heterogeneous collections of such in dataframes). For the things that Arrow/Feather does support, `pyarrow.feather` already does the job. We would not be able to depend on it as it [depends on `numpy`](https://github.com/apache/arrow/blob/main/python/setup.py#L452).

Consequently, I think this is a no-go.

One could probably devise a format/conventions built on top of Feather where an N-D array is represented as a flattened collection of 1-D columns stored in Feather, but I think that has to live outside of `numpy`.

**Comment by rkern** [comment]
Of course, the N-D data can just be flattened, and Arrow stores the flattened data with some custom metadata. And it looks like there is experimental N-D "Tensor" support in Arrow. It's at this point that we're leaving "Feather" per se and just working with Arrow's IPC format and `pyarrow`'s API directly.

But it's still something that one really needs to use `pyarrow` to work with, so still nothing we can do inside of `numpy`.
