### ISSUE TITLE
BUG: Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.         Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.

### ISSUE THREAD

**Issue by gfvxgd2k** [numpy/numpy#24683]
### Describe the issue:

when i train custom model using ultralytics yolov8 with multi-gpu(DDP use) . 
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
this error occurs. 
lowering the version to 1.24 shouldn't cause any problems.

### Reproduce the code example:

```python
from ultralytics import YOLO

model = YOLO()
results = model.train(device='0,1,2,3')
```

### Error message:

```shell
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
```

### Runtime information:

numpy 1.25.2
python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]

**Comment by mattip** [comment]
How did you install numpy and the other libraries in your environment? We don't supply NumPy linked with MKL, but the error message suggests this solution, maybe it will help?
```
import numpy
from ultralytics import YOLO
...
```

**Comment by seberg** [comment]
Closing, not related to NumPy, and I think Matti gave all the help we can give.
