### ISSUE TITLE
BUG: linalg does not raise error on a matrix that is not invertible

### ISSUE THREAD

**Issue by hongkonghector** [numpy/numpy#24684]
### Describe the issue:

np.linalg sometimes wrongly inverts a matrix that is not invertible. 

### Reproduce the code example:

```python
import numpy as np

'''
Non-invertible matrix . 
Determinant is zero.
I have tried scipy.linalg and the same behavior occurs. 
'''
A = np.array( [[2, 4],
             [3, 6] ])


A_inv = np.linalg.inv( A)
#No error is raised. 

B = A @ A_inv

print(B) 
'''
prints 
[ [ 0. 0.]
 [0. 1.]]
But if the matrix were invertible, we should get the identity. 
'''


'''
Try to invert the same matrix but exchange diagonal entries.
The determinant should still be zero.
But now linalg correctly detects the error. 
'''

A = np.array( [[2, 3],
             [4, 6] ])

#Now a LinAlgError: Singular Matrix occurs. 
A_inv = np.linalg.inv( A)
```

### Runtime information:

np version 1.23.5
3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
AttributeError: module 'numpy' has no attribute 'show_runtime'

**Comment by rkern** [comment]
See my comment https://github.com/numpy/numpy/issues/23793#issuecomment-1557951725 on a similar report.

**Comment by hongkonghector** [comment]
Thank you. I will close this issue.
