### ISSUE TITLE
ENH: <Please write a comprehensive title after the 'ENH: ' prefix>

### ISSUE THREAD

**Issue by NirmalSankalana** [numpy/numpy#24727]
### Proposed new feature or change:

Softmax Function

**Comment by WarrenWeckesser** [comment]
The softmax function is available in SciPy as [`scipy.special.softmax`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.softmax.html).

This is not a function that will be added to NumPy, so I'm closing the issue.
