### ISSUE TITLE
BUG: `update.py` (numpy.org) uses deprecated `pkg_resources`

### ISSUE THREAD

**Issue by charris** [numpy/numpy#24724]
Looks like `update.py` (numpy.org) needs updating

```
charris@fc [merge (main)]$ python3 update.py
/home/charris/Workspace/numpy.git/doc/build/merge/update.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

**Comment by rgommers** [comment]
It's not clear to me where that file comes from, or why you need to invoke a file in a generated build directory. Can you elaborate?

**Comment by charris** [comment]
It's here: https://github.com/numpy/doc/blob/main/update.py
