### ISSUE TITLE
numpy.org home page shows 1.25 as latest release.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#24744]
Not much add, The latest_version seems to be set correctly in the `_static/versionwarning.js` file in the numpy/doc repository. I did note one error I made in the drop down version list, but that looks unrelated.

**Comment by rgommers** [comment]
https://numpy.org/doc/stable/ is 1.26, seems correct to me?

**Comment by mattip** [comment]
Maybe a reference to the text in black at the top of the page
![Screenshot from 2023-09-19 12-20-30](https://github.com/numpy/numpy/assets/823911/6e1e3228-4bd7-4cb9-a647-31d8ee77f8cc)

**Comment by mattip** [comment]
Found it, that comes from [here](https://github.com/numpy/numpy.org/blob/268abd17b07842ea1d56fa665dd9f0387f493dc2/content/en/config.yaml#L13)

**Comment by charris** [comment]
@rgommers The 1.25 entry also points to the 1.26 documentation, that is the error.

The button update needs to be documented for the next time around.  I'll just list the files here for later reference:

- content/en/config.yaml
- content/ja/config.yaml
- content/pt/config.yaml

**Comment by rgommers** [comment]
> It would also be nice to get the new "news" snippets translated. Do we have a protocol for that? 

No need to open an issue, the Crowdin platform sends out notifications to translators already each time new untranslated strings appear.
