### ISSUE TITLE
ENH: typing: make the requirement to add np.dtype() more consistent

### ISSUE THREAD

**Issue by mikolajz** [numpy/numpy#24757]
### Proposed new feature or change:

It seems that right now it a bit random. In the following code:
```
import numpy as np

x = np.ones((1, 2), dtype=np.int32)  # ERROR
y = np.zeros((1, 2), dtype=np.int32)  # OK
z = np.zeros_like(x, dtype=np.int32)  # ERROR
```

I get errors for line 3 and 5 (I need to replace it with `dtype=np.dtype(np.int32)`), but not for 4:
```
test.py:3: error: Argument "dtype" to "ones" has incompatible type "type[signedinteger[Any]]"; expected "Optional[dtype[Any]]"  [arg-type]
test.py:5: error: Argument "dtype" to "zeros_like" has incompatible type "type[signedinteger[Any]]"; expected "Optional[dtype[Any]]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

It would be nice for it to be consistent.

**Comment by BvB93** [comment]
It's difficult to tell more with the currently provided information, but seems like numpy's type annotations are being overwritten by a third-party stub-only package as the current behavior simply does not match the respective function's type annotations.
Do you have any idea which package in your current environment could be the culprit? Also, what's the numpy, mypy and python version? How are you running mypy?

**Comment by mikolajz** [comment]
Oops, I forgot to uninstall numpy-stubs (I had it from `git+https://github.com/numpy/numpy-stubs@f3c6315738489983f5f37e1477ac68373d71b470`). After removing them, the file passes typechecks. Sorry for the false report.
