### ISSUE TITLE
ENH: Math functions as methods of the numpy.ndarray class

### ISSUE THREAD

**Issue by PanTheRiceMan** [numpy/numpy#24754]
### Proposed new feature or change:

Chaining calculations as calls to methods is often times more convenient than calling the functions from the numpy module on arrays. The order of operations easier to understand: left to right instead of right to left. The code is also shorter.

Instead of typing:
```python
y = np.sqrt(np.mean(np.power(x,2)))
``` 

The calculation would be more convenient using:
```python
y = x.pow(2).mean().sqrt()
``` 

PyTorch uses this syntax, which I find easy to understand and easy to read.

**Comment by rgommers** [comment]
NumPy arrays do have methods:

```python
>>> x = np.random.rand(4, 3, 2)
>>> x.mean(axis=2).std()
np.float64(0.17081320827269902)
>>> x.mean(axis=2, keepdims=True).std(axis=2)
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
>>> x.mean(axis=2).std(axis=2)
>>> x.mean(axis=2).std(axis=1)
array([0.06664678, 0.04328043, 0.05496028, 0.27238433])
```

You seem to want a `.pow` method, but that's supported by the builtin `**` operator:
```python
>>> (x**2).mean(axis=0).std()
np.float64(0.13452710440384558)
```

The `ndarray` object currently has 72 methods and attributes, and we don't want to increase that unless there's a very good reason. It seems like we provide pretty much what you want already, so I'll close this issue. Thanks @PanTheRiceMan.
