### ISSUE TITLE
`LICENSES_bundled.txt` content not included in license file for wheels in 1.26.0

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#24764]
I noticed this when reviewing gh-24753. I thought this was taken care of in the wheel build scripts, however that is a different kind of concatenation (for the vendored shared libraries, `libopenblas` & co):
```
# Update license
if [[ $RUNNER_OS == "Linux" ]] ; then
    cat $PROJECT_DIR/tools/wheels/LICENSE_linux.txt >> $PROJECT_DIR/LICENSE.txt
elif [[ $RUNNER_OS == "macOS" ]]; then
    cat $PROJECT_DIR/tools/wheels/LICENSE_osx.txt >> $PROJECT_DIR/LICENSE.txt
elif [[ $RUNNER_OS == "Windows" ]]; then
    cat $PROJECT_DIR/tools/wheels/LICENSE_win32.txt >> $PROJECT_DIR/LICENSE.txt
fi
```

When [PEP 639](https://peps.python.org/pep-0639/) finally arrives we get a `license-files` field that allows listing multiple license files in metadata. But for now we need to continue concatenation these files together for the wheels we distribute. I'll open a PR to fix this.

**Comment by mattip** [comment]
The `LICENSE_bundled.txt` refers to licenses like [`numpy/linalg/lapack_litee/LICENCES.txt`](https://github.com/numpy/numpy/blob/d0c6cdf8da4db4a2240dbbc6baa64bc01f27e05b/LICENSES_bundled.txt#L7) that it seems are not included in the 1.26 meson-produced wheel. Maybe the text should include a link to the numpy repo with a text like "at the appropriate tag"?
