### ISSUE TITLE
DOC: Inaccurate statement regarding array indexing and slicing?

### ISSUE THREAD

**Issue by djramones** [numpy/numpy#24769]
### Issue with current documentation:

In the [Slicing and striding](https://numpy.org/doc/1.26/user/basics.indexing.html#slicing-and-striding) section of the indexing basics page, it says:

> If the selection tuple has all entries `:` except the *p*-th entry which is a slice object `i:j:k`, then the returned array has dimension *N* formed by concatenating the sub-arrays returned by integer indexing of elements *i, i+k, …, i + (m - 1) k < j*.

My understanding of this is that, if, say, I have a simple 3-D array `a`:

```
a = np.arange(27).reshape(3, 3, 3)
```

And I have a selection:

```
a[:, 1:3, :]
```

The doc seems to say that I should get the same selection with:

```
 np.concatenate([a[:, i, :] for i in range(1, 3)])
```

But this has the wrong shape, `(6,3)`, instead of `(3, 2, 3)`, and that's because integer indexing reduces dimensionality by 1 (as explained in just the previous bullet point on the page). Adding `axis=1` to `concatenate` won't help.

### Idea or request for content:

Unless I'm mistaken, I believe the doc should instead say that the sub-array returned by integer indexing should be expanded to match the original dimensionality *N* before concatenation in order to get the same results. The clunkier but correct code is

```
np.concatenate([np.expand_dims(a[:, i, :], axis=1) for i in range(1, 3)], axis=1)
```

Which returns an array of shape `(3, 2, 3)`.

**Comment by jakevdp** [comment]
I think what the text is getting at is something like this:
```python
np.stack([a[:, i, :] for i in range(1, 3)], axis=1)
```
I don't think this is an inaccuracy of the documentation, but rather a rhetorical use of the word "concatenating" that does not directly align with the API of the `np.concatenate` function.

**Comment by djramones** [comment]
Ah, that's exactly it, a stack. Perhaps it could be clearer if it said something like:

> …formed by **stacking** the sub-arrays…along the *p*-th axis…

With “stacking” linked to the `numpy.stack()` doc, though the sentence is already dense as it is.

**Comment by shubhalgupta** [comment]
@djramones is this issue still open?

**Comment by djramones** [comment]
@shubhalgupta I just submitted PR #24996 for this.
