### ISSUE TITLE
DOC: numpy.std: default value for ddof

### ISSUE THREAD

**Issue by jkingdom3** [numpy/numpy#24800]
### Issue with current documentation:

The default value for ddof is given as zero. However, in my version of numpy (1.25.1) the default value is ddof=1.
![Screenshot 2023-09-25 19 30 12](https://github.com/numpy/numpy/assets/49148333/5d6ee15e-8a04-4d02-ad76-4c6c332e9942)

### Idea or request for content:

Documentation needs to be amended to give the default behaviour as ddof=1.

**Comment by rkern** [comment]
Your `data` object is not a `numpy.ndarray`. It's a `pandas.Series`, which uses a different default.
