### ISSUE TITLE
A reference link is invalid

### ISSUE THREAD

**Issue by RyotaBannai** [numpy/numpy#24826]
### Issue with current documentation:

A reference link is invalid in documentation.
The one is the link in `view` in a sentence, A record array representation of a structured array can be obtained using the appropriate [view](https://numpy.org/devdocs/user/numpy-ndarray-view):, in [this section](https://numpy.org/devdocs/user/basics.rec.html#record-arrays)

Thanks

**Comment by mattip** [comment]
Right, the source here https://github.com/numpy/numpy/blob/49858fc0ee0de32695209dfed8ffc7a8e0c02572/doc/source/user/basics.rec.rst?plain=1#L671. I think it should be using `numpy.ndarray.view`  with `.` instead of `-`.

**Comment by RyotaBannai** [comment]
Thank for your attention.
With your help, I guessed that the correct link would be `https://numpy.org/doc/stable/reference/generated/numpy.ndarray.view.html#numpy.ndarray.view` from other `<...>` code in the source.

**Comment by mattip** [comment]
Right. The html is generated using [sphinx](https://www.sphinx-doc.org/en/master/) from [RST](https://docutils.sourceforge.io/rst.html) files, which is why I linked the source. For more information on building the documentation from source, see https://numpy.org/devdocs/dev/howto_build_docs.html

**Comment by RyotaBannai** [comment]
Thank you for the links. 
These help my understandings.

**Comment by RyotaBannai** [comment]
Thank you for the links.
These help for my understanding.

**Comment by shubhalgupta** [comment]
@mattip is this issue still open?

**Comment by mattip** [comment]
Yes.

**Comment by shubhalgupta** [comment]
Thanks!

**Comment by mdhaber** [comment]
@rossbar It looks like this can be closed, since you merged the fix. It seems to render correctly in the [dev version of the documentation](https://numpy.org/devdocs/user/basics.rec.html)
<img width="772" alt="image" src="https://github.com/numpy/numpy/assets/6570539/d780548c-8be1-4f36-8dea-aa56d4fea0fa">

and the link works.

**Comment by rossbar** [comment]
Indeed, thanks @mdhaber !
