### ISSUE TITLE
BUG: Memory Cost of String Array is Far Higher than Necessary

### ISSUE THREAD

**Issue by gaotako** [numpy/numpy#24822]
### Describe the issue:

In the array with dtype `str_` or `bytes_`, I find that it will align the memory of every element with padding.
I am not sure if it is for vectorization efficiency, but if I occasionally have a long string in a very long list (I believe such tail distribution is common), it is extremely memory inefficent.

NumPy array of strings is using far more memory than necessary.
I believe the second implementation should be the expected memory cost. But if it is designed to work in such way, rather than a bug, please close this post.
Thank you.

### Reproduce the code example:

```python
# Here is an extreme example:

# Import.
import numpy as onp

# Raw data.
n = 1000
string_list = [b"a"] * n + [b"b" * n]

# Use an array of strings.
string_array1 = onp.array(string_list, dtype=onp.bytes_)
print(string_array1.nbytes)

# Use the combination of a fully concatenated string and an array of indices.
string_array2_data = onp.array(b"".join(string_list), dtype=onp.bytes_)
string_array2_ends = onp.array([0] + [len(it) for it in string_list])
string_array2_ends = onp.cumsum(string_array2_ends)
print(string_array2_data.nbytes + string_array2_ends.nbytes)

# Output
# >>> 1001000
# >>> 10016
```

### Runtime information:

```bash
$ python -c "import sys, numpy; print(numpy.__version__); print(sys.version); print(numpy.show_runtime())"
1.25.2
3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
[{'numpy_version': '1.25.2',
  'python': '3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='dev-dsk-gajianfe-1a-c107057b.us-east-1.amazon.com', release='5.10.192-159.736.amzn2int.x86_64', version='#1 SMP Tue Aug 29 20:21:49 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX'],
                      'not_found': ['AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'SkylakeX',
  'filepath': '/local/home/gajianfe/MiniConda3/envs/Default/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-5007b62f.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None
```

### Context for the issue:

I am coding for some customer name processors on bussiness database, and the database contains names (roughly 20M names) whose length ranging from 1 to more than 100, but mostly was around 15. I want to utilize numpy functions like vectorized `.rstrip()` or other funcions like `unique` for better speed under Python environment, however the memory cost of storing those strings together in a NumPy array is higher than acceptable expectation (nearly 8 times than expectation).

**Comment by jakevdp** [comment]
Hi - thanks for the report! I believe this is working as expected: currently, NumPy only supports constant-width string dtypes. There is currently a proposal on the table to support variable-width string dtypes; see [NEP 55](https://numpy.org/neps/nep-0055-string_dtype.html) for details.
