### ISSUE TITLE
BUG: Importing embedded NumPy hangs on Windows

### ISSUE THREAD

**Issue by car-bianco** [numpy/numpy#24833]
### Describe the issue:

Hello everyone!

I am working on a project in which usage of Numpy in a scenario with embedded subinterpreters is required. While I know this is not supported due to GIL shenanigans, I would like to at the very least be able to import numpy (and thus, reach the warning on subinterpreter usage).

On Linux, I am able to import numpy just fine (as long as I only do in a single subinterpreter).
On Windows, on the other hand, numpy freezes as soon as `getlimits.py` tries to use the `np.longdouble` data type. While I do not currently have debug information, I guess `_multiarray_umath.pyd` is trying to release the GIL, and thus deadlocks.

My main questions are:
* What does Windows do differently from Linux re. `np.longdouble`?
* What does `np.longdouble` do differently from other data types such as `float64` and so on?
* Are there any known workarounds (apart from aliasing `longdouble` to `double` in `__init__`)?

### Reproduce the code example:

```python
import numpy as np
```

### Runtime information:

Numpy 1.22.2
Windows Server 2016 x64
Python 3.10.4

**Comment by mattip** [comment]
I doubt it is a GIL problem. We have seen that exact problem before, for instance [here is a work-around](https://github.com/numpy/numpy/issues/17747#issuecomment-932739490) for windows and floating point error traps, and [here](https://github.com/numpy/numpy/issues/20895) is an issue where OpenCV/gevent change the floating point math registers.

**Comment by car-bianco** [comment]
Hi @mattip ,

None of the proposed workarounds seem to help. Here's the configuration as output by `np.show_config()`:
```
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX,AVX512_CNL
```

As far as I can see from an interactive console, both `np.longdouble` and `np.longfloat` alias to `np.float64`. But float64 works, while the others do not...

**Comment by seberg** [comment]
@car-bianoc, I agree with Matti that the most likely problem is floating point traps kicking in.  The question is in *what* you embed the Python interpreter and how that is compiled.

The work-around isn't some python stuff or even NumPy related (e.g. try executing `float("inf") - float("inf")` it likely causes the same type of issue).

While I am surprised about hangs, maybe a hang is to be expected due to some other reason.  The point is, some toolchains (Delphi, Fortran, ...) trap on FPE errors, which is incompatible with Python in general and NumPy more so.

For details/deeper workaround, please see this discussion: https://github.com/numpy/numpy/issues/20504 I don't want to try to dig out the exact incantations that probably help.

**Comment by car-bianco** [comment]
Upgrading to Numpy 1.26.0 did not solve the issue.

This is the backtrace when building Python with debug info:

![image](https://github.com/numpy/numpy/assets/18487753/3e5b9701-5b4b-4c2b-91a6-6e9d86a46d83)

At least judging from this, it indeed looks like a GIL issue... which makes it even weirder that it's only happening when using `np.longdouble`.

**Comment by ngoldbaum** [comment]
The place it's getting stuck is a few stack frames up, inside `NumPyOS_ascii_strtod_plain`. It's trying to acquire the GIL in the `NPY_ALLOW_C_API` macro, but something else is still holding the GIL so it deadlocks there. To debug further you'd need to find the thread that is holding the GIL and see what it's doing that is preventing it from releasing the GIL.

**Comment by wu-vincent** [comment]
I recently encountered the same issue when trying to import numpy in my embedded interpreter in a C++ application. I narrowed it down to the `_multiarray_umath.pyd`. After a bit of searching on Google, I found that this issue still exists in `numpy` 2.0.0.

My temporary workaround is to `import numpy` **once right after** initializing the interpreter on the main thread before releasing the GIL.

```python
pybind11::initialize_interpreter()
pybind11::module::import("numpy");
// other stuff
```

This issue may be relevant too. https://github.com/pybind/pybind11/issues/2197

**Comment by wu-vincent** [comment]
@seberg Thanks for the prompt response. I agree, the issue seems to be external to `numpy`.

Of course, GIL must be held while importing; the thing is, it somehow needs to be imported once **immediately** after creating the interpreter. Hopefully, this info can help someone with the same issue.
