### ISSUE TITLE
BUG: DEPRECATION: mpc 0.0.4 has a non-standard dependency specifier numpy>=1<2

### ISSUE THREAD

**Issue by giuseppefilippone** [numpy/numpy#24850]
### Describe the issue:

Hi!

I was updating numpy in Python 3.8 and I got the following warning:

> DEPRECATION: mpc 0.0.4 has a non-standard dependency specifier numpy>=1<2. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of mpc or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

Can I solve the problem somehow? Thank you in advance!

### Reproduce the code example:

```python
No response
```

### Runtime information:

No response

**Comment by rgommers** [comment]
Hi @giuseppefilippone, this is something that should be fixed in `mpc`, because that's the package with the incorrect dependency specifier. Can you please try that? 

I'll close this issue, because it's not a problem in numpy.
