### ISSUE TITLE
C-API changes for NumPy 2.0

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#24855]
**Please don't hesitate to edit this issue**

The board has some other issues as well, but I would like to list (and add) an issue to track the main C-API Changes we are anticipating/preparing for 2.0.

We can and *should* do these changes now.  There may be downstream CI fallout, but SciPy started to adapt so we can try to start enforcing NumPy 2.0 compilation.

Listing mostly changes here that I think are relatively important to do.

**"Smaller" changes**

* [x] Removal of many rarely used/unused functions (including many that were already deprecated)
* [x] Modifying the default integer on 64-bit windows: make the default `intp`: gh-24224
  * The PR was in a good shape, but other Python changes created a lot of merge conflicts :(.
  * IMO, we just need to do this and see what breaks, unless someone can spend a lot of time.
* [x] Modify `intp` to be `ssize_t` (`Py_ssize_t` as `ssize_t` is nonstandard).  This is irrelevant on most platforms, but better matches how we use it.  It might mean niche platforms like OpenVMS will require additional fixes (although they are probably broken in many subtle ways and this will fix that).
  * It might be good to allow `np.dtype("n")` and `np.dtype("p")`, but we can do so via Python aliases in principle.  (I.e. make sure p and P map to `intptr_t` or `size_t` equivalence even on niche platforms.)
  * Ensure that NumPy 2.0 requires `NPY_TARGET_VERSION >= NPY_2_0_API_VERSION` when those types should differ (otherwise ABI is broken).
* [x] Bump `NPY_MAXARGS` and `NPY_MAXDIMS`.  To do this, we have to do one or both of:
  * Add compat inline functions to access all of the iterator versions (or a new struct/version of the iterators for NumPy internal things)
  * Live with the fact that some functions will **not** support high dimensional arrays.
  * I had a start on this but it got stalled a bit last time because @mattip didn't much like the idea of not removing the limit completely.  I agree to target removing the limit completely (i.e. remove `NPY_MAXDIMS` as a public constant), but I would prefer to be pragmatic and live with the fact that we will limit to 64dims/args in some ufuncs parts for now and 32dims in some iterator paths.  (Basically, consider especially the 32dim limits as a minor bug, but due to iterator use hard to fix.)
* [ ] @mattip would like to not have any API returning borrowed references.  I am not sure how much we have, but I agree.
  * If API is not very niche, I would lean towards simply adding a non-borrowing version of the API.
* [ ] Consider moving `auxdata` in the strided-loop signature into `context` struct:
  * We should aim to make the new DType/UFunc API public.  The main thing that makes me pause is the ufunc strided/inner loop signature.  I am considering moving `auxdata` to be part of the struct passed in (since we commonly don't use `auxdata`).
* [x] ~[Expose PyArray_Pack](https://github.com/numpy/numpy/issues/23893). Maybe deprecate PyArray_SETITEM?~ Part of experimental API exposure, not going to backport as Nathan didn't think it worthwhile enough.
* [ ] Vet the new DType/UFunc API for const users.  E.g. `resolve_descriptors` should pass the original descriptors with `PyArray_Descr *const *`, since you are not allowed to mutate it.

**Larger Changes**

* [x] Make the `PyArray_Descr` struct opaque.
  * C code will have to use new, version specific, static-inline functions to fetch some struct members.
  * Cython 3 code should not mind this change.
* Hiding structs further structs.

**Comment by mattip** [comment]
Thanks for getting this started. I would add 
- [ ] review and remove much of `npy_3kcompat.h`
- [ ] Remove `PyArray_REFCOUNT` and `NPY_REFCOUNT`
- [ ] Follow the include paths from the `__init__.cython-30.pxd` files and make sure they are clean for use with `cimport numpy` and the `LIMITED_API`, [this issue](https://github.com/cython/cython/issues/5697) points to the use of `PyUnicodeObject` in `numpy/arrayscalars.h`, maybe there are more?

**Comment by rgommers** [comment]
>  Modifying the default integer on 64-bit windows ... IMO, we just need to do this and see what breaks, unless someone can spend a lot of time.

+1 for that approach. Pushing it in and then seeing if anything unexpected pops up downstream seems more pragmatic than trying to anticipate more than you already have.

**Comment by rgommers** [comment]
> but I would prefer to be pragmatic and live with the fact that we will limit to 64dims/args in some ufuncs parts for now and 32dims in some iterator paths.

That seems very reasonable to me. There's a lot of higher-prio stuff to do, and this seems like a pretty minor concession.

> Modify `intp` to be `ssize_t` (`Py_ssize_t` as `ssize_t` is nonstandard).

gh-24867 documents it as `intptr_t`, which I think is more correct?

**Comment by seberg** [comment]
> https://github.com/numpy/numpy/pull/24867 documents it as intptr_t, which I think is more correct?

They are different things in principle (not in practice, OpenVMS was one platform, but otherwise it is probably only machines with segmented address space, which is de-facto nonexisting).  We have quite a bit of code that uses it for `ssize_t` and assumes it is identical to `Py_ssize_t`, I think.  Thus, I am saying we should change it (even if it is unfortunate that `intp` name-wise is clearer as `intptr_t`)

**Comment by seberg** [comment]
I started a bit on changing `NPY_MAXDIMS`, but it is blocked by the intp default integer change (because that has some generic setup for runtime branching).

There are two small things:  We use `NPY_MAXDIMS` in some places as `axis=None` which should be -1 really.  That needs a compat layer (I would make this a runtime `NPY_RAVEL_AXIS` variable), second, of course the old iterators need to remain intact (not a problem, but a limitation).

@ngoldbaum brought up backporting `NPY_DEFAULT_INTEGER`.  That seems of limited value to me since you would strictly require against compiling with NumPy 1.26, which is nice, but in the end I am not sure it is all that helpful.  Instead, as soon as the other PR is in, I think the approach is to create a *single*, possibly large, `numpy2_compat.h` which hosts (almost) everything that is version specific (if there is a compat angle to it):
  * When compiled with `NPY_FEATURE_VERSION > 2.0` it is a very thing layer (possibly nothing)
  * When compiled with `NPY_FEATURE_VERSION < 2.0`, compatibility shims (including run-time version checking) is active.
  * If the file is vendored, the ABI version may be <2 when compiling against an old NumPy.  So we support that explicitly.

Any version specific code has to be guarded at runtime and compile time depending on the situation.  That way a macro like `NPY_DEFAULT_INT`, is defined via:
```
#if NPY_ABI_VERSION < 1
    #define NPY_DEFAULT_INT NPY_LONG
#elif NPY_FEATURE_VERSION >= NUMPY_2_0_API_VERSION
    #define NPY_DEFAULT_INT NPY_INTP
#else
    #define NPY_DEFAULT_INT (PyArray_RUNTIME_VERSION >= NPY_2_0_API_VERSION ? NPY_INTP : NPY_LONG)
#endif
```

This step is also necessary to unblock a couple of other points above.

**Comment by seberg** [comment]
@WillAyd would like us to add a few `const`'s e.g. to things like `PyArray_DESCR`.  That seems sensible to me.  It is also viable after the first rc probably (no ABI change at all). 

(This should be easy, PRs welcome obviously ;)).

**Comment by rgommers** [comment]
Is anything here still actionable, or can we close this issue? It seems like the last open items missed the boat.

> review and remove much of `npy_3kcompat.h`

I had a quick look at this one. It's pretty invasive to move the header; it's not used from other public headers but it is used from `numpy/f2py/src/` so it cannot be simply moved into `numpy/_core/src/`. A cleanup would have been nice, but I'd leave it alone at this point.

**Comment by mattip** [comment]
Yup, I think we can close this.
