### ISSUE TITLE
ENH: add ```return_percentage``` for ```np.unique```

### ISSUE THREAD

**Issue by ubless607** [numpy/numpy#24852]
### Proposed new feature or change:

Currently ```np.unique``` only have ```return_counts```, which returns count for unique items.
It would be convenient If ```return_percentage``` is supported,

**Comment by rkern** [comment]
I don't think we're going to add more complications to the function signature; we do not like this pattern where the number of outputs change depending on the arguments. The percentages are easily calculated from the `unique_counts`, so just that convenience is not worth the costs of adding another optional `return_*` argument.
