### ISSUE TITLE
BUG: problem indexing a matrix with two boolean vectors

### ISSUE THREAD

**Issue by c-foschi** [numpy/numpy#24851]
### Describe the issue:

How is this possible?

     In[37]: Y.shape
    Out[37]: (50, 50)
     In[38]: x_ind.shape
    Out[38]: (50,)
     In[39]: strata.shape
    Out[39]: (50,)
     In[40]: (Y[x_ind][:, strata == s]).shape
    Out[40]: (34, 13)
     In[41]: Y[x_ind, strata == s]
    Traceback (most recent call last):
      File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-4-e8d45309fd79>", line 1, in <module>
        Y[x_ind, strata == s]
        ~^^^^^^^^^^^^^^^^^^^^
    IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (34,) (13,) 

btw numpy version was 1.24.3, updating to 1.26.0 did not solve.

### Reproduce the code example:

```python
s= 0
Y= np.random.random((50, 50))
x_ind= np.array([False, False, False, False, False, False, False, False, False,
                 True,  True,  True,  True,  True,  True,  True,  True,  True,
                 True,  True,  True,  True,  True,  True,  True,  True,  True,
                 True,  True,  True,  True,  True,  True,  True,  True,  True,
                 True,  True,  True,  True,  True,  True,  True, False, False,
                 False, False, False, False, False])
strata= np.array([0, 3, 1, 0, 1, 2, 2, 1, 3, 1, 3, 2, 3, 1, 2, 2, 3, 2, 1, 3, 0, 2,
                  0, 0, 2, 3, 1, 0, 3, 1, 3, 0, 0, 1, 0, 1, 0, 3, 3, 0, 2, 0, 2, 0,
                  1, 3, 2, 3, 2, 1])
Y[x_ind, strata == s]
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e8d45309fd79>", line 1, in <module>
    Y[x_ind, strata == s]
    ~^^^^^^^^^^^^^^^^^^^^
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (34,) (13,)
```

### Runtime information:

1.26.0

3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

[{'numpy_version': '1.26.0',
  'python': '3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='foschi', release='10', version='10.0.22621', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}},
 {'architecture': 'Cooperlake',
  'filepath': 'C:\\Users\\miste\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-65e29aac85b9409a6008e2dc84b1cc09.dll',
  'internal_api': 'openblas',
  'num_threads': 24,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]

**Comment by rkern** [comment]
I'm afraid that's just not how boolean indexing is defined. [Here are our docs on the subject](https://numpy.org/doc/1.26/user/basics.indexing.html#boolean-array-indexing).

The kind of semantics you are looking for are considered in [NEP 21 - Simplified and explicit advanced indexing](https://numpy.org/neps/nep-0021-advanced-indexing.html), which has achieved broad agreement but no implementation effort yet.

**Comment by c-foschi** [comment]
I see. thank you for your reply.
