### ISSUE TITLE
BUG: numpy.lingalg.inv returns the wrong matrix

### ISSUE THREAD

**Issue by NoahSTEMStuff** [numpy/numpy#24881]
### Describe the issue:

I have a numpy array of shape (3,3), and when I take the the inverse using np.lingalg.inv it returns the wrong matrix. I verified this by multiplying the inverse by the original matrix, which did not return the identity matrix.

### Reproduce the code example:

```python
import numpy as np

def skew_3d(omega):
    """
    Converts a rotation vector in 3D to its corresponding skew-symmetric matrix.
    
    Args:
    omega - (3,) ndarray: the rotation vector
    
    Returns:
    omega_hat - (3,3) ndarray: the corresponding skew symmetric matrix
    """

    # YOUR CODE HERE
    omega_hat = np.array([[0, -omega[2], omega[1]],
                          [omega[2], 0, -omega[0]],
                          [-omega[1], omega[0], 0]])
    return omega_hat

def rotation_3d(omega, theta):
    """
    Computes a 3D rotation matrix given a rotation axis and angle of rotation.
    
    Args:
    omega - (3,) ndarray: the axis of rotation
    theta: the angle of rotation
    
    Returns:
    rot - (3,3) ndarray: the resulting rotation matrix
    """

    # YOUR CODE HERE
    omega_norm = np.linalg.norm(omega)
    R = np.eye(3) + (skew_3d(omega) / omega_norm) * np.sin(omega_norm*theta) + skew_3d(omega)@skew_3d(omega) / omega_norm**2 *(1-np.cos(omega_norm*theta))
    return R

def screw_tf(omega, h, theta):
    R = rotation_3d(omega, theta)
    q = 1*omega
    P = (np.eye(3)-R)@q + h*theta*omega
    return np.block([[R, P.reshape((3,1))],
            [0,0,0,1]])

w = np.array([1,1,1])
omega = w/np.linalg.norm(w)
h = 1/2
theta = 5
G = screw_tf(omega,h,theta)

R1 = G[0:3,0:3]
I = np.eye(3)
some_matrix = R1-I
# print("G = \n", G)
# print("R1 = \n", R1)
print("some_matrix = \n", some_matrix)
print("np.linalg.inv(some_matrix) = \n", np.linalg.inv(some_matrix))
print("(np.linalg.inv(some_matrix)@some_matrix) = \n", (np.linalg.inv(some_matrix)@some_matrix))
```

### Runtime information:

1.24.3
3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}}]
None

### Context for the issue:

The fact that I do not get the proper inverse when using numpy.linalg.inv is very concerning as that is crucial to many applications.

**Comment by rkern** [comment]
```python
>>> np.linalg.cond(some_matrix)
1.4833959951624962e+16
```

This high [condition number](https://en.wikipedia.org/wiki/Condition_number) is telling you that the matrix is essentially singular at the numerical level of precision provided by our floating point numbers. That means that attempting to invert it will fail. This is not a bug in `inv()` (the results are quite what we expect with a matrix of that large a condition number), but a fact of life when working with floating point arithmetic. Welcome to your journey with floating point. It's a wild ride, but we do manage to wrangle something useful out of it.

**Comment by NoahSTEMStuff** [comment]
but I thought if the matrix was singular nump.linalg.inv raises an error, so why doesn't it raise an error here?

**Comment by rkern** [comment]
It will raise an error if the algorithm fails. Not all nearly singular inputs will actually cause the algorithm to fail. The computations carry on to completion and just have a lot of error. Essentially all floating point computations have error to varying amounts. With matrices that are nearly singular like this, inversion will always have a lot of error. `np.linalg.cond()` lets you get a rough idea how much error to expect ahead of time. Whether those errors are acceptable to you is a choice that you have to make yourself based on what you are trying to do with the numbers and these algorithms.
