### ISSUE TITLE
BUG: use of deprecated function DataFrame.swapaxes in fromnumeric.py use 

### ISSUE THREAD

**Issue by almasgit** [numpy/numpy#24889]
### Describe the issue:

It looks like numpy uses deprecated function DataFrame.swapaxes in fromnumeric.py

### Reproduce the code example:

```python
import numpy as np
import pandas as pd

_ = np.array_split(pd.DataFrame({"a": [1,2]}), 2)
```

### Error message:

```shell
Warning:
<...>Lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
```

### Runtime information:

1.26.0
3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.26.0',
  'python': '3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) '
            '[MSC v.1935 64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='my-lenovo', release='10', version='10.0.22621', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

**Comment by BvB93** [comment]
Many of the fromnumeric functions currently automatically wrap the corresponding method of the passed object, passing a dataframe to `np.swapaxes` thus resulting in a call of the deprecated `DataFrame.swapaxes` function. I don't believe there's currently any way of disabling this behavior besides implementing a `__array_function__` method for overriding the offending fromnumeric functions (?)

**Comment by rgommers** [comment]
> Many of the fromnumeric functions currently automatically wrap the corresponding method of the passed object,

This is kind of a UX bug though - every time this comes up it does something unexpected. Our list for 2.0 is already too long, but it'd be quite nice if we could remove this behavior.

Short of that, there's nothing we can do here.

**Comment by NETkuz42** [comment]
Good afternoon. Similar problem, did you find a solution?

**Comment by almasgit** [comment]
No, unfortunately I didn't. понедельник, 23 октября 2023г., 09:55 +03:00 от NETkuz42  ***@***.*** :

**Comment by nabelekt** [comment]
I am doing some dataframe manipulation using `pandas` and seeing this as well
```
/usr/local/lib/python3.11/dist-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
```
versions:
numpy (1.26.1)
pandas (2.1.2)
arrow (1.3.0)
Python 3.11.5

**Comment by nabelekt** [comment]
Related: https://github.com/apache/arrow/issues/36412

**Comment by ferrannoguera** [comment]
Got the same problem as described using versions:
Python 3.11.4
numpy 1.26.3
pandas 2.1.4

Any updates?

**Comment by jorisvandenbossche** [comment]
For everyone running into this warning: in the end you will have to stop using `np.array_split` with a pandas DataFrame. You can replace that by calculating the start/stop slices and then slicing manually (`df.iloc[start:stop]`).

The explanation here is that `np.array_split` somewhat magically works on a pandas DataFrame because the implementation of that function under the hood only uses features that happen to work the same on an array of dataframe. But, one of those is the `np.swapaxes` function, which when called on a DataFrame will call the `swapaxes` method of that DataFrame. However, this method on the DataFrame is deprecated (for a DataFrame, which is 2D it does nothing different than `transpose`), and so that means that once this method is removed from pandas (probably in pandas 3.0), calling `np.array_split` on a DataFrame will also stop working.

**Comment by seberg** [comment]
Thanks for the note Joris, closing.

**Comment by ddelange** [comment]
confirming pandas v3.0 as the deprecation version ref https://github.com/pandas-dev/pandas/pull/57363

**Comment by ddelange** [comment]
quick update: tried with pandas 3.0
```
pip install -U --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple pandas
```

`np.array_split` will still work, but the return type is `np.ndarray`, not `pd.DataFrame`.
