### ISSUE TITLE
DOC: Issue in order='F' parameter in reshape() method

### ISSUE THREAD

**Issue by OgurtsovAndrei** [numpy/numpy#24894]
### Issue with current documentation:

Order in reshape documentation contains mistake, it does not correlate with real code
[link to doc page](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)
```python
x = np.arange(12)
d = np.reshape(x, (2, 6), order='A')
print(np.reshape(x, (2, 6), order='A'))
print(np.reshape(x, (2, 6), order='F'))
print(np.reshape(d, (2, 6), order='F'))
```
Returns
```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
```
![image](https://github.com/numpy/numpy/assets/89844281/be72d857-89fe-442c-a703-a88a41fa68de)

**Comment by seberg** [comment]
This all looks exactly as expected and correct to me.  I will guess you think:
```
print(np.reshape(x, (2, 6), order='F'))
print(np.reshape(d, (2, 6), order='F'))
```
should be the same.  But it is not, since `x.ravel("F")` and `d.ravel("F")` are clearly not the same.

**Comment by OgurtsovAndrei** [comment]
No, I know what my code works correct
I talk about that in documentation array is `[[0, 4, 3], [2, 1, 5]]` is that also correct?

**Comment by seberg** [comment]
I don't see why it should be wrong?

**Comment by rossbar** [comment]
>  I talk about that in documentation array is [[0, 4, 3], [2, 1, 5]] is that also correct?

Yes, this is correct. Perhaps the confusion arises from the fact that the `order` kwarg indicates both the order that values are indexed in the original array *and* the order that they are stored in the reshaped array. A careful reading of the parameter description from the docstring (emphasis mine) shows:

>    **Read the elements of `a` using this index order, and place the
>    elements into the reshaped array using this index order.**  'C'
>    means to read / write the elements using C-like index order,
>    with the last axis index changing fastest, back to the first
>    axis index changing slowest. 'F' means to read / write the
>    elements using Fortran-like index order, with the first index
>    changing fastest, and the last index changing slowest. **Note that
>    the 'C' and 'F' options take no account of the memory layout of
>    the underlying array, and only refer to the order of indexing.**
>    'A' means to read / write the elements in Fortran-like index
>    order if `a` is Fortran *contiguous* in memory, C-like order
>    otherwise.

If we apply this to the example `a`, then column-major indexing for **reading** (or raveling, in the second case) gives elements in the following order: `[0, 2, 4, 1, 3, 5]`. Then, populating the reshaped array following column-major indexing means the first element maps to index [0, 0], the second element to [1, 0], the third to [0, 1], etc. Following this pattern gives the result seen in the docs.

I will go ahead and close this as I don't think there's anything wrong with the documentation.
