### ISSUE TITLE
BUG: Deprecate unsupported dtype aliases

### ISSUE THREAD

**Issue by mroeschke** [numpy/numpy#24892]
### Describe the issue:

https://github.com/numpy/numpy/pull/24679 appears to have accidentially removed dtype aliases that used to work

### Reproduce the code example:

```python
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.24.4'

In [3]: np.dtype("unicode")
Out[3]: dtype('<U')

In [4]: np.dtype("a1")
Out[4]: dtype('S1')


>>> import numpy as np
>>> np.dtype("unicode")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type 'unicode' not understood
>>> np.dtype("a1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type 'a1' not understood
>>> np.__version__
'2.0.0.dev0+git20231007.040ed2d'
```

### Runtime information:

```python
>>> np.__version__
'2.0.0.dev0+git20231007.040ed2d'
```

**Comment by mtsokol** [comment]
@mroeschke `np.dtype("a")` was removed on purpose here: https://github.com/numpy/numpy/pull/24854. `np.dtype("S")` should be used instead.

**Comment by mroeschke** [comment]
> np.dtype("a") was removed on purpose here: https://github.com/numpy/numpy/pull/24854.

Sounds good. I can update `np.dtype("a")` usage in pandas

**Comment by ngoldbaum** [comment]
We could probably make the error message for trying to create an `aN` dtype nicer though. 

Also if we get more details about the need for supporting `"a"` we could bring it back as a deprecated alias instead. I don't think we want to keep it forever because it's confusing: it's short for ascii and represents the bytes dtype, which is not necessarily ascii.

**Comment by mroeschke** [comment]
On the pandas side, there's no need to keep supporting `"a"`

**Comment by mhvk** [comment]
I just introduced an astropy PR to remove our usage of "a" dtype - https://github.com/astropy/astropy/pull/15454

While it would have been nice if there had been deprecation warnings earlier, I also agree there is not much need to deprecate it now - we have been expecting breakage with numpy 2.0 (I do worry how close to our November feature freeze all this is happening...).

**Comment by ngoldbaum** [comment]
When I searched on github, I only found a couple dozen obscure usages and missed that both pandas and astropy are using it. That argues for merely deprecating it I think.
