### ISSUE TITLE
BUG: np.char.decode with an empty array returns an empty float array

### ISSUE THREAD

**Issue by jeandet** [numpy/numpy#24908]
### Describe the issue:

I would expect `np.char.decode` to always return string like dtype even with an empty input array. In the following example, I would expect the same dtype in both cases.

### Reproduce the code example:

```python
import numpy as np
print(np.char.decode(memoryview(np.array(['aa'], dtype='S2'))).dtype)
print(np.char.decode(memoryview(np.array([], dtype='S2'))).dtype)
```

### Runtime information:

```
In [19]: import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.4
3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)]

In [20]: print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}}]
None
```

### Context for the issue:

This likely not a big issue, it just makes user code less consistent (I think).

**Comment by seberg** [comment]
This should be a relatively straight forward bug to fix by someone willing to dive into it a bit.  Such issues were common in NumPy many years ago, shows how the character functions are not at the focus of attention most of the time...

**Comment by jeandet** [comment]
@seberg thanks for your feedback, I'll try to have a look if I can PR something.

**Comment by paulohdosanjos** [comment]
Hi @seberg. I talked to @jeandet and I'm currently working to fix this problem as a way to start contributing to the project.

**Comment by seberg** [comment]
This has been fixe don main, and seems pretty low priority to me, so closing.  To be fair, it isn't perfect yet, it does return `U1` when it could probably return `U2` (not quite sure).

So there is certainly room for improvement, but if that is an issue for you, please open a new one.
