### ISSUE TITLE
The main branch is not building wheels for PyPy.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#24918]
Is this intentional?
```
        python: ["cp39", "cp310", "cp311", "cp312"]  # "pp39"
```
I assume it was at some point, does it still not work?

**Comment by rgommers** [comment]
On Linux we have a passing PyPy 3.9 CI job, so that should work. IIRC the issue was with OpenBLAS detection on Windows, and that should be resolved now. So I think we can re-enable these builds.

**Comment by rgommers** [comment]
Fixed in gh-24920, closing.
