### ISSUE TITLE
ENH: can we have musl-aarch64 prebuilt binary as well?

### ISSUE THREAD

**Issue by tuananh** [numpy/numpy#24934]
### Proposed new feature or change:

I'm noticing even with latest release, we dont have musl-aarch64; only amd64

Any technical reason for that?

**Comment by andyfaff** [comment]
No technical reasons. However, CI resources for building that target will be a factor. We tend to focus on the most popular targets for pre-built binaries. It's not clear how widespread `musllinux_aarch64` is.

**Comment by tuananh** [comment]
multiarch images are catching up the trend. I think the demand for this will be higher. Can i keep this issue open to see the interest in this?

**Comment by rgommers** [comment]
I've indeed seen more frequent mentions of multi-arch images, and Docker seems to be making a push for those (see, e.g., [this intro blog post](https://www.docker.com/blog/how-to-rapidly-build-multi-architecture-images-with-buildx/)). It's not yet clear to me if there's any common groups of platform tags being used together that is emerging - maybe through higher-level build tooling. @tuananh what's the set of platforms you are trying to build for?

**Comment by tuananh** [comment]
> I've indeed seen more frequent mentions of multi-arch images, and Docker seems to be making a push for those (see, e.g., [this intro blog post](https://www.docker.com/blog/how-to-rapidly-build-multi-architecture-images-with-buildx/)). It's not yet clear to me if there's any common groups of platform tags being used together that is emerging - maybe through higher-level build tooling. @tuananh what's the set of platforms you are trying to build for?

We have mix-arch cluster at work and building multiarch images by default (amd64 and arm64).

**Comment by rgommers** [comment]
Thanks. And the musl part is a custom choice? Or you're building both with glibc and musl?

**Comment by tuananh** [comment]
> Thanks. And the musl part is a custom choice? Or you're building both with glibc and musl?

we use images that use musl (alpine) and some use glibc (wolfi & others) so it would be nice to have both

**Comment by andyfaff** [comment]
Just a clearer explanation of the cost:

- maintaining more wheels incurs extra time and effort required by the developers.
- native building of musllinux_aarch64 requires use of Cirrus-CI which comes at a monetary cost to the numpy project. It helps if companies are able to provide sponsorship to offset that cost.

**Comment by der-eismann** [comment]
Same here, we normally use Alpine-based containers, but our colleagues on Apple Silicon machines can't build these images because of the missing musllinux wheels. Would be great if they could be added, since the difference in image size can be huge (127 MB on `python-alpine` vs 204 MB on `python-slim`).

**Comment by rgommers** [comment]
Thanks @der-eismann, that use case makes sense. I didn't think about this before, but Apple switching to arm64 makes `musllinux` more relevant if one thinks about "Docker recipe should run the same across Linux, macOS and Windows machines" kind of requirement (and Windows on Arm may add to that).

I will note that on macOS there should be a workaround right now (from [this SO question](https://stackoverflow.com/questions/65612411/forcing-docker-to-use-linux-amd64-platform-by-default-on-macos)) - slower but should make things work:
```bash
export DOCKER_DEFAULT_PLATFORM=linux/amd64
```

**Comment by der-eismann** [comment]
Hey @rgommers, you're right, that workaround does help a bit, but in theory only for building the image. Actually running numpy workloads in an emulated environment is _incredibly_ slow, we're talking about factor 20-100. So I get that it costs money and everything to push this additional wheel, but it would be highly appreciated :slightly_smiling_face:

**Comment by rgommers** [comment]
It seems like the case for this is reasonable, and it wouldn't be too hard to do (assuming that there aren't unexpected test failures of course) - WDYT about starting to add these wheels @andyfaff, @charris, @mattip?

**Comment by andyfaff** [comment]
Straightforward, I'll get onto it. It'll be on cirrus

**Comment by rgommers** [comment]
These are up on https://anaconda.org/scientific-python-nightly-wheels/numpy/files, so I'll close this issue.

Thanks for adding them @andyfaff, and for the input everyone else.
