### ISSUE TITLE
DOC: NumPy Logo SVG files rendered in dark by Figma

### ISSUE THREAD

**Issue by iaminebriki** [numpy/numpy#24933]
### Issue with current documentation:

The **[NumPy logo SVG files](https://github.com/numpy/numpy/blob/main/branding/logo)** are correctly rendered in VSCode, GitHub Readme and in Chrome but **rendered as dark in Figma**. Therefore, I suspect the issue is related to Figma's SVG rendering engine.

I have loaded the SVG files in Figma, corrected the colors following the [NumPy Logo Guidelines](https://github.com/numpy/numpy/blob/main/branding/logo/logoguidelines.md) from **black** to a combo of **two shades of blue, rgb(77, 171, 207) and rgb(77, 119, 207)** and the original logo sizes are preserved of course.

The corrected SVG files now render correctly in Figma, as well as in other environments (VSCode, GitHub Readme, Chrome).

Corrected **numpylogoicon.svg**:
![numpylogoicon](https://github.com/numpy/numpy/assets/35892987/eb4fff52-e915-442d-8722-9cf3ca21ea89)

Corrected **numpylogo.svg**:
![numpylogo](https://github.com/numpy/numpy/assets/35892987/db87ef62-75c6-43e9-bad2-cbedf9c6b7c5)

Corrected **numpylogo2.svg**:
![numpylogo2](https://github.com/numpy/numpy/assets/35892987/5a53149a-c34d-410e-8187-3313576b9408)

**Comment by melissawm** [comment]
@isabela-pf any thoughts here?

**Comment by isabela-pf** [comment]
@melissawm while it's been a bit since I've had to open a non-black filled SVG in Figma, this issue does sound familiar to me. I'm not personally aware of anything we can do on it on the NumPy end. 

I'm not sure if there's any action you want me to take, but I'll do my best to if you let me know!

**Comment by melissawm** [comment]
@iaminebriki if you want to submit the corrected logos as a PR, I don't think it hurts 😄 Cheers!

**Comment by iaminebriki** [comment]
@melissawm sure! I'll do it 😄

**Comment by Amit1817** [comment]
Hiiiii

**Comment by iaminebriki** [comment]
@melissawm done #24975

**Comment by iaminebriki** [comment]
@melissawm @isabela-pf 
update concerning the source of the issue:
after checking the [_static](https://github.com/numpy/numpy/tree/eae0b8bc7cebda2c0e32c0552bda21ff64cf990f/doc/source/_static) folder which contains the primary logo and after checking their code I found that **Hex colors (#4dabcf, #4d77cf)** were used and they are correclty rendered by Figma, on the other hand the logos in the [logo](https://github.com/numpy/numpy/tree/eae0b8bc7cebda2c0e32c0552bda21ff64cf990f/branding/logo) folder **RGB colors (rgb(77, 119, 207), rgb(77, 171, 207))** were used and when I have updated just the colors in the code they were correctly rendered by Figma as well..
you can check the code update in my PR #24975
