### ISSUE TITLE
MAINT: Drop Python 3.9 support, require Python 3.10 (following SPEC 0)

### ISSUE THREAD

**Issue by EwoutH** [numpy/numpy#24932]
### Proposed new feature or change:

[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) was superseded by the scientific python ecosystem coordination guideline [SPEC 0 — Minimum Supported Versions](https://scientific-python.org/specs/spec-0000/). Where NEP had a 42 month support windows (3.5 years) for each Python version, SPEC 0 recommends a 3 year support window.

If we were to follow SPEC 0, than Python 3.9 support can already be dropped, since it was released October 5th, 2020.

Requiring Python 3.10+ for future NumPy releases would allow to start use Structural Pattern Matching and new typing features. See [What’s New In Python 3.10](https://docs.python.org/3/whatsnew/3.10.html).

**Comment by rgommers** [comment]
I'd much prefer only doing this after the 2.0 release, because that would probably help with the 1.X -> 2.0 transition. There's no urgency here, the new Python 3.10 features aren't all that relevant.

**Comment by charris** [comment]
> If we were to follow SPEC 0, than Python 3.9 support can already be dropped,

But dropping is not required :) We generally keep support for ~6 months longer than the minimum unless the old version is causing problems.

**Comment by rgommers** [comment]
I'll close this - we'll revisit naturally for numpy 2.1.0

**Comment by EwoutH** [comment]
With the NumPy 2.0 maintenance branch split off, it might be a good moment to reconsider dropping Python 3.9 towards NumPy 2.1.

**Comment by rgommers** [comment]
Already done, last month in gh-26222

**Comment by EwoutH** [comment]
Awesome! Can we close this issue as completed?
