### ISSUE TITLE
BUG: scipy and numpy, --use-scipy-openblas vs --with-scipy-openblas

### ISSUE THREAD

**Issue by andyfaff** [numpy/numpy#24966]
### Describe the issue:

scipy uses the `--use-scipy-openblas` argument when building with dev.py. In contrast numpy uses `--with-scipy-openblas` with spin.py.

Can we use the same flag naming on both?

### Reproduce the code example:

```python
na
```

### Error message:

```shell
na
```

### Runtime information:

na

**Comment by HaoZeke** [comment]
FWIW I think it's more idiomatic to use `with-blah` so this should be changed in SciPy.

**Comment by tylerjereddy** [comment]
I merged the cross-listed PR so SciPy matches NumPy, hopefully that's not too controversial, I think folks are pretty swamped with bigger stuff at the moment.
