### ISSUE TITLE
ImportError: Error importing numpy  from its source directory.

### ISSUE THREAD

**Issue by jjofres** [numpy/numpy#24965]
### Steps to reproduce:

OS is Windows.
I'm using Qt Creator as IDE for C++ code and a Python/C API wrapper. I'm using CMake. 
Python version 3.12 and used pip to install the packages.
They were installed in 'C:/Program Files/Python312/Lib/site-packages'.

Code works well until I try to import numpy or scipy.

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\Javier\Documents\GitRepos\build-PyWrap_tst-Desktop_Qt_6_4_2_MinGW_64_bit-Debug\mypythoncode.py", line 4, in <module>
    import numpy
  File "C:\Program Files\Python312\Lib\site-packages\numpy\__init__.py", line 149, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by ngoldbaum** [comment]
Somehow you've ended up with an installation of numpy where `from numpy.__config__ import show` fails. Normally that only happens if numpy is imported from inside the numpy source tree. It sounds like you installed numpy via pip, so that shouldn't be happening, which makes me think you have a broken install somehow.

I see some `minGW` strings in your debug output - minGW isn't supported by us and isn't tested in our CI so there may be issues we aren't aware of. I doubt anyone will spend a lot of time working on this so you'll likely have to dig in a little bit more into what's going wrong.

**Comment by DavidB3** [comment]
I get the error reproduced.
Numpy installed with pip. Tried Numpy in the Python shell with no problems.
Numpy import fails with the same error when calling import_array().

Is there anything else that needs to be taken into account when initializing Python?

  * The Python version is: Python3.12 from "C:\Users\dboeg\source\repos\NumpyTest\x64\Debug\NumpyTest.exe"
  * The NumPy version is: "1.26.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\numpy\__init__.py", line 149, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

**Comment by dzmitry-lahoda** [comment]
i did not installed via `pip`, but added `numpy` as `poetry` dep, and tried to run `script`.

**Comment by Telofy** [comment]
I also somehow ended up here after installing a dependency through Poetry that depends on numpy.

**Comment by ngoldbaum** [comment]
One of you should open a new issue with steps to reproduce the problem. I don't see that here or on the poetry issue linking back to this issue.

**Comment by DavidB3** [comment]
Hello, that is no longer necessary for me. I was able to find the error. I didn't read the documentation properly and I kept trying to get a debug build to work, which of course doesn't work

**Comment by Telofy** [comment]
I don't think it was a numpy issue at all for me. Somehow the Poetry isolation failed and the IPython I used when I imported the library that depends on numpy was an IPython from outside my venv that used an older Python version. Then I suppose numpy tried to find the C extensions for that older Python version and couldn't find them.

**Comment by mu-arkhipov** [comment]
The same issue, what I found: 
- `which ipython` points to `~/.local/bin/ipython`
- this starts **another** version of python interpreter, different from current poetry shell 
My hacky solution:
`python -c 'from IPython import start_ipython; start_ipython()'`
this is a shortened version of the script at `~/.local/bin/ipython`.

**Comment by 0xn4utilus** [comment]
For me it was missing libstdc++.so.6.
```
Original error was: libstdc++.so.6: cannot open shared object file: No such file or directory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.venv/lib/python3.10/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there
```

**Comment by samancyrus-eaton** [comment]
I got this error. Uninstalled and re-installed `numpy` which didn't resolve the issue. Ended up uninstalling and re-installing `ipython` and that solved it!

**Comment by vedhasua** [comment]
In case you are running into this issue, when trying to run something on a HPC server, it could be also because of you failed to load the necessary `gcc` module first 😛 😉 . 
In which case, the following steps should help 🙂👍 
```
deactivate #come out of your venv
module load gcc/14.2.0 #(or highter for the latest numpy)
source <venv_path>/bin/activate #activate your venv
which python #to make sure python_path is from your venv
python -c "import numpy as np; print(np.__version__)" #testing that numpy is imported without errors, and is the correct version
```
