### ISSUE TITLE
ENH: Use environment variables at load time in `f2py` code

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#24974]
...
              @HaoZeke  wanted to use environment variables in a different way, access them in a library compiled/linked with f2py and these set before loading the module - or used on the module in general.  I had not found a way to change that in this case.

...

_Originally posted by @2sn in https://github.com/numpy/numpy/issues/24874#issuecomment-1773632565_

**Comment by rgommers** [comment]
I skimmed the linked thread, but I don't really understand what the idea is here. It seems to have to do with `FFLAGS` specifically, but that's about all I can tell. Is this really a separate issue from gh-24974, and if so could this gain a self-contained problem statement and proposed solution?

**Comment by HaoZeke** [comment]
Sorry yeah this was not well phrased. The discussion on #24974 was about build systems. The last comment by @2sn as I understood it was related to a more fundamental problem, using environment variables in `f2py` code. This is part of the Fortran 2003 standard, [GET_ENVIRONMENT_VARIABLE](https://gcc.gnu.org/onlinedocs/gfortran/GET_005fENVIRONMENT_005fVARIABLE.html).

Though I'll close this since it is already supported `1.26.0`:
```fortran
! env_module.f90
MODULE env_module
  IMPLICIT NONE
CONTAINS
  SUBROUTINE get_env_value(varname, value)
    CHARACTER(LEN=*), INTENT(IN) :: varname ! The name of the environment variable to fetch
    CHARACTER(LEN=100), INTENT(OUT) :: value ! The value of the environment variable
    CHARACTER(LEN=100) :: buffer
    INTEGER :: status

    CALL GET_ENVIRONMENT_VARIABLE(varname, buffer, STATUS=status)

    IF (status == 0) THEN
      value = buffer
    ELSE
      value = 'NOT FOUND'
    END IF

  END SUBROUTINE get_env_value
END MODULE env_module
```

With `f2py -c envlib.f90 -m envlib` and:
```python
In [1]: import envlib
   ...: import os
   ...: 
   ...: # Set an environment variable for testing
   ...: os.environ["TEST_VAR"] = "Hello, Fortran!"
   ...: 
   ...: # Retrieve the value using the Fortran subroutine
   ...: value = envlib.env_module.get_env_value("TEST_VAR")
   ...: print(f"Value of TEST_VAR: {value}")
   ...: 
   ...: value_not_found = envlib.env_module.get_env_value("NON_EXISTENT_VAR")
   ...: print(f"Value of NON_EXISTENT_VAR: {value_not_found}")
Value of TEST_VAR: b'Hello, Fortran!'
Value of NON_EXISTENT_VAR: b'NOT FOUND'
```

@2sn let me know if there was something else w.r.t. `f2py` and environment variables.

**Comment by 2sn** [comment]
@HaoZeke 
Your example seems to test exactly what I was after.
Thanks!

I may have been using some different compatibility library with F77 at the time I tested it, Ila few yea s Back, but that should not matter.
