### ISSUE TITLE
BUG: array_api.Array has wrong type hints in __getitem__

### ISSUE THREAD

**Issue by Illviljan** [numpy/numpy#24982]
### Describe the issue:

The `__getitem__` is missing a `None` in the `tuple`:
https://github.com/numpy/numpy/blob/4811db788872f29ff3b71202a2130e9e964be4fb/numpy/array_api/_array_object.py#L542-L548

Probably should look like:
https://github.com/data-apis/array-api/blob/e2b373dd497a1e49b43529e66d1196e504c673cd/src/array_api_stubs/_draft/array_object.py#L502-L506

References:
https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.__getitem__.html
https://data-apis.org/array-api/latest/API_specification/indexing.html

### Runtime information:

Seen in main.

**Comment by shubhalgupta** [comment]
is this issue still open @Illviljan
