### ISSUE TITLE
BUG: np.cross is annotated as "NoReturn", despite returning an array. This results in IDE errors (amongst other issues).

### ISSUE THREAD

**Issue by jphdotam** [numpy/numpy#24999]
### Describe the issue:

The np.cross override has a NoReturn return annotation, see [here](https://github.com/numpy/numpy/blob/382eedf3891d474196677e65f3aae066afb32c5f/numpy/_core/numeric.pyi#L506).

This results in the following bug in PyCharm, which I have also submitted: https://youtrack.jetbrains.com/issue/PY-63674

### Reproduce the code example:

```python
centre_pos_abs_mm_xyz = centre_pos_rel_mm - pos_bot_slice_top_left_xyz + offset_xyz_mm
centre_pos_abs_mm_zyx = tuple(np.flip(centre_pos_abs_mm_xyz))

# ImageOrientationPatient -> Normal & Rotation
normal_xyz = np.cross(dir_right, dir_down)
normal_zyx = tuple(np.flip(normal_xyz)
```

### Error message:

```shell
The IDE thinks the line with "np.cross" is unreachable (please see screenshots in the JetBrain bug tracking link above).
```

### Runtime information:

1.23.3
3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0]

### Context for the issue:

I cannot do any code refactoring on lines that follow from np.cross, linting fails etc.

**Comment by BvB93** [comment]
The `NoReturn` overload is correct, as `np.cross` does not support operations between two boolean arrays which is reflected here by the second overload. We've had similar issues involving pyright before, hence the addition of the first overload involving `_ArrayLikeUnknown` as a safety net. And yet... pycharm ignores it anyway? And somehow ends up settling for a random overload that has `NoReturn` and treats that as the "correct" one here? I'm struggling a bit to see the logic here and would very much consider this a pycharm bug.

**Comment by rgommers** [comment]
> I'm struggling a bit to see the logic here and would very much consider this a pycharm bug.

Agreed, let's close this.
