### ISSUE TITLE
BUG: NPY_FR_GENERIC not included in NPY_DATETIMEUNIT

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#25013]
### Describe the issue:

#16266 added N`PY_DATETIMEUNIT` to the `__init__.pxd` file, but I apparently forgot to include `NPY_FR_GENERIC` there.  This is preventing us from using it directly in pandas in e.g. https://github.com/pandas-dev/pandas/pull/55695

### Reproduce the code example:

```python
NA
```

### Error message:

```shell
NA
```

### Runtime information:

NA

**Comment by seberg** [comment]
Will already added it in gh-24923, but you will need a 1.26 release (maybe already, not quite sure) and not 1.25 at *build* time.  Not sure if that is viable.
