### ISSUE TITLE
DOC: `np.long` doesn't show up in scalar reference doc

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#25015]
We re-added `np.long` in #24922 but didn't update the docs to match.

[This page](https://numpy.org/devdocs/reference/arrays.scalars.html) needs to be updated, the dtype docs as well maybe.

cc @mtsokol

**Comment by mtsokol** [comment]
That's right - I opened a PR for that. 

(I think you wanted to link https://github.com/numpy/numpy/pull/24922 in the issue's description)

**Comment by mtsokol** [comment]
Closing as #25030 was merged.
