### ISSUE TITLE
Issue importing numpy in AWS Lambda

### ISSUE THREAD

**Issue by selimir** [numpy/numpy#25033]
### Steps to reproduce:

I am encountering a Runtime.ImportModuleError when trying to import NumPy in an AWS Lambda function:
> Runtime.ImportModuleError: Unable to import module 'lambda_function': Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there

I have:
- Created a Lambda Layer containing the NumPy package.
- Attached this layer to an AWS Lambda function.
- The Lambda function uses the Python runtime, and the version is compatible with the version of numpy in the layer.
- The IAM role attached to the Lambda function has the necessary permissions to access the layer.
- The handler function simply tries to import numpy as np.
- I've checked that the layer is properly structured (python/lib/python3.11/site-packages/).

**Comment by rgommers** [comment]
I suggest doing what the error message suggests: "please exit the numpy source tree". If that is not the problem, you are going to have to give a full bug report here on how you installed Python and NumPy, how you're calling it, and the full traceback.
