### ISSUE TITLE
TASK,TYP: Review `np.long` related (typing) overloads and tests

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#25048]
### Proposed new feature or change:

xref https://github.com/numpy/numpy/pull/25039 and https://github.com/numpy/numpy/pull/24224

Aforementioned PRs have exposed a number of cases wherein the `np.long` re-introduction and shift to a new default int size of 64 bit have resulted in a number of failures in the typing test suite. These cases should be further reviewed and addressed appropriately.

In particular this concerns the:
* [ ] np.ctypeslibs reveal tests
* [x] np.random reveal tests

**Comment by seberg** [comment]
I think one reason why I got stuck multiple times is that it is easy to forget a definition, and that seems to translate to `Any`.  I would guess mypy gives at least a warning for that, maybe even an error?
Could we make sure we notice undefined variables in the stubs when running tests?

**Comment by rgommers** [comment]
@BvB93 I think we want to keep the 2.0.0 milestone for this, but it's probably not blocking for the release branch creation and `2.0.0rc1`, right?

**Comment by BvB93** [comment]
Correct, I'll see if I can make some time next week to review to issue but this is by no means a blocker.

**Comment by rgommers** [comment]
The `numpy.random` annotations were updated in gh-26089, which is already backported to 2.0.0.

@mtsokol @BvB93 did you mean to leave this open because `ctypeslib` (and maybe something else) still needs reviewing?

**Comment by mtsokol** [comment]
For the `ctypeslib` reveal test where we have a separate `if` for `win32` for `np.long`, I don't think there's much to do about it - in CPython when `intc` is the same size as `long`, `c_int` is an alias to `c_long`:

https://github.com/python/cpython/blob/92397d5ead38dde4154e70d00f24973bcf2a925a/Lib/ctypes/__init__.py#L183

From my side there's nothing else left here.

**Comment by seberg** [comment]
Let's close it for now then, if there is something remaining it's a bug now.
