### ISSUE TITLE
full linux tests are sporadically failing

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#25058]
They seem to be barfing up inside the histogram tests, I would assume this one:
```
    @requires_memory(free_bytes=1e10)
    @pytest.mark.slow
    def test_big_arrays(self):
        ...
```
due to hitting a memory limit.  I would think memory limitations mean that the test should just never be run on CI.

I doubt that there is anything to worry about or that anything concretely changed.  But am not sure how to avoid CI to run into it.

**Comment by mattip** [comment]
That free_bytes check has not proven reliable, I wonder if we could improve it. In any case, unconditionally skipping the test might be a reasonable work around.

**Comment by seberg** [comment]
Yeah, I was wondring if adding a `ulimit` might help to make it more reliable, but then we have to manually keep the ulimit updated for CI...

Skipping is indeed easy and reasonable path.
