### ISSUE TITLE
DOC: imprecise definition in numpy.fill_diagonal

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#25077]
### Issue with current documentation:

> `the diagonal is the list of locations with indices a[i, ..., i] all identical. `

This does not read correctly.  `a[i, ..., i] `is the indexed array, not a list of locations.  Maybe it should be:

`the diagonal is the list of locations a[i, ..., i] with indices i, ..., i all identical. `

?

**Comment by rossbar** [comment]
Seems reasonable to me, feel free to open a PR!

**Comment by DhavalParmar61** [comment]
@keithbriggs please provide more details like location of given sentence in the documentation

**Comment by keithbriggs** [comment]
It's in the third line of documentation.

**Comment by mdhaber** [comment]
@rossbar I can open a PR from [mdhaber:gh25077](https://github.com/mdhaber/numpy/tree/gh25077) if you're interested.
