### ISSUE TITLE
ENH: Fast interp function

### ISSUE THREAD

**Issue by parrenin** [numpy/numpy#25070]
### Proposed new feature or change:

I have a code where I do many linear interpolations and this is a bottleneck in terms of computation times.
Right now, I use the anaconda distribution and numpy.interp.
Apparently, this function does not scale well with multiple cores, it is sequential if I understand correctly.
Would not it be possible to make it parallel by sending sections of x coordinates to the different cores?
Is it not possible to make optional use of MKL's interpolation function, if it is faster?
Anaconda provides a MKL version of blas, but it does not seem to me that numpy is using its interpolation functions.
Thanks in advance for your answer.

**Comment by ngoldbaum** [comment]
This sort of generic usage question isn’t appropriate for the issue tracker so I am closing this. To answer your question, I think numba may be able to help according to the numba docs if you only use the first three arguments of `numpy.interp` you should be able to use the jit compiler with parallel=True to get a parallelized version. I haven’t actually tried that so no guarantees.

If all you need is basic 1D interpolation you could also probably write your own optimized implementation for your purposes using numba, cython, or another tool capable of generating fast low-level code.
