### ISSUE TITLE
BUG: pip install .  occurs error

### ISSUE THREAD

**Issue by GGBond8488** [numpy/numpy#25084]
### Describe the issue:

When I want to build numpy from source, following the official steps, I get the following error, which seems to say that I do not have the correct meson version installed，but I can get the correct version information of 1.2.3 by executing the `meson --version` command.

### Reproduce the code example:

```python
pip install .
```

### Error message:

```shell
Processing /root/dev/numpy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      
      ('\x1b[31m',)meson-python: error: Could not find meson version 0.63.3 or newer, found .
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Runtime information:

python=Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux

**Comment by mattip** [comment]
It seems you are using a numpy git repo. Did you do `git submodule update --init`?

**Comment by GGBond8488** [comment]
> It seems you are using a numpy git repo. Did you do `git submodule update --init`?

thanks, very helpful for me

**Comment by adrianeboyd** [comment]
Especially for people who only build numpy from source occasionally, I think it would be helpful to add this step to the current dev `INSTALL.rst` and "Install from source" instructions (https://numpy.org/devdocs/user/building.html#basic-installation).

I was also confused by this error message and it was only after trying to build with `spin` that I got more a helpful error message. The `meson-python` requirement at the top of `pyproject.toml` looks straight-forward at first glance and the `vendored-meson/...` lines are quite buried in the details. And no amount of verbose pip really helps you figure out what's going on.
