### ISSUE TITLE
BUG: Multinomial random seed validation too stringent

### ISSUE THREAD

**Issue by mortonjt** [numpy/numpy#25106]
### Describe the issue:

I'm unable to generate multinomial samples due to overly stringent validation checks on inputs.  If the sum(pvals) > 1, it will throw an error, even if it is off by a very small epsilon.  

This validation is problematic for us, since small numerical rounding errors will randomly throw errors.  I'm thinking there should be an option to enable internal normalization to 1, where `multinomial` renormalizes the values rather than throwing an error (maybe with a warning).  If there is a strong concern for numerical precision, then it may be desirable to have an option to pass in logits and have the inputs normalized internally (see the [`torch.distribution.Multinomial`](https://pytorch.org/docs/stable/distributions.html#multinomial) class for an example). Can open a quick PR as long as there is a willingness for a quick review / merge since this functionality is pretty core to our workflows.

### Reproduce the code example:

```python

import numpy as np
from scipy.special import softmax


def multinomial_bioms(k, D, N, M, min_sv=0.11, max_sv=5.0, sigma_sq=0.1):
    dims, hdims, total = D, k, N


    a = np.random.normal(0, 1, size=(D, 1))
    b = np.random.normal(0, 1, size=(D, 1))
    c = np.hstack((a, b))

    beta0 = np.random.randn(k)
    beta1 = np.random.randn(2, k)
    W = c @ beta1 + beta0  # D x k
    sigma_sq = sigma_sq
    sigma = np.sqrt(sigma_sq)
    z = np.random.normal(0, 1, size=(total, hdims))
    eta = np.random.normal(np.matmul(z, W.T), sigma).astype(np.float32)
    prob = softmax(eta, axis=1)
    prob = prob / prob.sum(axis=1).reshape(-1, 1)  # weird rounding issue
    print(prob.sum(axis=1))

    depths = np.random.poisson(M, size=N)
    Y = np.vstack([np.random.multinomial(depths[i], prob[i])
                   for i in range(N)])

# the runnable example
k = 5
D = 50
N = 100
M = 1e6
np.random.seed(0)
multinomial_bioms(k, D, N, M, min_sv=0.11, max_sv=5.0, sigma_sq=0.1)
```

### Error message:

When we run this function, the print statement shows the following output
```
[1.         1.         1.         1.0000001  1.         1.
 0.99999994 1.         1.         1.         1.         1.
 0.99999994 1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 0.99999994 1.         1.         0.99999994 1.         1.
 1.0000001  1.         0.99999994 1.0000001  1.0000001  1.
 1.         1.         1.         1.         1.         1.
 1.         0.99999994 1.         1.         1.         1.
 0.99999994 1.0000001  1.         1.0000001  1.         1.
 1.         0.99999994 1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.0000001
 0.99999994 1.         1.         1.0000001  0.99999994 1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 0.99999994 1.         1.         0.9999999  1.         1.
 1.         1.         1.         1.         1.         0.99999994
 1.         1.         1.         1.        ]
```
And the error thrown is given below
```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 6
      4 M = 1e6
      5 np.random.seed(0)
----> 6 sim = multinomial_bioms(k, D, N, M, min_sv=0.11, max_sv=5.0, sigma_sq=0.1)

File ~/Documents/research/MZvec/mzvec/sim.py:65, in multinomial_bioms(k, D, N, M, min_sv, max_sv, sigma_sq)
     62 print(prob.sum(axis=1))
     64 depths = np.random.poisson(M, size=N)
---> 65 Y = np.vstack([np.random.multinomial(depths[i], prob[i])

File ~/Documents/research/MZvec/mzvec/sim.py:65, in <listcomp>(.0)
     62 print(prob.sum(axis=1))
     64 depths = np.random.poisson(M, size=N)
---> 65 Y = np.vstack([np.random.multinomial(depths[i], prob[i])
     66                for i in range(N)])

File numpy/random/mtrand.pyx:4369, in numpy.random.mtrand.RandomState.multinomial()

ValueError: sum(pvals[:-1].astype(np.float64)) > 1.0. The pvals array is cast to 64-bit floating point prior to checking the sum. Precision changes when casting may cause problems even if the sum of the original pvals is valid.
```

### Runtime information:

```bash
In [1]: import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.1
3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32) 
[GCC 12.3.0]

In [2]: print(numpy.show_runtime())
[{'numpy_version': '1.26.1',
  'python': '3.9.18 | packaged by conda-forge | (main, Aug 30 2023, '
            '03:49:32) \n'
            '[GCC 12.3.0]',
  'uname': uname_result(system='Linux', node='juermieboop-desktop', release='5.15.0-88-generic', version='#98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/home/juermieboop/miniconda3/envs/mzvec/lib/python3.9/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 32,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None

```

### Context for the issue:

We are extensively using the multinomial function for our internal simulation tests. Having this function randomly break depending on the random seed causes many of our internal unittests to break.

From further tests, it looks like casting the probabilities to doubles can sometimes help ward against this issue.

**Comment by rkern** [comment]
> From further tests, it looks like casting the probabilities to doubles can sometimes help ward against this issue.

Yes, as the error message points you to. Can you show examples where the normalization of `prob` is done in `float64` before passing it to `multinomial()` and it still fails? E.g. instead of casting `eta` down to `float32`, just cast it to `float64`, assuming your `softmax` preserves the `dtype`.

`np.random.multinomial()` is [frozen and will not be changed in the future](https://numpy.org/neps/nep-0019-rng-policy.html). Please confirm the behavior with the current [`Generator` infrastructure](https://numpy.org/doc/1.26/reference/random/index.html) which we can modify.

If you can make your example more self-contained and runnable (preferably just down to the `probs` calculation and the `multinomial` call and not the rest), we might be able to help more. Unfortunately, your example is missing a few too many details for me to just run it and show you the workarounds directly.

**Comment by mortonjt** [comment]
Hi @rkern yes I've included the function call to reproduce the example. Below is the updated function that does the casting

```python
def multinomial_bioms(k, D, N, M, min_sv=0.11, max_sv=5.0, sigma_sq=0.1):
    """Simulates biom tables from multinomial.

    Parameters
    ----------
    k : int
       Number of latent dimensions.
    D : int
       Number of microbes.
    N : int
       Number of samples.
    M : int
       Average sequencing depth.

    Returns
    -------
    dict of np.array
       Ground truth parameters.
    """
    dims, hdims, total = D, k, N

    # define mz data
    # in the actual model, we need to standardize to unit normal
    rt = np.random.normal(0, 1, size=(D, 1))
    mz = np.random.normal(0, 1, size=(D, 1))
    mzdata = np.hstack((rt, mz))

    beta0 = np.random.randn(k)
    beta1 = np.random.randn(2, k)
    # define affine function to generate W for D molecules
    W = mzdata @ beta1 + beta0  # D x k
    sigma_sq = sigma_sq
    sigma = np.sqrt(sigma_sq)
    z = np.random.normal(0, 1, size=(total, hdims))
    eta = np.random.normal(np.matmul(z, W.T), sigma).astype(np.float32)
    eta = eta.astype(np.float64)
    prob = softmax(eta, axis=1)
    prob = prob / prob.sum(axis=1).reshape(-1, 1)  # weird rounding issue

    depths = np.random.poisson(M, size=N)
    Y = np.vstack([np.random.multinomial(depths[i], prob[i])
                   for i in range(N)])

``` 

I haven't run into issues with `float64` yet -- will follow up once I find an edge case there as well

**Comment by rkern** [comment]
When we ask for a complete example, we mean complete code that we can simply copy-paste into a Python interpreter that has the requisite packages installed. This is missing imports, `softmax` in particular, and the values of the function arguments that invoke the error. Consider reducing your code down to just a few lines from, say, the `eta`s down. You'll get more control that way.

I'm reasonably confident that if the `prob / prob.sum()` is done in `float64` arithmetic, you will not run into the error.

**Comment by mortonjt** [comment]
Hi, sorry imports are included.  The function arguments are already included in the code example. I'm haven't run into an error with np.float64 yet.

**Comment by rkern** [comment]
Yeah, just removing the `.astype(np.float32)` in the `eta` calculation will resolve this.

I think everything is working as intended. The error message is already helpful, thanks to an earlier person who ran into this issue, no doubt. So I don't think there's anything for us to work on, here.

**Comment by mortonjt** [comment]
Hi thanks for responding. I'm ok with closing, but I think it is still
useful to have this bug reported since it doesn't look like this is
supported for float32 (which is also useful to note).

**Comment by rkern** [comment]
Yeah, it's never a problem to report. Closing is not a criticism of opening, just a decision about what is and isn't happening next. Thank you for the report.
