### ISSUE TITLE
RFC: Getting rid of `numpy.f2py.compile()`

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#25122]
Here is the implementation:
https://github.com/numpy/numpy/blob/9340fcaeda5aa783a76ab356a58f52b9f76debe3/numpy/f2py/__init__.py#L18-L121

It was lightly amended recently for `meson` use in #25111, however there is really very little justification for its (continued) existence. Some thoughts:

- Things shouldn't be in `__init__`
- It is essentially a wrapper around `subprocess.run`
- Has barely been touched since it was brought in 18 years ago or so (from the `git blame`)
- It [leaks memory](https://github.com/numpy/numpy/blob/9340fcaeda5aa783a76ab356a58f52b9f76debe3/numpy/f2py/tests/test_compile_function.py#L26)

The only slight functionality it provides is that it can work with a block of text (by generating a temporary file). Additionally, tests for `compile` are pretty broken on Windows, and given that it still generates a module file, and the fact that since the `meson` transition users cannot use most of the old `-c` commands, it is really easier to use externally or be explicit about using `subprocess` with environment variables set.

It has always been marked as [experimental and subject to change](https://numpy.org/doc/stable/f2py/usage.html#python-module-numpy-f2py), I would like to therefore remove it ASAP :)

Any user who needs such functionality would be better suited by writing their own thin wrapper over `subprocess` based functionality (or use something like `sh`).

**Comment by rgommers** [comment]
Seems reasonable to me, but then again I'm not a user. Maybe write to the mailing list and do a bit of searching with a code search tool? If that doesn't yield objections, then I'd say go ahead.
