### ISSUE TITLE
DOC: install from git instructions should mention submodules initialization

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#25132]
Especially for people who only build numpy from source occasionally, I think it would be helpful to add the git submodule init step to the current dev `INSTALL.rst` and "Install from source" instructions (https://numpy.org/devdocs/user/building.html#basic-installation).

I was also confused by this error message and it was only after trying to build with `spin` that I got more a helpful error message. The `meson-python` requirement at the top of `pyproject.toml` looks straight-forward at first glance and the `vendored-meson/...` lines are quite buried in the details. And no amount of verbose pip really helps you figure out what's going on.

_Originally posted by @adrianeboyd in https://github.com/numpy/numpy/issues/25084#issuecomment-1803777931_

**Comment by adrianeboyd** [comment]
Thanks for updating this!
