### ISSUE TITLE
DOC: Add release notes for all the changes to np.char

### ISSUE THREAD

**Issue by lysnikolaou** [numpy/numpy#25142]
All the changes in `np.char` (writing ufuncs instead of calling the `str`/`bytes` methods) need release notes and probably also a small migration guide. Will get to this after all of the work on writing the ufuncs has been completed.

**Comment by akashmishrahaha** [comment]
I would like to work on this. Thanks

**Comment by mattip** [comment]
@akashmishrahaha we don't assign issues, feel free to work on anything you feel is important to making NumPy better. Please follow the [contribution guide](https://numpy.org/devdocs/dev/index.html) and be sure to link to this issue when you submit a PR. With that, this probably is not a good first issue, as it requires a good grasp of what changed in the related PRs in order to write concise and accurate documentation.

**Comment by rgommers** [comment]
@lysnikolaou the release branch is about to be created, so it'd be great to get these release notes written. A lot of folks are probably going to look at the notes when 2.0.0rc1 comes out. Exact timing TBD, but could be as soon as tomorrow (probably later in the week though). Would you be able to prioritize addressing this issue?

**Comment by lysnikolaou** [comment]
> Would you be able to prioritize addressing this issue?

Sure, I'll work on this first thing tomorrow morning.

**Comment by rgommers** [comment]
I'm removing this entry from the release notes, because it's about internals that aren't user-relevant, and pointing to a `numpy.core` location that no longer exists:

```
Add ``np.core.umath.find`` and ``np.core.umath.rfind`` UFuncs
-------------------------------------------------------------
Add two ``find`` and ``rfind`` UFuncs that operate on unicode or byte strings
and are used in ``np.char``. They operate similar to ``str.find`` and
``str.rfind``.

(`gh-24868 <https://github.com/numpy/numpy/pull/24868>`__)
```

You may want to reuse that (or not). Please try to express the changes in user-visible features/changes/performance.

**Comment by rgommers** [comment]
Looks like we're all good here after gh-25928. Thanks Lysandros

**Comment by lysnikolaou** [comment]
Closing this since #25928 was merged.

**Comment by rgommers** [comment]
synchronicity:)
