### ISSUE TITLE
BUG: AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'

### ISSUE THREAD

**Issue by gunaxprofessional** [numpy/numpy#25150]
### Describe the issue:

Whenever I try to run this code, `from peft import PeftModel` , it throws an error.

### Reproduce the code example:

```python
from peft import PeftModel
```

### Error message:

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-39-c22a8a6046a0> in <cell line: 1>()
----> 1 from peft import PeftModel

18 frames
/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py in <module>
     55 IS_PYSTON = hasattr(sys, "pyston_version_info")
     56 HAS_REFCOUNT = getattr(sys, 'getrefcount', None) is not None and not IS_PYSTON
---> 57 HAS_LAPACK64 = numpy.linalg._umath_linalg._ilp64
     58 
     59 _OLD_PROMOTION = lambda: np._get_promotion_state() == 'legacy'

AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'
```

### Runtime information:

numpy version = 1.23.5
system version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

### Context for the issue:

Well, I'm currently working on building a chatbot using the LLM. When I try to execute the `from peft import PeftModel` command, I receive the above error. You can access my notebook at the following [link](https://colab.research.google.com/drive/1cSs0Cbi8GEsHtdmsiGtdLsTK_MZ30-Z1?usp=sharing)

**Comment by mattip** [comment]
Looking at your notebook and the stack trace, the interesting part is where the code does 
```
from scipy.stats import norm
``` 

which then calls 
```
from numpy.testing import suppress_warnings
```

This was removed in response to https://github.com/scipy/scipy/issues/19344 in the latest SciPy HEAD. 

As to why it fails: that seems very strange and points to a problem with the numpy module. What kernel/runtime are you using? What happens if you try to only import that attribute, which of these lines fail?

```
import numpy
import numpy.linalg
import numpy.linalg._umath_linalg
import numpy.linalg._umath_linalg._ilp64
```

**Comment by alexanderkulesza** [comment]
Can reproduce with 
`import tellurium as te` on a google collab 

Trying the sequence you suggested gave 
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-17-d2a9a824a7cd>](https://localhost:8080/#) in <cell line: 4>()
      2 import numpy.linalg
      3 import numpy.linalg._umath_linalg
----> 4 import numpy.linalg._umath_linalg._ilp64

ModuleNotFoundError: No module named 'numpy.linalg._umath_linalg._ilp64'; 'numpy.linalg._umath_linalg' is not a package
```

**Comment by mattip** [comment]
> on a google collab

What kernel? How did you install numpy 1.23.5?

**Comment by alexanderkulesza** [comment]
To be honst, no  idea. Collab comes  with python3.10 and had that numpy version pre-installed

**Comment by mattip** [comment]
Maybe worth re-installing.

**Comment by contravarianceisuseful** [comment]
Also having this issue. numpy 1.26.2. I just tried upgrading it and that didn't work. 

Error happened when calling `from ray.rllib.agents.ppo import PPOTrainer`. Could it be that these libraries are trying to call a depreciated function that has been removed?

**Comment by Mrw33554432** [comment]
Same, newest numpy version 1.26.2

**Comment by Mr-Twave** [comment]
In Spyder, I'm using numpy 1.24.3 and it's throwing the same error.

**Comment by mattip** [comment]
I think these all are errors due to two numpy versions installed on top of eachother. It just so happens `ilp64` is the first thing to trip up the imports when `numpy.linalg._umath_linalg` is from a later version, and `numpy/testing/_private/utils.py` is from an earlier version.

**Comment by seberg** [comment]
Agreed with Matti, everyone here reporting seems to have a messed up NumPy installs that somehow have two versions mingled.

I might suggest manually uninstalling NumPy (possibly more than once with pip), but it's hard to guess how to fix broken environments remotely.  In either case these don't seem like NumPy issues.

**Comment by Mrw33554432** [comment]
> Agreed with Matti, everyone here reporting seems to have a messed up NumPy installs that somehow have two versions mingled.
> 
> I might suggest manually uninstalling NumPy (possibly more than once with pip), but it's hard to guess how to fix broken environments remotely. In either case these don't seem like NumPy issues.

Not really. During problem solving I actually tired uninstall - reinstall, and it doesn’t work. And inside the site package there is only 1 numpy, as well as in the package list. So it is an unsolved problem in my case, and the bug only appeared in  that piece of code - if there are two numpy then bug will be everywhere, as it used to be.

Additionally, having 2 versions of numpy is a very common issue, perhaps it worth to monitored during installation (actually I have encountered this type of issue a couple of times).

**Comment by Mr-Twave** [comment]
> Agreed with Matti, everyone here reporting seems to have a messed up NumPy installs that somehow have two versions mingled.
> 
> I might suggest manually uninstalling NumPy (possibly more than once with pip), but it's hard to guess how to fix broken environments remotely. In either case these don't seem like NumPy issues.

I attempted this and I appeared to achieve the same result with only numpy 1.24.3 installed. I would reconsider closing this issue.

**Comment by charris** [comment]
@Mr-Twave Have you done a file search to see if there is another version lurking about?

- What OS are you running on?
- How did you install 1.24.3?

**Comment by KlevertonSilva** [comment]
It worked here using pip install numpy==1.24.4

**Comment by finch-wren** [comment]
The issue still exists in colab, while pip show shows the latest version of numpy - the actual actual import's numpy.__version__ shows a different version causing errors in codes as mentioned above. Reopen the issue please.

**Comment by mattip** [comment]
@finch-wren please open a new issue and describe exactly how to reproduce it so we can help. So far we have not seen anyone explain how they get to this situation in a way that is reproducible.

**Comment by ShivamGupta92** [comment]
Encountered same issue when working with Scikit-learn (version== 1.4.0) and NumPy (version==1.25.2). Had a version conflict with NumPy tried upgrading to NumPy version==1.26.3

**Comment by mattip** [comment]
I locked this issue. Please do open an new issue with a description of your environment and complete reproducer. Much of the discussion here is not anything NumPy can control, but maybe we can help you fix the problem with a good description of what you are doing.
