### ISSUE TITLE
`linalg.pinv` gives wrong pseudoinverse for a matrix

### ISSUE THREAD

**Issue by Aweptimum** [numpy/numpy#25163]
### Describe the issue:

I have a sparse 6x6 matrix for which numpy computes an incorrect pseudoinverse on version 1.26.1
The matrix in question:
```python
A = np.array([
    [1,0,0,1,0,0],
    [0,1,0,0,1,0],
    [0,0,1,0,0,1],
    [0,0,0,0,0,0],
    [0,0,-48.5,0,0,-1681.2],
    [0,48.5,0,0,1681.2,0]
])
```
According to wolfram, the pseudoinverse should be [this](https://www.wolframalpha.com/input?i=pseudoinverse+%7B%7B1%2C0%2C+0%2C+1%2C+0%2C+0%7D%2C+%7B0%2C+1%2C+0%2C+0%2C+1%2C+0%7D%2C+%7B0%2C+0%2C+1%2C+0%2C+0%2C+1%7D%2C+%7B0%2C+0%2C+0%2C+0%2C+0%2C+0%7D%2C+%7B0%2C+0%2C+-48.5%2C+0%2C+0%2C+-1681.2%7D%2C+%7B0%2C+48.5%2C+0%2C+0%2C+1681.2%2C+0%7D%7D). `linalg.pinv` gives an almost identical matrix, but the 4th and 5th columns are swapped like so:
```python
inv = np.array([
    [0.5, 0, 0, 0, 0, 0],
    [0, 1.02971, 0, 0, 0, -0.000612482],
    [0, 0,1.02971, 0.000612482, 0, 0],
    [0.5, 0, 0, 0, 0, 0],
    [0, -0.0297054, 0, 0, 0, 0.000612482],
    [0, 0, -0.0297054, -0.000612482, 0, 0]
])
```
If you test this with the axiom that AA<sup>†</sup>A = A, it [fails](https://www.wolframalpha.com/input?i2d=true&i=%7B%7B1%2C0%2C0%2C1%2C0%2C0%7D%2C%7B0%2C1%2C0%2C0%2C1%2C0%7D%2C%7B0%2C0%2C1%2C0%2C0%2C1%7D%2C%7B0%2C0%2C0%2C0%2C0%2C0%7D%2C%7B0%2C0%2C-48.5%2C0%2C0%2C-1681.2%7D%2C%7B0%2C48.5%2C0%2C0%2C1681.2%2C0%7D%7D*%7B%7B0.5%2C0.%2C0.%2C0.%2C0.%2C0.%7D%2C%7B0.%2C1.02971%2C0.%2C0.%2C0.%2C-0.000612482%7D%2C%7B0.%2C0.%2C1.02971%2C0.000612482%2C0.%2C0.%7D%2C%7B0.5%2C0.%2C0.%2C0.%2C0.%2C0.%7D%2C%7B0.%2C-0.0297054%2C0.%2C0.%2C0.%2C0.000612482%7D%2C%7B0.%2C0.%2C-0.0297054%2C-0.000612482%2C0.%2C0.%7D%7D*%7B%7B1%2C0%2C0%2C1%2C0%2C0%7D%2C%7B0%2C1%2C0%2C0%2C1%2C0%7D%2C%7B0%2C0%2C1%2C0%2C0%2C1%7D%2C%7B0%2C0%2C0%2C0%2C0%2C0%7D%2C%7B0%2C0%2C-48.5%2C0%2C0%2C-1681.2%7D%2C%7B0%2C48.5%2C0%2C0%2C1681.2%2C0%7D%7D)

While wolfram's pseudoinverse [holds true](https://www.wolframalpha.com/input?i2d=true&i=%7B%7B1%2C0%2C0%2C1%2C0%2C0%7D%2C%7B0%2C1%2C0%2C0%2C1%2C0%7D%2C%7B0%2C0%2C1%2C0%2C0%2C1%7D%2C%7B0%2C0%2C0%2C0%2C0%2C0%7D%2C%7B0%2C0%2C-48.5%2C0%2C0%2C-1681.2%7D%2C%7B0%2C48.5%2C0%2C0%2C1681.2%2C0%7D%7D*%7B%7B0.5%2C0.%2C0.%2C0.%2C0.%2C0.%7D%2C%7B0.%2C1.02971%2C0.%2C0.%2C0.%2C-0.000612482%7D%2C%7B0.%2C0.%2C1.02971%2C0.%2C0.000612482%2C0.%7D%2C%7B0.5%2C0.%2C0.%2C0.%2C0.%2C0.%7D%2C%7B0.%2C-0.0297054%2C0.%2C0.%2C0.%2C0.000612482%7D%2C%7B0.%2C0.%2C-0.0297054%2C0.%2C-0.000612482%2C0.%7D%7D*%7B%7B1%2C0%2C0%2C1%2C0%2C0%7D%2C%7B0%2C1%2C0%2C0%2C1%2C0%7D%2C%7B0%2C0%2C1%2C0%2C0%2C1%7D%2C%7B0%2C0%2C0%2C0%2C0%2C0%7D%2C%7B0%2C0%2C-48.5%2C0%2C0%2C-1681.2%7D%2C%7B0%2C48.5%2C0%2C0%2C1681.2%2C0%7D%7D) and yields the original matrix

### Reproduce the code example:

```python
import numpy

A = numpy.array([
    [1,0,0,1,0,0],
    [0,1,0,0,1,0],
    [0,0,1,0,0,1],
    [0,0,0,0,0,0],
    [0,0,-48.5,0,0,-1681.2],
    [0,48.5,0,0,1681.2,0]
])

Ainv = numpy.linalg.pinv(A)

expected = numpy.array([
    [0.5, 0, 0, 0, 0, 0],
    [0, 1.02971, 0, 0, 0, -0.000612482],
    [0, 0, 1.02971, 0, 0.000612482, 0],
    [0.5, 0, 0, 0, 0, 0],
    [0, -0.0297054, 0, 0, 0, 0.000612482],
    [0, 0, -0.0297054, 0, -0.000612482, 0]
])

assert numpy.allclose(A, expected) 
```

### Runtime information:

1.26.1
3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.26.1',
  'python': '3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='LAPTOP-0FU0DIVB', release='10', version='10.0.19045', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

### Context for the issue:

I'm just trying to determine if a support couple can support a moment. The 6x6 matrix represents the bearing system on a shaft, and the shaft is always oriented to the x axis using geometry transforms. This means the matrix is always singular, but I can simply take a 6x1 vector <code>(F<sub>x</sub>, F<sub>y</sub>, F<sub>z</sub>, M<sub>x</sub>, M<sub>y</sub>, M<sub>z</sub>)</code>, decompose it into component vectors, and multiply each by the pseudoinverse. If the resulting 6x1 vector has a non-zero magnitude, then I know the couple can support that component load.

**Comment by jakevdp** [comment]
Thanks for the report! This is very similar to #16715: does the discussion there help resolve the issue for you?

**Comment by Aweptimum** [comment]
In the process of writing the test case, I guess I changed something because it's now giving the correct results. Sorry for the noise!
