### ISSUE TITLE
DOC: Clarify `virtualenv` setup and dependency installation in the development environment guide

### ISSUE THREAD

**Issue by zrottman** [numpy/numpy#25166]
### Issue with current documentation:

Currently the [Using virtual environments](https://numpy.org/devdocs/dev/development_environment.html#using-virtual-environments) section of the contributing guide's "Setting up and using your development environment" includes helpful details for `conda` users about how to install development dependencies using the `environment.yml` file. However, the guide does not include corresponding details for `virtualenv` users and does not specify whether it's preferred to use `pyproject.toml` for this purpose or the suite of `requirements.txt` files. While specific subsections of the tutorial do include this step (for instance, the [Testing builds](https://numpy.org/devdocs/dev/development_environment.html#testing-builds) section instructs the user to first install test dependencies by running `python -m pip install -r test_requirements.txt`), there is no general instruction for `virtualenv` users for installing all project dependencies at once.

For more experienced developers, this process may be more obvious, but for beginners such as myself with less experience managing virtual environments, the added steps could be beneficial in onboarding new contributors more quickly.

### Idea or request for content:

I would like to propose fleshing out dependencies-installation instructions for `virtualenv` users (happy to volunteer) using either the `pyproject.toml` file or the `requirements.txt` files, as recommended by project maintainers.

For example, if maintainers recommend using the `requirements.txt` files for installing dependencies, resolving this issue could be as simple as expanding the `virtualenv` code snippet in the existing "Using virtual environments" section as follows:
```
$ virtualenv numpy-dev
$ python -m pip install -r build_requirements.txt
$ python -m pip install -r doc_requirements.txt
$ python -m pip install -r linter_requirements.txt
$ python -m pip install -r release_requirements.txt
$ python -m pip install -r test_requirements.txt 
```

**Comment by melissawm** [comment]
Thanks for the report - would you like to submit a PR to fix that, @zrottman ? 😄

**Comment by zrottman** [comment]
Will do! Thanks @melissawm
