### ISSUE TITLE
DOC: Unexpected values from `np.median` when passing a sequence of ints for `axis=` 

### ISSUE THREAD

**Issue by szwiep** [numpy/numpy#25174]
### Describe the issue:

Calling `np.median` and passing a sequence of ints to the `axis=` parameter does not produce the same (expected) results as sequentially calling median on each axis of the sequence. My expectation is that these two methods of computing a median would produce the same result.

### Reproduce the code example:

```python
import numpy as np
a = [[[1,2],[3,4]],[[5,6],[8,9]]]
np.median(np.median(np.median(a, axis=0), axis=0), axis=0)
#> 4.75 
np.median(a, axis=[0,1,2])
#> 4.5
```

### Runtime information:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.1
3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
>>> print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.26.1',
  'python': '3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='FRST-FRM-2231E', release='10', version='10.0.19045', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX'],
                      'not_found': ['F16C',
                                    'FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None
```

**Comment by rkern** [comment]
`axis=[0, 1, 2]` means that those axes are flattened, and the median is taken over the resulting flattened axis. This is not the same as taking the median of medians of medians along each axis sequentially.

The code is behaving as intended, but the docstring doesn't actually describe the semantics in thorough-enough detail.

**Comment by szwiep** [comment]
Thank you for the clarification. I could submit a PR for this, if that works?

**Comment by rkern** [comment]
[Yes, please!](https://numpy.org/doc/1.26/dev/howto-docs.html#contributing-fixes)

For reference, the general `axis=seq_of_ints` semantics were introduced to numpy in [1.7.0](https://numpy.org/doc/1.26/release/1.7.0-notes.html#reduction-ufuncs-generalize-axis-parameter); you can see how it's documented in [`np.sum`](https://numpy.org/doc/1.26/reference/generated/numpy.sum.html) for instance. It was added to `np.median` in [1.9.0](https://numpy.org/doc/1.26/release/1.9.0-notes.html#generalized-axis-support-for-median-and-percentile), but the release notes and PR (#3908) are not especially enlightening.
