### ISSUE TITLE
DOC: Benchmark structure

### ISSUE THREAD

**Issue by Schefflera-Arboricola** [numpy/numpy#25256]
### Issue with current documentation:

Currently, there is no information in the [benchmarks README](https://github.com/numpy/numpy/blob/main/benchmarks/README.rst) about how the benchmarks are structured and grouped in the [benchmarks](https://github.com/numpy/numpy/tree/main/benchmarks/benchmarks) directory. I think it would be really helpful to have a small section describing this. 

Also, I wanted to know how it's structured. So, if you could pls refer me to where I could learn more about it.

Thank you :)

### Idea or request for content:

Adding more information in the [benchmarks README](https://github.com/numpy/numpy/blob/main/benchmarks/README.rst) about how the benchmarks are structured.

**Comment by mattip** [comment]
Maybe a link to the [documentation](https://numpy.org/devdocs/benchmarking.html#writing-benchmarks) would help?

**Comment by Schefflera-Arboricola** [comment]
thanks @mattip, but I meant how the functions are organized inside `bench_` files and different classes; like if someone wants to add a benchmark for a function then where should they add that `time_` benchmark function in the benchmark directory?

**Comment by charris** [comment]
@Schefflera-Arboricola What functionality do you want data on?

**Comment by Schefflera-Arboricola** [comment]
> What functionality do you want data on?

I was able to understand the functionalities of benchmarks. I was setting up benchmarks for nx-parallel and wanted to take some inspiration from numpy benchmarks, but I wasn't able to understand how they were structured. But the comment by @rgommers cleared it. Thx :)

**Comment by rgommers** [comment]
Great, thanks @Schefflera-Arboricola. If it's cleared up, I'll close this issue then.
