### ISSUE TITLE
BUG: Power calculation rounding error for array values on AMD EPYC 9534

### ISSUE THREAD

**Issue by mdales** [numpy/numpy#25269]
### Describe the issue:

We have several AMD EPYC computers, but on the newest one, a 9534, we observe a rounding error when calculating the power of float64 in an array, whereas calculating the same value as a scalar does not cause the issue. My expectation is that if I calculate an array value and a scalar value using numpy types and numpy functions I'd get the same result, on this one system we do not.

I've tested the same calculation on two other AMD EYPC systems (7763 and 7702), an M1 Pro Apple Silicon, and an Intel Xeon CPU, and all those systems give me the expected result where the array and scalar computations give me the exact same value.

The work around seems to be to switch from `**` to `np.float_power` (just `np.power` fails similar to `**`). With float_power on the offending AMD EPYC system I get the expected result.

In the below snippet I get no assertion error on every system, but I do get an assertion failure on our AMD EPYC 9534 machine.

I've tried numpy 1.25.2, 1.26.0, 1.26.1 and 1.26.2, all of which give me the same result.

The difference between the array result and the scalar result is lower than epsilon for the machine (indeed, exactly half epsilon), so it could be argued that the rounding is within tolerance, but I'd still expect array and scalar calculations to produce the same result.

### Reproduce the code example:

```python
import numpy as np
x = np.float64(0.8706432910332182)
y = np.array([x])
assert ((y ** 0.25)[0]) == (x ** 0.25)
```

### Runtime information:

1.26.2
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

### Context for the issue:

This error is triggering on our climate change analysis work as part of a research project, and currently causes us to treat all results from the AMD EPYC 9534 machine as suspect if they use power calculations - this is several days of CPU work that we're now having to re-evaluate.

**Comment by ngoldbaum** [comment]
The issue template asks you to paste some diagnostic information that I think would help here, can you include the output it asks for? In particular, the output of `np.show_runtime()` with `threadpoolctl` installed.

**Comment by r-devulap** [comment]
`np.pow` uses SVML since 1.24 which has 4 ULP tolerance. I initially thought that could be the reason but then the report says this doesn't happen on Intel Xeon. @mdales could you confirm what Xeon processor you were running this on? 

On the AMD system, could you set `export NPY_DISABLE_CPU_FEATURES="AVX512F,AVX512_SKX" and check if the error goes away?

**Comment by mdales** [comment]
> `np.pow` uses SVML since 1.24 which has 4 ULP tolerance. I initially thought that could be the reason but then the report says this doesn't happen on Intel Xeon. @mdales could you confirm what Xeon processor you were running this on?
> 
> On the AMD system, could you set `export NPY_DISABLE_CPU_FEATURES="AVX512F,AVX512_SKX"` and check if the error goes away?

I'm confused here - as one of my colleagues pointed out, it does say "Cooperlake" there, but this is on the AMD EPYC system. I'm not sure how I can convince the world of this, but here's a stab:

```
>>> np.show_runtime()
[{'numpy_version': '1.26.2',
  'python': '3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]',
  'uname': uname_result(system='Linux', node='daintree', release='6.2.0-37-generic', version='#38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}},
 {'architecture': 'Cooperlake',
  'filepath': '/home/Michael/dev/tmf-implementation/venv/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
>>> print(''.join(open("/proc/cpuinfo").readlines()[:20]))
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 25
model		: 17
model name	: AMD EPYC 9534 64-Core Processor
stepping	: 1
microcode	: 0xa101144
cpu MHz		: 1500.000
cache size	: 1024 KB
physical id	: 0
siblings	: 128
core id		: 0
cpu cores	: 64
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid overflow_recov succor smca fsrm flush_l1d
```

If I call `platform.processor()` I just get `x86_64`, but that's also what I get on our other AMD EPYC machines. They do however correctly identify as "Zen" in the `show_runtime()` output.

---

But @r-devulap I did what you asked, and I can confirm that if I disable those CPU features that the error does go away, and my test case passes!

**Comment by andyhhp** [comment]
AMD Genoa (Zen4) was the first AMD CPU with AVX512 support, so numpy will almost certainly be using a different underlying implementation on prior generations of AMD CPU

**Comment by mdales** [comment]
The Xeon system I believe is a little long in the tooth - indeed both of those flags are in the not found list.

```
[{'numpy_version': '1.26.2',
  'python': '3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]',
  'uname': uname_result(system='Linux', node='hipp', release='5.15.0-82-generic', version='#91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/michael/dev/yirgacheffe/venv/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
  ```
  
  For exhaustiveness I did check, and the other two AMD EPYC systems also lack those extensions.

**Comment by r-devulap** [comment]
@mdales thanks! That explains this is coming from AVX-512 SVML implementations which do have a 4ULP error. Using the env variable `export NPY_DISABLE_CPU_FEATURES="AVX512F,AVX512_SKX"` is one way to avoid it (but it does disable all AVX-512 optimizations in NumPy)

**Comment by mdales** [comment]
Okay, thanks for the root cause explanation. I'll have to consider what I'm doing to do about this. 

Just for context, my test case is just a simple version of what I was hitting. In the work we do we summaries the land coverage of many species and then sum across all species. What happens in the actual code that causes us to spot this is that we end up for each species where there we expected a zero, we get the sub-epsilon value. We then sum across all species, of which there are thousands, and so now I have a value of the 10^-14 area, which is significant.

So the actual problem I face is not one of comparison, where a check against epsilon would quickly tell me that we're identical, but one of cumulative errors. I just picked the asset test as a minimal reproduction for this issue.

I respect your decision not to want to solve this, but I just wanted to flag how it was impacting us incase that was useful for future work.

**Comment by ngoldbaum** [comment]
> What happens in the actual code that causes us to spot this is that we end up for each species where there we expected a zero, we get the sub-epsilon value

Perhaps you should have a check that does something like:

```
# numpy only guarantees 4 NULP precision
if np.abs(value) <= 4*np.spacing(0):
    value == 0
```

or a vectorized version that checks in many places at the same time
