### ISSUE TITLE
BUG: `np.array` strips trailing `\x00` from bytes

### ISSUE THREAD

**Issue by alreadydone** [numpy/numpy#25268]
### Describe the issue:

When creating a numpy array of bytes from a list using `np.array`, the trailing `\x00` bytes are stripped.

### Reproduce the code example:

```python
import numpy as np
l = [b'\x99', b'\x00', b'\x00\x99', b'\x99\x00']
print(l)
print(np.array(l))
```

Result:
```
[b'\x99', b'\x00', b'\x00\x99', b'\x99\x00']
[b'\x99' b'' b'\x00\x99' b'\x99']
```

### Error message:
N/A

### Runtime information:

tested on two machines:
```
1.26.2
3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) 
[Clang 6.0 (clang-600.0.57)]
```
```
1.24.4
3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]
```

### Context for the issue:

This bug means that I can't reliably create a numpy array of SHA256 hashes using `np.array`, for example. (This is how the bug was discovered.)

**Comment by rkern** [comment]
Yeah, known design feature of the `dtype=np.bytes_` dtype, not a bug. Padding with trailing null bytes is how variable-length (byte)strings are handled. Trailing null bytes in the input (byte)strings can't be distinguished from this padding.

If your bytestrings are all the same-length (like SHA256 hashes), use `dtype=np.void` instead.

```
>>> np.array([b'\x00\x99', b'\x99\x00'], dtype=np.void)
array([b'\x00\x99', b'\x99\x00'], dtype='|V2')
```

**Comment by alreadydone** [comment]
Okay, thanks!
