### ISSUE TITLE
BUG: Calling `squeeze` on a slice of a memmap raises cryptic error

### ISSUE THREAD

**Issue by WardBrian** [numpy/numpy#25278]
### Describe the issue:

Calling .squeeze() on a slice of a memmap that has shape `(1,)` raises
```
RuntimeError: ndarray subclass __array_wrap__ method returned an object which was not an instance of an ndarray subclass
```

### Reproduce the code example:

```python
import numpy as np
import struct

# set up file
filename = 'ex.bin'
with open(filename, 'wb') as f:
    f.write(bytearray(struct.pack('d', 3.14)))
    f.write(bytearray(struct.pack('d', 6.28)))

# mmap file
arr = np.memmap(filename, dtype=np.float64, mode='r', shape=(2,1))

print(arr)
print(arr.squeeze()) # works

print(arr[1:2,0])
print(np.array(arr)[1:2,0].squeeze()) # works
print(arr[1:2,0].squeeze()) # fails
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/brian/Dev/cpp/ffistan/repr.py", line 18, in <module>
    print(arr[1:2,0].squeeze()) # fails
RuntimeError: ndarray subclass __array_wrap__ method returned an object which was not an instance of an ndarray subclass
```

### Runtime information:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.2
3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
```

```
>>> print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.26.2',
  'python': '3.9.13 | packaged by conda-forge | (main, May 27 2022, '
            '16:56:21) \n'
            '[GCC 10.3.0]',
  'uname': uname_result(system='Linux', node='FlatTop', release='6.2.0-37-generic', version='#38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}}]
None
```

### Context for the issue:

This operation seems well-defined for normal arrays but fails for memmaps. This violates the sentence `The memmap object can be used anywhere an ndarray is accepted.` in the documentation, and makes it difficult to write a library which relies on `squeeze` in a generic way which is ambivalent to whether the user provided an array or memmap

**Comment by WardBrian** [comment]
This issue seems to be due to this logic in `memmap`:

https://github.com/numpy/numpy/blob/e8a1917843c574feb2b97b2058da50ed9bc7c5b2/numpy/_core/memmap.py#L338-L341

Removing it it resolves this issue, but as the comment suggests this changes the behavior of `np.sum`.

**Comment by seberg** [comment]
Thanks, looks like there are even more ways we are using `__array_wrap__`...  The more minimal fix is probably to just remove the error and trust `__array_wrap__`.

OTOH, array-wrap returning a scalar like this is tricky, I would prefer the core making the choice to use `arr[()]`, doing it here stands in the way of doing it later!

Maybe we need to try/except an argument to `__array_wrap__` indicating we want a scalar return?!

**Comment by WardBrian** [comment]
This may be a naive question, but how is it implemented for base `ndarrays` such that `array([1.0]).sum() == 1.0` but `array([1.0]).squeeze() == array(1.0)`?

**Comment by seberg** [comment]
For base ndarray, the odd stuff happens in the `replace_with_wrapped_result_and_return` or similar... But, nobody actually *likes* that.  Everything that calls `PyArray_Return` does this.

**Comment by WardBrian** [comment]
Got it. I guess squeeze is the outlier here, but I think it also makes good sense that you can't `squeeze` your way all the way to a base python type (which is what just deleting the error would currently result in for memmaps, which is also a less-than-ideal incompatibility, though perhaps better than a ValueError).

**Comment by seberg** [comment]
I fixed this in gh-25409.  Fixing bugs wasn't really my purpose, so I honestly didn't add a test.  That is also obviously not backportable.

A test would be awesome, and I suspect that not backporting is OK?  If anyone wants to though: The check can simply be removed.

Closing, thanks for the report (it had quite fun timing...).

**Comment by WardBrian** [comment]
Glad it was “fun” :)

It’s definitely a very niche thing, and for my purpose anyway I anticipate updating to 2.0 quickly, so backporting seems unnecessary. 

Actually finding a bug in numpy felt like how I imagine people who track down an issue in their C code deep enough to actually discover that this time it really **was** a compiler bug must feel.


For a test, I think one could just be the example I provided with the prints replaced by some assertions.
