### ISSUE TITLE
BUG: Using a Numpy array to advance index a Array API array succeeds

### ISSUE THREAD

**Issue by betatim** [numpy/numpy#25270]
### Describe the issue:

Using a Numpy array to (advance) index a Array API array does not lead to an exception. If instead you use convert `idx` to a Array API array before `X_xp[idx,:]` an exception is raised informing you that advanced integer indexing is not part of the Array API.

I think some kind of exception should be raised in the case of the Numpy array as well. At least it seems weird for it to succeed with a numpy array but fail with an Array API array.

### Reproduce the code example:

```python
import numpy as np
import numpy.array_api as xp

X = np.arange(100).reshape((10, 10))
X_xp = xp.asarray(X)
# a numpy array for indexing
idx = np.arange(4)

X_xp[idx,:]
```

### Runtime information:

```
[{'numpy_version': '1.25.2',
  'python': '3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) '
            '[Clang 14.0.6 ]',
  'uname': uname_result(system='Darwin', node='thead-mlt', release='23.0.0', version='Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}}]
None
```

**Comment by betatim** [comment]
cc @ogrisel

**Comment by AkavarapuTejadutt** [comment]
Hi everyone,

I encountered a similar issue while working with the numpy.array_api submodule. Specifically, when using a NumPy array for indexing an Array API array, I noticed that it doesn't raise an exception, unlike when using an Array API array directly.

# output: C:\Users\akava\Desktop\OpenSource\hello.py:2: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
**import numpy.array_api as xp**
  
  
It seems unexpected that this behavior differs between NumPy arrays and Array API arrays. Perhaps raising an exception or having consistent behavior in both scenarios could improve usability and prevent potential confusion for users moving between NumPy and the Array API.

Would it be possible to align the behavior between NumPy arrays and Array API arrays in this context?

Thanks!

**Comment by OscarSong2003** [comment]
Hey, can I look into this fix?

**Comment by rgommers** [comment]
Thanks for the bug report @betatim and offer to work on it @OscarSong2003. In NumPy 2.0, the `numpy.array_api` module has been removed in favor of https://github.com/data-apis/array-api-strict. And this issue has already been fixed in `array-api-strict`, it gives:
```
IndexError: Index arrays for array_api_strict must be array_api_strict arrays
```

Hence I will close this.
