### ISSUE TITLE
BUG: compiler warning about undefined behavior in macro expansion

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#25277]
Compiling the latest version of NumPy gives me the following warning in several locations:

```
  ../numpy/_core/src/npysort/simd_qsort.hpp:10:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
  #if !DISABLE_HIGHWAY_OPTIMIZATION
       ^
  ../numpy/_core/src/npysort/simd_qsort.hpp:6:38: note: expanded from macro 'DISABLE_HIGHWAY_OPTIMIZATION'
  #define DISABLE_HIGHWAY_OPTIMIZATION defined(__arm__)
```

According to the [gcc docs](https://gcc.gnu.org/onlinedocs/cpp/Defined.html), this is undefined behavior according to the C standard. Ping @Mousius

**Comment by Mousius** [comment]
Eek! Which compiler was this with @ngoldbaum? I don't think I had any warnings 🤔 

I think this will be fixed as part of https://github.com/numpy/numpy/pull/25045/files#diff-5eed8f056ca1a594291859bc1a2f655decb6ea34e7e5df5b19762855a28a9d74R12-R15, which is almost ready to go in, do you think it's worth splitting out the fix @ngoldbaum?

CC @r-devulap

**Comment by ngoldbaum** [comment]
This was reported by clang on MacOS Sonoma,  ot sure which upstream clang version that corresponds to.

> do you think it's worth splitting out the fix @ngoldbaum 

Nah, just as long as you're aware.

**Comment by seberg** [comment]
That linked PR is in, so going to close assuming that it really fixed the warning.  Thanks.
