### ISSUE TITLE
BUG: significant increase in computation time for np.random.Generator().random() beyond 10^7

### ISSUE THREAD

**Issue by nullhook** [numpy/numpy#25298]
### Describe the issue:

why does the computation time for np.random.Generator().random() experience a substantial increase when scaling the operation beyond 10^7?

```
10^0 = 0.07 ms
10^1 = 0.19 ms
10^2 = 0.09 ms
10^3 = 0.05 ms
10^4 = 0.09 ms
10^5 = 0.25 ms
10^6 = 2.68 ms
10^7 = 33.51 ms
10^8 = 266.66 ms
```

### Reproduce the code example:

```python
import numpy as np

def compute(i):
  rng = np.random.default_rng(1701530929)
  rng.random(size=(10**i,), dtype=np.float32)

for i in range(9): compute(i)
```

### Python and NumPy Versions:

1.24.2
3.11.6 [Clang 14.0.3 (clang-1403.0.22.14.1)]

**Comment by charris** [comment]
It isn't scaling, `size` is the number of generated values, so the time will increase by a factor of 10 in each run once calling overhead is exceeded. There are likely cache effects for larger outputs as well.

**Comment by charris** [comment]
> is there a way to accelerate number of values generated?

Basically, every value generated takes the same amount of time, so the total time scales with the number of values. If you need more speed, your best bet is to see if your problem can be parallelized so that more than one cpu  can be used used.
