### ISSUE TITLE
BUG: No module named 'numpy.core._multiarray_umath' Error in AWS Lambda Python3.10 runtime. 

### ISSUE THREAD

**Issue by the-real-henry** [numpy/numpy#25303]
### Describe the issue:

Installed numpy separately as dependencies of pinecone-client using `pip3 install numpy==1.22.0` on AWS Cloud9 environment. Compressed to Zip and created layer on AWS Lambda function runtime python3.10. Encounter the following error:

`Original error was: No module named 'numpy.core._multiarray_umath'`

### Reproduce the code example:

```python
Installation process

pip3 install numpy==1.22.0
```

### Error message:

```shell
Full error message:


IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/var/lang/bin/python3.10"
  * The NumPy version is: "1.22.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Python and NumPy Versions:

python 3.10
numpy 1.22.0

### Context for the issue:

Experienced the same issue with newest numpy versions installed with pip; same error so I dropped down to the 1.22.0 version. The troubleshooting guide does not help with the error.

**Comment by mattip** [comment]
The original error includes more information, please provide the entire traceback. Typically this happens when the system you are using to `pip install` NumPy is not exactly the same one (same operating system, same platform, same python) as the one you are running on.

**Comment by rgommers** [comment]
Probably the same as gh-21312 or gh-21312. Please have a look at those issues first, and try using a pre-built Lambda layer that includes numpy. If none of that works, please post here again with more details.
