### ISSUE TITLE
DOC: GSOD-NumPy Community Review #3

### ISSUE THREAD

**Issue by MarsBarLee** [numpy/numpy#25318]
### Overview:

<a href="https://drive.google.com/file/d/1F1pLhpVNRuMnVdmZ50QmeDMCDT0rdTFo/view?usp=sharing"><img src="https://hackmd.io/_uploads/ryIHONKmp.png" width="400"></a>
Hi everyone! I am inviting the community to review the first 10 pages of the '**NumPy Contributor Comics**', which is part of the GSOD-NumPy 2023 project.'

**The comic can be [viewed here, as a PDF](https://drive.google.com/file/d/1F1pLhpVNRuMnVdmZ50QmeDMCDT0rdTFo/view?usp=sharing)**. You can comment direct on the PDF viewer or on this Github issue.

Update since [Community Review #2](https://github.com/numpy/numpy/issues/24382): Illustrated of first 10 pages, based on the script. This version of the comics was released at the PyData NYC 2023 conference. I gave a talk there- [here’s the video of the talk](https://youtu.be/Gv_Ea94wquM?si=drLkjdN_0A75Jshn&t=40).

These comics aim to show newcomers that NumPy is driven by  people who use it: in this case, scientists! These comics will show grad students finding a usability problem in NumPy,  working together to submit an issue, and talking to community members.

For more details, check out the [project roadmap](https://medium.com/@marsbarlee/gsod-numpy-contributor-comics-project-roadmap-521280503fbd).

I will also host a **review session at the next NumPy Community Meeting on December 6**, if you would like to chat!

This thread will be open for the next two weeks and **close on December 20.**

### For Review:

For review, you can comment on any part, such as re-wording a specific line or panel.

Note: The comic has 10/16 pages complete. The remaining 6 pages will illustrate the script. The [script](https://docs.google.com/document/d/1fjLTDqSkcKMxo8oSTRThllBFpjo5rXS9/edit) has been reviewed in [Community Review #2](https://github.com/MarsBarLee/gsod-numpy-2023/blob/main/review-2/numpy-community-2023-08-16.md). 

Some specific parts I intend to add or change in the future:

**Adapting from PyData NYC 2023 edition to numpy.org version**
- Currently there are references to PyData NYC (on front cover and back cover)
- I plan on removing these references 
- Replace the QR code on a page to lead to the numpy.org comic version

**Next 6 pages**
- Last panel of the comic on Page 10 explains the relationship between maintainers and contributors
- Expand on this relationship in following pages
- A student will ask “Why doesn’t the maintainer do everything?”
- Answered by a visual metaphor of multiple people in a campsite working together. The maintainer as the lead organizer, and each doing a different job

**Credits**
- Add a 'Based on a true story': links to real [Github issue](https://github.com/numpy/numpy/issues/23319) and [PR](https://github.com/numpy/numpy/pull/23357) the comic was based on

**Comment by sahil-tgs** [comment]
Hi, I wanted to know how or where can i submit my `statement of Interest` for GSoD'24. I tried mailing to numpy-team@googlegroups.com, but I haven't received any response. can u please guide me regarding this?

**Comment by MarsBarLee** [comment]
This review has been closed. The GSOD-NumPy comics have been continued in 2024.
