### ISSUE TITLE
ENH: Allow `tolist()` to output list of tuples

### ISSUE THREAD

**Issue by EwoutH** [numpy/numpy#25319]
### Proposed new feature or change:

Currently, the `tolist()` method, when used on a 2D numpy array, returns a list of lists. In many scientific and computational scenarios, especially those involving coordinates or multi-dimensional data points, having the option to directly convert a 2D array into a list of tuples would be very useful.

#### Proposed Feature
I propose adding an optional argument to the `tolist()` method that allows users to specify the desired format of the output list. Specifically, by setting this argument (e.g., `output_format='tuple'`), the method would return a list of tuples instead of a list of lists.

#### Example
```python
import numpy as np

array = np.array([[1, 2], [3, 4], [5, 6]])
list_of_tuples = array.tolist(output_format='tuple')
# Expected Output: [(1, 2), (3, 4), (5, 6)]
```

#### Use Case
This feature would be particularly useful in scenarios where a numpy array represents a collection of multi-dimensional points (like coordinates), and the user intends to iterate over these points or pass them to functions that expect a list of tuples. This is a common requirement in fields like data analysis, computer graphics, spatial analysis, and machine learning.

#### Benefit
While it is possible to achieve this with a list comprehension or other methods in Python, having built-in support in NumPy's `tolist()` method would enhance readability and usability, and potentially leverage internal optimizations for performance gains.

**Comment by rgommers** [comment]
> and the user intends to iterate over these points or pass them to functions that expect a list of tuples

This is kind of unusual - usually it'd be a sequence of sequences. Would you be able to point at some concrete examples of APIs that require list of tuples but raises on list of lists?

**Comment by EwoutH** [comment]
Thanks for getting back. I don't think I've encountered actual runtime errors, just type hint systems warning. Considering that, maybe some projects take type hints too serious/strict.

I will try to dig up some examples.

**Comment by rgommers** [comment]
> Considering that, maybe some projects take type hints too serious/strict.

They're probably just wrong in those libraries, and should be annotating as `Sequence` rather than `list`.

**Comment by seberg** [comment]
Not sure I care for the new API, although maybe we can find some.  How do you indicate/know you want exactly the last dimension to be considered an "element" in this sense?

Btw. if you know that makes sense, you can probably get what you want with `arr.view("i8,i8").tolist()` in your example (of course now with exactly that call, it doesn't generalize well).

**Comment by YashM8** [comment]
I had to manually change the list objects to tuples. I was saving sensitive data in the list and wanted to add a layer of security by making them tuples so that they are immutable. This feature would be useful. 

As for @seberg concern, we could have a depth at which the list becomes a tuple.

I don't mind working on this.

**Comment by rkern** [comment]
This still feels like a very niche use case that I am happy to leave to users. Here's an efficient implementation that applies the view trick in @seberg's reply somewhat more generally for what I have to assume would be the most common of these niche use cases of treating the last axis as the only one to convert to a tuple:

```python
>>> import numpy as np
>>> def to_list_tuples(x):
...     new_shape = x.shape[:-1]
...     field_dtype = np.dtype([(f'f{i}', x.dtype) for i in range(x.shape[-1])])
...     y = x.view(field_dtype).reshape(new_shape)
...     return y.tolist()
...     
>>> x = np.arange(24).reshape((3, 4, 2))
>>> x
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])
>>> to_list_tuples(x)
[[(0, 1), (2, 3), (4, 5), (6, 7)], [(8, 9), (10, 11), (12, 13), (14, 15)], [(16, 17), (18, 19), (20, 21), (22, 23)]]
```

**Comment by rgommers** [comment]
> This still feels like a very niche use case that I am happy to leave to users. 

That seems to be the general sentiment, and since the initial issue is only type hint warnings there doesn't seem to be a pressing need for this. I think we're heading towards closing this as wontfix soon.

**Comment by EwoutH** [comment]
Agreed. If some situation comes up which makes it relevant again, will update, but for now, let’s close.

**Comment by rgommers** [comment]
Thanks @EwoutH & all
