### ISSUE TITLE
BUG: pypy39 wheel builder failing

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#25334]
The wheel builder workflow has been failing for pypy3.9 since last week, [see here](https://github.com/numpy/numpy/actions/workflows/wheels.yml?query=branch%3Amain).

The errors look like:

```
________________ TestNewBufferProtocol.test_error_too_many_dims ________________
  [gw1] linux -- Python 3.9.17 /tmp/tmp.0jQGXevz9m/venv/bin/python
  
  self = <numpy._core.tests.test_multiarray.TestNewBufferProtocol object at 0x0000000006a06368>
  
      @pytest.mark.slow
      def test_error_too_many_dims(self):
          def make_ctype(shape, scalar_type):
              t = scalar_type
              for dim in shape[::-1]:
                  t = dim * t
              return t
      
          # Try constructing a memory with too many dimensions:
          c_u8_65d = make_ctype((1,)*65, ctypes.c_uint8)
          try:
              m = memoryview(c_u8_65d())
          except ValueError:
              pytest.skip("memoryview doesn't support more dimensions")
      
          assert_equal(m.ndim, 65)
      
          with pytest.raises(RuntimeError, match=".*ndim"):
  >           np.array(m)
  E           Failed: DID NOT RAISE <class 'RuntimeError'>
```

And I think that was due to #25149.

**Comment by seberg** [comment]
Matti already fixed this in pypy, although we should probably skip it until a future version of PyPy comes out (or TBH, just delete the test, it never does what it was designed for anyway).

**Comment by charris** [comment]
I keep `cibuildwheel` pinned at `v2.16.0` to avoid that and have a PR to put up removing the pin when PyPy-7.3.14 comes out. I believe `v2.16.1` also works, `v2.16.2` fails.

**Comment by mattip** [comment]
>I keep cibuildwheel pinned at v2.16.0 to avoid that and have a PR removing the pin for when PyPy-7.3.14 comes out. 

@charris PyPy-7.3.14 was released, so hopefully that pin can be updated to 2.16.2
