### ISSUE TITLE
ENH: Add a round down function to round to nearest decimal

### ISSUE THREAD

**Issue by Chuck321123** [numpy/numpy#25353]
### Proposed new feature or change:

I know ```np.floor``` exists, but this only rounds downwards to nearest integer, but I want to round down to nearest decimal. Lets say we have the standard ```round(5.98765, 2)```. This gived 5.99. However, with a round down function, we would get 5.98. The function could then take either single values, two series, or a serie and a single number. Hoping for a reply

**Comment by andyfaff** [comment]
If you look at the bottom of the round function it shows you how it works. Essentially you multiply by `10**decimal`, then round to integer (rint), then divide by the same power of ten. What you want to do is to use `trunc` instead of rint.
