### ISSUE TITLE
BUG: error: 'llrint' has not been declared in '::'

### ISSUE THREAD

**Issue by mtelka** [numpy/numpy#25366]
### Describe the issue:

I tried to install numpy on OpenIndiana and the compilation failed.

### Reproduce the code example:

```python
$ PATH=/usr/gcc/13/bin:$PATH pip install numpy
```

### Error message:

```shell
[79/512] Compiling C++ object numpy/core/libsimd_qsort_16bit.dispatch.h_AVX512_SPR.a.p/src_npysort_simd_qsort_16bit.dispatch.cpp.o
      FAILED: numpy/core/libsimd_qsort_16bit.dispatch.h_AVX512_SPR.a.p/src_npysort_simd_qsort_16bit.dispatch.cpp.o
      ccache c++ -Inumpy/core/libsimd_qsort_16bit.dispatch.h_AVX512_SPR.a.p -Inumpy/core -I../../numpy/core -Inumpy/core/include -I../../numpy/core/include -I../../numpy/core/src/common -I../../numpy/core/src/multiarray -I../../numpy/core/src/npyma
th -I../../numpy/core/src/umath -I/usr/include/python3.9 -I/tmp/pip-install-ttcaxowf/numpy_70bcd61bf3234fffaafb4b85dfa26f4a/.mesonpy-huevykhk/build/meson_cpu -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c++17 -O3 -msse -msse2 -msse3 -fPIC -DNPY_INTERNAL_BUILD -DHAVE_NPY_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D__STDC_VERSION__=0 -fno-exceptions -fno-rtti -O3 -DNPY_HAVE_SSE2 -DNPY_HAVE_SSE -DNPY_HAVE_SSE3 -DNPY_HAVE_SSSE3 -DNPY_HAVE_SSE41 -DNPY_HAVE_POPCNT -DNPY_HAVE_SSE42 -DNPY_HAVE_AVX -DNPY_HAVE_F16C -DNPY_HAVE_FMA3 -DNPY_HAVE_AVX2 -DNPY_HAVE_AVX512F -DNPY_HAVE_AVX512F_REDUCE -DNPY_HAVE_AVX512CD -DNPY_HAVE_AVX512_SKX -DNPY_HAVE_AVX512VL -DNPY_HAVE_AVX512BW -DNPY_HAVE_AVX512DQ -DNPY_HAVE_AVX512BW_MASK -DNPY_HAVE_AVX512DQ_MASK -DNPY_HAVE_AVX512_CLX -DNPY_HAVE_AVX512VNNI -DNPY_HAVE_AVX512_CNL -DNPY_HAVE_AVX512IFMA -DNPY_HAVE_AVX512VBMI -DNPY_HAVE_AVX512_ICL -DNPY_HAVE_AVX512VBMI2 -DNPY_HAVE_AVX512BITALG -DNPY_HAVE_AVX512VPOPCNTDQ -DNPY_HAVE_AVX512_SPR -DNPY_HAVE_AVX512FP16 -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mno-mmx -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq -mavx512vnni -mavx512ifma -mavx512vbmi -mavx512vbmi2 -mavx512bitalg -mavx512vpopcntdq -mavx512fp16 -DNPY_MTARGETS_CURRENT=AVX512_SPR -MD -MQ numpy/core/libsimd_qsort_16bit.dispatch.h_AVX512_SPR.a.p/src_npysort_simd_qsort_16bit.dispatch.cpp.o -MF numpy/core/libsimd_qsort_16bit.dispatch.h_AVX512_SPR.a.p/src_npysort_simd_qsort_16bit.dispatch.cpp.o.d -o numpy/core/libsimd_qsort_16bit.dispatch.h_AVX512_SPR.a.p/src_npysort_simd_qsort_16bit.dispatch.cpp.o -c ../../numpy/core/src/npysort/simd_qsort_16bit.dispatch.cpp
      <command-line>: warning: "__STDC_VERSION__" redefined
      <built-in>: note: this is the location of the previous definition
      In file included from ../../numpy/core/src/common/npstd.hpp:13,
                       from ../../numpy/core/src/common/common.hpp:9,
                       from ../../numpy/core/src/npysort/simd_qsort.hpp:4,
                       from ../../numpy/core/src/npysort/simd_qsort_16bit.dispatch.cpp:8:
      /usr/gcc/13/include/c++/13.2.0/cmath:1950:11: error: 'llrint' has not been declared in '::'
       1950 |   using ::llrint;
            |           ^~~~~~
      /usr/gcc/13/include/c++/13.2.0/cmath:1951:11: error: 'llrintf' has not been declared in '::'
       1951 |   using ::llrintf;
            |           ^~~~~~~
      /usr/gcc/13/include/c++/13.2.0/cmath:1952:11: error: 'llrintl' has not been declared in '::'
       1952 |   using ::llrintl;
            |           ^~~~~~~
      /usr/gcc/13/include/c++/13.2.0/cmath:1954:11: error: 'llround' has not been declared in '::'
       1954 |   using ::llround;
            |           ^~~~~~~
      /usr/gcc/13/include/c++/13.2.0/cmath:1955:11: error: 'llroundf' has not been declared in '::'
       1955 |   using ::llroundf;
            |           ^~~~~~~~
      /usr/gcc/13/include/c++/13.2.0/cmath:1956:11: error: 'llroundl' has not been declared in '::'
       1956 |   using ::llroundl;
            |           ^~~~~~~~
```

### Python and NumPy Versions:

Python 3.9.16
NumPy 1.26.2

**Comment by rgommers** [comment]
I believe this is already fixed on the `main` branch, could you try that? GCC 13 is brand-new, so I'm not very surprised that the latest release on PyPI may have an issue with it on more niche platforms.

**Comment by ijones-gh** [comment]
Hi I'm getting the same errors. I've just taken a clone of main and followed the instructions in INSTALL.rst and I get the same errors about llrint etc. not being declared, same as mtelka. I'm using gcc 10.5.0 on OpenIndiana.

**Comment by seberg** [comment]
Is this still around and what fixed it in main?  If there is a simple fix, it might be good to backport to 1.26?  Ping @seiko2plus since I think you might just know?

**Comment by mtelka** [comment]
Do you have any suggestion how to prove the issue is in system header files?

I tried this:
```
#include <cmath>
#include <stdio.h>

int main(void)
{
        printf("%lld\n", llrint(1.2));
        return 0;
}
```
and it compiles using `/usr/gcc/13/bin/g++ -Wall a.c` and runs properly.  But this is obviously far from proving anything.

Thank you.

**Comment by mtelka** [comment]
> ... someone with access to OpenIndiana to investigate.

FYI, OpenIndiana can be downloaded here: https://openindiana.org/downloads/

**Comment by ijones-gh** [comment]
@rgommers @seberg it has been found that removing the argument "-d__STDC_VERSION__=0" from setup.py and meson.build allows numpy to be compiled and installed. I've successfully compiled and installed 1.26.4 with pip. See [OpenIndiana GitHub](https://github.com/OpenIndiana/oi-userland/pull/16549). I've done some basic checks and numpy seems to work, but I don't know what the larger consequences would be. What are your thoughts?

**Comment by serge-sans-paille** [comment]
I've run a local build of numpy without it and it seems fine. I can't recall why I added it back in the day :-/

**Comment by mtelka** [comment]
> I've run a local build of numpy without it and it seems fine. I can't recall why I added it back in the day :-/

Could you please consider to remove it then?  Thank you.

**Comment by ijones-gh** [comment]
Looking at the rest of the numpy sourcecode, other lines containing STDC_VERSION have all been commented out, so this may not be required at all. In addition, 0 is not a valid argument to the macro - the gcc online [docs](https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html) says it should be a C standard version number.

Would you like someone to generate a PR for further review and testing by the numpy team?

**Comment by rgommers** [comment]
sure, a PR is welcome. thanks @ijones-gh
