### ISSUE TITLE
DOC: random number generators

### ISSUE THREAD

**Issue by linus-md** [numpy/numpy#25373]
### Issue with current documentation:

Right now some distributions are very well documented like ``rng.normal()`` [normal distribution](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html#numpy.random.Generator.normal)
It contains code on how to draw a sample, how to verify some properties and a visualization of the distribution and pmf.
The [student disttribution](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_t.html) even contains a practical example.

Other distributions like [beta](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.beta.html) don't have any documentation or very little like [chi square](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.chisquare.html).

### Idea or request for content:

I would like to know how detailed the examples should be. There was also a discussion  @rkern @charris  [here](https://github.com/numpy/numpy/pull/25357#issuecomment-1849172262) on whether there should be ``scipy`` imports to display the pmf. Or if links should be added somewhere.

I started working on
- #25356 adding a plot
- #25413 adding plots, as well as a practical example and showing some properties
- #25354 adding a plot
- #25355 fixing a typo, there is also another issue as noted by @eendebakpt 
- #25357 adding a plot
- #25528 adding notes
- #25529 adding a plot
- #25530 adding a plot
- #25533 add pmf

Distributions that would benefit from improvements are:
- [hypergeometric](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.hypergeometric.html) could use a plot
- [negative binomial](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.negative_binomial.html) could definitely use a plot and some comments on the parameters
- [noncentral_chisquare](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.noncentral_chisquare.html) does not have a pmf in the plots
and some others.

**Comment by MilesWeberman** [comment]
I'm new to open source and working on my first contribution to the documentation. Do I need to follow the steps outlined on the building the building the NumPy API and reference docs [page](https://numpy.org/devdocs/dev/howto_build_docs.html#howto-build-docs)? Any guidance would be appreciated. Thanks
