### ISSUE TITLE
DOC: Document relation of np.histogram()'s resulting dtype to weights' dtype

### ISSUE THREAD

**Issue by hmeine** [numpy/numpy#25385]
### Issue with current documentation:

The current documentation does not at all mention the dtype that the accumulator ndarray will have.  Unfortunately, I used `weights` with uint8 values (only 0/1, masking elements to be analyzed) and eventually found that the resulting values were so low because of integer overflows / wraparounds. (See #23681)

### Idea or request for content:

It should be mentioned in the docstring, probably once in the result part and once in the weights argument documentation, that/when/how the output dtype depends on the given `weights`. (I *think* the rule may be as simple as "If weights are specified, their dtype will be used for the resulting accumulator array.", but it might also make sense to warn about integer overflows if a "small" weights dtype is used.)

**Comment by rossbar** [comment]
+1 for documenting this, which should IMO be sufficient to close #23681 and #16616.
