### ISSUE TITLE
ENH: Add a dedicated ufunc for `numpy.vecdot`

### ISSUE THREAD

**Issue by mtsokol** [numpy/numpy#25393]
### Proposed new feature or change:

#25155 introduced `numpy.vecdot` which performs conjugation and matmul operations separately.
Ideally there should be a dedicated ufunc for this, similarly to [vdot](https://github.com/numpy/numpy/blob/main/numpy/_core/src/multiarray/vdot.c).

**Comment by ngoldbaum** [comment]
Fixed by #25416
