### ISSUE TITLE
BUG: <FIX C IMPORT ERRORS: ' >

### ISSUE THREAD

**Issue by Az-Neter** [numpy/numpy#25400]
### Describe the issue:

For God's sake it is almost 2024 and this dependency is used in way too much software for you to have a WALL of non-functional 'recommendations' for fixing this idiotic problem.
This is pathetic, bad software design and it's getting disgusting.
Explain to me why it is that numpy can only run on three specific types of hardware architecture and you have the fucking balls to blame it on our software stack?
Even a fresh install of a modern os can't run numpy anymore. 
Truly. What the fuck.
2k open errors. 

I'm not even going to bother giving you my version info because you and I both know this problem persists across nearly every possible iteration of this shitty software. You owe it it the foss community to fix this bullshit.

### Reproduce the code example:

```python
Pip install numpy
```

### Error message:

```shell
Error importing c extensions
```

### Python and NumPy Versions:

🖕

**Comment by seberg** [comment]
We do appreciate actionable and friendly requests.
