### ISSUE TITLE
Importing numpy in archiconda env

### ISSUE THREAD

**Issue by MarieAnge2** [numpy/numpy#25410]
### Steps to reproduce:

Hi I sucefully managed to add archiconda on my jeyson nano, but when I am trying to compile scripts with the import numpy as np command, but I keep getting the no model named numpy error, and I did install numpy as you can see from the following codes I do have numpy properly installed
![20231216_144111](https://github.com/numpy/numpy/assets/85794448/1d310e7f-ef38-420b-b33e-3d8e813e50ee)

At first I thought it had something to do with the path, and I exported the numpy path location into the normal path and I still get error whenever I try to import numpy. When type comand "import sys" and "print(sys.executable) to check working environment I get that my environment is /home/marco/archiconda3/bin/python3.

Is there any help on how I can add numpy to this working environment

### Error message:

```shell
In <module>
Import numpy
Module not found error: no module named 'numpy'
```

**Comment by linus-md** [comment]
Did you try ``which python`` to see whether you are not using the base python?

**Comment by linus-md** [comment]
This should help
```
$ conda config --set auto_activate_base false
$ export "PATH=/bin:/usr/bin:$PATH" >> ~/.bashrc
$ source ~/.bashrc
$ which python3
```
see [this](https://github.com/yqlbu/archiconda3) also.

You should probably use this to create a specific environment:
`$ conda create --name envname (replace envname in your preference)`.
This is most likely not a NumPy issue.

**Comment by andyfaff** [comment]
As mentioned previously, this probably isn't a numpy issue, so closing.
