### ISSUE TITLE
BUG: dtype() handles single-length comma-separated fields as scalar

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [numpy/numpy#25429]
### Describe the issue:

`np.dtype("i,") == np.dtype("i")` (note the comma).  Is this designed?  It feels like the former should result in a structure with one field, whereas the latter should result in a scalar.  Same as how python handles parentheses in tuples, i.e. `(val)` is interpreted differently than `(val,)`

### Reproduce the code example:

```python
import numpy as np

arr = np.empty((1,), dtype="i,")
arr[0] = (5,)
```

### Error message:

```shell
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: setting an array element with a sequence.
```

### Python and NumPy Versions:

python :`'3.10.11 (main, Apr  5 2023, 14:15:30) [GCC 7.5.0]'`
numpy: `1.24.1`

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/jmsh/github/gen-experiments/env/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

### Context for the issue:

I'm implementing a version of `np.argmax` that accepts a `axis: None or int or tuple of ints` in the way that `np.max` does.  But I also unravel the index from an into into a tuple.  I store the tuples in an array of dtype as `arr.ndim * "i,"`.

I know there's other ways of [constructing a dtype](https://numpy.org/doc/stable/reference/arrays.dtypes.html) if I manually name the fields `"f0", "f1", ...`.  So not a big priority.

**Comment by ngoldbaum** [comment]
It looks like the behavior you're seeing dates back to 3d730002b1 committed in 2009. The modern version of this code lives on [here](https://github.com/numpy/numpy/blob/0032ede015c9b06f88cc7f9b07138ce35f4357ae/numpy/_core/src/multiarray/descriptor.c#L748).

I'm having trouble generating a github code search to find existing downstream usages, but given the vintage of that code I wouldn't be surprised if there are some.

To me, the benefit here is not worth any pain from chaging an old behavior that is not problematic since there are workarounds.

**Comment by ngoldbaum** [comment]
Good point. @seberg what do you think?

I'll also note that there is one usage inside numpy, in a test:

```
$ rg "\(\"[a-z],\""
numpy/_core/tests/test_nditer.py
1438:    in_dtype = np.dtype([("a", np.dtype("i,")),
```

**Comment by seberg** [comment]
I don't care much if we change it or not, but if nobody cares much, the default is probably to just accept that times changed on this one (long ago it probably seemed more reasonable to make `"i,"` the same as `"i"`).

The FutureWarning looks fine to just finalize and return a subarray with shape `(1,)` (if should be expected).  There are some more problems with the tuple notation, though.

**Comment by mhvk** [comment]
Agreed that we might as well change this; I think "i," should create a structured array with a single field called "f0" (just like "i,i" creates a structured array with fields "f0" and "f1").  2.0 is a nice release to have this clean-up...

**Comment by seberg** [comment]
I suppose: If anyone cares enough to open a PR soon enough for 2.0, I will merge it.  I really presume nobody likely relies on `i,` being special.

**Comment by ngoldbaum** [comment]
@Jacob-Stevens-Haas if you want to take this on, I linked to the relevant C code upthread.

**Comment by mhvk** [comment]
Really, "(2)i," is just a trick to interpret "(2)" wrongly as a tuple; this should be either "2i" or "(2,)i"...

This all annoyed me sufficiently to create a fix - see #25434 - let me know what you think!

**Comment by seberg** [comment]
Cool, I am not quite sure I follow why `(2)i` is bad when `2i` is fine?  Not that I care much.

**Comment by mhvk** [comment]
The PR deprecates it, since the regular `np.dtype("(2)i")` already fails, and (I think) it is easier to explain that something in parentheses should behave like a tuple. Of course, the reason I found it is that I removed the trailing comma in things like `np.dtype("(2)i,")` only to find I got an error...

**Comment by Jacob-Stevens-Haas** [comment]
> @Jacob-Stevens-Haas if you want to take this on, I linked to the relevant C code upthread.

Thanks!  Looks like another contributor was eager and made the PR, but I'll try to follow along through the local dev setup/build/test.
