### ISSUE TITLE
BUG: false positive in the heuristic for old Accelerate 

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#25433]
It was observed in https://github.com/spack/spack/issues/41742 that this error was triggered despite the numpy build not being linked to Accelerate and no other packages being loaded:
```
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend.
If you compiled yourself, more information is available at:
https://numpy.org/doc/stable/user/building.html#accelerated-blas-lapack-libraries
Otherwise report this to the vendor that provided NumPy.
RuntimeWarning: invalid value encountered in divide
```

A run of the test suite after disabling the `_mac_os_check` check in `numpy/__init__.py` confirmed that the `numpy` install was basically fine, with the only failures of interest being:
```
FAILED .../numpy/polynomial/tests/test_classes.py::test_bad_conditioned_fit[Polynomial] - AssertionError: assert 'invalid valu...red in divide' == 'The fit may ...y conditioned'
FAILED .../numpy/polynomial/tests/test_classes.py::test_bad_conditioned_fit[Legendre] - AssertionError: assert 'invalid valu...red in divide' == 'The fit may ...y conditioned'
FAILED .../numpy/polynomial/tests/test_classes.py::test_bad_conditioned_fit[Chebyshev] - AssertionError: assert 'invalid valu...red in divide' == 'The fit may ...y conditioned'
FAILED .../numpy/polynomial/tests/test_classes.py::test_bad_conditioned_fit[Laguerre] - AssertionError: assert 'invalid valu...red in divide' == 'The fit may ...y conditioned'
FAILED .../numpy/polynomial/tests/test_classes.py::test_bad_conditioned_fit[Hermite] - AssertionError: assert 'invalid valu...red in divide' == 'The fit may ...y conditioned'
FAILED .../numpy/polynomial/tests/test_classes.py::test_bad_conditioned_fit[HermiteE] - AssertionError: assert 'invalid valu...red in divide' == 'The fit may ...y conditioned'
```

The `numpy.polynomial` tests are separate code from the `_mac_os_check` heuristic, but both do the same thing and rely on a full-rank check after a call to `np.linalg.lstsq`. This seems to be sensitive to the particular build config in the linked Spack issue, which is:
- macOS 12.6.6, arm64
- Apple Clang 13.1.6
- OpenBLAS 0.3.24

This is a problem, because the heuristic failing makes NumPy unimportable with a misleading error message.

Finally, it's worth pointing out that the `lstsq` call uses `np.errstate` to suppress warnings exactly like the one that's making the heuristic fail: 
https://github.com/numpy/numpy/blob/0032ede015c9b06f88cc7f9b07138ce35f4357ae/numpy/linalg/_linalg.py#L2466-L2468

The question is what to do about this. We should probably at least change the hard error to a warning.

**Comment by seberg** [comment]
:shrug:, not sure if this serves too much purpose anymore.  The test is a bit awkward since it isn't super precise (I have no idea what the actual failure is supposed to be).

The error looks a bit more like a problem with `division` raising spurious FPEs rather than what this was supposed to catch (how come nobody else sees that, though?  Do they enable some fastmath?).
OTOH, I am not quite sure, because I am not quite sure how the test worked when it was "successful"...

**Comment by rgommers** [comment]
IIRC there were problems in older Apple Clang with floating-point errors, so that could explain it. But it could be many things, hard to untangle.

> not sure if this serves too much purpose anymore

Agreed. It's not even clear to me what will still break on what macOS versions. I'd say we try to make the test more specific than "any warning" (I think it can be narrowed down to `RankWarning`, make it as unlikely as possible to pick up old Accelerate by accident, and convert the error to a warning.

**Comment by seberg** [comment]
So the original issue seems to have been a [`RankWarning`](https://github.com/numpy/numpy/issues/20418).  Fair, we can narrow the check on that for sure.  The main bugs on accelerate were of course vastly worse and not about FPEs, but about blatantly wrong results.
I am not sure we actually have any tests which triggered those very reliably unfortunately.

**Comment by rgommers** [comment]
> I think it can be narrowed down to `RankWarning`, make it as unlikely as possible to pick up old Accelerate by accident, and convert the error to a warning.

I kept the error in case a `RankWarning` gets emitted for now. This is the first time in well over a year that this check failed, so I think it'll be okay for now. In case we do get a new report on a false positive on a `RankWarning`, then we should probably delete the check completely.
