### ISSUE TITLE
DOC: Missing how to create new branch code snippet

### ISSUE THREAD

**Issue by ankur0904** [numpy/numpy#25469]
### Issue with current documentation:

The current documentation does have the code snippet to `checkout` to the new branch e.g. `git checkout -b linspace-speedups` but doesn't have the code snippet for **How to create a new branch?** [here](https://numpy.org/devdocs/dev/index.html#development-process-summary)  

### Idea or request for content:

**My idea is to reframe the documentation like this:**
...
- Create a branch for the feature you want to work on. Since the branch name will appear in the merge message, use a sensible name such as ‘linspace-speedups’:
```bash
git branch linspace-speedups
```
- For checkout to this new branch use the following command
```bash
git checkout -b linspace-speedups
```
...

**Comment by ankur0904** [comment]
I am happy to submit the PR.

**Comment by rossbar** [comment]
The `-b` flag of `checkout` creates the branch, so this is all complete and correct. I will go ahead and close as completed!

**Comment by ankur0904** [comment]
@rossbar Sorry, I hadn't noticed the `-b` flag.
