### ISSUE TITLE
DOC: PyArray_Conjugate documentation wrong

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [numpy/numpy#25477]
### Issue with current documentation:

PyArray_Conjugate is described as taking one argument when, in reality, it takes two: the input array and the output array. This is inconsistent with other functions, but in any case it should be properly described in the docs.

**Comment by rgommers** [comment]
Thank you for the report @juanjosegarciaripoll. This is fixed by gh-25492, closing.
