### ISSUE TITLE
BUG: Installation from python and pip crashes on Installing backend dependences

### ISSUE THREAD

**Issue by AntonyBlanco** [numpy/numpy#25479]
### Describe the issue:

I am connecting to my machine via ssh.
I am trying to install numpy on a virtualenv.
When I install it on other machines it works as normal, but mine doesn't work.
In all cases I'm trying to install it using a python virtual environment.
When it finishes loading, my terminal crashes without installing the package, and I get kicked from the system.

If you need more information about my issue, please do not hesitate to ask for it and give me instructions about how to get it. 

### Reproduce the code example:

```python
python -m venv venv
source venv/bin/activate
pip install numpy
```

### Error message:

```shell
Collecting numpy
  Downloading numpy-1.26.2.tar.gz (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 9.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... -Connection to 192.168.X.X closed by remote host.
Connection to 192.168.X.X closed.
```

### Python and NumPy Versions:

system Python 3.11.6
venv Python 3.11.6
venv pip 23.2.1
numpy 1.26.2

### Context for the issue:

Educational reasons. Being the package installation the problem, it could expand to other areas where it is more important

**Comment by ngoldbaum** [comment]
"connection closed by remote host" indicates that the remote server you are connecting to (pip? although 192.168.x.x is a LAN address, so maybe a firewall or something?) closed the connection while trying to download something from pypi.

This is not a problem with numpy, rather it's a problem with pip or your network setup.

Closing as this is unrelated to numpy.
