### ISSUE TITLE
Clarification Requested on Sign Convention in QR Decomposition Output

### ISSUE THREAD

**Issue by moe18** [numpy/numpy#25487]
**Environment:**

NumPy version: 1.26.2
Python version: 3.11.7
Operating System: Windows 11

**Description:**
I've encountered an issue with the QR decomposition function (numpy.linalg.qr) where the sign of the first column elements in the Q matrix is negative when it should be positive. This discrepancy affects the correctness of the decomposition, especially when used in further calculations.

**Expected Behavior:**
For the matrix:
```
[[1, 1, 0],
 [1, 0, 1],
 [0, 1, 1]]
```

The expected QR decomposition (Q matrix) should be:
``` 
[[ 0.7071067811865475,  0.40824829046386313, -0.5773502691896257],
 [ 0.7071067811865475, -0.40824829046386296,  0.577350269189626],
 [ 0.0,                 0.8164965809277261,    0.5773502691896256]]
 ```

**Actual Behavior:**
However, the numpy.linalg.qr function returns:
``` 
[[-0.70710678  0.40824829 -0.57735027]
 [-0.70710678 -0.40824829  0.57735027]
 [0.          0.81649658  0.57735027]]
 ```

Notice the sign of the first element in the Q matrix is negative instead of positive, and the second value in the first column is also negative when it should have been positive.

**Steps to Reproduce:**

```
import numpy as np
A = np.array([[1,1,0], [1,0,1], [0,1,1]])
Q, R = np.linalg.qr(A)
print(Q)
```

https://github.com/numpy/numpy/blob/a43c068b369ad58ef6ad28d6c978389123ebcc1f/numpy/linalg/_linalg.py#L888

**Comment by banerjeesoumya15** [comment]
I checked the definition of QR decomposition, which only says about "Q being orthogonal matrix" and "R being upper triangular matrix". It **does not** define the direction of column vectors. From the result obtained from numpy and scipy packages, the results are same, and it satisfies orthogonal conditions (for Q) and upper triangular conditions (for R), with negligible floating point errors.

```
import numpy as np
A = np.array([[1,1,0], [1,0,1], [0,1,1]])
Q, R = np.linalg.qr(A)
print(Q)

# Output
[[-0.70710678  0.40824829 -0.57735027]
 [-0.70710678 -0.40824829  0.57735027]
 [-0.          0.81649658  0.57735027]]

# transpose of Q
Q_t = Q.transpose()
print(Q_t)

# Output
[[-0.70710678 -0.70710678 -0.        ]
 [ 0.40824829 -0.40824829  0.81649658]
 [-0.57735027  0.57735027  0.57735027]]

# matrix multiplication Q and Q_t
print(np.matmul(Q, Q_t))  # identity matrix

# Output
[[ 1.00000000e+00 -2.74609626e-16  2.01213401e-17]
 [-2.74609626e-16  1.00000000e+00 -2.01213401e-17]
 [ 2.01213401e-17 -2.01213401e-17  1.00000000e+00]]

# inverse of matrix
print(np.linalg.inv(Q))

# Output
[[-7.07106781e-01 -7.07106781e-01  1.14440252e-16]
 [ 4.08248290e-01 -4.08248290e-01  8.16496581e-01]
 [-5.77350269e-01  5.77350269e-01  5.77350269e-01]]
```

Although I tried QR decomposition manually using both Gram-Schmidt process and Householder's reflection, and it aligns with your result. I am not sure what method numpy and Scipy implements.

**Comment by rkern** [comment]
What sources are telling you that certain elements in the result ought to be positive? As far as I know, there are no correctness issues related to the choice of sign; the QR decomposition is unique only up to correlated choices of signs among `Q` and `R`. One can post-multiply `Q` and pre-multiply `R` by a diagonal matrix `D` with values of +/-1 on the diagonal, and you will get a valid QR decomposition (i.e. `Q @ D` and `D @ R` are also a valid Q,R pair because `D@D == I`).

It's possible that there are some implementations that chooses a sign convention that ensures that some elements are positive, but I am unaware of what that might be in aid of. We don't adopt that any convention. We output more or less whatever LAPACK gives us.

**Comment by moe18** [comment]
Thanks for clearing that up! I did a bit more digging and found this cool link that explains how NumPy does the QR decomposition, just like you mentioned about LAPACK: [Check it out here](https://netlib.org/lapack/lug/node40.html). Really helped me get a better grip on it. Appreciate your help!
