### ISSUE TITLE
BUG: imaginary infinity not representable as complex number

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#25493]
### Describe the issue:

I'm writing some tests for complex nans & infinities, as corner cases in the context of scipy factorial functions gaining support for complex values.

As it turns out, it's impossible (at least with the usual syntax) to correctly represent `0 + 1j * np.inf`, which is an unexpected inconsistency, given that other operations on infinities work fine.

### Reproduce the code example:

```python
>>> np.nan                      ✅
nan
>>> np.nan + np.nan * 1j        ✅
(nan+nanj)
>>> np.inf                      ✅
inf
>>> np.inf + 0j                 ✅
(inf+0j)
>>> np.inf * 1j                 ❌  # should be 0+infj
(nan+infj)
>>> 0 + np.inf * 1j             ❌  # should be 0+infj
(nan+infj)
>>> 1 + np.inf * 1j             ❌  # should be 1+infj
(nan+infj)
>>> np.inf * -1j                ❌  # sign is taken correctly, but should be 0-infj
(nan-infj)
>>> np.inf * (1 + 1j)           ✅
(inf+infj)
>>> np.inf * 1j * 1j * 1j * 1j  ❌  # should be inf+0j (ideally...)
(nan+nanj)
```

### Python and NumPy Versions:

1.26.0
3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)

### Runtime Environment:

```
>>> import numpy; print(numpy.show_runtime())
[{'numpy_version': '1.26.0',
  'python': '3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) '
            '[MSC v.1935 64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='...', release='10', version='10.0.22621', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'filepath': 'E:\\miniforge\\envs\\dev\\Library\\bin\\libblas.dll',
  'internal_api': 'mkl',
  'num_threads': 12,
  'prefix': 'libblas',
  'threading_layer': 'intel',
  'user_api': 'blas',
  'version': '2023.2-Product'}]
```

### Context for the issue:

Without having checked, it sounds plausible to me that some internal representation for complex numbers passes through polar coordinates, which would then yield 0*inf=np.nan in the real component.

**Comment by rkern** [comment]
All of this is inherited from the builtin `float` and `complex` behavior.

```python
>>> inf = float('inf')

>>> inf * 1j
(nan+infj)
```

The root problem is that there actually is no `complex` literal, only a literal for the subset of pure-imaginary, finite `complex` numbers with `0` as the real component. The idiomatic construction of a complex number from `floats` (`x + y*1j`) fails here because `1j` is actually `complex(0, 1)`, and when multiplying out `inf * 0`, we get the `nan`.

One can make a `complex` object with `0` as the real component and `inf` as the imaginary, but you have to use `complex(0, inf)` to do it.

```python
>>> complex(0, inf)
infj

>>> import numpy as np

>>> complex(0, np.inf)
infj
```

`np.complex64()` and `np.complex32` don't have a 2-argument constructor like this, but one can wrap around the builtin `complex()` for these edge cases.

```python
>>> np.complex64(complex(0, np.inf))
infj
```

I don't think there is anything we can do in numpy to fix this, but this workaround could be worth documenting somewhere.

**Comment by ngoldbaum** [comment]
> np.complex64() and np.complex32 don't have a 2-argument constructor like this

For what it's worth, I added this, it'll be in NumPy 2.0:

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '2.0.0.dev0+git20231227.8cdc89d'

In [3]: np.complex64(0, np.inf)
Out[3]: np.complex64(infj)

In [4]: np.complex128(0, np.inf)
Out[4]: np.complex128(infj)
```

**Comment by rkern** [comment]
Great! In that case, I think I'll close this issue. The documentation for this addition (a section of a NEP? The What's New?) would be a good place to show off this particular use case so we have it written down somewhere that we can point to.
