### ISSUE TITLE
BUG: Wrong type annotation in ndarray.__array_ufunc__

### ISSUE THREAD

**Issue by aerobio** [numpy/numpy#25499]
### Describe the issue:

According to the documentation, the `method` argument in `ndarray.__array_ufunc__()` "_is a string indicating how the Ufunc was called, either "\_\_call\_\_" to indicate it was called directly, or one of its methods: "reduce", "accumulate", "reduceat", "outer", or "at"._"

However, [`ndarray.__array_ufunc__`](https://github.com/numpy/numpy/blob/284a2f09bf304ea6a98cc1ad2f3dfc4c203b3c93/numpy/__init__.pyi#L1468) is declared as:

```
def __array_ufunc__(
    self,
    ufunc: ufunc,
    method: L["__call__", "reduce", "reduceat", "accumulate", "outer", "inner"],
    *inputs: Any,
    **kwargs: Any,
) -> Any: ...
```

There is an "inner" literal where there should be an "at" literal.

### Reproduce the code example:

```python
import numpy as np

a = np.arange(5)
a.__array_ufunc__(np.add, "__call__", a, a)
a.__array_ufunc__(np.add, "reduce", a)
a.__array_ufunc__(np.add, "accumulate", a)
a.__array_ufunc__(np.add, "reduceat", a, [0,3])
a.__array_ufunc__(np.add, "outer", a, a)
# No problem so far. Code works. Type inspection passes.

# The following line works as expected, but type inspection fails.
a.__array_ufunc__(np.add, "at", a, 1, 2)

# The following doesn't work ("inner" is not a valid ufunc method), but type inspection passes.
a.__array_ufunc__(np.add, "inner", a, 1, 2)
```

### Error message:

```shell
Type inspection message when using method "at":
Expected type 'Literal["__call__", "reduce", "reduceat", "accumulate", "outer", "inner"]', got 'Literal["at"]' instead

Error when using wrong method "inner":
Traceback (most recent call last):
  File "/home/[...]/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-33-59f74a683fa0>", line 1, in <module>
    a.__array_ufunc__(np.add, "inner", a, 1, 2)
AttributeError: 'numpy.ufunc' object has no attribute 'inner'
```

### Python and NumPy Versions:

Numpy version 1.24.4
Python version 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/jotaele/Devel/panimage/venv310/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'},
 {'architecture': 'Haswell',
  'filepath': '/home/jotaele/Devel/panimage/venv310/lib/python3.10/site-packages/opencv_python.libs/libopenblas-r0-f650aae0.3.3.so',
  'internal_api': 'openblas',
  'num_threads': 1,
  'prefix': 'libopenblas',
  'threading_layer': 'disabled',
  'user_api': 'blas',
  'version': None},
 {'architecture': 'Haswell',
  'filepath': '/home/jotaele/Devel/panimage/venv310/lib/python3.10/site-packages/scipy.libs/libopenblasp-r0-41284840.3.18.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.18'}]
None

### Context for the issue:

When implementing an ndarray subclass, static type checking flags correct code as a false positive.
Not terribly important, but trivial to fix.

**Comment by rgommers** [comment]
Thanks for the report @aerobio. Your diagnosis and test case seem correct. It looks like there are no existing tests for `__array_ufunc__` under `numpy/typing/tests/`. Could I interest you in submitting a PR to fix this issue?

**Comment by zachbrugh** [comment]
take

**Comment by zachbrugh** [comment]
Take
