### ISSUE TITLE
DOC: Misleading signature for `ndarray.reshape`

### ISSUE THREAD

**Issue by tail-3lbs** [numpy/numpy#25514]
### Issue with current documentation:

My main focus will on [this page](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html). For the first parameter `shape`, 

```
ndarray.reshape(shape, order='C')
```

why `this method on ndarray allows the elements of the shape parameter to be passed in as separate arguments`? Note that it is not `*args`, then why this implementation allows `a.reshape(10, 11)`?

**Comment by rkern** [comment]
It's not a recommended usage, so we leave it in the `Notes`. We could make this disrecommendation clearer, but I don't think we'll document it in the `Parameters`.

**Comment by rgommers** [comment]
Agreed with leaving it in Notes and adding "not recommended" to that note. 

There are a couple of minor issues with that signature though:

- Introspection in IPython correctly shows that `shape` is positional-only, however the rendered doc page linked above is missing the `/`
- both the linked doc page and the introspection-shown docstring are missing `, *` to indicate that `order` is keyword-only.

**Comment by rossbar** [comment]
> Introspection in IPython correctly shows that shape is positional-only, however the rendered doc page linked above is missing the /

Fortunately this was fixed in #24953 and should be reflected with the next release of the stable docs - it's updated in the [devdocs](https://numpy.org/devdocs/reference/generated/numpy.ndarray.reshape.html).

> both the linked doc page and the introspection-shown docstring are missing , * to indicate that order is keyword-only.

Good catch, this one still needs an update!
