### ISSUE TITLE
BUG: ufunc.reduce() RuntimeWarning: invalid value encountered in reduce

### ISSUE THREAD

**Issue by jli05** [numpy/numpy#25532]
### Describe the issue:

On macOS, with Python 3.10 and numpy 1.26.3, as shown by the reproducing code, the warning behaviour is not consistent. Actually even with a small change in version, for example from numpy 1.26.a to 1.26.b, all the output won't be identical.

It looks related to #22661. We are not digging as deep as in #22661, however there should have been *no* warning for the code in this issue. For one, both `inf + (-inf) = nan` and `2 + 3 = 5` are well defined as in the floating point arithmetics; for the second, in a new Python shell session, with the Python built-in `sum()` rather than the `sum()` imported from numpy, no warning is produced.

```python
>>> from numpy import nan, inf
>>> sum([-inf, inf])
nan
>>> sum([inf, -inf])
nan
```

@seberg asserted in #22661 that the behaviour was as designed by the IEEE FP standard. I'm no expert on the standard, however it looks rather that an all-encompassing `ufunc.reduce()` begins to produce inconsistent behaviour when asked to do simple things. #22661 just went to some length to illustrate that.

Could we fix this? (One may suggest filtering out the warning, but according to the Python documentation, it is not thread-safe creating a context catching the warnings.)

(Regardless pros and cons of having to write extra code to get rid of the warning,) fundamentally, as we argued, there should have been *no* warning in the first place (just as in the standard Python), as the code was to do a normal, well-defined operation.

### Reproduce the code example:

```python
>>> from numpy import sum, inf, mean
>>> mean([-inf, inf])
/Users/xxxxxx/Library/Python/3.10/lib/python/site-packages/numpy/core/_methods.py:118: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
nan
>>> mean([inf, -inf])
nan
>>> sum([-inf, inf])
/Users/xxxxxx/Library/Python/3.10/lib/python/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
nan
>>> sum([inf, -inf])
nan
```

### Python and NumPy Versions:

1.26.3
3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]

**Comment by rkern** [comment]
`with np.errstate(invalid='ignore'):` is the way to silence these errors and is thread-safe as of 2.0.

> fundamentally, as we argued, there should have been no warning in the first place (just as in the standard Python), as the code was to do a normal, well-defined operation.

You can argue that, but we haven't accepted that argument. The warning isn't for undefined operations, but for when NaNs are created by the defined semantics of the IEEE FP standard. Both choices to warn or not warn are valid choices. Python's `float` made one choice; we made another.

The reason that you don't see the warning the second time in your examples is just the `warnings` module's standard behavior of silencing warnings that it has seen before _from the same code location_ (the ones printed in the warning message). If you change the `warning` behavior or change the `invalid` handling to either `invalid='print'` or `invalid='raise'`, you will see both `[inf, -inf]` and `[-inf, inf]` trigger the handler.

```python
>>> with np.errstate(invalid='print'):
...     np.sum([np.inf, -np.inf])
...     np.sum([-np.inf, np.inf])
...     np.mean([np.inf, -np.inf])
...     np.mean([-np.inf, np.inf])
...     
Warning: invalid value encountered in reduce
Warning: invalid value encountered in reduce
Warning: invalid value encountered in reduce
Warning: invalid value encountered in reduce
```

**Comment by jli05** [comment]
@rkern with np.errstate(invalid='ignore'): is the way to silence these errors and is thread-safe as of 2.0.

You meant 2.0 of Python or numpy? Python is already of version 3. Latest numpy is only 1.26, is that an upcoming version of numpy? When is the release roughly?

**Comment by jli05** [comment]
@rkern @seberg Personally think worth noting that the standard Python always made the choice not to show the warning for the code example.

**Comment by rkern** [comment]
I meant numpy 2.0, see #24300 for a tentative schedule (though, it will probably slip a little). But you don't have to wait. `np.errstate()` is used all over numpy and scipy without issue in threaded environments. It's just that sometimes you'll get a leaked warning in places that you thought you'd silenced it or vice versa. Nothing particularly bad happens. By using the functions that internally use `np.errstate()`, you are already using it.

But also, if you just want to silence it all at once everywhere, at the top of your top-level scripts and notebooks (but not library modules!), you can add `np.seterr(invalid='ignore')` and be done with it.

> Personally think worth noting that the standard Python built-in arithmetics always made the choice not to show warning.

Yes, it was well-noted at the time we made our choice. But it's not dispositive. Python's built-in arithmetics also raise an exception on divide-by-zero, while we warn. Given numpy's focus on numerics on large arrays of floating point numbers, we took the opportunity to make fresh choices given the affordances granted us by the IEEE 754 standard. We provided configurability, and then made well-deliberated choices about the defaults. That others make different choices doesn't invalidate our choice or make it a bug.

I'm going to close this, as there has been no inconsistency demonstrated, and the conversation has drifted to challenging a long-standing design decision. Which you can do, but if you really want to push for that, the mailing list is the appropriate place to do so.

**Comment by seberg** [comment]
`np.errstate()` is thread-safe already (or at least very close).  It was previously *not* async safe, but most likely you don't care about that.

In either case, can we please ignore what Python does:
1. It is not all that relevant considering a 20 year history in NumPy.
2. Python ignores FPEs, but normally *raises hard errors* on most of such things.  `inf - inf` is the *exception* not the norm: `sqrt(-1)` is similar, but just raise, even `1/0` raises!

So as Robert says, this is a non-issue.  Could NumPy change the default?  Maybe, but it is a discussion much larger than this issue and I would say it needs a NEP.  And to borrow from Python's habit, it would help if some core dev at least backs such a thing here...

**Comment by jli05** [comment]
You surely have deep expertise in numerics. Kudos to your long-term work. My two cents:

* `inf - inf`, or `sqrt(-1)` are "well-defined" in a sense, as long as the user chooses to believe in the arithmetics involving "infinity" and "NaN", or complex calculus
*  The design of behaviour is best not to surprise an ordinary user/developer, and consistent everywhere, from an ordinary user's point of view
* Python is either in normal mode or raises, but when it raises it is usually *specific* and granular so that say when the user `except ZeroDivisionError: pass`, he would believe he is not ignoring any Exception he *didn't* anticipate, on the surface of the specific name of `ZeroDivisionError`.
* The warning's message in this issue may appear large and murky "RuntimeWarning: invalid value encountered in reduce", an ordinary user may never be sure what is exactly an "invalid" type of error. A risk consequential to that is when ignored with `errstate()`, it may be barely possible to detect what has been ignored precisely. Was it `inf + inf`, `nan - nan`, `nan ** inf`, ...? So I think, the ask is to make the warning's message straightforward. Maybe by doing so, the design of behaviour may become straightforward as well.

**Comment by jli05** [comment]
@seberg could you give some details about `async` safety, as you had mentioned?

**Comment by seberg** [comment]
async as in asyncio, etc.  If you use it, you recognize it.

Frankly, one might suggest to tweak the message, but they will always be a bit murky as the categories that must have similar messages:  Those `errstate` categories are not a NumPy invention, they are IEEE and baked into the **hardware** with roughly those names.
Are the names or message perfect?  No, even Kahan complained about "division by zero", but can you really find a better generic text?

**Comment by jli05** [comment]
@seberg you seemed to say at one point the `errstate()` was thread-safe, but not `async` safe? I was wondering if there's any example about that.

If in the IEEE standard a whole category of error is called "invalid" that's fine. Personally, I think one way is to only warn about what you have to, then we can affect more precise name to each type of error you do warn about, and when an ordinary user writes code, he *clearly expresses* what he intends to ignore, and what not to ignore. For Machine Learning applications, this small aspect may begin to matter (a huge lot) as cases involving `inf` or `nan` may lead to hugely different final decisions. There is real value not to give a sweeping murky name.

I don't know if this is a good example -- once a user is fine with arithmetics involving "infinity" and "NaN", getting `inf - inf = nan` doesn't surprise at all, rather, that is what is _expected_ if he does the same calculation on paper without computer. Either one set the rule `inf - inf = nan`, or `inf - inf` is undefined, in which case that still comes at `nan`. I guess that's why in standard Python no Exception is raised for that.

**Comment by rkern** [comment]
> If in the IEEE standard a whole category of error is called "invalid" that's fine.

Yes, that is the case. All we get is the notification that something in the ufunc's calculation created a NaN, somewhere. We don't get the precise reason why the NaN was created. We can only work with the affordances granted us by the IEEE 754 standard. It's an imperfect setup, but a practical one that has allowed many people build real applications without disaster for decades.

**Comment by jli05** [comment]
As I said, I'm no expert on numerics.

Whether numpy is self-consistent:

```python
>>> from numpy import seterr, sum, nan, inf
>>> seterr(invalid='print')
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>> sum([inf, inf])
inf
>>> sum([nan, inf])
nan
>>> sum([-inf, inf])
Warning: invalid value encountered in reduce
nan
>>> sum([nan, -inf, inf])
nan
>>> sum([nan, inf, -inf])
nan
>>> sum([-inf, inf])
Warning: invalid value encountered in reduce
nan
```

While I was looking for IEEE 754-2019 vs IEEE 754-2008, I came across

https://www.agner.org/optimize/blog/read.php?i=1012
https://www.agner.org/optimize/nan_propagation.pdf

Not sure your take on these.

After all, IEEE 754 seems an evolving system and never settled?

**Comment by rkern** [comment]
My language was a little loose. Our system relies on catching the [floating point exception](https://en.wikipedia.org/wiki/IEEE_754#Exception_handling) (n.b. not a Python exception) that is raised by the FPU and storing a flag to handle as the user configured via `seterr/errstate` once the ufunc is done with the whole array.

NaNs come in two flavors, quiet QNaNs and signaling SNaNs. When an operation on two non-NaN values results in a NaN, the "invalid result" floating point exception is sent and a QNaN gets returned. When a QNaN operates with a non-NaN value, the result is another QNaN but no new floating point exception is sent. When an SNaN operates with a non-NaN value, the result is a NaN (of some flavor; SNaNs are rarely used, so I'm not going to look up what the standard says should happen) and a floating point exception is sent. The behavior you are seeing is consistent with this understanding of when floating point exceptions are issued.

When I said "All we get is the notification that something in the ufunc's calculation created a NaN, somewhere", I meant in the usual non-NaN+non-NaN case. The QNaN+non-NaN case is an interesting side case. I didn't intend for my sentence to be exhaustive. There are some more side cases that I won't enumerate here (e.g. some operations on NaNs won't give NaNs, etc.).

**Comment by rkern** [comment]
The IEEE 754 standard is indeed evolving, but quite slowly. The behavior that we are discussing here is extremely old and has not changed in a long time.

**Comment by jli05** [comment]
Many thanks. Would it be possible to document this (succinctly) on [numpy.org](https://numpy.org)?

What you said seems hard to find anywhere. The English word "invalid" alone may appear abstruse for an ordinary user.

**Comment by rkern** [comment]
https://numpy.org/doc/stable/user/misc.html#how-numpy-handles-numerical-exceptions
https://numpy.org/doc/stable/reference/generated/numpy.seterr.html

What specifically would you like added to these docs?

**Comment by jli05** [comment]
Hi, the documentation you cited is fine as it is.

Just a few ideas below. Feel free to decide what to do (now or for later). By chance I studied a bit about the IEEE 754 standard before, but I'm writing from an ordinary user's view.

* "invalid" FP exception: after reading today's documentation, an ordinary user may wonder: is it 70% likely that NaN has been generated, or 99% so? If 70%, what are the other 30% cases? If 99%, can we alter or append the error message with that "some NaN has been generated" for clarity?
* Especially when some function called by `ufunc.reduce()` has triggered an "invalid" FP exception, today `ufunc.reduce()` 's warning message, with no reference to the actual `ufunc`, worded as "invalid value encountered in reduce", could almost mean *nothing* for an ordinary user. Compare if we change the warning message to "NaN has been generated in reduce"
* You mentioned there're several flavours of NaN. Not sure if it is necessary to document something about them?

The backdrop is that it would normally take a person at least one concentrated hour to study and begin to understand the IEEE 754 standard. It may take even more hours to read and  understand the error/corner cases.

An ordinary user tends to always translates in mind an abstruse phrase to a straightforward phrase I'd say. But how good is the correspondence between "invalid value encountered" and "NaN has been generated"? Does one supersede the other? How big is **the gap** (which may be critical to know for a real application)? Even I am not sure at all after conversing so long, and I think it is _very_ hard to find the answer without more detailed yet straightforward documentation somewhere.

All the above for your consideration.

**Comment by jli05** [comment]
At the root, it's all about what's the _precise_ cause of the FP exception, could we tell it in a straightforward language?
