### ISSUE TITLE
DOC: numpy.tensordot documentation could be improved

### ISSUE THREAD

**Issue by YudiXie** [numpy/numpy#25543]
### Issue with current documentation:

I am looking at the [numpy.tensordot documentation](https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html), and found the following sentence pretty confusing.

> When axes is integer_like, the sequence for evaluation will be: first the -Nth axis in a and 0th axis in b, and the -1th axis in a and Nth axis in b last.

Especially what does evaluation mean is not clear, and what is 0th axis is confusing. 

### Idea or request for content:

I think it might be better to change this to something like:

When axes is integer_like:
When axes is a positive integer, the sequence for **evaluation (multiply each element and then sum)** will be: first the -Nth axis in a and **1st** axis (axis 0) in b, until the -1th axis in a and Nth axis (axis N - 1) in b.
When axes = 0, return the tensor product, for example, A of size (a, b, c) and B of size (x, y, z). np.tensordot(A, B, 0) will return a tensor of (a, b, c, x, y, z)

**Comment by Amth274** [comment]
can i do the documentation for this ??

**Comment by mattip** [comment]
@Amth274 we don't assign issues. Please look at the [how to build documentation](https://numpy.org/doc/stable/dev/howto_build_docs.html) docs so you can get an idea of what is involved in building locally, and the [contributing docs](https://numpy.org/doc/stable/dev/development_workflow.html) for our general development workflow. Be sure to link back to this issue in your PR.

**Comment by DhavalParmar61** [comment]
Does it look okay? I think for axes 0 product is mentioned so no need to mention that here. For remaining,

When axes is integer_like and If axes is a positive integer, the sequence for evaluation (multiply each element and then sum) will first start with the -Nth (Nth from last) index axis in a and 0th index in b, until the -1st (last) index axis in a and (N - 1)th index in b.

**Comment by YudiXie** [comment]
I think this is great. One thing that might still be confusing is the use of `0th index in b` and `(N - 1)th index in b.` Because it is not clear to me what 0th means in English, and `(N - 1)th index` is actually the Nth axis or the axis indexed by N-1.

It would be clearer to change it to:
`First axis (or axis=0) in b` and `Nth axis (or axis=N-1) in b`

**Comment by DhavalParmar61** [comment]
Actually, when we deal with arrays or vectors in almost all cases index starts with zero (based on different python packages). So it should not create confusion but writing `Nth axis (or axis=N-1) in b` can create confusion because actually axis is N or N-1. Though I am fine with both.

**Comment by YudiXie** [comment]
I agree, as you pointed out, there could be confusion in my previous response. 

Something like this might be better.
`First axis (or equivalently axis=0) in b` and `Nth axis (or equivalently axis=N-1) in b`

The `0th` axis still sounds confusing to me and potentially other people [1](https://en.wikipedia.org/wiki/Zero-based_numbering), but I am not sure how widely that is used in the Python community. At least in the Numpy [user guide](https://numpy.org/doc/stable/user/basics.indexing.html), expressions like this are often used:

> the 1-D array at the first position (0) is returned.
> the first index value is 0 for both index arrays, and thus the first value of the resultant array is y[0, 0].

So I think using `First axis (or equivalently axis=0) in b` is better.

**Comment by DhavalParmar61** [comment]
How about,

When axes is integer_like and If axes is a positive integer, the sequence for evaluation (multiply each element and then sum) will first start with the Nth position from the last (axis=-N) in a and first position (axis=0) in b, until the last position (axis=-1) in a and Nth position (axis=N - 1) in b.

**Comment by YudiXie** [comment]
This is awesome! Thanks!

**Comment by DhavalParmar61** [comment]
Someone please verify and merge this pull request https://github.com/numpy/doc/pull/21 related to #25543.
