### ISSUE TITLE
DOC: Punctuation

### ISSUE THREAD

**Issue by linus-md** [numpy/numpy#25544]
### Issue with current documentation:

Hello,

there are a lot of places in the documentation where a sentence ending "." is followed by two spaces instead of one space.

```
"""
def uniform(self, low=0.0, high=1.0, size=None):
        """
        uniform(low=0.0, high=1.0, size=None)

        Draw samples from a uniform distribution.

        Samples are uniformly distributed over the half-open interval
        ``[low, high)`` (includes low, but excludes high).  In other words,
        any value within the given interval is equally likely to be drawn
        by `uniform`.

        Parameters
        ----------
        low : float or array_like of floats, optional
            Lower boundary of the output interval.  All values generated will be
            greater than or equal to low.  The default value is 0.
        high : float or array_like of floats
            Upper boundary of the output interval.  All values generated will be
            less than high.  The high limit may be included in the returned array of 
            floats due to floating-point rounding in the equation 
            ``low + (high-low) * random_sample()``.  high - low must be 
            non-negative.  The default value is 1.0.
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  If size is ``None`` (default),
            a single value is returned if ``low`` and ``high`` are both scalars.
            Otherwise, ``np.broadcast(low, high).size`` samples are drawn.
     """
```

There are nine instances in this example and up to 189 instances in ``_generator.pyx``. Other files are also affected by this. Is this intended?

**Comment by seberg** [comment]
This is customary in some regions (I think I learned it in canada even, but don't remember?).  I started often doing it myself, I believe the reason is that when you typeset seriously you would also insert a longer space after a period.  I would not bother either way, but also don't care if someon else has a strong opinion.

**Comment by rossbar** [comment]
Personally, I don't think these types of style concerns are worth any effort. I'm going to close this to discourage bikeshedding on it!

**Comment by linus-md** [comment]
@seberg ok, I did not know that. Thanks.

**Comment by charris** [comment]
> I'm going to close this to discourage bikeshedding on it!

Two spaces was standard with typewriters, that standard has faded over the years and is pretty much gone these days. Another old standard that will probably go is keeping the period inside quoted passages, a practice that supposedly produced less fragile cast type.
