### ISSUE TITLE
DOC: What is the mathematical theory or idea behind numpy.isclose?

### ISSUE THREAD

**Issue by hungpham3112** [numpy/numpy#25550]
### Issue with current documentation:

I'm trying to find the theory of formula behind `numpy.isclose()`. According to [pytorch document](https://pytorch.org/docs/stable/generated/torch.isclose.html) and [here](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwJcglzrXJbLRVZXclhsngGqKl):
`∣input−other∣≤ atol + rtol×∣other∣`

I search something like **_"relative tolerance in numerical analysis"_** but didn't found any formal definition or official term for `rtol` and `atol`. Where should I look for? What is the mathematical theory of `numpy.isclose()`? Why choose `rtol=1e-05, atol=1e-08,` as default number?

**Comment by jakevdp** [comment]
The core logic of `np.isclose` can be seen here: https://github.com/numpy/numpy/blob/f4800212761a311fe20e8bb4d16f45e7a37cfdb1/numpy/_core/numeric.py#L2375-L2379

**Comment by hungpham3112** [comment]
> The core logic of `np.isclose` can be seen here:
> 
> https://github.com/numpy/numpy/blob/f4800212761a311fe20e8bb4d16f45e7a37cfdb1/numpy/_core/numeric.py#L2375-L2379
> 
> `rtol` is short for "relative tolerance" and `atol` is short for "absolute tolerance".

I already read the source code. I mean why numpy choose the above formula to calculate approximate value but why? What is the theory? Can you share some documentation or keyword that I should search?

**Comment by charris** [comment]
The problem is that floating point values are not uniformly spaced, in particular they are far denser around zero, hence the "atol" to handle that region, for larger values "rtol" makes more sense. You can find it discussed in "Numerical Recipes" among other books. Looking at the graph of `log`, which goes to -inf at zero, might also help.

**Comment by rkern** [comment]
There are multiple ways to combine the `atol` and `rtol` components together to make a determination both when the inputs are far from 0 (where `rtol` is mostly going to make the decision) and close to 0 (where `atol` is mostly going to dominate the decision). `+` is one way to smoothly combine them, assuming that you use sensible tolerance values (such that `atol` will have only a minor effect when the values are far from 0). It has a long history; [here are some lecture notes on the subject](http://web.mit.edu/10.001/Web/Tips/Converge.htm). `max()` would be another way to combine them, which is what's used in `math.isclose()` and a few other places in `scipy` algorithms. Personally, I find `max()` to be easier to interpret, and therefore reason about the appropriate values to use, but both do the same job, broadly described.

As for the default values, there is no real reasoning behind them other than to keep them smallish, and there haven't been too many complaints about them. Ideally, you should use your knowledge about the numerical properties of the algorithms that you are using and the truncation errors of the inputs going into them to estimate good `atol` and `rtol` values. In practice, everyone just starts with the defaults and adjusts them by a couple powers of 10 in either direction until things seem to look right.

**Comment by hungpham3112** [comment]
> There are multiple ways to combine the `atol` and `rtol` components together to make a determination both when the inputs are far from 0 (where `rtol` is mostly going to make the decision) and close to 0 (where `atol` is mostly going to dominate the decision). `+` is one way to smoothly combine them, assuming that you use sensible tolerance values (such that `atol` will have only a minor effect when the values are far from 0). It has a long history; [here are some lecture notes on the subject](http://web.mit.edu/10.001/Web/Tips/Converge.htm). `max()` would be another way to combine them, which is what's used in `math.isclose()` and a few other places in `scipy` algorithms. Personally, I find `max()` to be easier to interpret, and therefore reason about the appropriate values to use, but both do the same job, broadly described.
> 
> As for the default values, there is no real reasoning behind them other than to keep them smallish, and there haven't been too many complaints about them. Ideally, you should use your knowledge about the numerical properties of the algorithms that you are using and the truncation errors of the inputs going into them to estimate good `atol` and `rtol` values. In practice, everyone just starts with the defaults and adjusts them by a couple powers of 10 in either direction until things seem to look right.

What is the official or formal meaning of rtol and atol?

**Comment by rkern** [comment]
`rtol` stands for "relative tolerance", which will be scaled by the absolute value of the reference value. `atol` stands for "absolute tolerance", which won't be so rescaled. There's nothing more formal to say about them except the implementation.
