### ISSUE TITLE
MAINT: Create libnpymath repository

### ISSUE THREAD

**Issue by lysnikolaou** [numpy/numpy#25551]
Can someone with the appropriate permissions in the numpy org create a new repository for libnpymath, since it's now almost ready to use in scipy and nearly there to use on numpy as well? More info on #20880.

I'm sorry if this is not the correct venue to post an issue like this.

**Comment by mattip** [comment]
I created it. Can you open a PR against it?

**Comment by lysnikolaou** [comment]
Sorry, but I can't find it. Could you give me a link?

**Comment by mattip** [comment]
https://github.com/numpy/libnpymath It was private, I made it public.

**Comment by lysnikolaou** [comment]
I can't open a PR. I assume a `main` branch needs to be created, in order for me to be able to open a PR against it.

**Comment by mattip** [comment]
I pushed from https://github.com/lysnikolaou/libnpymath and added a LICENSE.txt file. Please open an issue there if it doesn't work properly.
