### ISSUE TITLE
Error while importing Numpy after python 3.11.6 installation

### ISSUE THREAD

**Issue by itzswaps** [numpy/numpy#25557]
### Steps to reproduce:

After I install python 3.11.6 installation, I get an error when I import numpy. The error looks like

### Error message:

```shell
"numpy: Error importing numpy: you should not try to import numpy from
its source directory; please exit the numpy source tree, and relaunch
your python interpreter from there."
```

**Comment by mattip** [comment]
More information needed. When you say "after I install..." what do you mean? Are you cloning the source repository and using a python command? Which command?

**Comment by OmmAshutosh** [comment]
try to unistall numpy module and install this module again and the problem will be solved. I have also receive the same issuse in the beingining

**Comment by krish1209** [comment]
You can use this code if you have accidently added NumPy's source directory to sys.path
import sys
if "numpy" in sys.path[0]:
    sys.path.remove(sys.path[0])

Before this, You can check the directory using pwd

After tying all, 
Simply uninstall and reinstall NumPy
pip uninstall numpy
pip install numpy

**Comment by seberg** [comment]
Closing, we would need more info about how numpy was installed and the full error output.
