### ISSUE TITLE
ENH: Wrap string ufuncs in np.strings to allow optional / default arguments

### ISSUE THREAD

**Issue by lysnikolaou** [numpy/numpy#25566]
Strings ufuncs accept arguments to configure various things, like maximum number of replacements in `replace` or start and end position of possible matches in `find`. The CPython API provides sensible defaults for those parameters, so that uses don't have to do things like `'ttt'.replace('t', 'a', 3)`. We should do the same in `np.strings` and wrap the ufuncs to allow optional keyword arguments with defaults.

That way the naming of the parameters will be improved as well, so that we have `endswith(buf, suffix, start, end)` instead of `endswith(x1, x2, x3, x4)`.

Proposed in https://github.com/numpy/numpy/pull/25558#issuecomment-1885187601.

**Comment by mhvk** [comment]
Much of the naming ended up already done in #25558! Do we still need the issue!?

**Comment by lysnikolaou** [comment]
I was thinking this issue would be about wrapping functions other than `replace` and `strip`. Things like `find`/`rfind`/`startswith` etc.
