### ISSUE TITLE
BUG: np.float16(-32767) returns -32770.0

### ISSUE THREAD

**Issue by mliukis** [numpy/numpy#25568]
### Describe the issue:

numpy up to version 1.25.2 returns incorrect value of -32770.0 for numpy.float16(-32767)

### Reproduce the code example:

```python
import numpy as np
np.float16(-32767)
-32770.0
```

### Error message:

```shell
no error message, only incorrect value is returned
```

### Python and NumPy Versions:

Linux:
1.23.3
3.9.15 (main, Nov  4 2022, 16:13:54) 
[GCC 11.2.0]

OS X:
1.25.2
3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]

### Runtime Environment:

**Linux: (can't install additional packages)**
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.2',
  'python': '3.11.4 (main, Dec 20 2023, 13:34:57) [GCC 13.1.0]',
  'uname': uname_result(system='Linux', node='XXXX', release='4.18.0-513.9.1.el8_9.x86_64', version='#1 SMP Thu Nov 16 10:29:04 EST 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX'],
                      'not_found': ['AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}}]
None

**OS X:**
[{'numpy_version': '1.25.2',
  'python': '3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]',
  'uname': uname_result(system='Darwin', node='XXXX', release='22.6.0', version='Darwin Kernel Version 22.6.0: Tue Nov  7 21:40:08 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'VORTEX',
  'filepath': '/Users/mliukis/anaconda3/envs/itslivecube_latest_numba/lib/libopenblas.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libopenblas',
  'threading_layer': 'openmp',
  'user_api': 'blas',
  'version': '0.3.21'},
 {'filepath': '/Users/mliukis/anaconda3/envs/itslivecube_latest_numba/lib/libomp.dylib',
  'internal_api': 'openmp',
  'num_threads': 10,
  'prefix': 'libomp',
  'user_api': 'openmp',
  'version': None}]
None

### Context for the issue:

Any code that relies on np.float16 representation of the integer value does not work as expected as values don't match.

**Comment by rkern** [comment]
`float16` only has about 4 significant decimal digits of resolution available to it (10 bits of mantissa). `-32767` is simply not representable by `float16` exactly. The nearest `float16`-representable number that exists is `-32770.0`, which is what you get. This is a fundamental limitation of `float16` that you have to be aware of and deal with.

```python
>>> np.finfo(np.float16).resolution
0.001
```

**Comment by ksunden** [comment]
Just to add a little bit here, numpy provides the `nextafter` method to give the next number (towards an endpoint, here 0) in a given dtype:

```python
>>> np.nextafter(a, 0, dtype=np.float16)
-32750.0
>>> a = np.float16(-32767)
>>> a
-32770.0
>>> np.nextafter(a, 0, dtype=np.float16)
-32750.0
```

Thus the options for `-32767` are either `-32770` or `-32750`, of which the former is clearly the closer match. If you need more precision than that, then you must use a larger dtype (or an integer dtype; that particular value _is_ representable by `np.int16`, but only just as the minimum value is `-32768`)

**Comment by mliukis** [comment]
Thank you, both! I guess I didn't use `float16` enough to learn about its limitations :)
