### ISSUE TITLE
BUG: NDArray stops tracking a SHM buffer when pickled and unpickled

### ISSUE THREAD

**Issue by ethanjahn** [numpy/numpy#25561]
### Describe the issue:

When working with an NDArray that shares a buffer with a block of SHM memory, the NDArray normally will update when the SHM block is updated. Weirdly though, if I pickle the NDArray, the array and the underlying SHM seem to become unlinked, and changes to the SHM block will not impact the array any more. 

Since the multiprocess.shared_memory.SharedMemory object seems to pickle / unpickle while maintaining a reference to the underlying memory, it is surprising to me that the NDArray doesn't seem to maintain that reference.

To be honest, I'm not sure this is exactly a bug, but it is surprising behavior and would be helpful if the documentation around it was bolstered if it is expected behavior.

### Reproduce the code example:

```python
import asyncio
import pathlib
import pickle
from multiprocessing import shared_memory

import numpy as np

_TEST_ARRAY = np.zeros((1,2))

def make_shm() -> None:
    shm_ = shared_memory.SharedMemory(size=_TEST_ARRAY.nbytes, name="test-shm", create=True)
    array = np.ndarray(_TEST_ARRAY.shape, dtype=np.int16, buffer=shm_.buf)
    return shm_, array

def modify_shm() -> None:
    shm_ = shared_memory.SharedMemory(size=_TEST_ARRAY.nbytes, name="test-shm")
    array = np.ndarray(_TEST_ARRAY.shape, dtype=np.int16, buffer=shm_.buf)
    array[0] = [3, 3]

async def main() -> None:
    shm_path = pathlib.Path("/dev/shm/test-shm")
    if shm_path.exists():
        shm_path.unlink()

    shm_, array = make_shm()

    # Whith this line uncommented, modify_shm() will *not* change the printed array,
    # regardless of whether the array was created in a thread or process.
    # array = pickle.loads(pickle.dumps(array))

    print(array)
    modify_shm()
    print(array)

    shm_.unlink()

if __name__ == "__main__":
    asyncio.run(main())
```

### Python and NumPy Versions:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.3
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

### Runtime Environment:

```
>>> import numpy; print(numpy.show_runtime())
[{'numpy_version': '1.26.3',
  'python': '3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]',
  'uname': uname_result(system='Linux', node='ethan-built', release='5.15.0-79-generic', version='#86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/ethan/.local/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 16,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None
```

### Context for the issue:

I work in robotics, and have a situation where one of our programs needs to instantiate a large block of memory about the state of the world, while still being responsive. To do this, we use multiprocessing to run this in a separate process, since it can take seconds to complete and is CPU bound. The class that manages the world state is pickleable, so this seemed fine, but we found this bug that when other programs modified the SHM, this program would not receive those updates, since the class used an np.ndarray.

If we could pickle the NDArray directly, it would make it easier for us to offload CPU intensive work to other processes.

**Comment by rkern** [comment]
It's expected, designed behavior. We don't get (m)any opportunities to customize the behavior of pickling for different use cases, so we pickle the data itself and not just a reference to the buffer that might have created it (in fact, I'm not sure if the `ndarray` object itself still knows that it was created in such a way). Which is good for most use cases (saving to a file, shipping it to another machine, etc.) but doesn't work for yours. In your case, you know more details about what really should be communicated to the other processes, the `SharedMemory` object itself. So keep track of that, send it across the communication channel, and (cheaply) recreate the `ndarray` on the other side.

**Comment by ethanjahn** [comment]
very helpful, thank you!

Will close now
