### ISSUE TITLE
BUG: np.array() only shallow-copies arrays with dtype=object

### ISSUE THREAD

**Issue by neutrinoceros** [numpy/numpy#25562]
### Describe the issue:

Arrays with `dtype=object` seem to be shallow-copied by `np.array`.
This is surprising for 2 reasons:
- other dtypes are deep-copied
- raw `objects` are not singletons and nothing prevents them to be copied in general, as illustrated hereafter
```python
import copy
a = object()
assert copy.copy(a) is not a # pass
```

### Reproduce the code example:

```python
import numpy as np
a = np.array(object())

# copy=True is also the default behaviour, I'm just making it extra explicit
b = np.array(a, copy=True) 
assert b.item() is not a.item()
```

### Error message:

```shell
AssertionError(...)
```

### Python and NumPy Versions:

1.26.3
3.12.0 (main, Oct 27 2023, 11:50:57) [Clang 15.0.0 (clang-1500.0.40.1)]

### Runtime Environment:

[{'numpy_version': '1.26.3',
  'python': '3.12.0 (main, Oct 27 2023, 11:50:57) [Clang 15.0.0 '
            '(clang-1500.0.40.1)]',
  'uname': uname_result(system='Darwin', node='kwanzaabot.home', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'armv8',
  'filepath': '/Users/clm/.pyenv/versions/3.12.0/envs/astropy.dev/lib/python3.12/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]

### Context for the issue:

This came out as the root cause of a bug in astropy (https://github.com/astropy/astropy/issues/13435).

Perhaps a more striking illustration is
```python
a = np.array(1028)
b = np.array(a, copy=True) 
assert b.item() is not a.item() # pass

a = np.array(1028, dtype=object)
b = np.array(a, copy=True) 
assert b.item() is not a.item() # fail
```

**Comment by rkern** [comment]
This is not a bug. `copy=True` means only that when the input is already an `ndarray` that meets the requested `dtype` that we still make a new `ndarray` and copy its data over to the new array (with `copy=False`, it works just like `np.asarray()` in that if it's already an `ndarray` that meets the criteria, you'll just get that `ndarray` object back). In the case of `dtype=object`, "the data" that gets copied is just the set of pointers to the objects. Other dtypes are not deepcopied, per se. Their elements don't even _exist_ as Python objects until they are extracted out; they are not a comparable case.

FWIW, `copy.deepcopy()` should work fine on `dtype=object` arrays.

```python
>>> import copy
>>> import numpy as np
>>> x = np.array([object()])
>>> y = copy.deepcopy(x)
>>> y[0] is x[0]
False
```

The most we can do for this is to add to the documentation to clarify the behavior in this case and point to `copy.deepcopy()`.

**Comment by neutrinoceros** [comment]
Thanks @rkern. A documentation update would do it indeed.

**Comment by rkern** [comment]
Thanks. What change in what part of our documentation do you think would have helped you?

**Comment by neutrinoceros** [comment]
While researching this I look up `numpy.array`'s docstring. I think it would suffice to add a little more detail about the `copy` argument.

**Comment by mhvk** [comment]
@neutrinoceros - sounds reasonable, though I think one probably will want to add something under `Notes` (with perhaps a reference to it under `copy` itself). Also, `ndarray.copy()` would be another logical place for this. Would you be willing to make a PR? The docstrings are set in `numpy/_core/_add_newdocs.py`.

Hmm, checking, I see that `np.copy` (from `numpy/lib/_function_base_impl.py`) does have a warning about object arrays... Probably good to ensure that the three are consistent with each other...

**Comment by neutrinoceros** [comment]
Yes, I should be able to open a PR to fix this tomorrow.

**Comment by Bharath-12205425** [comment]
To fix this issue, you can explicitly use copy.deepcopy() to create a deep copy of the array with dtype=object
import numpy as np
import copy

a = np.array(1028)
b = np.array(a, copy=True)
assert b.item() is not a.item()  # Pass

a = np.array(1028, dtype=object)
b = copy.deepcopy(a)
assert b.item() is not a.item()  # Pass
