### ISSUE TITLE
BUG: Can't install Numpy 1.26.0 with Python 3.10.2

### ISSUE THREAD

**Issue by rajasekaran86** [numpy/numpy#25572]
### Describe the issue:

Tried to install Numpy 1.26.0 with Python 3.10.2 but command prompt shows "Requirement already satisfied". I would like to know does Numpy 1.26.0 support older versions or not.

### Reproduce the code example:

```python
>pip install numpy
Requirement already satisfied: numpy in c:\users\raj\python310\lib\site-packages (1.22.3)
```

### Python and NumPy Versions:

Numpy 1.26.0 and Python 3.10-2

**Comment by jakevdp** [comment]
numpy 1.26 does support Python 3.10. If you already have numpy installed and would like to update it, you can use
```
pip install --upgrade numpy
```

**Comment by rajasekaran86** [comment]
> numpy 1.26 does support Python 3.10. If you already have numpy installed and would like to upgrade it, you can use
> 
> ```
> pip install --upgrade numpy
> ```

Now it's working.Thanks for the info.
