### ISSUE TITLE
ENH: jax.numpy at[].set() syntax

### ISSUE THREAD

**Issue by albert-mathews** [numpy/numpy#25576]
### Proposed new feature or change:

hello, I'm trying to write code that can easily switch between numpy and jax.numpy, without changing any code except for what package is imported. 
for the most part, this is straight forward. the exception seems to be in the array slice+updating. for example:
```
# in numpy
np_arr = np.array([1,2,3,4])
np_arr[2:] = [5,6]

# in jax.numpy
jnp_arr = jnp.array([1,2,3,4])
jnp_arr = jnp_arr.at[2:].set([5,6])
```

this difference is where I cant seem to find a solution. I've tried using a custom fucntion like this:
```
def arr_update(arr, val, idx):
    arr[idx] = val
    return arr
```
but that doesn't work for anything more complex than 1d arrays with single element slice. of course i could change idx to a slice object, add more cases for more dimensions, but this seems hacky, likely wont scale well, and requires writing:
`arr = arr_update(arr,[5,6],slice(-2:None))`
which is not really a nice replacement for normal slicing+updating.

So I'm hoping I can make code that always uses the jax.numpy syntax (i dont need inplace updating). for example:
```
import <either numpy or jax.numpy> as np
arr = np.array([1,2,3,4])
arr = arr.at[2:].set([5,6])
```

I have tried subclassing `numpy.ndarray`, and this worked for the `at[]` op, but then the `set()` op fails because the object is no longer an array in the case of a single element slice. 
```
class NumPyWithUpdateSyntax(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
    
    @property
    def at(self):
        return self

    def set(self, indices, value):
        new_array = self.copy()
        new_array[indices] = value
        return new_array.view(NumPyWithUpdateSyntax)


np.ndarray = NumPyWithUpdateSyntax

```
the outcome from this is:
```
new_np_arr = np_arr.at[2].set(6)
E       AttributeError: 'numpy.float64' object has no attribute 'set'
```

So I've come here to ask for help, and anything is appreciated. thanks

**Comment by jakevdp** [comment]
This seems like it would be a good discussion for the Array API standard: https://data-apis.org/array-api/latest/

They've mostly punted on this question so far, but if it's important to you then it would be worth bringing up! Both JAX and NumPy have plans to support the array standard in the very near future.

In the meantime, I suspect your best approach will be to write your own convenience function for functional array updates which switches implementations based on the input type, and use that within your code.

**Comment by seberg** [comment]
Agreed, I'll just point out that `np.s_[...]` exists as a helper to construct an index (not that writing it yourself isn't trivial).
Also, you can write a tiny class that implements `__getitem__()` to get the `[]` syntax working without relying on NumPy.

There might be a point for such syntax, but I don't think this is sufficient: It already *is* very convenient in NumPy.

**Comment by albert-mathews** [comment]
> if it's important to you then it would be worth bringing up!

how do i do that? i could not find any contact info on that standard page. 

thank you @jakevdp and @seberg . very helpful. if JAX and numpy will in fact converge on that standard and it covers my use case, we'll just wait until that time comes.

**Comment by jakevdp** [comment]
The array api standard is developed here: https://github.com/data-apis/array-api
