### ISSUE TITLE
BUG: fft.*fft2: deprecation of "If s is not None, axes must not be None either"

### ISSUE THREAD

**Issue by crusaderky** [numpy/numpy#25605]
### Describe the issue:

Some fft functions state

> Deprecated since version 2.0: If s is not None, axes must not be None either.

while others don't.

In `fft.fft2` and `fft.ifft2`, this deprecation is mismatched between [documentation](https://numpy.org/devdocs/reference/generated/numpy.fft.fft2.html) and [implementation](https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/numpy/2.0.0.dev0/numpy-2.0.0.dev0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl).

In `fft.rfft2` and `fft.irfft2`, the deprecation is absent both in the documentation and in the implementation; I'm unsure if this omission was intentional or if they were forgotten.

| Function | Deprecated in documentation | Deprecated in implementation |
| --- | --- | --- |
| [i]fft2 | yes | no |
| [i]fftn | yes | yes |
| [i]rfft2 | no | no |
| [i]rfftn | yes | yes |

### Reproduce the code example:

```python
import numpy as np
arr = np.arange(100).reshape(10, 10)
np.fft.fft2(arr, (8, 9))
```

### Python and NumPy Versions:

python 3.11
numpy 2.0 nightly, 2024-01-17

**Comment by lucascolley** [comment]
This is partly deliberate but also sounds partly a mistake, let me take a look. The reason for only some functions being deprecated is that only some of them are part of [the array API standard](https://data-apis.org/array-api/draft/extensions/fourier_transform_functions.html), where this deprecation comes from. There is no need for the deprecation to apply to `fft2` and `ifft2`, but I assumed it did when I implemented it. As that isn't the case, I think it makes sense to just remove the incorrect documentation.

**Comment by lucascolley** [comment]
Nevermind, the problem is actually not with the deprecation at all but with the documented default values of `fft2` and `ifft2`. If you try `np.fft.fft2(arr, (8, 9), axes=None)` @crusaderky , you should see that the deprecation applies. The actual default for `axes` is `(-2, -1)`.
