### ISSUE TITLE
BUG: Different Ufunc behavior for large numbers 

### ISSUE THREAD

**Issue by AAWO** [numpy/numpy#25602]
### Describe the issue:

While analyzing data containing large numbers (256 bits each to be exact) I've stumbled upon a different behavior of `bitwise_xor` operation. Depending on the input integers values, the function returns a number (as expected) or a TypeError.

Description of the code example below:
1. Xor two different large numbers: 
```
-  4035225266123964411 (dec) = 0011011111111111111111111111111111111111111111111111111111111011 (bin)
- 18446744073709551614 (dec) = 1111111111111111111111111111111111111111111111111111111111111110 (bin)
```
by using `np.bitwise_xor(40...11, 18...14)`. This returns a TyperError.

2. Xor the same large number with itself: 
both `np.bitwise_xor(40...11, 40...11)` as well as `np.bitwise_xor(18...14, 18...14)` return `0` (as expected).

### Reproduce the code example:

```python
import numpy as np

np.bitwise_xor(4035225266123964411, 4035225266123964411)
# returns: 0
np.bitwise_xor(18446744073709551614, 18446744073709551614)
# returns: 0
np.bitwise_xor(4035225266123964411, 18446744073709551614)
# returns: TypeError
```

### Error message:

```shell
TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Python and NumPy Versions:
```
print(numpy.__version__)
# 1.24.4
print(sys.version)
# 3.8.10 (default, Nov 22 2023, 10:22:35)
# [GCC 9.4.0]
```

### Context for the issue:

I need to analyze multiple GB of raw 256 bits data words (acquired from external FPGA chip) for analysis and developing a more hardware-efficient solution for a specific application (compared to a standard correlation).

**Comment by mattip** [comment]
Calling `np.xor(v1, v2)` will start off by calling `np.array()` on the integer values.

The problem is that 18446744073709551614 is too big to fit into a `int64`, so NumPy creates a `uint64` array to hold it. But 4035225266123964411 can fit into an `int64`, so NumPy, being minimalistic, will create an `int64` array to hold it. `int64` and `uint64` cannot be cast together safely, so the operation fails.

You need to tell NumPy "Please use `uint64`, which can be done in various ways, any of these should work
```
np.bitwise_xor(np.array(4035225266123964411, dtype='uint64'), np.array(18446744073709551614, dtype='uint64'))
np.bitwise_xor(4035225266123964411, 18446744073709551614, dtype='uint64')
```

**Comment by AAWO** [comment]
Thank you for the explanation - it solved my problem.

Knowing the base of the problem I now understand the error message, but before it wasn't that clear. If I may make a suggestion, I'd add an information to the error message about the type of x1 and x2 parameter.

**Comment by AAWO** [comment]
Thank you for the explanation - it solved my problem.

Knowing the base of the problem I now understand the error message, but before it wasn't that clear. If I may make a suggestion, I'd add an information to the error message about the type of x1 and x2 parameter.

**Comment by seberg** [comment]
Actually (surprised even me a bit), on main the current result is that NumPy uses the default integer unless you convert it to an array yourself first.  Which means it fails with:
```
OverflowError: Python int too large to convert to C long
```
Could potentially be tweaked.  If you do pass arrays, you get the same error.  In many paths we print the dtypes here, but seems not this one.  Which indeed would be a nice little improvement.
