### ISSUE TITLE
BUG: float64 ufunc 'equal' has different behaviour in normal and debug mode

### ISSUE THREAD

**Issue by NeanderThaler** [numpy/numpy#25632]
### Describe the issue:

comparing float64 to a string works fine when running normally.
When running in debugger, i get an exception (see code below)

### Reproduce the code example:

```python
import unittest
import numpy as np

class MyTestCase(unittest.TestCase):
    def test_something(self):
        np.float64(3.14) == "pi"

if __name__ == '__main__':
    unittest.main()
```

### Error message:

```shell
Error
Traceback (most recent call last):
  File "C:\XXXXXXXXXXXXXXXX\test_Numpy.py", line 8, in test_something
    np.float64(3.14) == "pi"
numpy.core._exceptions._UFuncNoLoopError: ufunc 'equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.StrDType'>) -> None
```

### Python and NumPy Versions:

1.26.2
3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

### Runtime Environment:

[{'numpy_version': '1.26.2',
  'python': '3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='XXXXXXXXXX', release='10', version='10.0.19045', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\XXXXXXXXXXX\\Lib\\site-packages\\numpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None

**Comment by seberg** [comment]
What kind of debugger are you using how are you debugging exactly?

Just enabling pdb works fine for me (on a mac in ipython at least).  Didn't check if the details add up with this error:  but it is correct that the control-flow raises an internal error which is then cleared again.

**Comment by NeanderThaler** [comment]
Thanks for the fast response.

I use PyCharm as an IDE and their built-in debugger. Seems that this is causing the issues.
I noticed a warning 
```
UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
```
and when looking around, the pycharm debugger seems to do some stuff with numpy ... so i guess it's rather a PyCharm bug than a numpy bug?

**Comment by seberg** [comment]
I guess: yes, there are currently multiple things that will break with reloading, because we cache a lot of Python defined singletons (like the error class) in C.
So if this happens after reloading, that is probably the reason and not a big priority.

Of course it could be good to fix the reloading (i.e. invalidate caches).  Some of that would also be nice for other things like subinterpreters.  (There might also be potential to make sure we keep using the old version that is cached in C, but dunno)

I am not sure if we could prevent this from happening otherwise, somehow?

**Comment by ngoldbaum** [comment]
This seems to be a problem specific to the pycharm debugger, which apparently relies on being able to reload the module getting debugged. That won't work for numpy.

Please reopen if this ends up not being the real issue.
