### ISSUE TITLE
DOC: `numpy.binary_repr` is unclear about the deprecation of the parameter `width`

### ISSUE THREAD

**Issue by limabielefeld** [numpy/numpy#25634]
### Issue with current documentation:

In the [current doc](https://numpy.org/doc/stable/reference/generated/numpy.binary_repr.html) on `numpy.binary_repr`, under the parameter `width`, it simply says `Deprecated since version 1.12.0`.
After checking the [release notes of 1.12.0](https://numpy.org/devdocs/release/1.12.0-notes.html), it seems that only when an insufficient `width` is passed, the old behavior of silently ignoring the parameter is deprecated.
Thus the deprecation claim in the doc is very confusing: it looks like the whole `width` parameter is deprecated.

### Idea or request for content:

Be more precise about what is deprecated, e.g. add a sentence emphasizing "the parameter `width` itself is not deprecated".

**Comment by ngoldbaum** [comment]
Improvements to that deprecation warning in the docs would be very welcome, you’d just need to edit the docstring.

Also numpy 1.12 is very old, perhaps we should expire this deprecation that looks like it was missed to finalize a long time ago.

**Comment by msavinash** [comment]
This issue has been addressed in #25692 needs review and merge.
