### ISSUE TITLE
BUG: complex128 loses precision when constructed from string

### ISSUE THREAD

**Issue by bjodah** [numpy/numpy#25633]
### Describe the issue:

```python
>>> np.complex128('0.2j') + np.complex128('0.1j') - np.complex128('0.3j')
5.551115123125783e-17j
```
Note that the error is basically epsilon of float64. On my x86-64 machine (which uses 80-bit extended precision for `long double`), I would expect a few more decimal digits to be correct.

I can work around this by constructing `np.float128` for the real and imaginary parts and recombine them afterwards.

### Reproduce the code example:

```python
import numpy as np
assert abs((np.complex128('0.2j') + np.complex128('0.1j') - np.complex128('0.3j')).imag) <= np.finfo(np.float128).epsilon*0.3
```

### Python and NumPy Versions:

1.24.2
3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}},
 {'architecture': 'Cooperlake',
  'filepath': '/usr/local/lib/python3.11/dist-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 32,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None

### Context for the issue:

When computing reference values for tests, a few bits of extra precision is often useful.

**Comment by ngoldbaum** [comment]
Sorry, do you mean `complex256` if you want extended precision? `complex128` is two 64 bit floats.
