### ISSUE TITLE
BUG: argument of type "npyv_f64" is incompatible with parameter of type "__m512d"

### ISSUE THREAD

**Issue by philippegabert** [numpy/numpy#25649]
### Describe the issue:

I am trying to install py-numpy using spack using the command:
`spack install py-numpy`

I receive the following error messages:
`FAILED: numpy/core/libloops_exponent_log.dispatch.h_AVX512_SKX.a.p/meson-generated_loops_exponent_log.dispatch.c.o 
 error: argument of type "npyv_f64" is incompatible with parameter of type "__m512d" 
 error: a value of type "__m512d" cannot be used to initialize an entity of type "npyv_f64"`

### Reproduce the code example:

```python
`spack install py-numpy`
```

### Python and NumPy Versions:

Numpy 1.26.3

### Runtime Environment:

Spack: 0.22.0.dev0 (https://github.com/spack/spack/commit/75e96b856eba55f7a47a2f446b3cd4e8f3f90e3c)
Python: 3.7.16
Platform: linux-amzn2-icelake
Concretizer: clingo
Instance type: c6i.xlarge

### Context for the issue:

I have created an issue on the spack repo but they have recommended to open one here as it may be a numpy issue.
The original issue can be found here:
https://github.com/spack/spack/issues/42204

**Comment by rgommers** [comment]
Thanks @philippegabert.

I'll add the compiler and CPU detection result info here:

```
  C compiler for the host machine: /efs/spack/lib/spack/env/intel/icc (intel 2021.10.0 "icc (ICC) 2021.10.0 20230609")
  C linker for the host machine: /efs/spack/lib/spack/env/intel/icc ld.bfd 2.37
  C++ compiler for the host machine: /efs/spack/lib/spack/env/intel/icpc (intel 2021.10.0 "icpc (ICC) 2021.10.0 20230609")
  C++ linker for the host machine: /efs/spack/lib/spack/env/intel/icpc ld.bfd 2.37
...
  Test features "SSE SSE2 SSE3" : Supported
  Test features "SSSE3" : Supported
  Test features "SSE41" : Supported
  Test features "POPCNT" : Supported
  Test features "SSE42" : Supported
  Test features "AVX" : Supported
  Test features "F16C" : Supported
  Test features "FMA3" : Supported
  Test features "AVX2" : Supported (cached)
  Test features "AVX512F" : Supported
  Test features "AVX512CD" : Supported (cached)
  Test features "AVX512_KNL" : Supported
  Test features "AVX512_KNM" : Unsupported due to Compiler fails against the test code of "AVX512_KNM"
  Test features "AVX512_SKX" : Supported (cached)
  Test features "AVX512_CLX" : Supported
  Test features "AVX512_CNL" : Supported
  Test features "AVX512_ICL" : Supported
  Test features "AVX512_SPR" : disabled due to AVX512_SPR is disabled due to "intel compiler does not support it"
```

There's more info in the attached file on the original Spack issue.

@seiko2plus @r-devulap any thoughts?

**Comment by seiko2plus** [comment]
I wasn't able to verify #25652, Could you @philippegabert? It seems ICC is no longer part of the latest versions of Intel Oneapi
