### ISSUE TITLE
BUG: CI sometimes crashes on sort on macos_arm64

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#25685]
### Describe the issue:

I think it may happen only sometimes, otherwise it would have been noticed before, but there was a failure in the CI run on https://cirrus-ci.com/task/6368983864049664

Since the relevant PR, #25668, does not touch that side of the code at all, it seems unrelated, so reporting it here.

### Reproduce the code example:

```python
N/A
```

### Error message:

```shell
_____________________ numpy/_core/tests/test_multiarray.py _____________________
[gw2] darwin -- Python 3.11.7 /Users/admin/micromamba/envs/numpydev/bin/python3.11
worker 'gw2' crashed while running 'numpy/_core/tests/test_multiarray.py::test_sort_float[d-N127]'
=========================== short test summary info ============================
FAILED numpy/_core/tests/test_multiarray.py::test_sort_float[d-N127]
= 1 failed, 40600 passed, 289 skipped, 49 xfailed, 4 xpassed in 79.37s (0:01:19) =
```

### Python and NumPy Versions:

N/A

**Comment by mhvk** [comment]
Hmm, it does indeed not happen everytime, rerunning the same job, it succeeded: https://github.com/numpy/numpy/pull/25668/checks?check_run_id=20864648884

**Comment by Mousius** [comment]
This was originally raised in https://github.com/numpy/numpy/issues/25464, though I've failed to reproduce it locally.

**Comment by mhvk** [comment]
OK, sorry that I missed that.

**Comment by Mousius** [comment]
> OK, sorry that I missed that.

Thank you for raising it again 😸 it's good to know it's still happening and nudge me to look into it again.
