### ISSUE TITLE
BUG: einsum compute error

### ISSUE THREAD

**Issue by zcy618** [numpy/numpy#25694]
### Describe the issue:

hi friends:
when I use einsum to make complex matrix computing, I met error result, the compute flow as below:
        print("w1")
        print("{:.10f}".format(w1[0,0,0]))
        print("{:.10f}".format(w1[0,1,0]))
        print("{:.10f}".format(w1[1,0,0]))
        print("{:.10f}".format(w1[1,1,0]))
        
        print("Y_inv")
        print("{:.10f}".format(Y_inv[0,0,0]))
        print("{:.10f}".format(Y_inv[0,0,1]))
        print("{:.10f}".format(Y_inv[0,1,0]))
        print("{:.10f}".format(Y_inv[0,1,1]))     
        
        w1 = np.einsum('cef,feg->cgf', w1, Y_inv)
        
        print("w1")
        print("{:.10f}".format(w1[0,0,0]))
        print("{:.10f}".format(w1[0,1,0]))
        print("{:.10f}".format(w1[1,0,0]))
        print("{:.10f}".format(w1[1,1,0]))

the w1 shape is (2,2,513), Y_inv is (513,2,2)

the result is as below:
w1
2600000.0000000000+0.0000000000j
3800000.0000000000+800000.0000000000j
3800000.0000000000-800000.0000000000j
5800000.0000000000+0.0000000000j
Y_inv
100000.0000000000+0.0000000000j
0.0000000000+0.0000000000j
0.0000000000+0.0000000000j
100000.0000000000+0.0000000000j
w1
**260000006144.0000000000**+0.0000000000j
380000010240.0000000000+80000000000.0000000000j
380000010240.0000000000-80000000000.0000000000j
580000022528.0000000000+0.0000000000j

as you see, the result w1 is not correct, I think it should be: 2.6e+11 in the first row and the first col, but it is not.

And I also verified np.dot as below:
import numpy as np
 
def complex_matrix_multiplication(matrix1, matrix2):
    result = np.dot(matrix1, matrix2)
    return result

Cmatrix1 = np.array([[2600000+0.j, 3800000+800000j],
                    [3800000-800000j,  5800000+0.j]])

Cmatrix2 = np.array([[100000+0.j, 0+0.j],
                    [0-0.j, 100000.+0.j]])

matrix_3 = complex_matrix_multiplication(Cmatrix1, Cmatrix2)
print(matrix_3)

[[2.6e+11+0.e+00j 3.8e+11+8.e+10j]
 [3.8e+11-8.e+10j 5.8e+11+0.e+00j]]

the result is correct.

please help to check it.
Thanks

### Reproduce the code example:

```python
print("w1")
        print("{:.10f}".format(w1[0,0,0]))
        print("{:.10f}".format(w1[0,1,0]))
        print("{:.10f}".format(w1[1,0,0]))
        print("{:.10f}".format(w1[1,1,0]))
        
        print("Y_inv")
        print("{:.10f}".format(Y_inv[0,0,0]))
        print("{:.10f}".format(Y_inv[0,0,1]))
        print("{:.10f}".format(Y_inv[0,1,0]))
        print("{:.10f}".format(Y_inv[0,1,1]))     
        
        w1 = np.einsum('cef,feg->cgf', w1, Y_inv)
        
        print("w1")
        print("{:.10f}".format(w1[0,0,0]))
        print("{:.10f}".format(w1[0,1,0]))
        print("{:.10f}".format(w1[1,0,0]))
        print("{:.10f}".format(w1[1,1,0]))
```

### Python and NumPy Versions:

python: 3.9.12 64bit
Numpy: 1.23.4

**Comment by eendebakpt** [comment]
@zcy618 Could you provide the full matrices `w1` and `Y_inv`? You write that `w1` has shape `(2, 2, 513)`, but you only show a small part of the matrix. (alternatively, if possible you can provide python code which generated the `w1` and `Y_inv`)
Did you already test your code on a more recent version of numpy?

**Comment by seberg** [comment]
I will assume this is float32, and:
```
In [9]: np.nextafter(np.float32(260000006144.0), np.float32(0))
Out[9]: 259999990000.0
```
So the error is correct within one ULP and that is more than should likely be even expected with numerical precision.

If there seems to be more to this, please provide more details and we can reopen.
