### ISSUE TITLE
BUG: `np.tensordot` substantial overhead

### ISSUE THREAD

**Issue by randolf-scholz** [numpy/numpy#25713]
### Describe the issue:

I recently opened https://github.com/astral-sh/ruff/issues/9664, as I often see people implementing `np.trace(A@B)` which incurs am accidental cubic cost compared to the equivalent `np.tensordot(A.T, B)`. However, after running some benchmarks I discovered that `np.tensordot(A,B)` has a large overhead so that often even `np.sum(A*B)` is faster.

### Reproduce the code example:

```python
N = 64
A = np.random.randn(N, N)
B = np.random.randn(N, N)
%timeit np.trace(A.T @ B)
%timeit np.sum(A*B)
%timeit np.einsum("ij, ij -> ", A, B)
%timeit A.flatten().dot(B.flatten())
%timeit np.inner(A.ravel(), B.ravel())
%timeit np.tensordot(A, B)
```

### Error message:

```shell
# N=64
17.7 µs ± 93.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
6 µs ± 7.13 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
4.11 µs ± 13.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
3.29 µs ± 18.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.59 µs ± 23.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
12.7 µs ± 52.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

# N = 1024
12.9 ms ± 3.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.09 ms ± 11.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
463 µs ± 7.33 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
2.88 ms ± 54.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
27.5 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
57.9 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

For N=64, `tensordot(A,B)` is more than 2x as slow as `sum(A*B)` and 3-4x as slow as emulating `tensordot(A,B)` via einsum or `A.flatten().dot(B.flatten())` and 10x as slow as emulating via `np.inner(A.ravel(), B.ravel())`.

For N=1024, it is still substantially slower than `np.inner(A.ravel(), B.ravel())`, but one would expect only a constant overhead.

### Python and NumPy Versions:

1.26.2
3.11.6 (main, Oct 16 2023, 19:37:59) [GCC 11.4.0]

**Comment by eendebakpt** [comment]
The `np.tensordot` has overhead because of the argument parsing. The overhead can be reduced a bit (I created a PR for this). It could be reduced even more by creating a fast path for the `axis=2` case, but I do not know whether that is worth the extra complexity.

**Comment by randolf-scholz** [comment]
Seems like it is now on par with `np.inner(A.ravel(), B.ravel())`. 👍
