### ISSUE TITLE
BUG: Conflicting numpy imports Google Colab

### ISSUE THREAD

**Issue by finch-wren** [numpy/numpy#25725]
### Describe the issue:

So far, I have only observed this is in Google colab as we do not use it in a virtual environment. And you encounter it while installing other packages that specify a numpy version higher than the existing one in colab. Maybe it is a colab issue as well. Plase find the reproduction code in Google colab below. Please reach out in case of any more queries 

### Reproduce the code example:

```python
pip show numpy
#note the version say 1.23.x

pip install numpy ~= 1.26
pip show numpy
#this will show the latest one installed

import numpy
numpy.__version__
#this will still be the previous one 1.23.x
```

### Python and NumPy Versions:

1.23.5
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

#I installed 1.26.3 by the way!!

### Runtime Environment:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-12-deaa259f0b34>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import numpy; print(numpy.show_runtime())

[/usr/local/lib/python3.10/dist-packages/numpy/__init__.py](https://localhost:8080/#) in __getattr__(attr)
    309             val, msg = __deprecated_attrs__[attr]
    310         except KeyError:
--> 311             pass
    312         else:
    313             warnings.warn(msg, DeprecationWarning, stacklevel=2)

AttributeError: module 'numpy' has no attribute 'show_runtime'

###this is happening because my numpy is still at 1.23 while I just installed 1.26.x

### Context for the issue:

I am currently doing a deep learning architecture paper and I needed the results again of my model to make edits in paper to be published. I found this bug yesterday, but now I have just calmed the issue down with some manipulation but it ain't a long-term solution. Not sure if this is an issue with Google colab or numpy itself.

**Comment by mattip** [comment]
This is a colab issue, not one with NumPy. You need to ask on a colab forum how to change the basic colab imports. For instance, I saw this [stackoverflow post](https://stackoverflow.com/questions/55253498/how-do-i-install-a-library-permanently-in-colab) about setting up a virtualenv inside colab.

**Comment by andyfaff** [comment]
It's as simple as `!pip install --upgrade numpy` in a notebook cell.

**Comment by finch-wren** [comment]
> It's as simple as `!pip install --upgrade numpy` in a notebook cell.

Does not fix the issue that simply - I think it's some mess-up with the file system in google colab. Let me raise it there.

**Comment by finch-wren** [comment]
> This is a colab issue, not one with NumPy. You need to ask on a colab forum how to change the basic colab imports. For instance, I saw this [stackoverflow post](https://stackoverflow.com/questions/55253498/how-do-i-install-a-library-permanently-in-colab) about setting up a virtualenv inside colab.

Thank you for your input. I will raise the issue in Google colab, I think it's come issue with the directory files in colab and global/default colab settings not being updated on updating of a package. Yes, I tried using virtualenv, it was cumbersome in colab as colab is not meant like that in general. I will raise the issue in colab. Thank you!

**Comment by finch-wren** [comment]
> This is a colab issue, not one with NumPy. You need to ask on a colab forum how to change the basic colab imports. For instance, I saw this [stackoverflow post](https://stackoverflow.com/questions/55253498/how-do-i-install-a-library-permanently-in-colab) about setting up a virtualenv inside colab.

Thank you for your input. I will raise the issue in Google colab, I think it's come issue with the directory files in colab and global/default colab settings not being updated on updating of a package. Yes, I tried using virtualenv, it was cumbersome in colab as colab is not meant like that in general. I will raise the issue in colab. Thank you!

**Comment by jakevdp** [comment]
Note that in Jupiter notebook environments in general, if you `pip install` a new version of a previously-imported package, you must restart the kernel in order to import and use the newly-installed version. This is due to the way that Python caches previously-imported packages. In Colab you can do this by choosing *Runtime->Restart Session*.
