### ISSUE TITLE
DOC(?): Position-only start parameter in arange (numpy 2.0)

### ISSUE THREAD

**Issue by mstimberg** [numpy/numpy#25743]
### Issue with current documentation:

I am not 100% sure whether this is actually a documentation issue or some kind of regression (but I assume the former):
In numpy 1.26.3, the following three calls to `arange` give the same result:
```pycon
>>> import numpy as np
>>> np.__version__
'1.26.3'
>>> np.arange(2, 5)
array([2, 3, 4])
>>> np.arange(2, stop=5)
array([2, 3, 4])
>>> np.arange(start=2, stop=5)
array([2, 3, 4])
```
In numpy 2.0, the last call raises an error:
```pycon
>>> np.__version__
'2.0.0.dev0+git20240131.b49373d'
>>> np.arange(start=2, stop=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: arange() got an unexpected keyword argument 'start'
```
I am a bit confused about where this change comes from, since already in numpy 1.26.3, the `arange` definition appears to define `start` as a position-only parameter:
https://github.com/numpy/numpy/blob/b4bf93b936802618ebb49ee43e382b576b29a0a6/numpy/array_api/_creation_functions.py#L75-L94
On the other hand, the documentation does not state it as a position-only parameter in 1.26:
https://numpy.org/doc/1.26/reference/generated/numpy.arange.html
but does so for 2.0:
https://numpy.org/devdocs/reference/generated/numpy.arange.html

### Idea or request for content:

Assuming the change in behaviour is intended, I think it should be mentioned in the documentation of the `start` parameter (along the lines of "New in 2.0: `start` is a position-only parameter and cannot be provided as a keyword argument") and potentially as a (minor) breaking change in the release notes.

**Comment by mattip** [comment]
This was changed in #23536 for 2.0 and appears in the [2.0 release notes](https://numpy.org/devdocs/release/2.0.0-notes.html#arange-s-start-argument-is-positional-only), although it was noted [in the PR](https://github.com/numpy/numpy/pull/25336#issuecomment-1867805386):

> If it turns out this breaks code and we get complaints we could consider only deprecating using start as a keyword

**Comment by seberg** [comment]
It was itentional, but since you are the second person who seems to like to write `start=, stop=`, I suspect we should just add that ability.  (The worst of what we had was that `arange(start=3)` was actually `arange(stop=3)`

**Comment by mstimberg** [comment]
> This was changed in #23536 for 2.0 and appears in the [2.0 release notes](https://numpy.org/devdocs/release/2.0.0-notes.html#arange-s-start-argument-is-positional-only), although it was noted [in the PR](https://github.com/numpy/numpy/pull/25336#issuecomment-1867805386):

Many apologies, I *thought* I searched for it in the 2.0 release notes, but apparently I did not…

> It was itentional, but since you are the second person who seems to like to write `start=, stop=`, I suspect we should just add that ability. (The worst of what we had was that `arange(start=3)` was actually `arange(stop=3)`

My actual use case is slightly more complicated than that: we are wrapping `arange` and forwarding parameters to it. It wouldn't be a big deal to change it, but personally I feel that `np.arange(2, stop=5)` looks odd (since the `start` argument is not "more obvious" than `stop`), while both `np.arange(2, 5)` and `np.arange(start=2, stop=5)` make intuitive sense. Agreed that `np.arange(start=3)` is evil, though :)

**Comment by mattip** [comment]
@seberg on 1.26.2 this is not true, it raises a TypeError.

> `arange(start=3)` was actually `arange(stop=3)`

**Comment by seberg** [comment]
Hmmm, I really thought the PR would have fixed more than just disallow passing `start` by keyword.

So I guess we would end up basically just reverting the change due to `start=0, stop=4` being relatively common (although fixing should be easier/better than actual revert).
I am a bit surprised, but sounds fine to me.

(I am happy to keep the docs as they are since spelling out the logic is rather impossible in "signature" syntax.)
