### ISSUE TITLE
Slicing over the same index of a numpy array

### ISSUE THREAD

**Issue by kmld24** [numpy/numpy#25742]
### Describe the issue:

In some situations of our code, we need to access and change the values of a numpy array from the starting index to the final index. Unfortunately, when the starting index is equal to the final index, the targeted values do not change. Example: if A is a 2D array of 10 x 10 dimensions, the A[5:5, :]= VALUE does not work. This appears also for 1D and 3D arrays. (This works fine in Matlab and Octave.).

### Reproduce the code example:

```python
import numpy as np

# Array creation
A = np.zeros((100,100))

# Changing values
A[50:50, 0:60] = 10

# Does not work
print(A.nonzero())
```

### Error message:

```shell
Non error message is raised.
```

### Python and NumPy Versions:

Python 3.12
Numpy version 1.26.3 (the latest version)

**Comment by mattip** [comment]
> ...from the starting index to the final index. Unfortunately, when the starting index is equal to the final index, the targeted values do not change

There are no values to change since such a slice will always return an empty object. This is the way slices work on Python, and is not NumPy specific:
```
>>> a = list(range(10))
>>> print(a[5:5])
[]
```

What am I missing?

**Comment by mattip** [comment]
Also see the [notes section of the "NumPy for MATLAB users" documentation](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html#notes) which describes some work-arounds for the differences in indexing.

**Comment by seberg** [comment]
Closing, the behavior is covered in the documentation.  I know that assigning to empty slices may seem surprising, but it is perfectly consistent.

**Comment by kmld24** [comment]
I was not aware that the situation was already known, but I was expecting that the indicated value would change if there was not a slice. Thank you for the response.

**Comment by seberg** [comment]
You are indicating an empty slice (that is no values, try without assignment!).  So all of the indicated values *do* change (since there is nothing to change).
