### ISSUE TITLE
Tone down ABI printout length  (pybind11 related, already much shorter in final release)

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#25741]
It may be nice to reduce the ABI warning, especially with pybind11 it is quite long right now (in pre-release mode).  From meeting:

* The very very long ABI mismatch for _ARRAY_API and pybind11 issue is confusing
  * We'd like to get a traceback so it is clear from which package the warning is coming (that package used an old pybind11 to build its binaries) (Sebastian will have a look).
  * We need a new pybind11 release! (Ralf to poke)

**Comment by rgommers** [comment]
Thanks! I did open that issue two weeks ago: https://github.com/pybind/pybind11/issues/5009. No real esponse yet.

**Comment by ngoldbaum** [comment]
I just hit this as well, it's very confusing if the error gets suppressed somehow. In my case, it was coming from importing `pyarrow` inside pandas.

I ended up figuring it out after putting a `breakpoint()` call in the python code that generates the error. It would be nice if we could have some context in the error message explaining which package needs to be recompiled or reinstalled from a nightly.
