### ISSUE TITLE
DOC: documentation for `invert` is incorrect, as it does not return two's complement for signed integers

### ISSUE THREAD

**Issue by evertrol** [numpy/numpy#25747]
### Issue with current documentation:

The documentation for [`invert`](https://numpy.org/devdocs/reference/generated/numpy.invert.html) states (first sentence):
> Compute bit-wise inversion, or bit-wise NOT, element-wise.

Two paragraphs down, it states:
> For signed integer inputs, the two’s complement is returned.

These are not equivalent things (going by the common definition of two's complement, as found on e.g. [Wikipedia](https://en.wikipedia.org/wiki/Two%27s_complement). A test shows the bit-wise NOT is returned, not the two's complement.

The notes even mention
> numpy.bitwise_not is an alias for [invert](https://numpy.org/devdocs/reference/generated/numpy.invert.html#numpy.invert):
>
>     np.bitwise_not is np.invert
>     True

which makes it even clearer. 

It's likely a result of a mistaken thought of equivalency.

The issue was brought to light at [this StackOverflow question](https://stackoverflow.com/questions/77925955/unexpected-behavior-of-numpy-invert/77926058#77926058).

Note that the example section also mentions two's complement, but differently:
> When using signed integer types the result is the two’s complement of the result for the unsigned type:

Perhaps this is what actually is meant, but I find it confusing to read ("the two's complement of the result for the unsigned type" implies the two's complement of the unsigned type was taken. I guess it means something like the two's complement of the bit-wise NOT of the unsigned type, after converting the that bit-wise NOT result to a signed type?)

**Comment by charris** [comment]
Whoa, that is old documentation. I suspect that function is not much used.

**Comment by mattip** [comment]
We don't assign work. Please comment in your PR `fixes #25747` which will link back to here.
