### ISSUE TITLE
BUG: numpy.lib.stride_tricks.sliding_windows_view provides inconsistent results when used with numpy.pad

### ISSUE THREAD

**Issue by Grumpys-Dad** [numpy/numpy#25746]
### Describe the issue:

when using the sliding_windows_view on a multi-dimensional array which contains pads the output is inconsistent with an unpadded array. In particular the final n elements of any dimension in an array are ignored., (where n is the window axis size).

### Reproduce the code example:

```python
import numpy as np
import numpy.lib.stride_tricks as npt
ArrayA = np.pad(np.ones((5,5), dtype=int32), (1,1),'constant', constant_values = (0,0))
v = npt.sliding_window_view(ArrayA,(3,3),writeable = True)
v[1,1]+=2
produces:
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 3., 3., 1., 1., 0.],
       [0., 3., 3., 3., 1., 1., 0.],
       [0., 3., 3., 3., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])
"""I would expect all elements = 1 to be incremented to 3 given the above code.
Similar code, excluding the padding, works as expected.
I tried a number of different pad options EG constant, wrap and others.
All produced unexpected output."""



```

### Error message:

```shell
N/A
```

### Python and NumPy Versions:

1.24.3
3.11.5  packaged by Anaconda, Inc. (main, Sep 11 2023, 13:26:23[MSC v.1916 64 bit (AMD64)

### Runtime Environment:

N/A

### Context for the issue:

Research into physical matter quantisation.
I think I have a work-around so no real priority.
Just hate seeing faults in my work.

**Comment by Grumpys-Dad** [comment]
Whoops - included a typo there. ArrayA should be 2 dimensional not 3 (10 , 10) not (10,10,10)
II could not copy anythind directly as the computer I ran it on has some security features that prevent me from accessing the internet.

**Comment by seberg** [comment]
I don't understand what results you expect, this seems perfectly right.  Please initially the array with something like `np.arange(25).reshape(5, 5)`, experiment a bit, and then explain what you expect to see for the operations.

My guess is, you are thinking of `v[..., 1, 1] += 3`?

N.B.: Here it doesn't matter, but if you use advanced indexing (indexing with arrays), you need to use `np.add.at`.  Also NumPy should copy the `v[1, 1]` if it had overlapping memory, but it doesn't here.

**Comment by Grumpys-Dad** [comment]
Hi Sebastian.
Thankyou for your response
This was my original code and the output from it  - ArrayA
import numpy as np
import numpy.lib.stride_tricks as npt
ArrayA = (np.ones((5,5), dtype=int32),
v = npt.sliding_window_view(ArrayA,(3,3),writeable = True)
v[1,1]+=2
produces:
array([[1., 1., 1., 1.,1.],
          [1., 3., 3., 3.,1.],
          [1., 3., 3., 3.,1.],
          [1., 3., 3., 3.,1.],
          [1., 1., 1., 1.,1.]])
Because I wanted the full 5 by 5 array to be increased by the addition I then added padding by changing the code to ;

import numpy as np
import numpy.lib.stride_tricks as npt
ArrayA = np.pad(np.ones((5,5), dtype=int32), (1,1),'constant', constant_values = (0,0)) ## this line changed.
v = npt.sliding_window_view(ArrayA,(3,3),writeable = True)
v[1,1]+=2

I **expected** to see an output array like 
array([[0., 0.,0., 0., 0., 0., 0.],
          [0., 3., 3., 3., 3., 3. 0.],
          [0., 3., 3., 3., 3., 3. 0.],
          [0., 3., 3., 3., 3., 3. 0.],
          [0., 3., 3., 3., 3., 3. 0.],
          [0., 3., 3., 3., 3., 3. 0.]
          [0., 0., 0., 0., 0., 0.,0.]])
Instead I got the output as per the original post which superficially looks the same, but in reality has substantial differences

To be clear, I had experimented extensively on this coding before joining github to post a  problem. I understand just how much of your time can be wasted on trivial queries.
WRT your suggestion on adding to individual elements I have never had a problem with += before but I will try your suggestion of np.add.at.

As a final note, I wrote my own routine for mapping the subarray, so if you wish to close off this bug report, it is OK by me, but I guess it will come up again sometime. I can assure you the problem becomes much worse with 3 and more dimensions when using padded arrays.

**Comment by seberg** [comment]
This is what I meant to look at:
```python
In [16]: import numpy.lib.stride_tricks as npt

In [17]: arr = np.arange(25).reshape((5, 5))

In [18]: arr2 = np.pad(arr, (1, 1), 'constant', constant_values=(0, 0))

In [19]: arr2
Out[19]: 
array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  9,  0],
       [ 0, 10, 11, 12, 13, 14,  0],
       [ 0, 15, 16, 17, 18, 19,  0],
       [ 0, 20, 21, 22, 23, 24,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [20]: v = npt.sliding_window_view(arr2, (3, 3), writeable=True)

In [21]: v[1, 1]
Out[21]: 
array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [22]: v[1, 1] -= 100

In [23]: arr2
Out[23]: 
array([[   0,    0,    0,    0,    0,    0,    0],
       [   0, -100,  -99,  -98,    3,    4,    0],
       [   0,  -95,  -94,  -93,    8,    9,    0],
       [   0,  -90,  -89,  -88,   13,   14,    0],
       [   0,   15,   16,   17,   18,   19,    0],
       [   0,   20,   21,   22,   23,   24,    0],
       [   0,    0,    0,    0,    0,    0,    0]])
```
If you look at `v[1, 1]` all the values it points to change just fine.  So, I suspect you just want a pretty simple change here somehow.

**Comment by seberg** [comment]
Closing, I still assume there is just a simple mind slip here, like the intention being to increase the window also to `5, 5` or so.  If not please do comment and I can reopen.
