### ISSUE TITLE
BUG: numpy.put causes endless loop if array is empty

### ISSUE THREAD

**Issue by Tobi823** [numpy/numpy#25744]
### Describe the issue:

In my project I want to use `numpy.put` and `numpy.take` to wrap-around a variable to safely access an array.

If the array is empty, numpy.take throws a "IndexError: cannot do a non-empty take from an empty axes." exception. I did expect that `numpy.put` also throws an exception. But instead it keeps running.

And the docs does not state that the array must not be empty :)

### Reproduce the code example:

```python
import numpy as np

array = np.asarray(list())
np.put(array, 1, 1, mode="wrap")
```

### Error message:

```shell
None - np.put keeps running and refuses to get killed by Ctrl+C
```

### Python and NumPy Versions:

Python 3.11.6
Numpy 1.26.3

**Comment by GoddessLuBoYan** [comment]
same bug as python3.8 and numpy 1.24.3

**Comment by iquelli** [comment]
working on it
