### ISSUE TITLE
DOC: The CPU build options doc needs an update for new build system

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#25786]
### Issue with current documentation:

The documentation for configuring SIMD when building ([source](https://github.com/numpy/numpy/blob/main/doc/source/reference/simd/build-options.rst)) ([rendered](https://numpy.org/devdocs/reference/simd/build-options.html)) needs an update to reflect the new build system.

**Comment by rgommers** [comment]
This was done in gh-25806, closing.
