### ISSUE TITLE
BUG: C-API `PyDataMem_SetHandler` is no longer exported in the numpy shared libraries in versions 1.26.x

### ISSUE THREAD

**Issue by kshepherdkx** [numpy/numpy#25808]
### Describe the issue:

I am a developer for a Python project called [PyKX](https://github.com/KxSystems/pykx), which embeds another programming language called `q` into `Python`. This language has custom C allocators for its internal types and we have used the `numpy` allocator overrides provided in [NEP-49](https://numpy.org/neps/nep-0049.html#nep-49-data-allocation-strategies) to make `numpy` allocate arrays with `q`s allocators, to provide bi-directional 0 copy conversions between `q` vectors and `numpy` arrays.

I recently tried adding `Python` 3.12 support for my project which required upping the `numpy` version to `1.26.x` (we use the C API so we build against the lowest possible version where possible) and ran into an undefined symbol error on import of a C module we build that handles the custom `numpy` allocators. I tried other `Python` versions building against `numpy` `1.26.x` and ran into the same issue. So it doesn't seems to be `Python` version related but rather a breaking change in the `numpy` C API.

### Reproduce the code example:

```python
As this issue arises from a built C module there isn't a simple code example.

$ git clone https://github.com/KxSystems/pykx.git
$ cd pykx
$ sed -i 's/numpy~=1.22/numpy~=1.26/g' pyproject.toml # Python 3.8 - 3.10
or
$ sed -i 's/numpy~=1.23/numpy~=1.26/g' pyproject.toml # Python 3.11
$ pip install .
$ python -c "import os; os.environ['QARGS'] = '--unlicensed'; os.environ['PYKX_ALLOCATOR']='1'; import pykx"

If a smaller example is required let me know and I will create a small project that contains only the code required to reproduce this issue.
```

### Error message:

```shell
Where `_numpy` is the name of a C based python module

if k_allocator:
>       from . import _numpy as _pykx_numpy_cext
E       ImportError: /home/kian/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pykx/_numpy.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyDataMem_SetHandler
```

### Python and NumPy Versions:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.4
3.10.5 (main, Dec  8 2023, 04:43:15) [GCC 13.2.1 20230801]
```

### Runtime Environment:

Ryzen 9 7950X3D
Arch Linux

```
>>> import numpy; print(numpy.show_runtime())
[{'numpy_version': '1.26.4',
  'python': '3.10.5 (main, Dec  8 2023, 04:43:15) [GCC 13.2.1 20230801]',
  'uname': uname_result(system='Linux', node='arch', release='6.7.4-arch1-1', version='#1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}},
 {'architecture': 'Cooperlake',
  'filepath': '/home/kian/.pyenv/versions/3.10.5/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 32,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None
```

### Context for the issue:

This is a breaking change within the `numpy` C API, without a solution or a workaround it is not possible for me to add `Python` 3.12 support for my project. There are very few people with public code showing real world use cases for `NEP-49` so I haven't been able to find anyone elses code that has a solution to this issue.

I am happy to provide any additional information that may be required to debug this and am happy to build `numpy` from source off of branches that contain potential fixes if that helps.

**Comment by seberg** [comment]
NumPy changed the build setup to make it easier to create backwards compatible builds.  If you use new(ish) API, you need to ask for it to be available.  This one is basically the only relevant one.

To do this, add `-DNPY_TARGET_VERSION=NPY_1_22_API_VERSION` to your build or:
```
#define NPY_TARGET_VERSION NPY_1_22_API_VERSION
```
before including any NumPy headers.

**Comment by mattip** [comment]
> we have used the numpy allocator overrides provided in [NEP-49](https://numpy.org/neps/nep-0049.html#nep-49-data-allocation-strategies)

> There are very few people with public code showing real world use cases for NEP-49

Indeed! It is nice to hear that someone found it useful.

**Comment by kshepherdkx** [comment]
> NumPy changed the build setup to make it easier to create backwards compatible builds. If you use new(ish) API, you need to ask for it to be available. This one is basically the only relevant one.
> 
> To do this, add `-DNPY_TARGET_VERSION=NPY_1_22_API_VERSION` to your build or:
> 
> ```
> #define NPY_TARGET_VERSION NPY_1_22_API_VERSION
> ```
> 
> before including any NumPy headers.

Adding that compile flag has fixed the issue, thanks for the help. I think I probably read over it by accident in the docs; we had this flag being set `NPY_NO_DEPRECATED_API` and I misread that they were 2 separate flags and assumed we already had it in place.

Closing the issue as it seems to be passing for our tests now
