### ISSUE TITLE
BUG: Windows fatal exception code 0xc06d007e

### ISSUE THREAD

**Issue by Rational-IM** [numpy/numpy#25809]
### Describe the issue:

When running a very simple code (see below; from a previously similar issue reported), I receive the following error:

Windows fatal exception: code 0xc06d007e

After that, the kernel is restart (using Spyder 5.5.1; but it happens with other versions of Spyder too, like 5.5.0, that works fine). I tried installing Spyder + numpy in multiple ways - with Anaconda, with miniconda and conda-standalone. Nothing worked.

### Reproduce the code example:

```python
import numpy as np

a = np.array([
    [1., 0., 0.],
    [0., 1., 0.],
    [0, 0., 1.]
])

b = np.array([
    [1., 0., 0.],
    [0., 1., 0.],
    [0, 0., 1.]
])

print(np.dot(a, b))
```

### Error message:

```shell
Windows fatal exception: code 0xc06d007e

Main thread:
Current thread 0x00008e44 (most recent call first):
  File "c:\users\danil\onedrive\python_projects\canvas\canvas 30.py", line 23 in <module>
  File "C:\Users\danil\miniconda3\envs\spyder-5.5.1\Lib\site-packages\spyder_kernels\py3compat.py", line 356 in compat_exec
  File "C:\Users\danil\miniconda3\envs\spyder-5.5.1\Lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 473 in exec_code
  File "C:\Users\danil\miniconda3\envs\spyder-5.5.1\Lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 615 in _exec_file
  File "C:\Users\danil\miniconda3\envs\spyder-5.5.1\Lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 528 in runfile
  File "C:\Users\danil\AppData\Local\Temp\ipykernel_41640\313744497.py", line 1 in <module>

Restarting kernel...
```

### Python and NumPy Versions:

The attached file is an export of my environment: python 3.12.1 and numpy 1.26.4

### Runtime Environment:

Not sure if this is the requested outcome (as there is also an error) but here it is:

runfile('C:/Users/danil/OneDrive/Python_projects/Canvas/untitled0.py', wdir='C:/Users/danil/OneDrive/Python_projects/Canvas', current_namespace=True)
Traceback (most recent call last):

  File ~\miniconda3\envs\spyder-5.5.1\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\danil\onedrive\python_projects\canvas\untitled0.py:9
    print(numpy.show_runtime())

  File ~\miniconda3\envs\spyder-5.5.1\Lib\site-packages\numpy\lib\utils.py:66 in show_runtime
    config_found.extend(threadpool_info())

  File ~\miniconda3\envs\spyder-5.5.1\Lib\site-packages\threadpoolctl.py:415 in threadpool_info
    return ThreadpoolController().info()

  File ~\miniconda3\envs\spyder-5.5.1\Lib\site-packages\threadpoolctl.py:677 in info
    return [lib_controller.info() for lib_controller in self.lib_controllers]

  File ~\miniconda3\envs\spyder-5.5.1\Lib\site-packages\threadpoolctl.py:124 in info
    "num_threads": self.num_threads,

  File ~\miniconda3\envs\spyder-5.5.1\Lib\site-packages\threadpoolctl.py:139 in num_threads
    return self.get_num_threads()

  File ~\miniconda3\envs\spyder-5.5.1\Lib\site-packages\threadpoolctl.py:302 in get_num_threads
    return get_func()

OSError: [WinError -1066598274] Windows Error 0xc06d007e

### Context for the issue:

I use numpy in a code I run daily that is crucial for my business.

**Comment by Rational-IM** [comment]
Here is the environment export (couldn't attach as a .yml file):

name: spyder-5.5.1
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.16=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - astroid=3.0.3=py312h2e8e312_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.14.0=pyhd8ed1ab_0
  - bcrypt=4.1.2=py312hfccd98a_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=24.1.1=py312h2e8e312_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312h53d5487_1
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2024.2.2=h56e8100_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py312he70551f_0
  - chardet=5.2.0=py312h2e8e312_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - cookiecutter=2.5.0=pyhca7485f_0
  - cryptography=42.0.2=py312he4c2ea2_0
  - debugpy=1.8.1=py312h53d5487_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20230430=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - docstring-to-markdown=0.13=pyhd8ed1ab_0
  - docutils=0.20.1=py312h2e8e312_3
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - flake8=7.0.0=pyhd8ed1ab_0
  - gettext=0.21.1=h5728263_0
  - glib=2.78.3=h12be248_0
  - glib-tools=2.78.3=h12be248_0
  - gst-plugins-base=1.22.9=h001b923_0
  - gstreamer=1.22.9=hb4038d2_0
  - icu=73.2=h63175ca_0
  - idna=3.6=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intel-openmp=2024.0.0=h57928b3_49841
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.2=pyha63f2e9_0
  - ipython=8.21.0=pyh7428d3b_0
  - isort=5.13.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.1=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jellyfish=1.0.3=py312hfccd98a_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py312h2e8e312_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - keyring=24.3.0=py312h2e8e312_0
  - krb5=1.21.2=heb0366b_0
  - libblas=3.9.0=21_win64_mkl
  - libcblas=3.9.0=21_win64_mkl
  - libclang=15.0.7=default_hde6756a_4
  - libclang13=15.0.7=default_h85b4d89_4
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.4=hd77b12b_0
  - libglib=2.78.3=h16e383f_0
  - libhwloc=2.9.3=default_haede6df_1009
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=21_win64_mkl
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.42=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libsqlite=3.45.1=hcfcfb64_0
  - libvorbis=1.3.7=h0e60522_0
  - libxml2=2.12.5=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312he70551f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.0.0=h66d3029_49657
  - more-itertools=10.2.0=pyhd8ed1ab_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.16.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.4=py312h8753938_0
  - numpydoc=1.6.0=pyhd8ed1ab_0
  - openssl=3.2.1=hcfcfb64_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandoc=3.1.11.1=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=3.4.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - pcre2=10.42=h17e33f8_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prompt-toolkit=3.0.43=py312haa95532_0
  - psutil=5.9.8=py312he70551f_0
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycodestyle=2.11.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.2.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pylint=3.0.3=pyhd8ed1ab_0
  - pylint-venv=3.0.3=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py312hc560f31_3
  - pyqt=5.15.10=py312hd77b12b_0
  - pyqt5-sip=12.13.0=py312h2bbff1b_0
  - pyqtwebengine=5.15.10=py312hd77b12b_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.12.1=h2628c8c_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.1.2=pyhd8ed1ab_0
  - python-lsp-server=1.10.0=pyhd8ed1ab_0
  - python-lsp-server-base=1.10.0=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytoolconfig=1.2.6=py312haa95532_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=306=py312h53d5487_2
  - pywin32-ctypes=0.2.2=py312h2e8e312_1
  - pyyaml=6.0.1=py312he70551f_1
  - pyzmq=25.1.2=py312h1ac6f91_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_0
  - qstylizer=0.2.2=pyhd8ed1ab_0
  - qt-main=5.15.8=h9e85ed6_18
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.3.0=pyh9208f05_0
  - qtconsole=5.5.1=pyhd8ed1ab_0
  - qtconsole-base=5.5.1=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - referencing=0.33.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.7.0=pyhd8ed1ab_0
  - rope=1.12.0=pyhd8ed1ab_0
  - rpds-py=0.17.1=py312hfccd98a_0
  - rtree=1.2.0=py312h72b5f30_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sip=6.7.12=py312h53d5487_0
  - six=1.16.0=pyh6c4a22f_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=7.2.6=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.8=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.5=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - spyder=5.5.1=py312h2e8e312_0
  - spyder-kernels=2.5.0=win_pyh7428d3b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.11.0=h91493d7_1
  - text-unidecode=1.3=pyhd8ed1ab_1
  - textdistance=4.5.0=pyhd8ed1ab_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - tornado=6.3.3=py312he70551f_1
  - traitlets=5.14.1=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.20240106=pyhd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - ujson=5.9.0=py312h53d5487_0
  - urllib3=2.2.0=pyhd8ed1ab_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - watchdog=4.0.0=py312h2e8e312_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - whatthepatch=1.0.5=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=h8ffe710_2
  - yapf=0.40.1=pyhd8ed1ab_0
  - zeromq=4.3.5=h63175ca_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h12be248_0
prefix: C:\Users\danil\miniconda3\envs\spyder-5.5.1

**Comment by seberg** [comment]
Unlikely to be NumPy related, `dot` calls blas, which is MKL.  So it should be either MKL or some other odd interaction.  You might want to try what happens outside of spyder, maybe this is Qt or so.

My suspicion would be that somehow your blas install is broken, but I don't know how (I assume Numpy is *not* pip installed but installed through conda/mamba)

**Comment by math411** [comment]
Currently, I am also seeing some threading issues ([example execution](https://github.com/amazon-braket/amazon-braket-algorithm-library/actions/runs/7875440613/job/21487323563?pr=132)). It is notable that these failures were only see on MacOS runners but I will confirm whether this is the case for other OS's.

When constraining numpy to `numpy<=1.26.3`, the issue went away. I am still looking into what changed but for now, there seems to be a correlation.

**Comment by Yeop-Jung** [comment]
Could be an issue with Spyder 5.5.1. 
I tried the same code above on pycharm community version and it was fine.

**Comment by sgwu** [comment]
I came across a similar issue yesterday, not using numpy, but matplotlib + spyder, below is the error message:
`
Windows fatal exception: code 0xc06d007e


Main thread:
Current thread 0x000023f0 (most recent call first):
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\transforms.py", line 2436 in get_affine
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\transforms.py", line 2437 in get_affine
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\patches.py", line 587 in draw
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\artist.py", line 72 in draw_wrapper
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\figure.py", line 3153 in draw
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\artist.py", line 72 in draw_wrapper
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\artist.py", line 95 in draw_wrapper
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 388 in draw
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\backends\backend_qt.py", line 459 in _draw_idle
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\ipykernel\eventloops.py", line 128 in loop_qt
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 487 in advance_eventloop
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\tornado\ioloop.py", line 738 in _run_callback
  File "C:\Users\wdsyy\anaconda3\lib\asyncio\events.py", line 80 in _run
  File "C:\Users\wdsyy\anaconda3\lib\asyncio\base_events.py", line 1905 in _run_once
  File "C:\Users\wdsyy\anaconda3\lib\asyncio\base_events.py", line 601 in run_forever
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 195 in start
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 739 in start
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\spyder_kernels\console\start.py", line 330 in main
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\spyder_kernels\console\__main__.py", line 24 in <module>
  File "C:\Users\wdsyy\anaconda3\lib\runpy.py", line 87 in _run_code
  File "C:\Users\wdsyy\anaconda3\lib\runpy.py", line 197 in _run_module_as_main


Restarting kernel...
`
Here is my code:
`
import matplotlib.pyplot as plt

plt.plot([0,1,2])
`
Like @Yeop-Jung , I tried my code in jupyter lab and it runs fine.
> Could be an issue with Spyder 5. I tried the same code above on pycharm community version and it was fine.

The bug appeared after I updated my packages in conda by `conda update --all`. I tried downgrading spyder to previous versions, didn't work.

**Comment by sgwu** [comment]
I came across a similar issue yesterday, not using numpy, but matplotlib + spyder, below is the error message:
```
Windows fatal exception: code 0xc06d007e


Main thread:
Current thread 0x000023f0 (most recent call first):
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\transforms.py", line 2436 in get_affine
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\transforms.py", line 2437 in get_affine
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\patches.py", line 587 in draw
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\artist.py", line 72 in draw_wrapper
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\figure.py", line 3153 in draw
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\artist.py", line 72 in draw_wrapper
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\artist.py", line 95 in draw_wrapper
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 388 in draw
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\matplotlib\backends\backend_qt.py", line 459 in _draw_idle
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\ipykernel\eventloops.py", line 128 in loop_qt
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 487 in advance_eventloop
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\tornado\ioloop.py", line 738 in _run_callback
  File "C:\Users\wdsyy\anaconda3\lib\asyncio\events.py", line 80 in _run
  File "C:\Users\wdsyy\anaconda3\lib\asyncio\base_events.py", line 1905 in _run_once
  File "C:\Users\wdsyy\anaconda3\lib\asyncio\base_events.py", line 601 in run_forever
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 195 in start
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 739 in start
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\spyder_kernels\console\start.py", line 330 in main
  File "C:\Users\wdsyy\anaconda3\lib\site-packages\spyder_kernels\console\__main__.py", line 24 in <module>
  File "C:\Users\wdsyy\anaconda3\lib\runpy.py", line 87 in _run_code
  File "C:\Users\wdsyy\anaconda3\lib\runpy.py", line 197 in _run_module_as_main


Restarting kernel...
```

Here is my code:
```
import matplotlib.pyplot as plt

plt.plot([0,1,2])
```

Like @Yeop-Jung , I tried my code in jupyter lab and it runs fine.
> Could be an issue with Spyder 5. I tried the same code above on pycharm community version and it was fine.

The bug appeared after I updated my packages in conda by `conda update --all`. I tried downgrading spyder to previous versions, didn't work.

**Comment by seberg** [comment]
This should probably be floated to conda-forge.  Maybe it is a Spyder issue, maybe an MKL issue, or maybe a pacakging one, I don't know.

**Comment by ModelAdminIFCT** [comment]
FYI, I installed spyder 5.4  and now it works fine.

**Comment by Rational-IM** [comment]
I reported the issue at Spyder's GitHub. I will close the issue here due to @Yeop-Jung reporting a similar issue with matplotlib.

**Comment by GitKia1392** [comment]
Its 92% an issue with yo pc. 

Reg
Kiamehr

**Comment by Yeop-Jung** [comment]
For the final comment for this matter, 
Try to open spyder through the anaconda navigator or anaconda prompt. This resolved the issue for me

**Comment by sgwu** [comment]
> Final comment for this matter, Try to open spyder through the anaconda navigator or anaconda prompt. This resolved the issue for me

This solved the issue for me as well! Thanks!!

**Comment by Rational-IM** [comment]
I confirm that starting Spyder from Anaconda's Prompt worked - see below (albeit I received an error message - not sure it is related to the original problem). I believe this points the issue to Spyder 5.5.1.

Would someone care to comment why running it from Anaconda Prompt solves the issue? 

![image](https://github.com/numpy/numpy/assets/57544001/6ec1a9d1-67b8-486d-aaf7-b386edbe9f8a)

**Comment by GitKia1392** [comment]
The last comment on this issue...

**Comment by ccordoba12** [comment]
> Would someone care to comment why running it from Anaconda Prompt solves the issue?

Chiming in as @Rational-IM posted this problem in the Spyder issue tracker as well: it seems that conda envs are not activated correctly now (i.e. perhaps since the last release of Anaconda/Miniconda) when applications are started from the Windows Start menu. But that's not the case when launching Spyder in a terminal because you need to activate the env yourself before doing it. 

Since that mechanism (i.e. env activation in Start menu shortcuts) had been working fine for years, in Spyder we didn't activate the environment in which it's installed before creating a new console. But we'll change that in our next version (5.5.2) to account for that bug.

**Comment by sam-s** [comment]
inability to run python+numpy+matplotlib in batch via msys2 bash is a serious detriment.
running via "anaconda prompt" is at best a workaround, not a fix, especially since relatively recently (2 weeks ago?) it worked.

**Comment by mattip** [comment]
I am locking this issue for more comments since it was closed a while ago. @sam-s (or anyone else) if this is still blocking you, please open a new issue with the exact conditions under which it occurs.
