### ISSUE TITLE
BUG: numpy.fft not importable on macOS arm64 (numpy 2.0)

### ISSUE THREAD

**Issue by mstimberg** [numpy/numpy#25815]
### Describe the issue:

After installing `numpy 2.0.0.dev ` via the Python wheel on GitHub's macOS-14 image ([running on M1 hardware](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)), importing `numpy.fft` fails with an error about a missing `libc++` library.

I am afraid I am not able to help much with debugging beyond this report, since I don't have access to the architecture myself (i.e. outside of GitHub Actions).

### Reproduce the code example:

After installing `numyp` via pip (on Python 3.12):
```
python -m pip install --pre \
  -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple \
  numpy
```
The following fails:
```
python -c 'import numpy.fft'
```

Here's a repo with a GitHub workflow reproducing the issue:
https://github.com/mstimberg/numpy_m1_test
Workflow run: https://github.com/mstimberg/numpy_m1_test/actions/runs/7884651266/job/21514096538

### Error message:

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/fft/__init__.py", line 203, in <module>
    from . import _pocketfft, _helper
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/fft/_pocketfft.py", line 39, in <module>
    from . import _pocketfft_umath as pfu
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/fft/_pocketfft_umath.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: <29BA43E7-8454-3737-8420-9E4CE7D6CB81> /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/fft/_pocketfft_umath.cpython-312-darwin.so
  Reason: tried: '/Users/admin/micromamba/envs/numpydev/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/admin/micromamba/envs/numpydev/lib/libc++.1.dylib' (no such file), '/Users/admin/micromamba/envs/numpydev/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/admin/micromamba/envs/numpydev/lib/libc++.1.dylib' (no such file)
```

### Python and NumPy Versions:

```
2.0.0.dev0+git20240210.2946577
3.12.2 (v3.12.2:6abddd9f6a, Feb  6 2024, 17:02:06) [Clang 13.0.0 (clang-1300.0.29.30)]
```

### Runtime Environment:

```
[{'numpy_version': '2.0.0.dev0+git20240210.2946577',
  'python': '3.12.2 (v3.12.2:6abddd9f6a, Feb  6 2024, 17:02:06) [Clang 13.0.0 '
            '(clang-1300.0.29.30)]',
  'uname': uname_result(system='Darwin', node='Mac-1707818295450.local', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:25 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_VMAPPLE', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]
None
```

**Comment by seberg** [comment]
Seems all about `@rpath/libc++.1.dylib` not being found so not surprising that it works locally probably.

Ping @andyfaff maybe you know the reason?  SciPy must have a solution to this?

**Comment by ngoldbaum** [comment]
I can reproduce this on my laptop using the nightly wheel.

Local builds work fine though:

```
± spin python -c "import numpy.fft; print('imported numpy.fft!')"
Invoking `build` prior to invoking Python:
$ /Users/goldbaum/.pyenv/versions/3.11.6/bin/python3.11 vendored-meson/meson/meson.py compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /Users/goldbaum/.pyenv/versions/3.11.6/bin/ninja -C /Users/goldbaum/Documents/numpy/build
ninja: Entering directory `/Users/goldbaum/Documents/numpy/build'
[1/1] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
$ /Users/goldbaum/.pyenv/versions/3.11.6/bin/python3.11 vendored-meson/meson/meson.py install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="/Users/goldbaum/Documents/numpy/build-install/usr/lib/python3.11/site-packages"
🐍 Launching Python with PYTHONPATH="/Users/goldbaum/Documents/numpy/build-install/usr/lib/python3.11/site-packages"
$ /usr/bin/env python -P -c 'import numpy.fft; print('"'"'imported numpy.fft!'"'"')'
imported numpy.fft!
```

**Comment by mattip** [comment]
Local builds will compile with the local c++ runtime, so it will be found when importing NumPy. 

The scipy `scipy-1.12.0-cp310-cp310-macosx_12_0_arm64.whl` wheel also links to the same shared object, so I think it would have the same problem if that was missing:
```
% otool -L <path>/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-310-darwin.so
<path>/scipy/fft/_pocketfft/pypocketfft.cpython-310-darwin.so:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

**Comment by andyfaff** [comment]
I'm trying to look into this on my computer, using the dev wheel from nightly. I don't get the error with python3.10.11 (conda-forge), but I do get the error with 3.12.1 (also conda-forge).

Possibly related: the numpy wheel builds obtain compilers using [micromamba install -y -c conda-forge compilers python=3.11](https://github.com/numpy/numpy/blob/main/tools/ci/cirrus_wheels.yml#L80) using a micromamba provided python. Hence the micromamba in the paths. 
For scipy the system compiler suite is used, with gfortran provided by homebrew.

Possible routes to fix:
- try using a non-empty `delocate` command again, this may fix up the path for the dylib.
- try using gfortran from a different source (homebrew?)

**Comment by mattip** [comment]
> Possibly related: the numpy wheel builds obtain compilers using [micromamba install -y -c conda-forge compilers python=3.11](https://github.com/numpy/numpy/blob/main/tools/ci/cirrus_wheels.yml#L80) using a micromamba provided python. Hence the micromamba in the paths.
> For scipy the system compiler suite is used, with gfortran provided by homebrew.

Is there any objective reason to prefer one over the other (other than this problem)?

**Comment by andyfaff** [comment]
micromamba should hopefully furnish gfortran without having to resort to arcane gfortran utils scripts.

**Comment by andyfaff** [comment]
When I run the [cirrus wheel build locally](https://github.com/numpy/numpy/wiki/Debugging-CI-guidelines) for cp312, and comment out the `export CIBW_REPAIR_WHEEL_COMMAND_MACOS=""` line, then the resulting wheel has no issues. However, it does bundle `.dylibs/libc++.1.0.dylib`.

Ideally it'd be good not to have to bundle that library. When I use homebrew gfortran the libc++.dylib isn't bundled.

**Comment by matthew-brett** [comment]
Just guessing - but I suppose micromamba gfortran links to `@rpath/libc++` rather than the more standard `/usr/lib/libc++`.

**Comment by matthew-brett** [comment]
And I wonder, if so, whether this is a misfeature of micromamba Gfortran.   Worth a bug report / issue?

**Comment by andyfaff** [comment]
@matthew-brett, investigating this further. I took the cirrus build CI and ran it locally. The output from `delocate-listdeps is`
```
+ export DYLD_LIBRARY_PATH=$PWD/.openblas/lib && echo DYLD_LIBRARY_PATH $DYLD_LIBRARY_PATH && delocate-listdeps /private/var/folders/2f/3sd99gzd12g01qxs44n328qc0000gn/T/cibw-run-bnkgjisb/cp312-macosx_arm64/built_wheel/numpy-2.0.0.dev0-cp312-cp312-macosx_14_0_arm64.whl && delocate-wheel --require-archs arm64 -w /private/var/folders/2f/3sd99gzd12g01qxs44n328qc0000gn/T/cibw-run-bnkgjisb/cp312-macosx_arm64/repaired_wheel -v /private/var/folders/2f/3sd99gzd12g01qxs44n328qc0000gn/T/cibw-run-bnkgjisb/cp312-macosx_arm64/built_wheel/numpy-2.0.0.dev0-cp312-cp312-macosx_14_0_arm64.whl
DYLD_LIBRARY_PATH /private/tmp/cirrus-ci/working-dir/.openblas/lib
/Users/admin/micromamba/envs/numpydev/lib/libc++.1.0.dylib
INFO:delocate.delocating:Copying library /Users/admin/micromamba/envs/numpydev/lib/libc++.1.0.dylib to numpy/.dylibs/libc++.1.0.dylib
INFO:delocate.delocating:Modifying install name in numpy/fft/_pocketfft_umath.cpython-312-darwin.so from @rpath/libc++.1.dylib to @loader_path/../.dylibs/libc++.1.0.dylib
```

The compilers used are:
```
C compiler for the host machine: arm64-apple-darwin20.0.0-clang (clang 16.0.6 "clang version 16.0.6")
C linker for the host machine: arm64-apple-darwin20.0.0-clang ld64 609
C++ compiler for the host machine: arm64-apple-darwin20.0.0-clang++ (clang 16.0.6 "clang version 16.0.6")
C++ linker for the host machine: arm64-apple-darwin20.0.0-clang++ ld64 609
```
I suspect that those compilers are more modern than provided by Xcode on the average Sonoma computer. e.g. clang on my mac M3 (which is up to date) is:

```
(dev3) teapot:numpy andrew$ clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
``` 

So I believe that the micromamba compilers where building/linking against a `libc++` version which is probably not available on an average Sonoma mac (unless you've installed something with micromamba/conda/mamba which has installed it). Consequently, because the wheel build wasn't using `delocate` (that matrix entry doesn't use openblas) the required libc++ wasn't bundled with the wheel, causing the issue.

It's interesting to consider how we know wheels are good. Most of the testing is obviously dedicated to running the numpy test suite. However, that doesn't pick up issues like this one because the libs required by the wheel are by definition already present on the build machine. Perhaps a separate step is needed, on a clean machine without extra compilers, to check that build/delocate worked correctly. Otherwise we only know that things are wrong when people try to use defective wheels.

**Comment by matthew-brett** [comment]
Yes - it looks like the micromamba setup has its own `libc++` at `/Users/admin/micromamba/envs/numpydev/lib/libc++.1.0.dylib` - so delocate is doing the right thing to include it in the wheel.   I wonder whether micromamba really needs its own `libc++`?  And what the license is?
