### ISSUE TITLE
BUG: If xp is not increasing

### ISSUE THREAD

**Issue by husayn-mohammadi** [numpy/numpy#25811]
### Describe the issue:

If xp is not increasing, the interpolation results can be nonsensical.
What I mean is if 'xp' is in an ascending order it works well but if it is in a descending order, e.g., xp = [2, 1] and fp = [0.2, 0.1], the output of numpy.interp(1.5, xp, fp) is 0.1 rather than 0.15. 

### Reproduce the code example:

```python
import numpy as np

Xij = [2, 1]
Yij = [0.2, 0.1]
np.interp(1.5, Xij, Yij)

Out[26]: 0.1
```

### Python and NumPy Versions:

Python Version: 3.11.7
NumPy Version: 1.26.3

**Comment by rkern** [comment]
This is [documented reasonably thoroughly in the docstring](https://numpy.org/doc/stable/reference/generated/numpy.interp.html).
