### ISSUE TITLE
DOC: Release note snippets lost

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#25829]
I think this lost the ones that were inlcuded by the previous generation in https://github.com/numpy/numpy/pull/24510?  There some smaller fixups on that, but not sure they are relevant, maybe it is easier to just pull in all those fragments again.

_Originally posted by @seberg in https://github.com/numpy/numpy/issues/25827#issuecomment-1945178006_

**Comment by charris** [comment]
Might just merge the two, I have done that before. Made me wish for 
```
$ git co <somewhere> <whatever> as tmp
```
In any case, the previous version isn't lost.

**Comment by seberg** [comment]
Right, just should remember to eventually restore whatever was there (likely not much anyway).

**Comment by rgommers** [comment]
I'll fix it and then will follow up with the edits to make the log ready for the release.
