### ISSUE TITLE
In-flight DType change follow-ups

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#25820]
The following changes are in progress:

* [x] An overview of these changes and how downstream code should be updated for the transition guide.
* [x] The flags are still semi-public, the need to move.  This means also making them `usigned` and adding the hack to at least unpickle old pickles with the "negative" flag value.  (Follow up to gh-25816).
* [x] The metadata, etc. fields are not actually removed yet gh-25802.
* [x] Expose `PyArray_Pack` gh-23893
* [x] `PyArray_GetArrFuncs` needs docs.

**Comment by seberg** [comment]
All except exposing `PyArray_Pack` is part of the last PR(s).  I would like that (and yes, it may be mentioned in the docs), but it isn't blocking for an rc (no ABI break).

**Comment by rgommers** [comment]
All done, closing. Thanks @seberg!
