### ISSUE TITLE
ENH: add array methods for nan* functions e.g. nansum, nancumsum, nanmin, nanmax, nanmean, ...

### ISSUE THREAD

**Issue by ancri** [numpy/numpy#25826]
### Proposed new feature or change:

I often work with multidimensional arrays and much prefer the `ndarray.sum()` method to the `numpy.sum(ndarray)` function. Would you consider adding methods for other `nan*` functions as well e.g. (in some hypothetical order of popularity) `nansum`, `nancumsum`, `nanmin`, `nanmax`, `nanmean`, `nanstd`, `nanpercentile`, `nanquantile`?

If not, would love to understand the motivation.

Thank you!

**Comment by mhvk** [comment]
Thanks for the suggestion.  In general, new features should be suggested on the mailing list first, to get feedback, but I think here the chance of accepting it is rather low: generally people feel `ndarray` already has too many methods, and indeed in numpy 2.0 some are going to be deprecated or removed (e.g., `.ptp()`). 

A general issue is that ideally methods of a class always make sense, independent of what data exactly is in the class, but as is, some `ndarray` methods do not make sense for all data types. For instance, regular `.mean()` has no meaning for string or structured arrays. Obviously, that should not stop every addition (I certainly use `.mean()`, etc., all the time and agree with your preference for the method over the function), but the `nan*` ones would be rather worse in this regard, in that they make sense only for float data.

**Comment by rgommers** [comment]
I think this won't happen indeed, for the reasons @mhvk gave (plus maybe more, see below).

I personally don't quite agree with the method preference. If the whole NumPy API had been methods (like `pandas.DataFrame`), then it would feel natural. However, the split you end up with now if you use methods where you can is a completely arbitrary mix between function calls and method calls (because numpy has ~6x more functions than ndarray methods), and I'd argue that that is worse than only using functions.

This ship has sailed a long time ago I think - since NumPy 1.0 or even before. Also other array libraries prefer a functional style, as does the array API standard.

**Comment by ancri** [comment]
Thank you for the replies!

This probably steers into a generic discussion of methods vs functions, which I'm sure has been extensively litigated, but to motivate the preference for methods here: it simply ends up being more readable in code that applies successive transformations.

I provide a simple example below where we have an array of hourly temperature readings by state (using 10 sensors each) and we want to find out the state with the highest temperature variation over the course of the day.

```
temp = np.random.rand(24, 50, 10)  # dims are (hour-of-day, state, sensor)

# using methods, pretty readable
temp.mean(axis=2).std(axis=0).argmax()

# using functions, nested and harder for me to parse
argmax(std(mean(temp, axis=2), axis=0))
```

This is not meant to persuade anyone, just provided as context for the preference.

**Comment by charris** [comment]
The methods started in NumArray and were incorporated into NumPy. IIRC, Numeric had three, maybe four. The arguments as to suitability have been ongoing since, it is like Vim vs Emacs. The pipeline suggestion may settle things.

**Comment by charris** [comment]
That said, I would make a pipeline more like a decorator or function than a method itself.

**Comment by mhvk** [comment]
> That said, I would make a pipeline more like a decorator or function than a method itself.
> 
> EDIT Or maybe an operator.

Nice - though I think this should be on the mailing list to the suggestion there to have a `.pipe` method!

**Comment by rgommers** [comment]
I suggest we close this issue. If the pipeline API suggestion gains traction, that should be a new issue I think.

**Comment by rgommers** [comment]
It turns out there was already a more general "turn all numpy functions into ndarray methods" issue, from 8 months ago: gh-24081. So we can safely close this as a duplicate.
