### ISSUE TITLE
ENH: Numpy arrays of floats converted to string using astype(str) have unexpected behaviour

### ISSUE THREAD

**Issue by Pigizoid** [numpy/numpy#25841]
### Proposed new feature or change:

When converting an array of very small floats to str, the astype() function occasionally returns scientific notation instead of a str representation of a float.

This feels like an uninteded issue with the astype function, as there is no way to turn off the scientific notation as the notation is implied to be just a visual representation in the rest of the documentation. The only ways to convert the floats to the inteded string representation is to explicity declare it using a very slow and unvectorized for loop etc., or by using very strange or difficult methods like  arr = np.vectorize(np.core.multiarray.dragon4_positional)(arr)

It feels much more intentional for the astype() function to return only float representations as it is impossible to do the intentional string splitting on the scientific form.
e.g.  x.split('.')[1]  will return an error or incorrect formatting for every scientific notation returned

![image](https://github.com/numpy/numpy/assets/140896920/4b4c765f-8b64-4ec9-bb67-4f0096bab6ee)

**Comment by eendebakpt** [comment]
It seems numpy is following the python conversion here:
```
In [1]: import numpy as np
   ...: x=np.array([10**e for e in range(-6, 2)])
   ...: print(x.astype(str))
   ...: print([str(v) for v in x])
['1e-06' '1e-05' '0.0001' '0.001' '0.01' '0.1' '1.0' '10.0']
['1e-06', '1e-05', '0.0001', '0.001', '0.01', '0.1', '1.0', '10.0']
````

Your own suggestion `arr = np.vectorize(np.core.multiarray.dragon4_positional)(arr)` seems like a good alternative. Another option would be `[f'{v:f}' for v in x]`

Why are you trying to split on the `.` symbol? Perhaps there are alternative methods to achieve the same.

**Comment by Pigizoid** [comment]
i was just trying to split at the decimal so i can see the length of how many digits there are after the decimal
i was going to multiply out the float so it becomes a larger integer

i suppose the work around might be going into messing around with the mantissa or something, im not very familiar with that level of float manipulation and slicing at the decimal seemed to be a common way to get the remainder as a whole integer

i was mostly just explaining that its quite counterintuitive for python to return scientific notation instead of the direct string format
