### ISSUE TITLE
BUG: Creating a negative-sized fixed-width dtype should error

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#25860]
### Describe the issue:

Currently we allow constructing negative-sized fixed-width dtypes even though they are useless. It would be more helpful to raise an error IMO

### Reproduce the code example:

```python
import numpy as np

print(np.dtype("S-1"))
```

### Error message:

```shell
dtype('S-1')
```

### Python and NumPy Versions:

2.0.0.dev0+git20240219.590d429
3.11.6 (main, Nov 27 2023, 12:13:52) [Clang 15.0.0 (clang-1500.0.40.1)]

**Comment by ngoldbaum** [comment]
c.f. #25853 where this behavior led to a seg fault in a poorly tested error path

**Comment by goncalobarias** [comment]
working on it
