### ISSUE TITLE
[f2py] BUG: missing Fortran modules in version 1.26.3

### ISSUE THREAD

**Issue by mancellin** [numpy/numpy#25867]
### Describe the issue:

I have a Python+Fortran library built with meson-python and f2py.

Something in version 1.26.3 is causing `pip install --no-build-isolation .` to compile incomplete binary extension where some Fortran modules are missing. (The ones with a filename starting with a capital letter, coincidentally?)

I browsed the list of commits but could not guess where the issue might come from. Do you have any clue?

The meson file: https://github.com/capytaine/capytaine/blob/df41fb23323f5b55ba4aed0c3f4667f86c25af11/meson.build

### Reproduce the code example:

```python
pip install --no-build-isolation .  # works on 1.26.2, not on 1.26.3
pip install .  # works on all versions
```

### Python and NumPy Versions:

Python 3.11, Numpy 1.26.2 or 1.26.3

**Comment by charris** [comment]
@HaoZeke Thoughts?

**Comment by mancellin** [comment]
Searching the log message on Github, I found
https://github.com/numpy/numpy/blob/e920ca42d98c4911c2294784f8809b38735923a4/numpy/f2py/f90mod_rules.py#L115-L117
and indeed the missing modules are the ones that are used by other modules and not containing only variables.

**Comment by HaoZeke** [comment]
Thanks for the detailed report @mancellin, there is a fix for this [on main](https://github.com/numpy/numpy/blob/e920ca42d98c4911c2294784f8809b38735923a4/numpy/f2py/f90mod_rules.py#L184-L189), as part of #25337, and I know some of the patches have been left for 2.x
Do you know if it also errors out on the current main? (am traveling, will check over the weekend as well)

**Comment by mancellin** [comment]
> Do you know if it also errors out on the current main?

Are there some kind of nightly builds somewhere or do I need to compile from source?

**Comment by rgommers** [comment]
There are nightlies at https://anaconda.org/scientific-python-nightly-wheels/numpy. Note that they're not ABI-compatible with 1.26, so if you need scipy/pandas/etc., you should also get those from https://anaconda.org/scientific-python-nightly-wheels.

**Comment by mancellin** [comment]
I'm confused by #25361, because the comment on the PR does not seem to match the code:

> if a module has functions (is not an only variable module) it shouldn't be skipped.

```python
if m['name'] in usenames and not onlyvars:  # Used module with functions
    outmess(f"\t\t\tSkipping {m['name']} since it is in 'use'...\n")
    continue  # Skip
```
