### ISSUE TITLE
DOC: update the note for "insert" so that it points to the explanation of why `...0...` and `...[0]...` are wildly different.

### ISSUE THREAD

**Issue by Pomax** [numpy/numpy#25895]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/generated/numpy.insert.html#numpy.insert currently has a note that reads:

>Note that for higher dimensional inserts obj=0 behaves very different from obj=[0] just like arr[:,0,:] = values is different from arr[:,[0],:] = values.

Which doesn't let readers find out what the specific difference in behaviour is, or why that difference exists.

### Idea or request for content:

Link out to whatever page(s) explain this difference in behaviour, so that people aren't left with more questions than they had before they saw that note =)

**Comment by mattip** [comment]
Closed by #26609
