### ISSUE TITLE
RuntimeWarning: invalid value encountered in exp2

### ISSUE THREAD

**Issue by mikezang** [numpy/numpy#25898]
### Describe the issue:

When I import numpy with v1.26.4 on mac Sonoma, I got warning message as below,

    /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/getlimits.py:225: RuntimeWarning: invalid value encountered in exp2
    epsneg_f128 = exp2(ld(-113))
    ** On entry to DLASCLS parameter number  4 had an illegal value
    ** On entry to DLASCLS parameter number  4 had an illegal value

the code on line 223-255 as below

    # Known parameters for IEEE 754 128-bit binary float
    ld = ntypes.longdouble
    epsneg_f128 = exp2(ld(-113))

and exp2 is define as below

    def exp2(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any:
    "exp2(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nCalculate `2**p` for all `p` in the input array.\n\nParameters\n----------\nx : array_like\n    Input values.\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via the default\n    ``out=None``, locations within it where the condition is False will\n    remain uninitialized.\n**kwargs\n    For other keyword-only arguments, see the\n    :ref:`ufunc docs <ufuncs.kwargs>`.\n\nReturns\n-------\nout : ndarray or scalar\n    Element-wise 2 to the power `x`.\n    This is a scalar if `x` is a scalar.\n\nSee Also\n--------\npower\n\nNotes\n-----\n.. versionadded:: 1.3.0\n\n\n\nExamples\n--------\n>>> np.exp2([2, 3])\narray([ 4.,  8.])"
    ...

I tried use code to ignore it but it doesn't work!

    warnings.filterwarnings("ignore", message="RuntimeWarning: invalid value encountered in exp2")

What can I avoid this warning?

### Reproduce the code example:

```python
import numpy as np
```

### Error message:

```shell
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/getlimits.py:225: RuntimeWarning: invalid value encountered in exp2
    epsneg_f128 = exp2(ld(-113))
    ** On entry to DLASCLS parameter number  4 had an illegal value
    ** On entry to DLASCLS parameter number  4 had an illegal value
```

### Python and NumPy Versions:

1.26.4
3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)]

### Runtime Environment:

[{'numpy_version': '1.26.4',
  'python': '3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 '
            '(clang-1300.0.29.30)]',
  'uname': uname_result(system='Darwin', node='ZhengrongnoMac-mini.local', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3', 'SSE41'],
                      'not_found': ['POPCNT',
                                    'SSE42',
                                    'AVX',
                                    'F16C',
                                    'FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Core2',
  'filepath': '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 2,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None

### Context for the issue:

I am not sure if this warning will affect my program result in future, it never untill now. I want to not see them, I tried to use code `warnings.filterwarnings("ignore", message="RuntimeWarning: invalid value encountered in exp2")`, but it doesn't work, I still can view this waring. What can I do?

**Comment by ngoldbaum** [comment]
How did you install python? How did you install numpy into your python environment (e.g. from pip? some other way?)

**Comment by ngoldbaum** [comment]
I also see this is an intel mac. I don't see this behavior on my ARM mac running Sonoma, installing numpy from the wheel and python from pyenv. I don't have an intel mac available to test on the reporter's arch.

**Comment by mikezang** [comment]
> How did you install python? How did you install numpy into your python environment (e.g. from pip? some other way?)

I install python from [Python Releases for macOS](https://www.python.org/ftp/python/3.11.7/python-3.11.7-macos11.pkg), and use `pip install numpy` to install numpy.

**Comment by ngoldbaum** [comment]
Hmm, could be a SIMD issue on the old CPU. @seiko2plus do you have any insight?

**Comment by ngoldbaum** [comment]
Oh also how did you install sonoma on such an old mac? That might also be confusing logic in the CPU detection that assumes a baseline configuration.

**Comment by mikezang** [comment]
I used [OpenCore Legacy Patcher](https://github.com/dortania/OpenCore-Legacy-Patcher), they support old mac mini until Mac mini (Early 2009).

**Comment by mattip** [comment]
You are not using `warning.filter` correctly, it should be
```
warnings.filterwarnings("ignore", message="invalid value encountered in exp2")
```

It would be nice to get to the source of why this happens, but unfortunately I think using modern macos on 10 year old hardware is a pretty niche case. The way to approach this would be to try to figure out how/why `exp2(ld(-113))` is calling into a LAPACK library (which is producing that warning). I don't think that should be happening? Maybe the warning is coming from the underlying implementation of `exp2` on macos/bsd which somehow uses a LAPACK routine?

We do have a mechanism to replace error-prone math functions with our own better behaving ones (usually taken from the BSD math library), and I don't see that we have ever replaced `exp2` there. So my guess, like @ngoldbaum says, it might be a bad interaction of an older CPU with a too-new OS math library.

If you go back to an older version of macos, does the problem go away?

**Comment by mikezang** [comment]
The warning is avoid when I moved `warnings.filterwarnings("ignore", message="invalid value encountered in exp2")` just below import lines, now I want to know how to avoid message `On entry to DLASCLS parameter number  4 had an illegal value`, I tied the same way as `Invalid...`, it doesn't work.

**Comment by ngoldbaum** [comment]
You're seeing errors that are being triggered by OpenBLAS, probably related to having a CPU older than what is currently supported by Apple.

**Comment by ngoldbaum** [comment]
Closing, I don’t think we can reasonably spend time fixing bugs for issues on hardware configurations that are unsupported by the vendor. Patches welcome (well assuming it wouldn’t add much maintenance burden) of course if you’d like to work on this but I doubt any of us will.
