### ISSUE TITLE
The scientific-python/numpy nightlies disappeared

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#25907]
https://anaconda.org/scientific-python-nightly-wheels/numpy is not accessible, and `numpy` seems to have disappeared from the list of packages at https://anaconda.org/scientific-python-nightly-wheels/repo.

Having a look at the recent activity on the https://github.com/scientific-python/upload-nightly-action, this is likely to be related to https://github.com/scientific-python/upload-nightly-action/pull/64. 

This will break CI jobs for anyone using NumPy nightlies, and is also pretty unfortunate timing given we're planning to branch 2.0.x in days.

I was a maintainer on the `numpy` package under the https://anaconda.org/scientific-python-nightly-wheels bucket, but now that it's gone I have no visibility into what happened.

Cc @matthewfeickert @jarrodmillman @tupui

**Comment by charris** [comment]
I'm surprised that the whole directory disappeared, that's pretty impressive.

**Comment by matthewfeickert** [comment]
@rgommers While indeed unfortunate, it looks like a `jq` parsing error triggered our expected cleanup conditions. In https://github.com/scientific-python/upload-nightly-action/pull/33 we remove any wheels that are older than 30 days from the index as [noted in the README](https://github.com/scientific-python/upload-nightly-action/blob/50053b39cfd4eda8a4046cab060998ea1f8b839e/README.md#artifact-cleanup-policy-at-the-scientific-python-nightly-wheels-channel)

> ## Artifact cleanup-policy at the ``scientific-python-nightly-wheels`` channel
> 
> To avoid hosting outdated development versions, as well as to clean up space, we do have a
default retention policy of:
> 
> - Latest **5 versions**
> - Artifacts newer than **30 days**
> 
> Any versions beyond these are automatically removed as part of a daily cron job run from this repository.
> Projects may have reasons to request to be added to the list exempt from this automated cleanup, however
> in that case the responsibility of cleaning-up old, unused versions fall back on the individual project.

Though from your logs (https://github.com/numpy/numpy/actions/runs/7946079298/job/21693439899#step:9:127) it seems like 2 weeks ago you uploaded wheels. 

Looking into last night's "remove old wheels" workflow it seems that a [`jq` parsing error of the upload date triggered the removal](https://github.com/scientific-python/upload-nightly-action/blob/50053b39cfd4eda8a4046cab060998ea1f8b839e/.github/workflows/remove-wheels.yml#L79-L85):

```
...
# package: numpy
jq: parse error: Invalid numeric literal at line 1, column 6
# scientific-python-nightly-wheels/numpy/2.0.0.dev0 last uploaded on 
# Removing scientific-python-nightly-wheels/numpy/2.0.0.dev0
Using Anaconda API: https://api.anaconda.org/
...
```

I'll open up a bug report. Though If you want to manually trigger a rebuild of the nightly wheels from `main` then these should be able to get uploaded without any issue. So please try that.

> Having a look at the recent activity on the https://github.com/scientific-python/upload-nightly-action, this is likely to be related to https://github.com/scientific-python/upload-nightly-action/pull/64.

NumPy doesn't use the uploader, but uses your own workflow,

https://github.com/numpy/numpy/blob/0b43a0e947010df48d075ca41df8680407b64243/.github/workflows/wheels.yml#L231-L248

https://github.com/numpy/numpy/blob/0b43a0e947010df48d075ca41df8680407b64243/tools/wheels/upload_wheels.sh#L34-L54

so these are unrelated.

**Comment by matthewfeickert** [comment]
> I'm surprised that the whole directory disappeared, that's pretty impressive.

This is also expected, given that there's only one version (`numpy-2.0.0.dev0`) getting uploaded, which overwrites the previous wheels. So if there's only one set of the wheels, and then those get removed, the project gets removed as well. c.f. https://github.com/Anaconda-Platform/anaconda-client/issues/702.

**Comment by charris** [comment]
> the project gets removed as well

That doesn't seem wise.

**Comment by matthewfeickert** [comment]
> That doesn't seem wise.

@charris We don't control how Anaconda Cloud works, so feel free to open up an Issue with them expressing that on https://github.com/Anaconda-Platform/anaconda-client/issues/

**Comment by rgommers** [comment]
Great, thanks for the quick fix @matthewfeickert!



> Please still trigger a wheel build and upload job on `main` in case I missed any.

Done, it is running now. I'll keep an eye on it and will verify if anything is missing before closing this issue.

**Comment by larsoner** [comment]
> Done, it is running now. I'll keep an eye on it and will verify if anything is missing before closing this issue.

@rgommers based on this it's there:
```
$ pip install --upgrade --force --index-url "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" scipy
Looking in indexes: https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
...
Successfully installed numpy-2.0.0.dev0 scipy-1.13.0.dev0
```
but:
```
$ python -c "import scipy.special"

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.
```
(Originally [seen in CIs](https://github.com/mne-tools/mne-python/actions/runs/8113857939/job/22178206441?pr=11234) but replicated locally.) Is it possible that SciPy's wheels were compiled against < 2.0 because the wheels weren't up on scientific-nightly, and thus a rebuild for those *also* needs to be triggered?

**Comment by matthewfeickert** [comment]
> Is it possible that SciPy's wheels were compiled against < 2.0 because the wheels weren't up on scientific-nightly, and thus a rebuild for those also needs to be triggered?

@larsoner Yes, given the upload date is post the nightly removal

![image](https://github.com/numpy/numpy/assets/5142394/ea340c42-3cd5-4254-b5ed-a78a9a01bc15)

So @rgommers probabably worth retriggering `scipy`'s wheel building and upload workflow given this.

**Comment by rgommers** [comment]
Yes, that makes sense. We really should set the lower bound on those nightlies to `>=2.0.0.dev0` in SciPy and other downstream project to prevent another such regression.

SciPy wheels are building now.

The NumPy aarch64/arm64 are still rebuilding on Cirrus CI. Once those are up too I'll trigger SciPy jobs for those as well.

**Comment by matthewfeickert** [comment]
Thanks @rgommers.

From what I can tell, Anaconda Cloud's web API failed to resolve (there have been a few other unrelated API failures with `api.anaconda.org` in the last week) and we didn't guard against invalid returns in the https://github.com/scientific-python/upload-nightly-action scheduled removal. This is fixed now in https://github.com/scientific-python/upload-nightly-action/pull/74 and so scheduled automated removals can't be done unless valid returns come back from Anaconda Cloud.

**Comment by rgommers** [comment]
> The NumPy aarch64/arm64 are still rebuilding on Cirrus CI.

Two of them failed, so nothing got uploaded unfortunately - due to https://github.com/numpy/numpy/issues/25464#issuecomment-1973806513.

**Comment by rgommers** [comment]
Okay, the rebuilds worked, all wheels are up now.

SciPy wheels are also failing, so need to fix those first and then re-run wheel builds once more.

**Comment by stefanv** [comment]
Thanks @rgommers for the incident report, and to @matthewfeickert for the quick response.
