### ISSUE TITLE
Can't import numpy via other libraries - module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'

### ISSUE THREAD

**Issue by devinbost** [numpy/numpy#25906]
### Steps to reproduce:

Create a new Google Colab notebook
Run `!pip install -qU pandas==1.5.3 scipy torch==2.1.0 numpy==1.26.4 implicit`

It should output:

```
Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Collecting numpy
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Installing collected packages: numpy
Successfully installed numpy-1.26.4
```
Run:
`from implicit.als import AlternatingLeastSquares`

I've run into this same exception when attempting to import several other libraries as well that use numpy, not just the `implicit` library.

### Error message:

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-10b22e354f54> in <cell line: 2>()
      1 # Imports
----> 2 from implicit.als import AlternatingLeastSquares
      3 from datetime import datetime
      4 from pathlib import Path
      5 

8 frames
/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py in <module>
     55 IS_PYSTON = hasattr(sys, "pyston_version_info")
     56 HAS_REFCOUNT = getattr(sys, 'getrefcount', None) is not None and not IS_PYSTON
---> 57 HAS_LAPACK64 = numpy.linalg._umath_linalg._ilp64
     58 
     59 _OLD_PROMOTION = lambda: np._get_promotion_state() == 'legacy'

AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'

```
```


### Additional information:

Using Python 3 with CPU runtime.
Python 3.10.12

**Comment by ngoldbaum** [comment]
Can you update the bug report to include the 8 frames you elided in the traceback?

**Comment by devinbost** [comment]
You can reproduce it in this notebook: https://github.com/pinecone-io/examples/blob/master/learn/recommendation/product-recommender/product_recommender.ipynb

**Comment by devinbost** [comment]
If the numpy version is pinned to `numpy==1.24.4`, then the issue doesn't occur.

**Comment by ngoldbaum** [comment]
It seems you're somehow importing an old version of the numpy C libraries, which does not have this attribute set. Numpy 1.26.4 should [always have this attribute set](https://github.com/numpy/numpy/commit/b59da2d3000c56cc00dbcbd7228e35e1c839297a) on this module. The code for this was added before numpy 1.26.2. I don't know enough about setting up python environments on google colab to advise further what's going wrong or how to fix this. I think this issue is unrelated to numpy though.

**Comment by rgommers** [comment]
This indeed looks like an install issue where a newer and an older numpy version somehow get mixed. I'd suggest creating a fresh environment from scratch and ensuring PYTHONPATH is not set @devinbost. 

It doesn't look like there's anything that needs to be addressed in numpy, so I'll close this issue as suggested by @ngoldbaum. Thanks both.
