### ISSUE TITLE
Color and font choice for typesetting inline code - drop the pink/red

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#25927]
After spending a fair bit of time staring at the 2.0.0 release notes, the use of the bright red/pink color and the too-large font for text that is typeset as inline code became really jarring. 

<img width="457" alt="image" src="https://github.com/numpy/numpy/assets/98330/9ad613ef-35c1-4869-849f-5aacd62e8004">

Compare with the [docs of pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io) itself:

<img width="469" alt="image" src="https://github.com/numpy/numpy/assets/98330/75906777-b1ba-453c-967c-a271f798fc34">

That is far more pleasant to read. The theme authors have spent a lot of time polishing these choices; our bright pink/red is a leftover from the initial theme (originally from Pandas).

**Proposal: switch color choices and font sizes to the theme defaults.**

**Comment by seberg** [comment]
The sphinx theme has been bumped on main, closing.
