### ISSUE TITLE
Need names and emails for some contributors to NumPy 2.0.0

### ISSUE THREAD

**Issue by charris** [numpy/numpy#25935]
NumPy 2.0.0 will be coming soon! If you want to be properly credited as a contributor, please please comment on this issue  with your preferred name and email.

- [ ] @pojaghi  (pojaghi)
- [x] @patient74  (patient74)
- [ ] @mykykh  (mykykh)
- [ ] @mcp292  (mcp292)
- [ ] @matoro  (matoro)
- [x] @maisevector  (maisevector)
- [x] @liang3zy22  (liang3zy22)
- [ ] @ellaella12  (ellaella12)
- [x] @eliegoudout  (eliegoudout)
- [x] @oliviermattelaer  (oliviermattelaer)
- [x] @andersonm-ibm  (andersonm-ibm)
- [x] @F3eQnxN3RriK  (Yuki K)
- [x] @stefan6419846  (Stefan) 
- [x] @TheHawz  (Pablo)
- [ ] @undermyumbrella1  (Kei)
- [ ] @Algorithmist-Girl  (Deepansha)
- [ ] @cbrt64  (Edward E)
- [x] @thalassemia  (thalassemia)
- [x] @djramones  (DJ Ramone)

Chuck

**Comment by F3eQnxN3RriK** [comment]
Name: Yuki K
Email: drsuaimqjgar@gmail.com

Thanks.

**Comment by eliegoudout** [comment]
Thanks 👍

Élie Goudout
eliegoudout@hotmail.com

**Comment by stefan6419846** [comment]
For me its `stefan6419846`. Regarding the e-mail address, see my GitHub profile.

**Comment by TheHawz** [comment]
Thanks!

Pablo
***@***.***

**Comment by maisevector** [comment]
Thanks! :)
Matthias Schaufelberger
schaufim@gmail.com

**Comment by djramones** [comment]
D.J. Ramones
`dj` {at} `reversedelay.net`

Cheers 🎉

**Comment by souvlakeeb** [comment]
Link my GH.

**Comment by patient74** [comment]
Name: Yash Pethe
Email: yashpethe26@gmail.com

Thanks👍

**Comment by andersonm-ibm** [comment]
Maya Anderson
maya.anderson.ibm {at} gmail.com

Thanks!

**Comment by charris** [comment]
@TheHawz could you add a last name.

**Comment by TheHawz** [comment]
> @TheHawz could you add a last name.

Edited in the original message!

**Comment by liang3zy22** [comment]
Liang Yan
ckgppl_yan@sina.cn

Thanks.

**Comment by sharsha315** [comment]
Hi, is this issue still open. Please, can I have the opportunity to work on this issue.

**Comment by charris** [comment]
Thanks all.
