### ISSUE TITLE
Wheel build tests crashed on PyPy 39 macosx arm.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#25978]
Log at https://github.com/numpy/numpy/actions/runs/8216795820/job/22471760587?pr=25977. I'm going to ignore this for 2.0.0b1, but want there to be a record, so not rerunning.

**Comment by andyfaff** [comment]
We never actually built macosx_arm64 wheels for pypy, just macosx_x86_64. So when the Mac arm job moved to GHA the matrix started building them for pypy.  Given that historically we didn't build them we have a choice as to whether we want to start supporting them.

**Comment by mattip** [comment]
If they are problematic please skip them. With that, the failure is in macos arm64 sort, which may be another case of #25464

**Comment by andyfaff** [comment]
Skip the build entry, or skip the test?

**Comment by mattip** [comment]
Feel free to skip PyPy wheel building, if PyPy is a cause for extra effort or delay.

**Comment by rgommers** [comment]
+1 for skipping the build; this isn't good timing for adding an extra wheel with an apparently problematic configuration.
