### ISSUE TITLE
Action wheel builds do not happen when a tag is pushed.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#25979]
This turned up when building wheels for v2.0.0b1, I needed to trigger them manually. I assume this is because `push:` has been removed from `.github/workflows/wheels.yml`.

Another potential problem is that the commit has both a tag and `[wheel build]`. I also wonder why only use the first line of the commit when looking for `[wheel build]`. I note the `git log -1 --grep '\[wheel build\]'` will also find the directive.

**Comment by andyfaff** [comment]
Xref https://github.com/numpy/numpy/pull/24535

**Comment by andyfaff** [comment]
[here's](https://github.com/refnx/refnx/blob/c5282834a5055348af57755db6dda0ddef436d02/.github/workflows/release.yml#L6) how I run a build when a tag is pushed, for a personal project.

**Comment by charris** [comment]
Even after #24535 there are a ton of 15 second runs of the wheel builder action, it doesn't seem to have bought much. @rgommers.

**Comment by rgommers** [comment]
> Even after #24535 there are a ton of 15 second runs of the wheel builder action, it doesn't seem to have bought much. @rgommers.

That is not the case. There are way fewer triggers on this repo, and almost none on forks - it is now possible to find the actual runs on the first page of the action. And the email notifications went away completely. There are still some triggers on this repo, but that didn't seem avoidable given the setup.

**Comment by rgommers** [comment]
> It would also help if manually running builds in a maintenance branch uploaded to staging.

Good point. That requires some extra config. I just learned that it's possible to add options to manual triggers; https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs. Perhaps choosing nighty vs. staging manually is useful?
