### ISSUE TITLE
BUG: Flexible array member warning in C++ using 2.0.0b1 headers

### ISSUE THREAD

**Issue by karlotness** [numpy/numpy#26013]
### Describe the issue:

Thanks for all the work on NumPy 2.0. I have just run a few tests using 2.0.0b1 on a C++ extension that uses the NumPy array API and everything seems to build quite smoothly. 

I do get a new warning from `PyArrayMultiIterObject` (which I actually don't use) relating to its new use of a flexible array member [at the end of the struct](https://github.com/numpy/numpy/blob/acef1f61428288f2bbb75dc9e97fc016762c0084/numpy/_core/include/numpy/ndarraytypes.h#L1304) reporting that these aren't supported in ISO C++.

Granted, this is a warning from GCC's `-Wpedantic` and so is particularly picky, but the public headers for the 1.x versions did build in C++ even with these turned on. I took a quick glance and it looks like this might be the only flexible array member in public headers. I haven't dug in to the context around the change but I wanted to report this since it is the only warning I see. Thanks again!

### Reproduce the code example:

```python
// Could compile an empty C++ extension (for example, the below just including headers)
// set -Wpedantic with GCC

#define NPY_NO_DEPRECATED_API NPY_2_0_API_VERSION
#define NPY_TARGET_VERSION NPY_2_0_API_VERSION

#include <Python.h>
#include <numpy/arrayobject.h>
```

### Error message:

```shell
venv/lib/python3.12/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1304:31: warning: ISO C++ forbids flexible array member 'iters' [-Wpedantic]
```

### Python and NumPy Versions:

NumPy 2.0.0b1
Python 3.12.0

### Context for the issue:

Leads to added warnings when building as C++ and relies on compiler extensions

**Comment by mattip** [comment]
This is the offending construct https://github.com/numpy/numpy/blob/9de8a809efa4c8193a168af9191a0c69290db3e4/numpy/_core/include/numpy/ndarraytypes.h#L1304

One solution would be to change the struct. Another would be to make this an opaque struct, and not expose its internals.

**Comment by seberg** [comment]
Maybe we need to lie and use 32 or 64 always at least on C++?  We have public macros that access these and I didn't feel like forcing everyone to change these iteration pattrns this time around.
Of course one can change the macros together with it and then the field being gone isn't so bad.

**Comment by mattip** [comment]
Ahh, I see. There are macros that use `_PyMIT` to access the struct internals, and some of those access `_PyMIT(multi)->iters`. If you go back to using `NPY_MAXARGS`, which is version dependent, would that be so terrible? I think all the casts would just work, no?

**Comment by seberg** [comment]
Yeah, I don't think it would be a big deal, it's a small lie one way or another, but one that really should not matter in practice.
