### ISSUE TITLE
Handle warning about private API and pybind11 before 2.0.0rc1

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#26010]
In 2.0.0b1 we still have a very verbose and scary-looking warning like this:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.
...
pybind11 note: You may see this message if using pybind11,
this is not problematic at pre-release time
it indicates the need for a new pybind11 release.
```

Full warning:

<details>

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.

If you are a user of the module, the easiest solution will be to
either downgrade NumPy or update the failing module (if available).

NOTE: When testing against pre-release versions of NumPy 2.0
or building nightly wheels for it, it is necessary to ensure
the NumPy pre-release is used at build time.
The main way to ensure this is using no build isolation
and installing dependencies manually with NumPy.
For cibuildwheel for example, this may be achieved by using
the flag to pip:
    CIBW_BUILD_FRONTEND: pip; args: --no-build-isolation
installing NumPy with:
    pip install --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
in the `CIBW_BEFORE_BUILD` step.  Please compare with the
solutions e.g. in astropy or matplotlib for how to make this
conditional for nightly wheel builds using expressions.
If you do not worry about using pre-releases of all
dependencies, you can also use `--pre --extra-index-url` in the
build frontend (instead of build isolation).
This will become unnecessary as soon as NumPy 2.0 is released.

If your dependencies have the issue, check whether they
have nightly wheels build against NumPy 2.0.

pybind11 note: You may see this message if using pybind11,
this is not problematic at pre-release time
it indicates the need for a new pybind11 release.

```

</details>

We need to finalize this before `2.0.0rc1` in one of two ways:
1. Turn the warning into a hard error,
2. Silence the warning.

At https://github.com/numpy/numpy/issues/25918#issuecomment-1987316018 we discussed a bit. @seberg said:
_"That huge warning is seems only semi-useful, it would be nice to make it a hard error by the time we release, otherwise we don't protect users from potentially bad results/crashes due to a module that wasn't recompiled. I don't care much about `rc1` specifically it just seems like a plausible/reasonable warning shot for pybind11."_

I said: _"Well, it must be done either before `rc1` or not at all. The way it looks now, it actually seems fairly safe to disable the warning, leaving the compat shim in place for 2.0, and make it a hard error on `main` in a month or so. Probably best to wait and see how a `pybind11` release is coming along, and decide in a week or so?"_

The outcome will depend on https://github.com/pybind/pybind11/issues/5009. If `pybind11` manages to get a release out soon enough, we may be able to turn the warning into an error. If not, then it'll be too disruptive to do so.

**Comment by seberg** [comment]
I am not sure I can agree that silencing the warning is an option.  Remember that without the fixes at least in some parts, SciPy would have just returned incorrect results.
I can accept keeping the warning for `pybind11`s sake, but it seems to me users must have a fighting chance to know that why they may be seeing random nonsense or crashes.

**Comment by charris** [comment]
We are about ready for 2.0.0rc1.

**Comment by rgommers** [comment]
This issue is blocking, it needs to be resolved first on the `pybind11` side (very close to done).

**Comment by mattip** [comment]
Is there a tracking issue we can follow to see the progress?

**Comment by neutrinoceros** [comment]
I assume @rgommers was talking about https://github.com/pybind/pybind11/pull/5050

**Comment by henryiii** [comment]
One team member has said they would review, and we are waiting on that review. Hopefully very soon.

**Comment by henryiii** [comment]
pybind11 2.12 is out!

**Comment by rgommers** [comment]
Awesome, thanks a lot @henryiii!
