### ISSUE TITLE
DOC: Mention `np.lib.NumPyVersion()` in the migration guide

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#26031]
Some users will have to do conditional imports, SciPy uses `np.lib.NumPyVersion(np.__version__) > "2.0.0"` which seems like a decent pattern.

I think we should mention this pattern as one possible way to do things in the migration guide.

**Comment by rgommers** [comment]
Good idea - except things will work a bit smoother over the next 1-2 months if it's `>= "2.0.0b1"`.

**Comment by sharsha315** [comment]
Hello, is this issue open. I would like to work on this issue.

**Comment by rgommers** [comment]
Thanks for the offer @sharsha315, but please pick an issue that is not labelled with the 2.0.0 milestone.

**Comment by sharsha315** [comment]
Thanks for the information @rgommers.
