### ISSUE TITLE
BUG: Revert removal of `PyArray_TypeNumFromName` C-API

### ISSUE THREAD

**Issue by duburcqa** [numpy/numpy#26030]
### Describe the issue:

The C-API method `PyArray_TypeNumFromName`  has been removed in Numpy 2.0.0 with the argument in [commit message](https://github.com/seberg/numpy/blob/dde15a6320df672a40b3cfd0659de8fae7496cbc/numpy/_core/src/multiarray/arrayobject.c) that no library in the real world was relying on it in C. This statement turns out to be a wrong actually. [eigenpy](https://github.com/stack-of-tasks/eigenpy) is relying on it to expose custom types, which is a critical feature of this library. [Here](https://github.com/stack-of-tasks/eigenpy/issues/447) is the issue tracking the whole story of the compatibility with Numpy. To wrap up, there is a workaround for all other issues except this one.

### Reproduce the code example:

```python
NA
```

### Python and NumPy Versions:

NA

**Comment by seberg** [comment]
True, and I could be convinced to not do this, but this isn't your use very much the same as:
```
PyArray_Descr *descr = PyArray_DescrNew(type);
if (descr == NULL) {
    return -1;
}
int code = descr->type_num;
Py_DECREF(descr);
return code;
```
The function seems to exist with the idea that you add specific name and a 3rd party wants to find it (without doing so via C).

**Comment by duburcqa** [comment]
[Here](https://github.com/stack-of-tasks/eigenpy/blob/458c0e195253568a20b4ed1342cd4df28e2373a2/src/numpy.cpp#L16C1-L18C2) is the piece of code that relies on it:
```c
int PyArray_TypeNum(PyTypeObject* type) {
  return PyArray_TypeNumFromName(const_cast<char*>(type->tp_name));
}
```

At this point, there is no access to the `PyArray_Descr` associated with the type. So it sounds like to typically usecase of `PyArray_TypeNumFromName`. Am I wrong ? The library could probably be refactored to keep track of `PyArray_Descr` mapping by itself, but it may be a significant rework.

**Comment by seberg** [comment]
> At this point, there is no access to the PyArray_Descr associated with the type

But I don't really think comparing names of all dtypes is better anyway?  Btw. I meant to say use `PyArray_DescrFromTypeObject` there.  Oddly enough, that function seems not actually documented, though.  But that seems your intention to begin with.

(That function does slightly more, but it seems to be a better match for what you want to begin with, i.e. for where `PyArray_TypeNum` is used.  It searches both builtin and registered ones.)

**Comment by duburcqa** [comment]
Ah amazing ! I will try that :)

**Comment by duburcqa** [comment]
It works like a charm :) I suggest documenting the method you suggested so that it does not get removed anytime soon !
