### ISSUE TITLE
DOC: lack of doc for `numpy.multiply.outer` 

### ISSUE THREAD

**Issue by reallsx** [numpy/numpy#26043]
### Issue with current documentation:

There is no documentation for `numpy.multiply.outer` on the NumPy documentation website. I tried multiple search engines and searched on the website directly as well.

`numpy.multiply.outer` has a docstring and is mentioned in documentation for [numpy.outer](https://numpy.org/devdocs/reference/generated/numpy.outer.html) and [numpy.ufunc.outer](https://numpy.org/devdocs/reference/generated/numpy.ufunc.outer.html). I was expecting to find documentation on the NumPy documentation website but seems like the documentation for this function is not generated?

### Idea or request for content:

Add documentation.

**Comment by sharsha315** [comment]
Hello, is this issue still open. Can I have the opportunity to work on this issue?

**Comment by reallsx** [comment]
Thanks for the reply! It seems like I was confused about the usage of `ufunc`. Now it make sense to me, but I think there might be space for improvement for the documentation so that others can understand it by just searching `numpy.multiply.outere`
