### ISSUE TITLE
DOC: Inaccessible contrast for a:visited links in admonitions

### ISSUE THREAD

**Issue by hugovk** [numpy/numpy#26058]
### Issue with current documentation:

1. Visit https://numpy.org/neps/nep-0029-deprecation_policy.html
2. If you've not visited the link "SPEC 0 — Minimum Supported Versions" before, it looks like:

<img width="747" alt="image" src="https://github.com/numpy/numpy/assets/1324225/7fd0d136-69fc-447b-9573-dbda945c18c4">

3. Click the link "SPEC 0 — Minimum Supported Versions"
4. Return to https://numpy.org/neps/nep-0029-deprecation_policy.html
5. It looks like:

<img width="741" alt="image" src="https://github.com/numpy/numpy/assets/1324225/cb41d42e-9557-487d-8369-2e8ff82744c8">

The contrast of purple on the dark background is low: it's ratio is 1.51, below the WCAG AA level of 4.5:

<img width="235" alt="image" src="https://github.com/numpy/numpy/assets/1324225/c96a6f11-e869-4d66-b73d-7c1ba36a5602">

This comes from [`basic.css`](https://numpy.org/neps/_static/basic.css), which I think is from Sphinx:

```css
a:visited {
    color: #551A8B;
}
```

If I disable the rule, it looks like this, with a good ratio of 5.37:

<img width="733" alt="image" src="https://github.com/numpy/numpy/assets/1324225/528908b6-2052-4be0-9b80-adc810eb48eb">

The docs use PyData Sphinx Theme 0.13.3, but I can't reproduce the problem with these links (and inspecting the elements to edit in a link):

* https://pydata-sphinx-theme.readthedocs.io/en/v0.13.3/examples/kitchen-sink/admonitions.html
* https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/kitchen-sink/admonitions.html (0.15.2)

**Comment by melissawm** [comment]
Related: https://github.com/scientific-python/scientific-python-hugo-theme/issues/457

**Comment by trallard** [comment]
This is fixed in the most recent versions of the theme (with the updated colour palette). So once the pin on 0.13 is removed this should no longer be a problem. 

It's also related to https://github.com/numpy/numpy/issues/25927

**Comment by mattip** [comment]
The pin is here. Should we pin to a newer version? Which one?
https://github.com/numpy/numpy/blob/529fd40bdd44a551d78584d04b4f6cbe2fd9f2b2/requirements/doc_requirements.txt#L4

**Comment by trallard** [comment]
Bringing this issue also to this conversation as it would be good to ensure both the colour and font issues mentioned in https://github.com/numpy/numpy/issues/25927 are addressed.
