### ISSUE TITLE
DOC: docstrings for np.int_, np.uint, np.long, np.ulong are incorrect on NumPy2

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#26057]
The rendered docs for [np.int_](https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.int_) state `Default signed integer type, 64bit on 64bit systems and 32bit on 32bit systems.` This is wrong, it is 64-bits everywhere. The docstring for `np.long`, is now `alias of int_` but should be the platform-dependent docstring from `int_`.

The same confusion exists for the docstring of `uint` (is now always 64-bit) and `ulong` (platform dependent).

Also, on windows with python 3.11.4, it doesn't seem like the scalar docstrings are getting assigned for `np.int32` (`np.long` is aliased to `np.int32`).

**Comment by rgommers** [comment]
> This is wrong, it is 64-bits everywhere. 

That does not sound correct. It only changed to 64-bit for 64-bit Windows, not for 32-bit platforms. See https://numpy.org/devdocs/numpy_2_0_migration_guide.html#migration-windows-int64

**Comment by mattip** [comment]
> It only changed to 64-bit for 64-bit Windows, not for 32-bit platforms

Ahh, right. Sorry for the noise. Closing.
