### ISSUE TITLE
BUG: `beta` random generator can output exact zeros

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#26054]
### Describe the issue:

The PDF for the Beta distribution is exactly zero for the extreme values 0 and 1. Hence, a random number generator that samples from it should not sample points where the probability mass is zero - i.e. it should be bounded in the **open** interval `(0,1)`.

As a comparison, R's `rbeta` will never output exact zeros, but in some cases in can output exact ones, which perhaps _could_ be reasonable given that numerical precision close to 1 is more limited than close to zero:
```r
set.seed(123)
x = rbeta(1e6, shape1=0.010582142677289599, shape2=0.21254801747114022)
sum((x == 0) | (x == 1))
```
```
20
```

Numpy OTOH will output exact zeros with a non-negligible probability if the parameters are small:

### Reproduce the code example:

```python
import numpy as np
rng = np.random.default_rng(seed=123)
x = rng.beta(0.010582142677289599, 0.21254801747114022, size=int(1e6))
np.sum(x == 0), np.sum(x == 1)
```

### Error message:

```shell
(387, 13)
```
```


### Python and NumPy Versions:

1.26.1
3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]

### Runtime Environment:

[{'numpy_version': '1.26.1',
  'python': '3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='debian', release='6.1.0-18-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01)', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/david/anaconda3/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None

### Context for the issue:

_No response_

**Comment by eendebakpt** [comment]
Does the value of the beta distribution of the pdf not depend on the values of alpha and beta? In particular for the values provided the pdf is non-zero at 0 and 1.

```
from scipy.stats import beta as beta_dist
import matplotlib.pyplot as plt
x=np.linspace(0, 1, 1000)
plt.figure(10);plt.clf()

alpha, beta=0.010582142677289599, 0.21254801747114022
p=beta_dist.pdf(x, alpha, beta)
plt.plot(x, p, label=f'{alpha=} {beta=}')

alpha, beta=0.5, 0.5
p=beta_dist.pdf(x, alpha, beta)
plt.plot(x, p, label=f'{alpha=} {beta=}')

alpha, beta=2, 2 
p=beta_dist.pdf(x, alpha, beta)
plt.plot(x, p, label=f'{alpha=} {beta=}')
plt.legend()
```
![image](https://github.com/numpy/numpy/assets/883786/5a5f87e8-e9e7-4fbc-90de-cf43049c5a39)

**Comment by david-cortes** [comment]
Per [wikipedia](https://en.wikipedia.org/wiki/Beta_distribution), the PDF of the beta distribution is as follows:
$P(x|\alpha,\beta) = \frac{1}{B(\alpha, \beta)} x^{\alpha-1}(1-x)^{\beta - 1}$

with $B(\alpha, \beta) = \frac{\Gamma(\alpha) \Gamma(\beta)}{\Gamma(\alpha + \beta)}$

If $x=0$, the PDF will involve powers of zero, which will be either inifite (for $\alpha<1$), one (for $\alpha=1$), or zero (for $\alpha>1$).

If the distribution were to be defined in such a way that zeros are allowed, then it means a random sampler would only ever choose zeros when $\alpha<1$, which is not one's idea of a beta distribution, and not what numpy is outputting.

**Comment by eendebakpt** [comment]
Numpy can only output floating point numbers. If numpy would sample perfectly, and then convert those samples to floating point I would expect zeros both for $\alpha < 1$ and $\alpha > 1$.

The implementation of the beta distribution sampler is here https://github.com/numpy/numpy/blob/7f1c8cbe0c6fa4e554b3b1e4d7dc2f03fababbec/numpy/random/src/distributions/distributions.c#L411. The algorithm is not perfect (also see https://github.com/numpy/numpy/issues/688), but it does seem to give a reasonable sampling. 

A test to compare the CDF from a large sample with the true CDF
```
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta as beta_dist

rng = np.random.default_rng(seed=123)
alpha, beta = 0.010582142677289599, 0.21254801747114022

samples = rng.beta(alpha, beta, size=int(100e6))

# from samples determine a CDF
count, bins_count = np.histogram(samples, bins=np.linspace(0, 1., 1500)) 
sampled_pdf = count / sum(count) 
sampled_cdf = np.cumsum(sampled_pdf)   

# calculate the CDF 
centres  = ( bins_count[1:]+bins_count[:-1])/2
p=beta_dist.cdf(centres, alpha, beta)

# plot results
plt.figure(10); plt.clf()
plt.plot(centres, sampled_cdf, label="CDF from samples") 
plt.plot(centres, p, '-',  label=f'CDF {alpha=} {beta=}')
plt.legend() 

plt.figure(20); plt.clf()
plt.plot(centres, p - sampled_cdf, '.',  label="delta") 
plt.ylabel('Delta between CDF and sampled CDF') 
```
Results in
![image](https://github.com/numpy/numpy/assets/883786/bedf330f-d5ec-49b0-aa03-e88ac977fcd7)

So indeed the density of very small samples (including zero) is a bit high.

**Comment by rkern** [comment]
Not all infinities are the same. These singularities are not Dirac deltas. In the realm of pure real numbers, the probability _mass_ of any real number (like 0, 0.5, or 1) from a distribution without Dirac deltas is 0 (as the set of a single real number has measure 0). The only things that have nonzero probability mass are intervals, and there is no step-like behavior at 0 or 1. The CDF just has infinite slope exactly on 0, but the CDF doesn't jump up discontinuously as it would with a Dirac delta.

FWIW, this graph is plotting the wrong thing. The empirical CDF from the histogram approximates the true CDF evaluated at the _right_ edge of each bin, not the CDF evaluated at the center. `p = beta_dist.cdf(bins_count[1:], alpha, beta)`. The resulting residual plot looks much nicer.

![image](https://github.com/numpy/numpy/assets/46135/c5f105b3-99ed-4a5d-ae91-8f0fe17cfbc5)

Finite floating point implementations of probability distributions are always approximations. The floating point number that you get out at the end does not really represent the actual real number that has the same value. It's more fuzzy than that. I'd love to say that it represents some interval _around_ the real number with the same value, but that's not actually achievable in practice with practical implementations of nontrivial nonuniform distributions. But it's close to being true. The probability of getting the floating point value of `0.0` from `rng.beta(a, b)` does not represent the probability of getting real number 0 from $B(\alpha, \beta)$ (which is, of course 0). It's closer to the probability of getting a real number in the interval $[0, \epsilon]$ for some $\epsilon$ (sadly, not `np.finfo(float).eps`, but any means). And that's a finite, well-behaved value even if you keep that interval bounded or unbounded.

**Comment by david-cortes** [comment]
While it _might_ be the case that floating points of exactly zero are sometimes the correct answer given that they cannot represent every real number (even if overrepresented in this particular example), in practice one of the usages of random number generators is to pass aggregations of the results to statistical functionalities like PDF / CDF / other generators / etc.; for which values of zero in the specific case of a beta distribution are rather problematic.

**Comment by rkern** [comment]
0 and 1 are quite valid outputs of a (real, ideal) beta distribution (the CDF is perfectly well-defined and continuous on the boundary of the interval as well as the interior). If specific downstream applications have extra requirements, they can apply them as needed.

**Comment by mdhaber** [comment]
Looks like the issue has been addressed: the beta distribution can be defined to include 0 and/or 1 in the support, even if the the PDF is infinite at these points, and in this case NumPy Is not wrong to include 0s and/or 1s in random samples. I'm not seeing something to fix, and the conversation has not been active for a while, so I'll go ahead and close. Thanks all.
