### ISSUE TITLE
MAINT: maintenance/2.0.x branch binary compat issue on SciPy main

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#26060]
SciPy was planning to release `1.13.0` with NumPy `1.22.4` as our lowest supported runtime bound, and this was looking possible/feasible with the NumPy `2.0.0b1` release tag testing. However, as reported in https://github.com/scipy/scipy/issues/20268, our pre-release CI started catching a failure in binary compatibility at runtime after downgrading to `1.22.4` at test/runtime.

While that may not matter too much if it were a `2.1.0` change specific to NumPy `main`, I was able to reproduce on `maintenance/2.0.x` branch, and so bisected the `1.22.4` runtime incompatibility of that branch for SciPy to the commit below. Basically I'm wondering if you're going to need us to bump our minimum NumPy runtime bound, carry updates to our compat shims, or if this is likely to get shimmed in NumPy proper prior to RC1?

```
5f4dfa98afd62026cdc7b176a398647f8a3835b5 is the first bad commit
commit 5f4dfa98afd62026cdc7b176a398647f8a3835b5
Author: Nathan Goldbaum <nathan.goldbaum@gmail.com>
Date:   Wed Mar 13 14:24:19 2024 -0600

    MAINT: avoid use of flexible array member in public header

 numpy/_core/include/numpy/ndarraytypes.h | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)
```

For diagnostic purposes (probably not the right fix), this seems to alleviate the binary compat problem:

```diff
--- a/numpy/_core/include/numpy/ndarraytypes.h
+++ b/numpy/_core/include/numpy/ndarraytypes.h
@@ -1298,7 +1298,7 @@ typedef struct {
          * growing structs (as of Cython 3.0.6).  It also allows NPY_MAXARGS
          * to be runtime dependent.
          */
-#if (defined(NPY_INTERNAL_BUILD) && NPY_INTERNAL_BUILD) || defined(__cplusplus)
+#if (defined(NPY_INTERNAL_BUILD) && NPY_INTERNAL_BUILD)
         /* 64 is NPY_MAXARGS for numpy 2.0 or newer. We can't use a flexible
            array member in C++ so use the internal size there. */
         PyArrayIterObject    *iters[64];
```

**Comment by tylerjereddy** [comment]
I think my preference here is for NumPy to back it out and let the C++ folks swallow a pedantic compiler warning, unless there's an actual danger of a real segfault/bug for C++ consumers, but I haven't seen that clearly described yet.

**Comment by ngoldbaum** [comment]
Rather than backing it out, another way to handle this is to define NPY_MAXARGS in a version-dependent manner properly and put it somewhere visible to `ndarraytypes.h` and just use that.

I think c++ code starts to run into issues if someone allocates a subtype with `new`, I have no idea how likely that is in practice.

**Comment by tylerjereddy** [comment]
`scipy/_build_utils/src/npy_2_compat.h` already has shims for `NPY_MAXARGS`, should we really be adding shims on top of the vendored compat shims? Maybe that header needs to be included more broadly after your patch, though that seems like a fair bit of last-minute fallout.

**Comment by ngoldbaum** [comment]
I’m saying that define shouldn’t be in the compat header and should be available to define this since it’s in a publicly exposed struct. That’s just my opinion though, I’d wait to hear what @seberg thinks.

**Comment by seberg** [comment]
Arg, Cython is a problem, right.  I do not think you can use new in C++ for a Python object.  Short of just doing something special for Cython setting it to 32 seems easier to to me.

**Comment by seberg** [comment]
I triggered the nightly build for non-cirrus at least, so hopefully this should go away.
