### ISSUE TITLE
Fate of `numpy.version` in 2.0

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#26072]
While looking at the [reference](https://github.com/numpy/numpy/blob/main/numpy/tests/test_public_api.py) (effectively) for numpy's public API, I noticed:
https://github.com/numpy/numpy/blob/6059db15f06555b246f3743db3152050b50722b1/numpy/tests/test_public_api.py#L141

I haven't followed the finalization of 2.0 closely, so apologies if this is superfluous, but I thought I'd flag it. It wasn't mentioned in https://github.com/numpy/numpy/issues/25918 for example.

CC @rgommers @charris @seberg

**Comment by seberg** [comment]
I'll vote for not doing anything, the sum of all changes is already large when it comes to spending downstream annoyance chips.

**Comment by rgommers** [comment]
I agree with not doing anything. It was a minor cleanup opportunity, but the window for regular API changes for 2.0 has closed. We've asked downstream projects to do their RC1 and hopefully have our own RC1 out later this week.

I see a few more minor inaccuracies in that test, I'll open a PR to fix this comment and those other things.
