### ISSUE TITLE
DOC: confusing documentation for Python level `np.intp` and C-level `npy_intp`

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#26092]
### Issue with current documentation:

In #24888 the `npy_intp` type was updated to alias `Py_ssize_t` (instead of `intptr_t` as previously). Its documentation was updated accordingly:

https://github.com/numpy/numpy/blob/56dab5053eedbd0a34b8c5aa8bf66c46a8b15cb5/doc/source/reference/c-api/dtype.rst?plain=1#L387-L398

However, in the same file, the `NPY_INTP` enumerated type still refers to the equivalence with `intptr_t` (size of `void*`):

https://github.com/numpy/numpy/blob/56dab5053eedbd0a34b8c5aa8bf66c46a8b15cb5/doc/source/reference/c-api/dtype.rst?plain=1#L171-L175

followed by:

https://github.com/numpy/numpy/blob/56dab5053eedbd0a34b8c5aa8bf66c46a8b15cb5/doc/source/reference/c-api/dtype.rst?plain=1#L290-L296

Furthermore, the documentation for the Python-level dtype with matching name `np.intp` also refers to equivalence with `intptr_t`:

https://github.com/numpy/numpy/blob/56dab5053eedbd0a34b8c5aa8bf66c46a8b15cb5/doc/source/reference/arrays.scalars.rst?plain=1#L376-L384

### Idea or request for content:

So I am confused:

- are the documentation sections paragraph for the enumeration value and Python-level dtype object up to date?
- if so, I think it would be important to add a note to make the type discrepancy explicit (while explaining that this should not be a problem to confused `Py_ssize_t` with `intptr_t` on most platforms).
- if this not intended (that is, if the Python dtype and the enumeration value are now all aligned on `Py_ssize_t`/`npy_intp`), then those paragraphs should be updated.

Note: the documentation of `npy_uintp` `np.uintp` would deserve a similar clarification.

**Comment by ngoldbaum** [comment]
We talked about this at the triage meeting and were left a little confused. Are there systems we support where `Py_ssize_t` isn't the same size as `intptr_t`?

We can add some notes where we talk about how it's the same size as a pointer that this isn't strictly true according to the C standard.

**Comment by lorentzenchr** [comment]
I would expect that the documentation follows the code, i.e., if `np.intp` is defined as `Py_ssize_t` then say so regardless of the fact that on most platforms ist‘s the same as `intptr_t`.
Looking at https://github.com/numpy/numpy/blob/c3f091d403e0becda4887b2600df89b98f08473b/numpy/_core/include/numpy/npy_common.h#L201 this seems the case.

My guess is that this part of the doc was just not updated with the change to Py_ssize_t.

**Comment by seberg** [comment]
Yes, its the same type, I added `p` for pointer, not that it matters on any typical hardware.

**Comment by seberg** [comment]
gh-26241 hopefully clarifies things.  (I actually didn't add `p`, `p` always existed, I added `n` so that `p` can keep its meaning.)

**Comment by lorentzenchr** [comment]
@seberg Thanks for clarification in the docs.
