### ISSUE TITLE
DOC: undocumented behavior for converting month timedelta64 to days

### ISSUE THREAD

**Issue by zazaho** [numpy/numpy#26121]
### Issue with current documentation:

I have three syntaxes that attempt to convert a timedelta64 in month into days. As is well explained in the documentation:
https://numpy.org/doc/stable/reference/arrays.datetime.html#arrays-datetime
this is not possible because we  do not know how many days a month holds:

`np.timedelta64(1, 'M') / np.timedelta64(1, 'D')`
`Cannot get a common metadata divisor for Numpy datetime metadata [M] and [D] because they have incompatible nonlinear base time units.`

`timedelta64(timedelta64(1, 'M'), 'D')`
`Cannot cast NumPy timedelta64 scalar from metadata [M] to [D] according to the rule 'same_kind'`

but this yields:

`timedelta64(1, 'M').astype(timedelta64(1, 'D'))`
`numpy.timedelta64(30,'D')`

I am surprised that there is no error in the latter case but I am mostly interested to find out which rules are used to determine 30 in this case. For example:

`timedelta64(3, 'M').astype(timedelta64(1, 'D'))`
`numpy.timedelta64(91,'D')`

which indicates to me that there is some kind of heuristics used but I have not been able to find its documentation.

Thank you for your help,

Sacha

**Comment by ngoldbaum** [comment]
> I am surprised that there is no error in the latter case

This is happening because numpy defaults to "unsafe" casting in `astype`:

```
>>> np.timedelta64(1, 'M').astype(np.timedelta64(1, 'D'))
np.timedelta64(30,'D')
>>> np.timedelta64(1, 'M').astype(np.timedelta64(1, 'D'), casting='safe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast scalar from dtype('<m8[M]') to dtype('<m8[D]') according to the rule 'safe'
```

> which indicates to me that there is some kind of heuristics used but I have not been able to find its documentation.

According to the source code, this is the correct result averaged over a 400 year leap-year cycle:

https://github.com/numpy/numpy/blame/34fa608064fb2ff825d32f536ad420cf8cee3112/numpy/_core/src/multiarray/datetime.c#L1093-L1096

A PR documenting these rules and adding them to the documentation would be very welcome.

**Comment by sharsha315** [comment]
Hi, is this issue still open. Please, can I have the opportunity to work on this issue.

**Comment by ngoldbaum** [comment]
We don’t claim issues in numpy, please go ahead, in the future just check if anyone already has a PR open for an issue

**Comment by ajayjanapareddi** [comment]
Hi @ngoldbaum , 
Could you kindly review my first PR on numpy. Apologies if there are any mistakes.
