### ISSUE TITLE
BUG: creating an array that shares memory with a stringdtype array can fail

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#26140]
The following test case will fail on `main`:

```
import numpy as np
# strings long enough to live in the arena
string_list = ["abc", "def", "ghi" * 10, "A¢☃€ 😊" * 100, "Abc" * 1000, "DEF"]
arr = np.array(string_list, dtype=np.dtypes.StringDType())
arr_rev = np.array(string_list[::-1], dtype=np.dtypes.StringDType())

arr_view = np.array(arr, copy=None, dtype=arr_rev.dtype)
np.testing.assert_array_equal(arr, arr_view)
```

This is happening because of the code path here:

https://github.com/numpy/numpy/blob/6d4a0f74e89ac4a015742be896e99142a78c5a10/numpy/_core/src/multiarray/multiarraymodule.c#L1612-L1636

In the test case, `oldtype != dtype`, so we enter the path that calls `NewFromDescrAndBase` with the user-provided dtype. The problem is the user-provided dtype doesn't know anything about the arena that lives on the original dtype, so blindly accepting the user-provided dtype and passing it to `NewFromDescrAndBase` corrupts the arena.

I think a way to fix this would be to call `finalize_descr` on the user-provided DType to get a fresh descriptor if its already owned by the array, and then force the user-provided dtype to share allocators with the original dtype. We could also copy the arena, but that goes against the user desire to not have a copy.

Another way to handle this is to make stringdtype *always* copy in this situation, and error if someone passes `copy=False`. 

_Originally posted by @ngoldbaum in https://github.com/numpy/numpy/issues/26082#issuecomment-2021391412_

**Comment by seberg** [comment]
Maybe we need a more exact check than equiv dtypes? In fact, I think we do: they are equiv casts but not views. Until now we assumed that always matches. For strings it does not.
