### ISSUE TITLE
MNT: Adopt pythoncapi-compat?

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#26158]
As noted [in PEP 703](https://peps.python.org/pep-0703/#borrowed-references), C API functions returning borrowed references are problematic in the nogil build of Python, and new functions are available in Python 3.13 that return new references.

Three years ago @vstinner proposed vendoring `pythoncapi-compat` to replace `npy3k_compat.h` in https://github.com/numpy/numpy/pull/18713 and that was rejected.

Unlike that proposal, I don't want to expose `pythoncapi-compat.h` in the public numpy C API, instead I'd only like to use it internally, replacing the internal `npy_pycompat.h` header. That means concerns raised in that PR about requiring C99 or adding potentially problematic constructs to the numpy C API are moot.

We could also just copy/paste [the definitions](https://github.com/python/pythoncapi-compat/blob/d16872a44be1c363be0b6aecacb134ae759d89ef/pythoncapi_compat.h#L799-L839) of the functions I need from the `pythoncapi-compat.h` header, but I thought it would be worth taking the project's temperature on adding it as a build-time dependency via a submodule like `highway` and `pocketfft`, since there will inevitably be other things we want in the future.

**Comment by rgommers** [comment]
This proposal seems like the right way to go to me. We now have other git submodules, and these compat functions are probably going to be updated semi-regularly during the 3.13/3.14 release cycles. An extra git submodule is preferable over copy-pasting (LoC count difference as discussed in gh-18713 isn't too relevant here).

**Comment by vstinner** [comment]
You might also look at my experimental https://github.com/vstinner/deadparrot/ project which is similar to pythoncapi-compat, but it's implemented as a shared library, rather than a header file. It might be harder to integrate in numpy.

**Comment by rgommers** [comment]
It's possible to integrate a shared library, but we don't have any yet. It'd be slightly annoying because we'd have to deal with settings RPATHs and things like `os.add_dll_directory` or preloading with `ctypes.WinDLL` on Windows. And it's not clear to me that it'll work when several packages each preload the shared library - this probably requires name mangling.

Is there an advantage to using `deadparrot`?

**Comment by vstinner** [comment]
> Is there an advantage to using deadparrot?

My plan for the future is to backport/forward port way more complicated functions which don't fit into pythoncapi-compat.h. But numpy should not really need them, so pythoncapi-compat.h should be better fit for your practical constraints.

**Comment by ngoldbaum** [comment]
We added the submodule in #26189
