### ISSUE TITLE
BUG: np.sum() returns wrong value

### ISSUE THREAD

**Issue by JarmoHu** [numpy/numpy#26179]
### Describe the issue:

The matrices `Sz_old` and `Sz_new` calculated in both ways should be equal, and they are in fact equal. But the calculations calculated by the `np.sum()` function are not equal. But the result of `sum()` after `.copy()` is correct again.

### Reproduce the code example:

```python
#%%
import sys
import os
from typing import List
import numpy as np

# from ylections import OrderedDict
# from bidict import bidict
# import matplotlib.pyplot as plt
import tensorflow as tf
import scipy.io as io
import math
from datetime import datetime
from scipy.io import savemat, loadmat

sys.path.append("C:\\Program Files\\Lumerical\\v202\\api\\python\\")  # Default windows lumapi path
sys.path.append("D:\\Program\\Lumerical\\v202\\api\\python\\")
sys.path.append(os.path.dirname(__file__))  # Current directory
import lumapi
#%%
model = lumapi.FDTD()
model.load("C:\\Users\\jarmo\\Desktop\\temp.fsp")
#%%

modep = model.getresult("::model::monitor_1","mode profiles")
modep_E = modep["E1"]
modep_H = modep["H1"]
#%%
S_old = np.cross(modep_E,np.conj(modep_H))
Sz_old = S_old[0,:,:,0,2]

Ex = modep_E[0,:,:,0,0]
Ey = modep_E[0,:,:,0,1]
Ez = modep_E[0,:,:,0,2]
Hx = modep_H[0,:,:,0,0]
Hy = modep_H[0,:,:,0,1]
Hz = modep_H[0,:,:,0,2]
Sz_new = Ex*np.conj(Hy) - Ey*np.conj(Hx)
print("np.sum(Sz_old) - np.sum(Sz_new):\t\t\t\t" + str(np.sum(Sz_old) - np.sum(Sz_new)))
print("np.sum(Sz_old.copy()) - np.sum(Sz_new.copy()):\t" + str(np.sum(Sz_old.copy()) - np.sum(Sz_new.copy())))
print("np.sum(Sz_old-Sz_new):\t\t\t\t\t\t\t"+str(np.sum(Sz_old-Sz_new)))
delta = Sz_old-Sz_new
```

### Error message:

```shell
runcell(4, 'C:/Users/jarmo/.spyder-py3/temp.py')
np.sum(Sz_old) - np.sum(Sz_new):		-1.988289759429226e-17j
np.sum(Sz_old.copy()) - np.sum(Sz_new.copy()):	0j
np.sum(Sz_old-Sz_new):		0j
```

### Python and NumPy Versions:

Python 3.10.8
numpy                     1.21.5          py310h6d2d95c_3    defaults
numpy-base                1.21.5          py310h206c741_3    defaults

### Runtime Environment:

_tflow_select             2.3.0                       mkl    defaults
abseil-cpp                20211102.0           hd77b12b_0    defaults
absl-py                   1.3.0           py310haa95532_0    defaults
aiohttp                   3.8.3           py310h2bbff1b_0    defaults
aiosignal                 1.2.0              pyhd3eb1b0_0    defaults
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
arrow                     1.2.3           py310haa95532_0    defaults
astroid                   2.11.7          py310haa95532_0    defaults
astunparse                1.6.3                      py_0    defaults
async-timeout             4.0.2           py310haa95532_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     22.1.0          py310haa95532_0    defaults
autopep8                  1.6.0              pyhd3eb1b0_1    defaults
babel                     2.11.0          py310haa95532_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
bcrypt                    3.2.0           py310h2bbff1b_1    defaults
beautifulsoup4            4.11.1          py310haa95532_0    defaults
binaryornot               0.4.4              pyhd3eb1b0_1    defaults
black                     22.6.0          py310haa95532_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.1.0              pyhd3eb1b0_0    defaults
blinker                   1.4             py310haa95532_0    defaults
brotli                    1.0.9                h2bbff1b_7    defaults
brotli-bin                1.0.9                h2bbff1b_7    defaults
brotlipy                  0.7.0           py310h2bbff1b_1002    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2024.3.11            haa95532_0    defaults
cachetools                4.2.2              pyhd3eb1b0_0    defaults
certifi                   2024.2.2        py310haa95532_0    defaults
cffi                      1.15.1          py310h2bbff1b_3    defaults
chardet                   4.0.0           py310haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4           py310haa95532_0    defaults
cloudpickle               2.0.0              pyhd3eb1b0_0    defaults
colorama                  0.4.6           py310haa95532_0    defaults
comm                      0.1.2           py310haa95532_0    defaults
contourpy                 1.0.5           py310h59b6b97_0    defaults
cookiecutter              1.7.3              pyhd3eb1b0_0    defaults
cryptography              38.0.4          py310h21b164f_0    defaults
cycler                    0.11.0             pyhd3eb1b0_0    defaults
datetime                  5.0                      pypi_0    pypi
debugpy                   1.5.1           py310hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-match-patch          20200713           pyhd3eb1b0_0    defaults
dill                      0.3.6           py310haa95532_0    defaults
docutils                  0.18.1          py310haa95532_3    defaults
entrypoints               0.4             py310haa95532_0    defaults
fftw                      3.3.9                h2bbff1b_1    defaults
flake8                    4.0.1              pyhd3eb1b0_1    defaults
flatbuffers               2.0.0                h6c2663c_0    defaults
flit-core                 3.6.0              pyhd3eb1b0_0    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.12.1               ha860e81_0    defaults
frozenlist                1.3.3           py310h2bbff1b_0    defaults
gast                      0.5.3              pyhd3eb1b0_0    defaults
giflib                    5.2.1                h62dcd97_0    defaults
glib                      2.69.1               h5dc1a3c_2    defaults
google-auth               2.6.0              pyhd3eb1b0_0    defaults
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0    defaults
google-pasta              0.2.0              pyhd3eb1b0_0    defaults
grpcio                    1.42.0          py310hc60d5dd_0    defaults
gst-plugins-base          1.18.5               h9e645db_0    defaults
gstreamer                 1.18.5               hd78058f_0    defaults
h5py                      3.7.0           py310hfc34f40_0    defaults
hdf5                      1.10.6               h1756f20_1    defaults
icc_rt                    2022.1.0             h6049295_2    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      3.4             py310haa95532_0    defaults
imagesize                 1.4.1           py310haa95532_0    defaults
importlib-metadata        4.11.3          py310haa95532_0    defaults
importlib_metadata        4.11.3               hd3eb1b0_0    defaults
inflection                0.5.1           py310haa95532_0    defaults
intel-openmp              2021.4.0          haa95532_3556    defaults
intervaltree              3.1.0              pyhd3eb1b0_0    defaults
ipykernel                 6.19.2          py310h9909e9c_0    defaults
ipython                   7.31.1          py310haa95532_1    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
isort                     5.9.3              pyhd3eb1b0_0    defaults
jedi                      0.18.1          py310haa95532_1    defaults
jellyfish                 0.9.0           py310h2bbff1b_0    defaults
jinja2                    3.1.2           py310haa95532_0    defaults
jinja2-time               0.2.0              pyhd3eb1b0_3    defaults
jpeg                      9e                   h2bbff1b_0    defaults
jsonschema                4.16.0          py310haa95532_0    defaults
jupyter_client            7.4.8           py310haa95532_0    defaults
jupyter_core              5.1.1           py310haa95532_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
keras                     2.9.0           py310haa95532_0    defaults
keras-preprocessing       1.1.2              pyhd3eb1b0_0    defaults
keyring                   23.4.0          py310haa95532_0    defaults
kiwisolver                1.4.4           py310hd77b12b_0    defaults
lazy-object-proxy         1.6.0           py310h2bbff1b_0    defaults
lerc                      3.0                  hd77b12b_0    defaults
libbrotlicommon           1.0.9                h2bbff1b_7    defaults
libbrotlidec              1.0.9                h2bbff1b_7    defaults
libbrotlienc              1.0.9                h2bbff1b_7    defaults
libclang                  12.0.0          default_h627e005_2    defaults
libcurl                   7.86.0               h86230a5_0    defaults
libdeflate                1.8                  h2bbff1b_5    defaults
libffi                    3.4.2                hd77b12b_6    defaults
libiconv                  1.16                 h2bbff1b_2    defaults
libogg                    1.3.5                h2bbff1b_1    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libprotobuf               3.20.1               h23ce68f_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libspatialindex           1.9.3                h6c2663c_0    defaults
libssh2                   1.10.0               hcd4344a_0    defaults
libtiff                   4.5.0                h8a3f274_0    defaults
libvorbis                 1.3.7                he774522_0    defaults
libwebp                   1.2.4                h2bbff1b_0    defaults
libwebp-base              1.2.4                h2bbff1b_0    defaults
libxml2                   2.9.14               h0ad7f3c_0    defaults
libxslt                   1.1.35               h2bbff1b_0    defaults
lxml                      4.9.1           py310h1985fb9_0    defaults
lz4-c                     1.9.4                h2bbff1b_0    defaults
markdown                  3.4.1           py310haa95532_0    defaults
markupsafe                2.1.1           py310h2bbff1b_0    defaults
matplotlib                3.6.2           py310haa95532_0    defaults
matplotlib-base           3.6.2           py310h1094b8e_0    defaults
matplotlib-inline         0.1.6           py310haa95532_0    defaults
mccabe                    0.7.0              pyhd3eb1b0_0    defaults
mistune                   0.8.4           py310h2bbff1b_1000    defaults
mkl                       2021.4.0           haa95532_640    defaults
mkl-service               2.4.0           py310h2bbff1b_0    defaults
mkl_fft                   1.3.1           py310ha0764ea_0    defaults
mkl_random                1.2.2           py310h4ed8f06_0    defaults
multidict                 6.0.2           py310h2bbff1b_0    defaults
munkres                   1.1.4                      py_0    defaults
mypy_extensions           0.4.3           py310haa95532_1    defaults
nbclient                  0.5.13          py310haa95532_0    defaults
nbconvert                 6.5.4           py310haa95532_0    defaults
nbformat                  5.7.0           py310haa95532_0    defaults
nest-asyncio              1.5.6           py310haa95532_0    defaults
numpy                     1.21.5          py310h6d2d95c_3    defaults
numpy-base                1.21.5          py310h206c741_3    defaults
numpydoc                  1.5.0           py310haa95532_0    defaults
oauthlib                  3.2.1           py310haa95532_0    defaults
openssl                   1.1.1w               h2bbff1b_0    defaults
opt_einsum                3.3.0              pyhd3eb1b0_1    defaults
packaging                 22.0            py310haa95532_0    defaults
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
paramiko                  2.8.1              pyhd3eb1b0_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pathspec                  0.9.0           py310haa95532_0    defaults
pcre                      8.45                 hd77b12b_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.3.0           py310hdc2b20a_1    defaults
pip                       22.3.1          py310haa95532_0    defaults
platformdirs              2.5.2           py310haa95532_0    defaults
pluggy                    1.0.0           py310haa95532_1    defaults
ply                       3.11            py310haa95532_0    defaults
poyo                      0.5.0              pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.36          py310haa95532_0    defaults
protobuf                  3.20.1          py310hd77b12b_0    defaults
psutil                    5.9.0           py310h2bbff1b_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pyasn1                    0.4.8              pyhd3eb1b0_0    defaults
pyasn1-modules            0.2.8                      py_0    defaults
pycodestyle               2.8.0              pyhd3eb1b0_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydocstyle                6.1.1              pyhd3eb1b0_0    defaults
pyflakes                  2.4.0              pyhd3eb1b0_0    defaults
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyjwt                     2.4.0           py310haa95532_0    defaults
pylint                    2.14.5          py310haa95532_0    defaults
pyls-spyder               0.4.0              pyhd3eb1b0_0    defaults
pynacl                    1.5.0           py310h8cc25b3_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.9           py310haa95532_0    defaults
pyqt                      5.15.7          py310hd77b12b_0    defaults
pyqt5-sip                 12.11.0         py310hd77b12b_0    defaults
pyqtwebengine             5.15.7          py310hd77b12b_0    defaults
pyrsistent                0.18.0          py310h2bbff1b_0    defaults
pysocks                   1.7.1           py310haa95532_0    defaults
python                    3.10.8               h966fe2a_1    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2          py310haa95532_0    defaults
python-flatbuffers        2.0                pyhd3eb1b0_0    defaults
python-lsp-black          1.2.1           py310haa95532_0    defaults
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0    defaults
python-lsp-server         1.5.0           py310haa95532_0    defaults
python-slugify            5.0.2              pyhd3eb1b0_0    defaults
pytz                      2022.7          py310haa95532_0    defaults
pywin32                   305             py310h2bbff1b_0    defaults
pywin32-ctypes            0.2.0           py310haa95532_1000    defaults
pyyaml                    6.0             py310h2bbff1b_1    defaults
pyzmq                     23.2.0          py310hd77b12b_0    defaults
qdarkstyle                3.0.2              pyhd3eb1b0_0    defaults
qstylizer                 0.1.10             pyhd3eb1b0_0    defaults
qt-main                   5.15.2               he8e5bd7_7    defaults
qt-webengine              5.15.9               hb9a9bb5_4    defaults
qtawesome                 1.0.3              pyhd3eb1b0_0    defaults
qtconsole                 5.3.2           py310haa95532_0    defaults
qtpy                      2.2.0           py310haa95532_0    defaults
qtwebkit                  5.212                h3ad3cdb_4    defaults
requests                  2.28.1          py310haa95532_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
rope                      0.22.0             pyhd3eb1b0_0    defaults
rsa                       4.7.2              pyhd3eb1b0_1    defaults
rtree                     0.9.7           py310h2eaa2aa_1    defaults
scipy                     1.7.3           py310h6d2d95c_2    defaults
setuptools                65.6.3          py310haa95532_0    defaults
sip                       6.6.2           py310hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
snappy                    1.1.9                h6c2663c_0    defaults
snowballstemmer           2.2.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.3.2.post1     py310haa95532_0    defaults
sphinx                    5.0.2           py310haa95532_0    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaults
spyder                    5.3.3           py310haa95532_0    defaults
spyder-kernels            2.3.3           py310haa95532_0    defaults
sqlite                    3.40.1               h2bbff1b_0    defaults
tensorboard               2.9.0           py310haa95532_0    defaults
tensorboard-data-server   0.6.1           py310haa95532_0    defaults
tensorboard-plugin-wit    1.8.1           py310haa95532_0    defaults
tensorflow                2.9.1           mkl_py310h626feff_1    defaults
tensorflow-base           2.9.1           mkl_py310h6a7f48e_1    defaults
tensorflow-estimator      2.9.0           py310haa95532_0    defaults
termcolor                 2.1.0           py310haa95532_0    defaults
text-unidecode            1.3                pyhd3eb1b0_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
threadpoolctl             2.2.0              pyh0d69192_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tinycss                   0.4             pyhd3eb1b0_1002    defaults
tinycss2                  1.2.1           py310haa95532_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1           py310haa95532_0    defaults
tomlkit                   0.11.1          py310haa95532_0    defaults
tornado                   6.2             py310h2bbff1b_0    defaults
traitlets                 5.7.1           py310haa95532_0    defaults
typing_extensions         4.4.0           py310haa95532_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
ujson                     5.4.0           py310hd77b12b_0    defaults
unidecode                 1.2.0              pyhd3eb1b0_0    defaults
urllib3                   1.26.13         py310haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
watchdog                  2.1.6           py310haa95532_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1           py310haa95532_1    defaults
werkzeug                  2.2.2           py310haa95532_0    defaults
whatthepatch              1.0.2           py310haa95532_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
win_inet_pton             1.1.0           py310haa95532_0    defaults
wincertstore              0.2             py310haa95532_2    defaults
wrapt                     1.14.1          py310h2bbff1b_0    defaults
xz                        5.2.8                h8cc25b3_0    defaults
yaml                      0.2.5                he774522_0    defaults
yapf                      0.31.0             pyhd3eb1b0_0    defaults
yarl                      1.8.1           py310h2bbff1b_0    defaults
zeromq                    4.3.4                hd77b12b_0    defaults
zipp                      3.11.0          py310haa95532_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
zope-interface            5.5.2                    pypi_0    pypi
zstd                      1.5.2                h19a0ad4_0    defaults

**Comment by JarmoHu** [comment]
just run
```python
print(np.sum(Sz_new))
print(np.sum(Sz_new.copy()))
```
then return
```python
runcell(5, 'C:/Users/jarmo/.spyder-py3/temp.py')
-1.7833034624798014e-17j
-3.771593221909027e-17j
```

**Comment by seberg** [comment]
Please see the note in https://numpy.org/doc/stable/reference/generated/numpy.sum.html, this is expected behavior due to normal numerical precision limits;  there are existing issues discussing potential (long term) improvements.
