### ISSUE TITLE
BUG: the result of a complex indexing operation is incorrect

### ISSUE THREAD

**Issue by jtc1246** [numpy/numpy#26184]
### Describe the issue:

```python
a = np.zeros((10, 20, 4, 30, 40, 3), dtype='uint64')
x1 = a[3, (5, 2), (False, True, False, True), (5,), 2]
x1.shape
```
The result of this should be (2,2,1,3), but actually it is (2,3).

### Reproduce the code example:

```python
import numpy as np
a=np.zeros((10, 20, 4, 30, 40, 3), dtype='uint64')
x1 = a[3, (5, 2), (False, True, False, True), (5,), 2]
print(x1.shape)
```

### Python and NumPy Versions:

>>> print(numpy.__version__)
1.26.0
>>> print(sys.version)
3.9.18 (main, Aug 25 2023, 13:20:14) 
[GCC 11.4.0]

### Runtime Environment:

<details>

```
[{'numpy_version': '1.26.0',
  'python': '3.9.18 (main, Aug 25 2023, 13:20:14) \n[GCC 11.4.0]',
  'uname': uname_result(system='Linux', node='jtc', release='6.2.0-34-generic', version='#34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/home/jtc/.local/lib/python3.9/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None
```

</details>

### Context for the issue:

Actually I am implementing my own memmap algorithm with direct IO. I want to compare its result with np.memmap to check whether it is correct. Then I just encountered this issue.

**Comment by rkern** [comment]
The result looks correct [according to the semantics that are documented](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing) for this case. It looks like you want a [different set of semantics](https://numpy.org/neps/nep-0021-advanced-indexing.html#outer-indexing) that have been considered and largely agreed to, but the development work for it has stalled. #6075

**Comment by seberg** [comment]
I'll close the issue, since I think the links are sufficient.  I'll additionally mention `np.ix_` which I think exists basically to simplify what you want.
