### ISSUE TITLE
ENH: np.asanyarray should grow copy and device keyword arguments to match asarray

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#26196]
### Proposed new feature or change:

We added `copy` and `device` as keywords for `np.asarray` for array API compatibility. We should perhaps add similar keywords for `asanyarray`. This shouldn't be any additional maintenance burden because `asarray` and `asanyarray` have almost identical C implementations.

**Comment by seberg** [comment]
Adding `copy` makes sense to me for both, since `copy=False` is a useful meaning.

I am fine with `device=`, but are we sure we want to add `device=` to all but the strictly necessary ones?

**Comment by rgommers** [comment]
Addressed in gh-26580, closing.

> I am fine with `device=`, but are we sure we want to add `device=` to all but the strictly necessary ones?

We shouldn't overdo it I think, but in this case having `asarray` and `asanyarray` be as similar as possible looks right to me.
