### ISSUE TITLE
BUG: fft.fftfreq appears to be giving wrong answers

### ISSUE THREAD

**Issue by BartMassey** [numpy/numpy#26217]
### Describe the issue:

As far as I can tell, the bin frequencies given for `fft.fftfreq(n, d=d)` seem to be off by a factor of `n/(n-1)` for all `n` and `d` I have tried so far.

This *has* to be me, not `fftfreq`, I think, but for the life of me I can't see it and neither could a friend who looked.

The example below prints  `0.05834840492222022`. With the frequency correction at line 15 uncommented, it instead prints `5.523359547510154e-15`.

Please see <https://github.com/BartMassey/fftfreq-issue> for full reproducing code with comments, documentation and plots.

### Reproduce the code example:

```python
import numpy as np
from numpy.fft import *

sr = 24000
tf = 250
n = 512

ntf = 2 * tf / sr
b = round(ntf * n / 2)
freqs = fftfreq(n, d=1/sr)
f0 = freqs[b]
assert freqs[b] == -freqs[n - b]

fc = f0
# fc = f0 * (n - 1) / n

t = np.linspace(0, n / sr, n, dtype=np.float64)
y0 = np.cos(2 * np.pi * fc * t)

f = np.zeros(n, dtype=np.complex128)
f[b] = 1.0
f[n - b] = 1.0
y = 0.5 * n * ifft(f)

print(np.max(np.abs(y0 - np.real(y))))
```

### Error message:

```shell
N/A
```

### Python and NumPy Versions:

1.26.4
3.11.8 (main, Mar 26 2024, 12:26:07) [GCC 13.2.0]

### Runtime Environment:

[{'numpy_version': '1.26.4',
  'python': '3.11.8 (main, Mar 26 2024, 12:26:07) [GCC 13.2.0]',
  'uname': uname_result(system='Linux', node='bartx', release='6.7.9-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.7.9-2 (2024-03-13)', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'architecture': 'Zen',
  'filepath': '/usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so',
  'internal_api': 'openblas',
  'num_threads': 24,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.26'}]

### Context for the issue:

I spent a bunch of time figuring out this correction. If I'm right that it's needed, then a bunch of folks are getting slightly-wrong bin centers. If (as is likely) I'm wrong, then I'd like to supply a doc fix to help others avoid my mistake.

**Comment by lucascolley** [comment]
This is the code:

https://github.com/numpy/numpy/blob/e59c074842e3f73483afa5ddef031e856b9fd313/numpy/fft/_helper.py#L165-L174

**Comment by lucascolley** [comment]
One of our test cases in SciPy is that `9 * fft.fftfreq(9) == [0, 1, 2, 3, 4, -4, -3, -2, -1]`. Does that also seem incorrect to you? If not, is that a counterexample to "for all `n` and `d`"?

**Comment by BartMassey** [comment]
(Note: this issue was moved from <https://github.com/scipy/scipy/issues/20400>.)

**Comment by BartMassey** [comment]
@lucascolley It is wrong according to my code (https://github.com/BartMassey/fftfreq-issue):

```
$ python3 cos.py --n 9 --sr 1 --tf 0.2
0.9396926207859079
$ python3 cos.py --n 9 --sr 1 --tf 0.2 --correction
7.771561172376096e-16
```

**Comment by jakevdp** [comment]
An observation: if you use `endpoint=False` in the `linspace` in your code, the results match:
```python
t = np.linspace(0, n / sr, n, dtype=np.float64, endpoint=False)
```
This seems more correct, because it results in dividing your domain into `n` equal bins rather than `n - 1` equal bins.

**Comment by BartMassey** [comment]
Yeah, just found this myself while staring at things in the cold light of day. Why in the why does `endpoint` default to `True` in `numpy.linspace()`?

Ah well. Sure enough was my bug after all. Don't even see anyplace to add a warning to future users in the docs.

Thanks much for all your quick and friendly help!
