### ISSUE TITLE
BUG: numpy c-interface memory leak2

### ISSUE THREAD

**Issue by TeusEE** [numpy/numpy#26225]
### Describe the issue:

#26218 
it this case, np.empty_like -> np.ones can solve problem

but i find another case.

1. make result numpy Array in python function
2. passing it in c_func, and return this array
3. remove return Array and execute gc.collec()

please review code below

i think there are any problem...

```cpp
//mydll.c
#include "pch.h" // use stdafx.h in Visual Studio 2017 and earlier
#include <utility>
#include <limits.h>
#include <stdlib.h>
#include <thread>
#include <vector>
#include <stdio.h>
#include "mydll.h"
#include <omp.h>
#include <immintrin.h>

//just passing numpy array in c func
void* test_foo(int* a, int* b, int* ret, int data_cnt) {    
    return nullptr;
}

//passing numpy array to c func and useing as pointer access
void* list_add_serial(int* a, int* b, int* ret, int data_cnt) {    
    for (int i = 0; i < (data_cnt); i++) {
        ret[i] = a[i] + b[i];
    }    
    return nullptr;
}    

// mydll.h - Contains declarations of math functions
#pragma once

#ifdef MATHLIBRARY_EXPORTS
#define MATHLIBRARY_API __declspec(dllexport)
#else
#define MATHLIBRARY_API __declspec(dllimport)
#endif

extern "C" MATHLIBRARY_API void* test_foo(int* a, int* b, int* ret, int data_cnt);
extern "C" MATHLIBRARY_API void* list_add_serial(int* a, int* b, int* ret,int data_cnt);
```

becuase the return array get any varaible for save
the returned array must garbage collected.

but never removed in windows memory.

```python
import ctypes
import numpy as np
import psutil
lib = ctypes.CDLL(r'mydll.dll')
import time
import gc
dt1 = np.ones(100000000, dtype = np.int32)
dt2 = np.ones(100000000, dtype = np.int32)

def np_add_2d(_a, _b, _lib):
    _lib.restype = ctypes.POINTER(ctypes.c_void_p)
    #generate numpy array in python func
    _ret = np.ones(100000000, dtype = np.int32)
    temp_a = np.ctypeslib.as_ctypes(_a)
    temp_b = np.ctypeslib.as_ctypes(_b)    
    temp_ret = np.ctypeslib.as_ctypes(_ret)
    #pass numpy array to c func in python func
    ret_array = _lib(temp_a, temp_b, temp_ret, len(_ret))
    del temp_a, temp_b, temp_ret, ret_array    
    try:
        return _ret
    finally: 
        #adding below implicity remove return array can't free mem in python interpreter
        #del _ret
        while gc.collect():
            print("collect gcing...")   

np_add_2d(dt1, dt2, lib.test_foo)
np_add_2d(dt1, dt2, lib.test_foo)
np_add_2d(dt1, dt2, lib.test_foo)
np_add_2d(dt1, dt2, lib.test_foo)
np_add_2d(dt1, dt2, lib.test_foo)
#passing just numpy array to c_func. mem_leak 

np_add_2d(dt1, dt2, lib.list_add_serial)
np_add_2d(dt1, dt2, lib.list_add_serial)
np_add_2d(dt1, dt2, lib.list_add_serial)
np_add_2d(dt1, dt2, lib.list_add_serial)
np_add_2d(dt1, dt2, lib.list_add_serial)
#operating numpy array in c func. also mem_leak
```

strangly, if i execute python func with for loop, there are once mem_leak

but when in IPython Env(i using spyder), 
exeucute code with below sequence
np_add_2d(dt1, dt2, lib.list_add_serial) -> f9 execute
![image](https://github.com/numpy/numpy/assets/79349894/6b050e17-8bee-4399-b5a4-27aefc691f30)

make mem leak

the mem leak screenshot below.(there are no other program)
![image](https://github.com/numpy/numpy/assets/79349894/0bb8525d-4959-4ca9-98a5-71850682e395)

### Reproduce the code example:

```python
import ctypes
import numpy as np
import psutil
lib = ctypes.CDLL(r'mydll.dll')
import time
import gc
dt1 = np.ones(100000000, dtype = np.int32)
dt2 = np.ones(100000000, dtype = np.int32)

def np_add_2d(_a, _b, _lib):
    _lib.restype = ctypes.POINTER(ctypes.c_void_p)
    #generate numpy array in python func
    _ret = np.ones(100000000, dtype = np.int32)
    temp_a = np.ctypeslib.as_ctypes(_a)
    temp_b = np.ctypeslib.as_ctypes(_b)    
    temp_ret = np.ctypeslib.as_ctypes(_ret)
    #pass numpy array to c func in python func
    ret_array = _lib(temp_a, temp_b, temp_ret, len(_ret))
    del temp_a, temp_b, temp_ret, ret_array    
    try:
        return _ret
    finally:        
        while gc.collect():
            print("collect gcing...")   

np_add_2d(dt1, dt2, lib.test_foo)
#passing just numpy array to c_func. mem_leak 

np_add_2d(dt1, dt2, lib.list_add_serial)
#operating numpy array in c func. also mem_leak
```

### Python and NumPy Versions:

1.26.3
3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

### Runtime Environment:

[{'numpy_version': '1.26.3',
  'python': '3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='PC1702751', release='10', version='10.0.17763', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]

**Comment by seberg** [comment]
> strangly, if i execute python func with for loop, there are once mem_leak

If you cannot continue to leak data by running code in a loop, then there is no memory leak.

**Comment by TeusEE** [comment]
> > strangly, if i execute python func with for loop, there are once mem_leak
> 
> If you cannot continue to leak data by running code in a loop, then there is no memory leak.
> 
> EDIT: to be clear, you would want to loop everything, including the setup code.

i found that this issue occur only in IPython Env(Jupyter ipynb, Spyder)
![image](https://github.com/numpy/numpy/assets/79349894/6b050e17-8bee-4399-b5a4-27aefc691f30)

![image](https://github.com/numpy/numpy/assets/79349894/7ef69bcc-fa30-4bd5-9043-7d59ed19d45d)
should i consider this issue is about IPython module?

**Comment by TeusEE** [comment]
i found that if i make numpy array in python func and return it in Jupyter notebook env with one-line execute, same  Phenomenon occur.
```python
import ctypes
import numpy as np
import psutil
lib = ctypes.CDLL(r'mydll.dll')
import time
import gc
dt1 = np.ones(100000000, dtype = np.int32)
dt2 = np.ones(100000000, dtype = np.int32)
def np_add(_a, _b, _lib):    
    _ret = np.ones(100000000, dtype = np.int32)    
    try:
        return _ret
    finally:
        while gc.collect():
            print("collect gcing...")   
```
![image](https://github.com/numpy/numpy/assets/79349894/ab00503a-ffe2-4fde-bdc7-cba29a8dd9eb)
after increasing memory usage in windows, it never decrease until i shut down Jupyter kernel
![image](https://github.com/numpy/numpy/assets/79349894/67ad3df9-ca24-4247-a027-93eb60babecc)

is this intended..🤔?

**Comment by TeusEE** [comment]
seems like not only numpy array, python list also act same. i think this is not related with numpy array c func
close this issue.
