### ISSUE TITLE
BUG: Inconsistent behaviour of `SeedSequence.generate_state` inside vs outside of unittests.

### ISSUE THREAD

**Issue by zoj613** [numpy/numpy#26221]
### Describe the issue:

I was looking at https://github.com/numpy/numpy/blob/e59c074842e3f73483afa5ddef031e856b9fd313/numpy/random/tests/test_seed_sequence.py#L7 and noticed that row 5 of the `inputs` list as a seed to `SeedSequence` produces different results that indicated by row 5 of `outputs`. Particularly, row 5 of `outputs` insists that the expected output of `generate_state(4)` is  `[1086200464, 2191331643, 560336446, 3658716651]`, but when the call to the method actually produces `[3633748596, 2539471311, 1066956888, 1033319901]`.

Is this considered a bug? Or am I misunderstanding how `SeedSequence.generate_state` is supposed to work given a fixed seed?

cc @rkern @bashtage 

### Reproduce the code example:

```python
import numpy as np

input_row5 = [1864922766, 719732118, 3882010307, 1776744564]
ss = np.random.SeedSequence(input_row5)
ss.generate_state(len(input_row5))
>> array([3633748596, 2539471311, 1066956888, 1033319901], dtype=uint32)
# this is different from [1086200464, 2191331643, 560336446, 3658716651] as indicated by the unit test.
```

### Python and NumPy Versions:

1.22.4
3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]

### Context for the issue:

I would expect the tests to fail if the output is "wrong" but for some reason the tests pass if ran in that order. Is this behaviour expected? I thought `SeedSequence` states are supposed to be reproducible?

**Comment by seberg** [comment]
Where does the `len(input_row5)` come from?  The test uses 4 not 5, clearly generating a different number of outputs doesn't mean the first part is the same, I would be surprised if that isn't by design.
Going to close, not sure there is more to discuss.

**Comment by seberg** [comment]
Nvm, I am being silly: you simply typoed the second number.

**Comment by zoj613** [comment]
Is there a reason why you closed the issue @seberg ? I thought the example provided reproduces the inconsistent behaviour? Am I missing something?

**Comment by zoj613** [comment]
> Where does the `len(input_row5)` come from? The test uses 4 not 5, clearly generating a different number of outputs doesn't mean the first part is the same, I would be surprised if that isn't by design. Going to close, not sure there is more to discuss.

`input_row_5` is the fifth item in the `inputs` list of lists. It's "expected" output is the fifth item in the `outputs` list, namely `[1086200464, 2191331643, 560336446, 3658716651]`. However, the _actual_ output from `SeedSequence.generate_state` is `[3633748596, 2539471311, 1066956888, 1033319901]`. The weird thing is that the tests pass even thought the "expected" output is wrong.

**Comment by rkern** [comment]
You have a typo in your example. The second number in `input_row5` is supposed to be 1719732118, not 719732118.

**Comment by zoj613** [comment]
Thank you @rkern , I did not notice that. I must have accidentally deleted the leading 1 while trying to format the list in my editor.
