### ISSUE TITLE
ENH: Should `np.nonzero` throw exception on 0D input?

### ISSUE THREAD

**Issue by mtsokol** [numpy/numpy#26238]
### Proposed new feature or change:

The Array API standard says that [`np.nonzero` should throw an exception for 0D input](https://data-apis.org/array-api/latest/API_specification/generated/array_api.nonzero.html).

Currently, `np.nonzero` implicitly makes 0D input a 1D (with `atleast_1d`), ~~no warning is raised~~ a warning is raised. In its docstring it says:
```
       .. deprecated:: 1.17.0

          Use `atleast_1d` explicitly if this behavior is deliberate.
```

Also `np.array(1).nonzero()` gives a deprecation warning:
```
DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
```

Do we want to throw an exception on 0D input for both cases for Array API compatibility?

**Comment by ngoldbaum** [comment]
>  no warning is raised

I don't see that over here:

```
In [1]: np.nonzero(np.array(0))
/Users/goldbaum/Documents/numpy/numpy/_core/fromnumeric.py:57: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
  return bound(*args, **kwds)
Out[1]: (array([], dtype=int64),)

In [2]: np.nonzero(np.array(1))
/Users/goldbaum/Documents/numpy/numpy/_core/fromnumeric.py:57: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
  return bound(*args, **kwds)
Out[2]: (array([0]),)

In [3]: np.nonzero(np.array(True))
/Users/goldbaum/Documents/numpy/numpy/_core/fromnumeric.py:57: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  return bound(*args, **kwds)
Out[3]: (array([0]),)
```

Maybe something funky doing on with the array API tests?

**Comment by mtsokol** [comment]
My bad. Now I see that warnings are present in both cases. Then the question is about raising an exception.

**Comment by ngoldbaum** [comment]
Ah I see. It’s been deprecated since numpy 1.17 in 2019, I think it’s safe to expire this one.

**Comment by seberg** [comment]
Yeah, could have just done it in 2.0 (probably should have), but... let's just finish it in the next release.
