### ISSUE TITLE
DOC: Example for numpy.any with index argument is ambiguous

### ISSUE THREAD

**Issue by glados-verma** [numpy/numpy#26230]
### Issue with current documentation:

For [numpy.any](https://numpy.org/doc/stable/reference/generated/numpy.any.html#numpy.any), for the arg `index`, the following example is offered:

```
>>> np.any([[True, False], [False, False]], axis=0)
array([ True, False])
```

Note that you get the same output for axis=1

### Idea or request for content:

An example that gives different results for different values of axis, e.g.:

```
>>> np.any([[True, False, True], [False, False, False]], axis=0)
array([ True, False, True])
```

**Comment by rossbar** [comment]
Closed by #26235
