### ISSUE TITLE
ENH: Drop support for Python 3.9?

### ISSUE THREAD

**Issue by lpsinger** [numpy/numpy#26242]
### Proposed new feature or change:

According to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), Numpy is to drop support for Python 3.9 on April 5, 2024 — a few days ago. Is this plan still accurate?

I am asking because I maintain a number of packages that depend upon Numpy and emulate Numpy's Python support policy, and there are some features in Python 3.10 that I would like to start taking advantage of if the policy permits it.

**Comment by ngoldbaum** [comment]
We are planning to drop python3.9 for numpy 2.1, numpy 2.0 will support python3.9 because we had a couple asks for it.

**Comment by charris** [comment]
>  because we had a couple asks for it.

We drop in same version that will have the next Python release.

**Comment by ngoldbaum** [comment]
We dropped python3.9 support in `main` in #26222
