### ISSUE TITLE
BUG: consider shipping numpy 2 final (or rc2) with OpenBLAS 0.3.27

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#26240]
NumPy 2.0.0rc1 currently ships OpenBLAS 0.3.26 that has a thread-safety bug on Windows:

- https://github.com/OpenMathLib/OpenBLAS/issues/4582

This was fixed in OpenBLAS 0.3.27 but is not yet packaged on pypi.org:

- https://pypi.org/project/scipy-openblas64/

This bug is causing the scikit-learn release CI to freeze when testing against numpy 2.0.0rc1.

**Comment by ogrisel** [comment]
Here is the PR for threadpoolctl:

https://github.com/joblib/threadpoolctl/pull/175

Note: threadpoolctl now has a pluggable controller system, so numpy could ship its own library backend:

https://github.com/joblib/threadpoolctl?tab=readme-ov-file#writing-a-custom-library-controller

**Comment by ogrisel** [comment]
BTW, is there an issue somewhere that gives motivation for the filename / symbol renaming? If found #25505 that upgrades the numpy build system to download the library from pypi.org but as far as I understand, both numpy and scipy still ship their own copies of openblas, [scipy-openblas32](https://pypi.org/project/scipy-openblas32)/[](https://pypi.org/project/scipy-openblas64) is not meant to be a shared runtime dependency but rather a pre-built artifact vendored as build time by each projet.

**Comment by mattip** [comment]
The plan is to get SciPy to a point where it can use the same wheel at build time as NumPy. The decision to prefix the symbols with `scipy_` was made when we thought we could use the wheel as a runtime dependency, which would mean the symbols are loaded globally. Using the runtime wheel is waiting for improvements in the sdist/binary compatibility: there is currently no way to specify that scipy_openblas is a runtime dependency of the binary NumPy wheels we build without also specifying it as a dependency of the source distribution.

**Comment by rgommers** [comment]
> Note: threadpoolctl now has a pluggable controller system, so numpy could ship its own library backend:

NumPy itself (excluding BLAS calls) is always single-threaded. So this is probably not useful? We can't deal with the threading behavior of any underlying BLAS library, that's already in the `threadpoolctl` BLAS support and pretty complex. So my impression is still that all we need here is a more reliable way to tell `threadpoolctl` if we're using a vendored `libopenblas`.


> The decision to prefix the symbols with `scipy_` was made when we thought we could use the wheel as a runtime dependency,

To add to that: when trying the initial non-prefixed library, we very quickly ran into symbol name conflicts. For example, using `numpy` from conda-forge (which will rely on `libblas` with default symbol names) and then building `scipy` against `scipy-openblas32` will yield conflicts between the two BLAS libraries. 

See https://github.com/scipy/scipy/issues/19381 for more detail.

> is not meant to be a shared runtime dependency but rather a pre-built artifact vendored as build time by each project.

As Matti said, it is meant for that. Packaging standards/assumptions are getting in the way though. We are actively discussing that on the packaging Discourse right now - here is the most relevant explanation of the issue: https://discuss.python.org/t/enforcing-consistent-metadata-for-packages/50008/32 (and I need to reply to that thread again asap).

**Comment by ogrisel** [comment]
> NumPy itself (excluding BLAS calls) is always single-threaded. So this is probably not useful? We can't deal with the threading behavior of any underlying BLAS library, that's already in the threadpoolctl BLAS support and pretty complex. So my impression is still that all we need here is a more reliable way to tell threadpoolctl if we're using a vendored libopenblas.

I meant that if numpy wants to take control in the way threadpoolctl access its vendored OpenBLAS is possible for numpy to register a dedicated OpenBLAS controller into threadpoolctl (e.g. at numpy import time). I do not necessarily recommend it, but it's technically possible. However, I think I would rather evolve the default openblas controller provided in threadpoolctl by following the flexible naming approach you suggested in https://github.com/joblib/threadpoolctl/pull/175#issuecomment-2046590229.

**Comment by rgommers** [comment]
Thanks for explaining, makes sense now. And I agree with your assessment.
