### ISSUE TITLE
BUG: random.Generator.choice not random when size=len, no weights provided, and replace and shuffle are both false

### ISSUE THREAD

**Issue by adriancollister** [numpy/numpy#26254]
### Describe the issue:

With the following inputs, `random.Generator.choice` returns the input list unmodified:
- a=[a list]
- size=len(a)
- replace=False
- shuffle=False

I expected to be returned all the elements of the input list in random order. If I set `shuffle=True`, then I get my desired behaviour. But also, if I pass a set of uniform weights to `p` and leave `shuffle=False` I _also_ get my desired behaviour.

So, in summary, I'm really confused about the meaning of the `shuffle` parameter, and don't understand when I should consider setting it to `False`. The docs imply the consideration is purely one of performance, and don't give any explanation of the effect on the actual results.

### Reproduce the code example:

```python
import numpy as np
a = [2, 1, 0, 3, 4, 5]
rng = np.random.default_rng()

# Always prints '[2 1 0 3 4 5]'
print(rng.choice(a=a, size=len(a), replace=False, shuffle=False))

# Output varies on each execution.
p = [1 / len(a)] * len(a)
print(rng.choice(a=a, size=len(a), replace=False, p=p, shuffle=False))
```

### Python and NumPy Versions:

1.26.3
3.11.8

### Context for the issue:

I can workaround this by setting `shuffle=True`, or by providing explicit weights, so modifying the current behaviour does not need to be a priority. I would more importantly like to understand better whether this behaviour is intended, and how to reason about the effect of the `shuffle` parameter.

**Comment by eendebakpt** [comment]
The shuffle parameter can be set to `False` if you do not care about the order of the generated choices. For example when selecting two items from `[0, 1, 2]` the choices `(0, 1)` and `(1, 0)` are different, but if you do not care about the order then  `(0, 1)` and `(1, 0)` are equivalent.

An example:
```
import numpy as np
a = [0, 1, 2,]

print('-- shuffle=True --')
for ii in range(10):
    print(rng.choice(a=a, size=2, replace=False, shuffle=True))
    
print('-- shuffle=False --')
# a bit faster, but the two selected items will not be in random order 
for ii in range(10):
    print(rng.choice(a=a, size=2, replace=False, shuffle=False))
```
Output:
```
-- shuffle=True --
[2 1]
[2 1]
[0 1]
[1 0]
[1 0]
[0 2]
[1 0]
[0 1]
[2 0]
[2 1]
-- shuffle=False --
[1 2]
[1 2]
[0 1]
[0 2]
[0 1]
[1 0]
[0 2]
[1 0]
[0 1]
[1 0]
```
Note that in the second set of choices the order is not random (none of the generated choices starts with the value 2).

The generated choices with `shuffle=False` are random however, if you discard the order of the elements. Another example:
```
import numpy as np

N=100_000
x=np.zeros(N, dtype=object)
for jj in range(N):
    x[jj] = rng.choice(a=a, size=2, replace=False, shuffle=True).tolist()
print(np.unique(x, return_counts=True))

x=np.zeros(N, dtype=object)
for jj in range(N):
    x[jj] = rng.choice(a=a, size=2, replace=False, shuffle=False).tolist()
print(np.unique(x, return_counts=True))

# generate choices, but sort them so the order is discarded
N=100_000
x=np.zeros(N, dtype=object)
for jj in range(N):
    x[jj] = sorted(rng.choice(a=a, size=2, replace=False, shuffle=True).tolist())
print(np.unique(x, return_counts=True))

x=np.zeros(N, dtype=object)
for jj in range(N):
    x[jj] = sorted(rng.choice(a=a, size=2, replace=False, shuffle=False).tolist())
print(np.unique(x, return_counts=True))
```
Output
```
(array([list([0, 1]), list([0, 2]), list([1, 0]), list([1, 2]),
       list([2, 0]), list([2, 1])], dtype=object), array([16795, 16484, 16786, 16780, 16634, 16521], dtype=int64))
(array([list([0, 1]), list([0, 2]), list([1, 0]), list([1, 2])],
      dtype=object), array([16733, 33365, 16596, 33306], dtype=int64))
(array([list([0, 1]), list([0, 2]), list([1, 2])], dtype=object), array([33174, 33297, 33529], dtype=int64))
(array([list([0, 1]), list([0, 2]), list([1, 2])], dtype=object), array([33154, 33481, 33365], dtype=int64))
```
Note that the last two entries have the same statistics (each sorted tuple `(i, j)` is equally likely).

**Comment by adriancollister** [comment]
Ah! Thank you, that makes perfect sense now. So the apparent randomness when passing explicit uniform weights with `shuffle=False` should not be relied on, and for my use case I should definitely always have `shuffle=True`.

Many thanks for the clarification.
