### ISSUE TITLE
Where is `numpy=2.0.0rc1` on conda-forge?

### ISSUE THREAD

**Issue by valeriupredoi** [numpy/numpy#26271]
Hi folks, silly question here, but where is the new RC on conda-forge? Installation via environment file and adding `conda-forge/label/dev` as channel to the channels list didn't find it, manual install with `mamba install -c conda-forge/label/dev numpy==2.0.0rc1` didn't find it either, it's not in the main `conda-forge/linux-64` either, and the only way I could install it was with the very peasantly `mamba install https://anaconda.org/conda-forge/numpy/2.0.0rc1/download/linux-64/numpy-2.0.0rc1-py39h8eeae49_0.conda` but that's no bueno coz I'd like to test against multiple Pythons in a Github Action. Cheers muchly! BTW I see the thing was downloaded only 4 times, so I guess others are not finding it either :grin: Cheers again, and have a good weekend! :beer:

**Comment by ngoldbaum** [comment]
According to https://github.com/conda-forge/numpy-feedstock/issues/311#issuecomment-2029071785, the incantation you need is

```
conda install conda-forge/label/numpy_dev::numpy=2.0.0rc1
```

**Comment by valeriupredoi** [comment]
Ah good man, cheers much @ngoldbaum - shall try that 🍺

**Comment by rgommers** [comment]
Thanks for the question and the answer - resolved, so will close this.

**Comment by valeriupredoi** [comment]
very many thanks, folks! Problem solved :beer:
