### ISSUE TITLE
ENH: make `printoptions` a true context var

### ISSUE THREAD

**Issue by mtsokol** [numpy/numpy#26314]
### Proposed new feature or change:

Hi!

One of possible enhancements is to make `printoptions` use a context var. Right now it uses a `_format_options` dict defined in the `arrayprint` module - context var will give context-local state.

WDYT?

**Comment by ngoldbaum** [comment]
Yikes! I guess the current implementation isn't thread-safe then.

Do we want to allow thread-local print options? That seems strange to me. Better to make it like the `errstate` and make it a global setting that can only be entered once.

**Comment by seberg** [comment]
Heh, I thought there was an old issue about this somewhere, but didn't find it.  In any case: any context manager should be backed by one (or maybe more) context variables to make sure it is truly context safe. And I would expect that to make the code a bit nicer as well.

**Comment by mtsokol** [comment]
Resolved in https://github.com/numpy/numpy/pull/26846
