### ISSUE TITLE
Query: threading and threadpoolctl with main branch

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#26318]
I'm helping a downstream project adapt to NumPy changes, and noticed this:

```python
from threadpoolctl import threadpool_info, threadpool_limits
import numpy as np

for entry in threadpool_info():
    print(entry["num_threads"])
    # 2.1.0.dev0 built from source locally on x86_64 Linux prints: 1 
    # 2.0.0rc1 from PyPI doesn't print anything
    # 1.26.4 from PyPI prints: 32

with threadpool_limits(2):
    for entry in threadpool_info():
        print(entry["num_threads"])
        # 2 with NumPy 1.26.4 on PyPI
        # 2.0.0rc1 from PyPI doesn't print anything
        # 2.1.0.dev0 built from source locally on x86_64 Linux prints: 1 
```

I think what is happening is that the downstream library is using the latest stable release of `threadpoolctl` and assuming that `threadpool_limits(2)` (or similar) will genuinely provide threading control at the level of the provided integer number of threads, which I might naively guess would be reasonable. Is this something still being worked on related to nogil/free-threading business, or some simpler explanation of what is going on here?

Should the advice be not to rely on that integer value of the threadpool limit being hard-enforced moving forward?

**Comment by ngoldbaum** [comment]
I’m not aware of any recent numpy changes that would cause this. The nogil work is all ifdef’d behind build-time flags so I don’t think it’s related.

**Comment by seberg** [comment]
Seems that this is the discussion in https://github.com/numpy/numpy/issues/26240, so I guess it'll be resolved (not sure if by us or by threadpoolctl).

**Comment by rgommers** [comment]
https://github.com/joblib/threadpoolctl/pull/175 will resolve this.

> Should the advice be not to rely on that integer value of the threadpool limit being hard-enforced moving forward?

It should be made reliably, that's the whole point of `threadpoolctl`. And the PR linked above is already approved, so it should be ready before the final numpy 2.0 release.

It looks like this is under control. If it turns out to be necessary, we should add some info that is more reliable to query. In the end this is a practical problem for `numpy` users, and our official response is "use `threadpoolctl` for this".

**Comment by rgommers** [comment]
I'll add `threadpoolctl` to the 2.0 ecosystem tracking issue now.
