### ISSUE TITLE
BUG: Inconsistent behavior in basic and advanced combined indexing

### ISSUE THREAD

**Issue by hidetatz** [numpy/numpy#26323]
### Describe the issue:

I apologize if this is not actually a bug.

I am puzzled by the inconsistent behavior when indexing an ndarray with a mixture of slices and lists.

My understanding is that when using mixed slice and list indexing, the values should be retrieved by looping over the latter elements of the tuple passed as the index.

For example, consider the following code:

```
x = np.arange(72).reshape(4, 3, 2, 3)
y = x[0:2, 0:2, [0, 1], 1]
print(y.flatten(), y.shape)
```

The above code outputs `(array([ 1, 4, 7, 10, 19, 22, 25, 28]), (2, 2, 2))` .

Examining the indices of each value, we get:

```
1: x[0, 0, 0, 1]
4: x[0, 0, 1, 1]
7: x[0, 1, 0, 1]
10: x[0, 1, 1, 1] 
19: x[1, 0, 0, 1]
22: x[1, 0, 1, 1]
25: x[1, 1, 0, 1]
28: x[1, 1, 1, 1]
```

Looking at this, we can infer that it loops over the first element ( `0:2` ), then within that it loops over the second element ( `0:2` ), and further within that it loops over the third element ( `[0, 1]` ).

In pseudocode, it would look like this:

```
indices = []
for i in 0:2 {
    for j in 0:2 {
        for k in [0, 1] {
            for l in 1 {
                indices.append((i, j, k, l))
            }
        }
    }
}
```

However, the following code appears inconsistent with this behavior:

```
x = np.arange(288).reshape(4, 4, 3, 2, 3)
y = x[0:2, [0, 1], 0:1, [1, 0], 1]
print(y.flatten(), y.shape)
```
This code outputs `(array([ 4, 76, 19, 91]), (2, 2, 1))` 

The indices of each value are:

```
4: [0, 0, 0, 1, 1]
76: [1, 0, 0, 1, 1]
19: [0, 1, 0, 0, 1]
91: [1, 1, 0, 0, 1]
```

Looking at this, the first slice 0:2 loops before the fourth (and second) element pair.

Why does this behavior occur? I could not find any documentation that describes this, as far as I searched. I'm not sure if this is a bug, but if it's not, could you please explain the order in which the values are retrieved?

### Reproduce the code example:

```python
import numpy as np

# from shape and value, extract the value's index as [x, y, z] form.
def toidx(shp, target):                                                     
    def product(args):                                                      
        r = 1                                                               
        for arg in args:
            r *= arg                                                        
        return r                                                            

    strides = []
    for i in range(len(shp)):                                               
        strides.append(product(shp[i+1:]))                                  
                
    idx = []    
    sum = 0     
    for i in range(len(shp)):                                               
        for j in reversed(range(shp[i])):                                   
            if sum + strides[i] * j > target:                               
                continue                                                    
                
            idx.append(j)                                                   
            sum += strides[i] * j                                           
            break
    return idx                                                              

def printdataidx(data, shape):
    for d in data:
        print(f"{d}: {toidx(shape, d)}")

x = np.arange(72).reshape(4, 3, 2, 3)
y = x[0:2, 0:2, [0, 1], 1]
print(y.flatten(), y.shape)
printdataidx(y.flatten(), x.shape)

x = np.arange(288).reshape(4, 4, 3, 2, 3)
y = x[0:2, [0, 1], 0:1, [1, 0], 1]
print(y.flatten(), y.shape)
printdataidx(y.flatten(), x.shape)
```

### Error message:

```shell
No error message
```

### Python and NumPy Versions:

1.26.4
3.11.6 (main, Dec  3 2023, 11:02:17) [GCC 11.4.0]

### Runtime Environment:

```
[{'numpy_version': '1.26.4',
  'python': '3.11.6 (main, Dec  3 2023, 11:02:17) [GCC 11.4.0]',
  'uname': uname_result(system='Linux', node='mini', release='6.5.0-27-generic', version='#28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/hidetatz/whale/.env/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None
```

**Comment by thalassemia** [comment]
This is consistent with the current documentation about combining basic and advanced indexing that you linked. Your first example has a single advanced index which means the indexing operations are independent. You can replace `[0, 1]` with `0:2` and get the exact same result, with each index applying in order.

However, in your second example, you have two advanced indices separated by a slice. The documentation states that in this case:

> [T]he dimensions resulting from the advanced indexing operation come first in the result array, and the subspace dimensions after that.

Therefore, the first loop operates on the pair of advanced indices `[0,1]` and `[1,0]` for the second and fourth axes. Then comes the first axis `0:2`, the third axis `0:1`, and the last axis `1`.

In Python:

```python
indices = []
for second, fourth in zip([0, 1], [1, 0]):
    for first in range(0, 2):
        for third in range(0, 1):
            for last in [1]:
                indices.append((first, second, third, fourth, last))
```

**Comment by seberg** [comment]
Closing, the docs indeed explain this, e.g. [here](https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing), [this NEP draft](https://numpy.org/neps/nep-0021-advanced-indexing.html#outer-indexing) might be interesting, but I haven't thought about it a long time.  [`np.ix_`](https://numpy.org/doc/stable/reference/generated/numpy.ix_.html) may also be.

**Comment by hidetatz** [comment]
Thank you, I also made sure the explained behavior on my side. Thank you for your clear answer @thalassemia !
