### ISSUE TITLE
BUG: Numpy 1.26.4 np.dot() doesn't return valid number

### ISSUE THREAD

**Issue by VincentSon** [numpy/numpy#26344]
### Describe the issue:

Numpy 1.26.4 np.dot() doesn't return correct number 

### Reproduce the code example:

```python
import numpy as np
vector1 = np.array([0, 0, 175702, 173294])
print(np.dot(vector1, vector1))
# print out 772461096, should be 60902003240
```

### Python and NumPy Versions:

1.26.4
3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]

### Context for the issue:

I tried on different version of Numpy and Python on the same machine and the result was correct. Not sure why 1.26.4 is bugging on me.
1.21.5
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

**Comment by andyfaff** [comment]
You are creating an integer array in this example. If you create the `vector` array as `dtype=np.int32` the dot product overflows what an int32 can hold. If you create the vector array as `np.int64` you'll get the right answer.

**Comment by andyfaff** [comment]
In numpy 2.0 the default integer type will be 64 bit on all platforms. Previously it was platform dependent and equal to the C `long` type.

**Comment by VincentSon** [comment]
Thank you, A little strange it doesn't have warning for the overflow.

**Comment by charris** [comment]
> A little strange it doesn't have warning for the overflow.

We call it modular arithmetic :)
