### ISSUE TITLE
DOC: tril_indices triu_indices order

### ISSUE THREAD

**Issue by benjamin-lieser** [numpy/numpy#26350]
### Issue with current documentation:

The order of indices in not specified which makes it hard to rely on.

### Idea or request for content:

Document the current behavior and make it part of the function contract:

"The indices returned are sorted first with respect to the row and then the column"

**Comment by ajayjanapareddi** [comment]
Hi,
Although it may be obious, I think updating the docs seems like a valid suggestion for this. I will raise a PR shortly.
