### ISSUE TITLE
BUG: When iterating over a bytes array, empty bytes is returned as empty string

### ISSUE THREAD

**Issue by olebole** [numpy/numpy#26375]
### Describe the issue:

When iterating over a bytes array, normal bytes strings are given as bytes, but the empty bytes is returned as empty string.

### Reproduce the code example:

```python
>>> import numpy as np
>>> for item in np.char.array([b"foo", b"bar", b""]):
...     print(type(item))
<class 'bytes'>
<class 'bytes'>
<class 'str'>
```

### Python and NumPy Versions:

Python 3.11.9
Numpy 1.24.2

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue, that is definitely a bug.

NumPy folks, the problem is here:

https://github.com/numpy/numpy/blob/aa0cc043d1fe51e61024842b21905e11a2a4cee6/numpy/_core/defchararray.py#L578-L588

The line

```
               val = ''
```

needs to be changed to cast the empty string to the dtype of the array.  One way to do that would be to write it as

```
                val = self.dtype.type().item()
```

@olebole, we can fix this, but in case you haven't already, take a look at the docstring of the `numpy.char` module and the `numpy.char.array` class.  You'll find:

```
.. note::
   The `chararray` class exists for backwards compatibility with
   Numarray, it is not recommended for new development. Starting from numpy
   1.4, if one needs arrays of strings, it is recommended to use arrays of
   `dtype` `object_`, `bytes_` or `str_`, and use the free functions
   in the `numpy.char` module for fast vectorized string operations.
```

and

```
.. note::
   This class is provided for numarray backward-compatibility.
   New code (not concerned with numarray compatibility) should use
   arrays of type `bytes_` or `str_` and use the free functions
   in :mod:`numpy.char` for fast vectorized string operations instead.
```

respectively.  In other words, it is not recommended for new code.  Just FYI.

**Comment by WarrenWeckesser** [comment]
I'm note sure why the inner `if`-statement of the `__getitem__` method is necessary. If I change the method to

```
    def __getitem__(self, obj):
        val = ndarray.__getitem__(self, obj)

        if isinstance(val, character):
            return val.rstrip()

        return val
```

all the tests pass, and @olebole's example works as expected.  I haven't looked at the `chararray` stuff too much, so I might be missing some subtlety (Chesterton's fence and all that).

**Comment by WarrenWeckesser** [comment]
Heh, that's more or less what it used to be 18 or so years ago:

https://github.com/numpy/numpy/blob/779dc154b799a6660f7f60ef50c09fc445329999/numpy/core/defchararray.py#L44-L48

@teoliphant added the additional code, but I don't know what he was fixing by doing so.

**Comment by olebole** [comment]
@WarrenWeckesser my example was extracted from difficulties I had with `astropy.io.fits`, not my own code. Up to that I even didn't know that `chararry` exists. And I suspect, the Astropy code that uses `chararray` historically evolved from `pyfits`, which had the first implementation with `numarray`.
From the note I take that however `chararray` is not deprecated, right? Or shall I ask in `astropy` to update the code at some point?
Cc: @saimn as `astropy.io.fits` maintainer

**Comment by seberg** [comment]
FWIW, I would be up for just removing that inner if.  The best idea is that it works around a bug elsewhere (or is even just a try to find a bug).
In other words: I don't think it makes sense to worry about Chesterton's fence and try to understand some 20 year old reason that may never have existed.

**Comment by pllim** [comment]
`astropy.io.fits` is complicated. I don't see us dropping chararray overnight... Thanks for the help!

**Comment by WarrenWeckesser** [comment]
>  I would be up for just removing that inner if. 

OK, let's try it: https://github.com/numpy/numpy/pull/26384
