### ISSUE TITLE
BUG: numpy.sort with order and kind=stable is not stable

### ISSUE THREAD

**Issue by iyz91** [numpy/numpy#26387]
### Describe the issue:

When sorting a structured array with a specified key and kind=stable the returned array is not stable. The returned array should be stable, i.e. rows with the same value for specified key should be kept in same relative order in returned array.

### Reproduce the code example:

```python
import numpy as np

dtype = np.dtype([
  ('a', np.float64),
  ('b', np.float64)
])

x = np.array([(0, 2), (0, 1), (0, 3)], dtype=dtype)

y = np.sort(x, order="a", kind="stable") // Incorrect, should be same as x
```

### Python and NumPy Versions:

numpy: 1.26.4
python: 3.12.2

### Runtime Environment:

[
  {
    'numpy_version': '1.26.4',
    'python': '3.12.2 (main, Apr  2 2024, 12:08:40) [GCC 13.2.1 20230801]',
    'uname': uname_result(system='Linux', node='XXXX', release='6.8.4-arch1-1', version='#1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 00:14:23 +0000', machine='x86_64')
  },
 {
   'simd_extensions': {
     'baseline': ['SSE', 'SSE2', 'SSE3'],
     'found': ['SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2'],
     'not_found': ['AVX512F', 'AVX512CD', 'AVX512_KNL', 'AVX512_KNM', 'AVX512_SKX', 'AVX512_CLX', 'AVX512_CNL', 'AVX512_ICL']
   }
  }
]

### Context for the issue:

Basic operation that could be used in a lot of contexts. Stable sorting should be stable.

**Comment by charris** [comment]
What did you expect. The documentation says
```
not all fields need be specified,
but unspecified fields will still be used
```
In other words, none of the entries are identical. If you only want to sort on the first row, look at lexsort.

**Comment by iyz91** [comment]
Apologies, I misunderstood. Thanks for the clarification.
