### ISSUE TITLE
BUG: numpy.strings.str_len fails on null object

### ISSUE THREAD

**Issue by lithomas1** [numpy/numpy#26389]
### Describe the issue:

numpy.strings.str_len should put ``np.nan`` when in that position when encountering an string array with a missing value, but instead errors with

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The length of a null string is undefined
```

### Reproduce the code example:

```python
import numpy as np
a = np.array(["a", "b", None], dtype=np.dtypes.StringDType(na_object=None))
np.strings.str_len(a)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The length of a null string is undefined
```

### Python and NumPy Versions:

'2.1.0.dev0+git20240424.f8392ce'

**Comment by ngoldbaum** [comment]
This is by design. What would be a sensible value for the length of a null string? Note that numpy doesn't have support for missing integer values.

Also, separately, none of the string ufuncs support `None` as a NaN-like NA object that passes through operations.
