### ISSUE TITLE
[Question] Why are memmaps on X bit systems limited to a X-1 bit index?

### ISSUE THREAD

**Issue by Semnodime** [numpy/numpy#26394]
When attempting to memory-map a 16 EiB file as array of dtype np.uint8, a ValueError is raised.
To index the file, a np.uint64 is sufficient (exactly).
While the underlying filesystem supports managing files of the required size, numpy on my x86_64 system does not.
```
arr= np.memmap(out_file, shape=2**64, mode='w+')
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/numpy/core/memmap.py", line 254, in __new__
    fid.seek(bytes - 1, 0)
ValueError: cannot fit 'int' into an offset-sized integer
```

During investigation of the issue, I noticed this line:
https://github.com/numpy/numpy/blob/ca58cde7de282a485ca12e5f2582a64fb2e52113/numpy/_core/memmap.py#L121
I assumed numpy to support file indices of the maximum unsigned integer of the platform, though it is only half of it:

```math
 \begin{array}{l}
assumed:\ 0\rightarrow \left( 2^{X} -1\right)\\
instead:\ 0\ \rightarrow \left( 2^{X-1} -1\right)
\end{array}
```
**why?**

**Comment by seberg** [comment]
Dunno, that is a file system operation and in Python after all and not in NumPy at all, maybe multiple seeks actually can do it...

But NumPy (like Python) is limited to *signed* integers for sizes and indexing for various reasons so the size *must* fit into that.  So I guess you will have to make due with a size of a mere `8EiB - 1Byte` per array.  Even if NumPy wasn't I would be very surprised if your systems virtual memory points aren't smaller than 64bit as well.

I honestly can't tell if this is a serious question or not, in practice I would think that your virtual memory space is anyway much smaller than what NumPy would in theory allow you to do.
