### ISSUE TITLE
ENH: Add context management for np.seterr

### ISSUE THREAD

**Issue by hjenryin** [numpy/numpy#26408]
### Proposed new feature or change:

The current way (according to [1.26 doc](https://numpy.org/doc/stable/reference/generated/numpy.seterr.html)) of setting and resetting error is
```
old_settings = np.seterr(all='ignore')  #seterr to known value
np.seterr(over='raise')
{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
np.seterr(**old_settings)  # reset to default
```
This may be tedious and not elegant when we need to suppress the error for some certain lines, for example, `np.nan_to_num(a/b)` as we need to suppress `divide` here. 

I think it would be way more elegant to use `with` statement here, which should be able to be implemented with some simple changes.

An ideal result would be like:
```
with np.seterr(divide='ignore'):
    np.nan_to_num(a/b) # no warning

a/0 # still warn
```

**Comment by rkern** [comment]
[numpy.errstate](https://numpy.org/doc/stable/reference/generated/numpy.errstate.html) is what you are looking for.

**Comment by hjenryin** [comment]
Aha, sorry I missed it. Thanks a lot!
