### ISSUE TITLE
ENH: Support various writing mode for numpy.savetxt()

### ISSUE THREAD

**Issue by xinjie-h** [numpy/numpy#26407]
### Proposed new feature or change:

For [numpy.savetxt()](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html) function, is it possible to add an argument _mode_ to support various ways on writting data? That could give user control to choose from appending / overwritting data to the target file.

If this makes sense, I'm willing to give a try on this feature contribution.

Thanks in advance for any comments, guidance.

**Comment by ngoldbaum** [comment]
Note how the docstrings for `savetxt` say that `fname` can be a file handle, so you can do something like:

```
with open('file_to_append_to.txt', 'a') as f:
    np.savetxt(f, array)
```

Closing but let us know if for some reason passing a file handle to savetxt doesn't work for you.
