### ISSUE TITLE
ENH: @ operator differs from the convention for tensor dot 

### ISSUE THREAD

**Issue by WenyinWei** [numpy/numpy#26438]
### Describe the issue:

Hi, the current `@` operator has `np.matmul` function underlying, which means if $A$ or $B$ is multi-dimensional, `C = A@B` is equivalent to $C_{ijm} = \sum_{k} A_{ijk} B_{ikm}$. However, for multi-dimensional array, is would be more convenient and intuitive if it can somewhat imitate the behavior of tensor dots like using `C = A@@B` to calculate $C_{ij} = \sum_{m,n} A_{imn} B_{nmj}$. Is it possible to overload functions for such `@@@...` operators?

### Reproduce the code example:

```python
import numpy as np
testA, testB = np.random.rand(5,3,4), np.random.rand(5,4,3)
np.allclose( testA @ testB, np.einsum("ijk,ikm->ijm", testA, testB  )  )
```

### Python and NumPy Versions:

1.26.4
3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

**Comment by ngoldbaum** [comment]
See [numpy.vecdot](https://numpy.org/devdocs/reference/generated/numpy.vecdot.html). Of course that doesn't help someone wanting to use `@` like you'd like, but changing it would also almost certainly break user code so there would need to be a deprecation period, a period where using `@` in this way is a hard error, and then finally `@` is an alias for `vecdot`. Is the change worth the disruption?

**Comment by seberg** [comment]
`@` was proposed in [the PEP](https://peps.python.org/pep-0465/) to be useful for stacks of matrices, I don't think we should touch it and I would suspect that the stack of matrices use case is more common anyway.

Changing/adding operators in Python will not be easy, matmul was one of the few things that happened.

**Comment by ngoldbaum** [comment]
Also see np.einsum, which lets you write the contraction you want explicitly using Einstein notation. Closing since there's nothing really numpy can do to add more operators to Python and the operation the reporter was looking for is possible with a different spelling.
