### ISSUE TITLE
Unexpected behavior of `nanpercentile` with weighted missing values

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#26455]
### Issue with current documentation:

#24254 by @lorentzenchr introduced the possibility to pass non-negative weights to `np.nanpercentile`.

However, the influence of the weights of nan values is not necessarily intuitive to grasp. In particular, changing the weights of the nan values impacts the results:

```python
>>> import numpy as np
>>> np.nanpercentile([1, np.nan, 2, 3], 50, method="inverted_cdf")
np.float64(2.0)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 1.0, 1.0, 1.0], method="inverted_cdf")
array(2.)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 0., 1.0, 1.0], method="inverted_cdf")
array(1.)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 2., 1.0, 1.0], method="inverted_cdf")
array(2.)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 3., 1.0, 1.0], method="inverted_cdf")
array(3.)
>>> np.nanpercentile([1, np.nan, 2, 3], 50, weights=[1.0, 1e200, 1.0, 1.0], method="inverted_cdf")
array(3.)
```

This seems to contradict the first line of the docstring of that function:

> Compute the qth percentile of the data along the specified axis, while ignoring nan values.

However I am not sure if it's a bug or a feature. I assume that giving non-zero weights to missing values might have some mathematical meaning? If this is intended, I think the docstring should be updated to explain the expected behavior in this case.

However I do not really see why weighing more the `np.nan` values would shift the median to the right. In the above snippet, `np.nan` behaves like the largest non-missing values in the sample which seems quite arbitrary to me, hence the feeling that this might be a bug instead of an intended behavior. Maybe the weights should then be renormalized after trimming the weights of missing values to fix the problem.

### Idea or request for content:

Also note that the return type of this function is influenced by whether we pass the `weights` kwarg (the return value is 0d `ndarray`) or not (the return value is an instance of `np.float64`).

I think this is a minor bug on its own. I can open a dedicated issue if needed.

**Comment by ogrisel** [comment]
Thinking a bit more about this, I think I would have possibly, expected the following logical equivalence to hold in presence of weighted missing values:

```python
non_missing = np.logical_not(np.isnan(a))

np.testing.assert_allclose(
    np.nanpercentile(a, w, method="inverted_cdf"),
    np.nanpercentile(a[non_missing], w[non_missing] / w.sum(), method="inverted_cdf"),
)
```

This way if missing values have very large weights compared to non missing values, this would would make their weights "closer" to one another but would not shift the median closer of unit weighted non-missing values either to the right or the left when reweighing the missing values.

Although, I am not 100% sure if the ` / w.sum()` is justified or not.

**Comment by seberg** [comment]
Right, I think it should just filter non-missing ones.

> Although, I am not 100% sure if the  / w.sum() is justified or not.

Part of the reason to only allowing `method="inverted_cdf"` is that the sum of weights shouldn't matter to the result.
