### ISSUE TITLE
ENH: Start building WASM wheels against newer Pyodide (version 0.26.0)

### ISSUE THREAD

**Issue by agriyakhetarpal** [numpy/numpy#26467]
## Description

Based on https://github.com/pyodide/pyodide/discussions/4751 and https://github.com/pyodide/pyodide/issues/4713, a release for Pyodide 0.26.0 (Emscripten 3.1.52 + Python 3.12.1) should hit by Monday; a few days from now at the time of writing. This issue is being opened to propose bumping the configuration for the NumPy out-of-tree builds in `emscripten.yml` and build against the newer versions because the ABI is going to break. This is not an urgent or pressing issue, but would be a worthwhile addition to NumPy – this is because the Pyodide job has been succeeding for some time now without hiccups and it would be great to test the Scientific Python in general against the latest Pyodide version(s) as soon as they come out with general availability.

I am unsure if this is needed, but I would also suggest running a job against the Pyodide pre-releases and release candidates that are available on GitHub Releases (maybe not on PR builds, but scheduled, similarly to the nightlies).

## Proposed implementation

1. Update `emscripten.yml` to use the newer Pyodide version
2. Fix any errors that arise from the build system and any failures in test cases, adding xfails/skips and new tests if necessary

## Additional context

Since I was the one who helped out on gh-25894 a while back, I would be happy to be assigned to this by a project maintainer and subsequently work on this at a suitable time within the month.

xref some (recent and relevant) previous issues and PRs:

gh-24603
gh-25894
gh-26134
gh-26164

(and the greater goal with these builds, which is gh-25969).

**Comment by rgommers** [comment]
Yes please! Upgrading to a newer version of Pyodide is always welcome.

> I am unsure if this is needed, but I would also suggest running a job against the Pyodide pre-releases and release candidates that are available on GitHub Releases (maybe not on PR builds, but scheduled, similarly to the nightlies).

I'd prefer not to do that, that's too much overhead and isn't likely to catch issues of interest.
