### ISSUE TITLE
BUG: `newbyteorder` docs and typing don't agree on allowed types

### ISSUE THREAD

**Issue by dstansby** [numpy/numpy#26473]
### Describe the issue:

For `numpy.dtype.newbyteorder`, https://numpy.org/doc/stable/reference/generated/numpy.dtype.newbyteorder.html lists allowable arguments as:

- ‘S’ - swap dtype from current to opposite endian
- {‘<’, ‘little’} - little endian
- {‘>’, ‘big’} - big endian
- {‘=’, ‘native’} - native order
- {‘|’, ‘I’} - ignore (no change to byte order)

but the typing doesn't allow 'little', 'big', or 'native':

https://github.com/numpy/numpy/blob/67257a7447328358831a53a8a6e697a94c97104c/numpy/__init__.pyi#L639

Either the docs should be updated to match the typing, or the typing updated to match the docs.

### Reproduce the code example:

```python
import numpy as np
a = np.array([1, 2, 3])
a.dtype.newbyteorder("little")
```

### Python and NumPy Versions:

1.26.4
3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]

**Comment by rgommers** [comment]
Agreed, looks like the set of accepted literals missed this by accident. Updating the type annotation in gh-26480.
