### ISSUE TITLE
BUG:  i9-13900K (corner case bug: import numpy reboots).

### ISSUE THREAD

**Issue by ilaks2** [numpy/numpy#26470]
### Describe the issue:

We have several i9-13900K and 14900K compute servers setup to run heavy computation and saw an inexplicable bug that shows up only on this single i9-13900K cpu.   The motherboard was gigabyte B760M DS3H AX and we have several identical machines all with 64GB or 128GB DDR5.  POWER Supply is 500W.  There is no external GPU.

On this one CPU only, when we run import numpy in python3, the machine would immediately hang and reboot.

The curious part is that if we swap in another i9-13900K, it works.   If we take the problem i9-13900K onto a working system, that system now reboots on import numpy.

I'm returning this new cpu to get a replacement, but I wonder if intel or anyone else wants to do a fault analysis on what's going on with this corner case chip.   Also, has anyone else seen this on anywhere?   

### Reproduce the code example:

```python
import numpy  #will hang and reboot on this i9-13900K
```

### Error message:

```shell
immediate reboot
```

### Python and NumPy Versions:

python : 3.10.12
numpy : 1.26.4

### Context for the issue:

It seems this is a specific corner case i9-13900K bug.   I'm reporting it just in case others have seen similar behavior on their i9-13900K.   So far this is the only one we've seen from 8 basically identical machines.

**Comment by vxst** [comment]
Nothing in user mode program can cause a reboot without privilege. It's a faulty CPU and NumPy is not the place to fix hardware error.

**Comment by rgommers** [comment]
Agreed, it doesn't sound like there's anything we can or should do inside the numpy code base.

> I'm returning this new cpu to get a replacement, but I wonder if intel or anyone else wants to do a fault analysis on what's going on with this corner case chip.

Cc @r-devulap in case this is useful/interesting to Intel.

**Comment by r-devulap** [comment]
yeah sorry, nothing I can do about it either :)
