### ISSUE TITLE
BUG: Array with uint dtype cannot be multplied by negative Python int.

### ISSUE THREAD

**Issue by rmjarvis** [numpy/numpy#26483]
### Describe the issue:

In version 1.26 (and earlier), multiplying an array with unsigned dtype by a negative number would return an array with signed integer dtype.  In version 2.0.0rc2, this is true if the multiplicand is e.g. np.int32 or np.int64, but not a Python int.

It seems to me that either all cases should return a signed integer array or all should raise an OverflowError.  It's unclear which one is intended in the new casting API, but it seems like a bug that these work differently.

### Reproduce the code example:

```python
import numpy as np
a = np.arange(10, dtype=np.uint32)
print(a * np.int32(-1))
print(a * np.int64(-1))
print(a * -1)
```

### Error message:

```shell
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python integer -1 out of bounds for uint32
```

### Python and NumPy Versions:

2.0.0rc2
3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:35:20) [Clang 16.0.6 ]

Note: In version 1.26.4, it prints the same thing all three times.

### Runtime Environment:

```
[{'numpy_version': '2.0.0rc2',
  'python': '3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:35:20) '
            '[Clang 16.0.6 ]',
  'uname': uname_result(system='Darwin', node='Saxophone', release='21.6.0', version='Darwin Kernel Version 21.6.0: Thu Nov  9 00:42:05 PST 2023; root:xnu-8020.240.18.705.10~1/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'neoversen1',
  'filepath': '/Users/Mike/miniforge3/envs/numpy2/lib/python3.12/site-packages/numpy/.dylibs/libscipy_openblas64_.dylib',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]
None
```

**Comment by ngoldbaum** [comment]
Hi, this is discussed in the migration guide [here](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion) and also see [NEP 50](https://numpy.org/neps/nep-0050-scalar-promotion.html). If you don't want to see errors then you should convert to an explicit scalar type and not rely on implicit promotion of python scalars.

**Comment by rmjarvis** [comment]
OK.  So this is an intended anti-feature I guess.  Consider this user surprised.  But I'll change the code to use `np.int64` in such cases I guess.

**Comment by ngoldbaum** [comment]
It's possible the fallout in user code will be too large and we'll need to revert this change. Feedback like this is valuable.
