### ISSUE TITLE
DOC: How to build with PIP and custom Fortran compiler

### ISSUE THREAD

**Issue by Flamefire** [numpy/numpy#26495]
### Issue with current documentation:

The documentation misses how to build & install numpy from source using a custom compiler. There is https://numpy.org/devdocs/building/index.html#building-from-source-to-use-numpy which states the usual workflow `pip install .`

That is missing how to change the compiler, e.g. to use the Intel Fortran compiler instead of the GNU variant.

https://numpy.org/devdocs/f2py/buildtools/distutils.html#extensions-to-distutils states `--fcompiler=<Vendor>` but there is no example on how to use it, especially for installing numpy itself.

We used to do e.g. `python setup.py build --fcompiler=gnu95` but that is deprecated now:
```
  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12.
```

So there doesn't seem to be an option to change the Fortran compiler, when using pip, especially with `--global-option` being ignored by PEP517 builds, see https://github.com/pypa/pip/issues/11859
> WARNING: Ignoring --global-option when building numpy using PEP 517

Additionally the [migration guide](https://numpy.org/devdocs/reference/distutils_status_migration.html#moving-to-setuptools) also mentions that `site.cfg` is only supported by the numpy distutils but we use that a lot, e.g. for specifying FFT & BLAS libraries and e.g. `search_static_first=True`

Is there any option to specify the Fortran compiler to use when building with PIP? If so, is it compatible with earlier numpy versions and which ones?

**Comment by ngoldbaum** [comment]
You can get verbose output from `meson` if you pass `-C'compile-args=-v'` to your `pip install` invocation, which should print out something about the fortran install it finds. Also consider setting `-Cbuilddir=build` so `pip` leaves behind the meson build directory it creates. So your final invocation would look like:

```
python -m pip install -v . -C'compile-args=-v' -C'builddir=build'
```

Numpy itself doesn't use a fortran compiler at build time, so I guess you're talking about an f2py usage?

The numpy docs link to the scipy docs for documentation about selecting compilers, BLAS, and FFT: https://docs.scipy.org/doc/scipy/building/compilers_and_options.html

**Comment by Flamefire** [comment]
> You can get verbose output from meson if you pass -C'compile-args=-v' to your pip install invocation, which should print out something about the fortran install it finds.

> Numpy itself doesn't use a fortran compiler at build time

I'm a bit confused: What is the relevance of the Fortran related output if it isn't used by numpy? You wrote at "build time", which sounds it is used somewhere else. Where?

> so I guess you're talking about an f2py usage?

The code using this was written quite some time ago, so I can only guess. But very likely it is related to f2py. Isn't that used during the numpy build or at least during the tests? Wouldn't that require setting up the correct Fortran compiler?

**Comment by rkern** [comment]
> You wrote at "build time", which sounds it is used somewhere else. Where?

When you use `numpy.distutils` and `f2py` to build some other Fortran-using library. numpy basically bundles (or bundled, as they are now essentially deprecated) a Fortran bindings builder and a build system for use _by other projects_. numpy does not need the Fortran components in order to build itself.

**Comment by ngoldbaum** [comment]
> I'm a bit confused: What is the relevance of the Fortran related output if it isn't used by numpy? You wrote at "build time", which sounds it is used somewhere else. Where?

Sorry, I just wanted to offer some help to get more verbose output from the numpy build to help you understand what's going on better. Didn't mean to confuse.

You probably want this docs page: https://numpy.org/doc/stable/f2py/buildtools/meson.html

You'll likely need to convert whatever `numpy.distutils`-based build you were using before to now use meson. Unfortunately this breakage was forced on us by upstream's removal of distutils in Python 3.12.

**Comment by rgommers** [comment]
To answer the "how do I select a compiler" question: setting an environment variable is easiest (both for building NumPy and for using f2py with its Meson backend):
- `CC` for a C compiler,
- `CXX` for a C++ compiler
- `FC` for a Fortran compiler

**Comment by rgommers** [comment]
I'll close this, since the doc links given higher up contain all the information discussed here. So there is nothing to do here. 

@Flamefire please feel free to continue the discussion if we can help clear up some confusion of course.

**Comment by Flamefire** [comment]
> Numpy itself doesn't use a fortran compiler at build time,

After some back-and-forth with someone who has access to a system where this matters I found the following:
- `python setup.py build [--fcompiler <myFC>]` was used
- without `--fcompiler` numpy-distutils uses the `GnuFCompiler` (not sure how that decision is made though)
- This tries to get the compiler version by parsing the output of `<myFC> --version`
- On failure the superclass expects a result of `None`: https://github.com/numpy/numpy/blob/aad6c9cd1958309110f9892d10b28b1beea9c670/numpy/distutils/fcompiler/__init__.py#L429-L431
- However `GnuFCompiler` throws an error instead: https://github.com/numpy/numpy/blob/aad6c9cd1958309110f9892d10b28b1beea9c670/numpy/distutils/fcompiler/gnu.py#L74

So what would normally just result in [a warning](https://github.com/numpy/numpy/blob/aad6c9cd1958309110f9892d10b28b1beea9c670/numpy/distutils/fcompiler/__init__.py#L899-L904) becomes an error now which makes it impossible to use without setting the correct `--fcompiler` even though no Fortran code is ever used.

That seems to be a different issue though I'll (let) test whether the issue persists in the PEP517 build with `pip`. I opened a [PR](https://github.com/numpy/numpy/pull/26502) to fix that.

**Comment by rgommers** [comment]
> `python setup.py build [--fcompiler <myFC>]` was used

FYI, this no longer works at all. `setup.py` was removed quite a while back. So submitting a PR related to this isn't constructive.
