### ISSUE TITLE
BUG: numpy.alltrue is missing in numpy 2 and there is no lint or migration guide mention

### ISSUE THREAD

**Issue by illume** [numpy/numpy#26493]
### Describe the issue:

numpy.alltrue and maybe other functions are missing, and there's no lint for it

Here it mentions that there should probably be a lint for it. https://github.com/numpy/numpy/issues/24306#issuecomment-1764825752
> I don't think there's much appetite for a compat package and instead I think we're going to point people to ruff to lint and update their code. If there are cases where it's not straightforward to write code that works the same in both NumPy 1 and 2 we should look closer and see if it's possible to add code in a NumPy 1 bugfix release or in NumPy 2 to ease writing code that works in both versions.

Hi. 

We noticed numpy.alltrue was gone, and there's no lint for it. Not sure if there's lints for other missing things... I didn't test for that.

https://github.com/pygame/pygame/issues/4239#issuecomment-2121864586
There's quite a few hits for this function https://github.com/search?q=numpy+alltrue&type=code

### Reproduce the code example:

```python
import numpy
numpy.alltrue
```

- [x] Note this lint check does not find the missing function.
```
ruff check test/*.py --select NPY201
```

- [x] It's not mentioned in the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html

- [ ] It's not mentioned in the release notes: https://github.com/numpy/numpy/releases/tag/v2.0.0rc2

### Python and NumPy Versions:

2.0.0rc2

**Comment by mattip** [comment]
As mentioned [elsewhere](https://github.com/numpy/numpy/issues/24306#issuecomment-2121974495) by @mtsokol: 

`np.alltrue` had a deprecation message since 1.25 version. I think we need to mention it in the migration guide if it's missing. 

```
.. deprecated:: 1.25.0
    ``alltrue`` is deprecated as of NumPy 1.25.0, and will be
    removed in NumPy 2.0. Please use `all` instead.
```

**Comment by mtsokol** [comment]
Solved in https://github.com/numpy/numpy/pull/26517 and https://github.com/astral-sh/ruff/pull/11528.

**Comment by illume** [comment]
AWESOME

**Comment by mtsokol** [comment]
Closing as https://github.com/numpy/numpy/pull/26517 and https://github.com/astral-sh/ruff/pull/11528 were merged.
