### ISSUE TITLE
BUG: <module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'>

### ISSUE THREAD

**Issue by MsAnitaAli** [numpy/numpy#26494]
### Describe the issue:

I was cloning a repo  using Collab and installed it dependencies using the following 

!pip install -U numpy==1.18.5 # specific version installation did not work in collab 

then I tried this 

%pip install -U numpy==1.18.5  # it gave error 

So finally I installed latest available version using this
!pip install -U numpy

Note: Same for other specific version installation of TensorFlow and open cv python.
now when i run my code, I got error message like this 

/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py in <module>
     55 IS_PYSTON = hasattr(sys, "pyston_version_info")
     56 HAS_REFCOUNT = getattr(sys, 'getrefcount', None) is not None and not IS_PYSTON
---> 57 HAS_LAPACK64 = numpy.linalg._umath_linalg._ilp64
     58 
     59 _OLD_PROMOTION = lambda: np._get_promotion_state() == 'legacy'

**Reproduce the error**
You may check my notebook at this [link](https://colab.research.google.com/drive/1I2utI9kG_S6HrcZuaG4xiTsLyzv5iruO#scrollTo=N8ko7_diUdXT) 

@mattip 
in issue 25150 mentioned that it might be due to multiple installation of numpy. 

Kindly guide me. 

**Repo used**
 https://github.com/datature/resources

I was trying to replicate and run code of this notebook  https://github.com/datature/resources/blob/main/example-scripts/tracking/DeepSORT/DeepSORT.ipynb  of the repo from my Collab Notebook folder from my mounted drive.

 

### Reproduce the code example:

```python
# code snippet that produced error 

%cd /content/drive/MyDrive/resources/example-scripts/tracking/DeepSORT/deep_sort_realtime
#%cd deep_sort_realtime
from PIL import Image
from deep_sort_realtime.deepsort_tracker import DeepSort  # it got stuck at this line
```

### Error message:

```shell
/content/drive/MyDrive/resources/example-scripts/tracking/DeepSORT/deep_sort_realtime
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-26ca7afabb57> in <cell line: 4>()
      2 #%cd deep_sort_realtime
      3 from PIL import Image
----> 4 from deep_sort_realtime.deepsort_tracker import DeepSort
      5 get_ipython().run_line_magic('cd', '..')

10 frames
/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py in <module>
     55 IS_PYSTON = hasattr(sys, "pyston_version_info")
     56 HAS_REFCOUNT = getattr(sys, 'getrefcount', None) is not None and not IS_PYSTON
---> 57 HAS_LAPACK64 = numpy.linalg._umath_linalg._ilp64
     58 
     59 _OLD_PROMOTION = lambda: np._get_promotion_state() == 'legacy'

AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'
```

### Python and NumPy Versions:

all that was available in collab on 21st May 2024

### Runtime Environment:

Collab

### Context for the issue:

I am trying to run object tracking code for my course work. my exam is due and have to show some results to my supervisor. Please reply soon.

**Comment by ngoldbaum** [comment]
Somehow you have a newer and older version of numpy installed simultaneously. This can happen if you set e.g. PYTHONPATH or have multiple python installations present in your path.

See #25906, #25150.
