### ISSUE TITLE
BUG: Generator.choice fails with a.ndim > 1 and size=()

### ISSUE THREAD

**Issue by ricardoV94** [numpy/numpy#26518]
### Describe the issue:

Generator.choice with explict size=() fails whereas it works with size=None, when a.ndim > 1

According to the docs this should be a valid operation.

### Reproduce the code example:

```python
import numpy as np

rng = np.random.default_rng()
rng.choice([[1, 2, 3]], size=())  # ValueError: setting an array element with a sequence.
```

### Error message:

```shell
TypeError: only length-1 arrays can be converted to Python scalars
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/ricardo/miniconda3/envs/pytensor/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-4a79a97119ec>", line 4, in <module>
    rng.choice(np.array([[1, 2, 3]]), size=()) # ValueError: setting an array element with a sequence.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/_generator.pyx", line 938, in numpy.random._generator.Generator.choice
ValueError: setting an array element with a sequence.
```

### Python and NumPy Versions:

1.26.4
3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]

**Comment by mattip** [comment]
[The docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html#numpy-random-choice) state
```
size: int or tuple of ints, optional

    Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
```

What output would you expect when `size` is an empty tuple?

**Comment by WarrenWeckesser** [comment]
This occurs in the main development branch, too.

Note that the error does not occur if the first argument is a 1-d sequence, e.g.

```
In [19]: rng.choice([1, 2, 3], size=())
Out[19]: array(2)
```
That makes sense--an array with shape () is an array scalar.
```
In [20]: _.shape
Out[20]: ()

```

**Comment by WarrenWeckesser** [comment]
In the main development branch, the problem occurs at line 1002 of `_generator.pyx`:

https://github.com/numpy/numpy/blob/9142f32573612d544b65649cf6f485f55b48e97a/numpy/random/_generator.pyx#L994-L1007

That code doesn't take into account that `a` (the array of choices) might have more than one dimension, so the items being selected are themselves arrays.  I think we can fix the problem by adding the additional condition `and a.ndim == 1` to the conditions checked for the special case, so line 995 becomes

```
        if not is_scalar and idx.ndim == 0 and a.ndim == 1:
```

With that change:

```
In [3]: rng.choice([[1, 2, 3]], size=())
Out[3]: array([1, 2, 3])
```

Another wart that occurs without this change is the behavior of `rng.choice([[1]], size=())`.  This is what happens with the main dev branch:

```
In [4]: rng.choice([[1]], size=())
<ipython-input-4-ebe1e24be378>:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  rng.choice([[1]], size=())
Out[4]: array(1)
```
That's not what we want. With the change that I propose above, we get
```
In [5]: rng.choice([[1]], size=())
Out[5]: array([1])
```
which is what I would expect.

All the existing tests in `numpy.random` pass with this change, but I'm not sure if this would introduce any new warts.  I'll draft a pull request and see how it goes.

**Comment by rkern** [comment]
> What output would you expect when `size` is an empty tuple?

A "sample" in the case of a sequence of shape-`(3,)` arrays is a shape-`(3,)` array. In our other multivariate distributions, the provided `size` tuple gets prepended to the shape of a single sample and is not the shape of the output itself.

```python
>>> rng.multinomial(10, np.full(4, 1/4), size=(10,)).shape
(10, 4)
```

**Comment by ricardoV94** [comment]
Didn't expect the size=() to be confusing, @rkern explained it well, but perhaps a more direct example is:

```python
import numpy as np
rng = np.random.default_rng()
rng.multinomial(10, np.full(4, 1/4), size=()).shape  # (4,)
```
The same would be expected for `choice`.
