### ISSUE TITLE
DOC: Anaconda links are broken on Install page

### ISSUE THREAD

**Issue by wjandrea** [numpy/numpy#26533]
### Issue with current documentation:

Links:

> [Anaconda Distribution](https://www.anaconda.com/distribution)

Ends up at [Data Science & AI Workbench](https://www.anaconda.com/products/data-science-ai-workbench)

> [Anaconda](https://www.anaconda.com/distribution/)

Dead (404 error). This link goes to the same place, but with a trailing slash.

### Idea or request for content:

I opened an issue at Anaconda: [anaconda.com/distribution redirects to Data Science & AI Workbench](https://github.com/ContinuumIO/anaconda-issues/issues/13391), so hopefully they fix it on their end.

Otherwise, you could change the links to point to [anaconda.com/download/](https://www.anaconda.com/download/), like [SciPy does](https://scipy.org/install/).

BTW, [the Pandas install page](https://pandas.pydata.org/docs/getting_started/install.html) links to the Anaconda **docs** ([Distribution](https://docs.continuum.io/free/anaconda/) and [Installation](https://docs.continuum.io/free/anaconda/install/)) which I find a lot harder to navigate.

**Comment by rgommers** [comment]
Thanks for the report. Fixed by https://github.com/numpy/numpy.org/pull/755
