### ISSUE TITLE
BUG: OOM due to memmap page table entries filling up RAM

### ISSUE THREAD

**Issue by Semnodime** [numpy/numpy#26532]
### Describe the issue:

Running a python application which
- uses numpy.memmap to map
- a large input file and 
- a large output file and 
- processes the input map in chunks and writes to the output map

Results in
 - out of memory issue due to
 - page table entries filling up RAM, because
 - pages which have already been written through to underlying file do not get discarded by numpy

### Reproduce the code example:

```python
import numpy as np
arr_input = np.memmap('/data_6TB_in', dtype=np.uint8, mode='r')
arr_output = np.memmap('/data_6TB_out', dtype=np.uint8, mode='w')
for i in range(len(arr_input)):
  arr_output[i] = arr_input[i] + 1
```

### Python and NumPy Versions:

1.26.4
3.12.3 (main, May 14 2024, 07:34:56) [GCC 12.2.0]

### Runtime Environment:
```json
[
  {
    "numpy_version": "1.26.4",
    "python": "3.12.3 (main, May 14 2024, 07:34:56) [GCC 12.2.0]",
    "uname": {
      "system": "Linux",
      "node": "23e8beb91dff",
      "release": "6.1.0-21-amd64",
      "version": "#1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)",
      "machine": "x86_64"
    }
  },
  {
    "simd_extensions": {
      "baseline": [
        "SSE",
        "SSE2",
        "SSE3"
      ],
      "found": [
        "SSSE3",
        "SSE41",
        "POPCNT",
        "SSE42",
        "AVX",
        "F16C",
        "FMA3",
        "AVX2"
      ],
      "not_found": [
        "AVX512F",
        "AVX512CD",
        "AVX512_KNL",
        "AVX512_KNM",
        "AVX512_SKX",
        "AVX512_CLX",
        "AVX512_CNL",
        "AVX512_ICL"
      ]
    }
  },
  {
    "architecture": "Haswell",
    "filepath": "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.12/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so",
    "internal_api": "openblas",
    "num_threads": 4,
    "prefix": "libopenblas",
    "threading_layer": "pthreads",
    "user_api": "blas",
    "version": "0.3.23.dev"
  }
]
```

### Context for the issue:

Inability to process large files with memmap due to OOM issues.

**Comment by Semnodime** [comment]
Probably related to https://github.com/numpy/numpy/issues/21292

**Comment by seberg** [comment]
NumPy doesn't do anything special here, it simply memory maps the file and the kernel should do the rest?
To me, the only NumPy thing that NumPy could do wrong is leak the result of `arr_input[i] + 1` (or whatever you do in the real code), but I think someone else would have noticed that long ago on a released version of NumPy.

Maybe you know some memory mapping options that make this work, you can use the Python `mmap` and just wrap that with `np.frombuffer`.  Effectively, NumPy `np.memmap` doesn't do more than that anyway.
(I.e. not sure if normal page size is a problem, and huge pages would help, in which case `np.memmap` would end up with the default probably and doesn't expose options.)

If you think there is an actual issue, please make sure to modify the example to work.

**Comment by testhowtest** [comment]
Probably duplicated with #21292 ? Is that right?

**Comment by Semnodime** [comment]
> Probably duplicated with #21292 ? Is that right?

Please clarify what you mean by something being "duplicated with" something.
Note that [I have already hinted](https://github.com/numpy/numpy/issues/26532#issuecomment-2131368739) that #26532 is probably related to #21292 along the initial bug report.

@testhowtest Did you overlook said statement or are you suggesting to close this issue due to similarity as proposed by @seberg ?

**Comment by seberg** [comment]
Dunno if it is very related, since I am pretty sure the other issue was just confusion about what is (reported as) the real memory use, vs. virtual memory use, etc.

@Semnodime you seem to know about those subtleties.  So I'll ask again: can you clarify how you think that NumPy is failing to do what you would expect to work for reading from one huge memorymap and writing to another?

And you could do that operation e.g. with pure Python `mmap` to convince me that something is wrong.  But unless you do, I can currently only assume that there are some subtleties either in huge memory mapped files or in your own code you are running into:  And those are not NumPy issues.

**Comment by seberg** [comment]
Going to close this, please give more details/explain how NumPy is involved (as opposed to normal memory map handling in the kernel) and I am happy to reopen.
