### ISSUE TITLE
BUG: Memory leak of ndarray subclasses via augmented assignment operators

### ISSUE THREAD

**Issue by adeak** [numpy/numpy#26545]
### Describe the issue:

Subclasses of `np.ndarray` seem to lead to memory leaks (array instances not getting garbage collected) when their augmented assignment operators are called. This is on NumPy 2.0.0rc2 on Debian Linux, Python 3.11. No leak on NumPy 1.26.4.

### Reproduce the code example:

```python
import gc
import weakref
import numpy as np

class leaky_array(np.ndarray):
    pass

wref = weakref.ref(leaky_array((3,)).__mul__(1))
gc.collect()
print(wref)  # dead weakref, good
wref = weakref.ref(leaky_array((3,)).__imul__(1))
gc.collect()
print(wref)  # alive weakref to leaky array, bad
```

### Python and NumPy Versions:

```
2.0.0rc2
3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
```

Also nightly wheel:
```
2.1.0.dev0+git20240525.a6e9dc7
```

### Runtime Environment:

```
[{'numpy_version': '2.0.0rc2',
  'python': '3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]',
  'uname': uname_result(system='Linux', node='notebook', release='6.1.0-18-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01)', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/home/adeak/tmp_numpy2_gc_bug_env/lib/python3.11/site-packages/numpy.libs/libscipy_openblas64_-99b71e71.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]
```

**Comment by adeak** [comment]
There are additional confusing details about the leak, e.g. that the referrer that seems to keep the class alive is its own `__array_wrap__()` method:
```python
>>> gc.get_referrers(wref())
[<built-in method __array_wrap__ of leaky_array object at 0x7fca39523b50>]
>>> gc.get_referrers(wref())[0].__self__ is wref()
True
```
but I'm not sure how much of a red herring this is, considering that there might be referrers in C land that `gc` doesn't return. It's also weird to get one bound dunder array method but not the rest as referrers.

**Comment by adeak** [comment]
> It's also weird to get one bound dunder array method but not the rest as referrers (so it looks like it's not the `__self__` attribute that's doing the referring).

That's not true, sorry. Bounds methods are created on demand, so _no_ unused bound method should be referring to the instance. Probably not a red herring then.

It might be the `__array_wrap__` wrapped method that's kept alive somehow, pulling in the array instance with it. But calling `get_referrers()` on the bound method returns nothing.

**Comment by adeak** [comment]
Nightly wheel still has the issue:
```
2.1.0.dev0+git20240525.a6e9dc7
```

**Comment by seberg** [comment]
Thanks for the report!  There was another buggy path, but the main issue was accidental overshadowing which caused the cleanup to fail.

**Comment by adeak** [comment]
Thanks for the quick fix @seberg :)

**Comment by seberg** [comment]
One thing that would be nice to run the new release through a memory leak checker (valgrind will do, maybe sanitizers are faster these days).  I am very sure these paths were covered by tests, so that should have found it.
