### ISSUE TITLE
Fancy indexing fails on a[idx] = a

### ISSUE THREAD

**Issue by sl2c** [numpy/numpy#26542]
### Describe the issue:

Fancy indexing seems to produce incorrect results when calling
```
a[idx] = a
```
(see code example below). I guess, the [] operator does not to check if the id(r.h.s.) == id(self). One work-around is to call:
```
a[idx] = np.copy(a)
```
However, this is far from optimal, of course, when the set of indices in idx is small (compared to the full set of indices of a). At any rate, I believe the current result is not what a user expects, and it would be better to raise an exception in this case than have this kind of result creep in.

### Reproduce the code example:

```python
>>> import numpy as np
>>> a = np.array([0,1,2])
>>> idx = np.array([2,1,0])
>>> a[idx] = a
>>> a
array([0, 1, 0])
```

### Python and NumPy Versions:

>>> print(np.__version__); print(sys.version)
1.26.4
3.9.13 (main, Jul 29 2022, 10:49:47) 
[Clang 10.0.1 (clang-1001.0.46.4)]

**Comment by tylerjereddy** [comment]
I agree it is a bit confusing, I suppose one might naively expect this to reverse the array. That said, the footgun would still be easy to achieve even if an id check were in place I think:

```python
import numpy as np
a = np.array([0, 1, 2])
idx = np.array([2, 1, 0])
b = a[::]
print(id(a))
print(id(b))
a[idx] = b
print(a)
```

```
4312938512
4322288400
[0 1 0]
```

You could use `np.may_share_memory(a, b)`, but then I think from a design standpoint you end up with an NP-complete problem of assessing memory overlap of two arrays according to the NumPy docs! I'm guessing examples like this have been discussed previously.

I suppose one could add checks for the more obvious cases, but it may not be clear where to draw the line, and my guess would be there isn't much appetite for those kinds of shims, and performance tradeoffs on preventing corner case footguns, but I could be wrong.

**Comment by seberg** [comment]
I would actually consider this a small bug and otherwise an enhancement.  In most places NumPy detects this and implicitly makes the copy for the user now.  (e.g. with `out=` in ufuncs)
Indexing should probably do that check as well.

**Comment by tylerjereddy** [comment]
Interesting! Would/does the check go as far as detecting partial memory overlap, or just for having the same i.e., `arr.base`?

**Comment by seberg** [comment]
Yes, it would not be able to optimize by inspecting the index of cojrse.
