### ISSUE TITLE
ENH: Better error message for `np.put_along_axis`

### ISSUE THREAD

**Issue by arunppsg** [numpy/numpy#26553]
### Proposed new feature or change:

In the following code snippet and its corresponding traceback,
```py
arr = np.array([[10, 30, 20], [60, 40, 50]])
indices = np.array([[1], [0]])
values = np.array([[-1], [-2]])

np.put_along_axis(arr, indices, values, axis=None)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[43], line 5
      2 indices = np.array([[1], [0]])
      3 values = np.array([[-1], [-2]])
----> 5 np.put_along_axis(arr, indices, values, axis=None)

File ~/Applications/miniconda3/envs/np/lib/python3.10/site-packages/numpy/lib/shape_base.py:260, in put_along_axis(arr, indices, values, axis)
    257     arr_shape = arr.shape
    259 # use the fancy index
--> 260 arr[_make_along_axis_idx(arr_shape, indices, axis)] = values

File ~/Applications/miniconda3/envs/np/lib/python3.10/site-packages/numpy/lib/shape_base.py:32, in _make_along_axis_idx(arr_shape, indices, axis)
     30     raise IndexError('`indices` must be an integer array')
     31 if len(arr_shape) != indices.ndim:
---> 32     raise ValueError(
     33         "`indices` and `arr` must have the same number of dimensions")
     34 shape_ones = (1,) * indices.ndim
     35 dest_dims = list(range(axis)) + [None] + list(range(axis+1, indices.ndim))

ValueError: `indices` and `arr` must have the same number of dimensions
```

the `indices` in the `ValueError` refers to the fancy index (`_make_along_axis_idx(arr_shape, indices, axis)`) but it causes confusion as it can also mean the `indices` passed by the user for the `indices` arg in `np.put_along_axis`. Nevertheless, it does not throw a clear error why the input arguments passed are invalid.

One partial solution is to rename `indices` of `_make_along_axis_idx` as `fancy_index` but that in itself does not explain what's causing the error. Or else, we can also possibly add an additional error check for the case where axis is None here:
https://github.com/numpy/numpy/blob/5ac5c15e8736ecb687dff3748aec7b3d57e81e1b/numpy/lib/_shape_base_impl.py#L254

**Comment by eendebakpt** [comment]
Note: the `np.np.take_along_axis` has the same issue. 

Personally I think the error message is a bit confusing because `np.put_along_axis` is not a very easy function to understand. The fact that the same name (e.g. `indices`) is used as an argument name for two methods (e.g. `_make_along_axis_idx` and `put_along_axis`) is something that happens more often and the traceback shows clearly in which method the error occurs.

We could indeed add an error message inside the `if axis is None: `, something like
```
   if len(arr.shape)!=1 or len(values.shape)!=1:
      raise ValueError('for axis=None the `indices` should have dimension one')
```
Another option could be to show the dimensions in the error message, as that might give a hint as well.

**Comment by arunppsg** [comment]
Makes sense, I added the error message and made a PR.
