### ISSUE TITLE
BUG: use np.arrange(0.02,0.16,0.02) create a sequence of numbers will contain 0.16

### ISSUE THREAD

**Issue by kingkong311** [numpy/numpy#26561]
### Describe the issue:

use np.arrange(0.02,0.16,0.02) create a sequence of numbers will contain 0.16

### Reproduce the code example:

```python
import numpy as np
c=np.arange(0.02,0.18,0.02)
print(c)
a =np.arange(0.02,0.16,0.02)
print(a)
b =np.arange(0.02,0.14,0.02)
print(b)
d = np.arange(0.12,0.16,0.01)
print(d)
```

### Error message:

```shell
[0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16]
[0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16]
[0.02 0.04 0.06 0.08 0.1  0.12]
[0.12 0.13 0.14 0.15 0.16]
```

### Python and NumPy Versions:

1.26.3
3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]

**Comment by rossbar** [comment]
Closing as duplicate, thanks all!
