### ISSUE TITLE
BUG: Copy mode was _not_ restricted to booleans

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#26573]
Despite larger changes to it, the copy mode conversion was not restricted to booleans, which is very unfortunate, if we don't have at least a FutureWarning in place that we may change it, IMO.

The reason is that without that warning, we won't  be able to introduce `copy="never"`, and as far as I am aware there is broad consensus that supporting that would be much preferable over only supporting True/False/None.

@mtsokol do you know about this?

**Comment by rgommers** [comment]
It's not clear to me what the exact problem is here. Could you please elaborate a little @seberg (maybe a code example)?

**Comment by seberg** [comment]
`np.array(..., copy="never")` is equivalent to `np.array(..., copy=True)`.  But supporting the strings came up a few times, so I think it would be nice to tighten that.

Not that it matters a lot, I doubt anyone is passing strings (or anything else then True/False).  But seemed like a nice thing to get out of the way.

**Comment by seberg** [comment]
Note: The main reason for tightening is that if we *do* add `copy="never"` support, things get confusing/silently wrong if you test on a new version (with support) and then run on an old version.

**Comment by rgommers** [comment]
Ah okay, got it. Not sure if we should only allow literal `True`/`False`/`None` (and therefore, e.g., not `np.bool(True)`), or simply ensure to raise on `"never"`/"always"/"if-needed"` to ensure we reserve those names for future use.

**Comment by seberg** [comment]
I think a pretty good path (and what Python uses in some places, IIRC) is to only accept integer-likes (i.e. `operator.index(obj) != 0` is the fallback).
