### ISSUE TITLE
List comprehension does not work in np.argmin() function

### ISSUE THREAD

**Issue by DYFeng** [numpy/numpy#26647]
### Describe the issue:

When using List comprehension, the output is not expected 2

In [12]: np.argmin(x for x in [3,2,1])
Out[12]: 0

In [13]: np.argmin([x for x in [3,2,1]])
Out[13]: 2

### Reproduce the code example:

```python
np.argmin(x for x in [3,2,1])
```

### Python and NumPy Versions:

1.24.2
3.9.18 (main, Nov  2 2023, 17:01:24)
[Clang 14.0.0 (clang-1400.0.29.202)]

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/usr/local/lib/python3.9/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 2,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

**Comment by charris** [comment]
`x for x in [3,2,1]` is passed as a single generator object.
```
In [1]: array(x for x in [3,2,1])
Out[1]: array(<generator object <genexpr> at 0x7fa955091300>, dtype=object)
```

**Comment by luxedo** [comment]
I think that the behavior is correct. When creating an `ndarray` from a generator the generator is not consumed:

```python
>>>: np.array(x for x in [3, 2, 1])
array(<generator object <genexpr> at 0x7663dc12f9f0>, dtype=object)
```

By wrapping the list in the generator it is consumed and creates the list:

```python
>>> np.array([x for x in [3, 2, 1]])
array([3, 2, 1])
>>> np.array(list(x for x in [3, 2, 1])) 
array([3, 2, 1])
```

In fact, it is possible to wrap pretty much anything in an `ndarray`. I don't know if it is expected or useful to do so: 

```python
>>> np.array(tuple)
array(<class 'tuple'>, dtype=object)
>>> np.array(print)
array(<built-in function print>, dtype=object)
>>> np.array({})
array({}, dtype=object)
```

I see that it seems like a confusing behavior but the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.array.html) does not specify that it supports iterables or generators, only _array_like_.

I propose that the documentation should have a better definition for what's _array_like_. There's already [some discussion](https://stackoverflow.com/questions/40378427/numpy-formal-definition-of-array-like-objects) about that.
