### ISSUE TITLE
DOC: Add CI to commit messages standard acronyms

### ISSUE THREAD

**Issue by luxedo** [numpy/numpy#26649]
### Issue with current documentation:

The current [commit messages acronyms](https://numpy.org/devdocs/dev/development_workflow.html#writing-the-commit-message) does not contain `CI`:

```
API: an (incompatible) API change
BENCH: changes to the benchmark suite
BLD: change related to building numpy
BUG: bug fix
DEP: deprecate something, or remove a deprecated object
DEV: development tool or utility
DOC: documentation
ENH: enhancement
MAINT: maintenance commit (refactoring, typos, etc.)
MNT: alias for MAINT
REL: related to releasing numpy
REV: revert an earlier commit
STY: style fix (whitespace, PEP8)
TST: addition or modification of tests
TYP: static typing
WIP: work in progress, do not merge
```

Even though there's almost 300 commits that uses this acronym:

```bash
$ git log | grep "^ \+CI:" | wc -l
293
```

### I propose we add `CI` to the commit message acronym list.

 I'd be glad to create a PR if this idea is reasonable

**Comment by mattip** [comment]
Is that the only missing acronym? I wouldn't mind adding it and any others that are missing, and also note that other easily understood acronyms are acceptable.

**Comment by luxedo** [comment]
# List of commit acronyms with more than 10 commits - 10/06/2023 (dd/mm/yyyy):

* [x] 3573 DOC
* [x] 3355 MAINT
* [x] 3093 BUG
* [x] 2214 ENH
* [x] 1459 TST
* [x] 391 BLD
* [x] 322 STY
* [x] 244 DEP
* [x] 203 API
* [ ] 196 CI
* [ ] 174 NEP
* [x] 111 BENCH
* [x] 92 REL
* [x] 71 TYP
* [ ] 66 BUILD
* [x] 61 DEV
* [ ] 59 FIX
* [x] 58 MNT
* [ ] 41 TEST
* [ ] 38 SIMD
* [x] 34 WIP
* [ ] 34 REF
* [x] 33 REV
* [ ] 31 UPD
* [ ] 29 PERF
* [ ] 25 CLN
* [ ] 19 MANT
* [ ] 14 WRN
* [ ] 14 FEAT
* [ ] 11 BENTO


> Generated with:
> ```bash
> git log --oneline | grep "[0-9a-f]\{10\} \+[A-Z]\+:" | sed 's/[0-9a-f]\{10\} \([A-Z]\+\):.*/\1/' | sort | uniq -c | sort -h -r
> ```

**Comment by luxedo** [comment]
Other acronyms:
```
      9 WHT
      6 MAIN
      5 NEW
      5 MISC
      4 GEN
      4 CHG
      4 BF
      3 REVERT
      3 MRG
      3 HACK
      3 FIXUP
      3 EHN
      2 VER
      2 UPDATE
      2 RF
      2 REM
      2 PKG
      2 MOV
      2 MANIT
      2 LICENSE
      2 EJS
      2 DIST
      2 DEC
      2 BUGS
      1 WHL
      1 VENDOR
      1 TODO
      1 TMP
      1 TASK
      1 SPELL
      1 REPO
      1 PYX
      1 OTH
      1 NPYV
      1 MTH
      1 INIT
      1 GRRRRR
      1 GRR
      1 DOX
      1 DOCS
      1 DNM
      1 DIC
      1 CYT
      1 COMPAT
      1 COMMENT
      1 CHANGES
      1 BUT
      1 BUGLET
      1 BIG
      1 ABI
```

**Comment by luxedo** [comment]
Candidates for adding:
```
CI: continuous integration
NEP: NumPy enhancement proposals
BUILD: alias for BLD
```

**Comment by rgommers** [comment]
Yes to `CI` and `NEP` (a PR for this would be very welcome), no to `BUILD` (or `MNT` for that matter). There should be only one way to spell each, and the long-established ones are `BLD` and `MAINT`.
