### ISSUE TITLE
BUG: linalg.inv gives incorrect results when used with joblib

### ISSUE THREAD

**Issue by TTPO100AJIEX** [numpy/numpy#26643]
### Describe the issue:

Finding an inverse of a matrix with `linalg.inv` works incorrectly for matrices bigger than 12x12 when using `joblib` (see code example). 
The code works as expected for `size < 12` or `n_jobs = 1`. However, in all other cases the result of `inv` is incorrect.

### Reproduce the code example:

```python
def f(size):
    numpy.random.seed(42)
    return numpy.linalg.inv(numpy.random.normal(size = (size, size)))
print((joblib.Parallel(n_jobs = 2)(joblib.delayed(f)(p) for p in [ 10 ])[0] == f(10)).all())
print((joblib.Parallel(n_jobs = 2)(joblib.delayed(f)(p) for p in [ 12 ])[0] == f(12)).all())
print((joblib.Parallel(n_jobs = 2)(joblib.delayed(f)(p) for p in [ 15 ])[0] == f(15)).all())
```

### Error message:

```shell
Expected output:
True
True
True

Actual output:
True
False
False
```

### Python and NumPy Versions:

1.26.3
3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

### Runtime Environment:

[{'numpy_version': '1.26.3',
  'python': '3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC '
            'v.1929 64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='XXX', release='10', version='10.0.22631', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'XXX',
  'internal_api': 'openblas',
  'num_threads': 16,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]

**Comment by mattip** [comment]
Do the results become consistant if you force OpenBLAS to a single thread by calling `set OPENBLAS_NUM_THREADS=1` before running python?

**Comment by TTPO100AJIEX** [comment]
> Do the results become consistant if you force OpenBLAS to a single thread by calling `set OPENBLAS_NUM_THREADS=1` before running python?

No, still the same issue
```bash
PS C:\Users\XXX> set OPENBLAS_NUM_THREADS=1
PS C:\Users\XXX> python test.py
True
False
False
```

**Comment by mattip** [comment]
This is using an older version of OpenBLAS `'version': '0.3.23.dev`. Can you try with `pip install numpy==2.0.0rc2`, which uses OpenBLAS 0.3.27 and for me gives consistent results?

**Comment by TTPO100AJIEX** [comment]
> This is using an older version of OpenBLAS `'version': '0.3.23.dev`. Can you try with `pip install numpy==2.0.0rc2`, which uses OpenBLAS 0.3.27 and for me gives consistent results?

Yes, `2.0.0rc2` works as expected. Thanks.
