### ISSUE TITLE
f2py callstatement is ineffective in subroutines called from other subroutines

### ISSUE THREAD

**Issue by bilderbuchi** [numpy/numpy#26681]
### Describe the issue:

When using `callstatement` to overrride a subroutine with different code as per [the docs ](https://numpy.org/doc/stable/f2py/signature-file.html#f2py-statements), this works when said subroutine is directly invoked by Python. However, when invoking another subroutine that calls the first subroutine, this override is not in effect.

MWE:
test.f90
```fortran
module utils
    implicit none
  contains
    subroutine my_abort(message)
      implicit none
      character(len=*), intent(in) :: message
      !f2py callstatement PyErr_SetString(PyExc_ValueError, message);f2py_success = 0;
      !f2py callprotoargument char*
      write(0,*) "THIS SHOULD NOT APPEAR"
      stop 1
    end subroutine my_abort

    subroutine do_something()
        call my_abort("aborting inside")
    end subroutine do_something
end module utils
```

To avoid #2547, you have to do the compilation in 2 steps:
```
python3 -m numpy.f2py -h test.pyf --no-lower -m test test.f90
python3 -m numpy.f2py -c --f90exec=gfortran --fcompiler=gnu95 test.pyf test.f90
```

Invoking `my_abort` directly works as expected, raising the ValueError I have defined:
```
$ python3 -c "import test; test.utils.my_abort('aborting directly')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: aborting directly
```

However, when calling `do_something`, which in turn calls `my_abort`, the override seems to do nothing, and we run into the `stop`:
```
$ python3 -c "import test; test.utils.do_something()"
 THIS SHOULD NOT APPEAR
STOP 1
```
Expected result: Python raises `ValueError: aborting inside`

### Reproduce the code example:

```python
python3 -c "import test; test.utils.do_something()"
 THIS SHOULD NOT APPEAR
STOP 1

# Expected result: Python raises `ValueError: aborting inside`
```

### Python and NumPy Versions:

Numpy: 2.0.0rc2 via conda-forge
python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
gfortran: GNU Fortran (conda-forge gcc 11.2.0-16) 11.2.0

Using 2.0.0rc2 to avoid issue #26156

### Runtime Environment:

[{'numpy_version': '2.0.0rc2',
  'python': '3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) '
            '[GCC 12.3.0]',
  'uname': uname_result(system='Linux', node='b5dc6932b437', release='5.15.146.1-microsoft-standard-WSL2', version='#1 SMP Thu Jan 11 04:09:03 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM', 'AVX512_SPR']}},
 {'architecture': 'SkylakeX',
  'filepath': '/opt/conda/envs/xplengine/lib/libopenblasp-r0.3.27.so',
  'internal_api': 'openblas',
  'num_threads': 4,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]

### Context for the issue:

What I'm intending here is to avoid executing the Fortran `stop` statement when running wrapped code in Python, because that also kills the Python *interpreter* and thus, in my case, the `pytest` run of a whole test suite that this code is part of.

This `my_abort` cleanup subroutine is potentially called from many places throughout the actual codebase.

A similar-feeling issue involving callbacks: #7855
Feels related: #26156
ping @HaoZeke

**Comment by bilderbuchi** [comment]
I found an even smaller MWE, turns out that this also happens when both subroutines are in one module. Edited the OP.

**Comment by HaoZeke** [comment]
I was thinking about this a bit. I don't really think this is something which F2PY can handle. Basically, when you call `my_abort` in `do_something()` it calls the Fortran subroutine, but the `callstatement` is only valid for calls from Python into `my_abort` (basically because the `my_abort` Python wrapper includes the `callstatement`).

This behavior is integral to the way F2PY works efficiently, since always calling Python wrapped variants of Fortran routines would be pretty inefficient.

The way to call the Python wrapped variant would be using callbacks. I'm open to more design ideas about this but as it stands this isn't actionable.

There however a bug with `callstatement` and `--lower` wherein code like this:

```
      !f2py callstatement PyErr_SetString(PyExc_ValueError, message);f2py_success = 0;
```

ends up with issues like so:

```
  640 |                 pyerr_setstring(pyexc_valueerror, message);f2py_success = 0;;
      |                 ^~~~~~~~~~~~~~~
      |                 PyErr_SetString
../cstmtmodule.c:640:33: error: 'pyexc_valueerror' undeclared (first use in this function); did you mean 'PyExc_ValueError'?
  640 |                 pyerr_setstring(pyexc_valueerror, message);f2py_success = 0;;
      |                                 ^~~~~~~~~~~~~~~~
      |                                 PyExc_ValueError
```

I'll work on that in another issue.

**Comment by bilderbuchi** [comment]
> There however a bug with `callstatement` and `--lower` wherein code like this:

Yeah, that's basically the #2547 that I mentioned working around in the OP. 👍

**Comment by bilderbuchi** [comment]
> I was thinking about this a bit. I don't really think this is something which F2PY can handle. Basically, when you call `my_abort` in `do_something()` it calls the Fortran subroutine, but the `callstatement` is only valid for calls from Python into `my_abort` (basically because the `my_abort` Python wrapper includes the `callstatement`).
> 
> This behavior is integral to the way F2PY works efficiently, since always calling Python wrapped variants of Fortran routines would be pretty inefficient.
> 
> The way to call the Python wrapped variant would be using callbacks. I'm open to more design ideas about this but as it stands this isn't actionable.

Sad to hear that. Can't offer design ideas because the whole space is way too confusing/intricate for me -- if you say it can't be handled, then that's how it is.

I'm not sure what you mean exactly with this idea about callbacks? Could you maybe find the time to demonstrate this by adapting the MWE in here to that approach? 
I.e. so that `python3 -c "import test; test.utils.do_something()"` raises the `ValueError` instead of STOPping? Then I could translate that back into my real solution. 
Thanks!

**Comment by HaoZeke** [comment]
Sure, here is a rough sketch:

```fortran
module utils
    implicit none
  contains
    subroutine my_abort(message)
      implicit none
      character(len=*), intent(in) :: message
      !f2py callstatement PyErr_SetString(PyExc_ValueError, message);f2py_success = 0;
      !f2py callprotoargument char*
      write(0,*) "THIS SHOULD NOT APPEAR"
      stop 1
    end subroutine my_abort


    subroutine do_something(message)
        !f2py intent(callback, hide) mypy_abort
        character(len=*), intent(in) :: message
        call mypy_abort(message)
    end subroutine do_something
end module utils
```

Note that the key change is that `mypy_abort` is called, which can be set to the Python generated function. i.e. it is called as:

```ipython
In [1]: import test

In [2]: test.utils.my_abort('aborting directly')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 1
----> 1 test.utils.my_abort('aborting directly')

ValueError: aborting directly

In [3]: test.mypy_abort = test.utils.my_abort

In [4]: test.utils.do_something('helpme')
capi_return is NULL
Call-back cb_mypy_abort_in_do_something__user__routines failed.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 test.utils.do_something('helpme')

ValueError: helpme
```

There's a fix for the `--lower` stuff in the works as well.

**Comment by bilderbuchi** [comment]
Thanks a lot for that demo! One thing that's not clear to me is how to achieve this interaction correctly when only using Fortran, i.e. when _not_ involving Python/pytest. 
As explained above, ...

> What I'm intending here is to avoid executing the Fortran `stop` statement when running wrapped code in Python, because that also kills the Python _interpreter_ and thus, in my case, the `pytest` run of a whole test suite that this code is part of.

...Python/pytest just implements the test suite for a Fortran code. How can I modify the above to make sure when the main/proper simulation code runs, `do_something(message)` calls `my_abort(message)`, not `mypy_abort(message)`, as f2py is not involved then? 
AFAICT, `call mypy_abort(message)` would just fail/not compile because the compiler is not aware of the `!f2py` meta-comment. 😕

**Comment by HaoZeke** [comment]
> Thanks a lot for that demo! One thing that's not clear to me is how to achieve this interaction correctly when only using Fortran, i.e. when _not_ involving Python/pytest. As explained above, ...
> 
> > What I'm intending here is to avoid executing the Fortran `stop` statement when running wrapped code in Python, because that also kills the Python _interpreter_ and thus, in my case, the `pytest` run of a whole test suite that this code is part of.
> 
> ...Python/pytest just implements the test suite for a Fortran code. How can I modify the above to make sure when the main/proper simulation code runs, `do_something(message)` calls `my_abort(message)`, not `mypy_abort(message)`, as f2py is not involved then? That's what the `callstatement` nicely deals with automatically. AFAICT, `call mypy_abort(message)` would just fail/not compile because the compiler is not aware of the `!f2py` meta-comment. 😕

Good question, it can be done, but makes it a bit more verbose. My personal preference would be to use `fypp` or some other preprocessor to make calls to either `my_abort(message)` or `mypy_abort(message)` depending on a compile time check (e.g. are Python libraries being linked).

Another approach would be to pass a free function into the `do_something` routine itself, and marking it as `external` but this is pretty tedious (and can lead to very long calls).

**Comment by bilderbuchi** [comment]
Thank you for the pointers :-) , I'll see if i can use either approach.
