### ISSUE TITLE
ENH: Implementing function like scatter_add in PyTorch

### ISSUE THREAD

**Issue by shiningalehxb** [numpy/numpy#26689]
### Proposed new feature or change:

Hello NumPy Developing Team,
I am now writing codes to implement algorithms involving multi-dimensional array operations, which heavily use functions like scatter addition and gather. Currently I am using PyTorch, not because these codes are related to deep learning, but its built-in function "scatter_add" which perfectly matches the demand above. However, PyTorch tensors cannot be directly used as input for many SciPy special functions, which are also needed. Instead of repeatedly using tensor.numpy() to change torch.tensor into numpy.ndarray, I wonder if there is any possibility to add functions like "scatter_add" (together with its in-place version "scatter_add_") and "gather" in some future version of NumPy so that I can directly using numpy, which could be much more convenient. Thank you! :)

**Comment by mattip** [comment]
Inplace [pytorch.scatter_add_](https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_add_.html#torch.Tensor.scatter_add_) is spelled `numpy.add.at`, which is documented indirectly via [ufunc.at](https://numpy.org/devdocs/reference/generated/numpy.ufunc.at.html#numpy-ufunc-at). The "gather" variant is [ufunc.reduce](https://numpy.org/devdocs/reference/generated/numpy.ufunc.reduce.html) or [ufunc.reduceat](https://numpy.org/devdocs/reference/generated/numpy.ufunc.reduceat.html).
