### ISSUE TITLE
DOC: update section in NEP 44

### ISSUE THREAD

**Issue by rootsmusic** [numpy/numpy#26709]
### Issue with current documentation:

The [Data sets section](https://numpy.org/neps/nep-0044-restructuring-numpy-docs.html#data-sets) says: "Even for SciPy there has so far been no consensus on this".  That sentence should be updated.  (I can't find a tracking issue, so I assume that no decision has been made to adopt `scikit.datasets` or to create a `numpy` subpackage.)

### Idea or request for content:

[`scipy.datasets`](https://docs.scipy.org/doc/scipy/reference/datasets.html#how-dataset-retrieval-and-storage-works) decided to use Pooch to fetch datasets from its Github.

**Comment by mattip** [comment]
If I understand correctly, the formatting of that NEP should be improved to show that the datasets section is a subsection of the tutorials. It would be nice to be able to use `scipy.datasets` in the tutorials that require data.

**Comment by rgommers** [comment]
Good point about formatting, that seems worth fixing.

It's fine with me to update the sentence about `scipy.datasets` too. Note though that NEPs are proposals, which are snapshots in time, so in principle we're not updating them continuously when something they describe changes.
