### ISSUE TITLE
DOC: Change hardlinked NEPs to intersphinx mappings

### ISSUE THREAD

**Issue by Mukulikaa** [numpy/numpy#26707]
Our NEPs should be reachable via intersphinx mapping, so in this case we could use 
```
:ref:`NEP 50 <NEP50>`
```
instead of
```
`NEP 50 <NEP50>`_.
```
to create a link.  

Just for information, I ran `grep -R "NEP"` in the doc/source folder and found a number of instances where neps are hardlinked instead of using the intersphinx mapping. Not sure if this is something we want to fix also?

_Originally posted by @melissawm in https://github.com/numpy/numpy/issues/26371#issuecomment-2099300658_

**Comment by rgommers** [comment]
Sounds like a good idea to me! Yes, it'd be nice to fix this.

**Comment by eagunn** [comment]
Several of the hardlinks are in old release notes such as doc\source\release\1.18.0-notes.rst.

Should those be changed also? Or should they be left as is since, I'm guessing, those files aren't generally updated after they are issued?

**Comment by charris** [comment]
Note that I need to remove _all_ the intersphinx links in order to put the release notes up on the github release tag. From my point of view, no links would be good links :)

**Comment by eagunn** [comment]
@charris Are you saying that you simply need the 20 `:ref:` intersphinx links within `doc\source\release\2.0.0-notes.rst` changed to be hard links? Or do you also convert that file to some other format before you can feed it to the github release tag?

**Comment by charris** [comment]
@eagunn It is a two step process, but sphinx isn't part of it, so the links are not resolved. The first step is running towncrier, which produces hard links (good). The second step is translating the rst to md in order to post on github. Hard links translate without problems, sphinxisms need to be fixed after translation. Single backticks around NumPy references are a particular problem, but there are others.  Another problem is that folks may use md in the release fragments, which should be in rst.

These problems can all be dealt with, but mistakes seep through and it takes time.

**Comment by charris** [comment]
If you want to try to improve the translation, you can look in `pavement.py` for the `write_release` task. Not much is left in the pavement file, so any thoughts about replacing it would be welcome.

**Comment by eagunn** [comment]
@charris A tangled web it is then. I'll look at the pavement.py file soon. 
Also, let me know if, since it sounds as if the text wouldn't go through a standard PR review process, you simply need another pair of eyes for proofreading. I'm a fair line editor.

**Comment by charris** [comment]
> you simply need another pair of eyes for proofreading.

Yes, people are happy to point out errors in the posted notes :) But it is the translated version that is the main problem, and that only gets used once and also requires the downloaded wheels in order to generate the hashes, so posting it in a PR would be problematic, not least because the translated version occurs after the version tagging and also because the md file is not tracked by git. It is use and dump.

**Comment by charris** [comment]
If Github would take rst files, maybe using a repository script in the process, things would be easier. But last I looked, that wasn't possible. There are two README files produced, it is the rst version that is translated to produce the md version. It is possible that the rst version could be produced using sphinx to have hard links.

**Comment by eagunn** [comment]
Thanks to some build advice from @melissawm, I'm successfully building docs again and am making some progress on these changes. But as I'm finding and changing the hardlinks, I end up with some questions about the recommended best practice for how to use :ref: overall.

@Mukulikaa above recommended using the syntax:
```:ref:`NEP 50 <NEP50>` ```
which correctly generates a link to the doc\neps\nep-0050-scalar-promotion.html file with the label *NEP 50*. And there are a lot of links like that throughout all the docs.

But another option is to simplify the :ref: to
```:ref:`NEP50` ```
which generates the same hyperlink but pulls its label out of the NEP doc, in this case: *NEP 50 — Promotion rules for Python scalars*

As a newcomer to the docs, I would find it helpful to see the full title for the NEP.  But at the moment, whether to use the built-in document label or a shortened one seems to be left as an option for the author of the document that makes the reference. 

This all adds up to three questions for me:
- Is there currently a best practice policy about what label to use for a link to a NEP  (or to other pages that embed a clear label)? 
- If not, would it make sense to have a policy where the NEP's internal label is used for a first reference within a page and the short version is used for additional references, if any?
- Should I confine my current set of changes only to the hardlinks that were the original problem reported and not make any move to change other NEP links in the same docs to be more consistent?

**Comment by eagunn** [comment]
Note that many of the hardlinks to NEPs are in other NEPs themselves. I've figured out how to build the NEPs, so am proceeding with the hardlink fixes in those files. 

But given that the NEP docs have presumably gone through a long approval process and/or may refer to completed or abandoned work, are there special rules about editing them? Should they simply not be changed in a general cleanup pass?

**Comment by Mukulikaa** [comment]
> But at the moment, whether to use the built-in document label or a shortened one seems to be left as an option for the author of the document that makes the reference.

Yes, we generally use either depending on the context and structure of the sentence it is used in so that it does not "read weird". 

> If not, would it make sense to have a policy where the NEP's internal label is used for a first reference within a page and the short version is used for additional references, if any?

I don't have strong feelings about this either way so I'd like to hear what other people think too.

> Should I confine my current set of changes only to the hardlinks that were the original problem reported and not make any move to change other NEP links in the same docs to be more consistent?

If it's only fixing links it is generally okay to have them all in a single PR.

> But given that the NEP docs have presumably gone through a long approval process and/or may refer to completed or abandoned work, are there special rules about editing them?

IMO cosmetic changes like these are okay because they don't alter the information in any way.

**Comment by jorgepiloto** [comment]
Looks like this issue is already fixed and can be closed.

**Comment by ngoldbaum** [comment]
Closing, fixed by #26896. btw @eagunn if you put "closes #xxxxx" in your PR description, when the PR is merged the issue will close automatically.

**Comment by eagunn** [comment]
@ngoldbaum Thank you. I missed that part of the process.
