### ISSUE TITLE
Missing stub in Numpy 2.0

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#26712]
### Describe the issue:

MyPy gives a missing stub error.

### Reproduce the code example:

```python
Running MyPy on `input numpy as np` gives:

.venv/lib/python3.12/site-packages/numpy/ma/__init__.pyi:3: note: In module imported here,
.venv/lib/python3.12/site-packages/numpy/__init__.pyi:199: note: ... from here,
tjax/_src/display/display_generic.py:11: note: ... from here:
.venv/lib/python3.12/site-packages/numpy/ma/extras.pyi:2: error: Cannot find implementation or library stub for module named "numpy.lib.index_tricks"  [import-not-found]
    from numpy.lib.index_tricks import AxisConcatenator
```

### Python and NumPy Versions:

2.0.0
3.12.3 (main, Apr 25 2024, 13:23:56) [GCC 13.2.0]

### Runtime Environment:

[{'numpy_version': '2.0.0',
  'python': '3.12.3 (main, Apr 25 2024, 13:23:56) [GCC 13.2.0]',
  'uname': uname_result(system='Linux', node='Desktop', release='6.8.0-31-generic', version='#31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/neil/src/cmm/.venv/lib/python3.12/site-packages/numpy.libs/libscipy_openblas64_-99b71e71.so',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]

**Comment by rgommers** [comment]
That does look like a bug, thanks for reporting @NeilGirdhar. I'm a little confused why CI didn't catch this, since it seems like a very obvious error.

What Mypy version are you using?

**Comment by NeilGirdhar** [comment]
I'm using 1.10.0, but the error has disappeared on my machine even though nothing changed.  It may have been related to MyPy's cache.  Deleting the cache folder and running MyPy produces no errors.

So I think this is probably a bug in MyPy not updating its cache than in NumPy.  What do you think?

**Comment by rgommers** [comment]
Oh yes, Mypy's cache is known to b buggy. Rerunning it usually clears up errors that at first time seem puzzling for me. I'm not sure if there's anything in NumPy's type stubs that make caching bugs show up more frequently that on other packages. But I think it's a general thing - you probably upgraded to numpy 2.0.0 in an existing env, and Mypy didn't detect the upgrade?

**Comment by NeilGirdhar** [comment]
Exactly.  I'll close this then.  Maybe the closed will help others who run into the same problem.
