### ISSUE TITLE
NumPy 2.0.0 on Python 3.12 causes binary compatibilty issues with numpy.dtype for pandas 2.1.1

### ISSUE THREAD

**Issue by potiuk** [numpy/numpy#26710]
### Describe the issue:

We have a rather comprehensive CI suite of tests running for Airflow, and after Numpy 2.0.0 release, Python 3.12 tests of Airflow started to fail with this error:

```
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

It seems to be triggered by `pypi` resolving Pandas + numpy requirements to upgrade Numpy to 2.0.0 and downgrade pandas to 2.1.1 (from 2.1.4). It's likely because pandas 2.1.1 does not have limitation for numpy to be `<2` (pandas 2.1.4 actually has the limit added).

This is the diff of installation of "eager-upgrade" we run in Airflow's CI:

```diff
355c355
< numpy==1.26.4
---
> numpy==2.0.0
381c381
< pandas==2.1.4
---
> pandas==2.1.1
```

And **just** importing pandas -> numpy causes this error. Example failure (https://github.com/apache/airflow/actions/runs/9537986684/job/26286749479) 

```python
___ ERROR collecting tests/providers/google/cloud/triggers/test_vertex_ai.py ___
tests/providers/google/cloud/triggers/test_vertex_ai.py:37: in <module>
    from airflow.providers.google.cloud.hooks.vertex_ai.custom_job import CustomJobAsyncHook
airflow/providers/google/cloud/hooks/vertex_ai/custom_job.py:28: in <module>
    from google.cloud.aiplatform import (
/usr/local/lib/python3.12/site-packages/google/cloud/aiplatform/__init__.py:26: in <module>
    from google.cloud.aiplatform.datasets import (
/usr/local/lib/python3.12/site-packages/google/cloud/aiplatform/datasets/__init__.py:19: in <module>
    from google.cloud.aiplatform.datasets.column_names_dataset import _ColumnNamesDataset
/usr/local/lib/python3.12/site-packages/google/cloud/aiplatform/datasets/column_names_dataset.py:24: in <module>
    from google.cloud import bigquery
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/__init__.py:35: in <module>
    from google.cloud.bigquery.client import Client
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/client.py:69: in <module>
    from google.cloud.bigquery import _job_helpers
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/_job_helpers.py:47: in <module>
    from google.cloud.bigquery import job
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/__init__.py:27: in <module>
    from google.cloud.bigquery.job.copy_ import CopyJob
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/copy_.py:22: in <module>
    from google.cloud.bigquery.table import TableReference
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/table.py:28: in <module>
    import pandas  # type: ignore
/usr/local/lib/python3.12/site-packages/pandas/__init__.py:46: in <module>
    from pandas.core.api import (
/usr/local/lib/python3.12/site-packages/pandas/core/api.py:1: in <module>
    from pandas._libs import (
/usr/local/lib/python3.12/site-packages/pandas/_libs/__init__.py:18: in <module>
    from pandas._libs.interval import Interval
interval.pyx:1: in init pandas._libs.interval
    ???
E   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

It happens on ly for Python 3.12 - for Python 3.8-3.11, eager upgrade does not cause new numpy 2.0.0 to be installed. It's likely **some** incompatibility between pandas/numpy. We are going to address it temporarily for Airlfow by limiting numpy to < 2.0.0 until this is solved, so nothing urgent but maybe you can figure out some ways this can be prevented - seems that when `pip` is presented with command to install `numpy` and `pandas` on Python 3.12 will install `numpy 2.1.1` and `pandas 2.0.0` and they won't work together.

### Reproduce the code example:

```python
* Have a Python 3.12 environment
* Install pandas 2.1.1 and numpy 2.0.0:


pip install pandas==2.1.1 numpy==2.0.0
pip check


* Everything is fine
* Import pandas

```bash
root@01cd52a3b242:/opt/airflow# python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/usr/local/lib/python3.12/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Not sure if anything can be done there, we are going to change our limits to exclude that combination, but maybe you can also take a look and see if some exclusions might be needed.
```


### Error message:

```shell
___ ERROR collecting tests/providers/google/cloud/triggers/test_vertex_ai.py ___
tests/providers/google/cloud/triggers/test_vertex_ai.py:37: in <module>
    from airflow.providers.google.cloud.hooks.vertex_ai.custom_job import CustomJobAsyncHook
airflow/providers/google/cloud/hooks/vertex_ai/custom_job.py:28: in <module>
    from google.cloud.aiplatform import (
/usr/local/lib/python3.12/site-packages/google/cloud/aiplatform/__init__.py:26: in <module>
    from google.cloud.aiplatform.datasets import (
/usr/local/lib/python3.12/site-packages/google/cloud/aiplatform/datasets/__init__.py:19: in <module>
    from google.cloud.aiplatform.datasets.column_names_dataset import _ColumnNamesDataset
/usr/local/lib/python3.12/site-packages/google/cloud/aiplatform/datasets/column_names_dataset.py:24: in <module>
    from google.cloud import bigquery
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/__init__.py:35: in <module>
    from google.cloud.bigquery.client import Client
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/client.py:69: in <module>
    from google.cloud.bigquery import _job_helpers
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/_job_helpers.py:47: in <module>
    from google.cloud.bigquery import job
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/__init__.py:27: in <module>
    from google.cloud.bigquery.job.copy_ import CopyJob
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/copy_.py:22: in <module>
    from google.cloud.bigquery.table import TableReference
/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/table.py:28: in <module>
    import pandas  # type: ignore
/usr/local/lib/python3.12/site-packages/pandas/__init__.py:46: in <module>
    from pandas.core.api import (
/usr/local/lib/python3.12/site-packages/pandas/core/api.py:1: in <module>
    from pandas._libs import (
/usr/local/lib/python3.12/site-packages/pandas/_libs/__init__.py:18: in <module>
    from pandas._libs.interval import Interval
interval.pyx:1: in init pandas._libs.interval
    ???
E   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

### Python and NumPy Versions:

```
root@01cd52a3b242:/opt/airflow# python -c "import sys, numpy; print(numpy.__version__); print(sys.version)"
2.0.0
3.12.4 (main, Jun 13 2024, 03:50:00) [GCC 12.2.0]
```

### Runtime Environment:

```
root@01cd52a3b242:/opt/airflow# python -c "import numpy; numpy.show_runtime()"
[{'numpy_version': '2.0.0',
  'python': '3.12.4 (main, Jun 13 2024, 03:50:00) [GCC 12.2.0]',
  'uname': uname_result(system='Linux', node='01cd52a3b242', release='6.9.3-orbstack-00146-g1a8d02c90788', version='#1 SMP Wed Jun 12 00:20:38 UTC 2024', machine='aarch64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDFHM'],
                      'not_found': ['SVE']}},
 {'architecture': 'neoversen1',
  'filepath': '/usr/local/lib/python3.12/site-packages/numpy.libs/libscipy_openblas64_-3ca770d1.so',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]
```

### Context for the issue:

It fails CI checks for Airflow for Python 3.12. We will mitigate it by adding exclusions, but some of our users might run into the combinations of `pandas` + `numpy` that do not work well together on Python 3.12 so it could be a good idea to protect them against it.

**Comment by seberg** [comment]
Annoying that this is the error, TBH... but other errors would follow (C import failing, or other Python errors next).

The point is: pandas 2.2.2 is the first compatible release, and you are pinninig a lower version, so long you do this, you have to also pin NumPy unfortunately because of the way pip resolves things.
(The annoyance is that pip happily takes older versions of pandas without the pin, and there is no way to update that.)

**Comment by potiuk** [comment]
Almost.  The solution in https://github.com/apache/airflow/pull/40272 is that we add >=2.1.2 for all our pandas dependencies - and this will at least skips 2.1.1 that causes numpy 2.0.0 from being considered because pandas 2.1.2 already has numpy < 2 .

And yeah. It's likely not really solvable  for general case. I opened it mostly in case someone might figure out a better solution :)

**Comment by rgommers** [comment]
> The solution in [apache/airflow#40272](https://github.com/apache/airflow/pull/40272) is that we add >=2.1.2 for all our pandas dependencies

Thanks for sharing @potiuk. That solution seems correct to me (since pandas 2.1.1 is missing the <2 constraint which is technically a bug in pandas), and it also seems as good as it's going to get (metadata in existing releases cannot be fixed afterwards).

**Comment by potiuk** [comment]
For Python 3.8 we had to keep >= 1.5.3 though, because otherwise it would have conflict, but then Numpy 2 is Python 3.9+ only, so that is not an issue.

**Comment by OliverHKU** [comment]
This is more likely an issue of `pandas` than `numpy`. They assume that any latest version of `numpy` would be compatible but obviously the latest `numpy` release isn't. https://github.com/pandas-dev/pandas/issues/59023

**Comment by seberg** [comment]
@OliverHKU there is no bug in either pandas or NumPy:  If anything it is the `pip` install logic that creates basically unsolvable issues here because we cannot update very old versions to have the correct pins.

There is an "ouch" here: `bottleneck` doesn't have a compatible release published on pypi (unless you use `--pre` or `bottleneck>=1.4.0rc5` to install it).  If a user doesn't have it, all is good, but otherwise things get tricky.

**Comment by potiuk** [comment]
Yeah. Not an easy one because you cannot get a crystal bball and guess things in the future. I think lower binding of pandas >= 2.1.2. (where numpy <2 was already added) for python 3.9+ is the best approach.

**Comment by potiuk** [comment]
Not an easy one because nobody can guess far in advance what future will hold and whether certain future versions will be incompatible -especially that there are no universal standards about major version number being breaking or not.

Limiting pandas to >=2.1.2 on python 3.9+ (where numpy<2 is already set)seems to nicely solve the problem for Airflow (and our constraint mechanism that we recommend our users will get them safe when they are following recommended installation process). But generally speaking pandas >= 2.1.2 works nice

**Comment by TLeitzbach** [comment]
If it helps to narrow down the problem: We had the same issue in an AWS Lambda runtime with pandas==1.5.3 and Python 3.9 (we missed ot fix the numpy version). Curiously for us, the deployment failed today although we did not touch the dependencies. Fixing numpy to 1.24.3 resolved the problem. Apparently pip/pandas resolved to an incompatible version.

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/78650222/valueerror-numpy-dtype-size-changed-may-indicate-binary-incompatibility-expec/78650263#78650263

**Comment by vishnu1729** [comment]
we are having some pipelines break with this issue. reading through i couldn't quite follow what the fix is. Can someone advise?

**Comment by vishnu1729** [comment]
Okay so this is what worked for me when faced with issue while running an Azure Synapse Analytics notebook. 

```
%%sh
pip uninstall numpy --y
pip install numpy==1.26.4
```
References: 
[](https://stackoverflow.com/a/78638258) and [](https://stackoverflow.com/a/66138833)

**Comment by geee28** [comment]
I have the same error with Pandas 2.2.2 and Numpy 1.26.4 (even Numpy 2.0.0). I tried to downgrade Pandas to 2.1.2, and it makes no difference either. Any thoughts?

**Comment by RubTalha** [comment]
Once you downgrade to numpy 1.26.4 you need to restart your kernel. Restart
session ot Restart Runtime [Cntrl +M]

https://stackoverflow.com/questions/78650222/valueerror-numpy-dtype-size-changed-may-indicate-binary-incompatibility-expec

**Comment by vishnu1729** [comment]
> I have the same error with Pandas 2.2.2 and Numpy 1.26.4 (even Numpy 2.0.0). I tried to downgrade Pandas to 2.1.2, and it makes no difference either. Any thoughts?

I edited my original comment. As @RubTalha has mentioned, you need to restart the session after the install. My pandas version is 1.5.1.

**Comment by geee28** [comment]
I did restart the kernel. The same problem persists. 

https://github.com/alkaline-ml/pmdarima/issues/577

**Comment by itsDaiton** [comment]
numpy<2 in requirements.txt fixes the issue.

**Comment by wisskirchenj** [comment]
NumPy 2.0.0 is not only incompatible with pandas. I just had the same error as original poster in combination with SpaCy 3.7.5. 
Already a download of en_core_web_sm (`python -m spacy download en_core_web_sm`) crashed like it.

Downgrading NumPy to 1.26.4 fixed the problem.

**Comment by FrankXie05** [comment]
> NumPy 2.0.0 is not only incompatible with pandas. Using current Python 3.12.4, I just had the same error as original poster in combination with SpaCy 3.7.5. Already a download of en_core_web_sm (`python -m spacy download en_core_web_sm`) crashed like it.
> 

Thanks for sharing. I have a question, will this affect other modules? :)

**Comment by JohannesBuchner** [comment]
Perhaps this is the same issue:

On github CI with python 3.9, 3.10, 3.11 and 3.12:
*  `python -m pip install cython numpy scipy matplotlib corner getdist h5py pandas flake8 pycodestyle pydocstyle pytest-html pytest-xdist`
* building & importing a cython package using numpy

leads to " ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject" 

Here is the build log:
https://github.com/JohannesBuchner/UltraNest/actions/runs/11534375595/job/32108307793

adding "--upgrade --force-reinstall" to the pip command did not help.

**Comment by seberg** [comment]
I am going to close the issue, this is always the same: compiling against the wrong version.

In your case, you have `oldest-supported-numpy` in your `pyproject.toml`.

**Comment by AraHaan** [comment]
I run into a similar issue on python 3.14's main branch but with ``builtins.type`` for some reason with no idea on the internet on why that is that I get a ``RuntimeWarning`` from a specific python script.

**Comment by mattip** [comment]
We don't yet support python3.14 nor CPython `main`. Fixes are welcome (kind of, if upstream seems to have settled on the new API), but don't expect 3.14 to work until at the very earliest the first beta releases, i.e. May 2025, and even then only against the as-of-yet non-existant NumPy 2.3

**Comment by Alexandre-aksenov** [comment]
The title states Python 3.12 , but I can add that I've recently reproduced the issue on Python 3.11.16 while rebuilding from this old Dockerfile:
```dockerfile
FROM python:3.11  

RUN python -m pip install uvicorn==0.24.0.post1 fastapi==0.105.0 pandas==2.1.1 scikit-learn==1.3.0

....

```

First, I built the image:
```bash
docker build -t  image_name .
```

Next, I started it in the interactive mode with:
```bash
docker run --name container_name -d --rm -p 5002:5002 image_name
docker exec -it container_name bash

python
```

Next, I got the following results in python console:
```python 3.11.16 in the container
import numpy as np

np.__version__
# -> 2.4.6

import pandas as pd
#->
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.11/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/usr/local/lib/python3.11/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
''' 

```

Thanks for your attention!
