### ISSUE TITLE
gufunc dimensions

### ISSUE THREAD

**Issue by izaid** [numpy/numpy#26728]
Hello! I'm writing with a question about gufunc dimensions, specifically in the C API, that has come up in some recent work in SciPy. It has been suggested to me to ping @mhvk @seberg @mattip @WarrenWeckesser 

I'm particularly thinking about the loop function for a gufunc in the C API. According to https://numpy.org/doc/stable/reference/c-api/generalized-ufuncs.html#, this has the signature `void (*)(char **args, intp *dimensions, intp *steps, void *func)`. Here `steps` is an array of strides for each argument and for each dimension, in order. My question is about `dimensions`.

According to the documentation, "_Only one size is provided for each unique dimension name and the sizes are given according to the first occurrence of a dimension name in the signature._" So if my gufunc has signature:
`(i,j),(j,k)->(i,k)`
I'd expect dimensions to contain `i, j, k` in that order starting at the second entry.

But what I would really like is something analogous to `steps`, which contains all core dimensions of all arguments in order. For the example above, this would be `i, j, j, k, i, k` starting at the second entry. Is there a way to easily get that using the NumPy C API? If not, is there any suggested way to do this?

Many thanks for the help!

**Comment by seberg** [comment]
> which contains all core dimensions of all arguments in order

Could probably be done, but I don't understand the issue?  Since you have all the information available as is and if they don't match in shape, you would give them different names?

(I mean, I don't hate the idea, but there is the implementation fact that at the core the machinery builds the iteration with all the dimensions, so passing the information as it is passed right now is probably a lot more convenient.)

**Comment by izaid** [comment]
> > which contains all core dimensions of all arguments in order
> 
> Could probably be done, but I don't understand the issue? Since you have all the information available as is and if they don't match in shape, you would give them different names?
> 
> (I mean, I don't hate the idea, but there is the implementation fact that at the core the machinery builds the iteration with all the dimensions, so passing the information as it is passed right now is probably a lot more convenient.)

Essentially we're reconstructing views into the array, for the core dimensions only, in C. To do that, for each argument we need all strides and all dimensions. Indeed, I can do it myself manually with some work, but am wondering if there is a recommended way to do it or if this has come up before?

**Comment by seberg** [comment]
There are not that many gufuncs, mostly matmul and a couple of ones in `linalg`.  I don't think there is a recommendation, trick, or interesting pattern to it.  A comment with the actual signature? :)

Would have to dive into the code to know how easy it is to add such an option.  Adding a flag to opt-in to shouldn't be too hard (if maybe awkward to set) and I don't mind it, but I am not sure it's worth the trouble.
What I can see, is such an option making sense if anyone works on broadening the signature syntax (there is an issue somewhere, where one thought I had was to just make the "signature" a function so you can do almost anything.).

**Comment by mhvk** [comment]
I think @seberg answered it already, but maybe still useful to see an example: `matmul` is at https://github.com/numpy/numpy/blob/a4cddb60489f821a1a4dffc16cd5c69755d43bdb/numpy/_core/src/umath/matmul.c.src#L118 (it has a fairly complicated signature). Effectively, it assumes that the C code is written knowing the signature; I can imagine cases where it would be handier to treat it programmatically.

**Comment by izaid** [comment]
Thanks both! This was very helpful. Just wrapping up...

> Effectively, it assumes that the C code is written knowing the signature; I can imagine cases where it would be handier to treat it programmatically.

Indeed, this was my question. So the C code is written knowing the signature. Okay, so that at least clears up how to proceed (for now) over at SciPy. I will close this issue, but before I do I'll just write down some thoughts.

Essentially, we've been using gufuncs in SciPy to handle some of the more complicated special functions that operate on subarrays. It was nearly a perfect fit, except for two things:

1) Getting access to an array of dimensions, as discussed in this thread. I've now handled this by creating it semi-manually.

2) It would be nice if there was some way to have core dimensions at the beginning of an array. For instance, something like `(i,j,...),(j,k,...)->(i,k,...)` where `...` represents the broadcasted shape. So far as I know, that's not possible. Have worked around this using `np.moveaxis`.

Thanks again!

**Comment by mhvk** [comment]
> 2\. It would be nice if there was some way to have core dimensions at the beginning of an array. For instance, something like `(i,j,...),(j,k,...)->(i,k,...)` where `...` represents the broadcasted shape. So far as I know, that's not possible. Have worked around this using `np.moveaxis`.

The `gufuncs` have `axes` (and `axis` for a single core dimension) keyword arguments, so I think you can avoid `moveaxis`. For usage, see https://numpy.org/doc/stable/reference/ufuncs.html (I added them, but they do indeed seem little known...) Your example would be `axes=[(0, 1), (0, 1), (0, 1)]`

**Comment by izaid** [comment]
> > 2. It would be nice if there was some way to have core dimensions at the beginning of an array. For instance, something like `(i,j,...),(j,k,...)->(i,k,...)` where `...` represents the broadcasted shape. So far as I know, that's not possible. Have worked around this using `np.moveaxis`.
> 
> The `gufuncs` have `axes` (and `axis` for a single core dimension) keyword arguments, so I think you can avoid `moveaxis`. For usage, see https://numpy.org/doc/stable/reference/ufuncs.html (I added them, but they do indeed seem little known...) Your example would be `axes=[(0, 1), (0, 1), (0, 1)]`

That's great! Indeed, I didn't know the `axes` argument worked that way for gufuncs. Yes, it removes the need for `np.moveaxis`. Thanks!
