### ISSUE TITLE
DOC: Add missing package names in API documentation page

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#26727]
In [the API documentation page](https://numpy.org/doc/stable/reference/index.html#reference), there are some packages shown in parentheses (`numpy.exceptions`, `numpy.linalg`, etc.)  It might be nice to fill in the missing ones:
* [`numpy.strings`](https://numpy.org/doc/stable/reference/routines.strings.html)
* [`numpy.emath`](https://numpy.org/doc/stable/reference/routines.emath.html#module-numpy.emath)
* [`numpy.ma`](https://numpy.org/doc/stable/reference/routines.ma.html)
* [`numpy.polynomial`](https://numpy.org/doc/stable/reference/routines.polynomials.html)

**Comment by rgommers** [comment]
Thanks for pointing out the inconsistency @NeilGirdhar.

I'd be more inclined to remove other names in brackets. That page is by topic rather than by module, and is much less messy than it was but still not 100% ideal. The "by module" docs are at https://numpy.org/doc/stable/reference/module_structure.html

**Comment by NeilGirdhar** [comment]
That works too.  What do you think of reorganizing [the Array API's index](https://data-apis.org/array-api/latest/API_specification/index.html#) to match NumPy's index?  For some reason, the Array API chose to group all "element-wise functions" together, which seems to me to be less logical and useful than NumPy's organization.

**Comment by seberg** [comment]
The PR probably didn't do all the changes, you liked.  So feel free to open a new issue or PR about it.
