### ISSUE TITLE
DOC: set_printoptions doesn't mention new legacy mode 1.25

### ISSUE THREAD

**Issue by MichaelClerx** [numpy/numpy#26731]
### Issue with current documentation:

Current docstring explains the legacy modes 1.13 and 1.21 but not the new mode 1.25

https://github.com/numpy/numpy/blob/main/numpy/_core/arrayprint.py#L212

### Idea or request for content:

Add line describing 1.25 legacy mode

**Comment by ngoldbaum** [comment]
Looks like this was missed in the review of https://github.com/numpy/numpy/pull/22449.
