### ISSUE TITLE
BUG: `new DType in signature not yet supported` with `np.strings.add`

### ISSUE THREAD

**Issue by JacobHayes** [numpy/numpy#26735]
### Describe the issue:

The new `np.strings.add` accepts a `dtype` argument, which works when using `np.str_`, but fails with the new `StringDType`. The error message seems to indicate this is not just "not implemented", but shouldn't happen.

### Reproduce the code example:

```python
import numpy as np

np.strings.add(["num", "doc"], ["py", "umentation"], dtype=np.dtypes.StringDType)
```

### Error message:

```shell
Traceback (most recent call last):
  File "[...]/x.py", line 3, in <module>
    np.strings.add(["num", "doc"], ["py", "umentation"], dtype=np.dtypes.StringDType)
RuntimeError: Internal NumPy error: new DType in signature not yet supported. (This should be unreachable code!)
```

### Python and NumPy Versions:

2.0.0
3.12.3 (main, May 14 2024, 21:44:25) [Clang 15.0.0 (clang-1500.3.9.4)]

### Runtime Environment:

[{'numpy_version': '2.0.0',
  'python': '3.12.3 (main, May 14 2024, 21:44:25) [Clang 15.0.0 '
            '(clang-1500.3.9.4)]',
  'uname': uname_result(system='Darwin', node='jrh', release='23.5.0', version='Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]

### Context for the issue:

I was just experimenting with the new types and expected passing `StringDType` to all functions accepting a `dtype` would work, including `add` where I'd like the arbitrary length strings in the output.

**Comment by ngoldbaum** [comment]
Thanks! I can reproduce this on the latest version of the main branch.

I guess I never tried this during development.

It should definitely work to pass the either the dtype class or instance, I think. The instance doesn't work either, with a different error:

```
>>> np.strings.add(["num", "doc"], ["py", "umentation"], dtype=np.dtypes.StringDT\
ype())
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    np.strings.add(["num", "doc"], ["py", "umentation"], dtype=np.dtypes.StringDType())
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Cannot pass a new user DType instance to the `dtype` or `signature` arguments of ufuncs. Pass the DType class instead.
```

It does work if you create the arrays first:

```
>>> arr1 = np.array(['num', 'doc'], dtype=dt); arr2 = np.array(['py', 'umentation'], dtype=dt)
>>> np.strings.add(arr1, arr2)
array(['numpy', 'documentation'], dtype=StringDType())
```
