### ISSUE TITLE
ImportError when trying to import pcg64 from numpy.random".

### ISSUE THREAD

**Issue by Divyanshukukreti** [numpy/numpy#26748]
### Steps to reproduce:

I am trying to import pcg64 from numpy.random in my Python script. Despite using the latest version of NumPy (version 1.22.0), I'm encountering an ImportError.

### Error message:

```shell
ImportError                               Traceback (most recent call last)
Cell In[19], line 2
      1 from numpy.random import default_rng
----> 2 from numpy.random import pcg64

ImportError: cannot import name 'pcg64' from 'numpy.random' (C:\Users\HP\anaconda3\Lib\site-packages\numpy\random\__init__.py)
```

### Additional information:

Also, I'm new in this business and doing it first time so please be concise it will help me in learning. As a beginner with NumPy, I'm unsure how to resolve this ImportError when importing pcg64 and others also.

**Comment by rkern** [comment]
It's capitalized and case-sensitive: [`PCG64`](https://numpy.org/doc/1.26/reference/random/bit_generators/pcg64.html), not `pcg64`.
