### ISSUE TITLE
NumPy installation failed on my Android device

### ISSUE THREAD

**Issue by timonebiker796** [numpy/numpy#26749]
### Describe the issue:

With below errors, I can't install the numpy package.
![image](https://github.com/numpy/numpy/assets/173203124/afe8e800-97b5-40df-a2c7-2ea54ba4fc77)

### Reproduce the code example:

```python
pip install numpy
I just run above command, and the error occurred.
```

### Error message:

```shell
../numpy/_core/meson.build:198:4: ERROR: Problem encountered: Function 'csin' not found
```

### Python and NumPy Versions:

Latest version.

**Comment by rgommers** [comment]
NumPy requires C99 functions like `csin` to be available. Apparently that isn't the case on your Android device. I'm afraid this is a "your platform is not supported" case.
