### ISSUE TITLE
DOC: Typo on Release 2.0.0 markdown

### ISSUE THREAD

**Issue by mdevino** [numpy/numpy#26757]
### Issue with current documentation:

I was looking at the [v2.0.0 Release markdown](https://github.com/numpy/numpy/releases/tag/v2.0.0) realized there is as mall typo along the text. Downstream is written as "dpwmstream" in a few instances (see an example below).

![image](https://github.com/numpy/numpy/assets/19861348/1b9ebe72-eb93-4dce-9af3-f95cf0ebe486)

I wanted to open a PR with the fix, but I'm not sure how to edit the release markdown.

P.s.: This is definitely not a big deal, I was just wondering if this could be my first contribution to Numpy.

**Comment by seberg** [comment]
Only a maintainer (maybe even only owner can fix this typo), it is correct in the original docs, just a typo in fixing the links there.
I am not 100% sure if changing it triggers anything on the github side, though?

**Comment by mdevino** [comment]
Thanks for the reply. I'm not sure either. Let's wait on someone else to reply.

**Comment by dopplershift** [comment]
Editing the markdown on the GitHub release shouldn't trigger anything.

**Comment by charris** [comment]
Fixed. Thanks @mdevino . I only found the one occurance.
