### ISSUE TITLE
BUG: numpy.loadtxt read more lines than specified with max_rows

### ISSUE THREAD

**Issue by l09rin** [numpy/numpy#26754]
### Describe the issue:

Hi all,

I am trying to read a long file in bunches of 80000 lines at a time (I avoid reading the entire file all in once, since I also need to process some very large sized files). The sample file I use consists of 400 thousands lines of 5 columns each (mixed char and floats, all read as str type), but loadtxt() reads every time 110000 lines instead of 80000.

If I try to read less lines (in the example code 50000) it works properly. also if I use the function method genfromtxt() instead of loadtxt() I get the right number of lines.
I would like to keep using loadtxt(), since I saw that it is twice as faster then genfromtxt(), but I do not understand why it does not behave correctly in some cases. I attach the code giving me the error and also a sample data file.

[data.txt](https://github.com/user-attachments/files/15902550/data.txt)

### Reproduce the code example:

```python
import numpy as np

print("Looping with np.genfromtxt() :")
f = open( "data.txt" , 'r' )
for i in range(5) :
    conf = np.genfromtxt( f , dtype = 'str' , max_rows = 80000 )
    print("conf n.", i+1, ":", "loaded",len(conf),"lines.")
f.close()

print("Looping with np.loadtxt() :")
f = open( "data.txt" , 'r' )
for i in range(5) :
    conf = np.loadtxt( f , dtype = 'str' , max_rows = 80000 )
    print("conf n.", i+1, ":", "loaded",len(conf),"lines.")
f.close()

print("Loading 50000 lines with np.loadtxt() is ok:")
conf = np.loadtxt( "data.txt" , dtype = 'str' , max_rows = 50000 )
print("conf n. 1 :", "loaded",len(conf),"lines.")
```

### Python and NumPy Versions:

1.25.0
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

### Runtime Environment:

[{'numpy_version': '1.25.0',
  'python': '3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]',
  'uname': uname_result(system='Linux', node='giovanni-deskuu', release='6.5.0-27-generic', version='#28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/logrin/.local/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-7a851222.3.23.so',
  'internal_api': 'openblas',
  'num_threads': 24,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'}]

### Context for the issue:

I use numpy for data analysis in university research, since it is a fast tool to read and manipulate very large data sets.

**Comment by seberg** [comment]
The string path unfortunately needs to go through a second round of chunking, because it needs to figure out the string length, and the fast core of `loadtxt` doesn't support that.

That code seems to have a subtle bug, I think the chunking mechanism just gets things wrong and always reads `max_rows`, even though the intention was to process large files in chunks to reduce memory overhead.

The fix is simple, but I was wondering if you would be interested in a PR, the main work is probably adding one or two new tests.

**Comment by EngineerEricXie** [comment]
Given that the error occurs when the number of read lines exceeds 50,000, it seems likely that the problem is related to the handling of this variable. https://github.com/numpy/numpy/blob/ccff7fb327ed47db2dc94e2015572d4c75ccc9fd/numpy/lib/_npyio_impl.py#L850

**Comment by seberg** [comment]
Yes, the code just passes the wrong variable when reading chunks, instead of chunking it always reads everything (and then assumes it only read 50k lines in the first pass, but it read the full requested 80k already).

**Comment by a-figment** [comment]
Is there a similar fix/bug for `skiprows`? Using the same `data.txt` as above, the following only seems to load 50000 lines instead of `max_rows` rows that come after `skiprows` row, which should be 100000?  
```
conf = np.loadtxt( "data.txt" , dtype = 'str' , skiprows=200000, max_rows = 100000 )
print(len(conf)) # = 50000
```

numpy v2.2.2

**Comment by seberg** [comment]
Can you open a new issue?  It seems likley that it is the same (I didn't confirm).

**Comment by l09rin** [comment]
It seems to happen only when skip_rows is equal or greater than max_rows, I opened a new issue...
