### ISSUE TITLE
Compile Error when using C-API with Limited API on new Numpy 2.0

### ISSUE THREAD

**Issue by ids-pas** [numpy/numpy#26756]
Hi all,

we are using [numpy.i](https://github.com/numpy/numpy/blob/main/tools/swig/numpy.i) to integrate into our own Python bindings via SWIG and are building against the limited API.

Now that numpy 2.0 has been released we wanted to update our bindings to be compiled with numpy 2.0,
but stumbled onto this compile error:
`
Python312\site-packages\numpy\_core\include\numpy\dtype_api.h(452,5): error C2664: 'void Py_INCREF(PyObject *)': cannot convert argument 1 from 'PyArray_DTypeMeta *' to 'PyObject *'
`
Is there a "_PyObject_CAST" missing at:

https://github.com/numpy/numpy/blob/ccff7fb327ed47db2dc94e2015572d4c75ccc9fd/numpy/_core/include/numpy/dtype_api.h#L452

**Comment by seberg** [comment]
Heh, didn't know that newer versions of the stable ABI don't implicitly do the object cast for you in `Py_INCREF` anymore.  (A bit surprising on first thought but easy to fix, especially here.)

If you define the limited API to something slightly older (even `0x030A0000`, which is Python 3.10) I think it'll stop complaining as a workaround.

**Comment by ngoldbaum** [comment]
For what it's worth, we test with a relatively old limited API version:

https://github.com/numpy/numpy/blob/ccff7fb327ed47db2dc94e2015572d4c75ccc9fd/numpy/_core/tests/examples/limited_api/limited_api1.c#L1

**Comment by ids-pas** [comment]
Thank you very much for the quick response and your suggestions.

Unfortunatly we need a limited API >= 3.11 for the Python buffer API.
Unless you see another way, we will have to wait for numpy 2.0.1 to be released and stick with numpy 1.x for now.
