### ISSUE TITLE
BUG: PyArray_RegisterDataType has different reference counting behavior for Numpy 1.x vs. 2.x

### ISSUE THREAD

**Issue by lpsinger** [numpy/numpy#26763]
### Describe the issue:

Upon careful reading of the `PyArray_RegisterDataType` function, I think that it has different reference counting behavior for Numpy 1.x vs. 2.x. In Numpy 1.x, on success, a reference is stolen because the argument is added to the list of user descrs. However, in Numpy 2.x, the reference is never stolen.

So if one creates a `PyArray_DescrProto` on the heap and passes it to `PyArray_RegisterDataType`, one must remember to `Py_DECREF` it on success on Python 2.x but one must _not_ on Python 1.x.

### Reproduce the code example:

```python
# no reproducer, identified bug by reading source code
```

### Python and NumPy Versions:

2.x

**Comment by seberg** [comment]
A `PyArray_DescrProto` is an *uninitialized* object, it doesn't have a refcount before you register it.

But yeah, if you do heap allocate it, you should free it on NumPy 2, since NumPy 2 makes a copy.

**Comment by lpsinger** [comment]
Actually, it's not safe to call `Py_DECREF` at all on a `PyArray_DescrProto` in Numpy 2.x.

Normally to allocate it on the heap you would do the following:

```c
PyArray_DescrProto *proto = PyObject_New(PyArray_DescrProto, &PyArrayDescr_Type);
```

However if you ever call `Py_DECREF` on it, Python will crash in the `tp_dealloc` function for `PyArrayDescr_Type` because of the differences in struct layout between `PyArray_DescrProto` and `PyArray_Descr`.

I think it is best to always treat `PyArray_DescrProto` objects as immortal and to give them static storage duration. I have an unfortunate application where I really must allocate them dynamically, but I think that I can make that work by using `PyObject_Malloc` and `PyObject_Free`.

**Comment by lpsinger** [comment]
This was pretty subtle. It seems like better documentation could help, but I'm not sure exactly what form it would take.

**Comment by seberg** [comment]
For Numpy 2 lifetime does not matter. For Numpy 1 I thought the refcount was always ignored and returned witha refcount of 1 and then immortalized.

Using a non static dtype is rare, so dunno. They were never proper objects before registration anyway I think. So IMO allocating without PyObject_New was clewner even before. The change is, now you sjould free it again, because NumPy makes a copy.
