### ISSUE TITLE
BUG: 2.0.0 - Jupyter kernel crashes in VS Code during bokeh plotting

### ISSUE THREAD

**Issue by 2-5** [numpy/numpy#26773]
### Describe the issue:

I'm using Jupyter notebooks in VS Code and doing bokeh plots in them.

Yesterday I've re-created the virtual env, so I've got new versions of everything, including numpy 2.0.0. 
Now Jupyter notebooks crash when doing some bokeh plots.

Downgrading just numpy to 1.26.4 fixes the problem

### Reproduce the code example:

```python
Can't get a reproducible example, crashes only with larger more complex plots with non-public data.
```

### Error message:

```shell
No traceback, VS Code reports that the Jupyter kernel crashed.
```

### Python and NumPy Versions:

Python 3.11
Numpy 2.0.0

**Comment by melissawm** [comment]
This will be very hard to reproduce without some basic example. Can you at least share the code, if not the data?

**Comment by 2-5** [comment]
It's actually polars which crashes.

Reproducible example below. Extract `crash.parquet` from the attached zip.

```shell
# on Windows 11
py -3.11 -m venv .venv
.venv\Scripts\activate.bat
pip install numpy polars tzdata
```

Then run:

```python
import polars as pl

def iter_lines(df: pl.DataFrame, x: str, ys: list[str]):
    x_s = df.get_column(x)
    x_range = x_s.max() - x_s.min()

    resample_interval = x_range / 2000
    for y in ys:
        y_df = df.select([x, y])

        y_df = y_df.filter(pl.col(y).is_not_null())

        y_min_df = y_df.group_by_dynamic(
            x, every=resample_interval, start_by="datapoint",
        ).agg(
            _temp_value=              pl.col(y).    min(),
            _temp_idx  =pl.col(x).get(pl.col(y).arg_min()),
        )

        y_max_df = y_df.group_by_dynamic(
            x, every=resample_interval, start_by="datapoint",
        ).agg(
            _temp_value=              pl.col(y).    max(),
            _temp_idx  =pl.col(x).get(pl.col(y).arg_max()),
        )

        y_range_df = pl.concat([y_min_df, y_max_df])
        y_range_df = y_range_df.sort("_temp_idx")

        a = y_range_df.get_column("_temp_idx")  .to_numpy()
        b = y_range_df.get_column("_temp_value").to_numpy()

df = pl.read_parquet("crash.parquet")
print(df)

iter_lines(df, x="time", ys=["overshoot"])

print("NOT PRINTED, CRASHES BEFORE")
```
[crash.zip](https://github.com/user-attachments/files/15920059/crash.zip)

**Comment by rgommers** [comment]
Polars doesn't yet have full support for NumPy 2.0, see https://github.com/pola-rs/polars/issues/16998 which explains that datetime dtypes aren't supported and will yield segfaults. Based on your variable names, I'm guessing there are datetime dtypes involved here? If so, I think this can be closed. If it's something else, it's still a Polars issue that you may want to report to the Polars devs.

**Comment by 2-5** [comment]
Closing since this is indeed that polars datetime bug.
