### ISSUE TITLE
BUG: FFT operation returns C_CONTIGUOUS even if input is F_CONTUGIOUS

### ISSUE THREAD

**Issue by vahidmech** [numpy/numpy#26777]
### Describe the issue:

In Numpy_2, FFT operation returns C_CONTIGUOUS even if input is F_CONTIGUOUS while In NumPy 1.26 output was F_CONTIGUOUS for F_CONTIGUOUS input.

### Reproduce the code example:

```python
>>> import numpy as np
>>> a = np.ones((10,10), dtype=numpy.complex64, order="F")
>>> numpy.fft.fft(a).flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
```

### Python and NumPy Versions:

2.0.0
3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]

**Comment by ngoldbaum** [comment]
Ping @mhvk this smells related to the pocketfft changes.

**Comment by mhvk** [comment]
Hmm, I don't think that is a conscious choice, but rather something the gufunc machinery does automatically. I'm not sure how easy it is to set that - @seberg?

**Comment by mhvk** [comment]
p.s.  Am on holidays so will not be able to react very quickly.

**Comment by vahidmech** [comment]
> Hmm, I don't think that is a conscious choice, but rather something the gufunc machinery does automatically. I'm not sure how easy it is to set that - @seberg?

Isn't it because here `out` array is defined with default `order="C"`?
https://github.com/numpy/numpy/blob/main/numpy/fft/_pocketfft.py#L88
`out = empty(a.shape[:axis] + (n_out,) + a.shape[axis+1:], dtype=out_dtype)`

If an appropriate order is passed, it might work fine.

**Comment by mhvk** [comment]
@vahidmech - indeed, that seems plausible! Maybe that should just become an `empty_like`, so that only shape and dtype are overridden? Do you want to try and make a quick PR if it works? (I'm on holidays myself so it will be a bit before I get around to it.)
