### ISSUE TITLE
Proposal: Deprecate amax

### ISSUE THREAD

**Issue by gilaroni** [numpy/numpy#26801]
### Proposed new feature or change:

NumPy's np.amax function, an alias for np.max, can cause confusion due to its name. In many programming and mathematical contexts, 'amax' is commonly used as shorthand for 'argmax' (index of maximum value). However, np.amax returns the maximum value itself, not its index.

This mismatch between expected and actual behavior can lead to subtle, hard-to-detect bugs, especially when working with integer arrays where a maximum value might be mistaken for an index.

Moreover, users are unlikely to assume that max and amax are identical functions. Given the existence of both np.max and np.amax, it's reasonable to infer that amax must serve a different purpose, with argmax being the most logical assumption. This compound confusion increases the likelihood of misuse and errors in code.

For that reason, I think the best course of action is to deprecate one of them, and since amax is much less clear compared to max, it is probably the one to deprecate.

**Comment by ngoldbaum** [comment]
Unfortunately I don't think the benefit is worth the churn this would cause.

Currently there are 83,000 GitHub Python code search results for the string "np.amax", which means it's very commonly used.

**Comment by WarrenWeckesser** [comment]
For completeness: this issue also applies to `np.amin` and `np.around`.

**Comment by rgommers** [comment]
Agreed with @ngoldbaum's answer. We considered doing this deprecation for NumPy 2.0.0, but decided not to because it's too heavily used. We did remove many other aliases at that point. We're not reconsidering that right after 2.0 has been released - the ship has sailed I'm afraid. So I'll close as wontfix. Thanks for the proposal though @gilaroni!
