### ISSUE TITLE
Custom meson not included in 2.0.0 distribution

### ISSUE THREAD

**Issue by VictorEijkhout** [numpy/numpy#26806]
### Describe the issue:

When I tried to build the 2.0.0 distribution I got an incomprehensible message about no recent meson being found, while there was actually a recent meson in my path. Turns out you have your own meson, which doesn't seem to be included in the distribution. It was in the repo once I clone that.

### Reproduce the code example:

```python
download 200, try to install
```

### Python and NumPy Versions:

312 200

**Comment by charris** [comment]
What did you download, and from where?

**Comment by VictorEijkhout** [comment]
https://github.com/numpy/numpy/archive/refs/tags/v2.0.0.tar.gz

from the release page

https://github.com/numpy/numpy/releases/tag/v2.0.0

```
Processing /work2/00434/eijkhout/stampede3/python/numpy-2.0.0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]

      meson-python: error: Could not find meson version 0.63.3 or newer, found .
      [end of output]
```

**Comment by rgommers** [comment]
Please don't ever download such tags from a GitHub Releases page. GitHub auto-generates those, so unfortunately we cannot delete them. But such auto-generated tags are missing git submodules, which is the problem here. Please either download `numpy-2.0.0.tar.gz` from that same page, or download the sdist from PyPI.

**Comment by mattip** [comment]
@charris do we control the text at https://github.com/numpy/numpy/releases/tag/v2.0.0? Rather than putting the release notes, can we put an admonition that this is automatically generated and is the wrong place to look for anything: for release notes see ... and for downloads use PyPI sdist at ...

**Comment by VictorEijkhout** [comment]
Yes please. I think I've seen such warnings at repos.

**Comment by charris** [comment]
@mattip Having the release notes on the tag makes for a handy place that can be linked to for folks who just want to browse the notes or get there from the github page. I wish more projects put release notes on their release tags as that is one of the first places I look.

The problem with the wrong downloads comes up regularly, but also rarely. Github's automatic generation of tarballs is unfortunate, the tarballs never worked, even when we had no submodules. The ideal solution would be if we could disable that.

**Comment by mattip** [comment]
Having the release notes here means users need to scroll to the end to find the artifacts. If they get to that page from the github page, I would prefer to train them to check our documentation instead. 

> The ideal solution would be if we could disable that.

We can't. A second-best option would be to put an admonition here, but if we just put an admonition after the release notes it will get lost in the noise.

**Comment by rgommers** [comment]
An admonition at the top of the page seems like a reasonable middle ground to me.
