### ISSUE TITLE
CI: Test Linux (nightly OpenBLAS) is failing

### ISSUE THREAD

**Issue by charris** [numpy/numpy#26824]
See https://github.com/numpy/numpy/actions/runs/9732669831/job/26858622819. Seems to have started yesterday (6/30/2024)

**Comment by mattip** [comment]
This run is using scipy-openblas32-0.3.27.233 (aka OpenBLAS commit `c33bc849a`, where last week's scipy-openblas32-0.3.27.208 (aka OpenBLAS commit `1ba1b9c35`) did not have this problem. @martin-frbg any thoughts?

**Comment by martin-frbg** [comment]
Probably caused by that commit enforcing `0*INF=NAN` to satisfy https://github.com/OpenMathLib/OpenBLAS/issues/4728 . I need to doublecheck the claim made there that the reference BLAS really does this, as that change appears to introduce a significant number of LAPACK test failures on x86_64

**Comment by martin-frbg** [comment]
Still haven't got a handle on this, sorry - I have convinced myself that the changes from https://github.com/OpenMathLib/OpenBLAS/issues/4728 are correct, but there appears to be a problem with NAN propagation elsewhere in the code (and unrelated to the unmerged PR about NAN sort order in IMAX/IMIN, https://github.com/OpenMathLib/OpenBLAS/pull/4191 ). Unfortunately I still have a hard time matching up Numpy tests with the BLAS functions they call.
The LAPACK test failures appear to be a different issue, working around them does not change the numpy test results

**Comment by mattip** [comment]
Thanks for looking into it. Maybe we should mark the tests as xfail with that version of scipy-openblas32 to clear CI?

**Comment by martin-frbg** [comment]
probably, or rollback scipy-openblas32 - I have no idea what makes more sense in your context ? 
I'll try to fix whatever this is ASAP as it is blocking the already-delayed 0.3.28, but I'd rather not revert the (valid) PR that uncovered this problem

**Comment by ngoldbaum** [comment]
I opened #26991 to temporarily allow the scipy-openblas nightly tests to fail without failing all of the CI. Just the test step in the CI job, and hopefully only temporarily.
