### ISSUE TITLE
ENH: Add docstrings to native type stubs

### ISSUE THREAD

**Issue by rchiodo** [numpy/numpy#26845]
### Proposed new feature or change:

Numpy has a number of native functions as part of its public api, like [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html). 

The type stubs that ship for these native functions are missing docstrings at the moment. This request is to add the docstring found at runtime in the type stubs.

As a workaround, Pylance generates type stubs for numpy for numpy's native functions. (We run a script that loads all of the functions and asks them for their docstrings) 

Here's an example of the type stub we generated for `numpy.zeros` for 1.0:

```python
def zeros(shape, dtype=..., order=..., *, like=...) -> typing.Any:
    "    Return a new array of given shape and type, filled with zeros.\n\n    Parameters\n    ----------\n    shape : int or tuple of ints\n        Shape of the new array, e.g., ``(2, 3)`` or ``2``.\n    dtype : data-type, optional\n        The desired data-type for the array, e.g., `numpy.int8`.  Default is\n        `numpy.float64`.\n    order : {'C', 'F'}, optional, default: 'C'\n        Whether to store multi-dimensional data in row-major\n        (C-style) or column-major (Fortran-style) order in\n        memory.\n    like : array_like, optional\n        Reference object to allow the creation of arrays which are not\n        NumPy arrays. If an array-like passed in as ``like`` supports\n        the ``__array_function__`` protocol, the result will be defined\n        by it. In this case, it ensures the creation of an array object\n        compatible with that passed in via this argument.\n\n        .. versionadded:: 1.20.0\n\n    Returns\n    -------\n    out : ndarray\n        Array of zeros with the given shape, dtype, and order.\n\n    See Also\n    --------\n    zeros_like : Return an array of zeros with shape and type of input.\n    empty : Return a new uninitialized array.\n    ones : Return a new array setting values to one.\n    full : Return a new array of given shape filled with value.\n\n    Examples\n    --------\n    >>> np.zeros(5)\n    array([ 0.,  0.,  0.,  0.,  0.])\n\n    >>> np.zeros((5,), dtype=int)\n    array([0, 0, 0, 0, 0])\n\n    >>> np.zeros((2, 1))\n    array([[ 0.],\n           [ 0.]])\n\n    >>> s = (2,2)\n    >>> np.zeros(s)\n    array([[ 0.,  0.],\n           [ 0.,  0.]])\n\n    >>> np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype\n    array([(0, 0), (0, 0)],\n          dtype=[('x', '<i4'), ('y', '<i4')])"
    ...
```

**Comment by ngoldbaum** [comment]
I'm a little confused about this. We have type stubs for `zeros` [here](https://github.com/numpy/numpy/blob/0acdad6c8b7808e0cc6ce19523e2150b3fb72b27/numpy/_core/multiarray.pyi#L235-L261). The type stubs you're talking about are different from those?

**Comment by rchiodo** [comment]
Sorry I didn't realize the stubs already existed. Maybe the request then would be to add docstrings to your already existing type stubs?

**Comment by ngoldbaum** [comment]
I see [this thread](https://mail.python.org/archives/list/python-ideas@python.org/thread/QKJWPZ6XULFWNRFZYNTXXDC26UVQPFNG/#QKJWPZ6XULFWNRFZYNTXXDC26UVQPFNG) is relevant to this discussion, there's even a comment from a PyLance/PyRight developer in that thread advocating for exactly this.

I guess I don't see how we could do this without having the docstrings in multiple places. If there's a way to dynamically attach the docstrings to the type stubs at import time, would that be sufficient? I have no idea if that's possible though, since the types are supposed to be defined statically as I understand it.

**Comment by rchiodo** [comment]
Yeah you'd have to generate the stubs I believe before shipping. They can't be dynamic, as a typechecker doesn't actually run any python code.

We're currently solving this problem by running a script before we release that generates a secondary type stub that we injest.

**Comment by jorenham** [comment]
I was under the impression that it's bad practice to have docstrings in type stubs, because docstrings are a runtime feature.

**Comment by rchiodo** [comment]
> I was under the impression that it's bad practice to have docstrings in type stubs, because docstrings are a runtime feature.

I'd say native code is the exception here. Almost all other type stubs have no docstrings, well because they can be read from the real python code. Docstrings in type stubs are really only necessary for the cases where the underlying python source doesn't have them (or there is no underlying python code).

Whether or not numpy violates DRY would be an implementation detail IMO. Maybe the `add_newdoc` function could generate the stubs too?

**Comment by jorenham** [comment]
Perhaps something like [PEP 727](https://peps.python.org/pep-0727/) could to the trick

**Comment by ngoldbaum** [comment]
So you need to be able to get the docstrings statically without actually importing numpy? How are you doing that now?

Or if not, then I guess I'm confused why you can't combine the type information and docstrings at runtime.

**Comment by rchiodo** [comment]
> So you need to be able to get the docstrings statically without actually importing numpy? 

Yes we're a static type checker. No running of python code. People get upset if we run python code just because they opened a file in an editor.

> How are you doing that now?

We run a script during our build process specifically for numpy (and a few other packages). That python script imports all of the functions in numpy and then asks each one for their docstring. We then write this information to a type stub file we ship with Pylance. This was working okay before the API changed, but now that 2.0 is out, our stubs are out of date. Which is expected. It's a problem with us shipping stubs for packages, they never match.

**Comment by seberg** [comment]
I am going to close this.  As of now, I don't think there is a good story about how to do this without duplicating all of the docs.
Once it is a bit clearer of why this way, and how not to duplicate any docs/make the code weird, I think we should revisit.

**Comment by Jacob-Stevens-Haas** [comment]
Reading through the linked discussion, it looks like people had good reasons for docstrings to be available both dynamically and statically.  But GVR made a good point:

> There should be a tool to update the docstrings in stubs before I could recommend duplicating them there

This feels like something that, if enough people are interested, should be a feature of build tooling, rather than implemented independently on a per-repo basis.  Then, this feature could be as simple as adding `stub-docstrings` to `[build-system.requires]`.  Sort of like how `setuptools-scm` proliferated well before the community officially accepted `version` as dynamic metadata and debate continued as to whether VCS info should be part of an sdist.

(FWIW, part of that tool exists: sphinx reads docstrings dynamically and produces a static output)
