### ISSUE TITLE
BUG: including arrayobject.h results in fatal error 'numpy/_public_dtype_api_table.h: No such file or directory'

### ISSUE THREAD

**Issue by jkohnert** [numpy/numpy#26854]
### Describe the issue:

When trying to compile PlPlot I get the following error message:
```shell
In file included from /usr/lib/python3.12/site-packages/numpy/_core/include/numpy/ndarrayobject.h:22,
                 from /usr/lib/python3.12/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from /home/jankoh/projects/plplot/src/plplot-5.15.0/build/bindings/python/plplotcPYTHON_wrap.c:3201:
/usr/lib/python3.12/site-packages/numpy/_core/include/numpy/__multiarray_api.h:1475:10: fatal error: numpy/_public_dtype_api_table.h: No such file or directory
 1475 | #include "numpy/_public_dtype_api_table.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [bindings/python/CMakeFiles/plplotc.dir/build.make:76: bindings/python/CMakeFiles/plplotc.dir/plplotcPYTHON_wrap.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1782: bindings/python/CMakeFiles/plplotc.dir/all] Error 2
```

Since the failing include is within numpy's files, I suspect a possible bug in either Numpy, or Numpy's packaging.

Line 1475 in `__multiarray_api.h` reads:
```c
/*
 * The DType classes are inconvenient for the Python generation so exposed
 * manually in the header below  (may be moved).
 */
#include "numpy/_public_dtype_api_table.h"
```

However, the file is within the *same* directory as  `__multiarray_api.h`, not in another subdirectory `numpy/`.

I could find a bug report issuing the identical message for Gentoo: https://bugs.gentoo.org/932642

I am getting this error on current Arch Linux, so probably this indeed is an issue within Numpy.

### Reproduce the code example:

The include in PlPlot is done the following way:

```c
#define NPY_NO_DEPRECATED_API    NPY_1_7_API_VERSION
#include <arrayobject.h>
```

### Python and NumPy Versions:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
2.0.0
3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]
>>>

**Comment by ngoldbaum** [comment]
The path is relative to the numpy include directory returned from `np.get_include()`. Are you setting `np.get_include()` as an include path in your build?

Note that this is using gcc 14. So maybe this is because of some GCC change in a recent compiler version.

**Comment by jkohnert** [comment]
Thanks @ngoldbaum, I'll check that. I completely missed that the path given in the included header is relative to the previously given include dirs. Been doing too much Java/Kotlin recently. :rofl: 

I can (at least for Arch) verify, that the build worked using gcc-14 and Numpy<2.0.0; the problem started the day Arch introduced Numpy-2.0.0; gcc-14 was installed about a month earlier without any build problems for PlPlot using Numpy-1.26.4. 

Probably we have to use different includes for Numpy 2.0.0, then. On Arch, `get_includes()` currently yields
```python
>>> import numpy
>>> numpy.get_include()
'/usr/lib/python3.12/site-packages/numpy/_core/include'
>>> 
```
so I'll start digging into it using this information.

Thank's again! I'll report back.

Best, Jan

**Comment by seberg** [comment]
The error seems strange, because it seems to find NumPy 2 headers (NumPy 1.x doesn't include this file), but then the file isn't in the same folder.  I doubt the `get_includes()` is wrong here, if it was you would probably get 1.x headers and then a fail at runtime.

To me it seems that whatever installed NumPy 2 didn't properly copy all the header files into the install directory, although that is a bit weird.

**Comment by jkohnert** [comment]
Hi again,

I managed to recheck [gcc include documentation](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html). I'm not quite sure whether they changed something recently, but the docs state, `#include "..."` first checks the file's location if the included file can be found (backing my original idea, it should read `#include "_public_dtype_api_table.h"`, as Numpy itself does for the whole include hierarchy down from `arrayobject.h` except for this case), then gcc-specific `iquote`, which one should probaby not use, and *last* the system include dirs (to be augmented by `-I...`). In this case the file whould (in my case) need to sit in `/usr/lib/python3.12/site-packages/numpy/_core/include/numpy/`, which it does. So it should be findable.

One could argue to use `#include "_public_dtype_api_table.h"` as in the other places, but it should work the way it's written.

I'll do some more checking...

Thanks again, Jan

**Comment by seberg** [comment]
@jkohnert did you try just deleting the `numpy/`?  Sounds like while that may not be wrong there, it is not the best practice either.  A PR with the change would be welcome (especially if it works for you).

**Comment by charris** [comment]
IIRC, that  is a submodule. Did you init it?

**Comment by jkohnert** [comment]
@seberg just tried deleting the `numpy/` and the PlPlot build succeeded. I'll try to provide a PR for this.

@charris I'm not sure if I understand you. All the PlPlot package does is including `arrayobject.h`. Since we're way before using any code of Numpy, I'm not sure how to initialise. Does another another header provide any c-code to initialise something that is required to be done before one can include `arrayobject.h`? Or are you talking about a git submodule? Anything in Python?

**Comment by rgommers** [comment]
I don't think a change in numpy include style is the right thing to do here. Searching an installed numpy, there are quite a few include styles:
```bash
halffloat.h:#include <numpy/npy_math.h>
npy_math.h:#include <numpy/npy_common.h>
random/distributions.h:#include "numpy/npy_common.h"
random/distributions.h:#include "numpy/npy_math.h"
random/distributions.h:#include "numpy/random/bitgen.h"
numpyconfig.h:#include "_numpyconfig.h"
npy_3kcompat.h:#include "numpy/npy_common.h"
npy_3kcompat.h:#include "numpy/ndarrayobject.h"
npy_2_complexcompat.h:#include <numpy/npy_math.h>
ufuncobject.h:#include <numpy/npy_math.h>
ufuncobject.h:#include <numpy/npy_common.h>
npy_cpu.h:#include "numpyconfig.h"
npy_common.h:#include "numpyconfig.h"
__multiarray_api.h:#include "numpy/_public_dtype_api_table.h"
```

The actual problem I think is this line in PLPlot: https://github.com/PLplot/PLplot/blob/95bf7ebfe56154dda5fd4301a3ab7927848a7623/bindings/python/plplotc.i#L53

That should be `#include <numpy/arrayobject.h>`, not `#include <arrayobject.h>`.

**Comment by jkohnert** [comment]
@rgommers Uh, using the wrong `-I` directory and so specifiying the wrong path in the include statement would actually explain the error. And that would also mean, the whole thing as nothing to do with any gcc version threating things other than older versions. It was simply by chance, because the release dates of gcc-14 and numpy-2 were close to each other.

I'll patch PlPlot and test this. If it works, I'll send a PR there hoping it will get accepted.

Thank's again, I had unfortunately not seed that part. :disappointed: 

I'll report back. If this change solve my problem, I'll close that issue.

Best, Jan

**Comment by rgommers** [comment]
Sounds good, thanks @jkohnert!

**Comment by jkohnert** [comment]
The PLplot build runs just fine using the corrected include paths. So I'll close this issue. I just created a PR to get it fixed in PLplot. 

Thanks again, and best regards Jan
