### ISSUE TITLE
Array API - `np.sum` returns a scalar instead of an array/missing `.device` attribute

### ISSUE THREAD

**Issue by betatim** [numpy/numpy#26850]
With Numpy 2 I observed the following behaviour. I think it makes sense that an array now has a `.device` to fit in with the array API. It makes sense that a Numpy scalar doesn't have that attribute as the array API doesn't have scalars. It makes sense that `np.sum` returns a scalar. However, in the array API it says that `sum` should return an array.

I found this because we have a test in scikit-learn that checks that the `.device` attribute of the input and output of `sum` match.

```python
In [1]: import numpy as np

In [2]: a = np.asarray([1.,2,3,4])

In [3]: a.device
Out[3]: 'cpu'

In [4]: np.sum(a)
Out[4]: np.float64(10.0)

In [5]: np.sum(a).device
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 np.sum(a).device

AttributeError: 'numpy.float64' object has no attribute 'device'
```

Not sure how to resolve this. The individual "facts" make sense but the combination somehow doesn't.

Is the most pragmatic thing to add the `.device` attribute to Numpy scalars?

**Comment by betatim** [comment]
Maybe I should have read more than just the type annotation for `sum`. If you read the text it says

> if the sum was computed over the entire array, a zero-dimensional array containing the sum; otherwise, an array containing the sums. 

A 0dim array is a scalar, I guess. But then the question is: shouldn't it also have a `.device` attribute?

**Comment by rgommers** [comment]
Thanks for the report @betatim.
 
> A 0dim array is a scalar, I guess. But then the question is: shouldn't it also have a `.device` attribute?

Yes, I think you are completely correct here. In the discussion around NEP 47, we basically came to the conclusion that NumPy's array scalars are ducktyping 0-D arrays, and that that is fine for standard compliance and that it should work in practice. So scalars currently not having a `.device` method is incomplete ducktyping, and we should fix that.

It looks like that wasn't discussed in the review of the PR that added `ndarray.device` (gh-25233), so I think we can treat it as a simple oversight.

**Comment by rgommers** [comment]
@mtsokol maybe something you can work on as a follow-up to gh-25233?

**Comment by mtsokol** [comment]
@rgommers Sure - I will work on that!

**Comment by seberg** [comment]
The attribute was added, so closing.
