### ISSUE TITLE
BUG: crash after resize on a StringDType array

### ISSUE THREAD

**Issue by egesip** [numpy/numpy#26859]
### Describe the issue:

Dear numpy team,
A simple `StringDType` array resize seems to corrupt memory:
```
    import numpy as np
    from numpy.dtypes import StringDType
    a = np.array([''], dtype=StringDType())
    a.resize(2) # corrupts memory at a[1]
    print(a[1]) # crashes or raises MemoryError or whatever
```
I think this is because `PyArray_Resize` fearlessly writes a PyObject pointer into the array when a dtype has the `NPY_ITEM_REFCOUNT` flag set:
```
    PyObject *zero = PyLong_FromLong(0);
    char* optr = PyArray_BYTES(self) + oldnbytes;
    Py_INCREF(zero);
    memcpy(optr, &zero, sizeof(zero));
```
I suspect `PyArray_Resize` should do this only when the dtype is `NPY_OBJECT`,
but I leave it to the experts who know all the implications.
Thanks!

### Reproduce the code example:

```python
import numpy as np
from numpy.dtypes import StringDType
a = np.array([''], dtype=StringDType())
a.resize(2)
print(a[1])
```

### Error message:

```shell
>>> print(a[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: Failed to load string in StringDType getitem
```

### Python and NumPy Versions:

numpy 2.0.0
python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]

**Comment by ngoldbaum** [comment]
Thanks for the report! See #26934 for a fix.
