### ISSUE TITLE
BUG: Explicitly calling in-place arithmetic methods of ndarray doesn't work with advanced slicing

### ISSUE THREAD

**Issue by MikhailRyazanov** [numpy/numpy#26874]
### Describe the issue:

Calling in-place methods explicitly should be equivalent to using corresponding operators; for example, executing `a.__iadd__(b)` should have the same effect on `a` as executing `a += b`. However, when advanced slicing is used for `a`, executing `a[...] += b` does modify `a` as expected, but `a[...].__iadd__(b)` does not.

### Reproduce the code example:

```python
import numpy as np
def ab():
    return np.array([1, 0]), np.array([0, 2])

a, b = ab(); a += b;                 print(a) # [1 2] -- OK
a, b = ab(); a.__iadd__(b);          print(a) # [1 2] -- OK

a, b = ab(); a[1:] += b[1];          print(a) # [1 2] -- OK
a, b = ab(); a[1:].__iadd__(b[1]);   print(a) # [1 2] -- OK

a, b = ab(); a[::-1] += b;           print(a) # [3 0] -- OK
a, b = ab(); a[::-1].__iadd__(b);    print(a) # [3 0] -- OK

a, b = ab(); a[(1, 0),] += b;        print(a) # [3 0] -- OK
a, b = ab(); a[(1, 0),].__iadd__(b); print(a) # [1 0] -- wrong (not changed)
```

### Error message:

No error or warning messages.

### Python and NumPy Versions:

2.0.0
3.11.9 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0]

(Same results with NumPy 1.26.4 in Python 3.12.4.)

**Comment by seberg** [comment]
This is identical to:
```
tmp = arr[index]
tmp += values
```
Advanced indexing is documented to copy, so this cannot work.  I think there were ideas once whether you can warn that a result is temporary in nature and lost.  But there is no way to do so reliably, unfortunately (numpy guesses sometimes, but that guessing is platform specific and still a guess).

**Comment by MikhailRyazanov** [comment]
@seberg, but ``a[(1, 0),] += b`` does modify ``a``, and simply ``a[(1, 0),] = b`` also modifies ``a``, so the statement “Advanced indexing always returns a _copy_ of the data” is not true, since assigning to whatever it returns in fact affects the original data.

Moreover, ``a[(1, 0),] += b`` works at least faster (not sure about memory efficiency) than ``a[(1, 0),] = a[(1, 0),] + b`` or ``a[(1, 0),] = a[(1, 0),].__iadd__(b)``, even though Python documentation [says](https://docs.python.org/3.3/reference/datamodel.html#object.__iadd__) that “``x += y`` is equivalent to ``x = x.__iadd__(y)``”. Is there something wrong with Python itself?

In any case, if you don't consider the current behavior a bug, what is the proper and efficient way to do an in-place operation with advanced slicing when the operation cannot be hard-coded (for example, to write a generic function parametrized with a binary operation)?

**Comment by MikhailRyazanov** [comment]
Hm, I think I misunderstood Python internals: while it doesn't allow to overload assignments, it actually treats assignments to indexed objects very differently and makes them overloadable using `.__setitem__()`. So it seems that
```python
x[<expr>] += y
```
in fact translates to
```
idx = <expr>
tmp1 = x.__getitem__(idx)
tmp2 = tmp1.__iadd__(y)
x.__setitem__(idx, tmp2)
```
and there's really no way to implement truly in-place operations using regular Python syntax and available object methods (except making an overcomplication that `__getitem__` returns some proxy object, which is recognized by `__iadd__`, and then its result is recognized by `__setitem__`). Is this correct?
Would be helpful if documentation was more clear about these details...
