### ISSUE TITLE
BUG: Numpy2 breaks str() on list of numpy scalars

### ISSUE THREAD

**Issue by varchasgopalaswamy** [numpy/numpy#26907]
### Describe the issue:

Perhaps this has already been noticed/fixed/considered acceptable, but if not, if you have a list of numpy scalars, the dtype of the scalar is added to the string representation in numpy 2, but was not in older versions of numpy

### Reproduce the code example:

```python
import numpy as np 
nums = [np.int32(2)] 
str(nums)
# Produced "[2]" in numpy < 2 
# Produces "[np.int32(2)]" in numpy >= 2
```

### Python and NumPy Versions:

python=3.12 
numpy=2.0

**Comment by rkern** [comment]
This was a [deliberate change](https://numpy.org/neps/nep-0051-scalar-representation.html).
