### ISSUE TITLE
BUG: mismatch in means calculated two ways on the same data

### ISSUE THREAD

**Issue by schekroud** [numpy/numpy#26911]
### Describe the issue:

I'm working on some data and want to demean a specific axis. One way of doing this is looping over all the other dimensions and subtracting the mean of the relevant axis. This is super inefficient as you have more dimensions and levels of each dimension, and scales poorly.

alternatively, you can calculate the mean across the relevant axis and subtract in one step without a loop, which should be much faster. These two methods should result in numerically the same values, but they don't. Admittedly the decimal place at which they're different is very small, but i wanted to flag this in case there's something wrong as they should be numerically equal.

### Reproduce the code example:

```python
np.random.seed(123)
tmp = np.random.random([10,10,10])
tmp2 = np.zeros_like(tmp) * np.nan
for x in range(10):
    for y in range(10):
        tmp2[x, :, y] = np.subtract(tmp[x, :, y], tmp[x,:,y].mean())
imean = np.mean(tmp.copy(), axis=1, keepdims=True)
tmp3 = tmp.copy()
tmp3 = np.subtract(tmp3, imean)

np.equal(tmp2, tmp3).sum() == tmp2.size #evaluates as false
```

### Python and NumPy Versions:

numpy: 1.24.3
sys: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'filepath': 'C:\\Users\\sammirc\\anaconda3\\envs\\mne\\Library\\bin\\mkl_rt.2.dll',
  'internal_api': 'mkl',
  'num_threads': 6,
  'prefix': 'mkl_rt',
  'threading_layer': 'intel',
  'user_api': 'blas',
  'version': '2023.1-Product'},
 {'filepath': 'C:\\Users\\sammirc\\anaconda3\\envs\\mne\\vcomp140.dll',
  'internal_api': 'openmp',
  'num_threads': 12,
  'prefix': 'vcomp',
  'user_api': 'openmp',
  'version': None},
 {'filepath': 'C:\\Users\\sammirc\\anaconda3\\envs\\mne\\Library\\bin\\libiomp5md.dll',
  'internal_api': 'openmp',
  'num_threads': 12,
  'prefix': 'libiomp',
  'user_api': 'openmp',
  'version': None}]

**Comment by WarrenWeckesser** [comment]
Finite precision floating point arithmetic is not associative.  When you do mathematically equivalent operations in different orders, the rounding errors accumulate differently, and therefore the end result can be different ([obligatory link](https://dl.acm.org/doi/10.1145/103162.103163)).  So the difference that you see (roughly 2.22e-16) is normal.
