### ISSUE TITLE
BUG: <Please write a comprehensive title after the 'BUG: ' prefix>

### ISSUE THREAD

**Issue by masaduzz1** [numpy/numpy#26925]
### Describe the issue:

np.base_repr() gives wrong results time to time for the ternary number. I am not sure what is causing the issue.

### Reproduce the code example:

```python
import numpy as np

for i in range(10):
    print(np.base_repr(i,3))
    
np.base_repr(10,3)
```

### Error message:

```shell
Output:

0
1
2
10
11
12
20
21
22
100

'101'
```

### Python and NumPy Versions:

Python 3.12.4
Numpy version: '1.26.4'

### Runtime Environment:

[{'numpy_version': '1.26.4',
  'python': '3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, '
            '15:12:24) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='lft', release='5.15.0-113-generic', version='#123~20.04.1-Ubuntu SMP Wed Jun 12 17:33:13 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/asad/anaconda3/envs/Cirq/lib/python3.12/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'},
 {'architecture': 'Haswell',
  'filepath': '/home/asad/anaconda3/envs/Cirq/lib/python3.12/site-packages/scipy.libs/libscipy_openblas-c128ec02.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27.dev'}]

### Context for the issue:

I work with multi-level quantum system called qudits. Any physicist who works with higher levels might face the issue.

**Comment by WarrenWeckesser** [comment]
The output looks correct. What do you think is wrong?

**Comment by masaduzz1** [comment]
brain fart, looks correct. I will delete this.
