### ISSUE TITLE
BUG: linter didn't fail with very long line

### ISSUE THREAD

**Issue by paddyroddy** [numpy/numpy#26936]
### Describe the issue:

My commit [`ff27a7c` (#26935)](https://github.com/numpy/numpy/pull/26935/commits/ff27a7c30f45ff39f6555be54b1fc65e75cc1f60) didn't fail in CI despite it being 147 characters long https://github.com/paddyroddy/numpy/blob/dd12807b3b9d51e45105db96a2131c74a20e5614/numpy/f2py/tests/test_array_from_pyobj.py#L342

### Reproduce the code example:

```python
python tools/linting.py
```

### Python and NumPy Versions:

`Python 3.12.4` and on `main`/CI

**Comment by seberg** [comment]
Seems `f2py` just isn't linted, see `tools.linter.py`.  Dunno if that could be made more precise, I suspect there is a reason it isn't, but it could be that whitespace cleanups over time have made it more manageable.

**Comment by rgommers** [comment]
Excluding `numpy/f2py`, as done in `tools/linter.py`, was on purpose when the linting was introduced. The code is too much of a mess and too hard to update, plus that would yield merge conflicts with PRs. 

I had a quick sanity check, but that hasn't changed:
```
$ ruff check numpy/f2py/
Found 314 errors.
[*] 30 fixable with the `--fix` option (3 hidden fixes can be enabled with the `--unsafe-fixes` option).
```

So I'll close this as `wontfix`.

**Comment by paddyroddy** [comment]
> Seems `f2py` just isn't linted, see `tools.linter.py`. Dunno if that could be made more precise, I suspect there is a reason it isn't, but it could be that whitespace cleanups over time have made it more manageable.

Hadn't spotted that, cheers.
