### ISSUE TITLE
BUG: `pip install -r requirements/all_requirements.txt` installs `numpy==2.0.0`

### ISSUE THREAD

**Issue by paddyroddy** [numpy/numpy#26933]
### Describe the issue:

Following the DevDocs https://numpy.org/devdocs/dev/development_environment.html#using-virtual-environments it says `python -m pip install -r requirements/all_requirements.txt`. I've narrowed it down to `python -m pip install -r requirements/doc_requirements.txt`. It installs `numpy==2.0.0`.

### Reproduce the code example:

```python
python -m pip uninstall numpy
python -m pip install -r requirements/doc_requirements
python -m pip freeze | grep numpy==2.0.0
```

### Python and NumPy Versions:

`Python 3.12.4`. Working on `main` branch, commit c1d1ff4548.

**Comment by mattip** [comment]
That installs scipy and matplotlib and they require numpy. Why is that a problem?

**Comment by paddyroddy** [comment]
It's just confusing to install the latest release when trying to work on the development version

**Comment by paddyroddy** [comment]
Fair enough!

**Comment by rgommers** [comment]
Indeed. Circular dev dependencies are inevitable for NumPy. It shouldn't hurt. I'll close this, since there's nothing to change here.
