### ISSUE TITLE
ENH: add sphinx-copybutton to the documentation

### ISSUE THREAD

**Issue by mosc9575** [numpy/numpy#26948]
### Proposed new feature or change:

I suggest to add the [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/) to the sphinx extensions.

This would allow to copy code blocks and examples to the clipboard without text prompts. This is super useful to try some code from the documentation and avoids unnecessary editing and removals for the user.

The main change will be in [conf.py](https://github.com/numpy/numpy/blob/main/doc/source/conf.py), where the extension has to be listed.

```
extensions = [
    ...
    'sphinx_copybutton'
    ...
]
```

This extension is used in other projects like `pandas` and `bokeh`, too.

I found a very old issue ([#4016](https://github.com/numpy/numpy/issues/4016)), which was asking for a similar feature.

If wanted, I can open a pull request.

**Comment by rgommers** [comment]
Thank you @mosc9575. A PR for this is very welcome.
