### ISSUE TITLE
BUG: Certain non zero arrays sum to zero

### ISSUE THREAD

**Issue by alarichartsock** [numpy/numpy#26947]
### Describe the issue:

Certain arrays generated with math.comb yield 0 when passed to np.sum. 

There might be a logical explanation for this but I've been investigating this for hours and don't have a resolution so far. 

Other observations:

Removing the array brackets fixes the issue
Using Python's built in Sum function fixes the issue
![Screenshot from 2024-07-13 22-11-02](https://github.com/user-attachments/assets/56f31b45-22bb-4013-9422-67a5786400b3)

### Reproduce the code example:

```python
import numpy as np
import math

def number_regions(Di, D):
    N = np.sum([math.comb(D, i) for i in range(Di+1)])
    return N

g = number_regions(100, 62)
h = number_regions(100, 63)
i = number_regions(100, 64)
j = number_regions(100, 65)
k = number_regions(100, 66)
l = number_regions(100, 67)
m = number_regions(100, 68)

print(g, h, i, j, k, l, m)
```

### Error message:

```shell
4611686018427387904 -9223372036854775808 0 0 0 1.4757395258967641e+20 295147905179352825856
```

### Python and NumPy Versions:

2.0.0
3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)]

### Runtime Environment:

[{'numpy_version': '2.0.0',
  'python': '3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red '
            'Hat 14.1.1-5)]',
  'uname': uname_result(system='Linux', node='fedora', release='6.9.7-200.fc40.x86_64', version='#1 SMP PREEMPT_DYNAMIC Thu Jun 27 18:11:45 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'filepath': '/usr/lib64/libgomp.so.1.0.0',
  'internal_api': 'openmp',
  'num_threads': 12,
  'prefix': 'libgomp',
  'user_api': 'openmp',
  'version': None},
 {'architecture': 'Haswell',
  'filepath': '/home/alaric/Programming/udlbook/Notebooks/.venv/lib/python3.12/site-packages/numpy.libs/libscipy_openblas64_-99b71e71.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]

**Comment by yairchu** [comment]
It's due to integer overflow.

See this modified example without numpy:

```Python
import math

for k in range(62, 69):
    elems = [math.comb(k, i) for i in range(100+1)]
    res = sum(elems)
    print(k, res, res % 2**64, any(x > 2**63 for x in elems))
```

It shows that the values producing zero happen to be zero when calculating modulo over 2**64, which is the accuracy allowed by `int64`. Numpy will use `int64` if all the values in the given list fit, which isn't the case for `[number_regions(100, x) for x in [67, 68]]`

**Comment by seberg** [comment]
NumPy indeed doesn't protect you from overflows by design (it mostly warns for scalars).  There are other open issues about potentially doing more (which you can thumb up or comment on if you like).
So closing.
