### ISSUE TITLE
BUG: Converting Pytorch tensor to np.ndarray using np.asarray() is broken in 2.0.0

### ISSUE THREAD

**Issue by JonasDeSchouwer** [numpy/numpy#26951]
### Describe the issue:

When converting a Pytorch tensor to a np.ndarray using np.asarray(), I get a ValueError.
This seems undesirable as it will break a lot of code, and I did not find any references to this behaviour upon a (quick) search through the migration guide.

For instance, I came upon this problem by noticing that scikit-learn raised an error at this line https://github.com/scikit-learn/scikit-learn/blob/d79cb58c464f0b54bf0f0286c725d2df837574d0/sklearn/utils/_array_api.py#L828

### Reproduce the code example:

```python
import torch
import numpy as np

# version information
print(torch.__version__)    # 2.1.0+cu121
print(np.__version__)       # 2.0.0

a = torch.randn(100)
b = np.asarray(a)    # raises error

# b = np.array(a) raises the same error
# b = a.numpy() still works
```

### Error message:

```shell
ValueError                                Traceback (most recent call last)
Cell In[19], line 2
      1 a = torch.randn(100)
----> 2 b = np.asarray(a)

ValueError: object __array__ method not producing an array
```

### Python and NumPy Versions:

2.0.0
3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]

### Runtime Environment:

conda create -n myenv python=3.10
conda activate myenv

pip install torch==2.1.0+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
pip install numpy==2.0.0

### Context for the issue:

This will break a lot of existing code, so:
- ideally, it would be made to work again
- if that is not possible, it should be mentioned in the migration guide.

**Comment by seberg** [comment]
There is nothing that changed in NumPy.  This is a torch issue if anything, although probably the only issue is that `pip` should be printing a warning that you installed incompatible versions, but `torch` didn't pin versions (for that old one).
