### ISSUE TITLE
DOC: Hamming window formula is wrong in doc numpy.hamming

### ISSUE THREAD

**Issue by liuwei-git** [numpy/numpy#26965]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/generated/numpy.hamming.html#numpy.hamming

The code implementation is right:

`0.54 + 0.46*cos(pi*n/(M-1))`

but in the doc, the sign before 0.46 should be positive.

So, w(n) = 0.54 - 0.46\\cos\\left(\\frac{2\\pi{n}}{M-1}\\right)
               \\qquad 0 \\leq n \\leq M-1
should change to
w(n) = 0.54 + 0.46\\cos\\left(\\frac{2\\pi{n}}{M-1}\\right)
               \\qquad 0 \\leq n \\leq M-1

**Comment by liuwei-git** [comment]
After search the articles, it looks like the doc is right, but the implementation is wrong. So close this issue

**Comment by seberg** [comment]
Both are correct: the `cos` is evaluated shifted by pi in the code.
