### ISSUE TITLE
BUG: numpy.radians() returns different results when applied with and without array indexing for input arrays with integer elements

### ISSUE THREAD

**Issue by DMcAUoS** [numpy/numpy#26974]
### Describe the issue:

The numpy.radians function will return different results if it is called while indexing the input array and the array has only integer elements. When acting on an indexed array the radians function returns an integer array, whilst when acting on the same array without indexing it returns a floating point array.
This bug was found using linux for Python 3.11.5 with numpy 1.26.3.

### Reproduce the code example:

```python
# Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
import numpy as np # np.__version__ = '1.26.3'

# Convert with indexing
v    = np.array([90, 180]) # Angles in degrees
v[:] = np.radians(v[:])    # Angles in radians
print(v)
# >>> [1 3]

# Convert without indexing
v = np.array([90, 180]) # Angles in degrees
v = np.radians(v)       # Angles in radians
print(v)
# >>> [1.57079633 3.14159265]
```

### Python and NumPy Versions:

1.26.3
3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]

### Context for the issue:

When applying angle unit conversions on vectors in spherical coordinates, indexing the array is the most efficient way to write the transformation so as to leave the radial component undisturbed. Angles in radians returned as integer values are of no practical value.
I encountered this unexpected behaviour when developing code to model satellite links for use in an academic research environment.

**Comment by mattip** [comment]
In the first snippet, you are pre-creating `v` and then using indexing to assign to it. NumPy will respect the dtype when assigning, so you should create `v` with the proper dtype:
```
v    = np.array([90, 180], dtype=np.float64)
```
