### ISSUE TITLE
BUG: right bound in numpy.random.Generator.uniform is not excluded

### ISSUE THREAD

**Issue by francescotaurone** [numpy/numpy#26978]
### Describe the issue:

The documentation for numpy.random.Generator.uniform states that the output should be over the half-open interval [low, high). 
However, due to the floating point rounding, there are cases in which the right bound is included.

### Reproduce the code example:

```python
import numpy.random
from math import ulp
while True:
    sample = numpy.random.uniform(1.0, 1.0+ulp(1.0))
    if sample > 1.0:
        break
print("Right bound = \t", 1+ulp(1.0))
print("Sample = \t",sample)
```

### Python and NumPy Versions:

1.26.3
3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

**Comment by rkern** [comment]
This is discussed in the [documentation](https://numpy.org/doc/1.26/reference/random/generated/numpy.random.Generator.uniform.html) under the description for `high`. Unfortunately, the wording of the other statements were not adjusted to efficiently communicate this possibility. This is a documentation issue; we are content with the behavior.
