### ISSUE TITLE
Numpy 1.26 not finding GLIBCXX_3.4.30

### ISSUE THREAD

**Issue by mahmoodn** [numpy/numpy#26986]
With the following information
```
Ubuntu 22.04
GCC 11.4
Python 3.12
Conda 24.5.0
```

I have installed Numpy 1.26 and Pytorch 2.5 (cloned from repo). See the following confirmation from torch installation:

```
Using /home/mahmood/miniconda3/envs/numpy_1_26/lib/python3.12/site-packages
Searching for typing-extensions==4.11.0
Best match: typing-extensions 4.11.0
Adding typing-extensions 4.11.0 to easy-install.pth file

Using /home/mahmood/miniconda3/envs/numpy_1_26/lib/python3.12/site-packages
Finished processing dependencies for torch==2.5.0a0+gite317a8b
```
In fact, I can see Torch package in `conda list`.

```
(numpy_1_26) mahmood@rtx3080:pytorch$ conda list | grep -E "torch|numpy"
# packages in environment at /home/mahmood/miniconda3/envs/numpy_1_26:
numpy                     1.26.4          py312hc5e2394_0
numpy-base                1.26.4          py312h0da6c21_0
torch                     2.5.0a0+gite317a8b           dev_0    <develop>

```

However, when I try to import torch in Python environment, I get an error related to Numpy not finding GLIBCXX_3.4.30.
```
(numpy_1_26) mahmood@rtx3080:pytorch$ python
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mahmood/pytorch/torch/__init__.py", line 359, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/mahmood/miniconda3/envs/numpy_1_26/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/mahmood/pytorch/torch/lib/libtorch_python.so)

```
Any idea on how to fix that?

**Comment by abhihjoshi** [comment]
I believe a similar issue was posted here: https://github.com/rstudio/reticulate/issues/1282

In your conda env, you should be able to say `conda install -c conda-forge gcc=12.3.0` (or whatever version latest version there may be) and it should work.

**Comment by mattip** [comment]
This is all related to pytorch, not numpy. Please continue the discussion on a pytorch issue tracker. Closing.

**Comment by mahmoodn** [comment]
> In your conda env, you should be able to say conda install -c conda-forge gcc=12.3.0 (or whatever version latest version there may be) and it should work.

Thank you.
