### ISSUE TITLE
BUG: `np.ceil`/`np.floor` fails when specified `dtype` is int

### ISSUE THREAD

**Issue by mcrumiller** [numpy/numpy#26988]
### Describe the issue:

When using `np.ceil` or `np.floor`, you cannot specify an integer return dtype.

### Reproduce the code example:

```python
import numpy as np

np.floor(3/5, dtype=np.int32)  # fails
np.ceil(3/5, dtype=np.int32)  # fails

np.floor(3/5, dtype=np.float32)  # succeeds
```

### Error message:

```shell
TypeError: No loop matching the specified signature and casting was found for ufunc floor
```

### Python and NumPy Versions:

python 3.11.7
numpy 2.0.0

**Comment by seberg** [comment]
In practice identical to gh-26766.  `dtype=` doesn't (just) specify the result, it specifies the calculation loop.  And there is no integer loop (i.e. it doesn't never causes casting of the output).

**Comment by seberg** [comment]
Closing, the PR is merged, so the particular thing should work now.
