### ISSUE TITLE
ENH: Add numpy.random.disk() for generating uniform random points within a customizable disk or circular sector

### ISSUE THREAD

**Issue by amirh0ss3in** [numpy/numpy#26999]
### Proposed new feature or change:

I'd like to propose adding a new function `disk()` to `numpy.random` for generating random points uniformly distributed within a disk, circular sector, or annulus. This function would be useful for various applications in physics simulations, computer graphics, and statistical modeling.

Proposed function implementation:

```python
import numpy as np

def disk(size=None, angle_range=(0, 2*np.pi), radius=(0, 1)):
    """
    Draw samples from a uniform distribution over a disk or circular sector.
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape. If the given shape is, e.g., (m, n, k), then
        m * n * k samples are drawn. Default is None, in which case a
        single value is returned.
    angle_range : float or tuple of floats, optional
        Range of angles (in radians) to draw from. If a single value is provided,
        it's interpreted as (0, angle_range). Default is (0, 2*pi).
    radius : float or tuple of floats, optional
        Range of radii to draw from. If a single value is provided,
        it's interpreted as (0, radius). Default is (0, 1).
    
    Returns
    -------
    out : ndarray
        Drawn samples from the parameterized disk distribution.
        The shape of the output is (size, 2) if size is an int or tuple,
        or (2,) if size is None.
    
    Examples
    --------
    >>> np.random.disk()
    array([-0.35795712, -0.10633531])
    
    >>> np.random.disk(size=3, angle_range=np.pi/2, radius=2)
    array([[0.91221391, 1.32474818],
           [1.82670081, 0.77325543],
           [0.04891289, 1.03447163]])
    
    >>> np.random.disk(size=3, angle_range=(np.pi/4, np.pi/2), radius=(0.5, 1))
    array([[0.58382925, 0.58235371],
           [0.49721824, 0.69101054],
           [0.65270298, 0.52740025]])
    """
    if size is None:
        size = 1
    else:
        try:
            np.empty(size)
        except (TypeError, ValueError):
            raise ValueError("size must be a non-negative integer or tuple of non-negative integers")
    
    # Handle angle_range parameter
    if np.isscalar(angle_range):
        angle_range = (0, angle_range)
    theta1, theta2 = angle_range
    
    # Handle radius parameter
    if np.isscalar(radius):
        radius = (0, radius)
    r1, r2 = radius
    
    # Generate random angles and radii
    phi = np.random.uniform(theta1, theta2, size)
    r = np.sqrt(np.random.uniform(r1**2, r2**2, size))
    
    # Convert to Cartesian coordinates
    x = r * np.cos(phi)
    y = r * np.sin(phi)
    
    if np.isscalar(size):
        return np.array([x[0], y[0]]) if size == 1 else np.column_stack((x, y))
    else:
        return np.column_stack((x.ravel(), y.ravel())).reshape(size + (2,))
```

This function complements existing distribution functions in `numpy.random` and provides a convenient way to generate points in a disk, circular sector, or annulus without requiring users to implement these common operations themselves.

Key features:
1. Customizable angle range for generating points in circular sectors
2. Customizable radius range for generating points in annuli or scaled disks
3. Consistent interface with other NumPy random functions (e.g., `size` parameter)
4. Uniform distribution achieved by taking the square root of the random radii

The implementation uses the following approach:
1. Generate uniform random angles (phi) between the specified angle range
2. Generate uniform random radii (r) between the specified radius range, taking the square root to ensure uniform distribution
3. Convert to Cartesian coordinates: x = r * cos(phi), y = r * sin(phi)

Here's a visualization of the function's output for a half-disk annulus:

![Visualization of np.random.disk output](https://github.com/user-attachments/assets/bc2f6b90-52dd-421a-97d9-1b3456228b50)

This image was generated using the following code:

```python
import matplotlib.pyplot as plt

disk_distribution = disk(size=1000, angle_range=(0, 0.7 * np.pi), radius=(0.5, 1))

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(111, aspect='equal')
ax.scatter(disk_distribution[:, 0], disk_distribution[:, 1], s=5)
circle1 = plt.Circle((0, 0), 0.5, color='black', fill=False)
circle2 = plt.Circle((0, 0), 1, color='black', fill=False)
ax.add_artist(circle1)
ax.add_artist(circle2)
ax.set_xlim(-1, 1)
ax.set_ylim(-1, 1)
plt.show()
```

I'm willing to contribute the implementation if this proposal is accepted. Please let me know if any additional information or changes are needed.

**Comment by rkern** [comment]
Generally, we're not interested in adding to the list of distributions to sample from in `np.random`. This would be a fine contribution to scipy, however.

**Comment by amirh0ss3in** [comment]
Thanks. I've opened an issue in scipy and suggested the change there:
https://github.com/scipy/scipy/issues/21224
