### ISSUE TITLE
Contributor names for NumPy 2.1.0 release

### ISSUE THREAD

**Issue by charris** [numpy/numpy#27005]
The release of NumPy 2.1.0 will be coming soon. Could the following folks reply to this issue with full name and a preferred mailing address? They are needed for the contributor list.

- [x] @determ1ne (Azuk 443)
- [ ] @ogidig5 (Ogidi)
- [x] @carlosilva10260
- [x] @love-bees
- [x] @quotuva
- [ ] @vahidmech

**Comment by carlosilva10260** [comment]
> The release of NumPy 2.1.0 will be coming soon. Could the following folks reply to this issue with full name and a preferred mailing address? They are needed for the contributor list.
> 
> * [ ]  @determ1ne (Azuk 443)
> * [ ]  @ogidig5 (Ogidi)
> * [ ]  @carlosilva10260
> * [ ]  @love-bees
> * [ ]  @quotuva
> * [ ]  @vahidmech

Hi, @charris. My full name is Carlos Henrique Hermanny Moreira da Silva and my preferred mailing address is chhermanny@gmail.com.

**Comment by quotuva** [comment]
Charles Harris wrote:

> The release of NumPy 2.1.0 will be coming soon. Could the following
> folks reply to this issue with full name and a preferred mailing
> address? They are needed for the contributor list.

James Joseph Thomas, jimjoe AT gmx DOT net.

**Comment by love-bees** [comment]
> The release of NumPy 2.1.0 will be coming soon. Could the following folks reply to this issue with full name and a preferred mailing address? They are needed for the contributor list.
> 
> * [ ]  @determ1ne (Azuk 443)
> * [ ]  @ogidig5 (Ogidi)
> * [ ]  @carlosilva10260
> * [x]  @love-bees
> * [ ]  @quotuva
> * [ ]  @vahidmech

Milica Dančuk smicaus@yahoo.com

**Comment by determ1ne** [comment]
name: Liangyu Zhang
email: me@azuk.top

Thanks
