### ISSUE TITLE
BUG: unsharing Linux user namespace returns EINVAL when importing numpy

### ISSUE THREAD

**Issue by desiree-rentz** [numpy/numpy#27012]
### Describe the issue:

First Bug report here. As in the title. Once numpy is imported, it is not possible to create a new Linux user namespace anymore.

It is currently quite unclear to me why importing numpy interferes with Linux namespaces.

## Software Versions

Can be reproduced across multiple python versions/os releases.

Example 1:
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'2.0.1'
```

Example 2: (a python 3.12 venv on ubuntu-jammy)
```
# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

# python3
Python 3.12.4 (main, Jun  8 2024, 18:29:57) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'2.0.1'
```

## Reproducing the error

The syscall wrapper for `unshare()` is only part of the python `os` module since python 3.12. However, the issue can be reproduced with both the `os` module, as well as using `ctypes`.

On example host 1 (Debian 12, python 3.11.2, numpy 2.0.1)  using `ctypes`:
```
$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes.util, ctypes
>>> libc = ctypes.CDLL(ctypes.util.find_library("c"))
>>> CLONE_NEWUSER = 268435456
>>> libc.unshare(CLONE_NEWUSER)
0
>>> exit()

$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes.util, ctypes, numpy
>>> libc = ctypes.CDLL(ctypes.util.find_library("c"))
>>> CLONE_NEWUSER = 268435456
>>> libc.unshare(CLONE_NEWUSER)  # should return 0 as in the example above
-1
>>> exit()
```

On example host 2 (Ubuntu 22.04, python 3.12.4, numpy 2.0.1) using the `os` module:
```
# python3
Python 3.12.4 (main, Jun  8 2024, 18:29:57) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.unshare(os.CLONE_NEWUSER)
>>> exit()

# python3
Python 3.12.4 (main, Jun  8 2024, 18:29:57) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, numpy
>>> os.unshare(os.CLONE_NEWUSER)  # should succeed as in the example above
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
>>> exit()
```

### Reproduce the code example:

```python
import numpy
import os

# removing the numpy import makes it possible to unshare the user namespace
os.unshare(os.CLONE_NEWUSER)
```

### Error message:

```shell
>>> os.unshare(os.CLONE_NEWUSER)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```

### Python and NumPy Versions:

Example Host 1 (Debian 12):
```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
2.0.1
3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
```

Example Host 2 (Ubuntu 22.04):
```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
2.0.1
3.12.4 (main, Jun  8 2024, 18:29:57) [GCC 11.4.0]
```

**Comment by JosefSchoenberger** [comment]
It seems like importing `numpy` >= 2.0.0 creates several (21 on my machine) new threads. `unshare` does not allow `CLONE_NEWUSER` for multithreaded processes (see [here](https://elixir.bootlin.com/linux/v6.10/source/kernel/fork.c#L3286) and [here](https://elixir.bootlin.com/linux/v6.10/source/kernel/fork.c#L3209)), hence the `EINVAL`.

**Comment by seberg** [comment]
Numpy ships/links to blas (usually openblas), that creates threads on init.  Sounds expected that this would break the unsharing, so I am closing it, since I don't think there is any need to worry about it.

It doesn't seem strange to me that you should do the `unshare` before importing NumPy, so I am tempted to close the issue?

**Comment by ngoldbaum** [comment]
You could also build your own NumPy that links against another BLAS that doesn't spawn threads.

**Comment by desiree-rentz** [comment]
Thanks a lot for looking into this. I believe we will find a work-around to create the user namespace before the numpy import. I will mark this issue as closed.
