### ISSUE TITLE
DOC: NEP 50 documentation out of sync

### ISSUE THREAD

**Issue by nmiles2718** [numpy/numpy#27016]
### Issue with current documentation:

With the release of numpy 2.0.0, it appears that NEP50 has been accepted and implemented.

The relevant documentation for the NEP should be updated to reflect that it is no longer a draft. Additionally, it seems like it should be moved from the "Open NEPs (under consideration)" block to the "Finished NEPs" .

https://numpy.org/neps/nep-0050-scalar-promotion.html#nep50

![image](https://github.com/user-attachments/assets/84724085-e59e-4b87-b32f-d5bb66f81630)

**Comment by harshmarke** [comment]
Can you assign this task to me?

**Comment by nmiles2718** [comment]
Sorry, I have no ability to assign a ticket.

**Comment by amedinaaa** [comment]
Put in PR [https://github.com/numpy/numpy/pull/27116](url) for this issue.
