### ISSUE TITLE
Strange result running lexsort on array with compound type

### ISSUE THREAD

**Issue by moloney** [numpy/numpy#27020]
### Describe the issue:

It seems like it is not possible to get a reasonable result from the `lexsort` function on an array with compound dtype.

### Reproduce the code example:

```python
import numpy as np
data = np.array([(2,0), (0,0), (0,1), (1,1)], dtype="i,i")
np.lexsort(data) # This just returns 0
```

### Python and NumPy Versions:

1.24.2
3.11.1 (main, Jan  7 2023, 12:37:57) [GCC 9.3.0]

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}},
 {'architecture': 'SkylakeX',
  'filepath': '/home/moloney/code/nibabel/venv/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

**Comment by eendebakpt** [comment]
Is `np.lexsort(data.reshape((1, 4)))` maybe what you are looking for? The `data` has shape `(4, )`. 
Alternatively, you could construct the array without the dtype specified.

**Comment by moloney** [comment]
Ah yes, my bad.  I missed the fact that the data needed to be in columns, thanks.

**Comment by rossbar** [comment]
I suspect the confusion arises from the compound dtype. Note that lexsort expects input keys with `(k, N)`, but in the OP example there is only one dimension:

```python
>>> data = np.array([(2,0), (0,0), (0,1), (1,1)], dtype="i,i")
>>> data.shape
(4,)
```

Therefore the result is equivalent to calling lexsort with any other 1D input:

```python
>>> a = np.arange(4, 0, -1)
>>> np.lexsort(a)
0
```

I suspect what you may actually be looking for is the `order=` kwarg in `np.sort`. The [parameter description](https://numpy.org/devdocs/reference/generated/numpy.sort.html#numpy.sort) explains how `order=` can be used with named fields to specify the comparison order. Using the original example:

```python
>>> data  # note the fields have been assigned the default names `f0` and `f1`
array([(2, 0), (0, 0), (0, 1), (1, 1)],
      dtype=[('f0', '<i4'), ('f1', '<i4')])
>>> np.sort(data, order=("f0", "f1"))
array([(0, 0), (0, 1), (1, 1), (2, 0)],
      dtype=[('f0', '<i4'), ('f1', '<i4')])
>>> np.sort(data, order=("f1", "f0"))
array([(0, 0), (2, 0), (0, 1), (1, 1)],
      dtype=[('f0', '<i4'), ('f1', '<i4')])
```

If you want indices (like lexsort), `argsort` also supports the order kwarg.
