### ISSUE TITLE
DOC: Undocumented behavior in `np.reshape` and `np.transpose`

### ISSUE THREAD

**Issue by mlabslyken** [numpy/numpy#27024]
### Issue with current documentation:

This problem is found in NumPy version 1.26.4 and the NumPy 1.26 documentation. I think this issue might also exist in other NumPy versions/documentation versions, but I have not tried looking into it deeply.
 
## Undocumented behavior with `newshape` in `np.reshape`
This is the doc on `newshape` in <https://numpy.org/doc/1.26/reference/generated/numpy.reshape.html>:
> The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. _**One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.**_

However, it appears that actually any negative integer could be used to specify the unknown dimension:
```
>>> np.arange(12).reshape((3, -999)).shape
(3, 4)
```

## Undocumented behavior with `axes` in `np.transpose`
This is the doc on `axes` in <https://numpy.org/doc/1.26/reference/generated/numpy.transpose.html>:
> If specified, _**it must be a tuple or list which contains a permutation of [0,1,…,N-1]**_ where N is the number of axes of a. The i’th axis of the returned array will correspond to the axis numbered axes[i] of the input. If not specified, defaults to range(a.ndim)[::-1], which reverses the order of the axes.

However, `axes` does not have to strictly be a permutation of [0, ..., N-1] -- you can specify axes with negative indices, but the docs could be seen as suggesting that `axes` may only contain positive integers.
```
>>> np.arange(3*4*5).reshape((3, 4, 5)).transpose((-1, 0, -2)).shape
(5, 3, 4)
```

**Comment by seberg** [comment]
Thanks for the issue.  IMO, the first on is completely fine. I simply see no reason anyone should ever use anything but `-1` (and could imagine deprecating it in theory).
I agree the second one should probably be rephrased to make it clear that this is valid (maybe also using it in an example).

**Comment by guan404ming** [comment]
Hi @seberg , I've opened a pr based on the conversation, please help me review it, thanks~
