### ISSUE TITLE
Update vendored meson

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#27044]
The currently vendored version runs into https://github.com/mesonbuild/meson/issues/13403, which breaks cross-compilation in conda-forge.

**Comment by ngoldbaum** [comment]
I think @rgommers is actively working on this.

**Comment by h-vetinari** [comment]
meson 1.5.1 is [imminent](https://github.com/mesonbuild/meson/commit/b6b634ad33e5ca9ad4a9d6139dba4244847cc0e8), which contains a whole bunch of regression fixes from the 1.5.0 cycle. Would probably be a good baseline. :)

**Comment by h-vetinari** [comment]
Just talking with Ralf about this, it might be easier to just cherry-pick https://github.com/mesonbuild/meson/commit/ccdbbbee935c6daa5f7caa59d46b7a7f7ccb9aca. I'll prepare a PR to vendored meson.

**Comment by h-vetinari** [comment]
Opened https://github.com/numpy/meson/pull/16 to cherry-pick the fix

**Comment by rgommers** [comment]
> Opened [numpy/meson#16](https://github.com/numpy/meson/pull/16) to cherry-pick the fix

Thanks for doing that @h-vetinari. This is integrated now, it will be included in 2.1.0rc1.

**Comment by mattip** [comment]
@h-vetinari is there anything left to do here?

**Comment by rgommers** [comment]
There is always another update to make until we stop vendoring Meson. The specific conda-forge issue was addressed though. I'm fine with keeping this open or closing it.

**Comment by h-vetinari** [comment]
I'm fine with closing it - the intention was to fix the broken cross compilation, which was achieved. I'm pretty sure people won't forget that we want to stop vendoring meson eventually (or even ASAP). ;)
