### ISSUE TITLE
BUG: format_float_positional rounding error for precision >= 6

### ISSUE THREAD

**Issue by PydPiper** [numpy/numpy#27064]
### Describe the issue:

Unexpected rounding from `format_float_positional` past precision >= 6. Looking at the docs `round` points you to `format_float_positonal` for "accurate" rounding however i dont see anything under `format_float_positional` that mentions this behavior past precision >= 6

If this is not a bug, I do believe the docs should say something about it under `format_float_positional`

### Reproduce the code example:

```python
# good
np.format_float_positional(-0.05, 1)
'-0.1'
# good
np.format_float_positional(-0.005, 2)
'-0.01'
# good
np.format_float_positional(-0.0005, 3)
'-0.001'
# good
np.format_float_positional(-0.00005, 4)
'-0.0001'
# good
np.format_float_positional(-0.000005, 5)
'-0.00001'
# unexpected round down
np.format_float_positional(-0.0000005, 6)
'-0.000000'
# same unexpected round down when keeping everything in numpy-land (cast from str val)
np.format_float_positional(np.float64('-0.0000005'),6)
'-0.000000'
```

Just as a side note. I did also check `format_float_scientific` 's logic for precision >= 6 and it does not have the same issue.
```python
np.format_float_scientific(-0.0000005555555555555,6)
'-5.555556e-07'
```

### Python and NumPy Versions:

python 3.11.3
numpy 1.26.4 also checked it in numpy 2.0.1

**Comment by WarrenWeckesser** [comment]
This is not a bug.  In fact, the rounding is correct.  To see why, you have to look at the *actual full precision value* of each argument in your examples.  For example, the actual value represented by `-0.00005` is not exactly `-5/100000`; that value cannot be represented exactly as a double precision floating point value.  The true value of the number stored is `-0.0000500000000000000023960868011929647991564706899225711822509765625`.  So it is correct that `np.format_float_positional(-0.00005, 4)` returns `'-0.0001`.  Similarly, for the input `-0.0000005`, the true value is `-0.0000004999999999999999773740559129431293428069693618454039096832275390625`, so `np.format_float_positional(-0.0000005, 6)` correctly returns `'-0.000000'`.

There are several ways to see the true value represented by a float.  You can print it with many extra digits of precision, e.g.
```
In [93]: x = -0.0000005

In [94]: f'{x:.76f}'
Out[94]: '-0.0000004999999999999999773740559129431293428069693618454039096832275390625000'
```
Or you can convert it to an [`mpmath`](https://mpmath.org/) float with many digits of precision, and display that value:
```
In [95]: import mpmath

In [96]: mp.dps = 1000

In [97]: mp.mpf(x)
Out[97]: mpf('-0.0000004999999999999999773740559129431293428069693618454039096832275390625')
```

**Comment by PydPiper** [comment]
Thank you for the response Warren. I suspected that this was a number representation issue, however to an engineer using this library this is an incorrect output, thus I do believe this warrants a doc warning for users with this example, but i can create a MR for that myself.
