### ISSUE TITLE
NumPy 1.21.3 universal2 wheel has wrong metadata in WHEEL

### ISSUE THREAD

**Issue by JCGoran** [numpy/numpy#27069]
### Steps to reproduce:

This is an oddly-specific issue that arises due to a combination of using `pip`, MacOS, and a rather old version of NumPy, so feel free to close this as notabug/wontfix, I just thought I'd report it in case it helps others who encounter the same problem.

When using Python 3.10 on MacOS (in x86_64 mode), and attempting to install NumPy version `1.21.3` with `pip` version `24.2`, running `pip check` all of a sudden started failing (was not the case for earlier releases of `pip`).
A reproducer is:

```plaintext
$ pip install 'pip==24.2' 'numpy==1.21.3'
$ pip check
```

which reports:
```plaintext
numpy 1.21.3 is not supported on this platform
```

After some investigation, I found that the culprit is on the NumPy side, more specifically this line in the `WHEEL` file (of [the corresponding wheel](https://files.pythonhosted.org/packages/e9/d6/0255f13fc4b89618eb514e8a170429d8aad188638633ba2e224ce88dab75/numpy-1.21.3-cp310-cp310-macosx_10_9_universal2.whl)):
```plaintext
Tag: cp310-cp310-macosx_11_0_arm64
```
and due to [this PR](https://github.com/pypa/pip/pull/11088) making it into the `24.2` release of `pip`, the `check_unsupported` method reports that that version of NumPy is unsupported, which is incorrect since the libraries inside _are_ universal, but mislabeled. It's not a huge deal for our usecase (we can use other versions of NumPy instead), but the error is admittedly a bit cryptic (maybe I should report this to the `pip` issue tracker instead?).

**Comment by mattip** [comment]
NumPy provided a universal2 wheel (which contain binary extensions compiled so they can run on both arm64 and x86_64) for that version. But looking at the distinfo/WHEEL file in the [download files on PyPI](https://pypi.org/project/numpy/1.21.3/#files), I see the tag is `Tag: cp310-cp310-macosx_11_0_arm64`. Maybe that is tricking pip, which now checks the metadata in distinfo, into thinking this wheel is only for `arm64`? In any case, we no longer produce universal2 wheels: each architecture is separate.

**Comment by rgommers** [comment]
Thanks for the detailed report @JCGoran. It isn't too surprising that the metadata is slightly off; 1.21.x was the first release to support macOS arm64 and there was some manual massaging needed to get the wheels built. 

I think it'd be good to report to `pip` indeed, so they can decide whether this is okay or not. 

For NumPy it's a `wontfix` indeed, we can't update releases that are several years old. I'll label this issue as such right now; we can leave it open for a day or two for discoverability, in case others run into it.

**Comment by ngoldbaum** [comment]
Nothing NumPy can do about this short of uploading new artifacts for an old release, which we're not going to do I think.
