### ISSUE TITLE
ENH: re-include np.source

### ISSUE THREAD

**Issue by digitalsignalperson** [numpy/numpy#27078]
### Proposed new feature or change:

Small QOL request. This was removed here https://github.com/numpy/numpy/pull/24144

I frequently use this pattern in a qtconsole:
```
%pylab qt

# ... do stuff

# look up source for something
source(np.angle)

# possibly open the shown path and poke around
```

This was handy to have available. The function is really simple, just printing source path and the source:
```python
import inspect
print("In file: %s\n" % inspect.getsourcefile(object), file=output)
print(inspect.getsource(object), file=output)
```

The release notes say 
> ``np.source`` has been removed. The preferred replacement is   ``inspect.getsource``.

There's a convenience factor in np.source printing both the path and source, and being available in the namespace. But fair enough if it stays out. It's not exactly a numerical function

**Comment by rkern** [comment]
I don't think we're going to revisit this decision. We removed it deliberately, knowing all this information.
