### ISSUE TITLE
BUG: astype() function does not work on scalars

### ISSUE THREAD

**Issue by asmeurer** [numpy/numpy#27072]
### Describe the issue:

The new `astype()` function does not work on NumPy scalars. 

```
>>> np.astype(np.float32(0.), np.float64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/numpy/numpy/_core/numeric.py", line 2688, in astype
    raise TypeError(
TypeError: Input should be a NumPy array. It is a <class 'numpy.float32'> instead.
>>> np.float32(0.).astype(np.float64)
np.float64(0.0)
```

Note that this breaks with array API compatibility. 

CC @mtsokol 

### Reproduce the code example:

```python
>>> np.astype(np.float32(0.), np.float64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/numpy/numpy/_core/numeric.py", line 2688, in astype
    raise TypeError(
TypeError: Input should be a NumPy array. It is a <class 'numpy.float32'> instead.
>>> np.float32(0.).astype(np.float64)
np.float64(0.0)
```

### Python and NumPy Versions:

2.1.0.dev0+git20240728.fdcbd0e
3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]

### Context for the issue:

This leads to test failures in the array-api-tests test suite (test_unique_inverse and test_unique_values). If you are running those tests on CI you may want to investigate whey you didn't notice this earlier.

**Comment by asmeurer** [comment]
As for how this was missed, the test runs on CI are using `--max-examples=2`, which makes them almost useless https://github.com/numpy/numpy/blob/fdcbd0ef1911c554e488087354b0a458ac52a40d/.github/workflows/linux.yml#L256. With only 2 examples, hypothesis is only going to generate the most trivial of example inputs to the test functions. See https://github.com/data-apis/array-api-tests/pull/246#issuecomment-2048536237. Just to show what I mean, the above mentioned unique tests would fail with any floating-point array input, meaning that floating-point arrays are completely untested for these tests with --max-examples=2. 

Note that the test suite is much faster than it used to be and there should not be a need to reduce the number of max examples on the NumPy CI.

**Comment by mtsokol** [comment]
Hi @asmeurer,

I'll take a look at it. It seems like `astype` should also support scalars.

About `array-api-tests` comment: In this PR https://github.com/numpy/numpy/pull/27081 I increased `--max-examples` to `50` and it only failed with three more errors compared to `--max-examples=2`, where the first one seems to be the `scalar+astype` one that you described here and two more are related to missing `descending` keyword in `sort` and `argsort` (so then they should be skipped as we don't support that keyword).

Is `--max-examples=50` Ok to fully utilize `array-api-tests` suite capabilities?

**Comment by mtsokol** [comment]
To be fixed in https://github.com/numpy/numpy/pull/27081
