### ISSUE TITLE
`full` and `full_like` permit out-of-bounds Python integers

### ISSUE THREAD

**Issue by ndgrigorian** [numpy/numpy#27075]
`full` and `full_like` permit out-of-bounds Python integers, which is inconsistent as of Numpy 2.0.

```
In [2]: import numpy as np

In [3]: np.full(10, -1, dtype="u1")
Out[3]: array([255, 255, 255, 255, 255, 255, 255, 255, 255, 255], dtype=uint8)

In [4]: np.full_like(np.ones(10, dtype="u1"), -1, dtype="u1")
Out[4]: array([255, 255, 255, 255, 255, 255, 255, 255, 255, 255], dtype=uint8)

In [5]: np.arange(-5, 0, 1, dtype="u1")
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Cell In[5], line 1
----> 1 np.arange(-5, 0, 1, dtype="u1")

OverflowError: Python integer -5 out of bounds for uint8
```

`asarray` and `arange` don't permit it, and this is a (very) malformed workflow, so it seems logical to change.

**Comment by WarrenWeckesser** [comment]
This behavior goes all the way back to when `full` and `full_like` were added to numpy: https://github.com/numpy/numpy/pull/2875

The relevant lines for `full` are https://github.com/numpy/numpy/blob/36b7ff9c963233ed8365696ab97c085eaf3cfd98/numpy/_core/numeric.py#L365-L366

More specifically, the argument `casting='unsafe'` is the source of the issue.

I didn't find any discussion of the casting behavior in the pull request nor in the two long mailing list threads about these new functions.  We could prevent the problem reported here by changing that argument to `casting='safe'`, which would result in this behavior:

```
In [2]: np.full(10, -1, dtype='u1')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 np.full(10, -1, dtype='u1')

File ~/repos/git/forks/numpy/build-install/usr/lib/python3.12/site-packages/numpy/_core/numeric.py:366, in full(shape, fill_value, dtype, order, device, like)
    364     dtype = fill_value.dtype
    365 a = empty(shape, dtype, order, device=device)
--> 366 multiarray.copyto(a, fill_value, casting='safe')
    367 return a

TypeError: Cannot cast scalar from dtype('int64') to dtype('uint8') according to the rule 'safe'
```

but I don't know how disruptive such a change would be.

**Comment by seberg** [comment]
This is changed on main/2.1, just forgot to close.
