### ISSUE TITLE
BUG: np.shares_memory() docs refer to MAY_SHARE_EXACT, which has no public name in 2.0

### ISSUE THREAD

**Issue by hawkinsp** [numpy/numpy#27089]
### Describe the issue:

In 1.x, NumPy used to export `MAY_SHARE_EXACT` and `MAY_SHARE_BOUNDS` under the top-level numpy namespace.

These constants are passed as arguments to the `max_work` kwarg to `np.shares_memory` and `np.may_share_memory`, and are still documented in NumPy 2.0 (https://numpy.org/doc/stable/reference/generated/numpy.shares_memory.html#numpy.shares_memory).

There doesn't seem to a public name for these constants any more. As best I can tell, they are only available as `np._core.multiarray.MAY_SHARE_EXACT`.

How should users refer to these constants?

### Reproduce the code example:

```python
n/a
```

### Error message:

```shell
n/a
```

### Python and NumPy Versions:

n/a

### Runtime Environment:

n/a

### Context for the issue:

Found when trying to migrate code that uses `np.may_share_memory` to NumPy 2.

**Comment by seberg** [comment]
It's just -1, we should document that as valid.

**Comment by guan404ming** [comment]
Hi @seberg, I've opened a PR to address this issue, please help me review it, thank you~~
