### ISSUE TITLE
BUG: I need urgent help!Numpy and Pandas incompatibility: ' prefix>

### ISSUE THREAD

**Issue by hadisyekta** [numpy/numpy#27084]
### Describe the issue:

when I am trying to use pickle.loads a scale(most recent call last): 2024-07-15 10:20:22.594 workerpool0-0 File "/app/src/inference.py", line 212, in <module> 2024-07-15 10:20:22.594 workerpool0-0 scaler = read_from_gcs(project_id=PROJECT_ID, gcs_df_location=SCALER_FILE_PATH, bucket_name=BUCKET, file_format='scaler', gcs_scaler_location=SCALER_FILE_PATH) 2024-07-15 10:20:22.594 workerpool0-0 File "/app/src/inference.py", line 44, in read_from_gcs 2024-07-15 10:20:22.594 workerpool0-0 scaler = pickle.loads(pickle_content) 2024-07-15 10:20:22.594 workerpool0-0 ModuleNotFoundError: No module named 'numpy._core'r data I am receiving `ModuleNotFoundError: No module named 'numpy._core'` 
and I searched a lot and tried several versions of numpy and pandas, couldn't resolve this ..

### Reproduce the code example:

```python
def read_from_gcs(project_id: str, gcs_df_location: str, bucket_name: str, file_format: str, gcs_scaler_location: str):
    """Reads the dataframe in a parquet format from GCS.

    Args:
        project_id (str): Google Cloud project ID.
        gcs_df_location (str): File path of Dataframe inside the bucket.
        bucket_name (str): Bucket Name.
        file (str): indicator to choose file to read. Either 'df' or 'scaler'.
        gcs_scaler_location (str): File path of scaler inside the bucket.
        
    Returns:
        pd.DataFrame: Dataframe
    """
    storage_client = storage.Client(project= project_id)
    bucket = storage_client.bucket(bucket_name)
    
    if file_format == 'df':
        #Save the parquet file to local first, then delete
        file = 'components\\inference\\read.parquet'
        blob = bucket.blob(gcs_df_location)
        blob.download_to_filename(file)
        df= pd.read_parquet(file)
        
        os.remove(file)
        
        return df
    elif file_format == 'scaler':
        file = 'components\\inference\\scaler.pickle'
        blob = bucket.blob(gcs_scaler_location)
        pickle_content = blob.download_as_string()
        scaler = pickle.loads(pickle_content)
        # print(scaler)
        
        return scaler
```

### Error message:

```shell
scaler = read_from_gcs(project_id=PROJECT_ID, gcs_df_location=SCALER_FILE_PATH, bucket_name=BUCKET, file_format='scaler', gcs_scaler_location=SCALER_FILE_PATH)  workerpool0-0 File "/app/src/inference.py", line 44, in read_from_gcs 2024-07-15 10:20:22.594 workerpool0-0 scaler = pickle.loads(pickle_content) 2024-07-15 10:20:22.594 workerpool0-0 ModuleNotFoundError: No module named 'numpy._core'
```

### Python and NumPy Versions:

Python 3.9.7
numpy==2.0.1
pandas==2.2.2

### Runtime Environment:

function> 

### Context for the issue:

I am creating a vertexAI pipeline on gcp and it blocked my work

**Comment by ngoldbaum** [comment]
This error happens when you create a pickle file with numpy 2.x and try to load it with numpy 1.x. This won't work, since numpy 2.x moved some internals that the pickle file encodes directly into the file, and numpy 1.x can't account for that. Make sure that both workers have the same version of numpy installed.

**Comment by jakirkham** [comment]
Also would recommend reading [this blogpost on why not to use pickle for storing data]( https://ericmjl.github.io/blog/2024/7/2/use-native-formats-when-storing-data/ )
