### ISSUE TITLE
CI,BUG: windows 32 bit CI runs flaky on`test_ufunc_noncontiguous` ldexp/frexp

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#27093]
The test didn't fail on the original PR but now often do.  That is:
```
test_ufunc_noncontiguous
```
fails for `ldexp` and `frexp`.

The failures are harmless w.r.t. to unrelated changes: They are not new, the test is just new.

@r-devulap do you have time to have a look at fixing `ldexp` and `frexp`?  Not sure what is best, aligning to use `npyv_loadable_stride_##sfx/npyv_storable_stride_##sfx`, or just adding the alignment check that some of the other macros already have here.
The choice of the max stride is also slightly different, although I think compatible.

_Originally posted by @seberg in https://github.com/numpy/numpy/issues/27027#issuecomment-2265044219_

**Comment by seberg** [comment]
That won't work without care, because for some reason the avx512 version uses 64bit-indexed gather (for 64bit values), while these use 32bit-indexed one.  So it would need adapting the generic check as well.

For backporting, maybe a quick fix is best...  Although it would still be good to align the exponential code.
(And maybe use the macros from there in other places, since they are more compact.)

**Comment by r-devulap** [comment]
@seberg will take a look at it today

**Comment by charris** [comment]
@r-devulap Any progress?

**Comment by r-devulap** [comment]
@charris still working on it :/
