### ISSUE TITLE
BUG: zero-width histogram bins if the data values are in a small range close to numeric precision

### ISSUE THREAD

**Issue by timhoffm** [numpy/numpy#27142]
### Describe the issue:

`np.histogram` can produce zero-width bins if the data values are in a small range close to numeric precision. Noted in https://github.com/matplotlib/matplotlib/issues/28685

I'm aware that there is no reasonable representation / that calculating a reasonable representation close to the numeric precision is not possible. But would it be an option to check the bin-width and error out instead of returning nonsense histogram binning?

### Reproduce the code example:

```python
In [1]: import numpy as np

In [2]: a = np.array([1, 1+2e-16] * 10)

In [3]: counts, lims = np.histogram(a, bins=10)

In [4]: counts
Out[4]: array([ 0, 10,  0,  0,  0,  0,  0,  0,  0, 10])

In [5]: lims
Out[5]: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]: np.diff(lims)
Out[6]: 
array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.22044605e-16, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00])
```

### Python and NumPy Versions:

numpy 1.26.4
python 3.12.2

**Comment by timhoffm** [comment]
I saw there is already a check for monotony:

https://github.com/numpy/numpy/blob/69e28452df4c4cd8671557c834bb6e2a99b4fe28/numpy/lib/_histograms_impl.py#L434

Is there a reason = is accepted or could this check be changed to `>=`?

**Comment by mattip** [comment]
A PR with a test for this edge case might expose where other tests could fail.

**Comment by ngoldbaum** [comment]
This vaguely sounds like https://github.com/numpy/numpy/issues/23110 which was supposed to be solved by https://github.com/numpy/numpy/pull/24161
