### ISSUE TITLE
FloatingPointError with logaddexp([-inf], [-inf])

### ISSUE THREAD

**Issue by roger-** [numpy/numpy#2714]
Get this with NumPy 1.6.2 (32 bit) on Windows 7:

``` python
    >> np.seterr('raise');print np.logaddexp([-inf], [-inf])
    FloatingPointError: invalid value encountered in logaddexp
```

The correct result  `log(0) = -inf` is returned, but I think this is a common enough use-case that `logaddexp()` should account for it without raising any warnings/exceptions.

**Comment by seberg** [comment]
Seems fixed long ago in gh-5113
