### ISSUE TITLE
BUG: repeated axis is ignored in real FFT

### ISSUE THREAD

**Issue by vtavana** [numpy/numpy#27159]
### Describe the issue:

As shown in the example below when there is repeated axis in `axes` keyword of `numpy.fft.rfftn` it is not handled correctly.

### Reproduce the code example:

```python
import numpy as np
a = np.ones((2,3))
np.fft.rfftn(a, axes=(0, 0, 1), s=(10, 20, 40)).shape
# (20, 21) while I expect the output shape to be (10, 21)

# equivalent to a series of FFT
np.fft.fft(np.fft.fft(np.fft.rfft(a, axis=1, n=40), axis=0, n=20), axis=0, n=10).shape
# (10, 21)

# comparing with complex FFT which behaves correctly
np.fft.fftn(a, axes=(0, 0, 1), s=(10, 20, 40)).shape
# (10, 40) # This is expected

np.fft.fft(np.fft.fft(np.fft.fft(a, axis=1, n=40), axis=0, n=20), axis=0, n=10).shape
# (10, 40)
```

### Python and NumPy Versions:

2.0.0
3.12.4 | packaged by conda-forge

and

1.26.4
3.12.4 | packaged by conda-forge

**Comment by ngoldbaum** [comment]
Sorry, just to clarify, this happens with both NumPy 1.26 and NumPy 2.0 and it's not a new problem? There was a big rewrite of the FFT internals for NumPy 2.0 so if it's new it's likely because of that.

**Comment by mhvk** [comment]
Hmm, looks like there is indeed a bug there (likely old): the regular fft goes through: https://github.com/numpy/numpy/blob/8cba529f27d656069d958cfee563144efb196134/numpy/fft/_pocketfft.py#L747-L754

while `rfftn` uses https://github.com/numpy/numpy/blob/8cba529f27d656069d958cfee563144efb196134/numpy/fft/_pocketfft.py#L1401-L1406

Clearly, the last iteration is in the wrong order (should be `range(len(axes)-1, -1, -1)`) or reverse a list like for the regular case. @vtavana - interested in making a quick PR to fix this? You can use your examples for new test cases.

**Comment by Ishankoradia** [comment]
@ngoldbaum I see that the `axes` was deprecated . Does this bug still exist ?

**Comment by mhvk** [comment]
@Ishankoradia - this has not been fixes - the line numbers have changed only because some docstring comments have been removed in #27454. If you have time to create a fix (i.e., follow my above suggestion and add a test case), that would be great!

**Comment by Ishankoradia** [comment]
@mhvk sure, i will give this a shot.

**Comment by Ishankoradia** [comment]
@mhvk submitted a PR, would you review it. 
Thank you for the direction you gave.
