### ISSUE TITLE
BUG: `numpy.strings.rstrip` does not work correctly

### ISSUE THREAD

**Issue by MarkusSintonen** [numpy/numpy#27175]
### Describe the issue:

There is a bug in `numpy.strings.rstrip` that it strips incorrect characters away. See the simple repro example.

### Reproduce the code example:

```python
import numpy as np
# Gives incorrect empty string:
print(np.strings.rstrip(np.array(["10"], dtype="U10"), "0"))  # ['']
# Neither does StringDType work:
print(np.strings.rstrip(np.array(["10"], dtype="T"), "0"))  # ['']
```

### Python and NumPy Versions:

2.0.0
3.12.4 (main, Jun 18 2024, 13:47:41) [Clang 15.0.0 (clang-1500.3.9.4)]

**Comment by seberg** [comment]
Thanks for the report, this has been fixed and backported (I am not sure it is in 2.0.1 but it is fixed on main, so should be in 2.0.2).
