### ISSUE TITLE
DOC: Added documentation to bench_function_base.py

### ISSUE THREAD

**Issue by martiart** [numpy/numpy#27170]
### Issue with current documentation:

It lacks overall docstrings for classes, methods and functions. 
Additionally is missing double spacing for some classes.
Linting error after a ",". Missing space.

**Comment by seberg** [comment]
Thanks, but closing, that file doesn't need docs unless they happen to be very helpful to understand the code.  The linting issue is small enough that there is no reason to prioritize it.  If you happen to touch the file and it is so small, feel free to fix it, otherwise there is probably no point.
