### ISSUE TITLE
`download-wheels` can only find 50 names in numpy/staging, we need 52

### ISSUE THREAD

**Issue by charris** [numpy/numpy#27185]
We are apparently limited by the page size coded in the anaconda html, namely, 50 file names. Anyone know how to get a complete list?

**Comment by charris** [comment]
I was able to download the two missing files by hand, but it would be nice if everything just worked.

**Comment by andyfaff** [comment]
I'm guessing this is done as part of the release process.

In my own projects I've had good success using the [`pypa/gh-action-pypi-publish`](https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file) action and [trusted publishing on PyPI](https://docs.pypi.org/trusted-publishers/). This doesn't require long lasting tokens or username/password combos to be stored in a secret.
I have an action that gets triggered when there's an annotated tag (starting with 'v') pushed to the repo. The action builds all the wheels, makes an sdist, makes a GH release, then uses the trust publishing action to transfer all the wheels to PyPI. The automation takes a lot of potential mistakes out of the picture. 
Only complication is that I don't know just yet how to do the trusted publishing from non-GH CI.
