### ISSUE TITLE
BUG: Adding np.int64(1) to a list and converting that list in str return an str with dtype

### ISSUE THREAD

**Issue by Aman-Pinjara** [numpy/numpy#27188]
### Describe the issue:

When we create a list and have np.int64(1) as an element and when we convert that list to str the output is '[np.int64(1)]' it should be '[1]'

### Reproduce the code example:

```python
import numpy as np
str([np.int64(1)])
>>>[np.int64(1)]
```

### Python and NumPy Versions:

python version == 3.12.2
numpy version == 2.0.0

### Context for the issue:

I have test which test sql query, what the function does it, it add elements to array convert that to tuple and pass it to the SQL query through string interpolation and that function needs to work with any type of integer. So this fails the assertion and returns an invalid query

**Comment by mattip** [comment]
This changed in NumPy2. You need to update the test. This is mentioned in the [release notes](https://numpy.org/devdocs/release/2.0.0-notes.html#representation-of-numpy-scalars-changed)

**Comment by Aman-Pinjara** [comment]
Ok thanks for the change note. closing the bug report.
