### ISSUE TITLE
DOC: `PyArray_CheckAxis` doesn't refer to new `NPY_RAVEL_AXIS` macro

### ISSUE THREAD

**Issue by brendan-m-murphy** [numpy/numpy#27191]
### Issue with current documentation:

The [doc for](https://numpy.org/doc/stable/reference/c-api/array.html#c.PyArray_CheckAxis) `PyArray_CheckAxis` says that `axis=None` is checked by `*axis >= NPY_MAXDIMS`, whereas it should probably say `*axis == NPY_RAVEL_AXIS`, which is the check performed now (line 2904 of `_core/src/multiarray/ctors.c`).

**Comment by guan404ming** [comment]
Hi @brendan-m-murphy, thanks for pointing out this mistake. I've opened a PR to fix it~
