### ISSUE TITLE
DOC: `np.unique_all`, `np.unique_counts`, `np.unique_inverse`, `np.unique_values` should show an example using the function itself, not `np.unique`

### ISSUE THREAD

**Issue by jpivarski** [numpy/numpy#27214]
### Issue with current documentation:

On the documentation pages for the above-named functions,

* https://numpy.org/doc/2.0/reference/generated/numpy.unique_all.html
* https://numpy.org/doc/2.0/reference/generated/numpy.unique_counts.html
* https://numpy.org/doc/2.0/reference/generated/numpy.unique_inverse.html
* https://numpy.org/doc/2.0/reference/generated/numpy.unique_values.html

the code example shows `np.unique` with arguments like `return_index=True`, `return_inverse=True`, `return_counts=True`, and `equal_nan=False`. Although it's good to see how the new functions relate to parameterizations of `np.unique`, the lack of examples for the new functions hides the fact that their output is a namedtuple, rather than a tuple.

For instance,

```python
>>> x = np.array([1, 1, 2])
>>> np.unique(x, return_index=True, return_inverse=True, return_counts=True, equal_nan=False)
(array([1, 2]), array([0, 2]), array([0, 0, 1]), array([2, 1]))
>>> np.unique(x, return_counts=True, equal_nan=False)
(array([1, 2]), array([2, 1]))
>>> np.unique(x, return_inverse=True, equal_nan=False)
(array([1, 2]), array([0, 0, 1]))
>>> np.unique(x, equal_nan=False)
array([1, 2])
```

versus

```python
>>> np.unique_all(x)
UniqueAllResult(values=array([1, 2]), indices=array([0, 2]), inverse_indices=array([0, 0, 1]), counts=array([2, 1]))
>>> np.unique_counts(x)
UniqueCountsResult(values=array([1, 2]), counts=array([2, 1]))
>>> np.unique_inverse(x)
UniqueInverseResult(values=array([1, 2]), inverse_indices=array([0, 0, 1]))
>>> np.unique_values(x)
array([1, 2])
```

It can be useful to see the namedtuple names, `UniqueAllResult`, `UniqueCountsResult`, `UniqueInverseResult`, to know what to expect. Previously, when I didn't see these names, I was about to file a bug report, then later noticed that it was just the documentation.

**Comment by t-tasin** [comment]
Hi, I have fixed this issue by updating the documentation for `np.unique_all`, `np.unique_counts`, `np.unique_inverse`, and `np.unique_values` to show examples using the respective functions, as requested. The changes demonstrate the correct namedtuple outputs (where applicable) and clarify the function behavior. 

Please review the PR and let me know if further adjustments are needed. Thanks!
