### ISSUE TITLE
DOC: Remove outdated versionadded/changed directives?

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#27239]
We have a huge number of `versionadded` and `versionchanged` directives e.g. find with:
```
git grep -E "\.\. version(changed|added):"
```
I think we should remove them at some point, since they are not really helpful when relating to NumPy versions that are long out of use.

For example, NumPy 1.18.x only supported Python 3.8 which is EOL.  So I directive up to (and including) 1.19, would be OK to be removed.

When removing, we need to make sure that the information contained for the new paths remains documented.

---

I don't mind keeping them around if others disagree, but I do think that at some point the only purpose they serve would be understanding that past decisions were made to change behavior.

**Comment by mattip** [comment]
> I think we should remove them at some point,

Makes sense

> When removing, we need to make sure that the information contained for the new paths remains documented.

This is the hard part.

**Comment by mhvk** [comment]
:+1: One could start by just removing `.. versionadded` for any version that is beyond the support line in NEP 29/SPEC 0. Unlike for `.. versionchanged`, there is no text that one has to work elsewhere into the docstring.

**Comment by SMAntony** [comment]
Hey Antony here. I am new to numpy. Will change as many file as possible and raise a PR.

**Comment by vigneshkumarj7** [comment]
DOC: Removed outdated versionadded/changed directives in numpy random, ma, linalg and testing package #27452
