### ISSUE TITLE
random choice should support multidimensional arrays

### ISSUE THREAD

**Issue by alan-isaac** [numpy/numpy#2724]
random.choice enhancement request:

random.choice should support multidimensional arrays by taking an axis number. With this enhancement, axis=None would choose from a flattened array, while an integer argument would chose from the subarrays along that axis.

Apologies if this is a duplicate.  My previous submission seems to have vanished.

**Comment by samuela** [comment]
+1

**Comment by jhollowed** [comment]
+1. Is this still not implemented?

**Comment by jbachh** [comment]
Yes, I also just came across a use case for this. I guess I do a for loop instead.

**Comment by jbachh** [comment]
+1

**Comment by slidenerd** [comment]
Is this implemented?

**Comment by mikesmith1611** [comment]
Is this ever going to be implemented?

**Comment by MonsieurWave** [comment]
+1

**Comment by stephenpardy** [comment]
+1
I also tried implementing this, before realizing that @masasin had already done it.

**Comment by mattip** [comment]
Implemented in the new randomgen API: `np.random.Generator().choice(..., axis=int)`. Closing since we will not be updating the legacy code to support this. If you feel differently, please reopen for discussion.
