### ISSUE TITLE
BUG: No 2.1 docs published

### ISSUE THREAD

**Issue by gaborbernat** [numpy/numpy#27245]
### Describe the issue:

https://numpy.org/doc shows 2.0 as latest.

### Reproduce the code example:

```python
https://numpy.org/doc shows 2.0 as latest.
```

### Python and NumPy Versions:

2.1.0

**Comment by mattip** [comment]
Should be uploaded soon, I am working according to the [release walkthrough](https://numpy.org/devdocs/dev/releasing.html#upload-documents-to-numpy-org-skip-for-prereleases) which is quite thorough.

**Comment by mattip** [comment]
Cloning numpy/doc locally is the slowest part. We should change [this line](https://github.com/numpy/numpy/blob/d60444f2383b9549e02bb61db956b91a5110ead1/doc/Makefile#L112) into a shallow clone.

**Comment by mattip** [comment]
Hmm. I will use this issue to trace a possible glitch as I upload the new documents. The theme made a change in [PR 834](https://github.com/pydata/pydata-sphinx-theme/pull/834) with this as one of the many changes
> Factors out the JavaScript that was embedded in our version switcher, and now uses a combination of global variables and puts the main JS into our index.js script.

Now when I look at the 2.0 generated documentation, I see this in each page:
```
 <script>
        DOCUMENTATION_OPTIONS.theme_version = '0.15.3';
        DOCUMENTATION_OPTIONS.theme_switcher_json_url = 'https://numpy.org/doc/_static/versions.json';
        DOCUMENTATION_OPTIONS.theme_switcher_version_match = '2.0';
        DOCUMENTATION_OPTIONS.show_version_warning_banner = false;
        </script>
```

Note the hard-coded `show_version_warning_banner = false`. I hope this isn't a problem. The previous versions did all this centrally from a global (non-version-specific) script.

**Comment by mattip** [comment]
The documents are live. The version dropdown on 2.0 is red. I opened pydata/pydata-sphinx-theme#1960

**Comment by mattip** [comment]
Closing this as completed, I will open a new issue if needed.
