### ISSUE TITLE
BUG: Unexpected breaking change in `np.reshape` on v2.1.0

### ISSUE THREAD

**Issue by jonathanberthias** [numpy/numpy#27256]
### Describe the issue:

The API for `np.reshape` was modified to accept all the arguments from the Array API in #26292, but there was a side effect which was not reported in the release notes of v2.1.0.

The issue is that the `order` argument could previously be passed by position, but now it is keyword-only.

### Reproduce the code example:

```python
import numpy as np

np.reshape(np.arange(4), (2, 2), "C")
```

### Error message:

```shell
On v2.0.1: nothing, not even a warning

On v2.1.0:
File "/dev/np_reshape.py", line 3, in <module>
    np.reshape(np.arange(4), (2, 2), "C")
TypeError: reshape() takes from 1 to 2 positional arguments but 3 were given
```

### Python and NumPy Versions:

2.1.0
3.12.4 (main, Jun  6 2024, 18:26:44) [GCC 11.4.0]

### Context for the issue:

I don't think it's a bad thing to have to specify the `order` by keyword, but I think in this case the change was not intended as:
- there was no warning in previous version,
- there was nothing in the release notes about this,
- in [the stubs](https://github.com/numpy/numpy/pull/26292/files#diff-db8483d86d7214c860f5426db5b4f219d991f60ea325f49040e6e06d5278bb03R1723-R1729), passing `order` by position is valid, but not at runtime.

**Comment by ngoldbaum** [comment]
I think this was simply missed during the refactor and all that's needed is to move `order` to the left of the `\` in the signature. @mtsokol if you have time, would you mind preparing a patch for this so it can go into 2.1.1?

@jonathanberthias if you're interested, you can set up testing against the NumPy nightly wheels to help us catch these changes before we do releases.

**Comment by mtsokol** [comment]
@ngoldbaum Sure!
