### ISSUE TITLE
BUG: filled MaskedArray becomes object dtype if given a fill_value of None

### ISSUE THREAD

**Issue by bear24rw** [numpy/numpy#27269]
### Describe the issue:

Passing `fill_value=None` results in the `MaskedArray` dtype changing to `object`. Is this behavior intended? I didn't see mention of this in any changelog.

```
>>> np.__version__
'1.25.2'
>>> np.ma.MaskedArray([1,1,1], [True, False, True], dtype='uint64').filled()
array([999999,      1, 999999], dtype=uint64)
```

```
>>> np.__version__
'2.1.0'
>>> np.ma.MaskedArray([1,1,1], [True, False, True], dtype='uint64').filled()
array([np.int64(999999), 1, np.int64(999999)], dtype=object)
```

### Reproduce the code example:

```python
import numpy as np
assert np.ma.MaskedArray([1,1,1], [True, False, True], dtype='uint64').filled().dtype == np.dtype("uint64")
```

### Python and NumPy Versions:

```
2.1.0
3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]
```

### Runtime Environment:

```
[{'numpy_version': '2.1.0',
  'python': '3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 '
            '(clang-1500.3.9.4)]',
  'uname': uname_result(system='Darwin', node='<redacted>', release='23.2.0', version='<redacted>', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]
```

**Comment by ngoldbaum** [comment]
That seems like an unintended regression, although I'm a little surprised it hasn't come up yet.

One thing that might help is running `git bisect` between 1.25.2 and 2.1 to figure out which PR changed the behavior.

**Comment by bear24rw** [comment]
Bisection led to this as the first bad commit: https://github.com/numpy/numpy/commit/7eb4050719b1d86132dfc374ce91a015d32b3145

**Comment by seberg** [comment]
Ufff, yes, that changed it, but the problem is that the `.fill_value` ends up being an `int64` rather than the `uint64` of the masked array.
IIRC, that was a work-around for a _similar_ issue, with small integer values.  The solution may be to use a `uint32` but ideally, I think the fill value should always be aligned to the array immediately (when auto-setting it at least?)

This can happen because the code uses a try/except... It may be nice to find a minimal fix in `.filled()` for backporting...

**Comment by fengluoqiuwu** [comment]
> Ufff, yes, that changed it, but the problem is that the `.fill_value` ends up being an `int64` rather than the `uint64` of the masked array. IIRC, that was a work-around for a _similar_ issue, with small integer values. The solution may be to use a `uint32` but ideally, I think the fill value should always be aligned to the array immediately (when auto-setting it at least?)
> 
> This can happen because the code uses a try/except... It may be nice to find a minimal fix in `.filled()` for backporting...

I think the default value should be reconsidered. The default value of ma current may cause some problems:
 - 1. The default value of all integer is 999999 in python type, it will be treated as np.int64, but in function `copyto`, we treat usigned integer and signed integer as two different type.
 - 2. Both '999999' for integer type and `1.e20` for floating type is too big to the smallest type(`np.int8` and `np.float16`), and if we use `np.float16` it may raise runtime warning of overflow.

I met the similar problem when fixing the [bug27580](https://github.com/numpy/numpy/issues/27580), and I fix it by delete the copyto as there is no need to check infinity in that case, but every `copyto` (or casting more precisely) may cause the same problem. So I  think maybe we should use Numpy datatype, and  every types' default-fill-value should be at least in the same type.(such as integer, unsigned integer...)

**Comment by fengluoqiuwu** [comment]
This approach seems to resolve (or more accurately, suppress) the bug, but we still need to be mindful of the fact that using `np.float16` can trigger a runtime warning: overflow. This happens because `np.float16` has a smaller range compared to other floating-point types, and default-value is larger than its maximum value.

**Comment by seberg** [comment]
> I think the default value should be reconsidered

Yes, that is probably the right thing to do.  I haven't caught up with your many posts (it is great to see the energy and interest!).  It may be that we can jump through the hoop of using something like `np.asarray(fill_value).astype(arr.dtype)`, or maybe just expanding the default fill values to the (in)correctly cast results?

PS: As you noticed while browsing on some other issue.  There are a lot of inconsistencies in masked arrays and even good fixes tend to cause subtle changes downstream.  Maybe with more enthusiasm, something can be done about it, but I think a lot of us feel the better solution may be to write a more consistent version and ask users to eventually switch.
(I think a start for this exists for example in astropy.)

(That could use `__array_function__`/`__array_ufunc__` and avoid some of the odd handling for things like `np.ufunc(masked_array)` vs. `np.ma.ufunc(masked_array)`, etc.)
