### ISSUE TITLE
Impossible to use ACML with system installed ATLAS

### ISSUE THREAD

**Issue by bfroehle** [numpy/numpy#2728]
As far as I can tell it's impossible to configure `site.cfg` to link to ACML (+CBLAS) with a system installed ATLAS, using maintenance/1.6.x.  (I haven't tried with newer versions).

For example, `site.cfg` would have me believe that I should be able to link to ACML with:

```
[blas_opt]
libraries = cblas,acml
library_dirs = /opt/acml5.2.0/gfortran64_fma4/lib

[lapack_opt]
libraries = acml
library_dirs = /opt/acml5.2.0/gfortran64_fma4/lib
```

But running `python setup.py build` instead links to the system installed ATLAS:

```
$ ldd build/lib.linux-x86_64-2.7/numpy/core/_dotblas.so
    linux-vdso.so.1 =>  (0x00007fffbdf80000)
    libptf77blas.so.3 => /usr/lib64/atlas/libptf77blas.so.3 (0x00007f685ed10000)
    libptcblas.so.3 => /usr/lib64/atlas/libptcblas.so.3 (0x00007f685eaf0000)
    libatlas.so.3 => /usr/lib64/atlas/libatlas.so.3 (0x00007f685e490000)
...
```

This is easily seen as well by running `get_info('blas_opt')`:

```
$ cat test.py
import __builtin__ as builtins
builtins.__NUMPY_SETUP__ = True
import numpy.distutils.system_info as si
print si.get_info('blas_opt')

$ python test.py 
Running from numpy source directory.
...
{'libraries': ['ptf77blas', 'ptcblas', 'atlas'], 'library_dirs': ['/usr/lib64/atlas'], 'define_macros': [('ATLAS_INFO', '"\\"3.8.4\\""')], 'language': 'c', 'include_dirs': ['/usr/include']}
```

How can I convince the setup process to not ignore my site.cfg file?

**Comment by rgommers** [comment]
AFAIK the documentation changes to ``site.cfg`` have landed. We still don't have explicit support for ACML, but given that AMD announced the end-of-life of ACML (http://developer.amd.com/tools-and-sdks/archive/compute/amd-core-math-library-acml/) I believe we can close this now. There are enough other issues regarding fixing ``site.cfg`` behavior to "do what I say".

Thanks @bfroehle.
