### ISSUE TITLE
ENH: Hurst exponent

### ISSUE THREAD

**Issue by ncooder** [numpy/numpy#27299]
### Proposed new feature or change:

Add the Hurst exponent calculation feature to numpy, providing a tool for analyzing long-term memory effects in time series data based on:
[Hurst exponent](https://en.m.wikipedia.org/wiki/Hurst_exponent)

**Comment by WarrenWeckesser** [comment]
This is not a good fit for NumPy, so I don't think any other NumPy developers will object that I am closing the issue.

I think this would fit well in the [time series analysis submodule](https://www.statsmodels.org/stable/tsa.html) of [`statsmodels`](https://www.statsmodels.org/).  You could suggest this enhancement at the [`statsmodels` github page](https://github.com/statsmodels/statsmodels).
