### ISSUE TITLE
Numpy Import Error in AWS SAM

### ISSUE THREAD

**Issue by Jdldeveloper** [numpy/numpy#27338]
### Steps to reproduce:

I've created a minimum reproducible example called [sam-numpy-example](https://github.com/Jdldeveloper/sam-numpy-example).

The example above is simple a basic [AWS SAM](https://github.com/aws/aws-sam-cli) setup along with adding numpy inside an AWS lambda layer. Nothing else is done besides scaffold AWS SAM, add numpy and try to run it with `sam local start-api`.

### Error message:

```shell
Invalid lambda response received: Invalid API Gateway Response Keys: {'errorType', 'errorMessage', 'stackTrace', 'requestId'} in {'errorMessage':  
"Unable to import module 'app': Error importing numpy: you should not try to import numpy from\n        its source directory; please exit the numpy
source tree, and relaunch\n        your python interpreter from there.", 'errorType': 'Runtime.ImportModuleError', 'requestId':                    
'387b7f65-d7fe-48b4-8f51-9d074be50daa', 'stackTrace': []}
```

### Additional information:

I thought this was an AWS SAM issue however I opened an issue ([#7429](https://github.com/aws/aws-sam-cli/issues/7429)) in their repo first. The maintainers reviewed it and said from the SAM side of things, everything looks fine. 

They suggested opening an issue here since the error message coming out is directly numpy. Hopefully I can get some insight on what I could do to fix this, ideally I'd like to develop with SAM but this is a major blocker since I also need numpy.

**Comment by mattip** [comment]
This happens if you build the project on a different machine than the one you run on. NumPy is machine-specific, so you must build the lambda docker where you want to run it. You are not seeing the entire traceback, but we have seen this before. I imagine it has somewhere up higher
```
ModuleNotFoundError: No module named 'numpy._core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    ...
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.12 from "/tmp/throwaway/bin/python"
  * The NumPy version is: "2.1.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy._core._multiarray_umath'
```

**Comment by Jdldeveloper** [comment]
Closing this for now, thanks for the info @mattip

It doesn't necessarily solve my issue but [this comment](https://github.com/numpy/numpy/issues/21312#issuecomment-1614880006) did. Seems like it has to be containerized in AWS SAM to work properly (even though I confirmed architecture, python and numpy version)
