### ISSUE TITLE
Emscripten/Pyodide nightly upload failing.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#27339]
Looks like it needs an update:
```
Error:  ('Authentication token has expired', 401)
```

**Comment by agriyakhetarpal** [comment]
ccing @rgommers and @mattip for visibility and for the task of updating the tokens – I'm not aware of what the expiration date for them was, they might know better

**Comment by agriyakhetarpal** [comment]
ccing @rgommers and @mattip for visibility and for the task of updating the tokens – I'm not aware of what the expiration date for them was, they would know better

**Comment by agriyakhetarpal** [comment]
Suggestion: for future iterations, we could add the date when the token expires in a comment above where it is used in the workflow.

**Comment by mattip** [comment]
I am not an admin, someone with access to https://anaconda.org/scientific-python-nightly-wheels/numpy/settings will need to regenerate the tokens.

**Comment by matthewfeickert** [comment]
Please ask @rgommers, @tylerjereddy, or @seberg to generate new tokens and update the relevant GitHub Actions secrets (c.f. https://github.com/scientific-python/upload-nightly-action/issues/90#issuecomment-2336769581). @seberg's token was previously being used.

**Comment by seberg** [comment]
I am travelling and having some difficulties doing things quickly due to poor connectivity.  Should get to it soonish, though.

**Comment by mattip** [comment]
Closing, the tokens were regenerated.
