### ISSUE TITLE
BUG: The usage of "array1[array2] = 1" has bug

### ISSUE THREAD

**Issue by ShangJingLi** [numpy/numpy#27351]
### Describe the issue:

array1[array2] = 1,if the type of array2 is int, the output will be wrong. If the type of array2 is bool, the out put is right. 

### Reproduce the code example:

```python
import numpy as np

c = np.array([-1, 0, -1, -1, 0, 0, 0, -1, -1])
know_defective = c[c == -1]  # 被检出为次品的部分
print(know_defective)
know_defective = np.zeros_like(know_defective)  # 次品数组置0
print(know_defective)
random_values4 = np.random.rand(len(know_defective)) < 1  # 是否丢弃
print(random_values4)
know_defective[random_values4] = 1
print(type[know_defective])
```

### Error message:

```shell
C:\Users\LENOVO\anaconda3\python.exe C:\Users\LENOVO\AppData\Roaming\JetBrains\PyCharmCE2024.1\scratches\scratch.py 
[-1 -1 -1 -1 -1]
[0 0 0 0 0]
[1, 1, 1, 1, 1]
know_defective1: [0 1 0 0 0]
know_defective2: [1 1 1 1 1]  # The code runs normally but the output result is incorrect.
```

### Python and NumPy Versions:

python:3.9.13
numpy:2.0.4

### Runtime Environment:

pip

### Context for the issue:

![Uploading image.png…]()

**Comment by rruuaanng** [comment]
So, which is the result you want?

Here are the results I got when I ran the code using numpy 1.21.5:

```
[-1 -1 -1 -1 -1]
[0 0 0 0 0]
[ True  True  True  True  True]
type[array([1, 1, 1, 1, 1])]
```

**Comment by ShangJingLi** [comment]
I think the one that the type of array is bool is right and I want it

**Comment by ngoldbaum** [comment]
I also don't understand what the buggy behavior is supposed to be. How is the output "wrong"?

It would help if you could edit the example to make that clearer. 

Notably the code you shared in the example doesn't match the output you shared, I get the same output as @rruuaanng on a nightly version of numpy. I don't see what's wrong with it.

**Comment by rossbar** [comment]
There are two forms of [advanced indexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing) - array integer indexing and boolean indexing. Please check the linked docs to check your use case against the examples. In the meantime I will close this - if the issue persist please feel free to reopen with a reproducing example!
