### ISSUE TITLE
CI: Failures in uploading nightly wheels

### ISSUE THREAD

**Issue by lysnikolaou** [numpy/numpy#27367]
The scheduled job that builds nightly wheels and uploads them to the `scientific-python-nightly-wheels` index has been failing for a couple of weeks. The latest run can be viewed [here](https://github.com/numpy/numpy/actions/runs/10756487678). It seems that the wheels are build successfully and it's only the upload step that fails because the authentication token has expired.

```
Run source tools/wheels/upload_wheels.sh
IS_PUSH is false
IS_SCHEDULE_DISPATCH is true
scheduled or dispatched event
/Users/runner/work/numpy/numpy
./wheelhouse/numpy-2.2.0.dev0-cp313-cp313t-macosx_10_13_x86_64.whl
Found wheel
Warning:  Distribution "numpy-2.2.0.dev0-cp313-cp313t-macosx_10_13_x86_64.whl" already exists. Removing.
Error:  ('Authentication token has expired', 401)
Error: Process completed with exit code 1.
```

Contacting the Anaconda folks to renew the token is probably the way to go.

**Comment by andyfaff** [comment]
@seberg @stefanv, you probably have permissions to set the secret, do you also have permissions to generate the anaconda token?
The secret needs to be set in two places. numpy/numpy, but also on cirrus where various aarch64 wheels are made.

**Comment by stefanv** [comment]
xref: https://github.com/scientific-python/upload-nightly-action/issues/90
