### ISSUE TITLE
DOC: NumPy Comic Community Review #4

### ISSUE THREAD

**Issue by MarsBarLee** [numpy/numpy#27375]
### Overview:

<a href="https://drive.google.com/file/d/18-CWOIoBjMrffwMuKsx2YRkY9hkJm-dM/view?usp=drive_link"><img src="https://hackmd.io/_uploads/ryIHONKmp.png" width="400"></a>

Hi everyone! I am inviting the community to review the last 7 pages of the 'NumPy Contributor Comics', which is part of the GSOD-NumPy 2024 project. If this looks familiar, that’s because this work is a continuation of the GSOD 2023 work.
The comic can be viewed here, as a PDF (to upload link).

You can [comment directly on the PDF viewer](https://drive.google.com/file/d/18-CWOIoBjMrffwMuKsx2YRkY9hkJm-dM/view?usp=drive_link) or on this Github issue.

These comics aim to show newcomers that NumPy is driven by people who use it: in this case, scientists! These comics will show grad students finding a usability problem in NumPy, working together to submit an issue, and talking to community members.
This thread will be open for the next two weeks.

**For Review:**

- For review, you can comment on any part, such as re-wording a specific line or panel.
- I recommend jumping to review pages 11-16 and the back cover, since that was completed this year.
- Is there a clear Call to Action for people interested in learning more about contributing to NumPy?
- Is the difference between the role of a maintainer and contributor clear?

**Some major changes since last review:**
- Remove from references of PyData NYC 2023 edition
- This part was added when I gave a talk about the grant at PyData NYC
- Add other characters, such as the contributor and maintainer
- Show the process of reviewing PRs, merging and release cycle
- Add a credit section to name original contributors that made the .npz filetype change

**Comment by eagunn** [comment]
@MarsBarLee When I click the link above, I'm shown an Access Denied message and must to request access. 
That's not unreasonable behavior but, if intentional, the two-step access should probably be mentioned above.

**Comment by MarsBarLee** [comment]
@eagunn Hi Anne, thanks for pointing that out, that was something I missed out on set-up. It is fixed now.

**Comment by Joao-antonio-gg** [comment]
Hello! I'm from Brazil, and I really enjoy your comic. I'd love to help translate it into Portuguese. Would it be possible for me to translate your work and send it to you or help share it with others?

**Comment by MarsBarLee** [comment]
@Joao-antonio-gg Yes! I welcome translations of the comic! I really appreciate that people want to share the comic through translation!

I haven't fully figured out the translatoin process but I can create a tracking issue for translation and ping you on there.

**My understanding of the translation process:**
- Translate the [English script](https://docs.google.com/document/d/1bXwHd8F-0zFMeCu9ohASynmyOY03cmZHNTOD2Sp2oC0/edit?usp=sharing) into Portuguese (note: this is not the final script but close to final)
- Review the translation
- Update the text in a graphics editor (such as GIMP, Inkscape or Krita)
- Review the typesetting (does the translated text fit in the speech bubbles?)
- Release translated comic

**Items**
- Comic script in English
- Comic pages with blank speech bubbles
- Comic script in Portuguese
- Comic pages with Portugeuse

**Some considerations:**
- Will there be enough space in the speech bubbles to fit the translated text?
  - The speech bubbles were sized in English but might be too small or big for Portuguese text
  - This is a common problem in Japanese to English manga translation where English text may take up 20% more space than Japanese and thus not fit the speech bubbles. But perhaps not a problem here since both English and Portuguese use the Roman alphabet
- The current font, Anime Ace, has letters for English but I'm not sure if it has all the letters for Portuguese. We may need to select a new font that has all the letter for Portuguese

**Comment by Joao-antonio-gg** [comment]
Hi! I really like the idea of creating an issue to track the translation, and you can count on me to follow all the guidelines for the process.

As for the font, the one you mentioned, Anime Ace, has almost all the letters needed for Portuguese, except for the cedilla (ç). If necessary, we can discuss finding a new font that better suits the language, ensuring all the letters and accents are properly covered.

**Comment by MarsBarLee** [comment]
The review period has ended, thank you everyone that has given their thoughts and feedback!
