### ISSUE TITLE
CI: Latest Cython is causing problems

### ISSUE THREAD

**Issue by charris** [numpy/numpy#27378]
I think we are seeing https://github.com/cython/cython/issues/6387 in #27376. This is just to note it.

**Comment by ngoldbaum** [comment]
@charris I think this should be fixed now? Let me know if you're still seeing issues for free-threaded CI.

**Comment by ngoldbaum** [comment]
Err, once cython nightlies get updated anyway. I just confirmed numpy builds using the cython master branch.

**Comment by charris** [comment]
Nightlies are at https://anaconda.org/scientific-python-nightly-wheels/Cython/files.

**Comment by ngoldbaum** [comment]
There's a new nightly up and the compilation error is fixed so I'm closing this.
