### ISSUE TITLE
BUG: NumPy 2.0 type promotion semantics are inconsistent for builtin vs. custom dtypes

### ISSUE THREAD

**Issue by jakevdp** [numpy/numpy#27389]
### Describe the issue:

We noticed that array + scalar promotion differs between numpy 1.X and 2.X in an unexpected way. For example:
```python
>>> import numpy as np
>>> import ml_dtypes
>>> np.__version__
'1.26.4'
>>> ml_dtypes.__version__
'0.4.0'
>>> np.arange(4, dtype=np.float16) + 1
array([1, 2, 3, 4], dtype=float16)
>>> np.arange(4, dtype=ml_dtypes.bfloat16) + 1
array([1, 2, 3, 4], dtype=bfloat16)
```
Notice that in both cases here, the output dtype matches the input dtype. However in NumPy 2.0 we see this:
```python
>>> import numpy as np
>>> import ml_dtypes
>>> np.__version__
'2.0.0'
ml_dtypes.__version__
'0.4.0'
>>> np.arange(4, dtype=np.float16) + 1
array([1, 2, 3, 4], dtype=float16)
>>> np.arange(4, dtype=ml_dtypes.bfloat16) + 1
array([1, 2, 3, 4], dtype=float32)
```
For built-in dtypes (`float16`) the result is the same as in NumPy 1.X. But for custom dtypes (`ml_dtypes.bfloat16`) it ends up promoting to `float32`.

I know that the treatment of scalar promotion changed in NumPy 2.0, but I'm not familiar enough with the details to know why it would cause a difference for builtin vs. user-defined types, or whether this behavior is intended in the new promotion semantics.

xref https://github.com/jax-ml/ml_dtypes/issues/189

**Comment by seberg** [comment]
The only fix is to use new DTypes, and that is also the only possible fix, unfortunately.  I think the + 1 examples should try to use int8 or uint8, apparently that promotes for you already?

**Comment by jakevdp** [comment]
Sorry I'm not sure I understand the answer

> The only fix is to use new DTypes

Can you say more about "new DTypes" and what they entail?

> I think the + 1 examples should try to use int8 or uint8

I'm not sure what you're suggesting: the issue is that user code frequently adds built-in Python scalars to scalar-typed values, and the result is unexpected. We can't change that user code.

**Comment by seberg** [comment]
I what I mean is that `bfloat16 + 1` should behave the same as `bfloat16 + int8`, I thought (as a fallback).  If it does not, then maybe that can be fixed/changed.

> Can you say more about "new DTypes" and what they entail?

Sorry travelling, that is the NumPy 2 API only.  Which creates a DType class with fully new API and a bit different behavior (only relevant may be no metadata currently):
* https://numpy.org/doc/stable/reference/c-api/array.html#c.PyArrayInitDTypeMeta_FromSpec
* https://numpy.org/doc/stable/reference/c-api/types-and-structures.html#c.PyArrayDTypeMeta_Spec
* https://numpy.org/doc/stable/reference/c-api/array.html#c.NPY_DT_common_dtype

last one allows customization here.  Not sure if we can expose a mechanism for old-style dtypes...

**Comment by hawkinsp** [comment]
I can certainly try porting our dtypes to the NumPy 2 API when running on NumPy 2. I had assumed it was something we could not do for several years (given we need to maintain compatibility with NumPy 1 for quite some time per SPEC 0),  but looking at the examples it doesn't look as invasive as I had feared.

It's still far from clear to me how scalar vs user-dtype promotion is handled, though, even in the new API, but maybe that will become obvious when I try.

**Comment by seberg** [comment]
The problem should not be the difficulty itself (but of course it is not a one day job), but rather that the new code cannot work with older versions, so either there are two versions, or a runtime decision which version to use (which adds a layer of complexity):
```
if numpy1:
    import mltypes.numpy1
else:
    import mltypes.numpy2
```
kind of thing (and require compiling with NumPy 2+).  And of course possible subtle differences, although I think that may really be mostly the metadata.
But, yeah, unlike old dtypes, you have more power, but also need to do more of the leg-work to define e.g. all promotions.
