### ISSUE TITLE
TYP: `Generator.integers` wrong dtype when using the `endpoint` parameter

### ISSUE THREAD

**Issue by tguichaoua** [numpy/numpy#27388]
### Describe the issue:

The doc of `random.Generator.integers` says that the default dtype is `int64`.
But when using the `endpoint` parameter without specifyng the `dtype` parameter, the static type of the returned value is `bool` or `NDArray[bool]` instead of `int64` or `NDArray[int64]`. 

### Reproduce the code example:

```python
import numpy as np

rng = np.random.Generator(np.random.PCG64())
rolls = rng.integers(1, 6, endpoint=True, size=(10, 6)) # static type: NDArray[bool]

print(rolls.dtype)  # runtime type: int64
```

### Python and NumPy Versions:

2.1.1
3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

### Type-checker version and settings:

The python extension for VSCode, default settings.

**Comment by jorenham** [comment]
Apparantly it has to do with the explicitly specified `endpoint` kwarg. So as a workaround,
you could use `rng.integers(1, 6 + 1, size=(10, 6))` for the time being.
