### ISSUE TITLE
DOC: `numpy.var()`, `mean` parameter has wrong version attributed to it 

### ISSUE THREAD

**Issue by eliasfrimanns** [numpy/numpy#27399]
### Issue with current documentation:

In the API reference for versions 2.0.0+, the parameter `mean` of the `numpy.var()` function is labeled to be new in 1.26.0. However, in the documentation for 1.26.0 this parameter is not mentioned, and it was not implemented in 1.26.4 (as far as I've seen). 

[https://numpy.org/doc/stable/reference/generated/numpy.var.html](url) 

### Idea or request for content:

Change the version which it was added from 1.26.0 to 2.0.0.

**Comment by joehiggi1758** [comment]
@eliasfrimanns I'll give this a shot, and circle back shortly!

**Comment by Ishankoradia** [comment]
@joehiggi1758 i have created a PR please check and let me know if i missed anything.

**Comment by Ishankoradia** [comment]
@joehiggi1758 haha, sorry for hijacking your PR. 
I did `spin docs` and there were no errors.
