### ISSUE TITLE
BUG: 2D fft doesn't reconstruct function at Nyquist rate

### ISSUE THREAD

**Issue by unalmis** [numpy/numpy#27413]
### Describe the issue:

I have a unit test [here](https://github.com/PlasmaControl/DESC/pull/1119/files#r1731613591) for a 2D FFT that only passes above the Nyquist rate, when it should pass at the Nyquist rate.

The interpolation code is [here](https://github.com/PlasmaControl/DESC/pull/1119/files#r1763922238). I'm certain there are no implementation issues. Could someone please review this?

I am creating the issue here rather than with JAX and scipy because the issue is common to all three and I think those libraries just use numpy's implementation.

### Reproduce the code example:

```python
See link above.
```

### Error message:

```shell
See link above.
```

### Python and NumPy Versions:

```
1.26.4
3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
```

### Runtime Environment:

```
[{'numpy_version': '1.26.4',
  'python': '3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) '
            '[GCC 12.3.0]',
  'uname': uname_result(system='Linux', node='fedora', release='6.10.9-200.fc40.x86_64', version='#1 SMP PREEMPT_DYNAMIC Sun Sep  8 17:23:55 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'architecture': 'Haswell',
  'filepath': '/home/kaya/miniconda3/envs/desc-env/lib/libopenblasp-r0.3.27.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]
```

### Context for the issue:

Would like to understand whether there is a bug in the calculation of the Nyquist frequency component of 2D FFT.

**Comment by seberg** [comment]
TBH, I think your statement "when it should pass at the Nyquist rate" is just not correct, although I guess it may be for certain inputs.
FWIW, while NumPy and SciPy share at least a common implementation of the FFT (but not all), JAX doesn't.
If you still think there is something wrong here, please provide a more minimal example input, the FFT result and the inverse FFT result.

Until then closing the issue, we can always reopen it.

**Comment by unalmis** [comment]
> I think your statement "when it should pass at the Nyquist rate" is just not correct,
This is a statement of the sampling theorem. Could you let me know why you believe this theorem does not apply? Note the function in my example is band-limited.

**Comment by seberg** [comment]
I am sorry, but I don't want to dig up my DFT theorem knowledge know.  Could you provide a minimal working reproducer with the examples?
I am assuming you have a simple array you are taking the DFT of, and then calculating the inverse.  So all 3 of those can e.g. be shared here (maybe even with plots).

**Comment by unalmis** [comment]
> I am sorry, but I don't want to dig up my DFT theorem knowledge know. 
Ok that is fine. Note that I was politely challenging your claim. If I'm wrong it'd be educational to me.
 
> I am assuming you have a simple array you are taking the DFT of, 
Yes that's correct.

I'll make it more minimal and then share. The DFT is done with numpy. This yields the fourier coefficients of my function. I am using those fourier coefficients to evaluate the function at any point I want. This involves a matrix product shared in the code above. There is no numpy function for this as numpy only provides uniform inverse transforms.

**Comment by seberg** [comment]
If you are *at* the nyquist frequency, you clearly can't sample/reconstruct a sine wave reliably: you might even sample it always at 0 (or just two values).  And with two values that don't happen to be the maximu, I don't think you can get far (not without additional phase and/or offset info).

**Comment by unalmis** [comment]
Thanks, yes then at the nyquist rate (double the nyquist frequency), the phase matters, above it, it does not. Other bug fixes in downstream libraries fixed the numerical issues I was seeing in practice when this issue was made.
