### ISSUE TITLE
BUG: np.dtype(user_dtype_typeobj) doesn't correctly return the associated user dtype object

### ISSUE THREAD

**Issue by hawkinsp** [numpy/numpy#27415]
### Describe the issue:

Here's a repro with the mpfdtype from https://github.com/numpy/numpy-user-dtypes/tree/cf6cf91571982cccb8098f8004962d0c2835bf56/mpfdtype
installed with `pip install .` in that directory of that repo.

```
In [1]: import mpfdtype, numpy as np

In [2]: np.dtype(mpfdtype.MPFloat)
Out[2]: dtype('O')
```

But that's not the correct answer, because `mpfdtype.MPFDtype` is a thing and registered with NumPy, with its `.typeobj` pointing to `mpfdtype.MPFloat`: https://github.com/numpy/numpy-user-dtypes/blob/cf6cf91571982cccb8098f8004962d0c2835bf56/mpfdtype/mpfdtype/src/dtype.c#L241

So the only reasonable answer would be the dtype object already known to numpy.

As best I can tell, `PyArray_DescrFromTypeObject` doesn't have any logic to look at the type objects of registered user dtypes:
https://github.com/numpy/numpy/blob/da79a56e6aa8aeafcdd218fd2e4c534e84ae62bb/numpy/_core/src/multiarray/scalarapi.c#L292

and it falls back to walking up the `__mro__` of the user dtype.

```
In [3]: mpfdtype.MPFloat.__mro__
Out[3]: (MPFDType.MPFDType, object)
```

which is how we end up with `dtype('O')`.

There is logic to resolve user dtypes in there, but it only works for legacy dtypes, as best I can tell.

### Reproduce the code example:

```python
See above.
```

### Error message:

```shell
See above.
```

### Python and NumPy Versions:

2.1.1
3.10.6 (main, Aug  8 2022, 19:33:05) [GCC 11.3.0]

### Runtime Environment:

n/a

### Context for the issue:

Trying to port `ml_dtypes` from the legacy user dtype API to the newer NumPy 2 API.

**Comment by ngoldbaum** [comment]
> Trying to port ml_dtypes from the legacy user dtype API to the newer NumPy 2 API.

Neat!

I think `np.dtype(scalar_type)` should probably return the user dtype if the scalar and dtype are registered properly. I think updating `PyArray_DescrFromTypeObject` to work with new user dtypes makes sense.

@seberg do you want to weigh in?

**Comment by seberg** [comment]
Yes, agreed, we should just make this work.
