### ISSUE TITLE
BUG: Overflow values are different scenarios while down casting the numpy array

### ISSUE THREAD

**Issue by DarshanSP19** [numpy/numpy#27462]
### Describe the issue:

While stacking multiple `numpy` arrays into one using `np.stack()` and casting to another `dtype` it's giving different result then directly casting an individual array.

### Reproduce the code example:

```python
import numpy as np

data = {
    'B0': np.array(
        [-100000, -10000, -1000, -100, -10, 10, 100, 1000, 100000]
    ),
    'B1': np.array(
        [-10000, -1000, -100, -10, 10, 100, 1000, 10000, 100000]
    ),
}

r1 = np.stack([data['B0'], data['B1'] / 10]).astype(np.int16)

r2 = data['B0'].astype(np.int16)

# I'm expecting r1[0] and r2 having the same values
```

### Python and NumPy Versions:

2.0.1
3.11.8 (stable, redacted, redacted)

### Context for the issue:

I want to stack multiple numpy arrays into one and downcast them to reduce memory consumption but before that I just want to check that which arrays overflows after down casting So that I can scale them accordingly. Like I'm doing in the provided example `data['B1'] / 10`. But somehow this down scaling is affecting my other array `data['B0']`.

**Comment by mattip** [comment]
On my machine `np.all(r1[0] == r2)` is `True`. What machine are you using (you neglected to supply the runtime environment information, which makes helping you harder). What values are you getting for `r1` and `r2`? Note that `-100000` cannot be represented as `int16`, it overflows to `31072`. Likewise, `100000` overflows to `-31072`.

**Comment by DarshanSP19** [comment]
Runtime Info
```
[{'numpy_version': '2.0.1',
  'python': '3.11.8 (stable, redacted, redacted) [Clang google3-trunk '
            '(36adf8ecedb64047021265a1e1730773d3b3a9e8)]',
  'uname': uname_result(system='Linux', node='fac586e51a60fabf-286f0f7d0e2.borgtask.google.com', release='5.10.0-smp-1103.32.0.0', version='#1 [v5.10.0-1103.32.0.0] SMP @1721941885', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': [],
                      'not_found': []}}]
```

In my machine values are
```
r1[0] is array([-32768, -10000,  -1000,   -100,    -10,     10,    100,   1000, 32767], dtype=int16)

r2 is array([ 31072, -10000,  -1000,   -100,    -10,     10,    100,   1000, -31072], dtype=int16)
```

**Comment by mattip** [comment]
On my machine, which is Ubuntu 22.04 linux x86_64, downloading the numpy 2.0.1 wheel from PyPI, I get
```
>>> r1[0] == r2
array([ True,  True,  True,  True,  True,  True,  True,  True,  True])
>>> np.all(r1[0] == r2)
np.True_
>>> r1[0]
array([ 31072, -10000,  -1000,   -100,    -10,     10,    100,   1000,
       -31072], dtype=int16)
>>> r2
array([ 31072, -10000,  -1000,   -100,    -10,     10,    100,   1000,
       -31072], dtype=int16)
```

Are you on x86_64? Is your company building numpy/python or using our wheel/python from some distribution? If they are building, what compiler are they using?

**Comment by DarshanSP19** [comment]
Closing as `numpy` on my end is built on a different compiler. So it's intended behavior.

**Comment by seberg** [comment]
Casting floats (`r1`) to integers has undefined behavior in practice when values are out-of-bounds.  In some cases the "correct" integer overflow result is effectively guaranteed because compilers will cast as `float -> int64 -> int8` (which defines it or at least gets it right usually).  This indeed depends on compilers/platform.
