### ISSUE TITLE
BUG: numpy.matrix is not supporting dot product

### ISSUE THREAD

**Issue by JayMan91** [numpy/numpy#27477]
### Describe the issue:

I want to multiply each column of a matrix with a different number. I can do that with using `*` operator when the matrix is an `numpy.ndarray` object. But it is not supported if the matrix `numpy.matrix` object. To an end-user this is strange,
as `numpy.matrix`  objects are a subclass of `numpy.ndarray`  and are supposed to inherit all the attributes and methods of `numpy.ndarray` .

### Reproduce the code example:

```python
import numpy as np

V = np.arange(-3,3).reshape(2,3)
s =  np.array([0., 1, -1])
# I want to multiply 3 columns of V with 0, 1 and -1 respectively
op =  V*s
# This works
# Now let's transform V into a matrix
V = np.asmatrix(V)
op =  V*s
# This throws an error
```

### Error message:

```shell
Traceback (most recent call last):
  File "/tmp/ipykernel_14275/2296465942.py", line 3, in <module>
    V * S
  File "/home/jayanta/Documents/Projects/SolverFreeDFL/pkg/env_dfl/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py", line 219, in __mul__
    return N.dot(self, asmatrix(other))
ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)
```

### Python and NumPy Versions:

numpy version: 1.26.2
sys version: 3.10.12

### Context for the issue:

`np.linalg.svd` returns `U, S, Vh` as `numpy.matrix` . Operations on `U, S, Vh`  without converting them into  `numpy.ndarray` is raising errors, which is frustrating.

**Comment by mattip** [comment]
The whole point of `np.matrix` is that it now longer follows regular NumPy broadcasting rules and "lives" in a 2d-only universe. So if you want to multiply with a `np.matrix` you need to make sure the operands are all 2d.  Is there a special reason you are using this deprecated subclass?

**Comment by WarrenWeckesser** [comment]
FYI: As a work-around, you can write `op = np.multiply(V, s)`.  `np.multiply` is element-wise multiplication for both `np.ndarray` and `np.matrix`.

But as @mattip pointed out, the use of `np.matrix` is no longer recommended; see the note in the docstring of [`np.matrix`](https://numpy.org/doc/2.1/reference/generated/numpy.matrix.html).
