### ISSUE TITLE
ENH: Add a Function to Calculate Sum of Squares of an Array

### ISSUE THREAD

**Issue by RoyiAvital** [numpy/numpy#27476]
### Proposed new feature or change:

The need to calculate for a given vector its _sum of squares_ is common in _Scientific Programming_.

If the vector is materialized an easy option is using the `np.inner()` option with itself.
It is as quick as it gets with, probably, no memory allocation.

Yet if there is a vector to materialize within an expression there are only 2 options:
1. Use `np.linalg.norm()` and square the answer.
2. Use `np.sum(np.square())` which creates an intermediate allocation.

It would be great to have `np.sum_squares()` and `np.fsum_squares()` to sum the square of each element (Where `fsum_squares()` is specialized for the non complex case).
The requirement is to be fast with no allocation.  
For instance, have this use case optimized (Ridge Regression $f \\left( \\boldsymbol{x}, \\lambda \\right) = \\frac{1}{2} {\\left\\| \\boldsymbol{A} \\boldsymbol{x} - \\boldsymbol{b} \\right\\|}_{2}^{2} + \\frac{\\lambda}{2} \\left\\| \\boldsymbol{x} \\right\\|\_{2}^{2}$):

```python
hObjFun = lambda vX, λ: 0.5 * np.fsum_squares(mA @ vX - vB) + (λ / 2.0) * np.fsum_squares(vX)
```

Alternatives:
 - Add an option in `np.linalg.norm()` to skip the last calculation in `sum(abs(x)**ord)**(1./ord)`. Namely not applying the `1./ord` operation. This is a generalization of the above for $\\left\\| \\boldsymbol{x} \\right\\|_{p}^{p}$.
 - Add support for a single input case for `np.inner()` which will apply the operation of the array with itself.

At any case it seems they could share most of the code.

**Comment by DWesl** [comment]
Your suggestion is to create a helper function
```python
def sum_squares(x):
    return np.inner(x, x)
```
in NumPy, rather than your own code?

(or
```python
def sum_square(x):
    result = la.norm(x)
    result **= 2
    return result
```
for your alternative suggestion, each with about a 20-line docstring if done properly)

What advantage does including this function in NumPy have over adding it as an example in the documentation somewhere?

Alternately, if you prefer every program be a one-liner, the following should work:
```python
optimize(lambda vX, weight: 0.5 * (lambda x: np.inner(x, x))(mA @ vX - vB) + 0.5 * weight * (lambda x: np.inner(x, x))(vX), ...)
```

**Comment by RoyiAvital** [comment]
@DWesl , appreciate the ideas.    
Yet the concept was efficiency, hence the call overhead was to be minimized.

Also the case of having an option not to apply the `1./ord` could assist for many cases which are trickier.  
Applying the fractional power and then applying the power to reverse it must hurt accuracy as well.

The use of ${\\left\\| \\boldsymbol{x} \\right\\|}_{p}^{p}$ is very common, why not support it?

**Comment by DWesl** [comment]
Given the relevant lines of `numpy.linalg.norm`:
https://github.com/numpy/numpy/blob/cd4d6ba5d1aee621abb9d7d52ecb48cb7bc43c98/numpy/linalg/_linalg.py#L2743-L2744
https://github.com/numpy/numpy/blob/cd4d6ba5d1aee621abb9d7d52ecb48cb7bc43c98/numpy/linalg/_linalg.py#L2786-L2790
your helper function will not be slower than the original, especially if you enforce the use of a static type checker to avoid the runtime checks NumPy has earlier in that function (the first helper function is basically line 2743, without the argument regularization and case selection logic earlier in the function).

There was a big fuss some years back about Python adding an assignment operator:
```python
def hObjFun(vX, weight):
    return 0.5 * ((residuals := mA @ vX - vB).dot(residuals) + weight * vX.dot(vX))
```
which solves the "array doesn't have a name I can use in two places" problem in a way that doesn't produce a second line in the function, though you would still have to come up with a name for the expression, so if that's the bottleneck you're facing, this doesn't help.

Alternately:
```python
def norm_ne(vector, p=2):
    return numexpr.evaluate(f"sum(abs(vector) ** {p:d})", {"vector": vector})

@numba.njit
def norm_nm(vector, p=2):
    return np.sum(np.abs(vector) ** p)
```
should reduce function call overhead (especially on repeated calls), or you could write Cython, Pythran, Fortran/f2py, or C++/pybind11 versions where any functions called are C/Fortran not Python and therefore have smaller overhead.  (Depending on the requirements of `numexpr.re_evaluate`, you might be able to speed things further in whichever loop).

**Comment by HaoZeke** [comment]
Closing for now, it doesn't seem likely that such a function will make it into the NumPy API. A post to the mailing list would be a better starting point IMO.
