### ISSUE TITLE
BUG: numpy.zeros misses out on hugepages

### ISSUE THREAD

**Issue by crusaderky** [numpy/numpy#27483]
### Describe the issue:

Calling `numpy.zeros` to create a very large buffer is slightly faster than `numpy.ones` and `numpy.full`.
However, _writing_ anything to such an array is more than 5x slower upon first access to the memory.

On my AMD desktop, it shows that writing to a 3GiB buffer takes:
- 350~380 ms, if the buffer is cold (memory has just been acquired from the OS)
- 250~280 ms, if the buffer is warm (if setitem, np.zeros, np.full, bzero, or memset just wrote to it)
- 1.3s, if the buffer was just created with numpy.zeros
 
The following reproducer uses `ndarray.__setitem__` to repeat a scalar into the buffer, but I've obtained comparable measures by calling `memcpy` in C to copy over segments of memory of substantial size, as well as with Cython loops.

Omitted: I've also tried calling numpy.empty followed by bzero or memset glibc calls. They perform identically to numpy.ones and numpy.full.

### Reproduce the code example:

```python
import numpy as np
n = 400_000_000  # ~3 GiB

print("empty")
%time empty = np.empty(n, dtype=np.int_)
%time empty[()] = 123
%time empty[()] = 456

print("\nzeros")
%time zeros = np.zeros(n, dtype=np.int_)
%time zeros[()] = 123
%time zeros[()] = 456

print("\nones")
%time ones = np.ones(n, dtype=np.int_)
%time ones[()] = 123
%time ones[()] = 456

print("\nfull")
%time full = np.full(n, fill_value=789, dtype=np.int_)
%time full[()] = 123
%time full[()] = 456
```

### Error message:

```shell
empty
CPU times: user 167 μs, sys: 24.2 ms, total: 24.3 ms
Wall time: 24.1 ms
CPU times: user 55.2 ms, sys: 328 ms, total: 383 ms
Wall time: 381 ms
CPU times: user 255 ms, sys: 795 μs, total: 255 ms
Wall time: 254 ms

zeros
CPU times: user 1.13 ms, sys: 244 ms, total: 245 ms
Wall time: 245 ms
CPU times: user 145 ms, sys: 1.17 s, total: 1.32 s
Wall time: 1.32 s
CPU times: user 266 ms, sys: 168 μs, total: 267 ms
Wall time: 265 ms

ones
CPU times: user 52.1 ms, sys: 324 ms, total: 376 ms
Wall time: 375 ms
CPU times: user 257 ms, sys: 263 μs, total: 257 ms
Wall time: 256 ms
CPU times: user 259 ms, sys: 1.24 ms, total: 261 ms
Wall time: 259 ms

full
CPU times: user 41.3 ms, sys: 334 ms, total: 376 ms
Wall time: 375 ms
CPU times: user 256 ms, sys: 0 ns, total: 256 ms
Wall time: 255 ms
CPU times: user 256 ms, sys: 352 μs, total: 256 ms
Wall time: 255 ms
```

### Python and NumPy Versions:

2.1.1
3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:36:51) [GCC 12.4.0]

### Runtime Environment:
```
[{'numpy_version': '2.1.1',
  'python': '3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:36:51) '
            '[GCC 12.4.0]',
  'uname': uname_result(system='Linux', node='melody', release='6.8.0-45-generic', version='#45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'architecture': 'Zen',
  'filepath': '/home/crusaderky/miniforge3/envs/h5/lib/libopenblasp-r0.3.27.so',
  'internal_api': 'openblas',
  'num_threads': 32,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]
```

**Comment by seberg** [comment]
NumPy does nothing special at all here.  It simply `malloc`'s or `calloc`'s some memory (and hints at using huge pages).  Then fills it for `full/ones`.
The cost for zeros/empty happens at access when the page-fault happens.

Why the `zeros` is so super slow for you is not clear to me, besides that it needs to zero the full 2 MiB (presumably) page, the kernel is taking a ridiculous amount of time here for some reason (swapping? defragmenting? I honestly don't know, ...).

I would not be surprised that if you try it again or reorder the operations the situation may look very different.

The performance of malloc and page-faults is in general complex, although I don't think that should matter as much for such huge allocations.

**Comment by crusaderky** [comment]
> The cost for zeros/empty happens at access when the page-fault happens.

Thank you, this makes a lot of sense and fully explains the delta between cold (350ms) and warm buffer (250ms).

> swapping? defragmenting?

Very unlikely, as I have tons of free memory. 

Also worth pointing out that in my reproducer arrays never fall out of scope, e.g. every time you create a new one you are guaranteed to need to go to the OS to get more memory.

> I would not be surprised that if you try it again or reorder the operations the situation may look very different.

I tried that many times, in many configurations and circumstances. What you see is a distilled reproducer that I crafted after consistently observing this behaviour in much more sophisticated situations (reading with hdf5, to be precise).

> hints at using huge pages

This I suspect is a big lead. If empty/ones/full for some reason successfully access hugepages but zeros doesn't, I think it could explain the behaviour?

Do I understand correctly that ones and full trivially call empty and then fill the buffer with a basic for loop, whereas zeros uses a completely different syscall?

**Comment by crusaderky** [comment]
I reproduced this in C. Besides a very first process warmup cost, where the OS takes significantly longer to respond, the performance of writing to np.zeros is equivalent of that of writing to a buffer allocated with malloc, with or without hugepages hint. Writing to numpy.empty is much, much faster - so it seems that there's an extra trick going on there.

```C
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION

#include <assert.h>
#include <time.h>
#include <sys/mman.h>

#include <Python.h>
#include <numpy/arrayobject.h>

#define N 400000000  // ~3 GiB
#define NBYTES N*sizeof(long)

void* pyinit() {
    Py_Initialize();
    import_array();
    return NULL;
}

void bench(const char* label, long* buf) {
    assert(buf != NULL);
    clock_t t0, t1;
    int i;
    t0 = clock();
    for (i=0; i<N; i++) {
        buf[i] = 123;
    }
    t1 = clock();
    printf("%s: %fs\n", label, (double)(t1 - t0) / CLOCKS_PER_SEC);
}

int main(int argc, char** argv) {

    pyinit();
    long* buf;
    int i;
    PyObject* py_array;

    for (i=0; i<3; i++) {
        buf = malloc(NBYTES);
        bench("malloc", buf);
        free(buf);

        buf = malloc(NBYTES);
        madvise(buf, NBYTES, MADV_HUGEPAGE);
        bench("malloc+hugepages", buf);
        free(buf);

        npy_intp dims[1] = {N, };
        py_array = PyArray_SimpleNew(1, dims, NPY_LONG);
        assert(py_array != NULL);
        buf = (long*)PyArray_DATA((PyArrayObject*)py_array);
        bench("np.empty", buf);
        Py_DECREF(py_array);

        py_array = PyArray_ZEROS(1, dims, NPY_LONG, 0);
        assert(py_array != NULL);
        buf = (long*)PyArray_DATA((PyArrayObject*)py_array);
        bench("np.zeros", buf);
        Py_DECREF(py_array);
    }
    return 0;
}
```
Ouput:
```
malloc: 1.967548s
malloc+hugepages: 1.330530s
np.empty: 0.368722s
np.zeros: 1.336754s
malloc: 1.336366s
malloc+hugepages: 1.333154s
np.empty: 0.367398s
np.zeros: 1.339392s
malloc: 1.342403s
malloc+hugepages: 1.345901s
np.empty: 0.371611s
np.zeros: 1.345479s
```

**Comment by seberg** [comment]
Some notes:
* hugepages madvise may not do anything.  It is often set to always anyway, e.g. for me it is: `cat /sys/kernel/mm/transparent_hugepage/enabled` set to "always" anyway.
* `zeros` uses `calloc` which should be the only distinction (but we can double check hugepages if you think that's different).
* You could try using a different malloc (e.g. `mimalloc`) or playing around with some other `malloc` env variables to see what happens (I am not sure how likely that is to affect anything for huge allocations).
* `perf stat` may give you some additional info where time is spend (I suspect you have to enable some additional counters), e.g. how many page-faults there are.
* Far fetched or not?  Maybe it makes sense to pin `taskset --cpu-list 1` to see if it makes a difference?  Also, not sure if locality might break the argument that you have a huge amount of memory.

**Comment by seberg** [comment]
I noticed the title change:  You seem to be right and zeros doesn't hint hugepages that is a weird oversight many years ago, I think!

You managed to confuse me by using `arr[()]` rather than `arr[...]` :).  You are filling the whole array!  So hugepages should speed up things quite significantly (although I don't know how much to expect, this seems a bit much but who knows what other shenanigans are going on.).

@crusaderky do you happen to feel like refactoring out the hinting in `alloc.c` and making sure we run it also for the `calloc`/`NEW_ZERO` path?

**Comment by crusaderky** [comment]
@seberg I think I can do it, but it's unlikely I'll have the capacity for it before late November
