### ISSUE TITLE
BUG: Turning off Intel's 80-bit extended precision causes numpy to not recognize long double type

### ISSUE THREAD

**Issue by ernesto-ren** [numpy/numpy#27489]
### Describe the issue:

Turning off Intel's 80-bit extended precision _before_ importing numpy causes the following warning to appear:

```
/home/me/fptest/venv/lib/python3.12/site-packages/numpy/_core/getlimits.py:548: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
```

To repro we need to build a small C shared library:

```C
// fptest.c
// gcc -Wall -Werror -fpic -shared -o libfptest.so fptest.c

#include <fpu_control.h>

void disable_ext_prec(void) {
  fpu_control_t cw = (_FPU_DEFAULT & ~_FPU_EXTENDED) | _FPU_DOUBLE;
  _FPU_SETCW(cw);
}
```

Drop the .so in the same directory as the python script below and run the script. You should see the warning appear when running on an Intel CPU.

The root cause of the warning seems to be that the binary signature of a long double result when running on Intel with extended precision _disabled_ is not specified in `getlimits.py:_register_known_types`. I think it should be.

### Reproduce the code example:

```python
# python3 fptest.py   - run as normal
# python3 fptest.py 1 - run with extended precision disabled

import sys

def disable_ext_prec():
    import ctypes
    libfptest = ctypes.cdll.LoadLibrary("./libfptest.so")
    libfptest.disable_ext_prec()

if len(sys.argv) > 1 and bool(int(sys.argv[1])):
    disable_ext_prec()

import numpy

print(numpy.finfo(numpy.longdouble))

ftype = numpy.longdouble
key = (ftype(-1.0) / ftype(10.))
key = key.view(key.dtype.newbyteorder("<")).tobytes()
print(key)
```

### Error message:

```shell
/home/me/fptest/venv/lib/python3.12/site-packages/numpy/_core/getlimits.py:548: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
```

### Python and NumPy Versions:

```
2.1.1
3.12.7 (main, Oct  1 2024, 08:52:11) [GCC 9.4.0]
```

### Runtime Environment:

```
[{'numpy_version': '2.1.1',
  'python': '3.12.7 (main, Oct  1 2024, 08:52:11) [GCC 9.4.0]',
  'uname': uname_result(system='Linux', node='ubuntu', release='5.15.0-102-generic', version='#112~20.04.1-Ubuntu SMP Thu Mar 14 14:28:24 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C'],
                      'not_found': ['FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Sandybridge',
  'filepath': '/home/me/fptest/venv/lib/python3.12/site-packages/numpy.libs/libscipy_openblas64_-ff651d7f.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]
```

**Comment by seberg** [comment]
Could you provide more context?  I am not very familiar with disabling such features, but overall, NumPy assumes you don't and without context I can't tell why we should not do that.
I.e. if you change the behavior of `longdouble` it isn't what NumPy (and plausibly the user) expects and giving this warning seems OK.
For one thing, while there are not many such places, in some places NumPy does compile in information about the precision used, so there are some functions I assume are definitely broken as stated by the warning.

**Comment by ernesto-ren** [comment]
@seberg Having extended precision enabled not only affects long double computations, but also float and doubles (see this stackoverflow [answer](https://stackoverflow.com/a/612640). This is the real issue.

In my case we don't actually use the long double data type. We perform computations (in doubles) across different architectures which we expect to produce bitwise identical results. When extended precision is enabled we don't get this reproducibility on Intel targets. That's why we turn it off. But then we see the above warning from numpy.

Note that I am not requesting that numpy turn off extended precision on Intel or provide the means to do so. I understand that might not be something that numpy should do. Rather, when extended precision is off the signature of the long double type changes and numpy doesn't recognize it. My request is that this new signature be added to the list of hard coded ones in `getlimits.py`. I think it makes sense to do so since turning off extended precision is a valid thing to do, particularly when looking for reproducibility.

**Comment by seberg** [comment]
What is the warning to you?  If you have an application you know doesn't use longdouble, you can just ignore it (long double may be broken, but you don't care).
If you have a library, you might be breaking other peoples code if they use longdouble (not very likely, but still), and I think @carlkl is right: You should only do that temporarily.

**Comment by seberg** [comment]
I have no confidence that removing the warning leaves us with a working "longdouble is the same as double", and without that, I am not really convinced removing it is very helpful.

**Comment by charris** [comment]
> which we expect to produce bitwise identical results. 

Why? Bitwise results depend on compilers, microcode, optimization levels, execution paths, and other such things. I wouldn't expect bitwise identical results from floating point.

**Comment by ernesto-ren** [comment]
@seberg I also can't say how exactly disabling precision affects long double, I was hoping the numpy folks would ;)

@charris @carlkl Understood, and we've gone to great lengths to achieve reproducibility eliminating all source of mismatches. Also, I never said across different x86 platforms, I said different _architectures_ besides Intel. This is a business requirement for us, not much we can do about it, unfortunately.

**Comment by seberg** [comment]
I'll close it then, thanks @ernesto-ren.  For now, I think the warning is fine (since I do believe _something_ will be broken).  I was curious about the reasoning for this, in case there was something we missed.
Cautioning against using such flags may make sense, but may just not be very relevant depending on where you are coming from.

Setting this flag more targeted (e.g. explicitly in python, maybe even context local only), may or may not be relevant.  You can also just ignore the warning for an application.
