### ISSUE TITLE
Issues building numpy 2.1.1 with classic Intel compilers

### ISSUE THREAD

**Issue by AgilentGCMS** [numpy/numpy#27492]
### Describe the issue:

I am trying to compile numpy 2.1.1 from source on a platform with intel ifort/icc/icpc compilers, i.e., not the newer oneapi icx/ifx/icpx compilers. I know this is no longer supported by intel, but I've compiled previous versions of numpy with the older intel compilers before, so I thought I would give it a try. However, the compilation barfs as below. I am pasting a few instances of the error, which occurs on multiple source files. If it's true that numpy 2.1.1 can no longer be compiled with ifort/icc/icpc, then what is the last version of numpy that could be compiled with those?

### Reproduce the code example:

```python
CC=icc CXX=icpc FC=ifort F77=ifort CFLAGS='-xHost -fPIC -fp-model=strict' FFLAGS='-xHost -fPIC -fp-model=strict' CXXFLAGS='-xHost -fPIC -fp-model=strict -std=c++17' python -m pip install --no-build-isolation -v . -Cbuild-dir=build -Csetup-args=-Dallow-noblas=false -Csetup-args=-Dblas-order=mkl -Csetup-args=-Dlapack-order=mkl -Csetup-args=-Dblas=mkl-dynamic-lp64-iomp -Csetup-args=-Dlapack=mkl-dynamic-lp64-iomp
```

### Error message:

```shell
In file included from ../numpy/_core/src/common/npy_import.h(7),
                   from ../numpy/_core/src/multiarray/common.h(12),
                   from ../numpy/_core/src/multiarray/buffer.c(16):
  ../numpy/_core/src/common/npy_atomic.h(37): error: expression must have pointer-to-struct-or-union type
        return (npy_uint8)atomic_load((const _Atomic(uint8_t)*)obj);
                          ^

  In file included from ../numpy/_core/src/common/npy_import.h(7),
                   from ../numpy/_core/src/multiarray/common.h(12),
                   from ../numpy/_core/src/multiarray/buffer.c(16):
  ../numpy/_core/src/common/npy_atomic.h(52): error: expression must have pointer-to-struct-or-union type
        return atomic_load((const _Atomic(void *)*)obj);
               ^

  In file included from ../numpy/_core/src/common/npy_import.h(7),
                   from ../numpy/_core/src/multiarray/common.h(12),
                   from ../numpy/_core/src/multiarray/buffer.c(16):
  ../numpy/_core/src/common/npy_atomic.h(75): error: expression must have pointer-to-struct-or-union type
        atomic_store((_Atomic(uint8_t)*)obj, value);
        ^

  In file included from ../numpy/_core/src/common/npy_import.h(7),
                   from ../numpy/_core/src/multiarray/common.h(12),
                   from ../numpy/_core/src/multiarray/buffer.c(16):
  ../numpy/_core/src/common/npy_atomic.h(87): error: expression must have pointer-to-struct-or-union type
        atomic_store((_Atomic(void *)*)obj, value);
        ^
```

### Python and NumPy Versions:

Python 3.11.10

**Comment by AgilentGCMS** [comment]
@rgommers In one of my earlier tickets you had asked me to tag you in case of problems with intel compilers and numpy. Wondering if you had any thoughts on this error.

**Comment by rgommers** [comment]
That's a question for @ngoldbaum I think. It's not immediately clear to me whether there's something wrong with the way `atomic_load`/`atomic_store` is used here, or if the Intel compilers have an implementation issue.

**Comment by ngoldbaum** [comment]
I don't understand this error.

Out of curiosity, can you compile CPython itself using this version of the intel compilers? The code we're using was adapted from the CPython `pyatomic.h` header.

If compiling CPython does work, it would be interesting to know which version of the pyatomic implementation it's picking. There are implementations for GCC-style atomics, C11 atomics, and MSVC atomics. From the compiler error, it looks like it's trying to compile with C11 atomics, but that's breaking for some reason.

It might also be the case that if you hack the numpy header so that only `GCC_ATOMICS` is defined, then the build will succeed. I don't know offhand if the Intel compilers ever tried to emulate the GCC atomics API, or if they just went straight to C11 atomics.

**Comment by AgilentGCMS** [comment]
@ngoldbaum I did compile cpython with the same intel compilers, and now I'm trying to build numpy on top of that with the same compilers. Here's the configure line I used to compile python 3.11.10, and you can see the `CFLAGS` etc (plus some custom paths for my platform):
```
./configure --prefix=/discover/nobackup/projects/tm5var4d/packages/python/3.11.10 --enable-optimizations --with-computed-gotos --with-ensurepip=install --disable-ipv6 --with-libm=-limf \
    LIBS='-lpthread -limf -lirc' \
    CFLAGS='-O3 -g -fPIC -fp-model=strict -fwrapv -fomit-frame-pointer -xHost' \
    CC=icc CXX=icpc \
    CXXFLAGS='-O3 -g -fPIC -fp-model=strict -fwrapv -fomit-frame-pointer -xHost' \
    CPPFLAGS='-I/discover/nobackup/projects/tm5var4d/packages/openssl/1.1.1w/include -I/usr/include/ncursesw -I/discover/nobackup/projects/tm5var4d/packages/libffi/3.2.1/include' \
    LDFLAGS='-L/discover/nobackup/projects/tm5var4d/packages/openssl/1.1.1w/lib -L/discover/nobackup/projects/tm5var4d/packages/libffi/3.2.1/lib/../lib64'
```
Since the numpy build process outputs a lot of stuff besides those errors, it's possible that there is something there that will provide a clue as to what exactly is going wrong. I invoked the numpy build with
```
CC=icc CXX=icpc FC=ifort F77=ifort \
    CFLAGS='-xHost -fPIC -fp-model=strict' \
    FFLAGS='-xHost -fPIC -fp-model=strict' \
    CXXFLAGS='-xHost -fPIC -fp-model=strict -std=c++17' \
    python -m pip install --no-build-isolation -v . -Cbuild-dir=build -Csetup-args=-Dallow-noblas=false \
    -Csetup-args=-Dblas-order=mkl -Csetup-args=-Dlapack-order=mkl \
    -Csetup-args=-Dblas=mkl-dynamic-lp64-iomp -Csetup-args=-Dlapack=mkl-dynamic-lp64-iomp
```
The first error that it threw was the following
```
  In file included from ../numpy/_core/src/common/common.hpp(7),
                   from ../numpy/_core/src/npymath/halffloat.cpp(12):
  ../numpy/_core/src/common/npdef.hpp(5): error: #error directive: "NumPy requires a compiler with at least C++17 enabled"
        #error "NumPy requires a compiler with at least C++17 enabled"
         ^
```
This was despite the `-std=c++17` that I added to `CXXFLAGS`. Reading up online, it seemed that `icc/icpc` needed a recent `gcc` to be present as well. So then I added `gcc 13.1.0` to the environment, after which the numpy build failed with
```
  [72/578] Compiling C++ object numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o
  FAILED: numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o
  icpc -Inumpy/_core/libhighway.a.p -Inumpy/_core -I../numpy/_core -I../numpy/_core/src/highway -I/gpfsm/dtse01/tdirs/batch/slurm.39336633.sbasu1/numpy-2.1.1/build/meson_cpu -fvisibility=hidden -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -w3 -Wpch-messages -diag-disable:remark -std=c++17 -O3 -msse -msse2 -msse3 -DNPY_HAVE_SSE2 -DNPY_HAVE_SSE -DNPY_HAVE_SSE3 -xHost -fPIC -fp-model=strict -std=c++17 -fPIC -DTOOLCHAIN_MISS_ASM_HWCAP_H -MD -MQ numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o -MF numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o.d -o numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o -c ../numpy/_core/src/highway/hwy/abort.cc
  In file included from /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/bits/char_traits.h(50),
                   from /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/string(42),
                   from ../numpy/_core/src/highway/hwy/abort.cc(12):
  /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/type_traits(3363): error: type name is not allowed
      inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                                                ^
```
The full build log is [here](https://drive.google.com/file/d/1kGXy6YP7MCdH0l5S0e9tptHs73D7Hy4o/view?usp=sharing).

**Comment by AgilentGCMS** [comment]
As an aside, what's the way to capture all these build output messages from meson build? The `2>&1 > build.log` I learnt in linux kindergarten does not capture anything.

**Comment by AgilentGCMS** [comment]
I have now tried a few different intel compiler versions, and all have failed with the error above, `error: type name is not allowed`. Here are the next few errors, which may or may not be triggered by that first one.
```
  [145/578] Compiling C++ object numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o
  FAILED: numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o
  icpc -Inumpy/_core/libhighway.a.p -Inumpy/_core -I../numpy/_core -I../numpy/_core/src/highway -I/gpfsm/dtse01/tdirs/batch/slurm.39392386.sbasu1/numpy-2.1.1/build/meson_cpu -fvisibility=hidden -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -w3 -Wpch-messages -diag-disable:remark -std=c++17 -O3 -msse -msse2 -msse3 -DNPY_HAVE_SSE2 -DNPY_HAVE_SSE -DNPY_HAVE_SSE3 -xHost -fPIC -fp-model=strict -fPIC -DTOOLCHAIN_MISS_ASM_HWCAP_H -MD -MQ numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o -MF numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o.d -o numpy/_core/libhighway.a.p/src_highway_hwy_abort.cc.o -c ../numpy/_core/src/highway/hwy/abort.cc
  In file included from /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/bits/char_traits.h(50),
                   from /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/string(42),
                   from ../numpy/_core/src/highway/hwy/abort.cc(12):
  /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/type_traits(3363): error: type name is not allowed
      inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                                                ^

  In file included from /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/bits/char_traits.h(50),
                   from /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/string(42),
                   from ../numpy/_core/src/highway/hwy/abort.cc(12):
  /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/type_traits(3363): error: type name is not allowed
      inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                                                       ^

  In file included from /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/bits/char_traits.h(50),
                   from /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/string(42),
                   from ../numpy/_core/src/highway/hwy/abort.cc(12):
  /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/type_traits(3363): error: identifier "__is_convertible" is undefined
      inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                               ^

  compilation aborted for ../numpy/_core/src/highway/hwy/abort.cc (code 2)
```
Multiple other C++ objects also fail to compile with the same sequence of errors.

**Comment by r-devulap** [comment]
```
  /gpfsm/dulocal/sles12/other/gcc/13.1.0/bin/../include/c++/13.1.0/type_traits(3363): error: identifier "__is_convertible" is undefined
      inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
```
These seem to be a problem with gcc13 that someone else reported similar compile failures too: https://forums.developer.nvidia.com/t/strange-errors-after-system-gcc-upgraded-to-13-1-1/252441. Could you try with gcc-12 to see if it goes away?

**Comment by AgilentGCMS** [comment]
@r-devulap I changed to gcc 12, recompiled python, then tried rebuilding numpy. It failed again, but with a different error. The first error is
```
  In file included from ../numpy/_core/src/common/common.hpp(10),
                   from ../numpy/_core/src/npymath/halffloat.cpp(12):
  ../numpy/_core/src/common/half.hpp(45): error: expected a ")"
        );
```
Full build log is [here](https://drive.google.com/file/d/1LKNjGgj5RBGHHKM6PaJaIpMmGRlKk4-8/view?usp=sharing). My numpy build command was
```
CC=icc CXX=icpc FC=ifort F77=ifort CFLAGS='-xHost -fPIC -fp-model=strict' FFLAGS='-xHost -fPIC -fp-model=strict' CXXFLAGS='-xHost -fPIC -fp-model=strict -std=c++17' python -m pip install --no-build-isolation -v . -Cbuild-dir=build -Csetup-args=-Dallow-noblas=false -Csetup-args=-Dblas-order=mkl -Csetup-args=-Dlapack-order=mkl -Csetup-args=-Dblas=mkl-dynamic-lp64-iomp -Csetup-args=-Dlapack=mkl-dynamic-lp64-iomp
```
I can't imagine that numpy source code would have an actual syntax error like a missing closing brace, so something else must be going on.

As an aside, is there really no way to capture all these build messages except to scroll up and copy? Output redirection with `>` doesn't seem to work.

**Comment by eagunn** [comment]
@AgilentGCMS You wrote:
> what's the way to capture all these build output messages from meson build? . . . `2>&1 > build.log`

Shouldn't that be: `[whatever command] > buildlog 2>&1`

**Comment by AgilentGCMS** [comment]
@eagunn Thank you! Your suggestion worked. I learned today that the order of "redirect stderr to stdout" and "redirect stdout to file" matters!

**Comment by ngoldbaum** [comment]
```
In file included from ../numpy/_core/src/common/common.hpp(10),
                   from ../numpy/_core/src/npymath/halffloat.cpp(12):
  ../numpy/_core/src/common/half.hpp(45): error: expected a ")"
        );
```

Looking at `half.cpp`, there's some sort of complicated preprocessor magic happening right above line 45, I wonder if you're exercising a code block that no one has actually exercised before, leading to the compiler error you're seeing. I don't immediately see what the issue is there, I guess it could also be a compiler bug?

Anyway, it shouldn't be necessary to build Python itself with the intel compilers, but the fact that it's not building is a good hint that this might be painful.

I think I'd need local access to this compiler version to be able to dig in more to understand why the original build failure was happening.

**Comment by AgilentGCMS** [comment]
> Anyway, it shouldn't be necessary to build Python itself with the intel compilers, but the fact that it's not building is a good hint that this might be painful.

@ngoldbaum Python _is_ building without problems on several intel compilers, but numpy isn't. I have tested a few compiler versions so far, but I have access to several more on that system. I haven't tested all of them because I had the idea that to make things maximally bug free I would need to first rebuild python with all those compilers. If that's not the case, i.e., it's sufficient to just try building numpy with different intel compilers, I can do that. So far I've tested a couple of versions, and they could both build python, but both barfed on numpy with that `half.hpp` error. 

> I think I'd need local access to this compiler version to be able to dig in more to understand why the original build failure was happening.

I was afraid you'd say that :-) I am not the admin on the system so I can't give you local access, but I am very happy to test whatever code block you send me. Having intel compilers and intel MKL on an intel CPU yet not being able to use them in numpy is maddening to me. And the irony is that all this happened because I decided to upgrade python and numpy. I had compiled numpy 1.26.1 against python 3.8.2 using those same compilers on this platform using the old distutils method.

**Comment by andyfaff** [comment]
I know that you're trying to use the older compilers, but do the oneapi compilers work successfully?

(I'm not sure if it helps, but you could have a look at how scipy uses the ifx oneapi compiler in a CI run, https://github.com/scipy/scipy/blob/main/.github/workflows/windows_intel_oneAPI.yml)

**Comment by AgilentGCMS** [comment]
@andyfaff I have been able to compile scipy and numpy using the newer oneapi compilers on a few different platforms. However, on this particular compute system the latest oneapi compiler I have available is 2021.4, and I know from previous experience (including numpy and scipy tickets I've filed) that scipy and numpy doesn't build successfully, or builds but doesn't pass tests, before oneapi 2023.x. So I'm not even trying to build with oneapi 2021.4, instead choosing the latest "classic" compiler version on the system. I was optimistic because I have previously compiled andtested python 3.8.2/numpy 1.26.1 with that compiler version, but I was unsuccessful (hence this ticket).

The pain point is always C++, it seems.

**Comment by ngoldbaum** [comment]
For the `half.hpp` error, I don't see how you can be hitting an error about an unclosed paren. No matter what the preprocessor macros are set to, I don't think it should impact the nesting of parens. This makes me suspect some kind of compiler bug.

I don't think you ever shared which version of the intel compilers you're using, it would be useful to know that to search for compiler bugs related to constexpr support. Depending on how old the compiler is, you might be running a version from when they were still implementing constexpr.

I don't think you've mentioned the issue you originally ran into about use of C11 atomics, but now that I understand that that Python compiles successfully - it would help to see how it's compiling the pyatomic API - in particular which "flavor" of atomics its detecting.

In particular, it would help to know which branch of this preprocessor macro you end up in:

https://github.com/python/cpython/blob/d20c43d8e270016d743af6e8e0f8267e396a71f4/Include/cpython/pyatomic.h#L520-L544

If it picks C11 atomics, then I'm very confused why you're not hitting identical compiler errors from your original report, since the code should be identical.

Finally, if supporting the Intel compilers is important to you, then you might be interested in improving NumPy's CI coverage to include a test run under a version of the Intel compilers, it's that's possible given licensing concerns. The reason this regressed is that we don't test with the Intel compilers and we don't test with the Intel compilers because no one has done the work to set that up. I don't think it's reasonable to expect something to continue to work if it isn't tested, so the only way to ensure that something you need continues to work is to verify that an upstream like NumPy is doing testing, or do the testing yourself and report bugs as they happen so they can be caught quickly.

**Comment by AgilentGCMS** [comment]
> I don't think you ever shared which version of the intel compilers you're using, it would be useful to know that to search for compiler bugs related to constexpr support. Depending on how old the compiler is, you might be running a version from when they were still implementing constexpr.

* I tried 2021.7.0, the latest available on that system, and numpy compiled (surprisingly), but `numpy.test()` crashed on `_core/tests/test_einsum.py`.
* Next, I tried 2021.6.0, and `numpy` failed to build with
```
  In file included from ../numpy/_core/src/common/common.hpp(9),
                   from ../numpy/_core/src/npysort/x86_simd_qsort.hpp(4),
                   from ../numpy/_core/src/npysort/quicksort.cpp(57):
  ../numpy/_core/src/common/npstd.hpp(34): error: namespace "std" has no member "complex"
    using std::complex;
               ^
```
* Compilers 2021.5.0 and 2021.4.0 failed with the same error as 2021.6.0.
* Then I tried 19.1.0.166, which failed with
```
  In file included from ../numpy/_core/src/common/common.hpp(10),
                   from ../numpy/_core/src/npymath/halffloat.cpp(12):
  ../numpy/_core/src/common/half.hpp(45): error: expected a ")"
        );
         ^
```
* Which brought me to 19.1.3.304, then 19.1.2.254, both of which failed with the same error as 19.1.0.166.

And that's the summary of all the compiler versions I have available on the system.

> I don't think you've mentioned the issue you originally ran into about use of C11 atomics, but now that I understand that that Python compiles successfully - it would help to see how it's compiling the pyatomic API - in particular which "flavor" of atomics its detecting.
> 
> In particular, it would help to know which branch of this preprocessor macro you end up in:
> 
> https://github.com/python/cpython/blob/d20c43d8e270016d743af6e8e0f8267e396a71f4/Include/cpython/pyatomic.h#L520-L544
> 
> If it picks C11 atomics, then I'm very confused why you're not hitting identical compiler errors from your original report, since the code should be identical.

The original issue I reported, `type name is not allowed`, went away when I switched from gcc 13 to gcc 12 following @r-devulap's suggestion.

> Finally, if supporting the Intel compilers is important to you, then you might be interested in improving NumPy's CI coverage to include a test run under a version of the Intel compilers, it's that's possible given licensing concerns. The reason this regressed is that we don't test with the Intel compilers and we don't test with the Intel compilers because no one has done the work to set that up. I don't think it's reasonable to expect something to continue to work if it isn't tested, so the only way to ensure that something you need continues to work is to verify that an upstream like NumPy is doing testing, or do the testing yourself and report bugs as they happen so they can be caught quickly.

I have to maintain and run a python stack on five different systems. Three of them have moved away from "classic" intel compilers to a recent (2023+) version of intel oneapi which actually builds numpy/scipy successfully. However, the other two still run classic intel compilers, so yes, supporting numpy on those platforms is important to me. The trials I'm encountering now is because of my effort to update the python/numpy stack on one of them, and going by my experience I'm in no hurry to attempt this on the other system.

How can I help add the classic intel compilers to numpy's CI coverage? If it involves periodically checking out code, building and reporting back errors or success status, that would be possible. If it involves giving someone else login access to these systems, that would be hard/impossible.

**Comment by r-devulap** [comment]
> How can I help add the classic intel compilers to numpy's CI coverage

Building NumPy with intel compiler in a CI shouldn't be hard to do. Adding a starting point, we can iterate on it: see https://github.com/numpy/numpy/pull/27544

**Comment by AgilentGCMS** [comment]
In the meantime, I tried going back numpy versions just to find one that I could install with intel "classic" compilers. I tried compiling numpy 1.26.1 with icc/icpc 2021.4.0, and while the build succeeded (yay!), 227 tests failed in `numpy.test()`. That's too many to list here, but suffice it to say that it's not a winning combination.

**Comment by rgommers** [comment]
> As an aside, is there really no way to capture all these build messages except to scroll up and copy? Output redirection with > doesn't seem to work.

I haven't had this issue I think. Just double checked on macOS; both `spin build > tmp.txt` and with `pixi` I don't have a problem redirecting the whole build log into a file. Seems to be solved now though, 

> How can I help add the classic intel compilers to numpy's CI coverage? If it involves periodically checking out code, building and reporting back errors or success status, that would be possible.

I think for the classic compilers, since they're basically end of life, just reporting new issues and helping get them fixed is probably better/easier than trying to maintain a CI job. We have many compilers and platforms in such a "second tier" support status (e.g., AMD, IBM, Fujitsu, etc. compilers). 

> The original issue I reported, `type name is not allowed`, went away when I switched from gcc 13 to gcc 12

I'll update the issue title for this. It's getting harder to follow this issue with the multitude of errors and fixes/workarounds; it may be useful to summarize them in the issue description (and/or in a new comment, linking to that from the issue description).

**Comment by AgilentGCMS** [comment]
> > How can I help add the classic intel compilers to numpy's CI coverage? If it involves periodically checking out code, building and reporting back errors or success status, that would be possible.
> 
> I think for the classic compilers, since they're basically end of life, just reporting new issues and helping get them fixed is probably better/easier than trying to maintain a CI job. We have many compilers and platforms in such a "second tier" support status (e.g., AMD, IBM, Fujitsu, etc. compilers).

This is also very much OK with me. The platform I'm trying to build on will eventually switch to the LLVM compilers, just not very soon. So yes, I'd be happy to fix the occasional bugs and move on. The trouble is that I haven't been able to get any numpy release to build so far.

> > The original issue I reported, `type name is not allowed`, went away when I switched from gcc 13 to gcc 12
> 
> I'll update the issue title for this. It's getting harder to follow this issue with the multitude of errors and fixes/workarounds; it may be useful to summarize them in the issue description (and/or in a new comment, linking to that from the issue description).

Fair enough. Do you want me to close this issue and open a new one with just the remaining problem(s)?
