### ISSUE TITLE
BUG: Invalid calculation of percentile

### ISSUE THREAD

**Issue by george0st** [numpy/numpy#27529]
### Describe the issue:

Calculation of percentile with method 'lower' does not work correctly, see sample:

- input list **[0.34, 0.24, 0.11, 0.21, 0.33]**
- order list **[0.11, 0.21, 0.24, 0.33, 0.34]**
- 70 percentile = **4.2** in case of method 'lower', the value will be **4** => expected output will be **0.33** but numpy returns value **0.24**

### Reproduce the code example:

```python
import numpy as np

sequence = [0.34, 0.24, 0.11, 0.21, 0.33]
print(f"Numpy: {np.percentile(sequence,70, method='lower')}")
```

### Error message:

```shell
It is without error, but output value is invalid
```

### Python and NumPy Versions:

2.1.2 and 2.1.1
3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

**Comment by seberg** [comment]
Please carefully read the documentation.  There are many ways to define/estimate sample quantile levels (i.e. the population quantile from the sample drawn).
I assume you are basing your "70% = 4.2" off of one definition you read somewhere, and one of the methods certainly matches that (and maybe the full thing you expect).
`lower` isn't one you are likely to find in literature, but it is certainly correct as per definition.

I'll close for now, there shouldn't be a bug here, just a confusion about the exact definition being used.  We can keep discussing, though.

**Comment by george0st** [comment]
Hi @seberg , I still think, that implementation of method 'lower' is not valid see definition from documentation

```
lower:
NumPy method kept for backwards compatibility. Takes i as the interpolation point.

where:
The optional method parameter specifies the method to use when the desired percentile lies between two indexes i and j = i + 1
```

**Comment by seberg** [comment]
The documentation notes describe the exact definitions used by NumPy.  Your 4.2, is `0.7 * (n + 1)` where, as I said, the `n + 1` has nothing to do with the definition used by "lower" (or the default).

**Comment by seberg** [comment]
The one thing the documentation could say more clearly maybe is that those "legacy" ones use the same corrections as the default `linear`, so `alpha=1` and `beta=1`.
