### ISSUE TITLE
BUG:  build of python3.13t in windows fails 

### ISSUE THREAD

**Issue by eyalk11** [numpy/numpy#27527]
### Describe the issue:

I tried building  it (main) on windows : 

`python3.13t.bat -m pip install .` 

(or just pip install) 

```
 Checking for size of "PY_LONG_LONG" with dependency python: 8
      Has header "complex.h" : YES
      Checking for type "complex float" : NO

      ..\numpy\_core\meson.build:175:4: ERROR: Problem encountered: "complex.h" header does not include complex type complex float
```

### Reproduce the code example:

```python
mentioned
```

### Error message:

```shell
..\numpy\_core\meson.build:175:4: ERROR: Problem encountered: "complex.h" header does not include complex type complex float
```
```


### Python and NumPy Versions:

3.13.0 t (no GIL) 

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

**Comment by eyalk11** [comment]
I am btw not sure how to specify different compiling options in this context.

**Comment by mattip** [comment]
It seems you are on windows. In your first attempt what compiler are you using? In the second one, did you install the build dependencies in your virtual environment? If you wish to try the free threading wheels (without compiling), you should wait a few days for them to appear on PyPI. Although I don't see them on https://anaconda.org/scientific-python-nightly-wheels/numpy/files nor in the [artifacts from the wheel builder CI run](https://github.com/numpy/numpy/actions/runs/11198402107). I wonder if something is off?

**Comment by mattip** [comment]
Ahh, we are [excluding that build](https://github.com/numpy/numpy/blob/cd4d6ba5d1aee621abb9d7d52ecb48cb7bc43c98/.github/workflows/wheels.yml#L97). @ngoldbaum is that a left-over from being cautious with the free-threading builds?

**Comment by ngoldbaum** [comment]
I haven't yet tried to do anything with the free-threaded build on Windows. I think we still need an update to our vendored meson for it to build, @rgommers was going to work on that.

**Comment by eyalk11** [comment]
Hi, thanks for the reply. I probably should wait. Just drop a comment if you may when it does work :) 
I tried the no-GIL in windows and it is a huge improvment. 

On the first time I tried to build it with ninja. 

I did install the build reqs in my global env. Despite it not being the most recommended way. I don't think it is a dependency missing issue. Though maybe this what caused it not to work. I don't see how.

**Comment by Alec1198055421** [comment]
hi，

**Comment by rgommers** [comment]
> Current status: Is there a usable version of numpy available now?

There are conda packages for Windows available in Conda-forge now (after https://github.com/conda-forge/numpy-feedstock/pull/332). Install instructions at https://py-free-threading.github.io/installing_cpython/#conda-packages

Nightly wheels will hopefully follow shortly, we just got those unblocked.
