### ISSUE TITLE
set_printoptions with threshold as "nan" bug

### ISSUE THREAD

**Issue by Panoplos** [numpy/numpy#2752]
According to the numpy docs, if you want to disable summary printing for ndarray, you call `set_printoptions(threshold="nan")`, but this results in the following error when doing the print:

``` python
File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/numpy/core/arrayprint.py", line 240, in _array2string
    if a.size > _summaryThreshold:
TypeError: unorderable types: int() > str()
```

Line 240 of arrayprint.py should be changed to:

``` python
if _summaryThreshold != "nan" and a.size > _summaryThreshold:
```

**Comment by airrohit123** [comment]
thanks for 
set_printoptions(threshold=numpy.nan)
this work for me

**Comment by lebuckle** [comment]
Also worked for me changing to set_printoptions(threshold=numpy.nan), thanks!

**Comment by eric-wieser** [comment]
This is a bug in the documentation, and should be fixed in `doc/source/user/quickstart.rst`
