### ISSUE TITLE
BUG: Setting values to elements or slices do not elevate data type

### ISSUE THREAD

**Issue by sebreens** [numpy/numpy#27559]
### Describe the issue:

When the numpy array is created using int dtype, the data type of the array is not elevated if one of the elements (or a slice) is set to a float. Given that on creation dtype is elevated, this seems counter intuitive. 

### Reproduce the code example:

```python
import numpy as np
a = np.array([0,0,0])
a[1] = 0.1
print(a) #[0 0 0]
```

### Python and NumPy Versions:

1.26.4
3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

**Comment by charris** [comment]
When you assign values to elements or slices of an array you are using the same memory, a new array is not created, hence it keeps the original dtype and casts the value assigned to that dtype.
