### ISSUE TITLE
DOC: Questions Regarding C-API Documentation Status and Maintenance

### ISSUE THREAD

**Issue by fengluoqiuwu** [numpy/numpy#27576]
#### Description:
While reading the C-API documentation, I came across several sections that appear to be outdated or don't fully match the current codebase. I understand that maintaining up-to-date documentation can be challenging, especially for something as complex as the C-API. I would love to understand more about the current strategy and plans regarding the documentation, and I hope the following questions could help clarify things.

#### Questions:
1. **What is the current status of C-API documentation development?**
   - Are there any ongoing efforts or plans to regularly update and maintain the C-API documentation? I understand that the priorities in open-source projects can shift, but it would be great to know if this is on the roadmap.

2. **Is Doxygen being actively used to generate the C documentation?**
   - The contribution guide mentions using Doxygen for the C parts of NumPy, but I couldn't find clear references to its usage in the code. Is Doxygen still integrated into the documentation process, or has the approach shifted more towards manual documentation?

3. **Should C-API documentation include private/internal sections?**
   - I was also curious about the policy regarding internal/private C-API sections. Is there a standard for what parts of the C-API should be documented, or do we generally focus on the public-facing API?

**Comment by ngoldbaum** [comment]
> Are there any ongoing efforts or plans to regularly update and maintain the C-API documentation? I understand that the priorities in open-source projects can shift, but it would be great to know if this is on the roadmap.

Yes, we should fix out-of-date stuff in the docs. Please open issues and/or PRs about this.

> The contribution guide mentions using Doxygen for the C parts of NumPy, but I couldn't find clear references to its usage in the code. Is Doxygen still integrated into the documentation process, or has the approach shifted more towards manual documentation?


There was a half-completed transition to doxygen that was driven by a contributor who we haven't seen in a while. I think @seberg wanted this too.

We don't use doxygen in the docs build and I don't think it makes any sense to insist contributors provide C docstrings if we don't actually run CI with doxygen. IMO this needs a champion and someone to make sure we actually use doxygen in the docs build if we want to continue it and convert the rest of the docstrings.

> I was also curious about the policy regarding internal/private C-API sections. Is there a standard for what parts of the C-API should be documented, or do we generally focus on the public-facing API?

We generally focus on the public API. Some internals have docstrings but we don't require it. It would be good to add better documentation on NumPy internals, but I don't think we'll ever go through all the C internals and make sure there are internal docstrings that are correct. It would be better to have a high-level internals document IMO.

**Comment by seberg** [comment]
I like to have docstrings on most functions, but yeah, they can get outdated.  For public functions, yeah, it would be great to not duplicate docs.  It's nice to have them in source, but we need them in `.rst` form right now unfortunately.

If we ever generate the public API docs from source, then maybe we could think about also generating the same docs for private API (marking it accordingly).
That would maybe make creating high-level internal docs easier too, because just grouping functions with their existing docs would probably go a long way.

**Comment by fengluoqiuwu** [comment]
Thank you both for your clarifications! I understand your points now. I appreciate your help, and I'll be sure to submit a PR if I come across any inaccuracies while reviewing the C API.
