### ISSUE TITLE
BUG: The order of importing numpy and open3d affects the loading of libGL.

### ISSUE THREAD

**Issue by wzy-99** [numpy/numpy#27589]
### Describe the issue:

In a simple GUI visualization code, if I import open3d before numpy, the program runs normally. However, if I import numpy first and then open3d, there will be an OpenGL loading error.

Here is my code:

1. Import numpy first:
```python
import numpy as np
import open3d as o3d

points = np.random.rand(1000, 3)
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)

o3d.visualization.draw_geometries([pcd])
```  
The program encounters an error:
```bash
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[Open3D WARNING] GLFW Error: GLX: Failed to create context: GLXBadFBConfig
[Open3D WARNING] Failed to create window
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.
```
2. Import open3d first:
```python
import open3d as o3d
import numpy as np

points = np.random.rand(1000, 3)
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)

o3d.visualization.draw_geometries([pcd])
```
The program runs normally.

My environment is WSL2 Ubuntu 22.04.3 LTS.

My guess is that importing numpy first might change some environment settings, leading to issues with OpenGL loading. However, I don't know how to verify this.

Can you help me solve this problem? Or provide some ideas on how to anlayse it?

### Reproduce the code example:

```python
import numpy as np
import open3d as o3d

points = np.random.rand(1000, 3)
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)

o3d.visualization.draw_geometries([pcd])
```

### Error message:

```shell
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[Open3D WARNING] GLFW Error: GLX: Failed to create context: GLXBadFBConfig
[Open3D WARNING] Failed to create window
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.
```

### Python and NumPy Versions:

2.0.1
3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0]

### Runtime Environment:

[{'numpy_version': '2.0.1',
  'python': '3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='WZY-LAPTOP', release='5.15.153.1-microsoft-standard-WSL2', version='#1 SMP Fri Mar 29 23:14:13 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'filepath': '/home/wzy/miniconda3/envs/spann3r/lib/libmkl_rt.so.2',
  'internal_api': 'mkl',
  'num_threads': 10,
  'prefix': 'libmkl_rt',
  'threading_layer': 'intel',
  'user_api': 'blas',
  'version': '2023.1-Product'},
 {'filepath': '/home/wzy/miniconda3/envs/spann3r/lib/libomp.so',
  'internal_api': 'openmp',
  'num_threads': 20,
  'prefix': 'libomp',
  'user_api': 'openmp',
  'version': None}]

**Comment by rkern** [comment]
I see that you are using `miniconda` with builds of numpy that link against the MKL and OpenMP. It's possible that the dynamic linking setup done for these might be interfering with the finding of the dynamic libraries needed by `open3d`. Try setting up a plain-python venv and `pip install numpy` to get the official wheels and see if that works.

**Comment by wzy-99** [comment]
Hello @rkern, thank you for your answer.

I tried your solution, and the issue was resolved.

Your explanation about the differences in dynamic linking between conda environments and venv has indeed given me some inspiration, and I am very grateful for your response!
