### ISSUE TITLE
Linux QEMU CI currently failing

### ISSUE THREAD

**Issue by fengluoqiuwu** [numpy/numpy#27601]
I submitted a PR today, but it failed due to a Meson build failure. I believe my modifications should not affect the Meson build in any way.

To verify, I attempted to submit an empty commit to the PR that passed all tests yesterday, but that too resulted in the same Meson build failure.

Is there any recent change in the Meson build configuration or CI setup that could be causing this issue? Any insights would be appreciated.

**Comment by andyfaff** [comment]
It looks like all the QEMU jobs are failing. @seiko2plus, do you know of any structural reason why they've stopped working?

**Comment by andyfaff** [comment]
See e.g. https://github.com/numpy/numpy/actions/runs/11429677903.

**Comment by abhishek-iitmadras** [comment]
Self-assign to myself with high priority

**Comment by abhishek-iitmadras** [comment]
Fix https://github.com/numpy/numpy/pull/27613

**Comment by seiko2plus** [comment]
@andyfaff, Thanks for heading up! it seems docker hub tags been branched based on the `--platform`, before this update it was okay to just specify the arch name before container.
