### ISSUE TITLE
DOC: Ambiguity in Documentation Example for 'numpy.ndarray.byteswap' and Default Integer Dtype

### ISSUE THREAD

**Issue by Shezeeblanka** [numpy/numpy#27628]
### Issue with current documentation:

The documentation example for `numpy.ndarray.byteswap` demonstrates viewing an array of integers as `np.uint8`. However, the behavior of the example is platform-dependent and may lead to confusion, especially for users on 64-bit Windows systems where the default dtype for `np.array` is `np.int32` rather than `np.int64`.

**Steps to Reproduce:**
1. On a 64-bit Windows system, run the following code:
```python
import numpy as np
A = np.array([1, 2, 3])
print(A.view(np.uint8))
```
2. The output on 64-bit Windows systems shows the default dtype as `np.int32`:
```
array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0], dtype=uint8)
```
This contrasts with the documentation example, which assumes `np.int64`:
```
array([1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)
```
**Problem Description:**
The discrepancy between the documentation and actual behavior on different platforms could lead to confusion for users. The example appears to assume that `np.array` defaults to `np.int64`, which is true on most 64-bit Linux systems but not on 64-bit Windows, where `np.int32` is the default dtype. This difference is not mentioned in the documentation.

### Idea or request for content:

- Explicitly set the dtype in the example (e.g., `np.array([1, 2, 3], dtype=np.int64)`) to ensure consistency across platforms.
- Alternatively, add a note explaining that the default dtype of `np.array` may vary by platform (`np.int64` on most 64-bit Linux systems, `np.int32` on Windows).

This clarification will help avoid confusion for users on different platforms.

**Comment by fengluoqiuwu** [comment]
I ran the code on my 64-bit Windows machine, and it produced the expected result:

```python
[1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
```
System information:

 - NumPy version: 2.2.0.dev0+git20241024.78760de
 - Operating System: Windows 11 (Version 10.0.22631)
 - Machine: AMD64
 - Processor: Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
 - Python Version: 3.12.7
 - Architecture: 64bit
Given this, I don't believe the issue is specific to Windows.

**Comment by Shezeeblanka** [comment]
> I ran the code on my 64-bit Windows machine, and it produced the expected result:
> 
> ```python
> [1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
> ```
> 
> System information:
> 
> * NumPy version: 2.2.0.dev0+git20241024.78760de
> * Operating System: Windows 11 (Version 10.0.22631)
> * Machine: AMD64
> * Processor: Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
> * Python Version: 3.12.7
> * Architecture: 64bit
>   Given this, I don't believe the issue is specific to Windows.

This is interesting; I thought this behavior was consistent across all 64-bit Windows platforms. Ultimately, I believe explicitly specifying the dtype will eliminate any potential confusion.

**Comment by fengluoqiuwu** [comment]
I agree.

**Comment by seberg** [comment]
The default dtype is int64 on 64bit windows starting with NumPy 2 also.  But yes, we could set the dtype explicitly to be eclear.
