### ISSUE TITLE
BUG: Operation spuriously returns a legacy string

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#27637]
After applying the changes from #27636:

```
>>> print(repr(np.strings.replace(
            np.array(["hello planet"], dtype="U"),
            np.array("planet", dtype="T"),
            np.array("world", dtype="T"))))
array(['hello world'], dtype='<U11')
```

We get a unicode array back, despite the fact that StringDType explicitly installs a promoter for this case.

I thought this had something to do with the fact that the legacy string unicode promoters work by constructing a promoter DType tuple that's filled with `None` entries. But that's fine, since `None` has less priority than a specific DType.

Instead something else is going on. I got as far as tracing through the call to `resolve_descriptors`, which does correctly set the output DType to StringDType, so something else fishy is going on later when the actual output array is created.

**Comment by seberg** [comment]
Nice, tracking, but the error is just in the Python code.  It thinks we are taking the code path designed for old strings, and if it does that it has to pass the `out=` array.

So the ufunc does the right thing:  It operates with the new strings, but happily casts to the `U11` output that the Python code forces it to cast to.
(Which, is a same-kind cast, so not an error.)

**Comment by ngoldbaum** [comment]
Thanks! I should have probably noticed that `out` was set even though I didn't pass it in...

> The easiest solution is probably just to promote ahead of time. You could do that with _replace.resolve_dtypes, but not sure it is worth it compared to just using np.result_type here.

This works. I'll apply the same refactoring to the other string ufunc wrappers and update #27636  to close this.

**Comment by ngoldbaum** [comment]
> and this works

Oh actually one wrinkle is that `np.result_type` assumes a string argument is a dtype, but then strings are also array-likes 🙃 

I can get it to work by first converting to array and then calling `result_type`, but it is a little annoying for this use case where the arguments are very likely to be string scalars.

**Comment by seberg** [comment]
Yeah, I was starting to wonder if we should have `result_type(*args, objs=, dtypes=)`, because it's quite messy that there is "is this a dtype" guessing logic.  And then, we could potentially avoid converting to an array fully.
OTOH, the ufunc will convert to an array anyway, so... You can use the new `_array_converter` helper, it may be convenient here, but probably doens't really change anything.
