### ISSUE TITLE
Six outdated wheels hanging out in nightly repo.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#27645]
They are for `musllinux_1_1` and `macosx_10_9` and are no longer built. Someone with permissions might want to delete them.

**Comment by mattip** [comment]
Do you mean [on scientific-python-nightly-wheels](https://anaconda.org/scientific-python-nightly-wheels/numpy/files?page=2)? Maybe @seberg has access?

**Comment by andyfaff** [comment]
I have permission for scipy, but not numpy. I think @rgommers sorted permissions for me

**Comment by rgommers** [comment]
I have access (but not admin rights) - deleted now.
