### ISSUE TITLE
BUG: TypeError: std() got an unexpected keyword argument 'mean'

### ISSUE THREAD

**Issue by rteqs** [numpy/numpy#27677]
### Describe the issue:

The following snippet doesn't work for 1.26.4. The docs says it was introdcued in 1.26.0

<img width="577" alt="image" src="https://github.com/user-attachments/assets/0633f40c-8ac3-4471-83eb-0c091cc2d701">

https://numpy.org/doc/stable/reference/generated/numpy.std.html

### Reproduce the code example:

```python
import numpy as np

np.std([1,2,3,4], mean=2.5)
```

### Error message:

```shell
TypeError: std() got an unexpected keyword argument 'mean'
```

### Python and NumPy Versions:

Failing 
1.26.4
3.11.10 | packaged by conda-forge | (main, Sep 10 2024, 11:01:28) [GCC 13.3.0]

Working
```
2.0.2
3.11.10 | packaged by conda-forge | (main, Sep 10 2024, 11:01:28) [GCC 13.3.0]
```

**Comment by mattip** [comment]
That is a typo, it was added for 2.0. Care to make a PR to change it?

**Comment by rteqs** [comment]
yup
