### ISSUE TITLE
Backward Comaptibility of Numpy Argsort

### ISSUE THREAD

**Issue by JayMan91** [numpy/numpy#27725]
### Proposed new feature or change:

`numpy.argsort` has been [changed](https://numpy.org/doc/2.0/release/2.0.0-notes.html#minor-changes-in-behavior-of-sorting-functions)  in 2.0.0 compared to 1.26.x. 
Due to that,  there are some differences in results when an array contains repeated values.

For instance, 
```
import numpy as np 
array = [92, 2, 4, 2, 4, 2, 3, 3, 1, 2, 3, 3 , 2, 4,  1, 4, 1, 2, 4, 20]
indices = np.argsort(array)
print ("Sorted Indices:")
print (indices)

print ('Sorted array')
print([array[i] for i in indices])
``` 
if I run this code block in v1.26.2, the value of the array named indices is:
```
[ 8 14 16 12  5  9  3  1 17  6  7 10 11 18  2 13 15  4 19  0]
```
whereas in v2.0.0,the value of the array named indices is:
```
[14  8 16  1  9 12  5  3 17 10 11  6  7  4 13  2 18 15 19  0]
```
In both cases the sorted array is
```
[1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 20, 92]
```
So, both are correct.

However, I've used v1.26.2 to generate and save the data and now it's not compatible to v2.0.0.

Is there a way to replicate the results of v1.26.2 in v2.0.0?
Many thanks!

**Comment by jakevdp** [comment]
I'm not sure what changed in the quicksort implementation between the two versions, but you could pass `kind='stable'` and then you'd be sure to get the same results in both package versions.

**Comment by JayMan91** [comment]
Thanks, that's good to know. I checked that `kind='stable'` indeed make both versions output same results.

However, I was looking for something different. I am curious to know if I do not use `kind='stable'` in v1.26.2 (which is the the default), what options I can add so that  v2.0.0 give same result as v1.26.2 (with   `kind=None`).

**Comment by jakevdp** [comment]
I don't know of any way to reproduce the exact behavior of non-stable sorts from NumPy 1.26 when using NumPy 2.X.

**Comment by JayMan91** [comment]
I see. Thanks. I think I should indeed regenerate the data with `kind='stable'`.  

From this perspective, is it possible to make  `kind='stable'` the default argument in sort algorithms?

**Comment by charris** [comment]
> is it possible to make kind='stable' the default argument

It is possible, but unlikely. The default was chosen to be the sort that is usually the fastest, which historically was quicksort and its descendants. That said, with modern hardware and compilers, mergesort and its descendants can sometimes be faster, but use more memory.
