### ISSUE TITLE
BUG: The mask value may be removed in numpy.ma.core.MaskedArray

### ISSUE THREAD

**Issue by A-nkt** [numpy/numpy#27726]
### Describe the issue:

If you overwrite an array defined with numpy.ma.core.MaskedArray with numpy.ndarray, the mask will be removed.
However, this behavior only occurs when the dimensions are different; it does not occur if the dimensions are the same.

### Reproduce the code example:

```python
import numpy as np


a3 = np.array([[-9999, 8, -9999], [1, 100, 2], [-9999, -9999, 2]])
a3 = np.ma.masked_where(a3 == -9999, a3) # a3 is masked
b3 = np.array([[-9999, 8, -9999], [1, 100, 2], [-9999, -9999, 2]])
b3 = np.ma.masked_where(b3 == -9999, b3) # b3 is masked

x3 = np.zeros(((2, 3, 3)))
x3[0, :, :] = a3
x3[1, :, :] = b3
print(x3) # x3 is not masked. x3 contains -9999.
```

### Python and NumPy Versions:

3.10.6 (main, Aug 10 2022, 12:36:34) [Clang 13.1.6 (clang-1316.0.21.2.5)]

### Runtime Environment:

[{'numpy_version': '2.1.3',
  'python': '3.10.6 (main, Aug 10 2022, 12:36:34) [Clang 13.1.6 '
            '(clang-1316.0.21.2.5)]',
  'uname': uname_result(system='Darwin', node='MacBookAir-of-Ny.local', release='23.6.0', version='Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]

**Comment by eendebakpt** [comment]
@A-nkt In your example the `a3` array is a regular array (not masked). When assigning elements to it it remains a normal array. This is the behavior I would expect.

Could you try to describe your issue in a bit more detail?

**Comment by eendebakpt** [comment]
@A-nkt I made a mistake in my response, I actually meant `x3`.

On the line `x3 = np.zeros(((2, 3, 3)))` you define `x3` to be a regular array (e.g. not masked). Operations on that object cannot change its type (this is not possible in python), so in particular the statement `x3[0, :, :]` can not change the type of `x3` into a masked array.


You could modify the code to replace `x3` with a masked array (with the same shape, type etc.):
```
import numpy as np

a3 = np.array([[-9999, 8, -9999], [1, 100, 2], [-9999, -9999, 2]])
a3 = np.ma.masked_where(a3 == -9999, a3) # a3 is masked
b3 = np.array([[-9999, 8, -9999], [1, 100, 2], [-9999, -9999, 2]])
b3 = np.ma.masked_where(b3 == -9999, b3) # b3 is masked

x3 = np.zeros(((2, 3, 3)))
x3 = np.ma.asarray(x3)
x3[0, :, :] = a3
x3[1, :, :] = b3
print(x3) # x3 is now masked
```

Technically it would be possible for `x3[0, :, :] = a3` to emit a warning message, but I personally do not think this is desirable.

**Comment by A-nkt** [comment]
thank you for your reply. I could understood :)
