### ISSUE TITLE
DOC: clarification in absolute beginners tutorial

### ISSUE THREAD

**Issue by AidanHattingh** [numpy/numpy#27733]
### Issue with current documentation:
From https://numpy.org/devdocs/user/absolute_beginners.html#how-to-create-a-basic-array:

How to create an array from existing data
This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

You can easily create a new array from a section of an existing array.

Let’s say you have this array:

a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

You can create a new array from a section of your array any time by specifying where you want to slice your array.

arr1 = a[3:8]
arr1
array([4, 5, 6, 7, 8])

**Here, you grabbed a section of your array from index position 3 through index position 8.**

### Idea or request for content:

It should clearly state that:

Here, you grabbed a section of your array from index position 3 through index position 8 BUT NOT INCLUDING POSITION 8

NOTE: Value 8 is at index position 7

**Comment by melissawm** [comment]
Hi @AidanHattingh - would you like to submit a PR for this?

The file that needs to be edited for this change is https://github.com/numpy/numpy/blob/main/doc/source/user/absolute_beginners.rst

After doing your changes please try to build the documentation locally to see if it renders correctly and submit your PR. Also check out our [contributor guide](https://numpy.org/devdocs/dev/index.html) and [instructions on how to build the documentation](https://numpy.org/devdocs/dev/howto_build_docs.html). Feel free to ping me if you have any questions!

**Comment by AidanHattingh** [comment]
Hi @melissawm, 

No I do not have the time to contribute. I was just flagging the issue

**Comment by StanFromIreland** [comment]
Hi @melissawm and @AidanHattingh 

I have submitted the changes in #27788 .

**Comment by melissawm** [comment]
Closed by #27788
