### ISSUE TITLE
Unexpected error: module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by marisolcontreras1** [numpy/numpy#27759]
### Steps to reproduce:

./SPrediXcan.py \
> --model_db_path data/DGN-WB_0.5.db \
> --covariance data/covariance.DGN-WB_0.5.txt.gz \
> --gwas_folder data/GWAS \
> --gwas_file_pattern ".*gz" \
> --snp_column SNP \
> --effect_allele_column A1 \
> --non_effect_allele_column A2 \
> --beta_column BETA \
> --pvalue_column P \
> --output_file results/test.csv

### Error message:

```shell
FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  s[c] = numpy.array(pandas.to_numeric(s[c], errors='ignore'))
INFO - Processing input gwas
FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if a.dtype == numpy.object:
INFO - Unexpected error: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by jakevdp** [comment]
Hi – I think the error message is pretty clear here:
```
INFO - Unexpected error: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
Can you let us know what about this is unclear?

**Comment by marisolcontreras1** [comment]
Hi - I am interested in the code to be able to fix the issue. I am unsure how to use 'object' instead of np.object command. May I please receive more support? Thank you
This was my attempt below:
```
(my-env) [username@pdev1 software]$ np.object = object 
-bash: np.object: command not found
```

**Comment by jakevdp** [comment]
`object` is not a command – it's a python symbol within the code you are executing.

**Comment by marisolcontreras1** [comment]
I'm new to both Python and GitHub, and as I explore the project, I'm finding myself unsure about which file serves as the source file for the relevant updates. 

I have a specific question regarding the update from np.object to object. As I understand it, this change is important for ensuring compatibility with newer versions of Numpy. May it please be possible to provide an update to Numpy to reflect this change so that users can easily use the most current version of Numpy without issues?

I’m a bit concerned about using older versions of Numpy, as I assume they may not have the latest efficiency improvements or bug fixes. Could you let me know if this update is coming soon or if there’s any guidance on how to proceed?

Thank you so much for your time and assistance. I really appreciate your help as I continue to learn and work with these tools.

**Comment by WarrenWeckesser** [comment]
It is not the NumPy source code that needs to be updated.  The software that you are using (`SPrediXcan.py`) is not compatible with the version of NumPy that you have installed. If you want to help that project (which appears to be https://github.com/hakyimlab/MetaXcan), you can open up an issue there and work on updating their code to be compatible with the latest version of NumPy.

The specific error that you are getting appears to be the result of this code:

https://github.com/hakyimlab/MetaXcan/blob/76a11b856f3cbab0b866033d518c201374a5594b/software/metax/gwas/GWAS.py#L186

It is likely that more changes to the MetaXcan software will be needed beyond just that one line.

If you just want to run the program, you'll have follow @jakevdp's suggestion and install numpy 1.26.
