### ISSUE TITLE
BUG: np.pi returns wrong number

### ISSUE THREAD

**Issue by ElmWer** [numpy/numpy#27762]
### Describe the issue:

np.pi should be 3.14 and not 15625

### Reproduce the code example:

```python
import numpy as np
np.pi

result: 15625

np.pi??
Type:        int
String form: 15625
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating-point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
```

### Error message:

```shell
no error message, just the wrong number
```

### Python and NumPy Versions:

2.1.2
3.13.0 | packaged by conda-forge | (main, Oct  8 2024, 19:54:55) [MSC v.1941 64 bit (AMD64)]

### Runtime Environment:

[{'numpy_version': '2.1.2',
  'python': '3.13.0 | packaged by conda-forge | (main, Oct  8 2024, 19:54:55) '
            '[MSC v.1941 64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='xxx', release='11', version='10.0.22631', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'filepath': 'C:\\Users\\xxx\\apps\\miniconda3\\envs\\work\\Library\\bin\\libomp.dll',
  'internal_api': 'openmp',
  'num_threads': 8,
  'prefix': 'libomp',
  'user_api': 'openmp',
  'version': None},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\xxx\\apps\\miniconda3\\envs\\work\\Library\\bin\\libblas.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.28'}]

**Comment by ElmWer** [comment]
update numpy to verion 2.1.3 resolved the issue

**Comment by seberg** [comment]
I don't know what you saw there, but this was certainly never a NumPy bug.
