### ISSUE TITLE
BUG: ``gentype.__array_wrap__`` doesn't make much sense

### ISSUE THREAD

**Issue by AnonymousPlayer2000** [numpy/numpy#27783]
### Describe the issue:

As mentioned in the document, `diagflat ` should return a two-dimensional array. But it does not return a two-dimensional array when the input is the `var`'s output.

### Reproduce the code example:

```python
import numpy as np
print(np.diagflat(np.var(np.array([1,2,3]))).shape) # output is ()
```

### Python and NumPy Versions:

1.26.4
3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:27:36) [GCC 11.2.0]

### Runtime Environment:

[{'numpy_version': '1.26.4',
  'python': '3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, '
            '13:27:36) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', release='6.8.0-48-generic', version='#48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Prescott',
  'filepath': '/path/lib/python3.12/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 24,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]

### Context for the issue:

The result breaks the document spec.

**Comment by AnonymousPlayer2000** [comment]
I test the code snippet in NumPy 2.1.0. The `diaflat` behaves normally:
```shell
>>> import numpy as np
>>> print(np.diagflat(np.var(np.array([1,2,3]))).shape)
(1, 1)
>>> print(np.diagflat(np.var(np.array([1,2,3]))))
[[0.66666667]]
```

**Comment by seberg** [comment]
The underlying issue is:
```
>>> np.float64(4).__array_wrap__(np.array([[1, 4]]))
np.int64(1)
```
which makes no sense at all of course.

**Comment by seberg** [comment]
Note that the PR was about the underlying issue here.  We will not be backporting things to the old NumPy versions.  You will have to update to avoid the issue there.

**Comment by AnonymousPlayer2000** [comment]
Thank you!
