### ISSUE TITLE
TASK: Proper names for the NumPy 2.2.0 release

### ISSUE THREAD

**Issue by charris** [numpy/numpy#27799]
The NumPy 2.2.0 release will be coming out in a couple of weeks. If your name is in the list below, please
comment here with the name and email address you would like to use so that you get proper credit as one of the contributors.

- [x] @nocoding03 (Austin)
- [ ] @geetaakshata (Dreamge)
- [x] @Shaurya19
- [x] @StanFromIreland (Stan U.) 
- [x] @zvijayakumar (Vijayakumar Z @ 'Z)
- [ ] @bersbersbers
- [x] @fengluoqiuwu (fengluo, 枫落秋舞)
- [ ] @hutauf
- [x] @ScoobyP (ishanp)
- [x] @kp2pml30
- [ ] @musvaage
- [ ] @nullSoup
- [x] @vnherdeiro

**Comment by nocoding03** [comment]
name:Austin Ran
email:504977925@qq.com

**Comment by kp2pml30** [comment]
Name: Kira Prokopenko 
Email: kp2pml30@gmail.com

**Comment by zvijayakumar** [comment]
Name: Vijayakumar Z
email: zvijayakumar@gmail.com

**Comment by ScoobyP** [comment]
Name: Ishan Purekar
Email: ***@***.***

16:39 वर बुध, 20, नोव्हें 2024 Kira ***@***.***> रोजी लिहीले:

**Comment by musvaage** [comment]
doc/source/release/\<version\>-notes.rst

no interest on my end with being credited

the only accessible information provided if \<version\>-notes.rst files are autogenerated

is at the top of the single patch submitted

From: username \<username@users.noreply.github.com\>
