### ISSUE TITLE
DOC: numpy.random.Generator.choice needs to better document return types, e.g., returns int even when the input integer "a" is of type np.int64

### ISSUE THREAD

**Issue by RaghuSpaceRajan** [numpy/numpy#27801]
### Issue with current documentation:

The docs [here](https://numpy.org/doc/2.1/reference/random/generated/numpy.random.Generator.choice.html) say that:

> If an int, the random sample is generated from np.arange(a).

I expected an `np.int64` but it returns an `int`. `np.arange(a)` by default returns an array of dtype `np.int64`, so the sample is not directly from there. 

Further, I also expected an np.int64 to be returned when I run:
`np.random.default_rng(100).choice(np.int64(5))`, however I get `int`. 

In principle, I feel this could also be a _normal_ bug, but given that `np.random.default_rng(100).integers(5)` returns an `np.int64` with either type of scalar input and adding `size=()`, as in `np.random.default_rng(100).choice(np.int64(5),size=())` can be used as a workaround to get an `np.int64` as the return type when using `choice()`, I am guessing this behaviour will not be changed but I feel that this should at least be documented because it led to confusion on my end when I was debugging something. 

For reference, here are different ablations I ran to understand the current behaviour:
```
type(np.random.default_rng(100).choice(np.int64(5)))
<class 'int'>
type(np.random.default_rng(100).choice(np.int64(5),1))
<class 'numpy.ndarray'>
np.random.default_rng(100).choice(np.int64(5),1).dtype
dtype('int64')
np.random.default_rng(100).integers(5).dtype
dtype('int64')
```

Additionally, the "Returns" part of the docs says:
> samples : single item or ndarray

I believe the "single item" should be replaced with "Python int". 

I could open a pull request to change the docs or file this as a bug if you think the behaviour should be changed. Please let me know.

**Comment by rkern** [comment]
The `Returns` part is correct and should not be replaced (though it possibly could be supplemented). The typical input to `choice()` is an array of any dtype, and what we're documenting there is that it returns a single item from that array (or an array of such if `size` is given).

The only case to consider is that when the input is an integer, we lie a little when we say that it is as if you had passed in `np.arange(n)`; that was only meant to talk about the possible values that we return, not the finicky details of exactly which flavor of integer type we return. We sample the index integer in C and then just return that, and Cython's standard handling of converting C integers to Python is to return an `int` and not an `np.int64` as if we had created a full `np.arange(n)` and pulled the value out of that. Actually creating that intermediate would be wasteful and unnecessary.

I'm not too fussed about this, but if you like, you can add (not replace anything) `int` to the `Returns` section and talk about that case in the text.

**Comment by RaghuSpaceRajan** [comment]
> The Returns part is correct and should not be replaced (though it possibly could be supplemented).

Indeed, sorry about the oversight.

> Actually creating that intermediate would be wasteful and unnecessary.

I see. I'm curious now about why `choice()` and `integers()` differ in their default return types for the case when I pass in an integer to either of them. For me the default of `int` only in the case of a single integer being with `choice()` passed turned out to be magnified into a bigger issue because of type checking going on in some other library code deep down in the call stack leading to unexpected behaviour on the outside (both `choice()` and `integers()` return `np.int64` by default in the other cases).

**Comment by rkern** [comment]
> I'm curious now about why `choice()` and `integers()` differ in their default return types for the case when I pass in an integer to either of them.

Mostly just minor details about the implementations leaking through. We were not very careful about these minor details of type flavors. Type-checking was not popular at the time, and these minor differences had no meaningful effect on anyone until they were.

**Comment by RaghuSpaceRajan** [comment]
Thanks for the info! I created a PR here: https://github.com/numpy/numpy/pull/27806.

**Comment by seberg** [comment]
PR is merged, closing.
