### ISSUE TITLE
BUG: concatenate does not work as expected.

### ISSUE THREAD

**Issue by laniakea** [numpy/numpy#27818]
### Describe the issue:

The concatenate does not work as expected. When concatenating an empty array, the expected behaviour should return an empty array.
This is significant! I'm writing a code the groups eigen values and then loop through each group. There are times that all eigenvalues have similar magnitudes and there is only one group and the concatenating the rest of the groups returns an error.

### Reproduce the code example:

```python
import numpy as np
x = np.array([])
y = np.concatenate(x)
```

### Error message:

```shell
ValueError: need at least one array to concatenate
```

### Python and NumPy Versions:

3.10

**Comment by rossbar** [comment]
IMO the docs are clear on this topic, so I'm not sure there's much to be done here. I will close this as "answered" - thanks @WarrenWeckesser !
