### ISSUE TITLE
ENH: Compute Jacobian matrices

### ISSUE THREAD

**Issue by b-hedden** [numpy/numpy#27821]
### Proposed new feature or change:

NumPy currently lacks a built-in function for calculating Jacobian matrices. Although it is possible to find a Jacobian matrix by applying `np.gradient` to each component separately, or by using finite differences manually. a built-in function such as `np.jacobian` would improve usability. It seems that this addition would fit within the scope of NumPy. This could become quite complicated, as the user would need to define some function f(x) themselves for computing the Jacobian, but this feels like a worthwhile feature for NumPy, as other similar python libraries have built-in support for this.

**Comment by izzzabellay** [comment]
This sounds like a good idea. 
If no one else is working on it right now, I can try to develop a built-in function for Jacobian matrix calculation and will make a pull request before Dec.10, as a part of my school assignment.

**Comment by mattip** [comment]
Before jumping into an implementation, we need to discuss whether NumPy is a good place for this, and if so what the interface looks like. Typically such a request will start with a discussion on the mailing list, and in recent years engaging with the [data api standard](https://data-apis.org/array-api/latest/) to standardize the interface across all data processing packages.

**Comment by andyfaff** [comment]
It's not clear what kind of Jacobian that's being proposed. That of a numeric array, or that of a function. The latter is already available in scipy.

**Comment by seberg** [comment]
Please bring it up elsewhere on the mailing list if you want to pursue it.  Without any maintainer or wider community support, I think my, and others, decision is that SciPy already has the function, and it isn't that core that NumPy must have it:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.approx_fprime.html

If anyone disagrees feel free to comment/reopen.  It would at least need an argument why duplicating from scipy makes sense here.
