### ISSUE TITLE
BUG: Unexpected behavior when using np.power on a large array in a loop.

### ISSUE THREAD

**Issue by Ebanflo42** [numpy/numpy#27833]
### Describe the issue:

The objective is to compute a grid of values for reproducing a plot like this: [modular discriminant](https://en.wikipedia.org/wiki/Weierstrass_elliptic_function#/media/File:Discriminant_real_part.jpeg).

While working on this I came across some really strange behavior which I cannot explain, since all operations used are supposed to be working elementwise. The code as-is throws dozens of runtime warnings, as shown below. On its own that shouldn't actually be a problem because the evaluation of `discriminant` on values of the point grid having absolute value greater than 1.

However, the commented codeuses joblib parallelism to call the same function on scalar values, and it actually leads to a correct plot, with drastically different values from the pure numpy version.

Am I missing something here? It makes sense that inputs to `discriminant` with absolute value greater than 1 should lead to NaNs, but that shouldn't affect the rest of the values at all.

### Reproduce the code example:

```python
import numpy as np
import matplotlib.pyplot as plt
from joblib import Parallel, delayed


def discriminant(q):
    result = q
    for n in range(1, 64):
        result *= (1 - q**n)**24
    return result


def clamp(r):
    r = np.minimum(r, 1e12)
    return np.where(r < 0, 0, np.log1p(np.abs(r)))


if __name__ == "__main__":
    fig = plt.figure()
    ax = fig.add_subplot()
    ax.set_aspect('equal')
    linspace = np.linspace(-1, 1, 1080)
    linspace = np.tile(linspace[None], (1080, 1))
    mesh = linspace + 1j*linspace.T

    #vals = np.array(Parallel(n_jobs=12)(
    #    delayed(lambda x: 0 if np.abs(x) > 1 else discriminant(x))(x)
    #    for x in mesh.flatten())).reshape((1080, 1080))

    vals = np.where(np.abs(mesh) > 1, 0, discriminant(mesh))

    ax.pcolormesh(clamp(vals.real), cmap='turbo')
    ax.set_xticks([])
    ax.set_yticks([])
    plt.show()
```

### Error message:

```shell
/home/medusa/Projects/tattoos/eistenstein.py:66: RuntimeWarning: invalid value encountered in multiply
  result *= (1 - q**n)**24
```

### Python and NumPy Versions:

Python 3.9.7
NumPy 1.26.4

### Runtime Environment:

Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7b0e86cd9f70>
Traceback (most recent call last):
  File "/home/medusa/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/medusa/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/home/medusa/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/home/medusa/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
[{'numpy_version': '1.26.4',
  'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]',
  'uname': uname_result(system='Linux', node='haraway', release='6.8.0-49-generic', version='#49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]

### Context for the issue:

I think its really strange behavior and would like to know if there is a simple explanation.

**Comment by mattip** [comment]
I didn't run the code, but this jumped out at me. Was your intent to modify `q` (which is `mesh`) in-place?

```diff
def discriminant(q):
-    result = q
+    result = q.copy()
    for n in range(1, 64):
        result *= (1 - q**n)**24
    return result

```

**Comment by Ebanflo42** [comment]
Ah I see the problem, so `result` is just a pointer without the `copy`
