### ISSUE TITLE
DOC: numpy imported twice in default_rng example docs

### ISSUE THREAD

**Issue by jonpovey** [numpy/numpy#27834]
https://github.com/numpy/numpy/blob/b1e6ccd14b173b922f5d6a11bb252f4141dc42cd/doc/source/reference/random/index.rst?plain=1#L66C1-L68C25

Noticed this. A minor doc bug? Or some reason to import again after secrets?

**Comment by mattip** [comment]
No good reason. That came in as part of a PR to add `import numpy as np` in all the examples, and slipped under the review process.
