### ISSUE TITLE
DOC: Incorrect "New in version" for mean argument of numpy.std

### ISSUE THREAD

**Issue by mcleantom** [numpy/numpy#27838]
### Issue with current documentation:

numpy.std says that the mean argument is new from 1.26, but it is not available in 1.26. It should say new from 2.0.

https://numpy.org/doc/stable/reference/generated/numpy.std.html

Vs the 1.26 docs:

https://numpy.org/doc/1.26/reference/generated/numpy.std.html

**Comment by mcleantom** [comment]
It is wrong for the 2.0 docs and the 2.1 docs

**Comment by seberg** [comment]
This was fixed.
