### ISSUE TITLE
CircleCI builds are failing on `main`

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#27849]
Probably related to https://github.com/numpy/numpy/pull/27826

See e.g. https://app.circleci.com/pipelines/github/numpy/numpy/29822/workflows/fda81be6-eb4a-4fba-beb1-14472f0638ec/jobs/43843?invite=true#step-106-68030_58

**Comment by mattip** [comment]
There is something about CircleCI and merge-from-main before building that means you need to  rebase/merge main to get the fix in #27826. I think because the fix touches the build configuration itself and not the numpy code, and the merge is done as part of the build process.
