### ISSUE TITLE
BUG: np.array().max() is not working.

### ISSUE THREAD

**Issue by MagnusCaspersen184** [numpy/numpy#27857]
### Describe the issue:

Calling the max method on an `numpy.ndarray` fails with type error:
`TypeError: int() argument must be a string, a bytes-like object or a real number, not '_NoValueType'`

### Reproduce the code example:

```python
import numpy as np

# This fails
np.array([0, 3]).max()

# This works
np.max(np.array([0, 3]))
```

### Error message:

```shell
Traceback (most recent call last):
  File "\venv\Lib\site-packages\numpy\_core\_methods.py", line 45, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not '_NoValueType'
```

### Python and NumPy Versions:

```
print(np.__version__)
2.1.3
print(sys.version)
3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
```

### Context for the issue:

This issues affects packages that use numpy (e.g. [pandas](https://github.com/pandas-dev/pandas/issues/60421)).

**Comment by charris** [comment]
I don't see this with current main on linux intel.

**Comment by seberg** [comment]
The error is impossible in a proper NumPy install (unless very strange things are happening, but last time I saw those, it was bad cython/Python interaction a long time ago).

The only thing that makes sense to me is that the installation is bad.  The C code being used is somehow older than the Python code.

Reinstall `numpy`, if it doesn't work, delete `numpy` first and try again.  Make very sure you deleted everything and also check `$PYTHONPATH` (multiple times, in-place build left overs, etc.).

---

Closing, you can try asking, but I think the error is clear about you having an inconsistent/bad NumPy install.
