### ISSUE TITLE
Dropping Python 3.10 support.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#27861]
We are scheduled to drop Python 3.10 support in NumPy 2.3. I will make a PR to get started on that, but
have noticed a few issues I have questions about:

@ngoldbaum `numpy/_core/src/multiarray/stringdtype/static_string.c` has a 3.10 workaround.
@seberg `numpy/_core/include/numpy/numpyconfig.h`  NPY_FEATURE_VERSION needs update.
@r-devulap `linux_simd.yml` could probably use an update/rework.
@mattip can PyPy support 3.11 yet?

**Comment by ngoldbaum** [comment]
I think the comment in `static_string.C` is referring to the note about Python3.9 here: https://docs.python.org/3.12/c-api/arg.html#strings-and-buffers

But looking [at the same docs for 3.13](https://docs.python.org/3/c-api/arg.html#strings-and-buffers), it looks like I might have misunderstood, and we can actually remove all the `Py_SSIZE_T_CLEAN` macros after we remove support for Python 3.12.

**Comment by charris** [comment]
@ngoldbaum Feel free to push a comment update to #27862.

**Comment by r-devulap** [comment]
> [rdevulap](https://github.com/r-devulap) linux_simd.yml could probably use an update/rework.

Is 3.12 the new recommended version?

**Comment by r-devulap** [comment]
Never mind, I just saw your PR :)
