### ISSUE TITLE
Failed to install NumPy version '1.26.5' using 'pip install numpy==1.26.5'

### ISSUE THREAD

**Issue by hwhsu1231** [numpy/numpy#27873]
### Steps to reproduce:

Run the following commands in order:

```bash
conda create --prefix ./.venv --yes
conda activate ./.venv
conda install python=3.10 --yes
pip install numpy==1.26.5
```

See the full log of the above steps:

[log-failed-to-pip-install-numpy-1.26.5.txt](https://github.com/user-attachments/files/17949809/log-failed-to-pip-install-numpy-1.26.5.txt)

### Error message:

```shell
ERROR: Could not find a version that satisfies the requirement numpy==1.26.5 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.25.0, 1.25.1, 1.25.2, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc1)
ERROR: No matching distribution found for numpy==1.26.5
```

### Additional information:

There is already a `v1.26.5` tag from 7 months ago (as of today, 2024-11-28).

![Screenshot_20241128_230605](https://github.com/user-attachments/assets/8c5364b2-2f76-485a-9c81-3c3abde39e18)

However, there is no `1.26.5` wheel file in the https://pypi.org/simple/numpy

![Screenshot_20241128_231034](https://github.com/user-attachments/assets/b427db8e-76a9-4c19-ba9c-ba84eb50c47f)

**Comment by andyfaff** [comment]
The canonical location for releases for pip is PyPI (the [GH releases page](https://github.com/numpy/numpy/releases?page=2 will be canonical as well). There is no 1.26.5 entry at either of those locations --> there is no 1.26.5 release.

That there is a 1.26.5 tag on GH is unfortunate, but it's not a release.
