### ISSUE TITLE
BUG: np.ma.min/max: error with `uint` dtypes and `axis is not None`

### ISSUE THREAD

**Issue by mdhaber** [numpy/numpy#27885]
### Describe the issue:

`np.ma.min` and `np.ma.max` raise a `TypeError` when the input array is >1 D, has any unsigned integer dtype, and `axis is not None`.

---

I'm also finding other issues, like:
```python3
np.ma.min(np.ma.masked_array([1, 2], mask=True)).dtype  # dtype('float64') instead of integer
np.ma.all(np.ma.masked_array([1], True)).dtype  # dtype('float64') instead of boolean
np.ma.argmin(np.ma.masked_array([1, 2, 3], mask=True))  # 0 instead of something masked
```
The first two are really the same - `np.ma.MaskedConstant` always has `dtype` `float64`.
The third is that `np.ma.argmin` and `np.ma.argmax` return regular `ndarray`s or scalars, not masked arrays.
Is it worth reporting these all separately? Some of them get a bit into the weeds.

### Reproduce the code example:

```python
import numpy as np
shape = (1, 2)  # same with any shape with >1 dimension
dtype = np.uint16  # same with all uint types
x = np.ones(shape, dtype=dtype)  
mx = np.ma.masked_array(x, mask=False)
np.ma.max(mx, axis=0)  # same with min
```

### Error message:

```shell
TypeError: Cannot cast scalar from dtype('int64') to dtype('uint16') according to the rule 'same_kind'
```

### Python and NumPy Versions:

2.1.1
3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:24:51) [MSC v.1940 64 bit (AMD64)]

### Runtime Environment:

[{'numpy_version': '2.1.1',
  'python': '3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:24:51) '
            '[MSC v.1940 64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='DESKTOP-A5QV7K1', release='11', version='10.0.22631', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'filepath': 'C:\\Users\\matth\\miniforge3\\envs\\scipy-dev\\Library\\bin\\libomp.dll',
  'internal_api': 'openmp',
  'num_threads': 16,
  'prefix': 'libomp',
  'user_api': 'openmp',
  'version': None},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\matth\\miniforge3\\envs\\scipy-dev\\Library\\bin\\libblas.dll',
  'internal_api': 'openblas',
  'num_threads': 16,
  'prefix': 'libblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]

### Context for the issue:

I am working on [mdhaber/marray](https://github.com/mdhaber/marray) and ran across this issue during testing.

**Comment by seberg** [comment]
Fixed on main and backported, thanks.
