### ISSUE TITLE
BUG: logical_or operator | does not work as expected for ndarray view with single element

### ISSUE THREAD

**Issue by jackmedda** [numpy/numpy#27892]
### Describe the issue:

The logical_or operator seems not to work when the comparison is made between two views with a single element each. If the logical_or is used directly, the output is correct as expected.

In my case, I have to retrieve the middle part of an array, whose length can be greater or equal than 1.
When the length is 1, the logical_or operator does not work as expected, but the corresponding function does.

### Reproduce the code example:

```python
import numpy as np

a = np.array([1,2,3])
b = np.array([1,2,3])

res_operator = a[1:-1] > 2 | a[1:-1] <= 2  # array([False])
res_function = np.logical_or(a[1:-1] > 2, a[1:-1] <= 2)  # array([ True])

# I noticed that if the boolean array are stored in variables, the problem does not occur
first_check = a[1:-1] > 2
second_check = a[1:-1] <= 2

res_operator = first_check | second_check  # array([ True])
res_function = np.logical_or(first_check, second_check)  # array([ True])
```

### Python and NumPy Versions:

2.1.3
3.11.10 (main, Sep  7 2024, 18:35:42) [GCC 9.4.0]

**Comment by seberg** [comment]
You are fooled by operator precedence.  The bitwise `|` binds stronger than the comparison.

**Comment by jackmedda** [comment]
I feel like an idiot 😅 thank you

**Comment by seberg** [comment]
I guess it's easy to be fooled when you need to use bitwise operators for what is meant to be a logical one :).
