### ISSUE TITLE
DOC: no documentation for those who want to read numpy codes

### ISSUE THREAD

**Issue by mahdic200** [numpy/numpy#27926]
### Describe the issue:

sorry for making an issue for bug report , there was no other option related to what I wanted to say . I want to read numpy codes and I want to learn , but there is a really complicated architecture and a lot of unordered code which makes it difficult and almost impossible for me . the philosophy of open-source is "everyone be able to read, write, change, and maintain" . but I just can't get it , what if a person wants to cooperate with you and comes in to this repository and can't understand what the hell have you done . I also took a look at contributors and saw the maintaining is almost exclusive and there is no documentation related to a developer who wants to see which part of your codes are the core, which are modules , how do you manage match operation, where to begin to understand . this is absolutely the opposite of open-source philosophy , and as a programmer, I can tell you there is no one who can come in to this repository and figure it out even a bit !! why ??? is there any hidden documentation ? come on , me and a friend of mine have checked this repo , and even my teacher , no one could understand what is this . no one has told what to do to figure this out .

I just want guidance and help , and please , I begin you , for swear of god don't tell me to go to reddit or discord or any other communities , they don't know anything about your codes , you , I mean you major contributors know what you're doing !!! so don't expect me to accept to go to another environment to ask this .

wish you luck and bests .

### Reproduce the code example:

```python
there is no code , please read the description
```

### Python and NumPy Versions:

no version , please read the description

**Comment by mattip** [comment]
The NumPy codebase is quite old and mature, it predates much of the CPython interpreter code. So it is bound to be confusing. With that, we are always open to improvements. We could expand the [Understanding the code & getting started](https://numpy.org/devdocs/dev/development_environment.html#understanding-the-code-getting-started) section of the documents with a high-level overview of how the different Python and C-API pieces fit together. Is that something you would be willing to help us with? Let's dive into your questions/complaints:

> what if a person wants to cooperate with you

We have various ways of getting in touch with the team. There are [meetings](https://scientific-python.org/calendars/) of the documentation, optimization, community, and triage groups, as well as a new contributor's hour. There is this issue tracker, and the github discussions. There is a [mailing list](https://mail.python.org/mailman3/lists/numpy-discussion.python.org/).

> there is no documentation related to a developer who wants to see which part of your codes are the core, which are modules

The best way to do this, like in any python library, is to dive in and check. For instance, this will show you the modules (again, this is generic to any library):
```
[x for x in dir(np) if isinstance(getattr(np, x), type(np.random))]
```

I am not sure what you mean by "core", but two of the core concepts in NumPy are `np.ndarray` and `np.ufunc`. You can read about them in the [documentation](https://numpy.org/doc/stable/reference/index.html).

> how do you manage match operation, where to begin to understand 

Can you be more specific? I am not sure NumPy is any different from other libraries that wrap C code. One complication is that we decorate the [Array API](https://data-apis.org/array-api/latest/) functions with a wrapper. So to find the C implementation for `dot`, you would look at `np.dot.__wrapped__`, which is `built-in function dot`. Like any library that uses the Python C-API, this means you need to find `"dot"`, which can be done with `git grep '"dot"'` (note the use of quotes), which will point to both `numpy/_core/src/multiarray/methods.c` and `numpy/_core/src/multiarray/multiarraymodule.c`. The former is the `np.ndarray` method, the latter is the `np` function.
https://github.com/numpy/numpy/blob/1b2b17afd6d63bd4520c7f4d13e8498479cfbc45/numpy/_core/src/multiarray/methods.c#L2939-L2941 https://github.com/numpy/numpy/blob/1b2b17afd6d63bd4520c7f4d13e8498479cfbc45/numpy/_core/src/multiarray/multiarraymodule.c#L4456-L4458

From there you need to look at the actual implementation of those functions in C. Crossing the python -> C debugging bridge is tricky, but again not specific to NumPy.

> this is absolutely the opposite of open-source philosophy...

I am not sure where you are going with the rest of this, so I will let others answer it.

**Comment by ngoldbaum** [comment]
Please feel free to ask questions as you have them, via any of the communication channels we have available for asking questions lime this.

I agree better developer docs would be great. Would you be interested in learning more about the numpy codebase to help us to write better docs?

I think you’ll find that most large C/C++ codebases don’t have great internal docs. That’s been my experience anyway.

**Comment by mahdic200** [comment]
Hey @mattip ,
Thanks for getting back to me! I just wanted to introduce myself again - I'm Mahdi, a Persian guy who's super into open-source projects. I'd love to contribute to Numpy as part of your team, and I think it would be an awesome opportunity for me to grow my skills. I'm currently a Computer Science student in Iran, but even though I'm almost done with my degree, I still feel like there's a lot I need to learn in terms of practical experience. I really look up to you and your team, and I believe that working with you would help me fill in the gaps in my knowledge. You guys have already done so much amazing work, and I'd love to be a part of it!

and about the "core" :
> I am not sure what you mean by "core", but two of the core concepts in NumPy are np.ndarray and np.ufunc. You can read about them in the [documentation](https://numpy.org/doc/stable/reference/index.html).

I mean the main modules and codes which is the beginning and kind of inner dependency which causes Numpy to work .

and about this 
> Can you be more specific? I am not sure NumPy is any different from other libraries that wrap C code.

Yes ! absolutely , I meant the math operations , the optimization of multiplying matrices and arrays , the art you've created which is not understandable for me .
I was looking for some loops which do the math operations but I couldn't find them as Numpy is so huge .

I wanted to share my thoughts with you. There's no doubt that Numpy is an incredible tool for professional developers, and your team's work on it is truly remarkable. However, I feel there's still a challenge that needs to be addressed. Let me give you a bit of background about myself - I started learning programming around 6 and a half years ago with C++, which was quite difficult for a beginner like me. though I changed my way to web development with laravel and nextjs . and even I have learned Rust . At the time, I didn't have access to good documentation or teachers, and I wasn't aware of the supportive community on GitHub, like the one you've built around Numpy. This lack of guidance led to a lot of frustration, and I believe this is an issue that others might face as well.
I want to help fix this within the Numpy community. My plan is to first gain a solid understanding of Numpy's codebase and then create a minimal but extremely helpful documentation for developers who want to understand the workings of Numpy and similar projects. My aim is to provide an excellent starting point for those who might be facing similar challenges to what I faced in my early days.
For this, I need some help getting started. Even the line of code you shared with me earlier was a big help, as I wasn't aware of that possibility. 
>```python
>[x for x in dir(np) if isinstance(getattr(np, x), type(np.random))]
>```

I'm a self-taught programmer who has spent countless hours searching and learning on my own, but I still feel that there's a lot more to learn. I'm not one to ask too many questions, but I believe having a mentor or a teacher would be incredibly beneficial for my growth.
I promise that once I have a solid understanding of Numpy's codebase, I will create the best documentation you've ever had specialized for developers . and explaining the details in important modules with describing the architecture of code . like what's going on _core folder . what's the different between core folder and _core . and If want to begin , where to begin to understand the code . or even making a graph for a better visualization. I have also worked on some small projects in Rust, which you can find on my GitHub account to get an idea of my skills.
Thank you so much for considering my thoughts and for your support. I look forward to the opportunity to contribute to the Numpy community.

**Comment by mahdic200** [comment]
> Please feel free to ask questions as you have them, via any of the communication channels we have available for asking questions like this.
> 
> I agree better developer docs would be great. Would you be interested in learning more about the numpy codebase to help us to write better docs?
> 
> I think you’ll find that most large C/C++ codebases don’t have great internal docs. That’s been my experience anyway.

I'm really glad you guys are so friendly . and I think we can fix this issue together . the good documentation is as important as structured code . cause If you don't have good documentation just you can figure out what you've done .

and I want to write an excellent documentation specially for developers .

**Comment by melissawm** [comment]
Hi @mahdic200 - as a volunteer project, code and documentation are built around the demands (and availability) of the community. As you may have noticed, there is interest in the documentation you are mentioning but quite frankly, it may be a large project.

For context, we did talk about this back in 2022. Here are a few links:

- [Docs team meeting notes](https://github.com/numpy/archive/blob/211c9817defc310cb10ee46edc5573f8c60ff4db/community_meetings/2022/community-2022-09-28.md?plain=1#L99)
- [Zones of contribution draft](https://hackmd.io/zm65_TjfSpi9DSSkE2o7Iw)

There is probably more context in the meeting notes from that period if you want to explore this idea. I would strongly recommend joining the Documentation Team meetings if you are interested in taking this on - please check our [Community Calendar](https://scientific-python.org/calendars/) for more info.

Cheers!

**Comment by mahdic200** [comment]
Hi @melissawm, thanks a lot for responding . actually I'm totally new to open-source community . is there any notes about the codebase itself ? the architecture of Numpy and how it works . it seems it's not public and in the code itself . could you please help me ? how do your contributors learn the codebase ? do you guide them ?

**Comment by mahdic200** [comment]
dear @melissawm I totally understand . but don't you think such a great repository needs start point for beginners ? .

I don't know where to begin . I'm confused and frustrated at this point . there are so many files and codes in this repository . and I can't even count them .

I do not expect personal mentorship , just need a startup guidance and I'll go the rest of this journey by myself .

**Comment by mahdic200** [comment]
why no one gives me a clue . I'm searching and asking for months . no one is giving me a clue . how am I suppose to understand something which doesn't have any good explanation ? . like you give me a clock and I have to figure it out by my own without any guide book . it frustrating and I'm really tired and sick . even when I want to help the community there is no good support . where did you guys start to learn these things ?.

**Comment by mahdic200** [comment]
dear @mattip has a video on youtube which indicates how exactly setup everything . I don't know why he didn't mention it . this is the [video's link](https://youtu.be/lHJqOE5j6xE?si=Za-qvCnLd03S3fH_) thanks Mr. @mattip again . my problems solved .
