### ISSUE TITLE
BUG: Different (int * np.int32) behaviour between Windows & Linux

### ISSUE THREAD

**Issue by jps-aldridge** [numpy/numpy#27946]
### Describe the issue:

If I multiply a Python integer by a numpy.int32 value, then on my Linux machine the result is a numpy.int64 and on Windows it's a numpy.int32. This results in platform specific integer overflow problems.

I have tried
   Linux(Ubuntu): Python 3.12.3/numpy 1.26.4
   Windows:  Python 3.12.3/numpy 1.26.4 and Python 3.13.1/numpy 2.2.0

### Reproduce the code example:

```python
import sys
import platform
import numpy as np

print(platform.uname())
print(sys.version)
print('numpy:', np.__version__)
print()

a=100
b=np.int32(10**8)
print(type(a*b), type(b*a))
```

### Error message:

```shell
On Linux no error message occurs
Windows gives "RuntimeWarning: overflow encountered in scalar multiply"

The full output from the code example for the three platforms tested is...

--------------------------------------------------------------------------------
uname_result(system='Linux', node='ardbeg', release='6.8.0-49-generic', version='#49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024', machine='x86_64')
3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
numpy: 1.26.4

<class 'numpy.int64'> <class 'numpy.int64'>
--------------------------------------------------------------------------------
uname_result(system='Windows', node='LAGAVULIN', release='10', version='10.0.19045', machine='AMD64')
3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
numpy: 1.26.4

D:\RaspberryPi\AoC2024\test.py:12: RuntimeWarning: overflow encountered in scalar multiply
  print(type(a*b), type(b*a))
<class 'numpy.int32'> <class 'numpy.int32'>
--------------------------------------------------------------------------------
D:\RaspberryPi\AoC2024>python test.py
uname_result(system='Windows', node='LAGAVULIN', release='10', version='10.0.19045', machine='AMD64')
3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]
numpy: 2.2.0

D:\RaspberryPi\AoC2024\test.py:12: RuntimeWarning: overflow encountered in scalar multiply
  print(type(a*b), type(b*a))
<class 'numpy.int32'> <class 'numpy.int32'>
--------------------------------------------------------------------------------
```

### Python and NumPy Versions:

--------------------------------------------------------------------------------
3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
numpy: 1.26.4

<class 'numpy.int64'> <class 'numpy.int64'>
--------------------------------------------------------------------------------
3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
numpy: 1.26.4

D:\RaspberryPi\AoC2024\test.py:12: RuntimeWarning: overflow encountered in scalar multiply
  print(type(a*b), type(b*a))
<class 'numpy.int32'> <class 'numpy.int32'>
--------------------------------------------------------------------------------
3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]
numpy: 2.2.0

D:\RaspberryPi\AoC2024\test.py:12: RuntimeWarning: overflow encountered in scalar multiply
  print(type(a*b), type(b*a))
<class 'numpy.int32'> <class 'numpy.int32'>
--------------------------------------------------------------------------------

### Runtime Environment:

--- Linux ---------------------------------------------------------------------------------
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.26.4',
  'python': '3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]',
  'uname': uname_result(system='Linux', node='ardbeg', release='6.8.0-49-generic', version='#49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3', 'SSE41', 'POPCNT', 'SSE42'],
                      'not_found': ['AVX',
                                    'F16C',
                                    'FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}}]

--- Windows ---------------------------------------------------------------------------------
[{'numpy_version': '2.2.0',
  'python': '3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='LAGAVULIN', release='10', version='10.0.19045', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C'],
                      'not_found': ['FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Sandybridge',
  'filepath': 'C:\\Users\\John\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy.libs\\libscipy_openblas64_-43e11ff0749b8cbe0a615c9cf6737e0e.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.28'}]

### Context for the issue:

This difference in behaviour affects the portability of my code

**Comment by seberg** [comment]
Thanks for the report, but this was changed in NumPy 2, see also https://numpy.org/neps/nep-0050-scalar-promotion.html

(The difference between linux and windows to use a different default int even though both are 64bit systems had good historical reasons but was *also* changed in NumPy 2.)

**Comment by jps-aldridge** [comment]
OK, but that doesn't explain why I see the overflow on Windows only when using numpy 1.26.4.
Perhaps this change had found its way into the Windows version early?

**Comment by mattip** [comment]
Just to be clear, this is all by design and not a bug:

version | OS| a | b (python int) | a * b | Notes
---|---|---|---|---|---
1.26.4 | Linux | `np.int32(100)` | 100 | `np.int64(10_000)` | python int -> int64, result is promoted
1.26.4 | Windows | `np.int32(100)` | 100 | `np.int32(10_000)` | python int -> int32, no promotion
2.0+ | Linux | `np.int32(100)` | 100 | `np.int32(10_000)` | no more promotion
2.0+ | Windows | `np.int32(100)` | 100 | `np.int32(10_000)` | like before, but for different reasons

You will get an overflow warning whenever the return type is int32. You did not try linux + numpy2, which __will__ warn

**Comment by jps-aldridge** [comment]
Ah, got it now. The bit I'd missed is that int numpy 2 the Python int was converted to a numpy default int (np.int32 on Windows, np.int64 on Linux) before doing the multiply. Thank you.
