### ISSUE TITLE
DOC:  Unclear Documentation for debugging 

### ISSUE THREAD

**Issue by sai-srinivasan-v** [numpy/numpy#27972]
### Issue with current documentation:

Setting up spin and debugger setup is unclear and tedious.
URL: https://numpy.org/devdocs/dev/development_environment.html

I have followed the instructions here and after multiple attempts, the spin build system does not seem to be working for me. 
Maybe the documentation is missing something?

**Comment by melissawm** [comment]
Can you clarify what you tried and what error you got?

**Comment by sai-srinivasan-v** [comment]
Hi, I started a conda env and i tried running the spin commands and i keep getting the following: 
clang: error: no such file or directory: 'test'
clang: error: no input files
spin: preprocessing failed gcc -std=gnu99 -E -x c "test" > "pan.pre"

**Comment by mattip** [comment]
In order to help you, we will need to know
- what operating system you are using (windows, macos, ubuntu, freebsd…)
- What platform you are using (x86, raspberry pi, macbook…)
- What commands you executed starting from `conda install`
- If you are building inside an ide or from a shell command line

Please use text rather than screenshots.

**Comment by sai-srinivasan-v** [comment]
I am on Macos Sequoia
I am on a m2 pro macbook
These are the commands that I've executed:
conda env create -f environment.yml    
conda activate numpy-dev   
conda info --envs    
pip install -e .   

After which i get:
Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      
      meson-python: error: Could not find the specified meson: "vendored-meson/meson/meson.py"
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I am building from a shel command line.

**Comment by mattip** [comment]
Does [`git submodule update --init`](https://numpy.org/doc/stable/building/index.html#building-from-source-for-numpy-development) help?

**Comment by sai-srinivasan-v** [comment]
Hi, it does not. I should notify that ive forked the repo and cloned it.  The error still persists.

**Comment by mattip** [comment]
What does `dir vendored-meson/meson/meson.py` show?

**Comment by mattip** [comment]
The [Build from source](https://numpy.org/devdocs/building/index.html#building-from-source-to-use-numpy) documentation recommends
```
pip install . --no-build-isolation
```

or for local development work
```
spin build
```
