### ISSUE TITLE
ENH: Expanding NumPy's Capabilities: Incorporating Linked Lists

### ISSUE THREAD

**Issue by prakkhar03** [numpy/numpy#27980]
### Proposed new feature or change:

I would like to suggest a feature enhancement to the NumPy library. Specifically, I believe it would be highly beneficial to include built-in functions for linked list operations. This would significantly expand the library's capabilities and make it more versatile for various data structures and algorithms. Having direct support for linked lists within NumPy would streamline many data science and machine learning tasks

**Comment by rkern** [comment]
It's not entirely clear to me what kind of linked list you want, nor what applications you think they would apply to. Are you thinking of functions that work with our current numpy arrays as linked lists (like our set operations)? Or are you thinking of another fundamental datastructure alongside `ndarray`? What do you want to do that you cannot do with the stdlib's `collections.deque` object (a kind of advanced linked list)?

Regardless, this seems far out-of-scope for numpy, which is already very large to support the one common array datastructure. I don't think the core team has any appetite to do one of these things inside of numpy, but one could certainly explore ideas in a separate package and demonstrate the value to the community.
