### ISSUE TITLE
DOC: dtype member docstrings are not tested

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#28002]
### Issue with current documentation:

Over at #28001 we discovered that `np.dtype.kind` is not being tested via doctests. I think the problem is in doctests itself, where [it only checks certain items in `obj.__dict__`](https://github.com/python/cpython/blob/7900a85019457c14e8c6abac532846bc9f26760d/Lib/doctest.py#L1064):
- staticmethod, classmethod, property
- inspect.isroutine, inspect.isclass

In the case at hand, `np.dtype.kind` is a member, so it is not collected for testing.

### Idea or request for content:

We should find a work-around, as doctest is a part of the python stdlib, so we cannot simply upgrade the version. cc @ev-br

**Comment by ev-br** [comment]
cross-ref https://github.com/scipy/scipy_doctest/issues/178 which tracks a possible enhancement in scipy-doctest.

**Comment by ev-br** [comment]
`scipy-doctest == 1.6` is on pypi. This version fixes the collection bug, so can expect breakage in several dtype methods which were never doctested and now they are :-). Not sure if gh-28004 fixed them all.

**Comment by ev-br** [comment]
Is there anything left to do here? Looks like it's all done
