### ISSUE TITLE
Deprecate NPY_CHAR

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#2801]
This broke ABI compatibility in 1.6.x. Should be deprecated and removed, see <s>http://projects.scipy.org/numpy/ticket/2228</s> (dead link)

Archive of a sort [here](http://grokbase.com/t/scipy.org/numpy-tickets/12ag932nav/numpy-2228-abi-change-in-1-6-1)

**Comment by charris** [comment]
Moving up to 1.11.

**Comment by auvipy** [comment]
is this deprecated yet? if not how to deprecate a numpy feature? i'm aware with django internals only

**Comment by juliantaylor** [comment]
@pearu any progress?
Can you atleast outline what needs to be done?
this is really important is it is blocking the addition of any new core dtypes.

**Comment by juliantaylor** [comment]
gh-8948 for the deprecation.

**Comment by charris** [comment]
I believe this has been closed by #8948.
