### ISSUE TITLE
BUG: When installing numpy-2.2.0 using pip, it prompts that the hash does not match. Has someone tampered with it?

### ISSUE THREAD

**Issue by Deng-Xian-Sheng** [numpy/numpy#28031]
### Describe the issue:

I created a new venv environment and I was going to install numpy, then I got this error.

### Reproduce the code example:

```python
python -m venv venv 
source ./venv/bin/activate
pip install numpy
```

### Error message:

```shell
Collecting numpy
  Using cached numpy-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    numpy from https://files.pythonhosted.org/packages/90/24/d0bbb56abdd8934f30384632e3c2ca1ebfeb5d17e150c6e366ba291de36b/numpy-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl:
        Expected sha256 85ad7d11b309bd132d74397fcf2920933c9d1dc865487128f5c03d580f2c3d03
             Got        85e8642fd2b40d23fdd12135ed8f16f5ad9f371d73e08689bca048465b7d5829
```

### Python and NumPy Versions:

3.12.4 (main, Jul  9 2024, 09:31:23) [GCC 13.2.0]

### Context for the issue:

Currently version 2.1.3 does not have this problem, but for those who urgently need to use 2.2.0, it is necessary. Also, hashing is generally not wrong, is there a supply chain attack?

**Comment by mattip** [comment]
Please check your download: was it complete (16.1mb)? When I download the link you pointed to I get a wheel with the proper sha256 hash, and the package at https://pypi.org/project/numpy/#numpy-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is correct as well.

**Comment by Deng-Xian-Sheng** [comment]
Thank you, I'm sorry for the bother, I installed it successfully using disabling cache.

I have never used a mirror source. Maybe the last download was incomplete and then cached.

pip install --no-cache-dir numpy
Collecting numpy
  Downloading numpy-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 4.9 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.2.0
