### ISSUE TITLE
TYP: `nditer` does not allow `None`-valued elements in operand sequence

### ISSUE THREAD

**Issue by simonaltrogge** [numpy/numpy#28038]
### Describe the issue:

Passing `None`-valued elements next to array_like-valued elements in a sequence as operands to `nditer` is part of the documented idiom of [iterator-allocated output arrays](https://numpy.org/doc/stable/reference/arrays.nditer.html#iterator-allocated-output-arrays). Mentions of this can also be found in the [documentation of `nditer`](https://numpy.org/doc/stable/reference/generated/numpy.nditer.html) directly. The type-hints do not reflect this, however, and lead to an error instead when using this intended way of calling `nditer`.

### Reproduce the code example:

```python
import numpy as np
import numpy.typing as npt

def square(a: npt.NDArray):
    with np.nditer([a, None]) as it:
        for x, y in it:
            y[...] = x*x
        return it.operands[1]
```

### Error message:

```shell
Argument of type "list[NDArray[Unknown] | None]" cannot be assigned to parameter "op" of type "ArrayLike | Sequence[ArrayLike]" in function "__new__"
  Type "None" is not assignable to type "ArrayLike"
    "None" is incompatible with protocol "Buffer"
      "__buffer__" is not present
    "None" is incompatible with protocol "_SupportsArray[dtype[Any]]"
      "__array__" is not present
    "None" is incompatible with protocol "_NestedSequence[_SupportsArray[dtype[Any]]]"
      "__len__" is not present
      "__getitem__" is not present Pylance (reportArgumentType)
```

### Python and NumPy Versions:

2.2.0
3.13.1 | packaged by conda-forge | (main, Dec  5 2024, 21:23:54) [GCC 13.3.0]

### Type-checker version and settings:

Pylance 2024.12.1 used in Visual Studio Code 1.96.0

**Comment by jorenham** [comment]
Thanks for the report! This is indeed seems to be a valid use-case that currently is falsely rejected, and is reproducible.


---

> Mentions of this can also be found in the [documentation of `nditer`](https://numpy.org/doc/stable/reference/generated/numpy.nditer.html) directly.

Where exactly? I can't seem to find it.

## Minimal repro

```pycon
>>> import numpy as np
>>> np.__version__
'2.2.0'
>>> list(np.nditer([np.ones(3), None]))
[(array(1.), array(6.31480055e-310)), (array(1.), array(6.31480055e-310)), (array(1.), array(1.6e-322))]
```

This `[...]/issue_28038.pyi` example is rejected by both mypy and pyright:

```pyi
import numpy as np
import numpy.typing as npt

a: npt.NDArray[np.float32]
np.nditer([a, None])
```

mypy output:

```
Argument 1 to "nditer" has incompatible type "list[ndarray[tuple[int, ...], dtype[floating[_32Bit]]] | None]"; expected "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes] | Sequence[Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]]"
```

pyright output:

```
Argument of type "list[NDArray[float32] | None]" cannot be assigned to parameter "op" of type "ArrayLike | Sequence[ArrayLike]" in function "__new__"
  Type "None" is not assignable to type "ArrayLike"
    "None" is incompatible with protocol "Buffer"
      "__buffer__" is not present
    "None" is incompatible with protocol "_SupportsArray[dtype[Any]]"
      "__array__" is not present
    "None" is incompatible with protocol "_NestedSequence[_SupportsArray[dtype[Any]]]"
      "__len__" is not present
      "__getitem__" is not present
```

## The cause

`np.nditer.__new__` only accepts array-likes or sequences of array-likes for its first `op` parameter:
https://github.com/numpy/numpy/blob/e7a123b2d3eca9897843791dd698c1803d9a39c2/numpy/__init__.pyi#L4703-L4715

After seeing this, you can probably already see how this could be fixed. Do you want to give it a try, and submit a PR for this @simonaltrogge ?

**Comment by simonaltrogge** [comment]
Admittedly, it is more indirectly than directly: “`allocate` causes the array to be allocated if it is None in the `op` parameter.”

Regarding the PR, that’s already done, see #28039. :)
