### ISSUE TITLE
DOC: offline documentation auto switch dark mode back to light mode

### ISSUE THREAD

**Issue by jack6th** [numpy/numpy#28049]
### Issue with current documentation:

Reproduce:
1. download https://numpy.org/doc/2.2/numpy-html.zip
2. extract the zip file and double click index.html.
3. click "Color mode" button switch to dark mode.
4. click a link from 'Section Navigation' on the left side.
5. the page auto switch back to light mode.

**Comment by seberg** [comment]
Thanks for opening the issue.  Can you move it to [pydata-sphinx-teme](https://github.com/pydata/pydata-sphinx-theme), which is where this swticher is coming from.

**Comment by RafaelDev1v1** [comment]
a
