### ISSUE TITLE
ENH: Proposing a flattening functionality for deeply nested lists in NumPy

### ISSUE THREAD

**Issue by Mark799** [numpy/numpy#28079]
### Proposed new feature or change:

Many people have asked how to flatten a nested list into a one-dimensional list (e.g., see [this StackOverflow thread]( https://stackoverflow.com/questions/952914/how-do-i-make-a-flat-list-out-of-a-list-of-lists)). While flattening a 2D list is relatively straightforward, deeply nested lists can become cumbersome to handle. To address this challenge, I propose adding a built-in list-flattening functionality to NumPy.

By adding this feature to NumPy, the library would not only simplify a frequently used task but also enhance its overall usability, making it an even more powerful tool for data manipulation and scientific computing.

The code snippet below demonstrates how a nested list can be flattened, enabling conversion into a NumPy array. I believe this would be a valuable addition to the package.

```
from collections.abc import Iterable

def flatten_list(iterable):
    
    """
    Flatten a (nested) list into a one-dimensional list.
    
    Parameters
    ----------
    iterable : iterable
        The input collection.
    
    Returns
    -------
    flattened_list : list
        A one-dimensional list containing all the elements from the input, 
        with any nested structures flattened.
    
    Examples
    --------
    
    Flattening a list containing nested lists:
    
    >>> obj = [[1, 2, 3], [1, 2, 3]]
    >>> flatten_list(obj)
    [1, 2, 3, 1, 2, 3]
    
    Flattening a list with sublists of different lengths:
    
    >>> obj = [1, [7, 4], [8, 1, 5]]
    >>> flatten_list(obj)
    [1, 7, 4, 8, 1, 5]
    
    Flattening a deeply nested list. 
    
    >>> obj = [1, [2], [[3]], [[[4]]],]
    >>> flatten_list(obj)
    [1, 2, 3, 4]
    
    Flattening a list with various types of elements:
    
    >>> obj = [1, [2], (3), (4,), {5}, np.array([1,2,3]), range(3), 'Hello']
    >>> flatten_list(obj)
    [1, 2, 3, 4, 5, 1, 2, 3, 0, 1, 2, 'Hello']
    
    """
    
    if not isinstance(iterable, Iterable) or isinstance(iterable, (str, bytes)):
        return [iterable]
    
    def flatten_generator(iterable):
        
        for item in iterable:
            
            if isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
                yield from flatten_generator(item)
                
            else:
                yield item
    
    return list(flatten_generator(iterable))
```

**Comment by rkern** [comment]
I think this is out of [scope](https://numpy.org/neps/scope.html) for numpy.

Any numpy devs who disagree can reopen, but I think it's unlikely.

**Comment by Mark799** [comment]
> I think this is out of [scope](https://numpy.org/neps/scope.html) for numpy.
> 
> Any numpy devs who disagree can reopen, but I think it's unlikely.

Thank you for considering this, @rkern. I understand that requests outside the scope are unlikely to be implemented. However, in this case, I have provided a fully functional code snippet that could be easily integrated. Could this contribution hold value for consideration?

**Comment by mattip** [comment]
No, sorry. It is out of scope for NumPy.
