### ISSUE TITLE
Add unique row, for finding unique rows in a 2D array

### ISSUE THREAD

**Issue by simon-r** [numpy/numpy#2871]
In matlab the function unique works also for selecting the unique rows.
That should be useful if you add this possibility also in numpy.

For example:

> a = np.array( [ [1,2][2,3][1,2] ] )
> 
> np.unique(a , row=True ) # for example
> [[1,2] 
> [2,3]]

see matlab docs: http://www.mathworks.com/help/matlab/ref/unique.html

Now in numpy for performing this operation we must use some unreadable code like:

> np.unique1d(c.view([('',c.dtype)]*c.shape[1])).view(c.dtype).reshape(-1,c.shape[1])

**Comment by micmitch** [comment]
Would be nice if this functionality could be added to numpy!

**Comment by frank-stonybrook** [comment]
@bfroehle I am still confusing about this line of code "B = np.unique(A.view([('', A.dtype)]*A.shape[1]),
               return_index=return_index,
               return_inverse=return_inverse)"
I guess the basic strategy to get a unique row here is to create row-based view which allows the machine to  interpret all elements in a row at once and runs the uniqueness comparison among rows in original array. However, your code actually create a column based view. That' why I feel confusing how does it get the correct answer. 

Thanks!

**Comment by martinosorb** [comment]
I subscribe to the idea of introducing this feature. A lot of people need it, there are questions on Stackoverflow with hundreds of upvotes. Has anyone thought of it? I'm happy to take a look at the code.

**Comment by seberg** [comment]
Go ahead, pull requests are always welcome! The actual additional API (argument name/how it works) should also be discussed on the mailing list.

**Comment by martinosorb** [comment]
Turns out there was already a pull request, which you had commented on:
https://github.com/numpy/numpy/pull/3584
was that not good enough?

**Comment by seberg** [comment]
Yeah, had not found it on first look, but yes. A revival of that would be very welcome (you can clone his branch, make any necessary modification and just create a new PR from that). It seems like some more discussion/persistence about getting the API right and getting support for it might be necessary when looking at the discussion there, i think he already fixed the issues.
I don't remember it well or why exactly it was never merged, whether it was just lack of time for all of us or more reasons.

**Comment by shoyer** [comment]
Fixed by https://github.com/numpy/numpy/pull/7742
