### ISSUE TITLE
AttributeError when comparing inequally-sized ndarrays with complicated dtype

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#2902]
When comparing two ndarrays with complicated dtypes, and the sizes of the arrays are not the same, the comparison fails with an `AttributeError`. Below is some example code.

issue #790 appears similar, but was closed in 2006. The problem I experience is not identical, because a==a _succeeds_; it fails if and only if the sizes are not the same. It also fails with a slightly different error message (it doesn't say anything about a `bool`).

```
In [35]: zeros(4) == zeros(4)
Out[35]: array([ True,  True,  True,  True], dtype=bool)

In [36]: zeros(4) == zeros(5)
Out[36]: False

In [37]: dtp = dtype([("A", int8, 2), ("B", int8, 3)])

In [38]: zeros(4, dtp) == zeros(4, dtp)
Out[38]: array([ True,  True,  True,  True], dtype=bool)

In [39]: zeros(4, dtp) == zeros(5, dtp)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-39-cb9b1c180c1c> in <module>()
----> 1 zeros(4, dtp) == zeros(5, dtp)

AttributeError: logical_and
```

I'm using numpy 1.6.2, git revision ca07bce202ae26b6f0a73870eb2ef0b88e0210c5.

----

Edit seberg:

* The deprecation on `==` is now triggered: `DeprecationWarning: elementwise comparison failed; this will raise an error in the future`
* The whole branch looks a bit weirder (triggers another DeprecationWarning), but I suspect once the first is gone that may be fine (`DeprecationWarning: NotImplemented should not be used in a boolean context`)

**Comment by seberg** [comment]
On main, this now raises the expected error:
```
ValueError: operands could not be broadcast together with shapes (4,2) (5,2)
```
