### ISSUE TITLE
numpy.testing.assert_allclose reports wrong mismatch %

### ISSUE THREAD

**Issue by callegar** [numpy/numpy#2912]
numpy.testing.assert_allclose([1,2,3],[1,2.01,3]) returns

mismatch 100.0%

numpy.testing.assert_almost_equal([1,2,3],[1,2.01,3]) correctly returns

mismatch 33%

**Comment by jorisvandenbossche** [comment]
I think this issue can be closed as #5025 is intended to have fixed this?

**Comment by rgommers** [comment]
Indeed, thanks.
