### ISSUE TITLE
Incorrect documentation of mgrid on scipy.org

### ISSUE THREAD

**Issue by dmjboose** [numpy/numpy#2946]
on the following website (http://www.scipy.org/NumPy_for_Matlab_Users) the comparison to Matlab indicates that the two lines

mgrid[0:9.,0:6.]

and

meshgrid(r_[0:9.],r_[0:6.])

are equivalent, but the results are transposed. The meshgrid result is the one that matches Matlab.

**Comment by njsmith** [comment]
@gthomsen points out that this has been fixed at some point, so closing!
