### ISSUE TITLE
matrix.__add__ vs. matrix.__mul__

### ISSUE THREAD

**Issue by asmeurer** [numpy/numpy#3004]
``` py
In [64]: import numpy

In [65]: numpy.__version__
Out[65]: 1.7.0

In [66]: from sympy import Matrix

In [67]: type(numpy.matrix([[1, 2], [3, 4]]) + Matrix([[1, 2], [3, 4]]))
Out[67]: numpy.matrixlib.defmatrix.matrix

In [68]: type(numpy.matrix([[1, 2], [3, 4]])*Matrix([[1, 2], [3, 4]]))
Out[68]: sympy.matrices.dense.MutableDenseMatrix
```

In other words, `matrix.__add__` gives a `matrix`, but `matrix.__mul__` returns `NotImplemented` (or it just isn't implemented), and so falls back to `sympy.Matrix.__rmul__`.

I don't particularly care which behavior is used, but it should be consistant. Note that this is new in numpy 1.7.0. Previously, both of the above would return a SymPy `Matrix`.

**Comment by mattip** [comment]
Closing, it was fixed in sympy.
