### ISSUE TITLE
np.tile modifies the mask of the inputted masked array

### ISSUE THREAD

**Issue by tjanez** [numpy/numpy#3140]
Here is an example of the problem:

``` python
>>> import numpy as np
>>> import numpy.ma as ma
>>> A = ma.masked_array(np.array([1., 2.]), mask=np.array([False, False]))
>>> A
masked_array(data = [1.0 2.0],
             mask = [False False],
       fill_value = 1e+20)

>>> B = np.tile(A, (2, 1))
>>> A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/numpy/ma/core.py", line 3553, in __repr__
    data=str(self), mask=str(self._mask),
  File "/usr/lib64/python2.7/site-packages/numpy/ma/core.py", line 3537, in __str__
    res[m] = f
ValueError: boolean index array should have 1 dimension
>>> A._data
array([ 1.,  2.])
>>> A._mask
array([[False, False]], dtype=bool)
```

The issue is that the call to `np.tile` changed `A._mask` from `array([False, False], dtype=bool)` to `array([[False, False]], dtype=bool)`, which made the `__repr___()` function return the error.

Digging deeper, I found that the issue is with the call `_nx.array(A,copy=False,subok=True,ndmin=d)` in the [tile function](https://github.com/numpy/numpy/blob/master/numpy/lib/shape_base.py#L829).
Before this call, `A` has the correct `_mask` and after this call, `A`'s `_mask` changes.

Does anyone have any ideas how to fix this?

This is on Fedora-rawhide with:
python-2.7.3-34.fc19.x86_64
numpy-1.7.0-1.fc19.x86_64

**Comment by eric-wieser** [comment]
Thanks for reviving this - I think you just found the root cause of #10270. Pinging @mhvk, who has a PR somewhere that is a smaller alternative to #10308, that was just waiting on a test.

Here's that test:

```
np.tile(np.ma.masked, (2, 1))
assert_equal(np.ma.masked.mask.ndim, 0)  # fails
```

**Comment by mhvk** [comment]
@honnorat - thanks, indeed. My PR #01308 indeed solves this problem, and now uses @tjanez's example on top in a test that should ensure the problem will not recur.

**Comment by eric-wieser** [comment]
@mhvk: Wrong PR number?

**Comment by mhvk** [comment]
Thanks, corrected to #10314

**Comment by cmarmo** [comment]
Hello, I have run the snippet of code in the description and I am under the impression that this issue can be closed?
```py
Python 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.24.0.dev0+934.gdb7414b7f'
>>> A = ma.masked_array(np.array([1., 2.]), mask=np.array([False, False]))
>>> A
masked_array(data=[1.0, 2.0],
             mask=[False, False],
       fill_value=1e+20)
>>> B = np.tile(A, (2, 1))
>>> A
masked_array(data=[1.0, 2.0],
             mask=[False, False],
       fill_value=1e+20)
>>> A._data
array([1., 2.])
>>> A._mask
array([False, False])
```
Thanks for listening.

**Comment by seberg** [comment]
Thanks for the note @cmarmo. Agree, seems this has been fixed years ago!
