### ISSUE TITLE
ma.empty_like copies reference to mask instead of making a new mask

### ISSUE THREAD

**Issue by AgilentGCMS** [numpy/numpy#3145]
ma.empty_like on a masked array creates a new masked array with the mask pointing to the same mask as the source array, so if the target array mask is changed, the mask of the source array changes as well. Code sample:

<code>
from numpy import *
\# create some random data
a = random.random((5,5))
\# make this a masked array
a = ma.masked_greater(a, 0.3)
\# use empty_like to create a new array
b = ma.empty_like(a)
\# change b, in particular do something that sets the mask to False
b[:,:] = 2.0
\# check whether at least one element in a is still masked
print a.mask.any()
</code>

You will see that this destroys the mask of a. Note that this issue is similar to https://github.com/numpy/numpy/issues/2572, except that this exists even for numpy.ma.empty_like, which, being from the numpy.ma module, should in principle know how to handle masked arrays.

**Comment by jjhelmus** [comment]
This issue is also reported in #2572 and has been fixed in PR #5203.  I believe both this issues can be closed.

**Comment by njsmith** [comment]
@jjhelmus: Thanks!
