### ISSUE TITLE
OSError with numpy.fromfile() on python3 (32 bit) after seeking on a big file

### ISSUE THREAD

**Issue by hiddenspirit** [numpy/numpy#3151]
Code:

```
#!/usr/bin/env python3
import os
import sys

assert sys.maxsize == 0x7fffffff

path = "<some big file (over 2 GiB)>"
filesize = os.path.getsize(path)
assert filesize >= sys.maxsize
f = open(path, "rb")

f.seek(sys.maxsize)
numpy.fromfile(f, numpy.uint8, 1)

f.seek(filesize - 1)
numpy.fromfile(f, numpy.uint8, 1)
```

Either "OSError: [Errno 22] Invalid argument" or "OSError: first argument must be an open file" happens.

Only Python 3 (32 bit) seems to be affected. Tested on Windows 7 and Ubuntu 12.10.

**Comment by mattip** [comment]
Closing. Please reopen if it is still relevant on a modern OS / version of NumPy
