### ISSUE TITLE
random_sample for type float32

### ISSUE THREAD

**Issue by dstuebe** [numpy/numpy#3155]
Hi Numpy
I need a numpy.float32 array with a distribution between [0...1). I can not find a way to generate this array using the existing numpy.random tools as converting from the default double to float causes the distribution to change to [0..1].

You can see the problem in the code below. Can you suggest a better approach or should an optional argument for dtype be added to the existing methods?

Thanks
David

```
import numpy
sz = 10000000
rnd_f32 = numpy.zeros(sz,numpy.float32)

while True:
    rnd_f64 = numpy.random.rand(sz) # Creates doubles!
    rnd_f32[:] = rnd_64 #cast to float32
    if (rnd_f32 >= 1.0).any():
        print "FooBar!"
        print "Rnd64 Max: %s" % max(rnd_f64)
        print "Rnd32 Max: %s" % max(rnd_f32)
        break
```

**Comment by waylonflinn** [comment]
The following adds support for strings in the `dtype` argument. This is a common pattern found throughout `numpy`. Examples can be found below.

## Code
```python
import numpy as np

def random_sample(size=None, dtype=np.float64):

	if type(dtype) == str:
		dtype = np.dtype(dtype).type

	type_max = 1 << np.finfo(dtype).nmant
	sample = np.empty(size, dtype=dtype)
	sample[...] = np.random.randint(0, type_max, size=size) / dtype(type_max)
	if size is None:
		sample = sample[()]
	return sample
```
## Example Usage
`random_sample([10], dtype="float32")`

## Similar To
* `np.random.randint(0, 3, 100, dtype="int32")`
* `np.ndarray(10, dtype="float32")`

**Comment by bashtage** [comment]
xref #13163 . This is fixed in the randomgen branch.

**Comment by mattip** [comment]
Closing, the new API supports dtype, note the name is now `np.random.Generator().random` not `random_sample`
