### ISSUE TITLE
ma.polyfit() returns nans when there are masked nans in the input

### ISSUE THREAD

**Issue by goyodiaz** [numpy/numpy#3171]
This used to return (almost) [1., 1.] but returns [nan, nan] in numpy 1.7.

    import numpy as np
    x = np.ma.array([np.nan, 1., 2.], mask=[True, False, False])
    y = np.ma.array([np.nan, 2., 3.], mask=[True, False, False])
    np.ma.polyfit(x, y, 1)

Changing the last line of ma.ployfit() this way seems to work for me:

    return np.polyfit(x.filled(), y.filled(), deg, rcond, full, w, cov)

But it does not make much sense to me, to be honest.

**Comment by njsmith** [comment]
@gthomsen noticed that this seems to be fixed, so closing.
