### ISSUE TITLE
MaskedArray.dot not considering mask?

### ISSUE THREAD

**Issue by tkf** [numpy/numpy#3219]
`masked.dot(other)` is equivalent to `numpy.dot(masked, other)`, rather than `numpy.ma.dot(masked, other)`.

```py
In [1]:
import numpy
a = numpy.ma.array([0, 1], mask=True)
b = numpy.ma.array([0, 1])

In [2]:
a.dot(b)
Out [2]:
1

In [3]:
numpy.ma.dot(a, b)
Out [3]:
masked_array(data = --,
             mask = True,
       fill_value = 999999)
```

**Comment by jjhelmus** [comment]
Thanks for reporting this issue @tkf. This issue with the dot method not respecting the mask was fixed in PR #5709.
