### ISSUE TITLE
Add a more meaningful "ptp"

### ISSUE THREAD

**Issue by ebressert** [numpy/numpy#3292]
The peak-to-peak function, `ptp()`, is a simple and handy function to use, but it confuses the PEP20 suggestions a bit. See this discussion for reference: http://d.pr/i/snXG

Based on the discussion, it may be a good idea to make the name more relevant? Some suggestions include `span()` or `valuerange()`.

**Comment by WarrenWeckesser** [comment]
FWIW: Over in [ufunclab](https://github.com/WarrenWeckesser/ufunclab), I created a function called `peaktopeak` as an exercise in creating generalized ufuncs.  `peaktopeak` makes two imrovements over `ptp`:

* It makes a single pass over the data, so it will usually be faster than `ptp`.
* For arrays of signed integers, `peaktopeak` returns an unsigned integer result.  `ptp` returns a negative value with arrays of signed integers when the peak-to-peak value exceeds the maximum signed integer of the array's dtype (e.g. `np.array([-100, 0, 100], dtype=np.int8).ptp()` returns -56).

**Comment by mattip** [comment]
Closing. This is more appropriate for scipy.
