### ISSUE TITLE
Problem with dot(a,b,out=a)

### ISSUE THREAD

**Issue by rougier** [numpy/numpy#3357]
Here is a short example showing the problem (when out = a or out =b):

This works as expected:

```
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
np.dot(a, b)
```

This doesn't work as expected (wrong result):

```
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
np.dot(a,b,out=a)
```

**Comment by mattip** [comment]
Fixed in the NEP 20 refactoring
