### ISSUE TITLE
test_ufunc.py should test exceptions thrown from ufuncs

### ISSUE THREAD

**Issue by girving** [numpy/numpy#3359]
`test_ufunc.py` runs a few tests against the rational dtype that I wrote, but doesn't seem to run any of the exception-related tests.  In particular, if in my code I leave the `ACQUIRE_GIL` define commented out (see `test_rational.c.src`), I get a segfault in the `test_numpy_cast` test here:

https://github.com/girving/rational/blob/69c7c8ec2fe49461e87501503a9407ab0f47ae0b/test_rational.py#L174

I have only tested this against 1.7.1, so it's possible the bug is fixed in more recent versions.  However, it should be tested regardless of whether it's fixed.

**Comment by mattip** [comment]
Can we close this?

**Comment by girving** [comment]
Fine to close from my perspective.
