### ISSUE TITLE
Datetime timezone handling broken in 1.7.x

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#3388]
For a description, see http://thread.gmane.org/gmane.comp.python.numeric.general/53805

Something needs to be done about this for 1.8.0

**Comment by charris** [comment]
Datetime has stalled out in 1.10-devel. Kicking this onward to 1.11.

**Comment by charris** [comment]
@shoyer can this be closed?

**Comment by shoyer** [comment]
@charris yes, this is exactly why we switch to time zone naive datetimes!
