### ISSUE TITLE
regression (in 1.7.x series within "ENH: missingdata ..") -- incorrect np.asarray's result shape when fed ctypes data

### ISSUE THREAD

**Issue by yarikoptic** [numpy/numpy#3406]
```
$> python -c 'import ctypes, numpy as np; print np.__version__; print np.asarray((ctypes.c_double*2)()).shape'                              
1.7.1
(2, 2)

$> ON ANOTHER BOX with 1.6.2
1.6.2
(2,)
```

Initially detected with PyMVPA's unittest 
http://github.com/PyMVPA/PyMVPA/blob/HEAD/mvpa2/tests/test_procrust.py
testing functionality of
https://github.com/PyMVPA/PyMVPA/blob/HEAD/mvpa2/support/lapack_svd.py
and crashing with `TypeError: object of type 'float' has no len()` without any obvious reason, in differing locations depending on numpy's treeish

the issue  was bisect to lie somewhere within 321b8bf..25a64c8  where intermediate commits didn't build (some still might... forgot details)

Problem was troubleshooted with Sebastian (AKA seberg on IRC) -- many kudos to him, and as a resolution use of '.frombuffer' instead of '.asarray' was suggested and seems to resolve the crash in my case:

```
(Pydb) print vt
[[ 0.98039903 -0.19702221]
 [-0.19702221 -0.98039903]]
(Pydb) print numpy.frombuffer(s)
[ 0.50684344  0.49315656]
*(Pydb) print numpy.asarray(s)
*** TypeError: object of type 'float' has no len()
```

**Comment by joergdietrich** [comment]
Has this maybe been fixed?

```
$ python -c 'import ctypes, numpy as np; print(np.__version__); print(np.asarray((ctypes.c_double*2)()).shape)'          
1.12.1
(2,)
```

**Comment by pv** [comment]
I think there was a bug in ctypes buffer api format strings that was 
fixed in some CPython version.

**Comment by mattip** [comment]
Closing since the example now passes, please reopen if needed
