### ISSUE TITLE
savez fails when /tmp files are size limited.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#3464]
The size limit causes problems because savez goes through _savez, which creates a temporary file, then zips it. The size limit arises in recent Linux distros -- Ubuntu, Fedora, others -- that have started mounting tmpfs on /tmp. The tmpfs file system is essentially a ram disk and uses memory, which limits the size available. The advantage is spped and that SSD life is extended by not doing large numbers of small writes. On Linux is it probably better to use /var/tmp when writing big temporary files, but probably the easiest solution would be to put the temporary file in the user's directory. It gets deleted in any case.

**Comment by serhiy-storchaka** [comment]
#9863 solves this issue in Python 3.6+ by getting rid of temporary files.

**Comment by charris** [comment]
After the release of NumPy 1.14.0, temporary files can be avoided by upgrading to Python 3.6, which allows writing streams directly to the zipfile. So closing this.
