### ISSUE TITLE
assert_array_almost_equal_nulp tests only pass by chance

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#347]
There are a ton of tests in numpy/testing/tests/test_utils.py that use np.random without setting a seed.

So first of all, that's a bug just by itself, because it means that the actual tests that are being run depends randomly on what other tests have been run -- as I discovered today while adding a totally different test that touch np.random and suddenly the tests in test_utils started failing. So all these tests should be using an explicit random seed.

Second, the fact that these tests are failing randomly as soon as the input is perturbed suggests that either `assert_array_almost_equal_nulp` or its tests are broken. And that we should be testing a lot more cases, since obviously the existing tests have not really been working (it's really easy to do `for i in xrange(100): do_random_test()`!).

Since I'm trying to get this other patch submitted, for now I'll just add a loop to `TestArrayAlmostEqualNulp.test_simple` to force it to fail consistently, and knownfail it. But someone who knows about this module should really take a look...

**Comment by charris** [comment]
Closed by #5439.
