### ISSUE TITLE
Don't (try to) handle __array_priority__ in ufunc_object.c (badly)

### ISSUE THREAD

**Issue by inducer** [numpy/numpy#3502]
This issue is a continuation of the disussion with @seberg in PR #3501:

In my opinion, having `__array_priority__` logic in `umath` is just broken. It should be ripped out. A tell-tale sign of this is that the logic is activated only for two-argument ufuncs with one output. What's so special about them? Why should they behave differently from three-argument ufuncs? Also, as @seberg pointed out, why should a ufunc ever return `NotImplemented`?

See here:
- https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L2362
- https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L1971

**Comment by seberg** [comment]
This has happened (Probably done by Marten or maybe Nathaniel at some point :)).
