### ISSUE TITLE
BUG: Assignment of complex rank-zero arrays produces misleading error

### ISSUE THREAD

**Issue by endolith** [numpy/numpy#3548]
This all makes sense to me:

```
In [2]: h = zeros(5, dtype=complex)

In [3]: h[1] = 1

In [4]: h[2] = array(2)

In [5]: h[3] = 3j

In [6]: h[4] = array(4j)

In [7]: h
Out[7]: array([ 0.+0.j,  1.+0.j,  2.+0.j,  0.+3.j,  0.+4.j])
```

This also makes sense:

```
In [8]: h = zeros(5)

In [9]: h[1] = 1

In [10]: h[2] = array(2)

In [11]: h[3] = 3j
------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython console>", line 1, in <module>
TypeError: can't convert complex to float
```

This does not make sense:

```
In [12]: h[4] = array(4j)
------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython console>", line 1, in <module>
ValueError: setting an array element with a sequence.
```

The problem is not that array(4j) is a "sequence"; array(3) works fine.  The problem is that it's complex and you're trying to put it in a real array.

Took me a long time to figure out why 
`scipy.signal.impulse((array([1, 1]), array([1, 1]), 15))` works but
`scipy.signal.impulse((array([1, 1]), array([1, 1]), 15+0j))` does not.

**Comment by eric-wieser** [comment]
This now gives `TypeError: can't convert complex to float` in master (and probably earlier)
