### ISSUE TITLE
arccosh works for much larger numbers than arccos

### ISSUE THREAD

**Issue by endolith** [numpy/numpy#3595]
arccosh(x) = i arccos(x), so `np.arccos()` and `np.arccosh()` should produce the same output but with real and imaginary flipped:

```
In [39]: arccos(0.1+0j), arccosh(0.1+0j)
Out[39]: ((1.4706289056333368-0j), 1.4706289056333368j)

In [40]: arccos(1.1+0j), arccosh(1.1+0j)
Out[40]: (0.44356825438511532j, (0.44356825438511532+0j))
```

but at 10**7, arccos is inaccurate:

```
In [47]: arccos(10**7+0j), arccosh(10**7+0j)
Out[47]: (16.805431370234086j, (16.811242831518264+0j))
```

and then gives up at 10**8 and outputs infs:

```
In [48]: arccos(10**8+0j), arccosh(10**8+0j)
Out[48]: (inf*j, (19.113827924512311+0j))
```

but arccosh keeps going to almost the full float range:

```
In [86]: arccos(10**307+0j), arccosh(10**307+0j)
Out[86]: ((-inf-inf*j), (707.58677072973194+0j))
```

and [is still accurate](http://www.wolframalpha.com/input/?i=arccos[10**307])

so whatever algorithm is used for arccosh could presumably be used for arccos also, just with the imaginariness flipped.

**Comment by mattip** [comment]
Closing. In the examples given `arccos` is now the complex conjugate of `arccosh`. Please reopen with failures if relevant.
