### ISSUE TITLE
DOC: NumPy matrices `.nonzero()` returns matrices instead of arrays. 

### ISSUE THREAD

**Issue by cowlicks** [numpy/numpy#3605]
NumPy matrices `.nonzero()` return a tuple of matrices instead of arrays. The [documentation](http://docs.scipy.org/doc/numpy/reference/generated/numpy.nonzero.html) states that it should be a tuple of arrays. Code example:

``` python


In [27]: import numpy as np

In [28]: a = np.asmatrix(np.random.randint(2, size=(4, 6)))

In [29]: a
Out[29]: 
matrix([[1, 1, 1, 0, 0, 0],
        [1, 0, 0, 1, 0, 0],
        [1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 0, 0]])

In [30]: a.nonzero()
Out[30]: 
(matrix([[0, 0, 0, 1, 1, 2, 2, 2, 3, 3]]),
 matrix([[0, 1, 2, 0, 3, 0, 1, 3, 1, 2]]))
```

**Comment by mattip** [comment]
The [documentation](https://numpy.org/devdocs/reference/generated/numpy.matrix.nonzero.html) should note that matrices are returned

**Comment by hypercubestart** [comment]
@mattip is this issue still relevant? I am getting a tupple of arrays.
![image](https://user-images.githubusercontent.com/24601452/64929475-93dc2a80-d7db-11e9-8243-fde118bb3e20.png)
\numpy version: '1.18.0.dev0+aa01384'

**Comment by eric-wieser** [comment]
1.16.5 also shows this as fixed.
