### ISSUE TITLE
object with 'dtype' property crashes numpy

### ISSUE THREAD

**Issue by mwiebe** [numpy/numpy#3614]
The following code crashes numpy (latest master):

```
import numpy as np
class crashnumpy(object):
    @property
    def dtype(self):
        return self
np.array([1], dtype=crashnumpy())
```

**Comment by OmerJog** [comment]
was this fixed?

**Comment by seberg** [comment]
No, gh-13003 includes this fix, but I was travelling and on a small conference now, so I did not finish it up. I guess we will probably have it fixed soon. Does this affect you much?

**Comment by seberg** [comment]
Oh, forgot to close this one. It raises a maximum recursion depth error right now. There is the next step of deprecating parts of it, but there was even another issue about it IIRC.
