### ISSUE TITLE
Add numpy.phase in addition to numpy.angle

### ISSUE THREAD

**Issue by SuperFluffy** [numpy/numpy#3621]
I wanted to suggest adding a function which directly gives the phase of a complex valued number instead of the angle:

```
def phase(z): # Calculates the phase of a complex number
  r = numpy.absolute(z)
  return (z.real/r + 1j * z.imag/r)
```

This is a simple enhancement, which I think would make numpy more consistent and offer the benefit of simply being faster in large loops, rather than going the `ang = numpy.angle(z); phase = numpy.cos(ang) + 1j * numpy.sin(ang)` route (or `numpy.cos(1j * ang)`, for what it's worth).

**Comment by lebigot** [comment]
Side note: an argument against calling such a function `phase` is that `cmath.phase()` does something different (it essentially returns the same thing as `numpy.angle()`.

**Comment by eric-wieser** [comment]
On a similar note, an implementation of `copysign` for complex numbers would be nice, presumably with semantics `abs(a) * sgn(b)` - here it's pretty clear the `z / |z|` definition is more useful.

**Comment by mhvk** [comment]
Second the idea of extending `copysign` to complex numbers (although `copydirection` might be more intuitive -- and extendable to vectors).

**Comment by mhvk** [comment]
I'm closing this in favour of #13179 (mostly since the title no longer reflects the discussion, and because I think the request makes more sense as part of a larger effort to make working with complex numbers a little easier).
