### ISSUE TITLE
numpy.complex128 can easily overflow taking ratios of large quantities

### ISSUE THREAD

**Issue by callegar** [numpy/numpy#3649]
`>>> a=1E200j`

`>>> 1/a`
-1e-200j

This is OK

`>>> 1/np.complex128(a)`
-0j

Overflow

Weird enough, using arrays of complex128 there is no overflow

`>>> 1/np.asarray(a,dtype=np.complex128)`
-9.9999999999999998e-201j

**Comment by WarrenWeckesser** [comment]
At some point in the ensuing years, the original issue has been fixed:
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.22.0.dev0+1211.g7e8285ba4'

In [3]: a = 1e200j

In [4]: 1/a
Out[4]: -1e-200j

In [5]: 1/np.complex128(a)
Out[5]: -1e-200j

In [6]: np.divide(1, np.complex128(a))
Out[6]: -1e-200j

In [7]: 1/np.array(a)
Out[7]: -1e-200j

In [8]: 1/np.array([a])
Out[8]: array([0.-1.e-200j])
```
