### ISSUE TITLE
why support for axis=(1,2,3), i.e. a tuple, is not documented?

### ISSUE THREAD

**Issue by saullocastro** [numpy/numpy#3666]
In NumPy 1.7.1 we have seen some answers in SO:

- http://stackoverflow.com/a/18357674/832621

- http://stackoverflow.com/a/18545281/832621

where they are suggesting to pass a tuple to the `axis` argument.

It does work but we cannot find where it is documented.

Do you have any plans to include this into the official documentation?

Thank you!

**Comment by jaimefrio** [comment]
Closed by #5146
