### ISSUE TITLE
Data type conversion falling over to python types causes opaque bugs 

### ISSUE THREAD

**Issue by azylstra** [numpy/numpy#3756]
Hi numpy folks,
I have a function implementing a supergaussian function like so:

``` python
def supergaussian(x, A, mu, sigma, offset, N=8):
    return A * (1/(2**(1+1/N)*sigma*2*scipy.special.gamma(1+1/N))) * numpy.exp(-numpy.absolute(numpy.power(x-mu,N))/denom) + offset
```

I'm using the numpy math functions because this is used for curve fitting. The way that numpy handles data types for very large integers causes opaque problems. Basically, the denominator in my exponential gets too large for a numpy.int64, e.g.:

``` python
type(np.max(2*25**13))
```

is numpy.int64 but

``` python
type(np.max(2*25**14))
```

becomes int, presumably because it is too large for numpy.int64. In the first case, the value in the `numpy.exp` call is a numpy type (numpy.float64), but in the second case it becomes the python float instead. This leads to the code throwing an error:
`AttributeError: 'float' object has no attribute 'exp'`

If I evaluate the expression in the exponential, you can see that:

``` python
x = 10.
mu = 0.
np.max(-numpy.absolute(numpy.power(x-mu,13)))/(2*25**13))
```

returns type numpy.float64, but

``` python
np.max(-numpy.absolute(numpy.power(x-mu,14)))/(2*25**14))
```

becomes a normal float.

This seems to be related to the other open issue #3409 but in this case it's actually causing a problem unless I work around by forcing the type to be numpy.float64. 

I would suggest that this issue be worked around by having numbers too large for numpy.int64 fall back to numpy.float64 instead of a built-in type, or do the latter with a warning/error. Thanks!

**Comment by seberg** [comment]
Fixed in main by implementing NEP 50 (at least effectively, as it cements the ability to not convert the integer to an array first).

(Of course if you call `np.array()` explicitly on the value, you will get a terrible dance of `dtype=object` loop which then extract things, wraps it again and finally should succeed.)
