### ISSUE TITLE
Weird behaviour of string_array == []

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#3764]
This just bit me. @seberg, maybe you fixed it already?

```
# Regular dtype, == [] does the obvious thing:
In [9]: np.asarray([]) == []
Out[9]: array([], dtype=bool)

# String dtype, it gives the wrong answer:
In [8]: np.asarray([], dtype="S4") == []
Out[8]: False
```

(Specifically I was doing `np.all(string_array == array_like)` and somehow my tests were failing...)

**Comment by JeffryMAC** [comment]
yeah 
```
>>> np.asarray([]) == []
array([], dtype=bool)
>>> np.asarray([], dtype="S4") == []
__main__:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
False
```

**Comment by seberg** [comment]
Well, the warning is now there also for strings, so strings are not special anymore.  It still might be considered weird, but I will close it for now (considering the age).

NumPy normally never guesses so `[]` has float dtype effectively and thus runs into the warning now (which maybe should just broadcast to an empty array – of False if there was anything in it)
