### ISSUE TITLE
[1.7.1] fcompiler/gnu.py ignores the LDFLAGS from python2.7/config/Makefile

### ISSUE THREAD

**Issue by RJVB** [numpy/numpy#3797]
I ran into a scipy build failure that was caused by the fact that numpy's fcompiler/gnu.py ignores the linker flags defined through LDFLAGS in Python's config/Makefile . As a result, required linker flags were not passed to gfortran .

A few modifications to gnu.py resolved this:
After the _c_arg_flags function:

```
def _ld_flags(self):
    """ Return detected flags from LDFLAGS """
    from distutils import sysconfig
    try:
        return sysconfig.get_config_vars()['LDFLAGS'].split()
    except KeyError:
        return []
```

In GnuFCompiler.get_flags_linker.so I extend opt right after defining it:

```
    opt = self.linker_so[1:]
    opt.extend( GnuFCompiler._ld_flags(self) )
```

and then of course one doesn't need to (= shouldn't) add the arch_flags specifically (on Darwin) in Gnu95FCompiler.get_flags_linker_so :

```
def get_flags_linker_so(self):
    flags = GnuFCompiler.get_flags_linker_so(self)
    return flags
```

With these modifications, scipy 0.12.0 builds fine under 32+64 x86 universal python 2.7.5 on Mac OS X 10.6.8, and the standard test suite completes OK.

**Comment by rgommers** [comment]
`LDFLAGS` has been honored by default since numpy 1.18.0, so closing this.

Thanks all.
