### ISSUE TITLE
Unsafe use of PEP-3118 buffers

### ISSUE THREAD

**Issue by pv** [numpy/numpy#3831]
The current Numpy code base contains some calls to `PyObject_AsWriteBuffer / PyObject_AsReadBuffer`. These are unsafe for PEP-3118 buffers, since these Python routines release the buffer immediately after obtaining the pointer.

The correct fix would probably be to use a refcounted buffer object, which would also find use in other parts of Numpy (currently, memoryview is used, but it contains other stuff). There's an implementation in CPython source code 
http://hg.python.org/cpython/file/f6792f734fcc/Objects/memoryobject.c#l7 that could be used.

**Comment by charris** [comment]
The use of these functions raise errors in Python 3.7, we should stop using them for Numpy 1.5. @pv Do you still think we should borrow the "managedbuffer" object from Python 3, or would memoryviews be sufficient.

**Comment by charris** [comment]
A `managedmemory` object could be a useful lowlevel part. @njsmith Thoughts?

**Comment by njsmith** [comment]
All else being equal it seems simpler to use `memoryview` than to copy/paste a bunch of code we'd then have to maintain, but I don't know if there are other downsides I'm not seeing. @pv what do you mean about "it contains other stuff" in your original post?

**Comment by charris** [comment]
Looking at the 3.7 code, those functions only support the new `Py_buffer` type in Python 3, so I think the easy thing to do is wait until we drop 2.7 support, then replace them the new equivalents. Short term, we can ignore the deprecation warnings from the compiler for 3.7, I'm not sure why we didn't see them before, probably a flag somewhere. Another alternative would be the `npy_3kcompat.h` file, but I don't think it worth the effort.

**Comment by eric-wieser** [comment]
> The use of these functions raise errors in Python 3.7

Most of these calls are guarded by an `#ifndef NPY_3K`, making this a non-issue. Is there one that is not?

**Comment by charris** [comment]
Hmm, thinking a bit more, if we want the last NumPy release to support 2.7 to have decent longevity, putting something in `npy_3kcompat.h` might be the right way to go.

**Comment by njsmith** [comment]
BTW, the `PyBuffer_As*` functions are clearly broken, but I don't see any evidence that they've been removed in 3.7 -- what errors are you getting?

**Comment by charris** [comment]
They have a deprecated attribute in the C source, which causes a compiler warning with `-Wdeprecated-declarations`, which seems to be the Python 3.7 standard, at least in development versions. That is 11 extra warnings which triggers a test failure. Note that those functions are available in Python 3, but they use the new `Py_buffer` object, not the old one, that is, they are an alternative API to those objects, hence not needed. So we can

1. ignore the warnings, i.e., kick the can down the road,
2. or add numpy versions to `npy_3kcompat.h`
3. or stop using them in Python 3

I haven't looked at all the uses, but 3 is an easy fix for the `ctors.c` cases. They aren't  guarded by an `#ifndef NPY_3K` but we can add that and fix them up.

**Comment by mattip** [comment]
can be closed, all the uses were guarded with `#ifdef NPY_3k` in 7d2f3a6357
