### ISSUE TITLE
MachAr._do_init() hangs under mod_wsgi

### ISSUE THREAD

**Issue by lanzz** [numpy/numpy#3837]
(numpy version 1.6.2)

I've been investigating a complete process hang during `from sklearn.cluster import DBSCAN`, and I've traced it to a call to `numpy.finfo(float)` in the `scipy.linalg.decomp_schur` module. The actual hang occurs in `core/machar.py` [line 227](https://github.com/numpy/numpy/blob/master/numpy/core/machar.py#L227):

```
temp = z*t
```

This line is within a `for` loop and occurs on the `_ = 9` iteration. At that point I'm getting `repr(z) = array([  5.56268465e-309])`, and `repr(t) = array([ 1.])` (I don't know how to get a more accurate representation of their actual state). The next line is never reached — the process hangs indefinitely at the `temp = z*t` line.

The weirdest part is that the `from sklearn.cluster import DBSCAN` import works fine when I try it in a clean Python shell, but hangs when running in our web application. We're using numpy very sparsely, and we're certainly not messing with its internals, so I have no idea how to narrow down the conflict that apparently occurs between numpy and the rest of our codebase.

**Comment by ndjensen** [comment]
This is definitely not a trivial thing to solve, but if you wanted to replace PyGILState_Ensure() then I think you can as long as you have the PyThreadState*.  Getting that could be tricky, Jep uses the PyThreadState_GetDict() method.  See https://github.com/mrj0/jep/blob/v3.3.0rc/src/jep/pyembed.c#L351

```C
PyEval_AcquireLock();
PyThreadState *prevThread = PyThreadState_Swap(tstate);
// do stuff
PyThreadState_Swap(prevThread);
PyEval_RelaseLock();
```
For an example of Jep doing this, see https://github.com/mrj0/jep/blob/v3.3.0rc/src/jep/pyembed.c#L708

**Comment by charris** [comment]
The code is still there in current NumPy, but has been superseded and should not be accessed in normal use from finfo if you have a standard floating type. If it gets fixed in the future, it will preferably be by removal. Could you try a more recent NumPy and see if that fixes the problem?

**Comment by elliottslaughter** [comment]
I upgraded to NumPy 1.13.3 and the problem went away. Thank you!

**Comment by charris** [comment]
Thanks for checking.
