### ISSUE TITLE
test_nonzero_byteswap uses denormals, fails depending on icc floating point compiler flags.

### ISSUE THREAD

**Issue by derekbrokeit** [numpy/numpy#3844]
The test output can be seen here:
https://gist.github.com/derekbrokeit/6772961

The first error (test_nonzero_byteswap) was actually seen with 1.7.1, but I attempted to install 1.8 to see if that corrected the problem (it did not). 

I wanted to bring this to your attention, but also wanted to ask if this is something that I should worry about.

compiler version:

```
$ icc --version
icc (ICC) 12.0.0 20101116
Copyright (C) 1985-2010 Intel Corporation.  All rights reserved.
```

I also tested numpy 1.7.1 and python2.7.3 resulting in the byteswap error with a newer build of icc (have not tested 1.8).

```
icc (ICC) 13.1.0 20130121
Copyright (C) 1985-2013 Intel Corporation.  All rights reserved.
```

python version:

```
Python 3.3.2 (default, Oct  1 2013, 09:31:14)
[GCC Intel(R) C++ gcc 4.1 mode] on linux
```

**Comment by boegel** [comment]
We (@olavks and myself) are seeing this `test_nonzero_byteswap` failure too, see https://gist.github.com/boegel/92e3d4e1af95876d9ee4.

For the above, I conclude that this test is actually broken, and that this is not a real problem. Is that right? Or is there actually a miscompilation of some sort?

**Comment by vanzod** [comment]
Hi all. Any update regarding this issue?
Is it still ok to assume that it is just a bug in the tests that does not affect `numpy` correctness?

**Comment by mattip** [comment]
@oleksandr-pavlyk is this still relevant?

**Comment by olavks** [comment]
I quit the IT industry close two years ago. I was bored and moved back
home. I don't see a butten that says go away.

**Comment by derekbrokeit** [comment]
I no longer have access to the `icc` compiler, so I cannot test further. However, I did fix the link to the gist with relevant test output from 2013.

**Comment by oleksandr-pavlyk** [comment]
I do not think it is. Using NumPy 1.17 in Intel Distribution for Python, which is compiled with ICC 2016 update 3:

```
In [43]: a = np.array([0x80000000, 0x00000080, 0], dtype=np.uint32)

In [44]: a
Out[44]: array([2147483648,        128,          0], dtype=uint32)

In [45]: a.view(np.float32)
Out[45]: array([-0.0e+00,  1.8e-43,  0.0e+00], dtype=float32)

In [47]: a.view(np.float32).byteswap().newbyteorder()
Out[47]: array([-0.0e+00,  1.8e-43,  0.0e+00], dtype=float32)

In [48]: a.view(np.float32).dtype.itemsize
Out[48]: 4

In [49]: a.view(np.float32).__array_interface__['data']
Out[49]: (94273922875776, False)

In [50]: a.__array_interface__['data']
Out[50]: (94273922875776, False)

In [51]: a.view(np.float32).tostring()
Out[51]: b'\x00\x00\x00\x80\x80\x00\x00\x00\x00\x00\x00\x00'
```

No test suite failures were observed when compiling with ICC 2019 update 4 either. 

Let me know if I misunderstood the issue.

**Comment by mattip** [comment]
Closing. Please reopen if we misunderstood.
