### ISSUE TITLE
ERROR: test_big_arrays (test_io.TestSavezLoad) on OS X + Python 3.3

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#3858]
Reported by Piet van Oostrum on the mailing list against 1.8.0rc1 on OS X with Python 3.3:

```
======================================================================
ERROR: test_big_arrays (test_io.TestSavezLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/numpy/lib/tests/test_io.py", line 149, in test_big_arrays
    np.savez(tmp, a=a)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/numpy/lib/npyio.py", line 530, in savez
    _savez(file, args, kwds, False)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/numpy/lib/npyio.py", line 589, in _savez
    format.write_array(fid, np.asanyarray(val))
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/numpy/lib/format.py", line 417, in write_array
    fp.write(array.tostring('C'))
OSError: [Errno 22] Invalid argument
```

**Comment by makmanalp** [comment]
Another data point - using OSX 10.9.5 (Mavericks) and I get the same issue. I just saw this bug in the python tracker: https://bugs.python.org/issue24658

**Comment by charris** [comment]
Might as well reopen this. I don't know if it will be fixed when Python solves their part, but we will find out.

**Comment by adammenges** [comment]
Happens here, latest macOS, python (3.6), and numpy.

**Comment by danlou** [comment]
FYI Still seeing this bug on latest macOS (10.12.6) and Python 3.5.2 (Anaconda 4.2.0).
Has anyone figured out an upper limit on chunk sizes?

**Comment by divyansha** [comment]
Getting this error as well, macOS Sierra, python 3.6, numpy

**Comment by charris** [comment]
There looks to be some motion on the Python issue, but perhaps we should just go ahead and chunk the writes.

**Comment by charris** [comment]
Looks like this isn't going to get fixed upstream anytime soon. Anyone know the latest status?

**Comment by matrixise** [comment]
Hi all,

Could you try this issue with the last 3.6, 3.7 and 3.8 ? because I think to have fixed the issue on OSX with this PR (https://github.com/python/cpython/pull/1705).

Thank you

**Comment by charris** [comment]
@rgommers Any chance you can test this? Any other feedback on the current status of this would be welcome.

**Comment by rgommers** [comment]
The `test_big_arrays` test passes, but https://github.com/numpy/numpy/issues/3858#issuecomment-25607105 still fails for me with the latest Python 3.6 shipped by Anaconda. That probably doesn't have the CPython fix though. No time to build Python myself right now, sorry.

**Comment by charris** [comment]
@rgommers can you revisit this?

**Comment by rgommers** [comment]
This is indeed fixed as far as I can tell, at least with Python 3.7 from Anaconda. No other reports either, so closing. Thanks everyone, and @matrixise in particular for fixing this.
