### ISSUE TITLE
np.count_nonzero() should accept axis parameter

### ISSUE THREAD

**Issue by kernc** [numpy/numpy#391]
Currently, [np.count_nonzero()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.count_nonzero.html) accepts only the input array. I propose adding `axis` parameter similar to that of functions np.sum() and np.max() etc.

```
>>> A = np.arange(6).reshape(2,3)
>>> np.count_nonzero(A)  # with axis=None, count_nonzero in flattened A
5
>>> np.count_nonzero(A, axis=0)
array([1, 2, 2])
>>> np.count_nonzero(A, axis=1)
array([2, 3])
```
I think the alternative `(A != 0).sum(axis=rows_or_cols)` isn't as clear.

**Comment by tentrillion** [comment]
Also +1 here.

**Comment by lzkelley** [comment]
+1
