### ISSUE TITLE
masked_array.mean(axis=-1) returns np.float64 

### ISSUE THREAD

**Issue by Jim-Holmstroem** [numpy/numpy#3927]
type(masked_array( [0, 1] ).mean(axis=-1))
    type(masked_array([[0, 1]]).mean(axis=-1))

The return type depends on the number of dimensions of the masked_array which can hide bugs with ``np.float64`` not working like 0-dimensional ``masked_array``, like for example accessing the attribute ``data``

Just realised that this is documented behaviour for ``.sum`` but not for ``.mean``, this is thus probably only a documentation issue. Personally I would feel better if methods always returns the same type

I'm running ``'numpy-1.8.0.dev-e589c6e'``

**Comment by jjhelmus** [comment]
With commit b40e686f10421099400a533b343d6d1212f786e9, MaskedArrays are returned for both lines in the original report.  Specifically the fix is due to the changes on [line 783-784 of the ma/core.py file]( https://github.com/juliantaylor/numpy/blob/b40e686f10421099400a533b343d6d1212f786e9/numpy/ma/core.py#L783-L784) which force the division to occur on arrays.

The sum method still returns np.int64 types in certain cases as mentioned in the documentation:

```
>>> np.version.version
'1.11.0.dev0+626eb37'
>>> print type(np.ma.masked_array( [0, 1] ).sum(axis=-1))
<type 'numpy.int64'>
>>> print type(np.ma.masked_array([[0, 1]]).sum(axis=-1))
<class 'numpy.ma.core.MaskedArray'>
```

Since this is fixed this issues can be closed.

**Comment by njsmith** [comment]
@jjhelmus: How about we just give you write permissions so you can go ahead and close these things yourself? :-) Any objection?

**Comment by jjhelmus** [comment]
Sounds good to me @njsmith.  I would not mind being able to assign labels to issues so that these can be identified easier.

**Comment by njsmith** [comment]
@jjhelmus: you should have email from github asking you to confirm.

Definitely if you see issues that should be closed or need labels or whatever then "edit boldly", as they say on wikipedia... the issue tracker has a tendency towards maximum entropy, so anything that helps keep that in check is helpful, and there are plenty of other eyes watching so you don't need to worry about breaking things by accident :-). Beyond that, while you technically have the ability to commit directly to master now we definitely do not do that -- for any actual changes you want to make you should still submit a PR and wait for someone else to merge it. But if you want to get more involved in reviewing / merging other people's PRs, you're very welcome to do that as well -- just ask if you're uncertain about anything.

**Comment by jjhelmus** [comment]
Confirms and added to the team, thanks @njsmith.  I'll use the new powers for good and edit away.
