### ISSUE TITLE
Add LDL decomposition

### ISSUE THREAD

**Issue by hunse** [numpy/numpy#3960]
Add support for the [LDL decomposition](http://en.wikipedia.org/wiki/Cholesky#LDL_decomposition_2), which is a variant of the Cholesky decomposition that doesn't take any square roots (faster). LAPACK has a function for this called DPTTRF, so I'm guessing that supporting this is just a matter of adding a wrapper for this function. Also, if this is something that would fit better in Scipy, let me know.

**Comment by daniel-perry** [comment]
I'm interested in having an LDL decomposition available in numpy as well.
It looks like @tmwright has committed some code (a year ago) that appears from visual inspection to be a really good start if not most/all the way there.
Is there anything that is specifically preventing it from being merged in?
I'm happy to code, test, etc. but wasn't sure of the status?

**Comment by seberg** [comment]
Not sure about the status, maybe you can carry on the project. @tmwright it seems like you did a nice start, it would be best if you could give your OK and maybe a tip about the status so that maybe @daniel-perry can carry on and make it a pull request. (Assuming you are happy with that).

**Comment by daniel-perry** [comment]
Sounds good.  Assuming @tmwright is ok with this (@tmwright, please advise if you don't agree), I will grab his public changes, test things, fix anything I find amiss and then put in a pull request.

**Comment by daniel-perry** [comment]
Would you say this feature would be better suited for scipy specifically than numpy?
I ask because of this statement here: 
https://www.scipy.org/scipylib/faq.html#what-is-the-difference-between-numpy-and-scipy
Which essentially says in an ideal world all the linear algebra routines would be in scipy not numpy.

If so, then maybe I can open an issue in scipy instead and make these changes there, and this ticket can be closed by referencing that one?
(Unless there is a reason to have LDL in both, but it appears that backwards compatibility would not be one of those reasons.)

**Comment by seberg** [comment]
Likely, not sure myself about this.

**Comment by tmwright** [comment]
@daniel-perry I would be happy for you to take this over and push for its inclusion in numpy, or indeed scipy if that would be preferable.

However, I should warn you (and @seberg) that the decomposition it yields may not be the one you are expecting.  The LAPACK _sytrf and _hetrf functions perform decompositions by Bunch-Kaufman diagonal pivoting, such that the returned matrix L is not, in general, lower triangular.  In fact L is a product of permutation matrices and lower-triangular matrices (see, e.g., http://www.math.utah.edu/software/lapack/lapack-d/dsytrf.html).

Anyway, from memory, it may be that all that really remains to be done here is to add some tests.  As you can see the code uses the _umath_linalg interface in an analogous fashion to the existing Cholesky code.  Also from memory, scipy uses cython to wrap LAPACK routines now, so this code may not be suitable for inclusion in scipy.

But to reiterate, this is probably not the LDL factorization you are looking for, and I am not sure if it is worth including in numpy/scipy.  I am not aware of any fast, suitably licensed code to perform Cholesky LDL decomposition, which is the factorization people really want.

**Comment by rgommers** [comment]
Agree that Scipy is probably the better place for this. Would be good to not have duplicate implementations in Numpy and Scipy, and if we have to choose then ``scipy.linalg`` should be a superset of ``numpy.linalg`` imho.

**Comment by ilayn** [comment]
LDL factorization is now added to SciPy with the PR linked above.

**Comment by charris** [comment]
Thanks for the heads up @ilayn, closing this.
