### ISSUE TITLE
np.median doesn't preserve Fortran order

### ISSUE THREAD

**Issue by indiajoe** [numpy/numpy#3966]
Output array of median along an axis in multidimentional Numpy arrays defined with order='FORTRAN' doesn't have FORTRAN order.
np.sum(), np.mean() etc preserves this order, but np.median doesn't.

To reproduce the issue try the following.

a=np.ones((10,11,12),order='FORTRAN')
np.isfortran(a)  # Will return True
np.isfortran(np.mean(a,axis=0))  # Will return True
np.isfortran(np.sum(a,axis=0))  # Will return True
But
np.isfortran(np.median(a,axis=0))  # Will return False !!!

Why is only np.median() not preserving the fortran order?
Is this also the reason, unlike mean and sum, median along the **first axis is slower** for Fortran ordered arrays than C ordered arrays?

**Comment by seberg** [comment]
I will close this.  NumPy isn't super reliable about preserving order in general.  If there is a simple clear improvement, I think we may accept it.  (There are many C-functions that are even C-order only.)

OTOH: The original actual seems to return fortran order now ;).
