### ISSUE TITLE
Using numpy.f2py inside python fails because of numpy.distutils.exec_command

### ISSUE THREAD

**Issue by mhubble** [numpy/numpy#4023]
The following does not work on  winXP with Python 2.7.3 and numpy1.7

```
source="""
    subroutine test()
    print *,"Hello world"
    end subroutine
     """
import numpy.f2py as f2py
f2py.compile(source,modulename='untitled')
```

with the error:

```
Could not locate executable C:Python27python.exe
Executable C:Python27python.exe does not exist
```

There is a stackoverflow question about this:
http://stackoverflow.com/questions/19183904/f2py-could-not-locate-executable-cpython27pythonw-exe-executable-cpython27pyt

Somehow exec_command looses the slashes in the python executable path.

**Comment by ronanpaixao** [comment]
Try replacing https://github.com/numpy/numpy/blob/master/numpy/distutils/exec_command.py#L364 from

    argv = shlex.split(command)

to

    argv = shlex.split(command, posix=os.name == 'posix')

**Comment by HaoZeke** [comment]
Can't reproduce. `exec_command` has been deprecated and the OPs versions are EOL.
