### ISSUE TITLE
exotically large data types seem flaky

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#4035]
For example `float128`

```
>>> np.__version__
'1.7.1'
>>> np.array(42, dtype='float128') * long(42)
1764.0
>>> np.array(42, dtype='float128') * 1000111000111000111000111
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'numpy.float128' and 'long'
```

Copied from scipy issue https://github.com/scipy/scipy/issues/3051#issuecomment-28155999

**Comment by seberg** [comment]
Fixed in main by implementing NEP 50 (at least effectively, as it cements the ability to not convert the integer to an array first).
