### ISSUE TITLE
Align=true in dtype constructor does not fully ensure alignment

### ISSUE THREAD

**Issue by fjarri** [numpy/numpy#4084]
Suppose we create the following dtype:

```
>>> dt1 = numpy.dtype(dict(names=['i1','i2'], formats=[numpy.int32, numpy.int32],
... offsets=[0,4], itemsize=12, aligned=True))
>>> dt1.alignment
4
>>> dt1.isalignedstruct
True
```

The problem here is that the itemsize `12` is not actually achievable in C code for these particular fields without an explicit padding. But the `isalignedstruct` field reports that the struct is aligned, which is a bit misleading. There is no way to know which one is true:
1) `itemsize` is consistent with the fields (that is, in C code you
would not need any explicit alignment modifiers)
2) `itemsize` requires an explicit alignment attribute in C code
(e.g, `itemsize=16` would be achievable with an explicit
`__align__(16)` or equivalent applied to the whole struct).
3) `itemsize` is not achievable in C code and requires padding.

So, is the current numpy behavior an intended one, or is it a bug? I would find the following behavior more logical:

```
>>> dt1 = numpy.dtype(dict(names=['i1','i2'], formats=[numpy.int32, numpy.int32],
... offsets=[0,4], itemsize=8, aligned=True))
>>> dt1.base_alignment
4
>>> dt1.alignment
4
>>> dt1.isalignedstruct
True

>>> dt1 = numpy.dtype(dict(names=['i1','i2'], formats=[numpy.int32, numpy.int32],
... offsets=[0,4], itemsize=12, aligned=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: itemsize 12 for this dtype is not achievable without an explicit padding

>>> dt1 = numpy.dtype(dict(names=['i1','i2'], formats=[numpy.int32, numpy.int32],
... offsets=[0,4], itemsize=16, aligned=True))
>>> dt1.base_alignment
4
>>> dt1.alignment
16
>>> dt1.isalignedstruct
True
```

It would be also convenient to have a keyword for the total alignment of the struct (which will affect how it is placed in an encompassing struct):

```
>>> dt1 = numpy.dtype(dict(names=['i1','i2'], formats=[numpy.int32, numpy.int32],
... offsets=[0,4], itemsize=8, alignment=8, aligned=True))
>>> dt1.base_alignment
4
>>> dt1.alignment
8
>>> dt1.isalignedstruct
True
```

**Comment by ahaldane** [comment]
The original behavior makes sense to me. Consider a 'view' of an array:

    >>> dt1 = np.dtype('i4,i4,i4')
    >>> dt2 = np.dtype({'names': ['f0, 'f1'], 'formats': ['i4', 'i4'], 
    ...                 'itemsize': 12, 'aligned': True})
    >>> a = np.ones(5, dt1)
    >>> a.view(dt2)
    array([(1, 1), (1, 1), (1, 1), (1, 1), (1, 1)], 
      dtype={'names':['f0','f1'], 'formats':['<i4','<i4'], 'offsets':[0,4], 'itemsize':12, 'aligned':True})

Thus, `dt2` can be though of as a view into a C-struct described by `dt1`. (This will be important to allow if we want multi-field views). Also, it makes sense to me that `dt2.isalignedstruct` is True: If you tile items of type dt2 in memory starting at a location consistent with `dt2.alignment`, then all fields in all elements are properly aligned.

**Comment by fjarri** [comment]
First, I do not see how my proposal would prevent `view()` from working the way you demonstrated. In fact, `align` doesn't seem to have anything to do with this functionality — you just need `itemsize` of both types to be equal. 

Second, I think the whole `align` thing mixes two issues here. According to the [docs](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.html), `align` (and the corresponding attribute `isalignedstruct`) is supposed to "add padding to the fields to match what a C compiler would output for a similar C-struct." In your example, it should have added padding to `dt2`, because it is not possible to have a struct with only these fields in C and with `sizeof` 12 without padding. On the other hand, you are talking about alignment in memory, which is somewhat separate. 

To put it in a different perspective, what I need in practice is that if some structure has `isalignedstruct = True`, I can just go and build a corresponding C structure, setting `__align__` in C code to the corresponding `alignment` value of `dtype` object, and it will Just Work (tm). As I imagined it was the intent of these keywords and attributes in `dtype`, but perhaps I'm wrong and they serve a very different purpose. To illustrate what I mean, see see [`align() in reikna.cluda.dtypes`](https://github.com/fjarri/reikna/blob/develop/reikna/cluda/dtypes.py#L409).

**Comment by ahaldane** [comment]
Hmm. The documentation about what `align` does (and relatedly, what the `ALIGNED` flag of ndarrays means) is not very good. 

My understanding was that one goal of the `align` keyword was to do exaclty what your `align` function does: Create a dtype that is layed out exactly like a C-struct by padding. This functionality only kicks in if you do not specify the field offsets manually:

    >>> dtype('u1,i4,u1', align=True)
    dtype({'names':['f0','f1','f2'], 'formats':['u1','<i4','u1'], 'offsets':[0,4,8], 'itemsize':12}, align=True)

If you also supply the offsets (as you did in the example above) then the `align` flag only signals numpy to check that the field offsets correspond to their itemsize. In other words, `align` will do what you say as long as you do not manually override it by specifying field offsets and itemsize, like you did in the example.

`align` has a second purpose in numpy: aligned memory copies. Numpy wants to know whether the fields (and total item) of a dtype are aligned to correct byte-boundaries so that it can do quick (eg vectorized) copy operations. By setting `align=True` even when you manually give offsets and itemsize, you are helping numpy know that it will not need to do funny misaligned memory copies. From this point of view, we do not care if the dtype matches a C-struct, we just care that the fields and itemsize match the alignment conditions. That is what numpy is checking for in your example.

I welcome discussion of whether that is the right way to think of it, I'm trying to work though it myself!

I have a PR up right now where I wrote up documentation for structured arrays along these lines, see [here](https://github.com/ahaldane/numpy/blob/fa92d37407de3d3341f63ae165b8b6ec6ee305ef/numpy/doc/structured_arrays.py). (Scroll down to "Automatic Byte Offsets and Alignment"). But based on discussions like this one, I know there are wrong/missing things I have to add!

**Comment by fjarri** [comment]
Well, I'm mostly interested in the `align()` functionality, so if in your PR the `align` keyword will be able to replace it, and `isalignedstruct` will allow one to assert the aligned-ness, then I probably won't need anything else. I'll try to test your PR with my use cases and see if it works for me.

**Comment by ahaldane** [comment]
Oh sorry, that PR doesn't fix anything related to align, I just added documentation on how it works.

**Comment by seberg** [comment]
FWIW, you can actually do this now with `np.promote_types(dt1, dt1)`, which will remove padding fomr a dtype. I don't think this is abug, but a feature request (for which a workaround exists now).

**Comment by fjarri** [comment]
I'm sorry, what exactly do you mean by "this"? The example from the top comment still behaves the same in `numpy` 1.26.3. What `promote_types` does is pack `dt1` minimizing the itemsize (which makes it's name kind of misleading, but that's tangential to this issue). But this issue is about the times when I want to force a specific alignment on a structure (that's what the custom `itemsize` field is for, isn't it?), and that still doesn't work correctly.

**Comment by seberg** [comment]
Yes, it certainly does?  Not sure what you mean, the alignment is 4, that is presumably correct for the int32 contained, I don't see what the size has to do with it.

Maybe `align=True` does refuse if you give `itemsize=13`, so while I bet there are bugs, it still seems to me you want a new feature.

No, the itemsize does *not* align the struct in the way that an alignment attribute in C might.  And NumPy doesn't allow to customize alignment anyway  (nor could it guarantee such an alignment of more than `maxalign_type` in practice at the time).

**Comment by fjarri** [comment]
The underlying issue for me was (and is) to take a `numpy` datatype and map it to a C structure (that is, make sure that its offsets and itemsize are consistent with what a C compiler would set), in the context of GPGPU programming. I assumed the `aligned` attribute is supposed to do that, but evidently I was wrong (I'm not sure what *is* it supposed to do then, since [the docs](https://numpy.org/doc/1.26/reference/arrays.dtypes.html#index-10) don't really explain anything). In any case, I've got a [workaround](https://github.com/fjarri/grunnur/blob/master/grunnur/dtypes.py#L419) written up, so it's not a blocker for me, but the `dtype` docs probably need improvement in this area.

**Comment by seberg** [comment]
I dunno, I am happy to reopen and sure the docs are terrible.  But `dtype.alignment` refers to the alignment for C access of the struct (which refers to the elements.  If the struct is aligned, I would hope that is the same as `AlignOf` will give you in C).

But, when it comes to padding e.g. with itemsize (or just by passing strange `offset` values), you are on your own:  Building a matching C struct for that is indeed going to be hard.

In fact, I suspect that is why `dt1.descr` will add unnamed `V4` padding at the end.

Or maybe I am just all misunderstanding it...

**Comment by fjarri** [comment]
I guess the root of my misunderstanding is that I thought the `aligned` attribute is prescriptive (that is, the dtype will be adjusted on creation, so it would be more like "make aligned"), but it is merely descriptive (so it's on user to ensure that the rest of the inputs are consistent with it, and the meaning actually is "is aligned"), and no checking is performed.

> But dtype.alignment refers to the alignment for C access of the struct (which refers to the elements

But these are two separate things, aren't they? There is the external alignment (for the struct as a whole) and the alignment of the elements.

**Comment by seberg** [comment]
I am not sure I quite understand what you need for struct alignment, to me that can do two things (at least that is how I understood it):
* Tell the compiler that accessing the struct can assume this alignment
* Pad the size of the struct, since otherwise 

And NumPy does the second with `align=True`.  But NumPy's structured dtypes can also have arbitrary holes (and even mangled up field order).

FWIW, we _do_ have an `np.dtypes` namespace now, which probably could hold a helper function to do what you need.  I am not sure I could, because I am still a bit unsure what you need exactly.

Maybe what you need is something like `dtype.descr` where padding is explicitly inserted (and mangled field older is maybe corrected for as via `ignore_order=True` or so)?

**Comment by fjarri** [comment]
> I am not sure I quite understand what you need for struct alignment

I think I mentioned it a couple of times already in this thread: I want to take a `dtype` and "normalize" it so that it is the same from `numpy` perspective (that is, fields and their types are the same), but the offsets and itemsize are consistent with the C compiler logic (without adding padding fields, which may have been too strict of a requirement, but that's how my code works now). This is needed to generate the C code (or rather CUDA/OpenCL) that would be able to take a pointer to a `numpy` array of such structs and work with it.

**Comment by seberg** [comment]
What always confuses me is that you are providing `itemsize=...`.  That part is still a puzzle to me!  Itemsize tells NumPy to explicitly insert padding, and I think that is OK (NumPy does so as well, e.g. if you index away the last field, whether that makes sense or not).

But, now I think I may be seeing the problem:
1. If the user passes a struct with holes, you can't know that unless you check it manually.  `np.promote_types(dt, dt)` will remove them.  I think (but should double check) that `dt == np.promote_types(dt, dt)` will be false if there were any holes.
2. If the user did *not* pass an aligned struct, I think you have to reconstruct it from the names+fields unfortunately with `align=True` and then see if it matches.
3. It is *not* acceptable to me that `np.dtype(dt, align=True)` returns an unaligned struct unmodified.  Maybe an error, but nothing...

But of course there are problems with both.  NumPy structured dtyps are more like named tuples, so order matters and promotion might reorder memory layout to match actual field order.

**Comment by fjarri** [comment]
> What always confuses me is that you are providing itemsize=.... That part is still a puzzle to me! Itemsize tells NumPy to explicitly insert padding, and I think that is OK (NumPy does so as well, e.g. if you index away the last field, whether that makes sense or not).

It may be useful to align, say, a 24-byte struct to 32 bytes in a GPGPU context. You don't need explicit padding for that in C, just the `__align__` attribute. 

> If the user passes a struct with holes, you can't know that unless you check it manually. np.promote_types(dt, dt) will remove them. I think (but should double check) that dt == np.promote_types(dt, dt) will be false if there were any holes.

Honestly I find using `promote_types` for anything other than primitive types extremely confusing and non-intuitive, and the documentation does nothing to indicate the behavior you're describing.  

> If the user did not pass an aligned struct, I think you have to reconstruct it from the names+fields

This is exactly what my custom code I previously referred to does. 

> It is not acceptable to me that np.dtype(dt, align=True) returns an unaligned struct unmodified.

And this is what the initial issue was about.

**Comment by seberg** [comment]
> And this is what the initial issue was about.
 
Maybe we should make a new issue?

My point is that the initial issue talks (mostly) about passing `itemsize` (and `offsets`) together with `align=True`.  And given that:
1. It rejects things that NumPy doesn't considre aligned struct
2. NumPy is OK with padding while still considering something an "alignedstruct" (maybe a misnomer yes).

I suppose you can often get away with using `__align__` to achieve that padding.

> promote_types for anything other than primitive types extremely confusing and non-intuitive, and the documentation does nothing to indicate the behavior you're describing.

Fair, it's useful in NumPy.  The notes do mention the removal of padding, which I think is the main thing.  But, clearly this isn't the intended purpose, just a possible abuse...

**Comment by fjarri** [comment]
The initial issue is about how passing `align=True` neither aligns anything nor performs any checks on the rest of the data (specifically, custom `itemsize` and `offsets`). 

> just checks it to what NumPy considres "aligned struct".

I would be fine with it if it did, but it doesn't. 
```
>>> import numpy
>>> dt1 = numpy.dtype(dict(names=['i1','i2'], formats=[numpy.int32, numpy.int32],offsets=[0,4], itemsize=12, aligned=True))
>>> dt1
dtype({'names': ['i1', 'i2'], 'formats': ['<i4', '<i4'], 'offsets': [0, 4], 'itemsize': 12}, align=True)
```
There is no padding, but the custom `itemsize` is present, and the type is reported as aligned. Which it isn't.

**Comment by seberg** [comment]
It **is** aligned from the way NumPy cares about it:
* All fields are aligned (their offset matches the fields required alignment)
* The `itemsize` is a multiple of the field alignment.

And the `align=True` **does** check those things!  It does **not** care about additinal padding anywehere, and NumPy uses that internally a lot, e.g. if you do:
```
np.dtype("i1,i8,8", align=True)[["f0", "f2"]]
```
(or the equivalent array indexing), the original dtype is aligned (a correct C struct), but the indexed version inherits that alignment so to speak, but has a hole.

You want more than what NumPy considers aligned.  "isalignedstruct" is not a great name, but padding/holes is the way NumPy works with these.  We can drop those holes by reconstructing a dtype (without passing `offsets` or `itemsize`).

---

It isn't aligned to what you care about (I still don't quite understand how `itemsize=12` is supposed to work here, but I don't think).  You want something new, and that is fine.

**Comment by fjarri** [comment]
> It is aligned from the way NumPy cares about it:

Well, in that case, it is not very useful for me, since it's not enough for the structure to be aligned in the C sense. I was hoping that prior to code generation I could just check the `isalignedstruct` of all the involved dtypes, but currently I have to run every dtype through my "aligner" code see if the output is the same as the input. 

> I still don't quite understand how itemsize=12 is supposed to work here

It's supposed to raise an exception, or increase the itemsize to whatever will make it work (16).

**Comment by seberg** [comment]
OK, I think we are at an impasse:  I still would like to help you, but am still suspecting that you are trying to achieve larger than C alignment requirements, maybe because the GPU does have larger alignment requirements in many cases.

I would be truly happy about a new issue.  Because I really think a solution would be good, but I also truly don't think that there is anything wrong with the examples given here.

**Comment by fjarri** [comment]
> but am still suspecting that you are trying to achieve larger than C alignment requirements

That's where I would disagree, I'm trying to achieve parity with C. I honestly don't understand what information does the currently exposed `isalignedstruct` attribute give me, as an external user, if it doesn't mean that I can just take the struct and map it to C. Perhaps it is useful for something internally.

> I would be truly happy about a new issue.

I would love to make one, but clearly idea of how `numpy` is supposed to work does not align with the dev team, so I don't feel like I'm qualified to do it.

**Comment by seberg** [comment]
OK, one last thing from me at least.  NumPy allows (and needs to allow) padding (internal or at the end) that is all there is to it really.  That means the only way I know how to write your initial request into C is: https://godbolt.org/z/oTahPcfcG (i.e. with padding).  That agrees with NumPy: itemsize 12 is fine, and alignment is 4.
