### ISSUE TITLE
savetxt raises a misleading error if array's shape is not rectangular

### ISSUE THREAD

**Issue by sciunto** [numpy/numpy#4125]
Hi,

```
a = np.array([[1., 2.], [1., 2., 3.]]
np.savetxt('/tmp/toto', a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-4a2768c04067> in <module>()
----> 1 np.savetxt('/tmp/toto', a)

/usr/lib/python3.3/site-packages/numpy/lib/npyio.py in savetxt(fname, X, fmt, delimiter, newline, header, footer, comments)
   1061         else:
   1062             for row in X:
-> 1063                 fh.write(asbytes(format % tuple(row) + newline))
   1064         if len(footer) > 0:
   1065             footer = footer.replace('\n', '\n' + comments)

TypeError: a float is required
```

The error is misleading because all elements are made of floats. I agree that the array type is object but it would be easier to debug if we can distinguish between an array with mixed types and an array uncorrectly shaped. 

It took me half an hour to figure out my mistake.

I would be happy to hear your comments.
Thanks.

**Comment by orestisf1993** [comment]
This should be closed I think.

**Comment by eric-wieser** [comment]
This now (1.12.1) gives the error `TypeError: Mismatch between array dtype ('object') and format specifier ('%.18e')`, which seems reasonable enough
