### ISSUE TITLE
1.8 deprecations: Follow-up ticket

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#4131]
Depending on the change, these are probably interesting for removal in 1.10. the non-integer one probably later.

 * [ ] insert and delete changes (0-d input array and boolean indexing array)
 * [ ] non-integer scalar deprecations. (see test_deprecations; PyArray_PyIntAsIntp)
 * [ ] deprecation of `arr.__index__()` for non 0-d arrays. (see test_deprecations)
 * [ ] 'full' and 'economic' modes of qr factorization
 * [ ] nditer `oa_ndim == 0` for no `op_axes`. This needs changing in `numpy/core/src/multiarray/nditer_constr.c`. (see also gh-3104)
 * [ ] `NPY_RELAXED_STRIDES_CHECKING` was introduced as a compile time option in 1.8 (grep code for it).

Please extend the list (or comment) with other deprecations introduced in 1.8.

**Comment by charris** [comment]
Closing. The deprecations are now labeled, so currently open ones will be dealt with in >= 1.11.
