### ISSUE TITLE
1.9 deprecations: Follow-up ticket

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#4132]
Issue to gather deprecations in 1.9 and hints on the actions needed for them:

 * [ ] Indexing deprecations implemented by gh-3798 (see PR and deprecation tests):
    - Multiple `...` usage (`a[..., ...]`).
    - Non-integer array-like usage as index (`a[[1., 2]]`).
 * [ ] Sequence repetition with non-integers (`float64(1) * [2]`). (see gh-4038)
 * [ ] FutureWarning in array_split for empty arrays being replaced. (see gh-4102)
 * [ ] Future and DeprecationWarning for 1-d fancy indexing special cases (see gh-4804)
 * [ ] Comparison deprecations of objects and None. (see gh-3514 and also consider gh-4910)
 * [ ] DEP: deprecate pkgload #5245

**Comment by charris** [comment]
@seberg Many of these deprecations seem to have been made. Could you update this or maybe close it?

**Comment by seberg** [comment]
These were deprecations added that were first released in 1.9, I expect they are all "in progress" currently. But since you marked them in the code, that is maybe more reliably then this kind of issue, so close or not, I don't mind.

**Comment by charris** [comment]
OK, closing.
