### ISSUE TITLE
Enhance: rank correlation for numpy.corrcoef and numpy.cov

### ISSUE THREAD

**Issue by dfrusdn** [numpy/numpy#4147]
Can rank correlation and covariance be added to numpy.corrcoef  and numpy.cov as an enhancement?

Rank correlation is used on non parametric data to measure significance.

We can add a parameter such as 

```
type =  or method =
```

with parameters for pearsons(default), spearman's roh, and kendall's tau. 

Rank correlation and Covariance is available in R

http://stat.ethz.ch/R-manual/R-patched/library/stats/html/cor.html
pearson

**Comment by seberg** [comment]
I will close this, rank correlation, etc. as Josef also seems to think seems a bit special for NumPy. Maybe we could discuss about it, but it seems like most people think it unlikely to fly and keeping a year old issue open seems not very useful.
