### ISSUE TITLE
r/l shift on uint64 scalar and python int failing

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#4151]
#64 bit ubuntu

np.array(123, dtype='uint64') >> np.array(1, dtype='uint64')
61

np.array(123, dtype='uint64') >> 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'right_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

np.version.version
'1.8.0.dev-4a9d23b'

platform.architecture()
('64bit', 'ELF')

**Comment by ianwlarson** [comment]
This issue also affects me.

**Comment by mattip** [comment]
On 1.26 this raises a (conceptually correct) `TypeError("ufunc 'right_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'")`. Closing.
