### ISSUE TITLE
Adding LDFLAGS to NumPy build stage resulted in undefined reference

### ISSUE THREAD

**Issue by jbaksta** [numpy/numpy#4203]
I'm building a new version of NumPy and previously I had always just set LD_LIBRARY_PATH for runtime execution. This time, I wanted to test with some specific optimizations of different BLAS/LAPACK implementations. So I have 2 independent Python versions, and am using MKL on one and OpenBLAS on the other. Python 2.7.6, NumPy 1.8.0.  Compiling with GCC 4.8.2. When I issue the following command:

LDFLAGS="-Wl,-rpath,/apps/OpenBLAS/0.2.8/lib" python setup.py build

I get an error during a linking of the _dotblas.so shared library:

Undefined reference to main ...

I noticed that it was attempting to create a shared library, but missing the -shared flag so, adding that flag to LDFLAGS variable was a workaround, but it looks redundant for other linking steps.

fixed the issue when linking the shared library together. There is no issue if LDFLAGS is not defined, but I can do repeat the build again if the information would be helpful. I think that. I'm not sure if it is just the _dotblas.so part or if other parts were afftect. Hopefully this helps a developer, if need more information, let me know. Not as familiar with distutils as the compilers themselves.

**Comment by andreygursky** [comment]
It seems it is the same bug as reported 5 years ago: [Error building numpy (1.5.1 and 1.6.1rc3) with python2.7 debug](https://mail.scipy.org/pipermail/numpy-discussion/2011-July/057673.html). It is a standard behavior when a project build system appends the content of relevant environment variables (like CFLAGS, LDFLAGS) to the hardcoded ones.

**Comment by mattip** [comment]
we now append to `LD_LIBRARY_PATH`
