### ISSUE TITLE
Allow stacking along arbitrary dimensions

### ISSUE THREAD

**Issue by miguelbarao** [numpy/numpy#4222]
Currently, there are three functions `hstack`, `vstack` and `dstack` which contatenate along the first three dimensions, even if the arrays are of a lower dimension. 
It should also be possible to do the concatenation on any arbitrary nth dimension, expanding the dimensions of the arguments as required. The function `concatenate` does not expand the dimensions automatically. This could be done either by changing `concatenate` to allow this or creating a new function `nstack`.

See [here](http://stackoverflow.com/questions/19636487/concatenation-of-numpy-arrays-of-unknown-dimension-along-arbitrary-axis) for an example.

**Comment by seberg** [comment]
There has been the stack function added by @shoyer, so this is implemented in master.
