### ISSUE TITLE
Array operations may give incorrect answer when NumPy is compiled with Intel compilers and linked against MKL

### ISSUE THREAD

**Issue by leeping** [numpy/numpy#4236]
Hi there,

I'm not sure if this is entirely appropriate because I haven't found a good test case.  I followed the following tutorial to build and install Numpy / Scipy:

http://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl

The only thing I did differently from the tutorial was I specified "--fcompiler=intelem" when building both NumPy and SciPy as opposed to SciPy only.  I thought it was appropriate but maybe that was my mistake?

What occurred next was that my array operations (e.g. dot products) were randomly giving me wrong answers.  The answer would occasionally be right, but sometimes (in ~50% of cases) it was off by a factor of 2 or 3; in other cases it would be off by several orders of magnitude.

The error occurs deep inside my program (ForceBalance) and I can't seem to replicate it with a simple script.  However, I just confirmed that if I reinstall NumPy and SciPy with GCC compilers, the problem goes away.  

Please let me know if you've seen something like this before. Thanks!

**Comment by seberg** [comment]
Closing since there is no example, it is long ago and probably a miscompilation/linking to begin with.
