### ISSUE TITLE
can't see 'recfunctions' after 'import numpy'

### ISSUE THREAD

**Issue by rviger-usgs** [numpy/numpy#4242]
can only see 'recfunctions' after 'import numpy.lib.recfunctions'

http://stackoverflow.com/questions/21413947/adding-a-field-to-a-structured-numpy-array-3

**Comment by npezolano** [comment]
This issue still comes up in version `'1.13.0`.

**Comment by rgommers** [comment]
All examples in `numpy/lib/recfunctions.py` now start with:
```
from numpy.lib import recfunctions as rfn
```
So this is fixed, closing.
