### ISSUE TITLE
std() corner case behaves differently on different windows pythons

### ISSUE THREAD

**Issue by ghost** [numpy/numpy#4250]
xref https://github.com/pydata/pandas/issues/6136

a failing test led us to a case where using `.std(ddof=1)` on a singleton array 
returns some infinity on py2.6.6/64/np1.8.0 but returns `nan` on other windows
pythons and and in linux (at least as far as we know).

This may just be a facts-of-life numerical corner case. Reporting just in case. 
I have data to reliably reproduce the issue.

The numpy binary is from cgohlke's collection.

**Comment by seberg** [comment]
Pandas issue seems closed, and I don't recall ever hearing about it... and the platforms described look very old:  so closing, I don't see what to track down at this point.
