### ISSUE TITLE
False warning for masked arrays: RuntimeWarning: divide by zero encountered in divide

### ISSUE THREAD

**Issue by fkbreitl** [numpy/numpy#4269]
If I divide by a masked array with masked zeros I get a one time runtime warning.
This should not happen, because there is no such division since the zeros are masked:

print 1 / np.ma.masked_equal([1, 0], 0)

/usr/bin/ipython:1: RuntimeWarning: divide by zero encountered in divide
  #! /usr/bin/python
[1 --]

**Comment by MechCoder** [comment]
Has this been fixed? I can no longer reproduce this in NumPy version `1.11.`

```python
1 / np.ma.masked_equal([1, 0], 0)
```

However, I can reproduce this in version 1.10

**Comment by horsto** [comment]
I still get this error (1.13.1)!

**Comment by seberg** [comment]
Nowadays numpy blanket silences these... Not sure that is much better, but I think we can close the issue.
