### ISSUE TITLE
genfromtxt won't unpack if dtype=None

### ISSUE THREAD

**Issue by Gabriel-p** [numpy/numpy#4341]
Not sure if this is a bug or a feature but if I use:

```
f_data = np.genfromtxt('file.dat', dtype=None, unpack=True)
```

where `file.dat` is a standard data file with several columns (ie: http://pastebin.com/ihEW2dxS) the result is not transposed as one would expect having set `unpack=True`.

For example, the line `f_data = np.loadtxt('file.dat', unpack=True)` works as expected.

**Comment by moi90** [comment]
I also experience this. `loadtxt` is a bit more clever:
```
if unpack:
        if len(dtype_types) > 1:
            # For structured arrays, return an array for each field.
            return [X[field] for field in dtype.names]
        else:
            return X.T
```
Why doesn't genfromtxt does this?
