### ISSUE TITLE
DOC: Document ma.filled behavior with non-scalar fill_value 

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#4363]
The ma.filled function and equivalent MaskedArray method are documented as follows:

```
filled(self, fill_value=None) ..

    Parameters
    ----------
    fill_value : scalar, optional
```

However, the current implementation (using np.copyto(.., where=mask)) allows any shape that can be broadcast to the shape of self for fill_value.

This is a useful property and should be documented.

**Comment by yesass** [comment]
HI! I am an Outreachy applicant and I guess, this is the only unassigned issue :) Can I solve it?

**Comment by mattip** [comment]
@yesass yes, and please xref your pull request by putting `#4363` in the comments so others will know you have started working on this.

**Comment by yesass** [comment]
@mattip  Hi! Can you check it out? https://github.com/numpy/numpy/pull/13241

**Comment by eric-wieser** [comment]
Lifting [a comment from #10504](https://github.com/numpy/numpy/pull/10504#issuecomment-362846574):

> I'm wary of documenting this if it's not deliberate or well-supported behavior.
> 
> Arrays with non-scalar fill values also behave poorly upon slicing:
> ```python
> >>> m = np.ma.array(np.zeros((3, 5)), mask=True, fill_value=np.arange(5))
> >>> m.filled()
> array([[0., 1., 2., 3., 4.],
>        [0., 1., 2., 3., 4.],
>        [0., 1., 2., 3., 4.]])
> >>> m[:, :2].filled()
> ValueError: could not broadcast input array from shape (5) into shape (3,2)
> ```
> 
> Fixing this requires copying parts of xarray, which seems super out of scope.
> 
> I think it would be better to just advise using
> ```
> np.where(m.mask, some_broadcasting_fillvalue, m.data)
> ```
> possibly even in a deprecation warning.

**Comment by yesass** [comment]
@eric-wieser Hello!
So as I understood, the doc should be this way:
```
        fill_value : {None, array_like}, optional
        If array_like, the resulting ndarray must be broadcastable
        over `a`.  Arrays with non-scalar fill values are deprecated. The default is None.
```

Also, there should be Deprecation Warning raised like:
```
warnings.warn(
                "Arrays with non-scalar fill values are deprecated. Use "
                "Arrays with scalar values instead".format(self.__name__),
                DeprecationWarning, stacklevel=2)
```

**Comment by eric-wieser** [comment]
I think we should compromise on allowing `filled(...)` to take a broadcasting value, and writing tests for it (it's easy to get right), but deprecating using an non-scalar fill value for `fill_value` (because getting that right is hard).

**Comment by mattip** [comment]
The  deprecation warning should have a comment before it: `# 2019-04-02, 1.17.0, gh-4363`

**Comment by yesass** [comment]
Ok, I will edit the docstring and add deprecation warning. I have several questions:
Is it necessary to add examples in docstrings? 
And should I write a test? If yes, could you tell a specific file that contains tests in this method (to see the examples).

**Comment by mattip** [comment]
It is nice but not required to add examples in the docstrings. Some of them already have examples. If you do modify docstrings, make sure to run `python runtests.py --refguide-check` in addition to `python runtests.py` to make sure they pass tests.

You should always add tests for changed behaviour. Deprecation tests go into `/numpy/ma/tests/test_deprecations.py`, regulare masked array tests go in other files in that directory.
