### ISSUE TITLE
distutils mingw32 mess in msvcr versions

### ISSUE THREAD

**Issue by jove1** [numpy/numpy#4368]
Hi,
I made a simple extension and used numpy.distutils  to package it. Windows binary was built on wine with mingw32. Dependency viewer showed that resulting .pyd depends on:

kernel32.dll
msvcrt.dll
libgcc_s_dw2-1.dll
msvcr90.dll

when I tried to distribute it libgcc_s_dw2-1.dll and msvcrt.dll were not found on
host system (win7).

libgcc_s_dw2-1.dll is linked in due to using g++ as linker even though my code is pure C, setting compiler.linker_so[0] = "gcc" solved this problem.

msvcrt.dll is used as default runtime library by mingw32, currently numpy.distutils tries to replace it by setting -D__MSVCRT_VERSION__=0x0900 and -lmsvcr90. In my case this creates additional (correct) dependency on msvcr90.dll but does not remove msvcrt.dll. 

To achieve correct linking (only) to msvcr90.dll, compiler specs need to be modified, since linking to msvcrt.dll happens implicitly in the internals. (look at the first comment here: http://www.mingw.org/wiki/HOWTO_Use_the_GCC_specs_file#comment-106)

Please consider the pull request #4378. It generates and uses the needed specs modifications. 

```
gcc --version
gcc.exe (GCC) 4.8.1
```

```
sys.version
2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]
```

```
numpy.__version__
1.7.1
```

**Comment by seberg** [comment]
Closing, since the linked PR was closed with a discussion that this is outdated.
