### ISSUE TITLE
parse_flags fails with whitespaces in directories

### ISSUE THREAD

**Issue by MichaelAdello** [numpy/numpy#4382]
Scipy failed to build today when using a self-compiled version of numpy, being in a folder that had some whitespaces in it. I could track the issue back to numpy's parse_flags method, which fails if there are whitespaces in the directory.

The following 5 lines of python code will allow to reproduce the issue:

from numpy.distutils.npy_pkg_config import parse_flags
d = parse_flags("-L/my_folder/without_whitespaces/in_it")
print d
d = parse_flags("-L/my_folder/with whitespaces/in_it")
print d

**Comment by seberg** [comment]
Can't check, but the linked pull request was merged and claims to fix this. Plus it is an old build issue. gh-5765 may also be related.

**Comment by ddasilva** [comment]
Closing a issue logged almost 5 years ago! Truly a success story for issue tracking tools ;)
