### ISSUE TITLE
Deprecate ndim > 2 behavior in dot for 1.9

### ISSUE THREAD

**Issue by ewmoore** [numpy/numpy#4397]
Given that numpy is moving toward allowing its linear algebra routines to operate on (k, m,n) arrays where the array represents a stack of k, (m, n) matrices, it is important to provide a matrix multiply that can operate on such objects without unnecessary contortions.  The current behavior for np.dot with ndim > 2 doesn't provide this. As the first step to providing it, the ndim > 2 behavior should be deprecated in the next release so that it can be changed sooner rather than later. 

I would suggest that this be a 1.9 blocker.

**Comment by mattip** [comment]
Closing this, we cannot deprecate the `dot` multi-dimensional behaviour. `matmul` provides a gufunc-freindly version of matrix multiplication. Please reopen if I missed the point.
