### ISSUE TITLE
Typos in doc of seterrcall

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#4427]
`seterrcall` claims that two arguments are passed to the callback function (in "call" mode): "The first is the type of error (one of “divide”, “over”, “under”, or “invalid”), and the second is the status flag. The flag is a byte, whose least-significant bits indicate the status: [0 0 0 0 invalid over under invalid].  In other words, flags = divide + 2*over + 4*under + 8*invalid."
1. In case of over/underflow, the first argument is "overflow" or "underflow" (instead of "over" or "under").
2. The flags byte should be "[0 0 0 0 invalid overflow underflow divide]"; moreover it is unclear from the docs whether there can be multiple flags set simultaneously (and, if this is indeed possible, what is then the value of the first argument?).

**Comment by aisthesis** [comment]
The "over" and "under" reference variable names in the seterr() function, so I don't think they're wrong here in all cases. What is definitely wrong is that the message to be passed to func as first argument can be any string used as a clarification and doesn't have to have exactly one of the 4 values originally given.

An issue that is unclear to me is whether the 4 alternatives are mutually exclusive. I have trouble thinking of cases where one would want more than 1 flag set, but it does seem possible. And if you can't set more than one flag, then the seterr() function is also not set up well. I suspect that whoever wrote the original code wanted to leave the possibility open that more than one flag might be set even though it seems pretty unusual to do so.

**Comment by charris** [comment]
Closed by #5436.
