### ISSUE TITLE
BUG: Numpy does not recognize 'c' as PEP 3118 buffer format string

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#4469]
One way to demonstrate the bug without writing a C extension is

```
>>> np.core._internal._dtype_from_pep3118('c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpy/core/_internal.py", line 446, in _dtype_from_pep3118
    raise ValueError("Unknown PEP 3118 data type specifier %r" % spec)
ValueError: Unknown PEP 3118 data type specifier 'c'
```

http://legacy.python.org/dev/peps/pep-3118/#additions-to-the-struct-string-syntax

http://docs.python.org/2/library/struct.html#format-characters

**Comment by stephaniemdavis** [comment]
@abalkin @juliantaylor @jarl-haggerty - It appears this issue  was resolved and closed on September 27, 2014. If so, why is it still showing as an open issue? 
Thanks; just feeling my way around...

**Comment by eric-wieser** [comment]
This was fixed in #7803

```python
>>> np.core._internal._dtype_from_pep3118('c')
dtype('S1')
```

Thanks @stephaniemdavis for spotting this.

**Comment by stephaniemdavis** [comment]
Hello Eric and thank you for your response! I'm working my way thru the
intricacies of git/github. As such, is there a way for me to have
determined that this issue had already been addressed and that #7803 was
the issue number associated with the resolution? Thank you.

**Comment by eric-wieser** [comment]
No super easy way. What I did was look at the blame of the file in question on GitHub. I knew what the fix would look like, so found the relevant like, and clicked on the commit sha1 that blame shows beside it. When looking at a commit, GitHub shows the PR it was part of, which is how I found that number.

**Comment by stephaniemdavis** [comment]
@eric-wieser Again, I thank you for this information. It sounds as if I could also do some tracing through the Pull Request meta data and find it that way. You've put me on to learning something else new within github: [tracing changes...](https://help.github.com/articles/tracing-changes-in-a-file/)
This is fun; hope to see you again as I go along on my journey. I take it you're active on the numpy project...
