### ISSUE TITLE
void types print differently in python3 and python2.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#4495]
See test in #388.

In Python2

```
In [22]: np.void(b'123')
Out[22]: 123
```

In Python3

```
>>> numpy.void(b'abc')
[97 98 99]
```

We need to decide which form is preferable. I'm leaning towards the second at this point...

**Comment by mattip** [comment]
Closing. In python3, `np.void(b'abc')` prints `void(b'\x61\x62\x63')` and np.void(b'123')` prints `void(b'\x31\x32\x33')`. `np.void(u"123") raises an error.
Please reopen if this is not the desired behaviour.
