### ISSUE TITLE
structured dtype of the form np.dtype(["name", "str"]) are confusing

### ISSUE THREAD

**Issue by cournape** [numpy/numpy#450]
It is relatively intuitive to want to create a structured array with "str" string for a dtype, which is converted to a "S0" type. I think this should be detected as an error instead ?

**Comment by mattip** [comment]
Can we close this?

**Comment by eric-wieser** [comment]
Same as #8969, I think. Pick one to leave open.

**Comment by eric-wieser** [comment]
Duplicate of #8969, which is described more clearly
