### ISSUE TITLE
Where is the npy format documented?

### ISSUE THREAD

**Issue by larsmans** [numpy/numpy#4523]
The docstring for [`np.save`](https://github.com/numpy/numpy/blob/master/numpy/lib/npyio.py#L404) says:

```rst
Notes
-----
For a description of the ``.npy`` format, see `format`.
```

Where's that?

**Comment by rgommers** [comment]
The NEP is online at http://docs.scipy.org/doc/numpy/neps/npy-format.html, that should be a stable link.

**Comment by rgommers** [comment]
PR to add link to the docs: gh-5413
