### ISSUE TITLE
in python 3 numpy.savetxt can not save matrices with unicode data

### ISSUE THREAD

**Issue by newtover** [numpy/numpy#4543]
**numpy.savetxt** uses under the hood _the numpy.compat.py3k.asbytes_ utility function. In python 3 and above the function forces decoding of the data into 'latin1'. 

```
  File "C:\Python33\lib\site-packages\numpy\lib\npyio.py", line 1073, in savetxt
    fh.write(asbytes(format % tuple(row) + newline))
  File "C:\Python33\lib\site-packages\numpy\compat\py3k.py", line 31, in asbytes
    return str(s).encode('latin1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2009' in position 12: ordinal not in range(256)
```

It would be better to allow overriding the default encoding for the function (or even default it to 'utf-8').

**Comment by charris** [comment]
I think there was discussion of adding an 'encoding' keyword. I don't know what the current status of that discussion is.

**Comment by AlJohri** [comment]
+1 just ran into this issue myself. would love an encoding keyword

**Comment by juliantaylor** [comment]
the encoding keyword was added in 1.14 so the issue should be fixed
