### ISSUE TITLE
1.7 deprecations: Follow-up ticket

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#456]
In 1.9 or thereabouts (it might depend on how long it ends up being between releases etc.), we should follow through and make the various changes that were warned about/deprecated in 1.7.

These include:
* PyArray_Diagonal should begin returning a read-only view on the original array (and another ticket like this should be filed to remind us to switch this to a read-write view at some later date)
* A similar change needs to happen for structured dtype column subsetting.
* The ufunc casting mode should be switch to same_kind (by changing NPY_DEFAULT_ASSIGN_CASTING), and the wacky `NPY_INTERNAL_UNSAFE_CASTING_BUT_WARN_UNLESS_SAME_KIND` casting rule should be removed. (#451)
* "Specifying a custom string formatter with a _format array attribute is deprecated" (not sure what this means, needs looking up)
* "The macros in old_defines.h are deprecated and will be removed in the next minor release (>= 1.8)."
* Disallow passing invalid axis= arguments to concatenate when working with single-dimensional arrays (#440)
* Invalid number of bytes in types, such as "h100", see gh-294.

**Comment by charris** [comment]
These are done

* PyArray_Diagonal should begin returning a read-only view on the original array (and another ticket like this should be filed to remind us to switch this to a read-write view at some later date)
* The ufunc casting mode should be switch to same_kind (by changing NPY_DEFAULT_ASSIGN_CASTING), and the wacky `NPY_INTERNAL_UNSAFE_CASTING_BUT_WARN_UNLESS_SAME_KIND` casting rule should be removed. (#451)
* Invalid number of bytes in types, such as "h100", see gh-294.
* Disallow passing invalid axis= arguments to concatenate when working with single-dimensional arrays (#440)

Not done

* structured dtype column subsetting views is not currently implemented as it is not backward  compatible.   Decision is needed.

In process

* "Specifying a custom string formatter with a _format array attribute is deprecated" (not sure what this means, needs looking up)
* "The macros in old_defines.h are deprecated and will be removed in the next minor release (>= 1.8)."

**Comment by rgommers** [comment]
> "The macros in old_defines.h are deprecated and will be removed in the next minor release (>= 1.8)."

What does "in process" mean here? Those can't be removed yet.

**Comment by charris** [comment]
OK, closing this. The diagonal and structure view remain to be completed so have opened a 1.11 blocker issues for them.
