### ISSUE TITLE
Inconsistent behavior of ufuncs with 0d arrays

### ISSUE THREAD

**Issue by SylvainCorlay** [numpy/numpy#4563]
0d arrays are a special case for ufuncs. Indeed, rather than returning a 0d array, ufuncs return scalars in case of a 0d array inputs.
For example

``` python
print np.exp(np.array(1.0)).__class__
```

returns `<type 'numpy.float64'>`, while 

``` python
print np.exp(np.array([1.0, 2.0])).__class__
```

returns `<type 'numpy.ndarray'>`. 

Ideally ufuncs should return 0d arrays in case of 0d array inputs, and scalars in case of scalar inputs. (array>scalar) returns an array in every cases except in the case of a 0d array, which in my opinion breaks the Zen of Python. 

One of the consequences of the behavior was that `x[x>0]` was giving an error in the case of 0d-arrays, which was solved by PR #3798 by allowing scalar boolean to be used as an index for 0d array.

**Comment by eric-wieser** [comment]
Back to the original issue here - does the following look reasonable?

* `np.square(np.array(1.0))` &rarr; np.array(1.0)
* `np.square(1.0)` &rarr; np.float64(1.0)
* `np.multiply(1.0, 1.0)` &rarr; np.float64(1.0)
* `np.multiply(np.array(1.0), np.array(1.0))` &rarr; np.array(1.0)
* `np.multiply(np.array(1.0), 1.0)` &rarr; ?
* `np.multiply(1.0, np.array(1.0))` &rarr; ?

For those last two - should arrays take priority over scalars, or vice versa?

**Comment by seberg** [comment]
I think the important part is that `np.add.reduce(arr) = scalar` unless axis is not `None`. But I doubt very much that we can get away with changing this funny behaviour anyway.

**Comment by SylvainCorlay** [comment]
> Back to the original issue here - does the following look reasonable?
> 
> - np.square(np.array(1.0)) → np.array(1.0)
> - np.square(1.0) → np.float64(1.0)
> - np.multiply(1.0, 1.0) → np.float64(1.0)
> - np.multiply(np.array(1.0), np.array(1.0)) → np.array(1.0)
> - np.multiply(np.array(1.0), 1.0) → ?
> - np.multiply(1.0, np.array(1.0)) → ?
>
> For those last two - should arrays take priority over scalars, or vice versa? I'd vote in favor of them both returning np.array(1.0)

+1 on returning arrays in the last two cases. Array + scalar gives an array.

**Comment by seberg** [comment]
I'll close this, in favor of Marten's much newer duplicate in gh-24897 (which has more relevant info, I have chipped away in making this actually plausible).
