### ISSUE TITLE
Cannot compile numpy on Mac OSX 

### ISSUE THREAD

**Issue by ziploc1010** [numpy/numpy#4597]
Hi, 

I am trying to compile numpy on Mac OSX Mavericks linked to Intel MKL but I get the following error:

```
python setup.py config --compiler=intelem build_clib --compiler=intelem build_ext --compiler=intelem
```

icc -O3 -g -fPIC -fp-model strict -fomit-frame-pointer -openmp -xhost -shared build/temp.macosx-10.6-intel-2.7/numpy/core/src/dummymodule.o -Lbuild/temp.macosx-10.6-intel-2.7 -o build/lib.macosx-10.6-intel-2.7/numpy/core/_dummy.so
icc: command line warning #10006: ignoring unknown option '-shared'
Undefined symbols for architecture x86_64:
  "_Py_InitModule4_64", referenced from:
      _init_dummy in dummymodule.o
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
icc: command line warning #10006: ignoring unknown option '-shared'
Undefined symbols for architecture x86_64:
  "_Py_InitModule4_64", referenced from:
      _init_dummy in dummymodule.o
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
error: Command "icc -O3 -g -fPIC -fp-model strict -fomit-frame-pointer -openmp -xhost -shared build/temp.macosx-10.6-intel-2.7/numpy/core/src/dummymodule.o -Lbuild/temp.macosx-10.6-intel-2.7 -o build/lib.macosx-10.6-intel-2.7/numpy/core/_dummy.so" failed with exit status 1

**Comment by zeckalpha** [comment]
@ziploc1010: Is this still occurring for you?

**Comment by mattip** [comment]
@ziploc1010 is this still occurring? I am closing, please reopen if needed.
