### ISSUE TITLE
numpy (v1.8.1) gradient exception with shapes (1, N) or (N,1)

### ISSUE THREAD

**Issue by GFuhr** [numpy/numpy#4620]
Hi,

When i try to compute 1D gradient of arrays with shapes (1, N)  or (N,1) an indexerror exception is raised. 

Simple example i have used : 
Python 2.7.6 (default, Mar 22 2014, 15:40:47)
[GCC 4.8.2] 
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> test=numpy.random.rand(5)
>>> numpy.gradient(test)
array([-0.44777757, -0.16156607, -0.08967521,  0.03061334,  0.36522252])
>>> test=numpy.random.rand(5).reshape((5,1))
>>> numpy.gradient(test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 918, in gradient
    out[slice1] = (f[slice2] - f[slice3])
IndexError: index 1 is out of bounds for axis 1 with size 1

Regards,
G.

**Comment by ahaldane** [comment]
The docstring was greatly improved by #6129, so the example code above now says
```
ValueError: Shape of array too small to calculate a numerical gradient, at least two elements are required.
```

Closing.
