### ISSUE TITLE
link to f2py manual pdf is broken 

### ISSUE THREAD

**Issue by vgweirs** [numpy/numpy#4623]
From http://docs.scipy.org, the link to the html version of the guide is fine:
http://docs.scipy.org/doc/numpy-dev/f2py/

But the link to the pdf version:
http://docs.scipy.org/doc/numpy-dev/f2py-1.8.1.pdf
gives a file not found error:
"The requested URL /doc/numpy-dev/f2py-1.8.1.pdf was not found on this server."

**Comment by rgommers** [comment]
This has been fixed.
