### ISSUE TITLE
regression: division by int32(0) and by int64(0) are not consistent 

### ISSUE THREAD

**Issue by gdementen** [numpy/numpy#4636]
Numpy 1.8 (or 1.8.1, I don't know) changed the behaviour for "python_float / np.int32(0)" and np.float(value) / np.int32(0). I am not sure which is the best behaviour (1.7 or 1.8) but I think it should be consistent between int32 and int64. Using np.float64 instead of np.float() does not raise.

``` python
>>> np.__version__
'1.7.0'
>>> 5.0 / np.int32(0)
RuntimeWarning: divide by zero encountered in divide
inf
>>> 5.0 / np.int64(0)
inf
```

``` python
>>> np.__version__
'1.8.1'
>>> 5.0 / np.int32(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero
>>> 5.0 / np.int64(0)
inf
```

**Comment by seberg** [comment]
For int32/int64 this should naturally grow out with phasing out Python 2, so no change will happen here. For float types, I trust that we have other issues open. So closing.
