### ISSUE TITLE
numpy.corrcoef asks for bias/ddof

### ISSUE THREAD

**Issue by grfo** [numpy/numpy#4646]
Not a real issue, but why does numpy.corrcoef ask for bias/ddof?  I don't think it changes the value anyway.

The covariance and variance are proportional to 1/(N-ddof), but since they appear in the same power in the nominator and denominator of the formula for the correlation coefficent they cancel each other.

Beside of pathologic cases where N < ddof they don't play a role here, afais.

Why not just calculate the cov with ddof = 0 (or may be better N-1?) and don't ask for it in corrcoef?

**Comment by bsipocz** [comment]
This issue can probably be closed as ``bias`` and ``ddof`` is now deprecated  arguments.

**Comment by rgommers** [comment]
Indeed, thanks @bsipocz
