### ISSUE TITLE
add useful array searching functions 

### ISSUE THREAD

**Issue by arsenovic** [numpy/numpy#4650]
i have  a couple generic functions for 
- searching arrays by value, and 
- creating slices based on value bounds 

in the scikit-rf package.  are these of any use to numpy? if so i can make a PR. 

https://github.com/scikit-rf/scikit-rf/blob/472c1365260d32c99fcc39c8d933d046245b77f3/skrf/util.py#L73-L141

**Comment by seberg** [comment]
Closing this. I doubt we should include such functions (which does not mean we cannot talk about it). But I think it would be better as a concrete proposal to the mailing list (and since this is years old...).

**Comment by rgommers** [comment]
Thanks for all the triaging @seberg, very useful!
