### ISSUE TITLE
Spurious failures in creating npy_common.h

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#4673]
When creating npy_common.h I see many errors like:
_configtest.c:5:16: error: size of array ‘test_array’ is negative
One source of these is the test for complex compatability in numpy/core/setup.py:

       complex_def = "struct {%s __x; %s __y;}" % (type, type)
        res = config_cmd.check_type_size(complex_def, expected=2*expected[type])

This works better for me:

    res = config_cmd.check_type_size(complex_def, 
                            expected=[2*t for t in expected[type]]) 

Does this need to be a pull request?

**Comment by rgommers** [comment]
@mattip somehow this got missed, that happens with issues (we have a nice big collection of them...). A PR would indeed have been easier. 

This change has been made in aa8a2437. Thanks for your contribution!
