### ISSUE TITLE
Standardise docstrings in random module

### ISSUE THREAD

**Issue by gdementen** [numpy/numpy#4674]
As a followup to PR #4641:  more standardisation in docstrings in the random module would be nice
- descriptions for (other) arguments of many functions do not include the default value
- an "optional" keyword is present in many functions docstrings but not all where it applies
- returns should also be standardized (use the same template) as there are many 
- possibly raises too

**Comment by gmcastil** [comment]
I'll take a look at this.  Are the conventions for docstrings in Cython files the same as normal Python modules?

**Comment by rgommers** [comment]
@gmcastil yes, docstring format is the same.

**Comment by gmcastil** [comment]
Just a quick update - was gone for a bit, but I'm back working on standardizing the docstrings using the suggestions you outlined in PR #4641.

**Comment by rgommers** [comment]
sounds good, looking forward to your PR!

**Comment by giorgiop** [comment]
Is this still open?

**Comment by bashtage** [comment]
@rgommers Is this still needed?  Looks like these have been changed.

**Comment by gdementen** [comment]
Oops, I completely forgot about this issue. Sorry about this. 

As far as I can tell, a lot of progress has been done for most of the points I cited initially, but they are all still relevant (to a **much** lesser extent than when I opened the issue). Quickly scanning the current master, I can still spot a few occurrences of each of the mini-issues I cited. The only point where I do not immediately see progress is on the Raises front, but I personally seldom read them (or write them in my own code)... 

Anyway, given the progress made and that it has already been 3 years without any action on my part and I cannot tell when/if I will follow up on this, you might want to close the issue anyway... I don't really know what is the usual practice in this kind of case.

**Comment by rgommers** [comment]
thanks for pinging. agree that this issue can be closed, docstrings are in pretty good shape. not perfect, but we don't keep issues for that around. for minor formatting or completeness things just sending PRs without issues is better.

> The only point where I do not immediately see progress is on the Raises front, but I personally seldom read them 

``Raises`` is only needed for unusual exceptions or ones that are expected in some cases I'd say, not for things like invalid inputs. Hence most docstrings will not have such a section.
