### ISSUE TITLE
Change RELAXED_STRIDES to not intentionally mangle them up

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#4681]
Currently when RELAXED_STRIDES is active, new arrays which have a dimension with size 1 get a stride of `NPY_MAX_INTP` set to help debugging (since this will almost certainly trigger such bugs for any input array with such a shape, and not juts when one happens to have an input array with funny strides).

In release versions we should probably *not* do this. So for 1.10 I would suggest creating a RELAXED_STRIDES=2 setting where we actually still scramble up the stride, but as default with RELAXED_STRIDES=1 don't in the release. This requires `ctors.h` around line 3718 (`/* For testing purpose only */`) to be changed.

**Comment by charris** [comment]
@seberg See #5996. If that is satisfactory, please close this.
