### ISSUE TITLE
Change numpy.bitwise_and.identity from 1 to None

### ISSUE THREAD

**Issue by xflr6** [numpy/numpy#4696]
I would normally expect ```numpy.bitwise_and.identity``` to be ```0xFFFF...``` 

The current behaviour with ```1``` looks very suprising to me:
```np.bitwise_and.reduce([0b1111]) == 0b1```

I also doubt its usefulness: Why use ```bitwise_and.reduce``` to only process the last bit? ```np.bitwise_and.reduce([0b1111, 0b1010, 0b1110]) == 0b0``` instead of ```0b1010```, also making it inconsistent with ```np.bitwise_and.accumulate([0b1111, 0b1010, 0b1110])[-1]```,
see also http://isntagramm.com/questions/21050875/numpy-bitwise-and-reduce-behaving-unexpectedly

Is it correct that just setting identity to ```None``` would fix these cases?

**Comment by charris** [comment]
Closing, see #7373.

**Comment by ibrahim5253** [comment]
Hi. This is a bit unrelated, but I couldn't find it in docs. What's the behavior of `ufunc.accumulate` if the `identity` for the `ufunc` object is `None` (as is usually the case when such an object is created via `np.frompyfunc`)? 

Thanks,
