### ISSUE TITLE
np.asscalar should pass through scalars

### ISSUE THREAD

**Issue by mforbes** [numpy/numpy#4701]
**Suggestion**
It would be very convenient if `np.asscalar()` would pass through scalars.  The use-case is to ensure that an argument is a scalar, regardless what is passed in (as long as it behaves as a scalar).

``` python
>>> np.asarray(1.0)
1.0
>>> np.asarray(1j)
1j
```

Presently these fail as the implementation simply looks for the `.item()` method, which scalars do not possess:

`````` python
>>> np.asarray(1.0)
AttributeError                            Traceback (most recent call last)
<ipython-input-13-c6bc08be135e> in <module>()
----> 1 np.asscalar(1.0)

.../python2.7/site-packages/numpy/lib/type_check.pyc in asscalar(a)
    461 
    462     """
--> 463     return a.item()
    464 
    465 #-----------------------------------------------------------------------------

AttributeError: 'float' object has no attribute 'item'```
``````

**Rational**
It is common to use `np.asarray()` to ensure that the argument is an array (in the case that it might be a list etc.).  In an analogous use case, it would be useful to be able to use `np.asscalar()` to ensure that an argument is a scalar (as long as it can be converted to a scalar).

**Workaround**
Convert the argument to an array first.

``` python
np.asscalar(np.asarray(x))
```

**Resolution**
Perhaps code like the following would work:

``` python
def asscalar(a):
    try:
        return a.item()
    except AttributeError, e:
        return np.asarray(a).item()
```

**Comment by dpdoughe** [comment]
I'd like to reopen this issue.  This is not fixed in numpy 1.13. It doesn't have the fix mentioned [here](https://github.com/numpy/numpy/pull/5126/files/525574d8da7133d3a4385dc30ada86b9cd1dd360#diff-e6c5cd017deafb358d97bcf913540a13)


```
In [4]: np.asscalar(3.4)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-8460cfbb0c19> in <module>()
----> 1 np.asscalar(3.4)

/home/foo/.virtualenv/myapp/lib/python2.7/site-packages/numpy/lib/type_check.pyc in asscalar(a)
    478 
    479     """
--> 480     return a.item()
    481 
    482 #-----------------------------------------------------------------------------

AttributeError: 'float' object has no attribute 'item'
```




```python
def asscalar(a):
    """
    Convert an array of size 1 to its scalar equivalent.

    Parameters
    ----------
    a : ndarray
        Input array of size 1.

    Returns
    -------
    out : scalar
        Scalar representation of `a`. The output data type is the same type
       returned by the input's `item` method.

    Examples
    --------
    >>> np.asscalar(np.array([24]))
    24

    """
    return a.item()

```

**Comment by eric-wieser** [comment]
Looks like the wrong issue number was used in the commit that closed this

**Comment by eric-wieser** [comment]
We need to make a decision on this before we get even more PRs attempting to "fix" it. To date:

* #11856 
* #10659
* #10256
* #10680 
* #5133
* #5126

**Comment by eric-wieser** [comment]
One of the main problems I have with `asscalar` is that it's just not consistent with `isscalar` - `isscalar(x)` currently does not imply `asscalar(x) is x`:
```python
>>> x = np.float64
>>> isscalar(x)
True
>>> type(x)
<class 'numpy.float64'>
>>> type(asscalar(x))
<class 'float'>
```

Overall, we have three conflicting definitions of scalar:

1. Is a python scalar - the type of object returned from `asscalar`
2. Is a python or numpy scalar - objects meeting `isscalar`
3. is a 0d array - `np.ndim(x) == 0`

Almost every time I see an internal use of `isscalar`, the intention was actually `np.ndim(x) == 0`.
