### ISSUE TITLE
Offset is not updated when slicing memmaps

### ISSUE THREAD

**Issue by GaelVaroquaux** [numpy/numpy#471]
<pre>
>>> import numpy as np
>>> a = np.ones((10, 10))
>>> np.save('a.npy', a)
>>> b = np.load('a.npy', mmap_mode='r')
>>> c = b[3:]
>>> c.offset
80
>>> b.offset
80
</pre>

The offset of c is wrong: it does not take in account the fact that the slicing has changed the offset.

**Comment by Nodd** [comment]
Still true in 1.14.0, but I think it's fine: in the code `offset` is the offset on the underlying mmap object in the file, it's normal that it doesn"t change in a view.
Otherwise what would the offset for `d=b[9:5:-1]` be ?
I think this issue should be closed.

**Comment by mattip** [comment]
@GaelVaroquaux do you agree the offset should remain unchanged?

**Comment by GaelVaroquaux** [comment]
I don't know :).

**Comment by mattip** [comment]
Closing. `offset` is [documented](http://www.numpy.org/devdocs/reference/generated/numpy.memmap.html) at the bottom of the link as "Offset position in the file". Perhaps that could be "Offset position in the underlying file" but I think it is good enough as-is.
