### ISSUE TITLE
Error creating rpm file with setuptools

### ISSUE THREAD

**Issue by rmacian** [numpy/numpy#4797]
I am trying to create a custom RPM file but bdist is not able to create the spec file. Throws that error:

~/rpmbuild/SOURCES/numpy-1.8.1$ python2.7 setup.py bdist_rpm --spec-only --requires python27
Running from numpy source directory.
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)

**Comment by patricksjackson** [comment]
This should be closed by whoever can. @rmacian solves his own issue above.

**Comment by charris** [comment]
Hmm, not sure if there might be a bug somewhere, either in Python docs or numpy distutils, but maybe wait for another report.

Thanks @patricksjackson for the heads up.
