### ISSUE TITLE
numpy.corrcoef not to be used optional variable ddof

### ISSUE THREAD

**Issue by crisrab** [numpy/numpy#4807]
while in the function numpy.cov it has a meaning to specify ddof, since numpy.corrcoef return the correlation coefficient that are the normalized covariance coefficient, ddof is irrelevant.
If I did not misunderstood the meaning of numpy.cov and numpy.corrcoef, I would suggest to remove the optional argument ddof in the function  numpy.corrcoef.

**Comment by seberg** [comment]
This has been deprecated long ago. We have a tracking issue open for ongoing deprecations that can be finished.
