### ISSUE TITLE
Allow linspace to take vectors as parameters

### ISSUE THREAD

**Issue by chrism2671** [numpy/numpy#4818]
It would be very useful to be able to send start, end, and step-size to linspace as vectors, and return a 2d array. This is particularly useful for image warping.

Here's my bespoke implementation, it could probably be tweaked and used here:

def linspace2d(start, stop, iris_height):
  step = (stop - start)/iris_height
  width = len(start)
  x = np.empty((width, 1))
  y = np.arange(0,iris_height)
  xx,yy = np.meshgrid(x, y)
  # y = mx + c
  return yy \* step + start

**Comment by seberg** [comment]
Closing, since there is a newer gh-8839.
