### ISSUE TITLE
numpy.corrcoef returns 1 when applied on 2 matrices.

### ISSUE THREAD

**Issue by guziy** [numpy/numpy#4819]
Please consider the following behaviour (I understand that the input is wrong but the function returns 1 without any error messages):

<pre>
In [1]: import numpy as np

In [2]: x = np.random.randn(20, 10, 10)

In [3]: y = np.random.randn(20, 10, 10)

In [4]: np.corrcoef(x, y)
Out[4]: 1
</pre>

**Comment by seberg** [comment]
This results in an error currently. If another behaviour is desired, please open a new issue.
