### ISSUE TITLE
BUG: reduce does not work on flexible types

### ISSUE THREAD

**Issue by bam54** [numpy/numpy#4860]
I'm using numpy version 1.8.1 on Ubuntu 14.  I've run into the following problem:

> > > a = (1, 2, 3)
> > > np.asarray(a).any()
> > > True
> > > a = ('1', '2', '3')
> > > np.asarray(a).any()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 33, in _any
> > >     keepdims=keepdims)
> > > TypeError: cannot perform reduce with flexible type

This seems like a bug or at the very least, this inconsistency is not apparent from the documentation.

**Comment by seberg** [comment]
Going to close this. Reductions now _can_ work with flexible types, even if that is not yet public API (as part of NEP 42+43).
There is one case remaining, that is not covered yet, and that is when the result type depends on the _number_ of elements in the reduction, i.e. `prod([1*meter] * 1000) == meter**1000`
