### ISSUE TITLE
Bug/misfeature in NumPy's buffer interface implementation for array scalars

### ISSUE THREAD

**Issue by bgrant** [numpy/numpy#4864]
```
$ python3 -V
Python 3.3.2
$ ipython3 --no-banner

In [1]: import numpy

In [2]: numpy.__version__
Out[2]: '1.8.1'

In [3]: a = numpy.ones(1, dtype='f').sum()

In [4]: a.dtype.char
Out[4]: 'f'

In [5]: m = memoryview(a)

In [6]: m.format
Out[6]: 'B'
```

Originally reported here:

https://bitbucket.org/mpi4py/mpi4py/issue/6/incorrect-reduce-result-on-python-3

**Comment by mattip** [comment]
Closing. We now report the correct format on python3, and raise on python2 (which means we no longer report the wrong buffer protocol format.
