### ISSUE TITLE
Issues importing numpy

### ISSUE THREAD

**Issue by rbradfield** [numpy/numpy#4900]
Admittedly I am very new to numpy and python.
I have installed MacPorts and added the XCode Commandline to the terminal and using the suggested command: 
sudo port install py27-numpy py27-scipy py27-matplotlib py27-ipython +notebook py27-pandas py27-sympy py27-nose
I have tired to install numpy. However, whenever I try to import numpy within the terminal I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>
    import add_newdocs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/__init__.py", line 4, in <module>
    from type_check import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/type_check.py", line 8, in <module>
    import numpy.core.numeric as _nx
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/__init__.py", line 5, in <module>
    import multiarray
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/multiarray.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/multiarray.so: no matching architecture in universal wrapper

My version of python (according to terminal when I call python) is:
>>> print (sys.version)
2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Any guidance on this one? What have I done wrong?

**Comment by kasidkhansbp** [comment]
Hi All,

I am also facing the same issue. I installed the numpy by downloading the "numpy-1.6.2-py2.7-python.org-macosx10.3.dmg" and double clicked on it to installed the file. (it had number of steps, I just agreed and clicked continue till it showed me the installation is sucessful)

After this I am opening the IDLE from Python 2.7 in the Application of mac.
I created a new file and when I try to import the numpy , I am getting the above error.
I tried the below code:

"""Softmax."""

scores = [3.0, 1.0, 0.2]

import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    a= np.array(x)
     # TODO: Compute and return softmax(x)
    soft=np.divide(np.exp(a),np.sum(np.exp(a)))
    return soft
  

print(softmax(scores))

Note:
I have checked my .bash_profile and I dnt have any Python path in it.
I tried running the same file from Terminal and got the same error.

Any help is appreciated.

**Comment by matthew-brett** [comment]
In your case, you have run a very old installer which is specific to the Python.org python.  If you have no Python-related PATH setting in `.bash_profile` then the Python you are picking up is the system Python.  You can check this with `which python` - system Python is `/usr/bin/python`.   It's a really bad idea to do new numpy installs with system Python, because they usually don't work - see https://github.com/MacPython/wiki/wiki/Which-Python for details.

I suggest you install Python.org Python, and then you install numpy with `pip install numpy`.

**Comment by kasidkhansbp** [comment]
Hi Matthew.. 

 I downloaded Python.org Python and installed it by double clicking on it and following up till the end. I open the terminal followed the below command
1. Open the Terminal
2. Type "pip install numpy"
result:
kasidkhan ~ $ pip install numpy
Requirement already satisfied (use --upgrade to upgrade): numpy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
3. I tried running the python script from the terminal, same above error message
4. I saw an app "python launcher" in mac. I tried running the python script through this app and error remains the same.

Please help !!

Thanks and Regards,
Md Kasid Khan

**Comment by matthew-brett** [comment]
Right - now `pip` is picking up the old version of numpy you installed with the `dmg` installer before.

Try this to uninstall the old version:

```
rm -rf /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy*
```

Then try `pip install numpy` again.  What do you get?

**Comment by kasidkhansbp** [comment]
Hi Matthew,

Thanks a lot. I uninstalled the numpy and installed it once again with pip command as suggested by you and it is working fine.

Once again, thank u for taking out time for helping me. 

Thanks and Regards,
Md Kasid Khan

**Comment by ayushv005** [comment]
was stuck at this for hours.. and it worked! Thanks a lot. (Removing and installing numpy again)
