### ISSUE TITLE
savetxt cannot handle unicode objects

### ISSUE THREAD

**Issue by robertmuil** [numpy/numpy#4939]
I apologise if I'm using this incorrectly, but I could not find anything relevant in the issue list, and as far as I can work out, this really should work.

If I pass an array with unicode objects (instead of 'string' objects) into savetxt, it bombs out, trying to run the unicode object through the 'asbytes' function.

It does not change things if the dtype of the array is 'U' instead of 'S'.

```
>>> import numpy as np; np.savetxt('test.csv', np.array(['this wörks', u'this dös not']), fmt=['%s'])
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-6a3125624190> in <module>()
----> 1 import numpy as np; np.savetxt('test.csv', np.array(['this wörks', u'this dös not']), fmt=['%s'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)'
```

**Comment by juliantaylor** [comment]
this should be fixed with the textio refactor in 1.14

**Comment by oblek** [comment]
I'm getting this same error using numpy 1.14. also tried with numpy 1.16.
i'm using ubuntu 16.04 and python 2.7.12
`arr = np.array(['abc', 'cdé'], dtype=str)
np.savetxt('test.txt', arr, fmt='%s', encoding='utf8')
`

Curious... 
I tried the same with macOS and it worked fine!

**Comment by gonzalolc** [comment]
I'm getting this same error using numpy 1.14. also tried with numpy 1.16.
i'm using ubuntu 16.04 and python 2.7.12
arr = np.array(['abc', 'cdé'], dtype=str) np.savetxt('test.txt', arr, fmt='%s', encoding='utf8')

Curious...
I tried the same with macOS and it worked fine!

**Comment by chobe111** [comment]
> I'm getting this same error using numpy 1.14. also tried with numpy 1.16.
> i'm using ubuntu 16.04 and python 2.7.12
> arr = np.array(['abc', 'cdé'], dtype=str) np.savetxt('test.txt', arr, fmt='%s', encoding='utf8')
> 
> Curious...
> I tried the same with macOS and it worked fine!

thank you gonzalolc i solve my problem
