### ISSUE TITLE
confusing error message should give more information?

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#4962]
Just to be clear I'm not asking for help setting up numpy.  I'll just uninstall numpy, scipy, cython, and matplotlib, then reinstall all of them from their most recent github sources.

My question is about this weird error message I get, with a screwed up numpy configuration.  The error message does not include a full traceback, and I don't know which module it's talking about.  I suspect it could even be from matplotlib somehow.  Where exactly does it come from, and how could it be made clearer to help people fix their bad numpy installations?

```
$ python -c "import numpy"
RuntimeError: module compiled against API version 9 but this version of numpy is 7
```

**Comment by mattip** [comment]
Closing. Please reopen if you feel there is more to do here.
