### ISSUE TITLE
Boolean array indexing fails silently 

### ISSUE THREAD

**Issue by nhmc** [numpy/numpy#4980]
Indexing with a boolean array of length shorter than the indexed array seems to fail silently:

``` 
>>> a = np.arange(10)
>>> b = np.array([True, False])
>>> a[b]
array([0])
```
Is this behaviour intended? It seems preferable to raise an error if you try to index with a boolean array of a shape that cannot be broadcast to the same shape as the indexed array. For what it's worth, I just spent 2 hours of debugging to find this was the culprit. 

I'm using numpy version 1.8.1

**Comment by seberg** [comment]
Oh, we merged the deprecation, so closing this.
