### ISSUE TITLE
sync percentile behavior with R?

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#4990]
probably the last thing we may want to do before releasing 1.9
1.9 percentile now has a few options for interpolation `linear`, `lower`, `higher`, `nearest` and `midpoint`.
R has 9 types, see http://stat.ethz.ch/R-manual/R-patched/library/stats/html/quantile.html

as far as I can tell only one of them that matches is type 7 in R which is `linear` in our percentile.

The question is do we want to match up some types.
E.g. our `nearest` is not the same as R type 3 as theirs uses even order statistics.
I though their type 5 would be the same as our `midpoint` but it does not give the same result.
And the recommended type 8 is not implemented in numpy at all.

Its not really a blocker was we can always add new types that match R later should it be required, but something that should be discussed.

**Comment by seberg** [comment]
Closing in favor of gh-10736.
