### ISSUE TITLE
[ipo] compilation error

### ISSUE THREAD

**Issue by malreddy** [numpy/numpy#4992]
Hi,
I am trying to compile numpy-1.8.1 with Intel c compiler(icc) with an ipo switch which does inlining as its main feature. But I am facing the below build issue.
I am using Python 2.6.6 version.
<snip>
removing: _configtest.c _configtest.o
C compiler: icc -m64 -fPIC -O3 -ipo -fp-model fast -fomit-frame-pointer -openmp -xhost -DMKL_ILP64

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/usr/include/python2.6 -c'
icc: _configtest.c
removing: _configtest.c _configtest.o
Traceback (most recent call last):
  File "setup.py", line 239, in <module>
    setup_package()
  File "setup.py", line 231, in setup_package
    setup(**metadata)
  File "/home/indiatce/reddy/numpy_15.0/numpy-1.8.1/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/home/indiatce/reddy/numpy_15.0/numpy-1.8.1/numpy/distutils/command/build_clib.py", line 63, in run
    self.run_command('build_src')
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/home/indiatce/reddy/numpy_15.0/numpy-1.8.1/numpy/distutils/command/build_src.py", line 153, in run
    self.build_sources()
  File "/home/indiatce/reddy/numpy_15.0/numpy-1.8.1/numpy/distutils/command/build_src.py", line 170, in build_sources
    self.build_extension_sources(ext)
  File "/home/indiatce/reddy/numpy_15.0/numpy-1.8.1/numpy/distutils/command/build_src.py", line 329, in build_extension_sources
    sources = self.generate_sources(sources, ext)
  File "/home/indiatce/reddy/numpy_15.0/numpy-1.8.1/numpy/distutils/command/build_src.py", line 386, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 463, in generate_config_h
    rep = check_long_double_representation(config_cmd)
  File "numpy/core/setup_common.py", line 168, in check_long_double_representation
    type = long_double_representation(pyod(object))
  File "numpy/core/setup_common.py", line 308, in long_double_representation
    raise ValueError("Could not lock sequences (%s)" % saw)
ValueError: Could not lock sequences (None)

Note: W/o -ipo switch build works fine.
Could you please let me know if there is any work around for this issue ?
Thanks,
Reddy

**Comment by opoplawski** [comment]
PR #5190 does not appear to fix icc -ipo detection for me.

**Comment by malreddy** [comment]
Hi,
To build numpy with icc -ipo option we have to apply following patch in addition to PR #5190.
xiar combines ipo mock objects.

--- a/numpy/distutils/intelccompiler.py 2015-05-20 14:50:25.601413509 +0530
+++ b/numpy/distutils/intelccompiler.py 2015-05-20 14:50:31.272413768 +0530
@@ -16,6 +16,7 @@
         self.set_executables(compiler=compiler,
                              compiler_so=compiler,
                              compiler_cxx=compiler,
+                             archiver='xiar' + ' cru',
                              linker_exe=compiler,
                              linker_so=compiler + ' -shared')

@@ -41,5 +42,6 @@
         self.set_executables(compiler=compiler,
                              compiler_so=compiler,
                              compiler_cxx=compiler,
+                             archiver='xiar' + ' cru',
                              linker_exe=compiler,
                              linker_so=compiler + ' -shared')

Thanks,
Reddy

**Comment by rgommers** [comment]
I'm not sure that hardcoding the archiver to ``xiar`` is the right solution. ``-ipo`` is not enabled by default, so if you enable it you should also do ``export AR=xiar`` probably. Does that work for you?

**Comment by malreddy** [comment]
For some reason export AR=xiar doesn't work for me. Especially when building numpy-1.9.0 package with -ipo option  the -lnpymath -lnpysort libraries are not created by "xiar" , so resulting in below errors during multiarray.so object creation.
<<snip>>>
/tmp/ipo_iccmN1slL3.o:(.data+0x1898): undefined reference to `argbinsearch_right_half'
/tmp/ipo_iccmN1slL3.o:(.data+0x3420): undefined reference to `npy_binsearch_left'
/tmp/ipo_iccmN1slL3.o:(.data+0x3428): undefined reference to `npy_binsearch_right'
/tmp/ipo_iccmN1slL3.o:(.data+0x3430): undefined reference to `npy_argbinsearch_left'
/tmp/ipo_iccmN1slL3.o:(.data+0x3438): undefined reference to `npy_argbinsearch_right'
ld: build/lib.linux-x86_64-2.6/numpy/core/multiarray.so: hidden symbol `binsearch_left_ushort' isn't defined

**Comment by rgommers** [comment]
@malreddy it would be good if you opened a new issue (or PR) for this. I think a PR that would look at the link flags and only change the archiver to ``xiar`` if ``-ipo`` is used would be safer than unconditionally change the archiver like in your diff above - no telling what that could break.

**Comment by rgommers** [comment]
eh, never mind - I thought this was a PR. Let's just reopen this issue.

**Comment by opoplawski** [comment]
FWIW - doesn't setting the AR environment variable to xiar work for that part of the puzzle?

**Comment by rgommers** [comment]
@opoplawski you mean ``if os.environ['AR'] == 'xiar': archiver='xiar cru'``?

**Comment by juliantaylor** [comment]
weird it doesn't already work for for xiar, it works for gcc-ar which is required on older systems for gcc's equivalent -flto, might be worthwhile seeing what the difference is.

**Comment by opoplawski** [comment]
Let's get back to the original issue - long_double check failing with  ValueError: Could not lock sequences (None).  I still see it even with this patch.  I don't think the archiver is involved at all at this point as we're just doing:
icc _configtest.o -o _configtest

Which tellingly doesn't use any special flags - this may be what fixed it for gcc.

But with od -b I don't see the before or after  byte sequences any more.  However, I can get it to appear if I link with -O0.  Perhaps we should just abandon using any passed in or configured compiler flags for this test and just use "-O0"?  I'll note that I don't see the byte sequences with "icc -c -ipo -O0" either, so linking would still be needed if we can't strip the flags.  I don't see a way of specifying the compile flags though.

**Comment by schnaitterm** [comment]
**bump** I am also running into this issue now. I definitely don't think it has anything to do with xiar at this step, but as far as making it the default archiver for the intel c compiler and intel f compiler, I think it's a good idea.  xiar, if it doesn't detect ipo objects, immediately calls whichever `ar` is on the path.   I agree that we should drop the optimization flags on these types of configuration tests

**Comment by schnaitterm** [comment]
I think I found the issue.  `setup_common.py` disables whole program optimization for `check_long_double_representation()` on `MSVC` but not for the Intel compiler, [here](https://github.com/numpy/numpy/blob/d0beca32c97cec5153d6a31c1f9677994abc9352/numpy/core/setup_common.py#L210) so if we add something similar to strip `-ipo` from the icc command line during that test, it should fix it.

**Comment by schnaitterm** [comment]
fix got merged from #10116 so we should probably go ahead and close this! @charris

**Comment by charris** [comment]
@schnaitterm Thanks for the heads up. BTW, the closure would have been automatic if you had added `Closes #4992` or `Fixes #4992` to the commit message of the commit making the fix. Just a note for next time.

**Comment by schnaitterm** [comment]
@charris thanks! still new to this stuff :)
