### ISSUE TITLE
Wierd behaviour by numpy.where() and numpy.any()

### ISSUE THREAD

**Issue by bhanu860** [numpy/numpy#4995]
```
>>> import numpy as np
>>> x = np.array([  9.23673742e-01,   8.94218457e-02,   1.77016515e-01,   1.17322259e-01, 100])
>>> np.where(x<0)
(array([4]),)
>>> np.any(x < 0)
True
>>> if(x[4] < 0):
...  print("True")
... else:
...  print("False")
... 
False
>>> 
```

Please have a look on the above output. The above array doesn't contain any negative values then why does "where()" method says that the last element is negative? Same applies to "any()".

Here are my system details:
Python 3.4.0 (default, Aug 12 2014, 11:20:12)

numpy, Version: 1.8.1

OS Details:
NAME=openSUSE
VERSION="13.1 (Bottle)"
VERSION_ID="13.1"
PRETTY_NAME="openSUSE 13.1 (Bottle) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:13.1"

Thanks.

**Comment by jaimefrio** [comment]
I'm closing this, as it seems resolved.
