### ISSUE TITLE
excessive computation of _mode_from_name

### ISSUE THREAD

**Issue by richardsheridan** [numpy/numpy#4999]
I have an inner loop that calls numpy.convolve quite a lot:

```
def inner_loop(g_z,c_i,g_zs,lambda_array,segments):
        pg_zs=g_zs[:,0]    
        for r in range(1,segments):
            pg_zs=g_z*(c_i[0,segments-r-1]+numpy.convolve(pg_zs,lambda_array,'same'))
            g_zs[:,r]=pg_zs
```

both pg_zs and lambda_array are fairly short (~100,3) but segments is big (~1000). Profiling revealed that substantial time is spent in [_mode_from_name](https://github.com/numpy/numpy/blob/v1.8.1/numpy/core/numeric.py#L814) checking types and calling the "lower" method of strings. I tried to optimize the problem a bit by using 1 instead, but it didn't help much. A pure dictionary approach is a bit faster though:

```
198000 calls:     _mode_from_name()    convolve()
'same':              .315 s              2.888 s
1:                   .181 s              2.816 s
dict:                ----                2.476 s
```

I propose changing any code that executes 

```
mode=_mode_from_name(mode) 
```

to 

```
mode=_mode_from_name_dict[mode]
```

where the dictionary is defined:

```
_mode_from_name_dict = {0 : 0,
                        1 : 1,
                        2 : 2,
                        '0' : 0,
                        '1' : 1,
                        '2' : 2,
                        'v': 0,
                        's' : 1,
                        'f' : 2,
                        'V': 0,
                        'S' : 1,
                        'F' : 2,
                        'valid': 0,
                        'same' : 1,
                        'full' : 2,
                        'Valid': 0,
                        'Same' : 1,
                        'Full' : 2,
                        'VALID': 0,
                        'SAME' : 1,
                        'FULL' : 2}
```

Although it doesn't help too much for my case, it would provide a noticeable boost for even smaller convolutions. The only risk is that strings such as 'Vavoiubaowa3824' will no longer be valid mode inputs. If you really want to capture that behavior too, KeyErrors can be caught with try, and then _mode_from_name(mode) can be called for edge cases.

**Comment by richardsheridan** [comment]
I ended up going with multiarray.correlate, and I suggest others that seem to be bottlenecked by _mode_from_name do the same.

**Comment by mattip** [comment]
Note that `numpy.convolve` and `np.core.multiarray.correlate` do not produce the same output when one of the arguments is complex.
