### ISSUE TITLE
numpy.lib.recfunctions has no reference in the documentation

### ISSUE THREAD

**Issue by kgabor** [numpy/numpy#5008]
A collection of record array functions are available under numpy.lib.recfunctions. The documentation of the functions look OK, however they are completely missing from the documentation (no index entries). I actually discovered the existence of this module by chance... Is this intentional?  

---

I also have some additional source code developed for myself to manipulate record arrays (field cut/copies from one array to another, SQL-like joining of arrays) which I am happy to add possibly to this module if they are welcome. Feel free to comment.

**Comment by mattip** [comment]
They now appear in the documentation but require a separate import. I am closing this issue, further discussion should happen on #6205.
