### ISSUE TITLE
Fix or silence deprecation warnings for bad index calls

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#5009]
See gh-4991 for details. This is about things like 'arr[1<<64]` which gives misleading deprecation warnings even though it is an error anyway.

**Comment by charris** [comment]
@seberg Thoughts on this?

**Comment by charris** [comment]
Pushing this off to 1.11.

**Comment by charris** [comment]
Pushing off to 1.12.

**Comment by seberg** [comment]
Hmmm, well, the original "issue" is gone anyway, since the deprecation is over ;). The current error message could be better, since `1 << 64` is almost an integer, but upon error converting to intp, converting to array is still tried.

**Comment by charris** [comment]
So this can be closed?

**Comment by seberg** [comment]
Yeah, lets close it and wait until someone complains about the confusing error message for out of range python longs.
