### ISSUE TITLE
Record comparison fails for structured arrays

### ISSUE THREAD

**Issue by jbachan** [numpy/numpy#5011]
```
x = np.array([(0,0)], dtype='i,i')
x[0] < x[0]
# result = True
x[0] > x[0]
# result = True

tuple(x[0]) < tuple(x[0]) # the fix
# result = False
```

NumPy 1.8.1
Python 2.7.6

**Comment by eric-wieser** [comment]
In python 3, this just gives `TypeError: unorderable types: numpy.ndarray() < numpy.ndarray()`

This is an artefact of python 2 allowing arbitrary objects to be compared and producing meaningless results.
