### ISSUE TITLE
np.random.multinomial fails for 2D pvals argument

### ISSUE THREAD

**Issue by Jonathan-Livingston-Seagull** [numpy/numpy#5023]
Not able to generate multinomial samples for any given input probability shape. Expecting same kind of behavior as binomial.
Please refer for detail
http://stackoverflow.com/questions/25590694/multinomial-sample-generation-in-python/25591084#25591084
Thanks

**Comment by yoavram** [comment]
To illustrate the problem:

```py
>>> np.random.multinomial(
    1, 
    [0.5, 0.5]
)
```
return either `[1, 0]` or `[0,1]` with equal probabilities.

However,
```py
>>> np.random.multinomial(
    1, 
    [[0.5, 0.5], [0.25, 0.75]]
)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-ae450349452d> in <module>()
      1 np.random.multinomial(
      2     1,
----> 3     [[0.5, 0.5], [0.25, 0.75]]
      4 )

mtrand.pyx in mtrand.RandomState.multinomial (numpy\random\mtrand\mtrand.c:32957)()

ValueError: object too deep for desired array
```
Presumably this should return a 2X2 array, the first row as above (50:50 to get `[0,1]` or `[1,0]`) and the second row should be `[0,1]` with probability 0.75 or `[1,0]` with probability 0.25. Giving the argument `size=(2,2)` doesn't help.

Looping over the `pvals` argument is a solution, but a slow one, and other `np.random` generators support the above use case. For example, `np.random.poisson([1, 2, 3])` generates a 1D array of length 3, and `np.random.poisson([1, 2, 3], size=(5,3))` generates a 2D array of shape (5,3).

**Comment by Jonathan-Livingston-Seagull** [comment]
@yoavram Changed the subject. Thanks.

**Comment by mattip** [comment]
Closing, this now works on both legacy RandomState and the new Generator API code.

**Comment by yoavram** [comment]
Awesome! @mattip can you please refer to a commit or version in which it should work? I'd like to test and use this feature.

**Comment by mattip** [comment]
current HEAD of numpy

**Comment by yoavram** [comment]
is there a wheel I can use? pip installing the HEAD is a pain. thx.

**Comment by tylerjereddy** [comment]
> is there a wheel I can use? pip installing the HEAD is a pain. thx.

Nightly NumPy wheels are built off master branch for Mac & Linux (but not Windows), and uploaded here: http://8b8c47f30575e674b56d-47bd50c35cd79bd838daf386af554a83.r59.cf2.rackcdn.com

So you can try to find the 1.17 NumPy development wheel on that page with an appropriate date stamp in its file name. I can see June 5 date stamps there already, if that is new enough.

`pip install wheel_url` should work, I think

**Comment by ShawnGeller** [comment]
Using numpy version 1.21.5 on Ubuntu 20.04 with python version 3.8.10, this issue still exists for me:

```python
>>> import numpy as np
>>> import numpy.random as npr
>>> rng = npr.default_rng()
>>> rng.multinomial(10, np.array([[.1, .5, .4],[.7,.1,.2]]))
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "_generator.pyx", line 3757, in numpy.random._generator.Generator.multinomial
ValueError: object too deep for desired array
```

Am I doing something wrong?
