### ISSUE TITLE
f2py3 bug error in traslation Fortran to C: array become functions

### ISSUE THREAD

**Issue by EricPascolo** [numpy/numpy#5029]
Hi,
I have a machine with this configuration: Ubuntu 14.04, f2py3 version 2, Python 3.4.0.
I have a fortran module with a subroutine that take in input a 3D matrix and its dimension contained in two array ub(),lb() that specify the range. When I use f2py for create compile module happens a strange thing, gcc return:

error: called object ‘lb’ is not a function or function pointer

``` C
   maps_Dims[0]= ub(1)-(lb(1))+1,maps_Dims[1]=ub(2)-(lb(2))+1;   
```

but If I see the module.c that f2py have generated ub and lb are a pointer:

``` C
  int *ub = NULL;
  npy_intp ub_Dims[1] = {-1};
  const int ub_Rank = 1;
  PyArrayObject *capi_ub_tmp = NULL;
  int capi_ub_intent = 0;
  PyObject *ub_capi = Py_None;
  int *lb = NULL;
  npy_intp lb_Dims[1] = {-1};
```

The problem is that f2py translator replace square bracket with bracket. If I replace in module.c the line with this 

``` C
maps_Dims[0]= ub[1]-(lb[1])+1,maps_Dims[1]=ub[2]-(lb[2])+1;
```

the error disappears.

**Comment by pdebuyl** [comment]
Hi,

The code is not conforming in the first place. The declarations for the dummy variables should be uncommented. Here, the undeclared "ub" and "lb" are assumed to be functions.

It is possible to fix the code to

```.f90
MODULE distro

   IMPLICIT NONE
   PRIVATE
   SAVE

   PUBLIC :: maps_sca

 CONTAINS

SUBROUTINE maps_sca(maps,row_w,col_w,ub,lb,myid,num_of_core)

  IMPLICIT NONE
  INTEGER, INTENT(in) :: ub(3),lb(3),row_w,col_w,myid,num_of_core
  INTEGER, INTENT(inout) :: maps(:,:)
  !f2py depend(ub,lb) maps(lb(1):ub(1), lb(2):ub(2))
  INTEGER :: i,nprow,npcol
  INTEGER :: row_el,col_el,block_num
  INTEGER, ALLOCATABLE :: proc_idx_matrix(:,:)

  ALLOCATE(proc_idx_matrix(nprow,npcol))

  proc_idx_matrix = 0
  maps = 0

  print *, lb
  print *, ub
  print *, lbound(maps)
  print *, ubound(maps)
  print *, shape(maps)

  DEALLOCATE(proc_idx_matrix)

END SUBROUTINE maps_sca

END MODULE distro
```

But the bound will not be set appropriately.

Compiling with `f2py -m distro -c distro.f90` and executing with

```.py
import numpy as np
import distro

maps = np.zeros(shape=(10, 10), dtype=np.int32, order='F')

lb = np.array([2, 2, 2], dtype=np.int32)

ub = np.array([5, 5, 5], dtype=np.int32)

distro.distro.maps_sca(maps, 1, 1, ub, lb, 1, 1)
```

In short:

1. Original code is not correct
2. Intented purpose can probably not be achieved as is. Passing automatically the bounds of an array via dummy arguments is error-prone. Easiest way is to pass 1-index arrays and manually pass the region *or* pass strided arrays.

I suggest to close.

**Comment by charris** [comment]
@pdebuyl Thanks for taking a look. Closing.

**Comment by pdebuyl** [comment]
You are welcome! Thanks for noticing and closing :-)
