### ISSUE TITLE
Incorrect sprintf() result checks in fortranobject.c

### ISSUE THREAD

**Issue by chatcannon** [numpy/numpy#5044]
In f2py/src/fortranobject.c, there are several calls to `sprintf` which follow the pattern

``` c
            if (sprintf(p,"%s - ",def.name)==0) goto fail;
            if (sprintf(p+strlen(p),"no docs available")==0)
                goto fail;
```

From http://linux.die.net/man/3/sprintf

> Return value
> 
> Upon successful return, these functions return the number of characters printed (excluding the null byte used to end output to strings).
> The functions snprintf() and vsnprintf() do not write more than size bytes (including the terminating null byte ('\0')). If the output was truncated due to this limit then the return value is the number of characters (excluding the terminating null byte) which would have been written to the final string if enough space had been available. Thus, a return value of size or more means that the output was truncated. (See also below under NOTES.)
> 
> If an output error is encountered, a negative value is returned.

These `sprintf` calls should check for a negative value, rather than 0.

As an aside, would it be better to use e.g. `snprintf()`? Especially since there doesn't seem to be any other check whether the string will overflow the allocated region. According to the man page, `snprintf` is C99 whereas `sprintf` is C89 and later; does f2py require a C99 compiler?

**Comment by WarrenWeckesser** [comment]
There have been quite a few changes in `fortranobject.c` since this issue was created.  The specific issue reported here no longer exists.
