### ISSUE TITLE
np.pmt causing unnecessary warnings

### ISSUE THREAD

**Issue by alkarimlalani** [numpy/numpy#5046]
Sometimes when using the np.pmt I enter 0.0 as an interest rate like so:

```
np.pmt(0.0, 180, 20000)
```

According to the documentation at http://docs.scipy.org/doc/numpy/reference/generated/numpy.pmt.html there is no restriction against a rate of 0 and the notes section in the docs even address the use case where rate = 0.

Yet every time I run the function with rate set to 0.0 I get the following warning:

```
Warning: invalid value encountered in double_scalars
```

I looked at the source and understand why its throwing the warning, but it really shouldn't since 0 is a valid rate and should handle that case differently.

**Comment by RuchikaChugh** [comment]
> Sometimes when using the np.pmt I enter 0.0 as an interest rate like so:
> 
> ```
> np.pmt(0.0, 180, 20000)
> ```
> According to the documentation at http://docs.scipy.org/doc/numpy/reference/generated/numpy.pmt.html there is no restriction against a rate of 0 and the notes section in the docs even address the use case where rate = 0.
> 
> Yet every time I run the function with rate set to 0.0 I get the following warning:
> 
> ```
> Warning: invalid value encountered in double_scalars
> ```
> I looked at the source and understand why its throwing the warning, but it really shouldn't since 0 is a valid rate and should handle that case differently.

Can you tell which python, numpy version and which OS you are using while running this command.

**Comment by Kai-Striega** [comment]
@charris [pr-5577](https://github.com/numpy/numpy/pull/5577) fixed this. I think this issue should be closed.

**Comment by charris** [comment]
Closing. I note that #6073 is still open.

**Comment by Kai-Striega** [comment]
I think that should be closed too. The last comment (https://github.com/numpy/numpy/pull/6073#issuecomment-248061826) is nearly three years old:

> ☔️ The latest upstream changes (presumably #8050) made this pull request unmergeable. Please resolve the merge conflicts.

so I think we won't see further changes any time soon.
