### ISSUE TITLE
round do not respect ndarray subclass

### ISSUE THREAD

**Issue by ebw44** [numpy/numpy#5068]
round do not respect ndarray subclass in the following case:

``` python
import numpy as np

foo = NpArraySubclass([1,2,3], options)
# this respect the NpArraySubclass, __array_finalize__ of NpArraySubclass get call
print np.round(foo)
print foo.round()
print np.round(foo, 0)
print foo.round(0)
# this do not respect the NpArraySubclass, __array_finalize__ of NpArraySubclass is not call
print np.round(foo, 1)
print foo.round(1)
```

the issue is similar with around. My subclass is almost a copy of 
http://docs.scipy.org/doc/numpy/user/basics.subclassing.html#slightly-more-realistic-example-attribute-added-to-existing-array
and adding __array_wrap__ doesn't change anything as the method is not call.

**Comment by seberg** [comment]
This has been implemented (probably long ago).
