### ISSUE TITLE
numpy.corrcoef RuntimeWarning and NaN (wrong output)

### ISSUE THREAD

**Issue by fnino** [numpy/numpy#5080]
I have found a weird behaviour for numpy.corrcoef .  I reproduce with debian's squeeze python 2.6, on a compiled 2.7 python and in anaconda's 2.7 and 3.3 pythons on MacOSX.
The bug is shown in the following snippet:

---
# !/usr/bin/env python

import numpy as np

wk=np.ones((400,))_0.00282490517428 
print("\nCorrect output for values of ", wk[0])
print("    corrcoef=",np.corrcoef(wk,wk)[0,1])
wk2=wk_1.e13
print("\nCorrect output for values of ", wk2[0])
print("    corrcoef=",np.corrcoef(wk2,wk2)[0,1])
wk2=wk*1.e14
print("\nIncorrect output for values of ", wk2[0])
## print("    corrcoef=",np.corrcoef(wk2,wk2)[0,1])

The result is:

Correct output for values of  0.00282490517428
    corrcoef= 1.0

Correct output for values of  28249051742.8
    corrcoef= 1.0

Incorrect output for values of  282490517428.0
/Users/nino/anaconda/envs/py3/lib/python3.3/site-packages/numpy/lib/function_base.py:1823: RuntimeWarning: invalid value encountered in true_divide
  return c/sqrt(multiply.outer(d, d))
    corrcoef= nan

**Comment by mattip** [comment]
@fnino, this is expected. Closing, please reopen if you wish to explore the issue.
