### ISSUE TITLE
assert_warns does not clear emitted warning registry

### ISSUE THREAD

**Issue by pv** [numpy/numpy#5083]
[assert_warns](https://github.com/numpy/numpy/blob/master/numpy/testing/utils.py#L1568) should clear the emitted warning registry, to ensure that tested warnings are emitted regardless of the order in which tests are run. For instance, if test A emits a warning (e.g. silenced under catch_warnings) and test B tries to test it using `assert_warns`, whether test B passes or not depends on whether it gets run before or after test A --- which is not necessarily deterministic across platforms and Python/Nose versions (e.g. it may pass locally and fail under travis-ci, or vice versa, as happened in some cases in Scipy).

Controlling such interactions between tests is a hassle and should not be necessary. The assumption when using `assert_warns` probably is that all warnings are going to be raised, regardless of whether or not they were raised previously.

Python stores the status indicating whether a warning was previously emitted or not in a global `__warningregistry__` variable. Python's own warning test suite manipulates the warnings state to ensure the tests are reproducible: https://hg.python.org/cpython/file/c0b0dda16009/Lib/test/test_warnings.py#l18 See also https://stackoverflow.com/questions/2390766/how-do-i-disable-and-then-re-enable-a-warning  I'm not fully clear currently on which module's global variable gets which warning, however...

**Comment by seberg** [comment]
Just stumbled on this, I think I will close this, the solution is now the `suppress_warnings` context, IMO. Assert warns actually uses it now, so on up to date numpy this should be solved.

**Comment by seberg** [comment]
Well, I suppose the point of this was slightly different then I just thought, but inside numpy its solved now, and inside scipy I would argue it is basically thought (though the task is not yet finished), but reopen if you like, I am not sure closing was right.
