### ISSUE TITLE
Broken link in HOWTO_DOCUMENT

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#5094]
In the following file:

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

there is a link to http://docs.scipy.org/numpy/Questions+Answers/ which is broken - what should this link now be?

**Comment by phrazzld** [comment]
@astrofrog This appears to be fixed. Can we close the issue?

**Comment by astrofrog** [comment]
Yes, thanks!
