### ISSUE TITLE
khatri-rao product

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5143]
They are asking for this on stackoverflow, and I've also had a need for this myself.  It's an "I want to save a few keystrokes" argument.
http://stackoverflow.com/questions/26153147/special-kind-of-row-by-row-multiplication-of-2-sparse-matrices-in-python
http://en.wikipedia.org/wiki/Kronecker_product#Khatri-Rao_product
In particular the row-wise or column-wise Kronecker product.

**Comment by Joshuaalbert** [comment]
perhaps a rewrite of https://github.com/mrdmnd/scikit-tensor/blob/master/src/tensor_tools.py

**Comment by rgommers** [comment]
Is in SciPy now: https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.khatri_rao.html

Closing, thanks all.
