### ISSUE TITLE
nanmean numpy 1.9.0 Windows 32-bit

### ISSUE THREAD

**Issue by mnfienen** [numpy/numpy#5172]
In some circumstances, the first time nanmean is called in my code, the result is NaN even when there are no NaNs in the array. On the second call, the correct mean (ignoring NaNs) is reported. This behavior is not seen in 64-bit Windows numpy 1.9.0. Tragically, I cannot reproduce it outside of a place buried deep in my code.

**Comment by seberg** [comment]
This could be (have been) a serious bug. But without any followup I doubt we can figure it out and considering there were many fixes since then, I will close this.
