### ISSUE TITLE
Memory leak in pyfragments.swg

### ISSUE THREAD

**Issue by chrislong** [numpy/numpy#5181]
I think I found a memory leak in pyfragments.swg. In both `SWIG_AsVal_dec` fragments, `PyArray_DescrNewFromType` is called but its return value may not get deallocated.

I moved the calls to `PyArray_DescrNewFromType` to right before their value is used (the calls to `PyArray_CastScalarToCtype`) and added a call to `Py_DECREF` and that seems to have fixed my memory leak.

I discovered this in numpy 1.4.1, but I checked 1.9.0 and I think it's still present there.

**Comment by charris** [comment]
Fixed by #11877.
