### ISSUE TITLE
hard crash when using "flat" on non-contiguous size 0 array

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#5195]
``` python
import numpy as np
x = np.zeros((3, 0), order='F')
list(x.flat[:])
```

Running this test-script, I get:

```
[1]    6265 floating point exception  python test-script.py
```

I'm using conda on OS X, with Python 2.7 and numpy 1.9.0.

Yes, this is quite an edge case, but I really did encounter it today :).

**Comment by mattip** [comment]
Fixed on master
