### ISSUE TITLE
Using datetime converters in "numpy.genfromtxt()" results in crashes

### ISSUE THREAD

**Issue by arares** [numpy/numpy#5199]
Suppose I have a CSV file of floats, except one column (e.g. 2nd column) which is a datetime column with dates in the following format: 2014-04-31 01:16:11.745534 . I want to use a converter in order to transform it into epoch values. The datetime may or may not contain milliseconds (it mostly does).

My converter is:

``` python
str2epoch = lambda x: time.mktime(time.strptime(x, '%Y-%m-%d %H:%M:%S.%f')) if '.' in x else time.mktime(time.strptime(x, '%Y-%m-%d %H:%M:%S'))
```

If I do not specify the "dtype" parameter in "genfromtxt()", it is considered float by default. But then npyio.py crashes at line 1763 with this message: "TypeError: object of type 'float' has no len()"
What happens: "genfromtxt()" gets smart and, instead of reading the date as a string into "data", it identifies that the second column is a date and converts it into an epoch value, which is a float. Unfortunately it discards the milliseconds in the process, by the way. Then "len(row[i])" crashes with the error mentioned above because floats do not have lengths.

If I specify "dtype = None", npyio.py crashes at line 1705 with the same message: "TypeError: object of type 'float' has no len()". "genfromtxt()" got smart again and pre-converted the datetime to epoch, which is a float. And again, it lost the milliseconds on the way.

I think "genfromtxt()" should read the columns that are to be converted as strings and let the user convert them as they like.

This is how I used "genfromtxt()":

``` python
myData = np.genfromtxt(filePath, delimiter = ',', skip_header = 1, filling_values = "0", converters = {1: str2epoch})
```

or:

``` python
myData = np.genfromtxt(filePath, delimiter = ',', skip_header = 1, dtype = None, filling_values = "0", converters = {1: str2epoch})
```

One more mention, just in case: defining str2epoch as a proper function instead of a lambda function does not solve the problem.

**Comment by WarrenWeckesser** [comment]
This issue is probably no longer relevant to @arares, and I can't reproduce the problem.  For completeness, I'll verify that with the numpy main development branch, `genfromtxt` with a converter like the one given will convert the timestamps to floating point.

Here's the slightly modified converter, with a fairly common hack to read the microseconds (necessary since the existence of the microseconds field in `time.struct_time` is platform-dependent):
```
import time

def str2epoch(s):
    if '.' in s:
        datetime, micro = s.split('.')
    else:
        datetime = s
        micro = "0"
    dt = time.strptime(datetime, '%Y-%m-%d %H:%M:%S')
    epoch = time.mktime(dt) + int(micro)/1e6
    return epoch
```
Here's an example of reading a data file with that converter.  (Note that the example given, `'2014-04-31 01:16:11.745534'`, is not a valid date, because there is no April 31!)

```
In [10]: np.__version__
Out[10]: '1.22.0.dev0+1698.g79b381f36'

In [11]: !cat data.csv
1.0,2014-04-30 01:16:11.745534,81.5
2.0,2014-05-01 12:34:56.000000,82.5
3.0,2014-05-02 12:34:59.000000,83.5
4.0,2014-05-03 15:00:00.000000,84.5
5.0,2014-05-04 23:10:12.750000,85.5

In [12]: np.genfromtxt('data.csv', delimiter=',', converters={1: str2epoch}, encoding='ascii')
Out[12]: 
array([[1.00000000e+00, 1.39883497e+09, 8.15000000e+01],
       [2.00000000e+00, 1.39896210e+09, 8.25000000e+01],
       [3.00000000e+00, 1.39904850e+09, 8.35000000e+01],
       [4.00000000e+00, 1.39914360e+09, 8.45000000e+01],
       [5.00000000e+00, 1.39925941e+09, 8.55000000e+01]])
```
