### ISSUE TITLE
assert_almost_equal() for floats and assert_array_almost_equal() have different semantics

### ISSUE THREAD

**Issue by edisongustavo** [numpy/numpy#5200]
When using `assert_almost_equal` for floats I get different results when using arrays.

This can be seen by this code:

```
>>> from numpy.testing import assert_almost_equal
>>> assert_almost_equal(1.01, 1.02, 2)
AssertionError:
Arrays are not almost equal to 2 decimals
 ACTUAL: 1.01
 DESIRED: 1.02
>>> assert_almost_equal([1.01, 1.0], [1.02, 1.0], 2)
>>>
```

Looking at `utils.py` the behavior can be explained:

# Float

When comparing using simple float values, this is the `if` that checks if values are equal:
 
`if round(abs(desired - actual), decimal) != 0 :`
https://github.com/numpy/numpy/blob/master/numpy/testing/utils.py#L489

# Array
But when comparing using arrays:

`return around(z, decimal) <= 10.0**(-decimal)`
https://github.com/numpy/numpy/blob/master/numpy/testing/utils.py#L838

Making the same assert behave in different ways.

**Comment by martine** [comment]
I just ran into this, I think.

Another test case:
```
a = 0.38
b = 0.36651039123535156
numpy.testing.assert_almost_equal([a], [b], decimal=2)  # passes
numpy.testing.assert_almost_equal(a, b, decimal=2) # fails
```

**Comment by charris** [comment]
Verified for 1.10-devel.

**Comment by ignatenkobrain** [comment]
The same issue discovered in nipy.

**Comment by charris** [comment]
Someone want to put up a pr? The first form looks cleanest to me.

**Comment by ignatenkobrain** [comment]
@charris done in #6601.

**Comment by amueller** [comment]
We ran into the inverse issue of https://github.com/numpy/numpy/issues/5200#issuecomment-113628675 in scikit-learn. So this is a bug-fix that breaks backwards compatibility?

**Comment by amueller** [comment]
So the resolution of this is that all tests on arrays became one digit stricter, and all tests on scalars stayed the same?

**Comment by charris** [comment]
Note that `round` rounds up, whereas `around` rounds to even.
