### ISSUE TITLE
my norm is slow

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5218]
``` python
def norm_1d_inf_axis_1_ad_hoc():
    return [np.max(np.abs(row)) for row in M]

def norm_1d_inf_axis_1_desired():
    return np.linalg.norm(M, ord=np.inf, axis=1)
```

For `M = np.random.randn(4000, 4000)` the less-vectorized implementation is a bit faster on my machine (3.9 seconds vs. 4.6 seconds for `timeit(..., number=100)`).  This seems weird to me.  Is there a faster way to do what I want?

**Comment by solarjoe** [comment]
Are the things mentioned here (worse shapes) also the reason why calculating the 2-norm using
```python
np.sqrt(((a[...,0]**2+a[...,1]**2+a[...,2]**2)))
```
is significantly faster then the numpy methods

```python
 np.linalg.norm(a, axis=-1)
```
or its underlying
```python
np.sqrt(np.add.reduce((a.conj() * a).real, axis=0))
```
?

**Comment by seberg** [comment]
I am going to close this in favor of gh-18483, since optimized functions such as `maxabs` where mentioned here as well. I expect there is a bit more to this issue, but please reopen or create a new issue it when it comes up again!
