### ISSUE TITLE
BUG: TZ offset of datetime64(t, *) depends on sign of t

### ISSUE THREAD

**Issue by ischwabacher** [numpy/numpy#5220]
It appears that `datetime64(t, unit)` with `unit` smaller than `'D'` yields an object with the system time zone offset when `t >= 0`, but in UTC when `t < 0`.

Given the opacity of the system time zone, it's probably better to avoid using it completely unless it's explicitly requested.

``` python
In [1]: import numpy as np

In [2]: np.datetime64(0, 'ns')
Out[2]: numpy.datetime64('1969-12-31T18:00:00.000000000-0600')

In [3]: np.datetime64(-1, 'ns')
Out[3]: numpy.datetime64('1969-12-31T23:59:59.999999999Z')
```

**Comment by mattip** [comment]
Seems fixed, `np.datetime64(0, 'ns')` now ignores the timezone. Please reopen if needed.
