### ISSUE TITLE
Feature request: Add to numpy simple functions for transform coordinate systems

### ISSUE THREAD

**Issue by espdev** [numpy/numpy#5228]
It would be convenient to have these functions as a part of numpy [mathematical routines](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

**cart2pol** -- Transform Cartesian to polar coordinates

``` python
def cart2pol(x, y):
    theta = np.arctan2(y, x)
    rho = np.hypot(x, y)
    return theta, rho
```

**pol2cart** -- Transform polar to Cartesian coordinates

``` python
def pol2cart(theta, rho):
    x = rho * np.cos(theta)
    y = rho * np.sin(theta)
    return x, y
```

**cart2sph** -- Transform Cartesian to spherical coordinates

``` python
def cart2sph(x, y, z):
    hxy = np.hypot(x, y)
    r = np.hypot(hxy, z)
    el = np.arctan2(z, hxy)
    az = np.arctan2(y, x)
    return az, el, r
```

**sph2cart** -- Transform spherical to Cartesian coordinates

``` python
def sph2cart(az, el, r):
    rcos_theta = r * np.cos(el)
    x = rcos_theta * np.cos(az)
    y = rcos_theta * np.sin(az)
    z = r * np.sin(el)
    return x, y, z
```

**Comment by michaelaye** [comment]
There's 5 different norms implemented in `np.linalg.norm`? I don't see why it then is not also possible to add a few coordinate transformations. Even if done without options, I don't think there's any serious discussion about the validity of the usefulness of a simple  x,y -> r*cos(theta),sin(theta) and its inverse. I would be surprised if this would not be the most used and straight forward coordinate transformation in the world.

**Comment by rgommers** [comment]
> On the other hand, I don't see this fitting in numpy as a handful of standalone functions. Polar coordinates, especially as related to complex numbers, maybe, but spherical coordinates, not really.

Agree with this. Most people seem to be neutral to positive for adding the polar coordinate transforms. So if someone wants to make a concrete proposal and then work on implementing, I think that's welcome. 

Some other thoughts:
- Even for polar, there's some conventions that needs to be clearly documented (angle in degrees or radians, and in interval ``[0, 2pi)`` or ``[-pi, pi)``). I'd probably prefer ``[-pi, pi)``.
- We may consider putting the functions in the ``numpy.lib`` namespace instead of the top level ``numpy`` one.

**Comment by mhvk** [comment]
Found this as we were discussing speed-ups of coordinate transformations in astropy (https://github.com/astropy/astropy/pull/5735) and I wondered what happened with `sincos` (#2626) and "exponent of just an imaginary number" (#5625).

One suggestion might be to start by following `cmath` [1] and introduce `np.rect` and `np.polar`, and work from those (currently, we cover all but these two and `np.phase` of `cmath`).

[1] https://docs.python.org/3.5/library/cmath.html#conversions-to-and-from-polar-coordinates

**Comment by felixdivo** [comment]
3D versions of these helpers would also be helpful.

**Comment by fdkssdks** [comment]
Hello, I am new here and since I am into deep learning, I have this question.
I am using tensorflow to detect objects with USB HD Camera which is stationary. 
I get the coordinates of the center of objects and I want the robot to go to those coordinates, which conversion should I use for this purpose?
On robot I am using XYZ coordinates that is Cartesian per manual. Not sure what coordinates I get from tensorflow, cartesian, pixel or what ?

Thanks

**Comment by charris** [comment]
@fdkssdks Wrong place to ask those questions, try stackoverflow.

**Comment by felixdivo** [comment]
Or here: [Tensorflow API Documentation](https://www.tensorflow.org/api_docs/).

**Comment by tengfeixue-victor** [comment]
> ```python
> np.arctan2
> ```

Hi,
Should "el = np.arctan2(z, hxy)" be "**el = np.arctan2(hxy,z)**" in cart2sph?

Thanks

**Comment by mattip** [comment]
I think we should close this as "good idea, the API should be worked out in a package outside of NumPy and then we can think about merging in". Please reopen (or ask for it to be reopened) if you disagree.

**Comment by s-m-e** [comment]
There are a couple of Python packages in this space providing all sorts bits and pieces. I keep collecting what I need for each project from multiple packages - or implement the conversions myself. The weak spot, other than that this is time consuming, is literally performance. Implementing this sort of thing in pure Python with a bunch of calls into numpy ufuncs introduces significant overhead. This is what is suggested here and this is also what most packages tend to do. I usually compile this stuff down with numba, though again this solution is less than ideal.

If someone tries to implement this as "actual" ufuncs (in just any compiled language) with all bells and whistles of a ufunc (such as the `out` parameter), I could see some serious value - despite the "simplicity" of some of the proposed functions. In either case, if anyone is working on something along those lines, please drop a note here.
