### ISSUE TITLE
numpy 1.9.0 test suite failure on darwin

### ISSUE THREAD

**Issue by howarthjw** [numpy/numpy#5229]
The numpy 1.9.0 release when built against python 2.7.8 on OS X 10.10, produces a single test suite error of the form...

Fortran f77 compiler: /sw/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /sw/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran fix compiler: /sw/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
creating /private/tmp/tmpf6LDcN/private/tmp/tmpaq0PuV
compile options: '-I/private/tmp/tmpf6LDcN/src.macosx-10.10-x86_64-2.7 -I/sw/src/fink.build/root-numpy-py27-1.9.0-1/sw/lib/python2.7/site-packages/numpy/core/include -I/sw/include/python2.7 -c'
gfortran:f77: /private/tmp/tmpaq0PuV/tmpJpFlbH.f
/sw/bin/gfortran -Wall -g -L/sw/lib /private/tmp/tmpf6LDcN/private/tmp/tmpf6LDcN/src.macosx-10.10-x86_64-2.7/_test_ext_module_5403module.o /private/tmp/tmpf6LDcN/private/tmp/tmpf6LDcN/src.macosx-10.10-x86_64-2.7/fortranobject.o /private/tmp/tmpf6LDcN/private/tmp/tmpaq0PuV/tmpJpFlbH.o -L/sw/lib/gcc4.9/lib/gcc/x86_64-apple-darwin14.0.0/4.9.2 -L/sw/lib -lgfortran -o ./_test_ext_module_5403.so
Undefined symbols for architecture x86_64:
  "_PyArg_ParseTupleAndKeywords", referenced from:
      _f2py_rout__test_ext_module_5403_t in _test_ext_module_5403module.o
      _f2py_rout__test_ext_module_5403_func in _test_ext_module_5403module.o
      _f2py_rout__test_ext_module_5403_func0 in _test_ext_module_5403module.o
      _f2py_rout__test_ext_module_5403_t2 in _test_ext_module_5403module.o
      _f2py_rout__test_ext_module_5403_string_callback in _test_ext_module_5403module.o

This is when building against cython 0.21.1. It would appear that the problem linkage...

error: Command "/sw/bin/gfortran -Wall -g -L/sw/lib /private/tmp/tmpVbXjEF/private/tmp/tmpVbXjEF/src.macosx-10.10-x86_64-2.7/_test_ext_module_5403module.o /private/tmp/tmpVbXjEF/private/tmp/tmpVbXjEF/src.macosx-10.10-x86_64-2.7/fortranobject.o /private/tmp/tmpVbXjEF/private/tmp/tmpX78lsh/tmpp73F_P.o -L/sw/lib/gcc4.9/lib/gcc/x86_64-apple-darwin14.0.0/4.9.2 -L/sw/lib -lgfortran -o ./_test_ext_module_5403.so" failed with exit status 1

is missing the required flags to created a shared module on darwin. Is there a patch already in numpy git to fix this?

**Comment by mattip** [comment]
Is this still relevant or can we close it?

**Comment by mattip** [comment]
We now have CI running on mac OS and have not seen this problem. Please reopen if still relevant
