### ISSUE TITLE
TypeError: savez() got multiple values for keyword argument 'file'

### ISSUE THREAD

**Issue by rainwoodman** [numpy/numpy#5243]
savez consumes the 'file' parameter itself, thus the user can not save an array items named 'file'.
This shall probably be documented.

**Comment by melissawm** [comment]
I think this lacks information - I'm not sure I understand how to reproduce this. I propose we close this issue and reopen if necessary.

**Comment by eric-wieser** [comment]
I think this is saying that `np.savez('fname', a=myvarcalleda, file=myvarcalledfile)` fails.

**Comment by eric-wieser** [comment]
Making `file` positional only would fix this, and is unlikely to break anyone

**Comment by pv** [comment]
Maybe a new function (`save_npz`?) with a better API is warranted? The decision to use `**kwargs` keys for array names causes also other problems as it also blocks keyword arguments (e.g. `allow_pickle`).
