### ISSUE TITLE
bitwise_and.identity is incorrect

### ISSUE THREAD

**Issue by bmerry** [numpy/numpy#5250]
In numpy 1.9.0 I get the following
```
>>> numpy.bitwise_and.identity
1
```
But the correct identity should be a pattern of all 1's (for whatever the operation type is). This leads to bizarre results like the following:
```
>>> numpy.bitwise_and.reduce([4])
0
```

**Comment by xflr6** [comment]
If all 1s looks too complicated, please consider removing the identity in the meantime (see also #4696).

**Comment by charris** [comment]
Closing, see #7373.
