### ISSUE TITLE
Incorrect behaviour of numpy.random.binomial

### ISSUE THREAD

**Issue by dpinsard** [numpy/numpy#5254]
When I run the code below after about 29000 iterations the binomial function returns the negative value -2**31. All the previous answers are corrects.

while True:
   k = k+1
   x = binomial(1e10, .5, 1)
   print x
   assert x >= 0, k

**Comment by seberg** [comment]
I will close this, since it was probably fixed. Please reopen if a newer numpy version (e.g. 1.10) still has this problem.
