### ISSUE TITLE
Flatten in Matrix returns 2D array (numpy.matrixlib.defmatrix.matrix)

### ISSUE THREAD

**Issue by juliensiebert** [numpy/numpy#5269]
Hi,
I got a nasty bug / feature that I finally solve. 

I was using the flatten() function that normally returns a 1D array. In some piece of code (not relevant) this function returned 2D array! (This was the problem)
The solution:
I was assuming that I was working with numpy.array but it turns out that I was actually using numpy.matrixlib.defmatrix.matrix. The flatten() function in that case returns 2D array of shape (1,n) with n being the actual number of elements in the numpy.matrixlib.defmatrix.matrix.

Casting everything to numpy.array solves the problem.

The numpy version used is '1.6.2'
The OS version is Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux

Cheers,

Julien

**Comment by Shinigami-shinto** [comment]
> Hi,
> I got a nasty bug / feature that I finally solve.
> 
> I was using the flatten() function that normally returns a 1D array. In some piece of code (not relevant) this function returned 2D array! (This was the problem)
> The solution:
> I was assuming that I was working with numpy.array but it turns out that I was actually using numpy.matrixlib.defmatrix.matrix. The flatten() function in that case returns 2D array of shape (1,n) with n being the actual number of elements in the numpy.matrixlib.defmatrix.matrix.
> 
> Casting everything to numpy.array solves the problem.
> 
> The numpy version used is '1.6.2'
> The OS version is Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux
> 
> Cheers,
> 
> Julien

Thank you so much for providing a solution

**Comment by eric-wieser** [comment]
I think we can close this. We're fixing it by telling users not to use it at all: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html
