### ISSUE TITLE
return type inconsistent between code and docs for PyArray_ITEMSIZE etc

### ISSUE THREAD

**Issue by chatcannon** [numpy/numpy#5286]
In doc/source/reference/c-api.array.rst:

``` rst
.. cfunction:: int PyArray_ITEMSIZE(PyArrayObject* arr)

    Return the itemsize for the elements of this array.
```

In numpy/core/include/numpy/ndarraytypes.h:

``` c
static NPY_INLINE npy_intp
PyArray_ITEMSIZE(const PyArrayObject *arr)
{
    return ((PyArrayObject_fields *)arr)->descr->elsize;
}
```

I personally think that both of these are the wrong type and that it should be `size_t` or some other unsigned type. However, in any case the inconsistency is wrong and should be corrected in one or both places.

I discovered this because `printf("...%d...", PyArray_ITEMSIZE(arr))` is giving compiler warnings in fortranobject.c now that #5270 has been merged.

The same problem also occurs for `PyArray_STRIDE` and `PyArray_DIM` (note the singular i.e. the subscripted functions).

**Comment by seberg** [comment]
The docs are fixed on the initial issue, so closing.
