### ISSUE TITLE
BUG: ascontiguousarray and asfortranarray make 0d scalars into 1d arrays

### ISSUE THREAD

**Issue by tbekolay** [numpy/numpy#5300]
Not sure if this is intended behavior or a bug, but I had been under the assumption that the result of `np.ascontiguousarray` would be the same shape as the input. This is true except in the case of scalars.

``` python
>>> scalar = np.float64(3.0)
>>> np.asarray(scalar).shape  # asarray doesn't change shape
()
>>> np.ascontiguousarray(scalar).shape  # ascontiguousarray does
(1,)
```

If this is what should be expected, it would be helpful to document this in its docstring.

Thanks!

**Comment by charris** [comment]
I think we can change this for the 1.10 betas and see if anything breaks.

**Comment by njsmith** [comment]
Sounds good to me.

**Comment by charris** [comment]
Thinking more, I suspect this is intended for producing arrays for C and, in the case of asfortrancontiguous, for Fortran functions. Allowing zero dimensional arrays might well cause problems.

**Comment by charris** [comment]
Kicking this on to 1.11.

**Comment by GiggleLiu** [comment]
It has to be a bug, now I replaced it with asarray(..., order='F') in my codes.

**Comment by eric-wieser** [comment]
If nothing else, we need to fix the docs:
<pre>
Returns
-------
out : ndarray
    Contiguous array of <b>same shape</b> and content as `a`, with type `dtype`
    if specified.
</pre>

**Comment by eric-wieser** [comment]
How about we just deprecate `np.asfortranarray` and `np.ascontiguousarray` in favor of `np.asarray(..., order='C')` and `np.asarray(order='F')`, since the former are:

* More verbose
* Both broken with respect to their documentation on 0d arrays

**Comment by arogozhnikov** [comment]
> deprecate np.asfortranarray and np.ascontiguousarray in favor of np.asarray(..., order='C') and np.asarray(..., order='F')

Many thanks for your recommendation @eric-wieser , this worked.

Inconsistency with `ascontiguousarray` drives e.g. to problems in python interface for https://github.com/apache/incubator-mxnet/issues/12672, 
so explicit discouraging from using these functions is a wise choice IMO.

**Comment by arogozhnikov** [comment]
@GiggleLiu Are there any known problems with using always `np.asarray` since you made a switch in your code? Thank you.

**Comment by GiggleLiu** [comment]
> @GiggleLiu Are there any known problems with using always `np.asarray` since you made a switch in your code? Thank you.

Sorry, I can not remember, 4 years past...

**Comment by arogozhnikov** [comment]
@eric-wieser 
I have just opened a pull request to depreciate both functions.

I decided to do so after reviewing mxnet:
- they relied on `np.ascontiguousarray`, thus all their arrays were at least 1-dimensional
- seemingly, they decided, 0-dimensional arrays are inexistent, and now mxnet can't work with 0-dimensional arrays, and can't return those, because empty shape was used to pass and indicate errors. I am not sure it is only `np.ascontiguousarray` to blame, but that has its contribution

**Comment by teoliphant** [comment]
These functions should not be deprecated until a major version release.  They should be documented that they always return arrays at least 1-dimension.  They indeed were intended for integrating with compiled code that assumes at least vectors (1-d) arrays.  

These functions can and should have better documentation to state that their output is always at least one-dimensional and that if 0-d arrays need to be handled asarray should be used.

Deprecating these functions could be done, but this should be done as part of a larger effort to shrink the API.

**Comment by rgommers** [comment]
Documentation fix merged, closing. Thanks all!
