### ISSUE TITLE
Docstring for np.linalg.svd still wrong?

### ISSUE THREAD

**Issue by ChristophWiesmeyr** [numpy/numpy#5310]
The docstring of the SVD function in `np.linalg` says

    Factors the matrix `a` as ``u * np.diag(s) * v``, where `u` and `v`
    are unitary and `s` is a 1-d array of `a`'s singular values."

However, this is wrong for non-square matrices `a`. This has been discussed on the mailing list a few years back: [link](http://mail.scipy.org/pipermail/numpy-discussion/2011-January/054722.html). Nevertheless this is still wrong in my version, i.e. 1.9.0.

**Comment by njsmith** [comment]
This was fixed by #5325.
