### ISSUE TITLE
Use an aligned allocator for NumPy?

### ISSUE THREAD

**Issue by sturlamolden** [numpy/numpy#5312]
Regarding the f2py regression in NumPy 1.9 with failures on 32-bit Windows, the question is whether NumPy should start to use an allocator which gives guaranteed alignment.

https://github.com/scipy/scipy/issues/4168

**Comment by pitrou** [comment]
Given the complications with realloc(), it might not be realistic to expect CPython to solve this in the 3.5 timeframe. Numpy should perhaps use its own aligned allocated wrapper instead (which should be able to defer to the PyMem API, and take advantage of tracemalloc, anyway).

**Comment by sturlamolden** [comment]
Code for such an allocator is included above. I don't understand @juliantaylor 's  argument, but he probably understands this better than me. 

I can understand what he meant about calloc though. A calloc is **not** simply a malloc and a memset to zero. A memset will require the OS to fetch the pages before they are needed. AFAIK there is no PyMem_Calloc.

**Comment by pitrou** [comment]
Actually CPython 3.5 has `PyMem_Calloc` and friends.
I think @juliantaylor was considering the implementation case of using OS functions (posix_memalign, etc.). But that doesn't sound necessary.

By the way @sturlamolden, your snippet redefines PyArray_Malloc and friends, but array allocation seems to use PyDataMem_NEW. Am I misunderstanding something?

**Comment by pitrou** [comment]
Another thought is that aligned allocation may be wasteful for small arrays. Perhaps there should be a threshold below which standard allocation is used?
Also, should the alignment be configurable?

**Comment by sturlamolden** [comment]
The allocators are called PyArray_malloc and PyArray_free in Numpy 1.9.

**Comment by pitrou** [comment]
Are you sure? PyArray_NewFromDescr_int() calls npy_alloc_cache() and npy_alloc_cache() calls PyDataMem_NEW().

**Comment by njsmith** [comment]
Numpy has multiple allocation interfaces, and they don't have very obvious
names. PyArray_malloc/free are used for "regular" allocations (e.g. object
structs). Data buffers (ndarray ->data pointers, temporary buffers inside
ufuncs, etc.), however, are allocated via PyDataMem_NEW.

On Thu, Jan 15, 2015 at 7:48 PM, Sturla Molden <notifications@github.com>
wrote:

> The allocators are called PyArray_malloc and PyArray_free in Numpy 1.9.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5312#issuecomment-70149126>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by sturlamolden** [comment]
It seems PyDataMem_NEW calls ```malloc``` in NumPy 1.9.
https://github.com/numpy/numpy/blob/3975e095013119cfdbb9405ca95e6c723eb862d3/numpy/core/src/multiarray/alloc.c

**Comment by charris** [comment]
@njsmith Yeah, we should rationalize the allocation macros some day... I'd start with the one used to allocate dimensions for ndarray (IIRC).

**Comment by pitrou** [comment]
I created PR #5457 with a patch. Feedback on the approach would be nice.

**Comment by njsmith** [comment]
As far as I know there is currently no benefit to using an aligned
allocator in numpy?

On Fri, Jan 16, 2015 at 7:15 PM, Antoine Pitrou <notifications@github.com>
wrote:

> I created PR #5457 <https://github.com/numpy/numpy/pull/5457> with a
> patch. Feedback on the approach would be nice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5312#issuecomment-70305997>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by pitrou** [comment]
With Numba we determined that AVX vector instructions required a 32-byte alignment for optimal performance. If you compile Numpy with AVX enabled (requires specific compiler options, I guess), alignment should make a difference too.

**Comment by njsmith** [comment]
Out of curiosity, do you have any real-world measurements? I ask b/c there
are so many factors that play into these things (different overhead/speed
trade-offs at different array sizes, details of memory allocators -- which
also act differently at different array sizes -- etc.) that I find it hard
to guess whether one ends up with like a 0.5% end-to-end speedup or a 50%
end-to-end speedup or what.

On Fri, Jan 16, 2015 at 8:16 PM, Antoine Pitrou <notifications@github.com>
wrote:

> With Numba we determined that AVX vector instructions required a 32-byte
> alignment for optimal performance. If you compile Numpy with AVX enabled
> (requires specific compiler options, I guess), alignment should make a
> difference too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5312#issuecomment-70315434>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by juliantaylor** [comment]
fwiw on my i5-4210u I see no significant difference between 16 and 32 byte aligned data in a simple load add store test, the minimum cycle count seems lower by 5% but median and 10th percentile is identical to 1%

**Comment by sturlamolden** [comment]
Is that with AVX?

**Comment by pitrou** [comment]
@seibert made some AVX measurements with Numba (i.e. just-in-time code generation with LLVM) using Numpy arrays, I think he'll try to run them again to get precise numbers :-)

**Comment by seibert** [comment]
Here is the benchmark with the latest Numba master:

http://nbviewer.ipython.org/gist/seibert/6957baddc067140e55fe

For float32 arrays (size=10000) executing an `a + b * fabs(a)` operation, we see a 40% difference running on an Intel Core i7-4820K CPU @ 3.70GHz (Ivy Bridge).

(We are a little puzzled that the LLVM 3.5 autovectorizer is not generating any loop peeling code to correct for alignment problems.  I would not be surprised if gcc or clang correct for this.)

For other architectures we are planning to target (like AMD APUs that support the HSA standard), the alignment needs are more strict, with the OpenCL developers suggesting that we have 256 byte alignment for arrays for best performance.

**Comment by juliantaylor** [comment]
I don't know 40% seems like an excessive penalty, I see zero on an i5 (which granted has really poor avx performance)
Could it be that the jit compiler is creating two different versions of the loop?
do you have a assembly level profile of this (e.g. via perf record)?

**Comment by juliantaylor** [comment]
also maybe turbo boost is kicking in on the second loop, disabling it or monitoring he appropiate pmu might be interesting

**Comment by seibert** [comment]
Since we use this system for benchmarking, we have disabled TurboBoost in the BIOS.

The JIT is only running once (once Numba compiles a function for a given set of input types, it caches it), and the JIT triggered prior to benchmarking by Cell 6 in the linked notebook.

I haven't used perf record before, but I'll look into it.  How did you perform your benchmarks?  (I would actually expect Haswell to do better than Ivy Bridge if mis-alignment is triggering some kind of inefficient use of the available L2 cache bandwidth.)

**Comment by seibert** [comment]
This whitepaper from Intel gives a little more information on the alignment issue at the bottom of page 6:

https://software.intel.com/sites/default/files/m/d/4/1/d/8/Practical_Optimization_with_AVX.pdf

> The use of Intel AVX instructions on unaligned 32-byte vectors means that every second load will be across a cacheline split, since the cache line is 64 bytes. This doubles the cache line split rate compared to Intel SSE code that uses 16-byte vectors. A high cache-line split rate in memory-intensive code is extremely likely to cause performance degradation. For that reason, it is highly recommended to align the data to 32 bytes for use with Intel AVX.

Haswell has twice the L2 cache bandwidth of Sandy/Ivy Bridge, so it is possible the effect of misaligned arrays is not significant on Haswell...

**Comment by juliantaylor** [comment]
my simple benchmark is this:
https://gist.github.com/juliantaylor/68e578d140f427ed80bb
would be interesting to see on that i7

**Comment by pitrou** [comment]
Results on a Core i5-2500K (Sandy Bridge):
4644 6656 7704 10100

**Comment by pitrou** [comment]
Please note I had to add a longer warmup phase at start of the benchmark:
```
    for (i=0; i<10; i++)
        add(a, 1);
```

**Comment by juliantaylor** [comment]
is that an average/median/...? that looks quite significant, seems intel worked on it a lot for the haswell.

**Comment by pitrou** [comment]
It's the near-stable output from the benchmark after some hundreds of runs in a loop.

**Comment by pitrou** [comment]
I added a packed SSE2 implementation, here are the figures (i5-2500K):
4660 6492 7468 5108 10096 
(32B aligned AVX, 16B (un)aligned AVX, 8B (un)aligned AVX, aligned SSE2, scalar)

Here is the updated source: https://gist.github.com/pitrou/892219a7d4c6d37de201

**Comment by pitrou** [comment]
Near-stable output from a Core i5-4200U (laptop Haswell CPU):
4120 4152 4148 4260 7308 

At least here, misaligned AVX isn't worse than SSE2 with similar alignment.

**Comment by sturlamolden** [comment]
Here is from my MBP (quad-core i7, 2.4 GHz, not Haswell AFAIK):
5060 4932 5820 5704 5040

I had to change ```avxintrin.h``` to ```immintrin.h``` and  compile with Intel icc because gcc 4.8.1 refused to compile the code (and so did clang).

**Comment by pitrou** [comment]
@sturlamolden , may it be possible that icc is vectorizing the scalar loop (the last result in the numbers)?

**Comment by pitrou** [comment]
(note that the benchmark would probably put more pressure on the cache subsystem if the addition involved two separate input arrays)

**Comment by sturlamolden** [comment]
I have no idea.

**Comment by bashtage** [comment]
@sturlamolden This code was very useful for interfacing with some SSE2. 

I had one issue on Windows (all versions of VC, including 2015) don't like this line

```C
memmove((void*)p2,p1+old_offs,n);    
```

since they don't support pointer arithmetic on `void*`.  As a short term fix I cast it to `char*` to do the math.  This probably isn't right - do you have a better idea what would make it compile correctly on Windows?

**Comment by sturlamolden** [comment]
My bad. Pointer arithnetics on void* is illegal C. Casting to char* is correct.

**Comment by nachiket** [comment]
How do I get 64-byte aligned numpy arrays? The 'ALIGNED' addresses from https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.require.html seem to align at some different length. Is there some user-configurable parameter for alignment length?

**Comment by eamartin** [comment]
I made my own (Python) aligned allocator that works on (unaligned) memory provided by Numpy.

```python
import numpy as np

def empty_aligned(n, align):
    """                                                                                                                                     
    Get n bytes of memory wih alignment align.                                                                                              
    """

    a = np.empty(n + (align - 1), dtype=np.uint8)
    data_align = a.ctypes.data % align
    offset = 0 if data_align == 0 else (align - data_align)
    return a[offset : offset + n]


def test(n):
    for i in xrange(1, 1024):
        b = empty_aligned(n, i)

        try:
            assert b.ctypes.data % i == 0
            assert b.size == n
        except AssertionError:
            print i, b.ctypes.data % i, b.size
```

Perhaps a Python workaround like this is a viable solution?

**Comment by sturlamolden** [comment]
@eamartin This is about the NumPy's internal C code and the interface code to Fortran generated by f2py (also C code). For obvious reasons, the implementation of NumPy cannot depend on NumPy. 

You can use that trick for your Python projects, though.

**Comment by njsmith** [comment]
@sturlamolden: It might help @nachiket and others in a similar situation though.

**Comment by eamartin** [comment]
@sturlamolden : I didn't read closely enough to realize this was about C internals.

However, offering better alignment options in the Python interfaces would be valuable for developing Python interfaces between Numpy and native libraries that have alignment requirements on arguments.

**Comment by sturlamolden** [comment]
I am not against offering better alignment options in the Python interfaces 🙂

**Comment by eamartin** [comment]
The "Python aligned allocator" solution I suggested is a hack. I think offering alignment in the Python interfaces would be nice, but the right way to do that would be to handle alignment at the C level.

**Comment by vellamike** [comment]
This feature would be very helpful to me. I am using an FPGA device where the DMA controller requires 64-byte aligned data to be used, this speeds up my code by 40x. I suspect that @nachiket has the same problem as me. I wrote something similar to what @eamartin is using but this is a bit of a hack.

**Comment by mborgerding** [comment]
I definitely encourage 64 byte alignment: 
1. that is the cache line size
2. it is suitable for any SIMD alignment up to AVX512

**Comment by aldanor** [comment]
Here we are almost 5 years later.

Any thoughts on making this (64-byte alignment in particular) a standard feature?..

**Comment by bashtage** [comment]
This cython code is now in NumPy.  Of course, this doesn't change the default.

**Comment by hmaarrfk** [comment]
my 2cents: An aligned allocator would help when interface with hardware devices and kernel level calls. These interfaces might benefit from aligning the buffers to pages.

**Comment by mattip** [comment]
In merging randomgen, we gained [`PyArray_realloc_aligned`](https://github.com/numpy/numpy/blob/v1.17.2/numpy/random/src/aligned_malloc/aligned_malloc.h) and friends. Should we move these routines into `numpy/core/include` ?

**Comment by jakirkham** [comment]
That would certainly be useful, @mattip. Would it be possible to access this functionality from Python as well?

**Comment by sturlamolden** [comment]
> In merging randomgen, we gained [`PyArray_realloc_aligned`](https://github.com/numpy/numpy/blob/v1.17.2/numpy/random/src/aligned_malloc/aligned_malloc.h) and friends. Should we move these routines into `numpy/core/include` ?

Ripped off my code, did ya?  😂

**Comment by sturlamolden** [comment]
It looks like I am no loger contributor for the code I have written for NumPy 🧐:

https://github.com/numpy/numpy/blob/v1.17.2/numpy/_build_utils/src/apple_sgemv_fix.c
https://github.com/numpy/numpy/blob/v1.17.2/numpy/random/src/aligned_malloc/aligned_malloc.h

**Comment by bashtage** [comment]
Probably got lost at some point in the move from randomgen to numpy. I
think I had a record that this was yours.

**Comment by mattip** [comment]
what was the original source of the code?

**Comment by sturlamolden** [comment]
The link is dead, but it was adapted from an aligned malloc that looked like this:

https://tianrunhe.wordpress.com/2012/04/23/aligned-malloc-in-c/

**Comment by bashtage** [comment]
It was a github post from Sturla. There was no original code file.

**Comment by sturlamolden** [comment]
https://github.com/numpy/numpy/issues/5312#issuecomment-64529217

**Comment by bashtage** [comment]
This is for the aligned malloc.

**Comment by pitrou** [comment]
Does everyone who contributes 50 lines of code to Numpy get a dedicated copyright header? I might go through my contributions and see if any applies :-)

**Comment by rgommers** [comment]
> It looks like I am no longer contributor for the code I have written for NumPy 🧐:

You are and will always be:) 

> Does everyone who contributes 50 lines of code to Numpy get a dedicated copyright header? I might go through my contributions and see if any applies :-)

Nope. We try to avoid encoding such things inside the source code, since that will always be wildly incomplete and hard to maintain. We do ask people to list themselves in `THANKS.txt`; I'm looking at a better alternative to that, because that file often gives merge conflicts.

**Comment by seberg** [comment]
I am going to close the issue.  Happy about a new one though!  (It seems most of the discussion is simply outdated and should be re-evaluated based on Matti's work in gh-17582)

Note that it is now – with the next release – possible to write a context manager outside NumPy to swap in an aligned allocator.  Which alleviates the need to push it directly into NumPy and gives a chance for much clearer testing of the benefits.

**Comment by jakirkham** [comment]
Also there is a tracking issue with follow up items ( https://github.com/numpy/numpy/issues/20193 ). One of them is allocators with specific alignment ( https://github.com/numpy/numpy/issues/20193#issuecomment-952653423 )
