### ISSUE TITLE
Use GPU on Raspberry Pi for FFT

### ISSUE THREAD

**Issue by PanderMusubi** [numpy/numpy#5348]
Please, use GPU on Raspberri Pi for FFT.

Implement it in such way that calling FFT functionality explicitely has to request processing on GPU via a parameter. The default will remain processing on CPU.

For more information, see http://www.aholme.co.uk/GPU_FFT/Main.htm and for source code, see https://github.com/raspberrypi/userland/tree/master/host_applications/linux/apps/hello_pi/hello_fft

**Comment by mattip** [comment]
Closing. Use of the GPU is currently out of scope for NumPy.
