### ISSUE TITLE
ndarray astype docstring is missing 'new in version' hints

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5352]
http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

It would have been nice to have known that `astype` doesn't do keyword arguments in numpy 1.5.1 before writing https://github.com/scipy/scipy/pull/4238 without having to go exploring in http://docs.scipy.org/doc/numpy-1.5.x/reference/generated/numpy.ndarray.astype.html or digging through github history.

As always pull requests are welcome!

**Comment by mattip** [comment]
While technically we still don't have version info on the keywords, I am closing this as water under the bridge. Please reopen, or even better submit a PR.
