### ISSUE TITLE
numpy.packbits doesn't accept a bool array

### ISSUE THREAD

**Issue by Dunes** [numpy/numpy#5377]
Example of problem

    data = numpy.array([True])
    byte_values = numpy.packbits(data)

This results with an exception -- TypeError: Expected an input array of integer data type. This seems to go against the documentation of the function, which says it expects a 'binary-valued array'.

To make this work, you need to first convert the data type of the array to int, which seems redundant. eg.

    byte_values = numpy.packbits(numpy.array(data, dtype=int))

A better use case of where I encountered the problem.

    data = numpy.random.sample(1024)
    truth_values = data >= threshold
    bits = numpy.packbits(truth_values)

**Comment by LuisBL** [comment]
This is a real problem, because packbits is the only workaround the fact that np.array of boolean use 8bit by boolean. This is a limit to how compact a memory structure can be.

**Comment by LuisBL** [comment]
In [8]: x = np.array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1], dtype=np.bool)
    
    In [9]: px = np.packbits(x)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-9-326e19e2360b> in <module>()
    ----> 1 px = np.packbits(x)
    
    TypeError: Expected an input array of integer data type
    In [10]

**Comment by LuisBL** [comment]
There is a question on SO about this issue http://stackoverflow.com/questions/34511362/packing-numpy-boolean-array-needs-tons-of-ram

**Comment by alimuldal** [comment]
@LuisBL  There is no need to cast the input array to the native `int` dtype - you can avoid generating a copy simply by viewing it as `np.uint8`, which also uses a single byte per element, e.g.:

```python
px = np.packbits(x.view(np.uint8))
```

Having said that, I agree that it would be cleaner if `np.packbits` accepted booleans directly.

**Comment by jaimefrio** [comment]
That feature was added in #5319, it does work in current master, so closing this.
