### ISSUE TITLE
Implement new-style buffer protocol for scalars on Py2

### ISSUE THREAD

**Issue by inducer** [numpy/numpy#5381]
Numpy scalars have an old-style buffer interface:

```
Python 2.7.8 (default, Sep  9 2014, 22:08:43) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> buffer(np.int32(15))
<read-only buffer for 0x11b1810, size -1, offset 0 at 0x7f3208c1f6f0>
```

but not a new-style one.

```
>>> memoryview(np.int32(15))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot make memory view because object does not have the buffer interface
```
#4864 makes it sound like this inconsistency would eventually be addressed.

[PyOpenCL](/pyopencl/pyopencl) and [PyCUDA](/inducer/pycuda) are [affected](/inducer/pycuda/pull/60) by this.

**Comment by mattip** [comment]
`memoryview(np.int32(15))` works. If there is still missing buffer protocol functionality with scalars please open a new issue

**Comment by inducer** [comment]
Thanks. I can confirm that this appears to be fixed.
