### ISSUE TITLE
matrix nuclear norm

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5395]
Numpy already has [many norms](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html) but in my opinion it needs one more: `linalg.norm(x, ord='nuc')`!  The matrix nuclear norm (also known as the trace class norm and the Ky-Fan r-norm) is one of three familiar [Schatten norms](http://en.wikipedia.org/wiki/Matrix_norm#Schatten_norms), two of which are already available in numpy.norm as the Frobenius norm (Schatten 2-norm) and the spectral norm (induced 2-norm, Schatten inf-norm).  The nuclear norm is the Schatten 1-norm, and can be implemented as simply the sum of singular values of a matrix.

**Comment by bsipocz** [comment]
#5396 has addressed this
