### ISSUE TITLE
np.random.multinomial gives negative samples with large n

### ISSUE THREAD

**Issue by tjlane** [numpy/numpy#5404]
I haven't had a chance to track down the offending code yet, but this had me scratching my head a few times. When the number of samples is large, `np.random.multinomial` can return a (forbidden) negative number:

Code to produce the issue:

```
import numpy as np

n = 1e12 # this must be big
p = np.random.randn(100)
p /= p.sum()

for i in range(10):
    x = np.random.multinomial(n, p)
    assert np.all(x >= 0), 'fail'
```

my numpy version:
```
$ python -c "import numpy; print numpy.__version__"
1.8.1
```

**Comment by saketkc** [comment]
@tjlane Won't p have negative values in it? They can't be an input for `multinomial(size, pval)` anyway, right?

**Comment by tjlane** [comment]
Ah yes, I was being an idiot. Apologies. If you change `randn` to `rand`, it works!
