### ISSUE TITLE
masked array docs example

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5406]
In following [example](http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html#numerical-operations) in the docs

> Numerical operations can be easily performed without worrying about missing values, dividing by zero, square roots of negative numbers, etc.:

``` python
>>> import numpy as np, numpy.ma as ma
>>> x = ma.array([1., -1., 3., 4., 5., 6.], mask=[0,0,0,0,1,0])
>>> y = ma.array([1., 2., 0., 4., 5., 6.], mask=[0,0,0,0,0,1])
>>> print np.sqrt(x/y)
[1.0 -- -- 1.0 -- --]
```

I get a warning with a development version of numpy:

``` python
>>> import numpy as np
>>> import numpy.ma as ma
>>> x = ma.array([1., -1., 3., 4., 5., 6.], mask=[0,0,0,0,1,0])
>>> y = ma.array([1., 2., 0., 4., 5., 6.], mask=[0,0,0,0,0,1])
>>> print np.sqrt(x/y)
__main__:1: RuntimeWarning: invalid value encountered in sqrt
[1.0 -- -- 1.0 -- --]
```

I am not suggesting that the behavior of `numpy.ma` should be changed, but maybe the example could be modified to avoid the warning or the warning could be included in the example output?

**Comment by charris** [comment]
Should be `ma.sqrt(x/y)`.

**Comment by njsmith** [comment]
The fact that that warning is printed is a well known issue that regularly
confuses people. (There might well be some other issues filed about it
already.) I think everyone agrees that it's a bug. So it feels a little
weird to enshrine it in the docs. OTOH it's been there for years and no
evidence that it'll go away anytime soon...

**Comment by rgommers** [comment]
The most annoying thing is that the warnings are so inconsistent. The divide by zero isn't warned about, while if you do ``x.data / y.data`` you do get that warning. I'd say treat this as a bug and either always or never warn. Either way keep the warning out of the docs (add ``np.seterr(all='ignore')`` if needed).

**Comment by abalkin** [comment]
@njsmith - what is the "well known issue"?  Is it that `np.sqrt` prints a warning where `ma.sqrt` does not?

I think the confusing part is that `np.sqrt` accepts masked arrays in the first place.  I would much rather see an immediate type error in this case.

**Comment by njsmith** [comment]
> @njsmith - what is the "well known issue"? Is it that np.sqrt prints a
warning where ma.sqrt does not?

Yes.

> I think the confusing part is that np.sqrt accepts masked arrays in the
first place. I would much rather see an immediate type error in this case.

Way too late for that I'm afraid.
