### ISSUE TITLE
ma.median: cannot perform reduce with flexible type

### ISSUE THREAD

**Issue by dieterv77** [numpy/numpy#5424]
Consider the following snippet:
```python
import numpy as np
import numpy.ma as ma

x = np.zeros((10,))
ma.median(x, axis=None)
```

The last line throws a
```python
TypeError: cannot perform reduce with flexible type
```
using version 1.9.1, but works with versions prior to 1.9.0 (i didn't try 1.9.0).  Is this expected behavior?

Many thanks

**Comment by charris** [comment]
I get the same as @argriffing with 1.9.0 and 1.9.1
```
In [1]: x = np.zeros((10,))

In [2]: np.ma.median(x, axis=None)
Out[2]: 
masked_array(data = 0.0,
             mask = False,
       fill_value = 1e+20)

In [3]: np.__version__
Out[3]: '1.9.0'
```
I suspect something is off in your install. Can you do a clean install?

**Comment by dieterv77** [comment]
Strangely enough, when I do a clean install of 1.9.1 on a machine running Ubuntu 12.04, i continue to have the same problem.  However, i tested a clean install of 1.9.1 on Ubuntu 14.10 and did not encounter the error.

Just to verify that the install process on 12.04 was working OK, i did a clean install of 1.8.1 on Ubuntu 12.04, and then my problem went away.

**Comment by charris** [comment]
Curious. Where is your source coming from?

**Comment by dieterv77** [comment]
Installing via easy_install:

easy_install --upgrade --user numpy

**Comment by dieterv77** [comment]
For what it's worth, here's the stacktrace:

Traceback (most recent call last):
  File "nptest.py", line 4, in <module>
    print np.ma.median(x, axis=None)
  File "/home/foo/.local/lib/python2.7/site-packages/numpy-1.9.1-py2.7-linux-x86_64.egg/numpy/ma/extras.py", line 675, in median
    out=out, overwrite_input=overwrite_input), copy=False)
  File "/home/foo/.local/lib/python2.7/site-packages/numpy-1.9.1-py2.7-linux-x86_64.egg/numpy/lib/function_base.py", line 2890, in median
    overwrite_input=overwrite_input)
  File "/home/foo/.local/lib/python2.7/site-packages/numpy-1.9.1-py2.7-linux-x86_64.egg/numpy/lib/function_base.py", line 2803, in _ureduce
    r = func(a, **kwargs)
  File "/home/foo/.local/lib/python2.7/site-packages/numpy-1.9.1-py2.7-linux-x86_64.egg/numpy/lib/function_base.py", line 2944, in _median
    return mean(part[indexer], axis=axis, out=out)
  File "/home/foo/.local/lib/python2.7/site-packages/numpy-1.9.1-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 2727, in mean
    out=out, keepdims=keepdims)
  File "/home/foo/.local/lib/python2.7/site-packages/numpy-1.9.1-py2.7-linux-x86_64.egg/numpy/core/_methods.py", line 66, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: cannot perform reduce with flexible type

**Comment by maniteja123** [comment]
The exception is raised [here](https://github.com/numpy/numpy/blob/v1.9.1rc1/numpy/core/src/umath/ufunc_object.c#L3720)

For numpy 1.9.1,
The function ``PyArray_ISFLEXIBLE(mp)``, where ``mp`` is a ``PyArray_Object``, is returning 
1 in Ubuntu 12.04, while 0 on Ubuntu 14.04 for x = np.zeros(10)
0 on both for x = np.ma.zeros(10).
This is irrespective of ``dtype``.

The explanation about ``PyArray_ISFLEXIBLE`` should answer the problem.

**Comment by maniteja123** [comment]
It looks like ``PyArray_ISFLEXIBLE`` is a macro. 
[PyArray_ISFLEXIBLE](https://github.com/numpy/numpy/blob/v1.9.1rc1/numpy/core/include/numpy/ndarraytypes.h#L1667)
[PyTypeNum_ISFLEXIBLE](https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/ndarraytypes.h#L1636)

**Comment by charris** [comment]
Try deleting the previous numpy directory in your python site-directory and then doing an install. Might also to a `locate` to see if there are different numpy versions floating about in different spots.

**Comment by charris** [comment]
Also, what is the compiler version? There may be a compiler problem somewhere.

**Comment by dieterv77** [comment]
Thanks everyone for the various responses and hints, your time is much appreciated.

I did delete any other numpy versions in my .local before installing the new one, but that doesn't seem to help.  I also verified that both np.__file__ and ma.__file__ point to the correct version in .local.
The stock ubuntu numpy is also installed in the system folder.  I'll see if i can find a vm or something where i can uninstall that and try again.   It's something i can test, but would not be a viable solution.

Here's the compiler version (default gcc on Ubuntu 12.04):
> gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by dieterv77** [comment]
I reproduced the problem after that installing 1.9.1 on a 12.04 vm that did not have any version of numpy installed yet.  Same version of gcc

**Comment by charris** [comment]
I'm actaullly suspicious of `easy_install`, but you would need to get the source from someplace definitive. Maybe you can clone the github repo.

**Comment by dieterv77** [comment]
Cleaned up my .local, then cloned the repo, followed by git checkout v1.9.1 and python setup.py install --user

Unfortunately, i still get the same result.

**Comment by charris** [comment]
Darn. I'm out of ideas apart from the compiler. Did you try with master?

**Comment by charris** [comment]
Oh, and what optimization level are you compiling at?

**Comment by dieterv77** [comment]
I'm not doing anything specific with compiler settings.  How would i go about configuring those?
I'll try master too.

**Comment by charris** [comment]
If you do `python setup.py install --user &> install.log` you should be able to look through the log for the compile options, something like `-O`. Might also check `env` to see if there is a `CFLAGS` variable. I usually compile with
```
CFLAGS=" -Wall -Wstrict-prototypes -march=native -O2 -pipe -fomit-frame-pointer -fno-strict-aliasing"
```

**Comment by dieterv77** [comment]
Thanks again for your suggestions.

I first compiled master without changing compiler settings, the problem remains.  Next i tried the CFLAGS settings you proposed (after deleting build folder and cleaning out .local), same result.  Sorry i don't have something more promising to report.

**Comment by charris** [comment]
Thanks for all your work trying to track this down. I'm all out of ideas too.

**Comment by dieterv77** [comment]
I poked around a bit more, and wanted to report what i found in case someone with more knowledge of numpy internals than me (which is just about anyone) would see something interesting.

In ufunc_obj.c, the input is converted into an array called mp.  One of the first checks after this is PyArray_ISFLEXIBLE(mp) and throws the error in question if this returns true.  This checks whether the type_num of mp is >= NPY_STRING and <= NPY_VOID.  In v1.8.x, the type_num is NPY_DOUBLE (12) which is less than NPY_STRING, but with master, it seems to be NPY_VOID (20).   The values of this enum can be found in ndarraytypes.h.  

So the question now is why the array would have a different type_num with the different versions, but why that would only happen on Ubuntu 12.04.

**Comment by charris** [comment]
It's the "only happen on Ubuntu 12.04" that is odd. I'd quess either a compiler problem or something strange about the Ubuntu configuration, but at this point it is only guessing.

**Comment by juliantaylor** [comment]
fwiw I can reproduce it on ubuntu 12.04 but not other ubuntus I'll check it out later

**Comment by njsmith** [comment]
Possibly useful further debugging things to try (in case Julian doesn't just pop up with the answer :-)):

* Check whether you get the same result from regular `np.median`, or is it just `np.ma.median`
* Paste the output of: `x = np.zeros((10,)); for f in dir(x.dtype): print "%s: %r" % (f, getattr(x.dtype, f))`

**Comment by juliantaylor** [comment]
the masked median doesn't work at all with normal arrays due to it trying to work on the data buffer of them, weird I didn't test that.

```
x = np.arange(10.)
print np.median(x)

>>> 0.
```

the weird thing is that on ubuntu 12.04 the np.array(x.data) is a flexible type while on others it is int8, don't know why yet.

**Comment by juliantaylor** [comment]
seems to be related to the python version, in 12.04 `PyMemoryView_FromObject` fails on the buffer while it works on newer versions

**Comment by snjjay** [comment]
see this one useful info here https://kodlogs.net/318/cannot-perform-reduce-with-flexible-type
