### ISSUE TITLE
Custom ufuncs can't take typed timedeltas and datetimes

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#5429]
When creating a custom ufunc (e.g. with Numba) that uses the generic resolver, timedeltas and datetimes with a unit are forbidden, which kinds of make timedelta and datetime support useless.

Here's a simple identity function, compiled with Numba:

```
>>> def identity(x): return x
... 
>>> ii = vectorize([types.NPTimedelta('s')(types.NPTimedelta('s'))], nopython=True)(identity)
>>> ii.types
['m->m']
```

It can be used on unit-less timedeltas:

```
>>> ii(np.timedelta64(5))
numpy.timedelta64(5)
>>> ii(np.array([np.timedelta64(5)]))
array([5], dtype=timedelta64)
```

but it fails when a unit is specified:

```
>>> ii(np.timedelta64(5, 's'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'ufunc' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
>>> ii(np.array([np.timedelta64(5, 's')]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'ufunc' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by njsmith** [comment]
I believe that this is a fundamental limitation of the ufunc machinery --
the ufunc inner loop signature simply doesn't have any way to pass extra
attributes of the dtypes in use, like the unit. (I could be wrong that this
is what's happening here though, b/c I haven't examined the details of how
timedelta64s are implemented.)

I'd like to fix this, but if this is the issue then it's going to require a
longer-term rewrite of lots of the dtype and ufunc machinery.

On Wed, Jan 7, 2015 at 11:52 AM, Antoine Pitrou <notifications@github.com>
wrote:

> When creating a custom ufunc (e.g. with Numba) that uses the generic
> resolver, timedeltas and datetimes with a unit are forbidden, which kinds
> of make timedelta and datetime support useless.
>
> Here's a simple identity function, compiled with Numba:
>
> >>> def identity(x): return x
> ...
> >>> ii = vectorize([types.NPTimedelta('s')(types.NPTimedelta('s'))], nopython=True)(identity)
> >>> ii.types
> ['m->m']
>
> It can be used on unit-less timedeltas:
>
> >>> ii(np.timedelta64(5))
> numpy.timedelta64(5)
> >>> ii(np.array([np.timedelta64(5)]))
> array([5], dtype=timedelta64)
>
> but it fails when a unit is specified:
>
> >>> ii(np.timedelta64(5, 's'))
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: ufunc 'ufunc' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
> >>> ii(np.array([np.timedelta64(5, 's')]))
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: ufunc 'ufunc' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5429>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by pitrou** [comment]
I think this is basically a ufunc problem, since ufuncs dispatch based on the typecode (i.e. `m`, `M`, etc.) without any regard for the dtype metadata. For the same reason, they don't work on structured arrays either.

(note that `np.add` and other built-in ufuncs have a custom resolver which casts the inputs beforehand... but a generic mechanism would be much more helpful; take a look at `PyUFunc_AdditionTypeResolver` in `core/src/umath/ufunc_type_resolution.c` for an example)

**Comment by concretevitamin** [comment]
I've been hit by this issue as well, and it's a serious issue.

In my case, its manifestation is simpler.  I have a simple `ufunc` that expects a `np.datetime64` or an array thereof.  However, upon invocation, the arguments to the ufunc automatically get casts to its epoch num, something like `1548979200000000000`.

Anyone has a short-term efficient workaround?

**Comment by seberg** [comment]
I encourage anyone here to give feedback on NEP 43 and (currently) https://github.com/seberg/experimental_user_dtypes the implementation of that is mostly there, and it provides the mechanism. But we still need to do the leg-work to make it public.

I am going to close this, because I am pretty sure we have a few other issues about "flexible dtype support in ufuncs" open anyway.
