### ISSUE TITLE
array2string prints 0-D arrays incorrectly

### ISSUE THREAD

**Issue by mgraczyk** [numpy/numpy#5430]
The behavior is easy to reproduce:

```
>>> import numpy as np
>>> np.array2string(np.ndarray([]))
'9.223372036854776e+18'
```

Why is a seemingly arbitrary floating point value being printed?  The function [array2string](https://github.com/numpy/numpy/blob/master/numpy/core/arrayprint.py#L344) prints 0-D arrays by computing 

```
x = a.item()
...
lst = style(x)
...
return lst
```

According to the array2string docstring, style() should be passed the array `a`, but instead it is passed the value of a.item().

```
""" ...
style : function, optional
        A function that accepts an ndarray and returns a string.  Used only
        when the shape of `a` is equal to ``()``, i.e. for 0-D arrays.
..."""
```

The call to item() returns garbage, so garbage is printed instead of something meaningful. (I've filed a separate issue for item()). It seems like array2string, when called with a 0-D array, should either throw an exception or return something meaningful, perhaps even the empty string.

At the very least, the docstring needs to be corrected or `a` needs to be passed to the `style` function to be consistent with the docstring.

**Comment by charris** [comment]
`np.ndarray` gives you an ndarray but it does not initialize the array contents, you need to use `np.array` if you want to do that.

**Comment by mgraczyk** [comment]
That makes sense, but the function still does not pass the ndarray to it's input `style`.  That was my original reason for noticing this issue.  Is the docstring out of date?

**Comment by eric-wieser** [comment]
Don't confused 0D array with empty array. A 0d array has exactly one element. I think you might have confused:
```python
>>> np.ndarray([])
array(1.2500232724734e-311)
>>> np.array([])
array([], dtype=float64)
```
