### ISSUE TITLE
ndarray.item() reveals contents of memory for 0-D arrays

### ISSUE THREAD

**Issue by mgraczyk** [numpy/numpy#5431]
When ndarray.item() is called on 0-D arrays, the contents of memory are unnecessarily exposed. This causes unpredictable and non-deterministic behavior in places where item() returns values of uninitialized regions of memory.   This also looks like it could be a security problem.  

To reproduce:

```
>>> import numpy as np
>>> bytearray(np.ndarray([], dtype=np.dtype('|V10000')).item())
```

It seems like item() should raise an exception when called on a 0-D array.

**Comment by charris** [comment]
0-D arrays have addressable content, so I don't see why current behavior is wrong. 0-D is not the same as empty.

**Comment by mgraczyk** [comment]
That makes sense, I think I was a little confused about the [] shape initializer.
