### ISSUE TITLE
a bug in zeros array in numpy

### ISSUE THREAD

**Issue by wangnanwei** [numpy/numpy#5433]
import numpy as np
a=np.zeros(10,dtype=np.int8)
a[0]=64*2
print(a) # you will find the the entry is -128

**Comment by njsmith** [comment]
The title is misleading, b/c this has nothing to do with the zeros()
function.

What's going on here is that you have requested an array of 8-bit signed
integers ("int8"). 8-bit signed integers can only take on values between
-128 and +127 inclusive, with out-of-range values wrapping around (i.e.,
127 + 1 = -128, 127 + 2 = -127, etc.). So when you try to assign the value
128 to one of these integers, it wraps around to become -128.

Possibly we should issue some sort of warning or error on this assignment,
similar to what we do when assigning floats to an int array...

On Thu, Jan 8, 2015 at 3:31 PM, wangnanwei <notifications@github.com> wrote:

> Closed #5433 <https://github.com/numpy/numpy/issues/5433>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5433#event-215955243>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by charris** [comment]
Yes, expected behavior, Numpy integer arithmetic is modular. The number in question has bits `0x80` which is -128 in 8 bit two's complement. If you need larger integers, you need to use a larger integer type, or maybe unsigned.
