### ISSUE TITLE
problems with numpy.delete

### ISSUE THREAD

**Issue by tychung84** [numpy/numpy#5434]
Just noticed this: 

In [122]: np.delete(np.arange(1, 100, 1.0), np.arange(1, 100, 1.0))
Out[122]: array([ 1.])

In [123]: np.delete(np.arange(1, 100, 1.0), np.arange(0, 100, 1.0))
Out[123]: array([], dtype=float64)

In [124]: np.delete(np.arange(0, 100, 1.0), np.arange(1, 100, 1.0))
Out[124]: array([ 0.])

not sure if this is intended behavior, but probably worth looking into!

**Comment by jaimefrio** [comment]
The first two should probably raise an `IndexError`, as it does for single indices:

```
>>> a = np.arange(10)
>>> np.delete(a, 12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python27\lib\site-packages\numpy\lib\function_base.py", line 3626, in delete
    "size %i" % (obj, axis, N))
IndexError: index 12 is out of bounds for axis 0 with size 10
>>> np.delete(a, [1, 12])
array([0, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Comment by jaimefrio** [comment]
But there already is a `DeprecationWarning` in master about that, see [here](https://github.com/numpy/numpy/blob/v1.9.1/numpy/lib/function_base.py#L3602).

**Comment by tychung84** [comment]
I don't disagree about that, but this is odd, no?

>>> a = np.arange(0, 10, 1.0)
>>> np.delete(a,a)
array([], dtype=float64)

>>> b = np.arange(1, 10, 1.0)
>>> np.delete(b,b)
array([ 1.])

**Comment by tychung84** [comment]
or this...

>>> a = np.arange(0, 10)
>>> np.delete(a,a)
array([], dtype=int64)
>>> b = np.arange(1, 10)
>>> np.delete(b, b)
array([1])

**Comment by ewmoore** [comment]
No.  Indexing begins at 0.  So np.delete(b,b) should leave the 1.

**Comment by tychung84** [comment]
Sorry if I don't understand, but why doesn't np.delete(a,a) not leave the 0? Also, shouldn't deleting an array with itself always result in nothing (or an empty array)?

**Comment by maniteja123** [comment]
The first argument would create an array from the ``arange`` constructor, but the second argument is the array corresponding to the indices.

    a = np.arange(0, 10)
    np.delete(a,a)
    array([], dtype=int64)

Above the elements corresponding to the indices in the second argument, i.e. [0,...,9] are removed. So a[0] to a[9], all are removed.

    b = np.arange(1, 10)
    np.delete(b, b)
    array([1])

Here, only a[1] to a[9] are removed since the second argument is [1,...,9].

Hope it helps :)

**Comment by tychung84** [comment]
Cool that makes sense. Thanks guys!

**Comment by maniteja123** [comment]
No problem :)

**Comment by jaimefrio** [comment]
Closing this then.
