### ISSUE TITLE
DOC: Update "Pushing Changes to Main Repo" Dev Workflow

### ISSUE THREAD

**Issue by rnelsonchem** [numpy/numpy#5443]
In a recent updated to the Numpy Development Workflow documentation (#5332), some issues were brought up regarding the "Pushing Changes to Main Repo" section, but a consensus on the correct procedure was not reached. See the previous pull request for some of the discussions on potential changes. Specifically, a series of comments charris, juliantaylor, and tacaswell starting from a line comment by rgommers, as well as a comment at the end of the thread by charris.

**Comment by rgommers** [comment]
Regarding comment https://github.com/numpy/numpy/pull/5332#issuecomment-6910426, that looks good to me

**Comment by rgommers** [comment]
I don't think we disagreed on always a merge commit though, that was just a misunderstanding. I made one more comment on the PR.

**Comment by mattip** [comment]
Closing. The related PR was merged. If someone wishes to change the "Pushing Changes to Main Repo" [section of the docs](http://www.numpy.org/devdocs/dev/gitwash/development_workflow.html?highlight=pushing%20changes%20main%20repo#pushing-changes-to-the-main-repo) please open a new issue. Someday we should rework this section of the docs to only contain NumPy specific workflow information.
