### ISSUE TITLE
raising of NotImplementedError could be more helpful

### ISSUE THREAD

**Issue by stsci-sienkiew** [numpy/numpy#5444]
numpy 1.9.0

numpy/ma/core.py line 5462 says:

        raise NotImplementedError("Not implemented yet, sorry...")

This is in MaskedArray.tofile().  I came across this when answering a user support question where my user asserted "I am not writing a masked array to the file".

There are a few places in this file that give ambiguous errors like that.  It would be more helpful if the exception message were to say what it is that is not implemented.  For example, in this case:

        raise NotImplementedError("cannot write masked array to file")

There are other places in ms/core.py where there are similarly ambiguous messages, so I conjecture there may be other ambiguous messages in other places.  I suggest a sweep of the full numpy source code for NotImplementedError and clarify all the messages.

I think this would be easy for a numpy developer.  I am not very familiar with numpy myself.  Since this is a trivial (mostly) change, I could possibly make a pull request, if I have some indication that it would be accepted without me making a major commitment to testing or learning the numpy developer work flow.  (Unfortunately, I don't have time to make a serious commitment to becoming a numpy developer.)

**Comment by shoyer** [comment]
@stsci-sienkiew I am not a core numpy developer, but AFAICT, simple fixes like these are always welcome (and generally do not even require writing or modifying tests).
