### ISSUE TITLE
BUG: Sorting of unorderable object types in Python3

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#5445]
In Python3 not all objects are comparable:

```
>>> a = ['', 3, 5, 8, None]
>>> a.sort()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: int() < str()
>>> a
['', 3, 5, 8, None]
```

Numpy does not acknowledge this possibility, so when trying to sort an object array, even though the error is raised, the sorting goes on as if all unorderable objects compared equal:

```
>>> arr = np.array(a, dtype=object)
>>> arr
array(['', 3, 5, 8, None], dtype=object)
>>> arr.sort()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: int() > NoneType()
>>> arr
array([3, 5, 8, None, ''], dtype=object)
```

**Comment by njsmith** [comment]
What behaviour do you expect here? My intuition is that if a comparison
raises an error, then an in-place sort() should (1) propagate that error,
(2) leave the array in undefined order. From your example it looks like
numpy does meet both those criteria...

**Comment by jaimefrio** [comment]
Hmmm... I thought Python's sort guaranteed the original list would be unchanged if a comparison failed. But you are right, it only guarantees that no item will be lost. From a comment in the source code of `listobject.c`, "Even in case of error, the list will be some permutation of its input state (nothing is lost or duplicated)." And list sorting can indeed modify the original object:

```
>>> a = [5, 4, 3, 1, 2, None]
>>> a.sort()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: NoneType() < int()
>>> a
[1, 2, 3, 4, 5, None]
```

Closing this then.
