### ISSUE TITLE
Agregation functions don't use full machine int magnitude on 64-bit Windows

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#5448]
Linux 64-bit:

```
>>> np.full(3, 40003, dtype='uint16').prod()
64014401080027          # no overflow
```

Linux 32-bit:

```
>>> np.full(3, 40003, dtype='uint16').prod()
2208500443        # overflow due to the 32-bit result
```

Windows 64-bit:

```
>>> np.full(3, 40003, dtype='uint16').prod()
2208500443
```

As you can see, Win64 behaves like 32-bit Linux here: the operands are extended to 32 bits rather than 64 bits.

**Comment by njsmith** [comment]
This probably happens either because some code somewhere thinks it should
use a 'long' (which is 32-bits on Win64, 64-bits on Linux64), or b/c some
code somewhere prefers to promote to the "default" integer type (which
follows Python 2, where ints were always the same size as a C long)...

On Tue, Jan 13, 2015 at 3:58 PM, Antoine Pitrou <notifications@github.com>
wrote:

> Linux 64-bit:
>
> >>> np.full(3, 40003, dtype='uint16').prod()
> 64014401080027          # no overflow
>
> Linux 32-bit:
>
> >>> np.full(3, 40003, dtype='uint16').prod()
> 2208500443        # overflow due to the 32-bit result
>
> Windows 64-bit:
>
> >>> np.full(3, 40003, dtype='uint16').prod()
> 2208500443
>
> As you can see, Win64 behaves like 32-bit Linux here: the operands are
> extended to 32 bits rather than 64 bits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5448>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by ewmoore** [comment]
Looks like the code that needs to change is right around here: https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L3878.  This `NPY_LONG` should become what though?  is `NPY_LONGLONG` always 64 bit?

**Comment by juliantaylor** [comment]
the question is do we want to change this?
numpy does its integer reductions in size of long is our API, that thats kind of dumb is part of the interface.
I'd rather like to change the default integer to 64 bit on win64 in total, but that breaks abi even worse ...

**Comment by pitrou** [comment]
@ewmoore, to approximate the machine word size, NPY_INTP is probably a good choise.
@juliantaylor, I don't know, but I think the discrepancy between 64-bit Windows and 64-bit Linux is a bit unfortunate here. For the record, in Numba we chose to use 64-bit ints in this case.

**Comment by seberg** [comment]
I think we probably have so many issues open about this (including in some documents of what should happen in the future), that I will close this one.
