### ISSUE TITLE
remove the funroll-loops switch

### ISSUE THREAD

**Issue by didickman** [numpy/numpy#5451]
On OpenBSD/macppc, using the -funroll-loops option causes a segfault with scipy. Proposed patch below just removes the optimization flag across the board though. In the OpenBSD ports tree, this flag is sometimes removed due to buggy results.

For what it's worth gentoo also recommends against it:
http://wiki.gentoo.org/wiki/GCC_optimization#But_I_get_better_performance_with_-funroll-loops_-fomg-optimize.21

```
diff --git a/numpy/distutils/fcompiler/gnu.py b/numpy/distutils/fcompiler/gnu.py
index ccd5e8d..3b9481c 100644
--- a/numpy/distutils/fcompiler/gnu.py
+++ b/numpy/distutils/fcompiler/gnu.py
@@ -202,7 +202,6 @@ class GnuFCompiler(FCompiler):
             opt = ['-O2']
         else:
             opt = ['-O3']
-        opt.append('-funroll-loops')
         return opt

     def _c_arch_flags(self):
```

**Comment by charris** [comment]
I'll let you argue this one with @juliantaylor ;)

**Comment by juliantaylor** [comment]
if openbsd funroll-loops is buggy make it a no-op it in the compiler, it is used in numpy explicitly in places where it has significant performance impact even on newish hardware.

Best I'd be willing to accept is turn it off on bsd only, but I'd prefer bsd to fix their stuff.

**Comment by juliantaylor** [comment]
how does wrong results match with #5450 where you say gcc 4.2 does not support the flag at all?

**Comment by didickman** [comment]
One is a command line switch (-funroll-loops). This is supported by gcc 4.2.

The other is a function attribute which is not supported in 4.2. To quote from the gcc 4.4 "what's new" pages which I linked in #5450:
"A new optimize attribute was added ..."

**Comment by didickman** [comment]
Ok, let's turn it off for at least OpenBSD. I can't speak for the other BSDs since they use different system compilers (FreeBSD is on clang as far as I know).

```
diff --git a/numpy/distutils/fcompiler/gnu.py b/numpy/distutils/fcompiler/gnu.py
index ccd5e8d..3f2468c 100644
--- a/numpy/distutils/fcompiler/gnu.py
+++ b/numpy/distutils/fcompiler/gnu.py
@@ -202,7 +202,8 @@ class GnuFCompiler(FCompiler):
             opt = ['-O2']
         else:
             opt = ['-O3']
-        opt.append('-funroll-loops')
+        if platform.system() not in ['OpenBSD']:
+            opt.append('-funroll-loops')
         return opt

     def _c_arch_flags(self):
```

I'm surprised that you're seeing significant performance impact. I have to assume that most loops are short loops so cache misses aren't coming into play with what you're seeing. As the gcc docs say: "This option makes code larger, and may or may not make it run faster."

**Comment by juliantaylor** [comment]
oh this is about it being always added to the fcompiler flags.
I agree always adding it is often a bad idea in generic programs, though this is for fortran only (which is not used in numpy itself). It might be that for fortran it is more often beneficial than not as it is usually used for number crunching and not general applications.
If it causes issues I am more open to remove it, though I'd prefer to see some benchmarks for this.

**Comment by didickman** [comment]
The main issue is that scipy segfaults on OpenBSD/macppc when numpy is built with this switch. So it's not just a performance issue. At the moment, we patch it out on macppc.

**Comment by didickman** [comment]
will need to check. will come back here when i do. thanks.

**Comment by rgommers** [comment]
We've switched build systems now and won't be changing this anymore, hence closing. Thanks all.
