### ISSUE TITLE
BUG? : Inconsistency in slicing of object arrays

### ISSUE THREAD

**Issue by MechCoder** [numpy/numpy#5456]
I am not sure again if this is the expected behavior or not.

    In [16]: x1 = [[1], [2, 3]]
    In [17]: b = np.array(x1, dtype=object)
    In [18]: x = np.random.rand(5)
    In [19]: x[b[1]]
    Out[19]: array([ 0.65138485,  0.52464837])
    In [20]: x2 = [[1], [2]]
    In [21]: b = np.array(x2, dtype=object)
    In [22]: x[b[0]]
    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    <ipython-input-22-89c92d26bcc0> in <module>()
    ----> 1 x[b[0]]

    IndexError: arrays used as indices must be of integer (or boolean) type
    # Should this be a list?
    In [23]: b[0]
    Out[23]: array([1], dtype=object)

**Comment by jnothman** [comment]
The shape of `np.array(x1, dtype=object)` is `(2,)`, while that of `np.array(x2, dtype=object)` is `(2, 1)`. You've created quite different beasts. The reliable way to create an array of lists (or an array of arrays) is:
```python
b = np.empty(x1.shape[0], dtype=object)
b[:] = x1
```

**Comment by jnothman** [comment]
So I agree the behaviour's surprising, but it's predictable if you understand that `np.array(x2)` will recognise it as 2d regardless of the dtype.

**Comment by pv** [comment]
>>> b = np.array([[1], [2]], dtype=object)
>>> b.shape
(2,1)
.
It understands this as a 2D object array. The safe way to construct
object arrays is to first allocate with np.empty and then assign.

**Comment by MechCoder** [comment]
Thanks!
