### ISSUE TITLE
public macros missing in C API documentation

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#5460]
Noticed after trying to look up `NPY_LIKELY` used in another PR. These seem to be missing:

```
NPY_LIKELY
NPY_UNLIKELY
NPY_UNUSED
NPY_INTERRUPT_H
NPY_SIGSETJMP
NPY_SIGLONGJMP
NPY_SIGJMP_BUF
NPY_SIGINT_ON
NPY_SIGINT_OFF
NPY_HAVE_ENDIAN_H
```

There isn't yet an obvious place to add these in the reference guide. Maybe a new sub-section under "Numpy core libraries" (except for `HAVE_ENDIAN` which belongs in "System configuration")? Suggestion for a good name?

**Comment by rgommers** [comment]
``NPY_TYPES`` is missing as well.

**Comment by pujaji** [comment]
@mattip @rgommers 
Can I take up this issue and work?
May I know the obvious place to add about these?
Thanks!

**Comment by mattip** [comment]
System configuration documentation belongs in `doc/source/reference/c-api.config.rst`. Some of the others might fit into a new section `Compiler Directives` in that file. Try to see where the `NPY_SIG*` constants are used, perhaps you can come up with the correct section for them that way.
