### ISSUE TITLE
No clear documentation of how to go about working on Numpy

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#5465]
Currently there is no way to use a development Numpy without installing it, which makes interactive use and testing a pain:

```
$ python
Python 3.4.2 |Continuum Analytics, Inc.| (default, Oct 21 2014, 17:40:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "/home/antoine/np/numpy/__init__.py", line 155, in <module>
    from numpy.__config__ import show as show_config
ImportError: No module named 'numpy.__config__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/np/numpy/__init__.py", line 160, in <module>
    raise ImportError(msg)
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by pitrou** [comment]
And the build system is a PITA:

```
$ python3.4 setup.py develop
Running from numpy source directory.
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    setup_package()
  File "setup.py", line 235, in setup_package
    from numpy.distutils.core import setup
  File "/home/antoine/np/numpy/distutils/__init__.py", line 37, in <module>
    from numpy.testing import Tester
  File "/home/antoine/np/numpy/testing/__init__.py", line 14, in <module>
    from .utils import *
  File "/home/antoine/np/numpy/testing/utils.py", line 17, in <module>
    from numpy.core import float32, empty, arange, array_repr, ndarray
  File "/home/antoine/np/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'
```

**Comment by pv** [comment]
You can do `python setup.py build_ext -i` or use runtests.py. Not sure
why develop doesn't work, though.

**Comment by pitrou** [comment]
Apparently, I can do `python runtests.py --ipython`. It's quite unintuitive to use runtests for this, though, and it doesn't look documented anywhere. It would have saved me quite some time if I had noticed this earlier...

I don't think `build_ext --inplace` would solve the problem at all, since Numpy *refuses* to be loaded from its source tree.

**Comment by pv** [comment]
`setup.py build_ext -i` does work for me --- the in-place import
prevention magic AFAIK is coded to detect this.

**Comment by pv** [comment]
Also `python3.4 setupegg.py develop --user` also works for me.
`python3.4 setup.py develop --user` doesn't, but I get a different error
message (due to setup.py not using setuptools, not from missing
numpy.distutils)...

**Comment by rgommers** [comment]
there has never been an issue with ``build_ext --inplace``; the import only fails if you try to import from the source tree *without* an in-place build.

**Comment by rgommers** [comment]
The one thing that could easily improved here is if ``setup.py develop`` gave the user the hint to use ``setupegg.py develop`` before failing.

**Comment by pitrou** [comment]
> there has never been an issue with build_ext --inplace; the import only fails if you try to import from the source tree without an in-place build.

I see, thank you. It would be nice to document all this, so that people don't go mad at this because they don't know the right steps for developing.

**Comment by rgommers** [comment]
@pitrou I'll have a look at improving this. For Scipy there are these two entries in the FAQ of https://github.com/scipy/scipy/blob/master/HACKING.rst.txt that can be copied for numpy for starters:

- How do I set up a development version of SciPy in parallel to a released version that I use to do my job/research?
- How do I set up an in-place build for development

**Comment by rgommers** [comment]
Just noticed that this is already documented in ``INSTALL.txt``:

    Basic Installation
    ==================

    To install numpy run:

        python setup.py build -j 4 install --prefix $HOME/.local

    This will compile numpy on 4 CPUs and install it into the specified prefix.
    To perform an inplace build that can be run from the source folder run:

       python setup.py build_ext --inplace -j 4

    The number of build jobs can also be specified via the environment variable
    NPY_NUM_BUILD_JOBS.

It's missing from http://docs.scipy.org/doc/numpy-dev/user/install.html though. Is that where you looked?

**Comment by rgommers** [comment]
Updated build instructions in several places in gh-5473.

**Comment by chatcannon** [comment]
What about `pip install --user --editable [path to numpy git checkout]`? Or using a virtualenv?

**Comment by rgommers** [comment]
@chatcannon I described using virtualenv already in gh-5473. ``pip install --user --editable`` is pretty much the same as ``python setupegg.py develop --user`` (except that it may not work, just like ``setup.py develop`` doesn't as reported above).
