### ISSUE TITLE
BUG: partition and argpartition don't bound check kth for some types

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#5469]
For dtypes that do not have a type specific implementation of the introselect algorithm, both `partition` and `argpartition` resort to fully (arg)sorting the input array. When doing so, the `kth` array of elements to partition by is not bound checked:

```
>>> a = np.arange(10)
>>> a.partition(17)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: kth(=17) out of bounds (10)
>>> a.argpartition(17)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: kth(=17) out of bounds (10)

>>> b = np.array(range(10), dtype=object)
>>> b.partition(17)
>>> b.argpartition(17)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Comment by veenavijai** [comment]
Was this error resolved?

**Comment by mattip** [comment]
On what version of numpy? For me the code using `b = np.array(range(10), dtype=object)` raises and error. Can you distill your issue down to a few lines of code and open a new issue?
