### ISSUE TITLE
numpy.mean returns nan when indices are equal

### ISSUE THREAD

**Issue by muratetm** [numpy/numpy#5484]
I was working on finding the mean value over a set of array elements where sometimes the bounds are equal. numpy.mean returns nan in such a case. I'm guessing that it subtracts the bounds and gets a divide by zero.

aa = numpy.zeros((5,5),dtype=numpy.float)
aa += 5
print numpy.mean(aa)
print numpy.mean(aa[3,3])
print numpy.mean(aa[3:4,3:4])
print numpy.mean(aa[3:3,3])
print numpy.mean(aa[3,3:3])
print numpy.mean(aa[3:3,3:3])
5.0
5.0
5.0
nan
nan
nan

I can include a test for the equality of the bounds, but it seems like it should work with equal bounds.
Thanks
Mike

**Comment by njsmith** [comment]
Can you define "work"? :-) what are you expecting the mean of no elements
to be?

**Comment by muratetm** [comment]
On Jan 22, 2015, at 3:48 PM, Nathaniel J. Smith wrote:

> Can you define "work"? :-) what are you expecting the mean of no elements 
> to be? 

I am calculating the mean over a subarray defined by row_min,row_max,col_min,col_max. Sometimes col_min=col_max and mean returns nan. I could, of course, do something like this (from my code)

             if min_min==m_max:
                b0 = image[az_min-1,m_min]
                b1 = image[az_max+1,m_min]
             else: 
                b0 = numpy.mean(image[az_min-1,m_min:m_max])
                b1 = numpy.mean(image[az_max+1,m_min:m_max])

but my code would be cleaner if it could handle the col_min=col_max case.

But, I just realized what you mean (no pun) and that x:y does not include y.

So I should be using 

                b0 = numpy.mean(image[az_min-1,m_min:m_max+1])
                b1 = numpy.mean(image[az_max+1,m_min:m_max+1])

Ignore the man behind the curtain and the request.

Cheers

Mike

**Comment by charris** [comment]
OK :)
