### ISSUE TITLE
Make numpy.distutils recognize Fortran 2003 and Fortran 2008 files

### ISSUE THREAD

**Issue by sturlamolden** [numpy/numpy#5486]
NumPy build utils does not know what to do with `.f03` and `.f08` files. This makes it difficult to compile a library written in Fortran 2003 or 2008. 

Fortran 2003 is e.g. useful if we want to make a C callable library without depending on an ABI wrapper. A typical usecase is calling Fortran from Cython, which is more flexible and efficient than using f2py.

f2py does not parse Fortran 2003. But that is not a problem if we just want to use `configuration.add_library`, and not `configuration.add_extension` (which will invoke f2py).

**Comment by rgommers** [comment]
Is this as simple as updating ``language_map`` in ``distutils/fcompiter/__init__.py``? I.e. are you OK with the ``f90`` compiler flags?

**Comment by sturlamolden** [comment]
Yes that, and also update the compiler classes correspondingly to set the executable, I think. 


As for compiler flags:

The flags should be the same as for Fortran 90 in free form. (Well, since we can control the C ABI we don't always need to worry about flags like ```-fno-second-underscore```, but they do no harm either.)

I have never seen anyone use fixed-form formatted source code with Fortran 2003, but theoretically it is not forbidden. If fixed form Fortran 2003/2008 conflicts with fixed-form Fortran 90, I think we can just ignore implementing special cases for it.

When I compile with gfortran outside SciPy I typically use ```-O3 -ffast-math -funroll-loops -mavx```. I see that we have ```-O3  -funroll-loops```, but not ```-ffast-math```. ```-ffast-math``` is safer in Fortran than in C, and is needed for autovectorization with SSE/AVX. I am not sure about the simd flags. Do we get ```-msse2``` or ```-msse3``` from the C compiler? Otherwise we should add whatever simd flag the C compiler uses.

In any case Fortran flags can be added from setting ```FFLAGS``` in the environment, so it is not that important.

**Comment by juliantaylor** [comment]
fast-math allows the compiler to do all kinds of dangerous shenanigans, like numerical unstable complex divisions, use of very inaccurate reciprocal approximations, reorderings and ignoring of error codes.
It should only be used in special cases where accuracy really does not matter or the impact of it has been evaluated. It should never be the default of a build system.
unsafe-math-optimizations is the safer option, but should still not be the default.

Even the current default unroll-loops is questionable (and we do have a bug about it).

**Comment by sturlamolden** [comment]
Ok, then just leave the flags as they are.

**Comment by rgommers** [comment]
This would also needs a test. Guess add a Fortran 2003 and/or 2008 file with syntax that isn't valid Fortran 90, compile it with ``add_library`` and do a basic check on it. Similar to ``numpy/distutils/tests/f2py_f90_ext/``.

**Comment by rgommers** [comment]
This isn't very high on my prio list (and I wouldn't know how to write the right Fortran 200x test code), but PR welcome.

**Comment by sturlamolden** [comment]
A testcase is easy. ```use iso_c_binding``` will fail in Fortran 90 and ```bind(C, name='foobar')``` is invalid, but those two statements are required to make a function with C ABI in Fortran 2003. For Fortran 2008 we can try to use a ```do concurrent``` loop.

**Comment by bjodah** [comment]
Intel's Fortran compiler (ifort) did not support any other extension than .f90 for standards >= 90 last time I checked (don't have an installed copy atm. I'm afraid).

**Comment by sturlamolden** [comment]
Thanks. What do the other Fortran compilers do?

I am mostly familiar with Absoft and gfortran. Absoft do not support standards beyond Fortran 90 at all, except a tiny subset of Fortran 2003 and 2008 as extensions to Fortran 95. Both gfortran and Absoft assumes .f90 files are Fortran 95.

**Comment by bjodah** [comment]
Portland group has a separate binary for Fortran 90 source: ``pgf90`` (``pgf77`` for Fortran 77 sources)

**Comment by zerothi** [comment]
Sadly many compilers implement subsets of each standard, hence asserting complete support for 2003/8 would be hazardous at best.  Doing a simple "use iso_c_binding" would not cut all corner cases.  
In my experience (gfortran and ifort), the file-endings primarily **f90** or **f**, but **f90** do not force the standard to be fortran-90. As such is **f90** misleading. All it says is "free-format" code.
And actually gfortran assumes **f90** _and_ **f** to the latest implemented standard, unless you supply `-std=` to the compiliation.

I would highly recommend _not_ to use **f95**, **f03**, **f08**, etc.  
I would recommend to close this topic as resolved, and not supporting.

PS.
As such I also think supporting obscure file endings is bad practice. Only do **f** for fixed format, **f90** for free-format. (Note the fortran standard says nothing about _not_ using fixed format for fortran-2003+ standard, how will absoft handle fixed format ending with **f03**, maybe it eats it, I do not know).
A rhetorical question: would you name c obeying to certain standards by their standard year to the ending? c11, c99, etc.

**Comment by sturlamolden** [comment]
@zerothi I think you misunderstood. NumPy does not require a Fortran compiler to build. Nor did I suggest we use Fortran 2003 in SciPy. The problem arises when you want to build your own extension module, with the compliant compiler that you happen to have. In this case you cannot use distutils to build the module because it does not recognize the file extensions. If your compiler does not support Fortran 2003 you are screwed anyway, but that is a totally different problem. Obviously, not all compilers implement the Fortran 2003 or 2008 standards correctly, or even Fortran 90 for that matter. But since we are not using a Fortran compiler to build NumPy, that is hardly a problem here.

**Comment by zerothi** [comment]
@sturlamolden I do not think I misinterpreted the request.  
Adding `f03` and `f08` to the language map (in `distutils/fcompiler/__init__.py`), I would say should not be done, for the reasons I put in my previous comment.

Again, my main point in the previous comment was that naming files according to the standard they follow is bad practice, in my opinion. I would even go so far as removing **ftn**, **for** and **f95** from the `language_map` to enforce this! ;) (ok a bit over the top...)

The other stuff I wrote was merely to back up my thought about this.

**Comment by sturlamolden** [comment]
.f03 and .f08 are common file extensions. But clearly you could name every file .f and just use compiler flags.

**Comment by zerothi** [comment]
Yes, people tend to use those extensions.
But I would still claim that it is bad practice. ;)

I think we just have to agree to disagree on this matter.

2015-05-21 15:44 GMT+02:00 Sturla Molden <notifications@github.com>:

> .f03 and .f08 are common file extensions. But clearly you could name every
> file .f and just use compiler flags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5486#issuecomment-104281875>.
>



-- 
Kind regards Nick

**Comment by sturlamolden** [comment]
I do not disagree that it might be bad practice. I just think they are common enough to be recognized as Fortran files. :)

**Comment by zerothi** [comment]
Yeah. You are probably right. It does seem like the right thing to keep the
code usable for the larger audience.

I just trip when I hear those extensions, it seems like a nightmare to keep
the extension correct (I bet a lot of f03/f08 files are named incorrectly
;) ).

I had to react... ;)


2015-05-21 15:56 GMT+02:00 Sturla Molden <notifications@github.com>:

> I do not disagree that it might be bad practice. I just think they are
> common enough to be recognized as Fortran files. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5486#issuecomment-104284483>.
>



-- 
Kind regards Nick

**Comment by MarkWieczorek** [comment]
I am having a similar issue where I have `.f03` files that compile fine with my compiler (`gfortran`), but which are not recognized by `numpy.distutils`. In the 5 years since this issue was closed, the use of `.f03` has become increasing common given that it is **only** the f2003 standard that supports `use iso_c_binding`. As one notable example, the `fftw3` scientific library for FFTs includes a `.f03` file to define functions in an interface block.

Of course, you could rename the files `.f95` if you would like, and that should work in most cases, but it is an ugly hack.

**Comment by zerothi** [comment]
I will probably agree that `numpy` should support whatever *all* compiler vendors support. :)
But the question is how backward compatible we should be to compilers. For instance `Intel` does not document these file extensions in their `ifort --help`.
So should all files just be eaten and then fail if the compiler steps fails? It isn't clear...

**Comment by MarkWieczorek** [comment]
In `ifort`, you can use the compiler option `-Tf` to ignore the file extension.

**Comment by HaoZeke** [comment]
I'm strongly on @zerothi's side on this. The [Fortran 2018 language standard ](https://github.com/numpy/numpy/issues/12136) does not mention file endings to be appropriate for signally standard support. Additionally in Fortran, unlike C/++ files have even less meaning; as the standard recognizes modules as the smallest code chunk.

Compiler support is important, but impossible to get right without the appropriate flag. I would suggest (if necessary) the implementation of `--std=2018` or some such to `f2py` instead of file name based heuristics.

**Comment by rgommers** [comment]
I'd also say it's very low-prio either way, because there's a good chance we're moving away from `numpy.distutils` completely.

**Comment by HaoZeke** [comment]
Closing due to `np.distutils` deprecation.
