### ISSUE TITLE
Opening Pickle Files using ma.dump in Python 3

### ISSUE THREAD

**Issue by JacksonTanBS** [numpy/numpy#5491]
When using numpy.ma.dump to save a masked array in Python 3:

```
np.ma.dump(a, pathtofile)
```

I got the following error:

```
/home/btan1/.virtualenvs/python3.3/lib/python3.3/site-packages/numpy/ma/core.py in dump(a, F)
   7141     if not hasattr(F, 'readline'):
   7142         F = open(F, 'w')
-> 7143     return pickle.dump(a, F)
   7144 
   7145 def dumps(a):

TypeError: must be str, not bytes
```

This is with NumPy 1.9.1 and Python 3.3.2.

From what I found out, it is because in Python 3 pickle files has to be opened in binary mode, i.e. L7142 should be `F = open(F, 'wb')`. Indeed, if I were to change it to:

```
with open(pathtofile, 'wb') as f:
    pickle.dump(a, f)
```

the error goes away.

**Comment by eric-wieser** [comment]
Echoing my comments elsewhere:

> Why on earth do any of these exist?
> 
> * `np.ma.dump`
> * `np.ma.load`
> * `np.ma.dumps`
> * `np.ma.loads`
> 
> It seems pretty obvious to me that exposing a slightly-tweaked `pickle` api is not in scope for what `ma` should do, especially since these tweaks are broken on python 3 anyway (#5491).
> 
> Given that this is already broken on py3, I vote we leave it broken and simply add
> 
> ```
> warnings.warn(
>     "np.ma.{method} is deprecated, use pickle.{method} instead".format(method=the_method_name),
>     DeprecationWarning)
> ```

**Comment by eric-wieser** [comment]
Alright, closing as wont-fix - these functions will be deprecated in 1.15.0, as of #10192
