### ISSUE TITLE
Performance of numpy average and numpy.mean function

### ISSUE THREAD

**Issue by skuschel** [numpy/numpy#5507]
I need a weightened average function on a VERY large Dataset (some 1e8 numbers or more). The numpy functions mean and average serve me well and fast, but I discovered, that numpy.average is slower than builing the weightened average myself with two numpy.mean functions, as shown by the example:
https://gist.github.com/skuschel/2d148a37a2ce17925fb0
`np.average(a,weights=b)`   takes 0.32 sec on my computer, but
`np.mean(a*b)/np.mean(b)`   takes 0.23 sec for the equally sized dataset, yielding the same result.
How does that make sense?

**Comment by Nodd** [comment]
I did a quick timing using line_profiler: https://gist.github.com/Nodd/926e3e21af1f04741c14

28% of the time is spent doing ```a = a + 0.0``` (I guess it is to fonvert the array to float ?), this is an operation you're not doing while using mean.
```(0.32-0.23)/0.32``` is 28%, so it corresponds to the slowdown you've noticed.

The average function could use some refactoring :)

**Comment by minhlongdo** [comment]
I removed <code> a = a + 0.0 </code> and replaced <code> wgt = np.asarray(weights) </code> with <code> wgt = np.asarray(weights, dtype=float, copy=0) </code> and then ran the script provided by @skuschel and got the following results:
<code> execution time np.average: 3.03e-01 sec </code>
<code> exectution time np.mean: 3.01e-01 sec </code>

**Comment by njsmith** [comment]
Excellent!

That's not quite a complete fix (consider what happens if the input is
complex), but that can be handled with a call to result_type I think.

Could you submit a pull request?

-n

**Comment by minhlongdo** [comment]
@njsmith to which branch am i suppose to submit the pull request? Sorry for the stupid question, I am new to this.

**Comment by skuschel** [comment]
got finally fixed in  #7382
