### ISSUE TITLE
System complex functions not detected/used on Fedora 21.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#5511]
Current state on Fedora 21.

```
In [2]: np.tanh(372+1j)
Out[2]: (nan+nan*j)
```

Looks like library function is not used. gcc 4.9.2 gives `1.000000000000000000+0.000000000000000000i`, where denormals look to be flushed to zero, probably a side affect of how the function compiles. The code for that is

```
#include <stdio.h>
#include <math.h>
#include <complex.h>

int main(int argc, char **args)
{
    double complex z = 372.0 + 1.0 * I;
    double complex res = ctanh(z);

    printf("%20.18f%+20.18fi\n", creal(res), cimag(res));
}
```

**Comment by charris** [comment]
A lot of functions in `complex.h` are not looked for.

**Comment by mattip** [comment]
Is this still an issue?

**Comment by mattip** [comment]
ok, closing then.
