### ISSUE TITLE
how can i read the   numpy.where()   in the sources

### ISSUE THREAD

**Issue by 0532** [numpy/numpy#5520]
i just use  ```numpy.where()```  only , i want to know  where i  could read  the function

**Comment by jaimefrio** [comment]
This is not really an issue, so I am going to close it. Questions like this are better addressed to the [mailing list](http://mail.scipy.org/mailman/listinfo/numpy-discussion).

In any case, to answer your question, the Python `np.where` function is actually [`numpy.core.multiarray.where`](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/src/multiarray/multiarraymodule.c#L3704), which is the C function [`array_where`](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/src/multiarray/multiarraymodule.c#L2893), that is lttle more than argument parsing for [`PyArray_Where`](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/src/multiarray/multiarraymodule.c#L2745), where all the magic happens. They all live in [`numpy/core/src/multiarray/multiarraymodule.c`](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/src/multiarray/multiarraymodule.c).
