### ISSUE TITLE
np.lib.test() FAILED

### ISSUE THREAD

**Issue by r2007** [numpy/numpy#5521]
ubuntu 14.04
# pip freeze

backports.ssl-match-hostname==3.4.0.2
certifi==14.5.14
Cython==0.21.2
docutils==0.12
h5py==2.4.0
ipython==2.3.1
Jinja2==2.7.3
MarkupSafe==0.23
matplotlib==1.4.2
mock==1.0.1
nose==1.3.4
numexpr==2.4
numpy==1.9.1
numpydoc==0.5
pandas==0.15.2
Pillow==2.7.0
Pygments==2.0.2
pyparsing==2.0.3
python-dateutil==2.4.0
pytz==2014.10
pyzmq==14.5.0
scikit-image==0.10.1
scikit-learn==0.15.2
scipy==0.15.1
six==1.9.0
Sphinx==1.2.3
tables==3.1.1
tornado==4.0.2

In [3]: np.lib.test()  
Running unit tests for numpy.lib
NumPy version 1.9.1
NumPy is installed in /usr/local/lib/python2.7/dist-packages/numpy
Python version 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
nose version 1.3.4
......................................................................................................................................................
......................................................................................................................................................
......................................................................................................................................................
......................................................................................................................................................
......................................................................................................................................................
......................................................................................................................................................
............................................F.........................................................................................................
......................................................................................................................................................
# ......................................................................................................................................................
## FAIL: test_allnans (test_nanfunctions.TestNanFunctions_Median)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/tests/test_nanfunctions.py", line 613, in test_allnans
    assert_(len(w) == 3)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

---

Ran 1350 tests in 5.710s

FAILED (failures=1)
Out[3]: <nose.result.TextTestResult run=1350 errors=0 failures=1>

**Comment by r2007** [comment]
update: another 4 test is ok, but the 6th test is failed and the show the same message as above

**Comment by r2007** [comment]
if I use this method:
python -c 'import numpy as np;np.lib.test()'
it will be ok always.
but I run np.lib.test() in interactive mode, sometime it will be failed. both for python and ipython.

**Comment by maniteja123** [comment]
This has happened once before on 1.9.1 even in my installation for ``test_allnans`` function. Try reinstalling numpy again. It will mostly not occur, although not sure why it occurs.

**Comment by r2007** [comment]
I test on wakari.io. It shows the same error.
```
Running unit tests for numpy.lib
NumPy version 1.9.1
NumPy is installed in /opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/numpy
Python version 2.7.8 |Anaconda 1.9.1 (64-bit)| (default, Aug 21 2014, 18:22:21) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.4


======================================================================
FAIL: test_allnans (test_nanfunctions.TestNanFunctions_Median)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/numpy/lib/tests/test_nanfunctions.py", line 613, in test_allnans
    assert_(len(w) == 3)
  File "/opt/anaconda/envs/np18py27-1.9/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 1350 tests in 7.853s

FAILED (failures=1)

Out[3]:

<nose.result.TextTestResult run=1350 errors=0 failures=1>
```

**Comment by sprodde** [comment]
It does still show erratic behavior in numpy 1.10.1 w/ python 2.7.10 in interactive consoles (once in a while it fails, once in a while it doesn't), but I haven't had this issue when starting directly as command line argument to python (no fail), as suggested above.

**Comment by mattip** [comment]
Remnant from pre-CI days. Closing
