### ISSUE TITLE
argpartition fails on non-ndarray array-likes

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#5524]
While `partition` works, as advertised, array-likeinputs like, e.g. lists:

```
>>> np.partition([5, 4, 3, 2, 1], 2)
array([1, 2, 3, 4, 5])
```

`argpartition` raises an error if its first argument is not an `ndarray`:

```
>>> np.argpartition([5, 4, 3, 2, 1], 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\WinPython-32bit-sp-dev\python-2.7.5\lib\site-packages\numpy\core\fromnumeric.py", line 680, in argpartition
    return a.argpartition(kth, axis, kind=kind, order=order)
AttributeError: 'list' object has no attribute 'argpartition'
```

**Comment by maniteja123** [comment]
If any array-like inputs are to be accepted, then as in ``argsort``, this can be implemented:

    try:
        argpartition = a.argpartition
    except AttributeError:
        return _wrapit(a, 'argpartition', kth, axis, kind, order)
    return argpartition(kth, axis, kind=kind, order=order)

else it can be like ``sort`` and ``partition``:

    if axis is None:
        a = asanyarray(a).flatten()
        axis = 0
    else:
        a = asanyarray(a).copy(order="K")
    return a.argpartition(kth, axis, kind=kind, order=order)

Just asking out of curiosity, the following example is shown in the documentation : 

    >>> x = np.array([3, 4, 2, 1])
    >>> x[np.argpartition(x, 3)]
    array([2, 1, 3, 4])

Now, if any array-like inputs are allowed, then the following behavior is needed.

    >>> x = [3, 4, 2, 1]
    >>>np.array(x)[np.argpartition(x, 3)]
    array([2, 1, 3, 4])
    >>>x[np.argpartition(x, 3)]
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    TypeError: only integer arrays with one element can be converted to an index

If this is the procedure to be followed, as in case of ``argsort``, I think it should be documented. Please correct me if no such use is needed in general scenarios.

**Comment by juliantaylor** [comment]
it probably should be like argsort, Don't remember why its not, maybe just a mistake, I can't remember there being a reason. compared to sort, partition can't be overridden from the C side but that shouldn't matter here.

**Comment by maniteja123** [comment]
I think the ``partition`` and ``sort`` C API functions are defined in ``item_selection.c``. Can you please clarify on what ``compared to sort, partition can't be overridden from the C side`` means ? Could I have a go at fixing this ?

**Comment by juliantaylor** [comment]
no, that is kind of intentional the C sort functions are part of a public struct, adding partition would break the ABI and just add more stuff that should not be in that place.
So I went with a internal lookupt able that could get hooks for user functions. But I don't think its really worthwhile, I don't think anybody would use it.

**Comment by maniteja123** [comment]
@juliantaylor Thanks for the clarification. I wasn't aware of the nature of public struct functions and the way in which they are maintained.
