### ISSUE TITLE
Polyfit better error message

### ISSUE THREAD

**Issue by dashesy** [numpy/numpy#5528]
``` text
    ValueError: On entry to DLASCL parameter number 4 had an illegal value
```

The following calls all result in the above error message.

``` python
    slopes, intercepts = np.polyfit([0,0], [100,101], 1)
    slopes, intercepts = np.polyfit([0,0], [100,100], 1)
    slopes, intercepts = np.polyfit([0], [100], 1)
```

Yes, these are all invalid cases for polynomial, but may arrise when input is computed itself and a better error message will help, something like "Not enough distinct points to construct the polynomial". One learns the former error message and the latter are loosely related but the latter is more explicit and does not leak the implementation details.
This is numpy version 1.8.2

**Comment by jaimefrio** [comment]
The best way to have an issue fixed is to fix it yourself: PRs are always welcome!

In case you want to try your hand at it, `np.polyfit` lives [here](https://github.com/numpy/numpy/blob/v1.9.1/numpy/lib/polynomial.py#L396), and is mostly Python code wrapping a call to a LAPACK routine.

**Comment by dashesy** [comment]
I started to look into this as you suggested, but this seems to be only a problem for the degenerate case when `x ` is all zeros. To avoid the need to check `x` for this case all the time and hurt the performance of every other good case, I came up with this:

```python
    try:
        c, resids, rank, s = lstsq(lhs, rhs, rcond)
    except ValueError:
        if not NX.any(x):
            raise ValueError("x is all zeros")
        raise
```

But I have a question about consistency among the trivial cases:


```python
    slopes, intercepts = np.polyfit([1], [100], 1)
```

The above just raises a warning `RankWarning: Polyfit may be poorly conditioned` so is it consistent to special case the all-zeros case? Is there any documentation or coding style?

**Comment by bsipocz** [comment]
The examples now consistently  give the `RankWarning`, so I suggest to close the issue.

However, now there is also a lower level error (the same error for all 4 examples).  I'm not sure whether it was around before or not, or whether was reported in another issue:
```
In [3]:     slopes, intercepts = np.polyfit([1], [100], 1)                                                              
Python(66498,0x7fff9ed51380) malloc: *** mach_vm_map(size=18446744072341000192) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3296: RankWarning: Polyfit may be poorly conditioned
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]: np.__version__                                                                                                  
Out[4]: '1.18.0.dev0+67ecbcf'
```

**Comment by pranjal-joshi** [comment]
Still getting the same error while using **`np.polyfit`**
`** On entry to DLASCLS parameter number  4 had an illegal value`

Any updates about fixing this issue? Or even muting this could help for my application!

**Comment by iustin94** [comment]
Also running into the same issue, confusing error message. Was there a merge request done for this?

**Comment by missechogao** [comment]
Here is my [test images](https://www.dropbox.com/s/k7r06739idtwwj2/test.tar.gz?dl=0) and [sample code](https://www.dropbox.com/s/x45sis2i9ljg7ko/stitching.cpp?dl=0)
