### ISSUE TITLE
ImportError: cannot import name multiarray

### ISSUE THREAD

**Issue by nilswagner** [numpy/numpy#5529]
nils@linux-5fmr:~/git/numpy> python setup.py install --prefix=$HOME/local
Running from numpy source directory.
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    setup_package()
  File "setup.py", line 235, in setup_package
    from numpy.distutils.core import setup
  File "/home/nils/git/numpy/numpy/distutils/__init__.py", line 37, in <module>
    from numpy.testing import Tester
  File "/home/nils/git/numpy/numpy/testing/__init__.py", line 14, in <module>
    from .utils import *
  File "/home/nils/git/numpy/numpy/testing/utils.py", line 17, in <module>
    from numpy.core import float32, empty, arange, array_repr, ndarray
  File "/home/nils/git/numpy/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name multiarray

**Comment by rgommers** [comment]
Try ``git clean -xdf`` and then rebuild.

**Comment by nilswagner** [comment]
I have installed numpy from scratch. The problem persists.

**Comment by rgommers** [comment]
? you're reporting a build error, so what do you mean you installed it?

**Comment by nilswagner** [comment]
Sorry for my inexactness
I actually mean

cd git
rm -rf numpy
git clone https://github.com/numpy/numpy.git
cd numpy
python setup.py install --prefix=$HOME/local

**Comment by rgommers** [comment]
OK. That doesn't really make sense, the error is from a line that is under ``if _INSTALLED:`` in ``numpy.distutils.__init__.py`` which cannot really be true. I suggest you do a little bit of debugging in that file.

**Comment by juliantaylor** [comment]
there might be a broken numpy installtion already present somewhere, check what it is trying to import in that line and delete it.
most likely something in $HOME/local or /usr/local

**Comment by nilswagner** [comment]
A similar ticket ...
https://github.com/numpy/numpy/issues/5467

**Comment by FireAndIce** [comment]
Thanks @rgommers! You helped me solve the issue. :)

**Comment by charris** [comment]
@FireAndIce What was the problem?

**Comment by sravanipolisetty** [comment]
similar issue. I'm a beginner to python and I have no clue why it is showing up like this. I tried to fix the issue by installing scipy but it showed the same error even when I'm trying to install scipy. I already installed numpy with zero errors.
![theano error](https://cloud.githubusercontent.com/assets/15863467/14910292/105d69d8-0dba-11e6-851d-b20ddd805eaf.PNG)
