### ISSUE TITLE
Bug in `ndarray.fill()` in combination with indexing using a boolean array

### ISSUE THREAD

**Issue by megies** [numpy/numpy#5552]
Sorry, if this is a duplicate but I could not find a matching issue..

I am reporting an issue that was introduced *after* version 1.8.2 and is present in all of 1.9.1, 1.9.2rc1 and master (a4cdc5b8d314fcf18faf29d82e84c877c4ed0e3f). I am on Python 2.7.9.

Here's a snippet to illustrate the issue:
```python
import numpy as np

a = np.arange(10)
print a

mask = a > 4
print mask

a[mask].fill(-1)
a[~mask].fill(-2)
print a

a[mask] = -1
a[~mask] = -2
print a
```

which produces..
```
[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True  True]
[0 1 2 3 4 5 6 7 8 9]
[-2 -2 -2 -2 -2 -1 -1 -1 -1 -1]
```

I've tried to `git bisect` to the responsible commit, but git seems to get confused, it stops the bisect run with the following message:
```
The merge base 6c729b4423857850e6553cf6c2d0fc8b026036dd is bad.
This means the bug has been fixed between 6c729b4423857850e6553cf6c2d0fc8b026036dd and [4563730a2d036307f1b67b2856d749aabdd8d546].
```
Here's the `git bisect log` afterwards:
```
git bisect start
# good: [4563730a2d036307f1b67b2856d749aabdd8d546] REL: Release 1.8.2
git bisect good 4563730a2d036307f1b67b2856d749aabdd8d546
# bad: [d44b9c61499f8bc5a9fc94286cd52f05e15e003f] REL: Release 1.9.1
git bisect bad d44b9c61499f8bc5a9fc94286cd52f05e15e003f
# bad: [6c729b4423857850e6553cf6c2d0fc8b026036dd] Merge pull request #3635 from charris/giant-style-cleanup
git bisect bad 6c729b4423857850e6553cf6c2d0fc8b026036dd
```

**Comment by pv** [comment]
Python semantics imply that: `a[mask].fill(-1)` is equivalent to `tmp =
a[mask]; tmp.fill(-1)`. `a[mask] = 1` is equivalent to
`a.__setitem__(mask, 1)`. `a[mask]` is a separate array from `a` by the
indexing rules.

**Comment by megies** [comment]
Uhm.. sorry, actually my above report is not correctly covering the issue we were experiencing.. I'll look into it more and report back. Anyway, our project's build was working on numpy 1.8.2 but not on 1.9.1 until after this change: https://github.com/obspy/obspy/commit/1f9aae37e8cab889a8f6568ad8edca1487cdf84f

**Comment by megies** [comment]
Nevermind, my report was wrong, looks like. Seems like the behavior of `fill` is the same on all versions and it only had an effect for us on certain numpy versions (changes in some precision issues, probably??). Anyway.. closing.

**Comment by seberg** [comment]
That change might make a difference in the obscure case of a 0-d array, which was somewhat buggy before.

**Comment by megies** [comment]
Actually we now think that our problem had to do with a `np.empty()` and a `.fill(0)` on parts of the arrays selected by indexing with a boolean mask. It seems that in Python environments with numpy 1.8.2 it consistently worked because the values that we wanted to zero-out (and didn't due to the fill not working) were already numbers like `1e-316` and the like while on Python environments with numpy 1.9.1 we encountered some values around `1e1` to `1e4` that were not set to zero and then caused problems.

It sounds extremely strange and we didn't find out how we could consistently encounter close-to-zero values on numpy 1.8.2 but not on 1.9.. anyway, sorry about stealing your time. ;)

**Comment by njsmith** [comment]
Could be the more aggressive caching/reuse of small array buffers that was
added as an optimization, so you became more likely to get old array data
in your "empty" arrays instead of generic memory. Glad you found the
problem in any case!
