### ISSUE TITLE
Handling Fortran data types with numpy.dtype

### ISSUE THREAD

**Issue by bartolsthoorn** [numpy/numpy#5553]
Hi, I'm converting some Fortran code to Python, and the data is in these types:
```fortran
FORMAT(2I4,I3,I5,2I3,2I4,14F6.1,F9.0,F6.1,F6.0,2F6.1,F6.3,F6.2,
F9.0,F6.1,F6.0,2F6.1,F6.3,2F7.2,F6.1,I3,I4,I6,I5,F10.2,5F9.2,I3,I4,2F6.1,2I6,F5.1)
```
(`2I4` means two consecutive columns have the data type `I4`)

I noticed that `numpy.dtype('I4')` seems to work, but `numpy.dtype('F6.1')` does not. Any advice on how I should handle this?

**Comment by pv** [comment]
This is apparently not a bug report --- please ask on stackoverflow.com
or on the mailing lists http://www.scipy.org/scipylib/mailing-lists.html
