### ISSUE TITLE
Get error from loading very small numbers from FORTRAN

### ISSUE THREAD

**Issue by yu-yuxuan** [numpy/numpy#5557]
For example, I get solution including 
3.14-114. with real(kind=8).
But python cannot identify the data. 

The error is as follows

/usr/lib64/python2.7/site-packages/numpy/lib/npyio.pyc in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin)
    825                 vals = [vals[i] for i in usecols]
    826             # Convert each value according to its column and store
--> 827             items = [conv(val) for (conv, val) in zip(converters, vals)]
    828             # Then pack it according to the dtype's nesting
    829             items = pack_items(items, packing)

ValueError: invalid literal for float(): 5.687138413593-304

**Comment by charris** [comment]
Is the data text? What does it look like?

**Comment by yu-yuxuan** [comment]
Yes, it is. 
Sometimes my code will product  5.687138413593E+03, it is OK
But when the exponent number larger than hundred or less than minus hundred. It will become 3.14-114.
It is the default output in Fortran.

**Comment by charris** [comment]
So is this a Fortran format problem? `3.14-114` is not a valid representation for a number in a text file and you correctly get an error.

**Comment by argriffing** [comment]
> So is this a Fortran format problem? `3.14-114` is not a valid representation for a number in a text file and you correctly get an error.

I didn't believe this, but it looks like it is legitimate Fortran floating point representation.

> The E edit descriptor has two forms.  For both of them the rules for input are the same as those for the F descriptor.  On output, E*w.d* produces a mantissa (significand) of *d* digits with an absolute value less than 1 over a field of *w*.  This must include room for a possible sign, the decimal point, and an exponent of four characters, consisting either of E followed by a sign and two digits, or of a sign and three digits.   The form with E is not used if the magnitude of the exponent is greater than 99.  E.g. 1.234 x 10^23 is written under E10.4 as *b*.1234E+24 or *b*.1234+024.

**Comment by charris** [comment]
What a kludge O_o. The question then is how to deal with it, we can't rely on Python. Maybe a special Fortran mode the runs the line through a fixer upper? I don't suppose there is a fix on the fortran side.

**Comment by yu-yuxuan** [comment]
Can I add some separator to define what is "the magnitude of the exponent " and what is "significand"

**Comment by pv** [comment]
@yu-yuxuan: you can perhaps write a function that converts this fortran format to floating point numbers, and use it in loadtxt via the `converters` argument https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html#numpy.loadtxt

**Comment by WarrenWeckesser** [comment]
If you can change the Fortran code, you can use the `Ew.dEe` format.  For example, the following code

```
      implicit none
      double precision x

      x = 123.45D101
      write(*, 20) x, x
20    format(1X, E20.6, E20.6E4)
      end
```
prints
```
         0.123450+104      0.123450E+0104
```
Otherwise, @pv's suggestion to use a custom converter should work.  Here's a possible implementation:
```
def conv(s):
    try:
        val = float(s)
    except ValueError:
        s = s.replace('+', 'E+').replace('-', 'E-')
        val = float(s)
    return val
```
If the `k`th column of your file (starting at 0) contains these Fortran formatted floating point values, use `converters={k: conv}` as an argument to `loadtxt`.

**Comment by yu-yuxuan** [comment]
@WarrenWeckesser  It works, thank you very much

**Comment by charris** [comment]
Going to close this now. @WarrenWeckesser Note that your converter will have problems with small negative floats, which likely have two `-`.

**Comment by WarrenWeckesser** [comment]
> Note that your converter will have problems with small negative floats, which likely have two -.

@charris Ah, right, a string such as '-1.2345-101' will break it.
