### ISSUE TITLE
Masked arrays don't properly edit views

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#5558]
I tried to change the mask of `a` through a subindexed view, but was unable. Using this setup I can reproduce this in the 1.9.1 version of NumPy.

```
import numpy as np

a = np.arange(6).reshape(2,3)
a = np.ma.masked_array(a, mask=np.ma.getmaskarray(a), shrink=False)

b = a[1:2,1:2]

c = np.zeros(b.shape, b.dtype)
c = np.ma.masked_array(c, mask=np.ma.getmaskarray(c), shrink=False)
c[:] = np.ma.masked
```

This yields what one would expect for `a`, `b`, and `c` (seen below).

```
 masked_array(data =
   [[0 1 2]
    [3 4 5]],
              mask =
   [[False False False]
    [False False False]],
         fill_value = 999999)

 masked_array(data =
   [[4]],
              mask =
   [[False]],
         fill_value = 999999)

 masked_array(data =
   [[--]],
              mask =
   [[ True]],
         fill_value = 999999)
```

Now, it would seem reasonable that to copy data into `b` from `c` one can use `__setitem__` (seen below).

```
 b[:] = c
```

This results in new data and mask for `b`.

```
 masked_array(data =
   [[--]],
              mask =
   [[ True]],
         fill_value = 999999)
```

This should, in turn, change `a`. However, the mask of `a` remains unchanged (seen below).

```
 masked_array(data =
   [[0 1 2]
    [3 0 5]],
              mask =
   [[False False False]
    [False False False]],
         fill_value = 999999)
```

**Comment by stuarteberg** [comment]
@jakirkham, In your example code, I don't understand why you expect `a.mask` to be changed.  The masks for all three arrays `a`, `b`, and `c` are `False` everywhere.  Is the example missing a line such as `c.mask[:] = True`?

**Comment by jakirkham** [comment]
@stuarteberg Yes, sorry. You are correct I was missing such a line.

Generally, the documentation recommends one to assign as so `c[:] = np.ma.masked`. However, as we have ensured the mask is simply an array, it is also mentioned that you can do this as you have `c.mask[:] = True`.

**Comment by jakirkham** [comment]
This code seems to stop propagation of the mask and it is not clear to me why this is necessary ( https://github.com/numpy/numpy/blob/4bfcf4801ceedd0563e3648154fc49985729c442/numpy/ma/core.py#L3129-L3132 ). As the mask is not hard here, it should not be a problem to have propagation.

**Comment by jakirkham** [comment]
Same situation here ( https://github.com/numpy/numpy/blob/master/numpy/ma/core.py#L3112-L3113 ). I don't understand why only fields of masked record arrays can share masks, but nothing else. Is there something special we want to avoid in record arrays? If so, couldn't we accomplish this without ruining the possibility of editing views on an ordinary masked array?

**Comment by jjhelmus** [comment]
This issue was also reported in #1903.

**Comment by jakirkham** [comment]
Should this issue be added to 1.14.0 milestone (as that is where the fix landed)?

**Comment by charris** [comment]
Once it is in it doesn't matter. We don't rely on the milestone tag except to mark something as a potential release blocker.
