### ISSUE TITLE
Numpy structured arrays and logical indexing

### ISSUE THREAD

**Issue by jmlarson1** [numpy/numpy#5559]
Assigning values to Numpy structured arrays produces very odd behavior. For example, the following does not assign correctly:

    H = np.zeros(4, dtype=[('ind','float')])
    H['ind'] = np.arange(1,5)
    H['ind']
        array([ 1.,  2.,  3.,  4.])
    x = [False, True, False, True]
    H['ind'][np.ix_(x)]
        array([ 2.,  4.])
    H[np.ix_(x)]['ind'] = [-1, -1]
    H
        array([(1.0,), (2.0,), (3.0,), (4.0,)], 
              dtype=[('ind', '<f8')])

If I attempt to make the change recommended here: https://github.com/numpy/numpy/issues/3561, it still does not even change the first entry indexed:

    H[np.ix_(x)]['ind'][:] = [-1,-1]
    H
        array([(1.0,), (2.0,), (3.0,), (4.0,)], 
              dtype=[('ind', '<f8')])

Why might this be the case?

**Comment by pv** [comment]
The above examples appear to be modifying copies of the original array,
as per these rules:
http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing

**Comment by jmlarson1** [comment]
If that is the case, then why does this work then?

    H = np.arange(1,5)
    x = [False, True, False, True]
    H[np.ix_(x)] = [-1, -1]
    H
        array([ 1, -1,  3, -1])

**Comment by pv** [comment]
This is sort of a FAQ question.
A[b] = c is syntax sugar for A.__setitem__(b, c)

**Comment by jmlarson1** [comment]
Yes, that is surprising. It is also surprising that the Structured Array documentation doesn't mention that there is something different performed when assigning to Array[index]['field'] vs Array['field'][index]. 

    H = np.zeros(4, dtype=[('ind','float')])                                                                                                                                                   
    H['ind'] = np.arange(1,5)                                                                                                                                                                  
    x = [False, True, False, True]                                                                                                                                                             
    H[np.ix_(x)]['ind'] = [-1 -1]                                                                                                                                                              
    H
    array([(1.0,), (2.0,), (3.0,), (4.0,)], 
          dtype=[('ind', '<f8')])
    H['ind'][np.ix_(x)] = [-1,-1]
    H
    array([(1.0,), (-1.0,), (3.0,), (-1.0,)], 
          dtype=[('ind', '<f8')])

I (and the numerous bug reports https://github.com/numpy/numpy/issues/3561, https://github.com/numpy/numpy/issues/2598, https://github.com/numpy/numpy/pull/4556, https://github.com/numpy/numpy/issues/3126) assume that assigning to Array[index]['field'] is equivalent to assigning to Array['field'][index]. This seems understandable since no Exception is raised when assigning either way, and 

    Array['field'][index] == Array[index]['field']

**Comment by seberg** [comment]
Because `arr['field']` is always a view into an array while `arr[index]` is **not**. The whole fact that it works for the case where `arr[index]` is an item is an ugly hack (IMO) that probably nobody thought about too much.
This choice means that structured scalars are mutable objects and are a view into the original array. For `index` being advanced indexing there is simply not even a hackish solution to make it work, it is technically impossible.

**Comment by jmlarson1** [comment]
Thank you for the reply. Is it possible to add a warning to the structured array documentation that assigning to `arr[index]` can have unexpected results? Given the bug reports I mention above (where only the first element gets changed) suggests this is far from an isolated issue.
