### ISSUE TITLE
MaskedArray.trace() inconsistent with ndarray.trace() for arrays with ndim>2

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#5560]
The `trace` method for a masked array with more than 2 dimensions does not appear to respect the `axis1` and `axis2` methods.  In fact, for a 3-dimensional array, `MaskedArray.trace` does not return an array as `ndarray.trace` does, but appears to return the sum of the relevant array.  See the code sample below.

```
In [782]: A = arange(2*4*4).reshape(2,4,4)

In [783]: A.trace(axis1=1, axis2=2)
Out[783]: array([30, 94])

In [784]: Am = ma.masked_array(A, False)

In [785]: Am.trace(axis1=1, axis2=2)
Out[785]: 124.0
```

**Comment by maniteja123** [comment]
I think it is actually returning the sum of the diagonal, see [this](https://github.com/numpy/numpy/blob/master/numpy/ma/core.py#L4518). But I have no idea why this is done, also the ``ma.trace`` function would work just fine if the mask was ``np.ma.nomask`. 
    
    >>>am = np.ma.masked_array(A,np.ma.nomask)
    >>>am.trace(axis1=1,axis2=2)
    masked_array(data = [ 30.  94.],
             mask = False,
       fill_value = 1e+20)

Hope it helps :)

**Comment by eric-wieser** [comment]
Still present in 1.14-dev
