### ISSUE TITLE
tools/swig/numpy.i gives syntax error when swigged in C mode

### ISSUE THREAD

**Issue by vallis** [numpy/numpy#5561]
The "@#ifdef __cplusplus" guard at the end of tools/swig/numpy.i doesn't seem to be honored by the latest SWIG (3.0.5, or indeed older ones back to 2.0.4). As a result, swig imports std_complex.i, and tries to setup std::complex definitions, which it can't manage in C mode. By contrast, everything works with "swig -c++".

**Comment by charris** [comment]
This came in with #5308.  @gmabey Thoughts?

**Comment by vallis** [comment]
Perhaps it's as simple as having to use #ifdef instead of @#ifdef?

**Comment by gmabey** [comment]
Uhmm -- likely so; sorry about that .

**Comment by charris** [comment]
@vallis Want to make a PR?

**Comment by charris** [comment]
Fixed in #5568.
