### ISSUE TITLE
IndexError when extracting noncontiguous columns and rows from matrix

### ISSUE THREAD

**Issue by endisway** [numpy/numpy#5574]
Test case:
```python
>>> A=np.random.rand(4,4)
>>> A[(0,3),(0,2,3)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,)
```

However, `A[(0,3),(0,2,3)]` is a question with a very definite answer which can be obtained by calling
```python
>>> A[(0,3),:][:,(0,2,3)]
```

I can't think of any situation in which this might be ambiguous or indefinite, so if in fact none exists, I propose that numpy should return this result instead of an exception.

Thank you for your work!

**Comment by argriffing** [comment]
There's an `ix_` function that does something like this.
```python
>>> import numpy as np
>>> a = np.random.rand(4,4)
>>> a[(0,3),:][:,(0,2,3)]
array([[ 0.84060636,  0.69065912,  0.0026522 ],
       [ 0.61781349,  0.98709272,  0.97869428]])
>>> a[np.ix_((0,3),(0,2,3))]
array([[ 0.84060636,  0.69065912,  0.0026522 ],
       [ 0.61781349,  0.98709272,  0.97869428]])
```

**Comment by endisway** [comment]
Yes of course there are other ways to get the same result, indeed I got it with the syntax I reported, and I can see how with very large/sparse arrays, `ix_()` could be a better idea than nested `__getitem__`s with a temporary allocation in between. However I still suggest that the "basic"  square bracket syntax (and thus `__getitem__`) should behave the same way, instead of throwing an exception on very reasonable input, which in my view sounds like buggy behavior.

**Comment by pv** [comment]
The behavior suggested above becomes inconsistent when the two lists are
of the same length.

**Comment by endisway** [comment]
Oh ok, I didn't know that. Neat. I still feel this is inconsistent with slicing (which uses the same "operator" to extract a submatrix), however there's absolutely no point in changing anything, and I may be thinking too Matlab-y.
Please close this bug, and thanks for your time.

**Comment by njsmith** [comment]
Yes, this also confused me when I started using Numpy. You just have to
memorize that "fancy" indexing uses a totally different rule to combine
multiple indexes than slicing does. It's much more powerful this way,
granted, and it's far too late to change now. But it is confusing.

To get what you originally wanted, you can make it so the indices do
broadcast broadcast against each other:

arr[ np.reshape([1, 3, 5], (3, 1)), np.reshape([2, 4, 6], (1, 3)) ]
