### ISSUE TITLE
Problems with handling AMD64 Pile Driver

### ISSUE THREAD

**Issue by cjwilliams43** [numpy/numpy#5575]
scipy errors and failures due to piledriver:

(1) ERROR: test_improvement (test_quadpack.TestCtypesQuad)
     WindowsError: [Error 193] %1 is not a valid Win32 application

(2) ERROR: test_typical (test_quadpack.TestCtypesQuad)
     WindowsError: [Error 193] %1 is not a valid Win32 application

(3) FAIL: test_interpolate.TestInterp1D.test_circular_refs
     ReferenceError: Remaining reference(s) to object

(4) FAIL: test__gcutils.test_assert_deallocated
     ReferenceError: Remaining reference(s) to object

Colin W.  with thanks to Carl Kleffner

**Comment by pv** [comment]
By piledriver you mean the intel cpu arch? Not clear to me how these are
related to that. But I assume you mean these occur on Carl's win64 build?

**Comment by njsmith** [comment]
Also, if these are scipy errors, you should probably file a bug against the
scipy project.

**Comment by cjwilliams43** [comment]
Nathaniel,

I understand that both numpy and scipy are impacted.

Colin S.

**Comment by matthew-brett** [comment]
Colin - you've listed some scipy errors here - did you also get numpy test errors?  Why do you think both numpy and scipy are affected?

**Comment by cjwilliams43** [comment]
Matthew,

In an earlier post you said:
"By piledriver you mean the intel cpu arch? Not clear to me how these 
are related to that (and not more generally to win64). I assume you mean 
these occur on Carl's win64 build?"

I'm not familiar with the differences between the AMD and Intel 
architectures, but I understand that the problem is specifically with 
the AMD64.

Yes, this is based on Carl's build.

Colin W.

**Comment by juliantaylor** [comment]
if its really cpu dependent its more likely a problem of the BLAS library, numpy has no x86 cpu specific code.

**Comment by njsmith** [comment]
We haven't seen any numpy errors here anyway yet...

**Comment by pv** [comment]
Moved to https://github.com/scipy/scipy/issues/4528
