### ISSUE TITLE
wrong eigenvectors when using linalg.eig

### ISSUE THREAD

**Issue by aloctavodia** [numpy/numpy#5578]
```python 
import numpy as np
A = np.array([[1,2], 
            [0,1]])

np.linalg.eig(A)
```
returns

[[  1.00000000e+00  -1.00000000e+00]
 [  0.00000000e+00   1.11022302e-16]]
The second eigenvector is [0, 0], that is OK, but for the first one I was expecting [1, 0] like in [here](http://www.wolframalpha.com/input/?i=eigenvectors%28%5B1%2C+2%5D%2C+%5B0%2C++1%5D%29) 

It is also easy to check that the correct solution should be [1, 0] and not [1, -1].

Is this a bug or the expected behaviour? Am I doing something wrong?

**Comment by charris** [comment]
The eigenvectors are in the columns ;)

**Comment by aloctavodia** [comment]
ohh men!!! Sorry for that. Thanks!
