### ISSUE TITLE
Integer arithmetic doesn't use SIMD

### ISSUE THREAD

**Issue by d1manson** [numpy/numpy#5586]
See [this SO question](http://stackoverflow.com/q/28592415/2399799).

Addition of two integer arrays should be using SIMD, as should all other ufunc(ish) integer functions.  Currently all integer arithmetic takes roughly 3-5 times longer than 32-bit float operations. 

In the most extreme example, for the case of 8bit integers, this means there is probably a 12-20 times potential speedup not being used, which is a real shame.

**Comment by juliantaylor** [comment]
they are using simd in 1.10,but unlike floats only if the compiler is able to vectorize it.
manually vectorizing integer operation is quite annoying

**Comment by juliantaylor** [comment]
see https://github.com/numpy/numpy/pull/5144
