### ISSUE TITLE
numpy.linalg.svd hangs on bad input, fails to raise LinAlg("SVD did not converge") error

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#5588]
When an SVD calculation does not converge, normally we get `LinAlgError: SVD did not converge`.  For some matrices, this does not occur, and numpy remains in `svd_n_s` forever:

```
In [4]: a = array([[0., 0.],[nan, nan]])

In [5]: np.linalg.svd(a)
```

Rather than raising an exception, this causes numpy to hang indefinitely.

**Comment by argriffing** [comment]
Possibly related to https://github.com/numpy/numpy/pull/4324.

**Comment by sethtroisi** [comment]
Works in 1.16
```Python
>>> a = np.array([[0., 0.],[np.nan, np.nan]])
>>> np.linalg.svd(a)
(array([[nan, nan],
       [nan, nan]]), array([nan, nan]), array([[nan, nan],
       [nan, nan]]))
```

**Comment by mattip** [comment]
Thanks @sethtroisi. Closing. If someone can reproduces, please reopen with a note about what version and platform it fails on.
