### ISSUE TITLE
numpy.interp always uses a binary search of entire array -- may be slower than necessary.

### ISSUE THREAD

**Issue by newville** [numpy/numpy#5593]
`numpy.interp(x, xp, fp)`  uses a binary search  (https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/compiled_base.c#L495) of the entire input array to find the proper index for the linear interpolation. 

For nearly-monotonic target array (``x``) with spacing finer or similar to the original data, storing the last index and looking in the near vicinity of it (say +/- 1) can find the correct index much faster for many cases.   For the very common cases of a) interpolating data onto a finer grid, or b) making a small perturbation of the ``xp`` (say, a constant offset or a slight expansion or rotation),  storing the previous value and looking +/- 1 can avoid binary search at almost all values.   

Though binary search is efficient, a search through the entire array can be a serious bottleneck for large arrays.  Thus, storing and the index found for element N and using it as the starting search value for element  N+1 may offer a significant boost in performance.

**Comment by jaimefrio** [comment]
This one was fixed by #5594.
