### ISSUE TITLE
read_array_header_1_0 returns None

### ISSUE THREAD

**Issue by nicain** [numpy/numpy#5602]
When trying to read from a .npy file, the np.lib.format-read_array_header_1_0 function returns None instead of the intended triple of shape, fortran, dtype. 

Seems to me that numpy/lib/format.py line 379 needs a "return" to get the tuple back from the call.

Code snippet to reproduce the error:

# Create some junk data:
import numpy as np
filename = 'mp.npy'
data = np.random.random((10,100)).astype(np.float32)
np.save(filename, data)

# The error is caused by:
with open(filename, 'rb') as fhandle:
    major, minor = np.lib.format.read_magic(fhandle)
    shape, fortran, dtype = np.lib.format.read_array_header_1_0(fhandle)

**Comment by charris** [comment]
Hmm, same with `read_array_header_2_0`. The functions are not actually used anywhere and are only tested to see if they raise an appropriate error. Want to put together a PR?

**Comment by nicain** [comment]
Damn, that was a fast turn around

EEK I don’t even know what PR means… Pull Request?

Is there an FAQ for fork/edit/pull request, to guide me through?  Also, how do I run the unit tests to make sure I don’t break anything when I make the change.

Best,
-n

**Comment by charris** [comment]
Take a look at https://github.com/numpy/numpy/blob/master/CONTRIBUTING.md and follow the links. You can run tests from your local repo with `python runtests.py`, start with `python runtests.py --help`. Feel free to ask for help.

**Comment by njsmith** [comment]
Also note that when you submit a pull request, then the tests get run
automatically (in a bunch of different configurations) and the results
listed on the pull request web page. So you'll still probably want to run
the tests yourself to catch silly bugs, but you don't have to be too
paranoid, because you will have that backup check.

On Tue, Feb 24, 2015 at 4:20 PM, Charles Harris <notifications@github.com>
wrote:

> Take a look at https://github.com/numpy/numpy/blob/master/CONTRIBUTING.md
> and follow the links. You can run tests from your local repo with python
> runtests.py, start with python runtests.py --help. Feel free to ask for
> help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5602#issuecomment-75880407>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by nicain** [comment]
Thanks for the help  Here is the test I wrote to exercise the issue:

# test_read_array_header_1_0.py

import sys
sys.path.insert(1, '/local1/numpy-dev/lib/python2.7/site-packages')
import numpy as np

def test_read_array_header_1_0():
    filename = 'mp.npy'
    data = np.random.random((10,100)).astype(np.float32)
    np.save(filename, data)
    
    with open(filename, 'rb') as fhandle:
        major, minor = np.lib.format.read_magic(fhandle)
        shape, fortran, dtype = np.lib.format.read_array_header_1_0(fhandle)
        
if __name__ == "__main__":
    test_read_array_header_1_0()

I am going to update my fork, and then submit a pull request.  Thanks for the help!

**Comment by nicain** [comment]
OK I see that travis-ci is passing the changes in my pull request: https://travis-ci.org/numpy/numpy/builds/52076121

I probably don't have permissions to push upstream, what is the next step to finish off?

**Comment by charris** [comment]
Wait for code review. One of the developers will do the actual merge after review. No one escapes that bottleneck ;)

**Comment by nicain** [comment]
I have been writing up some tests in lib/tests/test_format.py, and found that there is no header_data_from_array_2_0 function in format.py.  Is this intentional?  Should I be doing something else to create the tests? 

https://github.com/nicain/numpy/commit/0afaecb139a879efa5c0d8884eb04317729532ac
