### ISSUE TITLE
set_printoptions does not work with numpy structured arrays 

### ISSUE THREAD

**Issue by jmlarson1** [numpy/numpy#5606]
I want to set the print precision for a numpy structured array, but it does not seem to work. 

```
H = np.zeros(1, dtype=[('x','float',2),('f','float')])
H['x']= np.random.uniform(0,1,(1,2))
H['f']= np.random.uniform(0,1)
np.set_printoptions(precision=3)
print(H)
```

leaves

```
[([0.5928384015048476, 0.6187004067605606], 0.2981617279773586)]
```

not 

```
[([0.593, 0.619], 0.298)]
```

as I expected. Printing H['x'] works (because that's not a structured array), but I have many fields in my structured array and I don't want to have to print each one when monitoring the progress of my code.

**Comment by manodeep** [comment]
My tests show that this issue has been (at least somewhat) solved somewhere between `1.11.3` and `1.12.1`. A simple test case of printing a structured array (containing floats) shows that `1.12.1` honors `precision` set by `np.set_printoptions` while `1.11.3` does not. 

I uncovered the issue via [failing doctests](https://travis-ci.org/manodeep/Corrfunc/jobs/325890970#L2189) for [source code](https://github.com/manodeep/Corrfunc/blob/DDsmu/Corrfunc/utils.py#L672)

**Comment by mhvk** [comment]
@manodeep - thanks for bringing this back to attention - this is indeed solved, so I'll close the issue.

@jmlarson1 - apologies that this was not followed up on directly - though clearly you were not alone in wondering, and the problem did get addressed. Please do not hesitate to report other problems!

**Comment by michael135** [comment]
@mhvk 
@manodeep 
@jmlarson1 

It seems not to be solved on arrays which include strings and floats:
`np.set_printoptions(precision = 20)
test_x[:3,:]`

**Output:**
```
array([[5, 5, 'dm', 'tdl', 1.6094379124341003, 54.0, 0.10517539946498722, 1.3862943611198906, 19.0, 0.04312932056672845, 1.791759469228055, 10.0, 0.06190778404270464, 1.791759469228055, 40.0, 0.15725465338980327],
       [6, 5, 'dm', 'tdl', 1.3862943611198906, 19.0, 0.04312932056672845, 1.791759469228055, 10.0, 0.06190778404270464, 1.791759469228055, 40.0, 0.15725465338980327, 1.791759469228055, 38.0, 0.07880509717964533],
       [7, 5, 'dm', 'tdl', 1.791759469228055, 10.0, 0.06190778404270464, 1.791759469228055, 40.0, 0.15725465338980327, 1.791759469228055, 38.0, 0.07880509717964533, 2.833213344056216, 80.0, 0.0982000110271209]], dtype=object)
```

**Comment by eric-wieser** [comment]
`precision` does not apply to arrays with `dtype=object`, as that would require us to know what type of object is stored within it.

**Comment by michael135** [comment]
> `precision` does not apply to arrays with `dtype=object`, as that would require us to know what type of object is stored within it.

That means, that it's impossible to apply to "mixed array" (string and floats)?

**Comment by eric-wieser** [comment]
Numpy has no concept of a "mixed" array, only of `object` arrays containing elements of unknown types. Your array would probably work better as a structured array (what this issue is actually about), because then numpy keeps track of the type of each column separately.

**Comment by michael135** [comment]
Thank you Eric!
