### ISSUE TITLE
development environment .rst doc is not advertised?

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5608]
https://github.com/numpy/numpy/blob/master/doc/source/dev/development_environment.rst

This file has useful information especially about `runtests.py` but I do not see how it is linked with the rest of the numpy documentation.

**Comment by DanielSank** [comment]
As a would-be contributor who's pull request failed because I didn't know how to run the tests before submitting:

+1

**Comment by pv** [comment]
It's linked, but the docs on the website were last built in November and the addition is newer than that

**Comment by bsipocz** [comment]
Please close.
Now this is available and reachable via a few clicks from the main numpy.org website.

**Comment by charris** [comment]
@bsipocz Thanks for the heads up.
