### ISSUE TITLE
Unexpected result when feeding empty array into atleast_2d

### ISSUE THREAD

**Issue by mtrbean** [numpy/numpy#5611]
I was expecting a square array `array([], shape=(0, 0), dtype=float64)`, but got `shape=(1,0)`. Is this the intended behavior?

    In [14]: np.empty(0).shape
    Out[14]: (0,)

    In [15]: np.atleast_2d(np.empty(0))
    Out[15]: array([], shape=(1, 0), dtype=float64)

The reason is that I needed a 2D array from `hsplit` and `vhsplit`, but the dimension is not preserved when the result happens to be empty (gh-4102). I tried to work around the issue with `atleast_2d`, and found that it doesn't work because `atleast_2d` doesn't give me a square array with shape `(0,0)`

**Comment by maniteja123** [comment]
I guess this is the intended behavior, at least with respect to the way dimensions of the ``ndarrays``  are defined

    >>>np.array([]).shape
    (0,)
    >>>np.array([[]]).shape
    (1, 0)
    >>>np.array([[],[]]).shape
    (2, 0)
    >>>np.array([[[]]]).shape
    (1, 1, 0)

And each of these are interconvertible using ``reshape``. In this case, the resulting dimension is (1,0) because of [this](https://github.com/numpy/numpy/blob/master/numpy/core/shape_base.py#L103)

    result = ary[newaxis,:]
 
    >>>a = np.array([])
    >>>a.shape
    (0, )
    >>>a[None,:].shape
    (1, 0)
    >>>a[np.newaxis,:].shape
    (1, 0)

Hope it helps :)

**Comment by mtrbean** [comment]
Thanks, but I'm not convinced.

It's obvious that `np.array([[]])` should have shape `(1, 0)`, because that first dimension contains one element, which is an empty array. I have no problem with that.

However I'm looking to construct a 2-d array with shape (0,0), and I'm expecting `atleast_2d` or `newaxis` will give me that. At least to me, the following looks somewhat arbitrary:

    In [2]: np.atleast_1d([]).shape
    Out[2]: (0,)
    
    In [3]: np.atleast_2d([]).shape
    Out[3]: (1, 0)
    
    In [4]: np.atleast_3d([]).shape
    Out[4]: (1, 0, 1)

    In [5]: np.__version__
    Out[5]: '1.9.1'

I was expecting  `(0,)`, `(0,0)`, `(0,0,0)` respectively.

**Comment by maniteja123** [comment]
I don't think I am that acquainted with the reasons behind the behavior, someone more experienced should be answering it :)

**Comment by njsmith** [comment]
I'm not sure why you expect that? The rule is that atleast_* always add a
dimension with length 1. This is a simple rule that always works, so that's
what they do for empty arrays too. I guess you think there should be a
special case?

**Comment by jaimefrio** [comment]
If you want an array of shape `(0, 0)` you can always set it explicitly yourself:

```
>>> a = np.array([])
>>> a.shape
(0,)
>>> a.shape = (0, 0)
>>> a.shape
(0, 0)
```

Actually, as long as the total array size is unchanged, i.e. there is a zero somewhere in the shape, you can do whatever you want with the shape:

```
>>> a.shape = (237, 0, 457)
>>> a.shape
(237, 0, 457)
```

The behavior of `atleast_xd` and `newaxis` is one that works with any array, including empty ones. Why does it even make a difference to you if the empty array is square or not? Does it even make sense to worry about the shape of an empty array? What generic benefit do you see in changing the behavior of `atleast_xd` to support your particular choice of behavior?

**Comment by mtrbean** [comment]
I can explain what I was trying to do.

I am splitting a covariance matrix (a square array) into 4 blocks
    
    [[A B]
     [C D]]

where A and D are also square.

Now I want to compute A - C * A^-1 * B [conditional cov of normal distribution](http://en.wikipedia.org/wiki/Multivariate_normal_distribution#Conditional_distributions):

But `np.linalg.solve` (or blas itself) throws error if A is not square. To reproduce:

    In [3]: np.linalg.solve(np.atleast_2d([]), np.array([]))
    LinAlgError: Last 2 dimensions of the array must be square

Since it's just a corner case that happens when A happens to be a 0 by 0 matrix, I guess it's no big deal (I can just work around that by slicing instead of using `np.split`). I was trying to see if there is any good reason for the current behavior to exist, and whether my use case warrants numpy handling empty array as a special case.

**Comment by njsmith** [comment]
Can you paste the code you're using to break up the matrix?

**Comment by mtrbean** [comment]
I was doing (doesn't work)

    c1, c2   = np.vsplit(arr, [index])
    c11, c12 = np.hsplit(c1, [index])
    c21, c22 = np.hsplit(c2, [index])

And now I'm using slicing. (This works for me)

    c11 = arr[:index, :index]
    c12 = arr[:index, index:]
    c21 = arr[index:, :index]
    c22 = arr[index:, index:]

**Comment by seberg** [comment]
I don't think linalg.solve currently supports empty arrays (even when they are squared, but if it already does, good).
Yes, splitting should just do slicing, but at this time does not yet. In any case, the behaviour is all correct, except for the behaviour of `np.{h|v}?split`, which *should* just do slicing, but replaces empty arrays (as you saw in the new warning). Only makes me wonder if we should add some transition helper for the split functions.

**Comment by njsmith** [comment]
Anything else to sort out here? It sounds like the problem is that `hsplit`/`vsplit` were improperly discarding dimensions and that's already being addressed by an ongoing deprecation, so this can just be closed?

**Comment by mtrbean** [comment]
Sure. Closing.

**Comment by njsmith** [comment]
Thanks!

On Tue, Mar 3, 2015 at 11:21 PM, Eric Wong <notifications@github.com> wrote:

> Sure. Closing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5611#issuecomment-77108202>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org
