### ISSUE TITLE
Have an `exp` for pure imaginary numbers

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#5625]
It would be nice to have a pure imaginary `exp` implemented like `npy_cexp`, but only for pure imaginary arguments (maybe `npy_iexp` or `npy_ciexp`). It would take a real value `$\theta$` and evaluate `$e^{i\cdot\theta}$`. The hope is this would be a little bit faster in cases where it is know there is no real part to the complex number.

**Comment by charris** [comment]
There have been previous proposals/discussions for a (cos, sin) function, and, IIRC, an `expj` function (this one). Might try a search of the mailing list archives.

**Comment by jakirkham** [comment]
Alright, thanks. I'll take a look. Do you know off hand if there is a reason previous proposals haven't been incorporated?

**Comment by argriffing** [comment]
It seems to be a thing in mpmath
http://docs.sympy.org/0.7.5/modules/mpmath/functions/powers.html#mpmath.expj

**Comment by ewmoore** [comment]
I'd bet part of it is that the gains aren't very large relative to just
calling sin and cos since the portable implementation is to call sin and
cos.

**Comment by jakirkham** [comment]
@argriffing Thanks. I'll take a look. Though I still see some value in having it in NumPy.

@ewmoore I'm not sure if you are referencing the implementation in C or Python. If you mean the latter, taking a few simple examples I find using `numpy.sin` and `numpy.cos` to 33% slow than simply doing `numpy.exp` with `1j` multiplying my value. My speculation is the creation of temporaries hurts here. If you were meaning the prior, I would hope skipping steps that handle the real value would cut down on the cost of the function in C. If I have completely missed you point, feel free to clarify.

**Comment by charris** [comment]
There is a `void sincos (double x, double *sinx, double *cosx)` function in gcc, it is an gnu extension.

**Comment by jakirkham** [comment]
@charris Interesting. So, are you thinking that exposing a form of sincos in NumPy would be worthwhile? I think there is something similar in clang.

**Comment by charris** [comment]
Yes, I think it would be worthwhile, there are some common operations involved, reduction of interval, etc. Probably the easiest way to expose it would be as `expj` with a real argument, although one could also return two arrays. Should probably be discussed on the list, again ;)

**Comment by juliantaylor** [comment]
note glibc internally already uses sincos for the computation of cexp, so there is not much to gain.

**Comment by jakirkham** [comment]
@juliantaylor but the NumPy version does not seem to use `cexp`, but calls `sin` and `cos` separately [npy_math_complex.c.src#L230-L231]( https://github.com/numpy/numpy/blob/35d01b2a7cd38b2fda54b148402919aa1dd7e9c4/numpy/core/src/npymath/npy_math_complex.c.src#L230-L231 ). Unless, this is something the compiler can optimize out, which I don't know, I would think using `sincos` or `cexp` would be better.

**Comment by juliantaylor** [comment]
that is the fallback version for when libc does not provide the function. It should only be used on windows. On windows you also should not have sincos available.
A decent compiler (like gcc) can optimize a call to sin and cos to a sincos, unfortunately that does not work when using the npy_ indirection.

**Comment by jakirkham** [comment]
Ah ok, sorry, so is there some other code I should be looking at?

**Comment by juliantaylor** [comment]
should be https://github.com/numpy/numpy/blob/35d01b2a7cd38b2fda54b148402919aa1dd7e9c4/numpy/core/src/npymath/npy_math_complex.c.src#L1772

**Comment by jakirkham** [comment]
Alright, thanks for your help. I'm going to close this as using `cexp` is the best that could be hoped for here. If someone disagrees, they are welcome to reopen the issue.

**Comment by juliantaylor** [comment]
glibc does not do a real = 0 optimization so there is still a exp(0) call in there that makes some overhead.
I wonder if they would accept this optimization, I think it makes sense as getting the sincos use right is probably not that simple, floating point has a lot of special cases.

**Comment by juliantaylor** [comment]
I sent a patch, not super significant but measureable
https://sourceware.org/ml/libc-alpha/2015-03/msg00139.html

**Comment by jakirkham** [comment]
@juliantaylor, the `cexp(0+a*I)` was my concern, as well. It seemed like the C99 spec didn't guarantee this optimization. Thanks for sending the patch.

Just out of curiosity, what did you find the improvement to be? I don't care about a formal benchmark just a rough idea would be interesting.

I don't know if this sort of thing still has an effect on performance, but it probably could be shortened to a ternary expression.
