### ISSUE TITLE
[BUG] np.allclose does not work with np.timedelta64

### ISSUE THREAD

**Issue by cloudformdesign** [numpy/numpy#5630]
http://stackoverflow.com/questions/28857937/trying-to-check-data-frequency-with-pandas-series-of-datetime64-objects/28858228?noredirect=1#comment45982435_28858228

It works fine with `datetime64`. Currently you have to convert to datetime in order to check allclose

**Comment by gerritholl** [comment]
I think this is a duplicate of #5610 as it's in `isfinite` that `allclose` fails.

**Comment by cloudformdesign** [comment]
Looks that way. Great point
