### ISSUE TITLE
f2py C to fortran mapping file files under python 3.3

### ISSUE THREAD

**Issue by DavidPowell** [numpy/numpy#5637]
Under python 3.3, f2py fails to read the file `.f2py_f2cmap`, for mapping fortran types to C types. It gives an exception `RuntimeError: dictionary size changed during iteration`. This is due to python 3's `keys()` and `items()` members of dictionaries returning iterators instead of lists. In `capi_maps.py` there is iteration over these functions, during which the dictionary is modified. This should be fixable by wrapping these calls with `list()`, which reproduces the old python 2 behaviour.

**Comment by jaimefrio** [comment]
LGTM. Is it possible, and does it make sense to write a test for this?
