### ISSUE TITLE
How can I install numpy1.92?

### ISSUE THREAD

**Issue by sonicsome2** [numpy/numpy#5639]
WIN7 64bit
Winpython: Python 3.4.3.1 64bit

Problems as follows:

F:\numpy-1.9.2>python setup.py install
Running from numpy source directory.
D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutils\dist.p
y:260: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
non-existing path in 'numpy\\distutils': 'site.cfg'
non-existing path in 'numpy\\f2py': 'docs'
non-existing path in 'numpy\\f2py': 'f2py.1'
F2PY Version 2
blas_opt_info:
blas_mkl_info:
  libraries mkl,vml,guide not found in ['D:\\Program Files\\WinPython-64bit-3.4.
3.1\\python-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit-3.4.3
.1\\python-3.4.3.amd64\\libs']
  NOT AVAILABLE

openblas_info:
  libraries openblas not found in ['D:\\Program Files\\WinPython-64bit-3.4.3.1\\
python-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit-3.4.3.1\\p
ython-3.4.3.amd64\\libs']
  NOT AVAILABLE

atlas_3_10_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas not found in ['D:\\Program Files\\WinPython-64bit-3.4.3.1\\py
thon-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit-3.4.3.1\\pyt
hon-3.4.3.amd64\\libs']
  NOT AVAILABLE

atlas_3_10_blas_info:
  libraries satlas not found in ['D:\\Program Files\\WinPython-64bit-3.4.3.1\\py
thon-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit-3.4.3.1\\pyt
hon-3.4.3.amd64\\libs']
  NOT AVAILABLE

atlas_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in ['D:\\Program Files\\WinPython-
64bit-3.4.3.1\\python-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-6
4bit-3.4.3.1\\python-3.4.3.amd64\\libs']
  NOT AVAILABLE

atlas_blas_info:
  libraries f77blas,cblas,atlas not found in ['D:\\Program Files\\WinPython-64bi
t-3.4.3.1\\python-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit
-3.4.3.1\\python-3.4.3.amd64\\libs']
  NOT AVAILABLE

F:\numpy-1.9.2\numpy\distutils\system_info.py:1603: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
blas_info:
  libraries blas not found in ['D:\\Program Files\\WinPython-64bit-3.4.3.1\\pyth
on-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit-3.4.3.1\\pytho
n-3.4.3.amd64\\libs']
  NOT AVAILABLE

F:\numpy-1.9.2\numpy\distutils\system_info.py:1612: UserWarning:
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  warnings.warn(BlasNotFoundError.__doc__)
blas_src_info:
  NOT AVAILABLE

F:\numpy-1.9.2\numpy\distutils\system_info.py:1615: UserWarning:
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  warnings.warn(BlasSrcNotFoundError.__doc__)
  NOT AVAILABLE

non-existing path in 'numpy\\lib': 'benchmarks'
lapack_opt_info:
openblas_lapack_info:
  libraries openblas not found in ['D:\\Program Files\\WinPython-64bit-3.4.3.1\\
python-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit-3.4.3.1\\p
ython-3.4.3.amd64\\libs']
  NOT AVAILABLE

lapack_mkl_info:
mkl_info:
  libraries mkl,vml,guide not found in ['D:\\Program Files\\WinPython-64bit-3.4.
3.1\\python-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit-3.4.3
.1\\python-3.4.3.amd64\\libs']
  NOT AVAILABLE

  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas,tatlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\
python-3.4.3.amd64\lib
  libraries lapack_atlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\p
ython-3.4.3.amd64\lib
  libraries tatlas,tatlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries tatlas,tatlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\
python-3.4.3.amd64\libs
  libraries lapack_atlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\p
ython-3.4.3.amd64\libs
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries satlas,satlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\
python-3.4.3.amd64\lib
  libraries lapack_atlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\p
ython-3.4.3.amd64\lib
  libraries satlas,satlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries satlas,satlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\
python-3.4.3.amd64\libs
  libraries lapack_atlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\p
ython-3.4.3.amd64\libs
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in D:\Program Files\WinPython-64bi
t-3.4.3.1\python-3.4.3.amd64\lib
  libraries lapack_atlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\p
ython-3.4.3.amd64\lib
  libraries ptf77blas,ptcblas,atlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries ptf77blas,ptcblas,atlas not found in D:\Program Files\WinPython-64bi
t-3.4.3.1\python-3.4.3.amd64\libs
  libraries lapack_atlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\p
ython-3.4.3.amd64\libs
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries f77blas,cblas,atlas not found in D:\Program Files\WinPython-64bit-3.
4.3.1\python-3.4.3.amd64\lib
  libraries lapack_atlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\p
ython-3.4.3.amd64\lib
  libraries f77blas,cblas,atlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries f77blas,cblas,atlas not found in D:\Program Files\WinPython-64bit-3.
4.3.1\python-3.4.3.amd64\libs
  libraries lapack_atlas not found in D:\Program Files\WinPython-64bit-3.4.3.1\p
ython-3.4.3.amd64\libs
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

F:\numpy-1.9.2\numpy\distutils\system_info.py:1505: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
lapack_info:
  libraries lapack not found in ['D:\\Program Files\\WinPython-64bit-3.4.3.1\\py
thon-3.4.3.amd64\\lib', 'C:\\', 'D:\\Program Files\\WinPython-64bit-3.4.3.1\\pyt
hon-3.4.3.amd64\\libs']
  NOT AVAILABLE

F:\numpy-1.9.2\numpy\distutils\system_info.py:1516: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  warnings.warn(LapackNotFoundError.__doc__)
lapack_src_info:
  NOT AVAILABLE

F:\numpy-1.9.2\numpy\distutils\system_info.py:1519: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  warnings.warn(LapackSrcNotFoundError.__doc__)
  NOT AVAILABLE

D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutils\dist.p
y:260: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutils\dist.p
y:260: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler opti
ons
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler opt
ions
running build_src
build_src
building py_modules sources
creating build
creating build\src.win-amd64-3.4
creating build\src.win-amd64-3.4\numpy
creating build\src.win-amd64-3.4\numpy\distutils
building library "npymath" sources
Looking for python34.dll
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelVisualFCompiler
Could not locate executable ifort
Could not locate executable ifl
customize AbsoftFCompiler
Could not locate executable f90
customize CompaqVisualFCompiler
Could not locate executable DF
customize IntelItaniumVisualFCompiler
Could not locate executable efl
customize Gnu95FCompiler
Found executable D:\Program Files\WinPython-64bit-3.4.3.1\tools\mingw32\bin\gfor
tran.exe
Found executable D:\Program Files\WinPython-64bit-3.4.3.1\tools\mingw32\bin\gfor
tran.exe
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    setup_package()
  File "setup.py", line 243, in setup_package
    setup(**metadata)
  File "F:\numpy-1.9.2\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\dist.py", line 974, in run_command
    cmd_obj.run()
  File "F:\numpy-1.9.2\numpy\distutils\command\install.py", line 60, in run
    r = old_install.run(self)
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\command\install.py", line 539, in run
    self.run_command('build')
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\dist.py", line 974, in run_command
    cmd_obj.run()
  File "F:\numpy-1.9.2\numpy\distutils\command\build.py", line 39, in run
    old_build.run(self)
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\command\build.py", line 126, in run
    self.run_command(cmd_name)
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\dist.py", line 974, in run_command
    cmd_obj.run()
  File "F:\numpy-1.9.2\numpy\distutils\command\build_src.py", line 153, in run
    self.build_sources()
  File "F:\numpy-1.9.2\numpy\distutils\command\build_src.py", line 164, in build
_sources
    self.build_library_sources(*libname_info)
  File "F:\numpy-1.9.2\numpy\distutils\command\build_src.py", line 299, in build
_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "F:\numpy-1.9.2\numpy\distutils\command\build_src.py", line 386, in gener
ate_sources
    source = func(extension, build_dir)
  File "numpy\core\setup.py", line 684, in get_mathlib_info
    st = config_cmd.try_link('int main(void) { return 0;}')
  File "D:\Program Files\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\distutil
s\command\config.py", line 243, in try_link
    self._check_compiler()
  File "F:\numpy-1.9.2\numpy\distutils\command\config.py", line 87, in _check_co
mpiler
    c_compiler=self.compiler)
  File "F:\numpy-1.9.2\numpy\distutils\fcompiler\__init__.py", line 842, in new_
fcompiler
    c_compiler=c_compiler)
  File "F:\numpy-1.9.2\numpy\distutils\fcompiler\__init__.py", line 816, in get_
default_fcompiler
    c_compiler=c_compiler)
  File "F:\numpy-1.9.2\numpy\distutils\fcompiler\__init__.py", line 765, in _fin
d_existing_fcompiler
    c.customize(dist)
  File "F:\numpy-1.9.2\numpy\distutils\fcompiler\__init__.py", line 540, in cust
omize
    self.set_libraries(self.get_libraries())
  File "F:\numpy-1.9.2\numpy\distutils\fcompiler\gnu.py", line 337, in get_libra
ries
    raise NotImplementedError("Only MS compiler supported with gfortran on win64
")
NotImplementedError: Only MS compiler supported with gfortran on win64

**Comment by pv** [comment]
Search/ask on stackoverflow.com

**Comment by sonicsome2** [comment]
@pv
1. It provides only numpy-1.92-win32's version.http://sourceforge.net/projects/numpy/files/NumPy/1.9.2/
2.WinPython-64bit-3.4.3.1.exe is the latest package.

**Comment by pv** [comment]
1. See the link to Gohlke's packages
2. It contains numpy 1.9.2rc1
3. Yes, or see https://github.com/numpy/numpy/wiki/Mingw-static-toolchain

**Comment by charris** [comment]
Closing this, it isn't an issue. @sonicsome2 Questions should be addressed to the numpy mailing list. Gohlke's packages are at http://www.lfd.uci.edu/~gohlke/pythonlibs/.
