### ISSUE TITLE
np.dtype('d,L') -> NameError: name 'L' is not defined

### ISSUE THREAD

**Issue by ggf84** [numpy/numpy#5645]
the title says it all.

additional info:
python: 2.7.9, numpy: 1.9.2, both from conda.
other combinations not using 'L' seems to work fine.

**Comment by charris** [comment]
???What do you expect it to do?

**Comment by ggf84** [comment]
sorry, I thought the title was clear enough.

this is what I expect
np.dtype('d,L') -> dtype([('f0', '<f8'), ('f1', '<u8')])

since
np.dtype('d,I') -> dtype([('f0', '<f8'), ('f1', '<u4')])

or am I wrong?

**Comment by charris** [comment]
Just hadn't seen that construction before. Does look like a bug.

**Comment by kevin-coder** [comment]
I will look through this issue.

**Comment by eric-wieser** [comment]
Workaround: `np.dtype('i,()L')`. Better workaround: `np.dtype([('f1', np.intc), ('f2', np.uint)])`

**Comment by RuchikaChugh** [comment]
Hey! I am an Outreachy applicant and this will be my initial contribution. Can i help in resolving this issue
