### ISSUE TITLE
test_collections_hashable fails on windows python 3.4

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#5647]
test introduced in gh-5326
isinstance(np.array([]), collections.Hashable) is true on windows python 3.4.3 built with msvc
though what is weird that both hash(x) and x.**hash**() raise an exception as expected, no clue whats going on.

@cournape any idea?

**Comment by cournape** [comment]
Not on the top of my head. The isinstance check is False as expected everywhere else, correct ?

**Comment by jaimefrio** [comment]
I also see this in Python 2.7.5 with numpy built from a more or less recent master, using 32 bit MinGW. It is only the `isinstance` check that fails.

**Comment by cgohlke** [comment]
`test_collections_hashable` also fails here on python 3.4.3 and 3.5.0b4, win-amd64:

Python's test for "hashability" is at <https://hg.python.org/cpython/file/c7273b46980c/Lib/_collections_abc.py#l73>.

`np.ndarray.__dict__["__hash__"]` is `<slot wrapper '__hash__' of 'numpy.ndarray' objects>`, not `None`, hence `isinstance(x, collections.Hashable)` returns True.

`hash(np.array([]))` correctly raises `TypeError`.

Relevant Python docs:
 
*  https://docs.python.org/3/reference/datamodel.html#object.__hash__
* https://docs.python.org/3/c-api/object.html#c.PyObject_HashNotImplemented

**Comment by charris** [comment]
Marking this as something to take another look at for the 1.10 release.

**Comment by charris** [comment]
What has happened with this? Anyone. We don't see errors on AppVeyor.

**Comment by mattip** [comment]
Closing, it seems the actual issue is lost in the haze of time. If needed please open a new issue with a reproducer.
