### ISSUE TITLE
numpy.dual.cholesky behaves differently than numpy.linalg.cholesky

### ISSUE THREAD

**Issue by rlabbe** [numpy/numpy#5649]
The documentation for numpy.dual states "Aliases for functions which may be accelerated by Scipy." One of the functions supported is cholesky. One would assume (I did) that the results will be the same regardless of whether scipy is installed or not; only the execution time might vary. 

However, the implementation in numpy and scipy for cholesky are different. The numpy version returns  a lower triangular matrix, and the scipy version returns an upper triangular matrix. Hence you get different behavior depending on whether you have scipy installed or not.

Below is a script that duplicates this behavior (without forcing you to uninstall scipy to test).

```
import numpy as np
import numpy.linalg as la
import numpy.dual as dual


P = np.cov(np.diag([1., 2., 3.]))
c1 = la.cholesky(P)
c2 = dual.cholesky(P)
assert c1[1,2] == c2[2,1]
assert c1[1,2] != c2[1,2]
```

Suggested fix: I dunno. Some choices that come to mind
- Add a _lower_ parameter to numpy, defaulted to true, and add a non-optional parameter _lower_ to dual.cholesky. This will break all code using dual.cholesky, but I am not a fan of silent failures. 
- Remove cholesky from dual
- scipy's cholesky has an optional _lower_ param that can be set to true. If dual.py could be modified to set that to be true than numpy.linalg.cholesky and dual.cholesky will behave the same, which is presumably the behavior that the programmer wants. I say 'presumably' because the programmer may be used to using the scipy version and expecting the upper-triangular behavior; they will be surprised by this choice.
- Add a warning in the documentation that the behavior is inconsistent. I dislike this because I found out about this problem the hard way - my output 'looked' wrong. Sure, documentation would have helped me find it faster, but either consistent behavior or an exception would have been preferred by me.
- Make cholesky in both scipy and numpy return upper-triangular. This is a terrible option IMO because it would break so much code.

The top two are the most "painful" to the users of the library, but they have the advantage of forcing them to think about and deal with the problem. The others allow silent failures.

**Comment by pv** [comment]
Note that there's probably no good reason for using numpy.dual at all.
The easiest fix is probably to force `numpy.dual.cholesky` always be the
numpy version.

**Comment by rlabbe** [comment]
Yes, I have no idea how often dual is actually used. I saw it, thought it would be a good way to reduce dependencies in my library because I only really use the scipy functions that are in dual. 

As an aside I'm finding that at least with the test array above dual runs about twice as slow as numpy. This is with the 64-bit Anaconda distributions for  both linux and Windows.

**Comment by pv** [comment]
Yes, apparently there is a performance difference for cholesky, and this may be something that needs to be investigated given that these wrappers for these linear algebra routines were recently rewritten -> gh-5650

**Comment by rlabbe** [comment]
@pv, actually my statement was the reverse. With a bit of testing it appears that numpy is about twice as fast as scipy for small arrays. On my machine the crossover point is right around 370x370 (larger than that and scipy is faster)

**Comment by rossbar** [comment]
The deprecation of `numpy.dual` was introduced in #16156 - hopefully that resolves any remaining issues. Closing for now - please feel free to re-open or create a new issue if additional discussion on the topic is needed.

**Comment by zoj613** [comment]
I have a question regarding the choice of returning the Lower triangular factor instead of the upper triangular factor. What motivated that choice for numpy? why did scipy choose the upper triangular factor as the default? I'm thinking it would be best to return the upper triangular matrix since python is stores data in row-major order, that way access the factor elements is efficient. Or am I missing something here? Someone please shed some light for me.

**Comment by charris** [comment]
> What motivated that choice for numpy?

I have no idea, it was before my time and one of those oddities. It may have been due to wanting Fortran compatibility.

**Comment by zoj613** [comment]
> > What motivated that choice for numpy?
> 
> I have no idea, it was before my time and one of those oddities. It may have been due to wanting Fortran compatibility.

Ahh, I see. Do you agree that python/C libraries making calls to CBLAS's `cblas_?potrf` routine should use CblasUpper instead of CblasLower for optimum efficiency? I see no reason for a user to pick the lower triangular part of a matrix by default if efficiency is important for a use case. I just want someone to confirm for me because BLAS documentation has no recommendation.

**Comment by charris** [comment]
Changing things at this point would probably break a lot of downstream code for little gain. It might be interesting to benchmark if it makes a difference, which might depend on the usage of the result. For instance, generating multivariate random numbers uses the lower factor.
