### ISSUE TITLE
allclose returns True when comparing an empty array to a scalar

### ISSUE THREAD

**Issue by mrbell** [numpy/numpy#5654]
In Numpy v 1.9.1

``` python
import numpy as np
np.allclose(np.array([]), 1)
```

returns `True`. The value of the scalar doesn't matter. It also returns `True` when comparing an empty array to an array with only one value, e.g.

``` python
np.allclose(np.array([]), np.array([123])
```

also returns `True`. It should return `False` unless comparing two empty arrays if you ask me.

**Comment by gmcastil** [comment]
I'll take a look at this - thanks.

**Comment by spencerahill** [comment]
We have recently bumped into this odd behavior of `allclose` when shapes don't match.  It remains in 1.13:

```python
In [2]: np.version.version
Out[2]: '1.13.1'

In [5]: np.allclose(np.ones([5, 1]), np.ones([1]))
Out[5]: True

In [7]: np.allclose(np.ones([5, 1]), np.ones([5, 2]))
Out[7]: True

In [8]: np.allclose(np.ones([5, 1]), np.ones([2]))
Out[8]: True

In [9]: np.allclose(np.ones([5, 1]), np.ones([]))
Out[9]: True
```

In contrast to:
```python
In [12]: np.allclose(np.ones([5, 1]), np.ones([12, 34]))
...
ValueError: operands could not be broadcast together with shapes (5,1) (12,34)
```

>Would a ValueError be the most appropriate if the two arrays are not the same shape?

Yes, I think so.

Any chance of a fix forthcoming?  I'm unfamiliar with numpy's internals, but from the outside it seems like it would be relatively straightforward.  If that's the case, I'd be willing to take a stab at it.  Thanks!

**Comment by eric-wieser** [comment]
As stated in the original post, this isn't a bug. Every element of `np.array([])` is close to 1.

You'd expect `np.allclose(a, 1)` to have the same meaning as `np.all(np.isclose(a, 1))`. When `a == []`. then `isclose` also returns `[]`, and `all([])` is defined as `True. So that's why you get the result you do.

> Would a ValueError be the most appropriate if the two arrays are not the same shape?

What's happening right now is broadcasting. This is useful to check something like if every point in a list of points is close to another point, ie `np.allclose(points_2d, point_1d)`.

Can you give an argument for why broadcasting isn't desirable here?

**Comment by spencerahill** [comment]
>As stated in the original post, this isn't a bug

I was agreeing with the sentiment by @gmcastil that "np.allclose should return an error of some sort if the lengths of the arrays are not the same."

>You'd expect np.allclose(a, 1) to have the same meaning as np.all(np.isclose(a, 1)). When a == []. then isclose also returns [], and all([]) is defined as `True. So that's why you get the result you do.

Thanks, that is a nice explanation of the logic.

>This is useful to check something like if every point in a list of points is close to another point, ie np.allclose(points_2d, point_1d)

That's a reasonable use case that I hadn't considered.

>Can you give an argument for why broadcasting isn't desirable here?

I'll walk back my statement.  I see now that the existing behavior is also consistent with that of exact equality:

```python
>>>np.all(np.equal(np.ones([5, 1]), np.ones([2])))
True
```

>There is certainly nothing in the docstring to suggest the kind of behavior you are seeing.

Adding a note to the docstring may be helpful.  The crux of my confusion was that I had incorrectly assumed that these required matching array shapes.  Closing this Issue also seems appropriate -- the combination of nothing in the docstring about this and an open Issue on it led me to believe that it was indeed a bug.

Thanks very much for your help.

**Comment by eric-wieser** [comment]
> Adding a note to the docstring may be helpful.

I agree - lets leave this open as a reminder to do that
