### ISSUE TITLE
Fix alignment issue for 1.10

### ISSUE THREAD

**Issue by charris** [numpy/numpy#5656]
There was quick fix for 1.9.2 that was a backport of #5316, but the proper fix for 1.10 is still open.

**Comment by charris** [comment]
A better fix does not seem in the offing.

**Comment by njsmith** [comment]
Totally agreed that we shouldn't worry about this for 1.10, but:
@juliantaylor: is there a more proper fix possible, and if so should we
keep a bug open (without a milestone attached) to remind us to do something
eventually?

**Comment by ahaldane** [comment]
I've read up on the alignment code recently, and it looks to me like building on #5365 is the right way to go, following [this comment](https://github.com/numpy/numpy/pull/5365#issuecomment-66690535) by @pv.

I'd like to give it a shot, if no one else is working on it right now.

I wrote up some notes [here](https://gist.github.com/ahaldane/6f57412470c3d8f12c20).

**Comment by njsmith** [comment]
@ahaldane: it would be great if you can move those notes to the wiki, or
maybe even a new "misc technical notes" section in doc/source/dev/, so they
can be found again later -- a gist is probably going to get lost I think

**Comment by juliantaylor** [comment]
here is my old code, the raw_array stuff is still missing in it
https://github.com/juliantaylor/numpy/tree/fix-copy-alignment
