### ISSUE TITLE
BUG some ufunc methods do not yet take tuple for output

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#5662]
#5621 introduced the nice option to allow tuples for output arrays, including a tuple holding a single array for a single output. However, it missed also changing the outputs for some of the ufunc methods such as reduce:
```
a = np.arange(10.)
b = np.array(1.)
np.add.reduce(a, out=b)
# array(45.0)
np.add.reduce(a, out=(b,))
# TypeError: output must be an array
```
cc @jaimefrio

**Comment by jaimefrio** [comment]
If I am not mistaken, ufunc methods can only be applied to ufuncs with a single output. Not sure it makes much sense to enable the tuple thing.

**Comment by mhvk** [comment]
Duh, OK, then this would really just be for consistency and possible future expansion. Anyway, while trying to see what would happen with two-output ufuncs, I at least found another bug (#5565). I'll close this now; the consistency does not seem worth the effort.

**Comment by jaimefrio** [comment]
`outer` would probably work on a ufunc with multiple outputs. But it requires a binary ufunc, and the only ones with 2 outputs (`frexp` and `modf`) are unary...

**Comment by njsmith** [comment]
IIRC scipy.special has some funky nin/nout combinations if you want
examples to play around with easily.

**Comment by jaimefrio** [comment]
Didn't see any on a quick search with two inputs and multiple outputs, but will ask the SciPy people.
