### ISSUE TITLE
tensordot handles contraction over 0-length dimensions differently than dot

### ISSUE THREAD

**Issue by mhauru** [numpy/numpy#5663]
``` python
>>> a = np.ndarray((3,0))
>>> b = np.ndarray((0,4))
>>> np.dot(a,b)
array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])
>>> np.einsum('ij,jk', a, b)
array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])
>>> np.tensordot(a, b, (1,0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CENSORED/site-packages/numpy/core/numeric.py", line 1274, in tensordot
    at = a.transpose(newaxes_a).reshape(newshape_a)
ValueError: total size of new array must be unchanged
```

If tensordot is asked to contract over an axis that has length 0 it raises a ValueError. In contrast, dot and einsum give an array of zeros. I could see both behaviors as reasonable choices, but I feel that tensordot should be a generalization of dot and the behavior of the two should be consistent.

This as of numpy 1.9.2.

**Comment by duvenaud** [comment]
This tripped us up too.  Me and @dougalm wrote a little wrapper to fix this:

```python
def safe_tensordot(A, B, axes):		
    """Allows dimensions of length zero"""		
    Adims, Bdims = list(A.shape), list(B.shape)		
    if np.any([d is 0 for d in Adims + Bdims]):		
        Anewdims = [d for i, d in enumerate(Adims) if i not in axes[0]]		
        Bnewdims = [d for i, d in enumerate(Bdims) if i not in axes[1]]		
        return np.zeros(Anewdims + Bnewdims)		
    else:		
        return np.tensordot(A, B, axes)
```

But I agree that it should be part of tensordot().

**Comment by njsmith** [comment]
Yeah, sounds like a bug. Anyone want to submit a pull request?

On Sun, May 17, 2015 at 12:45 PM, David Duvenaud <notifications@github.com>
wrote:

> This tripped us up too. Me and @dougalm <https://github.com/dougalm>
> wrote a little wrapper to fix this:
>
> def safe_tensordot(A, B, axes):
>     """Allows dimensions of length zero"""
>     Adims, Bdims = list(A.shape), list(B.shape)
>     if np.any([d is 0 for d in Adims + Bdims]):
>         Anewdims = [d for i, d in enumerate(Adims) if i not in axes[0]]
>         Bnewdims = [d for i, d in enumerate(Bdims) if i not in axes[1]]
>         return np.zeros(Anewdims + Bnewdims)
>     else:
>         return np.tensordot(A, B, axes)
>
> But I agree that it should be part of tensordot().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5663#issuecomment-102843270>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by eric-wieser** [comment]
Fix is to replace the `-1` in the shapes with an explicit calculation

**Comment by Nanonumpy** [comment]
It looks like this issue has been handled and should be closed.   Is there something more that needs to be done?

**Comment by mattip** [comment]
Closing
