### ISSUE TITLE
BUG segmentation fault for np.modf.at(np.arange(10.), (1,))

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#5665]
Found this while trying to thing of ufunc methods for ufuncs with two outputs (see #5662). While not something that I would expect to work, the following also shouldn't lead to a segmentation fault:
```
import numpy as np
np.sin.at(np.arange(10.), (1,))
# works
np.modf.at(np.arange(10.), (1,))
# Segmentation fault
```

**Comment by jaimefrio** [comment]
This should be easy to fix, adding a check for `ufunc->nout != 1` to `ufunc_at`in `ufunc_object.c`, similarly to what is done in `PyUFunc_GenericReduction` for `reduce`, `reduceat` and `accumulate`.

I don't fully follow what goes on in `ufunc_at`, so there may be a more elegant solution to this than the explicit check.

**Comment by jaimefrio** [comment]
Nice catch, by the way. The detailed scrutiny you are subjecting ufuncs to is invaluable, Marten!

**Comment by mhvk** [comment]
Thansk!  Though here it feels I'm asking for things to be truly fool-proof...  But I'm quite keen on having `__numpy_ufunc__` work for astropy's `Quantity` class (which is amazing; eventually I'd hope to migrate it to scipy so it can be used more broadly).
