### ISSUE TITLE
einsum - double diagonal fails when combined with contraction

### ISSUE THREAD

**Issue by aherrmann** [numpy/numpy#5667]
`einsum` has the ability to contract indices, but also to extract diagonals between indices. A combination of the two should also be possible.

E.g. if we have an array of shape (2,3,3) we can contract the first index, and take the diagonal between the last two as follows:

```python
>>> x = np.zeros((2,3,3))
>>> np.einsum('tii->i', x).shape
(3,)
```

However, it fails if we take more than one diagonal. E.g.:

```python
>>> x = np.diagonal((2,3,3,4,4))
>>> np.einsum('tiijj->ij', x).shape
Traceback (most recent call last):
  File "<ipython-input-30-4ab3a3e6fc50>", line 1, in <module>
    np.einsum('tiijj->ij', x).shape
ValueError: dimensions in operand 0 for collapsing index 'j' don't match (0 != 4)
```

To me, this seems like a bug because the same thing works if we just change the order of the axes:

```python
>>> x = np.zeros((3,3,4,4,2))
>>> np.einsum('iijjt->ijt', x).shape
(3, 4, 2)
```

---

Tested on NumPy version 1.8.2 with Python version 2.7.9 on openSuse 13.1 x64_86.

**Comment by jaimefrio** [comment]
Thanks for reporting. This seems to be the same that was reported in #5147 and should be fixed. It certainly works for me on master. Am going to close this, but feel free to complain if you think it should be reopened.

**Comment by aherrmann** [comment]
@jaimefrio Thanks! I missed that one when I looked through the issues. Updating to NumPy version 1.9.2 fixes the issue.
