### ISSUE TITLE
Ufunc override should normalize the sig keyword argument

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#5674]
Opening this as a reminder of unfinished work after merging #5659.

The ufunc override mechanism should make sure that, if `sig` is part of the keyword arguments, it gets normalized to `signature`.

It may also be a good idea to make `signature` the keyword argument announced in the docs, with a small footnote saying that `sig` is also acceptable for backwards compatibility reasons, rather than having them advertised as equally valid alternatives.

**Comment by njsmith** [comment]
CC @cowlicks
