### ISSUE TITLE
argsort (..., axis=None) doesn't use flattened array for 0d inputs.

### ISSUE THREAD

**Issue by mdickinson** [numpy/numpy#5678]
There seems to be an inconsistency in `numpy.argsort` with respect to zero-dimensional arrays when `axis=None`.  The docs for the `axis` parameter say:

> If None, the flattened array is used.

But for a 0d array, this doesn't seem to be true: I get a scalar out where I expected a 1d array
```
In [29]: x = np.array(5)

In [30]: np.argsort(x, axis=None)
Out[30]: 0

In [31]: np.argsort(x.ravel(), axis=None)
Out[31]: array([0])
```

I'd expect both `Out[30]` and `Out[31]` above to give me `array([0])`.  For 2d arrays, the results are the same with and without explicit flattening, as expected:

```
In [32]: x = np.array([[6, 7], [1, 4]])

In [33]: np.argsort(x, axis=None)
Out[33]: array([2, 3, 0, 1])

In [34]: np.argsort(x.ravel(), axis=None)
Out[34]: array([2, 3, 0, 1])
```

**Comment by mdickinson** [comment]
Versions: Python 3.4.3, NumPy 1.9.2, OS X 10.9.5.

**Comment by jaimefrio** [comment]
I refactored that code not long ago, see #5494, and apparently I unkwonwingly fixed your problem:

```
>>> np.__version__
'1.10.0.dev0+a866fdd'
>>> x = np.array(5)
>>> np.argsort(x)
array([0])
```

`PyArray_ArgSort` used to have an early bail-out on 0-D and size 1 arrays, that returned an array of `NPY_INTP` zeros like the input. That is now deferred to `_new_argsortlike`, after `PyArray_CheckAxis` has been called, which ravels the array if axis is `None`.

Before the refactor you could also do some very wrong things, which is the reason I moved it, like:

```
>>> np.__version__
'1.8.0'
>>> np.argsort(5, axis=7)
0
```

I'm going to leave this open for a while, in case someone thinks this is now broken and wasn't before...

**Comment by mdickinson** [comment]
Ah, that's beautiful.  Thank you!

> I'm going to leave this open for a while, in case someone thinks this is now broken and wasn't before...

No, please don't unfix this! :-) The particular use-case that generated this bug report was sorting an array `x` based on the values in another array `y` of the same shape as `x`.  Using `np.take(x, np.argsort(y, axis=None))` worked well for this right up until I hit the corner case where `x` and `y` were both 0d arrays.

**Comment by jaimefrio** [comment]
Well, their silence is your gain, closing.
