### ISSUE TITLE
array2string documentation is missing from docs.scipy.org

### ISSUE THREAD

**Issue by sbyrnes321** [numpy/numpy#5684]
There is a docstring for [array2string](https://github.com/numpy/numpy/blob/master/numpy/core/arrayprint.py#L344) but it is not online at docs.scipy.org, as far as I can tell from google and the [index](http://docs.scipy.org/doc/numpy/genindex.html).

There are *references* to it online, for example [here](http://docs.scipy.org/doc/numpy/reference/generated/numpy.array_str.html#numpy.array_str), but `array2string` shows up without a link!

**Comment by rgommers** [comment]
Thanks for the report @sbyrnes321. Fixed by gh-5689
