### ISSUE TITLE
I installed numpy-1.10.0.dev0+c60f1c6, the latest in the Git Hub and found the following error when running numpy.test('full')

### ISSUE THREAD

**Issue by s0r2637** [numpy/numpy#5688]
I installed numpy-1.10.0.dev0+c60f1c6, the latest in the Git Hub and found the following error when running numpy.test('full').  Could some please let me know if this is a serious bug that can cause problem later?
# 
## FAIL: test_from_object_array_unicode (test_defchararray.TestBasic)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/tests/test_defchararray.py", line 26, in test_from_object_array_unicode
    self.assertRaises(ValueError, np.char.array, (A,))
AssertionError: ValueError not raised
# 
## FAIL: test_from_unicode_array (test_defchararray.TestBasic)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/tests/test_defchararray.py", line 63, in test_from_unicode_array
    self.assertRaises(UnicodeEncodeError, fail)
AssertionError: UnicodeEncodeError not raised
# 
## FAIL: Ticket #1240.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/tests/test_regression.py", line 1376, in test_unicode_to_string_cast
    self.assertRaises(UnicodeEncodeError, fail)
AssertionError: UnicodeEncodeError not raised

---

Ran 6059 tests in 54.762s

FAILED (KNOWNFAIL=3, SKIP=9, failures=3)
<nose.result.TextTestResult run=6059 errors=0 failures=3>

**Comment by rgommers** [comment]
@s0r2637 thanks for the report. This doesn't look too serious, unless you use arrays of unicode strings nothing will go wrong.

Can you tell us how you installed numpy (OS, source build or binary from somewhere, compiler versions)?

**Comment by s0r2637** [comment]
Hi Ralph,

Thanks for allaying my fears.  My OS is Ubuntu 14.04.2 LTS 64-bit.  I got
the source from GitHub and built it from these.  The compiler versions are
as follows:

ii  g++                                                   4:4.8.2-1ubuntu6
                                   amd64        GNU C++ compiler
ii  g++-4.8                                               4.8.2-19ubuntu1
                                  amd64        GNU C++ compiler
ii  gcc                                                   4:4.8.2-1ubuntu6
                                   amd64        GNU C compiler
ii  gcc-4.8                                               4.8.2-19ubuntu1
                                  amd64        GNU C compiler
ii  gfortran                                              4:4.8.2-1ubuntu6
                                   amd64        GNU Fortran 95 compiler
ii  gfortran-4.8                                          4.8.2-19ubuntu1
                                  amd64        GNU Fortran compiler
ii  hardening-includes                                    2.5ubuntu2.1
                                   all          Makefile for enabling
compiler flags for security hardening
ii  libllvm3.5:amd64
 1:3.5-4ubuntu2~trusty2                              amd64        Modular
compiler and toolchain technologies, runtime library
ii  libxkbcommon0:amd64                                   0.4.1-0ubuntu1
                                   amd64        library interface to the
XKB compiler

Let me know if this is what you wanted.

Srini

**Comment by rgommers** [comment]
Thanks Srini, that's enough info

**Comment by mattip** [comment]
`mode --full` tests pass on HEAD, python2.7. Please reopen if you disagree.
