### ISSUE TITLE
including numpy.i in other projects

### ISSUE THREAD

**Issue by rashadkm** [numpy/numpy#5690]
What is the prefered way to include numpy.i in the source distribution of other projects using numpy.i. currently there is no license header associated with this file.  Adding the contents of LICENSE seems to be only way.

If there is any prefered way let me know

**Comment by rgommers** [comment]
Copying the text in ``LICENSE.txt`` at the top of ``numpy.i`` sounds reasonable to me.

**Comment by rgommers** [comment]
Because ``numpy.i`` is supposed to be copied, I guess we should see this as a valid bug report and make this change in numpy itself.

**Comment by rashadkm** [comment]
Thanks!
