### ISSUE TITLE
Mean of dtype object array works sometimes

### ISSUE THREAD

**Issue by amueller** [numpy/numpy#5696]
Hi.
We ran into this at scikit-learn and it is more of an integration/testing issue than anything else.
It boils down to this expression:
```python
np.arange(10).astype(object).mean(axis=0)
```
which either produces ``4.5`` or raises an error. I'd like to know what causes the error, in which version it is, and how to robustly test for it.
Maybe I'm overlooking something, but testing it on several platforms, what I get is this:

```
Ubuntu 12.04 + Py 2.7.3 + np 1.6.1 == Pass
Ubuntu 12.04 + Py 2.6.9 + np 1.6.2 == Pass
Ubuntu 12.04 + Py 3.4.3 + np 1.9.2 == Pass

Ubuntu 14.04 + Py 2.7.9 + np 1.8.0 == Fail
Ubuntu 14.04 + Py 2.7.9 + np 1.9.2 == Pass

OSX Yosemite + Py 2.7.6 + np 1.9.0 == Fail
OSX Yosemite + Py 2.7.6 + np 1.9.1 == Fail
OSX Yosemite + Py 2.7.6 + np 1.9.2 == Fail
OSX Yosemite + Py 2.7.9 + np 1.9.2 == Pass

Ubuntu 14.04 + Py 2.7.3 + np 1.6.1 == Pass
Ubuntu 14.04 + Py 2.7.6 + np 1.8.0 == Fail
Ubuntu 14.04 + Py 2.7.6 + np 1.9.0 == Pass
```
So even for the same Python and numpy version, the behavior is different between Ubuntu and OS X.

Any help would be much appreciated.
cc @trevorstephens

**Comment by charris** [comment]
What error/message is raised? Are the failures/successes repeatable? Are you building numpy from scratch? How about Python? Numpy master works for me on Fedora 21 with both Python 3.4.1 and Python  2.7.8.

**Comment by amueller** [comment]
The error on "fail" is (sorry for not posting earlier)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andy/virtenvs/numpy_madness/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 67, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'int' object has no attribute 'dtype'
```
The failures I could reproduce were with building numpy from scratch, that is ``pip install numpy==1.8.0``

**Comment by charris** [comment]
Could you try installing current master from github? I'd like to see if it got fixed somewhere along the line.

**Comment by charris** [comment]
Also try `np.arange(10, dtype=object)` instead of `astype`.

**Comment by ahaldane** [comment]
Something strange is going on which doesn't seem like a numpy bug. The lines that fail are:

    ...
    elif hasattr(ret, 'dtype'):
        ret = ret.dtype.type(ret / rcount)
    ...

So, we are getting an `AttributeError` when accessing `ret.dtype` immediately after checking `hasattr(ret, 'dtype')`.

**Comment by amueller** [comment]
``np.arange(10, dtype=object).mean()`` also fails on 1.8.0 on my ubuntu venv.

**Comment by amueller** [comment]
@ahaldane the surrounding code is
```python
    if isinstance(ret, mu.ndarray):
        ret = um.true_divide(
                ret, rcount, out=ret, casting='unsafe', subok=False)
    else:
        ret = ret.dtype.type(ret / rcount)
```

**Comment by amueller** [comment]
I guess it has been fixed in master. I am just surprised that the crash seems to be python version dependent somehow, though maybe that was an error on our part. Maybe it is just 1.8.0.

**Comment by ahaldane** [comment]
@amuller Ah, I see. The current code is what I pasted: [link](https://github.com/numpy/numpy/blob/master/numpy/core/_methods.py#L71)

So it seems quite possible the bug is fixed in dev.

**Comment by amueller** [comment]
It is already fixed in 1.8.1 as far as I can tell, but also in 1.7.1. There just seemed to have been a weird circumstance where it still popped up in 1.9.1

**Comment by amueller** [comment]
This seems to be the fix: 4ebf25e1e3b3b0c8619cce395a96d0dffa9e4e8a

**Comment by ahaldane** [comment]
Yes, in issue https://github.com/numpy/numpy/issues/4063

**Comment by amueller** [comment]
Ok. That clears it up for me, I think. I'll close this one for now.

**Comment by charris** [comment]
@amueller Thanks for the follow up.
