### ISSUE TITLE
Numerical precision inconsistency in np.linalg.norm (vector vs. matrix)

### ISSUE THREAD

**Issue by maciejkula** [numpy/numpy#5697]
There is a slight numerical inconsistency in `np.linalg.norm` in evaluating the length of vectors vs. the column-wise or row-wise length of matrices.

Minimal example to reproduce on 1.9.1:
```
import numpy as np

x = np.random.rand(100)
np.linalg.norm(x) == np.linalg.norm(np.vstack([x]), axis=1)[0]
```
Prints:
```
Out[27]: False
```
The last few digits of the output do not agree.

I understand this passes from the `allclose` perspective, but in some applications it is extremely surprising and hard to debug. I encountered this when writing an approximate nearest neighbour lookup tree and realising points were not being assigned to the same leaf nodes depending on whether I used the one-vector-at-a-time or matrix-based approach.

Numpy 1.8.1 gives the same result in both cases.

**Comment by argriffing** [comment]
In my opinion numpy shouldn't require exact floating point equality in this situation.

**Comment by njsmith** [comment]
It is somewhat surprising that simply adding an axis without changing
memory layout has this effect, but still, yeah, numpy in general does not
guarantee that semantically equivalent operations like this will produce
identical results. Even operations like sum can produce different results
depending on memory layout (and this is on purpose -- making them identical
all the time would require either big slowdowns or intentionally reducing
precision).

**Comment by maciejkula** [comment]
I think it's reasonable to not expect identical results. I just wanted to verify as this seems to have changed since 1.8.1.

Happy to close.

**Comment by argriffing** [comment]
@maciejkula Thanks for opening this issue, I think the inequality was introduced by https://github.com/numpy/numpy/pull/3895 which added a faster code path for particularly simple inputs (e.g. no `axis` specified).

```python
In [1]: import numpy as np
In [2]: np.__version__
Out[2]: '1.10.0.dev0+e310164'
In [3]: a = np.random.randn(1e6)
In [4]: b = np.vstack([a])
In [5]: %timeit np.linalg.norm(a)
1000 loops, best of 3: 441 µs per loop
In [7]: %timeit np.linalg.norm(b, axis=1)
1000 loops, best of 3: 1.91 ms per loop
```

So not only are the values not exactly equal, but also there is an unnecessary 4x-5x speed difference.  That said, all of these calculations explicitly use something like `sqrt(sum(square(x)))` whereas it is possible to do better numerically by using scaling like the blas `nrm2`.  When/if this is implemented for a subset of inputs to `np.linalg.norm`, this would cause the numerical values of the results to change yet again...
