### ISSUE TITLE
ERR: Broadcast error on assignment prints dimensions in wrong order

### ISSUE THREAD

**Issue by ischwabacher** [numpy/numpy#5710]
xref #2357

``` python
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.9.1'

In [3]: arr = np.zeros([5, 2])

In [4]: arr[:,[0,1]] = np.arange(10).reshape([2, 5])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-fe63af63442b> in <module>()
----> 1 arr[:,[0,1]] = np.arange(10).reshape([2, 5])

ValueError: shape mismatch: value array of shape (2,5) could not be broadcast to 
indexing result of shape (2,5)  # BAD

In [5]: arr[:,[0,1]] + np.arange(10).reshape([2, 5])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-8c656689a6ee> in <module>()
----> 1 arr[:,[0,1]] + np.arange(10).reshape([2, 5])

ValueError: operands could not be broadcast together with shapes (5,2) (2,5)  # correct
```

The first error message is confusing at best.

**Comment by jaimefrio** [comment]
The wrong message is being produced [here](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/src/multiarray/mapping.c#L3098), although the code seems to be correctly using the second array's shape and the first one's iterator shape. My guess is that this mismatch is due to axis reordering in the iterator, but not sure how to check that is the case, nor what the fix would be. Hopefully @seberg can take a look, as he is probably the one that better understands that code.

**Comment by seberg** [comment]
Haha, now I see it. First thought it was a confusion of showing the values array first and the indexing result second ;). There is basically a call to `PyArray_MapIterSwapAxes ` missing, but I think there is no array to actually call that function unfortunatly. Maybe we should split it up into a function just returning `permute` from it, then we can probably call it reasonably from there.

**Comment by seberg** [comment]
Or actually, I guess we don't need all of that logic, so maybe it is available through nditer or so as well, would have to check closer.

**Comment by seberg** [comment]
Wow, there is a **real** bug here along the same lines with the object non-array special case and I did not notice it :(!

**Comment by WarrenWeckesser** [comment]
Fixed by https://github.com/numpy/numpy/pull/18404.

(Apparently the magic text "Closes gh-XXXX" does not handle a comma separated list of issues.)
