### ISSUE TITLE
issubdtype(double, bool)

### ISSUE THREAD

**Issue by ahojnnes** [numpy/numpy#5711]
Maybe I am missing something, but is this correct?

`np.issubdtype(np.double, np.bool) => True`

At the very least, this is confusing.

**Comment by argriffing** [comment]
This isn't an answer, but:
```python
>>> np.issubdtype(np.double, np.bool_)
False
```

**Comment by ahojnnes** [comment]
Thanks for the clarification!

Feel free to close the issue, if you think this is the intended behavior.

**Comment by charris** [comment]
```
In [39]: issubdtype(np.bool_, np.int8)
Out[39]: False

In [40]: issubdtype(np.int8, np.bool_)
Out[40]: False
```
`np.bool_` seems to be a type all by itself in the type hierarchy.

**Comment by njsmith** [comment]
Yes, it is. For some reason the picture is hidden on this page:
http://docs.scipy.org/doc/numpy/reference/arrays.scalars.html

I don't know what's going on with the original report, though: dtype(bool)
and dtype(bool_) certainly ought to return the same things...

**Comment by charris** [comment]
There is this
```
n [14]: issubdtype(np.object, np.bool)
Out[14]: True

In [15]: issubdtype(np.bool, np.object)
Out[15]: True
```
Python bool was new in python version 2.2.1. It may be that the current behavior is an accident.

**Comment by pv** [comment]
Note that the code in `np.issubdtype` contains some weird stuff:
```
    if issubclass_(arg2, generic):
        return issubclass(dtype(arg1).type, arg2)
    mro = dtype(arg2).type.mro()
    if len(mro) > 1:
        val = mro[1]
    else:
        val = mro[0]
    return issubclass(dtype(arg1).type, val)
```
For example
```
>>> np.issubdtype(np.float32, np.dtype(float))
True
```

**Comment by maniteja123** [comment]
I think #3218 is relevant to this issue.

**Comment by eric-wieser** [comment]
Deprecated in #9505
