### ISSUE TITLE
misleading linalg error message for junk input

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5717]
In this toy example I tried to invert a meaningless Python object, but the error message complains about a 0-dimensional array.  I was able to decipher this error message because I have some experience using numpy, but maybe the message should be changed to indicate that numpy does not recognize the input as a matrix or array type?

``` python
>>> class Foo(object): pass                                                     
... 
>>> a = Foo()
>>> np.linalg.inv(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/numpy/linalg/linalg.py", line 510, in inv
    _assertRankAtLeast2(a)
  File "[...]/numpy/linalg/linalg.py", line 202, in _assertRankAtLeast2
    'at least two-dimensional' % len(a.shape))
numpy.linalg.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
```

**Comment by eric-wieser** [comment]
Remember that any numpy function `f(x)` is usually just short for `f(np.asanyarray(x))`. In this case, numpy has no qualms converting your `Foo()` into the 0d array `np.array(Foo())`.

**Comment by mattip** [comment]
Closing, please reopen if you have a concrete suggestion where we could improve the error message.
