### ISSUE TITLE
segfault while casting rational dtype

### ISSUE THREAD

**Issue by cowlicks** [numpy/numpy#5719]
On numpy master and numpy-types master.
```python
In [1]: import numpy, npytypes.rational

In [2]: numpy.array([npytypes.rational.rational(1111)]).astype('int8')
[1]    4639 segmentation fault  ipython
```
Instead, this should raise an overflow error.

This could possibly related to this [issue #3359](https://github.com/numpy/numpy/issues/3359).

**Comment by charris** [comment]
I think the working copy of rational is `numpy/core/src/umath/test_rational.c.src`. There also appears to be an issue (4) open in numpy-dtypes about this. Note that numpy-dtypes hasn't been maintained.

**Comment by cowlicks** [comment]
Just to confirm, the numpy rational gives the same behavior:
```python
In [1]: import numpy as np

In [2]: from numpy.core.test_rational import rational

In [3]: np.array([1111], dtype=rational).astype('int8')
[1]    11087 segmentation fault  ipython
```

**Comment by cowlicks** [comment]
@charris why is `test_rational.c.src` there? It seems out of place in that directory. And why is it called `test_rational`? Is it just in numpy so we can test things with a custom dtype?

**Comment by njsmith** [comment]
Yes, it's just for tests that need a custom dtype, not for public use.

**Comment by jaimefrio** [comment]
Clsed by #5724
