### ISSUE TITLE
the linalg norm axis keyword argument versionadded is not documented

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5727]
According to comments it should be 1.8.
http://stackoverflow.com/questions/20168596/linalg-norm-not-taking-axis-argument
http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html

Also in the current master branch the `keepdims` versionadded appears to be documented ~~but possibly not using correct sphinx formatting.  I think it needs more newlines.~~

**Comment by charris** [comment]
That form of `.. versionadded::` work fine, the blank line is only needed if it follows the text. I suspect the preceding `arg : ...` line serves the same purpose.
