### ISSUE TITLE
Recent updates cause importing numpy failed.

### ISSUE THREAD

**Issue by t3476** [numpy/numpy#5728]
![screenshot-1](https://cloud.githubusercontent.com/assets/3604312/6872279/392ced72-d4e3-11e4-8941-f8f113127780.png)

python-3.4.3
numpy-1.9.2

**Comment by charris** [comment]
Did you build numpy yourself? I'll guess a Cython problem, but need to know more. What distro? what OS?

**Comment by pv** [comment]
It's probably just user error -- built against Python with
--with-valgrind enabled, but running with Python compiled without that flag.

**Comment by t3476** [comment]
I didn't build them nor do anything tricky. What I did is just "pip install numpy --upgrade"  in a virtualenv's evironment.
Before updating, numpy still worked.

**Comment by pv** [comment]
That command builds numpy. What you write above suggests that it ends up obtaining a header file from the wrong Python version. There are various reasons why this could happen, starting from having CPATH environment variable etc.

**Comment by t3476** [comment]
After I rollback numpy to 1.9.1 and update to 1.9.2 with pip again, the problem disappears.
I'm sorry that I don't know what happened at all but it just disappears.

**Comment by charris** [comment]
Closing this. The conversation can continue if needed.
