### ISSUE TITLE
random.multivariate_normal doesn't work in 1d case

### ISSUE THREAD

**Issue by iuventus** [numpy/numpy#5734]
I don't think a mathematician would write a multivariate function that doesn't work in the particular case of n = 1. 

I've written code that in several places generates correlated normals with a given covariance matrix, but I now need to re-write the code to handle the special case in which the incoming data is one-dimensional. 

I consider this a bug, because I cannot imagine why anyone would design it like that.

**Comment by seberg** [comment]
Maybe you could give an example? Since the terminology seems not clear....

**Comment by pv** [comment]
`np.random.multivariate_normal([0], [[1.0]], size=1)` seems to work fine. The error is probably in your own code.

**Comment by iuventus** [comment]
Thanks a lot for the responses both. 

I was running the below:
*
In []:
means = np.array([0.])
covs = np.array([1.])
np.random.multivariate_normal(means,covs,5)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-62-41ba4a67c277> in <module>()
      1 means = np.array([0.])
      2 covs = np.array([1.])
----> 3 print np.random.multivariate_normal(means,covs,5)

mtrand.pyx in mtrand.RandomState.multivariate_normal (numpy/random/mtrand/mtrand.c:23060)()

ValueError: cov must be 2 dimensional and square
*

But I can see now from pv's response that I need the extra square bracket on the cov definition. It was the false error message that was throwing me off.

**Comment by charris** [comment]
Closing this then. I can't think of any default handling of 1-D arrays that makes much sense.

**Comment by iuventus** [comment]
thanks for the responses. I was missing the extra square bracket on the cov definition to make it 2d.

**Comment by njsmith** [comment]
BTW, if you think the error message could have been clearer then that could
also be a bug -- feel free to submit a PR improving it.

On Sun, Mar 29, 2015 at 11:55 AM, iuventus <notifications@github.com> wrote:

> thanks for the responses. I was missing the extra square bracket on the
> cov definition to make it 2d.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5734#issuecomment-87455221>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org
