### ISSUE TITLE
Cannot reliably compare uint64 values to integers?

### ISSUE THREAD

**Issue by nasailja** [numpy/numpy#5746]
According to this program any value between ...cde0 and ...cdef is equal to uint64 value of ...cdef which was a big surprise

```
import numpy
a = numpy.uint64(0x1234567890abcdef)
if a == 0x1234567890abcde0:
    print("BUG!")
```

Seems like uint64 is converted to float even when it is compared against standard integers which was another big surprise for me.

**Comment by jaimefrio** [comment]
Probably related to #5612.

**Comment by nasailja** [comment]
Looks more like a bug in uint64: https://github.com/numpy/numpy/issues/5745

**Comment by seberg** [comment]
Closing as duplicate of gh-22624
