### ISSUE TITLE
rfftn returns full sized fftn array instead of "half+1 sized"

### ISSUE THREAD

**Issue by egpbos** [numpy/numpy#5754]
My `np.fft.rfftn` returns a wrongly shaped array:

`Enthought Canopy Python 2.7.6 | 64-bit | (default, Sep 15 2014, 17:43:19) `
`[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import numpy as np`
`>>> grid = np.random.random((8,8,8))`
`>>> np.fft.rfftn(grid).shape`
`(8, 8, 8)`

The shape should be `(8, 8, 5)` in this case. What could be causing this behavior? Numpy version is 1.8.1. I'm running on Mac OS X 10.9 (Mavericks).

**Comment by Nodd** [comment]
I checked with numpy 1.9.2 on Linux and I have the correct shape.

**Comment by egpbos** [comment]
Found the problem: Enthought Canopy Python has the fastnumpy package and (apparently) a modified numpy that automatically (when available) loads fastnumpy, which replaces the fft library with an MKL accelerated version. The MKL version seems to misbehave. Removed the fastnumpy package and now it again works as expected.

**Comment by charris** [comment]
@egpbos You might let Enthought know, they support 350+ packages and it would be easy for something like that to slip through. We also should have a test for the shape, which would help find such things.

**Comment by Nodd** [comment]
I added some test in https://github.com/numpy/numpy/pull/3883, but they doesn't specifically test the 3D case.

**Comment by egpbos** [comment]
I sent a bug report to Enthought.

**Comment by aaren** [comment]
Have just come across this in Anaconda (numpy 1.9.2 with MKL and no fastnumpy).

**Comment by njsmith** [comment]
@aaren: have you filed a bug report with continuum?

**Comment by aaren** [comment]
I was about to, but now think it might actually be my understanding of rfftn that is in error. I'm getting an output array with a half sized last axis and full sized elsewhere, where I thought the output would be half sized on all axes, rather than just the last.

**Comment by njsmith** [comment]
Ah, I think that's correct then, yeah. This isn't any kind of
multi-dimensional fft, it's just doing n 1d ffts, each of which returns
half+1 elements.

**Comment by aaren** [comment]
This is actually documented as well (they all start to look the same after a while...). From the doc for `rfftn`:

> This function computes the N-dimensional discrete Fourier Transform over
> any number of axes in an M-dimensional real array by means of the Fast
> Fourier Transform (FFT).  **By default, all axes are transformed, with the
> real transform performed over the last axis, while the remaining
> transforms are complex.**

I was naively expecting the real transform over all axes. Not sure why this isn't the case to be honest.

**Comment by njsmith** [comment]
Sorry, I missed that this is rfftn, not rfft :-). My guess is that the
answer is, the output of rfft is no longer real, so you can't call rfft
repeatedly on multiple axes, only the first. But I'm not an fft expert, so
if you think something is wrong or confusing then you should ask in a new
issue or on the mailing list.

**Comment by aaren** [comment]
Yes, that makes sense. Will follow up elsewhere. Thanks :)
