### ISSUE TITLE
numpy.MachAr does not allow for denormals

### ISSUE THREAD

**Issue by OceanWolf** [numpy/numpy#5755]
Using numpy 1.8.2 on python 2.7.9, the return value of `MachAr.xmin` does not take into consideration of denormals, getting a value of `e-308` (see below), but much lower values exist for floats in the form of denormals.

``` python
In [1]: import numpy as np

In [2]: np.MachAr(float).xmin
Out[2]: 2.2250738585072014e-308
```

**Comment by juliantaylor** [comment]
the documentation says xmin is `ibeta**minexp` and beta is the smallest exponential with no leading zeros in the mantissa.
So the value is correct, though the naming is misleading

to get the real smallest value you can use `np.nextafter(0, 1)`

**Comment by juliantaylor** [comment]
note though that if you're C'library is compiled with a different compiler than numpy ´np.nextafter´ might give you the wrong result. subnormal support is compiler dependent, e.g. intels compiler flushes them to zero by default

**Comment by argriffing** [comment]
Maybe this is what is meant by 'usable' in 'the smallest [in magnitude] usable floating value'?

**Comment by ewmoore** [comment]
Given the large run time penalty from subnormals, I don't think we should
encourage people to introduce them deliberately into their code.

**Comment by OceanWolf** [comment]
@ewmoore I understand your concern, but at the moment the docs appear out of sync with code.

I think we need to make it clear what we mean by ``usable`` and ``machine``.  Once we have clear definitions of those, we can then determine whether the doc and/or the code needs to change.

For example does the term ``machine`` refer to just the base architecture, or the software compiled for it, if I understand @juliantaylor's comment correctly, the architecture should always support subnormals, however it depends on the compiliation of the software as to whether the end user can use it or not.

**Comment by WarrenWeckesser** [comment]
`MachAr` has been deprecated in https://github.com/numpy/numpy/pull/20201, so I don't think the `MachAr` code or docs will be updated.  Closing.
