### ISSUE TITLE
issubdtype(None, float) == issubdtype(np.float64, None) == True ??

### ISSUE THREAD

**Issue by bskinn** [numpy/numpy#5767]
Using Python 2.7.6 & numpy 1.8.1, passing `None` and either `float` or a `numpy.float#` subtype to `issubdtype` always yields `True`:

    >>> np.issubdtype(None, float)
    True
    >>> np.issubdtype(float, None)
    True
    >>> np.issubdtype(np.float64, None)
    True
    >>> np.issubdtype(None, np.float64)
    True

If I understand the nature of `NoneType` correctly, it seems to me that `issubdtype` should return `False` in all cases where `None` is passed to either argument, save for when `None` is passed as both arguments.  `np.issubdtype(None, int)` yields `False`, as I would expect.

Apologies if I'm misunderstanding, or if this has been fixed between 1.8.1 and 1.9.2.

**Comment by Nodd** [comment]
It's not fixed:
```
>>> import numpy as np
>>> np.__version__
'1.9.2'
>>> np.issubdtype(None, float)
True
>>> np.issubdtype(float, None)
True
>>> np.issubdtype(np.float64, None)
True
>>> np.issubdtype(None, np.float64)
True
>>> np.issubdtype(None, None)
True
```

**Comment by pv** [comment]
Both arguments of `issubdtype` are meant to be Numpy dtypes. `None` itself is *not* a valid Numpy dtype. However, it is translated to mean the Numpy default dtype, similarly as in `np.zeros(5, dtype=None)`. Perhaps you are thinking about `isinstance`?

**Comment by bskinn** [comment]
> Both arguments of issubdtype are meant to be Numpy dtypes.

Ah, I had missed that subtlety in reading the Numpy docs.  Feature, not bug, then. Gotcha.

> Perhaps you are thinking about isinstance, or issubclass instead?

It's been a while since I wrote the particular piece of code; I need to check an incoming parameter to ensure it's `int` or `float`, or one of the Numpy derived types.  I'm pretty sure I tested `isinstance` and it didn't do what I wanted for some reason; but that was early on in my Python learning curve so I may just have been doing something dumb.  I'll recheck.  

Thanks for the response!

**Comment by seberg** [comment]
Yes, isinstance would not work in general, unless you have a new enough numpy version and use the `numbers` ABC. Or first convert/make sure you have a numpy type and you can use the issubdtype if oyu are sure it is numpy.

**Comment by bskinn** [comment]
Is there a way to coerce a value of unknown type to the nearest "matching" Numpy type?  (I'm still hazy on how Numpy (broad)casts, so this may be simple.)

**Comment by argriffing** [comment]
> Is there a way to coerce a value of unknown type to the nearest "matching" Numpy type? (I'm still hazy on how Numpy (broad)casts, so this may be simple.)

Unless your non-numpy types are something like Python integers or floats I think numpy will encyst your stuff into a zero dimensional object array, which is probably not what you want.
