### ISSUE TITLE
Inconsistent arange behaviour with different int types

### ISSUE THREAD

**Issue by ml31415** [numpy/numpy#5775]
Given this code:

``` python
import numpy as np
np.arange(1,1,0)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

Obviously step 0 is an invalid input for creating a range. So the division error is understandable, but might be more explicit. What surprised me, was the following behaviour:

``` python
np.arange(np.int64(1),1,0)
__main__:1: RuntimeWarning: invalid value encountered in long_scalars
>>> array([], dtype=int64)
```

The code is as wrong as before, but now instead of throwing any error, it just returns an empty list. Shouldn't it throw exactly the same error as above? An error explicitly stating, that a range with a step of 0 can't be specified?

**Comment by jaimefrio** [comment]
I'm guessing you are running a 32-bit version of numpy, but can you please confirm?

**Comment by jaimefrio** [comment]
Whoever fixes this, there's also a potential memory leak around [here](vhttps://github.com/numpy/numpy/blob/e84454aded855a70c3dcfd586a3a0c0e108d0ab7/numpy/core/src/multiarray/ctors.c#L3138): the output array is assigned, and then three separate operation are performed and checked for failure: setting the first item, setting the second, calling the type's `fill` function. Only if the last one fails is the return array decref'ed. That should be moved to the `fail` block.

**Comment by jaimefrio** [comment]
Also, this seems like a great candidate to have all the input checking and preliminary calculations rewritten in Python and added to `_internal.py`, and then have them called from the C function. All those checks in C are painful to read...

**Comment by ml31415** [comment]
I'm running 1.9.2 with 64 bit on linux.

**Comment by njsmith** [comment]
Then I'll also note for future searching that this might be a good test
candidate for rewriting in cython, if we ever get around to making Cython
usable in multiarray.

**Comment by jaimefrio** [comment]
I left out the link to the potential memory leak: [starting here](https://github.com/numpy/numpy/blob/e84454aded855a70c3dcfd586a3a0c0e108d0ab7/numpy/core/src/multiarray/ctors.c#L3138).

**Comment by melissawm** [comment]
As of NumPy 1.24.0, here are the results for the initial report:

```
In [1]: np.arange(1, 1, 0)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 np.arange(1, 1, 0)

ZeroDivisionError: division by zero

In [2]: np.arange(np.int64(1), 1, 0)
<ipython-input-2-2d6e08a07532>:1: RuntimeWarning: invalid value encountered in scalar divide
  np.arange(np.int64(1), 1, 0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 np.arange(np.int64(1), 1, 0)

ValueError: arange: cannot compute length

In [3]: np.arange(np.int(1),1,0)
<ipython-input-3-18a95710960b>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.arange(np.int(1),1,0)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 np.arange(np.int(1),1,0)

ZeroDivisionError: division by zero

In [4]: np.arange(np.int32(1),1,0)
<ipython-input-4-39d83bf791d7>:1: RuntimeWarning: invalid value encountered in scalar divide
  np.arange(np.int32(1),1,0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 np.arange(np.int32(1),1,0)

ValueError: arange: cannot compute length
```

It looks like the initial report has been addressed. @seberg I know you routinely check for memory leaks, is this one still relevant?

**Comment by seberg** [comment]
@melissawm if we have a test that runs into the issue, no (i.e. raises the error probably).  Otherwise, I cannot say without checking it closer.

That said, I suspect it is long fixed, sorry, I can't do a full check right now.

**Comment by ml31415** [comment]
Now `np.int32` and `np.int64` produce a `ValueError` while `int` and `np.int` produce `ZeroDivisionError`. This is unfortunately still inconsistent.

**Comment by rgommers** [comment]
The difference that remains has little to do with `arange`. It's basically Python vs. NumPy scalars:
```python
>>> 1/0
Traceback (most recent call last):
  Cell In [15], line 1
    1/0
ZeroDivisionError: division by zero

>>> np.int64(1)/0
<ipython-input-16-0b4c6413f478>:1: RuntimeWarning: divide by zero encountered in long_scalars
  np.int64(1)/0
inf
```

Given that `/` is true division, producing a floating-point number (namely, `inf`) for `1/0` seems correct - so it's Python that is inconsistent with itself here. 

There's nothing to fix in NumPy, so I'll close this issue. Thanks all!
