### ISSUE TITLE
numpy.reshape overflow of np.prod somewhere?

### ISSUE THREAD

**Issue by MaximilianHoffmann** [numpy/numpy#5794]
I try to reshape a large array. numpy.reshape returns 

ValueError: total size of new array must be unchanged

I couldn't find it, but is it possible that there is a overflow of np.prod in the source code?
I checked the shapes and they are certainly ok! I read in a from a binary file and if I increase the size, the error sets in, where it was lacking at the beginning.

**Comment by seberg** [comment]
You are probably using an old numpy version, can you upgrade at least to 1.8. I would guess and then try again?
