### ISSUE TITLE
An error in odeint program

### ISSUE THREAD

**Issue by ocean164347** [numpy/numpy#5798]
I wrote a program to use odeint to solve a differential equation. But it had a problem. When I setted Cosmopara as np.array([70.0,0.3,0,-1.0,0]), it gave a warning that "invalid value encountered in sqrt" and "invalid value encountered in double_scalars" in "h = np.sqrt(y1 ** 2 + Omega_M * t ** (-3) + Omega_DE*y2)". But I checked that line and didn't find any error. If Cosmopara = np.array([70.0,0.3,0.0,-1.0,0.0]), Y shouldn't change but it changed. Besides, If I chose Cosmopara = np.array([70.0,0.3,0.1,-1.0,0.1]), this program could give a right result. I don't know why. So please help me. Followwing is my program.

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

global CosmoPara
Cosmopara = np.array([70.0,0.3,0.0,-1.0,0.0])

def derivfun(Y,t):
    Omega_M = Cosmopara[1]
    Sigma_0 = Cosmopara[2]
    omega = Cosmopara[3]
    delta = Cosmopara[4]
    Omega_DE = 1-Omega_M-Sigma_0 ** 2
    y1 = Y[0]
    y2 = Y[1]
    h = np.sqrt(y1 ** 2 + Omega_M * t ** (-3) + Omega_DE * y2)
    dy1dt = -3.0 * y1/t + (delta * Omega_DE * y2)/(t * h)
    dy2dt = -(3.0 * (1+omega) + 2.0 * delta * y1/h) * y2/t
    return np.array([dy1dt,dy2dt])
    
z = np.linspace(1,2.5,15001)
time = 1.0/z
Omega_M = Cosmopara[1]
Sigma_0 = Cosmopara[2]
omega = Cosmopara[3]
delta = Cosmopara[4]
Omega_DE = 1-Omega_M-Sigma_0 ** 2
y1init = Sigma_0
y2init = 1
Yinit = np.array([y1init,y2init])

Y = odeint(derivfun,Yinit,time)

y1 = Y[:,0]
y2 = Y[:,1]

h = np.sqrt(y1 ** 2 + Omega_M * time ** (-3) + Omega_DE * y2)

plt.figure()
plt.plot(z,h)
plt.show()

**Comment by pv** [comment]
This seems to be a bug in your own code. Try stackoverflow.com for debugging help.

**Comment by ocean164347** [comment]
pv, thanks for your answer. I had checked it already and didn't find any problem. Because I wrote it in Matlab and it could run rightly. Besides, I said above, if I used Cosmopara = np.array([70.0,0.3,0.0,-1.0,0.0]), the program could get a right result in python. So I still don't kwon what's wrong in my program.

**Comment by pv** [comment]
Yes, however, this is not the correct forum for looking debugging help.

**Comment by ocean164347** [comment]
I see. Thank you anyway

**Comment by pv** [comment]
Nevertheless, to resolve your problem --- try passing `hmax=0.1`
parameter to odeint to limit the step size of the solver.

**Comment by ocean164347** [comment]
Wow, thank you evry much pv! It works! But how does it work? I still don't know. Could you tell the reason?
