### ISSUE TITLE
BUG: numpy.arctan returns nan for large complex arguments

### ISSUE THREAD

**Issue by pbrod** [numpy/numpy#5799]
The cmath.atan  is able to handle large complex values

    >>> import numpy as np
    >>> import cmath
    >>> t = -1.10076957173e+292+0j
    >>> cmath.atan(t)
    Out[37]: (-1.5707963267948966+0j) 
    >>> cmath.atan(1j*t)
    Out[38]: (-1.5707963267948966-9.084553440447778e-293j)

while numpy.arctan does not as shown here:

    >>> np.arctan(t)
    Out[39]: (nan+nan*j)
    np.arctan(1j*t)
    Out[40]: (nan+nan*j)

**Comment by pv** [comment]
Has already been fixed 35d01b2a

**Comment by pbrod** [comment]
Well, it does not work on my windows machine with numpy version 1.9.0

**Comment by charris** [comment]
The fix will be in numpy 1.10.
