### ISSUE TITLE
segfault of linalg.cond with some nan matrices

### ISSUE THREAD

**Issue by ml31415** [numpy/numpy#5802]
```python
import numpy as np
for xsize in range(1, 30):
    print "xsize: %s" % xsize
    x = np.ones((xsize, xsize)) * np.nan
    res = np.linalg.cond(x, 1)
```

Counts to 8 and then segfaults for me. Linux, 64bit, numpy 1.9.2. It also crashes for other multiples of 8 for xsize like 16 and 24. Everything else seems fine. Just tested, it also hits `linalg.inv`

**Comment by matthew-brett** [comment]
Not so for me on:

* OSX 10.9, Python 2.7.9, numpy 1.9.2 from standard pypi wheel;
* Debian 8.0 64-bit Python 2.7.9, numpy 1.9.2 compiled on system.

Can you give any more details of your system?    For example, on the Debian system, I have:

```
>>> np.__config__.show()
lapack_opt_info:
    libraries = ['lapack', 'f77blas', 'cblas', 'atlas']
    library_dirs = ['/usr/lib/atlas-base/atlas', '/usr/lib/atlas-base']
    define_macros = [('ATLAS_INFO', '"\\"3.10.2\\""')]
    language = f77
    include_dirs = ['/usr/include/atlas']
```

**Comment by ml31415** [comment]
```
In [2]: np.__config__.show()
blas_info:
    libraries = ['blas']
    library_dirs = ['/usr/lib']
    language = f77
lapack_info:
    libraries = ['lapack']
    library_dirs = ['/usr/lib']
    language = f77
atlas_threads_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['openblas']
    library_dirs = ['/usr/lib']
    language = f77
openblas_info:
    libraries = ['openblas']
    library_dirs = ['/usr/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas']
    library_dirs = ['/usr/lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1)]
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
```

**Comment by matthew-brett** [comment]
I wonder whether this is an openblas bug?

**Comment by ml31415** [comment]
No idea ... a simple `np.linalg.inv(np.ones((8,8)) * np.nan)` also kills it. Again only multiples of 8 affected.

**Comment by matthew-brett** [comment]
Did you install openblas with your package manager?   Which version do you have?

**Comment by ml31415** [comment]
```
$ apt-cache show libopenblas-base
Package: libopenblas-base
Priority: optional
Section: universe/libs
Installed-Size: 45092
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Science Team <debian-science-maintainers@lists.alioth.debian.org>
Architecture: amd64
Source: openblas
Version: 0.2.8-6ubuntu1
```

**Comment by ml31415** [comment]
So is it sure, that this is an openblas bug? Then I'm gonna file it there instead.

**Comment by njsmith** [comment]
It's plausible but not exactly confirmed... Before taking it to openblas it
would be good to have a small C file reproducer (using just openblas with
numpy not in the picture), or at least a debug trace showing that the crash
happens in openblas code and showing how the OpenBLAS routine was called.

**Comment by ml31415** [comment]
Any ideas how to write such a demonsrator?

**Comment by ml31415** [comment]
I failed to hack something together using openblas directly, but managed to reproduce the crash with armadillo and openblas. So I suppose this can be closed here and I'll file the bug there. Here the demonstrator in case someone cares:

```cpp
// g++ test_matrix_pseudoinverse.cpp -o test_matrix_pseudoinverse -L/usr/lib/openblas-base -larmadillo -lopenblas 

#include <cstdio>
#include <math.h>
#include <armadillo>

using namespace std;

int main()
{
    for(int M=1; M <= 15; M++) { // dimension
        arma::mat _A(M,M);
        arma::mat _B(M,M);

        for(int i=0; i < M; i++) {
            for(int j=0; j < M; j++) {
                //_A(i,j) = rand()/(1.0 + RAND_MAX);
                _A(i,j) = NAN;
            }
        }
        _B = arma::inv(_A);
        cout << M << " ";
    }
    cout << endl;
    return 0;
}

```

**Comment by ml31415** [comment]
This is the link to the openblas bug: https://github.com/xianyi/OpenBLAS/issues/556

**Comment by argriffing** [comment]
This is not unexpected behavior for numpy with BLAS/LAPACK. See https://github.com/numpy/numpy/pull/4324.

**Comment by ml31415** [comment]
Getting openblas from source indeed helped. Looks like ubuntu ships something rather outdated there. Thanks for the hints!
