### ISSUE TITLE
ix_() returned array has dtype=float64 when given empty range

### ISSUE THREAD

**Issue by chkothe** [numpy/numpy#5804]
```
>>> np.ix_(range(0,0))
(array([], dtype=float64),)
```
The correct dtype should be int32, since float indices are usually not accepted as indices in numpy arrays. That dtype is returned for non-empty ranges:
```
>>> np.ix_(range(0,1))[0].dtype
dtype('int32')
```

**Comment by chkothe** [comment]
Thanks much!

**Comment by jaimefrio** [comment]
You're welcome, but let's keep this open until the PR gets reviewed and merged...
