### ISSUE TITLE
numpy.polfit freezes pyotherside app on jolla

### ISSUE THREAD

**Issue by dasimmet** [numpy/numpy#5807]
I'm not quite sure whether im right here, maybe this is pyotherside's issue (or my build of numpy).
when I run numpy's "polyfit" function on my jolla phone in a pyotherside app, it always hangs exactly at the same place without returning or throwing any error.
It works fine when running the same code in the terminal Interpreter on the phone, or in pyotherside on the desktop, it does not matter how big the attempted fit is (it does not simply run out of memory)
To investigate further, running the debugger on polyfit(a,b,1,w=c) showed me the last few lines before also freezing:

    (Pdb) 
    --Return--
    > /usr/lib/python3.4/site-packages/numpy/core/_methods.py(38)_any()->False
    -> return umr_any(a, axis, dtype, out, keepdims)

    (Pdb) 
    --Return--
    > /usr/lib/python3.4/site-packages/numpy/core/fromnumeric.py(1848)any()->False
    -> return arr.any(axis=axis, out=out, keepdims=keepdims)
    (Pdb) 
    > /usr/lib/python3.4/site-packages/numpy/core/machar.py(233)_do_init()
    -> i = i + 1
    (Pdb) 
    > /usr/lib/python3.4/site-packages/numpy/core/machar.py(234)_do_init()
    -> k = k + k
    (Pdb) 
    > /usr/lib/python3.4/site-packages/numpy/core/machar.py(223)_do_init()
    -> for _ in range(max_iterN):
    (Pdb) 
    > /usr/lib/python3.4/site-packages/numpy/core/machar.py(224)_do_init()
    -> y = z
    (Pdb) 
    > /usr/lib/python3.4/site-packages/numpy/core/machar.py(225)_do_init()
    -> z = y*y
    (Pdb) 

Has anyone an idea what could be causing this?
I havent seen any bug like this yet.
To reproduce, I created a quick demo:
[numpy bug showcase](https://github.com/dasimmet/numpy-polyfit-bug-on-jolla-)
run the installed app with sailfish-numpy in terminal on the jolla and press the button, it should bring up the python debugger.

the version of numpy I use is built by installing dependencies and running "pip wheel numpy" on the jolla phone, then extracted into the app dir.
The architecture it is built against is armv7hl.
Any other numpy function I tried seemed to work flawlessly.
Thanks for any kind of help

**Comment by charris** [comment]
Well, this is different ;) I suspect it is in the linear algebra functions but can't say more at this point. Can you compile things on your phone?

**Comment by charris** [comment]
Actually, looks like `machar.py` is the problem if the debug execution is correct.

**Comment by charris** [comment]
Can you try running `finfo('d').eps`?

**Comment by dasimmet** [comment]
i can compile things, though im not an expert in lower level languages... 
finifo("d") shows exactly the same error. 
from command line, it terminates with 2.2204460492503131e-16.
note also, that I could not compile(pip wheel) scipy, since lapack/blas are not available (I read somewhere they are optional dependencies of numpy also).

**Comment by dasimmet** [comment]
The Issue was caused by pyotherside, and it has already been fixed with version 1.4, which has not been up to date.
Thanks for your efforts!

**Comment by charris** [comment]
Thanks for the update.
