### ISSUE TITLE
Generator for normally distributed random numbers that reproduces MATLAB

### ISSUE THREAD

**Issue by Shambricool** [numpy/numpy#5810]
We've faced the problem of reproducing MATLAB's randn() while porting a project from MATLAB to Python (see this issue https://github.com/scipy/scipy/issues/4666). The solution that worked for us was to use MATLAB Coder for generating a C code for randn() function and wrapping it as a C extension to Python.
MATLAB uses Ziggurat method for generating gaussian random numbers and there were a lot of proposals here to implement it. Maybe the code generated by MATALB Coder could be used by numpy for implementing Ziggurat in numpy?
A project with a C extension for Python can be found here https://github.com/Shambricool/py_matlab_randn

**Comment by rkern** [comment]
No, much of the generated code (like the actual Ziggurat method implementation) is still copyright Mathworks under a proprietary license and cannot be incorporated into numpy. Specifically ([from the 2011 license text](http://www.mathworks.com/matlabcentral/answers/5988-does-mw-own-copyright-on-c-code-generated-by-matlab#answer_8317), at least): "MathWorks Coder Programs cannot be used to create an Application (a) providing scripting capability similar to the capabilities of any of the Programs; (b) providing functionality or behavior similar to that of the MATLAB command line; ...". IANAL and TINLA, but I would not distribute the generated source code as a Python extension module.

More generally, the implementation of the Ziggurat algorithm is not the blocking factor. We have a couple waiting in the wings. It could be added without much trouble if anyone wants to do the work. It just can't *replace* the current implementation of `randn()` and the others for backwards compatibility reasons. It would have to be added as a new method.

Bit-for-bit compatibility with MATLAB(TM) is explicitly not a goal, so it is still possible that our implementation will still not give the exact same numbers as MATLAB(TM).

**Comment by pv** [comment]
Matlab Coder license *explicitly forbids* what you are doing, so no go.
It's probably legally risky even to look at the generated source to try
to reverse engineer it.

**Comment by rkern** [comment]
Closing as we do have an existing issue that tracks the addition of the Ziggurat method: https://github.com/numpy/numpy/issues/2047
