### ISSUE TITLE
doc: dead links

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5813]
As mentioned in https://github.com/numpy/numpy/issues/5811#issuecomment-97124230 the page http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.vonmises.html has some dead links.

**Comment by charris** [comment]
@argriffing Those links are broken for all the distributions and probably don't belong there at all.

**Comment by urbanophile** [comment]
Does this mean that the broken links to the scipy stats module should be removed for all the numpy stats distributions in the documentation?

**Comment by rgommers** [comment]
Hmm, I think the links to scipy.stats distributions with the same name do have value. I'd rather see them fixed up. Can't be too hard.
