### ISSUE TITLE
argsort bug

### ISSUE THREAD

**Issue by hantek** [numpy/numpy#5816]
I come across a wrong numpy output while using argsort():

>>> x
array([  2.43752439e-01,   2.12345154e-01,   3.00682512e-01,
         8.82461778e-01,   6.54040476e-01,   9.66741454e-04,
         1.41006860e-01,   3.42346428e-02,   2.20661171e-01,
         1.04476288e+00,   1.82253038e-01,   5.79845517e-01,
         5.15250240e-01,   1.31020432e+00,   1.77514292e+00])
>>> x.argsort()
array([ 5,  7,  6, 10,  1,  8,  0,  2, 12, 11,  4,  3,  9, 13, 14])

Apparently the number 1.04476288e+00 in x[9] should be the third largest, but it yields that the number 2.20661171e-01 in x[8] is the third largest. 

It doesn't seem like an error caused by this simple code itself, so I consider it as a bug in argsort()

I am using numpy 1.6.1, python 2.7.2.

**Comment by Nodd** [comment]
I think you're misreading the exponent part: 1.04476288 is greater than 0.220661171
You can use `x[x.argsort()]` to see this more clearly.

**Comment by hantek** [comment]
Well, I misinterpreted x.argsort(). So it's correct. Sorry about that.

**Comment by jaimefrio** [comment]
Closing this then.

**Comment by juanmabelda** [comment]
It seems as argsort has a bug for dimension 3 arrays in an specific order.

For instance if I wrote

import numpy as np

np.argsort(array([2,3,1])

The returned value is:
array([2, 0, 1])

If I change the order of the numbers (i.e. [1,2,3]) the function works well. 

I have cross checked the malfunction in python 2.7.6 with numpy 1.8.2 and python 3.5.2 with numpy version 1.11.1 both in windows and linux.
