### ISSUE TITLE
`np.random.normal` with 0 scale

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#5818]
Currently `np.random.normal` refuses to generate random variates with no standard deviation (i.e., a stream of zeros).  While this could make sense for more featureful random libraries (e.g. scipy's, as the pdf becomes harder to define), when all we can have is a stream of numbers, the limitation seems arbitrary.

Use case: Be able to generate simulated data with zero noise using the same code as I generate data with some gaussian noise, just by passing a std of 0, rather than special-casing it.

**Comment by njsmith** [comment]
Sounds like a legit bug to me. Want to make a patch?

On Wed, Apr 29, 2015 at 9:59 PM, Antony Lee <notifications@github.com>
wrote:

> Currently np.random.normal refuses to generate random variates with no
> standard deviation (i.e., a stream of zeros). While this could make sense
> for more featureful random libraries (e.g. scipy's, as the pdf becomes
> harder to define), when all we can have is a stream of numbers, the
> limitation seems arbitrary.
>
> Use case: Be able to generate simulated data with zero noise using the
> same code as I generate data with some gaussian noise, just by passing a
> std of 0, rather than special-casing it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5818>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by jaimefrio** [comment]
This should be a very simple change, replace a `<=` by a `<` [here](https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L1564), and a `less_equal` by a `less` a few lines further down.

**Comment by anntzer** [comment]
There's quite a few other distribs which could probably allow 0 as their main parameter.  Should we fix them too?

**Comment by jaimefrio** [comment]
Sure, make a PR changing as many as you see fit, we can discuss the details during the review.

**Comment by mbolt01** [comment]
Is this still due to be updated int he numpy package anytime soon?

**Comment by michaalbert** [comment]
Hi, just wanted to mention that this issue was fixed in [pull request #5822](https://github.com/numpy/numpy/pull/5822).
