### ISSUE TITLE
np.allclose does not handle infinities correctly

### ISSUE THREAD

**Issue by david-zwicker** [numpy/numpy#5820]
Running 

    np.allclose([np.inf, np.inf], np.inf)

raises the following error my machine (macosx, python 2.7 + numpy 1.9.2 from macports):

    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    <ipython-input-6-318ae0ed72a3> in <module>()
          1 a = np.full(2, np.inf)
    ----> 2 np.allclose(a, np.inf)

    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/numeric.pyc in allclose(a, b, rtol, atol)
       2224             return False
       2225         # Check that sign of inf's in x and y is the same
    -> 2226         if not all(x[xinf] == y[xinf]):
       2227             return False
       2228 

    IndexError: index 1 is out of bounds for axis 1 with size 1
    
Interestingly, running the same code on a linux machine (pyhton 2.7 + numpy 1.8.1) fails
at the same line, but raises a `ValueError: too many boolean indices` error.

I suspect this is because I compare an array with a single number, since `np.allclose([np.inf, np.inf], [np.inf, np.inf])` works. However, `np.allclose([1, 1], [1])` returns `True`.

I'm not sure what `np.allclose` should return when a single element is compared to an array, but there certainly is an inconsistency here.

**Comment by charris** [comment]
Fixed in master.
```
In [1]: np.allclose([np.inf, np.inf], np.inf)
Out[1]: True

In [2]: np.__version__
Out[2]: '1.10.0.dev0+1cfe6d9'
```
