### ISSUE TITLE
distutils makes it too hard to install from source with mingw32

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#5832]
One can build from source with:

    $ python setup.py build --compiler=mingw32 

but then installing fails. Doing:

    $ python setup.py install --compiler=mingw32 

results in 

    ...
    error: option --compiler not recognized 

And doing:

    $ python setup.py install

results in this obscure error:

    ...
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands
    --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    No module named 'numpy.distutils.msvccompiler' in numpy.distutils;
    trying from distutils
    Unable to find productdir in registry
    Checking environ VS100COMNTOOLS
    error: Unable to find vcvarsall.bat 

This was reported at http://numpy-discussion.10968.n7.nabble.com/Compiling-NumPy-on-Windows-for-Python-3-3-td8653.html, can be found on various StackOverflow issues and is related to http://bugs.python.org/issue2943.

Most SO answers (which all recommend installing MSVC) and Python issue 2943 are not the whole story though, because if you add a file ``distutils.cfg`` in the ``distutils`` directory (a local ``setup.cfg`` or a ``$HOME/.pydistutils.cfg`` should also work) containing

    [build]
    compiler=mingw32 

then ``python setup.py install`` works fine. Because this will probably never be fixed in distutils (bug report open for 7 years...), maybe it can be fixed in ``numpy.distutils``. And otherwise at least this issue serves as documentation....

**Comment by jaimefrio** [comment]
Until I switched to OSX a few months ago, I have been building numpy with mingw, and still do occasionally. The magic spell I invoke to make things happen is:

    python setup.py config --compiler=mingw32 build --compiler=mingw32 install

which I think I got from some "build scipy with mingw" page off the internet somewhere, probably [here](http://nipy.sourceforge.net/nipy/devel/devel/install/windows_scipy_build.html). I have never tried to dissect exactly what each part of the incantation does, but it sure works

**Comment by rgommers** [comment]
Thanks @jaimefrio. Now that I have the full command to google, I see that it's included in http://wiki.scipy.org/Wiki/Build_for_Windows. http://scipy.org/scipylib/building/windows.html only contains the ``bdist_wininst`` variant. In numpy's ``INSTALL.txt`` it's also missing.
