### ISSUE TITLE
f2py CLI configuration problem

### ISSUE THREAD

**Issue by ckald** [numpy/numpy#5834]
I tried today to compile a small fortran code for my python modules and encountered the following problem (Python 2.7.9, OS X 10.10.3, Numpy 1.9.2):

```
(env)➜  pyBBN  f2py
zsh: /Users/b/Repositories/BBN/pyBBN/env/bin/f2py: bad interpreter: /Users/travis/build/MacPython/numpy-wheels/venv/bin/python: no such file or directory
```

This happened both with virtualenv numpy and system one. `python -c "from numpy import f2py; f2py.test()"` worked fine.

I had to edit the `/Users/b/Repositories/BBN/pyBBN/env/bin/f2py` to replace the weird shabang to be `#!/usr/bin/env python`. Now f2py executes fine

**Comment by charris** [comment]
This is may have been addressed by #5815, but @matthew-brett I think the form `#!/usr/bin/env python` is preferred for portability.

**Comment by matthew-brett** [comment]
The form `#!python` is for setuptools to know it should replace the shebang line when installing into - say - a virtualenv.  I believe - from some experiments I just did - that setuptools will leave `#!/usr/bin/env python` as it is when installing the script, but will change `#!python` to point to the path of the installing Python.

I realize now I think about it, I don't know what happens on Windows - to make `f2py` callable as a command - I wonder if it has been tested after installing into a virtualenv.

**Comment by charris** [comment]
I made a comment on your new PR. Whatever works is probably the principle here.

**Comment by seberg** [comment]
Sounds like the linked PR above should have fixed it (and it is a very old f2py build related issue, that would have come up again otherwise).
