### ISSUE TITLE
Inconsistency in setdiff1d return value dtype

### ISSUE THREAD

**Issue by christianbrodbeck** [numpy/numpy#5846]
I noticed this discrepancy in the dtype of the returned array because it lead to an "Implicitly casting between incompatible kinds" warning down the line:

```py
In [33]: np.setdiff1d(np.array([1], np.uint32), [], True)
Out[33]: array([1], dtype=uint32)

In [34]: np.setdiff1d(np.array([], np.uint32), [], True)
Out[34]: array([], dtype=bool)
```

It looks like this could be easily fixed in https://github.com/numpy/numpy/blob/50e4eb87370b77792f1f6d21a5edd6ff20abee68/numpy/lib/arraysetops.py#L478 by returning `ar1` instead of `aux`, is there another reason for returning `aux` instead?

**Comment by jaimefrio** [comment]
It seems like that would fix this indeed. There may be a simpler way though:

The general return of this function is built as `np.asarray(ar1)[aux == 0]`. Given that `aux` is the return of a call to `np.in1d`, which has an `invert` optional kwarg, that could instead be computed as:

```
aux = in1d(ar1, ar2, assume_unique=True, invert=True)
return np.asarray(ar1)[aux]
```
It may not be obvious, but that will also work without any specific special casing if `ar1` is empty:

```
>>> a = np.array([], dtype=float)
>>> b = np.in1d(a, [1, 2, 3])
array([], dtype=bool)
>>> a[b]
array([], dtype=float64)
```

So we can get rid of the branch on the size of `aux` altogether.

Would you like to send a PR?

**Comment by christianbrodbeck** [comment]
Sounds good, yes I'll send a PR
