### ISSUE TITLE
UserWarning in tests.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#5850]
`/usr/local/lib/python3.4/dist-packages/numpy/distutils/cpuinfo.py:120: UserWarning: [Errno 2] No such file or directory: '/proc/cpuinfo'`

This may be due to the way Travis CI runs tests.

**Comment by seberg** [comment]
OK, I did not check, but a user warning in a Travis CI test frun from 2015 seems not very relevant anymore, closing ;).
