### ISSUE TITLE
Equality specifier for numpy.unique

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#5853]
I would like to suggest a way to specify the equality function used in `np.unique`, e.g. with a `equality` argument (typical use-case: `np.isclose` for arrays of floats).  True, `isclose` is not transitive but it's probably still fine.
Implementation-wise, it's just a matter of replacing `aux[1:] != aux[:-1]` (l. 198) by the new equality function.

**Comment by jaimefrio** [comment]
This may be tricky... Because `np.unique` and friends rely on sorting, I'm not sure results would be meaningful. As an example, using a function like:

```
def f(a, b):
    return np.abs(a - b) < 0.2
```

would result in things like:

```
>>> np.unique([0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1[, equality=f)
array([0.])
>>> np.unique([0, .1, .2, .3, .4, .45, .6, .7, .8, .9, 1[, equality=f)
array([0. , 0.6])
```

which I am not sure make too much sense. Do you have a concrete example where this functionality is needed?

**Comment by anntzer** [comment]
Yes, certainly using a "nonsensical" equality function would give nonsensical results.  Perhaps a big fat warning telling to not use anything but `np.isclose` and friends.
The case I was more interested in was issues with floating point equality, typically
```
In [1]: np.unique(np.diff(np.linspace(0, 1, 11)))
Out[1]: array([ 0.1,  0.1,  0.1,  0.1])
```

**Comment by seberg** [comment]
I think I will close this. I agree with Jaime's point that this seems to have a pretty large ambiguity since associativity is lost `a != c` but `a == b` and `b == c` is possible, and what do you do then? We can reopen with a more specific idea, but I do not feel it is actionable as such.
