### ISSUE TITLE
floating point errors can deadlock when using multiple embedded sub interpreters

### ISSUE THREAD

**Issue by ndjensen** [numpy/numpy#5856]
If an application is using multiple embedded sub interpreters that use numpy, there is a possibility that floating point errors can cause the thread to deadlock.  I traced this down to ufunc_object's _error_handler() method where it does NPY_ALLOW_C_API and that freezes on PyGILStateEnsure().  Interestingly, the PyGILState API is allegedly unsafe for applications using sub interpreters, but it works fine as long as long as each sub interpreter is on its own thread.

There is a workaround to call numpy.seterr(all='ignore') as that will not even enter the method.  Ideally the print option would also not get the GIL as the GIL should not be needed for that.  In the meantime I added a warning to Jep when it detects an interpreter on the same thread in the hopes of deterring the conditions that can cause this.  I have a test case that illustrates the problem at https://github.com/mrj0/jep/blob/v3.3.0rc/src/jep/test/numpy/TestNumpyGILFreeze.java

This is somewhat related to gh-3837.  If you have problems running the test case, you may need to configure the environment variables PATH, LD_LIBRARY_PATH, or LD_PRELOAD depending on your system.

**Comment by njsmith** [comment]
Thanks for the report. As I think I said on an earlier report, we don't
have any objection in principle to improving our subinterpreter support,
but it's definitely not a supported configuration at the moment (as you've
noticed :-)), and I don't think any of us even understand what is required
to do this. So if you can provide patches that are not too intrusive, don't
cause noticeable slowdowns for the non-subinterpreter case, and have small
tests that we can include in the test suite (i.e., no java), then we'll be
happy to consider them.

**Comment by ndjensen** [comment]
Yeah, I understand it's low priority and not officially supported.  For the most part, numpy just works in a sub interpreter embedded environment, and then over years we've come across a few obscure things I've written up.  I figured they should be documented since they were difficult to track down and maybe someday sub interpreter support would become more important.

At present I'm also unsure how to fix it in a non-intrusive way, other than moving the print case outside of the GIL locking code, but that only takes care of one case and makes the code less clean.  Since there does exist two workarounds, either ignoring the floating point errors, or more correctly ensuring only one sub interpreter per thread in the embedding application, it's not a big deal.

I don't think I can provide a smaller test than what I have provided.  It does depend on Java and Jep, but to illustrate the issue requires starting up a multi-threaded application with multiple sub interpreters using numpy.  So the test case has a simple Java main(), albeit dependencies.  I wouldn't know where to start with attempting to include a test in the test suite.  The current set of tests appear to be written in python and I don't think we can spin up the appropriate conditions without involving a decent amount of C in the mix.  I was hoping if we ever came up with a solution for this, that we could use my test case to prove the problem had been fixed, and then numpy's test suite to prove the fix had no adverse effects.

**Comment by charris** [comment]
At a minimum, we could add an "embedded" flag to the issues.

**Comment by juliantaylor** [comment]
does it work when you replace the gilstate with the savethread api?
I don't think we are consistent in numpy about when to use what anyway, maybe we can get away with replacing it.

**Comment by ndjensen** [comment]
I would like to be able to use the PyEval_Restore/Save methods, PyEval_Acquire/Release methods, or NPY_BEGIN_ALLOW_THREADS and associated macros to take care of this.  The problem here is that we want to go in the reverse direction.  Instead of the usual behavior of releasing the GIL (allow threads), doing calculations, then reacquiring the GIL (end threads), we want to acquire the gil for the error handling, do the error handling, then release the GIL.  Put another way:

Usual code:
```c
NPY_BEGIN_THREADS;
// do stuff
NPY_END_THREADS;
```

What we need in _error_handler() is:
```c
NPY_END_THREADS;
// do stuff
NPY_BEGIN_THREADS;
```

To do the threads locking/unlocking in reverse order, we need the PyThreadState* as returned by NPY_BEGIN_THREADS (the first PyEval_SaveThread()).  That would require passing along the PyThreadState* to all the inner methods of ufunc_object.c so that when/if they call _error_handler() the PyThreadState* could be passed there for temporary locking of the GIL.  I'm not familiar enough with the internals of numpy to know the full implications of such a change and if that's a bad idea or a good idea.

**Comment by ndjensen** [comment]
Closing as overcome by events.  Jep has come up with a workaround and an alternative to using sub-interpreters with numpy.
