### ISSUE TITLE
np.dot deprecations

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#5859]
[This isn't actually a 1.10 blocker, but hopefully it will be resolved trivially before that so sticking the tag on so it doesn't get lost.]

http://thread.gmane.org/gmane.comp.python.numeric.general/60520

**Comment by charris** [comment]
IIRC, this is also implemented in the API as `PyArray_MatrixProduct2`, which we should probably leave as is.

**Comment by njsmith** [comment]
I'm not necessarily arguing, but I still don't understand why you think
deprecations should work differently for python functions and identical c
functions? There's a very substantial ongoing cost to maintaining old and
broken api functions, so I'd like at least to know what makes them
different...

**Comment by charris** [comment]
Leaving it alone is not the same as maintaining. I don't think there is much work involved, there isn't much code there, and leaving it be saves compatibility grief. The dot function is different, but over the long term I expect it to be replaced by `@`. The only thing missing from the latter is an `out` parameter, and that can be supplied by a `PyArray_MatrixProduct3` function.

**Comment by njsmith** [comment]
So, not to be annoying, but I have to point out you didn't actually answer
my question :-).

Also, I'm not at all convinced that "leaving it alone" is cheap -- there's
unique code there for handling the outer product looping, etc., and it
seems to me entirely likely that we might, say, refactor our intervals at
some point so that the way we look up the dot inner loop changes. (For
instance, we might make it a ufunc instead of making it a special case
handled through the dtype's ArrFuncs table. I guess we must have custom
type coercion code just for dot as well?) Keeping the old code working
indefinitely in spite of such changes would definitely not be free.

**Comment by charris** [comment]
The old interator handles the looping, hence the outer product bit, and inner loop is the dot (inner product) function that comes with the dtype. The function doesn't use any of the ufunc machinery. There isn't much code there, the cblas heavy lifting, which is common to the unstacked cases, is separate and called from the function. If you are worried about maintenance, we can deprecate the function if is ever becomes a burden.

As to not deprecating C-API functions, I think there is substantially more burden in maintaining c extensions using numpy code than there is for python code. There are currently some deprecated API functions, but they haven't been removed, they just call their replacement functions.

**Comment by njsmith** [comment]
> If you are worried about maintenance, we can deprecate the function if is
ever becomes a burden.

My suggestion here is that we immediately deprecate the rarely-used part of
the function that we anticipate might become a burden. That doesn't force
us to remove it, it just means that if it does become a maintenance burden
then at that point we'll have more options beyond starting a big year-long
deprecation dance, and in the mean time users get some useful usage
guidance.

(And generally speaking, the strategy of deprecating the specific
problematic cases is much better than the strategy of deprecating the whole
function -- the vast majority of code that uses this function is just using
1d and 2d arrays, which are fine, and there's no reason they should have to
waste time switching APIs.)

(Also FTR I have no problem with carrying around api functions that are no
longer optimal but easy to keep supporting -- some of those deprecated
functions are just single-line bodies, void dostuff() {
dostuff_ex(flags=0); }, right? That's no big deal.)

**Comment by jakirkham** [comment]
At present, I am not worried about point 1. Honestly, `dot` to me is all about working with a BLAS easily and a BLAS only really makes sense in the rank 0 to 2 cases.

As for point 2 (working with scalars), these cases are actually pushed through the BLAS used. This can be nice if threading is enabled on the BLAS allowing a handy speedup on a common operation. So, as a user, I have mixed feelings about this one.

As a contributor, I'd like to refactor code used by `dot` and `inner` into a more common code base as they seem to use much of the same stuff. This allows some handy optimizations to be shared and cuts down the code duplication. In the documentation, `inner` actually promises to do multiplication with scalars. This turns out to be handled at a really low-level (i.e. `cblas_innerproduct`). Now `cblas_innerproduct` can basically be replaced by a transpose and a call to `cblas_matrixproduct`, but with this deprecation proposed that wouldn't be possible. Instead, we would have two keep these two copies of code that are nearly the same separate as we deprecate small portions of one. That doesn't make sense to me. Instead, let's cut one of them out of the picture almost entirely by refactoring and cut down the C maintenance burden.

**Comment by njsmith** [comment]
Oh right, should update this: the `dot` deprecations turned out to be very controversial at the numpy bof we had a scipy in July 2015. I'm not sure whether that means it's just a bad idea, or just needs more discussion to assuage people's concerns, but either way it isn't something to move ahead on immediately.

**Comment by jakirkham** [comment]
Ok, thanks for clarifying. The blockers milestone scared me. ;)

**Comment by njsmith** [comment]
@jarackham: right, let me fill in some background :-). First: saying that you don't care about how dot works on >2d arrays because the BLAS works on 2d matrices is like saying you don't care how np.log works on 1d arrays because the log function in libm only works on scalars :-). The whole idea in numpy is to make it easy and convenient to do the apply operation many times to a stack of objects, and that's true regardless of whether we're talking about a stack of scalars or a stack of matrices. The `@` operator is vectorised in the same way as np.log and every other ufunc: if you give it a high dimensional argument it loops over the extra dimensions, and if you give it multiple high dimensional arguments then it broadcasts them, then aligns them and loops in parallel. The `dot` function does something different and not as nice. In any case we have to support both semantics, at least for a while. Part of the motivation for these proposed deprecations is/was to maybe eventually be able to remove the code duplication between `@` and `
dot`.

Probably if we do ever go through with these deprecations to `dot` then we should also apply the same deprecations to inner, tensordot, etc. That's a good point.

I'm not so excited about the idea that we should preserve `dot(scalar, array)` because of speed. There's a much much more obvious way to write this (`scalar * array`) that nearly everyone uses in practice. If the obvious way is really that slow, we should make it faster, not provide an obvious but slow option and an obscure but fast option.

In the mean time, any place we can merge two pieces of functionality it's almost certainly a good idea :-). We can always rearrange again later if we change our minds, and at least then we'll be starting from a smaller/simpler codebase.

It's also often the case that one can simplify code by factoring out common functionality, by making an internal function that does most of the hard shared work, and then having two different small pieces of interface code on top of it. So e.g. even though `dot` and `@` have different ideas about how to loop over high dimensional arrays, they could both call into the same code to do the actual matrix multiplies. (Right now IIRC they don't share any code at all... `@` is np.matmul and I think goes via einsum, so doesn't take advantage of the BLAS. You perhaps start to see why we are eager for folks to go in with a hatchet and refactor boldly :-). While there are strong constraints on what we can change about user-visible APIs, for everything else there's really no need to carefully respect how things used to be done or try to preserve them.)

**Comment by jakirkham** [comment]
The only reason I said I wasn't too worried about what happened with `dot` and higher dimensions is I wasn't wanting to dive into that discussion now. That being said, I think the example that you picked isn't quite fair. A function that takes a scalar and returns a scalar is something that one would have pretty obvious expectations about how it would generalize to ND arrays. On the other hand, generalizing matrix multiplication to tensors can be done in a variety of ways and all offer something that's a little different. Hence, why I wasn't wanting to leap into that discussion and still am not.

You're right that the simple way of doing this `scalar * array` should be fast. How is this done currently?

FTR, I am not saying `scalar * array` should be slow and `dot(scalar, array)` should be fast. What I am saying is `dot(scalar, array)` should be present and that it should proceed through the BLAS as it does. Perhaps, `scalar * array` should too. Working with a BLAS can be challenging, the fact that `dot` makes this so trivial is an awesome feature about NumPy so I feel strongly that this should remain as a BLAS interface. Though even this is a bit of tangent.

> In the mean time, any place we can merge two pieces of functionality it's almost certainly a good idea :-). We can always rearrange again later if we change our minds, and at least then we'll be starting from a smaller/simpler codebase.

This was the main point I was actually worried about. Hearing you say this is reassuring.

**Comment by njsmith** [comment]
Regarding high-dimensional arrays: sure, that's fair. I think when you get a chance to look you'll find that `@` does "the one right thing" (i.e. uses the same rules as numpy scalar functions as well as other numpy stacked array functions -- try e.g. applying np.linalg.inv on an array with shape `(n, m, m)`), and `dot` does not :-).

Regarding `scalar * array`: this calls the `np.multiply` ufunc, which eventually ends up in a templated [inner loop in umath/loops.c.src](https://github.com/numpy/numpy/blob/8a76291c76aa9b33b18ceb06f6e8f37f990c9e27/numpy/core/src/umath/loops.c.src#L1495). You'll notice that if possible it will use a SIMD implementation (from umath/simd.inc.src -- currently seems to be SSE2 only), so it's likely to already be competitive with BLAS kernels in many cases. The loop there handles the general case of `strided array * strided array` (which `scalar * array` is a special case of -- by the time we reach this point, the scalar has been broadcast to become an array with strides=0). So just like in the matrix product code we have the option of looking at the memory layout and detecting the special case that BLAS can handle and dispatching to BLAS, here we could if it's worthwhile detect the special strides and call SCAL or AXPY or whateever the appropriate BLAS kernel is.

Also FTR, my objection isn't to providing a nice interface to BLAS `scalar * array`; my objection is to spelling that as `dot(scalar, array)`. Aside from being totally confusing (`dot` on scalars implements a different operation than `dot` on arrays), the main effect of doing it this way is just to ensure that almost no-one knows about it, which rather defeats the purpose :-). If BLAS `scalar * array` is worth having, then it's worth optimizing the regular `scalar * array` spelling to use it, or providing a dedicated findable function.

**Comment by jakirkham** [comment]
I'll definitely play around with `@` on higher dimensional arrays at some point. Thanks for the pointers.

That's cool. Thanks for clarifying on how `s * a` works. I am sure you guys have put a lot of work into making this efficient.

Not that I was thinking it needed to be any faster, but I was curious so I tried running some `timeit` tests with `s * a` vs `dot(s, a)` (using OpenBLAS 0.2.15). For various arrays `s * a` is faster, but not by lots they are both close. Only when the arrays get really big ~100,000 the difference becomes basically negligible with `dot(s, a)` maybe being the tiniest bit faster, but its too close to say or probably matter. This was with a single thread. On a side note, I also tried BLAS operations from SciPy and found them to be 2 or 3 times slower than either, which was a bit disconcerting. Enabling different fixed numbers of threads doesn't seem to effect the result for OpenBLAS and may even hurt it. In short, using a BLAS might actually hurt performance for `s * a` and doesn't seem to help in any event.

**Comment by mattip** [comment]
While I think this issue can be closed, the last paragraph is relevant for my work on matmul in #11133. `matmul` and `dot` both do {create output, zero output, call `blas_saxy`} where the naive loop does {create output, loop} with no zeroing needed. 

For smaller arrays, another factor may be the iterator setup time in `dot` and `matmul`.

**Comment by eric-wieser** [comment]
Gmane link seems dead to me, but it's possibly transient

**Comment by bsipocz** [comment]
Reading through the thread about the bof discussion, and the multiple comments/label that this can be closed I go ahead and close the issue. Please reopen if you think the topic needs to be revisited.
