### ISSUE TITLE
creating an array from a Pillow 1-bit image object results in junk data.

### ISSUE THREAD

**Issue by LimEJET** [numpy/numpy#5861]
Python 3.4.2 Windows 64 bit
NumPy 1.9.2
pillow  2.8.1

When `numpy.array` is called on an 1-bit Pillow image, the resulting array is filled with junk data and does not correctly represent the image object it should contain.

I've tested this with a small image and a large image.

Small image (3x3):
![test](https://cloud.githubusercontent.com/assets/4407285/7554999/853ef4c2-f73d-11e4-9747-2e9c79190344.png)

Pillow represents it like this:
```python
>>> i = Image.open("test.png")
>>> for k in i.convert("1").getdata(): print(k)
0
255
0
255
0
255
0
255
0
```
while the resulting numpy array varies in how it looks:
```python
>>> p = np.array(i.convert("1"))
>>> p
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]], dtype=bool)
>>> i = Image.open("test.png")
>>> p = np.array(i.convert("1"))
>>> p
array([[ True,  True,  True],
       [False, False, False],
       [False, False,  True]], dtype=bool)
```

I tried this out on a bigger image (represented below), and I saw some interesting patterns in the output.

The code I tested with:
```python
i = Image.open("a.png")
i.show()
p = numpy.array(i.convert("1")) # gives boolean array
j = Image.fromarray(numpy.uint8(p)*255)
j.show()
```
Input image:
![2015-05-10_17-50-18](https://cloud.githubusercontent.com/assets/4407285/7554994/1031077e-f73d-11e4-9923-f07bf9117c4e.png)

Output image:
![2015-05-10_17-48-37](https://cloud.githubusercontent.com/assets/4407285/7554995/121907da-f73d-11e4-8e1f-f574fba57567.png)

Notice the row of miniaturized versions of the input along the top.

**Comment by seberg** [comment]
Numpy does not support bit arrays. So this is impossible the dtype `"|b1"` that Pillow/PIL uses for bit arrays is interpreted as "bool" which is still one byte size.
Since we do not support bit level arrays, pillow should probably just not provide an array interface or maybe provide an invalid one to error out.
Otherwise, Pillow might create a valid boolean (1-byte) array maybe for the array interface, or when `__array__` is called.

**Comment by LimEJET** [comment]
The data representation of the small image is, according to pillow, series of `0x00`s and `0xFF`s. Wouldn't that make the result a byte array?

**Comment by seberg** [comment]
Not after that `i.i.convert("1")` whatever it does.

```
In [13]: i.convert('1').__array_interface__
Out[13]: {'data': '@\xa0@', 'shape': (3, 3), 'typestr': '|b1'}
```

Or in other words:
```
In [38]: i = Image.open("test.png")

In [39]: np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)
Out[39]: array([ 64, 160,  64], dtype=uint8)

In [40]: i = Image.open("test.png")

In [41]: arr = np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)

In [42]: np.unpackbits(arr).reshape(3, -1)
Out[42]: 
array([[0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]], dtype=uint8)
```

Frankly, I have no clue why, but I would say the error here is in Pillow (whatever the correct solution is). Numpy does not support bit arrays, so I believe this is something Pillow/PIL must fix by not exposing a wrong array interface.

**Comment by seberg** [comment]
Not after that `i.i.convert("1")` whatever it does.

```
In [13]: i.convert('1').__array_interface__
Out[13]: {'data': '@\xa0@', 'shape': (3, 3), 'typestr': '|b1'}
```

Or in other words:
```
In [38]: i = Image.open("test.png")

In [39]: np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)
Out[39]: array([ 64, 160,  64], dtype=uint8)

In [40]: i = Image.open("test.png")

In [41]: arr = np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)

In [42]: np.unpackbits(arr).reshape(3, -1)
Out[42]: 
array([[0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]], dtype=uint8)
```

Frankly, I have no clue why, but I would say the error here is in Pillow (whatever the correct solution is). Numpy does not support bit arrays, so I believe this is something Pillow/PIL must fix by not exposing a wrong array interface.

**Comment by seberg** [comment]
Not after that `i.i.convert("1")` whatever it does.

```
In [13]: i.convert('1').__array_interface__
Out[13]: {'data': '@\xa0@', 'shape': (3, 3), 'typestr': '|b1'}
```

Or in other words:
```
In [38]: i = Image.open("test.png")

In [39]: np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)
Out[39]: array([ 64, 160,  64], dtype=uint8)

In [40]: i = Image.open("test.png")

In [41]: arr = np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)

In [42]: np.unpackbits(arr).reshape(3, -1)
Out[42]: 
array([[0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]], dtype=uint8)
```

Frankly, I have no clue why, but I would say the error here is in Pillow (whatever the correct solution is). Numpy does not support bit arrays, so I believe this is something Pillow/PIL must fix by not exposing a wrong array interface.

**Comment by seberg** [comment]
Not after that `i.i.convert("1")` whatever it does.

```
In [13]: i.convert('1').__array_interface__
Out[13]: {'data': '@\xa0@', 'shape': (3, 3), 'typestr': '|b1'}
```

Or in other words:
```
In [38]: i = Image.open("test.png")

In [39]: np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)
Out[39]: array([ 64, 160,  64], dtype=uint8)

In [40]: i = Image.open("test.png")

In [41]: arr = np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)

In [42]: np.unpackbits(arr).reshape(3, -1)
Out[42]: 
array([[0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]], dtype=uint8)
```

Frankly, I have no clue why, but I would say the error here is in Pillow (whatever the correct solution is). Numpy does not support bit arrays, so I believe this is something Pillow/PIL must fix by not exposing a wrong array interface.

**Comment by seberg** [comment]
Not after that `i.i.convert("1")` whatever it does.

```
In [13]: i.convert('1').__array_interface__
Out[13]: {'data': '@\xa0@', 'shape': (3, 3), 'typestr': '|b1'}
```

Or in other words:
```
In [38]: i = Image.open("test.png")

In [39]: np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)
Out[39]: array([ 64, 160,  64], dtype=uint8)

In [40]: i = Image.open("test.png")

In [41]: arr = np.fromstring(i.convert('1').__array_interface__['data'], dtype=np.uint8)

In [42]: np.unpackbits(arr).reshape(3, -1)
Out[42]: 
array([[0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]], dtype=uint8)
```

Frankly, I have no clue why, but I would say the error here is in Pillow (whatever the correct solution is). Numpy does not support bit arrays, so I believe this is something Pillow/PIL must fix by not exposing a wrong array interface.

**Comment by seberg** [comment]
oops, sorry for the repeats, browser did not react or other funny things.

**Comment by charris** [comment]
@seberg Good to know. I thought someone had invented an invisible ink font ;)

**Comment by LimEJET** [comment]
@seberg Alrighty then, better post this over on their repo as well.

**Comment by njsmith** [comment]
To be fair, I don't know if "b1" is an accurate description of what they're
providing or even if it should count as a valid buffer data type, but part
of the problem is that NumPy should realize that "b1" is not something it
understands instead of silently pretending that it said "b8". We're in the
middle of fixing this in fact, iirc.
