### ISSUE TITLE
vectorize fails for zero-dimensioned arrays

### ISSUE THREAD

**Issue by jordigh** [numpy/numpy#5868]
The following used to work and return an empty 5 by 0 array.

```python
np.vectorize(lambda x: x+1)(np.zeros([5,0]))
```

Now it stack traces:

```
/usr/lib/python2.7/dist-packages/numpy/lib/function_base.pyc in __call__(self, *args, **kwargs)
   1571             vargs.extend([kwargs[_n] for _n in names])
   1572 
-> 1573         return self._vectorize_call(func=func, args=vargs)
   1574 
   1575     def _get_ufunc_and_otypes(self, func, args):

/usr/lib/python2.7/dist-packages/numpy/lib/function_base.pyc in _vectorize_call(self, func, args)
   1631             _res = func()
   1632         else:
-> 1633             ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
   1634 
   1635             # Convert args to object arrays first

/usr/lib/python2.7/dist-packages/numpy/lib/function_base.pyc in _get_ufunc_and_otypes(self, func, args)
   1594             # Assumes that ufunc first evaluates the 0th elements in the input
   1595             # arrays (the input values are not checked to ensure this)
-> 1596             inputs = [asarray(_a).flat[0] for _a in args]
   1597             outputs = func(*inputs)
   1598 

IndexError: index 0 is out of bounds for axis 0 with size 0
> /usr/lib/python2.7/dist-packages/numpy/lib/function_base.py(1596)_get_ufunc_and_otypes()
   1595             # arrays (the input values are not checked to ensure this)
-> 1596             inputs = [asarray(_a).flat[0] for _a in args]
   1597             outputs = func(*inputs)
```

Seems to me that there should first be a check for empty arrays before attempting to see the return types of the function?

**Comment by jaimefrio** [comment]
The relevant source code lines were last modified over 3 years ago in [this](https://github.com/numpy/numpy/commit/127ae2f54d2c96fc7318fe12a3e2009e517828d1) commit. When (in what version) did this "use to work"?

**Comment by jordigh** [comment]
This worked in numpy 1.6

I hope you are not implying that breaking what used to work is desirable behaviour just because version 1.6 is 3 years old.

**Comment by seberg** [comment]
Sure, this would be better to work again if possible (even if I don't like vectorize much ;)). The code seems only for output type detection (which may indeed be tricky with empty arguments).

So the workaround is:
```
np.vectorize(lambda x: x+1, otypes=[np.float64])(np.zeros([5,0]))
```

**Comment by jordigh** [comment]
A possible fix could be to use a default-constructed element (e.g. _a.dtype.type()) and see what _func does with it. This would not require _a to have any elements, but it could potentially break if attempted on a nonempty _a.

```diff
diff --git a/numpy/lib/function_base.py b/numpy/lib/function_base.py
--- a/numpy/lib/function_base.py
+++ b/numpy/lib/function_base.py
@@ -1773,7 +1773,13 @@ class vectorize(object):
             # the subsequent call when the ufunc is evaluated.
             # Assumes that ufunc first evaluates the 0th elements in the input
             # arrays (the input values are not checked to ensure this)
-            inputs = [asarray(_a).flat[0] for _a in args]
+            #
+            # If there are empty arrays, we instead use a
+            # default-constructed element of the input empty input
+            # type.
+            arrinputs = [asarray(_a) for _a in args]
+            inputs = [_a.flat[0] if _a.size else _a.dtype.type()
+                      for _a in arrinputs]
             outputs = func(*inputs)
 
             # Performance note: profiling indicates that -- for simple
```

**Comment by jaimefrio** [comment]
No, of course unintentionally breaking things that work is rarely, if ever, OK. But that an issue takes 3 years to surface does help triage a 700+ issue list...

But getting back to `np.vectorize`, I think you proposed solution would end up doing something like:

```
>>> np.int + 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'type' and 'int'
```

or am I reading it wrong?

Actually, it seems to me it didn't really worked in 1.6, even if it did not raise an error: `np.vectorize` needs to figure out what the dtype of its return array should be, and to do so it calls the provided python function on its first input... But if the array is zero-sized there's nothing to pass in, and no return to check.

With "on the face of ambiguity, refuse the temptation to choose" in mind, raising an error seems like a very sensible option. It could probably use a more informative one, including a hint that, if you need it to work on empty arrays, the return type should be explicitly specified, as @seberg has demonstrated.

**Comment by jordigh** [comment]
> Actually, it seems to me it didn't really worked in 1.6, even if it did not raise an error

I can't easily check on numpy 1.6 now because it's gone with my OS upgrade. But whatever it did was better than stack tracing. I am guessing the type might have been irrelevant because it was for an empty array, so there were no elements whose type could have clashed with whatever other thing I was doing.

> or am I reading it wrong?

I think so. I did not mean np.int, but rather np.int(). Note the function call.

> if you need it to work on empty arrays, the return type should be explicitly specified, as @seberg has demonstrated.

This is not the best way to handle empty arrays, because I don't know a priori if I need it to work on empty arrays or not. I am guessing you are familiar with [the following](ftp.cs.wisc.edu/Approx/empty.pdf)? The Matlab folks long ago figured that handing empty arrays transparently is a very useful and natural thing to do. This is especially important in light of boolean indexing, which can produce empty arrays at any time.

The special-casing you suggest would effectively mean that np.vectorize would always have to be called with the type of the output argument, which seems like an undue burden upon the caller. An alternative could be to assume that the output type is NoneType and only change this default if there is anything to change it to.

**Comment by jordigh** [comment]
> The Matlab folks

Lest my comment be ignored because we all hate Matlab, let me say it this way instead: Carl de Boor, the guy whose splines you might have heard of, thinks we should treat empty arrays consistently.

**Comment by njsmith** [comment]
You're being a bit aggressive and fighty here. Do you think you could make
an effort to dial that down a little and assume good faith? We're all on
the same side etc.
.
NumPy does handle empty arrays consistently. And part of that consistency
is that it keeps track of, and cares about, the type of the elements that
would be in the array if they were present -- empty arrays have a dtype
just like any other array. What we're worrying about is that we don't want
np.vectorize to be creating functions where, e.g., they always return an
array of strings except sometimes (for an empty input) they return an array
of floats. That would be, well, inconsistent :-). And the only way to avoid
it AFAICT is to add arguments to vectorize that tell it what types this
function works with. (This might be a good idea in any case, e.g. if you
want floats as input you could say so and then let the ufunc machinery do
error checking and casting.)

**Comment by jordigh** [comment]
> You're being a bit aggressive and fighty here. 

Sorry. This is not my first time running into numpy bugs with empty arrays, and being told that I should check functions calls to make sure I'm not passing it an empty array is very frustrating. I'll try to be nicer. Let me know if I fail at being nicer.

I really value what you are doing, and I hope we can all make numpy better.

> And the only way to avoid it AFAICT is to add arguments to vectorize that tell it what types this
function works with. 

A user could just say the dtype is one thing but their function be returning a different type. So the only real way to avoid this is static type declarations. Since we're not going to get those except optionally in Python 3.5, the next best thing is to call the function on default arguments and hope the function to be vectorised is returning the same type regardless of inputs. Or maybe we could introduce a new numpy type for empty arrays?

**Comment by argriffing** [comment]
@jordigh I've opened PR https://github.com/numpy/numpy/pull/5880 that applies your patch.

**Comment by shoyer** [comment]
I added handling for size 0 inputs (basically, just a better error message) in https://github.com/numpy/numpy/pull/8054
