### ISSUE TITLE
Inconsistency for indexing multidimensional array

### ISSUE THREAD

**Issue by sunqm** [numpy/numpy#5871]
I noticed the implicit transpose when index multidimensional array.

>>> a = numpy.zeros((5,6,7,8))
>>> a[1,:,numpy.arange(3)].shape
(3, 6, 8)
>>> a[1][:,numpy.arange(3)].shape
(6, 3, 8)
>>> a[1,:,:,numpy.arange(3)].shape
(3, 6, 7)
>>> a[1][:,:,numpy.arange(3)].shape
(6, 7, 3)

But h5py and pytable do not imply this rule (and I feel that's a natural way to indexing subarray).   What's the rules of the transpose for subarray?

This problem is in numpy 1.6, 1.8, and I didn't check numpy 1.9.

**Comment by jaimefrio** [comment]
On Tue, May 12, 2015 at 12:43 PM, Qiming Sun <notifications@github.com>
wrote:

> I noticed the implicit transpose when index multidimensional array.
>
>  a = numpy.zeros((5,6,7,8))
> a[1,:,numpy.arange(3)].shape
> (3, 6, 8)
> a[1][:,numpy.arange(3)].shape
> (6, 3, 8)
> a[1,:,:,numpy.arange(3)].shape
> (3, 6, 7)
> a[1][:,:,numpy.arange(3)].shape
> (6, 7, 3)
>
>  But h5py and pytable do not imply this rule (and I feel that's a natural
> way to indexing subarray). What's the rules of the transpose for subarray?
>
> This problem is in numpy 1.6, 1.8, and I didn't check numpy 1.9.
>
It's everywhere. There was a recent discussion on the list regarding this
behavior, see starting here
<http://thread.gmane.org/gmane.comp.python.numeric.general/60239>.

Jaime

-- 
(\__/)
( O.o)
( > <) Este es Conejo. Copia a Conejo en tu firma y ayúdale en sus planes
de dominación mundial.

**Comment by pv** [comment]
See the documentation
https://docs.scipy.org/doc/numpy-dev/reference/arrays.indexing.html

**Comment by ZackHodari** [comment]
More specifically [combining-advanced-and-basic-indexing ](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#combining-advanced-and-basic-indexing)

> The easiest way to understand the situation may be to think in terms of the result shape. There are two parts to the indexing operation, the subspace defined by the basic indexing (excluding integers) and the subspace from the advanced indexing part. Two cases of index combination need to be distinguished:
> 
> - The advanced indexes are separated by a slice, Ellipsis or newaxis. For example `x[arr1, :, arr2]`.
> - The advanced indexes are all next to each other. For example `x[..., arr1, arr2, :]` but not `x[arr1, :, 1]` since `1` is an advanced index in this regard.
>
> In the first case, the dimensions resulting from the advanced indexing operation come first in the result array, and the subspace dimensions after that. In the second case, the dimensions from the advanced indexing operations are inserted into the result array at the same spot as they were in the initial array (the latter logic is what makes simple advanced indexing behave just like slicing).


And the comment in [detailed-notes](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#detailed-notes) may also be related

> The memory layout of an advanced indexing result is optimized for each indexing operation and no particular memory order can be assumed.
