### ISSUE TITLE
f2py - fix - extended common block

### ISSUE THREAD

**Issue by 2sn** [numpy/numpy#5876]
I try to include a common f77 block from legacy code.  
There once can continue a common block with a new common statement with the same common block name.  In crackfortran.py there is statement that (wrongly) explicitly catches this case.  That should be removed/reverted.

Example
      common/namecom/ namezone(nzonei+nzonec+nzoneb), names(nsubz)
      common/namecom/ unitzone(nzonei+nzonec+nzoneb)
[...hundreds more such lines...]
doing this all with just line continuation is not an option, there is too many of them hence compilers have overflowed in the past (beyond some 20 lines).

The patch, based on numpy 1.9.2, is

```
~/Python/lib/python3.4/site-packages/numpy/f2py>diff crackfortran.py_old crackfortran.py
1163,1166c1163,1164
<             if c[0] in commonkey:
<                 outmess('analyzeline: previously defined common block encountered. Skipping.\n')
<                 continue
<             commonkey[c[0]]=[]
---
>             if c[0] not in commonkey:
>                 commonkey[c[0]]=[]
```
Can you please include this patch in future versions of f2py?

**Comment by 2sn** [comment]
if you think this enhancement is reasonable (there was explicit code denying this compatibility and I do not know the background for it, but for my code it seemed to work and I did not see any reason why it logically should not work...) I am happy to try compiling a pull request for the fix.

**Comment by 2sn** [comment]
added pull request #6306

**Comment by charris** [comment]
@2sn, @pearu How exactly do you trigger this? For instance, the following test works fine
```
class TestF77Common(util.F2PyTest):

    def test_multiple_named_common(self):
        self.module.set0(1, 2)
        res = self.module.check0()
        print(res)
        #assert_(res == 3)

    code = """
       subroutine set0(ain, bin)
         real ain, bin, a, b
         common /foo/ a
         common /foo/ b
         save /foo/

         a = ain
         b = bin
       end

       function check0()
         real a, b
         common /foo/ a
         common /foo/ b
         save /foo/
         check0 = a + b
       end
   """
```
So I assume that the code isn't being run through the parser in the same way you are doing.

**Comment by charris** [comment]
The generated signature file is incorrect, but `f2py -h -m fortranfile.f` generates a working module. Hmm...

**Comment by charris** [comment]
There don't appear to be any current tests for signatures.

**Comment by pearu** [comment]
I agree with the patch.

I don't understand the comment "The generated signature file is incorrect, but f2py -c -m fortranfile.f generates a working module.":
1. Call `f2py -c -m fortranfile.f ` is wrong. Use `f2py -c -m foo fortranfile.f `
2. The generated signature file is contains two common /foo/ definitions in the two functions. This is correct. What part of the signature file is incorrect?

**Comment by charris** [comment]
@pearu f2py -h applied to

```
       subroutine set0(ain, bin)
         real ain, bin, a, b
         common /foo/ a
         common /foo/ b
         save /foo/

         a = ain
         b = bin
       end

       function check0()
         real a, b
         common /foo/ a
         common /foo/ b
         save /foo/
         check0 = a + b
       end
```

produces

```
!    -*- f90 -*-
! Note: the context of this file is case sensitive.

subroutine set0(ain,bin) ! in testf77.f90
    real :: ain
    real :: bin
    real :: a
    common /foo/ a
end subroutine set0
function check0() ! in testf77.f90
    real :: a
    real :: check0
    common /foo/ a
end function check0

! This file was auto-generated with f2py (version:2).
! See http://cens.ioc.ee/projects/f2py2e/

```

**Comment by charris** [comment]
Yes, a working module results and tests pass. That is not unexpected, as the fortran code itself does not have a problem and the interface is not affected.

**Comment by pearu** [comment]
Yes, f2py without the patch produces incorrect `common /foo/ a`. With the patch, the result is
```
$ f2py -m foo fortranfile.f -h stdout
Reading fortran codes...
	Reading file 'fortranfile.f' (format:fix,strict)
Post-processing...
	Block: foo
			Block: set0
			Block: check0
Post-processing (stage 2)...
Saving signatures to file "./stdout"
!    -*- f90 -*-
! Note: the context of this file is case sensitive.

python module foo ! in 
    interface  ! in :foo
        subroutine set0(ain,bin) ! in :foo:fortranfile.f
            real :: ain
            real :: bin
            real :: a
            real :: b
            common /foo/ a,b
        end subroutine set0
        function check0() ! in :foo:fortranfile.f
            real :: a
            real :: b
            real :: check0
            common /foo/ a,b
        end function check0
    end interface 
end python module foo

! This file was auto-generated with f2py (version:2).
! See http://cens.ioc.ee/projects/f2py2e/
```

**Comment by charris** [comment]
I was afraid of that, I don't think it is quite right yet. The point of having separate `common` statements in the original code was that some fortran compilers could not support the number of continuation lines needed, and in this case, a continuation may not even be generated (need to check that). Why do the common statements need to be in the pyf files?

**Comment by pearu** [comment]
Only compilers need separate `common` statements in Fortran sources. Signature files are consumed by f2py, not by Fortran compilers. So, it is ok to have a single `common` statement in the signature file. The single `common` statement and the separate `common` statements are equivalent.

Common statements need to be in pyf files because f2py uses these as an input to construct wrappers to common blocks. In case you didn't know then one can access (read&write) the common block data from Python.

In case one does not need to access common block data from Python, one can remove the common block statements from the signature files. But this the decision of f2py user.

But you are right, the issue is not quite resolved yet. Namely, f2py generates some wrapper functions in Fortran (see the generated file `foo-f2pywrappers.f` when using command `f2py -m foo fortranfile.f`) and there the common blocks are still represented with single `common` statement.

**Comment by 2sn** [comment]
In my case there seemed to be no issue with gfortran compiling the single common statement generated, but at least with some other and historic *Fortran* compilers this caused problems, as well as with the structure of the code that defines members to the same common block in a non-consecutive order, i,.e.,

```fortran
common /a/ a1, a2
common /b/ b1, b2
common /a/ a3, a4
common /b/ b3, b4
```

I assume at this point you have not push my fix to the main branch, though it would fix some of the problems - at least mine - and not break anything (!).  If that is not good enough, one solution I could suggest is to just disassemble the common block in individual common statements for each variable in the code generated, i.e.,

```fortran
common /a/ a1
common /a/ a2
common /a/ a3
common /a/ a4
common /b/ b1
common /b/ b2
common /b/ b3
common /b/ b4
```

as it does (now) not break anything, or at least group in modest numbers, say, a dozen, or to 72 char line widths where possible?

1) would this be a solution/resolution?
2) can you add this?  Or if I need to do this (but it will take me a long time) does a new patch be based on the current master?
3) I still think it would be great to add what is there now to master already.

-Alexander

**Comment by charris** [comment]
Both your PRs have been merged in master and 1.10.x. See #6487 and #6488. I cleaned them up a bit.

**Comment by 2sn** [comment]
Dear Charles,

Thanks.  I after some search I could find it; still sort of new using
bitbucket, needed to pull from upstream to see all changes, not master
which just pointed to my branch from Oct 10.  Thanks a lot.  Should there
still be a fix for creating unrolled common blocks for the interface code?

-Alexander

**Comment by charris** [comment]
Sure, although I don't think it pressing enough to shoot for 1.10. Note that in supporting old compilers we need to draw the line somewhere, else things get overly complicated. I'm not familiar with the Fortran landscape these days, so don't know which compilers really count.

**Comment by 2sn** [comment]
Dear Charles,

I agree there is no need at this point to change the f2py/crackfortran code
for the interface code creation as current gfortran is happy with the code
it generates even from extended common blocks.  I will do some tests on the
long fortran common block created - whether I can access the items at the
end of the block; for the current fix that was submitted, the use case is
clear: the split common block definitions that is legal in Fortran - legal
Fortran code should compile.

attached the pyf it creates for my case for your enjoyment

I still do get some error message from crackfortram that I need to
understand and that seem to be related to the interface code created (as it
is the last output before it actually makes the .so file it must be related
to the interface file it creates.

analyzevars: charselector={'len': '48'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '8'}
unhandled.analyzevars: charselector={'len': '48'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '33'}
unhandled.analyzevars: charselector={'len': '8'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '8'}
unhandled.analyzevars: charselector={'len': '2'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '80'}
unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars:
charselector={'len': '80'} unhandled.analyzevars: charselector={'len': '8'}
unhandled.analyzevars: charselector={'len': '16'} unhandled.analyzevars:
charselector={'len': '10'} unhandled.analyzevars: charselector={'len': '8'}
unhandled.analyzevars: charselector={'len': '48'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '8'}
unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '8'}
unhandled.analyzevars: charselector={'len': '16'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '8'}
unhandled.analyzevars: charselector={'len': '8'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '8'}
unhandled.analyzevars: charselector={'len': '256'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '16'}
unhandled.analyzevars: charselector={'len': '8'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '10'}
unhandled.analyzevars: charselector={'len': '10'} unhandled.analyzevars:
charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '1'}
unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars:
charselector={'len': '80'} unhandled.analyzevars: charselector={'len':
'80'} unhandled.


-Alexander
