### ISSUE TITLE
stdout suppression in tests

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5891]
At least one of the tests closes `sys.stdout`
https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/lib/tests/test_regression.py#L171
but according to
https://github.com/numpy/numpy/commit/3fd6b62c1db915
closing `sys.stdout` won't close it.

I'm not sure what is the best way to fix it.  This issue arose in review of a scipy PR https://github.com/scipy/scipy/pull/4805 which had copied this pattern from numpy.

**Comment by rgommers** [comment]
Recommendation from the Python FAQ: https://docs.python.org/3/faq/library.html#why-doesn-t-closing-sys-stdout-stdin-stderr-really-close-it

**Comment by njsmith** [comment]
I *think* that there are two things getting conflated here -- the file
object representing the OS's stdout descriptor, which is initially provided
under the name "sys.stdout", and the line of code " sys.stdout.close()".
What doesnt work is closing the real stdout file, even if you've got a
reference to it under a different name. OTOH doing sys.stdout.close()
should work fine if you've assigned some regular non-magical file object to
the name sys.stdout.

**Comment by argriffing** [comment]
From the recommendation:

> But stdin, stdout and stderr are treated specially by Python, because of the special status also given to them by C. Running sys.stdout.close() marks the Python-level file object as being closed, but does not close the associated C file descriptor.
To close the underlying C file descriptor for one of these three, you should first be sure that’s what you really want to do

But from @njsmith's comment, I think this is not what we really want to do.  In other words, we don't want to actually close the underlying C file descriptor for stdout.

I'll close this issue, but suggestions for improving this pattern would be welcome.
