### ISSUE TITLE
Segfault with boolean indexing and complex arrays casting to float

### ISSUE THREAD

**Issue by jdreaver** [numpy/numpy#5896]
I am experiencing a tricky segfault right now. To trigger the segfault, assign a `complex128` array to a large zeroed `float64` array using a boolean index array. Here is a program the reproduces the behavior:

```python
import numpy as np

# Setup the boolean index and float arrays
shape = (8, 63)
bool_index = np.zeros(shape).astype(bool)
bool_index[0, 1] = True
zero_array = np.zeros(shape)

# Assigning float is fine
zero_array[bool_index] = np.array([1])
assert zero_array[0, 1] == 1

# Fancy indexing works, although we get a cast warning
zero_array[[0], [1]] = np.array([2 + 1j])
assert zero_array[0, 1] == 2  # No complex part

# Segfault caused here with complex array and boolean indexing
print("About to segfault")
zero_array[bool_index] = np.array([1j])
```

Running gives:

```
seg.py:13: ComplexWarning: Casting complex values to real discards the imaginary part
  zero_array[[0], [1]] = np.array([2 + 1j])
About to segfault
Segmentation fault (core dumped)
```

Assigning a float with the boolean index array, and assigning a complex number with fancy indexing works (although you get a `ComplexWarning` because of casting). However, assigning the complex array to the float array using the boolean indexing array causes a segfault.

Here is where it gets weird. If I set the `shape` parameter to anything less than `(8, 63)` (that is, if I make 8 smaller or 63 smaller), the segfault doesn't occur. So it seems to me that the shape of the boolean and zero arrays must have at least 8 rows and at least 63 columns for some reason.  I have no idea why this is the case, but it may be a clue for what the problem is.

The size of the complex array doesn't matter, as long as it fits in the float array, of course.

**Comment by pv** [comment]
git bisect blames 259db01274c8

**Comment by jdreaver** [comment]
I will mention that this can be fixed simply by casting your array to float *before* assigning. That's my temporary fix for my code for now:

```python
zero_array[bool_index] = np.array([1j]).astype(float)
```

Thanks for the quick response @pv!

**Comment by juliantaylor** [comment]
mh numpy/core/src/multiarray/mapping.c:1176 needs to move down a bit, dumb mistake ...

**Comment by seberg** [comment]
This had been fixed at the SciPy sprints :) (see above).
