### ISSUE TITLE
numpy.diff docstring does not match operation for nth-order differences

### ISSUE THREAD

**Issue by mcgibbon** [numpy/numpy#5900]
An [nth-order difference](http://en.wikipedia.org/wiki/Finite_difference#Higher-order_differences) refers to a difference scheme which converges to the continuous difference as the nth power of the discrete mesh size used. For n greater than 1, what numpy.diff calculates is not the nth-order finite difference, but rather a first-order forward approximation to the nth difference of the series.

<code>import numpy as np
a = np.array([3,2,1,0])
np.diff(a, n=2)
Out[65]: array([0, 0])</code>

Expected:
<code>Out[65]: array([1,1])</code>

I don't suggest changing the code to match the docstring, rather, the docstring should probably be changed. It currently reads:

Calculate the n-th order discrete difference along given axis.

The first order difference is given by out[n] = a[n+1] - a[n] along the given axis, higher order differences are calculated by using diff recursively.

Parameters: 
a : array_like
Input array
n : int, optional
The number of times values are differenced.
axis : int, optional
The axis along which the difference is taken, default is the last axis.
Returns:  
diff : ndarray
The n order differences. The shape of the output is the same as a except along axis where the dimension is smaller by n.

It should probably read:

Calculate the n-th discrete difference along given axis.

The first difference is given by out[n] = a[n+1] - a[n] along the given axis, higher differences are calculated by using diff recursively.

Parameters: 
a : array_like
Input array
n : int, optional
The number of times values are differenced.
axis : int, optional
The axis along which the difference is taken, default is the last axis.
Returns:  
diff : ndarray
The n-th differences. The shape of the output is the same as a except along axis where the dimension is smaller by n.

By removing all instances of the word "order", the docstring would no longer misleadingly use "nth-order", which traditionally refers to the rate of convergence of a differencing scheme, and not which difference is being calculated.

**Comment by to266** [comment]
Additionally, it's not clear from the docstring how the method deals with non-integer order inputs. In effect it rounds the order up:
`np.diff(anything, n=1.3)` is actually equal to `np.diff(anything, n=2)`

**Comment by mattip** [comment]
Closed by #6322
