### ISSUE TITLE
round incorrect result on int64

### ISSUE THREAD

**Issue by ericctharley** [numpy/numpy#5903]
Using python 3.4.3 / anaconda 2.1.0 64-bit on Ubuntu 14.04

NumPy version 1.9.2
Python version 3.4.3 |Anaconda 2.1.0 (64-bit)| (default, Mar  6 2015, 12:03:53) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

correct:

> > > numpy.round(1432116610123450000, -7)
> > > 1432116610120000000

incorrect:

> > > numpy.round(1432116610123450000, -6)
> > > 1432116610123000064

**Comment by ewmoore** [comment]
This happens because `round` passes through double precision on the way to its output.  `np.round(1432116610123450000, -6)` becomes 
```
(np.rint(1432116610123450000//1e6)*1e6).astype('i8')
Out[34]: 1432116610123000064
```

**Comment by ericctharley** [comment]
should round have a different path for negative arguments?
It's surprising to me to have this error show up on an integer.
>>> numpy.asarray([1432116610123450000.1] * 2).astype(int) // (10 ** 6) * (10 ** 6)
array([1432116610123000000, 1432116610123000000])
>>> numpy.asarray([1432116610123450000] * 2).astype(int) // (10 ** 6) * (10 ** 6)
array([1432116610123000000, 1432116610123000000])
Seems like something like that would generally work on arrays.  Or remove the .astype(int) if it's surprising to have an input float returned as an int.

**Comment by seberg** [comment]
Same as gh-11881, closing this one.
