### ISSUE TITLE
DOC: Return type of eig may be real 

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#5904]
The documentation for [linalg.eig](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html#numpy-linalg-eig) claims that "The resulting array will be always be of complex type."

This is not true:

```
>>> import numpy
>>> numpy.linalg.eig([[1]])[0].dtype
dtype('float64')
```

In fact, the result is always cast to real whenever imaginary part is exactly zero.

**Comment by charris** [comment]
Fixed in #6321.
