### ISSUE TITLE
Einsum produces incorrect result when casting to non-contiguous out array

### ISSUE THREAD

**Issue by charris** [numpy/numpy#5907]
Like so:
```
In [28]: out = zeros((2,2,2))[...,0]

In [29]: x = ones((2,2), float32)

In [30]: einsum('ij,jk->ik', x, x, out=out)
Out[30]: 
array([[ 2.,  0.],
       [ 2.,  0.]])
```
This seems to be an iterator problem. It works correctly in the non-casting case.

**Comment by seberg** [comment]
Oh wow, that looks bad.... Note that:
```
In [9]: out.base
Out[9]: 
array([[[ 2.,  2.],
        [ 0.,  0.]],

       [[ 2.,  2.],
        [ 0.,  0.]]])
```

**Comment by seberg** [comment]
Just to note. Poked it a bit. Not conclusive (not sure I recreated the iterator perfectly), but I think it might be einsum. Note that the incorrectly written output is not zerod, so it keeps increasing if you call einsum again. However, I think the zeroing is done on the iterator operand and especially, the output operand is *not* buffered here, the inputs are buffered, so it can't be the buffering code being wonky, we are operating on the array directly.

**Comment by charris** [comment]
The output iterator may not be created correctly, or the error message is in error. I get the following with float64 inputs and complex128 out. 
```
TypeError: Iterator operand 2 dtype could not be cast from dtype('complex128') to dtype('float64') according to the rule 'safe'
```

**Comment by charris** [comment]
NVM, I think this is in our cblas routines.

**Comment by seberg** [comment]
OK, recreated the exact iterator (to my best knowledge and debug print info). And the error seems to be in einsum and not the iterator, unless maybe the iterator reports some wrong strides which it does not actually use itself.

**Comment by seberg** [comment]
OK, I found the bug. Since I don't want to write a horde of tests right now, just the diff:

```diff
diff --git a/numpy/core/src/multiarray/einsum.c.src b/numpy/core/src/multiarray/einsum.c.src
index 5b1bb77..5d6fb70 100644
--- a/numpy/core/src/multiarray/einsum.c.src
+++ b/numpy/core/src/multiarray/einsum.c.src
@@ -1770,14 +1770,14 @@ get_sum_of_products_function(int nop, int type_num,
     }
 
     /* Check for all contiguous */
-    for (iop = 0; iop < nop; ++iop) {
+    for (iop = 0; iop < nop+1; ++iop) {
         if (fixed_strides[iop] != itemsize) {
             break;
         }
     }
 
     /* Contiguous loop */
-    if (iop == nop) {
+    if (iop == nop + 1) {
         return _allcontig_specialized_table[type_num][nop <= 3 ? nop : 0];
     }
```

(feel free to poke me in a few days about making a PR)

**Comment by charris** [comment]
Heh. Thanks for tracking that down. When you make the PR be carefule about spaces around operators ;)
