### ISSUE TITLE
documentation of limitations of random integer sampling

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5908]
According to https://github.com/numpy/numpy/issues/4085 numpy cannot sample integers larger than 32 bits on systems where `long` is 32 bits (64 bit Windows but not 64 bit Linux or Mac), causing complications like https://github.com/scipy/scipy/issues/4552 which attempts to sample the sparsity structure of a large sparse matrix.  This limitation could be documented more clearly on pages like http://docs.scipy.org/doc/numpy/reference/routines.random.html or http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html.

**Comment by njsmith** [comment]
True. It could also just be fixed... Either by making np.random use
npy_intp internally or by making the randrange type functions switch to 64
bits when the input range is too large.

**Comment by argriffing** [comment]
@njsmith Would this fix be subject to the same constraints as the 'choice' and 'dirichlet' and 'normal' improvements as in https://github.com/numpy/numpy/issues/5851#issuecomment-101702612?

**Comment by njsmith** [comment]
Technically yes, but that doesn't necessarily cause a problem. E.g. letting
randrange accept a larger range won't break any existing streams.
.
(There is also an interesting problem where I bet right now you get
different streams from the same code depending on what platform you're
on... Oops.)

**Comment by bashtage** [comment]
@njsmith This can be closed.
