### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_.multiarray) with Python 3.5 Beta

### ISSUE THREAD

**Issue by sdamashek** [numpy/numpy#5915]
There seems to be an issue with running Numpy (latest, 1.9.2) using the just-released Python 3.5 beta 1 (https://www.python.org/downloads/release/python-350b1/). Below is the issue I seem to be running into:
```
samuel@samaritan ~ % /usr/local/bin/python3.5
Python 3.5.0b1 (default, May 25 2015, 14:47:20) 
[GCC 5.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.5/site-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: dynamic module does not define module export function (PyInit_.multiarray)
>>>
```

I'm running Arch Linux 64-bit on kernel 4.0.1, and have built a fresh Python 3.5 manually (build log at http://sprunge.us/gUab). I have attempted to install numpy both through pip and manually, but both run into the same error. The manual build log is located at http://sprunge.us/UZBV.

A friend, also running Arch Linux 64-bit, has confirmed he receives the same error when using Python 3.5, and I have reproduced the issue on a Gentoo Linux 64-bit box as well. If it helps, the relevant .so file exists:
```
samuel@samaritan ~ % ls -l /usr/local/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 8788928 May 25 16:35 /usr/local/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
```

**Comment by tdsmith** [comment]
FWIW the error is identical on OS X so this probably isn't a platform-specific change.

**Comment by charris** [comment]
My money says this is a bug in the beta.  `PyInit_.multiarray` should be `PyInit_multiarray`, and I''m guessing Python is handling the `.` incorrectly. FWIW, Python 3.5.0a4 was quite buggy, the last useful release seems to have been 3.5.0a3.

**Comment by tdsmith** [comment]
Yep, error in the beta, fixed after release: https://bugs.python.org/issue24285

**Comment by charris** [comment]
@tdsmith Thanks for the follow up. Closing.
