### ISSUE TITLE
np.can_cast(127, np.int8) is False??

### ISSUE THREAD

**Issue by rlamy** [numpy/numpy#5917]
On a 32-bit Linux with Python 2.7 and numpy 1.9.2, `np.can_cast(127, np.int8)` unexpectedly returns False. Puzzlingly, it's the only value that fails (`np.can_cast(126, np.int8)` and `np.can_cast(-128, np.int8)` return True) and it only happens on 32-bit.

**Comment by eric-wieser** [comment]
Same problem on windows 10, numpy 1.14-dev, 64-bit python 3.5.0
