### ISSUE TITLE
F_CONTIGUOUS loss during array column slicing

### ISSUE THREAD

**Issue by sergii-gavrylov** [numpy/numpy#5918]
Hello, my current version of numpy is 1.9.2

```python
>>> x = np.array([[1,2,],[3,4]], order='F')
>>> x
array([[1, 2],
       [3, 4]])
>>> x.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>> y = x[:, 1, np.newaxis]
>>> y.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

It is not clear to me why I lose F_CONTIGUOUS in this case. Because of that later In my script I have a problem:
```python
AttributeError: cannot set single-segment buffer for discontiguous array
```
when I do something like this:
```python
t.data = (2 * y).data # here t is F_CONTIGUOUS
```
It seems that it is quite natural that F_CONTIGUOUS should be preserved in case I slice by column. And that is the case when one slices  more than one column
```python
>>> y = x[:, :2]
>>> y.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

I found workaround for this behaviour with reshape
```python
>>> y = np.reshape(x[:,1], (2,1), order='F')
>>> y.flags
Out[47]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```
And also in my case `y` should be a view of an array not a copy.
I would highly appreciate any clarifications about this slicing behaviour.

**Comment by charris** [comment]
Seems to be fixed in master.
```
In [7]: x = np.array([[1,2,],[3,4]], order='F')

In [8]: x[:, 1, np.newaxis].flags
Out[8]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

**Comment by argriffing** [comment]
@charris Is this a 'relaxed strides' thing?

**Comment by argriffing** [comment]
Maybe check whether [`NPY_RELAXED_STRIDES_CHECKING`](http://docs.scipy.org/doc/numpy/release.html#npy-relaxed-strides-checking) is in effect by running:
```python
>>> np.ones((10, 1), order="C").flags.f_contiguous
```

**Comment by charris** [comment]
@argriffing Not sure, but likely.

**Comment by juliantaylor** [comment]
yes its relaxed strides, without it empty axes will make arrays non-contiguous

**Comment by argriffing** [comment]
This can be closed then, as already fixed?

**Comment by juliantaylor** [comment]
I guess there is no reason to keep it open, even when we revert the relaxed strides for the release again due to the scipy issue, there is probably another issue somewhere.
