### ISSUE TITLE
numpy float multiplied by a string does not raise a TypeError

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#5919]
This illustrates the issue:

```python
>>> import numpy as np 
>>> print 'x'*np.float64(3.5)
```

The same construction using a regular python float raises a `TypeError`, as I would expect:

```python
>>> 'x'*3.5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't multiply sequence by non-int of type 'float'
```

I haven't looked very closely at the implementation of the numpy float class. Please feel free to close this issue if this is working as expected.

This is on numpy 1.9.2 and python 2.7.9

**Comment by njsmith** [comment]
```
In [1]: import warnings

In [2]: warnings.simplefilter("always")

In [3]: "x" * np.float64(3.5)
/home/njs/.user-python2.7-64bit-3/bin/ipython:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  #!/home/njs/.user-python2.7-64bit-3/bin/python
Out[3]: 'xxx'
```

We really need to do something about `DeprecationWarning`s not showing up interactively, it bites people constantly :-/

**Comment by njsmith** [comment]
(Closing b/c there should be an issue for turning that DeprecationWarning into an error at some point... though I haven't double-checked :-))

**Comment by ngoldbaum** [comment]
I agree that the way DeprecationWarnings are hidden by default makes them pretty much useless.  Thanks for clearing that up!

**Comment by jakirkham** [comment]
Interesting coming across this today. Yeah, I think I agree. Did an issue ever get opened or confirmed for this?
