### ISSUE TITLE
Indicial-notation wrapper for numpy.einsum?

### ISSUE THREAD

**Issue by BenFrantzDale** [numpy/numpy#5926]
Would it be interesting to have a wrapper class that let you write indicial-notation expressions? It looks doable. I made this code work:

```
a = WrappedTensor(np.r_[:4].reshape(2,2).astype(float))
b = WrappedTensor([[1,0.1],[0.11,1.5]])
i,j,k,l='ijkl'
# Note: .tensor returns the ndarray:
assert a[i,i].tensor == np.trace(a.tensor)
assert np.all(a[j,i].tensor == a.tensor.T)
# Regular dot product:
assert np.all(np.dot(a.tensor, b.tensor) == (a[i,j]*b[j,k]).tensor)
assert np.all(((a[i,j] + a[j,i]) / 2.0).tensor == (a.tensor + a.tensor.T) / 2.0)
assert np.all((a[i,j] * KroneckerDelta(2)[j,k] * b[k,l]).tensor == (a[i,j] * b[j,k]).tensor)
x = WrappedTensor([1.0,0,0])
y = WrappedTensor([0,1.0,0])
z = WrappedTensor([0,0,1.0])
assert np.all((x[i]*y[j]*LeviCivita[i,j,k]).tensor == [0,0, 1])
assert np.all((x[k]*y[j]*LeviCivita[i,j,k]).tensor == [0,0,-1])
assert np.all((x[i]*x[j] + y[i]*y[j] + z[i]*z[j]).tensor == np.eye(3))
```

I'd be happy to share my code.

**Comment by njsmith** [comment]
Hi Ben, thanks for your interest in contributing to numpy. Two suggestions:
1) I'd suggest sending this to numpy-discussion instead of here --
that's where we have more general "what do you think of...?" type
discussions.
2) You'll probably have more luck if you also explain what an
indicial-notation wrapper is :-). It doesn't mean much to me, and
github has mangled your code.

On Fri, May 29, 2015 at 10:22 AM, Ben FrantzDale
<notifications@github.com> wrote:
> Would it be interesting to have a wrapper class that let you write
> indicial-notation expressions? It looks doable. I made this code work:
> a = WrappedTensor(np.r_[:4].reshape(2,2).astype(float))
> b = WrappedTensor([[1,0.1],[0.11,1.5]])
> i,j,k,l='ijkl'
> # Note: .tensor returns the ndarray:
> assert a[i,i].tensor == np.trace(a.tensor)
> assert np.all(a[j,i].tensor == a.tensor.T)
> # Regular dot product:
> assert np.all(np.dot(a.tensor, b.tensor) == (a[i,j]b[j,k]).tensor)
> assert np.all(((a[i,j] + a[j,i]) / 2.0).tensor == (a.tensor + a.tensor.T) /
> 2.0)
> assert np.all((a[i,j] * KroneckerDelta(2)[j,k] * b[k,l]).tensor == (a[i,j] *
> b[j,k]).tensor)
> x = WrappedTensor([1.0,0,0])
> y = WrappedTensor([0,1.0,0])
> z = WrappedTensor([0,0,1.0])
> assert np.all((x[i]y[j]LeviCivita[i,j,k]).tensor == [0,0, 1])
> assert np.all((x[k]y[j]LeviCivita[i,j,k]).tensor == [0,0,-1])
> assert np.all((x[i]x[j] + y[i]y[j] + z[i]z[j]).tensor == np.eye(3))
>
> I'd be happy to share my code.
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by BenFrantzDale** [comment]
Thanks for the feedback. I will play with it a bit more. I have a much cleaner version already, replacing WrappedTensor with a tensor class that subclasses np.ndarray but provides indicial-notation indexing.

**Comment by seberg** [comment]
This (tensor/einsum notation using indexing notation or something in that direction "identical-notation expression") sounds like an idea that is probably best developed outside of numpy (without any real loss in functionality). If it became popular, i guess it could be something to discuss. But it was mostly a tentative question even back in 2015, so closing. If it becomes more relevant at some point, the issue can be reopened/new one made.
