### ISSUE TITLE
linspace should give a Warning or Exception when num is negative

### ISSUE THREAD

**Issue by rubendv** [numpy/numpy#5937]
I just finished tracking down a bug that would have been much easier to find if `linspace` did not just give back an empty array whan `num` is negative. An exception or at least a warning (to be backwards compatible) would have been nice to have.

**Comment by charris** [comment]
A `ValueError` exception seems appropriate for `num <= 0`. If you want to make a PR that would be welcome.

**Comment by Nodd** [comment]
`num == 0` looks valid to me, I would expect an array with 0 elements. Only strictly negative values have no meaning.
(Take this as a remark more than a strong opinion)
