### ISSUE TITLE
Filling an array valued field of a Structured Array

### ISSUE THREAD

**Issue by rayarb** [numpy/numpy#5939]
After several days of debugging an application, I determined that the source of my problem was related to an unexpected behavior (bug?) when assigning ndarray values to structured arrays. Depending on how the assignment is expressed, only the first entry in the array gets updated. I am using numpy version 1.9.2.

Here is a snippet to demonstrate the issue.

```python
import numpy as np

x = np.zeros((4,), dtype=[("i", "u1"), ("a", "u1", (3,))])
i = np.arange(4)
b = np.arange(12).reshape((4,3))

print "Initial values:"
print "x:", x, "\n"
print "i:", i, "\n"
print "b:", b, "\n"

x["i"] = i
x["a"][0][:] = b[0]
x["a"][1] = b[1]
x[2]["a"][:] = b[2]
x[3]["a"] = b[3]

print "After assignments:"
print "x:", x
```

Here is the output. Notice the last assignment `x[3]["a"] = b[3]` did not fill in all three components.

```
Initial values:
x: [(0, [0, 0, 0]) (0, [0, 0, 0]) (0, [0, 0, 0]) (0, [0, 0, 0])] 

i: [0 1 2 3] 

b: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

After assignments:
x: [(0, [0, 1, 2]) (1, [3, 4, 5]) (2, [6, 7, 8]) (3, [9, 0, 0])]
```

**Comment by charris** [comment]
Thanks for the report. This is a known problem and we are working on it...
