### ISSUE TITLE
`numpy.bool_(True) is True` evaluates to `False`

### ISSUE THREAD

**Issue by shackenberg** [numpy/numpy#5942]
Even though `numpy.bool_(True) == True` evaluates to `True`. Doesn't this violate the [PEP8](http://legacy.python.org/dev/peps/pep-0008/#other-recommendations) recommendation that ``Comparisons to singletons like None should always be done with is or is not, never the equality operators.`?

Sorry, if this is a dupe. I searched for bool comarison and pep8 and could not find an relevant issue.
`numpy.__version__`: 1.9.0.dev-297f54b

**Comment by pv** [comment]
`numpy.bool_` is a type, not the same thing as Python booleans:
```
>>> np.bool_
<type 'numpy.bool_'>
```

**Comment by njsmith** [comment]
The pep recommendation doesn't mean that nothing is allowed to compare ==
to singletons, just that if you're checking for the literal singleton True
object you should use "is" to do that. And np.bool_(True) is a different
object than True -- it has to be, it's a different class! -- so "is" will
return False no matter what pep 8 says.

See also: 1 == True, 1 is True

**Comment by shackenberg** [comment]
Sorry for the bad example, better would have been:
`print numpy.ones((1), dtype=bool)[0] `  --> True
`print numpy.ones((1), dtype=bool)[0] is True` --> False
`print numpy.ones((1), dtype=bool)[0] == True` --> True

Thanks for the explanation.

**Comment by njsmith** [comment]
Ah, yes, it doesn't help that the numpy types like np.bool_ often disguise
themselves as being python built-in types... Which is unfortunate. Arguably
it should repr as "np.bool_(True)". I guess you could open a bug or
discussion about that on the mailing list if you want.

**Comment by jaimefrio** [comment]
Actually, the PEP8 recommendation for `True` and `False` is that you don't compare them against anything, not with `==`, and especially not with `is`, but use them directly. The following is the relevant paragraph:

> Don't compare boolean values to True or False using == .
>
> Yes:   `if greeting:`
> No:    `if greeting == True:`
> Worse: `if greeting is True:`

**Comment by charris** [comment]
Changing the repr sounds sensible except that doctests may be an problem...
