### ISSUE TITLE
Warning message for one function is used by several, and contains extraneous information

### ISSUE THREAD

**Issue by holdenweb** [numpy/numpy#5945]
In [this Stackoverflow question](http://stackoverflow.com/questions/30679192/how-to-remove-multiple-values-from-an-array-at-once/) the inquirer points out the following discrepancy in an error message:

    In [5]: np.delete(x, x == a)
    /usr/lib/python2.7/dist-packages/numpy/lib/function_base.py:3254: FutureWarning: in the future insert will treat boolean arrays and array-likes as boolean index instead of casting it to integer
      "of casting it to integer", FutureWarning)

Since the warning is produced by a call to `delete()` it would be better if the message didn't refer to a specific function.

Also, why does the string ` "of casting it to integer"` appear at the end of the warning message?

**Comment by njsmith** [comment]
The answer to your last question is, because python is trying to show you
the source for offending line of code, and we didn't pass a stacklevel=
argument to warnings.warn like we should have, so it's showing you the
source for actual call to warnings.warn.

**Comment by sumitbinnani** [comment]
@njsmith @seberg 
Is anyone working on this? If not I would be happy to contribute :-)

**Comment by njsmith** [comment]
Go for it!

**Comment by seberg** [comment]
Stacklevel has just been bumped in master, thanks again @sumitbinnani.
