### ISSUE TITLE
BUG: numpy.asarray does not work with large lists

### ISSUE THREAD

**Issue by jor-** [numpy/numpy#5975]
numpy.asarray throws an exception with lists with length greater than numpy.iinfo(np.int32).max. 

Try the following, but mind that much memory is needed:

``` python
import numpy as np
value_bound = 10**6
size = 10**10
data_list = list(np.random.randint(0, value_bound, size))
data_array = np.asarray(data_list)
```

The output on my system:

```
Python 3.4.3 (default, Mar  9 2015, 15:18:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> 
>>> value_bound = 10**6
>>> max_int32 = np.iinfo(np.int32).max
>>> 
>>> size = 10**10
>>> size > max_int32
True
>>> data_list = list(np.random.randint(0, value_bound, size))
>>> data_array = np.asarray(data_list, dtype=np.int32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sunip229/.local/lib/python3.4/site-packages/numpy/core/numeric.py", line 462, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: cannot copy sequence with size 1410065408 to array axis with dimension 1410065408
>>> 
>>> size = 10**9
>>> size > max_int32
False
>>> data_list = list(np.random.randint(0, value_bound, size))
>>> data_array = np.asarray(data_list, dtype=np.int32)
>>> 
```

Below are some version info:
Python 3.4.3
NumPy 1.9.2
OS: linux, 64 Bit

**Comment by jaimefrio** [comment]
It works with Python 2.7, latest máster, on a Mac.

**Comment by OmerJog** [comment]
Can someone reproduce it?
I get MemoryError: Unable to allocate array with shape (10000000000,) and data type int32 when trying to reproduce so I can't check if this still an issue

**Comment by seberg** [comment]
Thanks, I will close this. I cannot reproduce this (and you need an absurd amount of memory to try). What I could imagine is that there is a MemoryError which is hidden behind the `sequence` error making it difficult to understand why it failed in that sense.

If that is the case, chaining the exception in the value error would bet he solution.

**Comment by eric-wieser** [comment]
These is a bug in the error message generation here.

**Comment by eric-wieser** [comment]
I'd be inclined to leave this open - it's symptomatic of a misuse of `int` somewhere we meant `intp`, and maybe one day with enough memory will be able to reproduce it on their system

**Comment by seberg** [comment]
Oh, right, and Jaime would not have been able to repro on a 64 bit system... A lot of these issues were fixed at one point or another, so I guess right now it may or may not be an issue... I am OK with it being open or closed, personally.

**Comment by eric-wieser** [comment]
> Jaime would not have been able to repro on a 64 bit system

I think he would - `int` is not 64-bit on any sensible system - maybe this was fixed long ago and can be closed after all.

**Comment by jor-** [comment]
I tried it again with NumPy 1.17.2  on a 64 bit system. I do not get the error anymore. So this seems to be fixed and the issue can be closed. Thanks for fixing.
