### ISSUE TITLE
seg fault in concatenate

### ISSUE THREAD

**Issue by toadwarble** [numpy/numpy#5979]
I'm running numpy 1.9.1 on a X86-64 machine (tried more than one with slightly different builds)

The following code causes a segfault

import numpy as np
x=np.arange(1,100)
np.concatenate(x,100)

I know that the last line is wrong but it should bitch at me rather than segfaulting!!!

**Comment by jaimefrio** [comment]
It is still failing with máster. Should be able to take a look at it over the weekend if no one beats me to it.

**Comment by seberg** [comment]
Maybe this helps (just first thing I noticed):
`*** stack smashing detected ***: python terminated`

**Comment by seberg** [comment]
Ah, found it.

**Comment by seberg** [comment]
A bit surprised this does not throw a DeprecationWarning, but \*shrug\*.

**Comment by juliantaylor** [comment]
as it currently crashes we should probably just turn invalid axis argument it into an error in the python wrapper. The axis=maxdims is only for the C-API

**Comment by seberg** [comment]
It only crashes if you put in more then 32 arrays though. But then it is complete nonsense, so...
