### ISSUE TITLE
diagonal views need to be made writable.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#5993]
Was scheduled for 110.

**Comment by rgommers** [comment]
I thought we weren't going to do that anymore.....

**Comment by charris** [comment]
Duplicate.

@rgommers Where was that decided?

**Comment by njsmith** [comment]
We had a thread about it on the mailing list a while ago that didn't come
to any conclusion.

I think we should let the status quo ride until 1.11, anyway. The original
deprecation plan was written on the assumption of year+ gaps between
releases.

Closed #5993 <https://github.com/numpy/numpy/issues/5993>.

—
Reply to this email directly or view it on GitHub
<https://github.com/numpy/numpy/issues/5993#event-336273872>.
