### ISSUE TITLE
DEP: Python 3.4 deprecates the imp module.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#5997]
Should have a workaround applied before then.

**Comment by jakirkham** [comment]
What is `imp` being used for now? Could `importlib` just be imported instead?

**Comment by charris** [comment]
If you grep for `import imp` you will find about 5 uses. One kind of use is an easy fix, the other more complicated. I have an old branch making a start on this, but have at it if you want. The `importlib` module isn't a straight forward replacement and only `importlib.import_module` is available in 2.7. There is nothing in 2.6, so this is a 1.12 task.

**Comment by jakirkham** [comment]
> There is nothing in 2.6, so this is a 1.12 task.

Meaning python 2.6 support will be removed in 1.12 or something else?

**Comment by charris** [comment]
Python 2.6, 3.2, & 3.3 will be dropped in 1.12.

**Comment by jakirkham** [comment]
Thanks for clarifying.
