### ISSUE TITLE
numpy.linalg.eig eigenvectors not enough precision

### ISSUE THREAD

**Issue by lhknag** [numpy/numpy#6008]
I've been taking a Coursera class and came across an issue with Python 3.4 using numpy-1.8.1 on 32-bit Windows Vista when solving the following problem using eigenvalues and eigenvectors:

    import numpy as np
    import matplotlib.pyplot as plt

    M = np.matrix([[-.75,0,.75,.75,0],[0,-.75,0,.75,.75],[.75,0,-.75,0,.75],[.75,.75,0,-.75,0],[0,.75,.75,0,-.75]])
    # DOESN'T RETURN CORRECT PRECISION
    eigM=np.linalg.eig(M)

    W = np.matrix([[.6,.1,.1,.1,.1],[.1,.6,.1,.1,.1],[.1,.1,.6,.1,.1],[.1,.1,.1,.6,.1],[.1,.1,.1,.1,.6]])
    u = np.matrix([[.6],[.5],[.6],[.2],[.1]])
    h = W*u

    vss = 0
    for i in range(0,len(eigM[0])):
        vss += (np.dot(np.squeeze(np.asarray(h)),np.squeeze(np.asarray(eigM[1][:,i])))/(1-eigM[0][i]))*eigM[1][:,i]

The problem is the result for vss doesn't have the right precision. When I solve the equation numerically I get the correct answer with the right precision:

    v = np.matrix([[1.0],[1.0],[1.0],[1.0],[1.0]])
    tau = .1
    dt = .001
    for i in range(1,100000):
       v = v+1/tau*(-v+h+M*v)*dt

I also wrote equivalent code in MATLAB to confirm that the eig() function there is working correctly and it is. In looking at the results, it seemed like the eigenvalues matched closely, but the eigenvectors did not. Hopefully you can see what is going on here better than I can, I think numpy is awesome! Thanks for your time and efforts!

**Comment by charris** [comment]
The matrix M has two identical eigenvalues up to roundoff. Effectively, any orthogonal basis for the corresponding two dimensional subspace provides "correct" eigenvectors. IOW, the eigenvectors are not uniquely determined. You will also want to use `eigvalsh` for symmetric matrices like this.
