### ISSUE TITLE
ndarray should have a __numpy_ufunc__ method

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#6011]
As per https://github.com/numpy/numpy/issues/5986#issuecomment-114552976

CC: @mhvk

**Comment by mhvk** [comment]
Thanks!

**Comment by njsmith** [comment]
One complication to consider: if the presence of `__numpy_ufunc__` disables `__array_wrap__` and friends (as it currently does), then carelessly adding `__numpy_ufunc__` to `ndarray` might cause existing subclasses to break.

I guess the most practical way to implement `ndarray.__numpy_ufunc__` in the short term would be to teach the ufunc machinery to (as a special case) ignore the presence of this particular `__numpy_ufunc__` method when seen, and then its implementation could be
```
def __numpy_ufunc__(self, ...):
    if <there are any objects with __numpy_ufunc__ methods>:
        return NotImplemented
    else:
        return getattr(ufunc, method)(...)
```
and this would both avoid infinite regress and allow subclasses to still take advantage of the `__array_wrap__` stuff (since while they would inherit a `__numpy_ufunc__` implementation, it would be ignored).

Kinda ugly all around though...

**Comment by seberg** [comment]
It seems `ndarray.__array_ufunc__` exists nowadays, so closing.
