### ISSUE TITLE
Invalid offset in buffer format string generation, when trying to use PyOpenCl with Numpy

### ISSUE THREAD

**Issue by kirbyevanj** [numpy/numpy#6022]
I am porting over one of my projects from cpu to gpu and in the process I simply copied some of the code from http://documen.tician.de/pyopencl/howto.html
However I keep getting a numpy error. Code:

```
import pyopencl as cl
import pyopencl.tools
import pyopencl.array
import numpy as np

def gpuTest():
    context = cl.create_some_context(interactive=False)
    queue = cl.CommandQueue(context)
    my_struct = np.dtype([("field1", np.int32), ("field2", np.float32)])
    my_struct, my_struct_c_decl = cl.tools.match_dtype_to_c_struct(context.devices[0], "my_struct", my_struct)
    my_struct = cl.tools.get_or_register_dtype("my_struct", my_struct)

    print(my_struct_c_decl)

    ary_host = np.empty(20, my_struct)
    ary_host["field1"].fill(217)
    ary_host["field2"].fill(1000)
    ary_host[13]["field2"] = 12

    print(ary_host)

    ary = cl.array.to_device(queue, ary_host)

    prg = cl.Program(context, my_struct_c_decl + """
    ...     __kernel void set_to_1(__global my_struct *a)
    ...     {
    ...         a[get_global_id(0)].field1 = 1;
    ...     }   
    ...     """).build()

    evt = prg.set_to_1(queue, ary.shape, None, ary.data)

    print(ary)


gpuTest()
input()
```

Here is the console output:

```
typedef struct {
  int field1;
  float field2;
} my_struct;


[(217, 1000) (217, 1000) (217, 1000) (217, 1000) (217, 1000) (217, 1000)
 (217, 1000) (217, 1000) (217, 1000) (217, 1000) (217, 1000) (217, 1000)
 (217, 1000) (217, 12) (217, 1000) (217, 1000) (217, 1000) (217, 1000)
 (217, 1000) (217, 1000)]
Traceback (most recent call last):
  File "C:\Users\\Desktop\Programming\Python Programming\Pygpu\main.py", line 36, in <module>
    gpuTest()
  File "C:\Users\\Desktop\Programming\Python Programming\Pygpu\main.py", line 22, in gpuTest
    ary = cl.array.to_device(queue, ary_host)
  File "C:\Python34\lib\site-packages\pyopencl\array.py", line 1680, in to_device
    result.set(ary, async=async)
  File "C:\Python34\lib\site-packages\pyopencl\array.py", line 670, in set
    is_blocking=not async)
  File "C:\Python34\lib\site-packages\pyopencl\__init__.py", line 1051, in enqueue_copy
    return _cl._enqueue_write_buffer(queue, dest, src, **kwargs)
RuntimeError: This should never happen: Invalid offset in buffer format string generation. Please 
report a bug to the Numpy developers.
Press any key to continue . . .
```

I cant seem to find anyone else who has had this kind of problem, is there something I could have done wrong when installing?
Thank you in advance

**Comment by charris** [comment]
Hmm, I think @seberg wrote that message. What version of numpy?

**Comment by seberg** [comment]
Was my first guess as well, but seems it was @pv ;). The message has been there since 2011 apparently. This is field dtypes, don't have an immediate clue about it unfortunatly.

**Comment by Ragingdolphin** [comment]
I am using numpy version 1.9.2

**Comment by charris** [comment]
@seberg My apologies, I was going to correct the post but you beat me to it...

**Comment by charris** [comment]
@Ragingdolphin What compiler/OS?

**Comment by Ragingdolphin** [comment]
Windows 7 Home Premium 64 bit. I am using python 3.4, I installed it with the pip command "pip install numpy"

**Comment by Ragingdolphin** [comment]
I also just noticed my kernel is written with an error. 
Update:
	    prg = cl.Program(context, my_struct_c_decl + """
	            __kernel void set_to_1(__global my_struct *a)
	            {
	                a[get_global_id(0)].field1 = 1;
	            }   
	            """).build()

**Comment by pv** [comment]
One way this can happen is that the field offset in the dtype is
something other than an integer, so that `PyInt_AsLong` returns -1 to
signal an error. The array dtype appears to be generated by Pyopencl, so
it might be something nonstandard.
.
What does `print(repr(my_struct))` say?

**Comment by Ragingdolphin** [comment]
dtype({'names':['field1','field2'], 'formats':['<i4','<f4'], 'offsets':[4,0], 'itemsize':8})

**Comment by seberg** [comment]
There is a call to `PyInt_AsLong(offset_obj)` if this fails, then I think this error would be triggered instead. Just poking in the dark.

**Comment by pv** [comment]
... and what does `repr(my_struct.fields)` say?

**Comment by Ragingdolphin** [comment]
mappingproxy({'field1': (dtype('int32'), 4), 'field2': (dtype('float32'), 0)})

**Comment by pv** [comment]
... and can you check whether the integers there are actually Python
integers or something else that prints the same way?

**Comment by Ragingdolphin** [comment]
@pv what do you mean?

**Comment by seberg** [comment]
@Ragingdolphin, check the type of the "0" and the "4" in this `mappingproxy` object. Also check that `int(...)` works for it (unless it is a python integer already). I guess `type(my_struct.fields['field1'][1])` should be the trick.

**Comment by Ragingdolphin** [comment]
type(my_struct.fields['field1'][1]) returned <class 'int'>. Should it be int32?

**Comment by pv** [comment]
@Ragingdolphin: Check if `type(foo) is int`, where `foo` is one of the
integers inside dtypes.fields. Can you also check what `my_struct.names`
says?
.
The error can be triggered if `dtype.names` is not ordered so that the
field offsets are increasing. I guess this can happen in some code does
`x = dict(dtype.fields) -> manipulate x -> construct dtype from x`. In
principle the buffer format string generator should first sort the
fields according to increasing offset order.

**Comment by seberg** [comment]
No, this is right. I think the weird thing is that the fields are in the wrong order maybe? The offset 4 is before the offset 0, is this a legal way to index fields? I.e. why does the int field have an offset of 4? it should be 0, no? and the float field should have 4?

**Comment by Ragingdolphin** [comment]
my_struct.names returns ('field1', 'field2')

**Comment by seberg** [comment]
Yes, but the offsets are `[4, 0]`, they should be `[0, 4]`. Frankly, to me it seems that probably pyopencl is shuffling the order somewhere. Maybe due to hash randomization it is only apparent on python 3 or something like that?

**Comment by pv** [comment]
Ok, then it's an issue with having a field order with non-increasing
offsets.
.
This probably is a bug on our side --- it's probably valid to have a
dtype in which the fields in `dtype.names` are in an order where the
field offsets are non-increasing. The buffer format string generation
should be written to allow this, so there needs to be a sort...

**Comment by Ragingdolphin** [comment]
Is there anyway for me to switch the offsets?

**Comment by Ragingdolphin** [comment]
When I changed the line

    my_struct = np.dtype([("field1", np.int32), ("field2", np.float32)])

to

    my_struct = np.dtype([("field1", np.float32), ("field2", np.int32)])

I stil got the same error. And then when I ran "my_struct.fields" on the new line, I got the result "{'field1': (dtype('float32'), 4), 'field2': (dtype('int32'), 0)}"

**Comment by pv** [comment]
@Ragingdolphin: as a work-around you can re-construct the dtype from the
contents of `my_struct.field`, but do it so that the fields are ordered
so that offsets are increasing. Can't tell you exactly how this goes
from the top of my head --- you'd need to look into the docs of np.dtype.

**Comment by Ragingdolphin** [comment]
Ok, I'll see what I can do. Thank you.

**Comment by crackwitz** [comment]
I'd like to revisit this issue. I have constructed (for my convenience) a buffer of `dtype={'names':['x','y','rx','ry','xy','roi'], 'formats':['<f4','<f4','<f4','<f4',('<f4', (2,)),('<f4', (2,))], 'offsets':[0,4,8,12,0,8], 'itemsize':16})`

when I try to assign such a record to an element of a corresponding array, I get `*** RuntimeError: This should never happen: Invalid offset in buffer format string generation. Please report a bug to the Numpy developers.`

numpy 1.12.1 in py3.6 seems to dislike this. it DID work on a previous version.

what do you suggest?

**Comment by eric-wieser** [comment]
I don't see how your example, @crackwitz, could possibly have ever worked (correctly). Can you name a version that it did work in?

Your dtype contains overlapping fields, but the PEP3118 format is not able to represent that.

I believe the error message has been improved in 1.13.

**Comment by crackwitz** [comment]
it did work for python 2.7 and a version of then-current numpy that was built 2016, 2015 maybe (gohlke binary package).

it did work as expected: namely like a union. I don't know what'd be wrong with that. basically I just wanted a bunch of records where I can access single fields as-is and groups of fields as tuples/arrays.

**Comment by eric-wieser** [comment]
> it did work as expected: namely like a union. I don't know what'd be wrong with that. 

The problem with that is that PEP3118 does not support unions, and PEP3118 is what buffers must conform to.

There is nothing wrong with using unions in numpy - the issue is what happens when passed to `memoryview`:

>>> dt = np.dtype({'names':['x','y','rx','ry','xy','roi'], 'formats':['<f4','<f4','<f4','<f4',('<f4', (2,)),('<f4', (2,))], 'offsets':[0,4,8,12,0,8], 'itemsize':16})
>>> a = np.empty(0, dt)
>>> memoryview(a)
RuntimeError: This should never happen: Invalid offset in buffer format string generation. Please report a bug to the Numpy developers.
```

Are you calling `memoryview` or using some external library that might be? Or are you trying to describe a bug self-contained in numpy?

**Comment by crackwitz** [comment]
uh... I'm not aware of that. I do put my array in a memory mapped file using np.memmap(..., dtype=...)

**Comment by eric-wieser** [comment]
Can you give a minimal example of the error occuring?

**Comment by crackwitz** [comment]
https://gist.github.com/crackwitz/e13b600a1a0158cc3301918b7edf5200

**Comment by eric-wieser** [comment]
Thanks, that looks like a bug in `memmap` to me. I don't think it's really the same bug as this issue is reporting though - just the same exception. So maybe best to file a new issue for visibility?

**Comment by crackwitz** [comment]
can do
