### ISSUE TITLE
`np.dtype('string')` only works on Python 2

### ISSUE THREAD

**Issue by Garrett-R** [numpy/numpy#6023]
In Python 2, there's no problem:

```
~/git/numpy2 $ python2
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.10.0.dev0+38d6f09'
>>> np.dtype('string')
dtype('S')
```

In Python 3, this throw an exception:

```
~/git/numpy $ python
Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.10.0.dev0+38d6f09'
>>> np.dtype('string')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type "string" not understood
```

**Comment by KeWata** [comment]
2系
{'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'others': [bool, object, str, unicode, numpy.void],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64]}

In [3]: 
Do you really want to exit ([y]/n)? y
16:scipy keitawatanabe$ pyenv local 3.4.1
16:scipy keitawatanabe$ ipython 
Python 3.4.1 (default, Mar  6 2015, 16:01:42) 
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy as np

In [2]: np.sctypes
Out[2]: 
3系
{'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'others': [bool, object, str, str, numpy.void],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64]}

unicodeがstrになっている．これを残しているのはわざと？

**Comment by KeWata** [comment]
おそらく，sctypesのindexingを行う際に2系と3系での整合性を保つためであると思われる．問題なし

**Comment by malarinv** [comment]
it has been 3 years and still no fix yet?

**Comment by eric-wieser** [comment]
There's no reason to use this spelling in the first place - `np.dtype(str)` is shorter, faster, and more obvious. To quote [the zen of python](https://zen-of-python.info/there-should-be-one-and-preferably-only-one-obvious-way-to-do-it.html#13),

> There should be one-- and preferably only one --obvious way to do it.

Given it's been broken for 3 years, the compatibility argument doesn't hold much wait any more - users will have either already fixed this in their codebase, or are likely stuck on an old version of numpy already for other reasons.

I'd be inclined to close this.

**Comment by malarinv** [comment]
I'm here from an upstream [tensorflow-1.9.0](https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/python/keras/backend.py#L2883). It is breaking with this error because the type string they're sending happens to be 'string' in python3. will check if it is fixed in their master.

**Comment by mattip** [comment]
@malarinv  any news if [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L2880) from tensorflow master yields `'string'`

**Comment by malarinv** [comment]
@mattip I tried the latest tensorflow 1.12 release and this issue doesn't exist there, I assume the dtypes module is taking care of this quirk. so didn't care what it returned.

**Comment by mattip** [comment]
Thanks for checking. Closing.
