### ISSUE TITLE
Creating array from sympy matrix with dtype

### ISSUE THREAD

**Issue by vascotenner** [numpy/numpy#6024]
I try to convert an sympy matrix to a numpy array. Then this strange behaviour pops up:

Does **not** work:

``` python
np.array(sympy.Matrix([1]), dtype=np.complex)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-26314c7e97b1> in <module>()
----> 1 np.array(Matrix([1]), dtype=np.complex)

TypeError: __array__() takes exactly 1 argument (2 given)
```

**Works:**

``` python
np.array(Matrix([1])).astype(dtype=np.complex)
```

numpy.**version** = 1.9.2

**Comment by argriffing** [comment]
Here's a thread related to `np.array(sympy.Matrix(...))`
https://code.google.com/p/sympy/issues/detail?id=609

**Comment by argriffing** [comment]
Sympy has a special function [`matrix2numpy`](https://github.com/sympy/sympy/pull/7446) that can do this.

```python
>>> matrix2numpy(Matrix([1]), dtype=complex)
array([[ 1.+0.j]])
```

**Comment by WarrenWeckesser** [comment]
I haven't tracked down the changes that may have fixed this, but the example works now:
```

In [1]: import numpy as np

In [2]: import sympy

In [3]: np.__version__
Out[3]: '1.22.0.dev0+1410.g024d64b53'

In [4]: sympy.__version__
Out[4]: '1.8'

In [5]: np.array(sympy.Matrix([1]), dtype=complex)
Out[5]: array([[1.+0.j]])

```
I'm closing the issue, but please comment if there is still problem. We can reopen the issue if necessary.
