### ISSUE TITLE
min() and argmin() inconsistent with NaTs

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#6030]
Either NaT is ignored or it isn't when looking for a minimum, but min() and argmin() disagree:

```
>>> a = np.arange(10).astype('m8[s]')
>>> a[1] = 'NaT'
>>> a.min()
numpy.timedelta64(0,'s')
>>> a.argmin()
1
```

**Comment by jaimefrio** [comment]
In [`loops.c.src`](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/loops.c.src#L1142), the `maximum` and `minimum` ufuncs for datetime explicitly ignore `'NaT'`.

In [`arraytypes.c.src`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arraytypes.c.src#L3004), on the other hand, `'NaT'` are treated as normal values. This I believe is the function that should be changed.

The representation of `'NaT'` could also use some love:

```
In [74]: a = np.arange(3).astype('m8[s]')

In [75]: a[1] = 'NaT'

In [76]: a
Out[76]: array([                   0, -9223372036854775808,                    2],
               dtype='timedelta64[s]')
```

**Comment by pitrou** [comment]
I've filed https://github.com/numpy/numpy/pull/6033 for the representation of NaTs.
