### ISSUE TITLE
document numpy bylaws

### ISSUE THREAD

**Issue by sbenthall** [numpy/numpy#6034]
I am a researcher interested in Numpy. I am trying to find information about numpy's governance structure. Many OSS project have their process documented somehow.

There is a lot of interesting material about this in this mailing list discussion:
http://mail.scipy.org/pipermail/numpy-discussion/2012-February/060452.html

e.g. these comments by John Hunter:
http://mail.scipy.org/pipermail/numpy-discussion/2012-February/060640.html

Documenting this process might help resolve conflicts of the kind suggested by the discussion here:
https://github.com/numpy/numpy/issues/5844#issuecomment-117746511

**Comment by njsmith** [comment]
There isn't any documentation you're missing.

See also the first bullet point at
https://github.com/numpy/numpy/wiki/SciPy-2015-developer-meeting ...

On Wed, Jul 1, 2015 at 3:27 PM, Sebastian Benthall <notifications@github.com
> wrote:

> I am a researcher interested in Numpy. I am trying to find information
> about numpy's governance structure. Many OSS project have their process
> documented somehow.
>
> There is a lot of interesting material about this in this mailing list
> discussion:
> http://mail.scipy.org/pipermail/numpy-discussion/2012-February/060452.html
>
> e.g. these comments by John Hunter:
> http://mail.scipy.org/pipermail/numpy-discussion/2012-February/060640.html
>
> Documenting this process might help resolve conflicts of the kind
> suggested by the discussion here:
> #5844 (comment)
> <https://github.com/numpy/numpy/issues/5844#issuecomment-117746511>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6034>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by njsmith** [comment]
By the way, if you'll be around at SciPy already on Tuesday, then you'd be welcome at that meeting -- you can observe us for data and tell us about what you know in exchange ;-).

**Comment by shoyer** [comment]
This has been resolved:
https://docs.scipy.org/doc/numpy-1.15.1/dev/governance/governance.html
