### ISSUE TITLE
intp on 32bit architectures not same as int32

### ISSUE THREAD

**Issue by iyer-arvind** [numpy/numpy#6038]
np version 1.9.2 (but bug in previous versions as well)
python version 3.4.3 (but bug with previous versions as well)

The following demonstrates the problem: 
On 64Bit architecture: 

``` python
>>> import numpy as np
>>> np.intp
<class 'numpy.int64'>
>>> np.intp==np.int64
True
```

On 32Bit architecture:

``` python
>>> import numpy as np
>>> np.intp
<class 'numpy.int32'>
>>> np.intp==np.int32
False
```

**Comment by mattip** [comment]
Still valid on latest HEAD

**Comment by eric-wieser** [comment]
Relates to #10151

**Comment by seberg** [comment]
Lets close this as a duplicate of that one, thanks all.
