### ISSUE TITLE
DEV: adding unbias option to the correlate function

### ISSUE THREAD

**Issue by jankoslavic** [numpy/numpy#6041]
The correlate function currently does not support the unbias option.

Please see the issue discussed here:
http://nbviewer.ipython.org/gist/jankoslavic/d4298dae2fbe9d598db1

I also have a working proposal for the implementation:
https://github.com/jankoslavic/numpy/commit/3fc57351e0dacec5cdef6b0923d8fc80f52d37a0

Here is another implementation:
http://statsmodels.sourceforge.net/0.6.0/_modules/statsmodels/tsa/stattools.html#ccf

**Comment by rgommers** [comment]
``np.cov`` has a ``bias`` keyword. Even if it hadn't, ``bias=True`` would be better than ``unbias=False``. Besides that API nitpick, I'd say submit a PR.

**Comment by jankoslavic** [comment]
Dear @rgommers thank you! I have submited PR.

**Comment by mattip** [comment]
Closing as this has stalled. If someone wants to champion it they should ask on the mailing list (since it enhances the API). Or perhaps there already was a discussion? In any case I also closed the associated PR, but if someone wants to push it forward they can reopen.
