### ISSUE TITLE
Possible bug in numpy/ma/core.py

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6045]
pyflakes notes the `_sharedmask` is assigned but never used. I suspect this may be a bug. Note the the `FIXME` message is not yet in master.

```
        if hasattr(data, '_mask') and not isinstance(data, ndarray):
            _data._mask = data._mask
            # FIXME _sharedmask is never used.
            _sharedmask = True
```

**Comment by saimn** [comment]
I saw this one while looking at the code, the lines below uses `_data._sharedmask`, and it seems safe to do this change. Any idea when this "compatibility" code should be executed ? (It needs something that has a `._mask` attribute but doesn't inherit from ndarray).

**Comment by WarrenWeckesser** [comment]
The unused variable was fixed in https://github.com/numpy/numpy/pull/19102 (but see https://github.com/numpy/numpy/issues/20372 and https://github.com/numpy/numpy/pull/20386).
