### ISSUE TITLE
_polybase.py: the way to declear abstract class works only for Python 2

### ISSUE THREAD

**Issue by xuhdev** [numpy/numpy#6059]
The Python 2 way to specify abstract class:

``` python
__metaclass__ = ABCMeta
```

Python 3 way:

``` python
class MyClass(metaclass=ABCMeta):
      pass
```

**Comment by eric-wieser** [comment]
Fixed in 1.17, now that python 3 is dropped. Probably not worth the effort of backporting to 1.16
