### ISSUE TITLE
FAIL: test_umath.TestComplexFunctions.test_branch_cuts

### ISSUE THREAD

**Issue by githubmlai** [numpy/numpy#6063]
Got following error when running "runtests.py" on linux 64 bit.
```
[mlai@begws92 numpy]$ uname -a
Linux begws92 2.6.32-358.23.2.el6.x86_64 #1 SMP Sat Sep 14 05:32:37 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux


======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arccosh'>, [-1, 0.5], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mlai/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mlai/github/numpy/build/testenv/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1690, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/home/mlai/github/numpy/build/testenv/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: (array([  0.00000000e+00+3.14159265j,   1.11022302e-16-1.04719755j]), array([  4.71216091e-07+3.14159218j,   1.28119737e-13+1.04719755j]))

----------------------------------------------------------------------
Ran 5974 tests in 45.985s

FAILED (KNOWNFAIL=3, SKIP=3, failures=1)
```

**Comment by juliantaylor** [comment]
which compiler was used to compile numpy?

**Comment by githubmlai** [comment]
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

**Comment by fieryvova** [comment]
Same issue here.
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

**Comment by ltnetcase** [comment]
Same issue here.
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

**Comment by rgommers** [comment]
Did anyone check if this test fails on older numpy releases?

**Comment by juliantaylor** [comment]
the test is new in 1.10, the issue probably always existed.

**Comment by fieryvova** [comment]
I confirm that the previous release (1.9.1)  goes through the tests without errors.
The problem is not related to the compiler, it seems. I've tried to compile numpy/1.10 with gcc/4.9.3 and gcc/4.8.4 - tests fail with the same error.

**Comment by ewmoore** [comment]
What version of gibc do you have?  

In 1.10 numpy is more aggressive about using the system supplied complex functions than it was in 1.9.  One thing you could try is to force the use of the fallback implementation of cacosh and see if the test passes. The easiest way to do this is to temporarily add a few lines to the bottom of /numpy/core/src/private/npy_config.h that looks like 
```
#undef HAVE_CACOSH
#undef HAVE_CACOSHF
#undef HAVE_CACOSHL
```
Recompile and see if that fixes your problem.

**Comment by fieryvova** [comment]
Thanks **ewmoore**, it worked!
glibc version: 2.12
Test results:
```
Ran 6153 tests in 153.032s

OK (KNOWNFAIL=3, SKIP=2)
<nose.result.TextTestResult run=6153 errors=0 failures=0>
```

**Comment by ewmoore** [comment]
Looks to me then that `cacosh`  should be added to the blacklist.  Looking at [this](https://sourceware.org/bugzilla/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=SUSPENDED&bug_status=WAITING&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&f0=OP&f1=OP&f2=product&f3=component&f4=alias&f5=short_desc&f7=content&f8=CP&f9=CP&j1=OR&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&o7=matches&query_format=advanced&v2=cacosh&v3=cacosh&v4=cacosh&v5=cacosh&v6=cacosh&v7=%22cacosh%22) list of glibc bugs looks like there were fixes that we may want as  late as 2012.  I'm not sure which version of glibc that means we should start accepting.

**Comment by argriffing** [comment]
related https://github.com/numpy/numpy/issues/6712

**Comment by charris** [comment]
The glibc 2.16 is the version where a lot of this was fixed..

**Comment by charris** [comment]
A PR adding those functions (and a few more) to the blacklist is #6975.

**Comment by charris** [comment]
glibc 2.16 was released 2012-06-30 with this comment

>* Math library bug fixes.  A thorough audit of all open math library bugs was
  conducted by Joseph Myers.  Significant progress was made on many math
  library bugs resulting in more accurate exceptions and function results.
  Many thanks to all those that contributed including Andreas Jaeger for his
  patch review and work on the x87 trigonometric instruction issues.
