### ISSUE TITLE
DOC: argmin, argmax, argort, etc. should link to `np.take_along_axis` in their documentation

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#6078]
In #6075, I wondered whether it might be possible to

> to have some simple way to use the output of `np.arg[min|max|sort]` as a proper index (to avoid hackery as in https://github.com/astropy/astropy/blob/master/astropy/time/core.py#L896 -- if there is a simpler way already, let me know!)

and @jaimefrio suggested that it might be simpler to have

> a `make_me_an_indexing_tuple=False` new keyword argument for the `argxxx` functions?

That indeed seems better, so I'm raising this as a separate issue.  The code linked to above could be used as a template on how to generate the index tuple.

**Comment by shoyer** [comment]
Indeed, this problem has also flummoxed me.

Here's the helper function I wrote, which may be slightly more interpretable:
```python
def argsort_indices(a, axis=-1):
    """Like argsort, but returns an index suitable for sorting the
    the original array even if that array is multidimensional
    """
    a = np.asarray(a)
    ind = list(np.ix_(*[np.arange(d) for d in a.shape]))
    ind[axis] = a.argsort(axis)
    return tuple(ind)
```

**Comment by mhvk** [comment]
@shoyer - yours is definitely easier to read, in that it leaves the proper shaping to `np.ix_`... also, it doesn't deal with `keepdims`, right?

**Comment by shoyer** [comment]
> also, it doesn't deal with keepdims, right?

I guess it's less general in that it only works for `argsort` -- I didn't think about `min`/`max`, so I didn't need anything for `keepdims`.

**Comment by ElieGouzien** [comment]
I think it would be lot better than today's implementation if the `axis=None` option returned something equivalent to :
```python
np.unravel_index(np.argsort(a, axis=None), a.shape)
```

**Comment by shoyer** [comment]
> I think it would be lot better than today's implementation if the axis=None option returned something equivalent to :
> np.unravel_index(np.argsort(a, axis=None), a.shape)

As a rule, NumPy doesn't change existing behavior. So this will need to be new API of some sort.

**Comment by ElieGouzien** [comment]
@shoyer Oh that's true.
I've just submitted a pull request to add my proposition to the doc so that the user can easily find how to retrieve indices.

**Comment by seberg** [comment]
I think this issue is now irrelevant, since we have `np.take_along_axis` instead, which solves the issue. I will however transform it into a Documentation issue, since those functions should list it under the See Also section at least.
