### ISSUE TITLE
Missing keepdims in documentation for ndarray.min/max

### ISSUE THREAD

**Issue by FilipeMaia** [numpy/numpy#6080]
ndarray.min() and ndarray.max() accept the keepdims argument, but this is missing from the documentation.

**Comment by ahaldane** [comment]
I noticed this too a little while ago, and it should now be fixed in master by #5733. (Assuming that is what you're referring to!)

**Comment by FilipeMaia** [comment]
You're right, it's seems to be fixed. Sorry!
