### ISSUE TITLE
Document our backcompat guarantees for np.random

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#6084]
I met someone at SciPy this year who had implemented their own PRNG routine from scratch, because they needed to guarantee it was deterministic and weren't sure if `np.random` results were stable between versions and machines. Given how much effort we put into guaranteeing exactly this stability, we should probably let people know we're doing it :-)

(Specifically, the guarantee as I understand it is: so long as you use the same seed, the same sequence of calls to `np.random` functions / `np.random.RandomState` methods will always return the same sequence of results, modulo small (a few units-in-the-last-place) differences in floating point values due to unavoidable differences in rounding errors between compilers. Anything else is a bug.)

**Comment by rgommers** [comment]
Good idea. The place to put it is probably the ``RandomState`` docstring I think, with a reference to that in the module docstring.

**Comment by urbanophile** [comment]
Is this closed?

**Comment by seberg** [comment]
Yes, thanks for the note.
