### ISSUE TITLE
Array contiguousness is not preserved during np.vstack/np.hstack

### ISSUE THREAD

**Issue by serhii-havrylov** [numpy/numpy#6086]
Hi, my current version of numpy is 1.9.2

``` python
>>> a = np.array([[1,2,3]], order='F')
>>> b = np.array([[4,5,6]], order='F')
>>> c = np.vstack((a, b))
>>> c.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

It is not clear to me why array contiguousness is not preserved during vstack/hstack operations. I expect that `c` should be in the Fortran order. It is interesting enough that when you have an array with more than two rows the behavior is quite expected:

``` python
>>> a = np.array([[4,5,4], [9,5,2]], order='F')
>>> b = np.array([[4,5,4], [9,5,2]], order='F')
>>> d = np.vstack((a,b))
>>> d.flags
Out[39]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

I would highly appreciate any clarifications on this inconsistent behaviour.

**Comment by njsmith** [comment]
I don't think we even have any policy in general saying that array
contiguousness is preserved in any operation... there are some operations
that try to preserve contiguity, but it's pretty ad hoc and inconsistent.
.
For stacking/concatenation in particular, you can arbitrarily many
different orders, so what do you even choose? I can see an argument for
supporting an explicit order="F" argument to request that the output have a
specific order (regardless of the inputs), though.
.
Wouldn't it make more sense for you to set up the contiguity you want just
before you call some function with tricky contiguity requirements, instead
of trying to boil the ocean by asking every single operation in numpy to
try and guess which contiguity you want?

On Thu, Jul 16, 2015 at 6:06 AM, sergii-gavrylov <notifications@github.com>
wrote:

> Hi, my current version of numpy is 1.9.2
>
> >>> a = np.array([[1,2,3]], order='F')>>> b = np.array([[4,5,6]], order='F')>>> c = np.vstack((a, b))>>> c.flags
>   C_CONTIGUOUS : True
>   F_CONTIGUOUS : False
>   OWNDATA : True
>   WRITEABLE : True
>   ALIGNED : True
>   UPDATEIFCOPY : False
>
> It is not clear to me why array contiguousness is not preserved during
> vstack/hstack operations.
> I would highly appreciate any clarifications about this behaviour.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6086>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by mattip** [comment]
Closing. Please open a new issue if there is the design decision should be reviewed
