### ISSUE TITLE
Intel compilers not working with distutils

### ISSUE THREAD

**Issue by slishak** [numpy/numpy#6095]
I'm having some issues using distutils to compile some C and Fortran code in another package. I've built NumPy from source as the Intel C compilers in Windows don't seem to be supported at all in 1.9.2. I'm using Python 2.7.10 (32-bit) and Intel Parallel Studio XE 2015. 

I had to make some changes to the code to get things working at all. The first issue appeared to be in numpy/distutils/intelccompiler.py: I had to change "from numpy.distutils.msvc9compiler" to "from distutils.msvc9compiler" as I was getting this error:

```
No module named msvc9compiler in numpy.distutils; trying from distutils
error: can't compile C/C++ code: unable to load module 'distutils.intelccompiler
```

This got me a little further in the build process, but then I had a problem with the Fortran compiler:

```
ifort: command line error: Unrecognized keyword 'IA-32' for option '/arch'
```

I removed the /arch:IA-32 flag from IntelVisualFCompiler.get_flags_arch in numpy/distutils/fcompiler/intel.py, which again got me a little further, but then it failed at the linking stage. It appears that ifort gets called with arguments that look like this:

```
C:\Program Files (x86)\Intel\Composer XE 2015\bin\ia32\ifort.exe -shared -shared [.obj files] -LC:\Python27\libs -LC:\Python27\PCbuild [more library paths] -lpython27 [more lib references] /OUT:[output .pyd file]
```

These are not valid arguments to ifort, so I get a lot of warnings like this:

```
ifort: command line warning #10006: ignoring unknown option '/shared'
ifort: command line warning #10006: ignoring unknown option '/shared'
ifort: command line warning #10006: ignoring unknown option '/LC:\Python27\libs'
ifort: command line warning #10006: ignoring unknown option '/lpython27'
```

and then a lot more spam about unknown options starting with /O due to the /OUT argument (it expanded everything after /O as separate optimisation options, like /OU /OT etc). I think ifort expects commands that look more like the following:

```
C:\Program Files (x86)\Intel\Composer XE 2015\bin\ia32\ifort.exe /exe:[output .pyd file] [.obj files] /link /DLL /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild [more library paths] python27.lib [more lib references]
```

Running this command works a lot better, but I still got a few unresolved external symbol errors which I think are probably unrelated to the issues above and I still haven't resolved. However, I thought you should at least be made aware of the above fixes I needed to at least stand a chance of getting things working!

**Comment by slishak** [comment]
On a related note to the above, there is also a bug in numpy/distutils/fcompiler/gnu.py, in GnuFCompiler.get_flags_opt. In the is_win32() section, -msse2 and -mincoming-stack-boundary=2 are missing a space in between, so it gets turned into one long option that isn't recognised. In case it's not obvious, I'm kind of new to Github and I'm not quite ready to actually make these changes myself!

**Comment by charris** [comment]
You might have more luck posting to the mailing list. I expect someone there can help as Intel is not a rare compiler.

**Comment by rgommers** [comment]
I probably have a patch for this sitting in my inbox, will check within the next few days.

**Comment by rgommers** [comment]
@slishak can you try again now that gh-6152 is merged? I got those patches from Intel so it should now work on Windows with Intel Parallel Studio XE 2015.

I'll have a look at the ``GnuFCompiler.get_flags_opt`` issue that you pointed out tomorrow.
