### ISSUE TITLE
Indexing with single boolean behaves inconsistently

### ISSUE THREAD

**Issue by sinhrks** [numpy/numpy#6104]
Related to #4353, #4980, but would like to ask the cases when the indexer is a single bool.

1. In normal array, ``bool`` looks coerces to ``int``. Is this intended, or should be regarded as a boolean indexing with different shape (#4353)?

  ```
  np.__version__
  # '1.9.2'

  np.array([0])[True]
  # IndexError: index 1 is out of bounds for axis 0 with size 1
  np.array([0])[False]
  # 0
  ```

2. 0-dim array behaves quite strangely. I understand this should raise ``IndexError`` if it coerces to ``int``.

  ```
  np.array(0)[False]
  # array([], dtype=int64)
  np.array(0)[True]
  # array([0])

  np.array(0)[0]
  # IndexError: too many indices for array
  ```

**Comment by seberg** [comment]
This is intentional, please rerun with deprecation warnings on, and you will understand ;).

**Comment by seberg** [comment]
To be clear, `True` should behave like `np.array(True)`. This is not yet the case for the 1-d array for backward compatibility issues, but is the case for the 0-d array because it makes live so much easier in many cases (and seemed unlikely to create bugs by accident).

**Comment by seberg** [comment]
Sorry for the spam.... Maybe in case you are interested, it is actually it is not "with different" shape, since the 0-d array "fits" to anything (there is no dimension along which it has the wrong amount of elements). `np.array([0])[True]` will return `np.array([[0]])` (inserts an axis, and copies the data). This is consistent with how boolean indexing works, even if it might be mind-boggling at first, it makes sense if you consider an `N-d` case and go to 0 dims.

**Comment by sinhrks** [comment]
@seberg Thanks for quick reply. Sorry, I missed the warning. I understand the issue 1.

```
np.array([0])[True]
# FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
```

I'm still unclear for no2. If 0-d array fits to anything, below cases this should work? Or arg must have same dimensionality 0-d (scalar, thus shape has no meaning)?

```
np.array(0)[np.array([True])]
# IndexError: too many indices for array
np.array(0)[np.array([True, True])]
# IndexError: too many indices for array

**Comment by seberg** [comment]
No, this is a 1-d boolean array index. The 0-d boolean array index will fit to any array. Since an N-d boolean array "eats" N dimensions from the original array, a 0-d array "eats"/operates on 0 dimensions, so it can operate on any array.

**Comment by sinhrks** [comment]
Thanks for kind reply. I've confused by value dimensions rather than indexer's. 

I understood that above cases are all should work as boolean indexing, and single bool index is regarded as 0-dim array.

**Comment by seberg** [comment]
You are welcome. I hope you are happy with the new behaviours :).
