### ISSUE TITLE
Add opt-in collection of user data to numpy.

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#6105]
The idea is to set up a central data collection server. Code would be added to several prominent user interface front-ends to ask users whether they would like to opt-in to data collection. A standard software library would allow other software to check whether the user has opted-in, and if so then to make it easy to aggregate data and submit it to the central server.

See comments and links in https://github.com/numpy/numpy/pull/6103.

**Comment by njsmith** [comment]
This isn't really an actionable issue... Not sure what you're hoping to accomplish by filing it now? (Sorry if that sounds critical, I don't mean it sarcastically, I just literally mean, I'm not sure what kind of workflow you have in mind where having this issue open now would help; maybe I'm missing something?) This isn't infrastructure that numpy can build on its own, and it isn't infrastructure that exists elsewhere yet either. At some point in the future the infrastructure will likely exist, given the EXTREME EXCITEMENT expressed by everyone I talked to about it at scipy, and if/when that happens we'll need to have a conversation about whether and how to use it in numpy, presumably on the mailing list where the broader community can participate. There's not much to productively talk about before then though given how many details remain to be settled. So inasmuch as the purpose of an open issue is to serve as a to-do reminder, maybe this should just be closed for now?

(Of course if anyone wants to help make the infrastructure actually exist, solve the technical and social issues around managing it, etc., then sempervirens has a repo and mailing list you can subscribe to ;-).)

**Comment by seberg** [comment]
Closing, it isn't actionable.  If someone in the ecosystem figures something out, we can consider it.
