### ISSUE TITLE
astype(dtype) converts NaN to np.iinfo(dtype).min for int32 and int64, but 0 for int16

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#6109]
This seems inconsistent:

```
In [38]: x = np.array([np.nan, 1, 2, 3])

In [39]: x
Out[39]: array([ nan,   1.,   2.,   3.])

In [40]: x.astype(np.int16)
Out[40]: array([0, 1, 2, 3], dtype=int16)

In [41]: x.astype(np.int32)
Out[41]: array([-2147483648,           1,           2,           3], dtype=int32)

In [42]: x.astype(np.int64)
Out[42]:
array([-9223372036854775808,                    1,                    2,
                          3])
```

**Comment by ewmoore** [comment]
This comes down to the rules the C compiler uses for casting `nan` to these types. The C standard says (6.3.1.4): 
>When a finite value of real floating type is converted to an integer type other than _Bool,
the fractional part is discarded (i.e., the value is truncated toward zero). If the value of
the integral part cannot be represented by the integer type, the behavior is undefined.

So the results don't have to be consistent.  You could in principle check for `inf` or `nan` before casting, if the speed hit were deemed acceptable (which it probably won't be).  However, there isn't a correct answer, should the result be `0` or `-INT_MIN`? How do you decide?

**Comment by seberg** [comment]
Closing this one, I kept gh-14412 open about this.  I guess we could try to escalate or normalize, but basically this is C undefined behavior.  NumPy main, however, *does* give a warning now when this undefined behavior occurs.  (Although lets see if all platforms get it right.)
