### ISSUE TITLE
on Raspberry Pi pip install numpy --upgrade fails

### ISSUE THREAD

**Issue by denfromufa** [numpy/numpy#6116]
In file included from numpy/core/include/numpy/npy_common.h:5:0,

                 from numpy/core/src/private/npy_sort.h:6,

                 from numpy/core/src/npysort/mergesort.c.src:31:

numpy/core/include/numpy/numpyconfig.h:4:26: fatal error: _numpyconfig.h: No such file or directory

compilation terminated.

In file included from numpy/core/include/numpy/npy_common.h:5:0,

                 from numpy/core/src/private/npy_sort.h:6,

                 from numpy/core/src/npysort/mergesort.c.src:31:

numpy/core/include/numpy/numpyconfig.h:4:26: fatal error: _numpyconfig.h: No such file or directory

compilation terminated.

error: Command "gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibuild/src.linux-armv7l-2.7/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-armv7l-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/usr/include/python2.7 -Ibuild/src.linux-armv7l-2.7/numpy/core/src/private -Ibuild/src.linux-armv7l-2.7/numpy/core/src/private -Ibuild/src.linux-armv7l-2.7/numpy/core/src/private -Ibuild/src.linux-armv7l-2.7/numpy/core/src/private -c build/src.linux-armv7l-2.7/numpy/core/src/npysort/mergesort.c -o build/temp.linux-armv7l-2.7/build/src.linux-armv7l-2.7/numpy/core/src/npysort/mergesort.o" failed with exit status 1

----------------------------------------
  Rolling back uninstall of numpy
Command /usr/bin/python -c "import setuptools;__file__='/home/pi/build/numpy/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-SP4Uhk-record/install-record.txt failed with error code 1 in /home/pi/build/numpy
Storing complete log in /root/.pip/pip.log
pi@raspberrypi ~ $

**Comment by denfromufa** [comment]
after 
```
sudo pip install cython
```
numpy installed successfully.

**Comment by rgommers** [comment]
Cython has nothing to do with your first compile error, so probably unrelated. But well, if it works now.... closing.

**Comment by rgommers** [comment]
Using ``sudo`` isn't recommended by the way, that can fail in various mysterious ways. Better use ``pip install cython --user``.
