### ISSUE TITLE
Add a parameter for user to control precision when `random.choice()` ?

### ISSUE THREAD

**Issue by icycandy** [numpy/numpy#6123]
I use [apollo](https://github.com/Russell91/apollo/issues/5) and get the issue `ValueError: probabilities do not sum to 1`

I used pickle seriealized the probs, the error can be reproduced by the following test code.

file `test.py`
```python
import os
import numpy as np
import pickle

probs = None
with open('test.pkl', 'rb') as f:
    probs = pickle.load(f)
print np.random.choice(range(len(probs)), p=probs/sum(probs))
```

file `test.pkl`
```pickle
cnumpy.core.multiarray
_reconstruct
p0
(cnumpy
ndarray
p1
(I0
tp2
S'b'
p3
tp4
Rp5
(I1
(I3
tp6
cnumpy
dtype
p7
(S'f4'
p8
I0
I1
tp9
Rp10
(I3
S'<'
p11
NNNI-1
I-1
I0
tp12
bI00
S'\xa7cv;\xe6\x8be;}\xf3u;'
p13
tp14
b.
```

--------------
Maybe we can add a parameter, so the user can control the precision(such as 1e-8, or 1e-4) when comare sum of probs to 1.

Or are there a way to overcome this issue?

file `numpy/random/mtrand/mtrand.pyx`, line 1094 to line 1099.
```python
            if np.logical_or.reduce(p < 0):
                raise ValueError("probabilities are not non-negative")
            if abs(kahan_sum(pix, d) - 1.) > 1e-8:
                raise ValueError("probabilities do not sum to 1")

        shape = size
```

**Comment by njsmith** [comment]
You could just renormalize before calling, I guess? Would that solve your
problem? It's about the best we could do anyway...

On Mon, Jul 27, 2015 at 6:23 AM, Guohua Tang <notifications@github.com>
wrote:

> I use apollo <https://github.com/Russell91/apollo/issues/5> and get the
> issue ValueError: probabilities do not sum to 1
>
> I used pickle seriealized the probs, the error can be reproduced by the
> following test code.
>
> file test.py
>
> import osimport numpy as npimport pickle
>
> probs = Nonewith open('test.pkl', 'rb') as f:
>     probs = pickle.load(f)print np.random.choice(range(len(probs)), p=probs/sum(probs))
>
> file test.pkl
>
> cnumpy.core.multiarray
> _reconstruct
> p0
> (cnumpy
> ndarray
> p1
> (I0
> tp2
> S'b'
> p3
> tp4
> Rp5
> (I1
> (I3
> tp6
> cnumpy
> dtype
> p7
> (S'f4'
> p8
> I0
> I1
> tp9
> Rp10
> (I3
> S'<'
> p11
> NNNI-1
> I-1
> I0
> tp12
> bI00
> S'\xa7cv;\xe6\x8be;}\xf3u;'
> p13
> tp14
> b.
>
> ------------------------------
>
> Maybe we can add a parameter, so the user can control the precision(such
> as 1e-8, or 1e-4) when comare sum of probs to 1.
>
> Or are there a way to overcome this issue?
>
> file numpy/random/mtrand/mtrand.pyx, line 1094 to line 1099.
>
>             if np.logical_or.reduce(p < 0):
>                 raise ValueError("probabilities are not non-negative")
>             if abs(kahan_sum(pix, d) - 1.) > 1e-8:
>                 raise ValueError("probabilities do not sum to 1")
>
>         shape = size
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6123>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by argriffing** [comment]
> You could just renormalize before calling, I guess? Would that solve your
problem? It's about the best we could do anyway...

They are normalizing it before calling. The comparison fails because the data is float32 and the absolute tolerance is 1e-8. Would it make sense to use hardcoded tolerance of 1e-8 for float64 and 1e-4 for float32?

**Comment by njsmith** [comment]
Oh, I see, sure, that would make sense to me. Or something based on
np.finfo(arr.dtype).eps.
