### ISSUE TITLE
np.rec.fromarrays doesn't infer the shape for multidimensional arrays

### ISSUE THREAD

**Issue by roger-** [numpy/numpy#6124]
The following:

``` python
a = np.arange(10)
b = np.arange(20).reshape(-1, 2) + 10

rec = np.rec.fromarrays([a, b])
```

Gives: `ValueError: array-shape mismatch in array 1`.

Should it not produce a `recarray`  with elements `rec[0] == a[0], b[0]`, etc.?

**Comment by bhagivinni** [comment]
While trying to convert MDF file to MAT file using Export in ASAMMDF module, i got this error. Can anyone help, how can we resolve this issue??

Error : `ValueError: ('array-shape mismatch in array 7',)`

**Comment by mattip** [comment]
This is as expected. a.shape is (10,), b.shape is (10,2). What dtype would you have expected? The following succeed:

```
rec = np.rec.fromarrays([a, b[:,0]])
rec = np.rec.fromarrays([a, b[:,0], b[:,1]])
```
Please reopen if needed with an expected output.
