### ISSUE TITLE
numpy.linalg.norm returns nan for an array of int16

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#6128]
Example:

```
In [1]: np.__version__
Out[1]: '1.10.0.dev0+a92c4a1'

In [2]: x = np.array([ -91, -119, -137, -132], dtype=np.int16)

In [3]: np.linalg.norm(x)
/Users/warren/local_scipy/lib/python2.7/site-packages/numpy/linalg/linalg.py:2126: RuntimeWarning: invalid value encountered in sqrt
  ret = sqrt(sqnorm)
Out[3]: nan
```

The example is from http://stackoverflow.com/questions/31685156/normalizing-vector-produces-nan-in-numpy, although it is not clear in that question if the array has type int16.

**Comment by WarrenWeckesser** [comment]
Possibly related issues:
https://github.com/numpy/numpy/issues/5626
https://github.com/numpy/numpy/issues/4851

**Comment by argriffing** [comment]
I think the explanation is https://github.com/numpy/numpy/issues/4126, so for example
```python
>>> x = np.array([ -91, -119, -137, -132], dtype=np.int16)
>>> x.dot(x)
-6901
```

**Comment by jakirkham** [comment]
So, this should also be helped by @charris's proposal ( https://github.com/numpy/numpy/issues/5626#issuecomment-83807025 ) to converting everything to floats or similar before computing.

**Comment by WarrenWeckesser** [comment]
Fixed by https://github.com/numpy/numpy/pull/7088.
