### ISSUE TITLE
Strange type resolution of numpy.sqrt

### ISSUE THREAD

**Issue by beam2d** [numpy/numpy#6134]
I found that numpy.sqrt has a strange type mapping:

```
>>> numpy.sqrt.types
['f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']
```

It causes sqrt to upcast float16 to float32. It is also strange that 'f' and 'd' appear twice. Is this definition/behavior intended?
Note: I checked it with NumPy 1.9.2 on Python 2.7.9 & 3.4.3.

**Comment by seberg** [comment]
The initial bug here is solved. There is still strange duplication (which I am not quite sure about), but there is also a second issue open about this at: gh-7897, so closing this one.
