### ISSUE TITLE
IO Error using np.tofile() or np.fromfile() with TemporaryFile

### ISSUE THREAD

**Issue by pdunc** [numpy/numpy#6158]
Hi there,

Having an issue running a test suite for a library which uses the `np.fromfile()` with a `TemporaryFile`.  It is throwing `IOError: first argument must be a string or open file`.

I was able to reproduce the issue using both `tofile` and `fromfile` - this all works happily with a 'real' file.
### Machine

```
OS:     Windows 7 SP1 (x64)
python: 2.7.8
numpy:  1.9.2
```
### Sample Code

```
import numpy as np
import tempfile

file = tempfile.TemporaryFile()

dt = np.dtype([('time', [('min', int), ('sec', int)]),
               ('temp', float)])
x = np.zeros((1,), dtype=dt)

x['time']['min'] = 10; x['temp'] = 98.25

x.tofile(file)
```
### Exception

```
Traceback (most recent call last):
  File "C:/Users/pduncan/.PyCharm40/config/scratches/scratch_1", line 12, in <module>
    x.tofile(file)
IOError: first argument must be a string or open file
```

**Comment by mattip** [comment]
No longer raises. Checked on windows with numpy 1.11, which failed, but with numpy 1.15.4 it passes. Closing. Please open a new issue if needed.

**Comment by kalvdans** [comment]
I can also confirm that it works with Python 3.6.7, numpy 1.13.3, linux64.
