### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by stray-leone** [numpy/numpy#6163]
I run  the code below
```
x= np.array([[0,1],[2,3]], dtype=np.uint8)
print x.tobytes()
```
but the error below is happen.
Do you give the reason why ndarray don't have tobytes()??
```
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
```

**Comment by seberg** [comment]
Did we ever have that? I think we got `tostring` and that gives you bytes... which of course is a misnomer, especially in python3. Or should I read this as a feature request to add tobytes? I think it was discussed before and likely not a bad idea, so if you want to add it, feel free to open a PR to discuss it.

**Comment by stray-leone** [comment]
I didn't know that the prior of v1.9 and python2.7 don't have ```tobytes()```.
I can see the ```tobytes()``` in [v1.9 document](http://docs.scipy.org/doc/numpy-1.9.1/numpy-ref-1.9.1.pdf)
If It is no problem, to use ```tostring()```, I will use ```tostring()```.
Thank you for your comment

**Comment by argriffing** [comment]
@seberg looks like it was added in https://github.com/numpy/numpy/pull/4257

**Comment by seberg** [comment]
Sorry, yeah, I tried with an old numpy version and got confused....
