### ISSUE TITLE
Cannot convert boolean arrays to ctypes with ctypeslib

### ISSUE THREAD

**Issue by clemenshug** [numpy/numpy#6176]
ctypeslib seems to be unable to convert Boolean numpy arrays to ctypes.

``` python
import numpy as np
a = np.empty(10, dtype=np.bool_)
b = np.ctypeslib.as_ctypes(a)
```

Leads to:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-3-e5712fdde6f3> in <module>()
----> 1 b = np.ctypeslib.as_ctypes(a)

/home/chug/.local/lib/python2.7/site-packages/numpy/ctypeslib.py in as_ctypes(obj)
    419         if readonly:
    420             raise TypeError("readonly arrays unsupported")
--> 421         tp = _typecodes[ai["typestr"]]
    422         for dim in ai["shape"][::-1]:
    423             tp = tp * dim

KeyError: '|b1'
```

This is using Python 2.7.10 and numpy 1.9.2 on Scientific Linux release 6.6 (Carbon).
My naive fix (I don't know much about the numpy internals and if this will break anything elsewhere) was adding the bool type to the type list in ctypeslib.py:

``` python
    simple_types = [
        ((ct.c_byte, ct.c_short, ct.c_int, ct.c_long, ct.c_longlong), "i"),
        ((ct.c_ubyte, ct.c_ushort, ct.c_uint, ct.c_ulong, ct.c_ulonglong), "u"),
        ((ct.c_float, ct.c_double), "f"),
        ((ct.c_bool, ), "b"),
    ]
```

Now this works:

``` python
In [1]: import numpy as np
In [2]: a = np.empty(10, dtype=np.bool_)
In [3]: b = np.ctypeslib.as_ctypes(a)
In [4]: print(b)
Out[4]: <numpy.ctypeslib.c_bool_Array_10 object at 0x7fd449652f80>
```

**Comment by seisdrum** [comment]
Anybody want to have a look at this? I submitted a pull request which fixes this issue for me. I used it for 3 months now and I didn't notice any negative side effects.

**Comment by ccostes** [comment]
Also having this issue. Would be nice for your PR to be accepted, but is there an easy way to use your branch in the meantime?

**Comment by eric-wieser** [comment]
PR needs a complete rework unfortunately, due to other ctypes improvements that were underway at the time it was written.
