### ISSUE TITLE
 Does Numpy or Scipy support solving the generalized singular value decomposition? 

### ISSUE THREAD

**Issue by lxduan** [numpy/numpy#6179]
Hi, does anyone know if Numpy, Scipy, or any other python library now supports solving the generalized singular value decomposition (like the `gsvd` command in MATLAB)? I could not find any command related to generalized singular value decomposition in Numpy and Scipy.

Thanks in advance!

**Comment by argriffing** [comment]
There's a scipy issue https://github.com/scipy/scipy/issues/1484 linking to a patch http://projects.scipy.org/scipy/attachment/ticket/964/lapack_svd_diffs.diff.

**Comment by lxduan** [comment]
@argriffing, thank you for the reply! May I know how I should use the patch? Based on the issue link your provided, I still have no clue. Do I have to put `lapack_gesvd.diff` some where in the scipy source code and re-compile scipy by myself?

Thank you!

**Comment by argriffing** [comment]
It looks like the LAPACK name for this is like [dggsvd](http://www.netlib.org/lapack/explore-html/dd/db4/dggsvd_8f.html) which appears to at least be wrapped in recent versions of scipy, but I'm not sure if there are user-friendly ways to use it. In any case I think this question is more in scope for scipy than for numpy.

**Comment by argriffing** [comment]
OK I think the function you want is not even wrapped at a low level in scipy -- I think the available functions are listed [here](http://docs.scipy.org/doc/scipy/reference/linalg.lapack.html). The function's interface is declared in https://github.com/scipy/scipy/blob/master/scipy/linalg/cython_lapack.pxd but I think it's not yet actually wrapped.

**Comment by lxduan** [comment]
@argriffing, thank you very much for helping dig out. I guess at this point I have to stick with the MATLAB implementation..

**Comment by jaimefrio** [comment]
I'm gping to close this, as it is not really a numpy issue. You may reach a wider audience if you mail the scipy list.
