### ISSUE TITLE
numpy array to matrix conversion overhead

### ISSUE THREAD

**Issue by eendebakpt** [numpy/numpy#6186]
There seems to be a large overhead when converting a numpy.array to a numpy.matrix. I am trying to make a small function returning a matrix, but the overhead in creating the np.matrix is really significant. See the follow code

``` python
import time
import math
import numpy as np

def rot2D(phi):
    c=math.cos(phi); 
    return np.matrix(c)

_b=np.matrix(np.zeros( (1,)))
def rot2Dx(phi):
    global _b
    r=_b.copy()
    c=math.cos(phi);
    r.itemset(0, c)
    return r

phi=.023

%timeit rot2D(phi)
%timeit rot2Dx(phi)
```

The output of the code above is

```
100000 loops, best of 3: 8.57 µs per loop
100000 loops, best of 3: 3.15 µs per loop
```

Is there a way to create a numpy.matrix object with less overhead? Using a global object and making a copy works, but is not my ideal solution.

**Comment by njsmith** [comment]
I'm not immediately aware of an answer, no, though you might get more luck
asking on the list. You could always take a crack at optimizing the
constructor, I suppose.
Note for your information that while we have no plans to remove the matrix
class at this time, we strongly recommend that everyone avoid using it
whenever possible.

**Comment by eendebakpt** [comment]
On the mailing list there have been no replies to my question. I am closing this issue. In the long run the multiplication operator (https://www.python.org/dev/peps/pep-0465/) will be the best solution.
