### ISSUE TITLE
Inplace Operation Casting Problem

### ISSUE THREAD

**Issue by MarkusPrim** [numpy/numpy#6198]
x = np.array([1, 2, 3])
x = x \* 1.2
-> array([ 1.2,  2.4,  3.6])

does not yield the same result 

x = np.array([1, 2, 3])
x *= 1.2
-> array([1, 2, 3])

For all operations (*, /, +, -) and probably all other binary operations. Is this expected behaviour?

Tested with numpy 1.9.2 and 1.8.0

**Comment by argriffing** [comment]
Yes but in newer numpy versions this will give a TypeError. There are also weirder things that can happen with inplace operations, for example https://github.com/numpy/numpy/issues/1683.

```python
>>> import numpy as np
>>> np.__version__
'1.10.0.dev0+9232200'
>>> x = np.array([1, 2, 3])
>>> y = x[::-1]
>>> x
array([1, 2, 3])
>>> y
array([3, 2, 1])
>>> x += y
>>> x
array([4, 4, 7])
>>> z = np.array([1.2, 2.4, 3.6])
>>> x += z
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

**Comment by seberg** [comment]
All of the issues mentioned here seem fixed. In-place ops are now done with safe casting and overlap detection has also been implemented.

**Comment by charris** [comment]
Just want to say thank you for cleaning up these issues.

**Comment by seberg** [comment]
Next time, will try to remember to also add tags to the ones that are more tricky...
