### ISSUE TITLE
Clarify return value for rfft2

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#6201]
The following example may leave users perplexed:

``` python
In [6]: image = np.random.random((10,10))

In [7]: np.fft.fft2(image).shape
Out[7]: (10, 10)

In [8]: np.fft.rfft2(image).shape
Out[8]: (10, 6)
```

After all, `rfft2` is just meant to be a version of `fft2` that is more efficient for real input. Now I'm assuming that what is different is that the negative frequencies are missing along one axis for rfft2 since they are redundant, but at the same time it seems inconsistent to do it along one axis and not the other. The asymmetric array is due to the fact the 2-d rfft is done as a 1d rfft followed by a normal fft.

Ideally, `rfft2` should be fixed to actually return a complete `(10,10)` fourier transform to avoid requiring the user to manually mirror the values to make it back into a (10,10) array. `rfft2` should be usable as a drop-in replacement for `fft2`.

However, I presume this could break a lot of code, so as a plan B, `rfft2` could be given an optional argument to return the complete array (defaulting to `False` to preserve backward-compatibility).

Finally, either way, the docstring of `rfft2` should definitely be clarified to explain the shape of the output.

If others agree, I can try and implement this.

**Comment by rainwoodman** [comment]
I thought it is a tradition (if not a definition) that 'real' fft returns just the independent half of the transform. The inverse real transform irfft, takes the independent half as the input.

I suggest you read:
http://www.fftw.org/doc/Multi_002ddimensional-Transforms.html#Multi_002ddimensional-Transforms

"We could instead have cut any other dimension in half, but the last dimension proved computationally convenient." Notice the word 'any'. It can't be on both axes.

**Comment by astrofrog** [comment]
@rainwoodman - in that case, I would still suggest that the docstring should be clarified - I've encountered quite a few people who were not aware of this convention.

**Comment by rainwoodman** [comment]
A fair amount of documentation can be written on this, namely, which modes in the real FFTs are independent and how they are stored. -- I happen to be playing with this recently, so I'd draft up something soon for you to review.

**Comment by mattip** [comment]
Docstring of `rfft2` refers users to [`rfftn`](http://www.numpy.org/devdocs/reference/generated/numpy.fft.rfftn.html#numpy.fft.rfftn), which specifies the output shape. Closing. If there is a concrete suggestion of documentation improvements, please open a new issue.
