### ISSUE TITLE
Scipy compile broken for dual arch OSX at numpy >= 1.9.0

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#6204]
Our standard way to compile scipy is with the dual-arch gfortran 4.2.3 in https://github.com/MacPython/scipy-wheels/tree/master/archives and other places.

Scipy compiles without error against numpy==1.8.2, but raises the following error among many other warnings compiling against numpy==1.9.0 and later:

```
ld: warning: can't find atom for N_GSYM stabs rowns:G(0,30) in build/temp.macosx-10.6-intel-2.7/libodepack.a(prja.o)
ld: warning: tentative definition of '_ls0001_' with size 1904 from 'build/temp.macosx-10.6-intel-2.7/libodepack.a(prja.o)' is being replaced by real definition of smaller size 1900 from 'build/temp.macosx-10.6-intel-2.7/libodepack.a(blkdta000.o)'
ld: warning: can't find atom for N_GSYM stabs ls0001:G(0,12)=s1900rowns:(0,13)=ar(0,4);0;208;(0,5),0,13376;ccmax:(0,5),13376,64;el0:(0,5),13440,64;h:(0,5),13504,64;hmin:(0,5),13568,64;hmxi:(0,5),13632,64;hu:(0,5),13696,64;rc:(0,5),13760,64;tn:(0,5),13824,64;uround:(0,5),13888,64;iownd:(0,14)=ar(0,4);0;13;(0,4),13952,448;iowns:(0,15)=ar(0,4);0;5;(0,4),14400,192;icf:(0,4),14592,32;ierpj:(0,4),14624,32;iersl:(0,4),14656,32;jcur:(0,4),14688,32;jstart:(0,4),14720,32;kflag:(0,4),14752,32;l:(0,4),14784,32;meth:(0,4),14816,32;miter:(0,4),14848,32;maxord:(0,4),14880,32;maxcor:(0,4),14912,32;msbp:(0,4),14944,32;mxncf:(0,4),14976,32;n:(0,4),15008,32;nq:(0,4),15040,32;nst:(0,4),15072,32;nfe:(0,4),15104,32;nje:(0,4),15136,32;nqu:(0,4),15168,32;; in build/temp.macosx-10.6-intel-2.7/libodepack.a(solsy.o)
ld: warning: can't find atom for N_GSYM stabs rowns:G(0,13) in build/temp.macosx-10.6-intel-2.7/libodepack.a(solsy.o)
ld: in build/temp.macosx-10.6-intel-2.7/libodepack.a(solsy.o), sectionForAddress(0x770) address not in any section for architecture i386
collect2: ld returned 1 exit status
ld: warning: ignoring file build/temp.macosx-10.6-intel-2.7/libodepack.a, file was built for archive which is not the architecture being linked (x86_64): build/temp.macosx-10.6-intel-2.7/libodepack.a
ld: warning: ignoring file build/temp.macosx-10.6-intel-2.7/libmach.a, file was built for archive which is not the architecture being linked (x86_64): build/temp.macosx-10.6-intel-2.7/libmach.a
ld: warning: ignoring file /usr/local/lib/gcc/i686-apple-darwin8/4.2.3/libgfortranbegin.a, file was built for archive which is not the architecture being linked (x86_64): /usr/local/lib/gcc/i686-apple-darwin8/4.2.3/libgfortranbegin.a
ld: warning: ignoring file /usr/local/lib/gcc/i686-apple-darwin8/4.2.3/libgcc.a, file was built for archive which is not the architecture being linked (x86_64): /usr/local/lib/gcc/i686-apple-darwin8/4.2.3/libgcc.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /var/tmp//ccvbVMIh.out (No such file or directory)
error: Command "/usr/local/bin/gfortran -Wall -g -arch i686 -arch x86_64 -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.6-intel-2.7/scipy/integrate/_odepackmodule.o -L/usr/local/lib/gcc/i686-apple-darwin8/4.2.3 -Lbuild/temp.macosx-10.6-intel-2.7 -lodepack -lmach -lgfortran -o build/lib.macosx-10.6-intel-2.7/scipy/integrate/_odepack.so -Wl,-framework -Wl,Accelerate" failed with exit status 1
```

**Comment by charris** [comment]
Any idea what all that means? Seeing as this started in 1.9 I assume you are just now trying to upgrade.

**Comment by rgommers** [comment]
I have a memory of a discussion about breaking gfortran <4.4 in numpy 1.9.x. IIRC some performance improvement by @juliantaylor that depended on compiler version. I just can't find it anymore I'm afraid.

The Homebrew 4.9 gfortran does work well with newer numpy.

**Comment by matthew-brett** [comment]
I can build current numpy trunk fine with gfortran 4.2.3, but I do get the error I listed in http://numpy-discussion.10968.n7.nabble.com/ANN-Numpy-1-10-0b1-release-td40785.html#a40809 .  Could that be what you mean?

I think homebrew gfortran is a bit tricky to build with, because we need dual arch binaries, so even if gfortran can make 32-bit binaries, we have to build separate 32 and 64 bit builds and then fuse them to make the shipped wheel.

**Comment by matthew-brett** [comment]
In fact I don't get the numpy test error when building with gfortran 4.8 from homebrew.

**Comment by rgommers** [comment]
@matthew-brett I don't remember. Searching for the error in your second test failure doesn't turn up anything. But I'm still pretty sure that I knew already that gfortran 4.2.3 was broken, and that we decided to not fix it or left the discussion unresolved.

**Comment by rgommers** [comment]
@matthew-brett is this still an issue? If so, how did you work around it for the current OS X wheels?

**Comment by matthew-brett** [comment]
Actually, numpy now compiles and passes all tests with gfortran 4.2.3, but same error for scipy.

The current wheels are built against numpy 1.7.1 (oldest compatible version) so I guess we'll hit this one when we need to build against numpy 1.9.

**Comment by njsmith** [comment]
Probably this is already obvious to everyone who works on the osx stuff,
but I'll ask the silly question... If it works with newer gfortran, then is
there some reason you can't use that?

**Comment by matthew-brett** [comment]
That's up in https://github.com/numpy/numpy/issues/6204#issuecomment-130865516 - it's easier to build with a dual-arch gfortran.

**Comment by mattip** [comment]
Still relevant?

**Comment by matthew-brett** [comment]
No, not relevant any more.  Thanks for the reminder.
