### ISSUE TITLE
numpy 1.9.x on Py3 modifies `environ`

### ISSUE THREAD

**Issue by dvarrazzo** [numpy/numpy#6213]
See issue dvarrazzo/py-setproctitle#42

It seems that numpy 1.9 on Python 3 modifies the `environ` variable. Reproduced on Debian Jessie and OS X 10.10.4. Doesn't happen on numpy 1.8 and on Python 2. Info to verify the behaviour in the issue above.

This breaks `setproctitle`, unless `setproctitle` is imported before `numpy`, in which case I wonder if `numpy` won't break...

Is this a known behaviour of numpy 1.9 or did it happen accidentally? Is there a workaround to avoid clobbering `environ`?

For a rationale about why clobbering `environ` could be undesirable, take a look at dvarrazzo/py-setproctitle#15.

**Comment by pv** [comment]
This looks like it's relying on undefined behavior:
.
https://github.com/dvarrazzo/py-setproctitle/blob/master/src/spt_setup.c#L151
.
The `environ` pointer can be modified already by first setenv() call,
even if the environment is restored afterward. setenv()/unsetenv() is
called by numpy on import to control OpenBLAS behavior, so it is
intentional.

**Comment by njsmith** [comment]
Yeah, this isn't something weird numpy in particular is doing, this is just
how setenv works. I don't think you can ask that no python library ever
modify the environment, so the strategy your setproctitle implementation
currently uses isn't going to work unless you tell people that it has to be
the first thing imported.
.
There are some potential alternative strategies available:
http://tycho.ws/blog/2015/02/setproctitle.html
or you could consider submitting a patch to python itself to make it
possible to get ahold of argv* and friends.

**Comment by dvarrazzo** [comment]
Thank you for the clarification. I actually didn't know `environ` was moved after `setenv` calls. In this case importing `setproctitle` before `numpy` is all it takes and `numpy` should suffer no side effect.

@njsmith thank you for the link, will take a look into it.

Closing the issue, have a good day.
