### ISSUE TITLE
Advanced indexing using arrays created by as_strided

### ISSUE THREAD

**Issue by cytsai** [numpy/numpy#6221]
Instead of using <code>np.indices</code>, I tried the following method which creates indices for advanced indexing using as_strided, but it behaved quite strange (at least in NumPy 1.9.2). E.g. <code>C=3</code> was fine but <code>C=4</code> gave error (out-of-bound IndexError). I was using NumPy 1.9.2 (MKL) under Python 2.7.10 (Anaconda 2.3.0 64-bit), and my system's NumPy 1.9.2 (Ubuntu 12.04 with Python 2.7.3) also got the same problem. However, NumPy 1.6.1 (on another machine) seemed to be fine.

```
import numpy as np
from numpy.lib.stride_tricks import as_strided

def indices(shape):
	
	I = ()
	for d, D in enumerate(shape): I = I + (as_strided(np.arange(D), shape, (0,)*d+(8,)+(0,)*(len(shape)-d-1)), )
	return I

C = 4
X = np.random.randn(10,55,C,C,49)

I = np.argmax(X,-1)
M1 = X[indices(I.shape) + (I,)]
M2 = np.amax(X,-1)
print np.array_equal(M1,M2)
```

**Comment by seberg** [comment]
Bah, now I wanted to sleep long and nice and then this....

Anyway, the diff below fixes the bug, probably worth to check the other indexing related usages of the inner strides. Plus I should have known better, but there should be a warning there somewhere that while the pointer does not change the values *do* change (for `NpyIter_GetInnerStrideArray`).

```diff
--- a/numpy/core/src/multiarray/mapping.c
+++ b/numpy/core/src/multiarray/mapping.c
@@ -2501,7 +2501,7 @@ PyArray_MapIterCheckIndices(PyArrayMapIterObject *mit)
     NpyIter_IterNextFunc *op_iternext;
     npy_intp outer_dim, indval;
     int outer_axis;
-    npy_intp itersize, iterstride;
+    npy_intp itersize, *iterstride;
     char **iterptr;
     PyArray_Descr *intp_type;
     int i;
@@ -2572,7 +2572,7 @@ PyArray_MapIterCheckIndices(PyArrayMapIterObject *mit)
 
         NPY_BEGIN_THREADS_NDITER(op_iter);
         iterptr = NpyIter_GetDataPtrArray(op_iter);
-        iterstride = NpyIter_GetInnerStrideArray(op_iter)[0];
+        iterstride = NpyIter_GetInnerStrideArray(op_iter);
         do {
             itersize = *NpyIter_GetInnerLoopSizePtr(op_iter);
             while (itersize--) {
@@ -2583,7 +2583,7 @@ PyArray_MapIterCheckIndices(PyArrayMapIterObject *mit)
                     NpyIter_Deallocate(op_iter);
                     return -1;
                 }
-                *iterptr += iterstride;
+                *iterptr += *iterstride;
             }
         } while (op_iternext(op_iter));
```

**Comment by seberg** [comment]
Actually, the tags look worse then it is probably, I looked wrong on first sight. There is only one more occurance that *might* be wrong, but it is in the boolean indexing code which mark wrote. I think it is very likely correct because no buffering is used in that code. @mwiebe do you happen to know of the top of your head that the `inner strides array` does never change when buffering is not enabled, I do not see how it would right now, just to make sure?

The other usages all use pointers and are fine even with buffering.

**Comment by mwiebe** [comment]
@seberg the strides are constant in the unbuffered case, you're right.

**Comment by seberg** [comment]
@cytsai, opened a pull request that will fix it. By the way in your example (though I guess it was just that), there is no reason to actually repeat the arrays with stride 0, you can just leave the dimension with size 1.
It will be faster anyway if you leave the broadcasting of the indices to the indexing machinery.

**Comment by cytsai** [comment]
@seberg, thank you very much! and you're right, I should have just left the broadcasting to NumPy. it's indeed faster.
