### ISSUE TITLE
Bug in assignment with integer indexing to array subset

### ISSUE THREAD

**Issue by arahlin** [numpy/numpy#6225]
This fails with the expected `ValueError`:

```
>>> arr = np.zeros(10)
>>> arr[5:7] = np.arange(1,10)
```

As does this:

```
>>> idx = np.zeros(10, dtype=bool)
>>> idx[5:7] = True
>>> arr[idx] = np.arange(1,10)
```

However, this silently completes the assignment:

```
>>> arr[[5,6]] = np.arange(1,10)
>>> arr
array([ 0.,  0.,  0.,  0.,  0.,  1.,  2.,  0.,  0.,  0.])
```

As does this:

```
>>> arr[np.arange(10)] = [1,2]
>>> arr
array([ 1.,  2.,  1.,  2.,  1.,  2.,  1.,  2.,  1.,  2.])
```

I am running numpy 1.9.2 with python 2.7.8.  According to the [documentation](http://docs.scipy.org/doc/numpy/user/basics.indexing.html#assigning-values-to-indexed-arrays) the last two examples should fail because the index array and the assignment array are not shape consistent.

**Comment by seberg** [comment]
This is only there for backward compatibility with weird code. Yes, and they actually *do* fail, please rerun your examples with deprecation warnings enabled (for example in a python shell with `python -Wall` I think).

**Comment by arahlin** [comment]
I wouldn't call a warning a failure, especially one that isn't enabled by default.  Regardless, maybe the documentation should point out this behavior?

**Comment by seberg** [comment]
@arahlin, I don't know... You could add that this is being deprecated, it won't be there in a release or two, and that the warning is not visible is not our choice, it is pythons choice to not show these warnings.
I am fine with adding something to the docs about this being the case right now, though basically it was an undocumented "feature/bug" for years, so I did not bother to change anything when we deprecated it.

**Comment by seberg** [comment]
As mentioned a few years ago, this issue was even then in deprecation and now it is fixed. These assignements now all raise the correct ValueError.
