### ISSUE TITLE
”Two fields with the same name” should tell user which fieldname

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#6232]
I am creating a structured dtype with 126 fields, constructed from a table defining a particular file format.  This results in a `ValueError: two fields with the same name`, but it doesn't tell me what the fieldname is that occurs twice (or more).  It would be quite helpful if it did.

```
In [54]: len(xx)
Out[54]: 126

In [55]: dtype(xx)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-55-06d02af83c75> in <module>()
----> 1 dtype(xx)

ValueError: two fields with the same name
```

**Comment by jaimefrio** [comment]
If anyone wants to give a shot at this, it's C code, but all that needs doing is modifying the `PyErr_SetString` call [here](https://github.com/numpy/numpy/blob/maintenance/1.10.x/numpy/core/src/multiarray/descriptor.c#L512) to use `PyErr_Format` I guess.

**Comment by yashmehrotra** [comment]
I would like to work on this bug, @gerritholl , can you also please add the steps to recreate the bug as I need to test the changes I made.
Thanks.

**Comment by gerritholl** [comment]
On 24 August 2015 at 12:13, Yash Mehrotra <notifications@github.com> wrote:
>
> I would like to work on this bug, @gerritholl , can you also please add the steps to recreate the bug as I need to test the changes I made.

In [3]: numpy.dtype([("A", "f8"), ("B", "f8"), ("C", "f8"), ("A", "f8")])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-efce51eda5df> in <module>()
----> 1 numpy.dtype([("A", "f8"), ("B", "f8"), ("C", "f8"), ("A", "f8")])

ValueError: two fields with the same name


Desired error message would add something like "field 'A' occurs more
than once" or so.
