### ISSUE TITLE
Negative dtype.itemsize

### ISSUE THREAD

**Issue by frejanordsiek** [numpy/numpy#6235]
While tracking down something else, I stumbled upon a way to make a `dtype` with an `itemsize` that is negative, which is surely a bug. Essentially, with a structured `ndarray` (one with fields), while size checking is done on each field individually and probably on their sum, it seems that overflow checking is not done.

Let X either be the bit size of the internal representation of `itemsize`. So far, I have found that even in 64-bit Python (both 2.x and 3.x), it can be 32-bit or 64-bit depending on the build (is there a build option controlling it when Numpy is built?).

So if you try to make a structured Numpy `ndarray` with one field that is too big by one byte, an error is thrown like it should

``` python
>>> numpy.dtype([('a','int8', 2**(X - 1))])
ValueError: invalid shape in fixed-type tuple.
```

Put it at the maximum size and there is no problem (you will note that I am running the examples from a build where X is 64, but it was 32 bit on the machine I was using earlier today) as it should.

``` python
>>> numpy.dtype([('a','int8', 2**(X - 1) - 1)])
dtype([('a', 'i1', (9223372036854775807L,))])
```

But make a second field of the same size and one gets a negative value of `itemsize`

``` python
>>> dt = numpy.dtype([('a','int8', 2**(X - 1) - 1), ('b', 'int8', 2**(X - 1) - 1)])
>>> dt.itemsize
-2
```

Which should not be allowed. There was an overflow that was not detected.

I do not know what a negative `itemsize` will when the dtype is passed to other Numpy functions or other packages. It is hard to imagine it happening when `X == 64` on accident, but when `X == 32` it is pretty easy, say one got a MAT file from someone with a structure with a total size greater than 2 GB but each field smaller than 2 GB and tries to import it as a structured `ndarray` with SciPy (haven't tested this yet).

**Comment by seberg** [comment]
No, there is no option to control it, the itemsize is hardwired to be a C-int in some of the structs. There is definitely an overflow check missing here, even if the type was `ssize_t`/`intp`.

**Comment by njsmith** [comment]
It's pretty nasty, too, because while itemsize probably ought to be intp,
there's definitely no way to fix it without a major abi break. So I guess
we just have to live with a 2 GiB limit on itemsize for the foreseeable
future. Fortunately this is not a very harsh limit...

**Comment by jaimefrio** [comment]
But we all agree that the proper thing to do here is to raise an error, right?

**Comment by seberg** [comment]
Of course.

**Comment by njsmith** [comment]
Yeah

**Comment by frejanordsiek** [comment]
You are definitely right about it being 32-bit. Found another problem in the process actually. On my 64-bit Python 3.x system (64-bit intp), I can make a structured ndarray with a single field with a negative value:

``` python
>>> import numpy
>>> dt = numpy.dtype([('a','int8', 2**(64 - 1) - 1)])
>>> dt.itemsize
-1
```

So it seems that the only size checking that is done is to make sure that each field of the resulting dtype isn't bigger than an ``intp``. This field is clearly bigger than an ``intc`` but is allowed.

**Comment by thoth291** [comment]
@njsmith When do you think this limitation of 2GB limit on itemsize will be resolved?
What are the workarounds?
Is there anyway to inherit a special class from dtype to handle this buffer limit properly (and by doing so - keeping backward compatibility)?
This limit is a bit inconvenient when one deals with structure(record) of arrays which size may vary at run-time.

**Comment by njsmith** [comment]
I don't know of any workarounds, no, except to restrict oneself to <2GB
itemsizes. I'm not aware of any plans to lift the limitation, either --
it's rather difficult to do, because simply changing the size of the field
would be an ABI break. Maybe there's some cleverness that would be possible
(the next field is the somewhat meaningless 'alignment' field whose storage
could be stolen and repurposed? but probably this would break as much or
more code as changing the field size directly), or maybe it'll be possible
eventually to sneak the change in alongside some other ABI break, or maybe
we'll eventually grow a better system for managing ABI breaks. But I doubt
this change will be the one to force it, because the need for 2GB dtypes is
pretty rare.

On Tue, Dec 8, 2015 at 11:59 AM, Anar Yusifov <notifications@github.com>
wrote:

> @njsmith <https://github.com/njsmith> When do you think this limitation
> of 2GB limit on itemsize will be resolved?
> What are the workarounds?
> Is there anyway to inherit a special class from dtype to handle this
> buffer limit properly (and by doing so - keeping backward compatibility)?
> This limit is a bit inconvenient when one deals with structure(record) of
> arrays which size may vary at run-time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6235#issuecomment-162997431>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by seberg** [comment]
I think there is a related bug still open elsewhere, but this one seems fixed (all examples now raise an error).
