### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by trampas** [numpy/numpy#6237]
I am running numpy 1.9.2 on a Wandboard (quad ARM processor). If I open python and type "import numpy" immediately my CPU usage pegs for three of the four processors. 

I am not sure if this is a bug or not, but have not found anything googling the problem. 

Thanks

**Comment by njsmith** [comment]
It's certainly not an intended behavior, but it's hard to know where the
problem could be without more details.
.
The only thing I can think of immediately that might do that is if you
linked numpy to some BLAS library that is attempting to start a thread pool
but is broken somehow. But really that's just a wild guess.
.
Can you give any more details about how your numpy was built and installed,
and can you get a stack trace of what those cpus are doing?
.
Something like
* Run the command: gdb --args python -c 'import numpy; import time;
time.sleep(9999)'
* Type 'run' at the gdb prompt and hit enter
* Check your cpu monitor to make sure the problem is happening
* hit control-c, you should get a gdb prompt
* type 'thread apply all bt full' at the gdb prompt and hit enter

**Comment by trampas** [comment]
The install was "pip install numpy" from Debian repo.

If you can provide some detail instructions on generating stack trace (new
subject for me)  I will do it right away.

Thanks!
Trampas

**Comment by njsmith** [comment]
> If you can provide some detail instructions on generating stack trace (new subject for me) I will do it right away.

Umm... I just did? Are they unclear?

**Comment by trampas** [comment]
Sorry that looked like email header to my eyes...

The CPU usage went up and then I got the error below.

root@arm:/tti/mobile_wasp/development/mark1# gdb --args python -c 'import
numpy; import time; time.sleep(9999)'
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/python -c import\ numpy\;\ import\ time\;\
time.sleep\(9999\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library
"/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x7643a460 (LWP 32297)]
[New Thread 0x75c3a460 (LWP 32298)]
[New Thread 0x7443a460 (LWP 32299)]

Program received signal SIGILL, Illegal instruction.
0x719b0e08 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0

**Comment by njsmith** [comment]
And if you then do 'thread apply all bt full', what do you get?

**Comment by trampas** [comment]
I put in the nostop on the SIGILL:

root@arm:/tti/mobile_wasp/development/mark1# gdb --args python -c 'import
numpy; import time; time.sleep(9999)'
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
(gdb) handle SIGILL nostop
Signal        Stop    Print    Pass to program    Description
SIGILL        No    Yes    Yes        Illegal instruction
(gdb) run
Starting program: /usr/bin/python -c import\ numpy\;\ import\ time\;\
time.sleep\(9999\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library
"/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x7643a460 (LWP 32469)]
[New Thread 0x75c3a460 (LWP 32470)]
[New Thread 0x7443a460 (LWP 32471)]

Program received signal SIGILL, Illegal instruction.
^C
Program received signal SIGINT, Interrupt.
0x76e83592 in select () at ../sysdeps/unix/syscall-template.S:81
81    ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) thread apply all bt full

Thread 4 (Thread 0x7443a460 (LWP 32471)):
#0  0x76e5be86 in gettimeofday () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x76617218 in ?? () from /usr/lib/libopenblas.so.0
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0x75c3a460 (LWP 32470)):
#0  0x76e5be86 in gettimeofday () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x76617218 in ?? () from /usr/lib/libopenblas.so.0
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x7643a460 (LWP 32469)):
#0  0x76e5be86 in gettimeofday () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x76617218 in ?? () from /usr/lib/libopenblas.so.0
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x76ff8000 (LWP 32466)):
---Type <return> to continue, or q <return> to quit---
#0  0x76e83592 in select () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x00146b88 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) Quit
(gdb)

**Comment by njsmith** [comment]
Oh, so openssl calls illegal instructions *on purpose*? Of course it does...
.
Anyway, about your actual problem: the part where gdb fails at producing a
backtrace is a little weird, not sure if that indicates some deeper problem
or not, but this does at least seem to confirm my initial guess that the
problem seems to be in your build of openblas, not numpy itself. Things
that I would do next:
* file a bug with Debian on openblas, with a link to this thread
* use update-alternatives to try switching to another BLAS and see what
happens (details:
https://wiki.debian.org/DebianScience/LinearAlgebraLibraries)

**Comment by seberg** [comment]
Random guessing, openblas has some memory warmup option, I am not sure what it does exactly, but maybe that could cause a big cpu usage?

**Comment by seberg** [comment]
As a reference to support hte idea, this report from Julian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=709224

**Comment by njsmith** [comment]
Notice that says that Debian disabled this in 2013 though...

**Comment by rstecanella** [comment]
I had the exact same problem and this is what I did to solve it:
$ sudo apt-get install libatlas3-base
$ sudo update-alternatives --config libblas.so.3
choose the libatlas option
$ sudo update-alternatives --config liblapack.so.3
choose the libatlas option
$ sudo aptitude purge libopenblas-{base,dev}

**Comment by kroushl** [comment]
@rsteca thank you! This solved my problem on a Raspberry Pi (affecting both numpy and octave).

**Comment by seberg** [comment]
Not sure if the initial problem was this or not, but I will assume unless someone protests. I guess people will still be able to find the stuff when it is closed.

**Comment by matthew-brett** [comment]
Sorry to comment on this closed issue - but is there a good and visible page suggesting these kinds of simple optimizations for numpy?   I couldn't see anything very good in a quick search.  Maybe a page called "Optimizing numpy for performance"?

**Comment by KOLANICH** [comment]
Eomeone, please rename this issue to "python interpreter consumes 100% cpu after importing numpy".

**Comment by seberg** [comment]
Renamed the issue, but if someone knows other things to note somewhere, maybe create a wiki page?

**Comment by f0k** [comment]
> Renamed the issue, but if someone knows other things to note somewhere, maybe create a wiki page?

Not sure, might be overkill. For now this issue serves as a good landing page, so I will add my two cents:
I'm seeing the same behaviour on a Raspberry Pi (multiple threads spinning with gettimeofday calls). I can add that the problem disappears when enforcing OpenBLAS to use a single thread:
```
$ time OMP_NUM_THREADS=1 python -c 'import numpy; import time; time.sleep(5)'

real    0m5.637s
user    0m0.540s
sys     0m0.090s
$ time OMP_NUM_THREADS=2 python -c 'import numpy; import time; time.sleep(5)'

real    0m5.634s
user    0m4.950s
sys     0m11.890s
```
So it's quite surely not a numpy issue, and depending on what you want to do, this could be a suitable workaround. I assume updating OpenBLAS would help as well, but I won't investigate for now.
