### ISSUE TITLE
numpy.arange miscounts when step is large relative to value past stop

### ISSUE THREAD

**Issue by kawochen** [numpy/numpy#6238]
```
 In [14]: len(numpy.arange(0, 10000000000000001, 100000000000000))
Out[14]: 101

In [15]: len(numpy.arange(0, 100000000000000000001, 1000000000000000000))
Out[15]: 100
```

**Comment by jaimefrio** [comment]
To calculate the number of items, a rounded up division of `(stop - start) / step` is performed. This is done in floating point, and the loss of precision is what caused your missing last entry. If all three values are integers, we could alternatively take advantage of Python's arbitrary precision integers and use the `(stop - start - 1) // step + 1` rounded up integer division formula, which should fix your problem.

**Comment by kawochen** [comment]
Thanks.  I suspected it was some kind of floating point arithmetic at work as well, but couldn't find the source code for that function.  Can you point me to it?  The doc says when all three are integers it does the same thing as the built-in `range`, but in this case it's different.

**Comment by jaimefrio** [comment]
It's written in C. The function that ultimately creates the `arange` array is [`PyArray_ArangeObj`](https://github.com/numpy/numpy/blob/maintenance/1.10.x/numpy/core/src/multiarray/ctors.c#L3045), but the length is calculated by the auxiliary function [`_calc_length`](https://github.com/numpy/numpy/blob/maintenance/1.10.x/numpy/core/src/multiarray/ctors.c#L2971) called by it.

**Comment by julianeagu** [comment]
I am getting a (similar?) bug:

For example, I get an extra number in this case:
```
x = np.arange(0.75,0.8,0.01) 
print x
[ 0.75  0.76  0.77  0.78  0.79  0.8 ]
```
but this works fine:
```
x = np.arange(0.75,1.0,0.01)
print x
[ 0.75  0.76  0.77  0.78  0.79  0.8   0.81  0.82  0.83  0.84  0.85  0.86 0.87  
0.88  0.89  0.9   0.91  0.92  0.93  0.94  0.95  0.96  0.97  0.98 0.99]
```

I'm using numpy version 1.11.2.

**Comment by charris** [comment]
The problem is that `.8` and `.01` are not exactly representable in floating point, so the actual numbers used are not what they look like. For instance
```
 In [2]: print "%25.20f" % .8
   0.80000000000000004441
```
The way to do this sort of thing is to use `linspace` or integers and divide
```
In [1]: linspace(.75, .8, 5, endpoint=False)
Out[1]: array([ 0.75,  0.76,  0.77,  0.78,  0.79])

In [2]: arange(75, 80)/100.
Out[2]: array([ 0.75,  0.76,  0.77,  0.78,  0.79])
```
