### ISSUE TITLE
Reference leak when comparing structured scalars

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#6250]
If you execute the following code, you'll it leaks a reference to the array:

```
recordtype = np.dtype([('a', np.float64), ('b', np.int32), ('d', (np.str, 5))])

a = np.zeros(2, dtype=recordtype)

print(sys.getrefcount(a))
u, v = a[0], a[1]
u == v
del u, v
gc.collect()
print(sys.getrefcount(a))
```

The leak disappears if you remove the comparison (`u == v`) or if you remove the character string member in the dtype (the `d` member here). I've tried to diagnose this but I'm ending up completely lost in the comparison logic (which creates multiple temporary arrays).

**Comment by pitrou** [comment]
Note this is a regression in 1.10. 1.9.2 is fine.

**Comment by ahaldane** [comment]
I thought this might be due to structured array changes, but seems it has to do with string comparison.

Git bisect says it happens in 4b1f508a57549d80 if I have done it correctly, but the fix isn't obvious to me. @njsmith, maybe you see something?

**Comment by pitrou** [comment]
That must definitely be it. There is a missing `Py_DECREF(array_other)` after the call to `_strings_richcompare`.

It is astonishing the number of temporary arrays that get created here:
- one temporary 0-d array is created for each scalar
- one temporary array is created for each field in the structured dtype
- and then one temporary array is created when comparing the string fields...

**Comment by njsmith** [comment]
Yeah, that's definitely it. Good catch, thank you! I'll get a patch
together later today if no one beats be to it.
.
And yeah, that code is extremely inefficient. AFAICT the only way to fix it
though is to fix the issue with ufunc loops not having access to dtype
objects as discussed in the other thread, so that we can start using the
dtype machinery for string and void types.

**Comment by njsmith** [comment]
[start using the *ufunc* machinery, I meant, in that last comment... i.e. instead of having this weird richcompare stuff we should just make `np.equal` work for these arrays, and the blocker on that is what I said.]

**Comment by pitrou** [comment]
Well, the irony is that the code here compares scalars, so the indirection through arrays ideally shouldn't be necessary at all ;) That's a separate discussion anyway.
