### ISSUE TITLE
 np.linalg.pinv under ubuntu/anaconda

### ISSUE THREAD

**Issue by SteliosFly** [numpy/numpy#6253]
np.linalg.pinv(covR) returns wrong results when covR > (1000x1000).  
The above only happens under ubuntu (under windows it worked ok). I have not tested it on a second linux machine. 

I temporary resolved the problems by switching  np.linalg.pinv(covR) to  scipy.linalg.pinv2(covR). 

p.s. the problem starts when covR becomes (1001x1001), up to (1000x1000) everything is ok.

**Comment by njsmith** [comment]
This is almost certainly a problem with whatever BLAS/LAPACK library numpy is using, which depends on how numpy was installed. Is the numpy you're using from Ubuntu, or from Anaconda as the title says? If it's Anaconda, is it the regular download, or the MKL-enabled version?

What does `np.__config__.show()` print? What do you get if you go to the command line and run `ldd $(python -c 'import numpy; print(numpy.core._dotblas.__file__)')`?

**Comment by SteliosFly** [comment]
Hello NJ, thanks for the prompt reply!
I am using anaconda under ubuntu (and I agree with you this could very well be a Fortran 77 stile Maximum matrix allocation compilation flag set to 1000). The scary part is that I didn't got a failure, I simply got wrong results!  

Below you can see the output of the aforementioned commands:

numpy.core._dotblas.__file__
/home/stelios/anaconda/lib/python2.7/site-packages/numpy/core/_dotblas.so


lapack_opt_info:
    libraries = ['lapack', 'f77blas', 'cblas', 'atlas']
    library_dirs = ['/home/stelios/anaconda/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.4\\""')]
    language = f77
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_blas_info:
    libraries = ['f77blas', 'cblas', 'atlas']
    library_dirs = ['/home/stelios/anaconda/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.4\\""')]
    language = c
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['f77blas', 'cblas', 'atlas']
    library_dirs = ['/home/stelios/anaconda/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.4\\""')]
    language = c
atlas_info:
    libraries = ['lapack', 'f77blas', 'cblas', 'atlas']
    library_dirs = ['/home/stelios/anaconda/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.4\\""')]
    language = f77
atlas_3_10_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE

**Comment by SteliosFly** [comment]
Forgot this one:
ldd $(python -c 'import numpy; print(numpy.core._dotblas.__file__)')
	linux-vdso.so.1 =>  (0x00007fff29189000)
	libpython2.7.so.1.0 => /home/stelios/anaconda/lib/python2.7/site-packages/numpy/core/../../../../libpython2.7.so.1.0 (0x00007fc31ccc6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc31caa8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc31c6e3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc31c4df000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fc31c2dc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc31bfd6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc31d717000)

**Comment by njsmith** [comment]
Not so much a fortran 77 thing as some bug in your BLAS/LAPACK library
where it's trying to use one algorithm for smaller arrays and a different
one for larger arrays because of some cache optimization tricks or
something -- we see bugs like this in the underlying libraries all the
time, unfortunately :-(.
.
I think you need to take this up with the Anaconda devs -- there *might* be
a numpy bug here, but I don't think there's much we can do to help or track
it down without more information on what exactly they're doing with their
numpy builds and the ability to run tests against the underlying libraries
directly, and unfortunately their numpy build configuration is currently
proprietary :-/

On Thu, Aug 27, 2015 at 10:58 AM, SteliosFly <notifications@github.com>
wrote:

> Forgot this one:
> ldd $(python -c 'import numpy; print(numpy.core.*dotblas.__file_*)')
> linux-vdso.so.1 => (0x00007fff29189000)
> libpython2.7.so.1.0 =>
> /home/stelios/anaconda/lib/python2.7/site-packages/numpy/core/../../../../libpython2.7.so.1.0
> (0x00007fc31ccc6000)
> libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
> (0x00007fc31caa8000)
> libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc31c6e3000)
> libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc31c4df000)
> libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fc31c2dc000)
> libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc31bfd6000)
> /lib64/ld-linux-x86-64.so.2 (0x00007fc31d717000)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6253#issuecomment-135507263>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by SteliosFly** [comment]
Will do, 
Thanks NJ 
p.s. you guys keep up the good work :)

**Comment by njsmith** [comment]
Okay, I'm going to close this for now since there's currently no action item for us -- feel free to re-open or file a new bug later if it makes sense. Good luck!

**Comment by SteliosFly** [comment]
OKs
