### ISSUE TITLE
np.sqrt.types is weird

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#6255]
There are duplicated entries, and also `e->e` comes after `f->f`, which probably means there'll always be a conversion to float32.

```
>>> np.sqrt.types
['f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']
```

**Comment by eric-wieser** [comment]
Duplicate of #7897
