### ISSUE TITLE
f2py broken on Mac OS X 10.10.5?

### ISSUE THREAD

**Issue by louiswicker** [numpy/numpy#6273]
<b> Edit:  somehow, the parameters:

-undefined dynamic_lookup -bundle are not being input to the link command at the end on my workstation compile.  When that is added, the compile works.

somehow the numpy/distutils/fcompile/gnu.py is an old version.  Sorry to have bothered this list  </b>

Not sure how this happened - whether its an os update, or something to do with numpy update in the last 30-60 days.  I am using the conda environment from Continuum

Whether I use gfortran 5.1, or 5.0, or 4.9, and I have tried numpy 1.9.1 and numpy 1.9.2, the classic example case (FIB3.f) from the docs page no longer works.

(e.g., the code from https://sysbio.ioc.ee/projects/f2py2e/usersguide/fib3.f)

right now, my typical environment is:

gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.4.0/5.1.0/lto-wrapper
Target: x86_64-apple-darwin14.4.0
Configured with: ../gcc-5.1.0/configure --enable-languages=c++,fortran
Thread model: posix
gcc version 5.1.0 (GCC)

The errors I get using either the standard build or the the "f2py -c -m fib3 fib3.f" fails with this output.

Clearly the key is at the bottom:  "ld: symbol(s) not found for architecture x86_64"  is why this is failing, but looking at all the output I cannot understand where there is a problem with this arch issue.

running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "fib3" sources
f2py options: []
  adding 'build/src.macosx-10.5-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.macosx-10.5-x86_64-2.7' to include_dirs.
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/local/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building 'fib3' extension
compiling C sources
C compiler: gcc -fno-strict-aliasing -I/Volumes/Master_1/Users/wicker/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/include

compile options: '-Ibuild/src.macosx-10.5-x86_64-2.7 -I/Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Volumes/Master_1/Users/wicker/anaconda/include/python2.7 -c'
gcc: build/src.macosx-10.5-x86_64-2.7/fortranobject.c
In file included from /Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from build/src.macosx-10.5-x86_64-2.7/fortranobject.h:13,
                 from build/src.macosx-10.5-x86_64-2.7/fortranobject.c:2:
/Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc: build/src.macosx-10.5-x86_64-2.7/fib3module.c
In file included from /Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from build/src.macosx-10.5-x86_64-2.7/fortranobject.h:13,
                 from build/src.macosx-10.5-x86_64-2.7/fib3module.c:18:
/Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
build/src.macosx-10.5-x86_64-2.7/fib3module.c:104:12: warning: ‘f2py_size’ defined but not used [-Wunused-function]
 static int f2py_size(PyArrayObject\* var, ...)
            ^
compiling Fortran sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -m64 -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/local/bin/gfortran -Wall -g -fno-second-underscore -m64 -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -m64 -fPIC -O3 -funroll-loops
compile options: '-Ibuild/src.macosx-10.5-x86_64-2.7 -I/Volumes/Master_1/Users/wicker/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Volumes/Master_1/Users/wicker/anaconda/include/python2.7 -c'
gfortran:f77: fib3.f
/usr/local/bin/gfortran -Wall -g -L/usr/local/lib -L/usr/local/lib build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/fib3module.o build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/fortranobject.o build/temp.macosx-10.5-x86_64-2.7/fib3.o -L/usr/local/lib/gcc/x86_64-apple-darwin14.4.0/5.1.0 -L/Volumes/Master_1/Users/wicker/anaconda/lib -lgfortran -o build/lib.macosx-10.5-x86_64-2.7/fib3.so
Undefined symbols for architecture x86_64:
  "_PyArg_ParseTupleAndKeywords", referenced from:
      _f2py_rout_fib3_fib in fib3module.o
  "_PyCObject_AsVoidPtr", referenced from:
      _initfib3 in fib3module.o
      _F2PyCapsule_AsVoidPtr in fortranobject.o
  "_PyCObject_FromVoidPtr", referenced from:
      _fortran_getattr in fortranobject.o
      _F2PyCapsule_FromVoidPtr in fortranobject.o
  "_PyCObject_Type", referenced from:
      _initfib3 in fib3module.o
      _F2PyCapsule_Check in fortranobject.o
  "_PyComplex_Type", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
  "_PyDict_DelItemString", referenced from:
      _fortran_setattr in fortranobject.o
  "_PyDict_GetItemString", referenced from:
      _fortran_getattr in fortranobject.o
  "_PyDict_New", referenced from:
      _PyFortranObject_New in fortranobject.o
      _PyFortranObject_NewAsAttr in fortranobject.o
      _fortran_setattr in fortranobject.o
  "_PyDict_SetItemString", referenced from:
      _initfib3 in fib3module.o
      _fortran_getattr in fortranobject.o
      _F2PyDict_SetItemString in fortranobject.o
      _PyFortranObject_New in fortranobject.o
      _fortran_setattr in fortranobject.o
  "_PyErr_Clear", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _fortran_repr in fortranobject.o
      _F2PyDict_SetItemString in fortranobject.o
  "_PyErr_Format", referenced from:
      _initfib3 in fib3module.o
      _fortran_call in fortranobject.o
  "_PyErr_NewException", referenced from:
      _initfib3 in fib3module.o
  "_PyErr_Occurred", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _initfib3 in fib3module.o
      _F2PyDict_SetItemString in fortranobject.o
  "_PyErr_Print", referenced from:
      _initfib3 in fib3module.o
      _F2PyDict_SetItemString in fortranobject.o
  "_PyErr_SetString", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _initfib3 in fib3module.o
      _array_from_pyobj in fortranobject.o
      _fortran_setattr in fortranobject.o
  "_PyExc_AttributeError", referenced from:
      _initfib3 in fib3module.o
      _fortran_setattr in fortranobject.o
  "_PyExc_ImportError", referenced from:
      _initfib3 in fib3module.o
  "_PyExc_RuntimeError", referenced from:
      _initfib3 in fib3module.o
      _fortran_call in fortranobject.o
  "_PyExc_TypeError", referenced from:
      _fortran_call in fortranobject.o
      _array_from_pyobj in fortranobject.o
  "_PyExc_ValueError", referenced from:
      _array_from_pyobj in fortranobject.o
  "_PyImport_ImportModule", referenced from:
      _initfib3 in fib3module.o
  "_PyMem_Free", referenced from:
      _fortran_dealloc in fortranobject.o
  "_PyModule_GetDict", referenced from:
      _initfib3 in fib3module.o
  "_PyNumber_Int", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
  "_PyObject_GetAttrString", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _initfib3 in fib3module.o
      _fortran_repr in fortranobject.o
  "_PySequence_Check", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
  "_PySequence_GetItem", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
  "_PyString_AsString", referenced from:
      _fortran_repr in fortranobject.o
  "_PyString_ConcatAndDel", referenced from:
      _fortran_getattr in fortranobject.o
  "_PyString_FromFormat", referenced from:
      _fortran_repr in fortranobject.o
  "_PyString_FromString", referenced from:
      _initfib3 in fib3module.o
      _fortran_repr in fortranobject.o
      _fortran_getattr in fortranobject.o
  "_PyType_IsSubtype", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _array_from_pyobj in fortranobject.o
  "_PyType_Type", referenced from:
      _initfib3 in fib3module.o
  "_Py_BuildValue", referenced from:
      _f2py_rout_fib3_fib in fib3module.o
  "_Py_FindMethod", referenced from:
      _fortran_getattr in fortranobject.o
  "_Py_InitModule4_64", referenced from:
      _initfib3 in fib3module.o
  "__PyObject_New", referenced from:
      _PyFortranObject_New in fortranobject.o
      _PyFortranObject_NewAsAttr in fortranobject.o
  "__Py_NoneStruct", referenced from:
      _f2py_rout_fib3_fib in fib3module.o
      _fortran_getattr in fortranobject.o
      _array_from_pyobj in fortranobject.o
      _fortran_setattr in fortranobject.o
  "_main", referenced from:
      start in crt1.10.5.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
Undefined symbols for architecture x86_64:
  "_PyArg_ParseTupleAndKeywords", referenced from:
      _f2py_rout_fib3_fib in fib3module.o
  "_PyCObject_AsVoidPtr", referenced from:
      _initfib3 in fib3module.o
      _F2PyCapsule_AsVoidPtr in fortranobject.o
  "_PyCObject_FromVoidPtr", referenced from:
      _fortran_getattr in fortranobject.o
      _F2PyCapsule_FromVoidPtr in fortranobject.o
  "_PyCObject_Type", referenced from:
      _initfib3 in fib3module.o
      _F2PyCapsule_Check in fortranobject.o
  "_PyComplex_Type", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
  "_PyDict_DelItemString", referenced from:
      _fortran_setattr in fortranobject.o
  "_PyDict_GetItemString", referenced from:
      _fortran_getattr in fortranobject.o
  "_PyDict_New", referenced from:
      _PyFortranObject_New in fortranobject.o
      _PyFortranObject_NewAsAttr in fortranobject.o
      _fortran_setattr in fortranobject.o
  "_PyDict_SetItemString", referenced from:
      _initfib3 in fib3module.o
      _fortran_getattr in fortranobject.o
      _F2PyDict_SetItemString in fortranobject.o
      _PyFortranObject_New in fortranobject.o
      _fortran_setattr in fortranobject.o
  "_PyErr_Clear", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _fortran_repr in fortranobject.o
      _F2PyDict_SetItemString in fortranobject.o
  "_PyErr_Format", referenced from:
      _initfib3 in fib3module.o
      _fortran_call in fortranobject.o
  "_PyErr_NewException", referenced from:
      _initfib3 in fib3module.o
  "_PyErr_Occurred", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _initfib3 in fib3module.o
      _F2PyDict_SetItemString in fortranobject.o
  "_PyErr_Print", referenced from:
      _initfib3 in fib3module.o
      _F2PyDict_SetItemString in fortranobject.o
  "_PyErr_SetString", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _initfib3 in fib3module.o
      _array_from_pyobj in fortranobject.o
      _fortran_setattr in fortranobject.o
  "_PyExc_AttributeError", referenced from:
      _initfib3 in fib3module.o
      _fortran_setattr in fortranobject.o
  "_PyExc_ImportError", referenced from:
      _initfib3 in fib3module.o
  "_PyExc_RuntimeError", referenced from:
      _initfib3 in fib3module.o
      _fortran_call in fortranobject.o
  "_PyExc_TypeError", referenced from:
      _fortran_call in fortranobject.o
      _array_from_pyobj in fortranobject.o
  "_PyExc_ValueError", referenced from:
      _array_from_pyobj in fortranobject.o
  "_PyImport_ImportModule", referenced from:
      _initfib3 in fib3module.o
  "_PyMem_Free", referenced from:
      _fortran_dealloc in fortranobject.o
  "_PyModule_GetDict", referenced from:
      _initfib3 in fib3module.o
  "_PyNumber_Int", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
  "_PyObject_GetAttrString", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _initfib3 in fib3module.o
      _fortran_repr in fortranobject.o
  "_PySequence_Check", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
  "_PySequence_GetItem", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
  "_PyString_AsString", referenced from:
      _fortran_repr in fortranobject.o
  "_PyString_ConcatAndDel", referenced from:
      _fortran_getattr in fortranobject.o
  "_PyString_FromFormat", referenced from:
      _fortran_repr in fortranobject.o
  "_PyString_FromString", referenced from:
      _initfib3 in fib3module.o
      _fortran_repr in fortranobject.o
      _fortran_getattr in fortranobject.o
  "_PyType_IsSubtype", referenced from:
      _int_from_pyobj.constprop.0 in fib3module.o
      _f2py_rout_fib3_fib in fib3module.o
      _array_from_pyobj in fortranobject.o
  "_PyType_Type", referenced from:
      _initfib3 in fib3module.o
  "_Py_BuildValue", referenced from:
      _f2py_rout_fib3_fib in fib3module.o
  "_Py_FindMethod", referenced from:
      _fortran_getattr in fortranobject.o
  "_Py_InitModule4_64", referenced from:
      _initfib3 in fib3module.o
  "__PyObject_New", referenced from:
      _PyFortranObject_New in fortranobject.o
      _PyFortranObject_NewAsAttr in fortranobject.o
  "__Py_NoneStruct", referenced from:
      _f2py_rout_fib3_fib in fib3module.o
      _fortran_getattr in fortranobject.o
      _array_from_pyobj in fortranobject.o
      _fortran_setattr in fortranobject.o
  "_main", referenced from:
      start in crt1.10.5.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
error: Command "/usr/local/bin/gfortran -Wall -g -L/usr/local/lib -L/usr/local/lib build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/fib3module.o build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/fortranobject.o build/temp.macosx-10.5-x86_64-2.7/fib3.o -L/usr/local/lib/gcc/x86_64-apple-darwin14.4.0/5.1.0 -L/Volumes/Master_1/Users/wicker/anaconda/lib -lgfortran -o build/lib.macosx-10.5-x86_64-2.7/fib3.so" failed with exit status 1

**Comment by kjswanson** [comment]
I believe I am having the same issue. I was wondering if you could either elaborate more or point me in the right direction to solve this issue?

Have a good one,
Kyle

**Comment by matthew-brett** [comment]
Are you also using Anaconda?  Can you replicate using a pip install of numpy?

**Comment by kjswanson** [comment]
I am as using anaconda.

So install numpy with pip instead of through the anaconda interface?

**Comment by matthew-brett** [comment]
The reason I asked was because, we numpyers maintain the pip packages, but not the Anaconda install.  So if you have the problem after a pip install, we will try and fix it, if it's only for the Anaconda install, you would be better off raising an issue over at https://github.com/ContinuumIO/anaconda-issues/issues .  I don't use Anaconda myself, but I'm guessing that mixing a pip installed numpy with other Anaconda packages might get messy, so, if you are trying a pip install, I would do it by downloading / installing a Python.org Python and doing a `pip install numpy` into that, to keep it separate from your Anaconda installation.

**Comment by kjswanson** [comment]
I will pursue this and report back.

Thanks for the help!

**Comment by kjswanson** [comment]
Hello again!

I have re-tested in a new virtual environment.
-> Python 3.6
-> numpy 1.12

Using the fib1.f routine from this [scipy link](https://docs.scipy.org/doc/numpy-dev/f2py/getting-started.html)

This is one of the errors that show up.

#warning "Using deprecated NumPy API, disable it by " \

Also when I was looking through the errors/ feed back from f2py I also noticed.

1) It seemed to be using a python 3.6 that anaconda installed... When i made the virtual env, I must have pointed to that python instance instead of the (what I thought to be) separate python 3.6 I installed.

And.... 

I tried this on a xubuntu system, where I believe I have a fresh install of python3.5 and numpy. 

I also get a similar error. 

This has me thinking that it is a user error.

**Comment by TK-422** [comment]
I am receiving a similar error as above when attempting the hello.f example case, with the last bit of the error message repeated below.  I am also running a conda distribution (4.2.13 with numpy=1.12.1) with a homebrew managed gfortran version 6.3.0.  One thing that I noted is that while invoking "f2py -c -m hello hello.f" generates the error below, running the same command with sudo resolves the linker error.

  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
error: Command "/usr/local/bin/gfortran -Wall -g -L/usr/local/opt/sqlite/lib /var/folders/kr/036q9l1x793gk0fcl609dmhw2ts7d0/T/tmp9c0Fai/var/folders/kr/036q9l1x793gk0fcl609dmhw2ts7d0/T/tmp9c0Fai/src.macosx-10.7-x86_64-2.7/hellomodule.o /var/folders/kr/036q9l1x793gk0fcl609dmhw2ts7d0/T/tmp9c0Fai/var/folders/kr/036q9l1x793gk0fcl609dmhw2ts7d0/T/tmp9c0Fai/src.macosx-10.7-x86_64-2.7/fortranobject.o /var/folders/kr/036q9l1x793gk0fcl609dmhw2ts7d0/T/tmp9c0Fai/hello.o -L/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.3.0 -L/Users/johndoe/anaconda/lib -lgfortran -o ./hello.so" failed with exit status 1

**Comment by krystophny** [comment]
I checked the commands on a combination of Anaconda 2020.11 on macos 11 with numpy from conda and gfortran 10 from MacPorts, and there is no issue running these commands anymore. Does anyone still experience these kinds of problems? Otherwise I suggest to close the issue.

**Comment by krystophny** [comment]
Since there was no reply for a month and everything is working in my test, I'm closing this issue.
