### ISSUE TITLE
ravel and unravel are synonyms

### ISSUE THREAD

**Issue by okomarov** [numpy/numpy#6276]
Ravel and unravel are **synonyms**, but the methods where they appear accomplish inverse operations. 
See my [SO question](http://stackoverflow.com/questions/32336913/numpy-ravel-unravel-naming-rage) for details and example.

Can you consider introducing alternative methods that contain `unravel` in their name (even functions containing ravel are IMHO not a happy choice)?

I propose to change e.g. 

| before  | after   |
---|---
`unravel_index()` | `index_to_coord()` 
`ravel_multi_index()` | `index_to_flat`

**Comment by pv** [comment]
I think backward incompatible changes due to cosmetic reasons are
usually not a good idea. The suggested new names look more descriptive
though.

**Comment by juliantaylor** [comment]
I think giving flatten a keyword arg for copy=False would also be good.

**Comment by okomarov** [comment]
@pv I totally agree that backward compatibility deserves priority and I was thinking about duplication. The new functions should simply call the older ones and replace them in the docs.

Users caling the old methods should get a deprecation warning with a fixed timeline, e.g. 2 years. 

However, I understand if you do not have such policy, especially for cases like this one.

**Comment by pv** [comment]
Two years is a short time, 1.7.1 was released 2 yrs ago (the newest RHEL has it), and ubuntu 12LTS is still at 1.6.2 from 4 years ago. Now, imagine running a script you wrote 10 years ago, and having to fix multiple of these renamed functions.

Although there's no policy about exactly on this, I would personally prefer to avoid changes unless there is a pressing need to make them.

**Comment by okomarov** [comment]
Python is not a stranger to duality, see 2.* and 3.* and all the burden it imposes with the virtual environments etc... Hence, chances are that even without this renaming a script written 10 years ago won't work with the new release of the language. But then, of course, less hassle is always preferable. 

I'll just leave my last two cents on the matter, as a potential workflow, and we can close this issue afterwards:

1) Create a deprecation plan with explicit deadlines, that have to be checked as new releases of numpy come out.
2) For this type of cosmetic deprecations, you move the actual code of th old function in the new one, so that you do it now, when the reason is fresh, rather than in e.g.10 years.
3) The old function now calls the new one, with appropriate warnings. If the API changes, you need to warn the user that the old function does NOT support the .e.g new option. 
4) The docs shift to the new function. The old function will only be in an older version of the docs ONLY, and will have deprecation warnings, so that the old function does not get immediate visibility.  

With a deprecation plan, the changes all happen now, the development continues inside the newly renamed function and when the deadline hits, in 10 years, you just do not package it anymore.
