### ISSUE TITLE
Segmentation fault when using Numpy arrays and astropy time objects 

### ISSUE THREAD

**Issue by Dapid** [numpy/numpy#6284]
The following example triggers a segfault in the last line when the array is 501 elements or longer, and an exception when it is shorter.

```
from astropy import time
import numpy as np

t_max = 1258.2
phase = np.linspace(-10, 10, num=501)
date_obs = time.Time(np.random.random(phase.shape), format='jd')
selected = phase == phase[320]
selected = phase < phase[3]

_ph = np.array(time.Time(t_max, format='jd') - date_obs[selected])
print _ph, type(_ph)
phase[selected] = _ph
```

I am using Python 2.7 on Fedora 22, Numpy 1.9.1 and astropy 1.0.4 installed in a virtualenv.

This is what gdb has to say:

PyErr_Restore (type=<type at remote 0x309fd89e20>, value=<optimized out>, traceback=traceback@entry=0x0) at /usr/src/debug/Python-2.7.10/Python/errors.c:39
39      oldtype = tstate->curexc_type;

**Comment by jaimefrio** [comment]
I see it also on OSX.

**Comment by seberg** [comment]
The example gives a python error now, so I guess it is fixed.

**Comment by eric-wieser** [comment]
What's the new error?

**Comment by seberg** [comment]
```
ValueError: setting an array element with a sequence.
```
which is the same as for `np.asarray(_ph, dtype=phase.dtype)` (float64).  Which probably is right, because that timedelta object behaves a bit like a sequence but isn't (like a 0d array) maybe

**Comment by eric-wieser** [comment]
Error message could certainly be better there. It looks like we're missing a case for foreign 0d duck arrays

**Comment by seberg** [comment]
Sure, could at least print the type instead of just "sequence". I doubt
that this code errors at all is not numpy's fault though (except the
general difficulties of ducks).
