### ISSUE TITLE
Regression in numpy.intersect1d comparing sets?

### ISSUE THREAD

**Issue by quantax-github** [numpy/numpy#6285]
Hi,

Is this intentional or a regression between 1.7.1 and 1.9.1 (I don't have intermediate versions). I couldn't find anything in the release notes pointing directly to it. 

Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

```
>>> numpy.version.version
'1.7.1'
>>> numpy.intersect1d(set([1,2,3]),set([3,5,6]))
array([3])
```

Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
```
>>> numpy.version.version
'1.9.1'
>>> numpy.intersect1d(set([1,2,3]),set([3,5,6]))
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Quantax\trunk\Python64\lib\site-packages\numpy\lib\arraysetops.py", line 249, in intersect1d
    aux.sort()
TypeError: cannot compare sets using cmp()
```

Thanks and best regards, Martin

**Comment by pv** [comment]
These functions are not supposed to be used with set inputs (`set` is not a sequence, and thus not `array_like`). cf https://github.com/numpy/numpy/issues/3892

**Comment by quantax-github** [comment]
Ah, ok, I thought you could pass iterables. Restriction on sequences makes sense. 

Thanks and best regards,
Martin
