### ISSUE TITLE
Recent performance regression on np.dot linked to openBLAS with large matrices

### ISSUE THREAD

**Issue by Newmu** [numpy/numpy#6297]
Not quite sure if it's an issue with openBLAS or numpy yet. Regularly setup high performance environments from source on a ~monthly basis on the same hardware system and noticed a 2x performance regression that sometimes results in very long/hanging calls to `np.dot` with large matrices (i.e. 4096x4096 and up).

For reference, building both from source this morning results in the issue while using these commits from when last built works fine.
openBLAS 5408074941d5cc0f4aad180562cafcf4cf27a56d
numpy d750cba93436f20d5457daec5ad5d5ffb65f22bd
cython d6cf8959a58395daacb1e338644a698ef263ce98 (in case its relevant)

The system is ubuntu 14.04.3 on a 8 core haswell 5960x with 64 GB of ddr4. When `np.dot` is called a task manager first shows load distributed across all cores (as expected) and when hanging occurs it appears distributed across only 8 threads (out of 16 with hyperthreading) to begin with and slowly those threads exit till it seems to stall for 10+ minutes on only two threads remaining. The probability of hanging appears to be linked to the size of the matrices, at 8192x8192 it has always hanged (even waiting 100x the normal amount of time it takes) at 4096x4096 it happens ~ 1 in 3 times and at 128x128 it never appears to hang.

Example code 

``` python
import numpy as np
a = np.random.randn(4096, 4096)
b = np.random.randn(4096, 4096)
np.dot(a, b)
```

**Comment by charris** [comment]
I'd guess that openBLAS is the problem here.

**Comment by njsmith** [comment]
Can you file a bug with OpenBLAS?
.
The ideal would be if you can confirm for sure that it's OpenBLAS's fault
first by reproducing the problem using a simple C program without numpy.
But honestly, even without that it's like 99% likely to be an OpenBLAS bug,
and I suspect they'll be able to deal with it even if the reproducer
requires numpy.

On Wed, Sep 9, 2015 at 7:10 PM, Alec Radford <notifications@github.com>
wrote:

> Not quite sure if it's an issue with openBLAS or numpy yet. Regularly
> setup high performance environments on a ~monthly basis on the same
> hardware system and noticed a 2x performance regression that sometimes
> results in a very long hang on calls to np.dot with large matrices (i.e.
> 4096x4096 and up).
>
> For reference, building both from source this morning results in the error
> while using these commits from when I last built works fine.
> openBLAS 5408074941d5cc0f4aad180562cafcf4cf27a56d
> numpy d750cba
> <https://github.com/numpy/numpy/commit/d750cba93436f20d5457daec5ad5d5ffb65f22bd>
> cython d6cf8959a58395daacb1e338644a698ef263ce98 (in case its relevant)
>
> The system is ubuntu 14.04.3 built on a 8 core haswell 5960x with 64 GB of
> DDR4. When hanging occurs it appears distributed across 8 threads to begin
> with and slowly those threads exit till it seems to stall for 10+ minutes
> on only two threads remaining. The probability of hanging appears to be
> linked to the size of the matrices, at 8192x8192 it has always hanged (even
> waiting 100x the normal amount of time it takes) and at 128x128 it's never
> appeared to hang before.
>
> Example code
>
> import numpy as np
> a = np.random.randn(4096, 4096)
> b = np.random.randn(4096, 4096)
> np.dot(a, b)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6297>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by seberg** [comment]
This is an old speed related problem that was seems like an issue with OpenBLAS in the first place, so closing.
