### ISSUE TITLE
numpy.fft slow when used in a subprocess

### ISSUE THREAD

**Issue by praphael** [numpy/numpy#6299]
I've noticed that numpy.fft.fft (and its variants) very slow (about 10x) when used inside of a subprocess (spawned by multiprocessing), as compared to outside of it   Here is example code

    import numpy as np
    import multiprocessing as mproc
    import time
    import sys
    
    # the producer function, which will run in the background and produce data
    def Producer(dataQ):
        numFrames = 5
        n = 0
        while n < numFrames:
            data = np.random.rand(3000, 200)
            dataQ.put(data)   # send the datta to the consumer
            time.sleep(0.1)  # sleep for 0.5 second, so we dont' overload CPU
            n += 1
      # the consumer function, which will run in the backgrounnd and consume data from the producer
    def Consumer(dataQ):
        while True:
            data = dataQ.get()
            t1 = time.time()
            fftdata = np.fft.rfft(data, n=3000*5)
            tDiff = time.time() - t1
            print("Elapsed time is %0.3f" % tDiff)
            time.sleep(0.01)
            sys.stdout.flush()
      
    
    # the main program  if __name__ == '__main__': is necessary to prevent this code from being run
    # only when this program is started by user
    if __name__ == '__main__':     
        data = np.random.rand(3000, 200)
         t1 = time.time()
        fftdata = np.fft.rfft(data, n=3000*5, axis=0)
         tDiff = time.time() - t1
        print("Elapsed time is %0.3f" % tDiff)
        
        # generate a queue for transferring data between the producedr and the consumer
        dataQ = mproc.Queue(4)
        
        # start up the processoso
        producerProcess = mproc.Process(target=Producer, args=[dataQ], daemon=False)
        consumerProcess = mproc.Process(target=Consumer, args=[dataQ], daemon=False)
        print("starting up processes")
        
        producerProcess.start()
        consumerProcess.start()
        time.sleep(10) # let program run for 5 seconds
        
        producerProcess.terminate()
        consumerProcess.terminate()

The output it produces on my machine is 

    Elapsed time is 0.112
    starting up processes
    Elapsed time is 0.716
    Elapsed time is 0.749
    Elapsed time is 0.831
    Elapsed time is 0.908
    Elapsed time is 0.955

Anybody know whats going on?   I've tried other functions like convolve(), but they don't produce the same slowdown.  The CPU usage in both single and multiprrocess cases with heavy calls to fft() is the same (about 25-30%), as reported by Windows Task Manager.   Anybond know what could be causing the discrepancy?

**Comment by seberg** [comment]
If you are on windows, spawning times are very slow. Can you check if it is not just the spawning you are measuring?

**Comment by praphael** [comment]
Ok, I think I have it figured out.  Preallocating based on the expected array size seems to eliminate the difference.  Even if I allocate every time through the loop.  So change the line
    fftdata = np.fft.rfft(data, n=3000*5, axis=0)
To
    fftdata = np.zeros(3000*5 // 2 + 1, data.shape[1])
    fftdata[:, :] = np.fft.rfft(data, n=3000*5, axis=0)

I then get:
    Elapsed time is 0.088
    starting up processes
    Elapsed time is 0.089
    Elapsed time is 0.096
    Elapsed time is 0.092
    Elapsed time is 0.102
    Elapsed time is 0.089

**Comment by seberg** [comment]
Does not make much sense to me, unless you have an `out` keyword argument in the fft, the same calculation happens exactly (you get a temporary array, and this temporary array is assigned into your fftdata array).
But we do have some cache optimizations in numpy for temporary arrays, so maybe it could be somewhat related to that. Though I would expect any allocation to be much slower then the fft. Depending on how many cores/memory throughput you have, maybe it is just not worth it?

**Comment by praphael** [comment]
Actually this was an error on my part.   The FFT the frist time is done along axis=0, but when I did it in the subprocess I didn't specify an axis (and it defaults to last).   So it doing a much bigger FFT and of course it was slower

I have found the real problem, is that fft is very slow for certain input sizes.   But adjusting the zero pad to a close power of a 2 gets around this problem
