### ISSUE TITLE
mem_overlap(538) VLA not compile with visual studio

### ISSUE THREAD

**Issue by yajiedesign** [numpy/numpy#6300]
visual studio 2015 
numpy 4091facf55e03d356a5d7ce219ae0c0494920df3
mem_overlap(538) VLA not compile with visual studio
numpy\core\src\private\mem_overlap.c 538 line
diophantine_term_t Ep[n];
npy_int64 Epsilon[n], Gamma[n];

**Comment by argriffing** [comment]
Skimming the code, it looks like `n` is `nterms` and that this is at most `2*NPY_MAXDIMS+2`, so maybe use that value instead of `n` here, so that the array length is known at compile time (not variable)?

Would this have been caught if appveyor were enabled?

**Comment by njsmith** [comment]
That should work... or just use `malloc`...

> Would this have been caught if appveyor were enabled?

Yes, that would be awesome if someone has some [tuits](https://en.wiktionary.org/wiki/round_tuit) available.

**Comment by argriffing** [comment]
> Yes, that would be awesome if someone has some [tuits](https://en.wiktionary.org/wiki/round_tuit) available.

Sure, maybe keep [tuits](https://en.wiktionary.org/wiki/round_tuit) in mind for the shopping list to be used once numpy has figured out what it means to give money to numpy and has grown a layer of administration to make organizations feel comfortable doing this.

**Comment by juliantaylor** [comment]
lets just use `-Werror=vla` in travis

**Comment by argriffing** [comment]
Is there something more general like -Werror=everything-that-is-not-portable-to-visual-studio?

**Comment by pv** [comment]
this was fixed
