### ISSUE TITLE
FR - increment counter on write check

### ISSUE THREAD

**Issue by d1manson** [numpy/numpy#6301]
Presumably any block of code that modifies an ndarray is wrapped in a (thread safe?) check of the writable flag. Would it be possible to hold a counter rather than a simple bool flag and then increment the counter whenever you test the flag? Hopefully this would introduce only a tiny additional overhead, but would permit pseudo-hashing to test whether an immutable array has changed since you last encountered it.

**Comment by d1manson** [comment]
I meant mutable

**Comment by njsmith** [comment]
Interesting idea. Could you send to the list, with few more details about
what exactly you mean and examples of where it would be useful? (I think I
understand the proposal, but I had to reverse engineer it a bit in my mind
;-).) We try to keep the tracker more for day-to-day maintenance and do
design discussion on the list where more people will see it.

**Comment by d1manson** [comment]
Ok - I have just done as suggested.

**Comment by njsmith** [comment]
Thanks Daniel!
