### ISSUE TITLE
cumsum improvements

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#6311]
`cumsum` could support simultaneously summing over multiple axes (à la `sum`).
I also wonder if people are really relying on it to sum over the flattened array in dimensions higher than one... if not, perhaps that could be a warning.

**Comment by WarrenWeckesser** [comment]
In https://github.com/numpy/numpy/issues/12113, @anntzer repeated this enhancement request.  The newer one has more details and a response, so I'm closing this one as the duplicate.

**Comment by anntzer** [comment]
woops, sorry for the duplicate :)
