### ISSUE TITLE
Why numpy does not provide a 64 bits windows distribution ?

### ISSUE THREAD

**Issue by jamartinh** [numpy/numpy#6313]
Why numpy does not provide a 64 bits windows distribution ?

Yes I know, there are many sources to install a 64 bits numpy on windows, but why the official release does not come in a win 64 flavor ?

Thanks,
Jose

**Comment by charris** [comment]
Lack of a free 64 bit C compiler. Work is being done on a 64 bit tool chain using mingw64 but it isn't done yet.

**Comment by charris** [comment]
This sort of guestion is best raised on the mailing list as id isn't really an issue, so closing.
