### ISSUE TITLE
Missing byteswap when converting array with record dtype to opposite-endian dtype.

### ISSUE THREAD

**Issue by mdickinson** [numpy/numpy#6314]
Consider the following self-contained snippet of code:

```
import numpy as np
dtype = np.dtype([("V", "<f8"), ("A", "<f8")])
be_dtype = dtype.newbyteorder('>')
value = np.array((1.1, 1.2), dtype=dtype)

print np.asarray(value, dtype=be_dtype)
print np.asarray([value], dtype=be_dtype)
```

When I run this under Python 2.7 and NumPy 1.9.2 on my OS X 10.9 machine, I get the following output:

```
(1.1, 1.2)
[(-1.5423487136706484e-180, 4.667261458438315e-62)]
```

I'd expect to get this output:

```
(1.1, 1.2)
[(1.1, 1.2)]
```

Doing the same with a scalar dtype gives me the expected behaviour, and replacing `value` with the tuple `(1.1, 1.2)` also gives me the expected behaviour.  It looks as though there's a byteswap operation being missed at some level during the conversion.

**Comment by ahaldane** [comment]
This happens because `VOID_setitem` copies structured arrays as if they were void buffers, so no casting or byteswapping occurs. For example try this:

    print array([value], dtype=[("V", "i8"), ("A", "i8")])
    
This would be fixed by #6053
