### ISSUE TITLE
1.9.3 release very soon

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#6319]
I think the mailing list is down ATM.

It would be good to get out a release compatible with Python 3.5 as soon as possible, because Python 3.5 is the default download at Python.org.

I propose just merging https://github.com/numpy/numpy/commit/7d6aa8c721d5274ac57d0c87685d472cb1fd7948 for 1.9.3 and releasing in the next few days, and then add more bugfixes for 1.9.4 over the following week.

I'm happy to do the release work for 1.9.3 if that's acceptable.

**Comment by andreabedini** [comment]
@matthew-brett any chance we can have #5866 too in 1.9.4 ? it fixes homebrew/homebrew#43916.

**Comment by matthew-brett** [comment]
Any objection to a 1.9.3 release with:

* gzip fix
* signed git tag
* source, OSX wheels on pypi
* source, OSX wheels, unchanged docs on sourceforge

without:

* windows superpack builds on sourceforge.

?  Can someone point me to the most up to date release instructions?  `doc/HOWTO_RELEASE.rst.txt` seems to be seriously out of date?

**Comment by matthew-brett** [comment]
Proposed contents of 1.9.3 : https://github.com/numpy/numpy/pull/6332

**Comment by njsmith** [comment]
I think @charris and/or @juliantaylor are the most up-to-date on the release procedure stuff -- can either of you comment on doc/HOWTO_RELEASE.rst.txt?

**Comment by tdsmith** [comment]
Thank you very much on Homebrew's behalf!

**Comment by charris** [comment]
Yes, the release howto is still confusing and needsupdating. Updates mostly happen during release as the release manager struggles through and tries to clarify what they found confusing. Not terribly helpful, I admit.

@matthew-brett It is easiest to start by asking what you found particularly difficult. I admit that there are a lot of candidates for that position. For the wheel releases, I think you are the expert. We probably need to document signing as well, but that is new to me also.

Is there a particular reason you are skipping the windows builds? That is pretty straight forward with numpy-vendor, although it does have some glitches, especially building the pdf documentation, that I should get more experience with today, Currently I build the documention separately.

**Comment by matthew-brett** [comment]
I had a go at updating the release notes here:

https://github.com/numpy/numpy/pull/6344

I didn't build the windows installers because I don't think we can build Python 3.5 installers yet, and the only significant fix in 1.9.3 was for Python 3.5.  Documentation is also the same.

**Comment by zeckalpha** [comment]
Looks like the 1.9.3 release happened, can this be closed?

**Comment by charris** [comment]
@zeckalpha Thanks for the ping.
