### ISSUE TITLE
Automatic local variable representing start in slicing

### ISSUE THREAD

**Issue by joonro** [numpy/numpy#6323]
Hi,

I think it would be great if we can have a local variable representing the start position in slicing. For example, I'm parsing a lot of json data and some of them are corrupted, and I find that I use the following frequently when I'm debugging:

```python
ValueError: Expecting property name: line 1 column 580374 (char 580373)

>>> texts[580374:580374 + 20]
```

Which is a pain to type and edit. If we have something like this:

```python
ValueError: Expecting property name: line 1 column 580374 (char 580373)

>>> texts[580374:np._start + 20]
```

and `np._start` equals to `580374` inside the slicing notation. I think this will provide a fluent work-flow because I can easily do history search and edit only the first part. I use these kind of thing a lot when I work with data, etc as well.

Of course, I can do the following, but it is less fluent :

```python
>>> ix = 580374
>>> texts[ix:ix + 20]
```

I understand there can be problems with this and it may not be practical, but I wanted to hear what others think of this. :) Thank you!

**Comment by mhvk** [comment]
This is not numpy-specific: python turns any `[...:...]` into a `slice`. You can see this by printing what is passed on to an instances' `__getitem__` (which python calls to implement `[...]`):
```
class M(object):
    def __getitem__(self, item):
        print(item)
 
m = M()
m[10:20]
# -> slice(10, 20, None)
```

So, I think you're somewhat stuck, though a simple workaround is to slice *twice*:
```
texts[580374:][:20]
```
Here, the first one removes all the front parts, and the second one takes only the first 20 items of what is left.

(If this answers it, do close your issue.)

**Comment by joonro** [comment]
That is a very nice solution - I should have thought of it. Thanks a lot!
