### ISSUE TITLE
Export CBLAS functions

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#6324]
I was wondering if it's possible for the relevant Numpy DLLs (e.g. lapack_lite or _umath_linalg) to export the CBLAS functions, so that other software can call into them using e.g. ctypes. Under Linux they are exported by default, but not under Windows (AFAIK you have to explicitly export symbols on Windows, by default "global" symbols in a shared library are private to the library).

Or perhaps I'm missing another way of accessing those functions at runtime?

**Comment by njsmith** [comment]
SciPy now does this, if that helps?

**Comment by pitrou** [comment]
Well, I wouldn't want to add Scipy as a dependency while Numpy already has the required functions.

**Comment by pitrou** [comment]
Looking at scipy, there doesn't seem to be a place where CBLAS functions are explicitly exported, is there?

**Comment by pitrou** [comment]
I mean, the only C module seeming to export something called `*dgemm*` is `scipy.sparse.linalg.dsolve._superlu`, and apparently it does it only by chance under Linux (which means it wouldn't export it under Windows).

Not to mention, of course, that that implementation may not be the fastest DGEMM available (what is SuperLU?).

**Comment by ewmoore** [comment]
@njsmith  is refering to `scipy.linalg.cython_blas` and `scipy.linalg.cython_lapack` which export all of blas and lapack such that they can be called directly from cython.   Really, this is just a large number of PyCapsule objects that carry the function pointers.
```
In [1]: from scipy.linalg import cython_blas

In [2]: cython_blas.__pyx_capi__['dgemm']
Out[2]: <capsule object "void (char *, char *, int *, int *, int *, __pyx_t_5scipy_6linalg_11cython_blas_d *, __pyx_t_5scipy_6linalg_11cython_blas_d *, int *, __pyx_t_5scipy_6linalg_11cython_blas_d *, int *, __pyx_t_5scipy_6linalg_11cython_blas_d *, __pyx_t_5scipy_6linalg_11cython_blas_d *, int *)" at 0x00000000051F9CC0>
```
Cython unpacks these and lets you use them without any fuss. Not sure why you couldn't do it by hand if necessary though.

**Comment by pitrou** [comment]
```
In [2]: cython_blas.__pyx_capi__['dgemm']
Out[2]: <capsule object "void (char *, char *, int *, int *, int *, __pyx_t_5scipy_6linalg_11cython_blas_d *, __pyx_t_5scipy_6linalg_11cython_blas_d *, int *, __pyx_t_5scipy_6linalg_11cython_blas_d *, int *, __pyx_t_5scipy_6linalg_11cython_blas_d *, __pyx_t_5scipy_6linalg_11cython_blas_d *, int *)" at 0x00000000051F9CC0>
```

Wow. Is this a supported API or just an implementation detail of how Cython currently does things?

**Comment by ewmoore** [comment]
What is there is how Cython implements cimport.  I don't know that I would call using it without Cython a supported API.  But I'm happy to be wrong about that.

**Comment by njsmith** [comment]
If you want information on the details of Cython's ABI as implemented in SciPy, then there are probably places that will get you a more reliable answer than the numpy bug tracker :-)

That said I think that Cython's pycapsule stuff is undocumented, but that they're probably stuck with it because if they ever changed it then it would break every existing compiled Cython module.

**Comment by nouiz** [comment]
I just made a duplicate issue about this and was redirected to here.

Even if cython provide a complicated way to call scipy blas, I think it would be great to add a function line PyArray_Gemm(alpha, A, B, beta, C).

If I work on that in the next few weeks, would this be accepted in NumPy?

I think this new function should call an extended `cblas_matrixproduct(int typenum, PyArrayObject *ap1, PyArrayObject *ap2, PyArrayObject *out)` that accept alpha and beta. And this original cblas_matrixproduct call that extended function.

What do you think of that?

**Comment by charris** [comment]
What about putting the matmul function in the API? See `multiarraymodule.c` line 2299.

**Comment by charris** [comment]
Note that we don't want to get into the library business, however we do offer a library with numpy compatible functions in `numpy/core/src/npymath`.

**Comment by njsmith** [comment]
It sounds like @nouiz specifically wants the GEMM alpha and beta, which isn't something that we expose as part of matmul or... well... any of our internal wrappers either. I don't think we even have code to do an arbitrary strided GEMM with non-trivial alpha and beta? Adding that support everywhere internally just to support one new C API call ... not sure if that's worth it. (Note that this code is actually pretty complicated, because numpy has fallback paths for if CBLAS isn't available, etc., and those would also have to implement alpha and beta.)

**Comment by juliantaylor** [comment]
is having alpha, beta and C in one call even worthwhile? these are all level 1 operations in a level 3 operations, so they shouldn't be very relevant for performance.
If you want to save some lines of code you can probably wrap `PyArray_MatrixProduct2` in a convenience function.

**Comment by juliantaylor** [comment]
using openblas:

```
import numpy as np
d = np.ones((1000, 1000))
c = np.ones((1000, 1000))
e = np.ones((1000, 1000))

%timeit np.dot(d, c)
%timeit 2. * np.dot(d, c) + 2. * e

10 loops, best of 3: 87.1 ms per loop
10 loops, best of 3: 97.9 ms per loop
```

hardly a difference, having this in one call probably makes no difference.

**Comment by nouiz** [comment]
My goal is two fold:

1) We did a PR that does reuse PyArray_MatrixProduct2(): https://github.com/Theano/Theano/pull/5076/files The c code is about 190 lines (the first two files, the rest is Theano specific stuff). I find that pretty long to implement a gemm in C to reuse numpy blas.

Yes, we could make the code shorter then what we have. I think gemm is a base operation, numpy already provide it at the python interface. So I think having it at the c interface would be great.

2) small speed up.

Don't forget, I'm not the first one to ask for this and I think the solution I propose is simple.

I'm pretty sure the code change could be "relatively" small. Here is a plan proposal on how to implelment it:

- Modify the private function gemm in "numpy/core/src/multiarray/cblasfuncs.c" to take an alpha and beta parameter.
- Create a public interface PyArray_Gemm that will call it with extra error handling on the inputs.

  We already implement support in Theano for arbitrary strided gemm. It does the minimal number of copy, it transpose the inputs if needed. We even optimize it when the C input that don't support transpose is transposed. So I know how to implement that.

We can decide to implement it or return an error if the user pass inputs that aren't supported. In fact, this could be a parameter to PyArray_Gemm(..., int copy_if_needed). If True, then copy when needed.

I had in mind to have that PyArray_Gemm always call gemm. If people want a wrapper that chose to select axpy, gemv or gemm, then calling PyArray_MatrixProduct[2] would do that without the alpha/beta.

I can implement any of those version if we agree on what to implement.

**Comment by nouiz** [comment]
Finally, we got a PR on Theano that make Theano reuse mkl from conda on windows. So this fix our worst problem that PyArray_Gemm don't exist. So I don't plan to work on this in the short term now. But I still think it is a good idea to do.

**Comment by rgommers** [comment]
Just came across this issue looking at `lapack_lite` related build issues. I think we should close this as wontfix. Rationale: `numpy.linalg` provides a subset of `scipy.linalg`, and `scipy.linalg.cython_blas/lapack` provides what is needed. Any new functionality should go there. This is hard to maintain functionality with few users, and duplicating it between numpy and scipy is simply not a good idea.

**Comment by mhvk** [comment]
Agreed and I'll go ahead and close. I do think eventually it might make sense to more formally expose the generalized ufuncs around the LAPACK functions that we use ourselves. Furthermore, we perhaps could add a pointer to the documentation to those, since they provide nice examples on how best to wrap LAPACK functions inside numpy.
