### ISSUE TITLE
Bug in documentation for numpy.cov

### ISSUE THREAD

**Issue by d-klein** [numpy/numpy#6327]
Concerning the parameters, 
http://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html#numpy.cov
says about rowvar:

rowvar : int, optional

```
If rowvar is non-zero (default), then each row represents a variable, with observations in the columns. Otherwise, the relationship is transposed: each column represents a variable, while the rows contain observations.
```

But looking at the source-code, we have:
    if rowvar:
        N = X.shape[1]
        axis = 0
    else:
        N = X.shape[0]
        axis = 1

in other words, rowvar is boolean. if rowvar is True (default), then each row represents a variable and observations are in columns. If rowvar is False, it means that each column represents a variable, and observations are in rows.

The current text is kind of confusion, as one might think rowvar can specify a range or specific rows or something.

The documentataion (or rather the comment in source-code) should be changed accordingly. Note that interestingly, http://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.cov.html has it right

**Comment by seberg** [comment]
As noted above, the docs have been clarified in that respect.
