### ISSUE TITLE
Import Error: No Such process on cygwin

### ISSUE THREAD

**Issue by ericenns** [numpy/numpy#6331]
I have installed python-numpy on cygwin in windows and I get the following error when trying to import numpy.

```
Python 2.7.10 (default, Jun  1 2015, 18:17:45)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/usr/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: No such process
```

**Comment by njsmith** [comment]
Someone here might have an idea, but it looks pretty mysterious to me! I'd
suggest raising a bug with whoever provided the cygwin numpy build, because
we don't have anything to do with that ourselves and it sure looks like a
weird cygwin-related issue...

On Fri, Sep 18, 2015 at 10:52 AM, Eric Enns <notifications@github.com>
wrote:

> I have installed python-numpy on cygwin in windows and I get the following
> error when trying to import numpy.
>
> Python 2.7.10 (default, Jun 1 2015, 18:17:45)
> [GCC 4.9.2] on cygwin
> Type "help", "copyright", "credits" or "license" for more information.
>
> import numpy
> Traceback (most recent call last):
> File "", line 1, in
> File "/usr/lib/python2.7/site-packages/numpy/*init*.py", line 170, in
> from . import add_newdocs
> File "/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in
> from numpy.lib import add_newdoc
> File "/usr/lib/python2.7/site-packages/numpy/lib/*init*.py", line 18, in
> from .polynomial import *
> File "/usr/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19,
> in
> from numpy.linalg import eigvals, lstsq, inv
> File "/usr/lib/python2.7/site-packages/numpy/linalg/*init*.py", line 51,
> in
> from .linalg import *
> File "/usr/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29,
> in
> from numpy.linalg import lapack_lite, _umath_linalg
> ImportError: No such process
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6331>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by seberg** [comment]
Since this is years old and only a build issue, closing.
