### ISSUE TITLE
Generated Documentation Images 404

### ISSUE THREAD

**Issue by pv** [numpy/numpy#6334]
Copypaste from https://github.com/scipy/scipy.org/issues/86

On this <a href="http://docs.scipy.org/doc/numpy/reference/generated/numpy.interp.html#numpy.interp">page</a>, the links on the (Source code, png, pdf) all result in 404 errors.

I haven't checked any other pages.

**Comment by seberg** [comment]
Seems like those documentation websites have been fixed long ago.
