### ISSUE TITLE
Why np.isscalar('hello') is True?

### ISSUE THREAD

**Issue by alexsavio** [numpy/numpy#6335]

**Comment by rkern** [comment]
Because numpy treats strings as scalars when asked to convert objects to `ndarrays`, as that is usually the intent of the author. We usually don't want to have an array of characters.

```
>>> np.array('hello').shape
()
>>> np.array(['hello', 'there']).shape
(2,)
```

**Comment by charris** [comment]
This sort of question is best asked on the mailing list. Closing here.
