### ISSUE TITLE
e7689a2600a28e75d187bbad06d730fb7e66bc5f fails on MacOS X 10.10.5 with Python 3.5.0

### ISSUE THREAD

**Issue by HubertHolin** [numpy/numpy#6338]
Paris (U.E.), le 22/09/2015

   Hi

      With Python 3.5.0 and numpy e7689a2600a28e75d187bbad06d730fb7e66bc5f I have the following failure:

```
Last login: Mon Sep 21 21:29:12 on console
hubert-holins-mac-pro:~ hubertholin$ cd /Volumes/Mechanus/Developer/Git_repositories/Python/numpy
hubert-holins-mac-pro:numpy hubertholin$ sudo -H pip install -e . --no-index
Password:
Ignoring indexes: https://pypi.python.org/simple
Obtaining file:///Volumes/Mechanus/Developer/Git_repositories/Python/numpy
Installing collected packages: numpy
  Running setup.py develop for numpy
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 -c "import setuptools, tokenize; __file__='/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    Running from numpy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/setup.py", line 260, in <module>
        setup_package()
      File "/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/setup.py", line 244, in setup_package
        from numpy.distutils.core import setup
      File "/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/numpy/distutils/__init__.py", line 21, in <module>
        from numpy.testing import Tester
      File "/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/numpy/testing/__init__.py", line 14, in <module>
        from .utils import *
      File "/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/numpy/testing/utils.py", line 17, in <module>
        from numpy.core import float32, empty, arange, array_repr, ndarray
      File "/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/numpy/core/__init__.py", line 14, in <module>
        from . import multiarray
    ImportError: cannot import name 'multiarray'
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3 -c "import setuptools, tokenize; __file__='/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Volumes/Mechanus/Developer/Git_repositories/Python/numpy
hubert-holins-mac-pro:numpy hubertholin$ 
```

Hubert Holin

**Comment by charris** [comment]
This is usually a problem at the user end. Here I would guess it is the use of pip install. @matthew-brett Comment?

**Comment by matthew-brett** [comment]
I don't know what the problem is, it works for me with that commit and Python.org Python 3.5:

```
sudo -H pip3.5 install -e . --no-index
```

What do you get for `which pip` ?

**Comment by HubertHolin** [comment]
Hi

```
hubert-holins-mac-pro:~ hubertholin$ which pip
/Library/Frameworks/Python.framework/Versions/3.5/bin/pip
```
`pip` itself is 49f3682ccf45a4bd82af0649b03a60c1af0fb143 ( as an update to python 3.5.0's pip, as recommended; perhaps I should not have used the development version…).

Python 3.5.0 was compiled from the Python.org source distribution, being configured by:

```
CC=clang INSTALL=/usr/bin/install ./configure --enable-big-digits --enable-framework --enable-universalsdk --with-universal-archs=intel --enable-loadable-sqlite-extensions --enable-ipv6 --without-gcc --with-system-ffi --with-system-expat --with-system-libmpdec --with-signal-module --with-threads --with-dbmliborder=gdbm
```

(as an aside, the decimal module could not be built as one of the platforms implied by `--with-universal-archs=intel` is not supported by libmpdec) and installed by:

```
sudo -H make frameworkinstall
```

HH

**Comment by matthew-brett** [comment]
I'm afraid I don't have any experience building with a custom Python.   I guess you could try released pip to see if that helps?  I suppose you don't get the same problem with Python 3.5 installed with the Python.org installer?

**Comment by HubertHolin** [comment]
I reinstalled (custom) Python 3.5.0, did not update pip and got the same problem :-<
It looks as though I will have to go for the standard Python 3.5.0. installer… Not too happy about that, but that's still better than not having numpy.

HH

**Comment by HubertHolin** [comment]
I junked the whole 3.5 folder, installed stock Python 3.5.0 from Python.org (via the installer), then installed in turn: wheel, click, first, six, pygments, markupsafe, jinja2, docutils, snowball_py, pytz, babel, sphinx, nose, cython… and got the same failure with numpy! I am afraid that not installing these package would be a problem. As it stands, all of these packages but pytz are development versions, so I can try yet again with the stable versions, but I wonder if the problem really lies there.

HH

**Comment by HubertHolin** [comment]
With the same setup as just above but this time using `numpy-1.9.3.tar.gz` (via pypi) and installing thru

```
sudo -H pip3 install . --no-index
```

i.e., non development install, then the installation is a success (which is good!). It therefore really looks like using the github checkout without any prior installation of numpy from that checkout, and using the development install is the problem. In that latter case the installation procedure seems to be looking for an already installed bumpy so as to proceed, as seems to be hinted at by these last few lines of the failure report

```
File "/Volumes/Mechanus/Developer/Git_repositories/Python/numpy/numpy/core/__init__.py", line 14, in <module>
        from . import multiarray
    ImportError: cannot import name 'multiarray'
```

HH

**Comment by HubertHolin** [comment]
Finally, using my initial setup and `numpy-1.9.3.tar.gz` (via pypi) and installing thru
```
sudo -H pip3 install . --no-index
```
I was also able to install. Ergo, the fresh github checkout is the most likely cause of failure. At any rate, I can now go forward.

HH
