### ISSUE TITLE
zip/gz files produced by python setup.py sdist may have missing files

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6343]
In particular, `cblasfiles.c` and `python_xerbla.c` are missing when using `numpy-vendor`.The problem probably originates here:
```
    if blas_info and ('HAVE_CBLAS', None) in blas_info.get('define_macros', []):
        extra_info = blas_info
        multiarray_src.extend([join('src', 'multiarray', 'cblasfuncs.c'),
                               join('src', 'multiarray', 'python_xerbla.c'),
                               ])
```
Which makes the list dependent on the environment. Does anyone have a good idea about how to work around that?

**Comment by charris** [comment]
A workaround is to install atlas in numpy-vendor, but that is just a bandaid.

**Comment by pv** [comment]
Maybe adding them as `depends=` works?

**Comment by juliantaylor** [comment]
just putting them in the manifest would also work

**Comment by juliantaylor** [comment]
I assume this is a regression in 1.10? they have not been missing when I used my vendor fork for 1.9.x

**Comment by charris** [comment]
@juliantaylor The files are new in 1.10.

**Comment by juliantaylor** [comment]
xerbla.c was always there

**Comment by charris** [comment]
Not in multiarray. There are two copies.
