### ISSUE TITLE
numpy.linalg.cond error

### ISSUE THREAD

**Issue by sunqm** [numpy/numpy#6351]
Hello there,

For high dimension arrays, numpy.linalg.cond function does not return the right answer. Eg

>>> a=numpy.random.random((4,3,3))
>>> print numpy.linalg.cond(a).shape
(3,)

It should be a 4-item array.

Qiming

**Comment by njsmith** [comment]
Confirmed present in master. Haven't tried tracking down the actual cause,
but the numbers returned don't even make any sense to me -- e.g. it doesn't
seem to be slicing on the wrong axis or something simple like that.

On Wed, Sep 23, 2015 at 7:40 PM, Qiming Sun <notifications@github.com>
wrote:

> Hello there,
>
> For high dimension arrays, numpy.linalg.cond function does not return the
> right answer. Eg
>
> a=numpy.random.random((4,3,3))
> print numpy.linalg.cond(a).shape
> (3,)
>
> It should be a 4-item array.
>
> Qiming
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6351>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by argriffing** [comment]
It looks like it's not documented to accept high-dimensional arrays.
http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.cond.html
Until that is implemented, maybe just raise an exception when the input is too complicated?

**Comment by seberg** [comment]
The fix seems trivial to me, just change the function to:
```
    x = asarray(x) # in case we have a matrix
    if p is None:
        s = svd(x, compute_uv=False)
        return s[..., 0]/s[..., -1]
    else:
        return norm(x, p, axis=(-2, -1))*norm(inv(x), p, axis=(-2, -1))
```

**Comment by seberg** [comment]
OK, created a PR for it, if anyone wants to review/check it.
