### ISSUE TITLE
1.9 release notes do not mention API change to nansum

### ISSUE THREAD

**Issue by jdmarch** [numpy/numpy#6353]
While I agree that it's logical that the result is zero, apparently many users have code that expects otherwise. This API change should be documented in the release notes.

**Comment by njsmith** [comment]
True -- I guess it's a bit late to put it into the 1.9.0 docs, but for
people who upgrade multiple versions at a time (and so will be reading
through the 1.9 notes later on) then it might make sense to add it to the
copy of the 1.9 release notes that are in 1.9.4/1.10/master.
.
Want to make a pull request? If I remember correctly the release notes are
in docs/release
.
CC @matthew-brett for possible 1.9.4 relevance

On Thu, Sep 24, 2015 at 9:49 AM, Jonathan March <notifications@github.com>
wrote:

> While I agree that it's logical that the result is zero, apparently many
> users have code that expects otherwise. This API change should be
> documented in the release notes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6353>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by melissawm** [comment]
Is there any action pending here, or can we close this?

**Comment by mattip** [comment]
Closing, thanks.
