### ISSUE TITLE
np.savetxt raises an Exception when passed a file handle that was opened with 'w'

### ISSUE THREAD

**Issue by andyfaff** [numpy/numpy#6356]
I am trying to write an array to disk with `np.savetxt`, using a file handle opened with 'w'.  I get the following Exception. (python 3.4.3, numpy 1.9.2, OS X).  It works when the file is opened with 'wb'. This is either a bug in numpy, or the documentation needs to say that the file has to be opened in binary mode.

```
>>> import numpy as np
>>> a = np.arange(10.)
>>> with open('test.dat', 'w') as f:
...        np.savetxt(f, a)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-57-cf77f423517e> in <module>()
      2 a = np.arange(10.)
      3 with open('test.dat', 'w') as f:
----> 4     np.savetxt(f, a)

/Users/anz/Documents/Andy/programming/dev3/lib/python3.4/site-packages/numpy/lib/npyio.py in savetxt(fname, X, fmt, delimiter, newline, header, footer, comments)
   1085         else:
   1086             for row in X:
-> 1087                 fh.write(asbytes(format % tuple(row) + newline))
   1088         if len(footer) > 0:
   1089             footer = footer.replace('\n', '\n' + comments)

TypeError: must be str, not bytes
```

**Comment by musically-ut** [comment]
I think opening a file in merely `'w'` mode works in Python 2.x. 

`'wb'` is necessary only for Python 3.x. The docs should be altered to reflect this.

**Comment by mattip** [comment]
Fixed at some point, if writing `asunicode(x)` fails, `savetxt` will encode using the `encoding` and write as bytes.
