### ISSUE TITLE
Fix vdot or revert making ravel create less copies

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#6358]
The changed `vdot` code relied on `ravel` always returning a contiguous array. With the also changed `ravel` code to *always* return a view when possible, `ravel` can return arrays with a non-contiguous memory layout:
```
In [6]: arr = np.zeros((5, 5, 5))[..., 0].ravel()

In [7]: arr.flags
Out[7]: 
  C_CONTIGUOUS : False
```

Previously, this would return a contiguous copy with the exception of "keeporder":
```
In [5]: arr = np.zeros((5, 5, 5))[..., 0].ravel('K')

In [6]: arr.flags
Out[6]: 
  C_CONTIGUOUS : False
In [7]: np.__version__
Out[7]: '1.8.2'
```

While the `vdot` code may be just be called buggy, the question is whether we should avoid potential problems for other C-interfacing code and instead of changing `vdot` just revert `ravel` and document this behaviour.
Users who would prefer the new definition can be pointed to use `arr.reshape(-1)` for most purposes ("keeporder" is an exception).

**Comment by charris** [comment]
vdot should be able to deal with non-contiguous as long as it is 1-D.

**Comment by charris** [comment]
The problem looks to be here: https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/multiarraymodule.c#L2313.

**Comment by charris** [comment]
That said, I've always expected, perhaps wrongly, that the results of ravel would be contiguous. The documentation is perhaps misleading in that regard.
```
a : array_like
    Input array.  The elements in `a` are read in the order specified by
    `order`, and packed as a 1-D array.
```
Tne word "packed".

**Comment by seberg** [comment]
No, your expectation was always correct, except for "keeporder" which was "only" added in 1.7 and nobody really uses. Mine was wrong, I always expected it to be the same as reshape.

I guess I will revert the changes then just to be on the safe side *and* we should use reshape(-1) logic for vdot + fix that line you linked? Keeporder should probably be made consistent then, and a note to the doc would point people to reshape in case someone cares.

Does that sound good?

**Comment by charris** [comment]
Yes. We should also clearly document what the functions do.

**Comment by njsmith** [comment]
Probably in a perfect world we would find a way to make ravel equivalent to
reshape and get rid of this non-orthogonal contiguity guarantee, but I'm
not feeling inspired to try and accomplish that right now when we have much
more important cleanups to work on.
.
(Maybe the docs should equivocate a little, at least: like document that it
is contiguous, but that you shouldn't rely on that and should request
contiguity explicitly if that's something you care about?)

**Comment by insertinterestingnamehere** [comment]
FWIW, I'd like to see the contiguity guarantee removed. As I understand it, ravel gives a flattened view of an array whenever possible to avoid the speed/space cost of an extra copy. It is best for contexts where the user does not intend to write to the output and wants the extra performance benefit. It is also good in places where the memory layout of an array is already known. Requiring that the output be contiguous seems to make its purpose a little more murky for an end user. Why would we want a dedicated function for "reshape to a flat attay as fast as possible but also make sure the output is contiguous?" The natural way to guarantee contiguity is an additional call to ascontiguousarray.

**Comment by charris** [comment]
@insertinterestingnamehere  I'm most concerned that ravel may have been used to set up arrays before passing them to extensions written in C or Fortran.

**Comment by insertinterestingnamehere** [comment]
@charris Yes, that is a very reasonable concern. I'm not sure how much we really need to protect against it though since we're changing ravel to do what the documentation has always said it would. That said, mentioning more of the consequences of relaxed strides explicitly in the release notes would be good.

**Comment by insertinterestingnamehere** [comment]
Hmm. Looking at this more thoroughly, it appears that the C-contiguous guarantee was sort-of documented in the [comments before the routine `PyArray_Ravel`](https://github.com/numpy/numpy/blob/467d4e16d77a2e7c131aac53c639e82b754578c7/numpy/core/src/multiarray/shape.c#L924). Also, I'm no longer sure this is related to relaxed stride checking, though it runs in the same vein. Sorry about that.
Other than that, it still makes more sense in my mind to go with the version that better matches the longstanding Python documentation, though, from a maintenance standpoint, there are compelling reasons not to do so.
