### ISSUE TITLE
Is `np.empty(..., dtype=object)` guaranteed to fill the array with None?

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#6367]
Currently, `np.empty(..., dtype=object)` fills the array with `None`, which is certainly a very reasonable (though undocumented, afaict) behavior.  Is this guaranteed?  (Note that the other "more obvious" way of creating such an array, `np.fill(..., None)`, does not work, see #6366.)

**Comment by njsmith** [comment]
I guess so? It has to be filled with something, and there's probably code
that depends on it being None, so I don't imagine we ever could or would
want to change it. Want to submit a patch documenting this in empty's
docstring, to nail it down?
