### ISSUE TITLE
iOS (arm) compile defines both BIG and LITTLE endian

### ISSUE THREAD

**Issue by othalan** [numpy/numpy#6380]
Compiling NumPy for iOS (armv7 and arm64 architectures) `numpy/core/include/numpy/npy_endian.h` does not correctly configure the endian #defines.

Because this is an iOS application, I am cross-compiling NumPy on OSX with the following setup:

**NumPy Version:** v1.9.3 **AND** git branch 1.10.x
**Host OS:** OSX 10.10.5
**Xcode:** 7.0
**iOS Minimum Version:** 8.0

During compilation, errors are encountered which are fixed by forcing CPU endian detection instead of relying on endian.h.  Example in the 1.10.x branch:

```
numpy/core/src/multiarray/arrayobject.c:437:1: error: redefinition of 'extend' as different kind of symbol
extend(char **strp, Py_ssize_t n, Py_ssize_t *maxp)
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/include/MacTypes.h:574:3: note: previous definition is here
  extend                        = 0x40
  ^
```

Example from v1.9.3:

```
In file included from numpy/core/src/npymath/npy_math.c.src:56:
numpy/core/src/npymath/npy_math_private.h:78:3: error: typedef redefinition with different types ('union ieee_double_shape_type' vs 'union ieee_double_shape_type')
} ieee_double_shape_type;
  ^
numpy/core/src/npymath/npy_math_private.h:64:3: note: previous definition is here
} ieee_double_shape_type;
  ^
```

I suspect this is related to the fact that arm supports both BIG and LITTLE endian modes.

**Comment by njsmith** [comment]
I don't think any of the numpy core maintainers knows anything about python
on iOS. We're not against it, we just don't know anything, can't test
anything, etc. So I guess your best bet is to submit pull requests that are
clearly described and clearly don't break non-embedded builds, i.e. make it
as easy as possible for us :-). It might also make sense to ping the
mailing list to see if there are others in the same boat and whether you
can start pooling your efforts -- I'm guessing you aren't the first person
to encounter these issues.

**Comment by saturnman** [comment]
This is not a problem of numpy itself, this is a bug of numpy's build script. when the script create shell command like 'clang -arch arm64 -arch i386 -arch x86_64',  this command can cause clang create misleading builtin macro definitions, compiler error msg comes from wrong macro condition check branch.

**Comment by mattip** [comment]
Closing, since this is more of a distutils/setuptools question and not really numpy-specific. Please reopen if there is missing support in numpy/distutils for this type of compilation.
