### ISSUE TITLE
Updating the docstring of loadtxt

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#6387]
The docstring of the first argument of loadtxt currently states

```
    fname : file or str
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
```

In fact the generator can yield strings:

```
In [1]: np.loadtxt(iter(["1 2 3", "4 5 6"])) # or io.StringIO
Out[1]: 
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])
```

Not making a patch yet because we may as well clarify encoding issues at the same time... or not? Something like "If the file or generator is yielding unicode strings, they will be decoded as..."

**Comment by Palash-Vishnani** [comment]
Is this issue still open?? Can I work on updating the docstring of loadtxt?

**Comment by melissawm** [comment]
Hi @Palash-Vishnani, yes - please feel free to submit a PR if you can address this issue.

**Comment by kevintprivett** [comment]
This seems to have been corrected.  [Doc for loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html?highlight=loadtxt#numpy.loadtxt) shows that the fname argument accepts generators that output strings as well as byte strings and ver 1.14.0 added an encoding argument.
