### ISSUE TITLE
BUG: searchsorted on an object array of tuples returns incorrect result

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#6390]
This is present in both NumPy 1.9.3 and master:
```
In [28]: import numpy as np

In [29]: y = np.empty(3, dtype=object)

In [30]: y[0] = (0,)

In [31]: y[1] = (0,)

In [32]: y[2] = (9,)

In [33]: y
Out[33]: array([(0,), (0,), (9,)], dtype=object)

In [34]: y.searchsorted((5,))  # this is a 1d array for some reason?!?
Out[34]: array([0])

In [35]: np.array([0, 0, 9]).searchsorted(5)  # this is what I expected
Out[35]: 2
```

xref https://github.com/pydata/pandas/issues/11201

**Comment by njsmith** [comment]
This is on ~~python 2~~ legacy python, right?

**Comment by njsmith** [comment]
I think what's happening is that the you search for `(5,)`, then that's getting interpreted as a vectorised search for an 1d array containing 5, not a 0d array containing `(5,)`. And on ~~py2~~ legacy python, all objects are comparable and apparently `5` is less than `(0,)`.

This is not a bad idea for deprecating the auto-promotuon of tuples to arrays...

**Comment by shoyer** [comment]
OK, then. Not a bug, just the auto-promotion of tuples to arrays on Legacy Python. If I make a 0d ndarray containing the tuple, searchsorted works properly:
```
In [17]: z = np.empty(1, dtype=object)

In [18]: z[0] = (5,)

In [19]: z.shape = ()

In [20]: z
Out[20]: array((5,), dtype=object)

In [21]: y.searchsorted(z)
Out[21]: 2
```

I'm not sure how or if we'll work around this on the pandas side, but apparently it's on us.

**Comment by njsmith** [comment]
To be clear: The auto promotion should behave the same on py2 and py3, but
on py3 you'd then get an error trying to compare an int and a tuple, so
it'd be more obvious what had happened.

**Comment by jseabold** [comment]
Came here from a similar issue in pandas via dask. Is this behavior expected on Python 3.5.1 NumPy 1.11.0? I would have expected an error.

>>> np.searchsorted(np.arange(50), 'b')
50

>>> np.searchsorted(np.arange(50), '!')
0

**Comment by shoyer** [comment]
@jseabold That looks like a bug to me, but it's a different one than the one I reported here.

**Comment by jseabold** [comment]
https://github.com/numpy/numpy/issues/7700
