### ISSUE TITLE
generalizing meshgrid a little more

### ISSUE THREAD

**Issue by AndySchroder** [numpy/numpy#6398]
A few versions ago, meshgrid added the option for more than two dimensions. I would like to see intelligence in meshgrid such that if you only pass a single one dimensional coordinate array, that array will just be transparently returned back as it was passed in. This way the usage of meshgrid can work for any arbitrary number of dimensions, including 1. As it is now, if you have a code that uses meshgrid with a variable number of dimensions, you have to specifically catch the 1 dimensional case and skip meshgrid for that. meshgrid should automatically do so for you.

Also, why does the documentation refer to the coordinate arrays as x1, x2, x3, ...., xn? Should it start counting at 0, making them x0, x1, x2, ...., xn, like normal python conventions?

**Comment by seberg** [comment]
This seems to have been implemented (at least in 1.16, probably earlier).
