### ISSUE TITLE
Special-casing particular scalars for np.power

### ISSUE THREAD

**Issue by ajcr** [numpy/numpy#6399]
Pointed out on SO [here](http://stackoverflow.com/q/32903967/3923281).

For the scalar exponents -1, 0, 0.5, 1 and 2, it is significantly faster to write `arr ** exp` than `np.power(arr, exp)` because the former catches these scalars and handles them using more appropriate functions.

For example:

```
>>> a = np.arange(10000)
>>> %timeit a**2
100000 loops, best of 3: 10.9 µs per loop
>>> %timeit np.power(a, 2)
10000 loops, best of 3: 127 µs per loop
```

Would it make sense for `np.power` to also handle these scalars in this way?

**Comment by adler-j** [comment]
I certainly agree about this and this is actually one of the prime causes of other issues, like `np.linalg.norm` being very slow (#7786). It does however seem like this is already supposed to be implemented [here](https://github.com/numpy/numpy/blob/1429c606643d1ad305e710c4a31cb6f398d04c53/numpy/core/src/multiarray/number.c#L495-L572), but that this code is for some reason not called.

**Comment by seberg** [comment]
This would probably require a hack in the ufunc inner loop (should be in `loops.c.src`):

 1. Check if the stride of the second argument is 0.
 2. If it is 0, run a special loop.

Since I guess it does not hurt performance for the normal case, it might be worth it.

**Comment by eendebakpt** [comment]
On recent numpy the overhead is much lower:
```
In [4]: %timeit a**2
12.7 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [5]: %timeit np.power(a, 2)
25.5 µs ± 2.51 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

**Comment by eendebakpt** [comment]
But not for float type though:
```
import numpy as np
a=np.arange(10_000)
a=a.astype(float)
%timeit a**2
%timeit np.power(a, 2)
```
```
5.39 µs ± 415 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
468 µs ± 33.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

**Comment by seberg** [comment]
No, that is the object loop, not the one for floats/ints.  That one is probably in SIMD code by now.  For Python ints specifically, there is another option these days to have a special loop (used for comparisons mostly), but that is likely not really worth it.
