### ISSUE TITLE
numpy.lib.Arrayterator doesn't appear in docs

### ISSUE THREAD

**Issue by larsmans** [numpy/numpy#6404]
I just found out about this class from perusing the NumPy source code; it doesn't appear anywhere in the documentation, even though it's been around since 2008.

**Comment by larsmans** [comment]
I tried to add it myself, but I don't know how to. No matter what I do, I keep getting this cryptic error message

```
Exception occurred:
  File "/home/larsmans/src/numpy/doc/sphinxext/numpydoc/docscrape.py", line 211, in parse_item_name
    raise ValueError("%s is not a item name" % text)
ValueError: `Arrayterator` is not a item name
```

from `make html`.

**Comment by rgommers** [comment]
Fixed by gh-6445. Once again if Sphinx would have told you the file and line number that was causing the problem this would have been trivial to solve....

**Comment by charris** [comment]
This class does not appear to exist. I discovered that while fixing the typo 'Arrayterator' that was breaking the document build. Now the docs build but the entry has zero content.  @larsmans @rgommers Where did you find it?

**Comment by rgommers** [comment]
It does exist: https://github.com/numpy/numpy/blob/master/numpy/lib/arrayterator.py

**Comment by charris** [comment]
Hmm, OK, had wrong numpy version installed. Arrayterator still looks like a typo, should we change it?

**Comment by rgommers** [comment]
Not sure what you mean, the class is really called ``Arrayterator`` and ``lib/__init__.py`` has ``from .arrayterator import Arrayterator`` ?

**Comment by charris** [comment]
I mean the name `Arrayterator`, it's a bit odd. `ArrayIterator` would be the conventional form.

**Comment by argriffing** [comment]
It's not a typo, it's hacker wordplay like the Julia Arraypocalypse.

**Comment by larsmans** [comment]
I had interpreted it as a pun too, but a pun that I personally could live without.

**Comment by charris** [comment]
Which is fine if you are playing around, but it seems out of place in Numpy. Like a tattoo, it may not age well.

**Comment by rgommers** [comment]
Ah ok. I don't like the name much either. ``ArrayIterator`` isn't right though - if we're changing the name (which is probably not the best idea), then it needs to reflect that this class is not specific to ndarrays and it's a *buffered* iterator.

**Comment by charris** [comment]
Checking... Darn, i was hoping it was new, but it has been around since 2008. Guess there is nothing to be done :(

**Comment by larsmans** [comment]
It was undocumented all this time, but some client code can be found by extensive searching. There may be more lurking on people's hard drives.
