### ISSUE TITLE
setup.py clean breaks subsequent build_ext

### ISSUE THREAD

**Issue by larsmans** [numpy/numpy#6410]
After doing a `python setup.py clean`, I can't rebuild NumPy:

```
$ python setup.py build_ext -i
Running from numpy source directory.
Traceback (most recent call last):
  File "setup.py", line 260, in <module>
    setup_package()
  File "setup.py", line 244, in setup_package
    from numpy.distutils.core import setup
  File "/home/larsmans/src/numpy/numpy/distutils/__init__.py", line 21, in <module>
    from numpy.testing import Tester
  File "/home/larsmans/src/numpy/numpy/testing/__init__.py", line 14, in <module>
    from .utils import *
  File "/home/larsmans/src/numpy/numpy/testing/utils.py", line 17, in <module>
    from numpy.core import float32, empty, arange, array_repr, ndarray
  File "/home/larsmans/src/numpy/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name multiarray
```

The problem is that `numpy/__config__.py` and `numpy/distutils/__config__.py` persist. It would be nice if `setup.py clean` could clean those up as well.

**Comment by shoyer** [comment]
:+1: I've been stymied by the same thing.

**Comment by rgommers** [comment]
Looks like a ``setuptools`` bug. It shouldn't be ignoring ``py_modules``, seeing as that's what's being used as an example in its ``Distribution.include()`` docstring.

Might be able to work around that by adding ``__config__.py`` also to ``self.data_files`` in https://github.com/numpy/numpy/blob/master/numpy/distutils/misc_util.py#L2053 or a slightly more elaborate way of implementing an ``add_py_modules`` method: https://github.com/numpy/numpy/blob/master/numpy/distutils/misc_util.py#L1311

**Comment by rgommers** [comment]
Setuptools code I refer to: https://bitbucket.org/pypa/setuptools/src/11264de04d44e4cb82e1e797e91549a6a71fb99b/setuptools/dist.py?at=default&fileviewer=file-view-default#dist.py-462

**Comment by rgommers** [comment]
Or maybe more a ``distutils`` bug. I can't find anything in ``setuptools`` that improves the ``clean`` command, even though that's what this comment in ``setup.py`` suggests:

    # Run build
    if len(sys.argv) >= 2 and ('--help' in sys.argv[1:] or
            sys.argv[1] in ('--help-commands', 'egg_info', '--version',
                            'clean')):
        # Use setuptools for these commands (they don't work well or at all
        # with distutils).  For normal builds use distutils.

**Comment by seberg** [comment]
Running `setupy.py clean` has been disabled and gives a nice error (and I guess it would be pretty unused now anyway).

**Comment by dimpase** [comment]
This error still shows up if you invoke `pip wheel` with `--no-use-pep517`, something one has to use if there are `--build-options` to pass.

**Comment by rgommers** [comment]
> This error still shows up if you invoke `pip wheel` with `--no-use-pep517`,

That's not going to be supported in the semi-near future, so I wouldn't worry about that one too much. We shouldn't re-enable `setup.py clean`, because it doesn't work properly.

**Comment by dimpase** [comment]
@rgommers - it's a fallout of #20780 I just opened.
