### ISSUE TITLE
Incorrect hashbang for Numpy wheels

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#6412]
When installing Numpy via the wheels, the hashbang for the f2py script is incorrect, and is set to:

```
#!/Users/travis/build/MacPython/numpy-wheels/venv/bin/python
```

This causes the script to not work. I think this should instead have

```
#!/usr/bin/env python
```

cc @matthew-brett @soylentdeen

**Comment by matthew-brett** [comment]
That's correct - see https://github.com/numpy/numpy/issues/6348 and https://github.com/numpy/numpy/pull/5815 - 1.10 and upcoming 1.9.4 should fix this.
