### ISSUE TITLE
Test failures on py35

### ISSUE THREAD

**Issue by kyleabeauchamp** [numpy/numpy#6419]
Anyone know if the following test failures are known / to be expected?  Feel free to close if they are, or if they are known artifacts of my lazy build procedure...

Numpy built using openblas + anaconda python3.5 on OSX yosemite.  Numpy built and installed via conda-build with recipe given in following pull request https://github.com/conda/conda-recipes/pull/436

```
np.test()
[...]
======================================================================
ERROR: test_rfft (test_fft.TestFFT1D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/opt/envs/py35/lib/python3.5/site-packages/numpy/fft/tests/test_fft.py", line 72, in test_rfft
    x = np.fft.rfft([0, 1+5j, 0+7j, -3j])
  File "~/opt/envs/py35/lib/python3.5/site-packages/numpy/fft/fftpack.py", line 359, in rfft
    a = array(a, copy=True, dtype=float)
TypeError: can't convert complex to float

======================================================================
FAIL: test_blasdot.test_blasdot_used
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/opt/envs/py35/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "~/opt/envs/py35/lib/python3.5/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "~/opt/envs/py35/lib/python3.5/site-packages/numpy/core/tests/test_blasdot.py", line 31, in test_blasdot_used
    assert_(dot is _dotblas.dot)
  File "~/opt/envs/py35/lib/python3.5/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 5953 tests in 33.404s

FAILED (KNOWNFAIL=4, SKIP=9, errors=1, failures=1)
```

**Comment by seberg** [comment]
First, not sure. The second one is due to not deleting all of the old numpy install.

**Comment by aldanor** [comment]
Seeing the same issue with `test_rfft` on Python 3.4, Linux.

**Comment by suhangpro** [comment]
rfft expects real inputs, so I don't understand why "[0, 1+5j, 0+7j, -3j]" is used as a test case. This test case however is not found on the master branch now.

**Comment by rgommers** [comment]
The ``test_rfft`` issue you're both seeing is also due to not removing an old install. ``numpy/fft/tests/test_fft.py``isn't present as far back as numpy 1.8.0

**Comment by rgommers** [comment]
You need to either install numpy with pip/conda or manually delete the old build. Probably you've used something like ``python setup.py install`` at some point.

**Comment by aldanor** [comment]
Pretty sure that's not the case since I've specifically ran the tests in a clean new conda environment. Will double-check on Monday.

**Comment by rgommers** [comment]
@aldanor in that case can you report the numpy version of your install and map the failure you see to where it comes from in the numpy source code on github (just browse https://github.com/numpy/numpy)? Maybe there's something to fix here, but I'm not seeing it.

**Comment by aldanor** [comment]
Will do, thanks. Maybe it's some weird packaging problem that's causing this.
