### ISSUE TITLE
Incorrect version in 1.10.0.post1 setup.py

### ISSUE THREAD

**Issue by papachoco** [numpy/numpy#6423]
Hi,

The version in setup.py has not been updated to reflect the source version 1.10.0.post1

MAJOR               = 1
MINOR               = 10
MICRO               = 0
ISRELEASED          = True
VERSION             = '%d.%d.%d' % (MAJOR, MINOR, MICRO)

Thanks

Carlos

**Comment by charris** [comment]
The file was just renamed, the only difference was that it was signed. Hmm, does this cause an installation problem? (pipy, Grrr...)

**Comment by papachoco** [comment]
Sadly it does

**Comment by charris** [comment]
@*&%)&, I mean, darn. Time for a post2 release as pipy doesn't allow fixing files or reusing names.

Thanks for the report, now I know.

**Comment by charris** [comment]
Should be fixed. Could you give it a try?

**Comment by papachoco** [comment]
It works.. Thanks a lot

**Comment by charris** [comment]
Great. Thanks again.
