### ISSUE TITLE
Build checks failing on _configtest.c: no-return-in-nonvoid-function  

### ISSUE THREAD

**Issue by toddrme2178** [numpy/numpy#6427]
I am currently trying to build numpy for openSUSE, and I am getting the following issue, which is considered a serious issue and thus results in a build failure:

    E: python-numpy no-return-in-nonvoid-function _configtest.c:10

This error is due to `_configtest.c` having a function that is non-void, but doesn't return anything.  However, I am can't find `_configtest.c` (it seems to be generated on-the-fly) so I can't figure out exactly where the problem is.

**Comment by charris** [comment]
Curious. What compiler/version and numpy version? Any special flags for the compiler? Do you have CFLAGS defined?

**Comment by charris** [comment]
If this is new, a bisect search for the guilty commit might help.

**Comment by toddrme2178** [comment]
It only happens on numpy 1.10.0.  It did not happen on numpy 1.9.3 or earlier.  It happens with Python 2.6.8, 2.6.9, 2.7.6, 2.7.7, 2.7.8, 2.7.9, 3.3.2, and 3.4.1, and gcc 4.3.4, 4.8.1, and 4.8.3.  CFALGS are:

    CFLAGS='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fno-strict-aliasing'.

**Comment by toddrme2178** [comment]
I am trying to bisect now.

**Comment by toddrme2178** [comment]
The commit responsible for the issue is 7ee56eb6f5cf60a4a1910faf0f1d4c494eefedfc.

**Comment by ewmoore** [comment]
Hmmm. That commit doesn't change any of the config checks.

**Comment by juliantaylor** [comment]
numpy always produced these warnings during configuration, its your linter than got more strict.
You can override that, they are harmless. Its just a compile check, the functions are executed.

**Comment by toddrme2178** [comment]
The problem isn't a change in the linter.  Building with numpy as of commit 7ee56eb6f5cf60a4a1910faf0f1d4c494eefedfc fails, but an otherwise identical build with numpy as of commit f8ce5d1b3f323ab2d3568bacf145055a6cfa21ad (the commit immediately before that) succeeds.

**Comment by toddrme2178** [comment]
Nevermind, it is *not* 7ee56eb6f5cf60a4a1910faf0f1d4c494eefedfc.  If I try building at what github says is 7ee56eb6f5cf60a4a1910faf0f1d4c494eefedfc, it fails.  But if I just apply the 7ee56eb6f5cf60a4a1910faf0f1d4c494eefedfc patch to the f8ce5d1b3f323ab2d3568bacf145055a6cfa21ad commit, it doesn't.  Give me a bit more time to figure out exactly what patch is causing the problem.

**Comment by juliantaylor** [comment]
these warnings go back a long time, their present in 1.7 and likely in much earlier versions too. I think rpmlint is just a bit flaky in detecting them.
I'd not waste time trying to bisect, there will be no single commit that can be blamed in numpy, but it can probably be fixed by updating the configuration check template.
outside of configuration checks these warnings do not appear, travis would have told us that (% bugs in travis config)

**Comment by toddrme2178** [comment]
I have determined the exact commit responsible.  With the patch from commit 251acc007a07a2ed06a4b4666df82c8160c89f58 applied, the tests fail.  Without it, they pass.

**Comment by toddrme2178** [comment]
I have narrowed it down further, the failures start with patch 4769fe79bb5c2d4649fa2845009a0ceae94524c2, specifically the change in that patch to file `numpy/core/setup.py`.

**Comment by juliantaylor** [comment]
still doesn't change that your linter is flakey, this check goes back to 2009.
feel free to file a PR fixing it, its just adding a return 0 to some of the templates.

**Comment by rgommers** [comment]
It would help to list here what linter and version of it is the problem. It may be a check that should pass, but if it doesn't for one user within days of releasing 1.10.0 then for sure others will run into it as well. 

@juliantaylor it may be helpful to spell out exactly where to insert the ``return 0``.

@toddrme2178 if you could try the proposed fix and list your lint version, that would be great.

**Comment by juliantaylor** [comment]
its rpmlint, the templates are in autodist.py, I can fix it later today, its not a big issue for numpy, only packagers should run into this.

**Comment by rgommers** [comment]
thanks Julian

**Comment by toddrme2178** [comment]
That fixed it, thanks a lot!
