### ISSUE TITLE
NumpyVersion does not handle the `post` suffix correctly.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6431]
```
In [1]: from numpy.lib import NumpyVersion

In [2]: NumpyVersion('1.10.0.post2') >= '1.10.0'
Out[2]: False

In [3]: NumpyVersion('1.10.0.post2') >= '1.10.0.post1'
Out[3]: True

In [4]: NumpyVersion('1.10.0.post2') > '1.10.0.post1'
Out[4]: False

In [5]: NumpyVersion('1.10.0.post1') > '1.10.0'
Out[5]: False

In [6]: NumpyVersion('1.10.0.post1') == '1.10.0'
Out[6]: False

In [7]: NumpyVersion('1.10.0.post1') < '1.10.0'
Out[7]: True
```

**Comment by sumitbinnani** [comment]
Can I work on it?

**Comment by njsmith** [comment]
You can, but I'm not sure what the right solution is :-)

Option 1 would be to just never use the .post suffix again, so the problem
goes away :-)

Option 2 would be to find and steal an existing PEP 440 implementation from
somewhere (distlib?)

Option 3 would be to hack up NumpyVersion to handle what we need directly.

On Thu, Oct 8, 2015 at 11:18 PM, Sumit Binnani <notifications@github.com>
wrote:

> Can I work on it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6431#issuecomment-146767045>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by rgommers** [comment]
+1 for option 1.

option 2: I looked quite hard for an implementation that did the right thing before writing ``NumpyVersion``. I never even considered checking for ``.postN``, and I have never seen it used in any project. 

(and given that ``NumpyVersion`` is for comparing numpy versions and not a complete PEP440 implementation, it wasn't a bug until a few days ago)

**Comment by charris** [comment]
After rereading PEP440 a couple of times, I'm inclined towards 1. also. PEP440 was *too* flexible, making it difficult to understand, let alone to parse, the allowable versions. It should have come with a reference implementation as a demonstration of concept ;)

**Comment by njsmith** [comment]
Supposedly there is a reference implementation somewhere -- it was in the
pypa repo but now I can't find it. Maybe they moved it into distlib or pip
or something. Anyway, doesn't much matter.

**Comment by charris** [comment]
@rgommers I have seen `.postN` a couple of times, don't recall where, but it seems to be a new option and hence not represented in the geological strata.

**Comment by rgommers** [comment]
So can we close this as wontfix / not a bug?

**Comment by charris** [comment]
Might a well.

**Comment by njsmith** [comment]
Should we add a line or two of code to make import bomb out when the
version number isn't recognized, both to enforce the decision that we won't
use those numbers and remind anyone who tries why not?

**Comment by charris** [comment]
@njsmith That would be appropriate.

**Comment by rgommers** [comment]
That sounds good. Anything other than ``#.##.###`` should start with ``.dev0+`` and then a git hash or ``Unknown``.

**Comment by njsmith** [comment]
So as a regex, does this look right:

^[0-9]+\.[0-9]+\.[0-9]+(\.dev0\+([0-9a-f]+|Unknown))?$

?

**Comment by rgommers** [comment]
Actually no, because my description above is wrong. It doesn't allow for alpha/beta/rc version numbers. Should add ``|a[0-9]|b[0-9]|rc[0-9]``

**Comment by jensenbox** [comment]
FYI: This is breaking the statsmodels package - could be others affected: https://github.com/statsmodels/statsmodels/issues/2645
