### ISSUE TITLE
copysign fails to work inplace with integer arrays

### ISSUE THREAD

**Issue by ev-br** [numpy/numpy#6454]
```
In [2]: a = np.arange(3); a.dtype
Out[2]: dtype('int64')

In [3]: np.copysign(a, -1).dtype
Out[3]: dtype('float64')
```

And then trying to change the sign in-place (which is the original motivation)

```
In [4]: np.copysign(a, -1, a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-7aac9b2aea00> in <module>()
----> 1 np.copysign(a, -1, a)

TypeError: ufunc 'copysign' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [5]: x = np.arange(3, dtype=float)

In [6]: np.copysign(x, -1, x)
Out[6]: array([-0., -1., -2.])

In [7]: np.__version__
Out[7]: '1.10.0'
```

**Comment by seberg** [comment]
The reason is that copysign is only implemented for floating types, so the way it does integer types is by upcasting. You could of course provide the "unsafe" casting which would work, but under the hood, it will still cast to float and back.

**Comment by ev-br** [comment]
Any specific reason integer loops are not implemented? Other than bandwidth, of course :-). If it's the latter, I can give it shot.

**Comment by seberg** [comment]
Frankly, no idea. I expect it is because C has a copysign function only for floating point numbers.

Implementing it will mean a change in behaviour since the return value would be the a different type, so we have to worry a bit about breaking someones code and to be honest, I am unsure how bad that might be.
With that in mind though, please go ahead!

**Comment by mattip** [comment]
Closing. It is not clear how to implement `copysign` for integers. What happens to 0, MIN_INT?
