### ISSUE TITLE
ufunc cannot be cast with rule `same_kind`

### ISSUE THREAD

**Issue by arokem** [numpy/numpy#6464]
Updgrading to 1.10, I noticed the following new behavior: 

```
In [1]: import numpy as np

In [2]: a = np.array([1,2,3])

In [3]: b = 2.0

In [4]: a /= b
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-b9f4626d3ca8> in <module>()
----> 1 a /= b

TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [5]: a = a/b

In [6]: a
Out[6]: array([ 0.5,  1. ,  1.5])

```

See also https://github.com/nipy/dipy/issues/730. Is this an intended new behavior? If so, what does it portend (what should I stop doing?)?

**Comment by charris** [comment]
Probably means you didn't see the deprecation warnings since forever ;) If you want to cast the float result to integer, you can call `true_divide` with `out=a` and `casting='unsafe'` arguments.

**Comment by arokem** [comment]
Thanks @charris! If someone needed more evidence that no one looks at warnings, you can use this as reference in your next argument. Having dug a bit, I see this now with an explanation: http://docs.scipy.org/doc/numpy/reference/ufuncs.html#ufunc

**Comment by lesteve** [comment]
We are affected by this on scikit-learn too. Unless I missed it, there doesn't seem to be anything about this in the 1.10 [release notes](https://github.com/numpy/numpy/blob/master/doc/release/1.10.0-notes.rst). It is mentioned in the 1.9.0 release notes under the "Future changes" [section]( https://github.com/numpy/numpy/blob/master/doc/release/1.9.0-notes.rst#future-changes) though.

Maybe it would be worth moving some of the 1.9.0 release notes "Future changes" over to the 1.10 release notes?

**Comment by shoyer** [comment]
:+1: I also looked for this and didn't find it in the release notes

**Comment by njsmith** [comment]
Maybe someone would like to submit a PR to add it to the release notes? :-)
It sounds like we'll have a 1.10.2 in the not-too-distant-future (e.g. for
the structured array slowdown), so there's still time...

On Wed, Oct 14, 2015 at 1:05 PM, Stephan Hoyer <notifications@github.com>
wrote:

> [image: :+1:] I also looked for this and didn't find it in the release
> notes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6464#issuecomment-148180292>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by charris** [comment]
I have it in mind, will open an issue. I'm thinking of doing a 1.10.2 rc in two weeks or so, reports are still trickling in.

**Comment by siryne** [comment]
I got this error while executing this line : 
**X = preprocess_input(X, mode='tf')**  

I fixed this error by changing tools versions : 
**Numpy – 1.16.1
Pandas – 0.23.0
Matplotlib – 2.2.2
Keras – 2.2.4**

hope this would help.
