### ISSUE TITLE
numpy.interp uses 'left' value even when x[0]==xp[0]

### ISSUE THREAD

**Issue by danielsf** [numpy/numpy#6468]
The following code should demonstrate that numpy.interp uses the padding value specified by the kwarg 'left' even when the 0th element of the x-values being interpolated onto is identical to the 0th element of the input x-values.  This problem arose when I upgraded to numpy version 1.10.1 from version 1.9

```
import numpy as np

x1 = np.arange(1.0, 10.0, 1.0)
y1 = np.power(x1,  2)
x2 = np.arange(1.0, 9.1, 0.5)

np.testing.assert_equal(x1[0],  x2[0])
np.testing.assert_equal(x1[-1],  x2[-1])

y2 = np.interp(x2, x1, y1, left=np.NaN, right=np.NaN)

print y2[0]
```

**Comment by sambarluc** [comment]
I can confirm I am experiencing exactly the same problem here.

**Comment by gibbycu** [comment]
Same here but only when the left values are the "same".  Smells of a floating point rounding error.  I don't know much about the internals but does it have to do with 8925950666b6da64f57ca629c4448cb6800706dc and the change of variable type in the binary_search_with_guess function (lines ~517) and then the subsequent comparison of doubles?

Seems to me this would be a common scenario to interp the value at the boundary and want back that same value.

**Comment by nhmc** [comment]
I've also encountered this bug; it's introduced an annoying bug in specutils (astropy/specutils#123). I can confirm it is a regression in 1.10. See the following examples:
```
>>> np.__version__
'1.9.3'
>>> np.interp(1, [1,2], [2,2], left=np.nan)
2.0
```
```
>>> np.__version__
'1.10.1'
>>> np.interp(1, [1,2], [2,2], left=np.nan)
nan
```

**Comment by dnadeau4** [comment]
@danielsf Thanks for reporting this issue.  I am experiencing the same problem and I can't upgrade to version 1.10.1 until this is fixed.  I get gaps in my data analysis.

**Comment by charris** [comment]
Looks to be due to 48ee0b25.

**Comment by charris** [comment]
Definitely #5843 (8925950).

**Comment by njsmith** [comment]
Paging @jaimefrio...

**Comment by jaimefrio** [comment]
It seems to just be a bunch of `<=` that should have been `<` everywhere in the code that handles the guess. I need to write a few tests to confirm that nothing else breaks with that fix, probably tonight.  But things look pretty good:

```python
In [4]: np.interp([-0.5, 0, 0.5, 1.5,  2, 2.5], [0, 1, 2], [0, 1, 2], -1, -2)
Out[4]: array([-1. ,  0. ,  0.5,  1.5,  2. , -2. ])
```

Also, Google now owns the copyright of any and all code that I write, even in my spare time. And while OSS contributions are encouraged, they want to review my first few patches beforehand, so that I don't embarrass the company by submitting shitty code, e.g. with `<=` where `<` are needed...

So it will take a couple of days before I actually submit a PR, but I'm on to it.

**Comment by charris** [comment]
> It seems to just be a bunch of <= that should have been <

That was my guess 8-) It would be nice if you can get it through the filters by the weekend. if it looks to take longer I can take care of it.

**Comment by charris** [comment]
@jaimefrio How do things look?
