### ISSUE TITLE
git tags for 1.10.0 and 1.10.1 missing

### ISSUE THREAD

**Issue by ahaldane** [numpy/numpy#6492]
Maybe I have misunderstood how git tags work (I just learned about them), but I think we need git tags for the 1.10.0 and 1.10.1 releases and the rc's. At least, I don't see them in the output of `git tag`.

It looks like starting in 1.8.1 Julian Taylor has been tagging the non-rc releases with annotated tags with his GPG signature, judging from the output of `git tag -v v1.8.1`.

**Comment by charris** [comment]
`git fetch upstream --tag`. You don't get them automatically on a pull.

**Comment by ahaldane** [comment]
Oh OK, thanks. Closing.

**Comment by charris** [comment]
Yes, we should probably start annotating the tags. Although probably no one has signed my signature, so I could be anyone. Boo!

**Comment by rgommers** [comment]
@charris see this discussion: https://github.com/scipy/scipy/issues/4919

    In practice, if the key ID and fingerprint are mentioned in the release announcement mail,
    and the mail is signed with the same key, that is already not so easy to forge --- the real 
    release manager would see the forgery and react to it.

That discussion also contains the git and twine commands I now use for scipy.

**Comment by seberg** [comment]
Well, if anyone complains, I am sure we can organize good key signing easily and quickly. I remember Brian said at SciPy, that we may want to give keys to NumFOCUS or otherwise publish them somehow, so that it is possible to report security relevant bugs on a secure channel. I doubt this is very important for NumPy, but maybe something to keep in mind. (Not sure how debian does it, but they must be publishing their keys somehow and they have a rule about devs being signed by two trusted people I believe).

**Comment by rgommers** [comment]
We've had to deal with security bugs exactly zero times for numpy and once for scipy (in scipy.weave) as far as I'm aware. So probably not very urgent, although it can't hurt of course.

**Comment by juliantaylor** [comment]
just send your key to one of the many keyservers, the different usually sync themselves so sending to one will propagate to others.

    gpg --send-keys <yourkeyid>

receive some key from the servers (e.g. mine):

    gpg --recv-keys 32CC4AAC028756FF

signing your mails occasionally is already enough for most purposes, the value of those keys is to verify that the person who did that signed thing is the same person who also did these signed things in the past. Who it really is doesn't matter.
But if that does matter to you only trust keys you have signed in person by seeing documentation (e.g. at conferences)
