### ISSUE TITLE
gfortran: error: unrecognized command line option ‘-ffpe-summary=invalid,zero’

### ISSUE THREAD

**Issue by pv** [numpy/numpy#6495]
numpy.distutils adds a `-ffpe-summary` command line option to gfortran, but it's apparently not supported by all versions of the compiler.

See https://github.com/scipy/scipy/issues/5380

Apparently this was added in b354c005 --- seems to affect also non-windows platforms.

**Comment by charris** [comment]
@carlkl Comment?

**Comment by pv** [comment]
The part where these are added probably should be guarded with `is_win64()`.
`-mlong-double-64` probably should also only be added for mingw (and not e.g. for unix)

**Comment by pv** [comment]
The mingw64 changes seem to have also changed some other flags on non-Windows platforms --- these should probably also be changed back just to be sure.

**Comment by charris** [comment]
@pv I could also revert the PR. I didn't think it quite ready but put it in as a gamble to see what happened. The *.*.1 release is the FU release ;)

**Comment by pv** [comment]
Note that also gh-5614 seems to add some win64 stuff to all platforms.

**Comment by carlkl** [comment]
it seems I forgot to put this flags in ```gnu.py``` with in a ```elif is_win64():``` clause. To bad.
Another problem I encountered is, that is is necessary to discriminate ```mingw-w64|mingwpy``` and the old ```mingw32``` based numpy-vendor compiler as ```longdouble == double``` should not happen there.

**Comment by charris** [comment]
See also #6473. @carlkl  I'm tempted to revert both #5614 (#5587) and #6354.

**Comment by carlkl** [comment]
@charris, maybe it is better to redo a clean mingwpy PR from the scratch. So feel free to revert all these PR's.

**Comment by carlkl** [comment]
@charris, howto do a new PR now? Against https://github.com/numpy/numpy/tree/maintenance/1.10.x ?

**Comment by charris** [comment]
@carlkl All PRs start in master. Numpy 1.11 should be coming out in about 4 months, so that is probably a good release to shoot for in getting OpenBLAS support up and running.

**Comment by charris** [comment]
@pv This should be fixed now.

**Comment by charris** [comment]
OK, closing this. We should be back to the 1.9 state which, AFAICT, was not causing problems.
