### ISSUE TITLE
`python runtests.py --bench` should take a commit argument.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6508]
It currently runs against the tip of master even if a COMMIT arguement is given. Perhaps a bug?

**Comment by jakirkham** [comment]
Is this an issue with NumPy or with airspeed velocity?

**Comment by rgommers** [comment]
not sure, but if it's a numpy issue then it'll be in these few lines:

    if args.bench:
        # Run ASV
        items = extra_argv
        if args.tests:
            items += args.tests
        if args.submodule:
            items += [args.submodule]

        bench_args = []
        for a in items:
            bench_args.extend(['--bench', a])

        if not args.bench_compare:
            cmd = ['asv', 'run', '-n', '-e', '--python=same'] + bench_args

**Comment by argriffing** [comment]
I'm not sure if it's related, but scipy's runtests.py has a modification https://github.com/scipy/scipy/pull/5659 that hasn't yet made its way into numpy.

**Comment by bsipocz** [comment]
This can be closed now, as the current version has both 
```
  --bench               Run benchmark suite instead of test suite
  --bench-compare COMMIT
                        Compare benchmark results of current HEAD to BEFORE.
                        Use an additional --bench-compare=COMMIT to override
                        HEAD with COMMIT. Note that you need to commit your
                        changes first!
```

However the scipy and numpy version of `runtests.py` differ, it may be a prime candidate for a piece of infrastructure that could live in a central numfocus repo rather than being maintained in two places.
