### ISSUE TITLE
DOC: (yet another) typo in arrays.interface.rst

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#6518]
**THIS ISSUE HAS BEEN CREATED AS PART OF THE "BECOME AN OPEN SOURCE CONTRIBUTOR" WORKSHOP. IF YOU ARE NOT A WORKSHOP PARTICIPANT, PLEASE DO NOT SEND A PULL REQUEST TO FIX IT.**

This may be debatable, but on line 74 of `arrays.interface.rst`, see [here](https://github.com/numpy/numpy/blob/master/doc/source/reference/arrays.interface.rst), there is a (potential) typo, `homogenous` --> `homogen_e_ous`.  [This](http://grammarist.com/usage/homogenous-homogeneous/) suggests that the latter should be preferred over the former, even if it is in common use these days.

**Comment by mattip** [comment]
Fixed
