### ISSUE TITLE
DOC: typo in c-api.array.rst

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#6519]
~**THIS ISSUE HAS BEEN CREATED AS PART OF THE "BECOME AN OPEN SOURCE CONTRIBUTOR" WORKSHOP. IF YOU ARE NOT A WORKSHOP PARTICIPANT, PLEASE DO NOT SEND A PULL REQUEST TO FIX IT.**~

On line 237 of `c-api.array.rst`, see [here](https://github.com/numpy/numpy/blob/master/doc/source/reference/c-api.array.rst), fortran should be capitalized, `fortran` --> `_F_ortran`.

**Comment by mattip** [comment]
Fixed
