### ISSUE TITLE
numpy.inner return wrong inaccurate value sometimes... 

### ISSUE THREAD

**Issue by ocloarec** [numpy/numpy#6532]
After updating bumpy from 1.9.2-py27_0 to 1.10.1-py27_0. One of my class method returned a different and thus wrong result.
I localised the error to be from the numpy.inner fonction. What is weird is that when I use the method within another class method declared in a different file, it works! 

When I use the class after
 
if __name__ == '__main__': 

in the same file the class is written to test it it does not work even though the input data is exactly the same in each case. When I declare the class within a Jupyter notebook, the same problem occurs, a wrong output is given by numpy.inner.

**Comment by njsmith** [comment]
Can you provide a short working example demonstrating the problem? See e.g. https://en.m.wikipedia.org/wiki/Minimal_Working_Example or http://sscce.org/

Also, can you give more details on what platform you're using and how you downloaded numpy?

**Comment by ocloarec** [comment]
I work on a Mac Book Pro running Mac OS X 10.11

Attached three files demonstrating the issue. Also attached the file containing the data I used to compare the outputs. Executing the files with numpy 1.9.2 the evaluation of c gives the same correct answer running both files. Using numpy 1.10.1 first_class gives the wrong answer, second_class evaluation is correct! Apparently the preprocessing.scaling is involved because when I remove it, both classes give the wrong answer when I move from numpy 1.9.2 to 1.10.1.

**Comment by ocloarec** [comment]
sorry forgot the data

**Comment by njsmith** [comment]
Github appears to be discarding your attachments. Maybe upload them to gist.github.com?

**Comment by ocloarec** [comment]
Here they are:

https://gist.github.com/addb4bbaffaa63585d65.git <https://gist.github.com/addb4bbaffaa63585d65.git>

I couldn’t upload the data so here is a Dropbox public link

https://dl.dropboxusercontent.com/u/16926370/data.npz <https://dl.dropboxusercontent.com/u/16926370/data.npz>

**Comment by pv** [comment]
Self-contained code:
```
import numpy as np

def doit():
    np.random.seed(1234)
    X = np.random.rand(50, 1000)
    Y = np.random.rand(50, 3)
    X = X - X.mean(axis=0)
    Y = Y - Y.mean(axis=0)

    y = Y[:,0]

    XX = X.dot(X.T)
    tn = XX.dot(y)

    print("Numpy version", np.__version__)
    print(y.shape, tn.shape, y.min(), y.max(), tn.min(), tn.max())

    c = np.inner(y, tn) 
    c2 = np.inner(y.copy(), tn) 
    c3 = (y*tn).sum()

    print(c, c2, c3)

    np.testing.assert_allclose(c, c2)
    np.testing.assert_allclose(c, c3)

if __name__ == '__main__':
    doit()
```

**Comment by ocloarec** [comment]
('Numpy version', '1.10.1')
((50,), (50,), -0.48859534954264638, 0.47975144411505222, -41.144742080228653, 39.598697722152565)
(-28.278582107027624, 302.06900546026594, 302.06900546026594)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-23-2129c54d7dc0> in <module>()
     26 
     27 if __name__ == '__main__':
---> 28     doit()

<ipython-input-23-2129c54d7dc0> in doit()
     22     print(c, c2, c3)
     23 
---> 24     np.testing.assert_allclose(c, c2)
     25     np.testing.assert_allclose(c, c3)
     26 

/Users/olivier/anaconda/envs/testnumpy/lib/python2.7/site-packages/numpy/testing/utils.pyc in assert_allclose(actual, desired, rtol, atol, equal_nan, err_msg, verbose)
   1345     header = 'Not equal to tolerance rtol=%g, atol=%g' % (rtol, atol)
   1346     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
-> 1347                          verbose=verbose, header=header)
   1348 
   1349 def assert_array_almost_equal_nulp(x, y, nulp=1):

/Users/olivier/anaconda/envs/testnumpy/lib/python2.7/site-packages/numpy/testing/utils.pyc in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision)
    706                                 names=('x', 'y'), precision=precision)
    707             if not cond:
--> 708                 raise AssertionError(msg)
    709     except ValueError:
    710         import traceback

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(-28.278582107027624)
 y: array(302.06900546026594)

**Comment by ocloarec** [comment]
('Numpy version', '1.9.2')
((50,), (50,), -0.48859534954264638, 0.47975144411505222, -41.144742080228653, 39.598697722152565)
(302.069005460266, 302.069005460266, 302.06900546026594)

**Comment by ocloarec** [comment]
Forgot to mention that I downloaded Numpy as part of Anaconda 2.3. I updated Numpy using "conda update numpy" last weekend.

**Comment by argriffing** [comment]
I can reproduce this bug on a 1.11 development branch.

**Comment by argriffing** [comment]
Reducing @pv's self-contained code a bit I can reproduce the bug with
```python
def doit_b():
    Y = np.array([
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [9, 10, 11],
        [12, 13, 14]], dtype=float)
    y = Y[:, 0]
    tn = np.array([0, 1, 2, 3, 4], dtype=float)

    print("Numpy version", np.__version__)
    print(y)
    print(tn)

    c = np.inner(y, tn)
    c2 = np.inner(y.copy(), tn)
    c3 = (y*tn).sum()

    print(c, c2, c3)
    print(0*0 + 3*1 + 6*2 + 9*3 + 12*4)

    np.testing.assert_allclose(c, c2)
    np.testing.assert_allclose(c, c3)
```
where np.inner gives 30 instead of 90 :/
If `dtype=float` is changed to `dtype=int` I get the correct result.

**Comment by ocloarec** [comment]
The self contained code does not help to explain why when called from inside another function it works!

**Comment by argriffing** [comment]
This seems pretty bad, so I've boldly labeled this high priority.

**Comment by argriffing** [comment]
> The self contained code does not help to explain why when called from inside another function it works!

@ocloarec I don't what you mean by this.

**Comment by pv** [comment]
git bisect indicates 93feabba42a6c1

**Comment by charris** [comment]
@pv I rather expected that ;)

**Comment by ocloarec** [comment]
@argriffing sorry I wasn't clear. Here the del-contained code of what I meant.
 
    import numpy as np

    def scale(X, scale, axis=0):

        Xbar = X.mean(axis=axis)
        Sx = X.std(axis=axis)
        X = X - Xbar
        X = X / (Sx**scale)
        return X


    def foo1(X, y):
        XX = X.dot(X.T)
        t = XX.dot(y)
        tn = t/np.sqrt(np.sum(t**2))
    
        c = np.inner(y, tn)
    
        return c
    

    def foo2(X, Y):
        Xt = scale(X, 0.)
        Yt = scale(Y, 0.)
        c = foo1(Xt, Yt)
        return c


    if __name__ == '__main__':
        np.random.seed(1234)
        X = np.random.rand(50, 1000)
        Y = np.random.rand(50, 3)
        Xc = scale(Xt, 0.)
        Yc = scale(Yt, 0.)
        # With scaling
        print("Direct call:")
        print "c = " + str(foo1(Xc, Yc[:,0]))
        print("Called from foo2:") 
        print "c = " + str(foo2(X, Y[:,0]))

**Comment by argriffing** [comment]
@ocloarec I think the self-contained example does explain this, as it shows that `np.inner` has a bug that depends on the underlying layout of its input arrays.

In your 'direct vs. indirect' example, the `y` array in the direct call is like
```
y shape: (50,)
y strides: (24,)
y flags:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```
whereas in the indirect call the `y` array is like
```
y shape: (50,)
y strides: (8,)
y flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```
I agree that it's a bug.

**Comment by argriffing** [comment]
Here's a further simplified example.

```python
from __future__ import print_function
import numpy as np
from numpy.testing import assert_equal

A = np.array([
    [1, 2],
    [3, 4]], dtype=float)
B = np.array([
    [1, 3],
    [2, 4]], dtype=float)
c = np.array([1, 1], dtype=float)

assert_equal(A.T, B)

print('np.inner(A.T, c):', np.inner(A.T, c))
print('np.inner(B, c):', np.inner(B, c))
```

```
np.inner(A.T, c): [ 3.  7.]
np.inner(B, c): [ 4.  6.]
```

**Comment by argriffing** [comment]
@ocloarec Recent numpy versions try to use BLAS to accelerate inner products of floating point arrays, but apparently the implementation has issues with array contiguity. Presumably someone who knows more about numpy internals will fix this properly, but I've made this interim PR https://github.com/numpy/numpy/pull/6546 that would just revert the BLAS support.
