### ISSUE TITLE
f2py: Intent(out) broken in recent versions of numpy

### ISSUE THREAD

**Issue by rewquey** [numpy/numpy#6563]
As of recently, the intent(out) is no longer taken over into the signature file. This concerns both the information from a Fortran90 variable declaration and the f2py hint with the syntax 
```!f2py intent(out) var```.

The fib3.f example from the [f2py documentation](http://docs.scipy.org/doc/numpy/f2py/getting-started.html) is affected as well and can serve as a minimal example.

The reason seems to be that the function isintent_out() is not imported from auxfuncs.py into crackfortran.py . Intent(out) does hence pass not through the true_intent_list filter.

**Comment by charris** [comment]
fib3.f in numpy 1.9
```
!    -*- f90 -*-
! Note: the context of this file is case sensitive.

python module fib3 ! in 
    interface  ! in :fib3
        subroutine fib(a,n) ! in :fib3:fib3.f
            real*8 dimension(n),intent(out),depend(n) :: a
            integer intent(in) :: n
        end subroutine fib
    end interface 
end python module fib3
```
vs numpy 1.10.1
```
!    -*- f90 -*-
! Note: the context of this file is case sensitive.

python module fib3 ! in 
    interface  ! in :fib3
        subroutine fib(a,n) ! in :fib3:fib3.f
            real*8 dimension(n),depend(n) :: a
            integer intent(in) :: n
        end subroutine fib
    end interface 
end python module fib3

! This file was auto-generated with f2py (version:2).
! See http://cens.ioc.ee/projects/f2py2e/
```

**Comment by charris** [comment]
Bisect gives b80d1f97 as the first bad commit. The problem is that `crackfortran.py` uses `eval` all over the place and it is executed in the current environment, hence pyflakes and pylint are unable to detect everything that needs to be imported from a static analysis of the code. Ugh.

**Comment by charris** [comment]
The proximate cause seems to be
```
def true_intent_list(var):
    lst = var['intent']
    ret = []
    for intent in lst:
        try:
            c = eval('isintent_%s(var)' % intent)
        except NameError:
            c = 0
        if c:
            ret.append(intent)
    return ret
```
Which not only depends on the default environment, but hides the `NameError`. Hmm, what to do. Go back to a `*` import or just import everything `isintent_*`.

**Comment by charris** [comment]
The files `capi_maps.py`, `f90mod_rule.py`, and `crackfortran.py` all contained both `from .auxfuncs import *` and called `eval` without explicit environments in some spots. Pending a big refactor of `f2py`, it is probably safest to revert the PEP8 fixups to those files and use `import *` as before.
