### ISSUE TITLE
test_load_refcount from numpy.lib.tests.test_io

### ISSUE THREAD

**Issue by rherault-insa** [numpy/numpy#6571]
The test __test_load_refcount__ from __numpy.lib.tests.test_io__ seems to randomly fail even on the master branch.

```python
#!/usr/bin/env python

from __future__ import print_function

from numpy.lib.tests.test_io import test_load_refcount

n=100
print("Test",end='')
for i in range(n):
    print("\rTest %d/%d"%(i+1,n),end='')
    test_load_refcount()
print("")
```

**Comment by charris** [comment]
I've noticed that also. Checking refcounts can be tricky, so my initial thoughts have been that there is a test problem, but I haven't looked closely at it.

**Comment by njsmith** [comment]
Odd, I ran it 500 times and it passed every one...

**Comment by rherault-insa** [comment]
Ubuntu 15.04, Python 3.4.3, master branch it fails nearly each time. And I see Travis check regularly failing on it.

**Comment by njsmith** [comment]
Ah, I was checking under 2.7. Under 3.4 it seems to fail reliably the first time I run it in an interactive session (and then works reliably after that).

**Comment by njsmith** [comment]
@rherault-insa @charris: since you seem to be able to reproduce this reliably, can you check whether #6576 helps?
