### ISSUE TITLE
DOC: Is the where doc correct?

### ISSUE THREAD

**Issue by MaximilianR** [numpy/numpy#6589]
Here: http://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

```
x, y : array_like, optional
Values from which to choose. x and y need to have the same shape as condition.
```

Do they actually need to have the same shape as condition? Also from the docs:

``` python
>>> x = np.arange(9.).reshape(3, 3)
>>> np.where( x > 5 )
(array([2, 2, 2]), array([0, 1, 2]))
>>> x[np.where( x > 3.0 )]               # Note: result is 1D.
array([ 4.,  5.,  6.,  7.,  8.])
>>> np.where(x < 5, x, -1)               # Note: broadcasting.
array([[ 0.,  1.,  2.],
       [ 3.,  4., -1.],
       [-1., -1., -1.]])
```

**Comment by maximilianr** [comment]
Potentially `same shape` means a shape that's at least broadcast-able to that shape? 
Apologies if that's the standard meaning...

**Comment by shoyer** [comment]
Indeed, `where` seems to do broadcasting. I agree this should be updated.

**Comment by eric-wieser** [comment]
Duplicate of #7914
