### ISSUE TITLE
inconsistencies in array construction from a list of ndarrays

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#6591]
When looking at examples for https://github.com/numpy/numpy/issues/6584#issuecomment-152607473 I found the following weird or inconsistent behavior:

``` python
>>> a = np.zeros((2, 2))
>>> b = np.zeros((2, 3))
>>> c = np.zeros((3, 2))
>>> np.array([a, a])
array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]])
>>> np.array([a, b])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: could not broadcast input array from shape (2,2) into shape (2)
>>> np.array([a, c])
array([array([[ 0.,  0.],
       [ 0.,  0.]]),
       array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])], dtype=object)
```

How much of this is intended, and if it is not intended then which open github issues are most relevant?

**Comment by njsmith** [comment]
"Intended" may be a bit strong of a word...
.
I think at this point we should be (1) moving ahead with deprecating
implicit object dtype creation, (2) looking into an overhaul of np.array to
rationalize everything (with appropriate deprecations etc of course). These
are actually mostly orthogonal, because IMHO np.array([[1, 2], [1, 2, 3]],
dtype=object) should be an error even with the explicit dtype=object. And
I'm not even sure what broadcasting has to do with np.array.

**Comment by charlie0389** [comment]
I'm not 100% sure, but I think this is evidence of the same bug, that may help finding the root cause:

```
import numpy as np
print(np.__version__)
 
a = np.array([np.array([[-0.04,    0.04]], dtype=np.float64),
              np.array([[-1.57], [ 1.36]], dtype=np.float64)], dtype=object)
 
print(a.dtype)     # expected
print(a[0].dtype)  # expected
print(a[1].dtype)  # expected
 
b0 = np.array([np.array([-np.pi/2, 0.45], dtype=np.float64)], dtype=np.float64)
b = np.array([b0], dtype=object)
# b = np.array([np.array(b0, dtype=np.float64)], dtype=object)  # < Same unexpected result later ...
 
print(b.dtype)    # expected
print(b[0].dtype) # This I don't expect - shouldn't this be of float64 type?
```

Which produces the output:

> 1.23.2
> object
> float64
> float64
> object
> object

**Comment by seberg** [comment]
Fixed (presumably by my array-coercion rewrite in NumPy 1.19).

The last comment is expected as well, since the array is unpacked.  To not get unpacking behavior, you have to fill a pre-created `np.empty` array (with the right shape), no such mechanism exists currently.
