### ISSUE TITLE
BUG: `flatten` method does not validate its argument.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#6598]
According to the docstring of the `flatten` method, the argument should be one of `'C'`, `'F'` or `'A'`.  I would expect a `ValueError` to be raised if the argument is not one of those values.  However, it appears to ignore invalid arguments.

For example,

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.11.0.dev0+78d9628'

In [3]: x = np.zeros((3, 5))

In [4]: x.flatten(np.pi)  # Give flatten() a nonsense argument, and it doesn't complain.
Out[4]: 
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.])
```

I noticed this while editing the "NumPy for Matlab Users" guide, where `y = x.flatten(1)` was suggested as the NumPy version of the Matlab code `y = x(:)`.  (The guide has been fixed.)

**Comment by gfyoung** [comment]
From what I can tell, I believe the bug traces to code in the ```PyArray_OrderConverter``` method in this file <a href="https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/conversion_utils.c">here</a>.  I'll have a PR up for that soon!

**Comment by WarrenWeckesser** [comment]
@gfyoung Thanks for fixing this.

**Comment by gfyoung** [comment]
@WarrenWeckesser : Sure thing!  Your issue actually had ramifications for several other functions whose underlying functionality was tied to that ```order``` parameter.  So it was good that you caught this.
