### ISSUE TITLE
ma.dot no longer always returns a masked array in 1.10

### ISSUE THREAD

**Issue by ajdawson** [numpy/numpy#6611]
The function `numpy.ma.dot` in versions <1.10 always returned a masked array, but in 1.10 it does so only if one or both of the inputs are masked array. I couldn't find this documented anywhere in the release notes, so perhaps it is a regression? This broke some code "in the wild" that relied on `ma.dot` returning a masked array (ajdawson/eofs#34).

A simple code example, which returns a `numpy.ma.core.MaskedArray` on numpy <1.10 and a `numpy.ndarray` on numpy 1.10:

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
ma.dot(a, b)
```

It looks like the major change here was probably #5709. Can someone confirm if this is intentional new behaviour or if this is a bug, @charris @abalkin?

**Comment by charris** [comment]
The culprit is #5709. @abalkin Thoughts? Perhaps just converting both inputs to masked arrays will do.

**Comment by abalkin** [comment]
I agree with @charris  - the simplest fix is to add

```
a = ma.asarray(a)
```

to `ma.extras.dot` definition.  Note that conversing the first input should be enough.
