### ISSUE TITLE
 NPY_FORTRANORDER in make_fortran() function, numpy.i

### ISSUE THREAD

**Issue by colormotor** [numpy/numpy#6618]
Hi,
 
in the process of converting numpy arrays to fortran-contiguous ordering in a swig wrapper (python<->armadillo), I noticed that the `make_fortran` function in numpy does not seem to swap the memory layout of arrays.
In my use case I fixed the issue by substituting  `NPY_FORTRANORDER` with `NPY_ARRAY_F_CONTIGUOUS` in the `PyArray_FromArray` call.

I'm not very familiar with the internal workings of numpy, but I thought I would  share this in case it does represent an issue.

Best,
Daniel

**Comment by charris** [comment]
Indeed, `PyArray_FromArray` has a `flags` (int) argument, not an `NPY_ORDER` argument.

**Comment by charris** [comment]
Thanks for the report.
