### ISSUE TITLE
Window 7 64 bit  - large int to float conversion lost precision on iterator passed as float 

### ISSUE THREAD

**Issue by HBDunn** [numpy/numpy#6619]
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

In [1]: import numpy as np
   ...: np.version.full_version
   ...: 
Out[1]: '1.10.1'

In [2]: int32arr = np.array([39831850,39831850])
   ...: flt32arr = np.zeros((2), dtype = 'float32')
   ...: flt32arr[:] = int32arr
   ...: 

In [3]: int32arr
Out[3]: array([39831850, 39831850])

In [4]: flt32arr
Out[4]: array([ 39831848.,  39831848.], dtype=float32)

39831850 np.int goes to 39831848 as np.float32

**Comment by pv** [comment]
It's the float32 value closest to 39831850.
