### ISSUE TITLE
Interest in percentile function that matches behavior of Matlab / IDL?

### ISSUE THREAD

**Issue by cpaulik** [numpy/numpy#6620]
Matlab uses linear interpolation based on the rank of the data see [Algorithm part of the Matlab documentation](http://de.mathworks.com/help/stats/prctile.html). This algorithm is also used in some IDL libraries and can not be replicated using any of the interpolation schemes in the `numpy.percentile` function, see example at the bottom of this post.

It can easily be implemented as:

``` python
matlab_percentile(in_data, percentiles):
    """
    Calculate percentiles in the way IDL and Matlab do it.

    By using interpolation between the lowest an highest rank and the
    minimum and maximum outside.

    Parameters
    ----------
    in_data: numpy.ndarray
        input data
    percentiles: numpy.ndarray
        percentiles at which to calculate the values

    Returns
    -------
    perc: numpy.ndarray
        values of the percentiles
    """

    data = np.sort(in_data)
    p_rank = 100.0 * (np.arange(data.size) + 0.5) / data.size
    perc = np.interp(percentiles, p_rank, data, left=data[0], right=data[-1])
    return perc
```

Example of differences between `numpy` and `matlab`:

``` python
In [2]: import numpy as np

In [3]: a = np.array([2,4,6,8,10])

In [4]: matlab_percentile(a, [25, 50, 75])
Out[4]: array([ 3.5,  6. ,  8.5])

In [5]: np.percentile(a, [25, 50, 75])
Out[5]: array([ 4.,  6.,  8.])

In [6]: np.percentile(a, [25, 50, 75], interpolation='linear')
Out[6]: array([ 4.,  6.,  8.])

In [7]: np.percentile(a, [25, 50, 75], interpolation='lower')
Out[7]: array([4, 6, 8])

In [8]: np.percentile(a, [25, 50, 75], interpolation='higher')
Out[8]: array([4, 6, 8])

In [9]: np.percentile(a, [25, 50, 75], interpolation='midpoint')
Out[9]: array([ 5.,  7.,  9.])

In [10]: np.percentile(a, [25, 50, 75], interpolation='nearest')
Out[10]: array([4, 6, 8])
```

**Comment by rgommers** [comment]
Is this still relevant with the changes to `quantile`? @chunweiyuan this is probably still fresh in your memory, do you have an opinion on this?

**Comment by eric-wieser** [comment]
I think this is closely tied to #10736

**Comment by chunweiyuan** [comment]
I think it's not a question of interpolation.  The Matlab and Numpy seem to use different sampling methods to begin with.  That means the same sorted list of values would represent different quantiles in Matlab and Numpy.

Looking at the Matlab doc link above, for a sorted n-element vector X, where the elements are indexed `i \in [1, n]`, the values are taken as the `\frac{i-0.5}{n}`th quantiles (or multiply by 100 if you want percentiles).  This is Method 5 in #10736 (or Type 5 in [R](https://www.rdocumentation.org/packages/stats/versions/3.5.0/topics/quantile))

The same elements `i` become the `\frac{i-1}{n-1}`th quantiles in Numpy.  This is Method 7 in #10736.

**Comment by dsm-72** [comment]
> Matlab uses linear interpolation based on the rank of the data see [Algorithm part of the Matlab documentation](http://de.mathworks.com/help/stats/prctile.html). This algorithm is also used in some IDL libraries and can not be replicated using any of the interpolation schemes in the `numpy.percentile` function, see example at the bottom of this post.
> 
> It can easily be implemented as:
> 
> ```python
> matlab_percentile(in_data, percentiles):
>     """
>     Calculate percentiles in the way IDL and Matlab do it.
> 
>     By using interpolation between the lowest an highest rank and the
>     minimum and maximum outside.
> 
>     Parameters
>     ----------
>     in_data: numpy.ndarray
>         input data
>     percentiles: numpy.ndarray
>         percentiles at which to calculate the values
> 
>     Returns
>     -------
>     perc: numpy.ndarray
>         values of the percentiles
>     """
> 
>     data = np.sort(in_data)
>     p_rank = 100.0 * (np.arange(data.size) + 0.5) / data.size
>     perc = np.interp(percentiles, p_rank, data, left=data[0], right=data[-1])
>     return perc
> ```
> 
> Example of differences between `numpy` and `matlab`:
> 
> ```python
> In [2]: import numpy as np
> 
> In [3]: a = np.array([2,4,6,8,10])
> 
> In [4]: matlab_percentile(a, [25, 50, 75])
> Out[4]: array([ 3.5,  6. ,  8.5])
> 
> In [5]: np.percentile(a, [25, 50, 75])
> Out[5]: array([ 4.,  6.,  8.])
> 
> In [6]: np.percentile(a, [25, 50, 75], interpolation='linear')
> Out[6]: array([ 4.,  6.,  8.])
> 
> In [7]: np.percentile(a, [25, 50, 75], interpolation='lower')
> Out[7]: array([4, 6, 8])
> 
> In [8]: np.percentile(a, [25, 50, 75], interpolation='higher')
> Out[8]: array([4, 6, 8])
> 
> In [9]: np.percentile(a, [25, 50, 75], interpolation='midpoint')
> Out[9]: array([ 5.,  7.,  9.])
> 
> In [10]: np.percentile(a, [25, 50, 75], interpolation='nearest')
> Out[10]: array([4, 6, 8])
> ```

Just saved me minutes of banging my head.

**Comment by rossbar** [comment]
FWIW the `interpolation` methods listed in the above example are out-of-date as of v1.22. The kwarg is called `method` now, and there are [9 methods](https://numpy.org/devdocs/reference/generated/numpy.percentile.html) implemented. None of them are exactly the "matlab" version, but I think both `median_unbiased` and `normal_unbiased` are pretty close.

**Comment by seberg** [comment]
I suspect, the matlab version is just `method="hazen"` (method 5 from H&F, which is the same as R).  So I am going to close the issue.
