### ISSUE TITLE
f2py does not correctly parse selected_real_kind(precision(1.0d0))

### ISSUE THREAD

**Issue by srtlg** [numpy/numpy#6624]
Consider the dummy declarations below which are valid Fortran.  Both bar1 and bar2 are of double precision, however the C-code generated by f2py assumes that bar2 is typed NPY_FLOAT which results to writes into foreign memory from the compiled Fortran module.  If you think it is a too seldomly employed form, please consider to make f2py refuse automatically guessing bar2's type and require editing the .pyf file. 

This is up to version 1.10.1

``` fortran
subroutine foo(bar1,bar2,n)
integer, parameter :: dp1 = selected_real_kind(15)
integer, parameter :: dp2 = selected_real_kind(precision(1.0d0))
integer, intent(in) :: n
real(dp1), dimension(n), intent(out) :: bar1
real(dp2), dimension(n), intent(out) :: bar2
integer :: i
do i = 1, n
  bar1(i) = 1
  bar2(i) = 1
  write(*,*) i
end do
end subroutine
```

**Comment by charris** [comment]
@pearu Thoughts?
