### ISSUE TITLE
numpy.percentile does not accept sequence of floats

### ISSUE THREAD

**Issue by max0x7ba** [numpy/numpy#6625]
In numpy 1.8.2 numpy.percentile does not accept sequence of floats as it should, according to the documentation. 

This is because it compares `q` with scalars, whereas `q` can be either a scalar or a sequence:

```
def percentile(a, q, axis=None, out=None, overwrite_input=False):
    # ...
    if q == 0:
        return a.min(axis=axis, out=out)
    elif q == 100:
        return a.max(axis=axis, out=out)
```

**Comment by njsmith** [comment]
I'm pretty sure this is fixed in more recent numpy versions (but on my
phone so can't trivially check myself). Have you tried 1.10? 1.8 is pretty
old, and certainly won't get any fix even if one is needed.

**Comment by max0x7ba** [comment]
It looks like it is fixed in master, since I can see the unit tests do pass sequences in it and the code of `numpy.percentile` changed.
