### ISSUE TITLE
No new ver. of NumPy bin for Python32 to download 

### ISSUE THREAD

**Issue by JulianVolodia** [numpy/numpy#6635]
There is no NumPy for Python 3.2.

Last ver. was about 1.8.1 which I use now.

**Comment by shoyer** [comment]
Why are you still using Python 3.2? That's pretty old at this point, so there really isn't a lot of demand for supporting that version.

That said, I think Python 3.2 is still officially supported. Where are you attempting to download numpy from?

**Comment by njsmith** [comment]
Between 1.8 and now we stopped providing prebuilt wheels for 3.2 on osx on
pypi. You can still build it yourself, but yeah, 3.2 is extremely out of
date and I'd recommend upgrading if possible. (If you have a really
compelling reason why you can't upgrade and need the precompiled binaries
then you can try explaining here and maybe it will convince us to keep
supporting it for a bit longer, but there is a limit to how long we can
keep supporting obsolete versions...)

**Comment by JulianVolodia** [comment]
Just purism and my fault.
1) I haven't seen obvious info in README that support for python3.2 had been abandoned. So, need to change info that not 3.2 - 3.5 is supported, but 3.3 - 3.5.

2) I start to use actually very old version of lib - PyGame - which is compatible with python3.2

Sorry for disturbing.

**Comment by njsmith** [comment]
Not sure what's your fault, it's a reasonable confusion and we'd love to
provide binaries for every system forever if we could, it's just that we
have limited resources. We do still support python 3.2 (in the sense that
it works and if it doesn't we'll fix it), but we don't provide precompiled
binaries so you have to compile it yourself. (Currently we don't provide
precompiled binaries at all for most operating systems so this merely
leaves you in the the same position as e.g. all Linux users.)

**Comment by JulianVolodia** [comment]
OK, maybe you misunderstand me but - I do not complain.

I was wrong, now I get that there are no preprepared bin of new NumPy for older Python, but it works if I decide to compile.

Thanks.
