### ISSUE TITLE
uint32(hash(2**32)) throws OverflowError in win_amd64 builds, but nowhere else?

### ISSUE THREAD

**Issue by gojomo** [numpy/numpy#6637]
Based on errors I've seen from users, I believe the following code will reliably trigger an OverflowError ("Python int too large to convert to C long") for people using win_amd64 Numpy builds (such as the unofficial ones at http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy): 

```
numpy.uint32(hash(2**32))
```

But, I believe this line will work without error on most other 32-bit or 64-bit pythons. (Anywhere the `hash()` value is more than 32 bits, `uint32()` will still work to truncate – _except_ for these win_amd64 builds.) 

This discrepancy seems non-ideal, and perhaps against the intended type-casting functionality of `uint32()`.  

I know this may not be a core Numpy concern, but perhaps a win_amd64 build expert who can resolve the issue is here, or maybe adding a test (that this code does not throw an error) could prompt downstream builders to see and resolve the issue.

**Comment by njsmith** [comment]
Could likely be fixed by replacing some PyInt_AsLong call with a
PyInt_AsLongLong call. (In fact it might already work as a workaround to do
np.uint32(np.uint64(hash(...))).)

On Thu, Nov 5, 2015 at 11:11 PM, Gordon Mohr <notifications@github.com>
wrote:

> Based on errors I've seen from users, I believe the following code will
> reliably trigger an OverflowError ("Python int too large to convert to C
> long") for people using win_amd64 Numpy builds (such as the unofficial ones
> at http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy):
>
> numpy.uint32(hash(2**32))
>
> But, I believe this line will work without error on most other 32-bit or
> 64-bit pythons. (Anywhere the hash() value is more than 32 bits, uint32()
> will still work to truncate – *except* for these win_amd64 builds.)
>
> This discrepancy seems non-ideal, and perhaps against the intended
> type-casting functionality of uint32().
>
> I know this may not be a core Numpy concern, but perhaps a win_amd64 build
> expert who can resolve the issue is here, or maybe adding a test (that this
> code does not throw an error) could prompt downstream builders to see and
> resolve the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6637>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by seberg** [comment]
There is a deprecation in progress to make it a consistent error (and another issue with a table open IIRC).  If you want the silent overflow, I think you should use the workaround on all platforms (or even `%` to be explicit).
