### ISSUE TITLE
Improve random variate generation of noncentral F-distribution

### ISSUE THREAD

**Issue by xiaoweiz** [numpy/numpy#6638]
The noncentral F-distribution has three parameters: 
- `dfnum`, degrees of freedom in numerator
- `dfden`, degrees of freedom in denominator 
- `nonc`, noncentrality 

According to [http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.noncentral_f.html](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.noncentral_f.html), 
the current implementation unnecessarily requires both `dfnum` and `dfden` be greater than 1, while they are allowed to be any positive value in theory. 

This restriction stems from the fact that the implementation calls `random.noncentral_chisquare`, which unnecessarily required that its `dof` argument must be greater than 1 and has been fixed in `numpy 1.10`; see #5766. 

Since the implementation of `random.noncentral_f` is straightforward, something like 

``` python
t = np.random.noncentral_chisquare(dfnum, nonc) * dfden 
t / (np.random.chisquare(dfden) * dfnum)
```

according to [https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/distributions.c#L256-L260 ](https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/distributions.c#L256-L260), this should be an easy fix.

**Comment by xiaoweiz** [comment]
I have just checked the implementation at
[https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L2102-L2105](https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L2102-L2105), it seems that the code actually permits `dfden` to be any positive value, while restricting `dfnum` to be greater than 1. The docstring there still states both must be greater than 1 though.

**Comment by ahaldane** [comment]
Sounds reasonable although I'm not really familiar with that code.

If you are interested, I encourage you to submit a PR on github, this seems like a simple fix that isn't too hard.  If you need any guidance or summary of what you'd need to do, feel free to ask. (If not someone will probably get to it eventually :) )

**Comment by xiaoweiz** [comment]
As of version 1.13.3, the bug is still there. (I've tried the installation through both Conda and pip.)
<img width="725" alt="screen shot 2017-10-08 at 3 31 19 pm" src="https://user-images.githubusercontent.com/4540215/31314852-e0b8bf9c-ac3d-11e7-94eb-87a0c5b23a55.png">
