### ISSUE TITLE
__builtin_isnan, __builtin_isinf, and __bultin_isinfinite broken on OS X with Intel compiler version 16.0.0

### ISSUE THREAD

**Issue by andersjel** [numpy/numpy#6639]
Numpy uses __builtin_isnan, __builtin_isinf, and __bultin_isinfinite when available but these are not implemented correctly by version 16.0.0 of the Intel compiler installed on OS X 10.10. This means that `numpy.isinf(float('inf'))` returns `False`, for instance.

Here is a minimal test-case against the Intel compiler:

``` c++
#include <iostream>
#include <cmath>

int main(int argc, char const * argv[])
{
    std::cout
        << std::isnan(0.0/0.0)    << " " << __builtin_isnan(0.0/0.0)    << "\n"
        << std::isinf(1.0/0.0)    << " " << __builtin_isinf(1.0/0.0)    << "\n"
        << std::isfinite(1.0/0.0) << " " << __builtin_isfinite(1.0/0.0) << "\n";
}
```

which when compiled with `icpc -fp-model strict test.cpp -o test` prints

```
1 0
1 0
0 1
```

Here are some more details of my installation

```
$ icpc -v
icpc version 16.0.0 (gcc version 4.9.0 compatibility)
$ uname -a
Darwin QuantumWises-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```

**Comment by andersjel** [comment]
I reported this to Intel. The issue reference is: 6000139151

**Comment by ChristopherHogan** [comment]
As a temporary workaround, the following patch allows all tests to pass when using the Intel compiler on Mac OS X.
```
diff --git a/numpy/core/include/numpy/npy_math.h b/numpy/core/include/numpy/npy_math.h
index d1d50e8..0eade6e 100644
--- a/numpy/core/include/numpy/npy_math.h
+++ b/numpy/core/include/numpy/npy_math.h
@@ -158,7 +158,7 @@ double npy_spacing(double x);

 /* use builtins to avoid function calls in tight loops
  * only available if npy_config.h is available (= numpys own build) */
-#if HAVE___BUILTIN_ISNAN
+#if HAVE___BUILTIN_ISNAN && !(defined(__INTEL_COMPILER) && defined(__APPLE__))
     #define npy_isnan(x) __builtin_isnan(x)
 #else
     #ifndef NPY_HAVE_DECL_ISNAN
@@ -174,7 +174,7 @@ double npy_spacing(double x);


 /* only available if npy_config.h is available (= numpys own build) */
-#if HAVE___BUILTIN_ISFINITE
+#if HAVE___BUILTIN_ISFINITE && !(defined(__INTEL_COMPILER) && defined(__APPLE__))
     #define npy_isfinite(x) __builtin_isfinite(x)
 #else
     #ifndef NPY_HAVE_DECL_ISFINITE
@@ -189,7 +189,7 @@ double npy_spacing(double x);
 #endif

 /* only available if npy_config.h is available (= numpys own build) */
-#if HAVE___BUILTIN_ISINF
+#if HAVE___BUILTIN_ISINF && !(defined(__INTEL_COMPILER) && defined(__APPLE__))
     #define npy_isinf(x) __builtin_isinf(x)
 #else
     #ifndef NPY_HAVE_DECL_ISINF
```

**Comment by LogicalKnight** [comment]
Thought I'd mention that with version 16.0.2 of Intel's compiler on OS X, the about C++ test code now yields (when compiled with `-fp-model strict`):
    
    1 1
    1 0
    0 0

`__builtin_isnan` and `__builtin_isfinite` seem to be fixed, but `__builtin_isinf` is still broken.

**Comment by jakirkham** [comment]
There is an [Intel discussion thread]( https://software.intel.com/en-us/forums/intel-c-compiler/topic/600608 ) about that. Would be interesting to know if that got fixed.

**Comment by sethrj** [comment]
Wow, you'd hope that if the compiler is going to implement a nonstandard function, they'd at least implement it correctly? ...

**Comment by mattip** [comment]
Any news here? I think we should close this if there are no updates in 3 more months.

**Comment by jakirkham** [comment]
It sounds like a compiler bug and not a NumPy bug. So seems safe to close FWIW.
