### ISSUE TITLE
ma.asarray does not default to C order as stated.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6646]
In fact, the `order` keyword is ignored.
```
In [7]: a = eye(3).T

In [8]: a.flags
Out[8]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [9]: ma.asarray(a).flags
Out[9]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [10]: ma.asarray(a, order='C').flags
Out[10]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

**Comment by gfyoung** [comment]
Because ```copy``` is ```False``` in the ```__new__``` method for the ```MaskedArray``` class when it is called from ```asarray```, the order for the ```_data``` object is variable (either ```C``` or ```Fortran```).  Thus, to ensure ordering, I think you can just add an ```order``` parameter to that method.  I can put up a PR for that quickly.
