### ISSUE TITLE
f2py intent(in,out) appears broken in NumPy 1.10.1

### ISSUE THREAD

**Issue by DeadParrot** [numpy/numpy#6654]
Returning scalars using `intent(in,out)` that was working up throught NumPy 1.9.x now returns `None` with NumPy 1.10.1.

Also, I had to switch to `intent(in out)` (no comma) to get the passed value modified but that still didn't get it to return anything.

Here is a stripped down example:
```fortran
      SUBROUTINE SUB_WRAPPER( T, X, C, S, message_callback )
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN) :: X
      DOUBLE PRECISION, INTENT(INOUT) :: T, C, S
!f2py intent(in,out) :: T
!f2py intent(in,out) :: C
!f2py intent(in,out) :: S
      EXTERNAL :: message_callback
!f2py character*(*) msg
!f2py integer level
!f2py call message_callback(msg,level)
      CALL message_caller( message_callback )
      CALL SUB( T, X, C, S )
      END SUBROUTINE SUB_WRAPPER
```

The problem was observed running NumPy 1.10.1 on 64-bit Windows 10 using 64-bit Python 2.7.10 and the NumPy package from http://www.lfd.uci.edu/~gohlke/pythonlibs. My Linux systems don't have 1.10 yet.

**Comment by charris** [comment]
There is a fix for `intent` in current `maintenance/1.10.x`, could you test that? Also, could you supply stripped down fortran code, not the wrapper.

**Comment by charris** [comment]
See #6563 for possibly related.

**Comment by DeadParrot** [comment]
Looks like you have this under control. Sorry for missing the related issue in my search. I will try the maintenance branch if/when time allows but don't wait for me to release 1.10.2.

**Comment by charris** [comment]
The only other change affecting `intent` was in 1.9.1, where `intent(in out)` was made legal as that is a valid way to write `intent(inout)` if fortran is ignoring spaces. I don't believe that `intent(in, out)` is valid fortran, but I could be wrong. I'll leave this open until you can test 1.10.2.

**Comment by charris** [comment]
Maybe you can test `1.10.2rc`, there should be some windows version available and that will be coming out soon.

**Comment by DeadParrot** [comment]
If I can get a Windows binary of the RC I'll test it and report back.

I noticed the `intent(in out)` support F2PY added in 1.9, which is why I tried it. F2PY has `intent(in,out)` as well as `intent(inout)` because it has different semantics.

**Comment by charris** [comment]
There are some 32 bit windows binaries for `1.10.2rc1` on sourceforge: http://sourceforge.net/projects/numpy/files/NumPy/1.10.2rc1/. Don't know if that helps.

**Comment by DeadParrot** [comment]
Thanks but I am running 64-bit Python so I guess I'll have to wait for the Gohlke build of it (he posts RCs sometimes). Interesting that he removed the 1.10.1 releases -- must have been enough serious issues reported.

**Comment by charris** [comment]
Yep, there were some serious issues. It was a gamble leaving out in the wild, it may have been better to make a intermediate release earlier.

**Comment by scienceopen** [comment]
Hello, I have placed a minimum working example of this bug at
https://github.com/scienceopen/python-matlab-examples/tree/master/f2py

I notice that fortran intent(in), intent(out) are honored without having to add 
cf2py intent(in) 

But intent(inout) in the fortran code is not honored, it will just return None.
You have to add 
cf2py intent(in,out) 
only for it to work. cf2py intent(inout) does not work.

It seems that f2py should honor the Fortran code without adding cf2py.

This is broken in Numpy 1.10.1 and Numpy 1.9.2

**Comment by pv** [comment]
`intent(inout)` and `intent(in,out)` are different in f2py:  https://docs.scipy.org/doc/numpy/f2py/signature-file.html#attributes

**Comment by DeadParrot** [comment]
To clarify, the bug reported here is not about `intent(inout)` (or the need to use `cf2py` comments) but about a regression where the `cf2py intent(in,out)` usage that used to work, returning the variable, stopped returning it in 1.10.1.

**Comment by charris** [comment]
@scienceopen Also fails for 1.8, so @pv seems correct that your example has never worked.

**Comment by charris** [comment]
@DeadParrot Could you put together a minimal example of the failure and post it?

**Comment by DeadParrot** [comment]
@charris I spent a good bit of time on this and the results are surprising: very small test cases DO return the in,out values but in the context of my real application they aren't returned. I could start cutting down my real application until it starts working to see what matters but that would be a lot of work. If this is essential to resolving the issue I can give it a go -- let me know.

**Comment by charris** [comment]
@DeadParrot I'd really like to track this down. However, if it works for small files I might remove the 1.10.2 milestone as this is one of the blockers for release.

**Comment by DeadParrot** [comment]
@charris OK, I'll give it another go today and report back.

**Comment by DeadParrot** [comment]
OK, I got to the bottom of it. If I use fpy to generate the library in one operation it works but with separate steps the pyf generator is giving the wrong intent. Here is an example we'll call sub.f90:
```fortran
SUBROUTINE sub( x )
REAL(8), INTENT(INOUT) :: x
!f2py intent(in,out) :: x
x = x * 3
END SUBROUTINE sub
```
Running `f2py sub.f90 -h sub.pyf` with 1.10.1 gives:
```fortran
!    -*- f90 -*-
! Note: the context of this file is case sensitive.

subroutine sub(x) ! in sub.f90
    real(kind=8) intent(in) :: x
end subroutine sub

! This file was auto-generated with f2py (version:2).
! See http://cens.ioc.ee/projects/f2py2e/
```
Notice the `intent(in)` that should be `intent(in,out)` (and is on 1.9.x). I hope that helps and that you can fix this for 1.10.2.

**Comment by charris** [comment]
Great, thanks for tracking that down and giving an example. The good (bad?) news is that it has been fixed.
```
charris@fc [~]$ f2py sub.f90 -h sub.pyf && cat sub.pyf
Reading fortran codes...
	Reading file 'sub.f90' (format:fix)
Post-processing...
	Block: sub
Post-processing (stage 2)...
Saving signatures to file "./sub.pyf"
!    -*- f90 -*-
! Note: the context of this file is case sensitive.

subroutine sub(x) ! in sub.f90
    real(kind=8) intent(in,out) :: x
end subroutine sub

! This file was auto-generated with f2py (version:2).
! See http://cens.ioc.ee/projects/f2py2e/
```
So closing.

**Comment by scienceopen** [comment]
@pv, thanks, I hadn't read that part of the documentation. It makes sense to me now that this extra step is needed.
Most often, I am only using In or Out, not InOut, but I will make a note in my page explaining f2py to those just getting started that InOut is a special case.

**Comment by DeadParrot** [comment]
@charris Super! Glad this is already fixed. Thanks for the diligence. And we didn't even have to bother Pearu!
