### ISSUE TITLE
Typo at scipy manual

### ISSUE THREAD

**Issue by izxle** [numpy/numpy#6670]
At this page: http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
It says "Be sure to understand why this is occurs."
I think it should say "Be sure to understand why this occurs."

**Comment by urbanophile** [comment]
This closed, yes?

**Comment by seberg** [comment]
No, that is still there I think.

**Comment by urbanophile** [comment]
I think this has been changed on the master branch (see issue https://github.com/numpy/numpy/commit/296b0b78fd381116b0e26c14ed5caaf1c07575a8). I am not sure how the actual Numpy documentation on the website gets updated, is that also part of addressing this issue? (I am trying to look for easy things to fix)

**Comment by seberg** [comment]
Sorry, you are right of course. I must have forgotten to pull master before checking locally.
