### ISSUE TITLE
memory leak in np.clip()

### ISSUE THREAD

**Issue by lfsimoes** [numpy/numpy#6672]
I found a usage pattern under which np.clip() leaks memory.
You can reproduce it with the following code:

    In [1]: import numpy as np
    
    In [2]: a = np.arange(10).reshape(5,2)
    
    In [3]: a
    Out[3]:
    array([[0, 1],
           [2, 3],
           [4, 5],
           [6, 7],
           [8, 9]])
    
    In [4]: b = np.array([[3,5],[0,6]])
    
    In [5]: np.clip(a, b[:,0], b[:,1])
    Out[5]:
    array([[3, 1],
           [3, 3],
           [4, 5],
           [5, 6],
           [5, 6]])
    
    In [6]: for i in xrange(10000000): np.clip(a, b[:,0], b[:,1], a)

This problem was already present in numpy 1.9.0 (installed from `numpy-1.9.0-win32-superpack-python2.7.exe`), and I was now able to reproduce it in numpy 1.10.1 (installed from Christoph Gohlke's [`numpy-1.10.1+mkl-cp27-none-win32.whl`](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) Windows binary), as well as in Linux (numpy 1.10.1, local compile through pip).

**Comment by jaimefrio** [comment]
I see nothing weird memory-wise running your code on a Mac with version 1.11.0.dev0+6d323ae.

Can you give more details on how did you detect the leak, and how big it is?

Can you build yhe latest development version and retest?

**Comment by lfsimoes** [comment]
> how big it is

Calling np.clip() like that leaks a small amount of memory every single time it's called. The longer you run the for loop in my example, the greater the memory consumption of your program should be.
Running it now (Windows, numpy 1.10.1), the process' memory consumption grew by 635.8 MB, which divided by the 10000000 calls corresponds to a leak of roughly 66.6 bytes per call.

> how did you detect the leak

I detected the leak when I started getting MemoryError exceptions in a program I was writing. After tracing the problem to its source, I realized the leak was actually coming from np.clip(). The program in question was an optimization algorithm, where at times sampled solutions might lie outside the problem's bounds. np.clip() was being used to confine them back into the search space. In my example, `a` would be a matrix of sampled vectors, and `b` each variable's bounds. In an optimization run np.clip() would get called millions of times, and so the problem became so noticeable it actually started raising MemoryError exceptions.

Note that the leak only occurs when calling np.clip() in this specific way. The way I sidestepped the problem in my code was by replacing the call `np.clip(a, b[:,0], b[:,1], a)` by `a = np.clip(a, b[:,0], b[:,1])`. So, the problem should be related to the `out` argument.

> Can you build yhe latest development version and retest?

I executed that example code just now on two more machines (Linux, with numpy 1.8.1. and a Mac with numpy 1.8.0rc1). It replicated the problem on both.

I see here that [methods.c](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/methods.c#L2127) and  [calculation.c](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/calculation.c#L892), where clip is implemented, weren't updated since August & April. I've observed the problem in numpy 1.10.1 (relased in October). So, will it make any difference if I test it on the development version?

**Comment by charris** [comment]
Probably not.

**Comment by jaimefrio** [comment]
The problem, if there is one, has to be in [`_slow_array_clip`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/calculation.c#L861), but it is hard to tell what exactly may be going wrong: everything seems correct to me. Which would explain me not seeing any leak at all.

**Comment by seberg** [comment]
My guess is, you do not see it because it is python version dependent due to different string interning rules. This should fix it:
```diff
+++ b/numpy/core/src/multiarray/calculation.c
@@ -830,7 +830,7 @@ _GenericBinaryOutFunction(PyArrayObject *m1, PyObject *m2, PyArrayObject *out,
         return PyObject_CallFunction(op, "OO", m1, m2);
     }
     else {
-        PyObject *args, *kw, *ret;
+        PyObject *args, *kw, *ret, *unsafe;
 
         args = Py_BuildValue("OOO", m1, m2, out);
         if (args == NULL) {
@@ -841,12 +841,18 @@ _GenericBinaryOutFunction(PyArrayObject *m1, PyObject *m2, PyArrayObject *out,
             Py_DECREF(args);
             return NULL;
         }
-        if (PyDict_SetItemString(kw, "casting",
-                        PyUString_FromString("unsafe")) < 0) {
+        unsafe = PyUString_FromString("unsafe");
+        if (casting == NULL) {
+            Py_DECREF(args);
+            return NULL;
+        }
+        if (PyDict_SetItemString(kw, "casting", unsafe) < 0) {
+            Py_DECREF(unsafe);
             Py_DECREF(args);
             Py_DECREF(kw);
             return NULL;
         }
+        Py_DECREF(unsafe);
 
         ret = PyObject_Call(op, args, kw);
 
@@ -861,7 +867,6 @@ static PyObject *
 _slow_array_clip(PyArrayObject *self, PyObject *min, PyObject *max, PyArrayObject *out)
 {
     PyObject *res1=NULL, *res2=NULL;
-
     if (max != NULL) {
         res1 = _GenericBinaryOutFunction(self, max, out, n_ops.minimum);
         if (res1 == NULL) {
```

**Comment by jaimefrio** [comment]
Good catch, Sebastian!

Wouldn't it make sense to simply have the dictionary stored in a `static` variable and never deallocated?

**Comment by seberg** [comment]
Dunno, probably. Interning some of these strings would likely also make sense...
