### ISSUE TITLE
Unconsistent inplace division due to buffer size

### ISSUE THREAD

**Issue by Dschoni** [numpy/numpy#6673]
Numpy 1.8.2 with python 2.7.6 has unconsistent behaviour when doing inplace division of arrays exceeding the buffer size. 

    import numpy as np
    arr = np.random.rand(2, 5000)
    arr_copy = arr.copy()
    arr_copy = arr_copy / arr_copy[0]
    arr /= arr[0]
    print np.sum(arr != arr_copy), arr.size - np.sum(np.isclose(arr, arr_copy))

Should print 0 for equal divisions.
This can be circumvented by increasing the buffersize, nevertheless it should be emphasized, that this can happen.

**Comment by charris** [comment]
The problem is that `arr[0]` is a view and you are changing the value pointed to on the fly. This may change at some point where we do something for overlapping data, but for now it is expected behavior. To fix it, make a copy of `arr[0]`.

**Comment by pv** [comment]
iow, duplicate of gh-1683, gh-6272
