### ISSUE TITLE
mmap slicing performance regression (again)

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#6677]
mmap slicing has regressed in performance again, see the mmap_slicing benchmark 1.8ms -> 5ms

only in master, maybe the overlap check?

**Comment by juliantaylor** [comment]
yup the overlap check, not too surprising though  3ms is excessive for the simple case benchmarked
we should look into optimizing it a bit

**Comment by pv** [comment]
It's probably just due to `may_share_memory` being written in Python + control flow via exceptions.
Should be easy to move it back to C.
