### ISSUE TITLE
DOC: Cython is not listed as build requirement

### ISSUE THREAD

**Issue by bsipocz** [numpy/numpy#6682]
Couldn't find it anywhere mentioned in the docs, but it seems that Cython is a build requirement of the development version.

**Comment by charris** [comment]
Good catch. Could you make a PR to fix that?

**Comment by argriffing** [comment]
I guess https://github.com/numpy/numpy/blob/master/INSTALL.txt should be updated to mention cython.  I don't know what cython version is actually required, but the script https://github.com/numpy/numpy/blob/master/tools/cythonize.py mentions cython version 0.19.

**Comment by bsipocz** [comment]
Sure, I can open one a bit later.

**Comment by monkpit** [comment]
Would it be a better idea to create a `requirements.txt` or `development.txt` file for pip purposes?

**Comment by rgommers** [comment]
@monkpit those mechanisms are a bit ugly so I'd rather not see them used. And more importantly: we should treat Cython as a compiler and not as a Python dependency. Upgrading Cython should be a conscious choice for a user, not something that happens behind his back via upgrading numpy.

**Comment by monkpit** [comment]
I was not implying that it should be upgraded, just required.

**Comment by rgommers** [comment]
I'll include this in gh-6895.
