### ISSUE TITLE
1.10.2 strides error

### ISSUE THREAD

**Issue by ahaldane** [numpy/numpy#6683]
I get this funny result with current master

    >>> np.empty((1,1), dtype='float64').strides
    (9223372036854775807, 9223372036854775807)

In 1.10.1 on my system it correctly says `(8,8)`.

Can anyone confirm this? I initially suspected build issues on my side, but it seems to happen with a fresh build.

(also, oops hit enter by accident before commenting. This is an edit)

**Comment by njsmith** [comment]
Looks like we disabled the relaxed strides canary values on the 1.10 branch but forgot to do so on master.

Both sets of strides are semantically correct; the INT_MAX ones are that way to smoke out bugs in code that relies on incorrect assumptions about strides that get broken by relaxed strides.

**Comment by charris** [comment]
@njsmith No, it was deliberate. There was discussion...

**Comment by njsmith** [comment]
Oh? OK. I guess it makes sense to wait until we're certain that we're not rolling RS back out of 1.10. Just need to make sure to remember to do it before 1.11 .

**Comment by charris** [comment]
@njsmith There is already a PR for it that that is tagged for 1.11.

**Comment by charris** [comment]
See #6342.

**Comment by njsmith** [comment]
OK, guess I'm just out of the loop :-) thanks

**Comment by ahaldane** [comment]
I missed that too, got it.
