### ISSUE TITLE
Incorrect result for np.rint on Win32, numpy 1.10.1, MKL

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#6685]
Sorry for the specificity of this message, but I'm hoping it's the right place to file this.

With 32-bit numpy + MKL on Windows:

```
>>> import numpy as np
>>> ds = 4607998452777363968
>>> int(float(ds))
4607998452777363968L
>>> int(np.rint(ds))
4607998452777363456L
```

This is true of conda numpy packages and Christoph's wheels (though these seem to have disappeared now).

**Comment by juliantaylor** [comment]
might caused the lack of generics on those platforms

**Comment by gfyoung** [comment]
I don't see this bug on my Windows32 machine.
```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more inform
>>> import numpy as np
>>> np.__version__
'1.10.2'
>>> ds = 4607998452777363968
>>> int(float(ds))
4607998452777363968L
>>> int(np.rint(ds))
4607998452777363968L
```

**Comment by mattip** [comment]
Closing, the corresponding issue in anaconda-issues is the correct place for this
