### ISSUE TITLE
numpy docs on data types do not seem to be comprehensive

### ISSUE THREAD

**Issue by cel4** [numpy/numpy#6687]
Is there a reason for some available data types like `np.float128` not being listed here?

https://github.com/numpy/numpy/blob/master/numpy/doc/basics.py

**Comment by pv** [comment]
Probably no reason.
The reference docs however are comprehensive https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html

**Comment by mhvk** [comment]
Do note the `platform?` comment and generally be careful with `float128` -- at least on intel, it really only gives you 11 bits more precision than `float64`:
```
In [40]: 1. - np.array(2.**np.arange(-54, -52), np.float64) == 1.
Out[40]: array([ True, False], dtype=bool)

In [41]: 1. - np.array(2.**np.arange(-65, -63), np.float128) == 1.
Out[41]: array([ True, False], dtype=bool)
```

**Comment by mattip** [comment]
Closing, [float128](http://www.numpy.org/devdocs/user/basics.types.html#extended-precision) is now documented
