### ISSUE TITLE
multiarray object has no attribute 'may_share_memory' from recent commit

### ISSUE THREAD

**Issue by lzkelley** [numpy/numpy#6691]
I'm getting an error on master (Python 2.7.10) from:

>commit 8efc87ec599c0b3eac4e63bea6eda9023d8ed96d
>Date:   Thu Nov 12 20:15:37 2015 +0200
>
>    ENH: reimplement may_share_memory in C to improve its performance

```
python -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lzkelley/Programs/public/numpy/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/Users/lzkelley/Programs/public/numpy/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/lzkelley/Programs/public/numpy/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/lzkelley/Programs/public/numpy/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/lzkelley/Programs/public/numpy/numpy/core/__init__.py", line 25, in <module>
    from . import numeric
  File "/Users/lzkelley/Programs/public/numpy/numpy/core/numeric.py", line 388, in <module>
    may_share_memory = multiarray.may_share_memory
AttributeError: 'module' object has no attribute 'may_share_memory'
```

**Comment by njsmith** [comment]
How did you build NumPy? This looks like the kind of error you could get if
you did an in-place build, and then a git pull, without rebuilding.

On Sun, Nov 15, 2015 at 2:39 PM, Luke <notifications@github.com> wrote:

> I'm getting an error on master (Python 2.7.10) from:
>
> commit 8efc87e
> <https://github.com/numpy/numpy/commit/8efc87ec599c0b3eac4e63bea6eda9023d8ed96d>
> Date: Thu Nov 12 20:15:37 2015 +0200
>
> ENH: reimplement may_share_memory in C to improve its performance
>
> python -c "import numpy"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/lzkelley/Programs/public/numpy/numpy/__init__.py", line 180, in <module>
>     from . import add_newdocs
>   File "/Users/lzkelley/Programs/public/numpy/numpy/add_newdocs.py", line 13, in <module>
>     from numpy.lib import add_newdoc
>   File "/Users/lzkelley/Programs/public/numpy/numpy/lib/__init__.py", line 8, in <module>
>     from .type_check import *
>   File "/Users/lzkelley/Programs/public/numpy/numpy/lib/type_check.py", line 11, in <module>
>     import numpy.core.numeric as _nx
>   File "/Users/lzkelley/Programs/public/numpy/numpy/core/__init__.py", line 25, in <module>
>     from . import numeric
>   File "/Users/lzkelley/Programs/public/numpy/numpy/core/numeric.py", line 388, in <module>
>     may_share_memory = multiarray.may_share_memory
> AttributeError: 'module' object has no attribute 'may_share_memory'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6691>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by lzkelley** [comment]
I get the same error just trying to run, `python setup.py`

**Comment by njsmith** [comment]
Try `git clean -xdf` to get a clean source tree? (Note that this will delete any files that git does not know about, so make sure you don't have any important files that you added to your tree but haven't called `git add` on. `git clean -xdn` will tell you what it's about to delete.)

**Comment by lzkelley** [comment]
Yeah... that fixed it.  Sorry, and thanks!

**Comment by njsmith** [comment]
Happy to help!
