### ISSUE TITLE
Breaking np.nan_to_num() changes from 1.9.2 to 1.10.1

### ISSUE THREAD

**Issue by bazeli** [numpy/numpy#6710]
(This issue was originally filed with Pandas: https://github.com/pydata/pandas/issues/11380)

Previously when using Pandas 0.16.2 and Numpy 1.9.2 one could run various numpy funcs on a pandas Series and have the result returned back typed as a Series (instead of an NDarray). 

Example (with numpy 1.9.2):

``` python
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(10, 1))
dfn = np.nan_to_num(df[0])
print "dfn type: %s" % type(dfn)
```

renders the following output `dfn type: <class 'pandas.core.series.Series'>`

However, when using Numpy 1.10.1, the result is now typed as an NDarray.  So far I've only tested np.nan_to_num but perhaps there are other funcs that exhibit the same behaviour.

As advised by @jreback, I am filing this as a numpy issue.

**Comment by charris** [comment]
Works for me.
```
In [1]: numpy.__version__
Out[1]: '1.11.0.dev0+d05d26a'

In [2]: import pandas as pd

In [3]: pd.__version__
Out[3]: '0.12.0'

In [4]: df = pd.DataFrame(np.random.randn(10, 1))

In [5]: nan_to_num(df[0])
Out[5]: 
0    0.660599
1   -1.014407
2    0.229367
3   -0.548650
4   -0.667053
5    0.471386
6   -1.053691
7   -0.116289
8    1.457446
9   -0.107683
Name: 0, dtype: float64
```
For reference, that last change to `nan_to_num` was #5732.

**Comment by charris** [comment]
Maybe something changed in Pandas between 12 and 17.

**Comment by njsmith** [comment]
I think between 0.12 and 0.17 they switched away from subclassing ndarray,
so I expect that would have a radical effect on their ufunc integration.
I'm a bit surprised they were managing to return Series objects at all
even. But I don't really understand those hooks so I guess it worked
somehow.
.
Probably a good idea to bring @shoyer in here too...

**Comment by shoyer** [comment]
Yes, I think @charris figured this out. Series used to be a ndarray subclass, now it is not.

`nan_to_sum` is another one of those elementwise utility functions that arguably could be a ufunc (or treated like one), but actually isn't. So, it doesn't get the standard ufunc treatment of duck-arrays.

**Comment by jreback** [comment]
@charris you need to upgrade pandas! 0.12. is from 2012!

I had mentioned a bit of this in the 0.13 announcement (several years ago) [see here](http://pandas.pydata.org/pandas-docs/version/0.17.1/whatsnew.html#whatsnew-0130-refactoring)

might make sense to have a tests to check all functions with ``ndarray`` sub-classes for conformity to calling ``__array_wrap__`` (if they are supposed to, if and if not should they).

and agree with @shoyer that making everything a ``ufunc`` is a good thing.

**Comment by charris** [comment]
@jreback This explains the old version: `url = https://github.com/wesm/pandas` ;)

**Comment by jreback** [comment]
hah @wesm fork!

**Comment by wesm** [comment]
Yeah, we moved the repo in early 2013 IIRC

**Comment by mattip** [comment]
Closing since both NumPy and Pandas have moved on since then. If it is not resolved please reopen with an update.
