### ISSUE TITLE
docs for datetime units show incorrect time spans

### ISSUE THREAD

**Issue by clwainwright** [numpy/numpy#6711]
This can be seen in http://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#datetime-units

The correct time spans should be:
```
s   second      +/- 2.9e11 years    [2.9e11 BC, 2.9e11 AD]
ms  millisecond +/- 2.9e8 years     [ 2.9e8 BC, 2.9e8 AD]
us  microsecond +/- 2.9e5 years     [290301 BC, 294241 AD]
ns  nanosecond  +/- 292 years       [  1678 AD, 2262 AD]
```
rather than
```
s   second      +/- 2.9e12 years    [ 2.9e9 BC, 2.9e9 AD]
ms  millisecond +/- 2.9e9 years     [ 2.9e6 BC, 2.9e6 AD]
us  microsecond +/- 2.9e6 years     [290301 BC, 294241 AD]
ns  nanosecond  +/- 292 years       [ 1678 AD, 2262 AD]
```

**Comment by badhrink** [comment]
I know it has been a while since this has been reported. I was fishing for my first Open Source Contribution. Is it ok if I take this up?

**Comment by shoyer** [comment]
Yes, this would be a good choice for a first contribution!

**Comment by badhrink** [comment]
Ok, this is embarassing. I made changes to the text(using the edit option in the github) in doc/source/reference/arrays.datetime.rst. 

I made a pull request (https://github.com/numpy/numpy/pull/7721). Soon after that some auto build happened and two builds failed. I got this error "Specify a project or solution file. The directory does not contain a project or solution file."

Where did I go wrong?

**Comment by shoyer** [comment]
Take a look at the contributing guidelines: https://github.com/numpy/numpy/blob/master/CONTRIBUTING.md (and links there-in)

It's a little more work to set started, but I think it's definitely worthwhile to get git setup properly on your computer.

**Comment by charris** [comment]
I don't recommend that approach for the back and forth typical of numpy PRs, but noticed that the PR was against 1.7.x rather than master. Recently testing against older branches seems to fail,  possibly because of changes in the travis tester and also that fact that appveyor is newer.
