### ISSUE TITLE
arccosh is inaccurate when numpy is built with old glibc?

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#6712]
An arccosh test is failing in one of the TravisCI scipy configurations that builds numpy. I'm speculating that this is because TravisCI runs a somewhat old Ubuntu with a glibc that has some trig function implementations that numpy has blacklisted. If that is true, could this be fixed in a way that is better than bumping the scipy test tolerances or upgrading the TravisCI platform?
https://github.com/scipy/scipy/pull/4729

**Comment by charris** [comment]
Note that `acosh` is not blacklisted for glibc earlier than 2.16 . Maybe is should be?

**Comment by argriffing** [comment]
> Note that `cacosh` is not blacklisted for glibc earlier than 2.16 . Maybe it should be?

You are right, I just checked it with a small C program on a Ubuntu 12.04 VM and `cacosh` is inaccurate. The same C program built on newer Ubuntu is accurate. But I'm not sure if the numpy fallbacks for arccosh are better; at least one of them is not:
```
#ifndef HAVE_ACOSH
double npy_acosh(double x)
{
    return 2*npy_log(npy_sqrt((x + 1.0)/2) + npy_sqrt((x - 1.0)/2));
}
#endif
```

**Comment by charris** [comment]
@ewmoore Provided the code for the blacklisted functions, so maybe he would be interested in doing more fixups.

**Comment by argriffing** [comment]
Here's the C code I was using. It prints 0 with the good C library and something like 1e-13 with the bad C library.
```c
#include <math.h>
#include <complex.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
  const double x = 1.000001430511474609375;
  const double y = 0.001691455665129294448190238354291760044433;
  const double z = creal(cacosh(x));
  printf("%g\n", (z - y) / y);
  return 0;
}
```

**Comment by argriffing** [comment]
apparently Julia has a [bsd(?)](https://github.com/JuliaLang/openlibm/blob/master/LICENSE.md) libm to solve problems like this, see https://github.com/JuliaLang/openlibm/blob/master/src/e_acosh.c
