### ISSUE TITLE
High memory peak when MaskedArray creates a mask

### ISSUE THREAD

**Issue by saimn** [numpy/numpy#6732]
Hi,
We work with huge masked arrays, and noticed that there is a high memory peak when creating a masked array with `mask=False`. In the example below you can see that when using `MaskedArray(mask=np.ma.nomask ...)` the memory does not increase and the masked array use a view of the data array. But when using `MaskedArray(mask=False ...)` there is a memory peak of ~15 times the size of the boolean mask which is created !

```python
In [1]: import numpy as np

In [2]: import ipython_memory_usage.ipython_memory_usage as imu

In [3]: a = np.zeros((10000, 10000))

In [4]: imu.start_watching_memory()
In [4] used 0.0039 MiB RAM in 16.27s, peaked 0.00 MiB above current, total RAM usage 34.67 MiB

In [5]: a[:] = 1
In [5] used 763.0234 MiB RAM in 0.20s, peaked 0.00 MiB above current, total RAM usage 797.70 MiB

In [6]: m = np.ma.MaskedArray(data=a, mask=np.ma.nomask, dtype=float, copy=False)
In [6] used 0.0000 MiB RAM in 0.10s, peaked 0.00 MiB above current, total RAM usage 797.70 MiB

In [7]: m = np.ma.MaskedArray(data=a, mask=False, dtype=float, copy=False)
In [7] used 95.4375 MiB RAM in 10.23s, peaked 1525.77 MiB above current, total RAM usage 893.13 MiB
```

The issue comes from the line `mask = np.resize(mask, _data.shape)` in https://github.com/numpy/numpy/blob/master/numpy/ma/core.py#L2770, where mask is just `array([False], dtype=bool)`. And then `np.resize` call `concatenate((a,)*n_copies)` which causes the memory peak (https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py#L1149).

Without knowing the reasons of this implementation, I wonder why the mask is not created simply with a `np.zeros(dtype=bool, ...)` (or `np.ones` depending the value of the mask parameter).

**Comment by charris** [comment]
Just for reference, could you post the numpy version as well?

**Comment by saimn** [comment]
Yep sorry, I'm using 1.10.1

**Comment by charris** [comment]
The reason I asked was that 1.10.1 has a known problem with structured/record arrays that shows up as long run times and huge memory consumption. You don't mention whether structured/record arrays are being used in addition to masked arrays, so it might not be the same problem. There was also at least one problem with masked arrays. Could you try 1.10.2rc1 by any chance? It would also be good to know if numpy 1.9 was better so as to determine if this is a regression or a long standing problem.

**Comment by saimn** [comment]
I don't use record arrays here (but I known about this issue with astropy.io.fits). I have just forked and pulled the master branch and I get the same behavior. 
With a git blame, it seems that this code almost didn't change since its origins (but I didn't check resize and concatenate), so I guess it has always been present. It may have been unnoticed since by default the mask is set to nomask, and then the peak is temporary. We are also using this for months without noticing :/

**Comment by saimn** [comment]
Forgot to close this one (since #6734 was merged).
