### ISSUE TITLE
performace issue when accessing large structured arrays

### ISSUE THREAD

**Issue by skuschel** [numpy/numpy#6739]
numpy supports to create own `dtype` definitions. I used this in order to store data together with some meta informations. Irealized, that accessing the data then becomes VERY slow (takes seconds!). Since I couldnt find any warnings about large dtype definitions it is not clear to me if this is really the inteded behaviour:
```python
mydtype = np.dtype([('metainformation', np.float64), ('data', np.float64, (1000,1000))])
strarr = np.zeros(25, dtype=mydtype)
print(strarr[2]['data'][500,500])
```
on my laptop the 3rd line takes almost 4 seconds(!), although its just accessing a single scalar element. Is this a bug or just a shortcoming, i could find the documentation of? The jupyter notebook can be found here: https://gist.github.com/skuschel/4d2085c3c377a0f833a0
(numpy 1.10.1 on python3 or python2 with arch linux)

Thanks a lot
Stephan

**Comment by charris** [comment]
Numpy 1.10.1 is know to have some problems with structured dtypes. If you are able, could you try current master (or maintenance/1.10.x)? Your example runs quickly here with the latter.

**Comment by skuschel** [comment]
I tested it with python3 on arch linux, compiled with gfortran 5.2.0  and I confirm this is fixed in all versions that I tested, which is
* current master ( dac0e5d )
* current maintenance/1.10.x ( 1f40bb0 ) 
* tag: v1.10.2rc1 ( 90d1f8f )

Manually installing v1.10.1 reproced the bug. So I believe it already got fixed for all future version. Thanks a lot!
