### ISSUE TITLE
ctypeslib.as_array aborts

### ISSUE THREAD

**Issue by PolarNick239** [numpy/numpy#6741]
This script fails:

```
import numpy as np
import ctypes

sh = (1, 1)
tmp = np.zeros(sh, np.uint8)
test = ctypes.cast(ctypes.c_void_p(tmp.__array_interface__['data'][0]), ctypes.POINTER(ctypes.c_ubyte))
np.ctypeslib.as_array(test, sh)
```

python 3.4.2-dbg
numpy==1.10.1
Ubuntu 14.10
1. Under release python this code runs without crashes, because of disabled assertions
2. Under debug release python asserts failed:
   `python3.4: ../Objects/abstract.c:2077: PyObject_Call: Assertion '(result != ((void *)0) && !PyErr_Occurred()) || (result == ((void *)0) && PyErr_Occurred())' failed.`

Can you please explain why?

P.S. may be it can help:
If `sh = (1, 1)` change to `sh = 239`:
1. Release python will raise `TypeError: shape must be a tuple`
2. Debug python will also aborts

**Comment by charris** [comment]
Works here on Python 2.7.10 debug.

**Comment by charris** [comment]
Can reproduce on 3.4.

**Comment by charris** [comment]
Also with numpy 1.9.3 and 3.4 debug, so not a regression.

**Comment by jakirkham** [comment]
Not totally sure, but have a strong feeling this may be related to these types of problems ( https://github.com/numpy/numpy/issues/6990 ).

**Comment by jakirkham** [comment]
Ran this with `gdb` and it appears it is raising a warning about having an "`Invalid PEP 3118 format string`".

**Comment by jakirkham** [comment]
> Can you please explain why?

@PolarNick239: In Python 3.x, it appears they have taken a stricter stance on Python exception handling in C. Namely, they encourage (by way of assertions) us to handle an exception before calling any function that might raise another one. In some cases, CPython has been found to be violating this and we have started finding errors of our own where we are violating this. I am not sure who is responsible in this case.

**Comment by PolarNick239** [comment]
Thanks for explanation! :)
