### ISSUE TITLE
error in documentation (numpy.diff)

### ISSUE THREAD

**Issue by smccrossin** [numpy/numpy#6751]
From the documentation on this page -- http://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html

This example is given:
array([[2, 3, 4],
       [5, 1, 2]])
>>> np.diff(x, axis=0)
array([[-1,  2,  0, -2]])

The correct answer is array([[ 3, -2, -2]]).

**Comment by seberg** [comment]
Thanks for caring to fix things, but the doc seems perfectly correct? That is not the example, that is the result of the previous example, the array x is defined a bit earlier and it fits.

**Comment by smccrossin** [comment]
Oh goodness, you’re quite right.  I misread it as being applied to the array immediately above.  Sorry about that…

regards,
Sean M
