### ISSUE TITLE
Add `ndim` attribute to dtypes

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#6752]
`ndarray`s have `shape` and `ndim` attributes.  `X.ndim` is short for `len(X.shape)`.

`numpy.dtype`s have `.shape`, but no `.ndim`.  For consistency, numpy.dtype types should have an `ndim` attribute that behaves identically to the ndarray counterpart, such that `dt.ndim == len(dt.shape)`.

**Comment by jaimefrio** [comment]
Would be good to bring up the discussion in the mailing list.

Is relatively easy to do: in `core/multiarray/descriptor.c`, add a new entry to `arraydescr_getsets`, including a pointer to the implementation of the `ndim` getter, which needs to be written as well.

**Comment by embray** [comment]
I think this seems relatively harmless and makes sense to have.

**Comment by seberg** [comment]
Dtype objects now actually have the `ndim` attribute, so this has been implemented.
