### ISSUE TITLE
Add warning for integer overflow during array operations

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#6753]
I just noticed that this:

```
In [1]: import numpy as np

In [2]: arr = np.zeros((2, 3), dtype=np.int16) + np.int16(3201)

In [3]: arr.T.dot(arr)
Out[3]: 
array([[-19966, -19966, -19966],
       [-19966, -19966, -19966],
       [-19966, -19966, -19966]], dtype=int16)
```

spits out no warning about integer overflow.  Is it possible to generate one?

**Comment by njsmith** [comment]
IIRC array operations never generate warnings for integer overflow. (Only
scalars do.) Obviously this is silly and a patch to fix it would be very
welcome (I have suggestions on how to do it), but right now I think you're
out of luck.

**Comment by seberg** [comment]
Closing as duplicate of gh-8987, which discusses the difference between scalars and arrays.
