### ISSUE TITLE
Doc: typo in random.rand docstring - replace "propagate" with "populate"

### ISSUE THREAD

**Issue by mdickinson** [numpy/numpy#6792]
I just noticed this in passing, after doing `help(np.random.rand)`:
```
Help on built-in function rand:

rand(...)
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and propagate it with
    random samples from a uniform distribution
    over ``[0, 1)``.

[...]
```
I suspect that "propagate" should be "populate" here.

**Comment by gopalmeena** [comment]
Hello guys,
Can i try to solve this issue??

**Comment by charris** [comment]
No need to ask, just make a pull request.

**Comment by gopalmeena** [comment]
So can you guide me for this issue? I am beginner to this.

**Comment by charris** [comment]
Start by reading http://docs.scipy.org/doc/numpy-1.10.1/dev/index.html and setting up a development environment.

**Comment by gopalmeena** [comment]
Yeah i have already set up development environment using that document. I am going through functions of numpy to understand it better.

**Comment by gopalmeena** [comment]
Hello sir,
I have made changes and i have send pull request also.
if there is any more fixes required to resolve this issue, let me know. 
Thanks
