### ISSUE TITLE
corrcoef[1, 0] != corrcoef[0, 1]

### ISSUE THREAD

**Issue by arokem** [numpy/numpy#6793]
On Python 3.5 (from Anaconda) with numpy 1.10.1, the following test fails:

    import numpy as np
    import numpy.testing as npt

    np.random.seed(100)  # Only happens sometimes! 
    t = np.arange(1024)
    x = np.sin(10 * t) + np.random.rand(t.shape[-1])
    y = np.sin(10 * t) + np.random.rand(t.shape[-1])
    cc = np.corrcoef(x, y)
    npt.assert_equal(cc[0, 1], cc[1, 0])

Is this by design?

**Comment by pv** [comment]
They're probably equal up to fp error?

Probable cause: it's not necessarily guaranteed that `dot(X, X.T)` is exactly symmetric, since BLAS does not know the matrices are the same.

**Comment by charris** [comment]
Master works here on 3.5
```
In [15]: cc - cc.T
Out[15]: 
array([[ 0.,  0.],
       [ 0.,  0.]])
```
I suspect it has to do with different hardware/compiler and is basically roundoff error as Pauli says. We could probably make sure the result symmetric with a bit of cleverness.

**Comment by arokem** [comment]
OK. Hadn't stumbled into this before, (i.e. previous versions of Python/numpy)  so I was considering whether this might be a regression, but I am convinced. Closing.

**Comment by njsmith** [comment]
I guess a question for someone who understands blas/lapack details better
than me: is there a more efficient X@X.T implementation available in the
underlying libraries? (I know R provides this as a built-in primitive,
allegedly so they can optimize it, but I don't know to what extent anyone
does.) If so then it might well make sense for dot() to notice this case
and optimize it. (It's trivial for dot to detect -- same data pointer,
flipped strides.)

On Tue, Dec 8, 2015 at 1:08 PM, Ariel Rokem <notifications@github.com>
wrote:

> OK. Hadn't stumbled into this before, (i.e. previous versions of
> Python/numpy) so I was considering whether this might be a regression, but
> I am convinced. Closing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6793#issuecomment-163018383>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by pv** [comment]
Yes, syrk/herk
http://www.netlib.org/lapack/lug/node145.html

**Comment by njsmith** [comment]
Thanks! Filed #6794 so we at least don't lose the idea.
