### ISSUE TITLE
Delinking Numpy from BLAS/ATLAS etc. 

### ISSUE THREAD

**Issue by Paxanator** [numpy/numpy#6796]
Hello, 

I'm trying to benchmark sparse vs. dense routines on equal footing. Numpy inherently uses BLAS and other low level routines when doing matrix operations, significantly improving performance, which is great. However, it's not an apples to apples comparison. Is there a way to change the numpy config so that it only uses C/C++/Fortran routines, so that it's comparable to scipy.sparse?

Thank you!

**Comment by charris** [comment]
Yes, but I forget what is ;)  Note that no Fortran routines will be used after the low level routines are removed.

**Comment by Paxanator** [comment]
Shoot, does it have to do with something like reassigning numpy.__config__ or would i have to uninstall numpy and reinstall ensuring that it doesn't use the lower level libraries? Any recollection?

Thanks for your help

**Comment by charris** [comment]
`BLAS=None LAPACK=None ATLAS=None python setup.py build` should do it. Note that cblas isn't handled separately, but the above should probably work.

**Comment by charris** [comment]
This is not acutually a bug report, so closing. The mailing list is a better place for questions.

**Comment by Paxanator** [comment]
Duly noted, thanks for the help
