### ISSUE TITLE
Doc comment mistake in ifft

### ISSUE THREAD

**Issue by Phaiax** [numpy/numpy#6798]
https://github.com/numpy/numpy/blob/master/numpy/fft/fftpack.py#L205

The indices for the pos to neg frequency overflows are wrong here. They are described correctly in http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.fft.html#implementation-details

**Comment by seberg** [comment]
@Phaiax, if you have a bit of time, would you mind creating a pull request to fix it? For a simple documentation fix, you can even just press on the "Edit" button (though fixing it up is not as straight forward then maybe).

**Comment by Phaiax** [comment]
Tried it, but no, I do have a proxy in my way and can't ssh or git to github.com.

**Comment by Phaiax** [comment]
And what do you mean with the "Edit" button? Cant find one even in my own fork.

**Comment by seberg** [comment]
Thanks! To make it perfect, title the PR with `DOC: short description of problem`.

**Comment by gopalmeena** [comment]
Hello sir,
In http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.fft.html#implementation-details ,
 it is give that " A[1:n/2] contains the positive-frequency terms, and A[n/2+1:] contains the negative-frequency terms, in order of decreasingly negative frequency " ,
but in https://github.com/numpy/numpy/blob/master/numpy/fft/fftpack.py#L205 ,
it is give that "  ``a[1:n/2+1]`` should contain the positive-frequency terms, and
    ``a[n/2+1:]`` should contain the negative-frequency terms, in order of
    decreasingly negative frequency.  "

So i think we should make changes in documents like this :
 ``a[1:n/2]`` should contain the positive-frequency terms, and
    ``a[n/2+1:]`` should contain the negative-frequency terms, in order of
    decreasingly negative frequency.

Am i right?
