### ISSUE TITLE
rk_beta in /random lack of robust

### ISSUE THREAD

**Issue by dylanwwang** [numpy/numpy#6800]
Even if the beta_distribution of the parameters shouldn't < 0, function rk_beta in distribution.c should check the arguments

**Comment by rkern** [comment]
It was a conscious design decision to put all argument checking into the Cython wrappers and not the C code. These functions will be called in tight loops, always with valid parameters, so duplicating the checks inside the C functions would be a waste of cycles.

**Comment by charris** [comment]
Closing as invalid.
