### ISSUE TITLE
isnan and isinf on field with union dtype mixing float and int/bool fails with SystemError: Objects/dictobject.c:2172: bad argument to internal function

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#6803]
Under some circumstances that I have not yet succeeded to reproduce across different machines/configurations:

For a structured ndarray `M` with a field `A` with union dtype `(base_dtype, new_dtype)`, where `base_dtype` derives from `numpy.floating` and `new_dtype` derives from `numpy.integer` or `numpy.bool_`, `isnan` and `isinf` on `M['A']` sometimes fails with `SystemError: Objects/dictobject.c:2172: bad argument to internal function`, as illustrated here:

```
In [1002]: M = zeros(4, [("A", ">f16", [("comps", '16?')])])

In [1046]: x = M["A"]

In [1062]: isnan(M["A"])
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-1062-e103ba5a4ee4> in <module>()
----> 1 isnan(M["A"])

SystemError: Objects/dictobject.c:2172: bad argument to internal function
```

It appears not to happen always, as it has happened that I retried the same code with some minutes in between and code that failed before succeeded on a second try, or code that failed first succeeded later.

```
In [1084]: M = zeros(4, [("A", "<f16", [("comps", '>u8', 2)])])

In [1085]: isnan(M["A"])
Out[1085]: array([False, False, False, False], dtype=bool)

In [1098]: isnan(zeros(4, [("A", "<f4", [("comps", '<u2', 2)])])["A"])
Out[1098]: array([False, False, False, False], dtype=bool)

In [1099]: isnan(zeros(4, [("A", "<f2", [("comps", '<u1', 2)])])["A"])
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-1099-24cfbf1685d2> in <module>()
----> 1 isnan(zeros(4, [("A", "<f2", [("comps", '<u1', 2)])])["A"])

SystemError: Objects/dictobject.c:2172: bad argument to internal function
```

Among other places, this leads to the same failure in `__str__` and `__repr__`.

I have reproduced the failure on one machine (48-core, 20 TB RAM, mostly somewhat old libraries) using a self-compiled Python 3.5.0 or self-compiled 3.4.3 and numpy 1.9.2 or 1.11.0.dev0+fb0a35f.  I could not reproduce it on the same or other machines (mostly normal computers) using binary installations.

**Comment by gerritholl** [comment]
I'm not sure if this is a bug in NumPy or in Python.  The [Python 3.5 docs](https://docs.python.org/3/library/exceptions.html#SystemError) tells me I should *report this to the author or maintainer of your Python interpreter*, but I believe extensions such as NumPy can also trigger this problem.

**Comment by gerritholl** [comment]
On the same machine with numpy 1.9.2, Python 3.4.3, `zeros(4, [("A", ">f16", [("comps", '16?')])])` fails with `ValueError: invalid shape in fixed-type tuple.`, `isnan(zeros(4, [("A", "<f2", [("comps", '<u1', 2)])])["A"])` still fails.  On a different machine with numpy 1.8.2, Python 3.4.3, `isnan` succeeds.

**Comment by gerritholl** [comment]
I'm trying to see if I can reproduce this on a different machine.  The machine I'm running it on is a powerful machine with 48 cores and 2 TB RAM, with panfs filesystems and probably some other unusual configurations I am not aware of.

**Comment by ahaldane** [comment]
I just tried it, your first example fails for me too with the same error.

**Comment by ahaldane** [comment]
I took a look and sort of have an idea what is going on. The actual bug is in [this](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/convert_datatype.c#L651) line in `can_cast_fields`. For example we get an error for

    >>> np.can_cast(('f4', 'i2,i2'), 'f4')
    SystemError: <built-in function can_cast> returned a result with an error set

Specifically, the problem is that `fields2 = PyArray_DESCR(FLOAT_Descr)->fields` is not `NULL`, but rather `Py_None`. Calling `PyDict_Size(Py_None)` is an error, which we never check so it only turns up much later.  In the `isinf` example the casting code gets called during ufunc type dispatch.

What isn't clear to me is:
 * Should `PyArray_DESCR(FLOAT_Descr)->fields` be `NULL` or `Py_None`? I haven't yet seen where it gets set to `Py_None` in the first place.
 * Should `np.can_cast(('f4', 'i2,i2'), 'f4')` return `True` or `False`? For the purpose of ufunc dispatch, it makes more sense to return `True`. But probably `np.can_cast((np.void, 'i2,i2'), np.void)` should return `False`.

**Comment by gerritholl** [comment]
On the same machine and configuration where the `isnan` operation described above raises a `SystemError`, the `can_cast` that you describe returns `True` for me...

**Comment by ahaldane** [comment]
Hmm you're right, I get that too now. It seems to be state dependent. 

This fails for me in some cases:

    >>> np.can_cast((">f4", 'i2,i2'), 'f4')

For me this fails in python3, and also fails in python2 but only if I run it twice, and only in the plain python2 shell and not the ipython2 shell.

**Comment by charris** [comment]
Sounds like a possible reference counting error somewhere.

**Comment by seberg** [comment]
All of the examples work fine now.  This seems to be fixed, possibly long ago.
