### ISSUE TITLE
Reference leak in np.bincount with weights attribute

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#6805]
This code should illustrate what's going on

```
import sys
import numpy as np

intp_refcount = sys.getrefcount(np.dtype(np.intp))
double_refcount = sys.getrefcount(np.dtype(np.double))

for j in range(1000):
    np.bincount([1, 2, 3])

assert intp_refcount == sys.getrefcount(np.dtype(np.intp))
assert double_refcount == sys.getrefcount(np.dtype(np.double))

for j in range(1000):
    np.bincount([1, 2, 3], [4, 5, 6])

assert intp_refcount == sys.getrefcount(np.dtype(np.intp))  # this fails
assert double_refcount == sys.getrefcount(np.dtype(np.double))
```

**Comment by gfyoung** [comment]
@jaimefrio : Just curious, with your commit, does this mean you can close the issue?

**Comment by jaimefrio** [comment]
I have code in my fork, see the link above, that fixes the reference counting, but I cannot send a PR until my employer reviews the code and OKs it. Which reminds me that I have to submit the code for review, will do so tomorrow morning.

**Comment by gfyoung** [comment]
Oh, of course!  For some reason, I misread the branch as numpy/numpy.  Sorry about that!
