### ISSUE TITLE
f2py overwrites compilation flags if FFLAGS is set

### ISSUE THREAD

**Issue by Dapid** [numpy/numpy#6809]
If the environment variable FFLAGS is set, f2py replaces its compilations flags by these, which leads to failures if they are incomplete. Distutils behaviour is to append C(XX)FLAGS instead, so it keeps the required flags.

My use case is setting `-march=` to get optimal performance in locally built packages, but f2py fails if the `-fPIC` flag is missing.

**Comment by pv** [comment]
In previous tickets this has been discussed as a feature, not bug,
cf https://github.com/numpy/numpy/issues/1171

**Comment by Dapid** [comment]
I see. In that case, it should at least trigger a warning.

**Comment by rgommers** [comment]
This can now be controlled by `NPY_DISTUTILS_APPEND_FLAGS`, and the default behavior will change to appending rather than overwriting in Numpy 1.18.0
