### ISSUE TITLE
ENV  versus site.cfg for LAPACK

### ISSUE THREAD

**Issue by mfenner1** [numpy/numpy#6810]
WIth numpy 1.10.1 and reference (netlib) lapack installed to:

```
/usr/lib64/libreflapack.so -> libreflapack.so.3
/usr/lib64/libreflapack.so.3 -> libreflapack.so.3.6.0
/usr/lib64/libreflapack.so.3.6.0
```

Everything seems good:

```
% LAPACK=/usr/lib64/libreflapack.so python setup.py config > output.txt
% tail -15 output.txt 

lapack_info:
Replacing _lib_names[0]=='lapack' with 'reflapack'
Replacing _lib_names[0]=='reflapack' with 'reflapack'
Replacing _lib_names[0]=='reflapack' with 'reflapack'
Replacing _lib_names[0]=='reflapack' with 'reflapack'
  FOUND:
    libraries = ['reflapack', 'reflapack']
    library_dirs = ['/usr/lib64']
    language = f77
    runtime_library_dirs = ['/usr/lib64']

  NOT AVAILABLE

running config
```

However, trying to recreate that with a simple site.cfg file fails (I've also tried various permutations of library_dirs and others to no avail):

```
% cat site.cfg
[lapack]
libraries=reflapack
% python setup.py config > output.txt
% cat output.txt
*****snip******
lapack_info:
  libraries lapack not found in ['/usr/lib64']
  NOT AVAILABLE
******snip*****
```

I think a hint to the issue is in the working output.txt file above:  when it says `Replacing _lib_names[0]=='lapack' with 'reflapack'`.  My guess is that for some reason (deep in numpy/distutils/system_info.py) the LAPACK env variable causes the library name to be changed, but the [lapack] section does not.

**Comment by rgommers** [comment]
@mfenner1 IIRC this is a known issue - if you change ``[lapack]`` to ``[atlas]`` then I think it'll work as expected.

**Comment by rgommers** [comment]
Found it: commit ffd4332262

**Comment by mfenner1** [comment]
@rgommers Thanks for the pointer.  I'll read through that commit.  For clarity, are you saying that if I use:

```shell
% cat site.cfg
[atlas]
libraries=reflapack
```

Then I can expect to get proper linkage?  

So, it seems that the [atlas] section name is really applied more generally than to *just* get a purely atlas library (libatlas.so or simliar) linked?

**Comment by rgommers** [comment]
Yes, I think that's the case.

**Comment by bsipocz** [comment]
It seems that this question has been answered, maybe close the issue?

**Comment by mattip** [comment]
it seems site.cfg is woefully under-documented, the closest I could find is [using env values](https://www.numpy.org/devdocs/user/building.html) but does not mention site.cfg.
Closing this and opening #14286
