### ISSUE TITLE
Upload OSX wheels to pypi before release announcement

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#6833]
I suggest that we build and upload OSX wheels for numpy releases, before announcing, to minimize the number of OSX users who accidentally pip install from source after the announcement.

I guess it's implied but not emphasized in the HOWTO_RELEASE notes.

Is that policy acceptable?  Should I add something more to the release notes?

**Comment by njsmith** [comment]
Makes sense to me.
If we want to prevent from-source builds, though, then it isn't sufficient
-- for that we need to upload the wheels before we upload the sdist. (Or
does that break everyone else's downloads if pip can see that the latest
version available is 1.11.0, but it's only available as an osx wheel?)

**Comment by rgommers** [comment]
Makes sense to me too.

I think as long as there's not days between uploading wheels and sdists, it doesn't matter too much which ones go first. Just collect them all locally and then upload them all at once with twine.

**Comment by matthew-brett** [comment]
Is there a use for doing a local tag, then `python setup.py register` to register the release, and only then:

* building the sdist locally;
* pushing the tag up to github;
* building the OSX wheels on travis;
* collecting the OSX wheels locally;
* pushing up sdist and OSX wheels at the same time.

I can imagine revising the release text on pypi a few times, possibly making more local commits to do that, before finalizing the commit that will be tagged.

It's easiest to build OSX wheels from the most recent tag (that's the default), but you can also specify a commit to build.  The commit (but not the tag, in that case) will have to be upstream on github before you do that though.

**Comment by matthew-brett** [comment]
I believe that, if there are only wheels of the wrong format available for the latest release, then pip will drop back over releases looking for a format it can use.   So it should be safe to upload the wheels first.

**Comment by rgommers** [comment]
>  then ``python setup.py register`` to register the release

Like every other ``setup.py`` command, this is evil and should be avoided - use ``twine upload -s <tarballs or wheels to upload>`` instead.

**Comment by rgommers** [comment]
The local tag and other steps sound right though.

**Comment by mattip** [comment]
We have automated this now, no? Can we close?

**Comment by rgommers** [comment]
yep, thanks
