### ISSUE TITLE
Strange casting with integers

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#6835]
So, sometimes `int`s get casted to `float`s. It seems a bit unexpected. There are some other weird cases too.

    >>> import numpy
    >>> i = numpy.uint32(7)
    >>> i
    7
    >>> i + 1
    8
    >>> i = numpy.uint64(7)
    >>> i                          # As expected.
    7
    >>> i + 1                      # Casts to float?!
    8.0
    >>> i = numpy.int64(7)
    >>> i
    7
    >>> i + 1                      # This certainly doesn't cast to float.
    8

**Comment by charris** [comment]
It is because you are combing signed (python 1) with unsigned, so numpy tries to promote both so the smallest type that can hold both, hence double when using uint64. It's a bit of a cheat, as double loses precision and isn't integer, but it has been that way forever. I agree that it is weird.

**Comment by jakirkham** [comment]
Understood, I wasn't sure if this was intentional (for the reasons that you have listed) or not, but it caught me by surprise.
