### ISSUE TITLE
Use runtests.py for travis testing.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6838]
The proposal is to use `runtests.py` as a replacement for the current script `tools/test-installed-numpy.py`. I think that using `runtests.py` would take care of the virtual environment setup and generally clean up the testing scripts.

**Comment by charris** [comment]
@pv @njsmith I'd be interested in your take on this proposal.

**Comment by njsmith** [comment]
The advantage of testing numpy-as-installed is that it tests numpy-as-installed -- so it exercises the distribution logic and should catch things like files missing from MANIFEST.in.

**Comment by rgommers** [comment]
I agree with @njsmith that we don't want ``runtests.py`` to do its virtualenv creation and build thing. There's ``runtests.py --no-build`` that can be used to test, however that's just equivalent to and less readable than ``test-installed-numpy.py``.

**Comment by charris** [comment]
Well, that didn't fly. Closing this.
