### ISSUE TITLE
NumPy for MATLAB users mathematical term abuse

### ISSUE THREAD

**Issue by Aweather** [numpy/numpy#6839]
This article https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html uses "rank" for "dimension", which is quite confusing for people who knows what the mathematical definition of rank of a matrix (but not tensor rank) is.

I suggest we change "rank-n matrix" to "n-dimensional matrix" through the article.

**Comment by charris** [comment]
Sounds good to me. May also want to use `array` instead of `matrix`.

**Comment by rkern** [comment]
I don't see any uses of "rank-n matrix".

**Comment by rkern** [comment]
Or similar construction.

**Comment by argriffing** [comment]
@rkern if you search for 'rank' on that page, there are two different meanings. One meaning is used in the line explaining `np.matrix_rank`, and I think that every other usage of 'rank' on that page uses the meaning that @Aweather suggests would be confusing for people who know what the definition of rank of a matrix (but not tensor rank) is. On the other hand it is true that the string "rank-n matrix" doesn't appear on that page.

**Comment by charris** [comment]
Also, the link is https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

**Comment by matthew-brett** [comment]
There are quite a few uses of form 'rank n' or 'rank-n' on that page.

I've edited them out in this PR:

https://github.com/numpy/numpy/pull/6841

**Comment by rkern** [comment]
I understand that there is `rank-n` but not `rank-n matrix` as @Aweather and @charris seemed to be suggesting. That would indeed be wrong. I'm in favor of clarifying the term early and specifically distinguishing it in the discussion of `matrix_rank()`. I'm not in favor of eliminating it from this document. We use the term elsewhere in the "tensor rank" sense, and it would benefit the MATLAB™ convert to be made aware of the usage in this document.

**Comment by argriffing** [comment]
It doesn't say "rank-n matrix" but it says things like "matrix objects always have exactly rank 2". This seems like a similar construction. But I understand that you could argue it's not, because of the distinction between "matrix object" vs. "matrix" or between a "rank-n" thing vs. a thing that "has rank n".

**Comment by matthew-brett** [comment]
Did you have a chance to look at my PR?  Do you think using 'one-dimensional' etc not preferable?

**Comment by charris** [comment]
@rkern The use of rank in the tensor sense has been deprecated, at least as a function in numpy, to avoid the confusing ambiguity.
```
In [2]: rank(ones(3))
/home/charris/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2641: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
Out[2]: 1
```
We should probably try to remove the usage from all our documentation.
