### ISSUE TITLE
minor typo in docs for polyval()

### ISSUE THREAD

**Issue by jason-s** [numpy/numpy#6849]
The [`polyval()` docs](http://docs.scipy.org/doc/numpy/reference/generated/numpy.polyval.html#numpy.polyval) say:

>Parameters:	
p : array_like or poly1d object
1D array of polynomial coefficients (including coefficients equal to zero) from highest degree to the constant term, or an instance of poly1d.
x : array_like or poly1d object
A number, a 1D array of numbers, or an instance of poly1d, “at” which to evaluate p.

But `x` can be more than just a 1D array of numbers, it can be any array of numbers.

**Comment by gfyoung** [comment]
Confirmed (see below)!  Quick PR can easily rectify this.
```
>>> import numpy as np
>>> p = [1, 1]
>>> x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
>>> np.polyval(p, x)
array([[ 2, 3, 4],
       [ 5, 6, 7],
       [ 8, 9, 10]])
```
