### ISSUE TITLE
Masked array `__str__` and `__repr__` fail to display dots on omitted data

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#6855]
When a masked array `__str__` or `__repr__` is requested to display _too much_ data, it neglects to display `...` on omitted values in the data.  It does display those `...` on the mask:

```
In [58]: M = ma.masked_array(arange(5000), mask=arange(5000)%5==0)

In [59]: print(str(M))
[-- 1 2 3 4 -- 6 7 8 9 -- 11 12 13 14 -- 16 17 18 19 -- 21 22 23 24 -- 26
 27 28 29 -- 31 32 33 34 -- 36 37 38 39 -- 41 42 43 44 -- 46 47 48 49 --
 4951 4952 4953 4954 -- 4956 4957 4958 4959 -- 4961 4962 4963 4964 -- 4966
 4967 4968 4969 -- 4971 4972 4973 4974 -- 4976 4977 4978 4979 -- 4981 4982
 4983 4984 -- 4986 4987 4988 4989 -- 4991 4992 4993 4994 -- 4996 4997 4998
 4999]

In [60]: print(repr(M))
masked_array(data = [-- 1 2 3 4 -- 6 7 8 9 -- 11 12 13 14 -- 16 17 18 19 -- 21 22 23 24 -- 26
 27 28 29 -- 31 32 33 34 -- 36 37 38 39 -- 41 42 43 44 -- 46 47 48 49 --
 4951 4952 4953 4954 -- 4956 4957 4958 4959 -- 4961 4962 4963 4964 -- 4966
 4967 4968 4969 -- 4971 4972 4973 4974 -- 4976 4977 4978 4979 -- 4981 4982
 4983 4984 -- 4986 4987 4988 4989 -- 4991 4992 4993 4994 -- 4996 4997 4998
 4999],
             mask = [ True False False ..., False False False],
       fill_value = 999999)
```

In particular `__str__` suggests the array jumps directly from 49 to 4951 (with a single masked value in-between).

It is also not consistent between `data` and `mask` in deciding how many values to display.

**Comment by udiboy1209** [comment]
@rgommers I would like to fix this issue.

I did some digging in the code and found this `np.concatenate` statement as the problem: [numpy/ma/core.py#L3791](https://github.com/numpy/numpy/blob/bec40c2b7912c4d94894929a2f4aca18c6d344e6/numpy/ma/core.py#L3791). I tried adding a string literal `" ... "` to the concat list, but that converts each element to a string. Plus I don't think it'll work too well for arrays with different shapes. Could you point me to the right way to do this ? :smile:

**Comment by eric-wieser** [comment]
I think this is fixed?

```
>>> M = np.ma.masked_array(np.arange(5000), mask=np.arange(5000)%5==0)
>>> print(M)
[-- 1 2 ..., 4997 4998 4999]

>>> print(repr(M))
masked_array(data = [-- 1 2 ..., 4997 4998 4999],
             mask = [ True False False ..., False False False],
       fill_value = 999999)

Trailing comma is kinda weird, but thats present in normal arrays too.
