### ISSUE TITLE
Another question on cuBLAS

### ISSUE THREAD

**Issue by fayeshine** [numpy/numpy#6862]
I knew there is a way to do matrix dot or other cuBLAS operation automatically in numpy by using nvBLAS and run as "LD_PRELOAD=/usr/local/cuda/lib64/libnvblas.so python". 

However, it only support basic BLAS opertaions, something else like SVD (in LAPACK, not quite sure), are only supported by third party packages like CULA or MAGMA, is there any way to link numpy to these higher level libraries and make SVD run faster?

**Comment by charris** [comment]
This sort of guestion is best asked on the numpy mailing list, issues are for issues ;)
