### ISSUE TITLE
Multiple examples in docstrings contain print as a statement and not a function

### ISSUE THREAD

**Issue by fijal** [numpy/numpy#6863]
Files like arrayprint.py contain examples with print being used as a statement, even though they also contain from __future__ import print_function

**Comment by rgommers** [comment]
thanks @fijal. 

marked as easy-fix, would be great if someone could search for this issue throughout the codebase (``grin " print "``) and fix it up

**Comment by gfyoung** [comment]
I have an hour to kill, and I'm too lazy to do any brain-intensive work.  Also, I video gamed myself out earlier. :smile: Should have a PR up for this soon.
