### ISSUE TITLE
Structured Array documentation is not correct

### ISSUE THREAD

**Issue by dgcatanzaro** [numpy/numpy#6878]
The documentation for Structured Arrays (found here: http://docs.scipy.org/doc/numpy/user/basics.rec.html) is incorrect.  Typing 
      y = x['foo']
gives you 
array([1, 2]) 

not what the docs say.

See my stackoverflow question here:  http://stackoverflow.com/questions/34440832/numpy-structured-array-document-confusion

**Comment by hpaulj** [comment]
In `https://github.com/numpy/numpy/blob/master/numpy/doc/structured_arrays.py`

     >>> y = x['foo']

needs to be changed to:

    >>> y = x['bar']

'foo' is the integer field, 'bar' is the float one.

**Comment by nyck33** [comment]
@argriffing 
The typo is still there.
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html

**Comment by mattip** [comment]
The [current documentation](https://numpy.org/devdocs/user/basics.rec.html) has been redone. We do not typically go back to fix typos in old documentation.
