### ISSUE TITLE
Appveyor, Windows ERROR: test_compile1 (test_system_info.TestSystemInfoReading)

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6882]
@insertinterestingnamehere Any chance you have seen this on conda in tests before?

```
======================================================================
ERROR: test_compile1 (test_system_info.TestSystemInfoReading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\numpy\distutils\tests\test_system_info.py", line 181, in test_compile1
    c.compile([os.path.basename(self._src1)], output_dir=self._dir1)
  File "C:\Py\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Py\lib\site-packages\numpy\distutils\msvccompiler.py", line 17, in initialize
    distutils.msvccompiler.MSVCCompiler.initialize(self, plat_name)
  File "C:\Py\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Py\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
ValueError: [u'path']
```

**Comment by charris** [comment]
This is only for  64 bit Python 2.7 on 64 bit windows.

**Comment by charris** [comment]
May be a Python bug on windows.

**Comment by argriffing** [comment]
I googled that error and found a discussion here https://bugs.python.org/issue7511, but I don't know anything about numpy/python/windows interactions.

**Comment by charris** [comment]
So it looks like we either need to install  Visual C++ Compiler for Python 2.7 or run 32 bits. As this is an environmental problem (and numpy seems to build), I suggest either

* disabling the test for 64 bit windows or
* running 32 bit 2.7.

**Comment by charris** [comment]
I can confirm that the test pases with 32 bit python 2.7. It also runs faster...

**Comment by njsmith** [comment]
Probably the VC++-for-py27 toolchain actually is the correct one we should be testing against in any case, since that's the only py27-compatible microsoft toolchain that microsoft is still distributing... but if installing it on appveyor creates more problems then meh.

**Comment by rgommers** [comment]
https://bugs.python.org/issue7511 is again one of those that's clearly a bug, patch is simple, but some core devs say it's not a bug so it won't get fixed. Monkeypatching distutils is an acceptable workaround though....

So +1 for disabling for now. Note that setuptools already works around this. I'll have a look at the build todo list today.

**Comment by insertinterestingnamehere** [comment]
Good find. Sorry that I sometimes miss @ mentions. It probably comes from following too many things at once. Seeing as we're using setuptools now, do we want to try moving back to 64 bit?
