### ISSUE TITLE
Unused variable declaration in generated f2pywrappers2

### ISSUE THREAD

**Issue by wtjones1** [numpy/numpy#6894]
I am using f2py for a project where the coding standards forbid the declaration of unused variables. This is enforced by automated builds which consider warnings as errors. As such, I am prevented from successfully compiling the "*-f2pywrappers2.f90" code due to the declaration of an unused variable.

The variable "j" is declared in the wrappers generated to provide the dimensions of arrays, "*_getdims_*". The declaration comes in the form of "integer r,i,j" but "j" is never used. I have tracked this down to "numpy/f2py/f90mod_rules.py" in the definition of "fgetdims1", specifically line 52 in numpy version 1.10.2. The declaration seems to have existed since at least numpy version 1.4.1. Removal of the declaration of "j", while leaving "r" and "i", eliminates the unused variable warnings.

**Comment by charris** [comment]
I am not surprised that there may be an unused variable somewhere. Want to make a PR?

@pearu Thoughts?

**Comment by rehassachdeva** [comment]
Dear developers! I am a beginner. As mentioned above, I did observe the declaration of unused variable j in f90mod_rules.py in the latest clone. Could you please assign me this issue and guide me as to if this is indeed the procedure to be followed:  
1) Fork the repository. 
2) Modify the file to remove unused variable .
3) Submit a PR.

**Comment by njsmith** [comment]
We don't do formal tracking of issue assignments. But now that you've posted then no-one's going to jump in and steal it from you ;-).

And yes, that is the general procedure for submitting changes. There's some more information available here: https://docs.scipy.org/doc/numpy-dev/dev/ (but you don't really have to like read through and memorize all of that -- if you can submit a PR then we can guide you from there :-)). Good luck!

**Comment by rehassachdeva** [comment]
Thanks a lot for pointing me to the guidelines at the above link. They were utterly helpful. :-). I have followed the process as mentioned and is up for review. Thanks again! :-)

**Comment by charris** [comment]
Closed by #6962.
