### ISSUE TITLE
Dead link in 'Building from source' doc

### ISSUE THREAD

**Issue by kohr-h** [numpy/numpy#6906]
Under the [Basic installation](https://docs.scipy.org/doc/numpy-dev/user/building.html#basic-installation) section, there is a literal
```
:ref:`development-environment`
```
under `NOTE` just before the next subsection.

**Comment by kohr-h** [comment]
Update: the reference interferes with the emphasis `*NOTE: ...*`. When the asterisks are removed, the link appears as desired (I tested it). Looks like a Sphinx bug.

Maybe something like `**NOTE:** ...` can work around the issue in the meanwhile.

**Comment by rgommers** [comment]
Thanks @kohr-h. Sent a PR to fix this: gh-6914.
