### ISSUE TITLE
Test failure (Python 2 only): ImportError (cannot import name ccompiler)

### ISSUE THREAD

**Issue by kohr-h** [numpy/numpy#6907]
Running unit tests on a fresh clone from `master` produces an error as mentioned in the title. The error only occurs with Python 2.

##### Steps to reproduce:
- Set up a virtual environment for Python 2, e.g. `mkvirtualenv numpy-py2.7; pip install nose`
- Clean up: `git clean -xdf`
- Run `python setup.py build_ext --inplace` 
- Run `python -c "import numpy; numpy.test()"`

##### Error message:
```
======================================================================
ERROR: Failure: ImportError (cannot import name ccompiler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hkohr/.virtualenvs/numpy-py2.7/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/hkohr/.virtualenvs/numpy-py2.7/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/hkohr/.virtualenvs/numpy-py2.7/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "numpy/distutils/__init__.py", line 8, in <module>
    from . import ccompiler
  File "numpy/distutils/ccompiler.py", line 8, in <module>
    from distutils import ccompiler
  File "numpy/distutils/__init__.py", line 8, in <module>
    from . import ccompiler
  File "numpy/distutils/ccompiler.py", line 8, in <module>
    from distutils import ccompiler
ImportError: cannot import name ccompiler
```

##### Possibly related (although ancient): 
#1204

**Comment by rgommers** [comment]
does that mean you also cannot use ``numpy.distutils`` in that environment to build anything? Like compiling Scipy will fail at once?

**Comment by rgommers** [comment]
``from distutils import ccompiler`` should never fail, looks like an issue with ``mkvirtualenv`` or something else in your setup.

**Comment by kohr-h** [comment]
~~I forgot to mention that the isolated command `python -c "from distutils import ccompiler"` succeeds.~~ You're right, in fact I can import `ccompiler` from `distutils` but it uses the system one. This happens probably because `distutils` are not part of `site-packages` (they reside directly in `/usr/lib64/python2.7` in my case) and thus not excluded from the virtualenv. 

Any recommendation how to work around this issue? There does not seem to be anything keeping the package from working, but it would be nice if all tests would succeed.

**Comment by rgommers** [comment]
OK I have reproduced it now. The issue is due to you running the tests from the root of the git repo. Doing:

    $ cd ../..
    $ export PYTHONPATH=/path/to/inplace_build
    $ python -c "import numpy; numpy.test()"

doesn't give any test failures.

The reason of why the error occurs is probably convoluted and annoying to investigate - I don't see much of a reason to spend that effort now.

**Comment by kohr-h** [comment]
Right, this remedies the test for me, too. Your solution may be worth a mention in [the virtualenv section of the developer docs](https://docs.scipy.org/doc/numpy-dev/dev/development_environment.html#using-virtualenvs). In any case, it's documented here, which is already helpful.

**Comment by rgommers** [comment]
Sure. Added a note to gh-6914. Under "running tests", because this is not specific to virtualenvs.
