### ISSUE TITLE
ENH: Nicer Print Displays for OLS Results?

### ISSUE THREAD

**Issue by gfyoung** [numpy/numpy#6921]
I found this <a href="https://scipy.github.io/old-wiki/pages/Cookbook/OLS2d68.html?action=AttachFile&do=view&target=ols.0.2.py">file</a> some time ago in the SciPy cookbook, and for printing / display purposes, functionality similar to this might be useful in the code base.

I'm not sure if it would be as extensive as this (the code does use ```scipy``` material, which is beyond the bounds of this repository).  However, being able to "prettify" (in ```BeautifulSoup``` speak) the results from ```numpy.linalg.lstsq``` could be of use, at least as I have found it to be the case when I want to share data with / present data to colleagues.

**Comment by rkern** [comment]
We don't presume that `numpy.linalg.lstsq()` will be used in a statistical manner, so we won't apply statistical interpretations to its results. You would probably be better served by using [statsmodels](https://pypi.python.org/pypi/statsmodels) which does all of the fancy reporting you could hope for.

**Comment by shoyer** [comment]
statsmodels solves this niche quite well:
http://statsmodels.sourceforge.net/stable/example_formulas.html#ols-regression-using-formulas

I don't think this belongs in numpy.

**Comment by gfyoung** [comment]
Ah, okay, that's good to know.  Thanks!
