### ISSUE TITLE
Why does the signature for numpy.take and numpy.compress take the array in different positiosn?

### ISSUE THREAD

**Issue by Erotemic** [numpy/numpy#6928]
I often prefer to use arr.take and arr.compress over fancy indexing alternatives, but I usually use them
when I'm sure I'm dealing with a numpy array. Recently I was dealing with a code where I needed to use the version of both functions defined in the numpy module. 

To my surprise my code started raising exceptions. It turned out that I though the signature for numpy.compress would mirror the signature of numpy.take and accept the array first and then the condition / index. 

Is there a reason that these two similar functions support non-intuitively different signatures?
It seems like both functions should take the array first as to mirror the definition in the ndarray class. 

The documentation for both functions is linked bellow: 

http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.compress.html

http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.take.html

**Comment by njsmith** [comment]
Huh, that is unfortunate.

I don't know why it was done that way. Likely the original reason is lost in the mists of time, and may not have been that satisfying anyway ("someone wrote it in a hurry and no-one noticed in time to fix it"). Unfortunately there isn't much that can be done about it at this point without breaking everyone's code, so I'm going to close this issue (we try to keep open issues for open todo items for developers).

If there's a change that you think can/should be made, feel free to say so and re-open. If you're still hoping to pick people's brains for history out of general interest, then you might want to try the numpy-discussion list, which is both better suited to general discussion like this and more likely to reach someone who might happen to remember when the function was added. Good luck!
