### ISSUE TITLE
busday_offset does the wrong thing with modifiedpreceding roll

### ISSUE THREAD

**Issue by mghiggins** [numpy/numpy#6937]
numpy v1.9.3: seems like there's a bug in busday_offset using modifiedpreceding roll - the date rolls forward instead of backward. To reproduce:

cal = numpy.busdaycalendar('1111100', [datetime.date(2016,1,1)]) # create a trivial calendar
print(numpy.busday_offset(datetime.date(2015,12,7), 0, roll='modifiedpreceding', busdaycal=cal)) # should give 4Dec2015 but gives 7Dec2015

**Comment by mwiebe** [comment]
Looks like there's a copy/paste error in the code converting the Python parameter to the C enumeration. Can see this here:

https://github.com/numpy/numpy/blob/97c35365beda55c6dead8c50df785eb857f843f0/numpy/core/src/multiarray/datetime_busday.c#L891

**Comment by mwiebe** [comment]
I've fixed it, but it also looks like your bug case isn't quite correct, since the 7th was a Monday. Using the 6th, or making the 7th a holiday, shows it working after the fix.

```
>>> import numpy, datetime
>>> cal = numpy.busdaycalendar('1111100', [datetime.date(2016,1,1)]) # create a trivial calendar
>>> print(numpy.busday_offset(datetime.date(2015,12,7), 0, roll='modifiedpreceding', busdaycal=cal))
2015-12-07
>>> print(numpy.busday_offset(datetime.date(2015,12,6), 0, roll='modifiedpreceding', busdaycal=cal))
2015-12-04
>>> cal = numpy.busdaycalendar('1111100', [datetime.date(2015,12,7)])
>>> print(numpy.busday_offset(datetime.date(2015,12,7), 0, roll='modifiedpreceding', busdaycal=cal))
2015-12-04
```
