### ISSUE TITLE
Build problems/documentation noted in 1.10.4 release.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6964]
Just a few notes resulting from 1.10.4 release for future reference 
- `paver sdist` must be run before `paver write_release_and_log,` otherwise fail.
- docs are generated with `paver pdf` (not in documentation)
- paver generates `NOTES.txt`, need to rename `README.txt` and sign for Sourceforge.
- Changelog would look far better if merge commits were not included.
- Results are in three directories `release`, `dist`, `build_doc`. That's crazy.
- `python setup.py sdist --formats=gztar,zip upload --sign` requires a `~/.pypirc` file with     `[server-login]` entry.
- If `~/.pypirc` exists, twine expects `[pypi]` and maybe `[distutils]` entries.
- twine wasn't working anyway. Problem may have been on pypi side.

Conclusions: paver script needs updating, documentation also, make a `~/.pypirc` file. It would be nice to know why twine wasn't working, but given that pypi requires a new release every time you sneeze, I'm not going to explore the issue. The generation of the mac wheel files worked well. Pypi is an undocumented PITA.

**Comment by jakirkham** [comment]
So, it looks like PyPI was having issues a few hours ago. I don't know if this was causing you grief, but it may have. ( https://status.python.org/incidents/bflmhddmcmfh )

**Comment by rgommers** [comment]
We had a ``release.sh`` that did all of this, before we switched to numpy-vendor. Now that we dropped numpy-vendor again, a ``release.sh`` would make sense again.

> ``python setup.py sdist --formats=gztar,zip upload --sign``

I recommend not to do that. First your password goes over plain http, and I've seen other crazyness like changing PyPi maintainer statuses on doing an upload like this. My WIP packaging PR parses ``setup.py`` arguments and errors on ``upload``.

**Comment by charris** [comment]
I used `setup.py` to upload because twine did not work. I think the `http` problem was fixed in later versions of Python 2.7, around 2.7.9 IIRC. I read it somewhere on the internet, maybe on the twine page.

**Comment by jakirkham** [comment]
Yes, I think you are correct that Python 2.7.9 fixed this. Also, 3.2+ has this fix. Here is the old bug report ( http://bugs.python.org/issue12226 ). This can be seen in the changelog for Python 2.7.9 ( https://hg.python.org/cpython/raw-file/v2.7.9/Misc/NEWS ).

**Comment by charris** [comment]
I wonder if there is another way to rename files that would work for recovery on pypi since the same name cannot be used twice. If it were possible to make a simple rename, upload the renamed file and delete the original life would be simpler.

**Comment by charris** [comment]
@rgommers I'm looking to cleanup the pavement script. ISTM that all that needs to be retained are the commands for generating a source distribution, the Changelog and Readme files, and the pdf documentation. That gets rid of a lot.

**Comment by njsmith** [comment]
@charris: you might be interested in https://github.com/pypa/warehouse/issues/726

Unfortunately Pypi is in this weird unmaintained state because the plan is to throw the current codebase away "soon", but the new codebase isn't ready yet and so has to focus on feature parity first and foremost... :-(

**Comment by charris** [comment]
@njsmith "two phase" sounds great! I was thinking along the same lines. What pypi lacks now is discoverability, the option to fool around and see what works and what doesn't.

**Comment by njsmith** [comment]
@charris: yeah, too bad it's just vaporware for now :-). But maybe someday...

In the mean time, there is a scratch version of pypi you can play around with if it's useful: https://wiki.python.org/moin/TestPyPI

**Comment by rgommers** [comment]
> Yes, I think you are correct that Python 2.7.9 fixed this. 

That's good to see. Python 2.7 installs < 2.7.9 are extremely common though - for example the latest Ubuntu LTS release has 2.7.6. 2.7.9 is only 1 year old. I'd prefer to stick to avoiding ``upload``.

> I'm looking to cleanup the pavement script. ISTM that all that needs to be retained are the commands for generating a source distribution, the Changelog and Readme files, and the pdf documentation. That gets rid of a lot.

It's still useful to be able to build .exe installers, for debugging purposes at least. So I'd like to keep those, at least until we have MingwPy working.

I have less use for DMG installers for OS X, but they also don't really hurt. So only +0 to throw that capability away.

**Comment by rgommers** [comment]
And instead of a ``release.sh`` like I suggested before, maybe better to add ``paver release`` that does everything in one go.

**Comment by jakirkham** [comment]
> Python 2.7 installs < 2.7.9 are extremely common though - for example the latest Ubuntu LTS release has 2.7.6. 2.7.9 is only 1 year old.

Sure. When it comes to writing a script or having a set of instructions to follow for cutting a release, it is probably best to use commands that are safe on common/older versions of Python.

**Comment by charris** [comment]
I'd pretty much like to delete almost all, if not all, of `pavement.py`. @rgommers have you changed your opinion now that we are wheels based for releases?

**Comment by rgommers** [comment]
Yes, let's get rid of most of it. The only things that need to be kept at this point are:
- `sdist` generation
- writing release notes with hashes
- writing changelog (or shall we stop doing that, I don't think it is very useful?)

If we prefer to replace those few remaining things with a bash script, that's probably a good idea (just more familiar). And the file should probably go under `tools/` rather than in the root of the repo.

**Comment by mattip** [comment]
@charris after 1.15.0, 1.15.1 do you have any insights how to proceed?
