### ISSUE TITLE
Extending RandomState to handle multiple generators

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#6967]
I have been working on a more general implementation of RandomState that allow multiple RNGs to be implemented.  The repo is [here](https://github.com/bashtage/ng-numpy-randomstate)

Currently it passes the NumPy test suite for mt19937 as well as another direct comparrison.

The library consists of a few layers:
1. The source for the RNG
2. A shim library that provides a few core RNGs - uint 32/64 and double
3. A shared set of C/pyx code that use definitions and Cython conditional compilation

Ultimately this will generate libraries for any include random number where each library contains the same RandomState class that is in Numpy.  Currently the following RNGs are available (on Linux and other unix-like OSes + Windows Py 3.5)
- mt19937 (identical to the NumPy implementation)
- xorshift128+ and xorshift1024*
- pcg-32 and pcg-64
- mrg32k3a (popular but slow, not sure it should be included in any final version)
- A basic MLFG

It is pretty easy to add new core RNGs.

In addition, it supports `jump` and `advance` for RNGs that have these capabilities, which makes it suitable for use in parallel applications.

Still has a way to go, especially for Windows 2.7/3.4 support, but seems close enough to start talking about and getting feedback.

xref #2039

**Comment by charris** [comment]
Note that new functionality has been added to `randomkit.c`. In particular, there are generators for uint16, uint8, and bool. The new generators are used in the implementation of the `dtype` parameter added to `randint`.

**Comment by bashtage** [comment]
This isn't much an an issue.  All these these type of functions are are just other consumers of uint32 values.

**Comment by bashtage** [comment]
@charris Thanks for pointing this out - I have updated the main code and it passes all NumPy tests.

@rkern Your code for PCG64 seems to work fine on windows (both VS2008 and VS 2015) simply by dropping in a 3rd party `inttypes.h` implementation.

**Comment by bashtage** [comment]
There is one feature of the existing mtrand code that strikes me as a odd, the heavy reliance on `long`/`npy_long` for functions that return integers. There were two points where I noticed this: 

* All of the integer RNGs only return values in the range `[0,...)` so an unsigned type would seem to make more sense.  
* The return size varies by platform and bitness.

This makes me wonder whether it makes more sense to try and replace the mtrand with a general structure that allow multiple generators or to just leave the mtrand as it is forever and have a separate submodule that exposes additional RNGs.  In particular, it woudl be helpful for a lot of issues if any "new" code did not have the same perpetual guarantee w.r.t. bit-wise identical results (when compiling different versions of NumPy on the same machine).

**Comment by rkern** [comment]
The reasoning of my 10-years-stupider self was that `long` is numpy's default integer type. I'm not sure which functions you are referring to, but this is mostly constrained to the distributions, not the core PRNG, and so not relevant to this issue.

**Comment by bashtage** [comment]
I fully understand why it was done, so there is no blaming :-) -- but I'm not sure one would do it that way now.  For most of the PRNGs that return integers I would think that `uint64_t` (or `npy_ulonglong`) would be a better choice _now_ (10 years ago is a long time - 64 bits was uncommon then, compilers sucked* etc) so that the return type would be the same across Windows/*nix and 32/64 bit.  Of course this comes with a perf penalty on 32 bit platforms, but I'm not sure this is much of an issue these days.

* Being strapped ot VS2008 is really annoying.  VS2015/Python 3.5 is nearly infinitely easier to get setup and use on Windows.

**Comment by shoyer** [comment]
@bashtage This is kind of a dumb question, but could you please clarify for me the difference between jumping and advancing an RNG?

**Comment by gdementen** [comment]
@shoyer advance is much more granular (you can set its states as if you drew N numbers from the generator), jump does the same thing but using a fixed, very large number of draws, which depends on the generator, e.g. 2 ** 64.

**Comment by bashtage** [comment]
What @gdementen said.  I used this notation to differentiate the two.  It also matched the source names in dSFMT/xor* (jump) and PCG (advance)

**Comment by pierre-haessig** [comment]
Hi, just to say I would find it useful to add these fast generators, as well as the Ziggurat method for Gaussian numbers.
Best, Pierre

**Comment by luk-f-a** [comment]
Hi, I was wondering if this change is still being considered. Getting the improved performance @bashtage is showing in http://bashtage.github.io/ng-numpy-randomstate/doc/performance.html would be very important for projects relying on monte carlo simulations. Many projects, like Dask, link to Numpy's generator and the impact downstream would be very appreciated. I wrote my own Dask random number generator to bypass Numpy's random state but it does not feel like a long term solution if it could be improved upstream.
Thanks!

**Comment by bashtage** [comment]
Yes, there are plans to eventually add a more model RandomState-like implementation that will split the core PRNG from the functions that transform random integers into more useful distribution. It will take a different shape from what I worked on, and may have an API that looks something like

```
rs = RandomDistributions(PRNG())
```

where `PRNG` is a class that provides the low-level core PRNG and `RandomDistributions` is a class that transforms these.  `PRNG` will expose some opaque C functions that will be directly used by `RandomDistributions` to avoid Python overhead.  I would like `PRNG` to also expose a python interface to random stream both for testing and for users to develop distributions or algorithms that are not in NumPy.  This framework will also allow end users to develop `AltRandomDistributions(PRNG())` when they need performance using Cython (or perhaps even numba if `PRNG` can be easily consumed by numba)

This was the latest from a mailing list thread about the future.

**Comment by luk-f-a** [comment]
great to hear, thanks a lot for the work!

**Comment by MichaelClerx** [comment]
This would be great to have in numpy, particularly the features that make it suitable for parallel applications!

**Comment by bashtage** [comment]
I have put together a minimal working prototype at 

https://github.com/bashtage/core-prng

that uses a simple PRNG call SplitMix64, is deterministically seeded and only return uint64s.

**Comment by bashtage** [comment]
xref #13163 . This is fixed in the randomgen branch.
