### ISSUE TITLE
numpy.place - strange behaviour with array of strings

### ISSUE THREAD

**Issue by WojciechMigda** [numpy/numpy#6974]
I am using:
 * `Python 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010] on linux2`
 * numpy 1.10.1
 * `Linux wojtek-dell 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Given this snippet:
```
import numpy as np
arr = np.array(['12', '34'])
np.place(arr, np.array([False, True]), '9')
print arr
```
I would imagine that `arr` will equal `['12' '9']`, but instead it is `['12' '94']`.
Similar code with `numpy.putmask`gives expected `['12' '9']`.
Is this a designed behaviour of `numpy.place`?

**Comment by gfyoung** [comment]
From the documentation, it sounds like they do sound very similar.  Underneath the hood, the implementations are slightly different.  ```np.putmask``` calls ```memmove``` with the ```size_t``` input equal to the size of an element in ```arr``` (method can be found <a href="https://github.com/numpy/numpy/blob/c0e48cfbbdef9cca954b0c4edd0052e1ec8a30aa/numpy/core/src/multiarray/item_selection.c#L426">here</a>), whereas ```np.place``` calls ```memcpy``` with the ```size_t``` input equal to the size of an element in ```values``` (method can be found <a href="https://github.com/numpy/numpy/blob/9ce9b9a7244f4d583e9bc6bc798f642226e6c4b6/numpy/core/src/multiarray/compiled_base.c#L359">here</a>).

That difference (I think) would explain why you were seeing what you saw.  By equating the ```size_t``` input to the size of an element in ```arr```, you ensure that the element gets completely overwritten in memory, whereas equating the ```size_t``` input to the size of an element in ```values``` means that only part of an element in ```arr``` could be overwritten if the size of the ```values``` elements are smaller than those of ```arr```.  As you can see from your method call to ```np.place```, the '9' replaced the first element of '34' to get '94'.

**Comment by gfyoung** [comment]
If what I'm describing was the intention, then the documentation does not make that clear and should be clarified, though I must say it would get kind of nasty having to describe the C internals.  Also, I think that the documentation should clarify how ```np.place``` differs from ```np.putmask``` given how similar they are.

**Comment by seberg** [comment]
Sounds like a bug. I would generally suggest to use `np.copyto` or (in this case) boolean fancy indexing to achieve the same and avoid `np.place` or `np.putmask`. I realize that in some cases those functions are not quite 1:1 replaces by these.

**Comment by njsmith** [comment]
This just looks like some broken code to me, a living fossil from the ancient days when it hadn't yet occurred to anyone that one might want to store something besides numbers and objects inside arrays.

**Comment by seberg** [comment]
`putmask` already points to `copyto` (but with some wonky NA details), `place` should also point to advanced indexing, some easier doc fix for someone who wants to do a good deed for the day.

**Comment by gfyoung** [comment]
@seberg : IIUC the behavior of ```np.place``` and ```np.copyto``` are slightly different.

Out of curiosity though, what exactly is the difference supposed to be between ```np.place``` and ```np.putmask```?  They sound exactly the same from the documentation, especially if the string behavior is in fact a bug.

**Comment by gfyoung** [comment]
@seberg : I'm not sure I quite follow your comments about documentation.  I'm actually planning to put up a PR related to these functions, so your suggestions, once clarified, should certainly be useful.

**Comment by seberg** [comment]
`putmask` is like copyto, "indexed"/changed array and "values put in array" are iterated together and wherever it is True the value is copied into the "indexed" array from the "values" array. In other words, "indexed"/changed array and "values" array have *the same shape*, the shape of the "mask" array is irrelavent. The mention of preserving NA values for copyto is from stuff that had to be ripped out again (but left some residues in places like here).

`place` is like advanced boolean indexing, which means that the "values" array should have the same length as `np.flatnonzero(mask)`.

I am not quite sure without checking. At least place might be a flattened version, which would mean that the equivalency in some corner cases is more with `arr.flat[mask] = values` instead of `arr[mask] = values` (though I am not a big fan of the flat iterator especially in those corner cases....)

**Comment by gfyoung** [comment]
@seberg Okay, now I see the difference between ```place``` and ```putmask```.  I should change that in my PR as well.  Thanks!

Regarding ```place```: does ```values``` <b>have to</b> have the same length as ```np.flatnonzero(mask)```?  I tried calling ```place``` where that wasn't true, and it handled the call just fine without any errors / warnings.

**Comment by seberg** [comment]
No, it is like the flat iterator in that regard (I expect). That would mean that the shapes can all be complete nonsense it just iterates them all in C-order (possibly repetitively) until its done.

**Comment by njsmith** [comment]
@seberg: should we just rip out the implementations of these things and replace them with the equivalent calls to the functions/indexing that work?

**Comment by seberg** [comment]
@njsmith I would like it, but you first have to make sure they actually are identical to the flat iterator. `np.put` is not quite, since it has the kind of "mode" parameter as `np.take`, but `place` likely can just point there.
I would still be in favor of pointing people away from them in the doc, the way the `flat` iterator does things sloppily is a bad idea unless needed IMO.

**Comment by gfyoung** [comment]
@seberg : Could we instead just enforce shape parameters?  Perhaps we start with a ```RuntimeWarning``` if the args that don't match in shape and then turn it into an error later?

**Comment by njsmith** [comment]
I'm not so much worried about the flat iterator stuff as the fact that this
code has all these direct calls to memcpy etc. rather than going through
the dtype's PyArray_ArrFuncs structure which is just completely wrong.

On Tue, Jan 12, 2016 at 1:38 AM, seberg <notifications@github.com> wrote:

> @njsmith <https://github.com/njsmith> I would like it, but you first have
> to make sure they actually are identical to the flat iterator. np.put is
> not quite, since it has the kind of "mode" parameter as np.take, but place
> likely can just point there.
> I would still be in favor of pointing people away from them in the doc,
> the way the flat iterator does things sloppily is a bad idea unless
> needed IMO.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6974#issuecomment-170852391>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by seberg** [comment]
Yeah, doing away with the weird shapes would be a second step. And I think it is likely better to just document the preferred version. For some normal indexing we are in fact doing the deprecation right now.

**Comment by gfyoung** [comment]
@seberg : When you say "preferred version," what do you mean exactly?  Like the preferred version of the indexing OR the preferred function that we should call instead (e.g. ```np.copyto``` instead of ```np.put```)?

**Comment by seberg** [comment]
I think the preferred version is one of the two:
  * `arr[mask] = values`
  * `np.copyto(arr, value, where=mask)`

Which one depends on what you want to do. Though I admit that subclasses can override `place`. This to me seems preferable over the actually probably *compatible* version/replacement of `arr.flat[mask] = values` in the case of `place` (there is no compatible replacement for `putmask` probably.

**Comment by gfyoung** [comment]
@njsmith : Just to make sure I'm understanding this properly, when I call ```np.putmask```, are we actually calling that ```PyArray_FastPutmaskFunc``` function in the dtype's ```PyArray_ArrFuncs```?  I'm just not sure how everything gets linked up here when I do ```setup.py``` on ```numpy``` because I know eventually it gets stored in a ```multiarray``` lib that I cannot read.

**Comment by gfyoung** [comment]
@seberg : IIUC I think it may be the other way around.  I think ```putmask``` can be replaced with ```np.copyto```, whereas ```np.place``` has no equivalent given the way it does its replacement.

**Comment by njsmith** [comment]
@gfyoung: `np.putmask` is implemented by `array_putmask` in `multiarraymodule.c` (how I figured this out: C functions exposed to python are always listed in a structure that contains a C string naming the Python function, so I did `git grep '"putmask"'` -- notice that this is searching for the string `"putmask"` with the double-quotes included as part of the search). And `array_putmask` is a tiny wrapper around the global function `PyArray_PutMask`, and you can trace it from there.

**Comment by njsmith** [comment]
Another stopgap measure if we don't have an easy way to fix these functions, and don't want to spend the time to rewrite them properly, would be to add a check at the entry that errors out if the array has any dtype aside from the built-in fixed-width ones like `int64`, so at least users are protected from the code's brokenness.

**Comment by gfyoung** [comment]
Is this a bug as well?
```
>>> import numpy as np
>>> mask = [True, False]
>>> replace = 'FOO'
>>>
>>> m = np.array(['A', 'B'])
>>> np.place(m, mask, replace)
>>> m
array(['F', 'O'],
      dtype='|S1')
>>>
>>> m = np.array(['A', 'B'])
>>> np.copyto(m, replace, where=mask)
>>> m
array(['F', 'O'],
      dtype='|S1')
>>>
>>> np.put(m, [0], replace)
>>> m
array(['F', 'O'],
      dtype='|S1')
```
It seems like strange things happen when the element size of the copied elements in ```values``` / ```src``` differ from those in ```array``` / ```dest```.  In this case, we get this unexpected truncation, which also occurs when you use integers of different sizes (e.g. replace ```np.int8``` with ```np.int64```

**Comment by njsmith** [comment]
I guess place should do whatever the regular casting rules would do.

**Comment by gfyoung** [comment]
@njsmith : I'm not too familiar with what the "regular casting rules" are.  Are you  saying that the code I showed above is to be expected because we're casting an ```'|S2'``` string into ```'|S1'```, which is the dtype of ```m```?

**Comment by njsmith** [comment]
I'm saying that `place` should do the same thing as, say, array assignment. Whatever that might be.

I guess assigning an S2 into an S1 does silently truncate, which is arguably a bad idea, but at least it means place and array assignment are consistent, so it's not a unique bug in `place`:
```
In [2]: a = np.array(["x", "y"])

In [3]: a[0] = "qq"

In [4]: a
Out[4]: 
array(['q', 'y'], 
      dtype='<U1')
```

I suspect if you try using these functions on record arrays then that might also produce some highly weird results...

**Comment by gfyoung** [comment]
Oh, no, I certainly agree it's not an issue just with ```np.place```!  That's why I demonstrated the issue with each of ```np.place```, ```np.put```, and ```np.copyto```. Bug is everywhere! :smile:

**Comment by gfyoung** [comment]
@njsmith : But okay, I understand what you mean though.  In which case, the original issue that @WojciechMigda brought is in fact a "bug" in the sense that it is no consistent with what array assignment does, which is aligned with what ```np.putmask``` does.

**Comment by seberg** [comment]
My guess for the copyto case at least is that the string gets interpreted as an iterable. Not sure why this happens though, since array assignment (with `arr[...] = "Foo"``) does not do this, and it should use pretty much the same code IIRC.

**Comment by seberg** [comment]
Its possible that the indexing code somehow ensures conversion to array always (unless its an object array). The copyto code however might support any buffer, and a string is also a buffer.

**Comment by gfyoung** [comment]
@seberg : I'll poke around and see.

<b>@Everyone</b>: I've been trying to figure how that strange copying takes place with the example @WojciechMigda gave, and I think it's this line right <a href="https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/compiled_base.c#L413">here </a>.  It seems like the resulting element size in ```avals``` does not match that of ```ainput```, even though its dtype information is passed in.

I tried changing the line to this to match the definition of ```PyArray_FromObject```, except with the actual ```PyArray_DESCR(ainput)``` object passed in like this:
```
avals = (PyArrayObject *)PyArray_FromAny(vals, PyArray_DESCR(ainput), 0, 1,
                                           NPY_ARRAY_BEHAVED | NPY_ARRAY_ENSUREARRAY, NULL);
```

However, this segfaults Python.  Any ideas about why this is happening?
