### ISSUE TITLE
BUG: distutils.misc_util.mingw32() is completely broken

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#6981]
See comments in gh-6978. 

All compiler/bitness detection for Windows needs a rewrite, this can be included. See https://github.com/mingwpy/mingwpy.github.io/issues/19 for more details.

**Comment by techtonik** [comment]
1. `--build-for-bitness=32` and `--build-for-bitness=64`
2. `debug.log.bitness = True`

Is that it?

**Comment by carlkl** [comment]
This issue should be closed IMHO due to the fact that PYPI numpy is not build by mingwpy and https://github.com/numpy/numpy/pull/6978 is merged. @rgommers, any comments?

**Comment by rgommers** [comment]
> This issue should be closed IMHO due to the fact that PYPI numpy is not build by mingwpy and #6978 is merged. @rgommers, any comments?

It doesn't look like it is fixed, so this is still a `numpy.distutils` bug (`numpy.distutils.misc_util.mingw32()` must reliably detect whether a 32-bit MinGW compiler is installed). gh-6978 just fixed an issue that was caused by `misc_util.mingw32()` being broken, but didn't fix `misc_util.mingw32()` itself.

It's not high prio though, given that we're not building with MinGW at the moment. But it's still a bug.

**Comment by InessaPawson** [comment]
Given numpy.distutils has been officially deprecated, should we close this issue?
