### ISSUE TITLE
BUG: Clear errors before contructing error message that use `PyObject_Repr`

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#6990]
It turns out in Python3, when using debugging, they have been a bit more strict about stopping one from using `PyObject_Repr` when an exception is being handled, which sounds like a good practice as `PyObject_Repr` could raise an exception. As a result, one will see an interpreter crash if an exception is already present when running `PyObject_Repr`.

We use `PyObject_Repr` a lot when constructing exceptions as we may want to include `dtype`s or something else in the message. That being said, we need to do a better job of clearing the current exception when build the exception message. So, we need to clean up the code so that errors are cleared first by using `PyErr_Clear` before constructing the new error message. If the old error message is still needed for some reason, we need to store it somewhere else before clearing.

Also, we need to do a better job at checking to see if `PyObject_Repr` or similar is creating an exception. As `PyObject_Repr` can raise an error, we need to make sure that we are checking to see if it errored and forwarding it on instead of continuing to construct our error message.

To see an example of how this can be solved take a look at this PR ( https://github.com/numpy/numpy/pull/6988 ).

<br>
Thanks to @seberg and @charris for helping me get the needed pieces to figure out what was going wrong here.

<br>
Below is a compiled check list of problems I have found. The line numbers are based on a commit present when this issue was opened; so, code changes in those files may have shifted them. That being said, the links will use that same commit so it is a good place to start. Feel free to add others to this issue.

- [x] `PyArray_AssignArray` ( [numpy/core/src/multiarray/array_assign_array.c#L271-L284](https://github.com/numpy/numpy/tree/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/multiarray/array_assign_array.c#L271-L284) )
- [x] `PyArray_AssignRawScalar` ( [numpy/core/src/multiarray/array_assign_scalar.c#L204-L217](https://github.com/numpy/numpy/tree/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/multiarray/array_assign_scalar.c#L204-L217) )
- [x] `PyArray_FromArray` ( [numpy/core/src/multiarray/ctors.c#L1928-L1944](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/multiarray/ctors.c#L1928-L1944) ) ( resolved in https://github.com/numpy/numpy/pull/6988 )
- [x] `convert_datetime_metadata_tuple_to_datetime_metadata` ( [numpy/core/src/multiarray/datetime.c#L1815-L1821](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/multiarray/datetime.c#L1815-L1821) )
- [x] `arraydescr_setstate` ( [numpy/core/src/multiarray/descriptor.c#L2742-L2746](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/multiarray/descriptor.c#L2742-L2746) )
- [x] `array_astype` ( [numpy/core/src/multiarray/methods.c#L842-L856](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/multiarray/methods.c#L842-L856) )
- [x] `npyiter_check_casting` ( [numpy/core/src/multiarray/nditer_constr.c#L1297-L1312](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/multiarray/nditer_constr.c#L1297-L1312) )
- [x] `npyiter_check_casting` ( [numpy/core/src/multiarray/nditer_constr.c#L1319-L1335](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/multiarray/nditer_constr.c#L1319-L1335) )
- [x] `PyUFunc_ValidateCasting` ( [numpy/core/src/umath/ufunc_type_resolution.c#L66-L80](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/umath/ufunc_type_resolution.c#L66-L80) )
- [x] `PyUFunc_ValidateCasting` ( [numpy/core/src/umath/ufunc_type_resolution.c#L85-L99](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/umath/ufunc_type_resolution.c#L85-L99) )
- [x] `PyUFunc_AdditionTypeResolver` ( [numpy/core/src/umath/ufunc_type_resolution.c#L748-L759](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/umath/ufunc_type_resolution.c#L748-L759) )
- [x] `PyUFunc_SubtractionTypeResolver` ( [numpy/core/src/umath/ufunc_type_resolution.c#L934-L945](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/umath/ufunc_type_resolution.c#L934-L945) )
- [x] `PyUFunc_MultiplicationTypeResolver` ( [numpy/core/src/umath/ufunc_type_resolution.c#L1078-L1089](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/umath/ufunc_type_resolution.c#L1078-L1089) )
- [x] `PyUFunc_DivisionTypeResolver` ( [numpy/core/src/umath/ufunc_type_resolution.c#L1198-L1209](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/umath/ufunc_type_resolution.c#L1198-L1209) )
- [x] `PyUFunc_DefaultLegacyInnerLoopSelector` ( [numpy/core/src/umath/ufunc_type_resolution.c#L1323-L1333](https://github.com/numpy/numpy/blob/3a9c90cbfd6057e9f124f3d31b82f8c0ad22cd20/numpy/core/src/umath/ufunc_type_resolution.c#L1323-L1333) )
- [x] `raise_binary_type_reso_error` [ufunc_type_resolution.c#L72-L90](https://github.com/numpy/numpy/blob/31e71d7ce8d447cb74b9fb83875361cf7dba4579/numpy/core/src/umath/ufunc_type_resolution.c#L72-L90)
Edit: Fixed the formatting as it appears GitHub's parser's behavior changed since last creating this list.

**Comment by jakirkham** [comment]
Oops, looks like GitHub read "partial fix" as "fix". @charris, could you please reopen this one? We have only fixed one of these.

**Comment by jakirkham** [comment]
Thanks @njsmith.

**Comment by eric-wieser** [comment]
Worked through most of the `ufunc_type_resolution` ones in #12593 and #12178, updated your checklist

**Comment by seberg** [comment]
Closing, all of these things use `PyErr_Format` now which protects us from the issue.  The ufunc type resolution usages close `raise_binary_type_reso_error` may be lacking some (practically impossible to hit) error checks, but that is unrelated to this.
