### ISSUE TITLE
Different behaviour with (+,-,*,/)= and = operators

### ISSUE THREAD

**Issue by osadj** [numpy/numpy#7006]
Numpy arrays have different behaviors with (+,-,*,/)= and = operators. Here is an example for clarification:

import numpy as np

def myfunc(a):
    a /= 2

def myfunc1(a):
    a = a / 2

a = np.ones((10))
print a
#[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
myfunc(a)
print a
#[ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]
myfunc1(a)
print a
#[ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]

Any thoughts?

**Comment by shoyer** [comment]
Yes, the inplace operators like `/=` modifies the input array in place.

Your function myfunc1 is actually a no-op, because despite assigning to the variable `a`, it isn't returned. You might want to read up on Python's memory model if this is confusing.
