### ISSUE TITLE
np.inner 

### ISSUE THREAD

**Issue by tonyshardlow** [numpy/numpy#7007]
np.inner(x[:,0],y[:,1]) gives unexpected result when used with 2d arrays x,y. See code below.
--
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  7 2015, 14:10:42) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.

import numpy as np
x=np.random.rand(2,3)
y=np.random.rand(2,3)
a=np.inner(x[:,0],y[:,1])
b=np.dot(x[:,0],y[:,1])
c=np.inner(np.copy(x[:,0]),np.copy(y[:,1]))
f1=(np.fabs(a-c)<1e-14)
f2=(np.fabs(b-c)<1e-14)
print "x[:,0] = ",x[:,0]
print "y[:,1] = ",y[:,1]
print "np.copy(x[:,0]) = ", np.copy(x[:,0])
print "np.copy(y[:,1]) = ", np.copy(y[:,1])
print "a = ", a
print "b = ", b
print "c = ", c
print "inner=dot",f1,"\ninner(with copy)=dot",f2

x[:,0] =  [ 0.62403884  0.46967722]
y[:,1] =  [ 0.06379449  0.74974141]
np.copy(x[:,0]) =  [ 0.62403884  0.46967722]
np.copy(y[:,1]) =  [ 0.06379449  0.74974141]
a =  0.0571105918141
b =  0.391946700676
c =  0.391946700676
inner=dot False 
inner(with copy)=dot True

np.version.version
Out[4]: '1.10.1'

**Comment by charris** [comment]
Known problem, you need to upgrade numpy.
