### ISSUE TITLE
DOC: `mgrid` documentation is unclear for complex step

### ISSUE THREAD

**Issue by ZedThree** [numpy/numpy#7009]
When using a complex step with `numpy.mgrid`, the resulting output is similar to `numpy.linspace` where the step specifies the number of elements:

```
>>> np.mgrid[-1:1:5j]
array([-1. , -0.5,  0. ,  0.5,  1. ])
>>> np.linspace(-1,1,5, endpoint=True)
array([-1. , -0.5,  0. ,  0.5,  1. ])
```

But without the complex step, it is similar to `numpy.arange` where the step is actually the step length, i.e. the difference between elements:

```
>>> np.mgrid[-1:1:5]
array([-1])
>>> np.arange(-1,1,5)
array([-1])
```

The documentation doesn't make it clear that specifying a complex step does **two** things: makes the stop inclusive **and** changes the meaning of the step to be the number of elements, rather than the difference between elements. In order to just switch between the stop being inclusive/exclusive, one also has to take the reciprocal of the step.

**Comment by gfyoung** [comment]
Which documentation are you looking at?  If you type ```np.info(np.mgrid)```, IIUC I think they do make the distinction that you are describing.

**Comment by InessaPawson** [comment]
Thank you for sharing your thoughts, @ZedThree! We have reviewed the documentation related to `mgrid` and added a how-to-guide further clarifying the usage of NumPy functions for partitioning domains: https://numpy.org/doc/stable/user/how-to-partition.html.
