### ISSUE TITLE
np.diagonal returns non-writeable array in 1.10.1

### ISSUE THREAD

**Issue by The-Fonz** [numpy/numpy#7010]
Contrary to the docstring of `np.diagonal`, the returned array is non-writeable. The docstring says (predicts?) that for version 1.10 it is be writeable.

```
In [23]: np.version.full_version
Out[23]: '1.10.1'

In [24]: a = np.random.random(9).reshape((3,3))

In [25]: np.diagonal(a)[0] = 1
Traceback (most recent call last):

  File "<ipython-input-25-8277268b3e32>", line 1, in <module>
    np.diagonal(a)[0] = 1

ValueError: assignment destination is read-only
```

**Comment by njsmith** [comment]
Doh, yes, as you've guessed, that's just a forgotten message from the past
that should have gotten updated at some point but never did. It indeed is
not writeable in 1.10, and won't be writeable in 1.11 either given that
we're only a few days from branching and haven't talked about it at all.
I'll submit a patch to fix the message.
