### ISSUE TITLE
16-byte algined memory for NumPy development

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#7013]
Does anyone have any insights on getting 16 byte aligned memory (at least on x86/_64 systems)?  I saw #1165 and #1166 but this doesn't seem to have gone anywhere.

I have implemented dSFMT as an alternative to the random-kit generator in an attempt at general structure for RandomState here https://github.com/bashtage/ng-numpy-randomstate/ .  Unfortunately I can't use `-DHAVE_SSE2` since on occasion the allocated memory is not aligned.

The obvious solution is to over allocate memory to ensure that the key array si 16-byte aligned, but this feels clumsy at best. If anyone has experience with this it would be appreciated.

**Comment by bashtage** [comment]
Found [this reference](https://github.com/hgomersall/pyFFTW/blob/master/pyfftw/utils.pxi) for working with FFTW which suggests that overallocation and manual alignment is solution.

**Comment by juliantaylor** [comment]
btw. on x86_64 systems memory is always 16 byte aligned
also modern intel and amd cpus don't care about alignment anymore, that ended with the haswell

**Comment by bashtage** [comment]
Thanks - I'm surprised I missed  #5312 which is almost exactly what I need, and done better than my one-off-solution.

I think alignment still matters when interfacing with 3rd party code which uses SSE2 intrinsics that require alignment (short of rewriting SSE2 parts of the code).
