### ISSUE TITLE
NaT comparison change breaks pandas test suite

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#7019]
xref https://github.com/pydata/pandas/issues/12049

The source issue is changing NaT comparison (https://github.com/numpy/numpy/pull/7001)

I'll take a look and see if this is user facing or just in the test suite. If it does effect users, we may need to do a deprecation cycle instead.

**Comment by charris** [comment]
Thanks for testing that. Better now than later...

**Comment by shoyer** [comment]
Unfortunately, this change breaks several user facing APIs in pandas. We'll need to roll this change back for the NumPy v1.11 release, and preferably insert a deprecation warning in its place.

**Comment by jreback** [comment]
``pandas`` side fixes are actually pretty easy https://github.com/pydata/pandas/pull/12058 (and compat across numpy versions)

but I agree with @shoyer you might consider providing a ``FutureWarning`` for a version so people can take action :)

**Comment by njsmith** [comment]
Yeah, that'd probably be more virtuous of us anyway...

On Fri, Jan 15, 2016 at 1:15 PM, Jeff Reback <notifications@github.com>
wrote:

> pandas side fixes are actually pretty easy pydata/pandas#12058
> <https://github.com/pydata/pandas/pull/12058> (and compat across numpy
> versions)
>
> but I agree with @shoyer <https://github.com/shoyer> you might consider
> providing a FutureWarning for a version so people can take action :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/7019#issuecomment-172094381>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by charris** [comment]
@jreback  We are going to an accelerated release schedule. How long a *time* would you like to see a `FutureWarning`?

**Comment by jreback** [comment]
@charris 

ideally only 1 major release cycle.

we have not been good about that and have been leaving ``FutureWarnings`` open way to long IMHO. (going to fix this soon), e.g. https://github.com/pydata/pandas/issues/6581

**Comment by charris** [comment]
@shoyer Do you want to take care of this? Sounds like we need to revert the merge and put in place a FutureWarning.

**Comment by charris** [comment]
If not, let me know and I'll do it.

**Comment by shoyer** [comment]
Is there a cleaner way to handle this than putting the deprecate inside that ufunc kernel? That seems likely to have performance consequences.

**Comment by charris** [comment]
Oh, that's nasty. We don't want it in the loop if it can be helped, we would need to acquire the GIL. OTOH, we would need to check for NAT anyway if we want the warning to be specific. The only thing that occurs to me is to maybe make a wrapper function that shadows the true function, but that could be tricky. what with promotions and all and probably wouldn't make things any faster. Or we could just live with it for a release cycle. Hmm...

If anyone has ideas don't hesitate to make a suggestion.

**Comment by charris** [comment]
> what is your expected cycle time for major releases?

We are shooting for 3-4 months.

**Comment by njsmith** [comment]
I guess we should just put it in the inner loop and pay the cost -- we'll
only pay an extra penalty when the ufunc execution requires multiple passes
through the inner loop, and that shouldn't be common, and we attempt to
minimize passes in any case to amortize their cost?

On Fri, Jan 15, 2016 at 6:34 PM, Charles Harris <notifications@github.com>
wrote:

> what is your expected cycle time for major releases?
>
> We are shooting for 3-4 months.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/7019#issuecomment-172148360>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by charris** [comment]
This is what I'm thinking at the moment

* revert #7001 before branching
* put future warning in loop before branching 1.11
* put #7001 back in for 1.13, which should release Aug-Sept.

**Comment by njsmith** [comment]
Sounds good to me

**Comment by shoyer** [comment]
@charris Yes, I think that's what needs to be done. If you're able to do that quickly that would be appreciated -- if not I should be able to find some time to fix this tomorrow.

**Comment by charris** [comment]
I can do the reversion tonight, but I'm not going to try anything that needs the little gray cells. If you can't get to it tomorrow let me know and I'll give it a shot. The 1.11 branch may be a day or two late in any case.

**Comment by charris** [comment]
@shoyer How does your time look? I can do the `FutureWarning` this afternoon if you don't have the time.

**Comment by charris** [comment]
Just for reference
```
#define NPY_ALLOW_C_API_DEF  PyGILState_STATE __save__;
#define NPY_ALLOW_C_API      do {__save__ = PyGILState_Ensure();} while (0);
#define NPY_DISABLE_C_API    do {PyGILState_Release(__save__);} while (0);
```

**Comment by charris** [comment]
See #7057.

**Comment by charris** [comment]
On track for 1.13, closing this.
