### ISSUE TITLE
pandas wants us to provide 2.7 dev wheel snapshots too

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#7024]
Pandas is requesting that in addition to current py35 snapshots we're uploading to travis-dev-wheels.scipy.org, we also upload py27 snapshots. This should be pretty easy I think?

Ref: pydata/pandas#12049

CC: @jreback @ogrisel

**Comment by jreback** [comment]
even better would be conda packages on the ``numpy`` channel ......

**Comment by ogrisel** [comment]
Uploading py27 wheels would be trivial, just a matter of changing a couple lines in travis.yml. adding support for conda is probably more work. I have no experience with conda build.

**Comment by njsmith** [comment]
Conda seems decidedly non-trivial given that conda has special-case strict rules it applies to numpy versioning. I suspect we'd need help from a conda core dev to figure this out. In the mean time a PR to enable the wheel upload would be welcome.

**Comment by jreback** [comment]
I got this 2 work with 3.5

I had to install use the following on Travis-CI:
``time sudo apt-get $APT_ARGS install libatlas-base-dev gfortran``

rather than just typically install via ``conda``
``time conda install -n pandas libgfortran openblas || exit 1``

see [here](https://travis-ci.org/jreback/pandas/jobs/102817809)

it was my understanding that numpy looks at run-time for these, but maybe I would need to set an env variable to have it look for ``openblas`` rather than the default of ``atlas``?

**Comment by ogrisel** [comment]
> In the mean time a PR to enable the wheel upload would be welcome.

I am on it. Currently testing it on my travis ogrisel/numpy account. If it works I will open the PR to numpy.

**Comment by ogrisel** [comment]
Should be ok. The wheels will upload as soon as #7033 gets merged.

**Comment by jreback** [comment]
@ogrisel gr8! thanks!

saves about 5 min! in the build/test time

**Comment by jakirkham** [comment]
What's the question regarding getting builds working with `conda`?

**Comment by jakirkham** [comment]
@njsmith, what's the question regarding getting builds working with `conda`?

**Comment by njsmith** [comment]
The general question is the usual "does someone want to do the work to make
this happen and what do they need to know"; if someone just showed up with
a working patch of course that'd be cool. The reason why I am nervous about
this being difficult though is that conda enforces that packages built
against numpy 1.x.y can only be installed if numpy 1.x.z is installed. This
requires some special magic metadata in the numpy package that AFAIK no
other conda package uses, and creates problems for testing against master
which has a new version number that no other packages are compiled against.
To make things worse there's no guarantee that 1.x pre-releases will be abi
compatible with 1.x final, so building other packages against master
snapshots is not risky. (And really we'd rather testing not enforce this
strict abi versioning, because it doesn't actually match our own rules for
numpy abi compatibility -- we'd like to test that stuff built against
1.(x-1) still works when run against 1.x.)

**Comment by jakirkham** [comment]
AFAIK there is no special metadata. `conda-build` looks for recipes with `numpy` in the name.

So, I work a bit with building conda packages and even wrote a numpy recipe to build with openblas. Nothing special was required and it was able to detect right away the numpy package needed to work with scipy and the like.

**Comment by jakirkham** [comment]
Are you wanting a recipe to be included with numpy?

**Comment by jakirkham** [comment]
Adding Linux and Mac support would be straightforward. The only question to think about here is how to include/build against a BLAS. Normally, I have a different recipe for the BLAS. So, that should probably be included.

One trick is Windows support is going through a transition. They have started tying Windows builds to a particular copy of the VC library. For the most part, it looks like they are just following the guidelines that Python provides as far as which version of VC to build with. Personally, I don't have a working Windows development environment so can't be much help there. The best person to talk to there would probably be @msarahan who seems to be instrumental for getting the improvements into `conda-build`.

**Comment by njsmith** [comment]
The question here was just about providing snapshot builds of master so that downstream projects can easily test against them. We currently provide wheels for this propose; @jreback would like conda packages. I'm not sure why, given that wheels I guess should work fine in this context? you'd have to ask him :-).

More generally if there were an easy way for us to provide conda builds of prerelease versions then that would be nice, because it would make it easier for end-users to test and find bugs before the real release. I'm not sure how to make this happen effectively though given the abi tracking stuff I mentioned; maybe just sticking to wheels for now would be better.

**Comment by jreback** [comment]
my request for conda packages is somewhat orthogonal this this one. I am going to use wheels on our Travis-CI testing.

But I think it would be great to provide conda builds if you can from master. (I would use those instead of wheels as its slightly easier).

**Comment by jakirkham** [comment]
Thanks for the additional information, @njsmith and @jreback .

The easiest thing to do for a start would be to skip the BLAS (if possible) and focus on Linux builds. This would require a recipe be added to `numpy`. This will be a very simple recipe. Extending it to Mac shouldn't be too difficult. Extending to Windows would require someone else with more experience to help.

As far as compilers go, `conda` has a copy of `gcc` for Mac and Linux. They also have a compatible copy of `libgcc`. I think it would be easiest to start with that. If that becomes problematic, we can explore other solutions.

I'd be happy to create a PR for this. Wouldn't take me long. :)

**Comment by jakirkham** [comment]
I added a PR ( https://github.com/numpy/numpy/pull/7036 ).

**Comment by mattip** [comment]
Fixed
