### ISSUE TITLE
Using single and array indexing simultaneously swaps axis

### ISSUE THREAD

**Issue by ivan-baldin** [numpy/numpy#7030]
Here's the problem in a single example.

    In [2]: x = rand(3, 5, 7)
    
    In [3]: x[0, :, [0,1]].shape
    Out[3]: (2, 5)

    In [4]: x[0][:, [0,1]].shape
    Out[4]: (5, 2)

    In [5]: x[0, :, :2].shape
    Out[5]: (5, 2)

I'm using version 1.10 with python 3.4.

**Comment by seberg** [comment]
Please check http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#combining-advanced-and-basic-indexing 
I admit it is not very easy to understand, but the examples do show that this is expected and supposed to happen. There are multiple advanced indices and they are transposed to the front when this happens. Just imagine replacing the scalars with with an array `x[[0], :, [0, 1]]`.
