### ISSUE TITLE
DOC: directly link to numpy functions in release notes?

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#7041]
Something like the following in our release notes could make it easier to users to find document for new or changed functions:

```
:py:func:`numpy.moveaxis`
```

Thoughts?

**Comment by njsmith** [comment]
Sounds like an easy win to me :-)

**Comment by rgommers** [comment]
the ``:py:func:`` isn't needed for that. example: http://docs.scipy.org/doc/scipy/reference/release.0.16.0.html

just using single backticks and including the release notes in the reference guide (which is anyway a good idea imho) will do the job.

**Comment by njsmith** [comment]
the meaning of single backticks IIRC is a sphinx configuration option and
scipy looks like it has a non-default setting? (I think the search keywords
here are "default role").

On Sun, Jan 17, 2016 at 2:43 AM, Ralf Gommers <notifications@github.com>
wrote:

> the :py:func: isn't needed for that. example:
> http://docs.scipy.org/doc/scipy/reference/release.0.16.0.html
>
> just using single backticks and including the release notes in the
> reference guide (which is anyway a good idea imho) will do the job.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/7041#issuecomment-172311294>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by rgommers** [comment]
That's the same as for numpy: ``default_role = "autolink"`` in ``doc/source/conf.py``.

It's good to avoid the ``:py:func``, because now one can simply email the release notes as announcement without having to remove markup.

**Comment by sameshl** [comment]
@rgommers I would like to work on it. 

> just using single backticks and including the release notes in the reference guide

I didn't quite understand what you mean by `including the release notes in the reference guide`? Can you elaborate a little.
Thanks!

**Comment by mattip** [comment]
Closing, we already implemented all the reccomendations here.
