### ISSUE TITLE
DOC: HowTo refers to non-existant version of numpydoc

### ISSUE THREAD

**Issue by par2** [numpy/numpy#7043]
The [documentation](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) refers to the Yields section in `numpydoc` 0.6.  However, the latest release is 0.5.  

Is this a typo?  Or is this addition refering to `numpydoc` master?

**Comment by seberg** [comment]
The latter, IIRC this was added recently, so it will be in the next numpydoc release which will be 0.6. Not sure about numpydoc release cycle, but maybe we could do a release sooner rather than later (there seems to be two small PRs open, which probably could use merging first).

**Comment by patricksjackson** [comment]
This issue is no longer relevant and should be closed.

**Comment by rgommers** [comment]
thanks, closing
