### ISSUE TITLE
BUG: Warning in comparison for some values

### ISSUE THREAD

**Issue by Etendard7** [numpy/numpy#7044]
Hi,

I got a warning in pandas and dwelled on it to find that the issue whas about numpy :
When comparing a numpy integer with an unicode string, result is logically false but I am getting a warning if the integer is > 383.

Exemple :
`np.int32(383) == u'some text' #ok`
`np.int64(383) == u'some text' #ok`
but:
`np.int32(384) == u'some text' #warning`
`np.int64(384) == u'some text' #warning`
And the warning is 
_UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal_

I am on a 64 bits Windows, python 2.7.11 and numpy 1.10.1.

**Comment by seberg** [comment]
The real ooops is this I think (for 384 the `decode` part happens to fail):
```
In [67]: bytes(buffer(np.int32([383]))).decode('utf8') == np.int32([383])
Out[67]: True
```
I am not sure this is is easy to fix. Numpy should only defer it to the unicode equality, which probably does this trick. We could work around it for unicode specifically maybe. Fortunately, python3 should be better with this. It might still find equalities with `bytes` object, but not with (unicode)-strings, I expect.

**Comment by bsipocz** [comment]
Since this is a python2 only issue, I suggest to close.

**Comment by rgommers** [comment]
thanks @bsipocz!
