### ISSUE TITLE
Any reason why we're keeping np.random.tomaxint?

### ISSUE THREAD

**Issue by gfyoung** [numpy/numpy#7050]
In light of what has occurred with random integer generation and the deprecation of ```random_integers```, ```tomaxint``` looks really out of place.  Not only is it generating on a closed interval, which we are trying to discourage, but IIUC, ```np.random.tomaxint(size=size)``` looks no different from ```np.random.randint(0, np.iinfo('l').max + 1, size=size)```.

I propose that we deprecate ```tomaxint``` in favor of the call to ```randint``` just like we did with ```random_integers```.  But perhaps there's a use case or reason that I'm not aware of since it does have its own helper function separate from ```randint```.  Thoughts?

**Comment by rkern** [comment]
"Open interval" or "closed interval" corresponds to the convention that users specify the set of integers on which to generate random numbers from. The set itself is neither closed nor open; it's just a bunch of integers. The user does not specify an interval here, so the deprecation of `random_integers()` is not relevant.

That said, this is not a particularly useful method, now that `randint()` is properly fixed, but I'd prefer to deprecate it only if it starts causing problems. Deprecating long-standing code always has a cost. You don't want to do it unless if doing so brings a tangible benefit.

**Comment by gfyoung** [comment]
From a maintenance perspective, I see what you mean.  Until then, I'll leave ```tomaxint``` as is.  Closing the issue for now, as we haven't seen any problems with that method.
