### ISSUE TITLE
DOC: Any reason to continue using `..note` vs `..deprecated`?

### ISSUE THREAD

**Issue by par2** [numpy/numpy#7059]
In the numpdoc guideline, I notice the [`.. note::` directive](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections) is used to mark deprecation warnings in docstrings.  However, Sphinx appears to have a [`.. deprecated::` directive](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-deprecated).  Should the current use be updated or is there are reason to keep `.. note::` as the standard?

**Comment by seberg** [comment]
Probably just habit, where ever it originally came from. Changing sounds good to me, pull requests very welcome!

**Comment by rgommers** [comment]
That is outdated, the current practice is to decorate a function with ``np.deprecate``. We should probably just change the doc to match reality.

**Comment by njsmith** [comment]
That said, np.deprecate possibly should use some sort of admonition
directive to make its message more visible...

On Tue, Jan 19, 2016 at 12:54 PM, Ralf Gommers <notifications@github.com>
wrote:

> That is outdated, the current practice is to decorate a function with
> np.deprecate. We should probably just change the doc to match reality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/7059#issuecomment-172983691>.
>



-- 
Nathaniel J. Smith -- https://vorpus.org <http://vorpus.org>

**Comment by rgommers** [comment]
that might be good. maybe ``.. deprecated::`` indeed, assuming that that works for Sphinx >=1.2.1 (I've never used it).

**Comment by sameshl** [comment]
@seberg Is this still a problem. I would like to work on it. As I understand I will have to change all instances of `..note::` directive to `..deprecated::` in the numpy docs?

**Comment by mattip** [comment]
Correct. Are there many left? They should now be `.. deprecated:: <version>`

**Comment by sameshl** [comment]
I checked and found very 2 instances but I am not completely sure if I need to change it for the first one, so you could help me out. They are:
1) https://github.com/numpy/numpy/blob/88021a568cc13ef7325a52e22573f027a2be9df7/numpy/_pytesttester.py#L90-L91
2) https://github.com/numpy/numpy/blob/88021a568cc13ef7325a52e22573f027a2be9df7/numpy/core/fromnumeric.py#L3583-L3586

**Comment by mattip** [comment]
The first one is not a deprecation. The second one (`np.rank`) is. In fact perhaps the correct thing to do with this is to either remove the function entirely (it has been deprecated since v1.9 five years ago) or give up the deprecation and remove the deprecation note and warning.

**Comment by sameshl** [comment]
I think as `np.rank` has been deprecated for more than 5 years now it would make more sense to remove it entirely. I could do that.

**Comment by mattip** [comment]
Closing. There are no more `.. note` directives that should be `.. deprecate`. Please reopen (or just issue a PR) if I am mistaken
