### ISSUE TITLE
Value of bitwise_and.identity does not make sense

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#7060]
The value of `bitwise_and.identity` is `1`. This makes `bitwise_and.reduce()` basically useless for numbers other than zeros and ones. The value can not be changed or a different one passed in to `reduce()`. The correct value is `-1` or `0xFFF...` or something similar that will not change the bits of the initial value of the thing being reduced. A related question on StackOverflow can be found here: http://stackoverflow.com/questions/21050875/numpy-bitwise-and-reduce-behaving-unexpectedly.

**Comment by seberg** [comment]
On first sight, changing it to -1 should probably work correctly for all types and continue to work for all cases where it used to make sense. So I think we should do it, do you want to create a PR?

**Comment by madphysicist** [comment]
Will do shortly.

**Comment by madphysicist** [comment]
I was looking at the code and while `-1` is technically correct on two's complement systems, it is incorrect on one's complement machines. I think that a more appropriate value would actually be `None`. The `PyArray_InitializeReduceResult` routine in `numpy/core/src/umath/reduction.c` will actually use the first element in the array, which is perfect for the reduction in this case.

**Comment by seberg** [comment]
Yes, I was not quite sure about non ones complement (actually, I have no clue if they exist in practice or not :)). The other issue is the `object` dtype. `-1` as an integer seems to work reasonably there though, though of course it could be wrong, but that is similar problem in other cases as well.

But you are right, when in doubt refuse the temptation to guess. `None` is likely safer. The difference is what happens with empty arrays, they cannot be handled without an identiy and an error will be raised. There are some interesting points, such as `np.subtract` has no idenity, and if it was 0 it would return a different value. But I guess subtract is pretty special.

**Comment by madphysicist** [comment]
`bitwise_and` is pretty sensitive, I dunno about special. It will not work for non-integer arrays anyway, so I figure that empty arrays can throw an exception all they want. It actually makes sense that way. I created https://github.com/numpy/numpy/pull/7061 with `ReorderableNone` as the identity.

**Comment by madphysicist** [comment]
Has there been any effort to add an optional identity parameter to `ufunc.reduce()`? The default could be to use the identity attribute of the `ufunc`, preserving backwards compatibility. That would make `subtract`, `bitwise_and` and probably others easier to work with in many situations.

**Comment by seberg** [comment]
However, just changing to no identiy can break peoples code, so I am a bit hesitant. It could be nice to make dtype specific identities, but I doubt that is currently easy. My guess is the only safe place to use it can just as well (and probably is already) use a logical_and.reduce, so likely we are fine.

@madphysicist, I have personally thought that it oculd make sense to have identity as a parameter there, but I don't think we ever discussed it seriously.

**Comment by njsmith** [comment]
Setting this to `None` will definitely break code -- *lots* of code uses `&` on boolean arrays, and that's `bitwise_and`. There's no comparable shorthand for `logical_and`.

I am 100% unworried about ones-complement machines. There are none that numpy cares about (it's not clear whether they even still exist as physical hardware, even in niche applications), and I'm 99% sure we already assume twos-complement all over the place.

**Comment by madphysicist** [comment]
Fair enough. However, won't setting -1 break just as much code since the current value is one?

**Comment by seberg** [comment]
@njsmith no, code uses the & operator, that has nothing to do with the identity since it is not a reduction operation. And very little code should do `np.bitwise_and.reduce(bool_arr)` and not `np.all(bool_ar)` or `np.logical_and.reduce(bool_ar)` or one of those alternatives. Though of course some code may do it.

What might need some thinking is whether or not it is nonsense for object arrays, but basically that just gets better with fixing it to -1. I would even prefer some destiction between types + an identity kwarg if someone really needs it, but....
So my guess is also that we gain by putting it to -1, while disabling might cause some distress. And the possible awkwardness of -1 should be almost non-existing.

**Comment by madphysicist** [comment]
@seberg I agree that -1 is certainly much better than the current value of 1. I am not sure that disabling it will cause any significant distress since the current defective value has not been noticed/reported until now. The number of people passing empty arrays to `bitwise_and.reduce()` must be miniscule. If you think that -1 is still optimal, I will rescind my pull request, but I am not sure where to set the correct value.

**Comment by madphysicist** [comment]
This `numba` post https://github.com/numba/numba/issues/829#issuecomment-69209598 is part of what convinced me to set the value to `ReorderableNone` by the way.

**Comment by njsmith** [comment]
@seberg: Oh, you're right of course :-)

I guess that possibly we could get away with removing the identity altogether then, but I am still a bit wary of unforeseen breakage, given that there actually is a correct value we could in principle switch to instead. (At least for non-object arrays, I mean; for object arrays I agree that no-identity is the right thing.) It's jsut unfortunate that fixing it properly is difficult given how ufuncs are currently put together :-/

This would need a post on the mailing list + a deprecation cycle I think.
