### ISSUE TITLE
np.delete does not raise indexError when out-of-bounds index is in np array

### ISSUE THREAD

**Issue by markramakers** [numpy/numpy#7069]
> np.delete(np.array([0, 2, 4, 5, 6, 7, 8, 9]), 9)

this gives an index-error, as it should (index 9 is out of bounds)

while 

> np.delete(np.arange(0,5), np.array([9]))

and 

> np.delete(np.arange(0,5), (9,))

give:

> array([0, 1, 2, 3, 4])

**Comment by seberg** [comment]
Note that a DeprecationWarning is issued for these (though you don't necessary see it probably since 1.8). We could likely go ahead with the deprecation at least in master.

**Comment by seberg** [comment]
Actually, I will close this, as it is tracked in gh-11521 (just like many there, they would be pretty simple things to do for first contributions).
