### ISSUE TITLE
np.sctypes is missing bytes under Python 3

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7071]
... but it contains `str` twice.

Probably just a matter of fixing `numerictypes.py` line 437:
```
sctypes = {'int': [],
           'uint':[],
           'float':[],
           'complex':[],
           'others':[bool, object, str, unicode, void]}
```
Replace unicode -> str, str -> bytes (under Py3).

**Comment by seberg** [comment]
Closed by gh-7436 (probably I removed the existing tag in the commit, and you probably had there)
