### ISSUE TITLE
numpy.allclose parameter types do not allow float

### ISSUE THREAD

**Issue by marcotama** [numpy/numpy#7079]
Not sure if this bug is proper to be posted here or in the typing module... If this is the wrong place, please, point me to the right one.

Current type hints for parameters `a` and `b` of `np.allclose` are `Union[ndarray, Iterable]`, but should be changed to `Union[ndarray, Iterable, float]` since the function supports this type of usage.

`np.isclose` suffers from a similar issue: even though is quite rare for that function to be used with two floats, it would be more precise to mark the type of `a` and `b` as `Union[ndarray, Iterable, float]`.

**Comment by mattip** [comment]
Typing is not internal to NumPy. Closing. Please reopen if there is something to be done inside NumPy.
