### ISSUE TITLE
Clarify docstring of real_if_close

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7107]
Currently, it says

```
Returns:    

out : ndarray

    If a is real, the type of a is used for the output. If a has complex elements, the returned type is float.
```

It's a bit more complicated: at least on 64-bit builds, assuming the input only has close-to-real elements, then `complex64` or `complex128` inputs give a `float64` output, whereas `complex256` inputs give a `float128` output.  Or the behavior could be changed to return an output of the same size as the input's real part (so `float32` for `complex64` input).

**Comment by seberg** [comment]
@anntzer are you sure that your observation is correct? I cannot reproduce it, and frankly I cannot see any reason in the code for why it could possibly give the wrong result.

**Comment by anntzer** [comment]
Indeed, this is not the case currently.  I don't know if something changed since 3 years ago or I made some mistake in my original observation, but in any case this can be closed now.

**Comment by seberg** [comment]
Well, the doc strings are a bit fuzzy, you might also have just meant that ;), but it is not bad enough to keep the issue open I guess.
