### ISSUE TITLE
Allow Scipy Source Builds on Cygwin64

### ISSUE THREAD

**Issue by gfyoung** [numpy/numpy#7111]
When ```scipy/setup.py``` tries building the ```fftpack``` and ```dfftpack``` files in ```scipy```, it automatically builds them into the x86 architecture, making them incompatible with ```Cygwin64```. Related to #7104 .  The reason why the issue is here is due to comments from @rgommers in ```scipy``` issue <a href="https://github.com/scipy/scipy/issues/5759">#5759</a>.

On a side note, ```numpy``` is actually a lot nicer than it may have been beforehand when it comes to source builds.  ```Cygwin``` (either architecture) or ```MinGW``` (no ```Cygwin```) will work in building that library with no problems based on personal experience.

**Comment by argriffing** [comment]
Is this a numpy or scipy issue?

**Comment by gfyoung** [comment]
Did you read the ```scipy``` issue I mentioned?  That should clarify why it is here.

**Comment by argriffing** [comment]
Sorry, I should have read that first. You can ignore my comments in this thread :)

**Comment by gfyoung** [comment]
No worries.  It happens to the best of the us. :smile:

**Comment by gfyoung** [comment]
I've been running into this problem where if I run ```import numpy as np```, Cygwin just core-dumps after I exit.  This problem with core-dumping does not seem new either and appears to be reproducible in other contexts like this <a href="https://cygwin.com/ml/cygwin/2014-03/msg00102.html">one</a>.  Wondering whether or not it may now be worthwhile to build Cygwin64 support given this issue.

**Comment by gfyoung** [comment]
Sometimes you just need to put it aside and try again with fresh eyes and apparently, a fresh install.  Managed to build both libraries (albeit with some test failures) but that is not the original issue.  Closing

**Comment by gfyoung** [comment]
Sometimes you just need to put it aside and try again with fresh eyes and apparently, a fresh install.  Managed to build both libraries (albeit with some test failures) but that is not the original issue.  Closing.
