### ISSUE TITLE
np.delete changes order to C

### ISSUE THREAD

**Issue by wsfreund** [numpy/numpy#7113]
Hello,

there is probably a bug on np.delete as it changes data order from fortran to C in the following case:

```
In [1]: import numpy as np

In [2]: k=np.arange(10).reshape(2,5,order='F')

In [6]: m=np.delete(k,slice(60,None),axis=1)

In [7]: m.flags
Out[7]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [24]: np.__version__
Out[24]: '1.10.1'
```

That is, when you call it and it does not delete any index. What's funny, though, is that it keeps data representation the same. Other cases seem to maintain data order.

Thanks,
Werner.

**Comment by seberg** [comment]
It seems the empty slice is an explicit special case, which is fine, but it does not have the `arrorder` logic the other code paths have:
```
        new = empty(newshape, arr.dtype, arrorder)
```
The empty slice code path should probably use `arrorder` for the copy, since all the others seem to do it. If you have some time to have a look, this is some pure python code in numpy/lib/function_base.py, it would be much appreciated.

**Comment by maniteja123** [comment]
Hi, I am not sure whether this is the reason, but looks like [this](https://github.com/numpy/numpy/blob/master/numpy/lib/function_base.py#L4005) call of ``ndarray.copy`` is the reason for the change of the order

```
>>> k.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>>np.copy(k).flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>>k.copy().flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

It seems that the documentation of the ``ndarray.copy`` mentions the change of order to C

**Comment by gfyoung** [comment]
@maniteja123 : You are absolutely correct.  See my PR linked to this issue.
