### ISSUE TITLE
C-API Error

### ISSUE THREAD

**Issue by jayendra13** [numpy/numpy#7120]
I am trying to create, numpy array with the help of C-API, but getting the segmentation fault, what is the problem here?
```
#include "Python.h"                                                                                                                       
#include "numpy/arrayobject.h"
#include "assert.h"

int main()
 {
     int xdims[1] = {4};
     double x_data[4] = {1.2,2.3,3.4,4.5};
     PyObject *X;
 
     Py_Initialize();
 
     X = PyArray_SimpleNewFromData(1, xdims, NPY_DOUBLE, x_data);
     Py_Finalize();
 
     exit(0);
 }

//Compiling by gcc 
// gcc -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include pytest.c -lpython2.7
```
getting the segmentation fault when trying to run it.

**Comment by rkern** [comment]
You must call `import_array()` before you call any numpy API functions.

http://docs.scipy.org/doc/numpy-1.10.1/reference/c-api.array.html#importing-the-api

**Comment by jayendra13** [comment]
Great!! Thanks @rkern , I had skipped that part from documentations.
Much thanks.
