### ISSUE TITLE
Setuptools sdist doesn't include all the files in the extension sources list.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#7127]
The problem seems to be the inclusion of a mix of `*.c`, `*.h` and `*.c.src` files in `multiarray_src`, the list that only include `*.*.src` files seem to do better.

**Comment by rgommers** [comment]
It's not what's in ``MANIFEST.in``, it's that ``setuptools`` executes a part of the build that ``distutils`` doesn't. 

For v1.10.4:

    ...
    running sdist
    running check
    warning: check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too

    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    writing manifest file 'MANIFEST'
    creating numpy-1.10.4
    ...

For master:

    ...
    running sdist
    running egg_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.macosx-10.9-x86_64-2.7
    creating build/src.macosx-10.9-x86_64-2.7/numpy
    creating build/src.macosx-10.9-x86_64-2.7/numpy/distutils
    building library "npymath" sources
    customize Gnu95FCompiler
    Found executable /usr/local/bin/gfortran
    customize Gnu95FCompiler
    customize Gnu95FCompiler using config
    C compiler: clang -fno-strict-aliasing -fno-common -dynamic
    -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3
    -Wall -Wstrict-prototypes
    ...

**Comment by rgommers** [comment]
The issue is caused by (a) ``setuptools`` running ``egg_info``, and (b) ``numpy.distutils`` running ``build_src`` for ``egg_info``: https://github.com/numpy/numpy/blob/master/numpy/distutils/command/egg_info.py

There are other issues with the ``setuptools`` version of ``sdist``, for example: http://stackoverflow.com/questions/3779915/why-does-python-setup-py-sdist-create-unwanted-project-egg-info-in-project-r. It simply tries to be too smart for its own good again. I think we anyway don't want a ``numpy.egg_info`` dir in our source releases, so probably the way to go here is to make sure that ``sdist`` doesn't invoke ``egg_info`` at all. Or simply go back to not using ``setuptools`` at all for ``sdist`` (the PEP-440 issue that forced us to use ``setuptools`` doesn't play a role here, so it would be fine).

**Comment by rgommers** [comment]
Thinking about it some more, just going back to plain ``distutils`` still doesn't solve this issue for other projects that rely on ``numpy.distutils``. I just checked ``scikit-learn`` and ``statsmodels``, and both avoid using ``setuptools`` for ``sdist`` it looks like. Conclusion: we should go back to plain ``distutils`` here, as well as make ``numpy.distutils`` at least warn within ``egg_info`` that something is likely going wrong here.

**Comment by rgommers** [comment]
Calling ``egg_info`` and putting the result in the tarball is also completely wrong conceptually - the output of ``egg_info`` can depend on the OS, available libs, etc. on the build system. And build system is not the system on which the ``sdist`` is created.

**Comment by rgommers** [comment]
@charris sent you patches for this issue (can't push to github this week)

**Comment by charris** [comment]
Got them, thanks. Enjoy your time off.

**Comment by charris** [comment]
See #7131.

**Comment by Ivoz** [comment]
@jaraco is there a nice way to turn off setuptools' automatic collection of VCS tracked files?

**Comment by jaraco** [comment]
@ivoz I believe the VCS discovery is dependent on the finder library being present, so removing that library may be one way. Otherwise, I'm not aware of any.

**Comment by rgommers** [comment]
Shouldn't there be such a way, and is there a setuptools issue for that already? Including files or not based on the state of your Python library is very poor behavior.

Also, running ``egg_info`` seems a bit counterproductive. It leaves you with duplicate ``PKG_INFO`` files in the tarball, and a ``SOURCES`` file that's almost by definition incorrect so better left out.

**Comment by jaraco** [comment]
> Shouldn't there be such a way, and is there a setuptools issue for that already?

I'm not aware of any, but I haven't done a search.
