### ISSUE TITLE
meshgrid not accepting indexing argument

### ISSUE THREAD

**Issue by jjacob7734** [numpy/numpy#7130]
In NumPy ver. 1.11.0.dev0, the meshgrid function does not accept the indexing argument:

gc00, gc11 = np.meshgrid(gc0, gc1, indexing="ij")
TypeError: meshgrid() got an unexpected keyword argument 'indexing'

This seems to work in NumPy ver. 1.8.0, but the docs indicate indexing is still a supported argument.  Can anybody offer advice? 

Thank you.

Joe

**Comment by rgommers** [comment]
Works fine for me, and is still supported. Code at https://github.com/numpy/numpy/blob/master/numpy/lib/function_base.py#L3873 looks fine, you shouldn't be getting to the ``TypeError``. 

Please post a completely reproducible example and the full traceback.

**Comment by jjacob7734** [comment]
Thanks for checking and sorry it took me so long to get back to you.  I discovered my problem only happened when the meshgrid function is called in a unit test function triggered by nosetests and seems to only happen for a specific version of Nose and NumPy.   I am now using Anaconda distribution and the problem went away for me.

For Python ver 2.7.10, NumPy ver 1.11.0.dev0+772c80b, and nosetests ver 1.3.4, on my Mac OS X (10.9.5) and Linux systems, the test code below gives me the following error when I run it through nosetests, but runs fine in the Python interpreter:
TypeError: meshgrid() got an unexpected keyword argument 'indexing'

--- code snippet ---
import numpy as np
def test():
    x1 = np.array([1.,2.,3.])
    x2 = np.array([4.,5.,6.])
    xmat = np.meshgrid(x1,x2,indexing='ij')
--------------------------

For me the problem is solved by using Anaconda distribution.  With Anaconda ver 2.5.0 (x86_64),  I get Python ver 2.7.11, Numpy ver 1.10.4, and nosetests ver 1.3.7.  All are slightly different versions than I tested earlier.  It appears to be some specific version of Python, Numpy, or Nose that causes the problem.

Thanks again.

**Comment by jjacob7734** [comment]
Sorry about the code formatting above.  You can pull it from here:

https://github.com/jjacob7734/meshgrid_test.git

Thanks again.

**Comment by seberg** [comment]
Sounds like this must have been issues with using a very old numpy version, or some very temporary issue (with the feature missing in older versions), so I will close. The original poster had solved the issue by upgrading in any case and it is very old.
