### ISSUE TITLE
Automatically update development version of numpy docs 

### ISSUE THREAD

**Issue by amcameron** [numpy/numpy#7136]
The exponents in the denominators of the Freedman–Diaconis and Scott estimators are shown incorrectly in the typeset maths on this page:
http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.histogram.html

The offending lines of source code were corrected in commit 41de3c2d8c84dbfa406ccb77dd67d55f555bee8a in December, and incorporated on the maintenance/1.11.x branch, but the generated documentation doesn't yet reflect this, having been last updated in October.

**Comment by rgommers** [comment]
The html docs should be built for merge commits and pushed to docs.scipy.org (or a repo linked to there). Scipy has this set up already, so it's a matter of implementing the same thing for numpy.

I'll change the title of this issue to reflect the todo here.

**Comment by rgommers** [comment]
For reference, the scipy machinery is here: https://github.com/scipy/scipy/blob/master/.travis.yml#L140

**Comment by eric-wieser** [comment]
@stefanv: Can this be closed?

**Comment by mattip** [comment]
Closing.
