### ISSUE TITLE
parallel build fails sometimes with python3.5

### ISSUE THREAD

**Issue by jlec** [numpy/numpy#7139]
Using the new parallel build option fails for numpy and scipy-0.17.0 sometimes. The issue is not reproducable always.

Here are our downstream bugreports

[Gentoo bug 573222](https://bugs.gentoo.org/show_bug.cgi?id=573222)
[Gentoo bug 573148](https://bugs.gentoo.org/show_bug.cgi?id=573148)

Could this be that there is a clash with the new [parallel option](https://python.readthedocs.org/en/latest/whatsnew/3.5.html#distutils) in distutils of python 3.5?

**Comment by rgommers** [comment]
@juliantaylor did test this and adapted the naming of the numpy.distutils option (``--parallel/j``) to the ``distutils`` one - see comment in https://bugs.python.org/issue5309.

**Comment by rgommers** [comment]
Indeed looks like a conflict between the two though.

**Comment by juliantaylor** [comment]
I don't think it is really a conflict, but numpys build is not compatible with python3.5 approach of paralellizing.
numpy paralellizes within the compilation of files within one extension as its extensions contain main files, while python3.5 paralellizes the compilation of multiple extensions.
The latter does not actually work in numpy as we reuse the python_xerbla.c file in two extensions, lapack_lite and _umath_linalg. distutils builds both into the same place so when those two extensions are built in parallel one may clobber the result of the other.

**Comment by rgommers** [comment]
Then using the same names is maybe a bit unfortunate. Since we're advertising ``--parellel`` in a couple of places in the docs, we should fix this. It should be possible to pass the options between the various ``build`` commands in ``numpy.distutils`` that need, but make sure that ``distutils`` doesn't see anything of that.
