### ISSUE TITLE
astropy test failure with 0.11 prerelease

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#7161]
https://github.com/astropy/astropy/issues/4548

Possibly just a rounding issue and a too-severe test, but probably we should figure it out one way or another.

**Comment by njsmith** [comment]
For the two TestPhysicsSphericalRepresentation errors, git bisect says: "34c236939116c5ad75b79b1ccfbecb9c9157a165 is the first bad commit"

That's @charris's changes to divmod rounding. I guess this is probably OK and right solution is to fix the test?

**Comment by njsmith** [comment]
That's also the key commit for the `test_longitude` error. I'm not as sure what's going on with that, because it seems to involve a type mismatch... hopefully @mhvk or someone will take a look.

**Comment by charris** [comment]
The type error might be because scalar math remainder is now done using c operators instead of calling the ufunc fmod. This could be a problem with other scalar functions that don't use ufuncs...

**Comment by njsmith** [comment]
I just tested using numpy 1.9.3, and the type behavior is the same there, so I think that's a red herring, and it's just some rounding issues.

**Comment by njsmith** [comment]
Going to close this as a 1.11 blocker, unless astropy devs speak up and say otherwise.
