### ISSUE TITLE
binary_repr with large negative inputs

### ISSUE THREAD

**Issue by lorenzMuller** [numpy/numpy#7168]
binary_repr returns an error when a negative number that cannot be represented at the requested width is provided as input. When -2**width is input the output is erroneously zeros. 

When inputting positive numbers that cannot be represented the output is the largest representable number; the negative analogue would be a sensible behaviour.

Example:
`
import numpy as np

np.binary_repr(-8, width=3)
np.binary_repr(-9, width=3)
`
my numpy version is 1.8.2

**Comment by gfyoung** [comment]
While your version of `numpy` is a little out of date, I can replicate that issue in `1.10.4`.

**Comment by gfyoung** [comment]
Actually, in `1.10.4`, `np.binary_repr` can properly represent `-1`, though admittedly the representations of other negative numbers is a little buggy.
