### ISSUE TITLE
np.float64 multiplied by a string gives empty string, but other float dtypes raise error

### ISSUE THREAD

**Issue by robintw** [numpy/numpy#7169]
Multiplying a `np.float64`, `np.float32` or `np.float16` by a string gives an empty string, but doing the same with a `np.float` or a `np.float128` raises an error:

``` python
Python 3.4.4 |Anaconda 2.3.0 (x86_64)| (default, Jan  9 2016, 17:30:09) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.float64(0.5) * 'hello'
''
>>> np.float16(0.5) * 'hello'
''
>>> np.float32(0.5) * 'hello'
''
>>> np.float128(0.5) * 'hello'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't multiply sequence by non-int of type 'numpy.float128'
>>> np.float(0.5) * 'hello'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't multiply sequence by non-int of type 'float'
```

I would expect these to all give the same result - and, personally, I would expect that result to be raising an exception.

(For context: I was bitten by this when I had a nasty bug in some of my own code. The bug was - of course - entirely my own fault, but a `np.float64` not raising an exception when multiplied by a string made the bug quite hard to track down)

**Comment by robintw** [comment]
Duplicate of https://github.com/numpy/numpy/issues/5919

(I searched the issues before I submitted, but couldn't seem to find that one).

**Comment by seberg** [comment]
@robintw actually, please go ahead if you have the time. There probably is no issue, IIRC it was a while since that DeprecationWarning is in place.

**Comment by robintw** [comment]
Could you point me to the file I'd need to edit? (I had a bit of a browse around the source, but it's fairly large and I wasn't quite sure where to look).

**Comment by seberg** [comment]
Hmmm, it is in scalartypes.c.src, look for "PySequence_Repeat". But the deprecation warning is actually just the general integer deprecation warning (numpy refuses to interpret 3.5 or even 3.0 as an integer in the future).
Frankly, I am actually not sure the code is quite correct if you set the warning to raise, it might be that it should be returning NotImplemented, but raises an error instead.

If you see a nice way, I would be fine with speeding up the deprecation for specifically this case. Maybe it is time to think about the general one in 1.12, but that is quite a big deal that might need some care.

**Comment by seberg** [comment]
To be clear, the deprecation warning should be caused by the `repeat = PyArray_PyIntAsIntp(m1);` calls.

**Comment by robintw** [comment]
I've had a brief look at that, and to be honest it's beyond me - my C isn't as good as it used to be, and I haven't contributed to any C projects before.

Sorry, but I think I'll have to leave this for someone else to do

**Comment by seberg** [comment]
Thanks for taking a look. Actually at the moment it is not unlikely that 1.11 will have the deprecation finished. The error will be:
```
In [2]: np.float64(3.5) * [1]
TypeError: 'numpy.float64' object cannot be interpreted as an index

In [3]: 3.5 * [1]
TypeError: can't multiply sequence by non-int of type 'float'
```
which seems reasonable, but could probably be better, probably by asking the list to handle the multiplication on fail.

**Comment by robintw** [comment]
Will this fix apply for multiplication by a string as well as a list? (I see the error refers to an index). Something like:

`np.float64(3.5) * 'test'`

**Comment by seberg** [comment]
Yes, it will give the same error. "index" refers to the unfortunate naming that pythons `operator.index` (mapping to `blah.__index__()`). It basically means "not an integer that could in principle be used as an index" (which really means not an integer, with the possible exception of very big longs).

**Comment by seberg** [comment]
These issues have been fixed. Multiplying a string by python floats always raises nowadays.
