### ISSUE TITLE
use openlibm

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#7173]
Numpy has [hacks](https://github.com/numpy/numpy/blob/master/numpy/core/src/npymath/npy_math.c.src) to work around bad/missing/old platform math library implementations. It has been mentioned [a](https://github.com/numpy/numpy/pull/6976) [few](https://github.com/numpy/numpy/issues/6081) [times](https://github.com/numpy/numpy/issues/6712) that the compatibly-licensed [openlibm](http://julialang.org/openlibm/) could be used instead, so I'm opening a separate github issue for that idea.

**Comment by argriffing** [comment]
see also https://mail.scipy.org/pipermail/numpy-discussion/2016-February/074856.html

**Comment by mattip** [comment]
I think we can close this. Even [musl](https://wiki.musl-libc.org/mathematical-library.html) has enough C99 math that precludes the need for openlibm

**Comment by charris** [comment]
Looks like this problem will solve itself over time.
