### ISSUE TITLE
numpy/core/src/npymath/npy_math_complex.c.src: incorrect bracketing of #ifndef HAVE_CEXP@C@

### ISSUE THREAD

**Issue by blueness** [numpy/numpy#7182]
Commit c15f7747c78e3e8b492ac4b1ef298b51bbae428f did a bunch of cleanups of compiler warnings.  One cleanup involved moving `#ifndef HAVE_CEXP@C@ ... #endif` in numpy/core/src/npymath/npy_math_complex.c.src to include the definition of the function `_npy_scaled_cexp@c@()`.   If `HAVE_CEXP@C@` is not defined, then there is no problem, however if it is defined, then the definition of `_npy_scaled_cexp@c@()` is hidden.  This causes a compiler error later in that file when calls like `z = _npy_scaled_cexp@c@(absx, y, -1);` are made in `npy_ccosh@c@()` and friends.  You can "fix" this with a patch like

```
--- a/numpy/core/src/npymath/npy_math_complex.c.src
+++ b/numpy/core/src/npymath/npy_math_complex.c.src
@@ -184,8 +184,6 @@ npy_carg@c@(@ctype@ z)
 #define SCALED_CEXP_LOWERL 11357.216553474703895L
 #define SCALED_CEXP_UPPERL 22756.021937783004509L

-#ifndef HAVE_CEXP@C@
-
 static
 @ctype@
 _npy_scaled_cexp@c@(@type@ x, @type@ y, npy_int expt)
@@ -212,6 +210,7 @@ _npy_scaled_cexp@c@(@type@ x, @type@ y, npy_int expt)
                          npy_ldexp@c@(mant * mantsin, expt + exsin));
 }

+#ifndef HAVE_CEXP@C@
 @ctype@
 npy_cexp@c@(@ctype@ z)
 {
```

but I'm not sure that's what you want.  If you want the definition of `_npy_scaled_cexp@c@()` hidden if `HAVE_CEXP@C@` is not defined, then you have to do something below  in `npy_ccosh@c@()` and friends where you make calls to it.

**Comment by seberg** [comment]
Seems long ago fixed in 05dd27e2ec481dfa923d4cd2f149c3da82f0a9e8.
