### ISSUE TITLE
linalg.solve breaks at 30x30

### ISSUE THREAD

**Issue by paintingpeter** [numpy/numpy#7186]
Subsets of a 30x30 matrix along with a subset of 30x1 matrix is fine (ie 10x10, 20x20, 29x29 and it doesn't matter whether its from 0:29 or from 1:30.  But as soon as I submit the 30x30 it creates a scientific notated number and all 30 entries are the same in the single column 'vector'.

[30x30Test.xlsx](https://github.com/numpy/numpy/files/118030/30x30Test.xlsx)
[btest.xlsx](https://github.com/numpy/numpy/files/118031/btest.xlsx)

**Comment by njsmith** [comment]
Can you provide some sample python code to demonstrate what you mean?

**Comment by pv** [comment]
The matrix is singular.
