### ISSUE TITLE
Document ufunc kwargs in docstrings

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7190]
Currently, `np.multiply?` (in IPython) only gives

```
multiply(x1, x2[, out])
```

although there are a bunch of other keyword arguments mentioned in the docs (http://docs.scipy.org/doc/numpy/reference/ufuncs.html#optional-keyword-arguments) (actually, it isn't clear from the docs whether they are keyword-or-positional or keyword-only).
Some, such as `where`, may well be generally useful; documenting `casting` may also help with those who got bitten by the switch to safe casting mode.

Also a typo in the page for ufuncs:

> The optional output arguments can be used to help you save memory for large calculations. If your arrays are large, complicated expressions can take longer than absolutely necessary due to the creation and (later) destruction of temporary calculation spaces. For example, the expression G = a \* b + c is equivalent to t1 = A \* B; G = T1 + C; del t1. It will be more quickly executed as G = A \* B; add(G, C, G) which is the same as G = A \* B; G += C.

(upper/lowercasing of variables is not consistent.)

**Comment by njsmith** [comment]
This would be great, yeah...

On Thu, Feb 4, 2016 at 7:09 PM, Antony Lee <notifications@github.com> wrote:

> Currently, npmultiply? (in IPython) only gives
>
> multiply(x1, x2[, out])
>
> although there are a bunch of other keyword arguments mentioned in the
> docs (
> http://docsscipyorg/doc/numpy/reference/ufuncshtml#optional-keyword-arguments)
> (actually, it isn't clear from the docs whether they are
> keyword-or-positional or keyword-only)
> Some, such as where, may well be generally useful; documenting casting
> may also help with those who got bitten by the switch to safe casting mode
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/7190>.
>



-- 
Nathaniel J. Smith -- https://vorpus.org <http://vorpus.org>

**Comment by eric-wieser** [comment]
This is fixed in #9026. I haven't touched the typos though, so you might want to make a PR for that
