### ISSUE TITLE
Fortran compilation under Windows 7 64bit

### ISSUE THREAD

**Issue by kolas001** [numpy/numpy#7192]
Hi,
Following this instruction (found in this [post] (http://scientificcomputingco.blogspot.fr/2013/02/f2py-on-64bit-windows-python27.html) ):
replace  line 337: ```raise NotImplementedError("Only MS compiler supported with gfortran on win64")``` by ```pass``` in the file numpy/distutils/fcompiler/gnu.py, I was able to compile my own fortran module using mingw under Anaconda distribution.
Since fortran compilation seems to be working under Win 7 64bits, is it possible to remove the ```NotImplementedError``` in gnu.py in future numpy release ?

**Comment by insertinterestingnamehere** [comment]
This was already fixed in https://github.com/numpy/numpy/commit/acd873633a9c7017571834ca9d266ed5756d73ed and should be available if you are using numpy 1.10 (possibly 1.9, I don't remember for sure).

**Comment by njsmith** [comment]
Thanks Ian
