### ISSUE TITLE
pyasdf test failure with 1.11.0b2

### ISSUE THREAD

**Issue by olebole** [numpy/numpy#7200]
I found another potential regression: spacetelescope/pyasdf#189
I must however say that I don't understand the error message here:
```
self = <pyasdf.generic_io.InputStream object at 0x7f4b413b5710>, size = 80

    def read_into_array(self, size):
        try:
            # See if Numpy can handle this as a real file first...
>           return np.fromfile(self._fd, np.uint8, size)
E           SystemError: error return without exception set

pyasdf/generic_io.py:870: SystemError
```

**Comment by njsmith** [comment]
The way you raise Python exceptions from C code is that (a) you call `PyErr_SetException`, and then (b) you return a special sentinel value like -1. The error means that some code path in `fromfile` is returning the special sentinel value, but forgot to call `PyErr_SetException`. So, definitely a bug -- that's just an incorrect usage of the Python C API.

So, who touched `fromfile` last? :-)

**Comment by juliantaylor** [comment]
5225e4c2007963fa2cfd5d9faf5d3ca010621310
not sure why that got added, PyFile_AsFile does not raise an error but granted it is not documented
