### ISSUE TITLE
Python 3.5, Windows7/10 x64, OpenBLAS and MKL with NumPy and SciPy, how to upload package?  Compile help SciPy.

### ISSUE THREAD

**Issue by mrslezak** [numpy/numpy#7216]
I have NumPy 1.10.4 compiled with both OpenBLAS (Int32 Windows 64, v0.2.15 precompiled binary) and MKL (using a community license on MKL, i.e. free distribution). But... I can't compile SciPy - seems a small portion looks for the gfortran compiler "fortan compiler not found" if anyone has an idea how to fix this issue. I'm using ifort.exe (Intel Parallel Studio XE 2015) since Ananconda supports these builds as direct plug-ins. Compiled for Python 3.5 with Microsoft Visual Studio Community 2015 if anyone can help me figure out how to package this for distribution.... then I will upload to github or Anaconda's website. Appreciate it.

**Comment by jakirkham** [comment]
Should probably move this issue to SciPy's [issue tracker]( https://github.com/scipy/scipy/issues ).

**Comment by rgommers** [comment]
Well, compiler not found is either a user error or it's a bug in ``numpy.distutils``, so keeping the discussion here is fine for now I think.

@mrslezak can you please provide the exact build command you used, and put the build log in a gist and give a link here?

**Comment by mrslezak** [comment]
Ah I got it... The Intel Parallel Studio 2015 XE prompt path statement was
too long.  Opened an admin CMD window and added the path to ifort.exe and
it compiled just fine.  The sure fix of this is to type ifort in a CMD
window to ensure the right one (Intel64 usually) pops up before building.
I built the same as NumPy:

python setup.py config --compiler=msvc build_clib --compiler=msvc build_ext
--compiler=msvc install

Hope someone else finds this useful,

Matt

Well, compiler not found is either a user error or it's a bug in
numpy.distutils, so keeping the discussion here is fine for now I think.

@mrslezak <https://github.com/mrslezak> can you please provide the exact
build command you used, and put the build log in a gist and give a link
here?

—
Reply to this email directly or view it on GitHub
<https://github.com/numpy/numpy/issues/7216#issuecomment-182046830>.

**Comment by rgommers** [comment]
great, thanks @mrslezak
