### ISSUE TITLE
Expose PyArray_SqueezeSelected in Numpy API?

### ISSUE THREAD

**Issue by gandalf013** [numpy/numpy#7222]
Numpy exports `PyArray_Squeeze` in its [API](http://docs.scipy.org/doc/numpy-dev/reference/c-api.array.html#c.PyArray_Squeeze), but `PyArray_SqueezeSelected` is not a part of the API.  Could the latter function also be made a part of the official API?  I am writing a C extension and having `PyArray_SqueezeSelected` available would be perfect.

**Comment by mattip** [comment]
Closing. The numpy c-api should stay as minimal as possible in my opinion.If others think we should consider this please reopen.
