### ISSUE TITLE
Ndarray transposing when indexing with list past the 2nd axis

### ISSUE THREAD

**Issue by kitizz** [numpy/numpy#7223]
Hiya!

Using:
Numpy version 1.10.2
Python 3.5
Mac OSX 10.10.3

This occurs when:
- First axis is sliced with a single index, and
- Any axis past the 2nd axis is indexed with a list

Self contained example:
```python
A = np.zeros((2,3,4))
print(A[0, :, 0:2].shape)  # (3,2) As one would expect
print(A[0, :, [0,1]].shape)  # (2,3) Unexpected
```

I've inspected the values afterwards to confirm that it's a simple transposition that's occurring (no weird remapping of data). Also occurs for arrays with higher dimensions.

**Comment by seberg** [comment]
This is to be expected (well, in the sense that it is correct and consistent, not that any normal human being actually expects it) and actually in its own twisted way mentioned in the documentation ^^. I hope this might give an understandable example (Legacy fancy indexing is what we currently have):

https://github.com/seberg/numpy/blob/indexing-nep/doc/neps/indexing.rst#examples

See also (gh-6256) and (gh-6075).

Plus seeing we have some ideas to make it nicer, might be a relief (though that does not mean it will happen too soon).
