### ISSUE TITLE
Numpy mailing list rejecting gmail domain as source of spam

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#7238]
I just got an email from matthew.brett@gmail.com rejected by the scipy.org server:

Delivery to the following recipient failed permanently:

     numpy-discussion@scipy.org

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain scipy.org by mail.scipy.org. [23.253.247.54].

The error that the other server returned was:
554 Currently Sending Spam See: http://www.sorbs.net/lookup.shtml?209.85.192.53

Posting here in case others are seeing the same thing, and suggesting again that we move to python.org mailing list hosting.

**Comment by rgommers** [comment]
never seen this before. did it only happen once?

**Comment by FRidh** [comment]
I got exactly the same. My e-mail is hosted by gmail.

**Comment by rgommers** [comment]
@dpinte @rkern any ideas? Can't find the GitHub username of Chip, but will ping him via email.

**Comment by rkern** [comment]
The `mail.scipy.org` server is under heavy spam attack at the moment. @infowolfe (Chip) has been very busy trying to block it. During the configuration churn, some legitimate emails have been blocked unintentionally. I have forwarded all of these complaints as soon as I saw them; fixing this is highest priority. @dpinte may have more information today on the ultimate outcome of this battle.

**Comment by rgommers** [comment]
Thanks for the update Robert. That doesn't sound good. Good luck fighting this off.

**Comment by dpinte** [comment]
@rgommers quick update: the spam attacks are made using `gmail.com` addresses which led the various anti-spam filtering be a bit too greedy on what is valid and what not. Fine tuning is going on and we will hopefully be in a state where it won't happen again.

**Comment by rgommers** [comment]
thanks Didrik.

**Comment by ahaldane** [comment]
Could one of you put me on the whitelist too please? I'm getting rejected as well. allan.haldane@gmail.com

Thank you!

**Comment by dpinte** [comment]
@infowolfe can you check the status of @ahaldane ?

**Comment by anntzer** [comment]
@infowolfe requesting whitelisting as well for `anntzer dot lee at gmail dot com` (me).

**Comment by matthew-brett** [comment]
I am also still being blocked (matthew.brett@gmail.com).

**Comment by dpinte** [comment]
A solution is being implemented right now. @infowolfe will be posting details on this ticket.

**Comment by infowolfe** [comment]
Sorry for the radio silence everybody, I lost my home directory and about 200GB of data over the weekend and have been trying to get back up to speed since.

If you need me urgently I'm on freenode under the nick 'infowolfe.'

It SEEMS that SORBS is completely braindead in how they list and delist large scale MX boxes (specifically Google's) and this has been going on for quite some time. I've found references as far back as 2010, and I didn't dig very hard. For those uninterested in the technicals, every 6 hours mail.scipy.org will ask _spf.google.com which netblocks it has designated as allowed for outgoing mail, and then it will process and dump the resulting ip blocks into a whitelist file. The result of that work is shown below:

I also dropped a couple of links at the bottom that I ran across when researching this issue. We might have a slightly higher incidence of spammers with gmail accounts getting through, but it should still be significantly less spam than we were dealing with before.

```
mail:~$ rblwatch 209.85.192.53
Looking up: 209.85.192.53 (please wait)

--- DNSBL Report for 209.85.192.53 ---
Results for spam.dnsbl.sorbs.net: True
  + Host information: 127.0.0.6
    + Additional information: Spam Received See: http://www.sorbs.net/lookup.shtml?209.85.192.53
Results for dnsbl.sorbs.net: True
  + Host information: 127.0.0.6
    + Additional information: Currently Sending Spam See: http://www.sorbs.net/lookup.shtml?209.85.192.53

mail:~$ rblwatch 209.85.192.50
Looking up: 209.85.192.50 (please wait)

--- DNSBL Report for 209.85.192.50 ---
Results for spam.dnsbl.sorbs.net: True
  + Host information: 127.0.0.6
    + Additional information: Spam Received See: http://www.sorbs.net/lookup.shtml?209.85.192.50
```

So 2 ips of Google's who've been blacklisted by SORBS...

This is what a connection from Google's netblocks looked like before (note the fail, NAUGHTY, dnsbl.sorbs.net line):
```
Fri Feb 12 23:42:07 2016 mail.scipy.org[2982]: Accepted connection 0/15 from 209.85.192.53 / mail-qg0-f53.google.com
Fri Feb 12 23:42:07 2016 mail.scipy.org[2982]: Connection from mail-qg0-f53.google.com [209.85.192.53]
Fri Feb 12 23:42:07 2016 mail.scipy.org[2982]: US
Fri Feb 12 23:42:07 2016 mail.scipy.org[2982]: karma 1 (1)
Fri Feb 12 23:42:07 2016 mail.scipy.org[2982]: pass
Fri Feb 12 23:42:08 2016 mail.scipy.org[2982]: pass, not spontaneous
Fri Feb 12 23:42:08 2016 mail.scipy.org[2982]: skip, no match
Fri Feb 12 23:42:08 2016 mail.scipy.org[2982]: karma -1 (0)
Fri Feb 12 23:42:08 2016 mail.scipy.org[2982]: fail, NAUGHTY, dnsbl.sorbs.net
Fri Feb 12 23:42:08 2016 mail.scipy.org[2982]: 220 mail.scipy.org ESMTP qpsmtpd 0.95/v0.95 ready; send us your mail, but not your spam.
Fri Feb 12 23:42:08 2016 mail.scipy.org[2982]: dispatching EHLO mail-qg0-f53.google.com
Fri Feb 12 23:42:08 2016 mail.scipy.org[2982]: karma -1 (-1)
Fri Feb 12 23:42:08 2016 mail.scipy.org[2982]: 250-mail.scipy.org Hi mail-qg0-f53.google.com [209.85.192.53]
```
And what the result of that failure was...
```
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: LISTNAME-LIST is a mailman list
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: pass: scipy.rog in rcpthosts
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: 250 <listname-list@scipy.rog>, recipient ok
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: dispatching DATA
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: pass, No URIs found in mail
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: disconnecting
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: 554 Currently Sending Spam See: http://www.sorbs.net/lookup.shtml?209.85.192.53
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: click, disconnecting
Fri Feb 12 23:42:09 2016 mail.scipy.org[2982]: 1.427 s.
```

As of this morning we note that "skip, whitelisted host" shows when email comes in from Google's mailservers.
```
Thu Feb 18 15:36:03 2016 mail.scipy.org[6681]: 220 mail.scipy.org ESMTP qpsmtpd 0.95/v0.95 ready; send us your mail, but not your spam.
Thu Feb 18 15:36:03 2016 mail.scipy.org[6681]: dispatching EHLO mail-qg0-f50.google.com
Thu Feb 18 15:36:03 2016 mail.scipy.org[6681]: skip, whitelisted host
Thu Feb 18 15:36:03 2016 mail.scipy.org[6681]: 250-mail.scipy.org Hi mail-qg0-f50.google.com [209.85.192.50]
...
Thu Feb 18 15:36:04 2016 mail.scipy.org[6681]: pass
Thu Feb 18 15:36:04 2016 mail.scipy.org[6681]: 250 Queued! <CABxw0nEGN2gkjZAPnnCofGE32umtvujA41-SzskrMwAA9MZ_-Q@mail.gmail.com> (Queue-Id: 34C57382F)
Thu Feb 18 15:36:04 2016 mail.scipy.org[6681]: dispatching QUIT
Thu Feb 18 15:36:04 2016 mail.scipy.org[6681]: 221 mail.scipy.org closing connection. Have a wonderful day.
Thu Feb 18 15:36:04 2016 mail.scipy.org[6681]: click, disconnecting
Thu Feb 18 15:36:04 2016 mail.scipy.org[6681]: 1.485 s.
```

https://productforums.google.com/forum/#!msg/apps/WjzMWHorSSs/kuUjoxqyEOYJ
https://forums.contribs.org/index.php?topic=46690.0
