### ISSUE TITLE
Request: logspace that doesn't require log(a) as argument

### ISSUE THREAD

**Issue by endolith** [numpy/numpy#7255]
linspace(a, b, 10) creates 10 points linearly spaced from a to b.

logspace(a, b, 10) does *not* create 10 points logarithmically spaced from a to b, as everyone expects it to:

- http://stackoverflow.com/q/31480033/125507
- http://stackoverflow.com/q/31192392/125507
- https://sourceforge.net/p/numpy/mailman/numpy-discussion/thread/Mahogany-0.66.0-0000-00000000-111126.00@CASC64043305.american.edu/

The current behavior can't be changed because of backwards/matlab compatibility, but it would be nice if there were another function that didn't require the extra step of `logspace(log(a), log(b)...`.  

I don't know what it should be called, though.

**Comment by njsmith** [comment]
Can you write up a specific proposal for what the new function's semantics should be, and send it to the mailing list? (In particular it isn't instantly obvious to me what "10 points logarithmically spaced from a to b" means, e.g. does the log base matter?)

**Comment by endolith** [comment]
I think it would be as simple as:

```
def newlogspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None):
    return numpy.logspace(log(start)/log(base), log(stop)/log(base), num, endpoint, base, dtype)
```
Mostly I just don't know what to call the function, since "logspace" would make sense, but is taken.

And maybe accuracy is slightly better if it has a special case of log10(start) when the base == 10, etc.

**Comment by njsmith** [comment]
OK, but it's still the case that if you want this to move forward your next step is to write up a specific proposal and send it to the mailing list :-)

**Comment by jaimefrio** [comment]
The syntax seems to be taken [from Matlab](http://ch.mathworks.com/help/matlab/ref/logspace.html).

I'm terrible at naming, but your function would build a geometric sequence, so maybe something along the lines of `geomspace`?

Also, getting rid of the `base` parameter seems to make all the sense here.

But we should be having this discussion on the mailing list.

**Comment by rkern** [comment]
"Logarithmically spaced" is well defined and not base-dependent; `base` only appears in the current `np.logspace()` because it needs to interpret its already-logged arguments. As @jaimefrio points out, it is just a geometric sequence where each successive element is a uniform multiple of its predecessor. This gives you the same result regardless of base, for instance:

```
np.power(base, np.linspace(np.log(start)/np.log(base), np.log(stop)/np.log(base), n))
```

A base-independent implementation would be:

```
def mylogspace(start, stop, num=50, endpoint=True, dtype=None):
    return np.exp(np.linspace(np.log(start), np.log(stop), num=num, endpoint=endpoint, dtype=dtype))
```

**Comment by endolith** [comment]
@jaimefrio  I just found [spacepy.toolbox.geomspace](http://spacepy.lanl.gov/doc/autosummary/spacepy.toolbox.geomspace.html).  Same name, same syntax. :)
