### ISSUE TITLE
unravel_index returns non-writeable arrays

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7269]
```
In [6]: x, y = np.unravel_index([1, 2, 3], (4, 5))

In [7]: y[0] = 1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-cb16f55df1e0> in <module>()
----> 1 y[0] = 1

ValueError: assignment destination is read-only
```

**Comment by gfyoung** [comment]
1) Is there a reason why you want to directly modify the coordinate arrays?
2) I actually did not realize the arrays were read-only, so the doc should at least reflect that

**Comment by anntzer** [comment]
Because I wanted corresponding row indices, but shifted by 1, in another array?  Yes I can just write `x_ = x + 1` but the fact that `x+=1` doesn't work seems to be a gratuitious inconvenience.

**Comment by gfyoung** [comment]
Fair enough.  Also, I don't know of too many `numpy` functions which return read-only arrays, so this definitely feels inconsistent with the entire of the `numpy` API.

**Comment by seberg** [comment]
There is no reason for this to be read only, it is certainly simply a matter of some flags being forgotten in the array creation.

**Comment by gfyoung** [comment]
Indeed, the fix is not super difficult.
