### ISSUE TITLE
memoryview on array with datetime/timedelta-dtype triggers SystemError on Python 3.5

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#7270]
On Python 3.5, constructing a `memoryview` for an `ndarray` containing a datetime/timedelta-dtype leads to a `SystemError: <class 'memoryview'> returned a result with an error set`:

```
In [50]: memoryview(numpy.zeros(10, dtype=[("A", "m8[s]")]))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: cannot include dtype 'm' in a buffer

During handling of the above exception, another exception occurred:

SystemError                               Traceback (most recent call last)
<ipython-input-50-5d5ac6c085fa> in <module>()
----> 1 memoryview(numpy.zeros(10, dtype=[("A", "m8[s]")]))

SystemError: <class 'memoryview'> returned a result with an error set
```

Prior to Python 3.4, results for the same were unpredictable and bizarre, see [this Stack Exchange question](http://stackoverflow.com/q/28708411/974555).

I am aware that `datetime64` and `timedelta64` do not support the buffer protocol (see #4983), but the _another exception occurred_ should not happen.

This appears to be related to [Python issue 23571](https://bugs.python.org/issue23571), although I can't say I quite understand what's going on.

**Comment by gerritholl** [comment]
Or should this still be considered [an upstream bug](https://github.com/numpy/numpy/issues/4983#issuecomment-80796424)?

**Comment by augurar** [comment]
Yes, this is an upstream bug.  It seems that `memoryview()` is setting an error but returning a non-null result.  Handling of this case changed in Python 3.5, so the `SystemError` is expected behavior.

**Comment by eric-wieser** [comment]
I can't reproduce this any more in 1.15.4, despite the fact that nothing seems to have changed upstream.
