### ISSUE TITLE
Converting array to subarray dtype requires bogus intermediary dtype

### ISSUE THREAD

**Issue by machinaut** [numpy/numpy#7273]
I have an array of 2d-arrays that I wish to treat as single units.

```
>>> import numpy as np
>>> x = np.arange(4*3*2).reshape((4,3,2))
```

So I made a custom subarray dtype:

```
>>> blob_dtype = np.dtype((x.dtype, (3,2)))
```

But conversions to this new subarray dtype fail:

```
>>> y = x.flatten().view(blob_dtype)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: new type not compatible with array.
```

After looking at the [code causing the failure](https://github.com/numpy/numpy/blob/328f89e48558b8c9523a6c41696fd2b677930fa1/numpy/core/src/multiarray/getset.c#L493) I saw this was a viable workaround:

```
>>> void_dtype = np.dtype((np.void, x.dtype.itemsize*3*2))
>>> y = x.flatten().view(void_dtype).view(blob_dtype)
```

Which seems to work, but I may be missing something fundamental about how subarray dtypes work.

My end goal is to filter out unique subarrays from a very large dataset.

**Comment by ahaldane** [comment]
Yes, it looks like you cannot view an array if the dtype's itemsize changes and there is a subarray. That line goes back to at least 2009, too. See also #3584.

Your solution using void types is exactly the kind of thing I have done myself. (In my case, to find unique sequences in a multiple sequence alignment). I might go with that for now, until #3584 is implemented.

**Comment by ahaldane** [comment]
And also, just brainstorming here: I was recently thinking about pandas which optimizes this kind of operation, and where a possible solution is
```
pandas.DataFrame(x.reshape((4,6))).drop_duplicates()
```
It's too bad that we have to reshape it to be 2d in pandas, but I've also recently been reading about xarray which promises to be pandas for large nd datasets. But it doesn't seem to have "unique" or "drop_duplicates" functionality yet.

In summary, various people have been thinking about how to solve your problem, but currently viewing as void may still be the way to do it in numpy.

**Comment by machinaut** [comment]
FWIW, I'd still like the ability to `view()` with a custom subarray dtype, though the specific instance which caused me to post this issue is now addressed.

**Comment by eric-wieser** [comment]
A simpler workaround is `arr.view([('val', new_dtype)])['val']`?

**Comment by atom-moyer** [comment]
I am trying to also cast a prebuilt ndarray into an array of reduced dimension with a subarray dtype. Specifically in my case, I have a `(N, 50) array (uint8)` and I would would like to create, without copying, an array like `(N) array (50, uint8)` which is necessary for interfacing with a pybind11 application.

**Comment by eric-wieser** [comment]
@atom-moyer: my example above does not make a copy, what is your concern? Can you show some code?

**Comment by atom-moyer** [comment]
```
values = np.packbits([np.array([True, False]*200, dtype=np.bool)]*200, axis=1)
values.view([('val', np.dtype('50u1'))])['val']
print(values, values.shape, values.dtype)
```

```
[[170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]
 ...
 [170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]
 [170 170 170 ... 170 170 170]] (200, 50) uint8
```

**Comment by eric-wieser** [comment]
You need to use the return value of `new_values = values.view([('val', np.dtype('50u1'))])['val']`

**Comment by atom-moyer** [comment]
That is close! It seems like it is applying a view change, however, it is not quite right. Now my code looks like this and returns the following.

```
values = np.packbits([np.array([True, False]*200, dtype=np.bool)]*200, axis=1)
new_values = values.view([('val', value_type)])['val']
print(new_values, new_values.shape, new_values.dtype)
```

```
[[[170 170 170 ... 170 170 170]]
 [[170 170 170 ... 170 170 170]]
 [[170 170 170 ... 170 170 170]]
 ...
 [[170 170 170 ... 170 170 170]]
 [[170 170 170 ... 170 170 170]]
 [[170 170 170 ... 170 170 170]]] (200, 1, 50) uint8
```

I expect something like this:
```
[ [170 170 170 ... 170 170 170]
  [170 170 170 ... 170 170 170]
  [170 170 170 ... 170 170 170]
 ...
  [170 170 170 ... 170 170 170]
  [170 170 170 ... 170 170 170]
  [170 170 170 ... 170 170 170] ] (200) (uint8, 50)
```

**Comment by eric-wieser** [comment]
It is not possible to create an array with dtype `('u1', (50,))` by any means. Subarray types decay when not within a structured type.

**Comment by atom-moyer** [comment]
Thanks. I suppose that this entire issue is not actually a valid issue because, to my understanding, the original poster was trying to do the same thing as me, but they were going from 3D to 1D with a 2D subarray dtype.

**Comment by atom-moyer** [comment]
So if I make a structured type with a data member of type `('u1', (50,))`, would you expect me to be able to cast the view then?

**Comment by eric-wieser** [comment]
> So if I make a structured type with a data member 

That's exactly what my code above does, with a data member called "val"

**Comment by atom-moyer** [comment]
Ok. Thanks!

**Comment by mattip** [comment]
Closing, please reopen if action is needed
