### ISSUE TITLE
0-dimensional ndarrays should support `len`

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#7281]
When asking for `len(X)` on a 0-d ndarray, a `TypeError` is raised because the object is reportedly unsized.  This despite `X.size` being equal to 1.  If `X` were unsized, it wouldn't have a '.size' attribute?

```
In [88]: X = array(0.0, dtype=float32)

In [89]: X.shape
Out[89]: ()

In [90]: X.size
Out[90]: 1

In [91]: len(X)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-91-a6c197cecae8> in <module>()
----> 1 len(X)
```

Interestingly, a `void` *does* accept `len`:

```
In [80]: X = zeros(shape=(), dtype=dtype([('x', '<f4')]))

In [81]: X.size
Out[81]: 1

In [82]: len(X)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-82-a6c197cecae8> in <module>()
----> 1 len(X)

TypeError: len() of unsized object

In [83]: len(X[()])
Out[83]: 1
```

**Comment by rkern** [comment]
It does not report a `__len__` because it cannot be indexed by integers, sliced, or iterated over, at least one of which should be true for things with a `__len__`. `.size` is a numpy thing talking about how much memory it takes up (in units of `.itemsize` bytes), more or less.

**Comment by gerritholl** [comment]
Or maybe not.  I just thought the second example was odd.  If it has a size, doesn't that sort of mean it has a length?

**Comment by gerritholl** [comment]
It makes sense, on second thought.  But then why does `void` have a `__len__`?

**Comment by njsmith** [comment]
Another way to think about it: `a.size` is `prod(a.shape)`, and `len(a)` is `a.shape[0]`. So for a 0d array, the former is 1 and the latter is an error.

**Comment by rkern** [comment]
This `void` is a record with fields. You can access those fields by indexing in addition to using the name.

**Comment by seberg** [comment]
I guess this can be closed, or is there still something to discuss here @gerritholl?
