### ISSUE TITLE
Clarify the error message on reshape failure

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7293]
Currently, if incompatible values are passed to `np{,.ndarray}.reshape`, the error message is a rather unhelpful "total size of new array must be unchanged".  It would be nicer if this was instead something like "Cannot reshape array of size N into shape (X, Y, Z)".
(Because `reshape` is written in C, if something like `func().reshape(...)` fails, then you can't even check for the size of `func()` via `pdb` and you actually need to edit your code there.)

**Comment by yash14123** [comment]
Would like to work on this one.

**Comment by njsmith** [comment]
@yash14123: go for it!

**Comment by jaimefrio** [comment]
To make your life easier, @yash14123:

 1. The `ndarray.reshape()` function is implemented in C as [`array_reshape`](https://github.com/numpy/numpy/blob/maintenance/1.11.x/numpy/core/src/multiarray/methods.c#L172).
 3. It calls the C API function [`PyArray_Newshape`](https://github.com/numpy/numpy/blob/maintenance/1.11.x/numpy/core/src/multiarray/shape.c#L171).
 4. The actual error happens in the auxiliary function [`_fix_unknown_dimension`](https://github.com/numpy/numpy/blob/maintenance/1.11.x/numpy/core/src/multiarray/shape.c#L492).
 5. Creating a dynamic error message in C is kind of cumbersome. NumPy already does something similar for the `nditer` object, you may want to draw inspiration from [here](https://github.com/numpy/numpy/blob/maintenance/1.11.x/numpy/core/src/multiarray/nditer_constr.c#L1741).

Thanks and good luck!
