### ISSUE TITLE
Minor grammatical oversight in Quickstart tutorial 

### ISSUE THREAD

**Issue by brawlingNavada** [numpy/numpy#7303]
From: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

"In example pictured below, the array has rank 2"

Should include 'the' 
"In the example pictured below, the array has rank 2..."

**Comment by njsmith** [comment]
Would you like to file a pull request fixing this? The source code for that file should be under `numpy/doc/...` somewhere :-)

**Comment by omegahm** [comment]
This is fixed by #7313.
