### ISSUE TITLE
performance loss after vectorization

### ISSUE THREAD

**Issue by mistguy** [numpy/numpy#7319]
I am writing a time consuming program. To reduce the time, I have tried my best to use numpy.dot instead of for loops.

However, I found vectorized program to have much worse performance than the for loop version:
```python
import numpy as np
import datetime
kpt_list = np.zeros((10000,20),dtype='float')
rpt_list = np.zeros((1000,20),dtype='float')
h_r = np.zeros((20,20,1000),dtype='complex')
r_ndegen = np.zeros(1000,dtype='float')
r_ndegen.fill(1)
# setup completed
# this is a the vectorized version
r_ndegen_tile = np.tile(r_ndegen.reshape(1000, 1), 10000)
start = datetime.datetime.now()
phase = np.exp(1j * np.dot(rpt_list, kpt_list.T))/r_ndegen_tile
kpt_data_1 = h_r.dot(phase)
end = datetime.datetime.now()
print((end-start).total_seconds())
# the result is 19.302483
# this is the for loop version
kpt_data_2 = np.zeros((20, 20, 10000), dtype='complex')
start = datetime.datetime.now()
for i in range(10000):
    kpt = kpt_list[i, :]
    phase = np.exp(1j * np.dot(kpt, rpt_list.T))/r_ndegen
    kpt_data_2[:, :, i] = h_r.dot(phase)
end = datetime.datetime.now()
print((end-start).total_seconds())
# the result is 7.74583
```
I have asked this question on stackoverflow and was suggested to post it here.

What's happening here?

**Comment by charris** [comment]
You should ask this on the mailing list.

**Comment by shoyer** [comment]
StackOverflow is also a good place to ask questions like this -- arguably better than the mailing list.

**Comment by seberg** [comment]
Might be RAM usage/cache friendliness or just some other performance error in the code (without looking at it). Anyway, it does not belong here as pointed out, so closing. Feel free to email the list or some such.

**Comment by njsmith** [comment]
The problem's almost certainly the call to `tile` -- you're allocating a giant temporary array, and it's unnecessary. See the docs on "broadcasting" -- your code I think will still work if you replace the line calling `tile` with
```

**Comment by njsmith** [comment]
Stupid phone.

... If you replace it with
```
r_ndegen_tile = r_ndegen.reshape(1000, 1)
```

Good luck
