### ISSUE TITLE
Wrong name of inverse hyperbolic function

### ISSUE THREAD

**Issue by WilliWichtig** [numpy/numpy#7321]
The name of the inverse hyperbolic functions are for example:

areasinh() = arsinh()
areacosh() = arcosh()

In numpy the inverse hyperbolic functions are defined by arcsinh(). This is misleading because the "arcus" is used for the inverse trigonometric functions. I think the best would be to implement arsinh() as well in numpy. So one can use both names (e.g. arsinh and arcsinh).

Greetings

PS: https://en.wikipedia.org/wiki/Inverse_hyperbolic_function

**Comment by pv** [comment]
There's a long tradition of using the "wrong" names, see, for example [DLMF](http://dlmf.nist.gov/4.37), [Abramowitz&Stegun](http://people.math.sfu.ca/~cbm/aands/page_86.htm), and [Mathematica](https://reference.wolfram.com/language/ref/ArcSinh.html). I do not believe changing the names are on the table at this point.
