### ISSUE TITLE
numpy.histogram2d documentation page "source code" link not working.

### ISSUE THREAD

**Issue by theaverageguy** [numpy/numpy#7326]
[numpy.histogram2d](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.histogram2d.html) has a source code link at the bottom. It does not seem to work.

**Comment by maniteja123** [comment]
Hi there, it would be helpful to get the relevant error occurring and also corresponding traceback for others to understand the problem.

**Comment by yash14123** [comment]
Willing to fix it. :)

**Comment by maniteja123** [comment]
It seems that the links are working when building locally. Also it probably is not working even for other pages. See [sin](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.sin.html). But even I have no clue why this is happening.

**Comment by pv** [comment]
They links are probably not that useful in the first place. They can be removed by setting appropriate options for the plot directive in the sphinx configuration file.

**Comment by yash14123** [comment]
I am on it then . :)

**Comment by yash14123** [comment]
Is it finalized then? Remove the links right?

**Comment by mattip** [comment]
Closing. The link no longer appears.
