### ISSUE TITLE
">>>" button in docs not correct

### ISSUE THREAD

**Issue by yash14123** [numpy/numpy#7327]
In [numpy.histogram2d](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.histogram2d.html) , the code snippets have a ">>>" button on top right. This does not work correctly on a multi-line command. The lines except the first one get vanished.

**Comment by pv** [comment]
The multi-line commands there are written incorrectly -- continuation lines should start with `... `

**Comment by simongibbons** [comment]
Looks like this is fixed on master already.

https://github.com/numpy/numpy/blob/master/numpy/lib/twodim_base.py#L679
