### ISSUE TITLE
No source link in numpy.bincount and numpy.digitize docs

### ISSUE THREAD

**Issue by rehassachdeva** [numpy/numpy#7333]
Following documents don't have source link on top right as opposed to many other related documents.
http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.bincount.html
http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.digitize.html

**Comment by jaimefrio** [comment]
That's because they are written in C, and I guess the doc generator is not smart enough to figure where those are. I'm going to close this as a non-issue, but feel free to reopen it if you have further questions.

**Comment by mzechmeister** [comment]
I traced it back to `PyCFunction arr_bincount` in
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/multiarraymodule.c
and finally
https://github.com/numpy/datetime/blob/master/numpy/lib/src/_compiled_base.c

**Comment by jxu** [comment]
https://github.com/numpy/numpy/blob/main/numpy/core/src/multiarray/compiled_base.c is the main repo for now
