### ISSUE TITLE
install pytz on CI systems

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#7335]
It [looks like](https://github.com/numpy/numpy/pull/7324#issuecomment-188570894) we missed a bug due to not having pytz installed on Travis/Appveyor, and thus skipping all the tests for timezone-related stuff. This is bad, so we should make sure that doesn't happen again by installing pytz on those systems.

**Comment by jakirkham** [comment]
Oops, didn't see this so I didn't have it included in the PR before it was merged. Was just merged here ( https://github.com/numpy/numpy/pull/7338 ). Feel free to close unless something else is needed.

**Comment by njsmith** [comment]
No worries, thanks for getting it fixed :-)

**Comment by jakirkham** [comment]
Of course.
