### ISSUE TITLE
BUG: np.ma.median has rank 1 or 0 result

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#7345]
When using `numpy.ma` functions that reduce to a scalar most behave in a reasonable and consistent manner for their results. Namely, both results are rank 0 scalars.

    >>> import numpy as np
    >>> a = np.ma.array([1.0, 2.0, 3.0])
    masked_array(data = [ 1.  2.  3.],
                 mask = False,
           fill_value = 1e+20)
    >>> b = np.ma.array([1.0, 2.0, 3.0], mask=True)
    masked_array(data = [ 1.  2.  3.],
                 mask = [ True  True  True],
           fill_value = 1e+20)
    >>> np.ma.mean(a)
    masked_array(data = 2.0,
                 mask = False,
           fill_value = 1e+20)
    >>> np.ma.mean(b)
    masked

However, `numpy.ma.median` does not behave in a consistent manner. Seems to me that `numpy.ma.median` should be consistent and return a scalar in both cases.

    >>> import numpy as np
    >>> np.ma.median(a)
    masked_array(data = 2.0,
                 mask = False,
           fill_value = 1e+20)
    >>> np.ma.median(b)
    masked_array(data = [--],
                 mask = [ True],
           fill_value = 1e+20)

**Comment by charris** [comment]
In `1.12.0.dev0+5bd7cb2`
```
In [47]: ma.median(b)
Out[47]: masked
```
Which looks to be what is asked for.
