### ISSUE TITLE
Documentation Error in NumPy User Guide

### ISSUE THREAD

**Issue by sirdodo** [numpy/numpy#7364]
NumPy User Guide Release 1.10.1, section 2.7.1 (Introduction to Structured Arrays) shows
>>> y = x['foo']

This is incorrect. The line should read
>>> y = x['bar']

**Comment by simongibbons** [comment]
Looks like this is already fixed on master
https://github.com/numpy/numpy/commit/e5d61d6f946ef75b822d937b801a02f64736e53f

**Comment by seberg** [comment]
Thanks @sirdodo and @simongibbons.
