### ISSUE TITLE
Link not working in Docs.

### ISSUE THREAD

**Issue by theaverageguy** [numpy/numpy#7365]
In the [docs](http://docs.scipy.org/doc/) , the CHM link in this hyperlink does not work.
Numpy (development version) Reference Guide, [HTML+zip], [CHM], [PDF]

![p](https://cloud.githubusercontent.com/assets/9817962/13397968/3b78a658-df22-11e5-9613-c63b9f46141a.png)

**Comment by rgommers** [comment]
We don't produce CHM files anymore, the links should be removed from this file: https://github.com/scipy/docs.scipy.org/blob/master/index.rst

**Comment by b-carter** [comment]
I can remove these links. Do you want to leave the old ones that are still working or remove all of them? Also, what about those from scipy?

**Comment by rgommers** [comment]
Thanks @b-carter. All the html and pdf links should still be working; we upload those for every release. So only all the CHM ones need to be removed. Same applies to Scipy.
