### ISSUE TITLE
lexsort fails on datetime objects

### ISSUE THREAD

**Issue by tinloaf** [numpy/numpy#7369]
Hi,

as stated over here: https://github.com/scipy/scipy/issues/1794, lexsort fails to sort datetime.date (or datetime.datetime) objects.

I just tried this with recent numpy from pip, the issue still exists:
```
>>> import numpy as np
>>> import datetime
>>> date = np.array([datetime.date(2000, 1, 1), datetime.date(1999, 1, 1)])
>>> np.lexsort((date,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: merge sort not available for item 0

```

My numpy version is 1.10.4.

**Comment by charris** [comment]
I believe this has been fixed.
```
In [1]: np.__version__
Out[1]: '1.12.0.dev0+f6c2e7f'

In [2]: date = np.array([datetime.date(2000, 1, 1), datetime.date(1999, 1, 1)])

In [3]: np.lexsort((date,))
Out[3]: array([1, 0])
```

**Comment by charris** [comment]
Might try `pip install --pre --upgrade` to see if you can get 1.11.0rc1 .

**Comment by seberg** [comment]
Closing then, since it seems fixed.
