### ISSUE TITLE
integer overflow in arange for integers beyond 32 bit

### ISSUE THREAD

**Issue by mtremmel** [numpy/numpy#7375]
when using np.arange to make a an array with size larger than 2**31 I get integer overflows for indices between 2**31 and the second to last index. Strangely, the last value is correct. This did not occur in version 1.9 but occurs as of 1.10.4 (possibly sooner)

**Comment by mtremmel** [comment]
sorry that is 2^31 to be clear not 231

**Comment by jaimefrio** [comment]
Not on Mac:

```Python
In [68]: np.__version__
Out[68]: '1.12.0.dev0+bd905a8'

In [69]: np.arange(2**32-5, 2**32+5)
Out[69]: 
array([4294967291, 4294967292, 4294967293, 4294967294, 4294967295,
       4294967296, 4294967297, 4294967298, 4294967299, 4294967300])

In [70]: np.arange(2**31+5)[-10:]
Out[70]: 
array([2147483643, 2147483644, 2147483645, 2147483646, 2147483647,
       2147483648, 2147483649, 2147483650, 2147483651, 2147483652])
```

Can you give more details on your system, and some reproducible code sample of the error you are seeing?

**Comment by mtremmel** [comment]
The computer I use has the Cray Linux Environment. It is using python 2.7... maybe it needs an updated version of numpy?

In [1]: import numpy as np

In [2]: xx = np.arange(2**31 + 3000)

In [3]: xx.min()
Out[3]: -2147483648

In [4]: np.__version__
Out[4]: '1.10.4'

**Comment by charris** [comment]
My guess is that you have 32 bit longs, either as a compiler default or because you are running a 32 bit version of numpy. Try `np.arange(..., dtype=np.int64)`. You can check the size of long by `np.dtype('l').itemsize`.

**Comment by mtremmel** [comment]
hmmm no I get that my longs are 64 bit. setting dtype does not help.

```
In [18]: np.dtype('l').itemsize
Out[18]: 8

In [19]: np.dtype('int64').itemsize
Out[19]: 8

In [20]: np.dtype('int32').itemsize
Out[20]: 4

In [21]: xx = np.arange(2**31 + 3000,dtype=np.int64)

In [22]: xx.min()
Out[22]: -2147483648

In [23]: xx[:-10]
Out[23]: 
array([          0,           1,           2, ..., -2147480661,
       -2147480660, -2147480659])

In [24]: xx[-1]
Out[24]: -2147480649

In [25]: xx = np.arange(2**31 + 3000)

In [26]: xx[-1]
Out[26]: -2147480649

In [27]: xx[-10:]
Out[27]: 
array([-2147480658, -2147480657, -2147480656, -2147480655, -2147480654,
       -2147480653, -2147480652, -2147480651, -2147480650, -2147480649])
```

**Comment by charris** [comment]
OK, what is the value of `2**31 + 3000`? Also, `np.arange(10).dtype`?

**Comment by mtremmel** [comment]
```
In [28]: np.arange(10).dtype
Out[28]: dtype('int64')

In [29]: 2**31 + 3000
Out[29]: 2147486648
```

**Comment by charris** [comment]
It's pretty clear that the values are wrapping at 2**31, the question is why a 32 bit accumulator  is being used. Note that I don't see this problem either.

**Comment by charris** [comment]
I'm going to guess a compiler bug as a possibility.

**Comment by charris** [comment]
What does `np.array([2**31], dtype='l')` show? How about `np.array([2**31], dtype='l').tostring()`?

**Comment by seberg** [comment]
Thats odd, just be sure the length of the array is correct, right? And the first two items are correct as well?

Because if those are correct, it should come down to:
```
@NAME@_fill(@type@ *buffer, npy_intp length, void *NPY_UNUSED(ignored))
{
    npy_intp i;  <- equivalent to ssize_t
    @type@ start = buffer[0];  <- first value in array
    @type@ delta = buffer[1];  <- second value in array

    delta -= start;
    for (i = 2; i < length; ++i) {
        buffer[i] = start + i*delta;
    }
}
```
and I can't see anything weird about that, unless `start + i*delta` for some reason is wrong.

**Comment by charris** [comment]
I'm beginning to think it may be a printing format error, which would put it in the C library.

**Comment by eric-wieser** [comment]
FWIW, `np.arange(2**31-5, 2**31+5)` behaves correctly for me on windows, where `np.dtype('l').itemsize == 4`. Perhaps this can be closed?

**Comment by mattip** [comment]
Closing this old report since the original reporter did not respond with more information
