### ISSUE TITLE
NumPy has a readthedocs page?

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#7376]
It appears there is a readthedocs page for NumPy, but it is really old. Should this be maintained? Removed. Here is the link. ( http://numpy.readthedocs.org/en/latest/ )

**Comment by njsmith** [comment]
That's weird. Also weird is that the "Owners" list is blank. It's certainly not useful as is, and I'm not sure whether it could be made so in any reasonable way...

**Comment by shoyer** [comment]
Someone else contributed the original version, but I did write to him/her and get admin privileges. So if anyone wants to play around with the admin settings, let me know. My intent was to see if getting an automated build of the numpy docs would be possible, but I never got around to it....

**Comment by rgommers** [comment]
Closing in favor of https://github.com/numpy/numpy.org/issues/431
