### ISSUE TITLE
Logical function output types do not correspond to dtype argument

### ISSUE THREAD

**Issue by DavidYoungSoton** [numpy/numpy#7377]
The documentation for ufuncs says that the optional dtype argument "Overrides the dtype of the calculation and output arrays." I think this means that the result should have the specified dtype (or if this is not possible, an error should be raised).

However, this doesn't happen. For example

```
import numpy as np
print np.__version__
y = np.logical_xor(1.0, 0.0, dtype=np.float32)
print y.dtype
```

prints

> 1.10.4
> bool

The same happens with other functions that produce boolean results, but with arithmetic functions such as `add` the dtype argument affects the result type in the way I'd expect.

If I've misunderstood the documentation, I think there's a case for clarifying it, but I imagine that the point of the dtype argument is that it enables you to set the type of the output without having to do a subsequent cast.

**Comment by yashmehrotra** [comment]
@charris Hi Charles. I would like to work on this bug. Can you help me get started with it. I have understood the issue and would like to solve it.

**Comment by yashmehrotra** [comment]
@charris Hi Charles. I would like to work on this bug. Can you help me get started with it. I have understood the issue and would like to solve it. Can you pinpoint towards the right file ? I am facing some difficulty finding out where it is being called. Thanks.

**Comment by OmerJog** [comment]
Bug still exist.

```
import numpy as np
print (np.__version__)
y = np.logical_xor(1.0, 0.0, dtype=np.float32)
print (y.dtype)
```

prints
```
1.16.2
bool
```

**Comment by charris** [comment]
I think the documentation is probably incorrect but it might be worth raising the issue on the mailing list to see if others agree..

**Comment by seberg** [comment]
I added a deprecation for this in main:
```
In [5]: import numpy as np
   ...: print (np.__version__)
   ...: y = np.logical_xor(1.0, 0.0, dtype=np.float32)
   ...: print (y.dtype)
1.22.0.dev0+332.gd3b84db58
<ipython-input-5-12d9b6709410>:3: DeprecationWarning: using `dtype=` in comparisons is only useful for `dtype=object` (and will do nothing for bool). This operation will fail in the future.
  y = np.logical_xor(1.0, 0.0, dtype=np.float32)
bool
```
