### ISSUE TITLE
Reconsider identity of bitwise reductions on empty object arrays

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#7381]
As came up in gh-7373 returning `-1` for `np.bitwise_or.reduce(np.array([], dtype=object))` is a bit weird. Since the return of `True` before was less correct -1 is currently returned.
See also https://mail.scipy.org/pipermail/numpy-discussion/2016-March/075127.html though at the time of writing there was no further discussion there.

It might be a good idea to reconsider the empty reductions for object arrays in the case of `bitwise_or` specifically and more general possibly some other empty object reductions.

**Comment by seberg** [comment]
Just to note, there seems to be a strong tendency towards deprecation for the -1 case at least.

**Comment by WarrenWeckesser** [comment]
I haven't tracked down when it happened, but apparently this has been fixed:
```
In [10]: import numpy as np

In [11]: np.__version__
Out[11]: '1.22.0.dev0+1643.gbc087bb2b'

In [12]: np.bitwise_or.reduce(np.array([], dtype=object))
Out[12]: 0
```
