### ISSUE TITLE
nanmax returns inconsistent shape when applied to pandas.Series

### ISSUE THREAD

**Issue by DSLituiev** [numpy/numpy#7389]
When used with pandas Series `np.nanmax` and `np.nanmin` return an array, while a scalar is expected, [pandas issue #12383](https://github.com/pydata/pandas/issues/12383):

```
import pandas as pd
import numpy as np

li = [1,2,3,4,5]
ds = pd.Series(li, index= ["%s"%x for x in li])

# these returns a scalar
print(np.nanmean(ds))
print(np.max(ds))

#this returns a Series
print(np.nanmax(ds))
```

I do not exactly understand why  `np.fmax.reduce(np.array(ds))` and `np.fmax.reduce(ds.tolist())` return a scalar, while `np.fmax.reduce(ds)` returns a Series, but this looks to be the cause.

https://github.com/numpy/numpy/blob/master/numpy/lib/nanfunctions.py#L340

**Comment by ahaldane** [comment]
Reviewing this as part of my 10 random issues, as requested in a [3/20/19 request](https://mail.python.org/pipermail/numpy-discussion/2019-March/079250.html).

I ran the example code above, and this issue appears to be fixed. The three values are now numpy scalars.
Closing.
