### ISSUE TITLE
np.dtype doesn't represent datetime64 with timezone

### ISSUE THREAD

**Issue by gliptak** [numpy/numpy#7390]
Code to reproduce (using Pandas):

    from dateutil.parser import parse
    import numpy as np
    import pandas as pd
    df = pd.DataFrame([parse("Mar 10, 2016 11:20 PM EDT")], columns=['ts'])
    df.dtypes['ts'] == np.dtype('datetime64[ns, tzlocal()]')

This above last line fails with

    TypeError: Invalid datetime unit in metadata string "[ns, tzlocal()]"

**Comment by shoyer** [comment]
NumPy has never supported datetime64 with timezones -- pandas uses it's own dtype system, as described in the issue above.
