### ISSUE TITLE
BUG: np.sum / np.add.reduce / np.array change in behaviour for indexable objects

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#7393]
`astropy` is failing with 1.11 because of a bug that seems to boil down to a change in behaviour of `np.sum` (or specifically `np.add.reduce`), which I think in turn is due to how `np.array` treats things that end up being object arrays (have not investigated in detail), in that before, if something could be indexed, it would be split into individual pieces, while now it becomes a single object array. If split into pieces, it seems `np.add.reduce` attempts to add the pieces together (which fails for our class), while if a single piece, it just returns the single object.

While this is a regression of sorts, in a way the new behaviour is a bit more sane, and we can work around it, so I'm raising this mostly to ensure this new behaviour is in fact desired.
```
# in numpy 1.10.4
np.__version__
# '1.10.4'
from astropy.time import Time
d = Time([50001, 50002], format='mjd')           
np.array(d)
# array([<Time object: scale='utc' format='mjd' value=50001.0>,
#        <Time object: scale='utc' format='mjd' value=50002.0>], dtype=object)
np.add.reduce(d)
OperandTypeError                          Traceback (most recent call last)
.
.
.
   1322         if not isinstance(other, TimeDelta):
-> 1323             raise OperandTypeError(self, other, '+')
.
.
.
OperandTypeError: Unsupported operand type(s) for +: 'Time' and 'Time'
```

While in more recent versions:
```
np.__version__
# '1.11.0.dev0+6e067b3'
d = Time([50001, 50002], format='mjd')
np.array(d)
# array(<Time object: scale='utc' format='mjd' value=[ 50001.  50002.]>, dtype=object)
np.add.reduce(d)
# <Time object: scale='utc' format='mjd' value=[ 50001.  50002.]>
```

**Comment by mhvk** [comment]
Actually, it does mean that behaviour changed for another class we have, for which addition does not raise an error. I don't really feel it is very important to keep our behaviour, but this does suggest it may be important for other users:
```
d = TimeDelta([1, 2, 3], format='jd')
# in 1.10
np.array(d)
# array([<TimeDelta object: scale='None' format='jd' value=1.0>,
#        <TimeDelta object: scale='None' format='jd' value=2.0>,
#        <TimeDelta object: scale='None' format='jd' value=3.0>], dtype=object)
np.sum(d)
# <TimeDelta object: scale='None' format='jd' value=6.0>
# in 1.11
np.array(d)
# array(<TimeDelta object: scale='None' format='jd' value=[ 1.  2.  3.]>, dtype=object)
np.sum(d)
# <TimeDelta object: scale='None' format='jd' value=[ 1.  2.  3.]>
```

**Comment by njsmith** [comment]
I at least am surprised by this... is it easy to bisect?

On Tue, Mar 8, 2016 at 2:25 PM, Marten van Kerkwijk
<notifications@github.com> wrote:
> Actually, it does mean that behaviour changed for another class we have, for
> which addition does not raise an error. I don't really feel it is very
> important to keep our behaviour, but this does suggest it may be important
> for other users:
>
> d = TimeDelta([1, 2, 3], format='jd')
> # in 1.10
> np.array(d)
> # array([<TimeDelta object: scale='None' format='jd' value=1.0>,
> #        <TimeDelta object: scale='None' format='jd' value=2.0>,
> #        <TimeDelta object: scale='None' format='jd' value=3.0>],
> dtype=object)
> np.sum(d)
> # <TimeDelta object: scale='None' format='jd' value=6.0>
> # in 1.11
> np.array(d)
> # array(<TimeDelta object: scale='None' format='jd' value=[ 1.  2.  3.]>,
> dtype=object)
> np.sum(d)
> # <TimeDelta object: scale='None' format='jd' value=[ 1.  2.  3.]>
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Nathaniel J. Smith -- https://vorpus.org

**Comment by seberg** [comment]
Just wondering, is there something extra here, some newer astropy version or python 3? Because I tried on python2 + astropy 1.0.3 + numpy 1.11.x and it doesn't seem to happen.

**Comment by mhvk** [comment]
@seberg - I don't have immediate access to python2 + numpy 1.11, but here is a simpler, non-astropy example:
```
class A(object):
    def __init__(self, data):
        self._data = data
    def __getitem__(self, item):
        return type(self)(self._data[item])
    def __len__(self):
        return len(self._data)
    def __add__(self, other):
        return type(self)(self._data + other._data)
    def __repr__(self):
        return "A({})".format(self._data)


d = A([1,2,3])
# on 1.10
np.array(d)
# array([A(1), A(2), A(3)], dtype=object)
np.sum(d)
A(6)
# on 1.11 and master
np.array(d)
# array(A([1, 2, 3]), dtype=object)
np.sum(d)
# A([1, 2, 3])
```

**Comment by mhvk** [comment]
Now tried a bisection (following https://github.com/astropy/astropy/issues/4548#issuecomment-178145581; thanks @njsmith, learned something new!). To blame seems to be #7266.

**Comment by mhvk** [comment]
cc @ahaldane since he wrote #7266.

**Comment by njsmith** [comment]
And #7266 was backported here: 545d53b45e7b62bb1a77, making this a 1.11 regression.

@charris: possibly we should revert 545d53b and worry about fixing this properly in master?

**Comment by ahaldane** [comment]
We can consider reverting for 1.11, but in any case I see the fix for master.

My mistake was to combined two cases that were subtly different: If `PyArray_DTypeFromObjectHelper` gets an object which is not sequence-like, it should give back `NPY_OBJECT`, but if it is sequence like  (itt defines `__len__`) but `__len__` fails, it should give back `NULL` instead. The mistake was to also return `NPY_OBJECT` in the latter case.

**Comment by ahaldane** [comment]
Never mind on my last comment, the bug was actually much more subtle. Overall #7266 was the right idea, but I was missing a call to `PyErr_Clear()`. See #7397

**Comment by njsmith** [comment]
Leaving to remind us that it needs a 1.11 backport.

**Comment by charris** [comment]
Backported in #7401.
