### ISSUE TITLE
np.bool_.__index__ should error

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#7395]
`operator.index` correctly raises an error on boolean arrays:

```
In [6]: operator.index(np.array(True))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a4163d1794ac> in <module>()
----> 1 operator.index(np.array(True))

TypeError: only integer arrays with one element can be converted to an index
```

But on a boolean scalar, it incorrectly succeeds:

```
In [7]: operator.index(np.bool_(True))
Out[7]: 1
```

The latter should be an error (possibly with some deprecation period).

**Comment by emilienkofman** [comment]
Hi,

Just to be clear, is this the expected behavior that it raises an error since coercing the built-in bool to int with index doesn't:

```python
>>> import numpy as np
>>> from operator import index
>>> index(True)
True
>>> index(np.bool(True))
True
>>> index(np.bool_(True))
1
```

It's a bit difficult to read `numerictypes.py`, but I guess it's where I should be looking? where is the `bool_.__index__` supposed to be defined?

**Comment by ewmoore** [comment]
It's defined in [numpy/core/src/multiarray/scalartypes.c.src](https://github.com/numpy/numpy/blob/947b023a4999ec879b745c3e7b903d16d9ae65a1/numpy/core/src/multiarray/scalartypes.c.src#L2831).

**Comment by njsmith** [comment]
> Just to be clear, is this the expected behavior that it raises an error since coercing the built-in bool to int with index doesn't

In regular python, bools barely even exist as their own type -- bool is a thin subclass of int, and `True` and `False` are just copies of `1` and `0` that have a special repr. Aside from their repr they act exactly like regular `int`s; for example, `list[True]` is identical to `list[1]`. Numpy intentionally diverges from this behavior: numpy bools do *not* subclass from int, and act very differently in contexts like indexing.

In addition, the different behavior between `np.bool_(True)` and `np.array(True)` is a bug because these two objects are generally supposed to be interchangeable.

I guess fixing `np.bool_` could be confusing to some users who don't necessarily realize that the things they are working with *are* `np.bool_` objects rather than regular `bool`s, so probably it would be good to double check with the mailing list and give folks there a chance to object (most don't read the bug tracker). But I think requiring the explicit cast to int is almost certainly the right thing.

**Comment by dsaumyajit007** [comment]
Has this bug been fixed or is it still open? I am a new contributor and I have been looking for some easy bug fixes. Is this a good place to start?
