### ISSUE TITLE
numpy.in1d returns incorrect value in first element when using assume_unique option

### ISSUE THREAD

**Issue by jmidwint** [numpy/numpy#7400]
I am getting a different and incorrect value for the first element comparison when using the "assume_unique" option in numpy.in1d when comparing two 1D arrays. 

>>> mask = np.in1d(sum_array1, sum_array2)
>>> mask
array([**False**, False, False, ...,  True, False, False], dtype=bool)

>>> mask = np.in1d(sum_array1, sum_array2, assume_unique=True)
>>> mask
array([ **True**, False, False, ...,  True, False, False], dtype=bool)

NOTE: The first value in mask is incorrect when I used the "assume_unique" option. As far as I can tell the other values are ok. 

>>> sum_array1.shape
(10000,)
>>> sum_array2.shape
(200000,)
>>> sum_array1
array([ 166.25097656, -131.        ,  -72.66274261, ..., -153.37646484,
       -154.26272583, -248.20391846], dtype=float32)
>>> sum_array2
array([ -67.80783844, -155.38824463,   -6.23921967, ..., -290.447052  ,
        179.6862793 ,  205.69413757], dtype=float32)
 

>>> np.version.version
'1.10.1'
>>> print(sys.version)
2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by jaimefrio** [comment]
Are you sure the arrays don't have any repeated values?

**Comment by jmidwint** [comment]
No, I am not guaranteed that each element in each array is unique, but since dealing with floats it was thought they could be mostly unique. Is it essential that all elements in each array be exactly unique?

**Comment by jaimefrio** [comment]
That's the whole idea of that flag: if you know your values are unique and not repeating, let us know and we will use that information to speed things up. But they have to be really unique or results will be wrong, If you could run `assert np.unique(x).shape == x.shape` for both your arrays, we can be sure and close this.

**Comment by jmidwint** [comment]
Doh! My bad! I see I have misunderstood the documentation on that flag. I can see that my elements are not always unique every time. We can close this.  
Curious though on your take on putting in a check for uniqueness and raising an exception inside this numpy function (to protect from misuse) or would such a check slow things down and be better off being done by users of the function before invoking?

**Comment by jaimefrio** [comment]
It is a performance flag. When `assume_unique = False`, the first thing `in1d` does is call `unique` on both arrays, an operation that probably takes about half of the execution time. So if you know there are no duplicates, you can make this call about 2x faster with this flag. Doing a uniqueness check would ruin that advantage. Also note that It seems unlikely that a uniqueness check followed by a call to `in1d` with `assume_unique = True` would be faster than a call with `assume_unique = False`, so this flag is mostly for cases where duplicates **cannot** happen, not simply **don't** hapen.

**Comment by jmidwint** [comment]
Thanks.
