### ISSUE TITLE
[Long arithmetics] Element-wise involution fails

### ISSUE THREAD

**Issue by ivanychev** [numpy/numpy#7405]
Hey there. I've noticed a bug related to long arithmetic operations. Attached a screenshot below.

NumPy v.1.10.4
Python 3.5
OS X 10.11.4

<img width="1111" alt="2016-03-10 16 47 47" src="https://cloud.githubusercontent.com/assets/5954224/13671392/c5e952ea-e6e0-11e5-9b92-6fb38662a532.png">

Custom involution and the operation that is performed to `numpy.int64` types do well. Now look at the last two cells with elementwise involution. It appears to be that NumPy fails to compute the last value in the resulting array correctly.

**Comment by pv** [comment]
The computation appears to be performed in floating point for some reason `np.int64(15.**15.) == 437893890380859392`.

**Comment by ewmoore** [comment]
For arrays, numpy calls the C `pow` function for integral types ([ref](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/loops.c.src#L918)) for scalars, it calls a power routine that uses integer multiplication ([ref](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/scalarmath.c.src#L222)).  Looks to me as though this is a long latent bug, as the technique used for scalar power (added in 2006) should probably be used for arrays as well.
