### ISSUE TITLE
np.linalg.norm limited by data type 

### ISSUE THREAD

**Issue by mingleizhao** [numpy/numpy#7413]
numpy 1.10
python 3.5

In [392]: np.linalg.norm(np.array([  0,   0, 256]))
Out[392]: 256.0

In [393]: np.linalg.norm(np.array([  0,   0, 256], dtype=np.int16))
Out[393]: 0.0

In [394]: np.linalg.norm(np.array([  0,   0, 256], dtype=np.int32))
Out[394]: 256.0

**Comment by omtcyf0** [comment]
Can you elaborate please?

From my perspective the overflow happening here is totally logical.

**Comment by mingleizhao** [comment]
In this case, the norm function returns a float scala. In my opinion, it should take care of the overflow, just like the square operation shown below. I understand why it does not, but it's not convenient for the users and is not documented. 

In [3]: a = np.array([ 0, 0, 256], dtype=np.int16)

In [4]: a**2
Out[4]: array([0, 0, 0], dtype=int16)  # overflow here is expected

In [6]: a[2]**2
Out[6]: 65536  # no overflow

In [7]: type(a[2]**2)
Out[7]: numpy.int64

In [8]: type(a[2])
Out[8]: numpy.int16

**Comment by njsmith** [comment]
Given that `norm` is casting the values to float regardless (as seen from the final output being a float), I agree it seems weird and surprising that intermediate computations overflow.

**Comment by charris** [comment]
In 1.11.0 all norms are computed in floating point.
```
In [1]: np.linalg.norm(np.array([ 0, 0, 256]))
Out[1]: 256.0

In [2]: np.linalg.norm(np.array([ 0, 0, 256], dtype=np.int16))
Out[2]: 256.0

In [3]: np.linalg.norm(np.array([ 0, 0, 256], dtype=np.int32))
Out[3]: 256.0
```

**Comment by njsmith** [comment]
So this can be closed?

**Comment by charris** [comment]
Probably, but I was waiting for a response.

**Comment by mingleizhao** [comment]
Good to know. Thank you!
