### ISSUE TITLE
numpy.angle shouldn't return negative values according to documentation?

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [numpy/numpy#7426]
I was surprised that numpy.angle returns negative values.

The documentation for [numpy.angle](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.angle.html) says:

> The **counterclockwise** angle from the positive real axis on the complex plane ..

This means the values should go from 0 to (2pi).

But that is not what happens. For example: 

> numpy.angle( 1 - 1j )
> **-0.78539816339744828**

I believe this should be that value plus (2pi) or **5.497787143782138**

If I am wrong, I believe the documentation should be clarified to give the intended output range as **(-pi, +pi]**

**Comment by makeyourownneuralnetwork** [comment]
anyone want to discuss ways to fix this? I don't have the coding skills but could help with the maths side...

**Comment by ewmoore** [comment]
The right fix is probably to just change the docs.  The function is just a wrapper around `np.arctan2`.

**Comment by leofang** [comment]
@eric-wieser @makeyourownneuralnetwork the doc doesn't seem to be fixed yet. I'd recommend reopen the issue until it's actually fixed.
