### ISSUE TITLE
`lingalg.norm` documentation reference to the source is wrong

### ISSUE THREAD

**Issue by omtcyf0** [numpy/numpy#7429]
`linalg.norm` [documentation](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.linalg.norm.html) (numpy-dev version) seems to point the source of the function to `numpy/linalg/linalg.py#L1976-L2221` while it should be `numpy/linalg/linalg.py#L1976-L2224`.

Since I've no developer experience at all with numpy I'm not sure how the docs are generated and how this should be fixed.

**Comment by charris** [comment]
Indeed. @pv Is this done by numpydoc?

**Comment by charris** [comment]
Or perhaps the documentation is out of sync with master.

**Comment by omtcyf0** [comment]
@charris might aswell be.

These two, for example, are referring to wrong SLocs (SourceLocations), too:

* https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.all.html
* https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.any.html

**Comment by pv** [comment]
It's just out of sync, there's no build automation

**Comment by omtcyf0** [comment]
@pv ah, I see. Sorry then. Since I'm not experienced with the numpy codebase and project itself, I didn't know that.

How often is the documentation updated and why is there no CI bot/something similar?
