### ISSUE TITLE
doc/numpy/user/basics.rec.html example code typo

### ISSUE THREAD

**Issue by elronayellin** [numpy/numpy#7444]
'foo' should be 'bar', ie, the second field name, in the third code block:

\>\>\> y = x['foo']
\>\>\> y
array([ 2.,  3.], dtype=float32)

**Comment by njsmith** [comment]
Would you like to submit a pull request?

**Comment by simongibbons** [comment]
Looks like this is already fixed on master. https://github.com/numpy/numpy/commit/e5d61d6f946ef75b822d937b801a02f64736e53f

It would be nice to get something setup that will automatically build the documentation

**Comment by njsmith** [comment]
@simongibbons: Yeah, that would be really nice :-). In theory it shouldn't be too hard to have a travis job that builds the docs and rsyncs them to the server, but of course someone would have to do the work of making this happen...

Anyway, sounds like this particular bug can be closed -- thanks for checking!
