### ISSUE TITLE
Some arrays for which `arr.size * arr.dtype.itemsize > max_ssize_t` currently not recognized as invalid

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#7451]
The example is a little convoluted, but fails consistently:

```Python
import numpy as np
from numpy.lib.stride_tricks import as_strided
a = np.ones((1, 1))
len_ = np.iinfo(np.intp).max // 2 + 1
b = as_strided(a, shape=(1, len_), strides=(0, 0))
# next line segfaults
b.ravel()
```

Not sure what may be going on, but it sure doesn't happen if the strided view is much smaller.

**Comment by mhvk** [comment]
Odd, does not segfault for me (1.10.4, 1.11.0.dev0+2ec0db0; Debian amd64).

**Comment by jaimefrio** [comment]
Of course you don't, because I left the offending line out: a call to `b.ravel()` at the end... Have edited my original post.

**Comment by seberg** [comment]
There is another odd thing here (and I get a MemoryError if I avoid it). The array should not be created in the first place. I guess it *might* be a separate issue though. For the original array `arr.size * arr.dtype.itemsize` is larger then `ssize_t` here (my old 1.8.2 fails on `b =` line).
AFAIK, that is not considered a valid array.

**Comment by mhvk** [comment]
> Of course you don't, because I left the offending line out: a call to `b.ravel()` at the end... Have edited my original post.

Indeed, now it "works"...

**Comment by seberg** [comment]
Git blame suggests the offending commit is 1475cfa46356c63c337b2d3d5903be2451dbb9c5, the `sd * size` later on, will go off into integer wraparound and should be checked (possibly start off with size = sd, maybe with an sd > 0 check -- not sure that can happen or not, somewhat think not, but...). Anyway, this also segfaults for copy, etc. as well, so nothing to do with ravel, just with malloc'ing empty arrays when the array is larger then legally possible.

**Comment by jaimefrio** [comment]
I guess we have a winner then... The following fails with a memory error:

```Python
from numpy.lib.stride_tricks import as_strided
a = np.ones((1, 1))
len_ = np.iinfo(np.intp).max // 2
b = as_strided(a, shape=(1, len_), strides=(0, 0))
b.ravel()
```

The difference is that `(np.iinfo(np.intp).max // 2 + 1) * 8` is a power of two, so when it overflows an `int64`, it results in a calculated array size of zero bytes. `np.iinfo(np.intp).max // 2 * 8` is a power of two minus one, and thus has a binary representation full of ones, so even though it also overflows, it results in some ridiculously large amount of memory that cannot possibly be allocated.

**Comment by jaimefrio** [comment]
Ah, hadn't seen your message when I sent mine. Yes, that seems to be it.
