### ISSUE TITLE
Clarify branch cut for arccos

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7474]
The doc for `np.arccos` goes into the detail of specifying the branch cut:

```
arccos is a multivalued function: for each x there are infinitely many numbers z such that cos(z) = x.
The convention is to return the angle z whose real part lies in [0, pi].
```

(which, unsurprisingly, matches the C standard).  This is not a complete definition though: it does not specify what is the output for a real input `x` of absolute value greater than 1, in which case both `arccosh(x) * 1j` and `-arccosh(x) * 1j` have a cosine equal to `x`.  From a quick test it seems that the latter is chosen, but it'd be nice if this was specified.

**Comment by pv** [comment]
In C99, the sign of zero determines which side of branch cut you are on.
28.3.2016 7.06 "Antony Lee" <notifications@github.com> kirjoitti:

**Comment by anntzer** [comment]
Fair enough, I guess this is implicit in the doc ("is continuous from above on the former and from below on the latter.")  Feel free to close this.
