### ISSUE TITLE
Confusing error message when mixing seq and slice indexing during sub-array assignment

### ISSUE THREAD

**Issue by wgm2111** [numpy/numpy#7479]
I got an odd error message during sub-array assignment when using a combination of a slice and sequence indexing.  I know about the closed issue on [mixed indexing](https://github.com/numpy/numpy/issues/7030).  The behavior is fine, but the error message gave the same shape that I was _wrongly_ expecting.  

So, the `ValueError` said that arrays of the same shape could not be broadcast.

```
import scipy as sp
a = sp.zeros((3, 4, 5))
b = sp.ones((4, 5))

I = sp.array([0, 1, 3])

b[:, I] = a[0, :, I]
```

This code raises the following ValueError:

ValueError: shape mismatch: value array of shape (3,4) could not be broadcast to indexing result of shape (3,4)

**Comment by seberg** [comment]
Yeah, there is transposing going on internally, and for the error reporting, the transposing is not fully undone. It is not difficult to fix, but a bit tedious, so never got around it (the right hand side gets transposed as well, but the original right hand side shape is reported correctly).
Probably more elagent to solve with the extra stuff necessary for `oindex`, though I guess that time schedule is very open.

**Comment by seberg** [comment]
Closing in favor of gh-5710
