### ISSUE TITLE
numpy.loadtxt with skiprows much slower than custom generator

### ISSUE THREAD

**Issue by jauerb** [numpy/numpy#7480]
I noticed when trying to load somewhat large text files (~12MB) that using the skiprows option of numpy.loadtxt is much slower than implementing the same thing with a custom generator

For example this take on average ~1.2s per invocation on my laptop

``` python
times = []
for _ in range(30) :
    s = time.time()
    tmp = np.loadtxt("test.txt",  skiprows=1001)
    times.append(time.time() - s)

print np.mean(times)
```

whereas this takes ~0.4s per invocation

``` python
def my_generator(fname, skiprows=0) :
    f = open(fname, 'r')
    for i,line in enumerate(f) :
        if i >= skiprows :
            yield line

times = []
for _ in range(30) :
    s = time.time()
    tmp = np.loadtxt(my_generator("test.txt", skiprows=1001))
    times.append(time.time() - s)

print np.mean(times)
```

**Comment by saintsfan342000** [comment]
This isn't really and issue.  It is well documented that `np.loadtxt` is just about as slow as it gets for file I/O.  See, for example, [this blog entry from Wes Mckinney](http://wesmckinney.com/blog/a-new-high-performance-memory-efficient-file-parser-engine-for-pandas/).   `np.genfromtxt` is ~4x faster than `np.loadtxt` in my experience.  And if you have pandas, then `pandas.read_csv` or `pandas.read_table` is another 4-5x faster than `np.genfromtxt`.

**Comment by seberg** [comment]
Closing, `loadtxt` is now fast.
