### ISSUE TITLE
BUG: Masked array transpose doesn't return view

### ISSUE THREAD

**Issue by cpelley** [numpy/numpy#7483]
Currently, requesting the transpose of a masked array does not return a true view of a masked array (not like reshaping).  In our usage, we transpose both mask and data separately as a workaround.

See the following gist:

https://gist.github.com/cpelley/894d1f2123868ed87c4ab435db2624ea#file-masked_transpose_bug-ipynb

**Comment by eric-wieser** [comment]
This came up in https://github.com/numpy/numpy/pull/8441#discussion_r97069917, where it seems that `transpose` didn't require the result to be a view

**Comment by cpelley** [comment]
Thanks @eric-wieser :)
