### ISSUE TITLE
ENH: Consider adding numpy.unit_basis_vector for convenience

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#7485]
Described here: http://stackoverflow.com/questions/11975146/efficient-unit-basis-vector-with-numpy

**Comment by jpreiss** [comment]
This issue was closed by its creator, but IMO constructing a basis vector is a really fundamental operation, and it feels weird to require the SciPy signal processing module to get it. I would love to see this function in NumPy.

**Comment by NeilGirdhar** [comment]
I agree, but maybe find some support?

**Comment by NeilGirdhar** [comment]
If there's support, I'm okay with reopening this.

**Comment by rgommers** [comment]
This doesn't belong in NumPy. The SO post also has a couple of trivial functions to do this; we don't really want such simple utility functions in NumPy, because there's a huge amount of those one could propose, and they add little.

**Comment by NeilGirdhar** [comment]
Okay, thanks for the quick update!
