### ISSUE TITLE
types in numpy/doc/basics.py are missing uintc and uintp dtypes

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7486]
All's in the title.
See http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html

**Comment by jaimefrio** [comment]
There is also no mention of `byte` (and `ubyte`).

**Comment by badhrink** [comment]
I'm interested in taking up this issue, but I'm having a hard time in finding out ranges of uintc, uintp, byte and ubyte. Can you guys give me any pointers on where i can find this info?

TIA

**Comment by charris** [comment]
I expect `uintc` and `uintp` vary with the OS and platform, although `uintc` is almost always 32 bits in practice -- I know of no exceptions on 32 & 64 bit systems. For the others
```
In [1]: iinfo(ubyte)
Out[1]: iinfo(min=0, max=255, dtype=uint8)

In [2]: iinfo(byte)
Out[2]: iinfo(min=-128, max=127, dtype=int8)
```

**Comment by seberg** [comment]
I think there are values for the non-unsigned variants, so you can just steal those and make them unsigned.

**Comment by sethtroisi** [comment]
Fixed in https://github.com/numpy/numpy/pull/11837
