### ISSUE TITLE
np.random issue with quality of randomness

### ISSUE THREAD

**Issue by mattgara** [numpy/numpy#7497]
I've written a very simple implementation of simulated annealing mainly using the np.random.randn and np.random.uniform functions, but there is either something I've overlooked and wrong with the implementation, or there is a serious issue with the quality of random numbers generated by numpy, at least with these two methods. I think the latter is more probable as I've stared and tried to find bugs in this code for hours but have come up with none. I apologize in advance if it is indeed an issue with the implementation, but I feel it is my duty to report this as I can find nothing wrong with it.

Please consider these two python modules:

sa.py:
```
#!/usr/bin/python

import numpy as np

class SimulatedAnnealer:

    def __init__(self,schedule,nvar,nsamp=100):
        self.nsamp = nsamp
        self.nvar  = nvar
        self.state = np.random.randn(nsamp,nvar)
        self.schedule    = schedule

    def _run(self,b,niter):
        for _ in xrange(niter):
            new_state = self.state + np.random.randn(*self.state.shape)
            old_loglikelihood = self.loglikelihood(self.state)
            new_loglikelihood = self.loglikelihood(new_state)
            lalpha = b*(new_loglikelihood - old_loglikelihood)
            idx = np.log(np.random.uniform(self.nsamp,1)) < lalpha
            self.state[idx] = new_state[idx]

    def run(self,niter=1000):
        for ib,b in enumerate(self.schedule):
            print ' Performing schedule item:', ib, ' b: ', b
            self._run(b,niter)
```
test_sa.py:
```
#!/usr/bin/python

from sa import SimulatedAnnealer
import numpy as np

class TestSa(SimulatedAnnealer):

    def __init__(self,nsamp):
        SimulatedAnnealer.__init__(self,np.linspace(0.1,1,10.),1,nsamp)

    def loglikelihood(self,state):
        return -1./(2*5.)*np.square(state-1.)

if __name__ == "__main__":

    tsa = TestSa(20)
    tsa.run()
    print np.mean(tsa.state), np.std(tsa.state)
```

Changing the number of concurrent running SA chains from TestSa(20) to TestSa(1) improves SA by a lot, where it should have no effect. The only explanation I can think of is there is a problem with how the random numbers are drawn, they are not independent.

This is using numpy 1.9.2. Installed through pip.

**Comment by seberg** [comment]
Random number generation is not thread safe. You have to run each thread with its own `RandomState` instance with a different initial point.

**Comment by seberg** [comment]
Sorry, first glance thought that you have been using threads, but I am sure this is a bug in the code somewhere to be honest.

**Comment by charris** [comment]
@seberg that would be my guess. Simulated annealing is delicate and hard to get right, which is one reason it deprecated in scipy in favor of basinhopping. IIRC, there is a better simulated annealing implementation out in the wild.

**Comment by rkern** [comment]
Can you describe what results you are getting and what results you expect to see? I don't immediately know what "improve" means here.

**Comment by mattgara** [comment]
@rkern: Sure, this simple SimulatedAnnealer is written to find a maximum in the loglikelihood of the function f(x) = -1./(2*5.)*np.square(x-1.), which is a 1d-gaussian with mean 1.0. It should be clearly maximized at exactly 1.0, meaning the closer the Annealer finds the value to 1.0, the better. Increasing the concurrent chains from 1 to 2 or higher seems to degrade the quality.

**Comment by pv** [comment]
First you need to explain why you are pulling random numbers from range `[1,nsamp]` instead of `[0,1]` via np.uniform.

**Comment by rkern** [comment]
Indeed, that makes them equally poorly-performing. :-)

**Comment by pv** [comment]
Closing, seems to be a bug in the example code above.

**Comment by mattgara** [comment]
Oh I see thank you, that is indeed an issue with my code. Thanks!
