### ISSUE TITLE
Test failure on openblas buildbot - significance?

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#7500]
@xianyi kindly started to run the numpy tests against OpenBLAS master on the OpenBLAS buildbots:

http://build.openblas.net/builders

This found a test failure on numpy on several (maybe all) kernels:

http://build.openblas.net/builders/full-sandybridge-linux/builds/23/steps/shell/logs/stdio
http://build.openblas.net/builders/full-nehalem-linux/builds/27/steps/shell/logs/stdio
http://build.openblas.net/builders/full-core2-linux/builds/27/steps/shell/logs/stdio

```
======================================================================
FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arccosh'>, [-1, 0.5], [1j, 1j], 1, -1, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/2.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/2.7/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 1748, in _check_branch_cut
    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))
  File "/opt/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: (array([  0.00000000e+00+3.14159265j,   1.11022302e-16-1.04719755j]), array([  4.71216091e-07+3.14159218j,   1.28119737e-13+1.04719755j]))
```

Is this a significant failure?  Or is it within reasonable precision bounds?

**Comment by pv** [comment]
May indicate a bug in libc cacosh on that machine. Unrelated to linalg, however.

**Comment by xianyi** [comment]
@pv , how could I remove this error? Upgrade libc?

**Comment by matthew-brett** [comment]
I'm sure the problem is that you are using the manylinux docker image for doing the tests.  That (deliberately) has a very old libc.

Would it be easy to use an ubuntu 12 or 14 docker image for the tests instead?   Of course it would need Python as well as the usual build tools, but that shouldn't be too hard to organize.    For example, I believe this is the current travis-ci docker image : https://hub.docker.com/r/travisci/worker/ (current tag appears to be packer-1457060342) .
