### ISSUE TITLE
typo in the doc

### ISSUE THREAD

**Issue by davefontaine** [numpy/numpy#7502]
Hi. On the following page:

http://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html

in the third text box 'foo' should be 'bar'. You reference the second column which is a float with column header 'bar'.

{code}
>>> y = x['foo']
>>> y
array([ 2.,  3.], dtype=float32)
>>> y[:] = 2*y
>>> y
array([ 4.,  6.], dtype=float32)
{code}

**Comment by seberg** [comment]
This already has been fixed, just not pushed yet.

**Comment by seberg** [comment]
To be clear, that website is version 1.10, so the new versions will be correct.
