### ISSUE TITLE
The new range handling method will raise ValueError for arrays including NaN

### ISSUE THREAD

**Issue by hopehhchen** [numpy/numpy#7503]
This issue appears after one of the latest changes to function_base.py (around Row 550 in 127eb9e on March 16, 2016). Resetting the range to array minimum and maximum by using a.min() and a.max() will raise ValueError: 'range parameter must be finite.' if the array includes NaN. Before the change, the codes assigned a pair of range parameters only when they were included in the input explicitly.

**Comment by seberg** [comment]
To note for everyone, this is np.histogram.

@hopehhchen can you explain what you expect? It seems to me that the old behaviour returned useless results, so I am not sure I wouldn't consider the error an improvement?

**Comment by seberg** [comment]
For anyone else who might look at this, this seems to be the old behaviour  (in 1.8.2):
```
In [8]: np.histogram([1, 2, np.nan, 1e10, -1e19])
Out[8]: 
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]))
```
which seems nonsense, the numbers don't even add up.

**Comment by hopehhchen** [comment]
@seberg Thanks for the looking at this as well. Sorry I wasn't being super clear. I'm not suggesting going back to roll back, but just thinking if, instead, using np.nanmin(a) and np.nanmax(a) in the new code would make more sense. Doing this would save the users extra troubles to remove the NaNs or to manually set `range = (np.nanmin(array), np.nanmax(array))`.

**Comment by leewalsh** [comment]
I like @hopehhchen's suggestion of using the `nan` functions, though it's a little bit more of a change in behavior. And for @seberg's example an error is probably preferable.

However, this issue breaks cases when `bins` is a sequence. In that case, I believe that `range` should be determined using `bins.min()` and `bins.max()` (or maybe `bins[0]` and `bins[-1]`).

That is, these two calls should be equivalent:

    In [9]: np.histogram([1, 2, np.nan, 1e10, -1e19], bins=[0, 1, 2])
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-9-37e33a638eb7> in <module>()
    ----> 1 np.histogram([1, 2, np.nan, 1e10, -1e19], bins=[0, 1, 2])

    /usr/local/lib/python2.7/site-packages/numpy/lib/function_base.pyc in histogram(a, bins, range, normed, weights, density)
        503     if not np.all(np.isfinite([mn, mx])):
        504         raise ValueError(
    --> 505             'range parameter must be finite.')
        506     if mn == mx:
        507         mn -= 0.5

    ValueError: range parameter must be finite.

    In [10]: np.histogram([1, 2, np.nan, 1e10, -1e19], bins=[0, 1, 2], range=(0, 2))
    Out[10]: (array([0, 2]), array([0, 1, 2]))

**Comment by seberg** [comment]
I think if bins are used, range is probably not used in any case? Which seems like the right behaviour to me.
Filtering out NaNs, sounds like it might be a good option, whether or not it should be default, I don't know. Maybe the default should just be to error, and ask the user to specfiy "ignore_nan=True" or something.
Or frankly maybe it is best to just error with "histogram does not support NaN, use blabla to remove NaNs first."? @leewalsh if you are interested in this issue, we always welcome pull requests!

**Comment by seberg** [comment]
Ah, sorry, missed that. So I guess right now range actually does matter and will filter NaNs (and probably Infs, etc.)? Seems not to matter in older versions. It might be good to double check how this behaviour has changed over the last few versions.

**Comment by johnarban** [comment]
I am just seconding the issue @hopehhchen raised. I am using version 1.11.0
A minimal example is
```python
bins = np.asarray([0,2,4,6,8,10])
values = np.asarray([1,2,4,6,4,6,7,8,5,2,2,4,6,np.nan,7,5,4,22,3,57,8,9,6,4,3,2,1,46,8,9])
# broken version. Worked in previous stable release in conda
h, bins = np.histogram(values, bins=bins)
# now this is required. 
h, bins = np.histogram(values, bins=bins, range=(bins.min(),bins.max()))
```

**Comment by tritemio** [comment]
This error propagates to matplotlib `plt.hist`. An array containing NaN will raise an error even if the full bins array is specified. Adding `range=(bins.min(),bins.max())` works but is extremely verbose.

**Comment by syrte** [comment]
Can we use `np.nanmax` and `np.nanmin` to find the range for `histogram`?
I mean to replace 
```
mn, mx = a.min() + 0.0, a.max() + 0.0
```
by 
```
mn, mx = np.nanmin(a) + 0.0, np.nanmax(a) + 0.0
```
in `function_base.py`:

```python
def histogram(a, bins=10, range=None, normed=False, weights=None,
              density=None):
...
    # Do not modify the original value of range so we can check for `None`
    if range is None:
        if a.size == 0:
            # handle empty arrays. Can't determine range, so use 0-1.
            mn, mx = 0.0, 1.0
        else:
            mn, mx = a.min() + 0.0, a.max() + 0.0
...
```

Is there any reason we can not do it like this? e.g. performance reason?
As I see, if I do care the performance I shall give a `range` value myself.

**Comment by eric-wieser** [comment]
Note that we could still consider using `nanmin` and `nanmax` to compute the range when no bin edges are given

**Comment by michaelklachko** [comment]
I just got this error even though there are no NaN values in my array:

```
print np.argwhere(np.isnan(array))
[]

array_hist, _ = np.histogram(array, range=(0.0, 1.0))
print array_hist
[ 8461  4600  4306  4344  3827  3636  3734  3607  4399 12718] 

print array    //all values appear to be normal (too large to show here)

plt.hist(train_acc_per_sample, bins='sqrt', range=(0.0, 1.0))

/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
Traceback (most recent call last):
  File "/home/michael/main.py", line 212, in <module>
    class.train()
  File "/home/michael/code/__init__.py", line 339, in train
    plt.hist(array, bins='sqrt')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3081, in hist
    stacked=stacked, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1898, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 6195, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 670, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.

Process finished with exit code 1
```

I'm using Numpy version 1.14, matplotlib 2.0.2

**Comment by eric-wieser** [comment]
Looks like a matplotlib bug. Am I right in thinking that this works:

```
array_hist, _ = np.histogram(array, bins='sqrt', range=(0.0, 1.0))
```
And this fails:
```
plt.hist(array, bins='sqrt', range=(0.0, 1.0))
```

**Comment by eric-wieser** [comment]
Your backtrace doesn't match the code you're running:
```
plt.hist(array, bins='sqrt')
```
vs
```
plt.hist(train_acc_per_sample, bins='sqrt', range=(0.0, 1.0))
```

**Comment by michaelklachko** [comment]
Oh yes, I added range argument after the fact, to see if it helps. Original error happened without range argument in plt.hist call. Let me edit the post.

**Comment by eric-wieser** [comment]
Did it help? It should have.

**Comment by michaelklachko** [comment]
Yes, it helped. This time there were nan values in the array, and I got the following warnings:

```
/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py:780: RuntimeWarning: invalid value encountered in greater_equal
  keep = (tmp_a >= first_edge)
/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py:781: RuntimeWarning: invalid value encountered in less_equal
  keep &= (tmp_a <= last_edge)
```
but the code execution continued after that.
