### ISSUE TITLE
linalg.svd core dumped (stack smashing detected) for specific matrices dimensions

### ISSUE THREAD

**Issue by Thomas-Z** [numpy/numpy#7520]
Hello,

Understand that my mathematical knowledge is very limited but I have to work on a program using numpy.linalg.svd (actually scipy.linalg.svd but with full_matrices=0 so it's a direct call to the numpy svd function).

After many tests I ended up with this simple program which reveals what appears to be a bug to me.

```python
import numpy as np

x = 500
y = 161
b = np.floor(np.random.rand(x, y))
np.linalg.svd(b, full_matrices=False, compute_uv=True)
```

If 'y' is 161, 162, 163 it will 100% fail and crash. Using a variety of other values for both 'x' and 'y' is working just fine (50234 and 164 will work but 50234 and 163 won't).
As far as I know there are no mathematical explanation to this behavior (and I guess it would raise an error if there was).

I tried with Numpy 1.6.1 and the last one (1.11.1) and Python 2.7.3 on Ubuntu 12.04.5 LTS.
Feel free to ask for more details.

Thanks and regards,
Thomas

**Comment by pv** [comment]
Most likely a bug in the lapack/blas libraries shipped with ubuntu 12.04.

**Comment by njsmith** [comment]
What does`np.show_config()` say? You can probably avoid the bug by switching which BLAS you're using (Ubuntu ships several of them).

**Comment by Thomas-Z** [comment]
Thanks for your answers.

I created an Ubuntu 15.10 VM (Python 2.7.10, Numpy 1.8.2) and it works without any problem so you're probably right.

liblapack3 version:
Current: 3.3.1-1
VM: 3.5.0-4

libblas version:
Current: 1.2.20110419-2ubuntu1
CM: libblas3: 1.2.20110419-10

```python
np.show_config()
blas_info:
    libraries = ['blas']
    library_dirs = ['/usr/lib']
    language = f77
lapack_info:
    libraries = ['lapack']
    library_dirs = ['/usr/lib']
    language = f77
atlas_threads_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['blas']
    library_dirs = ['/usr/lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1)]
atlas_blas_threads_info:
  NOT AVAILABLE
lapack_opt_info:
    libraries = ['lapack', 'blas']
    library_dirs = ['/usr/lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1)]
atlas_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
```
If you have any ideas how to make the "current" configuration work without having to install new libraries (not an option for now in my situation) I'm all ears !

**Comment by njsmith** [comment]
You might try Matthew Brett's beta Linux wheels: https://mail.scipy.org/pipermail/numpy-discussion/2016-April/075234.html

They ship their own BLAS/LAPACK rather than relying on the system version, so you may be able to sneak them by. If your system LAPACK is broken, as it appears to be, then you really don't have many options that don't involve installing a new library in one sense or another.

Note that there is currently some corner case bug in those wheels on certain AMD machines. Once this is sorted out (hopefully in the next few days), then those wheels will become the default/official ones you get by doing `pip install numpy` on Linux.

**Comment by Thomas-Z** [comment]
Thanks once more for your help, I'll take a look into this.
