### ISSUE TITLE
Feature request: create ndarray.unique which calls np.unique(ndarray)

### ISSUE THREAD

**Issue by stsievert** [numpy/numpy#7524]
While using NumPy I used `x.unique` naturally when `x` was an ndarray. This made intuitive sense and goes with natural language.

To be specific, this is the functionality I'd like:

``` python
>>> x = np.array([1, 1, 2, 3, 5, 8])
>>> x.unique()
array([1, 2, 3, 5, 8])
```

I looked into making a pull request for this but looks like the ndarray class is in C in the file [arrayobject.c](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arrayobject.c)

**Comment by seberg** [comment]
We are very conservative/hesitant to add new methods to `ndarray`, so I will close this. One could pick it up, but I think it basically needs discussion on the mailing list and not in an issue first.
