### ISSUE TITLE
Error in online documentation for structured arrays

### ISSUE THREAD

**Issue by kmdouglass** [numpy/numpy#7527]
I believe there is an error in the online numpy-1.10.1 documentation (accessed on April 8, 2016) for [structured arrays](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html) related to the first and third code blocks. In the first block, x is defined as:

```x = np.array([(1,2.,'Hello'), (2,3.,"World")],
                        dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])```

Then in the third block, there are the lines:

```
y = x['foo']
y
array([ 2.,  3.], dtype=float32)
```

I think the author intended to write `x['bar']`, not `x['foo']`.

Cheers
kmd

**Comment by maniteja123** [comment]
Thanks for the report. But I suppose it is fixed on master - [this](https://github.com/numpy/numpy/blob/master/numpy/doc/structured_arrays.py) and also #7502 . The website doesn't build with the master and hence contains the error.

**Comment by seberg** [comment]
Thanks both of you.
