### ISSUE TITLE
BUG: Floating exception with np.lexsort

### ISSUE THREAD

**Issue by simongibbons** [numpy/numpy#7528]
import numpy as np
    x = np.linspace(0.0, 1.0, 126).reshape(42, 3)
    np.lexsort(x, axis=2)

Kills python with a `Floating exception (core dumped)` 

This is with python 2.7.8 and with numpy built from both the current master and 1.11.0

I'm running this on RHEL 6 and numpy was compiled with gcc 4.7.2

**Comment by simongibbons** [comment]
Messing around with GDB suggests the culprit occurs during [this call](https://github.com/numpy/numpy/blob/2af06c804931aae4b30bb3349bc60271b0b65381/numpy/core/src/multiarray/item_selection.c#L1444) to `PyArray_IterAllButAxis`

**Comment by charris** [comment]
Also in numpy 1.9.3, so not a regression.

**Comment by simongibbons** [comment]
I think what is going on here is that the call to `PyArray_IterAllButAxis` is occurring before we check that the axis that has been passed into `PyArray_LexSort` actually exists in the array.

`PyArray_IterAllButAxis` doesn't check to see if the axis that has been passed into it exists in the array so when it tries it tries to find the number of elements in the axis it gets a garbage value, which in this case due to how things are laid out in memory is zero.

I assume that this checking isn't done in `PyArray_IterAllButAxis` for performance reasons so I guess the easiest way of fixing this would be to move the axis check to before the iterators are made in `PyArray_LexSort`?
