### ISSUE TITLE
Inconsistent reduction of single value arrays in Windows and Linux using np.int32 or np.int64

### ISSUE THREAD

**Issue by spichardo** [numpy/numpy#7531]
Hi, 

This issue is currently present  when using Anaconda 4.0 X64 both in Windows and Linux, with numpy 1.10.4

From longtime I've been having some issues when slicing/indexing using the same code in Linux or Windows when the array/value for the indexing is not integer at source (i.e, when reading Matlab 7.3 files using h5py), and finally I managed to narrow it to the reduction that takes place when calling np.int32 or np.int64 that reduces the input array to scalar instead of the original array. The code below exemplifies the issue.

```
import numpy as np
OrgArray=np.zeros((1))
MaterialList=np.zeros((500,4))
ValueLine=np.zeros(MaterialList.shape[0]-1)
print np.int32(OrgArray).shape # this will reduce to shape "()" in Windows (reduced to scalar) but in Linux it will reduce to "(1,)"
print np.int64(OrgArray).shape # this will reduce to shape "()" in Linux (reduced to scalar) but in Windows it will reduce to "(1,)"
print np.uint32(OrgArray).shape # this will reduce to "(1,)" in Windows and Linux 
print np.uint64(OrgArray).shape # this will reduce to "(1,)" in Windows and Linux 

try: 
    MaterialList[1:,np.int32(OrgArray)] =ValueLine # this will work in Windows but not in Linux
    print "MaterialList[1:,np.int32(OrgArray)] =ValueLine Succes"

except ValueError as e:
    print "MaterialList[1:,np.int32(OrgArray)] =ValueLine FAILED"
    print e.message
try: 
    MaterialList[1:,np.int64(OrgArray)] =ValueLine # this will work in Linux but not in Windows
    print "MaterialList[1:,np.int64(OrgArray)] =ValueLine Succes"
except ValueError as e:
    print "MaterialList[1:,np.int64(OrgArray)] =ValueLine FAILED"
    print e.message
```

When the test fails, the error message is `shape mismatch: value array of shape (499,) could not be broadcast to indexing result of shape (1,499)`, which I think it should be the correct behavior regardless the integer conversion or the OS being used.

Of course I can simply use OrgArray[0] in the code and it will work either in Linux and Windows, but the issue that different behaviors depending on the integer conversion should not happen in the first place.

Regards

**Comment by seberg** [comment]
Those commands were probably never quite intended for creation of arrays, it is better to use `dtype=...` or `arr.astype(np.intp, copy=False)`, etc. to do this.

On the other hand, we probably could change it by trying to convert to array first, and only then try to make it an integer if it is a 0-D array. Not 100% sure that won't have some other side effects, but it could be done.

**Comment by spichardo** [comment]
Hi,

I guess this was me carrying on still "Matlab habits"... :), in Matlab you can convert in that way from one numerical data type to another. 

I checked that using `arr.astype(np.intp, copy=False)` always retain the original shape of the array (`(1,)`), which I think it is the right behaviour

I think that any conversion done using the `np.intp(arr)` approach should mimic the `arr.astype(np.intp...`.  

In any way, I think all conversions using `np.intp` should behave equally. My comment was more oriented to highlight that in Windows np.int32 behaves differently to np.int64, np.uint32 and np.uint64, and that in Linux the similar issue appears between np.int64 vs the rest of integer types. That may cause, as in my case, a lot of troubles figuring out why a code works in Windows and not in Linux, and vice versa.

**Comment by seberg** [comment]
The difference has to do do with the C long dtype quivalent (which depends on the system), is a subclass of Python int on python 2. So on some systems `int32` is a subclass of int, on others `int64` is. While that should be the reason, i did not check the code.

**Comment by skrah** [comment]
Yes, apparently reductions use `long` by default, which is `int32_t` in Windows. I encountered this on another project's CI, where Windows returned the second result without an explicit `dtype` passed to `reduce()`. The example below is on Linux, so the `dtype` needs to be forced to get the Windows result:

```
>>> x = np.array([28, 29, 30, 31, 32, 33, 34], dtype="int32")
>>> y = np.multiply.reduce(x)
>>> y
27113264640
>>> y.dtype
dtype('int64')
>>> 
>>> y = np.multiply.reduce(x, dtype="int32")
>>> y
1343460864
>>> y.dtype
dtype('int32')
```
