### ISSUE TITLE
np.sum does not respect keepdims for np.ma.arrays

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#7537]
Given an array, we can sum with and without keepdims:

```python
>>> x = np.arange(20).reshape(4, 5)
>>> print(x)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
>>> print(np.sum(x, axis=1))
[10 35 60 85]
>>> print(np.sum(c, axis=1, keepdims=True))
[[10]
 [35]
 [60]
 [85]]
```

But if we try the same thing with a masked array (even one without a mask):

```python
>>> xm = np.ma.array(x)
>>> print(xm)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
>>> print(np.sum(xm, axis=1))
[10 35 60 85]
>>> print(np.sum(xm, axis=1, keepdims=True))
[10 35 60 85]
```

Wat.

Furthermore, if we try `xm.sum(axis=1, keepdims=True)` we get:

    TypeError: sum() got an unexpected keyword argument 'keepdims'

For completeness:

```python
>>> np.__version__
'1.10.1'
```

**Comment by eric-wieser** [comment]
Oops, duplicate of #4537

**Comment by seberg** [comment]
Thanks, fixed in master.

**Comment by AvlWx2014** [comment]
I'm just running in to this issue with np.ma.mean(). Was that method fixed as part of this effort?
