### ISSUE TITLE
np.linalg.norm does not handle matrix norm

### ISSUE THREAD

**Issue by zhengwy888** [numpy/numpy#7553]
for 1-norm, the result seems to be wrong. The second line should be 30, not 10.

my numpy version: 1.10.2
python: Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
```
>>> import numpy as np
>>> np.linalg.norm(np.arange(6),1)
15
>>> np.linalg.norm([np.arange(6),np.arange(6)],1)
10
>>> np.linalg.norm(np.asarray([np.arange(6),np.arange(6)], dtype=np.float),1)
10.0
```

**Comment by charris** [comment]
Indeed, looks like the matix norm is computed along the wrong axis.

**Comment by charris** [comment]
Nope, I was wrong. The 1-norm is the max sum of the absolute values down columns. So the result is correct. What you want is the `inf` norm, which is the same thing only along rows. Closing this.

**Comment by zhengwy888** [comment]
I think the defintion is the other way? Correct me if I am wrong.
 
L-inf-norm is the max absolute along the columns. [http://mathworld.wolfram.com/L-Infinity-Norm.html]
1-norm means the sum. [http://mathworld.wolfram.com/L1-Norm.html]
 At least when I verified with Matlab, the 1-norm of the second matrix returned is 30, not 10.

**Comment by charris** [comment]
The matrix norm is an operator norm, which means the maximum of `||Ax||` over the unit ball `||x|| =1`, where `||` is the appropriate norm. For the `L_1` operator norm the maximum is reached when the only nonzero entry in `x` is equal to `+/- 1` and lines up with the column of `A` with maximum L_1 norm.  For the `inf` norm the maximum is when all elements of `x` are `+/- 1` and the maximum is then the maximum `L_1` norm of the rows in `A`. What you are referring to is a vector norm, but in numpy vectors are 1-d, where in matlab they are 2-d and I suspect you need to specify whether the matrix or vector norm is the desired result.
