### ISSUE TITLE
ndarray smart type hints (working demo code inside)

### ISSUE THREAD

**Issue by MInner** [numpy/numpy#7554]
I wonder if anybody have implemented\though of something like a type hint system that could also check dimensionality\types of passed `np.ndarray`'s?

I wrote a short implementational demo (working implementation of those type hints with tests on the bottom) explaining what I mean:
https://gist.github.com/MInner/ea549d7eb6b53cd8467d8d3b3a5d0d0b

So you can do (intentionally messy and complex example)

```
def func(m:NDArr[:, 10](dtype=int), n:int):
     ....
```

\- to restrict the first argument of of function (`m`) to be a 2-dimensional array of ints with strictly 10 columns.

I' not sure if `typecheck-decorator`'s `@typecheck` decorator implementation would be useful here, because its error messages are kind of uninterpretable (~"something when wrong"), but if such a thing would seem useful, I can write a short custom `@nptypecheck` that would give more meaningful error messages (like, "wrong dimensionality here").

I wonder if that seems relevant for community: like a very simple short-cut for checking input data dimensionality in user code?

One other very useful thing might be to have a sort of placeholder there, like:

```
i = TypeVar()
def dot(A:m:NDArr[:, i], B:NDArr[i, :]):
    ...
```

or even

```
def func(A:NDArr(dtype=int, max=n), B:NDArr[n]):
    ...
```

\- but I have no idea of how one could implement it.

Ben

**Comment by shoyer** [comment]
It would be nice to try to do this in a way that complements the standard library's `typing` module (see [PEP484](https://www.python.org/dev/peps/pep-0484) for details). Integrating this into static type checkers like mypy would be awesome but require some serious effort to determine a typing specification. [Datashape](http://datashape.pydata.org/) is one attempt to formalize this sort of thing, though it's pretty different (and predates) the typing library.

**Comment by shoyer** [comment]
I'm closing this in favor of https://github.com/numpy/numpy/issues/7370 to keep the type checking discussion in one place.
