### ISSUE TITLE
Problems with numpy.delete()

### ISSUE THREAD

**Issue by jhtang12** [numpy/numpy#7555]
Hi, 

I am currently experiencing some issues with numpy.delete function.

I have got some code which outputs a 3x3 array (from the cv2.Rodrigues function). I then call np.delete(arr, 2, 1) to get rid of the last column in the array. However it outputs "IndexError: index 2 is out of bounds for axis 1 with size 1".

When I make a new Python script, and type the array out as (i.e.) arr = np.array([a,b,c],[d,e,f],[g,h,i]]), and call the exact same function it works.

Any help would be appreciated.

**Comment by njsmith** [comment]
It sounds like you don't actually have something that numpy considers a 3x3 array -- it would help to paste what your array looks like.

**Comment by jhtang12** [comment]
Hi njsmith,

Thanks for your reply. My array looks like the following in the Python Command Window as I print(arr) before calling np.delete:

`[[-0.02012984 0.99975599 0.00909702]`
`[-0.64085521 -0.00591853 -0.76763896]`
`[-0.76739781 -0.02128233 0.64081797]]`

If I then go into a new script and type the above array using the following code:

`arr = np.array([[a, b, c],[d,e,f],[g,h,i]]`
'arr = np.delete(array, 2, 1)'

The output deletes the last column with no errors.

**Comment by njsmith** [comment]
Can you paste the following lines into the Python Command Window one at a time, hit enter after each, and then paste the entire output you see?
```
arr
type(arr)
arr.shape
arr.dtype
```

**Comment by jaimefrio** [comment]
OpenCV is notoriously famous for adding size 1 dimensions in weird places. My bet is `arr.shape` will be `(3, 1, 3)`, not `(3, 3)`, which would explain all your issues.

**Comment by jhtang12** [comment]
Hi All,

So I've turned off the Raspberry Pi, opened the script again and have executed the same code. It appears as though the array shape was in fact (3,1,3) and not (3,3).

Thanks for all your help. I'm going to close the issue!
