### ISSUE TITLE
Runtime Warning: Invalid value encountered in median 

### ISSUE THREAD

**Issue by ralston3** [numpy/numpy#7557]
<p>Code bit:</p>
	if dtype == 'float64' or dtype == 'int32' or dtype == 'int64':

		try:

			writer.writerow({'Index':idx, 'Name':col, 'Variance':np.var(series), 'Standard_Deviation':np.std(series), 
				'Mean':np.mean(series), 'Median':np.median(series), 'Mode':stats.mode(series), 
				'Minimum':np.amin(series), 'Maximum':np.amax(series), '25%':np.percentile(series, 25), 
				'50%':np.percentile(series, 50), '75%':np.percentile(series, 75), 
				'Empty_Values':sum(series.isnull()), '%_Empty':sum(series.isnull())/len(series), 'Dtype':series.dtype})
		
		except:

			raise ValueError('%s is not a supported data type.' % dtype)

	else: 

		try:

			writer.writerow({'Index':idx, 'Name':col, 'Variance':'NA', 'Standard_Deviation':'NA', 
				'Mean':'NA', 'Median':'NA', 'Mode':stats.mode(series), 'Minimum':'NA', 
				'Maximum':'NA', '25%':'NA', '50%':'NA', 
				'75%':'NA', 'Empty_Values':sum(series.isnull()), '%_Empty':sum(series.isnull())/len(series), 
				'Dtype':series.dtype})

		except:

			raise ValueError('%s is not a supported data type.' % dtype)

<p>Results:</p>

<p>Everything works, but I get these annoying, <code>RuntimeWarning: Invalid value encountered in median</code>, and <code>RuntimeWarning: Invalid value encountered in percentile</code> warnings. 

Checked SO for a solution and tried putting <code>np.seterr(invalid='ignore')</code> in my <code>if</code> loop, but that didn't help. Can someone offer a suggestion on how to mute these warnings? Thanks.

Details:

<code>numpy v (1.11.0)</code>
<code>Mac OSX</code>
<code>Python3.5</code>

**Comment by charris** [comment]
You can try using `np.errstate` as a context
```
with np.errstate(invalid='ignore'):
    blah, blah.
```
This is a question rather than a bug report, so closing. Questions should be raised on the mailing list.
