### ISSUE TITLE
Add WITH_DEBUG configuration to AppVeyor build matrix

### ISSUE THREAD

**Issue by tadeu** [numpy/numpy#7564]
Would you be interested in a pull request for this?

I'm thinking about adding this support, but it would need to download `python` and `cython` packages from an Anaconda.org channel other than the default (in order to provide `python_d` and the debug version of `cython`).

**Comment by charris** [comment]
Would be interested in seeing it. Runtime might be a consideration, we are looking at paying for better service, as appveyor can be a bottleneck.

**Comment by mattip** [comment]
Closing, we have a `USE_DEBUG` on travis for Linux.
