### ISSUE TITLE
When use float16 types, does numpy do computation in float16 or float32?

### ISSUE THREAD

**Issue by sunshineatnoon** [numpy/numpy#7571]
Surely numpy supports float16 numbers in storage, but in my case, I would like to know how does numpy handle float16 computation? Does it do float computation in float16 or in float32? Thanks!

**Comment by charris** [comment]
It does them in float32. Closing because not an issue, questions should be asked on the mailing list.

**Comment by sunshineatnoon** [comment]
@charris Thanks!

**Comment by charris** [comment]
Note that the float result is then converted back to float16.
