### ISSUE TITLE
python setup.py sdist fails with ValueError: Submodule not clean: -... doc/scipy-sphinx-theme

### ISSUE THREAD

**Issue by ssbarnea** [numpy/numpy#7574]
It seems that running `python setup.py sdist` with a really confusing error:
```
running sdist
Traceback (most recent call last):
  File "setup.py", line 390, in <module>
    setup_package()
  File "setup.py", line 382, in setup_package
    setup(**metadata)
  File "/media/psf/Home/aaa/xxx%2Fyyy/numpy/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 199, in run
    check_submodules()
  File "setup.py", line 192, in check_submodules
    raise ValueError('Submodule not clean: %s' % line)
ValueError: Submodule not clean: -c466764e2231ba132c09826b5b138fffa1cfcec3 doc/scipy-sphinx-theme
```
To make it even more confusing, `git status` reports no changed files, so how this can be unclean?

**Comment by pv** [comment]
Your git checkout may be corrupted, try recloning.

**Comment by ssbarnea** [comment]
Not really, I did it again and got the same result. I even tested on two different platforms! OS X and Ubuntu!
```
git checkout git@github.com:numpy/numpy.git
cd numpy
python setup.py sdist
```

**Comment by pv** [comment]
You also need to do `git submodule init; git submodule update` or use 
`git clone --recursive`. The sdist is correct to fail, since it needs to 
contain the stuff in the submodules.

**Comment by ssbarnea** [comment]
Thank you, this solved the problem. As a note, I want to mention that I did read the docs before raising the bug and there is no mention of the submodules. 

Maybe it would be a good idea to document them or even better to try to run the commands if the modules were not initialized yet.
