### ISSUE TITLE
one is not x plus one

### ISSUE THREAD

**Issue by momahajogami** [numpy/numpy#7589]
import numpy poly1d
poly1d([1,1]) == poly1d([1])
but it shouldn't, because one does not equal x plus one.

The definition of equality for poly1d is 

def __eq__(self, other):
    if self.coeffs.shape != other.coeffs.shape:
        return False
    return (self.coeffs == other.coeffs).all()

And this seems correct.  Indeed, 
poly1d([1]).coeffs.shape != poly1d([1,1]).coeffs.shape
is True.

So I can't see how this bug happens. 

I am using version 1.8.2 of numpy
and version 2.7.9 of python

**Comment by charris** [comment]
```
n [1]: poly1d([1,1]) == poly1d([1])
Out[1]: False
```
Looks fixed in recent versions. 1.8 is pretty old at this point...

**Comment by momahajogami** [comment]
Thanks
