### ISSUE TITLE
numpy.core.scalarmath disappeared from at least release 1.10.4?

### ISSUE THREAD

**Issue by ygrange** [numpy/numpy#7591]
I noticed that numpy.core.scalarmath seems to have silently disappeared from numpy. If I build 1.9.3, scalarmath does exist. When using 1.10.4, it doesn't. I haven't tried the intermittent ones. In the release notes, this is not mentioned so I was wondering whether the disappearance was actually intentional.

**Comment by ewmoore** [comment]
The module was merged with umath in #5162.  Perhaps you could say a little more about what you're trying to do?  I think the things that were in `numpy.core.scalarmath` should probably be considered an implementation detail.

**Comment by charris** [comment]
Closing.

**Comment by ygrange** [comment]
I was trying to build a package that was basically using this module as an extra check to search for numpy. I didn't really know whether I should report this to you or them (so I went for both). Issue will be soved. Thanks for the answer!
