### ISSUE TITLE
[Windows Python 3.5 only] np.clip replace nans with lower bound

### ISSUE THREAD

**Issue by lesteve** [numpy/numpy#7601]
```python
import numpy as np

arr = np.array([np.nan, 10])
print(np.clip(arr, -1, 1))
```

Expected output is that nan are left untouched:
```
[ nan   1.]
```

Actual output with Python 3.5 on a Windows VM (numpy 1.11 installed through conda):
```
[-1.  1.]
```

It works as expected with Python 2.7 and 3.4 on the Windows VM. It works as expected with all Python versions on my Ubuntu box.

**Comment by matthew-brett** [comment]
Sorry, I can't test at the moment (no access to a Windows machine or VM) but would you mind testing with the current numpy wheel on pypi?  I imagine it has the same error, because it's built with the same compiler, but it would be good to be sure.     Do you get the same error for 32- and 64-bit?

**Comment by lesteve** [comment]
This is 64 bit, I haven't tested with 32-bit.

I get the same behaviour with the numpy wheel from PyPI.

**Comment by lesteve** [comment]
I started looking at it a bit further and I see a very surprising behaviour. It seems like adding a `printf` statement inside the filling loop in `numpy/core/src/multiarray/arraytypes.c.src`
somehow fixes it. If someone has any clue on how this is even remotely possible, I'd be very very interested!

I see this behaviour on my laptop and I reproduced it on AppVeyor:

* Commit adding a commented line and reproducing the np.clip bug
https://github.com/lesteve/numpy/commit/7c9cf40c96dd4f239b3aacf0d1b24a9958d0d917.
[AppVeyor build](https://ci.appveyor.com/project/lesteve/numpy/build/1.0.3/job/6ogjwvft7q9bkqik)
* Commit uncommenting the `printf` line, which appears to fix the np.clip bug:
https://github.com/lesteve/numpy/commit/b87a0a80f896aeb9186061871b2a694161f384c1. [AppVeyor build](https://ci.appveyor.com/project/lesteve/numpy/build/1.0.5/job/vxr2j84jd4965ild)

**Comment by seberg** [comment]
I don't know this stuff well, but I would guess that the printf statement kills the compilers optimization to vectorized/SIMD instructions, which in turn changes the floating point error status setting stuff. If you compile with `-O0` it probably always works.
Anyway, I don't know the depth of SSE, non-vectorized, etc. floating point error flag setting, especially on windows, but maybe someone else will know it.

**Comment by matthew-brett** [comment]
Loic - this is rather a serious bug - would you consider writing a failing
test case for it to put into the numpy test suite?

**Comment by lesteve** [comment]
> Loic - this is rather a serious bug - would you consider writing a failing test case for it to put into the numpy test suite?

There is one in my branch: https://github.com/lesteve/numpy/commit/2c257cfad7b3b4f5b3c89ed1e063a3d015712546

Or did you mean something else?

**Comment by lesteve** [comment]
I managed to reproduce the problem in a stand-alone C program.

```c
#include <stdio.h>
#include <math.h>
#include <stdlib.h>

#define SIZE 2

void clip(double* in, int size, double min, double max, double* out){
  for (int i=0; i < size; i++){
    if (in[i] < min){
      out[i] = min;
    }
    else if (in[i] > max) {
      out[i] = max;
    }
    else {
      out[i] = in[i];
    }
  }
}

int main() {
  double* in = malloc(sizeof(double) * SIZE);
  double* out = malloc(sizeof(double) * SIZE);
  double min = -1.;
  double max = 1.;

  in[0] = NAN;
  in[1] = 10;

  clip(in, SIZE, min, max, out);

  for (int i=0; i < SIZE; i++){
      printf("i: %d, value: %f\n", i, out[i]);
    }
}
```

As @seberg it has something to do with optimizations. Compiling it with `cl clip_bug.c` (without optimization) and running it works as expected with the output:
```
i: 0, value: -nan(ind)
i: 1, value: 1.000000
```

Compiling it with `cl /Ox clip_bug.c` (maximum optimization, which numpy uses AFAICS) reproduces the bug with the output:
```
i: 0, value: -1.000000
i: 1, value: 1.000000
```

Does anyone have any advice on where to report this bug?

**Comment by pv** [comment]
Does `/Ox` imply the equivalent of gcc `-ffast-math`? If yes, this is 
not necessarily compiler bug --- rather, it means Numpy should not use 
the `/Ox` flag but some more conservative optimization setting.

**Comment by lesteve** [comment]
I just opened a ticket at connect.microsoft.com [here](https://connect.microsoft.com/VisualStudio/feedback/details/2723801/unexpected-nan-handling-in-vectorized-loop).

**Comment by eric-wieser** [comment]
@lesteve: Any idea where that ticket moved to? The link is now dead, and I think this is causing #12520

**Comment by mattip** [comment]
@eric-wieser does that stand alone program fail in your setup?

**Comment by lesteve** [comment]
> @lesteve: Any idea where that ticket moved to?

It seems Microsoft Connect has been retired ... I could not find anything from googling and I could not find any archive online. From what I remember there was not much content in the Microsoft Connect ticket besides an acknowledgement that there was a bug and that the bug will be fixed in a further version of Visual Studio (I asked but the answer was not clear as to which version it was going to be exactly).
