### ISSUE TITLE
numpy.polysub, polyadd: incorrect result when operating on polynomials of different order

### ISSUE THREAD

**Issue by jdahle** [numpy/numpy#7603]
Documentation on numpy.polynomial.polynomial.polysub, polyadd, and polymul, (and perhaps others), seems to be incorrect.  It indicates that "The arguments are sequences of coefficients from lowest order term to highest".  This description does not match the behavior when adding or subtracting polynomials of different order (i.e. lists are different length), or when multiplying polynomials.

If we use this equation as an example: (5x + 5) - (1) = 5x + 4

From the documentation, I would expect this:
polysub([5, 5], [1]) = [4, 5]

But instead, we get [5, 4], which represents 4x + 5

I did not see any requirement that the lists be the same length.  Either the documentation is incorrect, and polynomials coefficients are listed from highest order to lowest, or the behavior is incorrect.  Based on the way that polymul behaves, I would say that the documentation is in error, and polynomial coefficients are listed from highest order to lowest.

```python
import numpy.polynomial;
numpy.polysub([5, 5], [1])       # Correct only if polynomials listed from highest order to lowest
numpy.polyadd([5, 5], [1])       # Correct only if polynomials listed from highest order to lowest
numpy.polymul([5, 5], [0, 2])    # Correct only if polynomials listed from highest order to lowest
numpy.polymul([5, 5], [2, 0])    # Correct only if polynomials listed from highest order to lowest
```
[http://docs.scipy.org/doc/numpy/reference/generated/numpy.polynomial.polynomial.polysub.html#numpy.polynomial.polynomial.polysub](url)

python 3.4.4
numpy 1.10.4

I am running on Windows, with Anaconda3 (64 bit).  print(sys.version) gives
3.4.4 |Anaconda 2.4.1 (64-bit)| (default, Feb 16 2016, 09:54:04) [MSC v.1600 64 bit (AMD64)]

**Comment by charris** [comment]
Wrong function ;) The functions in the polynomial package are not imported by default and what you are seeing is the function from `numpy.lib.polynomial` which uses the coefficients in the other way round.
```
In [3]: polysub
Out[3]: <function numpy.lib.polynomial.polysub>

In [4]: numpy.polynomial.polynomial.polysub
Out[4]: <function numpy.polynomial.polynomial.polysub>

In [5]: numpy.polynomial.polynomial.polysub([5,5], [1])
Out[5]: array([ 4.,  5.])
```
