### ISSUE TITLE
Vague VisibleDeprecationWarning in random module

### ISSUE THREAD

**Issue by Chroxvi** [numpy/numpy#7613]
After upgrading to numpy 1.11.0, a few VisibleDeprecationWarnings showed up in one of my test suites. Most of these warnings were easy to identify and fix. However, I had some trouble tracking down one particular warning that just showed up as `<name_of_module>:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future """`. It turned out that this warning originated from passing a float dimension argument to one of the `numpy.random.*` distribution functions, e.g.

``` python
>>> import numpy as np
>>> np.__version__
'1.11.0'
>>> np.random.randn(2, 2.0)
__main__:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
array([[-0.26266633, -0.65826378],
       [ 1.01571069,  1.94209076]])
```

The warning seems fair since the docstring states that the dimensions must be integers. However, the text printed by the warning could be more clear. The other VisibleDeprecationWarnings, that showed up, all gave a precise reference to the relevant module:line and printed that line.

**Comment by mattip** [comment]
This is now a `TypeError`. Closing, feel free to reopen if you feel the error message is still not clarer.
