### ISSUE TITLE
No module named version

### ISSUE THREAD

**Issue by bilian1995** [numpy/numpy#7645]
I've been used numpy for three months, but one week ago it said no module named version error when I tried to import numpy. The error happened in __init__.py file.
I tried to look up information online, but no one asked this question. Any idea?

**Comment by rgommers** [comment]
There should be a ``version.py`` file in the directory where your numpy is installed (look at the traceback you get to see that location).

Maybe you've accidentally deleted that file?

The contents are something like this:

    $ cat version.py

    # THIS FILE IS GENERATED FROM NUMPY SETUP.PY
    #
    # To compare versions robustly, use `numpy.lib.NumpyVersion`
    short_version = '1.12.0'
    version = '1.12.0'
    full_version = '1.12.0.dev0+e96ebfc'
    git_revision = 'e96ebfc233412e8da98ae96f5c640d00f5411f6e'
    release = False

    if not release:
        version = full_version
