### ISSUE TITLE
memory leak in svd

### ISSUE THREAD

**Issue by kilianrisse** [numpy/numpy#7646]
If I run the code below, it uses more and more memory:

    import numpy as np
    import resource
    
    def run():
        X = np.random.rand(10000, 1000)
    
        while True: 
            print("i  Memory usage: {} (kb)".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

            U, d, V = np.linalg.svd(X, full_matrices=False)

            print("ii Memory usage: {} (kb)".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

    if __name__ =="__main__":
        run()

I am running numpy version 1.9.2-2 with python 3.4.3 on fedora 23.

**Comment by jaimefrio** [comment]
On OSX with Python 2.7, both with 1.9.1 and a development version, memory use stabilizes after about the tenth run:

```
i  Memory usage: 110874624 (kb)
ii Memory usage: 407674880 (kb)
i  Memory usage: 407674880 (kb)
ii Memory usage: 495984640 (kb)
i  Memory usage: 495984640 (kb)
ii Memory usage: 496685056 (kb)
i  Memory usage: 496685056 (kb)
ii Memory usage: 496693248 (kb)
i  Memory usage: 496693248 (kb)
ii Memory usage: 496693248 (kb)
i  Memory usage: 496693248 (kb)
ii Memory usage: 496693248 (kb)
i  Memory usage: 496693248 (kb)
ii Memory usage: 496693248 (kb)
i  Memory usage: 496693248 (kb)
ii Memory usage: 496693248 (kb)
i  Memory usage: 496693248 (kb)
ii Memory usage: 496742400 (kb)
```

and that last value repeats ever after (or at least the next couple dozen runs).

It's weird behavior, but I would think the blame has to be on the linear algebra library, not numpy?

**Comment by kilianrisse** [comment]
okay - didn't know these are separate libraries. :) 
Yeah my values do not repeat - adds about 100 mb per iteration.

 Where can I report it? Is this a standalone project?

**Comment by mhvk** [comment]
For me (Debian, numpy 1.10), it stabilizes even earlier:
```
. I thinki  Memory usage: 102184 (kb)
ii Memory usage: 388356 (kb)
i  Memory usage: 388356 (kb)
ii Memory usage: 478228 (kb)
i  Memory usage: 478228 (kb)
ii Memory usage: 480036 (kb)
i  Memory usage: 480036 (kb)
... and on
```
With an explict `gc.collect()` before the second print statement, it changes to:
```
i  Memory usage: 102024 (kb)
ii Memory usage: 388080 (kb)
i  Memory usage: 388080 (kb)
ii Memory usage: 477924 (kb)
i  Memory usage: 477924 (kb)
ii Memory usage: 479752 (kb)
i  Memory usage: 479752 (kb)
...
```

**Comment by mhvk** [comment]
Oddly, my usage is a factor 1000 less than @jaimefrio's -- there must be a bug in the code on his machine, in that it lists kb but gives bytes.

**Comment by mhvk** [comment]
Independently, it seems puzzling that memory usage is well over 4 times that of the input array, rather than the ~2 times expected.

**Comment by seberg** [comment]
Dunno, since you can't collect the old `X` before the new `X` is defined, I would thin kyou always got 2x X and 2x U, etc. in the memory.

I always forget how to best do it, but maybe @kilianrisse you can check what lapack/blas you are using? Worst case, this is a bug in our very own lapacklite and we all just use something else, instead of the other way around.

**Comment by jaimefrio** [comment]
Isn't it kind of weird that it increases **at all** after the first iteration?

**Comment by seberg** [comment]
Shouldn't it increase until the second call where `U` is defined the second time? Since the first `U` can only be cleared *after* this happens (and python won't actually give you back that memory, even though it is kind of free). After that, dunno, who knows what kind of small stuff happens....

**Comment by kilianrisse** [comment]
I use lapack and blas 3.5.0-12

**Comment by charris** [comment]
If I keep the call but remove the assignment I get
```
i  Memory usage: 100568 (kb)
ii Memory usage: 384400 (kb)
i  Memory usage: 384400 (kb)
ii Memory usage: 384400 (kb)
i  Memory usage: 384400 (kb)
ii Memory usage: 384400 (kb)
i  Memory usage: 384400 (kb)
ii Memory usage: 384400 (kb)
i  Memory usage: 384400 (kb)
```
So it looks like `_` is preserved. In any case, this doesn't look like a Numpy problem.
