### ISSUE TITLE
BUG: Integers raised to negative powers gives wrong results

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#7649]
In current master:
```
np.array(1, dtype=int) ** -2
Out[5]: 0
```
In 1.11 and earlier:
```
In [3]: np.array(1, dtype=int) ** -2
Out[3]: 1
```
(Found in astropy testing; https://github.com/astropy/astropy/pull/4950)

**Comment by jakevdp** [comment]
Duplicate of https://github.com/numpy/numpy/issues/7648 – this can probably be closed.

**Comment by mhvk** [comment]
Oops, sorry. Will close (though my example is even worse...)

**Comment by jakevdp** [comment]
Actually, you're right – this looks like a regression in master that might be unrelated.
