### ISSUE TITLE
hstack accepts generators, concatenate doesnt

### ISSUE THREAD

**Issue by skuschel** [numpy/numpy#7650]
I was wondering, why `hstack` accepts generators, but `concatenate` doesnt. Is that on purpose? It doesnt seem right to me. I am using numpy 1.11.0.

Code Example:

``` python
import numpy as np
seq = [np.random.random(5) for _ in range(10)]
hstackseq = np.hstack(seq)
catseq = np.concatenate(seq)
print(np.all(hstackseq == catseq))  # They are equal as they should be
generator = (s for s in seq)
hstackgen = np.hstack(generator)
print(np.all(hstackgen == catseq))  # Same result. ok!
generator = (s for s in seq)
hstackcat = np.concatenate(generator)  # This errors. Why?
```

Additionally there is something wrong in the docs at https://github.com/numpy/numpy/blob/1429c606643d1ad305e710c4a31cb6f398d04c53/numpy/core/shape_base.py#L267
It says, that `hstack(tup)` is equivalent to `concatenate(tup, axis=1)`, but in fact `concatenate(tup, axis=0)` yields the same result. Try that code after the code above:

``` python
catseq0 = np.concatenate(seq, axis=0)
print(np.all(hstackseq == catseq0))
```

**Comment by eric-wieser** [comment]
This now emits a warning for `hstack`:
```
FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
```

I think this can be closed - at least it's moving towards consistency
