### ISSUE TITLE
Building with no BLAS on Mac

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#7652]
We are trying to build a copy of NumPy that uses no BLAS at all on several platforms including Mac. The main reason we are doing this is that most BLAS libraries are quite large and the system BLASes (e.g. Accelerate) are unreliable. So, in situations where space and/or time are heavily constrained downloading a pre-built BLAS is simply not an option. However, this doesn't appear to be an option on Mac even when we follow the recommended [best practice](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html#disabling-atlas-and-other-accelerated-libraries) based on the [current logic](https://github.com/numpy/numpy/blob/730af6f800d7e9b57ae7a2233aa7ca563603c960/numpy/distutils/system_info.py#L1517-L1518). What can we do?

cc @pelson

**Comment by charris** [comment]
Best ask this on the mailing list. But if you want to build with no BLAS you can do
```
BLAS=None LAPACK=None ATLAS=None python setup.py build
```
I don't know if that works correctly with all the build options (wheels, etc.)

**Comment by jakirkham** [comment]
So, that is what we are trying to do now, but it doesn't seem to work. It still picks up Accelerate on Mac.

**Comment by charris** [comment]
OK, that would be a bug. OSX is special cased, so that probably needs a fix.

**Comment by charris** [comment]
Search for `darwin` in `sys_info.py`. The distutils are a mess, it would be nice is someone with a bad case of OCD and great programming skills would come along and fix it up.

**Comment by jakirkham** [comment]
As this is something we are eager to have, we will likely come up with a patch that seems to fix our current issues. Though we can submit a PR and iterate on a proper solution once we can get a working building for our more immediate use case.

**Comment by charris** [comment]
The easiest, if hackish, fix might be to add an `ACCELERATE=None` environment variable.

**Comment by jakirkham** [comment]
Thanks for all of the advice, @charris. We will give that a try and get back to you.

**Comment by rgommers** [comment]
This can be taken along or will be fixed when someone (might be me) finally gets around to reworking ``system_info`` to respect ``site.cfg`` instead of using the first BLAS lib it finds in the hardcoded order.

**Comment by mattip** [comment]
Closing as we no longer will pick up Accelerate. Please reopen if I misunderstood or if it is not clear how to achieve the configuration you desire.

**Comment by jakirkham** [comment]
@mattip, the request in this issue is not about Accelerate, it's about disabling building NumPy with any BLAS. We just happened to have some peculiar issues with Accelerate specifically. This can be handy for space limited environments (e.g. Heroku) where users may want NumPy for basic array operations, but don't care about any BLAS routines.

**Comment by mattip** [comment]
Did the suggestions on setting environment variables or using a setup.cfg fail to work?

**Comment by rgommers** [comment]
And, what does this do now?
```
BLAS=None LAPACK=None ATLAS=None python setup.py build
```

**Comment by jakirkham** [comment]
It failed previously. Was not aware Accelerate is no longer used. So that seems like a good step in the right direction.

Have not rechecked. Will try to find some time to do that.

**Comment by mattip** [comment]
We also have `NPY_BLAS_ORDER=""` and `NPY_LAPACK_ORDER=""` which should ensure no blas is used.

**Comment by jakirkham** [comment]
Ok let's go ahead and close then.

**Comment by jakirkham** [comment]
Thanks all for the work here! :)
