### ISSUE TITLE
"Importing data with genfromtxt" doc page

### ISSUE THREAD

**Issue by victoriastuart** [numpy/numpy#7662]
Re:

https://docs.scipy.org/doc/numpy-dev/user/basics.io.genfromtxt.html

... great job/effort; your examples are also fabulous: clever, illustrative, powerful!  :-)

There is a Python 2 vs. 3 issue: see my 'answer'/comments, here:

https://stackoverflow.com/questions/11914472/stringio-in-python3/37380717#37380717

Also, in your last example, I believe you should have

np.genfromtxt(StringIO(data), **kwargs)

not

np.genfromtxt(StringIO.StringIO(data), **kwargs)

Also, it would be really great to have those doc pages as a Jupyter notebook(s), or at least have the code given in raw form, minus the prompts (>>> ).  ;-)

Those comments often wrap into the code, which is necessarily distracting; you could also break those into two or more lines (to the right), as needed: e.g.

<pre>
some code      # This is just
               # a small comment.
</pre>

vs.

<pre>
some code      # This is just
a small comment.
more code
...
</pre>
or adjust your page formatting (CSS? page / code block width and/or font size?).

Minor points; again, fabulous work; much appreciated!  :-D

**Comment by rgommers** [comment]
> Also, it would be really great to have those doc pages as a Jupyter notebook(s), or at least have the code given in raw form, minus the prompts (>>> ). ;-)

Did you notice the ``>>>`` at the right top of every example block? Clicking that removes the promts and the output, so only the code remains and you can copy-paste it easily.

Notebooks probably aren't going to happen, that's quite a bit of work and there'll be a huge amount of them (not even sure where we'd put them).

**Comment by rgommers** [comment]
> Also, in your last example, I believe you should have
> np.genfromtxt(StringIO(data), **kwargs)

good catch, thanks

**Comment by victoriastuart** [comment]
"Did you notice the >>> at the right top of every example block?" >> whoops!  Thx  :-)

**Comment by rgommers** [comment]
Thanks for filing this issue, needs fixing indeed. It's even worse, somehow we managed to break the Python 2.7 code as well with numpy 1.11.0:

    In [1]: from io import StringIO, BytesIO

    In [2]: data = "1, 2, 3\n4, 5, 6"

    In [3]: np.genfromtxt(StringIO(data), delimiter=",")
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-3-b21e8ad6019c> in <module>()
    ----> 1 np.genfromtxt(StringIO(data), delimiter=",")

    TypeError: initial_value must be unicode or None, not str
