### ISSUE TITLE
matrix inversion bug

### ISSUE THREAD

**Issue by jonturner53** [numpy/numpy#7663]
The following is from an interactive session using numpy in python 3.5. Similar results were
obtained with python 2.7.

>>> z
matrix([[  5.00000000e+00,   5.10000000e+02,   5.20300000e+04,
           5.30910000e+06,   5.41840354e+08],
        [  5.10000000e+02,   5.20300000e+04,   5.30910000e+06,
           5.41840354e+08,   5.53101783e+10],
        [  5.20300000e+04,   5.30910000e+06,   5.41840354e+08,
           5.53101783e+10,   5.64705388e+12],
        [  5.30910000e+06,   5.41840354e+08,   5.53101783e+10,
           5.64705388e+12,   5.76662666e+14],
        [  5.41840354e+08,   5.53101783e+10,   5.64705388e+12,
           5.76662666e+14,   5.88985522e+16]])
>>> z.I
matrix([[  1.31848350e+08,  -3.14331980e+06,   1.69158434e+04,
           7.76571487e+01,  -6.43306734e-01],
        [ -3.14331970e+06,   7.28054929e+04,  -3.36563229e+02,
          -2.54456357e+00,   1.77294369e-02],
        [  1.69158403e+04,  -3.36563170e+02,   1.60108119e-01,
           3.01378385e-02,  -1.49983677e-04],
        [  7.76571786e+01,  -2.54456435e+00,   3.01378441e-02,
          -1.49939603e-04,   2.53606512e-07],
        [ -6.43306833e-01,   1.77294398e-02,  -1.49983705e-04,
           2.53606602e-07,   1.16593238e-09]])
>>> z * z.I
matrix([[  1.00000000e+00,   1.86264515e-09,  -1.45519152e-11,
          -2.84217094e-14,   0.00000000e+00],
        [ -7.62939453e-06,   9.99999642e-01,  -1.86264515e-09,
          -1.81898940e-11,   0.00000000e+00],
        [  2.92968750e-03,  -3.05175781e-05,   9.99999881e-01,
          -2.32830644e-10,  -1.45519152e-11],
        [  0.00000000e+00,   3.90625000e-03,  -1.52587891e-05,
           1.00000006e+00,   1.86264515e-09],
        [ -8.00000000e+00,  -1.25000000e-01,   0.00000000e+00,
           3.81469727e-06,   9.99999970e-01]])

As I understand it, the final matrix should be an identity matrix. Even if I accept most of
small non-diagonal values as zero, the first two entries in the last row are very far from zero.
These flaws make the matrix inversion function totally worthless.

I am running Mac OS X 10.9.5  on a MacBook pro.

**Comment by pv** [comment]
Not a bug. Look up the term "condition number" in a numerical analysis 
book or online.

**Comment by charris** [comment]
The matrix is numerically singular.

**Comment by jonturner53** [comment]
The determinant is non-zero. Do you mean something else by
�numerically singular�?

Jon

**Comment by ewmoore** [comment]
https://en.wikipedia.org/wiki/Condition_number#Matrices  see also [`numpy.linalg.cond`](http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.linalg.cond.html#numpy.linalg.cond)

**Comment by matthew-brett** [comment]
For example:

```
In [5]: np.linalg.matrix_rank(z)
Out[5]: 2
```

**Comment by ewmoore** [comment]
The last paragraph of the wikipedia entry is the most relevant: 

> If the condition number is not too much larger than one (but it can still be a multiple of one), the matrix is well conditioned which means its inverse can be computed with good accuracy. If the condition number is very large, then the matrix is said to be ill-conditioned. Practically, such a matrix is almost singular, and the computation of its inverse, or solution of a linear system of equations is prone to large numerical errors. A matrix that is not invertible has condition number equal to infinity.

The condition number of your matrix is 
```
In [15]: np.linalg.cond(a)
Out[15]: 3.386052175713763e+23
```
Which is not very close to 1.

**Comment by jonturner53** [comment]
Clearly I need to find another way to solve my problem that
does not require matrix inversion. Back to the drawing board.

Jon
