### ISSUE TITLE
array2string fails for matrix inputs

### ISSUE THREAD

**Issue by perimosocordiae** [numpy/numpy#7687]
Here's a minimal example:

``` python
a = np.matrix(np.ones((3, 3)))
b = np.matrix(np.ones((30000, 3)))

np.array2string(a)  # raises ValueError in _formatArray

np.array2string(b)  # raises RuntimeError: "maximum recursion depth exceeded" in _leading_trailing
```

The basic problem is familiar. The code assumes that `a[0].ndim == a.ndim - 1`, which is true for most `ndarray` subclasses but not for matrices.

Perhaps we could just convert matrix inputs to regular arrays before calling `_array2string`?

**Comment by eric-wieser** [comment]
This was fixed in #10164
