### ISSUE TITLE
ValueError: fname must be a string, file handle, or generator

### ISSUE THREAD

**Issue by svnitHIMANSHU** [numpy/numpy#7691]
import numpy as np
import pylab as pl
import tarfile
with tarfile.open('data.tar') as tf:
    #print tf
    namelist = tf.getnames()
    #print namelist
    for i in range(1, len(namelist)):
        #print namelist[i]
        fileobj = tf.extractfile(namelist[i])
        #print fileobj
        data = np.loadtxt(fileobj)
        pl.plot(float(data[:,1]), float(data[:,3]), 'ro')
        pl.xlabel ('l')
        pl.ylabel ('nu')
                pl.show()
i have data.tar file, from that i am trying to plot graph between two columns of that data.
here i m getting the error, ValueError: fname must be a string, file handle, or generaor

**Comment by birm** [comment]
is line 4, 11, or line 16 raising a ValueError? Or is it another line?

**Comment by svnithemu** [comment]
thank you so much for your response.line no 11 is giving me value error.

**Comment by birm** [comment]
numpy.loadtxt() expects a file path, not the file-like object created by tarfile.
try numpy.fromfile() instead

**Comment by mattip** [comment]
Closing. If `fromfile` is not doing what you expect, please reopen with more information.
