### ISSUE TITLE
str(numpy.datetime64) has different output in Pyhon2/Python3

### ISSUE THREAD

**Issue by MacHu-GWU** [numpy/numpy#7693]
Code to reproduce this bug:

```python
from __future__ import print_function
import numpy as np

# In Python 3, it display local time:"1969-12-31T19:00:00-0500＂
# In Python 2, it returns utc time: "1970-01-01T00:00:00"
print(np.datetime64("1970-01-01 00:00:00Z"))
```

**Comment by shoyer** [comment]
Make sure you're running the same version of NumPy. We changed datetime64 to be time zone naive in NumPy 1.11: http://docs.scipy.org/doc/numpy/release.html#datetime64-changes

**Comment by MacHu-GWU** [comment]
Thank you! I think it's because I am using different version of Numpy.
