### ISSUE TITLE
Support `with` statement for `seterr`

### ISSUE THREAD

**Issue by tillahoffmann** [numpy/numpy#7694]
I often find myself saving the current error reporting configuration, modifying the configuration for a particular operation, and subsequently restoring the original configuration. For example,

```python
import numpy as np


def compute_entropy(probabilities):
    err = np.geterr()
    np.seterr(divide='ignore')
    surprisal = - np.log(probabilities)
    np.seterr(**err)
    return np.sum(probabilities * surprisal)
```

I have handled such situations using an `ErrorContext` class that stores the current configuration in its `__enter__` method and restores it in `__exit__` such that the above code becomes.

```python
import numpy as np


def compute_entropy(probabilities):
    with ErrorContext(divide='ignore'):
        surprisal = - np.log(probabilities)
    return np.sum(probabilities * surprisal)
```

Would such functionality be desired as a contribution or is it too specific to the particular use case? If desired, I will submit a PR.

**Comment by charris** [comment]
Already done, see `errstate`.

**Comment by tillahoffmann** [comment]
Great, thank you.
