### ISSUE TITLE
Version number of 1.11RC1 breaks distutils.version.StrictVersion

### ISSUE THREAD

**Issue by olebole** [numpy/numpy#7697]
The latest RC1 package uses a version number (1.11.1rc1) that causes an exception in `distutils.version.StrictVersion`:
```
>>> from distutils.version import StrictVersion
>>> import numpy
>>> StrictVersion(numpy.__version__)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python2.7/distutils/version.py", line 40, in __init__
self.parse(vstring)
File "/usr/lib64/python2.7/distutils/version.py", line 107, in parse
raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '1.11.1rc1'
```
This cause [failures](https://ci.debian.net/data/packages/unstable/amd64/s/spectral-cube/latest-autopkgtest/log.gz) on packages (like [spectral-cube](https://github.com/radio-astro-tools/spectral-cube)) that use `StrictVersion` in their build/run time tests.

**Comment by pv** [comment]
The answer is that you should not use StrictVersion.
It's not PEP-440 compliant.

**Comment by olebole** [comment]
What would be a proper replacement?

**Comment by njsmith** [comment]
Also the problem here is that StrictVersion doesn't understand the concept of an rc release, so the bad news is that there's really nothing we can do to make it happy with our rc release, but the final release will have a regular version number that works.

There is a NumpyVersion class in new numpys.

**Comment by njsmith** [comment]
(Note that NumpyVersion is only guaranteed to work for numpy version numbers though; I don't think it implements all of pep 440 so please don't trust it as a general solution. There are some pep440 implementations out there though -- in particular http://packaging.readthedocs.io/en/latest/version/ )

**Comment by olebole** [comment]
The current use in spectral-cube is to handle releases <= 1.8 differently from modern ones. I opened radio-astro-tools/spectral-cube#308 and think we should find a solution there. There is probably nothing to do on numpy side, therefore I am closing this.
