### ISSUE TITLE
Wrong example from ctypes

### ISSUE THREAD

**Issue by fabiodl** [numpy/numpy#7701]
In 
http://docs.scipy.org/doc/numpy-1.10.1/user/c-info.python-as-glue.html
in the discussion of ctypes, 
the example function 

void dfilter2d(double *a, double *b, int *astrides, int *dims)

takes astrides and dims as int_, but it seems the correct signature is long_ 

at least with an x64, Python 2.7.6, numpy 1.8.2

**Comment by seberg** [comment]
The correct filter is always `npy_intp` (which is identical to `ssize_t`) if you are concerned with getting the right dims and strides. Not sure in this context exactly, but please feel free to open a pull request to fix the doc.

**Comment by fabiodl** [comment]
indeed intp is 8 bytes on a 64 bit system.
The problem is with the c code, and yes, making dims an ssize_t would fix the problem
