### ISSUE TITLE
ufunc identity of -inf

### ISSUE THREAD

**Issue by mikegraham** [numpy/numpy#7702]
I would like to write a function that, given `log(x)` and `log(y)`, will compute `log(x + y)`. The identity for this is `log(0) = -inf`. Currently, numpy only allows the values of 0, 1, -1, and `None`, as far as I can tell. It would be nice for my purposes if -inf or an arbitrary value could be used.

**Comment by njsmith** [comment]
Fyi the function already exists as np.logaddexp

**Comment by mhvk** [comment]
I guess the question then becomes whether`logaddexp.identity` could be `-inf` (currently it is `None`). Although I'm not quite sure whether it would help all that much for `logaddexp(np.array([]))` to yield `-inf`.  ... ... Except perhaps for `MaskArray` where reducing over an axis could well have parts for which there are no elements ... ... Which led me to think why don't I check `np.ma.logaddexp`, only to find it doesn't exist!

**Comment by mikegraham** [comment]
@njsmith Wow, thanks, I had thought I checked well enough... ;)

**Comment by mikegraham** [comment]
@mhvk I don't necessarily agree: someone could be indexing a plain array to filter instead of using a ma, or someone could be initializing a result for a generic reduce where some of the loops are plain-old for loops (not over an array that actually exists) so you don't have to build the whole thing in memory. (The latter was my application.)

**Comment by seberg** [comment]
Adding -inf from within numpy is reasonably easy, we recently added the -1, so you could find a template on how to do it. I would not mind if we had a way of defining the identity more specific, though. One could also think about an `identity=...` kwarg, to override the identity, or define one for functions where it is unclear what the identity should be (i.e. objects it is common, or np.nan could be a desired result to avoid the error).

**Comment by eric-wieser** [comment]
If we want to allow arbitrary identity values, I think we should pull out `ufunc.reorderable` from the C `ufunc.identity`.

There was another recent PR about identity somewhere...

**Comment by mikegraham** [comment]
Many thanks, @eric-wieser

**Comment by eric-wieser** [comment]
I'm afraid this is a way off from being merged since it would break the ufunc abi, so I'd prefer to leave this open.

**Comment by mikegraham** [comment]
Oops, I misread (I thought it was merged). Thanks all the same :)
