### ISSUE TITLE
Import error on importing scipy.stats

### ISSUE THREAD

**Issue by MichaelAdolph** [numpy/numpy#7703]
Working on a 64bit system, using WinPython 2.7.10.3 I get an error if I try

from scipy import stats

I get: Import Error: DLL load failes: %1 is not a valid Win32 application.

just import scipy works fine. I could "solve" the problem by downgrading to numpy 1.9.3.
I'm sorry, but I have no suggestions what is wrong.

**Comment by njsmith** [comment]
Sounds like something the winpython folks might be better positioned to handle... DLL load failures usually indicate some problem with the build/distribution process, and they're the ones who did that for you -- we just provided them with the source code.

**Comment by MichaelAdolph** [comment]
Thanks, than I'll start crying at their place.
But out of interest: If I'd download a compiled version of numpy 1.11.0 for my system and replace the winpython numpy version, would that work than? Or is the DLL error located somewhere else?

**Comment by njsmith** [comment]
@MichaelAdolph: I don't know for sure, but I haven't heard of any similar problems from the numpy wheels on pypi or from Christoph Gohlke's packages.
