### ISSUE TITLE
Recommendation to install packages for various OS

### ISSUE THREAD

**Issue by AbdealiJK** [numpy/numpy#7711]
In [systeminfo.py](https://github.com/numpy/numpy/blob/730af6f800d7e9b57ae7a2233aa7ca563603c960/numpy/distutils/system_info.py) there are various routines to find packages, libs etc. And if it cannot find a package, an error message which says which packages were not found while installing is shown.
Would it be possible to suggest methods of installing these packages in some common Operating Systems ? Something like:

```python
# A list of apt, brew, etc packages for various OS
# Example using fortran compiler
pkg = 'Fortran compiler'
apt_pkg = 'gfortran'
yum_pkg = 'gcc-gfortran'
brew_pkg  'gcc'  # In homebrew, gcc contains g++, gcc, gfortran, etc.
win_pkg_url = 'https://gcc.gnu.org/wiki/GFortranBinaries#Windows'

if platform.system() == 'win32':
    print('Please check {0} for instructions to install {1}'
           .format(win_pkg_url, pkg))
elif platform.system() == 'darwin':
    print('Try installing {0} with `brew install {1}`'
          .format(pkg, brew_pkg))
elif platform.system() == 'Linux':
    distname, _, __ = platform.linux_distribution()
    if distname.lower() in ('ubuntu', 'debian'):
        print('Try installing {0} with `apt-get install {1}`'
              .format(pkg, apt_pkg))
    elif distname.lower() in ('redhat', 'centos', 'fedora'):
        print('Try installing {0} with `yum install {1}`'
              .format(pkg, yum_pkg))
```

This can be added to error messages like:
 - library dfftpack has Fortran sources but no Fortran compiler found
 - numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
etc

**Comment by seberg** [comment]
Not against helping out users. I would prefer something like a wiki page for it though, and if we have a reasonably well kept wiki page, maybe we can suggest to check that then?

**Comment by rgommers** [comment]
Indeed, there are too many options and such docs don't belong in code but on a website. We could link http://scipy.org/install.html and/or http://scipy.org/scipylib/building/index.html

**Comment by rgommers** [comment]
Looking at the implementation in ``check_libs`` and ``check_libs2`` in ``system_info``, there's not even a good way to add the link there without having it show up many times. So I think we just don't want to do this. Any error message is better Googled anyway.

**Comment by AbdealiJK** [comment]
Error messages can be googled by developers - I agree. But if I want non-dev users to use a package which I am hosting on pypi (and it has a numpy dependency), then the user would get very confused. This is assuming that the wheel for the OS is not found and it needs to be compiled.

The reason I created this issue is because a few users of my package were unable to understand these error messages as they are not developers.

I made a similar patch for `dlib` which you can check out at https://github.com/davisking/dlib/pull/133
Also, @rgommers I think a wiki page documenting this and showing a link for that may be a better approach too.

CC @jayvdb @DrTrigon

**Comment by seberg** [comment]
Well, explaining how to make a build work, is no good for users anyway, they usually don't want to build it themselves. The only thing I could think of is giving a big error at the end of any failed compile to check the "how to install" website.

**Comment by rgommers** [comment]
> Well, explaining how to make a build work, is no good for users anyway, they usually don't want to build it themselves.

indeed 

> The only thing I could think of is giving a big error at the end of any failed compile to check the "how to install" website.

that you can only do in the main ``setup.py`` I think, with a try-except around the ``setup`` call. don't really want to do that - people will find the install instructions fairly easily if they look for them. and this gets less relevant over time, we have wheels now
