### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by aboettcher** [numpy/numpy#7714]
The following code has a memory leak with the current numpy version:
```python
import numpy as np
import scipy
import scipy.stats
u = np.random.random(128**2)
for i in range(100000):
    scipy.stats.norm.ppf(u)
```
Checking with `htop` the memory increases as the loops are performed. With older versions of numpy the above code runs with very little memory usage and especially no increase over time.

I tested if the error is due to a bug in scipy but it isn't. Then I checked with which numpy version the error got introduced (since I realized it after an update of all my packages).

According to git bisect the commit that introduced the error is:
9128ed5198cc8544406467a00824e5fe6791f090

OS: Ubuntu 14.04.3 LTS
Python: sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
numpy: 1.12.0.dev0+cc51ba8
scipy: 0.18.0.dev0+41e2d00

**Comment by charris** [comment]
@gfyoung This is yours.

**Comment by gfyoung** [comment]
@aboettcher : I can't reproduce this.  I ran your commands and monitored `htop` as the loop was running and my `MEM%` remained constant virtually the entire time.  Can you provide further information about your architecture, Python version, and `numpy` + `scipy` versions?  Here is mine:

OS: Ubuntu 14.04
Python: 2.7.11
numpy: v1.11.0
scipy: 0.18.0.dev0+e2c946c

Also, not really sure at the moment how this memory leak could have been triggered by those changes, as they seem quite distant from what you are running here.

**Comment by aboettcher** [comment]
@gfyoung thank you for fast response. Those are my versions:
OS: Ubuntu 14.04.3 LTS
Python: sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
numpy: 1.12.0.dev0+cc51ba8
scipy: 0.18.0.dev0+41e2d00
I did not yet test python 2.7.

**Comment by gfyoung** [comment]
@aboettcher : should have mentioned this initially, but could you actually put that system info in your original issue?  I think that would be useful for people when they read it so they know the entire context.

**Comment by aboettcher** [comment]
I tested your version of numpy (v1.11.0) and the memory leak is indeed not there.

**Comment by gfyoung** [comment]
@aboettcher : okay, so at least we know it was introduced after `v1.11.0` - however, it did seem strange that `git` would get it wrong with `bisect`, so I checked the release and it turns out that PR wasn't included in that release.  Sigh...I'll double check now against `master` to see if I can replicate.

**Comment by charris** [comment]
@gfyoung I do see that commit in v1.11.0, but if the bug doesn't show up there it suggests a bisection failure.

**Comment by aboettcher** [comment]
@gfyoung I am sorry for giving the wrong pointer. I trusted bisect at this point.

**Comment by gfyoung** [comment]
Sorry, before we relegate it to a bisect failure, @charris , can you show me where you're seeing that commit show up in `v1.11.0`?  I couldn't find it anywhere in the maintenance branch.

**Comment by gfyoung** [comment]
@aboettcher : I am able to replicate the memory leak using the bleeding versions of `scipy` (<a href="https://github.com/scipy/scipy/commit/5a779fddeee9e76a9b5fdbb2d6d0a607008812d2">5a779fd</a>) and `numpy` (<a href="https://github.com/numpy/numpy/commit/175476fec763984573e60485a447978cbcb381c0">175476f</a>) on the architecture and Python I gave earlier.

**Comment by charris** [comment]
@aboettcher 
```
charris@fc [numpy.git ((v1.11.0))]$ git log 9128ed5
commit 9128ed5198cc8544406467a00824e5fe6791f090
Author: gfyoung <gfyoung@mit.edu>
Date:   Wed Jan 13 13:15:21 2016 +0000

    BUG: Fix string copying for np.place
```

**Comment by charris** [comment]
Changes in Scipy may have exposed the problem. There is also the possibly related (unlikely?) report #7710.

**Comment by gfyoung** [comment]
@charris : Hmmm...I can find that commit via `git` as you did - not sure why GitHub can't display it either...

**Comment by aboettcher** [comment]
I also cannot find it on github.

At least the changes or not visible here:
https://github.com/numpy/numpy/blob/v1.11.0/numpy/core/src/multiarray/compiled_base.c

**Comment by charris** [comment]
@gfyoung Seems like pilot error on my part, git log also finds it in 1.8.x. Probably need to make git log only search reachable from HEAD.

**Comment by charris** [comment]
OK, this works better `git log --grep 'BUG: Fix string copy'`. Looks like searching by hash looks into the whole tree. Learn something everyday ;)

**Comment by gfyoung** [comment]
Me too! :smile:

In any case, I will run `git bisect` between `v1.11.0` and `master` and see where the bug lies.  I'll also take a look to see whether there are sources of improvement upon that PR.

**Comment by aboettcher** [comment]
I am currently rerunning bisect with
`git bisect good v1.11.1rc1`
`git bisect bad 175476fec763984573e60485a447978cbcb381c0` (newest version). Will report the result soon.

**Comment by aboettcher** [comment]
The rerun of bisect gave the same result as I reported above (9128ed5198cc8544406467a00824e5fe6791f090)

**Comment by gfyoung** [comment]
Yep, I can confirm as well.  It's my PR...now off to figuring out why. :confused:
