### ISSUE TITLE
Xeon CPUs are not detected on Windows in mkl_info

### ISSUE THREAD

**Issue by mingwandroid** [numpy/numpy#7717]
When _not_ using a site.cfg, Xeon is detected at:

https://github.com/numpy/numpy/blob/master/numpy/distutils/system_info.py#L1005

.. but Win32CPUInfo does not have is_Xeon (only LinuxCPUInfo has that).

**Comment by charris** [comment]
Which numpy versions?

**Comment by mingwandroid** [comment]
I checked 1.11 but the git master branch looks the same.

**Comment by mattip** [comment]
Closing. The xeon-detection code does not exist at all on HEAD
