### ISSUE TITLE
The folder name for the 32-bit MKL libraries is wrong in mkl_info for MKL/ICC 2016 update 3.

### ISSUE THREAD

**Issue by mingwandroid** [numpy/numpy#7718]
When _not_ using a site.cfg, after my Xeon is not detected, the folder containing 32-bit libraries is incorrect.

The code at https://github.com/numpy/numpy/blob/master/numpy/distutils/system_info.py#L1016 identifies the folder name as '32'

but in my "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl\lib" I have:

ia32 (link) => ia32_win
intel64 (link) => intel64_win
mic (link) => intel64_win_mic

**Comment by charris** [comment]
Am I correct that this worked for earlier MKL versions?

**Comment by charris** [comment]
BTW you should combine the two issues into one.

**Comment by InessaPawson** [comment]
Given numpy.distutils has been officially deprecated, is this still relevant?
