### ISSUE TITLE
Masked arrays: keepdims is not enforced in numpy.ma.amax

### ISSUE THREAD

**Issue by ycopin** [numpy/numpy#7720]
The `keepdims` option is not enforced in fonction `numpy.ma.amax`:

```python
>>> import numpy
>>> x = numpy.random.randn(4, 3)
>>> numpy.amax(x, axis=-1, keepdims=True).shape
(4, 1)
>>> numpy.ma.amax(numpy.ma.masked_array(x), axis=-1, keepdims=True).shape
(4,)
```

**Comment by seberg** [comment]
Thanks for the report. Ignoring of keepdims in the ma code has recently been fixed (I am not quite sure whether it is fixed in 1.11 or only will be in 1.12 though). Anyway this works now, probably update to 1.11 is good enough.

**Comment by ycopin** [comment]
Thanks for the feedback. FYI, I was using latest pip-available numpy 1.11.0.

**Comment by charris** [comment]
Hmm, not fixed in 1.11.1rc1.

**Comment by seberg** [comment]
I would leave it I think, IIRC, it was quite a complex piece of
changes.

**Comment by charris** [comment]
I went ahead with the backport, #7736, the cherry-pick was clean and a lot of the changes just reformatted docstrings.

**Comment by charris** [comment]
Well, that actually didn't fix the masked array problem, but now it raises an error ;)

**Comment by charris** [comment]
Bisect shows #5706 to have the good stuff.
