### ISSUE TITLE
Masked arrays not allowed in interp1d as of 0.17

### ISSUE THREAD

**Issue by briantoby** [numpy/numpy#7728]
We have code that uses masked arrays (numpy.ma) as input to interpolate.interp1d. This has stopped working as of 0.17.x. A modified unit test is attached that runs in 0.16 but fails in 0.17.0 or 0.17.1

[test-ma-interpolate.py.txt](https://github.com/numpy/numpy/files/309789/test-ma-interpolate.py.txt)

**Comment by rgommers** [comment]
IIRC this raises an error on purpose, because masked array inputs were always accepted without checking the mask and just using the data no matter if it was masked or not. So your code was probably buggy.

@ev-br this was one of your PRs, can you confirm?

**Comment by rgommers** [comment]
This is a Scipy issue by the way, so this is the wrong issue tracker. So closing. But let's continue the discussion before opening a scipy issue.

**Comment by ev-br** [comment]
Hmm, masked arrays are not supported  by `interp1d`, I'd say. If they work, that's accidental, likely depends on the interpolation kind and is likely buggy. Let's see:

```
In [18]: x = np.ma.array([1, 2, 3, 1000, 5], mask=[False, False, False, True, False])

In [19]: y = x

In [20]: interp1d(x, y, kind='linear')(4)
Out[20]: array(4.0)

In [21]: import scipy

In [22]: scipy.__version__
Out[22]: '0.18.0.dev0+01529bc'
```

What fails is evaluating the interpolant on a masked array:

```
In [23]: interp1d(x, x)(x)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-cfdf2b2e4ebe> in <module>()
----> 1 interp1d(x, x)(x)

/home/br/virtualenvs/scipy_py27/local/lib/python2.7/site-packages/scipy/interpolate/polyint.pyc in __call__(self, x)
     76 
     77         """
---> 78         x, x_shape = self._prepare_x(x)
     79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)

/home/br/virtualenvs/scipy_py27/local/lib/python2.7/site-packages/scipy/interpolate/polyint.pyc in _prepare_x(self, x)
     88     def _prepare_x(self, x):
     89         """Reshape input x array to 1-D"""
---> 90         x = _asarray_validated(x, check_finite=False, as_inexact=True)
     91         x_shape = x.shape
     92         return x.ravel(), x_shape

/home/br/virtualenvs/scipy_py27/local/lib/python2.7/site-packages/scipy/_lib/_util.pyc in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    184     if not mask_ok:
    185         if np.ma.isMaskedArray(a):
--> 186             raise ValueError('masked arrays are not supported')
    187     toarray = np.asarray_chkfinite if check_finite else np.asarray
    188     a = toarray(a)

ValueError: masked arrays are not supported
```

Git blame points to https://github.com/scipy/scipy/commit/cd6587d77521fd293c020e8357a1cd5f6a3c8304 which added `_asarray_validated`.

IMO not allowing masked arrays is correct. For missing data, a recommended workaround is Julian's trick of using Univariatespline(..., s=0) with zero weights, http://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html

**Comment by ev-br** [comment]
I now see there was a complaint already: https://github.com/scipy/scipy/commit/cd6587d77521fd293c020e8357a1cd5f6a3c8304#commitcomment-15974228

There was no pull request and this was forgotten :-(.

**Comment by ev-br** [comment]
All that being said, if there's a pull request which implements and tests all interpolation kinds for various combinations of masked arrays and regular ndarrays, I personally won't be opposed.
