### ISSUE TITLE
einsum - bug when sublist index values are between 26 and 52.

### ISSUE THREAD

**Issue by hpaulj** [numpy/numpy#7741]
In the `einsum(op0, sublist0, op1, sublist1, ..., [sublistout])` form of input, index numbers cannot be larger than 26, even though the subscript version allows any alpha (the 52 upper and lower case values).  This is due to a bug in the function that converts the lists to subscripts.

`core/src/multiarray/multiarraymodule.c`
   `einsum_list_to_subscripts`

tests that an index number is in the [0,52] range

```
       if ( s < 0 || s > 2*26) {
            PyErr_SetString(PyExc_ValueError,
                    "subscript is not within the valid range [0, 52]");
            Py_DECREF(obj);
            return -1;
        }
```

and then maps it on to the alpha character set:

```
        if (s < 26) {
            subscripts[subindex++] = 'A' + s;
        }
        else {
            subscripts[subindex++] = 'a' + s;
        }
```

The last case maps on to '{|}~\x7f...`.   It should instead be

```
   subscripts[subindex++] = 'a' + s -26;
```

I elaborate on this in a Stackoverflow answer  http://stackoverflow.com/a/37796451/901925

We might also want to document that these values have to be in the [0, 52] range.

**Comment by OmerJog** [comment]
Wasn't this fixed?

**Comment by mattip** [comment]
Yes, it was. Closing.

**Comment by davystrong** [comment]
This still appears to be broken in version 1.24.3, however only at index 32:
```python
a = np.array([[1]], dtype=np.uint8)
# Works
np.einsum(*[x for i in range(31) for x in [a, [i, i+1]]])
# Throws ValueError: too many operands
np.einsum(*[x for i in range(32) for x in [a, [i, i+1]]])
```

**Comment by charris** [comment]
I suspect this is because numpy arrays can have at most 32 dimensions. There has been discussion about increasing that number, but it is a very intrusive change.

**Comment by davystrong** [comment]
Hmm, possibly. Though just to clarify, the output of my example is only a 2D array, so presumably it's something internal to how `einsum` works. Thanks though, didn't realise Numpy had this limit.
