### ISSUE TITLE
Error passing rpath from gfortran when linking on OSX

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#7750]
I was trying to build scipy with OpenBLAS, when I ran into this error:

```
    /usr/local/bin/gfortran -Wall -g -arch x86_64 -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.6-intel-2.7/scipy/integrate/_quadpackmodule.o -L/Users/mb312/usr/local32/lib -L/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2 -Lbuild/temp.macosx-10.6-intel-2.7 -Wl,-rpath="/Users/mb312/usr/local32/lib" -lquadpack -lmach -lopenblas -lopenblas -lgfortran -o scipy/integrate/_quadpack.so
    ld: unknown option: -rpath=/Users/mb312/usr/local32/lib
    collect2: error: ld returned 1 exit status
    ld: unknown option: -rpath=/Users/mb312/usr/local32/lib
    collect2: error: ld returned 1 exit status
```

I believe this is because the incantation to the OSX linker should be of form `-Wl,-rpath,"/Users/mb312/usr/local32/lib"` rather than `-Wl,-rpath="/Users/mb312/usr/local32/lib"` - see : http://stackoverflow.com/questions/26472590/ld-unknown-option-rpath-libs-linking-error-while-building-openframework

At least - with this diff to numpy, scipy compiled without error:

```
diff --git a/numpy/distutils/fcompiler/gnu.py b/numpy/distutils/fcompiler/gnu.py
index 9ba5759..6966168 100644
--- a/numpy/distutils/fcompiler/gnu.py
+++ b/numpy/distutils/fcompiler/gnu.py
@@ -230,7 +230,7 @@ class GnuFCompiler(FCompiler):
         return []

     def runtime_library_dir_option(self, dir):
-        return '-Wl,-rpath="%s"' % dir
+        return '-Wl,-rpath,"%s"' % dir

 class Gnu95FCompiler(GnuFCompiler):
     compiler_type = 'gnu95'
```

I doubt this is the right fix in general, so posting here to ask for advice.

**Comment by njsmith** [comment]
Seems like it could be the right fix to me, as long as gnu binutils ld also accepts the `-rpath foo` syntax. Does it?

**Comment by charris** [comment]
Looks right from what I can see with google. `-Wl` is a option for passing options, hence the arguments follow as a list. Or that is what I can make out...

**Comment by njsmith** [comment]
Yeah, the argument `"-Wlfoo,bar"` passed to the compiler is the same as the arguments `["foo", "bar"]` passed to the linker. So the question is just whether the linker understands these arguments.

**Comment by rgommers** [comment]
This issue is no longer relevant, hence closing - thanks all.
