### ISSUE TITLE
Objections to upload of Python 3.5 OSX wheels for CI builds?

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#7755]
Hi,

I have two built wheels for numpy, python 3.5 that I use fairly often for testing in CI setups:

```
numpy-1.7.1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
numpy-1.9.2-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
```

Both these wheels will, if installed, fail their tests - but of course this is also true of the current situation where users will get an sdist instead of the wheel for `pip install numpy==1.9.2` etc.

I use these to build packages against the earliest possible versions of numpy, for back-compatibility. 

I can't see how uploading these would hurt, and it will help CI builds, but I'm checking here in case I haven't thought of something.

**Comment by rgommers** [comment]
> I use these to build packages against the earliest possible versions of numpy, for back-compatibility. 

Hmm, the earliest release that supports Python 3.5 is 1.10.0. So why would you need to build against older versions, especially if they also have failing tests?

**Comment by matthew-brett** [comment]
Let's imagine that someone does have numpy installed at an earlier version (nothing to stop that happening, after a build from source).   Particularly for 1.9.3, there's a single uninteresting test failure, so they won't have noticed the problem.  Then they install - say - matplotlib, which we built with numpy 1.10, and they get a nasty dtype error on import.   The cost of building against the earlier version seemed pretty small (is there one?) compared to the cost of breaking the the installed package, when they have an old numpy.

**Comment by rgommers** [comment]
I see your point, but I have the feeling that this may become problematic in the long run. How many test failures are acceptable? And how do other package maintainers know what version of numpy to build against? At least "the first numpy version to support a given Python version" is consistent.

The use case you're describing is inherently a bit fragile - you have to use ``pip`` either without version pinning or with ``--no-binary`` or ``--only-binary`` to be robust against this kind of binary incompatibility.

**Comment by matthew-brett** [comment]
So, we're only talking about the odd case where the user has somehow installed an oldish version of numpy that gives test errors on Python 3.5.  Now they are installing - say - matplotlib, and they somehow fail to upgrade numpy.   We have two options:

* Give them a nasty crash on import that won't give them much hint as to what the problem is or;
* Let this work correctly, which lets them sail on with an old numpy that gives test errors.

I suppose one could argue that the first is better because it lets the user know there's a problem with their numpy, but that doesn't seem a good way of telling them.

**Comment by njsmith** [comment]
This is somewhat orthogonal to the main point here, but for the specific point you mention, matplotlib wheels built against the numpy 1.10 api should include an install-requires numpy >= 1.10. We're really bad about this right now, but sooner or later we need to start making this metadata more accurate.

**Comment by matthew-brett** [comment]
Right - here I'm just trying to reduce the amount of puzzling breakage in the rather messy situation we are in right now.

**Comment by rgommers** [comment]
> I suppose one could argue that the first is better because it lets the user know there's a problem with their numpy

That's not my point at all. Of course a crash is not better. But we need to figure out a few guidelines for when to upload which wheels. Uploading a couple of wheels now just because you have them at hand feels a bit too ad hoc. Why for 1.7.1 and not for 1.7.2, 1.8.x, etc.? What do we do when Python 3.6 comes out?

The only simple and consistent rule I can think of is uploading Numpy wheels for supported Python versions for that release, and doing that at the moment we cut the release.

**Comment by rgommers** [comment]
> This is somewhat orthogonal to the main point here, but for the specific point you mention, matplotlib wheels built against the numpy 1.10 api should include an install-requires numpy >= 1.10

If there have to be new MPL wheels, then this is a better solution (despite my strong dislike of the current ``pip`` upgrade behavior with ``install_requires``).

**Comment by matthew-brett** [comment]
Yes, sure, this is not a situation that I was imagining we need a simple and consistent rule.

I think this is a case where doing something not consistent would help and do no harm.

The dtype error applies to all packages that depend on numpy, so can't be fixed except by persuading all upstream packages to declare their dependencies correctly, so my suggestion is to help work round that problem until we have done that.

**Comment by rgommers** [comment]
> The dtype error applies to all packages that depend on numpy, so can't be fixed except by persuading all upstream packages to declare their dependencies correctly, so my suggestion is to help work round that problem until we have done that.

This by itself doesn't work around anything though. The actual workaround is to upload new MPL (/ Scipy / Scikit-learn / ...) wheels. Those can be uploaded in two ways, (a) built against an older numpy, and (b) with an ``install_requires`` added. I guess (b) takes a little more convincing, but other than that it's not more work.

By the way, don't you anyway have the problem that re-uploading a wheel with the same name is not possible on PyPI? Or are you planning to change the wheel name in some non-meaningful way?

**Comment by rgommers** [comment]
Other thought: given that these wheels just help with CI, what is the issue with just having them available at http://wheels.scipy.org/? They don't really need to be on PyPI.

**Comment by matthew-brett** [comment]
Pypi is much more reliable than the Rackspace containers, and is https by default.  Anyway - closing this, and I'll work round it.
