### ISSUE TITLE
argsort result

### ISSUE THREAD

**Issue by kivinju** [numpy/numpy#7767]
I tried
`np.argsort(np.array([-1, -2, -3, -3]))`
I expected
`[3, 2, 1, 0]`
but the result is 
`[2, 3, 1, 0]`
How can I argsort this array?

**Comment by njsmith** [comment]
```
In [2]: a = np.array([-1, -2, -3, -3])

In [3]: a[np.argsort(a)]
Out[3]: array([-3, -3, -2, -1])
```

Looks sorted to me. Why were you expecting the repeated `-3`s to be reversed? Or did you mean to use `[-1, -2, -3, -4]`?
```
In [4]: np.argsort(np.array([-1, -2, -3, -4]))
Out[4]: array([3, 2, 1, 0])
```

(Closing because there's nothing else for us to do right now, feel free to re-open and add more information if you still have a problem.)
