### ISSUE TITLE
Installing numpy (with python3) overwrites existing python2 f2py executible

### ISSUE THREAD

**Issue by MarkWieczorek** [numpy/numpy#7769]
By installing python2.7, and then using pip to install numpy, the `f2py` executible was created here

```
/usr/local/bin/f2py
```

However, if I now install python3.5, and then use pip3 to install numpy, the prexisting python2.7 `f2py` executible gets overwritten by the python3.5 `f2py` version. Given that the two versions of `f2py` are not compatible, this is a problem.

In my opinion, pip3 should install an executible `f2py3` in order to distinguish it from the python2 `f2py`.

In any case, there is a way to get around this problem: instead of using the executibles, one could use the following commands instead (which as far as I can tell are identical):

```
python -m numpy.f2py
python3 -m numpy.f2py
```

Notes: python2.7 and 3.5 were installed by brew on OSX.

**Comment by rgommers** [comment]
> In my opinion, pip3 should install an executible f2py3 in order to distinguish it from the python2 f2py

The latest installed version gets the generic ``f2py``, this is expected behavior and the same as for other executables (``python``, ``ipython``, etc.).

I also see on my machine that in addition to ``f2py``, there are python-version-specific executables installed (``f2py3.4`` etc.)

**Comment by rgommers** [comment]
The ``python -m numpy.f2py`` will indeed be identical

**Comment by MarkWieczorek** [comment]
On OSX, using `pip` and `pip3`, only a single binary file is generated: `f2py` (it is not a link).

Even though I have version specific binaries of python (such as `python2.7`, `python3.5`, along with links to generic names like `python`), this is not the case with `f2py` on my system. 

So, I still think that this is a bug, but that it is probably OSX specific.

**Comment by MarkWieczorek** [comment]
I should also add that if I uninstall the python2.7 version of numpy, and reinstall it
~~~~
pip2.7 uninstall numpy
pip2.7 install numpy
~~~~
that this also creates a single `f2py` binary that overwrites the existing one. Again, I think that it would be more logical to name this binary `f2py2.7`.

**Comment by rgommers** [comment]
OK, if on OS X no Python-specific versions are installed, that's indeed a bug. An install should generate both ``f2py`` and ``f2py2.7`` or ``f2py3.x``

**Comment by materialjan** [comment]
It seems I have the same problem on os x 10.13.6
Can't make co-exist numpy for python2 and python3. One is overwritten by the other...

**Comment by seberg** [comment]
I am no tsure we can fix that easily, I think you should probably just use `python -m numpy.f2py ...` not sure if that should be documented somewhere?

**Comment by seberg** [comment]
Oh sorry, this has been discussed before. @materialjan so you do not have to the python specific versions `f2py2.7`, etc.?

**Comment by materialjan** [comment]
Sorry i'm not a dev.
When i try to use` f2py2.7` or `f2py2` it goes straight to python3.7
```
MacBook:~ macbook$ /usr/local/bin/f2py2
'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "/usr/local/bin/f2py2", line 6, in <module>
    from numpy.f2py.f2py2e import main
  File "/usr/local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

```

But if uninstall numpy for python3 it works, maybe something wrong in my paths

**Comment by seberg** [comment]
@materialjan can you check what: `cat $(which f2py2.7)` or `cat $(which f2py2)` print? It should have the correct shbang to pick the right interpreter...

**Comment by materialjan** [comment]
```
MacBook:~ macbook$ which f2py2.7
/usr/local/bin/f2py2.7
```
```
MacBook:~ macbook$ which f2py2
/usr/local/bin/f2py2
```

this is post python3 numpy install
hope this help

**Comment by seberg** [comment]
Heh, you removed the `cat` part, I wanted to know what is inside (specifically the first line) of `/usr/local/bin/f2py2.7` and `/usr/local/bin/f2py2`. It should give a version specific python executable there, you could check that those add up.

**Comment by materialjan** [comment]
aha sorry I don't know what i'm doing
`cat $(which f2py2)` is outputting the same
```
MacBook:~ macbook$ cat $(which f2py2.7)
#!/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
# -*- coding: utf-8 -*-
import re
import sys

from numpy.f2py.f2py2e import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by seberg** [comment]
@materialjan there is something wrong with your `PYTHONPATH` or so, I think. Otherwise this does not really make sense to me. Obviously `#!/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python` is a very specific (correct) python version. So that python version picks up the wrong numpy apparently.

**Comment by HaoZeke** [comment]
Closing as a probable polluted `PYTHONPATH` issue
