### ISSUE TITLE
result dtype depends on scalar's value (not just its dtype)

### ISSUE THREAD

**Issue by alan-isaac** [numpy/numpy#7770]
Nathan Smith suggested the following behavior should be considered a bug:

```
>>> (np.int64(2**6)*np.arange(5,dtype=np.int8)).dtype
dtype('int8')
>>> (np.int64(2**7)*np.arange(5,dtype=np.int8)).dtype
dtype('int16')
```

**Comment by seberg** [comment]
Thanks for the (old) report. The value based casting is a recuring problem, and I am pretty sure we have tracking issues about these things with more discussion on them, so I will close this.
