### ISSUE TITLE
Compound `logical_and` queries.

### ISSUE THREAD

**Issue by jbn** [numpy/numpy#7772]
I run into this problem all the time. I'm sure I'm missing some existing method, but I couldn't find it. Is there a simple way to use boolean indexing over many conditions. That is, 

```python
sub_df = df[f(df['Age'] > 30, 
              df['State'] == 'NJ',
              df['Sex'] = 'M')]
```

I've been using the following utility function for a while. 
```python
from functools import reduce
def np_conditions(condition, *conditions):
    return reduce(np.logical_and, conditions, condition)
```

leaving

```python
sub_df = df[np_conditions(df['Age'] > 30, 
                          df['State'] == 'NJ',
                          df['Sex'] = 'M')]
```

I assume there this is a solved problem and I appreciate any course headings! If this doesn't exist, I'll submit a PR (based on feedback). I just think PRs are noisier without prior questions.

**Comment by pv** [comment]
sub_df=  df[(df['Age'] > 30) &
             (df['State'] == 'NJ') &
             (df['Sex'] ==  'M')]

**Comment by jbn** [comment]
@pv Sorry, I should have been more verbose (rarely my problem). I meant a solution, excluding that parenthesizing style. For elaborate conditions, it always starts to feel noisy. And, sometimes, I confuse it with function invocation. 

I liked my reducing function because it's less noisy and it reads more like conjunctions in probability statements. It's certainly not a major issue, but I was hoping there was already some `logical_and` that accepted varargs.

**Comment by seberg** [comment]
Pauli's suggestion is the only other alternative really. If you had a large array, you could also use `np.logical_and.reduce`, but since you have multiple arrays, that is about as good as it gets. `logical_and` is a binary unary function, and as such cannot accept varargs. I think creating your own simple function is simply the right solution.

**Comment by seberg** [comment]
`np.all` and `np.any` are aliases for `np.logical_and`, and `np.logical_or` but any numpy function will not be made to handle your thing better then your own reduce solution.
