### ISSUE TITLE
How to accumulate an array by index in numpy?

### ISSUE THREAD

**Issue by maplewizard** [numpy/numpy#7776]
I have an array:

    a = np.array([0,0,0,0,0,0])

I want to add some other array into each index of a, while the index can appear more than one times. I want to get the some of each index. I write:

    a[np.array([1,2,2,1,3])] += np.array([1,1,1,1,1])

but get a to be:

    array([0, 1, 1, 1, 0, 0])

But what I want is to get:

    array([0, 2, 2, 1, 0, 0])

How to implement this in numpy without for loop?

**Comment by njsmith** [comment]
You want the not-well-known `at` method that all binary ufuncs have. For example, `np.add` is a binary ufunc, specifically the one that's used to implement `+` for arrays:
```
In [1]: a = np.array([0,0,0,0,0,0])

In [2]: np.add.at(a, np.array([1,2,2,1,3]), np.array([1,1,1,1,1]))

In [3]: a
Out[3]: array([0, 2, 2, 1, 0, 0])
```

**Comment by seberg** [comment]
If you want add specificially, you can use `np.bincount` as well, it should be quite a lot faster.
