### ISSUE TITLE
misleading error message when using ```hstack```

### ISSUE THREAD

**Issue by xuewei4d** [numpy/numpy#7782]
``` python
a = np.random.rand(10, 2)
b = np.random.rand(10, 2)
b = csc_matrix(b)
np.hstack((a, b))

ValueError: all the input arrays must have same number of dimensions
```

I think it should raise like 'cannot stack sparse matrix'?

Thanks,

**Comment by saullocastro** [comment]
To perform `hstach` in sparse matrices you should use `scipy.sparse.vstack` instead. See this post for an example:

http://stackoverflow.com/q/18417906/832621

**Comment by xuewei4d** [comment]
@saullocastro My point is that the error message is not correct

**Comment by pv** [comment]
hstack does not know anything about sparse matrices, so the error 
condition is the same as for `np.hstack((np.random.rand(10,2), None))`.

**Comment by seberg** [comment]
The error message is correct, since `np.asarray(sparse_matrix)` gives a 0-D array back. That is a general confusion/issue which might be possible (may even have been to some degree?) to mitigate in the sparse code. Also it is a known and open issue, so closing this one.

**Comment by njsmith** [comment]
I believe we had agreement that we should deprecate silent casting of unrecognized objects to 0d object arrays, exactly because of confusing cases like this. No one has actually implemented that yet, though.

**Comment by seberg** [comment]
Right, making `dtype=object` forced if you want an object array.... Or maybe an `allow_object` argument, I am not sure if we even hashed out the details quite. But yes, I think any thought out proposal will be merged quickly ;).
