### ISSUE TITLE
median should respect custom types

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#7787]
The behaviour of `median` is inconsistent with the behaviour of other `ufunc`s, such as `mean` and `max`, when operating on custom types.  For example, when using the `pint` `Quantity` type, `mean` and `max` return something of type `Quantity`, but `median` does not:

```
In [1]: import pint

In [2]: ureg = pint.UnitRegistry()

In [3]: x = linspace(0, 10, 30)**2 * ureg.km

In [4]: mean(x)
Out[4]: <Quantity(33.9080459770115, 'kilometer')>

In [5]: max(x)
Out[5]: <Quantity(100.0, 'kilometer')>

In [6]: median(x)
Out[6]: 25.029726516052317
```

This is caused by the first line of `numpy.lib.function_base._median`:

```
    a = np.asanyarray(a)
```

I don't know why that line is there.  Clearly, changing this would potentially break backward-compatibility, but for the sake of consistency, it may still be desirable in the long term.

**Comment by mhvk** [comment]
The difference is that `np.max`, `np.mean` etc will let themselves be overridden by a corresponding method on the input (which I think you define in your quantity class). It is not so obvious how one would do that for functions that do not have corresponding methods; a possibility might be via `__array_wrap__` which is used by the likes of `np.insert`.

p.s. At some point we should compare notes on problems/solutions between `pint` and `astropy.units` (and possibly also whatever is used by `amuse`); with our `Quantity` being an `ndarray` subclass, `np.median` works but other functions like `concatenate`, `hstack`, and `dot`, do not.

**Comment by gerritholl** [comment]
(it's not my Quantity class, I'm just a user)

**Comment by seberg** [comment]
With the new `__array_function__` protocol and all the work going into that direction, I think this is now an issue that pint has to deal with, and not an issue with numpy. Please reopen if there is something numpy may have to do here.
