### ISSUE TITLE
numpy.test(): relocation R_X86_64_PC32 against symbol `fun_' can not be used

### ISSUE THREAD

**Issue by sjackman** [numpy/numpy#7794]
With numpy ~~1.11.0~~ (correction) 1.11.1 `numpy.test()` gives the following error:

```
/gsc/btl/linuxbrew/bin/gfortran -Wall -g -L/gsc/btl/linuxbrew/lib -Wl,--dynamic-linker=/gsc/btl/linuxbrew/lib/ld.so -Wl,-rpath,/gsc/btl/linuxbrew/lib -shared /tmp/tmp71Zjud/tmp/tmp71Zjud/src.linux-x86_64-2.7/_test_ext_module_5403module.o /tmp/tmp71Zjud/tmp/tmp71Zjud/src.linux-x86_64-2.7/fortranobject.o /tmp/tmp71Zjud/tmp/tmp1ORQ11/tmptbgkJq.o -L/gsc/btl/linuxbrew/lib -L/gsc/btl/linuxbrew/opt/openssl/lib -L/gsc/btl/linuxbrew/opt/sqlite/lib -L/gsc/btl/linuxbrew/Cellar/python/2.7.11/lib -lpython2.7 -lgfortran -o ./_test_ext_module_5403.so
/gsc/btl/linuxbrew/bin/ld: /tmp/tmp71Zjud/tmp/tmp1ORQ11/tmptbgkJq.o: relocation R_X86_64_PC32 against symbol `fun_' can not be used when making a shared object; recompile with -fPIC
/gsc/btl/linuxbrew/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

A gist of the build logs are found here:
https://gist.github.com/sjackman/038b13b0becc4965bca7bd73238e278b#file-03-python-L105

**Comment by charris** [comment]
What system are you running on?

**Comment by sjackman** [comment]
Linuxbrew with Python 2.7.11 and GCC 5.3.0. See this gist for more info: https://gist.github.com/sjackman/038b13b0becc4965bca7bd73238e278b#file-00-config-out

**Comment by sjackman** [comment]
numpy 1.11.0 previously built correctly (I haven't tried rebuilding it recently), and I'm seeing this error with numpy 1.11.1.

**Comment by mattip** [comment]
Does this still fail or can we close?

**Comment by sjackman** [comment]
I never managed to build `1.11.1`, but `1.11.2` and subsequent versions up to `1.14.1` build fine.

**Comment by charris** [comment]
@sjackman Closing then, thanks for the feedback.
