### ISSUE TITLE
Error in convergence for smallest eigenvectors of sparse Laplacian matrix

### ISSUE THREAD

**Issue by guillean** [numpy/numpy#7795]
Currently, I'm computing the eigenvectors of the laplacian for a spectral embedding problem I'm working on. The following minimal working example:

```python
import numpy as np
import scipy.sparse as sparse
import scipy.sparse.linalg as linalg

adj_mat = np.load('adj_mat.npy').tolist()

def weight_to_lapl(W):
    d = np.array(W.sum(axis=0))[0,:]
    D = sparse.spdiags(d, 0, d.size, d.size)
    return D - W

L, V = linalg.eigsh(weight_to_lapl(adj_mat), k=3, which='SM')
```
with the file [adj_mat.zip](https://github.com/numpy/numpy/files/341777/adj_mat.zip).

In particular, I get the following error:

```python
/root/CentOS6/x86_64/Python/2.7.11-03st/lib/python2.7/site
-packages/scipy/sparse/linalg/eigen/arpack/arpack.pyc in _raise_no_con
vergence(self)
    365             vec = np.zeros((self.n, 0))
    366             k_ok = 0
--> 367         raise ArpackNoConvergence(msg % (num_iter, k_ok, self.
k), ev, vec)
    368
    369

ArpackNoConvergence: ARPACK error -1: No convergence (23211 iterations
, 0/3 eigenvectors converged) [ARPACK error -14: DNAUPD  did not find
any eigenvalues to sufficient accuracy.]
```

I'm unsure what is causing this error as the problem doesn't seem too ill-posed (in particular, there is a single zero eigenvalue as the graph is connected, but everything else should be non-zero).

**Comment by charris** [comment]
Wrong project. The scipy repository is at https://github.com/scipy/scipy

**Comment by guillean** [comment]
@charris Yes, you're totally right, pardon me!

**Comment by pv** [comment]
@guillean: non-convergence is not immediately a bug, so stackoverflow.com may be a better place to ask than these issues (which are for bug reports).

Also: try shift-invert mode instead which='SM'.

**Comment by guillean** [comment]
@pv That worked quite nicely; I wasn't aware of the option! Thank you.
