### ISSUE TITLE
AVX detection fails on MacOS if $PATH doesn't contain /usr/sbin

### ISSUE THREAD

**Issue by depp** [numpy/numpy#7801]
Only on MacOS.  Installed 1.11.1 via pip on Python 3.5.2.

```
~ $ PATH=/usr/local/bin:/usr/bin:/bin python3 -c 'import numpy'
sh: sysctl: command not found
~ $ PATH=/usr/sbin:/usr/local/bin:/usr/bin:/bin python3 -c 'import numpy'
```

See: https://github.com/numpy/numpy/blob/1429c606643d1ad305e710c4a31cb6f398d04c53/numpy/_build_utils/src/apple_sgemv_fix.c#L69

Note that this uses `system()`, which is just plain silly, and explains why it fails if the environment variables are not what you expect.  Here is an alternative, self-contained program that works more reliably:

```
#include <stdio.h>
#include <sys/types.h>
#include <sys/sysctl.h>
int cpu_supports_avx(void) {
    int enabled, r;
    size_t length = sizeof(enabled);
    r = sysctlbyname("hw.optional.avx1_0", &enabled, &length, NULL, 0);
    return r == 0 && enabled != 0;
}
int main(int argc, char **argv) {
    printf("AVX supported: %d\n", cpu_supports_avx());
    return 0;
}
```

**Comment by njsmith** [comment]
...you're right, that is pretty silly. Any interest in turning that into a real pull request?

(You might also run into a similar issue with the `using_mavericks` macro.)

**Comment by depp** [comment]
I am interested in making a pull request, but it might take me a little longer.  We'll see.

**Comment by ron819** [comment]
@depp are you still working on this?
