### ISSUE TITLE
multidimensional indexing

### ISSUE THREAD

**Issue by dokato** [numpy/numpy#7805]
Hi,
I have a problem with indexing. Not sure if this is a bug, or I don't understand something.
Let's say that I have a 4D matrix and I want to pick specific items from last two dimensions:

```python
>>> a = np.ones((12,10,5,5))
>>> b = a[:,:,[0,3], [0,3]]
>>> b.shape
 (12L, 10L, 2L)
```

I expected rather `(12L, 10L, 2L, 2L)`. What's wrong?

I use Python 2.7.11 and Numpy 1.10.0.

**Comment by seberg** [comment]
Nothing is wrong, that is how multidimensional indexing works currently. You can check the documentation/reference guide it will explain it as well. Also https://github.com/numpy/numpy/pull/6256/files?short_path=01e4dd9#diff-01e4dd9d2ecf994b24e5883f98f789e6 explains some things. What you expect is the "outer" type indexing, what you get is the legacy/fancy type indexing. Basically all index arrays are iterated as one, so you have to change your code to `b = a[:,:,[[0],[3]], [0,3]]`
