### ISSUE TITLE
Python3: Comparing "bytes" vs "str", array vs scalar

### ISSUE THREAD

**Issue by jzwinck** [numpy/numpy#7806]
Let me start by saying I'm not certain what the right solution is here, but the current behavior certainly can be improved.  In Python 3:

```
>>> np.array([b'x',b'y',b'z']) == b'z'
array([False, False,  True], dtype=bool) # expected

>>> np.array([b'x',b'y',b'z']) == 'z'
False

>>> np.array([b'x',b'y','z']) == b'x'
False
```

What's happening is that when the input values to `np.array()` are _all_ `bytes` type, the resulting array has dtype "S", rather than "U" which it would have if at least one input value were `str` (Unicode).

In the second case, where all the array elements are `bytes` and the scalar is `str`, I can see an argument that returning a scalar in today's NumPy (1.11.1) is consistent with other cases where an array is compared against a scalar of an incompatible type.  _However_, those other cases produce warnings:

```
>>> np.array(['x','y','z']) == 4 
__main__:1: FutureWarning: elementwise comparison failed; returning scalar instead,
        but in the future will perform elementwise comparison
False

>>> np.array(['x','y','z']) == None
__main__:1: FutureWarning: comparison to `None` will result in an elementwise object
        comparison in the future.
False
```

So I think comparing a `bytes` array against a `str` scalar should also result in a warning, and in the future, an elementwise comparison.

The third case is really surprising.  Apparently NumPy is happy to coerce the first two elements of the array from `bytes` to `str`, but then it refuses to compare them.  If one of the input elements was `b'x'` and I compare against that very same scalar, I would expect a bool array result `[True, False, False]` (or I would expect the array construction to have failed because the types are incompatible).

**Comment by seberg** [comment]
This is fixed in master, string comparisons are well defined after all. I had a bit of a cleanup with unicode byte orders, and that also cropped (gh-7664):

```
In [3]: np.array([b'x',b'y',b'z']) == b'z'
Out[3]: array([False, False,  True], dtype=bool)

In [4]: np.array([b'x',b'y',b'z']) == 'z'
Out[4]: array([False, False,  True], dtype=bool)

In [5]: np.array([b'x',b'y','z']) == b'x'
Out[5]: array([ True, False, False], dtype=bool)
```

**Comment by seberg** [comment]
Do you think the warning phase is badly needed? Hadn't really thought about it when fixing it I guess.

**Comment by seberg** [comment]
The thing is, that in python 2, it already returns the boolean arrays (even if you manually make them U arrays), so not sure.

**Comment by seberg** [comment]
Hmmmm, sorry. I tested the wrong python version. It is of course still the same result. The result is right in the sense of incompatible type, since python also has `'a' != b'a'`. So I am not sure what one should change here.

**Comment by seberg** [comment]
I have to rethink this more thoroughly, sorry. One could expect the result to be always an array of `False` with incorrect types as well?

**Comment by njsmith** [comment]
Yeah, is definitely a bug if you can get a scalar output from `==` with no warning :-/.

**Comment by jzwinck** [comment]
@seberg: As far as what to change, at a minimum there needs to be a warning saying "elementwise comparison failed" as there is if you compare an array of strings against a number.

The more tricky part is what to do about my third example: where an array is constructed from a mix of `bytes` and `str` and NumPy coerces everything to `str`, resulting in failure to compare against the original input value.  If coercion is allowed during construction, perhaps it ought to be allowed during comparison as well.  I think this solution is superior to a mere warning with wrong result.

**Comment by njsmith** [comment]
I missed the point of your third example too. IMO numpy definitely should not be silently coercing bytestrings to Unicode in python 3, and possibly not in python 2 either. But, it's a separate orthogonal bug to the comparison issue -- could you file it separately?

**Comment by jzwinck** [comment]
@njsmith I just started writing an issue for that but realized my heart isn't in it: I actually like the way that coercion works during construction now.  I'm not claiming that the coercion should not happen--the only bugs I intended to describe here are about comparison.
