### ISSUE TITLE
np.linalg.svd not giving expected results.

### ISSUE THREAD

**Issue by Jonksar** [numpy/numpy#7812]
According to numpy for matlab users doc (https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html)

[U, S, V] = svd(X) is equivelant to U, S, Vh = np.linalg.svd(X); V = Vh.T

Matlab:

```
>> [U, S, V] = svd(ones(3,3))
U =

  -0.57735  -0.57735  -0.57735
  -0.57735   0.78868  -0.21132
  -0.57735  -0.21132   0.78868

S =

Diagonal Matrix

   3.00000         0         0
         0   0.00000         0
         0         0   0.00000

V =

  -0.57735   0.81650   0.00000
  -0.57735  -0.40825  -0.70711
  -0.57735  -0.40825   0.70711
```

In numpy:

```
import numpy as np

U, S, Vh = np.linalg.svd(np.ones((3,3))); V = Vh.T

print '\n\n'.join(map(str, [U, S, V]))

[[-0.57735027 -0.57735027 -0.57735027]
 [-0.57735027 -0.21132487  0.78867513]
 [-0.57735027  0.78867513 -0.21132487]]

[ 3.  0.  0.]

[[-0.57735027  0.          0.81649658]
 [-0.57735027 -0.70710678 -0.40824829]
 [-0.57735027  0.70710678 -0.40824829]]
```

**Comment by njsmith** [comment]
What specifically is the problem?

**Comment by Jonksar** [comment]
The matrix U, V columns 2, 3 are switched.

**Comment by Jonksar** [comment]
This works exactly like MatLabs version. 

```
    U, S, V = np.linalg.svd(eye(3,3))
    V = V.T
    V[:, [1, 2]] = V[:, [2, 1]]
    U[:, [1, 2]] = U[:, [2, 1]]
```

**Comment by njsmith** [comment]
The order of those two columns is arbitrary -- the columns are sorted in order of descending singular values, but those have the same singular value (0). So both answers are correct, and you could probably get either answer out of either MATLAB or numpy depending on various random environmental/configuration details.
