### ISSUE TITLE
Complex arrays: view and transpose

### ISSUE THREAD

**Issue by achrist42** [numpy/numpy#7815]
The real view of a transposed complex 2D array gives the wrong result. A (n x m) array is mapped onto a (2n x m) array instead of a (n x 2m) array. Explicitly copying the array fixes the issue. Example:

```
import numpy as np
a = np.array([[1 + 1j, 2 + 2j], [3 + 3j, 4 + 4j]])
b = a.transpose()
c = b.copy()

# Real view of a complex array
print(a.view('float'))
# Real view of transposed complex array (wrong)
print(b.view('float'))
# Real view of copied transposed complex array (correct)
print(c.view('float'))
```

Python 3.5.1
Numpy 1.10.4

**Comment by pv** [comment]
The result is correct --- `.view(float)` means "real-valued view of the array" only for contiguous arrays.

**Comment by seberg** [comment]
Its a weird thing with how view works and we actually have been discussing deprecating the behaviour elsewhere. The deprecation is in process in current master:
```
In [5]: print(a.view('float'))
[[ 1.  1.  2.  2.]
 [ 3.  3.  4.  4.]]

In [6]: print(b.view('float'))
runtests.py:1: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
```

**Comment by achrist42** [comment]
Thanks a lot for the information. I was not aware that this was already taken care of. Deprecation sounds good.
