### ISSUE TITLE
numpy.zeros((0, 2**31-1)) raises MemoryError

### ISSUE THREAD

**Issue by cgohlke** [numpy/numpy#7819]
Using numpy-1.11.1 with the patch for issue #7813 on 64-bit Python, creating an array of size=0 several times raises `MemoryError` on a Windows 10 system with 32 GB RAM:
```Python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> a = numpy.zeros((0, 2**31-1))
>>> a.size
0
>>> a = numpy.zeros((0, 2**31-1))
>>> a = numpy.zeros((0, 2**31-1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
``` 
According to the the VMMap tool, every call to `numpy.zeros((0, 2**31-1))` allocates ~16GB on the heap.
I would not expect the creation of an array of size=0 to fail with `MemoryError` (64-bit) or `ValueError` (32-bit).

**Comment by cgohlke** [comment]
See also https://github.com/numpy/numpy/issues/7813#issuecomment-231568548

**Comment by seberg** [comment]
Oh, is this a new bug or an old? Oh well, probably does not matter. I think it is supposed to allocate a single element for these arrays, though even that should really be unnecessary.

**Comment by charris** [comment]
@seberg Old. There is a comment in the code that some memory is needed:
```
        /*
         * Allocate something even for zero-space arrays
         * e.g. shape=(0,) -- otherwise buffer exposure
         * (a.data) doesn't work as it should.
         */
```
But that path is never taken currently. I'll put up a patch.

**Comment by charris** [comment]
See #7820.

**Comment by charris** [comment]
If someone will review #7820 and #7817 I'll try to get a 1.11.2rc1 out tomorrow.

**Comment by juliantaylor** [comment]
hm there is nothing worth releasing on the branch, why the rush?
this issue is super unimportant

**Comment by charris** [comment]
There is also a fix for a failing test in latest scipy.

**Comment by charris** [comment]
@juliantaylor See #7515. However, the release schedule is negotiable.

**Comment by cgohlke** [comment]
https://github.com/numpy/numpy/issues/7813 causes scipy.test() to crash on 32 bit Python 2.6-3.4 for Windows. That's how I discovered the issues.

**Comment by cgohlke** [comment]
Thanks for the fix and backport @charris.

Still, I would not expect `numpy.zeros((0, 2**31-1))` to raise ```ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.``` on 32 bit but that is a different issue.

**Comment by seberg** [comment]
Well, it is a bit of a theoretical construct and there are some things (like stride/size after view) which may misbehave. So I think it is correct to just disallow it. I admit the error message might be a bit confusing in this specific case.
However, I doubt there is any reason to have a (0, huge) array in a place where a (1, huge) array can never occur, so it also seems unlikely for anyone to run into it, unless when designing weird tests or just trying out edge cases for fun.
