### ISSUE TITLE
SVD // return value V //better documentation to avoid confusion

### ISSUE THREAD

**Issue by kroditakis** [numpy/numpy#7828]
In the documentation @ page:
http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.svd.html

In most of the bibliografy it can be found that, svd works like that:
![alt text](http://s0.wp.com/latex.php?latex=%5BU%2CS%2CV%5D+%3D+SVD%28E%29+&bg=ffffff&fg=000000&s=0)
![alt text](http://s0.wp.com/latex.php?latex=E+%3D+USV%5ET+&bg=ffffff&fg=000000&s=0)

Most users will assume that the return value of np.linalg.svd() will be V but actually is V transposed. This behaviour can be noticed from the example "Reconstruction based on reduced SVD:"
but it is not mentioned explicity in the documentation

**Comment by theultimatecrouton** [comment]
In the docs you linked to it says:
"The SVD is commonly written as a = U S V.H. The v returned by this function is V.H and u = U."

V.H being the hermitian conjugate of V, so this does clarify it.

It could be clearer though.

**Comment by njsmith** [comment]
We're always happy to get patches to clarify docs!
