### ISSUE TITLE
Feature-Request: extend `random.poisson` `size` argument to work for ndarray `lam` values.

### ISSUE THREAD

**Issue by lzkelley** [numpy/numpy#7843]
#### Proposal
Currently if an ndarray is passed as the argument to [`numpy.random.poisson`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.poisson.html), then the `size` parameter becomes useless.  Instead, the `size` parameter should result in `np.product(size)` samples being drawn **for each `lam` given**, such that the returned array has shape ``[lam.shape, size.shape]``.  For example:

```python
> np.random.poisson((10, 100), 3)
array([[  9,  10,  10],
       [ 96, 104, 101]])
```

#### Background

For a single width/scale of poisson distribution (`lam` parameter is a scalar), the shape (number of elements) returned can be set with the `size` argument.  e.g.

```python
In [334]: np.random.poisson(5)
Out[334]: 4

In [335]: np.random.poisson(5, size=3)
Out[335]: array([5, 6, 6])

In [336]: np.random.poisson(5, size=(3,2))
Out[336]: 
array([[4, 4],
       [4, 7],
       [3, 5]])
```

If the width of the distribution is itself an ndarray, then random variables are drawn from each element, e.g.

```python
In [340]: np.random.poisson((10,3,2,5))
Out[340]: array([8, 0, 1, 8])
```

In this case, however, the `size` argument becomes useless.  If the value of `size` is anything by the size of lam, then an error is raised:
```python
In [342]: np.random.poisson(lam=(10,2,5), size=2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-342-f9ef2b16686b> in <module>()
----> 1 np.random.poisson(lam=(10,2,5), size=2)

mtrand.pyx in mtrand.RandomState.poisson (numpy/random/mtrand/mtrand.c:29659)()

mtrand.pyx in mtrand.discd_array (numpy/random/mtrand/mtrand.c:7708)()

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [343]: np.random.poisson(lam=(10,2,5), size=(3,2))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-343-cc9f2c83e8b3> in <module>()
----> 1 np.random.poisson(lam=(10,2,5), size=(3,2))

mtrand.pyx in mtrand.RandomState.poisson (numpy/random/mtrand/mtrand.c:29659)()

mtrand.pyx in mtrand.discd_array (numpy/random/mtrand/mtrand.c:7708)()

ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

**Comment by rkern** [comment]
The shape tuple you give to `size` must be the final shape of the output array. This must be broadcast-compatible with the inputs. So let's say that you want `(3, 2)` variates for each of 4 `lam` values:

```
[~]
|9> lam = np.array([10, 3, 2, 5])

[~]
|10> np.random.poisson(lam[:, np.newaxis, np.newaxis], size=(4, 3, 2))
array([[[ 7, 12],
        [ 6, 11],
        [16, 14]],

       [[ 3,  4],
        [ 5,  1],
        [ 4,  4]],

       [[ 2,  4],
        [ 1,  1],
        [ 2,  4]],

       [[ 7,  2],
        [ 3,  8],
        [ 5,  4]]])
```

**Comment by lzkelley** [comment]
Thanks @rkern, that's really cool.  It still seems like this would be a worthwhile improvement, except --- perhaps --- instead of drawing `size` samples for each `lam`, automatically broadcasting the `lam` appropriately.  I.e. such that you could simple do:

```python
> np.random.poisson(lam, size=(4, 3, 2))
array([[[ 7, 12],
        [ 6, 11],
        [16, 14]],

       [[ 3,  4],
        [ 5,  1],
        [ 4,  4]],

       [[ 2,  4],
        [ 1,  1],
        [ 2,  4]],

       [[ 7,  2],
        [ 3,  8],
        [ 5,  4]]])
```
