### ISSUE TITLE
numpy trig timing inconsistencies on arch linux

### ISSUE THREAD

**Issue by gforsyth** [numpy/numpy#7846]
This was discussed at SciPy with a few people -- I initially thought it was an issue with `%timeit`but I think it goes deeper.  I can reproduce this on several machines (all running Arch Linux).  I cannot reproduce it on machines running Ubuntu and @ahmadia couldn't reproduce it on his Mac laptop

```python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

In [1]: import numpy

In [2]: a = numpy.ones((1000, 1000))

In [3]: %timeit numpy.sin(a)
10 loops, best of 3: 219 ms per loop

In [4]: %timeit numpy.sin(a)
10 loops, best of 3: 35.9 ms per loop

In [5]: numpy.__version__
Out[5]: '1.11.1'
```

This is in a clean `conda` environment using IPython 5.0 and Python 3.5.2 on Arch Linux.  I can also reproduce it using earlier versions of IPython.

This by itself seems to be an issue with the variable `a` not being copied to the timeit namespace and so the allocation is being included in the timings.  

It became stranger, however, when I tried to verify timings using tic tocs.

```python
In [1]: import time

In [2]: import numpy

In [3]: for i in range(10):
   ...:     a = numpy.random.random((1000, 1000))
   ...:     tic = time.time()
   ...:     numpy.sin(a)
   ...:     toc = time.time()
   ...:     print(toc - tic)
   ...:     
0.04498696327209473
0.21718716621398926
0.21537017822265625
0.21524667739868164
0.21706175804138184
0.2152256965637207
0.21519064903259277
0.21519851684570312
0.21525835990905762
0.2171497344970703
```

Using a bare Python interpreter and just doing tic tocs also results in

```python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import time
>>> for i in range(10):
...     a = numpy.random.random((1000, 1000))
...     tic = time.time()
...     b = numpy.sin(a)
...     toc = time.time()
...     print(toc - tic)
... 
0.044760704040527344
0.21795320510864258
0.21889948844909668
0.2152705192565918
0.21535921096801758
0.21519804000854492
0.2171337604522705
0.21524333953857422
0.21523666381835938
0.2152090072631836
```

Switching to system python on Arch (which isn't backed by MKL)

```python
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import time
>>> for i in range(10):
...     a = numpy.random.random((1000, 1000))
...     tic = time.time()
...     b = numpy.sin(a)
...     toc = time.time()
...     print(toc - tic)
... 
0.04167914390563965
0.21538329124450684
0.21514892578125
0.21516728401184082
0.21514582633972168
0.21581220626831055
0.21516823768615723
0.215134859085083
0.21513795852661133
0.21516680717468262
>>> numpy.__version__
'1.11.1'
>>> numpy.show_config()
atlas_3_10_info:
  NOT AVAILABLE
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas']
    language = c
    library_dirs = ['/usr/lib64']
atlas_3_10_threads_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'lapack']
    language = f77
    library_dirs = ['/usr/lib64']
openblas_lapack_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_info:
    define_macros = [('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas']
    language = c
    library_dirs = ['/usr/lib64']
atlas_blas_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
lapack_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['lapack', 'lapack', 'cblas', 'blas']
    language = c
    library_dirs = ['/usr/lib64']
atlas_3_10_blas_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
```

**Comment by charris** [comment]
Hmm, on fedora 24, Intel i5-4670K I get
```
0.013729095459
0.0136158466339
0.0132520198822
0.0132880210876
0.0135478973389
0.013219833374
0.013288974762
0.0136709213257
0.0134949684143
0.0132730007172
```
What hardware are you running on? There might be some cache effect...

**Comment by gforsyth** [comment]
I'm on an Intel i7-5930K

**Comment by ahmadia** [comment]
Can this be completely explained by CPU temporary performance boosting?

**Comment by bashtage** [comment]
Windows NumPy 1.11.1 (i5-6500) is also consistent

```
: for i in range(10):
:   ...:     a = numpy.random.random((1000, 1000))
:   ...:     tic = time.time()
:   ...:     numpy.sin(a)
:   ...:     toc = time.time()
:   ...:     print(toc - tic)
:
:--
0.007997512817382812
0.008026599884033203
0.00802159309387207
0.007989883422851562
0.008021354675292969
0.008025884628295898
0.008007287979125977
0.00902414321899414
0.008022069931030273
0.007047176361083984
```

**Comment by Lodomir** [comment]
On my ArchLinux system I see a difference when I run it in an interactive interpreter session, not when I run a script. But the first try takes longer...

Interactive python shell:

    0.11668753623962402
    0.07954740524291992
    ...

Saved script run by hand:

    0.07984209060668945
    0.07588362693786621
    ...

I have no idea what is happening there, but maybe it's no bug in numpy but a feature of the interpreter?

**Comment by gforsyth** [comment]
@Lodomir -- I have seen that behavior in the interpreter, too, and I think that's just some interpreter overhead.  My concern is the 4.5x speedup/slowdown I've observed elsewhere.  

It's very possibly not a bug in NumPy at all, but I wanted to post this somewhere to see if others were having similar issues.

**Comment by bashtage** [comment]
Is it suprising that your timings are often an order-of-magnitude slower than what charris or I posted (despite have what looks liek a high-end modern processor)?

**Comment by charris** [comment]
Could be compiler flags or power saving, but it looks like the Arch Linux folks might have a better idea of what is going on.

**Comment by gforsyth** [comment]
It is very surprising, @bashtage. I'm very confused overall. And I don't think it's related to compiler flags since this is happening with anaconda binaries, too.

**Comment by charris** [comment]
I'm going to close this as it seems Arch specific. @gforsyth Feel free to reopen if you can track this back to numpy.
