### ISSUE TITLE
numpy.cov() computes covariance of matrix of shapes (p x n) and (q x n) ?

### ISSUE THREAD

**Issue by YSanchezAraujo** [numpy/numpy#7850]
X = np.array([np.random.normal(size=10),
                 np.random.normal(size=10),
                 np.random.normal(size=10)])

    Y = np.array([np.random.normal(size=10),
                 np.random.normal(size=10),
                 np.random.normal(size=10),
                 np.random.normal(size=10)])

    CovXY = np.cov(X,Y)

np.cov(X,Y) runs all the way through, however from the documentation: 

    m : array_like
    A 1-D or 2-D array containing multiple variables and observations. Each row of m represents a variable, and each column a single observation of all those variables. Also see rowvar below.

    y : array_like, optional
    An additional set of variables and observations. y has the same form as that of m.

Is this suppose to be the case ?

**Comment by theultimatecrouton** [comment]
Yes this is as expected.

In the example you provide, X is a 3x10 matrix, Y is a 4x10 matrix. By default, cov interprets each row as a different variable and each column as an observation.

The comment in the docs that "y has the same form as that of m" is simply saying that m and y must have the same number of observations. And in our example they both have 10 observations as expected.

So cov simply adds Y to X to create a 2d array of a total of 7 variables, with 10 observations for each, and as expected this produces a covariance matrix of 7x7, with element ij being the covariance of variable i and variable j.
