### ISSUE TITLE
Memory (segfault) issues with np.empty_like

### ISSUE THREAD

**Issue by flatberg** [numpy/numpy#7854]
import numpy as np
import pandas as pd
pd.DataFrame(np.empty_like([None]))

Details at: pydata/pandas/issues/13717

**Comment by rkern** [comment]
I suspect that the correct behavior for `empty()` and `empty_like()` when asked to create `dtype=object` arrays is to go ahead and fill with `None` but issue a warning indicating that it is doing so.

**Comment by njsmith** [comment]
Or even just to do it without the warning: if some code is doing
empty_like(array_ with_arbitrary_dtype), then there isn't really anything
they can do about the warning -- they just want us to fill it with None and
move on, I think.

**Comment by seberg** [comment]
Yeah might be worth to try to get rid of that whole NULL is None logic stuff in the long run. No reason to not fill explicitly though.

**Comment by gfyoung** [comment]
@seberg : FWIW, the explicit filling seems to patch things well ATM

**Comment by gfyoung** [comment]
xref my comment <a href="https://github.com/pydata/pandas/issues/13717#issuecomment-234704316">here</a>

There appears to be some weird memory access violation in Cython, which can be replicated in the `numpy` library as follows:

In `mtrand.pyx`, add the following function:
~~~python
def getfirstelt(ndarray[object] arr):
    return arr[0]
~~~
After installing, do this:
~~~python
>>> from numpy.random import getfirstelt
>>> import numpy as np
>>> np.getfirstelt(np.empty_like([None]))
~~~
This will segfault.  It seems like the quick-fix is to change `ndarray[object] arr` to just `arr`, but Cython will compile in the form that I have above, so either it's a Cython issue or a `numpy issue.

**Comment by rkern** [comment]
`numpy` issue.

**Comment by gfyoung** [comment]
@rkern : So @njsmith was saying <a href="https://github.com/pydata/pandas/issues/13717#issuecomment-234362343">here</a> that using 0-field values was another way of indicating a `None`, but it seems like Cython doesn't compile that properly.  I'm not really sure what the fix would be on the `numpy` end.

**Comment by rkern** [comment]
Ah, okay, if `np.empty(…, dtype=object)` is consistently filling with `NULL` then it's a Cython bug in how it deals with indexing `dtype=object` arrays.

**Comment by gfyoung** [comment]
@rkern: If by `NULL` if you the 0-field value, the no:
~~~python
>>> import numpy as np
>>> bytes(np.empty((1,), dtype=object, order='C').data)
b'0\x81\x85`\xea\x7f\x00\x00'
>>> bytes(np.empty_like([None, dtype=object, order='C', subok=False).data)
b'\x00\x00\x00\x00\x00\x00\x00\x00'
~~~
This seems to be somewhat inconsistent IMO, but again, not sure what to do about it.

**Comment by rkern** [comment]
It looks like the first one is filling it with the pointer to `None`.

```
[~]
|11> np.frombuffer((np.empty((1,), dtype=object, order='C').data), np.uint64)
array([4296552352], dtype=uint64)

[~]
|12> id(None)
4296552352
```

I honestly don't care much whether it switches between filling with pointers to `None` or filling with `NULL` depending on the invocation. It's an opportunity to improve, perhaps. My point was that as long as it doesn't just allocate the memory and expose it like it does with the other dtypes, it's not numpy causing the segfault but Cython not following the corner cases of the rules of `dtype=object` arrays.

**Comment by gfyoung** [comment]
@rkern : Yes, that's right.  Okay, so I think we can call it a Cython issue then and close it on the `numpy` end, if I'm not mistaken?

**Comment by seberg** [comment]
I would say so personally, though I am still open to discuss whether we should try to shift away from this NULL is None logic in the longer run.
