### ISSUE TITLE
dtype('b') != dtype('b1')?  also boolean is printed weirdly in type strings

### ISSUE THREAD

**Issue by suntzu86** [numpy/numpy#7869]
numpy.version.version: 1.11.1

The bare typestr 'b' (bool) maps to 1-byte integer whereas 'b1' (a "1 byte" bool) maps to bool.
```
In [638]: numpy.dtype('b')
Out[638]: dtype('int8')

In [639]: numpy.dtype('b1')
Out[639]: dtype('bool')

# 'b2', 'b3', etc. all raise, which makes sense
```
This makes a real difference as an array with the first dtype will take values from -128 to 127 inclusive. An array w/the second dtype only has False/True values. This seems very confusing to me. In fact I might have assumed it would be the other way around where 'b' is 1-bit per entry, and 'b1' forces 1 byte per entry.

According to docs http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html#specifying-and-constructing-data-types (see Array protocol type strings section) and http://docs.scipy.org/doc/numpy/reference/arrays.interface.html#python-side (see typestr section), the format is expected to be "ABC" where A is ``<, >, |``, B is one of the type identifier characters, and C is a number. 

Actually it seems like B is allowed to be a number of other characters too, like 'a' or 'q' work, 'x' and 'z' do not. Several other typestr chars produce something reasonable, like ``dtype('i')`` and ``dtype('f')`` produce 32-bit int and float, respectively.  This isn't universal as ``dtype('u')`` raises (instead of making uint32)

I'm guessing that the single char typestrings do not mean the the same thing as their friends with num bytes attached. So 'b' and 'b1' are wholly unrelated. And it working out for 'i' and 'f' is coincidence or something. Either way, could y'all:

1. If the single char typestrings carry different meanings, could you document this on those type protocol pages (or link to where it is doc'd).
AND/OR
2. Make 'b' and 'b1' the same dtype. It'd still be handy to point out what other single char strings map into types and what that mapping is. (It seems like some of them follow printf's character codes, but that's not universal either.) boolean still seems the most confusing case here since a multi-byte (or even multi-bit) boolean doesn't make sense.

While we're here,
```
In [698]: foo = numpy.zeros(2, dtype=[('foo', 'f8'), ('bar', 'b1'), ('bam', 'i4')])
In [701]: foo.dtype
Out[701]: dtype([('foo', '<f8'), ('bar', '?'), ('bam', '<i4')])  # 'bar' has type '?'
```
Not sure why the boolean column has its type printed as a question-mark.

**Comment by pv** [comment]
The array interface codes are different from the dtype codes:
https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html#built-in-scalar-types

**Comment by suntzu86** [comment]
It's even linked off of the dtype page that I linked to :(  Man I feel silly.

It never occurred to me that the single char ones would be scalar types! And I guess ``?`` is meant to evoke "Yes/No".  Sorry about that.
