### ISSUE TITLE
Invalid link to RecordArrays in Quickstart Tutorial

### ISSUE THREAD

**Issue by scimax** [numpy/numpy#7881]
I already accidentally submitted this issue on the scipy/scipy.org project. But the bug is probably in this [file](https://github.com/numpy/numpy/blob/master/doc/source/user/quickstart.rst), isn't it?

While browsing the [Quickstart Guide](http://docs.scipy.org/doc/numpy/user/quickstart.html#fancy-indexing-and-index-tricks) in the "Fancy Indexing" section I found this [link](http://docs.scipy.org/doc/numpy/user/RecordArrays.html) under "Indexing with Strings" which is pointing nowhere.
Should it point to this [section](http://docs.scipy.org/doc/numpy/user/basics.rec.html#record-arrays)?

**Comment by rgommers** [comment]
Thanks for the report @scimax. Yes, that looks like the right place to point to. A PR to fix this would be very welcome.
