### ISSUE TITLE
Warning for np.rint(np.inf) on Windows but not Unix

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#7882]
Over at https://github.com/nipy/nibabel/pull/216#issuecomment-236266516 we found that numpy has different behavior on Windows and Unix for warnings.

Specifically:

```
np.rint(np.inf)
```

on Windows, gives a warning:

```
>>> np.rint(np.inf)
__main__:1: RuntimeWarning: invalid value encountered in rint
```

but on OSX and Linux, it does not.  Is this expected?

**Comment by seberg** [comment]
I don't think we should bother about this.  I would argue the `inf` result is OK for `inf` input so no warning should be given:  I.e. the window smath lib (if it still does this) is buggy, but not enough to bother work-arounds.
