### ISSUE TITLE
Multiply numpy int and float arrays

### ISSUE THREAD

**Issue by josephernest** [numpy/numpy#7883]
I'd like to multiply an `int16` array but a `float` array, with auto rounding, but this fails :

    import numpy
    
    A = numpy.array([1, 2, 3, 4], dtype=numpy.int16)
    B = numpy.array([0.5, 2.1, 3, 4], dtype=numpy.float64)
    
    A *= B

I get: 

>TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int16') with casting rule 'same_kind'

How to do it properly?

**Comment by josephernest** [comment]
It seems it's possible with `numpy.multiply(A, B, out=A, casting='unsafe')` but that's way much longer syntax!
Is there a way to set `casting='unsafe'` in numpy ?

**Comment by charris** [comment]
Only at the C level, and we made that change to stricter casting rules some time ago. Explicit is better than implicit, it indicates that you intended the cast and that it isn't the more common coding goof.
