### ISSUE TITLE
Saving/loading sparse matrix corrupts shape

### ISSUE THREAD

**Issue by inexxt** [numpy/numpy#7890]
Hi,

There is apparently some problem with either saving or loading sparse matrix.

```
import numpy
from scipy import sparse

X = np.ones(shape=(10, 10))

P = sparse.csr_matrix(X)

with open("temp", "wb") as f:
    np.save(f, P)

with open("temp", "rb") as f:
    P2 = np.load(f)

print(P2.shape)
```
gives
``` () ```

I'm using numpy 1.11.1 in conda 4.1.6

**Comment by theultimatecrouton** [comment]
I don't think this is an issue with saving/loading.

P is of type `scipy.sparse.csr.csr_matrix`, whereas P2 is of type `numpy.ndarray`, which is to be expected I think.

And if you coerce P into a `ndarray`, then you get the same result, i.e.:

```
import numpy as np
from scipy import sparse

X = np.ones(shape=(10, 10))

P = np.array(sparse.csr_matrix(X))
print(P.shape)
```

gives
`()`

This seems like a bug to me, I'll have a look into fixing.

**Comment by pv** [comment]
There's no automatic coercion from scipy.sparse matrices via array(),
what you get is an object array with a single element.

**Comment by theultimatecrouton** [comment]
Thanks!
