### ISSUE TITLE
scipy.stats.mstats.winsorize on masked array triggers future warnings

### ISSUE THREAD

**Issue by shadowleaves** [numpy/numpy#7892]
when calling scipy.stats.mstats.winsorize on a masked array in numpy 1.11, the following warnings will appear:

*** MaskedArrayFutureWarning: setting an item on a masked array which has a shared mask will not copy the mask and also change the original mask array in the future.
Check the NumPy 1.11 release notes for more information.

**Comment by seberg** [comment]
We used to have some problems with this warning being too noisy, but I think you should bring this up on SciPy. Also please double check your scipy version, warnings like this are to be expected and nothing to worry about if your numpy version is newer then your scipy version (just make sure you are not many versions old scipy with very new numpy).

It is likely SciPy already has fixed this or is in the process of doing so, but please note it on the SciPy issue tracker. If this warnings makes trouble for SciPy/you and we have to discuss the change as such, please feel free to reopen/create a new issue.
