### ISSUE TITLE
matrix inverse with power: algebraic incorrect

### ISSUE THREAD

**Issue by mdrew46** [numpy/numpy#7893]
Taking the inverse of a diagonal matrix with A**(-1) gives +/-inf for off diagonal elements where should be zero. numpy.linalg.matrix_power(A,-1) works fine though.

**Comment by pv** [comment]
`**` is elementwise for numpy.ndarray.

**Comment by mdrew46** [comment]
Hi, thanks for the explanation. Sorry for bothering you.

Cheers,

Matt
