### ISSUE TITLE
np.sqrt.types is bogus

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#7897]
Notice how some loops are duplicated, and `e->e` comes after `f->f`, ensuring it never gets selected.

```
>>> np.__version__
'1.11.1'
>>> np.sqrt
<ufunc 'sqrt'>
>>> np.sqrt.types

['f->f',
 'd->d',
 'e->e',
 'f->f',
 'd->d',
 'g->g',
 'F->F',
 'D->D',
 'G->G',
 'O->O']
```

**Comment by charris** [comment]
The first two entries should not be there. Hmm... looks like this entry in the `numpy/core/code_generators/generate_umath.py` sqrt entry
```
          TD(inexactvec),
```
I think it can simply be removed along with the definition of `inexactvec`, as that seems to be the only place it is used. @juliantaylor This looks like a leftover scrap that snuck in. Did you intend it for something else.

**Comment by charris** [comment]
For some reason, the fix for this exposes a segfault in `assert_almost_equal` for 0-D complex values.

**Comment by eric-wieser** [comment]
Reopening, because there are still duplicates in here, even if the bug with `float16` is fixed

**Comment by WarrenWeckesser** [comment]
The duplicated loops are the SIMD and generic loops:
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.22.0.dev0+1257.gb0e1a445d'

In [3]: np.sqrt.types
Out[3]: 
['e->e',
 'f->f',
 'd->d',
 'f->f',
 'd->d',
 'g->g',
 'F->F',
 'D->D',
 'G->G',
 'O->O']

In [4]: from ufunclab import ufunc_inspector

In [5]: ufunc_inspector(np.sqrt)
'sqrt' is a ufunc.
nin = 1, nout = 1, ntypes = 10
loop types:
  0:   23 ->  23  (e->e)  PyUFunc_e_e_As_f_f
  1:   11 ->  11  (f->f)  not generic (or not in the checked generics)
  2:   12 ->  12  (d->d)  not generic (or not in the checked generics)
  3:   11 ->  11  (f->f)  PyUFunc_f_f
  4:   12 ->  12  (d->d)  PyUFunc_d_d
  5:   13 ->  13  (g->g)  PyUFunc_g_g
  6:   14 ->  14  (F->F)  PyUFunc_F_F
  7:   15 ->  15  (D->D)  PyUFunc_D_D
  8:   16 ->  16  (G->G)  PyUFunc_G_G
  9:   17 ->  17  (O->O)  PyUFunc_O_O_method
```

**Comment by seberg** [comment]
Been fixed a long time ago, even added a test to catch most of these at some point.
