### ISSUE TITLE
Minor bug in ndim documentation

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#7900]
The docstring for `<function numpy.core.fromnumeric.ndim>` states that it wants an `array_like` input parameter.  However, in reality, `ndim` works for any arbitrary Python object, array-like or not.

**Comment by seberg** [comment]
The documentation is correct, `array_like` broadly means "can be converted to an array by `np.array`", though it also supports duck-typing the `.ndim` attribute, that is also quite common. So I would say that array-like is the correct word here.

**Comment by seberg** [comment]
I admit converting to an array just to get the dimensions is fun, but then the method is likely a nicer way to this anyway.
