### ISSUE TITLE
setuptools 25.1.6 breaks numpy.distutils on Windows

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#7921]
See https://github.com/pypa/setuptools/issues/728 and the linked issues.

**Comment by rgommers** [comment]
Thanks for the ping @pitrou. Looks like the fix should land in ``setuptools``, so nothing to do here. 

These monkeypatching issues do happen too often. Not easy to avoid though, unless we have some "build CI" for setuptools itself where the numpy.distutils-setuptools interaction is tested extensively.

**Comment by rgommers** [comment]
This was fixed, see linked PRs.
