### ISSUE TITLE
Should linalg call __array_prepare__ with a context argument?

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#7923]
`np.linalg._makearray(a)` returns `a.__array_prepare__` when possible, otherwise using `ndarray.__array_wrap__`.

is this a valid use of `__array_prepare__`? Shouldn't this only be called on the way into ufuncs, not the way out?

At the very least, shouldn't the context be populated with something sensible?

Related: hgrecco/pint#420

**Comment by mhvk** [comment]
Indeed, I think it should use `__wrap__`. I vaguely recall noticing this too at some point (I think in testing our astropy `Quantity` class with `linalg` routines), but being to horrified about what all might break to try just changing it...

**Comment by seberg** [comment]
Removed array-prepare, so I think this is moot now ...  (its calling array-wrap)

I don't think we need to improve context anymore: use the other protocols.
