### ISSUE TITLE
iscomplexobj does not work for sparse matrices

### ISSUE THREAD

**Issue by goerz** [numpy/numpy#7924]
>>> import scipy
    >>> import numpy as np
    >>> A = scipy.sparse.csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5j]])
    >>> np.iscomplexobj(A)
    False

I would argue that the implementation of `iscomplexobj` should not include the `asarray`, but should simply read

    return issubclass(x.dtype.type, _nx.complexfloating)

This might cause an `AttributeError`, of course. Not sure whether it's better to throw the exception at this point, or whether to handle it locally.

**Comment by shoyer** [comment]
None of the examples in the current docstring have a valid dtype:

    >>> np.iscomplexobj(1)
    False
    >>> np.iscomplexobj(1+0j)
    True
    >>> np.iscomplexobj([3, 1+0j, True])
    True

But we could certainly check for a `dtype` attribute before calling asarray in the style of existing support for duck array types in NumPy, e.g.,

    try:
        dtype = x.dtype
    except AttributeError:
        dtype = np.asarray(x).dtype
    return issubclass(dtype.type, _nx.complexfloating)
