### ISSUE TITLE
numpy.memmap notes document unclear size limits

### ISSUE THREAD

**Issue by Zac-HD** [numpy/numpy#7927]
My interpretation of [the docs here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html) (under 'Notes') is that memmapped arrays could not be over 2GB in size for Python <=2.4; and that this restriction no longer exists.

This paragraph should either be clarified, or - given that Numpy now supports only Python >= 2.6 - removed entirely.

**Comment by rgommers** [comment]
agreed, the paragraph can be removed completely.

**Comment by souravsingh** [comment]
I think the issue is fixed

**Comment by charris** [comment]
Thanks for the heads up.
