### ISSUE TITLE
trapz() gives wrong results if x is datetime

### ISSUE THREAD

**Issue by rubenbaetens** [numpy/numpy#7928]
When using `trapz( )` to integrate a data timeseries (stored in a pandas dataframe), wrong results are sometimes returned if arg `x` is in a `DateTime` format. When the same x-axis is converged to float ndarray, the right results are returned.

**Comment by theultimatecrouton** [comment]
Could you give me an example of it giving the wrong results? I just hacked an example together and it seemed to work
