### ISSUE TITLE
infinity error when averaging many float16

### ISSUE THREAD

**Issue by kyleellefsen** [numpy/numpy#7930]
I was trying to average a large array with dtype=float16 and noticed that function returned infinity.  Here is some code which consistently replicates this bug:

`np.mean(np.random.randn(100000).astype(np.float16)+1)`

I expected there would be an internal check for floating point overflow before the result is handed back.

I'm using Python 3.5.1 on Windows 7, numpy version 1.11.0

**Comment by mhvk** [comment]
This is a result of `float16` having limited resolution and range:
```
np.finfo(np.float16)
# finfo(resolution=0.0010004, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
```
The maximum number `float16` can represent is 65504, so one reaches infinity by going above that by its resolution:
```
np.ones(65519, dtype=np.float16).sum()
# 65504.0
np.ones(65520, dtype=np.float16).sum()
# inf
```
To avoid it, set the output type:
```
np.ones(65520, dtype=np.float16).sum(dtype=np.float64)               
# 65520.0
```

But I guess your question is about why there is no warning raised (unlike when one, e.g., adds two numbers). This is noted in the documentation of `np.sum`, but not in that for `np.mean`. It might be good to add a note there too...

**Comment by juliantaylor** [comment]
the numeric exceptions are not checked for any reduction functions actually. Though I don't know why.

**Comment by charris** [comment]
This should be much improved by #8222, so closing this.
