### ISSUE TITLE
sqrt raises AttributeError on unexpected input

### ISSUE THREAD

**Issue by silvioricardoc** [numpy/numpy#7961]
``` python
>>> numpy.sqrt(9)
3.0
>>> numpy.sqrt(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: sqrt
```

I expected a TypeError or ValueError, and spent quite some time trying to understand why `sqrt` was "missing"...

**Comment by charris** [comment]
`None` is treated as an object, which is why a `sqrt` attribute is looked for. Perhaps the error message can be improved.

**Comment by timhoffm** [comment]
Same problem with sympy integers:

~~~
>>> import numpy as np
>>> x = Integer(10)
>>> np.sqrt(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Integer' object has no attribute 'sqrt'
~~~

Reported in https://github.com/matplotlib/matplotlib/issues/13106.

A better error message would really help to find out what's going on.

**Comment by eric-wieser** [comment]
+1 from me on improving the error message. Raising `TypeError("Object loop of ufunc {} does not support object of type {} which has no {} method")` if the attribute is absent would be helpful.

I'm not sure if we should also try and check is the attribute is callable.

Perhaps chaining the exception would be useful here
