### ISSUE TITLE
Zeros inserted when converting to uint8

### ISSUE THREAD

**Issue by cjmcmurtrie** [numpy/numpy#7966]
When I run:
```
import numpy as np
a = np.array([1, 2, 4, 256, 3, 7])
print a
>>> [  1   2   4 256   3   7]
```

Now try the below, 256 is replaced with zero:
```
b = np.array(a, dtype=np.uint8)
print b
>>> [1 2 4 0 3 7]
```

This yields the same result:
```
b = a.astype(np.uint8)
print b
>>> [1 2 4 0 3 7]
```

Any explanation for this?

**Comment by jaimefrio** [comment]
The largest possible value in a `uint8` is 255, values outside of the `[0. 255]` bounds wrap around, i.e. are replaced with `x % 256`, hence your result.

This is a known and expected behavior, so am closing this, feel free to reopen if you have any further questions.

**Comment by cjmcmurtrie** [comment]
Thank you @jaimefrio! Makes perfect sense.
