### ISSUE TITLE
Undocumented behaviour of `np.concatenate` with `axis=None`

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#7968]
```
>>> a = np.array([[1,2,],[3,4]])
>>> b = a + 10
>>> np.concatenate((a, b), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])
>>> np.concatenate((a, b), axis=1)

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])
>>> np.concatenate((a, b), axis=None)
array([ 1,  2,  3,  4, 11, 12, 13, 14])
```

**Comment by derrickaw** [comment]
Hey @eric-wieser, I would like to try working on this issue.  Will be my first time contributing to open-source, so need to go through all the numpy guides on contributing first.  But wanted to go ahead and speak up for something.  Can you add me as a contributor and assignee on this issue?  Is that the correct procedure?
Thanks

**Comment by eric-wieser** [comment]
No need to add you as a contributor - if you haven't already, take a look at [our contribution guide](https://github.com/numpy/numpy/blob/master/CONTRIBUTING.md#contributing-code).

For something as simple as documentation, you should be able to just edit the file right in github, which will automatically do the right thing of creating a fork and feature branch for you to work in.

In practice numpy seems not to use assignees much.
