### ISSUE TITLE
numpy.insert() won't upcast from int8 to int64

### ISSUE THREAD

**Issue by Dmitrii-I** [numpy/numpy#7970]
I am fairly new to numpy so maybe this is not considered a bug. However I think it is bad you are not even issuing a warning that the element I want to insert is not of same dtype.

Example:

```
import numpy as np
x = np.array([1, 2, 3], dtype='int8')
np.insert(x, 0, 1234567)
>>> array([-121,    1,    2,    3], dtype=int8)
```

Obviously I would prefer you upcast the array to higher dtype.

**Comment by charris** [comment]
Could warn, although sometimes people want the behavior and a warning would be annoying. The documentation does say that the inserted values will be cast to the type of the array, but perhaps that should also be mentioned in the summary part.

**Comment by Dmitrii-I** [comment]
Could you please give me a link to the docs where it says that? I used http://docs.scipy.org/doc/numpy/reference/generated/numpy.insert.html and it does not say about casting, except one of the example that does type casting. Perhaps I am using wrong documentation source.

**Comment by charris** [comment]
If you want to improve the documentation that would be great.

**Comment by Dmitrii-I** [comment]
I would like to, but I don't think I am qulified yet :-)

**Comment by seberg** [comment]
@Dmitrii-I just try. That is why there is a review process, so you don't have to worry to get it right in the first attempt and can be sure someone who knows things in more detail checked it.

**Comment by mattip** [comment]
Closing. It seems 3 years is long enough to wait for a documentation improvement PR. Please go ahead and create a PR to improve documentation if you can think of a better way to present the information.
