### ISSUE TITLE
Adding large 2d sliced arrays of 3d ndarrays crashes python

### ISSUE THREAD

**Issue by kkoshijima** [numpy/numpy#7971]
I am trying to add large 2darrays which belong to higher dimensional arrays, e.g.,

```
dim1 = 16000
dim2 = 8000
dim3 = 100
a = np.zeros([dim1, dim2, dim3])
a[:,:,1] + a[:,:,2]
```

When I do this, it uses tremendous amounts of memory and the python process gets killed. However, when I try

```
b = np.zeros([dim1, dim2])
c = np.zeros([dim1, dim2])
b + c
```

it works fine.

The calculation finishes properly when `dim3` is set to a small number, giving the same result as  `b + c`. 

Why is this happening?
Could this be a bug in numpy?

**Comment by MSeifert04** [comment]
Your `a` contains 13 billion (16k * 800 * 100) float64. Which is 102 billion bytes (95GB). If you're using a normal computer it's unlikely yo have that much RAM.

On the other hand `b` and `c` contain 1/100 of that elements, which means they are ~ 1GB each and easily fit (generally avaiable) RAM.

**Comment by kkoshijima** [comment]
@MSeifert04 
I see. That's true.  

What was confusing to me was that I could create `a`, and I can even access `a[:,:,1]` as below.

```
In [17]: a = np.zeros([16000, 8000, 100])

In [18]: a[:,:,1]
Out[18]:
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])
```

Perhaps, the memory for all of the elements is not allocated until the addition is executed?

**Comment by charris** [comment]
I get a `MemoryError` for this. @kkoshijima What version of numpy are you using and what platform are you running on?

**Comment by kkoshijima** [comment]
@charris 
numpy version is 1.11.1 and I am running this on MacOSX 10.11.3.

**Comment by charris** [comment]
@kkoshijima Interesting, I'm running on Linux. `zeros` is somewhat special in allocation, so it is possible that OS X allows creation of the array and doesn't error until excessive memory is actually accessed. I don't know that that is what is going on, but it is possible...

**Comment by shoyer** [comment]
OS X does some tricks with compressed memory. I wouldn't be surprised if it uses that for `zeros`.

**Comment by seberg** [comment]
Seems to me it adds up. Since you are indexing the last/fast dimension with an integer, all of the memory would be accessed (and written to) at some point, and thus it has to blow up. If you would do:
```
a = np.zeros([dim1, dim2, dim3], order="F")
a[:, :, 1] + a[:, :, 2]
```
it probably works fine, since in that case you don't actually need to uncompress/access the whole giant blob, but just the small enough slices.

**Comment by seberg** [comment]
Closing this, while it would be nicer to raise a MemoryError instead of crashing after accessing a too large array, it does not seem like something we have influence over, since it is probably some OOM kill which finally "crashed" the python here. It is also a discussion from 2016.
