### ISSUE TITLE
Minor imprecision in error message from `rollaxis`

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7974]
```
In [1]: np.rollaxis(np.zeros((2, 2)), 3)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-b401785fc6dd> in <module>()
----> 1 np.rollaxis(np.zeros((2, 2)), 3)

/usr/lib/python3.5/site-packages/numpy/core/numeric.py in rollaxis(a, axis, start)
   1448     msg = 'rollaxis: %s (%d) must be >=0 and < %d'
   1449     if not (0 <= axis < n):
-> 1450         raise ValueError(msg % ('axis', axis, n))
   1451     if not (0 <= start < n + 1):
   1452         raise ValueError(msg % ('start', start, n + 1))

ValueError: rollaxis: axis (3) must be >=0 and < 2
```
but in fact a negative index will work too:
```
In [2]: np.rollaxis(np.zeros((2, 2)), -1)
Out[2]: 
array([[ 0.,  0.],
       [ 0.,  0.]])
```

numpy 1.11.1

**Comment by gfyoung** [comment]
Reproducible on `master`.

Is there any reason why negative values are rejected?  Couldn't we just do `mod n` on the value?

**Comment by shoyer** [comment]
This is just a bug in the error message. Negative axes (`-1` through `-ndim`) are already supported.

**Comment by gfyoung** [comment]
@shoyer : That's not exactly what I meant.  I mean, why can't we just accept any integer and then readjust it `mod n` i.e. `start = start % n`?

**Comment by shoyer** [comment]
Suppose you have a 2D array. What does `np.rollaxis(a, axis=2)` mean? The array has no 3rd axis to roll.

Rather than guess about user intent, NumPy raises errors in ambiguous cases. This helps catch bugs in user code.

**Comment by gfyoung** [comment]
Fair enough.  PR up.
