### ISSUE TITLE
Unexpected warning using np.rec.fromfile

### ISSUE THREAD

**Issue by tillahoffmann** [numpy/numpy#7975]
I am using numpy 1.11.1 and would like to persist a record array to disk using the `tofile` method. The code executes successfully but I get an odd warning. Here is an example.

``` python
import numpy as np
# Create an array, save and load
x = np.rec.fromarrays(np.random.normal(size=(1,10)))
x.tofile('temp')
np.rec.fromfile('temp', x.dtype)
```

The last lines results in the following warning:

```
[my site-packages]/numpy/core/records.py:419: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self = ndarray.__new__(subtype, shape, (record, descr), order=order)
```

The following code runs fine without warning and produces the same result.

``` python
np.rec.array(np.fromfile('temp', x.dtype))
```

**Comment by mattip** [comment]
Closing. I do not get a warning on latest HEAD. Please reopen if I misunderstood.
