### ISSUE TITLE
random.normal does not always preserve shape of size-1 arrays

### ISSUE THREAD

**Issue by drhagen** [numpy/numpy#7983]
On 1.11.1, `random.normal` does not preserve the shape of its inputs in one particular case: the size of the `ndarray` is one.

```
In[2]: import numpy as np
In[2]: from numpy.random import normal
```

Sending in Python lists all acts as expected:

```
In[4]: normal(0)
Out[4]: -0.5191599213417067
In[5]: normal([0])
Out[5]: array([-0.03654451])
In[6]: normal([[0]])
Out[6]: array([[-1.03033527]])
```

Numpy arrays of size 1 all return a float instead of an array of the corresponding shape:

```
In[10]: normal(np.asarray(0))
Out[10]: 0.6874599652327416
In[11]: normal(np.asarray([0]))
Out[11]: -0.044433450447185156
In[12]: normal(np.asarray([[0]]))
Out[12]: -0.4610284419029141
```

Arrays of other shapes work fine:

```
In[14]: normal(np.asarray([0, 0]))
Out[14]: array([-0.58998342,  0.13144979])
In[15]: normal(np.asarray([[0, 0]]))
Out[15]: array([[-0.14003459,  0.28130253]])
```

**Comment by adler-j** [comment]
Problem existed already in numpy version '1.10.4'.

**Comment by bashtage** [comment]
This happens since anytime inputs are 

* scalars - either actual scalars or arrays squeezable to 0-d (these are the same since this line converts all inputs to arrays, https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L236 )
* `size=None` 

this path is visited:

https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L236

which returns scalars.

**Comment by WarrenWeckesser** [comment]
Has this been fixed?  Here's what I get with numpy `'1.12.0.dev0+c90d7c9'`, and Python 3.5.1:

```
In [8]: import numpy as np

In [9]: np.__version__
Out[9]: '1.12.0.dev0+c90d7c9'

In [10]: np.random.normal(np.array([0]))
Out[10]: array([-0.445584])

In [11]: np.random.normal(np.asarray([0]))
Out[11]: array([ 0.27932514])

In [12]: np.random.normal(np.asarray([[0]]))
Out[12]: array([[-1.66792229]])
```

When the argument is a scalar array, the return type is a plain float:

```
In [13]: np.random.normal(np.asarray(0))
Out[13]: 0.7710030901774756

In [14]: type(_)
Out[14]: float
```

**Comment by charris** [comment]
Seems to have been fixed by #7055. It's a fairly large commit, so adding it to 1.11.2 would make me nervous.

**Comment by WarrenWeckesser** [comment]
Then it seems reasonable to not backport the fix.  So I guess this issue can be closed, as the fix is in for 0.12.0.  (Although, if someone is motivated, a unit test could help ensure that it stays fixed.)

**Comment by WarrenWeckesser** [comment]
>  (Although, if someone is motivated, a unit test could help ensure that it stays fixed.)

Ignore that.  #7055 has unit tests, of course.

**Comment by bashtage** [comment]
@charris This looks like it can be closed
