### ISSUE TITLE
unify spelling of Numpy/NumPy

### ISSUE THREAD

**Issue by btel** [numpy/numpy#7986]
The documentation is not consistent in spelling of "NumPy" (vs "Numpy"). For example, the reference manual uses both spelling in the introduction [paragraph](https://github.com/numpy/numpy/blob/master/doc/source/reference/index.rst):

> This reference manual details functions, modules, and objects included in **Numpy**, describing what they are and what they do. For learning how to use **NumPy**, see also :ref:`user`.

What is the official spelling? Make it consistent across all documentation.

This issue was initially reported at Scipy Lectures (https://github.com/scipy-lectures/scipy-lecture-notes/issues/250) by @btel and @emmanuelle.

Following the discussion on the mailing list and recommendations of @pdebuyl to close the issue:
- [ ] update the docs to use NumPy when we refer to the project and `numpy` only in relation to the module name
- [ ] explain the rules of "NumPy" spelling in the NumPy docs

**Comment by charris** [comment]
The choice always leaves me thinking a bit. I try to use NumPy for official stuff, but tend to fall back on numpy for informal communication. This might be a good topic to raise on the mailing list.

**Comment by pdebuyl** [comment]
The mailing-list thread has support for NumPy (uppercase N and P) from
- Stefan van der Walt https://mail.scipy.org/pipermail/numpy-discussion/2016-August/075916.html
- Ben Root https://mail.scipy.org/pipermail/numpy-discussion/2016-August/075915.html
- A 2010 SciPy-User post from Robert Kern https://mail.scipy.org/pipermail/scipy-user/2010-June/025756.html

The book by @teoliphant (still available here, for instance http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf) is "Guide to NumPy" and the intro is consistently using "NumPy".

There are inconsistencies in the documentation on scipy.org but I (humbly) suggest to pick "NumPy" for the name of the project and also for reference to the software and "numpy" as the module name. The "Guide to NumPy" refers to the `numpy` namespace.

There is no FAQ in the documentation of NumPy but it would be good to add this information somewhere (either in the NumPy reference or in the user guide).

"NumPy arrays" and "numpy arrays" can both be used, as they can refer to the project or to the module.

**Comment by btel** [comment]
@pdebuyl thanks! I updated the issue with your proposed solution. If there is no other volunteers, I can open a PR with these changes.

**Comment by pdebuyl** [comment]
I can help for this.

There are 61 files in `numpy` and 75 in `doc`.
```
$ cd numpy/
$ ack-grep -l Numpy | wc -l
61
$ cd ../doc/
$ ack-grep -l Numpy | wc -l
75
```
Should the release notes be modified? They could be considered "historical" data.

There are a few instances of "Numpy*" in the test code (the `NumpyDoctest` in nosetests), in the distutils code (`NumpyDistribution` class) and the `NumpyVersion` variable.

The C code seems to use "NumPy" consistently.

**Comment by eric-wieser** [comment]
@pdebuyl: Can this be closed, or is there more to do here?

**Comment by pdebuyl** [comment]
No problem for closing. The corresponding PR was merged.
