### ISSUE TITLE
Misleading info in the build docs says a Fortran compiler is needed to build numpy

### ISSUE THREAD

**Issue by fperez** [numpy/numpy#7992]
The [build section of the user docs](https://github.com/numpy/numpy/blob/master/doc/source/user/building.rst#prerequisites) says:

> Compilers
> 
> To build any extension modules for Python, you'll need a C compiler. Various NumPy modules use FORTRAN 77 libraries, so you'll also need a FORTRAN 77 compiler installed.

This is incorrect, and inconsistent with the [instructions in the main install file](https://github.com/numpy/numpy/blob/master/INSTALL.rst.txt#choosing-compilers), which state:

>  Fortran compiler isn't needed to build Numpy itself; the numpy.f2py tests will be skipped when running the test suite if no Fortran compiler is available. For building Scipy a Fortran compiler is needed though, so we include some details on Fortran compilers in the rest of this section.

The former is probably a remnant of the old scipy docs.

I'm happy to submit a fix, but it would be good to know how folks want to deal with the duplication of those files.  As long as that information is carried in two duplicate locations, problems of divergence will keep reappearing.  Ideally there should be only one location to describe the source build process.

**Comment by charris** [comment]
That file was created last Oct. by Pauli. @pv Do you want to keep that section of the docs, or would it be better to reference the `doc/HOWTO_BUILD_DOCS.rst.txt` file?

**Comment by pv** [comment]
That file is from 2009 (see `git log --follow`) --- I have no opinion on 
the content, but it may be misleading.

**Comment by fperez** [comment]
@charris, note that [doc/HOWTO_BUILD_DOCS.rst.txt](https://github.com/numpy/numpy/blob/master/doc/HOWTO_BUILD_DOCS.rst.txt) is about how to build *the docs*, not numpy itself.  So at least currently it only focuses on sphinx & friends.

There should be one location for build instructions of numpy itself.  Or are you suggesting that the above get upgraded to covering all build questions (library and docs)?  I think that's pretty reasonable, though if that's the direction you all want to go, it might be worth renaming the file to `HOWTO_BUILD` or similar, and just include sections on library and doc builds within.

**Comment by charris** [comment]
@fperez Yeah, my mistake. I meant the `INSTALL.rst.txt` in the root directory.

**Comment by fperez** [comment]
Got it. If you guys decide how you want to go about it, I'm happy to whip up a PR in a hurry, it's an easy one and I haven't done anything for numpy in a long time, so it will be good karma :)

**Comment by rgommers** [comment]
The [build section of the user docs](https://github.com/numpy/numpy/blob/master/doc/source/user/building.rst#prerequisites) is outdated, we should get rid of it. We can't get rid of ``INSTALL.rst.txt`` because many people expect such a top level file.

So proposal:

1.  ``.. include::`` the ``INSTALL.rst.txt`` file into the user docs. 
2. From ``INSTALL.rst.txt`` (which is up to date as far as I can tell but concise), link to http://scipy.org/scipylib/building/index.html for more details per platform and use of alternative BLAS / compilers.

**Comment by mattip** [comment]
The misleading text is [still there](https://numpy.org/devdocs/user/building.html).

**Comment by Mukulikaa** [comment]
It seems to me that a Fortran compiler will be necessary only if someone wants to run the `numpy.f2py` tests. In that case, will it make sense to rephrase the sentence as 

> Compilers
> To build any extension modules for Python, you’ll need a C compiler. Optionally, you'll also need a FORTRAN 77 compiler installed. For more information, see [Choosing the fortran compiler](https://numpy.org/devdocs/user/building.html#choosing-the-fortran-compiler).

And in [Choosing the fortran compiler](https://numpy.org/devdocs/user/building.html#choosing-the-fortran-compiler) we add 

> The compiler will only be needed for running the `numpy.f2py` tests. These tests will be skipped if no compiler is auto-detected. Building with a particular compiler can be done with --fcompiler.

**Comment by rossbar** [comment]
The proposed wording seems to be almost there; if you're up to it I'd say go ahead and open a PR with the suggested wording so it can be reviewed and we can get this fixed!

**Comment by Mukulikaa** [comment]
Sure then, I'll make the PR!
