### ISSUE TITLE
Building Numpy with MKL attempts to link in libblas, even if it's not available

### ISSUE THREAD

**Issue by ehermes** [numpy/numpy#7995]
I am trying to build Numpy version 1.11.0 with the Intel compilers and Intel MKL for BLAS/LAPACK. My site.cfg is here:

https://gist.github.com/ehermes/e0b481fbf669d2cc2d9527ec7e542950

Attempting to build with `python setup.py --compiler=intelem --fcompiler=intelem` results in the following build log:

https://gist.github.com/ehermes/4f14e1880d06e974883a87ad04ff7f6d

Notably, "blas" is absent in the site.cfg, and the build log indicates libblas.so was not found, yet it was added to the list of found libraries. This did not occur with Numpy version 1.10.4, which builds successfully  with the same site.cfg and build command.

Edit: For the sake of clarity, the site.cfg was automatically generated by Portage, the Gentoo package manager. However, this build log is the result of me manually running the build command I indicated above in the Portage work directory. Nothing about this issue is Gentoo-specific.

**Comment by SoapGentoo** [comment]
The likely culprit here I believe is:

```
--- numpy-1.10.4/numpy/distutils/system_info.py	2016-01-07 03:16:25.000000000 +0100
+++ numpy-1.11.1/numpy/distutils/system_info.py	2016-06-26 01:59:40.000000000 +0200
@@ -665,7 +669,10 @@
         return [b for b in [a.strip() for a in libs.split(',')] if b]
 
     def get_libraries(self, key='libraries'):
-        return self.get_libs(key, '')
+        if hasattr(self, '_lib_names'):
+            return self.get_libs(key, default=self._lib_names)
+        else:
+            return self.get_libs(key, '')
 
     def library_extensions(self):
         static_exts = ['.a']
```

This will likely always add `-lblas`, even if the true blas has a different name (in Gentoo we rename blas to refblas in order to have multiple blas implementations installed concurrently). In Gentoo, I've reverted (https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=80b2e1b4def977bee9743d7bc52c01acf19fbb9a) this part and it works for me.

**Comment by rgommers** [comment]
This came from gh-7048. @zerothi fyi ping

Fixing one thing about ``site.cfg`` usage without breaking another is getting increasingly difficult. I'm not sure we should revert that commit or wait until the bigger overhaul needed to respect ``site.cfg`` rather than autodetect when a ``site.cfg`` is present.

**Comment by zerothi** [comment]
Yes, currently if you want to use mkl, you should use the blas_opt block, or the mkl block. In fact, I am curious as to why the blas_opt does not find anything...

I have just tried on my box with various settings, i.e. no MKL vars in my env, an equivalent site.cfg file as you have (replaced by my own paths), and trying to run the build command. 
I saw no double libraries and it got the correct MKL libraries without adding any blas libraries. 
However, I can perhaps see where this enters,
could you perhaps try out this branch:
https://github.com/zerothi/numpy/tree/site-cfg
which should contain a workaround for the thing you see, my guess is that this actually arises when trying to find the cblas library. The above branch contains a pre-check for the cblas library with the given libraries (no guessing!).

**Comment by zerothi** [comment]
bump, @ehermes could you try the branch I linked?

**Comment by andyfaff** [comment]
This issue can be closed now. The build system has changed completely, and there are examples on how to build with a variety of BLAS.
