### ISSUE TITLE
out kwarg to bincount

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7998]
`bincount` could gain an `out` kwarg (which would not get zeroed before adding the weights).

Rationale: This would sidestep the issue of poor ufunc.at performance (#5922) at least for the `add` ufunc.

I'd expect this kwarg to be incompatible with `minlength`; the `minlength` would simply be obtained from the length of the `out` array.

**Comment by jaimefrio** [comment]
So you would accumulate on top of the value already stored in the array? That's an interesting idea! Can you elaborate on how it replaces `.at`, maybe with an example? 

Deciding on doing this would probably need some discussion on the list, but implementing it should be relatively straightforward.

**Comment by anntzer** [comment]
Basically, you'd replace
```
indices = ...
weights = ...
counts = ... # perhaps a previous value, or just np.zeros(...)
np.add.at(counts, indices, weights)
```
by
```
counts = ...
np.bincount(indices, weights, out=counts)
```

TBH I feel it would be preferable to fix the performance of `ufunc.at`; OTOH given the discussion on #5922 I guess it's not going to happen any time soon, and this may be a reasonable and simpler to implement workaround.

**Comment by seberg** [comment]
I think you can get a speedup of maybe even up to 5 without completely overhauling `ufunc.at` implementation, though.

**Comment by mattip** [comment]
Closing, #23136 was merged
