### ISSUE TITLE
How to store random Seeds.

### ISSUE THREAD

**Issue by rbiswas4** [numpy/numpy#8004]
In an application, which has stochasticity, I use 
```
import numpy as np
rng = np.random.RandomState(4)
...
# I want to store the state of the random number here
rng.normal(0., 1., size=30.)
```
In order to keep this easily reproducible, I want to store the random state before the call to `rng.normal`. I know I can use
```
rng.get_state()
```
to get the state of the random number generator. Is this entire array something I need to store ? Do people store this array for such purposes?

**Comment by seberg** [comment]
Seeds use, I believe, another RNG to fill up the whole state. So, no, you cannot map the state to a seed and you have to store the whole state if you want to do this here. It seems you can also do `copy.copy(rng)` if that is more convenient.

**Comment by charris** [comment]
@rbiswas4 Note that you can pickle the RNG state. See http://stackoverflow.com/questions/20911147/choose-random-seed-and-save-it.
