### ISSUE TITLE
BUG: Build fails on OS X 10.9.5

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#8013]
The commit b831444bee734537daeaffd1455eb88663ee3763 added the line `fid.close()` to this bit of code in `distutils/gnu.py`:

```
def _can_target(cmd, arch):
    """Return true if the architecture supports the -arch flag"""
    newcmd = cmd[:]
    fid, filename = tempfile.mkstemp(suffix=".f")
    fid.close()
...
```

This causes the error `AttributeError: 'int' object has no attribute 'close'
` when building numpy on OS X.  `fid` is a file descriptor, which is an integer.  To close the file, use `os.close(fid)`.

Ping @seberg.

**Comment by seberg** [comment]
@WarrenWeckesser, tsorry for that oversight and thanks for the report. I opened gh-8014 to fix it.
