### ISSUE TITLE
numpy.loadtxt returns string repr of bytestring instead of string in Python 3

### ISSUE THREAD

**Issue by skjaeve** [numpy/numpy#8033]
Numpy version 1.11.1
Python version 2.7.12/3.5.1

When reading strings from a data file with numpy.loadtxt() in Python 3 the returned strings are string representations of bytestrings. In Python 2 normal strings are returned.

MWE:

``` python
from __future__ import print_function
import numpy as n

strings = ['str1', 'str2']
parsed = n.loadtxt(strings, dtype='str')
print('Result:', parsed)

```

which, when executed, gives different results for Py2 and Py3.

```
$> python2 mwe.py 
Result: ['str1' 'str2']
$> python3 mwe.py 
Result: ["b'str1'" "b'str2'"]
```

Python 2 gives strings as expected, Python 3 gives strings containing the string representation of bytestrings.

Workarounds have been suggested at http://stackoverflow.com/q/39371467/912307

**Comment by hjorne** [comment]
Having this issue as well, where something like parsed[0][0] == "b" and parsed[0][1] == "'" is happening across all entries returned by loadtxt
