### ISSUE TITLE
Integer np.array - differences in division and power

### ISSUE THREAD

**Issue by jacobnzw** [numpy/numpy#8035]
Hi, I'm running Python 3.5.2 :: Anaconda 4.1.1 (64bit) with NumPy 1.11.1 on Windows 10. I get this strange behaviour in the following

```
a = np.array([3])
print(a**-1)
print(1/a)
```

which prints

```
[0]
[ 0.33333333]
```

I think both results should be `float`.

**Comment by charris** [comment]
The division is `true_division`, hence specified to return float. The problem with the first case is when there are mixed power, i.e., the exponent is an array. In that case the positive exponents should return integers and the result type needs to depend on the input types, in distinction to the element values. I think we have decided to raise an error for integers raised to negative integer exponents.

**Comment by brauliobarahona** [comment]
There is no difference in division and power when the inputs are consistent:

`a**-1.`

will return a float
