### ISSUE TITLE
Invalid result from ufunc.reduce with output array

### ISSUE THREAD

**Issue by pv** [numpy/numpy#8036]
ufunc.reduce appears to produce wrong result for some input/output stride combinations:
```
import numpy as np

x = np.ones((7, 13, 8), np.int16)
x = x[4:6,1:11:6,1:5].transpose(1, 2, 0)
y = np.ones((4, 4), np.int16)[::2,:]

r0 = np.add.reduce(x, out=y.copy(), axis=2)
r1 = np.add.reduce(x, out=y, axis=2)

print(np.__version__)
print(r0)
print(r1)
assert np.all(r0 == r1)
```
It prints:
```
1.11.0
[[2 2 2 2]
 [2 2 2 2]]
[[2 2 2 2]
 [0 0 0 0]]
Traceback (most recent call last):
  File "overlap2.py", line 13, in <module>
    assert np.all(r0 == r1)
AssertionError
```
Discovered by fuzzing.

**Comment by pv** [comment]
The output array gets clobbered out of bounds:
```
# y.base before
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
# y.base after
[[2 2 2 2]
 [3 3 3 3]
 [0 0 0 0]
 [1 1 1 1]]
```

**Comment by pv** [comment]
Probably iterator bug
```
import numpy as np

x_base = np.ones((7, 13, 8), np.int16)
x = x_base[4:6,1:11:6,1:5].transpose(1, 2, 0)

y_base = np.ones((4, 4), np.int16)
y = y_base[::2,:,None]

it = np.nditer([y, x], ['buffered', 'external_loop', 'reduce_ok'],
                       [['readwrite'], ['readonly']])
a, b = next(it)
a.fill(2)

# fails if 'buffered' is in global flags
assert np.allclose(y_base[1::2], 1)
```

**Comment by charris** [comment]
That would be @seberg's specialty.

**Comment by pv** [comment]
I think the issue is here https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/nditer_api.c#L2341 or maybe here https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/nditer_api.c#L2701, but how the buffering is supposed to work is over my head currently.

**Comment by seberg** [comment]
The buffering is really confusing... also that buffer reuse code. Got to enable the iterator debug print maybe something there gives hints.

**Comment by pv** [comment]
It think it's some interaction in which `npyiter_checkreducesize` computes transfersize ignoring array contiguity, and later on the code path in `npyiter_copy_to_buffers` decides that the array can actually be used directly without copying to buffer --- which is incorrect because the transfersize is too big vs. continuity.

But I don't know which one is the wrong thing, or whether both are working as intended but the bug is somewhere else.

**Comment by seberg** [comment]
All of these branches/cases are always really confusing, it sounds like you already dug deeper then I would have any knowledge. I might try to dig into it later....

**Comment by seberg** [comment]
Guessing a bit, maybe this branch should not be enabled (with the Iterator: Operand %d has stride 0 in the outer loop?) when the outer loop has a size of 1?

**Comment by seberg** [comment]
Nah, silly guess...

**Comment by seberg** [comment]
@pv did you figure out the `(reduce_outerdim > 0)` part? of that `if` statement?

**Comment by seberg** [comment]
I could imagine the error is that there is an assumption here that a reduction always has a zero stride as one of the first two iterator dimensions.

**Comment by pv** [comment]
Sorry, I don't have currently any understanding of how this part of the code is supposed to work.

**Comment by seberg** [comment]
Me neither :). By now I think it probably really is that if that you changed which is bad.

Making the check in the if `reduce_outerdim == 1` seems enough to fix it. If those axes could be coalesced for this operand (but not for the other), then this is probably slightly less efficient in some cases.

**Comment by seberg** [comment]
Its also not the intended thing in the case of multiple reduction dimensions, hmmm.

**Comment by seberg** [comment]
On line 2250 `(reduce_outerdim == 1)` is being used (and its original code by Mark), which suggests that the idea of just making it more strict there may not be all wrong....

**Comment by pv** [comment]
That at least fixes it in fuzz tests, FWIW

**Comment by seberg** [comment]
Ahhh! OK, I think I just got a bit enlightened... The first branch of it checks `ad_strides[iop] == 0`. So in this branch we know that we are basically like a normal iteration and not like a reduction. So I do think the `== 1` check is "good enough", in the sense that it is no better then intended in the non-reduction operands.

**Comment by seberg** [comment]
If we assume that is correct in the non-reduce part (where the identical check exists) when `reduce_outerdim == 1` should be correct.

@pv do you have some nice tests, if yes can you open a PR? Change could use a line or two of extra comment....

**Comment by pv** [comment]
gh-8042

**Comment by pv** [comment]
Fixed in gh-8042
