### ISSUE TITLE
Stochastic behaviour even after setting random.seed()

### ISSUE THREAD

**Issue by gan3sh500** [numpy/numpy#8041]
numpy.random.multivariate_normal() result is not reproducible even if numpy.random.seed() is set. 
`
np.random.seed(9)
class1 = np.random.multivariate_normal(mean, cov, n_samples)
class2 = np.random.multivariate_normal(mean, cov, n_samples)
` 
class1 won't be the same as class2. When I generate mean and cov with np.random.rand() it is reproducible. cov is a positive semi-definite matrix I generated using np.dot(A,A.T) where A is generated with random.rand()
 
This was on Python 2.7.12 with Numpy 1.11.1 on Ubuntu 16.04.1

**Comment by seberg** [comment]
Sometimes linear algebra operations are not completely reproducible. Especially if they are ill conditioned. Maybe you should check whether your cov array is not ill conditioned.

I do not think this has anything to do with the random numbers (or even with numpy itself). It is rather a behaviour of different optimization branches/stochastic behaviour inside the linear algebra library you linked against.

**Comment by seberg** [comment]
In other words. `np.random.multivariate_normal` uses `np.dual.svd` (probably same as `np.linalg.svd`). The random behaviour will certainly already be visible in the `np.linalg.svd(cov)` call.

**Comment by MSeifert04** [comment]
@gan3sh500 Just out of curiosity: Do you set the seed to your value again between `class1 = ...` and `class2 = ...` calls?

**Comment by gan3sh500** [comment]
The data generated from each run of the code is same but from calling the function multiple times they are not.  @MSeifert04 I now tried to re-set the seed and it helps a lot. Although not identical the data generated is much closer in class1 and class2.  @seberg I am guessing these small changes are from the stochastic nature of the linalg part.

Thank you for the quick and helpful answers.

**Comment by seberg** [comment]
OK, I think I will close this (though feel free to keep discussing). If you think a note in the documentation would have helped you, please do have a look and open a pull request to improve it!
