### ISSUE TITLE
Unattended installation for Windows

### ISSUE THREAD

**Issue by Furiml** [numpy/numpy#8048]
Hello,
I'm currently deploying build machines in my company, and I'd like to perform an unattended installation of numpy, without the use of third party softwares (like AutoIt).
I stumbled on this : https://mail.scipy.org/pipermail/numpy-discussion/2012-April/061892.html
which seemed promising, but I can't find more information about it, and it is old.
I'm currently deploying v1.5, but maybe if newer versions come with a unattended-capable installer, we may change that. In the mean time, is there something I can do to perform such install for this version ?

Thanks :)

**Comment by rgommers** [comment]
Hi @Furiml, that's all old indeed. We don't do .exe installers anymore. You want to use either wheels from PyPI (install with pip) or conda packages (installed with Anaconda/Miniconda). Both you can very easily automate completely without any of the trouble with NSIS installers.
