### ISSUE TITLE
isnan, isinf, isposinf, isneginf, isfinite raise RuntimWarning for some float32 and float64 NaN's but not others

### ISSUE THREAD

**Issue by frejanordsiek** [numpy/numpy#8049]
I've had this mysterious warning for well over a year for several versions of Numpy in different versions of Python 2.x and 3.x on different machines and OS's. Finally tracked it down today (Numpy 1.11.1 on Debian Jessie little-endian x64 Linux in Python 3.4.2). I've found this issue for float32/complex64 and float64/complex128. It does not exist for float16.

If we make two float32's a and b that are NaN, but different ones.

```
>>> import numpy
>>> a = numpy.ndarray(shape=(), dtype='float32', buffer=b'\x00\x00\xc0\xff')
>>> b = numpy.ndarray(shape=(), dtype='float32', buffer=b'\x00\xe0\xbf\xff')
```

Note, if you are on a big endian machine, you will need to swap the byte order.

Displaying them,
```
>>> a, b
(array(nan, dtype=float32), array(nan, dtype=float32))
```

Then, evaluating whether they are NaN with ``numpy.isnan`` gives no problem for ``a``

```
>>> numpy.isnan(a)
True
```

But doing it for ``b`` does return the right answer but throws a warning

```
>>> numpy.isnan(a)
/home/USERNAME/.local/bin/ipython3:1: RuntimeWarning: invalid value encountered in isnan
True
```

specifically a ``RuntimeWarning``.

I get the same thing with the following functions, including ``isnan``

isnan
isinf
isneginf
isposinf
isfinite

Get the same thing for float64 if instead we make a and b as

```
>>> a = numpy.ndarray(shape=(), dtype='float64', buffer=b'\x00\x00\x00\x00\x00\x00\xf8\x7f')
>>> b = numpy.ndarray(shape=(), dtype='float64', buffer=b'\x00\x01\x00\x00\x00\x00\xf0\x7f')
```

It is easy to confirm that it is not an issue for float16 for all possible float16 values with

```
>>> c = numpy.arange(0, 2**16, dtype='uint16').view('float16')
>>> d = numpy.isnan(c)
```

In case anyone is wondering where this comes up, it comes up when generating ndarrays with completely random bytes, which is useful for unittests.

**Comment by juliantaylor** [comment]
this happens because you are generating signaling NaN scalars which throw fpu exceptions also on the typical ways you check for special values fast.
see also gh-7838
