### ISSUE TITLE
ndarray.tolist() not working recursively with structured arrays

### ISSUE THREAD

**Issue by christophercrouzet** [numpy/numpy#8052]
```
>>> dtype = numpy.dtype([('position', numpy.int32, 3)])
>>> values = [([1, 2, 3],), ([4, 5, 6],)]
>>> a = numpy.array(values, dtype=dtype)
>>> a.tolist()
[(array([1, 2, 3], dtype=int32),), (array([4, 5, 6], dtype=int32),)]
```

In the code snippet above, I would have thought that `a.tolist()` would return `[([1, 2, 3],), ([4, 5, 6],)]` instead of a structure still containing non-expanded versions of `ndarray` objects.

Is this behaviour to be expected?

I wrote a quick and dirty workaround but this is far from optimal as it duplicates part of the work of `ndarray.tolist`.

```
def array_to_list(array):
    if isinstance(array, numpy.ndarray):
        return array_to_list(array.tolist())
    elif isinstance(array, list):
        return [array_to_list(item) for item in array]
    elif isinstance(array, tuple):
        return tuple(array_to_list(item) for item in array)
    else:
        return array
```

For reference, this question was first raised on StackOverflow http://stackoverflow.com/questions/39502461/truly-recursive-tolist-for-numpy-structured-arrays

**Comment by seberg** [comment]
Closing as won't-fix.  I don't think recursive unpacking should be expected from NumPy here.  Maybe we can discuss on a new issue, but since this is now 6 years old...
