### ISSUE TITLE
`deprecate` adds extra indentation

### ISSUE THREAD

**Issue by person142** [numpy/numpy#8058]
Suppose I do:

``` python
>>> def foo():
...     """This is the docstring for foo.
...
...     It has two lines.
...     """
...
>>> help(foo)
```

I get this:

```
Help on function foo in module __main__:

foo()
    This is the docstring for foo.

    It has two lines.
```

Now let's deprecate `foo`:

``` python
>>> foo = np.deprecate(foo, new_name='bar')
>>> help(foo)
```

The docstring now reads:

```
Help on function foo in module numpy.lib.utils:

foo(*args, **kwds)
    `foo` is deprecated, use `bar` instead!

    This is the docstring for foo.

        It has two lines.
```

The third line ("It has two lines") has gained an extra level of indentation.

**Comment by wrwrwr** [comment]
This can be traced back to how [`inspect.cleandoc()`](https://github.com/python/cpython/blob/c30098c8c6014f3340a369a31df9c74bdbacc269/Lib/inspect.py#L582) removes indentation &ndash; "uniformly from the second line onwards". The original first line becomes the second line, but it has no indentation, so the following lines are left unstripped.
