### ISSUE TITLE
Structured array - Introduction - Doc error

### ISSUE THREAD

**Issue by Francois888** [numpy/numpy#8067]
On page : http://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html
Structured array - Introduction
In the example : "Conveniently, one can access any field of the array by indexing using the string that names that field."

```
        y = x['foo'] should be >>> y = x['bar'] (the actual name of the "second" field which is addressed along the example).
        Additionally, this has to be updated at several places on the page.
```

**Comment by ahaldane** [comment]
I have a rewrite of the structure array docs that will probably get in 1.13, to accompany #6053.

https://gist.github.com/ahaldane/7d1873d33d4d0f80ba7a54ccf1052eee

I think I've fixed those problems there.
