### ISSUE TITLE
lack of warning when applying ufunc to np.array([np.nan])

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#8068]
As of 1.11.1, `np.array([np.nan]) > 0` fails to trigger a warning, while `np.array([np.nan, 1]) > 0` triggers a

```
RuntimeWarning: invalid value encountered in greater
```

as expected.

**Comment by seberg** [comment]
@anntzer this has been a few years, and both paths raise a warning for me. I somewhat think there may have been fixes along these lines (although there were also common issues e.g. on windows). I will tentetavily close it, but if someone sees similar issue (with platform information), we should reopen/create a new issue.

**Comment by anntzer** [comment]
Actually, I see the issue again on fedora with numpy 1.17.2, pypi wheels, cpython 3.7.3, so can this be reopened?

**Comment by seberg** [comment]
Sure, I will reopen. I am not actually sure it is supposed to trigger a warning here, I do not think it should, there is no new NaN created here...

**Comment by anntzer** [comment]
I'm not really sure whether it should trigger a warning either, but my main puzzlement comes from size-1 and size-2 arrays having different behaviors.

**Comment by seberg** [comment]
Going to close, pretty sure this is now set to "we don't warn for comparisons", which actually diverges from IEEE, but...

If anyone has historic curiosity:  IIRC, gcc at some point started to ensure the warning (correct, but surprising to those who didn't have them before).  Then SSE came around it didn't support the warnings so they tended to vanish again, I think (mostly)... And by now we ensure that last thing thing.
