### ISSUE TITLE
memmap performance when slicing with large step

### ISSUE THREAD

**Issue by fkloosterman** [numpy/numpy#8070]
Hi,

I am using numpy.memmap to memory map a large (~40GB) file, where each record has a size of 500kB. When testing the performance, I noticed that retrieving a slice of N records with step 1 is much faster than retrieving N records with larger step:

dtype = np.dtype( [('a','>u4'),('b','>u4',(20,)),('c','>u4',(480,))])
f = np.memmap( filename, mode='r', dtype=dtype) 
%timeit -n1 -r1 f[0:500000:500] # takes ~7.5 seconds
%timeit -n1 -r1 f[1000000:1001000:1] # takes ~140 ms

Why is slicing a memmap with step size larger than 1 so much slower?

**Comment by charris** [comment]
Hmm, interesting. creating a view shouldn't take much time unless the data is being brought into memory, in which case disk seek time would play a role. I'm not sure how memmap is handling that.

**Comment by charris** [comment]
This sort of question is best asked on the mailing list.

**Comment by fkloosterman** [comment]
Sorry, there was an omission in my example code. In my actual test I did:
`np.array( f[0:500000:500] )`, which was slow (just creating a view without np.array was fast). So, it seems that indeed loading the data into memory is slow.

In any case, I will ask my question on the mailing list.

**Comment by charris** [comment]
Oh, in that case seek time is probably the dominant factor. For large files it often pays to sort them into an order compatible with the intended use so that data is accessed sequentially. Seek times are much better with SSDs than spinning disks, I don't know which you are using. 

In anycase, closing this.
