### ISSUE TITLE
histogram crashes cryptically with single float bin

### ISSUE THREAD

**Issue by guetg** [numpy/numpy#8072]
This code:
`np.histogram(np.random.random(1000), bins=100.1) # Crashes`

works fine with python3.4 & numpy 1.9.2. However it crashes with 3.5.2 & numpy 1.11.1 with the following error msg:

```
 File "test.py", line 8, in <module>
     np.histogram(np.random.random(1000), bins=100.1)
 File "/home/bin/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py", line 603, in histogram
      increment = (tmp_a_data >= bin_edges[indices + 1]) & (indices != bins - 1)
  IndexError: index 101 is out of bounds for axis 1 with size 101
```

I know that bins should be int, but I would suggest either better error message or floor/ceil to make it int like in 1.9.2

**Comment by charris** [comment]
In master this raises an a somewhat better, but totally misleading, error
```
TypeError: 'float' object cannot be interpreted as an index
```

**Comment by seberg** [comment]
Just a side comment, I just noticed (after wondering about whether a change in python would make sense), that this is actually changed in python, so that it does say "integer" instead of the confusing "index in python 3.5 (probably earlier, thought not my python 2.7).

**Comment by eric-wieser** [comment]
Now raises `TypeError( '`bins` must be an integer, a string, or an array')`
