### ISSUE TITLE
difference between __matmul__ and dot

### ISSUE THREAD

**Issue by akhmerov** [numpy/numpy#8074]
I have accidentally discovered a confusing difference in numpy v1.11.1 (but probably everywhere):

```python
>>> np.dot(np.identity(2), np.array(2))
array([[ 2.,  0.],
       [ 0.,  2.]])
>>> np.identity(2) @ np.array(2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-f1c5259fce13> in <module>()
----> 1 np.identity(2) @ np.array(2)

ValueError: Scalar operands are not allowed, use '*' instead
```

I expected that:
* 0-d arrays are a convenience for scalars to behave similar to arrays, and the behavior of dot product seems to follow this idea.
* `__matmul__` should be identical to `np.dot`, how come there's a difference?

**Comment by charris** [comment]
It's a feature, not a bug ;) See `doc/neps/return-of-revenge-of-matmul-pep.rst`, in particular
```
* 0d (scalar) inputs raise an error.  Scalar * matrix multiplication
  is a mathematically and algorithmically distinct operation from
  matrix @ matrix multiplication, and is already covered by the
  elementwise ``*`` operator.  Allowing scalar @ matrix would thus
  both require an unnecessary special case, and violate TOOWTDI.
```
However, I note that this seems to conflict with the earlier example in the NEP that multiplies two scalars together. Hmm... @njsmith Thoughts.

**Comment by shoyer** [comment]
> However, I note that this seems to conflict with the earlier example in the NEP that multiplies two scalars together.

Can you point this out more specifically?

I'm pretty sure `@` is working as intended. Note that `@` in NumPy is implemented by `np.matmul`.

**Comment by akhmerov** [comment]
@charris, @shoyer thanks for the clarification. While the current situation is somewhat confusing, I understand that numpy just directly follows the PEP presciption. Well except for the product of two scalars :-)

**Comment by seberg** [comment]
We actually merged `doc/neps/return-of-revenge-of-matmul-pep.rst`? Hahar, wasn't that just the draft for the PEP?

**Comment by charris** [comment]
@seberg Yep, I merged it. History and all that. 

@shoyer I see I was misreading the examples, where `arr(3)` was not a scalar array, but rather a 1d array with three elements.
