### ISSUE TITLE
numpy.add.accumulate(), numbers get high very fast => problems with int

### ISSUE THREAD

**Issue by noob5** [numpy/numpy#8078]
When i have the follwing code:

```
import numpy as np
a = [12414, 33103, 41379, 88964, 142756, 328960, 693092, 2228239, 27359548, 750138639, 2040789728, 188603780]
print np.add.accumulate(a)
```

the result is result is:

```
array([      12414,       45517,       86896,      175860,      318616,
            647576,     1340668,     3568907,    30928455,   781067094,
       -1473110474, -1284506694])
```

It seems that internally the "wrong" int-dtype is chosen. Because high numbers are reached very fast with np.add.accumulate(a) and even faster with np.multiply.accumulate(a).

edit: this is probably a policy issue, but a warning (in the docs) would be nice

**Comment by charris** [comment]
Yep, integer overflow. It is a feature of NumPy which takes the C approach. If you need to sum large numbers of large numbers there are three alternatives: 

- use floats, where overflow is replaced by precision loss.
- use a larger integer type, if available
- use object arrays of python integers (slow) 

If you can find a good place in the docs to note this potential problem a PR would be welcome.
