### ISSUE TITLE
why the language is C?

### ISSUE THREAD

**Issue by crazy-canux** [numpy/numpy#8079]
I saaw the language is C?

**Comment by charris** [comment]
What is the question or problem?

**Comment by nouiz** [comment]
A quick answer. Numpy is old. What I read once was that when it was stated,
not all platform as a good C++ compiler. So for better compatibility it was
fine in C.

Le 21 sept. 2016 11:13, "Charles Harris" <notifications@github.com> a
écrit :

**Comment by charris** [comment]
Note that cPython is also in C.
