### ISSUE TITLE
NPY header alignment

### ISSUE THREAD

**Issue by superbobry** [numpy/numpy#8085]
According to the NPY format [spec](http://docs.scipy.org/doc/numpy-dev/neps/npy-format.html), the header should be padded to be aligned on the 16-byte boundary

> The next `HEADER_LEN` bytes form the header data describing the array’s format. It is an ASCII string which contains a Python literal expression of a dictionary. It is terminated by a newline (‘n’) and padded with spaces (‘x20’) to make the total length of the magic string + 4 + `HEADER_LEN` be evenly divisible by 16 for alignment purposes

The 4 in the above formula accounts for 
- 2 version bytes and 
- `HEADER_LEN` itself, which is 2 bytes in NPY1.0. 

Interestingly, the same formula [is used](https://github.com/numpy/numpy/blob/master/numpy/lib/format.py#L311) for NPY2.0 files, despite the fact that `HEADER_LEN` is now 4 bytes. Therefore, NPY2.0 file header is not guaranteed to be aligned. I think this might be worth pointing out in the docs.

By the way, did anyone ever profile this optimization?

**Comment by charris** [comment]
@juliantaylor IIRC, you did the npy 2 format. I don't know if this can be fixed in a way compatible with files already out there, or even if it still matters. SPARC might be a problem.

**Comment by juliantaylor** [comment]
should be a backward compatible change as it just would just change the number of padding spaces

the alignment is very unlikely to be relevant for performance but might be worthwhile to fix it or update the documentation.

**Comment by superbobry** [comment]
> should be a backward compatible change as it just would just change the number of padding spaces

Completely dropping the padding should also be backward compatible, since NumPy does `safe_eval` and any alternative implementations (if any) probably just strips the spaces before further processing.
