### ISSUE TITLE
Force float32 computations in numpy?

### ISSUE THREAD

**Issue by the-bobo** [numpy/numpy#8086]
Apologies if this is the wrong place for this question, did not know where else to ask.

I'm producing some code using numpy to run some evaluation tests on neural nets with specific bit-widths for weights, activations, and gradients. I wanted to ensure that calculations were being done in float32. I know that I can use `.astype('float32')` with `np.zeros` or `np.random.randn`, and get a float32 `ndarray`.

My question is - if i then use a method like `np.dot` will these computations be done in float32? Or will they first be done in float64, and then cast down into float32 (perhaps to try to avoid rounding errors)?

Judging from https://github.com/numpy/numpy/blob/1429c606643d1ad305e710c4a31cb6f398d04c53/numpy/core/src/multiarray/cblasfuncs.c#L64 and http://docs.scipy.org/doc/numpy/reference/c-api.dtype.html#c.NPY_FLOAT it appears that `np.dot` will perform the computations in the type that the array has. So if I call `np.dot` with float32 arrays, then float32 calculations will be done, if I am correct in thinking that CBLAS is what is being used for `np.dot`.

Is this understanding correct? I am new to numpy so appreciate guidance. Thank you!

**Comment by charris** [comment]
The dot functions do indeed preserve real and complex float32 and float64. No such guarantee is made for ufuncs, which will fall back on the nearest available type if the wanted function is not available. The success of what you are trying do will depend on the details. I note that scipy offers better support 32 bit versions of LAPACK functions and the FFT. 

Questions like this are best addressed to the numpy mailing list, as it isn't an issue per se. However, I'm not sure the mailing list is working at the moment, at least my posts are not showing up.

**Comment by the-bobo** [comment]
@charris  - sorry to resuscitate this thread, but do you know of any way of making the `dtype` of a numpy array be the same kind of ints that python natively uses - namely, the flexible bit-width arbitrary-precision integers? i could not find documentation for this as an option. again, this would be useful for some experiments i am running with fixed bit-width neural nets, thank you.

**Comment by shoyer** [comment]
You can make an array full of Python integers with `dtype=object`, but it is going to have very slow performance.

**Comment by the-bobo** [comment]
@shoyer  - thanks, i may end up using `dtype=object` and `bitarray` (https://pypi.python.org/pypi/bitarray)

Can anyone tell me what `NPY_USERDEF` does? Can I use that to get my fixed bit-width integers? Found it in the documentation here but couldn't find any discussion of it when googling: http://docs.scipy.org/doc/numpy/reference/c-api.dtype.html

**Comment by shoyer** [comment]
NumPy's dtype system is extensible in theory, but very rarely done in practice (@mwiebe may be the only person to have done so from scratch). There are a few examples floating around out there, e.g., https://github.com/moble/quaternion

**Comment by mwiebe** [comment]
https://github.com/numpy/numpy-dtypes was created as a place for extension types, but looks like it hasn't been touched in a number of years.
