### ISSUE TITLE
linalg.cond does not check for exact zero

### ISSUE THREAD

**Issue by ilayn** [numpy/numpy#8090]
For the following case, the convention is to give `np.inf` which is also consistent with the documentation

```
C = np.zeros((3,3))
np.linalg.cond(C)
```

however, does the following 

```
c:\....\appdata\local\programs\python\python35\lib\site-packages\numpy\linalg\linalg.py:1457: 
RuntimeWarning: invalid value encountered in true_divide
  return s[..., 0]/s[..., -1]
Out[1]: nan
```

Similarly, if a singular matrix is given, the algorithm does not check the health of the inversion but direclty inverts the matrix regardless of the norm used.  Hence, 

```
cond([[1,1],[1,1]],2)
```

thus throws a `LinAlgError` for singular matrix. This defeats the purpose of the function since I am trying to monitor this information without the exception. I guess a simple check for exact zero singular values would rule out these possibilities.

**Comment by rudolphyo** [comment]
Hi!

I`d like to try it. As I understand, everything that concerns cond() located [here ](https://github.com/numpy/numpy/blob/master/numpy/linalg/linalg.py).

I guess that simple "hard-coding" of zero case isn`t a workaround.

**Comment by rgommers** [comment]
@rudolphyo go for it.

> I guess that simple "hard-coding" of zero case isn`t a workaround.

No. That doesn't address the second example @ilayn gave, and doesn't sound like the best idea.

**Comment by ilayn** [comment]
Hi @rudolphyo , please by all means go for it. A typical way is to get the exact zeros out of the way first. 

Currently the code is 
```
    x = asarray(x)  # in case we have a matrix
    if p is None:
        s = svd(x, compute_uv=False)
        return s[..., 0]/s[..., -1]
    else:
        return norm(x, p, axis=(-2, -1)) * norm(inv(x), p, axis=(-2, -1))
```


A rough pseudo-code might be 

  1. If p = None then look at the last value of singular value s[...,-1] compare it with 0. and emit `np.inf` if true
  2. If p is None and it is not exact zero then let it do its thing as above. 
  3. If p is something else then None then again check for low rank or singularity and emit inf without inverting the matrix. 

You can find more inspiration [here on this page](https://people.sc.fsu.edu/~jburkardt/m_src/condition/condition.html). There are also Python versions. It would be great if you can also test with those horribly ill-conditioned matrices :) One thing to keep in mind if you are not familiar with the subject that ill-conditioned does not imply singularity. The converse is trivially true though.

**Comment by rudolphyo** [comment]
Hello @ilayn !

I greatly appreciate materials you provide!

I am currently working on an issue, and one question appeared. "Test whether x is a zero matrix..." does it mean that my solution should be able to work with very close to zero matrix? As far as I know, if determinant of x is very close to zero there may appear some problems in calculation of conditional number. Is there any thoughts on this? 

Basic solution will be in a day.

Thanks for responding!

**Comment by ilayn** [comment]
@rudolphyo, it is indeed a very obscure corner case but a completely zero matrix can also be provided by the user or some algorithm fails to find a solution and spits out an exact `np.zeros((m,n))` . That case can be checked with `np.any(x)` and can be discarded right away. 

Note however that determinant is not a sensitive-enough measure of the problem, for example, a block diagonal 2x2 matrix with 1e10 and 1e-10 on the diagonal has a very nice determinant 1.

**Comment by pv** [comment]
Here, one should note the function supports stacked matrices. The fix 
AFAICS is:
.
* In the branch where SVD is used, replace s[-1]==0 results with inf.
* In the branch where SVD is not used, there needs to be either an 
explicit outer loop and the LinAlgError exception caught for each item. 
Alternatively, the inv(x) LAPACK error handling could be extended, but 
this needs more discussion since it's not the only routine that could 
use such a thing (see issue #xxx on the TODOs left for generalized 
linalg ufuncs).
.
There's no way to know a priori whether LAPACK runs into an exactly zero 
pivot in inv(x), so the only way to deal with this as far as I see is to 
catch the LAPACK error and return inf for those cases.

**Comment by pv** [comment]
Also, instead of adding kwargs to inv(x), it's also possible to use the 
underlying generalized ufunc directly, and adjust the error handling 
that way.

**Comment by ilayn** [comment]
@pv That doesn't sound robust enough to rely on `inv`. This has to be caught before inverting the matrix to avoid problems. Hence first a decomposition is needed anyways (svd or rank-revealing qr etc.). If @rudolphyo haven't started I can submit a PR for this (after deciding on Riccati stuff). I have another one waiting for https://github.com/scipy/scipy/issues/6634 and then I will attempt to see if I can do anything about https://github.com/numpy/numpy/issues/3755) . 

Can you elaborate on the "stacked" matrices ?
