### ISSUE TITLE
confused by numpy with blas and lapack

### ISSUE THREAD

**Issue by tonyzeng2016** [numpy/numpy#8091]
my os is  ubuntu 14.04,lapack  and blas have been installed  by:
sudo apt-get install libblas libblas-dev liblapack liblapack-dev

installed numpy by typing "python setup.py install " and import from prompt, numpy.show_config() shows the following:

blas_info:
    libraries = ['blas']
    library_dirs = ['/usr/lib']
    language = f77
lapack_info:
    libraries = ['lapack']
    library_dirs = ['/usr/lib']
    language = f77
atlas_threads_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['blas']
    library_dirs = ['/usr/lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1)]
...

but when typing " id(numpy.dot)==id(numpy.core.multiarray.dot)",the result is "True".

I tried some versions,just as numpy-1.8.0,numpy-1.10.3 and numpy-1.11.2rc1.
can any suggestion??

**Comment by pv** [comment]
The test `id(numpy.dot)==id(numpy.core.multiarray.dot)` is always True 
regardless of whether BLAS is used or not in recent numpy versions.

**Comment by tonyzeng2016** [comment]
I already solved the problem. In recent numpy versions,just less than 1.10,if the test "id(numpy.dot)==id(numpy.core.multiarray.dot) " is True, it means numpy doesn't call Blas to do matrix dot.but in recent versions,the test is always True,It doesn't indicate no calling to Blas.
