### ISSUE TITLE
Bit-level difference in logspace between MacOS X and Linux

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#8092]
In recent versions of Numpy (I haven't tracked down exactly when this happened), np.logspace has started to return very slightly different results in some cases with ``np.logspace``:

**OS X - Numpy 1.11.1 - Python 3.5**

```
In [7]: np.logspace(0, 20, 100)[75]
Out[7]: 1417474162926801.8
```

**Linux - Numpy 1.11.1 - Python 3.5**

```
In [3]: np.logspace(0, 20, 100)[75]
Out[3]: 1417474162926802.0
```

Is this expected? If so, feel free to close this issue.

**Comment by shoyer** [comment]
In general, I don't think NumPy guarantees precise bit-level equality for floating point operations across platforms, since we rely on system libraries which may differ slightly.

**Comment by rgommers** [comment]
the difference is <1 ULP, so not unexpected.
