### ISSUE TITLE
Verbose output from np.testing.assert_equal incorrectly shows 'nan' values

### ISSUE THREAD

**Issue by mwtoews** [numpy/numpy#8095]
By example, with Python 2.7 on Windows and shown below on CentOS 6 Linux:

``` python
>>> import numpy as np
>>> print(np.version.version)  # 1.11.1
>>> a = np.ma.array([1.1, 2.0, 3.0], mask=[False, True, False])
>>> b = np.ma.array([1.2, 2.2, 3.1], mask=[True, False, False])
>>> print(a)  # [1.1 -- 3.0]
>>> print(b)  # [-- 2.2 3.1]
>>> np.testing.assert_equal(a, b)
/opt/anaconda/lib/python2.7/site-packages/numpy/ma/core.py:4144: UserWarning: Warning: converting a masked element to nan.
  warnings.warn("Warning: converting a masked element to nan.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 320, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 811, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/opt/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 737, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 100.0%)
 x: MaskedArray([ 1.1,  nan,  3. ])
 y: MaskedArray([ nan,  2.2,  3.1])
```

(Note with this example, the last elements of the arrays contains the only valid non-equal value that triggers the message.)

As shown in the verbose output, the arrays are shown having 'nan' values, when the arrays do not contain any 'nan' values.

Similar message can also be shown with `np.testing.assert_allclose(a, b)` and `np.testing.assert_almost_equal(a, b)`.

**Comment by rgommers** [comment]
>>> from numpy.ma import testutils
>>> testutils.assert_equal(a, b)
AssertionError: 
Arrays are not equal

(mismatch 33.33333333333333%)
 x: array([ 1.,  1.,  3.])
 y: array([ 1. ,  1. ,  3.1])

**Comment by rgommers** [comment]
``np.testing`` is not very ``ma``-aware, so I think this is expected.

**Comment by mattip** [comment]
Closing. The warning is a good enough indication that something is wrong. If someone feels we could somehow increase the discoverability of `numpy.ma.testutils.assert_equal` over `np.testing.assert_equal` for masked arrays, they should reopen
