### ISSUE TITLE
`asarray` get array of no `shape`

### ISSUE THREAD

**Issue by Rholais** [numpy/numpy#8101]
In `1.11.1`, `asarray` works well:

> Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> Anaconda is brought to you by Continuum Analytics.
> Please check out: http://continuum.io/thanks and https://anaconda.org
> >>> from PIL import Image
> >>> pic = Image.open('./test.png')
> >>> pic.size
> (1200, 1200)
> >>> import numpy
> >>> numpy.version.version
> '1.11.1'
> >>> pix = numpy.asarray(pic)
> >>> pix.shape
> (1200, 1200)

However, `1.12.0` is not working:

> Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from PIL import Image
> >>> pic = Image.open('./test.png')
> >>> pic.size
> (1200, 1200)
> >>> import numpy
> >>> numpy.version.version
> '1.12.0.dev0+86c780d'
> >>> pix = numpy.asarray(pic)
> >>> pix.shape
> ()

I was wondering if there was any logic change of `asarray`?

**Comment by seberg** [comment]
Frankly, seems more likely due to PIL then due to numpy, are you sure you got the same PIL version?

**Comment by Rholais** [comment]
@seberg  Thanks a lot! I'll check it.

**Comment by Rholais** [comment]
@seberg  Fixed by using the pillow package.
