### ISSUE TITLE
Can't do a formatted print of a <class 'numpy.core.memmap.memmap'> returned by a.mean(a)

### ISSUE THREAD

**Issue by Christopher-Field** [numpy/numpy#8108]
The second line of the program fragment below succeeds if b is a regular numpy array
but generates a TypeError if b is a memory mapped array (memmap).

m2 = b.mean()
print("The mean of b is {:f}.".format(m2))

TypeError: non-empty format string passed to object.__format__

The work around is a specific type change as 
print("The mean of b is {:f}.".format(float(m2)))

A program demonstrating the success and failure is attached. I have observed the error in python 2.7 with numpy 1.10.4, python 3.5 with numpy 1.10.4, and pythion 3.5 with numpy 1.11.1.
I am running OS X 10.10.5.

[memmap_error.py.zip](https://github.com/numpy/numpy/files/504729/memmap_error.py.zip)

**Comment by ahaldane** [comment]
This is fixed in 1.12 by #7406.

I'm going to close, thanks for the report.

(feel free to reopen if I'm wrong about that. I checked python2/numpy1.12 and your example works)
