### ISSUE TITLE
Documentation issue: np.histogram2D, non-functioning example for pcolormesh

### ISSUE THREAD

**Issue by phyzicist** [numpy/numpy#8115]
Hi all,

np.histogram2d online documentation gives an non-functioning example.

Documentation page:
http://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram2d.html

Non-functioning example:
```
pcolormesh can display exact bin edges:
>>> ax = fig.add_subplot(132)
>>> ax.set_title('pcolormesh: exact bin edges')
>>> X, Y = np.meshgrid(xedges, yedges)
>>> ax.pcolormesh(X, Y, H)
>>> ax.set_aspect('equal')
```

Problem with example:
numpy.histogram2d returns an array H shaped (nx, ny).
numpy.meshgrid returns X, Y arrays shaped (ny, nx).   [When called with the default Cartesian indexing]
Therefore, X,Y are incompatible with H for pcolormesh, which gives an error.

Proposed updated example (transpose H):
```
pcolormesh can display exact bin edges:
>>> ax = fig.add_subplot(132)
>>> ax.set_title('pcolormesh: exact bin edges')
>>> X, Y = np.meshgrid(xedges, yedges)
>>> ax.pcolormesh(X, Y, H.T)
>>> ax.set_aspect('equal')
```

**Comment by wrwrwr** [comment]
If following all the documentation steps, H gets redefined to a square matrix before the `pcolormesh` example, so here's a short bit to reproduce the problem:

```python
import matplotlib.pyplot as plt
import numpy as np

H, xedges, yedges = np.histogram2d([], [], bins=(2, 4))
X, Y = np.meshgrid(xedges, yedges)
plt.pcolormesh(X, Y, H)
```

(With X and Y of dimensions 5x3 and H 2x4.)

**Comment by phyzicist** [comment]
Yes, thanks for that update. I should have clarified that the example script technically works but is bad documentation (it only works because, by chance, nx=ny). The proposed fix is better documentation.
