### ISSUE TITLE
"python setup.py build" fails from downloaded tarball

### ISSUE THREAD

**Issue by aixtools** [numpy/numpy#8117]
What confuses me is that XXXX states that cython is not needed for distributed versions - and I am taking a tarball as a release.

So, maybe I need to figure out what needs to be done to install cython - but what I want to do is investigate why "pip install numpy" fails with:
    error: Command "xlc_r -I/opt/include -O3 -qmaxmem=-1 -qarch=pwr5 -q64 -I/opt/buildaix/includes -DNDEBUG -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.aix-5.3-2.7/numpy/core/src/private -Inumpy/core/include -Ibuild/src.aix-5.3-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray    -Inumpy/core/src/umath -Inumpy/core/src/npysort  -I/opt/include/python2.7 -Ibuild/src.aix-5.3-2.7/numpy/core/src/private -Ibuild/src.aix-5.3-2.7/numpy/core/src/private -Ibuild/src.aix-5.3-2.7/numpy/core/src/private -c numpy/core/src/private/mem_overlap.c -o build/temp.aix-5.3-2.7/numpy/core/src/private/mem_overlap.o" failed with exit status 1

Step 1 is to run a build outside of pip.

Once that is running - I may have several other issues.

So, issue is that tarball (gzipped) requires cython - while expectation is that it does not.

Question: is this something easy to resolve (at command line) or do I need to "pip install cython" or something equivalent?

**Comment by rgommers** [comment]
Hmm, that's not good. Cython should indeed not be needed, maybe something is missing in the tarball or there's an issue with a recent change in ``cythonize.py``.

**Comment by rgommers** [comment]
> Question: is this something easy to resolve (at command line) or do I need to "pip install cython" or something equivalent?

Not sure yet. ``pip install cython`` is pretty easy, so I'd go that way.

**Comment by rgommers** [comment]
Issue is that ``cythonize.dat`` (containing the hashes of the ``.c`` files corresponding to the ``.pyx`` files) is missing from the release tarballs.

**Comment by pv** [comment]
What tarball did you download? If the eg "v1.11.2.tar.gz" ones from 
Github, then those are automatic snapshots and not the release sources.

**Comment by rgommers** [comment]
No, that's not it - the ``PKG-INFO`` file is present so ``cythonize.py`` never gets called.

**Comment by pv** [comment]
I see --- cythonize.dat appears indeed missing in all recent releases.

**Comment by rgommers** [comment]
> I see --- cythonize.dat appears indeed missing in all recent releases.

No, my mistake - it's not needed. ``generate_cython`` isn't called in ``setup.py``

**Comment by aixtools** [comment]
a) : wget --no-check-certificate https://github.com/numpy/numpy/archive/v1.11.2.tar.gz

-- this is the link I found following this path:
http://www.numpy.org/ (Getting numpy)

http://www.scipy.org/scipylib/download.html (NumPy release page)
https://github.com/numpy/numpy/releases
https://github.com/numpy/numpy/archive/v1.11.2.tar.gz

As v1.11.2 is what pip installed downloaded - I thought it was the same.

Should I have followed to the "SourceForge" area?

b)
michael@x071:[/data/prj/python/numpy/numpy-1.11.2]python setup.py
Running from numpy source directory.
Cythonizing sources
Processing numpy/random/mtrand/mtrand.pyx
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Cython.Compiler.Main
Traceback (most recent call last):
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 199, in <module>
    main()
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 195, in main
    find_process_files(root_dir)
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 187, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 161, in process
    processor_function(fromfile, tofile)
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 81, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 386, in <module>
    setup_package()
  File "setup.py", line 369, in setup_package
    generate_cython()
  File "setup.py", line 207, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

System 2 - tried same thing...
root@x064:[/data/prj/python/numpy/numpy-1.11.2]python setup.py
Running from numpy source directory.
Cythonizing sources
Processing numpy/random/mtrand/mtrand.pyx
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Cython.Compiler.Main
Traceback (most recent call last):
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 199, in <module>
    main()
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 195, in main
    find_process_files(root_dir)
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 187, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 161, in process
    processor_function(fromfile, tofile)
  File "/data/prj/python/numpy/numpy-1.11.2/tools/cythonize.py", line 81, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 386, in <module>
    setup_package()
  File "setup.py", line 369, in setup_package
    generate_cython()
  File "setup.py", line 207, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

**Comment by rgommers** [comment]
> wget --no-check-certificate https://github.com/numpy/numpy/archive/v1.11.2.tar.gz

Yep that explains it, not an official release. Get it here instead: https://pypi.python.org/pypi/numpy

**Comment by rgommers** [comment]
SourceForge also has the right tarball right now, but we're getting rid of SourceForge for the next release (it's 2016.....). So ignore that.

**Comment by rgommers** [comment]
Thanks for the detailed links. http://www.scipy.org/scipylib/download.html has an issue, it should link to PyPI. I'll open a new issue for that on the scipy.org repo.

**Comment by aixtools** [comment]
Just some feedback - but the pip install I did this morning also "installs" cython - for itself I expect. As the messages I was getting (a lot of them!) were coming from the "cython" install needed for the numpy (pip install) to proceed.

Head of that "script" capture:
root@x064:[/]/opt/bin/pip install numpy
Collecting numpy
  Downloading numpy-1.11.2.tar.gz (4.2MB)
K25l 100%||################################|44.2MB247kB/seeta00:00:01
?25hInstalling collected packages: numpy
  Running setup.py install for numpy ... ?25lerror
    Complete output from command /opt/bin/python -u -c "import setuptools, tokenize;__fil
e__='/tmp/pip-build-i23Cv3/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(_
_file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-We1d
i_-record/install-record.txt    --single-version-externally-managed --compile:
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last Numpy release on PyPi)


    blas_opt_info:
    blas_mkl_info:
      libraries mkl_rt not found in ['/opt/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/opt/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/opt/lib', '/usr/lib']
      NOT AVAILABLE

All of these messages about BLAS - are something else I need to look into (as /usr/lib/libblas.a is there) - but I also think they are coming from the pseudo "cython build" that pip is doing before continuing with numpy. -- just a guess, FYI

**Comment by rgommers** [comment]
> Just some feedback - but the pip install I did this morning also "installs" cython - for itself I expect. 

that doesn't sound right, there's no ``build_requires`` or ``install_requires`` ``= 'cython'`` anywhere. I also don't see it in the log above.

> All of these messages about BLAS - are something else I need to look into (as /usr/lib/libblas.a is there) - but I also think they are coming from the pseudo "cython build" that pip is doing before continuing with numpy. -- just a guess, FYI

No those are from the numpy build. Numpy looks for all BLASes it supports, and reports on each one. So as long as a few lines lower it reports that it found one BLAS install, you're good.

**Comment by aixtools** [comment]
On 04-Oct-16 19:43, Ralf Gommers wrote:
>
>     Just some feedback - but the pip install I did this morning also
>     "installs" cython - for itself I expect.
>
> that doesn't sound right, there's no |build_requires| or 
> |install_requires| |= 'cython'| anywhere. I also don't see it in the 
> log above.
>
>     All of these messages about BLAS - are something else I need to
>     look into (as /usr/lib/libblas.a is there) - but I also think they
>     are coming from the pseudo "cython build" that pip is doing before
>     continuing with numpy. -- just a guess, FYI
>
> No those are from the numpy build. Numpy looks for all BLASes it 
> supports, and reports on each one. So as long as a few lines lower it 
> reports that it found one BLAS install, you're good.
>
Ok. I shall repeat the whole process, step-by-step, but tomorrow - maybe 
I was blinded by the flashing lights!

**Comment by aixtools** [comment]
must bow to my master - using the tar.gz that pip "fetched" did not create any errors.

In case anyone wants to use this on AIX - the process would be to installp (my package) of python at www.aixtools.net (not giving the complete URL without your okay), and then the following commands:

# export OBJECT_MODE=64
# export CFLAGS="-D_LARGE_FLAGS"
# pip install numpy

p.s. I have someone testing an AIX installp (i.e., pre-packaged) version. If this works - any interest from your side (means can be installed without a C compiler as it is already compiled).
