### ISSUE TITLE
No warning message if overflow encountered while subtracting a uint16 array and uint16 variable 

### ISSUE THREAD

**Issue by amilgeorge** [numpy/numpy#8119]
Subtracting two unsigned int variables throws RuntimeWarning. ("RuntimeWarning: overflow encountered in ushort_scalars"). But numpy proceeds silently without throwing a warning of one of the variables is an array

OS - 14.04.1-Ubuntu
numpy version - 1.11.1
python version - Python 2.7.6

## Example code:
import numpy as np

a = np.uint16(1)
a_array = np.ones(2,dtype=np.uint16);
b = np.uint16(3);

#### Comment:Runitme Warning in this case
print a-b

#### Comment: No Runtime warning in this case
print a_array - b

**Comment by charris** [comment]
Numpy considers overflow a feature :) It is modular arithmetic, just like in C.

**Comment by amilgeorge** [comment]
But why the difference in behaviour in case of array and non array variables?
