### ISSUE TITLE
loops.c fails to compile from generated source on Westmere

### ISSUE THREAD

**Issue by congma** [numpy/numpy#8128]
The generated source `numpy/core/src/umath/loops.c` fails to compile on a fairly old Linux machine with Westmere CPU (with no AVX/AVX2 instructions).  The assembly file generated from `loops.c` contains a large amount of illegal instructions.

It seems that either the recent `numpy` isn't compatible with older CPUs, or there is a bug in configuring the generated code.

I've tentatively bisected this to commit 37740eb8.

The full error output is too huge and here is the relevant beginning:

```
gcc: build/src.linux-x86_64-2.7/numpy/core/src/umath/loops.c                    
/tmp/cc9nF6h7.s: Assembler messages:                                            
/tmp/cc9nF6h7.s:43293: Error: suffix or operands invalid for `vpunpcklbw'       
/tmp/cc9nF6h7.s:43294: Error: suffix or operands invalid for `vpunpckhbw'       
/tmp/cc9nF6h7.s:43295: Error: suffix or operands invalid for `vpmullw'          
/tmp/cc9nF6h7.s:43296: Error: suffix or operands invalid for `vpshufb'          
/tmp/cc9nF6h7.s:43297: Error: suffix or operands invalid for `vpmullw'          
/tmp/cc9nF6h7.s:43298: Error: suffix or operands invalid for `vpshufb'          
/tmp/cc9nF6h7.s:43299: Error: suffix or operands invalid for `vpor'             
/tmp/cc9nF6h7.s:43301: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%
r8,%rdi)'
/tmp/cc9nF6h7.s:43535: Error: suffix or operands invalid for `vpmovsxbw'        
/tmp/cc9nF6h7.s:43536: Error: no such instruction: `vextracti128 $0x1,%ymm0,%xmm
0'
/tmp/cc9nF6h7.s:43537: Error: suffix or operands invalid for `vpmovsxwd'        
/tmp/cc9nF6h7.s:43538: Error: suffix or operands invalid for `vpmovsxbw'        
/tmp/cc9nF6h7.s:43539: Error: no such instruction: `vextracti128 $0x1,%ymm6,%xmm
0'
```

The compiler is GNU `gcc 5.2.0`.

CPU id:

```
vendor_id       : GenuineIntel
cpu family      : 6
model           : 47
model name      : Intel(R) Xeon(R) CPU E7- 4850  @ 2.00GHz
```

CPU flags:

```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2ap
```

**Comment by juliantaylor** [comment]
you probably have a new gcc with an ancient linker, whats `ld --version`?
which OS are you using?

**Comment by congma** [comment]
@juliantaylor you're right;  the OS and build environment are pretty ancient. `ld --version` shows `GNU ld version 2.20.51.0.2-5.34.el6 20100205`.  The OS is `Scientific Linux release 6.3 (Carbon)` according to `/etc/redhat-release`.

This is on a shared machine managed by admins who installed newer `gcc` versions from source.  Can we somehow build `numpy` with this, or do I have to do some sub-admin in my own `$HOME`, such as keeping local copies of `binutils` and others?

**Comment by juliantaylor** [comment]
you can build older versions, the use of AVX2 is only on git master right now, for example 1.11.2 should be good.
If you want to use master you have to undefine  HAVE_ATTRIBUTE_TARGET_AVX2 in `numpy/core/include/numpy/npy_common.h`
we'll have to add linker capability check for this configuration.

**Comment by congma** [comment]
Thanks!  I don't have to use master for now but I'm a bit concerned with building later releases.

Do I have to patch `numpy/core/include/numpy/npy_common.h`?  Can I undefine this macro by env. variables, say, `CC` or `CFLAGS`?

**Comment by juliantaylor** [comment]
this should do it

```patch
--- a/numpy/core/include/numpy/npy_common.h
+++ b/numpy/core/include/numpy/npy_common.h
@@ -34,6 +34,7 @@
 #else
 #define NPY_GCC_TARGET_AVX
 #endif
+#undef HAVE_ATTRIBUTE_TARGET_AVX2
 #ifdef HAVE_ATTRIBUTE_TARGET_AVX2
 #define NPY_GCC_TARGET_AVX2 __attribute__((target("avx2")))
 #else
```

**Comment by congma** [comment]
Thanks again!  But I meant to ask, can I do something like the following?
```bash
CFLAGS='-UHAVE_ATTRIBUTE_TARGET_AVX2' python setup.py build
```
Will setup.py pick up the environment variables and make `gcc` undefine the macro?

**Comment by congma** [comment]
Thanks.  I mean, I tried passing `CFLAGS='-UHAVE_ATTRIBUTE_TARGET_AVX2'` as an env. var. to `python setup.py build`, but build still fails.  Is patching `npy_common.h` the only way of doing it?

**Comment by juliantaylor** [comment]
that flag cannot undefine stuff in source files, it only works for commandline options
patching is currently the only way, but it will probably get fixed soon.

**Comment by juliantaylor** [comment]
this is how we could fix it, check if we can link avx2 assembly, we can't use the intrinsics as they need `-mavx2` set. Just needs a little extra logic to give the created macro a better name.

```patch
--- a/numpy/core/include/numpy/npy_common.h
+++ b/numpy/core/include/numpy/npy_common.h
@@ -34,7 +34,7 @@
 #else
 #define NPY_GCC_TARGET_AVX
 #endif
-#ifdef HAVE_ATTRIBUTE_TARGET_AVX2
+#if defined HAVE_ATTRIBUTE_TARGET_AVX2 && defined HAVE___ASM__
 #define NPY_GCC_TARGET_AVX2 __attribute__((target("avx2")))
 #else
 #define NPY_GCC_TARGET_AVX2
diff --git a/numpy/core/setup_common.py b/numpy/core/setup_common.py
index cc2047b..2dc8b75 100644
--- a/numpy/core/setup_common.py
+++ b/numpy/core/setup_common.py
@@ -131,6 +131,7 @@ OPTIONAL_INTRINSICS = [("__builtin_isnan", '5.'),
                         "xmmintrin.h"),  # SSE
                        ("_mm_load_pd", '(double*)0', "emmintrin.h"),  # SSE2
                        ("__builtin_prefetch", "(float*)0, 0, 3"),
+                       ("__asm__", '"vpand %ymm1, %ymm2, %ymm3"')
                        ]
 
 # function attributes
```

**Comment by congma** [comment]
@juliantaylor

Again, many thanks for the latest patch and the explanations.
