### ISSUE TITLE
master broken on OS X with Clang

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#8130]
looks like issue was introduced in gh-7980, and is hitting this Clang bug: https://llvm.org/bugs/show_bug.cgi?id=25510. Will have a look at finding a workaround.

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-4ee716103900> in <module>()
    ----> 1 import numpy as np

    /Users/rgommers/Code/numpy/numpy/__init__.py in <module>()
        140         return loader(*packages, **options)
        141 
    --> 142     from . import add_newdocs
        143     __all__ = ['add_newdocs',
        144                'ModuleDeprecationWarning',

    /Users/rgommers/Code/numpy/numpy/add_newdocs.py in <module>()
         11 from __future__ import division, absolute_import, print_function
         12 
    ---> 13 from numpy.lib import add_newdoc
         14 
         15 ###############################################################################

    /Users/rgommers/Code/numpy/numpy/lib/__init__.py in <module>()
          6 from numpy.version import version as __version__
          7 
    ----> 8 from .type_check import *
          9 from .index_tricks import *
         10 from .function_base import *

    /Users/rgommers/Code/numpy/numpy/lib/type_check.py in <module>()
          9            'common_type']
         10 
    ---> 11 import numpy.core.numeric as _nx
         12 from numpy.core.numeric import asarray, asanyarray, array, isnan, \
         13                 obj2sctype, zeros

    /Users/rgommers/Code/numpy/numpy/core/__init__.py in <module>()
         30 del os
         31 
    ---> 32 from . import umath
         33 from . import _internal  # for freeze programs
         34 from . import numerictypes as nt

    ImportError: dlopen(/Users/rgommers/Code/numpy/numpy/core/umath.cpython-35m-darwin.so, 2): Symbol not found: ___cpu_model
      Referenced from: /Users/rgommers/Code/numpy/numpy/core/umath.cpython-35m-darwin.so
      Expected in: flat namespace
     in /Users/rgommers/Code/numpy/numpy/core/umath.cpython-35m-darwin.so

Clang version: 

    $ clang -v
    Apple LLVM version 7.3.0 (clang-703.0.31)
    Target: x86_64-apple-darwin15.6.0

**Comment by rgommers** [comment]
https://github.com/numpy/numpy/blob/master/numpy/_build_utils/src/apple_sgemv_fix.c#L66 works around it (probably by accident, code is pre intro of ``__builtin_cpu_supports`` support in Clang) with a dynamic check.

**Comment by juliantaylor** [comment]
neat I didn't know clang even implemented that
too bad apple is shipping an incomplete implementation ...
should be fixable by doing a link test but this will likely break enough code that apple will fix it themselves

**Comment by rgommers** [comment]
``__builtin_cpu_supports`` also broken for GCC 5.3 it looks like: https://github.com/Blosc/c-blosc/blob/master/blosc/shuffle.c#L76

**Comment by rgommers** [comment]
> should be fixable by doing a link test but this will likely break enough code that apple will fix it themselves

it's already fixed in trunk of Clang. but the broken compiler version is the default one on OS X 10.11, so that won't go away any time soon.

**Comment by juliantaylor** [comment]
apple updates their compiler more often than their OS, so it might
but a fix would still be good, I'll have a look

**Comment by juliantaylor** [comment]
actually it already is linking it. The problem is intrinsics are optimized away even at O0
this should fix that, can you try it on the mac? It works with linux clang-3.9 but that does not have the problem.

```patch
--- a/numpy/core/setup_common.py
+++ b/numpy/core/setup_common.py
@@ -125,7 +125,7 @@ OPTIONAL_INTRINSICS = [("__builtin_isnan", '5.'),
                        ("__builtin_bswap64", '5u'),
                        ("__builtin_expect", '5, 0'),
                        ("__builtin_mul_overflow", '5, 5, (int*)5'),
-                       ("__builtin_cpu_supports", '"sse"'),
+                       ("volatile int r = __builtin_cpu_supports", '"sse"'),
                        ("_mm_load_ps", '(float*)0', "xmmintrin.h"),  # SSE
                        ("_mm_prefetch", '(float*)0, _MM_HINT_NTA',
                         "xmmintrin.h"),  # SSE
 ```

**Comment by rgommers** [comment]
yep, that does fix it, thanks

**Comment by jakirkham** [comment]
What version of `clang` did you test against, @rgommers ?

**Comment by rgommers** [comment]
$ clang --version
    Apple LLVM version 7.3.0 (clang-703.0.31)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
