### ISSUE TITLE
einsum documentation addition

### ISSUE THREAD

**Issue by mattharrigan** [numpy/numpy#8138]
I really like einsum, very powerful, fast, flexible, and easy to read once you get the hang of it.  After reading the docs, I didn't know that you could leave subscripts empty for a scalar.  Specifically, np.einsum(',ij', 3, c) is equivalent to np.einsum('..., ...', 3, c), which I thought was pretty neat and not otherwise obvious in the docs.  Perhaps add that to the docs.  Thank you

**Comment by shoyer** [comment]
A pull request to improve the docs would certainly be welcome. You can find the docstring in this file:
https://github.com/numpy/numpy/blob/86c780d1c60473b594db7a241419167ebc3df687/numpy/core/einsumfunc.py#L703
