### ISSUE TITLE
numpy.arange(0,0,0) raises ZeroDivisionError

### ISSUE THREAD

**Issue by glopesdev** [numpy/numpy#8143]
`numpy.arange(0)` sends out an empty array, as expected, but surprisingly `numpy.arange(0,0,0)` raises a `ZeroDivisionError`. Shouldn't it also return an empty array for consistency?

**Comment by mhvk** [comment]
The problem is the step of `0` (i.e., the last number): the number of elements becomes `0/0`. It seems it is appropriate to raise an exception in that case, since almost certainly there is a real underlying error.

p.s. Note that `np.linspace(0,0,0)` does return an empty array, as expected.

**Comment by glopesdev** [comment]
That makes sense, `np.linspace` is exactly what I needed. Thanks!
