### ISSUE TITLE
numpy.var computes the wrong sample variance

### ISSUE THREAD

**Issue by franciscogodoy** [numpy/numpy#8144]
numpy.var computes the sample variance by doing sum(x_i - E(x)) / n where n is the number of samples in the vector, E(x) the mean of x and the sum is over all the samples. For sample variance the correct formula is  sum(x_i - E(x)) / (n-1). The current formula is a biased estimator of the sample variance

**Comment by seberg** [comment]
Yes, indeed. Which is not wrong and mentioned in the documentation as well as changeable.  If you would want to change the default you would have to go through an ugly deprecation, so I am not sure you can convince people for it, but please start on the mailing list.

**Comment by seberg** [comment]
Of course we (or you even) could see if the documentaiton could be more clear though.
