### ISSUE TITLE
ENH: `take` argument `keepdim`

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#8150]
Would be really nice in some circumstances to have a `keepdim` argument with `take`. This would allow one to potentially preserve a dimension they have indexed into.

**Comment by shoyer** [comment]
Can't you just index with a vector instead of a scalar? e.g., `a.take([index], axis)` instead of `a.take(index, axis)`?

**Comment by charris** [comment]
@jakirkham Does that work for you?

**Comment by seberg** [comment]
Closing this on a whim, I am not sure how take benefits of `keepdim` (or even how to implement it) given that the shape of the index array is inserted at the axis position:  The described workaround seems good to me.
