### ISSUE TITLE
__matmul__ does not raise ``NotImplemented`` if it should

### ISSUE THREAD

**Issue by mcocdawc** [numpy/numpy#8155]
I have a custom class for which I want to implement the possibility of using the matrix multiplication ``@`` operator.

In my class the ``__rmatmul__`` method is defined and if I have e.g. an instance ``molecule`` the following works:

    molecule.__rmatmul__( np.diag([1, 1, -1]))

But the following returns a ``ValueError``:

    np.diag([1, 1, -1]) @ molecule

Further testing it (thanks to Martijn Pieters (http://stackoverflow.com/questions/40044182/rmatmul-not-working-as-expected?noredirect=1#comment67364565_40044182)) I ran:

     np.diag([1, 1, -1]).__matmul__(molecule)

This raises a ``ValueError`` and not a ``NotImplemented``, as it should. (As far as I understand it of course).

In order to further investigate it, I wrote this minimal example:

    class minimal:
         def __rmatmul__(self, other):
             return 1
    
         def __rmul__(self, other):
             return 2

    test = minimal()

    1 * test

returns 2 as expected.

    np.zeros([3,3]) @ test

returns now a ``TypeError``. 

Technical details:
I used the default installation from anaconda:
Python 3.5.2 :: Anaconda custom (64-bit)
Numpy version: 1.11.2-py35_0
OS is: Ubuntu 16.04 LTS

**Comment by pv** [comment]
This is not specific to rmatmul, it's the same for any r-op. Consider 
`np.zeros([3,3]) * test`. You use `__array_priority__` to override.
.
This is intended behavior, so not a bug although it is confusing.

**Comment by mcocdawc** [comment]
I just found this [post](http://stackoverflow.com/questions/38229953/array-and-rmul-operator-in-python-numpy) greatly explaining it for ``__rmul__``. Sorry for not seeing it before.
The tip with ``__array_priority__`` is great and solves my problem. Thank you very much.
May I ask what the allowed values for ``__array_priority__`` are?
Is it just a positive (64bit) floating number.

**Comment by pv** [comment]
It's a float, see
 >>> print np.array([1]).__array_priority__
0.0
 >>> print np.matrix([1]).__array_priority__
10.0
 >>> print np.ma.array([1]).__array_priority__
15
 >>> scipy.sparse.csr_matrix([1]).__array_priority__
10.1

**Comment by mcocdawc** [comment]
Thank you very much
