### ISSUE TITLE
Json Deserialize - Mismatching array shape

### ISSUE THREAD

**Issue by adailsonfilho** [numpy/numpy#8162]
Hi guys!

### Context
I think i'm doing something wrong, but I could not understand what. I'm reading this [json](https://gist.github.com/adailsonfilho/7a894397073f63a3d57199cc50d07fd0) and I want to put the fields "data" and "fitness" into numpy array formats.

In resume, this is a Genetic Algoritm Log, the "data" field has a shape (23, 40, 8): 23 Epochs, 40 individuals in each epoch, 8 dimensions each individual.

### The problem

_[considering that `jsondata` is the json alerady deserialized]_
```python
data = np.array(jsondata['data'])
len(data) # returns 23
len(data[0]) # returns 40
len(data[0][0]) # returns 8
data.shape #returns (23,)
```
And i can not reshape because `data.size` returns 23. As far as I could understand my numpy array object has 23 (epochs) objects there are lists, each one with 40 lists (individuals), wich in turn has 8 elements. How could I get the `data.shape` returning the actual shape of the json data? This is a bug?

My setup:
- Windows 10
- Python 3,5, from Miniconda3
- Numpy 1.11.2 installed via conda

**Comment by njsmith** [comment]
What do you get if you do

```python
type(jsondata['data'])
type(jsondata['data'][0])
type(jsondata['data'][0][0])
type(jsondata['data'][0][0][0])
```

?

**Comment by adailsonfilho** [comment]
I get this:

```
<class 'list'>
<class 'list'>
<class 'list'>
<class 'int'>
```

**Comment by njsmith** [comment]
Then my best guess is that not all of your lists are the same length. E.g. try `[len(l) for l in jsondata['data']]`, and check if they're all 40, or `[len(l2) for l2 in l1 for l1 in jsondata['data']]` and check if they're all 8?

**Comment by adailsonfilho** [comment]
Huuum, I you are right, I've changed recently my code for building the the data field. Only the fist epoch is comming with 40 lenght, the others are comming 20. Thank you so much!
