### ISSUE TITLE
issue with site-packages/numpy/distutils/ccompiler.py - enhancement

### ISSUE THREAD

**Issue by aixtools** [numpy/numpy#8163]
File "/opt/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 516, in CCompiler_cxx_compiler
    cxx.compiler_so = [cxx.compiler_cxx[0]] + cxx.compiler_so[1:]

The root cause is not numpy (imho). I am posting this incase others may run into an issue like this.

The resolution (in my case with xlc and xlC) is:
Add
 'CXX': 'xlC_r',
to
$prefix/lib/python2.7/.sysconfigdata.py

As an enhancement, numpy might handle this more graciously with an error message to report on CXX equals '' (zero length string).

**Comment by rgommers** [comment]
This isn't relevant anymore I believe, so I'll close it. Thanks for the report and workaround @aixtools
