### ISSUE TITLE
Different answers for mean across columns vs. selecting a column and then computing the mean

### ISSUE THREAD

**Issue by nirum** [numpy/numpy#8170]
Let's say I have a 2d array of type float32, and I want to compute the mean of the first column:
```python
np.random.seed(1234)
X = (np.random.rand(5000000, 2) * 100).astype(np.float32)

# first method
mu1 = X.mean(axis=0)[0]

# second method
mu2 = X[:, 0].mean()

# absolute error
print('Abs. error:', np.abs(mu1 - mu2))
```

These two methods give me different answers (absolute error of around 0.05 depending on the seed, for example if I set the seed to 1234 the absolute error is 0.0572586)

Shouldn't these methods give the same result?

I'm using numpy version 1.11.2

**Comment by seberg** [comment]
That is to be expected, check for example gh-8116, float32 is probably not a good type for such large sums in any case.

**Comment by seberg** [comment]
You will have "better then expected" precision in the second method though, which I suppose may be surprising, but then the logic is: provide the best answer you can when possible, its just not really possible for the other case.

**Comment by nirum** [comment]
Makes sense, thanks for the reference to the other issue!
