### ISSUE TITLE
a potential bug in numpy multivariate_normal 

### ISSUE THREAD

**Issue by 1a1a11a** [numpy/numpy#8185]
See here: http://stackoverflow.com/questions/40100340/numpy-multivariate-normal-bug-when-dimension-too-high. 

Here is the test code: 
    p = 5000 
    cov_true  = np.eye(p)
    mean_true = np.zeros(p)
    beta_true = multivariate_normal(mean_true, cov_true, size=1).T

Firstly, the last line takes great amount of time, second it doesn't make too much difference when I run it on 48 core machine and 4 core machine while it eats all cores(48 and 4 in each case). I guess it might be a bug?

**Comment by 1a1a11a** [comment]
testing environment, python3.4, python3.5, python2.7 with numpy 1.11.0.

**Comment by pv** [comment]
The multicore issue is very likely due to the BLAS/LAPACK library you 
are using, so most likely openblas bug.

**Comment by 1a1a11a** [comment]
can I upgrade Openblas?

**Comment by juliantaylor** [comment]
probably the actual work to do per threads is to small with dimensions of 5000 and 48 cores, so openblas is just burning cpu cycles running `sched_yield` in all threads, that is a function you should never be using on linux but unfortunately openblas does.
Thats why you get no speedup with more cores, you are probably lucky that it does not get slower
There  isn't really much numpy can do about this.

**Comment by seberg** [comment]
The openblas issue (where this belongs anyway) is closed, so closing this one as well.
