### ISSUE TITLE
Structured arrays containing NaNs are not considered equal by numpy.testing.assert_array_equal()

### ISSUE THREAD

**Issue by colinpalmer** [numpy/numpy#8192]
numpy.testing.assert_array_equal is supposed to accept NaN values as equal. This seems to work fine for normal arrays but not for arrays with structured dtypes:

```
>>> import numpy as np
>>> a = np.array((np.nan,), dtype=[('f', 'f4')])
>>> b = a.copy()
>>> np.testing.assert_array_equal(a, b)
Traceback (most recent call last):
  ...
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array((nan,), 
      dtype=[('f', '<f4')])
 y: array((nan,), 
      dtype=[('f', '<f4')])
```

The result from assert_equal is identical. Tested using numpy 1.11.2 on python 2.7.12 and 3.5.2.

**Comment by charris** [comment]
Hmm, doesn't work for `assert_allclose` either.

**Comment by shoyer** [comment]
Note that `np.isnan` gives a `TypeError` on structured arrays: `TypeError: ufunc 'isnan' not supported for the input types...`. That might be related to the ultimate cause here.

**Comment by eric-wieser** [comment]
Related to #9023

**Comment by charris** [comment]
Pushing this off, it should get fixed when #8157 goes in.

**Comment by sethtroisi** [comment]
This is s still broken in 1.16.4

Doesn't seem to have been fixed by #8157

```
import numpy as np

a = np.array((np.nan,), dtype=[('f', 'f4')])
b = a.copy()

np.testing.assert_array_equal(a, b)
```
```
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    np.testing.assert_array_equal(a, b)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 904, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatch: 100%
 x: array((nan,), dtype=[('f', '<f4')])
 y: array((nan,), dtype=[('f', '<f4')])

shell returned 1

Press ENTER or type command to continue
```

**Comment by seberg** [comment]
We would have to define a new `equivalent` ufunc or so to do this correctly (i.e. combine isnan and equality check into one function). Then you could define this function also for structured dtypes. As Eric pointed out, the same issue exists for object dtypes.

**Comment by seberg** [comment]
Same as gh-21539, closing this one.
