### ISSUE TITLE
Squeeze incorrect with list inputs and axis argument

### ISSUE THREAD

**Issue by jluttine** [numpy/numpy#8201]
If I give an array to squeeze, it handles `axis` argument correctly:

```
>>> np.squeeze(np.array([[[42]]]), axis=(1,)).shape
(1, 1)
```

However, if the input is a list, it works differently:

```
>>> np.squeeze([[[42]]], axis=(1,)).shape
()
```

I was expecting the results to be the same.

**Comment by eric-wieser** [comment]
Good spot - the `axis` parameter seems to have been forgotten [here](https://github.com/numpy/numpy/blob/v1.11.0/numpy/core/fromnumeric.py#L1198)

**Comment by sethtroisi** [comment]
This can be closed, it was fixed by https://github.com/numpy/numpy/pull/12873

**Comment by jluttine** [comment]
Yes, I can confirm this is fixed in recent version(s). Thanks.
