### ISSUE TITLE
linalg.det throws LinAlgError for 0-by-0 matrices

### ISSUE THREAD

**Issue by mwallerb** [numpy/numpy#8212]
Since LAPACK functions cannot handle 0-by-0 matrices, numpy must explicitly handle those cases.  However, while in newer versions of numpy, the inverse is computed correctly, the determinant raises `LinAlgError`:

```
>>> A = numpy.empty((0, 0))
>>> numpy.linalg.inv(A)
array([], shape=(0, 0), dtype=float64)
>>> numpy.linalg.det(A)
LinAlgError: Arrays cannot be empty
```

Since the determinant of a zero-by-zero matrix is well-defined, a LinAlgError is IMHO wrong, since it indicates a numerics problem rather than the purely technical fact that the backend cannot handle this.

Thus, expected result:

```
>>> numpy.linalg.det(A)
1.0
```

Numpy version: 1.11.0 (also present in git master)
Python version: 2.7.12

**Comment by mhassell** [comment]
Hi! I'll take a look and see what I can do to fix this.  But just a heads up, this is my first time fixing a bug in numpy, so I might not be super quick.

**Comment by mhassell** [comment]
Okay, so here's the rub.  Because of the ability to compute determinants of a stack of arrays:

    >>> a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
    >>> a.shape
    (3, 2, 2)
    >>> np.linalg.det(a)
    array([-2., -3., -8.])

Now, my thought is to do the following: 

Loop over a and flag any arrays in the stack that are empty.   

Keep track of the indices where there are empty arrays for later.  
Delete the empty arrays, pass the nonempty arrays to _umath_linalg.det, read back the determinants, and then fill in the missing locations with ones where there were empty matrices.

Does this seem like it will address the issue?

**Comment by pv** [comment]
All "stacked" arrays are always of the same shape, which can be
determined from the overall shape so no loops needed.

**Comment by mhassell** [comment]
Hm, so if one member of a stacked array is empty, they are then all empty?  This doesn't seem to be explicitly forbidden by numpy:

    >>> a = np.array( [ [[1, 2], [3,4]], [[]], [[]] ])
    >>> a.shape
    (3,)

**Comment by eric-wieser** [comment]
@mhassell: That's a `dtype=object, ndim=1` array though, which `np.linalg.det` (rightly) rejects

**Comment by mwallerb** [comment]
@mhassell I think you may draw some inspiration from the code of `linalg.inv`, since it handles 0-by-0 just fine.

**Comment by mhassell** [comment]
Sure, I'll check it out and try to fix this. Thanks for the pointer.

**Comment by Don86** [comment]
Hi, I'd like to know if this is still being worked on? I'd like to try my hand at it otherwise.

**Comment by mhassell** [comment]
Hi Don86, I've gotten a bit swamped with other stuff, so please do have a go at it.

**Comment by eric-wieser** [comment]
I've got this one, but I think there are a tonne more cases in `linalg` that ought to work for 0d

**Comment by ashwinpathak20** [comment]
I would like to work on this one, @eric-wieser can you point out some of the cases that you were talking about in the previous comment?

**Comment by eric-wieser** [comment]
@ashwinpathak20: This is already well in process (#8368), but has opened a can of worms:

 * #8369 - the tests weren't testing this type of array properly
 * #8376 - the current version of lapack bundled with numpy is very out of date, and buggy
 * #8381 - the tools for rebundling lapack were also broken
 *
