### ISSUE TITLE
atleast_2d documentation

### ISSUE THREAD

**Issue by mattharrigan** [numpy/numpy#8214]
The doc for [atleast_2d](https://github.com/numpy/numpy/blob/v1.11.0/numpy/core/shape_base.py#L24) says it returns "An array, or tuple of arrays", but actually returns an array or list of arrays.  atleast_1d says it returns "An array, or sequence of arrays".  I think a list is a sequence but I'm not 100% sure.  Not sure if atleast_2d doc should say a list or sequence, but it shouldn't say a tuple.  atleast_3d has a similar issue.

**Comment by shoyer** [comment]
Both tuples and lists are sequences. In practice, I doubt anyone is relying on this but "list" is certainly more precise, so we should probably update the docs.
