### ISSUE TITLE
How to get numpy.core._dotblas.dot?

### ISSUE THREAD

**Issue by EGQM** [numpy/numpy#8225]
compiled the latest numpy with openblas,I find there is not numpy.core._dotblas.dot.
How can I get numpy.core._dotblas.dot?
should I compile numpy with openblas and **BLAS**?

**Comment by pv** [comment]
dotblas no longer exists, blas interfacing is handled differently

**Comment by EGQM** [comment]
Thank you @pv!
I find the line:
The _dotblas module has been removed. CBLAS Support is now in Multiarray.
