### ISSUE TITLE
Warning during test suite

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#8232]
Not sure if this warning is meaningful or not. However, I thought I would mention it as I don't recall seeing this before.

```
clang: warning: -Wl,-rpath=<PATH>/libbar.so: 'linker' input unused
```

**Comment by rgommers** [comment]
A search for the exact phrase ``libbar.so: 'linker' input unused`` gives me only one hit, which is also a numpy issue (gh-6718). That's a year old so this isn't urgent, but I guess something does need fixing.

**Comment by WarrenWeckesser** [comment]
Is this still warning still occurring?

**Comment by jakirkham** [comment]
Unclear. Somewhere `-Wno-unused-result` is being passing to compiler (not sure if it is conda-forge or NumPy itself), which would likely silence this warning. IOW the underlying issue may not be fixed, but suppressed

**Comment by jakirkham** [comment]
Unclear. So much has changed over the past 5yrs it could have been fixed. We can close if you like

**Comment by seberg** [comment]
Lets close it then, and just open a new issue it shows up again.  5 years really is a long time ago for such an issue.
