### ISSUE TITLE
Long runtime in numpy.exp()

### ISSUE THREAD

**Issue by martin-hahn** [numpy/numpy#8233]
The runtime of the exponential is extremely slow compared to other floating point values:

`import numpy as np`
 `x = np.repeat(-8.3266726846886721e-16, 1e5)`
 `np.exp(x)` 
 `x = np.repeat(-2.7755575615628909e-16, 1e5)`
 `np.exp(x)`

The used numpy version is 1.11.0

**Comment by charris** [comment]
What floating point values and where is the timing?

**Comment by martin-hahn** [comment]
In [1]: import numpy as np
   ...: x = np.repeat(-8.3266726846886721e-16, 1e5)
   ...:

In [2]: %timeit np.exp(x)
1 loop, best of 3: 8.51 s per loop

In [3]: x = np.repeat(-2.7755575615628909e-16, 1e5)

In [4]: %timeit np.exp(x)
1 loop, best of 3: 8.52 s per loop

In [5]: x = np.repeat(-2.77555e-16, 1e5)

In [6]: %timeit np.exp(x)
10 loops, best of 3: 85 ms per loop

**Comment by MSeifert04** [comment]
That's just guessing but if the dtype of your `x` does not differ (which may cause different runtimes) then this may be a problem of your C-`math`-library. I suspect `numpy` just vectorizes your `math.h`, `exp` function on your array.

**Comment by matthew-brett** [comment]
Strange - on my laptop, I get:

```
In [1]: import numpy as np

In [2]: x = np.repeat(-8.3266726846886721e-16, 1e5)

In [3]: timeit np.exp(x)
1000 loops, best of 3: 466 µs per loop

In [4]: x = np.repeat(-2.7755575615628909e-16, 1e5)

In [5]: timeit np.exp(x)
1000 loops, best of 3: 467 µs per loop

In [6]: x = np.repeat(-2.77555e-16, 1e5)

In [7]: timeit np.exp(x)
1000 loops, best of 3: 506 µs per loop

In [8]: np.__version__
Out[8]: '1.11.0'
```

What system are you on?   (`uname -a`). What do you get for `np.show_config()`?

**Comment by martin-hahn** [comment]
(venv) vagrant@wheezy-test:/code/mor-model$ uname -a
Linux wheezy-test 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux

**Comment by martin-hahn** [comment]
In [2]: np.show_config()
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
    libraries = ['lapack', 'ptf77blas', 'ptcblas', 'atlas', 'ptf77blas', 'ptcblas']
    library_dirs = ['/usr/lib/atlas-base/atlas', '/usr/lib/atlas-base']
    define_macros = [('NO_ATLAS_INFO', -1)]
    language = f77
    include_dirs = ['/usr/include/atlas']
blas_opt_info:
    libraries = ['ptf77blas', 'ptcblas', 'atlas', 'ptf77blas', 'ptcblas']
    library_dirs = ['/usr/lib/atlas-base']
    define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
    language = c
    include_dirs = ['/usr/include/atlas']
openblas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
    libraries = ['ptf77blas', 'ptcblas', 'atlas', 'ptf77blas', 'ptcblas']
    library_dirs = ['/usr/lib/atlas-base']
    define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
    language = c
    include_dirs = ['/usr/include/atlas']
lapack_opt_info:
    libraries = ['lapack', 'ptf77blas', 'ptcblas', 'atlas', 'ptf77blas', 'ptcblas']
    library_dirs = ['/usr/lib/atlas-base/atlas', '/usr/lib/atlas-base']
    define_macros = [('NO_ATLAS_INFO', -1)]
    language = f77
    include_dirs = ['/usr/include/atlas']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE

**Comment by charris** [comment]
Strange indeed.  Fedora 24, NumPy `1.12.0.dev0+a9fb0d4`.
```
In [32]: x = np.repeat(-8.3266726846886721e-16, 1e5)

In [33]: timeit exp(x)
1 loops, best of 3: 951 ms per loop

In [34]: x = np.repeat(-8.32667e-16, 1e5)

In [35]: timeit exp(x)
10 loops, best of 3: 43.7 ms per loop
```
Where does -8.3266726846886721e-16 come from? Anything special about it?

**Comment by MSeifert04** [comment]
Windows 10 (mkl)

```
import numpy as np

x = np.repeat(-2.77555e-16, 1e5)
%timeit np.exp(x)

x = np.repeat(-2.7755575615628909e-16, 1e5)
%timeit np.exp(x)

x = np.repeat(-8.3266726846886721e-16, 1e5)
%timeit np.exp(x)
```

=>

```
1000 loops, best of 3: 1.07 ms per loop
1000 loops, best of 3: 1.07 ms per loop
1000 loops, best of 3: 1.07 ms per loop
```

**Comment by matthew-brett** [comment]
In a minimal Ubuntu 16.04 docker container:

```
apt-get update
apt-get install -y python wget
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py 
pip install numpy ipython
ipython
```

```
In [1]: import numpy as np

In [2]: x = np.repeat(-8.3266726846886721e-16, 1e5)

In [3]: timeit np.exp(x)
1 loop, best of 3: 1.08 s per loop

In [4]: x = np.repeat(-2.7755575615628909e-16, 1e5)

In [5]: timeit np.exp(x)
1 loop, best of 3: 1.05 s per loop

In [6]: x = np.repeat(-2.77555e-16, 1e5)

In [7]: timeit np.exp(x)
10 loops, best of 3: 50.6 ms per loop
```

**Comment by charris** [comment]
There is something seriously wrong with the exponential function for negative values
```
In [64]: x = array([-8.32667268468e-16] * 10 ** 5)

In [65]: timeit exp(x)
1 loops, best of 3: 949 ms per loop

In [66]: x = array([+8.32667268468e-16] * 10 ** 5)

In [67]: timeit exp(x)
1000 loops, best of 3: 1.51 ms per loop
```

**Comment by person142** [comment]
This is possibly an instance of the table maker's dilemma--i.e. the routine for `exp` tries a quick and dirty computation and has a slower fallback routine if there's too much rounding error. From the binary representations it seems possible:
```python
In [9]: bin(np.array([-2.77555e-16], dtype=np.float64).view(np.uint64)[0])
Out[9]: '0b1011110010110011111111111111110001101101110111001111011010100011'

In [10]: bin(np.array([-2.7755575615628909e-16], dtype=np.float64).view(np.uint64)[0])
Out[10]: '0b1011110010110011111111111111111111111111111111111111111111111111'

In [11]: bin(np.array([-8.3266726846886721e-16], dtype=np.float64).view(np.uint64)[0])
Out[11]: '0b1011110011001101111111111111111111111111111111111111111111111110'
```

What version of glibc is being used? Can check the source to see if this is a possibility.

**Comment by charris** [comment]
I'd guess it has something to do with using an alternating Taylor's series for small negative values.

**Comment by charris** [comment]
I have glibc 2.23 here.

**Comment by martin-hahn** [comment]
the other slow value i found was -2.7755575615628909e-16 (see example above)

**Comment by juliantaylor** [comment]
this is not surprising, this number is small enough that the math library needs to fall back to multiprecision math to give a result compliant with the C standard.

**Comment by person142** [comment]
@juliantaylor beat me too it, but here's the relevant stuff from the source.

In glibc 2.23, the source for the `exp` routine says:

```c
/***************************************************************************/
/*  MODULE_NAME:uexp.c                                                     */
/*                                                                         */
/*  FUNCTION:uexp                                                          */
/*           exp1                                                          */
/*                                                                         */
/* FILES NEEDED:dla.h endian.h mpa.h mydefs.h uexp.h                       */
/*              mpa.c mpexp.x slowexp.c                                    */
/*                                                                         */
/* An ultimate exp routine. Given an IEEE double machine number x          */
/* it computes the correctly rounded (to nearest) value of e^x             */
/* Assumption: Machine arithmetic operations are performed in              */
/* round to nearest mode of IEEE 754 standard.                             */
/*                                                                         */
/***************************************************************************/
```
The important thing is the "correctly rounded" bit--i.e. we indeed have to overcome the table maker's dilemma (by having slow fallback routines). And indeed in the source there are several points where it bails out with
```c
else return __slowexp(x); /*if error is over bound */
```
The `slowexp` function says:
```
/**************************************************************************/
/*  MODULE_NAME:slowexp.c                                                 */
/*                                                                        */
/*  FUNCTION:slowexp                                                      */
/*                                                                        */
/*  FILES NEEDED:mpa.h                                                    */
/*               mpa.c mpexp.c                                            */
/*                                                                        */
/*Converting from double precision to Multi-precision and calculating     */
/* e^x                                                                    */
/**************************************************************************/
```

**Comment by juliantaylor** [comment]
fwiw glibc has systemtap tracepoints when it goes into its multiprecision math:
http://www.gnu.org/software/libc/manual/html_mono/libc.html#Mathematical-Function-Probes

you can use these to figure it if this might be slowing your applications down in practice.

**Comment by charris** [comment]
I don't think exp is one of the functions for which correct rounding is required, and it is known to be difficult.

**Comment by WarrenWeckesser** [comment]
The conclusion of the discussion in 2016 seemed to be that this was a glibc issue.  That's not something numpy can fix. I'm closing the issue, but if my understanding of the "actionability" of this issue is wrong, please reopen the issue.
