### ISSUE TITLE
numpy exits instead of catches on atlas error

### ISSUE THREAD

**Issue by TimMurnaghan** [numpy/numpy#8252]
Python 2.7.12 on Windows 7

Newly upgraded to numpy 1.11.2

Following program just prints:
 ** On entry to DLASCL parameter number  4 had an illegal value
instead of letting the error be caught.

There are some old bugs about atlas linking that mention similar problems - so it looks like a re-occurence?

--------------------------------------------------------------
```
import numpy as np
try :
    np.linalg.lstsq([[np.nan]]*2, [1]*2)
except:
    print("caught")

print("carry on")
```

**Comment by rgommers** [comment]
You pass ``nan`` into ``lstsq`` and get back ``(array([ nan]), array([ nan]), 1, array([ nan]))`` (right?). I think that's simply expected. If you would have liked an exception for the nan, use ``scipy.linalg.lstsq`` instead.

**Comment by pv** [comment]
AFAIK on windows the XERBLA override has never worked, depending on the 
compiler configuration, so you get the default abort-process behavior.

**Comment by rgommers** [comment]
Ah, that rings a bell. Can't find an open issue for that, so leaving this one open then.

**Comment by TimMurnaghan** [comment]
@pv The snippet prints "carry on"  on version 1.10 - so even if we can't catch then not exiting would be a help.

**Comment by charris** [comment]
I don't think we can fix this, it usually depends on compiler and, IIRC, perhaps the flags ATLAS is compiled with. @TimMurnaghan The exiting behavior is in the compiled library, not NumPy. I think MKL might work on windows.

**Comment by TimMurnaghan** [comment]
@charris 
Your answer seems to suggest that ATLAS is outside numpy - but it's bundled in the wheel file on pypi.
Can you get whoever builds the wheel file to bundle an MKL build - or something with less unfriendly build flags then (like whatever 1.10 had) ? 

While I know that windows support is hard for some of the developers - I do think that being cross-platform is a huge selling point - and if you're going to be cross-platform then you do have to own some of these nasty end-to-end problems.

**Comment by pv** [comment]
MKL is not possible currently (the license requires the distributor to
shoulder legal risks, which perhaps acceptable for a company, are too
much for a private person to take on pro bono).

**Comment by TimMurnaghan** [comment]
@pv Sure, like I say, I recognize that the windows build environment isn't easy to work with - so the answer probably isn't MKL (maybe that should be a FAQ so that @charris wouldn't have suggested it).
Can we ask the question of whoever it is that builds the Atlas .dll that goes into the wheel file - of what did they did for v 1.10 and what changed for this version?

**Comment by pv** [comment]
If you have the time and expertise to sort it out yourself, the wheel building infrastructure is here: https://github.com/MacPython/numpy-wheels https://github.com/numpy/windows-wheel-builder

**Comment by charris** [comment]
Might see if @matthew-brett has any ideas.

**Comment by seberg** [comment]
As far as I understand the issue, this is about windows wheels shipping ATLAS behaving badly (since only the build binary matters/would have an influence).

We don't ship such wheels for many years anymore, so closing.
