### ISSUE TITLE
 Memory gets full when trying to add two different shape numpy array

### ISSUE THREAD

**Issue by taoyizhi68** [numpy/numpy#8254]
I accidently added a (1000, 1000, 1) numpy array  with an (1000, 1000) array, then memoy got full suddenly, and the pc was completely dead, I can only restart it forcely.

**Comment by pv** [comment]
That creates a (1000, 1000, 1000) array. That the machine freezes when 
trying to allocate lots of memory is a problem of the operating system, 
Numpy can't help here.

**Comment by taoyizhi68** [comment]
@pv Got it, thanks for the help.

**Comment by pv** [comment]
If you're on linux, using `ulimit -v` to set a safe bound for memory 
usage is one solution.

**Comment by juliantaylor** [comment]
limiting virtual memory is often not really what you want, you want to limit resident memory. But linux does not enforce the ulimit resident memory limits.
On linux you are better of using cgroups for this. They are also a lot more flexible.
