### ISSUE TITLE
Singleton arrays convert to numeric type 

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#8262]
Ran into a surprising case recently. Would have expected this to be illegal. Especially as this would be illegal with a `list`. However, it appears one can convert a singleton array (of arbitrary dimensionality) to a simple numeric type. Please see the code snippet below.

```python
In [1]: import numpy

In [2]: int([1])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-7c9c44330c2c> in <module>()
----> 1 int([1])

TypeError: int() argument must be a string or a number, not 'list'

In [3]: int(numpy.array([1]))
Out[3]: 1
```

While shown with `int`s and 1-D singleton array, this seems to work with other types and dimensions.

**Comment by pv** [comment]
I think this is widely relied on, and no semantic changes are possible.

**Comment by mattip** [comment]
Closing, this is a request for an incompatible behaviour change.

**Comment by eric-wieser** [comment]
I think there are other open issues about this. This can be a source of latent bugs, so I think we should either deprecate it or emit a UserWarning.

**Comment by seberg** [comment]
Yeah, I would be up for that deprecation, one of those things I would have liked to do years ago and never quite got myself to do it :).
