### ISSUE TITLE
It would be great to have multivariate_normal raising exception

### ISSUE THREAD

**Issue by Horta** [numpy/numpy#8263]
instead of undefined behaviour as the NumPy doc says:
> Note that the covariance matrix must be positive semidefinite (a.k.a. nonnegative-definite). Otherwise, the behavior of this method is undefined and backwards compatibility is not guaranteed.

For example, the following

```python
from numpy import errstate
from numpy.random import RandomState
from numpy.linalg import eigh
from numpy import dot

rs = RandomState(3)
m = rs.randn(10)
G = rs.randn(10, 5)
K = dot(G, G.T)

with errstate(all='raise'):
    try:
        rs.multivariate_normal(m, K)
    except Exception as e:
        print("Exception raised!")
    else:
        print("Exception not raised!")
```

prints

```bash
bug.py:13: RuntimeWarning: covariance is not positive-semidefinite.
  rs.multivariate_normal(m, K)
Exception not raised!
```

As you know, ``K`` happens to not be positive-semidefinite in the above example because of floating point arithmetic. This can be easily _fixed_ by adding a small value to its diagonal. If NumPy raised an Exception, I could perform this hack only if necessary. As it is now, I would need to check for positive-semidefiniteness beforehand, or add a small value to its diagonal before hand. Both solutions are not ideal in my opinion. Raising an exception would solve that.

**Comment by jenishah** [comment]
If no one is working, I would like to take this up.

**Comment by njsmith** [comment]
I think it's safe to assume no one's working on it

Does anyone know why it was done like this in the first place? Like, is the
check unreliable or expensive or something?

On Jan 5, 2017 8:55 AM, "jeni Shah" <notifications@github.com> wrote:

If no one is working, I would like to take this up.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/numpy/numpy/issues/8263#issuecomment-270695478>, or mute
the thread

**Comment by rgommers** [comment]
We just merged gh-5726 yesterday, so it's possible to raise an exception. The default is still to warn, with rationale backwards compat and numerical noise may sometimes give a covariate matrix that's *just* not PSD.

**Comment by rgommers** [comment]
And why not use ``errstate``: this is not one of the things (divide/over/under/invalid) it is for.

**Comment by Horta** [comment]
@njsmith 

> Does anyone know why it was done like this in the first place? Like, is the
> check unreliable or expensive or something?

I would like to be able to do the following:

```python
from numpy.random import RandomState
from numpy import einsum
from numpy import dot

rs = RandomState(3)
m = rs.randn(10)
G = rs.randn(10, 5)
K = dot(G, G.T)

try:
    u = rs.multivariate_normal(m, K)
except NotPositiveDefiniteException:
    einsum('ii->i', K)[:] += 1e-7
    u = rs.multivariate_normal(m, K)
```

The above is efficient/easy (I don't need to do any check on my part) and solve corner cases that happens all the time with such functions relying on PSD matrices.

**Comment by Horta** [comment]
@rgommers Thanks for the merge then!

Didn't get the "And why not use errstate: this is not one of the things (divide/over/under/invalid) it is for." part though...

**Comment by rgommers** [comment]
You said you wanted to use ``errstate``. ``errstate`` is for floating point errors (as in IEEE 754). This is different - you basically want a check for whether the covariance matrix provided by a user is valid or not. The normal way to deal with those kinds of user parameter checks is: do a specific check, then raise a ``ValueError`` if needed.

**Comment by Horta** [comment]
Got it now =)

By the way, nice merge here https://github.com/numpy/numpy/pull/5726 =)
