### ISSUE TITLE
Missing documentation for the "out" kwarg for np.<ufunc>.outer

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#8268]
Neither https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.outer.html#numpy.ufunc.outer nor https://docs.scipy.org/doc/numpy/reference/ufuncs.html#methods document that `np.<ufunc>.outer` supports the `out` kwarg.

**Comment by eric-wieser** [comment]
The documentation should actually just say that all the arguments are forwarded to the underlying ufunc

**Comment by eric-wieser** [comment]
Wait, I already fixed this in #8197

**Comment by charris** [comment]
@eric-wieser Could probably use more improvement, but closing this as the immediate problem is fixed.
