### ISSUE TITLE
PyArray_FromArray not always aligned on some architectures with complex numbers

### ISSUE THREAD

**Issue by olebole** [numpy/numpy#8274]
I am currently trying to get casacore working for several platforms on Debian. On some platforms (MIPS big and little endian, hppa, sparc64) there is a problem which can be reproduced with the following C extension code:
```
#include "Python.h"
#define NPY_NO_DEPRECATED_API NPY_1_10_API_VERSION
#include "numpy/arrayobject.h"

static PyObject*
array (PyObject *dummy, PyObject *args)
{
    PyObject *arg1=NULL;

    if (!PyArg_ParseTuple(args, "O", &arg1)) {
      return Py_BuildValue("s", "wrong argument");
    }
    
    PyArrayObject* po = 
      (PyArrayObject*)PyArray_FromArray((PyArrayObject*)arg1, NULL,
					NPY_ARRAY_NOTSWAPPED
					| NPY_ARRAY_C_CONTIGUOUS
					| NPY_ARRAY_ALIGNED);

    if (!PyArray_ISCONTIGUOUS(po)) {
      Py_DECREF(po);
      return Py_BuildValue("s", "not contiguous");
    }
    if (!PyArray_ISALIGNED(po)) {
      Py_DECREF(po);
      return Py_BuildValue("s", "not aligned");
    }
    if (PyArray_ISBYTESWAPPED(po)) {
      Py_DECREF(po);
      return Py_BuildValue("s", "byte swapped");
    }
    return (PyObject *)po;
}

static struct PyMethodDef methods[] = {
    {"array", array, METH_VARARGS, "return an array"},
    {NULL, NULL, 0, NULL}
};

PyMODINIT_FUNC
initnptest (void)
{
    (void)Py_InitModule("nptest", methods);
    import_array();
}
```
On mips, this gives:
```
>>> import numpy, nptest
>>> print nptest.array(numpy.copy([1, 3]))
[1 3]
>>> print nptest.array(numpy.copy([1+2j]))
[ 1.+2.j]
>>> print nptest.array(numpy.copy([1+2j, 3-4j]))
not aligned
```
However, the array was always requested to be aligned.

**Comment by pv** [comment]
Which numpy version?

**Comment by olebole** [comment]
1.11.2~rc1, but this happened also on older (1.10 or so).

**Comment by juliantaylor** [comment]
alignment of complex numbers never worked, but the only platform where its an issue is sparc which actually has 16 byte complex numbers. But you shouldn't get any bus errors anymore.
Is the issue only not reporting being aligned? If so thats probably not worth looking into, complex alignment on these arches is a cesspool of brokenness.

**Comment by olebole** [comment]
On sparc64, there is a segmentation fault here (see test 447 [here](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=sparc64&ver=2.1.0-3%2Bb3&stamp=1478984188)).

The issue raises on a [function in casacore](https://github.com/casacore/casacore/blob/master/python/Converters/PycArrayComCC.h#L308) that creates a Casa array from a Numpy array. There is no specific use for it (it is part of the Python API); however I don't know whether it is expected that this array is aligned.
If this is not going to be fixed in numpy, it may however be worth to be noted in the API docs that the alignment is done on a "best effort" base only and may not be fullfilled depending on the platform.

**Comment by juliantaylor** [comment]
An actual alignment error is usually a bus error not a segmentation fault.
An option for casacore would be to test the alignment it needs instead of using the flag. Numpy does nothing special when allocating arrays, so on most platforms the arrays are still perfectly usable. An exception is glibc powerpc which is just broken, but that platform can handle unaligned access.

**Comment by olebole** [comment]
The funny thing is that "sometimes" it seemed to work, at least on mipsel. The only difference in the numpy dependencies that changed in between (between [2.1.0-3+b2](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=mipsel&ver=2.1.0-3%2Bb2&stamp=1477168986) and [2.1.0-3+b3](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=mipsel&ver=2.1.0-3%2Bb3&stamp=1479122446) is the Debian release of the same Python version (going from  2.7.12-3+b1 to 2.7.12-5). The [changelog](http://metadata.ftp-master.debian.org/changelogs/main/p/python2.7/python2.7_2.7.12-5_changelog) didn't enlighten me here.
I will open an issue on casacore and probably just disable this check in their code.

**Comment by seberg** [comment]
My suspicion is that we can close this issue, see also https://github.com/python/cpython/pull/13320 the Python allocator should guarantee 16 byte alignment, which should be enough.  Interesting, the issue does mention this causing segmentation faults when compiling on clang, not sure that this may be related though.

In any case, alignment should be (effectively) guaranteed now for a new allocation and if there is a similar issue that comes up, please do create a new one!  (hard to proof this, since it requires a specific platform)
