### ISSUE TITLE
The --compilers flag is ignored for build_ext

### ISSUE THREAD

**Issue by aguzmanballen** [numpy/numpy#8283]
On my Ubuntu 10.04 LTS machine and while using Python 2.7.12, I have found that when I try to compile Numpy using the Intel compiler with 'python setup.py build_ext --inplace --debug --force --compiler=intelem --fcompiler=intelem' (and even without --inplace), the compilers are not being configured at all. Specifically, when it goes to run numpy/core/setup.py, there are Intel flags I have added in extra_compiler_args parameter for the umath extension that cause the build to fail with "gcc error: unrecognized command line option". I also sourced the compilervars to make sure ICC is in the path.

This is a symptom of the culprit:
running build_clib
running build_src
build_src
building py_modules sources
building library "npymath" sources
creating build
creating build/src.linux-x86_64-2.7
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using config

It should look like a little something like this:
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
creating build
creating build/src.linux-x86_64-2.7
creating build/src.linux-x86_64-2.7/numpy
creating build/src.linux-x86_64-2.7/numpy/distutils
building library "npymath" sources
Found executable /localdisk/psxe_16/compilers_and_libraries_2016.3.210/linux/bin/intel64/icc
Could not locate executable ecc
customize IntelEM64TFCompiler
Found executable /localdisk/psxe_16/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
customize IntelEM64TFCompiler using config

I do not experience this problem with 'setup.py build' because the configuration function is correctly called here: https://github.intel.com/SAT/numpy/blob/develop/numpy/distutils/command/build.py#L11 (that is where I got the output from above). However, I do not see anything like this in build_ext: https://github.intel.com/SAT/numpy/blob/develop/numpy/distutils/command/build_ext.py#L34. This of course could be because build_ext is doing something else below in the run command on line 109.

I'd be glad to help fix this in some way instead of just handing it off to you guys. Hopefully there is something I'm missing but if not, I'd be happy to do what I can to get a patch for this so I can debug my code using build_ext --inplace.

**Comment by charris** [comment]
Where did you get numpy and what version is it?

**Comment by charris** [comment]
Also, you may want to post to the list, there are likely more Intel using folks there than here.

**Comment by aguzmanballen** [comment]
It's numpy v1.11.2 (https://pypi.python.org/packages/16/f5/b432f028134dd30cfbf6f21b8264a9938e5e0f75204e72453af08d67eb0b/numpy-1.11.2.tar.gz). I'll post it to the mailing list too, thank you for the suggestion!

**Comment by rgommers** [comment]
We've switched build systems from `numpy.distutils` to Meson, hence this issue is no longer relevant. Building with Intel compilers should be working as expected. Hence closing - thanks all.
