### ISSUE TITLE
HTML documentation gets version number wrong.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#8289]
For example, `NumPy v1.12b1 Manual` should be `NumPy v1.12.0b1 Manual`. The same mistake is repeated in the links and tags. The PDF documentation looks fine.

**Comment by pv** [comment]
Can be fixed by removing version munging from doc/source/conf.py

**Comment by charris** [comment]
OK, we don't upload documentation for pre-releases, so using the same documentation modulo minor fixups throughout a major.minor release cycle makes sense and there should be no need to include the micro release number.  I'm closing this.

**Comment by charris** [comment]
Although I see the links on the docs page use the micro version number. Hmm...
