### ISSUE TITLE
link args contain -Wl,Accelerate even when using openblas

### ISSUE THREAD

**Issue by davydden** [numpy/numpy#8293]
on macOS numpy ends up using `extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']` even when configured with
```
[ALL]
libraries = openblas
library_dirs=path/to/openblas/lib
```
in `site.cfg`. 

p.s. no extra environment variables like `ATLAS`, `BLAS`, `LAPACK` are set.

**Comment by charris** [comment]
The OS X configuration is hardwired in, we might want to change that going forward.

**Comment by rgommers** [comment]
@davydden thanks for the report. Should be fixed by gh-8308, can you check that that works as expected for you?
