### ISSUE TITLE
Sum factorization in einsum

### ISSUE THREAD

**Issue by nchisholm** [numpy/numpy#8301]
I'm wondering if `einsum` takes advantage of sum factorization when more than more than one summation is involved.  Consider the following simple example.

```
# Define some arrays
a = np.random.random((10, 10))
b = np.random.random((10, 10))
c = np.random.random((10, 10))

# "Naive" multiplication (dot products) of the three matrices
#   x_il = SUM_j SUM_k a_ij b_jk c_kl  with  i, j, k, l = 0, 1, ..., N-1
# => needs O(2 * N^4) multiplications
result1 = np.einsum('ij,jk,kl', a, b, c)

# Factor `a` out of the inner summation over k
#   x_il = SUM_j a_ij ( SUM_k b_jk c_kl )
# => needs only O(N^3) + O(N^3) multiplications
result2 = np.einsum('ij,jk', a, np.einsum('jk,kl', b, c))
```
Of course, `result1` and `result2` come out equal.  Doing some simple timings in IPython, I get the following.
```
# No factorization
%timeit np.einsum('ij,jk,kl', a, b, c)
The slowest run took 4.91 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 48 µs per loop

# Factorization done explicitly
%timeit np.einsum('ij,jk', a, np.einsum('jk,kl', b, c))
The slowest run took 4.97 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.89 µs per loop
```
Explicitly doing the sum factorization results in a 6x speedup.  I'm thinking it would not be too hard to do the factorization automatically without making nested einsum calls. Any thoughts?

**Comment by charris** [comment]
Numpy 1.12 will have optional optimization einsum evaluation, see #5488. @dgasmith I believe your work covers this case?

**Comment by dgasmith** [comment]
Absolutely, in Numpy 1.12 `np.einsum('ij,jk,kl', a, b, c, optimize=True)` will automatically build intermediates to reduce the overall scaling of a tensor contraction. You can check out the primary [repo](https://github.com/dgasmith/opt_einsum) if you want it before 1.12 or if you want BLAS functionality.
