### ISSUE TITLE
Documentation: Example code for histogram2d

### ISSUE THREAD

**Issue by cbehren** [numpy/numpy#8309]
Hi everyone,
I noticed the following:
The documentation for histogram2d input and output parameters correctly states that 
`H, xedges, yedges = np.histogram2d(x,y)`
returns the bin edges associated with the data binned along the first dimension (x) in xedges. As described in the doc, histogram2d does not follow the Cartesian convention for the input vectors, so to have the binned data of y on the Cartesian y axis, one needs to revert the order of arguments. However, the code examples look like this:
`H, xedges, yedges = np.histogram2d(y,x)`
Note that the input arguments have been reverted, but the output argument have not. As far as I understand, It should read
`H, yedges, xedges = np.histogram2d(y,x)`

In my opinion, it would be good to additionally relabel the arguments in the doc, because 'x' and 'y' will mislead some users to assuming that this is the order of arguments for a histogram following Cartesian convention. I know that it is written on the very same page that the routine does not follow the convention, but I suppose many users will skip over this. 
I hope this is the right place to file this issue: I did not find a specific tracker for the documentation.

**Comment by rgommers** [comment]
Thanks @cbehren. You are correct, this change has already been made in master: https://github.com/numpy/numpy/blob/master/numpy/lib/twodim_base.py#L609
