### ISSUE TITLE
Allow random.choice from empty array when size=0

### ISSUE THREAD

**Issue by MareinK** [numpy/numpy#8311]
This piece of code:

```python
np.random.choice([],size=0)
```

Generates this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1397, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:15499)
ValueError: a must be non-empty
```

This error makes sense when `size>0`, but when `size=0`, `random.choice` could simply return `[]`. This would be useful when the `a` and `size` parameters are variable. Right now this situation requires an additional check:

```python
if size > 0:
  result = np.random.choice(a,size)
else:
  result = np.array([])
```

Would it be a good idea to simply return an empty array when `size=0`? This is my first issue so I hope this is the right way to address this.

I created a simple patch that implements this: 57ab0728d4cf73c1f4b3af2450fe603bf8670b75

I'm using Python 3.5.2 with numpy 1.11.2.

Edit: My implementation returns an empty slice from the original array. My thinking was that this would assign the correct `base` to the resulting array, but on second thought this is not what happens with `random.choice` normally, so I think returning `np.array([])` would be better.

**Comment by eric-wieser** [comment]
You should probably promote this to a PR, and add a test with it

**Comment by anntzer** [comment]
You probably want to return an array of the same dtype of the input choices (if it is already an ndarray itself), too.
