### ISSUE TITLE
numpy.mean returns infinity while values are finite

### ISSUE THREAD

**Issue by MareinK** [numpy/numpy#8313]
When taking the mean of an array of large (but finite) values, numpy will return `np.inf`.

```python
>>> x = np.array([8.988465674311579e+307, 8.98846567431158e+307])
>>> x
array([  8.98846567e+307,   8.98846567e+307])
>>> x.mean()
inf
```

[I discussed this on StackOverflow](http://stackoverflow.com/questions/40803737/why-is-numpy-mean-infinite-while-values-are-finite) and the consensus seems to be that this happens because numpy first sums the values, then divides by the length of the array. Since the two values in the example array sum to a value larger than the limit of their data type, the result of the sum is `np.inf`, and remains so after division.

Would it be a good idea to change this behaviour? The obvious solution would be to divide first, sum after. However, this would impact performance of all `mean` calls negatively. Smarter solutions are possible, but first I'd like to know whether this is something worth investigating. Have there been previous discussions/decisions on this topic?

I'm using Python 3.5.2 with numpy 1.11.2.

**Comment by charris** [comment]
This is the sort of thing that should be raised on the list. I own inclination is to leave things as is. There are more accurate algorithms for computing means, but eventually everything breaks down and the loss of speed can be significant. One simply needs to be aware of the pitfalls of numerical computation.

**Comment by metaperture** [comment]
You can also use the following hack to do this in general:
```
def my_mean(x):
    return np.average(x, weights=np.ones_like(x) / x.size)
```
The way you'd fix np.mean would be to multiply by 1/n beforehand--using weights with np.average can do that without loss of generality.

**Comment by charris** [comment]
Another way is with a recursive filter: avg(n+1) = avg(n) + (d(n+1) - avg(n)) / (n+1), which less susceptible to roundoff errors. I the division is done termwise it will also never go out of the convex hull of the data values.

I'm going to close this though. The general topic of improvements for the computation of mean and variance comes up now and then, it can always be discussed once more on the mailing list. I believe some downstream packages offer more robust computation, but don't remember which at the moment.
