### ISSUE TITLE
numpy "debug" crashes at import

### ISSUE THREAD

**Issue by bartoli** [numpy/numpy#8314]
If I try to build numpy (1.11.0)  for a python (3.5.1) that has lots of debugging features enabled, importing of mtrand will crash at import of numpy

Python is compiled with `--with-pydebug CFLAGS="-DPy_DEBUG -DPy_REF_DEBUG -DPyTRACE_REFS -DCOUNT_ALLOCS -DPYMALLOC_DEBUG"`

numpy is then built with that python with `python setup.py --debug` (using setuptools-21.0.0)

At the import of numpy from that pyhton, i get : 
```
File "/path/to/numpy-1.11.0/lib/python3.5/site-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
  File "mtrand.pyx", line 5080, in init mtrand (numpy/random/mtrand/mtrand.c:38324)
  File "mtrand.pyx", line 931, in mtrand.RandomState.__init__ (numpy/random/mtrand/mtrand.c:11787)
  File "mtrand.pyx", line 938, in mtrand.RandomState.seed (numpy/random/mtrand/mtrand.c:11952)
TypeError: seed() takes at most 1 positional argument (139815047117784 given)
RuntimeWarning alloc'd: 1, freed: 1, max in use: 1
```

Doing the same with a python build with just `-with-pydebug` but not the additional CFLAGS don't crash. Maybe that's the indication of something not properly done, if extra checks cause a crash?

I at first suspected an issue of a debug version that would load release .so or something like that, because i was installing both builds at the same place. I now build numpy release and debug in separate places with separate python builds, and still got the problem, so that is not the issue

**Comment by charris** [comment]
Sounds more like a Cython problem. Might raise this on the mailing list for discussion.

**Comment by juliantaylor** [comment]
hm one of our CI builds is using the debug interpreter, maybe it should be updated to a newer version.

**Comment by mattip** [comment]
closing since the original reporter has not replied and we do test debug on CI, although not ths exact version of cpython. If the issue reappears please reopen.
