### ISSUE TITLE
repr for "empty" matrix cannot be evaluated

### ISSUE THREAD

**Issue by goerz** [numpy/numpy#8316]
>>> from numpy import *
    >>> a = array([[], []], dtype=float64)
    >>> repr(a)
    'array([], shape=(2, 0), dtype=float64)'
    >>> eval(repr(a))
    TypeError: 'shape' is an invalid keyword argument for this function

This prevents me from sending a `repr` string to another process where the original object can be instantiated through `eval`

**Comment by charris** [comment]
Yep, that repr isn't right.

**Comment by charris** [comment]
`str(a)` isn't any better
```
In [3]: str(a)
Out[3]: '[]'
```

**Comment by njsmith** [comment]
It would be nice to fix the repr, but note that we definitely do *not*
guarantee that eval(repr(...)) will do anything useful. You really
shouldn't be doing that. (Maybe you want pickle?)

**Comment by charris** [comment]
The code is mostly in `numpy/core/numeric.py`, see line 1900. There is also a bit in `numpy/core/arrayprint.py` that sets the `[]`, but the actual formatting seems to be in the numeric file.

**Comment by goerz** [comment]
Yeah, I'm aware of the problems associated with`eval`. Nonetheless, it would be really nice to guarantee that the `eval` of any object re-instantiates that object, assuming a proper context. I'm working on a computer algebra system where I would like to have this property (and where numpy arrays may come up as coefficients). There's definitely ways around it, but it makes things easier.

**Comment by charris** [comment]
How do you print something of shape `(0, 1)`? the `(1, 0)` case isn't a problem.

**Comment by njsmith** [comment]
I can see how it would be nice, but it's still not a guarantee that we
make, and if it breaks you get to keep both pieces. Off the top of my head,
array repr also discards precision, and ellipsizes large arrays. If you
really want this property, then you should write your own array printing
code.
.
None of this necessarily rules out this bug report, though; it just means
that the change has to be justified as being nicer for humans to read.
(Though... is it? For a (0, 2) shaped array, I guess [[], []] is somewhat
nicer and certainly more accurate, but for a (0, 100) shaped array I'm not
so sure.)

**Comment by goerz** [comment]
point taken

**Comment by pv** [comment]
Note that the repr appears quite often in interactive use, where having 
huge outputs spewed to the console can be a nuisance which I guess is 
the motivation for precision truncation and ellipsis.

**Comment by goerz** [comment]
Yeah, that's another problem, which e.g. `sympy` solves by having `srepr`. I think if `repr` gets too long and starts to clutter up the interactive console, pushing that functionality into a special function, or configuration flags (which I think numpy partly does by allowing to configure things like precision and ellipsis in the output) makes a lot of sense.

**Comment by charris** [comment]
```
In [1]: a = array([]).reshape(0, 2)

In [2]: a
Out[2]: array([], shape=(0, 2), dtype=float64)
```
How do you propose to reproduce `a` without a reshape?

**Comment by goerz** [comment]
You're right, there's no direct way, because `array` doesn't explicitly take the shape information in its constructor.

Very ideally, I would say that the output of `repr` actually *should* be valid, but adding a `shape` keyword argument to the `array` constructor that does automatic reshaping seems like a pretty big change. In the absence of that, one would probably have to detect this case explicitly and output e.g. the original `array([[], []])`. But I agree, it's a pretty pathological case, unfortunately, and I'm not sure what a good fix would be.

If you want to just close this, I'm fine with that, too - for my particular situation, I have an easy workaround.

**Comment by charris** [comment]
Thanks for the report.
