### ISSUE TITLE
Unable to use scipy.stats.multivariate_normal

### ISSUE THREAD

**Issue by frapoleon** [numpy/numpy#8321]
I have installed scipy before, but unable to find a module named multivariate_normal. I guess it is because I didn't upgrade scipy. But when I use pip install scipy --upgrade, it returns error 13: Permission denied - /usr/local/lib/python2.7. How can I fix it? Thanks a lot!

**Comment by rgommers** [comment]
``multivariate_normal`` was introduced in 0.14.0, do you have an even older version?

Upgrading depends on how you installed scipy in the first place. Looks like you installed via your package manager. That must have a recent enough version. If not, uninstall from your package manager and install with ``pip install scipy --user``.
