### ISSUE TITLE
numpy.packbits does not always return a uint8 array

### ISSUE THREAD

**Issue by iwiwi** [numpy/numpy#8324]
The document states that `numpy.packbits` returns a `uint8` array. However, when an empty array is given, the `dtype` of the returned array is not `uint8`, but is the same as that of the input array.

I think this is because function `pack_bits` in `core/src/multiarray/compiled_base.c` just copies the input array when the input array is empty. (https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/compiled_base.c#L1555)

![image](https://cloud.githubusercontent.com/assets/469803/20664179/6dbe62e0-b59d-11e6-8790-34e1a1cd2b2c.png)

I confirmed this issue on NumPy 1.11.2.

**Comment by thouis** [comment]
It looks like there may also be a leak of the `new` object on this code path.

**Comment by iwiwi** [comment]
I also found another problem: the shape of the output is inconsistent when given an empty array and axis specification.

Do we have good reason to handle empty arrays separately? I think it would solve these three problems (type, shape and leak) to remove that part.

![image](https://cloud.githubusercontent.com/assets/469803/20698787/ba9183be-b646-11e6-85b0-e3f3367be0be.png)

**Comment by charris** [comment]
Fixed by #8327.
