### ISSUE TITLE
numpy.ndarray.tofile creates a corrupt file for large arrays in append file mode

### ISSUE THREAD

**Issue by potocpav** [numpy/numpy#8329]
When saving a large array (>= 2,097,152 doubles), the `tofile` function creates a file twice the size of the data, and the first half of the file is all zeros. This occurs only in the append file mode (`"ab"`).

My system:
```
Linux 4.8.10-1-ARCH x86_64
Python 3.5.2
numpy.version.version == '1.11.2'
```

Code to reproduce:
```python
import numpy

def foo(n, file, mode):
    m = numpy.random.rand(n)
    open(file, "wb").close() # delete old file contents
    f = open(file, mode)
    m.tofile(f)
    f.close()

    n = numpy.fromfile(open(file, "rb"))
    print("correct" if numpy.array_equal(m, n) else "incorrect")

foo(2097151, "f1", "ab") # correct
foo(2097152, "f2", "ab") # incorrect
foo(2097152, "f3", "wb") # correct```

**Comment by potocpav** [comment]
x86_64?

**Comment by potocpav** [comment]
Maybe the number it starts to fail on is variable, could you try bigger arrays?

**Comment by pv** [comment]
x86_64

**Comment by potocpav** [comment]
I dug into the issue, and it seems to be due to the behavior of `fallocate`. Offending code is in this function:

https://github.com/numpy/numpy/blob/7ccf0e08917d27bc0eba34013c1822b00a66ca6d/numpy/core/src/multiarray/convert.c#L44

The issue manifests starting with the array size of 16,777,216, which is when the `fallocate` is triggered. I tested `fallocate` followed by a `write` and it produces the same leading zeros as observed.

It may be possible to reproduce only on some filesystems: I tested btrfs and tmpfs.

A possible fix: fallocate only if the file is not in append mode?

**Comment by charris** [comment]
@juliantaylor Thoughts?

**Comment by charris** [comment]
Fails here:

Numpy: '1.13.0.dev0+1a640ea'
Linux: 4.8.8, x86_64
Python:  2.7.12

Disk is two SSDs formatted as ext4 and configured in raid 0

**Comment by juliantaylor** [comment]
hm yes, it should be using FALLOC_FL_KEEP_SIZE (=1) in that case. Can you get the mode of a file descriptor?
if not probably it could probably just always be used.

**Comment by charris** [comment]
@juliantaylor Mode is 'ab' for the write. I don't anything at the file descriptor level -- fstat, fstatvfs -- that looks useful. What did you have in mind?
