### ISSUE TITLE
ENH: in1d, but preserve shape of ar1

### ISSUE THREAD

**Issue by brsr** [numpy/numpy#8331]
in1d takes two arrays, `ar1` and `ar2`, and returns a 1d array with the same number of elements as `ar1`. The logical extension would be a function that does the same thing but returns a (possibly multi-dimensional) array of the same shape as `ar1`. Effectively, it would be equivalent to this:

    def in(ar1, ar2, **kwargs):
      return np.in1d(ar1, ar2, **kwargs).reshape(ar1.shape)

although it might be implemented differently.

**Comment by jaimefrio** [comment]
There already is [a comment](https://github.com/numpy/numpy/blob/master/numpy/lib/arraysetops.py#L444) in the code pointing in that direction.

I don't think it is viable to change the behavior of the function for backwards compatibility reasons, although it would be possible to add a `keep_shape=False` kwarg to trigger the proposed new behavior.

If you want to see this happen, your best bet is to do it yourself. It should be relatively straightforward, as this function is entirely coded in Python, see the link above. Before getting down to that, changes in the user interface like this one would require discussion and approval on the mailing list. Can you also send an e-mail there with the proposed change?

**Comment by brsr** [comment]
I figured there would need to be discussion beforehand. Should I email numpy-discussion or scipy-dev?

**Comment by jaimefrio** [comment]
numpy-discussion is the place for this, please do!
