### ISSUE TITLE
Data race issue in numpy array index increamenting

### ISSUE THREAD

**Issue by PeterPallesen** [numpy/numpy#8334]
The following code gives a data race. I know it is not the right way to make an array counting all the aperances of values, but I would have liked to have warning. Is this approprited for a warning without to much overhead?
---code----
import numpy as np
x_train=np.random.random_sample((10000,5))
x_train_idx=np.round(x_train*1e4).astype("int32")
hist_train=np.zeros((x_train.shape[1],1e4+1))
for i in range(x_train.shape[1]):
    hist_train[i,x_train_idx[:,i]]+=1
print(np.sum(hist_train))
print(x_train.shape[0]*x_train.shape[1])
----out--- 
31649.0
50000

**Comment by pv** [comment]
This is more a question of semantics
```
a += b
a[...] = a + b
```
are supposed to be equivalent.

**Comment by PeterPallesen** [comment]
You are probably right. In the end it was a stupid way to do it. Thanks for the opinion
