### ISSUE TITLE
print nonbroadcastable shapes in np.broadcast_arrays error message

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#8345]
Currently, `np.broadcast_to` prints the nonbroadcastable shapes in its error message, but not `np.broadcast_arrays`:
```
In [1]: np.broadcast_to([1, 2], 3)
<elided>
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,) and requested shape (3,)

In [2]: np.broadcast_arrays([1, 2], [3, 4, 5])
<elided>
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```
It would be mildly helpful if the second error message also reported the incorrect shapes.

**Comment by eric-wieser** [comment]
What should `np.broadcast_arrays(a, b, c, d, e, f, g, h, i ,j, k, l, m, n, o, p, q, ...)` print out to be useful? The error message could quickly become unmanageable

**Comment by anntzer** [comment]
I would just print all the shapes.  If you write illegible code (with a gazillion of arguments in the same function call), you get an illegible error message.  If you write legible code, you get a legible error message.  Sounds fair?

**Comment by WarrenWeckesser** [comment]
Proposed enhancement is in https://github.com/numpy/numpy/pull/20018.

With that change:

```
>>> import numpy as np
>>> np.__version__
'1.22.0.dev0+1295.g6ad932c41'
>>> np.broadcast_arrays([1, 2], [3, 4, 5])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 181, in broadcast_arrays
  File "/home/warren/mc39numpy/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 539, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/home/warren/mc39numpy/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 421, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2,) and arg 1 with shape (3,).
```
