### ISSUE TITLE
np.isscalar(custom_obj) returns False even though np.shape(custom_obj) is ()

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#8347]
I would have assumed that `np.isscalar(x) == (np.shape(x) == ())` but this is not the case when `x` is an object of a user-defined class (with no special methods whatsoever).

**Comment by mhvk** [comment]
I agree with the presumption, but `isscalar` is really about the object being an instance of a scalar type. E.g., array scalars fail as well:
```
In [2]: np.isscalar(np.array(1))
Out[2]: False
```
The actual code is:
```
    if isinstance(num, generic):
        return True
    else:
        return type(num) in ScalarType
```
(l2088 in numeric.py)

**Comment by shoyer** [comment]
We wrote our own helper function for this in xarray:
https://github.com/pydata/xarray/blob/8b54f939bc84b20ad4670f22375d2fd7c1761b7a/xarray/core/utils.py#L181

**Comment by eric-wieser** [comment]
I think this can be closed, as this is now documented at https://www.numpy.org/devdocs/reference/generated/numpy.isscalar.html?highlight=isscalar#numpy.isscalar, advising you us `np.ndim(x) == 0` instead.
