### ISSUE TITLE
recarray access is slow (1.11.2)

### ISSUE THREAD

**Issue by isaacovercast** [numpy/numpy#8353]
Hi Folks,
I'm seeing `recarray` access on the order of 10x slower than `array` access. I'm using python 2.7.12 on mac with numpy 1.11.2. Appears to be similar behavior to #6467 in 1.10.1, but it looks like that issue was fixed. I tested this on a linux box and see the same behavior (python 2.7.12, numpy 1.11.2, Ubuntu 14.04 LTS).

Code to reproduce:
```
a = np.recarray(100, dtype=[('wat', np.int64)])
b = np.zeros(100, dtype=np.int64)

%timeit a['wat'][5] += 1
100000 loops, best of 3: 15.7 µs per loop

%timeit b[5] += 1
1000000 loops, best of 3: 579 ns per loop
```

Any more information I can provide?

**Comment by J-Sand** [comment]
#6467 seems to be about plain `ndarray`s with fields. `recarray` is a wrapper around `ndarray` that allows you to access fields using attribute syntax, e.g. `a.wat`. `recarray` is implemented in pure python, so it's bound to be slower. If you don't want to access fields as if they are attributes, you should just be able to do:

    a = np.zeros(100, dtype=[('wat', np.int64)])

**Comment by ahaldane** [comment]
This doesn't seem to be a regression since it does this even in 1.8.0. Also, the slowdown is due to the `__getitem__` key access overhead, since this is fast:

    c = a['wat']
    %timeit c[5] += 1

recarrays have to do some extra work compared to ndarrays on key access, to determine whether to cast the result to a recarray too.

**Comment by isaacovercast** [comment]
That makes sense. Thanks for the clarification, i looked everywhere in the docs and online and it was not straightforward to identify why this was happening.
