### ISSUE TITLE
Multiple imports of shape_base

### ISSUE THREAD

**Issue by smontanaro** [numpy/numpy#8370]
While working on some mypy/typeshed stubs for numpy, I stumbled on what I thought was a mypy error, but which they indicated was a numpy error. Details here:

https://github.com/python/mypy/issues/2557

**Comment by smontanaro** [comment]
Note that the same bug probably exists for the function_base module.

**Comment by eric-wieser** [comment]
I don't see a problem in master, since neither the `__all__` in `core/__init__.py` or `lib/__init__.py` allows `shape_base` to escape that module

**Comment by seberg** [comment]
Seems like this was fixed already at the time of opening, just not closed.
