### ISSUE TITLE
big matrix computing issue

### ISSUE THREAD

**Issue by liucsthu** [numpy/numpy#8375]
I use numpy to solve matrix decomposing problem with target function
$J = 0.5*|A*(X - U.*V')|_f^2 + b*|U|_f^2 + b*|V|_f^2$
and use gradient decrease to solve it but it seems the target is wrong
A is an indicator matrix where if X[i][j] != 0 A[i][j] = 1  else A[i][j] = 0 
X is m*n matrix as the target matrix (we use 10000*10000)
U is m*k  matrix  ranged at(0,1) and is randomly generated
V is n*k matrix   ranged at (0,1) and is randomly generated
it seems after a few times of iteration, the J will overflow
here is the code
 ```python
delta_U = ( np.multiply(A , (np.substract(U.dot(V.T), X)))).dot(V) + 2 * b * U
delta_V = (np.multiply(A , np.substract(U.dot(V.T), X))).T.dot(U) + 2 * b * V
U = U - a*delta_U
V = V - a*delta_V
The J is computed in this way :
J = 0.5 * norm(A * (X - U.dot(V.T)),ord='fro') + b * norm(U,ord='fro') + b * norm(V,ord='fro')
Is this an issue or I misused the package?

**Comment by pv** [comment]
This type of questions are best asked on stackoverflow, if it's not 
clear Numpy is at fault.

**Comment by seberg** [comment]
Looks like an old user question, closing.
