### ISSUE TITLE
Selecting multiple fields from structured masked array gives FutureWarning

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#8383]
On Numpy 1.11.2:

```
In [181]: M = ma.zeros(shape=10, dtype="f,f,f,f")

In [182]: M[["f0","f1"]]
/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/numpy/ma/core.py:2958: FutureWarning: Numpy has detected that you (may be) writing to an array returned
by numpy.diagonal or by selecting multiple fields in a structured
array. This code will likely break in a future numpy release --
see numpy.diagonal or arrays.indexing reference docs for details.
The quick fix is to make an explicit copy (e.g., do
arr.diagonal().copy() or arr[['f0','f1']].copy()).
  if (obj.__array_interface__["data"][0]
/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/numpy/ma/core.py:2959: FutureWarning: Numpy has detected that you (may be) writing to an array returned
by numpy.diagonal or by selecting multiple fields in a structured
array. This code will likely break in a future numpy release --
see numpy.diagonal or arrays.indexing reference docs for details.
The quick fix is to make an explicit copy (e.g., do
arr.diagonal().copy() or arr[['f0','f1']].copy()).
  != self.__array_interface__["data"][0]):
```

I don't know if it will break, but it does sound scary.

**Comment by gerritholl** [comment]
Still the same in `numpy 1.12.0b1`.

**Comment by gerritholl** [comment]
Still the same in `1.13.0`.

**Comment by gerritholl** [comment]
It also happens if I try to circumvent it by explicitly calling

ma.masked_array(M.data[["f0", "f1"]], M.mask[["f0","f1"]])

**Comment by ahaldane** [comment]
The message is referring to the proposed change for 1.14 in #6053. 

In this case, it is probably a spurious warning. At most, the warning is telling us that a fixup may be needed somewhere deep in `np.ma` code after #6053 is accepted, which we should seriously investigate.

Here is how this warning was "supposed" to work:
```python
>>> N = np.zeros(shape=10, dtype="f,f,f,f")
>>> N[["f0", "f1"]]  # no warning
array([(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.),
       (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
      dtype=[('f0', '<f4'), ('f1', '<f4')])
>>> N[["f0", "f1"]].view('i,i')  # warning!
runtests.py:1: FutureWarning: Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array. 

This code may break in numpy 1.13 because this will return a view instead of a copy -- see release notes for details.
  #!/usr/bin/env python
array([(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),
       (0, 0), (0, 0)],
      dtype=[('f0', '<i4'), ('f1', '<i4')])
```

**Comment by ahaldane** [comment]
I just confirmed this is a spurious warning. 

It is caused by a call to `array_might_be_written` in `array_interface_get`. However in the relevant `np.ma` code no such writes/views actually occur, so we are safe.

Another way to get the spurious warning is
```python
>>> N = np.zeros(shape=10, dtype="f,f,f,f")
>>> N[["f0", "f1"]].__array_interface__
runtests.py:1: FutureWarning: ....
```

**Comment by jzwinck** [comment]
Here's another way to trigger this annoying warning:

    arr = np.array([(1, 2), (3, 4)], [('a', int), ('b', int)]).view(np.recarray)
    print(arr[['a', 'b']]) # FutureWarning, though I have done nothing that could possibly go wrong

In NumPy 1.12.1 it gives this warning:

    numpy/core/records.py:507: FutureWarning: Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array. 
    This code may break in numpy 1.13 because this will return a view instead of a copy -- see release notes for details.
      return obj.view(dtype=(self.dtype.type, obj.dtype))

The problem is, it's totally unclear how to fix it!  Adding `.copy()` either before or after the indexing does not fix it.  I had to sprinkle `warnings.simplefilter` in several places to work around it, and I'm not even writing to any of the arrays!

**Comment by bsipocz** [comment]
These warnings are not present any more on 1.18dev. 

Please reopen if you still see them with a recent numpy release.
