### ISSUE TITLE
`rowvar` should be boolean in `cov`, `corrcoef`

### ISSUE THREAD

**Issue by endolith** [numpy/numpy#8396]
The `rowvar` parameter seems to a boolean flag?

> rowvar : int, optional
> 
> If rowvar is non-zero (default), then each row represents a variable, with observations in the columns. Otherwise, the relationship is transposed: each column represents a variable, while the rows contain observations.

If so, the docstring should be changed to 

> rowvar : bool, optional
> 
> If rowvar is True (default), then each row represents a variable, with observations in the columns. Otherwise, the relationship is transposed: each column represents a variable, while the rows contain observations.

and the code should be changed from `if rowvar == 0` to `if not rowvar`.

**Comment by b-carter** [comment]
I believe this was changed in v1.11 for `cov` (https://github.com/numpy/numpy/pull/6857) but still appears unchanged for `corrcoef`. Are you looking at the documentation in v1.11?

I can submit a PR to update `corrcoef`.

**Comment by b-carter** [comment]
Actually, there was still the `if rowvar == 0` check in `cov`. I'll update those as well.
