### ISSUE TITLE
Inconsistency in lstsq

### ISSUE THREAD

**Issue by heinzermch** [numpy/numpy#8404]
I have a problem which I am solving via linear least squares. However the results are not consistent when running the program multiple times with the same data. But whenever I run the solver multiple times inside the same program, the difference does not appear. Moreover the results seem to alternate between two different solutions.

The latest examples are the following two outputs:
`[  7.78964111e+06  -6.91807608e+07   3.69908591e+08  -1.33019377e+09
   3.40050537e+09  -6.36327818e+09   8.83160153e+09  -9.09698195e+09
   6.87236823e+09  -3.70300498e+09   1.34827000e+09  -2.97445412e+08
   3.00399284e+07]`

`[  7.78964630e+06  -6.91808033e+07   3.69908803e+08  -1.33019448e+09
   3.40050710e+09  -6.36328128e+09   8.83160565e+09  -9.09698605e+09
   6.87237124e+09  -3.70300656e+09   1.34827056e+09  -2.97445534e+08
   3.00399406e+07]`

The differences are not huge but nevertheless lead to different results in other parts of the program, and therefore to an unnecessary randomness.

What causes those differences?

**Comment by pv** [comment]
General floating point issue on modern computers.
.
http://www.mpcdf.mpg.de/services/computing/software/languages-1/FP_accuracy_reproducibility.pdf

**Comment by heinzermch** [comment]
Thanks, question solved

**Comment by pv** [comment]
You can avoid variation from data alignment by copying first into 
64-byte aligned arrays, cf 
https://github.com/scipy/scipy/blob/9cec221e5eb2fc6252863e056e25c823c1e8ee5f/scipy/_lib/_util.py#L102. 
This doesn't fix the variation from multithreaded BLAS, however.
