### ISSUE TITLE
numpy basic operation issue (add)

### ISSUE THREAD

**Issue by kbosal** [numpy/numpy#8405]
I found a strange problem, where the the variable on the right side of ( = ) take values from left side and it goes up back to the beginning of the program:
example:
TABLE_COORDINATES_T = array([
                           [0,0,0],
                           [2.00,3.0,0.00],
                           [-4.0,	5.0,	-0.00],
                           [-3.0,	9.0,	0.0]
                           ])
u=array([10,20,30])

TABLE_COORDINATES_TAU=TABLE_COORDINATES_T # This is just for initialization

TABLE_COORDINATES_TAU[2]=TABLE_COORDINATES_T[2]+u
# This gives:
>>>TABLE_COORDINATES_TAU[2]
array([  6.,  25.,  30.])
# but also gives the strange response as!!!
>>>TABLE_COORDINATES_T[2]
array([  6.,  25.,  30.]) #####!!!!!!! the value on the right side is also updated!!!

**Comment by charris** [comment]
Because they are the same array. You probably want
```
TABLE_COORDINATES_TAU=TABLE_COORDINATES_T.copy()
```

**Comment by kbosal** [comment]
It was not copying, It was just initialization by using an old array. I could solve the issue by generation with f zero arrays zero( m,n)  and then updating components for the new array one by one to AVOID COPYING. Anyway I solved the issue. in fact,  it was strange to me that the copying was happening.

**Comment by juliantaylor** [comment]
I recommend to go over the basics of python again, in this language everything is a reference and copies are explicit for mutable types.
Numpy behaves the same way with one exception, slicing on array(`[:]`) does unlike python lists produce a view and not a copy.
