### ISSUE TITLE
np.linalg.norm returning wrong result (2-norm)

### ISSUE THREAD

**Issue by stefanonardo** [numpy/numpy#8407]
operating system: ubuntu 16.04
numpy: 1.11.2
python: 2.7.12
```

>>> import numpy as np
>>> m = np.array([[4,0],[1,2]])
>>> np.linalg.norm(m, ord=2, axis=0)
array([ 4.12310563,  2.        ])
```
It should instead returns [4, sqrt(5)]

**Comment by charris** [comment]
Looks right to me. The `axis=0` means along the first axis on the left, i.e., downwards so that the norms are for `[4, 1][` and `[0, 2]` respectively. What you seem to be expecting is what `axis=1` would give you.
