### ISSUE TITLE
Allow numpy to copy internal buffer into memoryview

### ISSUE THREAD

**Issue by realitix** [numpy/numpy#8408]
Hello,

I have a C extension which maps memory address to a pointer.
In this extension, I return this pointer through a memoryview `PyMemoryView_FromMemory(char *mem, Py_ssize_t size, int flags)`.

In my python code, I created a numpy array of float and I want to `memcpy` this array to my memory mapped in C.

Here what I do:
```
mymemoryview = MyMemoryView() # pointer on a 24 bytes buffer
vertices = np.array([0, -0.5, 0.5, 0.5, -0.5, 0.5], dtype=np.float32)
wrapper = np.array(mymemoryview, copy=False) # Wrap my memoryview into a numpy array without copy
np.copyto(wrapper, vertices, casting='no')
```

When I execute this code, I get:
```
TypeError: Cannot cast scalar from dtype('float32') to dtype('uint8') according to the rule 'no'
```

Ok so I force my `memoryview` to be a `float32`
```
mymemoryview = MyMemoryView() # pointer on a 24 bytes buffer
vertices = np.array([0, -0.5, 0.5, 0.5, -0.5, 0.5], dtype=np.float32)
wrapper = np.array(mymemoryview, copy=False, dtype=vertices.dtype) # Wrap my memoryview into a numpy array without copy
np.copyto(wrapper, vertices, casting='no')
```

Return:
```
ValueError: could not broadcast input array from shape (6) into shape (24)
```

Of course the size of my `memoryview` is 24 bytes but not 24 float... Numpy doesn't understand...

I tried with `casting='unsafe'` but it doesn't work either.

### I would like to create a new function `copyinto` wich copy into a `memoryview`. Do you see another way to do it ?

**Comment by shoyer** [comment]
You can use the view method (https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.view.html) to convert your numpy array to the dtype of the memory view.

**Comment by realitix** [comment]
Thanks @shoyer I will try that and let you know.

**Comment by realitix** [comment]
It seems to work with

```
mymemoryview = MyMemoryView() # pointer on a 24 bytes buffer
vertices = np.array([0, -0.5, 0.5, 0.5, -0.5, 0.5], dtype=np.float32)
wrapper = np.array(mymemoryview, copy=False) # Wrap my memoryview into a numpy array without copy
np.copyto(wrapper, vertices.view(dtype=np.uint8), casting='no')
```

I will do some more check, then I will close this issue. Thanks @shoyer

**Comment by realitix** [comment]
It works ! Thanks
