### ISSUE TITLE
BUG: np.ma.median returns wrong values for even number of elements

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#8409]
Tests in astropy (https://github.com/astropy/astropy/issues/5629) uncovered a bug in `np.ma.median` for the case where the median should be the mean of the two entries nearest the median:
```
np.ma.median(np.ma.MaskedArray([1., 1.]))
# 2.0
np.ma.median(np.ma.MaskedArray([1., 1., 1.]))
# 1.0
np.ma.median(np.ma.MaskedArray([0., 1., 1., 5.]))
# 2.0
```
The bug is not present in 1.11.2.

I have not yet investigated where the problem occurs, as it may be that this immediately rings a bell for @juliantaylor, who last seems to have committed to `np.ma.extras`

**Comment by charris** [comment]
Looks like a missing division by 2.

**Comment by charris** [comment]
Yep, the division on extras.py line 730 drops the result, https://github.com/numpy/numpy/blob/master/numpy/ma/extras.py#L730

@juliantaylor Heads up.

**Comment by mhvk** [comment]
Indeed, `np.ma.median(np.ma.MaskedArray([2., 2.]))` returns 4.

I think the culprit is a missing `out=s` [here](https://github.com/numpy/numpy/blob/master/numpy/ma/extras.py#L730)

...

Ah, I see you found the same. One thing not immediately clear to me is why here `s` is used directly while further down it is `s.data`.

**Comment by charris** [comment]
Yes, I wondered the same. I suspect the `s.data` form is correct.

**Comment by mhvk** [comment]
See #8414 for a fix.
