### ISSUE TITLE
Subtracting one to biggest uint64 casts to float

### ISSUE THREAD

**Issue by ddasilva** [numpy/numpy#8411]
I have the largest `uint64` in a variable, as type `uint64`. I was very surprised that when I subtracted one, this became a `float64`.

Is this a bug? If not, can someone explain this it to me?

```
In [1]: big = ~np.uint64(0)

In [2]: type(big)
Out[2]: numpy.uint64

In [3]: type(big - 1)
Out[3]: numpy.float64
```

Release info:
```
    full_version = '1.11.2'
    git_revision = 'bb6e3dc30016b89bf154f7d7fce4248e760bd40f'
    release = True
    short_version = '1.11.2'
    version = '1.11.2'
```

**Comment by pv** [comment]
This looks like a duplicate, search the bug tracker.

**Comment by ddasilva** [comment]
Thanks @pv 

https://github.com/numpy/numpy/issues/7126
https://github.com/numpy/numpy/issues/7409
