### ISSUE TITLE
Conflict eig() results between numpy and matlab

### ISSUE THREAD

**Issue by ray306** [numpy/numpy#8412]
```
C2 = np.array([[ 5, 10],[ 10, 33]])
[V2, P2] = np.linalg.eig(C2)
```
V2:
[ 1.79534947 36.20465053] 
P2:
[[-0.95229551 -0.30517743]
[ 0.30517743 -0.95229551]]

Matlab's eigenvector result is different from Numpy's:
[[-0.95229551 0.30517743]
[ 0.30517743 0.95229551]]

**Comment by pv** [comment]
Both results are correct.

**Comment by ray306** [comment]
@pv 
But eigenvalue recheck of Numpy's failed:
```
C2 = np.matrix([[ 5, 10],[ 10, 33]])
[V2, P2] = np.linalg.eig(C2)
print(V2)
print(P2*C2*P2.T)  # PCP`
```
[  1.79534947  36.20465053]
[[ 13.42011334  16.27466942]
 [ 16.27466942  24.57988666]]

Matlab's result is correct:
```
P3 = np.matrix([[-0.95229551, 0.30517743], [ 0.30517743, 0.95229551]])
print(V2)
print(P3*C2*P3.T) 
```
[  1.79534947  36.20465053]
[[  1.79534947e+00  -4.82620511e-08]
 [ -4.82620521e-08   3.62046506e+01]]

**Comment by pv** [comment]
No, the results are correct. Please read the documentation.

**Comment by pv** [comment]
In particular, your transposes are the wrong way around.

**Comment by seberg** [comment]
I trust Pauli that this is just a misunderstanding of the details.
