### ISSUE TITLE
Problems with matplotlib colorbar when using keyword 'extend' for contourf

### ISSUE THREAD

**Issue by AnkitBarik** [numpy/numpy#8422]
Matplotlib version: 2.0.0rc2+2827.gab98852
Python version: 2.7.6
Compiler: gcc
Platform: Linux

While trying to reproduce the output from documentation:

http://matplotlib.org/examples/api/colorbar_only.html

I get the expected output, using **numpy version 1.11.3** (installed using pip):

![figure_1-2](https://cloud.githubusercontent.com/assets/13730345/21504902/f8f13f64-cc62-11e6-86b6-63dfb5ac7acf.png)

However, with **numpy version 1.13.0.dev0+2498b74** (installed from source both manually and using pip with same result), I get:

```python

/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py:2888: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=0.5, right=0.5
  'left=%s, right=%s') % (left, right))
```

![figure_1-1](https://cloud.githubusercontent.com/assets/13730345/21504936/34e000f0-cc63-11e6-93a4-f945e4c95014.png)

The issue has also been opened on matplotlib: [#7686](https://github.com/matplotlib/matplotlib/issues/7686)

**Comment by eric-wieser** [comment]
Following the breadcrumbs, it looks like this was fixed in #8617, so closing...
