### ISSUE TITLE
eigh / eigvalsh returns incorrect results

### ISSUE THREAD

**Issue by marekyggdrasil** [numpy/numpy#8429]
example that reproduces the problem

```python
from numpy import zeros, matrix
from numpy.linalg import eigvalsh
d = matrix(zeros([4,4]), dtype=complex)
for i in range(0, 4) :
    for j in range(0, 4) :
        d[i,j] = 1/4.0
eigenvals = eigvalsh(d)
print eigenvals
```

outputs

```
[ -1.58250139e-16+0.j   0.00000000e+00+0.j   1.94722604e-17+0.j
   1.00000000e+00+0.j]
```

expected output would be

```
[1, 0, 0, 0]
```

from Volfram Alpha

<img width="566" alt="screen shot 2016-12-30 at 9 18 44 am" src="https://cloud.githubusercontent.com/assets/8202674/21562654/d45a11ca-ce7a-11e6-80b0-c72e98235731.png">

from Mathematica

<img width="206" alt="screen shot 2016-12-30 at 10 28 52 am" src="https://cloud.githubusercontent.com/assets/8202674/21562661/e4677b5c-ce7a-11e6-951b-980c4aa9319d.png">

my environment

```
$ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.8.0rc1'
>>> np.intp(0).dtype.itemsize
8
```

I researched issues with same keywords but they turn out not to be that much related

https://github.com/numpy/numpy/issues/6378
https://github.com/numpy/numpy/issues/6008
https://github.com/numpy/numpy/issues/6002
https://github.com/numpy/numpy/issues/2424

I appreciate some feedback and comments, thanks in advance!

**Comment by marekyggdrasil** [comment]
```python
from numpy import zeros, matrix
from numpy.linalg import eig
d = matrix(zeros([4,4]))
for i in range(0, 4) :
    for j in range(0, 4) :
        d[i,j] = 1/4.0
eigenvals, eigenvect = eig(d)
print eigenvals
print eigenvect
```

Changing type from complex to real and using eig instead of eigh or eigenvalsh reproduces same results as Volfram Alpha / Mathematica. Not sure enough but I guess that is enough to close the issue.

**Comment by chandrashekar10** [comment]
Hi Marek,   I have a question,  you have changed the matrix d from 

d = matrix(zeros([4,4]), dtype=complex)
to
d = matrix(zeros([4,4]))

in the latest version.  Does this mean that the density matrix is not complex anymore ?  
If so I  would prefer
to keep the earlier version where some of the density matrix elements are complex (that is the most common thing in quantum information theory).
