### ISSUE TITLE
pip installation of numpy fails on windows when username contains accented character

### ISSUE THREAD

**Issue by aaaidan** [numpy/numpy#8430]
Recently I successfully installed numpy 1.11.2 on windows 10 using pip. My colleague, attempted to install the same version (also on windows 10), but got an error:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 47: invalid continuation byte`

Given it worked for me, but not for Frédéric, it seems likely to be to do with the accented e in his username.

Here's the [full error chain](https://github.com/numpy/numpy/files/679192/pip.install.numpy.error.txt).

Please let me know if this isn't the right place to report this. This might be an issue with pip, rather than numpy, but pip seems to install many other packages fine (nltk, colorama, for example). I'm an experienced developer, but a python noob, so any info would be gratefully received.

**Comment by charris** [comment]
Hmm, probably the terminal isn't utf-8 enabled? ISTR that windows uses latin-1 by default for most locales and that powershell is preferred if you want to change it to utf-8. I don't know if there is a way for pip to determine what the encoding is.

**Comment by aaaidan** [comment]
Thanks @charris - we have tried `chcp 65001`, which sets the terminal codepage to UTF-8, but to no avail.

**Comment by charris** [comment]
Google shows a couple of hits for this problem related to pip. Are you using the latest pip version?

**Comment by aaaidan** [comment]
More research suggests this is a pip issue, and that we're [not](https://github.com/pypa/pip/issues/4110) [alone](https://github.com/pypa/pip/issues/3992) in having problems with non-ascii characters in usernames.

(I'll close this soon, unless anyone has anything else to add.)

**Comment by aaaidan** [comment]
@charris Yep, latest pip (9.0.1)

**Comment by njsmith** [comment]
Yeah, those exceptions are all coming from pip code, rather than numpy code... try running `python setup.py install` directly instead of using `pip`, I guess?

Though, I am a bit confused that you seem to be building numpy from source -- is that on purpose? `pip install numpy` should be giving you a pre-compiled wheel...

**Comment by njsmith** [comment]
Oh, never mind, I see that you're using python 3.6, and there isn't any pre-compiled wheel for 1.11.2 + 3.6.

**Comment by aaaidan** [comment]
Thanks for your help @njsmith and @charris. The ... uh, pragmatic solution we opted for was to create a new user on Fréd's machine (without non-ascii characters). Not ideal, but it got us unstuck.
