### ISSUE TITLE
Python3 ctypes: fopen spurious failure

### ISSUE THREAD

**Issue by hainest** [numpy/numpy#8438]
I have a project using ctypes to interface with an external C library that manages a `FILE*`. However, the call to `fopen` fails with `errno`=2 (No such file or directory) even when the mode is 'w'.

### foo.c
	#include <errno.h>
	#include <stdio.h>
	#include <string.h>
	
	static FILE *fd = 0;
	void foo_py_open(char const *filename, char const *mode) {
		printf("foo_py_open received: %s (%lu) and %s (%lu)\n", filename, strlen(filename), mode, strlen(mode));
		fd = fopen(filename, mode);
		if (errno != 0)
			fprintf(stderr, "fopen failed: %s\n", strerror(errno));
	}
	void foo_py_close() { if (fd) fclose(fd); }

### foo.py
    import ctypes
    import numpy.ctypeslib as npct
    
    # This doesn't work. print() must be called after load_library
    # print()
    
    lib = npct.load_library("libfoo", "")
    cfname = ctypes.c_char_p(bytes('out.txt', 'utf-8'))
    cmode = ctypes.c_char_p(bytes('w', 'utf-8'))
    
    # These all work
    # print()
    # print('\n', sep='', end=None)
    # print('', sep='', end='\n')
    # print('', sep=None, end=None)
    
    # This fails
    # print('', sep='', end='')
    
    lib.foo_py_open(cfname, cmode)
    lib.foo_py_close()

***

The C was compiled using gcc-6.2

	gcc -std=c99 -Wall -Wextra -O3 -fPIC -c foo.c -o foo.o
	gcc -shared -Wl,-soname,libfoo.so -o libfoo.so foo.o

As noted in the comments, the current work-around is to place a newline character into the stdout stream *after* calling `numpy.ctypeslib.load_library`.

**Python3**
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux

Note that the example code is compiled with a newer, but binary-compatible version of gcc.

**NumPy**
np.version.full_version = '1.11.0'
np.version.git_revision = '4092a9e160cc247a4a45724579a0c829733688ca'

**OS**
Linux Mint 18 Sarah
kernel 4.4.0-53-generic

**Comment by pv** [comment]
Pretty unlikely this has to do with Numpy, given that load_library
simply does "return ctypes.cdll[libpath]"

**Comment by WarrenWeckesser** [comment]
@pv is correct, this has nothing to do with NumPy.

From https://www.man7.org/linux/man-pages/man3/errno.3.html:

```
   errno
       The value in errno is significant only when the return value of
       the call indicated an error (i.e., -1 from most system calls; -1
       or NULL from most library functions); a function that succeeds is
       allowed to change errno. [...]
```

You are inspecting `errno` after calling `fopen`, but you haven't first checked that `fopen` failed.  If `fopen` succeeded, `errno` is not necessarily valid.

A corrected version of your C function is
```
void foo_py_open(char const *filename, char const *mode) {
    printf("foo_py_open received: %s (%lu) and %s (%lu)\n", filename, strlen(filename), mode, strlen(mode));
    fd = fopen(filename, mode);
    if (fd == NULL) {
        fprintf(stderr, "fopen failed: %s\n", strerror(errno));
    }
}
```
