### ISSUE TITLE
Let histogram take both weights and automatic bins for some estimators

### ISSUE THREAD

**Issue by dstansby** [numpy/numpy#8450]
For the estimators that only rely on the number of datapoints (eg. `'sqrt', 'sturges', 'rice'`) supplying both `bins` and `weights` should be possible.

Currently if you try to supply a string for `bins` to automatically choose the number of bins, and also supply `weights`, numpy throws this error:

```
  File "/home/dstansby/miniconda3/lib/python3.5/site-packages/numpy/lib/function_base.py", line 516, in histogram
    raise TypeError("Automated estimation of the number of "
TypeError: Automated estimation of the number of bins is not supported for weighted data
```

**Comment by eric-wieser** [comment]
What should `sqrt` do with weights? Use `sqrt(weights.sum())`? Is the implied default `weights = 1/n` or `weights = 1`?

I think some thought is needed if there's a well-defined extension of any of these weighting methods

**Comment by dstansby** [comment]
Not really sure what I meant here any more, so closing.
