### ISSUE TITLE
dtype kwarg for numpy.random methods

### ISSUE THREAD

**Issue by jwittenbach** [numpy/numpy#8451]
Currently, it looks like only `numpy.random.randint` allows the user to specify the dtype when construction a random array. It would be great to extend this option to the other methods as well, to avoid needing to call `astype` after construction.

**Comment by shoyer** [comment]
NumPy's functions from different distributions are all written in fixed double precision:
https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/distributions.c

@rkern may have a better sense of how difficult this is but it looks fairly non-trivial to me.

**Comment by rkern** [comment]
There are two ways to implement this request. There is the "native" version, where we only use `float32` float values and only pull enough random bits to create each `float32`. Then there is the "poor-man's" version, where we go ahead and use the existing `float64` routines and just downcast the resulting values into a `float32` output array as they are created. The "poor-man's" version might not be as good in terms of time-efficiency (if generating the raw random bits are a significant bottleneck), but is space-efficient, which is often what people are after.

For `random_sample()`, it would be useful and straightforward to implement a "native" solution. For most of the other distributions, I think the "poor-man's" solution would be sufficient; implementing "native" versions of these would be too annoying for little benefit. In between, I think that a case could be made for making "native" versions of the `standard_*` distributions as those are often building blocks where raw speed might be as important as the space savings.

**Comment by rkern** [comment]
Either way, it's going to be at least as difficult to implement as `randint()`, which took a long time to get in.

**Comment by bashtage** [comment]
There are pretty big gains for 32-bit versions of the standard generators:

I implemented these in `randomstate` for normals, uniforms, gammas and exponentials

```
                      64-bit     32-bit
random_sample          69 ms      35 ms
standard_normal       592 ms     190 ms  
standard_gamma        952 ms     189 ms 
standard_exponential  921 ms     403 ms 
```

`random_sample` performs exactly as expected, 50% reduction in time.  `normal` and `gamma` both do much better.

**Comment by mattip** [comment]
The new random API provides a dtype kwarg. Please reopen if I misunderstood.
