### ISSUE TITLE
numpy.load fails loading large arrays on windows due to integer overflow

### ISSUE THREAD

**Issue by tolga-b** [numpy/numpy#8469]
Hi,
The problem is as follows:
I have an array of size (1281024, 4096) (5247074304 elements) of type float32.
I can save and load this array using numpy.save and numpy.load functions in Ubuntu 14.04 64bit, however when I try to load the same array in Windows 64bit I get an error:
"Total size of the array must be unchanged" in numpy/lib/format.py.

I found out that the read count is incorrectly set in numpy.multiple.reduce at line 626 in format.py due to int32 overflow for any array with larger than 2,147,483,647 elements (default C int is 32bit in 64bit Windows unlike Linux). Which in turn causes only a part of the file to be read and therefore setting the shape fails. Just fixing the read count caused the read array to contain a lot of "nan" values, so there must be other parts that are broken as well. 

I think this should be included in documentation if there is a file limit for numpy.save.

I am using numpy version 1.11.1 with latest Anaconda distribution.

**Comment by charris** [comment]
Should be fixed by #7598.
```
commit da668fc74653e5caae9f741461c4d20f9df6e5c1
Author: drasmuss <daniel.rasmussen@appliedbrainresearch.com>
Date:   Mon May 2 17:06:26 2016 -0400

    BUG: Cast size to int64 when loading from archive
    
    Prevents overflow errors for large arrays on systems
    where the default int type is int32.
```

Looks like that didn't get backported, unfortunately. Numpy 1.12.0 should be out this weekend.
