### ISSUE TITLE
Numpy contains shebang pointing to /usr/bin/python which are problematic

### ISSUE THREAD

**Issue by ssalonen** [numpy/numpy#8472]
Hi

We are packaging numpy pre-installed in a virtualenv using a rpm. RPM has a "convenient" feature to automatically scan for script files with shebang and adding those as requirements of the resulting rpm. For more information, see [this blog post](http://www.legendiary.at/2013/03/20/rpmbuild-shebang-auto-required-packages/).

Most of the numpy scripts use

````bash
#!/usr/bin/env python
````

which rpm resolves to whatever is in the PATH.

However, some of the packages point to hard-coded path of python:
````bash
$ grep '^#!' **/*.py|grep -v '/usr/bin/env python'
numpy/core/tests/test_arrayprint.py:#!/usr/bin/python
numpy/distutils/conv_template.py:#!/usr/bin/python
numpy/distutils/from_template.py:#!/usr/bin/python
````

I would propose that the above scripts would be changed to use `#!/usr/bin/env python`.

This change would make the rpm process resolve python and bash using whatever is in the path. For example, with CentOS 6, the system python (in `/usr/bin/python`) is python 2.6, although the `python` in PATH could very well be `python2.7` or newer. In our case the virtualenv is activated during the build, and thus `#!/usr/bin/env python` would resolve to the correct interpreter.

The additional benefit is that the scripts are more cross-platform.

I'm willing to submit a pull requests if you agree with the fix?

Best,
Sami Salonen

Scipy issue regarding the same matter: https://github.com/scipy/scipy/issues/6961
Pandas issue regarding the same matter: https://github.com/pandas-dev/pandas/issues/15131

**Comment by charris** [comment]
Go for it.

**Comment by ssalonen** [comment]
PR submitted with the proposed changes.
