### ISSUE TITLE
Runtime warning for "where" ?

### ISSUE THREAD

**Issue by sparseinference** [numpy/numpy#8473]
This was ok in previous versions of numpy to guard against domain errors in UFuncs:

```
x = zeros((10,)) 
x[5]=10.0 
where(x > 0, log(x), 0)
```

in version 1.11.3 there is now a warning:

> /home/peter/python36/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: divide by zero encountered in log

**Comment by juliantaylor** [comment]
`where` is not lazy, so it will still evaluate the log on all values and the domain error is expected.
You need to ignore the error via `np.errstate`

**Comment by juliantaylor** [comment]
r = np.log(x, where=x>0)
    r[x<=0] = 0

should also work

**Comment by sparseinference** [comment]
@juliantaylor Thanks .. but isn't this new behaviour? 
I don't recall a runtime warning in 'where' for this exact same code in over 10 years of using numpy.

**Comment by juliantaylor** [comment]
the error is generated by the system math library, so it is platform dependent, some generate others don't

**Comment by sparseinference** [comment]
I guess I never thought that 'where' evaluates everything. That's a major performance problem.

**Comment by sparseinference** [comment]
@juliantaylor  BTW: Thanks for clearing up my misunderstanding!

**Comment by filipre** [comment]
I believe the error warning is a bit confusing for the user. It basically implies that you did not handle the case splitting correctly even though you actually did. After all, the whole point of `np.where` is to avoid running into illegal math expressions. I know that you can suppress the warning but that does not change the fact that the error message is misleading in this special case. 
Can we think about reopening this issue?

>I guess I never thought that 'where' evaluates everything. That's a major performance problem.

I'd be interested whether this is actually true or whether it might be the other way round, thus this behavior in the first place.
