### ISSUE TITLE
Numerical errors with numpy.linalg.eig

### ISSUE THREAD

**Issue by Kaba2** [numpy/numpy#8481]
The following example demonstrates numerical issues with numpy.linalg.eig with numpy installed from either numpy‑1.11.3+mkl‑cp35‑cp35m‑win32.whl or numpy-1.12.0+mkl-cp35-cp35m-win32.whl:

    import numpy
    
    a = 7599.9393278410407
    # Can also be changed to positive.
    b = -7.198527976045102e-13
    # Differs from a only in the last two digits.
    c = 7599.9393278410489
    
    # Symmetric matrix.
    A = [[a, b], [b, c]]
    
    print(A)
    
    s, u = numpy.linalg.eig(A)
    
    print(s)
    print(u.T.dot(u))

Since u is orthogonal, the product u^T u should be close to identity. However, the corresponding matrix is 

    [[ 1.         -0.08760483]
     [-0.08760483  1.        ]]

Matrix A is close to being diagonal. In contrast, Matlab 2016a gives a correct answer with this example.

**Comment by pv** [comment]
The calculations in both Numpy and Matlab are both done by LAPACK, so 
this is a LAPACK issue.
.
The difference between the two is on the assumption of matrix symmetry, 
which for numpy must specify explicitly by using `eigh` whereas Matlab 
selects the symmetric routine itself.

**Comment by pv** [comment]
Without assumption of symmetry, there probably are matrices within 
relative floating point epsilon that have very non-orthogonal right 
eigenvectors.
.
If so, there's probably no bug in LAPACK here --- it's just a matter of 
the nonsymmetric eigenproblem being numerically unstable.

**Comment by charris** [comment]
@Kaba2 Works for me with eigh. If this is still a problem, please reopen.
