### ISSUE TITLE
In Python 3, BytesIO input for numpy.genfromtxt does not work as the examples say

### ISSUE THREAD

**Issue by geoalchimista** [numpy/numpy#8498]
The examples provided in https://docs.scipy.org/doc/numpy/user/basics.io.genfromtxt.html cannot work in Python 3 due to a TypeError. I got the following error message.
```
>>> data = "1, 2, 3\n4, 5, 6"
>>> np.genfromtxt(BytesIO(data), delimiter=",")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' does not support the buffer interface
```

It turns out that the input string needs to be cast to a bytestring for it to work properly. I hope the manual page [Importing data with `genfromtxt`](https://docs.scipy.org/doc/numpy/user/basics.io.genfromtxt.html) can be updated so that it states this issue properly.
```
>>> data = "1, 2, 3\n4, 5, 6"
>>> np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=",")
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])
```

**Comment by lravindr** [comment]
The string is treated as python 2.x is treated as a string type and a byte array type. In python 3.x plaintext is only as a string type. Some of the examples 1, 2 would not work in Python 3.x interpreters. 

I would like to contribute towards fixing this documentation. This would be my first contribution. We should fix the documentation to each of the example pages or add to the FAQ for possible issues when moving between the two interpreters. Which one would be the preferred method?
