### ISSUE TITLE
Mode function for ndarray

### ISSUE THREAD

**Issue by vaastav** [numpy/numpy#8499]
I was wondering if there was any particular reason as to why there doesn't exist a mode function like the mean and median functions that work on ndarray. I feel that it should be provided.
( On that note, if I wanted to contribute this function to numpy then what would be a good starting point for me?)
Thanks in advance

**Comment by rgommers** [comment]
There's ``scipy.stats.mode`` which should do what you want. Mode is much less common than mean/median, so we won't move that into NumPy.

**Comment by leferrad** [comment]
That doesn't make sense to me, since it is something that can be computed from functions already implemented in NumPy, and it's not nice to add Scipy as a dependency in a project just for a couple of methods not covered by NumPy. However, a workaround (at least for 1D arrays) for this can be just `np.argmax(np.bincount(array))` (extracted from https://stackoverflow.com/a/6252400).

**Comment by mayowaosibodu** [comment]
> That doesn't make sense to me, since it is something that can be computed from functions already implemented in NumPy, and it's not nice to add Scipy as a dependency in a project just for a couple of methods not covered by NumPy. However, a workaround (at least for 1D arrays of ints) for this could be just `np.argmax(np.bincount(array))` (extracted from https://stackoverflow.com/a/6252400).

This also feels very surprising to me. It also feels like a relatively trivial function to implement, and so I'm not sure why there's so much of a reluctance to implement it. It's not like it's going to bloat the NumPy codebase or anything

**Comment by adityaraute** [comment]
> it's not nice to add Scipy as a dependency in a project just for a couple of methods not covered by NumPy. 

I agree. Numpy should add a `mode` function to cover all three measures of center.
