### ISSUE TITLE
BUG: Object array dealloc causes total refcount to increase due to INCREF of self (no actual leak occurs)

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#8503]
Running the following code in Python 3.6 configured `--with-pydebug`, shows that `numpy.array(['a'], 'O')` is leaking references:

```
$ cat x.py
import sys
import numpy

n = sys.gettotalrefcount()
for i in range(100):
    a = numpy.array(['a'], 'O')
del i, a
print(sys.gettotalrefcount() - n)

$ python3.6 x.py
104
```

(Changing 100 to 1000 in the loop range results in 1004.)

**Comment by charris** [comment]
Just to be sure,  which version of numpy?

**Comment by abalkin** [comment]
I tested with numpy-1.11.3 and numpy-1.12.0.  Will soon know about latest github clone.

**Comment by abalkin** [comment]
Reproduced with 1.13.0.dev0+20d6ca1.

**Comment by eric-wieser** [comment]
I don't have a `--withpydebug` installation. Does this happen with:

```python
O = np.dtype(np.object_)
for i in range(100):
    a = numpy.array([], O)
```

**Comment by abalkin** [comment]
Yes.

```python
>>> sys.gettotalrefcount()
255661
>>> for i in range(10000):
...     a = numpy.array([], O)
...
>>> sys.gettotalrefcount()
265661
```

(note the increase from 25k to 26k references)

**Comment by seberg** [comment]
It likely does not leak memory, just references. But a note: It does not have to be `[]` it can also be a singleton such as `1` (which should take a much shorter code path). There is one thing that might be a hint ,or may be unrelated, and that is that `np.array(np.array(1), 'O')` loses twice the references, even though the `np.array(1)` call does not lose any reference.

**Comment by seberg** [comment]
I am giving up for now. Since I iterated through `gc.get_objects` (not sure what this all gives) and checked their refcounts. I guess the leaking reference is for a non-gc object? For all I know, I bet on some interned string or so right now, but who knows, could be about anything. For me the test suit does not run through because of errors in exception settings (using python3.6-dbg) as well on master.

**Comment by seberg** [comment]
Hmmm, I had hoped one of the current fixes might have patched this over. But I can confirm this is still the case on master.

**Comment by seberg** [comment]
I think I found it. Should have seen it before. It is not actually leaking anything at all, just the total refcount is wrong! Should have noticed because Jaime referenced it in some other issue.

During deallocation, object arrays INCREF themselves, but never DECREF "because they are already being removed" (as per comment).

I am not sure if they should DECREF themself, never INCREF there or do something else.

**Comment by seberg** [comment]
So, not surprisingly adding a DECREF segfaults. Removing the INCREF seems to work, but I wonder whether there was a reason for it being there.

**Comment by seberg** [comment]
The commit adding it is 7e4a505ceebc45e4bc90cf5093b6f59aa1125be8, but it is so old I doubt it is worth looking at it.

The question is: Is there any reason (at least nowadays), why one would increment the reference count on `self` during dealloc? As far as I can tell, at `dealloc` time, nobody can resurrect the object anymore, nor should they really access it, so I do not see why an INCREF would help. It might be it was just an accident during debugging?

**Comment by mattip** [comment]
The problem is that the underlying object's dealloc could call back to something in the ndarray, which is no longer valid. Although I am not sure incrementing the refcount after it has reached 0 is a valid way of keeping the object alive.

**Comment by mattip** [comment]
We should use a python3.4 and up [finalizer](https://www.python.org/dev/peps/pep-0442/) in __del__ (or tp_finalize) to decref the objects instead of tp_dealloc

**Comment by seberg** [comment]
Can't say I understand the details here, would be nice if someone who knows the details of `dealloc` in combination with `INCREF` (holding on to `self` temporarily) could chime in.

In any case, there is definitely *no* leak here, only the total refcount is off due to this INCREF.

**Comment by mattip** [comment]
The `writebackifcopy` check should also move to a finalizer.

**Comment by seberg** [comment]
I am not sure an `ndarray` can actually be resurrected? But a quick look, sounds like that is a solution. Sounds fine if we add this only to Python 3, or 1.17, it only helps debugging refcounts really.

**Comment by mattip** [comment]
Theoretically, I have never done it in practice. I guess we could add a `tp_finalize` method and use gdb to make sure it is called before `tp_dealloc`

**Comment by seberg** [comment]
Identical to gh-9600. This has been fixed recently, object arrays will not "leak" total reference count on dealloc anymore.
