### ISSUE TITLE
Invalid version string for development versions

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#8512]
I am just setting up a travis cron job to test the wheel building repo.

The tests fail, because of the numpy version string of the wheel:

```
======================================================================
FAIL: test_numpy_version.test_valid_numpy_version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/venv/local/lib/python2.7/site-packages/numpy/tests/test_numpy_version.py", line 19, in test_valid_numpy_version
    assert_(res is not None, np.__version__)
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 90, in assert_
    raise AssertionError(smsg)
AssertionError: 1.13.0.dev0+
```

https://travis-ci.org/MacPython/numpy-wheels/jobs/193916296#L366

Is there a reason to have this invalid version string for development versions?

**Comment by charris** [comment]
Version should be  something like `'1.12.0.dev0+54abe00'`, so something is probably wrong with the wheels  version.

**Comment by matthew-brett** [comment]
Aha - thanks for the pointer - I'll explore further.

**Comment by rgommers** [comment]
Looks like a sign of git not working when building from a git repo. That should never happen for wheels. Still, the ``+`` should be removed from this version string, needs a minor change around line 126 of ``setup.py``.

**Comment by matthew-brett** [comment]
I believe the problem is a version of https://github.com/matthew-brett/multibuild/issues/11.  I believe that pip likes to copy the directory it is building from to some crazy location; when numpy is a submodule, as it is here, then git commands to fetch the version will fail during the pip build.    There's a pull request from a brave soul to try and fix this in the general case, at https://github.com/matthew-brett/multibuild/pull/12 . For now, I just switched to using `python setup.py bdist_wheel` instead of `pip wheel` : https://github.com/MacPython/numpy-wheels/commit/f3ac2bb0a2eed1a66e5187c4daf976e767db8aa1

**Comment by rgommers** [comment]
True, the pip copy behavior is braindead. Still is the numpy bug I described though, because ``1.13.0.dev0`` is a valid version string (says PEP 440) while ``1.13.0.dev0+`` isn't.

**Comment by rgommers** [comment]
fixed the `dev0+` thing, so closing
