### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [numpy/numpy#8520]
I quickly wanted to report some broken links in the first pages of the numpy documentation:

On the start page of NumPy v1.12 Manual (https://docs.scipy.org/doc/numpy/index.html)

* "Guide to NumPy" links to http://www.tramy.us/ which does not contain any information
* "NumPy Documentation Marathon" directs to https://docs.scipy.org/numpy/ which is non existing (404)
* "NumPy Documentation Wiki" links to https://docs.scipy.org/numpy/ which is non existing (404)

On the about page (https://docs.scipy.org/doc/numpy/about.html)

* 1st line link NumPy http://www.scipy.org/NumpPy/ does not exist.
* "Old NumPy Trac (no longer used)" directs to http://projects.scipy.org/numpy/ which is obsolete

**Comment by charris** [comment]
Thanks for finding those.

- Not sure what the "Guide to NumPy" should link to
- The documentation marathon is defunct, so that reference should be removed.
- The Wiki is also extinct, so that could also be removed.
- Not sure what http://www.scipy.org/NumpPy/ should refer to, if anything
- The Trac reference (and any others) should be removed as its contents were merged on Github

@rgommers Comment?

**Comment by charris** [comment]
@ImportanceOfBeingErnest PR welcome if you want to put one together.

**Comment by ImportanceOfBeingErnest** [comment]
@charris Sorry, I can't dig that deep into the stuff. I just wanted to let you guys know about the broken links.

**Comment by rgommers** [comment]
> @rgommers Comment?

I can have a look in the weekend and fix that all up.

**Comment by nicoguaro** [comment]
Regarding the _Guide to NumPy_ there are two urls hosted in universities:

- http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf

- http://ftp.stu.edu.tw/pub/FreeBSD/ports/distfiles/numpybook.pdf

Since the book is now in public domain, I uploaded a version in the Internet Archive

    https://archive.org/details/NumPyBook

**Comment by pv** [comment]
The book is mainly of historical interest, as its contents are 
essentially in the numpy documentation currently.
.
Its sources are also available in Numpy's git history,
https://github.com/numpy/numpy/tree/48c77a64aba109de54d90f103203f1990325c37c/doc/numpybook

**Comment by morenoh149** [comment]
@pv so the reference should be removed altogether? The footer is still broken as of now.

**Comment by mattip** [comment]
The documentation has been updated and should be correct in the next release. You can preview the [corrected documentation](http://www.numpy.org/devdocs/index.html). Leaving this open until the actual release, since we get many reports of the broken links.

**Comment by mattip** [comment]
Now that 1.15 is out we can close this, thanks
