### ISSUE TITLE
determinant of a zero matrix raises RuntimeWarning with mkl/osx

### ISSUE THREAD

**Issue by pavoljuhas** [numpy/numpy#8529]
After updating to NumPy 1.11.3 calculation of determinant of a zero matrix gives correct result, but it also raises RuntimeWarning about "invalid value in det" as follows:

```python
>>> from numpy.linalg import det
>>> det([[0, 0], [0, 0]])
/Users/pjuhas/arch/anaconda/envs/dev35/lib/python3.5/site-packages/numpy/linalg/linalg.py:1776: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
0.0
```

I see this with Anaconda Python 3.5 on Mac OS X, where NumPy is built with `mkl 2017.0.1`.  The warning happens also on 64-bit Linux version of Anaconda Python 3.5.

Running `git bisect` on a local build showed that the warning got introduced in b900860d5d5ef59812ecdbf6ab93d5d3b127084d.

**Comment by pv** [comment]
possibly, the invalid fp flag is raised by mkl. potentially the code
should ignore fp exc raised by lapacks, or possibly this is a (minor)
mkl bug

**Comment by boegel** [comment]
Is there some kind of workaround for this problem outside of `numpy`? Or maybe a patch that can be applied to fix this issue in numpy?

**Comment by boegel** [comment]
The problem I'm hitting is worse though, since it's a `FloatingPointError` rather than a warning:

```
  ...
    if numpy.linalg.det(A) < 0:
  File "/prefix/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/linalg/linalg.py", line 1821, in det
    r = _umath_linalg.det(a, signature=signature)
FloatingPointError: invalid value encountered in det
```

**Comment by njsmith** [comment]
@boegel: that's when doing `np.det` on an all-zero matrix using anaconda numpy with mkl on MacOS?

**Comment by boegel** [comment]
Close: I'm using a numpy built from source, on top of Intel MKL and Intel compilers, on Linux.

MKL and `np.det` are the common factor here.

**Comment by njsmith** [comment]
@boegel: I think the reason you're getting an exception instead of a warning is that you (or some library you're loading) are calling `np.seterr` to request that this warning be converted into an exception.

As for the underlying issue, I guess there isn't much that can be done except ignoring fp flags from lapack... Do we know of any situations where lapack setting these flags actually indicates a real error that isn't also indicated some other way? It seems unlikely to me.

**Comment by charris** [comment]
I believe we find the determinant using an LU factorization, so the problem may arise there with zero pivots.

**Comment by boegel** [comment]
I'm seeing the same issue with older versions of numpy (1.11.0, 1.10.4), so I'm not sure this is related to a change in numpy at all, it's just some kind of mismatch between recent versions of MKL and numpy?

@njsmith How would you ignore these fp flags from LAPACK exactly? Is there some change that can be made in the code that calls `np.det` to dance around this?

**Comment by njsmith** [comment]
> How would you ignore these fp flags from LAPACK exactly? Is there some change that can be made in the code that calls np.det to dance around this?

Well, you could disable the error/warning like:
```python
with np.errstate(invalid="ignore"):
    np.det(...)
```

But what I was suggesting was a change inside the LAPACK wrapper code in numpy. The simplest way would be to explicitly clear the fp flags after calling LAPACK and before returning from the gufunc core loop.

**Comment by seberg** [comment]
Going to close this for now until reported again.  It seems like a small bug probably, but in MKL.  Unless we want to blanket ignore FPEs from blas.

OpenBLAS lapack has a similar issue on M1 (which is a clang compiler issue really probably...)
