### ISSUE TITLE
np.linalg.norm()  is ~4x slower than standard library on small arrays

### ISSUE THREAD

**Issue by Jakobovski** [numpy/numpy#8532]
```
array = np.array([randint(0,100), randint(0, 100)])
with timeit_context('np'):
    for i in range(10000):
        np.linalg.norm(array)

with timeit_context('not np'):
    for i in range(10000):
        math.sqrt(randint(0,100)**2 + randint(0, 100)**2)

```

[np] finished in 50.801 ms
[not np] finished in 13.0641 ms

Here we see numpy took about 4x as long to finish the 10,000 calculations

**Comment by pv** [comment]
This is unsurprising for small arrays.

**Comment by Jakobovski** [comment]
It may be unsurprising but a 4x difference is pretty bad. I am wondering if there is any reasonable way to improve on this.

**Comment by person142** [comment]
Note that

```sqrt(x**2 + y**2)```

is not how one computes a norm--it will overflow unnecessarily if either of the components is large. The correct method is scaling by the larger component; i.e. if `x > y` one computes

```|x|*sqrt(1 + (y/x)**2)```.

 How do the timings look when you do that?

**Comment by jaimefrio** [comment]
I haven't looked into this particular case, but timings for such small arrays are typically dominated by constant overheads, i.e. I wouldn't be surprised if the timing for a 10 item array was almost the same as for your 2 item one. Which would mean there isn't much that can be done without a major rehaul of the core of numpy.

If this really bugs you, the source code for `norm` is [here](https://github.com/numpy/numpy/blob/maintenance/1.12.x/numpy/linalg/linalg.py#L2159). I don't see any obvious bottleneck, but feel free to see what you can come up with.

**Comment by charris** [comment]
Note that `randint(0, 100)` is a scalar, so no arrays are involved in the second case.

**Comment by godaygo** [comment]
It's normal to have 4x slowdown on simple function call, between `numpy` functions and python `stdlib` functions. In fact, your example compares a time of function call, and `numpy` functions have a little overhead, you do not have the necessary volume of computing where `numpy` can show his super speed.

**Comment by seberg** [comment]
Closing this, there are always small imrovements possible and as everyone says here: it really is unsurprising for very small arrays.
