### ISSUE TITLE
Feature: iscopy or isview attributes

### ISSUE THREAD

**Issue by pylang** [numpy/numpy#8534]
It seems we can verify whether an numpy object is a view or copy by inspecting the [`.base` attribute](https://stackoverflow.com/questions/11524664/how-can-i-tell-if-numpy-creates-a-view-or-a-copy).

Example via _From Python to Numpy_

```python
>>> Z = np.random.uniform(0,1,(5,,5))
>>> Z1 = Z[:3,:]
>>> Z2 = Z[[0,1,2], :]
>>> print(np.allclose(Z1,Z2))
True
>>> print(Z1.base is Z)
True
>>> print(Z2.base is Z)
False
>>> print(Z2.base is None)
True
```

However, after performing this comparison, it is still unclear if a returned `None` suggests the object is a view or copy.  Can we have an explicit attribute instead, e.g. `.iscopy` or `.isview`?  Example:

```python
>>> print(np.isview(Z1))
True
>>> print(np.isview(Z2))
False
>>> print(np.iscopy(Z2))
True
```

Unless there is a more modern approach to verifying views/copies, these options might reduce ambiguity on this ubiquitous topic.  Many thanks.

**Comment by eric-wieser** [comment]
When is this useful information?

**Comment by pylang** [comment]
A brief section in [From Python to Numpy](http://www.labri.fr/perso/nrougier/from-python-to-numpy/#views-and-copies) presents some rationales for distinguishing copies and views.  For large arrays, using views can preserve memory. See the reference for a detailed example.

**Comment by njsmith** [comment]
It is important to know whether an operation returns a copy or a view, but there's no useful way to implement a `iscopy` or `isview` attribute. For example, it's not uncommon for operations to make an internal copy and then return a view of the copy. To numpy this is a view, but for all practical purposes it should be treated as a copy.

I wish people would stop giving the advice to look at `.base`. It's just not reliable. If that book suggests it then I'd suggest filing a bug on the book.

I think `np.shares_memory` is what you're actually looking for.
