### ISSUE TITLE
numpy.dot (v1.12.0) causes signal 11 (SIGSEGV) fault within celery worker on macOSX Sierra

### ISSUE THREAD

**Issue by andrew0harney** [numpy/numpy#8535]
Running numpy.dot(a, b) causes a signal 11 (SIGSEGV) error.

This is with:
len(a) = 28781
len(b) = 100

System Configuration:
Python 3.5.2
numpy numpy-1.12.0 and numpy==1.11.2
celery==4.0.0
Processor: 3.1 GHz Intel Core i5
Memory 16 GB 2133 MHz LPDDR3

Additional info:

Memory profiling shows little usage and failure is immediate.  

This error only happens in celery and only on Mac. I have tested on ubuntu 16.04 and 16.10 where it appears to work fine.

**Comment by pv** [comment]
Probably due to the fact that Apple's Accelerate BLAS library crashes if 
used after fork. If so, I think there's another issue ticket. Apple has 
IIRC stated that they will not fix this bug in their library, so the 
only fix is to install Numpy not compiled with Apple's linalg library.

**Comment by mattip** [comment]
Closing, Accelerate is no longer in use
