### ISSUE TITLE
float128(0).item() returns numpy.float128

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#8547]
`float128` types cannot be represented in native Python.  The conversion method `.item()` returns a `numpy.float128`, contrary to documentation and to the behaviour for all other dtypes:

```
In [307]: type(float128(0).item())
Out[307]: numpy.float128
```

Not sure what the right approach here is; for the other dtypes that cannot be represented natively, [I don't like the approach either](https://github.com/numpy/numpy/issues/8546).

**Comment by seberg** [comment]
I think this is the best approach since there is no safe converesion, and you could use `float(...)` otherwise. Yes, its a bit strange, but I think raising an error is worse...

(We discussed this briefly on the triage meeting)
