### ISSUE TITLE
Numpy does not recognize overflow

### ISSUE THREAD

**Issue by david-hoffman** [numpy/numpy#8548]
It seems that numpy does not recognize the following overflow error:

```python
In [1]: import numpy as np

In [2]: data = np.array((65536, 65535), dtype=np.int32)

In [3]: np.geterr()
Out[3]: {'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [4]: np.cumprod(data)
Out[4]: array([ 65536, -65536], dtype=int32)

In [5]: with np.errstate(over="raise"):
   ...:     np.cumprod(data)
   ...:
```

No warnings or exceptions are raised

**Comment by MSeifert04** [comment]
The [function documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumprod.html#numpy-cumprod) contains an explicite note about that:

> Arithmetic is modular when using integer types, and no error is raised on overflow.

**Comment by seberg** [comment]
Closing as duplicate of gh-6753 (lots of integer overflow issues open).
