### ISSUE TITLE
MS Windows Defender reporting trojan SpursInt in downloads, Windows, wheel

### ISSUE THREAD

**Issue by GlennEric** [numpy/numpy#8549]
Windows Defender wouldn't let me open either  numpy-1.12.0-cp3-none-win_amd64.whl or the 32 bit version as well.  Reported the trojan SpursInt

**Comment by charris** [comment]
See #8397, seems to be a Windows problem.

**Comment by pv** [comment]
https://www.virustotal.com/en/file/84cec2549e94dd147a384d60d8ab342309f80c8e099b2325505a202cd3a764a5/analysis/
.
https://www.virustotal.com/en/file/778c8c5f734c47c0292c4df17cc7d5acb4957dd8972793b9c3a6b37a333f4be0/analysis/

**Comment by chaksridhar** [comment]
I also faced similar issue. Had to disable  "Windows  Real time Protection"  option in Windows-Defender setting to enable the file to be downloaded and accessed

**Comment by mattip** [comment]
closing, please reopen if it is still an issue
