### ISSUE TITLE
Document `np.clip` with `None` arguments

### ISSUE THREAD

**Issue by bluss** [numpy/numpy#8552]
Its behaviour (no boundary in that direction) is very useful, but is it intentional? If yes, docs for that would be nice.

```python
>>> np.clip([-2, -1, 0, 1, 2, np.inf], 0, None)
array([0, 0, 0, 1, 2, inf])
```

**Comment by charris** [comment]
Closed by #8558.

**Comment by bluss** [comment]
Awesome. I'll let you project members handling close when appropriate.

**Comment by WarrenWeckesser** [comment]
As @charris noted above, this was closed by https://github.com/numpy/numpy/pull/8558.
