### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by Jackels** [numpy/numpy#8556]
Numpy version 1.9.3

> a = numpy .ones((1, 1, 2, 3))
> b = numpy .ones((2, 3))
> c = [[[0], [1]], [[0, 1, 2]]]
> b[c] # works
> a[:, :, c] # crashes

The last line crashes with the message 
`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`

Now I only used slices and integer-arrays in the a-case.

**Comment by Dan-Patterson** [comment]
I am not sure what you mean by it works...

```
a
array([[[[0, 1, 2],
         [3, 4, 5]]]])
b
array([[0, 1, 2],
       [3, 4, 5]])
c
[[[0], [1]], [[0, 1, 2]]]
b[c]  # what does it return
array([[0, 1, 2],
       [3, 4, 5]])
b[c[0]]  # what does the first element in c return?
array([1])
b[c[0][0]]  # continue slicing the elements in c
array([[0, 1, 2]])
b[c[0][1]]  # continue slicing the elements in c
array([[3, 4, 5]])
b[c[1]]  # Now on to the second element of c
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: index 2 is out of bounds for axis 0 with size 2

```
Can you explain what you mean by than in terms of the slicing by elements demonstrated above?

**Comment by Jackels** [comment]
With works I mean it does not result in an IndexError, while it complains in the a-case that the input is invalid. But I only added an ':' to the input, which is valid( IndexError: only integers, slices (:) ... ), it says that the type of my input is wrong to begin with. But why is it then not an IndexError in the b case as well?

So either a and b should crash OR a and b should be valid, as far as input types go. It then can go on and crash afterwards when the indices try to access out of range data.

**Comment by seberg** [comment]
You are doing two different things, the first one is equivalent to `b[c[0], c[1]]]`, the second one (supposedly) to `a[:, :, np.asarray(c)]`.
Feel free ton continue the discussion.
