### ISSUE TITLE
Assigning values not working properly on arrays returned by meshgrid

### ISSUE THREAD

**Issue by dstansby** [numpy/numpy#8561]
On the current master branch, trying to assign a value to certain parts of an array returned by `meshgrid` isn't working properly:
```
import numpy as np
X = np.array([1.1, 2.2])
Y = np.array([3.3, 4.4])
x, y = np.meshgrid(X, Y)

print(x)
print(x[0, :])
x[0, :] = 0
print(x)
```
This prints
```
[[ 1.1  2.2]
 [ 1.1  2.2]]

[ 1.1  2.2]

[[ 0.  0.]
 [ 0.  0.]]
```
In this example only the top row of `x` should be set to zero, but the whole `x` array is set to zero. This is working correctly in version 1.1.12. This was discovered on https://github.com/matplotlib/matplotlib/issues/7686 and apparently was introduced by https://github.com/numpy/numpy/pull/5302

**Comment by eric-wieser** [comment]
Looks like `0 in x.strides` is true here, and the caveats of `np.broadcast_arrays` apply. Except the documentation does not warn for that here, so this is a bug

**Comment by dstansby** [comment]
But I would expect arrays returned by meshgrid to be accessed just like
normal arrays, which is what happens in the current released version of
numpy. Is this an intentional change that has been made to meshgrid for
1.1.13?

On 12 Feb 2017 2:35 a.m., "Eric Wieser" <notifications@github.com> wrote:

Looks like 0 in x.strides is true here, and the caveats of
np.broadcast_arrays apply. Except the documentation does not warn for that
here, so this is a bug

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/numpy/numpy/issues/8561#issuecomment-279192075>, or mute
the thread

**Comment by eric-wieser** [comment]
This behaviour changed in 3811083eee8d61548587f0d52286a08a7744d88f, possibly accidentally

**Comment by eric-wieser** [comment]
I think this would be fixed simply by moving the `if copy_` lines below `np.broadcast`

**Comment by idfah** [comment]
Yes, this appears to be a bug that was accidentally introduced by my patch to preserve dtype in meshgrid.  Sorry about that!  Also, yes, moving the copy below the broadcast_arrays should fix the problem.  Looks like the commit by eric-wieser should fix it.  Thank you!

**Comment by mhvk** [comment]
OK, this is fixed, so closed; thanks, @dstansby for reporting and @eric-wieser for the fix!

**Comment by dstansby** [comment]
:+1: Thanks for fixing
