### ISSUE TITLE
Wrong results for polynomial multiplications on GNU/Linux

### ISSUE THREAD

**Issue by pdroalves** [numpy/numpy#8563]
Hello,

I've noticed wrong coefficients in the return of the function numpy.polynomial.polynomial.polymul(). This errors appears to be related to the size of the operands.

A MCVE:
```
from numpy.polynomial.polynomial import polymul
a = [2147483646, 2147483646, 1, 0, 1, 1, 1, 1]
b = [1333972901L, 1455503259L, 571326120L, 324028950L]
c_expected = [813510746L, 1505491134L, 1454627169L, 560148189L, 1581270071L, 966021463L, 1213318633L, 1537347583L, 203374682L, 895355070L, 324028950L]
c = [long(x) for x in polymul(a, b)]
assert c == c_expected # This will fail
```

I could verify this error in a machine running versions 1.11 and 1.12 of numpy on Ubuntu 16.04 64bits, Python 2.7.12. This bug was verified either in a new installation of the same OS in a virtual machine with the same versions of numpy and Python.

**Comment by charris** [comment]
`c_expected` is incorrect.
```
In [12]: convolve(a, b)  # expected
Out[12]: 
array([2864684989104677046, 5990354434506879360, 4352582945968808735,
       1922760371643688479,  695846872860850721,          3113505110,
                3360802280,          3684831230,          2350858329,
                 895355070,           324028950])

In [13]: polymul(a, b)
Out[13]: 
array([  2.86468499e+18,   5.99035443e+18,   4.35258295e+18,
         1.92276037e+18,   6.95846873e+17,   3.11350511e+09,
         3.36080228e+09,   3.68483123e+09,   2.35085833e+09,
         8.95355070e+08,   3.24028950e+08])
```

**Comment by charris** [comment]
Note that the convolution is `int64` and near to overflow, and the float representation cannot be exact. If you need both large numbers and exactness numpy is the wrong tool, sympy would be better.
