### ISSUE TITLE
Failure for test_dot_mem_overlap on PPC

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#8564]
Taken from #8298 

```
======================================================================
ERROR: test_dot_out_mem_overlap (test_multiarray.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/numpy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/numpy-1.13.0.dev0_a611932-py2.7-linux-ppc64.egg/numpy/core/tests/test_multiarray.py", line 2340, in test_dot_out_mem_overlap
    x = np.dot(a, b, out=b)
ValueError: output array is not acceptable (must have the right type, nr dimensions, and be a C-Array)
```

http://nipy.bic.berkeley.edu/builders/numpy-py2.7-debian-ppc/builds/716/steps/shell_5/logs/stdio

The problem is that `np.dot` is testing the `out` array with the `PyArray_ISCARRAY` macro, which includes a test for whether the array is aligned; when testing with the `np.clongdouble` dtype, the output array is not aligned:

```
In [4]: b = np.random.rand(3, 3).astype(np.clongdouble)

In [5]: b.flags
Out[5]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : False
  UPDATEIFCOPY : False
```

Does the `out` array have to be aligned?   Why should this array not be aligned?

**Comment by pv** [comment]
I don't think BLAS requires alignment, so the test for that is probably was intended to check for `PyArray_ISCONTIGUOUS`.

**Comment by charris** [comment]
@pv It isn't coming from BLAS if it is clongdouble, I think it comes from `new_array_for_sum` and alignment may be needed in both places for SPARC.

**Comment by pv** [comment]
Ok, then the test probably needs to be changed to use aligned allocation...

**Comment by pv** [comment]
But is alignment really necessary on SPARC? I thought usually memory provided by `malloc()` is sufficiently aligned to use with any C types?

**Comment by charris** [comment]
Could check for `NPY_CPU_SPARC`. But the test would still need fixing to pass on SPARC...

**Comment by pv** [comment]
Fix in #8567 (just changes the test to use aligned memory) --- @matthew-brett: can you verify?

**Comment by charris** [comment]
Make that `NPY_CPU_HAVE_UNALIGNED_ACCESS`, which checks for AMD or INTEL. For PowerPC
```
The PowerPC takes a hybrid approach. Every PowerPC processor to date has hardware support for unaligned 32-bit integer access. While you still pay a performance penalty for unaligned access, it tends to be small.

On the other hand, modern PowerPC processors lack hardware support for unaligned 64-bit floating-point access. When asked to load an unaligned floating-point number from memory, modern PowerPC processors will throw an exception and have the operating system perform the alignment chores in software. Performing alignment in software is much slower than performing it in hardware.
```
Sounds like it would be best to require alignment for power PC, although it sounds like it only needs to be 64 bits for double_double.

**Comment by charris** [comment]
>The address of a block returned by malloc or realloc in GNU systems is always a multiple of eight (or sixteen on 64-bit systems).

@matthew-brett Is the ppc 32 bits?

**Comment by charris** [comment]
Probably our alignment requirements are over strict, but fixing that is likely a can of worms.

**Comment by matthew-brett** [comment]
```
$ uname -a
Linux alexis 3.16.0-4-powerpc64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) ppc64 GNU/Linux
```

I confirmed this one is fixed on current master, thanks all.
