### ISSUE TITLE
fromfile could accept pathlib.Path argument

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#8576]
#6660 allowed savetxt, loadtxt, load, savez, savez_compressed, ndfromtxt, recfromtxt, and recfromcsv to take a pathlib.Path as input.  A function that is still missing support for such inputs is `np.fromfile`.

**Comment by paulmueller** [comment]
https://github.com/numpy/numpy/blob/master/numpy/core/records.py#L767

I could add this functionality in a PR for #11342.

**Comment by sorenrasmussenai** [comment]
> That was premature. `fromfile` and `tofile` are implemented in C.

...

> The changes would have to be made there (probably with a lot of work to be able to detect pathlib.Paths?).

Maybe there could be a thin Python wrapper to the C functions?
The tiny performance hit shouldn't matter for functions like `fromfile` and `tofile`..

**Comment by seberg** [comment]
I suppose it should also be possible to use `PyOS_FSPath`, but I guess that limits us to python >=3.6, not doing it for 2.7 seems OK, not having 3.5 is not nice though.
Having python wrappers are not bad, although I expect that calling back to python from C to call `os_fspath` is not very tricky. @sorenrasmussenai are you interested in trying this and doing a PR?

**Comment by sorenrasmussenai** [comment]
@seberg I will try to find the time :)

**Comment by anntzer** [comment]
Looks like this was closed by #12915, thanks all :)
