### ISSUE TITLE
[Feature Request] Improve linalg.inv performance

### ISSUE THREAD

**Issue by realitix** [numpy/numpy#8580]
Hello,
Currently, `linalg.inv` returns the inverted matrix. To do so, it creates a new `array` and returns it.
To improve performance and avoid new creation of matrix each time this function is called, there should be an `out` parameter like in the function `matmul`.

It would allow to create a temporary array and re-use it for each computation.

I can try to implement this functionality if you don't have time to do so.
What is your opinion about this request ?

**Comment by pv** [comment]
I would suggest first making sure it is not the inversion and memory 
access themselves that are the bottleneck. If so, using an existing 
array won't improve performance.

**Comment by realitix** [comment]
Sure @pv. But why the `out` parameter exists in `matmul`? Memory allocation can cost a lot on embedded device like phone. And I target android.

**Comment by njsmith** [comment]
I think the main advantage for out= arguments in numpy is for
memory-constrained situations, where one wants to avoid allocating
unnecessary temporaries. This is particularly true for operations like
matrix multiplication and inv, that are O(N**3) -- usually this is *way*
more expensive than allocating a block of memory, so I wouldn't assume this
will actually help you unless you've measured it. But sure, I mean, having
the support wouldn't hurt either.

**Comment by realitix** [comment]
@njsmith : You are right, inverting a matrix is a costly operation compared to allocating memory.
Do I let this ticket open for reference ? 1247 issues currently :smile:

**Comment by njsmith** [comment]
Probably better to close it if it's not something you actually care about after all – if someone else finds a case where it's useful, then they can (re)open an issue :-)

**Comment by realitix** [comment]
ok @njsmith
