### ISSUE TITLE
Segfault when doing an array operation on strided array not owning it's data

### ISSUE THREAD

**Issue by samuelstjean** [numpy/numpy#8582]
This is a weird one. I was trying to modify some striding function based on stuff from sklearn to suit my purpose. And it just blew up in my face without warning. As the original works, this must be my fault, and I have no idea why. I would rather have an error than everything segfaulting, but anyway, here is a snippet to reproduce it.

~~~python
import numbers
import numpy as np
from numpy.lib.stride_tricks import as_strided


def extract_patches(arr, patch_shape, extraction_step=1, modified=True):
    """Extracts patches of any n-dimensional array in place using strides.
    Stolen from https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/feature_extraction/image.py
    """

    arr_ndim = arr.ndim

    if isinstance(patch_shape, numbers.Number):
        patch_shape = tuple([patch_shape] * arr_ndim)

    if isinstance(extraction_step, numbers.Number):
        extraction_step = tuple([extraction_step] * arr_ndim)

    patch_strides = arr.strides

    slices = [slice(None, None, st) for st in extraction_step]
    indexing_strides = arr[slices].strides

    patch_indices_shape = ((np.array(arr.shape) - np.array(patch_shape)) //
                           np.array(extraction_step)) + 1

    # Only change I did : switch order and multiply it together before returning strides

    if modified:
        shape = tuple((np.prod(patch_shape), np.prod(patch_indices_shape)))
        strides = tuple((np.prod(patch_strides), np.prod(indexing_strides)))
    else:
        shape = tuple(list(patch_indices_shape) + list(patch_shape))
        strides = tuple(list(indexing_strides) + list(patch_strides))

    patches = as_strided(arr, shape=shape, strides=strides)
    return patches

# it also blows on regular C order
data = np.asfortranarray(np.random.randn(10,10,10))

# now data does not own it's own data!
data = extract_patches(data, 3, modified=False)
np.array(data, copy=True)

print('it works!')
print(data.flags)

patches = extract_patches(data, 3, modified=True)
print('the flags')
print(patches.flags)
np.array(patches, copy=True) # I tried sum in the first place, but even this blows up
print('this explodes :(')

~~~

I unfortunately did not understand how to save back the gdb backtrace as I never used that before, but I got some output according to using gdb on the python wiki, if it may help.

~~~bash
samuel ~ $ [~] gdb -ex r --args python test.py
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.
Starting program: /home/samuel/anaconda3/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
it works!
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
the flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6ae9aa2 in __mmap (addr=addr@entry=0x0, len=len@entry=1261568, prot=prot@entry=3, flags=flags@entry=34, fd=fd@entry=-1, offset=offset@entry=0) at ../sysdeps/unix/sysv/linux/wordsize-64/mmap.c:32
32	../sysdeps/unix/sysv/linux/wordsize-64/mmap.c: No such file or directory.
(gdb) 
~~~ 

I am also a terrible bug reporter who did not try it on the latest master, rather I am using the anaconda version with python 3.5, which is at numpy 1.11.2. This is on ubuntu 16.04 also, in case the blame lies elsewhere. I have no idea what is happening under the hood though.

It seems like using striding in the way I modified it for my purpose makes the underlying array in memory weird, as the original formulation works. My modification might be 'illegal', as it blows on the next operation made unto it. If that is the case, it would be great to have an error message (if it is even possible at this is a low level feature) instead of segfaulting.

**Comment by eric-wieser** [comment]
You can't just collapse down strides like that, for the same reason that the following incurs a copy:

```
>>> x = np.eye(3)
>>> x2 = x[:2,:2]
>>> xf = np.reshape(x2, -1)  # copy here
>>> xf[...] = 2
>>> x2
array([[ 1.,  0.],
       [ 0.,  1.]])
```

**Comment by samuelstjean** [comment]
Figured I was just doing random stuff after all. If it's too much hassle to check for segfaults in rare cases where people are doing nonsense, then this can be closed I guess. I'll just work around my problem differently for my use case.

So to be sure, strides can only be modified when they stay contiguous and you can't jump all over the memory of your array? It would probably kill performance anyway, but for chunking data of many GB with rolling windows (thus storing it making it well over 1TB, true story),  it seemed useful.

**Comment by eric-wieser** [comment]
>  you can't jump all over the memory of your array?

What do you mean by the memory of the array? You can certainly jump over the memory used by the elements of the array, but it's probably not ok to try and use the space in between them, which is what you've done

**Comment by samuelstjean** [comment]
I unfortunately do not understand enough about low level memory allocation to phrase it correctly, but, is the problem here that I am trying to use strides which are non contiguous as opposed to using data in reshaping/viewing which keeps strides in a 'good ordering'?

**Comment by pv** [comment]
Understanding the memory layout is crucial for using as_strided 
correctly --- it's explained eg here 
https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray
.
Stackoverfow is probably a better forum for user questions such as this, 
if it is not a bug in numpy.

**Comment by eric-wieser** [comment]
The problem is that your strides cause the numpy array to claim ownership of memory that is not its to own. The only bug in numpy here is the lack of error message, but #8315 is the PR for that.

**Comment by samuelstjean** [comment]
Ah well, figured I was doing something wrong, and it is being checked for in that other PR anyway, so I guess I'll go back to reading more about it again then, thanks.
