### ISSUE TITLE
Numpy + mkl: Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

### ISSUE THREAD

**Issue by RO-mix** [numpy/numpy#8587]
I read the whole thread on this here... Cannot find the solution. It came up after reinstallation of anaconda and messing up with Py3.5 packages. Removed all mkl* from system directory. Ensured that i have dlls in "C:\Python\Anaconda3\Lib\site-packages\numpy\" directory. Adden this to path... Nothing helps.
Don`t know is it possible to fix and how....
win 8.1 64

**Comment by njsmith** [comment]
Not sure what to tell you... I guess I'd suggest trying to completely
remove and then reinstall Anaconda, and if that doesn't work then try the
Anaconda mailing list:
https://groups.google.com/a/continuum.io/forum/?fromgroups#!forum/anaconda
We don't have anything to do with MKL ourselves, though.
