### ISSUE TITLE
Questionable behaviour  in MaskedArray.__eq__ on flexible arrays

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8589]
[These lines](https://github.com/numpy/numpy/blob/7927b3cb4b57e79bf6b1b8a723583295fc0398eb/numpy/ma/core.py#L3924-L3928), introduced in a5da87c6254f183dc068d912dde9fd00341d926f by @pierregm, appear multiple times in `numpy/ma/core.py`, such as `MaskedArray.__eq__`:
```python
try:
    mask = mask.view((bool_, len(self.dtype))).all(axis)
except ValueError:
    mask = np.all([[f[n].all() for n in mask.dtype.names]
      for f in mask], axis=axis)
```
But where is this `ValueError` expected to come from? The `.view`, or the `.all`, due to an invalid axis.

It seems like there is a bug in the code that prepares `axis` here, and this bug is being silenced by an overzealous try/catch.

**Comment by charris** [comment]
@mhvk @ahaldane Thoughts.

**Comment by mhvk** [comment]
In the commit pointed too, in another similar change, there is a [comment](https://github.com/numpy/numpy/commit/a5da87c6254f183dc068d912dde9fd00341d926f#diff-e85f023d9c07df014a190b485db72c3dR2042): "# In case we have nested fields..."

So, at least that gives a hint why this was introduced. Indeed, one of the test cases shows that it is at least one thing the `ValueError` is meant to catch:
```
ndtype = [('A', int), ('B', [('BA', int), ('BB', int)])]
a = np.ma.array([(1, (1, 1)), (2, (2, 2))], mask=[(0, (1, 0)), (0, (0, 1))], dtype=ndtype)
a.mask
# array([(False, ( True, False)), (False, (False,  True))], 
#       dtype=[('A', '?'), ('B', [('BA', '?'), ('BB', '?')])])
a.mask.view((np.bool_, len(a.dtype)))
# ValueError: new type not compatible with array.
```

In principle, I guess one should really write
```
try:
    mask = mask.view((bool_, len(self.dtype)))
except ValueError:
    mask = np.all(....)
else:
    mask = mask.all(axis)
```

But where does the indexing go wrong? I must say having a default of `axis=1` seems very odd; surely, this should be `axis=-1`?!?!

**Comment by mhvk** [comment]
Just checking now: my `try/except/else` indeed throws the same errors as found in #8584, and those disappear when I (correctly) set `axis=-1`. PR to come soon.

**Comment by eric-wieser** [comment]
Does this mean there is a bug with masked 2D record arrays?

**Comment by mhvk** [comment]
> Does this mean there is a bug with masked 2D record arrays?

Yes. What a code...  Anyway, fix almost done.

**Comment by mhvk** [comment]
See #8590 for a fix.

**Comment by eric-wieser** [comment]
@mhvk: We can close this as of #8590, right?

**Comment by mhvk** [comment]
Yes!
