### ISSUE TITLE
numpy.save() data alignment increase from 16 to 64 bytes

### ISSUE THREAD

**Issue by jzwinck** [numpy/numpy#8598]
This is regarding the NumPy file format: https://docs.scipy.org/doc/numpy-dev/neps/npy-format.html

The format guarantees 16 byte alignment of the stored array.  But sometimes this is not enough.  For example, current Intel processors support AVX2 which operates on 32 byte chunks.

Currently, if an array is stored with `numpy.save()` and the data happens not to be aligned to 32 bytes (which will happen about 50% of the time), feeding the data to AVX2 instructions (perhaps outside of NumPy) requires extra work to realign the data.  I presume that avoiding such extra work is the reason why there is 16 byte alignment in the first place.

I propose increasing the minimum alignment from 16 bytes to 64 bytes.  As far as I can tell this will be backward compatible because `np.load()` doesn't care how much padding there is before the newline which ends the header.  That is, the NumPy file header version would not need to change.

Why 64 bytes?  It's good for the upcoming AVX-512, it's not too wasteful, and I don't see a current need for more.

**Comment by juliantaylor** [comment]
cpus since haswell don't have any measurable penalty for 16 byte aligned data. This only has a very small effect on sandybridge type cpus.
Also for storing this doesn't really have any effect at all.
A weak argument can be made for the general memory allocation inside numpy, but there is only very little that uses avx inside numpy and there is no aligned calloc available that is compatible with free, so its not worth it to have a very minimal effect on by now rather old cpus.

As for avx512, I don't have the hardware to test alignment performance, but given how their newer cpus work, the goal of that instruction set and how numpy itself works I doubt 64 bit alignment is necessary.

**Comment by jzwinck** [comment]
@juliantaylor Please see for example VMOVAPS which is described here: http://www.felixcloutier.com/x86/MOVAPS.html

The description says:

> When the source or destination operand is a memory operand, the operand must be aligned on a 16-byte (128-bit version) or 32-byte (VEX.256 encoded version) boundary or a general-protection exception (#GP) will be generated.

So I'm not really talking about the performance penalty of unaligned access, but rather the fact that a fault will occur if code expecting full alignment (to 32 bytes in the AVX2 case) receives data not so aligned.

**Comment by juliantaylor** [comment]
AVX, like SSE before it, has unaligned instructions, e.g. VMOVUPS. So you can use AVX on unaligned memory just fine, and compilers knowing that it has no significant penalty will also use these type of instructions.
An issue is that you can't directly use operations with memory operands without unaligned loading first, but in practice this makes no difference anymore, at least I have not seen any code yet where a difference can be measured.

**Comment by juliantaylor** [comment]
actually no, its even better, except for the explicit aligned ones like VMOVAPS, all avx instructions (like VADDPS) can operate on unaligned memory operands. So there is really no issue.

**Comment by jzwinck** [comment]
@juliantaylor I think you're coming at this from the perspective of someone who would write the SIMD code themselves, as opposed to someone who merely hopes to use SIMD on data stored in the NumPy format.  If I have a library that uses aligned instructions and a file format which is not sufficiently aligned, there is indeed still an issue that must be resolved--either with extra code to realign the data, or by increasing the alignment in the file format.

**Comment by juliantaylor** [comment]
gh-8085 still needs fixing, so we could increase the padding in that fix.

**Comment by jzwinck** [comment]
@juliantaylor there is a problem with what you said here:

> you can always read the header manually and mmap the right offset. Then you have page aligned memory.

On Linux, the offset argument to `mmap()` *must* be page-aligned (e.g. to 4096 bytes).  So this idea can't be used on Linux (which happens to be the platform I'm using).
