### ISSUE TITLE
`iscomplexobj` not working for custom dtypes

### ISSUE THREAD

**Issue by behrmann** [numpy/numpy#8601]
Hi,

As wished by @shoyer in PR #7936 here a new Issue. The PR introduced a small backwards incompatibility, that now bites the [tinyarray](https://gitlab.kwant-project.org/kwant/tinyarray) project, which provides a mostly Numpy compatible array on top of `PyVarObject`s. As a dtype tinyarrays simply return a Python type like `complex`, which is not recognized by `iscomplexobj` anymore.

The problem can be examplified by imagining a custom array type on top of list
```
class MyArray(list):
    @property
    def dtype(self):
        return type(self[0])
```
We can use this like this
```
>>> import numpy as np
>>> a = MyArray([1+0j, 2+0j, 3+0j])
>>> np.lib.type_check.iscomplexobj(a)
False
>>> np.asarray(a)
array([ 1.+0.j,  2.+0.j,  3.+0.j])
>>> issubclass(np.asarray(a).dtype.type, np.complexfloating)
True
```
where the last line is equal to the former implementation of `iscomplex`.

**Comment by behrmann** [comment]
The issue could be fixed by adding a call to `getattr` in `iscomplexobj`:
```
def iscomplexobj(x):
    try:
        dtype = x.dtype
        getattr(dtype, "type")            
    except AttributeError:
        dtype = np.asarray(x).dtype
    try:
        return issubclass(dtype.type, np.complexfloating)
    except AttributeError:
        return False
```
This should reproduce the previous behaviour of `iscomplexobj`.

**Comment by shoyer** [comment]
@behrmann why don't you open up a PR?

**Comment by behrmann** [comment]
@shoyer Done, I just wanted to ask beforehand. My proposed fix is very easy, but again has corner cases, if somebody goes so far as to implement the type attribute on a dtype, but there is I guess little one can do.

**Comment by shoyer** [comment]
This gets really messy, it's basically impossible to maintain compatibility with every conceivable array-like type. About the best we can do is fix these issues when they come up.
