### ISSUE TITLE
Release note format causes merge conflicts without fail

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8603]
Is there some other header/whitespace format we can switch to that might alleviate this, or a .gitattributes file of some kind?

**Comment by eric-wieser** [comment]
Looks like

```
/doc/release/*.rst merge=union
```

In .gitattributes would do the trick

**Comment by mhvk** [comment]
That is what we ended up doing in astropy as well; :+1:

(It does mean the release manager has to check for possible missing blank lines, but that seems to be about the extent of the mistakes that get made).

**Comment by seberg** [comment]
Sounds like something to decide for those who do release work. But seems like a good idea, for all I see we have to read through the release notes anyway once, so that it should be fine.

**Comment by eric-wieser** [comment]
Ok, this is now a pain. Say you make a series of commits where the first adds

```diff
+Add some new feature to x
+-------------------------
 +This does a and b
```

and the second adds

```diff
-Add some new feature to x
----------------------------
-This does a and b
+Add some new feature to x and y
+------------------------------
+This does a and b and c
```

Then the release notes get changed in master, and somehow there's a conflict anyway.

So you rebase, and end up with
```
+Add some new feature to x
+---------------------------
+This does a and b
+Add some new feature to x and y
+------------------------------
+This does a and b and c
```

because it's taking the union of the additions. Fixing this bad rebase is a lot of work

I think maybe we should revert this patch, and just fix conflicts as they come up in the web editor, creating merge commits

**Comment by njsmith** [comment]
We might consider switching to: https://github.com/hawkowl/towncrier

The basic idea is that we have a directory (conventionally called `newsfragments`), and PRs with user-visible effects should create a file called `newsfragments/${ISSUE}.${TYPE}.rst`, like `newfragments/123.bugfix.rst`. And then at release time you use the tool to collect up the files, collate them, and dump them into your actual docs.

**Comment by eric-wieser** [comment]
Including the pr number is tricky for new users, because you don't know it till you submit.

But yes, I think that would be sensible. It's frustrating to see old PRs needing a rebase simply because they target the wrong release notes / clash with other release notes.

Is towncrier what matplotlib uses? They seem to have something similar going on

**Comment by rgommers** [comment]
Towncrier was also suggested and discussed on the scipy issue tracker recently: 
https://github.com/scipy/scipy/issues/7793

I'm -0.5 on that, and propose simply to use one Github issue per release. At merge time fragments can be added there. Simple, not much work for release manager, less cognitive load for new contributors, and doesn't make a mess of many little files.

**Comment by pv** [comment]
I wrote this thing to collect items from Github issues (or PRs in this 
case): https://github.com/scipy/scipy/pull/7794

**Comment by seberg** [comment]
And another issue about the annoyance of release notes creating merge conflicts. Closing.
