### ISSUE TITLE
Documentation for average does not indicate axis may be tuple

### ISSUE THREAD

**Issue by cancan101** [numpy/numpy#8604]
Docs for`average` indicate that axis may be an int but does not indicate that it may be a tuple. the tuple format _does_ work

Docs: https://docs.scipy.org/doc/numpy/reference/generated/numpy.average.html

```
>>> np.average(np.ones((4,4,4)), axis=(1,2))
array([ 1.,  1.,  1.,  1.])
```

**Comment by seberg** [comment]
Yes, it should be mentioned. Want to create a PR?

**Comment by nbara** [comment]
This does not work in case weights are provided though: 

```python 
>>> np.average(np.ones((4,4,4)), axis=(1,2), weights=[1, 0, 0])
TypeError: tuple indices must be integers or slices, not tuple
```
