### ISSUE TITLE
Change the documentation of the gradient function  that it uses first order central difference in the interior

### ISSUE THREAD

**Issue by drabach** [numpy/numpy#8607]
There is a "typo" in the documentation of the gradient function
(https://docs.scipy.org/doc/numpy/reference/generated/numpy.gradient.html).

The implementation is using first order central difference in the interior. But the documentation states that central difference of second order would be used. 

I can make a fix available when this issue gets approved.

**Comment by eric-wieser** [comment]
You did this, and then it was reverted, right?

**Comment by drabach** [comment]
Sorry for this late answer...

Yes, what you state is what happened. Afterwards there was some work where I was not really involved. So I guess the issue got addressed somehow differently. 

There are different definitions for "second order" difference. It was proposed at least to give the definition used, inside the documentation - otherwise users might be confused about the outcome of the gradient function as I was. In case the documentation of the gradient function contains the definition now I would say this issue can be closed. But I have not checked it yet.

**Comment by eric-wieser** [comment]
Closing - the docs said "second order *error*", not "second order *difference*"
