### ISSUE TITLE
How to install numpy with pip, linked against openblas in non-standard location ?

### ISSUE THREAD

**Issue by samfux84** [numpy/numpy#8613]
Hi,

Since several years I am installing software on a large HPC cluster. I build Python from source and used to install all packages by downloading the source code from pypi and installing them with setuptools (python setup.py install).

According to https://docs.python.org/3/installing/index.html, since Python 3.4, the preferred way of installation for Python packages is to use pip:

"pip is the preferred installer program. Starting with Python 3.4, it is included by default with the Python binary installers."

I am fine with that as long as I get something usable in the end. I usually link numpy and scipy to our OpenBLAS 0.2.13 library, that was installed from source. It is located in

/cluster/apps/openblas/0.2.13_seq/x86_64/gcc_4.8.2/lib/libopenblas.so

How can I install numpy with pip, such that it is linked against my local libopenblas.so. With setuptools, this is trivial and used to work with the command:

OPENBLAS=/cluster/apps/openblas/0.2.13_seq/x86_64/gcc_4.8.2/lib/libopenblas.so python setup.py install

If I install numpy with

OPENBLAS=/cluster/apps/openblas/0.2.13_seq/x86_64/gcc_4.8.2/lib/libopenblas.so pip install numpy

it downloads a precompiled wheel and installs it, but it is not linked against the local openblas. I searched in the internet for a solution to this problem. Most of the answers about this problem were not very usefull.

If pip is the way to go for future Python installations (3.4+), then it should at least be possible to achieve what could be done with setuptools before.

Any help is appreciated

Best regards

Sam

**Comment by njsmith** [comment]
The precompiled wheel ships with a copy of openblas inside it which it uses, so it might be good enough for your purposes. Certainly it's simpler than building things yourself :-)

If you do want to build from source though using pip, the incantation is:
```
pip install numpy --no-binary=numpy
```
(In general if you're installing multiple packages at once, `--no-binary` takes a comma-separated list of packages where you want to force pip to *not* use a wheel, or you can use `--no-binary=:all:` to disable wheels altogether.)

**Comment by njsmith** [comment]
(Note also that openblas 0.2.13 was released in 2014 and there have been a lot of bug fixes since then... it looks like the numpy wheel currently ships with 0.2.18.)

**Comment by rgommers** [comment]
Complementary answer: since you cannot specify the OpenBLAS location on the command line, put it in ``~/.numpy-site.cfg`` and building from source with pip will pick it up. See ``site.cfg.example`` in the root dir of the numpy repo.
