### ISSUE TITLE
Wrong results with numpy.sum

### ISSUE THREAD

**Issue by igngvs** [numpy/numpy#8616]
Why does numpy.sum return different values in the following expressions? I don't know if it is a bug, but it seems to be a wrong behaviour. The results have been obtained with python 2.7.12 and numpy 1.12.0.

```
>>> numpy.sum([2**63 for x in range(64)])
0
>>> numpy.sum(2**63 for x in range(64))
590295810358705651712L
```

**Comment by charris** [comment]
The first is an array of ints and the sum is performed in modular arithmetic. The second doesn't even construct an array AFAICT, it appears to call the python sum on the generator and that works with the python ints that have unlimited precision.

**Comment by igngvs** [comment]
Thank you.

This behaviour (i.e., the implicit conversion from python list to numpy array) can be a source of bugs in some circumstances. In my case, the error occurred in jupyter notebook with "%pylab inline". As pylab populates the interactive namespace from numpy, the python sum function is substituted by "numpy.sum". So, perhaps the problem is really due to this "%pylab" behavior.
