### ISSUE TITLE
ENH: magic squares

### ISSUE THREAD

**Issue by pezcore** [numpy/numpy#8635]
First, I apologize for asking this here, (can someone with more expreince with this project please direct me to the appropriate channels to ask this sort of thing?)

Should we add a `magic()` function that can be used to create [Magic Squares](https://en.wikipedia.org/wiki/Magic_square) similar to [MATLAB's `magic()` function](https://www.mathworks.com/help/matlab/ref/magic.html) ? 

This could be yet another routine in ["Array Creation Routines"](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html)

This would be very easy to add and I think adds value even if it is a python implementation.

**Comment by charris** [comment]
A better place for questions like this would be the numpy mailing list.

I don't think magic would be a good fit for numpy, which is for basic functionality and routines with wide application. I admit that some things have slipped in that don't fit that criteria, but we try to limit that. May I suggest that you put this up on PyPI instead? Maybe with other routines of the same sort.

**Comment by pezcore** [comment]
@charris yea, thats kind of what I figured: I agree it is a tad bit out-of-scope for numpy. 

Thanks very much though for your timely response and guidance in helping me understand this project and how to get involved, I look forward to contributing in the future,
