### ISSUE TITLE
ENH: Implement np.linalg.{svd,qr,lstsq} for matrices with .size == 0

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8654]
Right now, this fails by design, but it could return a logical result without doing so.

It's possible that the LAPACK routines can handle this natively, and we just need to call them with the right arguments.

Follows on from #8212

* [x] `qr` (#11593)
* [x] `svd` (#11424)
* [x] `lstsq` (#11594)

**Comment by eric-wieser** [comment]
@convexset, do you have any intuition for how `lstsq` should behave on empty arrays?

**Comment by convexset** [comment]
a     | b      | x      | res    | rank   | s   
-------|--------|--------|--------|--------|--------
(m, n) | (m, p) | (n, p) | (p, )  | int    | (min(m, n), )
(0, n) | (0, p) | (n, p) | (p, )  | int    | (0, )
(m, 0) | (m, p) | (0, p) | (p, )  | int    | (0, )
(m, n) | (m, 0) | (n, 0) | (0, )  | int    | (min(m, n), )

**Comment by eric-wieser** [comment]
To be clear, my question is what the _value_ of x should be in the first row - the shapes are obvious

**Comment by convexset** [comment]
I think the following would make sense:

 a     | b      | x      | res    | rank   | s   
-------|--------|--------|--------|--------|--------
(0, n) | (0, p) | zeros(n, p) | zeros(p, )  | int    | (0, )
(m, 0) | (m, p) | (0, p) | respective column norms of b  | int    | (0, )
(m, n) | (m, 0) | (n, 0) | (0, )  | int    | (min(m, n), )

**Comment by convexset** [comment]
PR for `qr`: https://github.com/numpy/numpy/pull/11593 (Sorry, got busy.)

**Comment by convexset** [comment]
PR: https://github.com/numpy/numpy/pull/11594 (for `linalg.lstsq`)

**Comment by convexset** [comment]
I had some problems with the tests, so I'm not sure if my development workflow is right.

Basically, to "iterate", I do something like
```bash
python setup.py build_ext --inplace; python3 runtests.py -t numpy/linalg/tests/test_linalg.py
```
and will see failures like
```
Python(38280,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744072351240192) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(38280,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744072351240192) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(38280,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744072351240192) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(38280,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744072351240192) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(38280,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744072351240192) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(38280,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744072351240192) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
```
So I'm wondering how I can get rid of these.

The above PRs were developed by editing code in `site_packages/numpy` in a virtual environment and verified with tests in the REPL. Since the additional code is pure python, there should not be a problem. But I'd like to figure out how to ensure things work on my machine.

I'm on OS X High Sierra.

**Comment by pv** [comment]
No need for build_ext inplace

**Comment by convexset** [comment]
Hmmm... even after clearing things up...
```
git clean -xdf
```
... doing a fresh build...
```
python3 setup.py build
```
... and finally running tests...
```
python3 runtests.py -t numpy/linalg/tests/test_linalg.py
```
... the same issues arise
```
Python(44122,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744071653396480) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(44122,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744071653396480) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(44122,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744071653396480) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(44122,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744071653396480) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(44122,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744071653396480) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Python(44122,0x7fffa3104380) malloc: *** mach_vm_map(size=18446744071653396480) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
```
Is this something that no one else has every encountered?

**Comment by tylerjereddy** [comment]
One thought

> The above PRs were developed by editing code in `site_packages/numpy` in a virtual environment

Isn't that a bit unusual for a workflow? Maybe I'm just strange, but I usually develop directly in the git repo and expect the build to **target** the install to `site_packages` but I almost never touch code by directly editing in `site_packages`.

**Comment by convexset** [comment]
Nah... you're doing things the normal way. My "exceptional" (in the sense of raising an exception) approach was due to it being purely in python (and the build environment issue).

**Comment by eric-wieser** [comment]
Looks like this can now be closed
