### ISSUE TITLE
binary_repr: extra bit for most-negative number

### ISSUE THREAD

**Issue by jsw-fnal** [numpy/numpy#8670]
`binary_repr` does not correctly represent maximally-negative numbers of a given width.  For example, an 8-bit two's complement can represent numbers in the range [-128, 127], inclusive.  That is, -128 as an 8-bit two's complement number is "10000000", and 127 is "01111111".  However, `binary_repr` mishandles -128:
```
>>> import numpy
>>> numpy.__version__
'1.12.0'
>>> numpy.binary_repr(-128, 8)
'110000000'
```

Notice, the result is a 9-bit string instead of the requested 8-bit string.

This is not limited to a width of 8:
```
>>> numpy.binary_repr(-8, 4)
'11000'
>>> numpy.binary_repr(-32768, 16)
'11000000000000000'
>>> numpy.binary_repr(-1, 1)
'11'
```

**Comment by rkern** [comment]
Hmm, works fine in 1.11.3:

```
[~]
|3> np.binary_repr(-128, width=8)
'10000000'

[~]
|4> np.__version__
'1.11.3'
```

**Comment by charris** [comment]
@rkern Confirmed. Looks like a regression.

**Comment by charris** [comment]
The only recent changes to the function came in with b03527de, #7178. @gfyoung Head up.

**Comment by gfyoung** [comment]
Here is why:
~~~python
>>> bin(127)
'0b1111111'
>>> bin(128)
'0b10000000'
~~~
My patch relied on computing the 2's complement using the length of the positive number.  Numbers at the boundary get one additional digit.  This should be relatively easy to patch with one `if` branch.

**Comment by gfyoung** [comment]
Patch for this regression is up: #8674.
