### ISSUE TITLE
Broken link in Documentation

### ISSUE THREAD

**Issue by jesseakt** [numpy/numpy#8673]
I wanted to report a broken link I found in the NumPy User Guide. 

In [NumPy Basics / Subclassing ndarray](https://docs.scipy.org/doc/numpy/user/basics.subclassing.html), credit is given to Pierre Gerard-Marchant and his contribution to a linked wiki page at [http://www.scipy.org/Subclasses](http://www.scipy.org/Subclasses), but this is currently redirecting to a 404.

In #8520, @charris notes that the wiki is extinct, so perhaps the link to the wiki should be deleted. Any ideas on whether this link should redirect to a different location or how to preserve the credit given without the link?

**Comment by rgommers** [comment]
Thanks for reporting @jesseakt. Those credits should be removed, they don't belong in user docs. We have commit messages (fine here) or THANKS.txt for that.
