### ISSUE TITLE
ENH: Add a helper function to convert to array or scalar

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8681]
Something so that:
```
>>> the_func([1, 2])
array([1, 2])
>>> type(_)
np.ndarray
>>> the_func(1)
1
>>> type(_)
np.int32
```

Can be implemented trivially as

```
def the_func(x):
    return asanyarray(x)[()]
```

What should this be called?

* `asanyarray(x, ..., allow_scalar=True)`
* `asanyarrayorscalar(x)`

**Comment by seberg** [comment]
On the C-api side there is a function, something like PyArray_ReturnArray or so, which does this conversion. The indexing is just a hack that comes close to doing the same thing really.

**Comment by mattip** [comment]
I suggest we close this.

**Comment by InessaPawson** [comment]
@eric-wieser I’m going to close this issue as the proposed feature didn’t get support from the NumPy dev team at 2023-02-08 meeting where it was reviewed.
