### ISSUE TITLE
numpy.split() does not work for not sorted indices

### ISSUE THREAD

**Issue by dankal444** [numpy/numpy#8683]
If you provide not sorted array of integers as 'indices_or_sections` argument you will not get the expected output.
```
array = np.arange(20)
split_indices = [4, 7, 13]
splitted_array = np.split(array, split_indices)
```
--> works like charm, returns:
 [0, 1, 2, 3],  [4, 5, 6], ...
```
# changing order of split_indices
splitted_array = np.split(array, split_indices[::-1]
```
--> strange output: 
[0, 1, 2, ..., 11, 12],   [],   [],   [4, 5, 6, ... 18, 19]

**Comment by seberg** [comment]
What is the expected output? It basically is what the documentation says it will be, though of course that is strange.

**Comment by dankal444** [comment]
My bad i did not notice word "sorted" while reading documentation.
Whether or not there should be warning informing about using not sorted array i do not know.

**Comment by eric-wieser** [comment]
yep, that output is correct - you asked for `arr[:13]`, arr`[13:7]`, and `arr[7:]`

**Comment by eric-wieser** [comment]
Now, maybe you could argue that in this case it should return `arr[:13], arr[7:13][::-1], arr[4:7][::-1], and arr[4:]`

**Comment by seberg** [comment]
Doing anything with reversed steps sounds like magic to me and my gut feeling is to run like hell from it. Adding a warning/error would seem fine to me, though not sure its a big thing.

**Comment by eric-wieser** [comment]
Yeah, i think you're right. Something like `if (indices[:-1] < indices[1:]).any(): warn()` would be good

**Comment by stefanv** [comment]
The general consensus here, which I agree with, is that this issue should be closed as invalid.  A patch in #14581 provides a warning, which is good enough.

**Comment by stefanv** [comment]
(Additional note: the warning checking isn't entirely trivial, and in this case was perhaps not quite correct. The additional benefit of adding this logic did not outweigh its cost.)
