### ISSUE TITLE
np.abs(np.nan) causes floating point exception on MIPS

### ISSUE THREAD

**Issue by jcowgill** [numpy/numpy#8686]
Python 2.7.13
NumPy 1.12.0 (Debian package)

As the title says:
```
$ python -c 'import numpy as np; np.seterr(all="raise"); np.abs(np.nan)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FloatingPointError: invalid value encountered in absolute
```

Something is going on in numpy to cause this. Simply running `fabs` on a `NaN` in C doesn't set any FP exception flags. I can run things on MIPS machines for you, but I'm not sure where to start in debugging this.

**Comment by charris** [comment]
Why do you say this is a bug? How do you know that a flag can't be set depending on various runtime settings?

**Comment by juliantaylor** [comment]
hm I looked at that years ago on a mips machine once and wrote if of as a mips bug, I think fabs did raise. Maybe something changed in the mean time, but mips is not a relevant platform for numpy so you will have to provide a patch if numpy really has a bug.

**Comment by jcowgill** [comment]
> Why do you say this is a bug? How do you know that a flag can't be set depending on various runtime settings?

I think it's a bug because it only affects MIPS NumPy (plain Python `math.fabs` with `fpectl` works and  C `fabs` does not set any flags) and AFAIK abs should never set any FP exception flags if the input is a QNaN.

> hm I looked at that years ago on a mips machine once and wrote if of as a mips bug, I think fabs did raise. Maybe something changed in the mean time, but mips is not a relevant platform for numpy so you will have to provide a patch if numpy really has a bug.

OK I'll have a look myself at some point.
