### ISSUE TITLE
Wheels licensing

### ISSUE THREAD

**Issue by pombredanne** [numpy/numpy#8689]
The Pypi wheels (in particular the manylinux ones) contain prebuilts libraries for openblas (bsd) and libgfortran.... (gpl with runtime exception?) but no information about their licenses and where to get the corresponding sources. It would be great to have some clarity in this domain.
The same issues exist with scipy: https://github.com/scipy/scipy/issues/7093

**Comment by rgommers** [comment]
Let's not do the identical discussion twice - so let's deal with the SciPy issue first (since I replied there, arbitrary choice).

**Comment by pombredanne** [comment]
Agreed.

**Comment by rgommers** [comment]
The scipy issue is now resolved, so can do the same in numpy for the next release.

**Comment by charris** [comment]
Made PR to `numpy-wheels`: https://github.com/MacPython/numpy-wheels/pull/5
