### ISSUE TITLE
np.absolute(v[idx] , v[idx])   does not update v  

### ISSUE THREAD

**Issue by gfacciol** [numpy/numpy#8691]
I haven't found if this issue is already reported, my excuses if it is the case. 

This issue affects at least the functions `absolute, sign`, and `maximum` in numpy 1.12.0. 
Running:

     import numpy as np
     v   = np.array([1,-1,-1])
     idx = np.array([True,True,True])   
     np.absolute(v[idx], out=v[idx])    # v not updated
     print(v)                           # expected result: [1, 1, 1]
does not produce the expected result `[1, 1, 1]`, instead it gives  `[ 1 -1  -1]`.
 
Oddly `np.absolute(v, v)` does update `v` correctly.

**Comment by eric-wieser** [comment]
Not a bug. `arr[boolean_indexing]` always returns a copy, not a view, by design

**Comment by gfacciol** [comment]
Thanks for the clarification!
