### ISSUE TITLE
masked median of empty dimension fails

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#8703]
a = np.ma.masked_array(np.array([], dtype=float, ndmin=3))
    np.ma.median(a, axis=2)

fails with

    IndexError: index -1 is out of bounds for axis 2 with size 0

As integer indexing of empty slices does not work.
Normal median slices instead and returns the mean of an empty slice, so nan.

What should masked median return? a masked nan to somewhat match the normal median or an empty array again?

**Comment by charris** [comment]
This is also an error in 1.11.3, so not a regression. I want to release 1.12.1 soon, so may not include a fix for this if it isn't ready.

**Comment by juliantaylor** [comment]
hm that is a regression in 1.11.2, it does work in 1.11.1
there it returns nan, like the normal median so thats probably how we should fix it.
