### ISSUE TITLE
Add `keepdims` argument to argmin and argmax

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8710]
For consistency with `min` and `max`, so that the returned object is the same shape.

**Comment by eric-wieser** [comment]
This might actually be done best by making `argmin` a `gufunc`?

**Comment by eric-wieser** [comment]
Trivial implementation:

```
def argmin(*args, keepdims=False, **kwargs):
    res = np.argmin(*args, **kwargs)
    axis = kwargs.get('axis', none)
    if axis is not None:
        res = np.expand_dims(res, axis=axis)
    return res
```

**Comment by shoyer** [comment]
>This might actually be done best by making argmin a gufunc?

The challenge here is that only `ufunc.reduce` has the logic for axis handling. That's not something that exists for general ufuncs, though it probably should (https://github.com/numpy/numpy/issues/5197), at least for simple cases like these where the ufunc signature looks like `(n)->()`.

**Comment by FabianSchuetze** [comment]
I would be glad about this features. As I was thinking of trying to contribute to numpy for some time, would somebody mind if I simply tried to implement the feature according to the [development workflow](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html)?

**Comment by yarki** [comment]
Folks, below is the workaround I'm currently using. Please reply if you see a better way to preserve original dimensions. Thanks.

```python
def argmax_keepdims(x, axis):
    """
    Returns the indices of the maximum values along an axis.

    The axis which is reduced is left in the result as dimension with size one.
    The result will broadcast correctly against the input array.

    Original numpy.argmax() implementation does not currently support the keepdims parameter.
    See https://github.com/numpy/numpy/issues/8710 for further information.
    """
    output_shape = list(x.shape)
    output_shape[axis] = 1
    return np.argmax(x, axis=axis).reshape(output_shape)
```

**Comment by arvoelke** [comment]
In my case `np.unravel_index(np.argmax(x), x.shape)` did what I needed (flattens the array, takes the argmax, and then reinterprets the index with respect to the original shape). Your mileage may vary depending on what you are trying to do of course.
