### ISSUE TITLE
It can not calculate generalized  inverse  matrix.

### ISSUE THREAD

**Issue by zhaoxingfeng** [numpy/numpy#8711]
>>>
For example,
----------
import numpy as np
m = np.mat([[1, 1], [0, 0]])
print(m.I)

It fails giving LinAlgError: Singular matrix error.
----------
Actually, the generalized  inverse  matrix for m is:
matrix([[1/2, 0],[1/2, 0]])

**Comment by njsmith** [comment]
That's because `matrix.I` is the inverse, not the generalized inverse.

As a general rule, you shouldn't be using `np.matrix` at all – I'd recommend using `np.array`, and `np.linalg.inv` for inverse, `np.linalg.pinv` for pseudo-inverse / generalized inverse:
```python
In [2]: m = np.array([[1, 1], [0, 0]])

In [3]: np.linalg.pinv(m)
Out[3]: 
array([[ 0.5,  0. ],
       [ 0.5,  0. ]])
```

**Comment by zhaoxingfeng** [comment]
Thanks a lot!
