### ISSUE TITLE
python bool False returned from relational operator

### ISSUE THREAD

**Issue by rizac** [numpy/numpy#8724]
I am sorry if the issue has already been discussed but I didn't find any mention after browsing here. 
Given the following:
```
import numpy as np
>>> condition = np.array('abc') < 7  # or np.array(['a','c']) < 7, whatever ...
>>> condition
False
>>> type(condition)
<type 'bool'>
```
Is it a bug or there is a rationale behind returning the python boolean `False`, given the fact that, afaik, all other comparison operators return `numpy.bool_` arrays?

The logic is unclear. I would understand, when comparing apples and oranges as in this case, to either return something different, or stick to `numpy.bool_` arrays. That `False` seems to be a specific design choice (it's actually *almost* what one would expect) which on the other hand prevents using handy `numpy` functions further (e.g. `if condition.all()`) without cumbersome `if-else`s

Thanks in advance

**Comment by pv** [comment]
Not a bug. In Python 2, comparisons are defined between all objects. In 
Python 3 you get TypeErrors.
