### ISSUE TITLE
Wrong documentation page for `hsplit`

### ISSUE THREAD

**Issue by Sentient07** [numpy/numpy#8725]
I'm sorry if this issue has already been reported and I'm reposting it. The documentation of page of `hsplit` seems to be wrong and does what `dsplit` does. 
The examples should rather give, 

```
In [2]: np.hsplit(x, 2)
Out[2]: 
[array([[[  0.,   1.,   2.,   3.]],
 
        [[  8.,   9.,  10.,  11.]]]), array([[[  4.,   5.,   6.,   7.]],
 
        [[ 12.,  13.,  14.,  15.]]])]

```
and 
```
In [4]: np.hsplit(x, np.array([3, 6]))
Out[4]: 
[array([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.]],
 
        [[  8.,   9.,  10.,  11.],
         [ 12.,  13.,  14.,  15.]]]),
 array([], shape=(2, 0, 4), dtype=float64),
 array([], shape=(2, 0, 4), dtype=float64)]
```

Edit:
Link to the documentation page : https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.hsplit.html#numpy.hsplit

**Comment by rgommers** [comment]
The output in the html docs for ``hsplit`` is what I get with numpy 1.12.0, and ``assert_allclose(np.split(x, 2, axis=1), np.hsplit(x, 2))`` is True as it should be. So documentation seems correct.
