### ISSUE TITLE
strange behavior with numpy.ndarray

### ISSUE THREAD

**Issue by rhao22** [numpy/numpy#8727]
Hello,

Here is a strange behavior I found with numpy.ndarray. 
I guess it is in numpy, sorry if I post this in the wrong place...

I found it on windows 7 with:
> numpy.version     1.9.2
> python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Dec 18 2014, 16:57:52) [MSC v.1500 64 bit (AMD64)]

But I get the same behavior on a linux (ubuntu) box.

The following code shows it:

```
In [1]: import numpy as np
In [2]: B = np.random.choice(2, 10, replace=True, p=[1,0] )
In [3]: A = B
In [4]: print A
[0 0 0 0 0 0 0 0 0 0]
In [5]: print B
[0 0 0 0 0 0 0 0 0 0]
In [6]: for i in range(10): B[i] = np.random.choice(2, 1, replace=True )
In [7]: if np.array_equal(A, B) : print "A equals B"
A equals B
In [8]: print A
[0 0 1 1 1 1 1 0 0 1]
In [9]: print B
[0 0 1 1 1 1 1 0 0 1]

```
We see that A is modified like B in line 6, it gets the same value. 
This doesn't make sense to me as only B should change.
In [6]: If I change B using that method:
`B = np.random.choice(2, 10, replace=True, p=[0.5,0.5] )
`Then A isn't changed, this should be the normal behavior.

any explanation?

**Comment by rhao22** [comment]
Ok I got it 
my wrong, **sorry**
i didn't know that the = doesn't copy the copy array but only the reference to the array....

**Comment by seberg** [comment]
OK, great if you figured things out, so closed.
