### ISSUE TITLE
c runtime issues with windows numpy wheels from pypi

### ISSUE THREAD

**Issue by matham** [numpy/numpy#8732]
One of our users at Kivy reported a issue with numpy + kivy. 

We provide kivy windows wheels which contains compiled cython code, which we compile with mingwpy. I'm not exactly sure what mingw numpy uses for the pypi wheels. The problem as described by that person is as follows:

> I've been trying to understand why this is happening all day and have finally given in to get some broader input. When I close my app, it always crashes with the following message:
> 
> "This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information"

My system runs the examples shipped with kivy fine. However, I tried adding numpy imports to them and have also noticed some strange behaviors. If numpy is imported before any kivy imports, the app also crashes on close. If numpy is imported after, it closes without issue. Also, the crash only happens on closing the app, otherwise it works fine.

I have previously experienced this behavior outside of numpy before I switched to `mingwpy` for all my python extensions and it seemed to be due to issues with the mingw version used to compile them previously. I have even filed an issue with python: https://bugs.python.org/issue23743.

I wonder what numpy is using to compile the pypi windows wheels and whether it should maybe change to use mingwpy if it doesn't already? For the person with the issue I suggested they use the @cgohlke wheels for numpy rather than the pypi ones and that fixed it.

**Comment by rgommers** [comment]
> I'm not exactly sure what mingw numpy uses for the pypi wheels.

Those are all compiled with MSVC.

**Comment by matthew-brett** [comment]
But the ATLAS library is compiled with mingw ...

**Comment by rgommers** [comment]
Ah. mingw or mingw-w64? The linked bug report above says the issue with with mingw from mingw.org (which has been obsolete for a long time AFAIK)

**Comment by matthew-brett** [comment]
Mingw-w64 via Cygwin - I believe.

**Comment by matham** [comment]
Yes, but kivy is compiled with mingwpy that uses minw-w64. I linked to that
issue because the crash is similar. Not sure its the same cause.

**Comment by carlkl** [comment]
Maybe the comments on http://stackoverflow.com/questions/8177152/what-is-the-cause-of-this-application-has-requested-the-runtime-to-terminate-it helps. 
You may try to install the somwhat outdated numpy wheels on https://anaconda.org/carlkl/numpy . These numpy wheels are compiled with mingwpy as well.

**Comment by ahaldane** [comment]
Reviewing this as part of my 10 random issues, as requested in a [3/20/19 request](https://mail.python.org/pipermail/numpy-discussion/2019-March/079250.html).

This compilation issue is now over 2 years old. @matham,  is it still an issue?

**Comment by matham** [comment]
I guess it can be closed for now since I'm not sure if it's still an issue. If someone encounters the issue again they can just reopen.
