### ISSUE TITLE
Unexpected truncation when storing float to int array

### ISSUE THREAD

**Issue by OliverEvans96** [numpy/numpy#8733]
I was caught offguard by the following behavior using numpy 1.12:

### Current behavior
```
In  [1]:  a=array([1,0])
          a[0] = 1 + 1.1  
          print(a.dtype)       
          print(a)
          print(a.dtype)               
Out [1]:  int64
          [ 2  0 ]
          int64 
```

### Expected behavior
```
In  [2]:  a=array([1,0])
          a[0] = 1 + 1.1  
          print(a.dtype)       
          print(a)
          print(a.dtype)               
Out [2]:  int64
          [ 2.1  0. ]
          float64
```

It may be that this is intentional behavior, but I would like to suggest automatic conversion of integer arrays to floating point arrays when a float is saved to an element or slice of the array. I'm not sure how straighforward implementation of this feature would be.

At the very least, there ought to be a warning when truncation occurs, especially since I at no point in the above code explicity declare the dtype of A to be int64, so I (and I think most users) would expect it to default to float64.

I'm interested in opinions on the matter.

Thanks,
Oliver

**Comment by eric-wieser** [comment]
Automatic conversion can be a very expensive operation if the array is large, so I'm definitely -1 on that. A warning seems pretty reasonable though, and it wouldn't surprise me if a mechanism already exists to do that.

**Comment by OliverEvans96** [comment]
Thanks for the reply. Do you know where one would start looking in order to
implement such a warning?

On a philosophical note, we have two possible behaviors; one is logical
from the naive user's perspective, and the other is far cheaper. Is it best
to default to the user-friendly behavior and issue a warning about
inefficiency, or to default to the efficient behavior and issue a warning
about potential user misuse?

**Comment by eric-wieser** [comment]
That choice is mostly irrelevant - the important thing is that It's best to default to the backwards-compatible behaviour.

**Comment by OliverEvans96** [comment]
That makes sense. Thanks for the info!

**Comment by eric-wieser** [comment]
Ok, so here's where it's already implemented:

```python
>>> a=array([1,0])
>>> np.copyto(a[0,...], 1 + 1.1)
TypeError: Cannot cast scalar from dtype('float64') to dtype('int32') according to the rule 'same_kind'
```

**Comment by OliverEvans96** [comment]
Got it. I'm not familiar with Python.h, but I'm looking through the
multiarraymodule.c file and vaguely understanding what's going on in the
copyto function. It seems like the key line is 1782:
```    NPY_CASTING casting = NPY_SAME_KIND_CASTING;```

Now, do you know which function is called when I execute `a[0] = 1.1` ?
I.e., where the warning should be implemented?

**Comment by eric-wieser** [comment]
`array_assign_subscript` is most like the place to look.

**Comment by eric-wieser** [comment]
Digging deeper into `copyto`, it looks like you'd want to add

    if (!PyArray_CanCastTypeTo(PyArray_DESCR(src), PyArray_DESCR(dst), casting))

somewhere.

I think if you did implement this, it should take the form of `np.setconfig(casting='same-kind')` or some global setting like floating point warnings.

**Comment by charris** [comment]
We should definitely raise an error for this. ISTR that this issue may have been reported before.

**Comment by pv** [comment]
I expect error would have backward compatibility issues --- which is why 
complex->real casts don't raise either by default (you can make them 
raise by using warnings module to catch Complexwarning).

**Comment by eric-wieser** [comment]
Hmm, what's the end goal here?

If I have this code
```
a = np.zeros((100, 100), dtype=np.int8)
b = np.zeros((100,), dtype=float64)

a[0] = b
```

We want it to throw a warning, right? What should that warning encourage if this behaviour is deliberate? `a[0] = b.astype(float)` incurs an extra copy, and `np.copyto(a[0], b, casting=...)` doesn't work for advanced indexing.

**Comment by charris** [comment]
The idea is that most such occurrences will be programming errors. That was certainly the case for complex numbers. Being explicit also has the advantage that the conversion, truncation or rounding, will be clear. The code will also be easier to understand with an explicit cast.

**Comment by eric-wieser** [comment]
Right, but my point is that we have no way of specifying that cast without also doing a copy, do we?

**Comment by charris** [comment]
I think you can use functions for that, copyto for instance. The default conversion of floats is truncation. For inplace addition you can use the np.add with the out parameter, etc.

**Comment by seberg** [comment]
For inplace ufunc, we already have the warning. Assignment is the only thing that is "unsafe" still. (though possibly its just a deprecation warning, don't remember the current state)

**Comment by eric-wieser** [comment]
`out` and `copyto` only work for views, not advanced indexing

**Comment by OliverEvans96** [comment]
Perhaps this is an indication that copyto should support advanced indexing.
Although I'm sure that's non-trivial and may have unintended consequences
elsewhere.

**Comment by eric-wieser** [comment]
Also, I guess I'm making assumptions here about what `__setitem__` does under the hood. It might be that casting incurs a copy even implictly

**Comment by seberg** [comment]
Depends a lot on the code paths taken, most involved ones end up doing much the same as copyto (or even call it for the view cases). Plus object arrays do get an extra copy in some cases. But no, normally there is no copy made. You could add indexing to copyto in principle. I am not quite sure I am convinced that this is the only right thing. OTOH, it is one of those traps learning numpy

**Comment by njsmith** [comment]
Ugh, I thought we had deprecated this. But @seberg's right, we seem to have gone all the way through the deprecation cycle for in-place operations, but missed simple assignment:
```
In [4]: a = np.arange(10)

In [5]: a += 0.5
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-633f1f7b6cb9> in <module>()
----> 1 a += 0.5

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [6]: a[:] = 0.5

In [7]: 
```

I agree with @charris et al that we should deprecate these unsafe conversions on assignments and eventually make them an error.

**Comment by OliverEvans96** [comment]
I'm not sure whether this directly addresses the issue or if it's reasonable, but it just occured to me that there would be no ambiguity in my original situation if a=array([1,0]) defaulted to a float array. If that were the case, then somebody who intended to truncate the value they're saving in an int array would simply explicitly declare a=array([1,0],dtype=int64).

Is there a reason this is not presently the case? Would it break backwards-compatability or be significantly less efficient for most use cases?

**Comment by charris** [comment]
> if a=array([1,0]) defaulted to a float array. If that were the case,

Terrible compatibility break. The default is to use the minimum suitable kind compatible with the given elements.

**Comment by seberg** [comment]
Closing this, part of the discussion here predates gh-25621 by a long time, but it just seems like a question more anyway even back then.

**Comment by turbulent-ajaxform24** [comment]
Here’s something to consider



https://human-readablemoisture26.github.io/douglas253/
