### ISSUE TITLE
Rank calculation in np.linalg.lstsq

### ISSUE THREAD

**Issue by wmdrichards** [numpy/numpy#8740]
For some inconsistent systems, np.linalg.lstsq returns an incorrect matrix rank, though the singular values appear to be correct. np.linalg.matrix_rank returns the correct number

Example:
```
import numpy as np
print 'version:' np.__version__

M = np.array([[0., 1.,  0.,  1.,  2.,  0.],
              [0., 2.,  0.,  0.,  1.,  0.],
              [1., 0.,  1.,  0.,  0.,  4.],
              [0., 0.,  0.,  2.,  3.,  0.]])

b = np.array([1, 0, 0, 0, 0, 0])

x, res, rank, s = np.linalg.lstsq(M.T, b)

print 'rank from matrix_rank:', np.linalg.matrix_rank(M.T)
print 'rank from lstsq:', rank
print 's', s
print 'x', x
```

output (I get the same results with 1.12):
```
version: 1.11.2
rank from matrix_rank: 3
rank from lstsq: 4
s [  4.44364340e+00   4.24264069e+00   2.06253080e+00   5.36052001e-16]
x [ -1.48023635e+15   7.40118177e+14  -6.25000000e-02   7.40118177e+14]
```

**Comment by seberg** [comment]
seems like lstsq uses a different (maybe less sensible, at least in the sense of matrix rank) default for the tolerance/rcond parameter to the svd, so one will accept that tiny value, the other does not.

**Comment by charris** [comment]
The `lstsq` call uses `rcond` equal to machine precision by default, whereas `matrix_rank` uses
```
tol = S.max() * max(M.shape) * finfo(S.dtype).eps
```
i.e., it scales with matrix size, so probably does a better job of accounting for roundoff error. The polynomial fit routines are even more conservative
```
I've noticed that `lstsq` will happily produce bogus fits with the default settings, maybe we should change that. Note that the polynomial fitting routines also pass more conservative values when they call `lstsq`.

**Comment by seberg** [comment]
I am all for trying to get the most sensible defaults, most users will use the default in any case. The question is how to get there....

**Comment by divenex** [comment]
I agree that `np.linalg.lstsq` default `rcond=-1` is not a good choice and will lead to problems to most users, when the matrix is nearly rank deficient.

A much better default would be `rcond=max(M.shape)*np.finfo(M.dtype).eps`

This approach is already used both by `np.linalg.matrix_rank`, as already noted by @charris, and also by `scipy.linalg.lstsq`

**Comment by seberg** [comment]
We now got a warning and in place to change the defaults to lstsq (gh-9582) so closing this.
