### ISSUE TITLE
numpy.poly1d.__eq__ method fails with AttributeError

### ISSUE THREAD

**Issue by bondarevts** [numpy/numpy#8760]
I called the `inspect.signature` function on a `numpy.poly1d` object:
```python
import numpy as np
import inspect
poly = np.poly1d([1, 2, 3])
print(inspect.signature(poly))
```
and got an unexpected exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.5/inspect.py", line 2987, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/python3.5/inspect.py", line 2737, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/python3.5/inspect.py", line 2228, in _signature_from_callable
    if _signature_is_builtin(obj):
  File "/python3.5/inspect.py", line 1785, in _signature_is_builtin
    obj in (type, object))
  File "/python3.5/site-packages/numpy/lib/polynomial.py", line 1203, in __eq__
    if self.coeffs.shape != other.coeffs.shape:
AttributeError: type object 'type' has no attribute 'coeffs'
```

So `numpy.poly1d` objects can be compared only to objects with special attributes structure.

The current`__eq__` implementation from [v.1.12.x](https://github.com/numpy/numpy/blob/maintenance/1.12.x/numpy/lib/polynomial.py#L1201-L1204):
```python
def __eq__(self, other):
    if self.coeffs.shape != other.coeffs.shape:
        return False
    return (self.coeffs == other.coeffs).all()
```

numpy version 1.12.0

**Comment by eric-wieser** [comment]
That should probably have a `if not isinstance(other, poly1d): return NotImplemented`

**Comment by bondarevts** [comment]
I think `if not isinstance(other, poly1d): return False` is better.
With `raise NotImplemented` we still will have the same problem.

**Comment by eric-wieser** [comment]
@bondarevts: Indeed, that is why I suggested `return NotImplemented` and not `raise NotImplementedError`

**Comment by bondarevts** [comment]
> Indeed, that is why I suggested return NotImplemented
@eric-wieser You're right. I read it wrong. Thank you for the clarification.
