### ISSUE TITLE
DEP: Deprecate np.poly1d

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8763]
Is this a sensible thing to do? Right now, the docs for `np.poly1d` do not contain any mention of its successor `np.polynomial.Polynomial`

**Comment by rgommers** [comment]
It's not, it's too heavily used (search the scipy code base for example).

The ``poly1d`` docs can explain that ``Polynomial`` is the recommended class to use, but any more than nudging users in the docs isn't really possible.

**Comment by stefanv** [comment]
I don't think we can reasonably deprecate `poly1d`: it is used all over the place, and differs in behavior from `Polynomial`.  I'm going to close, for now; please reopen if you disagree.

**Comment by eric-wieser** [comment]
> and differs in behavior from Polynomial. 

I think the argument goes that the difference in behavior is a design flaw.

> I don't think we can reasonably deprecate `poly1d`

I suspect if we did:

* We need to make `Polynomial` a more compelling replacement. In my mind, that would mean allowing it to be used without the `domain` / `window` stuff unless explicitly requested.
* We would need to take a very long `np.matrix`-style approach.

If nothing else, i think we might want to leave this open to track documenting `Polynomial` in more places as an intended replacement for `poly1d`, although I think such a tracking issue might already exist elsewhere. One possible reason for pushing this is:

![image](https://user-images.githubusercontent.com/425260/70576181-91a22600-1ba8-11ea-9ab9-52947e6b6d0e.png)

**Comment by stefanv** [comment]
We should probably fix that.

```
In [1]: import numpy as np                                                                                                                                                                                                          

In [2]: np.poly1d([3, 2, 1, 0])                                                                                                                                                                                                     
Out[2]: poly1d([3, 2, 1, 0])

In [3]: print(_)                                                                                                                                                                                                                    
   3     2
3 x + 2 x + 1 x
```

I think if we add the symbol and ability to switch off scaling, we'd be close.  @charris would have to weigh in too.

**Comment by charris** [comment]
The default scaling is 1.0, if you don't specify the domain it acts like a normal polynomial. The only place I think that might be annoying is the `linspace` method domain defaults to that of the polynomial, but that can be overridden.

**Comment by charris** [comment]
The other place is least squared fitting, but since folks routinely do that badly, I think the default scaling is appropriate, especially with Chebyshev and Legendre polynomial. ISTR an example that gave bad results out of the box for commercial software, precision about 1e-4, where poly1d did better, about 1e-7 (because of column scaling), and Polynomial managed 1e-14 (after converting to the usual form). The problem was the ill conditioned design matrix that results from using an unscaled and unshifted basis.

**Comment by rgommers** [comment]
> If nothing else, i think we might want to leave this open to track documenting `Polynomial` in more places as an intended replacement for `poly1d`, although I think such a tracking issue might already exist elsewhere.

There's gh-13113 and gh-13602 at least. Since the title and discussion of this issue is about deprecating `poly1d`, which we really shouldn't do, I think it's better not to reopen this.
