### ISSUE TITLE
Full numpy array shape not recognized

### ISSUE THREAD

**Issue by seaotterman** [numpy/numpy#8766]
I think it is best explained through a simple example:

```python
a = [np.empty([10, 20]), np.empty([20, 10])]
print(np.shape(a))
>> (2,)

b = [a, a, a]
print(np.shape(b))
>> (3, 2)

c = np.swapaxes(b, 0, 1)
print(np.shape(c))
>> (2, 3)

print(np.shape(c[0]))
>> (3,)
# expected: (3, 10, 20)

print(np.shape(np.array(c[0])))
>> (3,)
# expected: (3, 10, 20)

# workaround
d = list(c[0])
print(np.shape(d))
>> (3, 10, 20)
```

Numpy should figure out that the elements in `c[0]` are all of the same shape and therefore recognize its shape as `(3, 20, 30)`, especially after the `np.array()` call.

Using `np.transpose(c, [1, 0])` instead of `np.swapaxes(c, 0, 1)` yields the same result.

Since I am unfamiliar with numpy's internal specifics, I am not entirely sure if this is a bug or expected behavior.

Tested on Python 2 and 3. Numpy version: 1.12.0 (latest). OS: OS X 10.11.6.

**Comment by eric-wieser** [comment]
It's worth noting that the implementation of `np.shape(a)` is basically `np.asanyarray(a).shape`.

If you have a look at `np.asanyarray(a)`, you'll see it has `dtype=object`. I'd suggest using a much smaller array so that you can see what's going on.

This isn't really a bug, and is more a case of object arrays containing arrays being difficult and sometimes surprising to construct.

**Comment by seaotterman** [comment]
Thanks for the very quick answer! I wasn't sure about np.shape calling np.asanarray(), but it explains why calling `np.array()` doesn't change anything.

If this is not a bug, is the workaround of casting the array into a list and back to a numpy array actually the most straightforward solution to this? Feels a bit clunky, especially in situations where the array cannot be built up in another way to avoid this.

**Comment by eric-wieser** [comment]
> Numpy should figure out that the elements in c[0] are all of the same shape

It's already too late here. You've already got an `np.array` in `c[0]` by this point, so numpy figures out _"I shouldn't just randomly reshape stuff that someone already has in an array"_

**Comment by eric-wieser** [comment]
> If this is not a bug, is the workaround of casting the array into a list and back to a numpy array actually the most straightforward solution to this

You could also try using a structured array:
```python
dt = np.dtype([('h', int, (3, 6)), ('v', int, (6, 3))])  # smaller so you can see what is up
a = np.array((np.zeros([3, 6], int), np.zeros([6, 3], int)), dtype=dt)
b = [a, a, a]
# no axes to swap any more, so can't compute c
d = np.array(b)['h']

a.shape  # ()
np.shape(b)  # (3,)
d.shape  # (3, 3, 6)
```

**Comment by seaotterman** [comment]
Thanks, will check it out!
