### ISSUE TITLE
Unusual behaviour of linalg.inv()

### ISSUE THREAD

**Issue by shailesh210** [numpy/numpy#8769]
When I try `a=np.array([[1,2,1],[-2,-3,1],[3,5,0]])`
 and then 
`np.linalg.inv(a)`,

 the output is:

```
array([[ -3.75299969e+15,   3.75299969e+15,   3.75299969e+15],
      [  2.25179981e+15,  -2.25179981e+15,  -2.25179981e+15],
        [ -7.50599938e+14,   7.50599938e+14,   7.50599938e+14]])
```

But when I try `a=np.array([[1,8,50],[8,64,400],[50,400,2500]])` and then `np.linalg.inv(a)`, it fails to give an output saying that it is a singular matrix.
But the first matrix was also a singular one, then why did it not raise the error and gives an output which is technically wrong?

Thanks in advance!

**Comment by eric-wieser** [comment]
Relatedly, `np.linalg.det(a)` doesn't give `0` here in either case

**Comment by shailesh210** [comment]
Hi @eric-wieser 
Good you pointed out that :)
It gives determinant zero in the latter case but not in the first. Whereas both the determinants are zero.

**Comment by eric-wieser** [comment]
> It gives determinant zero

Not on my machine:

```python
>>> a=np.array([[1,8,50],[8,64,400],[50,400,2500]])
>>> np.linalg.det(a)
-6.9333477997941029e-29
```

**Comment by shailesh210** [comment]
I tried online IDE. But in either case it should not give that. 
Any idea why is it so?

**Comment by eric-wieser** [comment]
Because numpy uses floating-point lapack routines even for integer arrays, which make no promise about exactness.

**Comment by shailesh210** [comment]
Hi @eric-wieser 
But even if it uses floating-point routines, how does it reaches the result. 
Does it follows a different algorithm to find inverse or it just fails to raise an error sometimes?

**Comment by matthew-brett** [comment]
Is BLAS doing something other than Gaussian elimination here?   Doing it now by hand, I can't see where floating point precision would cause trouble before hitting the 0 pivot at `a[2, 2]`.

**Comment by charris** [comment]
@matthew-brett It uses row pivoting, that is, it brings the row whose leading element has the largest absolute value to the top of the remaining rows that need processing. In the first example elimination starts with the row `[3,5,0]`, so there will already be a division by 3 with inexact results when that row is used to eliminate the remaining leading elements.

For problems like this the singular value decomposition is recomended. Numerically, both matrices are singular by that method.

**Comment by matthew-brett** [comment]
@charris - thanks for the explanation.

**Comment by shailesh210** [comment]
Can someone please elaborate whether this is a bug or I need to learn more about invert and determinant of a matrix.

**Comment by eric-wieser** [comment]
Not a bug - the two things you should take away from this are:

* Floating point arithmetic cannot represent real numbers exactly
* Different methods of inverting/taking the determinant of a matrix may produce mathematically equal results, but that doesn't mean the results are numerically equal.
