### ISSUE TITLE
ENH: Integer gcd function

### ISSUE THREAD

**Issue by brsr** [numpy/numpy#8772]
Essentially, `math.gcd`, but operating on numpy arrays with `dtype=` something in the `int` family.

    >>> a = np.arange(4)
    >>> b = np.arange(10,14)
    >>> np.gcd(a, b)
    array([10, 1, 2, 1])

Would support broadcasting:

    >>> c = 2
    >>> np.gcd(b, c)
    array([2, 1, 2, 1])

Might want to have a version that operates on multiple values (more than 2) on an axis of a multivariable array:

    >>> d = np.arange(9).reshape((3, 3))
    >>> np.gcd_along_axis(d, axis=1)
    array([3, 1, 1])

(This is slightly related to #4829.)

**Comment by eric-wieser** [comment]
Sounds like you're after a `gufunc` for `gcd` (and why not `lcm` as well?)

Although `lcm` could be implemented as a regular `ufunc` here and then you could use `np.lcm.reduce(d, axis=...)` for your second case.
