### ISSUE TITLE
BUG: #8570 broke pandas and scipy.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#8776]
Taken from https://github.com/numpy/numpy/pull/8570#issuecomment-285961193

> This broke one of our tests downstream because this is now not returning an array (but a list). I don't think this is what you want?
> 
> You are testing this input, but not that it actually returns an ndarray (just that it is equal).
> 
> https://travis-ci.org/pandas-dev/pandas/jobs/210272568
> ```
> In [5]: np.__version__
> Out[5]: '1.13.0.dev0+cf349c9'
> 
> In [6]: np.random.permutation([(0, 1), (1, 0)])
> Out[6]: [(0, 1), (1, 0)]
> ```
> ```
> In [1]: np.__version__
> Out[1]: '1.12.0'
> 
> In [2]: np.random.permutation([(0, 1), (1, 0)])
> Out[2]: 
> array([[1, 0],
>        [0, 1]])
> ```

**Comment by eric-wieser** [comment]
Mirroring another remark downstream: `np.random.permutation(range(10))` causes an error.

**Comment by charris** [comment]
`np.random.shuffle(range(10))` is inplace, so the result goes away.
