### ISSUE TITLE
The numpy documentation is down and unreachable

### ISSUE THREAD

**Issue by GDICommander** [numpy/numpy#8779]
Hello,

I'm not sure if I should report it here on GitHub, but the numpy documentation is down.

Accessing http://docs.scipy.org/ results in a timeout. From Chrome:

```
tcp_error: A communication error occurred: "Operation timed out"
```

Have a good day!

**Comment by pv** [comment]
Known issue, people are on it.

**Comment by bryevdv** [comment]
Any ETA on this? Any CI docs builds that utilize intersphinx from SciPy are failing

**Comment by rgommers** [comment]
Not sure. Cc'ing @dpinte on this issue.

**Comment by dpinte** [comment]
The server has been completely migrated to a new clean VM overnight. There are some final little glitches related to undocumented features that need to be migrated and we will be good to go. ETA is end of day today!

**Comment by rgommers** [comment]
Awesome, thanks for the update Didrik

**Comment by jakelee8** [comment]
Would it be possible to use the CloudFlare always-online cache? This is not the first time I've noticed scipy.org is down.

**Comment by JosephKJ** [comment]
Is there any alternative to access docs?

Can we build the docs on a mac?

**Comment by endolith** [comment]
> Is there any alternative to access docs?

http://scipy.github.io/devdocs/ ?

**Comment by matthew-brett** [comment]
Suggestion to move docs hosting to github : https://mail.scipy.org/pipermail/numpy-discussion/2017-March/076578.html

**Comment by dpinte** [comment]
The key issue is not hosting in this case but the documentation of what's been stored, where and how. We're working with machines that have been installed many years ago, have seen multiple maintainers touching configuration with various level of expertise, etc. It is a nice example of what entropy is!

Once everything will be back online, we can investigate any other hosting ideas. For the future, the real thing that needs to be addressed is the documentation of the infrastructure and ensuring that a policy existing for maintaining that infrastructure.

The scipy.org site is back online but there is a 500 for docs.scipy.org and when accessing www.scipy.org directly.

**Comment by horejsek** [comment]
Still can't access it. Can anyone at least attach here objects.inv? Our documentations depends on it and we don't have cached version now.

**Comment by Naereen** [comment]
Thanks to all the nice sysadmin working on that, good luck! you are the best :1st_place_medal:

**Comment by dpinte** [comment]
docs.scipy.org is back online!

**Comment by dpinte** [comment]
The performance is not there yet but the pages are served!

**Comment by bryevdv** [comment]
Intershinx is still not working:
```
sphinx.errors.SphinxWarning: WARNING: intersphinx inventory 'http://docs.scipy.org/doc/numpy/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='docs.scipy.org', port=443): Max retries exceeded with url: /doc/numpy/objects.inv (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2ab30b6ebac8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by dpinte** [comment]
Performance issue has been fixed.

@bryevdv investigating the issue. I see there is something wrong:

```
$ wget http://docs.scipy.org/doc/numpy/objects.inv
--2017-03-15 17:48:01--  http://docs.scipy.org/doc/numpy/objects.inv
Resolving docs.scipy.org (docs.scipy.org)... 50.17.248.72
Connecting to docs.scipy.org (docs.scipy.org)|50.17.248.72|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://docs.scipy.org/doc/numpy/objects.inv [following]
--2017-03-15 17:48:01--  https://docs.scipy.org/doc/numpy/objects.inv
Connecting to docs.scipy.org (docs.scipy.org)|50.17.248.72|:443... connected.
ERROR: The certificate of ‘docs.scipy.org’ is not trusted.
ERROR: The certificate of ‘docs.scipy.org’ hasn't got a known issuer.
```

**Comment by bkreider** [comment]
You might want to append the intermediate CA cert to the the server's cert.  Most browsers will look for the intermediate cert but not all client libraries.  

```
Certificate chain
 0 s:/C=US/ST=Texas/L=Austin/O=Enthought, Inc./OU=IT/CN=*.scipy.org
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
```

The Certificate matching the issuer above: `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA`

**Comment by dpinte** [comment]
@bryevdv can you check now? Apache should be much happier than 10' ago

**Comment by dopplershift** [comment]
I'm still seeing this on Travis:
```
WARNING: intersphinx inventory 'https://docs.scipy.org/doc/numpy/objects.inv' not fetchable due to <class 'requests.exceptions.SSLError'>: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
```

**Comment by bkreider** [comment]
Actually here is the Qualys Labs SSL report saying the same thing: https://www.ssllabs.com/ssltest/analyze.html?d=docs.scipy.org

Look under "chain issues" and "Certification paths":

![screen shot 2017-03-15 at 6 33 19 pm](https://cloud.githubusercontent.com/assets/1699478/23962311/f71e5b9e-09ad-11e7-827e-c6969b140884.png)

SSL will still work under Firefox, chrome, safari, etc because the will download that certificate on their own, but client libraries like requests probably will not.

**Comment by Naereen** [comment]
Great job everybody!

**Comment by bryevdv** [comment]
@dpinte still failing:

https://travis-ci.org/bokeh/bokeh/jobs/210962890#L1674-L1755

**Comment by dpinte** [comment]
@bryevdv now it fails with a certificate issue, which make sense. We will bundle the intermetiade cert and that will fix the issue.

**Comment by dpinte** [comment]
@bryevdv the intermediate certificate has been added locally. You should be able to download the file as expected

**Comment by bryevdv** [comment]
Thanks, working now

**Comment by dopplershift** [comment]
The server still seems really slow to access for me...

**Comment by dpinte** [comment]
@dopplershift can you provide timings? We're continuing to monitor it and still tweaking some Apache configurations.

**Comment by dopplershift** [comment]
They seem more reasonable now, though it's still taking Safari 11 seconds to load the page. At least my sphinx build isn't timing out now, though.

**Comment by dpinte** [comment]
11 seconds is a lot. What page do you try to load?

**Comment by dopplershift** [comment]
Just https://docs.scipy.org/

When I tried just now, though, things were much better.

**Comment by Naereen** [comment]
Things are perfectly fine now, from my tests.
Good job everybody :+1: !

**Comment by bryevdv** [comment]
FYI I'm seeing timeouts on intersphinx accessing `objects.inv` which is causing our builds to fail again.  Navigating to spicy.org by hand, just tool 8-10 seconds to load

**Comment by jrleeman** [comment]
Just took about 25 seconds to load here

**Comment by dpinte** [comment]
Confirmed. Investigating. The machine load is low. More than likely some tweaks for the Apache configuration

**Comment by dopplershift** [comment]
Not sure if I should post here or open anew, but seeing problems again.

**Comment by bryevdv** [comment]
same, docs.scipy.org is down and CI builds that rely on intersphinx are failing.

**Comment by bryevdv** [comment]
ping @dpinte @rgommers

**Comment by dpinte** [comment]
@bryevdv looking at it. AWS console reported it has been unreachable since 31'. Restarting it

**Comment by dpinte** [comment]
@bryevdv we should be back online. There seem to be some hardware issue with the AWS VM. Restarted and fully updated now

**Comment by bryevdv** [comment]
Thanks!
