### ISSUE TITLE
BUG: np.linalg.inv rejects scalar input

### ISSUE THREAD

**Issue by jpreiss** [numpy/numpy#8785]
The inverse of a 1x1 matrix `A = [a]` is `[1 / a]`, but `np.linalg.inv()` doesn't handle this case.

With a true scalar (or NumPy scalar):

	>>> a = 8 # or a = np.float64(8)
	>>> np.linalg.inv(a)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "<snip>/numpy/linalg/linalg.py", line 445, in inv
		return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
	IndexError: tuple index out of range

Or with a one-element array:

	>>> b = np.array([8])
	>>> np.linalg.inv(b)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "<snip>/numpy/linalg/linalg.py", line 445, in inv
		return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
	  File "<snip>/numpy/linalg/linalg.py", line 311, in solve
		_assertRank2(a, b)
	  File "<snip>/numpy/linalg/linalg.py", line 155, in _assertRank2
		two-dimensional' % len(a.shape)
	numpy.linalg.linalg.LinAlgError: 1-dimensional array given.
	Array must be two-dimensional

It's possible to get around this issue with `b.reshape(1,1)`, but this is not a good solution when the 1x1 matrix is a special case of an algorithm that generally works with `n >= 1` dimensions.

As a transitioning Matlab user, I may be too infected by the "everything's a matrix" attitude. However, since NumPy converts some general matrix results to scalar when appropriate (e.g. `x.T.dot(x)`), it seems reasonable to also treat scalar inputs as 1x1 matrices when appropriate.

Python 2.7, NumPy 1.6.2, verified present in 1.11 also.

**Comment by eric-wieser** [comment]
This is definitely by design, but that's not the same as saying the design is a good one.

> converts some general matrix results to scalar when appropriate (e.g. `x.T.dot(x)`)

I don't believe you:

```python
>>> x = np.array([[1], [2], [3]]); x
array([[1],
       [2],
       [3]])
>>> x.T.dot(x)
array([[14]])
```

>> special case of an algorithm that generally works with n >= 1 dimensions.

What do you mean? This doesn't work when n = 1 either: `np.linalg.inv([1, 2, 3])`

**Comment by eric-wieser** [comment]
>     IndexError: tuple index out of range

Ah, this one definitely is a bug - it should raise the same error as the following example

**Comment by jpreiss** [comment]
Sorry, my comment "special case of an algorithm that generally works with n >= 1 dimensions" was unclear.

The example I had in mind was implementing the Gauss-Newton method for nonlinear least squares curve fitting. (It would be better to use a solve, but suppose we are being sloppy 😉). The algorithm looks like:

def gauss_newton(x_data, y_data, param, curve_fn, curve_jacobian_fn):
	ITERS = 20
	for i in range(ITERS):
		residual = y_data - curve_fn(x_data, param)
		J = curve_jacobian_fn(x_data, param)
		param = param + np.linalg.inv(J.T.dot(J)).dot(J.T.dot(residual))
	return param

where `curve_jacobian_fn` should return the jacobian of the curve function with respect to the parameters, evaluated at each data point in `x_data`. In this case, when the curve function has a single parameter, it is natural (in my opinion, but maybe I'm wrong?) to write `curve_jacobian_fn` to return a 1D array. Then `J.T.dot(J)` is like:

    >>> a = np.array([1, 2, 3])
    >>> a.T.dot(a)
    14

I tested the tuple index bug in 1.11, you are right, it is replaced by the "must be two-dimensional" exception.

**Comment by eric-wieser** [comment]
> it is natural (in my opinion, but maybe I'm wrong?) to write curve_jacobian_fn to return a 1D array

**Comment by eric-wieser** [comment]
Remember that `J.T == J` if  is 1D. If you want something to have matrix semantics, then you should return a matrix

> In this case, when the curve function has a single parameter it is natural (in my opinion, but maybe I'm wrong?) to write `curve_jacobian_fn` to return a 1D array

IMO, you are wrong here. The model for your function seems to be _"there are `n` parameters"_. If `n == 1`, then you should represent that as `params = np.array([p1])`. Dimensions tell you information about what type of variable you're working with. Don't just drop dimensions because they happen to be size 1.

**Comment by jpreiss** [comment]
That is a good point. Perhaps Matlab has made me careless with dimensions :).

**Comment by eric-wieser** [comment]
I think there might be some other examples though where specifically 0d &rarr; 2d is a sensible conversion.

For instance, it might be nice if `some_2d @ some_0d` were allowed, behaving as if scalars were promoted to square identity matrices of the right size
