### ISSUE TITLE
np.hstack([ ]) throws IndexError instead of ValueError

### ISSUE THREAD

**Issue by medakk** [numpy/numpy#8790]
Calling `np.hstack([ ])` throws an `IndexError`. It takes a bit more work to find out the root cause of the error, ie: the empty list.
```
>>> import numpy as np
>>> np.hstack([ ])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/core/shape_base.py", line 277, in hstack
    if arrs[0].ndim == 1:
IndexError: list index out of range
```

`np.vstack`, on the other hand, throws a more appropriate error.

```
>>> np.vstack([ ])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/core/shape_base.py", line 230, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

**Comment by ZZhaoTireless** [comment]
I would take this. Thanks!

**Comment by ZZhaoTireless** [comment]
@eric-wieser What error message would you prefer to use there? How about `ValueError: need at least one element to concatenate`?

And if add 
`if len(arrs) == 0:
        raise ValueError('need at least one element to concatenate')`
before the line [if arrs[0].ndim == 1:](https://github.com/numpy/numpy/blob/master/numpy/core/shape_base.py#L286) is an acceptable solution?
