### ISSUE TITLE
Bad regexp in crackfortran.py

### ISSUE THREAD

**Issue by jwilk** [numpy/numpy#8791]
`numpy/f2py/crackfortran.py` contains the following code:
```python
determineexprtype_re_3 = re.compile(
    r'\A[+-]?[\d.]+[\d+-de.]*(_(P<name>[\w]+)|)\Z', re.I)
```
But here `+-d` means all characters between `+` and `d`, which includes, among others, all uppercase letters and a bunch of punctuation characters.
If you want `-` to be meant literally, you need to escape it, or place it as the first or last character inside `[]`.

The dubious regexp was found using [pydiatra](https://github.com/jwilk/pydiatra).

**Comment by charris** [comment]
Looks like a valid problem

**Comment by ZZhaoTireless** [comment]
Hi, could I take this issue? I would like to make contribution here :)

**Comment by charris** [comment]
Sure, no need to ask permission to submit a fix.

**Comment by ZZhaoTireless** [comment]
Thanks!
