### ISSUE TITLE
multiarray ImportError when importing numpy module

### ISSUE THREAD

**Issue by kayla8l** [numpy/numpy#8794]
```  File "/usr/local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```

I keep getting this error when trying to import numpy. I have tried to `pip uninstall` and `pip install` numpy as well as manually delete the files and reinstalling numpy.

**Comment by charris** [comment]
Out of curiosity, which version of Numpy did pip say it was installing?

**Comment by charris** [comment]
Is there another version of numpy in `~/.local`?

**Comment by rgommers** [comment]
no follow-up, closing. for users that see this issue in the future: please see https://github.com/numpy/numpy/issues/9047#issuecomment-385226000

**Comment by devedse** [comment]
Yeah, this strange buggy monster they call a language (python) apparently just loads python libraries from random places on your computer:
I removed a folder named Python in AppData/Roaming which fixed my issue.
