### ISSUE TITLE
numpy.r_ seems to cache string beyond failing call

### ISSUE THREAD

**Issue by Dominik1123** [numpy/numpy#8815]
Consider the following code:

```python
from __future__ import print_function

import numpy as np

a = np.ones((3, 3, 3))
b = np.zeros((3, 3))

# Uncommenting this will make the below call to `np.r_` work.
# try:
# 	np.r_['2,3', a, b]
# except ValueError:
# 	print('failure')

print(np.r_[a, b.reshape((3, 3, 1))])
```

This fails with:

        Traceback (most recent call last):
      File "test.py", line 13, in <module>
        print(numpy.r_[a, b.reshape((3, 3, 1))])
      File "/usr/local/lib/python2.7/dist-packages/numpy/lib/index_tricks.py", line 338, in __getitem__
        res = _nx.concatenate(tuple(objs), axis=self.axis)
    ValueError: all the input array dimensions except for the concatenation axis must match exactly

All right as the dimensions don't match indeed. However uncommenting the above `try/except` block will make the second call to `numpy.r_` work, just as it was `numpy.r_['2,3', a, b.reshape((3, 3, 1))]` instead (stacking along the last axis). So it seems that `numpy.r_` still has that string from the previous failing call cached and is using it for the second call.

    failure
    [[[ 1.  1.  1.  0.]
      [ 1.  1.  1.  0.]
      [ 1.  1.  1.  0.]]

     [[ 1.  1.  1.  0.]
      [ 1.  1.  1.  0.]
      [ 1.  1.  1.  0.]]

     [[ 1.  1.  1.  0.]
      [ 1.  1.  1.  0.]
      [ 1.  1.  1.  0.]]]

Tested on:
* Python 2.7.12 + numpy==1.12.0
* Python 3.5.2 + numpy==1.12.0

**Comment by eric-wieser** [comment]
To confirm, what is the expected behaviour here for the second call? Obviously it shouldn't depend on previous invocations - but should it fail or succeed?

**Comment by eric-wieser** [comment]
I'm really struggling to comprehend here why `r_` and `c_` have state, and why they mutate it. That just seems like a recipe for (this) disaster

**Comment by eric-wieser** [comment]
This also afflicts `np.ma.mr_`, which duplicates most of the code. Great.

**Comment by tranquil-coder** [comment]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.r_.html Negative integers specify where in the new shape tuple the last dimension of upgraded arrays should be placed, so the default is ‘-1’.

what does this sentence mean?

np.r_['0,2,-5', [1,2,3],[4,5,6] ] # ValueError: all the input array dimensions except for the concatenation axis must match exactly
np.r_['0,2,-6', [1,2,3],[4,5,6] ] # array([[1],[2],[3],[4],[5],[6]])

-5 and -6 both exceed dims bund, why -6 can run ,but -5 can not
