### ISSUE TITLE
exponential and trigonometrical functions aren't using the faster (than libm) libimf

### ISSUE THREAD

**Issue by damianam** [numpy/numpy#8823]
numpy relies on the scalar version of these functions provided by the python standard library. The problem is that frequently the python interpreter (and standard library) are compiled with GCC (in linux platforms) and linked with `-lm`. I think there is an important but easy optimization opportunity in intel platforms if numpy is made aware of the compiler it is being compiled with, and act accordingly. What that means in this context is using `-limf` for these functions, instead of relying on what is provided by the standard library. Using the intel optimized primitives from `libimf` can be 2x faster.

One example:

```
$ cat numpy_exp.py
import numpy as np
import time
N = 10000000
repeats = 10
a = np.random.random(N)
t0 = time.time()
for i in range(repeats):
        ax = np.exp(a) # alternatively use sin, atan2, ...
        t1 = time.time()
        print("Test took %.6f s" % (t1 - t0))
```

Results with the interpreter compiled with GCC 5.4.0 and numpy with icc 2017.2 and MKL 2017.2 (even though for this particular test it doesn't matter if MKL is used or not):

```
$ python numpy_exp.py
Test took 0.317490 s
Test took 0.635600 s
Test took 0.953398 s
Test took 1.271579 s
Test took 1.589239 s
Test took 1.907361 s
Test took 2.225147 s
Test took 2.543188 s
Test took 2.860913 s
Test took 3.178903 s
```

Results with both the interpreter and numpy with icc 2017.2 (all other things equal):

```
$ python numpy_exp.py
Test took 0.138923 s
Test took 0.277856 s
Test took 0.417010 s
Test took 0.556243 s
Test took 0.695368 s
Test took 0.834127 s
Test took 0.973219 s
Test took 1.112011 s
Test took 1.251062 s
Test took 1.389904 s
```

Using `LD_PRELOAD=/path/to/libimf.so python numpy_exp.py` shows the same good results (ie: recompiling the whole standard library with icc is not necessary, just using libimf's functions).

In my opinion there are two possible ways forward:

1. Stop reusing `math.exp` and related (or `math` altogether?) from the standard library, and leverage icc (and with it libimf) during numpy's build process. I suppose the code can be taken from the standard library and put in a separate namespace. This seems like the most portable approach, and it would work with other compilers/platforms having similar effects.
2. During numpy's init, hack the loader to have the same effect than the `LD_PRELOAD` would. I have no idea if there are similar things to be done for non-linux platforms.

Does this seem like a reasonable suggestion? It looks to me like there is potentially a lot of people out there that can benefit from addressing this issue.

**Comment by njsmith** [comment]
Numpy is using libm, which has nothing to do with the python standard
library "math" module (except that math also uses libm).

How accurate are the libimf routines? It's very common to see different
versions of libm be faster or slower depending on how sloppy they're
willing to be.

In any case, we certainly could support linking against libimf if someone
is motivated to make the appropriate build system changes. I have no idea
how difficult this would be, and we mostly rely on external contributions
for Intel library related support.

**Comment by damianam** [comment]
> Numpy is using libm, which has nothing to do with the python standard
> library "math" module (except that math also uses libm).

That is not the issue here. My understanding is that the vectorized version of `exp` that numpy provides is simply calling `math.exp` underneath, which is using whatever C `exp` function is found at compile time. In other words, it depends on the compiler used for compiling the interpreter/standard library, which in most cases come from whatever distribution the user is using. numpy, on the other hand, is often/sometimes compiled with more care (eg: leveraging high performance linear algebra libraries like MKL). It is a pity that compiling numpy with an intel compiler doesn't result in numpy using the faster intel routines.

Regarding accuracy: Intel claims that libimf routines are ~0.55 ULPs (https://software.intel.com/sites/default/files/article/326703/fp-control-2012-08.pdf) I do not know about the typical accuracy for libm though. In any case, they seem to be accurate enough, as they are the default when compiled with intel compilers, which are kind of the gold standard in HPC. They have their issues but they are widely used. So I wouldn't be too concerned about general lack of precision on libimf.

> In any case, we certainly could support linking against libimf if someone
> is motivated to make the appropriate build system changes. I have no idea
> how difficult this would be, and we mostly rely on external contributions
> for Intel library related support.

As I see it now, I don't think this is exclusively a build problem. What has to be done is not simply linking with libimf (that is done already if numpy is compiled with icc), it involves avoiding calls to `math.exp` (and related) in favour of numpy controlled functions that rely on libimf instead of the `math.exp` functions that rely on libm.

**Comment by pv** [comment]
numpy.exp does not call math.exp, it uses the libm function

**Comment by juliantaylor** [comment]
we already support alternative matlibs via the MATLIB environment variable
I used it to link against libmvec and it worked ok.

**Comment by juliantaylor** [comment]
I'd be curious if a libimf numpy passes the scipy tests.

**Comment by damianam** [comment]
> numpy.exp does not call math.exp, it uses the libm function

Funny. I read somewhere that it was doing that, and it seemed to match my results, so I assumed it was true. Any idea then of why changing the compiler of the interpreter results in numpy using libimf instead of libm (libimf gets added by icc transparently)? Maybe related to the stuff defined in `lib/python2.7/_sysconfigdata.py`?

> we already support alternative matlibs via the MATHLIB environment variable at compile time (comma separated libraries, e.g. "-lm,-lmvec")
> I used it to link against libmvec and it worked ok.

Oh, cool, I didn't know about that. Then I guess it is simply a matter of defining that properly when compiling numpy.

> I'd be curious if a libimf numpy passes the scipy tests.

That's a good point. A number of HPC centers using EasyBuild (https://github.com/hpcugent/easybuild) have been building it that way for some time, and the folks at intel seem to be doing something similar with their python distribution, so I naively assume it would pass them, but I'll try to assert it.

**Comment by damianam** [comment]
I dug a bit more, but I have more questions than answers. I could specify `libimf` using `MATHLIB`, but that didn't make any difference.

I assessed then the performance of both setups (interpreter compiled with the intel compiler and compiled with gcc) for the scalar call using `math.exp` and the performance difference seems to be minimal (~3%).

I checked then the performance of both setups calling `numpy.exp` but with vectors of 1 element, and the performance difference didn't go beyond ~6.5%.

I found out that I don't need to preload `libimf.so` to get the best performance. Prepending the path to `libpython2.7.so` in `LD_LIBRARY_PATH` is just as effective:

```
$ python numpy_exp.py
Test took 0.317748 s
Test took 0.635604 s
Test took 0.953847 s
Test took 1.271719 s
Test took 1.589706 s
Test took 1.907617 s
Test took 2.225506 s
Test took 2.543440 s
Test took 2.861266 s
Test took 3.179119 s
$ LD_LIBRARY_PATH=/path/to/intel/compiled/python/libs:$LD_LIBRARY_PATH python numpy_exp.py
Test took 0.138972 s
Test took 0.278184 s
Test took 0.417475 s
Test took 0.556679 s
Test took 0.695796 s
Test took 0.834936 s
Test took 0.974095 s
Test took 1.113354 s
Test took 1.252499 s
Test took 1.391595 s
```

That is regardless of the interpreter itself (ie: if it has been compiled with intel or gcc, the important bit is that `libpython2.7.so` compiled with intel is before in `LD_LIBRARY_PATH` than the one compiled with gcc). Due to that, my current hypothesis is that inside `numpy.exp` there is some call to a function defined in `libpython2.7.so` that is way faster when compiled with intel compilers than when compiled with gcc. However, I've ran before other set of benchmarks comparing both, and I couldn't find any significant differences. I observe them just on exponential or trigonometical functions, which I find extremely odd.

I also checked with `cProfile`, but it doesn't say anything about what is happening inside `numpy_exp.py`. My understanding is that `numpy.exp` gets defined using code generators (https://github.com/numpy/numpy/blob/3b7908d299fc3287486bbe453e2335c1fa50fc29/numpy/core/code_generators/generate_umath.py#L667), and at that moment I get lost.

I'd like to poke at what is inside `numpy.exp` with some profiling tool, but this is getting too time consuming and I can't spend the time on it at this moment.

**Comment by njsmith** [comment]
For single element calls, the overhead of doing a python function call is overwhelming any differences in the actual exp calculation.

I don't know why setting MATHLIB isn't working for you. That's probably worth figuring out.

Re: the LD_LIBRARY_PATH thing, I think you're getting confused by now ELF symbol lookup works. Numpy is not calling anything in libpython, but libpython is pulling in libimf, and so when numpy looks for the `exp` symbol it finds the one in libimf. Basically this is doing the same thing as LD_PRELOAD=libimf. This might also be why MATHLIB wasn't working, if you're loading a libimf-linked numpy into a libm-linked Python.

`numpy.exp` is implemented in C, so if you want to profile it you'll need a C profiling tool like perf. (cProfile, confusingly, is not a c profiling tool. It's a tool for profiling Python code that's written in c for speed.)

**Comment by damianam** [comment]
> For single element calls, the overhead of doing a python function call is overwhelming any differences in the actual exp calculation.

Of course, that makes a lot of sense. Kind of dumb not seeing that before.

> Re: the LD_LIBRARY_PATH thing, I think you're getting confused by now ELF symbol lookup works. Numpy is not calling anything in libpython, but libpython is pulling in libimf, and so when numpy looks for the exp symbol it finds the one in libimf. Basically this is doing the same thing as LD_PRELOAD=libimf. 

Mmmmh that might make sense too. My understanding of symbol look up was that the dependencies were loaded per library, following the paths in `LD_LIBRARY_PATH`. In other words, `libpython2.7.so` would load its libraries, and the `*.so` objects from numpy would load theirs, without looking if the undefined symbols are already available in a different library loaded previously. I thought about peeking into the debugging output of the loader, but it is normally very verbose and I guess I was looking in the wrong direction, so I discarded that [good?] idea

> This might also be why MATHLIB wasn't working, if you're loading a libimf-linked numpy into a libm-linked Python.

I guess it might be possible. If numpy goes looking for an `exp` symbol, and finds one in the already loaded `libm`, then the function in `libimf` never gets called. I'll verify it tomorrow with `LD_DEBUG`. If that is indeed the issue, then the question is how to force the use of the functions defined in `libimf`, even if `libm` is already loaded.

> `numpy.exp` is implemented in C, so if you want to profile it you'll need a C profiling tool like perf. (cProfile, confusingly, is not a c profiling tool. It's a tool for profiling Python code that's written in c for speed.)

I know. I had vtune in mind for that, but if you are correct and the issue is `MATHLIB` not being picked up properly then it is pointless.

**Comment by seberg** [comment]
Closing, sounds superseded by SIMD in any case.
