### ISSUE TITLE
nextafter and spacing links (and function documentation) missing

### ISSUE THREAD

**Issue by MSeifert04** [numpy/numpy#8831]
The links for the ufuncs `nextafter` and `spacing`  seems to be broken [in the `ufunc.rst`](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#floating-functions) and I couldn't find their "function page" in the online documentation.

**Comment by MSeifert04** [comment]
If someone could point me in the right direction I could provide a PR (or if someone knows how to fix this he/she can do a PR). But I actually have no idea what's wrong there. Maybe it just needs to be referenced in the appropriate `doc/source/reference` `.rst` file?

**Comment by eric-wieser** [comment]
Seems you already knew about this in #7988, so you might already know more than most of us

**Comment by eric-wieser** [comment]
Ah, [got it](http://www.sphinx-doc.org/en/1.5.1/ext/autosummary.html#directive-autosummary)

> The toctree option also signals to the sphinx-autogen script that stub pages should be generated for the entries listed in this directive.

**Comment by MSeifert04** [comment]
@eric-wieser Yes, I've seen it in #7988 but I after a few attempts of cleaning/rebuilding I somewhat lost the motivation. I'm not sure anymore if I tried including it in `routines.math.rst` anymore.

Do you want to test and submit a PR? :)

**Comment by eric-wieser** [comment]
If you have the ability to test, go for it.

Also, while you're building documentation locally... Can you check out sphinx `stable`, and verify that #6769 is fixes too?

**Comment by MSeifert04** [comment]
ok, I'll give it a try.
