### ISSUE TITLE
np.random.randint(0,1,size=(10,10) return all 0 matrix

### ISSUE THREAD

**Issue by ftune** [numpy/numpy#8842]
import numpy as np
i want to generate random matrix with int0 and int1
i use np.random.randint(0,1,size=(10,10)
but get all 0
while  np.random.randint(0,100,size=(10,10) seems get random matrix with a correct uniform distribution
i cannot image why i try randint(0,1,size=(10,10) get all 0 several times

**Comment by eric-wieser** [comment]
`np.randint` generates numbers in the _half-open_ interval [0, 1). The only integer in that interval is `0`.

Use `np.randint(0, 2)` instead. This is consistent with how `range(0,2)` works in python.
