### ISSUE TITLE
Documentation for getbuffer, newbuffer

### ISSUE THREAD

**Issue by MSeifert04** [numpy/numpy#8858]
The `numpy.getbuffer` and `numpy.newbuffer` functions are only present in python2 (https://github.com/numpy/numpy/commit/61d0bd66242a33da1f05364f45220e067e9e1b73). However the documentation tries to document them (https://github.com/numpy/numpy/blob/master/doc/source/reference/routines.other.rst) and fails because at least on python 3 they don't exist anymore.

I'm not sure if and how this could be fixed.

**Comment by MSeifert04** [comment]
This also affects various methods that aren't present in python3 anymore: `__hex__`, `__long__`, `__oct__`, `__div__`, `__idiv__`, `__rdiv__` and `__nonzero__`

**Comment by eric-wieser** [comment]
As a side-note: are the online docs generated from py2 or py3? @rgommers ?

**Comment by kritisingh1** [comment]
@mattip can we document these somewhere in plain text, and further tell that these are not supported in Python3? Where would they best fit according to you?

**Comment by seberg** [comment]
Hmmm, we dropped python 2 support for 1.17 (or are going to). So such an addition would only be helpful in the numpy 1.16 branch.

**Comment by seberg** [comment]
I will close this, since in mater now, they are not relevant anymore.
