### ISSUE TITLE
numpy.asarray(None, dtype=int|float) different behaviour (version: 1.12.0)

### ISSUE THREAD

**Issue by jkrajniak** [numpy/numpy#8863]
Recently I encountered a different behaviour of ```numpy.asarray``` when the input data is ```None``` and dtype is set to ```int``` or ```float```.

numpy version: 

```
In [12]: np.asarray(None, dtype=float)
Out[12]: array(nan)
```

but with ```int```
```
In [13]: np.asarray(None, dtype=int)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-d6dbc0412d33> in <module>()
----> 1 np.asarray(None, dtype=int)

/home/teodor/.local/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    529 
    530     """
--> 531     return array(a, dtype, copy=False, order=order)
    532 
    533 

TypeError: long() argument must be a string or a number, not 'NoneType'
```

**Comment by eric-wieser** [comment]
What behaviour do you expect?

**Comment by MrTheodor** [comment]
I would expect that whatever ```dtype``` is, ```asarray``` will behave in the same way for ```None```

**Comment by eric-wieser** [comment]
Ok, so let's enumerate the options:

* `np.array([None], dtype=int)` return `np.array(nan)`. This is disastrous, because it ignored the dtype we asked for
* `np.array([None], dtype=float)` throws an exception. But `None` &rarr: `nan` is a reasonably useful conversion - is this worth sacrificing for consistency?


Why? `nan` is a reasonable interpretation o

**Comment by MrTheodor** [comment]
Well if this is a feature or an expected behaviour by others then I can handle it;

**Comment by seberg** [comment]
Going to close, the choice of allowing `None` as `NaN` could maybe be discussed, but wasn't the core of the issue.  The behaviour for integers seems certainly set.
