### ISSUE TITLE
Suggestion: merge `mean` and `average` and deprecate one

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#8864]
Please consider merging `mean` and `average` and deprecating one in order to simplify the numpy interface and reduce confusion.

**Comment by eric-wieser** [comment]
Think of it as two functions - "mean", and "weighted average". Perhaps the one-argument form of `average` should be deprecated in favor of `mean`?

**Comment by NeilGirdhar** [comment]
@eric-wieser I think it's better to just have one function with an optional parameter.  (Similarly, it's not like you would want a special name for `asarray` with a `dtype` argument.)

**Comment by eric-wieser** [comment]
> Similarly, it's not like you would want a special name for `asarray` with a dtype argument.

You're aware that `asarray` is basically just `array` without the `copy` argument, right?

**Comment by NeilGirdhar** [comment]
No, I didn't know that :)  Anyway, I guess I find numpy's interface daunting.  You may be interested in this [question](http://stackoverflow.com/questions/20054243/np-mean-vs-np-average-in-python-numpy).

**Comment by MSeifert04** [comment]
I think that ship has sailed long ago. `mean` and `average` are both used regularly so a deprecation + removal might annoy lots of people just for "consistency".

**Comment by eric-wieser** [comment]
> You may be interested in this question.

If you want to submit a pull request that makes the difference more clear in the documentation, if you think that right now it isn't, then that would be appreciated

**Comment by NeilGirdhar** [comment]
My point is that there is no difference between the methods except that one has an optional argument.  And if you don't want to "annoy lots of people", then I don't think deprecating the single argument form of average is the way to go.

Why not a middle ground solution and make `np.mean` a simple redirect to `average` both in the documentation and in the code?

**Comment by eric-wieser** [comment]
> Why not a middle ground solution and make np.mean a simple redirect to average both in the documentation and in the code?

Performance, possibly.

Also, `mean` is really a method, not a function. So `np.array([1, 2, 3]).mean()` is a thing, but `np.array([1, 2, 3]).average()` is not. Any definition of `np.mean(x)` that doesn't boil down to `x.mean()` would be confusing. So under this proposal which tries to reduce duplication, we would end up having to add `x.average`, increasing duplication!

**Comment by NeilGirdhar** [comment]
Good points.

Why not go the other way then: make `average` a redirect to `mean` and absorb the `weights` parameter into mean?
