### ISSUE TITLE
A new tremandous BUG in Advanced Indexing?

### ISSUE THREAD

**Issue by Levstyle** [numpy/numpy#8866]
# This is a BUG
``` python
train = np.zeros([26,26])
train2 = np.zeros([26,26])
tmp = [1,2,3,4,5,6,1,2,3,4,5,6]
train[tmp[0:-1], tmp[1:]] += 1
for i in range(len(tmp)-1):
    train2[tmp[i], tmp[i+1]] += 1
print(np.sum(train - train2))
```
**the output is -5**
I find that `train` is not equal to `train2` when there are some duplicate tuples in `tmp`. Is there something wrong in numpy slicing.

**Comment by RogerMonkey** [comment]
The same to you.

**Comment by MSeifert04** [comment]
You know that you're trying to write to the "same position" twice, for example `[1, 2]`. Unfortunatly that doesn't work.

But you can use [`np.add.at`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.at.html#numpy.ufunc.at) which according to the docs "For addition ufunc, this method is equivalent to a[indices] += b, except that results are accumulated for elements that are indexed more than once.":

```
train = np.zeros([26,26])
np.add.at(train, [tmp[0:-1], tmp[1:]], 1)
```

**Comment by Levstyle** [comment]
Thanks!

**Comment by Levstyle** [comment]
Thanks!
