### ISSUE TITLE
ENH: Add axis argument to tile

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#8879]
Currently `tile` doesn't have an `axis` argument. Considering `repeat` and `concatenate`, which share similarities to `tile`, do take `axis` arguments, it doesn't seem unreasonable to have a similar argument for `tile`. Not to mention this would avoid some unnecessary fiddling with arrays to affect the intended dimension. If there were to be an `axis` argument for `tile`, it could be added with a default of `-1`. Thus this would preserve existing behavior while allowing for more flexibility with ease.

**Comment by eric-wieser** [comment]
What would this even mean? Can you add an example of what it would do?

**Comment by WarrenWeckesser** [comment]
Without a clearer specification for the requested enhancement, this isn't something we can act on, and given the apparent lack of interest from anyone else since 2017, I'm closing the issue.  @jakirkham, if this is something you are still interested in, can you add more information?

**Comment by Evidlo** [comment]
This is something that has been bugging me as well, as I also expected `tile` to have an `axis` argument.  I believe OP might have been looking for something like:

``` python
def tile(A, repeats, axis=None):
    if isinstance(axis, int):
        assert isinstance(repeats, int), "`repeats` should be integer"
        axis, repeats = (axis,), (repeats,)

    if isinstance(axis, tuple):
        assert len(repeats) == len(axis), "`repeats` and `axis` should have the same length"
        new_repeats = [1] * A.ndim
        for ax, r in zip(axis, repeats):
            new_repeats[ax] = r
        repeats = new_repeats

    return np.tile(A, repeats)
```

This adds support for an `axis` argument which may be either an int or a tuple[int] where each integer is an axis of `A`.

- if `axis` is int, then `repeats` should also be an int
- if `axis` is tuple of ints, then `repeats` should be a tuple of ints of the same length

Some examples with standard behavior and equivalent behavior when using `axis`:

``` python
>>> A = np.arange(3)[None, :]
>>> np.tile(A, (1, 2))
[[0 1 2 0 1 2]]
>>> tile(A, 2, axis=1)
[[0 1 2 0 1 2]]
```

``` python
>>> np.tile(A, (2, 2))
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
>>> tile(A, (2, 2), axis=(0, 1))
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
```
