### ISSUE TITLE
ENH: Add ndarray tile method

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#8880]
There is already a `repeat` method for `ndarray`s. It would be good for symmetry to have a `tile` method as well.

**Comment by charris** [comment]
Take a look at #7768. I'm embarrassed that after taking it over it is still unfinishec.

**Comment by eric-wieser** [comment]
@charris: I think this is just the "why does ndarray.X method not exist when ndarray.Y does, where np.X and np.Y are existing and similar" issue again.

**Comment by WarrenWeckesser** [comment]
After reviewing the linked issue about `median`, my conclusion is that the same arguments apply here.  I'm closing the issue, but @jakirkham, if you still think `tile` should be a method, I won't complain if you reopen the issue and try again to make a case for adding it.
