### ISSUE TITLE
BUG: np.array does not respect __len__ of passed sequence

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8912]
```
>>> class OneList:
	def __len__(self): return 1
	def __getitem__(self, x):
		if x != 0: raise RuntimeError
		return 1
>>> np.array(OneList())
Traceback (most recent call last):
  File "<pyshell#24>", line 1, in <module>
    np.array(OneList())
  File "<pyshell#23>", line 4, in __getitem__
    if x != 0: raise RuntimeError
RuntimeError
```

This is worse if `__getitem__` silently succeeds on out-of-bounds indices, as then `np.array` just hangs

**Comment by MSeifert04** [comment]
That's weird. If you raise `IndexError` it works as expected (even though it tries to access the "length+1" index. But if you raise `KeyError` it creates an object array. 

It seems your `OneList` doesn't quack like a duck 😄

**Comment by eric-wieser** [comment]
I think this is as expected, and should be closed - `list(OneList())` fails in exactly the same way

**Comment by eric-wieser** [comment]
I suspect [this question](https://stackoverflow.com/questions/43566044/what-is-pythons-sequence-protocol) was inspired by this issue.

The underlying cause here is how `iter(OneList())` behaves

**Comment by tylerjereddy** [comment]
Our [docs for `numpy.array`](https://www.numpy.org/devdocs/reference/generated/numpy.array.html?highlight=mp%20array#numpy.array) do actually say "*any* (nested) sequence" -- this is perhaps pushing it though.

As the answer to that linked question implies -- this is indeed tricky.

The accepted response:

> As for what counts as a sequence in practice, it's usually anything that supports __len__ and __getitem__ with integer indexes starting at 0 and isn't a mapping. If the docs for a function say it takes any sequence, that's almost always all it needs.

**Comment by eric-wieser** [comment]
I'd argue that's untrue, as a lot of functions that take sequences will use `for x in sequence`, which calls `iter`, and that in turn never touches `__len__`.

I think this probably could do with a follow-up in CPython, but it would be strange for us to pick a different convention to CPython for such a corner case.

**Comment by tylerjereddy** [comment]
Ok, [I followed up with CPython](https://bugs.python.org/issue34494) for good measure, thanks Eric.

**Comment by eric-wieser** [comment]
Great, thanks! I think this and the PR can be closed then.
