### ISSUE TITLE
BUG: x.flags.writeable changes when using x.flat.__array__

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8916]
What's going on here?

```python
>>> x = np.broadcast_to(1, (2,2))
>>> x.flags.writeable = True  # ok, this is a little sketchy
>>> x.flags.writeable
True
>>> x.flat.__array__()
>>> x.flags.writeable
False
```

**Comment by jaimefrio** [comment]
This is probably related to the last point in #5721.

**Comment by jaimefrio** [comment]
And it may be fixed in #5740?

**Comment by charris** [comment]
Yep. Explanation given in the closed issue. The `x.flat.__array__()` makes an updateifcopy array in this case and locks `x` until it finishes. Since the terminal is holding a reference to the result, it is not deallocated, hence doesn't copy back and reset the writeable flag on `x`.

**Comment by charris** [comment]
Using the current example
```
In [1]: x = np.broadcast_to(1, (2,2))

In [2]: x.flags.writeable = True  # ok, this is a little sketchy

In [3]: x.flags.writeable
Out[3]: True

In [4]: a = x.flat.__array__()

In [5]: x.flags.writeable
Out[5]: False

In [6]: del a

In [7]: x.flags.writeable
Out[7]: True
```

**Comment by mattip** [comment]
should now be well defined and documented by PR #9447 which was merged
