### ISSUE TITLE
Integers to negative integer powers are not allowed

### ISSUE THREAD

**Issue by Zex** [numpy/numpy#8917]
Components:
Numpy-1.12.0
Python-3.5.3
Description:
```10**-5``` is fine,
But do it in a for loop ValueError raise.
Here is the code
```
>>> [10**c for c in np.arange(-5,5)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
ValueError: Integers to negative integer powers are not allowed.
>>> 10**0
1
>>> 10**-1
0.1
>>> 10**-2
0.01
>>> 10**-3
0.001
>>> 10**-4
0.0001
>>> 10**-5
1e-05
>>> 10**1
10
>>> 10**2
100
>>> 10**3
1000
>>> 10**4
10000
>>> 10**5
100000
```

**Comment by MSeifert04** [comment]
A lot of numpy functions don't do implicit type coercions. 

For scalars this may seem weird but for arrays it makes sense, because `np.power` should know what the result dtype is just by looking at the dtype of the operands.

**Comment by eric-wieser** [comment]
What you're seeing here is the difference between `10 ** np.int(-1)` and `10 ** -1`

**Comment by njsmith** [comment]
(@eric-wieser means `np.int_(1)` in case you try it and are confused. `np.int` is a silly alias for Python's built in `int`.)

**Comment by eric-wieser** [comment]
Oops, good catch. Can we do #6103 already?

**Comment by sursu** [comment]
This behavior seems stupid.

**Comment by xyXiangYu** [comment]
why we close this issue?  Since the logic completely does not make sense. 

for the code: 
x = 10 ** np.arange(-4,4)

we have error: 
ValueError: Integers to negative integer powers are not allowed.

It is so counter-intuitive, why do we not allow negative integer?

**Comment by skjerns** [comment]
A quick fix for anyone dropping by, create the exponent as float.
```
[10**c for c in np.arange(-5,5, dtype=float)]
```

**Comment by hundanLi** [comment]
I just use range() function.

**Comment by diogenesjusto** [comment]
> [10**c for c in np.arange(-5,5, dtype=float)]

or just:
10**np.arange(-5,5, dtype=float)
