### ISSUE TITLE
np.equal not correctly comparing NaN Values

### ISSUE THREAD

**Issue by david1309** [numpy/numpy#8926]
Hello,

If there are two vectors `x, y` which are actually the same and contain _NaN_ values, `np.equal(x,y)` will not return True for all elements in the vectors.

I understand that numpy manages _NaN_ values in a particular way, and thus, to compare if a value `val` is a _NaN_ one must use `np.isnan(val)`.

I think the method `np.equal(x,y)` must be modified in order for it to internally better manage NaN values, so that when two vectors are the equal it returns True **even for those positions which conain _NaN_ values**

**Example Code**
```Python
x = np.array([1,2,np.nan])
y = np.array([1,2,np.nan])
print(np.equal(x,y))

Out: [ True  True False]
```

**System Specs:**
- Python Version: Python 2.7.13 :: Continuum Analytics
- Numpy Version: '1.12.0'
- OS: Ubuntu 16.04 LTS

**Comment by eric-wieser** [comment]
And what would you have `np.equal(np.array([np.nan]),  np.array([np.nan]))` return?

What you're suggesting goes against the IEEE 754 specification of `nan`, and so doesn't sound like a good idea at all to me

**Comment by eric-wieser** [comment]
As a side note, you can _sometimes_ get what you're looking for with

    np.equal(x.view(np.int64), y.view(np.int64))

By viewing the `float64`s as their integer bits.

But just because two floats are `nan` does not mean they have the same bit pattern. There is no unique representation of `nan`.

**Comment by seberg** [comment]
That seems moderately horrific, -0 and 0 are also not the same, etc. Note that python does **not** give you this guarantee when doing comparisons of lists, etc. (just to point it out).
```
In [1]: [float("nan")] == [float("nan")]
Out[1]: False
In [2]: [np.nan] == [np.nan]
Out[2]: True
```

Equality is carefully designed as it is, if you want to accept equivalence in the sense of NaN being identical, you have to do other things, not change the definition of equality. One might only argue for a new function or so, and we have such functions for testing purposes (where it is relatively common).

**Comment by pv** [comment]
ieee specifies nans do not compare equal. This looks like wontfix to me, the current behavior is correct.

**Comment by eric-wieser** [comment]
@seberg: Your `[float("nan")] == [float("nan")]` is misleading

```
In [1]: [float("nan")] == [float("nan")]
Out[1]: False
In [2]: nan = float("nan")
In [3]: [nan] == [nan]
Out[3]: True
```
This strikes me as a python bug? List equality shouldn't invoke `is` before `==` on elements, should it?

**Comment by seberg** [comment]
Debatable if it is a bug or not I suppose. You could try to argue that NaN should not be hashable, too. Just showing another oddity that comes with the properties of NaN....

**Comment by pv** [comment]
Python has some argumentation why they do it like that:
https://docs.python.org/3.6/reference/expressions.html#value-comparisons

**Comment by eric-wieser** [comment]
Yep, I just found that, which I'll repeat here since there's no great section link:


> In enforcing reflexivity of elements, the comparison of collections assumes that for a collection element `x`, `x == x` is always true. Based on that assumption, element identity is compared first, and element comparison is performed only for distinct elements. This approach yields the same result as a strict element comparison would, if the compared elements are reflexive. For non-reflexive elements, the result is different than for strict element comparison, and may be surprising: The non-reflexive not-a-number values for example result in the following comparison behavior when used in a list:
> ```python
> >>>
> >>> nan = float('NaN')
> >>> nan is nan
> True
> >>> nan == nan
> False                 <-- the defined non-reflexive behavior of NaN
> >>> [nan] == [nan]
> True                  <-- list enforces reflexivity and tests identity first
> ```
