### ISSUE TITLE
Suggestion: allow jit decorator to read types from annotations

### ISSUE THREAD

**Issue by mangecoeur** [numpy/numpy#8930]
The `@jit` allows supplying expected types

```py
@jit(int32(int32, int32))
def f(x, y):
    return x + y
```

Function type annotations in Python 3.5+ look like a good fit for this use case, annotations are easy enough to [read from the decorated function properties ](https://docs.python.org/3.5/library/inspect.html#inspect.signature), allowing you to write:

```py
@jit
def f(x: int32, y: int32) -> int32:
    return x + y
```

With the added bonus that the same type annotations could improve IDE support (e.g. completions and error checking in PyCharm) and mypy tests.

This might not cover every use case, but could probably cover a lot of common cases, including when several types are accepted using `Union[]`

**Comment by pv** [comment]
Wrong issue tracker?

**Comment by seberg** [comment]
Agreed, seems not like a numpy issue.

**Comment by mangecoeur** [comment]
Apologies, wrong issue tracker.
