### ISSUE TITLE
Missing ufuncs: np.divmod and np.positive

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#8932]
These are not terribly useful, but would be nice to have for completeness, so we can implement every binary operation between arrays by calling `__array_ufunc__` (e.g., for `NDArrayOperatorsMixin`, https://github.com/charris/numpy/pull/19).

Currently ndarray implements `__divmod__` and `__pos__` in terms of other helper functions that aren't exposed in the API:
https://github.com/numpy/numpy/blob/f3682860cfe28cd73f46ae290add5d6fdbe43c89/numpy/core/src/multiarray/number.c#L1120

**Comment by charris** [comment]
Hmm, `divmod` is already a Python builtin function, so we don't want to shadow that. OTOH, it would add some efficiency to the current implementation of `ndarray.__divmod__`. `+` might be a bit weird if we let it overwrite itself using the out argument...

**Comment by njsmith** [comment]
divmod ends up dispatching to the div and mod ufuncs, doesn't it? And pos
is a unary operation that just returns a copy so a workaround would be for
the mixin class to define __pos__ to call self.copy().

(Not expressing an opinion on the best solution, just thinking about the
space of options.)

**Comment by shoyer** [comment]
> Hmm, divmod is already a Python builtin function, so we don't want to shadow that

Right, because some people still do `from numpy import *`... sigh...

So probably `np.divmod_` it is, then.

> divmod ends up dispatching to the div and mod ufuncs, doesn't it?

That's right. So it probably does the right thing most of the time.

> And pos is a unary operation that just returns a copy so a workaround would be for
the mixin class to define __pos__ to call self.copy().

Yes, that would certainly work.

**Comment by shoyer** [comment]
One downside of the current unary `+` operation is that it's defined on *all* array dtypes, so `+np.array('foo')` works even though `+'foo'` raises TypeError.

**Comment by eric-wieser** [comment]
Also, it would make sense to have a loop for `dtype=object`, so that custom types that do something with `__pos__` don't get ignored in object arrays

**Comment by charris** [comment]
> divmod ends up dispatching to the div and mod ufuncs, doesn't it?

Yes, and each of those calls the relevant divmod function defined in `npy_math` ;) So two calls where one would do. Hey, it was the easy way...

**Comment by eric-wieser** [comment]
It should be pretty straightforward to add loops for both of these, right?

On the note of adding loops - it seems that we have two different methods of defining inner loops - one with a scalar function and an existing loop that calls it through the data pointer, and one that uses macros to instantiate a full loop containing that operation.

Which one is preferable?

is my approach in #8774 the right one? Or was the approach in #8820 better?

**Comment by shoyer** [comment]
See #8967 for a ufunc for `np.positive`. The PR currently also uses it in `ndarray.__pos__`, but that's probably premature.

Nobody really uses `divmod`, so I'm OK leaving `__divmod__` out from NDArrayOperatorsMixin. But it would be an shame to need to omit `__pos__`, too.

**Comment by eric-wieser** [comment]
> Nobody really uses divmod

I'd wager that more people use `divmod` than `__pos__`, but whatever - I'd only use that as an argument for shipping with neither being an option too

**Comment by mhvk** [comment]
Bit late to the game, but we do have `Quantity.__divmod__` in astropy -- and I use `divmod` quite a bit myself in my baseband code (e.g., https://github.com/mhvk/baseband/blob/master/baseband/vlbi_base/base.py#L86)

**Comment by shoyer** [comment]
@mhvk if you're up for turning `np.divmod` into a single ufunc, that would be awesome! I think this would actually be quite straightforward and offer a 2x performance boost.

> Hmm, divmod is already a Python builtin function, so we don't want to shadow that.

If someone is using `from numpy import *`, they deserve it! But honestly, they probably won't even notice. We already do this sort of thing with `np.abs` (which maps to `<ufunc 'absolute'>`).

**Comment by shoyer** [comment]
I actually might give `np.divmod` a shot. It looks pretty straightforward.

**Comment by mhvk** [comment]
@shoyer - that would be great!

**Comment by shoyer** [comment]
See #9063
