### ISSUE TITLE
Return of np.any() cannot be used for 'is False' or 'is True' expression

### ISSUE THREAD

**Issue by Cooper-Yang** [numpy/numpy#8944]
Python version: 3.4.3
System: Ubuntu 14.04
Kernel version: 4.4.0-72-generic
numpy version: 1.12.1

```
>>> np.any([2576, 1716] < [128, 256])
False
>>> np.any([2576, 1716] < [128, 256]) == False
True
>>> np.any([2576, 1716] < [128, 256]) is False
False
>>> np.any([2576, 1716] < [128, 256]) is True
False
```

**Comment by MSeifert04** [comment]
yes, the returned values is of type `np.bool_`.  So `is` comparisons can't work because the values are of different type.

Also [PEP8](https://www.python.org/dev/peps/pep-0008/) is quite clear on the subject of boolean comparisons:

```
Don't compare boolean values to True or False using == .

Yes:   if greeting:
No:    if greeting == True:
Worse: if greeting is True:
```

**Comment by charris** [comment]
@MSeifert04 Just so.
