### ISSUE TITLE
Inconsistency in shape of custom dtype

### ISSUE THREAD

**Issue by mpu-creare** [numpy/numpy#8946]
I found an odd discrepancy when creating a custom dtype in numpy. The code below:
```python
import numpy as np
print "VERSION", np.__version__

def f(data, size):
    return np.frombuffer(data, np.dtype([('d', 'i', size)]))

d1 = np.arange(1)
d2 = np.arange(2)

a1 = f(d1, 1)
a2 = f(d2, 2)
b1 = f(d1, [1])
b2 = f(d2, [2])

print "a1['d'].shape: ",  a1['d'].shape, " b1['d'].shape: ", b1['d'].shape
print "a2['d'].shape: ",  a2['d'].shape, " b2['d'].shape: ", b2['d'].shape
```
produces this: 
```
VERSION 1.12.1
a1['d'].shape:  (1L,)  b1['d'].shape:  (1L, 1L)
a2['d'].shape:  (1L, 2L)  b2['d'].shape:  (1L, 2L)
```
where `a1['d'].shape` is the odd one out. This inconsistency is annoying... but at least it seems like always defining the size with a list produces consistent behavior.  

I did a quick search and I didn't see a duplicate, but I might have missed it.

**Comment by eric-wieser** [comment]
I think the problem here is just with `np.dtype`, and is not really to do with `frombuffer`:

```
In [1]: import numpy as np

In [2]: def make_dt(size):
   ...:     return np.dtype([('d', 'i', size)])
   ...:

In [3]: make_dt(1)
Out[3]: dtype([('d', '<i4')])         # this one flattens out the repetition count

In [4]: make_dt([1])
Out[4]: dtype([('d', '<i4', (1,))])

In [6]: make_dt(2)
Out[6]: dtype([('d', '<i4', (2,))])

In [5]: make_dt([2])
Out[5]: dtype([('d', '<i4', (2,))])
```

I can only assume that this is by design

**Comment by mpu-creare** [comment]
Should have tested just dtype, thanks for pointing out it has nothing to do with frombuffer. 

I can live with it as long as it's carefully documented somewhere -- which is a pretty easy fix. But it would be good if the interface was consistent. No idea where that is in the numpy code -- searching for dtype returns a lot of result.

**Comment by eric-wieser** [comment]
`_convert_from_array_descr` in `descriptor.c` is what you're looking for

**Comment by eric-wieser** [comment]
There's a comment there of:

```
        /*
         * If (type, 1) was given, it is equivalent to type...
         * or (type, ()) was given it is equivalent to type...
         */
```

**Comment by eric-wieser** [comment]
This feature was added in 071f111e8c14ac2286722fb147254aebd8ff98d3

**Comment by eric-wieser** [comment]
I think I'd be in favor of giving a `FutureWarning` in this situation, and then fixing this in a much later release?

**Comment by mpu-creare** [comment]
I think that would be great. But I suppose another core numpy developer should weigh in.

**Comment by ganesh-k13** [comment]
Hey @eric-wieser , is this issue still open for PRs?

**Comment by eric-wieser** [comment]
I think this may have been fixed already - can you check if the code above now emits warnings?

**Comment by ganesh-k13** [comment]
Yep:
```py
>>> np.__version__
'1.20.0.dev0+aebaa8d'
>>> np.dtype([('d', 'i', 1)])
<stdin>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
dtype([('d', '<i4')])
```

**Comment by eric-wieser** [comment]
Wonderful, sounds like this can be closed. Thanks for finding this issue and pinging!

**Comment by eric-wieser** [comment]
(#13326 was the PR)
