### ISSUE TITLE
Issue detected by installing Numpy 1.12.1 from Cygwin 2.8.0 (x86_64) - Python 3.6.1

### ISSUE THREAD

**Issue by KptainBiwouak** [numpy/numpy#8950]
Not possible to setup Numpy 1.12.1 from Cygwin:

<details>
<summary>

`pip3 install numpy`

</summary>

```
Collecting numpy
  Using cached numpy-1.12.1.zip
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /.gfmwk_tmp_120417204610_19564/spectools/tmpdbmu4l3rpip-wheel- --python-tag cp36:
  Running from numpy source directory.
  blas_opt_info:
  blas_mkl_info:
    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  blis_info:
    libraries blis not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  openblas_info:
    libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  atlas_3_10_blas_info:
    libraries satlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  /.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  blas_info:
    libraries blas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  /.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/system_info.py:572: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    self.calc_info()
  blas_src_info:
    NOT AVAILABLE

  /.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/system_info.py:572: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  non-existing path in 'numpy/distutils': 'site.cfg'
  F2PY Version 2
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries tatlas,tatlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries tatlas,tatlas not found in /usr/lib/
    libraries lapack_atlas not found in /usr/lib/
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries satlas,satlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries satlas,satlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries satlas,satlas not found in /usr/lib/
    libraries lapack_atlas not found in /usr/lib/
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
    libraries lapack_atlas not found in /usr/lib/
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries f77blas,cblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries f77blas,cblas,atlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries f77blas,cblas,atlas not found in /usr/lib/
    libraries lapack_atlas not found in /usr/lib/
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE

  /.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  /.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build/src.cygwin-2.8.0-x86_64-3.6
  creating build/src.cygwin-2.8.0-x86_64-3.6/numpy
  creating build/src.cygwin-2.8.0-x86_64-3.6/numpy/distutils
  building library "npymath" sources
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Found executable /cygdrive/d/GFMWK_NEXT/base/cygwin/bin/DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  don't know how to compile Fortran code on platform 'posix'
  C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1 -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1

  compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.6m -c'
  gcc: _configtest.c
  gcc _configtest.o -o _configtest.exe
  success!
  removing: _configtest.c _configtest.o _configtest.exe
  C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1 -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1

  compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.6m -c'
  gcc: _configtest.c
  _configtest.c:1:5: warning: conflicting types for built-in function 'exp'
   int exp (void);
       ^
  gcc _configtest.o -o _configtest.exe
  success!
  removing: _configtest.c _configtest.o _configtest.exe
  creating build/src.cygwin-2.8.0-x86_64-3.6/numpy/core
  creating build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src
  creating build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npymath
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npymath/npy_math.c
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npymath/ieee754.c
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npymath/npy_math_complex.c
  building library "npysort" sources
  creating build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npysort
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npysort/quicksort.c
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npysort/mergesort.c
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npysort/heapsort.c
  creating build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/private
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/private/npy_partition.h
    adding 'build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/private' to include_dirs.
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npysort/selection.c
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/private/npy_binsearch.h
  conv_template:> build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/npysort/binsearch.c
  None - nothing done with h_files = ['build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/private/npy_partition.h', 'build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/src/private/npy_binsearch.h']
  building extension "numpy.core._dummy" sources
  Generating build/src.cygwin-2.8.0-x86_64-3.6/numpy/core/include/numpy/config.h
  C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1 -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1

  compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.6m -c'
  gcc: _configtest.c
  _configtest.c:1:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  _configtest.c:1:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  failure.
  removing: _configtest.c _configtest.o
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/setup.py", line 391, in <module>
      setup_package()
    File "/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/setup.py", line 383, in setup_package
      setup(**metadata)
    File "/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 199, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/command/build.py", line 47, in run
      old_build.run(self)
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/command/build_src.py", line 148, in run
      self.build_sources()
    File "/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/command/build_src.py", line 165, in build_sources
      self.build_extension_sources(ext)
    File "/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/command/build_src.py", line 324, in build_extension_sources
      sources = self.generate_sources(sources, ext)
    File "/.gfmwk_tmp_120417204610_19564/spectools/pip-build-zu8uhs4m/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
      source = func(extension, build_dir)
    File "numpy/core/setup.py", line 416, in generate_config_h
      moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
    File "numpy/core/setup.py", line 40, in check_types
      out = check_types(*a, **kw)
    File "numpy/core/setup.py", line 275, in check_types
      "install {0}-dev|{0}-devel.".format(python))
  SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
```

</details>

Current configuration:
Cygwin 2.8.0
Python: 3.6.1

As I have understand that Numpy requirements are automatically selected also for install, could you clarified which package have to be available on Cygwin in order to proceed Numpy setup.

I would add that python3-numpy package was added when I have selected cygwin package for setup.
But when, I am doing:
```
import numpy 
from my script
 -> it's failing with meassage below:
$ python3 numpy_sample.py
Traceback (most recent call last):
  File "numpy_sample.py", line 3, in <module>
    a = np.array([1,2,3,4])
AttributeError: module 'numpy' has no attribute 'array'
```
Thanks in advance for your help,

Stephan

**Comment by eric-wieser** [comment]
>     Perhaps you need to install python-dev|python-devel.

Did you do this?

**Comment by KptainBiwouak** [comment]
Yes.
As recommended, I have installed python-dev package on Cygwin.
It seems to be better as now I am able to build wheels for collected packages: numpy

>>
$ pip3 install numpy
Collecting numpy
  Using cached numpy-1.12.1.zip
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /cygdrive/d/ARCHITECTURE/.cache/pip/wheels/50/b5/d0/3994af801e0786dfb41a9856ddf85d69c54f233e749935d536
Successfully built numpy
Installing collected packages: numpy
Successfully installed numpy-1.12.1
<<

No issue detected also from from pip checker:
>>
$ pip3 check numpy
No broken requirements found.
<<

However, I am still not able to run my numpy sample script:

(short extract)
import numpy as np

a = np.array([1,2,3,4])
print(a)

------------------------------------------------------------------------
 python3 numpy_sample.py
Traceback (most recent call last):
  File "numpy_sample.py", line 1, in <module>
    import numpy as np
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: No such file or directory
<<

I am not also to find any lapack library for python.

Thnaks again for your help,

S;

**Comment by KptainBiwouak** [comment]
It seems lapack_lite library is not correctly build by PIP during numpy installation.
Could you provide some support for Cygwin users?
Probably some tool is missing from Cygwin setup?

**Comment by KptainBiwouak** [comment]
Here is an overview of linalg library folder:
$ ll /cygdrive/c/<PATH>/base/cygwin/lib/python3.6/site-packages/numpy/linalg
total 244
drwxrwx---+ 1 Administrators Domain Users      0 Apr  5 21:26 .
drwxrwx---+ 1 Administrators Domain Users      0 Apr  5 21:26 ..
-rwxrwx---+ 1 Administrators Domain Users   2343 Mar 15 00:28 __init__.py
drwxrwx---+ 1 Administrators Domain Users      0 Apr  5 21:26 __pycache__
-rwxrwx---+ 1 Administrators Domain Users 123411 Mar 15 00:28 _umath_linalg.cpython-36m-x86_64-cygwin.dll
-rwxrwx---+ 1 Administrators Domain Users   1198 Mar 15 00:28 info.py
-rwxrwx---+ 1 Administrators Domain Users  15891 Mar 15 00:28 lapack_lite.cpython-36m-x86_64-cygwin.dll
-rwxrwx---+ 1 Administrators Domain Users  75865 Mar 15 00:28 linalg.py
-rwxrwx---+ 1 Administrators Domain Users   1735 Mar 15 00:28 setup.py
drwxrwx---+ 1 Administrators Domain Users      0 Apr  5 21:26 tests

**Comment by eric-wieser** [comment]
Does `from numpy.linalg import lapack_lite` fail by itself then?

**Comment by KptainBiwouak** [comment]
Yes, it seems DLL built for Cygwin are wrong?
How to proceed to check build process?
Nothing is highlighted by Pip.

**Comment by eric-wieser** [comment]
Is the error still `ImportError: No such file or directory` in that case?

**Comment by eric-wieser** [comment]
Could this be your problem: https://stackoverflow.com/questions/1099981/why-cant-python-find-shared-objects-that-are-in-directories-in-sys-path

**Comment by eric-wieser** [comment]
What does `cygcheck thatdll.dll` give?

**Comment by KptainBiwouak** [comment]
I think you could have identified the root cause of the issue as one dll (cyglapack-0.dll) is missing as shown below:

$ cygcheck lapack_lite.cpython-36m-x86_64-cygwin.dll
Found: .\lapack_lite.cpython-36m-x86_64-cygwin.dll
.\lapack_lite.cpython-36m-x86_64-cygwin.dll
  D:\GFMWK_NEXT\base\cygwin\bin\cygwin1.dll
    C:\WINDOWS\system32\KERNEL32.dll
      C:\WINDOWS\system32\ntdll.dll
      C:\WINDOWS\system32\KERNELBASE.dll
      C:\WINDOWS\system32\api-ms-win-core-fibers-l2-1-1.dll
  D:\GFMWK_NEXT\base\cygwin\bin\libpython3.6m.dll
    D:\GFMWK_NEXT\base\cygwin\bin\cygintl-8.dll
      D:\GFMWK_NEXT\base\cygwin\bin\cygiconv-2.dll
cygcheck: track_down: could not find cyglapack-0.dll

but the problem is: where is the source package from which this DLL has to be built?

As you suggest at the beginning, I think an other package is wrong or is missing from original cygwin setup.

FYI, when I start to install numpy, I have selected python-numpy package (1.11.2).
But as there was an issue, I have uninstalled package (pip3 uninstall) and proceed with install for latest 1.12.1. It is why maybe there is a misalignement with default packages available on Cygwin (dedicated for 1.11.2) and the latest one. If it can help you understand.

**Comment by KptainBiwouak** [comment]
The DLL can be found here on PC:
D:\GFMWK_NEXT\base\cygwin\lib\lapack\cyglapack-0.dll

I don't really understand why Python desn't look into this path

**Comment by eric-wieser** [comment]
It seems wrong to me that `cyglapack-0.dll` is needed - the whole point in `lapack_lite` is that it does not depend on any cygwin installation.

**Comment by eric-wieser** [comment]
What does the following give for you in python?
```
from numpy.distutils.system_info import get_info
get_info('lapack_opt', 0)
```

**Comment by KptainBiwouak** [comment]
Same report as before (3 days ago)

current path: /cygdrive/d/GFMWK_NEXT/base/scripts/py/TP

$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from numpy.distutils.system_info import get_info
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: No such file or directory
------------------------------------------------------------------------------------

I have added below beginning of content of linalg.py:


-----------------------------------------------------------------------------
"""Lite version of scipy.linalg.

Notes
-----
This module is a lite version of the linalg.py module in SciPy which
contains high-level Python interface to the LAPACK library.  The lite
version only accesses the following LAPACK functions: dgesv, zgesv,
dgeev, zgeev, dgesdd, zgesdd, dgelsd, zgelsd, dsyevd, zheevd, dgetrf,
zgetrf, dpotrf, zpotrf, dgeqrf, zgeqrf, zungqr, dorgqr.
"""
from __future__ import division, absolute_import, print_function


__all__ = ['matrix_power', 'solve', 'tensorsolve', 'tensorinv', 'inv',
           'cholesky', 'eigvals', 'eigvalsh', 'pinv', 'slogdet', 'det',
           'svd', 'eig', 'eigh', 'lstsq', 'norm', 'qr', 'cond', 'matrix_rank',
           'LinAlgError', 'multi_dot']

import warnings

from numpy.core import (
    array, asarray, zeros, empty, empty_like, transpose, intc, single, double,
    csingle, cdouble, inexact, complexfloating, newaxis, ravel, all, Inf, dot,
    add, multiply, sqrt, maximum, fastCopyAndTranspose, sum, isfinite, size,
    finfo, errstate, geterrobj, longdouble, rollaxis, amin, amax, product, abs,
    broadcast, atleast_2d, intp, asanyarray, isscalar, object_
    )
from numpy.lib import triu, asfarray
from numpy.linalg import lapack_lite, _umath_linalg
from numpy.matrixlib.defmatrix import matrix_power
from numpy.compat import asbytes

# For Python2/3 compatibility
_N = asbytes('N')
_V = asbytes('V')
_A = asbytes('A')
_S = asbytes('S')
_L = asbytes('L')

fortran_int = intc

# Error object
class LinAlgError(Exception):
    """
    Generic Python-exception-derived object raised by linalg functions.

    General purpose exception class, derived from Python's exception.Exception
    class, programmatically raised in linalg functions when a Linear
    Algebra-related condition would prevent further correct execution of the
    function.

    Parameters
    ----------
    None

    Examples
    --------
    >>> from numpy import linalg as LA
    >>> LA.inv(np.zeros((2,2)))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "...linalg.py", line 350,
        in inv return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
      File "...linalg.py", line 249,
        in solve
        raise LinAlgError('Singular matrix')
    numpy.linalg.LinAlgError: Singular matrix

    """
    pass

# Dealing with errors in _umath_linalg

_linalg_error_extobj = None

.....


---------------------------------------------------------------------------------

Maybe the locations of lapack_lite DLLs are wrong (linalg folder) or have to be specified somewhere else.

**Comment by eric-wieser** [comment]
Really? Is it not possible to import `numpy.distutils.system_info` when the numpy installation is broken?

**Comment by KptainBiwouak** [comment]
Here is the result following your recommendations:

------------------------------------------------------------------------------------------------------------------
$ python3 test.py
/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/distutils/system_info.py:572: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
/cygdrive/d/GFMWK_NEXT/base/cygwin/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
/cygdrive/d/GFMWK_NEXT/base/cygwin/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status

-----------------------------------------------------------------------------------------

it seems Atlas library is not found.
file numpy/distutils/site.cfg doesn't exist
no ATLAS environnement variable.

probably I have to select Cygwin Atlas package?

**Comment by eric-wieser** [comment]
Can you actually print the result of `get_info`? I assumed you were going to type that into a repl

**Comment by KptainBiwouak** [comment]
Here is the result by using CLI:
$ python3
Python 3.6.1 (default, Mar 21 2017, 21:49:16)
[GCC 5.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from numpy.distutils.system_info import get_info
>>> get_info
<function get_info at 0x6ffff200268>
>>> get_info('lapack_opt', 0)
/cygdrive/d/GFMWK_NEXT/base/cygwin/lib/python3.6/site-packages/numpy/distutils/system_info.py:572: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
/cygdrive/d/GFMWK_NEXT/base/cygwin/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
/cygdrive/d/GFMWK_NEXT/base/cygwin/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
{'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'libraries': ['lapack', 'lapack', 'blas', 'blas'], 'library_dirs': ['/cygdrive/d/GFMWK_NEXT/base/cygwin/lib'], 'language': 'c'}

**Comment by eric-wieser** [comment]
> probably I have to select Cygwin Atlas package?

Nope. You shouldn't have to install anything. If lapack is not installed, numpy should detect that, and then attempt to build a substitute lapack instead.

**Comment by eric-wieser** [comment]
What about `get_info('blas')` and `get_info('lapack')`?

**Comment by eric-wieser** [comment]
I think this might be your bug: https://github.com/numpy/numpy/issues/6381

**Comment by KptainBiwouak** [comment]
Thanks again for your time!

here are the results:

>>> get_info('blas')
{'libraries': ['blas', 'blas'], 'library_dirs': ['/cygdrive/d/GFMWK_NEXT/base/cygwin/lib'], 'language': 'c', 'define_macros': [('HAVE_CBLAS', None)]}
>>> get_info('lapack')
{'libraries': ['lapack', 'lapack'], 'library_dirs': ['/cygdrive/d/GFMWK_NEXT/base/cygwin/lib'], 'language': 'f77'}

if I understand well, numpy library is not correctly installed without highlighting clearly where is the default.

does some "pip  check" option exist in order to improve report?

**Comment by KptainBiwouak** [comment]
Generally, I have found that Python library dependencies are clearly reported, but when dependencies concern other source code types sub packages are not clearly reported.

This issue is clearly linked to #6381 but it is still not clear which packages could be missing under Cygwin: ATLAS, PTATLAS, MKL could still be missing regarding this issue.

**Comment by KptainBiwouak** [comment]
After some investigations, it appears:
 - nose package is required by numpy but never higlighted by pip
 - /usr/lib/lapack path has to be added to current $PATH

These 2 actions solve this issue.

**Comment by eric-wieser** [comment]
I'm not sure if any followup is needed here. Close?

**Comment by charris** [comment]
The solution looks straight forward and not something NumPy should do, so I'm happy to close this.
