### ISSUE TITLE
ufunc.reduce hides warnings

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8954]
Arguments that would cause `ufunc.__call__` to throw a warning seem to not do so when passed to `ufunc.reduce`:

Bug or feature?
```python
In [24]: np.minimum(*[1, np.nan])
RuntimeWarning: invalid value encountered in minimum
Out[24]: nan

In [25]: np.minimum.reduce([1, np.nan])
Out[25]: nan

# not just minimum
In [28]: np.divide(*[1, 0])
RuntimeWarning: divide by zero encountered in true_divide
Out[28]: inf

In [29]: np.divide.reduce([1, 0])
Out[29]: inf
```

**Comment by njsmith** [comment]
Looks like a bug to me. I suppose it could be an intentional optimization
to not check the fp flags.

**Comment by eric-wieser** [comment]
This would be quite a user visible change, as `sum`, `min`, etc would all start warning on nans

**Comment by njsmith** [comment]
Yeah. You could check on the list I guess if you're worried. But adding new useful warnings isn't generally a compatibility break, and numpy already provides good tools to control these particular warnings if people don't like the chatter.

**Comment by eric-wieser** [comment]
This is a bit of a pain - `_check_ufunc_fperr` is not visible inside `reduction.c`
