### ISSUE TITLE
vlines documentation typo

### ISSUE THREAD

**Issue by catalys1** [numpy/numpy#8956]
The documentation for the function `vlines` has a typo: in the parameters section it should say ymin and ymax, instead of xmin and xmax.
![image](https://cloud.githubusercontent.com/assets/11340846/25111724/e8a2f712-23a9-11e7-99cd-7a6579ba6aaf.png)
numpy version 1.12.1

**Comment by njsmith** [comment]
That's a matplotlib function, so I think you want their bug tracker :-)
https://github.com/matplotlib/matplotlib/issues
