### ISSUE TITLE
Numpy core attribute error on pyspark+jupyter notebook

### ISSUE THREAD

**Issue by futurikidis21** [numpy/numpy#8958]
Hi,

I am trying to install spark+jupyter notebook on a windows machine.
The problem is when i run pyspark and import numpy i get the following error from numpy:

"AttributeError: module 'numpy' has no attribute 'core'"

But when i just run Jupyter Notebook without spark everything works fine.

Can you please help on that?

Thank you

**Comment by eric-wieser** [comment]
Can you give a full traceback?

**Comment by futurikidis21** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5a0bd626bb1d> in <module>()
----> 1 import numpy

C:\Users\user\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\__init__.py in <module>()
    140         return loader(*packages, **options)
    141 
--> 142     from . import add_newdocs
    143     __all__ = ['add_newdocs',
    144                'ModuleDeprecationWarning',

C:\Users\user\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\add_newdocs.py in <module>()
     11 from __future__ import division, absolute_import, print_function
     12 
---> 13 from numpy.lib import add_newdoc
     14 
     15 ###############################################################################

C:\Users\user\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\__init__.py in <module>()
      6 from numpy.version import version as __version__
      7 
----> 8 from .type_check import *
      9 from .index_tricks import *
     10 from .function_base import *

C:\Users\user\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\type_check.py in <module>()
      9            'common_type']
     10 
---> 11 import numpy.core.numeric as _nx
     12 from numpy.core.numeric import asarray, asanyarray, array, isnan, \
     13                 obj2sctype, zeros

AttributeError: module 'numpy' has no attribute 'core'

**Comment by eric-wieser** [comment]
> But when i just run Jupyter Notebook without spark everything works fine.

Presumably by this you mean `import numpy` works fine?

**Comment by futurikidis21** [comment]
yes this is what i mean.

**Comment by eric-wieser** [comment]
What happens if you type `import numpy.core`?

**Comment by juliantaylor** [comment]
how did you install numpy?

**Comment by futurikidis21** [comment]
it results to the same message as before. It appears to be calling the correct path according to the trace back provided above. The core module is withing the numpy package folder.

**Comment by charris** [comment]
How did you install spark?

**Comment by futurikidis21** [comment]
i downloaded the required pachages: Spark,Java,Winutils etc. Then i set the path on windows. I followed similar process to the one on that link: 
https://medium.com/@GalarnykMichael/install-spark-on-windows-pyspark-4498a5d8d66c

**Comment by charris** [comment]
Hmm... All I can say is that the problems you are having are consistent with a failed install.

**Comment by guzzijones** [comment]
I have the same issue with fresh install of spark and anaconda

**Comment by Subhraj07** [comment]
is there any solution for this?

**Comment by guzzijones** [comment]
I heae python 3 does not work with spark. And that is the reason. This is 
not numpies faylt but the fualt of spark

Enviado con AquaMail para Android http://www.aqua-mail.com


En 25 de abril de 2017 01:20:12 subhrajit mohanty

**Comment by guzzijones** [comment]
Basically install 2.7 python anaconda and spark and it works

Enviado con AquaMail para Android http://www.aqua-mail.com


En 25 de abril de 2017 01:20:12 subhrajit mohanty

**Comment by Subhraj07** [comment]
I have anaconda3 installed in my machine. can I use python 2.7 along with jupyter for spark?

**Comment by mforsyth** [comment]
I am trying to use Spark with Jupyter along with another library which only exists on python3.   So I don't have the option of trying this with python 2.7.  Has anyone successfully gotten python3, numpy, and spark to work together?   @guzzijones  you mentioned that "python 3 does not work with spark".  Python3 seems to be officially supported by Spark though - are you just saying that you get this error with python3, or are you reporting some other known incompatibility?

**Comment by mforsyth** [comment]
FYI:  I was able to successfully import numpy when using python 3.5.  I can't do it when I'm running python 3.6.

**Comment by WenjieZ** [comment]
I am encountering the same issue.

My PySpark notebook used to work fine. Today, it says "AttributeError: module 'numpy' has no attribute 'core'". However, I can correctly import numpy in a pure python environment.

**Comment by WenjieZ** [comment]
Supplementing information:

Running `import numpy` for the 2nd, 3rd, etc. gives the same error message as OP. But running it for the 1st time, it gives the following error message
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-5a0bd626bb1d> in <module>()
----> 1 import numpy

/usr/lib/python3/dist-packages/numpy/__init__.py in <module>()
    140         return loader(*packages, **options)
    141 
--> 142     from . import add_newdocs
    143     __all__ = ['add_newdocs',
    144                'ModuleDeprecationWarning',

/usr/lib/python3/dist-packages/numpy/add_newdocs.py in <module>()
     11 from __future__ import division, absolute_import, print_function
     12 
---> 13 from numpy.lib import add_newdoc
     14 
     15 ###############################################################################

/usr/lib/python3/dist-packages/numpy/lib/__init__.py in <module>()
      6 from numpy.version import version as __version__
      7 
----> 8 from .type_check import *
      9 from .index_tricks import *
     10 from .function_base import *

/usr/lib/python3/dist-packages/numpy/lib/type_check.py in <module>()
      9            'common_type']
     10 
---> 11 import numpy.core.numeric as _nx
     12 from numpy.core.numeric import asarray, asanyarray, array, isnan, zeros
     13 from .ufunclike import isneginf, isposinf

/usr/lib/python3/dist-packages/numpy/core/__init__.py in <module>()
     72 
     73 
---> 74 from numpy.testing.nosetester import _numpy_tester
     75 test = _numpy_tester().test
     76 bench = _numpy_tester().bench

/usr/lib/python3/dist-packages/numpy/testing/__init__.py in <module>()
      8 from __future__ import division, absolute_import, print_function
      9 
---> 10 from unittest import TestCase
     11 
     12 from . import decorators as dec

/usr/lib/python3.6/unittest/__init__.py in <module>()
     56 __unittest = True
     57 
---> 58 from .result import TestResult
     59 from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
     60                    skipUnless, expectedFailure)

/usr/lib/python3.6/unittest/result.py in <module>()
      5 import traceback
      6 
----> 7 from . import util
      8 from functools import wraps
      9 

/usr/lib/python3.6/unittest/util.py in <module>()
    117     return (x > y) - (x < y)
    118 
--> 119 _Mismatch = namedtuple('Mismatch', 'actual expected value')
    120 
    121 def _count_diff_all_purpose(actual, expected):

/usr/lib/python3.6/collections/__init__.py in namedtuple(*args, **kwargs)
    379 
    380     def namedtuple(*args, **kwargs):
--> 381         cls = _old_namedtuple(*args, **kwargs)
    382         return _hack_namedtuple(cls)
    383 

TypeError: namedtuple() missing 3 required keyword-only arguments: 'verbose', 'rename', and 'module'
```

**Comment by eric-wieser** [comment]
@WenjieZ: do you get the same problem with `import unittest`? That doesn't look like a numpy problem to me.

**Comment by WenjieZ** [comment]
After hours of investigation, I find a workaround (in Linux). It does not solve the bug but at least let you run your code without problems.

Let me sum it up:
1. Python3.6 can import numpy correctly.
2. Python3.6 driven by Jupyter notebook can import numpy correctly.
3. Python3.6 driven by Spark, from either the terminal or the notebook, *cannot* import numpy correctly.

Therefore, the problem is at the Spark side.

A workaround is to explicitly link a Python3.5 (or any version your desire) kernel to Jupyter (it does not take consideration of your `.bashrc` configuration). In Linux, you can use the following command line code. It will add your default python (configured in `.bashrc`) as kernel.
```bash
python -m ipykernel install --user --name Python3.5
```
Ref: https://stackoverflow.com/questions/39007571/running-jupyter-with-multiple-python-and-ipython-paths/39022003

Let me know if it solves your problems.

@futurikidis21 , @guzzijones , @Subhraj07 , @mforsyth

**Comment by WenjieZ** [comment]
@eric-wieser, I can import `unittest` in Python3.6, but not when driven by Spark. Since Spark hijacks the `namedtuple` in its `serializer.py` file, there may be collision here. My Spark version is `spark-1.6.0-bin-hadoop2.6`. 

Error message:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-4f0d77ec6aeb> in <module>()
----> 1 import unittest

/usr/lib/python3.6/unittest/__init__.py in <module>()
     56 __unittest = True
     57 
---> 58 from .result import TestResult
     59 from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
     60                    skipUnless, expectedFailure)

/usr/lib/python3.6/unittest/result.py in <module>()
      5 import traceback
      6 
----> 7 from . import util
      8 from functools import wraps
      9 

/usr/lib/python3.6/unittest/util.py in <module>()
    117     return (x > y) - (x < y)
    118 
--> 119 _Mismatch = namedtuple('Mismatch', 'actual expected value')
    120 
    121 def _count_diff_all_purpose(actual, expected):

/usr/lib/python3.6/collections/__init__.py in namedtuple(*args, **kwargs)
    379 
    380     def namedtuple(*args, **kwargs):
--> 381         cls = _old_namedtuple(*args, **kwargs)
    382         return _hack_namedtuple(cls)
    383 

TypeError: namedtuple() missing 3 required keyword-only arguments: 'verbose', 'rename', and 'module'
```

**Comment by WenjieZ** [comment]
Related:
[1] https://stackoverflow.com/a/42901351
[2] https://issues.apache.org/jira/browse/SPARK-10542

**Comment by eric-wieser** [comment]
If you get the problem simply importing `unittest`, then this isn't a numpy bug.

**Comment by eric-wieser** [comment]
Oops, I forgot that this wasn't a new issue you opened, but an existing one.

**Comment by WenjieZ** [comment]
To sum it up, if you use the latest version of Spark (>=1.6.4), you can safely use Python3.6; otherwise, you should link your Spark and Jupyter with Python3.5 using the workaround I described earlier.

**Comment by WenjieZ** [comment]
@eric-wieser , I can confirm it is *not* a numpy bug but a Spark issue that has been fixed. Since I use an old version of Spark, and my lab secretly updates Python to 3.6 last weekend, I hit this error today. I believe the other people here are experiencing the same problem.

**Comment by Invince11** [comment]
@futurikidis21  Uninstalling numpy I installed earlier using pip and then installing numpy using conda as 'conda install numpy' worked for me for the same error you are facing.  It is too late for a reply but might help someone else. Also if you got this issue resolved do share the solution you used. Thanks :)

**Comment by rdekou** [comment]
I had the same error with two version of Spark 1.6 and Spark.2.0. It is not linked with the spark version but with python 3.6. 

The solution was to change the default anaconda python environment form 3.6 to 3.5. 

For that I had to update conda: 

<conda update conda>

Then I ran: 

<conda install python=3.5>

In the case there is a conflict error between python 3.5 and python 3.6 you can either remove the package causing the conflict or uninstall conda completely. 

To remove the package causing the conflict use the following:

<conda remove 'package' conda-manager>.

If you still have the same error after running the notebook. 

I will suggest doing <python -m ipykernel install --user --name Python3.5>

I ran this at the beginning and I am not sure whether  or not it helps.

**Comment by paragkr007** [comment]
Actually Spark <= 2.1.0 is not compatible with Python 3.6+.
This can be one of the reasons for the "numpy core error".
Thanks :)

**Comment by seberg** [comment]
@paragkr007 thanks for the note. I guess we can close this then. It is a very old issue lingering for a long time now. If someone runs into this or a similar issue again, it is probably better to open a new one in any case. If this is still valid, please reopen/post a new issue.
