### ISSUE TITLE
BUG: ndarray.__repr__ has no guard against recursion

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8960]
```
x = np.array([None, None])
x[0] = x
repr(x)
```

**Comment by rainwoodman** [comment]
This is interesting!

```
In [1]: x = [None, None]
In [2]: x[0] = x
In [3]: repr(x)
Out[3]: '[[...], None]'
```

**Comment by eric-wieser** [comment]
Yep, cpython has the `Py_ReprEnter` and `Py_ReprLeave` functions that enable that behaviour. (Presumably not much more than a dict lookup by id)

Of course, we probably want to handle this manually python-side, since that's where the bulk of our implementation is

**Comment by rainwoodman** [comment]
Both C side and Python side may need to be patched. I don't really understand how array_repr /array_str interacts with the python space. It is called only once in the test case -- which is strange.

**Comment by eric-wieser** [comment]
`ndarray.__repr__` is basically just a call to `array_repr`, and `ndarray.__str__` is basically just a call to `array_str`

**Comment by rainwoodman** [comment]
The crash is on IntegerFormatter. The formatter probes the data before it falls back to `array_repr` again.

**Comment by rainwoodman** [comment]
```
>>> numpy.maximum.reduce(a)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```
So the problem is not easily fixable by tweaking the formatters .. They use ufunc to probe the data and ufuncs crash when the array is recursive.

**Comment by eric-wieser** [comment]
Oh, that's an interesting one too. But I don't think that calling `maximum` is sensible on object arrays anyway?

**Comment by eric-wieser** [comment]
As a trial fix, a shim for `reprlib.recursive_repr` would be a start

**Comment by eric-wieser** [comment]
I think for object arrays, the sensible option would be `max([len(str(x)) for x in arr.flat])`

Also interesting: `x.astype(str)` does something really odd here
