### ISSUE TITLE
count_nonzero gives different result than in example

### ISSUE THREAD

**Issue by aamster** [numpy/numpy#8965]
Using numpy 1.11.1, I get a flattened sum instead of a sum along an axis
```
In [42]: np.count_nonzero([[0,1,7,0,0],[3,0,0,2,19]], axis=1)
Out[42]: 5
```

**Comment by juliantaylor** [comment]
what is your numpy version?

    np.__version__

**Comment by eric-wieser** [comment]
I can reproduce this on `1.11.1`

**Comment by juliantaylor** [comment]
the axis argument was only introduced in 1.12.
Though it is unfortunate that older versions ignore it.

**Comment by eric-wieser** [comment]
@juliantaylor: Should we close this then? It seems the only other alternative is to add a backport to 1.11 that warns about that argument, but I suspect we no longer support 1.11?

At any rate, this is documented behaviour - the docs say that the argument was added in 1.12

**Comment by mattip** [comment]
Closing.
