### ISSUE TITLE
[feature request] expose introselect functionality in numpy.partition

### ISSUE THREAD

**Issue by changhe3** [numpy/numpy#8966]
a.k.a.
add a function
numpy.select(a, kth)
that simply returns the value of the element in kth position is in the position it would be in a sorted array.
Sometimes it is just too clumsy to use numpy.partition() directly.
Thanks

**Comment by jaimefrio** [comment]
I personally don't think that saving you from typing 6 extra chars:

```
np.partition(a, k)[k]
np.select(a, k)
```

warrants adding a new function to numpy. So I am -1 on this one.

**Comment by eric-wieser** [comment]
Also note that [`np.select`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.select.html) is already a thing that exists, but does something different

**Comment by changhe3** [comment]
@jaimefrio @eric-wieser np.partition(a, k)[k] seems still need to allocate the partitioned array. Whereas np.select_kth simply return the partitioning value. I am not sure this is substantially more efficient. I guess for most applications, this does no more than saving some memory and a tiny amount of time. But if you need to, say, select kth elements in a large amount of arrays in a loop, this can save a good amount of time by not allocating that partitioned array. Sorry for bothering if this is actually insignificant.

**Comment by eric-wieser** [comment]
Is there any way to calculate the partitioning value without allocating a workspace array equal in size to the input?

When this does matter is for something like `np.partition(arr_2d, axis=-1)` -  here we allocate a full partition array, whereas `select_kth` would only need to allocate for one row (and reuse that allocation).

But in the 1d case, I see no gain at all here

**Comment by jaimefrio** [comment]
Sorry if I came across too harsh, @changhe3: you shouldn't worry at all about bothering, and are very welcome to post feature requests whenever you come up with them. We sometimes get carried away with discussing the technicalities and forget there are people behind the avatars. So please, accept my apologies!

I still think that this doesn't fit well within numpy, because the advantages it would provide are too minor to justify the extra maintenance burden, for the reasons that Eric has outlined in more detail. But if you have an actual use case where the advantage would be significant, please share it with us and I'll be happy to reconsider.

**Comment by juliantaylor** [comment]
Selection is a quite expensive operation by nature, the cost of allocating a new array is not that significant. The cost of a copy is around 10-15% of the selection cost for random ordered input.

But the larger issue is, as mentioned my Eric, there probably is no algorithm that can compute an order without temporary storage *and* with similar performance as introselect.

If you do not need to preserve the ordering of the input you can use the `.partition` member which will work inplace and thus need no extra copies.

**Comment by changhe3** [comment]
@juliantaylor @eric-wieser @jaimefrio Yes, I just realized that there are no algorithms, except for some approximate ones, for selection without allocating O(n) space. I forgot that introselect must partition the array to obtain the kth smallest element. This is my bad, thanks for discussing with me.
