### ISSUE TITLE
numpy.ma.masked_where produces array with wrong mask shape if input is of shape (1, 1)

### ISSUE THREAD

**Issue by cpaulik** [numpy/numpy#8968]
## Test script
```python
import numpy as np
print np.__version__

a = np.array([[1]])
print "orignal shape ", a.shape

b = np.ma.masked_equal(a, 1)

print "masked_equal shape", b.shape
print "masked_equal .mask shape", b.mask.shape

c = np.ma.masked_where(a == 0, a)

print "masked_where shape", c.shape
print "masked_where .mask shape", c.mask.shape
```
## output
```
1.12.1
orignal shape  (1, 1)
masked_equal shape (1, 1)
masked_equal .mask shape (1, 1)
masked_where shape (1, 1)
masked_where .mask shape ()
```
the `.mask` shape should be the same as the array shape.

**Comment by eric-wieser** [comment]
This is by design - `np.ma.array` uses `np.ma.nomask`, a single scalar, as the `.mask`, when nothing is masked.

It's not necessarily a good design, and it makes it hard to make masked array slicing return proper views, but for now, we're stuck with it

**Comment by cpaulik** [comment]
Ah, good to know. I ran into this because in combination with `np.where` this makes for some ugly special case handling because the number of return arguments changes.

```python
print np.where(c.mask)

d = np.ma.masked_where(a == 1, a)
print np.where(d.mask)
```

```
(array([], dtype=int64),)
(array([0]), array([0]))
```

**Comment by eric-wieser** [comment]
You can eliminate that special casing by using `np.ma.getmaskarray(c)` instead of `c.mask`
