### ISSUE TITLE
BUG: mixed object arrays and nan functions

### ISSUE THREAD

**Issue by pwolfram** [numpy/numpy#8974]
The following code produces non-intuitive behavior that I believe may be a bug:
```python
In [1]: import numpy as np

In [2]: import datetime

In [3]: test = np.array([[datetime.datetime(1970, 7, 15, 0, 0), 364.0],
   ...:        [datetime.datetime(2017, 2, 5, 0, 0), np.nan]], dtype=object)

In [4]: np.nanmin(test[:,1])
/Users/pwolfram/anaconda/bin/ipython:1: RuntimeWarning: All-NaN axis encountered
  #!/Users/pwolfram/anaconda/bin/python
Out[4]: nan

In [5]: np.nanmax(test[:,1])
/Users/pwolfram/anaconda/bin/ipython:1: RuntimeWarning: All-NaN slice encountered
  #!/Users/pwolfram/anaconda/bin/python
Out[5]: nan
```

I would expected output from `[4]` and `[5]` to be `364.0`, not `nan`.  Other nan functions, e.g., `nanmean` also appear to be corrupted.  Furthermore, the `RuntimeWarning` is fairly cryptic and doesn't appear to be correct.  

Is there something I'm missing here?  This is not at all what I would expect based on what boils down to a reducing function to a dimension that is effectively a numpy array that is not all `nan`s as apparently interpreted by the `RuntimeWarning`.

**Comment by eric-wieser** [comment]
On python 3, I get `TypeError: unorderable types: datetime.datetime() <= float()`.

Python 2 lets you compare anything to anything else, and get a totally random result, which is why you don't get an error

**Comment by eric-wieser** [comment]
Apologies, I forgot the slicing. I can replicate this behaviour on 3.5

**Comment by eric-wieser** [comment]
Geez, seems that `nanmin` is just completely broken on the simplest input:

```python
>>> arr = np.array([np.nan, 1], dtype=np.float64)
>>> np.nanmin(arr)
nan
```

**Comment by pwolfram** [comment]
For the record, here is a somewhat hacky fix that is obviously unsavory for several reasons (fairly arbitrary cast, introduction of `if`, increased code):

```python
def safe_nanfunc(data, nanfunc):
    if data.dtype == 'object':
        # cast to float
        data = np.ndarray.astype(data, dtype='f')
    return nanfunc(data)
```
```

**Comment by pwolfram** [comment]
```python
In [1]: import numpy as np

In [2]: np.array([np.nan, 1], dtype=np.float64)
Out[2]: array([ nan,   1.])

In [3]: np.nanmin(np.array([np.nan, 1], dtype=np.float64))
Out[3]: 1.0

In [4]: np.nanmax(np.array([np.nan, 1], dtype=np.float64))
Out[4]: 1.0
```

wasn't a problem for me.  I'm on `Python 2.7.13` via conda macOS and 
```
In [5]: np.__version__
Out[5]: '1.12.1'
```

**Comment by pwolfram** [comment]
It seems like unit tests should have caught this error, but regardless we have one above now!  @eric-wieser if you agree this is a bug how long would it take to get this pushed into a minor version number if a fix can be found quickly?

**Comment by eric-wieser** [comment]
So, the issue here is that `fmin` and `minimum` have different behaviour when they see a nan - but when applied to an object array, they both fall back on the same function, `npy_ObjectMin`.

The fix would be to add a new function, `npy_ObjectFMin`, that emulates the nan logic used elsewhere.

**Comment by pwolfram** [comment]
@eric-wieser, I should note the speed to fix isn't a real problem but more of a curiosity for me.  This is the type of thing I could likely fix but the unfortunate things is I'm under some severe time pressure right now and have a work around via `safe_nanfunc` for my current workflow.

**Comment by pwolfram** [comment]
Thanks @eric-wieser for the hints on how to fix the issue.  It sounds like this might be fast to fix but my numpy dev environment is quite stale now.  What is typically the timeline here, e.g., the process to typically get this type of thing fixed?  I can't work on this now but may be able to make some time over the next 60 days or so.

**Comment by eric-wieser** [comment]
Little more work than I expected - realistically, you'd need to write `npy_ObjectIsNan` as well, and then you could hook that up to `np.isnan`.

**Comment by eric-wieser** [comment]
There's also a quick hack fix which would be to change `nanfunctions` to take the slow path for object arrays - I'd imagine you could submit that PR directly through github

**Comment by eric-wieser** [comment]
A related bug: 6209

**Comment by eric-wieser** [comment]
@pwolfram: Numpy 1.13 will now have a workaround for this, although the underlying bugs of #9009 and #8975 are still there
