### ISSUE TITLE
Documentation: numpy.histogram2d array shapes inconsistent

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [numpy/numpy#8979]
In the [`histogram2d` documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram2d.html), the number of bins and edges is inconsistent. 

If `nx` and `ny` are the bin counts (as stated in the `bins` argument's text), then the return `H` has indeed shape `(nx, ny)`. However, the returned `xedges` and `yedges` will then have shape `(nx+1,)` and `(ny+1,)` respectively (and not as it is currently written `(nx,)` and `(ny,)`).

**Comment by eric-wieser** [comment]
Yep, I agree - do you want to submit a patch for this? You should be able to fix it right from the github editor.

Also, printing out the shape of `H` in the example code in that documentation might be handy too
