### ISSUE TITLE
nanmax does not work with groups

### ISSUE THREAD

**Issue by robpla** [numpy/numpy#8985]
The code to reproduce

    import numpy as np
    import pandas as pd
    
    df = pd.DataFrame({ 'data' : np.arange(10), 'label' : list('a'*4+'b'*6)})
    df.groupby('label')['data'].apply(np.nanmax)
```
0    3
1    3
2    3
3    3
4    9
5    9
6    9
7    9
8    9
9    9
Name: data, dtype: int32
```

I expected the last line to work the same as  `df.groupby('label')['data'].apply(np.max)`.

Expected output is: 
```
label
a    3
b    9
Name: data, dtype: int64
```

Regards

**Comment by eric-wieser** [comment]
What is the actual output?

**Comment by bashtage** [comment]
This is a simpler demonstration of the difficulty:

```
import pandas as pd
import numpy as np

np.nanmax(pd.Series([1,2,3]))

Out[8]: 
0    3
1    3
2    3
dtype: int64

np.max(pd.Series([1,2,3]))
Out[10]: 3
```

**Comment by bashtage** [comment]
Seems to be taking wrong path:

```
np.nanmax(pd.Series([np.nan,np.nan,np.nan]))

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: All-NaN slice encountered
  after removing the cwd from sys.path.
```

This error message only appears in the path the says it is not robust to subclasses here 

https://github.com/numpy/numpy/blob/eb12b7106fb2962167627af21bc0bef24f6f650d/numpy/lib/nanfunctions.py#L342


Looks like `or` should be `and`

**Comment by eric-wieser** [comment]
I don't think that `pd.Series` is a subclass - I think it's a duck type?

Evidently we didn't consider those in that function. Perhaps simply `if type(a) is np.ndarray` would be enough?

**Comment by eric-wieser** [comment]
On the other hand, when `__array_ufunc__` comes into play, that second branch shouldn't be needed at all

**Comment by bashtage** [comment]
It is not a subclass so that `not isinstance(a, np.ndarray)` is `True`.
```
a=pd.Series([np.nan,np.nan,np.nan])

isinstance(a, np.ndarray)
Out[16]: False
```

**Comment by bashtage** [comment]
> Perhaps simply if type(a) is np.ndarray would be enough?

Not clear why that first part of the `or` is there since the second part tests that it is a genuine array.

**Comment by eric-wieser** [comment]
Thanks for confirming.

I assume it is there to catch `list` and other ndarray convertibles

**Comment by seberg** [comment]
Closing, the original report returns the correct result on main.
