### ISSUE TITLE
Adding support for one-sided clipping

### ISSUE THREAD

**Issue by zfrenchee** [numpy/numpy#8990]
Hello Numpy, 

I'm using the [clip function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html), and have realized I only want to clip on one side. Setting only `a_min` results in 

```
TypeError: clip() missing 1 required positional argument: 'a_max'
```

I see [this conversation](https://mail.scipy.org/pipermail/numpy-discussion/2007-December/030262.html) from 2007, but I'm unclear as to what the conclusion attained is.

Would it be possible to support 1-sided clipping. If not, is there a better way to do this (which could be linked to in the numpy documentation?)

Thanks!

**Comment by charris** [comment]
Assign `a_max=None`. The clip function is a mess, it disagrees with the corresponding method in the parameter names and in having no defaults. Grrr...

**Comment by charris** [comment]
Because the documentation should be fixed to at least mention the `None` option, I labeled this an easy fix. We might also want to make `a_max` and `a_min` have defaults, although that won't help for earlier numpy versions.

**Comment by bashtage** [comment]
Why not `-inf` and `+inf`?

**Comment by seberg** [comment]
There is a PR open to make clip a ufunc, unfortunatly this case specifically is hard to get in there....

**Comment by eric-wieser** [comment]
That PR mentioned above is #7876

**Comment by shitian-ni** [comment]
@charris master branch seems already mentioned the None option in fromnumeric.py `clip` function comment.
But it is not in branch 1.12.x and docs.scipy.org/doc seems to be pointing to branch 1.12.x for /reference/generated

**Comment by charris** [comment]
@shitian-ni That's true. The online docs only get updated when a release is made.

**Comment by matheusportela** [comment]
Since the docs are already mentioning the `None`, should this issue be closed?

**Comment by rgommers** [comment]
Indeed, thanks @matheusportela, all
