### ISSUE TITLE
np._NoValue looks weird in help() and generated docs

### ISSUE THREAD

**Issue by crayxt** [numpy/numpy#8991]
I noticed in ```numpy.amax``` help that np._NoValue looks weird, see https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.amax.html#numpy.amax or ```help(np.amin)```, instead of ```keepdims=np._NoValue``` it is shown as ```keepdims=<class numpy._globals._NoValue>)```.

**Comment by seberg** [comment]
I suppose giving it a `__repr__` method should make it look nicer?

**Comment by b-carter** [comment]
It seems like the global singleton classes are all empty (https://github.com/numpy/numpy/blob/master/numpy/_globals.py).

Do you think it's fine to add ``__repr__`` to just ``np._NoValue``, or should similar ones be added to the other classes for consistency?

**Comment by eric-wieser** [comment]
I only see one Singleton class in that file - the others are warning types.

It's pretty wierd that `isinstance(np._NoValue, type)`

**Comment by seberg** [comment]
Yeah, warnings do not need a repr, since they are instantiated in any case. Note that you will have to do a bit of metaclassing to implement a repr for the class (as opposed to its instances).

**Comment by eric-wieser** [comment]
I don't think that NoValue being a type is a feature worth preserving.

**Comment by eric-wieser** [comment]
So no metaclasses needed - just define _NoValue = _NoValueType(), with the latter a regular class

**Comment by seberg** [comment]
I am not sure that works if you use multiprocessing? Frankly I just do not know. I think to preserve the singleton, it might have to be a class.

**Comment by b-carter** [comment]
Is it true that ``isinstance(np._NoValue, type)``? I just tested this and it returns False.

**Comment by seberg** [comment]
@b-carter, I guess it is not true for old style classes in python 2 probably. But there is no sense in using those, it should inherit from `object`. Also, it seems that the `object` part was missing earlier and is added in master.

Anyway, not sure what it matters though. The only thing I care about: If you pickle it, and load it again (in a new session) it still has to be the correct singleton (practically there is likely no case where it matters, but lets be sure). As long as that is true, anything to fix the representation seems good.

**Comment by b-carter** [comment]
@seberg, sounds good, I see there is a [test](https://github.com/numpy/numpy/blob/master/numpy/tests/test_reloading.py#L12) for reloading singletons. Is this sufficient to test whether pickling/unpickling would be problematic, as you mention? (I imagine you're asking about pickling because of potential issues with multiprocessing?)

Why would it be problematic to just add ``__repr__`` to the class as-written?

**Comment by seberg** [comment]
Yes, the test is also probably enough anyway, frankly I do not know exactly. If you add `__repr__` to the class, it will affect its instances, not the class itself. Whatever passes the tests/pickling and changes the representation of the singleton is good :).

**Comment by b-carter** [comment]
Submitted a preliminary PR that I think should fix it and adds a test. Let me know if you think that's sufficient.
