### ISSUE TITLE
How np.array([]) works in numpy

### ISSUE THREAD

**Issue by sandipmgiri** [numpy/numpy#8992]
my sample code :

```
a = 2.0
b = 3.0
x = np.array([a, b])
print x
```
Output :` [ 2. 3.]`

I just wanted to know , how this array is created here. Basically how `np.array` works ? Which constructor/function is invoking to generate this array ?

I tried putting prints in `/numpy/numpy/lib/user_array.py` but that didn't help.

**Comment by MSeifert04** [comment]
I'm not 100% sure but you could start with [`PyArray_FromAny`](https://github.com/numpy/numpy/blob/4408f743db8b5a15e9d0b5ace39ef12cafa1bce3/numpy/core/src/multiarray/ctors.c#L1681). I guess that's the routine that creates an array from a python object (like a list).

**Comment by eric-wieser** [comment]
The source code for `np.array` is `_array_fromobject` in `:/numpy/core/src/multiarray/multiarraymodule.c``

**Comment by sandipmgiri** [comment]
Now I could understand np.array([]) work, hence closing this discussion.

thanks all.
