### ISSUE TITLE
Ufunc does not call __array__ on output parameters

### ISSUE THREAD

**Issue by elliottslaughter** [numpy/numpy#9000]
According to the documentation of `__array__`, this method should get called for both inputs and outputs of ufuncs. As best I can tell, the actual behavior of the code is to call `__array__` on only inputs, not outputs.

Personally, I would prefer that ufuncs call `__array__` on output arguments, since I'd like to use this for my use case. I believe this should be safe to do as `__array__` is required to return a reference (not a copy) when `dtype` is not supplied---contrary to the comment here: https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/ctors.c#L1519-L1525

More important, however, is that the documentation be made consistent with the behavior. The numpy code isn't exactly a breeze to read through, so if the documentation isn't accurate most users are simply going to get stuck.

## Documentation

From: https://docs.scipy.org/doc/numpy/reference/arrays.classes.html#numpy.class.__array__

> If a class (ndarray subclass or not) having the `__array__` method is used as the output object of an ufunc, results will be written to the object returned by `__array__`. Similar conversion is done on input arrays.

I am reading this as saying that a call to `ufunc(..., out=myarray)` should be equivalent to the sequence:

```
x = myarray.__array__()
ufunc(..., out=x)
```

However, this is not the behavior of the code.

## Minimal Example

Here is a minimal example that demonstrates the inconsistency. The last line (marked with the comment) fails. Note that the previous two examples both work, proving that `__array__` is called on inputs, and that the output argument is well-formed if the interior array is passed directly.

```from __future__ import print_function
import numpy

class C(object):
    def __init__(self, array):
        self.array = array
    def __array__(self, *args, **kwargs):
        return self.array.__array__(*args, **kwargs)

x = C(numpy.ones([4, 4]))

print(numpy.add(x, x))
print(numpy.add(x, x, out=x.array))
print(numpy.add(x, x, out=x)) # TypeError: return arrays must be of ArrayType
```

## Code Inspection

This is not surprising based on a cursory reading of the code:

  * Inside `get_ufunc_arguments`, `PyArray_FromAny` is used on all input arguments: https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L825
  * However, later in the same function, I don't see any such invokation for the output: https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L995
  * And `_set_output_array` simply calls `PyArray_Check`: https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L741

Moreover, this means that even a use of `__array_struct__` or `__array_interface__` in this context wouldn't work. The output type must literally be a subclass of the array type.

Again, I believe this comment in `PyArray_FromAny` is incorrect; the semantics of `__array__` is to return a reference if dtype is not supplied, so it likely would be ok to use for output arrays. https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/ctors.c#L1519-L1525

## Versions

  * Numpy 1.12.1 (installed with pip)
  * Python 2.7.6 (from Ubuntu package)
  * Ubuntu 14.04

**Comment by njsmith** [comment]
I'm a little nervous about changing this; the main`__array__` users that are jumping to mind return copies (e.g. dask). And this request is coming just as we're in the process of finalizing a new and better way for custom classes to override ufuncs (search `__array_ufunc__`).

Cc @mrocklin

**Comment by mrocklin** [comment]
Dask currently interprets the `__array__` protocol as a request to "please turn this thing into a new numpy array", which it is happy to do.  If the following is to be standard behavior:

```python
x = myarray.__array__()
ufunc(..., out=x)
```

Then yes, this doesn't make much sense for dask.arrays.  However using `out=my_dask_array` probably didn't make much sense for dask.arrays in the first place just because they don't really support in-place operations (they do semantically, but there is no performance benefit).  

So I guess if I understand this issue correctly (which I'm not sure about) then I think my vote here is "No, this doesn't make sense for Dask but it doesn't matter that much because Dask users aren't doing this anyway."  If they did start wanting to do this, which I could see happening mostly just to produce single codebases that worked on either NumPy or Dask.array, then I would be against this change.

**Comment by shoyer** [comment]
I would also lean against changing this behavior now, given that `__array_ufunc__` is a much more complete solution and that this wouldn't work well for many classes that actually implement `__array__`.

So let's fix-up the documentation instead.
