### ISSUE TITLE
Can't build docs if twine installed.

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy#9005]
This one is fun. I'm going to skip directly to why.

When building docs  encountering ``` numpy/add_newdocs.py: The item should be a scalar value and `args` ```, autolink of sphinx ext kicks in. One of the things it does is attempting to import  whatever is in between ``` `...` ```, which happen to be `args` thus importing [`args`](https://github.com/kennethreitz/args) , installed by [`clint`](https://github.com/kennethreitz/clint), installed by [`twine`](pypi.python.org/pypi/twine) which you might have installed  to publish packages on PyPI.

The only available released versions of `args`  is Python 2 only (uses `basestring` which is undefined on Py3), and has not seen an update in ~5 years even if seem to be fixed on `args` master. 

So sphinx fails as it try to (indirectly) evaluate `basestring`. And no docs get produced.

Reproduced on Fresh ubuntu 17.04.

I'm not sure there is anything one can do (inject a fake `args` in sys modules via `conf.py` ?) but I want to at least make you aware, as I have little hope to see a fix in clint or args with the slow pace of release.

**Comment by charris** [comment]
Hmm, I'm not sure what the ``` `...` ```  should be doing. The effect in the documentation is italics, not a link, or at least I thought so. One thing you might try is fooling with the `arg` part of that docstring, which is `\\*args` in master. Maybe a straight `args` would make a difference.

@rgommers ping just to make sure that I understand how numpydoc handles ``` `...` ```.

**Comment by Carreau** [comment]
Sorry I was unclear, on master it is

```
as *item*.  Then, ``a.itemset(*args)`` is equivalent to but faster
than ``a[args] = item``.  The item should be a scalar value and `args`
                                                                 ^ this args     
```

Which triggers the issue and my guess is that it's rst default role, which (by default) is `:any:` and likely is what in the code is called `autolink`.

In numpydoc syntax IIUC ``` `<whatever>` ``` is supposed to be parse as "the parameter of the current function named `<whatever>`". In docutils it will be a `title_reference` node as fa as I can tell.

The annoying thing is that any module that would raise at import may trigger that (agreed that's a small chance), but it might just be a symptom of a bigger problem.

**Comment by charris** [comment]
Fooling around a bit, I see links in the generated html docs. If I replace ``` `args` ``` by ``` `\\*args` ``` it is in italics, but not a link. And if I change the parameter to `args` in the parameter section the reference is in red, but there is no link to anywhere. Strange...

Just to be clear, this is a problem that only shows up in python 3?

i'll bet it was fun chasing this down 8-).

**Comment by Carreau** [comment]
> Just to be clear, this is a problem that only shows up in python 3?

Yes, and it goes away if you uninstall `args`.

> i'll bet it was fun chasing this down 8-).

Oh, you have no ideas.

**Comment by pv** [comment]
To be clear, that's a bug in sphinx.ext.autolink --- it should catch the 
import failure rather than crashing.

**Comment by eric-wieser** [comment]
@pv: Although it sounds like we're also using the wrong format in our documentation to refer to argument names.

**Comment by InessaPawson** [comment]
@Carreau Hi, Matthias! Given the age of this issue, I wonder if it's still relevant.

**Comment by Carreau** [comment]
Yeah, let's close.
