### ISSUE TITLE
Possible error in documentation for indexing

### ISSUE THREAD

**Issue by zengi** [numpy/numpy#9010]
On the following page:
https://docs.scipy.org/doc/numpy-1.12.0/reference/arrays.indexing.html

it states that :

> Assume n is the number of elements in the dimension being sliced. Then, if i is not given it defaults to 0 for k > 0 and n - 1 for k < 0 . If j is not given it defaults to n for k > 0 and -1 for k < 0

Should not this be that "If j is not given it defaults to n for k > 0 and -n-1 for k < 0".  For example:
```
In [25]: a1 = np.array([1,2,3])

In [26]: a1[::-1]
Out[26]: array([3, 2, 1])

In [27]: a1[2:-4:-1]
Out[27]: array([3, 2, 1])

In [28]: a1[2: -1:-1]
Out[28]: array([], dtype=int32)
```

**Comment by eric-wieser** [comment]
Seems reasonable to me. Do you want to submit a patch?

**Comment by zengi** [comment]
I am not quite sure how to submit a patch.

**Comment by crackadd1ct** [comment]
Fork the repository, make your change in the appropriate place, then submit a pull request for the project supervisors to approve. Probably include a link to this issue to make it clear why you did this and that it was approved by a project member prior to implementation

**Comment by eric-wieser** [comment]
Or easier, you can just hit edit on the relevant `.rst` file on github, and fix it from your browser
