### ISSUE TITLE
Scipy sparse inplace fails after __array_ufunc__ merge

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9019]
The following works before merge of #8247.
```
In [1]: import scipy.sparse as sp

In [2]: a = np.array((2,3))

In [3]: a += sp.lil_matrix(a)
```
After merge
```
In [1]: import scipy.sparse as sp

In [2]: a = np.array((2,3))

In [3]: a += sp.lil_matrix(a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-4472ce1a04df> in <module>()
----> 1 a += sp.lil_matrix(a)

TypeError: ufunc 'add' output (typecode 'O') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

The sparse matrices depend on the fact that they are cast to objects, so this is a function of how object arrays are handled,

**Comment by charris** [comment]
Probably missing priority forwarding for inplace operators.

**Comment by pv** [comment]
Probably indeed `__array_priority__` handling. In previous numpy:
```
>>> a.__iadd__(sp.lil_matrix(a))
NotImplemented
```
current master:
```
a.__iadd__(sp.lil_matrix(a))
Traceback (most recent call last):
  File "<ipython-input-3-c4acac29d15e>", line 1, in <module>
    a.__iadd__(sp.lil_matrix(a))
TypeError: ufunc 'add' output (typecode 'O') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

**Comment by charris** [comment]
Hmm, we are still depending on ufuncs returning `NotImplemented`, that doesn't seem right. This seems like the sort of thing that should be handled at the ndarray level.

**Comment by charris** [comment]
This fixes the inplace add
```
diff --git a/numpy/core/src/multiarray/number.c b/numpy/core/src/multiarray/number.c
index 0d667ac..2ee2c2d 100644
--- a/numpy/core/src/multiarray/number.c
+++ b/numpy/core/src/multiarray/number.c
@@ -628,6 +628,7 @@ array_bitwise_xor(PyArrayObject *m1, PyObject *m2)
 static PyObject *
 array_inplace_add(PyArrayObject *m1, PyObject *m2)
 {
+    BINOP_GIVE_UP_IF_NEEDED(m1, m2, nb_add, array_add);
     return PyArray_GenericInplaceBinaryFunction(m1, m2, n_ops.add);
 }
```
The result is that a is replaced by a matrix, python rules. but that is as before.

I seems that all the inplace operators suffer the same omission. Major test failure ;)

**Comment by charris** [comment]
@juliantaylor What happens to the elision code if the inplace function returns `NotImplemented`?

**Comment by eric-wieser** [comment]
[Called it ;)](https://github.com/numpy/numpy/pull/8247#issuecomment-296254798)

**Comment by eric-wieser** [comment]
There's a hidden discussion [here](https://github.com/numpy/numpy/pull/8247#discussion_r112754755) with some rationale

**Comment by charris** [comment]
See #9021.

**Comment by charris** [comment]
@pv Would it be appropriate to raise a `DeprecationWarning` in this case while preserving past behavior? The return value really isn't consistent with the ndarray inplace behavior.

**Comment by pv** [comment]
I think what's deprecated is not so much this behavior, but the 
__array_priority__ attribute itself.

**Comment by pv** [comment]
For scipy.sparse the warning would make sense if scipy.sparse would plan 
to deprecate the in-place behavior, but this will not be done so the 
warning is just noise --- instead, the plan is to add replacement sparse 
ndarray semantics compatible classes. I don't see a way to do any 
gradual evolution of the old stuff, and it's better to just keep old 
codes working.
