### ISSUE TITLE
unravel_index([], (n, m)) gives unhelpful TypeError message

### ISSUE THREAD

**Issue by fgregg** [numpy/numpy#9034]
If you call `numpy.unravel_index`, with an empty Python sequence, it returns a mysterious complaint about the dtypes being of the wrong type. 

In my opinion, it should return the same thing as when you call it with an empty numpy array.

```python
>>> numpy.unravel_index([], (2, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Iterator operand 0 dtype could not be cast from dtype('float64') to dtype('int64') according to the rule 'same_kind'
>>> numpy.unravel_index(numpy.array([], dtype='int'), (2, 3))
(array([], dtype=int64), array([], dtype=int64))
```

**Comment by jaimefrio** [comment]
You are getting the same error you would get if you hadn't "cheated" by adding a dtype to your second example, aren't you? As far as NumPy is concerned, `[]`  is `np.array([])`, which defaults to `dtype=float`. So I think it rightfully fails, and should keep doing so: without extra complexity the fix you are requesting is very likely to also open the door to `np.array([], dtype=float)` being accepted, and that is a route we decided some time ago we don't want to go down.

The error message could certainly be more informative, I fully agree on that one.

**Comment by fgregg** [comment]
Good point. A clearer error message would be great.

**Comment by noamzilo** [comment]
ok... I am also getting this error, but I still have no idea what I'm doing wrong.

        hires = np.array(self.hr_shape)
        lowres = np.array(self.lr_shape)
        h, w = hires // lowres

        hr_to_lr_ind_map = np.arange(np.prod(lowres)).reshape(lowres)

        self.lines_list_ind_lr = []
        for line_hr in self.lines_list_ind_hr:
            i, j = np.unravel_index(line_hr, hires)
            line_lr = hr_to_lr_ind_map[i // h, j // w]
            self.lines_list_ind_lr.append(line_lr)

here, line_hr is a ndarray of shape (138,1) [of indexes. i.e ints]

The code follows this
https://stackoverflow.com/questions/53906261/how-to-get-a-mapping-from-high-to-low-resolution-ndarray-in-numpy


What am I not getting right?

**Comment by seberg** [comment]
The error is helpful now, and I think we didn't want to do more at the time.  So closing.
