### ISSUE TITLE
Intel compiler flags set xHost

### ISSUE THREAD

**Issue by wscullin** [numpy/numpy#9042]
I hate to rehash #7287, but the [Intel Fortran compiler](https://github.com/numpy/numpy/blob/a188a3448537ade540fbde9a8782aac318b99896/numpy/distutils/fcompiler/intel.py) still references xHost which may lead to issues when the build and execution host don't share an architecture. 

Since there's a guarantee that the user will be compiling with the Intel compiler, there's the [option](https://software.intel.com/en-us/node/682440) to create multiple code paths with the `-ax` flag. For instance, in my local builds I have: `-xAVX -axMIC-AVX512,CORE-AVX512,CORE-AVX2,SSE4.2` which builds an AVX baseline path, but then looks for opportunities to build alternate code paths for listed processor features. The only issue that may appear is when the version of the Intel compiler is too old to recognize a processor feature as a valid option to `-ax`.

**Comment by rgommers** [comment]
Thanks @wscullin. That's not a rehash of gh-7287 but a bug that was missed when removing the SSE4.2 flags in gh-7655. Will submit a fix.
