### ISSUE TITLE
BUG: Changes to core/ufunc_docstrings are ignored in incremental builds

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9046]
The contents of this file is loaded at generation-time into `generate_umath.py`. Unfortunately, the condition for regenerating the c code is not dependent on whether this file has changed

**Comment by rgommers** [comment]
This rebuild seems to be done correctly now after the switch to Meson:

```
$ spin build
$ spin build
....
[1/1] Generating numpy/generate-version with a custom command

$ touch numpy/core/code_generators/generate_umath.py
$ spin build
...
[5/5] Linking target numpy/core/_multiarray_umath.cpython-39-darwin.so
```

Nice to have a good build system:) It's not impossible there's still missing links, but we have a check with `ninja -C build -t missingdeps` and it should be correct for everything `ninja` knows about.
