### ISSUE TITLE
np.ma.median does not work on multiple axes when input is masked

### ISSUE THREAD

**Issue by dingwell** [numpy/numpy#9048]
I'm not sure if this is a bug but I found something inconsistent.

numpy.ma.median accepts tuple arguments for the axis keyword when given an unmasked array (and returns the expected result). If the array is masked but the mask is empty (A.mask == False) it also works. If, however, the mask is not empty (i.e. the mask itself is an array), numpy.ma.median will return an error.

```python
import numpy as np
x1 = np.random.rand(2,5,5)                # normal array
x2 = np.ma.asarray(x1)                    # no mask
x3 = np.ma.where(x1>0.5,np.ma.masked,x1)  # partially masked

np.ma.median(x1,axis=(1,2)) # Returns an array of shape (2,)
np.ma.median(x2,axis=(1,2)) # Returns an array of shape (2,)
np.ma.median(x3,axis=(1,2)) # Raises TypeError
np.ma.median(np.ma.reshape(x3,(2,25)),axis=1) # Works as expected but is less clear
```

Python version: 2.7.12
NumPy version: 1.11.0

**Comment by MSeifert04** [comment]
Definetly weird, because according to the [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.median.html) multiple axis shouldn't be supported at all. Maybe it just delegates to `np.median` (which supports multiple axis) when it has no mask.

**Comment by eric-wieser** [comment]
Your code runs without error on 1.13.
