### ISSUE TITLE
np.sum with keepdims fails when input is a 1d array 

### ISSUE THREAD

**Issue by YontiLevin** [numpy/numpy#9064]
got the following error when running np.sum(a, axis=1, keepdims=True):
`TypeError: sum() got an unexpected keyword argument 'keepdims'`

when a.shape is (100,2) everything works fine
but
when a.shape is (1,2) i get this error

got it solved by an if but this should be handled intrinsically
thanks

**Comment by seberg** [comment]
This only makes sense to me if `a` is not actually an array, so can you give an example and the numpy version? With typical arrays, it works fine.

**Comment by YontiLevin** [comment]
checked the type
a is a matrix

got this error when following the tutorial from here:
http://peterroelants.github.io/posts/neural_network_implementation_part04/

**Comment by seberg** [comment]
True enough, but best to avoid matrix class anyway. My guess it is there in the first place as an accident.

**Comment by YontiLevin** [comment]
Thanks,
when casting a to an array (using np.asarray) this error went away
