### ISSUE TITLE
CLN: Yield tests are deprecated, and scheduled to be removed in pytest 4.0

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#9067]
I recently setup a new dev environment with the latest pytest (3.0.7). Running the numpy test suite, I get a *lot* of warnings like this (e.g., 81 times from `test_multiarray.py`):
`WC1 /Users/shoyer/dev/numpy/numpy/core/tests/test_multiarray.py yield tests are deprecated, and scheduled to be removed in pytest 4.0`

I guess we should look into this, so our test suite doesn't break when pytest 4.0 comes out :)

**Comment by charris** [comment]
There was a GSOC proposal that would have covered that for Scipy with a side NumPy that I was hoping would take care of that. Yield tests are also a big part of `numpy.polynomial` testing.

I wonder if we can implement a Nose compatible version of the PyTest parametrize decorator?

**Comment by charris** [comment]
There is https://pypi.python.org/pypi/parameterized that might help with the transition. Might be others as well.

**Comment by ev-br** [comment]
Meanwhile, there's a workaround for silencing the pytest noise: http://stackoverflow.com/questions/40710094/how-to-suppress-py-test-internal-deprecation-warnings

**Comment by bashtage** [comment]
xref #9352

**Comment by charris** [comment]
Done in #10859. I'm going to close this, these pytest things are being tracked at #10856.
