### ISSUE TITLE
DOC: Missing for nextafter and spacing

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#9076]
These functions show up [here]( https://docs.scipy.org/doc/numpy/reference/ufuncs.html#floating-functions ), but I am unable to find other documentation about them including their APIs in the docs.

**Comment by eric-wieser** [comment]
Pretty sure that's fixed in master

**Comment by jakirkham** [comment]
Ok, is there any chance we could get the docs rebuilt then? Not sure how NumPy handles these sorts of things though.

**Comment by jakirkham** [comment]
Looks like the rebuilt docs online now include the API docs.
