### ISSUE TITLE
ENH: call np.positive in ndarray.__pos__, and issue a deprecation warning when it falls

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#9081]
As I wrote in https://github.com/numpy/numpy/pull/8967#issuecomment-300273518:

> Probably, the desired behavior is something like:
```python
def __pos__(self):
    try:
        return np.positive(self)
    except TypeError:
        issue deprecation warning
        return self.copy()
```
> (This may be a little tricky, though, because it will need to be done in C.)

This will be useful for ndarray subclasses that override `__array_ufunc__`.

**Comment by eric-wieser** [comment]
I think you also want `if self.__array_ufunc__ != ndarray.__array_ufunc__` in there, so that if `__array_ufunc__` raises a `TypeError` it's not just swallowed

**Comment by njsmith** [comment]
In fact, that could potentially replace the `TypeError` catch altogether?
```python
if self.__array_ufunc__ is not ndarray.__array_ufunc__:
    return np.positive(self)
else:
    return self.copy()
```
I don't think we'd even need to deprecate anything if we did it this way.

**Comment by eric-wieser** [comment]
Difference would be that `__array_wrap__` would never see `np.positive`, but I don't think we care. So that does sound like a good solution

**Comment by njsmith** [comment]
Or more precisely, `__array_wrap__` would see explicit calls to `np.positive`, but wouldn't see calls to `__pos__` (just like today). And that's actually probably what we want, since we don't want to risk breaking existing `__array_wrap__` users.

**Comment by shoyer** [comment]
> I don't think we'd even need to deprecate anything if we did it this way.

I also wanted to deprecate calls like `+np.array(['foo'])`, which currently works but should really raise an error.

But we could switch to only catching `TypeError` if `__array_ufunc__` is not set. Something like:
```python
def __pos__(self):
    if self.__array_ufunc__ is not ndarray.__array_ufunc__:
        return np.positive(self)
    else:
        try:
            return np.positive(self)
        except TypeError:
            issue deprecation warning
            return self.copy()
```

**Comment by ngoldbaum** [comment]
I'll just say that it would be really nice if `np.positive` were invoked by `operator.pos`. With `__array_ufunc__` I've been able to remove all of the magic method overrides on my ndarray subclass except for the override for `__pos__` due to this issue.

**Comment by eric-wieser** [comment]
@ngoldbaum: Although it's also really not hard for you to use `def __pos__(self): return np.positive(self)` until this is fixed :)

**Comment by ngoldbaum** [comment]
I realize, it's just yet another corner case that an implementer of an ndarray subclass needs to deal with.

**Comment by shoyer** [comment]
@ngoldbaum this logic is all pretty self-contained (I would start [here](https://github.com/numpy/numpy/blob/d0c15fab8e3c0324914baede7496810485eb4e56/numpy/core/src/multiarray/number.c#L1051)), so implementing something like @njsmith's suggestion both would be straightforward. Contributions would certainly be welcome!

It would indeed be nice to get this into 1.13 before the final release.

**Comment by mhvk** [comment]
See #11450 for a fix.
