### ISSUE TITLE
BUG: tostring output incorrect when using newbyteorder

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#9084]
If I take an array and create a view using newbyteorder, the output from ``tostring`` is not byteswapped:

```python
In [2]: import numpy as np

In [3]: x = np.array([1,2,3], dtype=np.int16)
   ...: y = x.byteswap(False)
   ...: z = x.newbyteorder('S')

In [4]: print(x.tostring())
b'\x01\x00\x02\x00\x03\x00'

In [5]: print(y.tostring())
b'\x00\x01\x00\x02\x00\x03'

In [6]: print(z.tostring())
b'\x01\x00\x02\x00\x03\x00'
```

I think ``z.tostring()`` should match ``y.tostring()`` instead?

I'm using Numpy 1.11.2 with Python 3.6

A related issue is that the ``data`` memoryview on ``z`` is also not byteswapped, i.e.:

```python
import numpy as np
from io import BytesIO

x = np.array([1,2,3], dtype=np.int16)
y = x.byteswap(False)
z = x.newbyteorder('S')

for array in [x, y, z]:

    b1 = BytesIO()
    b1.write(array.data)
    b1.seek(0)
    print(b1.read())
```

gives:

```
b'\x01\x00\x02\x00\x03\x00'
b'\x00\x01\x00\x02\x00\x03'
b'\x01\x00\x02\x00\x03\x00'
```

**Comment by pv** [comment]
newbyteorder documentation: "Return the array with the same data viewed 
with a different byte order."

**Comment by juliantaylor** [comment]
`newbyteorder` returns a view of the same data with interpreted with a different byteoder, it does not change the raw data of the array.
`tostring` (or better `tobytes`) returns the raw databuffer of the array. As changing the byteorder did not change that you still get the original data.
To actually swap the databuffer you have to use `byteswap`

**Comment by matthew-brett** [comment]
`newbyteorder` changes the metadata for the array, telling it to interpret the data as being byteswapped.  It does not change the backing memory for the array.   `tostring` returns a byte string corresponding to the backing memory for the array.  The backing memory for `z` is unchanged compared to `x`, which is what you see in the `tostring` output.

**Comment by juliantaylor** [comment]
neat 3 equivalent answers within  10 seconds :D

**Comment by pv** [comment]
I think we broke the record :)

**Comment by astrofrog** [comment]
Thanks for the replies, and sorry for mis-identifying this as a bug - I was hoping to have a way to get a byte representation of the array without modifying the array in-place (need to support read-only arrays) and without doubling memory usage. Is there a way to do this within Numpy?

**Comment by seberg** [comment]
Sure, you should be able to create the new view (as you did) and then use assignment or `np.copyto(orig, orig_with_new_byteorder)` or `orig_with_new_byteorder[...] = orig`. (assuming you don't have self overlapping memory). It might do buffering, but it won't copy the whole array (in which case it is possible that it is actually slower then copying the whole array for small arrays). Both methods will do the exact same thing internally.

**Comment by juliantaylor** [comment]
that will to the same as `byteswap(True)`, so inplace swap.
I don't think there is a way to get swapped python bytes without a copy.
Can you use memoryviews instead of bytes? (note its tobytes also copies and views the original unswapped data)

**Comment by seberg** [comment]
Oh, sorry misread... but doing that then is hard without duplicating the memory (you need it swapped after all at least when you get the string). I doubt you can avoid copying it once more for the string itself, since strings need to make sure their data is read only. Depending on what you do with the string, I suppose a memoryview or `array.array` might allow you to avoid the string and thus one copy.

**Comment by seberg** [comment]
Yeah, ooops, that already does that.... I suppose there is no way then

**Comment by astrofrog** [comment]
@seberg @juliantaylor @pv @matthew-brett I'd like to follow up on this a little - the reason I opened this in the first place is because I'm writing some code that does some I/O, and I get arrays from the user, but I don't know if they have done a ``newbyteorder`` view. The issue is that ``.dtype`` gets updated but ``tostring`` doesn't match:

```python
In [5]: x = np.array([1,2,3], np.int16)

In [6]: x.dtype
Out[6]: dtype('int16')

In [7]: x.tostring()
Out[7]: b'\x01\x00\x02\x00\x03\x00'

In [8]: y = x.newbyteorder('S')

In [9]: y.dtype
Out[9]: dtype('>i2')

In [10]: y.tostring()
Out[10]: b'\x01\x00\x02\x00\x03\x00'
```

As a developer of an I/O package, how can I make sure that I know that ``y.dtype`` doesn't match ``y.tostring()``? Is there a flag that indicates I should treat ``y`` with caution when it comes to I/O and that I can't just use ``dtype`` and ``tostring`` together?

**Comment by eric-wieser** [comment]
In what sense do you claim that the dtype and string do not match?

**Comment by juliantaylor** [comment]
dtype assigns the meaning to the data, it always matches the data in an ndarray.
When doing IO you need preserve the meaning, which means save the information in the dtype along with the dtype.
Every useful IO format defines equivalent to the numpy dtype, i.e. it may assigns a fixed dtype (like big endian for fits) or stores the metadata like long with the data like np.save.

So when storing ndarrays, always read the dtype and decide from that what to do. If it is already in the correct endian you can just store it directly (tobytes can be used), if not you have to swap first.

You could use `copyto` into a memory mapped ndarray to save memory. Or implement that yourself with a small loop swapping small chunks of the array before saving.

**Comment by eric-wieser** [comment]
Try actually printing `x` and `y` in your above example, and I think it will become more clear what is going on.

**Comment by juliantaylor** [comment]
for example:

```python
def little_endian_byte_store(arr):
    assert arr.carray # fortran order needs special handling
    arr = arr.ravel()
    dest = np.empty(4096, '<i4') # fixed endianness
    for i in range(0, arr.size, 4096):
        # convert whatever endian the input is to dest
        # could be skipped if byteorder is already correct, though this is very cheap compared to io
        dest[...] = arr[i:i+4096]
        store(dest.tobytes())
```
