### ISSUE TITLE
np.vstack and friends fail with empty sequence as input

### ISSUE THREAD

**Issue by kohr-h** [numpy/numpy#9086]
Due to [this check](https://github.com/numpy/numpy/blob/c11628abd820a1f44b052ea87af810f8f00cf2e4/numpy/core/src/multiarray/multiarraymodule.c#L334-L338) we have the following:
```python
>>> np.vstack([])
  File "<ipython-input-14-d10b437c017f>", line 1, in <module>
    np.vstack([])

  File "[...]/lib/python3.6/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)

ValueError: need at least one array to concatenate
```
I wonder why `concatenate` not simply returns an empty array of the requested shape, which I guess is `(0, 0)` in this case.

**Comment by eric-wieser** [comment]
How can `concatenate` know what shape to return there? It doesn't know that you were trying to pass 2d inputs.

**Comment by eric-wieser** [comment]
Remember, when `tup` is empty, `[atleast_2d(_m) for _m in tup]` is exactly the same as `[atleast_1d(_m) for _m in tup]`

**Comment by kohr-h** [comment]
Yes, I realize that. But wouldn't the `axis=0` argument imply the shape anyway?

Even if I'm wrong on this matter, wouldn't it still make sense if `concatenate` returned something if given empty input?

**Comment by kohr-h** [comment]
So my (adjusted) expectation would be
```python
>>> np.concatenate([], axis=whatever)
array([], dtype=float64)
```

**Comment by kohr-h** [comment]
Okay, after thinking about this for a while, I think the logic is that `axis` must be less than the common `ndim` of all inputs, which is undefined for no input. What I was thinking of was actually `np.vstack([[]])` which works as expected.
