### ISSUE TITLE
DOC: "Guide to NumPy" link leads to ads

### ISSUE THREAD

**Issue by tv3141** [numpy/numpy#9088]
The link is at the bottom of the SciPy documentation frontpage: https://docs.scipy.org/doc/

The domain under which the "Guide to Numpy" was available has been abandoned.

I could not find an official source for Travis Oliphant's "Guide to Numpy" (2006, Public domain since 2008?)

The second addition is currently only available on Amazon.

Is there another legitimate URL for the PDF book "Guide to Numpy" (2006)?

**Comment by pv** [comment]
https://github.com/numpy/numpy/tree/maintenance/1.6.x/doc/numpybook
.
Note that the content is essentially the same as the Numpy main 
documentation, except out of date.

**Comment by tv3141** [comment]
Better remove the link then?

**Comment by eric-wieser** [comment]
I think these docs are under scipy, so you should report the issue there

**Comment by shoyer** [comment]
see https://github.com/scipy/scipy.org/issues

**Comment by tv3141** [comment]
The URL of the book link is only in the Numpy repo.

https://github.com/numpy/numpy/search?utf8=%E2%9C%93&q=www.tramy.us&type=  [2 results]
https://github.com/scipy/scipy.org/search?utf8=%E2%9C%93&q=www.tramy.us&type=  [0 results]

**Comment by rgommers** [comment]
Fixed by gh-10592, closing
