### ISSUE TITLE
BUG __array_ufunc__ does not work well with output set on reduce, accumulate, reduceat

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#9105]
As noted by @eric-wieser in https://github.com/numpy/numpy/pull/9104#discussion_r116126413, currently `__array_ufunc__` does not actually work as advertised if `out` is set on anything but `__call__`: if it is, it is turned into a `tuple`, but if that is passed back to the regular non-overriden ufunc, one gets an error, since those do not know how to deal with tuples.

Two possible solutions:
1. We break the "`out` is always a tuple" rule for `reduce`, `accumulate`, `reduceat`; if we do this, my sense would be to give up the whole tuple idea for `nout=1`, and just do it only for `nout>1`...
2. We allow passing in of tuples in the `ufunc.reduce`, `ufunc.accumulate`, and `ufunc.reduceat` methods.

I think I slightly favour option 1 even though I definitely have argued differently before.

p.s. Interesting how quickly reality hits!

@pv, @njsmith, @charris, @eric-wieser - suggestions?

**Comment by eric-wieser** [comment]
`out` also works fine on `outer`, I'd assume

**Comment by eric-wieser** [comment]
I'd favor option 2 for consistency, I think - especially since I'd like to see `ufunc.reduce` become a gufunc someday

**Comment by mhvk** [comment]
well, option 2 is the easier, so I'll take this as a reason to at least make a PR for it...

**Comment by mhvk** [comment]
See #9106 for an implementation of option 2. Definitely the easier route...

**Comment by mhvk** [comment]
closing this since a fix is now ready.
