### ISSUE TITLE
TST: __array_ufunc__ cannot be overridden on axis, etc.

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#9107]
While looking at our `__array_ufunc__` implementation, I noticed that it looks on all `args` and any `kwargs['out']` entry. This is OK for the regular `ufunc.__call__`, but for the other methods, it means that if you pass in, e.g., an axis as a positional argument with something that overrides `__array_ufunc__`, it is counted, and you get your override. This is probably not intended, if only because it means positional and keyword arguments are treated differently...

Unlike the other issues, probably a bit less critical, but still, should be fixed.

**Comment by seberg** [comment]
Changing title/tag, since gh-15271 will fix this, but new tests for it might be good.

**Comment by mhvk** [comment]
Ah, yes, I vaguely seemed to recall there was an issue open for it - and then it turns out to have been mine! I think it is definitely good to have it fixed!

**Comment by mhvk** [comment]
fixed by #15271
