### ISSUE TITLE
Numpy Legend Error --"#using-proxy-artist".format(orig_handle)-- (Pie Chart)

### ISSUE THREAD

**Issue by NedySuprianto** [numpy/numpy#9108]
i got error when i need to add legend in numper pie chart, i want to add legend to show like memory status used and free memory.

ex:
Used 30000
Free 40000

**_but i got err:_**

C:\Users\Nedy Suprianto\python\lib\site-packages\matplotlib\legend.py:634: UserWarning: Legend does not support 'Used' instances.
A proxy artist may be used instead.
See: http://matplotlib.org/users/legend_guide.html#using-proxy-artist
  "#using-proxy-artist".format(orig_handle)
C:\Users\Nedy Suprianto\python\lib\site-packages\matplotlib\legend.py:634: UserWarning: Legend does not support 'Free' instances.
A proxy artist may be used instead.
See: http://matplotlib.org/users/legend_guide.html#using-proxy-artist
  "#using-proxy-artist".format(orig_handle)

**_*show-memory.csv file_**
Used;Free;
26932152;47036848;

**_here's my ugly code :) :_**

`import matplotlib.pyplot as plt
import numpy as np

plt.rcParams['text.color'] = 'k'

data = np.loadtxt('show-memory.csv' ,dtype=bytes, delimiter=';', usecols=(0, 1)).astype(str)
slice = data[1]
xt = np.loadtxt('show-memory.csv', dtype=bytes, delimiter=';', usecols=(0, 1)).astype(str)
labels = (xt[0])
colors = ['lightskyblue', 'lightcoral']
explode = [0.05, 0]
plt.pie(slice, labels=labels, colors=colors, explode=explode, startangle=90, shadow=True, autopct='%1.1f%%')

plt.title('Memory Statistic\n(Bytes)')
plt.legend(labels, slice, loc='upper left')
plt.show()`

**Comment by njsmith** [comment]
Numpy itself only provides the stuff you get by using `np.something`. All the plotting code here is from matplotlib, so you should file this bug report [with them](https://github.com/matplotlib/matplotlib). Or possibly ask on stackoverflow.com. Good luck!
