### ISSUE TITLE
Installation no longer tells user when Intel compiler is not on PATH

### ISSUE THREAD

**Issue by drhagen** [numpy/numpy#9117]
When compiling on Windows with the Intel compiler, Numpy 1.12.1 tells you if the compiler is not in the PATH. In the upcoming 1.31.0rc1 release, this error message is gone.

The error used to be:

```
icl.exe /c /nologo /O3 /MD /W3 /Qstd=c99 -Inumpy\core\src\private -Inumpy\core\s
rc -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\cor
e\src\umath -Inumpy\core\src\npysort -IC:\Anaconda3\envs\temp\include -IC:\Anaco
nda3\envs\temp\include /Tc_configtest.c /Fo_configtest.obj
Could not locate executable icl.exe
Executable icl.exe does not exist

failure.
```

The error is now:

```
icl.exe /c /nologo /O3 /MD /W3 /Qstd=c99 -Inumpy\core\src\private -Inumpy\core\s
rc -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\cor
e\src\umath -Inumpy\core\src\npysort -IC:\Anaconda3\envs\temp\include -IC:\Anaco
nda3\envs\temp\include /Tc_configtest.c /Fo_configtest.obj

failure.
```

Those two lines make a big difference in helping to diagnose the problem. I couldn't figure out what change caused this to happen. I think [this line](https://github.com/numpy/numpy/blob/master/numpy/distutils/intelccompiler.py#L95) is where the path search is done, but as far as I can tell the relevant code has not changed between version [1.12.1](https://github.com/numpy/numpy/blob/v1.12.1/numpy/distutils/intelccompiler.py) and version [1.13.0rc1](https://github.com/numpy/numpy/blob/v1.13.0rc1/numpy/distutils/intelccompiler.py#L95). The master branch has the same problem as 1.13.0rc1.

Configuration:
* Windows 7
* MS Visual Studio 2015
* Intel Parallel Studio XE 2018 beta
* Anaconda with these packages
```
(temp) c:\numpy-1.12.1>conda list
# packages in environment at C:\Anaconda3\envs\temp:
#
cython                    0.25.2                   py36_0
pip                       9.0.1                    py36_1
python                    3.6.1                         2
setuptools                27.2.0                   py36_1
vs2015_runtime            14.0.25123                    0
wheel                     0.29.0                   py36_0
````

I am running this command to install:

`python setup.py config --compiler=intelemw build_clib --compiler=intelemw build_ext --compiler=intelemw install`

**Comment by charris** [comment]
If the  butler didn't do it, perhaps #7862 did. Are you able to test that?

**Comment by charris** [comment]
@pitrou Can you help?

**Comment by rgommers** [comment]
With current numpy master on linux I get:

    creating build/src.macosx-10.6-intel-3.5/numpy/distutils
    building library "npymath" sources
    Could not locate executable icc
    Could not locate executable ecc
    error: can't compile C/C++ code: unable to find class 'IntelEM64TCCompilerW' in module 'numpy.distutils.intelccompiler'

So either Windows specific (can't test that at the moment) or fixed in the meantime.

**Comment by rgommers** [comment]
I'll close this, wasn't reproducible for me, 6 years old issue in a deprecated component. Thanks all.
