### ISSUE TITLE
scipy.sparse.todense() different behaviour in python 2.7 and python 3.6

### ISSUE THREAD

**Issue by joachimwolff** [numpy/numpy#9120]
As described already at scipy: https://github.com/scipy/scipy/issues/7403
The scipy / numpy versions of Python 2.7 and 3.6 are behaving different if a matrix is printed out. Scipy says, it is probably a numpy issue. For this reason I am posting it here again. It would be nice if you could figure out who is responsible and maybe fix it in a way that the version in Python 2 and Python 3 are behaving the same. 

Thanks a lot!

**Comment by eric-wieser** [comment]
Copying the repro from there:

```python
>> a = np.array([0], dtype='q')
>> b = np.array([0], dtype='l')
>> a.dtype == np.int64
True
>> b.dtype == np.int64
True
>> a
array([0], dtype=int64)
>> b
array([0])
```
