### ISSUE TITLE
Failed to get determinant of a matrix

### ISSUE THREAD

**Issue by amezoure** [numpy/numpy#9127]
```python
import numpy as np

np.linalg.det([[14, 2], [10, 0]]) # equal to -19.999999999999989
np.linalg.det([[14, 2], [10, 0]]).astype(np.int32) # equal to -19

14 * 0 - 10 * 2 # equal to -20, right
```

**Comment by njsmith** [comment]
NumPy is a numerical library focused on floating point calculation, not a symbolic library focused on exact calculation. In particular most of its linear algebra routines work exclusively in floating point. So this behavior is considered correct – when working with floating point there's always the potential for small rounding errors. And then the `astype(np.int32)` does a "forced" truncating cast, following C tradition – use `np.round` if you want more intelligent rounding behavior.

If you need "fancy math" like determinants computed exactly on integers, then sympy might be more useful to you.
