### ISSUE TITLE
dtype of unique_indices for np.unique depends on input data

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#9137]
Consider the following example:

```
In [4]: np.unique([1, 2, 3], return_index=True)[1].dtype
Out[4]: dtype('int64')

In [5]: np.unique([], return_index=True)[1].dtype
Out[5]: dtype('bool')

In [6]: np.__version__
Out[6]: '1.12.1'
```

This is probably innocuous in most cases but it's annoying when writing cython code that calls `np.unique` with `return_index=True`, since the type of the data returned will depend on the inputs.

**Comment by jaimefrio** [comment]
Interestingly, there is an explicit check for empty arrays, and an empty boolean array is deliberately returned for that case for all extra returns, see [here](https://github.com/numpy/numpy/blob/maintenance/1.13.x/numpy/lib/arraysetops.py#L266).

This seems to be a left over behavior from a time long gone when `unique1d` would return the index array as a boolean array, see [here](https://github.com/numpy/numpy/commit/06db31eac5bf957778c5b95f813b4cd0d86ed012).

So I think this is a legit bug, despite the explicitness. The solution is simple: replace all three `np.bool` in my first link with `np.intp`.
