### ISSUE TITLE
MAINT: Innermost if statement condition will never evaluate to true

### ISSUE THREAD

**Issue by k-kapp** [numpy/numpy#9154]
I am not that familiar with the Numpy codebase yet, but as far as I can see, the innermost `if` statement's condition at https://github.com/numpy/numpy/blob/69a423b23492ecf8471efc4e59ab8a93b03d8454/numpy/core/src/multiarray/ctors.c#L1532 will never evaluate to `true`. In fact, since we already know at that stage that the caller specified `writeable` as `false`, there is no need to worry anymore about the `tmp` object not being writeable. That innermost `if` statement and the block that it encloses should therefore be taken out, if I am correct here.

**Comment by eric-wieser** [comment]
Good find. I might be wrong here, but in general I don't think you need to create both an issue and a PR, especially not at the same time.

**Comment by k-kapp** [comment]
Ok, sure. Was thinking of just creating the PR, but could not find anything in the Numpy dev guide.

**Comment by eric-wieser** [comment]
Regarding dead code in general: Presumably there exist static analyzers that would find this type of problem throughout the numpy codebase - it might be a good idea to try using such a thing

**Comment by k-kapp** [comment]
According to [this](http://stackoverflow.com/a/230036/4475902) StackOverflow answer, you can add a -Wunreachable-code compiler option under gcc. Just tried it with a trivial program, but it doesn't seem to work.

**Comment by mhvk** [comment]
fixed by #9155
