### ISSUE TITLE
FFT issue

### ISSUE THREAD

**Issue by nyctalope** [numpy/numpy#9156]
Below is my script to calculate FFT.
Please note that the frequency range is from 0 to L-1, instead of 0 to L/2 conventionally.
The magnitude of the second period is only half of the first. I tried to plot in Matlab while Matlab is correct, but neither numpy nor scipy is correct. Please take a look and correct the bug if it is.

###############################################################

import numpy as np
import scipy as sp
from scipy.fftpack import fft, ifft
from scipy.signal import convolve
from matplotlib.pyplot import *
 
Fs = 1000;            # Sampling frequency                    
T = 1/Fs;             # Sampling period       
L = 1500;             # Length of signal
t = linspace(0,L-1,L)*T;        # Time vector

S = 0.7*sin(2*pi*50*t) + sin(2*pi*120*t);
X = S + 2*randn(size(t));

figure(1)
subplot(2,1,1)
plot(1000*t[1:50],X[1:50])
title('Signal Corrupted with Zero-Mean Random Noise')
xlabel('t (milliseconds)'); ylabel('X(t)');

Y = np.fft.fft(X);

P2 = abs(Y/L);
P1 = P2[0:L/2];
P1[1:-1-1] = 2*P1[1:-1-1];

f = Fs*linspace(0,L-1,L)/L;
subplot(2,1,2)
plot(f,abs(P2)) 
title('Single-Sided Amplitude Spectrum of X(t)')
xlabel('f (Hz)'); ylabel('|P1(f)|');

####################################################################

**Comment by charris** [comment]
This was answered in your scipy issue, so closing here also.
