### ISSUE TITLE
DOC development_setup upstream url notice 

### ISSUE THREAD

**Issue by shitian-ni** [numpy/numpy#9169]
in [development_setup](https://docs.scipy.org/doc/numpy-dev/dev/gitwash/development_setup.html),
the document writes `git remote add upstream git://github.com/numpy/numpy.git`.
The git protocol can be blocked by firewalls as suggested by [git-scm](https://git-scm.com/book/id/v2/Git-on-the-Server-The-Protocols).
I couldn't do `git fetch upstream` before I noticed the firewall problem.
Should we add a notice in the document to let people know the issue?

**Comment by pv** [comment]
Or change git:// to https://

**Comment by shitian-ni** [comment]
Can I make a PR for this issue? 
Though this issue looks small.

**Comment by seberg** [comment]
You are always welcome to create a PR, have a look at our development workflow document for some pointers and hints on commit format, etc.
