### ISSUE TITLE
Error in finding Roots of the Polynominal

### ISSUE THREAD

**Issue by shril** [numpy/numpy#9170]
numpy.roots(p) function is giving error when Cubic (3rd) Degree polynomial is passed having equal roots.
It also gives complex numbers as roots even if the roots are equal real numbers.

```python
# Polynomial : x^3 - 9 x^2 + 27 x -27 = 0
l = [1, -9, 27, -27]
r = np.roots(l)
```

```
Output : [ 3.00001435 +2.48510154e-05j  3.00001435 -2.48510154e-05j  2.99997130 +0.00000000e+00j]
```
But the correct output is [3, 3, 3]. This error happens everytime when all the roots are equal.
The use of **R. A. Horn & C. R. Johnson, Matrix Analysis** needs to be re-evaluated.
[Link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.roots.html)

CC: @devojoyti

**Comment by pv** [comment]
Perturbation of the polynomial coefficients by floating point epsilon 
eps produces changes of magnitude (eps)^(1/m) in the roots. The issue is 
inherent in the power basis representation of the polynomial in floating 
point numbers.

**Comment by bashtage** [comment]
Looks right:

```python
>>> np.linalg.eigvals(np.r_[[[9,-27,27]],np.eye(2,3)])
Out[14]: 
array([ 3.00001435 +2.48510154e-05j,  3.00001435 -2.48510154e-05j,
        2.99997130 +0.00000000e+00j])

>>> 3.0 - np.linalg.eigvals(np.r_[[[9,-27,27]],np.eye(2,3)])
Out[15]: 
array([ -1.43475485e-05 -2.48510154e-05j,
        -1.43475485e-05 +2.48510154e-05j,   2.86950969e-05 +0.00000000e+00j])
```

**Comment by charris** [comment]
Note that the polynomial is very flat near 3, so that polynomial value is closer to zero than you might expect.
```
In [9]: from numpy.polynomial import Polynomial as P

In [10]: p = P.fromroots([3,3,3])

In [11]: p(p.roots())
Out[11]: 
array([ -2.84217094e-14 +0.00000000e+00j,
        -2.84217094e-14 +2.15942329e-19j,  -2.84217094e-14 -2.15942329e-19j])
```
Although 3 is even better
```
In [12]: p(3)
Out[12]: 0.0
```

Might be worth looking at some of the other polynomial root finders for comparison.

**Comment by charris** [comment]
Note that the selection of domain also makes a difference for the numerics.
```
In [17]: p = P.fromroots([3,3,3], domain=(2,4))

In [18]: p.roots()
Out[18]: array([ 3.,  3.,  3.])
```

**Comment by zztalker** [comment]
There is also the problem with roots, which partially equal. 

```
import numpy as np
l = [-1,1,5,3]
np.roots(l)
array([ 3. +0.00000000e+00j, -1. +1.20320638e-08j, -1. -1.20320638e-08j])
```

But roots is 3 and -1.

**Comment by charris** [comment]
There isn't much to be done here, I doubt other root finding methods would help much because the general case is always going to involve iterative approximation. One could improve things with an algebraic solutions in special cases if the polynomial be fully factored over the base field, but that is not normally the case in practice.
