### ISSUE TITLE
np.tile fails confusingly and inconsistently with non-interger repetitions.

### ISSUE THREAD

**Issue by DFoIUtN02r** [numpy/numpy#9171]
```
import numpy as np
np.__version__
Out[2]: '1.12.1'
```
The following code returns, but with a warning:
```
Input: np.tile([23,24,25,26], reps=2.2)
```
```
lib\site-packages\numpy\lib\shape_base.py:873: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return c.reshape(shape_out)
Output: array([23, 24, 25, 26, 23, 24, 25, 26])
```
But this code throws an exception:
```
Input: np.tile([23,24,25,26], reps=2.3)
```
```

  File lib\site-packages\numpy\lib\shape_base.py", line 873, in tile
    return c.reshape(shape_out)

ValueError: total size of new array must be unchanged
```

Ideally the function should support fractional repetitions. If not, it should check for non-integer repetitions and show a more helpful error message.

**Comment by seberg** [comment]
It will give an error in the future, that is why there is a VisibleDeprecationWarning, which explicitly says that. Once we have that for a while, you could think about non-integer repetitions, but I doubt its a good idea.

**Comment by seberg** [comment]
(The future is probably already here, the newest numpy version will probably simply error out)

**Comment by eric-wieser** [comment]
Yeah, this errors already on 1.12

**Comment by eric-wieser** [comment]
When I try this on 1.12.1 and python 3,, I get an error for both cases.

**Comment by seberg** [comment]
Well, error is now `TypeError: 'float' object cannot be interpreted as an index`, which could be nicer maybe (general problem though). My guess is @DFoIUtN02r did not actually use numpy 1.12, but 1.11?

**Comment by eric-wieser** [comment]
I haven't tried it on python 2.7 - perhaps something weird is happening with integer division there?
