### ISSUE TITLE
ndarray.tofile fails with a file handle from gzip.open

### ISSUE THREAD

**Issue by dariomel** [numpy/numpy#9179]
the behavior below looks like a bug to me.
Specifically, I would expect ndarray.tofile to work with any file handle open for sequential output. Instead ndarray.tofile fails with a file handle obtained from gzip.open.

python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy as np
>>> import gzip as gz
>>> np.array([1,2]).tofile(open("temp.txt","wb"))
>>> np.array([1,2]).tofile(gz.open("temp.txt.gz","wb"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: first argument must be an open file
>>>

**Comment by charris** [comment]
Numpy version?

**Comment by dariomel** [comment]
>>> import numpy
>>> numpy.version.version
'1.11.1'



Dario



________________________________

**Comment by charris** [comment]
Works for me in master
```
In [1]: import gzip

In [2]: np.array([1,2]).tofile(gzip.open("temp.txt.gz","wb"))

In [3]: 
```

**Comment by dariomel** [comment]
glad to hear that.
I did conda update numpy on both Ubuntu 14.04 and Windows 7.
Now I have numpy 1.11.3 and 1.12.1, respectively.
I still get the same error on both platforms.

**Comment by juliantaylor** [comment]
it doesn't work in python2, I think this is fixed on master

**Comment by charris** [comment]
Yep, it is broken in 1.12.1, works in 1.13.0rc2.  I'm going to close this, reopen if you still have problems after 1.13.0 is released.

**Comment by charris** [comment]
Yep, it is broken in 1.12.1, works in 1.13.0rc2.  I'm going to close this, reopen if you still have problems after 1.13.0 is released.
