### ISSUE TITLE
memmap: Invalid offset in buffer format string generation

### ISSUE THREAD

**Issue by crackwitz** [numpy/numpy#9184]
So I have constructed an unusual dtype with overlapping fields and no strict order to the offsets.

```python
#!/usr/bin/env python3
import os
import numpy as np

mydtype = np.dtype({
	'names': 'x y xy'.split(),
	'formats': 'f4 f4 2f4'.split(),
	'offsets': [0, 4, 0]
})

mapfile = "numpy-union-example.dat"
if os.path.exists(mapfile):
	os.unlink(mapfile)

mapped = np.memmap(mapfile, shape=(1,), dtype=mydtype, mode='w+')

mapped[0]['xy'] = np.nan

record = np.empty((), dtype=mydtype)
record['xy'] = np.nan

mapped[0] = record # THIS is where it crashes
```
when I execute that, I get this error:

    Traceback (most recent call last):
      File "numpy-union-example.py", line 26, in <module>
        mapped[0] = record # THIS is where it crashes
    RuntimeError: This should never happen: Invalid offset in buffer format string generation. Please report a bug to the Numpy developers.

This is Win7 x64, CPython 3.6.1, numpy 1.12.1.

Got any ideas what might be happening?

**Comment by eric-wieser** [comment]
Looks to me like we're trying to roundtrip through the `memoryview` format when dealing with `void` scalars, which is evidently a bad idea. Can you confirm that the first write actually worked?

**Comment by crackwitz** [comment]
the first write (direct assignment involving broadcast) succeeds without error, and the value (any value) also appears in the mapped file.

**Comment by mattip** [comment]
Cannot reproduce on HEAD. @crackwitz can you verify this still occurs?

**Comment by crackwitz** [comment]
I just tried that snippet I posted in 2017. Now I'm running CPython 3.6.5, numpy 1.16.1, and the code does not raise any exceptions.

Appears resolved to me.
