### ISSUE TITLE
BUG: comparisons between scalars and arrays with different precision

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#9194]
We've had numerous issues about float32 precision bugs, but the inconsistency in comparisons found out in https://github.com/numpy/numpy/pull/9189#issuecomment-305271771 seems a bit much to bear: comparing 1 and something that is slightly larger but equal to 1 at float32 precision is admittedly not that well-defined, but it does seem simplest to just convert the float32 to float64 and do the comparison there. And this is done in some cases, but not all. It seems particularly troubling that array scalars and arrays with a shape are treated differently...
```python
# not good: float32 array with float64 array scalar (or regular scalar or python scalar)
np.array([1.], dtype=np.float32)>=np.array(1.00000001, dtype=np.float64)
# array([ True], dtype=bool)

# OK float32 array with float64 array
np.array([1.], dtype=np.float32)>=np.array([1.00000001], dtype=np.float64)
# array([False], dtype=bool)

# also OK: (array) scalar with (array) scalar
np.array(1., dtype=np.float32)>=np.array(1.00000001, dtype=np.float64)
# False
```

**Comment by toobaz** [comment]
Just to understand: is the following, concerning equality rather than weak inequality, the same or a different bug (assuming it is indeed a bug)?

```python
In [2]: a = np.array([1.2], dtype='float64')

In [3]: a.astype('float32') == a[0]
Out[3]: array([ True], dtype=bool)

In [4]: a.astype('float32')[0] == a[0]
Out[4]: False

```

**Comment by seberg** [comment]
It is the same thing, though maybe a bit more surprising, the float32 scalars won't cause upcast to float64 if the other is an array. And:
```
n [2]: a.astype(np.float32).astype(np.float64)
Out[2]: array([ 1.20000005])
```

**Comment by mhvk** [comment]
Closing this in favour of #10322, since there is a bit more focussed discussion there.
