### ISSUE TITLE
int(numpy.int_(sys.maxint)) should not output a long

### ISSUE THREAD

**Issue by mehrdadn** [numpy/numpy#9221]
This appears to be a bug stemming from [here](/numpy/numpy/blob/e332ba4314bf874b1c7d17d82a2f1bf1766ece69/numpy/core/src/umath/scalarmath.c.src#L1429) and occurs until at least version 1.12.1 (the latest I tried):

	>>> import sys, numpy
	>>> a = numpy.int_(sys.maxint)
	>>> int(a).__class__
	<type 'long'>
	>>> int(int(a)).__class__
	<type 'int'>

Output should give `int`, not `long`.

**Comment by pv** [comment]
Why should it give an int?
```
Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 >>> type(int(2**65))
<type 'long'>
 >>> type(int(2**62))
<type 'int'>
```

**Comment by pv** [comment]
Ok i see, the result apparently fits in int range.

**Comment by WarrenWeckesser** [comment]
This is a Python 2 issue, so no longer relevant; closing.
