### ISSUE TITLE
Histogramdd returns negative values after bins were not checked for monotonic increase

### ISSUE THREAD

**Issue by HagaiHargil** [numpy/numpy#9222]
A call to `np.histogram(2, bins=[1, 3, 1])` will raise a `ValueError: bins must increase monotonically.` exception. However, arrays generated with a datatype of `uint64` or `np.uint64` will *not* be checked (correctly, at least) for monotonicity and will execute without a problem, generating a histogram with a negative value:

```
hist, edges = np.histogram(2, bins=np.array([1, 3, 1], dtype='uint64'))
# hist == np.array([1, -1]) 
```

The two problems here are obvious:

1. `numpy` doesn't check the monotonicity of the bins, or at least does so incorrectly.
2. A histogram with a negative value is returned. 

I'm using `numpy` version `1.12.1` with Python 3.6.1 on Windows 64 bit.
Thanks!

**Comment by b-carter** [comment]
It seems like the unsigned arithmetic operation _should_ be returning an unsigned result, so the problem here seems to be in the monotonicity check using `np.diff`.

I guess one solution would be to just convert anything unsigned to a signed type, but this might cause issues for very large unsigned integers that can't fit into a signed integer.

Maybe a better solution (I think also more efficient?) would be just doing `np.all(bins[1:] > bins[:-1])` as the check.

If this looks good, I'll write a test and submit a PR.

**Comment by b-carter** [comment]
Just checking back on this. Does that seem like an acceptable solution to everyone? If so, I can create a PR. Thanks!

**Comment by HagaiHargil** [comment]
I'd be happy if this issue could be somehow resolved, the proposed solution seems pretty straight-forward IMHO.
I'd also like to point out that this bug still exists in version 1.13.

Thanks.

**Comment by seberg** [comment]
@b-carter or @HagaiHargil, we always apreciate PRs (no need to ask if it seems acceptable ;), though it does seem so, we can decide on that later). Please remember that we need tests to merge anything new, there is also a development workflow document, one thing we particularly like is our commit messages: https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message ;)

But these are all details we can hash out once the PR is there, so please just go ahead!

**Comment by eric-wieser** [comment]
This is fixed for `np.histogram` in #9294, but is still a problem for `histogramdd`

**Comment by eric-wieser** [comment]
Actually I think this is fixed for `histogramdd` too

```python
>>> hist, edges = np.histogramdd([[2]], bins=[np.array([1, 3, 1], dtype='uint64')])
ValueError: Found bin edge of size <= 0. Did you specify `bins` withnon-monotonic sequence?
```

**Comment by HagaiHargil** [comment]
After revisiting this issue, I think something is still bugged:

```python
hist, b = np.histogram(np.array([1, 2, 3]), bins=np.array([1, 1, 2, 4]))
# hist: array([0, 1, 2])

hist, b = np.histogramdd(np.array([1, 2, 3]), bins=(np.array([1, 1, 2, 4]), ))
# ValueError: Found bin edge of size <= 0. Did you specify `bins` withnon-monotonic sequence?
```

Besides the typo in `histogramdd`'s exception message, I think that `histogram`'s behavior is the correct one. I see no problem with identical bin edges, as long as they're not decreasing. Moreover, in my application allowing two bins to be identical will simplify a few calculations.

This is on version 1.14.3.

**Comment by eric-wieser** [comment]
On 1.15.0, the error changes to:
```
>>> hist, b = np.histogramdd(np.array([1, 2, 3]), bins=(np.array([1, 1, 2, 4]), ))
ValueError: `bins[0]` must be strictly increasing, when an array
```

You're right that `histogram` behaves differently here.

Things are this way because of the design flaw that is #10864.

**Comment by HagaiHargil** [comment]
Nice, will a pull request along the lines of the previous one that dealt with `histogram` (#9294) make it to 1.15?

**Comment by eric-wieser** [comment]
@HagaiHargil: As far as I can tell, that is issue is about integer overflow, which is a separate problem. Is that one you've encountered with `histogramdd`? Can you give an example?

Histograms have received some significant refactoring in 1.15, and histogramdd has a [minor new feature](https://github.com/numpy/numpy/blob/master/doc/release/1.15.0-notes.rst#histogramdd-allows-explicit-ranges-to-be-given-in-a-subset-of-axes).

Unfortunately further changes cause us to run against compatibility breaks, as discussed in the mailing list post - unless there's consensus that those breaks are ok, we're stuck with the current behavior.

**Comment by HagaiHargil** [comment]
Indeed, this issue is about the integer overflow issue that was fixed in #9294. I raised my "new issue" here since it seemed close enough and I wasn't sure what the exact underlying cause was.

I'm happy to see these improvements in the histogram function. If you believe that the behavior I described above is not a bug then I guess I'll have to find a workaround.

Thanks!

**Comment by eric-wieser** [comment]
Hey look, a float-integer overflow bug:
```
def test_large_integers():
    big = 2**60  # Too large to represent with a full precision float

    x = np.array([0], np.int64)
    x_edges = np.array([-1, +1], np.int64)
    y = big + x
    y_edges = big + x_edges

    hist, edges = histogramdd((x, y), bins=(x_edges, y_edges))
```

gives, on 1.13.3:
```
ValueError: Found bin edge of size <= 0. Did you specify `bins` withnon-monotonic sequence?
```

**Comment by mattip** [comment]
#11023 has been merged, this no longer raises on master
