### ISSUE TITLE
argsort returns incorrect results

### ISSUE THREAD

**Issue by gcv** [numpy/numpy#9223]
I've reproduced this behavior on macOS and Linux with numpy 1.12.1:

```
>>> import numpy as np
>>> np.argsort(np.array([115, 70, 29]))
array([2, 1, 0])
>>> np.argsort(np.array([115, 70, 29, 0, 0]))
array([3, 4, 2, 1, 0])
>>> np.argsort(np.array([115, 70, 29, 0, 0]), axis=-1, kind='mergesort')
array([3, 4, 2, 1, 0])
>>> np.argsort(np.array([115, 70, 29, 0, 0]), axis=-1, kind='heapsort')
array([4, 3, 2, 1, 0])
>>> np.argsort(np.array([0, 0, 115, 70, 29, 0, 0]), axis=-1, kind='heapsort')
array([5, 0, 1, 6, 4, 3, 2])
>>> np.argsort(np.array([0, 0, 115, 70, 29, 0, 0]), axis=-1, kind='mergesort')
array([0, 1, 5, 6, 4, 3, 2])
```

[TFM states](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html): "`numpy.argsort`: Returns the indices that would sort an array." I expect the indices corresponding to 29, 70, and 115 to be the highest three in the result and appear in that order. They do not do so predictably.

**Comment by njsmith** [comment]
> I expect the indices corresponding to 29, 70, and 115 to be the highest three in the result and appear in that order. They do not do so predictably.

It looks like they do to me in your examples – maybe I'm just missing it. Can you point to a specific one where they don't?

Note that a quick way to check `argsort` is to do `a[np.argsort(a)]`, which should give you an array in sorted order.

**Comment by gcv** [comment]
You're right. I misinterpreted the behavior of `argsort`. I took its return value to contain the _sorted order_ of the indices of the input. It actually contains the indices themselves.

**Comment by eric-wieser** [comment]
Duplicate of #8757
