### ISSUE TITLE
numpy.arange issue

### ISSUE THREAD

**Issue by conico486** [numpy/numpy#9224]
Operating system: Windows 10
python version: 3.5.3
numpy version: 1.12.1

Issue information:
when I input numpy.arange(0,5), the output was normal for an array excluding the terminal number 5, but if I input numpy.arange(0.442,0.524,0.001), the outcome turned out to be abnormal including the terminal number 0.524.

**Comment by jaimefrio** [comment]
Thanks for the detailed report, but this is expected, unavoidable behavior due to floating point roundoff. See the comment on the `arange` docs about using `linspace` instead for a more consistent result:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
