### ISSUE TITLE
bumpy test fails with python3.7 - PyTraceMalloc_Untrack

### ISSUE THREAD

**Issue by dwintergruen** [numpy/numpy#9227]
Trying to build numpy (master) with python3.7 (ubuntu 16.02, python from git)
Compiling seems to work, but the tests give

ImportError:  FOO/numpy/build/testenv/lib/python3.7/site-packages/numpy/core/multiarray.cpython-37dm-x86_64-linux-gnu.so: undefined symbol: PyTraceMalloc_Untrack

Who can help?

**Comment by juliantaylor** [comment]
it will work as soon as https://github.com/python/cpython/pull/1236 is merged
until then you can change the required version number in the defines in alloc.c

**Comment by njsmith** [comment]
Well, I guess we're learning something here... Someone else just ran into this and filed a bug upstream with python: http://bugs.python.org/issue30623

1.13 came out 3 days ago, and we've already had 2 reports, one misdirected. To me that means we need to fix this. Apparently people actually test python master these days. (At least @brettcannon will be pleased :-))

Untangling ourselves is a bit complicated though. The worst would be if we scramble to release a 1.13.1 that switches to unconditionally using the underscore-prefixed version, and simultaneously cpython scrambles to merge that PR to drop the underscore, and then we're back where we started.

I guess the most robust option would be to add a build time check for the symbol. But if that's annoying or will delay releasing a bug fix, then we should switch back to the underscore version unconditionally. And in any case I'll nudge Victor about making that PR provide a backcompat `#define` and perhaps getting merged sooner than later.

**Comment by charris** [comment]
I note that 1.13 does not officially support Python 3.7, much less its development version. But I suppose it won't hurt to check if the function is present. I don't think we have checked the Python C-API before...

**Comment by juliantaylor** [comment]
I didn't expect cpython to be so slow in merging, pinging them should be enough.

**Comment by tacaswell** [comment]
Also seeing this in the Matplotlib tests (and finally getting around to tracking it down...)

**Comment by charris** [comment]
> pinging them should be enough.

Guess again ;)

**Comment by charris** [comment]
Removing the 1.13.1 milestone. If there is still a problem when Python 3.7 is released we will deal with it then.

**Comment by tacaswell** [comment]
https://github.com/python/cpython/pull/1236 has been merged, I think this and the cpython bug can be closed?

matplotlib nightly is working again on travis :)

**Comment by charris** [comment]
@tacaswell Thanks for the update.
