### ISSUE TITLE
numpy.array_equal() returns False on apparently identical arrays with NaN values

### ISSUE THREAD

**Issue by cwfinn** [numpy/numpy#9229]
OS: macOS Sierra (10.12.5)
Python version: 2.7.12
numpy version: 1.13.0

Passing `np.array_equal()` two apparently identical arrays containing NaN values returns `False`. See the following example replicating this issue:

```python
>>> a = np.array([1, 2, np.nan])
>>> np.array_equal(a, a)
False
```

It would make sense to me if this returned `True`, though I understand that the following comparison returns `False` by definition:

```python
>>> np.nan == np.nan
False
```

I presume this is related to [changes in `np.equal` and `np.not_equal`](https://github.com/numpy/numpy/blob/master/doc/release/1.13.0-notes.rst#npequal-npnot_equal-for-object-arrays-ignores-object-identity). If this is the desired behaviour, I wonder if it might be more helpful for the element-wise comparison to raise an exception on encountering NaN comparisons, as this has caused unit test failures for me and took a while to track down.

**Comment by charris** [comment]
Might be good to add an `equal_nan` argument.
```
In [3]: np.allclose(a, a, equal_nan=True)
Out[3]: True
```

**Comment by charris** [comment]
Note this is not a regression, NumPy 1.12.1 returns the same result.

**Comment by cwfinn** [comment]
Though it does return `True` in the following instance with version 1.12.1:

```python
>>> a = np.array([1, 2, np.nan], dtype=object)
>>> np.array_equal(a, a)
True
```

**Comment by charris** [comment]
Yep, that was a NumPy bug that has been fixed. The comparison was falling back to comparing object addresses rather than values. That behavior was deprecated in 2014.

**Comment by cwfinn** [comment]
@charris I notice that [`numpy.testing.assert_array_equal`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_array_equal.html#numpy-testing-assert-array-equal) should compare NaNs as numbers unlike elsewhere in numpy, which makes sense to me. I verify this with the following test:

```python
>>> import numpy.testing as npt
>>> import numpy as np
>>> a = np.array([1, 2, np.nan])
>>> npt.assert_array_equal(a, a)
```

However, this does not work with arrays that have dtype object:

```python
>>> b = np.array([1, 2, 'a', np.nan], dtype=object)
>>> npt.assert_array_equal(b, b)
```
```
AssertionError: 
Arrays are not equal

(mismatch 25.0%)
 x: array([1, 2, 'a', nan], dtype=object)
 y: array([1, 2, 'a', nan], dtype=object)
```

Is this the desired behaviour? I thought that changing my tests to use `npt.assert_array_equal` would solve the issue I was experiencing, but it does not for this reason. The only workaround in my case is to cast the array as dtype str.

**Comment by eric-wieser** [comment]
1.12.1 does not throw an `AssertionError` in that case, so perhaps that is a regression?

**Comment by normanius** [comment]
As @charris commented, might be good to add an `equal_nan` argument, just as in [`allclose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html). 

A particular reason why no one followed up on this suggestion?

**Comment by atvaccaro** [comment]
The [docs for this function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_array_equal.html) indicate that it _should not_ be throwing an exception (emphasis mine).

>Given two array_like objects, check that the shape is equal and all elements of these objects are equal. An exception is raised at shape mismatch or conflicting values. **In contrast to the standard usage in numpy, NaNs are compared like numbers, no assertion is raised if both objects have NaNs in the same positions.**

**Comment by aloosley** [comment]
I have this same error using np.array_equal with numpy version 1.18.2. 

It would be great if there was a simple solution.  In the meantime, the workaround is:
```
np.array_equal(np.nan_to_num(a), np.nan_to_num(b))
```
where `a` and `b` are my arrays that are otherwise equal up to nan values.

**Comment by rossbar** [comment]
> As @charris commented, it might be good to add an equal_nan argument, just as in allclose.

> A particular reason why no one followed up on this suggestion?

The `equal_nan` kwarg has been added in #16128, which should be sufficient to close the issue. If there is still discussion to be had about `np.testing.assert_array_equal`, feel free to re-open or, better yet, open a new issue that links to the relevant comments here.
