### ISSUE TITLE
Zscore normalization with NumPy doesn't agree with R and Pandas

### ISSUE THREAD

**Issue by jolespin** [numpy/numpy#9230]
The NumPy way is slightly different than Pandas.  I thought it was an error in Pandas but when I saw that R had the same values I started to be skeptical of the implementation.  Do you know what could be causing this? 

Here's the test data: 
```
           orf_0     orf_1       orf_2
1054.1  3.606670  6.011117   58.608393
1054.2  9.199679  5.826464  117.295913
1057.1  5.830196  9.231144  123.891674
1057.2  2.658734  2.658734   99.702514
1059.1  4.492885  3.369664   11.232212
```
Here's Numpy and Pandas:
![image](https://user-images.githubusercontent.com/9061708/26946684-fc7860b0-4c44-11e7-9c42-24af498eb43b.png)

R

```
>  df_test  = read.table("~/test.tsv", sep="\t", row.names=1, header = TRUE, check.names=FALSE)
> scale(df_test, center=TRUE, scale=TRUE)
            orf_0      orf_1      orf_2
1054.1 -0.6097186  0.2283017 -0.4998640
1054.2  1.5890202  0.1570541  0.7464650
1057.1  0.2644000  1.4707333  0.8865372
1057.2 -0.9823740 -1.0651989  0.3728394
1059.1 -0.2613276 -0.7908902 -1.5059776
```
Versions
```
np.__version__, pd.__version__
('1.12.1', '0.20.1')
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"

**Comment by rgommers** [comment]
look at the ``ddof`` parameter to ``np.std``, it will have a default different from R. 

You only use the ``mean`` and ``std`` functions here, and both are certainly correct, hence closing this issue.
