### ISSUE TITLE
No release notes?

### ISSUE THREAD

**Issue by thanatos** [numpy/numpy#9231]
We're trying to trace some failure in pandas where subtracting two series containing timestamps fails. It seems to be failing only on instances with `numpy>=1.13`; whereas there are [1.12.0 release notes](https://docs.scipy.org/doc/numpy-1.12.0/release.html), there are [no release notes for 1.13.0](https://docs.scipy.org/doc/numpy-1.13.0/release.html); we were trying to find these to see if there was anything relevant sounding that might help us determine the cause. (and rule in/out a regression in numpy)

**Comment by MSeifert04** [comment]
https://github.com/numpy/numpy/blob/master/doc/release/1.13.0-notes.rst?

**Comment by eric-wieser** [comment]
The issue that you're actually observing is that there is no html documentation on scipy.org for 1.13. @rgommers?

**Comment by rgommers** [comment]
Started on those last night. There were some formatting issues with the pdf, so I didn't finish yet. Tonight or tomorrow they'll be up - I'll close this issue when that's done.

**Comment by thanatos** [comment]
Thanks! In the meantime, the link @MSeifert04 posted definitely suffices. I'm not sure why I didn't think to actually check the repository.

**Comment by rgommers** [comment]
May be a few days before this is fixed - I'll send a PR with doc build fixes soon, but permissions for uploading are NOK after a server move: https://github.com/scipy/scipy.org/issues/213

**Comment by rgommers** [comment]
1.13.0 docs are up at https://docs.scipy.org/doc/numpy/reference/index.html

Still need to modify the index page at docs.scipy.org

**Comment by rgommers** [comment]
docs.scipy.org front page updated as well, closing.
