### ISSUE TITLE
Arithmetic with flat iterator of large broadcasted array gives ValueError

### ISSUE THREAD

**Issue by mtrachy** [numpy/numpy#9232]
```python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.13.0'
>>> np.version.git_revision
'e94ed84010c60961f82860d146681d3fd607de4e'
>>> np.asarray(np.broadcast_to(np.zeros(1), 32768).flat) * 0.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: output array is read-only
```

Environment:
Centos 6.9 (kernel 2.6.32-696.3.1)
Python 3.5.2 from Anaconda
Numpy 1.13.0

It only seems to happen if the input and output `dtype` match and if the output array is `2**18` bytes or more.

```python
>>> np.asarray(np.broadcast_to(np.zeros(1, np.uint8), 2**18-1).flat) * np.uint8(0)
array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)
>>> np.asarray(np.broadcast_to(np.zeros(1, np.uint8), 2**18).flat) * np.uint8(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: output array is read-only
>>> np.asarray(np.broadcast_to(np.zeros(1, np.uint8), 2**18).flat) * np.float64(0.0)
array([ 0.,  0.,  0., ...,  0.,  0.,  0.])
>>> np.asarray(np.broadcast_to(np.zeros(1, np.uint8), 2**18).flat) * np.uint32(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: output array is read-only
>>> np.asarray(np.broadcast_to(np.zeros(1, np.uint8), 2**18).flat) * np.uint64(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: output array is read-only
```

**Comment by eric-wieser** [comment]
@juliantaylor is this temporary elision misfiring?

**Comment by juliantaylor** [comment]
it is, a check for writeable temporaries is missing.

**Comment by charris** [comment]
@eric-wieser Good catch,

**Comment by juliantaylor** [comment]
hmm we could just ignore the readonly property of the temporary, it doesn't really make sense to preserve it as it disappears anyway.
Though it is probably a somewhat marginal optimization.

**Comment by charris** [comment]
Ignoring the readonly flag seems like it could lead to subtle problems. Is there really a guarantee that the temporary will go away and not end up holding the result?  Hmm, and if it does, is it thread safe?

What might be interesting is to see how we ended up with a readonly temporary. Sounds like it might be something like the "temporary" readonly flag on diagonal views.

**Comment by charris** [comment]
The problem is
```
In [4]: np.broadcast_to(np.zeros(1), 32768).flags
Out[4]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False
```
Also
>__Returns__
   broadcast : array
    A readonly view on the original array with the given shape. It is
    typically not contiguous. Furthermore, more than one element of a
    broadcasted array may refer to a single memory location.

I think the problem here is that `asarray` keeps the `WRITEABLE` flag even though it makes a new array. It's not clear to me how it gets the flag from the iterator.

**Comment by charris** [comment]
More

```
In [14]: array(np.broadcast_to(np.zeros(1), 32768).flat).flags
Out[14]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [15]: array(np.broadcast_to(np.zeros(1), 32768).flat, copy=False).flags
Out[15]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False
```
The code should really be calling `array` rather than `asarray`, but even so, I wonder if `asarray` should keep the `WRITEABLE` flag when it makes a copy?

**Comment by charris** [comment]
And the flag comes from the `__array__` method of the iterator.
```
In [21]: np.broadcast_to(np.zeros(1), 32768).flat.__array__().flags
Out[21]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False
```

**Comment by charris** [comment]
I confess I don't see how the reference count ended up at one in the failing example.

**Comment by charris** [comment]
So I think this is a bug in `asarray`. Here is a slightly different version
```
In [9]: a = ones(10)[::2]

In [10]: a.flat.__array__().flags
Out[10]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : True

In [11]: asarray(a.flat.__array__()).flags
Out[11]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False
```
Note that `it.__array__` returns a contiguous array with `UPDATEIFCOPY` because the a is not contiguous. The `asarray` makes a copy but sets the `WRITEABLE` flag to false, which I think it should not do.

**Comment by charris** [comment]
And here we see that the error is erratic for some reason.
```
In [31]: a = ones(2**20)[::2]

In [32]: asarray(a.flat) + 1.
Out[32]: array([ 2.,  2.,  2., ...,  2.,  2.,  2.])

In [33]: asarray(a.flat) + 1.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-c4bc02077c58> in <module>()
----> 1 asarray(a.flat) + 1.

ValueError: output array is read-only
```
Not sure what is going on there.

**Comment by charris** [comment]
Curious
```
In [47]: a = ones(2**20)[::2]

In [48]: a.flat.__array__().flags
Out[48]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : True

In [49]: a.flat.__array__().flags
Out[49]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False
```

**Comment by charris** [comment]
So I think in this case that the result of `asarray` is legitimately unwriteable as `np.broadcast_to(np.zeros(1), 32768)` is, and hence the new array returned by `np.broadcast_to(np.zeros(1), 32768).flat.__array__()`. Note that the later is a new, contiguous copy of `np.broadcast_to(np.zeros(1), 32768)`, which is not contiguous. It might be argued that in this case, since the original in not writeable and we have made a copy, that the copy could be made writeable. The relevant line is https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/iterators.c#L1117,

@julian as a separate issue, it is not clear to me if we should treat UPDATEIFCOPY arrays as temporaries as the base arrays may not be temporary.
