### ISSUE TITLE
`show_config()` has no docstring and is not in the online docs.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#9258]
The subject says it all, but in case you missed it:  the function `numpy.show_config()` (an alias for `numpy.__config__.show()`) doesn't have a docstring, and it does not appear in the [online docs](https://docs.scipy.org/doc/numpy/genindex.html#S).

A docstring that explains the information printed by `show_config()` would be helpful.

**Comment by siryog90** [comment]
@rgommers @WarrenWeckesser 
Hello,
A regular numpy user (numerical analysis), this is my first time looking into the source code and trying to become a contributor, so any comments on improvement or accepted standards would be very welcome.

After looking through `distutils.system_info` and `misc_util` modules, I came up with this
`def show():
    """
    Print information about various resources (libraries, library directories,
    include directories, etc.) in the system. Information is grouped according
    to classes ('blas_opt_info' below) that specify relevant resources, and 
    it is formatted to be compatible with distutils.setup keyword arguments.

    Examples
    --------
    >>> import numpy as np
    >>> np.__config__.show()
    blas_opt_info:
        language = c
        define_macros = [('HAVE_CBLAS', None)]
        libraries = ['openblas', 'openblas']
        library_dirs = ['/usr/local/lib']

    Classes specifying the information to be printed are defined 
    in the `numpy.distuitls.system_info` module. 

    Information may include:
        language: language used to write the libraries (mostly C or f77)
        libraries: names of libraries found in the system     
        library_dirs: directories containing the libraries
        include_dirs: directories containing library header files
        src_dirs: directories containing library source files
        define_macros: preprocessor macros used by distutils.setup
    """

    for name,info_dict in globals().items():
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print(name + ":")
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in info_dict.items():
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print("    %s = %s" % (k,v))
    ''')

    f.close()
    return target`

I have a gut feeling that it is too vague, or maybe even too verbose. Any suggestions for improvement?

**Comment by rgommers** [comment]
Thanks for working on this @siryog90. Looks like a good start. A couple of comments:

- ``in the system.`` --> add something like "on which ``numpy`` was built"
- Formatting: docstrings should start with a single summary line, then a blank line, then a description. Format is documented in detail in https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt
- Last 6 lines: make this a list, otherwise the formatting will be messed up.
- The last 10 lines are not part of ``Examples`` but of ``Notes`` (which goes above Examples).
- A ``See Also`` section with a link to ``get_include`` would be nice. There may be another function of interest, can't think of any right now though.
- There was a mailing list discussion a while back about ``show_config`` and what it was lacking - would be nice to dig that up. I can look for it later if you can't find it.

**Comment by siryog90** [comment]
@rgommers 
For the 5th point, do you mean a Sphinx link, or is there a Python docstring standard for links?

**Comment by rgommers** [comment]
Just this will create a link:

    See Also
    --------
    get_include

and optional, you can add a one-line description of how it's related:

    See Also
    --------
    get_include : some text here

**Comment by rgommers** [comment]
Adding ``numpy.distutils.system_info.get_info``: not quite sure about that one. It doesn't have a docstring at the moment. If it did and it clearly explained the purpose, then indeed would be nice.

**Comment by rgommers** [comment]
That whole docstring looks pretty close to ready. I suggest you pop it into a PR!

**Comment by siryog90** [comment]
@rgommers 
Done. Thanks for the info.

**Comment by orbit-stabilizer** [comment]
Should this issue be closed?

**Comment by eric-wieser** [comment]
@orbit-stabilizer: No, the issue at #9312 needs a fixup

**Comment by SahanaJavgal** [comment]
Hello, Im new to Open Source and I am Applying for Outreachy. I would like to work on this Issue. Could you please assign it to me

**Comment by mattip** [comment]
@SahanaJavgal work on this has already begun in #9312. No need to duplicate effort
