### ISSUE TITLE
f2py - consecutive execution on same inputs

### ISSUE THREAD

**Issue by mcenerney1** [numpy/numpy#9273]
I have an f2py interface to some old fortran code. If I run with a loop on the same inputs I get a different answer than if I run it once. This is quite disturbing.  I've tried a number of things that don't work such as clearing internal arrays in the fortran, reloading, "forcing" garbage collection, etc.  Has anyone seen this behavior? Any ideas would be appreciated!!!

**Comment by charris** [comment]
I suspect a code error here, but it is hard to pinpoint without a good example.

**Comment by mcenerney1** [comment]
In the pyf file?

**Comment by mcenerney1** [comment]
After further investigation I found that there some deliberate changes to certain parameters in the second execution.  So this is not an issue. The lesson relearned is you need to know what the fortran is doing!
