### ISSUE TITLE
np.insert() for -1 index does not work as expected

### ISSUE THREAD

**Issue by jaredvacanti** [numpy/numpy#9274]
For example: 

`>>> np.insert(np.array([1,2,3,4,5]), [0,-1], 0)`

would expect to return
`>>> array([0, 1, 2, 3, 4, 5, 0])`

but instead returns
`>>> array([0, 1, 2, 3, 4, 0, 5])`

**Comment by jaredvacanti** [comment]
After some more discussion IRC it looks like this is desired behavior. The index location is what position to insert BEFORE. 

It does feel confusing with traditional python syntax of identifying the index location to insert - so `-1` would insert at the last position of the array. I'll defer to the powers that be.

**Comment by seberg** [comment]
It is a point, considering that it is legal to give a one large index then the array size for that reason. It is not entirely impossible to discuss and possibly change it, but you would have to go through lengthy deprecation process, this function is 20 years old for sure.
