### ISSUE TITLE
BUG or Feature? np.resharp() doesn't behave the same

### ISSUE THREAD

**Issue by JollyTRjano** [numpy/numpy#9286]
python 2.7.12 and numpy 1.11.2
# 1#
>>> x = np.arange(9.).reshape(3,3)
>>> x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])
>>> x.shape

(3L, 3L)

It gives me a 3 * 3 x straight.

#  2#
>>> x=np.arange(9.)
>>> x.reshape(3,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])
>>> x.shape

(9L,)

In this way, x is 1 * 9 actually, but looks like 3 * 3 in IDLE. 
And I have to
>>> x=x.reshape(3,3)
>>> x.shape

(3L, 3L)

Is it a bug or a feature?

**Comment by seberg** [comment]
Feature, you should not change the shape of an array in place, some other part of the code might still like to have it around, so use `x = x.reshape(...)`, you can in fact hack it by using `x.shape = ...` but I **strongly** discourage it, it is a hack that I would not mind if it was deprecated and removed.

**Comment by charris** [comment]
The first case assigns to x the reshaped array. the second discards it. The reshape is not in place, it returns a new array that is a view of the data.

**Comment by JollyTRjano** [comment]
Thanks guys.
