### ISSUE TITLE
numpy 1.13: numpy.testing.utils.assert_almost_equal doesn't support bools anymore.

### ISSUE THREAD

**Issue by ultimanet** [numpy/numpy#9290]
In numpy 1.13 the following "DeprecationWarning to error" was made:

> subtract(bool_, bool_), TypeError when subtracting boolean from boolean.

Because of this, `assert_almost_equal` cannot be used with numpy booleans anymore. 

```
import numpy as np
np.testing.utils.assert_almost_equal(np.True_, True)
```

raises

```
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Comment by charris** [comment]
This will not be a problem in 1.13.1, but we should deal with it for the future. Strictly speaking, booleans (and integers), should be checked for equality.

**Comment by theodoregoetz** [comment]
following the discussion in PR #9926 between myself and @eric-wieser, adding in @charris comment above, it's two to one that `almost_equal` **does not apply to bools**. That makes this issue a wontfix. It also means we have differring behavior for `assert_almost_equal(np.True_, True)` and `assert_array_almost_equal([np.True_], [True])`.

**Comment by eric-wieser** [comment]
> two to one that almost_equal does not apply to bools.

That's not quite my claim - I'm saying that `almost_equal` should just mean `equal` when applied to bool, rather than throwing an error.

At the very least, this needs a better error message if we keep it as an error.

**Comment by charris** [comment]
Going to kick this can down the road to 1,15,

**Comment by eric-wieser** [comment]
> It also means we have differring behavior for ...

This is definitely a bug. Unfortunately the testing code is full of special cases, and it's sometimes hard to reason about why they are there.

**Comment by eric-wieser** [comment]
Tempted to fix this by simply deprecating `assert_almost_equal` - `assert_allclose` is preferred according to the docs anyway

**Comment by mattip** [comment]
Grepping scipy, I get 2182 occurances of `assert_almost_equal`. Pandas has 608.

**Comment by charris** [comment]
Thinking this should get fixed, although I suspect many have worked around it by now.

**Comment by charris** [comment]
So it looks like this should be fixed. OTOH, It looks like it is no longer a pressing problem, so pushing off to 1.17.

**Comment by mattip** [comment]
We should make a decision to fix or to close.

**Comment by eric-wieser** [comment]
Earlier, @charris said:

> Strictly speaking, booleans [...], should be checked for equality.

My interpretation of this is `assert_almost_equal(bools...)` should be an alias for `assert_equal(bool...)`, for the purpose of being able to write parametric tests and do something sensible - this is my opinion on what should be done.

It's also possible he meant "people writing tests should not be calling this in the first place", which is also not a bad argument.

**Comment by charris** [comment]
@eric-wieser The first interpretation is what I intended.

**Comment by charris** [comment]
This slippery devil has managed to miss another release :) I am still in favor of comparing booleans for equality.

**Comment by george-zip** [comment]
> My interpretation of this is assert_almost_equal(bools...) should be an alias for assert_equal(bool...), for the purpose of being able to write parametric tests and do something sensible - this is my opinion on what should be done.

My understanding of this recommendation is that we check the types of `actual` and `desired` inside of `assert_almost_equal.` If they booleans then return `assert_equals` instead, as we do for `ndarray`:

```python
   if isinstance(actual, (ndarray, tuple, list)) \
            or isinstance(desired, (ndarray, tuple, list)):
        return assert_array_almost_equal(actual, desired, decimal, err_msg)
```

Is that right?

**Comment by mattip** [comment]
Closing This has been around so long I hope people have cleaned up their code to not need it any more. If that is not the case, please submit a PR to use `array_equal` for `bool`s.
