### ISSUE TITLE
Use converters for all columns

### ISSUE THREAD

**Issue by terriyu** [numpy/numpy#9291]
Suggestion for an enhancement: `loadtxt()` and `genfromtxt()` have the option to specify converters but only on a per-column basis.  If you have many columns and want to use the same converter on all of them, it would be nice to be able to do that without having to create a giant dictionary containing the same converting function over and over again.

So instead of having

`np.loadtxt('myfile', converters={0: myfunc, 1: myfunc, 2: myfunc, 3: myfunc, 4: myfunc, 5: myfunc, 6: myfunc, 7: myfunc, 8: myfunc, 9: myfunc})`

it would be nice to use something like

`np.loadtxt('myfile', converters=myfunc)`

**Comment by WarrenWeckesser** [comment]
Allowing `converters` to be a callable that is applied to all the columns would handle the case where you want a common converter for all columns but the number of columns is not known in advance.  Currently that is not possible.

**Comment by seberg** [comment]
Passing a single callable is now implemented by gh-20580.
