### ISSUE TITLE
Enable lgtm.com analysis on pull requests

### ISSUE THREAD

**Issue by jhelie** [numpy/numpy#9297]
Following #9292 @eric-wieser suggested discussing enabling PR integration for lgtm.com (see https://lgtm.com/docs/lgtm/config/pr-integration).

In brief:
- lgtm.com is an engineering analytics tool based on code queries expressed in QL, an SQL-like language to efficiently parse the code AST (https://lgtm.com/docs/ql/about-ql)
- alerts (= queries results) are tracked through revisions and changes are highlighted: PR integration gives a chance to check and act on any alerts before they find their way into the code base (e.g. the issues addressed in #9292 were flagged when vendoring in tempita in https://github.com/numpy/numpy/commit/581bb79c170748cbf2f6970cd53595b3b5f1fe3e)
- the query-console allows anyone to start writing their own QL code and ask questions about any open-source project of interest. All of our standard queries are open-source and give an idea of the kind of insights that can be achieved with a few lines of QL 

More info at https://lgtm.com/docs/lgtm/about-lgtm

Numpy's page: https://lgtm.com/projects/g/numpy/numpy

Any question please ask, we keep rolling out features and are always happy about feedback!

**Comment by eric-wieser** [comment]
Ok, since I just introduced a regression caught by lgtm, I've enabled this

**Comment by jhelie** [comment]
Hi Eric, that's great, thanks for letting me know! We've been working on lots of improvements to make PR integration more useful and user friendly - for instance you can now easily [suppress alerts](https://lgtm.com/docs/lgtm/alert-suppression) you believe are wrong/irrelevant (hopefully that won't be too many:) More should be rolled out soon so stay tuned. In the meantime feel free reach out if you have any questions/comments.

Cheers!
-Jean
