### ISSUE TITLE
Read-only error when temporary array is not writable

### ISSUE THREAD

**Issue by tkf** [numpy/numpy#9305]
It seems that an error is raised during arithmetic operations with large read-only array which is not referenced by any variables.  Maybe this is a bad interaction with Python's GC and Numpy reusing temporary?

The last line of the following code does not work:

```python
import numpy


def get():
    x = numpy.zeros(240000)
    x.flags['WRITEABLE'] = False
    return x


X = get()
X + 1   # no error from this line


get() + 1
```

It produces the following error:

```pytb
Traceback (most recent call last):
  File "...", line 14, in <module>
    get() + 1
ValueError: output array is read-only
```

Checked with Numpy 1.13.0 and Python 3.6.0.  No error is raised in Numpy 1.12.1.

**Comment by juliantaylor** [comment]
this issue should be fixed on the 1.13 branch, to be released soon
see https://github.com/numpy/numpy/pull/9260
