### ISSUE TITLE
`numpy.dtype()` issue warning when run python3 with `-b` switch

### ISSUE THREAD

**Issue by BranYang** [numpy/numpy#9308]
See [here](https://github.com/pandas-dev/pandas/issues/16776)

1. Run Python using
`python3 -b`
2. Run 
```
import numpy as np
np.dtype('int32')
```
I get output
```
>>> import numpy as np
>>> np.dtype('int32')
__main__:1: BytesWarning: Comparison between bytes and string
dtype('int32')

>>> print(sys.version)
3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 12:15:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

>>> np.version.version
'1.13.0'
```

**Comment by ahaldane** [comment]
Hmm. All numpy is doing is accessing a dictionary with a 'bytes' key. The offending line  essentially does`np.sctypeDict[b'int32']`.

You can get the same error in plain python3 by accessing a dict:
```python
>>> d = {'int32': 1}
>>> d[b'int32']
__main__:1: BytesWarning: Comparison between bytes and string
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: b'int32'
```

This doesn't seem like a numpy problem to me. If anything it may be a python3 problem, but it also seems possible to me it is the "expected" behavior of the `-b` flag, I'm not sure.

**Comment by eric-wieser** [comment]
I suspect the problem is the opposite - namely `d = {b'int32': 1}; d['int32']`

**Comment by ahaldane** [comment]
You would think :)  My reading is that in python3 the string is first converted to a bytes object [here](https://github.com/numpy/numpy/blob/bf12213a1835d42acbfc0bd5f5587d30372fc50e/numpy/core/src/multiarray/descriptor.c#L1440), then the dict lookup happens [here](https://github.com/numpy/numpy/blob/bf12213a1835d42acbfc0bd5f5587d30372fc50e/numpy/core/src/multiarray/descriptor.c#L1612), then it is converted back to unicode [here](https://github.com/numpy/numpy/blob/bf12213a1835d42acbfc0bd5f5587d30372fc50e/numpy/core/src/multiarray/descriptor.c#L1616).

**Comment by jdufresne** [comment]
I'm able to reproduce the `BytesWarning` simply by importing `numpy`. I bisected. For me this first started in commit 2c14e47834262de85673c0b71e94494a5f642268.

**Comment by jdufresne** [comment]
I have isolated the issue to the following code:

https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/descriptor.c#L1667-L1677

The bytes object `b'int64'` is passed. The code first indexes the dict by the bytes object and and then by the str object. But all the keys in the dict are str. I tried changing this to:

```c
            if (PyBytes_Check(obj)) {
                PyObject *tmp;
                tmp = PyUnicode_FromEncodedObject(obj, "ascii", "strict");
                if (tmp != NULL) {
                    item = PyDict_GetItem(typeDict, tmp);
                    Py_DECREF(tmp);
                }
            }
            else {
                item = PyDict_GetItem(typeDict, obj);
            }
```

But after that change, the tests segfault. Not quite sure where to go from there.

**Comment by seberg** [comment]
Sounds like the whole thing could use some cleanup with the knowledge that we are python3 maybe. @jdufresne, I think the problem with your patch is, that it is a bit obscure that `tmp == NULL` results in a `goto fail` immediately. I am not actually immediately sure why that shows up after your change and not before, but I think that explainst he segfaults you are seeing.
