### ISSUE TITLE
DOC: document PY_ARRAY_UNIQUE_SYMBOL and friends

### ISSUE THREAD

**Issue by jaimefrio** [numpy/numpy#9309]
There doesn't seem to be anywhere in the docs (or anywhere on the internet) where the role that `PY_ARRAY_UNIQUE_SYMBOL` and `NO_IMPORT` or `NO_IMPORT_ARRAY` play in creating C extensions that use the NumPy API in more than one compilation unit. We should add it!

**Comment by rgommers** [comment]
Good find! This rings only a very vague bell. Would be good to add some details here now that you have it in your short-term memory still.

**Comment by jaimefrio** [comment]
So this is how I understand this works...

It is [well documented](https://docs.scipy.org/doc/numpy-1.10.0/user/c-info.how-to-extend.html#required-subroutine) that to use the NumPy API you have to run `import_array()`, typically in your module definition, before calling any of the API functions. To have access to this function, I think you typically `#include "numpy/arrayobject.h"`, although in some places in SciPy this is replaced with the equivalent `#include "numpy/noprefix.h"` because it adds some backward compatible symbols.

 Internally, the C API is stored in an array of pointers, which by default is called `PyArray_API`, which gets initialized when `import_array()` is called. If you use the procedure described above, this is declared as:

```
static void **PyArray_API;
```

and because it is `static` it is not visible outside the compilation unit.

That is fine if you only have one compilation unit. If you have more, rather than having to call `import_array()` somewhere within each compilation unit, which may work but probably has subtle issues that escape me, NumPy provides two preprocessor flags that you can use.

The first one is `PY_ARRAY_UNIQUE_SYMBOL`. In scipy, this is typically defined by modules to be:

```
#define PY_ARRAY_UNIQUE_SYMBOL _scipy_module_ARRAY_API
```

but you could use any other *unique* identifier. This alone achieves two things:

 * the NumPy API storing pointer is renamed to your unique identifier, and
 * the `static` is dropped from the definition.

I.e. after all the preprocessing is done, it will now be:

```
void **_scipy_module_ARRAY_API;
```

so the symbol is visible also to other compilation units. You still need to call `import_array()` to get this pointer initialized to the actual API.

Lastly, you can also either `#define NO_IMPORT` or `#define NO_IMPORT_ARRAY` (they both do the same) before including the NumPy header. This basically changes the declaration of the API pointer variable to be:

```
extern void **PyArray_API;
```

(or your unique symbol if `PY_ARRAY_UNIQUE_SYMBOL` is also defined). This means that, within this compilation unit, we have access to the API declared and defined in some other compilation unit. It also removes the definition of `import_array`, so that it cannot be called from within this compilation unit.

So typically what you have to do if you have multiple compilation units is to:

 * Add `#define PY_ARRAY_UNIQUE_SYMBOL my_unique_snowflake_identifier` to the top of every compilation unit, before including the numpy header. This will be the identifier of the numpy API that all these compilation units will share.
 * On all but the compilation unit that initializes the Python module and calls `import_array()`, add also a `#define NO_IMPORT_ARRAY` before including the numpy header. This will ensure that these compilation units reuse the numpy API defined and initialized in the one that calls `import_array()`.

**Comment by mhvk** [comment]
That summary was useful; this stuff has confused me no end! So, please add to the documentation!

**Comment by jaimefrio** [comment]
Apparently it's already there, as @perimosocordiae pointed out in scipy/scipy#7537::

https://docs.scipy.org/doc/numpy/reference/c-api.array.html#importing-the-api

Unfortunately google misses it, and does not show a link to the numpy docs anywhere in the first few pages of a search for PY_ARRAY_UNIQUE_SYMBOL:

https://www.google.ch/search?q=PY_ARRAY_UNIQUE_SYMBOL

Interestingly this issue comes up fourth right now in those search results.

A search for NO_IMPORT_ARRAY does show the link to the docs, also in fourth position.

So I'm going to close this. If anyone thinks a lower level explanation would be a good thing, ping me here and I'll reopen and send a PR updating the docs.

**Comment by ev-br** [comment]
> So I'm going to close this. If anyone thinks a lower level explanation would be a good thing, ping me here and I'll reopen and send a PR updating the docs.

Ping :-).

**Comment by matthew-brett** [comment]
Ping2 :-) - it would be great to extend the old page with your explanation - I found it very helpful.

**Comment by jaimefrio** [comment]
Back by popular demand! ;-)

**Comment by elsampsa** [comment]
this link: https://docs.scipy.org/doc/numpy/reference/c-api.array.html#importing-the-api has disappeared since.. it would sure nice to find that excellent explanation again from somewhere..

**Comment by melissawm** [comment]
Is this page what you are looking for? https://numpy.org/doc/stable/reference/c-api/array.html#importing-the-api

**Comment by mpconte** [comment]
I followed the instructions as per [https://numpy.org/doc/stable/reference/c-api/array.html#importing-the-api](url)

but I'm getting an `unresolved external symbol my_unique_snowflake_identifier`.

I have one module which initializes the python environment (i.e. **Py_Initialize** and **import_array**) and a separate module that links to this and deals with numpy arrays via the C API. 

Am I missing something?

**Comment by mattip** [comment]
@mpconte this issue is closed. Please open a new one with a minimal reproducer that shows exactly what you are doing.
