### ISSUE TITLE
Slightly confusing auto-generated signature for the new `heaviside` ufunc

### ISSUE THREAD

**Issue by adeak** [numpy/numpy#9314]
The new `heaviside` ufunc has the following auto-generated signature both [online](https://docs.scipy.org/doc/numpy/reference/generated/numpy.heaviside.html) and via `numpy.info(numpy.heaviside)`:

```
heaviside(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
```

The documentation then goes on discussing the signature in terms of

```
heaviside(x, h0, /, **kwargs)
```

so at first glance the mismatch between the variable names `x1,x2` vs `x,h0` can be confusing, especially since the former would suggest that the two inputs have similar roles, such as in the case of the inputs of `logical_and`.

After a bit of digging in the source I realized that the auto-generated signature [seems to have the same format as e.g. `logical_and`](https://github.com/numpy/numpy/blob/11f3ebf86a16452d0af40b41925b201485ae7f9c/numpy/core/code_generators/generate_umath.py#L561-L566), and it's likely that the format of the signature can't be further customized, assuming the existing machinery for generating ufuncs. Note that e.g. [`logical_and`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_and.html) which formally shares a signature with `heaviside` refers to its inputs as `x1,x2` in the docstring. The same goes for [`right_shift`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.right_shift.html) which again has the same signature, but where the two inputs have similarly asymmetric roles. So perhaps the solution is to keep the auto-generated signature, and adjust the docstring.

There's also the minor but independent issue that [the documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.heaviside.html) contains the `out`-`where`-`kwargs` lines of the docstring twice (once listed after `x`, once after `h0`).

**Comment by eric-wieser** [comment]
`heaviside` is unusual in that it names its arguments.

Regarding the duplicate `out` parameters, thats due to [repeated `PARAMS` in the docstring here](https://github.com/numpy/numpy/blob/1ec9ad692e38654b70b77d92b74e841d7255e109/numpy/core/code_generators/ufunc_docstrings.py#L939-L944), which was missed presumably due to the unexpected parameter names

**Comment by WarrenWeckesser** [comment]
I probably got the habit of using more descriptive parameter names from the scipy ufuncs, where we add an extra line at the beginning of the docstring that shows the signature using the friendlier names.  E.g.

```
In [41]: from scipy.special import jn

In [42]: print(jn.__doc__)
jv(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

jv(v, z)

Bessel function of the first kind of real order and complex argument.

Parameters
----------
v : array_like
    Order (float).
z : array_like
    Argument (float or complex).

Returns
-------
J : ndarray
    Value of the Bessel function, :math:`J_v(z)`.

[...]
```

I'll create a pull request to use only `x1` and `x2` in the `heavside` docstring.

*Added to the numpy 2.0 wishlist*: ufuncs that handle argument names like  python functions created with `def`. :smile:

**Comment by WarrenWeckesser** [comment]
Change submitted: https://github.com/numpy/numpy/pull/9320

**Comment by adeak** [comment]
I can see why you'd do that, the scipy convention nicely bridges the gap between the auto-generated signature and the human-friendly docs. Thanks for the fix!
