### ISSUE TITLE
`isnat` seems to be missing from the online documentation

### ISSUE THREAD

**Issue by adeak** [numpy/numpy#9321]
I can't find `isnat` [in the list of logic functions in the documentation](https://docs.scipy.org/doc/numpy/reference/routines.logic.html), nor does its page exist [at the expected URL](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isnat.html). In contrast, `isin` and `heaviside` which are also new ufuncs, can be found in their respective expected locations.

**Comment by eric-wieser** [comment]
Fixed in #9253

**Comment by eric-wieser** [comment]
Actually, leaving this open to raise that we need to backport that

**Comment by adeak** [comment]
Just in case someone stumbles upon the other half of the issue: the referenced PR fixes the docs of both `isnat` and `positive`.

**Comment by charris** [comment]
Backport is up, so closing this.
