### ISSUE TITLE
DOC: Incorrect comment in the `common_type` docstring.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#9326]
The docstring for `common_type` says:

    All input arrays can be safely cast to the returned dtype without loss
    of information.

This is not true.  When the inputs are integers, the common type returned is `numpy.float64`.  Sufficiently large integers cannot be cast to floating point exactly.  For example,

```
In [8]: a = np.array([2**63+1])

In [9]: a
Out[9]: array([9223372036854775809], dtype=uint64)

In [10]: np.common_type(a, a)
Out[10]: numpy.float64
```

Send `a` on a round-trip to `float64` and the back to its original type.  The result does not equal `a`.
```
In [11]: a.astype(np.float64).astype(a.dtype)
Out[11]: array([9223372036854775808], dtype=uint64)
```

This issue could probably be marked "easy fix": just remove the statement.

**Comment by troublemagnet** [comment]
I'd like to work on this. May I?
