### ISSUE TITLE
BUG: ndarray.cumsum()[-1] is not equal to ndarray.sum() in some circumstances

### ISSUE THREAD

**Issue by hust220** [numpy/numpy#9329]
In the below case, a.cumsum()[-1] should be equal to a.sum(), but they are not.
```
>>> import numpy as np
>>> a = np.array([1,2e-9,3e-9]*1000000)
>>> a.cumsum()
array([  1.00000000e+00,   1.00000000e+00,   1.00000000e+00, ...,
         1.00000001e+06,   1.00000001e+06,   1.00000001e+06])
>>> a.cumsum()[-1]
1000000.0050045159
>>> a.sum()
1000000.0050000029
```

**Comment by seberg** [comment]
NumPy uses a pairwise summation for many/most sums (not for cumsum, and only along the "fast" axis in memory), which gives a better numerical accuracy. So in the sum case, you are seeing a better numerical accuracy for free basically, as to the cumsum case this cannot be provided.

**Comment by shoyer** [comment]
I agree with @seberg, this isn't a bug.

It is impossible to do exact calculations in floating point arithmetic, so numpy cannot guarantee that every mathematically equivalent way to calculate an expression gives the same result.

**Comment by eric-wieser** [comment]
To partially fix this, you could do:

```
a = np.cumsum(x)
a *= np.sum(x) / a.max()
```

Which would correct the final value, at the expense of the immediate values.

Another option would be to split the summation into segments, using the more accurate method for between-segment sums, for instance calculating:
```
a = np.cumsum(x)
```
as
```
s = 0
a = np.empty(len(x))
for i in range(0, len(x), 4):
    a[i:i+4] = s + np.cumsum(x[i:i+4])
    s += a[i:i+4]
```

**Comment by mcgeeco** [comment]
Is there an argument for documenting this? It led to a particularly nasty bug for us because we were using both the `sum` and the `cumsum` of an array while calculating some [weighted percentiles](https://en.wikipedia.org/wiki/Percentile#The_weighted_percentile_method), in which we were using both cum and cumsum.
Apologies if it's already documented somewhere and I missed it.

**Comment by seberg** [comment]
Not sure it is really documented anywhere, might have an other issue open for it. Documentation improvements are always welcome!
