### ISSUE TITLE
“where” clause in numpy-1.13 ufuncs

### ISSUE THREAD

**Issue by lvkessel** [numpy/numpy#9334]
See also [this question on stackoverflow](https://stackoverflow.com/questions/44725481/where-clause-in-numpy-1-13-ufuncs).

Essentially, the following code used to work but fails as of numpy-1.13:
````
import numpy as np
a = np.linspace(-1, 1, 10)
np.sqrt(a, where=a>0) * (a>0)
````
The error message is
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Automatic allocation was requested for an iterator operand, and it was flagged as readable, but buffering  without delayed allocation was enabled
````

If an `out` parameter is provided, the `sqrt` function works correctly. According to the comments on #9250, if an `out` parameter is not provided, the ufunc is supposed to allocate its own return memory (but not initialise it). To me, it seems that something is going wrong in this automatic allocation.

**Comment by eric-wieser** [comment]
It's worth noting that `np.sqrt(a, where=a>0) * (a>0)` did not _always_ do the right thing in 1.12, as you're relying on uninitialized memory not containing `nan`, `+inf`, or `-inf` when doing that multiplication.

To be safe, you should write:

```
b = np.sqrt(a, where=a>0)
b[~(a > 0)] = 0
```

**Comment by lvkessel** [comment]
Good point. I suppose that, from a practical user perspective, the best thing to do at the moment is to always provide a zero-initialised output array. Glad to see that this really is a bug though, and not my misunderstanding.

Out of curiosity, is it safe to provide `out = numpy.zeros(a.shape)` directly, i.e. not having the output array in an intermediate variable? Sorry if this is a novice question, I'm not exactly well-versed in python, I'm afraid it might get garbage collected or something.

**Comment by eric-wieser** [comment]
Yes, that would indeed be safe.

Does this error only occur with the multiplication added? If so, this sounds like misfiring temporary elision again

**Comment by lvkessel** [comment]
Thanks.
No, I always get the error, regardless of the `* (a>0)` bit.

**Comment by pv** [comment]
It's the copy-if-overlap change, 3b78ac77a9c74231a1db6514bbc3acc0b1257666
.
It's possibly a matter of not setting NPY_ITER_READWRITE when the 
output array is not user-provided.

**Comment by pv** [comment]
gh-9335
It seems there was no test coverage for `where=` without `out=`...
