### ISSUE TITLE
numpy.round() should return the same number of significant digits

### ISSUE THREAD

**Issue by homocomputeris** [numpy/numpy#9350]
```
In[1]: a = np.round([0.62831853,  0.39766996,  0.25032611],decimals=3)
Out[1]: array([ 0.628,  0.398,  0.25 ])
```
instead of 
`array([ 0.628,  0.398,  0.250 ])`

The problem is worse when you do `a[2]` and receive `0.25`. Is it exact or rounded to 3 decimals, 4 or 20?

To sum up: Trailing zeros to the right of the decimal are significant and should not be cut off.

**Comment by njsmith** [comment]
Computer floating point representations don't keep track of significant digits. `0.25` and `0.250` have exactly the same representation in memory. The numpy array printing routines are doing their best to show you this representation, but they don't have any way to know whether the `0.25` you gave them was created by calling `round` or anything else, so they use the heuristic of not showing trailing zeros.

You might find this article useful: https://en.wikipedia.org/wiki/Floating-point_arithmetic
