### ISSUE TITLE
Infinite loop in type_tuple_userloop_type_resolver

### ISSUE THREAD

**Issue by moble** [numpy/numpy#9351]
In relation to [a bug filed on my numpy quaternion package](https://github.com/moble/quaternion/issues/54), @eric-wieser found a bug in numpy.  He reports an infinite loop in `type_tuple_userloop_type_resolver`.  I don't actually understand that code, but I guess he's talking about the `continue` statement in [this loop](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_type_resolution.c#L1796) short-circuiting the `funcdata = funcdata->next` statement, which means the loop condition doesn't change between iterations.

Presumably, that bug needs to be fixed regardless, but (not really understanding numpy's internals) I wonder if I could have also done something in the quaternion package to avoid this problem.  My package attempts to add a new dtype to numpy, so maybe it also needs to update some internal list of dtypes that numpy maintains???  If so, I welcome comments.

**Comment by eric-wieser** [comment]
I'm surprised that this only gets hit in reduce.

The bug is indeed as you describe, and I have a working patch that's waiting on a non-metered internet connection to be submitted. (including some unrelated cleanup)

**Comment by eric-wieser** [comment]
To trigger this without reduce:

```
a = np.array(np.quaternion.x)
np.multiply(True, a, signature=(a.dtype, a.dtype, a.dtype))
```
