### ISSUE TITLE
TST: Make tests Pytest clean

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9352]
The files below with a checkmark currently work with Pytest.  The remainder have problems, among which are missing decorators, exception types, and use of generators. Doctests are also not run, but that is probably due to missing options. 

NumPy tests that work with Pytest
=================================

`numpy/tests`
-------------

- [x] `numpy/tests/test_ctypeslib.py`
- [x] `numpy/tests/test_matlib.py`
- [x] `numpy/tests/test_numpy_version.py`
- [x] `numpy/tests/test_reloading.py`
- [x] `numpy/tests/test_scripts.py`
- [x] `numpy/tests/test_warnings.py`

`numpy/lib/tests`
-----------------

- [ ] `numpy/lib/tests/test_format.py`
- [ ] `numpy/lib/tests/test_index_tricks.py`
- [ ] `numpy/lib/tests/test_twodim_base.py`
- [x] `numpy/lib/tests/test__datasource.py`
- [x] `numpy/lib/tests/test__iotools.py`
- [x] `numpy/lib/tests/test__version.py`
- [x] `numpy/lib/tests/test_arraypad.py`
- [x] `numpy/lib/tests/test_arraysetops.py`
- [x] `numpy/lib/tests/test_arrayterator.py`
- [x] `numpy/lib/tests/test_financial.py`
- [x] `numpy/lib/tests/test_function_base.py`
- [x] `numpy/lib/tests/test_io.py`
- [x] `numpy/lib/tests/test_mixins.py`
- [x] `numpy/lib/tests/test_nanfunctions.py`
- [x] `numpy/lib/tests/test_packbits.py`
- [x] `numpy/lib/tests/test_polynomial.py`
- [x] `numpy/lib/tests/test_recfunctions.py`
- [x] `numpy/lib/tests/test_regression.py`
- [x] `numpy/lib/tests/test_shape_base.py`
- [x] `numpy/lib/tests/test_stride_tricks.py`
- [x] `numpy/lib/tests/test_type_check.py`
- [x] `numpy/lib/tests/test_ufunclike.py`
- [x] `numpy/lib/tests/test_utils.py`

`numpy/f2py/tests`
------------------

- [ ] `numpy/f2py/tests/test_array_from_pyobj.py`
- [ ] `numpy/f2py/tests/test_assumed_shape.py`
- [ ] `numpy/f2py/tests/test_callback.py`
- [ ] `numpy/f2py/tests/test_common.py`
- [ ] `numpy/f2py/tests/test_kind.py`
- [ ] `numpy/f2py/tests/test_mixed.py`
- [ ] `numpy/f2py/tests/test_parameter.py`
- [ ] `numpy/f2py/tests/test_regression.py`
- [ ] `numpy/f2py/tests/test_return_character.py`
- [ ] `numpy/f2py/tests/test_return_complex.py`
- [ ] `numpy/f2py/tests/test_return_integer.py`
- [ ] `numpy/f2py/tests/test_return_logical.py`
- [ ] `numpy/f2py/tests/test_return_real.py`
- [ ] `numpy/f2py/tests/test_size.py`
- [ ] `numpy/f2py/tests/test_string.py`

`numpy/random/tests`
--------------------

- [x] `numpy/random/tests/test_random.py`
- [x] `numpy/random/tests/test_regression.py`

`numpy/polynomial/tests`
------------------------

- [ ] `numpy/polynomial/tests/test_classes.py`
- [x] `numpy/polynomial/tests/test_chebyshev.py`
- [x] `numpy/polynomial/tests/test_hermite.py`
- [x] `numpy/polynomial/tests/test_hermite_e.py`
- [x] `numpy/polynomial/tests/test_laguerre.py`
- [x] `numpy/polynomial/tests/test_legendre.py`
- [x] `numpy/polynomial/tests/test_polynomial.py`
- [x] `numpy/polynomial/tests/test_polyutils.py`
- [x] `numpy/polynomial/tests/test_printing.py`

`numpy/distutils/tests`
-----------------------

- [ ] `numpy/distutils/tests/test_system_info.py`
- [x] `numpy/distutils/tests/test_exec_command.py`
- [x] `numpy/distutils/tests/test_fcompiler_gnu.py`
- [x] `numpy/distutils/tests/test_fcompiler_intel.py`
- [x] `numpy/distutils/tests/test_misc_util.py`
- [x] `numpy/distutils/tests/test_npy_pkg_config.py`

`numpy/testing/tests`
---------------------

- [ ] `numpy/testing/tests/test_doctesting.py`
- [x] `numpy/testing/tests/test_decorators.py`
- [x] `numpy/testing/tests/test_utils.py`

`numpy/core/tests`
------------------

- [ ] `numpy/core/tests/test_arrayprint.py`
- [ ] `numpy/core/tests/test_datetime.py`
- [ ] `numpy/core/tests/test_deprecations.py`
- [ ] `numpy/core/tests/test_longdouble.py`
- [ ] `numpy/core/tests/test_mem_overlap.py`
- [ ] `numpy/core/tests/test_multiarray.py`
- [ ] `numpy/core/tests/test_nditer.py`
- [ ] `numpy/core/tests/test_numeric.py`
- [ ] `numpy/core/tests/test_print.py`
- [ ] `numpy/core/tests/test_records.py`
- [ ] `numpy/core/tests/test_regression.py`
- [ ] `numpy/core/tests/test_scalarmath.py`
- [ ] `numpy/core/tests/test_umath.py`
- [ ] `numpy/core/tests/test_umath_complex.py`
- [x] `numpy/core/tests/test_abc.py`
- [x] `numpy/core/tests/test_api.py`
- [x] `numpy/core/tests/test_defchararray.py`
- [x] `numpy/core/tests/test_dtype.py`
- [x] `numpy/core/tests/test_einsum.py`
- [x] `numpy/core/tests/test_errstate.py`
- [x] `numpy/core/tests/test_extint128.py`
- [x] `numpy/core/tests/test_function_base.py`
- [x] `numpy/core/tests/test_getlimits.py`
- [x] `numpy/core/tests/test_half.py`
- [x] `numpy/core/tests/test_indexerrors.py`
- [x] `numpy/core/tests/test_indexing.py`
- [x] `numpy/core/tests/test_item_selection.py`
- [x] `numpy/core/tests/test_machar.py`
- [x] `numpy/core/tests/test_memmap.py`
- [x] `numpy/core/tests/test_numerictypes.py`
- [x] `numpy/core/tests/test_scalarinherit.py`
- [x] `numpy/core/tests/test_scalarprint.py`
- [x] `numpy/core/tests/test_shape_base.py`
- [x] `numpy/core/tests/test_ufunc.py`
- [x] `numpy/core/tests/test_unicode.py`

`numpy/linalg/tests`
--------------------

- [ ] `numpy/linalg/tests/test_linalg.py`
- [x] `numpy/linalg/tests/test_build.py`
- [x] `numpy/linalg/tests/test_deprecations.py`
- [x] `numpy/linalg/tests/test_regression.py`

`numpy/ma/tests`
----------------

- [x] `numpy/ma/tests/test_core.py`
- [x] `numpy/ma/tests/test_deprecations.py`
- [x] `numpy/ma/tests/test_extras.py`
- [x] `numpy/ma/tests/test_mrecords.py`
- [x] `numpy/ma/tests/test_old_ma.py`
- [x] `numpy/ma/tests/test_regression.py`
- [x] `numpy/ma/tests/test_subclassing.py`

`numpy/fft/tests`
-----------------

- [x] `numpy/fft/tests/test_fftpack.py`
- [x] `numpy/fft/tests/test_helper.py`

`numpy/compat/tests`
--------------------

- [x] `numpy/compat/tests/test_compat.py`

`numpy/matrixlib/tests`
-----------------------

- [x] `numpy/matrixlib/tests/test_defmatrix.py`
- [x] `numpy/matrixlib/tests/test_multiarray.py`
- [x] `numpy/matrixlib/tests/test_numeric.py`
- [x] `numpy/matrixlib/tests/test_regression.py`

**Comment by andyfaff** [comment]
Is there a plan to replace `numpy/testing/nosetester.py` by a `numpy/testing/pytester.py`? I think a few downstream projects use that for their module testing, and it might be a good time to move that to pytest instead of nose.

**Comment by pv** [comment]
I think the better plan is to discard those and use the native pytest
test runner.

**Comment by njsmith** [comment]
I suspect we'll have to keep `nosetester` around for downstream users, but yeah, probably the simplest way is to just deprecate it without removing or modifying or replacing it.

Is there some particular value you see in having a `pytester` module?

**Comment by andyfaff** [comment]
One of my projects uses the scipy approach for package/module testing. In the `__init__.py` files for each of the modules (each module also has a tests directory) there is:

    from numpy.testing import Tester
    test = Tester().test

Enabling you to do:

    import scipy.optimise as spo
    spo.test()

etc. `numpy.testing.Tester` is an alias for `NoseTester` in `numpy/testing/nosetester.py`. My comment above was about replacing the nose machinery involved with that by pytest machinery.

**Comment by seberg** [comment]
The thing that I wonder a bit about…. Is there a way to specify your own warning filtering? Best even wrap the test run in your own things? We currently do that. half of that can probably be easily moved, but I am not sure about all of it. Plus, it allows to be at least slightly less spammy during testing without making the testing unreliable.

**Comment by rgommers** [comment]
> Is there some particular value you see in having a ``pytester`` module?

Like @andyfaff, I'd like to not lose functionality like being able to expose a ``numpy.test()`` or ``scipy.test()`` function. Plus I'd suspect we want warning filters, knownfailure decorator, etc. in a similar way - would be surprising if ``pytest`` does all we need out of the box.

> My comment above was about replacing the nose machinery involved with that by pytest machinery.

We can't replace for backwards compat reasons, so agree with deprecate (in docs only, no deprecation warning).

**Comment by pv** [comment]
Pytest does a lot out of the box,
https://docs.pytest.org/en/latest/contents.html
including warning filtering and knownfailures.
.
It's also arguable that `scipy.test()` and `numpy.test()` can be 
discarded over `python -m pytest ...` or just make it a thin wrappers 
calling `pytest.main(...)`.

**Comment by seberg** [comment]
Yes, but I somewhat expect we need those thin wrappers. You know that warning filtering is a mess, and that usual "ignore" filtering can create problems we have run into repeatedly. Now I am biased of course, but I dislike ditching it. Of course thin wrappers will be good enough to achieve that. Another thing might be to push some of our stuff upstream I suppose.

**Comment by pv** [comment]
pytest has builtin warning filtering system.

**Comment by seberg** [comment]
Last time I checked, they did not seem to have one that seems to really handles the annoying `__warning_registry__` stuff. Of course most of this is in the tests itself, but using global "ignore" could kill it. But then I may well be completely wrong. I did not check it, and don't have the time to look into pytest right now. Once wrote a mail to the list IIRC but there seemed to be no interest in discussing it.

**Comment by charris** [comment]
See #9362 for some preliminary work to support this issue.

**Comment by charris** [comment]
@rgommers Note that our testing decorators don't have the same functionality as similar decorators available in pytest. In particular, the skip, skipif, xfail markers are *markers* and are used at collection time, they lack the dynamic features of our versions - callable as well as boolean conditions - and only work with official test functions. I suspect our extra functionality is not needed, a bit of over design perhaps, but backwards compatibility is always a problem.  At some distant time we may want to deprecate some of those features just to simplify things.

**Comment by pv** [comment]
This seems to be working on an assumption that it makes sense to make 
the test suite runnable both with pytest and with nose. But maybe there 
is no upside in trying to retain nose compatibility --- it just adds 
extra work and friction (basically, pytest tmpdir, output capture etc 
helpers will not be so easy to backport to nose).

**Comment by rgommers** [comment]
@pv I think the worry is other projects? For numpy itself I agree, its test suite can be ``pytest``-only.

**Comment by rgommers** [comment]
> Note that our testing decorators don't have the same functionality as similar decorators available in pytest. In particular, the pytest skip, skipif, and xfail markers are markers and are used at collection time, they lack the dynamic features of our versions - callable as well as boolean conditions - and only work with official test functions. 

Not sure what you mean exactly. https://docs.pytest.org/en/latest/skipping.html shows that things like ``skipif`` and ``xfail`` have the boolean conditions we need, and there's also function-based equivalents that you can call. So AFAICS nothing important is missing.

**Comment by charris** [comment]
@pv Yes, it is other projects that make life difficult, as we need to maintain backwards compatibility. Scipy is one of those "other" projects.

@rgommers If you look closely, the pytest functions aren't the same and are used differently. Pytest looks at the marks when it gathers the functions for testing, so using those functions for non-testing functions doesn't work, and the condition needs to evaluate to boolean at collection time. I don't think the difference matters for usefulness, the problem is backward compatibility. Compatibility would not be a problem if we didn't need to worry about other projects. My thought is that eventually Numpy can go over to straight pytest and not worry about nose at all and we will only maintain the numpy decorations for backwards compatibility. We could, I suppose, start by using the pytest functions internally, wrapped with the old names, and simply deprecate *all* the nose functions at some point. We need to keep the nose testing working until all the tests are pytest clean, at that point we can reconsider.

**Comment by nicoddemus** [comment]
Guys, one of the pytest maintainers here. Just to let you know that if you need any hints or help on this endeavour please let us know. 👍

**Comment by charris** [comment]
@nicoddemus Now that you offer ...  I do have a question ;) Due to various historical reasons, some of our decorated test functions raise skipping exceptions, but not from the original function, and in verbose mode that gives output like
```
numpy/core/tests/test_umath_complex.py::TestCarg::test_zero <- ../../../../.local/lib/python2.7/site-packages/numpy-1.14.0.dev0+10b383f-py2.7-linux-x86_64.egg/numpy/testing/pytest_tools/decorators.py SKIPPED
```
Is there a hook that would allow me to remove the `<- ../../../../.local/lib/python2.7/site-packages/ ...` traceback stuff?

**Comment by nicoddemus** [comment]
Hi @charris,

As for the original question unfortunately I don't think it is possible to get rid of that traceback detail. 

But looking at the implementation of the decorators, unless I'm mistaken don't they already depend on `pytest` at import time anyway? For instance, looking at [how `slow` is implemented](https://github.com/charris/numpy/blob/add-pytest-support/numpy/testing/pytest_tools/decorators.py#L23):

```python
def slow(t):
    """..."""
    import pytest
    return pytest.mark.slow(t)
```

By marking a test function like this:

```python
@slow
def test_foo():
```

`pytest` will be imported during collection time, which sounds fine because at that point you are using the `pytest` runner to collect run/tests.

Sorry if I'm not correct on my assumptions, I don't know how the details of the numpy test suite.

**Comment by charris** [comment]
@nicoddemus Yes, you are correct. Theoretically, that is a bug, at least according to the way things are (were) supposed to work. I'm thinking of making it a feature. I have it done differenty in my unpushed changes. I can think of three levels of pytest independence:

1. pytest is never imported until the tests are run -- current practice with nose
2. pytest is never imported unless the testfiles are imported -- what I would like
3. pytest is imported together when numpy is -- what we need to avoid.

**Comment by nicoddemus** [comment]
@charris I see thanks. IMHO option 2 is reasonable enough if pytest is imported only when pytest is the configured runner. 👍

**Comment by charris** [comment]
Going to close this now that NumPy has switched to pytest.
