### ISSUE TITLE
[ENH] nan_to_num enhancement to fill inexact values with user provided values

### ISSUE THREAD

**Issue by kikocorreoso** [numpy/numpy#9356]
[See PR #9355]

**Comment by eric-wieser** [comment]
Note that you can already write this as:

```
np.select([np.isnan(x), np.isposinf(x), np.isneginf(x)], [-999, 999, -999], x)
```

**Comment by eric-wieser** [comment]
Closing - let's leave the discussion at the PR - there's no need to open an issue here as well. I've copied the content across
