### ISSUE TITLE
genfromtext doesn't work for me with list input

### ISSUE THREAD

**Issue by boffi** [numpy/numpy#9359]
I'm working on Debian Sid, using the Anaconda distribution, Python is 3.6.1 and Numpy is 1.13.0.
After reading [Defining the input](https://docs.scipy.org/doc/numpy/user/basics.io.genfromtxt.html#defining-the-input) (the **emphasis** is mine)

> The only mandatory argument of genfromtxt is the source of the data. **It can be** a string, **a list of strings**, or a generator. If a single string is provided, it is assumed to be the name of a local or remote file, or an open file-like object with a read method, for example, a file or StringIO.StringIO object. **If a list of strings** or a generator returning strings **is provided, each string is treated as one line in a file.** When the URL of a remote file is passed, the file is automatically downloaded to the current directory and opened.

I've hence  tried to use `genfromtext()` with a list of strings but it failed (see below, pasted and copied from an IPython session).  It is possible that I've misunderstood how the feature is intended to be used, in which case please close this issue as soon as possible...

Thanks,
```
In [115]: np.genfromtxt(['3. 6.', '3. 4.'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-115-b02d9b9867dc> in <module>(), 
----> 1 np.genfromtxt(['3. 6.', '3. 4.'])

~/lib/miniconda3/lib/python3.6/site-packages/numpy/lib/npyio.py in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows)
   1578                     first_line = (
   1579                         b''.join(first_line.split(comments)[1:]))
-> 1580             first_values = split_line(first_line)
   1581     except StopIteration:
   1582         # return an empty array if the datafile is empty

~/lib/miniconda3/lib/python3.6/site-packages/numpy/lib/_iotools.py in _delimited_splitter(self, line)
    218     def _delimited_splitter(self, line):
    219         if self.comments is not None:
--> 220             line = line.split(self.comments)[0]
    221         line = line.strip(b" \r\n")
    222         if not line:

TypeError: must be str or None, not bytes

In [116]: 
```

**Comment by bashtage** [comment]
This is a bug on Python3 since it is not handling strings correctly.

If you need a workaround, you could use

```
from numpy import genfromtxt
from io import StringIO, BytesIO

sio = BytesIO('3. 6.\n3. 4.'.encode('utf8'))
genfromtxt(sio,comments=None)
```

**Comment by bashtage** [comment]
You also could use

```
np.genfromtxt(['3. 6.'.encode('utf8'), '3. 4.'.encode('utf8')])
```

or
 
```
data = ['3. 6.', '3. 4.']
np.genfromtxt(map(lambda s:s.encode('utf8'), data))
```

**Comment by sethtroisi** [comment]
Seems to be working at head
```python
>>> import numpy as np
>>> np.genfromtxt(['3. 6.', '3. 4.'])
array([[3., 6.],
       [3., 4.]]) 
```
