### ISSUE TITLE
New space prefixing string output of floating point array scalars

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#9384]
I guess this is to do with the new numpy scalar formatting stuff, but this seems a bit odd - and broke our doctests:

```
In [5]: str(np.array(1/3.))
Out[5]: ' 0.33333333'

In [6]: np.__version__
Out[6]: '1.14.0.dev0+569c591'
```

Notice the space before the first 0 in the output string.   This isn't present with released numpy:

```
In [3]: str(np.array(1/3.))
Out[3]: '0.333333333333'

In [4]: np.__version__
Out[4]: '1.13.1'
```

Is it intended?

**Comment by eric-wieser** [comment]
Yep, 1.14dev is unstable in this regard - there are a bunch of PRs related to this can of worms, none of which have yet been merged.

**Comment by eric-wieser** [comment]
All fixed now
