### ISSUE TITLE
BUG: 1.13.1 build fails on numpy.random.mtrand in python3.7dev

### ISSUE THREAD

**Issue by yarko** [numpy/numpy#9391]
I'll log this for now:

on ubuntu 16.04.2
numpy 1.13.1 installed fine on python 3.6.2.rc1
numpy 1.13.0 installed fine on python 3.7.0a0 (heads/master:6969eaf)

Numpy 1.13.1 failure in building:

```
     building 'numpy.random.mtrand' extension
    compiling C sources
    C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
    
    creating build/temp.linux-x86_64-3.7/numpy/random
    creating build/temp.linux-x86_64-3.7/numpy/random/mtrand
    compile options: '-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c'
    gcc: numpy/random/mtrand/mtrand.c
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
    numpy/random/mtrand/mtrand.c:44374:12: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject **, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
    numpy/random/mtrand/mtrand.c:44374:12: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject **, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                ^
    error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of numpy
```

**Comment by charris** [comment]
What Cython version? The only PR that touched mtrand was #9240, and that only for the documentation. I think this is probably a Python 3.7 or Cython problem. If it is Python, it would be good to let them know. And yes, there is one argument (NULL) too many.

**Comment by yarko** [comment]
Cython 0.25.2

**Comment by timgraham** [comment]
From http://bugs.python.org/issue29464#msg298230

> I think you need to update Cython to a version that supports new FASTCALL call convention in 3.7. If the support of FASTCALL in Cython is optional try to disable it.

**Comment by yarko** [comment]
thanks @timgraham - but not sure how this guides this issue:

Cython 0.25.2 seems to support METH_FASTCALL from 0.25.2
 See:
- cython/cython#1506
 - cython/cython#1513 (closed as duplicate - is it?)

Is this, then, still a pending Cython bug, which should be posted there?
Is this a numpy (?) issue, wherin FASTCALL should be disabled for said extension (mtrand)?

**Comment by timgraham** [comment]
I don't have any experience with cython.

**Comment by njsmith** [comment]
Those Cython bug reports are from last year, and the [CPython commit](https://github.com/python/cpython/commit/6969eaf4682beb01bc95eeb14f5ce6c01312e297) you're referring to that changed the semantics of METH_FASTCALL was made 9 days ago, so I don't think they're related.

I think this is a Cython bug – CPython just changed the C API underneath them, and they need to adapt.

**Comment by scoder** [comment]
Cython 0.26 will be released shortly and adds support for this change in Py3.7.

**Comment by scoder** [comment]
Fixed in Cython 0.26.

**Comment by seberg** [comment]
So I guess this is a cython+ pzthon version issue, so I will just close this. Thanks @scoder!

**Comment by yarko** [comment]
...it does not appear that Cython 0.26 has solved the problem on my setup...

I'll collect the info and open a new issue in a little bit.

**Comment by seberg** [comment]
Sorry, will reopen this then for now.

**Comment by scoder** [comment]
@yarko are you still getting the exact same errors with Cython 0.26 ?

**Comment by yarko** [comment]
From a venv, using python3.7dev built last Friday, I have the following results (tail after pip install numpy):

```
    creating build/temp.linux-x86_64-3.7/numpy/random
    creating build/temp.linux-x86_64-3.7/numpy/random/mtrand
    compile options: '-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/yarko/tmp/env/py37/include -I/usr/local/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c'
    gcc: numpy/random/mtrand/mtrand.c
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
    numpy/random/mtrand/mtrand.c:44374:12: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject **, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
    numpy/random/mtrand/mtrand.c:44374:12: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject **, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                ^
    error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/yarko/tmp/env/py37/include -I/usr/local/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
    
    ----------------------------------------
Command "/home/yarko/tmp/env/py37/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/user/1000/pip-build-rrczbth5/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/user/1000/pip-9mfc74mm-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/yarko/tmp/env/py37/include/site/python3.7/numpy" failed with error code 1 in /tmp/user/1000/pip-build-rrczbth5/numpy/
(py37) yarko@yarko-nuc6:~/tmp$ pip list
Cython (0.26)
pip (9.0.1)
setuptools (36.2.7)
(py37) yarko@yarko-nuc6:~/tmp$ python -c 'import sys; print(sys.version)'
3.7.0a0 (heads/master:d255fea, Aug  4 2017, 17:37:58) 
[GCC 5.4.0 20160609]
```

**Comment by yarko** [comment]
...also, to confirm this wasn't something with my ubuntu config / library setup, I just did this in a virtualbox for RHEL, clean install and clean python3.7 build (also, install in a venv):

Also, same results:

```
...
    creating build/temp.linux-x86_64-3.7/numpy/random
    creating build/temp.linux-x86_64-3.7/numpy/random/mtrand
    compile options: '-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/yarko/tmp/env/py37/include -I/usr/local/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c'
    gcc: numpy/random/mtrand/mtrand.c
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
    numpy/random/mtrand/mtrand.c:44374:5: error: too many arguments to function ‘(struct PyObject * (*)(struct PyObject *, struct PyObject **, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
         ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
    numpy/random/mtrand/mtrand.c:44374:5: error: too many arguments to function ‘(struct PyObject * (*)(struct PyObject *, struct PyObject **, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
         ^
    error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/yarko/tmp/env/py37/include -I/usr/local/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
    
    ----------------------------------------
Command "/home/yarko/tmp/env/py37/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f4v6c4zu/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3l4f2sf9-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/yarko/tmp/env/py37/include/site/python3.7/numpy" failed with error code 1 in /tmp/pip-build-f4v6c4zu/numpy/
(py37) [yarko@rhel tmp]$ uname --all
Linux rhel.localdomain 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
(py37) [yarko@rhel tmp]$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
Cython (0.26)
pip (9.0.1)
setuptools (36.2.7)
(py37) [yarko@rhel tmp]$ 
```

**Comment by scoder** [comment]
The question is whether NumPy has already switched to Cython 0.26. If the sources that you are compiling have been generated with 0.25.2, then you won't see a difference. You can find the Cython version in the header comment of the generated C files.

BTW, we are currently planning for a 0.26.1 release with a couple of more bug fixes (not related to this issue), so maybe it's worth waiting for that for an actual production release of NumPy. Given that this is an issue with CPython 3.7, which is still far from release ready, I guess this isn't a major priority, though. The first beta of 3.7 is planned for end of next January. There's definitely going to be a Cython 0.27 before that.

**Comment by timgraham** [comment]
For what it's worth, I like to test Django with cpython's master branch to give an early warning for cpython changes affecting Django. This is blocking that testing, however, we could stop this testing with numpy in the meantime.

**Comment by montefra** [comment]
I am trying to test some of my code, that depends on ``numpy``, against python3.7.

``tox -e py37`` fails with the error reported in thi issue. 
I have tried to install numpy by hand in the virtualenv created by ``tox`` using ``pip``.
All the cases I have testes failed, as you can see in the table:

version | ``pip install cython`` first | no pre-installed ``cython`` | 
----------|----------------------------------|-------------------------------------
git master (9e05bc3)| fail | fail
1.13.1 | fail | fail
1.13.0 | fail | fail

**Comment by yarko** [comment]
ok - so the pieces I left off of past posts (I assumed they would be obvious, w/in context - but now will double check all explicitly, for all):

Back to my python3.7dev venv used just for this test:
```
(py37) yarko@yarko-nuc6:~/tmp$ pip install numpy
Collecting numpy
  Using cached numpy-1.13.1.zip
Installing collected packages: numpy
  Running setup.py install for numpy ... |
```
also:
```
(py37) yarko@yarko-nuc6:~/tmp$ pip install --no-cache-dir numpy
Collecting numpy
  Downloading numpy-1.13.1.zip (5.0MB)
    100% |████████████████████████████████| 5.0MB 23.9MB/s 
Installing collected packages: numpy
  Running setup.py install for numpy ... /
```
and, just to inspect @scoder suggestion, downloaded numpy-1.13.1.zip manually from https://pypi.python.org/pypi/numpy/1.13.1  to unzip and check the header files...

I think @scoder is assuming the pre-built packages from pypi, but for python3.7, this is built from source for the pip-install, so I'm not sure that concern applies.  Grep-ing thru C (`*.{c,h,py}`) sources I see no reference to any cython verson (only fftpack, python, and npy_api versions) - so I'll go with this.

Just to confirm, I'm trying a pip install from the unpacked source archive, manually (so I have the residuals readily available to inspect).

Using the suggestion from `INSTALL.rst.txt`, I built (inside the venv) with:

`python setup.py build -j 4 install`

with the same results (albeit, in a different form of flow - but the same error in `mtrand.c`:
```
gcc: numpy/core/src/multiarray/temp_elide.c
numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
numpy/random/mtrand/mtrand.c:44374:12: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject **, Py_ssize_t))meth’
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
            ^
numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
numpy/random/mtrand/mtrand.c:44374:12: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject **, Py_ssize_t))meth’
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
            ^
```

Repeating the same, from the github repository master results in success:

```
creating dist
creating 'dist/numpy-1.14.0.dev0+9e05bc3-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing numpy-1.14.0.dev0+9e05bc3-py3.7-linux-x86_64.egg
creating /home/yarko/tmp/env/py37/lib/python3.7/site-packages/numpy-1.14.0.dev0+9e05bc3-py3.7-linux-x86_64.egg
Extracting numpy-1.14.0.dev0+9e05bc3-py3.7-linux-x86_64.egg to /home/yarko/tmp/env/py37/lib/python3.7/site-packages
Adding numpy 1.14.0.dev0+9e05bc3 to easy-install.pth file
Installing f2py script to /home/yarko/tmp/env/py37/bin

Installed /home/yarko/tmp/env/py37/lib/python3.7/site-packages/numpy-1.14.0.dev0+9e05bc3-py3.7-linux-x86_64.egg
Processing dependencies for numpy==1.14.0.dev0+9e05bc3
Finished processing dependencies for numpy==1.14.0.dev0+9e05bc3
(py37) yarko@yarko-nuc6:~/tmp/numpy$ 
(py37) yarko@yarko-nuc6:~/tmp/numpy$ pip list
Cython (0.26)
numpy (1.14.0.dev0+9e05bc3)
pip (9.0.1)
setuptools (36.2.7)
```

**Comment by yarko** [comment]
... in the HEAD of master build, there were more verbose "errors" (e.g. not finding f95), so I checked, didn't have, and installed gfortran (for f95).   This seemed to produce no differences building from the unpacked numpy-1.13.1 source tree, with `python setup.py build_ext --inplace -j 4`.

**Comment by njsmith** [comment]
@yarko: numpy releases contain pre-cythonized .c files, so that users don't need to install cython to build from source. In this case, if you unpack `numpy-1.13.1.zip` and look in `numpy/random/mtrand.c`, the first line is: `/* Generated by Cython 0.25.2 */`

Building from a git checkout OTOH does use your local cython install to create mtrand.c on the fly.

So if the release is failing but a git checkout is succeeding, then that's all as expected. You'll need to wait for another release for this to be fixed.

**Comment by yarko** [comment]
Thanks @njsmith (my grep'ing missed this? - my partial attention...)

As far as I can tell, the `--force` option to `setup.py` doesn't seem to do it (it looks like it should work to rebuild mtrand.c, but does not), and I did not find a `pip`option which worked either (tried `--force-reinstall`).

So right now, it looks like, in order to successfully install *numpy* for *python3.7dev* it will take the following (if you see another way, please...):

- get the source (either unzip numpy-1.13.1 distro, or git-clone, and checkout appropriate version);
- in the source top directory (numpy, or numpy-1.13.1 as appropriate):
- `cd numpy/random/mtrand;  python generate_ mtrand_c.py; cd -`
- then, either:
   - `pip install .`
   - or any of the `python setup.py ...` patterns from the `README`.

This seems to work (even as it is a not a usual process).

**Comment by yarko** [comment]
as a post-script, an after-note just for completeness (installing from the github repo I would prefer):

In order to install numpy-1.13.1 in python3.7dev, from the distribution archive (which for python3.7 means from the source zip distributed), it appears you need to:

- install Cython 0.26, or later;
-  unzip the numpy-1.13.1 archive manually, and `cd` into it;
- `cd numpy/random/mtrand/`
- `python3.7 generate_mtrand_c.py`
- `cd -`
- `pip install .`  (or, alternately, one of the `python setup.py ...` methods described in the `INSTALL` doc;

**Comment by seberg** [comment]
Sounds like it might be worth to consider to regenerate the file before the 1.13.2 release, and by that time cython 0.26.1 is possibly there as well? Frankly, not sure myself, but just tagging in case, if its just regeneration it might be a small thing.

**Comment by yarko** [comment]
fyi - the runtests.py completes "ok' for python 2.7.13, 3.6.2, and 3.7dev from numpy1.13.1 w/ cython 0.26 (cloned tree).

**Comment by njsmith** [comment]
c9fd63407da2a529c205402fd1bda5ea20eedce2 changed it so `mtrand.c` isn't checked into git at all. It's automatically generated every time you build from a checkout or create an sdist. So 1.13.2 should take care of itself (so long as @charris makes sure to have the latest cython installed).

**Comment by charris** [comment]
@njsmith Yep, had it since this was reported. Always good to be sure ...

**Comment by charris** [comment]
Fixed by using Cython 0.26+. Note that there appears to be a bug in 0.27.

**Comment by Aashutosh-kumar** [comment]
Its till throws the same error

**Comment by mattip** [comment]
If you are not using NumPy version 1.13, please open a new issue. If you are, please upgrade.
