### ISSUE TITLE
np.stack and np.concatenate should return np.emtpy(0) when the arrays is emtpy

### ISSUE THREAD

**Issue by acgtyrant** [numpy/numpy#9395]
OS: Ubuntu
Python:  '3.5.2 (default, Nov 17 2016, 17:05:23) \n[GCC 5.4.0 20160609]'
Numpy: 1.13.0

```
 (e) .env  In [5]   np.stack([np.empty(0), np.empty(0)])
            Out[5]   array([], shape=(2, 0), dtype=float64)

 (e) .env  In [6]   np.stack([np.empty(0)])
            Out[6]   array([], shape=(1, 0), dtype=float64)

 (e) .env  In [7]   np.stack([np.empty((0,1)), np.empty((0,1))])
            Out[7]   array([], shape=(2, 0, 1), dtype=float64)

 (e) .env  In [8]   np.stack([np.emtpy((0,1))])
            Out[9]   array([], shape=(1, 0, 1), dtype=float64)
```

So for the above rule, `np.stack([])` should return `np.empty(0)`, no complain `need at least one array to stack`, in the same way for `np.concatenate([])`.

**Comment by njsmith** [comment]
The problem is that if there are no arrays given, then we have no way to know the intended dimensionality of the output. It could be `np.empty(0)`, but it could also be `np.empty((0, 10, 17))` or any shape whose first dimension is 0.

**Comment by acgtyrant** [comment]
You are right, we have to handle the intended dimensionality of the output manually.
