### ISSUE TITLE
Unexpected TypeError when get the length of a copy of an array

### ISSUE THREAD

**Issue by cmpute** [numpy/numpy#9396]
An weird error occurs when trying to use len() of a copy of an ndarry (in fact, I found the bug using a recarray)
Code pasted as follows:
```python
import numpy as np
a = np.array([1,2])
len(np.array(a[0], copy=False)) # this line raise an TypeError
```
TypeError raised with message:
`TypeError: len() of unsized object`
my OS is win10, python 3.5, numpy 1.11.1

**Comment by eric-wieser** [comment]
The "copy" is a red herring. The simplest reproduction is `len(np.array(1))`, which is what your code is doing.

This is by design - `len(arr)` is defined as `arr.shape[0]`, but here `arr.shape == ()`
