### ISSUE TITLE
Can argsort deal with multiple duplicates?

### ISSUE THREAD

**Issue by ivan-marroquin** [numpy/numpy#9410]
Hi there!

I am using an anaconda 4.3.18 64 bits installation on windows 7. the version of python is 3.6.1 and numpy version is 1.12.1

I imported an ascii file, and ran these commands:
import numpy as np

# read the ascii file into attribute variable

sorted_items= np.sort(attribute, axis=0)
sorted_ids= np.argsort(attribute,axis=0)

Then, I exported sorted_items and sorted_ids to an ASCII file.

Thereafter, I imported the same file in Octave version 4.2.0 64 bits and ran this command:
[sorted_items,sorted_ids]= sort(attribute)

Also, I exported the outputs to an ASCII file.

When I compared these outputs, I noticed the following:
- The sorted values in Python match those in Octave
-  The sorted index show issues.  The index reported by numpy are different to those reported by Octave in many places (see the excell spreadsheet, rows with blue background)
- The sorted index show some good matches. A good index match is when the Octave index is one value higher than the one for Python (because Octave starts counting from 1, instead of 0 for Python)

I attached to this issue two files: the excell spreadsheet, and the text file containing the data used to report this issue.

Many thanks,
Ivan
[Data.zip](https://github.com/numpy/numpy/files/1145419/Data.zip)

**Comment by eric-wieser** [comment]
`argsort` has a `kind` argument, which specified whether to use a stable sort. I don't know what the default is for octave, but the default in numpy is an unstable sort (equal items can be reordered).

`np.argsort(attribute, axis=0, kind='mergesort')` will give a stable sort, and possibly match the octave behaviour

**Comment by ivan-marroquin** [comment]
Hi Eric,

Thanks so much! the trick worked.

Ivan
