### ISSUE TITLE
MAINT: Convert the doctest in `numpy/lib/tests/test_polynomial.py` to regular tests.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9416]
Might be tricky, as the tests are testing the output formatting.

**Comment by kchomski-reef** [comment]
@charris While looking into this issue I found that module level docstring in `test_polynomial.py` is **not** run by `test_doctests` method inside `TestDocs` class, which is defined as:
```python
class TestDocs(object):
    def test_doctests(self):
        return rundocs()
...
```
Now it only collects two docstrings from other `TestDocs` methods (which have no tests inside them) - is this correct?

And 2nd question regarding your OP - if we're converting doctests to regular test, then it is not required to check the output formatting, right?
I mean:
```python
>>> p = np.poly1d([ 1.,  2.,  3.])
>>> q = np.poly1d([1.,2.,3.])
>>> p == q
True
```

**Comment by charris** [comment]
I don't know about the first question. The answer to the second question probably depends precisely on what is being tested. If the result values are being tested, then the formatting doesn't matter, that is, in fact one good reason not to use doctests. But the polynomial printing also attempts to format the result in a mathematical way, and that also gets tested, so in those cases we want to check the formatting. Apropos the mathematical printing, we will probably want to replace that at some point with special formatting functions that can be called by Jupyter, so I don't know if we want to spend a lot of time checking the current behavior.
