### ISSUE TITLE
ENH: Add gallery to numpy.org,

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9417]
Suggested by @stefanv 

>Here's a random idea: how about building a NumPy gallery?  scikit-{image,learn} has it, and while those projects may have more visual datasets, I can imagine something along the lines of Nicolas Rougier's beautiful book:
http://www.labri.fr/perso/nrougier/from-python-to-numpy/

@WeatherGod 

>Just a heads-up. There is now a sphinx-gallery plugin. Matplotlib and a few other projects have migrated their docs over to use it.
https://sphinx-gallery.readthedocs.io/en/latest/

I don't know enough about the tools to be helpful with this. Note that the actual repo is not numpy, but among the numpy project repos.

**Comment by rgommers** [comment]
We can close this I think, we have a new website and new notebook tutorials.
