### ISSUE TITLE
TST: Add Mac testing

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9421]
@rgommers 

> On Wed, Jul 5, 2017 at 10:14 PM, Peter Cock <p.j.a.cock@googlemail.com> wrote:
>>    Note that TravisCI does not yet have official Python support on Mac OS X,
>>    https://github.com/travis-ci/travis-ci/issues/2312
>>    I believe it is possible to do anyway by faking it under another setting
    (e.g. pretend to be a generic language build, and use the system Python
    or install your own specific version of Python as needed), so that may be
    worth trying during a sprint.

> That approach has worked reliably for https://github.com/MacPython/numpy-wheels for a while now, so should be straightforward.

**Comment by rgommers** [comment]
Thanks @charris, this dropped off the todo list.

**Comment by rgommers** [comment]
@matthew-brett would be nice to get your opinion on this one. What do you think the best way is to do this?

I suspect we want to avoid putting ``multibuild`` and ``gfortran`` submodules in the numpy repo, but we could clone them within a shell script that's called in the TravisCI ``before_install``, and then execute that. Just for one config, Python 3.6 (your daily tests provide better coverage, but one build matrix entry would be useful).

**Comment by matthew-brett** [comment]
I think we could get away with just cloning multibuild, and using homebrew to install the latest gfortran - multibuild is really small, and has the bash scripts for downloading / installing the Python.org binaries, pip etc.

**Comment by rgommers** [comment]
That sounds okay I think. If it is put at ``tools/multibuild`` it will be nicely out of the way so people don't wonder what it is.

**Comment by cournape** [comment]
@rgommers are you working on this ? Otherwise I can take a quick look at it

**Comment by charris** [comment]
@cournape Go for it.

**Comment by cournape** [comment]
Ok, looking at it now (I am on gitter.im/numpy/numpy for the sprints, is that the right location for chit chat, to avoid polluting the issue tracker ?)

**Comment by charris** [comment]
> is that the right location for chit chat

Doesn't seem to be anyone else on there, I just now saw your earlier message. I should probably set up notifications.

**Comment by rgommers** [comment]
@cournape I'm not. Note that @andyfaff just did this for scipy: https://github.com/scipy/scipy/pull/7607, so can borrow from that

**Comment by andyfaff** [comment]
Multibuild doesn't have a release branch, I used master, which is not necessarily the best thing to do. Use `brew install gcc` to get gfortran. Might be worth looking at conda-forge to see how they deal with multi platform builds.

**Comment by matthew-brett** [comment]
`master` branch should be fine - as recorded at https://github.com/matthew-brett/multibuild#multibuild-development, we try to keep `master` at release quality, and develop on the `devel` branch.

**Comment by cournape** [comment]
I have something that almost work, but I have an error at the end: https://travis-ci.org/cournape/numpy/builds/254106566 (cournape/numpy@cd78bdc794e9b3dd87b249d4a65461b156da37a6)

Also, I am not sure whether the upload wheel part can be reused as is for osx as well ?

**Comment by cournape** [comment]
It is almost impressive we manage to have lunch for 5 hours and did not discuss a minute of this, @matthew-brett :)

**Comment by matthew-brett** [comment]
It is impressive - but then again - we covered other topics ...  

The `shell_session_update` thing is probably hiding another error - c.f. https://github.com/direnv/direnv/issues/210

In multiibuild, we hack around this: https://github.com/matthew-brett/multibuild/blob/master/common_utils.sh#L17

**Comment by tylerjereddy** [comment]
Resolved in #12051 -- we have MacOS CI testing now via Azure. Homebrew is used to install gfortran via gcc and all acceleration libraries are disabled to avoid LAPACK issues.
