### ISSUE TITLE
BUG: 2D histogram incorrect when dealing with small values

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#9435]
The following example is incorrect - the single bin in the histogram should have a value of 0, not 1:

```python
In [13]: np.histogram2d([1e-60], [1e-60], range=((0, 1e-50), (-1e-50, 0)), bins=(1, 1))[0]
Out[13]: array([[ 1.]])
```

**Comment by astrofrog** [comment]
It seems that this already occurs with only moderately challenging precision cases:

```
In [4]: np.histogram2d([61.000001], [1], bins=(1,1), range=((0, 61), (-10000000,0)))[0]
Out[4]: array([[ 1.]])
```

**Comment by eric-wieser** [comment]
This appears to be by design (!?), because `histogramdd` fuzzes the comparison on the last bin

**Comment by astrofrog** [comment]
@eric-wieser - I'm going to assume you intended to close this, so will do it :)
