### ISSUE TITLE
BUG: it is possible to set array to writeable even when the underlying buffer/memoryview is supposedly not.

### ISSUE THREAD

**Issue by danielhrisca** [numpy/numpy#9440]
Given 50 bytes of data that contains 10 records, 5 bytes each, from which I need to extract two unsigned little endian signals:

1.  byte offset 0, bit offset 0, bit count 7 
2.  byte offset 0, bit offset 7, bit count 29 (it starts after the first one)

The dtypes used for the numpy.core.records.fromstring function are

1. [('vals', 'u1'), ('res3', 'S4')]
2. [('vals', '<u4'), ('res3', 'S1')]

# Using setflags to make the array writable
``` python
from numpy import dtype
from numpy.core.records import fromstring

data = bytes([0x00, 0x00, 0x00, 0x00, 0x00, 0x81, 0x00, 0x00, 0x00, 0x30, 0x02, 0x01, 0x00, 0x00, 0x40, 0x83, 0x01, 0x00, 0x00, 0x70, 0x04, 0x02, 0x00, 0x00, 0x00, 0x85, 0x02, 0x00, 0x00, 0x30, 0x06, 0x03, 0x00, 0x00, 0x40, 0x87, 0x03, 0x00, 0x00, 0x70, 0x08, 0x04, 0x00, 0x00, 0x00, 0x89, 0x04, 0x00, 0x00, 0x30])

signals = []

# first signal
bits = 7
types = dtype( [('vals', 'u1'), ('res3', 'S4')] )
values = fromstring(data, types)
vals = values['vals']
vals.setflags(write=True)
vals &= (2**bits-1)
signals.append(vals)

# second signal
bits = 29
bit_offset = 7
types = dtype( [('vals', '<u4'), ('res3', 'S1')] )
values = fromstring(data, types)
vals = values['vals']
vals.setflags(write=True)
vals >>= bit_offset
vals &= (2**bits-1)
signals.append(vals)

print(signals)
```
The erroneous output is:
```python
[array([0, 0, 2, 2, 4, 4, 6, 6, 8, 8], dtype=uint8), array([0, 0, 2, 2, 4, 4, 6, 6, 8, 8], dtype=uint32)]
```
# Creating new arrays for each operation
```python
from numpy import dtype
from numpy.core.records import fromstring

data = bytes([0x00, 0x00, 0x00, 0x00, 0x00, 0x81, 0x00, 0x00, 0x00, 0x30, 0x02, 0x01, 0x00, 0x00, 0x40, 0x83, 0x01, 0x00, 0x00, 0x70, 0x04, 0x02, 0x00, 0x00, 0x00, 0x85, 0x02, 0x00, 0x00, 0x30, 0x06, 0x03, 0x00, 0x00, 0x40, 0x87, 0x03, 0x00, 0x00, 0x70, 0x08, 0x04, 0x00, 0x00, 0x00, 0x89, 0x04, 0x00, 0x00, 0x30])

signals = []

# first signal
bits = 7
types = dtype( [('vals', 'u1'), ('res3', 'S4')] )
values = fromstring(data, types)
vals = values['vals']
vals = vals & (2**bits-1)
signals.append(vals)

# second signal
bits = 29
bit_offset = 7
types = dtype( [('vals', '<u4'), ('res3', 'S1')] )
values = fromstring(data, types)
vals = values['vals']
vals = vals >> bit_offset
vals = vals & (2**bits-1)
signals.append(vals)

print(signals)
```
This time I get the correct output:
```python
[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint32)]
```

**Comment by seberg** [comment]
Should recheck, but print vals right before you put it into signals and it should not be weird, then create a new `data` object before the second trial and you will see you are just confused by views, so you are changing what is inside `data` itself.

**Comment by seberg** [comment]
OK, sorry. There is areal bug here, in that it should not allow you to unset the writeable flag probably.

**Comment by danielhrisca** [comment]
You are right. I couldn't imagine that the bytes object will get changes (since it is immutable), I guess numpy interacts with it at the C level.

**Comment by njsmith** [comment]
In Python, nothing is *really* immutable if you try hard enough :-). I think @seberg is right and numpy isn't supposed to let you (easily) disable the WRITABLE flag in this case, but in general numpy does have a tendency to let you do dubious things if you insist you know better. Like when you tell it that you really want to write to an array even after it has told you that you can't. :-)

**Comment by njsmith** [comment]
IIRC when you try to set an array to WRITABLE then numpy does have some heuristics it uses to try and figure out whether the array is marked read only for some trivial reason like "someone set WRITABLE = False" like for diagonal in which case it allowed the request, or if there's some deeper reason then it denies the request.

I don't know why that heuristic is going wrong here, though, or if it should be updated.

**Comment by pv** [comment]
That unpicking creates writeable arrays that are backed by PyString buffers is wrong (this at least used to be the case, maybe it has been fixed?).

**Comment by mattip** [comment]
The comment is out of date.

**Comment by pv** [comment]
Seems we're still mutating stuff that's not mutable... https://github.com/numpy/numpy/blob/a1b3f26cbfd5d43ad70a4b75f46b417d71a55f93/numpy/core/src/multiarray/methods.c#L1779-L1786

**Comment by mattip** [comment]
Perhaps #11161 can provide a path to resolving the pickling issue using the new PEP 574 interface.
