### ISSUE TITLE
distutils.errors.DistutilsError: _numpyconfig.h not found in numpy include dirs ['/usr/lib/python3.6/site-packages/numpy/core/include']

### ISSUE THREAD

**Issue by deasmhumhna** [numpy/numpy#9449]
Trying to build a copy of mtrand.pyx with methods exposed by a local mtrand.pxd file. I call get_mathlibs() in my build script and I get the above error. Looking at misc_util.py, I see , get_mathlibs() searches all the paths returned by get_numpy_include_dirs() for "_numpyconfig.h", which is in the subfolder "numpy". But this is the default file hierarchy, no?  Regardless, shouldn't it be a recursive search of all subdirectories?

**Comment by rgommers** [comment]
`numpy.distutils` is deprecated, so we won't do anything with this anymore. I'll close this issue. `get_mathlibs` was never really for public consumption I think.

Thanks all.
