### ISSUE TITLE
scalars in result promotion

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#9460]
Am seeing strange behavior using NumPy's `where`. Namely it does not seem to properly promote types correctly when scalars are involved. An example of the behavior is shown below along with the environment used to reproduce it.

<br>

Code snippet:

<details>

```python
In [1]: import numpy as np

In [2]: np.promote_types(np.int8, int)
Out[2]: dtype('int64')

In [3]: np.promote_types(np.int8, np.int64)
Out[3]: dtype('int64')

In [4]: np.where(
   ...:     np.array([True, False]),
   ...:     np.array([1, 1], dtype=np.int8),
   ...:     0
   ...: )
Out[4]: array([1, 0], dtype=int8)

In [5]: np.where(
   ...:     np.array([True, False]),
   ...:     np.array([1, 1], dtype=np.int8),
   ...:     np.int64(0)
   ...: )
Out[5]: array([1, 0], dtype=int8)

In [6]: np.where(
   ...:     np.array([True, False]),
   ...:     np.array([1, 1], dtype=np.int8),
   ...:     np.array([0, 0], dtype=np.int64)
   ...: )
Out[6]: array([1, 0])
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: np2
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py27_0
- backports.shutil_get_terminal_size=1.0.0=py27_1
- blas=1.1=openblas
- ca-certificates=2017.4.17=0
- certifi=2017.4.17=py27_0
- decorator=4.1.1=py27_0
- enum34=1.1.6=py27_1
- ipython=5.4.1=py27_0
- ipython_genutils=0.2.0=py27_0
- libgfortran=3.0.0=0
- ncurses=5.9=10
- numpy=1.13.1=py27_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pathlib2=2.3.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.3=py27_0
- pip=9.0.1=py27_0
- prompt_toolkit=1.0.14=py27_0
- ptyprocess=0.5.2=py27_0
- pygments=2.2.0=py27_0
- python=2.7.13=1
- readline=6.2=0
- scandir=1.5=py27_1
- setuptools=36.2.2=py27_0
- simplegeneric=0.8.1=py27_0
- six=1.10.0=py27_1
- sqlite=3.13.0=1
- tk=8.5.19=1
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
```

</details>

**Comment by jcrist** [comment]
Numpy takes into account the value of the scalar when promoting dtypes for this function (and others). This is the logic in `np.result_type`.

```python
In [3]: c = np.array([True, False])

In [4]: x = np.array([1, 1], dtype=np.int8)

In [5]: np.where(c, x, 0).dtype  # smaller scalar, use array dtype
Out[5]: dtype('int8')

In [6]: np.where(c, x, 2**32).dtype  # Larger scalar requires larger dtype
Out[6]: dtype('int64')
```

**Comment by jakirkham** [comment]
I see. Though it's not exactly like we are taking `min` and `max` of arrays to determine their range and constrain their types accordingly. Still feels a bit strange.

**Comment by jcrist** [comment]
Arrays are already typed thus giving them known bounds. `np.where` won't ever result in a dtype with less precision than an input *array*, only scalars are checked for bounds.

**Comment by jakirkham** [comment]
So is a scalar. `0` is typed (i.e. normally it is an `int` so either `int64` on Unix or `int32` on Windows) and that type does already have defined bounds. IMHO this is even worse when a user has gone to the effort to create `0` as `np.int64` and then it is ignored.

**Comment by jcrist** [comment]
I agree in the case of numpy scalars that is a bit unexpected. Not sure if it's odd enough that it's worth changing IMO (backwards compat and all that). I see no issue with the current behavior for python scalars though, as they're not fixed precision.

**Comment by seberg** [comment]
Closing, this is what NEP 50 tries to fix.  The main branch is now defaulting it (although more fixes especially around handling in Python functions are probably needed).
