### ISSUE TITLE
ndarray.tobytes() shows incorrect byte order

### ISSUE THREAD

**Issue by corrigami** [numpy/numpy#9461]
Windows 10 64-bit, Python 3.6.1 (Anaconda 4.4.0), numpy 1.12.1
```
In[22]: bin(np.float16(math.radians(-293.64)).view('H'))[2:].zfill(16)
Out[22]: '1100010100100000'
In[23]: np.float16(math.radians(-293.64)).tobytes()
Out[23]: b' \xc5'
````
Out[22] represented in hex is 0xC520, while Out[23] represented in hex is 0x20C5.
The output of numpy.ndarray.tobytes() does not correctly represent a half precision float, where the expected representation is shown in Out[22].

**Comment by eric-wieser** [comment]
You're confused about endianess here. `bin` prints in big-endian, but clearly on your system, like most, bytes are stored as little-endian.

You can see this clearly with `np.int16(0x20C5).tobytes()`
