### ISSUE TITLE
numpy.vdot returns incorrect result when I use complex number

### ISSUE THREAD

**Issue by okuta** [numpy/numpy#9467]
I got incorrect result.
```python
import numpy
a = [ 1.+0.j,  2.+1.j,  3.-1.j,  4.+0.j,  5.+1.j]
b = [ 5.+0.j,  4.+1.j,  3.-1.j,  2.+0.j,  1.+1.j]

print(sum(i * j for i, j in zip(a, b)))
# (32+6j)

print(numpy.vdot(a,b))
# (38+2j)
```

**Comment by eric-wieser** [comment]
From the documentation:

> The `vdot(a, b)` function handles complex numbers differently than dot(a, b). If the first argument is complex **the complex conjugate of the first argument is used for the calculation of the dot product**.

**Comment by okuta** [comment]
Thank you!
