### ISSUE TITLE
Windows: count_nonzero returns int32 for object array only

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#9468]
It seems `count_nonzero` has a different return type depending on the data provided to it. 😕 In particular, if an `object` array is given as input `count_nonzero` returns `int32`. Otherwise `count_nonzero` returns `int64`. Seems strange to have a different return type in this one case. Is it a bug.

ref: https://ci.appveyor.com/project/daskdev/dask/build/1.0.1766#L2982

**Comment by juliantaylor** [comment]
The object code does not account for the fact that the default integer type on windows is int32. while the fast paths and paths for axis tuples does ...
