### ISSUE TITLE
vectorize-style decorator

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#9477]
Would be really handy to have a `vectorize`-like implementation that acts like a Python decorator. To be clear, `vectorize` almost satisfies that need, but one cannot use it as a decorator and pass keyword arguments. There are certainly easy ways around this, but it would be nice to have an accepted way to do this in NumPy for simple reuse.

**Comment by eric-wieser** [comment]
Can you give an example of proposed syntax?

**Comment by jakirkham** [comment]
I guess some syntax like this would be good (name is arbitrary here).

```python
@dec_vectorize(otypes=None, doc=None, excluded=None, cache=False, signature=None)
def my_func(arr):
   ...
```

This means that `dec_vectorize` (or otherwise named) would look something like this.

```python
def dec_vectorize(otypes=None, doc=None, excluded=None, cache=False, signature=None):
    def wrapper(pyfunc):
        return np.vectorize(pyfunc,
                            otypes=otypes,
                            doc=doc,
                            excluded=excluded,
                            cache=cache,
                            signature=signature)
    return wrapper
```

Though this is rough and certainly open to changes.

**Comment by eric-wieser** [comment]
Can't we just make the func argument to vectorize optional, and have it return a decorator if its ommited?

**Comment by jakirkham** [comment]
Completely agree. That sounds much better actually.

**Comment by shoyer** [comment]
You can already do this with `functools.partial`:
```python
@partial(np.vectorize, otypes=None, doc=None, excluded=None, cache=False, signature=None)
def my_func(arr):
   ...
```

I think this is a pretty reasonable solution.

> Can't we just make the func argument to vectorize optional, and have it return a decorator if its ommited?

`vectorize` is a class, so it would require jumping through some hoops (using `__new__`, I think) to make this work.

**Comment by ExpHP** [comment]
This is doable without any magical hacks, with a small amount of added complexity on the `vectorize` class.  (basically, if a function hasn't been provided, then `__call__` will perform the final bits of initialization and return `self`)

Prototype: https://github.com/ExpHP/numpy/commit/a3507d319dd39fc68bef0131df84103f102f2f15

(note: In this design, the partially-initialized decorator can only be used once.  I believe making it a pure function is possible, but this requires a bit more complexity, so I figured one-time use is a reasonable limitation for something intended for use in decorator syntax!)

**Comment by shoyer** [comment]
@ExpHP OK, that looks pretty reasonable to me. Can you measure the difference in call-time overhead for a trivial function, e.g., calling your `identity` function in a loop? I think this will add a small amount of overhead, but hopefully not too much.

(It may seem a little excessive to insist on performance here, but `vectorize` already has some performance optimizations so clearly someone cared about this.)

**Comment by ExpHP** [comment]
> @ExpHP OK, that looks pretty reasonable to me. Can you measure the difference in call-time overhead for a trivial function, e.g., calling your identity function in a loop? I think this will add a small amount of overhead, but hopefully not too much.

I'll take a look.  If it turns out to be an issue, my initial design for the implementation looked something more like this, which effectively adds zero overhead to `__call__` once it is finally initialized, but is perhaps a bit "evil" in design:

```python
class vectorize:

    def __init__(self, pyfunc=None, ...):
        ...
        # current definition of __init__
        ...
        if pyfunc:
            self(pyfunc)

    def _call_as_decorator(self, pyfunc):
        self.pyfunc = pyfunc
        self.__call__ = self._call_as_normal
        return self

    def _call_as_normal(self, *args, **kw):
        ...
        # current definition of __call__
        ...

    __call__ = _call_as_decorator
```

**Comment by ExpHP** [comment]
Hmm.  Yes, looks like the additional overhead of the `if` in `__call__` costs **~0.4s per 1,000,000 calls.**

The most trivial case I can think of is `np.vectorize((lambda x: x), otypes=['object'])` called on a scalar, which currently takes **~9.4s** per 1,000,000 calls (this puts the maximum possible slowdown at about **5%**).

```python
import numpy as np
import timeit

def measure(s):
	ts = timeit.repeat(s, globals=globals())
	print(f'{s:>20}: {min(ts):>6.3f}s ({ts})')


x = 2
xs = [0,1,2]
identity = lambda x: x
videntity = np.vectorize(identity)
vfloat    = np.vectorize(identity, otypes=['float64'])
vobject   = np.vectorize(identity, otypes=['object'])

print(np.__version__)
print(f'{"snippet":^20}  best  (all times)')
measure('videntity(x)')
measure('vfloat(x)')
measure('vobject(x)')
measure('videntity(xs)')
measure('vfloat(xs)')
measure('vobject(xs)')
```

(I benched each commit twice and alternated between them to help rule out large-scale fluctuations in background CPU load.  Times between the last a3507d3 run and the last 707f33f run differ by almost a constant 0.4s, which is the kind of difference I expected to see)
```
1.14.0.dev0+a3507d3 (vectorize-decorator)
      snippet         best  (all times)
        videntity(x): 21.768s ([22.481908158000806, 22.126309535000473, 21.767917130999194])
           vfloat(x): 10.091s ([10.213460775001295, 10.102545202998954, 10.090628451998782])
          vobject(x):  9.759s ([9.792092114001207, 9.759098587001063, 9.782961138000246])
       videntity(xs): 25.536s ([25.586909683999693, 25.535762661000263, 25.539334753999356])
          vfloat(xs): 12.238s ([12.257686156001, 12.247956515999249, 12.238118137000129])
         vobject(xs): 10.387s ([10.38699293800164, 10.402060299000368, 10.409089253000275])

1.14.0.dev0+707f33f (master)
      snippet         best  (all times)
        videntity(x): 21.030s ([21.067762631000733, 21.051139414999852, 21.029984390999743])
           vfloat(x):  9.671s ([9.67083306999848, 9.710276227000577, 9.693550022000636])
          vobject(x):  9.427s ([9.426805156001137, 9.43146521699964, 9.439738913000838])
       videntity(xs): 25.736s ([25.736185777001083, 25.75581542299915, 25.780563274000087])
          vfloat(xs): 12.114s ([12.113508943000852, 12.125795419999122, 12.124225663999823])
         vobject(xs): 10.150s ([10.17923738799982, 10.149743374000536, 10.175849371000368])

1.14.0.dev0+a3507d3  (vectorize-decorator)
      snippet         best  (all times)
        videntity(x): 21.581s ([21.581047177000073, 21.620422907999455, 21.600887791999412])
           vfloat(x): 10.104s ([10.130099814999994, 10.116891741001382, 10.104108626999732])
          vobject(x):  9.834s ([9.873765270000149, 9.833725597000011, 9.848447660000602])
       videntity(xs): 26.053s ([26.079194400001143, 26.092705879000277, 26.0533020769999])
          vfloat(xs): 12.454s ([12.458595768001032, 12.453564949999418, 12.461592382998788])
         vobject(xs): 10.570s ([10.581810928999403, 10.570412836999822, 10.583278764999704])

1.14.0.dev0+707f33f (master)
      snippet         best  (all times)
        videntity(x): 20.952s ([21.0368907510001, 20.951934971999435, 21.000456947000202])
           vfloat(x):  9.706s ([9.710992902999351, 9.715530942999976, 9.70636702900083])
          vobject(x):  9.415s ([9.44331799900101, 9.414527223998448, 9.427343850000398])
       videntity(xs): 25.608s ([25.612814928999796, 26.496048314998916, 25.60797780499888])
          vfloat(xs): 12.072s ([12.072046217999741, 12.115006013000311, 12.097886954999922])
         vobject(xs): 10.126s ([10.134322165000412, 10.126409878999766, 10.132111399001587])
```

**Comment by eric-wieser** [comment]
I think I'd prefer overriding `vectorize.__new__`~ to return a lambda if the function argument is missing, otherwise fall back on `object.__new__`

**Comment by ExpHP** [comment]
Hmmm, yes, it would make the logic cleaner, make the types cleaner, and restore the old performance. I guess the only reason not to override `__new__` at this point is just because momma said not to.

I'll throw together an alternate implementation using `__new__`.

**Comment by shoyer** [comment]
> I guess the only reason not to override __new__ at this point is just because momma said not to.

`__new__` should be used with caution, but this may be one of those cases where it makes sense :).

(If we were writing this API from scratch, `np.vectorize` could just be a function that returns a lambda or `_Vectorize` object without a public constructor. But it's too late to change that now.)

**Comment by ExpHP** [comment]
PR updated to use `__new__`.  The end result is a wonderfully simple and compact change: [these lines are the whole thing](https://github.com/ExpHP/numpy/blob/d1a5f1d319eca0920ef11848a7c110a990e15588/numpy/lib/function_base.py#L2692-L2703).  Everything else is documentation and tests.

**Comment by firegurafiku** [comment]
Why not just call it `numpy.vectorized` instead of trying to combine a Gummy bear with an assault riffle? Making decorators behave properly can be hard (keep in mind the difference between `@vectorize` and `@vectorize()`).

**Comment by bsipocz** [comment]
Reopening as https://github.com/numpy/numpy/pull/23061 has been reverted.
