### ISSUE TITLE
website: make "deprecation" more visible: red boxes

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#9478]
As discussed in #9475, numpy would likely profit from more visible deprecation notes than plain text in the docstring (see [hstack's documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html), for example).

While actual deprecation is not desirable (for one, numpy 2.0 is a long way away), it was suggested to introduce big red boxes in the style of Python itself; see, e.g., [here](https://docs.python.org/2/library/string.html#deprecated-string-functions).

![dep](https://user-images.githubusercontent.com/181628/28685251-7d313086-7307-11e7-971b-706e424892a3.png)

**Comment by eric-wieser** [comment]
Does `.. deprecated:` do the right rhing here?

**Comment by nschloe** [comment]
The function `binary_repr` has `.. deprecated:: 1.12.0` set, but I see nothing of that in [the generated docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.binary_repr.html).

`corrcoef` actually shows something in [the docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html), but it isn't very visible either.

**Comment by njsmith** [comment]
It's fairly straightforward to redefine `deprecated` to be more visible, or to define a new directive, either by modifying the numpydoc plugin or by making a little numpy-local plugin.

**Comment by seberg** [comment]
The deprecated directive now uses red boxes in the rendered docs.
