### ISSUE TITLE
DOC: code example in quickstart tutorial(NumPy v1.13) incompatible with Python 3

### ISSUE THREAD

**Issue by trencyclopedia** [numpy/numpy#9483]
hi, 
when I was reading the  NumPy v1.13 Manual, [https://docs.scipy.org/doc/numpy/user/quickstart.html]. In the "Fancy indexing and index tricks" part, I found a code like this which doesn't work on Python 3, (I think 'xrange' was already depreated in Python3)
`>>> data_max = data[ind, xrange(data.shape[1])] # => data[ind[0],0], data[ind[1],1]...
`
the correct code should be 
`>>> data_max = data[ind, np.arange(data.shape[1])] # => data[ind[0],0], data[ind[1],1]...
`
on windows 7, numpy verison 1.10.4

**Comment by matheusportela** [comment]
I just confirmed this issue on Mac OS X using Python 3.6.2 and Numpy 1.13.0. Hence I just opened a PR which solves this problem.

**Comment by rgommers** [comment]
this was fixed, closing
