### ISSUE TITLE
numpy fromstring behavior (v1.12.1,v1.13.1)

### ISSUE THREAD

**Issue by jierice** [numpy/numpy#9484]
Hi, 

I am trying to use np.fromstring to read Hex code into ascii array. However, I get the following result when I expect only 170. Does anybody happen to know where the number "194" is from? 
```
>>>import numpy as np
>>>np.fromstring('\xaa',np.uint8)
array([194, 170], dtype=uint8)
```
This is the example from the document. 
```
>>> np.fromstring('\x01\x02\x03\x04\x05', dtype=np.uint8, count=3)
array([1, 2, 3], dtype=uint8)
```
Thanks

**Comment by jaimefrio** [comment]
It works properly (returns 170 only) with 1.11.1 on Linux, which is what I have available right now.

**Comment by jierice** [comment]
I tried both 1.12 and 1.13 in Linux. They all give [194,170] instead of 170.

**Comment by eric-wieser** [comment]
This is python 3, right? Looks like \xaa is being utf8-encoded, which is as sensible a choice as any.

This doesn't happen on python 2, because quotes create `bytes` objects

**Comment by eric-wieser** [comment]
IMO, `np.fromstring(unicode)` should just throw an error - we should have been using `y`, not `s`, in `PyArg_ParseTupleAndKeywords`

Can we do that, or do we need to deprecate it first?
