### ISSUE TITLE
np.fmin:  inconsistent handling of None vs. np.nan (v 1.12.1)

### ISSUE THREAD

**Issue by erbian** [numpy/numpy#9485]
possibly the same issue as https://github.com/numpy/numpy/issues/8975 ?

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.12.0'

In [3]: np.fmin(1., None)

In [4]: np.fmin(1., np.nan)
Out[4]: 1.0
```

**Comment by eric-wieser** [comment]
This is python 2, right? In python 3, that gives

```
TypeError: unorderable types: float() <= NoneType()
```

So my question - why would you expect these to behave similarly at all? `None` and `nan` are different things.

**Comment by erbian** [comment]
yes.  this is python 2.  I see your point on `None` and `nan` being different things.  Though `np.fmax(1, None) = 1` so I would have expected `np.fmin` to behave similarly.

**Comment by eric-wieser** [comment]
As you noted, #8975 means that you're really just comparing `max(1, None)` and `min(1, None)`. It seems that in python 2, `1 > None`, which explains both the results.

**Comment by erbian** [comment]
ok we can close this issue then.

**Comment by mattip** [comment]
Closing.
