### ISSUE TITLE
Incorrect array creation when using arange

### ISSUE THREAD

**Issue by teja781** [numpy/numpy#9486]
Numpy - 1.12.1
Python - 2.7.13 | Anaconda 4.4.0
OS - CentOS, MacOS

I am run the following code to produce an array using numpy
```
import numpy as np
print np.arange(0.002, 0.021, 0.001)
```
And get the following result

`[ 0.002  0.003  0.004  0.005  0.006  0.007  0.008  0.009  0.01   0.011
  0.012  0.013  0.014  0.015  0.016  0.017  0.018  0.019  0.02   0.021]
`

The last entry should not be there. This is specific to values I have mentioned here. I do not encounter this while using other values in arange.

I was able to reproduce this in the following online ipython editor website, so I don't think this is specific to my installation.
https://www.pythonanywhere.com/try-ipython/

**Comment by eric-wieser** [comment]
Ok, now try:

```
a = np.arange(0.002, 0.021, 0.001)
assert a[-1] < 0.21
```

This is not a numpy bug, this is just how floating point numbers work.

**Comment by eric-wieser** [comment]
Duplicate of #9224, among others
