### ISSUE TITLE
discussion: use of MKL

### ISSUE THREAD

**Issue by xoviat** [numpy/numpy#9494]
Since intel's license seems to have changed to apply to users rather than distributors, would this be something that is now up for consideration?

**Comment by matthew-brett** [comment]
Basically - no - shipping MKL would mean that the Numpy binary would no longer be GPL license compatible, which might well be a problem for PyPI - see [here](https://github.com/matthew-brett/pip-legal/blob/master/pip_legal.md) for a discussion.

**Comment by xoviat** [comment]
That document references ifort, which I would not recommend using. I am talking about gfortran+MKL. This SO question said the following:

https://softwareengineering.stackexchange.com/questions/252818/distributing-gpl-licensed-software-that-optionally-links-to-non-gpl-licensed-lib

> As BLAS is effectively an API with multiple (both free and non-free) implementations, it is possible that it falls under the GPL definition of a "Standard Interface". In that case, the GPL requirements don't extend to the BLAS library that you happen to distribute with your application.

**Comment by matthew-brett** [comment]
Hmm - so that would have MKL falling under the 'System Library Exception'.  It's possible that would work, but we'd have to get a proper opinion on that.  I can add that as a question in that document I pointed to.  But I think the answer is still - no - until we have that opinion. 

> The “System Libraries” of an executable work include anything, other than the work as a whole, that (a) is included in the normal form of packaging a Major Component, but which is not part of that Major Component, and (b) serves only to enable use of the work with that Major Component, or to implement a Standard Interface for which an implementation is available to the public in source code form. A “Major Component”, in this context, means a major essential component (kernel, window system, and so on) of the specific operating system (if any) on which the executable work runs, or a compiler used to produce the work, or an object code interpreter used to run it.

https://www.gnu.org/licenses/gpl-3.0.html

**Comment by xoviat** [comment]
I have emailed the FSF regarding this issue. We'll see what they say.

**Comment by matthew-brett** [comment]
In a way it doesn't matter very much - about MKL in particular - we've already got OpenBLAS working and are intending to support it on Linux, and probably soon on OSX, so using OpenBLAS on Windows is the most attractive option.

**Comment by xoviat** [comment]
Closing for now but will update with the response from FSF
