### ISSUE TITLE
404 links in numpy.random.normal documentation

### ISSUE THREAD

**Issue by kannes** [numpy/numpy#9500]
The (Source code, png, pdf) links on the bottom of https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html are pointing to missing files.

I hope this is the right place to report this, if not, sorry but I looked around. :)

**Comment by pv** [comment]
Solution: set
plot_html_show_formats = False
plot_html_show_source_link = False
in doc/source/conf.py

**Comment by jrbourbeau** [comment]
It looks like the (Source code, png, pdf) links are broken for all of the api examples. However, the links work when I locally built the documentation on my machine. 

I can submit a PR with the fix @pv suggested
