### ISSUE TITLE
Numpy Import error for 3.6.0 - 

### ISSUE THREAD

**Issue by SriramSudharsan** [numpy/numpy#9501]
```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sriram Sudharsan\documents\visual studio 2017\Projects\TestApp1\TestApp1\TestApp1.py", line 1, in <module>
    import numpy as np
  File "C:\Program Files\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Program Files\Python36\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Program Files\Python36\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Program Files\Python36\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified procedure could not be found.

Press any key to continue . . .
```
Could anyone suggest me to get this working ? also tried with 3.6.2 with 32 bit on my 64 bit win 10 machine. Not sure about changing lib entry.
![capture](https://user-images.githubusercontent.com/30468090/28783351-0954ee42-7608-11e7-8d49-76a2b3a7706f.JPG)

**Comment by seberg** [comment]
How and where did you install numpy?

**Comment by SriramSudharsan** [comment]
it was installed with VS 2017 professional.

**Comment by SriramSudharsan** [comment]
Also i can see the library in "C:\Program Files\Python36\Lib\site-packages\numpy", rest of the libraries looks okay and work okay.

**Comment by SriramSudharsan** [comment]
Do you know any simple way to remove and avoid writing .pyc files whenever the new project was created, probably that is causing the issue ?

**Comment by seberg** [comment]
Seriously, how did you install/compile it exactly? Also, did you actually read the error message carefully? The part about `zou should not try to import numpy from its source directory`?

**Comment by SriramSudharsan** [comment]
Okay, let me explain it first, without trying anything from Visual Studio, i chose the environment (Python 3.6 (64-bit)) from drop down i choosen packages, then simply keyed in "numpy" which gave me something like this 
![image](https://user-images.githubusercontent.com/30468090/28787893-ff3d689a-7615-11e7-9c9d-1946799a8f0c.png) then if we double click on it, it automatically asks for elevated permission and installs the package automatically. 

My doubt is that, if Python try to install automatically then it should going into source directory ? if we needed to import numpy what is the correct way to do it ? 

When i install the package from VS 17 Python, it automatically goes into (C:\Program Files\Python36\Lib\site-packages\numpy). Also i'm not sure how its running from Source directory. 

To say this, i'm trying it for first time. Just learning.

**Comment by seberg** [comment]
Dunno, I could imagine that importing numpy inside the sites-packages/numpy folder might not work. Other then that you really have an issue with the installer and not with numpy itself. Someone here might be able to help you, but quite possibly not. This very much could be a problem with that Visual Studio install thingy.

**Comment by SriramSudharsan** [comment]
i can see number of issues raised for the same error with different kind a occurrence, maybe its a VS problem. Have raised with them as well. If they provide me any details, will update you here,

**Comment by njsmith** [comment]
My guess is that that's a fancy gui overlay for `pip install numpy`, and this is the issue where the latest numpy binaries were built on Python 3.6.1, and 3.6.1 has a bug that makes them not run on 3.6.0.

@charris: it looks like 3.6.2 has been out for a few weeks – do we have a plan for releasing new wheels with this fixed?

@SriramSudharsan: the quick workaround would be to either downgrade your numpy to 1.12.1, or else upgrade your python to 3.6.2.

**Comment by charris** [comment]
@njsmith Travis is running 3.6.2, but appveyor is still on 3.6.1. I suspect appveyor needs to wait until the next miniconda release, which I think will come after the next conda release. Conda is currently on 4.4.0beta2, so probably in a couple of weeks.

**Comment by rgommers** [comment]
this was resolved a long time ago, closing

**Comment by ruleGreen** [comment]
How to get this resolved? I meet this problem too. I run my code at Pycharm and the interpreter is Anaconda 3.5.0

**Comment by mattip** [comment]
@ruleGreen please open a new issue, tell us what operating system, what you did, and what error you get. This is specifically for python 3.6 on visual studio, not pycharm

**Comment by wangzhankun** [comment]
I meet the same problem on vs2017.
