### ISSUE TITLE
BUG: Indexing with `False` produces unexpected results

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#9515]
Referencing SO post https://stackoverflow.com/q/45493270/2988730.

Using `False` and `np.asanyarray(False)` yields unexpected results:
```
>>> x = np.arange(6).reshape(3, 2)
>>> x[False]
array([], shape=(0, 3, 2), dtype=int64)
>>> x[np.asanyarray(False)]
array([], shape=(0, 3, 2), dtype=int64)
```
 What is most surprising is that the result in not only a valid array, but has an extra dimension.

Doing `x[np.array([False])]` or `x[np.array([[False]])]` raises the expected `IndexError`.

Using `True` appears to have the same behavior of adding an axis:
```
>>> x[True]
array([[[0, 1],
        [2, 3],
        [4, 5]]])
>>> x[np.asanyarray(True)]
array([[[0, 1],
        [2, 3],
        [4, 5]]])
```

**Comment by madphysicist** [comment]
Resolved by https://stackoverflow.com/a/45493750/2988730. Behavior is known and expected.

**Comment by seberg** [comment]
Note that this changed "recently" so if you write stuff for older numpy versions, you cannot rely on it (for the singleton case, forcing that the boolean is an array will make it generally work).

**Comment by madphysicist** [comment]
Luckily I encountered this while working on #9514. As it turns out, the end result of this behavior is exactly the feature I want, so everything works out perfectly.
