### ISSUE TITLE
Error loading .npy files

### ISSUE THREAD

**Issue by pgromano** [numpy/numpy#9518]
Hello all,

I've been using `np.save` and `np.load` to store and load my data for some time, and recently I am unable to load any of my files. I get the error

```
NEWOBJ class argument isn't a type object
```

I'm not entirely sure what the error is, as these are not new files, and I have been able to open them  in the past without any problem.  Please let me know what information I can provide to address this issue and thank you all for the help.

**Comment by eric-wieser** [comment]
Can you give a full traceback, including the exception type? Have you switched python version between saving and loading?

**Comment by pgromano** [comment]
```
model = np.load('Analysis/MSM_c1000.npy').item()

---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-3-719d1a402129> in <module>()
----> 1 model = np.load('Analysis/MSM_c1000.npy').item()

~/Programs/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    417             else:
    418                 return format.read_array(fid, allow_pickle=allow_pickle,
--> 419                                          pickle_kwargs=pickle_kwargs)
    420         else:
    421             # Try a pickle

~/Programs/anaconda3/lib/python3.6/site-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    638             pickle_kwargs = {}
    639         try:
--> 640             array = pickle.load(fp, **pickle_kwargs)
    641         except UnicodeError as err:
    642             if sys.version_info[0] >= 3:

UnpicklingError: NEWOBJ class argument isn't a type object
```

I'm still using the same version of Python. The only thing I can think of is that I may have upgraded NumPy which is currently 1.12.1 (py36_blas_openblas_200  [blas_openblas]  conda-forge).

**Comment by charris** [comment]
Python 3.6? Python 3.6.0 and 3.6.1 are not compatible (python bug).

**Comment by charris** [comment]
Might try downgrading to Python 3.6.0 if you are running 3.6.1. The recently released Python 3.6.2 is supposed to fix the problem, but I don't know if it is available from anaconda. Mind, I don't know that that is the problem, but it is worth checking.

**Comment by pgromano** [comment]
I updated to Python 3.6.2 from 3.6.1, but still getting the same error. On my linux workstation, I'm running Python 3.6.1, and am able to load the same file. The are only two differences I can find

1.  iPython version: 6.1.0 (OSX) vs 5.3.0 (Ubuntu)
2.  NumPy version is the same, but OSX has py36_blas_openblas_200  [blas_openblas]  conda-forge, but Ubuntu has just the default conda repo.

**Comment by charris** [comment]
Hmm, hard to see how either would make a difference, but bugs are clever that way. I'm fresh out of ideas at the moment. Is there anyway you can pinpoint when the loads started to fail?

**Comment by eric-wieser** [comment]
Is your the same on both machines?

It sounds like the array you're saving has an object dtype, which is why pickle is involved.

Pickle runs your code when saving and loading. If the code changes when you do that, you're in for a bad time.

**Comment by pgromano** [comment]
@eric-wieser You were right! I had tried "fixing" a base class in my code, I've gone ahead and reverted back to the older version, and everything looks good now. Thank y'all so much for the help!
