### ISSUE TITLE
Feature request: `T` method for transposition applying to 1D vectors

### ISSUE THREAD

**Issue by jolespin** [numpy/numpy#9530]
Would it be possible to apply the `.T` syntax to 1-dimensional arrays? Or does this violate some mathematical assumption about transposition and dimensionality? 
```
x = np.linspace(0,1,5)
# array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])
x.T
# array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])
np.transpose([x])
# array([[ 0.  ],
#        [ 0.25],
#        [ 0.5 ],
#        [ 0.75],
#        [ 1.  ]])

# Future?
x.T
# array([[ 0.  ],
#        [ 0.25],
#        [ 0.5 ],
#        [ 0.75],
#        [ 1.  ]])
```

**Comment by charris** [comment]
Transpose doesn't change the number of dimensions, just reverses their order. I think another function would be needed, and the multidimensional case should also be included.

**Comment by eric-wieser** [comment]
Yeah, I think what's really needed here is a "transpose last two axes", function, in which automatic promotion from 1d to 2d seems reasonable

**Comment by njsmith** [comment]
@jolespin: Notice that `np.transpose([x])` is not the same as `np.transpose(x)`. In the first case, you're effectively doing `np.array([x])` as a (somewhat confusing and non-idiomatic) way to promote `x` to a 2-dimensional row vector, and then transposing that.

@eric-wieser: So would a 1d array be promoted to a row vector or a column vector before being transposed? If we had an operation to swap the last two axes, then it would make more sense to me if it fails when there aren't two axes two swap. In the face of ambiguity, refuse the temptation to guess, and all that.

**Comment by eric-wieser** [comment]
@njsmith You'd promote an `(N,)` array to a `(1, N)` (row) array (and then transpose to `(N,1)` (column)), as broadcasting is always done by adding singular axes to the left. Perhaps this is still too magic, but I would say the choice between row and column is clear

**Comment by eric-wieser** [comment]
Also, `np.transpose([x])` will bite you if `x` is already 2d, as that produces a 3d array.

I should draw attention to the edit to my original comment linking to a mostly-duplicate issue, #7495

**Comment by njsmith** [comment]
I don't think broadcasting is relevant here at all. Broadcasting is a way of lining up parallel loops, not a method for arbitrary munging of arrays to meet some shape requirement. Note that `np.dot` also coerces 1d arrays to 2d, but it does not use the broadcasting rule.

Also, if that's the promotion behavior you want you can already get it by explicitly writing `np.atleast_2d(x).T`, or if we had some sort of `stacked_transpose` it could be `stacked_transpose(np.atleast_2d(x))`.

**Comment by shoyer** [comment]
> I don't think broadcasting is relevant here at all. Broadcasting is a way of lining up parallel loops, not a method for arbitrary munging of arrays to meet some shape requirement.

+1

Using the model of generalized ufuncs, the "transpose last two axes" function would have the core dimensions signature `(m,n)->(n,m)`. Following the rules for generalized ufuncs, that means it should error, not broadcast when given 1D inputs. (See https://github.com/numpy/numpy/issues/8811 and https://github.com/numpy/numpy/pull/5077 for discussion.)

**Comment by mhvk** [comment]
In https://github.com/numpy/numpy/pull/8827#discussion_r138682349, @charris suggested `.M[atrix]T[ranspose]=.MT` as the name for the possible new property. With such a property, transposing a shape `(N,)` to `(N, 1)` would seem reasonable -- the implementation would then be `np.swapaxes(atleast_2d(array), -2, -1)`.

**Comment by njsmith** [comment]
Changing the operation's spelling from a function to a property does not change my opinion on the semantics :-)

**Comment by seberg** [comment]
I just merged `.mT`, so closing.
