### ISSUE TITLE
Bug on the documentation page (byteswapping)

### ISSUE THREAD

**Issue by mar-ses** [numpy/numpy#9535]
This is very minor and I'm sort of new to this, so apologies if I shouldn't have posted here. I was trying to figure out byte ordering and swapping and reading this page: https://docs.scipy.org/doc/numpy-dev/user/basics.byteswapping.html

However, there seems to be a bug.

```
big_end_str = chr(0) + chr(1) + chr(3) + chr(2)
import numpy as np
big_end_arr = np.ndarray(shape=(2,),dtype='>i2', buffer=big_end_str)
```

Doesn't work as expected giving a `TypeError: a bytes-like object is required, not 'str'` error. I think instead it should be:

```
big_end_array = bytearray([0,1,3,2])
big_end_arr = np.ndarray(shape=(2,),dtype='>i2', buffer=big_end_array)
```

or something else. To be honest I thought `chr()` was for converting ASCII to integers, so I don't even understand why it's giving the byte representation of integers in the first example (if someone knows I'd be interested in finding out). Thanks.

**Comment by eric-wieser** [comment]
That example worked in python 2, but fails in python 3, because `chr` now returns a unicode codepoint, not a byte. Your fix would work, as would `big_end_str = b'\x00\x01\x02\x03'
