### ISSUE TITLE
unravel_index: ValueError with larger integers

### ISSUE THREAD

**Issue by delete000** [numpy/numpy#9538]
```
In [23]: numpy.unravel_index(1,[4294967295,2147483647])
Out[23]: (0, 1)

In [24]: numpy.unravel_index(1,[4294967295,2147483648])
Out[24]: (0, 1)

In [25]: numpy.unravel_index(1,[4294967295,2147483649])

ValueError                                Traceback (most recent call last)
<ipython-input-25-6551b793f30b> in <module>()
----> 1 numpy.unravel_index(1,[4294967295,2147483649])

ValueError: invalid entry in index array

In [26]: numpy.__version__
Out[26]: '1.13.1'`
```
Python 2.7.12, Ubuntu 14.04. Is this a known issue?

Thanks

**Comment by delete000** [comment]
ravel_multi_index throws a different value error:

`In [27]: numpy.ravel_multi_index([0,0],[4294967295,2147483649])

ValueError                                Traceback (most recent call last)
<ipython-input-27-9dfaed49b740> in <module>()
----> 1 numpy.ravel_multi_index([0,0],[4294967295,2147483649])

ValueError: invalid dims: array size defined by dims is larger than the maximum possible size.`

Shouldn't this work with integers longer than 32 bits?

**Comment by eric-wieser** [comment]
This is about the total size of the array. Your provided `shape` results in a size that does not fit in an `ssize_t` (`int64_t`), as it is `>= 2**63`

**Comment by delete000** [comment]
Bummer. Is there any way to circumvent this limitation? I was under the impression that numpy routines work with longer integers?

**Comment by eric-wieser** [comment]
Numpy works with arrays that can actually fit in memory on your system. If you have an 128-bit system, then this will work just fine. If you don't, this operation doesn't even make any sense, does it?

**Comment by delete000** [comment]
I would like to use unravel_index to loop over multi-dimensional spaces (not necessarily array elements, although I do sometimes use a sparse-tensor format) in cases where I do not know a priori how many dimensions I have. In many cases, the total linear dimension to span is indeed greater than 2**63. I thought that one could perhaps use multi-precision integers and to make unravel_index work for these cases too, as there doesn't seem to be any resource limitation to generating larger indices. Perhaps there are technical limitations I am not aware of?

**Comment by delete000** [comment]
For example, this works just fine with integers that are much longer than 2**63:

`def idxtovec(i,l):
    """ Transforms scalar index to vector index. """
    a = zeros((len(l)+1),int)
    idxtovec = zeros((len(l)),int)
    a[0] = 1
    a[1:] = l
    for j in arange(len(l),0,-1):
        idxtovec[j-1] = (int(i-1)/prod(a[0:j])) % a[j]+1
    return idxtovec`

**Comment by delete000** [comment]
For example, this works (pardon the sloppiness):

`def idxtovec(i,l):
    a = zeros((len(l)+1),int)
    idxtovec = zeros((len(l)),int)
    a[0] = 1
    a[1:] = l
    for j in arange(len(l),0,-1):
        idxtovec[j-1] = (int(i-1)/prod(a[0:j])) % a[j]+1
    return idxtovec`

`In [43]: idxtovec(2,[2**40,2**40])
Out[43]: array([2, 1])`

**Comment by juliantaylor** [comment]
The error message could certainly be improved by using `PyArray_OverflowMultiplyList` in the right spot of the unraveling, you can probably currently produce "valid" indices via overflows which would not be good.

As for supporting arbitrary integers, I do not think that is within numpy's scope as this function is usually used for indexing arrays and is implemented in C for speed. Moving it to python on overflow is probably not really worth it as this seems to be a rather special case.
A numpy implementation would not be any better than the helper function you already wrote.

**Comment by delete000** [comment]
Thank you for the clarification, Julian. So nothing can be done on the C side to extend the range to, say, 64 bits?

**Comment by juliantaylor** [comment]
The range is already 64 bits, we would have to extend it further if you want to use flattened indices outside the 64 bit range.
We do have int128 math functions in numpy one could use, but that again has a limit. A pure python function like you have written has no limitations (except memory usage).

A pull request providing a python fallback for very large numbers could be considered though.

**Comment by psschand** [comment]
can I work on this?
I see the error message is different now
```
>>> numpy.unravel_index(1,[4294967295,2147483649])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akshay/workspace/numpy/env/lib/python3.7/site-packages/numpy/core/overrides.py", line 150, in public_api
ValueError: index 1 is out of bounds for array with size -9223372034707292161
```

**Comment by seberg** [comment]
@psschand sure, you can just start, we do not typically assign issues. As soon as you have a pull request it will show up in the issue in any case. Give us a ping if you need help with anything.
