### ISSUE TITLE
ImportError: cannot import name 'show_config'

### ISSUE THREAD

**Issue by KaifangXu** [numpy/numpy#9547]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Anaconda3\lib\site-packages\lightgbm\__init__.py", line 8, in <module>
    from .basic import Booster, Dataset
  File "F:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 14, in <module>
    import scipy.sparse
  File "F:\Anaconda3\lib\site-packages\scipy\__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
ImportError: cannot import name 'show_config'

**Comment by njsmith** [comment]
Sounds like your numpy install got corrupted somehow. Can't really say anything more without more details. We could try to debug the exact details, but honestly the most practical solution is probably to reinstall numpy.

**Comment by KaifangXu** [comment]
Reinstalled and it works, thanks!

**Comment by Mahdidrm** [comment]
hi
i have same problem, but after reinstalling it was not solve... Could you please guide me?

**Comment by mattip** [comment]
@Mahdidrm you should open a new issue and follow the instructions there:
- what version of numpy and python, where id you get them?
- post the entire traceback

**Comment by narfanar** [comment]
@mattip 

Traceback:
```py
<module>()
     10 import torch as T     11 import numpy as np---> 12 import scipy as sp
     13 from scipy import stats
     14 import opt_einsum as oe
~/anaconda3/lib/python3.6/site-packages/scipy/__init__.py in <module>()
     60 __all__ = ['test']
     61 
---> 62 from numpy import show_config as show_numpy_config
     63 if show_numpy_config is None:
     64     raise ImportError(

ImportError: cannot import name 'show_config'
```

Installed via `conda install -c anaconda -c conda-forge numpy scipy`.

Versions:
```
blas               anaconda/linux-64::blas-1.0-mkl
  intel-openmp       anaconda/linux-64::intel-openmp-2020.0-166
  libgfortran-ng     anaconda/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  mkl                anaconda/linux-64::mkl-2019.5-281
  mkl-service        anaconda/linux-64::mkl-service-2.3.0-py37he904b0f_0
  mkl_fft            anaconda/linux-64::mkl_fft-1.0.15-py37ha843d7b_0
  mkl_random         anaconda/linux-64::mkl_random-1.1.0-py37hd6b4f25_0
  ninja              anaconda/linux-64::ninja-1.9.0-py37hfd86e86_0
  numpy              anaconda/linux-64::numpy-1.18.1-py37h4f9e942_0
  numpy-base         anaconda/linux-64::numpy-base-1.18.1-py37hde5b4d6_1
  pytorch            pytorch/linux-64::pytorch-1.4.0-py3.7_cuda10.1.243_cudnn7.6.3_0
  scipy              anaconda/linux-64::scipy-1.4.1-py37h0b6359f_0
```

**Comment by kimnamu** [comment]
I had the same problem. I reinstall 1.17.4 version. Then the problem was solved.
```
sudo pip install numpy==1.17.4
```

**Comment by johndpope** [comment]
```shell
pip uninstall scipy
pip uninstall numpy
conda install scipy

```

**Comment by teddysp99** [comment]
dont create file py with numpy.py on your file directory, delete or rename the file.
