### ISSUE TITLE
_read32 TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by SidLipovits** [numpy/numpy#9549]
This seems to be a bug.

For me, array concatenation is not working as expected.  Doing a little searching, I found these:

https://github.com/llSourcell/tensorflow_demo/issues/4

https://stackoverflow.com/questions/42128830/typeerror-only-integer-scalar-arrays-can-be-converted-to-a-scalar-index

https://github.com/Paradigm4/SciDB-Py/issues/96

**Comment by njsmith** [comment]
Those links show projects adapting to an intentional change of behavior that happened back in numpy 1.12, after a deprecation period. As far as I can tell, though, none of them have anything to do with array concatenation.

Can you give an example of what you're doing and what you're getting and what you were expecting instead?

**Comment by SidLipovits** [comment]
Sure.  This is the whole script:

`import numpy as np`
`import scipy.io.wavfile as wf`
`(fs, x) = wf.read('wave.wav')`
`zrs = np.zeros(int(x.size / 2))`
`x = np.concatenate(x, zrs)`

Thank you very much for the help!

**Comment by njsmith** [comment]
Concatenate's signature is
```python
def concatenate(arrays, axis=0):
```
i.e. it takes a single positional argument which is an iterable of arrays to be concatenated. So you want `np.concatenate((x, zrs))`. Right now you're ending up saying `np.concatenate(x, axis=zrs)`, and then numpy is getting confused when it tries to convert the `zrs` array into an axis index.

**Comment by SidLipovits** [comment]
Hi Nathaniel,

Thank you for that.  Sorry to waste your time on a silly syntax mistake.  You are very kind to have answered.  :)
