### ISSUE TITLE
AttributeError when compiling f2py using mingw in Python 3 and miniconda (suggested patch)

### ISSUE THREAD

**Issue by jennirinker** [numpy/numpy#9553]
Overview:
-----------
Attempting to compile fortran90 code using mingw using f2py in Python 3 on Windows 7 via miniconda. Got an error, made a patch that works for me, but I figured I should post the issue so it can be resolved officially.

Package info:
* python 3.6.1
* conda 4.3.24
* numpy 1.13.1

Steps:
-------
a. Followed steps 1 through 4 given at [this link](https://www.scivision.co/f2py-running-fortran-code-in-python-on-windows/).
b. In Anaconda prompt: `>f2py -c myCodes.f -m myCodes`

myCodes.f:
```c     NAME OF THIS FILE - myCodes.f
c     -----------------------------

c     This subroutine prints hello World
c     on the screen

      subroutine hwd()

          print*, 'Hello World !'

      end subroutine hwd
```

Results:
--------
![image](https://user-images.githubusercontent.com/11503804/29268861-07e73ec4-80ef-11e7-96a8-f64099d6cf08.png)

Self-patch:
------------
The issue arises due to Lines 265 through 268 in numpy/distutils/mingw32compiler.py, which has
```
    lib_dirs = []
    for stem in stems:
        for folder in sub_dirs:
            lib_dirs = os.path.join(stem, folder)
```
This sets to lib_dirs as a string, which then throws an error in line 272, when we try to append to it.

I modified the code as follows and was able to compile fortran using f2py:
```
    lib_dirs = []
    for stem in stems:
        for folder in sub_dirs:
            lib_dirs.append(os.path.join(stem, folder))
```

Hopefully this patch won't affect any other functionality.

**Comment by rgommers** [comment]
Thanks @jennirinker, that looks like a clear bug. Was recently introduced in gh-8454 (present in 1.13.x only).
