### ISSUE TITLE
numpy.linalg.lstsq has possible numerical stability issues

### ISSUE THREAD

**Issue by mortonjt** [numpy/numpy#9563]
Long story short, I'm trying to implement the the [optspace algorithm](https://arxiv.org/abs/0910.5260), which basically requires a least squares calculation at each iteration of the gradient descent.

About half way through the calculation, the algorithm comes to a grinding halt -- the most likely culprit is the numerical precision of the `numpy.linalg.lstsq` function.

Below are the inputs break

```python
A = np.array([[ -4.64062339e+01,  4.54978339e+01, -6.31991340e+01,   1.07656994e+01,
   -6.76116674e+01,  9.86868513e+00,  9.91782608e+01,  -5.98546913e+00, -6.31837286e+01],
 [  2.20753729e+00, -2.16432485e+00,  3.00637292e+00,  -5.12122637e-01,
    3.21627645e+00, -4.69451809e-01, -4.71789436e+00,   2.84727831e-01, 3.00564009e+00],
 [ -8.94839454e-01,  8.77323011e-01, -1.21865262e+00,   2.07592208e-01,
   -1.30373837e+00,  1.90295313e-01,  1.91242885e+00,  -1.15416259e-01, -1.21835556e+00],
 [ -3.56931012e+00,  3.49944103e+00, -4.86092685e+00,   8.28037885e-01,
   -5.20031445e+00,  7.59044523e-01,  7.62824173e+00,  -4.60369087e-01, -4.85974195e+00],
 [ -5.62419105e+01,  5.51409776e+01, -7.65940206e+01,   1.30474605e+01,
   -8.19417787e+01,  1.19603264e+01,  1.20198827e+02,  -7.25407324e+00, -7.65753502e+01],
 [  1.99985473e+00, -1.96070766e+00,  2.72353683e+00,  -4.63942731e-01,
    2.91369287e+00, -4.25286325e-01, -4.27404031e+00,   2.57940965e-01, 2.72287294e+00],
 [  5.32142984e+01, -5.21726308e+01,  7.24708146e+01,  -1.23450901e+01,
    7.75306923e+01, -1.13164787e+01, -1.13728289e+02,   6.86357228e+00, 7.24531492e+01],
 [  2.60876955e-01, -2.55770300e-01,  3.55279803e-01,  -6.05203792e-02,
    3.80085269e-01, -5.54777303e-02, -5.57539807e-01,   3.36478708e-02, 3.55193200e-01],
 [ -1.76015507e+01,  1.72570011e+01, -2.39709769e+01,   4.08335234e+00,
   -2.56446191e+01,  3.74312128e+00,  3.76176009e+01,  -2.27024539e+00, -2.39651338e+01]]

C = np.array([  5.02048006e+01,   1.32516220e-12,   2.26130226e-12,   1.59516844e-12,
   6.03668993e+01,  -2.06501483e-13,   2.95230507e-12,  -3.74811293e-13,
   7.83282546e+01])
```
When the following is run, I get the following results
```python
>>> np.linalg.lstsq(A, C)[0]
array([ -1.26903163e+09,  -7.48892104e+08,   1.03419196e+09,
         1.99936581e+09,   1.17872085e+08,   1.40025004e+09,
        -4.58249914e+08,  -1.17404160e+09,  -8.16501289e+08])
```
This is a little mind boggling, because all of the previous iterations of the gradient descent yield the following.
```
np.array([-0.06714084,  0.06582656, -0.09143691,  0.01557588, -0.097821,  0.01427808,  0.14349175, -0.00865982, -0.09141463])
```
So I'd expect the output to be very close to the above vector.

Now -- I was able to get away around this problem, by rolling out my own least squares calculation.  Namely

```python
def leastsq(X, Y):
    """ Solves the problem Y = XB """
    inv = np.linalg.pinv(np.dot(X.T, X))
    cross = np.dot(inv, X.T)
    beta = np.dot(cross, Y)
    return beta
```
And this works as expected, so the algorithm works when `np.linalg.lstsq` is swapped out with `leastsq`.

But the outstanding question is, why is `np.linalg.lstsq` behaving this way?  Any thoughts @charris @rgommers @pv

**Comment by pv** [comment]
Most likely different default values for `rcond`.

**Comment by charris** [comment]
Agree with @pv here. I note that your replacement function is even worse from a numerical standpoint, but `pinv` has a larger default value of `rcond`. There is a pending PR, #9284, to remedy that. Apart from `rcond`, it also helps to scale the columns of the design matrix so that they have comparable norms, otherwise `rcond` loses a good bit of its utility.

**Comment by charris** [comment]
If you want to explore how this applies to your data, print out the condition numbers of the arrays that you are using in the fits. The singular values should be in descending order, so the condition number is the first sigular value divided by the last.

**Comment by mortonjt** [comment]
Thanks @charris !  Below are some of the condition numbers that are generated

```
iteration 1
1.46996148802e+19
iteration 2
8.65499439562e+18
iteration 3
3.17088654932e+20 <- things start blowing up here
iteration 4
4.711481353e+20 
```
I take it these large condition numbers indicate ill-conditioned inputs?

**Comment by charris** [comment]
The condition number is approximately the factor by which the errors in the rhs data are multiplied. Roughly speaking, the number of usable digits in the result is decreased by `log10(condition_number)`. You would like to see it around 1e7 for double precision, so your design matrix is effectively singular. That in turn indicates is that your problem is not well posed and you should review it to see how that came about.  Might print out the singular values themselves, to see how many of them are relatively small. I'm surprised that  you are getting anything useful(?) as a result.

**Comment by charris** [comment]
Note that `lstsq` "fixes" the problem by effectively ignoring some to the columns. Your replacement function, being worse, probably ignores even more columns, thus the improved "fix'.

**Comment by mortonjt** [comment]
@charris this is some seriously useful feedback.

I noticed that when I change the default `rcond` values closer to 0 (i.e. `rcond=1e-7)`, the singularity problems disappear.  I take it that lower values of rcond will cutoff more columns?

I'm going to go ahead an close this, since this doesn't look like a bug.  Thanks!

**Comment by charris** [comment]
Note that I said "effectively". The algorithm actually changes the basis, i.e., creates a new set of columnes using linear combinations of the original columns, so if you rely on `rcond` you are losing some control over what the true design matrix ends up being. Whether that matters or not is something you need to determine.

**Comment by charris** [comment]
I should change my suggested condition number a bit, < 1e12 will probably work for most things, i.e, `rcond=1e-12`.
