### ISSUE TITLE
Cant import multiarray

### ISSUE THREAD

**Issue by Vineet77** [numpy/numpy#9566]
So I was trying to use matplotlib, but there was an error with numpy, trying to import multiarray  

```
  File "C:\Program Files\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Program Files\Python36\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Program Files\Python36\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Program Files\Python36\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Program Files\Python36\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified procedure could not be found.
```

I even looked through the numpy files and could not find a multiarray file. I used pip on Visual Studio to install it. It installed version 1.13.1 of numpy. I am on Windows 10, coding on Visual Studio, using Python 3.6. 

I did look through the internet to find a solution. but now have worked for me or would apply to me.

**Comment by matthew-brett** [comment]
There was a bug in Python 3.6.1 such that packages built on that version, do not work correctly for Python 3.6.0.   See https://github.com/numpy/numpy/issues/9501 .  Can you upgrade to Python 3.6.2?  Does that help?

**Comment by pv** [comment]
@matthew-brett: that looks like a different failure, with likely a
different cause. Possible suspect is the old msvc9 compiler math library.

16.8.2017 4.05 "Matthew Brett" <notifications@github.com> kirjoitti:

**Comment by pv** [comment]
Sorry, posted that to the wrong issue...

16.8.2017 4.52 "Pauli Virtanen" <pav@iki.fi> kirjoitti:

**Comment by Vineet77** [comment]
@matthew-brett Thanks! Your solution worked!
