### ISSUE TITLE
On win32, np.absolute changes floating point control word

### ISSUE THREAD

**Issue by pv** [numpy/numpy#9567]
Consider this:
```
import numpy as np
import fpread
print("before:", hex(fpread._control87() & fpread._MCW_PC))
np.absolute(complex(np.inf, 0))
print("after:", hex(fpread._control87() & fpread._MCW_PC))
```
where [_control87](https://msdn.microsoft.com/en-us/library/e9b52ceh.aspx) returns the floating point control word. Full code in https://github.com/pv/fpread

On win32, using the current numpy 1.13.1 Python 3.6 wheels from Pypi, this prints
```
before: 0x10000
after: 0x0
```
I.e., the precision mode changes from 53-bit to 64-bit. On win64 it's 0x0 before and after. 

The mode is apparently *not* changed unless the value passed in to np.absolute is both complex-valued and contains nan or inf.

In addition to `np.absolute`, also `np.hypot(np.inf, 0)` appears to have the same issue.

I'm not sure if this is actually a bug, but it seems strange that `np.absolute` changes the precision mode. This however appears to be a source for some [fun](https://github.com/scipy/scipy/issues/7726) as it seems as if this can break gfortran optimizations and make heisenbugs appear.

**Comment by njsmith** [comment]
Yeah, numpy shouldn't be changing the precision like this. That's very weird that it is.

It looks like `np.absolute` on complex just calls `npy_hypot`, which is selected at compile time between the platform hypot or [our implementation](https://github.com/numpy/numpy/blob/663094532de48e131793faaa0ba06eb7c051ab47/numpy/core/src/npymath/npy_math_internal.h.src#L191-L219). And our implementation starts with some checks to bail out if `npy_isinf` or `npy_isnan` return true. So it sounds like either a bug in the platform `hypot`, or a bug in `npy_isinf`/`npy_isnan`, which themselves have several implementations.

I guess the next step might be to look at the disassembly for `CDOUBLE_absolute` in your build to see what it's actually doing, and then following the trail from there?

Are you using the official numpy windows wheels? Is this consistent on both Python 2 and 3? (Wondering if the different MSVC versions might affect anything.)

**Comment by xoviat** [comment]
Are the official binaries compiled with MSVC or mingwpy?

**Comment by njsmith** [comment]
MSVC. [Build scripts](https://github.com/MacPython/numpy-wheels), [Appveyor account](https://ci.appveyor.com/project/matthew-brett/numpy-wheels), [sample appveyor log containing lots of calls to cl.exe](https://ci.appveyor.com/project/matthew-brett/numpy-wheels/build/job/f6yij6lg47hgyuyr)

**Comment by pv** [comment]
The numpy-1.13.1-cp27-none-win32.whl wheel does not change the precision mode.

**Comment by xoviat** [comment]
I have MSVC 2017 installed, but here's my contribution:

```
PS C:\Users\User\Downloads> type test.c
// crt_hypot.c
// This program prints the hypotenuse of a right triangle.

#include <math.h>
#include <stdio.h>

#pragma fenv_access (on)

int main( void )
{
   double x = 3.0, y = 4.0;

   printf("FPU mode: %2.1d\n", _control87(0, 0));
   printf( "If a right triangle has sides %2.1f and %2.1f, "
           "its hypotenuse is %2.1f\n", x, y, _hypot( x, y ) );

   printf("FPU mode: %2.1d", _control87(0, 0));
}
PS C:\Users\User\Downloads> .\test
FPU mode: 589855
If a right triangle has sides 3.0 and 4.0, its hypotenuse is 5.0
FPU mode: 589855
PS C:\Users\User\Downloads>
```

**Comment by njsmith** [comment]
Odd. objdump says that the `umath.cp36-win32.pyd` in `numpy-1.13.1-cp36-none-win32.whl` is importing the `hypot` symbol from `api-ms-win-crt-math-l1-1-0.dll`. I'm not quite sure how to check if it's actually being used, though. If you have a debugger on windows then I guess you could set a breakpoint on it and see if `np.absolute` triggers it.

@xoviat: Try with a `nan` or `inf`?

**Comment by njsmith** [comment]
The 3.6 wheels are built with MSVC 2015, but MSVC 2015 and MSVC 2017 both use the `hypot` implementation from the UCRT, which is shipped as part of the operating system. So in theory MSVC 2015 and MSVC 2017 should behave the same way here. (And the 2.7 wheels are using a much older version of MSVC that doesn't use the UCRT.)

**Comment by xoviat** [comment]
Jackpot:

```
FPU mode: 589855
If a right triangle has sides inf and 4.0, its hypotenuse is inf
FPU mode: 786463
```

**Comment by xoviat** [comment]
@brettcannon Who should we contact about this?

**Comment by pv** [comment]
I guess Numpy should just blacklist hypot on 32-bit MSVC? If so, done in gh-9574. It seems hypot() is indeed the only thing that does this stuff, as far as the test suite can see.

**Comment by zooba** [comment]
Sounds reasonable. The implementation of `hypot` certainly saves and restores the control word when there is an SNaN, both arguments are zero, or there's a special value that isn't inf, SNaN or QNaN. Without digging into 20+ year old macros I wouldn't be able to figure out why it flips that bit though, and blacklisting sounds like the right approach anyway.

**Comment by pv** [comment]
Does someone want to submit a MSVC bug report (I'm not up for that.)? Do they take bugreports?

**Comment by zooba** [comment]
Yep, we do. I'll email the team with a link to this issue.

**Comment by pv** [comment]
Also `cabs*` seem to have this issue.
