### ISSUE TITLE
wrap DSYTRD/ZHETRD

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#9584]
Given a symmetric matrix `A`, I need to retrieve the triangular matrix `T` generated from `A` by an orthogonal similarity transformation
```
Q**T * A * Q = T
```
There are LAPACK methods for this, [DSYTRD](http://www.netlib.org/lapack/explore-3.1.1-html/dsytrd.f.html)/[ZHTRD](http://www.netlib.org/lapack/explore-3.1.1-html/zhetrd.f.html), but unfortunately, they are not yet wrapped by numpy.

What would be required to do so?

**Comment by njsmith** [comment]
Scipy's wrapping of LAPACK is sometimes more complete, because scipy requires a real LAPACK while numpy has to have fallbacks for when LAPACK is unavailable. So you might want to check there first.

**Comment by nschloe** [comment]
I see. I'll move this report over to scipy.
