### ISSUE TITLE
broadcasting problem for list argument in`np.sum` and `np.prod`

### ISSUE THREAD

**Issue by tondieker** [numpy/numpy#9585]
```
np.sum([np.ones((3,5)), np.ones((3,5))], axis=0)
array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

np.sum([np.ones((3,5)), np.ones((1,5))], axis=0)
array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

np.sum([np.ones((3,5)), np.ones((3,1))], axis=0)
Traceback (most recent call last):
  File "/Users/ton/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-44-f9ea6aa5100e>", line 1, in <module>
    np.sum([np.ones((3,5)), np.ones((3,1))], axis=0)
  File "/Users/ton/anaconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1834, in sum
    out=out, **kwargs)
  File "/Users/ton/anaconda/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _sum
    return umr_sum(a, axis, dtype, out, keepdims)
ValueError: could not broadcast input array from shape (3,5) into shape (3)

np.__version__
'1.13.0'

```
The same problem appears if I have more than two arrays in the list. It also appears for `np.prod`.

There are obvious workarounds but I thought this may be a bug.

**Comment by eric-wieser** [comment]
If you're using a list, plain old `sum` is probably faster anyway - otherwise you waste time stacking all the input arrays anyway.

I'm away from an interpreter - can you print `np.array([np.ones((3,5)), np.ones((1,5))])`? I suspect either that is your problem, or that it produces an object array and there is something strange going on.

**Comment by seberg** [comment]
Yeah, numpy decides it should be a 2D array result probably (2x3) and then things go bad.

**Comment by seberg** [comment]
Frankly, one of those things we probably just need the `dtype=object, ndim=1` arguments or so to make object dtype arrays creation sane.

**Comment by tondieker** [comment]
I was actually under the impression that using `np.sum` on a list (like I did) _avoids_ the creation of a new numpy array. I thought it was the most efficient way to do it since I also assumed that it only has to allocate an output array, no intermediate arrays. Sounds like I was wrong on at least the first one.

`np.array([np.ones((3,5)), np.ones((1,5))])`
gives an array of shape `(2,)`:
`np.array([np.ones((3,5)), np.ones((1,5))])
array([ array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]]),
       array([[ 1.,  1.,  1.,  1.,  1.]])], dtype=object)
`

If I use `sum` then it works as expected. I suppose it probably avoids allocating intermediate arrays as well.

In what kinds of situations would you want `np.sum` to accept a list? If that would have thrown an error of some kind then I would have probably tried `sum`.

**Comment by tondieker** [comment]
To be clear: when I speak about "intermediate arrays" I'm thinking of having a list with many elements, not just two as in this MWE.

**Comment by ExpHP** [comment]
> I was actually under the impression that using np.sum on a list (like I did) avoids the creation of a new numpy array. I thought it was the most efficient way to do it since I also assumed that it only has to allocate an output array, no intermediate arrays.

@tondieker alas, it does not work that way.

```python
import resource
import numpy as np


def max_memory():
	return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024 / 1024
def show_max_memory(s=None):
	print(f'max memory usage: {max_memory():.03f} GiB - {s}')

row = np.zeros((1000,))
show_max_memory("after creating ndarray of shape (1000,)")

print()

lst = [row]*10000
show_max_memory("after creating the python list [arr]*10000")
np.sum(lst)
show_max_memory("after np.sum(lst)")

print()

lst = [row]*50000
show_max_memory("after creating the python list [arr]*50000")
np.sum(lst)
show_max_memory("after np.sum(lst)")
```

```
max memory usage: 0.024 GiB - after creating ndarray of shape (1000,)

max memory usage: 0.024 GiB - after creating the python list [arr]*10000
max memory usage: 0.098 GiB - after np.sum(lst)

max memory usage: 0.098 GiB - after creating the python list [arr]*50000
max memory usage: 0.397 GiB - after np.sum(lst)
```

Each line prints the maximum amount of memory used by the application up to that point.  Here, we see that `np.sum` on a list with many O(1)-memory references to the same array suddenly results in large max memory usage; indicating the creation of a large temporary array.

**Comment by ExpHP** [comment]
P.S:  Output if `np.sum` is changed to `sum`:

```
max memory usage: 0.024 GiB - after creating ndarray of shape (1000,)

max memory usage: 0.024 GiB - after creating the python list [arr]*10000
max memory usage: 0.024 GiB - after sum(lst)

max memory usage: 0.024 GiB - after creating the python list [arr]*50000
max memory usage: 0.024 GiB - after sum(lst)
```

We see that no large temporaries are built here.  `sum` is just a python builtin, which calls `+` on each pair of arguments, so it will construct temporaries for the output of each `+`.

If you want to have summation without large memory usage along other axes, you can also try doing `.sum(axis=axis)` on each array prior to calling the builtin `sum()`.

**Comment by tondieker** [comment]
@ExpHP: that's super neat, thanks for sharing! 

> `sum` is just a python builtin, which calls `+` on each pair of arguments, so it will construct temporaries for the output of each `+`

This is exactly what I was hoping `np.sum` avoids. There is no need for temporaries here, I was expecting that `np.sum` would do something like this with the input `lst`:

```
res = np.zeros(figure_out_shape(lst))
for a in lst:
    res += a
```

Here `figure_out_shape` is of course mindful of broadcasting. Of course I can just do it this way without using `np.sum`.

**Comment by seberg** [comment]
Closing the issue.  Both of these are due to the weird "ragged" array behaviour of `np.asarray()` (which is implicitly called by `np.sum` and `np.prod`.  All odder cases now give a `VisibleDeprecationWarning` to warn about the ragged nested sequences.  So the confusing cases will lead to more easily understandable errors in the future.

The side issue that `sum(list_of_arrays)` will typically be faster than `np.sum(list_of_arrays)` is somewhat expected.
