### ISSUE TITLE
numpy.gradient doesnt take list of array as an arguement

### ISSUE THREAD

**Issue by SRattan16** [numpy/numpy#9587]
Hello everyone,
Im having trouble in running a basic code using numpy.gradient. This package used to work for me before but it seems it doesnt like a list of evenly spaced array or list as an argument anymore:
x = [1,2,3,4,5,6,7,8]
y= [1,1,1,1,1,1,1,1]
np.gradient(x,y)
Traceback (most recent call last):

  File "<ipython-input-15-ad0b1a67ff5c>", line 1, in <module>
    np.gradient(x,y)

  File "/Users/SRattan/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1598, in gradient
    raise ValueError("distances must be scalars")

ValueError: distances must be scalars

Any help will be appreciated.

**Comment by eric-wieser** [comment]
What version of numpy?

**Comment by analoguenative** [comment]
Has there been any resolution to this?  I am also using numpy version 1.12.1, about which I don't have a choice for now due to workplace restrictions.  I obtain the same behavior as in the example given.  If np.gradient is not available due to the ValueError, is there a next-best option?

**Comment by eric-wieser** [comment]
Works fine on 1.14.2:
```
In [107]: x = [1,2,3,4,5,6,7,8]
     ...: y= [1,1,1,1,1,1,1,1]
     ...: np.gradient(x,np.sum(y))
     ...: 
Out[107]: array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125])
```

**Comment by eric-wieser** [comment]
Works fine on 1.14:
```
In [109]: x = [1,2,3,4,5,6,7,8]
     ...: y= [1,1,1,1,1,1,1,1]
     ...: np.gradient(x,np.cumsum(y))
     ...: 
Out[109]: array([1., 1., 1., 1., 1., 1., 1., 1.])
```

**Comment by eric-wieser** [comment]
Note that I use `cumsum` there since gradient expects an array of values, not an array of diffs, and taking a gradient where all the "x" values are 1 gives nan
