### ISSUE TITLE
np.bmat cause unexpected behaviour in reshape and squeeze

### ISSUE THREAD

**Issue by JialongJiang** [numpy/numpy#9598]
![squeeze](https://user-images.githubusercontent.com/30475801/29669548-cfe3a06a-88b1-11e7-8337-4d670e8704ef.PNG)

The shape of the bmat has some unexpected behaviour. sum, reshape, squeeze cannot function. np.copy to another array can solve this problem. Minimal code is shown below
**************
import numpy as np

test = np.bmat([[np.eye(3), np.zeros((3, 8))], [np.zeros((8, 3)), np.eye(8)]])
ttest = np.sum(test, 1)
print(ttest.shape)
print(np.squeeze(ttest).shape)
print(ttest.reshape((11,)).shape)

**Comment by pv** [comment]
numpy.bmat produces numpy.matrix results. You can use
numpy.block_matrix instead. (or convert numpy.matrix to numpy.array by
np.bmat(...).A )
