### ISSUE TITLE
array_dealloc leaks reference count for object arrays or updateifcopy

### ISSUE THREAD

**Issue by pv** [numpy/numpy#9600]
Running the following script on a python3.6-debug build:
```
import sys, numpy as np, gc
print("Numpy version:", np.__version__)
f = np.frompyfunc(lambda x: x, 1, 1)
count = 5000
for outer in range(4):
    gc.collect()
    start = sys.gettotalrefcount()
    for j in range(count):
        k = f(j)
    gc.collect()
    delta = sys.gettotalrefcount() - start
    print("[{}] Leaked refcount: {}".format(outer, delta))
    print("[{}] Per iteration: {}".format(outer, delta / count))
```
prints
```
Numpy version: 1.14.0.dev0+707f33f
[0] Leaked refcount: 15006
[0] Per iteration: 3.0012
[1] Leaked refcount: 15000
[1] Per iteration: 3.0
[2] Leaked refcount: 15000
[2] Per iteration: 3.0
[3] Leaked refcount: 15000
[3] Per iteration: 3.0
```

When numpy gets pytest support, it could be interesting to ensure it gets a clean report from https://pypi.python.org/pypi/pytest-leaks so that it's possible to find reference leaks also in packages depending on numpy without confounding factors.

**Comment by pv** [comment]
The reason is that in `array_dealloc` there is a `Py_INCREF(self)` for object arrays:
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arrayobject.c#L421
That looks a bit nasty. I wonder if there's a right way to do this.

In Python >=3.4 there's [tp_finalize](https://docs.python.org/3.7/c-api/typeobj.html#c.PyTypeObject.tp_finalize) which could be a better place to do things like this that need the full API.

**Comment by mattip** [comment]
this should be fixed by pr #9639

**Comment by pv** [comment]
I don't think the updateifcopy changes have to do with this. The
example in the issue description still leaks refcounts.

**Comment by mattip** [comment]
My comment was about the `Py_INCREF` on [line 492](https://github.com/numpy/numpy/blob/07d590c980edb05f1ef67cd27fff2ffe2d9c6047/numpy/core/src/multiarray/arrayobject.c#L492), there is another one on [line 513]https://github.com/numpy/numpy/blob/07d590c980edb05f1ef67cd27fff2ffe2d9c6047/numpy/core/src/multiarray/arrayobject.c#L513), which may be the one from @pv 's comment above. The file changed in the mean time, which means the link is not accurate

**Comment by seberg** [comment]
Just in case anyone is insterested in it. I got the test running with the pytest-leaks, tracking down all the small refcount issues might be a pretty annoying project though.

**Comment by seberg** [comment]
Object arrays do not leak anymore, and the same is true for correct usage of `writebackifcopy`, since it should be resolved before the dealloc (the warning paths still leak admittedly). The example above does not leak anymore, so closing.
