### ISSUE TITLE
use with statement to open/close files.

### ISSUE THREAD

**Issue by srinivasreddy** [numpy/numpy#9612]
Now that with statement - context managers has become a thing. Please feel free to use them whenever we need to read/write to file.

You can find the files here - https://lgtm.com/projects/g/numpy/numpy/alerts/?mode=tree&severity=warning&rule=10030095

**Comment by eric-wieser** [comment]
It looks like LGTM might not have this rule any more? That link seems not to point to anything any more.

**Comment by tylerjereddy** [comment]
hmm... I know there was some discussion over in SciPy about eventually adopting the custom checks interface for LGTM, so we may be able to add what we want eventually.

I think Ralf was rightly concerned about maintenance burden for that though--holding off until i.e., LGTM allows the config files to be shared between multiple projects in the Python ecosystem.

**Comment by eric-wieser** [comment]
I think this is something that used to be caught by lgtm but no longer is. Perhaps worth summoning a lgtm developer.

**Comment by tylerjereddy** [comment]
cc @jhelie

**Comment by tylerjereddy** [comment]
I think Jean was / is working for LGTM so I've pinged him. I just meant that we could maybe reactive checks we need, eventually, if it is an issue.

**Comment by jhelie** [comment]
I still am, thanks for pinging me :)
I think the query in question is this [one](https://lgtm.com/rules/10030095/). It is run but not displayed by default. As described [here](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file#queries) you can make it visible by adding the following to your .lgtm.yml file:
```
queries:
- include: py/file-not-closed
```

Regarding for share-able custom [query packs](https://lgtm.com/help/lgtm/about-queries#what-are-query-packs): yes this is still work in progress, and I'd be very interested to hear some of the concerns that were raised and which workflow would work best for you so please do let us know!

**Comment by eric-wieser** [comment]
Is there an easy way to get a list of all the queries that are disabled by default, so that we can decide which to enable?

**Comment by aibaars** [comment]
@eric-wieser I'm afraid there is no direct way to get exactly what you want. 

You can find all python queries as follows: https://lgtm.com/search?q=language%3Apython&t=rules and check the value of `Displayed by default?` on each of the linked query details pages.

Another approach would be to enable all queries in `.lgtm.yml`:
```
queries:
- include: "*"
```
That would make all alerts visible on the Alerts tab. You could have a look at them and decide which queries you don't care about and exclude them. For example:
```
queries:
- include: "*"
- exclude: py/unused-import 
```
Note that changes to the `lgtm.yml` may take up to 24 hours to be picked up. Just ping me so I can give LGTM a little nudge to speed things up.

**Comment by eric-wieser** [comment]
Can I make a feature request to allow me to perform such a search? I think it's probably not worth the churn out temporarily committing the all-inclusive yaml to master to answer that question right now, and I imagine other projects feel the same way

**Comment by aibaars** [comment]
Yes you may, thanks for the feature request! In the mean time this should be the list of hidden python queries:

ID | Description
-- | --
py/hardcoded-credentials | Credentials are hard coded in the source code of the application.
py/jinja2/autoescape-false | Using jinja2 templates with 'autoescape=False' can cause a cross-site scripting vulnerability.
py/request-without-cert-validation | Making a request without certificate validation can allow man-in-the-middle attacks.
py/undefined-placeholder-variable | Using a variable before it is initialized causes an exception.
py/uninitialized-local-variable | Using a local variable before it is initialized causes an UnboundLocalError.
py/exit-from-finally | Using a Break or Return statement in a finally block causes the Try-finally block to exit, discarding the exception.
py/file-not-closed | Opening a file without ensuring that it is always closed may cause resource leaks.
py/import-of-mutable-attribute | Importing the value of a mutable attribute directly means that changes in global state will not be observed locally.
py/overly-permissive-file | Allowing files to be readable or writable by users other than the owner may allow sensitive information to be accessed.
py/overwritten-inherited-attribute | Assignment to self attribute overwrites attribute previously defined in subclass or superclass __init__ method.
py/commented-out-code | Commented out code causes visual clutter as it is neither code nor comment.
py/cyclic-import | Module forms part of an import cycle, thereby indirectly importing itself.
py/duplicate-function | There is another identical implementation of this function. Extract the code to a common file or superclass to improve sharing.
py/empty-except | Except doesn't do anything and has no comment
py/ineffectual-statement | A statement has no effect
py/mixed-returns | Mixing implicit and explicit returns indicates a likely error as implicit returns always return 'None'.
py/mixed-tuple-returns | A function that potentially returns tuples of different lengths may indicate a problem.
py/mostly-duplicate-class | More than 80% of the methods in this class are duplicated in another class. Create a common supertype to improve code sharing.
py/mostly-duplicate-file | There is another file that shares a lot of the code with this file. Merge the two files to improve maintainability.
py/mostly-similar-file | There is another module that shares a lot of the code with this module. Notice that names of variables and types may have been changed. Merge the two modules to improve maintainability.
py/not-named-cls | Using an alternative name for the first argument of a class method makes code more difficult to read; PEP8 states that the first argument to class methods should be 'cls'.
py/old-style-octal-literal | Octal literal with a leading 0 is easily misread as a decimal value
py/overly-complex-delete | __del__ methods may be called at arbitrary times, perhaps never called at all, and should be simple.
py/print-during-import | Using a print statement at module scope (except when guarded by if __name__ == '__main__') will cause surprising output when the module is imported.
py/unnecessary-lambda | A lambda is used that calls through to a function without modifying any parameters
py/unused-global-variable | Global variable is defined but not used

**Comment by mattip** [comment]
PR welcome to add to `.lgtm.yml`
```
queries:
- include: py/file-not-closed
```
and check the LGTM analysis

**Comment by psschand** [comment]
@mattip @seberg 
surprisingly all checks passed (even file-not-closed check)
is it good to go?

**Comment by jhelie** [comment]
@mattip @seberg Only catching up with this now but if you look at the [Queries tab](https://lgtm.com/projects/g/numpy/numpy/queries/?pack=com.lgtm%2Fpython-queries) you should see that results for the `py/file-not-closed` query are now displayed - and you can see them [here](https://lgtm.com/projects/g/numpy/numpy/alerts/?mode=list&id=py%2Ffile-not-closed).

> Is there an easy way to get a list of all the queries that are disabled by default, so that we can decide which to enable?
@eric-wieser hopefully this new Queries page now makes it easier to address your question

**Comment by mattip** [comment]
Cool! It seems I closed this too soon, there are a bunch of files left dangling. Reopening
