### ISSUE TITLE
arange recomputation of step variable may lead to problems with floating point

### ISSUE THREAD

**Issue by MSeifert04** [numpy/numpy#9616]
In the discussion in a recent [StackOverflow question](https://stackoverflow.com/q/45907088/5393381) I was made [reminded that the `step` variable isn't passed verbatim](https://stackoverflow.com/questions/45907088/how-does-numpys-arange-differ-from-this-custom-function/45907351?noredirect=1#comment78773324_45907351) to the [`@NAME@_fill`](https://github.com/numpy/numpy/blob/v1.13.1/numpy/core/src/multiarray/arraytypes.c.src#L3556-L3578) function. It is computed by subtracting the second element from the first element. While that's no problem for integers it can lead to reduced precision with `float`s.

For example:

```
import numpy as np

np.diff(np.arange(1e17, 1e17+50, 1))
```

gives 

```
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

because the step was changed to `0` - because `1e17+1 == 1e17`, it would still be weird if the step was passed through verbatim but at least more precise.

**Comment by FrozenBob** [comment]
Or, for a less extreme example,

```
In [94]: numpy.arange(0, 1000, 0.1)[-1]
Out[94]: 999.90000000000009

In [95]: numpy.arange(100, 1000, 0.1)[-1]
Out[95]: 999.89999999994882
```

the precision loss in recomputing the step as `(100+0.1)-100` causes substantial rounding error in `numpy.arange(100, 1000, 0.1)` compared to `numpy.arange(0, 1000, 0.1)`.

Of course, using a floating-point step at all with `arange` is usually a bad idea - `linspace` is usually a superior option, and it doesn't suffer step recomputation issues. Still, the `arange` implementation could do better than it currently does.

**Comment by seberg** [comment]
Probably, but it will never be as good as linspace even if it was better, and then the question whether we can change it without disrupting other programs is unclear….

I would rather see trying to hash out a `save` step argument again, though not sure if it can be done in a pretty way, mine one try was not very pretty.

**Comment by melissawm** [comment]
It is clear that np.arange should not be used with a floating point step, but is the enhancement suggested here actionable? If so, it would probably be a better idea to close this issue and open a new one with the suggested feature.
