### ISSUE TITLE
f2py: Fortran preprocessor falsely disallows arrays of dimension 0

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#9617]
Moved from https://github.com/scipy/scipy/issues/7801.

---

This came up in the context of https://github.com/scipy/scipy/pull/7780: When allocating a Fortran vector of length 0 in `scipy/linalg/flapack.pyf.src`, the preprocessor bails out with
```
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```
The value `0`, however, is a perfectly legal array length in Fortran.
```fortran
program main
  real, dimension(0) :: array
end program
```

**Comment by ilayn** [comment]
I think zero sized arrays are introduced relatively recently in Fortran or I'm remembering quite wrongly

**Comment by nschloe** [comment]
From a 1996 forum post http://computer-programming-forum.com/49-fortran/a259c35696bffc67.htm:

> Zero-sized arrays are legal in Fortran 90 in all circumstances, including   
allocate statements. Further details are in Section 6.2 of our "Fortran 90 
Explained".
