### ISSUE TITLE
Linalg norm for 1D arrays

### ISSUE THREAD

**Issue by benoitrosa** [numpy/numpy#9622]
Hi,

Trying to optimize a code of mine, I noticed that numpy was spending a significant amount of time computing vector (i.e. 1D numpy array) norms. Looking a bit in detail, I realized that for 1D vectors and the L2 norm, np.linalg.norm is not performing the best it could do. Calling np.sqrt(np.inner(A,A)), where A is a 1D numpy array, is significantly faster. 

Consider the following code : https://gist.github.com/benoitrosa/5087120222c38a6646dfc8e04cad5d1d

For all tested sizes of 1D vectors, the Norm() function is approximatively 50% faster than np.linalg.norm. For 2D and 3D vectors, it is a tiny bit slower. That's probably due to the overhead in the Norm function (i.e. testing for array number of dimensions). 

I know this applies only for 1D arrays and for the L2 norm, but I feel like this is a common use for many numpy users. Many there is room for improvement ? Or maybe, if that's too specific for integrating into the numpy function, could it be specified in the doc that taking the square root of the inner product for 1D arrays is significantly faster than using np.linalg.norm ?

For the record, Ubuntu 16.04 x64 with numpy 1.13.0 on python 2.7.12 were used for testing.

**Comment by eric-wieser** [comment]
In general, I wonder if we could do better by exposing the `inner1d` ufunc that we use in the ufunc tests, and then using that in norm - which might speed up the along-axis 1d norm as well.

**Comment by eendebakpt** [comment]
This has been solved with recent PRs. I think this can be closed. @seberg 

Output on my system:
```
n =  10
1D array
ratio time(Norm)/time(np.linalg.norm) =  0.8673939707937021
2D array
ratio time(Norm)/time(np.linalg.norm) =  1.0654506678473339
3D array
ratio time(Norm)/time(np.linalg.norm) =  1.2746391545068125

n =  15
1D array
ratio time(Norm)/time(np.linalg.norm) =  0.8531931315323401
2D array
ratio time(Norm)/time(np.linalg.norm) =  1.0928215498169638
3D array
ratio time(Norm)/time(np.linalg.norm) =  1.0193767577132902

n =  20
1D array
ratio time(Norm)/time(np.linalg.norm) =  0.9621976596903647
2D array
ratio time(Norm)/time(np.linalg.norm) =  1.132455581052208
3D array
ratio time(Norm)/time(np.linalg.norm) =  0.9229424390051727

n =  25
1D array
ratio time(Norm)/time(np.linalg.norm) =  0.7995956190924826
2D array
ratio time(Norm)/time(np.linalg.norm) =  1.3395246341221767
3D array
ratio time(Norm)/time(np.linalg.norm) =  0.9826553325589223

n =  30
1D array
ratio time(Norm)/time(np.linalg.norm) =  0.9640864538804268
2D array
ratio time(Norm)/time(np.linalg.norm) =  1.1027938000442814
3D array
ratio time(Norm)/time(np.linalg.norm) =  0.9186856966277359

n =  35
1D array
ratio time(Norm)/time(np.linalg.norm) =  0.9598238422591521
2D array
ratio time(Norm)/time(np.linalg.norm) =  1.086816339082723
3D array
ratio time(Norm)/time(np.linalg.norm) =  1.0107915118685755

n =  40
1D array
ratio time(Norm)/time(np.linalg.norm) =  0.9601146917723412
2D array
ratio time(Norm)/time(np.linalg.norm) =  1.072926786985567
3D array
ratio time(Norm)/time(np.linalg.norm) =  1.0880486541774161

n =  45
1D array
ratio time(Norm)/time(np.linalg.norm) =  1.0646616736225973
2D array
ratio time(Norm)/time(np.linalg.norm) =  1.117463594029618
3D array
ratio time(Norm)/time(np.linalg.norm) =  1.0668896467532096
```

**Comment by seberg** [comment]
Cool, thanks @eendebakpt lets close this since there are significant improvements.  The idea of using `inner1d` or similar ufuncs may still be worthwhile, but is indeed a different issue/project.
