### ISSUE TITLE
Why is fancy indexing slower than flattening + flat indexing?

### ISSUE THREAD

**Issue by kohr-h** [numpy/numpy#9635]
I recently noticed that it is faster to flatten a list of index arrays and then index the flat array than to use the list directly for indexing. Why would that be the case?
```python
>>> arr = np.random.rand(100, 100, 100)
>>> indcs_multi = [np.random.randint(0, n - 1, size=int(1e6)) for n in arr.shape]
>>> indcs_flat = np.ravel_multi_index(indcs_multi, arr.shape)
>>> np.array_equal(arr[indcs_multi], arr.ravel()[indcs_flat])
True

>>> %timeit arr[indcs_multi]
17 ms ± 38.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

>>> %timeit arr.ravel()[indcs_flat]
3.32 ms ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

>>> %timeit np.ravel_multi_index(indcs_multi, arr.shape)
6.33 ms ± 5.57 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Playing a bit around with sizes, the multi-index variant runs between 50 % and 75 % longer for medium (~75 %) to large (~50 %) sizes. For small arrays, `ravel_multi_index` dominates runtime.

**Comment by seberg** [comment]
Dunno, there is always room for making things faster. Might be indexing is iterating twice, once to check and once to pick (which does not happen in the flat case that is optimized a lot). Which is great if you have broadcasting going on and does not need a temporary, but would slow it down here in comparison. Add some smaller things and you probably get in the right ballpark.

**Comment by kohr-h** [comment]
Hm, so perhaps some special cases could be optimized for.

Where is `ndarray.__getitem__` defined exactly? I have a hard time finding it with all the C code and name mangling going on.

**Comment by seberg** [comment]
The setup stuff is all in `.../mapping.c`, the lowlevel loop (there are two version, one from 1D, and one with a few different cases for higher dimensionality) is in `lowlevel_strided_loops.c.src` (or something like that, too lazy to look it up).

It is a long and non-trivial code file, so feel free to ask me/us questions, there is a MapIter object which basically is in charge of non-trivial advanced indexing.

**Comment by seberg** [comment]
It is plausible that you can speed up the lowlevel loop itself also (or add, yet another, faster path). But my guess is that this is mostly due to the double iteration avoiding temporaries and unnecessary checks if the index arrays have different shapes, so there is likely not much of a point.

Part of it might just be that we have "trivially iterable" fast paths everywhere, but obviously those do not exist for generic N-Dimensional code.

**Comment by kohr-h** [comment]
I'll make an attempt at understanding the loop code.
What I have in mind as fast path would look in Python like this (paraphrased):
```python
if isinstance(indices, list):
    if (all(isinstance(i, np.ndarray) and
            i.ndim == 1 and
            i.size == indices[0].size
            for i in indices):
        # Fast multi-index path
    else:
        # Current path
```
Give or take conversion of array-like objects.

**Comment by kohr-h** [comment]
From my understanding of the code I can think of the following rough implementation:
- Add a case similar to [this one](https://github.com/numpy/numpy/blob/8ed1770a8ca968388eacd5d96b8068b272fb47b7/numpy/core/src/multiarray/mapping.c#L1685-L1724) for the case in question (`array.ndim` 1D index arrrays of equal size).
- Add some `mapiter_trivial_get` variant (or amend existing) for this kind of index. This will likely require some extra checks, size info and stuff.
- The simplest implementation of the preparation steps (e.g. `PyArray_PREPARE_TRIVIAL_PAIR_ITERATION`) in the `mapiter` would be pairwise using the existing implementation, i.e. `result, ind[0]`, `result, ind[1]` etc. That seems simply like adding an outer loop [here](https://github.com/numpy/numpy/blob/25a6dfbbebb1d92e0e402aed7c8f11e4f5d3bc5b/numpy/core/src/multiarray/lowlevel_strided_loops.c.src#L1397-L1420).
- The get/set loop [here](https://github.com/numpy/numpy/blob/25a6dfbbebb1d92e0e402aed7c8f11e4f5d3bc5b/numpy/core/src/multiarray/lowlevel_strided_loops.c.src#L1435-L1471) would need an inner loop over the index arrays.

Any difficulty I'm missing? Hardships to be expected with the C API?

Most importantly: given the expected speedup, is this worth the extra code and effort?

**Comment by kohr-h** [comment]
Obviously haven't had time to do this. I'll close, and if anybody wants to have a go, reopen or make a new one.
