### ISSUE TITLE
importing multiarray fails

### ISSUE THREAD

**Issue by honggyukim** [numpy/numpy#9655]
Hi folks,

I would like to import numpy in C program but got some problems importing it.  The problem is that my C program `dlopen`s `libpython2.7.so` library and finds some functions using `dlsym`. Then it calls other python function.

In this environment, I would like to import numpy but the below statement in `numpy/core/__init__.py` fails.
```
try:
    from . import multiarray
except ImportError:
    msg = """
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
"""
    raise ImportError(msg)
```
I've investigate the problem and found that multiarray is not `.py` but `.so` file. In this situation, how can I properly import numpy `.so` modules?

I appreciate all your help!

Thanks,
Honggyu

**Comment by eric-wieser** [comment]
How did you install numpy, and have you tried reinstalling it? Importing `.so` files should "just work".

**Comment by honggyukim** [comment]
@eric-wieser Thanks for your comment. I installed it using `$ sudo apt install python-numpy` in my Ubuntu system. I also tried installation using `pip` but got the same error.

**Comment by honggyukim** [comment]
If I import numpy as follows, it just works.
```
$ python -c 'import numpy`
```
But the problem is importing it in my C program that loads libpython2.7 using `dlopen`.

**Comment by njsmith** [comment]
@honggyukim: Try passing the `RTLD_GLOBAL` flag to `dlopen`.

**Comment by honggyukim** [comment]
@njsmith I really appreciate your help! I added `RTLD_GLOBAL` in `dlopen` but got another error as follows:
```
Traceback (most recent call last):                                                                                                                                                        
  File "/home/honggyu/src/uftrace/git/uftrace/scripts/test.py", line 1, in <module>                                                                                                       
    import numpy                                                                                                                                                                          
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>                                                                                                        
    from . import add_newdocs                                                                                                                                                             
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>                                                                                                      
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 33, in <module>
    from . import _internal  # for freeze programs
  File "/usr/lib/python2.7/dist-packages/numpy/core/_internal.py", line 14, in <module>
    import ctypes
  File "/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
```
Here is `_ctypes` related files in my system.
```
$ find -name "*ctypes*"
./lib-dynload/_ctypes.x86_64-linux-gnu_d.so
./lib-dynload/_ctypes_test.x86_64-linux-gnu_d.so
./lib-dynload/_ctypes_test.x86_64-linux-gnu.so
./lib-dynload/_ctypes.x86_64-linux-gnu.so
./ctypes
./multiprocessing/sharedctypes.pyc
./multiprocessing/sharedctypes.py
./dist-packages/numpy/tests/test_ctypeslib.pyc
./dist-packages/numpy/tests/test_ctypeslib.py
./dist-packages/numpy/core/numerictypes.py
./dist-packages/numpy/core/tests/test_numerictypes.pyc
./dist-packages/numpy/core/tests/test_numerictypes.py
./dist-packages/numpy/core/numerictypes.pyc
./dist-packages/numpy/ctypeslib.pyc
./dist-packages/numpy/ctypeslib.py
```
I will see more on it again. Thanks!

**Comment by eric-wieser** [comment]
I think numpy 1.13 removes the hard dependency on `ctypes`? That was a regression that I remember merging a patch for, but maybe it's scheduled for 1.14

**Comment by njsmith** [comment]
In any case, if you're getting an `ImportError` from trying to import `ctypes`, which is a stdlib package, then that seems to indicate some kind of general problem with your python setup. Maybe try comparing `sys.path` inside a regular python interpreter versus your C program, and then try to figure out why they're different? But it sounds like this isn't a numpy issue at this point, so I don't think we can help much...

Glad to hear the `RTLD_GLOBAL` tip worked though :-)

**Comment by honggyukim** [comment]
@njsmith You're absolutely correct!
The problem was `RTLD_GLOBAL` and `sys.path`. I printed `sys.path` from interpreter and use the same one in my C program. Now it can import numpy without a problem.
I really appreciate your help!

@eric-wieser Thanks for your kind comment as well.

**Comment by njsmith** [comment]
@honggyukim great!
