### ISSUE TITLE
Unexpected result for numpy.dot with dtype=float32

### ISSUE THREAD

**Issue by the-holger** [numpy/numpy#9656]
Hi all!

I'm not sure if this is bug or a feature, but: I'm trying to get the dot product of two vectors (word representations from word2vec) that are 300 dimenstional float32 numpy arrays.

I assumed np.dot(vec1, vec2) would do the trick, but this results in unexpected (wrong?) results compared to a naive dot product implementation (i.e. sum(vec1*vec2)).

When changing the dtype of one of the vectors to float64 I get the expected results.

Example:
```
np.dot(vec1, vec2) => 3.6893488e+19
sum(vec1, vec2) => 15.354403884115527
np.dot(vec1.astype(float64), vec2) => 15.354403884115527
```
Is this intended behaviour I missed in the docs?

Thank you!
Holger

**Comment by eric-wieser** [comment]
by _"300 dimenstional"_, I assume you mean `arr.shape == (300,)`? Can you post the array as the result of `np.save`?

**Comment by the-holger** [comment]
I'm sorry for the ambiguity. Yes, vec1.shape == (300,).

I saved the two vectors and attached them [here](https://github.com/numpy/numpy/files/1280297/issue9656.zip)

To reproduce my results:
```
>>> v1 = np.load(open('vec1.npy','rb'))
>>> v2 = np.load(open('vec2.npy','rb'))
>>> np.dot(v1, v2)
3.6893488e+19

>>> np.dot(v1.astype(np.float64), v2)
15.354403943424975

In case this matters: I'm working with numpy 1.13.1 on the macOS High Sierra beta.

**Comment by pv** [comment]
The platform probably matters. Not reproduced on Linux/openblas. Maybe 
another Apple Accelerate bug?

**Comment by the-holger** [comment]
Yes, the platform does seem to matter, I just ran my code on a Linux (Ubuntu 14.04 LTS, anaconda install of numpy 1.13.0) and could not reproduce the behaviour.

Is there anything I can do to help pinpoint the problem?

**Comment by njsmith** [comment]
@the-holger Can you show the output of `numpy.__config__.show()` for the numpy that doesn't work? And how did you install numpy? (`pip install numpy`, anaconda, homebrew, ...?)

**Comment by the-holger** [comment]
@njsmith I installed via anaconda (miniconda for Python 3.6)

```
np.__config__.show()
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/holger/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/holger/miniconda3/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/holger/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/holger/miniconda3/include']
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/holger/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/holger/miniconda3/include']
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/holger/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/holger/miniconda3/include']
```

**Comment by pv** [comment]
Can you reproduce by reinstalling miniconda from scratch (e.g. into a 
different directory)? If yes, can you list the conda package & versions?

**Comment by the-holger** [comment]
Updating my development environment let me reproduce the issue, so... I purged my development machine and set up miniconda from scratch. Cannot reproduce the issue anymore.

I'm sorry for wasting you guys' time :-(

**Comment by fatrabber** [comment]
I am afraid that I reproduced this issue:

103     y_pred = np.dot(x[:5], b)
104     print(y_pred[0])
105
106     y_pred = np.dot(x.astype(np.float64),b.astype(np.float64))
107     print (y_pred[0])
108 
109     y_pred = np.dot(x, b)
110     print(y_pred[0])

output:
[ 2.09536389]
[ 9.42897485]
[ 10.2467952]

And another wired thing is, every time I run, the second and third results will be slightly different.

np.__config__.show()
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda2/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda2/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda2/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda2/include']
