### ISSUE TITLE
Argument in numpy.rint does not look right

### ISSUE THREAD

**Issue by Gabriel-p** [numpy/numpy#9660]
(Brought from https://github.com/numpy/numpydoc/issues/108)

See https://docs.scipy.org/doc/numpy/reference/generated/numpy.rint.html, this is what I mean:

> numpy.rint(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'rint'>

There's a backlash, asterisk, and other stuff that looks foreign to me.

**Comment by charris** [comment]
The * notation came in with Python 3 and the `/` notation somewhat later. The `*` means that the following arguments are keyword only, i.e., cannot be given by position, and the `/` means that the following arguments are optional and also positional, upto where the `*` occurs. See https://www.python.org/dev/peps/pep-0457/ for more explanation.

**Comment by charris** [comment]
Although I confess that I'm not sure the signature is correct, or couldn't be made clearer.

**Comment by Gabriel-p** [comment]
I did not know that, thank you @charris!

**Comment by pv** [comment]
But note that it tags the `[, signature, extobj]` to the end --- I guess 
that stuff isn't a part of the PEP standard?

**Comment by charris** [comment]
@pv I wondered about that too. For a function that allows those arguments, I think they should be treated like the other arguments, and, if not allowed, they should be absent. The purely positional arguments can be optional, indicated by `[...]` groupings, but in this case the arguments may not be available at all. The documentation generator probably needs some work.

**Comment by eric-wieser** [comment]
> I think they should be treated like the other arguments, and, if not allowed, they should be absent

This issue is indicating that they are optional keyword-only arguments, with no default value. You're right though, it is wrong - it should be `[, signature][, extobj])`, because they are not grouped.

Perhaps the implementation should be adjusted to allow `None` to be passed, and then they can simply be documented as defaulting to `None`.
