### ISSUE TITLE
How do these examples have axis lengths of 3, 2, 3 ?

### ISSUE THREAD

**Issue by peter-mason-dpm** [numpy/numpy#9664]
I found this example in a [tutorial here](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#the-basics). My understanding is the point has an axis length of root 6 and the in the second example first axis has length of 1 and the second axis root 5. Can someone confirm this or explain why not please.

> For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.
> ```
> [[ 1., 0., 0.],
>  [ 0., 1., 2.]]
> ```

**Comment by eric-wieser** [comment]
Can you link to the tutorial you're talking about?

**Comment by peter-mason-dpm** [comment]
I did not want to link to the tutorial because the real possibility that I have misunderstood and I do not want to cause confusion. I believe all the information is contained above and it is only a question of if the axis they speak of is a 3D "vector" however if you insist I will publish the link. 
The section from "For example......" to the end is a direct quote I should have put it in quotation. My apologies.

**Comment by eric-wieser** [comment]
I've added the link myself, now that you've told me it's a quote. In this case, dropping the context made this more confusing

Can you explain what you mean by the word "root", and where the "5" came from?

**Comment by eric-wieser** [comment]
Oh, I see your problem.

You're looking at the cartesian length of the vector consisting of the numbers **in** the array - the result of `np.linalg.norm(arr, axis=-1)`

This is using "axis length" to mean "number of elements in a row" or "number of elements in a column"

**Comment by pv** [comment]
Please note that this issue tracker is meant primarily for bug reports, 
so the part interesting to the many people who receive notifications 
about this issue is only whether there's something that should be 
corrected in the tutorial.

**Comment by peter-mason-dpm** [comment]
In reverse order.
pv I was fairly sure that this did need correction. For people like me the clarification that length of axis refers to the number of elements in the array is a different way of defining length.
Engineers habitually hang a measurement on the term "length" and the explanation that I found explained arrays in those terms but I also agree I only "found" something that is familiar.
eric. The explanation is now clear. Thank you. 
As an old boss of mine reiterated, it is difficult to remember when surrounded by  alligators that the intention was to drain the swamp. In my case to use wolfram or NumPy to find and display dynamically the FFT of my telescope data running on a RaspberryPi.

**Comment by njsmith** [comment]
See #9668
