### ISSUE TITLE
Bug of argsort with arrays of size 3

### ISSUE THREAD

**Issue by juanmabelda** [numpy/numpy#9669]
It seems as argsort has a bug for dimension 3 arrays in an specific order.

For instance if I wrote

import numpy as np

np.argsort(array([2,3,1])

The returned value is:
array([2, 0, 1])

If I change the order of the numbers (i.e. [1,2,3]) the function works well.

I have cross checked the malfunction in python 2.7.6 with numpy 1.8.2 and python 3.5.2 with numpy version 1.11.1 both in windows and linux.

**Comment by seberg** [comment]
And why do you expect something else? Seems like the right answer to me:
```
In [5]: np.array([2,3,1])[np.argsort(np.array([2,3,1]))]
Out[5]: array([1, 2, 3])

In [6]: np.argsort(np.array([1,2,3]))
Out[6]: array([0, 1, 2])
```

**Comment by juanmabelda** [comment]
'got it. Sorry. I misanderstood the help documentation.

**Comment by eric-wieser** [comment]
Duplicate of #8757
