### ISSUE TITLE
Expose datetime conversion funcs in C API

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#9675]
There is a bunch of datetime64 conversion code in pandas which I think is copy/pasted from numpy.  It would be really fulfilling to delete a bunch of that and import it from numpy instead.  AFAICT this could be done if a few `NPY_NOEXPORT` were removed upstream.

In particular, pandas' [np_datetime_strings.c](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/datetime/np_datetime_strings.c) mirrors numpy's [datetime_strings.c](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/datetime_strings.c) and pandas' [np_datetime.c](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/datetime/np_datetime.c) implements a bunch of functions identical to those in numpy's [datetime.c](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/datetime.c).  If `convert_datetime_to_datetimestruct` were exposed to cython, a big chunk of pandas compat code could be deleted (... a few release cycles from now when dependencies catch up).

Would numpy folks be amenable to that?

**Comment by mattip** [comment]
My personal preference would be to split `datetime64` off into a separate unit that both projects could use. It could be a PyPI package, a repo we track and occasionally update (like `einsum`), or some other mechanism that does not extend the already too-wide NumPy API. This may need to wait for the dtypes overhaul so `datetime64` can become a true `int64`-with-units dtype.

**Comment by jbrockmendel** [comment]
closed by #21199?
