### ISSUE TITLE
There's a spurious 'None' string at the top of a doc html page

### ISSUE THREAD

**Issue by pv** [numpy/numpy#9676]
There's a spurious "None" text at the top left of the page https://docs.scipy.org/doc/numpy/index.html

The document actually starts with `None<!DOCTYPE html>` and the top-level `index.html` is the only page where this appears, so it's probably not just an issue in the Sphinx html template (https://github.com/scipy/scipy-sphinx-theme/)

From https://github.com/numpy/numpydoc/issues/109

**Comment by nph10995** [comment]
It also seems that the page is requesting an insecure style sheet not using HTTPS protocols.

**Comment by WarrenWeckesser** [comment]
I think this is a Sphinx bug.  A [warning was added to `defindex.html`](https://github.com/sphinx-doc/sphinx/commit/8a1703c94463c4de53e31a304b6e25586d771b52#diff-99ac0e9b6fbcfda8ab684bbf67571cf3), but it appears that change is injecting `None` (the return value of `warn(...)`) into the HTML output.

**Comment by WarrenWeckesser** [comment]
I created a Sphinx issue: https://github.com/sphinx-doc/sphinx/issues/4051

**Comment by pv** [comment]
I think this should also be fixed in Numpy: defindex.html in numpy is 
included from _templates/indexcontent.html --- since it's deprecated in 
upstream, we should ship our own copy.

As follows: copy defindex.html from sphinx to 
numpy/doc/sources/_templates/defindex.html and just edit out the `warn` 
directive. IIUC this should fix the issue.
