### ISSUE TITLE
Missing `versionadded` for np.moveaxis

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9678]
It's in the source code, but there's a missing space.

See https://docs.scipy.org/doc/numpy-1.11.0/reference/generated/numpy.moveaxis.html

**Comment by shoyer** [comment]
I fixed this in https://github.com/numpy/numpy/pull/9498

(you actually reviewed it!)

**Comment by eric-wieser** [comment]
Gee, that was pretty dumb
