### ISSUE TITLE
ValueError: output array is read-only calling .imag on real valued signal in 1.13.1

### ISSUE THREAD

**Issue by LukasDrude** [numpy/numpy#9679]
When I create a real valued array of certain shape, I get a `ValueError: output array is read-only` when calling .imag and squared on the array.

This happens on:
```
numpy-1.13.1
numpy-1.13.0-p
```

This does not happen on:
```
numpy-1.12.0-p
```

Details to reconstruct are given as follows (here for Anaconda). Create an empty environment with `environment.yml` as follows:
```
name: project_read_only_bug
dependencies:
- python=3.6
- numpy=1.13.1
```

Run:
```
conda env create
```

Run the following Python file:
```
import numpy as np
time_signal = np.random.randn(3, 16000)
time_signal.imag ** 2
```

Expect the following error:
```
Traceback (most recent call last):
  File "read_only_bug.py", line 3, in <module>
    time_signal.imag ** 2
ValueError: output array is read-only
```

In all the following very related cases, the bug does not occur:
```
import numpy as np
time_signal = np.random.randn(3, 16000)
time_signal.imag
```

```
import numpy as np
time_signal = np.random.randn(3, 10)
time_signal.imag ** 2
```

```
import numpy as np
time_signal = np.random.randn(3, 16000)
time_signal.imag + 3
```

**Comment by mhvk** [comment]
Ouch. It sounds like it might be related to trying to re-use temporary arrays, though I thought that would have been fixed by #9260 (which was backported to 1.13.1 in #9261). @juliantaylor?

**Comment by mhvk** [comment]
p.s. It does also happen with `** 0.5` and `** 1`, which suggests it has to do with the fast tracks for power

**Comment by mhvk** [comment]
And just for reference, this is unrelated to `random` - `np.ones(1000000).imag ** 2` has the same problem.

**Comment by charris** [comment]
Doesn't happen with `** 3`
```
In [14]: a.imag ** 3
Out[14]: array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [15]: a.imag ** 2
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-3cb22818d310> in <module>()
----> 1 a.imag ** 2

ValueError: output array is read-only
```
Does look like a fastrack missing check issue. Hmm, are there more fastracks where we might be missing a check.

**Comment by mhvk** [comment]
Indeed, [`fast_scalar_power`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/number.c#L473) only checks `+1,-1, 0, 0.5, 2`. Still, it must just be the `can_elide_temp_unary` function not checking for the array to be writable. In fact, I think #9260 just missed that - [`can_elide_temp`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/temp_elide.c#L288) has the added check for writable, but [`can_elide_temp_unary`](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/temp_elide.c#L363) has not.

**Comment by WarrenWeckesser** [comment]
I don't get the error if the array has size less than 32768:

```
In [45]: np.ones(32767).imag ** 2
Out[45]: array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [46]: np.ones(32768).imag ** 2
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-46-551142906365> in <module>()
----> 1 np.ones(32768).imag ** 2

ValueError: output array is read-only
```

**Comment by charris** [comment]
@WarrenWeckesser Elision only takes place for big arrays due to the overhead of validating whether is can be used or not.

**Comment by charris** [comment]
@mhvk Yep, looks as if `can_elide_temp_unary`  needs the extras checks.

**Comment by charris** [comment]
@juliantaylor Want to take a look? Otherwise we can make the fix.
