### ISSUE TITLE
Weird issue with arange

### ISSUE THREAD

**Issue by arosen93** [numpy/numpy#9694]
If I do `np.arange(3.18,3.21,0.01)`, it gives `array([ 3.18,  3.19,  3.2 ])`. However, if I do `np.arange(3.18,3.22,0.01)`, it gives `array([ 3.18,  3.19,  3.2 ,  3.21,  3.22])`. This seems inconsistent. Why is this so? I am using numpy 1.11.2 on Python 2.7.13.

**Comment by u55** [comment]
This is simply [floating point precision](https://docs.python.org/2/tutorial/floatingpoint.html). To see this, increase the number of digits that are displayed:

```python
>>> np.set_printoptions(precision=32)
>>> print np.arange(3.18, 3.22, 0.01)
[ 3.18000000000000015987211554602254  3.18999999999999994670929481799249
  3.19999999999999973354647408996243  3.20999999999999952038365336193237
  3.21999999999999930722083263390232]
```

This has nothing to do with numpy. Compare the difference between:
```python
>>> format(3.18+(0.01+0.01+0.01+0.01), '.32f')
'3.22000000000000019539925233402755'
```
versus
```python
>>> format((3.18+0.01)+(0.01+0.01+0.01), '.32f')
'3.21999999999999975131004248396493'
```

**Comment by arosen93** [comment]
u55, thanks for letting me know. I had a feeling it wouldn't be an issue with numpy since it's so fundamental. Apologies for such a trivial report and thanks for the clarification.
