### ISSUE TITLE
Numpy element-wise arithmetic gives inaccurate results

### ISSUE THREAD

**Issue by MelvinYin** [numpy/numpy#9697]
```
x = float(3200)
y = np.array([49568], dtype=int)
z = np.array([130125], dtype=int)
print(x/(y*z))

a = float(3200)
b = int(49568)
c = int(130125)
print(a/(b*c))
```

First answer is -1.49539797e-06, while second (correct) is 4.96121261958848e-07. Tested on numpy 1.13.1, python 3.6.1.

**Comment by njsmith** [comment]
Odd, I get 4.96121262e-07 for both.

What operating system and CPU architecture is this? How did you install numpy (pip, conda, ...)? Can you paste the output of `np.__config__.show()`?

**Comment by charris** [comment]
Probably integer overflow.  I suspect `dtype=int` is probably `int32` (long) on Windows and what should be used instead is `int64`. @MelvinYin Note that unlike Python, numpy integer dtypes are C types and use modular arithmetic, so they will happily overflow without raising a warning.

```
In [3]: dtype(int)
Out[3]: dtype('int64')

In [4]: dtype(int).char
Out[4]: 'l'
```
Yep, it is a long.

**Comment by njsmith** [comment]
Ah, yeah, if I explicitly use `int32` for the integer arrays then I do get -1.49539797e-06. Another example where it would be helpful to warn on integer overflow.

**Comment by MelvinYin** [comment]
That is true, when I switched it to int64 the disparity disappears as well. Yup I'm using windows. Thanks @njsmith and @charris! Really appreciate it.
