### ISSUE TITLE
MAINT: check warnings on windows builds

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9704]
I got some errors while working on datetime.c - but this made `runtests.py -i` show a bunch of warnings I would have otherwise missed. Many were unrelated to my patch, and of the form:

```
 C4244: 'function': conversion from 'npy_datetime' to 'int', possible loss of data
```

**Comment by eric-wieser** [comment]
Is there any easy way to build with `/WX` or `-Werror`? I can't seem to make this happen wherever I try and inject those flags

**Comment by charris** [comment]
On Linux you can add it to the CFLAGS environment variable. For instance, I have the (currently commented out) entry in `.bashrc`
```
#CFLAGS=$CFLAGS" -Werror=declaration-after-statement"
```

**Comment by eric-wieser** [comment]
Unfortunately for me, I'm on windows using MSVC. Adding this to `runtests.py` has no effect (ie, the flag never appears in `build.log`:

```
import os
os.environ["CFLAGS"] = '/WX'
```

**Comment by mattip** [comment]
Changed the title. On linux, CI uses `grep` to check the output of the build stage (after configuration). Perhaps we could do something similar on windows using pure python or `FIND` in a script?

**Comment by rgommers** [comment]
We've now switched build systems and the build log is pretty clean, even on Windows. Enabling -Werror in a cross-platform manner can be done by passing `--werror` to `meson setup`. E.g., when using the `spin` developer CLI:
```
$ git clean -xdf
$ spin build -- --werror
```
or with `pip`:
```
pip install . -Csetup-args=--werror
```

The total build log with MSVC in CI is ~1100 lines (from ~10,000 with `numpy.distutils`), about ~200 of which are warnings. New ones crept in:
```
..\numpy\core\src\umath\loops_unary.dispatch.c.src(346): warning C4146: unary minus operator applied to unsigned type, result still unsigned
```
Cleaning build warnings on Windows and macOS is always welcome, but that probably doesn't require keeping this 6 year old issue open. Hence I'll close it. Thanks @eric-wieser and @mattip.
