### ISSUE TITLE
remove newline in repr of arrays with flexible datatype?

### ISSUE THREAD

**Issue by ahaldane** [numpy/numpy#9717]
Another one to think about while we are changing print output for 1.14: (see #9699)

Flexible types have an extra newline before the datatype in the repr of the array:

```python
>>> np.array(['hello'])
array(['hello'],
      dtype='<U5')
```

Should we remove the newline?

**Comment by mhvk** [comment]
The newline doesn't seem particularly useful here...

**Comment by eric-wieser** [comment]
Seems to me that this was targeted at `np.void` structured arrays, but leaked into the formatting of all flexible arrays. I think it's handy for the `np.void` ones, but not for the `np.character` ones

**Comment by eric-wieser** [comment]
This should be easy to handle with the `legacy` flag now, right?
