### ISSUE TITLE
Make numpy.ndarray a subclass of Sequence

### ISSUE THREAD

**Issue by mitar** [numpy/numpy#9719]
`numpy.ndarray` could be marked as a subclass of [Sequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence). To my understanding it exposes interface.

All that is needed to be done is:

```python
Sequence.register(numpy.ndarray)
```

**Comment by shoyer** [comment]
There is already an issue for this -- please see https://github.com/numpy/numpy/issues/2776
