### ISSUE TITLE
ENH: numpy.random functions do not have an option to use a pre-allocated buffer. 

### ISSUE THREAD

**Issue by MorganGellert** [numpy/numpy#9722]
Most functions in numpy include an argument to use a buffer that you have already allocated through the use of an 'out' parameter. Is there a reason this cannot be implemented for these functions?

**Comment by eric-wieser** [comment]
Related: #8833

**Comment by bashtage** [comment]
See http://bashtage.github.io/ng-numpy-randomstate/doc/change-log.html?highlight=out#version-1-12 for a fully compatible project that supports out for a core subset of generators.

**Comment by mattip** [comment]
Closing since this is implemented in the new API. Please reopen if the `out` parameter is not sufficient for your needs.
