### ISSUE TITLE
Sum of entries of a matrix depends on row ordering

### ISSUE THREAD

**Issue by AndreaBarbon** [numpy/numpy#9723]
The sum of the entries of a matrix is obviously an invariant with respect to re-shuffling of row and/or columns.

However, this does not hold for the numpy `sum` function applied to matrices.

Here is a replication of the problem with a simple code snippet, which generates a random matrix, re-shuffles it using `pandas` and then compares the sum of the entries for original and the shuffled matrix.
I also check the entry-by-entry difference of the two matrices, confirming that they are exactly the same.
The `sum` error rate oscillates between 70% and 80%. It is numerically very small, though.

```
import pandas as pd; import numpy as np
print("Pandas version: " + pd.__version__)
print("Numpy  version: " + np.__version__)
print()
sum_error = []; mat_error = []
for i in range(0,100):
    A = pd.DataFrame(np.random.random(size=(100,100)))
    ind1 = np.random.choice(A.index, size=100, replace=False)
    ind2 = np.sort(ind1)
    A1 = A.loc[ind1][ind1]
    A2 = A.loc[ind2][ind2]
    sum_error.append((np.sum(A1) - np.sum(A2)) != 0)
    mat_error.append( np.sum(A1-A2) != 0 )
print("Sum    error rate: {0:1.0f}%".format(np.mean(sum_error)* 100))
print("Matrix error rate: {0:1.0f}%".format(np.mean(mat_error)* 100))
```

The output on my system is the following

> Pandas version: 0.20.3
> Numpy  version: 1.13.1
> 
> Sum    error rate: 84%
> Matrix error rate: 0%

**Comment by charris** [comment]
> The sum of the entries of a matrix is obviously an invariant with respect to re-shuffling of row and/or columns.

Not true. Changing the order of summation will change the result due to the properties of floating point numbers.

**Comment by charris** [comment]
Addition and multiplication of floating point numbers is not associative.

**Comment by MSeifert04** [comment]
Well, that's just a problem with inexact (but fast) algorithms. Note that the order of elements definitely influences the result:

```
np.array([10e70, -10e70, 1]).sum()   # 1
np.array([10e70, 1, -10e70]).sum()   # 0
```

**Comment by AndreaBarbon** [comment]
> > The sum of the entries of a matrix is obviously an invariant with respect to re-shuffling of row and/or columns.
> > 
> 

> Not true. Changing the order of summation will change the result due to the properties of floating point numbers.

Well, mathematically this is actually true. With floating point numbers this is not, I see.
Thanks for your work and for the quick reply!
