### ISSUE TITLE
numpy.distutils bug

### ISSUE THREAD

**Issue by sunqm** [numpy/numpy#9729]
Hi,

In numpy.distutils,
https://github.com/numpy/numpy/blob/master/numpy/distutils/exec_command.py#L249
using shell in subprocess.Popen may cause a bug when compiling python extension.

For example, for the following setup.py 
```
from distutils.core import setup, Extension
setup(ext_modules=[Extension("foo", ["foo.c"], libraries=['abcde'], runtime_library_dirs=['$ORIGIN'])],
)
```
assuming I have foo.c file in the directory while the abcde library is not existed,  cmdline "python setup.py build" will raise an error "/usr/bin/ld: cannot find -labcde".

If numpy.distutils was imported
```
from distutils.core import setup, Extension
import numpy.distutils
setup(ext_modules=[Extension("foo", ["foo.c"], libraries=['abcde'], runtime_library_dirs=['$ORIGIN'])],
)
```
"python setup.py build" does not raise any error.  The problem is that gcc link flags  "-Wl,-R$ORIGIN -labcde" which was recognized as "-Wl,-lR -labcde" in numpy.distutils because shell is enabled in subprocess.Popen.

**Comment by rgommers** [comment]
`exec_command` was rewritten after this build report and deprecated / no longer used internally in numpy, so I don't think this applies anymore. `numpy.distutils` is also deprecated, so I'll close this issue. Thanks @sunqm
