### ISSUE TITLE
BUG: np.divmod produces nested tuple for object loops

### ISSUE THREAD

**Issue by pazqo** [numpy/numpy#9730]
Simple reproduction:
```python
>>> np.divmod(np.array(1, object), 1)
((1, 0), None)
```
---

I cannot understand why this happens. It doesn't happens with built-in divmod. It seems to be a matter of int representation (2**63 ~ 1e19) but I don't undestrand if this is a bug or a feature.

Any ideas?

```
from numpy import divmod

test = 10**6
for i in range(15,25):
    x = 10**i
    print(i, divmod(x, test))

15 (1000000000, 0)
16 (10000000000, 0)
17 (100000000000, 0)
18 (1000000000000, 0)
19 (10000000000000.0, 0.0)
20 ((100000000000000, 0), None)
21 ((1000000000000000, 0), None)
22 ((10000000000000000, 0), None)
23 ((100000000000000000, 0), None)
24 ((1000000000000000000, 0), None)
```

**Comment by MSeifert04** [comment]
It's because the `10**20` and above are interpreted as `object` arrays. From what I can see `np.divmod` delegates to Pythons `divmod` for the first returned item but just inserts `None` in the second element.

So I think that's a problem with `object` arrays and `divmod`. For some reason `uint` also behaves weird in floor division and modulo, giving doubles instead of `uint`s (can the remainder be negative?).

**Comment by shoyer** [comment]
Agreed, this looks like a bug, for the reasons @MSeifert04 has diagnosed.

**Comment by shoyer** [comment]
Interestingly, it looks like our code generator hard-codes one only output for ufuncs (at least with object dtype):
https://github.com/numpy/numpy/blob/4a103d432c0c717168bcf9230092c8910ac675c1/numpy/core/code_generators/generate_umath.py#L931-L935

**Comment by eric-wieser** [comment]
#10284 changes the result to be

```
TypeError: ufunc 'divmod' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

for the larger values, which is better than nothing until we have a fix.

**Comment by eric-wieser** [comment]
>  For some reason uint also behaves weird in floor division and modulo

This is because it's doing `uint64 // int64`. `uint64 // uint64` works as expected.

**Comment by eric-wieser** [comment]
Closing in favor of #10954, which now has a more accurate title
