### ISSUE TITLE
BUG: `allclose` returning False in master but True in 1.13.1

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#9734]
There is a recent change in the behavior of `np.allclose()` (and therefore `np.testing.assert_allclose()`) that is causing an unexpected test failure in scipy.

Here's numpy 1.13.1:

```
In [30]: np.__version__
Out[30]: '1.13.1'

In [31]: a = 9.7596849444895994e+297

In [32]: b = 9.7596849444884899e+297+0j

In [33]: np.allclose(a, b, atol=0)
Out[33]: True
```

Here's numpy master branch:

```
>>> import numpy as np
>>> np.__version__
'1.14.0.dev0+54232da'
>>> a = 9.7596849444895994e+297
>>> b = 9.7596849444884899e+297+0j
>>> np.allclose(a, b, atol=0)
False
```

**Comment by WarrenWeckesser** [comment]
I think my comment at https://github.com/numpy/numpy/pull/9720#issuecomment-331484568 explains how this broke.

**Comment by pv** [comment]
The minimal reproduction is:
```
z = abs(np.complex128(1.109454021559596e+285))
assert np.isfinite(z), z
``
Looks like a bug in the nb_absolute implementation in np.complex128

**Comment by pv** [comment]
Looks like it's doing something silly, probably computing 
sqrt(x**2+y**2) rather than hypot(x,y)

**Comment by WarrenWeckesser** [comment]
I didn't dig further than what I showed in my comment on the numpy pull request, but because of the large value of the argument that causes the error, a naive implementation of `abs(z)` seems likely.

**Comment by pv** [comment]
Here: 
https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/scalarmath.c.src#L557

**Comment by charris** [comment]
Curiously, on my system both `HAVE_HYPOTF` and `HAVE_HYPOTL` are defined, but `HAVE_HYPOT` is not. This seems like a common problem for the functions listed in `OPTIONAL_STDFUNCS`. Looks like a bug, actually.

**Comment by pv** [comment]
It looks like it's just silliness in the scalarmath implementation: https://github.com/numpy/numpy/pull/9741
