### ISSUE TITLE
savetxt on Python 2.7 cannot handle unicode `fmt`

### ISSUE THREAD

**Issue by andreas-h** [numpy/numpy#9738]
On Python2, I'm using `from __future__ import unicode_literals`.  now, when I try

    np.savetxt(fd, np.atleast_2d(sl), fmt='%11.7f', newline=sep)

I get a `ValueError: invalid fmt: u'%11.7f'`.

Not sure if this has already been reported, there are several unicode-related issues but none seemed to match this case (or I was too quick in looking).  The following worked:

    np.savetxt(fd, np.atleast_2d(sl), fmt=b'%11.7f', newline=sep)

I'm using numpy 1.12.1 on Python2.7.

**Comment by mattip** [comment]
Closing, python2 is no longer supported.
