### ISSUE TITLE
numpy.cov

### ISSUE THREAD

**Issue by nobuosato** [numpy/numpy#9763]
Numpy cov function generates large memory and it does not get removed from memory.  memory_profiler gives the following:

```
Line #    Mem usage    Increment   Line Contents                                               
================================================                                               
    85  156.133 MiB    0.000 MiB     @profile  
    86                               def test(samples):                                
    87  159.184 MiB    3.051 MiB       cov=np.cov(np.transpose(samples))                       
    88  159.184 MiB    0.000 MiB       cov=my_cov(samples)                                   
    89  159.184 MiB    0.000 MiB       return cov  
```
my_cov is my own  implementation of cov. The shape of sample is (50,19). This was tested on a linux machines (archlinux and centos) using anaconda 1.6.3.  This is quite problematic if one needs to call the numpy cov several times

**Comment by nobuosato** [comment]
Also numpy.lingalg.eig  is generating large memory

**Comment by eric-wieser** [comment]
I'm not convinced your profiling is valid - can you repeatthta with a `del cov` after line 87?

**Comment by nobuosato** [comment]
"""
Line #    Mem usage    Increment   Line Contents                                               
================================================                                               
     5   49.863 MiB    0.000 MiB   @profile    
     6                             def test(samples):                                          
     7   56.727 MiB    6.863 MiB     cov=np.cov(np.transpose(samples))                         
     8   56.727 MiB    0.000 MiB     del cov                                                   
     9   56.727 MiB    0.000 MiB     return None 
"""

**Comment by eric-wieser** [comment]
Right, but  now you've removed your function from there. Can you reinsert the line you removed?

**Comment by nobuosato** [comment]
```
$ python -m memory_profiler driver.py          
Filename: driver.py    

Line #    Mem usage    Increment   Line Contents                                               
================================================                                               
    13   49.871 MiB    0.000 MiB   @profile    
    14                             def test(samples):                                          
    15   58.730 MiB    8.859 MiB     cov1=np.cov(np.transpose(samples))                        
    16   58.730 MiB    0.000 MiB     cov2=get_cov(samples)                                     
    17   58.730 MiB    0.000 MiB     del cov1                                                  
    18   58.730 MiB    0.000 MiB     return None  
```

Here is the code

```
#!/usr/bin/env python
import sys,os
import numpy as np


def get_cov(sample):
  n=len(sample)
  mean=np.mean(sample,axis=0)
  diff=[s-mean for s in sample]
  return np.einsum('ki,kj->ij',diff,diff)/(n-1)


@profile
def test(samples):                                    
  cov1=np.cov(np.transpose(samples))
  cov2=get_cov(samples)
  del cov1       
  return None

samples=np.random.rand(50,20)
test(samples)    
```

**Comment by charris** [comment]
Sometimes I see it, sometimes I don't. Putting a pause of several seconds (time.sleep) seems to ensure that memory is returned. Might just be garbage collection taking time to run. Python also caches memory for reuse.

**Comment by eric-wieser** [comment]
What happens if your call your function first?

**Comment by nobuosato** [comment]
It seems to give the same behavior 

```
$ python -m memory_profiler  driver.py                                                         
Filename: driver.py    

Line #    Mem usage    Increment   Line Contents                                               
================================================                                               
    13   50.152 MiB    0.000 MiB   @profile    
    14                             def test(samples):                                          
    15   50.152 MiB    0.000 MiB     cov2=get_cov(samples)                                     
    16   56.859 MiB    6.707 MiB     cov1=np.cov(np.transpose(samples))                        
    17   56.859 MiB    0.000 MiB     del cov1                                                  
    18   56.859 MiB    0.000 MiB     return None   
```

For simple applications where cov is called only once or even few times, this will not be an issue. But for users  with long running code where it is called several times is an issue, and setting a time.sleep will degrade the performance of the overall code. 

As I mentioned before, the problem exist also with np.linalg.eig, and for that I don't have simple solution to replace the cov function. A simple solution at present for me is to use my cov function along with the eig function from mpmath which does not have the memory problem.

**Comment by nobuosato** [comment]
I also added time.sleep(10)  and it does not seems to work.

**Comment by njsmith** [comment]
@nobuosato If you call `np.cov` over and over again, does your process's memory grow without bound? If so, it's a memory leak that we need to fix. If not, then what you're seeing here is almost certainly an artifact of your measuring tools rather than anything real. Measuring memory usage is extremely complicated and this kind of spurious effect is very common...

**Comment by nobuosato** [comment]
@njsmith , many thanks. I took your suggestion and checked if there where other possible sources that caused the memory to increase and I found it. It was not the cov function at the end, despite the fact that  mprof was indicating possible issues in the cov function. I think the issue is resolved.

**Comment by Liuyubao** [comment]
> @njsmith , many thanks. I took your suggestion and checked if there where other possible sources that caused the memory to increase and I found it. It was not the cov function at the end, despite the fact that mprof was indicating possible issues in the cov function. I think the issue is resolved.

Hi @nobuosato, amazing we have exactly the same issue. Very glad that you found the root cause. 

Can I ask two quick questions:
1.What's the final sources that caused the memory increasing?
2.What other measuring tools did you use to find the final answer?

Super appreciate it if you can share any hints. Thanks a lot!!
