### ISSUE TITLE
BUG: str of long arrays has stray comma

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9777]
```
a = np.arange(5000)
print(a)
[   0    1    2 ..., 4997 4998 4999]
```

**Comment by aviral1701** [comment]
@eric-wieser I would like to work on this.

**Comment by aviral1701** [comment]
@eric-wieser Can you point me in the direction?

**Comment by eric-wieser** [comment]
@aviral1701: Sure

The `_array2string` function in `:/numpy/core/arrayprint.py` introduces this string. Right now it always adds a comma.
You'll need to come up with some way to tell it to only do this in `repr`, not in `str`.

**Comment by eric-wieser** [comment]
Actually, just changing `summary_insert = "..., "` to `summary_insert = "..." + separator` should be enough

**Comment by nafest** [comment]
@eric-wieser: There are already tests that cover this change. Is it necessary to add an additional test?

**Comment by aviral1701** [comment]
@nafest I was supposed to be doing this as already mentioned above.Why did you commit then?

**Comment by nafest** [comment]
@aviral1701 sorry I fixed that yesterday. Didn't know I had to comment that I am working on this.

**Comment by aviral1701** [comment]
@eric-wieser I would suggest that we add some guidelines in Contributing guide to avoid duplicacy of work which harm the contribution spirit.
