### ISSUE TITLE
Numpy is no longer in PyPI

### ISSUE THREAD

**Issue by japagetw** [numpy/numpy#9790]
Numpy has been removed from the Python Package Index.  The page https://pypi.python.org/pypi/numpy no longer exists.

**Comment by tacaswell** [comment]
Indeed, that is worrying, but `pip install numpy` still seems to work.  Not sure if that means this is a web-front end issue on pypi or that I am just seeing the CDN which has not been flushed yet.

**Comment by rgommers** [comment]
PyPI bug, https://pypi.python.org/pypi/numpy/1.13.1 exists but https://pypi.python.org/pypi/numpy/1.13.2 was deleted. Should be fixed once 1.13.3 is uploaded.

**Comment by willhardy** [comment]
It's probably too late, but maybe it would be (would have been) worth re-releasing 1.13.1 as 1.13.3 (ie reverting) until it is fixed (the fix would then need to be released as 1.13.4)?

**Comment by lauhayden** [comment]
What was the reason why 1.13.2 was pulled? (Was that release pulled?)

**Comment by eric-wieser** [comment]
Probably #9786, @lauhayden

**Comment by charris** [comment]
Fixed with the release of 1.13.3.
