### ISSUE TITLE
How to plot the numpy arrays?

### ISSUE THREAD

**Issue by PhilipTheVictor** [numpy/numpy#9793]
Code :
import matplotlib.pyplot as plt
import numpy as np

data = np.loadtxt('math.csv', delimiter=',', skiprows = 1, usecols = (2,))
print(data)

years = np.loadtxt('math.csv', dtype='str', delimiter=',', skiprows = 1, usecols = (1,))
print(years)

plt.ylabel("No. of students")
plt.xlabel("Year")

plt.title("No. of Students in Fall Semester in Maths Class")

plt.xticks([i + 0.5 for i, _ in enumerate(years)], years)
plt.yticks(np.arange(0,400,50))

plt.bar(data, years)

plt.show()

Problem:
I am trying to plot the data and years but I am not getting my data plotted according to no. of years. Instead every bar graph approaches highest limit of data. How to resolve it?

**Comment by njsmith** [comment]
You'll probably have better luck asking a question like this on
stackoverflow.com.
