### ISSUE TITLE
Wrong result from np.linalg.cholesky on 32-bit win32 in numpy 1.13.3

### ISSUE THREAD

**Issue by pv** [numpy/numpy#9795]
The following program produces wrong results for Numpy 1.13.3 for the 32-bit win32 wheel `numpy-1.13.3-cp36-none-win32.whl`:
```
import numpy as np
m = np.array([[1, 0.3], [0.3, 1]])
c = np.linalg.cholesky(m)
print(np.__version__, "\n", c)
assert np.allclose(c @ c.T, m)
```
it prints
```
1.13.3 
 [[ -2.00000000e+00   0.00000000e+00]
 [ -1.50000000e-01  -9.55902467e-54]]
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    assert np.allclose(c @ c.T, m)
AssertionError
```
The 64-bit windows wheels appear to be OK.

The result for Numpy 1.13.1 (`numpy-1.13.1-cp36-none-win32.whl`) is also OK:
```
1.13.1 
 [[ 1.         0.       ]
 [ 0.3        0.9539392]]

```

**Comment by pv** [comment]
I can't think of other causes than a broken LAPACK/BLAS linalg library. Was the build changed between 1.13.1 and 1.13.3? Also, doesn't numpy have tests for cholesky that would have caught this?

**Comment by pv** [comment]
This issue probably can be handled just with the wheel build tags...

**Comment by matthew-brett** [comment]
No better using mingwpy build of later OpenBLAS commit : https://ci.appveyor.com/project/matthew-brett/numpy-wheels/build/job/uf1r7hsa6rmxe962

This is OpenBLAS commit 5f998ef

How easy would it be to make a minimal test case for the OpenBLAS guys?

**Comment by pv** [comment]
Fairly easy, https://github.com/xianyi/OpenBLAS/pull/1318

**Comment by charris** [comment]
Doesn't look to be an easy way to choose between ATLAS and OpenBLAS for building Windows wheels. The quick fix would be to use ATLAS for the four 32 bit windows wheels, then use OpenBLAS again when it is fixed.

**Comment by charris** [comment]
So, just to clarify the procedure for bad wheels, as opposed to bad source,

* Remove the bad wheels from PyPI, should fall back to last good release.
* Upload good wheels, when available, using a build tag.

@rgommers Thoughts? The wheel names are already so arcane that I think adding a build tag is not much of a problem.

**Comment by matthew-brett** [comment]
@charris - I've built the 32-bit ATLAS wheels : https://ci.appveyor.com/project/matthew-brett/numpy-wheels/build/1.0.75 - just a hack for now, using an older numpy-wheels commit.  I've downloaded them, got the build tags done, can upload on your say-so.

**Comment by charris** [comment]
@matthew-brett Let's give it a shot. I'll download them once they are up in order to redo the hashes for Github.

**Comment by charris** [comment]
Oh, and which cythonized version did you use? Just want to make sure it was 0.26.1.

**Comment by matthew-brett** [comment]
Oops - no - it was Cython 0.27.  Silly me.  Build tag 2 I guess.

**Comment by matthew-brett** [comment]
Done rebuild with Cython 0.26.1 : https://ci.appveyor.com/project/matthew-brett/numpy-wheels/build/1.0.76

Checked they are using ATLAS, and are not the same as previous wheels built with Cython 0.27.

Added build tag.  Ready to upload.   This will be build tag 2...

**Comment by charris** [comment]
Sounds good.

**Comment by matthew-brett** [comment]
Done.

**Comment by charris** [comment]
Great, thanks. I'll leave the other files in for a bit to see if PyPI works correctly with them there.

**Comment by pv** [comment]
`pip install numpy` still gives the broken wheel (with no build tags).
Maybe pip just doesn't actually have support for build tags?

**Comment by pv** [comment]
Ok, seems to work now (after charris deleted the old wheels --- or due to something else).

**Comment by rgommers** [comment]
> Maybe pip just doesn't actually have support for build tags?

My internet connection is too slow to search for it now, but I'd like to point out again that we tried using ``.post0`` build tags before, they didn't work as expected, and we decided to not do that again.

> So, just to clarify the procedure for bad wheels, as opposed to bad source,
>
>    Remove the bad wheels from PyPI, should fall back to last good release.
>    Upload good wheels, when available, using a build tag.
>
> @rgommers Thoughts? The wheel names are already so arcane that I think adding a build tag is not much of a problem.

Unless we experiment with this thoroughly (not in the main numpy account) and prove that everything works as expected, I'd say that either broken wheels or broken source means we pull the whole release if the breakage is bad enough to warrant that.

**Comment by pv** [comment]
If we want openblas for the windows numpy wheels, gh-9645 may be a better way to go, because that relies on vanilla mingw-w64 rather than on mingwpy.

**Comment by charris** [comment]
@rgommers, If this works I'm inclined to leave it be. That said, IIRC, the reason for not allowing reuse of file names was that synchronizing different servers could take time. I don't know that build tags solve that problem. I think we need more feedback from the PyPA people.

**Comment by pv** [comment]
Before closing this, consider fixing the numpy-wheels repo configuration.

**Comment by xoviat** [comment]
I thought we already had found that mingwpy caused problems. I would recommend using the same procedure in the source repository as the release repository.

**Comment by matthew-brett** [comment]
@xoviat - yes - that's a good idea.  Do you have any interest in porting your stuff over to the `numpy-wheels` repo?

**Comment by xoviat** [comment]
Yes but I think the pull request on this repository needs to be merged first (#9645).

**Comment by matthew-brett** [comment]
For the build tags - I'm pretty confident that they work - I've used them before a few times, and we're testing it again now, with this fix.  I have always deleted the previous versions after uploading the new build tag, but I suspect that's not necessary.

**Comment by charris** [comment]
@xoviat  #9645 is in.

**Comment by xoviat** [comment]
I'll look at the wheels repository sometime soon.

**Comment by xoviat** [comment]
@matthew-brett See MacPython/numpy-wheels#3.

**Comment by rgommers** [comment]
> @rgommers, If this works I'm inclined to leave it be. That said, IIRC, the reason for not allowing reuse of file names was that synchronizing different servers could take time. I don't know that build tags solve that problem. I think we need more feedback from the PyPA people.

Now that I've looked at it in a little more detail: what you currently did should be robust. It's not a build tag like ``.post0``, which is a version modifier (that is the thing that should be avoided). By deleting the old wheel and putting in a new one with an extra tag ``-1`` in this case, it should still find this wheel for the relevant OS/Python combo. It could be any tag, doesn't have to be ``-1``, ``-2`` etc. The only requirement is that it's a valid tag format.

**Comment by matthew-brett** [comment]
I believe the build tag has to start with a digit - see: https://github.com/pypa/pip/blob/master/src/pip/_internal/wheel.py#L488

**Comment by rgommers** [comment]
@matthew-brett you're right. And it's not just an implementation detail, there's an actual spec: https://www.python.org/dev/peps/pep-0491/#file-name-convention

I thought there were also arbitrary tags, but doesn't look like that's right. The ``.post0`` business has been removed.

**Comment by njsmith** [comment]
`.post0` is still a thing; in the [file name layout in PEP 491 that you linked](https://www.python.org/dev/peps/pep-0491/#file-name-convention), `.post0` would be part of the `version`. The `.post` nonsense is [described in PEP 440](https://www.python.org/dev/peps/pep-0440/#post-releases) (though even it suggests that you avoid using it).

The key distinction here is that `.post0` is part of the actual version number, so as far as the tools are concerned `1.13.1.post0` is a whole new release that comes after `1.13.1`. It's basically a more confusing way of spelling `1.13.1.1`. OTOH a wheel build tag is a new build of the *same* release.

**Comment by charris** [comment]
@njsmith Would be good if build tags could also be used with sources, although the naming scheme might be too flexible for that. I suspect the possiblity of different source builds was overlooked.

**Comment by njsmith** [comment]
@charris I believe (for better or for worse) the concept is exactly that a given release has 1 source and possibly lots of builds, and if you want to roll a new sdist then you should bump the actual version. I guess this makes some sense; if you have multiple source builds then how do you know which ones were used for which binary builds?

**Comment by xoviat** [comment]
I think the general idea is that a source distribution is as close to a
source checkout as possible (specifically, there should be no cythonized
files in the source distribution). If that's not the case, then pypi won't
play well with what you're trying to do.​

**Comment by njsmith** [comment]
Cythonized files in the source distribution work fine, but yeah, if you want to regenerate the cython files it means you have to bump the version number.

**Comment by charris** [comment]
I'm going to close this. The NumPy problem seems to have been solved by moving to vanilla mingw-w64.
