### ISSUE TITLE
ndarray.reshape performs out-of-bounds access if no arguments are given

### ISSUE THREAD

**Issue by FrozenBob** [numpy/numpy#9802]
If `ndarray.reshape` receives no arguments, it goes through

```
    if (n <= 1) {
        if (PyTuple_GET_ITEM(args, 0) == Py_None) {
            return PyArray_View(self, NULL, NULL);
        }
```

which performs an unchecked out-of-bounds access to the `args` tuple. This doesn't seem to be causing crashes or anything, but it should still probably be fixed.

**Comment by seberg** [comment]
The code has actually been fixed since then.
