### ISSUE TITLE
Array elements are sent individually when using another class's rlshift/rrshift

### ISSUE THREAD

**Issue by bleppie** [numpy/numpy#9809]
Python: 3.5.2 (default, Oct 11 2016, 05:05:28) 
Numpy: 1.13.1

```
class Foo(object):
    def __rrshift__(self, other):
        print(other)

(1,2) >> Foo()
numpy.array((1,2)) >> Foo() 
```

Output:
```
(1,2) # As expected
1 # What?
2 # Huh?

```

**Comment by eric-wieser** [comment]
This is a feature. If you don't want this behaviour, I think you can set `__array_ufunc__ = None`

**Comment by charris** [comment]
And for older numpy versions, `__array_priority__ = 1000` will probably have the same effect as `__array_ufunc__ = None`. What is happening is that `Foo()` becomes an element of an object array and is broadcast across the elements of the LHS.

**Comment by bleppie** [comment]
Thanks. For people who stumble upon this, the folks above mean adding `__array_ufunc__ = None` to the Foo class like so:
```
class Foo(object):
    __array_ufunc__ = None
    def __rrshift__(self, other):
        print(other)
```
