### ISSUE TITLE
np.matmul Get the wrong answer

### ISSUE THREAD

**Issue by Riotpiaole** [numpy/numpy#9813]
I was using numpy calculating my  math homework. But the matrix multiplication obtaining wrong result

```python
import numpy as np
R = np.matrix([[5,-12],[12,5]])
Q= np.matrix([[1,1],[1,0]])

Q*R # should obtain [[17,-7],[5,-12]] however obtain [[17,-7],[17,-7]]

```
Please help me with this confusing case. It is an issue of just a pure misunderstanding on the np.matrix

Sincerely

**Comment by charris** [comment]
Works for me. What version of numpy are you using and how did you install it?

Using matrices is discouraged, it is better to use arrays, recent numpy, and python >=3.5. Then you can write `R @ Q`.

**Comment by Riotpiaole** [comment]
Nevermind, probably some random as memory issue. 
```python
import numpy as np
R = np.matrix([[5,-12],[12,5]])
Q= np.matrix([[1,1],[1,0]])

R*Q //matrix  matrix([[ 17,  -7],[  5, -12]])
```
it works out couple days later
