### ISSUE TITLE
NumPy pad docstring examples show np.lib.pad

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#9820]
Probably should just say `np.pad` instead of `np.lib.pad`. Here's an example of what I'm seeing in the docs to clarify.

```python
>>> a = [1, 2, 3, 4, 5]
>>> np.lib.pad(a, (2,3), 'constant', constant_values=(4, 6))
array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])
```

ref: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.pad.html

**Comment by charris** [comment]
Closed by #9868.
