### ISSUE TITLE
np.mean() with axis produces wrong answer

### ISSUE THREAD

**Issue by clavichord93** [numpy/numpy#9823]
I have a np.array X with shape (100000, 64, 64, 3).

`np.mean(X, axis=(0,1,2))` produces [0.04096  0.04096  0.04096] but `np.mean(X[:,:,:,0])`, `np.mean(X[:,:,:,1])` and `np.mean(X[:,:,:,2])` produce [0.48024598  0.44807231  0.39754641].

Did I do something wrong?

**Comment by seberg** [comment]
Please see https://github.com/numpy/numpy/issues/9393
