### ISSUE TITLE
Inconsistent step of the output array using numpy.arange?

### ISSUE THREAD

**Issue by pkmn99** [numpy/numpy#9827]
I was trying to create array to get some latitude values.
**Example 1:**
`a = np.arange(49.9375, 19.9375, -0.125) `
`(a[1] - a[0]) == -0.125`
`True`
`a[-1] == (19.9375 + 0.125)`
`True`

Above example can give me exactly what I want. The output array has the step of -0.125 (True) and the last value is exactly what it should be.

**Example 2:**
However, in the second example below, the output step is not -0.02 (False) and the output array is not exactly the value I want.
`b = np.arange(60.58, -0.02, -0.02)`
`(b[1] - b[0]) == -0.02`
`False`
`b[-1] == (-0.02 +0.02 )`
`False`

When I print out array `a` and `b`, it shows 
a: `array([ 49.9375,  49.8125,  49.6875,  49.5625,  49.4375,  49.3125, ...`
b: `array([  6.05800000e+01,   6.05600000e+01,   6.05400000e+01, ...,`
It seems array `b` has more digits after zero than array `a`.

How can I get the expected results for Example 2? 
I don't understand why there is such inconsistent result, is that a precision problem? 
I use np.arange quite often in my work and I just noticed this issue recently ...
Thanks a lot!

**Comment by ahaldane** [comment]
Yep, it's a precision issue, see also #9694.

Note that even in pure-python (no numpy) on 64bit systems, (in fact, anytime you use IEEE 64 bit floats) you get:
```python
>>> (60.58 - 0.02) - 60.58
-0.020000000000003126
```
which is not equal to -0.02 as you might expect.

Also, the reason b prints with more digits is a quirk of the numpy printing system when using scientific notation (with `e+01`), it does not mean anything. In fact we're thinking of getting rid of that quirk.

I'm going to close, hopefully that helps!

**Comment by pkmn99** [comment]
Thanks for the explation! Since both example 1 and 2 are floating numbers, why example 1 works as expected but example 2 doesn't? Is there a way to always get example-1-type of behavior?

**Comment by njsmith** [comment]
Probably this happens because floating point uses base 2, and 0.125 =
2**-3, so it's exactly representable. 0.2 on the other hand is some
infinite repeating fraction when written in binary, so it can't be
represented exactly. This is pretty deeply baked into how NumPy (and most
programs) work with numbers.

Use linspace, it will give you what you want, or get you as close as you
can get.

**Comment by pkmn99** [comment]
Thanks for your reply, njsmith! 
This is tricky and it seems there is no quick workaround... 
I also tried linspace:
`c = np.linspace(60.58, 60.58-0.02*15, num=15, endpoint=False)`
`(c[1] - c[0]) ==-0.02`
`False`

As you predicted, it has the similar issue.
But I think I can use `round` to get the output array correct.
