### ISSUE TITLE
numpy.random.seed fails with empty non-int array

### ISSUE THREAD

**Issue by pdknsk** [numpy/numpy#9832]
```Python
>>> numpy.random.seed([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 684, in mtrand.RandomState.seed
TypeError: Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe'
```
```Python
>>> numpy.random.seed(numpy.array([]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 684, in mtrand.RandomState.seed
TypeError: Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe'
```

**Comment by kenogo** [comment]
What's wrong with this?

**Comment by pdknsk** [comment]
Well, as the array is empty, the type shouldn't matter.
```Python
>>> numpy.array_equal(numpy.array([], dtype = numpy.int), numpy.array([], dtype = numpy.float))
True

```

**Comment by rkern** [comment]
In an ideal world, yes, the constructor would check the length (and raising an exception with an informative message in the empty case) before checking the dtype.

**Comment by rkern** [comment]
FWIW, `RandomState(np.array([], dtype=int))` should also raise an exception though the implementation currently doesn't. The underlying C code assumes that there is at least one entry. I think it is only by chance that the code doesn't segfault.

**Comment by bashtage** [comment]
> I think it is only by chance that the code doesn't segfault.

I think if you pass a trivial 0-length array it will no-op.  It could potentially be segfaulted by passing an empty array with a non-zero dimension, e.g., `np.empty((10,0))` which would try and read 10 elements from an empty data array.

**Comment by rkern** [comment]
The way I read the code, it will execute this line `RK_STATE_LEN` times, accessing `init_key[j]` at `j=0`: https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/initarray.c#L123-L124

**Comment by bashtage** [comment]
Yes, I see.  What does `PyArray_DATA` return for an empty array?  A quick check on Windows indicates that it always contains 0.

**Comment by eric-wieser** [comment]
In principle it could return anything it likes, since the expectation is there are 0 bytes under the pointer. In practice, I think we always allocate some memory, because malloc(0) is implementation defined.

**Comment by rkern** [comment]
Regardless, I'm pretty sure that we don't want to make an API guarantee that the allocated memory contains any particular value, so we ought to never use that dummy value for code that is intended to produce reproducibility. :-)
