### ISSUE TITLE
uint64 and int in integer-division returns float

### ISSUE THREAD

**Issue by PrometheusPi** [numpy/numpy#9833]
When using **uint64 data type with any (signed) integer data types in an integer divisions** `//` the result is a float, not an int. For any other `np.uint` an integer is returned. Is this the expected behavior - if yes why? Or should this be casted to an int instead?

**Example code:**
```python
import numpy as np

type(np.int64(12) // np.uint64(5))
# returns numpy.float64 (2.0) --> FLOAT value!

type(np.int64(12) // np.uint32(5))
# returns numpy.int64 (2)

type(np.uint64(12) // np.int64(5))
# returns numpy.float64 (2.0) --> FLOAT value!

type(np.uint64(12) // np.uint64(5))
# returns numpy.uint64 (2)
```

I am using python 3.4 with numpy 1.10.4 on OS X 10.11.6 and a python 3.4.3 with numpy 1.12.0b1 on  Ubuntu 14.04.5 LTS.

**Comment by eric-wieser** [comment]
The bug here is actually _"When using `np.uint64` and `np.signed_integer` in **any arithmetic**, the result is promoted to `float64`"_

**Comment by shoyer** [comment]
This is actually intentional, although you are certainly not the first person to be displeased with it.

Let's keep this discussion consolidated to https://github.com/numpy/numpy/issues/5745

**Comment by PrometheusPi** [comment]
@eric-wieser and @shoyer Thank you for your reply. The reference helped a lot in understanding the numpy strategy at this point.

**Comment by ax3l** [comment]
Huh, so that design decision means for the above examples:

If we do int arithmetics, where an `(u)int64` operation is precise up to **20** *significant digits*, numpy trades the potential range difference of the input of a factor 2x for a *precision decrease* to **15-16** *significant digits* in `float64` 🦉
