### ISSUE TITLE
f2py: patches to build with gfortran/mingw on windows (Python 2.7 & 3.x)

### ISSUE THREAD

**Issue by briantoby** [numpy/numpy#9839]
With Python 2.7 for reasons unclear, the environment variable WINDIR was being cleared in the build process, so changing line 932 of Anaconda/Lib/site-packages/numpy/distutils/mingw32ccompiler.py
from this

         winsxs_path = os.path.join(os.environ['WINDIR'], 'winsxs')

to this allowed the build to complete

        winsxs_path = os.path.join(os.environ.get('WINDIR','C:\WINDOWS'), 'winsxs')

For Python 3.x, also in mingw32ccompiler.py there is a line lib_dirs = os.path… which defeats the purpose of looking for the dll. This change in lines 266-268 allowed the build to work:

    for stem in stems:
        for folder in sub_dirs:
            lib_dirs.append(os.path.join(stem, folder))

**Comment by rgommers** [comment]
Thanks @briantoby. Are you able to submit these changes as a pull request? If so that would help get this integrated.

One review comment: I think ``'C:\WINDOWS'`` requires either a double backslash or a raw string.

**Comment by briantoby** [comment]
Ralf, my coworker (who does not use git ) provided this info. I don’t have a windows machine. Providing a pull request would be hard.

Brian

Sent from a powerful small device but with weak eyes.

On Oct 28, 2017, at 11:15 PM, Ralf Gommers <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @briantoby<https://github.com/briantoby>. Are you able to submit these changes as a pull request? If so that would help get this integrated.

One review comment: I think 'C:\WINDOWS' requires either a double backslash or a raw string.

**Comment by rgommers** [comment]
Okay no worries, I'll try to do it in the next week or so.
