### ISSUE TITLE
DOC: doc error in np.absolute

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#9841]
The last example uses np.abs instead of np.absolute.

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.absolute.html

**Comment by eric-wieser** [comment]
Not really an error - `np.abs is np.absolute`

**Comment by matheusportela** [comment]
This issue should be closed since #10220 already took care of it, right?

**Comment by mvinoba** [comment]
@eric-wieser I think this issue should be closed now, pinging you so you can evaluate closing it. I bumped into this issue while searching for the `difficulty: Easy` tag.
