### ISSUE TITLE
Documentation Error on Numpy.Mean page

### ISSUE THREAD

**Issue by aswinvk28** [numpy/numpy#9843]
A documentation error on numpy.mean has been spotted.

Please see attached screenshot
![numpy mean numpy v1 13 manual](https://user-images.githubusercontent.com/1046939/31359318-67795cfe-ad41-11e7-8ef3-639621c1e678.png)

**Comment by bashtage** [comment]
I don't see anything obviously wrong.  Could you elaborate?

**Comment by aswinvk28** [comment]
Sorry my mistake, I'll close the issue

**Comment by aswinvk28** [comment]
is it possible to delete this issue ?

**Comment by charris** [comment]
No, but I added an `Invalid` label. Don't worry about it, there are thousands of issues and few are going to notice.
