### ISSUE TITLE
BUG: memory leak in numpy.dot

### ISSUE THREAD

**Issue by mcdigman** [numpy/numpy#9844]
In numpy 1.13.1 running with Python 2.7.14 on OSX El Capitan, the following code causes python's memory to run out of control and crashes my system: 

`
import numpy as np

v = np.array([1.])
res = np.array([[1.]])
#loop continues until system runs out of memory 
while True:
    np.dot(res[0:0,0:0],v[0:0])
`

Each iteration of the loop leaks about 107 bytes of memory, and on my system the loop allocates about 9 Gb of ram in 90 seconds.

**Comment by pv** [comment]
Maybe was fixed in 1.13.3

10.10.2017 2.13 "mcdigman" <notifications@github.com> kirjoitti:

**Comment by mcdigman** [comment]
Seems it is fixed in 1.13.3. Thought I had the latest version.
