### ISSUE TITLE
np.linalg.norm is broken with float32 and arrays > 2 ** 28

### ISSUE THREAD

**Issue by kohr-h** [numpy/numpy#9852]
I get this:
```python
>>> a = np.ones(2 ** 28, dtype='float32')
>>> np.linalg.norm(a) == np.sqrt(a.size)
True
>>> a = np.ones(2 ** 28 + 2 ** 12 + 1024, dtype='float32')
>>> np.isclose(np.linalg.norm(a), np.sqrt(a.size))
True
>>> a = np.ones(2 ** 28 + 2 ** 12 + 2048, dtype='float32')
>>> np.isclose(np.linalg.norm(a), np.sqrt(a.size))
False
```
For `float64`, everything is fine even with size `2 ** 32`, so 32-bit integer indices are not the immediate issue.

**Comment by eric-wieser** [comment]
Do you get the problem comparing `a.sum()` to `a.size`?

**Comment by kohr-h** [comment]
No, no problem there.

A potentially interesting finding: `np.dot` behaves like this:
```python
>>> a = np.ones(2 ** 29, dtype='float32')
>>> int(np.dot(a, a))
268435456
>>> int(np.dot(a, a)) * 2 == a.size
True
```
The result is wrong by a factor of 2 exactly.

**Comment by kohr-h** [comment]
I get the same result with `sdot` from SciPy:
```python
>>> sdot = scipy.linalg.blas.get_blas_funcs('dot', dtype='f')
>>> int(sdot(a, a, a.size))
268435456
```
I guess Numpy also uses BLAS dot in this case.

**Comment by eric-wieser** [comment]
On my machine it's wrong in a different way:
```
>>> int(np.dot(a, a))
67108864
```

**Comment by kohr-h** [comment]
> On my machine it's wrong in a different way:
> 
> >>> int(np.dot(a, a))
> 67108864

:-) 

The issue only occurs with openblas it seems, just tested with MKL and results are correct.

**Comment by kohr-h** [comment]
Since this is likely platform-dependent I should add that I'm using 64 bit Linux.

**Comment by matthew-brett** [comment]
If it is a bug in OpenBLAS, we should raise an issue with them ...

**Comment by matthew-brett** [comment]
Here's me on numpy with Accelerate on Mac:

```
In [14]: a = np.ones(2 ** 29, dtype='float32')

In [15]: int(np.dot(a, a))
Out[15]: 268435456
```

**Comment by kohr-h** [comment]
> If it is a bug in OpenBLAS, we should raise an issue with them ...

I'll do that.

**Comment by kohr-h** [comment]
I get a different but also wrong behavior of vanilla OpenBLAS with the `develop` branch. I'll test the release version that I currently use with Numpy next.

**Comment by kohr-h** [comment]
Repeating a comment on the OpenBLAS issue: How does Numpy use MKL for dot products? I'm asking since the MKL and OpenBLAS backends behave differently: the former does not suffer from this issue, the latter does.

**Comment by kohr-h** [comment]
From the upstream issue: there is also a `dsdot` function that takes `float` arrays and accumulates and returns in `double` precision, I think part of LAPACK. It's somewhat slower than `sdot` but gives correct results in the upstream issue case.

**Comment by ahmedahmedov** [comment]
I have a similar issue with np.dot. 
np.dot(a,a) returns a negative number, which never happen. 
Related question with a working example here: 
[](https://stackoverflow.com/questions/47206028/numpy-dot-product-of-two-same-vectors-returns-a-negative-number?noredirect=1#comment81364053_47206028)

**Comment by ahmedahmedov** [comment]
I have the following output for the original example: 

>>> a = np.ones(2 ** 28, dtype='float32')
>>> np.linalg.norm(a) == np.sqrt(a.size)
False
>>> a = np.ones(2 ** 28 + 2 ** 12 + 1024, dtype='float32')
>>> np.isclose(np.linalg.norm(a), np.sqrt(a.size))
False
>>> a = np.ones(2 ** 28 + 2 ** 12 + 2048, dtype='float32')
>>> np.isclose(np.linalg.norm(a), np.sqrt(a.size))
False

**Comment by kohr-h** [comment]
There is [a fix](https://github.com/xianyi/OpenBLAS/pull/1329) available in openblas now (will be in the next release I guess). The `sdot` function still behaves exactly the same, but the `dsdot` function that accumulates in double precision is now optimized and nearly as fast as `sdot` (+2 % roughly). My suggestion is that `numpy.dot` should use `dsdot` for extended precision in the range of sizes 2^28 and above.

**Comment by charris** [comment]
On fedora with Atlas it also fails, but at a different point. I find the stopping point a bit odd, I'd expect the accumulation to fail to increment at a different spot, so probably multiple threads/registers are being used. The `sum` below is computed in double precision:
```
exp: 25, dot: 33554432.0, sum: 33554432.0
exp: 26, dot: 67108864.0, sum: 67108864.0
exp: 27, dot: 67108864.0, sum: 134217728.0
exp: 28, dot: 67108864.0, sum: 268435456.0
exp: 29, dot: 67108864.0, sum: 536870912.0
```

**Comment by charris** [comment]
> My suggestion is that numpy.dot should use dsdot for extended precision in the range of sizes 2^28 and above.

The result would be double, which is likely a problem.

**Comment by kohr-h** [comment]
> The result would be double, which is likely a problem.

Why would that be a problem? What's wrong about casting to `float`?

In any case, an alternative is to use `sdsdot` which uses the same loop as `dsdot` but returns `float` (and has an extra parameter `alpha`, I think to add a constant to the result -- pretty useless).

**Comment by kohr-h** [comment]
As of 0.3.0, openblas has an optimized DSDOT implementation that could be used to fix this issue. If the double accumulator is problematic (although I don't see why), there's still SDSDOT.

**Comment by kohr-h** [comment]
Not sure what fixed the issue, but I don't see it anymore in (numpy 1.13 and) latest openblas. Closing.
