### ISSUE TITLE
Why is array_split returning empty dataframes?

### ISSUE THREAD

**Issue by CptanPanic** [numpy/numpy#9853]
I have a dataframe as below, but when I try array_split, I just get empty dataframes.  This works for me for some dataframes, but not others.  Maybe it is because indicies are not integers?  What is the issue?  This is python3 with numpy 1.13.3

```
>> test.head()
                     open high  low close volume
736481.000000  217.029577  NaN  NaN   NaN    NaN
736481.041667  213.684360  NaN  NaN   NaN    NaN
736481.083333  217.213991  NaN  NaN   NaN    NaN
736481.125000  220.794124  NaN  NaN   NaN    NaN
736481.166667  221.086816  NaN  NaN   NaN    NaN
>>> numpy.array_split(test,2)
[Empty DataFrame
Columns: [open, high, low, close, volume]
Index: [], Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []]
>>>

**Comment by shoyer** [comment]
My guess is that array_split does array indexing (with `[]`), which can have unpredictable effect on pandas DataFrames. There’s not really a clear fix here. In general it’s not really possible for numpy functions to work on every alternative data type.

**Comment by dalito** [comment]
You could pass the numpy representation of the data in the dataframe to the numpy function ([pandas.DataFrame.values](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.values.html)).
```
>>> np.array_split(test.values, 2)
[array([[ 217.029577,         nan,         nan,         nan,         nan],
        [ 217.029577,         nan,         nan,         nan,         nan],
        [ 217.213991,         nan,         nan,         nan,         nan]]),
 array([[ 220.794124,         nan,         nan,         nan,         nan],
        [ 221.086816,         nan,         nan,         nan,         nan]])]
```
numpy does not claim to work with pandas.DataFrames. So I think this is not a numpy issue. Close it?

**Comment by charris** [comment]
Yep, lets close it. If nothing else, we don't test against pandas.

**Comment by endrebak** [comment]
I too experience this, but as long as you just ignore the empty dfs, the result seems to be okay.

```
splits = np.array_split(...)
nonempty = [df for df in splits if not df.empty]
```
