### ISSUE TITLE
numpy.savetxt does not save arrays to previously opened text files in Python 3.x

### ISSUE THREAD

**Issue by AndrewUshakov** [numpy/numpy#9859]
Despite the information at the page [https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.savetxt.html](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.savetxt.html) that numpy.savetxt() "Save an array to a text file." it does not, at least if use Python 3.6.3. See test below:
```Python
# -*- coding: utf-8 -*-

import numpy as np

if __name__ == '__main__':
    with open('file.txt', 'w') as f:
        a = np.zeros(3)
        np.savetxt(f, a)
```
which fails with:
```text
Traceback (most recent call last):
  File "C:\Program Files\Python 3.6\lib\site-packages\numpy\lib\npyio.py", line 1254, in savetxt
    fh.write(asbytes(format % tuple(row) + newline))
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:/My Documents/PyCharm/tst/tst6.py", line 9, in <module>
    np.savetxt(f, a)
  File "C:\Program Files\Python 3.6\lib\site-packages\numpy\lib\npyio.py", line 1258, in savetxt
    % (str(X.dtype), format))
TypeError: Mismatch between array dtype ('float64') and format specifier ('%.18e')

Process finished with exit code 1
```
All is working if open file in binary mode, but in this case you can't use print(...) to manually add title/comments to the file. That is, code below works in Python 2.7 but does not in Python 3.6:
```Python
# -*- coding: utf-8 -*-

from __future__ import print_function
import numpy as np

if __name__ == '__main__':

    with open('file.txt', 'wb') as f:
        a = np.zeros(3)
        print('title', file=f)
        np.savetxt(f, a)
```

So, my suggestion is not to only correct documentation, but also enhance functionality of utility in 3.x environment.

/Andrew

**Comment by CatEars** [comment]
It seems that there is an older PR which aims to handle this by providing the encoding option for savetxt: https://github.com/numpy/numpy/pull/4208/files#diff-1df6521a15075ac4e7c5c89d091da2fbL1063

**Comment by WarrenWeckesser** [comment]
I haven't tracked down which change fixed it (perhaps the one linked above), but this appears to be working now.  I'm closing the issue, but if there is a combination of (supported) Python version and platform for which this problem still exists, please comment and reopen the issue.
