### ISSUE TITLE
Import numpy in Python 3.6.0 for Win 7 32bit: numbers.Integral.register(integer) raise AttributeError ("module 'numbers' has no attribute Integral')

### ISSUE THREAD

**Issue by Dafydd-W** [numpy/numpy#9872]
Hey all, I'm trying to import my newly installed numpy v1.13.4 to Python programs. However, I get the following error code from both Command Prompt and from Visual Studio 2017:

[import_numpy.txt](https://github.com/numpy/numpy/files/1389560/import_numpy.txt)

Curiously, I don't get this when I'm doing it straight from a Python terminal. But, any help would be appreciated. Thanks.

**Comment by eric-wieser** [comment]
Is one of your files called `numbers.py`, which is hiding the builtin `numbers`?

**Comment by Dafydd-W** [comment]
Embarrassingly, yes. Thanks.

**Comment by satishgaurav** [comment]
I am still getting this error eve
![capture](https://user-images.githubusercontent.com/36672530/41787050-d9c514f0-7664-11e8-89e4-fead6c960eb3.PNG)
n after changing the name of numbers.py

**Comment by satishgaurav** [comment]
I was getting this error because I had one program named numbers.py. Great no explanation needed.

**Comment by khoatcao** [comment]
Dear satishgaurav. I met the same issue like you. Please tell me how to fix it. 
thanks

**Comment by journaldev** [comment]
I faced the same error, simple solution is to rename your project file.

**Comment by Zachary125** [comment]
I had the same issue. Changing the file name (numbers.py) will do the job. Thanks a lot.
