### ISSUE TITLE
nonempty char array created from numpy.empty on python 2.7 - secret documents hidden in numpy.empty?!

### ISSUE THREAD

**Issue by cwtsai** [numpy/numpy#9882]
I am running numpy 1.13.3 in Python 2.7.13 on OS 10.11. While trying to create a char array using numpy, I have found something interest. When I run:
`np.empty([1000],dtype ='str')`
in interactive shell, I got the following array which contains nonempty elements:

       array(['', '', '', '', '', '', '', '\`', '', '', '', '', '', '', '', '\`',
       '?', '', '', '', '', '', '', '', '\xff', '\xff', '\xff', '\xff',
       '\xff', '\xff', '\xff', '\xff', '', '', '', '', '\n', ' ', ' ', ' ',
       ' ', 'n', 'e', 'w', 'b', 'y', 't', 'e', 'o', 'r', 'd', 'e', 'r'
       ........
       'r', 'd', 'e', 'r', '.', '\n', '\n', ' ', ' ', ' ', ' '],
       dtype='|S1')

After combining all the elements, it turns out to be a part of [the explanation document of numpy.dtype.newbyteorder](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.dtype.newbyteorder.html#numpy-dtype-newbyteorder):

    newbyteorder(new_order='S',
       "'", ')

    Return a new `dtype` with a different byte order.

    Changes are also made in all fields and sub-arrays of the data type.

    The `new_order` code can be any from the following:

    * 'S' - swap dtype from current to opposite endian
    * {'<', 'L'      '} - little endian
    * {'      '>', 'B'} - big endian
    * {'=', 'N'} - native order
    * {'|', 'I'} - ignore (no change to byte order)

    Parameters
    ----------
    new_order : str, optional
        Byte order to force; a value from the byte order specifications
        above.  The default value ('S') results in swapping the current
        byte order. The code does a case-insensitive check on the first
        letter of `new_order` for the alternatives above.  For example,
        any of 'B' or 'b' or 'biggish' are valid to specify big-endian.

    Returns
    -------
    new_dtype : dtype
        New `dtype` object with the given change to the byte order.

1) This is repeatable within the same python shell, but it's not repeatable if I open a new terminal to run the other python shell in parallel where a different non-empty array came up. 

2) I got identical results if run np.chararray:
`np.chararray(1000)`

2) The results are different if I request the array sizes other from 1000, such as:
`np.empty([999],dtype ='str')`
it gives me a different non-empty char array with nonsense in it.
 
3) When I run python 3.5.1 on the same computer with numpy v.1.13.3, the array is clean as expected.

4) When I run the same command on the other computer of mine (with python 2.7.14, numpy version 1.13.1), I also got a different non-empty array. 

I guess it is a problem only for numpy on python 2.7?

**Comment by eric-wieser** [comment]
This is by design. `np.empty` means:

> Return a new array of given shape and type, **without initializing entries**.

What you're seeing is the contents of uninitialized memory, which could be absolutely anything.

If you want empty strings, use `np.zeros`

**Comment by eric-wieser** [comment]
Now, if writing to this array ends up actually changing the docstring of `newbyteorder`, then you have found a bug!
