### ISSUE TITLE
Ufunc where parameter causes array to be silently read out of bounds

### ISSUE THREAD

**Issue by sergiocallegari** [numpy/numpy#9886]
When the `where` argument of a `ufunc` has a shape that exceeds that of the input argument of the ufunc, arrays are silently read out of bounds. For instance

```
np.log([10], where=[True, False])
Out[58]: array([  2.30258509,  31.5       ])
```

Is this the intended behavior?

**Comment by pv** [comment]
Are you sure it's a read out of bounds? It can also be just 
uninitialized memory (because where=False for the element, no value is 
set to it and it is not zeroed).

**Comment by eric-wieser** [comment]
A pretty simple test is to reverse the `where` array:
```
>>> np.log([10], where=[False, True])
array([  5.03403489e+223,   2.30258509e+000])
```
An out of bounds error shouldn't mess up for entry `0`, so this looks like it's the intended behaviour `pv` describes.

**Comment by callegar** [comment]
OK, now I understand. Since the where is broadcast with the argument, the output get the length of the wider. The output array is allocated but not initialized. Because the function is not computed where "where" is false, some buckets in the output remain uninitialized.

Makes sense, sorry for the noise. Wonder if the documentation could be enriched a little.

**Comment by eric-wieser** [comment]
> Wonder if the documentation could be enriched a little.

You're right, the descriptions don't suggest that at all right now. The relevant docstrings are in `numpy\core\code_generators\ufunc_docstrings.py` and `numpy\doc\source\reference\ufuncs.rst`

What you're seeing is the interaction between `out == None` and `where != True` - the docs for `where` only describe the case when `out != None`.

Feel free to submit a patch with improved wording, or even just file an issue suggesting the new docstring.
