### ISSUE TITLE
Compiler error with VS2017, Python 3.6.3-64bit

### ISSUE THREAD

**Issue by dalito** [numpy/numpy#9895]
```
  c:\users\XXX\appdata\local\temp\pip-g9v8dgwi-build\numpy\linalg\lapack_lite\f2c_s_lapack.c(18273) : fatal error C1001: An internal error has occurred in the compiler.
  (compiler file 'f:\dd\vctools\compiler\utc\src\common\error.c', line 792)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
  LINK : fatal error LNK1257: code generation failed
```
numpy revision(master): e657629bbc2bfb880a1b2fa24a39c5921c1f965e
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25547 for x64
(This compiler is part of [build-tools-for-visual-studio-2017](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017) downloaded today.)

**Comment by pv** [comment]
ICE pretty much means a bug in the compiler, so probably hopefully microsoft fixes their bugs eventually.

**Comment by dalito** [comment]
After installing the VC++ compiler from VS2015 the build succeeds. Compiler version:
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24225.1 for x64

There are several reports about compilation errors with the VS2017 compiler in other projects. I'll wait for a fix by microsoft and use the compiler from VS2008 in the meantime.
