### ISSUE TITLE
replace HOW_TO_DOCUMENT with link to numpydoc.rtfd.io

### ISSUE THREAD

**Issue by jnothman** [numpy/numpy#9903]
We've just created docs for numpydoc on readthedocs which include the content from [doc/HOW_TO_DOCUMENT.rst.txt](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt). Perhaps that should be removed from this repository and replaced with a link to http://numpydoc.readthedocs.io/en/latest/format.html

**Comment by eric-wieser** [comment]
Seems pretty reasonable

**Comment by charris** [comment]
Could someone write a clear explanation of the use of single backticks? I see that single backticks are only mentioned with respect to variable names, but that is not their only use. How does numpydoc handle backticks in general?

**Comment by jnothman** [comment]
Single backticks are interpreted based on sphinx's default_role to my
knowledge. numpy sets this to anylink which means, I think, it will try
link to any autosummary object, and otherwise italicise.

**Comment by rgommers** [comment]
That file is linked to directly in many places, so needs to be replaced by a link and not just removed.

**Comment by mattip** [comment]
Changed in PR #10878
