### ISSUE TITLE
BUG: np.isin and np.in1d fails on unsortable object arrays

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9914]
This is a problem for object arrays that are unsortable, such as those which
* are heterogenous (py 3)
* contain `None` (py 3)
* contain objects where `cmp(a, b) == 1` (#9874)

`np.isin` uses sorting for efficiency on large arrays, but in these cases this isn't valid. For example:

```python
>>> np.isin(1, [None]*5)
array(False, dtype=bool)
>>> np.isin(1, [None]*10)
TypeError: unorderable types: NoneType() < NoneType()
```

In the latter case (#9874) the problem is even worse, as a wrong result is silently produced.

I don't think there's any option here but to drop the efficient behaviour when `dtype == object`

**Comment by jdoepfert** [comment]
@eric-wieser I made a PR with your suggestion, i.e. dropping the sorting when `dtype == object`
