### ISSUE TITLE
`np.random.binomial` consistently shows artefacts

### ISSUE THREAD

**Issue by MichaelClerx** [numpy/numpy#9915]
The following code consistently shows two odd peaks, despite using a different see each time:

    import numpy as np
    import matplotlib.pyplot as pl
    n = 1000000
    b = 35
    binomial = np.random.binomial(100, 0.5, n)
    pl.figure()
    pl.hist(binomial, bins=b, range=[30, 70], alpha=0.5, edgecolor='k')
    pl.show()

![binomial](https://user-images.githubusercontent.com/517644/31940846-91d6ec92-b8b7-11e7-82e6-7e2ddc28eedd.png)

**Comment by matthew-brett** [comment]
This is because of the bins widths - a couple of the bins cover more than one integer.  Try:

```
pl.hist(binomial, bins=range(30, 71), alpha=0.5, edgecolor='k')
```

to force integer bin widths.

**Comment by MichaelClerx** [comment]
Thanks!

**Comment by matthew-brett** [comment]
I just hit the same thing a few days ago ...
