### ISSUE TITLE
Need numpy.lib.pad with unmirrored copying...

### ISSUE THREAD

**Issue by Felix-neko** [numpy/numpy#9917]
Hi folks! I want to use `numpy.lib.pad` function to pad my array. I want to simply copy first 100 elements of my array at its beginning and 100 last elements at the end.
Alas, only reflected copying is supported. Can you also support umirrored padding?

Just now I have to do this:
    `x_data_padded = np.concatenate((x_data[:self._filter.size], x_data, x_data[-self._filter.size:]))`

**Comment by mattip** [comment]
Closing. Concatenate is better suited to this task. Please reopen if I misunderstood or if you disagree.
