### ISSUE TITLE
DOC: incorrect suffixes for math constants

### ISSUE THREAD

**Issue by person142** [numpy/numpy#9922]
From the documentation:

"The following math constants are available in npy_math.h. Single and extended precision are also available by adding the F and L suffixes respectively."

From looking at the code that should be "f and l suffixes respectively" for some of them:

 https://github.com/numpy/numpy/blob/3b7908d299fc3287486bbe453e2335c1fa50fc29/numpy/core/include/numpy/npy_math.h#L88

https://github.com/numpy/numpy/blob/3b7908d299fc3287486bbe453e2335c1fa50fc29/numpy/core/include/numpy/npy_math.h#L102

Note however that for `NPY_INFINITY` and a couple of others the correct suffixes are `F` and `L`.

**Comment by charris** [comment]
"F" and "L" are valid suffixes. Why do you say there is a problem?

**Comment by charris** [comment]
Ah, you mean the aliases.
