### ISSUE TITLE
Numpy 1.11 fails with new mkl on Appveyor with Python 3.4

### ISSUE THREAD

**Issue by matteobachetti** [numpy/numpy#9933]
We have CI tests running on Appveyor with old and new numpy versions. We noticed that when fixing numpy to 1.11, a strange error was reported by `scipy`:
```
    import scipy.stats
  File "C:\conda\envs\test\lib\site-packages\scipy\stats\__init__.py", line 344, in <module>
    from .stats import *
  File "C:\conda\envs\test\lib\site-packages\scipy\stats\stats.py", line 173, in <module>
    import scipy.special as special
  File "C:\conda\envs\test\lib\site-packages\scipy\special\__init__.py", line 636, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.
Command exited with code 1
``` 
https://ci.appveyor.com/project/matteobachetti/stingray/build/1.0.248/job/4qcjxbtslfam3dhp

However, the scipy version was the same in the various cases and only `numpy` was changing. Fixing the `mkl` version to 2017.0.3 (suggestion by @bsipocz ) solved the problem.  

Can someone check and/or update the requirements of the old versions of the library? Thanks in advance

**Comment by matthew-brett** [comment]
I think you're using conda packages?  We don't build those - maybe you could try the Anaconda support channels - or conda-forge if you got the packages from them?

**Comment by matteobachetti** [comment]
Ok, I'll do that. Thanks!

**Comment by mattip** [comment]
Can we close this?

**Comment by matteobachetti** [comment]
@mattip yes. Sorry for not letting you know before
