### ISSUE TITLE
pip install numpy fails in MSYS2 due to setup.py problem

### ISSUE THREAD

**Issue by jafetmorales** [numpy/numpy#9935]
Am using Python 3.6.2 in MSYS2. The installation is unable to build the wheel:

> Running setup.py bdist_wheel for numpy ... error

Then many pages are printed with the output of command setup.py bdist_wheel with warnings such as:

>   x86_64-pc-msys-gcc: _configtest.c
>   _configtest.c:1:5: warning: conflicting types for built-in function ‘sinf’
>    int sinf (void);
>        ^~~~

After that it tries to run other commands with setup.py and it also fails:

> ----------------------------------------
>   Failed building wheel for numpy
>   Running setup.py clean for numpy
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pcj9wcf2/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
>   Running from numpy source directory.
> 
>   `setup.py clean` is not supported, use one of the following instead:
> 
>     - `git clean -xdf` (cleans all files)
>     - `git clean -Xdf` (cleans all versioned files, doesn't touch
>                         files that aren't checked into the git repo)
> 
>   Add `--force` to your command to use it anyway if you must (unsupported).
> 
> 
>   ----------------------------------------
>   Failed cleaning build dir for numpy
> Failed to build numpy
> Installing collected packages: numpy
>   Running setup.py install for numpy ... error

**Comment by xoviat** [comment]
Numpy isn't tested on MSYS2. That said, it would help for you to post all of the output as a gist.

**Comment by jafetmorales** [comment]
[output.txt](https://github.com/numpy/numpy/files/1427820/output.txt)

**Comment by pv** [comment]
Can you compile any other packages that have C extensions?

There's something strange going on with the path names 
"mingw64_nt-6.1-2.9.0(0.318/5/3)" --- that the platform tag contains 
parentheses and slashes looks wrong. iiuc, these come from the python's 
distutils, so the problem may also be there.

**Comment by xoviat** [comment]
Now that's interesting:

```
  compile options: '-Ibuild/src.mingw64_nt-6.1-2.9.0(0.318/5/3)-x86_64-3.6/numpy/core/src/npymath -Inumpy/core/include -Ibuild/src.mingw64_nt-6.1-2.9.0(0.318/5/3)-x86_64-3.6/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.6m -Ibuild/src.mingw64_nt-6.1-2.9.0(0.318/5/3)-x86_64-3.6/numpy/core/src/private -Ibuild/src.mingw64_nt-6.1-2.9.0(0.318/5/3)-x86_64-3.6/numpy/core/src/npymath -Ibuild/src.mingw64_nt-6.1-2.9.0(0.318/5/3)-x86_64-3.6/numpy/core/src/private -Ibuild/src.mingw64_nt-6.1-2.9.0(0.318/5/3)-x86_64-3.6/numpy/core/src/npymath -Ibuild/src.mingw64_nt-6.1-2.9.0(0.318/5/3)-x86_64-3.6/numpy/core/src/private -Ibuild/src.mingw64_nt-6.1-2.9.0(0.318/5/3)-x86_64-3.6/numpy/core/src/npymath -c'
```

**Comment by xoviat** [comment]
Likely the -I options should be enclosed in quotes but aren't. But as @pv noted, those appear odd.

**Comment by jafetmorales** [comment]
I attempted to install another package that is a C extension and it complained about gcc:
https://gist.github.com/jafetmorales/7e9987e3ad1f89c46f2ab15f31dde761

**Comment by pv** [comment]
btef is not compatible with Python 3, try checking against some python 3 
compatible module.

**Comment by fa15073** [comment]
"mingw64_nt-6.1-2.9.0(0.318/5/3)" is uname output in MSYS2, not sure why only some extensions have this issue. Is it possible to fix the path name handling in numpy?

**Comment by fa15073** [comment]
here is workaround for the invalid file path:
>>> from distutils.util import get_platform
>>> get_platform()
'mingw64_nt-6.3-2.10.0(0.325/5/3)-x86_64'

distutils support an environ to override uname, replace the '/' and '(' with whatever makes sense to you
$ export _PYTHON_HOST_PLATFORM="mingw64_nt-6.3-2.10.0-x86_64"

per https://github.com/numpy/numpy/issues/8362 the rest should work, hopefully

**Comment by crajun** [comment]
Fails for me as well using MYS2 3.0.2 on Windows 7.

gist: https://gist.github.com/crajun/e3e73637fa6374404d84cf733c2991bb

$ python --version
3.7.4
$ pip --version
19.2.1
$ which gcc
/mingw64/bin/gcc
$ gcc --version
gcc: (Rev 3, Built by MSYS2 project) 9.1.0
$ which ld
/mingw64/bin/ld
$ ld --version
GNU ld (BNU Binutils) 2.30
$ uname
MSYS_NT-6.1-7601

**Comment by seberg** [comment]
I suspect MSYS2 setup got a pretty long way since this issue was opened (and even 2019).  Since its an installation issue and old, I am going to close it.  Happy for a new issue to be opened, if anyone still runs into something similar.
