### ISSUE TITLE
Add the flang compiler.

### ISSUE THREAD

**Issue by xoviat** [numpy/numpy#9940]
This is a tracking issue for adding support for flang: the first free, open source, CRT-compatible fortran compiler on windows. We've managed to confirm the basic functionality and now we want to see what it can compile.

I will submit a PR for this sometime soon.

**Comment by rgommers** [comment]
Interesting. Looking forward to this!

**Comment by xoviat** [comment]
Relevant PR is #9942. I'm going to attempt to compile scipy and see what happens.

**Comment by xoviat** [comment]
Anaconda installation is:

```
conda install -c isuruf/label/flang clangdev
conda install -c isuruf/label/flang flangdev
```

**Comment by jakirkham** [comment]
cc @isuruf

**Comment by xoviat** [comment]
He already knows about this. We're working on resolving a difficult bug that we found.

**Comment by insertinterestingnamehere** [comment]
This is really great. Having a Fortran compiler for windows that is both freely available and ABI compatible is a huge deal. Let me know if I can help with testing, etc.

**Comment by xoviat** [comment]
Anyone know how to add static runtime libraries to the link command?

**Comment by isuruf** [comment]
`-static-flang-libs`

**Comment by isuruf** [comment]
@insertinterestingnamehere, for OpenBLAS, we need to fix CMake to support Flang on Windows. We can use some help there. https://gitlab.kitware.com/cmake/cmake/issues/17384

**Comment by isuruf** [comment]
Ah. Here's what I found from a github search, https://github.com/numpy/numpy/blob/c90d7c94fd2077d0beca48fa89a423da2b0bb663/numpy/distutils/fcompiler/absoft.py#L93

**Comment by insertinterestingnamehere** [comment]
Alright, I'll see if I can make any progress past what you already have in https://gitlab.kitware.com/cmake/cmake/merge_requests/1430. I should be able to look at it some this afternoon.

**Comment by xoviat** [comment]
Update: I managed to compile SciPy with MKL/flang (OpenBLAS is still WIP at this point). With full mode, we get three test failures in 520 seconds vs 480 seconds for OpenBLAS/gfortran.

**Comment by isuruf** [comment]
@xoviat, here's a openblas DYNAMIC_ARCH=1 NOFORTRAN=0 build with flang. [libopenblas-win32-x86_64-flang-v0.2.20-158-gcc26cdc.zip](https://github.com/numpy/numpy/files/1463438/libopenblas-win32-x86_64-flang-v0.2.20-158-gcc26cdc.zip)

**Comment by xoviat** [comment]
What about conda though? It will be easier to update the openblas build.

**Comment by xoviat** [comment]
Also, what happened at the meeting? Did you go?

**Comment by isuruf** [comment]
Meeting is not yet finalized. I'll update conda-forge package, but it'll take more than 2 hours on appveyor, because we have to use nmake instead of ninja. (I tried and with 1 hour only 40% finished)

**Comment by xoviat** [comment]
Idea: compile dynamic arch with ninja then compile no Fortran and link the static libs together.

**Comment by xoviat** [comment]
Link will ignore all of the symbols except Fortran in the second lib.

**Comment by isuruf** [comment]
Using `NMake Makefiles JOM` might work.
