### ISSUE TITLE
discussion: updating the released wheels to VS2017

### ISSUE THREAD

**Issue by xoviat** [numpy/numpy#9958]
Although MSVC 2015 and MSVC 2017 are ABI compatible, numpy generated a library with link-time code generation (LTCG) enabled, which is not compatible. This means that downstream projects cannot be built against the released numpy, but they need to compile from source, and then build against that (note that a project compiled against a numpy that's build from source would still work with DLLs compiled with VS2015).

The question is: should numpy compile wheels for Python 3.5 and Python 3.6 with VS2017? Note that Python 3.6 has made VS2017 the default. And how can we coordinate this in a somewhat reasonable way?

**Comment by njsmith** [comment]
Would disabling LTCG make our binaries more broadly compatible?

**Comment by xoviat** [comment]
Yes, but it would reduce performance.

**Comment by xoviat** [comment]
LTCG doesn't need to be disabled everywhere actually. Just for the .lib files that go into the wheels, if you want to go that route.

**Comment by njsmith** [comment]
If the choice is between "reduced performance" and "it doesn't work at all" then often the former is better... what `.lib` files are we even talking about? `npymath`? Normal downstream projects don't link against anything in numpy (the numpy C API uses a different mechanism that doesn't involve the linker).

**Comment by xoviat** [comment]
Yes, it's npymath. See here: https://ci.appveyor.com/project/xoviat/scipy/build/1.0.7#L5478

**Comment by njsmith** [comment]
Disabling LTCG for npymath seems reasonable. We've never supported link-time optimization for that library before, and very few packages will be affected in any case. I guess if scipy wants to try and optimize this further to allow npymath functions to be inlined or whatever, they also have the option of doing their own build with LTCG enabled (and whichever compiler they want) and then building against that.

**Comment by xoviat** [comment]
Actually, I don't think it would be that bad if LTCG was disabled for only the objects that go into npymath. Scipy could rebuild numpy from source each time they wanted to do a release, but the daily CI builds wouldn't need to be optimized.

**Comment by xoviat** [comment]
In case you're putting that library into your DLLs, you really should build it once with LTCG (for internal use) and once without (for external use).

**Comment by njsmith** [comment]
Do we know whether LTCG actually makes a difference here in practice? Any benchmarks?

**Comment by xoviat** [comment]
I have not run benchmarks on this. It looks like it was switched on in Python 3.5 because someone figured, "well, why not?"

**Comment by dalito** [comment]
Being compatible with both MSVC 2015 and MSVC 2017 would be very desirable.

In my recent attempts to build scipy and numpy I also stumbled about these incompatibilities (on Win10). The incompatibility is especially problematic since some MS installers (IIRC VS 2017) remove the MSVC2015 runtime libraries completely and replace it with the ones from MSVC 2017. This caused problems (=failing tests and segfaults) when using MSVC2015 wheels.

**Comment by bashtage** [comment]
I agree.  I got hit by the after updating VS 2017 to the latest release which added itself above VS 2015.  Building statsmodels failed with an error about versions.

**Comment by xoviat** [comment]
Will submit a PR for this soon if there are no objections.
