### ISSUE TITLE
numpy array memory error

### ISSUE THREAD

**Issue by bfmorriss** [numpy/numpy#9960]
This has haunted me on and off for a while, but I never really see anything about it, so I assume there's either an easy fix that I never noticed, or most people don't run into it... ever.  Let's say I'm working with a large raster (50,000 by 50,000 pixels, uint8) that I need to manipulate in an array (say with numpy.where()).  This array should take up 2.5 gb of memory, but it takes 20 gb to allocate (I assume the default behavior is some 64-bit data type) and then it is cast after the initial allocation and becomes 2.5 gb.  This behavior also occurs with things like copy(), where(), etc.--they throw memory errors if a variable of that size and 64-bits would throw one.

Somewhat related topics and suggestions involve parsing smaller pieces of the image, which is fine, but reassembling the entire image in numpy seems impossible because an array of that size even with a very small data type can never exist.

**Comment by eric-wieser** [comment]
Can you prove your 20GB claim with a code example?\

> it takes 20 gb to allocate (I assume the default behavior is some 64-bit data type) and then it is cast after the initial allocation

That's not how this works, unless you write `np.zeros((50000,50000)).astype(np.uint8)` instead of `np.zeros((50000, 50000), dtype=np.uint8)`

**Comment by bfmorriss** [comment]
```
import numpy as np
from psutil import virtual_memory
mem = virtual_memory()
print(mem)
np.zeros((50000, 50000), dtype=np.uint8)
```

svmem(total=34253840384, available=24564895744, percent=28.3, used=9688944640, free=24564895744)
Traceback (most recent call last):
  File "C:\scripts\typing_problem.py", line 5, in <module>
    np.zeros((50000, 50000), dtype=np.uint8)
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

**Comment by pv** [comment]
You are probably using 32-bit Python, which is the problem.

**Comment by eric-wieser** [comment]
Print out `np.intp` to find out what type the size of an array must fit in. If it prints `int32`, then that's your problem.

**Comment by seberg** [comment]
Closing the issue, the larger then maximum size is definitely expected on 32bit system and not really an out of memory error (which would raise a MemoryError).

**Comment by SaschaHeyer** [comment]
If you reach this page this is might be helpful and also cause the same error message
https://www.kernel.org/doc/Documentation/vm/overcommit-accounting

**Comment by hariprasadprabhu** [comment]
decoder_outputs = np.zeros((2225, 1000, 15000), dtype='float32') 
i am not able to execute this (i have python 64 bit)
i am getting the below error


decoder_outputs = np.zeros((2225, 1000, 15000)).astype(np.unit8)
MemoryError


please Help me out
