### ISSUE TITLE
Build from sources fails when /bin/tcsh is the default shell

### ISSUE THREAD

**Issue by matthew-hoyles** [numpy/numpy#9970]
Building numpy from sources fails when /bin/tcsh is the default shell for the account being used. What matters is the setting of the SHELL environment variable, not what shell is actually running. The workaround is to unset the SHELL variable before building.

Operating system is RHEL 6.8, numpy version is 1.13.3, python version is 2.7.14.

Steps to reproduce:

- Use an account with the default shell set to /bin/tcsh, or set the SHELL environment variable to simulate this.
- Have atlas installed from an official Red Hat rpm (e.g. atlas-sse3 and atlas-sse3-devel).
- Download and expand the numpy sources.
- Run 'python setup.py build' in the source directory.
- Build will fail with an error like:

```
creating build/temp.linux-x86_64-2.7/numpy/core/src/multiarray
creating build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/numpy/core/src/multiarray
creating build/temp.linux-x86_64-2.7/numpy/core/src/private
compile options: '-DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -DATLAS_INFO="\"3.8.4\"" -I usr/include -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/ ore/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/nmp/Python2/include/python2.7 -Ibuild/src.l nux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/n mpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -c'
gcc: numpy/core/src/multiarray/compiled_base.c
Unmatched ".
Unmatched ".
error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -DATLAS_INFO="\"3.8.4\"" -I/usr/include -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Inumpy/core/ nclude -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -In mpy/core/src/umath -Inumpy/core/src/npysort -I/opt/nmp/Python2/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibu ld/src.linux-x86_64-2.7/numpy/core/src/npymath -c numpy/core/src/multiarray/comp                                                                                              build/temp.linux-x86_64-2.7/numpy/core/src/multiarray/compiled_base.o.d" failed
```

Cause of problem:

The command that failed is correctly quoted for bash but not for tcsh ; `-DATLAS_INFO="\"3.8.4\"" ` is the problem. The numpy build process is assembling this command formatted for bash, then using whatever is in the SHELL environment variable to run it. If this is /bin/tcsh the build process fails. The code that does this is in the _exec_command function in the numpy/distutils/exec_command.py module.

Workaround:

Unset the SHELL environment variable before building, with `unsetenv SHELL` for tcsh or `unset SHELL` for bash. With the SHELL variable unset, the numpy build process defaults to using /bin/sh.

**Comment by dmacks** [comment]
We found a similar problem in fink, where part of the build sandboxing is to run under a user that does not have a usable login shell (see fink/fink-distributions/issues/121). While diagnosing that, I found that FreeBSD also was reporting the same problem ([bugzilla entry](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225156)). They now hardcode /bin/sh, and we will likely do the same thing.

**Comment by mattip** [comment]
As a first step we should warn when running under a tscsh-based shell, with a message. I am not sure I like the idea of replacing the user shell under them, it could be flagged as a security vulnerability

**Comment by charris** [comment]
Closing this in favor of #11824, which has more discussion.
