### ISSUE TITLE
BUG: number.__int__ and int(number) are not the same

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9972]
As worked around in #9181, we have two implementation of every `number.__int__`, one in `scalarmath` (`int`), and one in `scalartypes` (`__int__`).

This happens because after calling `PyType_Ready`, we reassign `tp_number`, but the `__int__` slot wrapper has already been created.

It's super misleading that this is the case, and exposes cpython implementation details.

It seems to me it would be safer to not set `__int__` at all until we fix this, rather than having two possibly different implementation to trap the end user

**Comment by mattip** [comment]
Not only because of reassignment after ``PyType_Ready``, also because of CPython quirks. For example, this code has different paths due to CPython not inheriting ``nb_int`` but inheriting ``__int__`` via mro lookup.

It successfully calls ``int(a)`` via ``int_new`` which eventually calls ``int_from_string`` in cpython2.7 abstract.c since ``PyStringArrType_Type.tp_from_number.nb_int`` is ``NULL``. 

It fails with ``a.__int__()`` since ``type(a).mro()`` hits ``numpy.generic`` which has ``gentype_int`` as its ``nb_int`` 
```
>>> a = np.array(['100'])[0]
>>> int(a)
100
>>> a.__int__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: don't know how to convert scalar number to int
```

**Comment by mattip** [comment]
Just to clarify - ``PyStringArrType_Type.tp_as_number`` is not overwritten after ``PyType_Ready`` in ``addscalar_math``, only the numeric types are overwritten, so this is purely a CPython method lookup quirk

**Comment by eric-wieser** [comment]
I'm wondering if the culprit is `ndarray.__int__`, which for some reason doesn't fall back on `PyNumber_Int`, instead trying to call the members directly.

**Comment by mattip** [comment]
That would add another layer of abstraction, slowing down the conversion for the 99% of the cases when a ``nb_int`` exists

**Comment by eric-wieser** [comment]
Right, but it also means that our implementation right now is incorrect. `int(x)` is also supposed to try `__trunc__` if `__int__` doesn't exist.

**Comment by eric-wieser** [comment]
Another example:
```
>>> a = np.array(None)
>>> a[()] = bytearray('10')
>>> int(a)
TypeError: cannot convert to an int; scalar object is not a number
>>> int(bytearray('10'))
10
```

**Comment by mattip** [comment]
#10042 fixed these. These now work
```
>>> a = np.array([b'100'])[0]
>>> int(a)
100
>>> a.__int__()
100
```
and 
```
>>> a = np.array(None)
>>> a[()] = bytearray(b'10')
>>> int(a)
10
```

**Comment by bsipocz** [comment]
It looks like everything works here now. Can this be closed @mattip?

**Comment by mattip** [comment]
Closing. Please reopen if more discrepancies appear
