### ISSUE TITLE
Why python2 tries to get data from python3 module ?

### ISSUE THREAD

**Issue by trDjango** [numpy/numpy#9979]
Hello ;

I get this error after installing Ros system.Firstly I run python from the terminal.
no problem if I do not run it from the terminal.
then import the numpy module and : 

```
system:ubuntu 16.04, ros lunar
Python 2.7.12  
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.5/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray

```

**Comment by njsmith** [comment]
It looks like your python installation is totally broken -- maybe you should contact who-ever provided your python? (I guess "ROS"?)

**Comment by seberg** [comment]
Maybe you got `PYTHONPATH` environment variable set to include the python 3.5 version or something similar to that anyway? You may want to check `sys.path` from within python. Anyway, this does not look like a numpy issue, but a broken python setup, so closing the issue, if you got another question feel free to ask.

**Comment by seberg** [comment]
Or, you were doing what the error warns you about, and you were actually running python inside the `/usr/local/lib/python3.5/dist-packages/` folder, which cannot work.
