### ISSUE TITLE
Slicing numpy array with numpy.ndarray datatype

### ISSUE THREAD

**Issue by pskeshu** [numpy/numpy#9990]
I was trying to find the maximum value in a 2D array and get the region around it like this:

```
img_max = np.max(image)
ix, iy = np.where(image == img_max)[0]
print(ix, iy)
print(type(ix), type(iy))
```

Here's the output for this code:
```
[342] [2462]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
```
So, the problem arises when I'm trying to slice the `image` array with `ix` and `iy`.

```
max_region = image[ix-4:ix+5,iy-4:iy+5]
```
which returns the following error: `TypeError: only integer scalar arrays can be converted to a scalar index`

To reproduce this behavior, here's a code snippet which will illustrate the issue in the code above:
```
>>> import numpy as np
>>> data = np.array(list(range(10)))
>>> data
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> x, y = np.array([1]), np.array([5])
>>> a, b = 1, 5
>>> data[a:b]
array([1, 2, 3, 4])
>>> data[x:y]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: only integer scalar arrays can be converted to a scalar index
```

Often, it does happen that one has to slice arrays with indices that are returned by numpy functions, so it can be very useful to be able to just do `data[x:y]` in the above code.

If this can be an useful addition to numpy, I'd be happy to submit a PR to incorporate such a change.

Please let me know your thoughts.

**Comment by seberg** [comment]
1. you can use argmax (though you have to do that on the ravelled array and use unravel_index)
2. This is intentional. If you know your array has only a single element that you want to use, we believe you can be expected to use `data[x[0]:y[0]]`. A 0d array asuch as `np.array(0)` works after all.
