### ISSUE TITLE
Add order='F' option for numpy.eye

### ISSUE THREAD

**Issue by dhermes** [numpy/numpy#9995]
For example, in the simplified case that the matrix is square:

```python
id_mat = np.zeros((N, N), order='F')
id_mat.flat[::N + 1] = 1.0
```

I'm happy to send a PR to add this as an extra kwarg, but I don't want to do it unless maintainers are open to it.

It may not be desired to add this. Two reasons come to mind:

- this would add a branch inside `np.eye` for **every** call, which could be a performance hit for code that relies heavily on `np.eye`
- this can already be achieved just by using `np.eye` and then taking the transpose

**Comment by eric-wieser** [comment]
Can you add some reasons why it _is_ desired to have this as well?

**Comment by dhermes** [comment]
For code that passes data into Fortran routines (via `f2py`, `ctypes`, `cffi`, Cython, etc.), it's quite helpful to be able to just pass a pointer to the data as-is. This is just a generic argument for having an `ndarray` in Fortran order, but I think it should apply to `np.eye()` just as well as it applies to `np.zeros()` or `np.empty()` (both of which have an `order` kwarg).

An argument "against" the "take the transpose" response would be data ownership:

```python
>>> import numpy as np
>>> id_mat = np.eye(3)
>>> id_mat.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
...
>>> id_mat.T.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
...
>>> 
>>> 
>>> id_mat = np.zeros((3, 3), order='F')
>>> id_mat.flat[::3 + 1] = 1.0
>>> id_mat
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])
>>> id_mat.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
...
```

**Comment by njsmith** [comment]
It seems unobjectionable to me.

**Comment by eric-wieser** [comment]
Thanks for the explanation - despite spending the last couple days dealing with fortran, I'd forgotten why that would be useful!

Seems pretty reasonable. An `out` argument might be nice too.

I wonder if no-input-argument ufuncs could become a thing...
